### ISSUE TITLE
Error when adding a question to a dashboard

### ISSUE THREAD

**Issue by AlixHn** [metabase/metabase#11854] opened 2020-02-04 13:47 UTC
**Describe the bug**
Every time I try to add a query to a dashboard (either by the query or by the dashboard), I get the error "Une erreur d'entrée/sortie a eu lieu lors d'envoi vers le serveur." ("An I/O error occurred while sending to the server.").

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)
`// https://metabase.trusk.com/api/card?f=all
{
  "message": "Une erreur d'entrée/sortie a eu lieu lors d'envoi vers le serveur.",
  "type": "class org.postgresql.util.PSQLException",
  "stacktrace": [
    "org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:335)",
    "org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)",
    "org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)",
    "org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)",
    "org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)",
    "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)",
    "clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1072)",
    "clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1066)",
    "clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1095)",
    "clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)",
    "clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)",
    "clojure.java.jdbc$query.invoke(jdbc.clj:1126)",
    "toucan.db$query.invokeStatic(db.clj:285)",
    "toucan.db$query.doInvoke(db.clj:281)",
    "clojure.lang.RestFn.invoke(RestFn.java:410)",
    "toucan.db$simple_select.invokeStatic(db.clj:391)",
    "toucan.db$simple_select.invoke(db.clj:380)",
    "toucan.db$select.invokeStatic(db.clj:659)",
    "toucan.db$select.doInvoke(db.clj:653)",
    "clojure.lang.RestFn.applyTo(RestFn.java:139)",
    "clojure.core$apply.invokeStatic(core.clj:667)",
    "clojure.core$apply.invoke(core.clj:660)",
    "toucan.db$select_field.invokeStatic(db.clj:682)",
    "toucan.db$select_field.doInvoke(db.clj:674)",
    "clojure.lang.RestFn.invoke(RestFn.java:521)",
    "--> api.card$hydrate_favorites.invokeStatic(card.clj:55)",
    "api.card$hydrate_favorites.invoke(card.clj:50)",
    "api.card$cards_for_filter_option.invokeStatic(card.clj:133)",
    "api.card$cards_for_filter_option.invoke(card.clj:131)",
    "api.card$fn__47785.invokeStatic(card.clj:156)",
    "api.card$fn__47785.invoke(card.clj:142)",
    "middleware.auth$enforce_authentication$fn__64168.invoke(auth.clj:14)",
    "routes$fn__65545$fn__65546.doInvoke(routes.clj:56)",
    "middleware.exceptions$catch_uncaught_exceptions$fn__64267.invoke(exceptions.clj:104)",
    "middleware.exceptions$catch_api_exceptions$fn__64264.invoke(exceptions.clj:92)",
    "middleware.log$log_api_call$fn__65919$fn__65920.invoke(log.clj:170)",
    "middleware.log$log_api_call$fn__65919.invoke(log.clj:164)",
    "middleware.security$add_security_headers$fn__64230.invoke(security.clj:122)",
    "middleware.json$wrap_json_body$fn__65624.invoke(json.clj:63)",
    "middleware.json$wrap_streamed_json_response$fn__65642.invoke(json.clj:97)",
    "middleware.session$bind_current_user$fn__60792$fn__60793.invoke(session.clj:209)",
    "middleware.session$do_with_current_user.invokeStatic(session.clj:184)",
    "middleware.session$do_with_current_user.invoke(session.clj:177)",
    "middleware.session$bind_current_user$fn__60792.invoke(session.clj:208)",
    "middleware.session$wrap_current_user_id$fn__60777.invoke(session.clj:161)",
    "middleware.session$wrap_session_id$fn__60762.invoke(session.clj:123)",
    "middleware.auth$wrap_api_key$fn__64176.invoke(auth.clj:27)",
    "middleware.misc$maybe_set_site_url$fn__65946.invoke(misc.clj:56)",
    "middleware.misc$bind_user_locale$fn__65949.invoke(misc.clj:72)",
    "middleware.misc$add_content_type$fn__65934.invoke(misc.clj:28)",
    "middleware.misc$disable_streaming_buffering$fn__65957.invoke(misc.clj:87)"
  ],
  "sql-exception-chain": [
    "PSQLException:",
    "Message: Une erreur d'entrée/sortie a eu lieu lors d'envoi vers le serveur.",
    "SQLState: 08006",
    "Error Code: 0"
  ]
}`

**To Reproduce**
1. Go on a query
2. Click on 'Add to a dashboard'
3. Click on a dashboard
4. The dashboard will show and few seconds later you'll see the error

**Expected behavior**
The query should be added to the dashboard.

**Screenshots**

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.4.0-166-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-11-19",
      "tag": "v0.33.6",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}

**Severity**
Really annoying

**Comment by dacort** [comment] 2020-02-06 05:06
Hi @AlixHn - I believe this was fixed in v0.34.0 of Metabase (relevant [pull request](https://github.com/metabase/metabase/pull/11018)). Please try upgrading to the latest version, [v0.34.2](https://github.com/metabase/metabase/releases/tag/v0.34.2), released today. 

Duplicate of #9648

**Closed by dacort** 2020-02-06 05:06 UTC
Labels: .Needs Triage, Type:Bug
