### ISSUE TITLE
Add a link from the admin to the home page

### ISSUE THREAD

**Issue by Chardonneaur** [metabase/metabase#11872] opened 2020-02-08 13:16 UTC
Hi there,
Here is a simple request, when I am in the admin panel and that I need to come back on the home page, I need to change the url in the address bar.
Maybe there is a link within the admin to go back easily on the home page but I cannot find it.

**Comment by flamber** [comment] 2020-02-08 15:41
Duplicate of #11529
You can back to home page by clicking the top-right gear (:gear:) and "Exit admin".

**Closed by flamber** 2020-02-08 15:41 UTC
Labels: .Duplicate
