### ISSUE TITLE
X-ray throws exception Non-terminating decimal expansion; no exact representable decimal result

### ISSUE THREAD

**Issue by on99** [metabase/metabase#6175] opened 2017-10-15 03:44 UTC
### Bugs
X-ray **int**, **decimal** columns throws exception but **float** won't.

- Browser: Version 61.0.3163.100 (Official Build) (64-bit)
- OS: macOS Sierra
- Database: MySQL
- Metabase: 0.26.1
- Metabase hosting environment: docker
- Metabase internal database: MySQL

#### Steps to reproduce:

data table schema and data:
```sql
create table xray (
i int,
d decimal(19,8),
f float,
created_at datetime
);

insert into xray values (1, 1.1, 2.5, '2017-10-15 05:00:00');
insert into xray values (1, 1.1, 2.5, '2017-10-15 06:00:00');
insert into xray values (1, 1.1, 2.5, '2017-10-15 07:00:00');
insert into xray values (1, 1.1, 2.5, '2017-10-15 08:00:00');
insert into xray values (1, 1.1, 2.5, '2017-10-15 09:00:00');
```

in metabase

* save a question ***sum(i) by created_at (hour)*** and X-ray this question (Exception)
* save a question ***sum(d) by created_at (hour)*** and X-ray this question (Exception)
* save a question ***sum(f) by created_at (hour)*** and X-ray this question (Works like a charm)

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by sbelak** [comment] 2017-10-18 10:29
Hm, I can't reproduce it. Can you give me your MySQL version and the full exception trace.

**Comment by on99** [comment] 2017-10-20 03:10
@sbelak 

### mysql versions

![image](https://user-images.githubusercontent.com/13196393/31803551-f87f342e-b586-11e7-9ba4-ea66849d1c2b.png)

### metabase stack trace

```
10-20 11:09:06 ERROR metabase.middleware :: GET /api/x-ray/card/7 500 (83 ms) (13 DB calls)
{:message "Non-terminating decimal expansion; no exact representable decimal result.",
 :stacktrace
 ["feature_extraction.core$field__GT_features.invokeStatic(core.clj:26)"
  "feature_extraction.core$field__GT_features.invoke(core.clj:23)"
  "feature_extraction.core$fn__43693.invokeStatic(core.clj:109)"
  "feature_extraction.core$fn__43693.invoke(core.clj:101)"
  "api.x_ray$fn__43757$fn__43758.invoke(x_ray.clj:79)"
  "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:248)"
  "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:243)"
  "api.x_ray$fn__43757.invokeStatic(x_ray.clj:71)"
  "api.x_ray$fn__43757.invoke(x_ray.clj:71)"
  "middleware$enforce_authentication$fn__29522.invoke(middleware.clj:122)"
  "api.routes$fn__43831.invokeStatic(routes.clj:65)"
  "api.routes$fn__43831.invoke(routes.clj:65)"
  "routes$fn__44402$fn__44403.doInvoke(routes.clj:75)"
  "routes$fn__44402.invokeStatic(routes.clj:71)"
  "routes$fn__44402.invoke(routes.clj:71)"
  "middleware$log_api_call$fn__29621$fn__29623.invoke(middleware.clj:330)"
  "middleware$log_api_call$fn__29621.invoke(middleware.clj:329)"
  "middleware$add_security_headers$fn__29571.invoke(middleware.clj:245)"
  "middleware$bind_current_user$fn__29526.invoke(middleware.clj:142)"
  "middleware$maybe_set_site_url$fn__29575.invoke(middleware.clj:268)"]}
```

**Comment by on99** [comment] 2017-10-20 03:33
@sbelak 

Sorry, it's not able to reproduce the exception with previous sample data set.

Here is the new one.

```sql
CREATE TABLE `xray` (
  `i` bigint(20) unsigned NOT NULL,
  `d` decimal(19,8) NOT NULL,
  `f` float NOT NULL,
  `created_at` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

insert into xray values (1010000, 110000000, 250000000, '2017-10-15 05:00:00');
insert into xray values (10100000, 110000000, 250000000, '2017-10-15 06:00:00');
insert into xray values (10000000, 110000000, 250000000, '2017-10-15 07:00:00');
insert into xray values (11000000, 110000000, 250000000, '2017-10-15 08:00:00');
insert into xray values (101000, 110000000, 250000000, '2017-10-15 09:00:00');
```

in metabase

* save a question ***sum(i) by created_at (hour)*** and X-ray this question (Exception)
* save a question ***sum(d) by created_at (hour)*** and X-ray this question (Works)
* save a question ***sum(f) by created_at (hour)*** and X-ray this question (Works)

Sorry for misleading.

**Comment by camsaul** [comment] 2017-11-15 01:28
@sbelak We have a function in `metabase.util` called `round-to-decimals` that might help fix this. Maybe just round these numbers to however many digits we need

**Comment by sbelak** [comment] 2017-11-15 09:33
@camsaul the error itself can be solved by with-precision, I'm having trouble understanding what causes it. It only manifests on some systems (Docker image so far. I've already eliminated differences in Java version/JDK. Will do some more digging

**Comment by camsaul** [comment] 2017-11-15 18:23
@sbelak maybe it's a difference between 32-bit and 64-bit JVMs?

**Comment by sbelak** [comment] 2018-05-04 20:06
Closing this as with 0.29 we are retiring this approach to xrays in favour of a dashboard-based one.

**Closed by sbelak** 2018-05-04 20:06 UTC
Labels: Bug, Priority/P2, X-Rays
