### ISSUE TITLE
Native Query "Explore results" button doesn't pull through variables

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#19041] opened 2021-11-18 22:07 UTC
**Describe the bug**
On a native SQL question that has a variable with a default value, if the variable value is specified (i.e. don't use the default) when the "Explore results" button is clicked the data pressed the data presented reverts back to the default value of the variable, not the filter explicitly set.

**Logs**
Not applicable

**To Reproduce**
1. Create native SQL question with a variable used as a filter, make it required and set a default value

**Expected behavior**

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.x. OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by flamber** [comment] 2021-11-18 22:12
Yeah, filters from SQL questions are not parsed through - only the default results - duplicate of #6449

**Closed by flamber** 2021-11-18 22:12 UTC
Labels: Type:Bug, .Needs Triage
