### ISSUE TITLE
A custom question based on a native sql question can't be filtered on the dashboard

### ISSUE THREAD

**Issue by stephanvd** [metabase/metabase#11270] opened 2019-11-06 08:55 UTC
**Describe the bug**
When showing a nested custom question on a dashboard and adding a filter of any type, The question is showing 'No valid fields' when there cleary are fields of the correct type available. The same filters for non-nested questions work fine.

**Logs**
```
Error getting setting table.columns TypeError: Cannot read property 'cols' of undefined
    at app-main.bundle.js?3f8f0db4d958de85c2e9:5
    at Function.v.every.v.all (vendor.bundle.js?3f8f0db4d958de85c2e9:1)
    at Object.isValid (app-main.bundle.js?3f8f0db4d958de85c2e9:5)
    at g (app-main.bundle.js?3f8f0db4d958de85c2e9:5)
    at t.getComputedSettings (app-main.bundle.js?3f8f0db4d958de85c2e9:5)
    at h (app-main.bundle.js?3f8f0db4d958de85c2e9:5)
    at t.value (app-main.bundle.js?3f8f0db4d958de85c2e9:5)
    at t.value (app-main.bundle.js?3f8f0db4d958de85c2e9:5)
    at u.performInitialMount (vendor.bundle.js?3f8f0db4d958de85c2e9:1)
    at u.mountComponent (vendor.bundle.js?3f8f0db4d958de85c2e9:1)
```

```
dataset::fieldRefForColumn mismatch
column product_type 
(3) ["field-literal", "product_type", "type/Text"]
new ["field-literal", "product_type", "type/Text"]
old null
```

```
app-main.bundle.js?3f8f0db4d958de85c2e9:5 TypeError: Cannot read property 'fields' of null
    at t.value (app-main.bundle.js?3f8f0db4d958de85c2e9:5)
    at Array.value (app-main.bundle.js?3f8f0db4d958de85c2e9:5)
    at app-main.bundle.js?3f8f0db4d958de85c2e9:5
    at Array.map (<anonymous>)
    at t.getMode (app-main.bundle.js?3f8f0db4d958de85c2e9:5)
    at Function.value (app-main.bundle.js?3f8f0db4d958de85c2e9:5)
    at e.value (app-main.bundle.js?3f8f0db4d958de85c2e9:5)
    at app-main.bundle.js?3f8f0db4d958de85c2e9:5
    at r (app-main.bundle.js?3f8f0db4d958de85c2e9:5)
    at e.n.value (app-main.bundle.js?3f8f0db4d958de85c2e9:5)
```

**To Reproduce**
1. Create a Native query
2. Create a Custom question based on the question from step 1.
3. Add the nested question to a dashboard
4. Add a filter to the dashboard
5. Try to attach the filter to the nested question
6. See 'No valid fields'

**Expected behavior**
I would expect the available fields for filtering to be equal to the list of fields available for filtering in the custom SQL question.

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:70.0) Gecko/20100101 Firefox/70.0",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.1+9",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "13.0.1+9",
    "os.name": "Linux",
    "os.version": "3.10.0-957.1.3.el7.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "date": "2019-10-07",
      "tag": "v0.33.4",
      "branch": "release-0.33.x",
      "hash": "9559406"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
This is blocking us from presenting reports to our customers. There is some pressure on us to deliver this soon. Our current workaround is to hard-code the dates.

**Additional context**
This seems related to another issue with nested queries we're seeing: #11028

**Comment by flamber** [comment] 2019-11-08 00:19
Hi @stephanvd 
I think you're seeing #9802 - read the comments, since it's not very well described.

**Comment by mazameli** [comment] 2019-11-18 18:22
Yeah, quite sure this is a duplicate of #9802. Let me know if you disagree @stephanvd

**Closed by mazameli** 2019-11-18 18:22 UTC
Labels: .Duplicate
