### ISSUE TITLE
Performance issues with Data Reference Page

### ISSUE THREAD

**Issue by flashput** [metabase/metabase#6152] opened 2017-10-12 01:51 UTC
![image](https://user-images.githubusercontent.com/11661814/31475211-2fb862d0-aec5-11e7-92e0-f86f2c4d45d3.png)

with large  database/schemas (say contains 10000+ tables), visiting "Data Reference" may become extremely slow, metadata request could get too much from server api.

**Comment by salsakran** [comment] 2017-10-12 17:30
dupe of #5106

**Closed by salsakran** 2017-10-12 17:30 UTC
