### ISSUE TITLE
Top menu still displayed when entering fullscreen from a browser action

### ISSUE THREAD

**Issue by MarcSamD** [metabase/metabase#19029] opened 2021-11-18 09:59 UTC
**Describe the bug**
1) When entering fullscreen from the browser side (typing F11 or using kiosk mode), the top menu (with search bar) is still displayed
2) Adding "#fullscreen" at the end of the URL is not changing the page display at all. Instead the "#fullscreen" is automatically removed from the URL.

**Expected behavior**
1) The top menu should be hidden when the browser enter in fullscreen (whatever the method). I guess this can be detected by a script.
2) Despite it is not possible anymore to set the browser in fullscreen from a URL parameters (see #10876 and #10896), at least the "#fullscreen" URL option should be preserved and should remove the top menu. So a combination of the "#fullscreen" URL and the browser kiosk mode will allow to display a full and maximized dashboard without user interaction.

Only implement 1 of the 2 behavior above will be enough to solve this issue on my side.

**Screenshots**
Issue:
![image](https://user-images.githubusercontent.com/70358310/142385242-e939427a-e61f-4337-b47c-d1003512a9bb.png)
_Page displayed when typing on F11 (tested on both Edge and Firefox)._
.
.
.
.
Expected:
![image](https://user-images.githubusercontent.com/70358310/142388755-be1e386d-379a-403f-a74b-1707e9182ecb.png)
_Page displayed when clicking on Metabase arrows icon "Enter fullscreen"._

**Information about your Metabase Installation:**
Metabase 0.41.2

**Severity**
Low

**Comment by flamber** [comment] 2021-11-18 10:12
Hi @MarcSamD 
That's not a bug.
Metabase has never removed the header in F11-mode. Only when the fullscreen-button was clicked on dashboards.
And as for the `#fullscreen` being removed, that's similar to https://github.com/metabase/metabase/issues/7133#issuecomment-465746919, where you have to do it in a new tab.

**Comment by MarcSamD** [comment] 2021-11-23 09:24
> you have to do it in a new tab.

That was the information I was missing !
So on my side this ticket can be closed, but I suggest to update the [user guide](https://www.metabase.com/docs/latest/users-guide/07-dashboards.html#configuring-a-dashboard-through-its-url) to mention this mandatory requirement.

Thanks @flamber as usual

**Comment by flamber** [comment] 2021-11-23 09:35
@MarcSamD Then let's keep this open, since if there isn't an issue open, then it's easy to overlook.

**Comment by brunobergher** [comment] 2024-12-30 12:13
`#fullscreen` works in the same tab now, closing.

**Closed by brunobergher** 2024-12-30 12:13 UTC
Labels: Type:UX, Priority:P3, Reporting/Dashboards
