### ISSUE TITLE
Data missing in all visualization except the table view

### ISSUE THREAD

**Issue by StaymanHou** [metabase/metabase#6370] opened 2017-11-13 21:10 UTC
Please check screenshots attached below. Exact same query. October numbers are present in the table visualization but missing in the bar visualization ( other visualization, too ).

![selection_533](https://user-images.githubusercontent.com/5069041/32749334-126cddfa-c88d-11e7-8665-4d9be5cdc62e.png)

![selection_534](https://user-images.githubusercontent.com/5069041/32749345-171dfa50-c88d-11e7-902e-62112a752490.png)

**Comment by attekei** [comment] 2018-01-20 18:12
Line/area/bar x-axis marks are are off basically all the time, and this applies also to other date grouping granularities. See for instance this example:
<img width="1155" alt="screen shot 2018-01-20 at 20 11 25" src="https://user-images.githubusercontent.com/6034928/35186522-44216250-fe1e-11e7-9004-e2c8942c34a2.png">

**Comment by tlrobinson** [comment] 2018-01-25 14:44
I'm having a hard time reproducing this. For time related bugs it's useful to know the following:

* time zone of the database host, Metabase host, and your browser
* the "Report Timezone" Metabase setting
* it's useful to have the raw data from the query, you can get it from the network panel of the browser developer tools
* even better if you can reproduce it using the "Sample Dataset"

Thanks.

**Comment by flamber** [comment] 2019-06-20 19:14
Hi @StaymanHou 
Are you still experiencing this issue in the latest version 0.32.9? Can you provide more information?
I think this might be a duplicate of #5246

**Comment by salsakran** [comment] 2019-08-05 05:15
closing since we've fixed a lot of timezone bugs since this report, there's no clear reproduction and we don't have enough information to determine if this isn't a fixed or other open TZ bug.

**Closed by salsakran** 2019-08-05 05:15 UTC
Labels: Priority:P1, Timezones/Calendars, Type:Bug
