### ISSUE TITLE
The date filter popup is not respecting the date format configuration

### ISSUE THREAD

**Issue by tatusis** [metabase/metabase#12622] opened 2020-05-30 03:48 UTC
**The date filter popup is not respecting the date format configuration**

When you click on the date filter to select a specific date, the date is always displayed in MM / DD / YYYY format. Even if the setting is DD / MM / YYYY.

**To Reproduce**
1. Click on a date column header.
2. Choose to filter by a specific date.
3. The field will display the date in MM / DD / YYYY format.

**Expected behavior**
The date field filter popup is expected to display the date in the configured format.

**Screenshots**

![image](https://user-images.githubusercontent.com/55719904/83318802-8dc59700-a20e-11ea-95b5-8db7ad621317.png)

![image](https://user-images.githubusercontent.com/55719904/83318817-a5048480-a20e-11ea-9e42-c89682e342a5.png)

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_241-b07",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_241",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.241-b07",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "America/Sao_Paulo"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "oracle",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.14"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.3",
      "date": "2020-04-21",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
This error can induce the user to perform a wrong filter when changing the month for the day or the reverse.

**Comment by flamber** [comment] 2020-05-30 09:43
Duplicate of #9151

**Closed by flamber** 2020-05-30 09:43 UTC
Labels: .Needs Triage, Type:Bug
