### ISSUE TITLE
Don't show Saved Questions "virtual" DB in Data Reference

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#5417] opened 2017-06-30 19:15 UTC
~should be as simple as making sure not to include `&include_cards=true` in the API call.~

It turns out the Data Reference relies on the same data in the redux store as the Query Builder so only one API call is ever made; thus we can't remove the `&include_cards=true` param without breaking the QB. Instead I think we should just filter out the Saved Questions DB client-side; if we want to fix this the right way (we do), we should include an extra column in the DBs response called `is_saved_questions` (similar to what we do for the Sample Dataset) or something like that. Note that that will likely require some backend test updates

**Comment by camsaul** [comment] 2017-06-30 19:29
Sounds like this should be taken care of in @salsakran's pending cleanup of the Data Reference code

**Comment by salsakran** [comment] 2017-07-10 04:30
I think as part of a follow-on for  #5354, we shouldn't be loading everything under the sun for the data reference. This is the sort of thing that should be trivial.

**Comment by camsaul** [comment] 2017-07-10 16:31
@salsakran it turns out the the data reference loads the same exact data as the query builder and then that data gets cached for either use case

**Comment by salsakran** [comment] 2017-07-10 17:03
Yeah, the problem is that in some cases, that's a little nuts. Eg, there's at least one case of someone running us on a DB with 5M fields. On the data reference main page, we also load up the entire set of dashboards, segments and metrics every time someone clicks on it. Kinda nuts and something we need to unwind.

**Comment by salsakran** [comment] 2017-07-25 00:37
closed via #5565

**Closed by salsakran** 2017-07-25 00:37 UTC
Labels: Nested Queries
