### ISSUE TITLE
Feature Request/Bug: Limited Colors for Bar Chart Stacking Option

### ISSUE THREAD

**Issue by kritop** [metabase/metabase#3633] opened 2016-10-19 15:19 UTC
- Your browser and the version: Chrome 54
- Your operating system: OS X Sierra
- Your databases: MysQL
- Metabase version: 0.20.1
- Metabase hosting environment: Heroku
- Metabase internal database: default

see here

http://look.neta.io/hotJ

I can only select 5 different colors, even if i can stack way more values.

**Comment by mazameli** [comment] 2016-10-19 17:03
Hmm, yeah, we should be using the same logic for extra colors here as we do for pie/donut charts. Is this a bug or a limitation @tlrobinson / @kdoh ?

**Comment by kdoh** [comment] 2016-10-19 17:12
I think this is just an oversight. We just need to apply the same color harmony to bar charts we do to pie slices when the number of slices is > 5. 

It'd be rad if we could find a way to standardize that logic across all our chart types.

**Comment by tlrobinson** [comment] 2016-10-19 17:21
Sort of a duplicate of #3185.

Do we want all of those colors to appear in the picker, or maybe have a custom color picker?

**Comment by kritop** [comment] 2016-10-19 20:59
thanks for looking into this! is there a general limit, because it seems sometime if the "stackable" axis is to large it just fails to produce a bar chart?

**Comment by camsaul** [comment] 2016-12-08 21:37
@kritop, this isn't a bug 😒

**Comment by camsaul** [comment] 2016-12-08 21:39
@tlrobinson I think this does sound like a duplicate of #3185

**Comment by camsaul** [comment] 2017-01-09 18:02
Duplicate of #3185

**Closed by camsaul** 2017-01-09 18:02 UTC
Labels: Bug, Visualization
