### ISSUE TITLE
Date Format in Pulses cannot be understood by excel and doesn't respect defaults.

### ISSUE THREAD

**Issue by calvinthomas150** [metabase/metabase#11828] opened 2020-01-30 11:39 UTC
**Is your feature request related to a problem? Please describe.**
Currently we try to use pulses for end of month reporting. As the data changes for these reports frequently the time they are run is important and pulses solve this problem however the reports are then used via excel which cannot understand the date/time format used in the pulse 'YYYY-MM-DDZhh:mm:ssZ.

If the report was exported from metabase manually the question formatting is respected and hence the dates are formatted as required (dd/mm/yyyy) in our case.

**Describe the solution you'd like**
Ideally for the date format from questions or even global to be respected. Alternatively, the default it uses to be a format understood by excel (e.g. YYYY-MM-DD hh:mm:ss)

**Describe alternatives you've considered**
The best workarounds we have at the moment is to run the reports manually or to fiddle with the formatting in excel afterwards through macros or find and replace which is difficult for inexperienced users.

**How important is this feature to you?**
Fairly important as it removes need for manual task and some lack of confidence from users in the tool.

**Additional context**
None

**Comment by notrom** [comment] 2020-01-30 20:18
I think this is probably related to #10803 which is about date formats in exported files. Would be great to get both fixed as the manual manipulation required in excel after the export drives my users crazy.

**Comment by flamber** [comment] 2020-02-05 19:28
Duplicate of #10803

**Closed by flamber** 2020-02-05 19:28 UTC
Labels: .Duplicate
