### ISSUE TITLE
sync the format of DateRangeWidget.jsx from Localization setting

### ISSUE THREAD

**Issue by hanfengcan** [metabase/metabase#17544] opened 2021-08-22 02:54 UTC
Hi, I found the format of DateRangeWidget.jsx is fixed `MMMM D, YYYY`. Would it be better if you could display the format according to the Settings.

Or The `YYYY-MM-DD` is better more.

![image](https://user-images.githubusercontent.com/4559753/130340277-3105da6c-bc61-431a-8e1b-d1d8056eb82e.png)

![image](https://user-images.githubusercontent.com/4559753/130340198-fde0d7a8-b9d0-44fe-992e-2f7c7d61a1f1.png)

**Comment by flamber** [comment] 2021-08-22 15:15
Duplicate of #9151

**Closed by flamber** 2021-08-22 15:15 UTC
Labels: Type:New Feature, .Needs Triage
