### ISSUE TITLE
It is possible to add an empty dashboard filter (contains)

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#15462] opened 2021-04-02 16:58 UTC
**Describe the bug**
When using new dashboard filters, it is possible to set empty value.

**Logs**
N/A

**To Reproduce**
1. Go to dashboard with at least one card on it
2. Click on pencil icon to edit the dashboard
3. Click on filter icon to add a filter to the dashboard
4. Choose "Other categories" > Contains
5. Connect it to a column in the question on a dashboard
6. Save the dashboard
7. Click on that filter widget - you can type and "Add filter" button is correctly disabled
8. Enter a letter or two - observe that the list of values appear and "Add filter" button is now enabled
9. Delete what you typed
10. "Add filter" stays enabled and you can now click on it adding an empty filter value

**Expected behavior**
"Add filter" button should go back to disabled state when there is no input value, or when it is deleted.

**Screenshots**
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/KoudQBmy/1eb8430f-1401-4b4d-a16f-4c9c57f1e1b6.gif?source=viewer&v=a74a3fb4b3702cc950ca9637c4d7e158)

**Information about your Metabase Installation:**
- v0.39.0-SNAPSHOT
- Built on 2021-04-01src_hash=a6e9f576a52174cff5ecaa741cd4fed22cbae3e9
- Branch: master
- Hash: dfa9398

**Severity**
Low.

**Comment by WiNloSt** [comment] 2023-07-20 07:57
Couldn't reproduce on `master` @ 31d934c527e184b3d401a5775a9bdfbd5b1be723.

I have tested 2 filters. Text contains and location contains.
- ![image](https://github.com/metabase/metabase/assets/1937582/bcef4364-2318-42c5-9366-4f576f0b101a)
- ![image](https://github.com/metabase/metabase/assets/1937582/bfa46adb-0474-4c52-992c-b68c425ed0b4)

CC @NevRA Is it safe to close the issue?

**Comment by WiNloSt** [comment] 2023-07-24 06:33
We should add E2E test(s) for this. [Ref](https://metaboat.slack.com/archives/C057LE0Q4PQ/p1689953430097339?thread_ts=1689865605.974619&cid=C057LE0Q4PQ)

**Comment by NevRA** [comment] 2023-07-24 07:40
@WiNloSt is it possible to add integration tests here? not e2e

**Closed** 2023-07-31 10:28 UTC
Labels: Type:Bug, Priority:P3, Reporting/Dashboards, Querying/Parameters & Variables, .Frontend, .Team/42 :milky_way:, .BugScope42

**Comment by WiNloSt** [comment] 2023-08-15 06:11
Can't reproduced on v0.46.7
