### ISSUE TITLE
jsonb query is returning empty result

### ISSUE THREAD

**Issue by flynfish** [metabase/metabase#13872] opened 2020-11-23 22:01 UTC
**Describe the bug**
JSONB query no longer works and returns "No Results!". This was working before a recent metabase update (not sure which version broke it). I can run this query on the Postgres instance and it works correctly. 

```
SELECT test.*
    FROM
      filethis_sources,
      jsonb_to_recordset(filethis_sources.sources->'sources') AS test(id int, name text)
    ORDER BY id
```

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**Severity**
Affecting queries our product team uses, so moderate severity. 

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_272-heroku-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_272-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.272-b10",
    "os.name": "Linux",
    "os.version": "4.4.0-1081-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.4 (Ubuntu 12.4-1.pgdg16.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.37.2",
      "date": "2020-11-16",
      "branch": "release-x.37.x",
      "hash": "25e5f70"
    },
    "settings": {
      "report-timezone": "US/Mountain"
    }
  }
}
```

**Comment by flamber** [comment] 2020-11-24 14:23
Hi @flynfish 
It would be very helpful if you could figure out which version you where using before.
And check Admin > Troubleshooting > Logs for activity, when you run the query.

**Comment by flynfish** [comment] 2020-11-24 17:22
@flamber Unfortunately I can't say exactly when it broke because I'm unsure of the last time our product team accessed this particular question. We were on `v0.37.0.2` when it was discovered as not working, so I upgraded to `0.37.2` to check if there was a fix for it. 

Before `0.37.02` I think we were on a `.35.*` version. Looking at the git history, I made updates to the latest version on:
4-8-2020
8-17-2020
11-2-2020
11-23-2020

So based on that, I would think that the breaking change was from the 11-2-2020 update to `.37..02`. It looks like `.36.4` was released on 8-17 so that is the version we were on before. 

Sorry, I don't have more specifics, I hope the timeline above is a little helpful. I also don't see anything in the logfile for this query, so it isn't erroring out from what I can tell. 

Let me know if I can provide any other info!

**Comment by flamber** [comment] 2020-11-24 17:46
@flynfish Okay, it was very helpful with the version information. Can you check your Postgres server log to see if you can log the query, since I don't see anything around 0.36.4, which should be causing an empty result like this, while the query runs correctly.

**Comment by flamber** [comment] 2020-12-04 21:54
@flynfish Can you supply a sample object. I cannot reproduce.

**Comment by flynfish** [comment] 2020-12-05 00:17
Ok, so I was able to get a sample object and in doing so, I found the issue. It has to do with what is stored in the jsonb column:

This works correctly in metabase and also psql command line:

```
save this in the jsonb field: {"sources": [{"id": 1,"name": "test"},{"id": 2,"name": "test_2"}]}

SELECT test.*
    FROM
      brandings,
      jsonb_to_recordset(brandings.colors->'sources') AS test(id int, name text)
    ORDER BY id
```
Result in metabase:
<img width="228" alt="Screen Shot 2020-12-04 at 5 11 44 PM" src="https://user-images.githubusercontent.com/253936/101227065-d9407e00-3653-11eb-919f-377d6fdd3c15.png">

When a json escaped value into the jsonb column, no result is returned:
```
"{\"sources\":[{\"id\":3,\"name\":\"test2\"}]}"
```
A fix would be to remove the escapes from our data..just wondering why it used to work and doesn't anymore

**Comment by flamber** [comment] 2020-12-05 12:31
@flynfish Great. I don't know how you can even do a query in psql, when the object is escaped. I'm not getting any results in psql.
And I'm not getting any results in 0.36.4 or 0.37.2 either.
Only when I run the query on the "correct" unescaped column, then it works in psql, 0.36.4 and 0.37.2
I have never seen a stored jsonb escaped like that. You should probably use single-quote around the object on insert, like:
`INSERT INTO brandings (colors) VALUES ('{"sources":[{"id":3,"name":"test2"}]}'::jsonb);`
Closing this, since I cannot reproduce.

**Closed by flamber** 2020-12-05 12:31 UTC
Labels: .Needs Triage, Type:Bug
