### ISSUE TITLE
Impossible to copy any value from resulting table

### ISSUE THREAD

**Issue by M4zD4i** [metabase/metabase#6247] opened 2017-10-24 09:11 UTC
- Your browser and the version: Safari 11.0 (12604.1.38.1.7)
- Your operating system: MacOS Sierra 10.12.6
- Your databases: Apache Impala
- Metabase version: fork from 0.26.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

Steps to reproduce:
1. Run some query in Builder to get resulting table
2. Try to select:
- value in some cell
- row
- all table
3. Try to copy selected data (Ctrl/Cmd+C or context menu)
4. Paste "copied" data

As result there are no data was copied from table. Even if we use Ctrl/Cmd+A to select all page content we have copied Builder and table titles only.

There is only one way to copy data at this time – use the page source in development tools of the browser

**Comment by flamber** [comment] 2019-02-17 22:42
Hi @M4zD4i 
I cannot reproduce your issue on 0.31.2 with Firefox 65 or Chromium 71.
Do you still have this issue in newer versions of Metabase? Or is this a Safari specific issue?

**Comment by flamber** [comment] 2021-11-07 18:21
Closing in favor of #4425

**Closed by flamber** 2021-11-07 18:21 UTC
Labels: Type:UX, .Proposal, Visualization/
