### ISSUE TITLE
Dashboards Filters stopped working in v19

### ISSUE THREAD

**Issue by cagiraudo** [metabase/metabase#3292] opened 2016-08-31 20:29 UTC
Hi,

I don't know if it was already reported, i couldn't find it

I was using metabase v18 and i had a dashboard with a month-year dashboard filter. And now with v19 the filter still works but i can't add it to a new question and when i try to edit it says No Valid Field in the questions that it is working.

Here you can see that the filter is working:
![seleccion_109](https://cloud.githubusercontent.com/assets/19225821/18145037/e23902ea-6f9f-11e6-9a9b-f236108dc2ef.png)

If i change the month the questions change
![seleccion_110](https://cloud.githubusercontent.com/assets/19225821/18145098/1b9e30b4-6fa0-11e6-9a76-b016eae9e684.png)

But when i edit the filter i get the No Valid Field in the questions that already work and the new ones.
![seleccion_111](https://cloud.githubusercontent.com/assets/19225821/18145138/4426aee4-6fa0-11e6-8280-9cca1a54dfb6.png)

### Bug Report Info

If this is a bug report, help us diagnose your issue by checking the appropriate boxes below:

*  I'm using this browser:
   - [x] Chrome
   - [ ] Firefox
   - [ ] Safari
   - [ ] Internet Explorer / Edge
   - [ ] Other: ____________________
*  My computer's OS is:
   - [ ] OS X
   - [ ] Windows
   - [x] Linux
   - [ ] Other: ____________________
*  I'm running Metabase:
   - [x] Locally from the JAR
   - [ ] Locally with the Mac App
   - [ ] On AWS (via Docker)
   - [ ] On Heroku
   - [ ] Other: ____________________
* *Internally*, Metabase is using this database: (This is the database Metabase stores internal information like accounts and dashboards in, *not* one you're running queries against. If you haven't done anything special to configure this, Metabase defaults to using H2 when running locally; if you're running Metabase on AWS or Heroku using the provided scripts/instructions, you're most likely using Postgres.):
   - [ ] H2
   - [ ] Postgres
   - [x] MySQL
*  My data is in a database of this type:
   - [ ] Postgres
   - [x] MySQL
   - [ ] Redshift
   - [ ] BigQuery
   - [ ] MongoDB
   - [ ] SQLite
   - [ ] Druid
   - [ ] SQL Server
   - [ ] Crate
   - [ ] Oracle
   - [ ] Other: ____________________
*  I'm using Metabase version:
   - [ ] 0.18.0
   - [ ] 0.18.1
   - [x] 0.19.0
   - [ ] 0.19.1
   - [ ] 0.19.2
   - [ ] 0.19.3
   - [ ] Other: ____________________

**Comment by mazameli** [comment] 2016-08-31 21:09
I believe this is a dupe of #3096, which was fixed in v0.19.1

**Closed** 2016-08-31 21:10 UTC
Labels: Duplicate
