### ISSUE TITLE
Menu on mobile is broken

### ISSUE THREAD

**Issue by MixMe** [metabase/metabase#4676] opened 2017-04-03 19:14 UTC
Menu is broken on low resolutions(any mobile):

![mobile_version](https://cloud.githubusercontent.com/assets/3535911/24626697/c9bf6c8a-18ba-11e7-87b2-bc346244cdc3.jpg)

**Comment by mazameli** [comment] 2017-04-03 19:16
Dupe of #3194

**Closed by mazameli** 2017-04-03 19:16 UTC
Labels: Duplicate
