### ISSUE TITLE
Question not being exported correctly on public shared link with filters

### ISSUE THREAD

**Issue by samuelbwr** [metabase/metabase#5728] opened 2017-08-11 14:41 UTC
The export function on public shared questions does not export the updated list according to the defined custom filters.

- Your browser and the version: Chrome 57
- Your operating system: Ubuntu 15.10
- Your databases: Mysql
- Metabase version: v0.24.1
- Metabase hosting environment: Elastic BeanStalk
- Metabase internal database: Postgres

-- *Repeatable steps to reproduce the issue*
1. Create a question on metabase and use custom variables with default values
2. Enable public sharing and access the public link
3. Export with no filters change
4. Change the filters
5. Export again
6. Check the result of step 3 and 5, the result is the same.

**Comment by attekei** [comment] 2017-08-11 16:22
Seems like a duplicate of #5674.

**Closed by attekei** 2017-08-11 16:22 UTC
