### ISSUE TITLE
Sometimes, Metabase not respond to PUT /api/permissions/graph

### ISSUE THREAD

**Issue by RomantsovArtur** [metabase/metabase#33912] opened 2023-09-16 21:37 UTC
### Describe the bug

Hi, 

Thanks a lot for developing Metabase. It's a fantastic product!

We've been using the latest version of it for a while now, and starting a few months, maybe a bit more, we began to see that when we submit a PUT /api/permissions/graph, it's somewhat stuck and dies after the reverse-proxy timeout (15 minutes). If we restart the Metabase instance, all goes okay until after a day or so it gets stuck again.

I'm happy to provide move any more information required to help debugging the issue.

### To Reproduce

1. Send a new permission graph via API PUT /api/permissions/graph
2. It can't be completed in 15 minutes and being killed by a reverse-proxy timeout

### Expected behavior

Permission graph got updated

### Logs

[metabase_logs.txt](https://github.com/metabase/metabase/files/12641608/metabase_logs.txt)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "5.10.176+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "exasol",
      "starburst",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-07-24",
      "tag": "v0.46.6.2",
      "branch": "patch-google-sso-button",
      "hash": "a4c740a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Blocking permission updates

**Comment by RomantsovArtur** [comment] 2023-09-16 21:38
We run Metabase in K8s using powerful machine and we don't see any utilisation that could have caused the issue
<img width="1427" alt="image" src="https://github.com/metabase/metabase/assets/40241717/eeaa6b5b-8df7-4d38-b6f8-489f0e1d7d2a">

**Comment by RomantsovArtur** [comment] 2023-09-16 21:52
If we restart the instance, the PUT request takes around a minute to complete.
We do have a lot of DBs/Connections

Is there any way possibly to update this graph not at full?

**Comment by paoliniluis** [comment] 2023-09-17 04:53
Duplicate of https://github.com/metabase/metabase/issues/30474

**Closed by paoliniluis** 2023-09-17 04:53 UTC
Labels: Type:Bug, .Needs Triage
