### ISSUE TITLE
Custom column is not available with BigQuery table

### ISSUE THREAD

**Issue by tamvm** [metabase/metabase#12999] opened 2020-07-25 22:23 UTC
**Describe the bug**
Custom column is not available with BigQuery table. I have tried with Postgresql table, and I can see that feature while I don't see in BigQuery table.

**To Reproduce**
1. Create new question with BigQuery table
2. There's no option to create custom column

**Expected behavior**
https://www.metabase.com/docs/latest/users-guide/custom-questions.html#creating-custom-columns
Should see custom column icon to click on

**Screenshots**
<img width="1312" alt="compact_log_failed_by_query_path_·_Metabase" src="https://user-images.githubusercontent.com/344684/88467310-2a5b9b00-cf19-11ea-855d-98e396fece30.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Version 84.0.4147.89 (Official Build) (64-bit)
- Your operating system: MacOS
- Your databases: BigQuery
- Metabase version: 3.6
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Low priority

**Comment by flamber** [comment] 2020-07-26 08:37
Duplicate of #9382

**Closed by flamber** 2020-07-26 08:37 UTC
Labels: .Needs Triage, Type:Bug
