### ISSUE TITLE
Remove or add field in setup or notebook will change existing column order settings 

### ISSUE THREAD

**Issue by chendanli** [metabase/metabase#20410] opened 2022-02-10 03:03 UTC
**Describe the bug**
When I add or delete fields in the setup or notebook, the original adjusted field order will be reset.

**Logs**
don't have

**To Reproduce**
1. Reordered the columns
2. Removed a field in notebook or setup 
3. Click visualize
4. Original adjusted column order changed

**Expected behavior**
hope that the set column order will not be changed.

**Screenshots**
![GIF1](https://user-images.githubusercontent.com/92294741/153328790-46ce7841-80b4-4be0-8976-3d57b5bac380.gif)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 95.0.4638.69
- Your operating system: Windows 10.1607
- Your databases: Postgres
- Metabase version: v0.41.3.1
- Metabase hosting environment:I don‘t know
- Metabase internal database:I don‘t know

**Severity**
When there are many fields, it can cause inconvenience

**Additional context**

**Comment by flamber** [comment] 2022-02-10 08:50
You should upgrade immediately to a newer release: https://github.com/metabase/metabase/releases
Duplicate of #13455

**Closed by flamber** 2022-02-10 08:50 UTC
Labels: Type:Bug, .Needs Triage
