### ISSUE TITLE
Sub-path of SITE URL (Reverse proxy, metabase located at `/metabase`) stripped in "Custom destination" click behavior

### ISSUE THREAD

**Issue by exetico** [metabase/metabase#21313] opened 2022-03-29 10:39 UTC
**Describe the bug**
I've defined "https://" "domain.com/metabase" as my SITE URL, and it's working great.

However... 

If I create a "Click behavior" in a table within a dashboard, and adding a "Custom destination" to "Dashboard Y", Metabase are sending me to `https://domain.com/dashboard/24` instead of  `https://domain.com/metabase/24`.

It's stripping the sub-path.

**To Reproduce**
1. Add SITE URL with subpath like `domain.com/metabase`
2. Save settings and validate that the subpath are now resolved as it should
3. Create a table with data
4. Add Click behavior to column
5. Select "Dashboard"
6. Use the link
7. Metabase are now trying to send the user to  `https://domain.com/24` (where `/metabase` is removed from the path)

**Expected behavior**
Metabase should keep the sub-path

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your databases: Mulitple, but not relevant for the problem
- Metabase version: v0.41.4
- Metabase hosting environment: Docker
- Metabase internal database: MariaDB

**Severity**
It's annoying. 

But there's a workaround. It's possible to instead using the "Custom url" and just creating the URL manually like
`https://domain.com/metabase/dashboard/24?daysAmount=360&titel={{subject}}`

**Comment by flamber** [comment] 2022-03-29 10:54
Duplicate of #13602

**Closed by flamber** 2022-03-29 10:54 UTC
Labels: Type:Bug, .Needs Triage
