### ISSUE TITLE
Incorrect display of group size

### ISSUE THREAD

**Issue by gvwilson** [metabase/metabase#16516] opened 2021-06-09 12:45 UTC
**Describe the bug**

After adding a person to a group, the group size is shown as 0 instead of 1.

**Logs**

**To Reproduce**

1. Fresh instance of Metabase.
2. Create a group called 'Human Resources'.
3. Create a new user called 'Farrah Zubin' and put that user in 'Human Resources'.

Display of groups in Admin shows 0 people in 'Human Resources'.
![Screen Shot 2021-06-09 at 8 37 38 AM](https://user-images.githubusercontent.com/911566/121356022-7bd90280-c8fe-11eb-9004-7eabb432136b.png)

Clicking on 'Human Resources' shows one person in the group.
![Screen Shot 2021-06-09 at 8 37 47 AM](https://user-images.githubusercontent.com/911566/121356062-84c9d400-c8fe-11eb-978a-51391a4badea.png)

Note: After logging in as Farrah in an incognito window and going to 'Account Settings', group memberships are *not* displayed, i.e., Farrah can't see what groups she belongs to. That seems weird, but is a design issue rather than a bug (?).

![Screen Shot 2021-06-09 at 8 42 21 AM](https://user-images.githubusercontent.com/911566/121356284-b347af00-c8fe-11eb-9c23-b1192ce03919.png)

**Expected behavior**

Group membership count should show 1 instead of 0 when there is one person in the group.

**Information about your Metabase Installation:**

Using Firefox on MacOS, Metabase details below.

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_291-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_291",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.291-b10",
    "os.name": "Mac OS X",
    "os.version": "10.16",
    "user.language": "en",
    "user.timezone": "America/Toronto"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "vUNKNOWN",
      "date": "2021-05-17",
      "branch": "master",
      "hash": "9700fe5"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

Recent log entries:

```
2021-06-09 08:42:07,927 DEBUG middleware.log :: POST /api/session 200 348.0 ms (8 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (4 idle, 0 queued) (52 total active threads) Queries in flight: 0 (0 queued)
2021-06-09 08:42:07,980 DEBUG middleware.log :: GET /api/session/properties 200 14.7 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (4 idle, 0 queued) (52 total active threads) Queries in flight: 0 (0 queued)
2021-06-09 08:42:07,981 DEBUG middleware.log :: GET /api/user/current 200 15.5 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (4 idle, 0 queued) (52 total active threads) Queries in flight: 0 (0 queued)
2021-06-09 08:42:08,031 DEBUG middleware.log :: GET /api/database 200 20.3 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (4 idle, 0 queued) (52 total active threads) Queries in flight: 0 (0 queued)
2021-06-09 08:42:08,068 DEBUG middleware.log :: GET /api/collection/root/items 200 41.1 ms (8 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (4 idle, 0 queued) (52 total active threads) Queries in flight: 0 (0 queued)
2021-06-09 08:42:08,106 DEBUG middleware.log :: GET /api/collection/root 200 7.3 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 8/50 (4 idle, 0 queued) (52 total active threads) Queries in flight: 0 (0 queued)
2021-06-09 08:42:08,153 DEBUG middleware.log :: GET /api/database 200 11.5 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (4 idle, 0 queued) (52 total active threads) Queries in flight: 0 (0 queued)
2021-06-09 08:42:08,216 DEBUG middleware.log :: GET /api/automagic-dashboards/database/1/candidates 200 47.8 ms (6 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (4 idle, 0 queued) (52 total active threads) Queries in flight: 0 (0 queued)
2021-06-09 08:43:40,231 DEBUG middleware.log :: GET /api/util/bug_report_details 200 34.3 ms (1 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (10 idle, 0 queued) (51 total active threads) Queries in flight: 0 (0 queued)
```

**Severity**

The incorrect report misled me into thinking I hadn't added the user to the group - wasted some time, but as far as I can tell, the group membership stuck.

**Additional context**

Situation came up while prepping for a demo of sandboxing & permissions.

**Comment by flamber** [comment] 2021-06-09 12:52
Duplicate of #12693 - doing a browser refresh will correct it.

**Closed by flamber** 2021-06-09 12:52 UTC
Labels: .Needs Triage, Type:Bug
