### ISSUE TITLE
Bigquery Project Id with Service Accounts

### ISSUE THREAD

**Issue by stujo** [metabase/metabase#16863] opened 2021-07-02 00:47 UTC
Swapping an OAuth credential for a Service Account (json)

Seems to leave us unable to change the google project id for the connection

The project id is read from the service account json (which is fine)

But: now looking to migrate the data to another project and reconnect metabase to the new google project

Uploading a new json with a different project seems to leave metabase trying to connect to the project specified in the original service account json

Any tips or workarounds?

**Comment by flamber** [comment] 2021-07-02 09:38
Duplicate of #13245

**Closed by flamber** 2021-07-02 09:38 UTC
Labels: .Needs Triage, Type:Question
