### ISSUE TITLE
Strange opacity when upgrade to 0.24.0

### ISSUE THREAD

**Issue by sailxjx** [metabase/metabase#5081] opened 2017-05-11 03:42 UTC
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Chrome

- Your operating system: (e.x. OS X 10, Windows XP, etc)
OS X 10.12.4

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Redshift

- Metabase version: (e.x. 0.19.3)
0.24.0

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
docker

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
postgres

When I upgrade metabase to 0.24.0, I find some cards in dashboard become transparent, maybe this is a bug.
<img width="921" alt="2017-05-11 11 37 38" src="https://cloud.githubusercontent.com/assets/909853/25931454/e8048eb8-363e-11e7-87f0-187d29fa64db.png">

Thanks for being part of the Metabase project!
-------

**Comment by mazameli** [comment] 2017-05-11 03:46
This is because you have at least one dashboard filter active that is not mapped to that card. I'm going to close this issue, but please reopen if you think something else is causing this behavior.

**Closed by mazameli** 2017-05-11 03:46 UTC

**Comment by sailxjx** [comment] 2017-05-11 03:59
@mazameli I have 5 filters on the dashboard, so whenever which filter is active, these is always some cards in transparent state.

Maybe a tooltip on the corner of card is enough for this warning, but don't make the whole card transparent.

**Comment by MiBaDK** [comment] 2017-05-18 08:35
Same issue here. Just upgraded to 0.24.

Dashboard with issue has 3 date filters ("current month", "previous month", "current month last year" in this case). Some cards use only one, some cards 2/3 and one card none.

It would be really nice with a general setting or maybe even a setting per dashboard whether this fading should be enabled. Or as @sailxjx suggests would work as well.

PS: The caching feature is EPIC!

**Comment by Eilliar** [comment] 2017-05-19 17:59
Same issue here. Just upgraded to 0.24.1.

It would be nice if we could turn on or off this feature (to fade the card if a feature is not applied) on the dashboard. Just a simple warning would be enough.

PS.: Great improvements on this new release!

**Comment by jaxn** [comment] 2017-06-06 17:52
I agree that this is not the expected behavior and would prefer to be able to disable the fading feature.

My proposal for a sane default: fade any card that has optional variables that are not used by the current filters. If a card only has required variables and they are already set, the card shouldn't fade.
