### ISSUE TITLE
Random filters order when a question has more than 8 filters

### ISSUE THREAD

**Issue by wavekasipat** [metabase/metabase#19657] opened 2022-01-13 05:21 UTC
**Describe the bug**
When create or edit a native query question and add more than 8 filters then save, filters at the top of a question will randomly place.

**Logs**
N/A

**To Reproduce**
1. Create a native query question in Sample Dataset.
2. Use this query or any query with more than 8 filters.
```
select * from PEOPLE
where 1 = 1
[[and id = {{id}}]]
[[and address ilike concat('%',{{address}},'%')]]
[[and email ilike concat('%',{{email}},'%')]]
[[and name ilike concat('%',{{name}},'%')]]
[[and city ilike concat('%',{{city}},'%')]]
[[and state ilike concat('%',{{state}},'%')]]
[[and source ilike concat('%',{{source}},'%')]]
[[and zip ilike concat('%',{{zip}},'%')]]
[[and latitude ilike concat('%',{{latitude}},'%')]]
```
3. Click on "Save".
4. Filters will be randomly placed.

**Expected behavior**
If I understand correctly, the filters should be ordered as same as query.

**Screenshots**
<img width="1155" alt="MicrosoftTeams-image1" src="https://user-images.githubusercontent.com/21122213/149270394-088962a0-9ce7-41f0-983e-2b7c39399210.png">
<img width="1155" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/21122213/149270435-88848598-41ce-4381-95b0-4aa0e249b73d.png">

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 97.0
- Your operating system: Windows 11
- Your databases: H2 Sample Dataset
- Metabase version: 0.41.5
- Metabase hosting environment: Windows Server 2019 Jar-file
- Metabase internal database: H2

**Severity**
Invalid filters order may confuse user.

**Comment by flamber** [comment] 2022-01-13 08:56
Duplicate of #5136

**Closed by flamber** 2022-01-13 08:56 UTC
Labels: Type:Bug, .Needs Triage
