### ISSUE TITLE
When you hover the mouse over the points of the graphs, the captions are not displayed correctly

### ISSUE THREAD

**Issue by twins-a** [metabase/metabase#17588] opened 2021-08-25 07:40 UTC
When you hover the mouse over the points of graphs added to the series, the captions are not displayed correctly
It all started after the update to the version 0.40.2

How do I make sure that the signatures are displayed correctly? Details on the screenshots.

**Screenshots**
![Screen series](https://user-images.githubusercontent.com/82577774/130747183-567fde13-e9f9-4f53-a98f-ccfc9c795ba5.png)
![Visualization options](https://user-images.githubusercontent.com/82577774/130747199-38efd6be-1ea8-4b96-88e7-5c011fd904bf.png)
![Example 1](https://user-images.githubusercontent.com/82577774/130747211-89856d98-e397-4088-927a-a4aa9d66221e.png)
![Example 2](https://user-images.githubusercontent.com/82577774/130747226-c3116365-8eee-440e-b94f-36e3639b1006.png)

Browser Opera 78.0.4093.147
Operating system: Windows 10.19043.1165
Databases: MSSQL
Metabase version: 0.40.2
Metabase hosting environment: Docker
Metabase internal database: Postgres

It is very inconvenient to use. Incorrect labels bring down

**Additional context**

**Comment by flamber** [comment] 2021-08-25 09:36
Duplicate of #16249

**Closed by flamber** 2021-08-25 09:36 UTC
Labels: Type:Bug, .Needs Triage
