### ISSUE TITLE
pivot table - translation bug (czech)

### ISSUE THREAD

**Issue by dfx413** [metabase/metabase#16667] opened 2021-06-18 08:21 UTC
Metabase version: 89d1b96

When the results in pivot table are grouped by month, the month name in "totals" row is always translated to czech as "January 2021":

![Snímek obrazovky 2021-06-18 v 10 19 16](https://user-images.githubusercontent.com/1764151/122530585-ea187600-d01e-11eb-9ad1-c43ce734b9a3.png)

It works fine in English version:
![Snímek obrazovky 2021-06-18 v 10 16 48](https://user-images.githubusercontent.com/1764151/122530576-e71d8580-d01e-11eb-8161-dbc4b400fedf.png)

Also works fine in Slovak and German

**Comment by flamber** [comment] 2021-06-18 08:26
@dfx413 You need to provide all the details, when opening a bug

**Comment by flamber** [comment] 2021-06-20 18:06
I cannot reproduce on 0.39.4 nor latest master `6c8c6fe` - closing without requested issue details and steps-to-reproduce
![image](https://user-images.githubusercontent.com/1447303/122683927-a54d3480-d202-11eb-8b7d-7803f73df7af.png)

**Closed by flamber** 2021-06-20 18:06 UTC
Labels: .Needs Triage, Type:Bug
