### ISSUE TITLE
Metabase on old AWS Elastic Beanstalk (Amazon Linux w/ old Docker) upgrade to 0.40 failed

### ISSUE THREAD

**Issue by kangli914** [metabase/metabase#17012] opened 2021-07-13 14:25 UTC
**Describe the bug**
I did an incremental upgrade and successfully upgraded from v0.37.8 to v0.39.0 to v0.39.4 but ut the upgrade to the latest version (v0.40.0) failed. my config was same as @psantosl where Metabase running on Beanstalk and docker and I have dedicated posgresSQL to store Metabase data as well.

**Logs**
looking at eb-activity.log. here is the error with v0.40:

[2021-07-12T20:57:08.737Z] INFO [14849] - [Application update v0.40.0.metabase-aws-eb.zip@5/AppDeployStage0/EbExtensionPostBuild/Infra-EmbeddedPostBuild/postbuild_0_Performance_Team_Metabase/Command 07-install_cloudwatch_agent] : Starting activity...
[2021-07-12T20:57:09.085Z] INFO [14849] - [Application update v0.40.0.metabase-aws-eb.zip@5/AppDeployStage0/EbExtensionPostBuild/Infra-EmbeddedPostBuild/postbuild_0_Performance_Team_Metabase/Command 07-install_cloudwatch_agent] : Activity execution failed, because: Loaded plugins: priorities, update-motd, upgrade-helper
No package amazon-cloudwatch-agent available.
Error: Nothing to do
(ElasticBeanstalk::ExternalInvocationError)

[2021-07-12T20:57:09.085Z] INFO [14849] - [Application update v0.40.0.metabase-aws-eb.zip@5/AppDeployStage0/EbExtensionPostBuild/Infra-EmbeddedPostBuild/postbuild_0_Performance_Team_Metabase/Command 07-install_cloudwatch_agent] : Activity failed.
[2021-07-12T20:57:09.085Z] INFO [14849] - [Application update v0.40.0.metabase-aws-eb.zip@5/AppDeployStage0/EbExtensionPostBuild/Infra-EmbeddedPostBuild/postbuild_0_Performance_Team_Metabase] : Activity failed.
[2021-07-12T20:57:09.085Z] INFO [14849] - [Application update v0.40.0.metabase-aws-eb.zip@5/AppDeployStage0/EbExtensionPostBuild/Infra-EmbeddedPostBuild] : Activity failed.
[2021-07-12T20:57:09.143Z] INFO [14849] - [Application update v0.40.0.metabase-aws-eb.zip@5/AppDeployStage0/EbExtensionPostBuild] : Activity failed.
[2021-07-12T20:57:09.143Z] INFO [14849] - [Application update v0.40.0.metabase-aws-eb.zip@5/AppDeployStage0] : Activity failed.
[2021-07-12T20:57:09.143Z] INFO [14849] - [Application update v0.40.0.metabase-aws-eb.zip@5] : Completed activity. Result:
Application update - Command CMD-AppDeploy failed

**To Reproduce**
- upgrade from  v0.37.8 to v0.40 directly it failed
- upgraded from v0.37.8 to v0.39.0 to v0.39.4 successfully
- upgraded from v0.39.4 to v.40 failed 

**Expected behavior**
Upgrade success

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (Chrome 52.1)
- Your operating system: (e.x. OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: ( Postgres)
- Metabase version: (v0.39.4 current)
- Metabase hosting environment: (Elastic Beanstalk)
- Metabase internal database: (Postgres )

**Severity**
Blocking the upgrade to the latest version

**Additional context**
found users also having the same problem:
https://discourse.metabase.com/t/cant-upgrade-elastic-beanstalk-to-the-new-docker/15752/14

**Comment by flamber** [comment] 2021-07-13 14:34
Too many problems with EB - we either need to fix it or make it very clear how to upgrade.

**Comment by paoliniluis** [comment] 2021-07-13 16:29
Just managed to reproduce it, it's because they're using the deprecated Amazon Linux (instead of Amazon Linux 2) with Docker running on 64bit Amazon Linux/2.16.9 (deprecated as well). In this version AWS can't find it's own Cloudwatch agent installer in yum repository. Will investigate further and push a fix (if I can), but the truth is that users need to update that platform ASAP

**Comment by paoliniluis** [comment] 2021-07-13 18:46
Uploading a custom deployment file which will work on deprecated Amazon Linux (it gets the package from a bucket instead of the yum repository which seem to be inexistent in that version)
[metabase-aws-eb-deprecated-ElasticBeanstalk.zip](https://github.com/metabase/metabase/files/6811226/metabase-aws-eb-deprecated-ElasticBeanstalk.zip)

For everyone reading this, please try this version and let us know if it works

**Comment by psantosl** [comment] 2021-07-13 18:58
It failed to me crating a new beanstalk from scratch too. Just following the link from they docu

On 13 Jul 2021, at 20:46, Luis Paolini ***@***.***> wrote:

﻿

Uploading a custom deployment file which will work on deprecated Amazon Linux (it gets the package from a bucket instead of the yum repository which seem to be inexistent in that version)
metabase-aws-eb-deprecated-ElasticBeanstalk.zip<https://github.com/metabase/metabase/files/6811226/metabase-aws-eb-deprecated-ElasticBeanstalk.zip>

For everyone reading this, please try this version and let us know if it works

**Comment by paoliniluis** [comment] 2021-07-13 19:01
Hi @psantosl, did you try upgrading your current Elastic Beanstalk deployment with the zip file in my previous comment?

I'm not having issues creating a new deployment, can you send us the steps that you're following? thanks

**Comment by raphamotta** [comment] 2021-07-14 16:49
Hello guys,

I have docker with Amazon Linux 2 on Beanstalk. When I try to upgrade from 0.39.4 to 0.40, it asks again to input all database info, username, etc like if it's the first time to install. Then I need to rollback to version 0.39.4. So, we have a problem...

**Comment by paoliniluis** [comment] 2021-07-14 16:50
Hi @raphamotta, you need to do a [decoupling of your RDS database from Elastic Beanstalk(https://www.metabase.com/docs/latest/operations-guide/creating-RDS-database-on-AWS.html#decouple-your-rds-database-from-the-elastic-beanstalk-deployment), it's a different issue

**Comment by mikeb-bb** [comment] 2021-07-15 12:24
we tried running the upgrade with the new zip, which seemed to work at first, but then it went into the setup and asked me to recreate my account and organization, so obviously that is not ideal.  i reverted back to 0.39.4.

**Comment by paoliniluis** [comment] 2021-07-15 16:56
@mikeb-bb that's the other issue that I commented first in which you need to [decouple the RDS from the Elastic Beanstalk Deployment](https://www.metabase.com/docs/latest/operations-guide/creating-RDS-database-on-AWS.html#decouple-your-rds-database-from-the-elastic-beanstalk-deployment)

**Comment by paoliniluis** [comment] 2021-07-16 18:38
Lowering the priority to P1 as this is an issue with old Elastic Beanstalks and seems to be tackled with the custom deployment file

**Comment by msencenb** [comment] 2021-07-21 20:27
Our RDS is decoupled from the Elastic Beanstalk environment and I ran into the same thing as @mikeb-bb

**Comment by kangli914** [comment] 2021-07-22 03:03
This is sad!Can we please request a clear well written guide for upgrade Metabase on old AWS Elastic Beanstalk to 0.40？Believe or not most loyal Metabase customers are on old Beanstalk and please don't abandon us :-)On Jul 21, 2021 4:27 PM, Matt Sencenbaugh ***@***.***> wrote:
Our RDS is decoupled from the Elastic Beanstalk environment and I ran into the same thing as @mikeb-bb

**Comment by kydn** [comment] 2021-07-23 15:04
> Uploading a custom deployment file which will work on deprecated Amazon Linux (it gets the package from a bucket instead of the yum repository which seem to be inexistent in that version)
> [metabase-aws-eb-deprecated-ElasticBeanstalk.zip](https://github.com/metabase/metabase/files/6811226/metabase-aws-eb-deprecated-ElasticBeanstalk.zip)
> 
> For everyone reading this, please try this version and let us know if it works

This worked for me! Do you have a version for 0.40.1, or instructions on how I could make this for future updates?

**Comment by kydn** [comment] 2021-07-26 14:10
> Uploading a custom deployment file which will work on deprecated Amazon Linux (it gets the package from a bucket instead of the yum repository which seem to be inexistent in that version)
> [metabase-aws-eb-deprecated-ElasticBeanstalk.zip](https://github.com/metabase/metabase/files/6811226/metabase-aws-eb-deprecated-ElasticBeanstalk.zip)
> 
> For everyone reading this, please try this version and let us know if it works

@paoliniluis, this worked for me! Thank you. Any chance of getting this for 0.40.1 and future versions? I've had issues decoupling and running Metabase on the latest Docker platform, so I'm putting off making the switch. (Deprecated Docker reaches EOL next summer.)

**Comment by paoliniluis** [comment] 2021-07-29 03:04
Hi @kydn @msencenb @kangli914 @mikeb-bb @raphamotta @psantosl, can you please test this bundle which should work both in deprecated Elastic Beanstalk versions and also in the new ones? it also uses the data it gets from the coupled RDS and if you decouple it will get the vars from the Env Vars you pass
https://github.com/metabase/metabase/files/6897620/metabase-ebs.zip

If everything is OK then this will be included in the next maintenance release, thanks!

**Comment by kydn** [comment] 2021-07-29 13:59
@paoliniluis, upgrade failed for me when I tried to upgrade 0.40.0 on Docker running on 64bit Amazon Linux/2.16.10.

```
-------------------------------------
/var/log/eb-activity.log
-------------------------------------
 Step 1/2 : FROM metabase/metabase:v0.40.1
   ---> 18d6b793cf0c
  Step 2/2 : EXPOSE 3000
   ---> Running in 68e1cff42efa
  Removing intermediate container 68e1cff42efa
   ---> 60c49b2787c8
  Successfully built 60c49b2787c8
  Successfully tagged aws_beanstalk/staging-app:latest
  Successfully built aws_beanstalk/staging-app
[2021-07-29T13:51:28.177Z] INFO  [19163] - [Application update v0.40.1-a@36/AppDeployStage0/AppDeployPreHook] : Completed activity. Result:
  Successfully execute hooks in directory /opt/elasticbeanstalk/hooks/appdeploy/pre.
[2021-07-29T13:51:28.177Z] INFO  [19163] - [Application update v0.40.1-a@36/AppDeployStage0/EbExtensionPostBuild] : Starting activity...
[2021-07-29T13:51:28.805Z] INFO  [19163] - [Application update v0.40.1-a@36/AppDeployStage0/EbExtensionPostBuild/Infra-EmbeddedPostBuild] : Starting activity...
[2021-07-29T13:51:28.808Z] INFO  [19163] - [Application update v0.40.1-a@36/AppDeployStage0/EbExtensionPostBuild/Infra-EmbeddedPostBuild/postbuild_0_Metabase] : Starting activity...
[2021-07-29T13:51:29.144Z] INFO  [19163] - [Application update v0.40.1-a@36/AppDeployStage0/EbExtensionPostBuild/Infra-EmbeddedPostBuild/postbuild_0_Metabase/Command 01-persist_env_vars] : Starting activity...
[2021-07-29T13:51:29.270Z] INFO  [19163] - [Application update v0.40.1-a@36/AppDeployStage0/EbExtensionPostBuild/Infra-EmbeddedPostBuild/postbuild_0_Metabase/Command 01-persist_env_vars] : Activity execution failed, because: sed: can't read /opt/elasticbeanstalk/deployment/env.list: No such file or directory
  sed: can't read /opt/elasticbeanstalk/deployment/env.list: No such file or directory
  sed: can't read /opt/elasticbeanstalk/deployment/env.list: No such file or directory
  sed: can't read /opt/elasticbeanstalk/deployment/env.list: No such file or directory
  sed: can't read /opt/elasticbeanstalk/deployment/env.list: No such file or directory
  .ebextensions/metabase_config/metabase-setup.sh: line 26: /opt/elasticbeanstalk/deployment/env.list: No such file or directory
   (ElasticBeanstalk::ExternalInvocationError)

-------------------------------------
/var/log/eb-commandprocessor.log
-------------------------------------
[2021-07-29T13:51:29.298Z] ERROR [19163] : Command CMD-AppDeploy failed!
[2021-07-29T13:51:29.299Z] INFO  [19163] : Command processor returning results: 
{"status":"FAILURE","api_version":"1.0","results":[{"status":"FAILURE","msg":"(TRUNCATED)...loyment/env.list: No such file or directory\nsed: can't read /opt/elasticbeanstalk/deployment/env.list: No such file or directory\n.ebextensions/metabase_config/metabase-setup.sh: line 26: /opt/elasticbeanstalk/deployment/env.list: No such file or directory. \ncontainer_command 01-persist_env_vars in .ebextensions/01_metabase.config failed. For more detail, check /var/log/eb-activity.log using console or EB CLI","returncode":1,"events":[{"msg":"Successfully pulled metabase/metabase:v0.40.1","severity":"TRACE","timestamp":1627566686},{"msg":"Successfully built aws_beanstalk/staging-app","severity":"TRACE","timestamp":1627566688}]}],"truncated":"true"}
[2021-07-29T13:53:51.119Z] DEBUG [19633] : Reading config file: /etc/elasticbeanstalk/.aws-eb-stack.properties
[2021-07-29T13:53:51.120Z] DEBUG [19633] : Checking if the command processor should execute...
[2021-07-29T13:53:51.122Z] DEBUG [19633] : Checking whether the command is applicable to instance (i-0204121a26d82caa1)..
[2021-07-29T13:53:51.122Z] INFO  [19633] : Command is applicable to this instance (i-0204121a26d82caa1)..
[2021-07-29T13:53:51.122Z] DEBUG [19633] : Checking if the received command stage is valid..
[2021-07-29T13:53:51.122Z] INFO  [19633] : No stage_num in command. Valid stage..
[2021-07-29T13:53:51.122Z] INFO  [19633] : Received command CMD-TailLogs: {"execution_data"=>"*", "instance_ids"=>["i-0204121a26d82caa1"], "data"=>"987a0521-dcd1-4c57-a25c-88836c5e3305", "command_name"=>"CMD-TailLogs", "api_version"=>"1.0", "resource_name"=>"AWSEBAutoScalingGroup", "request_id"=>"987a0521-dcd1-4c57-a25c-88836c5e3305"}
[2021-07-29T13:53:51.122Z] INFO  [19633] : Command processor should execute command.
[2021-07-29T13:53:51.122Z] DEBUG [19633] : Storing current stage..
[2021-07-29T13:53:51.122Z] DEBUG [19633] : Stage_num does not exist. Not saving null stage. Returning..
```

**Comment by mikeb-bb** [comment] 2021-07-29 18:27
i've got the same as @kydn, i think i'll hold off based on that result :)

**Comment by paoliniluis** [comment] 2021-07-29 23:30
Thanks @kydn and @mikeb-bb, just managed to reproduce your error and built another version, this one should update without issues. Please test this new bundle and let me know
[metabase-ebs.zip](https://github.com/metabase/metabase/files/6904170/metabase-ebs.zip)

**Comment by kydn** [comment] 2021-07-29 23:39
Something is weird with this; it gave me db auth errors. This has never happened before when updating Metabase:

```
2021-07-29 23:37:02,710 INFO db.setup :: [36mVerifying postgres Database Connection ...[0m
2021-07-29 23:37:03,203 ERROR metabase.core :: Metabase Initialization FAILED
clojure.lang.ExceptionInfo: Unable to connect to Metabase postgres DB. {}
	at metabase.db.setup$fn__35702$verify_db_connection__35707$fn__35708$fn__35709.invoke(setup.clj:102)
	at metabase.db.setup$fn__35702$verify_db_connection__35707$fn__35708.invoke(setup.clj:100)
	at metabase.db.setup$fn__35702$verify_db_connection__35707.invoke(setup.clj:94)
	at metabase.db.setup$setup_db_BANG_$fn__35737$fn__35738.invoke(setup.clj:142)
	at metabase.util$do_with_us_locale.invokeStatic(util.clj:683)
	at metabase.util$do_with_us_locale.invoke(util.clj:669)
	at metabase.db.setup$setup_db_BANG_$fn__35737.invoke(setup.clj:141)
	at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:140)
	at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:136)
	at metabase.db$setup_db_BANG_$fn__35751.invoke(db.clj:61)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:56)
	at metabase.db$setup_db_BANG_.invoke(db.clj:51)
	at metabase.core$init_BANG_.invokeStatic(core.clj:87)
	at metabase.core$init_BANG_.invoke(core.clj:66)
	at metabase.core$start_normally.invokeStatic(core.clj:131)
	at metabase.core$start_normally.invoke(core.clj:125)
	at metabase.core$_main.invokeStatic(core.clj:164)
	at metabase.core$_main.doInvoke(core.clj:158)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "[username]"
```

**Comment by mikeb-bb** [comment] 2021-07-29 23:44
hmm.  i was about to give it a shot but maybe not.  we're at 0.39.4 currently, Docker running on 64bit Amazon Linux/2.16.10.  db is also not decoupled.

**Comment by kydn** [comment] 2021-07-30 00:04
Yeah. I am thoroughly annoyed because now my prod installation seems fucked. When I downgrade to the previous application version (0.40.0, the version linked above that I said worked fine) I get an error that says 

```
Command failed on instance. Return code: 1 Output: (TRUNCATED)...42M 0s 40450K ....... 100% 134M=0.9s 2021-07-29 23:44:47 (46.1 MB/s) - 'amazon-cloudwatch-agent.rpm' saved [41427996/41427996] package amazon-cloudwatch-agent-1.247348.0b251302-1.x86_64 is already installed. container_command 07-install_cloudwatch_agent in .ebextensions/01_metabase.config failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.
```

When I try to revert to 0.39.4, I get 502 nginx errors. Restarting the app server doesn't fix it. In the logs I see "Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "[username]"" errors. So I reset my RDS db password (to the same password it has always been). Now the error is:

```
2021-07-29 16:58:00 UTC-0700 | ERROR | Updating RDS database named: [db name] failed Reason: Cannot upgrade postgres from 10.15 to 10.6
-- | -- | --
2021-07-29 16:58:00 UTC-0700 | ERROR | Service:AmazonCloudFormation, Message:Stack named '[name]' aborted operation. Current state: 'UPDATE_ROLLBACK_IN_PROGRESS' Reason: The following resource(s) failed to update: [AWSEBRDSDatabase].
```

I can't downgrade successfully to any previous version. I get the same bogus errors:

```
2021-07-30 00:03:32,186 ERROR metabase.core :: Metabase Initialization FAILED
clojure.lang.ExceptionInfo: Unable to connect to Metabase postgres DB. {}
	at metabase.db.setup$fn__35507$verify_db_connection__35512$fn__35513$fn__35514.invoke(setup.clj:102)
	at metabase.db.setup$fn__35507$verify_db_connection__35512$fn__35513.invoke(setup.clj:100)
	at metabase.db.setup$fn__35507$verify_db_connection__35512.invoke(setup.clj:94)
	at metabase.db.setup$setup_db_BANG_$fn__35542$fn__35543.invoke(setup.clj:142)
	at metabase.util$do_with_us_locale.invokeStatic(util.clj:687)
	at metabase.util$do_with_us_locale.invoke(util.clj:673)
	at metabase.db.setup$setup_db_BANG_$fn__35542.invoke(setup.clj:141)
	at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:140)
	at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:136)
	at metabase.db$setup_db_BANG_$fn__35556.invoke(db.clj:61)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:56)
	at metabase.db$setup_db_BANG_.invoke(db.clj:51)
	at metabase.core$init_BANG_.invokeStatic(core.clj:95)
	at metabase.core$init_BANG_.invoke(core.clj:74)
	at metabase.core$start_normally.invokeStatic(core.clj:139)
	at metabase.core$start_normally.invoke(core.clj:133)
	at metabase.core$_main.invokeStatic(core.clj:172)
	at metabase.core$_main.doInvoke(core.clj:166)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "[username]"
```

Great fun being a test subject. How do I fix this?

**Comment by mikeb-bb** [comment] 2021-07-30 00:21
oh damn, did you snapshot the db before the upgrade?

**Comment by paoliniluis** [comment] 2021-07-30 00:33
@kydn, try the following please: if you have the host, username, password, db type and port (even though your DB is coupled, you should have that in the configuration of your environment in elastic beanstalk), try entering those as environment variables as we state here: https://www.metabase.com/docs/latest/operations-guide/environment-variables.html (use the latest file if possible)

please let me know how it works, thanks

**Comment by raphamotta** [comment] 2021-07-30 00:57
> Thanks @kydn and @mikeb-bb, just managed to reproduce your error and built another version, this one should update without issues. Please test this new bundle and let me know
> [metabase-ebs.zip](https://github.com/metabase/metabase/files/6904170/metabase-ebs.zip)

It worked for me with coupled RDS on both, deprecated Amazon Linux and new Amazon Linux 2. Thank you!
Can you please tell me how you did the trick? (if you can detail the coupled database part...)
Do you think it's safe to use with production environment?

**Comment by kydn** [comment] 2021-07-30 00:59
> @kydn, try the following please: if you have the host, username, password, db type and port (even though your DB is coupled, you should have that in the configuration of your environment in elastic beanstalk), try entering those as environment variables as we state here: https://www.metabase.com/docs/latest/operations-guide/environment-variables.html (use the latest file if possible)
> 
> please let me know how it works, thanks

I had those as environment variables when I encountered the above errors. :(

**Comment by paoliniluis** [comment] 2021-07-30 01:10
Thanks, so you say that the user, password, db name and everything works correctly when you connect from the outside but when you deploy the new version of Metabase it fails with FATAL: password authentication failed for user "[username]", is that diagnose correct?

**Comment by kydn** [comment] 2021-07-30 01:11
Yes, and I am unable to revert to previous versions of Metabase now because of the same error. I reset the password to be sure.

**Comment by paoliniluis** [comment] 2021-07-30 01:33
ok, is there any way in which you can SSH into the instance and see id the file /opt/elasticbeanstalk/deploy/configuration/containerconfiguration has the correct parameters for connecting to the database?

**Comment by kydn** [comment] 2021-07-30 01:36
No, sorry, I cannot do that.

**Comment by paoliniluis** [comment] 2021-07-30 01:41
ok, and what about rebuilding (taking into account you have backups) and/or decoupling and upgrading to newer Elastic Beanstalk platform, is that feasible?

**Comment by kydn** [comment] 2021-07-30 01:53
I just created a new environment on Docker running on 64bit Amazon Linux 2/3.4.3 using Metabase 0.40.1 from the main site. New RDS database restored from a snapshot with DB credentials as environment variables. I see in the logs a bunch of database migrations, so apparently it has connected. Everything has settled now, environment health status is okay, but when I go to the instance URL I still got a 502 error. No errors in the logs that I can find.

**Comment by kydn** [comment] 2021-07-30 02:28
I just tried updating the app running on the deprecated Docker environment with the version of Metabase 0.40.1 from the main site. It worked, and I see all my data, queries, and dashboards. So, that's great!

Still can't get 0.40.1 running on the newer version of Docker, though.

**Comment by paoliniluis** [comment] 2021-07-30 02:33
This is incredible odd then, how's that even possible if we haven't upgraded the release bundle in the main site? Are you using an application database or you are using h2? can you post your diagnostic information here?

**Comment by kydn** [comment] 2021-07-30 03:41
Yeah, I was very surprised that it worked. I'm using the RDS db that's coupled with the deprecated version of Docker. Where can I find my diagnostic info?

**Comment by raphamotta** [comment] 2021-07-30 10:40
> > Thanks @kydn and @mikeb-bb, just managed to reproduce your error and built another version, this one should update without issues. Please test this new bundle and let me know
> > [metabase-ebs.zip](https://github.com/metabase/metabase/files/6904170/metabase-ebs.zip)
> 
> It worked for me with coupled RDS on both, deprecated Amazon Linux and new Amazon Linux 2. Thank you!
> Can you please tell me how you did the trick? (if you can detail the coupled database part...)
> Do you think it's safe to use with production environment?

Just tested in a few more environments I have in elastic beanstalk and so far everything is working properly

**Closed** 2021-08-03 10:36 UTC
Labels: .Regression, Operation/Elastic Beanstalk, Priority:P1, Type:Bug

**Comment by kangli914** [comment] 2021-08-03 12:25
Hello Luis,I have Metabasis 0.39 running on deprecated Amazon Linux with decoupled RDS, ive seen many custom package and attempts for upgrade 0.40.Can I please give one package that is known working for my case? I am upgrading the production instance so need to be cautious.ThanksOn Aug 3, 2021 6:36 AM, Luis Paolini ***@***.***> wrote:
Closed #17012 via #17261.
