### ISSUE TITLE
Remove individual line/column/series from Multi-series Dashboard

### ISSUE THREAD

**Issue by nitsujri** [metabase/metabase#21149] opened 2022-03-22 03:01 UTC
**Describe the bug**
When a graph(s) are added it looks like I should be able to remove a specific series:

![Test_Dash_·_Dashboard_·_Metabase](https://user-images.githubusercontent.com/224840/159396469-7d6c6832-9036-46c3-9ef3-450dbef103f5.png)

Clicking the `X` results in a JS error:

![Test_Dash_·_Dashboard_·_Metabase](https://user-images.githubusercontent.com/224840/159396587-724127aa-7c30-49fc-9409-9d1f8d64f643.png)

**Logs**

```
react-dom.production.min.js:52 Uncaught TypeError: Cannot read properties of undefined (reading 'setState')
    at value (AddSeriesModal.jsx:129:10)
    at onClick (LegendItem.jsx:46:23)
    at Object.l (react-dom.production.min.js:14:84)
    at p (react-dom.production.min.js:14:238)
    at react-dom.production.min.js:14:292
    at y (react-dom.production.min.js:15:72)
    at lt (react-dom.production.min.js:52:146)
    at at (react-dom.production.min.js:51:255)
    at ct (react-dom.production.min.js:52:334)
    at gt (react-dom.production.min.js:56:10)
```

**To Reproduce**
1. Create 2x separate Visualizations with multiple series
2. Add to dashboard
3. Add multi-series
4. Try to remove a specific series (not a set) with the `x`
5. Nothing happens.

**Expected behavior**
I should be able to remove a specific series from a 'question' that has multiple series graphed.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8-Ubuntu-0ubuntu1.21.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8-Ubuntu-0ubuntu1.21.04",
    "os.name": "Linux",
    "os.version": "5.10.76-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-28",
      "tag": "v0.42.2",
      "branch": "release-x.42.x",
      "hash": "d6ff494"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Annoying

**Additional Information**
To work around not being able to selectively choose specific series from a 'question', I have to build a single question with a single series graphed.

While this physically works, it appears loading to be quite slow.

**Our specific use case**

1. We have 1x SQL query that builds 8x columns/series. It runs in `300ms`.
1. Each row of the query belongs to a `country` - `US`, `MX`, `CA`, `*` (for aggregate).
2. There are 4 core graphs, each is a filter i.e. `country_alpha2 = 'US'`
    - Each core graphs contains the 8x column/series
4. From these 4 core, we wanted 'pivot' on 1x series across the 4 regions. 
    - i.e. compare the regions for 1 metric.

The final goal is a dashboard with 12x graphs, 4x core and 8x cross-region metric comparison.

Ideally, I would have built the 4x core graphs and select a specific metric to display cross region via multi-series. But since I can't pick an individual series from a graph - to work around this, **I have built 32x individual questions w/ a single graph and then build up each 8x cross region metrics via multi-series**.

Doing this, the dashboard takes ~25-30s to load, which makes me believe it is running the query once for every individual series and processing the data up to 36x times (32x individual + 4x core?).

Caching doesn't seem to help because the query itself returns too fast? At least when we turn caching on and drop it to 2s it does not seem to improve the dashboard's load time.

**Comment by flamber** [comment] 2022-03-22 08:47
Duplicate of #12794

**Closed by flamber** 2022-03-22 08:47 UTC
Labels: Type:Bug, .Needs Triage
