### ISSUE TITLE
Public dashboard fail to show data on v0.28.4

### ISSUE THREAD

**Issue by thucnc** [metabase/metabase#7253] opened 2018-04-02 09:22 UTC
I upgraded metabase docker image from v0.28.0 to v0.28.4 and got an issue on my public dashboard as below screenshot and log

![screen shot 2018-04-02 at 4 18 21 pm](https://user-images.githubusercontent.com/2088055/38191194-eb6b23d8-3691-11e8-8cfd-2abbdbed925b.png)

`04-02 09:17:41 DEBUG metabase.middleware :: GET /api/public/dashboard/10d24eb2-ef69-401a-a6b5-833ef5f59456/card/3424 400 (1 ms) (2 DB calls).
"An error occurred."`

Please help

**Comment by valtlfelipe** [comment] 2018-04-02 12:30
I'm having the same issue. I get this error:

```json
"error": "(not (matches-some-precondition? nil))"
```

stack trace:
![captura de tela 2018-04-02 as 09 29 47](https://user-images.githubusercontent.com/3065339/38196264-67e55eea-3658-11e8-92e3-e7956cd319ef.png)

**Comment by valtlfelipe** [comment] 2018-04-02 12:32
Also getting this error in another dashboard:
![captura de tela 2018-04-02 as 09 32 14](https://user-images.githubusercontent.com/3065339/38196326-c8a89d8c-3658-11e8-90df-6b61984c360d.png)

All of the questions/dashboards where working before upgrade.

**Comment by jornh** [comment] 2018-04-02 18:00
Possibly related #7212 

It looks like the fix for this issue is close to getting merged into an upcoming v0.28.5 together with another critical issue already resolved: https://github.com/metabase/metabase/milestone/61

**Comment by camsaul** [comment] 2018-04-02 22:01
@thucnc @jornh @valtlfelipe can you confirm that this issue is fixed in #7248 ?

**Comment by ywadi** [comment] 2018-04-04 18:35
The custom category filter is the root cause, whenever the query string is applied that happens.

**Comment by jornh** [comment] 2018-04-04 20:05
@camsaul on the contrary. I can confirm that what is *probably* the same error as @thucnc originally reported above I'm now able to reproduce when I'm using https://github.com/metabase/metabase/pull/7248/commits/5458a7af7dcbca635f02f7e411ef8f47b9ab1274 (your `Ok now the test is finished! [ci all]` commit, so just missing the final test code commit and merge of #7248). I pulled it and then you continued working! 😉 

I believe I have narrowed the issue down to that it happens on **native SQL queries.** with filter on paramaters I have it reproduced with a Postgres database + H2 for Metabase itself (but that part is probably not important wrt. this issue).

I tried adding another Metabase GUI query to the same dashboard also querying a table in the same database so I could apply the same category filter. It works fine (due to #7248 I presume).

Note the dashboard has three failing native queries hence the 3 times where it barfs at me below.

Let me know if you need anything more!

@thucnc & @valtlfelipe does your dashboards also contain native SQL questions?

```
04-04 21:35:17 [1mWARN metabase.query-processor[0m :: {:status :failed,
 :class clojure.lang.ExceptionInfo,
 :error "Input to value-for-tag does not match schema: \n\n\t [0;33m  [nil (named [{:default disallowed-key}] params)] [0m \n\n",
 :stacktrace
 ["query_processor.middleware.parameters.sql$fn__30811$value_for_tag__30816.invoke(sql.clj:242)"
  "query_processor.middleware.parameters.sql$fn__30837$query__GT_params_map__30842$fn__30848$iter__30851__30855$fn__30856.invoke(sql.clj:263)"
  "query_processor.middleware.parameters.sql$fn__30837$query__GT_params_map__30842$fn__30848.invoke(sql.clj:262)"
  "query_processor.middleware.parameters.sql$fn__30837$query__GT_params_map__30842.invoke(sql.clj:252)"
  "query_processor.middleware.parameters.sql$expand.invokeStatic(sql.clj:518)"
  "query_processor.middleware.parameters.sql$expand.invoke(sql.clj:512)"
  "query_processor.middleware.parameters$expand_parameters_STAR_.invokeStatic(parameters.clj:21)"
  "query_processor.middleware.parameters$expand_parameters_STAR_.invoke(parameters.clj:14)"
  "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:45)"
  "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:42)"
  "query_processor.middleware.parameters$substitute_parameters_STAR_.invokeStatic(parameters.clj:51)"
  "query_processor.middleware.parameters$substitute_parameters_STAR_.invoke(parameters.clj:48)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__29902.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__31315.invoke(resolve_driver.clj:15)"
  "query_processor.middleware.cache$run_query_and_save_results_if_successful_BANG_.invokeStatic(cache.clj:113)"
  "query_processor.middleware.cache$run_query_and_save_results_if_successful_BANG_.invoke(cache.clj:111)"
  "query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:124)"
  "query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:121)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__28623.invoke(cache.clj:147)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__29819.invoke(catch_exceptions.clj:58)"
  "query_processor$process_query.invokeStatic(query_processor.clj:130)"
  "query_processor$process_query.invoke(query_processor.clj:126)"
  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:241)"
  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:235)"
  "query_processor$fn__31349$process_query_and_save_execution_BANG___31354$fn__31355.invoke(query_processor.clj:281)"
  "query_processor$fn__31349$process_query_and_save_execution_BANG___31354.invoke(query_processor.clj:267)"
  "api.card$run_query_for_card.invokeStatic(card.clj:607)"
  "api.card$run_query_for_card.doInvoke(card.clj:593)"
  "api.public$run_query_for_card_with_id$fn__38223.invoke(public.clj:65)"
  "api.public$run_query_for_card_with_id.invokeStatic(public.clj:63)"
  "api.public$run_query_for_card_with_id.doInvoke(public.clj:58)"
  "api.public$public_dashcard_results.invokeStatic(public.clj:212)"
  "api.public$public_dashcard_results.doInvoke(public.clj:200)"
  "api.public$fn__38377$fn__38378.invoke(public.clj:223)"
  "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:253)"
  "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)"
  "api.public$fn__38377.invokeStatic(public.clj:217)"
  "api.public$fn__38377.invoke(public.clj:217)"
  "middleware$genericize_exceptions$fn__33396.invoke(middleware.clj:359)"
  "api.routes$fn__46397.invokeStatic(routes.clj:79)"
  "api.routes$fn__46397.invoke(routes.clj:79)"
  "routes$fn__47156$fn__47157.doInvoke(routes.clj:106)"
  "routes$fn__47156.invokeStatic(routes.clj:101)"
  "routes$fn__47156.invoke(routes.clj:101)"
  "middleware$log_api_call$fn__33388$fn__33390.invoke(middleware.clj:347)"
  "middleware$log_api_call$fn__33388.invoke(middleware.clj:346)"
  "middleware$add_security_headers$fn__33338.invoke(middleware.clj:249)"
  "core$wrap_streamed_json_response$fn__47951.invoke(core.clj:67)"
  "middleware$bind_current_user$fn__33293.invoke(middleware.clj:138)"
  "middleware$maybe_set_site_url$fn__33342.invoke(middleware.clj:273)"],
 :query
 {:type "native",
  :native
  {:query
   "select max(t) as t, max(m_agg) as FCR2_t, sales_product_text, sales_product from poc.mythirdtable_fcr2 where esum > 0 and sales_product_text = {{sales_product_text}} group by sales_product_text, sales_product order by sales_product_text; \n",
   :collection "account",
   :template_tags {:sales_product_text {:id "181da7c5-1269-05f0-8e92-be5898780427", :name "sales_product_text", :display_name "Sales product text", :type "text", :required true, :default nil}}},
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :parameters ({:type "category", :target ["variable" ["template-tag" "sales_product_text"]], :value "OUR REALLY NICE PRODUCT NAME", :name "Category", :slug "category", :id "aa09668c", :default "OUR REALLY NICE PRODUCT NAME"}),
  :cache_ttl 246,
  :info
  {:executed-by 37,
   :context :public-dashboard,
   :card-id 103,
   :dashboard-id 36,
   :query-hash [-127, -45, -90, 41, 21, 47, -38, 75, 91, 86, -53, 99, -127, -24, -2, -35, -90, -56, -88, 65, 45, -84, 116, -45, -106, -117, -64, 13, -32, -120, 123, 105],
   :query-type "native"}},
 :expanded-query nil,
 :ex-data
 {:type :schema.core/error,
  :value
  [{:id "181da7c5-1269-05f0-8e92-be5898780427", :name "sales_product_text", :display_name "Sales product text", :type "text", :required true, :default nil}
   ({:type "category", :target ["variable" ["template-tag" "sales_product_text"]], :value "OUR REALLY NICE PRODUCT NAME", :name "Category", :slug "category", :id "aa09668c", :default "OUR REALLY NICE PRODUCT NAME"})],
  :error [nil (named [{:default disallowed-key}] params)]}}

04-04 21:35:17 [1mWARN metabase.query-processor[0m :: {:status :failed,
 :class clojure.lang.ExceptionInfo,
 :error "Input to value-for-tag does not match schema: \n\n\t [0;33m  [nil (named [{:default disallowed-key}] params)] [0m \n\n",
 :stacktrace
 ["query_processor.middleware.parameters.sql$fn__30811$value_for_tag__30816.invoke(sql.clj:242)"
  "query_processor.middleware.parameters.sql$fn__30837$query__GT_params_map__30842$fn__30848$iter__30851__30855$fn__30856.invoke(sql.clj:263)"
  "query_processor.middleware.parameters.sql$fn__30837$query__GT_params_map__30842$fn__30848.invoke(sql.clj:262)"
  "query_processor.middleware.parameters.sql$fn__30837$query__GT_params_map__30842.invoke(sql.clj:252)"
  "query_processor.middleware.parameters.sql$expand.invokeStatic(sql.clj:518)"
  "query_processor.middleware.parameters.sql$expand.invoke(sql.clj:512)"
  "query_processor.middleware.parameters$expand_parameters_STAR_.invokeStatic(parameters.clj:21)"
  "query_processor.middleware.parameters$expand_parameters_STAR_.invoke(parameters.clj:14)"
  "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:45)"
  "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:42)"
  "query_processor.middleware.parameters$substitute_parameters_STAR_.invokeStatic(parameters.clj:51)"
  "query_processor.middleware.parameters$substitute_parameters_STAR_.invoke(parameters.clj:48)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__29902.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__31315.invoke(resolve_driver.clj:15)"
  "query_processor.middleware.cache$run_query_and_save_results_if_successful_BANG_.invokeStatic(cache.clj:113)"
  "query_processor.middleware.cache$run_query_and_save_results_if_successful_BANG_.invoke(cache.clj:111)"
  "query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:124)"
  "query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:121)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__28623.invoke(cache.clj:147)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__29819.invoke(catch_exceptions.clj:58)"
  "query_processor$process_query.invokeStatic(query_processor.clj:130)"
  "query_processor$process_query.invoke(query_processor.clj:126)"
  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:241)"
  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:235)"
  "query_processor$fn__31349$process_query_and_save_execution_BANG___31354$fn__31355.invoke(query_processor.clj:281)"
  "query_processor$fn__31349$process_query_and_save_execution_BANG___31354.invoke(query_processor.clj:267)"
  "api.card$run_query_for_card.invokeStatic(card.clj:607)"
  "api.card$run_query_for_card.doInvoke(card.clj:593)"
  "api.public$run_query_for_card_with_id$fn__38223.invoke(public.clj:65)"
  "api.public$run_query_for_card_with_id.invokeStatic(public.clj:63)"
  "api.public$run_query_for_card_with_id.doInvoke(public.clj:58)"
  "api.public$public_dashcard_results.invokeStatic(public.clj:212)"
  "api.public$public_dashcard_results.doInvoke(public.clj:200)"
  "api.public$fn__38377$fn__38378.invoke(public.clj:223)"
  "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:253)"
  "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)"
  "api.public$fn__38377.invokeStatic(public.clj:217)"
  "api.public$fn__38377.invoke(public.clj:217)"
  "middleware$genericize_exceptions$fn__33396.invoke(middleware.clj:359)"
  "api.routes$fn__46397.invokeStatic(routes.clj:79)"
  "api.routes$fn__46397.invoke(routes.clj:79)"
  "routes$fn__47156$fn__47157.doInvoke(routes.clj:106)"
  "routes$fn__47156.invokeStatic(routes.clj:101)"
  "routes$fn__47156.invoke(routes.clj:101)"
  "middleware$log_api_call$fn__33388$fn__33390.invoke(middleware.clj:347)"
  "middleware$log_api_call$fn__33388.invoke(middleware.clj:346)"
  "middleware$add_security_headers$fn__33338.invoke(middleware.clj:249)"
  "core$wrap_streamed_json_response$fn__47951.invoke(core.clj:67)"
  "middleware$bind_current_user$fn__33293.invoke(middleware.clj:138)"
  "middleware$maybe_set_site_url$fn__33342.invoke(middleware.clj:273)"],
 :query
 {:type "native",
  :native
  {:query
   "select max(t) as t, max(m_agg) as FCR_t, sales_product_text, sales_product from poc.mythirdtable where esum > 0 [[and sales_product_text = {{sales_product_text}}]] group by sales_product_text, sales_product order by sales_product_text; \r\n",
   :template_tags {:sales_product_text {:id "cbe49f3a-ed40-a543-8137-f946f9900e1b", :name "sales_product_text", :display_name "Sales product text", :type "text"}}},
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :parameters ({:type "category", :target ["variable" ["template-tag" "sales_product_text"]], :value "OUR REALLY NICE PRODUCT NAME", :name "Category", :slug "category", :id "aa09668c", :default "OUR REALLY NICE PRODUCT NAME"}),
  :cache_ttl 249,
  :info
  {:executed-by 37,
   :context :public-dashboard,
   :card-id 89,
   :dashboard-id 36,
   :query-hash [-32, 88, -76, -16, 95, -26, -56, 40, 27, -61, 103, -46, 1, -37, -28, -123, 31, 21, 75, 68, 114, 125, -19, -96, -11, -122, 101, -115, 19, -88, 115, -85],
   :query-type "native"}},
 :expanded-query nil,
 :ex-data
 {:type :schema.core/error,
  :value
  [{:id "cbe49f3a-ed40-a543-8137-f946f9900e1b", :name "sales_product_text", :display_name "Sales product text", :type "text"}
   ({:type "category", :target ["variable" ["template-tag" "sales_product_text"]], :value "OUR REALLY NICE PRODUCT NAME", :name "Category", :slug "category", :id "aa09668c", :default "OUR REALLY NICE PRODUCT NAME"})],
  :error [nil (named [{:default disallowed-key}] params)]}}

04-04 21:35:17 [1mWARN metabase.query-processor[0m :: {:status :failed,
 :class clojure.lang.ExceptionInfo,
 :error "Input to value-for-tag does not match schema: \n\n\t [0;33m  [nil (named [{:default disallowed-key}] params)] [0m \n\n",
 :stacktrace
 ["query_processor.middleware.parameters.sql$fn__30811$value_for_tag__30816.invoke(sql.clj:242)"
  "query_processor.middleware.parameters.sql$fn__30837$query__GT_params_map__30842$fn__30848$iter__30851__30855$fn__30856.invoke(sql.clj:263)"
  "query_processor.middleware.parameters.sql$fn__30837$query__GT_params_map__30842$fn__30848.invoke(sql.clj:262)"
  "query_processor.middleware.parameters.sql$fn__30837$query__GT_params_map__30842.invoke(sql.clj:252)"
  "query_processor.middleware.parameters.sql$expand.invokeStatic(sql.clj:518)"
  "query_processor.middleware.parameters.sql$expand.invoke(sql.clj:512)"
  "query_processor.middleware.parameters$expand_parameters_STAR_.invokeStatic(parameters.clj:21)"
  "query_processor.middleware.parameters$expand_parameters_STAR_.invoke(parameters.clj:14)"
  "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:45)"
  "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:42)"
  "query_processor.middleware.parameters$substitute_parameters_STAR_.invokeStatic(parameters.clj:51)"
  "query_processor.middleware.parameters$substitute_parameters_STAR_.invoke(parameters.clj:48)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__29902.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__31315.invoke(resolve_driver.clj:15)"
  "query_processor.middleware.cache$run_query_and_save_results_if_successful_BANG_.invokeStatic(cache.clj:113)"
  "query_processor.middleware.cache$run_query_and_save_results_if_successful_BANG_.invoke(cache.clj:111)"
  "query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:124)"
  "query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:121)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__28623.invoke(cache.clj:147)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__29819.invoke(catch_exceptions.clj:58)"
  "query_processor$process_query.invokeStatic(query_processor.clj:130)"
  "query_processor$process_query.invoke(query_processor.clj:126)"
  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:241)"
  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:235)"
  "query_processor$fn__31349$process_query_and_save_execution_BANG___31354$fn__31355.invoke(query_processor.clj:281)"
  "query_processor$fn__31349$process_query_and_save_execution_BANG___31354.invoke(query_processor.clj:267)"
  "api.card$run_query_for_card.invokeStatic(card.clj:607)"
  "api.card$run_query_for_card.doInvoke(card.clj:593)"
  "api.public$run_query_for_card_with_id$fn__38223.invoke(public.clj:65)"
  "api.public$run_query_for_card_with_id.invokeStatic(public.clj:63)"
  "api.public$run_query_for_card_with_id.doInvoke(public.clj:58)"
  "api.public$public_dashcard_results.invokeStatic(public.clj:212)"
  "api.public$public_dashcard_results.doInvoke(public.clj:200)"
  "api.public$fn__38377$fn__38378.invoke(public.clj:223)"
  "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:253)"
  "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)"
  "api.public$fn__38377.invokeStatic(public.clj:217)"
  "api.public$fn__38377.invoke(public.clj:217)"
  "middleware$genericize_exceptions$fn__33396.invoke(middleware.clj:359)"
  "api.routes$fn__46397.invokeStatic(routes.clj:79)"
  "api.routes$fn__46397.invoke(routes.clj:79)"
  "routes$fn__47156$fn__47157.doInvoke(routes.clj:106)"
  "routes$fn__47156.invokeStatic(routes.clj:101)"
  "routes$fn__47156.invoke(routes.clj:101)"
  "middleware$log_api_call$fn__33388$fn__33390.invoke(middleware.clj:347)"
  "middleware$log_api_call$fn__33388.invoke(middleware.clj:346)"
  "middleware$add_security_headers$fn__33338.invoke(middleware.clj:249)"
  "core$wrap_streamed_json_response$fn__47951.invoke(core.clj:67)"
  "middleware$bind_current_user$fn__33293.invoke(middleware.clj:138)"
  "middleware$maybe_set_site_url$fn__33342.invoke(middleware.clj:273)"],
 :query
 {:type "native",
  :native
  {:query
   "SELECT \"public\".\"mysecondtable\".\"esum\" AS \"esum\", \"public\".\"mysecondtable\".\"m_agg\" AS \"m_agg\", \"public\".\"mysecondtable\".\"m_for_real\" AS \"m_for_real\", \"public\".\"mysecondtable\".\"n_running_total\" AS \"n_running_total\", \"public\".\"mysecondtable\".\"qsum\" AS \"qsum\", \"public\".\"mysecondtable\".\"sales_product_text\" AS \"sales_product_text\", \"public\".\"mysecondtable\".\"t\" AS \"t\"\nFROM \"public\".\"mysecondtable\"\nwhere {{sales_product_text}}\nLIMIT 5000",
   :template_tags
   {:sales_product_text
    {:id "b6118909-71f1-3f94-4ab2-b79fc7f47e14", :name "sales_product_text", :display_name "Sales product text", :type "dimension", :dimension ["field-id" 1540], :widget_type "category"}}},
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :parameters ({:type "category", :target ["dimension" ["template-tag" "sales_product_text"]], :value "OUR REALLY NICE PRODUCT NAME", :name "Category", :slug "category", :id "aa09668c", :default "OUR REALLY NICE PRODUCT NAME"}),
  :cache_ttl 252,
  :info
  {:executed-by 37,
   :context :public-dashboard,
   :card-id 87,
   :dashboard-id 36,
   :query-hash [59, -31, 81, -34, -109, 35, -13, 1, 108, -64, 109, -25, -72, -73, -125, -23, -22, 51, -118, -60, -23, -84, -66, 2, 43, 69, -5, -12, 23, -9, 1, -102],
   :query-type "native"}},
 :expanded-query nil,
 :ex-data
 {:type :schema.core/error,
  :value
  [{:id "b6118909-71f1-3f94-4ab2-b79fc7f47e14", :name "sales_product_text", :display_name "Sales product text", :type "dimension", :dimension ["field-id" 1540], :widget_type "category"}
   ({:type "category", :target ["dimension" ["template-tag" "sales_product_text"]], :value "OUR REALLY NICE PRODUCT NAME", :name "Category", :slug "category", :id "aa09668c", :default "OUR REALLY NICE PRODUCT NAME"})],
  :error [nil (named [{:default disallowed-key}] params)]}}

04-04 21:35:17 [1mINFO middleware.cache[0m :: Query took 750 ms to run; miminum for cache eligibility is 20000 ms
04-04 21:35:17 [1mWARN metabase.query-processor[0m :: Query failure: Input to value-for-tag does not match schema:

         [0;33m  [nil (named [{:default disallowed-key}] params)] [0m


["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:209)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:202)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:242)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:235)"
 "query_processor$fn__31349$process_query_and_save_execution_BANG___31354$fn__31355.invoke(query_processor.clj:281)"
 "query_processor$fn__31349$process_query_and_save_execution_BANG___31354.invoke(query_processor.clj:267)"
 "api.card$run_query_for_card.invokeStatic(card.clj:607)"
 "api.card$run_query_for_card.doInvoke(card.clj:593)"
 "api.public$run_query_for_card_with_id$fn__38223.invoke(public.clj:65)"
 "api.public$run_query_for_card_with_id.invokeStatic(public.clj:63)"
 "api.public$run_query_for_card_with_id.doInvoke(public.clj:58)"
 "api.public$public_dashcard_results.invokeStatic(public.clj:212)"
 "api.public$public_dashcard_results.doInvoke(public.clj:200)"
 "api.public$fn__38377$fn__38378.invoke(public.clj:223)"
 "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:253)"
 "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)"
 "api.public$fn__38377.invokeStatic(public.clj:217)"
 "api.public$fn__38377.invoke(public.clj:217)"
 "middleware$genericize_exceptions$fn__33396.invoke(middleware.clj:359)"
 "api.routes$fn__46397.invokeStatic(routes.clj:79)"
 "api.routes$fn__46397.invoke(routes.clj:79)"
 "routes$fn__47156$fn__47157.doInvoke(routes.clj:106)"
 "routes$fn__47156.invokeStatic(routes.clj:101)"
 "routes$fn__47156.invoke(routes.clj:101)"
 "middleware$log_api_call$fn__33388$fn__33390.invoke(middleware.clj:347)"
 "middleware$log_api_call$fn__33388.invoke(middleware.clj:346)"
 "middleware$add_security_headers$fn__33338.invoke(middleware.clj:249)"
 "core$wrap_streamed_json_response$fn__47951.invoke(core.clj:67)"
 "middleware$bind_current_user$fn__33293.invoke(middleware.clj:138)"
 "middleware$maybe_set_site_url$fn__33342.invoke(middleware.clj:273)"]

04-04 21:35:17 [1mDEBUG metabase.middleware[0m :: GET /api/public/dashboard/e5c446a8-7233-4c8d-807d-5ca9113340fd/card/86 200 (937 ms) (13 DB calls). Jetty threads: 8/50 (11 busy, 1 idle, 0 queued)
04-04 21:35:17 [1mWARN metabase.middleware[0m :: An error occurred while running the query.
04-04 21:35:17 [1mDEBUG metabase.middleware[0m :: GET /api/public/dashboard/e5c446a8-7233-4c8d-807d-5ca9113340fd/card/103 400 (946 ms) (11 DB calls).
"An error occurred."
```

**Comment by camsaul** [comment] 2018-04-04 20:48
@jornh I believe I have a fix for the issue you're seeing. Can you please try out #7272 and let me know if it fixes everything for you?

**Comment by jornh** [comment] 2018-04-04 21:39
That was quick! I’m out of steam for today (close to midnight here) 

... will take it for a spin tomorrow when I get a chance.

**Closed** 2018-04-04 22:51 UTC
Labels: Bug, Embedding, Priority/P1

**Comment by jornh** [comment] 2018-04-05 07:12
Yep! Can confirm that the freshly made new `0.28.5` fixes this issue for me.
