### ISSUE TITLE
DatabaseException during migration from 0.35.4 to 0.36.0

### ISSUE THREAD

**Issue by vreon** [metabase/metabase#12981] opened 2020-07-22 21:47 UTC
**Describe the bug**

Metabase 0.36.0 fails to start, reporting the following exception during migrations:

> Reason: liquibase.exception.DatabaseException: (conn=74) Incorrect datetime value: '2019-03-10 02:00:00.000000' for column 'started_at' at row 75347 [Failed SQL: ALTER TABLE metabase.query_execution MODIFY started_at timestamp(6)]

**Logs**

<details>
<summary>Click to view startup logs</summary>

```
07-22 21:25:16 INFO metabase.core :: Starting Metabase in STANDALONE mode
07-22 21:25:16 INFO metabase.server :: Launching Embedded Jetty Webserver with config:
 {:port 3000, :host "0.0.0.0"}

07-22 21:25:16 INFO metabase.core :: Starting Metabase version v0.36.0 (b31049f release-0.36.x) ...
07-22 21:25:16 INFO metabase.core :: System info:
 {"file.encoding" "UTF-8",
 "java.runtime.name" "OpenJDK Runtime Environment",
 "java.runtime.version" "11.0.7+10",
 "java.vendor" "AdoptOpenJDK",
 "java.vendor.url" "https://adoptopenjdk.net/",
 "java.version" "11.0.7",
 "java.vm.name" "OpenJDK 64-Bit Server VM",
 "java.vm.version" "11.0.7+10",
 "os.name" "Linux",
 "os.version" "3.10.0-1127.13.1.el7.x86_64",
 "user.language" "en",
 "user.timezone" "GMT"}

[...]

07-22 21:25:17 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
07-22 21:25:17 INFO metabase.db :: Verifying mysql Database Connection ...
07-22 21:25:17 INFO driver.impl :: Initializing driver :sql...
07-22 21:25:17 INFO driver.impl :: Initializing driver :sql-jdbc...
07-22 21:25:17 INFO driver.impl :: Initializing driver :mysql...
07-22 21:25:17 INFO metabase.db :: Successfully verified MySQL 5.7.23-25 application database connection. ✅
07-22 21:25:17 INFO metabase.db :: Running Database Migrations...
07-22 21:25:17 INFO metabase.db :: Setting up Liquibase...
07-22 21:25:17 INFO metabase.db :: Liquibase is ready.
07-22 21:25:17 INFO db.liquibase :: Checking if Database has unrun migrations...
07-22 21:25:18 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
07-22 21:25:18 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
07-22 21:25:18 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
07-22 21:25:18 INFO db.liquibase :: Migration lock is cleared. Running migrations...
07-22 21:25:18 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
07-22 21:25:19 ERROR changelog.ChangeSet :: Change Set migrations/000_migrations.yaml::168::camsaul failed.  Error: (conn=74) Incorrect datetime value: '2019-03-10 02:00:00.000000' for column 'started_at' at row 75347 [Failed SQL: ALTER TABLE metabase.query_execution MODIFY started_at timestamp(6)]
07-22 21:25:19 WARN metabase.util :: auto-retry metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__20939@50fbc617: Migration failed for change set migrations/000_migrations.yaml::168::camsaul:
     Reason: liquibase.exception.DatabaseException: (conn=74) Incorrect datetime value: '2019-03-10 02:00:00.000000' for column 'started_at' at row 75347 [Failed SQL: ALTER TABLE metabase.query_execution MODIFY started_at timestamp(6)]
07-22 21:25:19 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
07-22 21:25:21 ERROR changelog.ChangeSet :: Change Set migrations/000_migrations.yaml::168::camsaul failed.  Error: (conn=74) Incorrect datetime value: '2019-03-10 02:00:00.000000' for column 'started_at' at row 75347 [Failed SQL: ALTER TABLE metabase.query_execution MODIFY started_at timestamp(6)]
07-22 21:25:21 WARN metabase.util :: auto-retry metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__20939@50fbc617: Migration failed for change set migrations/000_migrations.yaml::168::camsaul:
     Reason: liquibase.exception.DatabaseException: (conn=74) Incorrect datetime value: '2019-03-10 02:00:00.000000' for column 'started_at' at row 75347 [Failed SQL: ALTER TABLE metabase.query_execution MODIFY started_at timestamp(6)]
07-22 21:25:21 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
07-22 21:25:22 ERROR changelog.ChangeSet :: Change Set migrations/000_migrations.yaml::168::camsaul failed.  Error: (conn=74) Incorrect datetime value: '2019-03-10 02:00:00.000000' for column 'started_at' at row 75347 [Failed SQL: ALTER TABLE metabase.query_execution MODIFY started_at timestamp(6)]
07-22 21:25:22 WARN metabase.util :: auto-retry metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__20939@50fbc617: Migration failed for change set migrations/000_migrations.yaml::168::camsaul:
     Reason: liquibase.exception.DatabaseException: (conn=74) Incorrect datetime value: '2019-03-10 02:00:00.000000' for column 'started_at' at row 75347 [Failed SQL: ALTER TABLE metabase.query_execution MODIFY started_at timestamp(6)]
07-22 21:25:22 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
07-22 21:25:23 ERROR changelog.ChangeSet :: Change Set migrations/000_migrations.yaml::168::camsaul failed.  Error: (conn=74) Incorrect datetime value: '2019-03-10 02:00:00.000000' for column 'started_at' at row 75347 [Failed SQL: ALTER TABLE metabase.query_execution MODIFY started_at timestamp(6)]
07-22 21:25:23 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.MigrationFailedException: Migration failed for change set migrations/000_migrations.yaml::168::camsaul:
     Reason: liquibase.exception.DatabaseException: (conn=74) Incorrect datetime value: '2019-03-10 02:00:00.000000' for column 'started_at' at row 75347 [Failed SQL: ALTER TABLE metabase.query_execution MODIFY started_at timestamp(6)]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.Liquibase.update(Liquibase.java:175)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__20939.invoke(liquibase.clj:126)
	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:423)
	at metabase.util$do_with_auto_retries.invoke(util.clj:415)
	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:430)
	at metabase.util$do_with_auto_retries.invoke(util.clj:415)
	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:430)
	at metabase.util$do_with_auto_retries.invoke(util.clj:415)
	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:430)
	at metabase.util$do_with_auto_retries.invoke(util.clj:415)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:126)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:114)
	at metabase.db$migrate_BANG_$fn__21719$fn__21720.invoke(db.clj:208)
	at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:38)
	at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:29)
	at metabase.db$migrate_BANG_$fn__21719.invoke(db.clj:203)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:852)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at metabase.db$migrate_BANG_.invokeStatic(db.clj:194)
	at metabase.db$migrate_BANG_.invoke(db.clj:173)
	at metabase.db$run_schema_migrations_BANG_.invokeStatic(db.clj:329)
	at metabase.db$run_schema_migrations_BANG_.invoke(db.clj:323)
	at metabase.db$setup_db_BANG__STAR_$fn__21801.invoke(db.clj:346)
	at metabase.util$do_with_us_locale.invokeStatic(util.clj:665)
	at metabase.util$do_with_us_locale.invoke(util.clj:651)
	at metabase.db$setup_db_BANG__STAR_.invokeStatic(db.clj:344)
	at metabase.db$setup_db_BANG__STAR_.invoke(db.clj:339)
	at metabase.db$setup_db_from_env_BANG_.invokeStatic(db.clj:358)
	at metabase.db$setup_db_from_env_BANG_.invoke(db.clj:351)
	at metabase.db$setup_db_BANG_$fn__21806.invoke(db.clj:368)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:366)
	at metabase.db$setup_db_BANG_.invoke(db.clj:361)
	at metabase.core$init_BANG_.invokeStatic(core.clj:75)
	at metabase.core$init_BANG_.invoke(core.clj:54)
	at metabase.core$start_normally.invokeStatic(core.clj:119)
	at metabase.core$start_normally.invoke(core.clj:113)
	at metabase.core$_main.invokeStatic(core.clj:152)
	at metabase.core$_main.doInvoke(core.clj:146)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
Caused by: liquibase.exception.DatabaseException: (conn=74) Incorrect datetime value: '2019-03-10 02:00:00.000000' for column 'started_at' at row 75347 [Failed SQL: ALTER TABLE metabase.query_execution MODIFY started_at timestamp(6)]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:356)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
	... 50 more
Caused by: java.sql.SQLDataException: (conn=74) Incorrect datetime value: '2019-03-10 02:00:00.000000' for column 'started_at' at row 75347
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:232)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:349)
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:484)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352)
	... 55 more
Caused by: java.sql.SQLException: Incorrect datetime value: '2019-03-10 02:00:00.000000' for column 'started_at' at row 75347
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1599)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1461)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1424)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:178)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:343)
	... 57 more
07-22 21:25:23 INFO metabase.core :: Metabase Shutting Down ...
07-22 21:25:23 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
07-22 21:25:23 INFO metabase.core :: Metabase Shutdown COMPLETE
```

</details>

**To Reproduce**
Stop the 0.35.4 container, then start the 0.36.0 container.

**Expected behavior**
Migrations should be successfully applied and Metabase should start.

**Screenshots**
n/a

**Information about your Metabase Installation:**

- Your browser and the version: n/a
- Your operating system: n/a
- Your databases: MySQL 5.6
- Metabase version: 0.36.0
- Metabase hosting environment: Docker on Kubernetes
- Metabase internal database: MySQL 5.7.23 (Percona Server)

**Severity**
A blocker for upgrading, but rolling back to 0.35.4 works fine, so not very urgent.

**Additional context**
n/a

**Comment by alex-bowers** [comment] 2020-07-23 07:47
I'm having something very similar. 

> Change Set migrations/000_migrations.yaml::168::camsaul failed.  Error: (conn=42308878) Incorrect datetime value: '2019-03-31 01:00:00.000000' for column 'started_at' at row 166960 [Failed SQL: ALTER TABLE metabase.query_execution MODIFY started_at timestamp(6)]

**Comment by flamber** [comment] 2020-07-23 15:41
I'm not sure why this is failing, and I haven't been able to reproduce, but I know we made changes specifically in this area.
Do you see a more detailed error on your MySQL server log?

https://github.com/metabase/metabase/blob/ea22d293576e7c404152727d16a010df8facd2c5/resources/migrations/000_migrations.yaml#L6366-L6377

**Comment by sbelak** [comment] 2020-07-23 17:39
Is it possible you are hitting https://dba.stackexchange.com/questions/234270/incorrect-datetime-value-mysql

**Comment by vreon** [comment] 2020-07-23 18:12
Thanks @sbelak, that's definitely it. Looks like Metabase's internal DB was configured to use the `America/Los_Angeles` time zone.

**Comment by flamber** [comment] 2020-07-24 15:56
We're going to close this issue as "won't fix", since it would require a lot of work to try to fix this problem, which caused by bad database configurations and probably affect very few installations.
The workaround would be to remove the rows that is causing problems, or change the time/date on the rows, so it doesn't conflict with DST. And then the upgrade should run smoothly.
Remember to always backup before upgrading or making manual changes to the application database.

**Closed by flamber** 2020-07-24 15:56 UTC
Labels: .Won't Fix, Operation/Database Migrations, Priority:P1, Type:Bug
