### ISSUE TITLE
Fix intermittent CI failures

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2233] opened 2016-03-24 16:16 UTC
It seem like Circle is randomly failing about 50% of the time.

**Comment by camsaul** [comment] 2016-03-24 18:33
Ya about half the time it's the Mongo DB on Circle not responding (not sure what to do about that) and the other half it's the connection the BigQuery randomly failing

**Comment by tlrobinson** [comment] 2016-03-24 18:34
It would be nice if there were a way to skip backend tests if we're only working on the frontend and vice versa.

**Comment by camsaul** [comment] 2016-03-24 18:35
Short of making them separate projects I don't think you can do that with circle

**Comment by agilliland** [comment] 2016-03-24 18:41
Yeah, I would like to find a way to do something like this.  IMO we don't really need to be running the backend driver tests on every push to the repo, it's overkill.  It would be nice if most of the pushes just ran the tests on the main parts of the app which would speed things up and reduce intermittent failures.

**Comment by camsaul** [comment] 2016-03-24 18:46
You can just run the relevant tests locally and then wait to commit until you know they pass. We need to run the full suite before merging something to make sure changing something somewhere didn't accidentally break something somewhere else. Running only "main" tests would kind of defeat the purpose of CI.

**Comment by camsaul** [comment] 2016-03-24 18:51
Instead let's look at ways to address the root causes of the issue. E.g. seeing if we can get Circle's MongoDB to work correctly and opening a ticket with them otherwise.

Maybe adding some auto-retry capability or something to the BigQuery driver. 

If tests fail intermittently that's a sign we need to fix our app, not stop running the tests.

**Comment by salsakran** [comment] 2016-03-24 18:55
I think it's less a sign that we need to fix our app and more a function of our dependency on a managed service not under our control.

Eg. if BigQuery went down for a day, would we want every CI test to fail and hold up deployments until it was back up? Even if none of the new code touched the execution path to BQ?

**Comment by camsaul** [comment] 2016-03-24 19:01
Sure, but there are a lot of cases where you don't think changing one thing will affect something unrelated, an CI is there to catch those weird errors. Might be the case that we tweak some util function that we thought was completely unrelated and CI is there to save us. Selectively deciding which tests to run is a slippery slope prone to human error

Also realistically I don't think we have to worry about BigQuery going down for a day.

**Comment by camsaul** [comment] 2016-03-24 19:03
If 1/100 BigQuery queries fails because of a connection error, it seems to me like we can just make the driver a bit more robust and add some logic to retry in that case. Fix random CI errors and random errors for our users too. That sounds like the right fix for this case

**Comment by salsakran** [comment] 2016-03-24 19:25
Fair enough. If connection errors are that frequent (1/100), we should be retrying.

**Comment by camsaul** [comment] 2016-03-24 19:30
I've reached out to Circle to see if they can pre-install Mongo 3 on circle boxes so we don't have to take the error-prone route of manually installing it ourselves every CI run. They've been helpful about this kind of thing before (Hobbs had them support a newer version of GCC with C++11 support for me in the past) so I'm hoping they can help us resolve our intermittent Mongo issues.

**Comment by camsaul** [comment] 2016-03-24 19:50
I've been poking through test failures on `master` and another thing that fails intermittently a lot is NPM dependencies. `apt-get` dependencies as well to an extent. Maybe the solution is for Circle to stop being wonky :unamused:

**Comment by camsaul** [comment] 2016-03-24 20:31
#2235 should help with this. I'll revisit this in few days to see gauge its impact and take further action if necessary.

**Comment by camsaul** [comment] 2016-04-01 01:58
It looks like random BigQuery  failures are down significantly in CI with new branches off of master since #2235, #2239, and #2248 were merged in. Will continue monitoring the situation :basic-need:

**Comment by agilliland** [comment] 2016-04-01 02:24
I agree, seems significantly more stable.  :+1:

**Comment by camsaul** [comment] 2016-04-08 23:01
![screen shot 2016-04-08 at 3 59 14 pm](https://cloud.githubusercontent.com/assets/1455846/14399590/f046d35e-fda2-11e5-9576-f0138bc55697.png)

In light of our recent 100% CI success rate on master I'm going to declare this issue as officially fixed. This is a great day for Metabase and a BASIC need for all contributors.

**Closed by camsaul** 2016-04-08 23:01 UTC
Labels: Limitation
