### ISSUE TITLE
Page rendering exception for 'Permissions' tab

### ISSUE THREAD

**Issue by JasonWu2008** [metabase/metabase#11962] opened 2020-02-24 03:07 UTC
**Describe the bug**

The table header and the vertical scroll bar will be shaking when you maximize the window. (Please note, the table of role columns is over a screen.) 

**To Reproduce**
Admin -> Data permissions & Collection permissions

**Information about your Metabase Installation:**
-Metabase version: v0.34.2
- Your browser and the version: (e.x. Chrome 80.0, 64bit, Firefox 73.0.1 bit)
- Your operating system: (e.x. Windows 10)

**Comment by flamber** [comment] 2020-02-24 11:05
Duplicate of #8165 - upvote by clicking :+1: on the first post of the issue

**Closed by flamber** 2020-02-24 11:05 UTC
Labels: .Needs Triage, Type:Bug
