### ISSUE TITLE
BigInteger Lost Precision

### ISSUE THREAD

**Issue by hongyang413** [metabase/metabase#24809] opened 2022-08-16 09:56 UTC
Please use the issue chooser, when creating a new issue:

https://github.com/metabase/metabase/issues/new/choose

My environment：
Metabase 0.43.4
databse：mysql

I found some problems about lost precision when using metabase. I also saw  [#5816](https://github.com/metabase/metabase/issues/5816) but it did not solve all the problems. At least in two scenarios, I still encountered the problem of accuracy loss

1.create model through native query
![native query](https://user-images.githubusercontent.com/36788769/184849291-903a1bfe-8bdc-4367-8e9c-109c06f076fb.jpg)
2.query by filter from model
Under the premise of 1, use filter query. When I enter 147248902101323776, it will become 147248902101323800
![image](https://user-images.githubusercontent.com/36788769/184851250-1ba36f90-8a1e-46ab-9a6a-7938f7a0d8c7.png)

**Comment by flamber** [comment] 2022-08-16 09:59
Duplicate of #5816

**Closed by flamber** 2022-08-16 09:59 UTC

**Comment by hongyang413** [comment] 2022-08-16 10:03
If this is Duplicate of [#5816](https://github.com/metabase/metabase/issues/5816) why does this problem still exist in the new version

**Comment by flamber** [comment] 2022-08-16 10:07
@hongyang413 Because 5816 is not fixed. It's a browser problem with handling long integers. There's no simple fix. I don't have a timeline.

**Comment by hongyang413** [comment] 2022-08-16 10:17
> @hongyang413 Because 5816 is not fixed. It's a browser problem with handling long integers. There's no simple fix. I don't have a timeline.

OK, thank you for your answer

**Comment by udisun** [comment] 2022-11-23 09:59
> @hongyang413 Because 5816 is not fixed. It's a browser problem with handling long integers. There's no simple fix. I don't have a timeline.

this is a javascript issue not a browser issue.
