### ISSUE TITLE
Add an ability to send requests to external resourses from metabase behind proxy server

### ISSUE THREAD

**Issue by razer96** [metabase/metabase#10553] opened 2019-08-12 04:07 UTC
Hi! I've faced the following problem. My metabase application is located on a server behind proxy server. I was trying to connect to Slack bot, but as I could notice, all requests to Slack are sent directly and there is no way to send requests via proxy. Clojure also doesn't take into account the environment variables of the operating system, which makes it impossible to simply define env variables in the docker container and not worry about whether your request will be delivered or not.

**Describe the solution you'd like**
I would like you to add a feature that allows set proxy settings for request-fn. As I understand all requests to Slack are sent via this function, and I would like to set ENV variables like MB_PROXY_HOST and MB_PROXY_PORT, then request_fn would use this variables to send all request through proxy server.

The link below refers to an example of how I would like it to work:
https://www.codetd.com/en/article/6327748

**How important is this feature to you?**
This problem is very relevant for me, and perhaps for some developers who are deploying metabase application behind a proxy server.

**Comment by flamber** [comment] 2019-08-12 04:25
Hi @razer96 
It sounds like a duplicate of #3236 - if you agree, then please close this issue :+1:

**Comment by razer96** [comment] 2019-08-12 04:35
@flamber, oh, sure, I do. It is the same.

**Comment by flamber** [comment] 2019-08-12 04:47
@razer96 
Did you try the Java options, which are non-specific to Metabase?
Slack should work over `https` - but there's issues with MetaBot, from reading the comments.
```
-Dhttp.proxyHost=[YourProxyHost] -Dhttp.proxyPort=[YourProxyPort] -Dhttps.proxyHost=[YourProxyHost] -Dhttps.proxyPort=[YourProxyPort]
```

**Closed** 2019-08-12 04:54 UTC
Labels: Type:New Feature
