### ISSUE TITLE
Display the value on the graph

### ISSUE THREAD

**Issue by AB-Nagashima** [metabase/metabase#13464] opened 2020-10-14 07:37 UTC
**Is your feature request related to a problem? Please describe.**
We can't see the value without hovering over the graph.
But we want to know the value clear at a glance without hovering.
That way, we can see the values ​​when printing.

**Describe the solution you'd like**
Display the value on the graph.

**How important is this feature to you?**
It's important to know the value when we printing.

**Additional context**
![Image](https://user-images.githubusercontent.com/72788057/95957997-71339f80-0e3b-11eb-80d4-ab69bb3f2191.png)

**Comment by flamber** [comment] 2020-10-14 08:37
Duplicate of #12977

**Closed by flamber** 2020-10-14 08:37 UTC
Labels: .Needs Triage, Type:New Feature
