### ISSUE TITLE
MBQL relative-datetime clause should support extraction units

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14868] opened 2021-02-18 03:04 UTC
Right now `relative-datetime` (or `time-interval` for that matter) only supports "truncation" units, e.g. `minute`, `hour`, `day`, `week`, etc. It doesn't currently support "extraction units" like `:minute-of-hour`, `:day-of-week`, `:day-of-month`, etc.

This is enforced by the MBQL schema itself, but I don't see any reason why this should actually be the case. This is an example use-case:

```clj
;; show me the count of checkins for the same day of the week as today, for last week
;; e.g. if today is Wednesday, show me count of checkins for *last* Wednesday
(mt/run-mbql-query checkins
  {:aggregation [[:count]]
   :filter      [:and
                 [:time-interval $date :current :day-of-week]
                 [:time-interval $date :last :week]]})
```

If we lift the restriction from the schema itself I think this would mostly work, but we might have to tweak a few things to support it. I think the FE client doesn't currently allow this.

**Comment by flamber** [comment] 2021-11-15 17:34
This is a duplicate of #7614, which has 32 upvotes, so closing in favor of that issue.

**Closed by flamber** 2021-11-15 17:34 UTC
Labels: Querying/MBQL, Type:New Feature
