### ISSUE TITLE
Download results from within the dashboard (non-embedded)

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#25424] opened 2022-09-14 21:55 UTC
**Is your feature request related to a problem? Please describe.**
Would be nice if you could download the card results from within the dashboards, not having to click on the question and then downloading from there

**Describe the solution you'd like**
Download the card results from the dashboard

**Describe alternatives you've considered**
None

**How important is this feature to you?**
Requested by a customer

**Additional context**
NA

**Comment by flamber** [comment] 2022-09-15 08:03
Duplicate of #13546

**Closed by flamber** 2022-09-15 08:03 UTC
Labels: Reporting/Dashboards, Type:New Feature, Reporting/Export
