### ISSUE TITLE
Summarizing sum and grouping by date fails on using saved question as base data

### ISSUE THREAD

**Issue by gvaibhavraj2** [metabase/metabase#16615] opened 2021-06-16 08:11 UTC
**Bug** 
When using existing saved question as the base data and building questions in top of it, it shows error

Value does not match schema: {:query {:breakout [(named (not (":field clauses using a string field name must specify :base-type." a-clojure.lang.PersistentVector)) "Must be a valid instance of one of these clauses: :expression, :field")]}}

**Logs**
`[c912d870-60c5-4440-8ec4-9a7c73afa041] 2021-06-16T11:30:35+05:30 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: null
{:database_id 2,
 :started_at #t "2021-06-16T11:30:35.760232+05:30[Asia/Kolkata]",
 :error_type :invalid-query,
 :json_query
 {:type "query",
  :query
  {:source-table "card__67",
   :filter
   ["and"
    ["time-interval" ["field" "createdat" {:base-type "type/DateTime"}] -7 "day" {:include-current true}]
    ["=" ["field" "state" {:base-type "type/Text"}] "PROCESSED"]
    ["!=" ["field" "plantype" {:base-type "type/Text"}] "VIP"]],
   :aggregation [["sum" ["field" "paymentamount" {:base-type "type/Float"}]]],
   :breakout [["field" "createdat" {:temporal-unit "day"}]]},
  :database 2,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native nil,
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> util.schema$schema_core_validator$fn__16373.invoke(schema.clj:29)"
  "query_processor.middleware.validate$validate_query$fn__49643.invoke(validate.clj:9)"
  "query_processor.middleware.normalize_query$normalize$fn__47524.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44790.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49574.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__46641.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__48686.invoke(process_userland_query.clj:135)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46581.invoke(catch_exceptions.clj:173)"
  "query_processor.reducible$async_qp$qp_STAR___38051$thunk__38052.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___38051.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___38060$fn__38063.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___38060.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:241)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:237)"
  "query_processor$fn__49733$process_query_and_save_execution_BANG___49742$fn__49745.invoke(query_processor.clj:253)"
  "query_processor$fn__49733$process_query_and_save_execution_BANG___49742.invoke(query_processor.clj:245)"
  "query_processor$fn__49777$process_query_and_save_with_max_results_constraints_BANG___49786$fn__49789.invoke(query_processor.clj:265)"
  "query_processor$fn__49777$process_query_and_save_with_max_results_constraints_BANG___49786.invoke(query_processor.clj:258)"
  "api.dataset$run_query_async$fn__55990.invoke(dataset.clj:56)"
  "query_processor.streaming$streaming_response_STAR_$fn__55969$fn__55970.invoke(streaming.clj:72)"
  "query_processor.streaming$streaming_response_STAR_$fn__55969.invoke(streaming.clj:71)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$fn__16071.invoke(streaming_response.clj:84)"],
 :context :ad-hoc,
 :error
 "Value does not match schema: {:query {:breakout [(named (not (\":field clauses using a string field name must specify :base-type.\" a-clojure.lang.PersistentVector)) \"Must be a valid instance of one of these clauses: :expression, :field\")]}}",
 :row_count 0,
 :running_time 0,
 :preprocessed nil,
 :ex-data
 {:type :schema.core/error,
  :value
  {:type :query,
   :query
   {:source-table "card__67",
    :filter
    [:and
     [:time-interval [:field "createdat" {:base-type :type/DateTime}] -7 :day {:include-current true}]
     [:= [:field "state" {:base-type :type/Text}] "PROCESSED"]
     [:!= [:field "plantype" {:base-type :type/Text}] "VIP"]],
    :aggregation [[:sum [:field "paymentamount" {:base-type :type/Float}]]],
    :breakout [[:field "createdat" {:temporal-unit :day}]]},
   :database 2,
   :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
   :info
   {:executed-by 1,
    :context :ad-hoc,
    :card-id 67,
    :nested? true,
    :query-hash
    [122, 110, -90, -31, 71, 0, 121, 70, -106, -58, 51, 100, 47, 33, -23, 92, -117, -108, 98, 125, 96, -15, 123, -19,
     -68, 109, -61, -54, -58, 38, 59, -113]},
   :constraints {:max-results 10000, :max-results-bare-rows 2000}},
  :error
  {:query
   {:breakout
    [(named (not (":field clauses using a string field name must specify :base-type." a-clojure.lang.PersistentVector)) "Must be a valid instance of one of these clauses: :expression, :field")]}}},
 :data {:rows [], :cols []}}
`

**Installation**
`{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.14.225-169.362.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Kolkata"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "redshift"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-27",
      "tag": "v0.39.3",
      "branch": "release-x.39.x",
      "hash": "598a112"
    },
    "settings": {
      "report-timezone": "Asia/Kolkata"
    }
  }
}`

**Severity**
Breaking our questions in production. Blocked

**Comment by flamber** [comment] 2021-06-16 08:42
Duplicate of #16327

**Closed by flamber** 2021-06-16 08:42 UTC
