### ISSUE TITLE
Hide Legend

### ISSUE THREAD

**Issue by yogidup-xx** [metabase/metabase#9093] opened 2018-12-10 02:05 UTC
![selection_579](https://user-images.githubusercontent.com/6147959/49706757-64036380-fc5a-11e8-8e21-8e9b41fdd658.png)

For some reason I need to hide those legend to make dashboard more clean, how i can do it in metabase?

**Comment by flamber** [comment] 2019-02-22 17:47
Related to #8437

**Comment by mazameli** [comment] 2019-10-08 21:27
I think I'm going to retitle #8437 to make it more general (ability to hide legends for any chart) and close this issue as a duplicate of that.

**Closed by mazameli** 2019-10-08 21:27 UTC
Labels: .Proposal, Duplicate, Visualization/Chart Settings
