### ISSUE TITLE
Creating custom column from changed name tables/columns

### ISSUE THREAD

**Issue by PauloHFM** [metabase/metabase#11519] opened 2019-12-13 21:22 UTC
Trying to create a simple custom column, and it won't work.

Maybe it's because I changed the names of the columns and table in admin mode, because in tables I didn't change the name it doesn't happen.

A column from the question is "margin_gross" and this simple custom column:

![Screenshot from 2019-12-13 18-18-04](https://user-images.githubusercontent.com/38223133/70832921-1cffff00-1dd5-11ea-9028-23e4c6033355.png)

Throws out this error: 

![Screenshot from 2019-12-13 18-16-31](https://user-images.githubusercontent.com/38223133/70832918-1bced200-1dd5-11ea-9003-f9ada390c2c5.png)

Using Metabase version 0.33.6 Jar file on postgres. 

This is a only question modification so it not viable to put it on the table on the database.

Thanks!

**Comment by flamber** [comment] 2019-12-13 21:37
Just adding this, since we cannot search images:
`Input to expression-with-name does not match schema: [0;33m [(named (not (map? nil)) arg0) nil] [0m`
Do you see other errors or more details in the log?
Are you querying Postgres, or using it for metadata, or both?
Do you have any way to reproduce this? What's the column type of `margin_gross`?

**Comment by mazameli** [comment] 2019-12-13 23:03
I'm still digging into this, but I've been able to reproduce it on some but not all of my local datasets. Still searching for a pattern, but I'm seeing this in the JS console:

```
expression error: Error: Unknown field "away err ct"
    at t.value (app-main.bundle.js?86ec783e929e6e5a32b3:5)
    at t.<anonymous> (app-main.bundle.js?86ec783e929e6e5a32b3:5)
    at t.<anonymous> (vendor.bundle.js?86ec783e929e6e5a32b3:1)
    at t.s [as dimensionExpression] (vendor.bundle.js?86ec783e929e6e5a32b3:1)
    at t.e.SUBRULE1 (vendor.bundle.js?86ec783e929e6e5a32b3:1)
    at t.e.SUBRULE (vendor.bundle.js?86ec783e929e6e5a32b3:1)
    at t.ALT (app-main.bundle.js?86ec783e929e6e5a32b3:5)
    at t.e.orInternal (vendor.bundle.js?86ec783e929e6e5a32b3:1)
    at t.e.OR1 (vendor.bundle.js?86ec783e929e6e5a32b3:1)
    at t.e.OR (vendor.bundle.js?86ec783e929e6e5a32b3:1)
```

Here's what the query looked like:

![Screen Shot 2019-12-13 at 2 19 45 PM](https://user-images.githubusercontent.com/2223916/70836589-77896300-1db5-11ea-92c2-fb8c274ec29f.png)

This is a postgres db, and those columns are ints. I thought the problem might have to do with columns that have been renamed, and I'm still trying out that hypothesis, but so far it doesn't seem to be consistently the case. I'm definitely _not_ seeing this problem on every postgres database, nor every integer column that's been renamed.

**Comment by ScottDHall** [comment] 2020-03-30 12:07
I'm seeing this issue on SQL Azure (Hosted SQL Server).  I did change the name of the table in Metabase because the import mangled the spelling.

**Comment by sbelak** [comment] 2020-04-23 14:50
@ScottDHall can you describe steps to reproduce more specifically. What does the custom column expression look like? What are the types of the fields it uses? Do you have any remappings or some such?

**Comment by ScottDHall** [comment] 2020-04-23 16:23
The database is a SQL Azure database, which is basically SQL Server hosted/managed by Azure and is about 90% of what SQL Server has, but you can't do anything with the master table.

I imported the database tables and they came in with weird spacings as though Metabase was trying to format them nicer. It was renaming tables like BentexxMonthlySummary as B Ente Xx Monthly Summary  (not the real name, but something similar)  I changed the name to Bentexx Monthly Summary.  The column types are ints and money.

**Comment by ChakshuGautam** [comment] 2020-04-28 15:05
Is this still open? We are facing the issue while using Metabase with [ODK Aggregate ](https://github.com/getodk/aggregate) server data.

**Comment by flamber** [comment] 2020-05-15 07:37
I cannot reproduce this on `master` using with the steps in Maz's https://github.com/metabase/metabase/issues/11519#issuecomment-565642442. I would guess it's fixed by some of the laziness fixes.

**Comment by flamber** [comment] 2020-06-07 10:11
Closing, since #12387 was added to 0.35.4. Please comment with details if you're still seeing this.

**Closed by flamber** 2020-06-07 10:11 UTC
Labels: Priority:P2, Querying/Notebook, Type:Bug
