### ISSUE TITLE
Select / Unselect columns in question

### ISSUE THREAD

**Issue by Philippe-M** [metabase/metabase#16289] opened 2021-05-31 07:15 UTC
Hello,

When creating a question, when you want to select the columns to display, it is not possible to deselect everything with a click.

![image](https://user-images.githubusercontent.com/4558101/120154824-87d30f00-c1f0-11eb-8042-c81c0ab13fa6.png)

Metabase 0.39.3

**Comment by flamber** [comment] 2021-05-31 09:28
Duplicate of #10460

**Closed by flamber** 2021-05-31 09:28 UTC
Labels: .Needs Triage, Type:New Feature
