### ISSUE TITLE
Table Fields Overlapping Across Databases with the Same Table Name

### ISSUE THREAD

**Issue by EndikaRamos** [metabase/metabase#50138] opened 2024-11-18 12:55 UTC
### Describe the bug

When adding two MySQL databases (**test1** and **test2**) in Metabase, both containing a table named `customer` but with different schemas, the fields from the `customer` table in one database are incorrectly merged or displayed in the schema or query results of the other `customer` table. This results in schema confusion and incorrect query outputs.
![Image](https://github.com/user-attachments/assets/47841f5c-9c2a-423b-aa8c-2056fd42d92b)
![Image](https://github.com/user-attachments/assets/ccfe2c6d-723a-4967-a1d9-e0a6bd6ad8d3)

### Steps to Reproduce:

1. Go to Metabase and add two MySQL databases, let's call them **test1** and **test2**, both hosted on the same MySQL server (`localhost`).
2. Each database contains a table named `customer`, but their structures are different:
   - **test1.customer**:
     ```sql
     CREATE TABLE `customer` (
       `customer_id` int(11) NOT NULL AUTO_INCREMENT,
       `first_name` varchar(50) NOT NULL,
       `last_name` varchar(50) NOT NULL,
       `email` varchar(100) NOT NULL,
       `phone_number` varchar(15) DEFAULT NULL,
       `created_at` timestamp NULL DEFAULT current_timestamp(),
       PRIMARY KEY (`customer_id`),
       UNIQUE KEY `email` (`email`)
     ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
     ```
   - **test2.customer**:
     ```sql
     CREATE TABLE `customer` (
       `customer_id` int(11) NOT NULL AUTO_INCREMENT,
       `order_name` varchar(50) NOT NULL,
       `other_name` varchar(50) NOT NULL,
       `email2` varchar(100) NOT NULL,
       `phone2` varchar(15) DEFAULT NULL,
       `created_at` timestamp NULL DEFAULT current_timestamp(),
       PRIMARY KEY (`customer_id`),
       UNIQUE KEY `email2` (`email2`)
     ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
     ```
3. In Metabase, attempt to query one of the `customer` tables (e.g., from **test1**).
4. Observe the error: Fields from the other `customer` table (e.g., from **test2**) appear in the query interface or results, causing confusion.

### Expected behavior

**Expected behavior**

Each table in Metabase should only display fields that belong to its corresponding database and table schema. Fields from tables in other databases with the same name should not interfere.

**Actual Behavior:**
Fields from the customer table in test2 are included in the query or schema view of the customer table in test1, and vice versa. This leads to unexpected query results and incorrect schema representation.

### Information about your Metabase installation

```JSON
Metabase 0.51.3
Server version: 10.11.6-MariaDB-0+deb12u1 Debian 12
```

### Severity

High

### Additional context

Both databases are hosted on the same MySQL instance (localhost).
The issue seems to arise because the tables have the same name (customer) despite being in different databases. Metabase appears to conflate the schemas of tables with identical names across databases.

**Comment by paoliniluis** [comment] 2024-11-18 13:51
duplicate of https://github.com/metabase/metabase/issues/50072, fixed already

**Closed by paoliniluis** 2024-11-18 13:51 UTC
Labels: Type:Bug, .Needs Triage

**Comment by crisptrutski** [comment] 2024-11-19 07:19
Unsure of whether this is sync or query builder issue, worth ruling out the former first I think.
