### ISSUE TITLE
Issue processing Mongo BigDecimal when values are less than 0

### ISSUE THREAD

**Issue by yohfreeman** [metabase/metabase#44506] opened 2024-06-20 20:33 UTC
### Describe the bug

I'm working on a collection that contains several BigDecimal columns. Occasionally, there are negative values, for example -0.02. This results in a the following error:  :error "Negative zero can not be converted to a BigDecimal". The error occurs during the initial table analysis, as well as attempting to visualize the data.

### To Reproduce

Load the following records into a mongodb collection:
{"_id":{"$oid":"765f669ee10537b1f9251821"},"recType":"driver","status":"active","rate":{"rateType":"driver","basePerMinRate":{"$numberDecimal":"0.72"},"day":{"percentage":{"$numberDecimal":"-0.01"}},"evening":{"percentage":{"$numberDecimal":"0.02"}},"night":{"percentage":{"$numberDecimal":"1.87"}},"blocked":{"percentage":{"$numberDecimal":"1.33"}}},"audit":{"createdTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedBy":{"$oid":"4461766566467265656d616e"}}}
{"_id":{"$oid":"765f669ee10537b1f9251822"},"recType":"driver","status":"active","rate":{"rateType":"driver","basePerMinRate":{"$numberDecimal":"0.63"},"day":{"percentage":{"$numberDecimal":"0.03"}},"evening":{"percentage":{"$numberDecimal":"0.0"}},"night":{"percentage":{"$numberDecimal":"2.66"}},"blocked":{"percentage":{"$numberDecimal":"1.04"}}},"audit":{"createdTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedBy":{"$oid":"4461766566467265656d616e"}}}
{"_id":{"$oid":"765f669ee10537b1f9251823"},"recType":"driver","status":"active","rate":{"rateType":"driver","basePerMinRate":{"$numberDecimal":"0.44"},"day":{"percentage":{"$numberDecimal":"-0.12"}},"evening":{"percentage":{"$numberDecimal":"0.09"}},"night":{"percentage":{"$numberDecimal":"2.87"}},"blocked":{"percentage":{"$numberDecimal":"1.25"}}},"audit":{"createdTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedBy":{"$oid":"4461766566467265656d616e"}}}
{"_id":{"$oid":"765f669ee10537b0b2b4b061"},"recType":"driver","status":"active","rate":{"rateType":"driver","basePerMinRate":{"$numberDecimal":"0.51"},"day":{"percentage":{"$numberDecimal":"-0.07"}},"evening":{"percentage":{"$numberDecimal":"-0.03"}},"night":{"percentage":{"$numberDecimal":"2.09"}},"blocked":{"percentage":{"$numberDecimal":"1.21"}}},"audit":{"createdTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedBy":{"$oid":"4461766566467265656d616e"}}}
{"_id":{"$oid":"765f669ee10537b0b2b4b062"},"recType":"driver","status":"active","rate":{"rateType":"driver","basePerMinRate":{"$numberDecimal":"0.61"},"day":{"percentage":{"$numberDecimal":"0.01"}},"evening":{"percentage":{"$numberDecimal":"0.09"}},"night":{"percentage":{"$numberDecimal":"1.75"}},"blocked":{"percentage":{"$numberDecimal":"1.03"}}},"audit":{"createdTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedBy":{"$oid":"4461766566467265656d616e"}}}

Attempt to create the metadata and you will see the error

### Expected behavior

The system should be able to use a BigDecimal value of -0.02 for example.

### Logs

.41baa84f-a01f-4586-ac50-d00ca1b24dc1] 2024-06-20T16:08:34-04:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: Negative zero can not be converted to a BigDecimal
{:database_id 2,
 :started_at #t "2024-06-20T16:08:33.877420-04:00[America/New_York]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error reducing result rows: Negative zero can not be converted to a BigDecimal",
   :stacktrace
   ["--> query_processor.pipeline$_STAR_reduce_STAR_$fn__56619.invoke(pipeline.clj:65)"
    "query_processor.pipeline$_STAR_reduce_STAR_.invokeStatic(pipeline.clj:62)"
    "query_processor.pipeline$_STAR_reduce_STAR_.invoke(pipeline.clj:49)"
    "query_processor.pipeline$_STAR_run_STAR_$respond__56626.invoke(pipeline.clj:86)"
    "driver.mongo.execute$reduce_results.invokeStatic(execute.clj:177)"
    "driver.mongo.execute$reduce_results.invoke(execute.clj:171)"
    "driver.mongo.execute$execute_reducible_query.invokeStatic(execute.clj:207)"
    "driver.mongo.execute$execute_reducible_query.invoke(execute.clj:182)"
    "driver.mongo$fn__118236$f__114486__auto____118237.invoke(mongo.clj:314)"
    "driver.mongo.connection$do_with_mongo_client$fn__114477.invoke(connection.clj:94)"
    "util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:165)"
    "util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:154)"
    "driver.mongo.connection$do_with_mongo_client.invokeStatic(connection.clj:89)"
    "driver.mongo.connection$do_with_mongo_client.invoke(connection.clj:85)"
    "driver.mongo$fn__118236.invokeStatic(mongo.clj:313)"
    "driver.mongo$fn__118236.invoke(mongo.clj:310)"
    "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47)"
    "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34)"
    "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:88)"
    "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:81)"
    "query_processor.execute$run.invokeStatic(execute.clj:60)"
    "query_processor.execute$run.invoke(execute.clj:54)"
    

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "22.0.1",
    "java.vendor": "Homebrew",
    "java.vendor.url": "https://github.com/Homebrew/homebrew-core/issues",
    "java.version": "22.0.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "22.0.1",
    "os.name": "Mac OS X",
    "os.version": "14.5",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-19",
      "tag": "v0.50.6",
      "hash": "a5fbebf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Blocking my usage of Metabase entirely

### Additional context

If you remove the negative sign from the sample data I provided, metabase will work fine.

**Comment by lbrdnk** [comment] 2024-06-24 09:33
Hey [yohfreeman](https://github.com/yohfreeman)! Thanks for the report.

I'm unable to reproduce with the provided data. I have a clue what could be causing the issue, but I'd like to make sure the error you are seeing is an instance of what I suspect.

_Could you confirm that you are hitting the exception on the provided data?_ I've found no problem working with the negative close to zero values. I've even tried to add minus to `0.02` in the data provided, as the `-0.02` is not present.

---

In case of answer to my question is negative, could you confirm the data you have, or rather the query that you run, may contain result _negative zero_, ie. `{"$numberDecimal":"-0.0"}}`?

**Comment by lbrdnk** [comment] 2024-06-24 16:26
Thanks for the confirmation. When the linked PR is merged and released, you should be able to work also with data containing negative zero.

**Closed** 2024-06-27 15:33 UTC
Labels: Type:Bug, Priority:P1, Database/Mongo, Querying/Processor, .Team/QueryProcessor, Release-Blocker:50
