### ISSUE TITLE
Caching in External Redis

### ISSUE THREAD

**Issue by kp3nguinz** [metabase/metabase#17095] opened 2021-07-16 15:36 UTC
**Is your feature request related to a problem? Please describe.**
We currently max out our containers and have multiple caching problems for some of our larger queries.

**Describe the solution you'd like**
we've seen better performance of our apps which push the cache to our Redis Clusters, and would like the support for the same here.

**Describe alternatives you've considered**
beefing up the container and mysql backend

**How important is this feature to you?**
Note: the more honest and specific you are here the more we will take you seriously. 
Extremely important, we cannot use this in production till we figure out a way to take loading times to sub-1m.

**Additional context**
Our queries contain 10's of TB's of data each.

**Comment by paoliniluis** [comment] 2021-07-16 16:02
Hi, this is a duplicate of https://github.com/metabase/metabase/issues/10129, if you are using Metabase Enterprise, please contact support so we can prioritize this

**Closed by paoliniluis** 2021-07-16 16:02 UTC
Labels: .Needs Triage, Type:New Feature

**Comment by jeff303** [comment] 2021-07-16 16:06
Also, in adding more context to #10129, please explain a bit more about the usage pattern.  I'm having a hard time understanding how tens of TBs of data can be handled visually, at all?  How many rows result from these queries?  Or do you mean you're running aggregations/filtering on tables that have tens of TBs of "raw" data, in which case, I would expect the data that ends up passing through Metabase to the frontend is much smaller.

**Comment by kp3nguinz** [comment] 2021-07-16 16:14
> Also, in adding more context to #10129, please explain a bit more about the usage pattern. I'm having a hard time understanding how tens of TBs of data can be handled visually, at all? How many rows result from these queries? Or do you mean you're running aggregations/filtering on tables that have tens of TBs of "raw" data, in which case, I would expect the data that ends up passing through Metabase to the frontend is much smaller.

Raw data, though it is about 100GB of data in the cache.
