### ISSUE TITLE
Convert to SQL results in SQL error for generated query

### ISSUE THREAD

**Issue by albertoperdomo** [metabase/metabase#36078] opened 2023-11-23 12:35 UTC
### Describe the bug

I am using Query Editor and then convert to SQL. The resulting SQL query returns a SQL error.

### To Reproduce

1. Open [this table](https://stats.metabase.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoxNCwidHlwZSI6InF1ZXJ5IiwicXVlcnkiOnsic291cmNlLXRhYmxlIjoxMjMzfX0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==)
2. Click on Show Editor
3. Click on View the SQL
4. Click on Convert this question to SQL
5. Click on Run Query
6. A SQL error is shown (pasted below)

```
ERROR: operator does not exist: >> text[] Hint: No operator matches the given name and argument type. You might need to add an explicit type cast. Position: 175
```

### Expected behavior

The generated SQL doesn't have errors

### Information about your Metabase installation

```JSON
- Stats Built on 2023-11-23 Hash: 03ed7cc
```

### Severity

I am not sure what causes the issue or how likely customers will run into this. I imagine I am hitting some edge case since convert to SQL is working with other questions.

**Comment by ranquild** [comment] 2023-12-08 12:07
I could not reproduce it because the question from step 1 seems broken. However the corresponding SQL query comes from the BE and if there is an issue with that it should be fixed there. Related to https://github.com/metabase/metabase/issues/36175

**Closed** 2023-12-08 22:54 UTC
Labels: Type:Bug, Priority:P1, Querying/Processor, .Backend, .Team/QueryProcessor
