### ISSUE TITLE
Different font size in a pivot table on a fullscreen dashboard

### ISSUE THREAD

**Issue by Philippe-M** [metabase/metabase#23073] opened 2022-06-01 06:23 UTC
Hello,

When a pivot table is displayed in a dashboard, the font size is different between full screen mode and normal mode.

- Metabase 0.43.2
- Firefox 100
- Chromium 92

Normal mode
![image](https://user-images.githubusercontent.com/4558101/171340640-4f5b7cd0-926b-43b4-a886-c1edeb59241f.png)

Full screen
![image](https://user-images.githubusercontent.com/4558101/171340773-767eaca4-6929-42be-9323-46a4ea30099d.png)

**Comment by flamber** [comment] 2022-06-02 12:44
Duplicate of #9615

**Closed by flamber** 2022-06-02 12:44 UTC
Labels: Type:Bug, .Needs Triage
