### ISSUE TITLE
Ability to use boolean field in Custom Expression

### ISSUE THREAD

**Issue by guillaume-chech** [metabase/metabase#19460] opened 2021-12-22 15:13 UTC
**Is your feature request related to a problem? Please describe.**
When using expressions like , `case` or `countif` if Custom Question Notebook, it's not possible to use directly a boolean field as a condition, it would return `Unknown Segment` error. 

**Describe the solution you'd like**
Make possible to use boolean field in place of `Something that evaluated to true or false` in Custom Expression/ Custom Column Builder

**Describe alternatives you've considered**
No alternative found 

**How important is this feature to you?**
This is critical as this make boolean field usable only in filter/group by and no alternative was found.

**Screenshot**
<img width="1428" alt="Screenshot 2021-12-22 at 16 09 05" src="https://user-images.githubusercontent.com/24913696/147113971-4205175e-79d1-4b9c-be77-e7948eb49ba0.png">

**Comment by flamber** [comment] 2021-12-22 17:26
Duplicate of #12393

**Closed by flamber** 2021-12-22 17:26 UTC
Labels: Type:New Feature, .Needs Triage
