### ISSUE TITLE
Variable Field Type after upgrade "Input to parse-value-to-field-type does not match schema"

### ISSUE THREAD

**Issue by ticup** [metabase/metabase#15901] opened 2021-05-03 09:48 UTC
**Describe the bug**
We just upgraded from 0.38 to 0.39.01, which broke our query Variables - Field Type.
All queries with such variables now return: 
> Input to parse-value-for-field-type does not match schema: [0;33m [(named (not ("Valid field type" nil)) effective-type) nil] [0m

For some it was fixed by going to the database model and remove the cached field values + rescan, but for other variables this doesn't fix it.

**Logs**
```
app-main.bundle.js?c27310ee92f8f98b4fb8:5 Error getting setting scalar.field TypeError: Cannot read property 'name' of undefined
    at Object.getDefault (app-main.bundle.js?c27310ee92f8f98b4fb8:5)
    at _ (app-main.bundle.js?c27310ee92f8f98b4fb8:5)
    at t.getComputedSettings (app-main.bundle.js?c27310ee92f8f98b4fb8:5)
 b8:495
Show 22 more frames
app-main.bundle.js?c27310ee92f8f98b4fb8:5 error Input to parse-value-for-field-type does not match schema: 

	 [0;33m  [(named (not ("Valid field type" nil)) effective-type) nil] [0m 
```

**To Reproduce**
1. Go to 'question with field type variable'
2. Click on 'run'

**Expected behavior**
no errors

**Screenshots**

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.6+10-post-Debian-1bpo91",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.6+10-post-Debian-1bpo91",
    "os.name": "Linux",
    "os.version": "4.19.0-6-amd64",
    "user.language": "en",
    "user.timezone": "Europe/Brussels"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.23"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-20",
      "tag": "v0.39.0.1",
      "branch": "release-x.39.x",
      "hash": "47bb5f2"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}
```
**Severity**
We have a lot of dashboard queries that rely on these variable field types, which are now all broken.
We base our daily operations on the results of these queries, so quite annoying.
It's possible to go around it by not using the variables, but by manually inserting the values in the queries, but we have a lot of them.

**Additional context**
Happened after upgrade from 0.38.X to 0.39.01.
In the metabase db table metabase_field  I found this in the fingerprint of a failing field used by variables:
> {"global":{"distinct-count":17,"nil%":0.0},"type":{"type/DateTime":{"earliest":"2021-04-19T13:30:47Z","latest":"2021-04-22T10:10:21Z"}}}

It might have something to do with the "nil%"?

**Comment by flamber** [comment] 2021-05-03 10:23
Hi @ticup 
Upgrade to 0.39.1 - duplicate of #15700

**Comment by ticup** [comment] 2021-05-03 11:37
@flamber  Thanks for the reply.
I upgraded to 0.39.1, but the problem persists :(

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.6+10-post-Debian-1bpo91",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.6+10-post-Debian-1bpo91",
    "os.name": "Linux",
    "os.version": "4.19.0-6-amd64",
    "user.language": "en",
    "user.timezone": "Europe/Brussels"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.23"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-27",
      "tag": "v0.39.1",
      "branch": "release-x.39.x",
      "hash": "6beba48"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}
```

**Comment by ticup** [comment] 2021-05-03 11:40
On 0.39.1:
<img width="1434" alt="Screenshot 2021-05-03 at 13 39 58" src="https://user-images.githubusercontent.com/962776/116871773-15810600-ac15-11eb-826a-f3036e97b7eb.png">

**Comment by flamber** [comment] 2021-05-03 12:00
@ticup 
What is the Field Type in Admin > Data Model > production > users > created?
Does this only happen to variables that are Field Filter? And does it only happen to date column types?

**Comment by ticup** [comment] 2021-05-03 12:44
@flamber 
It's a "Creation Stamp".
<img width="1106" alt="Screenshot 2021-05-03 at 14 36 55" src="https://user-images.githubusercontent.com/962776/116876662-174ec780-ac1d-11eb-80f0-6f3a0027dc7c.png">

It was also the case with other types, e.g. with Country, but for that one it was resolved after clearing cached field values + re-scanning. For the creation stamp the problem remains, even after those actions.

Tried some other types and it's the same problem whenever it tries to do something "smart" with the field type.
When I use a filter type that is mapped to a category and change the "Filter Widget Type" from "Category" to "None" it works, but the error remains when it's on "Category".

**Comment by flamber** [comment] 2021-05-03 12:51
@ticup Please provide the full stacktrace from Admin > Troubleshooting > Logs.
I'm 99% sure that it has nothing to do with scan.

**Comment by ticup** [comment] 2021-05-03 12:58
Only thing in logs:

```
[fa910e1c-3431-4926-8dc3-1e0e4e37fd9c] 2021-05-03T13:35:36+02:00 ERROR metabase.driver.sql-jdbc.execute Failed to set timezone 'Europe/Brussels' for :mysql database
java.sql.SQLTransientConnectionException: (conn=248) Unknown or incorrect time zone: 'Europe/Brussels'
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:79)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:363)
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:501)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
```

I've seen this one before though, so I'm not sure why this would suddenly cause errors for the variable fields (also non-time field variables).

<img width="557" alt="Screenshot 2021-05-03 at 14 58 25" src="https://user-images.githubusercontent.com/962776/116878722-0c496680-ac20-11eb-9978-1389b9ad1604.png">

**Comment by flamber** [comment] 2021-05-03 13:28
@ticup Okay, that's unrelated. It's because you don't have tzdata in your MySQL.

But the error indicates that it comes from the backend, which is weird if there's nothing in the log, when you see the error in the frontend.
Check the returned request of `/api/dataset` in your browser developer Network-tab, since the response should contain more details of the problem.

I think we need to find the root cause in the application database in the table `report_card`, which might have a wrong reference somehow.
If you create a new question exactly matching the one, which is causing problems, does that new question work? If yes, please save it and then export `report_card` for the working and failing question, so we can see where the problem could be.

**Comment by ticup** [comment] 2021-05-03 13:34
Created a new question, error remains.
Response from request:
```
{"database_id":2,"started_at":"2021-05-03T15:30:45.037657+02:00","via":[{"status":"failed","class":"class clojure.lang.ExceptionInfo","error":"Error determining value for parameter","stacktrace":["--> driver.common.parameters.values$fn__78952$value_for_tag__78957$fn__78958.invoke(values.clj:323)","driver.common.parameters.values$fn__78952$value_for_tag__78957.invoke(values.clj:316)","driver.common.parameters.values$fn__78976$query__GT_params_map__78981$fn__78985$iter__78987__78991$fn__78992.invoke(values.clj:338)","driver.common.parameters.values$fn__78976$query__GT_params_map__78981$fn__78985.invoke(values.clj:337)","driver.common.parameters.values$fn__78976$query__GT_params_map__78981.invoke(values.clj:328)","driver.sql$fn__80857.invokeStatic(sql.clj:44)","driver.sql$fn__80857.invoke(sql.clj:40)","query_processor.middleware.parameters.native$expand_inner.invokeStatic(native.clj:39)","query_processor.middleware.parameters.native$expand_inner.invoke(native.clj:30)","query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:50)","query_processor.middleware.parameters$expand_one.invoke(parameters.clj:41)","query_processor.middleware.parameters$expand_all$replace_48286__48287.invoke(parameters.clj:59)","mbql.util.match.impl$replace_in_collection$iter__17982__17986$fn__17987.invoke(impl.cljc:44)","mbql.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:43)","mbql.util.match.impl$replace_in_collection.invoke(impl.cljc:38)","query_processor.middleware.parameters$expand_all$replace_48286__48287.invoke(parameters.clj:59)","query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:59)","query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)","query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:56)","query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)","query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:77)","query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:73)","query_processor.middleware.parameters$fn__48302$substitute_parameters_STAR___48307$fn__48308.invoke(parameters.clj:82)","query_processor.middleware.parameters$fn__48302$substitute_parameters_STAR___48307.invoke(parameters.clj:79)","query_processor.middleware.parameters$substitute_parameters$fn__48328.invoke(parameters.clj:111)","query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46258.invoke(resolve_referenced.clj:79)","query_processor.middleware.expand_macros$expand_macros$fn__46879.invoke(expand_macros.clj:155)","query_processor.middleware.add_timezone_info$add_timezone_info$fn__44803.invoke(add_timezone_info.clj:15)","query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49320.invoke(splice_params_in_response.clj:32)","query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48531$fn__48535.invoke(resolve_database_and_driver.clj:31)","driver$do_with_driver.invokeStatic(driver.clj:60)","driver$do_with_driver.invoke(driver.clj:56)","query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48531.invoke(resolve_database_and_driver.clj:25)","query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47119.invoke(fetch_source_query.clj:274)","query_processor.middleware.store$initialize_store$fn__49329$fn__49330.invoke(store.clj:11)","query_processor.store$do_with_store.invokeStatic(store.clj:44)","query_processor.store$do_with_store.invoke(store.clj:38)","query_processor.middleware.store$initialize_store$fn__49329.invoke(store.clj:10)","query_processor.middleware.validate$validate_query$fn__49374.invoke(validate.clj:10)","query_processor.middleware.normalize_query$normalize$fn__47255.invoke(normalize_query.clj:22)","query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44649.invoke(add_rows_truncated.clj:35)","query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49305.invoke(results_metadata.clj:147)","query_processor.middleware.constraints$add_default_userland_constraints$fn__46500.invoke(constraints.clj:42)","query_processor.middleware.process_userland_query$process_userland_query$fn__48417.invoke(process_userland_query.clj:135)","query_processor.middleware.catch_exceptions$catch_exceptions$fn__46440.invoke(catch_exceptions.clj:173)","query_processor.reducible$async_qp$qp_STAR___37978$thunk__37979.invoke(reducible.clj:103)","query_processor.reducible$async_qp$qp_STAR___37978.invoke(reducible.clj:109)","query_processor.reducible$sync_qp$qp_STAR___37987$fn__37990.invoke(reducible.clj:135)","query_processor.reducible$sync_qp$qp_STAR___37987.invoke(reducible.clj:134)","query_processor$process_userland_query.invokeStatic(query_processor.clj:239)","query_processor$process_userland_query.doInvoke(query_processor.clj:235)","query_processor$fn__49464$process_query_and_save_execution_BANG___49473$fn__49476.invoke(query_processor.clj:251)","query_processor$fn__49464$process_query_and_save_execution_BANG___49473.invoke(query_processor.clj:243)","query_processor$fn__49508$process_query_and_save_with_max_results_constraints_BANG___49517$fn__49520.invoke(query_processor.clj:263)","query_processor$fn__49508$process_query_and_save_with_max_results_constraints_BANG___49517.invoke(query_processor.clj:256)","api.dataset$run_query_async$fn__55721.invoke(dataset.clj:56)","query_processor.streaming$streaming_response_STAR_$fn__55700$fn__55701.invoke(streaming.clj:72)","query_processor.streaming$streaming_response_STAR_$fn__55700.invoke(streaming.clj:71)","async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)","async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)","async.streaming_response$do_f_async$fn__16071.invoke(streaming_response.clj:84)"],"error_type":"invalid-query","ex-data":{"tag":{"id":"6014cb92-5137-4898-32d6-219392a0f720","name":"created","display-name":"Created","type":"dimension","dimension":["field",2191,null],"widget-type":"date/range"},"type":"schema.core/error"}},{"status":"failed","class":"class clojure.lang.ExceptionInfo","error":"Error building query parameter map","stacktrace":["--> driver.common.parameters.values$fn__78976$query__GT_params_map__78981$fn__78985.invoke(values.clj:346)","driver.common.parameters.values$fn__78976$query__GT_params_map__78981.invoke(values.clj:328)","driver.sql$fn__80857.invokeStatic(sql.clj:44)","driver.sql$fn__80857.invoke(sql.clj:40)","query_processor.middleware.parameters.native$expand_inner.invokeStatic(native.clj:39)","query_processor.middleware.parameters.native$expand_inner.invoke(native.clj:30)","query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:50)","query_processor.middleware.parameters$expand_one.invoke(parameters.clj:41)","query_processor.middleware.parameters$expand_all$replace_48286__48287.invoke(parameters.clj:59)","mbql.util.match.impl$replace_in_collection$iter__17982__17986$fn__17987.invoke(impl.cljc:44)","mbql.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:43)","mbql.util.match.impl$replace_in_collection.invoke(impl.cljc:38)","query_processor.middleware.parameters$expand_all$replace_48286__48287.invoke(parameters.clj:59)","query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:59)","query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)","query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:56)","query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)","query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:77)","query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:73)","query_processor.middleware.parameters$fn__48302$substitute_parameters_STAR___48307$fn__48308.invoke(parameters.clj:82)","query_processor.middleware.parameters$fn__48302$substitute_parameters_STAR___48307.invoke(parameters.clj:79)","query_processor.middleware.parameters$substitute_parameters$fn__48328.invoke(parameters.clj:111)","query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46258.invoke(resolve_referenced.clj:79)","query_processor.middleware.expand_macros$expand_macros$fn__46879.invoke(expand_macros.clj:155)","query_processor.middleware.add_timezone_info$add_timezone_info$fn__44803.invoke(add_timezone_info.clj:15)","query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49320.invoke(splice_params_in_response.clj:32)","query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48531$fn__48535.invoke(resolve_database_and_driver.clj:31)","driver$do_with_driver.invokeStatic(driver.clj:60)","driver$do_with_driver.invoke(driver.clj:56)","query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48531.invoke(resolve_database_and_driver.clj:25)","query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47119.invoke(fetch_source_query.clj:274)","query_processor.middleware.store$initialize_store$fn__49329$fn__49330.invoke(store.clj:11)","query_processor.store$do_with_store.invokeStatic(store.clj:44)","query_processor.store$do_with_store.invoke(store.clj:38)","query_processor.middleware.store$initialize_store$fn__49329.invoke(store.clj:10)","query_processor.middleware.validate$validate_query$fn__49374.invoke(validate.clj:10)","query_processor.middleware.normalize_query$normalize$fn__47255.invoke(normalize_query.clj:22)","query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44649.invoke(add_rows_truncated.clj:35)","query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49305.invoke(results_metadata.clj:147)","query_processor.middleware.constraints$add_default_userland_constraints$fn__46500.invoke(constraints.clj:42)","query_processor.middleware.process_userland_query$process_userland_query$fn__48417.invoke(process_userland_query.clj:135)","query_processor.middleware.catch_exceptions$catch_exceptions$fn__46440.invoke(catch_exceptions.clj:173)","query_processor.reducible$async_qp$qp_STAR___37978$thunk__37979.invoke(reducible.clj:103)","query_processor.reducible$async_qp$qp_STAR___37978.invoke(reducible.clj:109)","query_processor.reducible$sync_qp$qp_STAR___37987$fn__37990.invoke(reducible.clj:135)","query_processor.reducible$sync_qp$qp_STAR___37987.invoke(reducible.clj:134)","query_processor$process_userland_query.invokeStatic(query_processor.clj:239)","query_processor$process_userland_query.doInvoke(query_processor.clj:235)","query_processor$fn__49464$process_query_and_save_execution_BANG___49473$fn__49476.invoke(query_processor.clj:251)","query_processor$fn__49464$process_query_and_save_execution_BANG___49473.invoke(query_processor.clj:243)","query_processor$fn__49508$process_query_and_save_with_max_results_constraints_BANG___49517$fn__49520.invoke(query_processor.clj:263)","query_processor$fn__49508$process_query_and_save_with_max_results_constraints_BANG___49517.invoke(query_processor.clj:256)","api.dataset$run_query_async$fn__55721.invoke(dataset.clj:56)","query_processor.streaming$streaming_response_STAR_$fn__55700$fn__55701.invoke(streaming.clj:72)","query_processor.streaming$streaming_response_STAR_$fn__55700.invoke(streaming.clj:71)","async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)","async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)","async.streaming_response$do_f_async$fn__16071.invoke(streaming_response.clj:84)"],"error_type":"invalid-query","ex-data":{"type":"schema.core/error","tags":{"created":{"id":"6014cb92-5137-4898-32d6-219392a0f720","name":"created","display-name":"Created","type":"dimension","dimension":["field",2191,null],"widget-type":"date/range"}},"params":[{"type":"date/range","value":"2021-05-13~2021-05-28","target":["dimension",["template-tag","created"]]}]}}],"error_type":"invalid-query","json_query":{"type":"native","native":{"query":"select count(*) from users where {{created}}","template-tags":{"created":{"id":"6014cb92-5137-4898-32d6-219392a0f720","name":"created","display-name":"Created","type":"dimension","dimension":["field",2191,null],"widget-type":"date/range","default":null}}},"database":2,"parameters":[{"type":"date/range","value":"2021-05-13~2021-05-28","target":["dimension",["template-tag","created"]]}],"middleware":{"js-int-to-string?":true,"add-default-userland-constraints?":true}},"status":"failed","class":"class clojure.lang.ExceptionInfo","stacktrace":["--> driver.common.parameters.values$fn__78852$parse_value_for_field_type__78857.invoke(values.clj:249)","driver.common.parameters.values$fn__78875$update_filter_for_field_type__78880$fn__78888.invoke(values.clj:271)","driver.common.parameters.values$fn__78875$update_filter_for_field_type__78880.invoke(values.clj:265)","driver.common.parameters.values$fn__78912$parse_value_for_type__78917$fn__78918.invoke(values.clj:311)","driver.common.parameters.values$fn__78912$parse_value_for_type__78917.invoke(values.clj:282)","driver.common.parameters.values$fn__78952$value_for_tag__78957$fn__78958.invoke(values.clj:321)","driver.common.parameters.values$fn__78952$value_for_tag__78957.invoke(values.clj:316)","driver.common.parameters.values$fn__78976$query__GT_params_map__78981$fn__78985$iter__78987__78991$fn__78992.invoke(values.clj:338)","driver.common.parameters.values$fn__78976$query__GT_params_map__78981$fn__78985.invoke(values.clj:337)","driver.common.parameters.values$fn__78976$query__GT_params_map__78981.invoke(values.clj:328)","driver.sql$fn__80857.invokeStatic(sql.clj:44)","driver.sql$fn__80857.invoke(sql.clj:40)","query_processor.middleware.parameters.native$expand_inner.invokeStatic(native.clj:39)","query_processor.middleware.parameters.native$expand_inner.invoke(native.clj:30)","query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:50)","query_processor.middleware.parameters$expand_one.invoke(parameters.clj:41)","query_processor.middleware.parameters$expand_all$replace_48286__48287.invoke(parameters.clj:59)","mbql.util.match.impl$replace_in_collection$iter__17982__17986$fn__17987.invoke(impl.cljc:44)","mbql.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:43)","mbql.util.match.impl$replace_in_collection.invoke(impl.cljc:38)","query_processor.middleware.parameters$expand_all$replace_48286__48287.invoke(parameters.clj:59)","query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:59)","query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)","query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:56)","query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)","query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:77)","query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:73)","query_processor.middleware.parameters$fn__48302$substitute_parameters_STAR___48307$fn__48308.invoke(parameters.clj:82)","query_processor.middleware.parameters$fn__48302$substitute_parameters_STAR___48307.invoke(parameters.clj:79)","query_processor.middleware.parameters$substitute_parameters$fn__48328.invoke(parameters.clj:111)","query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46258.invoke(resolve_referenced.clj:79)","query_processor.middleware.expand_macros$expand_macros$fn__46879.invoke(expand_macros.clj:155)","query_processor.middleware.add_timezone_info$add_timezone_info$fn__44803.invoke(add_timezone_info.clj:15)","query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49320.invoke(splice_params_in_response.clj:32)","query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48531$fn__48535.invoke(resolve_database_and_driver.clj:31)","driver$do_with_driver.invokeStatic(driver.clj:60)","driver$do_with_driver.invoke(driver.clj:56)","query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48531.invoke(resolve_database_and_driver.clj:25)","query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47119.invoke(fetch_source_query.clj:274)","query_processor.middleware.store$initialize_store$fn__49329$fn__49330.invoke(store.clj:11)","query_processor.store$do_with_store.invokeStatic(store.clj:44)","query_processor.store$do_with_store.invoke(store.clj:38)","query_processor.middleware.store$initialize_store$fn__49329.invoke(store.clj:10)","query_processor.middleware.validate$validate_query$fn__49374.invoke(validate.clj:10)","query_processor.middleware.normalize_query$normalize$fn__47255.invoke(normalize_query.clj:22)","query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44649.invoke(add_rows_truncated.clj:35)","query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49305.invoke(results_metadata.clj:147)","query_processor.middleware.constraints$add_default_userland_constraints$fn__46500.invoke(constraints.clj:42)","query_processor.middleware.process_userland_query$process_userland_query$fn__48417.invoke(process_userland_query.clj:135)","query_processor.middleware.catch_exceptions$catch_exceptions$fn__46440.invoke(catch_exceptions.clj:173)","query_processor.reducible$async_qp$qp_STAR___37978$thunk__37979.invoke(reducible.clj:103)","query_processor.reducible$async_qp$qp_STAR___37978.invoke(reducible.clj:109)","query_processor.reducible$sync_qp$qp_STAR___37987$fn__37990.invoke(reducible.clj:135)","query_processor.reducible$sync_qp$qp_STAR___37987.invoke(reducible.clj:134)","query_processor$process_userland_query.invokeStatic(query_processor.clj:239)","query_processor$process_userland_query.doInvoke(query_processor.clj:235)","query_processor$fn__49464$process_query_and_save_execution_BANG___49473$fn__49476.invoke(query_processor.clj:251)","query_processor$fn__49464$process_query_and_save_execution_BANG___49473.invoke(query_processor.clj:243)","query_processor$fn__49508$process_query_and_save_with_max_results_constraints_BANG___49517$fn__49520.invoke(query_processor.clj:263)","query_processor$fn__49508$process_query_and_save_with_max_results_constraints_BANG___49517.invoke(query_processor.clj:256)","api.dataset$run_query_async$fn__55721.invoke(dataset.clj:56)","query_processor.streaming$streaming_response_STAR_$fn__55700$fn__55701.invoke(streaming.clj:72)","query_processor.streaming$streaming_response_STAR_$fn__55700.invoke(streaming.clj:71)","async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)","async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)","async.streaming_response$do_f_async$fn__16071.invoke(streaming_response.clj:84)"],"context":"ad-hoc","error":"Input to parse-value-for-field-type does not match schema: \n\n\t \u001B[0;33m  [(named (not (\"Valid field type\" nil)) effective-type) nil] \u001B[0m \n\n","row_count":0,"running_time":0,"ex-data":{"type":"schema.core/error","value":[null,"2021-05-13~2021-05-28"],"error":["schema.utils.NamedError@4680acc9",null]},"data":{"rows":[],"cols":[]}}
```

Record in `report_card` for this question:
```
id	created_at	updated_at	name	description	display	dataset_query	visualization_settings	creator_id	database_id	table_id	query_type	archived	collection_id	public_uuid	made_public_by_id	enable_embedding	embedding_params	cache_ttl	result_metadata	collection_position
5088	2021-05-03 15:33:12	2021-05-03 15:33:12	Test case		table	"{""type"":""native"",""native"":{""query"":""select count(*) from users where {{created}}"",""template-tags"":{""created"":{""id"":""6014cb92-5137-4898-32d6-219392a0f720"",""name"":""created"",""display-name"":""Created"",""type"":""dimension"",""dimension"":[""field"",2191,null],""widget-type"":""date/range""}}},""database"":2}"	{}	45	2		native	0				0			"[{""name"":""count(*)"",""display_name"":""count(*)"",""base_type"":""type/BigInteger"",""field_ref"":[""field"",""count(*)"",{""base-type"":""type/BigInteger""}],""semantic_type"":null,""fingerprint"":{""global"":{""distinct-count"":1,""nil%"":0.0},""type"":{""type/Number"":{""min"":300691.0,""q1"":300691.0,""q3"":300691.0,""max"":300691.0,""sd"":null,""avg"":300691.0}}}}]"	
```

Or as insert:

```
INSERT INTO `report_card` (`id`, `created_at`, `updated_at`, `name`, `description`, `display`, `dataset_query`, `visualization_settings`, `creator_id`, `database_id`, `table_id`, `query_type`, `archived`, `collection_id`, `public_uuid`, `made_public_by_id`, `enable_embedding`, `embedding_params`, `cache_ttl`, `result_metadata`, `collection_position`) VALUES
(5088, '2021-05-03 15:33:12', '2021-05-03 15:33:12', 'Test case', NULL, 'table', '{\"type\":\"native\",\"native\":{\"query\":\"select count(*) from users where {{created}}\",\"template-tags\":{\"created\":{\"id\":\"6014cb92-5137-4898-32d6-219392a0f720\",\"name\":\"created\",\"display-name\":\"Created\",\"type\":\"dimension\",\"dimension\":[\"field\",2191,null],\"widget-type\":\"date/range\"}}},\"database\":2}', '{}', 45, 2, NULL, 'native', b'0', NULL, NULL, NULL, b'0', NULL, NULL, '[{\"name\":\"count(*)\",\"display_name\":\"count(*)\",\"base_type\":\"type/BigInteger\",\"field_ref\":[\"field\",\"count(*)\",{\"base-type\":\"type/BigInteger\"}],\"semantic_type\":null,\"fingerprint\":{\"global\":{\"distinct-count\":1,\"nil%\":0.0},\"type\":{\"type/Number\":{\"min\":300691.0,\"q1\":300691.0,\"q3\":300691.0,\"max\":300691.0,\"sd\":null,\"avg\":300691.0}}}}]', NULL);
```

**Comment by flamber** [comment] 2021-05-03 14:18
@ticup Okay, so I can see it failing, but I'm not able to reproduce in any way. And I still don't understand why you're not seeing a stacktrace in your log.
Can you provide the output of `/api/field/2191` which should tell a lot of details about orders.created ?

**Comment by ticup** [comment] 2021-05-03 14:20
@flamber 
```
{"description":null,"database_type":"TIMESTAMP","semantic_type":"type/CreationTimestamp","table_id":43,"coercion_strategy":null,"table":{"description":null,"entity_type":"entity/UserTable","schema":null,"db":{"description":null,"features":["basic-aggregations","standard-deviation-aggregations","expression-aggregations","foreign-keys","right-join","left-join","native-parameters","nested-queries","expressions","set-timezone","binning","inner-join","advanced-math-expressions"],"cache_field_values_schedule":"0 0 22 * * ? *","timezone":"+02:00","auto_run_queries":true,"metadata_sync_schedule":"0 1 * * * ? *","name":"production","caveats":null,"is_full_sync":true,"updated_at":"2021-04-27T16:01:00","details":{"host":"*****","port":3306,"dbname":"****","user":"****","password":"****","tunnel-port":22,"let-user-control-scheduling":false},"is_sample":false,"id":2,"is_on_demand":false,"options":null,"engine":"mysql","refingerprint":null,"created_at":"2017-04-08T09:43:16","points_of_interest":null},"show_in_getting_started":false,"name":"users","caveats":null,"updated_at":"2021-02-20T01:44:06","entity_name":null,"active":true,"id":43,"db_id":2,"visibility_type":null,"field_order":"database","display_name":"Users","created_at":"2017-04-08T09:43:19","points_of_interest":null},"name":"created","fingerprint_version":4,"has_field_values":"none","settings":null,"caveats":null,"fk_target_field_id":null,"dimensions":[],"updated_at":"2021-02-18T17:01:12","custom_position":0,"effective_type":null,"active":true,"parent_id":null,"id":2191,"last_analyzed":"2019-09-09T15:19:37","position":0,"visibility_type":"normal","preview_display":true,"display_name":"Created","database_position":28,"name_field":null,"fingerprint":{"global":{"distinct-count":8242,"nil%":0.0},"type":{"type/DateTime":{"earliest":"2017-03-26T23:01:01.000Z","latest":"2019-07-03T04:16:51.000Z"}}},"created_at":"2019-07-31T18:24:17","base_type":"type/DateTimeWithLocalTZ","points_of_interest":null}
```

**Comment by flamber** [comment] 2021-05-03 14:45
Okay, I have no idea how to reproduce this. Please let me know if you can reproduce this on a new instance consistently.
The only thing that seems out of place is the fingerprint version, which is 4, while the latest should be 5.

**Comment by dpsutton** [comment] 2021-05-03 14:59
The error is that the effective_type passed in to `parse-value-for-field-type` is null. You can see that that function looks for the [effective_type of a field](https://github.com/metabase/metabase/blob/master/src/metabase/driver/common/parameters/values.clj#L265). But from what you've posted, the field only has a base_type: `{""base-type"":""type/BigInteger""}`.

This change is from a refactor that aimed to simplify some of the coercion logic. Seems like we need to fall back to the base type here.

I've made a PR that I believe addresses this here: https://github.com/metabase/metabase/pull/15905

**Comment by flamber** [comment] 2021-05-03 15:06
@dpsutton I think you're right about `effective_type`, which is null from the /api/field, while `base_type="type/DateTimeWithLocalTZ"`
The `{""base-type"":""type/BigInteger""}` is from the `result_metadata`, which is correct.

**Comment by dpsutton** [comment] 2021-05-06 21:10
Closing due to PR #15905

**Closed by dpsutton** 2021-05-06 21:10 UTC
Labels: .Regression, .Unable to Reproduce, Administration/Metadata & Sync, Priority:P2, Querying/Native, Querying/Parameters & Variables, Type:Bug

**Comment by ticup** [comment] 2021-05-12 09:55
Thanks @dpsutton  and @flamber ! 👍
