### ISSUE TITLE
Color range styles in conditional formatting not working properly 

### ISSUE THREAD

**Issue by okaeiz** [metabase/metabase#34017] opened 2023-09-21 11:08 UTC
### Describe the bug

When I set the formatting style on color range, I cannot change the color of the range. It freezes on its default style (which is made up of red, white and green colors). It is frustrating and I think the issue is the result of upgrading Metabase to its latest version.

![cap](https://github.com/metabase/metabase/assets/100111649/074fdeb0-dba9-4db0-a1da-24fdbe5b5ca6)

### To Reproduce

1. Go to 'Conditional formatting in a question settings panel'
2. Click on 'Color range'
3. Try changing the color of the range
4. It cannot be changed! It freezes.

### Expected behavior

I should be able to change the color of the range.

### Logs

There are no logs about the error; but the division id is class="css-1eiksu7 eg5ebpm3", if it helps.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.15.0-83-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.1 (Debian 15.1-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-07",
      "tag": "v0.47.1",
      "branch": "release-x.47.x",
      "hash": "bd278b9"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

### Severity

Currenlty, the users cannot have a good grasp of the data because the formatting of the scores is not correct.

**Comment by nemanjaglumac** [comment] 2023-09-22 07:59
I spun up the official `v0.47.1` JAR and cannot reproduce this behavior.
![image](https://github.com/metabase/metabase/assets/31325167/dd32dd3c-b5d8-4dbb-959b-12b7b355f69f)

Can you try to reproduce it using the Sample Database, or provide the query for the question you were using when this happened.

> I think the issue is the result of upgrading Metabase to its latest version

Did you recently upgrade? From which version?
Did this work before and is not working anymore or have you tried it for the first time in this version?

**Comment by okaeiz** [comment] 2023-09-22 12:07
I also used the sample database. The issue persists.
I recently upgraded Metabase and before that, everything was fine.
When I click on the color range, I can see other styling options as well but I cannot choose them. Nothing happens when I click on them.

**Comment by okaeiz** [comment] 2023-09-25 06:17
Any updates on this? The issue is too annoying.

**Comment by nemanjaglumac** [comment] 2023-09-25 10:11
@okaeiz please do not use comments to ask for updates on an issue. We historically removed messages like that as they are considered a spam.

> I also used the sample database. The issue persists.

Please provide the reproduction steps using the Sample Database. I cannot reproduce the issue so there must be something specific about your repro case. The more info you provide, the easier will it be for us to figure out what's going on and to help.

**Comment by cbalusek** [comment] 2023-09-25 13:00
@okaeiz  You mentioned you recently upgraded Metabase - what version were you on and what version are you on now?

**Comment by okaeiz** [comment] 2023-09-26 04:57
> @okaeiz You mentioned you recently upgraded Metabase - what version were you on and what version are you on now?

I was on v0.46.8 and I upgraded to v0.47.1

**Comment by okaeiz** [comment] 2023-09-26 05:07
> @okaeiz please do not use comments to ask for updates on an issue. We historically removed messages like that as they are considered a spam.
> 
> > I also used the sample database. The issue persists.
> 
> Please provide the reproduction steps using the Sample Database. I cannot reproduce the issue so there must be something specific about your repro case. The more info you provide, the easier will it be for us to figure out what's going on and to help.

I provided this video. Take a look at the steps.

https://github.com/metabase/metabase/assets/100111649/e3f1cb49-ca1f-42db-bf3a-88fca21e01b4

As you can see, I can only change the color of the 2nd range style and I could not choose the first or third one. It seems buggy.

**Comment by okaeiz** [comment] 2023-09-26 05:35
I also checked it on v0.47.2.
Not working.

**Comment by nemanjaglumac** [comment] 2023-09-26 10:00
@okaeiz thank you for the video. This helps a lot!

**Comment by nemanjaglumac** [comment] 2023-09-26 22:52
Upon further discussion with @EmmadUsmani, it turned out that this issue is a duplicate of https://github.com/metabase/metabase/issues/33229, which was already fixed in https://github.com/metabase/metabase/pull/33989.

The fix will be available in `47.3`

**Closed by nemanjaglumac** 2023-09-26 22:52 UTC
Labels: Type:Bug, Priority:P3, Visualization/Tables, .Regression, .Team/PixelPolice :police_officer:

**Comment by okaeiz** [comment] 2023-09-28 05:56
Thanks.
I am looking forward to upgrading to 47.3

**Comment by okaeiz** [comment] 2023-10-05 14:26
It is fixed ✅
