### ISSUE TITLE
Graph type mismatch between pulse and web

### ISSUE THREAD

**Issue by BenjaminDavison** [metabase/metabase#2294] opened 2016-04-02 22:58 UTC
If I save a question as a bar graph and then try and recall it in metabot I get a sparkline instead.
-  I'm running Metabase Docker
-  My database is big query
-  My Metabase version is 0.17

**Comment by mazameli** [comment] 2016-04-04 16:45
This is actually the intended behavior, @BenjaminDavison. For context, Metabot uses the same rules as Pulses do to try and convert your saved questions into the best format for email and Slack, which often involves condensing things down visually. For Pulses, since they're sent on a regular schedule, we anticipated that most users would be regularly receiving updates on queries that have a time dimension, which we think are generally better represented as a line than as bars; spark lines also work better than bars when you don't have a lot of vertical space.

However, we might want to revisit this thinking, since with Metabot you're not only getting daily/weekly time-sensitive queries sent to you, but you could be trying to reference any saved question/chart in Metabase, and you might not want that chart to get mutated.

/cc @kdoh

**Comment by BenjaminDavison** [comment] 2016-04-06 10:07
Hi @mazameli 

Thanks for the answer, yup that's exactly it. We also found that the sparkline sometimes "smooths" out important information.

Our use case is that we have an hour process that we want to monitor, and the easiest way is by using a bar graph -- but recalling it with metabot brings up a sparkline that smooths out the outage.

For example:

![metabsebar](https://cloud.githubusercontent.com/assets/105371/14313117/b3cf962a-fbe7-11e5-8a60-5d1300072466.png)

But when recalled with metabot

![metabasesparklines](https://cloud.githubusercontent.com/assets/105371/14313124/bff0df18-fbe7-11e5-8b50-8c7ca4441226.png)

Regards,

Ben

**Comment by agilliland** [comment] 2016-04-06 15:04
@BenjaminDavison do you mind sharing the data behind your first chart above?  the main thing I'm interested in is whether or not there is a value for that gap in your graph, or if the data itself is non-continuous, meaning that it goes from 1pm to 3pm without ever providing a value for 2pm.

**Comment by tlrobinson** [comment] 2016-04-06 15:37
@agilliland it's almost certainly non continuous. We have issue #896 open, which I think would cover this (assuming it were implemented in the backend)

**Comment by BenjaminDavison** [comment] 2016-04-06 16:09
@agilliland There is no data in that time hour bucket (we load data hourly)

Thanks,

Ben

**Comment by agilliland** [comment] 2016-04-07 15:20
Yeah, I think the primary fix here is via #896

**Comment by mattbillenstein** [comment] 2017-09-28 21:58
I think metabot changing the chart type is very counter-intuitive -- and in my experience it doesn't really do what you want.  I think I'd actually want a decent size image of the user-selected chart type so that I can full-screen it in the client if I really want to dig in.

**Comment by flamber** [comment] 2020-05-24 18:02
Closing in favor of #5493, which has a lot more upvotes

**Closed by flamber** 2020-05-24 18:02 UTC
Labels: .Correctness, Reporting/MetaBot, Type:UX
