### ISSUE TITLE
Increase maximum number of series that can be displayed by a line/area/bar chart

### ISSUE THREAD

**Issue by inkrement** [metabase/metabase#3656] opened 2016-10-24 14:19 UTC
Would be great if it's possible to create a line chart with multiple lines, where two lines are generated by the same column and a third column decides on the color of the line.
## Example

Dataset:

> Type,t,value
> A,0,12
> B,0,12
> A,1,20
> B,1,23

Expected result:

Generate a different line for each type (x-axsis=t, y-axsis=value)

**Comment by tlrobinson** [comment] 2016-10-24 16:41
@inkrement We should support this, but since `t` and `value` are both numbers in your case we assume they are both metrics to be graphed as separate lines. If you go into the chart settings (gear icon on `/q` or `/card` page) you can remove `t` from the Y-axis and add click `Add a series breakout...` to select it there.

<img width="654" alt="screenshot 2016-10-24 09 40 26" src="https://cloud.githubusercontent.com/assets/18193/19654612/e8842eba-99cd-11e6-9520-cc5c7bbb5cb0.png">

You may also want to disable `Use a split y-axis when necessary` in the AXES settings.

(I just noticed a minor bug where we're not displaying the `0` as a title).

**Comment by inkrement** [comment] 2016-10-24 18:51
Ok thanks. Seems to work, but only with limitations: 

> This chart type doesn't support more than 20 series

Is it possible to set a higher limit?

**Comment by tlrobinson** [comment] 2016-10-24 19:06
@inkrement Currently that number is hard-coded here https://github.com/metabase/metabase/blob/8a113d8b5b83a7e172b25db5b28dfe522f4a9bc5/frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js#L636

We needed some limit in case the user accidentally picked a high cardinality column as the breakout (our charting library would likely hang the UI if you tried to display, say, 1000 lines), and we felt 20 was more than could be reasonably interpreted, but we're willing to revisit that.

Do you mind providing some more info about your use case? What would you like to increase that number to?

**Comment by inkrement** [comment] 2016-10-25 07:46
We want to visualize the trend of some social media metrics (number of likes, comments) for human brands (e.g. music artists). I selected quite similar/related brands, so the curves should be similar too. We would like to try it and if this is too much/noisy we would make smaller groups (maybe one for each genre/branch). 

I understand it, but as software engineer I would not hardcode magic numbers in the source code. Would be great if there is a default value (e.g. 20) and each user can change it in the settings.

**Comment by Poggen** [comment] 2016-12-12 13:49
+1 for this. I regularly run queries with more than 10-30 series, which is problematic to say the least, since anything above 5 series creates issues due to the color limitation on bar/area/scatter charts.

One solution (not for @inkrement's use case, though) could be grouping these series into an "other" group and allowing the user to set a minimum percentage, kind of how it works with pie charts?

**Comment by abtinf** [comment] 2017-02-20 10:14
+1 for this. I run into this issue with stacked bar charts, where it can be very useful and clear to display a couple hundred series on a single chart. I've previously rendered this data using D3 directly and it was very fast.

**Comment by m-collins** [comment] 2017-05-09 08:17
@abtinf agree wrt stacked bar chart use case

**Comment by dricket** [comment] 2017-07-26 15:09
I hit the magic 20 on stacked area chart of expense category visualization vs time.  50 would probably do it for me, I'd change to 100 to have some buffer.  

The issue is many of the my 50 are normally zero or small, so seeing top 20 is normally the bulk of the area; but sometimes a small category increases, and it's nice to be able to mouseover and see what it is.  Also the sum of the smaller categories after the top 20 can still add to a significant quantity and I'd want to know the true sum of all of them, without having to munge data to produce an "other" category.

**Comment by adjenks** [comment] 2017-10-12 19:51
Oh, this was a problem for me but I guess the change just isn't reflected yet in the java jar release...
200 is reasonable I suppose.

**Comment by jaGarcia** [comment] 2018-05-17 16:51
Can this please be added.  I'm one-by-one losing visualizations as my number of series are increasing.

**Comment by Shlomitalbi** [comment] 2018-07-04 16:29
Is this going to be deployed anytime soon? That's becoming a real blocker

**Comment by mangalprasad** [comment] 2018-07-22 21:33
Agree with @Shlomitalbi +200 ! 💯💯
Can't wait for this to be done. Too much work to get around this right now.

**Comment by jaGarcia** [comment] 2018-12-12 15:59
@tlrobinson  Can we please get some progress on this.. it's a crippling and oddly low series number..

**Comment by MarkRx** [comment] 2018-12-31 18:52
What if (1) the max was increased to N and (2) if there are more than N series only the first N would be used? Chances are if you have more than N series the data wouldn't be legible either.

I would rather see my first (according to resultset order) N series then see this ugly error:
![image](https://user-images.githubusercontent.com/17504314/50566050-3febed00-0d03-11e9-9d83-1af9a64654b7.png)

**Comment by mazameli** [comment] 2019-07-17 23:53
Here's my latest thinking on this: treat it like row series limits. In the changes we're making to the query builder, there's a label/button in the bottom-right of the screen that shows how many rows are being displayed and which lets you change that limit to a custom value or to show-max. We could use this same pattern for series, where we could continue to have 20 be the default max, but allow setting a custom limit or showing all series. 

![default-series-limit](https://user-images.githubusercontent.com/2223916/61418468-79570500-a8af-11e9-84c4-59b21d17e4ea.png)

![change limit](https://user-images.githubusercontent.com/2223916/61419266-567a2000-a8b2-11e9-94b0-e7d1d25692e8.png)


One problem that will be exacerbated by allowing more series is that our horizontal legends are pretty useless once they exceed around 10 series or so. In these mocks, I'm showing the idea that if we see that series legends are starting to overflow, switch them to vertical. These mocks depict 20 legend items; if there are more than that, we could deal with additional legend items by having text link at the bottom like `and 17 more` which would open a scrollable popover to show the rest (I _think_ that's better than having that column be scrollable).

![overflow](https://user-images.githubusercontent.com/2223916/61418458-6e9c7000-a8af-11e9-9835-4d36b5572117.png)

![overflow-popover](https://user-images.githubusercontent.com/2223916/61418453-6c3a1600-a8af-11e9-91d4-6e9e9677981d.png)

**Comment by maxzheng** [comment] 2019-10-10 23:55
@mazameli That looks great. We are getting hit by this now when using line and bar charts. It would be great to have the limit be configurable (with a default of 20) and a warning like you have. When do you think your changes will be ready to go in?

**Comment by contradironee** [comment] 2019-10-31 08:24
Another suggestion would be to show the top 20 labels (ordered by as if there were no x-axis) by default and aggregate the remainder as Other, like in the pie chart?

I come across this problem quite often, but working around with creating a custom SQL question atm.

**Comment by antoine-lizee** [comment] 2019-11-05 00:07
- I agree there is some limit to the number of series that can be _nicely_ displayed in a graph, but when doing exploration, having an arbitrary high number can be useful.
- In some types of graphs, you're _expected_ to have high number of series, as the UI relies on underlining the big performers. Example: cohort graphs (with area). Example below.

Given the easiness of the fix I would do it asap and **put this number to 100 now, and think about a smart solution later**. It's about unblocking your users that have been waiting for a fix for more than  two years now!

![image](https://user-images.githubusercontent.com/2957716/68168199-5046a700-ff68-11e9-915c-d070a7c65583.png)

**Comment by bubonic** [comment] 2020-02-26 03:48
Don't forget about scatter plots. I recently uploaded some data from my app and it broke my beautiful scatter plot of averages for users. Can't wait for the milestone, looking forward to it. Keep up the great work gents!

**Comment by bubonic** [comment] 2020-02-26 04:08
Never mind, I see the commit from a few hours ago that applies to scatter plots. Thanks!!!

**Comment by flamber** [comment] 2020-02-26 10:24
:wave: This will be part of 0.34.3 (fixed by PR #11981). You should see a release today :rocket:

**Closed** 2020-02-26 10:25 UTC
Labels: Priority:P2, Type:Completeness, Visualization/Charts

**Comment by jaGarcia** [comment] 2020-02-28 19:39
thank you! not trying to be a mouse w/ a cookie, but being able to configure this above 100 would be sweet
