### ISSUE TITLE
Carry redirect query param when going from Google auth screen to email/password screen 

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#16605] opened 2021-06-15 20:49 UTC
Assumption: SSO is enabled.

#### Preparation

1. Copy the url of a question, dashboard or collection to your clipboard.

#### Enable SSO authentication

1. Go to Admin
2. On left menu, click `Authentication`
3. In section titled `Sign in with Google`, click `Configure`
4. Add any string to `Client ID` input
5. Click `Save Changes`

#### Sign out and check sign in

1. Sign Out of Metabase
2. Try to go to the url you have on your clipboard
3. You should now see the Google authentication button
4. Note that the url has a query parameter: `?redirect=……`
5. Click on `Sign in with email`
6. Note that url has lost the `redirect` query param.
7. Now if you log in, you will no longer land in the url you wanted initially.

**Comment by flamber** [comment] 2021-06-16 09:01
Duplicate of #16216

**Closed by flamber** 2021-06-16 09:01 UTC
Labels: .Needs Triage
