### ISSUE TITLE
Blocked: you are not allowed to run queries against Database

### ISSUE THREAD

**Issue by sid-habu** [metabase/metabase#24415] opened 2022-07-28 19:28 UTC
**Describe the bug**
Unable to view questions if the logged-in user is part of a group which doesn't have access to `Native Query Editing` permission. The logged in user's group has `Unrestricted Data Access` on the database.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

1. Create a group which has unrestricted data access and native query editing to a database
2. Log in as user who is in the above group and create questions with SQL or Query Builder
3. Add above questions to a collection. Also, add a dashboard with above question in it.
4. Create another group which has `No Self Service` access to the database and has `View` access to the above collection
5. Log in as user who is in the above group and view the dashboard or the question in the collection

Outcome `Blocked: you are not allowed to run queries against Database 166.` 

**Expected behavior**

**Screenshots**
![Group Permissions](https://user-images.githubusercontent.com/92833044/181621192-9306e828-14c6-4bcb-adf4-96cd69116675.png)
![Database Permissions](https://user-images.githubusercontent.com/92833044/181621197-4e2608ec-b82f-4d43-94ac-9633240416c1.png)
![Error](https://user-images.githubusercontent.com/92833044/181621199-be003741-00c7-4def-95d9-3ffa132a1135.png)
![Collection_Question](https://user-images.githubusercontent.com/92833044/181621204-c87e0828-9fad-4255-a77d-a44f3a6835fc.png)

**Severity**
This is blocking us from showing collections with dashboards and questions to read-only users who should not have access to native query editing

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.4.196-108.356.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "snowflake",
      "athena",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.18"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-06-27",
      "tag": "v1.43.4",
      "branch": "release-x.43.x",
      "hash": "61cc28e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2022-07-28 19:33
Hi @sid-habu 
Please use the support email, when using the Pro/Enterprise edition.
Duplicate of #21695

**Closed by flamber** 2022-07-28 19:33 UTC

**Comment by sid-habu** [comment] 2022-07-28 19:51
Issue resolved by removing Block permission on the All Users group

Found this flowchart very useful from @camsaul - Thank you!

![Metabase_Permissions](https://user-images.githubusercontent.com/92833044/181625102-9fa7123a-7d9f-4319-87ea-d28041e212dd.png)
