### ISSUE TITLE
y-axis label for incorrect when there is only a single value in one of the dimensions

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#15586] opened 2021-04-13 02:04 UTC
**Describe the bug**
When the dataset only includes one value (repeated) in one of the dimensions used in the chart x-axis, the y-axis label is changed to be that dimension value.

**To Reproduce**
1. New Question > Sample Dataset > Products
2. Average Price, grouped by Title, Category 
3. Line chart, X-axis Title, Category.
4. Note the y axis label is "Average of Price" as expected
5. Filter to a single value of Category "Doohickey"
6. y-axis label is changed incorrectly to "Doohickey"

**Expected behavior**
The y-axis label should remain "Average of Price", describe what is being measured.

**Screenshots**
Label should be "Average of Price" by default
![image](https://user-images.githubusercontent.com/4504437/114484987-40ec8280-9c5f-11eb-8f06-fb5fb96f4ed4.png)

Removing the category filter the y-axis lable becomes correct:
![image](https://user-images.githubusercontent.com/4504437/114485163-90cb4980-9c5f-11eb-88f4-1121ec18fd47.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_161-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_161",
    "java.vm.name": "Java HotSpot(TM) Client VM",
    "java.vm.version": "25.161-b12",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlserver",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.38.1",
      "date": "2021-03-03",
      "branch": "release-x.38.x",
      "hash": "79ef63a"
    },
    "settings": {
      "report-timezone": "Pacific/Auckland"
    }
  }
}
```

**Severity**
Frustration and leads to having to explain what's going on to users. It's not doing the correct thing here.

**Comment by flamber** [comment] 2021-04-13 08:35
Duplicate of #12782

**Closed by flamber** 2021-04-13 08:35 UTC
Labels: .Needs Triage, Type:Bug
