### ISSUE TITLE
Unable to create mongodb native query with mongo functions or simple arithmetics

### ISSUE THREAD

**Issue by PolarAir** [metabase/metabase#19768] opened 2022-01-19 09:48 UTC
Hi,

We are using Metabase v0.41.5 with MongoDB 4.4.6 on Ubuntu 20.04.3

For a certain question we have to implement a custom aggregation query on the MongoDB, where it required using native functions  and arithmetics, such as 'new Date()' and ' + - * /'. 
We are able to get the results through these queries with native mongo command line.

The exact query is mentioned below.

`
[
    {"$match": {"siteName": {"$ne": null}}},
    {"$match": {"updatedUtc": {"$gte": new Date().getTime() / 1000 - 3600 * 24 * 2}}},
    {"$group": {_id: {"siteName": "$siteName"}, count: {$sum: 1}}}
]
`
![image](https://user-images.githubusercontent.com/11264186/150105924-1ca72575-b5bd-4e5a-93a3-dacb7baa3bcf.png)

The results in native mongo command line
![image](https://user-images.githubusercontent.com/11264186/150105799-69636dd3-de95-4cc5-b22a-88608b008bfb.png)

**Comment by flamber** [comment] 2022-01-26 11:57
Duplicate of #4083 - see https://github.com/metabase/metabase/issues/4083#issuecomment-649466421 for workaround

**Closed by flamber** 2022-01-26 11:57 UTC
Labels: Type:Bug, .Needs Triage
