### ISSUE TITLE
deselect all 

### ISSUE THREAD

**Issue by Idreesqbal** [metabase/metabase#19056] opened 2021-11-22 10:53 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**How important is this feature to you?**
Note: the more honest and specific you are here the more we will take you seriously. 

**Additional context**

**Comment by Idreesqbal** [comment] 2021-11-22 10:54
If you are working with a table with tons of columns it is a nightmare deselecting columns...currently, there is only 'Select all' but no deselect all... it will awesome to have the 'Deselect all' feature added.

**Comment by flamber** [comment] 2021-11-22 10:55
Duplicate of #10460

**Closed by flamber** 2021-11-22 10:55 UTC
Labels: Type:New Feature, .Needs Triage
