### ISSUE TITLE
Pie chart not working for email

### ISSUE THREAD

**Issue by vaibhav12321** [metabase/metabase#16248] opened 2021-05-26 15:47 UTC
**Describe the bug**
I want to send Pie chart as email but its sending as vertical bars. Please check screenshot

**Logs**
NA

**To Reproduce**
1. Create a visualize question (as Pie chart
2. Create Pulse by selecting that question
3. Schedule it for email.
4. The email and preview always show the same chart (attached screenshot).

**Expected behavior**
It should send graph in described format.

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/13692091/119690976-ce7adf00-be67-11eb-9ccf-adfcfe23af60.png)

**Comment by flamber** [comment] 2021-05-26 16:02
Duplicate of #5493

**Closed by flamber** 2021-05-26 16:02 UTC
Labels: .Needs Triage, Type:Bug
