### ISSUE TITLE
[Data Permissions] Saved questions showing in the list of databases

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#22071] opened 2022-04-26 11:26 UTC
**Describe the bug**
"Saved Questions" are showing in the "Databases" under data permissions `/admin/permissions/data/database`

**Logs**
N/A

**To Reproduce**
1. Have some saved questions (NOTE: it seems that the **joined** questions trigger this)
2. Go to `/admin/permissions/data/database`
3. Notice that apart from the "Sample Database" you can edit permissions for "Saved Questions"

Updated steps:
4. Click on "Saved Questions" - the url is now `/admin/permissions/data/database/-1337`
5. Individual questions will now be offered in the left sidebar as tables
6. Click on any of the saved questions (for example "Orders")
7. The UI updates and it now shows "Permissions for Sample Database", but the url is completely busted and is showing `/admin/permissions/data/database/1/schema/Everything%20else/table/card__1`

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/31325167/165293963-4e44c06c-ed7b-4879-bde1-5b9d6e7b31fd.png">
8. Change permissions for any user group and try to save
9. You will see this error

<img width="620" alt="image" src="https://user-images.githubusercontent.com/31325167/165293455-44f404eb-15b7-4f39-b892-084574dae504.png">

**Expected behavior**
"Saved Questions" shouldn't ever appear in data permissions.

**Screenshots**
<img width="260" alt="image" src="https://user-images.githubusercontent.com/31325167/165289186-27b6a9a5-2268-4f34-b62d-88b064a20ed2.png">

Individual questions are shown as "Tables"
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/31325167/165290116-eb0f8968-e834-4611-b52a-81632e002ba0.png">

**Information about your Metabase Installation:**
local dev, `master`, 87a1de84b2d0bc607566596c089611d13db1e37e, H2, Sample database

**Severity**
P1

**Additional context**
Tested 42.4 and 41.6 and was still able to reproduce it. It was probably like this ever since we updated the permissions UI cc @alxnddr

**Comment by flamber** [comment] 2022-04-26 11:37
Seems like a duplicate of #18331, which was fixed in #21840

**Comment by nemanjaglumac** [comment] 2022-04-26 11:40
@alxnddr I was able to reproduce it immediately using:
1. docker images for 41.6 and 42.4 (OSS versions)
2. local dev environment on the latest master (EE version)

There's really not too much additional context.
1. Create Orders join Products and save
2. Go to `/admin/permissions/data/database`
3. See "Saved Questions"

Not sure how you're not able to reproduce it and what exact steps did you take?

**Comment by alxnddr** [comment] 2022-04-26 11:46
Not sure what is different on my machine but I could not see it. Will try to figure out
<img width="376" alt="Screenshot 2022-04-26 at 15 41 33" src="https://user-images.githubusercontent.com/14301985/165292850-afe2ea6e-c564-490e-8422-e8fac20dd307.png">

**Comment by nemanjaglumac** [comment] 2022-04-26 11:47
I'll create a repro so you don't have to try to reproduce it locally.

**Comment by alxnddr** [comment] 2022-04-26 11:48
Oh, I see. I copied to url to the permissions page but it must be opened in the same tab without page reload

**Comment by nemanjaglumac** [comment] 2022-04-26 11:55
This is where `-1337` part is coming from:
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/lib/saved-questions/saved-questions.js#L4

**Closed** 2022-04-26 22:05 UTC
Labels: Type:Bug, Priority:P3, Administration/Permissions, .Frontend
