### ISSUE TITLE
Edit model metadata: selecting a column highlights the wrong column

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#22989] opened 2022-05-26 18:43 UTC
**Describe the bug**
I click on a column and another column is highlighted

https://www.loom.com/share/c1e03a9f551b4cee97b26c00780bff74

**Severity**
It is misleading, but doesn't impact funcionality

**Comment by flamber** [comment] 2022-05-27 08:08
Duplicate of #22521

**Closed by flamber** 2022-05-27 08:08 UTC
Labels: Type:Bug, .Needs Triage, Querying/Models
