### ISSUE TITLE
Propagating SQL parameters to referenced saved queries (and models)

### ISSUE THREAD

**Issue by Fraznist** [metabase/metabase#30802] opened 2023-05-16 15:06 UTC
**Is your feature request related to a problem? Please describe.**
When used as a source by another query, saved queries that are parametrized always use their default parameter values. This happens even if the unsaved query tries to overwrite the parameter with a parameter of its own that matches the param name.

This also means dashboard level filters cannot modify saved queries that are nested within other queries.

**Describe the solution you'd like**
Parameters are a clear interface to change question behavior in expected ways. If a parametrized query is allowed to be saved and used as a source, the SQL parameter values of the saved query should be editable by the query that references it.

I'd like the parameter set of the unsaved query to be applied to any saved queries referenced. It feels like a simple and intuitive solution. 

**Describe alternatives you've considered**
* Automatically adding the parameter list of nested saved questions to the host question, maybe with a prefix of the saved question id. Then propagating that.

**How important is this feature to you?**
It is important, as it will require a significant workflow change for all of our user base, explanation below:

We are looking to migrate from Redash, and the biggest blocker so far is that Metabase doesn't allow multiple visualizations per question. That feature is hard to implement and is nowhere near completion i think. Instead we intend to use a saved question (or model) to centralize business logic, and reference it in a noop question for every visualization we had in redash. 

We cannot migrate queries that are both parametrized and have multiple visualizations this way, since saved questions do not accept outside parameters. The alternative is to duplicate questions and business logic for every visualization, which requires repetitive labor for updates to business logic. 

For now our scenario is very specific, as we haven't adopted Metabase completely. But this feature would enable much more than our specific scenario, and really empower question reusability.

**Comment by kosiakk** [comment] 2023-06-01 16:17
I believe it's a duplicate of a very old one: #2763 

> dashboard level filters cannot modify saved queries

Exactly [that](https://github.com/metabase/metabase/issues/2763#issuecomment-1546423147). For some reason Metabase team [considers it a security feature](https://github.com/metabase/metabase/issues/2763#issuecomment-232734464), and it basically works as designed.
We are trying to collect votes under a central (earliest) issue to change this behavior.

**Comment by paoliniluis** [comment] 2023-06-25 17:56
Yup, closing as it’s a dupe

**Closed by paoliniluis** 2023-06-25 17:56 UTC
Labels: Type:New Feature, .Needs Triage
