### ISSUE TITLE
Unexpected timestamp with Druid groupBy queries

### ISSUE THREAD

**Issue by psalaberria002** [metabase/metabase#3823] opened 2016-11-29 19:56 UTC
Great tool guys!

I am having some issues with the timestamps. I expected all Druid queries to return UTC timestamps. However, this is not happening when running groupBy queries in the UI.

Timeseries queries:
- Timestamps are correct, between 20th and 25th, including both dates.

<img width="950" alt="captura de pantalla 2016-11-29 a las 20 38 33" src="https://cloud.githubusercontent.com/assets/2410564/20726058/5344c9f4-b674-11e6-90af-229f95855947.png">

GroupBy queries:
- Timestamps from 19th to 24th. What's going on here?
<img width="1056" alt="captura de pantalla 2016-11-29 a las 20 39 00" src="https://cloud.githubusercontent.com/assets/2410564/20726063/57831818-b674-11e6-999f-fe1104b13288.png">

Native groupBy queries:
- Timestamps are correct, between 20th and 25th, including both dates.
<img width="795" alt="captura de pantalla 2016-11-29 a las 20 39 50" src="https://cloud.githubusercontent.com/assets/2410564/20726072/5c6f52d8-b674-11e6-8094-a2c7bf5eb32d.png">

- Your browser and the version: Chrome 54.0.2840.98 (64-bit)
- Your operating system: OSX 10.11.6
- Your databases: Druid 0.9
- Metabase version: 0.20.3
- Metabase hosting environment: Mesos
- Metabase internal database: Postgres

**Comment by moumny** [comment] 2016-11-29 20:33
Whats your configured timezone(see Admin Panel)?

**Comment by psalaberria002** [comment] 2016-12-01 18:23
It's set to UTC.

**Comment by moumny** [comment] 2016-12-01 23:25
I can reproduce this. 
The driver returns the right query but the formatting of the date in the table is wrong. (probably displayed in the wrong timezone)
Only happens with goupBy day (grouping by hour works fine)

**Comment by camsaul** [comment] 2016-12-13 03:06
@moumny did you say you think this is an issue with how the dates are shown in the table?

**Comment by moumny** [comment] 2016-12-15 13:19
Correct !
The values in the returned request is correct.
Somehow the formatting in the "day" aggregation does some wierd things. 
Theres a few open issue related to this part of the code :)

**Comment by flamber** [comment] 2021-11-07 13:15
I have not been able to reproduce this on 0.41.1, but a lot has changed over the years, so closing this.
This looks like it was a frontend issue specific to the old pivoted table, which seems like it wasn't applying timezone.

**Closed by flamber** 2021-11-07 13:15 UTC
Labels: .Need More Info, Database/Druid, Misc/Timezones
