### ISSUE TITLE
User, without access to data, can not see allowed dashboard on the main page.

### ISSUE THREAD

**Issue by nanotexnik** [metabase/metabase#10418] opened 2019-07-26 12:05 UTC
If a user has permissions for a table and a collection it can see the collection on the main page, but if  the user has only the collection permission than the user cannot see the collection on the main page. At the same time if the user uses direct link on the dashboard, it's great (the user can see dashboard).

**Comment by flamber** [comment] 2019-07-26 15:16
Hi @nanotexnik 
I cannot reproduce your issue on 0.32.9.
Can you provide all the information requested, when creating a new issue? Like version, errors, etc.
Please check your permissions and provide a reproducible step-by-step guide.

**Comment by sinnus** [comment] 2019-07-27 06:22
The same issue on 0.32.9

**Comment by flamber** [comment] 2019-07-27 06:35
@sinnus 
Do you see any error in the log or browser console?
Can you please provide a step-by-step guide to reproduce the issue?

**Comment by sinnus** [comment] 2019-07-27 07:02
browser log

```
vendor.bundle.js?0d1325582067a4b57db2:1 Uncaught Invariant Violation: Minified React error #143; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=143 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at e.exports (https://localhost/app/dist/vendor.bundle.js?0d1325582067a4b57db2:1:697009)
    at Object.e.exports [as only] (https://localhost/app/dist/vendor.bundle.js?0d1325582067a4b57db2:1:1896171)
    at t.value (https://localhost/app/dist/app-main.bundle.js?0d1325582067a4b57db2:5:117040)
    at u._renderValidatedComponentWithoutOwnerOrContext (https://localhost/app/dist/vendor.bundle.js?0d1325582067a4b57db2:1:1968833)
    at u._renderValidatedComponent (https://localhost/app/dist/vendor.bundle.js?0d1325582067a4b57db2:1:1968940)
    at u.performInitialMount (https://localhost/app/dist/vendor.bundle.js?0d1325582067a4b57db2:1:1964822)
    at u.mountComponent (https://localhost/app/dist/vendor.bundle.js?0d1325582067a4b57db2:1:1963868)
    at Object.mountComponent (https://localhost/app/dist/vendor.bundle.js?0d1325582067a4b57db2:1:652653)
    at u.performInitialMount (https://localhost/app/dist/vendor.bundle.js?0d1325582067a4b57db2:1:1964983)
    at u.mountComponent (https://localhost/app/dist/vendor.bundle.js?0d1325582067a4b57db2:1:1963868)

vendor.bundle.js?0d1325582067a4b57db2:1 Uncaught (in promise) TypeError: Cannot read property '_currentElement' of null
    at u._updateRenderedComponent (vendor.bundle.js?0d1325582067a4b57db2:1)
    at u._performComponentUpdate (vendor.bundle.js?0d1325582067a4b57db2:1)
    at updateComponent (vendor.bundle.js?0d1325582067a4b57db2:1)
    at u.receiveComponent (vendor.bundle.js?0d1325582067a4b57db2:1)
    at Object.receiveComponent (vendor.bundle.js?0d1325582067a4b57db2:1)
    at u._updateRenderedComponent (vendor.bundle.js?0d1325582067a4b57db2:1)
    at u._performComponentUpdate (vendor.bundle.js?0d1325582067a4b57db2:1)
    at updateComponent (vendor.bundle.js?0d1325582067a4b57db2:1)
    at u.receiveComponent (vendor.bundle.js?0d1325582067a4b57db2:1)
    at Object.receiveComponent (vendor.bundle.js?0d1325582067a4b57db2:1)

Uncaught TypeError: Cannot read property 'replaceChild' of null
    at Function.h.replaceChildWithTree (vendor.bundle.js?0d1325582067a4b57db2:1)
    at Object.dangerouslyReplaceNodeWithMarkup [as replaceNodeWithMarkup] (vendor.bundle.js?0d1325582067a4b57db2:1)
    at u._replaceNodeWithMarkup (vendor.bundle.js?0d1325582067a4b57db2:1)
    at u._updateRenderedComponent (vendor.bundle.js?0d1325582067a4b57db2:1)
    at u._performComponentUpdate (vendor.bundle.js?0d1325582067a4b57db2:1)
    at updateComponent (vendor.bundle.js?0d1325582067a4b57db2:1)
    at u.receiveComponent (vendor.bundle.js?0d1325582067a4b57db2:1)
    at Object.receiveComponent (vendor.bundle.js?0d1325582067a4b57db2:1)
    at u._updateRenderedComponent (vendor.bundle.js?0d1325582067a4b57db2:1)
    at u._performComponentUpdate (vendor.bundle.js?0d1325582067a4b57db2:1)
```

**Comment by flamber** [comment] 2019-07-27 07:05
@sinnus Okay, that's issue #10191, which is already fixed and will be included in next release.
There's a work-around: https://github.com/metabase/metabase/issues/10191#issuecomment-505240542

**Comment by sinnus** [comment] 2019-07-27 07:15
The work-around doesn't work

**Comment by flamber** [comment] 2019-07-27 07:17
@sinnus Hmmm....okay. Well then I need a step-by-step to reproduce the issue.

**Comment by flamber** [comment] 2019-07-27 07:25
Maybe you're seeing #10212, which is fixed by the same code, but the work-around is to give access to at least a single table.

**Comment by sinnus** [comment] 2019-07-27 08:03
#10212 fix my issue

**Comment by mbvictoria** [comment] 2019-07-30 22:37
Closing - fixed.

**Closed by mbvictoria** 2019-07-30 22:37 UTC
