### ISSUE TITLE
Grouping by Week # of Year Using Query Builder - Week 53 transformed to 1st

### ISSUE THREAD

**Issue by chucksense** [metabase/metabase#10122] opened 2019-06-10 17:19 UTC
- Your browser and the version: Chrome 75.0.3770.80 (Official Build) (64-bit) but issue happens in Safari too
- Your operating system: macOS 10.14.5
- Your databases: MySQL
- Metabase version:  0.32.8
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

Using Query Builder, I'm pulling a year long data set, grouping by week number of the year.

When using Query Builder, Week 53 (really Week 52, but per #8969 there is a +1 added to the query and the year starts on Week 2) is transformed in the visualizations into "1st."  When I write the query manually and run it, it remains week 53.

Examples:
Here is a group by Week (instead of Week of Year) to show the corresponding dates and counts:

![Question · Metabase 2019-06-10 13-16-23](https://user-images.githubusercontent.com/199588/59213047-f50fb480-8b81-11e9-894d-750d16911746.jpg)

Here is a custom query (where I literally took the query Metabase produced, but ran it in SQL mode instead of using Query Builder) that shows week 53 correctly:

![Question · Metabase 2019-06-10 13-17-36](https://user-images.githubusercontent.com/199588/59213131-24bebc80-8b82-11e9-8f97-e0c7de8ec143.jpg)

And here is when using Query Builder (again, same query, just using Builder instead of Native SQL) where the 53rd week is changed to be 1st instead:

![Question · Metabase 2019-06-10 13-18-35](https://user-images.githubusercontent.com/199588/59213179-461fa880-8b82-11e9-9581-364d60fdcf7b.jpg)

**Comment by flamber** [comment] 2019-06-10 18:17
Hi @chucksense 
I think it might be better to rename #8969, so it isn't specific to Line Chart, since it's the same issue.
Seems to specific to MySQL/MariaDB: https://github.com/metabase/metabase/issues/8969#issuecomment-459146738

**Comment by chucksense** [comment] 2019-06-10 18:31
@flamber, to be clear, it's not quite the same issue.  Even if the query didn't have the +1, there are legitimate cases of a 53rd week in many years and in those cases, having the visualization UI roll the 53rd week into the 1st week is still not appropriate.  So that other issue is about the +1 in the query which shouldn't occur while this is about the transformation of 53rd to 1st in query-builder driven visualizations.

**Comment by flamber** [comment] 2019-06-10 18:44
@chucksense 
I understand the case of 53rd week, but when I test on H2 Sample Data returns week 1st thru 52nd, which is correct, but when I test on MySQL Sample Data with the same query, then it returns week 2nd thru 1st, which is incorrect.
![image](https://user-images.githubusercontent.com/1447303/59218228-f7bbdb00-8b7c-11e9-9312-65a5ab9165a6.png)
Every time I group by "Week of Year" with MySQL, then it always return +1
I don't have any data for 2015 and 2020, which are the closest years with 53 weeks.

**Comment by chucksense** [comment] 2019-06-11 13:36
Drop down to native sql query that query builder generates.  You will see it's not MySQL that's returning the data in this way.  I think Metabase is doing this transformation.

**Comment by flamber** [comment] 2019-06-11 20:11
@chucksense Yes, like I've already pointed out in https://github.com/metabase/metabase/issues/8969#issuecomment-459146738

**Comment by chucksense** [comment] 2019-06-13 14:07
#8969 is referring to the fact that Metabase is adding a +1 in the query for some reason.  You are correct that that shouldn't happen, but I believe that's separate from this.

This issue is referring to the fact that _when_ the MySQL result comes back as week number `53` (which of course occurs much more frequently than it should due to the +1 issue, but even if that is fixed, will legitimately occur every few years), Metabase is for some reason transforming the MySQL result of `53` to `1st` in the visualization when applying the labels.

E.g., MySQL returns:

Week|Value
---|---
2| 
3| 
4| 
...| 
52| 
53| 

But the visualization transforms those into:

Week|Value
---|---
2nd| 
3rd|
4th|
...|
52nd|
1st|

**Comment by flamber** [comment] 2019-06-13 21:33
@chucksense 

Okay, now I think I see what you mean.

I generated test data for 2020 and ran with `BETWEEN '2020-01-01' AND '2020-12-31'`.
The response data is `2` thru `54`, which is caused by the `+1` in #8969 - hardcoded Sunday is #1779.
But when visualized via QB, then it's displayed as `2nd` thru `52nd`, `1st`, `2nd`.

From what I can understand, this is caused by the following code, because it only receives a number, it it tries to correlate that to the current date (as starting point) and locale of the browser.
https://momentjscom.readthedocs.io/en/latest/moment/02-get-set/10-week/
https://github.com/metabase/metabase/blob/8bf2b13652694944b1d3fb9f54226dc184f6f438/frontend/src/metabase/lib/formatting/date.js#L32

**Comment by chucksense** [comment] 2019-06-14 12:44
Got it!  Looks like they have an issue related to this behavior already: https://github.com/moment/moment/issues/5132

**Comment by ranquild** [comment] 2022-04-18 13:53
@flamber I couldn't reproduce this issue. Tried the following query and there was `53rd` week as expected. And it also works for SQL questions. I'll close this issue then. Please re-open if can still reproduce it somehow.

<img width="888" alt="Screenshot 2022-04-18 at 16 51 22" src="https://user-images.githubusercontent.com/8542534/163818043-2b2efda0-edc5-4483-b0e5-8bc2e2816843.png">
<img width="886" alt="Screenshot 2022-04-18 at 16 51 34" src="https://user-images.githubusercontent.com/8542534/163818052-9468d71b-ea4b-4688-9571-f9563865c09b.png">
<img width="1728" alt="Screenshot 2022-04-18 at 16 52 39" src="https://user-images.githubusercontent.com/8542534/163818137-b3021dbb-5cf5-45bc-b291-01269a492a81.png">

**Closed by ranquild** 2022-04-18 13:53 UTC
Labels: Type:Bug, Priority:P2, .Correctness, Misc/Timezones, .Frontend
