### ISSUE TITLE
add filter report

### ISSUE THREAD

**Issue by hieule1997** [metabase/metabase#12006] opened 2020-02-28 04:20 UTC
**Describe the bug**
some err when i add filter time. i click chose column on block in dashboard. I can't drop block

**Screenshots**
![image](https://user-images.githubusercontent.com/41559257/75510161-9692ab00-5a1c-11ea-8142-1aaac5293fa9.png)

**Comment by flamber** [comment] 2020-02-28 09:36
Duplicate of #11927

**Closed by flamber** 2020-02-28 09:36 UTC
Labels: .Duplicate
