### ISSUE TITLE
Language picker in user config hides chosen language on page load if language includes substring between parentheses

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#16654] opened 2021-06-17 17:12 UTC
## To reproduce

1. http://localhost:3000/user/edit_current
2. Choose any language that has any text between parentheses, such as `Portuguese (Brazil)`
3. Click button to update
4. Wait for page reload

Dropdown will render empty.
For other languages with nothing between parentheses, the language shows.

### Language with text between parentheses — for example `Portuguese (Brazil)`.

<img src="https://user-images.githubusercontent.com/380816/122443147-aa498400-cf75-11eb-9cad-5e18f7258bdc.png" width=300 />

### Language with no text between parentheses — for example `Italian`.

<img src="https://user-images.githubusercontent.com/380816/122443260-c9481600-cf75-11eb-940a-29d50cfe1c74.png" width=300 />

**Comment by flamber** [comment] 2021-06-17 17:25
Almost a duplicate of #15657

**Comment by gusaiani** [comment] 2021-06-17 18:25
> Almost a duplicate of #15657

I have to read widely in our issues list to avoid creating duplicates.

**Closed** 2021-09-15 02:22 UTC
Labels: Type:UX, Priority:P3, Customization/i18n, Administration/Settings
