### ISSUE TITLE
Option for CSV export for dashboard table

### ISSUE THREAD

**Issue by miguelmota** [metabase/metabase#6288] opened 2017-10-27 23:33 UTC
Currently you can export to CSV when you edit a question (which is awesome), but there is no option for exporting when the question is in a dashboard. Is this possible or are there any plans for this in the near future?

Thanks

**Comment by mazameli** [comment] 2017-10-28 16:46
Closing as duplicate of https://github.com/metabase/metabase/issues/3847

**Closed by mazameli** 2017-10-28 16:46 UTC
Labels: Duplicate
