### ISSUE TITLE
Pass values from dashboard's filters to other dashboard's filters, the slice type is changed to string type

### ISSUE THREAD

**Issue by Yamiyo** [metabase/metabase#17831] opened 2021-09-10 10:04 UTC
**Describe the bug**
If I want to pass values from dashboard's filters to other dashboard's filters, the slice type is changed to string type.

**Expected behavior**
If I want to pass values from dashboard's filters to other dashboard's filters, the slice type is changed to string type, But it should be slice type.

**Screenshots**
![image](https://user-images.githubusercontent.com/11374934/132824399-85226d3a-6a3d-4c7d-940e-072874ee3830.png)

The `member_login` values is slice type, example like `"value":["demobot1","demobot2","demobot3","demobot4"]` .
params:
```json
{"parameters":[{"type":"date/all-options","value":"past7days~","target":["dimension",["template-tag","payout_time_range"]]},{"type":"category","value":["demobot1","demobot2","demobot3","demobot4"],"target":["dimension",["template-tag","member_login"]]}]}
```

But if I clicked question, pass values to other dashboard's filter.
![image](https://user-images.githubusercontent.com/11374934/132826269-c47a6455-c735-42c0-a2c7-a1aeb0650f50.png)

The `member_login` values type will change to string type, example like `"value":"demobot1,demobot2,demobot3,demobot4"` .
params:
```json
{"parameters":[{"type":"date/all-options","value":"past7days~","target":["dimension",["template-tag","time_range"]]},{"type":"category","value":"demobot1,demobot2,demobot3,demobot4","target":["dimension",["template-tag","member_login"]]}]}
```

But it should be slice type, like `"value":["demobot1","demobot2","demobot3","demobot4"]` before pass values.

**Information about your Metabase Installation:**
- Browser: Brave version 1.28.106 Chromium: 92.0.4515.159 (x86_64)
- Device: MacOS 11.5.2
- Databases: TiDB
- Metabase version: 0.40.4
- Metabase hosting environment: Docker
- Metabase internal database: H2

Maybe it means I can't ues link to related other questions or dashboards.

**Comment by flamber** [comment] 2021-09-10 10:16
Duplicate of #17160

**Closed by flamber** 2021-09-10 10:16 UTC
Labels: Type:Bug, .Needs Triage
