### ISSUE TITLE
charts customization

### ISSUE THREAD

**Issue by CzechJiri** [metabase/metabase#2596] opened 2016-05-12 21:17 UTC
- The existing charts are "too intelligent" and make assumptions about data. I would like to be specific and pick what column is used for what axis and what series, for example I noticed the charts change when my dataset is growing (X axis flipped to Y axis)

- There is very limited color options, at bare minimum please add grey

- area charts should have an option stack vs non-stack

- there should be an option to add dual Y axis (left and right side)

**Comment by MrMauricioLeite** [comment] 2016-05-17 14:31
I completelly agree with @CzechJiri in that. There is no problem with metabase sugesting a visualization with X and Y axis, but I want to change the sugestion to my preference and would like metabase to remember that.

Maybe a button for advanced editing of the visualization where we can set a chart to stack vs not-stack and change axis.

**Comment by marketingnerds** [comment] 2016-05-23 14:12
Sorry to mention a competitor but this is the best platform that I've used with respect to customizing visualizations:

http://www.cyfe.com/sql-dashboard

... it allows modification of chart type, line/marker type, axes and labels by parsing extra info or tokens from the query. Maybe some inspiration to be found there.

**Comment by camsaul** [comment] 2016-07-26 22:38
Duplicate of #612 / #1445?

@tlrobinson @kdoh is this something that will be covered by #2931 (chart settings)

**Comment by tlrobinson** [comment] 2016-08-13 00:33
Your points # 1 and 3 have been resolved by the chart settings added in 0.19.

I've opened separate issues for 2 (#3185) and 4 (#3186) so I'm going to close this one.

Please comment those or open additional issues for specific chart settings.

**Closed by tlrobinson** 2016-08-13 00:33 UTC
Labels: Visualization/Chart Settings
