### ISSUE TITLE
Direct links to questions fail when user has limited permissions

### ISSUE THREAD

**Issue by stefanproell** [metabase/metabase#6537] opened 2017-12-06 08:15 UTC
When I write a new question and add it to a collection, then a user with limited access can not open the particular question via its direct link, although it is added to a collection where the user has access to. Opening the very same question by using the GUI and navigating via the collection the question is contained in works.

Here is an example:
A1 ... Administrator
U1 ... User with read access
C1 ... collection where U1 has read access
Q1 ... a question inside C1
L1 ... a URL (link) to Q1 (e.g.  metabase.example.org/question/Q1)

1) A1 creates a new collection called C1
2) A1 sets permissions to allow user U1 to view collection C1
3) A1 creates a new question Q1 and adds it to C1
4) A1 sends link L1 to U1 via email / chat
5) U1 cannot open Q1 directly via pasting it into the browser
6) U1 can open Q1 by navigating to C1 and clicking the link there

![metabase](https://user-images.githubusercontent.com/5196286/33651367-e3525d48-da65-11e7-8fbc-8f2993bc42e8.png)

**Comment by camsaul** [comment] 2017-12-19 23:39
@metabase/core-developers I'm not able to repro this. Can someone else try and see if you can repro it? @mazameli @salsakran ? 

@stefanproell what version of Metabase are you using?

**Comment by mazameli** [comment] 2017-12-20 00:53
No, couldn't reproduce this. I tried this where "U1" had no data access permissions at all, but did have view permissions for a collection. My "A1" user created a new question and saved it in that collection, and in a separate incognito tab I logged in with U1 and pasted the URL for the question in, and it displayed fine. I also tried clicking on a link to that question from within Slack and having it open it up in a browser session where U1 was logged out, then I logged in and still the question loaded up fine.

**Comment by camsaul** [comment] 2017-12-20 21:54
Closing as unable to reproduce. I suspect this was inadvertently fixed recently at some point.

@stefanproell if you're still running into this issue on the latest version of Metabase (0.27.2 at the time of this writing) please let us know.

**Closed by camsaul** 2017-12-20 21:54 UTC
Labels: Bug, Permissions, Priority/P2, Saved Questions, Unable to Reproduce
