### ISSUE TITLE
Use saved questions as Datasource with BigQuery DB

### ISSUE THREAD

**Issue by vbronsky** [metabase/metabase#7118] opened 2018-03-14 09:02 UTC
Hello!

Is there any news about possibility to use saved question as datasources with BigQuery DB? 

It is very usefull thing because we can't join our data for example: A => B => C with Query Builder. (it's not problem for me to use SQL query but it's hard for dummy users)

Thanks!

**Comment by jornh** [comment] 2018-03-14 17:24
Sounds like a duplicate of https://github.com/metabase/metabase/issues/5808

**Comment by salsakran** [comment] 2018-03-31 01:24
dupe

**Closed by salsakran** 2018-03-31 01:24 UTC
