### ISSUE TITLE
Bug in "Replace missing values with" for line visualizations

### ISSUE THREAD

**Issue by vebjorre** [metabase/metabase#27548] opened 2023-01-06 14:22 UTC
**Describe the bug**
Sometimes when not using 'linear interpolated' some non-null values are set to zero or "(empty)". 

**To Reproduce**
1. Make a question aggregated per day and some category, e.g. as in screenshot
![Skjermbilde 2023-01-06 kl  14 55 08](https://user-images.githubusercontent.com/55921651/211026267-274ec3ca-70a0-4a29-a7ba-2230a2a3247e.png)
2. Choose line visualization.
3. Go to settings and change "Replace missing values with" to zero (nothing is also buggy).
4. Observe that the sum changes for most days. It seems like some of the groups (for some product_ids) are set to zero for every day instead of just days with no value.

**Expected behavior**
Days with no value set to zero. None of the existing sums should change. Missing values do not normally add to a sum.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "nb-NO",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.17+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.17",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.17+8",
    "os.name": "Linux",
    "os.version": "5.10.147+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-12-07",
      "tag": "v1.45.1",
      "branch": "release-x.45.x",
      "hash": "019d31c"
    },
    "settings": {
      "report-timezone": "Europe/Oslo"
    }
  }
}
```

**Severity**
The default setting "linear interpolated" gives the correct values, but is misleading when there are many missing values. 

**Additional context**
For one of my questions with similar structure to the example, but with a series breakout and bigquery database, all lines are entirely set to zero when choosing 'zero' on each line's style settings. I wasn't able to reproduce on the sample database though. 
I believe v1.45 broke this as it worked perfectly a couple of months ago, and I just noticed the bug.

**Comment by flamber** [comment] 2023-01-06 14:23
Duplicate of #27063

**Closed by flamber** 2023-01-06 14:23 UTC
Labels: Type:Bug, .Needs Triage
