### ISSUE TITLE
Centering pin map around issues not working

### ISSUE THREAD

**Issue by vinceve** [metabase/metabase#38700] opened 2024-02-13 09:16 UTC
### Describe the bug

We have several maps on an embedded page where we display pins. It seems that the first map will always be centered and zoomed appropriately around the pins. The next maps underneath will not do that, they will focus on an area where there aren't any pins and will not change zoom levels. Note that I didn't draw a filter box or pinned the map on a specific location.

This is an example of a map I am seeing. Note that you do not see any pins on the map:
<img width="1083" alt="Screenshot 2024-02-13 at 09 06 55" src="https://github.com/metabase/metabase/assets/875642/92f0b3f8-0cd8-44e5-b058-5957c88d02f7">

If I zoom out and scroll to the correct spot, I get to see this:

<img width="1091" alt="Screenshot 2024-02-13 at 09 07 07" src="https://github.com/metabase/metabase/assets/875642/b0086a2d-019e-4829-88a2-e8ead8e605cb">

Note that I changed the filters and that you need to scroll to see the second map. I don't know if that could explain why it doesn't focus the map (because it was not loaded yet, something in the javascript).

### To Reproduce

1. Create a dashboard with several maps
2. Look at the second map, change your filters, see a static view

### Expected behavior

The maps should focus all pins within its bounds and zoom to the correct level

### Logs

DEPRECATED: metabase/redux/metadata addParamValues
g @ metadata.js:18
metadata.js:18 DEPRECATED: metabase/redux/metadata addFields
g @ metadata.js:18
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696
Dimension.ts:696 Unknown MBQL Field clause null
parseMBQLOrWarn @ Dimension.ts:696

### Information about your Metabase installation

```JSON
- latest chrome

{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.10.198-187.748.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-01-05",
      "tag": "v1.48.2",
      "hash": "e66c075"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

annoying / giving wrong information to users

**Comment by JesseSDevaney** [comment] 2024-07-01 17:37
Hey @vinceve!

I tried working on this issue, but I could not reproduce it locally.

I tested adding different pin maps to a dashboard, setting it up so some of the maps have to be scrolled down to, embedding the dashboard, and altering the location filter multiple times. 

In the end, I could not get a single map to display with broken centering and zoom levels.

---
Would you be able to provide some more information about your reproduction specifically in order to help diagnose and fix this issue?
1. Is it still occurring for you?
2. Is it occurring on the in-app dashboard as well? Or, is this only occurring on the embedded version of the dashboard?
   - Along the same lines, can you reproduce this in the question view/query builder itself? Or is this only a dashboard related thing?
3. What are the exact steps you are taking that cause this issue to occur?

**Comment by cdeweyx** [comment] 2024-08-06 21:03
I'm unable to reproduce this as well. Closing this, at least until we have more information on this issue.

**Closed by cdeweyx** 2024-08-06 21:03 UTC
Labels: Type:Bug, Priority:P2, .Unable to Reproduce, .Frontend, Visualization/Maps, .Team/DashViz
