### ISSUE TITLE
Data model sync not working

### ISSUE THREAD

**Issue by dfx413** [metabase/metabase#13803] opened 2020-11-16 10:42 UTC
version: 145b575 docker
db: MSSQL

**Expected behaviour**
1. I add new view, remove table
2. I go to "Databases", select my DB, hit "Sync schema"
4. I wait for a while
3. I go to "Data model", select my DB, hard-refresh (CTRL+F5) and I see the new view and I do not see the removed table

**Actual behaviour**
The new view is not there, the removed table is still there.
When I try to change the table (remove column) and hit sync again, the changes are still not present.
There are no exceptions shown in the log. 
The "analyze" action that was triggered by the button press took 977ms and returned "null".

**Comment by flamber** [comment] 2020-11-16 11:20
Hi @dfx413 
I cannot reproduce. Can you provide more details, and with a reproducible sample SQL?

**Comment by dfx413** [comment] 2020-11-16 11:39
@flamber 
Hi,
to give you some update:
the hourly DB sync captured the change so now it is OK.
But hitting the button to force the sync apparently did not work as expected.
I don't really know how to help debugging it. SQL samples (`drop table dbo.my_table`, `create view dbo.my_view as select column from table`) probably won't be helpful since the scheduled sync worked.

**Comment by flamber** [comment] 2020-11-16 11:41
Okay, in the future, please provide logs - even when there are no errors - so we can see which processes are running. Closing.

**Closed by flamber** 2020-11-16 11:41 UTC
Labels: .Needs Triage, Type:Bug
