### ISSUE TITLE
Dashboards refresh automatically even when auto refresh is off in iOS devices

### ISSUE THREAD

**Issue by ariamn86** [metabase/metabase#22446] opened 2022-05-05 08:35 UTC
In the latest release (docker image) 0.43.0, dashboards refresh automatically. It occurs in about 10 seconds. Auto-refresh is off, but it still happens. It only occurs in IOS devices, with no difference between Safari or Chrome. This problem is not with Android devices.

When auto-refresh is off, the dashboards should not be refreshed

- The Metabase version is v0.43.0 (Built on 2022-05-02) and is installed from docker file (metabase/metabase:latest).
- There is no difference between Chrome and Safari (Chrome 99 and Safari ...)
- It is tested in these operating systems: IOS 15.4.1, IOS 14.4
- Metabase internal database: Postgres

It is blocking our usage of Metabase entirely because we can only see the first one or two charts on a page.

**Comment by flamber** [comment] 2022-05-05 08:37
Duplicate of #22172

**Closed by flamber** 2022-05-05 08:37 UTC
Labels: Type:Bug, .Needs Triage
