### ISSUE TITLE
Smart Numbers: chose the unit of the lag displayed

### ISSUE THREAD

**Issue by antoine-lizee** [metabase/metabase#11200] opened 2019-10-23 11:11 UTC
Linked to:
- #9510, but I don't understand really the proposal or if the problem is the same
- #8919, but I don't understand really the proposal or if it has been implemented yet

**Is your feature request related to a problem? Please describe.**
When using a smart number, the unit of the lag is inferred, not sure how. This is sometimes wrong or inappropriate

**Describe the solution you'd like**
I would like to be able to override the unit of the lag displayed by specifying a setting of the visualization.

**Describe alternatives you've considered**
Improving the automatic detection. Here I always specify the date, so it could be inferred that it's 28days and not 1 month. Yet, I don't think this solution is satisfactory because (i) inference is hard, you might create other problems (ii) in the end, this is display and should be overridable.

**How important is this feature to you?**

We use 28days for the standard interval of comparison across the company. All our smart numbers say "last month", which is inaccurate and confusing (we sometimes use months too).

![image](https://user-images.githubusercontent.com/2957716/67387551-67b08800-f597-11e9-9927-72f20228fc62.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2019-10-23 11:59
Hi @antoine-lizee I'm fairly sure it's a duplicate of #9510, but let's ask @sbelak since he's developing some of the magic behind it.

**Comment by sbelak** [comment] 2019-10-23 12:46
Not really. This is more about what we term "unit". Basically how smart numbers work is they infer the unit (day, month, week, ...) and then use lag = 1. #9510 is about allowing lag > 1. This is about essentially non-standard units.

**Comment by kanobi** [comment] 2021-09-28 11:40
Hi, is there any plan to implement this feature in the next few major updates?

We're also using non-standard units for the date comparison and it doesn't look good on the dashboards with the static "last week" label.

Thanks

**Closed** 2024-02-13 22:53 UTC
Labels: Priority:P2, Type:New Feature, Visualization/Chart Settings, Querying/X-rays, Visualization/Scalars
