### ISSUE TITLE
sql variable date type  too simple. Very inconvenient operation

### ISSUE THREAD

**Issue by 8debug** [metabase/metabase#15417] opened 2021-03-31 11:47 UTC
**Describe the bug**
sql variable date type  too simple.
1. You cannot change the date by specifying the year and month
2. Cannot specify hours, minutes and seconds

**Logs**

**To Reproduce**
1. Write SQL statement and create variables "start_date" and "end_date"
2. Set "start_date" and "end_date" to Date type respectively
3. Operate the "start_date" and "end_date" filters through the generated UI widget
4. Can’t quickly select a specific month and year, Unable to quickly select specific hours, minutes and seconds.
5. Date widget font is not available in other languages

**Expected behavior**
Can quickly select a specific month and year, quickly select specific hours, minutes and seconds.
### [demo](https://www.jquery-az.com/boots/demo.php?ex=20.0_1)
![image](https://user-images.githubusercontent.com/3394927/113138917-02b39400-9259-11eb-9545-47af348e5770.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/3394927/113139361-98e7ba00-9259-11eb-8932-3e863337e883.png)

**Information about your Metabase Installation:**
- Chrome 88.0.4324.104
- Windows 10 Pro
- MySQL 5.7.26
- Metabase version: v0.38.2
- Metabase hosting environment: Windows Server 2016 Datacenter
- Metabase internal database: H2

**Comment by flamber** [comment] 2021-03-31 12:00
Duplicate of #4585 / #7418

**Closed by flamber** 2021-03-31 12:00 UTC
Labels: .Needs Triage, Type:Bug

**Comment by flamber** [comment] 2021-03-31 14:12
@8debug Go and upvote issues by clicking :+1: on the first post - there are 2000+ other issues, and do not have a timeline.
