### ISSUE TITLE
Permission for collection is not working well when dashboard has a card which made of multi questions

### ISSUE THREAD

**Issue by nakazavva** [metabase/metabase#5266] opened 2017-06-05 08:07 UTC
- Metabase version: 0.24.2

Usually dashboard composed of private collection is only visible for people who have a right permission, but when dashboard has some card which is composed of multi questions, even in same restricted collection, dashboard becomes visible for anyone. they can not see the data, but they can edit dashboard.

**Comment by attekei** [comment] 2017-06-05 17:33
I was able to reproduce this issue and it seems to apply to all dashcards with two or more questions. 

I peeked at the dashcard model source code and it seems that [`dashboard_card_series.clj`](https://github.com/metabase/metabase/blob/master/src/metabase/models/dashboard_card_series.clj) is missing the permission control logic, and as a consequence all dashcards with >1 questions are accessible by anyone.

**Comment by Digma** [comment] 2018-01-03 15:54
A small message because this issue has been opened quite some time ago but it is still relevant in our case.

A quick explanation of how it affects so you get a bit more context on our use-case:

One regular use-case we have is that we want to count a number of user without necessarily giving access to everyone to all the ID of the users. The collection allow us to give access to cards counting the number of users quite nicely. 
However, this bug prevent us from truly using these questions in dashboards. Having multiple questions in a single card happens very often, especially in our case where we work a lot with time-series. 

Do you think this could be fixed by someone with little clojure or metabase api know-how?

**Closed** 2018-01-26 18:57 UTC
Labels: Bug, Permissions, Priority/P1
