### ISSUE TITLE
Cannot filter on ARRAY types in PostgreSQL

### ISSUE THREAD

**Issue by robdaemon** [metabase/metabase#18108] opened 2021-09-28 23:36 UTC
**Describe the bug**
If you have an ARRAY type in your pgsql database, you cannot filter for values in it.

**Logs**

From the JS console:

```text
error ERROR: function lower(text[]) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 795
```

**To Reproduce**
Given a table such as:

```sql
CREATE TABLE token
(
   token                   bytea          DEFAULT gen_random_bytes(32) NOT NULL,
   created                 timestamp      DEFAULT now() NOT NULL,
   updated                 timestamp      DEFAULT now() NOT NULL,
   features                text[]         NOT NULL,
   state                   token_status   DEFAULT 'trial'::token_status NOT NULL,
   valid_thru              timestamp      DEFAULT (now() + '10 days'::interval) NOT NULL,
   stripe_subscription_id  text,
   user_id                 integer,
);
```

and a MBQL query of:

```json
{
  "query": {
    "filter": [
      "and",
      [
        "=",
        [
          "field",
          272958,
          null
        ],
        "valid",
        "trial"
      ],
      [
        "contains",
        [
          "field",
          272957,
          null
        ],
        "sso",
        {
          "case-sensitive": false
        }
      ]
    ],
    "source-table": 5616
  }
}
```

**Expected behavior**
A `contains` query should be able to look for values inside a PostgreSQL table.

**Screenshots**

![problem](https://user-images.githubusercontent.com/287213/135179422-a11874af-afa2-476c-b3e0-ad0d1cd75836.png)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.12+7",
    "java.vendor": "Eclipse Foundation",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.12",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.12+7",
    "os.name": "Linux",
    "os.version": "4.14.238-125.422.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "bigquery",
      "redshift",
      "druid",
      "googleanalytics",
      "h2",
      "bigquery-cloud-sdk",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.22"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-09-28",
      "tag": "v1.41.0-SNAPSHOT",
      "branch": "master",
      "hash": "6e487b3"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

**Severity**
It's annoying - you have to revert to plain SQL to accomplish this.

**Additional context**

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by jeff303** [comment] 2021-09-29 02:02
Possible duplicate of #2974?  But with much better detail.

**Comment by paoliniluis** [comment] 2024-09-13 23:45
duplicate of https://github.com/metabase/metabase/issues/2974, yes

**Closed by paoliniluis** 2024-09-13 23:45 UTC
Labels: Priority:P2, Database/Postgres, Type:New Feature, Querying/Parameters & Variables, Querying/GUI
