### ISSUE TITLE
In Custom Question, a Date JOIN is using YEAR-MONTH instead of full Date

### ISSUE THREAD

**Issue by alexandreb11** [metabase/metabase#11959] opened 2020-02-23 01:24 UTC
**Description**
In Custom Questions, using a SQL Server as Data Source, Metabase is converting my Dates, that I use in a join, to a Year-Month value (the day is always 1) when it should use the full 

**To Reproduce**
The first table contains records with multiple dates and repeated values for those dates (the date column is used in the join).
The second table is a calendar-like table, only contains unique dates (this column is used in join) and other.
So the first table is used as Primary Data in the Custom Question and the calendar-like table is used as Join Data.
*Here is the query output:*
`LEFT JOIN "dbo"."first_table" "first_table" ON datefromparts(year("dbo"."first_table"."date"), month("dbo"."first_table"."date"), 1) = CAST("calendar_table"."data" AS date)
`

The same happens if I change the order of tables.
EDIT: metabase version - v0.34.1 -  2020-01-13

**Comment by flamber** [comment] 2020-02-23 15:32
Hi @alexandreb11 
It looks like a duplicate of #10924, so I'm closing this. Upvote the other issue by clicking :+1:

**Closed by flamber** 2020-02-23 15:32 UTC
Labels: .Needs Triage, Type:Bug
