### ISSUE TITLE
v0.35.x breaks new questions in MongoDB(?)

### ISSUE THREAD

**Issue by mjk** [metabase/metabase#12279] opened 2020-04-06 17:15 UTC
**Describe the bug**
Using Metabase on a new project. Deployed on GCE as a container (version v0.35.1). Saving a new question returned a Success message in the UI, but did not actually save when looking at dashboard. Based on searching through past issues, I rolled back to v0.34.3 and the problem went away.

**Logs**
`[06e678d5-bf6a-43af-860f-798e13ae7347] 2020-04-06T13:07:37-04:00 DEBUG metabase.middleware.log POST /api/card 400 5.8 ms (0 DB calls)
{:errors {:result_metadata "value may be nil, or if non-nil, value must be an array of valid results column metadata maps."}}`

**To Reproduce**
1. Connect to MongoDB Atlas
2. Make an aggregate query as a new Question
3. See the Question return fine
4. Save the Question
5. See the "Success" message
6. Observe no question actually saved in dashboard
7. Reboot GCE instance pinned to older image
8. Repeat 1-6 and notice all is well.

**Expected behavior**
I expected the question to save as indicated.

**Screenshots**
N/A

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.19.112+",
    "user.language": "en",
    "user.timezone": "US/Eastern"
  },
  "metabase-info": {
    "databases": [
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-02-25",
      "tag": "v0.34.3",
      "branch": "release-0.34.x",
      "hash": "1a83edb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Seems impossible to use Metabase with Mongodb under these circumstances.

**Additional context**
N/A

**Comment by mjk** [comment] 2020-04-06 17:25
(possibly a duplicate of or at least related to #12265)

**Comment by flamber** [comment] 2020-04-06 18:16
Closing as duplicate of #12265 - it seems more or less the exact same steps.

**Closed by flamber** 2020-04-06 18:16 UTC
Labels: .Needs Triage, Type:Bug
