### ISSUE TITLE
Dashboard / Question. Months not fit with graph bar.

### ISSUE THREAD

**Issue by jlisyc** [metabase/metabase#9175] opened 2018-12-26 11:47 UTC
## Environment
Your browser and the version: Firefox 64
Your operating system: Windows10
Your databases: Postgres
Metabase version: 0.31.2
Metabase hosting environment: Docker
Metabase internal database: Postgres
Timezone is the same for database ,  metabase server and metabase configuration (Europe/Brussels)

## Steps to reproduce
- Create a Question as a Bar graph Grouped by month time

## Observed result
- It shows axe x with month but it is not fitted with the bar
![image](https://user-images.githubusercontent.com/33416503/50445054-51508600-090c-11e9-8191-565d0519bba6.png)

In this case, march is repeted and october is missed (even if there are data)
![image](https://user-images.githubusercontent.com/33416503/50476717-8078fd00-09c9-11e9-8e03-9d66a189c272.png)

### Thanks a lot!
-------

**Comment by flamber** [comment] 2018-12-27 18:06
@jlisyc Isn't this a duplicate of #5916 - not just related?

**Comment by salsakran** [comment] 2018-12-28 01:36
Hello @jlisyc -

What timezones is your server running on, what is your reporting timezone (if any) and what is your browser/laptop timezone ?

**Comment by salsakran** [comment] 2018-12-28 01:37
also, if you switch to table view, are the months correct?

**Comment by jlisyc** [comment] 2018-12-28 07:14
Hi @salsakran,
"What timezones is your server running on, what is your reporting timezone (if any) and what is your browser/laptop timezone ?"
Europe/Brussels
Note: in the example showed the question (images) comes from the example H2 metabase. And it happends the same.

"also, if you switch to table view, are the months correct?"
Yes, in the table it shows correct info.

**Comment by jlisyc** [comment] 2018-12-28 07:16
@flamber 
thanks. I have changed it to duplicate of the issue 5916.

**Comment by mazameli** [comment] 2019-05-14 19:51
Closing as duplicate of https://github.com/metabase/metabase/issues/5916

**Closed by mazameli** 2019-05-14 19:51 UTC
Labels: Bug, Duplicate, Priority/P2, Visualization
