### ISSUE TITLE
Dashboard cards sends a query for each filter defined

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13150] opened 2020-08-20 21:23 UTC
**Describe the bug**
Viewing a dashboard URL with parameters causes requests send for each filter defined, which causes unnecessary queries.

**To Reproduce**
1. Simple question > Sample Dataset > Products, save as Q1 and add to dashboard
2. On dashboard, add 3 filters (Category) and link to Q1's Title, Category and Vendor, save dashboard
3. View the dashboard URL `/dashboard/:id?category=Awesome Concrete Shoes&category_1=Widget&category_2=McClure-Lockman`
![image](https://user-images.githubusercontent.com/1447303/90824273-74c51180-e337-11ea-9043-58ee4c550b73.png)
4. On load (or browser refresh), the log shows requests for the same card 4 times:
```
08-20 22:42:13 DEBUG middleware.log :: GET /api/session/properties 200 3.6 ms (2 DB calls) App DB connections: 1/7 Jetty threads: 5/50 (1 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
08-20 22:42:13 DEBUG middleware.log :: GET /api/user/current 200 11.3 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (1 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
08-20 22:42:13 DEBUG middleware.log :: GET /api/database 200 5.3 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (1 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
08-20 22:42:13 DEBUG middleware.log :: GET /api/dashboard/6 200 22.3 ms (11 DB calls) App DB connections: 1/7 Jetty threads: 4/50 (1 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
08-20 22:42:13 DEBUG middleware.log :: GET /api/table/10/query_metadata 200 14.7 ms (9 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (1 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
08-20 22:42:13 DEBUG middleware.log :: GET /api/collection/root 200 3.0 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (1 idle, 0 queued) (82 total active threads) Queries in flight: 1 (0 queued)
08-20 22:42:13 DEBUG middleware.log :: POST /api/card/114/query 202 [ASYNC: completed] 70.6 ms (16 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (1 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
08-20 22:42:14 DEBUG middleware.log :: GET /api/field/109/values 200 11.1 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (1 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
08-20 22:42:14 DEBUG middleware.log :: GET /api/field/109 200 23.4 ms (7 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (1 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
08-20 22:42:14 DEBUG middleware.log :: GET /api/field/105/values 200 2.5 ms (3 DB calls) App DB connections: 1/7 Jetty threads: 5/50 (1 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
08-20 22:42:14 DEBUG middleware.log :: GET /api/field/105 200 28.1 ms (7 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (1 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
08-20 22:42:14 DEBUG middleware.log :: POST /api/card/114/query 202 [ASYNC: completed] 118.7 ms (16 DB calls) App DB connections: 1/7 Jetty threads: 3/50 (1 idle, 0 queued) (85 total active threads) Queries in flight: 2 (0 queued)
08-20 22:42:14 DEBUG middleware.log :: POST /api/card/114/query 202 [ASYNC: completed] 53.6 ms (16 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (1 idle, 0 queued) (85 total active threads) Queries in flight: 1 (0 queued)
08-20 22:42:14 DEBUG middleware.log :: POST /api/card/114/query 202 [ASYNC: completed] 89.6 ms (16 DB calls) App DB connections: 1/7 Jetty threads: 3/50 (1 idle, 0 queued) (85 total active threads) Queries in flight: 0 (0 queued)
```

The request payload is different for each request - notice the added brackets around each `value`, added one by one:
1. `{"parameters":[{"type":"category","target":["dimension",["field-id",106]],"value":"Awesome Concrete Shoes"},{"type":"category","target":["dimension",["field-id",107]],"value":"Widget"},{"type":"category","target":["dimension",["field-id",109]],"value":"McClure-Lockman"}]}`
2. `{"parameters":[{"type":"category","target":["dimension",["field-id",106]],"value":["Awesome Concrete Shoes"]},{"type":"category","target":["dimension",["field-id",107]],"value":"Widget"},{"type":"category","target":["dimension",["field-id",109]],"value":"McClure-Lockman"}]}`
3. `{"parameters":[{"type":"category","target":["dimension",["field-id",106]],"value":["Awesome Concrete Shoes"]},{"type":"category","target":["dimension",["field-id",107]],"value":["Widget"]},{"type":"category","target":["dimension",["field-id",109]],"value":"McClure-Lockman"}]}`
4. `{"parameters":[{"type":"category","target":["dimension",["field-id",106]],"value":["Awesome Concrete Shoes"]},{"type":"category","target":["dimension",["field-id",107]],"value":["Widget"]},{"type":"category","target":["dimension",["field-id",109]],"value":["McClure-Lockman"]}]}`

**Information about your Metabase Installation:**
Metabase 0.35.0, 0.36.0, 0.36.4

**Additional context**
Only sends a single request in 0.34.3
Sometimes it cancels some of the requests (step 4), which throws a stacktrace about `org.eclipse.jetty.io.EofException` in the log, but it doesn't cause a crash like #12474 (but that probably wasn't the root of the crash in that issue)
Related to #12926

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by nemanjaglumac** [comment] 2021-07-19 09:40
Seems to be fixed.
Cannot reproduce locally. Merged in unskipped repro and it's passing.

**Closed by nemanjaglumac** 2021-07-19 09:40 UTC
Labels: .Reproduced, Priority:P2, Reporting/Dashboards, Type:Bug, Type:Performance
