### ISSUE TITLE
Sharing dashboards shows all user emails when collection permissions are set

### ISSUE THREAD

**Issue by fretz12** [metabase/metabase#27861] opened 2023-01-25 04:11 UTC
**Describe the bug**
When I share a dashboard and go to `Email this dashboard`, the recipient list shows every single user within the list. If that dashboard is in a particular collection which has permissions set to a specific group, I would expect the only users within that group should be shown in the dropdown list. 

I'm happy to hear any workarounds, like disabling the autocomplete in the list of email recipients. 

**To Reproduce**
1. Create a group, call it Group A
2. Create a collection, and set permissions on it such that only Group A has access
3. Create a dashboard and put it in the collection created in step 2. 
4. When you go to the email dashboard recipient list, it will show all users even those that are not in Group A.

**Expected behavior**
I am expecting only users within a group that have access to a collection to show up in the share dashboards recipient list

**Information about your Metabase Installation:**
I'm on Metabase version 0.45.2 

**Severity**
This is high severity to us because it leaks sensitive user information across groups, and someone can accidentally send confidential data to an unintended person in another group.

**Comment by nemanjaglumac** [comment] 2023-01-25 07:03
Duplicate of https://github.com/metabase/metabase/issues/10795.
Please upvote the related issue.

**Closed by nemanjaglumac** 2023-01-25 07:03 UTC
Labels: Type:Bug, .Needs Triage
