### ISSUE TITLE
Pulse fails if using card owned by deactivated user

### ISSUE THREAD

**Issue by parzysz** [metabase/metabase#12010] opened 2020-02-28 14:17 UTC
**Describe the bug**
When a pulse is using a card which is owned by deactivated user email sending get`s error.
**Logs**
02-28 14:44:42 WARN middleware.process-userland-query :: Query failure {:status :failed,
 :class java.lang.Exception,
 :error "You do not have permissions to view Card 635.",
 :stacktrace
 ("--> query_processor.middleware.permissions$fn__40219$check_card_read_perms__40224$fn__40225.invoke(permissions.clj:20)"
  "query_processor.middleware.permissions$fn__40219$check_card_read_perms__40224.invoke(permissions.clj:15)"
  "query_processor.middleware.permissions$fn__40267$check_query_permissions_STAR___40272$fn__40278.invoke(permissions.clj:39)"
  "query_processor.middleware.permissions$fn__40267$check_query_permissions_STAR___40272.invoke(permissions.clj:34)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__36737.invoke(cumulative_aggregations.clj:57)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__40853.invoke(resolve_joins.clj:184)"
  "query_processor.middleware.limit$limit$fn__37814.invoke(limit.clj:19)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__43612.invoke(results_metadata.clj:87)"
  "query_processor.middleware.format_rows$format_rows$fn__37802.invoke(format_rows.clj:26)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__34217.invoke(add_dimension_projections.clj:232)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__34930.invoke(add_source_metadata.clj:107)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__40903.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__34777.invoke(add_row_count_and_status.clj:16)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__36813.invoke(driver_specific.clj:12)"
  "query_processor.middleware.add_settings$add_settings$fn__34800.invoke(add_settings.clj:45)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__40517.invoke(resolve_driver.clj:22)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__36127$fn__36128.invoke(bind_effective_timezone.clj:9)"
  "util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
  "util.date$call_with_effective_timezone.invoke(date.clj:77)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__36127.invoke(bind_effective_timezone.clj:8)"
  "query_processor.middleware.store$initialize_store$fn__43637$fn__43638.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__43637.invoke(store.clj:10)"
  "query_processor.middleware.async$async__GT_sync$fn__20163.invoke(async.clj:23)"
  "query_processor.middleware.async_wait$runnable$fn__35853.invoke(async_wait.clj:89)"),
 :query

**To Reproduce**
1.Create a card/query
2. Add this card to pulses screen
3. Deactivate / withdraw permissions from user who created card
4. Send email - it will fail

**Expected behavior**
Pulses should ommit checking permissions when sending email, or not try to view card/query by owner.

**Information about your Metabase Installation:**
JAR 0.34.3
You can get this information by going to Admin -> Troubleshooting.

**Severity**
It`s annoying and blocking flow of information.
User is able to generate pulse from metabase directly but for large sets of data he has to wait to see it.

**Additional context**
None

**Comment by flamber** [comment] 2020-02-28 20:27
Related to #11455

**Comment by camsaul** [comment] 2020-07-16 20:18
Duplicate of #11455

**Closed by camsaul** 2020-07-16 20:18 UTC
Labels: Priority:P2, Reporting/Pulses, Type:Bug
