### ISSUE TITLE
Formatting options at Column/Metric level

### ISSUE THREAD

**Issue by kkalyan** [metabase/metabase#12058] opened 2020-03-05 04:37 UTC
**Is your feature request related to a problem? Please describe.**
As of now, any formatting options like Percent, Currency or multiply by number needs to be specified while explore the data. This typically results in setting up same options on every exploration. 

**Describe the solution you'd like**
It would be much better to include these formatting options in Data model screens for both Columns and Metrics. 

**Describe alternatives you've considered**
Alternatively, formatting options can be supported at both explore and data model level. 

**How important is this feature to you?**
Avoiding the repetitive work makes the user experience much better. It would be great to have this. 

**Additional context**
None

**Comment by flamber** [comment] 2020-03-05 18:32
Hi @kkalyan 
Unless I'm misunderstanding, this is already available via:
Admin > Data Model > (db) > (table) > (column) :gear: > Formatting (left sidebar)
As for metrics, that sounds like a duplicate of #1858.

**Closed by flamber** 2020-03-05 18:32 UTC
Labels: .Needs Triage, Type:New Feature
