### ISSUE TITLE
Bug: Filter not applied when downloading data.

### ISSUE THREAD

**Issue by BMahr** [metabase/metabase#11557] opened 2019-12-19 08:23 UTC
**Describe the bug**
When adding a filte to a saved Question and then downloading the result, the additional filter ist not applied to the downloaded data set.

**Logs**
not applicable

**To Reproduce**
0. open the sample dataset and filter the People table to: birthdate - past 20 years. 
1. save this as a new Question "PEOPLE, Filtern nach BIRTH_DATE"
3. open a saved Question
4. click on a value in the table and use it as a filter (SOURCE = "Twitter")
5. refresh the data (the dataset is now filtred)
6. download the data set to EXCEL
7. realize the the additional filter (step 2) is NOT applied to the downloaded data

**Expected behavior**
I expected the downloaded dataset to be equal to the dataset shown in the browser

**Screenshots**
![Step3](https://user-images.githubusercontent.com/59045528/71156357-27405400-2240-11ea-88c5-9f82ef22a823.PNG)
![Step4](https://user-images.githubusercontent.com/59045528/71156355-27405400-2240-11ea-9a5f-f78f2caa46cb.PNG)
![Step5](https://user-images.githubusercontent.com/59045528/71156354-26a7bd80-2240-11ea-8d04-417777306109.PNG)
![Step6](https://user-images.githubusercontent.com/59045528/71156353-26a7bd80-2240-11ea-8ee7-ad5bd74855c9.PNG)
![Step7](https://user-images.githubusercontent.com/59045528/71156351-260f2700-2240-11ea-9158-6c98e848c09a.PNG)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
{
  "browser-info": {
    "language": "de-DE",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10",
    "java.vendor": "Private Build",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_222",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.222-b10",
    "os.name": "Linux",
    "os.version": "4.4.0-1099-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.4",
      "date": "2019-10-07",
      "branch": "release-0.33.x",
      "hash": "9559406"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Because of this bug our users may download and process incorrect data sets.
It is a medium bug since it can be avoided by adding the filter from the filter menu and not directly from the table.

**Comment by flamber** [comment] 2019-12-19 13:19
Hi @BMahr 
Thanks for the details. I have a feeling that this is likely the same problem as #11432, but I just didn't understand that issue.
Reproduced on `master`. Seems like it's not correctly "dirtying" the question.
1. This is the saved question - 76 rows visually, 76 rows downloaded:
![image](https://user-images.githubusercontent.com/1447303/71175769-f48d6000-222d-11ea-926b-5e0f21b5a7ba.png)
2. From step 1: Add filter via column header - notice the added filter and Save, but it's not completely dirty like step 3 - 15 rows visually, 76 rows downloaded
![image](https://user-images.githubusercontent.com/1447303/71175939-50f07f80-222e-11ea-8546-0fe546dc4a86.png)
3. From step 2: Try to click the filter "Source from Twitter" and then click Update
or
From step 1: Add filter via Filter-button - 15 rows visually, 15 rows downloaded:
![image](https://user-images.githubusercontent.com/1447303/71176248-0de2dc00-222f-11ea-853c-5d777e30f356.png)

**Comment by flamber** [comment] 2020-05-20 10:37
Also reproducible with Map visualization:
1. Simple question > Sample Dataset > People
2. Filter by State=`CO` (81 rows)
3. Change visualization to Map
4. Save question and refresh browse
5. "Draw box to filter" (top-right of map) and make a small selection (e.g. 1 pin)
6. Download CSV - it will still return 81 rows
7. Click the Latitude filter above the map and click "Update filter" without changing anything
8. Download CSV - it will return the amount of rows as the selection in step 5

**Comment by camsaul** [comment] 2020-07-16 20:21
The results download button is implemented as a `<form>` submit action on the frontend. If the filters are passed in as part of the `<form>` when it is submitted then I am about 90% sure everything should work as expected (but we would need to verify this). I am guessing the problem is that when the filter value is changed in the UI the `<form>` itself isn't getting rerendered to reflect the updates. If that assumption is correct then I would imagine this is a pretty easy fix.

**Comment by paulrosenzweig** [comment] 2020-07-24 13:51
Closed by #12960

**Closed by paulrosenzweig** 2020-07-24 13:51 UTC
Labels: .Frontend, Difficulty:Easy, Priority:P2, Querying/GUI, Reporting/Export, Type:Bug

**Comment by officeutils** [comment] 2024-12-24 11:48
Version 0.52 has the same problem

**Comment by paoliniluis** [comment] 2024-12-24 16:27
@officeutils this is something we fixed in 2020, this is the first time that we hear that someone has a problem in version 52, please open a new issue with clear reproduction steps if you're hitting this again
