### ISSUE TITLE
Display of multiple rows when several Excel cells are copied and pasted simultaneously into an SQL Query column filter

### ISSUE THREAD

**Issue by Deco1998** [metabase/metabase#40376] opened 2024-03-20 14:33 UTC
### Describe the bug

I am referring to the version v0.49.0 in the description below:

Before the last update, when I copied several Excel cells together and pasted them into an SQL Query column filter, they were read separately (as they should be as they are different pieces of data) and I got all the information I needed for each one of the cells I was using as inputs. However, the update to the version v0.49.0 deleted this feature. Now, when I try to copy and paste multiple Excel cells into an SQL Query column filter simultaneously, they are read as they were only one piece of data (instead of separately as before), which doesn't make sense.

### To Reproduce

1. Create an SQL Query referring to a specific database
2. Chose a specific column of the table displayed by this SQL Query
3. In a separate Excel sheet, write down, in different subsequent cells in the same Excel column, some of the pieces of data contained in the chosen column from the SQL Query table in step 2
4. Copy all the data you wrote down in step 3 from the Excel sheet
5. In one of the columns of the table displayed by this SQL Query, apply a filter (type "equal to"/"is") and paste the content copied from multiple Excel cells in step 4
6. See error (the data will be displayed as it was only one Excel cell, not as several cells as it should be)

### Expected behavior

After the filter described above is applied, the table should display all the data referring to each one of the Excel cells, which is not happening any more in this new version of Metabase (v0.49.0).

### Information about your Metabase installation

```JSON
- My browser and the version: Microsoft Edge - Version 122.0.2365.80 (Official build) (64-bit)
- My operating system: Windows 11 Enterprise
- My databases: PostgreSQL
- Metabase version: 0.49.0
- Metabase hosting environment: Azure
- Metabase internal database: PostgreSQL
```

### Severity

Blocking some important daily activities

### Additional context

![image (1)](https://github.com/metabase/metabase/assets/153678884/26883d6d-31b1-46df-9cf9-e45ba9d5193d)
![image](https://github.com/metabase/metabase/assets/153678884/a0b8cfd9-f3eb-4889-82dd-f2899a0ac544)

As you can see, all the 12 Excel cells I copied and pasted into the SQL Query column filter were read as only one cell, which blocked me from getting the information I needed from the other columns of the SQL Query table referring to these 12 cells.

**Comment by paoliniluis** [comment] 2024-03-20 14:51
duplicate of https://github.com/metabase/metabase/issues/40265, already fixed in 49.1

**Closed by paoliniluis** 2024-03-20 14:51 UTC
Labels: Type:Bug, .Needs Triage
