### ISSUE TITLE
Dashboard field filters are empty with 'can view items' permission on collection and 'no access' permission on data

### ISSUE THREAD

**Issue by fetanchaud** [metabase/metabase#8700] opened 2018-10-16 10:43 UTC
In Metabase v0.30.3,
field filters in dashboards have no items with
- can view items permission on collection
- no access permission on data

if you allow permission on data, filters get populated.

Thank you for providing us with Metabase !

**Comment by mazameli** [comment] 2018-10-24 19:30
I reproduced this with normal dashboard filters used on GUI saved questions. As @fetanchaud said, what happens is that the filter does not show either the list of options or the search box to search the options for a filter if the user does not have data access to the table containing the field that the filter uses. Instead the user just sees an input box. The filter does work if given a valid input.

I think the expected UX would be that if you grant a user access to view and use a dashboard, that you intend to let them use any and all exposed filters and see all possible values in those filters.

**Comment by flamber** [comment] 2019-02-10 19:15
This looks like a duplicate of #8472 or at least related.

**Comment by flamber** [comment] 2020-05-05 20:50
Closing this in favor of #8472

**Closed by flamber** 2020-05-05 20:50 UTC
Labels: Administration/Permissions, Reporting/Dashboards, Type:UX
