### ISSUE TITLE
Print Layout cuts off as well as loses outline on visualizations in 0.43.3

### ISSUE THREAD

**Issue by StyvieK** [metabase/metabase#23436] opened 2022-06-20 14:42 UTC
**Describe the bug**
Print layout of dashboards in 0.43.3 is significantly different and buggy in 0.43.3.  

**Logs**
Not sure what logs exactly to attach -  since its a production instance - the logs are verbose - and mostly irrelevant.   The bug is very much UI rather than an error. 

**To Reproduce**
Create dashboard.  Add some bar graphs and some pie graphs.  Ctrl+P to print and view the layout when selecting "Save as PDF" 
Notice the cut offs of pie charts,  filters stack on top of each other ,   sizing is different to how it used to be on the same dashboard. 

**Expected behavior**
Borders on visualizations to remain -  no cutting off,  no stacking of filters. 

**Screenshots**
Demo data:     Pie charts  ( postgres db connection ) 
select 'Steve' as Name,  (random()*100)::numeric as Value 
union all
Select 'Someone else', (random()*100)::numeric 
union all
Select 'Third person', (random()*100)::numeric 

Bar Chart: 
select *, floor(random() * value/100) From (select generate_series(1,5000) as value ) g

Create dashboard with 4 pies and 3 bar charts underneath.  
Add 4 category filters on the top.

Use public shared link to view

View PDF print layout in 0.43.3
![image](https://user-images.githubusercontent.com/2724634/174624007-bbd475b9-7b1a-4aa2-b1fc-7b1460facdfd.png)

Dashboard before print
![image](https://user-images.githubusercontent.com/2724634/174624068-b5d6e11d-21a7-4f57-a86b-9fbc2a923265.png)

Same scenario in older version
![image](https://user-images.githubusercontent.com/2724634/174624368-045ae5d6-7098-40a7-900c-ce5ee7517f6b.png)

Dashboard before print 
![image](https://user-images.githubusercontent.com/2724634/174624305-c6749adc-c32b-4200-a1ab-8448e551f053.png)

Note printing layout didnt cut off or drop borders etc. 

**Information about your Metabase Installation:**
NOTE:  Tried both Java v11 as well - but didnt seem to make a difference. 

{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.44",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_302-b08",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "1.8.0_302",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.302-b08",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.42.2.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Africa/Johannesburg"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.43.3",
      "date": "2022-06-13",
      "branch": "release-x.43.x",
      "hash": "c9c7ef0"
    },
    "settings": {
      "report-timezone": "Africa/Harare"
    }
  }
}
**Severity**
This issue blocks us upgrading since we use the printouts from dashboards.  We cannot have cut off graphs and stacking filters - since it makes the printouts unusable.  We have had to revert to older version.

**Comment by flamber** [comment] 2022-06-24 14:45
Regression since 0.43.0, not as severe as #23098, since there's a workaround, but most users don't know how to use scaling.
Seems like only Chrome messes with Pie chart, Firefox does not, but both will cut-off large visualizations.

Note that OP is showing screenshots from Public dashboard, and doesn't mention which version they are coming from, but it's pre-42.

Metabase has never officially supported printing, but 43 was a definite step in the wrong direction.

0.42.4
![image](https://user-images.githubusercontent.com/1447303/175557949-2f30801a-18fc-41d0-a5de-82970579efbf.png)
0.43.3
![image](https://user-images.githubusercontent.com/1447303/175558609-60428419-a714-4266-b706-09f9981c621b.png)
0.43.3 with adjust scaling
![image](https://user-images.githubusercontent.com/1447303/175558860-f3cbe1f3-7cd7-4255-ad19-43ac09eb0b97.png)

**Comment by gusaiani** [comment] 2022-07-04 19:38
@flamber, can you help me better reproduce this issue?

In short, my attempt to reproduce yields something even farther from what we'd want, I want to be sure I'm not off.

Incidentally, https://github.com/metabase/metabase/issues/23098 seems to have returned from my attempts to check.

1m18s video:
https://www.loom.com/share/41c4e4cbdfb149a8a670003c1c912f87

**Comment by flamber** [comment] 2022-07-05 08:24
@gusaiani You are testing some older version. Latest release is 43.4. I don't know which Tutti means, and it looks like you are showing vertical, whereas I showed every setting available, so try with latest master and with some settings that are similar to what I show.

**Comment by ranquild** [comment] 2022-08-03 16:22
@StyvieK We've recently merged a [PR](https://github.com/metabase/metabase/pull/24551) that should address some of the mentioned issues:
- there should no longer be any cut offs in charts
- there should be card outlines when printing

The only issue that is doesn't solve is that you would likely need to use scaling when printing dashboards with many charts on the same row. Hope that helps.

**Closed** 2022-08-04 13:21 UTC
Labels: Type:Bug, .CSS, Priority:P2, .Frontend, .Regression
