### ISSUE TITLE
Can't change data type of dashboard filter and keep variables in same arrangement without deleting all variables and making them again

### ISSUE THREAD

**Issue by samiyabroudi** [metabase/metabase#3507] opened 2016-10-11 18:00 UTC

**Comment by mazameli** [comment] 2016-10-11 18:11
If I'm understanding you correctly, you'd like the ability to change a dashboard filter's type without having to delete the filter and adding a new one, correct? Not entirely sure what you're referencing when you say "variables," but I assume you mean the fields that are wired up to the filter. This seems like a very reasonable request.

**Comment by samiyabroudi** [comment] 2016-10-11 18:33
That's exactly it. Thanks!

**Comment by flamber** [comment] 2019-02-16 22:35
Hi @samiyabroudi 
As for changing filter type, this is a duplicate of #3507, which is more descriptive.
As for reordering filters, that is already possible. Don't know when it was added, but 0.31.2 looks like this:
![screenshot 2019-02-16 16 33 09](https://user-images.githubusercontent.com/1447303/52905993-ca7fa180-3208-11e9-80aa-9eb5569c2a6c.png)

**Comment by flamber** [comment] 2020-06-01 12:52
Closing in favor of #5963. Dashboard filter reordering was added around 0.31

**Closed by flamber** 2020-06-01 12:52 UTC
Labels: .Proposal, Type:New Feature, Type:UX
