### ISSUE TITLE
metabase v0.39.4, connects to mysql8, error :Client does not support authentication protocol requested by server. plugin type was = 'mysql_native_password' 

### ISSUE THREAD

**Issue by gaofei8704** [metabase/metabase#16710] opened 2021-06-22 08:19 UTC
**Describe the bug**
connects to mysql8,it reports a error:Client does not support authentication protocol requested by server. plugin type was = 'mysql_native_password'. We changed to version 39.2，it's was running successful on the same database.

our mysql 8 configuration ：
+------------------+-----------+-----------------------+
| USER             | HOST      | PLUGIN                |
+------------------+-----------+-----------------------+
| root             | %         | mysql_native_password |
| mysql.infoschema | localhost | mysql_native_password |
| mysql.session    | localhost | mysql_native_password |
| mysql.sys        | localhost | mysql_native_password |
+------------------+-----------+-----------------------+
**Logs**
 ["org.mariadb.jdbc.authentication.AuthenticationPluginLoader.get(AuthenticationPluginLoader.java:52)"
  "org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authenticationHandler(AbstractConnectProtocol.java:727)"
  "org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:546)"
  "org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1367)"
  "org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:635)"
  "org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)"
  "org.mariadb.jdbc.Driver.connect(Driver.java:89)"
  "java.sql.DriverManager.getConnection(DriverManager.java:664)"
  "java.sql.DriverManager.getConnection(DriverManager.java:208)"
  "--> connection_pool$proxy_data_source$reify__35108.getConnection(connection_pool.clj:29)"],
 :context :ad-hoc,
 :error
 "Client does not support authentication protocol requested by server. plugin type was = 'mysql_native_password'",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:database 2,
  :query
  {:source-table 6,
   :fields
   [[:field 61 nil]
    [:field 43 nil]
    [:field 46 nil]
    [:field 50 nil]
    [:field 40 nil]
    [:field 60 nil]
    [:field 37 nil]
    [:field 53 nil]
    [:field 42 nil]
    [:field 56 nil]
    [:field 59 nil]
    [:field 51 nil]
    [:field 63 nil]
    [:field 52 {:temporal-unit :default}]
    [:field 41 nil]
    [:field 47 {:temporal-unit :default}]
    [:field 57 nil]
    [:field 62 nil]
    [:field 44 nil]
    [:field 49 nil]
    [:field 55 nil]
    [:field 54 {:temporal-unit :default}]
    [:field 58 nil]
    [:field 48 {:temporal-unit :default}]
    [:field 45 nil]
    [:field 38 nil]
    [:field 39 nil]],
   :limit 2000},
  :type :query,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :nested? false,
   :query-hash
   [-68, -85, 119, 43, -34, -40, 6, 44, -82, 40, 32, -48, 107, 13, 112, 38, -101, -119, 5, 31, 113, -101, -1, 82, -106,
    -65, 52, 59, 6, -47, 38, -11]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :data {:rows [], :cols []}} 

```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_281-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_281",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.281-b09",
    "os.name": "Linux",
    "os.version": "3.10.0-862.14.4.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "sparksql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.33"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.39.4",
      "date": "2021-06-15",
      "branch": "release-x.39.x",
      "hash": "f538050"
    },
    "settings": {
      "report-timezone": "Asia/Shanghai"
    }
  }
}
```

**Comment by flamber** [comment] 2021-06-22 12:24
Hi @gaofei8704 
I cannot reproduce.

Which version of MySQL are you using?
Are you running multiple instances of Metabase or just one?

Unrelated, but I would recommend upgrading to Java 11: https://www.metabase.com/docs/latest/operations-guide/java-versions.html

**Comment by gaofei8704** [comment] 2021-06-25 02:52
> Hi @gaofei8704
> I cannot reproduce.
> 
> Which version of MySQL are you using?
> Are you running multiple instances of Metabase or just one?
> 
> Unrelated, but I would recommend upgrading to Java 11: https://www.metabase.com/docs/latest/operations-guide/java-versions.html
Hi @flamber 
 My Metabase metadata database is：
        "name": "MySQL",
        "version": "5.7.33"
java verison：1.8.281
I have some business data in Mysql 8,when I connect to it，Error happens.
And I deployed metabase  in on my cdh platform ，It's hard to upgrade java version.
I will try to move metabase to a new place，then test it again。
thanks。

**Comment by flamber** [comment] 2021-06-25 08:50
@gaofei8704 I was asking which version of MySQL 8 you are using as data source. I can see all the other information from the Diagnostic Info. I cannot reproduce with MySQL 8.0.24. There's no changes to the driver in Metabase between 0.39.2 and 0.39.4

**Comment by flamber** [comment] 2021-06-29 15:39
Closing, since this hasn't been reported by anyone else and not enough information to troubleshoot.

**Closed by flamber** 2021-06-29 15:39 UTC
Labels: .Needs Triage, Type:Bug

**Comment by r-martins** [comment] 2022-02-01 01:23
Same error here.
Using metabase 0.41.6 and Mysql 8.0.27.
> Client does not support authentication protocol requested by server. plugin type was = 'mysql_native_password'.

I already altered the user in mysql to support native password, but it seems metabase does not support it (as it is the "client")

**Comment by flamber** [comment] 2022-02-01 08:48
@r-martins Try restarting Metabase and it should work. We have no idea why there's problems with some MySQL setups (like DigitalOcean's managed MySQL), but it seems to fail, when it establish connections sometimes.

**Comment by r-martins** [comment] 2022-02-01 20:26
Thank you guys. A restart solved the problem. :)
