### ISSUE TITLE
Don't insert default value into filter widget query if cleared

### ISSUE THREAD

**Issue by phaseOne** [metabase/metabase#20862] opened 2022-03-04 23:48 UTC
**Describe the solution you'd like**
When I clear the value of a filter widget on a question, the default is still passed into the query. This is [a documented behavior](https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#:~:text=even%20if%20the%20filter%20widget%20is%20empty). I'd prefer that clearing the value disables the filter until a new value is inserted, rather than **silently** continue to pass the default value to the query.

**Describe alternatives you've considered**
Create a dummy "empty" record in the table that is linked to the filter widget; this isn't really an option. 

**How important is this feature to you?**
Nice to have. It pretty much eliminates the possibility of creating a question with an "exclude" or "include" filter widget that has default values. Users are confused when they clear the filter, and it returns the same result as having the default there.

**Comment by flamber** [comment] 2022-03-05 08:18
Duplicate of #13961

**Closed by flamber** 2022-03-05 08:18 UTC
Labels: Type:New Feature, .Needs Triage
