### ISSUE TITLE
Calendar component render does not depend on week start setting 

### ISSUE THREAD

**Issue by AlekHed** [metabase/metabase#21125] opened 2022-03-21 09:40 UTC
**Describe the bug**
Calendar component renders first day of week as Sunday and its hardcoded into Calendar.jsx component. 
Is it possible to make it use FIRST DAY OF THE WEEK settings instead of constant?  

**To Reproduce**
Open any report with date filter and try to select date range

**Expected behavior**
Calendar week begins with FIRST DAY OF THE WEEK setting value

**Screenshots**
[Calendar Element which first week date is Sunday](https://postimg.cc/NLnnFLS6)

**Severity**
This issue is very annoying for most of our dashboard users. ( 

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "ru-RU",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.12+7-LTS",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "11.0.12",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.12+7-LTS",
    "os.name": "Linux",
    "os.version": "4.18.0-348.12.2.el8_5.x86_64",
    "user.language": "ru",
    "user.timezone": "Europe/Moscow"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "oracle"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.17"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-17",
      "tag": "v0.42.1",
      "branch": "release-x.42.x",
      "hash": "629f4de"
    },
    "settings": {
      "report-timezone": "Etc/Greenwich"
    }
  }
}
```

**Comment by flamber** [comment] 2022-03-21 09:54
Duplicate of #13899

**Closed by flamber** 2022-03-21 09:54 UTC
