### ISSUE TITLE
Filter on aggregation prevents question's fields from connecting to dashboard filters

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#26244] opened 2022-11-04 09:44 UTC
**Describe the bug**
When a question has a filter on an aggregation, some or all fields before the aggregation are not available for connecting to dashboard filters.

**To Reproduce**
On sample database:
1. Open Orders, join People.
2. Summarize: Count by Discount (auto binned).
3. Save question and add it to a new dashboard.
4. Add a dashboard date filter.
5. Notice all question's date fields are available for connection.
6. Go to the question and add a filter after the aggregation: Count is greater than 1. Save the question.
7. Notice that on the dashboard, the fields are no longer available for connection.

**Expected behavior**
All fields should stay available, regardless of filters.

**Screenshots**
![4 Nov 2022 at 10_35_18](https://user-images.githubusercontent.com/30152071/199941422-7861f44b-ad9a-4639-badc-a83df3bba33a.gif)

**Information about your Metabase Installation:**
`{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "5.10.76-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-08-31",
      "tag": "v0.44.2",
      "branch": "release-x.44.x",
      "hash": "8d9de8a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2022-11-04 15:47
Basically the same as #19744, since it would still have the metrics and group-bys available, though that would cause #12985

**Comment by bshepherdson** [comment] 2024-02-16 14:41
This is even worse on master now :scream: 

The query seems to be just broken with the second-stage filter. The network request looks sound, returning the count and discount columns and with correct values for 3 rows. But the query doesn't visualize at all and the dashboard is broken.:
![2024-02-16-093551_1867x1561_scrot](https://github.com/metabase/metabase/assets/157812/8636ec41-3c1a-459e-9227-993deb95d749)
![2024-02-16-093732_1829x1202_scrot](https://github.com/metabase/metabase/assets/157812/ef645b79-4e82-4ee3-906a-2add6fc0e74f)

At first I guessed this was choking on one of the bin values being `null` (since many orders have no discount) but that's not it. Trying the same basic flow with a non-nil column like subtotal yields the same results!

I'm checking this on the 49 RCs; this would be a release blocker for sure if present there.

**Comment by bshepherdson** [comment] 2024-02-16 15:13
This reproduces on 0.49.0 RC1 as well. These issues share a repro but the symptoms are different, so I've filed a separate issue #38861 for that.

Until that "covering" issue is fixed, we can't really reproduce the original form of this bug. I'm going to guess at easy/medium for difficulty to fix this. Not clear from what we know whether this original issue is MLv2 related or FE related.

**Comment by bshepherdson** [comment] 2024-06-21 16:15
My #38861 is a dupe of #10493 , which is a FE issue under active work.

I'm actually working on the underlying issue anyway, since it should be solved by #19744 .

**Comment by perivamsi** [comment] 2024-07-16 13:36
Duplicate of https://github.com/metabase/metabase/issues/19744

will close this issue in favor of the other one

**Closed by perivamsi** 2024-07-16 13:36 UTC
Labels: Type:Bug, Priority:P1, Reporting/Dashboards, Querying/Parameters & Variables, Querying/Nested Queries, .Team/QueryProcessor, .Wanted: MLv2
