### ISSUE TITLE
Mac Client Chart Formatting

### ISSUE THREAD

**Issue by billmohler** [metabase/metabase#3350] opened 2016-09-13 17:45 UTC
When using the a client you're unable to format the Y-axis because the pop-over is not properly rendering.  Since you need to specify the axis of the results to chart, I can't get charting to work.

![screenshot 2016-09-13 10 31 58](https://cloud.githubusercontent.com/assets/13141697/18484839/f7e3ff38-799e-11e6-9eb2-0c477879ab9b.png)

**Comment by salsakran** [comment] 2016-09-13 18:25
What is the underlying data you are trying to graph. 

Can you reproduce this using our sample data? Tried this out on v0.19.3 of the mac client and the drop down correctly renders for me.

**Comment by billmohler** [comment] 2016-09-13 18:39
I’m trying to do revenue over time.  Query works fine as a table.

The problem is then when I select a line graph, it asks me to specify X and Y axis.  I can set the X axis, but the Y axis will not allow me to set it.  I have two variables.

Order Date (MM-YY)
Revenue ($)

The Y axis is not allowing a drop down to select the Revenue.





----
Bill Mohler
(760) 224-4651
bill@mohler.me

**Comment by salsakran** [comment] 2016-09-13 18:42
Is this with sql or the gui? Can you share the query + the underlying table schema?

Again, if there's anyway you can reproduce this using the sample dataset, we can probably get a quick fix.

**Comment by billmohler** [comment] 2016-09-13 18:54
GUI

SELECT
	DATE_FORMAT (client_transactions.dts,"%m/%Y") as orderdate,
	Concat('$', format(SUM(invoiceamount), 2)) AS "Total Sales"
FROM
	`orders`
	JOIN client_transactions ON (client_transactions.orderid = orders.id )

WHERE
	client_transactions.dts >= DATE_FORMAT(NOW()-INTERVAL 3 MONTH, "%Y-%c-01 00:00:00")	AND
	orders.companyid = 1 AND
	order_status = 7 
GROUP BY
	orderdate
	;
	
The table results are really simple, I get the same results in Sequel Pro



I just can’t assign the axis to plot the y.  
----
Bill Mohler
(760) 224-4651
bill@mohler.me

**Comment by billmohler** [comment] 2016-09-13 19:01
The top axis I can select, the bottom axis has a pop under that is unpopulated/can’t select.
----
Bill Mohler
(760) 224-4651
bill@mohler.me

**Comment by salsakran** [comment] 2016-09-13 19:05
Ok, so the reason it's not working is the `Concat('$', format(SUM(invoiceamount), 2)) AS "Total Sales"`. 

This is a string, and as such can't really be plotted on a Y-Axis without conversion. In this case, that would mean detecting + stripping the '$' and casting the remaining string as a float. This sort of casting is beyond what we do auto-magically. If you replace the above with just `SUM(invoiceamount)` it should all work.

**Comment by billmohler** [comment] 2016-09-13 19:18
Ok. I'll change it from a string. 

---------

Bill Mohler
(760) 224-4651

**Comment by salsakran** [comment] 2016-09-13 19:19
closing this. we can re-open if there's an actual bug (vs the lack of auto-magic)

**Closed by salsakran** 2016-09-13 19:19 UTC
Labels: Bug, Client/Mac App
