### ISSUE TITLE
Dashboard Filters - comma keeps getting deleted from input

### ISSUE THREAD

**Issue by samiyabroudi** [metabase/metabase#3510] opened 2016-10-11 19:31 UTC
This problem happens at the dashboard level, but doesn't happen at the question level (with variables)

Thanks.

**Comment by salsakran** [comment] 2016-11-07 19:52
is this on numbers or strings?

**Comment by samiyabroudi** [comment] 2016-11-07 20:09
Numbers

**Comment by attekei** [comment] 2017-07-17 22:48
Possibly a duplicate of https://github.com/metabase/metabase/issues/5457

**Comment by samiyabroudi** [comment] 2017-07-17 22:50
It is not. Very separate

**Comment by attekei** [comment] 2017-07-17 22:51
Could you @samiyabroudi provide steps to reproduce the issue? Thanks!

**Comment by samiyabroudi** [comment] 2017-07-17 22:54
I believe this issue is from November and was eventually fixed

**Comment by attekei** [comment] 2017-07-17 22:55
Ah, good to hear. Seems that we are happy with closing this issue.

**Closed by attekei** 2017-07-17 22:55 UTC
Labels: Bug, Dashboards, Parameters/Variables, Priority/P3
