### ISSUE TITLE
Cannot deploy on Heroku

### ISSUE THREAD

**Issue by jbasko** [metabase/metabase#11323] opened 2019-11-15 12:57 UTC
**Describe the bug**
If I go to https://elements.heroku.com/buttons/metabase/metabase-deploy and click the button "Deploy to Heroku" and choose region "Europe" (didn't try with US) and then click "Deploy app" then the deployment fails. It failed two days ago, it failed today.

**Logs**

```
...

-----> Build
       Running build (yarn)
       yarn run v1.19.1
       $ yarn && webpack --bail
       $ echo $npm_execpath | grep -q yarn || echo '\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
       [1/5] Validating package.json...
       [2/5] Resolving packages...
       [3/5] Fetching packages...
       info fsevents@1.1.3: The platform "linux" is incompatible with this module.
       info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
       [4/5] Linking dependencies...
warning " > grid-styled@4.1.0" has unmet peer dependency "styled-components@>=2.0 || >=3.0".
warning " > postcss-cssnext@2.11.0" has unmet peer dependency "caniuse-db@^1.0.30000652".
       [5/5] Building fresh packages...
internal/modules/cjs/loader.js:895
    throw err;
    ^
Error: Cannot find module 'babel-register'
Require stack:
- /tmp/build_407122d885f5ead60623c2f81ecc2ae3/webpack.config.js
- /tmp/build_407122d885f5ead60623c2f81ecc2ae3/node_modules/webpack/bin/convert-argv.js
- /tmp/build_407122d885f5ead60623c2f81ecc2ae3/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/tmp/build_407122d885f5ead60623c2f81ecc2ae3/webpack.config.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/build_407122d885f5ead60623c2f81ecc2ae3/webpack.config.js',
    '/tmp/build_407122d885f5ead60623c2f81ecc2ae3/node_modules/webpack/bin/convert-argv.js',
    '/tmp/build_407122d885f5ead60623c2f81ecc2ae3/node_modules/webpack/bin/webpack.js'
  ]
}
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**To Reproduce**

1. go to https://elements.heroku.com/buttons/metabase/metabase-deploy 
2. click "Deploy to Heroku"
3. choose region "Europe" (didn't try with US)
4. click "Deploy app" then the deployment fails.

**Comment by flamber** [comment] 2019-11-15 17:16
Hi @jbasko 
It looks like a duplicate of #9661/#8716. If you agree, then please close this issue.
Have you tried https://www.metabase.com/start/heroku.html instead?

**Comment by jbasko** [comment] 2019-11-15 17:58
Okay, I can close it, but neither of them have got any attention recently anyway. What is the method to install this on heroku?

**Comment by flamber** [comment] 2019-11-15 18:05
@jbasko I understand what you're saying, but there's already 2000+ issues open, so adding duplicates doesn't really help overview and prioritizing issues.
Click :+1: on the first post of issues to upvote them - that's how issues are prioritized.
How to install on Heroku? Follow the link I posted: https://www.metabase.com/start/heroku.html

**Closed** 2019-11-16 00:18 UTC
Labels: .Needs Triage, Type:Bug

**Comment by jbasko** [comment] 2019-11-16 00:20
Thank you. Great success!
