### ISSUE TITLE
Issue with date field filters after v0.35.0 upgrade

### ISSUE THREAD

**Issue by lukeman** [metabase/metabase#12228] opened 2020-04-01 15:18 UTC
**Describe the bug**
On a question or a dashboard with a date field filter, there seems to be an issue with deserializing the query parameter. I almost always use relative defaults like the past 30 days, so it may be limited to those strings. Choosing an option from the date filter works, but if you reload the page it fails to parse the query param as below.

**Logs**
I decided to quickly roll back my primary instance once I confirmed this issue, so unfortunately I don't have a full set of logs, but this is the error that is presented in the browser.

`Input to date-string->range does not match schema: [0;33m [(named (not (instance? java.lang.String ["past30days"])) date-string) nil] [0m`

**To Reproduce**
1. Create a native question and/or a dashboard with a field filter against a date column
2. Set the value to something like "past 30 days"
3. Reload the question/dashboard now that the param is set in the URL

**Expected behavior**
Date filter should work, both default values but also when query params are present.

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome, Edge & Safari
- Your operating system: macOS Catalina
- Your databases: BigQuery
- Metabase version: v0.35.0
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
Pretty severe. I usually would try to get more info and submit a better bug report, but in this case I felt I needed to roll back to v0.34.3 right away.

**Comment by Olaktal** [comment] 2020-04-01 15:27
+1 ! https://github.com/metabase/metabase/issues/12230

**Comment by mazameli** [comment] 2020-04-01 15:35
Reproduced. It seems to happen only when a saved dashboard or question is newly loaded, e.g. when you first arrive at it from a collection. Re-running the query doesn't fix it, but clicking on the filter and hitting "Update filter" and _then_  re-running the query does then result in the correct behavior.

This does _not_ seem to affect GUI-based questions.

**Comment by rjansen** [comment] 2020-04-02 13:16
+1
Hi guys. Do you have any workaround to solve this issue?

**Comment by flamber** [comment] 2020-04-02 13:20
@rjansen Downgrade to 0.34.3 until there's a fix released (most likely 0.35.1). Remember to backup.

**Comment by parisholley** [comment] 2020-04-02 14:12
for anyone needing a quick fix, it appears an automated build is available on dockerhub that i was able to use as a temporary workaround until next release:

`metabase/metabase-head:fix-12228`

**Comment by paulrosenzweig** [comment] 2020-04-02 14:13
Fixed in #12239, which will be release in 0.35.1

**Closed by paulrosenzweig** 2020-04-02 14:13 UTC
Labels: Priority:P1, Querying/Parameters & Variables, Type:Bug

**Comment by rjansen** [comment] 2020-04-02 18:36
Hi guys, a tried the version `metabase/metabase-head:fix-12228`, but some questions do not work. The questions are loading forever. Even if I try to change the filter value. In the logs I can't find any information just the query API receiving the request. In the table `query_execution` the query was aborted due to `Error reducing result rows` error.

Could you give me help?

Logs:
```
04-02 17:56:28 INFO middleware.cache :: Query took 357.0 ms to run; miminum for cache eligibility is 15.0 s
04-02 17:56:28 DEBUG middleware.log :: POST /api/card/1/query 202 [ASYNC: completed] 391.0 ms (7 DB calls) App DB connections: 1/7 Jetty threads: 2/50 (5 idle, 0 queued) (107 total active threads) Queries in flight: 0 (0 queued)
```

**Comment by mazameli** [comment] 2020-04-02 18:40
@rjansen Are you seeing any commonalities among the questions that don't work? Are they all against the same database type? If you were to recreate from scratch one of the saved questions that isn't working, does it then work?

**Comment by rjansen** [comment] 2020-04-02 21:35
Hi @mazameli, I tried to create a new question with the same arguments but I got the error: `Error reducing result rows` on the query_execution table.
These questions share the same database type and using date filters. But other questions with similar behavior work well.

**Comment by paulrosenzweig** [comment] 2020-04-02 21:53
@rjansen I'm not sure how to reproduce this issue. Do all questions with date filters show this bug? Are you looking at individual questions or dashboards? I suspect this is a separate bug, but knowing more about it will help determine whether to create a new issue or reopen this one.

Is it possible for you to give us steps to see the issue you're talking about? For example something like this:
1. Create a sql question using the Orders table in the sample dataset
2. Add a field filter on created at
3. etc...

**Comment by rjansen** [comment] 2020-04-02 21:59
Hi @mazameli I found more information about the problem um the api response.
The data for questions is returned bu the error I mentioned, `Error reducing result rows`, is returned together. In the returned stack trace an 

Erro on Api Response:
```
class clojure.lang.ExceptionInfo","error":"Error reducing result rows","stacktrace":["--> query_processor.context.default$default_reducef$fn__37780.invoke(default.clj:61)","query_processor.context.default$default_reducef.invokeStatic(default.clj:58)","query_processor.context.default$default_reducef.invoke(default.clj:49)","query_processor.context$reducef.invokeStatic(context.clj:69)"
``` 

Error on the result query status:
```
class java.lang.StackOverflowError","stacktrace":["clojure.lang.Numbers.isZero(Numbers.java:117)","--> sync.analyze.fingerprint.insights$change.invokeStatic(insights.clj:29)","sync.analyze.fingerprint.insights$change.invoke(insights.clj:26)","sync.analyze.fingerprint.insights$change.invokeStatic(insights.clj:35)","sync.analyze.fingerprint.insights$change.invoke(insights.clj:26)"
```

**Comment by paulrosenzweig** [comment] 2020-04-02 22:05
@rjansen that sounds like a different bug. I created a new issue #12251. Please follow up there with steps on how to reproduce the issue.
