### ISSUE TITLE
Dashboard show blank page after upgrading to version 0.39.3

### ISSUE THREAD

**Issue by Orkin** [metabase/metabase#16544] opened 2021-06-10 21:14 UTC
**Describe the bug**
I was previously on Metabase 36.3 version and I upgrade to 39.3. Previously my dashboard with filters (with default values) works pretty well. Since the upgrade I am unable to access to the dashboard and I have a blank page (I can see Metabase title in code source). I dont have errors in metabase logs, just in my browser console. When I start loading the dashboard I can see metabase headers and on error all disapear.
I search a lot of things, I tried to reset cache, re-sync database and I tried to re-create the dashboard from scratch. The creation is working perfectly, when I saved it everything was ok and I could see all my metrics. I tried to reload the page and blank page 😢 

**Logs**
I have a lot of javascript warnings and 3 times this error in log.
```
react_devtools_backend.js:2560 TypeError: Cannot read property 'field' of null
    at app-main.bundle.js?8f423c47488b32b1f66b:5
    at Array.map (<anonymous>)
    at t.value (app-main.bundle.js?8f423c47488b32b1f66b:5)
    at new t (app-main.bundle.js?8f423c47488b32b1f66b:5)
    at yo (vendor.bundle.js?8f423c47488b32b1f66b:487)
    at Ia (vendor.bundle.js?8f423c47488b32b1f66b:487)
    at vs (vendor.bundle.js?8f423c47488b32b1f66b:487)
    at vu (vendor.bundle.js?8f423c47488b32b1f66b:487)
    at gu (vendor.bundle.js?8f423c47488b32b1f66b:487)
    at uu (vendor.bundle.js?8f423c47488b32b1f66b:487)
```
I didn't past all logs because it's really verbose. If it's useful I can add them later with pleasure.

I have also a lot of http request that are cancelled
<img width="1753" alt="Capture d’écran 2021-06-10 à 23 11 04" src="https://user-images.githubusercontent.com/1061903/121597748-5d2f5480-ca41-11eb-8520-0950c304bd24.png">

**To Reproduce**
I don't know how to reproduce. I tried to revert to the previous version 36.3 and revert database schema for `metabase_field` table to rename `semantic_type` column to `special_type`

**Expected behavior**
The dashboard is visible

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "5.4.110-54.189.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-27",
      "tag": "v0.39.3",
      "branch": "release-x.39.x",
      "hash": "598a112"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}
```

**Severity**
It is an annoying problem because the dashboard is not usable. This is our main dashboard.

If someone has an idea of what kind of problem it could be 😉 

Thanks a lot in advance

**Comment by flamber** [comment] 2021-06-11 15:31
Hi @Orkin 
It's going to be very difficult to figure out what's going on without seeing the metadata for your dashboard and the questions.
That means the response from each request (except the actual row data).

Another possibility is to try creating a similar dashboard with Sample Dataset or note all your steps, so we can reproduce and fix the problem.

The cancelled requests is because the dashboard went blank, so that is expected.

Downgrading without reverting to a backup is really not recommended, since the application database is now in a different state than the version you're on. Just downgrading is a great way of causing corruption, which can be extremely difficult to fix.

**Comment by Orkin** [comment] 2021-06-11 15:40
Hi @flamber thanks for your reply

I understand that is very complicated to identify the problem. How can I give you thoses metadata without giving some sensitives data ?

Yes I understand so I had restore the database to point in time before the upgrade and everything works perfectly now. I can provide you information for schema from version 0.36.3, I hope it's enough to identify the problem ?

**Comment by Orkin** [comment] 2021-06-11 16:09
Thanks @flamber I will come back to you when I can do this. I would like to copy my actual database et load custom data in a separate metabase instance to avoid same problem again.

In the meantime, can I provide to you some informations ? Maybe api responses from dashboard query or something like that ? This is the only one dashboard that do not works properly so that's a really weird problem

**Comment by flamber** [comment] 2021-06-11 20:21
@Orkin I don't really know where to look, so I would basically need all the responses, which you can export as a HAR-file via the Chrome developer Network-tab - but that will include sensitive data.
That's why I'm recommending that you try to narrow down the problem first by making multiple duplicates of the dashboard and only have one card on each (and the relevant filters for that card). That way you can narrow in on a particular card (question), which is causing problems (`/api/card/:id/query`) or perhaps it only happens when filters are connected.

**Comment by flamber** [comment] 2021-06-17 20:32
Closing, but please comment back if you can provide more information on how to reproduce or debug information.

**Closed by flamber** 2021-06-17 20:32 UTC
Labels: .Needs Triage, Type:Bug
