### ISSUE TITLE
Column not showing in dashboard after question revision

### ISSUE THREAD

**Issue by OnFormLimited** [metabase/metabase#19174] opened 2021-12-02 12:10 UTC
**Describe the bug**
A revised question that brings in a new column called 'description' (and aliased in Metabase as Job Description) does not show in the dashboard. 

**Logs**
[metabaselog2.txt](https://github.com/metabase/metabase/files/7641637/metabaselog2.txt)

**To Reproduce**
1. Go to **Dashboards | Client Services**
2. Click on **Timesheet Check**
3. In the columns, Job Description cannot be seen.
4. Click on the question 'Timesheet Check'
5. Now it **can** be seen

**Expected behavior**
Column should be visible in the dashboard

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.53",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "4.14.219-164.354.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.9"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-11-09",
      "tag": "v1.41.2",
      "branch": "release-x.41.x",
      "hash": "ad599fd"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
We have a workaround, but it's concerning that this should occur at all.

**Additional context**
The query that joins 2 tables both herald the column 'description' - but again - as stated - in the model it's alias has changed which I thought would be adequate

**Comment by flamber** [comment] 2021-12-02 12:21
Hi @OnFormLimited 
This very much sounds like a duplicate of #18086/#17769. Closing in favor of those.
It is not possible to reproduce with your steps, since that requires your data.

**Closed by flamber** 2021-12-02 12:21 UTC
Labels: Type:Bug, .Needs Triage
