### ISSUE TITLE
Long table lists cause UX issues with scrolling on data model pages

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2673] opened 2016-05-26 18:04 UTC
This is meant to be a continuation of https://github.com/metabase/metabase/issues/2553 which provides a more meaningful solution.

**Comment by flamber** [comment] 2021-11-06 16:26
Closing, since a lot has changed and there's no screenshots or steps-to-reproduce.

**Closed by flamber** 2021-11-06 16:26 UTC
Labels: Type:UX
