### ISSUE TITLE
Column Filter Greyed Out - Sandboxed User

### ISSUE THREAD

**Issue by jpipas** [metabase/metabase#11473] opened 2019-12-09 15:58 UTC
**Describe the bug**
As a sandboxed user, viewing a sandboxed table, I am able to filter a column only when using the filter "sidebar".  When I try to filter the column directly by clicking on the Column Header->Filter , the "Update Filter" button is greyed out and not selectable.  However, I'm able to click on a cell row and filter an exact value, or fully customize the filter directly by using the "sidebar" filter.  As an "Admin" user (non-sandboxed user) the column header is able to be filtered.

**Logs**
Not receiving any errors, but I can pull logs upon request.

**To Reproduce**
Create a sandbox (requires Enterprise edition) - and assign a user to that sandbox.  Access any saved question.
1. Click on a column header...
2. Click on '"Filter"
3. Try and add a filter
4. "Update Filter" is greyed out

**Expected behavior**
If I can add a filter via the "sidebar" - I would expect I could use the column header to filter the values as well.

**Screenshots**
<img width="330" alt="Screen Shot 2019-12-09 at 10 42 59 AM" src="https://user-images.githubusercontent.com/73047/70450676-1cccd000-1a72-11ea-84ab-8682ff4cfdc3.png">
<img width="382" alt="Screen Shot 2019-12-09 at 10 43 15 AM" src="https://user-images.githubusercontent.com/73047/70450681-20f8ed80-1a72-11ea-8ce5-2d95fbae060b.png">

**Information about your Metabase Installation:**
```{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.14.109-80.92.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-11-26",
      "tag": "v1.33.6.1",
      "branch": "enterprise-release-1.33.x",
      "hash": "b02d8b9"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}```


**Severity**
Not a show stopper, but somewhat annoying that functionality is "limited".

**Comment by mazameli** [comment] 2019-12-17 00:37
Hi Jeff! Since this has to do with the enterprise edition, I've opened a new support ticket on your behalf with a couple questions about this. Could you please check your email?

I'll go ahead and close this GitHub issue and we'll follow up via the support ticket. Thanks!

**Closed by mazameli** 2019-12-17 00:37 UTC
Labels: .Needs Triage, Type:Bug

**Comment by jpipas** [comment] 2020-01-14 19:31
@mazameli - could you send me the ticket number on this... I never received an email...

**Comment by mazameli** [comment] 2020-01-14 19:41
@jpipas Sorry about that, Jeff. Not sure why you didn't receive the support email, but I've just tried adding you as an explicit CC on it and sent it again, so if you could please reply to that if and when you get it that would be great so I can confirm zendesk is working right. Thanks!
