### ISSUE TITLE
Export to Excel in embedded dashboard differs from export on query page

### ISSUE THREAD

**Issue by Yambr** [metabase/metabase#16796] opened 2021-06-28 15:29 UTC
**Describe the bug**
[bug in query](https://github.com/metabase/metabase/issues/10803) - fixed and works fine
but i have same problem in embedded dashboard

**To Reproduce**
1. Go to any query with timestamp column
2. Add query to dashboard
3. Turn on embedding for this dashboard, click on the cloud and download results from query on dashboard

**Expected behavior**
Exporting from embedded dashbord works like exporting from query

**Screenshots**
![image](https://user-images.githubusercontent.com/28951082/123662718-62acdd00-d83e-11eb-987f-29a6b18b8d60.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version:  Chrome v.91
- Your operating system:Windows 10.1809
- Your databases: MS SQL
- Metabase version: v0.39.1
- Metabase hosting environment:  Docker
- Metabase internal database: Postgres 

**Severity**
blocking exporting from dashboard

**Comment by flamber** [comment] 2021-06-28 15:30
Duplicate of ##14393

**Closed by flamber** 2021-06-28 15:30 UTC
Labels: .Needs Triage, Type:Bug
