### ISSUE TITLE
Ability to use native SQL in custom columns within the UI

### ISSUE THREAD

**Issue by jack-cook-repo** [metabase/metabase#24549] opened 2022-08-03 10:51 UTC
**Describe the solution you'd like**
Where there are some gaps in the [custom expressions](https://www.metabase.com/docs/latest/users-guide/expressions-list.html), for example if I want to do a DATEADD (Bigquery) on a date column, it would be great to be able to write custom SQL to use as a column (or even as a custom metric) in the UI.

**Describe alternatives you've considered**
The only real alternatives at the moment is turning to a SQL question - or doing more of the transformations upstream. Both options are viable, but they have drawbacks:
- Custom SQL questions become a lot harder to maintain compared to UI questions, and are less transparent
- There are some things we only want to do for a one-off analysis rather than plumbing it into our data pipeline (e.g. a specific DATEADD number of days)

**How important is this feature to you?**
This would be a big value add for us, as it would combine the ease of use/maintenance for the UI with the flexibility of custom SQL. 

**How could this work?**
I imagine you'd either have a new option alongside `Custom column` such as `Native SQL column` with a caveat that there will be no syntax suggestions, or you could have a checkbox for `Native SQL` in the existing `Custom column`. 

<img width="489" alt="image" src="https://user-images.githubusercontent.com/61659989/182589848-5878d18d-4560-4b2a-8957-e83c86dfbcbc.png">

I imagine that handling this from your end would be more straightforward as you'd just be parsing `{{column_expression}} AS {{column_alias}}` without any need to convert it for each database vendor (given that it'd just be directly interpreted).

Custom metrics could work in a similar way, but there's a risk of non-compatible window functions being used with a GROUP BY.

**Comment by flamber** [comment] 2022-08-03 10:58
Duplicate of #16873. Time manipulations are coming in #19274.

**Closed by flamber** 2022-08-03 10:58 UTC
Labels: Type:New Feature, .Needs Triage
