### ISSUE TITLE
Filters on dashboard duplicated with a previous and new value.

### ISSUE THREAD

**Issue by HillReywer** [metabase/metabase#24699] opened 2022-08-10 11:00 UTC
**Describe the bug**
Question answer changes between dashboard view and question view when applying a filter from the dashboard first. At the same time when you open a question from a dashboard with a pre-applied filter and then try to update the filter, it gets duplicated with a previous and new value.

**To Reproduce**
1. Add a question within a dashboard and make sure to have dashboard filters
2. Update dashboard filter (ex. country = FR)
3. Remember the value (we will call it X)
4. Open a question
5. Update the filter that you used in a dashboard (ex. replace country from FR to DE)
6. You will see that there are 2 country codes
7. Remove the latest filter (ex. country = DE)
8. View that value of the question is not X anymore but Y (even tho we are back at the initial filter setup as in step 3)

**Expected behavior**
As a user, I expect to be able to update filters on a question when entering from the dashboard without data changes and filter duplication. 

**Screenshots**

**Severity**
The severity is 6/10. It introduces chaos as people are not sure anymore what is the accurate number as you see different variations according to the flow.

**Comment by sachalau** [comment] 2022-08-10 12:05
Suffering from the same bug, since updating to 0.44. Very confusing :(

**Comment by HillReywer** [comment] 2022-08-10 12:08
@sachalau Yes, we faced with this after update at 0.44 version too.

**Comment by flamber** [comment] 2022-08-10 12:13
I cannot reproduce with the steps provided. Can someone provide steps using Sample Database or show a video or screenshots?
Sounds a lot like #24664

**Comment by sachalau** [comment] 2022-08-10 12:17
Yeah it's the same indeed !

**Comment by HillReywer** [comment] 2022-08-10 12:20
@flamber https://youtu.be/Zrxks7_DMdE

**Comment by flamber** [comment] 2022-08-10 12:44
Duplicate of #24664 - fixed in upcoming 44.1 coming in a few days.

**Closed by flamber** 2022-08-10 12:44 UTC
Labels: Type:Bug, .Needs Triage
