### ISSUE TITLE
"Last x days/hours"-Filter 

### ISSUE THREAD

**Issue by majnu-campact** [metabase/metabase#6404] opened 2017-11-16 10:07 UTC
Metabase has great filtering capabilities, but I found no way to select say the last 14 days **including** today in a filter. Our data is available in real-time and we have a hard time with relative date filters (like "Previous x days/hours") that mostly exclude the last day/hour, etc.

Thanks!

**Comment by Digma** [comment] 2017-11-16 15:42
Typically what we do in our case is filter on "last 1440 minutes" to get data for the last day in real-time. However this only works in question but not in dashboard filters since metabase restricts options to "day/week/month/year"

**Comment by mazameli** [comment] 2017-11-16 19:13
Yep, we'd really like to add this. This issue is a duplicate of https://github.com/metabase/metabase/issues/4749.

**Closed by mazameli** 2017-11-16 19:13 UTC
Labels: Duplicate
