### ISSUE TITLE
Collections should be able to be deleted and still cannot be

### ISSUE THREAD

**Issue by prilosac** [metabase/metabase#10375] opened 2019-07-18 17:26 UTC
**Is your feature request related to a problem? Please describe.**
I'm a developer working with your API. As a developer, I need to be able to test different things, and easily undo those actions. However, as of Metabase v0.32.8, collections cannot be deleted, either through the UI or with the API. I created an issue 11 months ago, #8285, which I am unsure why was closed. It was claimed to be a duplicate of #8096, which it is not since that issue specifically discusses deleting cards and dashboards (which _has_ been implemented, while I'm discussing deleting collections, which _has not_). @kdoh said it was being worked on in #8820, and that collections would be deletable, but that issue has since been closed and they still are not deletable. 

**Describe the solution you'd like**
Ideally, we would be able to simply delete a collection from the UI (just like you can a card or dashboard) rather than only have the option to unarchive it. An endpoint (e.g. DELETE /api/collections/:id) is also needed. If I could only choose one though, it would definitely be the API endpoint.

**Describe alternatives you've considered**
The only alternative is to develop with two Metabase instances, having to completely reset the second one any time I do a test. This is because my use of the API revolves around the transfer of Metabase objects (including collections), and once a collection is created, it is permanently present and thus I can no longer test anything involving creation of that collection.

**How important is this feature to you?**
Incredibly. As mentioned before, my development and testing needs require the ability to wipe out a metabase instance often of all added cards, dashboards, and collections. I can delete cards and dashboard through the UI or the API, but collections cannot be deleted, making it near impossible to develop for without installing a fresh Metabase instance every time. 

**Additional context**
The below screenshots show that while I am able to actually delete other types of objects, collections can still only be unarchived.
![Screen Shot 2019-07-18 at 12 22 48 PM](https://user-images.githubusercontent.com/18317064/61478357-f9847580-a956-11e9-814f-0c00378a4e31.png)
![Screen Shot 2019-07-18 at 12 22 41 PM](https://user-images.githubusercontent.com/18317064/61478358-f9847580-a956-11e9-855a-90a1b2008325.png)

In general I think it is important to keep developers in mind and remember that just because a user takes an action, doesn't necessarily mean they want it to be forever permanent. I do understand the desire to maintain data integrity and history by defaulting to an archive, but I really feel that the ability to delete is more of a missing feature than a new one.

**Comment by flamber** [comment] 2019-07-18 18:21
Related to #2783, which is half fixed.
There's more details why deletion of collections is not easy in the comments of #9452.

**Comment by prilosac** [comment] 2019-07-18 18:31
Makes sense, I hope they get it figured out soon though. It's a blocker for my development with their API.

**Comment by salsakran** [comment] 2019-10-07 00:01
dupe of #2783

**Closed by salsakran** 2019-10-07 00:01 UTC
Labels: Type:New Feature

**Comment by yasergsi** [comment] 2022-12-30 06:14
I would like to have this feature as well since when I archive a collection and create a new one with the same name it adds a sequential serial number as a suffix to the collection name which looks very bad when clients view it on our website which has full app embedding if Enterprise version.
