### ISSUE TITLE
Table Metadata Menu - Column with "Only in detail view" option enabled is not actually visible in the Details View

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#32097] opened 2023-07-03 15:56 UTC
### Describe the bug

Column with "Only in detail view" option enabled is not actually visible in the Details View

### To Reproduce

1. Go to Admin -> Table Metadata -> Sample Databast -> Products -> Set `Category` to Only in detail views

<img width="1333" alt="image" src="https://github.com/metabase/metabase/assets/110378427/b894171f-c1e6-4b7c-8a7f-bd506396b9eb">

2. Click on Browse Data -> Sample Databast -> Products -> Click Details View -> There is no `Category` column

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/3afe39a2-1dd4-4bb9-99b4-331087bdbb17">

### Expected behavior

Columns should be visible in the Details Views if Only in detail views is enabled

### Logs

None

### Information about your Metabase installation

```JSON
1.46.6 and master
```

### Severity

minor

**Comment by krschacht** [comment] 2023-08-20 15:58
@Tony-metabase I think we should increase the priority of this bug. “only detailed view” is an explicit toggle which is broken because of this bug. A big value of metabase is being able to manage an overwhelming number of database columns. You hide the ones analytics doesn’t need, and you reserve most for detailed only. With this bug customers must turn off “detailed only” for all columns and now they’re visible on all views. Its a pretty janky customer experience.

Plus, fixing this is not hard. It’s a recent regression in another PR that got the logic wrong.

**Comment by Tony-metabase** [comment] 2023-08-21 08:11
Increased priority

**Comment by EmmadUsmani** [comment] 2023-09-19 17:04
https://github.com/metabase/metabase/assets/37751258/969af491-7562-4bd8-a5cf-2b5f496d80bd

@krschacht I tried reproducing on the lastest commit on master, seems to be working fine now. Upgrading your instance to the latest version (47.2) should fix it. Closing the issue for now, but if it persists on 47.2 feel free to reopen.

**Closed by EmmadUsmani** 2023-09-19 17:04 UTC
Labels: Type:Bug, Priority:P2, Administration/Metadata & Sync, Administration/Table Metadata, .Team/PixelPolice :police_officer:
