### ISSUE TITLE
Multiple questions on the chart to use the same axes

### ISSUE THREAD

**Issue by vkovalskiy** [metabase/metabase#2498] opened 2016-05-01 14:47 UTC
Having the ability to use multiple Y-axes for a couple of questions is great. But sometimes the ability to use the SAME Y-axis would be much more viable.

**Comment by robinfrick** [comment] 2016-05-03 16:07
I want to reiterate that it is very frustrating to combine two charts that have the same kind of data for example one has goals and the other one actual values and they are displayed with different Y axis although the values should be comparable and are very similar (like one having a max value of ~200 the other ~150). This has been requested in #2317 and #2178 as well.

I hope this can get some kind of priority :)

**Comment by tlrobinson** [comment] 2016-08-13 00:18
I believe this was resolved by the chart settings branch #2931, released in 0.19.0. Also, duplicate of #2317

**Closed by tlrobinson** 2016-08-13 00:18 UTC
Labels: Visualization/Chart Settings
