### ISSUE TITLE
Visualize GeoJSON on Map stored in MongoDB

### ISSUE THREAD

**Issue by aindeev** [metabase/metabase#2578] opened 2016-05-10 23:18 UTC
Currently we can set latitude and longitude fields in Metabase and then visualize those on a pin map.
Unfortunately the storage format of geographical data for Metabase is often in GeoJSON format

Example of how a Point would be stored

```json
{
  "type": "Point",
  "coordinates": [-123.1529998779297, 49.26988983154297]
}
```

There is currently no way to indicate that that `coordinates[1]` is Latitude and `coordinates[0]` is Longitude. 

It would be fantastic if Metabase could detect GeoJSON formatted data and allow us to display it on the map directly 😄

**Comment by camsaul** [comment] 2016-05-10 23:20
Duplicate of #1331

**Closed by camsaul** 2016-05-10 23:20 UTC
Labels: Database/Mongo
