### ISSUE TITLE
Changing filters on Simple question drops anything after first aggregation

### ISSUE THREAD

**Issue by kinerix** [metabase/metabase#14193] opened 2020-12-24 09:41 UTC
https://user-images.githubusercontent.com/4180027/103077841-0b595600-45ea-11eb-98ac-5c820fb57041.mp4

**To Reproduce**
Please, watch the video

**Expected behavior**
The number and content of columns will remain according to the original formulas

**Information about your Metabase Installation:**
Google Chrome 87.0.4280.88, (64 bit)
PostgreSQL 11.7 (Ubuntu 11.7-2.pgdg16.04+1)
Metabase 0.37.4

**Severity**
Users get confused and break reports.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2020-12-24 10:39
Likely a duplicate of #11957

Reproduce:
1. Create a Notebook query like this with a filter before aggregated section and Custom Column after aggregation:
![image](https://user-images.githubusercontent.com/1447303/103083245-3c328e80-45dc-11eb-939e-07a3dde871ba.png)
2. Change filter in Simple GUI will drop the Custom Column after aggregated section

Workaround: Change filter in Notebook will keep the Custom Column

**Comment by kinerix** [comment] 2020-12-24 19:53
Change filter in Notebook can advanced user, but most users are confused. Reports should be as easy to manage as possible. This is critical.

**Comment by kinerix** [comment] 2021-01-20 10:00
The bug is reproducible on the latest version, please watch the video.

https://user-images.githubusercontent.com/4180027/105158809-cf051100-5b27-11eb-87ae-d6d9ea4a5e07.mp4

**Comment by flamber** [comment] 2021-01-20 10:04
@kinerix Until the issue is closed with a milestone, then it's not fixed.

**Comment by kinerix** [comment] 2021-01-20 16:19
Ok, thank you!

**Closed** 2022-09-16 10:55 UTC
Labels: Type:Bug, Priority:P2, .Correctness, .Frontend, Querying/GUI, .Reproduced
