### ISSUE TITLE
Models will be repeated in collections with the same name

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#28105] opened 2023-02-06 22:29 UTC
**Describe the bug**
We have a "model" folder under several top-level collections. Each of them has different models for different business units. 
When starting a question, browsing to one of the Model sub-collection is showing models from all Model sub-collections. 

**Logs**
n/a

**To Reproduce**
1. Create several collections with the same name and add different Metabase models
2. Create a new question and browse to one of the created collections. All models are repeated instead of displaying the ones that should be there

**Expected behavior**
Only models from the selected collection should show. 

**Screenshots**
n/a

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome
- Metabase version: master

**Severity**
Still works but just confusing

**Additional context**
n/a

**Comment by paoliniluis** [comment] 2023-02-08 14:29
@maxzheng I can't visually see what you're seeing, can you put some screenshots? I see models inside collections they belong to

**Comment by maxzheng** [comment] 2023-02-28 22:47
@paoliniluis See screenshot below. It shows several models in Models collection. If you click on Revenue -> Models, it will show the same models list or any other Models folder in other collections as all models are merged into a single list for the same collection name "Models". 
<img width="714" alt="Screenshot 2023-02-28 at 2 43 17 PM" src="https://user-images.githubusercontent.com/9684260/221998797-45236149-e349-44db-9350-d3c32c82522e.png">

**Comment by paoliniluis** [comment] 2023-03-01 19:03
I just checked and this seems to be a dupe of https://github.com/metabase/metabase/issues/24660

**Closed by paoliniluis** 2023-03-01 19:03 UTC
Labels: Type:Bug, Priority:P2, Organization/Collections, .Frontend, Querying/Models
