### ISSUE TITLE
Percentage Calculations result in only whole-number results

### ISSUE THREAD

**Issue by sharedphysics** [metabase/metabase#11826] opened 2020-01-29 21:36 UTC
**Describe the bug**
When I try to do percentage calculations in the UI (for example: `100*sum(A)/sum(b)` or some variations thereoff, I keep getting only whole numbers as a result. Additionally, they seem to always round down, so anything under 1 ends up displaying as 0.
![image](https://user-images.githubusercontent.com/5796884/73399086-a3549f80-42b4-11ea-8b8a-110e68949367.png)
![image](https://user-images.githubusercontent.com/5796884/73399257-e9a9fe80-42b4-11ea-96a9-44e90530e478.png)

Changing the number of decimals counted to doesn't help, neither does multiple the numbers, neither does formatting the number as a percentage. Modifying the data types in data modeling doesn;t seem to help either, I keep getting only-whole-number results. Any clue as to why? 

**Information about your Metabase Installation:**
0.33.6 but I've had this issue in previous versions as well. 
Postgres/Redshift database. 
H2 backend.
Chrome
Running on Elastic Beanstalk 

**Severity**
Low-ish, though it comes up very often and is annoying.

**Comment by sbelak** [comment] 2020-01-29 21:50
Duplicate of #8783

**Closed by sbelak** 2020-01-29 21:50 UTC
Labels: .Needs Triage, Type:Bug
