### ISSUE TITLE
Humanization of column names is way too aggressive

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#9908] opened 2019-05-07 20:25 UTC
On sql queries, things get kind crazy 
<img width="474" alt="Screen Shot 2019-05-07 at 1 24 36 PM" src="https://user-images.githubusercontent.com/107439/57330657-8c896f80-70cb-11e9-8be5-6269fa0725ae.png">

**Comment by ogeagla** [comment] 2019-06-17 17:25
Some other good cases that need fixing can be found here: https://github.com/metabase/metabase/issues/7606

**Comment by tlrobinson** [comment] 2019-06-17 17:54
I'm going to close this as a duplicate of #7606

**Closed by tlrobinson** 2019-06-17 17:54 UTC
Labels: Bug, Priority/P1, Query Builder/Native
