### ISSUE TITLE
Question based on saved question: field picker for join condition displays wrong table name

### ISSUE THREAD

**Issue by sbi-c** [metabase/metabase#25913] opened 2022-10-13 14:13 UTC
**Describe the bug**

Join condition field picker shows wrong table name when joining a saved question's results to another table. Results are correct, though.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
I have a very basic saved question named Question1 that summarizes a single table ("Articles") by counting rows for each ID (a silly question of course, but this is a minimal test case). 

![Question1](https://user-images.githubusercontent.com/115717095/195621570-74ed9792-87f5-4f62-8ce7-da9453600a46.png)

Then I create another question based on this saved question (click on New > Question > Saved Questions > Question1), and join the results of the first question to the Articles table again. Now the field picker for the join condition displays correctly for Question1 fields, but the header is off for the Articles table:

![Question2](https://user-images.githubusercontent.com/115717095/195621617-8cf1126c-b2c2-4aac-958f-aa1a3ea2b73b.png)

When clicking "Visualize", the results are correct, though.

**Expected behavior**
Field picker headline should be "Articles", not "Question1". Also, the blue bubbles representing the field names after selection is complete both display "Question1 ID", where the second one should read "Articles ID".

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "de",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "5.10.0-18-amd64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.5.15-MariaDB-0+deb11u1"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-09-29",
      "tag": "v0.44.4",
      "branch": "release-x.44.x",
      "hash": "382d728"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**

This is confusing for my non-technical users, but not a show stopper. I could work around it by replacing the saved question with a database view.

**Comment by flamber** [comment] 2022-10-13 14:16
Duplicate of #19893

**Closed by flamber** 2022-10-13 14:16 UTC
Labels: Type:Bug, .Needs Triage
