### ISSUE TITLE
Large pivoted tables generate massive amount of warnings

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#23158] opened 2022-06-05 15:24 UTC
**Describe the bug**
When we render massive cards on dashboards that log to the console lots of warnings, performance will be downgraded severely. In fact, the queries finish quickly, but the frontend is not able to render them since it's dumping warnings massively.

**Logs**
FE logs
```
TypeError: Cannot read properties of undefined (reading 'fields')
    at app-main.bundle.js?1bd38c0dcf86e221ad70:2:4467706
    at re (app-main.bundle.js?1bd38c0dcf86e221ad70:2:4467821)
    at F (app-main.bundle.js?1bd38c0dcf86e221ad70:2:510228)
    at app-main.bundle.js?1bd38c0dcf86e221ad70:2:531755
    at Array.flatMap (<anonymous>)
    at e.value (app-main.bundle.js?1bd38c0dcf86e221ad70:2:531727)
    at i.value (app-main.bundle.js?1bd38c0dcf86e221ad70:2:4840970)
    at app-main.bundle.js?1bd38c0dcf86e221ad70:2:4837616
    at i.value (app-main.bundle.js?1bd38c0dcf86e221ad70:2:775748)
    at app-main.bundle.js?1bd38c0dcf86e221ad70:2:777989
```

**To Reproduce**
With the sample database
1) create the following question via GUI: Orders -> summarize: cummulative sum of Quantity, standard deviation of discount; grouped by user-> city, click on visualize to render it as a table
2) then click on the chart setting-> pivot the table
3) add the pivoted table to the dashboard 3 times
4) see the lag, your browser is getting obliterated since the console is generating massive amounts of warnings

**Expected behavior**
Don't generate that amount of errors

**Screenshots**
![performance_regression](https://user-images.githubusercontent.com/1711649/172057748-72e4ef12-5d23-4149-87f4-e8528e0ba792.gif)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop OS 22.04
- Your databases: Postgres 14.2
- Metabase version: 1.43.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14.2

**Severity**
Severe, if you have those pivoted tables in the dashboard, even if they're not rendered entirely you'll have a huge performance impact

**Additional context**
NA

**Comment by flamber** [comment] 2022-06-05 17:46
This is basically a dupe of #11739, as noted a few years ago https://github.com/metabase/metabase/pull/11305#issuecomment-565196011
Moderns browser shouldn't care much about console messages if the developer console is closed.
The performance problem comes from the many cells in the tables, which isn't handled great.

**Closed** 2022-06-06 14:18 UTC
Labels: Type:Bug, Priority:P1, .Performance, .Frontend, Visualization/Tables/old-pivoted
