### ISSUE TITLE
event_timestamp hovering over shows "UTC" in query builder even though localisation settings set the timezone to America/Mexico City 

### ISSUE THREAD

**Issue by EvaSchreyer** [metabase/metabase#27335] opened 2022-12-19 18:43 UTC
Hi, we use Metabase 0.45.1 sitting ontop a Google BigQuery database. we get event_timestamps in UTC. 
We changed our localisation settings in Metabase to the timezone America/Mexico City, although hovering over the event_timestamp column in query builder always shows UTC, what is confusing for users. 
<img width="304" alt="grafik" src="https://user-images.githubusercontent.com/28557318/208496947-a20b0d0f-e1d9-47b5-8eee-048f00f91625.png">
I would expect the hovering over to show the correct timezone based on the localisation settings.

**Comment by flamber** [comment] 2022-12-19 18:50
Duplicate of #12816

**Closed by flamber** 2022-12-19 18:50 UTC
Labels: Type:Bug, .Needs Triage
