### ISSUE TITLE
Download/Export to .xlsx generates invalid xlsx file

### ISSUE THREAD

**Issue by 1t5j0y** [metabase/metabase#13282] opened 2020-09-21 10:16 UTC
**Describe the bug**
Exporting any report to .xlsx generates an invalid .xlsx file which Excel etc. cannot open. On checking further, the downloaded .xlsx file in fact contains json content with error details.

**Logs**
Server logs:
```
[eb9d687a-226d-4e4a-9e75-51d842605800] 2020-09-21T15:12:33+05:30 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: null
{:database_id 53,
 :started_at #t "2020-09-21T09:42:32.980Z[Zulu]",
 :via
 [{:status :failed,
   :class org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException,
   :error
   "Fail to save: an error occurs while saving the package : The part /docProps/app.xml failed to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@4266ff88",
   :stacktrace
   ["org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:595)"
    "org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1539)"
    "org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:227)"
.
.
```

**To Reproduce**
1. Go to any question
2. Click on 'Download full results' icon at the bottom of the page and select the .xlsx option.
3. File gets downloaded succesfully
4. File cannot be opened by Excel

**Expected behavior**
The downloaded .xlsx file should contain the report data and Excel should be able to open it.

**Screenshots**
Excel error when attempting to open the .xlsx file:
![Metabase - report export not opening](https://user-images.githubusercontent.com/54208632/93754454-63657280-fc1f-11ea-8b9c-85b7ce127f1a.JPG)

JSON content in the xlsx file:
![image](https://user-images.githubusercontent.com/54208632/93754424-50eb3900-fc1f-11ea-8e46-94f350a98d79.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox 80.0.1
- Your operating system: Ubuntu 20.04
- Your databases: Postgres
- Metabase version: 0.36.2
- Metabase hosting environment: AWS EC2
- Metabase internal database: (Postgres)

**Severity**
Blocking some users but managing to workaround with the csv download option.

**Additional context**
- JSON and CSV download options generate the data correctly.
- Noticed #13271 and #10803 but I am observing this issue for records with no timestamps in them and with low number of total records (5-10)
- Users first noticed this last Wednesday (Sep 16)

**Comment by flamber** [comment] 2020-09-21 10:34
Hi @1t5j0y 
Can you provide a sample table to reproduce this with?
Please provide the full stacktrace.

**Comment by 1t5j0y** [comment] 2020-09-21 10:45
Ran this simple query to generate a sample row as my dataset: `select 'key' as key, 'value' as value;`

[Downloaded xlsx file](https://github.com/metabase/metabase/files/5254818/query_result_2020-09-21T10.41.51.124Z.xlsx)

[Stacktrace](https://github.com/metabase/metabase/files/5254819/13282-stacktrace.txt)

**Comment by flamber** [comment] 2020-09-21 11:05
@1t5j0y 
Please post "Diagnostic Info" from Admin > Troubleshooting.
I cannot reproduce on 0.36.2, 0.36.6 or `master` with H2, MySQL or Postgres on AdoptOpenJDK 11
But I am seeing some warnings, which makes me think that it is related to Java and some versions might fail harder than others.
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.poi.util.DocumentHelper (file:/home/flamber/metabase/metabase.jar) to method com.sun.org.apache.xerces.internal.util.SecurityManager.setEntityExpansionLimit(int)
WARNING: Please consider reporting this to the maintainers of org.apache.poi.util.DocumentHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
09-21 12:55:19 DEBUG middleware.log :: POST /api/card/288/query/xlsx 202 [ASYNC: completed] 1.2 s (6 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (1 idle, 0 queued) (58 total active threads) Queries in flight: 0 (0 queued)
```

**Comment by 1t5j0y** [comment] 2020-09-21 11:11
We're on Java 1.8.

Diagnostic Info:
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_201-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_201",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.201-b09",
    "os.name": "Linux",
    "os.version": "4.9.76-3.78.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "Zulu"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.36.2",
      "date": "2020-07-31",
      "branch": "release-0.36.x",
      "hash": "13f0225"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

**Comment by flamber** [comment] 2020-09-21 11:14
@1t5j0y That's a very old version of Java - you should really consider upgrading. I would recommend AdoptOpenJDK:
https://github.com/metabase/metabase/blob/master/docs/operations-guide/java-versions.md

**Comment by 1t5j0y** [comment] 2020-09-21 12:18
Thanks for the Java warnings you noticed @flamber. We'll look into using a newer version of Java.

Came across [this thread](https://bz.apache.org/bugzilla/show_bug.cgi?id=62151) on the POI project that deals with this issue. Perhaps updating the POI version in Metabase will resolve this issue?

**Comment by flamber** [comment] 2020-09-21 12:25
@1t5j0y Perhaps, but since I cannot reproduce on AdoptOpenJDK 11, then I don't know if that will fix the stacktrace for Java 8.
We haven't updated POI because too many dependencies required updating too https://github.com/metabase/metabase/pull/13133#issuecomment-683074167

**Comment by 1t5j0y** [comment] 2020-09-22 09:37
Looked further into this and found there was a file system usage issue on our server. Fixing that and a restart of Metabase resolved this issue so this is probably related to #13159 though the error message in this case was different.

**Comment by flamber** [comment] 2020-09-22 09:41
Thanks for the feedback. I guess that there wasn't even enough space to write the tiny `/docProps/app.xml`, whereas #13159 was able to write that file, but not enough space to write all the result data.
Closing in favor of #13159

**Closed by flamber** 2020-09-22 09:41 UTC
Labels: Operation/, Priority:P2, Reporting/Export, Type:Bug
