### ISSUE TITLE
Friendly Column names not shown anymore

### ISSUE THREAD

**Issue by gvisniuc** [metabase/metabase#10819] opened 2019-09-06 08:01 UTC
Hi there,

I’m currently running Metabase **v0.33.1** and have noticed that the column names declared as aliases in SQL (i.e. “my_column”) are not following the **FRIENDLY TABLE AND FIELD NAMES** setting anymore, and do not replace underscores with spaces.

I tried finding any issues or traces of this change as well, so I’m not sure if this is a bug or intended behaviour.

![7b616e6b1d8e1a943dd8b2a2836cc67f16a8009e](https://user-images.githubusercontent.com/1614747/64411275-228ad200-d08d-11e9-9d87-286dd843a301.png)

Your browser and the version: Chrome 76.x
Your operating system: macOS Mojave
Your databases: Redshift
Metabase version: 0.33.1
Metabase hosting environment: Official Metabase Docker image running in Kubernetes.
Metabase internal database: AWS RDS Postgres

⬇️ Please click the 👍 reaction instead of leaving a +1 or 👍 comment

**Comment by flamber** [comment] 2019-09-06 08:03
Pinging @camsaul because of PR #10196, but I cannot find the reason behind it.

**Comment by gvisniuc** [comment] 2019-09-10 07:06
Also just a small note even when declaring a title case alias such as `My Alias` the column names will be transformed to lowercase as well.

**Comment by salsakran** [comment] 2019-10-06 00:49
The intended behavior is that we respect your aliases and don't mess with them, since the friendly names was misfiring more often than not with raw sql.

The lowercasing is a bug and marking it as such

**Comment by ismayil22** [comment] 2019-10-07 23:49
Guys Hi,

I have related question regarding column names, but not sure is it bug or should work like intended. Since you removed "friendly column names", as I see in v0.33.3, I had to fix all column names using "Settings->Table options->Column title. 

Thus adjusted column names as needed. Problem is that they **do not reflect** on Pulses now (see second screenshot). It seems it is bug , and they should be adjusted on Pulses too. Am I right?

![image](https://user-images.githubusercontent.com/26248319/66356853-8c381d80-e964-11e9-9c46-312b2cd9bb38.png)

![image](https://user-images.githubusercontent.com/26248319/66357002-12ecfa80-e965-11e9-887a-51d0fb63d565.png)

**Comment by ismayil22** [comment] 2019-10-11 12:23
@flamber Hi, can you please give me approx. time when above issue will be fixed (I hope).
1 week? 1 month? 1 year?

Or maybe easier just revert above mentioned by you PR :) https://github.com/metabase/metabase/issues/10819#issuecomment-528755633

All Pulses now looks weird, and it will take eternity to fix all these column names manually in all existing pulses.

**Comment by flamber** [comment] 2019-10-11 15:45
@ismayil22 Did you see the comment by @salsakran? I don't think this will be reverted. The lower-casing is a bug, but cannot give you a time-frame, there's 2000 other open issues.
Pulses doesn't read the formatting from the visualization, which is why the column name doesn't change in the pulse, when you edit it in table options - there's an issue open on that #8258.

**Comment by walterl** [comment] 2020-03-13 23:51
I'm not seeing the lower-casing issue on current `master` (0.35.0-RC @ ):

**Comment by walterl** [comment] 2020-03-13 23:52
I'm not seeing the lower-casing issue on current `master` (0.35.0-RC @ fb1ed0d):

![image](https://user-images.githubusercontent.com/23798/76669896-67d91080-6596-11ea-8ac0-7661f1c0bfdb.png)

Closing, since it appears to have been fixed already.

**Closed by walterl** 2020-03-13 23:52 UTC
Labels: Priority:P2, Querying/Native, Type:Bug
