### ISSUE TITLE
Adding filters sometimes flips the x-axis data and the group-by data

### ISSUE THREAD

**Issue by fferguso11** [metabase/metabase#11218] opened 2019-10-25 14:19 UTC
**Describe the bug**
When using Metabase, I have some attribute 'A' along the x axis, and am grouping by attribute 'B' to have multiple lines of data shown on the graph. However, if I place a filter on 'B' to limit the number of lines shown, Metabase often changes A for B on the axes. 

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to Metabase Dashboard for Respective Firm 
2. Click 'Ask Question'
3. Provide a metric and group by two variables
4. Add a filter on the variable currently being grouped by (so not the x-axis)
5. The variables on the x axis and being grouped on will then flip (although this doesn't seem to happen every time)

**Expected behavior**
Would simply expect the x axis and grouping variables to remain as the filter is added

**Screenshots**
![image](https://user-images.githubusercontent.com/44494546/67578459-653a6380-f73a-11e9-9e14-5d65bd3f6c4e.png)
Above is the data flipping after a filter set on 'Series Day'

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: 
Version 77.0.3865.120 (Official Build) (64-bit)
- Your operating system: 
OS X 10.14.6
- Your databases: 
PostgreSQL
- Metabase version: 
v0.33.4
- Metabase hosting environment: 

- Metabase internal database: 
PostgreSQL

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Simply annoying - a bit of playing around tends to get round the problem but there doesn't seem much logic behind what solves the issue.
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**
-

**Comment by Swift-Jr** [comment] 2019-10-25 16:03
Voting on this - also happening for our team

**Comment by flamber** [comment] 2019-10-25 18:39
@fferguso11 @Swift-Jr I don't think I completely understand the problem. Could you provide more examples of how it looked before and after?
Is it possible to reproduce this using the Sample Dataset? That would be the best, since we have all access to the same data.

**Comment by mazameli** [comment] 2019-11-15 22:50
I think this is a bug with the auto visualization logic: I believe it tries to put the higher cardinality dimension on the x-axis, and use the lower cardinality one as the series breakout. So maybe what's going on is that adding a filter is causing Metabase to reevaluate the state of things and therefore switching which column is used for the x-axis versus the breakout.

Seems like it should make that evaluation the first time the query is visualized, and also whenever breakouts are changed, but not when a filter is added or modified.

**Comment by flamber** [comment] 2019-11-15 23:01
@mazameli I guess it's related to #10957 then?

**Comment by flamber** [comment] 2020-02-06 21:19
When there's a Native question with a filter on a dashboard, then it always shows table viz, when the filter is active and clicking the card title. Looking at Maz's https://github.com/metabase/metabase/issues/11218#issuecomment-554559729, it seems like that would be fixed, when this issue is fixed (if not, I can create a separate issue).
From the forum: https://discourse.metabase.com/t/question-visualization-config-is-lost-when-navigate-from-dashboard/8690

**Comment by Tbodewes** [comment] 2020-03-25 11:38
We have a problem that relates to this according to Flamber. It is the exact problem described here https://discourse.metabase.com/t/question-visualization-config-is-lost-when-navigate-from-dashboard/8690 

I've included more details about it in this comment https://github.com/metabase/metabase/issues/11960#issuecomment-603787084

We are running Metabase V0.34.3

**Comment by flamber** [comment] 2020-05-14 15:26
PR #12476 (included in 0.36.0) fixes the issue of visualization is "lost" (changed to table), when navigating from dashboard to question.

I still haven't been able to reproduce this issue, so I don't know it also fixes that.
Related #8623

**Comment by vvaezian** [comment] 2020-06-25 18:24
@flamber To reproduce:
Simple Question > Sample Dataset > Average of PRICE Group by CREATED_AT (by year) and CATEGORY

![bug1](https://user-images.githubusercontent.com/15974735/85775676-d6b92000-b6d4-11ea-99c2-df16e9a7d031.png)

Now Choose Filter > CATEGORY. Choose one of the values (here I chose "Doohickey"):

![bug2](https://user-images.githubusercontent.com/15974735/85777267-52679c80-b6d6-11ea-9df7-1fdfef749981.png)

The expected behavior is to look like the first image, but with only "Doohickey" at the top of the chart. 
This issue is specially problematic in dashboards, when the users can filter the data.

**Comment by flamber** [comment] 2020-06-25 18:39
@vvaezian The single legend is #4995. But your example doesn't flip the x-axis - it doesn't even flip the y-axis, just gives an incorrect name to "Y-axis label"
![image](https://user-images.githubusercontent.com/1447303/85779204-a9479300-b723-11ea-8f5a-d016ec73a323.png)

**Comment by vvaezian** [comment] 2020-06-25 19:08
@flamber  Sorry, I don't know why I misread it as y-axis.
I was experiencing the issue I mentioned, and after searching came to this issue and thought it is related.
I couldn't find a ticket for the part about wrong label. Do you know of any? If not I'll create a new one.

**Comment by flamber** [comment] 2020-06-25 19:28
@vvaezian I don't recall seeing one, so create a new - and please reference #4995, since it's related.

**Comment by flamber** [comment] 2020-08-25 20:01
Closing as fixed in 0.36.0 - if anyone is still seeing this, then please provide steps-to-reproduce with Sample Dataset.

**Closed by flamber** 2020-08-25 20:01 UTC
Labels: Priority:P2, Type:Bug, Visualization/Chart Settings
