### ISSUE TITLE
Syntax error when trying to migrate H2 to Postgres

### ISSUE THREAD

**Issue by ArloL** [metabase/metabase#5425] opened 2017-07-05 11:27 UTC
- Your browser and the version: Firefox 54.0.1
- Your operating system: Windows 8.1 Pro
- Your databases: Postgres
- Metabase version: 0.24.2
- Metabase hosting environment: openSUSE Leap 42.1
- Metabase internal database: H2 -> Postgres

I am trying to follow the [steps for migrating the H2 database to Postgres](http://www.metabase.com/docs/v0.24.2/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres). Sadly I get the following error message. It is reproducible. Please let me know if I can provide more information.

~~~
kevdev34:/opt/metabase # systemctl stop metabase.service
kevdev34:/opt/metabase # cp metabase.db.mv.db backup
kevdev34:/opt/metabase # export MB_DB_TYPE=postgres
kevdev34:/opt/metabase # export MB_DB_DBNAME=metabase
kevdev34:/opt/metabase # export MB_DB_PORT=5432
kevdev34:/opt/metabase # export MB_DB_HOST=kevdb05.herbrand.rz.evosec.de
kevdev34:/opt/metabase # export MB_DB_USER=postgres
kevdev34:/opt/metabase # export MB_DB_PASS=somepassword
kevdev34:/opt/metabase # java -jar /opt/metabase-0.24.2.jar load-from-h2 /opt/metabase/metabase.db.mv.db
07-05 12:08:40 INFO metabase.util :: Loading Metabase...
07-05 12:08:47 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓
07-05 12:09:02 INFO metabase.db :: Verifying postgres Database Connection ...
07-05 12:09:02 DEBUG metabase.driver :: Registered driver :postgres 🚚
07-05 12:09:02 INFO metabase.db :: Verify Database Connection ...  ✅
07-05 12:09:02 INFO metabase.db :: Running Database Migrations...
07-05 12:09:02 INFO metabase.db :: Setting up Liquibase...
07-05 12:09:03 INFO metabase.db :: Liquibase is ready.
07-05 12:09:03 INFO metabase.db :: Checking if Database has unrun migrations...
07-05 12:09:06 INFO metabase.db :: Database has unrun migrations. Waiting for migration lock to be cleared...
07-05 12:09:06 INFO metabase.db :: Migration lock is cleared. Running migrations...
07-05 12:10:00 INFO metabase.db :: Database Migrations Current ...  ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
Temporarily disabling DB constraints...
org.postgresql.util.PSQLException: ERROR: syntax error at or near "CONSTRAINT"
  Position: 36
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:365)
        at clojure.java.jdbc$db_do_execute_prepared_statement$fn__10865.invoke(jdbc.clj:784)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:637)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:783)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:778)
        at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:814)
        at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:795)
        at clojure.java.jdbc$execute_BANG_$execute_helper__10908.invoke(jdbc.clj:961)
        at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:963)
        at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:943)
        at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:954)
        at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:943)
        at metabase.cmd.load_from_h2$disable_db_constraints_COLON_postgres_BANG_.invokeStatic(load_from_h2.clj:155)
        at metabase.cmd.load_from_h2$disable_db_constraints_COLON_postgres_BANG_.invoke(load_from_h2.clj:151)
        at metabase.cmd.load_from_h2$disable_db_constraints_BANG_.invokeStatic(load_from_h2.clj:170)
        at metabase.cmd.load_from_h2$disable_db_constraints_BANG_.invoke(load_from_h2.clj:168)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__39488.invoke(load_from_h2.clj:214)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:613)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:629)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:212)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:205)
        at clojure.lang.Var.invoke(Var.java:379)
        at metabase.core$load_from_h2.invokeStatic(core.clj:210)
        at metabase.core$load_from_h2.invoke(core.clj:203)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.core$apply.invoke(core.clj:641)
        at metabase.core$run_cmd$fn__40258.invoke(core.clj:264)
        at metabase.core$run_cmd.invokeStatic(core.clj:264)
        at metabase.core$run_cmd.doInvoke(core.clj:263)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$apply.invoke(core.clj:641)
        at metabase.core$_main.invokeStatic(core.clj:278)
        at metabase.core$_main.doInvoke(core.clj:274)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at metabase.core.main(Unknown Source)
Command failed with exception: ERROR: syntax error at or near "CONSTRAINT"
  Position: 36
~~~

**Comment by mnzt** [comment] 2017-07-14 09:16
Same issue with the following postgres version:
```postgres (PostgreSQL) 8.4.20```

Will try to post more system information when I get it.

**Comment by camsaul** [comment] 2017-07-14 17:41
@ArloL what's your Postgres version? I don't think we've ever tested against Postgres 8.x because 9 has been out for *seven years* (and 8.x was EOL'ed before we even started writing Metabase)

@salsakran I think this is probably just an issue with Postgres 8. It sounds like Liquibase isn't generating SQL it accepts.

**Comment by camsaul** [comment] 2017-07-18 00:04
@mnzt @ArloL It appears that several of the libraries (e.g. Liquibase) we rely on don't support Postgres 8 (since, as mentioned above, Postgres 9 has been out since 2010 -- seven years -- and 8 was EOL'ed before we even started developing Metabase). So unfortunately I don't think it is technically feasible for us to add support for Postgres 8.

@metabase/core-developers and objection to me closing this as Can't Fix?

**Comment by salsakran** [comment] 2017-07-18 00:07
@mnzt  + @ArloL 

I'm with Cam here. While we want Metabase to work with as many databases and versions as possible, versions that were EOL'd before our project started are a little too much of a stretch for us. We'd be open to a PR that helps us on this, but I don't think we have the bandwidth for this. 

I'd suggest you upgrade a recent version of PostgreSQL or MySQL. Alternatively, the embedded DB should also work well for you.

**Comment by camsaul** [comment] 2017-07-18 00:31
Closing as Can't Fix

**Closed by camsaul** 2017-07-18 00:31 UTC
Labels: Bug, Can't Fix, Priority/P2, Running Metabase

**Comment by ArloL** [comment] 2017-07-19 08:24
I figured it out. I am using PostgreSQL 9.2 which does not support altering foreign keys https://www.postgresql.org/docs/9.2/static/sql-altertable.html vs https://www.postgresql.org/docs/9.4/static/sql-altertable.html

**Comment by facundofarias** [comment] 2019-02-05 11:44
Still reproducing it with `psql (PostgreSQL) 9.2.24` :|
