### ISSUE TITLE
Pass confirm environment variables via a file

### ISSUE THREAD

**Issue by naxIO** [metabase/metabase#4846] opened 2017-04-24 13:45 UTC
I'm running metabase as plain jar and wondered how do I pass it a config file if I dont want to write all the config into env? Is it even possible?

So instead of:
```
export MB_DB_TYPE=h2
export MB_DB_FILE=/the/path/to/my/h2.db
java -jar metabase.jar
```

I want / seek something like 
```
ExecStart=/usr/bin/java -jar /home/ubuntu/metabase.jar -config /path/to/config
```
Or any other appropriate way.

Thanks

**Comment by salsakran** [comment] 2017-04-24 17:55
We don't currently support that. You can mimic it by putting all the exports in a file and doing a 
`source file_with_exports.sh && java -jar metabase.jar`

**Comment by camsaul** [comment] 2017-11-15 02:03
Duplicate of #2052

**Closed by camsaul** 2017-11-15 02:03 UTC
Labels: Proposal, Running Metabase
