### ISSUE TITLE
Dashboard Filters Unmodifiable After Upgrade from v48 to v49

### ISSUE THREAD

**Issue by tomy137** [metabase/metabase#42379] opened 2024-05-08 09:57 UTC
### Describe the bug

After upgrading from version v0.48.8 to version v0.49.8, I've encountered a peculiar issue with the dashboard filters. 

In read mode, the filters function correctly; I can select items from the list, and the questions filter as expected. However, when I attempt to modify the filters, an error message stating "unknown field" appears.

Furthermore, when I try to forcefully modify the filters, no changes are displayed. Additionally, the following error message is logged in the browser console: `Uncaught (in promise) Error: No matching clause - [metabase.lib.util.js:11:115](webpack:///target/cljs_release/metabase.lib.util.js)`.

![metabase-filter-bug](https://github.com/metabase/metabase/assets/2952029/3087b062-769e-48e9-9791-eefbc7f78685)

This issue persists even when trying to add new filters.

Essentially, I am unable to modify or add any filters.

### To Reproduce

Not sure about the repeatabily but, this is what I've done : 
- Set my dashboard with filters up on v0.48.8  
- Upgrade to v0.49.8
- Try to modify existing filters

I tried to downgrade to v0.48 to selectively upgrade version to version but can't manage to succesfully downgrade...

### Logs

No server-side logs when the error appear. Seems to be front-side specifics. 

Browser logs : 
Some of thoses before click : 
```
DashCardCardParameterMapper.tsx:84 [re-reselect] Invalid cache key "undefined" has been returned by keySelector function.
h @ index.js:98
(anonymous) @ DashCardCardParameterMapper.tsx:84
r @ wrapMapToProps.js:47
r.mapToProps @ wrapMapToProps.js:56
r @ wrapMapToProps.js:47
(anonymous) @ selectorFactory.js:19
(anonymous) @ connect.js:313
u @ use-sync-external-store-shim.production.min.js:10
l @ connect.js:337
o6 @ react-dom.production.min.js:153
iF @ react-dom.production.min.js:175
iN @ react-dom.production.min.js:175
iD @ react-dom.production.min.js:174
l @ react-dom.production.min.js:268
aH @ react-dom.production.min.js:246
(anonymous) @ react-dom.production.min.js:246
aW @ react-dom.production.min.js:246
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
on @ react-dom.production.min.js:122
oi @ react-dom.production.min.js:123
oo @ react-dom.production.min.js:122
Y @ react-dom.production.min.js:287
TU @ react-dom.production.min.js:68
```

After click :
```
Uncaught (in promise) Error: No matching clause: 
    BV metabase.lib.util.js:11
    71733 metabase.lib.convert.js:22
    h cljs.core.js:509
    k1 metabase.lib.card.js:7
    6242 metabase.lib.card.js:11
    v cljs.core.js:510
    e metabase.lib.metadata.calculation.js:40
    6242 metabase.lib.card.js:8
    v cljs.core.js:510
    e metabase.lib.metadata.calculation.js:43
    c metabase.lib.stage.js:17
    c metabase.lib.stage.js:22
    91877 metabase.lib.stage.js:23
    v cljs.core.js:510
    e metabase.lib.metadata.calculation.js:43
    U_ metabase.lib.metadata.calculation.js:44
    d_ metabase.lib.metadata.calculation.js:7
    e_ metabase.lib.metadata.calculation.js:8
    t metabase.lib.metadata.calculation.js:43
    e metabase.lib.filter.js:66
    e4 cljs.core.js:71
    e7 cljs.core.js:71
    g cljs.core.js:269
    t metabase.lib.core.js:80
    filterable_columns metabase.lib.js.js:48
    d_ metabase.lib.metadata.calculation.js:7
    e_ metabase.lib.metadata.calculation.js:8
    filterable_columns metabase.lib.js.js:47
    tn filter.ts:73
    f mapping-options.ts:163
    t utils.ts:69
    o utils.ts:102
    eS parameters.js:129
    Redux 2
    eS parameters.js:126
    Redux 3
    g DashCardCardParameterMapper.tsx:130
    onChange DashCardCardParameterMapper.tsx:290
    onChange ParameterTargetList.jsx:28
    handleChange AccordionList.jsx:247
    onClick AccordionListCell.jsx:149
    React 12
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
metabase.lib.util.js:11:115

```

### Information about your Metabase installation

```JSON
- Firefox 122.0.1 OR Brave / Chromium 124.0.6367.118 (Same behaviour)
- Metabase v0.49.8 - Docker image metabase/metabase:v0.49.8
```

### Severity

blocking

### Additional context

I already try to : 
- Clear cache (Metabase + Browser)
- discard_values / sync_schema
- force rename colomn in model metadata

**Comment by calherries** [comment] 2024-05-08 17:31
I can't reproduce this using v0.49.8.

But the stack trace gives a hint as to what's causing it.
```
Uncaught (in promise) Error: No matching clause: 
    BV metabase.lib.util.js:11
    71733 metabase.lib.convert.js:22
    h cljs.core.js:509
    k1 metabase.lib.card.js:7
```
"No matching clause" means a case statement is being executed. It must be [this one](https://github.com/metabase/metabase/blob/5ca34c17b2e99b7f0c2c1163cd751abbd21c44c2/src/metabase/lib/util.cljc#L274-L276) since it's the only case statement in the file.

@tomy137 can you provide more information about what you see when you try to downgrade? Is there an error message? Perhaps it is related.

**Comment by k2xl** [comment] 2024-05-14 15:16
This happens to me too on 0.49.10. Seems to happen more often on mobile but also happens on browser.

**Comment by bshepherdson** [comment] 2024-05-27 19:51
@tomy137 @k2xl some more information would be useful for debugging this.

It would help a lot to see the network payload for the dashboard - can you use the devtools Network tab to "Copy -> Copy response" for the `/api/dashboard/123` request?

If you create a new dashboard and new questions (ideally based on our sample database) can you create and edit filters for it? That is, is this only an issue when upgrading a dashboard which already exists on 48 to 49?

**Comment by paoliniluis** [comment] 2024-05-31 13:54
@tomy137 @k2xl can you please give us some information about this?

**Comment by tomy137** [comment] 2024-05-31 14:44
Sorry, but I can't reproduce it now. I haven't worked on filters since this issue arose, and today it's working.
I did update to v0.49.10; maybe it's related?

**Comment by bshepherdson** [comment] 2024-06-05 21:14
Ah, I see. Slippery issues like this are puzzling.

With no one able to reproduce this, I'm going to close this issue. Feel free to reopen it if the issue reappears!

**Closed by bshepherdson** 2024-06-05 21:14 UTC
Labels: Type:Bug, Priority:P1, Reporting/Dashboards, .Unable to Reproduce, Querying/Parameters & Variables, Operation/Database Migrations, .Regression, .Team/QueryProcessor
