### ISSUE TITLE
export csv failed with "Not Found" error

### ISSUE THREAD

**Issue by robbietree8** [metabase/metabase#33487] opened 2023-08-25 03:29 UTC
### Describe the bug

When I upgrade from v0.46.3 to v0.47.0, export data from question failed.

### To Reproduce

1. Go to some question
2. Click on export
3. See error

### Expected behavior

export should work successfully

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.15.2.el7.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.40-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-08-16",
      "tag": "v0.47.0",
      "branch": "release-x.47.x",
      "hash": "682ec2d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

not blocking, since we can export directly from db

### Additional context

The exported file looks below:

```
{timestamp:2023-08-25T03:22:55.717+00:00 | status:404 | error:Not Found | path:/card/38/query/csv}
-- | -- | -- | --
```

**Comment by paoliniluis** [comment] 2023-08-25 06:40
Dupe of https://github.com/metabase/metabase/issues/33244

**Closed by paoliniluis** 2023-08-25 06:40 UTC
Labels: Type:Bug, .Needs Triage
