### ISSUE TITLE
Dashboard filter using boolean value sends string on browser reload

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11911] opened 2020-02-13 22:48 UTC
**Describe the bug**
When connecting a dashboard category filter to a boolean column, it only works via the widget. If visiting the dashboard URL or refreshing the dashboard (with the filter set to true/false), sends the `true`/`false` as string.

**Logs**
When visiting the URL or refreshing `/dashboard/172?boolean=false`
```
[6c693206-f2f1-47a6-8450-f804282c1390] 2020-02-13T23:23:37+01:00 WARN metabase.query-processor.middleware.process-userland-query Query failure {:status :failed,
 :class clojure.lang.ExceptionInfo,
 :error "No matching signature for operator = for argument types: BOOL, STRING. Supported signatures: ANY = ANY at [2:117]",
 :stacktrace
 ("--> driver.google$execute_no_auto_retry.invokeStatic(google.clj:39)"
  "driver.google$execute_no_auto_retry.invoke(google.clj:32)"
  "driver.google$execute$fn__1663.invoke(google.clj:50)"
  "util$do_with_auto_retries.invokeStatic(util.clj:397)"
  "util$do_with_auto_retries.invoke(util.clj:389)"
  "util$do_with_auto_retries.invokeStatic(util.clj:401)"
  "util$do_with_auto_retries.invoke(util.clj:389)"
  "util$do_with_auto_retries.invokeStatic(util.clj:401)"
  "util$do_with_auto_retries.invoke(util.clj:389)"
  "driver.google$execute.invokeStatic(google.clj:49)"
  "driver.google$execute.invoke(google.clj:43)"
  "driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:202)"
  "driver.bigquery$execute_bigquery.invoke(bigquery.clj:191)"
  "driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:193)"
  "driver.bigquery$execute_bigquery.invoke(bigquery.clj:191)"
  "driver.bigquery$process_native_STAR_$fn__2490.invoke(bigquery.clj:209)"
  "util$do_with_auto_retries.invokeStatic(util.clj:397)"
  "util$do_with_auto_retries.invoke(util.clj:389)"
  "util$do_with_auto_retries.invokeStatic(util.clj:401)"
  "util$do_with_auto_retries.invoke(util.clj:389)"
  "driver.bigquery$process_native_STAR_.invokeStatic(bigquery.clj:208)"
  "driver.bigquery$process_native_STAR_.invoke(bigquery.clj:204)"
  "driver.bigquery$eval2494$fn__2496.invoke(bigquery.clj:224)"
  "query_processor$fn__46282$execute_query__46287$fn__46288.invoke(query_processor.clj:69)"
  "query_processor$fn__46282$execute_query__46287.invoke(query_processor.clj:64)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__37469.invoke(mbql_to_native.clj:40)"
  "query_processor.middleware.annotate$result_rows_maps__GT_vectors$fn__40576.invoke(annotate.clj:541)"
  "query_processor.middleware.annotate$add_column_info$fn__40482.invoke(annotate.clj:485)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__41516.invoke(cumulative_aggregations.clj:57)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__43373.invoke(resolve_joins.clj:184)"
  "query_processor.middleware.limit$limit$fn__42151.invoke(limit.clj:19)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__46142.invoke(results_metadata.clj:87)"
  "query_processor.middleware.format_rows$format_rows$fn__42139.invoke(format_rows.clj:76)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__38229.invoke(add_dimension_projections.clj:234)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__38880.invoke(add_source_metadata.clj:107)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__43423.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__38717.invoke(add_row_count_and_status.clj:16)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__41591.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__43037.invoke(resolve_driver.clj:22)"
  "query_processor.middleware.store$initialize_store$fn__46167$fn__46168.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__46167.invoke(store.clj:10)"
  "query_processor.middleware.async$async__GT_sync$fn__37380.invoke(async.clj:23)"
  "query_processor.middleware.async_wait$runnable$fn__40633.invoke(async_wait.clj:89)"),
 :query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:userland-query? true},
  :info
  {:executed-by 44,
   :context :question,
   :card-id 1042,
   :dashboard-id nil,
   :query-hash [-100, -74, 83, -75, -125, 92, 37, -58, -8, -31, 68, -30, -68, 74, -101, 108, -6, 112, -51, 85, -99, -43, 82, 124, 96, 109, 2, 55, -104, -28, -87, -78]},
  :query {:source-table 7707},
  :parameters [{:type "category", :target ["dimension" ["field-id" 284395]], :value "false"}],
  :async? true,
  :cache-ttl 41},
 :preprocessed
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:userland-query? true},
  :info
  {:executed-by 44,
   :context :question,
   :card-id 1042,
   :query-hash [-100, -74, 83, -75, -125, 92, 37, -58, -8, -31, 68, -30, -68, 74, -101, 108, -6, 112, -51, 85, -99, -43, 82, 124, 96, 109, 2, 55, -104, -28, -87, -78]},
  :preprocessing-level 1,
  :database 32,
  :query
  {:source-table 7707,
   :filter [:= [:field-id 284395] [:value "false" {:base_type :type/Boolean, :special_type :type/Category, :database_type "BOOLEAN"}]],
   :fields [[:field-id 284396] [:field-id 284395]],
   :limit 2000},
  :cache-ttl 41},
 :native
 {:query "SELECT `dacort.bool_test`.`name` AS `name`, `dacort.bool_test`.`is_cool` AS `is_cool` FROM `dacort.bool_test` WHERE `dacort.bool_test`.`is_cool` = 'false' LIMIT 2000",
  :table-name "bool_test",
  :mbql? true},
 :ex-data
 {"code" 400,
  "errors"
  [{"domain" "global", "location" "q", "locationType" "parameter", "message" "No matching signature for operator = for argument types: BOOL, STRING. Supported signatures: ANY = ANY at [2:117]", "reason" "invalidQuery"}],
  "message" "No matching signature for operator = for argument types: BOOL, STRING. Supported signatures: ANY = ANY at [2:117]",
  "status" "INVALID_ARGUMENT"}}
```

**To Reproduce**
1. Create a Simple question on a table with boolean values
2. Add question to a dashboard
3. Add Category filter and connect to question
4. Click filter and select "False" - it shows all the rows with `false` boolean column
5. Refresh browser or copy URL to new tab, it will display error-card and the log will contain full error.
When checking the request, it's sending an array (`"value":[false]`) when using the widget, but a string (`"value":"false"`) when visiting/reloading the URL.

**Information about your Metabase Installation:**
stats instance and 1.34.2 - only tested with BigQuery

**Additional context**
This is very likely a duplicate of #11883 - or very related.

**Comment by paulrosenzweig** [comment] 2020-02-21 23:13
Fixed in #11937

**Comment by dacort** [comment] 2020-03-06 23:29
Looks like this only fixed it for `true` values. If I go to a dashboard with a value of `false` in the URL for the dashboard filter, the page reloads to a URL with no filter, "false" is filled in in the category filter, but not actually applied to the underlying query.

**Closed** 2020-03-13 21:53 UTC
Labels: Database/BigQuery, Priority:P2, Querying/Parameters & Variables, Reporting/Dashboards, Type:Bug

**Comment by jsuarezb** [comment] 2020-05-22 21:24
> Looks like this only fixed it for `true` values. If I go to a dashboard with a value of `false` in the URL for the dashboard filter, the page reloads to a URL with no filter, "false" is filled in in the category filter, but not actually applied to the underlying query.

Having the same issue right now with v0.35.3. @dacort are you still experiencing issues with passing a `false` query param? It seems fixed in question filters but not with dashboard filters.

**Comment by flamber** [comment] 2020-05-22 21:38
@jsuarezb Please post "Diagnostic Info" from Admin > Troubleshooting. And which database you're querying.

**Comment by jsuarezb** [comment] 2020-05-26 01:48
@flamber 

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/81.0.4044.138 Chrome/81.0.4044.138 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.9.0-11-amd64",
    "user.language": "en",
    "user.timezone": "GMT-3"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-21",
      "tag": "v0.35.3",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": "America/Buenos_Aires"
    }
  }
}
```

Querying Redshift!

` PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.15503`

**Comment by flamber** [comment] 2020-05-26 09:09
@jsuarezb I cannot reproduce this on `master`. I don't have Redshift available in my 0.35.3, but I don't think there has been any changes in this area since 0.35.0.
Can you provide steps to reproduce and error logs?

**Comment by jsuarezb** [comment] 2020-05-27 03:59
@flamber I've tried to reproduce it with a new dashboard and I wasn't able to.

These were the steps that caused the query param to disappear:

1. Set the category filter to `false`
2. Refresh the page
3. See how the query param disappears from the URL when the dashboard is loaded and the dashboard filter stays empty (with the blue border as if it was set)

I'm suspecting there may be have been some issues with the fields the filter was associated with (maybe some type change, can't be sure though). I managed to fix this by deleting and recreating the filter again, but now I can't reproduce it again. :-1:

**Comment by flamber** [comment] 2020-05-27 08:54
@jsuarezb 
Thanks for trying to reproduce :+1:
This might be a difficult question to answer, but do you remember which version of Metabase you were using, when you created the dashboard filter?

I have a feeling that it might be an old problem with `visualization_settings` incompatibility after upgrades, which has previously caused some settings to get lost. For reference: #11829
But if you could guide to circa version, then I can try to reproduce, so we can figure out a way to migrate those old settings.

**Comment by jsuarezb** [comment] 2020-05-28 12:15
@flamber yes! The dashboard with the issue was created last week, using v0.35.3. 

From what I can see though, it's **highly** likely that the field associated with the filter was a Redshift `varchar` column (with `'true'` and `'false'` strings) when the filter was created; later it was changed to a `boolean` column.

**Comment by flamber** [comment] 2020-05-28 12:47
@jsuarezb Okay, changing column types after already created questions (with possible filters and aggregation) and dashboard with filter connections, can break things in Metabase, but I would say that's expected behavior.

I'm sure it would also cause problems if you changed a column from string to number, or number to date, or vice-versa.

It would be very difficult for Metabase to automatically change all linkage to "something else", when the underlying structure changes column types.
But it's probably a discussion for a different issue - you're welcome to open a new feature request.
