### ISSUE TITLE
FE - disable "Add or remove columns" when there are aggregations or breakout in the last stage - unskip e2e test only

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#36746] opened 2023-12-13 12:43 UTC
Complementary to #36574

Discussion: [Slack](https://metaboat.slack.com/archives/C04CYTEL9N2/p1702063378269379)
Resolution: [Slack](https://metaboat.slack.com/archives/C04CYTEL9N2/p1702471190604429?thread_ts=1702063378.269379&cid=C04CYTEL9N2)

See [this video](https://github.com/metabase/metabase/assets/6830683/f9ce47a4-a6eb-4d39-ab10-7c414ec38d37) for "Add or remove columns" location (https://github.com/metabase/metabase/issues/36575#issuecomment-1851994370).

----

`19745-cc-nested-query-remove-expressions.cy.spec.js` e2e test will have to be removed as this change is not backwards-compatible and it will no longer be possible to have fields after aggregations and breakouts.

The video linked above shows how to manually reproduce situation from e2e test setup.

**Comment by ranquild** [comment] 2023-12-22 12:27
Do not forget to unskip the test when the issue is fixed in the lib

**Closed** 2024-01-05 16:47 UTC
Labels: .Frontend, .metabase-lib, .Team/QueryingComponents
