### ISSUE TITLE
Inoptimal queries using time when using field filters

### ISSUE THREAD

**Issue by hello-error** [metabase/metabase#26031] opened 2022-10-20 08:08 UTC
**Describe the bug**
Using field filters on large scale data and time field inside it results in an inoptimal query.

**Logs**
```python
select * from table where CAST("public"."table"."time" AS date) = '2022-10-20' limit 10;
```

**To Reproduce**
1. Select a table with high cardinality of time series data and a time field say "time" as field filter.
2. Select relative date.

**Expected behavior**
Resulting in a query like 
```python
select * from table where CAST("public"."table"."time" AS date) = '2022-10-20' limit 10;
```
requires the SQL planner to parse all the possible time values, cast them to date and then check the condition.
Databases like timescale db rather benefit by a simple command such as 
```python
select * from table where time >= '2022-10-20' limit 10;
```
or
```python
select * from table where time = '2022-10-20' limit 10;
```
no explicit type casts required.

**Severity**
Unable to use field filters ---- no control on query structure when high cardinality time series data is of concern.

<img width="1064" alt="Screenshot 2022-10-20 at 4 08 31 PM" src="https://user-images.githubusercontent.com/23632420/196892913-a6242500-2c0f-4d78-8143-ed3214dce48f.png">

**Comment by flamber** [comment] 2022-10-20 09:01
Duplicate of #20333/#21133

**Closed by flamber** 2022-10-20 09:01 UTC
Labels: Type:Bug, .Needs Triage
