### ISSUE TITLE
Can't make a line chart of a custom field

### ISSUE THREAD

**Issue by imightbeamy** [metabase/metabase#2546] opened 2016-05-05 14:06 UTC
I have price/cost information stored in cents and would like it to show up in dollars on my chats. I tried using a custom field for this, but it says "We couldn’t create a line chart based on your query." The table view of the data looks exactly the same for the raw Price field and the custom field (besides being 100x).

<img width="855" alt="screen shot 2016-05-05 at 9 55 58 am" src="https://cloud.githubusercontent.com/assets/1229145/15045399/3e390856-12a8-11e6-9f6e-f675fd88b28c.png">

My field looks like this: (I tried add, subtract and multiply too and they also didn't work) 
<img width="528" alt="screen shot 2016-05-05 at 10 03 11 am" src="https://cloud.githubusercontent.com/assets/1229145/15045482/b6ca0ff4-12a8-11e6-868b-95bd453c8d14.png">

*  I am using Chrome.
*  My computer's OS is OS X El Capitan.
*  I'm running Metabase on Herkou.
*  My database is Postgres.
*  My Metabase version is v0.17.0.

**Comment by mazameli** [comment] 2016-05-05 16:51
Hmm, yeah, I'm able to replicate this with the Sample Data. We'll have to look into this. Thanks, @imightbeamy.

**Comment by mazameli** [comment] 2016-05-05 18:51
Steps to reproduce:

1. open up the sample dataset and select the Orders table
2. create a custom column that takes Total and multiplies or divides etc. it by 100
3. select the average, sum, etc. of your custom column and group it by Created At and run the query
4. attempt to change the visualization to a line or bar chart

**Comment by agilliland** [comment] 2016-05-06 19:07
@tlrobinson After playing with this I believe this is just a frontend issue.  The query is executing fine and returning valid results when I try this locally and I can see the data in a table, but when trying to chart it i am getting an error.

<img width="892" alt="screen shot 2016-05-06 at 12 05 39 pm" src="https://cloud.githubusercontent.com/assets/1987787/15083625/1aa3e04c-1383-11e6-881b-3f0c84c5a7cb.png">

**Comment by tlrobinson** [comment] 2016-05-09 16:15
@agilliland Sorry, I think @camsaul and I discussed this in Slack but I didn't update this issue. The problem is the backend is not returning a `base_type` for the calculated field so the frontend doesn't know it's considered a metric. I think the backend should set the `base_type` depending on the calculated column's formula (but for I think it can always be `FloatField`)

Does that make sense? If so can we assign this back to @camsaul?

Alternatively we could try to infer the `base_type on the frontend if none is set, but I feel like we're trying to move away from that sort of thing.

**Comment by camsaul** [comment] 2016-05-09 20:33
Fixed by #2566

**Closed by camsaul** 2016-05-09 20:33 UTC
Labels: Bug, Priority/P1, Visualization

**Comment by AlexandraLouise** [comment] 2016-10-20 14:54
Hi @camsaul 

Getting this error again. I am writing a custom sql query. When I use the Date(created) sql function and group by date(created) I cannot visualize the data through Metabase. It gives me the issue
"We couldn’t create a line chart based on your query." 

An example of this query would be 

SELECT Date(created), count(*)
FROM TABLE
GROUP BY DATE(created)

It is obviously not aware that the date is a metric - is there a way I can get around this? 

Alex

**Comment by camsaul** [comment] 2016-10-21 21:10
@AlexandraLouise any reason you can't just use the query builder for the query?

It also sounds like the problem you're having is a different issue than this one. The error is similar but this one is talking about using custom fields in the query builder, while it sounds like you're talking about writing custom SQL queries. Can you open a new issue for this? Please be sure to fill out all the information like Metabase version, which DB you're using, etc.
