### ISSUE TITLE
Failed to change collection permission cause by data to long

### ISSUE THREAD

**Issue by KEN-LJQ** [metabase/metabase#13088] opened 2020-08-10 04:13 UTC
**Describe the bug**
As we want to grant visit permission for collection to specific permision group, and we get `(conn=81258) Data too long for column 'before' at row 1` exception after click the save change button.
Note that, we have about 400+ collections and 40+ group

**Logs**
```
08-10 09:50:40 ESC[1mERROR middleware.logESC[0m :: ESC[31mPUT /api/collection/graph 500 979.4 ms（25个数据库调用） 
{:via
 [{:type java.sql.SQLDataException, :message "(conn=81257) Data too long for column 'before' at row 1", :at [org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper get "ExceptionMapper.java" 232]}
  {:type java.sql.SQLException,
   :message "Data too long for column 'before' at row 1",
   :at [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol readErrorPacket "AbstractQueryProtocol.java" 1599]}],
 :trace
 [[org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol readErrorPacket "AbstractQueryProtocol.java" 1599]
  [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol readPacket "AbstractQueryProtocol.java" 1461]
  [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol getResult "AbstractQueryProtocol.java" 1424]
  [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol executeQuery "AbstractQueryProtocol.java" 240]
  [org.mariadb.jdbc.ClientSidePreparedStatement executeInternal "ClientSidePreparedStatement.java" 216]
  [org.mariadb.jdbc.ClientSidePreparedStatement execute "ClientSidePreparedStatement.java" 145]
  [org.mariadb.jdbc.ClientSidePreparedStatement executeUpdate "ClientSidePreparedStatement.java" 176]
  [com.mchange.v2.c3p0.impl.NewProxyPreparedStatement executeUpdate "NewProxyPreparedStatement.java" 462]
  [clojure.java.jdbc$db_do_execute_prepared_return_keys$exec_and_return_keys__19121 invoke "jdbc.clj" 979]
  [clojure.java.jdbc$db_do_execute_prepared_return_keys invokeStatic "jdbc.clj" 1007]
  [clojure.java.jdbc$db_do_execute_prepared_return_keys invoke "jdbc.clj" 963]
  [clojure.java.jdbc$db_do_prepared_return_keys invokeStatic "jdbc.clj" 1038]
  [clojure.java.jdbc$db_do_prepared_return_keys invoke "jdbc.clj" 1015]
  [toucan.db$simple_insert_many_BANG_$iter__21615__21619$fn__21620$fn__21621 invoke "db.clj" 563]
  [toucan.db$simple_insert_many_BANG_$iter__21615__21619$fn__21620 invoke "db.clj" 561]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5402 invokeStatic "core.clj" 137]
  [clojure.core$dorun invokeStatic "core.clj" 3133]
  [clojure.core$doall invokeStatic "core.clj" 3148]
  [clojure.core$doall invoke "core.clj" 3148]
  [toucan.db$simple_insert_many_BANG_ invokeStatic "db.clj" 560]
  [toucan.db$simple_insert_many_BANG_ invoke "db.clj" 546]
  [toucan.db$simple_insert_BANG_ invokeStatic "db.clj" 593]
  [toucan.db$simple_insert_BANG_ invoke "db.clj" 582]
  [toucan.db$insert_BANG_ invokeStatic "db.clj" 610]
  [toucan.db$insert_BANG_ invoke "db.clj" 597]
  [toucan.db$insert_BANG_ invokeStatic "db.clj" 613]
  [toucan.db$insert_BANG_ doInvoke "db.clj" 597]
  [clojure.lang.RestFn invoke "RestFn.java" 731]
  [metabase.models.collection.graph$save_perms_revision_BANG_ invokeStatic "graph.clj" 130]
  [metabase.models.collection.graph$save_perms_revision_BANG_ invoke "graph.clj" 120]
  [metabase.models.collection.graph$fn__51650$update_graph_BANG___51659$fn__51662$fn__51685 invoke "graph.clj" 161]
  [toucan.db$do_in_transaction$fn__21447 invoke "db.clj" 147]
  [clojure.java.jdbc$db_transaction_STAR_ invokeStatic "jdbc.clj" 807]
  [clojure.java.jdbc$db_transaction_STAR_ invoke "jdbc.clj" 776]
  [clojure.java.jdbc$db_transaction_STAR_ invokeStatic "jdbc.clj" 852]
  [clojure.java.jdbc$db_transaction_STAR_ invoke "jdbc.clj" 776]
  [clojure.java.jdbc$db_transaction_STAR_ invokeStatic "jdbc.clj" 789]
  [clojure.java.jdbc$db_transaction_STAR_ invoke "jdbc.clj" 776]
  [toucan.db$do_in_transaction invokeStatic "db.clj" 145]
  [toucan.db$do_in_transaction invoke "db.clj" 142]
  [metabase.models.collection.graph$fn__51650$update_graph_BANG___51659$fn__51662 invoke "graph.clj" 158]
  [metabase.models.collection.graph$fn__51650$update_graph_BANG___51659 invoke "graph.clj" 136]
  [metabase.api.collection$fn__51961 invokeStatic "collection.clj" 339]
  [metabase.api.collection$fn__51961 invoke "collection.clj" 333]
  [compojure.core$wrap_response$fn__1993 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__1977 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__1982 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 151]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [metabase.middleware.auth$enforce_authentication$fn__68489 invoke "auth.clj" 14]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2033 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 296]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 665]
  [clojure.core$apply invoke "core.clj" 660]
  [metabase.routes$fn__70022$fn__70023 doInvoke "routes.clj" 56]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2033 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 296]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [metabase.middleware.exceptions$catch_uncaught_exceptions$fn__68592 invoke "exceptions.clj" 96]
  [metabase.middleware.exceptions$catch_api_exceptions$fn__68589 invoke "exceptions.clj" 84]
  [metabase.middleware.log$log_api_call$fn__70470$fn__70471 invoke "log.clj" 197]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.middleware.log$log_api_call$fn__70470 invoke "log.clj" 191]
  [metabase.middleware.security$add_security_headers$fn__68555 invoke "security.clj" 121]
  [metabase.middleware.json$wrap_json_body$fn__70173 invoke "json.clj" 64]
  [metabase.middleware.json$wrap_streamed_json_response$fn__70191 invoke "json.clj" 100]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__70771 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__70787 invoke "params.clj" 69]
  [metabase.middleware.misc$maybe_set_site_url$fn__70501 invoke "misc.clj" 59]
  [metabase.middleware.session$bind_current_user$fn__65051$fn__65052 invoke "session.clj" 204]
  [metabase.middleware.session$do_with_current_user invokeStatic "session.clj" 186]
  [metabase.middleware.session$do_with_current_user invoke "session.clj" 178]
  [metabase.middleware.session$bind_current_user$fn__65051 invoke "session.clj" 203]
  [metabase.middleware.session$wrap_current_user_info$fn__65038 invoke "session.clj" 169]
  [metabase.middleware.session$wrap_session_id$fn__65026 invoke "session.clj" 127]
  [metabase.middleware.auth$wrap_api_key$fn__68497 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__70691 invoke "cookies.clj" 216]
  [metabase.middleware.misc$add_content_type$fn__70486 invoke "misc.clj" 28]
  [metabase.middleware.misc$disable_streaming_buffering$fn__70509 invoke "misc.clj" 76]
  [ring.middleware.gzip$wrap_gzip$fn__70733 invoke "gzip.clj" 86]
  [metabase.middleware.ssl$redirect_to_https_middleware$fn__70522 invoke "ssl.clj" 39]
  [metabase.server$async_proxy_handler$fn__70248 invoke "server.clj" 72]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 500]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 383]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 547]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 375]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 273]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 103]
  [org.eclipse.jetty.io.ChannelEndPoint$2 run "ChannelEndPoint.java" 117]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 336]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 313]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 171]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 129]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 375]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 806]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 938]
  [java.lang.Thread run "Thread.java" 748]],
 :cause "Data too long for column 'before' at row 1",
 :message "(conn=81257) Data too long for column 'before' at row 1",
 :type java.sql.SQLDataException,
 :sql-exception-chain ["SQLDataException:" "Message: (conn=81257) Data too long for column 'before' at row 1" "SQLState: 22001" "Error Code: 1406"]}
```

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_162-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_162",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.162-b12",
    "os.name": "Linux",
    "os.version": "2.6.32-696.3.1.el6.x86_64",
    "user.language": "zh",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "presto"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.26-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.36.2",
      "date": "",
      "branch": "2020-08-04",
      "hash": "pre-production"
    },
    "settings": {
      "report-timezone": "Asia/Hong_Kong"
    }
  }
}
```

**Severity**
With this issue, we can not change the permission of collection very well.
Now my solution is insert a record into table `permissions`; And I wonder whether we can change data type of `before` and `after` from text to mediumtext without impact the metabase upgrade

**Comment by flamber** [comment] 2020-08-10 08:02
Hi @KEN-LJQ 
Change all `TEXT` types to `LONGTEXT`, that will fix it.
Likely a duplicate of #7006/#11977

**Comment by camsaul** [comment] 2021-02-18 02:18
Same underlying issue as #7006. Closing as duplicate of #7006

**Closed by camsaul** 2021-02-18 02:18 UTC
Labels: Administration/Permissions, Database/MySQL, Operation/Database Migrations, Priority:P2, Type:Bug
