### ISSUE TITLE
Custom filters on dashboard don't work anymore

### ISSUE THREAD

**Issue by AgentBlond** [metabase/metabase#11951] opened 2020-02-21 08:36 UTC
**Describe the bug**
I have a dashboard with mulitiple questions - some made with the editor, some are native queries on BigQuery. When I want to update the filters, I cannot access the variables in the native queries any more.

**Expected behavior**
When I click on the filter options on the dashboards it should show me all available filter options on the questions.

I have attached a video to show the bug.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22956171/75017539-82373700-548d-11ea-9d79-c5b95daf0824.gif)

**Information about your Metabase Installation:**

Your browser and the version: Chrome Version 78.0.3904.108
Your operating system: Mac OS Catalina
Your databases: BigQuery
Metabase version: 0.34.2
Metabase hosting environment: Docker

**Severity**
It is a severe bug because I cannot alter or add filters on any dashboard anymore.

**Comment by flamber** [comment] 2020-02-21 11:13
Duplicate of #11927. It's caused by the Text Box on the dashboard and only workaround currently is either to remove the Text Box or downgrade to 0.34.0 (remember to backup before up-/downgrade!)

**Closed by flamber** 2020-02-21 11:13 UTC
Labels: .Needs Triage, Type:Bug
