### ISSUE TITLE
CSV Download limit numbers not consistent with the Table size

### ISSUE THREAD

**Issue by Rohith6215** [metabase/metabase#10885] opened 2019-09-13 14:44 UTC
**Describe the bug**
CSV download doesn't give proper results. As per the documentation 1 million is the download limit. However in my case I'm getting 29,167 rows in excel this is download on the table created on Metabase, whereas my data is having ~265k rows. What is the exact limit for Metabase download ?

**To Reproduce**
1. Go to 'Download Button'
2. Click on 'Download button'
3. Fetch the results and do the count of the rows
4. This doesn't match from the source data

**Expected behavior**
To download the entire data since it is in the limit of 1 million rows

**Screenshots**

- Your browser and the version: Chrome
- Your operating system: Windows 10
- Your databases: Google Big Query
- Metabase version: 0.33.2
- Metabase hosting environment:  Jar-file on Ubuntu
- Metabase internal database: MySQL

**Severity**
Very Important since we need to answer our stack holders on the 

**Additional context**

**Comment by flamber** [comment] 2019-09-13 16:32
Hi @Rohith6215 
Sounds like a duplicate of #6960 - if you agree, then please close this issue and upvote by clicking :+1: on the first post of the other issue.

**Comment by salsakran** [comment] 2019-10-05 23:59
dupe as @flamber said. bumping #6960 in priority given the number of people experiencing it.

**Closed by salsakran** 2019-10-05 23:59 UTC
Labels: Type:Bug
