### ISSUE TITLE
Report containing a joined subquestion (which contains a metrics) throws an error

### ISSUE THREAD

**Issue by Thomassso** [metabase/metabase#15571] opened 2021-04-12 15:55 UTC
**Describe the bug**
Report goal: create product list and sold product quantity total and product quantity sold with discount.
If the joined question contains a metric then the report raises an error.
```
Column "Question 168.DISCOUNT" not found; SQL statement: -- Metabase:: userID: 66 queryType: MBQL queryHash: 6313bc443f236bc216458592b541f091ffe5d8c11cb64331da276c15e1f98d29 SELECT "PUBLIC"."PRODUCTS"."CATEGORY" AS "CATEGORY", "PUBLIC"."PRODUCTS"."TITLE" AS "TITLE", "Question 168"."sum" AS "sum" FROM "PUBLIC"."PRODUCTS" LEFT JOIN (SELECT "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID", sum("PUBLIC"."ORDERS"."QUANTITY") AS "sum" FROM "PUBLIC"."ORDERS" GROUP BY "PUBLIC"."ORDERS"."PRODUCT_ID") "Question 168" ON "PUBLIC"."PRODUCTS"."ID" = "Question 168"."PRODUCT_ID" WHERE "Question 168"."DISCOUNT" > 0 LIMIT 2000 [42122-197]
```

**To Reproduce**
1. In Admin/Data_Model create a new metric on Orders table. (Filtering: Discount greater than 0; Aggregation: Sum of Quantity).
2. Remap PRODUCT_ID column: In Admin/Data_Model choose Orders table and PRODUCT_ID column. Configure *Display values* to ```Use foreign key > TITLE```.
3. Create a new Custom question on Orders table. Summarize it by: metric created previously. Aggregate by PRODUCT_ID.
4. Save the question as *Product quantity with discount*
5. Create another new Custom question on Products table. Leave only 2 columns: CATEGORY, TITLE.
6. Join the *Product quantity with discount* question. Join on PRODUCTS.ID=ORDER.PRODUCT_ID . Leave only 1 column: *sum* .
7. The Visualize button shows an error message instead of the report.

**Expected behavior**
A report with 3 columns should be visible: CATEGORY, TITLE, sum.

**Screenshots**
Screenshot for Step 1
![Screenshot for Step 1](https://user-images.githubusercontent.com/27001370/114422053-375b1000-9bb6-11eb-9bc5-d561f6a7f2a5.png)

Screenshot for Step 3
![Screenshot for Step 3](https://user-images.githubusercontent.com/27001370/114422309-71c4ad00-9bb6-11eb-815e-8fb2de183566.png)

Screenshot for Step 6
![Screenshot for Step 6](https://user-images.githubusercontent.com/27001370/114422495-9f115b00-9bb6-11eb-9f74-7b401408c597.png)

Yet another screenshot for Step 6
![Yet another screenshot for Step 6](https://user-images.githubusercontent.com/27001370/114422683-cb2cdc00-9bb6-11eb-9c0f-e6be992acc3b.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_262-b10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_262",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.262-b10",
    "os.name": "Linux",
    "os.version": "4.15.0-133-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.39.0-rc1",
      "date": "2021-04-06",
      "branch": "release-x.39.x",
      "hash": "471eda1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Every second report contains metrics (aggregation with filters). In every third report we need to join such a question to a main category table (like agents, customers, products, etc.).

**Comment by flamber** [comment] 2021-04-12 21:03
This is a duplicate of #12507/#8856

**Closed by flamber** 2021-04-12 21:03 UTC
Labels: .Needs Triage, Type:Bug
