### ISSUE TITLE
Group by month is off when using BigQuery

### ISSUE THREAD

**Issue by robinwassen** [metabase/metabase#2405] opened 2016-04-22 12:51 UTC
*  I am using the Mac App browser.
*  My computer's OS is Mac OS X 10.10.5.
*  I'm running Metabase Mac App. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is BigQuery.
*  My Metabase version is 0.16.1.

It seems like the month grouping is off when using a BigQuery database as source.

In the following example March 2015 does not exist and October 2015 appears twice (I used Maximum of Citylong as val to not show sensitive data, same problem when I use row count).

The Time field is a TIMESTAMP in BQ and a sample value is: 2016-04-06 04:27:29 UTC	

![screen shot 2016-04-22 at 14 46 46](https://cloud.githubusercontent.com/assets/302151/14741869/86a753a4-0899-11e6-9c55-caba67fa3d0c.png)

**Comment by agilliland** [comment] 2016-04-22 21:56
Hey @robinwassen , would you be able to check the application logs which are output when you run the query and see if we can take a look at the actual BQ sql that is generated.  That would be really helpful in getting us a chance to figure out what's going on.

When using Metabase via Mac App you would open up the Mac `Console` application which is where the app logs will be reported.

**Comment by robinwassen** [comment] 2016-04-24 12:00
The query looks like the following:

	SELECT COUNT(*) AS [count], CAST(STRFTIME_UTC_USEC(TIMESTAMP_TO_USEC([x.userlogin.time]), '%Y-%m-01') AS TIMESTAMP) AS [x.userlogin.time]
	FROM [x.userlogin]
	GROUP BY [x.userlogin.time]
	ORDER BY [x.userlogin.time] ASC

And yields the following data when run in the BQ console:

	Row	count	x_userlogin_time	 
	1	1	2014-11-01 00:00:00 UTC	 
	2	1	2014-12-01 00:00:00 UTC	 
	3	1	2015-01-01 00:00:00 UTC	 
	4	1	2015-02-01 00:00:00 UTC	 
	5	1	2015-03-01 00:00:00 UTC	 
	6	1	2015-04-01 00:00:00 UTC	 
	7	1	2015-05-01 00:00:00 UTC	 
	8	1	2015-06-01 00:00:00 UTC	 
	9	1	2015-07-01 00:00:00 UTC	 
	10	1	2015-08-01 00:00:00 UTC	 
	11	1	2015-09-01 00:00:00 UTC	 
	12	1	2015-10-01 00:00:00 UTC	 
	7	1	2015-05-01 00:00:00 UTC	 
	8	1	2015-06-01 00:00:00 UTC	 
	9	1	2015-07-01 00:00:00 UTC	 
	10	1	2015-08-01 00:00:00 UTC	 
	11	1	2015-09-01 00:00:00 UTC	 
	12	1	2015-10-01 00:00:00 UTC	 
	13	1	2015-11-01 00:00:00 UTC	 
	14	1	2015-12-01 00:00:00 UTC	 
	15	1	2016-01-01 00:00:00 UTC	 
	16	1	2016-02-01 00:00:00 UTC	 
	17	1	2016-03-01 00:00:00 UTC	 
	18	1	2016-04-01 00:00:00 UTC	 

Which looks correct, so it is probably something in the presentation layer. My guess is that it has something to do with the daylight saving time events, because they were happened [29:th March and 29:th October in 2015](http://www.timeanddate.com/time/dst/2015.html).

My computer time zone is set to CEST (and in the extension the Metabase server since I host the instance).

**Comment by agilliland** [comment] 2016-04-26 16:03
It's possible that what you are seeing was caused by this issue, which has been resolved ... https://github.com/metabase/metabase/issues/2340

**Comment by agilliland** [comment] 2016-04-27 15:53
@robinwassen When you get a chance if you can post the output of the query execution from your browser network log that would be really helpful.  When the query runs there should be a call to `/api/dataset` and we'll just want to take a quick look at the rows of data from that output to make sure they match up with the output from your query above.  If not then this is like a timezone related mismatch.

**Comment by camsaul** [comment] 2016-08-31 22:32
@robinwassen?

**Comment by robinwassen** [comment] 2016-09-02 12:54
Hi guys,

Sorry, I have lost the metabase instance and setup since long. So I am not able to add additional information anymore.

**Comment by camsaul** [comment] 2016-09-02 19:59
Ok. Since as @agilliland mentioned this issue was probably resolved by #2340 I'm going to go ahead and close this; feel free to reöpen it this or open a new issue if you run into it again.

**Closed by camsaul** 2016-09-02 19:59 UTC
Labels: Bug, Database/BigQuery, Need More Info
