### ISSUE TITLE
Can define default value if empty string on a question result

### ISSUE THREAD

**Issue by maximepvrt** [metabase/metabase#13185] opened 2020-08-30 17:57 UTC
<img width="1371" alt="Capture d’écran 2020-08-30 à 19 53 51" src="https://user-images.githubusercontent.com/1840026/91666114-a342a980-eafa-11ea-8ed6-e3669385f906.png">

Be able to replace the value `(empty)` with another string on each question.

**Comment by flamber** [comment] 2020-08-30 18:06
Duplicate of #12128

**Closed by flamber** 2020-08-30 18:06 UTC
Labels: .Needs Triage, Type:New Feature
