### ISSUE TITLE
Can't connect Big Query to Metabase, instructions seem outdated

### ISSUE THREAD

**Issue by ctivanovich** [metabase/metabase#12888] opened 2020-07-10 09:19 UTC
The instructions say that we should select "Other" as an option for OAuth credentials application type, however, that is no longer available on GCP:

![image](https://user-images.githubusercontent.com/7261199/87138634-acbd4b80-c2d9-11ea-904f-a5fda6dd308f.png)

I tried setting this up with Web application as the choice, and authentication failed to redirect properly:

`The redirect URI in the request, urn:ietf:wg:oauth:2.0:oob, can only be used by a Client ID for native application. It is not allowed for the WEB client type.`

Any suggestions on how to connect to BQ with the current iterations of GCP and Metabase?

**Comment by flamber** [comment] 2020-07-10 09:37
Duplicate of #12491 - use "Desktop app" - 0.36.0 will change to Service Accounts, so this will be deprecated soon.

**Closed by flamber** 2020-07-10 09:37 UTC
Labels: .Needs Triage, Type:Question
