### ISSUE TITLE
Sort widget not displaying name of aggregation and not properly sorting by that aggregation.

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#3939] opened 2016-12-13 17:21 UTC
![image](https://cloud.githubusercontent.com/assets/1708680/21150913/c006b41e-c171-11e6-81e1-294cfc24d064.png)

**Comment by mazameli** [comment] 2016-12-13 19:28
I was able to reproduce this on our stats instance. It seems that the aggregation/metric shows up as blank in the sort popover, regardless of which "metabasic" aggregation is used. (I tried `count of rows` by `State` in the sample dataset, and also `Number of distinct values of User ID` by `State`.)

**Comment by anki-code** [comment] 2017-02-01 21:19
Still actual.

**Comment by mazameli** [comment] 2017-02-02 17:44
@anki-code, you mean to say you're still observing this bug, correct? I'm still seeing it on our stats instance as well. If the user has something like a bar graph with a count of rows broken out by category, this bug makes it so the user is stuck seeing the bars in alphabetical category order rather than by ascending/descending order of the count. The workaround is switching to table view and clicking on the column heading to do the sort (though, as mentioned in #4226, this doesn't work for SQL).

**Comment by mazameli** [comment] 2017-07-06 13:52
Okay, I've done a bit of investigating into this one, and I have an update:
* The popover still is not correctly displaying the name or label of the aggregation field(s).
* The sorting behavior _does_ work if the breakout is a non-numerical category field:

<img width="1295" alt="screen shot 2017-07-06 at 9 43 25 am" src="https://user-images.githubusercontent.com/2223916/27914066-100ed068-6230-11e7-8d73-ac47a81f6ebc.png">

* The sorting behavior _does not work_ if the breakout is a numeric field, even if it's an ID or category, or if it's very low cardinality:

<img width="1289" alt="screen shot 2017-07-06 at 9 45 18 am" src="https://user-images.githubusercontent.com/2223916/27914101-2a38be5e-6230-11e7-8b20-3bc56b2e51af.png">

<img width="1267" alt="screen shot 2017-07-06 at 9 43 00 am" src="https://user-images.githubusercontent.com/2223916/27914128-37ab4fde-6230-11e7-9920-9cd8f27a4a60.png">

<img width="1278" alt="screen shot 2017-07-06 at 9 33 46 am" src="https://user-images.githubusercontent.com/2223916/27914141-44571060-6230-11e7-933d-549bf5e7714e.png">

Importantly, yes, you can still sort the second kind of query in table view, but if you sort it in table view and then change back to a bar or line, **it still is not sorted.** Because of this last point, I'd motion to increase the priority of this, @salsakran, as it effectively breaks sorted charts for things like count of orders by rating.

**Comment by attekei** [comment] 2017-07-17 22:39
I double-checked that all issues listed by @mazameli still exist after merging #5134.

**Comment by mazameli** [comment] 2017-07-21 22:50
Per conversation with @attekei, I'm going to spin out my big comment about sorting with numerical categories into a separate issue. This issue will be just about the sort labels.

**Comment by attekei** [comment] 2017-07-24 19:13
@mazameli do you think that https://github.com/metabase/metabase/pull/5550 is sufficient for closing this issue?

**Comment by mazameli** [comment] 2017-07-25 18:35
Yes, the other issue I mentioned about sorting with a non-numerical field breakout is captured in this issue: https://github.com/metabase/metabase/issues/5549

**Closed** 2017-07-25 18:36 UTC
Labels: Bug, Priority/P3, Query Builder
