### ISSUE TITLE
Data selector popover is too small

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#15591] opened 2021-04-13 13:44 UTC
![image](https://user-images.githubusercontent.com/691495/114562300-6025e880-9c3c-11eb-9205-62f51bdc609e.png)

I'm seeing this on Stats with Chrome.

**Comment by paulrosenzweig** [comment] 2021-04-13 13:44
I called this a P1 since it's such a heavily trafficked path, but it doesn't totally prevent usage of anything so maybe P2 is better. cc @flamber

**Comment by flamber** [comment] 2021-04-13 13:45
@paulrosenzweig It is, and I already called it out: https://github.com/metabase/metabase/pull/15524#issuecomment-816919845

**Comment by nemanjaglumac** [comment] 2021-04-13 16:04
I can't reproduce this. At least not on `release-x.39.x` with Chrome in Cypress. Since you're seeing it in stats, is it possible that this issue exists only on `master`?

Btw when I go to stats with Brave, it displays normally for "Simple Question" but I can reproduce it for "Custom Question".

**Comment by flamber** [comment] 2021-04-13 16:18
I can reproduce for Simple and Custom (and Data Model > Segments and Metrics) on 0.39.0-rc2 on Firefox and Chrome with 1920x1080 - I have 17 databases, 31 on stats.
![image](https://user-images.githubusercontent.com/1447303/114585834-56c06e80-9c84-11eb-8517-f48ab3b51fb7.png)
![image](https://user-images.githubusercontent.com/1447303/114585970-75bf0080-9c84-11eb-8ff7-b337f05c6193.png)

**Comment by howonlee** [comment] 2021-04-13 17:53
I was able to repro and then wasnt after the 15524 so I thought that it fixed this, thanx for deterministic repro

**Comment by flamber** [comment] 2021-04-13 18:24
Can we also make sure to fix the CE option popover (and binning options, less relevant, since it's smaller) that goes outside of the viewport instead of staying inside with a scroll? As noted in https://github.com/metabase/metabase/pull/15524#issuecomment-816919845

**Comment by daltojohnso** [comment] 2021-04-15 21:16
fixed by https://github.com/metabase/metabase/pull/15608

**Closed by daltojohnso** 2021-04-15 21:16 UTC
Labels: .Frontend, .Regression, .Reproduced, Priority:P1, Type:Bug

**Comment by nemanjaglumac** [comment] 2021-04-15 21:37
@daltojohnso there was a repro for this issue that had to be unskipped before the merge.
