### ISSUE TITLE
Value does not match schema

### ISSUE THREAD

**Issue by pjaspers** [metabase/metabase#7541] opened 2018-05-03 12:11 UTC
We're running 0.28.6 and we're seeing a lot of these errors in the logs:

` {:field {:field {:special-type (not ("Valid field type" a-clojure.lang.Keyword)), :fingerprint {:type {:type/DateTime disallowed-key}}}}}`

This seems to happen when adding a filter for a datetime to a card, it can be worked around by using SQL but that does not seem like the way forward.

Any ideas or pointers where I should start looking?

**Comment by pjaspers** [comment] 2018-05-08 10:09
So, I found a workaround for this issue,

Go to Database Model, open the table, find the field that it's complaining about (we figured trhough some trial and error that it was always the 'Created At' field), then do this:

- Add a special type to that field (doesn't matter which one)
- Select 'Not a special type'

And that fixes the issue. So somehow the field had a special type attached to it (but not that you could see it in the UI, it was only the queries that were breaking)

**Comment by tlrobinson** [comment] 2018-05-08 17:34
@pjaspers can you tell me what database you're using and the database schema / type for the fields that you're having problems with?

Also, if you're still able to reproduce it could you take a look at the `/api/table/:table-id/query_metadata` request when you load the datamodel (or query builder), find the field, and tell me what the `special_type` was marked as?

**Comment by pjaspers** [comment] 2018-05-09 08:35
@tlrobinson Sorry we fixed it by resyncing (which could use some love in the documentation)

The field in question was just a regular postgres datetime, somehow that got lost in the transition from 0.25 to 0.28 and it became a 'special field'.

**Comment by salsakran** [comment] 2019-08-19 21:29
@sbelak can you double check the spec for field_types and make sure we don't throw errors on previously valid names? 

in the words of RH `accretion is not breaking` (see https://www.case-podcast.org/20-problem-solving-and-clojure-19-with-rich-hickey/transcript)

**Comment by salsakran** [comment] 2019-08-19 21:30
to elaborate, we'll be adding + removing semantics types so we shouldn't be barfing on a type that is unknown to a given version. It's entirely possible it was added by a previous version and never upgraded. 

thoughts @camsaul  ?

**Comment by sbelak** [comment] 2019-08-20 12:23
The problem is our types are keywords and so you can't put metadata (deprecated) on them. I think the correct way to do this is to be mindful when doing migrations and update all the no longer present types to their ancestor or something. Having said that, I don't think this bug is due to a type being retired (I don't recall us ever doing that). Looking at .28.6 we didn't yet have a fingerprint for datetimes, so what I think happened here is that the op's instance was at some point downgraded resulting in there being fingerprints stored that the backend doesn't know what to do with. If we want fingerprints to be more resilient to downgrading (although I think a lot of our migrations are irreversible so it's questionable if it makes sense to harden), we can add `{s/Keyword s/Any}` to all the fingerprint Schemas.

**Comment by salsakran** [comment] 2019-10-01 02:12
closing this since there was only a single instance of it happening in the wild and it was fixed with a re-sync.

We should keep note of this when we examine the type system in the future.

**Closed by salsakran** 2019-10-01 02:12 UTC
Labels: Priority:P1, Type:Bug
