### ISSUE TITLE
cannot-read-properties-of-undefined-reading-rows

### ISSUE THREAD

**Issue by jazz788** [metabase/metabase#19543] opened 2022-01-04 21:32 UTC
![image](https://user-images.githubusercontent.com/66713895/148126523-afe89f9c-a770-4834-a117-e051eb2f2eb1.png)

https://discourse.metabase.com/t/cannot-read-properties-of-undefined-reading-rows/18166

{
"browser-info": {
"language": "en-US",
"platform": "Win32",
"userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62",
"vendor": "Google Inc."
},
"system-info": {
"file.encoding": "UTF-8",
"java.runtime.name": "OpenJDK Runtime Environment",
"java.runtime.version": "11.0.13+8",
"java.vendor": "Eclipse Adoptium",
"java.vendor.url": "https://adoptium.net/",
"java.version": "11.0.13",
"java.vm.name": "OpenJDK 64-Bit Server VM",
"java.vm.version": "11.0.13+8",
"os.name": "Linux",
"os.version": "4.14.248-129.473.amzn1.x86_64",
"user.language": "en",
"user.timezone": "GMT"
},
"metabase-info": {
"databases": [
"mysql",
"redshift",
"googleanalytics",
"snowflake"
],
"hosting-env": "unknown",
"application-database": "mysql",
"application-database-details": {
"database": {
"name": "MySQL",
"version": "8.0.25"
},
"jdbc-driver": {
"name": "MariaDB Connector/J",
"version": "2.6.2"
}
},
"run-mode": "prod",
"version": {
"date": "2021-12-16",
"tag": "v0.41.5",
"branch": "release-x.41.x",
"hash": "fbfffc6"
},
"settings": {
"report-timezone": null
}
}
}

**Comment by flamber** [comment] 2022-01-04 22:04
@jazz788 Please fill out the details with reproducible steps.

**Comment by jazz788** [comment] 2022-01-05 02:21
Hi @flamber we are 100% ok now. Our fix: we just went back and manually edited every record that had the characters that Metabase did not like - it was less than 30mins work, and we reconfigured some other things so that we don't send those characters again.  From where I"m sitting this is low or no priority, I just made this ticket as you asked for it. If someone does want to work on it, there is enough detail above plus my original post on discourse.

In  case it helps, in terms of reproducible steps, something like this ought to work - (apologies if this is not 'perfect' this is not really my space):

STEPS
1.  create a field: VARCHAR(1500) ENCODE lzo
2. put this data into it: 

``` test data.  | <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd"><html><body><div><div><div><p>test  </p><p>test  <a rel="noreferrer noopener" href="http://test.com/#" target="_blank"></p><p><a rel="noreferrer noopener" 
```
3. try to query it. 
4. Metabase will fail. saying: `Cannot read properties of undefined (reading 'rows')`

**Comment by flamber** [comment] 2022-01-26 19:08
Great that it fixed it for you, but I have not been able to reproduce with the steps you provide, so closing this issue and if someone else encounter the same problem, then perhaps they are able to provide steps to reproduce.

**Closed by flamber** 2022-01-26 19:08 UTC
Labels: Type:Bug, .Needs Triage

**Comment by caleb15** [comment] 2022-10-21 22:34
We got this error as well. In our case it was because of a bad row with a large amount of data in it's jsonb column. I'm not sure how much data exactly, but I'm guessing at least a million bytes, maybe ~50 million or more.

The workaround is deleting the bad row, selecting all columns except for the bad row, or casting the jsonb column to a size-limited varchar.
