### ISSUE TITLE
Middleware exceptions in metabase

### ISSUE THREAD

**Issue by vjvel** [metabase/metabase#24937] opened 2022-08-23 11:49 UTC
Every 5 seconds, getting the below error. We are using latest version v0.44. what is the reason for this error and how to fix it?

2022-08-23 11:34:08,715 INFO middleware.exceptions :: Request canceled before finishing.
2022-08-23 11:34:18,716 INFO middleware.exceptions :: Request canceled before finishing.
2022-08-23 11:34:18,716 INFO middleware.exceptions :: Request canceled before finishing.
2022-08-23 11:34:23,713 INFO middleware.exceptions :: Request canceled before finishing.
2022-08-23 11:34:28,715 INFO middleware.exceptions :: Request canceled before finishing.
2022-08-23 11:34:28,715 INFO middleware.exceptions :: Request canceled before finishing.
2022-08-23 11:34:33,715 INFO middleware.exceptions :: Request canceled before finishing.
2022-08-23 11:34:38,716 INFO middleware.exceptions :: Request canceled before finishing.
2022-08-23 11:34:43,714 INFO middleware.exceptions :: Request canceled before finishing.
2022-08-23 11:34:48,716 INFO middleware.exceptions :: Request canceled before finishing.
2022-08-23 11:34:58,713 INFO middleware.exceptions :: Request canceled before finishing.
2022-08-23 11:35:08,715 INFO middleware.exceptions :: Request canceled before finishing.
2022-08-23 11:35:08,716 INFO middleware.exceptions :: Request canceled before finishing.
2022-08-23 11:35:18,714 INFO middleware.exceptions :: Request canceled before finishing.
2022-08-23 11:35:18,715 INFO middleware.exceptions :: Request canceled before finishing.

**Comment by flamber** [comment] 2022-08-23 12:12
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Latest release is 0.44.1. It's not an error, it's a INFO. It's most likely caused by a reverse-proxy closing a connection too fast.

**Closed by flamber** 2022-08-23 12:12 UTC
Labels: Type:Bug, .Needs Triage

**Comment by adjenks** [comment] 2023-06-02 18:33
My logs are filled with this as well. 
Did you ever figure it out @vjvel ?

**Comment by paoliniluis** [comment] 2023-06-03 15:11
Please upgrade to latest version. This is the reverse proxy cutting connections

**Comment by SallyBlichG** [comment] 2023-09-20 11:33
> Please upgrade to latest version. This is the reverse proxy cutting connections

The same issue continues to persist in version 0.47.1 as well, and I want to emphasize that I have followed the log configuration [guide](https://www.metabase.com/docs/latest/configuring-metabase/log-configuration) provided.

@paoliniluis

**Comment by adjenks** [comment] 2023-10-04 21:58
@SallyBlichG if you've updated and followed the guide, then perhaps you should open a new ticket and link this one.

**Comment by paoliniluis** [comment] 2023-10-05 10:55
@SallyBlichG it’s your reverse proxy cutting connections, please check with your infrastructure team what’s going on there (most probably the health check endpoint is being called)
