### ISSUE TITLE
Jaggy scrolling in entity type picker in Admin > Table Metadata

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#38595] opened 2024-02-09 08:12 UTC
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/886ba877-1a8b-4346-abc1-d9fa19ebeb9a

### To Reproduce

1. Go to Admin > Table Metadata -> Data -> Sample Database -> Any table
2. Open entity type picker for any column
3. Scroll down in it
4. While holding the vertical scrollbar with your cursor, slowly scroll up

The content in the dropdown will jump up and down as you scroll up.
If you release the left mouse button, sometimes it will stay in the current place, but sometimes it will scroll up all the way to the top of the dropdown.

### Expected behavior

Scrolling is smooth

### Information about your Metabase installation

7eb7cd3, v48

### Severity

P3

**Comment by uladzimirdev** [comment] 2024-02-09 08:27
it's a duplicate of or similar to https://github.com/metabase/metabase/issues/36074
there could be more similar issues reported. 

@iethree can it be solved by migrating to a new popover?

**Comment by iethree** [comment] 2024-02-12 17:59
I wonder if we could move this whole component to Mantine Select 🤔

**Comment by npfitz** [comment] 2024-06-03 19:25
This was fixed by https://github.com/metabase/metabase/pull/40453

**Closed by npfitz** 2024-06-03 19:25 UTC
Labels: Type:Bug, Priority:P3, .Frontend, .Team/AdminWebapp
