### ISSUE TITLE
Selecting time in Time filters

### ISSUE THREAD

**Issue by Tonkonozhenko** [metabase/metabase#8522] opened 2018-09-14 15:00 UTC
Hi

I want to select a time in Time filter. I think it should be possible.

- Your databases: Redshift
- Metabase version: 0.30.2
- Metabase hosting environment: AWS ECS
- Metabase internal database: posgres

- *Repeatable steps to reproduce the issue*
- Create a dashboard filter
- Try to select time

![image](https://user-images.githubusercontent.com/1307646/45558235-1b4d3180-b848-11e8-9a36-cbc162dc4674.png)

**Comment by mazameli** [comment] 2018-09-14 16:40
Duplicate of https://github.com/metabase/metabase/issues/6660. (Can't believe I beat @jornh to this one. ;) )

**Closed by mazameli** 2018-09-14 16:40 UTC
Labels: Duplicate

**Comment by jornh** [comment] 2018-09-17 22:58
Haha 🤣 @mazameli seems you caught a blind spot on my issue similarly radar. Maybe a dead pixel?
