### ISSUE TITLE
Pulse schedules does not been sent

### ISSUE THREAD

**Issue by tl3shi** [metabase/metabase#7389] opened 2018-04-20 14:10 UTC
Hi, guys, 

I am using the latest metabase(v0.28.1).  I have configurated metabase email successfully (The test email can be received). 
 
It also works when I click "send email now" in the pulse edit pane. 

![image](https://user-images.githubusercontent.com/491629/39055314-82e41532-44e6-11e8-94cc-168a43197005.png)

However,  I have never received any schedule pulse emails.   I am wondering why and how to do to make it worked.

**Comment by senior** [comment] 2018-04-27 15:41
I'll need some more information to be able to troubleshoot this. Since the "Send email now" works, your email settings are correct. Do you see any errors in the log at the time the emails should be sent for the Pulse?

**Comment by tl3shi** [comment] 2018-04-28 03:33
@Senior  There's nothing in the log. Can I modify the log level (for example: trace) by add some parameter to the start command?

**Comment by luizarakaki** [comment] 2018-07-01 17:44
Same case here. We used Slack pulses for months and suddenly it stopped. Daily pulses and e-mails are not working. But both work when clicking on sending now.

We host Metabase on AWS EBS.

**Comment by FilippoPetroli** [comment] 2018-08-23 19:56
I had the same problem but i did what @luizarakaki said and solved the problem.

Thanks!!

**Comment by kuil09** [comment] 2018-08-23 23:37
@tl3shi are you using metabase docker?
then check the container's timezone.
https://github.com/metabase/metabase/issues/7682#issuecomment-415605328

**Comment by jornh** [comment] 2018-08-27 05:04
Moving @ShipraShalini @xjzhou and @vitorhirota over here from a duplicate bug report in #7682.

1. I suggest everybody upgrade to latest v0.30.x if possible for you. It includes the fix mentioned in 
https://github.com/metabase/metabase/issues/7682#issuecomment-407926230 as well as other changes related to pulses (and alert) handling. 

2. Since @luizarakaki surfaced one possible Metabase internal database related problem/fix with Postgres in https://github.com/metabase/metabase/issues/7389#issuecomment-401621759 please check if that would apply to your environment. 

3. I think it would be useful to know each of your configurations as requested in the issue template. For this particular bug I’ve highlight the important ones below:
> If you're filing an issue about a bug please include as much information
as you can including the following.
>
> - Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
> - Your operating system: (e.x. OS X 10, Windows XP, etc)
> - Your databases: (e.x. MySQL, Postgres, MongoDB, …)
> - **Metabase version**: (e.x. 0.19.3)
> - **Metabase hosting environment**: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
> - **Metabase internal database**: (e.x. H2 (default), MySQL, Postgres)
>
> - *Repeatable steps to reproduce the issue*

Thanks!

**Comment by vitorhirota** [comment] 2018-08-27 13:29
Thanks for the heads-up @jornh. I can confirm when upgraded to 0.30, pulses started to flow normally. So, I'm good :)

**Comment by nuk** [comment] 2019-02-14 10:05
Same here, but restarting our Postgres didn't work so I restarted the Metabase Server and things went well afterward.

I just felt bad that took me quite some time to stumble on such a simple solution.

**Comment by camsaul** [comment] 2019-05-13 20:47
It sounds like this have been fixed in 0.30.x+.

**Closed by camsaul** 2019-05-13 20:47 UTC
Labels: Bug, Priority/P2, Pulses

**Comment by satyaprakashaw28** [comment] 2019-06-18 16:33
Few other case where your pulses won't get delivered are (like we faced):
1) Email throttling from the service provider on the port from which you are trying to send the email
2) Limit of sending email might have reached
