### ISSUE TITLE
Bar chart not displaying the x axis value if it is having one value

### ISSUE THREAD

**Issue by ankitanubhav212** [metabase/metabase#9034] opened 2018-11-28 04:20 UTC
Not displaying the value in x axis if it has only one value. 
<img width="1571" alt="screenshot 2018-11-13 at 12 41 04 pm" src="https://user-images.githubusercontent.com/31243315/49128721-ab046700-f2f2-11e8-8251-4bfbcb8a531c.png">
<img width="1599" alt="screenshot 2018-11-13 at 12 40 39 pm" src="https://user-images.githubusercontent.com/31243315/49128728-ae97ee00-f2f2-11e8-984d-2a024e025975.png">

**Comment by MarkRx** [comment] 2018-11-28 18:40
Looks like #8540

**Comment by salsakran** [comment] 2018-12-28 02:47
dupe of #8540 as @MarkRx points out

**Closed by salsakran** 2018-12-28 02:47 UTC
