### ISSUE TITLE
Fingerprint update logic is wrong

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#9124] opened 2018-12-13 18:57 UTC
Currently we track the fingerprint version per base_type (https://github.com/metabase/metabase/blob/master/src/metabase/sync/interface.clj#L163), however the version storred with each field is the the global max fingerprint version (`latest-fingerprint-version` -- https://github.com/metabase/metabase/blob/master/src/metabase/sync/analyze/fingerprint.clj#L31). This breaks the update logic as a field will get re-fingerprinted only if the type with the highest version number got bumped. 

Example:
Starting from:
```
(def fingerprint-version->types-that-should-be-re-fingerprinted
  {1 #{:type/*}
   2 #{:type/Number}
   3 #{:type/DateTime}})
```
if we it change to
```
(def fingerprint-version->types-that-should-be-re-fingerprinted
  {1 #{:type/*}
   3 #{:type/DateTime :type/Number}})

(count (fields-to-fingerprint (Table 2))) => 0
``` 
however
```
(def fingerprint-version->types-that-should-be-re-fingerprinted
  {1 #{:type/*}
   4 #{:type/Number}
   3 #{:type/DateTime}})

(count (fields-to-fingerprint (Table 2))) => 7
``` 

Unless I'm missing some intricacy, the fix should be straightforward, we just need to store the corresponding version from `fingerprint-version->types-that-should-be-re-fingerprinted` for each field (and bump the fingerprint version to 4 across the board to trigger recalculation).

**Comment by camsaul** [comment] 2018-12-13 23:08
Unless I'm misunderstanding what you're saying, that's intentional behavior, I guess it's not totally clear why we're doing things this way so I'll make a note to add some more documentation in that namespace explaining the reasoning behind it. But here's the idea:

The basic problem is that fingerprinting Fields is expensive and we'd like to minimize the amount of times we do it. If we add some new classifiers to fingerprints, we will want to update certain fingerprints -- only the ones for Fields that would be affected by the new classifiers. For example, let's say we add an `%odd` property to the fingerprint for `type/Integer` Fields. There would be no point in re-fingerprinting `type/Text` fields -- this new property would not be part of their fingerprints. We only want to re-fingerprint `type/Integer` Fields.

So we'll add a new entry to `fingerprint-version->types-that-should-be-re-fingerprinted`:
```clj
(def fingerprint-version->types-that-should-be-re-fingerprinted
  {1 #{:type/*}
   2 #{:type/Number}
   3 #{:type/DateTime}
   ;; 4 is the new version
   4 #{:type/Integer}})
```

This means that any Field whose base type derives from `:type/Integer` that has a fingerprint less than version `4` should get re-fingerprinted. `:type/Integer` Fields with fingerprint version 3 will get re-fingerprinted. `:type/Text` Fields with version 3 will not.

Of course, any other Fields that happen to get new fingerprint in that time for whatever reason (e.g. a newly-added Table) will also get saved as having the latest fingerprint version (`4`) because they used the 
"version 4" version of our fingerprint logic to generate their Fingerprint. It ultimately doesn't make a difference that version 3 and version 4 are the same for `type/Text` Fields. If a version 5 comes along that changes fingerprints for `type/Text` Fields. we'll update both of them.

It's probably most helpful to think of `fingerprint-version->types-that-should-be-re-fingerprinted` sort of like a list of database migrations -- when we add or change classifiers, we add an entry to the map so Metabase knows it needs to "migrate" certain Fields to the latest version; these entires, like database migrations, shouldn't be changed after they're added -- for further updates, add a new entry instead. 

So in your example I would say it's expected behavior that no new Fields are marked as needing an update if you change the `fingerprint-version->types-that-should-be-re-fingerprinted` entry after they've already been fingerprinted with that version -- just like you wouldn't expect changing a database migration that's already been ran to run again simply because it was changed. If you're updating classifiers, the logic assumes you'll add new entries along with each new set of updates.

Does that make sense?

**Comment by sbelak** [comment] 2018-12-14 07:46
Ok. So the correct usage of `fingerprint-version->types-that-should-be-re-fingerprinted` is to always bump the highest number, rather than viewing it as versions for indivitual fingerprint types and shuld be read as a log (in v3 we've updated numbers, in v4 we've updated numbers and dates, ...)?

**Comment by camsaul** [comment] 2018-12-14 17:01
Yes exactly

**Closed** 2018-12-14 17:09 UTC
Labels: Metadata/Sync
