### ISSUE TITLE
Query error unavailable because of run-button overlay

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12586] opened 2020-05-25 21:34 UTC
**Describe the bug**
When running a query that ends in failure, can cause error details to become unavailable because of run-button overlay.

**Logs**
```
Firefox:
TypeError: "t.data is undefined"

Chromium:
TypeError: Cannot read property 'rows' of undefined
```

**To Reproduce** _until issue #12585 is fixed - otherwise different steps for 1+2 would be needed_
1. Simple question > Sample Dataset > Orders
2. Summarize "Cumulative sum of Discount" by CreatedAt:Month
3. Query fails with error, but refresh-button is showing on top of the error, so it's not possible to see error details, only the vague title "There was a problem with your question".
![image](https://user-images.githubusercontent.com/1447303/82843473-7e2c1280-9edd-11ea-8dba-7f5dc6055331.png)
4. Going to Admin > Troubleshooting > Logs, will show the error - including stacktrace.

**Information about your Metabase Installation:**
Metabase 0.35.3 and `master`

**Comment by OptimusOS** [comment] 2020-07-03 09:44
I have the same problem with the version: v0.35.4

**Comment by flamber** [comment] 2021-06-29 14:52
@nemanjaglumac I don't know any other easy way to reproduce, besides 13536 and 14985.

**Comment by WiNloSt** [comment] 2023-08-30 09:32
Since https://github.com/metabase/metabase/issues/14985 is fixed and I couldn't reproduce this with https://github.com/metabase/metabase/issues/13536#issuecomment-1698821475, maybe we should close this issue? @NevRA @nemanjaglumac what do you guys think?

**Comment by kamilmielnik** [comment] 2024-03-04 13:54
I can reproduce it in `master` at a926009707 with a bit of extra code to simulate BE failing.

```patch
diff --git a/frontend/src/metabase/services.js b/frontend/src/metabase/services.js
index 6e72fe19bd..d6e2d7da0f 100644
--- a/frontend/src/metabase/services.js
+++ b/frontend/src/metabase/services.js
@@ -375,7 +375,9 @@ export const MetabaseApi = {
   field_discard_values: POST("/api/field/:fieldId/discard_values"),
   field_search: GET("/api/field/:fieldId/search/:searchFieldId"),
   field_remapping: GET("/api/field/:fieldId/remapping/:remappedFieldId"),
-  dataset: POST("/api/dataset"),
+  dataset: () => {
+    throw new Error("Simulated error");
+  },
   dataset_pivot: POST("/api/dataset/pivot"),
   dataset_duration: POST("/api/dataset/duration"),
   native: POST("/api/dataset/native"),
```

1. Apply the above patch
2. Create and visualize any question

**Comment by kamilmielnik** [comment] 2024-07-17 14:44
Another way to reproduce:

1. New > Question > Orders > Visualize
2. Disable network
3. Summarize > Done

**Comment by ranquild** [comment] 2024-10-28 07:03
I think the fix is remove the overlay in this case. There is another run button in the header.

**Closed** 2024-10-29 11:43 UTC
Labels: Type:Bug, Priority:P2, .Frontend, Querying/GUI, .Team/Querying
