### ISSUE TITLE
Can't change default filter date options on SQL questions

### ISSUE THREAD

**Issue by sicarul** [metabase/metabase#46342] opened 2024-07-31 18:20 UTC
### Describe the bug

When trying to set a default value for a date filter, clicking on the 3 dots to specify current day/week/etc and to choose if it starts from X previous days/weeks/etc shows up behind the dialog, so i can't properly click on it, seems to be a CSS bug?

![image](https://github.com/user-attachments/assets/54a9e0ad-a16e-4c59-bac5-40f0d3877881)

### To Reproduce

Create a field filter with type "Date filter" and try to filter on it
![image](https://github.com/user-attachments/assets/7788a58a-fd24-49df-9895-5290556cd45e)

### Expected behavior

I should be able to select the options same as in the report itself
![image](https://github.com/user-attachments/assets/f1db81db-4b93-43f3-9a6c-2b8493fe3b89)

### Logs

This happens in the frontend

### Information about your Metabase installation

```JSON
v0.50.17
```

### Severity

Annoying because i can't properly set default values for date filters

**Comment by noahmoss** [comment] 2024-07-31 18:45
I can repro on 50.17 but not on master

**Comment by sicarul** [comment] 2024-07-31 19:25
Just upgraded to 0.50.18 and still seeing the same behavior.

**Comment by nemanjaglumac** [comment] 2024-08-12 22:39
Fixed by https://github.com/metabase/metabase/pull/46702.
It was a silly z-index issue caused by having a mix of new and old popovers. New has z-index 300, and the old one has z-index 4.

Should go out in v0.50.20, so @sicarul keep an eye on it 👀 .

**Closed by nemanjaglumac** 2024-08-12 22:39 UTC
Labels: Type:Bug, Priority:P2, Querying/Parameters & Variables, .Team/QueryingComponents

**Comment by sicarul** [comment] 2024-08-12 23:05
> Fixed by #46702. It was a silly z-index issue caused by having a mix of new and old popovers. New has z-index 300, and the old one has z-index 4.
> 
> Should go out in v0.50.20, so @sicarul keep an eye on it 👀 .

I imagined something with a z-index being faulty but i don't know enough about Metabase's source code to make a PR yet 😅  Thanks!
