### ISSUE TITLE
Columns in table wont sync

### ISSUE THREAD

**Issue by 0xicl33n** [metabase/metabase#7249] opened 2018-03-31 12:22 UTC
- Browser: Chrome Version 65.0.3325.181 (Official Build) (64-bit)
- OS: Windows 10 64bit, Debian 9.4 64bit, Docker container
- Database: MongoDB 3.4
- Metabase version: 0.28.4
- Metabase hosting environment: jar
- Metabase internal database: default

I have one table in my mogodb database that will not sync with metabase. It is the most important of all of the tables in my DB and i cannot figure out why it will not sync. This is the error i get. Ive tried running metabase off my desktop, my vps server and off docker and they all have the same issue. How do i fix this?

```
03-31 12:15:32 ERROR sync.util :: Error syncing fields for Table 5 'switch': class java.lang.NullPointerException
("driver.mongo$describe_table_field.invokeStatic(mongo.clj:123)"
 "driver.mongo$describe_table_field.invoke(mongo.clj:120)"
 "driver.mongo$describe_table$f__50080__auto____50960$iter__50961__50965$fn__50966.invoke(mongo.clj:165)"
 "driver.mongo$describe_table$f__50080__auto____50960.invoke(mongo.clj:164)"
 "driver.mongo.util$_with_mongo_connection$fn__50073.invoke(util.clj:116)"
 "util.ssh$with_ssh_tunnel_STAR_.invokeStatic(ssh.clj:106)"
 "util.ssh$with_ssh_tunnel_STAR_.invoke(ssh.clj:91)"
 "driver.mongo.util$_with_mongo_connection.invokeStatic(util.clj:95)"
 "driver.mongo.util$_with_mongo_connection.invoke(util.clj:90)"
 "driver.mongo$describe_table.invokeStatic(mongo.clj:160)"
 "driver.mongo$describe_table.invoke(mongo.clj:159)"
 "driver$fn__25758$G__25590__25767.invoke(driver.clj:51)"
 "sync.fetch_metadata$fn__36311$table_metadata__36316$fn__36317.invoke(fetch_metadata.clj:18)"
 "sync.fetch_metadata$fn__36311$table_metadata__36316.invoke(fetch_metadata.clj:15)"
 "sync.sync_metadata.fields$fn__36872$db_metadata__36877$fn__36878.invoke(fields.clj:294)"
 "sync.sync_metadata.fields$fn__36872$db_metadata__36877.invoke(fields.clj:290)"
 "sync.sync_metadata.fields$fn__36900$sync_fields_for_table_BANG___36909$fn__36912$fn__36913.invoke(fields.clj:307)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:124)"
 "sync.util$do_with_error_handling.invoke(util.clj:119)"
 "sync.sync_metadata.fields$fn__36900$sync_fields_for_table_BANG___36909$fn__36912.invoke(fields.clj:306)"
 "sync.sync_metadata.fields$fn__36900$sync_fields_for_table_BANG___36909.invoke(fields.clj:301)"
 "sync.sync_metadata.fields$fn__36900$sync_fields_for_table_BANG___36909$fn__36910.invoke(fields.clj:304)"
 "sync.sync_metadata.fields$fn__36900$sync_fields_for_table_BANG___36909.invoke(fields.clj:301)"
 "sync.sync_metadata$fn__37532$sync_table_metadata_BANG___37537$fn__37538.invoke(sync_metadata.clj:37)"
 "sync.sync_metadata$fn__37532$sync_table_metadata_BANG___37537.invoke(sync_metadata.clj:34)"
 "sync$fn__37582$sync_table_BANG___37587$fn__37588.invoke(sync.clj:38)"
 "sync$fn__37582$sync_table_BANG___37587.invoke(sync.clj:35)"
 "api.table$fn__39124$fn__39127.invoke(table.clj:79)"
 "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:254)"
 "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)"
 "api.table$fn__39124.invokeStatic(table.clj:52)"
 "api.table$fn__39124.invoke(table.clj:52)"
 "middleware$enforce_authentication$fn__37770.invoke(middleware.clj:117)"
 "api.routes$fn__46912.invokeStatic(routes.clj:87)"
 "api.routes$fn__46912.invoke(routes.clj:87)"
 "routes$fn__46957$fn__46958.doInvoke(routes.clj:106)"
 "routes$fn__46957.invokeStatic(routes.clj:101)"
 "routes$fn__46957.invoke(routes.clj:101)"
 "middleware$log_api_call$fn__37869$fn__37871.invoke(middleware.clj:347)"
 "middleware$log_api_call$fn__37869.invoke(middleware.clj:346)"
 "middleware$add_security_headers$fn__37819.invoke(middleware.clj:249)"
 "core$wrap_streamed_json_response$fn__52142.invoke(core.clj:67)"
 "middleware$bind_current_user$fn__37774.invoke(middleware.clj:138)"
 "middleware$maybe_set_site_url$fn__37823.invoke(middleware.clj:273)")
```
Here is an example of what the data looks like, i used [robo3t](https://robomongo.org/) to grab this in a "json like" format.

```
{
    "_id" : ObjectId("59d891405c669610c59406e3"),
    "discordId" : "158163424004538369",
    "FC" : "SW-4604-8159-9402",
    "tier" : null,
    "CB" : "S+",
    "IGN" : "sε|Jσnny",
    "level" : 66,
    "salmon" : "Profreshional",
    "RM" : "S+9",
    "TC" : "S+9",
    "SZ" : "S+9",
    "team" : 2316.3,
    "W1" : "Rapid Blaster",
    "W2" : "Foil Flingza Roller",
    "W3" : "Splattershot",
    "pair" : "2371.2",
    "splat" : "Egg",
    "clan" : "Senkura (sε)",
    "map" : "musselforge fitness",
    "rm_xPwr" : "null",
    "tc_xPwr" : "null",
    "sz_xPwr" : "null",
    "cb_xPwr" : "null"
}
```

**Comment by jornh** [comment] 2018-03-31 16:54
Related: https://github.com/metabase/metabase/issues/6975 (maybe even duplicate?)

Note: There’s a proposed workaround in https://github.com/metabase/metabase/issues/6975#issuecomment-371136192

**Comment by salsakran** [comment] 2018-04-02 23:39
closing this as a dupe of #6975 and bumping the severity of that issue as lots of people seem to be hitting this.

**Closed by salsakran** 2018-04-02 23:39 UTC
Labels: Bug, Database/Mongo, Metadata/Sync
