### ISSUE TITLE
The Metabase server terminated unexpectedly (since last update of the macOS app)

### ISSUE THREAD

**Issue by alexsonnay** [metabase/metabase#5608] opened 2017-07-27 15:14 UTC
![image](https://user-images.githubusercontent.com/28756458/28677802-e7d54c56-72ee-11e7-9e69-45f78d1cd424.png)

**Comment by camsaul** [comment] 2017-07-27 18:23
Hi @alexsonnay, can you open `Console.app` and filter by `Metabase`, and try starting it again? If you could post what you see in the those logs here it would be super helpful

**Comment by michaelfeihstel** [comment] 2017-09-28 12:58
I'm seeing the same problem. Here's my console log:

    standard	14:52:41.494576 +0200	Metabase	0x107bf2c00 - DocumentLoader::startLoadingMainResource: Returning empty document (frame = 0x1079b9000, main = 1)
    standard	14:52:41.494631 +0200	Metabase	Memory usage info dump at MainFrameLoadCompleted:
    standard	14:52:41.494645 +0200	Metabase	  javascript_gc_heap_capacity: 65536
    standard	14:52:41.494657 +0200	Metabase	  document_count: 1
    standard	14:52:41.494690 +0200	Metabase	  pagecache_page_count: 0
    standard	14:52:41.494714 +0200	Metabase	  compressed: 0
    standard	14:52:41.494724 +0200	Metabase	  virtual_size: 3664314368
    standard	14:52:41.494750 +0200	Metabase	  internal: 4907008
    standard	14:52:41.494762 +0200	Metabase	  javascript_gc_heap_extra_memory_size: 0
    standard	14:52:41.494786 +0200	Metabase	  phys_footprint: 4902912
    standard	14:52:41.494798 +0200	Metabase	  resident_size: 35016704
    standard	14:52:41.494945 +0200	Metabase	0x7fb973605370 - PerformanceMonitor::measureCPUUsageInActivityState: Process is using 84.8% CPU in state:     VisibleNonActive
    standard	14:52:41.523682 +0200	Metabase	NSWindow warning: adding an unknown subview: <INMovableByBackgroundContainerView: 0x618000320be0>. Break on NSLog     to debug.
    standard	14:52:41.525221 +0200	Metabase	Call stack:
    (
    	0   AppKit                              0x00007fff84191aed -[NSThemeFrame addSubview:] + 109
    	1   AppKit                              0x00007fff84191838 -[NSView addSubview:positioned:relativeTo:] + 217
    	2   AppKit                              0x00007fff849a8ac5 -[NSThemeFrame addSubview:positioned:relativeTo:] + 43
    	3   Metabase                            0x00000001051da2af Metabase + 53935
    	4   Metabase                            0x00000001051d9081 Metabase + 49281
    	5   Metabase                            0x00000001051d7243 Metabase + 41539
    	6   AppKit                              0x00007fff841fc6f7 -[NSWindowTemplate nibInstantiate] + 478
    	7   AppKit                              0x00007fff84145e72 -[NSIBObjectData instantiateObject:] + 286
    	8   AppKit                              0x00007fff84145568 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 591
    	9   AppKit                              0x00007fff8413caf0 loadNib + 375
    	10  AppKit                              0x00007fff8
    standard	14:52:41.541167 +0200	Metabase	0x7fb973605370 - PerformanceMonitor::measureCPUUsageInActivityState: Process is using 97.7% CPU in state: NonVisible
    standard	14:52:41.627884 +0200	Metabase	0x7fb973605370 - PerformanceMonitor::measureCPUUsageInActivityState: Process is using 93.1% CPU in state:     VisibleNonActive
    standard	14:52:41.630711 +0200	Metabase	Using port 13150
    standard	14:52:41.630768 +0200	Metabase	(re)starting health checker @ 0x60800007f040...
    standard	14:52:41.630841 +0200	Metabase	Deleting /Users/ulflunge/Library/Application Support/Metabase/metabase.db.lock.db...
    standard	14:52:41.631170 +0200	Metabase	Starting MetabaseTask @ 0x608000246090...
    standard	14:52:41.631521 +0200	Metabase	Launching MetabaseTask
    MB_DB_FILE='/Users/ulflunge/Library/Application Support/Metabase/metabase.db'
    MB_PLUGINS_DIR='/Users/ulflunge/Library/Application Support/Metabase/Plugins'
    MB_JETTY_PORT=13150
    /Applications/Metabase.app/Contents/Resources/jre/bin/java -jar /Applications/Metabase.app/Contents/Resources/metabase.jar
    standard	14:52:41.649030 +0200	Metabase	Faulting in NSHTTPCookieStorage singleton
    standard	14:52:41.649050 +0200	Metabase	Faulting in CFHTTPCookieStorage singleton
    standard	14:52:41.649061 +0200	Metabase	Creating default cookie storage with process/bundle identifier
    standard	14:52:41.652527 +0200	Metabase	UNIX error exception: 17
    standard	14:52:41.652798 +0200	Metabase	0x618000267800 opened /private/var/db/mds/system/mdsDirectory.db: 50744 bytes
    standard	14:52:41.653768 +0200	Metabase	UNIX error exception: 17
    standard	14:52:41.654047 +0200	Metabase	UNIX error exception: 17
    standard	14:52:41.654173 +0200	Metabase	UNIX error exception: 17
    standard	14:52:41.654380 +0200	Metabase	UNIX error exception: 17
    standard	14:52:41.654484 +0200	Metabase	UNIX error exception: 17
    standard	14:52:41.654554 +0200	Metabase	0x61800026aa80 opened /Users/ulflunge/Library/Keychains/login.keychain-db: 467684 bytes
    standard	14:52:41.657799 +0200	Metabase	0x610000260000 opened /Library/Keychains/System.keychain: 37028 bytes
    standard	14:52:41.660844 +0200	Metabase	TIC TCP Conn Start [1:0x610000396650]
    standard	14:52:41.724276 +0200	Metabase	TIC TCP Conn Event [1:0x610000396650]: 1 Err(0)
    standard	14:52:41.724322 +0200	Metabase	TIC TCP Conn Connected [1:0x610000396650]: Err(0)
    standard	14:52:41.724447 +0200	Metabase	TIC Enabling TLS [1:0x610000396650]
    standard	14:52:41.952581 +0200	Metabase	TIC TLS Event [1:0x610000396650]: 2, Pending(0)
    standard	14:52:41.960983 +0200	Metabase	TIC TLS Event [1:0x610000396650]: 11, Pending(0)
    standard	14:52:41.961275 +0200	Metabase	UNIX error exception: 17
    standard	14:52:41.961480 +0200	Metabase	UNIX error exception: 17
    standard	14:52:41.961980 +0200	Metabase	TIC TLS Event [1:0x610000396650]: 12, Pending(0)
    standard	14:52:41.962092 +0200	Metabase	TIC TLS Event [1:0x610000396650]: 14, Pending(0)
    standard	14:52:41.974531 +0200	Metabase	TIC TLS Trust Result [1:0x610000396650]: 0
    standard	14:52:42.126871 +0200	Metabase	TIC TLS Event [1:0x610000396650]: 20, Pending(0)
    standard	14:52:42.127866 +0200	Metabase	TIC TCP Conn Event [1:0x610000396650]: 8 Err(0)
    standard	14:52:42.127885 +0200	Metabase	TIC TLS Handshake Complete [1:0x610000396650]
    standard	14:52:42.609546 +0200	Metabase	INFO metabase.util :: Loading Metabase...
    standard	14:52:43.595875 +0200	Metabase	0x7fb973605370 - PerformanceMonitor::measureCPUUsageInActivityState: Process is using 5.2% CPU in state:     VisibleAndActive
    standard	14:52:43.699085 +0200	Metabase	TIC TCP Conn Start [2:0x610000396cd0]
    standard	14:52:43.700783 +0200	Metabase	TIC TCP Conn Event [2:0x610000396cd0]: 3 Err(61)
    fehler	14:52:43.700805 +0200	Metabase	TIC TCP Conn Failed [2:0x610000396cd0]: 1:61 Err(61)
    standard	14:52:43.700823 +0200	Metabase	TIC TCP Conn Cancel [2:0x610000396cd0]
    standard	14:52:43.700841 +0200	Metabase	TIC TCP Conn Destroyed [2:0x610000396cd0]
    fehler	14:52:43.701022 +0200	Metabase	HTTP load failed (error code: -1004 [1:61])
    fehler	14:52:43.701084 +0200	Metabase	NSURLConnection finished with error - code -1004
    standard	14:52:43.701919 +0200	Metabase	😷
    standard	14:52:44.200782 +0200	Metabase	INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓 
    See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
    standard	14:52:46.481382 +0200	Metabase	TIC TCP Conn Start [3:0x600000380410]
    standard	14:52:46.483058 +0200	Metabase	TIC TCP Conn Event [3:0x600000380410]: 3 Err(61)
    fehler	14:52:46.483073 +0200	Metabase	TIC TCP Conn Failed [3:0x600000380410]: 1:61 Err(61)
    standard	14:52:46.483086 +0200	Metabase	TIC TCP Conn Cancel [3:0x600000380410]
    standard	14:52:46.483102 +0200	Metabase	TIC TCP Conn Destroyed [3:0x600000380410]
    fehler	14:52:46.483198 +0200	Metabase	HTTP load failed (error code: -1004 [1:61])
    fehler	14:52:46.483251 +0200	Metabase	NSURLConnection finished with error - code -1004
    standard	14:52:46.483369 +0200	Metabase	😷
    standard	14:52:47.798335 +0200	Metabase	TIC TCP Conn Start [4:0x608000381040]
    standard	14:52:47.800979 +0200	Metabase	TIC TCP Conn Event [4:0x608000381040]: 3 Err(61)
    fehler	14:52:47.801009 +0200	Metabase	TIC TCP Conn Failed [4:0x608000381040]: 1:61 Err(61)
    standard	14:52:47.801022 +0200	Metabase	TIC TCP Conn Cancel [4:0x608000381040]
    standard	14:52:47.801043 +0200	Metabase	TIC TCP Conn Destroyed [4:0x608000381040]
    fehler	14:52:47.801209 +0200	Metabase	HTTP load failed (error code: -1004 [1:61])
    fehler	14:52:47.801250 +0200	Metabase	NSURLConnection finished with error - code -1004
    standard	14:52:47.801357 +0200	Metabase	😷
    standard	14:52:48.244848 +0200	Metabase	0x7fb973605370 - PerformanceMonitor::measureCPUUsageInActivityState: Process is using 2.2% CPU in state:     VisibleNonActive
    standard	14:52:48.628016 +0200	Metabase	TIC TCP Conn Event [1:0x610000396650]: 2 Err(0)
    standard	14:52:48.628049 +0200	Metabase	TIC TCP Conn Cancel [1:0x610000396650]
    standard	14:52:48.628102 +0200	Metabase	TIC TCP Conn Destroyed [1:0x610000396650]
    standard	14:52:50.522922 +0200	Metabase	TIC TCP Conn Start [5:0x6080003801a0]
    standard	14:52:50.526057 +0200	Metabase	TIC TCP Conn Event [5:0x6080003801a0]: 3 Err(61)
    fehler	14:52:50.526096 +0200	Metabase	TIC TCP Conn Failed [5:0x6080003801a0]: 1:61 Err(61)
    standard	14:52:50.526107 +0200	Metabase	TIC TCP Conn Cancel [5:0x6080003801a0]
    standard	14:52:50.526138 +0200	Metabase	TIC TCP Conn Destroyed [5:0x6080003801a0]
    fehler	14:52:50.526259 +0200	Metabase	HTTP load failed (error code: -1004 [1:61])
    fehler	14:52:50.526375 +0200	Metabase	NSURLConnection finished with error - code -1004
    standard	14:52:50.526505 +0200	Metabase	😷
    standard	14:52:52.460931 +0200	Metabase	TIC TCP Conn Start [6:0x610000396720]
    standard	14:52:52.463482 +0200	Metabase	TIC TCP Conn Event [6:0x610000396720]: 3 Err(61)
    fehler	14:52:52.463510 +0200	Metabase	TIC TCP Conn Failed [6:0x610000396720]: 1:61 Err(61)
    standard	14:52:52.463548 +0200	Metabase	TIC TCP Conn Cancel [6:0x610000396720]
    standard	14:52:52.463562 +0200	Metabase	TIC TCP Conn Destroyed [6:0x610000396720]
    fehler	14:52:52.463766 +0200	Metabase	HTTP load failed (error code: -1004 [1:61])
    fehler	14:52:52.463828 +0200	Metabase	NSURLConnection finished with error - code -1004
    standard	14:52:52.463937 +0200	Metabase	😷
    standard	14:52:52.576143 +0200	Metabase	0x7fb973605370 - PerformanceMonitor::measureCPUUsageInActivityState: Process is using 0.8% CPU in state:     VisibleAndActive
    standard	14:52:53.813750 +0200	Metabase	TIC TCP Conn Start [7:0x6100003967f0]
    standard	14:52:53.816364 +0200	Metabase	TIC TCP Conn Event [7:0x6100003967f0]: 3 Err(61)
    fehler	14:52:53.816385 +0200	Metabase	TIC TCP Conn Failed [7:0x6100003967f0]: 1:61 Err(61)
    standard	14:52:53.816397 +0200	Metabase	TIC TCP Conn Cancel [7:0x6100003967f0]
    standard	14:52:53.816413 +0200	Metabase	TIC TCP Conn Destroyed [7:0x6100003967f0]
    fehler	14:52:53.816531 +0200	Metabase	HTTP load failed (error code: -1004 [1:61])
    fehler	14:52:53.816589 +0200	Metabase	NSURLConnection finished with error - code -1004
    standard	14:52:53.816706 +0200	Metabase	😷
    standard	14:52:56.574388 +0200	Metabase	TIC TCP Conn Start [8:0x608000381040]
    standard	14:52:56.577095 +0200	Metabase	TIC TCP Conn Event [8:0x608000381040]: 3 Err(61)
    fehler	14:52:56.577137 +0200	Metabase	TIC TCP Conn Failed [8:0x608000381040]: 1:61 Err(61)
    standard	14:52:56.577148 +0200	Metabase	TIC TCP Conn Cancel [8:0x608000381040]
    standard	14:52:56.577163 +0200	Metabase	TIC TCP Conn Destroyed [8:0x608000381040]
    fehler	14:52:56.577246 +0200	Metabase	HTTP load failed (error code: -1004 [1:61])
    fehler	14:52:56.577277 +0200	Metabase	NSURLConnection finished with error - code -1004
    standard	14:52:56.577381 +0200	Metabase	😷
    standard	14:52:57.951938 +0200	Metabase	TIC TCP Conn Start [9:0x618000382d80]
    standard	14:52:57.954187 +0200	Metabase	TIC TCP Conn Event [9:0x618000382d80]: 3 Err(61)
    fehler	14:52:57.954215 +0200	Metabase	TIC TCP Conn Failed [9:0x618000382d80]: 1:61 Err(61)
    standard	14:52:57.954226 +0200	Metabase	TIC TCP Conn Cancel [9:0x618000382d80]
    standard	14:52:57.954255 +0200	Metabase	TIC TCP Conn Destroyed [9:0x618000382d80]
    fehler	14:52:57.954360 +0200	Metabase	HTTP load failed (error code: -1004 [1:61])
    fehler	14:52:57.954406 +0200	Metabase	NSURLConnection finished with error - code -1004
    standard	14:52:57.954512 +0200	Metabase	😷
    standard	14:52:59.281373 +0200	Metabase	INFO metabase.core :: Starting Metabase in STANDALONE mode
    standard	14:52:59.290654 +0200	Metabase	INFO metabase.core :: Launching Embedded Jetty Webserver with config:
    {:port 13150}
    standard	14:52:59.324838 +0200	Metabase	INFO metabase.core :: Starting Metabase version v0.26.1 (dacff52 release-0.26.1) ...
    INFO metabase.core :: System timezone is 'Europe/Berlin' ...
    standard	14:52:59.451344 +0200	Metabase	WARN metabase.driver :: No -init-driver function found for 'metabase.driver.google'
    standard	14:52:59.632734 +0200	Metabase	INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
    standard	14:52:59.633341 +0200	Metabase	INFO metabase.db :: Verifying h2 Database Connection ...
    standard	14:53:00.534962 +0200	Metabase	TIC TCP Conn Start [10:0x618000382d80]
    standard	14:53:00.537445 +0200	Metabase	TIC TCP Conn Event [10:0x618000382d80]: 1 Err(0)
    standard	14:53:00.537477 +0200	Metabase	TIC TCP Conn Connected [10:0x618000382d80]: Err(0)
    standard	14:53:00.578338 +0200	Metabase	😷
    standard	14:53:02.621137 +0200	Metabase	😷
    standard	14:53:04.576590 +0200	Metabase	😷
    standard	14:53:04.634612 +0200	Metabase	ERROR metabase.driver :: Failed to connect to database: Timed out after 5000 milliseconds.
    standard	14:53:04.640219 +0200	Metabase	java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
    (binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine     details))
    standard	14:53:04.642608 +0200	Metabase	at metabase.db$verify_db_connection.invokeStatic(db.clj:334)
    at metabase.db$verify_db_connection.invoke(db.clj:327)
    at metabase.db$verify_db_connection.invokeStatic(db.clj:330)
    at metabase.db$verify_db_connection.invoke(db.clj:327)
    at metabase.db$setup_db_BANG_.invokeStatic(db.clj:382)
    at metabase.db$setup_db_BANG_.doInvoke(db.clj:376)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at metabase.core$init_BANG_.invokeStatic(core.clj:103)
    at metabase.core$init_BANG_.invoke(core.clj:82)
    at metabase.core$start_normally.invokeStatic(core.clj:187)
    at metabase.core$start_normally.invoke(core.clj:181)
    at metabase.core$_main.invokeStatic(core.clj:285)
    at metabase.core$_main.doInvoke(core.clj:280)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at clojure.lang.AFn.applyToHelper(AFn.java:152)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at metabase.core.main(Unknown Source)
    ERROR metabase.core :: Metabase Initialization FAILED:  Assert failed: Unable to connect to Metabase h2 DB.
    (binding [*allow-potentailly-u<…>
    standard	14:53:04.642832 +0200	Metabase	INFO metabase.core :: Metabase Shutting Down ...
    INFO metabase.core :: Metabase Shutdown COMPLETE
    standard	14:53:05.091444 +0200	Metabase	TIC TCP Conn Event [10:0x618000382d80]: 2 Err(0)
    standard	14:53:05.091579 +0200	Metabase	TIC TCP Conn Cancel [10:0x618000382d80]
    standard	14:53:05.091671 +0200	Metabase	TIC TCP Conn Destroyed [10:0x618000382d80]
    standard	14:53:05.091970 +0200	Metabase	
    
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Task terminated with exit code 1 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    standard	14:53:05.882580 +0200	Metabase	TIC TCP Conn Start [11:0x600000381110]
    standard	14:53:05.885485 +0200	Metabase	TIC TCP Conn Event [11:0x600000381110]: 3 Err(61)
    fehler	14:53:05.885528 +0200	Metabase	TIC TCP Conn Failed [11:0x600000381110]: 1:61 Err(61)
    standard	14:53:05.885540 +0200	Metabase	TIC TCP Conn Cancel [11:0x600000381110]
    standard	14:53:05.885556 +0200	Metabase	TIC TCP Conn Destroyed [11:0x600000381110]
    fehler	14:53:05.885679 +0200	Metabase	HTTP load failed (error code: -1004 [1:61])
    fehler	14:53:05.885731 +0200	Metabase	NSURLConnection finished with error - code -1004
    standard	14:53:05.885829 +0200	Metabase	😷
    standard	14:53:08.461198 +0200	Metabase	TIC TCP Conn Start [12:0x600000381040]
    standard	14:53:08.463843 +0200	Metabase	TIC TCP Conn Event [12:0x600000381040]: 3 Err(61)
    fehler	14:53:08.463865 +0200	Metabase	TIC TCP Conn Failed [12:0x600000381040]: 1:61 Err(61)
    standard	14:53:08.463877 +0200	Metabase	TIC TCP Conn Cancel [12:0x600000381040]
    standard	14:53:08.463907 +0200	Metabase	TIC TCP Conn Destroyed [12:0x600000381040]
    fehler	14:53:08.464096 +0200	Metabase	HTTP load failed (error code: -1004 [1:61])
    fehler	14:53:08.464157 +0200	Metabase	NSURLConnection finished with error - code -1004
    standard	14:53:08.464276 +0200	Metabase	😷
    standard	14:53:10.093503 +0200	Metabase	TIC TCP Conn Start [13:0x618000383190]
    standard	14:53:10.096602 +0200	Metabase	TIC TCP Conn Event [13:0x618000383190]: 3 Err(61)
    fehler	14:53:10.096651 +0200	Metabase	TIC TCP Conn Failed [13:0x618000383190]: 1:61 Err(61)
    standard	14:53:10.096677 +0200	Metabase	TIC TCP Conn Cancel [13:0x618000383190]
    standard	14:53:10.096721 +0200	Metabase	TIC TCP Conn Destroyed [13:0x618000383190]
    fehler	14:53:10.096969 +0200	Metabase	HTTP load failed (error code: -1004 [1:61])
    fehler	14:53:10.097073 +0200	Metabase	NSURLConnection finished with error - code -1004
    standard	14:53:10.097263 +0200	Metabase	😷
    standard	14:53:11.743615 +0200	Metabase	TIC TCP Conn Start [14:0x618000383190]
    standard	14:53:11.746434 +0200	Metabase	TIC TCP Conn Event [14:0x618000383190]: 3 Err(61)
    fehler	14:53:11.746484 +0200	Metabase	TIC TCP Conn Failed [14:0x618000383190]: 1:61 Err(61)
    standard	14:53:11.746509 +0200	Metabase	TIC TCP Conn Cancel [14:0x618000383190]
    standard	14:53:11.746540 +0200	Metabase	TIC TCP Conn Destroyed [14:0x618000383190]
    fehler	14:53:11.746634 +0200	Metabase	HTTP load failed (error code: -1004 [1:61])
    fehler	14:53:11.746689 +0200	Metabase	NSURLConnection finished with error - code -1004
    standard	14:53:11.746855 +0200	Metabase	😷

**Comment by camsaul** [comment] 2017-09-28 17:50
Hi @michaelfeihstel, try closing the app and opening that again. I've seen this error myself once or twice but it started working by just restarting the app

**Comment by camsaul** [comment] 2017-10-20 01:03
Duplicate of #5126. This was fixed in our latest release, 0.26.1. @michaelfeihstel try updating to the latest version of Metabase

**Closed by camsaul** 2017-10-20 01:03 UTC
Labels: Client/Mac App, Need More Info
