### ISSUE TITLE
Cannot select granularity of aggregated fields in nested question

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13764] opened 2020-11-12 15:10 UTC
**Describe the bug**
No granularity options are shown, when using an aggregated field in the same question, but if the question is saved, then the options will then be available.

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Summarize "Average of Total" by UserID
3. Summarize Count by "Average of Total" - no granularity/binning/bucket is available
![image](https://user-images.githubusercontent.com/1447303/98955627-68e48800-24ff-11eb-92da-383043ed2bf6.png)

**Workaround:**
4. Remove the Summarize section in step 3 and save the question as "Q1"
5. Simple question > Saved Questions > "Q1"
6. Summarize Count by "Average of Total" - now the granularity option is available:
![image](https://user-images.githubusercontent.com/1447303/98956346-34250080-2500-11eb-93cc-787803c76ce1.png)

**Information about your Metabase Installation:**
Metabase 0.34.3 thru 0.37.0.2

**Additional context**
Related to #11439

**Comment by ariya** [comment] 2022-03-09 22:01
This looks like an incomplete implementation in the field lookup for nested query ("virtual" field on the source query), i.e. at https://github.com/metabase/metabase/blob/v0.42.2/frontend/src/metabase-lib/lib/Dimension.ts#L646

To resolve this, we potentially need to teach `FieldDimension` to synthesize its dimensions options, in case none is provided. This is similar to PR #20645.

**Comment by nemanjaglumac** [comment] 2023-09-19 10:11
@deniskaber 
<img width="890" alt="image" src="https://github.com/metabase/metabase/assets/31325167/6c392f4d-340e-4cc7-bf63-e2878c31c395">

**Comment by metamben** [comment] 2023-09-27 20:14
The current version (https://github.com/metabase/metabase/commit/3a0346c39cda77ad4c4a4e59ececdb31d8361306) doesn't allow binning even if we start with a saved question:

![Image](https://github.com/metabase/metabase/assets/103100869/22a21aee-b702-411e-a1c4-0cfe9646f984)

Binning needs fingerprinting information (`min` and `max`), so the question is when and how to produce that.

**Comment by luizarakaki** [comment] 2023-09-27 20:45
I think this can be called a limitation (something between a bug and a feature request).

Do we need `min` and `max` even if the user specifies the the number of bins?
If they specify 10, can we build the distribution without the precomputed values?

**Comment by luizarakaki** [comment] 2023-09-28 16:23
Right... In principle I think we should not rely on fingerprinting data for this (as it can get outdated or not calculate at all like in this case) but it would be a full project to rework that.

For now I'd call this a limitation/feature request and let it go

**Comment by nemanjaglumac** [comment] 2023-11-08 08:37
I can reproduce the issue on latest `master` d35c779976ae6bd79369e9cc6bec8540908f37d2 using the original steps.
There is an E2E test for this and it's still reliably failing, which means it can still be reliably used.

I was following @metamben 's repro steps and I couldn't reproduce that. In other words, it seems that this works at least when you start from a saved question (like the original issue suggested)


![Image](https://github.com/metabase/metabase/assets/31325167/f067514f-22fb-4d34-b885-e63080e8543f)

**Comment by nemanjaglumac** [comment] 2023-11-08 08:42
Please note one more thing that differs from the original issue.
There is now an additional option to choose columns from a "User" table. Not sure if this is correct/intended behavior or a bug?


![Image](https://github.com/metabase/metabase/assets/31325167/28d14b0d-efa6-42e3-a258-b7cb4bec114a)

Btw, if you expand the "User" to see its columns and then collapse it again "User ID" and "Average of Total" are not going to be visible in UI anymore. This particular part is 100% a FE bug.


![Image](https://github.com/metabase/metabase/assets/31325167/248e2ddf-158a-42bd-99ba-1342573cda25)


![Image](https://github.com/metabase/metabase/assets/31325167/d20c3d44-2312-4862-bcdb-28f799cef733)

**Comment by camsaul** [comment] 2023-11-10 00:10
> In principle I think we should not rely on fingerprinting data for this (as it can get outdated or not calculate at all like in this case) but it would be a full project to rework that.

Well, if we don't rely on the fingerprint, we need to get the `min` and `max` values from somewhere else... currently only the fingerprint has that information.

Either way, we don't have that `min` and `max` info until we run the query. There is no way we can bin a column without having min and max information to determine bin sizes; and that information only exists for columns that come from and existing table or saved question. There really is no way this can work, so I'm going to close this as a limitiation.

**Closed by camsaul** 2023-11-10 00:10 UTC
Labels: Type:Bug, .Limitation, Querying/Nested Queries, .Backend, Querying/GUI, .Reproduced, .Team/QueryProcessor, .Team/42 (DEPRECATED), .Wanted: MLv2, .FixMBQLScope42
