### ISSUE TITLE
Why special characters are not shown correctly in Metabase?

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#8690] opened 2018-10-15 12:19 UTC
### Bugs

- Your browser and the version: Chrome 69
- Your operating system: OS X 10
- Your databases: MySQL
- Metabase version: 0.30.3
- Metabase hosting environment: Linux Debian
- Metabase internal database: MySQL

- *Repeatable steps to reproduce the issue*

```
use test;

CREATE TABLE `special_chars` (
  `name` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

insert into special_chars (name) values ('🌟Test characters 🌟');
```

Now if you select the records data will be as below:

```
MariaDB [test]> select * from special_chars;
+---------------------------+
|                 name      |
+---------------------------+
| 🌟Test characters 🌟     |
+---------------------------+
1 rows in set (0.00 sec)
```

So data is stored as expected.

The issue is that `Metabase` displays special characters in question mark:

```
? Test characters ?
```

Why this happens? Is this a bug or is there a setting that we could set for display?

**Comment by jornh** [comment] 2018-10-15 16:42
I suspect this could just be a MySQL database configuration issue. 

See this search for closed issues with the word `utf8mb4`: 
https://github.com/metabase/metabase/issues?q=is%3Aissue+utf8mb4+is%3Aclosed

In particular https://github.com/metabase/metabase/issues/7438#issuecomment-386206859 has hints on further settings.

**Comment by alirezastack** [comment] 2018-10-21 06:41
Should I give more information for this? Is this a bug?

**Comment by jornh** [comment] 2018-10-21 22:07
Honestly nut sure yet if this is a Metabase bug or related to environment/configuration. I think it’s a matter of narrowing further down where the problem is. So it related to database/driver, Metabase backend/frontend, browser, OS settings like locale, available fonts etc.

To rule out database as a factor and see if it’s related to frontend/browser etc. I just tried the below native SQL query (on Metabase 0.30.4, Docker on Azure, with iOS 12 on my iPad):

![cfe79530-75b5-4e61-a85f-1095aee5a86e](https://user-images.githubusercontent.com/766423/47273015-eee6ac80-d58d-11e8-946c-f8b7721d612d.jpeg)

As you can see it renders both 🌟 and ⚠️. What’s to output if you try the same query?

**Comment by alirezastack** [comment] 2018-10-22 10:43
@jornh interesting enough, it gives the below error:

![screen shot 2018-10-22 at 2 13 11 pm](https://user-images.githubusercontent.com/6417083/47288822-acac8200-d604-11e8-89ca-5d088aceeb30.png)

**Comment by jornh** [comment] 2018-10-22 17:57
Ah... Okay, guess this is just an indication that the version of MySQL (or MariaDB? - as your error message indicates) you’re running doesn’t support the standalone [values trick](https://modern-sql.com/feature/values) ... though it seems it’s supported/getting support lately: 
https://modern-sql.com/blog/2018-08/whats-new-in-mariadb-10.3#3.values

Anyway - instead of upgrading your primary DB a quick workaround might be to either spin up a test Metabase instance running with the defaults so it creates a H2 database with the sample dataset. That’s the one I used above, and it doesn’t complain about the `values` syntax. Point of this exercise after all is just to make sure it’s not related to frontend environment in your setup.

**Comment by camsaul** [comment] 2020-01-21 22:54
Duplicate of #5192

**Closed by camsaul** 2020-01-21 22:54 UTC
Labels: Database/MySQL, Priority:P2, Type:Bug, Visualization/
