### ISSUE TITLE
Table/field descriptions are not sync'ed when updated in database

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#38694] opened 2024-02-12 23:17 UTC
### Describe the bug

When using [this feature](https://github.com/metabase/metabase/issues/3089) to sync table/field descriptions to Metabase from the database, it works on initial set or when descriptions are not set yet. Once descriptions are set, any description changes in the database table/field will no longer reflect in Metabase. 

### To Reproduce

1. Create new table/field with descriptions
2. Let Metabase scan it and see descriptions for table/fields
3. Update description for table or fields in database
4. Force Metabase to re-scan schema and see that no descriptions are updated. 

### Expected behavior

If description is updated in the db table/field, they should reflect in Metabase

### Logs

n/a

### Information about your Metabase installation

```JSON
master on Postgres
```

### Severity

Outdated metadata / can't use db as source of truth for field descriptions

**Comment by calherries** [comment] 2024-03-12 09:12
Dupe of [A table with an existing SQL description does not get updated when it is sync'ed](https://github.com/metabase/metabase/issues/12493) and [Sync: distinguish between metadata coming from the db & user set](https://github.com/metabase/metabase/issues/12574).

**Closed by calherries** 2024-03-12 09:12 UTC
Labels: Type:Bug, .Needs Triage, .Team/BackendComponents
