### ISSUE TITLE
Funnel graph has issues with Full Screen

### ISSUE THREAD

**Issue by wrongusernameyetagain** [metabase/metabase#12854] opened 2020-07-07 09:55 UTC
**Describe the bug**
Funnel graph has a visual bug, cutting the results of each "step" when on full screen.

**Logs**
N/A

**To Reproduce**
1. Create a funnel chart with multiple steps.
2. Expand its "card" to cover at least 7 width x 6 height so that descriptions of 'stages' and results are showing
3. Change dashboard to Full-Screen.

**Expected behavior**
Absolute and percentual results should be shown without being truncated when on full-screen.
**Screenshots**
![image](https://user-images.githubusercontent.com/56592983/86763510-ac0d8680-c047-11ea-8320-9793b667523f.png)

**Severity**
Not very severe. Slightly annoying as users have to hover over the funnel chart to see values.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.171-105.231.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2020-07-07 10:03
Very likely a duplicate of #12042 (related to #12175)

**Comment by geovanisouza92** [comment] 2020-09-14 18:46
I've done some investigation with an embedded dashboard, and it seems that [this CSS rule](https://github.com/metabase/metabase/blob/23e577c9053d593bf8785842edab42ad2f05086f/frontend/src/metabase/visualizations/components/FunnelNormal.css#L3) is the guilty.

By removing it, the chart doesn't get cropped anymore:

![Captura de tela de 2020-09-14 15-15-30](https://user-images.githubusercontent.com/786105/93125258-3c4bf580-f6a1-11ea-9c28-fc01cfe246dd.png)

**Comment by flamber** [comment] 2020-09-14 18:48
@geovanisouza92 You're more than welcome to submit a PR.

**Comment by nick-holaemi** [comment] 2021-03-17 19:50
@flamber any news regarding this issue?

**Comment by flamber** [comment] 2021-03-17 19:54
@nick-holaemi There's 2000 other issues open, so not currently. Click :+1: on the first post to upvote the issue. And this is likely a duplicate of #12042

**Closed** 2021-06-18 12:28 UTC
Labels: .Frontend, Priority:P3, Reporting/Dashboards, Visualization/
