### ISSUE TITLE
Scheduled (cached) Reports

### ISSUE THREAD

**Issue by kotso** [metabase/metabase#2575] opened 2016-05-10 12:52 UTC
Is there any way to make scheduled question?

I have very big database (around 20GB with lots of user and transaction data) and generating some queries that take more then 10-15 min per execution but I need them on daily bases (for example analyze past 7,14,30 days)

If Metabase does not support it it would be excellent feature request I guess.

**Comment by agilliland** [comment] 2016-05-10 15:26
Check out Pulses http://www.metabase.com/docs/v0.17.0/users-guide/07-pulses.html

**Comment by tlrobinson** [comment] 2016-05-10 15:33
Duplicate of #1666?

**Comment by salsakran** [comment] 2016-05-12 22:29
@kotso when you say scheduled reports do you mean sending a report out (aka Pulses) every night? Or precomputing expensive queries?

If the latter, have you looked into materialized views?

**Comment by kotso** [comment] 2016-05-13 06:20
@salsakran I mean precomputing expensive queries.

**Comment by camsaul** [comment] 2016-07-07 03:47
Closing as duplicate of #1666

**Comment by salsakran** [comment] 2016-07-07 03:49
this isn't quite the same as #1666 . 

What @kotso is describing is a pre-computation, not a caching. Not sure it's in scope, but it's different at least =)

**Comment by camsaul** [comment] 2016-07-07 03:51
if you compute it once and then *cache* the results for later...

**Comment by flamber** [comment] 2020-05-15 10:29
Related to #4967

**Comment by flamber** [comment] 2021-11-06 15:50
Closing in favor of #4967, which has a lot more upvotes.
There's more advanced caching options in 0.41: https://www.metabase.com/docs/latest/enterprise-guide/cache.html

**Closed by flamber** 2021-11-06 15:50 UTC
Labels: Type:Question, .Proposal
