### ISSUE TITLE
DateFilter - Date Range doesn't allow to select date ranges properly

### ISSUE THREAD

**Issue by jescorotero** [metabase/metabase#7036] opened 2018-02-28 11:20 UTC
- Your browser and the version: Chrome Versión 64.0.3282.186 (Build oficial) (64 bits)
- Your operating system: Windows 10
- Your databases: Mysql
- Metabase version: v0.28.1

When trying to select a date range for for example 2017-10-01 to 2017-12-25 , the variable DateFilter - Date Range doesn't allow it.

https://share.vidyard.com/watch/KtGyGUWWN9sRdWBAaQ1gA1

- *Repeatable steps to reproduce the issue*

1. Define a new DateFilter variable and use Date Range as widget
![image](https://user-images.githubusercontent.com/1407874/36784846-3085055e-1c81-11e8-8749-26952d38f93b.png)

1. Go to any month of previous year, like 2017-October and set any date as Start Date
![image](https://user-images.githubusercontent.com/1407874/36784955-84e5345c-1c81-11e8-8643-08b81952f3d7.png)

1. Then try to set any date of the next month as End Date. 

The result is the range is reset and you have just started from the begining selecting start date instead of EndDate.

-------

**Comment by salsakran** [comment] 2018-03-02 00:14
pretty sure this is a dupe of #6952

**Closed** 2018-03-31 00:30 UTC
Labels: Bug, Priority/P1, Query Builder, Query Builder/Native
