### ISSUE TITLE
Mongo DB queries - execute $match before $project

### ISSUE THREAD

**Issue by stan-focal-systems** [metabase/metabase#8678] opened 2018-10-11 22:46 UTC
# $match in MongoDB qggregation pipeline

- databases: MongoDB
- Metabase version: v0.30.4
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

MongoDb queries would execute much faster if the first aggregation step was $match. Currently, the first step is $project which goes through all the entries in a collections.

**Comment by notz** [comment] 2018-10-12 08:35
According to MongoDB Documentation your statement is not valid. See here:

https://docs.mongodb.com/manual/core/aggregation-pipeline-optimization/#pipeline-sequence-optimization

**Comment by stan-focal-systems** [comment] 2018-10-12 15:56
Thanks for fast reply @notz.

Well, let's look into MongoDB documentation:

1. For an aggregation pipeline that contains a projection stage ($project or $addFields) followed by a $match stage, MongoDB moves any filters in the $match stage that __do does not require values computed in the projection stage__ to a new $match stage before the projection.
https://docs.mongodb.com/manual/core/aggregation-pipeline-optimization/#pipeline-sequence-optimization.  

2. If you place a $match at the very beginning of a pipeline, the query can take advantage of indexes like any other db.collection.find() or db.collection.findOne(). https://docs.mongodb.com/manual/reference/operator/aggregation/match/#behavior

Metabase recomputes all dates values in the first $project, so matching by date is done after $project. Aa a result date related questions are very slow. Switching to native queries and placing $match on top reduces execution time significantly (provided the right indexes are defined).

We use huge collections, with millions of entries. Having $project as the first pipeline stage makes our Metabase questions extremely long.

**Comment by camsaul** [comment] 2018-11-21 00:52
Duplicate of #8678

**Closed by camsaul** 2018-11-21 00:52 UTC
Labels: Database/Mongo, Performance, Proposal
