### ISSUE TITLE
Filter field selection and drag and drop.

### ISSUE THREAD

**Issue by mfazekas** [metabase/metabase#7068] opened 2018-03-04 08:24 UTC
I've created the following questions from Sample Dataset
1.) Number: `People, Count`
2.) Native query: `SELECT name, email FROM people;` called `People SQL`
3.) Number: `People SQLs, Count`. (data: `People SQL`)

4.) Created a new dashboard, add `People, Count` and `People SQLs, Count` 
5.) Add a new time filter with `All Options`, Select `Created at` from `People, Count` then press `Done` for `Select the field that should be filter for each card`
6.) Press `Save` then press `Edit dashboard`, then the `Edit` buttton on the `Date filter`
8.) click `People SQLs, Count` that starts drag and drop, but i was not able to drop it, and i was able to drag multiple cards on top of each other

![image](https://user-images.githubusercontent.com/52435/36943418-5c3a6224-1f89-11e8-898e-e064aba73045.png)

Environment:

Browser: Chrome 64.0.3282.186, but was happening on firefox too
OS: OX 10.13.3 (17D47)
DB: H3
Metabase version: v0.28.1 and master(56a2dba99f43a9bccc894cac49510768ed7d76dd)
Database: postgresql and H2
Metabase hosting environment: Heroku and dev env
Metabase internal database: PostgreSQL and H2

**Comment by matthieu-foucault** [comment] 2019-06-18 16:57
This seems to be a duplicate of #5365 . This bug is still around

**Closed** 2019-08-29 00:12 UTC
Labels: Priority:P3, Reporting/Dashboards, Type:Bug
