### ISSUE TITLE
Exports ignore column ordering regression in v0.41.6

### ISSUE THREAD

**Issue by francesmcmullin** [metabase/metabase#19796] opened 2022-01-20 12:12 UTC
**Describe the bug**
Since deploying version 0.41.6, data exports (emailed from pulse or from UI download button) do not respect the configured column order.

**Logs**
Not sure of logs relevant to this issue.

**To Reproduce**
1. Setup a question with at least two columns of the same type (e.g., one group and one aggregation column won't work)
2. Re-order the columns (the default seems to be alphabetic, so use a different order than that)
3. Download results

**Expected behavior**
The columns in the export CSV should be in the same order as configured in the question

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your databases: Postgres
- Metabase version: v0.41.6 (tested and this problem is not present in v0.41.5)
- Metabase hosting environment: AWS Elastic Beanstalk
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely? Low. For now I've just downgraded to 0.41.5

**Additional context**

**Comment by flamber** [comment] 2022-01-20 19:42
@noahmoss Yep:
![image](https://user-images.githubusercontent.com/1447303/150410384-ee7c3d97-a4cc-46b7-9d5c-bf0b7d3d4a66.png)
```
Category,Created At,Count,Sum of Price,Average of Rating
Doohickey,2016-01-01,13,632.1204747596681,3.4538461538461536
```
<details><summary>/api/card/:id</summary>

```
{
  "description": null,
  "archived": false,
  "collection_position": null,
  "table_id": 10,
  "result_metadata": [
    {
      "description": "The type of product, valid values include: Doohicky, Gadget, Gizmo and Widget",
      "semantic_type": "type/Category",
      "coercion_strategy": null,
      "name": "CATEGORY",
      "field_ref": [
        "field",
        107,
        null
      ],
      "effective_type": "type/Text",
      "id": 107,
      "display_name": "Category",
      "fingerprint": {
        "global": {
          "distinct-count": 4,
          "nil%": 0
        },
        "type": {
          "type/Text": {
            "percent-json": 0,
            "percent-url": 0,
            "percent-email": 0,
            "percent-state": 0,
            "average-length": 6.375
          }
        }
      },
      "base_type": "type/Text"
    },
    {
      "description": "The date the product was added to our catalog.",
      "semantic_type": "type/CreationTimestamp",
      "coercion_strategy": null,
      "unit": "year",
      "name": "CREATED_AT",
      "field_ref": [
        "field",
        108,
        {
          "temporal-unit": "year"
        }
      ],
      "effective_type": "type/DateTime",
      "id": 108,
      "display_name": "Created At",
      "fingerprint": {
        "global": {
          "distinct-count": 200,
          "nil%": 0
        },
        "type": {
          "type/DateTime": {
            "earliest": "2016-04-27T01:29:55.147Z",
            "latest": "2019-04-15T19:34:19.931Z"
          }
        }
      },
      "base_type": "type/DateTime"
    },
    {
      "name": "count",
      "display_name": "Count",
      "base_type": "type/BigInteger",
      "effective_type": "type/BigInteger",
      "semantic_type": "type/Quantity",
      "field_ref": [
        "aggregation",
        0
      ],
      "fingerprint": {
        "global": {
          "distinct-count": 11,
          "nil%": 0
        },
        "type": {
          "type/Number": {
            "min": 3,
            "q1": 7.5,
            "q3": 17.585786437626904,
            "max": 21,
            "sd": 5.94418483337567,
            "avg": 12.5
          }
        }
      }
    },
    {
      "name": "sum",
      "display_name": "Sum of Price",
      "base_type": "type/Float",
      "effective_type": "type/Float",
      "semantic_type": null,
      "field_ref": [
        "aggregation",
        1
      ],
      "fingerprint": {
        "global": {
          "distinct-count": 16,
          "nil%": 0
        },
        "type": {
          "type/Number": {
            "min": 195.03825709546499,
            "q1": 466.0797557826742,
            "q3": 992.6586308164215,
            "max": 1080.2154999244008,
            "sd": 316.67782792622427,
            "avg": 696.8299958490093
          }
        }
      }
    },
    {
      "name": "avg",
      "display_name": "Average of Rating",
      "base_type": "type/Float",
      "effective_type": "type/Float",
      "semantic_type": "type/Score",
      "field_ref": [
        "aggregation",
        2
      ],
      "fingerprint": {
        "global": {
          "distinct-count": 16,
          "nil%": 0
        },
        "type": {
          "type/Number": {
            "min": 2.675,
            "q1": 3.1281512605042017,
            "q3": 3.829934210526316,
            "max": 4.052941176470588,
            "sd": 0.43526377213681783,
            "avg": 3.430696045709107
          }
        }
      }
    }
  ],
  "creator": {
    "email": "test@test.test",
    "first_name": "Meta",
    "last_login": "2022-01-19T12:06:11.078",
    "is_qbnewb": false,
    "is_superuser": true,
    "id": 1,
    "last_name": "Base",
    "date_joined": "2019-04-07T23:36:04.697",
    "common_name": "Meta Base"
  },
  "can_write": true,
  "database_id": 4,
  "enable_embedding": false,
  "collection_id": null,
  "query_type": "query",
  "name": "Export column order",
  "last_query_start": "2022-01-20T20:40:23.571962+01:00",
  "dashboard_count": 0,
  "average_query_time": 73,
  "creator_id": 1,
  "moderation_reviews": [],
  "updated_at": "2022-01-20T20:39:49.271",
  "made_public_by_id": null,
  "embedding_params": null,
  "cache_ttl": null,
  "dataset_query": {
    "database": 4,
    "query": {
      "source-table": 10,
      "aggregation": [
        [
          "count"
        ],
        [
          "sum",
          [
            "field",
            104,
            null
          ]
        ],
        [
          "avg",
          [
            "field",
            103,
            null
          ]
        ]
      ],
      "breakout": [
        [
          "field",
          107,
          null
        ],
        [
          "field",
          108,
          {
            "temporal-unit": "year"
          }
        ]
      ]
    },
    "type": "query"
  },
  "id": 1059,
  "display": "table",
  "last-edit-info": {
    "id": 1,
    "email": "test@test.test",
    "first_name": "Meta",
    "last_name": "Base",
    "timestamp": "2022-01-20T20:26:08.373"
  },
  "visualization_settings": {
    "table.pivot": false,
    "table.columns": [
      {
        "name": "sum",
        "field_ref": [
          "aggregation",
          1
        ],
        "enabled": true
      },
      {
        "name": "CATEGORY",
        "fieldRef": [
          "field",
          107,
          null
        ],
        "enabled": true
      },
      {
        "name": "count",
        "fieldRef": [
          "aggregation",
          0
        ],
        "enabled": true
      },
      {
        "name": "CREATED_AT",
        "fieldRef": [
          "field",
          108,
          {
            "temporal-unit": "year"
          }
        ],
        "enabled": true
      },
      {
        "name": "avg",
        "field_ref": [
          "aggregation",
          2
        ],
        "enabled": true
      }
    ],
    "table.pivot_column": "CATEGORY",
    "table.cell_column": "count"
  },
  "collection": null,
  "created_at": "2022-01-20T20:25:44.237",
  "public_uuid": null
}
```

</details>

**Comment by noahmoss** [comment] 2022-01-20 19:49
Oh, I see, it happens with aggregations. In this case it seems that the `visualization_settings` stored in the DB for the card has the columns in a different order than what the frontend displays. Digging into it...

**Comment by noahmoss** [comment] 2022-01-24 14:59
@flamber Could you describe how to replicate this using the query in your screenshot? I'm trying to recreate it, but it's not replicating for me (might be doing something slightly different).

I _can_ replicate the issue with a different question but I think the root cause of the issue is slightly different on the backend. So I want to make sure my fix is generic.

**Comment by flamber** [comment] 2022-01-24 16:06
@noahmoss 
1. Custom question > Sample Dataset > Products
2. Summarize Count grouped by Category and CreatedAt:Year
3. Visualize, change to Table, unpivoted - now move the Count to the middle column like so:
![image](https://user-images.githubusercontent.com/1447303/150819045-ca1655f2-7672-4722-86c2-e75a24cc4a82.png)
4. Save question - refresh browser
5. Notebook > under Summarize add Sum of Price and Average of Rating - visualize - move Sum to the first column like so:
![image](https://user-images.githubusercontent.com/1447303/150819164-aa5819d5-389a-44cb-b5e6-13307277c84a.png)
6. Save question - refresh browser
7. Export
```
Category,Created At,Count,Sum of Price,Average of Rating
Doohickey,2016-01-01,13,632.1204747596681,3.4538461538461536
Doohickey,2017-01-01,17,854.1890645795561,4.052941176470588
```
8. Downgrade to 0.41.5, refresh the question generated on 0.41.6, then it exports as expected

**Comment by rlotun** [comment] 2022-01-27 05:15
fixed by https://github.com/metabase/metabase/pull/19882

**Closed by rlotun** 2022-01-27 05:15 UTC
Labels: Type:Bug, Priority:P2, .Correctness, Reporting/Export, .Regression
