### ISSUE TITLE
Time and space bucket division is not supported. You cannot divide the: type / date field into buckets through: hour.

### ISSUE THREAD

**Issue by Mrshanyan** [metabase/metabase#19469] opened 2021-12-23 02:09 UTC
Time and space bucket division is not supported. You cannot divide the: type / date field into buckets through: hour.

![image](https://user-images.githubusercontent.com/20273704/147176836-c861430a-e09b-4bb6-8312-7b026e4120af.png)

**Comment by flamber** [comment] 2021-12-23 09:27
Duplicate of #17598

**Closed by flamber** 2021-12-23 09:27 UTC
Labels: Type:Question, .Needs Triage
