### ISSUE TITLE
Column checklist in Custom Question does not allow "Deselect all"

### ISSUE THREAD

**Issue by mlm603** [metabase/metabase#12793] opened 2020-06-26 17:29 UTC
**Describe the bug**
By default when you start a custom question, under the `Columns` list, `Select All` is greyed out. If you only want to select one or two columns, you have to uncheck all of the other columns.

<img width="227" alt="Screen Shot 2020-06-26 at 1 27 42 PM" src="https://user-images.githubusercontent.com/13624950/85884538-d5f5bc00-b7b0-11ea-94e6-8deb97ab4db0.png">

**Expected behavior**
You should be able to uncheck `Select All` in order to deselect all columns and then pick only the ones you want.

**Information about your Metabase Installation:**
Metabase v1.35.4

**Severity**
Low severity. It's frustrating, but doesn't impact functionality. We're usually doing aggregations, anyway, instead of just selecting columns.

**Comment by flamber** [comment] 2020-06-26 17:37
Duplicate of #10460

**Closed by flamber** 2020-06-26 17:37 UTC
Labels: .Needs Triage, Type:Bug
