### ISSUE TITLE
Questions should not be clickable when editing a dashboard

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#9445] opened 2019-02-19 09:58 UTC
When in dashboard edit mode if you do a long click (but only if the mouse is down for a while) on a question, you jump to that question which is very annoying, doubly so because you also loose any (unsaved) changes you've made to the dashboard until this point.

**Comment by flamber** [comment] 2019-02-19 19:08
That just happened to me (twice), when I was trying to reproduce 6765 :disappointed: 
Related to #6888

**Comment by tlrobinson** [comment] 2019-06-05 19:27
@sbelak I'm unable to reproduce the long click issue. Which type of chart is it and where are you clicking?

I am able to reproduce #6888. We should disable brushing when editing, and probably prompt if trying to navigate away without saving.

**Comment by paulrosenzweig** [comment] 2019-09-20 21:51
Resolved by #10931

**Closed by paulrosenzweig** 2019-09-20 21:51 UTC
Labels: Priority:P3, Reporting/Dashboards, Type:UX
