### ISSUE TITLE
Inconsistent card behaviour when there's no data

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#6765] opened 2018-01-24 18:53 UTC
Some have a title, some don't (this one is especially troublesome as you can't even click on it), if it's a multi-series it retains the legend:
<img width="1242" alt="screenshot 2018-01-23 15 42 35" src="https://user-images.githubusercontent.com/178038/35351045-978549ba-00f4-11e8-8ae2-8041fa3c5505.png">

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2019-02-18 17:58
Hi @sbelak 
I cannot reproduce this issue on 0.31.2 - all my cards (tables, bar, line, area, line+bar) shows the card title no matter if it's a multi-series or single-series.

**Comment by sbelak** [comment] 2019-02-19 09:52
It's better, but still not right:
<img width="1105" alt="screenshot 2019-02-19 10 50 50" src="https://user-images.githubusercontent.com/178038/53005819-49a4ed80-3434-11e9-9fdb-1b888de7f52b.png">
Note the differences in titles.

**Comment by flamber** [comment] 2019-02-19 15:13
@sbelak Okay, now I see. This seems to be related to bar charts. Did some more testing:
![screenshot_00000](https://user-images.githubusercontent.com/1447303/53025341-64706580-3426-11e9-9f0f-d681b820b839.png)
![screenshot_00001-2](https://user-images.githubusercontent.com/1447303/53025348-6803ec80-3426-11e9-917c-812f4c8539a1.png)

**Comment by flamber** [comment] 2021-11-10 13:17
This was fixed in 0.41 with the legend revamp.

**Closed by flamber** 2021-11-10 13:17 UTC
Labels: Type:Bug, Priority:P3, Reporting/Dashboards
