### ISSUE TITLE
[SLOW Query] API endpoint for query are too slow vs the query

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#7943] opened 2018-06-26 16:09 UTC
### Bug

- Your browser and the version: Chrome 67.0.3396.62 (64-bits)
- Your operating system: Linux/Ubuntu
- Your databases: Postgres
- Metabase version: v0.29.3
- Metabase hosting environment: Linux/Debian
- Metabase internal database: Postgres

I run the same query over `/api/card/320/query` and at my `SQL client` (I use [SQLWorkbench](https://www.sql-workbench.eu/) that uses the same JDBC connector). Did it take 5 seconds at the endpoint and 200 milliseconds and my client, why this the parse slow at this point?

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2020-05-23 23:37
Hi @dannyeuu 

Are you seeing the same behavior on the latest 0.35.3 release?

Is Metabase located on the same machine as SQL Workbench, so they would have similar connection and latency costs?

If you check the log, it should tell you the query time (23ms for this example):
`POST /api/card/182/query 202 [ASYNC: completed] 23.0 ms (10 DB calls) App DB connections: 2/15 Jetty threads: 3/50 (4 idle, 0 queued) (149 total active threads) Queries in flight: 0 (0 queued)`

**Comment by flamber** [comment] 2021-11-11 13:28
Closing, since a lot has changed since this issue was created and without more details, then it's impossible to reproduce or know how to address this.

**Closed by flamber** 2021-11-11 13:28 UTC
Labels: Type:Performance, Querying/Processor
