### ISSUE TITLE
Static viz incorrectly handles multiple charts combined on the dashboard

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#24810] opened 2022-08-16 09:58 UTC
**Describe the bug**
The multiple line chart on the dashboard is totally different than what is received in the e-mail. This example uses 2 series example

**Logs**
No logs for this

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to create a new native query
2. Chart 1 -  Copy and paste the following query to create a dataset and save it as a line chart

```
Select '1 Customer Intent'     AS goal, 'financial_model_target' AS development_model, null AS avg_days_from_project_creation
UNION ALL
Select '2 Project Validation'   AS goal, 'financial_model_target' AS development_model, 90 AS avg_days_from_project_creation
UNION ALL
Select '3 Project Contracts'   AS goal, 'financial_model_target' AS development_model, 240 AS avg_days_from_project_creation
UNION ALL
Select '4 Regulatory Approval' AS goal, 'financial_model_target' AS development_model, 270 AS avg_days_from_project_creation
UNION ALL
Select '5 Notice to Proceed'   AS goal, 'financial_model_target' AS development_model, 300 AS avg_days_from_project_creation
```
![image](https://user-images.githubusercontent.com/110378427/185576940-094c4089-c6fd-483e-8fbb-475080de6ce0.png)

3. Chart 2 - Copy and paste the following query to create a dataset and save it as a line chart

```
Select '1 Customer Intent'     AS goal, 'dtc' AS development_model, 59.82 AS avg_days_from_project_creation
UNION ALL
Select '1 Customer Intent'     AS goal, 'dealer' AS development_model, 137.75 AS avg_days_from_project_creation
UNION ALL
Select '2 Project Validation'   AS goal, 'dtc' AS development_model, 196.08 AS avg_days_from_project_creation
UNION ALL
Select '2 Project Validation'   AS goal, 'dealer' AS development_model, 78.94 AS avg_days_from_project_creation
UNION ALL
Select '3 Project Contracts'   AS goal, 'dtc' AS development_model, 346.34 AS avg_days_from_project_creation
UNION ALL
Select '3 Project Contracts'   AS goal, 'dealer' AS development_model, 369.35 AS avg_days_from_project_creation
UNION ALL
Select '4 Regulatory Approval' AS goal, 'dtc' AS development_model, 254.69 AS avg_days_from_project_creation
UNION ALL
Select '4 Regulatory Approval' AS goal, 'dealer' AS development_model, 107.35 AS avg_days_from_project_creation
UNION ALL
Select '5 Notice to Proceed'   AS goal, 'dealer' AS development_model, 386.35 AS avg_days_from_project_creation
```

![image](https://user-images.githubusercontent.com/110378427/185577142-4b66e05b-35e5-41fd-a429-339999d4d21d.png)

5. Add the two charts into a dashboard .. Make sure to add them as a multi series:

![image](https://user-images.githubusercontent.com/110378427/185577300-3bf3708e-0b06-4c04-99b8-32f32202613f.png)

7. Send Dashboard to e-mail

**Expected behavior**
Matching email chart with Dashboard chart

**Screenshots**

![image](https://user-images.githubusercontent.com/110378427/185577887-4a7ffd27-60b3-4426-96c4-98f433af21d8.png)

**Information about your Metabase Installation:**

- Metabase version: 1.44.1

**Severity**
Blocking users which use e-mail to share information with clients. The result is not even comparable to what we have on the dashboard

**Comment by flamber** [comment] 2022-08-19 12:27
Very related to #21559

**Comment by WiNloSt** [comment] 2022-12-01 03:13
The problem was due to how each series doesn't contain the same set of x values. In this case the series are as shown
- [2 3 4 5]
- [1 2 3 4]
- [1 2 3 4 5]

This can be harder than it seems. Since we can’t only rely on the x label to be always sorted. In this case, it’s sorted, but if it’s not, it might be impossible to have a deterministic order. e.g. if we can’t rely on the x tick label (since it can be named anything) given we have 3 series in the following orders:
- [2 3 4]
- [1 3]
- [2 4]

We want the end result to be [1 2 3 4]
But we only know 1 comes before 3, and 2 comes before 3, but we don’t know for sure if 1 comes before 2 or not since we can only rely on their orders.

We can build the order graph like this:

```mermaid
graph LR;
1((1)) --> 3
2((2)) --> 3((3)) --> 4((4))
2  --> 4
```

But I'm not yet sure how to best traverse this graph to produce the sorted list.

**Comment by adam-james-v** [comment] 2022-12-16 23:06
I'm going to close this comment because on Metabase 0.45 (and 1.45) I am unable to reproduce the issue following the given steps. There were efforts to improve the static-viz area of the code for the 45 release, so I believe this was solved.

Here is the static-viz result from the dashboard: 

![image](https://user-images.githubusercontent.com/21064735/208202793-1325528a-839c-49fe-922f-8bf4e5465a1b.png)

Of course, if there are circumstances in which this problem still shows up, please feel free to open this issue again (perhaps with added context, or some indication that it's still a concern even in 45), or open a fresh issue.

**Closed by adam-james-v** 2022-12-16 23:06 UTC
Labels: Type:Bug, Priority:P2, .Correctness, Visualization/Charts, Reporting/Dashboards/Combined charts, Visualization/Static
