### ISSUE TITLE
Timestamps for activity log are not being converted to browser timezone

### ISSUE THREAD

**Issue by jeff303** [metabase/metabase#15635] opened 2021-04-15 18:33 UTC
**Describe the bug**
The items in the activity log are rendering their timestamps as if the browser is in UTC.

**Logs**
N/A

**To Reproduce**
1. Set up a new instance of Metabase x.39
2. Navigate to Activity (under gearbox menu)
3. Observe the timestamp of the "up and running" event

**Expected behavior**
This should say something like "1 minute ago" or "now", but instead it's showing a relative date string that suggests it's not being converted to the browser timezone (from UTC, which presumably it's stored in).

**Screenshots**

![Activity_timezone_bug](https://user-images.githubusercontent.com/3521562/114920411-06195480-9def-11eb-976d-bc625c5f358c.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 89
- Your operating system: OS X 11
- Your databases: None
- Metabase version: 1.39 RC
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Unclear, but probably minor

**Additional context**

**Comment by flamber** [comment] 2021-04-15 19:47
Related to #14654

**Comment by ranquild** [comment] 2022-05-02 11:15
This is a backend issue. The problem is that `timestamp` field in `/api/activity` returns timestamps in the instance timezone without any timezone information:

<img width="904" alt="Screenshot 2022-05-02 at 14 14 13" src="https://user-images.githubusercontent.com/8542534/166225417-d384d5d0-116c-4c66-a923-3a1a8379f9ad.png">

**Comment by flamber** [comment] 2022-05-02 11:18
Quite a lot of other places too: https://github.com/metabase/metabase/pull/21959#issuecomment-1107445095

**Comment by npfitz** [comment] 2023-12-21 17:50
This issue can be closed as the endpoint and pages have been removed from the app as of https://github.com/metabase/metabase/pull/29056

**Closed by npfitz** 2023-12-21 17:50 UTC
Labels: Type:Bug, Priority:P3, Misc/Timezones, .Backend, Organization/Activity Log
