### ISSUE TITLE
Unable to view `created_at` and `updated_at` field values

### ISSUE THREAD

**Issue by ramandamodar12** [metabase/metabase#10285] opened 2019-07-02 12:41 UTC
<img width="1632" alt="Screenshot 2019-07-02 at 6 10 01 PM" src="https://user-images.githubusercontent.com/52196920/60513561-30228500-9cf5-11e9-838a-abd7d5e610d0.png">

Metabase Version - 0.33

Unable to view the raw values of created_at and updated_at fields of any table in my MySQL database.

**Comment by flamber** [comment] 2019-07-02 15:01
Hi @ramandamodar12 
The screenshot is not Metabase 0.33 (not even released yet) - latest is 0.32.9 - so what are you using?
Have you defined formatting, otherwise try setting it again? Admin > Settings > Formatting
What is the default language of your browser?

**Comment by ramandamodar12** [comment] 2019-07-02 15:08
> Hi @ramandamodar12
> The screenshot is not Metabase 0.33 (not even released yet) - latest is 0.32.9 - so what are you using?
> Have you defined formatting, otherwise try setting it again? Admin > Settings > Formatting
> What is the default language of your browser?

<img width="644" alt="Screenshot 2019-07-02 at 8 36 03 PM" src="https://user-images.githubusercontent.com/52196920/60523868-23a82780-9d09-11e9-925a-f212c7e859de.png">

The settings page shows the version as 0.33.0-snapshot. 

<img width="419" alt="Screenshot 2019-07-02 at 8 37 46 PM" src="https://user-images.githubusercontent.com/52196920/60523961-4f2b1200-9d09-11e9-8c26-979db14a4202.png">

Sharing the screenshot of the global level format settings.

The default language is set to EN

**Comment by flamber** [comment] 2019-07-02 15:17
@ramandamodar12 
Okay, that doesn't show which branch+commit you're using. Are you reporting an issue with `master`?
Why are you not using one of the pre-built releases? https://metabase.com/start/

**Comment by ramandamodar12** [comment] 2019-07-02 15:32
@flamber I had followed the steps shown at https://metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html#deploying-new-versions-of-metabase to update metabase. This file was downloaded https://downloads.metabase.com/v0.32.9/metabase-aws-eb.zip and was updated in the AWS console. Not sure why the settings page shows 0.33.

**Comment by flamber** [comment] 2019-07-02 17:14
@ramandamodar12 
Okay, something must have gone wrong somewhere. Can you verify that the file `Dockerrun.aws.json` inside `metabase-aws-eb.zip` is using the image `metabase/metabase:v0.32.9`?
Also, click the gear-icon :gear: in top right corner and click "About Metabase", which should tell you version and commit version and built date.

**Comment by amis47** [comment] 2019-07-04 22:03
we just updated to 0.32.8 as well and it ran into the same problem

fwiw
![image](https://user-images.githubusercontent.com/31551334/60688870-d3e27100-9e6c-11e9-88eb-acb499820418.png)

**Comment by flamber** [comment] 2019-07-04 22:14
@amis47 
Which version did you upgrade from?
Are you using MySQL too? Which version?
Is this only a problem with Native (SQL) or does it also happens with Custom question?
Does it work if you change the field formatting in visualization settings :gear:?

**Comment by amis47** [comment] 2019-07-04 22:21
thanks for your quick response, we upgraded metabase from 0.31.2 to 0.32.8. All SQL statement seems to work fine, the only problem is we are unable to see datetime field such as `created_at` / `updated_at` field values.

**Comment by flamber** [comment] 2019-08-14 17:14
@amis47 
Does the `created_at`/`updated_at` use microseconds? Where column type is like `datetime(6)`
Which version of MySQL?
Reference: https://discourse.metabase.com/t/datetime-values-not-rendering-in-results-table/6869

**Comment by ramandamodar12** [comment] 2019-08-16 07:30
> @amis47
> Does the `created_at`/`updated_at` use microseconds? Where column type is like `datetime(6)`
> Which version of MySQL?
> Reference: https://discourse.metabase.com/t/datetime-values-not-rendering-in-results-table/6869

Yes @flamber The fields use microseconds. As a workaround, we are using DATE_FORMAT function.

**Comment by salsakran** [comment] 2019-10-07 00:40
Closing as this was fixed in 0.33 based on that discourse conversation.

If it reappears chime in here and we'll reopen

**Comment by dannymc129** [comment] 2019-10-07 21:32
Hate to do this @salsakran but  I just upgraded today from 0.31.2 to 0.33.3 and this issue popped up. It's a very interesting one, I noticed that a datetime that specifically have microseconds of 000 does return from the /datasets but all others don't. I guess 1/1000 ain't bad right?

![image](https://user-images.githubusercontent.com/1252938/66349944-04ccb900-e928-11e9-8eea-420f6a0e38ab.png)

![image](https://user-images.githubusercontent.com/1252938/66349980-1ada7980-e928-11e9-85d5-76af77183bcb.png)

I reverted all the way back to 0.33.0-rc1 and this still occurs.

**Comment by flamber** [comment] 2019-11-26 23:33
@dannymc129 
Are you still seeing this problem on 0.33.6? Is it specific to Custom or Native question?
I cannot reproduce this problem with MySQL 5.7.28 column type `datetime(6)` (0.32.9 thru 0.33.6)
![image](https://user-images.githubusercontent.com/1447303/69681131-b956a180-1072-11ea-8b05-ea103d807b92.png)

**Comment by flamber** [comment] 2020-03-18 11:55
Is anyone able to reproduce this problem on the latest release 0.34.3 ?

**Closed** 2020-04-28 15:56 UTC
Labels: .Unable to Reproduce, Database/MySQL, Priority:P2, Type:Bug
