### ISSUE TITLE
Multi-series charting not working on 33.4

### ISSUE THREAD

**Issue by Swift-Jr** [metabase/metabase#11219] opened 2019-10-25 16:24 UTC
**Describe the bug**
When I try to add a chart to an existing chart on the dashboard I am not able to add the new chart, even if it is the same data type, or an exact clone of the original chart.

https://www.metabase.com/docs/latest/users-guide/09-multi-series-charting.html

Dashboards with layered charts that did work before cannot be edited, otherwise they all fail.

**Logs**
There are around 1000+ JS errors appearing in the console

**To Reproduce**
1. Create a new report that uses an advanced summary (calculated value, distinct or otherwise), as a line chart showing count over number series
2. Save the report
3. Save the report again with a different name
4. Add both to a dashboard - works
5. Try and add one to the other using the layering/add chart - fails
6. The other chart (an exact copy) is not compatible/available
7. Altering the 2nd chart does not appear to allow it to be added in anyway

**Expected behavior**
Should be able to layer both the charts on a single graph as per https://www.metabase.com/docs/latest/users-guide/09-multi-series-charting.html

**Screenshots**
n/a
**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.4+11",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.4",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.4+11",
    "os.name": "Linux",
    "os.version": "4.15.0-1031-azure",
    "user.language": "en",
    "user.timezone": "Europe/London"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-10-07",
      "tag": "v0.33.4",
      "branch": "release-0.33.x",
      "hash": "9559406"
    },
    "settings": {
      "report-timezone": "GMT"
    }
  }
}

**Severity**
This is pretty irritating - not being able to compare datasets almost defeats the point of having metabase.

**Comment by flamber** [comment] 2019-10-25 18:53
Hi @Swift-Jr 
Can you provide the response-data from the `/api/card/XX/query` request of the question? Check the browser developer Network-tab, and click the refresh-icon (top-right) when viewing the question.

**Comment by mazameli** [comment] 2019-11-15 22:47
Haven't been able to reproduce this yet on 0.33.5.1, so any additional information you could provide would be helpful, @Swift-Jr. Tried it on a Postgres DB and it worked, so I'm scratching my head trying to think of other causes.

You said there are around 1,000 JS console log errors — if you can look at the bottom to see if any look relevant, or falling short of that just copy the whole thing and upload it as a ZIP here, that would help us.

**Comment by flamber** [comment] 2020-06-03 15:08
Closing, since not enough details to debug the issue.
Possibly related to #5344 and #4488

**Closed by flamber** 2020-06-03 15:08 UTC
Labels: Priority:P2, Reporting/Dashboards, Type:Bug

**Comment by bturndorf** [comment] 2020-08-26 19:33
I'm experiencing this same issue. Here's a video of what I'm seeing, including the console errors (getting a 404 on fetchData): https://share.getbento.com/ApukJWbG

The saved question I was looking for in the 'add chart' modal is called 'Avg. OO transactional revenue previous 90 days (not using Campaigns)', but it isn't shown there. The two questions I was trying to combine were started from the same question and just have a single filter changed.

Here's my diagnostic info:
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.186-110.268.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "US/Eastern"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```

**Comment by flamber** [comment] 2020-08-26 20:16
@bturndorf Please test with the latest release, 0.36.4 - if you're still experiencing problems there, then please open a new issue.

**Comment by bturndorf** [comment] 2020-08-26 21:03
Thank you! Connecting with our sysadmin to upgrade, sorry, I hadn't
realized we weren't running the latest.
