### ISSUE TITLE
Zero rounded to very small number in Bar chart

### ISSUE THREAD

**Issue by janmpeterka** [metabase/metabase#19203] opened 2021-12-06 11:14 UTC
Stumbled upon this visualisation bug:
![Screenshot from 2021-12-06 12-09-33](https://user-images.githubusercontent.com/6343648/144836182-de77abf8-e480-4910-9de5-d882ba1d59f1.png)

When showing original data, it is ok:
![Screenshot from 2021-12-06 12-10-27](https://user-images.githubusercontent.com/6343648/144836180-044b6376-15d7-43a8-98e8-31da136ffab6.png)

![Screenshot from 2021-12-06 12-10-31](https://user-images.githubusercontent.com/6343648/144836178-4baf112b-d4d4-46a5-9aaa-2ad59cddc58c.png)
Data type of `Provider level` is Category

---

Metabase version v0.41.3.1

**Comment by flamber** [comment] 2021-12-06 11:19
Duplicate of #14218
Remove the remapping on the field, or change X-scale to Ordinal.

**Closed by flamber** 2021-12-06 11:19 UTC
Labels: Type:Bug, .Needs Triage

**Comment by janmpeterka** [comment] 2021-12-06 11:36
Thanks, did miss that one issue. 
Ordinal X-scale solved it.
