### ISSUE TITLE
Dashboard, cannot add filters and save failed

### ISSUE THREAD

**Issue by maxschloegl** [metabase/metabase#10796] opened 2019-09-04 14:24 UTC
**Describe the bug**
When I want to match a filter of a dashboard with parameters of questions in a dashboard it is not possible.

**Logs**

**Javascript console log**
XHRGEThttps://metabase.gruberreisen.at/api/collection/12
[HTTP/2.0 200 OK 10ms]

XHRGEThttps://metabase.gruberreisen.at/api/dashboard/16
[HTTP/2.0 200 OK 24ms]

XHRPOSThttps://metabase.gruberreisen.at/api/card/53/query
[HTTP/2.0 200 OK 80ms]

XHRPOSThttps://metabase.gruberreisen.at/api/card/52/query
[HTTP/2.0 200 OK 77ms]

XHRPOSThttps://metabase.gruberreisen.at/api/card/55/query
[HTTP/2.0 200 OK 82ms]

XHRPOSThttps://metabase.gruberreisen.at/api/card/54/query
[HTTP/2.0 200 OK 102ms]

XHRPOSThttps://metabase.gruberreisen.at/api/card/57/query
[HTTP/2.0 200 OK 92ms]

XHRPOSThttps://metabase.gruberreisen.at/api/card/56/query
[HTTP/2.0 200 OK 76ms]

TypeError: e is null app-main.bundle.js:5:622424
Error: Minified React error #136; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=136&args[]=Scalar for the full message or use the non-minified dev environment for full errors and additional helpful warnings. vendor.bundle.js:1:232345
XHRPUThttps://metabase.gruberreisen.at/api/dashboard/16
[HTTP/2.0 200 OK 16ms]

XHRGEThttps://metabase.gruberreisen.at/api/dashboard/16
[HTTP/2.0 200 OK 22ms]

Invariant Violation: "Minified React error #136; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=136&args[]=Scalar for the full message or use the non-minified dev environment for full errors and additional helpful warnings."
    exports https://metabase.gruberreisen.at/app/dist/vendor.bundle.js?a43410d9fdb01c3119b9:1
    updateComponent https://metabase.gruberreisen.at/app/dist/vendor.bundle.js?a43410d9fdb01c3119b9:1
    receiveComponent https://metabase.gruberreisen.at/app/dist/vendor.bundle.js?a43410d9fdb01c3119b9:1
    receiveComponent https://metabase.gruberreisen.at/app/dist/vendor.bundle.js?a43410d9fdb01c3119b9:1
    updateChildren https://metabase.gruberreisen.at/app/dist/vendor.bundle.js?a43410d9fdb01c3119b9:1
    _reconcilerUpdateChildren https://metabase.gruberreisen.at/app/dist/vendor.bundle.js?a43410d9fdb01c3119b9:1
    _updateChildren https://metabase.gruberreisen.at/app/dist/vendor.bundle.js?a43410d9fdb01c3119b9:1
    updateChildren https://metabase.gruberreisen.at/app/dist/vendor.bundle.js?a43410d9fdb01c3119b9:1
    _updateDOMChildren https://metabase.gruberreisen.at/app/dist/vendor.bundle.js?a43410d9fdb01c3119b9:1
app-main.bundle.js:5:614505
Unhandled promise rejection Invariant Violation: "Minified React error #136; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=136&args[]=Scalar for the full message or use the non-minified dev environment for full errors and additional helpful warnings."
    exports https://metabase.gruberreisen.at/app/dist/vendor.bundle.js?a43410d9fdb01c3119b9:1
    updateComponent https://metabase.gruberreisen.at/app/dist/vendor.bundle.js?a43410d9fdb01c3119b9:1
    receiveComponent https://metabase.gruberreisen.at/app/dist/vendor.bundle.js?a43410d9fdb01c3119b9:1
    receiveComponent https://metabase.gruberreisen.at/app/dist/vendor.bundle.js?a43410d9fdb01c3119b9:1
    updateChildren https://metabase.gruberreisen.at/app/dist/vendor.bundle.js?a43410d9fdb01c3119b9:1
    _reconcilerUpdateChildren https://metabase.gruberreisen.at/app/dist/vendor.bundle.js?a43410d9fdb01c3119b9:1
    _updateChildren https://metabase.gruberreisen.at/app/dist/vendor.bundle.js?a43410d9fdb01c3119b9:1
    updateChildren https://metabase.gruberreisen.at/app/dist/vendor.bundle.js?a43410d9fdb01c3119b9:1
    _updateDOMChildren https://metabase.gruberreisen.at/app/dist/vendor.bundle.js?a43410d9fdb01c3119b9:1
vendor.bundle.js:1:1884528

**Server logs around the time this bug occurred**
`[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:04+02:00 DEBUG metabase.middleware.log GET /api/user/current 200 3,1 ms (3 DB calls) Jetty threads: 6/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:04+02:00 DEBUG metabase.middleware.log GET /api/session/properties 200 3,0 ms (1 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:05+02:00 DEBUG metabase.middleware.log GET /api/database 200 3,2 ms (3 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:05+02:00 DEBUG metabase.middleware.log GET /api/session/properties 200 2,2 ms (1 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:05+02:00 DEBUG metabase.middleware.log GET /api/setting 200 516,9 µs (0 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:05+02:00 DEBUG metabase.middleware.log GET /api/setting 200 607,4 µs (0 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:05+02:00 DEBUG metabase.middleware.log GET /api/setup/admin_checklist 200 5,4 ms (11 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:07+02:00 DEBUG metabase.middleware.log GET /api/task 200 693,2 ms (2 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:15+02:00 DEBUG metabase.middleware.log GET /api/collection/root/items 200 4,6 ms (6 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:17+02:00 DEBUG metabase.middleware.log GET /api/collection/7 200 2,3 ms (3 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:17+02:00 DEBUG metabase.middleware.log GET /api/collection/7/items 200 5,1 ms (8 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:29+02:00 DEBUG metabase.middleware.log GET /api/collection/12 200 3,0 ms (4 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:29+02:00 DEBUG metabase.middleware.log GET /api/collection/12/items 200 5,6 ms (8 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:33+02:00 DEBUG metabase.middleware.log GET /api/dashboard/16 200 16,7 ms (12 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:33+02:00 DEBUG metabase.middleware.log POST /api/card/53/query 200 [ASYNC: completed] 66,3 ms (15 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 1
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:33+02:00 DEBUG metabase.middleware.log POST /api/card/52/query 200 [ASYNC: completed] 76,8 ms (15 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:33+02:00 DEBUG metabase.middleware.log POST /api/card/55/query 200 [ASYNC: completed] 91,7 ms (15 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 3
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:33+02:00 DEBUG metabase.middleware.log POST /api/card/57/query 200 [ASYNC: completed] 85,0 ms (15 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 2
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:33+02:00 DEBUG metabase.middleware.log POST /api/card/54/query 200 [ASYNC: completed] 98,3 ms (15 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 1
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:33+02:00 DEBUG metabase.middleware.log POST /api/card/56/query 200 [ASYNC: completed] 90,2 ms (15 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:36+02:00 DEBUG metabase.middleware.log GET /api/collection/12 200 2,6 ms (4 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:37+02:00 DEBUG metabase.middleware.log GET /api/dashboard/16 200 15,5 ms (12 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:37+02:00 DEBUG metabase.middleware.log POST /api/card/53/query 200 [ASYNC: completed] 68,3 ms (15 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 5
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:37+02:00 DEBUG metabase.middleware.log POST /api/card/55/query 200 [ASYNC: completed] 57,9 ms (15 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 4
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:37+02:00 DEBUG metabase.middleware.log POST /api/card/52/query 200 [ASYNC: completed] 82,3 ms (15 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 3
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:37+02:00 DEBUG metabase.middleware.log POST /api/card/54/query 200 [ASYNC: completed] 77,6 ms (15 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 2
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:37+02:00 DEBUG metabase.middleware.log POST /api/card/57/query 200 [ASYNC: completed] 70,3 ms (15 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 1
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:37+02:00 DEBUG metabase.middleware.log POST /api/card/56/query 200 [ASYNC: completed] 77,3 ms (15 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:42+02:00 DEBUG metabase.middleware.log GET /api/collection/12 200 3,1 ms (4 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:44+02:00 DEBUG metabase.middleware.log GET /api/dashboard/16 200 14,5 ms (12 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:44+02:00 DEBUG metabase.middleware.log POST /api/card/53/query 200 [ASYNC: completed] 74,6 ms (15 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 5
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:44+02:00 DEBUG metabase.middleware.log POST /api/card/52/query 200 [ASYNC: completed] 71,8 ms (15 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 4
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:44+02:00 DEBUG metabase.middleware.log POST /api/card/55/query 200 [ASYNC: completed] 75,9 ms (15 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 3
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:44+02:00 DEBUG metabase.middleware.log POST /api/card/56/query 200 [ASYNC: completed] 70,0 ms (15 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 2
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:44+02:00 DEBUG metabase.middleware.log POST /api/card/57/query 200 [ASYNC: completed] 82,2 ms (15 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 1
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:00:44+02:00 DEBUG metabase.middleware.log POST /api/card/54/query 200 [ASYNC: completed] 88,9 ms (15 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:01:13+02:00 DEBUG metabase.middleware.log PUT /api/dashboard/16 200 7,1 ms (5 DB calls) Jetty threads: 5/50 (3 idle, 0 queued) (62 total active threads) Queries in flight: 0
[dd5d8ca3-7fc6-44c3-9226-6699fdaa256c] 2019-09-04T16:01:13+02:00 DEBUG metabase.middleware.log GET /api/dashboard/16 200 13,3 ms (12 DB calls) Jetty threads: 5/50 (3 idle, 0 queued) (62 total active threads) Queries in flight: 0`

**To Reproduce**
1. Create a dashboard and add questinos. Same issue when opening an existing dashboard with questions
2. Click on the pencil to edit the dashboard
3. Add a filter for time
4. See error --> Questions still show previous results. It is not possible to match the filter with parameters of the questions
5. If you click on save dashboard the button shows that saving failed

**Expected behavior**
If I add or edit a filter to a dashboard all questions ask for the parameter to filter.

**Screenshots**
1. I edit the filter
2. The header shows to choose the field on the card I want to filter
3. No card offers to choose a field

![grafik](https://user-images.githubusercontent.com/3726156/64263252-9fa03500-cf2f-11e9-9690-23ef33027ebe.png)

**Information about your Metabase Installation:**
- Your browser and the version: Firefox 68.0.2 64-Bit
- Your operating system: Windows 10 1903 (Client), Debian GNU/Linux 10 buster (Server)
- Your databases: Postgres 11.5
- Metabase version: 0.33.0
- Metabase hosting environment: Jar-file on Debian
- Metabase internal database: Postgres

**Severity**
Is this **BLOCKING** my usage of Metabase entirely!
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**
Sometimes it works

**Comment by paulrosenzweig** [comment] 2019-09-05 18:23
@maxschloegl I'm unable to reproduce this. Does it happen every time you add a time filter to any dashboard? Can you reproduce it with the sample dataset that ships with Metabase?

**Comment by maxschloegl** [comment] 2019-09-05 21:53
How is it possible to add the sample dataset to my DB?
It seams if I have questions with more than 100.000 results the bug appears. If I add a filter to the question itself to limit the results to f.e. 1.000 results it works.

Prok. Max Schlögl - Geschäftsführung
GRUBER-reisen.

T: +43 316 7089 4511 A: Puchstraße 176, 8055 Graz
https://www.gruberreisen.at max.schloegl@gruberreisen.at

GRUBER Touristik GmbH HG Wien FN 214982a | ATU-53633798
GRUBER-reisen. Veranstalter GmbH HG Wien FN 131553k | ATU-38331300
GRUBER-Golfreisen GmbH LG für ZRS Graz FN 162612k | ATU-43626509
Bretanide Resort d.o.o. Split FN 060182684 | HR-13041542128
________________________________
Von: Paul Rosenzweig <notifications@github.com>
Gesendet: Thursday, September 5, 2019 8:23:50 PM
An: metabase/metabase <metabase@noreply.github.com>
Cc: Max Schlögl <max.schloegl@gruberreisen.at>; Mention <mention@noreply.github.com>
Betreff: Re: [metabase/metabase] Dashboard, cannot add filters and save failed (#10796)


@maxschloegl<https://github.com/maxschloegl> I'm unable to reproduce this. Does it happen every time you add a time filter to any dashboard? Can you reproduce it with the sample dataset that ships with Metabase?

**Comment by paulrosenzweig** [comment] 2019-09-05 23:31
If you visit `/admin/databases`, you should see this link "Bring the sample dataset back":

![image](https://user-images.githubusercontent.com/691495/64389929-b5d2f180-d012-11e9-9740-3b73f25024ff.png)

Reproducing the bug with the sample dataset will help us fix it since we can duplicate the exact conditions on our machines.

---
A few other questions:

* What kind of questions are these? Native SQL or GUI?
* When you say "Sometimes it works", does it both work and fail on the same question? Does something besides row count seem to influence it?

**Comment by maxschloegl** [comment] 2019-09-06 08:06
I testet now with the sample dataset.

1. I created a question with the sample data. (Join of all 4 tables --> 106.880 rows)
2. Created a new dashboard with the question from sample dataset.
3. Added a filter for time.
4. It worked (1)
5. After that I added a question from my dataset to the dashboard.
6. I edited the filter and the bug only occours with the question from my dataset. (2)

Here you can see it on the screenshot:
![grafik](https://user-images.githubusercontent.com/3726156/64410181-c0c96880-d08a-11e9-9062-6442dd39b939.png)

> What kind of questions are these? Native SQL or GUI?

I have only GUI questions

> When you say "Sometimes it works", does it both work and fail on the same question? Does something besides row count seem to influence it?

Difficult to reproduce.
But after some testing I found another evidence.
After editing and saving one question (add another filter; save, delete the filter; save) the bug with the filter on the dashboard does not happen anymore so a can match the dashboard filter witch the question.

See here:
![grafik](https://user-images.githubusercontent.com/3726156/64411376-52d27080-d08d-11e9-8a06-71dfdff8cb8f.png)

At the moment it works and I am not able to repoduce what I have to do that the bug occours again.
That is what I ment, that it sometimes works. :-)

**Comment by maxschloegl** [comment] 2019-09-16 10:46
Hello @paulrosenzweig! 
Do you have further information for me?
BR
Max

**Comment by paulrosenzweig** [comment] 2019-09-18 15:55
@maxschloegl it's hard for me to find a cause without being able to reproduce the issue locally. Any help you can provide in narrowing down the situation where it occurs would be great!

Can you find any pattern to when the error occurs? Some things to try: 
* Does it always fail above a certain row count?
* Does it fail after a certain change is made before the page is reloaded? Or only after the page is reloaded?
* Does it happen with some types of filters? Or on certain column types?

**Comment by flamber** [comment] 2019-09-23 21:24
@paulrosenzweig I've just noticed that there are 15 database calls, which is a hardcoded connection limit, so could that have some unintentional consequences? See 8679, not sure, avoiding link.

**Comment by paulrosenzweig** [comment] 2019-09-24 22:04
@flamber hmm interesting idea! If it were a db connection issue, would other things break too?

@maxschloegl you can try out a workaround for that issue described in this comment: https://github.com/metabase/metabase/issues/8679#issuecomment-509560314

**Comment by flamber** [comment] 2019-09-24 22:18
@paulrosenzweig From what I understand, the 15 hardcoded connection limit per database also means the metadata database, so if all the connections are in use for the metadata, then I would think the UI would suffer - or have to wait in queue up to the 50 limit Jetty connections (configurable).
But it's getting to a complexity level where I would throw in the :towel: and Better Call Saul ™ :laughing:
Note that I'm not sure if this is related to that, I just noticed the 15 calls, while supporting someone in the forum with a problem about that limit.

**Comment by maxschloegl** [comment] 2019-09-25 09:57
@flamber Thank you for your hint.

@paulrosenzweig How can I change this parameter?
Can I change it directly in die .jar file or do I have to change the sourcecode and compile the .jar again.
If I have to compile it how do I do this?

BR Max

**Comment by paulrosenzweig** [comment] 2019-09-26 20:36
@maxschloegl Yes you'll need to recompile. Here are the instructions for how to do that: https://github.com/metabase/metabase/blob/master/docs/developers-guide.md#build-metabase

**Comment by grimxd** [comment] 2019-11-28 09:58
I am having the exact same issue, even with the sample dataset. I am mostly using field filters.
The **solution** that kind of works for me is:
**Open a single question from the dashboard -> open editor -> variables -> open field to map to (it will display the fields) -> go back to the dashboard and now I can map the filter to all questions.**
I don't know why this works but it works most of the times.

**Comment by flamber** [comment] 2019-11-28 17:13
@grimxd Can you provide steps-to-reproduce with Sample Dataset? What do you see in the browser console and Metabase log around the time, when it fails to save?

**Comment by grimxd** [comment] 2019-11-29 14:10
I can't seem to reproduce it with sample dataset now, maybe the metabase server instance was overloaded at that point. As the op posted at first, this error doesn't always happen. It seems that on the sample dataset happens even less or not at all.

Regarding the browser console:
I noticed that I always have in the console this error when opening a dashboard.

`Uncaught Invariant Violation: Minified React error #44; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=44 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
at e.exports (...)
at Object.e.exports [as findDOMNode] (...)
at d.value  (...)
at n._updateSize (...)`
 The error is twice for each question
And then some lines with:
`dataset::fieldRefForColumn mismatch              app-main.bundle.js?d1dced319abf1b617b66:5 
dataset::fieldRefForColumn mismatch              app-main.bundle.js?d1dced319abf1b617b66:5 
dataset::fieldRefForColumn mismatch              app-main.bundle.js?d1dced319abf1b617b66:5 
`
This error is there both when the filter bug occurs and when it doesn't so I don't think is related.

**Comment by flamber** [comment] 2019-11-29 17:24
@grimxd Can you post Diagnostic Info from Admin > Troubleshooting?

**Comment by grimxd** [comment] 2019-12-03 10:50
Sorry for late reply. I am having trouble replicating the issue now, my previous solution seem to have solved it. I will try to do a new droplet on digitalocean similar to the one that had the issue.
I think that part of the problem might be as following:

- On the metabase server instance I had _This is a large database, so let me choose when Metabase syncs and scans_ turned **on** with scheduling to scan at night **3-4am**.
-  I turned off the metabase server instance and then on the database server some modifications were made (not by me, I don't know exactly what. Maybe even in the schema)
-  I turned on the metabase server instance at about **1pm**, so the scan didn't take place yet.

This is when I had the issue.
Some times when I triggered the scan manually on a database the filter issue didn't happen, but sometimes even with the manual scan complete the issue happened. The only thing that worked was the solution in my previous post.

I will post Diagnostic Info from Admin > Troubleshooting as soon as I manage to replicate the bug.

**Comment by flamber** [comment] 2020-04-02 17:44
@maxschloegl 
I'm going to close this. If you figure out how to reproduce the problem, then please comment.
There has been several really strange issues, which has been caused by proxies like Cloudflare, so in case you're using a proxy, then that is likely the reason for the problem. Also see:
https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html

**Closed by flamber** 2020-04-02 17:44 UTC
Labels: .Unable to Reproduce, Priority:P3, Querying/Parameters & Variables, Reporting/Dashboards, Type:Bug
