### ISSUE TITLE
Provide a way to disable split axis on line/area/bar charts

### ISSUE THREAD

**Issue by rohit-guitar** [metabase/metabase#2317] opened 2016-04-05 22:23 UTC
I have 2 questions created from my database. They both have the same x axis. When i go to Dashboard and click Add data, I see two trend line but two different Y axis as well. Please refer to the attached image. 
![problem](https://cloud.githubusercontent.com/assets/5105736/14299954/71eaec46-fb5b-11e5-96a8-52e385d2720d.PNG)

How can i solve this?

**Comment by camsaul** [comment] 2016-04-05 22:24
Hi @rohit-guitar, please fill in these blanks, it will help us diagnose your issue:

*  I am using the ___________ browser.
*  My computer's OS is ___________.
*  My database is ___________.
*  My Metabase version is ___________.

**Comment by salsakran** [comment] 2016-04-05 22:25
Strictly speaking, this isn't a bug, but intended behavior. Metabase is splitting the two axis  to allow you to compare the two series. If it was a single axes, on of those time series would hug the x-axis and not be discernable.

**Comment by rohit-guitar** [comment] 2016-04-05 22:27
I am using the __Chrome V49_________ browser.
My computer's OS is _Windows 10__________.
My database is _Sql Server__________.
My Metabase version is ___0.16.1________.

**Comment by tlrobinson** [comment] 2016-04-05 22:27
That said, we should give the user a way to disable axis splitting if they really want to.

**Comment by tlrobinson** [comment] 2016-08-13 00:19
This was resolved by the chart settings branch #2931, released in 0.19.0

**Closed by tlrobinson** 2016-08-13 00:19 UTC
Labels: Proposal, Visualization, Visualization/Chart Settings
