### ISSUE TITLE
Add a reply-to header to subscription emails/all emails

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#18682] opened 2021-10-26 20:14 UTC
**Is your feature request related to a problem? Please describe.**
Some cloud customers would like to receive responses to the subscription emails. As we don't support tailored SMTP servers, we could add a customizable reply to header to the emails so they can get the response. 

**Describe the solution you'd like**
Add a reply-to header to emails so when users receive an email they can reply to the one that's in the header which might be different from the senders¡

**Describe alternatives you've considered**
None, the alternative should be a bit harder

**How important is this feature to you?**
Important for some cloud customers

**Additional context**
Sent by a cloud customer

**Comment by metamben** [comment] 2022-04-29 18:24
@paoliniluis @flamber What is the preferred solution reply-to for just subscription emails or for all emails? What exactly is meant by subscription email? The one you get when somebody adds you to an alert?

**Comment by paoliniluis** [comment] 2022-04-29 19:46
@metamben we thought to have an option to set up this reply to for all emails so customers could reply to a different email other than the default in the cloud

**Comment by metamben** [comment] 2022-04-29 19:54
@paoliniluis Does the setting need to be accessible in the UI or is a server-side setting enough?

**Comment by paoliniluis** [comment] 2022-04-29 21:23
Looping @brunobergher for that

**Comment by brunobergher** [comment] 2022-04-29 21:29
This is a [project slated for 44](https://www.notion.so/metabase/Allow-Admins-to-define-a-reply-to-header-6d6d216a633f4a5bbe6408f6875b7afc).

**Comment by calherries** [comment] 2022-06-20 06:11
Closing due to being a duplicate of #22540

**Closed** 2022-06-20 06:15 UTC
Labels: Reporting/Pulses, Type:New Feature, Administration/Settings, Misc/Emails
