### ISSUE TITLE
tooltip show label bug, I have provided a video, please watch it

### ISSUE THREAD

**Issue by 8debug** [metabase/metabase#15327] opened 2021-03-25 00:45 UTC
## Please watch the video below

https://user-images.githubusercontent.com/3394927/112401712-1be2af00-8d46-11eb-8b08-0c3f7d7f6462.mp4

![image](https://user-images.githubusercontent.com/3394927/112402237-1d60a700-8d47-11eb-94d1-08b0d20c12e2.png)
![image](https://user-images.githubusercontent.com/3394927/112402253-25204b80-8d47-11eb-9895-0bf5784caa5f.png)
![image](https://user-images.githubusercontent.com/3394927/112402260-2782a580-8d47-11eb-9df9-b290f6b24796.png)

**Comment by flamber** [comment] 2021-03-25 08:54
Duplicate of #11395

**Closed by flamber** 2021-03-25 08:54 UTC
Labels: .Needs Triage, Type:Bug
