### ISSUE TITLE
Date formatting

### ISSUE THREAD

**Issue by mtmmtm9** [metabase/metabase#14078] opened 2020-12-15 06:59 UTC
**Describe the bug**
Dates are formatted wrong in Sweden (2020-11-27, 24:27  or 2020-12-15, 24:26:18.656).
They should be formatted as 2020-11-27, 0:27  or 2020-12-15, 0:26:18.656.
It happens only when the hour is between 0 and 1.

**To Reproduce**
Make a report using a date. (using metabase + postgresql + date-type TIMESTAMPTZ)

Expected behaviour:
They should be formatted as 2020-11-27, 0:27  or 2020-12-15, 0:26:18.656.

Version used:
jar-file metabase v0.37.2
running on Linux.

**Severity**
minor

**Comment by flamber** [comment] 2020-12-15 10:03
Duplicate of #9538

**Closed by flamber** 2020-12-15 10:03 UTC
Labels: .Needs Triage, Type:Bug
