### ISSUE TITLE
Add a setting to insert a session tracking Javascript code snippet

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#40998] opened 2024-04-04 00:10 UTC
**Is your feature request related to a problem? Please describe.**
Embedded Metabase does not allow admins to add a Javascript snipped for session tracking like Hotjar or similar.

**Describe the solution you'd like**
Add a setting to input a Javascript snippet for session tracking or specific plugins for Hotjar, etc. URLs (like select a supported session tracker, then enter the relevant parameters in a second input.)

**Describe alternatives you've considered**
- Custom build, does not work for Cloud customers

**How important is this feature to you?**
- a few requests per year from customers

**Additional context**
- https://help.hotjar.com/hc/en-us/articles/115011624347-Can-I-Track-iframes-Inside-Heatmaps-and-Recordings

**Comment by albertoperdomo** [comment] 2024-05-21 13:22
Duplicate of https://github.com/metabase/metabase/issues/5462 @likeshumidity ?

**Comment by paoliniluis** [comment] 2024-12-07 23:08
dupe

**Closed by paoliniluis** 2024-12-07 23:08 UTC
Labels: Type:New Feature, .Needs Triage, Embedding/Public, Embedding/Static, Embedding/Interactive, .Team/Embedding
