### ISSUE TITLE
Control initial load of question/dashboard

### ISSUE THREAD

**Issue by rcronin** [metabase/metabase#20870] opened 2022-03-06 15:17 UTC
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem, but current behavior of the dashboard and question functionality. Dashboards load automatically and yes you can control default filters but it’d be nice to have functionality to control whether the dashboard requires users to run the dashboard or not. Questions on the other hand can be controlled by requiring filters. 

**Describe the solution you'd like**
Some sort of setting on a question and dashboard that allows a user to disable initial load. Enabling this would obviously not load the dashboard or question and then it gives the user the opportunity to change the filters and then run the dashboard or question.

**Describe alternatives you've considered**
No real alternative on a dashboard but requiring a filter value on a question works.

**How important is this feature to you?**
As we get more users on Metabase, this will just save resources not having to load an insane amount of data initially. Priority 7/10 for us.

**Additional context**
This feature is built in out of the box in other BI platforms.

**Comment by flamber** [comment] 2022-03-06 15:22
Duplicate of #18097 and #12002, and very related to #9871.

**Closed by flamber** 2022-03-06 15:22 UTC
Labels: Type:New Feature, .Needs Triage
