### ISSUE TITLE
Impossible to save changes on click behavior 

### ISSUE THREAD

**Issue by ValentinGuicheteau** [metabase/metabase#24872] opened 2022-08-18 15:15 UTC
I have a dashboard with several cards configured with a click behavior to filter the entire dashboard. When I try to "unset" the click behavior by selecting  'do nothing' instead of 'update dashboard's filter' you simply can't press the save button (see .gif video).

1. Go to an already configured dashboard with click behavior
2. Click on 'modify click behavior' on a card
3. Set the mode from 'update dashboard's filter' to 'do nothing'
4. Try to press the save button

It should be possible to click on the save button.

![mb_click_behavior_bug](https://user-images.githubusercontent.com/62407182/185429839-bda4a9ff-0689-4f57-8262-19276ded636b.gif)

Information :
- Browser version : Google Chrome Version 104.0.5112.81
- OS : Windows 10
- Database : Postgres
- Metabase version: 0.41.5

Severity :
The problem is not necessarily blocking because you can bypass the use of the save button by clicking for example on the configuration of another card.

**Comment by flamber** [comment] 2022-08-18 15:52
Duplicate of #16573

**Closed by flamber** 2022-08-18 15:52 UTC
Labels: Type:Bug, .Needs Triage
