### ISSUE TITLE
Dashboard filters dropdown stopped working for multiple table field

### ISSUE THREAD

**Issue by luissancho** [metabase/metabase#4909] opened 2017-04-28 10:16 UTC
- Your browser and the version: Chrome 56.0
- Your operating system: OS X 10.12.3
- Your databases: MySQL
- Metabase version: metabase-head:latest
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

I have several dashboards that uses a category filter witch value comes from the same value but two different tables, such as "country code" (es, en, fr, etc...) in "clients" and "services".

It takes all posible values and set it as dropdown filter, even though it had to look for all posible values from both tables. Until latest master version, that those filters stopped working and now are all plain text filters. It only works if all cards in dashboard are filtered by the same table and field.

<img width="275" alt="screenshot-dropdown" src="https://cloud.githubusercontent.com/assets/12734676/25524719/12e8e27e-2c0c-11e7-9450-4a11d2a538df.png">

I'm not sure if this is a bug or something fully planned. Does somebody see this issue?

**Comment by luissancho** [comment] 2017-05-02 15:59
What is the criteria followed to convert dashboard filters in popovers (dropdown select)? Where is that handled in code? Is it max number of values? Or if every card's field is coming from the same database table?

Please, I need to know if this is going to get fixed, so I don't change all our model to adapt.

Thanks.

**Comment by mazameli** [comment] 2017-05-02 19:08
After talking with @tlrobinson, my understanding is that the logic for this is that we show all the values in a list if there are fewer than 300 distinct options available, otherwise we only show the input box.

**Comment by zihzihtw** [comment] 2017-05-09 09:22
Hi,
I have the same problem.
The amount of the distinct options is only 20, but I still can't use the dropdown menu.

<img width="793" alt="2017-05-09 5 17 22" src="https://cloud.githubusercontent.com/assets/7886453/25843927/84e0547a-34db-11e7-9901-ca7ca19a5a2b.png">

Does anyone know what's wrong?

Thanks

**Comment by tanzoniteblack** [comment] 2017-05-19 22:04
I've run into this same issue and spent a little while investigating it today.

It used to be that if a dashboard filter was filtering multiple tables, it would show drop down items from one of them (probably the first? never really checked that out), and since generally this was done on our side when I was using dashboards to show both values from our regular DB and different DB that shows a normalized version I was using the dashboard filter to filter items that happen to be the same, and it worked.

Now, however, the instant you select a filter on a dashcard that is using a different DB/Table/Column combination, the `field_id` parameter to the `ParameterValueWidget` changes to `null`, and therefore when it ends up calling https://github.com/metabase/metabase/blob//frontend/src/metabase/parameters/components/ParameterValueWidget.jsx#L36 it doesn't have any values found, because there's not a field for it to try to get the completions from.

What I would actually expect to happen in this case, is for there to be a list of fields that are available for autocompletion, and that the candidates are a unique set of candidates from all of the fields in question.

**Comment by moumny** [comment] 2017-06-16 11:51
Ok took me a while to find the root cause, you need to change === to >=
        in https://github.com/metabase/metabase/blob/master/frontend/src/metabase/dashboard/selectors.js#L164

        field_id: fieldIds.length >= 1 ? fieldIds[0] : null

**Comment by salsakran** [comment] 2017-07-27 22:20
bumping this to 0.25.2 since 0.25.1 needs to be released with a critical patch.

**Comment by attekei** [comment] 2017-09-19 08:56
Resolved by #5543

**Closed by attekei** 2017-09-19 08:56 UTC
Labels: Bug, Dashboards, Parameters/Variables, UX

**Comment by mazameli** [comment] 2017-09-27 19:24
Hey everyone. Just a heads up that [we've shipped version 0.26](http://www.metabase.com/blog/Metabase-0.26) which fixes this issue.

**Comment by AmbrishKora** [comment] 2018-06-05 05:35
I got the same issue again. I am using 0.29.0v Metabase.
Please help searched a lot to get it fixed.

**Comment by SrancsikAtBitrise** [comment] 2018-08-06 09:44
I have this issue on 0.29.3. The filters used to work, then now they are empty. Added new filters, saved the dashboard, worked fine but only till I reloaded the page.

**Comment by alexcohaniuc** [comment] 2018-09-04 11:52
I'm using  v0.29.3
Any update on this?

**Comment by SrancsikAtBitrise** [comment] 2018-09-04 19:27
I cannot reproduce the issue after upgrading to 0.30.0.

**Comment by eschultze** [comment] 2018-10-31 17:37
Hi, I'm facing this same issue now while running on Metabase 0.30.4. Any workarounds on this matter?

**Comment by lahorekid** [comment] 2018-12-10 08:07
Running  0.31.1 version no drop down list in filters. Any tips to solve this issue?

**Comment by fatica** [comment] 2018-12-12 14:30
We are also experiencing the same problem.

We have a dashboard with multiple cards.  When all cards are sourced from the same table the drop-down filters work fine.  These are drop-downs to select the locale, which has only 3 or 4 unique values. 

When another card is added to the dashboard which uses a different table and the locale field is hooked up to the locale filter, the drop-down *sometimes* stops populating the drop-down lists with unique values.  

Steps to reproduce:

1. Create a dashboard with cards only sourced from table A, establish category filters on Field A
2. Add a card from table B which has Field A in common and link the filters to table B on Field A. 
3.  Observe that the filters function as expected,
4.  Reload the page.
5. Observe that the filters no longer include the drop-down options and do not autocomplete.

Both fields in both tables are configured the same way.  

This video shows the issue

https://public.3.basecamp.com/p/wWfQBbJpqCrYyhe1VpN6fZSP

**Comment by nrdsdata** [comment] 2018-12-16 05:17
Found a work around where if you duplicate the Filter A  as Filter B and only connect  Filter B it to one card. Filter A works. Its ugly but it makes it work

**Comment by ATL64** [comment] 2019-03-21 10:50
Can this issue be reopened? Also having this problem.  Currently using workaround as commented by nrdsdata, but the more filters you got, the messier the dashboard gets (each filter needs to get duplicated)

**Comment by ATL64** [comment] 2019-03-21 10:56
Found open issues for this here : https://github.com/metabase/metabase/issues/8698

**Comment by stekes** [comment] 2020-07-24 12:17
> 
> 
> We are also experiencing the same problem.
> 
> We have a dashboard with multiple cards. When all cards are sourced from the same table the drop-down filters work fine. These are drop-downs to select the locale, which has only 3 or 4 unique values.
> 
> When another card is added to the dashboard which uses a different table and the locale field is hooked up to the locale filter, the drop-down _sometimes_ stops populating the drop-down lists with unique values.
> 
> Steps to reproduce:
> 
>     1. Create a dashboard with cards only sourced from table A, establish category filters on Field A
> 
>     2. Add a card from table B which has Field A in common and link the filters to table B on Field A.
> 
>     3. Observe that the filters function as expected,
> 
>     4. Reload the page.
> 
>     5. Observe that the filters no longer include the drop-down options and do not autocomplete.
> 
> 
> Both fields in both tables are configured the same way.
> 
> This video shows the issue
> 
> https://public.3.basecamp.com/p/wWfQBbJpqCrYyhe1VpN6fZSP

We are having a similar issue in v0.35.4

We have two filters in a dashboard. One filters a field from the tables which are used in the questions in the dashboard and the other one, through a relation. The filter which goes trough the relation does not render as a list or has auto-complete. The first one is a list! 
Both fields are declared the same way in the model (Category and filtering as "list of values").

**Comment by flamber** [comment] 2020-07-24 12:37
@stekes I don't know what "through a relation" means, but this issue has been closed for almost 3 years. There has been a lot of fixes to dashboards and filters in the latest 0.36.0 release: https://github.com/metabase/metabase/releases/tag/v0.36.0
