### ISSUE TITLE
[Feature Request] Opening dashboard cards in new windows

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#9755] opened 2019-04-10 16:31 UTC
When looking at a dashboard, the user may want to dig deeper and open some of the cards without losing the current open dashboard. The intuitive way is to open the card in a new tab. But apparently this is not possible. Clicking on the name of the card (link at the top left of the card) opens the card in the current window (so losing the current open dashboard). Right-clicking the link doesn't give the option to open in a new tab.

**Comment by flamber** [comment] 2019-04-10 17:22
Duplicate of #5168
It is somewhat implemented in #8860 by using the `metaKey` in 0.31.2

**Closed** 2019-04-10 17:49 UTC

**Comment by RMMSecurity** [comment] 2019-04-11 18:30
> Duplicate of #5168
> It is somewhat implemented in #8860 by using the `metaKey` in 0.31.2

I'll add that it might not work depending on the Browser/OS

**Comment by cqcn1991** [comment] 2019-06-21 03:29
I appreciate what https://github.com/metabase/metabase/issues/5168 has achieved. 
but why not enable right click/direct link instead of using the metakey?

**Comment by flamber** [comment] 2019-06-21 03:38
Hi @cqcn1991 
Have a look at the comments throughout the #5168. It's because it's not a `<a>` link, so that entire logic would need to be changed.
