### ISSUE TITLE
mysql table can not using date column index 

### ISSUE THREAD

**Issue by caochangshan** [metabase/metabase#18927] opened 2021-11-10 03:06 UTC
**Describe the bug**
mysql custom query cannot use date column **index** 

**To Reproduce**
1.The query I'm running is:
select count(1) from game_order_detail where {{betTime}}
![image](https://user-images.githubusercontent.com/62995787/141040712-75034c8b-de82-49a4-8ea4-9540f78e8936.png)

2.And the resulting SQL is:
select 
count(1) 
from game_order_detail 
where 
 **date**(`game_order_detail`.`create_time`) BETWEEN date '2021-10-11' AND date '2021-11-09'

**Expected behavior**
Remove date functions

`select 
count(1) 
from game_order_detail 
where 
`game_order_detail`.`create_time` BETWEEN date '2021-10-11' AND date '2021-11-09'

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_251-b08",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_251",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.251-b08",
    "os.name": "Linux",
    "os.version": "4.18.0-193.el8.x86_64",
    "user.language": "en",
    "user.timezone": "Etc/GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.41.1",
      "date": "2021-10-21",
      "branch": "release-x.41.x",
      "hash": "76aa4a5"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2021-11-10 08:43
Duplicate of #17711
You should upgrade to Java 11: https://www.metabase.com/docs/latest/operations-guide/java-versions.html
And migrate away from H2 if you're running in production: https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html

**Closed by flamber** 2021-11-10 08:43 UTC

**Comment by noear** [comment] 2021-11-17 13:37
顶起：）
