### ISSUE TITLE
Admin: last login time confuses UTC with local timezone

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#15408] opened 2021-03-30 21:55 UTC
**Describe the bug**
If local timezone is different than UTC (eg. CEST), when in Admin -> People, then the last login time shows "2 hours ago" even when I am logged in right now.

**To Reproduce**
1. Ensure you have system timezone different than UTC (eg. CEST).
2. Go to Admin -> People.
3. Notice your own last login time is shown with an offset from now (eg. "2 hours ago" if you're in CEST).

**Expected behavior**
I expect the time to be calculated relative to the current timezone.

**Information about your Metabase Installation:**
`{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "13.0.2",
    "java.vm.name": "Eclipse OpenJ9 VM",
    "java.vm.version": "openj9-0.18.0",
    "os.name": "Linux",
    "os.version": "4.15.0-66-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.32"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-01-13",
      "tag": "v0.37.6",
      "branch": "release-x.37.x",
      "hash": "344e5e0"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}`

**Severity**
A minor issue.

**Additional context**
Tried searching, but couldn't find such an issue.

**Comment by paoliniluis** [comment] 2021-03-31 01:35
@andreychirikba what have you configured as the JVM timezone?

**Comment by flamber** [comment] 2021-03-31 11:50
Duplicate of #14654

**Closed by flamber** 2021-03-31 11:50 UTC
Labels: .Needs Triage, Type:Bug
