### ISSUE TITLE
After archiving collection and unarchiving some of its questions, question will be restored to an unknown location

### ISSUE THREAD

**Issue by CZvacko** [metabase/metabase#37644] opened 2024-01-12 15:22 UTC
### Describe the bug

After archiving the entire collection and unarchiving some of its questions, question will be restored to an unknown location (related collection is NOT restored).

### To Reproduce

1. Select Collection (with some questions inside)
2. Archive whole collection
3. Unarchive some question from that collection (users may not realize that they have to Unarchive collection first - which is hidden somewhere at bottom of archive)
4. Question become restored, but user cannot find it in ANY collection. Able to find/open question only when use searchbox

### Expected behavior

When user unarchive question, related collection should be restored too if previously archived

### Information about your Metabase installation

```JSON
Metabase version 0.48.1 - 0.48.3
```

### Severity

low

**Comment by paoliniluis** [comment] 2024-01-12 15:25
So this is an effect of https://github.com/metabase/metabase/issues/2783, as the question will be restored but inside an archived collection

**Comment by paoliniluis** [comment] 2024-01-12 15:26
sorry, this is a duplicate of https://github.com/metabase/metabase/issues/26168

**Closed by paoliniluis** 2024-01-12 15:26 UTC
Labels: Type:Bug, Priority:P2, Organization/Collections, Organization/Archive
