### ISSUE TITLE
Mongodb Unix timestamp convert

### ISSUE THREAD

**Issue by thucnc** [metabase/metabase#3249] opened 2016-08-22 04:00 UTC
If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is Ubutun.
*  My data is in a Mongodb database. [Postgres / MySQL / Redshift / BigQuery / MongoDB / SQLite / SQL Server / etc.]
*  My Metabase version is v0.19.2.

My database uses Unix Timestamp and we want Metabase to convert it to readable format, but I failed to use 'new Date(0)' to convert it to datetime type. Please advise. Thanks
Here is a simple example and error message:
[   
    {"$match": {"time": {"$gt": 1471833194}}},
    {"$project": {"date": new Date(0)}}
]

=> Unrecognized token 'new': was expecting 'null', 'true', 'false' or NaN at [Source: java.io.StringReader@1f6a5bcc; line: 3, column: 30]

**Comment by camsaul** [comment] 2016-08-22 17:54
Hi @thucnc, this is a duplicate of #3170, which we plan on addressing for our next release.

**Closed by camsaul** 2016-08-22 17:54 UTC
Labels: Duplicate

**Comment by usopan** [comment] 2018-02-22 08:29
I am still getting the same error message in version 0.28.1
