### ISSUE TITLE
Option to Send Subscriptions on Weekdays Only

### ISSUE THREAD

**Issue by stephenblount** [metabase/metabase#34138] opened 2023-09-26 13:39 UTC
**Problem Description**
When setting up email subscriptions it is difficult to create a subscription that only sends on weekdays.

**Solution**
When the weekly option is selected for the email subscription, allow the "on" option to be a multi-select. This way a user could choose Monday through Friday, or any combination of days. 
![image](https://github.com/metabase/metabase/assets/65960696/62c54b4b-8f3f-4663-8754-f3d557f2feb5)

**Alternatives**
An alternative solution is to create five separate email subscriptions for the same recipients, one for each weekday. At scale this is challenging to maintain and troubleshoot. 

**Importance**
There would be a large time savings in setting up and maintaining email subscriptions.

**Comment by luizarakaki** [comment] 2023-09-26 14:30
@stephenblount we are considering adding a `custom: cron syntax` option to set schedules. Would this be a reasonable option for you?

**Comment by stephenblount** [comment] 2023-09-26 14:33
@luizarakaki Yes, a field to input custom cron syntax would solve this problem. Example: 0 0 * * 1-5 “At 00:00 on every day-of-week from Monday through Friday.”

**Comment by paoliniluis** [comment] 2023-09-26 17:40
Dupe of https://github.com/metabase/metabase/issues/3846 @luizarakaki

**Closed** 2023-09-26 17:57 UTC
Labels: Reporting/Pulses, Type:New Feature
