### ISSUE TITLE
Bad "Time style" transformation

### ISSUE THREAD

**Issue by InkOut** [metabase/metabase#12992] opened 2020-07-24 07:28 UTC
**Describe the bug**
Metabase converts 12:30 AM to 24:30. 
![image](https://user-images.githubusercontent.com/5202843/88369135-0fade880-cd98-11ea-84d9-7a22680487d5.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/5202843/88369279-556ab100-cd98-11ea-90be-5aabfd6d40c5.png)

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "ru-RU",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.15.0-55-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.3 (Ubuntu 12.3-106-yandex.48058.5060275aa8)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-07-21",
      "tag": "v0.36.0",
      "branch": "release-0.36.x",
      "hash": "b31049f"
    },
    "settings": {
      "report-timezone": "Europe/Moscow"
    }
  }
}
```

**Comment by flamber** [comment] 2020-07-24 09:13
Duplicate of #9538

**Closed by flamber** 2020-07-24 09:13 UTC
Labels: .Needs Triage, Type:Bug
