### ISSUE TITLE
metrics are not migrated from v0.29.3 to v0.30.1

### ISSUE THREAD

**Issue by on99** [metabase/metabase#8399] opened 2018-08-25 02:28 UTC

**Comment by on99** [comment] 2018-08-25 02:41
![image](https://user-images.githubusercontent.com/13196393/44614221-346b4f80-a853-11e8-9881-9ca9fe7be9d3.png)

I don't see any migration error log in metabase, but the metrics are not migrated. I am not sure if it's related to Chinese characters in metrics.

**Comment by on99** [comment] 2019-02-18 08:06
The migration process may potentially archive the metrics.

I figure out that this sql `UPDATE metric SET archived = 0` helps getting all my metrics back

**Comment by tlrobinson** [comment] 2019-02-20 00:28
Duplicate of #8277

**Closed by tlrobinson** 2019-02-20 00:28 UTC
Labels: Bug, Metrics & Segments, Priority/P3
