### ISSUE TITLE
Metabase with mongodb is too slow

### ISSUE THREAD

**Issue by muniyandibg** [metabase/metabase#28405] opened 2023-02-17 13:04 UTC
I am running metabase in localhost using mongodb as datasource.
Created a native query with lookup processing around 5 collection data.

The query takes more than 2 minutes to show the results with
2000 records in the metabase ui.

It takes around 15 to 20minutes to export the result
to csv which has around 30k records.

Is this normal or is there anything can be done to improve the speed.

Thanks.

**Comment by luizarakaki** [comment] 2023-02-17 14:03
@muniyandibg We need more information to understand what is going on. How large are these collections? What MongoDB version are you using? Is your MongoDB cluster running locally? What CPU are you using?

**Comment by paoliniluis** [comment] 2023-02-17 15:52
@muniyandibg we will proceed to close the issue as you didn't follow the bug template. We can't reproduce what you're saying in any way without you providing information about sizing or structure of your collections/documents. E.g. if you're running an old version of Mongo on a raspberry pi, then things will be slow

**Closed by paoliniluis** 2023-02-17 15:52 UTC
Labels: Type:Question, Database/Mongo, .Performance, .Needs Triage

**Comment by muniyandibg** [comment] 2023-02-18 05:03
I am using remote mongodb atlas db. Running metabase locally in my system.
These collections have 30k to 60k records.

Please let me know if you need any other information.

Thanks

**Comment by paoliniluis** [comment] 2023-02-18 09:03
Run the same queries in your mongo cli and let us know how much time it takes
