### ISSUE TITLE
Hitting enter doesn't save filter changes

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#6552] opened 2017-12-09 00:13 UTC
So I'm typing a new value for my Query Builder filter in and since my hands are already on the keyboard I hit enter thinking it will apply the values like it does everywhere else in the app where we use filters (for example Dashboard params). Instead it just closes the filter popover and does not apply any changes at all.

In fact since you *must* hit enter to apply other filters IMO this is confusing behavior 101. 

![annoying](https://user-images.githubusercontent.com/1455846/33790134-7a17bdd6-dc32-11e7-89f7-0a55a708cf8d.gif)

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by mazameli** [comment] 2017-12-09 00:18
I could have sworn I'd filed an issue for this already, but in any case I agree a million times yes to this. Enter should absolutely commit the changes.

**Comment by camsaul** [comment] 2017-12-09 00:21
This is related to #2059 I think

**Comment by flamber** [comment] 2019-02-18 01:38
It seems to be only an issue for date pickers. When trying number/string picker, then it saves on `Enter`.
On the date picker, if you try to input 300 and press `Tab` and then `Enter`, then it works. `OnBlur` issue?

**Comment by ranquild** [comment] 2022-08-04 07:52
Unassigning since the UI has changed and it's not clear what the correct behavior would be.

**Comment by uladzimirdev** [comment] 2023-07-26 08:57
I believe that UI has been reworked and we don't have this issue anymore.

**Comment by nemanjaglumac** [comment] 2023-11-08 08:02
I can still reproduce this on latest master d35c779976ae6bd79369e9cc6bec8540908f37d2.

1. Open any table from the Sample Database (let's use Analytic Events)
2. Click on a timestamp column
3. Choose "Filter by this column" from the dropdown
4. Choose "Last 30 days" (It should show no results)
![Image](https://github.com/metabase/metabase/assets/31325167/475f14c4-bfa6-424e-969b-dbb3abc3be13)
5. Click on a filter "Timestamp Previous 30 Days" to edit it
![Image](https://github.com/metabase/metabase/assets/31325167/e4f0f14a-7345-492a-90d2-3fb04d934697)
6. Edit the number and click "enter" - nothing happens
![Image](https://github.com/metabase/metabase/assets/31325167/21dc1cf8-fcc5-47d4-bf50-2df3f6ba7867)

Also not that it says "Add filter" and not "Update filter"

**Comment by WiNloSt** [comment] 2023-11-08 12:25
Fixed in https://github.com/metabase/metabase/pull/34851/commits (e546daa65437dd32bed1d91ce133c022eb5bbabb), the filter got updated immediately when the value is changed
![image](https://github.com/metabase/metabase/assets/1937582/1eeb5f26-a27e-40fd-8a4d-f431503f1cff)

**Comment by ranquild** [comment] 2023-11-14 10:42
Fixed by https://github.com/metabase/metabase/pull/35658

**Closed by ranquild** 2023-11-14 10:42 UTC
Labels: Type:UX, Priority:P2, .Frontend, Querying/GUI, .Wanted: MLv2, .Team/QueryingComponents
