### ISSUE TITLE
Auto split works in customize chart but not on chart itself

### ISSUE THREAD

**Issue by erix920** [metabase/metabase#7749] opened 2018-05-29 16:02 UTC
When auto split is needed for a dataset using a line chart, one group shows correctly while the other is pinned to the 0 mark. However, when customizing the chart, it looks perfect in that preview.

I am running release 29.3 using MySQL 8 for both the Metabase DB and data DB.

![image](https://user-images.githubusercontent.com/3211179/40670669-d72ee468-6337-11e8-9e30-e1f9af83028e.png)
![image](https://user-images.githubusercontent.com/3211179/40670722-f63752b4-6337-11e8-9ece-2abb250e68a6.png)

**Comment by jornh** [comment] 2018-05-29 16:49
Hi @erix920,

I'm pretty sure it would help the developers immensely to reproduce this error if you were somehow able to give steps with e.g. the Sample Dataset that Metabase comes with. 

Reason is that the "automagic" split Y-axis behavior AFAIK depends a lot on the incoming dataset. So if it's something specific to your data - then the trick to fixing the bug is to find the combination of data where it fails. As an example you see below I tried getting a split Y-axis view with the `Orders` table - and it didn't fail 😞 

![image](https://user-images.githubusercontent.com/766423/40672967-a58019bc-6370-11e8-9447-b7ef071b1fe8.png)

**Comment by jornh** [comment] 2018-05-29 18:52
If you look at my screenshot in https://github.com/metabase/metabase/issues/7749#issuecomment-392848683 above you see that I specifically picked some very odd metrics to view together: `Average of Product Rating` and `Average of Total` to get to something that **do** create a split Y-axis view ... that works. And BTW here's the corresponding settings view which displays the same (with the default "on" position of the "Use a split y-axis when necessary" toggle)

![image](https://user-images.githubusercontent.com/766423/40678413-c84f6ba4-6380-11e8-8695-748a52518a74.png)

Note - my point is not to say that your findings are wrong. It is to say that it depends on the data: The split axis works with some data and not with some other data. So it's helpful to find some dataset that can be shared to the team that triggers the wrong behaviour.

**Comment by erix920** [comment] 2018-05-29 20:07
Looks like it is under certain conditions in which my data always falls into.

Try out this setup and let me know if it gives you the issue - 

![image](https://user-images.githubusercontent.com/3211179/40682648-5d556810-635a-11e8-949b-69397b16bcdd.png)

**Comment by jornh** [comment] 2018-05-29 21:53
Yep, confirmed!

I see the same behavior as you with that input criteria.

> The datatype of Ean is not defined in Metabase which is the same as in my data. Maybe that is causing the issue. 

Not sure if it’s linked to Ean not having a type defined. I tried setting it to Enum and Category ... it made no difference.

I think it’s debateable if the reproduced case with the sample dataset really falls within the "Use a split y-axis when necessary“ criteria - but there sure is for your production data. Good part is that the behavior with difference between the settings screen and final screen is reproduced, so there’s something for the team to dig into the codebase from.

**Comment by erix920** [comment] 2018-05-30 23:15
Great, thanks for confirming!

**Comment by flamber** [comment] 2020-06-26 20:40
I cannot reproduce on 0.35.4 - likely fixed in 0.33.0 if not before

**Closed by flamber** 2020-06-26 20:40 UTC
Labels: Priority:P2, Type:Bug, Visualization/Chart Settings
