### ISSUE TITLE
Request to add more bin options for grid map or even customized bin options

### ISSUE THREAD

**Issue by xyupony** [metabase/metabase#9479] opened 2019-02-23 02:28 UTC
Hi all,

Currently for the grid map visualization, the default bin options for latitude/longitude are quite limited, with only `auto`, `0.1`, `1`, `10`, `20` degree options, which is rather inconvenient.

I checked this PR https://github.com/metabase/metabase/pull/7348 , and it didn't mention why there are only 5 options, so I wonder could more options be added? Like `0.01`, `0.001` or even with an input box to allow users to customize bin value?

Thanks.

**Comment by MarcGJA** [comment] 2019-03-15 17:11
@xyupony Have a look at the following and if you feel it covers your proposal please close your issue:
<a href="https://github.com/metabase/metabase/issues/9208">Give Users Map & Legend Binning Control (enhancement) #9208</a>

Although it refers to maps (geojson) it is applicable to all visualizations across the board, users should have the ability to define binning including the assigning of hex (hash) code colors per some secondary field.

**Comment by salsakran** [comment] 2019-04-10 04:38
dupe of #9208

**Closed by salsakran** 2019-04-10 04:38 UTC
