### ISSUE TITLE
Variable on Question SQL Editor not works

### ISSUE THREAD

**Issue by omysurya** [metabase/metabase#11382] opened 2019-11-25 07:26 UTC
(conn=81) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SET @date_start = '2019-10-01'

**Comment by flamber** [comment] 2019-11-25 07:49
Hi @omysurya 
Please provide all the information as requested, when opening a bug.
Looks like a duplicate of #4050. If you agree, then please close this and upvote the other issue :+1:
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by mazameli** [comment] 2019-12-18 23:46
Closing as duplicate of #4050

**Closed by mazameli** 2019-12-18 23:46 UTC
Labels: .Duplicate
