### ISSUE TITLE
Unable to connect to Metabase DB w/ Windows 10

### ISSUE THREAD

**Issue by chtefi** [metabase/metabase#1871] opened 2016-02-03 23:17 UTC
Hey,

I'm on Windows, and wanted to give a try at metabase using the .jar, but it seems it can't connect to the metabase DB (on h2 by default).
I've looked around in the issue and just saw #1853 that pops the same error as me, but in my case, I can't even make it run.

I mean, I can start it, go to `localhost:3000` but the loading screen stays (i can't access the create account screens) and in the logs, there are infinite calls to `GET /api/health 503`.

Am I missing something ?
Do I have a way to know what's going on ? 

Here are the logs :

```
$ java -jar metabase.jar
2016-02-04 00:10:14,447 [INFO ] org.eclipse.jetty.util.log :: Logging initialized @1988ms
WARNING: update already refers to: #'clojure.core/update in namespace: clj-http.client, being replaced by: #'clj-http.client/update
2016-02-04 00:10:19,458 [INFO ] metabase.core :: Starting Metabase in STANDALONE mode
2016-02-04 00:10:19,493 [INFO ] metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

2016-02-04 00:10:19,514 [INFO ] org.eclipse.jetty.server.Server :: jetty-9.2.z-SNAPSHOT
2016-02-04 00:10:19,544 [INFO ] org.eclipse.jetty.server.ServerConnector :: Started ServerConnector@19e64900{HTTP/1.1}{0.0.0.0:3000}
2016-02-04 00:10:19,545 [INFO ] org.eclipse.jetty.server.Server :: Started @7087ms
2016-02-04 00:10:19,553 [INFO ] metabase.core :: Starting Metabase version v0.14.0 (bbfdf23 HEAD)...
2016-02-04 00:10:19,842 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.druid
2016-02-04 00:10:19,927 [DEBUG] metabase.driver :: Registered driver :druid.
2016-02-04 00:10:19,938 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.h2
2016-02-04 00:10:20,068 [DEBUG] metabase.driver :: Registered driver :h2.
2016-02-04 00:10:20,070 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.mongo
2016-02-04 00:10:21,134 [DEBUG] metabase.driver :: Registered driver :mongo.
2016-02-04 00:10:21,135 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.mysql
2016-02-04 00:10:21,145 [DEBUG] metabase.driver :: Registered driver :mysql.
2016-02-04 00:10:21,146 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.postgres
2016-02-04 00:10:21,160 [DEBUG] metabase.driver :: Registered driver :postgres.
2016-02-04 00:10:21,164 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.redshift
2016-02-04 00:10:21,172 [DEBUG] metabase.driver :: Registered driver :redshift.
2016-02-04 00:10:21,172 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.sqlite
2016-02-04 00:10:21,182 [DEBUG] metabase.driver :: Registered driver :sqlite.
2016-02-04 00:10:21,183 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.sqlserver
2016-02-04 00:10:21,194 [DEBUG] metabase.driver :: Registered driver :sqlserver.
2016-02-04 00:10:21,195 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.sync
2016-02-04 00:10:21,443 [INFO ] metabase.db :: Verifying Database Connection ...
2016-02-04 00:10:26,448 [ERROR] metabase.driver :: Failed to connect to database: Timed out after 5000 milliseconds.
Exception in thread "main" java.lang.AssertionError: Assert failed: Unable to connect to Metabase DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((clojure.core/deref (resolve (quote metabase.driver/can-connect-with-details?))) engine details))
        at metabase.db$verify_db_connection.invoke(db.clj:149)
        at metabase.db$setup_db.doInvoke(db.clj:163)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at metabase.core$init_BANG_.invoke(core.clj:130)
        at metabase.core$start_normally.invoke(core.clj:211)
        at metabase.core$_main.doInvoke(core.clj:245)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
2016-02-04 00:10:42,649 [ERROR] metabase.middleware :: GET /api/health 503 (1 ms)
{:status "initializing", :progress 0.4}

2016-02-04 00:10:43,274 [ERROR] metabase.middleware :: GET /api/health 503 (170 Ás)
{:status "initializing", :progress 0.4}
```

The H2 db is properly created in my current folder : 

```
$ ls metabase.db.h2.db
metabase.db.h2.db
```

Thanks,

**Comment by agilliland** [comment] 2016-02-03 23:53
Can you give me a few pieces of information so that I can try reproducing this?

* what version of Metabase are you running?
* what version of Windows is this happening on?
* what version of Java are you using?

**Comment by agilliland** [comment] 2016-02-03 23:54
Also, did this happen on a brand new installation of Metabase?  or had you run the metabase.jar file before?

**Comment by chtefi** [comment] 2016-02-04 09:19
I'm not on my PC right now but I was running on Windows 10, metabase.jar from the website `http://www.metabase.com/start/jar.html` and the latest Java 8_71 (pretty sure).

And yes, it was a fresh install. But it's possible that I already gave it a try few months ago, I don't remember exactly. Could this have an impact, some metadata left somewhere (such as `/Application Data`) ?

**Comment by agilliland** [comment] 2016-02-04 23:44
Cool, thanks for the info.  It'll probably take me a little bit of time to dig into this a bit because I don't spend a lot of time on a PC, but i'll take a look.

Metabase only attempts to access the H2 database file in the same location it is launched by default, so there shouldn't be any files left lying around from previous installations.

I'll see if I can reproduce this and we'll go from there.

**Comment by gps13** [comment] 2016-02-09 14:36
Hi I probably have the same problem.

Setup
Windows 10, java 1.8.0_73

Have tried:
1. jar file
2. updated java (had older version -> upgraded to 1.8.0_73)
3. restart windows 
4. tried docker 
5. tried Mozilla, Chrome, Edge

Still I get the following log:

```
$ java -jar metabase.jar
2016-02-09 16:30:44,789 [INFO ] org.eclipse.jetty.util.log :: Logging initialized @2830ms
WARNING: update already refers to: #'clojure.core/update in namespace: clj-http.client, being replaced by: #'clj-http.client/update
2016-02-09 16:30:49,880 [INFO ] metabase.core :: Starting Metabase in STANDALONE mode
2016-02-09 16:30:49,905 [INFO ] metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

2016-02-09 16:30:49,926 [INFO ] org.eclipse.jetty.server.Server :: jetty-9.2.z-SNAPSHOT
2016-02-09 16:30:49,957 [INFO ] org.eclipse.jetty.server.ServerConnector :: Started ServerConnector@167c42f{HTTP/1.1}{0.0.0.0:3000}
2016-02-09 16:30:49,957 [INFO ] org.eclipse.jetty.server.Server :: Started @8000ms
2016-02-09 16:30:49,962 [INFO ] metabase.core :: Starting Metabase version v0.14.1 (56b123e release-0.14.1)...
2016-02-09 16:30:50,384 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.druid
2016-02-09 16:30:50,449 [DEBUG] metabase.driver :: Registered driver :druid.
2016-02-09 16:30:50,460 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.h2
2016-02-09 16:30:50,624 [DEBUG] metabase.driver :: Registered driver :h2.
2016-02-09 16:30:50,626 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.mongo
2016-02-09 16:30:51,537 [DEBUG] metabase.driver :: Registered driver :mongo.
2016-02-09 16:30:51,538 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.mysql
2016-02-09 16:30:51,552 [DEBUG] metabase.driver :: Registered driver :mysql.
2016-02-09 16:30:51,553 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.postgres
2016-02-09 16:30:51,590 [DEBUG] metabase.driver :: Registered driver :postgres.
2016-02-09 16:30:51,594 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.redshift
2016-02-09 16:30:51,603 [DEBUG] metabase.driver :: Registered driver :redshift.
2016-02-09 16:30:51,603 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.sqlite
2016-02-09 16:30:51,615 [DEBUG] metabase.driver :: Registered driver :sqlite.
2016-02-09 16:30:51,616 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.sqlserver
2016-02-09 16:30:51,630 [DEBUG] metabase.driver :: Registered driver :sqlserver.
2016-02-09 16:30:51,631 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.sync
2016-02-09 16:30:52,082 [INFO ] metabase.db :: Verifying Database Connection ...
2016-02-09 16:30:57,088 [ERROR] metabase.driver :: Failed to connect to database: Timed out after 5000 milliseconds.
Exception in thread "main" java.lang.AssertionError: Assert failed: Unable to connect to Metabase DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((clojure.core/deref (resolve (quote metabase.driver/can-connect-with-details?))) engine details))
        at metabase.db$verify_db_connection.invoke(db.clj:149)
        at metabase.db$setup_db.doInvoke(db.clj:163)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at metabase.core$init_BANG_.invoke(core.clj:130)
        at metabase.core$start_normally.invoke(core.clj:211)
        at metabase.core$_main.doInvoke(core.clj:245)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
```

**Comment by agilliland** [comment] 2016-02-20 01:46
Hmmm, so I've just gotten a chance to try this out on a Windows 10 laptop running Java 1.8.0_60 and while there was one part of the initialization which is a bit slower than expected, everything has worked and I haven't been able to reproduce the error you guys are reporting.  I am just running `java -jar metabase.jar` from inside Windows PowerShell.

My suspicion is that something about your local computer setups are blocking the ability for the H2 database to initialize itself properly and that's what's causing the error you are seeing.  Are you using any kind of special firewall rules or security software that might be clamping down on things?

**Comment by camsaul** [comment] 2016-02-20 02:16
Powershell? I would assume most people run it from `cmd`

**Comment by agilliland** [comment] 2016-02-20 18:02
I get the same result either way.  Everything works fine.

**Comment by chtefi** [comment] 2016-02-20 23:29
Got some news with that. I successfully made metabase run on my Windows.
I investigated with some tools and the source code, and pointed out that clearly, the h2 socket connection couldn't be made for some reasons as you said @agilliland.

I checked my `ipconfig` and notice I had a bunch of adapters. I had docker, virtualbox and some other softwares like that. I decided to uninstall them to get a cleaner `ipconfig`, and finally, metabase worked. Not sure which software did mess up with the local connection.

**Comment by tlrobinson** [comment] 2016-06-03 08:43
I'm running into this error in Windows 10 running in VMware Fusion. It looks like it creates the `metabase.db.lock` file but not the actual database.

**Comment by kritop** [comment] 2016-07-05 15:05
anyone any clue on the health 503 errors? i get them too on heroku.

**Comment by tomkanjam** [comment] 2016-07-05 15:36
@kritop The only time I see 503 errors is when the database has been locked. More info:
http://www.metabase.com/docs/v0.18.1/operations-guide/start#metabase-fails-to-startup

You can also delete the row from the databasechangeloglock table.

**Comment by x2764tech** [comment] 2017-02-22 13:02
I had this problem and solved it by right clickling on metabase.jar, choosing properties and clicking  unblock (this is the same as the [PS Unblock-File cmdlet](https://msdn.microsoft.com/powershell/reference/5.1/microsoft.powershell.utility/Unblock-File) )

**Comment by camsaul** [comment] 2017-03-29 18:15
I sounds like the fix for this issue is just unblocking the downloaded file as mentioned above 

Maybe we just need to add documentation about doing this?

**Comment by camsaul** [comment] 2017-04-07 17:32
I've been unable to repro this on 3 different PCs I tried yesterday. It sounds like for people who are seeing it there's either:

*  Something wrong with the `ipconfig` configuration, as @chtefi noted
*  The file needs to be unblocked by right-clicking and choosing "Unblock". (Not sure why only some people need to do this)

I think maybe it makes sense to add documentation about these situations and close this as a bug since there isn't anything fixable on our end.

**Comment by salsakran** [comment] 2017-04-07 18:50
👍  to adding some docs around this. Agreed, that it sounds more like configuration issues we don't have control over.

**Closed** 2017-04-07 19:51 UTC
Labels: Bug, Help Wanted, OS/Windows, Priority/P1, Running Metabase

**Comment by parallogix** [comment] 2017-04-13 04:35
I also had issues with this.  I have Win10 Java 8u121x86/64.  I have Nmap installed and the network drivers for the loopback were causes the connection issues for me.  Once I disabled them everything worked fine.

**Comment by SSchaaf** [comment] 2017-05-08 14:37
Same error here. Windows 2012 more than one adapter. Only one with IP. Solved with H2 System property h2.bindAddress. My java command : 

`java -Dh2.bindAddress=192.168.20.200 -Xms512m -Xmx512m -Xss1024k -jar metabase.jar`

**Comment by hawkwinger** [comment] 2017-06-22 16:30
I have Win10 and Java Version 8.31. I've tried using both cmd and Windows Powershell. Nothing works. Is there anything else that needs to be installed other than JDK and JRE?
`C:\Users\Admin>java -jar metabase.jar
06-22 21:34:36 [1mINFO metabase.util[0m :: Loading Metabase...
06-22 21:34:41 [1mINFO util.encryption[0m :: DB details encryption is DISABLED for this Metabase instance. ?
06-22 21:34:53 [1mINFO metabase.core[0m :: Starting Metabase in STANDALONE mode
06-22 21:34:53 [1mINFO metabase.core[0m :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

06-22 21:34:53 [1mINFO metabase.core[0m :: Starting Metabase version v0.24.2 (b859d40 release-0.24.2) ...
06-22 21:34:53 [1mINFO metabase.core[0m :: System timezone is 'Asia/Calcutta' ...
06-22 21:34:53 [1mDEBUG metabase.driver[0m :: Registered driver [34m:bigquery[0m ?
06-22 21:34:53 [1mDEBUG metabase.driver[0m :: Registered driver [34m:crate[0m ?
06-22 21:34:53 [1mDEBUG metabase.driver[0m :: Registered driver [34m:druid[0m ?
06-22 21:34:53 [1mDEBUG metabase.driver[0m :: Registered driver [34m:googleanalytics[0m ?
06-22 21:34:53 [1mDEBUG metabase.driver[0m :: Registered driver [34m:h2[0m ?
06-22 21:34:54 [1mDEBUG metabase.driver[0m :: Registered driver [34m:mongo[0m ?
06-22 21:34:54 [1mDEBUG metabase.driver[0m :: Registered driver [34m:mysql[0m ?
06-22 21:34:54 [1mDEBUG metabase.driver[0m :: Registered driver [34m:postgres[0m ?
06-22 21:34:54 [1mDEBUG metabase.driver[0m :: Registered driver [34m:presto[0m ?
06-22 21:34:54 [1mDEBUG metabase.driver[0m :: Registered driver [34m:redshift[0m ?
06-22 21:34:54 [1mDEBUG metabase.driver[0m :: Registered driver [34m:sqlite[0m ?
06-22 21:34:54 [1mDEBUG metabase.driver[0m :: Registered driver [34m:sqlserver[0m ?
06-22 21:34:54 [1mINFO metabase.core[0m :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
06-22 21:34:54 [1mINFO metabase.db[0m :: [36mVerifying h2 Database Connection ...[0m
06-22 21:34:59 [1mERROR metabase.driver[0m :: Failed to connect to database: Timed out after 5000 milliseconds.
java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
        at metabase.db$verify_db_connection.invokeStatic(db.clj:334)
        at metabase.db$verify_db_connection.invoke(db.clj:327)
        at metabase.db$verify_db_connection.invokeStatic(db.clj:330)
        at metabase.db$verify_db_connection.invoke(db.clj:327)
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:382)
        at metabase.db$setup_db_BANG_.doInvoke(db.clj:376)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at metabase.core$init_BANG_.invokeStatic(core.clj:103)
        at metabase.core$init_BANG_.invoke(core.clj:82)
        at metabase.core$start_normally.invokeStatic(core.clj:187)
        at metabase.core$start_normally.invoke(core.clj:181)
        at metabase.core$_main.invokeStatic(core.clj:279)
        at metabase.core$_main.doInvoke(core.clj:274)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
06-22 21:34:59 [1mERROR metabase.core[0m :: Metabase Initialization FAILED:  Assert failed: Unable to connect to Metabase h2 DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
06-22 21:34:59 [1mINFO metabase.core[0m :: Metabase Shutting Down ...
06-22 21:34:59 [1mINFO metabase.core[0m :: Metabase Shutdown COMPLETE`

This is what is shows. Both the cases.

**Comment by camsaul** [comment] 2017-06-23 17:50
@hawkwinger did you try the suggestions mentioned in this thread?

**Comment by camsaul** [comment] 2017-06-23 19:41
At any rate these issues should be fixed by #5396 which will ship with our upcoming release in a week or so

**Comment by toybaelescione** [comment] 2018-05-31 09:17
Solved by try to connect to h2 shell, then disconnect.
`java -cp metabase.jar org.h2.tools.Shell -url jdbc:h2:/opt/metabase/metabase.db`

**Comment by NasreenUstad** [comment] 2019-09-06 12:37
https://github.com/metabase/metabase/issues/3250#issuecomment-528837487
