### ISSUE TITLE
SQL server in metabase

### ISSUE THREAD

**Issue by rohit-guitar** [metabase/metabase#2310] opened 2016-04-05 14:57 UTC
If this is a bug report, please fill in the blanks:

*  I am using the ___chrome__v49______ browser.
*  My computer's OS is __windows 10_________.
*  I'm running Metabase _jar file 0.16__________. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is _SQL server__________.
*  My Metabase version is ___0.16________.

I cannot connect to the sql server. I am just keep getting issue like timeout in 5000 miliseconds

**Comment by agilliland** [comment] 2016-04-05 15:06
dupe of #1854

**Closed by agilliland** 2016-04-05 15:06 UTC
Labels: Duplicate
