### ISSUE TITLE
Can't save permissions

### ISSUE THREAD

**Issue by BenjaminGK** [metabase/metabase#17795] opened 2021-09-08 01:57 UTC
**Describe the bug**
When trying to modify a collections permissions for who has access and can read/write, I get the following error upon saving. We haven't had this issue previously
**_There was an error saving
(conn=296926095) Data too long for column 'before' at row 1_**

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

```
[d4bf9017-adfb-4a8f-a2a5-c17b253c5443] 2021-09-08T08:41:13+07:00 ERROR metabase.server.middleware.log PUT /api/collection/graph 500 169.4 ms (20 DB calls) 
{:via
 [{:type java.sql.SQLSyntaxErrorException,
   :message "(conn=296926095) Data too long for column 'before' at row 1",
   :at [org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory createException "ExceptionFactory.java" 62]}
  {:type org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException,
   :message "Data too long for column 'before' at row 1",
   :at [org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException of "MariaDbSqlException.java" 34]}
  {:type java.sql.SQLException,
   :message "Data too long for column 'before' at row 1",
   :at [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol readErrorPacket "AbstractQueryProtocol.java" 1688]}],
 :trace
 [[org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol readErrorPacket "AbstractQueryProtocol.java" 1688]
  [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol readPacket "AbstractQueryProtocol.java" 1550]
  [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol getResult "AbstractQueryProtocol.java" 1513]
  [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol executeQuery "AbstractQueryProtocol.java" 318]
  [org.mariadb.jdbc.ClientSidePreparedStatement executeInternal "ClientSidePreparedStatement.java" 220]
  [org.mariadb.jdbc.ClientSidePreparedStatement execute "ClientSidePreparedStatement.java" 149]
  [org.mariadb.jdbc.ClientSidePreparedStatement executeUpdate "ClientSidePreparedStatement.java" 181]
  [com.mchange.v2.c3p0.impl.NewProxyPreparedStatement executeUpdate "NewProxyPreparedStatement.java" 462]
  [clojure.java.jdbc$db_do_execute_prepared_return_keys$exec_and_return_keys__27661 invoke "jdbc.clj" 979]
  [clojure.java.jdbc$db_do_execute_prepared_return_keys invokeStatic "jdbc.clj" 1007]
  [clojure.java.jdbc$db_do_execute_prepared_return_keys invoke "jdbc.clj" 963]
  [clojure.java.jdbc$db_do_prepared_return_keys invokeStatic "jdbc.clj" 1038]
  [clojure.java.jdbc$db_do_prepared_return_keys invoke "jdbc.clj" 1015]
  [toucan.db$simple_insert_many_BANG_$iter__28774__28778$fn__28779$fn__28780 invoke "db.clj" 563]
  [toucan.db$simple_insert_many_BANG_$iter__28774__28778$fn__28779 invoke "db.clj" 561]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5402 invokeStatic "core.clj" 137]
  [clojure.core$dorun invokeStatic "core.clj" 3133]
  [clojure.core$doall invokeStatic "core.clj" 3148]
  [clojure.core$doall invoke "core.clj" 3148]
  [toucan.db$simple_insert_many_BANG_ invokeStatic "db.clj" 560]
  [toucan.db$simple_insert_many_BANG_ invoke "db.clj" 546]
  [toucan.db$simple_insert_BANG_ invokeStatic "db.clj" 593]
  [toucan.db$simple_insert_BANG_ invoke "db.clj" 582]
  [toucan.db$insert_BANG_ invokeStatic "db.clj" 610]
  [toucan.db$insert_BANG_ invoke "db.clj" 597]
  [toucan.db$insert_BANG_ invokeStatic "db.clj" 613]
  [toucan.db$insert_BANG_ doInvoke "db.clj" 597]
  [clojure.lang.RestFn invoke "RestFn.java" 731]
  [metabase.models.collection.graph$save_perms_revision_BANG_ invokeStatic "graph.clj" 127]
  [metabase.models.collection.graph$save_perms_revision_BANG_ invoke "graph.clj" 117]
  [metabase.models.collection.graph$fn__57473$update_graph_BANG___57482$fn__57485$fn__57508 invoke "graph.clj" 156]
  [toucan.db$do_in_transaction$fn__28606 invoke "db.clj" 147]
  [clojure.java.jdbc$db_transaction_STAR_ invokeStatic "jdbc.clj" 807]
  [clojure.java.jdbc$db_transaction_STAR_ invoke "jdbc.clj" 776]
  [clojure.java.jdbc$db_transaction_STAR_ invokeStatic "jdbc.clj" 852]
  [clojure.java.jdbc$db_transaction_STAR_ invoke "jdbc.clj" 776]
  [clojure.java.jdbc$db_transaction_STAR_ invokeStatic "jdbc.clj" 789]
  [clojure.java.jdbc$db_transaction_STAR_ invoke "jdbc.clj" 776]
  [toucan.db$do_in_transaction invokeStatic "db.clj" 145]
  [toucan.db$do_in_transaction invoke "db.clj" 142]
  [metabase.models.collection.graph$fn__57473$update_graph_BANG___57482$fn__57485 invoke "graph.clj" 153]
  [metabase.models.collection.graph$fn__57473$update_graph_BANG___57482 invoke "graph.clj" 133]
  [metabase.api.collection$fn__58159 invokeStatic "collection.clj" 702]
  [metabase.api.collection$fn__58159 invoke "collection.clj" 694]
  [compojure.core$wrap_response$fn__1996 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__1980 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__1985 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 151]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 153]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 153]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 153]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 153]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 152]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 153]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__77067 invoke "auth.clj" 14]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2036 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 296]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [metabase.api.routes$fn__77133$fn__77135 invoke "routes.clj" 70]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 665]
  [clojure.core$apply invoke "core.clj" 660]
  [metabase.server.routes$fn__79369$fn__79370 doInvoke "routes.clj" 57]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2036 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 296]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 153]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 153]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 153]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [metabase.server.routes$fn__79357$fn__79359 invoke "routes.clj" 41]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__77124 invoke "exceptions.clj" 98]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__77121 invoke "exceptions.clj" 86]
  [metabase.server.middleware.log$log_api_call$fn__79283$fn__79284$fn__79285 invoke "log.clj" 209]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 15]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 9]
  [metabase.server.middleware.log$log_api_call$fn__79283$fn__79284 invoke "log.clj" 201]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.server.middleware.log$log_api_call$fn__79283 invoke "log.clj" 200]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__78902 invoke "browser_cookie.clj" 30]
  [metabase.server.middleware.security$add_security_headers$fn__57732 invoke "security.clj" 148]
  [metabase.server.middleware.json$wrap_json_body$fn__79047 invoke "json.clj" 62]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__79065 invoke "json.clj" 98]
  [metabase.server.middleware.offset_paging$handle_paging$fn__57754 invoke "offset_paging.clj" 42]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__79626 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__79642 invoke "params.clj" 69]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__36092 invoke "misc.clj" 59]
  [metabase.server.middleware.session$bind_current_user$fn__42987$fn__42988 invoke "session.clj" 257]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 238]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 230]
  [metabase.server.middleware.session$bind_current_user$fn__42987 invoke "session.clj" 256]
  [metabase.server.middleware.session$wrap_current_user_info$fn__42974 invoke "session.clj" 216]
  [metabase.server.middleware.session$wrap_session_id$fn__42960 invoke "session.clj" 162]
  [metabase.server.middleware.auth$wrap_api_key$fn__77075 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__79546 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__36075 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__36100 invoke "misc.clj" 76]
  [ring.middleware.gzip$wrap_gzip$fn__79588 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__36103 invoke "misc.clj" 93]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__79302 invoke "ssl.clj" 48]
  [metabase.server$async_proxy_handler$fn__78846 invoke "server.clj" 71]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 383]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 556]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 375]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 273]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 336]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 313]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 171]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 129]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 375]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 773]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 905]
  [java.lang.Thread run nil -1]],
 :cause "Data too long for column 'before' at row 1",
 :message "(conn=296926095) Data too long for column 'before' at row 1",
 :sql-exception-chain
 ["SQLSyntaxErrorException:"
  "Message: (conn=296926095) Data too long for column 'before' at row 1"
  "SQLState: 22001"
  "Error Code: 1406"]}
```

**To Reproduce**
1. Go to 'admin'
2. Click on 'permissions'
3. modify permissions on collection
4. press save
5. see error

**Expected behavior**
I would expect to be able to save new permissions

**Screenshots**

![Screen Shot 2021-09-08 at 08 49 17](https://user-images.githubusercontent.com/23311430/132433178-96b7495d-a237-4f67-9f84-ccf9f43c5342.png)
**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "5.11.0-1016-aws",
    "user.language": "en",
    "user.timezone": "Europe/Stockholm"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.33-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-08-03",
      "tag": "v0.40.2",
      "branch": "release-x.40.x",
      "hash": "b884d29"
    },
    "settings": {
      "report-timezone": "Europe/Stockholm"
    }
  }
}

```
**Severity**
It is quite severe as it means we can't control who can access specific reports

**Additional context**

**Comment by BenjaminGK** [comment] 2021-09-08 02:49
It did not happen previously, and we are using MySQL 5.7 on AWS

**Comment by flamber** [comment] 2021-09-08 07:30
Duplicate of #7006

**Closed by flamber** 2021-09-08 07:30 UTC
Labels: Type:Bug, .Needs Triage

**Comment by AlphaIX** [comment] 2022-02-08 03:04
hi there,I have changed  mysql table `permissions_revision` LONGTEXT instead of TEXT, but it does'nt work

**Comment by flamber** [comment] 2022-02-08 09:11
@AlphaIX Have a look here: https://discourse.metabase.com/t/in-administrator-permission-there-is-no-visual-feedback-when-clicking-collections-permissions/18340/6?u=flamber

**Comment by AlphaIX** [comment] 2022-02-10 07:11
@flamber Thanks a lot, it is working now!
