### ISSUE TITLE
Viz icons not showing up in full-app embeds

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#30377] opened 2023-04-25 21:55 UTC
### Context
Viz icons are only showing up if you click or select the visualization in full-app embedding. All icons show up as expected in normal instance.
### Full-app embedding
![image](https://user-images.githubusercontent.com/16455495/234412662-28796526-157c-40ac-be34-ff86bdf90479.png)
### Instance / expected behavior
![image](https://user-images.githubusercontent.com/16455495/234412685-46c28310-e73e-4ffd-9d2f-5791d21694b5.png)

### To Reproduce

1. Go to [https://embedding-demo.metabase.com/](https://embedding-demo.metabase.com/)
2. Click on Reports / New
3. Go to viz settings, see that icons aren't appearing

### Severity

Medium

### Additional context

[Slack context](https://metaboat.slack.com/archives/C045W5MF84U/p1682446343015549)

**Comment by albertoperdomo** [comment] 2023-11-09 12:38
Looks like this for me on https://embedding-demo.metabase.com/reports

<img width="1503" alt="image" src="https://github.com/metabase/metabase/assets/24216/800bd642-ae68-4958-b4dd-c9d001a99fb5">
<img width="1504" alt="image" src="https://github.com/metabase/metabase/assets/24216/137b5084-9e67-483b-abb5-9eb79c0048bf">

**Comment by albertoperdomo** [comment] 2023-11-09 12:47
Can't reproduce. Closing.

**Closed by albertoperdomo** 2023-11-09 12:47 UTC
Labels: Type:Bug, Priority:P2, .Frontend, Embedding/Interactive, .Team/Embedding
