### ISSUE TITLE
Amazon Athena (S3) Driver

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#4418] opened 2017-02-21 17:55 UTC
[Apparently Amazon has a service that lets you query data in S3 using SQL](https://aws.amazon.com/documentation/athena/)

> Amazon Athena is an interactive query service that makes it easy to analyze data in Amazon S3 using standard SQL. Athena is serverless, so there is no infrastructure to setup or manage, and you pay only for the queries you run. To get started, simply point to your data in S3, define the schema, and start querying using standard SQL.

[And they offer a JDBC driver](http://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html)

Something to consider

**Comment by salsakran** [comment] 2017-02-21 18:04
Athena is essentially Presto, so I imagine #4294 would probably be related/a dupe of this.

**Comment by damiencarol** [comment] 2017-03-07 15:50
@salsakran don't konw if Amazon guys kept something compatible with PrestoDB interface.

**Comment by wwwiiilll** [comment] 2017-03-27 19:22
Compatibility was mentioned on my Presto PR, however their JDBC driver is also lacking prepared statement support and their API is very much different from Presto's, so if anything, there's high re-usability between the two, but work is needed to actually be able to talk to Athena.

Since the query language is the same, something similar to what Redash is doing (https://github.com/getredash/redash-amazon-athena-proxy) might work, at least temporarily, the small subset of the Presto API that I'm using could be easily mapped over the Athena driver. If I have a bit of time I might try doing it.

**Comment by mazameli** [comment] 2017-05-22 21:27
Is this a dupe of https://github.com/metabase/metabase/issues/3960? (Or of #4294 as Sameer mentioned?)

**Closed** 2017-05-22 21:29 UTC
Labels: Database Support, Duplicate, Proposal

**Comment by oripwk** [comment] 2018-09-02 10:54
@wwwiiilll, is there anything new on this?

One question:
What if we choose the PrestoDB from the dropdown, but provide a connection string for Athena? Will it work?

`jdbc:awsathena://AwsRegion=[Region];UID=[AccessKey];PWD=[SecretKey];S3OutputLocation=[Output][Property1]=[Value1];[Property2]=[Value2];…`
