### ISSUE TITLE
Grouped By not working for JSON fields

### ISSUE THREAD

**Issue by KarthiAru** [metabase/metabase#5581] opened 2017-07-26 02:29 UTC
**Issue**
The aggregation **view** seems to work, but doesn't display the **Grouped By** names for JSON fields.

<img width="1259" alt="screen shot 2017-07-26 at 7 28 29 am" src="https://user-images.githubusercontent.com/8588253/28601627-f499ed2a-71d6-11e7-9ebc-c89eb7921a0f.png">

**Repeatable steps to reproduce the issue**

Sample Mongodb document
```
{ 
    "_id" : ObjectId("1000"),
    "company" : "Company 1",
    "event_time" : ISODate("2017-07-01T00:10:10.123+0000"),
    "event_type" : "form_submit",
    "event_properties" : {
    "program" : "Program 1",  
    "project" : "Project 1"
    }
}
{ 
    "_id" : ObjectId("1001"),
    "company" : "Company 2",
    "event_time" : ISODate("2017-07-01T00:10:10.123+0000"),
    "event_type" : "form_submit",
    "event_properties" : {
    "program" : "Program 2",  
    "project" : "Project 2"
    }
}
{ 
    "_id" : ObjectId("1003"),
    "company" : "Company 3",
    "event_time" : ISODate("2017-07-01T00:10:10.123+0000"),
    "event_type" : "form_submit",
    "event_properties" : {
    "program" : "Program 3",  
    "project" : "Project 3"
    }
}
```
Do a Grouped By on **Program** and choose any aggregation view. Expected results would be to display the values of the **Program** along with the corresponding aggregated values.

**Query Generated**
```
[{"$project":{"event_properties___program":"$event_properties.program","event_properties":"$event_properties"}},
{"$project":{"_id":"$_id","___group":{"event_properties___program":"$event_properties___program"}}},
{"$group":{"_id":"$___group","count":{"$sum":1}}},
{"$sort":{"_id":1}},
{"$project":{"_id":false,"count":true,"event_properties___program":"$_id.event_properties___program"}},
{"$sort":{"event_properties___program":1}}]
```

**Environment**
- Metabase hosting environment: Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-121-generic x86_64) on DigitalOcean
- Metabase version: v0.25.0 (docker)
- Metabase internal database: Postgres (client) 9.3.17 on DigitalOcean
- Databases: MongoDB v3.0.15 on DigitalOcean
- Browser and the version: Safari Version 10.1.1 (12603.2.4)
- Operating system: MacOS Sierra 10.12.5

-------

**Comment by oliviersaintgobain** [comment] 2017-10-10 10:11
Hello, I'm sorry to introduce in this ticket, but I would like to know how you manage the aggregation view ?
I have a json field, added manually in the table reference, but there is no option when I want to group by...
it seems that it does not recognize json field

thanks a lot

**Comment by flamber** [comment] 2021-11-08 19:55
Closing, since I cannot reproduce on 0.41.1 with Mongo 4.0, but I think this was fixed long ago

**Closed by flamber** 2021-11-08 19:55 UTC
Labels: Type:Bug, Priority:P2, Database/Mongo
