### ISSUE TITLE
Support "Contains" filtering on Arrays

### ISSUE THREAD

**Issue by chucksense** [metabase/metabase#13036] opened 2020-07-30 14:44 UTC
**Is your feature request related to a problem? Please describe.**
We use postsgres and I'd like to be able to use the Metabase Query Builder UI to filter using "Contains" on a column that contains arrays, but the filter UX only allows for "Is", "Is not", "Is empty", and "Not empty."  I'd love to have "Contains" like found on Character types.

**Describe the solution you'd like**
The UX shows "Contains", "Does not contain", "Starts with", and "Ends with" on Array data (both native from the database and in other Saved Questions that utilize the `array_agg()` aggregator) like on strings.

**Describe alternatives you've considered**
I can first create a question to cast it to one of the _Character_ types (e.g., _text_) and then use this first question as a Saved Question to get to the "Contains" filter.  But this creates clutter.

**How important is this feature to you?**
Mildly at most.  Not blocking anything and we do have a workaround.

**Comment by flamber** [comment] 2020-07-30 14:51
Duplicate of #2974 - related to #708 ?

**Closed** 2020-07-30 18:36 UTC
Labels: .Needs Triage, Type:New Feature
