### ISSUE TITLE
Can´t Save UI Question 

### ISSUE THREAD

**Issue by AndreLuizRego** [metabase/metabase#11255] opened 2019-11-01 18:50 UTC
When using the UI to make a question with sumarize that generate "count(*)" (as showed using "SQL View" button), it is not possible to save the resulting question.

1. Go to "Custom question"
2. Choose any table on a MySQL Database
3. Sumarize to count all lines (# of lines) and group by any other column
4. Run the question
5. Click on "Save" and see that it won´t save the question.

**Information about your Metabase Installation:**
- Your browser and the version: Chrome  78.0.3904.70
- Your operating system: Windows 7
- Your databases: MySQL and MongoDB
- Metabase version: 0.34 Snapshot

To overcome this problem you´ve got to copy the code presented on SQL view, create a new native query and substitute count(*) with count(`nameoftable`.`id`).

**Comment by flamber** [comment] 2019-11-07 23:32
Hi @AndreLuizRego 
Do you see any errors in the log?
Which version/commit are you using? Does it work with latest 0.33.4 release?

**Comment by mazameli** [comment] 2019-11-15 22:16
Haven't been able to reproduce this with a MySQL DB or H2 on master or v0.33.5.1.

As Flamber asked, are you seeing any relevant server errors?

**Comment by chris299** [comment] 2019-11-19 16:17
I see the same problem saving UI-generated questions, if the question contains a join
v0.33.5.1 & postgresql

**Comment by flamber** [comment] 2020-02-06 15:57
@AndreLuizRego As I said in the other issue too, you're using a third party version of Metabase, so you need to get support from the people who created that version. Or use an official release: https://www.metabase.com/start/
I'm going to close this issue, since we cannot provide support for third party versions.

**Closed by flamber** 2020-02-06 15:57 UTC
Labels: .Unable to Reproduce, Querying/GUI, Type:Bug
