### ISSUE TITLE
Different visualization types in one chart

### ISSUE THREAD

**Issue by doodlebro** [metabase/metabase#4747] opened 2017-04-10 18:14 UTC
I'd like to be able to use different viz types within the same chart on a dashboard, similarly to how periscopedata allows for this freedom:

<img width="771" alt="screen shot 2017-04-10 at 12 09 43 pm" src="https://cloud.githubusercontent.com/assets/7634378/24875832/a63438d2-1de6-11e7-9cd8-c2d29d13d73c.png">

As you can see, here we are using bars to show daily data, a line to show a net sum, and a shaded area to show a goal to be met by a certain date. Periscope allows for this freedom through the settings panel by each series on a Y-Axis:

<img width="924" alt="screen shot 2017-04-10 at 12 11 54 pm" src="https://cloud.githubusercontent.com/assets/7634378/24875907/ed82dd56-1de6-11e7-9d05-eaf6e1f8e20c.png">

This is very useful, since it allows for complex visualizations that are also compact. Metabase already allows for multiple series on the same chart, so all that needs adding is individual "visualization types" for each series added.

**Comment by mazameli** [comment] 2017-04-10 18:16
Dupe of #3330, but this is good feedback. Thanks!

**Closed by mazameli** 2017-04-10 18:16 UTC
Labels: Duplicate
