### ISSUE TITLE
New field IP

### ISSUE THREAD

**Issue by FJLendinez** [metabase/metabase#13193] opened 2020-09-01 06:32 UTC
**Is your feature request related to a problem? Please describe.**
Metabase has geojson support, has a nice integration with databases and a great design allowing us to provide metadata of what a field is. For that, one possible field that is widely used is IP field that provide us information of where is located some the owner of registry, among other uses.

**Describe the solution you'd like**
As i imagine the solution is...
On installing time:
*  Add GeoIP databases as a plugin 
*  On the first setup check if GeoIP is added to activate this feature
*  Provide a standard connect geojson worldwide (that can be changed to a zone-precise geojson)
On configuration time:
*  Just add a check to inform that geoip database is currently added to be used on admin site-> maps 
*  When a new map is added, check compatibility adding and ip and show if the related zone y highlighted 
*  To activate this behaviour we need to define that a field is IP 
On query time:
*  Just use IP and geojson to describe information on map, just like we test before. 
*  Enjoy located analytics 

**Describe alternatives you've considered**
I suppose that if this can be done like that, we can create another table using ip as FK and adding location information but this solution has many problems:

*  Lack of precision:  We can not update all register as ease as change the geoIP database. 
*  Redundant information: This information is provided anyway  via geoIP and just copied into our database.
*  Specific development:  In all the related projects we just need to create this behaviour making it possible new ways of failure

**How important is this feature to you?**
I understand that this can be see as a low prio, low added value issue, but for some databases it could bring analytics to a new level of control. 
 
**Additional context**
If all the geodata integration is impossible, added an IP field on field selector could be nice, just to define it

**Comment by flamber** [comment] 2020-09-01 09:23
Duplicate of #3159

**Closed by flamber** 2020-09-01 09:23 UTC
Labels: .Needs Triage, Type:New Feature
