### ISSUE TITLE
Cannot comment out variable in SQL query

### ISSUE THREAD

**Issue by carstenkadmos** [metabase/metabase#27612] opened 2023-01-10 15:54 UTC
In a simple sql query that uses commented out variables referencing to an existing question, the table is still called.

```
select 
dt,
KPI as kpi,
NULL as category,
cumulated,
Count as measure
from
/* yo mama {{#some saved question}}*/
{{#some saved question}}
```

*My diagnostic info*
```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "ANSI_X3.4-1968",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8-post-Debian-1deb10u1",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8-post-Debian-1deb10u1",
    "os.name": "Linux",
    "os.version": "5.4.202+",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-12-03",
      "tag": "v0.45.0",
      "branch": "release-x.45.x",
      "hash": "4e41d76"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by paoliniluis** [comment] 2023-01-10 15:57
You're seeing a duplicate of https://github.com/metabase/metabase/issues/7742

**Closed by paoliniluis** 2023-01-10 15:57 UTC
Labels: Type:Bug, .Needs Triage
