### ISSUE TITLE
Cannot add new columns after hiding some or changing order of existing columns

### ISSUE THREAD

**Issue by nbrustein** [metabase/metabase#15393] opened 2021-03-30 11:06 UTC
**Describe the bug**
After hiding some columns using the "Visible Columns" list under settings, any new columns added to the query will not be shown

**To Reproduce**
1. Create a native query with the following contents:

```
select 
    1 as visible 
    , 2 as hidden
```

2. Click `Settings`.  Press the `X` next to the column named `hidden` to hide it.
3. Update the query by adding a third column, so the new contents are:

```
select 
    1 as visible 
    , 2 as hidden
    , 3 as added
```

4. See that the new column is not displayed in the results and does not show up in the list of columns under settings.

**Expected behavior**
I would expect the new column to be visible by default, and I would expect to see it in the list of columns under settings so I could configure it.

**Screenshots**
![Screen Shot 2021-03-30 at 7 03 33 AM](https://user-images.githubusercontent.com/82556/112979148-3215b400-9126-11eb-84f5-a88a62ced65b.png)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "4.14.209-160.339.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-03-17",
      "tag": "v0.38.2",
      "branch": "release-x.38.x",
      "hash": "91f0ed6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
I can work around it by replacing the query, but that's difficult when other people have links or the query is already included in dashboards, etc.  I don't normally hide columns, so I think I will just totally avoid using that feature in the future in order to prevent getting into this situation.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2021-03-30 12:15
This is likely a duplicate of #7612, but leaving this open, since it's not possible to click "Reset to default" for "Visible columns" since version 0.38.0 because of PR #13968

**Closed** 2021-06-28 15:14 UTC
Labels: .Frontend, .Regression, .Reproduced, Priority:P2, Type:Bug, Visualization/Chart Settings
