### ISSUE TITLE
(conn=58) Table 'metabase.permissions_group_membership' doesn't exist

### ISSUE THREAD

**Issue by 13242934754** [metabase/metabase#29586] opened 2023-03-28 03:50 UTC
**Describe the bug**

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.15.0-58-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.41"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-02-19",
      "tag": "v0.45.3",
      "branch": "release-x.45.x",
      "hash": "070f57b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by 13242934754** [comment] 2023-03-28 03:56
metabase在docker容器环境下，第一次连接mysql数据库，会注入示例数据表，我删除了这些示例数据表后，提示了这个错误

**Comment by noahmoss** [comment] 2023-08-01 13:31
Hi @13242934754, I suspect that you connected Metabase to MySQL as the [application database](https://www.metabase.com/docs/latest/installation-and-operation/configuring-application-database) rather than as an analytics database. This would result in a number of tables being created in your MySQL instance that are required for Metabase to operate, including `permissions_group_membership`.

You can fix this by using a separate, empty database as the application database for Metabase. Closing this issue since it's expected behavior and not a bug.

**Closed by noahmoss** 2023-08-01 13:31 UTC
Labels: .Needs Triage
