### ISSUE TITLE
Bug with csv/xlsx exports from question results - not all rows exported!

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#6661] opened 2018-01-08 11:43 UTC
csv/xls files exported from Metabase questions do not include all rows as returned in query results. 
For example, a question has c. 80k rows in results and the export keeps showing only 20588 in various exports tried. 
Another question with 45k rows returned shows consistently shows only 17500 rows in exported files.
There has been no error message when starting the export. 

This is somewhat worrying, and we would really like to be able to rely on the exports of questions results!

Thanks for having a look into this!

Your browser and the version: Chrome Version 63.0.3239.108 (64-Bit)
Your operating system: Windows 10
Your databases: BigQuery
Metabase version: v0.27.1
Metabase hosting environment: Heroku

**Comment by salsakran** [comment] 2018-02-02 00:48
Are there any errors in the logs? Does this always occur or is it only with specific tables?

**Comment by flamber** [comment] 2019-03-13 03:31
Related to #6960 - possibly duplicate.

**Comment by jlisyc** [comment] 2019-04-01 15:10
### Bug. Dashboard EMBEDDED. DOWNLOAD XLS/CSV with more than 10000 rows, Shows only 10000 rows.
Only 2000 if there is RawData (not view agrupation like a count)

- Your browser and the version: (Firefox 60.0.1,)
- Your operating system: (ubuntu 16.04)
- Your databases: (mysql, h2)
- Metabase version: (0.31.2)
- Metabase hosting environment: (Linux/Ubuntu)
- Metabase internal database: (Postgres)

## Steps to reproduce
1. H2 Exampe. ORDERS
![image](https://user-images.githubusercontent.com/33416503/55338241-90105200-54a0-11e9-9906-e4e72d6673da.png)

2. Create dashboard based in that question and Embedd it.
3. Try to download . You can see it shows only 10000 (should be more than 18000.


-------------------
Thanks for Metabase project!
-------

**Comment by flamber** [comment] 2020-04-28 09:05
Closing in favor of #6960, since that issue has more activity and higher priority already.

**Closed by flamber** 2020-04-28 09:05 UTC
Labels: .Correctness, Priority:P2, Type:Bug
