### ISSUE TITLE
ISO8601 date

### ISSUE THREAD

**Issue by pegxit** [metabase/metabase#44945] opened 2024-06-29 07:42 UTC
**Describe the bug**
Please add the ISO8601 data format as an option-> YYYY-MM-DD HH:mm:ss

**Logs**
n/a

**To Reproduce**
n/a

**Expected behavior**
ISO8601 date format available 

**Screenshots**
n/a

**Severity**
42 countries already have accepted ISO8601 as national standards, these include United States; United Kingdom, Switzerland, Sweden, Russia, Norway, Netherlands, Japan, Germany, France, China, Canada, ....

**Additional context**
Date just read more "normal" for users accustomed to it in a specific format.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.14.0-427.22.1.el9_4.x86_64",
    "user.language": "en",
    "user.timezone": "Africa/Johannesburg"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.11.8-MariaDB-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-12",
      "tag": "v0.50.2",
      "hash": "1a2c2da"
    },
    "settings": {
      "report-timezone": "Africa/Johannesburg"
    }
  }
}
```

**Comment by NicolasPA** [comment] 2024-07-09 07:38
Duplicate of https://github.com/metabase/metabase/issues/9539

**Comment by mngr** [comment] 2024-08-22 11:22
Duplicate of https://github.com/metabase/metabase/issues/9539

**Closed by mngr** 2024-08-22 11:22 UTC
Labels: Type:New Feature, Customization/i18n, Customization/Formatting, Administration/, .Needs Triage, .Team/AdminWebapp
