### ISSUE TITLE
Description on items in collection gets cropped

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#24466] opened 2022-08-01 13:09 UTC
**Describe the bug**
The description of the item gets cut when hovering over the icon on a description

**To Reproduce**
1) create a question or dashboard, but on the description, use a very long word. Save it
2) see how the text looks on the collection

**Expected behavior**
Have text correctly rendered

**Screenshots**
![image](https://user-images.githubusercontent.com/1711649/182154940-55f7752d-b401-47bb-979f-88a233ad2938.png)
![image](https://user-images.githubusercontent.com/1711649/182154973-a8f4eb5f-24aa-47a6-8c65-cddc99ec57ce.png)
![image](https://user-images.githubusercontent.com/1711649/182154993-3d5acd87-ff8d-42e7-995f-630303b6544e.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop 22.04
- Your databases: Postgres 14
- Metabase version: 1.44.0-RC2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by flamber** [comment] 2022-08-01 13:35
Duplicate of #12535

**Closed by flamber** 2022-08-01 13:35 UTC
Labels: Type:Bug, Priority:P3, Organization/Collections, .Frontend

**Comment by shaunlebron** [comment] 2023-06-06 21:20
Specifically a duplicate of https://github.com/metabase/metabase/issues/21229
