### ISSUE TITLE
Filtering: Not Between,OR

### ISSUE THREAD

**Issue by PauloHFM** [metabase/metabase#11490] opened 2019-12-10 21:14 UTC
We need to filter in Custom and Simple Questions, for example, prices that is less than 10 OR greater than 20.

The ultimate solution would be an OR statement in Filtering!
As on https://github.com/metabase/metabase/issues/5870 
and 
https://github.com/metabase/metabase/issues/3217

But my idea for a quick win is another solution for numbers:
Doing a "Not Between" filter !

Sorry if it's already an idea!

Thanks!

**Comment by flamber** [comment] 2019-12-10 21:45
Hi @PauloHFM 
Sounds a lot like the proposal in #11397, which asked for a "not" checkbox, so everything could be negative of filter option. Was closed in favor of #7402, since it was kinda specific to "not starts with".

**Comment by EBoisseauSierra** [comment] 2019-12-11 12:35
@flamber I think this issue could be generalized as:
* Creating an `OR` option, when adding multiple filters (because, as far as I can tell, adding multiple filters causes Metabase to `AND` them — i.e. the records must match both filters selected). Was solved as explained in #5870 / #3217 but seems to have disappear in the new UI.
* Creating an `NOT` option: as you have said, this generic case was asked in #11397, and closed in favour of the initial (yet slightly more specific) #7402.

The `OR` would theoretically be superflous if one has `AND` and `NOT` — yet would be much nicer to have and easier to use!

**Comment by flamber** [comment] 2019-12-11 14:12
@EBoisseauSierra #5870 was closed as a duplicate of #3217, which is still open, so nothing has disappeared, since that functionality has never existed.
Totally agree, that you can create much more advanced queries if `OR`, but the challenge has been how to visualize it without making the UI too advanced (as discussed in the two issues).

**Comment by mazameli** [comment] 2019-12-13 23:21
As has been discussed above, this issue seems effectively like a duplicate of #3217 and #7402.

**Closed by mazameli** 2019-12-13 23:21 UTC
Labels: .Duplicate
