### ISSUE TITLE
Add Monthly Alert Option

### ISSUE THREAD

**Issue by officiallymarky** [metabase/metabase#38174] opened 2024-01-26 09:15 UTC
**Is your feature request related to a problem? Please describe.**
There are hourly, daily, weekly options for alerts, monthly would be very handy and seems like one of the most logical options to have.

**Describe the solution you'd like**
Monthly option for alerts

**Describe alternatives you've considered**
None

**How important is this feature to you?**
Would save me some time on a regular basis.

**Additional context**
n/a

**Comment by abhishek-superk** [comment] 2024-01-29 18:22
Having a cron scheduler would probably be the best. It has been asked many times before. Oldest one probably being #3846 & #6648

**Comment by paoliniluis** [comment] 2024-07-19 22:40
duplicate of https://github.com/metabase/metabase/issues/13189

**Closed by paoliniluis** 2024-07-19 22:40 UTC
Labels: Type:New Feature, .Needs Triage
