### ISSUE TITLE
Field filter dropdown is not showing all of the expected options

### ISSUE THREAD

**Issue by carolineloop** [metabase/metabase#42841] opened 2024-05-17 16:45 UTC
### Describe the bug

I have a field filter linked to all of the charts on my [dashboard](https://loop.metabaseapp.com/dashboard/234-parcel-rate-errors?tenant_qid=qid%3A%3Atenant%3Ac468614d-6ad3-4312-bb54-61073e526114&invoiced_after=&invoiced_before=&carrier=&invoice_numbers=&tracking_number=&charge_type=) and there should be 3 options showing up in the dropdown, but only 2 are showing up. I triple checked that the data contains all 3 values, and for whatever reason the third will not show up. The only way I can get it to show up is if I make all 3 the default value (see screenshot). But as soon as I unselect the missing value "UPS," it disappears from the dropdown.
<img width="1492" alt="Screenshot 2024-05-17 at 11 38 06 AM" src="https://github.com/metabase/metabase/assets/147414454/a2f1843f-d93e-46b5-bc89-f1e1110ae890">
<img width="338" alt="Screenshot 2024-05-17 at 11 38 26 AM" src="https://github.com/metabase/metabase/assets/147414454/95d10470-9d60-4e5f-9d51-0a45e0ef8273">
<img width="337" alt="Screenshot 2024-05-17 at 11 38 43 AM" src="https://github.com/metabase/metabase/assets/147414454/574a504a-14b9-4a36-b6dc-74ad2b9d8566">
I'm confident that "UPS" data is in the charts on the dashboard, because when I set it to ONLY use UPS using the hack I figured out, the dashboard is populated with data (see screenshot).
<img width="1489" alt="Screenshot 2024-05-17 at 11 40 23 AM" src="https://github.com/metabase/metabase/assets/147414454/53db78b3-549b-47df-860d-67100a17a703">

### To Reproduce

1. Go to this [dashboard](https://loop.metabaseapp.com/dashboard/234-parcel-rate-errors?tenant_qid=qid%3A%3Atenant%3Ac468614d-6ad3-4312-bb54-61073e526114&invoiced_after=&invoiced_before=&carrier=DHL&carrier=FedEx&invoice_numbers=&tracking_number=&charge_type=)
2. Click on the Carrier filter
3. See error - the options should be "UPS" "FedEx" and "DHL," but only "FedEx" and "DHL" are showing up. If you remove the filter all together, you will see that UPS data does indeed exist in the reports that this filter is attached to.

### Expected behavior

This dropdown filter should be showing 3 options, not 2: "UPS" "FedEx" and "DHL"

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.10.215-203.850.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-05-13",
      "tag": "v1.49.10",
      "hash": "9e8fc83"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Annoying

### Additional context

[metabase-bug.webm](https://github.com/metabase/metabase/assets/147414454/956fe059-bb27-4fbc-95ac-ed48afc1dc9e)

**Comment by paoliniluis** [comment] 2024-05-17 17:41
Are the filters linked_

**Comment by carolineloop** [comment] 2024-05-17 17:59
Yes the filter is linked to all of the other field filters on the dashboard. However, the one that removes "UPS" is the tenant_qid filter. Except when I run a "distinct" query with the table that the field filter is derived from WITH the tenant_qid field filter applied, it returns all 3 expected values. So I think it must be bug that's causing only 2 to show up in the dropdown.

**Comment by ranquild** [comment] 2024-07-03 02:58
Reassigned to DashViz because it's Linked filters. My take - this is probably working as intended because linked filters do not take connected cards into account.

**Comment by paoliniluis** [comment] 2024-09-01 01:32
@carolineloop are you still hitting this? if so, please send us an email to help at metabase dot com

**Comment by carolineloop** [comment] 2024-09-03 04:17
I don't believe it's come up again, no - I will reach out at the email if
needed! Thanks!

**Closed** 2024-09-13 23:46 UTC
Labels: Type:Bug, Priority:P2, Querying/Parameters & Variables, .Backend, .Product Input Needed, .Team/Querying, .Team/DashViz
