### ISSUE TITLE
Model metadata may not be editable

### ISSUE THREAD

**Issue by haboshi** [metabase/metabase#20518] opened 2022-02-15 10:34 UTC
**Describe the bug**
After creating the model, I cannot edit the metadata or SQL by clicking the title part.

Only the screen reloads and the search results are redisplayed.

The occurrence status differs depending on the model, but the model that cannot be edited is in the same state even if the browser or OS is changed.

I've attached a browser console error.

**Logs**
```
react-dom.production.min.js:49 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at react-dom.production.min.js:49
    at it (react-dom.production.min.js:50)
    at Object.t.findDOMNode (react-dom.production.min.js:289)
    at s.value (ExplicitSize.jsx:31)
    at ExplicitSize.jsx:101
    at c (throttle.js:32)
```

**To Reproduce**
1. Go to 'Model pages'
2. Click on 'title'
3. See error

**Expected behavior**
Being able to edit metadata or SQL

**Screenshots**

**Information about your Metabase Installation:**

docker composer

- Your browser and the version: Chrome 52.1, Firefox 48.0, Safari 11.1
- Your operating system: macOS monterey
- Your databases: PostgreSQL , Redshift
- Metabase version: 0.42.0
- Metabase hosting environment: Docker
- Metabase internal database: PostgreSQL

**Severity**
I can't change the model I created over time
Even if you create a new one, for some reason you will not be able to edit it again.

![metabase error](https://user-images.githubusercontent.com/4361863/154044531-92853b3a-af93-4cab-b183-b8c336da2f26.png)

**Comment by kulyk** [comment] 2022-02-15 10:37
Duplicate of #20414 that will be fixed in the next patch release (x.42.1)

**Comment by kulyk** [comment] 2022-02-15 10:38
@haboshi, as a temporary workaround, you can open the model editor using the URL like `/model/:id/metadata` and `/model/:id/query`

**Closed by kulyk** 2022-02-15 10:37 UTC
Labels: Type:Bug, .Needs Triage

**Comment by haboshi** [comment] 2022-02-15 11:53
Thank you very much.
I was able to edit it.
