### ISSUE TITLE
Support PrestoDB Multi Catalogues

### ISSUE THREAD

**Issue by Abdillah** [metabase/metabase#22522] opened 2022-05-09 03:56 UTC
**Is your feature request related to a problem? Please describe.**
I'm working on a company rely on Metabase for data analytics. We wanted to create a Unified database that can query across database. So, we create PrestoDB instance that has multiple connections. Although PrestoDB support multiple database (multiple "catalogues"), Metabase doesn't. When setting up Metabase connector to Presto, we're obliged to enter catalogue name, so multiple PrestoDB connectors is not accessible under one query.

**Describe the solution you'd like**
PrestoDB query already support multi catalogues, so why not make the "Catalogue" field optional?
This will likely depends on the JDBC library provided by PrestoDB.

**Describe alternatives you've considered**
Supporting query across multiple Metabase "Database" also will solve our problem, hope we'll be there in the near future. 

**How important is this feature to you?**
It will likely expand our capability in processing multiple data source. But, before the feature is implemented, we will try some ELT pipeline, which in our experience is costly or hard to setup (if building ourselves).

**Additional context**
- SQLAlchemy support multi data sources (or catalogues) query.

**Comment by flamber** [comment] 2022-05-09 08:12
Duplicate of #22237

**Closed by flamber** 2022-05-09 08:12 UTC
Labels: Type:New Feature, .Needs Triage
