### ISSUE TITLE
Cannot save question when results are empty

### ISSUE THREAD

**Issue by markberger** [metabase/metabase#11256] opened 2019-11-01 23:44 UTC
**Describe the bug**
I am not able to save or replace a question when I query against `my_dataset.__TABLES__` and the results are empty.

**To Reproduce**
1. Create a new question with the BigQuery driver
2. Use the following query:

```
#legacySQL
select * from my_dataset.__TABLES__ where row_count = -1
```
3. Try to save the question. This returns:

`value may be nil, or if non-nil, value must be an array of valid results column metadata maps.`

**Expected behavior**
Should be able to save or replace the question.

**Information about your Metabase Installation:**

Running v0.33.4 jar from the releases page with a postgres db

**Severity**
Annoying

**Additional context**
May be related to #10839 or #9286 ?

Thank you for all your work on Metabase! 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by dgies** [comment] 2020-02-20 22:33
This is blocking me from creating Pulses which only fire when the Question has results.  This makes Pulses effectively useless for data quality monitoring since it forces you to create Questions that have results even when there is no problem.

**Comment by markberger** [comment] 2020-02-27 18:52
@dgies I've found that I can save the question if I do not execute the query beforehand. That may be a workaround for you

**Comment by oopsjoppe** [comment] 2020-03-16 22:57
> @dgies I've found that I can save the question if I do not execute the query beforehand. That may be a workaround for you

wow - thanks!

**Comment by knzshirox** [comment] 2020-04-02 04:34
I am having the same problem with version v0.35.0 and there are records in the MongoDB query. True that I can save the question if I don't run the query beforehand, but it does not work if I want a visualization.

**Comment by TrineFN** [comment] 2020-04-09 07:38
We have the same problem on Metabase v.0.35.1 with a Redshift db. 

When saving a question with no results we get the error:
```
[34d0a779-8175-4cfb-85ed-6d8cf806318e] 2020-04-09T09:28:53+02:00 DEBUG metabase.middleware.log PUT /api/card/116 400 1.2 ms (0 DB calls)
{:errors {:result_metadata "value may be nil, or if non-nil, value must be an array of valid results column metadata maps."}}
```

The workaround that @markberger mentioned works for us.

**Comment by ShocksPegsLucky** [comment] 2020-04-15 22:42
> I am having the same problem with version v0.35.0 and there are records in the MongoDB query. True that I can save the question if I don't run the query beforehand, but it does not work if I want a visualization.

Same thing with v0.35.2 except it now says an error occurs when you try to save the question (an improvement). This bug practically makes native queries unusable with MongoDB as you can only keep the default visualization settings (not to mention you have to create a new question each time you want to update your query).

**Comment by ShocksPegsLucky** [comment] 2020-04-15 22:54
Looks like this might now be accounted for here:

**Comment by dgies** [comment] 2020-04-16 18:21
> Looks like this might now be accounted for here:
> #12329

I don't see the connection, am I missing something?  This bug affects empty questions and does not require MongoDB to reproduce.  That issue affects questions with results being used with MongoDB.

**Comment by johnmastro** [comment] 2020-04-17 16:03
We're also getting this error when saving any question that returns an empty result set, regardless of the source database type (we're seeing it with both Postgres and Snowflake)

**Comment by marcioibm** [comment] 2020-04-17 16:23
As a workaround i'm copying the POST/PUT request in chrome, importing in Postman and before sending setting the result_metadata to null... It works for me!

**Comment by aogilvie** [comment] 2020-04-20 02:57
Same as above. I am using Docker, Metabase v0.35.2, Mongo 4.x db.

Any native query cannot be saved and I can re-create this bug each time on localhost running metabase DB and metabase containers.

```
[04edc459-dd4c-47c8-9436-639930868ceb] 2020-04-20T11:47:50+09:00 DEBUG metabase.middleware.log POST /api/card 400 2.1 ms (0 DB calls)
{:errors {:result_metadata "value may be nil, or if non-nil, value must be an array of valid results column metadata maps."}}
```

Workaround written by `markberger` allows me to save the question native query.

**Comment by paulrosenzweig** [comment] 2020-04-30 12:00
Fixed by #12427

**Closed by paulrosenzweig** 2020-04-30 12:00 UTC
Labels: Priority:P1, Querying/, Type:Bug

**Comment by scream314** [comment] 2020-05-05 09:32
**A possible workaround:**
If you manage to get anything in the results pane (for example using a different query), then change the query to the correct one, you can save the question as long as you do not run it.
If you need to edit a question with no results, change it first to a different query (with results), run it, change it back, and save without running.

**Comment by jankatins** [comment] 2020-05-06 12:27
This bug is really annoying, is there any hope that we get a release with this in soonish?

**Comment by flamber** [comment] 2020-05-06 12:31
@jankatins While I hate giving hard dates, I would expect 0.35.4 next week. There's a couple of other issues that we're trying to get into that release.
