### ISSUE TITLE
As a admin user, when going to settings, i am getting a: "We're a little lost..." page

### ISSUE THREAD

**Issue by mvandewouw** [metabase/metabase#10986] opened 2019-09-25 11:10 UTC
**Describe the bug**
As a admin user, when going to settings, i am getting a: "We're a little lost..." page

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.4+11",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.4",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.4+11",
    "os.name": "Linux",
    "os.version": "3.10.0-1062.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Europe/Amsterdam"
  },
  "metabase-info": {
    "databases": [
      "oracle",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-09-20",
      "tag": "v0.33.3",
      "branch": "release-0.33.x",
      "hash": "86d32bf"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**
This metabase instance was upgraded from H2 to postgres (couple of versions back). WIth upgrading (from postgres->postgres) this bug appeared

**Comment by amoskaliov** [comment] 2019-09-25 14:09
So after upgrading to 0.33.3 I had two problems:
* this one
* LDAP users can't log in. In logs I had the following error:
    ```
   ERROR api.session :: Problem connecting to LDAP server, will fall back to local authentication
   LDAPException(resultCode=34 (invalid DN syntax), errorMessage='Unable to parse string 'DN: cn=data-analysts,ou=group,dc=***,dc=***' as a DN because it does not have an equal sign after RDN attribute 'DN:'.', ldapSDKVersion=4.0.4, revision=27051)
   ```
   (asterisks added)

I connected to Postgres DB and edited `ldap-group-mappings` field in public.setting (removed `DN: `) and also `settings-last-updated` field (set to current time). After this fix and restart both problems disappeared. Can't say exactly how it's all connected, but I hope this will help you.

**Comment by camsaul** [comment] 2019-09-25 18:50
@amoskaliov I opened #10988 as a separate issue to track the problems you're having with LDAP.

**Comment by mvandewouw** [comment] 2019-09-26 12:55
hi amoskaliov,
thanks for the reply
All data in settings is encrypted. I did not see any LDAP error in logging btw
Are you suggesting to empty this field, set last updated to now and restart environment?

**Comment by amoskaliov** [comment] 2019-09-26 13:02
If you don't have any problems with LDAP, maybe you shouldn't touch this field. You can try at first just to update `settings-last-updated` field,

**Comment by salsakran** [comment] 2019-10-01 01:51
this is pretty obnoxious, and in general, the settings app shouldn't refuse to render if it sees bad data, but not sure it's a P1 unless multiple people are hitting this.

**Comment by flamber** [comment] 2020-06-03 20:16
On one of my test setups, I could reproduce this consistently on several versions of 0.33 and 0.34.
But I'm switching between versions many times each hour on the same application database.
Since 0.35, I'm not seeing this problem anymore (unless I downgrade to version before), so closing.
Please comment with details if you're still experiencing this problem.

**Closed by flamber** 2020-06-03 20:16 UTC
Labels: .Frontend, Administration/, Priority:P2, Type:Bug
