### ISSUE TITLE
Custom Column leads to error: Input to expression-with-name does not match schema

### ISSUE THREAD

**Issue by fferguso11** [metabase/metabase#12357] opened 2020-04-20 17:26 UTC
**Describe the bug**
Upon adding a simple addition of two columns as a custom column to the queried table, receive an error: 
`Input to expression-with-name does not match schema: [0;33m [(named (not (map? nil)) arg0) nil] [0m`

Adding the custom column creates a subquery, and the subquery does not have an alias, so I think the SQL execution is getting crossed with the parent query and subquery references not being unique 

**Logs**
![image](https://user-images.githubusercontent.com/44494546/79780836-72748b80-8334-11ea-862d-de8abcad1d28.png)

**To Reproduce**
1. Go to metabase.com
2. Click on Ask a question
3. Click on Simple Query
4. Go to table of choice
5. In editor, enter custom column (e.g. column x + column y) 
6. Press visualize
7. Error should appear
5. See error

**Expected behavior**
Expect to see the original table complete with the custom table

**Screenshots**
![image](https://user-images.githubusercontent.com/44494546/79875778-06e8f780-83e2-11ea-801d-f880f2a3ff0b.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Chrome Version 79.0.3945.88 (Official Build) (64-bit)
- Mac OS Mojave 10.14.6 (18G103)
- Database is Postgres
- Metabase You're on version v0.35.2

**Severity**
This can be circumvented by adapting the underlying data, but removes a lot of the functionality for getting away without using native queries/spending lots of time adding any number of columns to datasets just in case you need them

**Comment by flamber** [comment] 2020-04-20 17:44
Hi @fferguso11 
Are you querying Postgres? By the way, latest release is 0.35.2
There's another issue #11519 with the same error, which I think this might be a duplicate of. If you also think this is a duplicate of the other issue, then please close this and upvote the other issue :+1:

**Comment by fferguso11** [comment] 2020-04-21 14:08
Hello - yes I'll update, have since moved to the most recent Metabase version (0.35.2) but this hasn't solved the error - now gives a different error message to #11519

**Comment by flamber** [comment] 2020-04-21 16:06
@fferguso11 
1. Are you querying Postgres?
2. Okay, if it is giving a different error on 0.35.2, then please post the error. Admin > Troubleshooting > Logs

**Comment by flamber** [comment] 2020-05-15 07:39
Closing this, since it seems to be a duplicate of #11519, which is likely fixed in upcoming 0.36.0

**Closed by flamber** 2020-05-15 07:39 UTC
Labels: .Need More Info, Type:Bug
