### ISSUE TITLE
Suggestions unexpectedly change in the SQL query editor

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#34596] opened 2023-10-12 11:26 UTC
### Describe the bug

:warning: In prod build (stats instance) it blinks twice and comes back to the initial list of suggestions on the 2nd blink.

`master`, locally, dev build, **blinks once**:
https://github.com/metabase/metabase/assets/6830683/d902fad7-d4aa-4cd3-9fdb-c25d87a97e66

stats instance, prod build, **blinks twice**:
https://github.com/metabase/metabase/assets/6830683/ff1c53d2-82a6-425f-93b0-341fdeb63805

### To Reproduce

1. Create new SQL question
2. Hit <kbd>p</kbd>

Suggestions are displayed and the list shortly changes to a different list.

### Expected behavior

Suggestions are displayed and don't change

### Information about your Metabase installation

`master` & stats instance

### Severity

P2

### Additional context

Found when reviewing #34534

**Comment by paoliniluis** [comment] 2023-10-12 11:31
Related to https://github.com/metabase/metabase/issues/34330

**Comment by oleggromov** [comment] 2024-01-23 16:42
Still reproducible on 926b04a1d5377798b0bbb98ef6b28ddac3210c89

**Comment by romeovs** [comment] 2024-03-06 13:41
While things are a bit better now https://github.com/metabase/metabase/issues/34330 has been merged, the issue still persists.


I've looked into how the completions work in Ace and this is why I think some of the flickers happen:
- insert `PE`
- there are a bunch of completions including `EXPECTED_INVOICE` since it matches the `PE`
- insert `O` (editor text is now: `PEO`)
- ACE will still display `EXPECTED_INVOICE` because there is both `PE` and `O` in it
- The async autocompletions come in and don't contain `EXPECTED_INVOICE`
- `EXPECTED_INVOICE` dissappears because it's no longer in the autocompletions

It is not possible with Ace to clear or remove old completion results, so I don't think much can be done here (other than switching to a different editor).

**Closed** 2024-10-31 09:48 UTC
Labels: Type:Bug, Priority:P2, Querying/Native, Difficulty:Medium, .Frontend, .Team/Querying

**Comment by romeovs** [comment] 2024-11-01 02:56
Reopening because https://github.com/metabase/metabase/pull/45136 was reverted in https://github.com/metabase/metabase/pull/49417 due to flakes.
