### ISSUE TITLE
Corrupt H2 db

### ISSUE THREAD

**Issue by joshhopkins** [metabase/metabase#9457] opened 2019-02-20 12:30 UTC
- Your operating system: MacOS 10.14.3 (18D109)
- Your databases: Postgres
- Metabase version: 0.31.2.1
- Metabase hosting environment: Mac app
- Metabase internal database: H2

Received this message when booting up today:

```shell
Messages:
INFO metabase.core :: Starting Metabase in STANDALONE mode
INFO metabase.core :: Launching Embedded Jetty Webserver with config: 
{:port 13171}
INFO metabase.core :: Starting Metabase version v0.31.2 (89c37eb release-0.31.2) ...
INFO metabase.core :: System timezone is 'Europe/Zurich' ...
WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collection, being replaced by: #'monger.collection/any?
INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
INFO metabase.db :: Verifying h2 Database Connection ...
ERROR metabase.driver :: Failed to connect to database: org.h2.jdbc.JdbcSQLException: Row not found when trying to delete from index """"".I63: ( /* key:1173 */ X'de02dd285a04b64bd1d6b733d3d229beea2b2a4741f511ffe2b2ee56ca1017ff', 105, SPACE(709 /* table: 61 id: 36901 */))" [90112-197]
ERROR metabase.core :: Metabase Initialization FAILED
java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
at metabase.db$verify_db_connection.invokeStatic(db.clj:402)
at metabase.db$verify_db_connection.invoke(db.clj:395)
at metabase.db$verify_db_connection.invokeStatic(db.clj:398)
at metabase.db$verify_db_connection.invoke(db.clj:395)
at metabase.db$setup_db_BANG_.invokeStatic(db.clj:464)
at metabase.db$setup_db_BANG_.doInvoke(db.clj:458)
at clojure.lang.RestFn.invoke(RestFn.java:421)
at metabase.core$init_BANG_.invokeStatic(core.clj:162)
at metabase.core$init_BANG_.invoke(core.clj:139)
at metabase.core$start_normally.invokeStatic(core.clj:246)
at metabase.core$start_normally.invoke(core.clj:240)
at metabase.core$_main.invokeStatic(core.clj:266)
at metabase.core$_main.doInvoke(core.clj:261)
at clojure.lang.RestFn.invoke(RestFn.java:397)
at clojure.lang.AFn.applyToHelper(AFn.java:152)
at clojure.lang.RestFn.applyTo(RestFn.java:132)
at metabase.core.main(Unknown Source)
INFO metabase.core :: Metabase Shutting Down ...
INFO metabase.core :: Metabase Shutdown COMPLETE

```

Appears that H2 is corrupt. I've followed the recovery process detailed [here](https://github.com/metabase/metabase/blob/97f15d4e487957217623d8591e13872cfb1bef7f/docs/troubleshooting-guide/application-database.md), but receive the following error:

`Error: Could not find or load main class org.h2.tools.RunScript`

**Comment by salsakran** [comment] 2019-04-10 04:45
Sounds like a classpath issue.

what version of java are you on?

**Comment by joshhopkins** [comment] 2019-04-10 16:27
Java 8 Update 191

**Comment by flamber** [comment] 2020-05-24 18:13
Closing, since it's difficult to reproduce without the commands executed.
Looks like it wasn't including `metabase.jar` correctly, which contains the tool:
https://stackoverflow.com/questions/56792957/error-could-not-find-or-load-main-class-org-h2-tools-runscript

**Closed by flamber** 2020-05-24 18:13 UTC
Labels: Operation/H2
