### ISSUE TITLE
Changing variable type to 'Field Filter' causes page to crash

### ISSUE THREAD

**Issue by pranayat** [metabase/metabase#30034] opened 2023-04-12 14:28 UTC
**Describe the bug**
Changing variable type to 'filter field' causes page to crash with the error - "Something's gone wrong
We've run into an error. You can try refreshing the page, or just go back."
A frontend error is seen in the browser console as well, nothing observed in network logs.

**To Reproduce**
Create a native MongoDB query as below
```
[
  {
    "$group": {
      "_id": {
        "_id": "$_id"
      }
    }
  },
  {
    "$project": {
      "_id": "$_id._id"
    }
  },
  {
    "$lookup": {
      "from": "restaurants",
      "let": {
        "let__id_3036": "$_id"
      },
      "pipeline": [
        {
          "$match": {
            "$expr": {
              "$eq": [
                "$$let__id_3036",
                "$_id"
              ]
            }
          }
        }
      ],
      "as": "join_alias_Restaurants"
    }
  },
  {
    "$unwind": {
      "path": "$join_alias_Restaurants",
      "preserveNullAndEmptyArrays": true
    }
  },
  {
    "$project": {
      "_id": "$_id",
      "Restaurants___id": "$join_alias_Restaurants._id",
      "Restaurants__location": "$join_alias_Restaurants.location",
      "Restaurants__instagramLink": "$join_alias_Restaurants.instagramLink",
      "Restaurants__lieferandoLink": "$join_alias_Restaurants.lieferandoLink",
      "Restaurants__phoneNumber": "$join_alias_Restaurants.phoneNumber",
      "Restaurants__address": "$join_alias_Restaurants.address",
      "Restaurants__facebookLink": "$join_alias_Restaurants.facebookLink",
      "Restaurants__town": "$join_alias_Restaurants.town",
      "Restaurants__foodToGo": "$join_alias_Restaurants.foodToGo",
      "Restaurants__foodToDeliver": "$join_alias_Restaurants.foodToDeliver",
      "Restaurants__currentInformation": "$join_alias_Restaurants.currentInformation",
      "Restaurants__websiteLink": "$join_alias_Restaurants.websiteLink",
      "Restaurants__lockdownClosed": "$join_alias_Restaurants.lockdownClosed",
      "Restaurants__plz": "$join_alias_Restaurants.plz",
      "Restaurants__hasGarden": "$join_alias_Restaurants.hasGarden",
      "Restaurants__responsible": "$join_alias_Restaurants.responsible",
      "Restaurants__openingHours": "$join_alias_Restaurants.openingHours",
      "Restaurants__deliverConditions": "$join_alias_Restaurants.deliverConditions",
      "Restaurants__subTown": "$join_alias_Restaurants.subTown",
      "Restaurants__isPublished": "$join_alias_Restaurants.isPublished",
      "Restaurants__restaurantType": "$join_alias_Restaurants.restaurantType",
      "Restaurants__mailAddress": "$join_alias_Restaurants.mailAddress",
      "Restaurants__name": "$join_alias_Restaurants.name",
      "Restaurants__old_id": "$join_alias_Restaurants.old_id",
      "Restaurants____v": "$join_alias_Restaurants.__v",
      "Restaurants__updatedAt": "$join_alias_Restaurants.updatedAt",
      "Restaurants__old_tags": "$join_alias_Restaurants.old_tags",
      "Restaurants__tags": "$join_alias_Restaurants.tags",
      "Restaurants__swappedLoc": "$join_alias_Restaurants.swappedLoc",
      "Restaurants__media": "$join_alias_Restaurants.media",
      "Restaurants__priority": "$join_alias_Restaurants.priority",
      "Restaurants__createdAt": "$join_alias_Restaurants.createdAt",
      "Restaurants__tags_old": "$join_alias_Restaurants.tags_old",
      "Restaurants__imageMigrated": "$join_alias_Restaurants.imageMigrated",
      "Restaurants__mainMenuLinks": "$join_alias_Restaurants.mainMenuLinks",
      "Restaurants__openingHoursLinks": "$join_alias_Restaurants.openingHoursLinks",
      "Restaurants__mainMenuLinksTypes": "$join_alias_Restaurants.mainMenuLinksTypes",
      "Restaurants__individualPictureUploaded": "$join_alias_Restaurants.individualPictureUploaded",
      "Restaurants__logoUploaded": "$join_alias_Restaurants.logoUploaded",
      "Restaurants__individualStatement": "$join_alias_Restaurants.individualStatement",
      "Restaurants__takeawayConditions": "$join_alias_Restaurants.takeawayConditions",
      "Restaurants__lastValidatedAt": "$join_alias_Restaurants.lastValidatedAt"
    }
  },
  {
    "$lookup": {
      "from": "meals",
      "let": {
        "let_Restaurants___id_3037": "$Restaurants___id"
      },
      "pipeline": [
        {
          "$match": {
            "name": {
                "$regex": {{meal_name}},
                "$options": "i"
            }
          }
        },
        {
          "$group": {
            "_id": {
              "restaurantId": "$restaurantId"
            },
            "count": {
              "$sum": 1
            }
          }
        },
        {
          "$project": {
            "_id": false,
            "restaurantId": "$_id.restaurantId",
            "count": true
          }
        },
        {
          "$match": {
            "$expr": {
              "$eq": [
                "$$let_Restaurants___id_3037",
                "$restaurantId"
              ]
            }
          }
        }
      ],
      "as": "join_alias_Question 4"
    }
  },
  {
    "$unwind": {
      "path": "$join_alias_Question 4",
      "preserveNullAndEmptyArrays": false
    }
  },
  {
    "$project": {
      "Restaurants__name": "$Restaurants__name",
      "Restaurants__town": "$Restaurants__town",
      "Restaurants__subTown": "$Restaurants__subTown",
      "Question 4__count": "$join_alias_Question 4.count"
    }
  },
  {
     "$sort": {
        "Question 4__count": -1
      }
  },
  {
    "$limit": 1048575
  }
]
```
Then change the variable type from 'Text' to 'Field Filter'

**Screenshots/videos**

https://user-images.githubusercontent.com/6952713/231487935-4c9b800e-2ae7-479f-ae03-3e574080107d.mov

Error in console
![image](https://user-images.githubusercontent.com/6952713/231488777-fdfcb7c3-85a2-471a-91a4-c94f9d692d3c.png)

**Information about your Metabase Installation:**
v0.46.1
Browser - Google Chrome Version 112.0.5615.49 (Official Build) (arm64)

**Severity**
Unable to set a field filter and as a result unable to set a dashboard filter for this question.

**Comment by paoliniluis** [comment] 2023-04-12 14:37
duplicate of https://github.com/metabase/metabase/issues/29786

**Closed by paoliniluis** 2023-04-12 14:37 UTC
Labels: Type:Bug, .Needs Triage
