### ISSUE TITLE
locale language display problem

### ISSUE THREAD

**Issue by szsuyuji** [metabase/metabase#15804] opened 2021-04-25 07:56 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/1931764/115985449-79d11380-a5de-11eb-91e4-e63501a49e31.png)
![image](https://user-images.githubusercontent.com/1931764/115985518-c3b9f980-a5de-11eb-9fd9-9a6c1e9de51a.png)

**Comment by flamber** [comment] 2021-04-25 08:39
Duplicate of #15694

**Closed by flamber** 2021-04-25 08:39 UTC
Labels: .Needs Triage, Type:Bug
