### ISSUE TITLE
Unable to remove a series from a combined questions dashboard card

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#17394] opened 2021-08-10 14:40 UTC
**Describe the bug**
Unable to remove a series from a combined questions dashboard card.

These buttons do not work:
<img width="1111" alt="Screen Shot 2021-08-10 at 17 37 38" src="https://user-images.githubusercontent.com/14301985/128886973-0584e960-4159-4994-9b6c-51cf6af653d8.png">

**To Reproduce**
- Create two line charts and combine them in a single dashboard card
- Try to remove any series

Checked on the latest master

**Comment by flamber** [comment] 2021-08-10 14:44
Duplicate of #12794

**Closed by flamber** 2021-08-10 14:44 UTC
Labels: Type:Bug, .Needs Triage
