### ISSUE TITLE
I want to show column's alias

### ISSUE THREAD

**Issue by 8debug** [metabase/metabase#15276] opened 2021-03-22 08:10 UTC
![image](https://user-images.githubusercontent.com/3394927/111958950-ce3d2b00-8b28-11eb-99a4-e09276c31cea.png)

when I hover here, I want  `oper_date`  to display as 季度 and  want  `chinnel_id`  to display as 店铺.

help！how should I do

Thanks！

**Comment by flamber** [comment] 2021-03-22 08:40
Duplicate of #11395

**Closed by flamber** 2021-03-22 08:40 UTC
Labels: .Needs Triage, Type:Question
