### ISSUE TITLE
[Feature] Running the container with the specific user rather than root.

### ISSUE THREAD

**Issue by ADeeeee** [metabase/metabase#13549] opened 2020-10-21 10:56 UTC
**Is your feature request related to a problem? Please describe.**
Don't want my containers running with the root permission for avoiding some security concerns and warnings from the scaners.

**Describe the solution you'd like**
I have migrated some of the steps in **run_metabase.sh** to Dockerfile in order to create the account and assign the right permission of the files while building it, which works well for docker and kubernetes both by assigning a user in docker-compose.yml and securitycontext in deployment.yaml. e.g.:

```
# I'm using postgresql as my database in my lab, so didn't give the permission of metabase.db a test if $MB_DB_FILE is not in /app in default.

RUN MGID=${MGID:-2000}; MUID=${MUID:-2000} && addgroup -g $MGID -S metabase && \
    adduser -D -u $MUID -G metabase metabase && chown -R metabase:metabase /app
RUN db_file=${MB_DB_FILE:-/metabase.db} && if ls $db_file\.* > /dev/null 2>&1; then db_exists=true; else db_exists=false; fi && \
    if [[ -d "$db_file" ]]; then db_directory=true; else db_directory=false; fi && \
    new_db_dir=$(dirname $db_file)/$(basename $db_file) && \
    if [[ $db_exists = "true" && ! $db_directory = "true" ]]; then mkdir $new_db_dir; mv $db_file\.* $new_db_dir/; fi; \
    if [[ $db_exists = "false" && $db_directory = "false" ]]; then mkdir $new_db_dir; fi; \
    export MB_DB_FILE=$new_db_dir/$(basename $db_file) && chown metabase:metabase $new_db_dir $new_db_dir/* 2>/dev/null; \
    chmod o+r /app/metabase.jar
```

**Describe alternatives you've considered**
Please make it official or even not using run_metabase.sh for entrypoint anymore if it's possible. Why not doing this in the image, but running it every time during initializing? In current branch, the daemon is running by metabase, the container itselfs isn't.

**How important is this feature to you?**
Security, security, security! And it'd be nice if I don't need to build it every time when there's any upgrade events coming.

**Additional context**
I'd be appreciated to know the reason if it's not going to be changed in the future. It's an awesome project. Thank you all!

**Comment by flamber** [comment] 2020-10-21 11:08
Duplicate of #9861

**Closed by flamber** 2020-10-21 11:08 UTC
Labels: .Needs Triage, Type:New Feature
