### ISSUE TITLE
Technical and Usability Issues with Click Behavior Links

### ISSUE THREAD

**Issue by FWalder** [metabase/metabase#15835] opened 2021-04-27 19:22 UTC
**Describe the bug**
There are several issues with links created using the new Click Behavior interface.
- Links generated do not take the Metabase base path into account
  - If a system runs under https://metabase.acme.com/metabase/..., new questions will still open with the URL https://metabase.acme.com/question/... instead of https://metabase.acme.com/metabase/question
  - This occurs even if the base URL is properly configured in the Admin section

- Links opening in the same tab/window 
  - Forcing the link to open in the same window causes issues where Metabase is embedded. Firefox will not allow the link to open in the same tab, but gives an security error message and at least a button to open it in a new tab. Chrome doesn't even do that, but simply says the page cannot load. (See screen shots)
  - The way the links are constructed, a user cannot even middle-click a link to open it in a new tab even if they wanted

**Expected behavior**
- Links generated by the Click Behavior interface should build on the base URL defined in settings, not the out-of-the-box configuration.

- Even if you could argue that this it's intended behavior to stay in the same tab when clicking a link to give the drill down feel, in real life situations it's often the case that you see a list and want see details for a couple of items. Instead of following a bread crumb path, you want to fan out, while the source remains intact. Opening several tabs from the original list would make that possible. That means a middle click or the ability to right-click "Open in new Window" would already help a lot. Going back and forth between questions is often not feasible, because you will loose sorting and scroll position.

- A feasible solution would also be the option to specify whether links should be opened in new tabs or the existing tab. Letting the user choose is better, but this would at least be a start for dashboard designers.

**Screenshots**
Firefox:
![image](https://user-images.githubusercontent.com/52678499/116299529-1ab9fd00-a79e-11eb-9c48-35c670a55a6b.png)

Chrome:
![image](https://user-images.githubusercontent.com/52678499/116299679-489f4180-a79e-11eb-913c-4374228c4f6c.png)

**Information about your Metabase Installation:**
- Your browser and the version: Firefox 88.0, Chrome 90.0.4430.93
- Your operating system: Windows 10
- Your databases: Postgres
- Metabase version: 0.39.0.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Comment by flamber** [comment] 2021-04-27 19:38
Hi @FWalder 
While I agree with all of the listed problems, we have separate issues for each.
Duplicate of #13602 and #10370 and #5168

**Closed by flamber** 2021-04-27 19:38 UTC
Labels: .Needs Triage, Type:Bug

**Comment by FWalder** [comment] 2021-04-27 20:05
Thanks @flamber!

Some of those issues you linked are many years old. I'm not saying you won't get to them eventually, but I just want to reinforce that what previously might have been a nice-to-have, has now become a real usability issue with the new Click behavior.
