### ISSUE TITLE
Pivot table is not consistent and should allow for choice of vertical, horizontal series

### ISSUE THREAD

**Issue by doodlebro** [metabase/metabase#5478] opened 2017-07-14 18:20 UTC
Pivoting tables is a very useful feature (expecially for developing cohort charts). Unfortunately metabase automatically picks which series will be vertical, and which series will be horizontal (and does not allow the user to adjust in any way).

I am working on a set of cohort charts and expect all of them to render consistently so that whomever is reading them does not get confused. Here is an example of how it is inconsistent:

<img width="1199" alt="screen shot 2017-07-14 at 12 14 42 pm" src="https://user-images.githubusercontent.com/7634378/28224997-533df42c-688e-11e7-966f-dd2b56c5b428.png">

When the selected app is 'FCiOS', the cohort chart/pivot table is rendered in the way I would like all pivot tables to render... However when I select 'Overall' as the app, the vertical and horizontal series are flipped, making the pivot look different and much harder to read if switching from specific apps to 'Overall':

<img width="1214" alt="screen shot 2017-07-14 at 12 14 55 pm" src="https://user-images.githubusercontent.com/7634378/28225123-c5bd02e0-688e-11e7-837b-2efeb3564bb8.png">

Please let me know if there is something I am doing incorrectly to lead to the inconsistency. I believe the best fix allows any user to select which series is vertical and which is horizontal in the pivot table.

**Comment by doodlebro** [comment] 2017-07-14 18:31
So, it looks like this only happens for questions (that are not a part of a dashboard). When I brought this question to a dashboard, the pivot table was consistent regardless of which app I chose.

Not sure what causes that difference, but there should still be an explicit option to pick how the table pivots.

**Comment by salsakran** [comment] 2017-07-17 21:41
closing as a dupe of #4210 #5370

**Closed by salsakran** 2017-07-17 21:41 UTC
