### ISSUE TITLE
Metabase reports Update Available when the update is older than current

### ISSUE THREAD

**Issue by multiplegeorges** [metabase/metabase#14908] opened 2021-02-20 18:10 UTC
**Preamble**

Our team LOVES Metabase. Thanks so much for such fantastic software. It's a pleasure to use and really easy to for ops to maintain. 💯 

**Describe the bug**
I run Metabase from the JAR file on a DO Droplet. It was running version 0.37.x and we saw that 0.38 is out, so I downloaded the new JAR, stopped the service, symlinked in the new JAR, and restarted the service. 

The service restarted and upgraded itself perfectly. 👍 

However, in the admin panel, Metabase is reporting an incorrect "Upgrade available" status.

**To Reproduce**
1. Run Metabase 0.37.x
2. Go to metabase.com and download the new JAR from https://www.metabase.com/start/oss/jar.html (This will auto-start a download.)
3. Upgrade Metabase using the downloaded JAR.
4. Go to newly upgraded Metabase and go to Admin. The incorrect status is there.

**Expected behavior**
Metabase should not report upgrades to *older* versions in the Admin panel.

**Screenshots**

<img width="572" alt="Screen Shot 2021-02-20 at 1 03 53 PM" src="https://user-images.githubusercontent.com/59541/108604551-981b5880-737c-11eb-9f94-0724c526b7fe.png">

**Severity**

Low, really just an annoyance, but I'm reporting it to put it on radar and in case it points to larger version management issue.

**Comment by flamber** [comment] 2021-02-20 18:13
It will show correctly in less than 12 hours. Duplicate of #11336

**Closed by flamber** 2021-02-20 18:13 UTC
Labels: .Needs Triage, Type:Bug
