### ISSUE TITLE
MSSQL bug - table not properly aliased -> multi-part identifier could not be bound 

### ISSUE THREAD

**Issue by dfx413** [metabase/metabase#13532] opened 2020-10-20 08:22 UTC
version: d4c811d

Hi, 
the queries generated by query builder that use filters on the tables related via foreign keys fail because of wrong table aliasing. When a table is aliased in MSSQL it must then be always accessed using that defined alias

Code here (problems marked by "------!!!" comments): 
```
SELECT
    SOME COLUMNS
FROM
    "dbo"."_vs_KLIENT_POBYT_PROGRAM_OBSAZ"
    LEFT JOIN "dbo"."_sgmt_L4_KL_POBYT_duplicity_L4G" "_sgmt_L4_KL_POBYT_duplicity_L4G - L4 pobyt"
    ON "dbo"."_vs_KLIENT_POBYT_PROGRAM_OBSAZ"."ID_L4_KL_POBYT" =
       "_sgmt_L4_KL_POBYT_duplicity_L4G - L4 pobyt"."ID_L4_KL_POBYT"
    LEFT JOIN "dbo"."L4_KL_POBYT" "L4_KL_POBYT__via__ID_L4_KL_POB"
    ON "dbo"."_vs_KLIENT_POBYT_PROGRAM_OBSAZ"."ID_L4_KL_POBYT" = "L4_KL_POBYT__via__ID_L4_KL_POB"."ID_L4_KL_POBYT"
    LEFT JOIN "dbo"."L4_CIS_PROGRAM" "L4_CIS_PROGRAM__via__ID_L4_CIS" ------!!! TABLE ALIASED HERE
    ON "dbo"."_vs_KLIENT_POBYT_PROGRAM_OBSAZ"."ID_L4_CIS_PROGRAM" = "L4_CIS_PROGRAM__via__ID_L4_CIS"."ID_L4_CIS_PROGRAM"
WHERE
    (datefromparts(year("dbo"."_vs_KLIENT_POBYT_PROGRAM_OBSAZ"."D_ZADANI_R"), 1, 1) =
     datefromparts(year(getdate()), 1, 1)
        AND (NOT (lower("L4_CIS_PROGRAM__via__ID_L4_CIS"."NAZEV_PROGRAM") like 'something')
            OR "dbo"."L4_CIS_PROGRAM"."NAZEV_PROGRAM" IS NULL) AND --------!!! MISSING TABLE ALIAS
     (NOT (lower("L4_CIS_PROGRAM__via__ID_L4_CIS"."NAZEV_PROGRAM") like 'something') OR
      "dbo"."L4_CIS_PROGRAM"."NAZEV_PROGRAM" IS NULL) AND --------!!! MISSING TABLE ALIAS
     ("L4_CIS_PROGRAM__via__ID_L4_CIS"."COLBIS_KOD_CLEN_B" <> 'something' OR
      "dbo"."L4_CIS_PROGRAM"."COLBIS_KOD_CLEN_B" IS NULL) AND --------!!! MISSING TABLE ALIAS
     (NOT (lower("L4_CIS_PROGRAM__via__ID_L4_CIS"."NAZEV_PROGRAM") like 'something') OR
      "dbo"."L4_CIS_PROGRAM"."NAZEV_PROGRAM" IS NULL) AND --------!!! MISSING TABLE ALIAS
     ("L4_CIS_PROGRAM__via__ID_L4_CIS"."COLBIS_KOD_CLEN_C" <> 'something' OR
      "dbo"."L4_CIS_PROGRAM"."COLBIS_KOD_CLEN_C" IS NULL))  
```

**Comment by dfx413** [comment] 2020-10-20 09:10
@sbelak 
Hi, not sure if it is about nested queries. The case mentioned uses just tables connected via relations in data model, nothing special.

**Comment by flamber** [comment] 2020-10-20 09:17
@dfx413 Is this is a new problem or is it the same in previous versions? Can you provide the full stacktrace too?
Possibly related to #13112

**Comment by dfx413** [comment] 2020-10-20 09:21
@flamber 
Hi, 
it is a new problem. Happened after upgrading to d4c811d.
I am sorry but I had to downgrade to 2e77f44 (the problem does not appear in that version) so I cannot provide the stack trace right now.

**Comment by flamber** [comment] 2020-10-20 09:36
@dfx413 I would guess it's caused by #13243, but it would be very helpful if you can narrow down the commit that caused it.

**Comment by dfx413** [comment] 2020-10-20 09:52
@flamber sorry but I only know that 2e77f44 works just fine. 
The pull request you are mentioning seems to be too old. 
If I am correct then this pull request is present in both d4c811d and 2e77f44 so I don't think it is the one causing the issue.

**Comment by sbelak** [comment] 2020-10-20 09:55
#13243 doesn't alter how we generate SQL beyond dropping duplicates

**Comment by flamber** [comment] 2020-10-20 12:04
Closing in favor of #13534

**Closed by flamber** 2020-10-20 12:04 UTC
Labels: .Query Language (MBQL), Database/SQLServer, Priority:P1, Type:Bug
