### ISSUE TITLE
Values Improperly labled in multiple series chart

### ISSUE THREAD

**Issue by TomTrinh** [metabase/metabase#6524] opened 2017-12-05 10:28 UTC
When building a multi-series area chart in SQL, multiple series charts can misrepresent the underlying data.

I have two column (TRX and TPV in million) to show as multiple line/bar chart by day.
This is the raw data showed as table:
![image](https://user-images.githubusercontent.com/22843620/33602038-ae3f9bdc-d9e0-11e7-8392-26e8ebe9b0e9.png)

However, when I show it as line or bar chart and hover over the point on TRX line in the chart, it show wrong number of 'TPV in million'.  But When hovering to the point of 'TPV in million' line, it show correct value:
![image](https://user-images.githubusercontent.com/22843620/33602242-4615c5e4-d9e1-11e7-89ef-adc4193f5386.png)
![image](https://user-images.githubusercontent.com/22843620/33602306-83fda2b4-d9e1-11e7-8634-c5ca6f0b65bb.png)

Bar chart and area chart show the same thing improperly.

METABASE version: Metabase 0.27.0
Browser: Fire Fox Quantum 57.0

**Comment by c-schmitz** [comment] 2017-12-19 13:34
Same issue here. I hope this can be fixed soon.

**Comment by mazameli** [comment] 2017-12-19 14:58
I believe #6591 will fix this issue.

**Comment by attekei** [comment] 2018-01-22 09:58
I can't reproduce this anymore in `master` so I'll close this issue. We will release 0.28 which will contain the fix (#6591) pretty soon.

**Closed by attekei** 2018-01-22 09:58 UTC
Labels: Bug, Priority/P2, Visualization
