### ISSUE TITLE
Custom column after a simple query fails, creates faulty SQL

### ISSUE THREAD

**Issue by dah33** [metabase/metabase#13336] opened 2020-10-01 14:15 UTC
Custom column after a simple query fails. The custom column "Margin" should just be half the "Sum of Total" column.

To reproduce, see this screen shot, which uses the sample data.

![image](https://user-images.githubusercontent.com/17231347/94820547-7edb3500-03f8-11eb-832c-651cabf9da4e.png)

It seems to produce this fauly SQL, which I've simplified to isolate the bug:

```sql
SELECT
(CAST("source"."sum" AS float) / CASE WHEN 2.0 = 0 THEN NULL ELSE 2.0 END) AS "Margin", 
"source"."TOTAL" AS "TOTAL", "source"."sum" AS "sum" FROM 
(SELECT sum("PUBLIC"."ORDERS"."TOTAL") AS "sum" FROM "PUBLIC"."ORDERS") "source"
```

**Logs**
```
10-01 15:10:49 [1mERROR middleware.catch-exceptions[0m :: Error processing query: null
{:database_id 1,
 :started_at #t "2020-10-01T15:10:49.644+01:00[Europe/London]",
 :state "42S22",
 :json_query
 {:type "query",
  :query {:source-query {:source-table 2, :aggregation [["sum" ["field-id" 15]]], :breakout [["field-id" 13]]}, :expressions {:Margin ["/" ["field-literal" "sum" "type/Float"] 2]}, :limit 10},
  :database 1,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"sum\" AS \"sum\", \"source\".\"Margin\" AS \"Margin\" FROM (SELECT (CAST(\"source\".\"sum\" AS float) / CASE WHEN 2.0 = 0 THEN NULL ELSE 2.0 END) AS \"Margin\", \"source\".\"TOTAL\" AS \"TOTAL\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"sum\" AS \"sum\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID_2\" FROM (SELECT \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", sum(\"PUBLIC\".\"ORDERS\".\"TOTAL\") AS \"sum\" FROM \"PUBLIC\".\"ORDERS\" GROUP BY \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" ORDER BY \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" ASC) \"source\") \"source\" LIMIT 10",
  :params nil},
 :status :failed,
 :class org.h2.jdbc.JdbcSQLException,
 :stacktrace
 ["org.h2.message.DbException.getJdbcSQLException(DbException.java:357)"
  "org.h2.message.DbException.get(DbException.java:179)"
  "org.h2.message.DbException.get(DbException.java:155)"
  "org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)"
  "org.h2.expression.Alias.optimize(Alias.java:51)"
  "org.h2.command.dml.Select.prepare(Select.java:858)"
  "org.h2.command.Parser.prepare(Parser.java:263)"
  "org.h2.engine.Session.prepare(Session.java:576)"
  "org.h2.table.TableView.compileViewQuery(TableView.java:120)"
  "org.h2.table.TableView.initColumnsAndTables(TableView.java:172)"
  "org.h2.table.TableView.init(TableView.java:113)"
  "org.h2.table.TableView.<init>(TableView.java:70)"
  "org.h2.table.TableView.createTempView(TableView.java:559)"
  "org.h2.command.Parser.readTableFilter(Parser.java:1367)"
  "org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:2138)"
  "org.h2.command.Parser.parseSelectSimple(Parser.java:2287)"
  "org.h2.command.Parser.parseSelectSub(Parser.java:2133)"
  "org.h2.command.Parser.parseSelectUnion(Parser.java:1946)"
  "org.h2.command.Parser.parseSelect(Parser.java:1919)"
  "org.h2.command.Parser.parsePrepared(Parser.java:463)"
  "org.h2.command.Parser.parse(Parser.java:335)"
  "org.h2.command.Parser.parse(Parser.java:307)"
  "org.h2.command.Parser.prepareCommand(Parser.java:278)"
  "org.h2.engine.Session.prepareLocal(Session.java:611)"
  "org.h2.engine.Session.prepareCommand(Session.java:549)"
  "org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)"
  "org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)"
  "org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1135)"
  "com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:267)"
  "--> driver.sql_jdbc.execute$fn__72545.invokeStatic(execute.clj:239)"
  "driver.sql_jdbc.execute$fn__72545.invoke(execute.clj:237)"
  "driver.sql_jdbc.execute$prepared_statement_STAR_.invokeStatic(execute.clj:257)"
  "driver.sql_jdbc.execute$prepared_statement_STAR_.invoke(execute.clj:254)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:387)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)"
  "driver.sql_jdbc$fn__73933.invokeStatic(sql_jdbc.clj:49)"
  "driver.sql_jdbc$fn__73933.invoke(sql_jdbc.clj:47)"
  "driver.h2$fn__72752.invokeStatic(h2.clj:82)"
  "driver.h2$fn__72752.invoke(h2.clj:79)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
  "query_processor.context.default$default_runf.invoke(default.clj:67)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__45635.invoke(mbql_to_native.clj:26)"
  "query_processor.middleware.check_features$check_features$fn__44911.invoke(check_features.clj:42)"
  "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__45800.invoke(optimize_datetime_filters.clj:133)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47328.invoke(wrap_value_literals.clj:137)"
  "query_processor.middleware.annotate$add_column_info$fn__43532.invoke(annotate.clj:574)"
  "query_processor.middleware.permissions$check_query_permissions$fn__44786.invoke(permissions.clj:64)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__46318.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__44984.invoke(cumulative_aggregations.clj:61)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__46850.invoke(resolve_joins.clj:183)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39262.invoke(add_implicit_joins.clj:245)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__45596.invoke(large_int_id.clj:44)"
  "query_processor.middleware.limit$limit$fn__45621.invoke(limit.clj:38)"
  "query_processor.middleware.format_rows$format_rows$fn__45576.invoke(format_rows.clj:81)"
  "query_processor.middleware.desugar$desugar$fn__45050.invoke(desugar.clj:22)"
  "query_processor.middleware.binning$update_binning_strategy$fn__44076.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__44592.invoke(resolve_fields.clj:24)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__38811.invoke(add_dimension_projections.clj:318)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39018.invoke(add_implicit_clauses.clj:141)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39411.invoke(add_source_metadata.clj:105)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__46515.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__43717.invoke(auto_bucket_datetimes.clj:125)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__44639.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.parameters$substitute_parameters$fn__46300.invoke(parameters.clj:114)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__44691.invoke(resolve_referenced.clj:80)"
  "query_processor.middleware.expand_macros$expand_macros$fn__45306.invoke(expand_macros.clj:158)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__39442.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47212.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526$fn__46530.invoke(resolve_database_and_driver.clj:33)"
  "driver$do_with_driver.invokeStatic(driver.clj:61)"
  "driver$do_with_driver.invoke(driver.clj:57)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526.invoke(resolve_database_and_driver.clj:27)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45524.invoke(fetch_source_query.clj:267)"
  "query_processor.middleware.store$initialize_store$fn__47221$fn__47222.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__47221.invoke(store.clj:10)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__44568.invoke(cache.clj:209)"
  "query_processor.middleware.validate$validate_query$fn__47230.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__45648.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39280.invoke(add_rows_truncated.clj:36)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47197.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__44927.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__46389.invoke(process_userland_query.clj:136)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__44870.invoke(catch_exceptions.clj:174)"
  "query_processor.reducible$async_qp$qp_STAR___38074$thunk__38075.invoke(reducible.clj:101)"
  "query_processor.reducible$async_qp$qp_STAR___38074.invoke(reducible.clj:107)"
  "query_processor.reducible$sync_qp$qp_STAR___38083$fn__38086.invoke(reducible.clj:133)"
  "query_processor.reducible$sync_qp$qp_STAR___38083.invoke(reducible.clj:132)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:215)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:211)"
  "query_processor$fn__47372$process_query_and_save_execution_BANG___47381$fn__47384.invoke(query_processor.clj:227)"
  "query_processor$fn__47372$process_query_and_save_execution_BANG___47381.invoke(query_processor.clj:219)"
  "query_processor$fn__47416$process_query_and_save_with_max_results_constraints_BANG___47425$fn__47428.invoke(query_processor.clj:239)"
  "query_processor$fn__47416$process_query_and_save_with_max_results_constraints_BANG___47425.invoke(query_processor.clj:232)"
  "api.dataset$fn__50707$fn__50710.invoke(dataset.clj:55)"
  "query_processor.streaming$streaming_response_STAR_$fn__35496$fn__35497.invoke(streaming.clj:73)"
  "query_processor.streaming$streaming_response_STAR_$fn__35496.invoke(streaming.clj:72)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
  "async.streaming_response$do_f_async$fn__23282.invoke(streaming_response.clj:85)"],
 :context :ad-hoc,
 :error
 "Column \"source.TOTAL\" not found; SQL statement:\nCREATE FORCE VIEW PUBLIC._36 AS\nSELECT\n    (CAST(\"source\".\"sum\" AS DOUBLE) / CASE WHEN (2.0 = 0) THEN NULL ELSE 2.0 END) AS \"Margin\",\n    \"source\".TOTAL AS TOTAL,\n    \"source\".PRODUCT_ID AS PRODUCT_ID,\n    \"source\".\"sum\" AS \"sum\",\n    \"source\".PRODUCT_ID AS PRODUCT_ID_2\nFROM (\n    SELECT\n        PUBLIC.ORDERS.PRODUCT_ID AS PRODUCT_ID,\n        SUM(PUBLIC.ORDERS.TOTAL) AS \"sum\"\n    FROM PUBLIC.ORDERS\n    GROUP BY PUBLIC.ORDERS.PRODUCT_ID\n    ORDER BY 1\n) \"source\" [42122-197]",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:type :query,
  :query
  {:source-query {:source-table 2, :aggregation [[:aggregation-options [:sum [:field-id 15]] {:name "sum"}]], :breakout [[:field-id 13]], :order-by [[:asc [:field-id 13]]]},
   :expressions {:Margin [:/ [:field-literal "sum" :type/Float] 2]},
   :limit 10,
   :source-metadata
   [{:name "PRODUCT_ID", :id 13, :table_id 2, :display_name "Product ID", :base_type :type/Integer, :special_type :type/FK, :fingerprint {:global {:distinct-count 200, :nil% 0.0}}, :settings nil}
    {:name "sum", :display_name "Sum of Total", :base_type :type/Float, :special_type nil, :settings nil}],
   :fields [[:field-literal "PRODUCT_ID" :type/Integer] [:field-literal "sum" :type/Float] [:expression "Margin"]]},
  :database 1,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :nested? false,
   :query-hash [-18, 73, 97, -78, -94, 120, -80, -80, -18, 119, 76, 60, 16, 9, 62, -117, 61, 93, 33, -1, -36, 83, -124, 87, -76, 15, -77, -128, -67, -121, -59, -52]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :data {:rows [], :cols []}}
```

**Troubleshooting info**:
```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_241-b07",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_241",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.241-b07",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Europe/London"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.36.6",
      "date": "2020-09-15",
      "branch": "release-0.36.x",
      "hash": "cb258fb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2020-10-01 14:19
Duplicate of #12762

**Closed by flamber** 2020-10-01 14:19 UTC
Labels: .Needs Triage, Type:Bug
