### ISSUE TITLE
Schemas and tables dont appear in metabase UI but in SQL query editor you can query it

### ISSUE THREAD

**Issue by Filip-Djokovic** [metabase/metabase#35562] opened 2023-11-09 20:59 UTC
### Describe the bug

The GUI is routinely missing several schemas. Our Metabase instance is connected to a database with more than a dozen schemas. Sometimes all the schemas can be seen through the GUI, both in the "Browse data" tab and with the Question editor, sometimes you only seed a handful (e.g. from the letter A to the letter O).
This causes an issue when creating a new question with the question editor, you can't select tables from schemas that are not shown in the GUI. You cannot either add filters that use those fields.
Notes:
The SQL query editor can query all the schemas and tables that are not shown with the GUI. It is not a connection or permission issue between Metabase and the database.
Existing dashboards and questions relying on the hidden schemas are still working and returning data.
Both the database sync and scan are done daily.
This bug occurs more often on days where we have more Metabase usage.

### To Reproduce

- Open metabase
- go to browse data tab

### Expected behavior

You should see all schemas and tables in metabase UI

### Information about your Metabase installation

```JSON
- Chrome Version 119.0.6045.123
- macos Version 14.1 (23B74)
- redshift
```

### Severity

issue for users that dont have sql query permissions

**Comment by paoliniluis** [comment] 2023-11-09 22:51
It's impossible to debug without logs or troubleshooting info

**Comment by paoliniluis** [comment] 2023-11-10 12:05
@Filip-Djokovic please send logs, troubleshooting info and possibly reproduction steps, otherwise we will have to close the issue

**Comment by paoliniluis** [comment] 2023-11-22 20:21
closing due to inactivity

**Closed by paoliniluis** 2023-11-22 20:21 UTC
Labels: Type:Bug, .Needs Triage

**Comment by ignacio-mb** [comment] 2023-12-01 17:33
This was https://github.com/metabase/metabase/issues/36040
