### ISSUE TITLE
no dropdown filters on dashboards with sql questions

### ISSUE THREAD

**Issue by AgentBlond** [metabase/metabase#14242] opened 2021-01-04 15:57 UTC
**Describe the bug**
In earlier versions of Metabase it was possible to link filters to sql based questions and questions created with the builder. Dropdown options were displayed for both type of questions. Now, once there is one sql-based question the dropdown values are not shown anymore.

**Expected behavior**
See video expected behavior.

**Screenshots**
See current behavior

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome Version 87.0.4280.88
- Your operating system: Mac OS Catalina
- Your databases: BigQuery
- Metabase version: 0.37.3
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
It is quite severe, because all of our dashboards are built with at least 1 question that is sql based.

Expected behavior
![metabase-expected-behavior](https://user-images.githubusercontent.com/22956171/103553481-ca94f300-4ead-11eb-9be1-9a4f8aa8a232.gif)

Current behavior
![metabase-behavior-now](https://user-images.githubusercontent.com/22956171/103553466-c668d580-4ead-11eb-819c-01505609757e.gif)

**Comment by flamber** [comment] 2021-01-29 17:54
Hi @AgentBlond 

This only occurs, when the SQL filter is not a Field Filter. You should also see a note, when connecting the filter to the card:
> This field only accepts a single value because it's used in a SQL query

The problem is that the dropdown list allows multiple values to be selected, which could break the query on the SQL question - depending on how the variable is used.

Example with multiple selected values:
This would break on any version: `WHERE 1=1 [[AND column={{text_filter}}]]`
While this would work pre-0.35.0: `WHERE 1=1 [[AND column IN ({{text_filter}})]`

But we haven't documented the use-case of `IN ()`, which is likely why it was overlooked and the widget was forced to input.

Regression since 0.35.0. Related to #4728, #5245 and #7605. Workaround is to use Field Filters:
https://www.metabase.com/learn/building-analytics/sql-templates/field-filters.html

**Comment by daltojohnso** [comment] 2021-06-15 18:35
Looks like this was caused by https://github.com/metabase/metabase/pull/12012 which was needed to fix https://github.com/metabase/metabase/issues/11882.

Since Field Filters cover things (besides `IN ()` syntax with a variable) is there anything to do here @flamber?

**Comment by flamber** [comment] 2021-06-15 21:32
Considering this issue only has 1 upvote (me) and the workaround is to use Field Filters, then I think we're going to close this.

**Closed by flamber** 2021-06-15 21:32 UTC
Labels: .Regression, Priority:P2, Querying/Parameters & Variables, Reporting/Dashboards, Type:Bug

**Comment by sarim-zafar** [comment] 2023-10-04 13:37
On many occasions you might not have the data available in a raw table and it might be coming through a model instead. I think it should at least be allowed to link it to a model's column to filter if raw text prohibits it.
