### ISSUE TITLE
Inconsistent width on Visibility and Type dropdowns in Data Model

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#22633] opened 2022-05-11 15:28 UTC
What you pick in the semantic type dropdown seems to have an undesireable effect on how wide the Type and Visibility dropdowns are, causing them to be irregular widths, which makes things look weird.

These dropdowns should be a consistent width, and the `Type` heading should be left-aligned with the semantic type dropdowns.

![image](https://user-images.githubusercontent.com/2223916/167888008-58120ec4-ef6b-4989-b498-e93141c8ce50.png)

**Comment by flamber** [comment] 2022-05-11 15:39
Duplicate of #10465

**Closed by flamber** 2022-05-11 15:39 UTC
Labels: Type:Bug, Priority:P3, Administration/Data Model
