### ISSUE TITLE
Returning raw data view always returns 'We couldn’t understand your question'

### ISSUE THREAD

**Issue by bencarter78** [metabase/metabase#1560] opened 2015-11-25 22:13 UTC
I've just found Metabase and am just having a play with it. I've connected it to a MySQL DB which is working. However, if I try to ask a new question that just returns the raw data with no filters or grouping then it always returns the message 'We couldn't understand your question'. On 1 particular table in my DB it will return but only if the results are limited to 10 results.

I then went to the query editor and tried...

SELECT * FROM my_table
This always returns 'Connection is read-only. Queries leading to data modification are not allowed' no matter what table I choose.

If I run the same query against the sample data then it returns the data set as expected.

Am I doing something wrong? Is this a bug?

**Comment by camsaul** [comment] 2015-11-25 22:41
Hi @bencarter78 this is a bug with the way we were setting timezones for MySQL DBs and a fix will be available in our next release. In the meantime, if you unset the timezone in the admin panel it should let you run queries again.

Closing as duplicate of #1291

**Closed by camsaul** 2015-11-25 22:41 UTC

**Comment by bencarter78** [comment] 2015-11-26 10:14
HI @camsaul I've tried unsetting it and I still get the same thing happening. Any ideas how I can get it to work?
