### ISSUE TITLE
Impossible to delete a collection - even through the API

### ISSUE THREAD

**Issue by prilosac** [metabase/metabase#8285] opened 2018-08-10 19:08 UTC
I need to be able to delete things from Metabase (cards, dashboards, collections), and I know that cards and dashboards can be deleted through the API (which I have done), but there is no endpoint in the API docs to delete a collection, and it also cannot be done from the UI. I tried `DELETE /api/collection/:id`, but it says there is no API endpoint for that. would really like to be able to get rid of this "test" collection, which neither the Metabase UI nor the API seem to have an option for. Is there any way to do this, or do I have to completely re setup Metabase in order to delete a collection? If there is not a way to do this, could one be implemented? It doesn't seem right that Metabase doesn't allow you to easily actually delete things rather than archive them - seems like a feature many people would need/want.

**Comment by kdoh** [comment] 2018-10-31 02:04
Agree with @jornh this is an overall duplicate of #8096. We're doing some work on this in #8820 and I'll make a note to ensure collections can be deleted there.

**Closed by kdoh** 2018-10-31 02:04 UTC
