### ISSUE TITLE
Nested queries with date filter fail with honeysql error

### ISSUE THREAD

**Issue by lenn4rd** [metabase/metabase#9056] opened 2018-11-30 14:57 UTC
Using a question that has a date filter defined as Saved Question in the query builder fails with the following error:

`No method in multimethod '->honeysql' for dispatch value: [metabase.driver.h2.H2Driver :time-interval]`

Steps to reproduce:

1. Create a question from any table in the sample database and define a simple date filter, e.g. _Created At_ is _Current Year_ in _Orders_
2. Use this question as a Saved Question and execute it; it'll fail with above error message

This seems to be a regression. I encountered it while testing our staging installation running v0.31.1 and also tested against our production installation running v0.30.1. It works in v0.30.1 and it's broken in v0.31.1.

I looked at the issues labeled Nested Queries and the ones with a similar error message but they seem a bit different. Let me know if I missed something and feel free to close issue as a duplicate.

- Your browser and the version: Safari 12.0.1
- Your operating system: macOS 10.13.6
- Your databases: Postgres 10.4
- Metabase version: v0.31.1
- Metabase hosting environment: AWS ECS
- Metabase internal database: Postgres 10.5

**Comment by camsaul** [comment] 2018-11-30 22:20
Duplicate of #9007

**Comment by lenn4rd** [comment] 2019-03-04 16:07
This is actually not a duplicate of #9007 because it's set up a bit differently. In contrast to that issue, my issue is caused by using the Custom query builder and setting a date in the underlying (to be nested) query. When using it as a nested query, it fails.

**Comment by flamber** [comment] 2019-03-04 17:49
@lenn4rd Yeah, it seems like a different issue. I can reproduce your issue on 0.31.2 with any datasource

@camsaul This issue seems to be valid, while I cannot reproduce #9007 on 0.31.2

**Comment by Wemps** [comment] 2019-05-08 17:10
Ooof, this is killing me now as well after updating to 0.32.5.0. Any work arounds besides creating the query again?

**Comment by flamber** [comment] 2020-03-04 13:24
I'm not sure what fixed this, but I cannot reproduce on 0.32.9+, while I can reproduce on 0.32.7-

**Closed by flamber** 2020-03-04 13:24 UTC
Labels: Priority:P2, Querying/Nested Queries, Type:Bug

**Comment by lenn4rd** [comment] 2020-03-04 14:49
Good to know! Thanks for the heads-up.

Let's `git bisect`! 😬
