### ISSUE TITLE
No lines in chart when first row has NULL value

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4128] opened 2017-01-11 22:11 UTC
Metabase 0.22

![image](https://cloud.githubusercontent.com/assets/1708680/21868478/e9d8e362-d863-11e6-8768-deb5b2ec8e3c.png)

If I sort this table ASC order (first row haven't NULL values) everything fine.

**Comment by tlrobinson** [comment] 2017-02-07 22:15
@anki-code Does this only occur for SQL queries, or the GUI query builder as well?

**Comment by tlrobinson** [comment] 2017-02-07 22:19
If that is the case, I believe this is a result of #4256.

**Comment by anki-code** [comment] 2017-02-08 08:33
@tlrobinson 
> Does this only occur for SQL queries, or the GUI query builder as well?

It's occur only for SQL:

1. H2 + Query Builder:
```
create table test(a int, b int, c int);
insert into test(a,b,c) values(1,1,null);
insert into test(a,b,c) values(2,2,null);
insert into test(a,b,c) values(3,3,1);
insert into test(a,b,c) values(4,4,2);
insert into test(a,b,c) values(5,null,3);
```
Result:
![image](https://cloud.githubusercontent.com/assets/1708680/22729070/1ada3cb0-edf2-11e6-84c6-77359a53ebc0.png)

2. SQL:
```
SELECT *
FROM (
    select 1a , 1b, null c union
    select 2,2,null union
    select 3,3,1 union
    select 4,4,2 union
    select 5,null,3
)q
ORDER BY 1
```

Result:
![image](https://cloud.githubusercontent.com/assets/1708680/22729087/33367da0-edf2-11e6-805e-98d3a06d9590.png)

**Comment by neoecos** [comment] 2017-02-08 15:01
Have the same issue with a query 

`SELECT  date_trunc('month', "public"."charge"."date_created") AS "date_created", (100.0 * (1 - lag( sum("public"."charge"."amount_amount") ) OVER month /  sum("public"."charge"."amount_amount"))) AS Grown

![selection_238](https://cloud.githubusercontent.com/assets/1490677/22742657/7cc7a208-ede5-11e6-9365-8c8d8f19a6d3.png)
`

**Comment by tlrobinson** [comment] 2017-03-01 01:28
I'm going to close this as a duplicate of #4256

**Closed by tlrobinson** 2017-03-01 01:28 UTC
Labels: Bug, Priority/P2, Visualization
