### ISSUE TITLE
If there are only questions in "Everything else" or a single collection, skip that panel

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#5027] opened 2017-05-09 00:28 UTC
Not really any point in showing this screen:

 ![screen shot 2017-05-08 at 5 26 55 pm](https://cloud.githubusercontent.com/assets/18193/25830724/a0ad91e0-3413-11e7-9cc0-5b63edfa8b22.png)

**Comment by mazameli** [comment] 2017-05-11 22:35
Totally agree. Dupe of https://github.com/metabase/metabase/issues/4668

**Closed by mazameli** 2017-05-11 22:35 UTC
Labels: UX
