### ISSUE TITLE
Metric with ID xx does not exist

### ISSUE THREAD

**Issue by cgg-pwdt** [metabase/metabase#40393] opened 2024-03-20 18:01 UTC
**Describe the bug**
When creating a Metabase question, selecting a Common Metric and creating a summary, we lose the Common Metrics group and if we pick the initial Common Metric added Metabase shows a error message. The console log displays a "metric with id xx not found" issue. 

We've recorded the following Loom to show the issue: https://www.loom.com/share/a3775a517dc3402ba4e37bd1e4e7fdb0?sid=b196bff3-b455-40dc-8348-a94d9b3663b6 

If we pick all the Common Metrics we are summarizing and then the Dimensions, Metabase outputs the result properly. However, we lose the ability to edit the question.

**Logs**
metric with ID does not exist : 32 > react-dom.prodcution.min.js:209 
Error app.ts:30

**To Reproduce**
1. Go to 'New > Question'
2. Select a Table with Metrics (Common Metrics)
3. Scroll down to and add one Common Metric and a Dimension to group by
4. Try to add another Common Metric (doesn't show)
5. Click on the initial common metric
6. Error

https://www.loom.com/share/a3775a517dc3402ba4e37bd1e4e7fdb0?sid=b196bff3-b455-40dc-8348-a94d9b3663b6 

**Expected behavior**
Expectation is to continue to see the Common Metrics group and be able to click on it these metrics to edit its definition 

**Screenshots**
<img width="516" alt="image" src="https://github.com/metabase/metabase/assets/136714486/d0ea4cc4-7ffc-402e-979e-165a5301f54c">

**Severity**
blocking usage of metabase

**Additional context**
metabase 0.49, self hosted

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.10.205-195.804.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-14",
      "tag": "v0.49.0",
      "hash": "46c668b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by cgg-pwdt** [comment] 2024-03-20 18:06
apologies I forgot to label this issue 

I guess it should be `.Needs Triage` and `Type:Bug`

**Comment by uladzimirdev** [comment] 2024-03-27 07:15
Duplicate of https://github.com/metabase/metabase/issues/40553

**Closed by uladzimirdev** 2024-03-27 07:15 UTC
