### ISSUE TITLE
SQLite - Error running sync step: Output of sync-fields-for-table!

### ISSUE THREAD

**Issue by JBrame** [metabase/metabase#10681] opened 2019-08-22 11:17 UTC
**Describe the bug**
When trying to sync a data base I am getting the error: Error running sync step: Output of sync-fields-for-table! This is a new installation of metabase 0.33.0 but it's a database that I have been using on previous versions without any issues

**Logs**
```
08-22 12:05:06 [1mINFO sync.util[0m :: STARTING: Sync metadata for sqlite Database 2 'SQLite'
08-22 12:05:07 [1mWARN sql-jdbc.sync[0m :: Don't know how to map column type '' to a Field base_type, falling back to :type/*.
08-22 12:05:07 [1mWARN sql-jdbc.sync[0m :: Don't know how to map column type '' to a Field base_type, falling back to :type/*.
08-22 12:05:07 [1mWARN sql-jdbc.sync[0m :: Don't know how to map column type '' to a Field base_type, falling back to :type/*.
08-22 12:05:07 [1mERROR sync.util[0m :: Error syncing Fields for Table 'Table 5 'csp_min_max'': Output of table-metadata does not match schema:

         [0;33m  {:fields #{{:database-type (not ("Non-blank string" ""))} {:database-type (not ("Non-blank string" ""))} {:database-type (not ("Non-blank string" ""))}}} [0m


("--> sync.fetch_metadata$fn__49438$table_metadata__49443.invoke(fetch_metadata.clj:15)"
 "sync.sync_metadata.fields.fetch_metadata$fn__49760$db_metadata__49765$fn__49766.invoke(fetch_metadata.clj:82)"
 "sync.sync_metadata.fields.fetch_metadata$fn__49760$db_metadata__49765.invoke(fetch_metadata.clj:78)"
 "sync.sync_metadata.fields$fn__50264$sync_fields_for_table_BANG___50273$fn__50279$fn__50281.invoke(fields.clj:91)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:149)"
 "sync.util$do_with_error_handling.invoke(util.clj:144)"
 "sync.sync_metadata.fields$fn__50264$sync_fields_for_table_BANG___50273$fn__50279.invoke(fields.clj:90)"
 "sync.sync_metadata.fields$fn__50264$sync_fields_for_table_BANG___50273.invoke(fields.clj:83)"
 "sync.sync_metadata.fields$fn__50309$sync_fields_BANG___50314$fn__50315$iter__50316__50320$fn__50321$fn__50322.invoke(fields.clj:117)"
 "sync.sync_metadata.fields$fn__50309$sync_fields_BANG___50314$fn__50315$iter__50316__50320$fn__50321.invoke(fields.clj:116)"
 "sync.sync_metadata.fields$fn__50309$sync_fields_BANG___50314$fn__50315.invoke(fields.clj:116)"
 "sync.sync_metadata.fields$fn__50309$sync_fields_BANG___50314.invoke(fields.clj:111)"
 "sync.util$fn__41313$run_step_with_metadata__41318$fn__41322$fn__41324.invoke(util.clj:356)"
 "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
 "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
 "sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)"
 "sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)"
 "sync.util$fn__41313$run_step_with_metadata__41318$fn__41322.invoke(util.clj:353)"
 "sync.util$fn__41313$run_step_with_metadata__41318.invoke(util.clj:348)"
 "sync.util$fn__41505$run_sync_operation__41510$fn__41511$fn__41512.invoke(util.clj:441)"
 "sync.util$fn__41505$run_sync_operation__41510$fn__41511.invoke(util.clj:441)"
 "sync.util$fn__41505$run_sync_operation__41510.invoke(util.clj:435)"
 "sync.sync_metadata$fn__50996$sync_db_metadata_BANG___51001$fn__51002$fn__51003.invoke(sync_metadata.clj:51)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:149)"
 "sync.util$do_with_error_handling.invoke(util.clj:144)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:147)"
 "sync.util$do_with_error_handling.invoke(util.clj:144)"
 "driver$fn__19275.invokeStatic(driver.clj:671)"
 "driver$fn__19275.invoke(driver.clj:671)"
 "sync.util$sync_in_context$fn__41219.invoke(util.clj:140)"
 "sync.util$with_db_logging_disabled$fn__41216.invoke(util.clj:131)"
 "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
 "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
 "sync.util$with_start_and_finish_logging$fn__41205.invoke(util.clj:116)"
 "sync.util$with_sync_events$fn__41200.invoke(util.clj:90)"
 "sync.util$with_duplicate_ops_prevented$fn__41191.invoke(util.clj:69)"
 "sync.util$do_sync_operation.invokeStatic(util.clj:168)"
 "sync.util$do_sync_operation.invoke(util.clj:165)"
 "sync.sync_metadata$fn__50996$sync_db_metadata_BANG___51001$fn__51002.invoke(sync_metadata.clj:50)"
 "sync.sync_metadata$fn__50996$sync_db_metadata_BANG___51001.invoke(sync_metadata.clj:47)"
 "api.database$fn__51669$fn__51671.invoke(database.clj:520)")

08-22 12:05:07 [1mERROR sync.util[0m :: Error running sync step: Output of sync-fields-for-table! does not match schema:

         [0;33m  (not (map? a-clojure.lang.ExceptionInfo)) [0m


("--> sync.sync_metadata.fields$fn__50264$sync_fields_for_table_BANG___50273.invoke(fields.clj:83)"
 "sync.sync_metadata.fields$fn__50309$sync_fields_BANG___50314$fn__50315$iter__50316__50320$fn__50321$fn__50322.invoke(fields.clj:117)"
 "sync.sync_metadata.fields$fn__50309$sync_fields_BANG___50314$fn__50315$iter__50316__50320$fn__50321.invoke(fields.clj:116)"
 "sync.sync_metadata.fields$fn__50309$sync_fields_BANG___50314$fn__50315.invoke(fields.clj:116)"
 "sync.sync_metadata.fields$fn__50309$sync_fields_BANG___50314.invoke(fields.clj:111)"
 "sync.util$fn__41313$run_step_with_metadata__41318$fn__41322$fn__41324.invoke(util.clj:356)"
 "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
 "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
 "sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)"
 "sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)"
 "sync.util$fn__41313$run_step_with_metadata__41318$fn__41322.invoke(util.clj:353)"
 "sync.util$fn__41313$run_step_with_metadata__41318.invoke(util.clj:348)"
 "sync.util$fn__41505$run_sync_operation__41510$fn__41511$fn__41512.invoke(util.clj:441)"
 "sync.util$fn__41505$run_sync_operation__41510$fn__41511.invoke(util.clj:441)"
 "sync.util$fn__41505$run_sync_operation__41510.invoke(util.clj:435)"
 "sync.sync_metadata$fn__50996$sync_db_metadata_BANG___51001$fn__51002$fn__51003.invoke(sync_metadata.clj:51)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:149)"
 "sync.util$do_with_error_handling.invoke(util.clj:144)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:147)"
 "sync.util$do_with_error_handling.invoke(util.clj:144)"
 "driver$fn__19275.invokeStatic(driver.clj:671)"
 "driver$fn__19275.invoke(driver.clj:671)"
 "sync.util$sync_in_context$fn__41219.invoke(util.clj:140)"
 "sync.util$with_db_logging_disabled$fn__41216.invoke(util.clj:131)"
 "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
 "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
 "sync.util$with_start_and_finish_logging$fn__41205.invoke(util.clj:116)"
 "sync.util$with_sync_events$fn__41200.invoke(util.clj:90)"
 "sync.util$with_duplicate_ops_prevented$fn__41191.invoke(util.clj:69)"
 "sync.util$do_sync_operation.invokeStatic(util.clj:168)"
 "sync.util$do_sync_operation.invoke(util.clj:165)"
 "sync.sync_metadata$fn__50996$sync_db_metadata_BANG___51001$fn__51002.invoke(sync_metadata.clj:50)"
 "sync.sync_metadata$fn__50996$sync_db_metadata_BANG___51001.invoke(sync_metadata.clj:47)"
 "api.database$fn__51669$fn__51671.invoke(database.clj:520)")

08-22 12:05:07 [1mINFO sync.util[0m :: FINISHED: Sync metadata for sqlite Database 2 'SQLite' (1.1 s)
```

**To Reproduce**
Error seen when trying to sync the database via the admin console. 

**Screenshots**
When trying to view data from some of the tables in the query builder I now also see this error, but some tables also work fine.

![image](https://user-images.githubusercontent.com/6168847/63510512-aada7600-c4d6-11e9-899d-ec0a2f2821e0.png)

**Information about your Metabase Installation:**
- Browser: Chrome Version 76.0.3809.100 (Official Build) (64-bit)
- OS: Windows 10
- Database: SQLite
- Metabase version: 0.33.0
- Metabase hosting environment: jar file
- Metabase internal database: H2 (default)

**Severity**
Blocking your usage of Metabase entirely

**Comment by TheCondorman** [comment] 2019-08-28 15:12
Any ideas about this one?

**Comment by equivalentideas** [comment] 2019-10-16 01:20
I've raised an thread in the forum to get help on what appears to be the same issue https://discourse.metabase.com/t/incorrect-reading-of-sqlite-database-fields/7669

**Comment by camsaul** [comment] 2020-07-16 17:25
This is the same issue as #12547, merging into that

Duplicate of #12547

**Closed by camsaul** 2020-07-16 17:25 UTC
Labels: Administration/Metadata & Sync, Database/SQLite, Priority:P2, Type:Bug
