### ISSUE TITLE
Postgres 'DATE' field off by 1 day

### ISSUE THREAD

**Issue by discobeta** [metabase/metabase#3914] opened 2016-12-09 20:14 UTC
### Postgres 'date' field off by one day

It seems that queries with field type 'DATE' are not processing the correct dates and are often off by 1 day while the same table defined with the field type 'TIMESTAMPTZ' works correctly.

We noticed that our query visualized the data incorrectly by displaying items that should be on the 30th of the month on the 29th of the month - off by 1 day.

To test this, we created two foo tables, the first with the 'DATE' field and the 2nd with the 'TIMESTAMPTZ' and loaded it up with the exact data, later we used MetaBase 0.21 (and 0.20.3) to query the two tables separately which returns the correct days for the table using the TIMESTAMPTZ field and the incorrect date (off by 1 day) for the table using 'DATE' field.

### Recreate Issue
<pre>

CREATE TABLE testdate1 (
 id SERIAL PRIMARY KEY NOT NULL,
 date DATE NOT NULL
);

CREATE TABLE testdate2 (
 id SERIAL PRIMARY KEY NOT NULL,
 date TIMESTAMPTZ NOT NULL
);

insert into testdate1 (date) values ('2016-12-6 13:00:00');
insert into testdate1 (date) values ('2016-12-7 14:00:00');
insert into testdate1 (date) values ('2016-12-8 15:00:00');
insert into testdate1 (date) values ('2016-12-9 16:00:00');

insert into testdate2 (date) values ('2016-12-6 13:00:00');
insert into testdate2 (date) values ('2016-12-7 14:00:00');
insert into testdate2 (date) values ('2016-12-8 15:00:00');
insert into testdate2 (date) values ('2016-12-9 16:00:00');

select * from testdate1;
1 Monday, December 5, 2016 7:00 PM
2 Tuesday, December 6, 2016 7:00 PM
3 Wednesday, December 7, 2016 7:00 PM
4 Thursday, December 8, 2016 7:00 PM
** notice the dates 5,6,7,8

select * from testdate2;
5 Tuesday, December 6, 2016 12:00 AM
6 Wednesday, December 7, 2016 12:00 AM
7 Thursday, December 8, 2016 12:00 AM
8 Friday, December 9, 2016 12:00 AM
** notice the dates 6,7,8,9
</pre>

### Details
Browser Version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36
OS: Metabase/Metabase Docker Image Version 0.21 (Also tested on v0.20.3)
DB: Postgres Redshift
Metabase: 0.21
Hosting: Kubernetes
Internal DB: MySQL

**Comment by camsaul** [comment] 2016-12-13 03:44
Hi @discobeta, did you set a Timezone in the admin panel?

**Comment by discobeta** [comment] 2016-12-13 04:23
@camsaul Yes, we did.

**Comment by discobeta** [comment] 2016-12-21 15:26
@camsaul Could this be the cause? (line 138 on https://github.com/metabase/metabase/blob/d404d831ff5c14231c174fd84503afcc2c2ff5e3/src/metabase/driver/postgres.clj)

"Postgres weeks start on Monday, so shift this date into the proper bucket and then decrement the resulting day"

**Comment by paoliniluis** [comment] 2021-03-21 01:26
This issue could be extremely related (if not the same) to https://github.com/metabase/metabase/issues/14294 which was closed recently, so if you could test it now @discobeta and see if it was solved it would be nice :)

**Comment by tsmacdonald** [comment] 2023-10-31 12:33
I can't reproduce this on master (pre-release of 48), so I'm marking this as fixed.

![image](https://github.com/metabase/metabase/assets/784417/e71fd925-6316-4ecf-9de7-f117f06de4bd)

**Closed by tsmacdonald** 2023-10-31 12:33 UTC
Labels: Type:Bug, Database/Postgres, .Correctness, Misc/Timezones, .Backend
