### ISSUE TITLE
"Cannot read properties" error when trying to replace a question

### ISSUE THREAD

**Issue by natashamathur** [metabase/metabase#34626] opened 2023-10-12 19:12 UTC
### Describe the bug

Even after the update I get this error when editing and saving a pre existing chart, and I need to save another one and archive the previous
![image (7)](https://github.com/metabase/metabase/assets/35498283/d47d98d3-f6f0-45c6-b17f-a82b60ad5c01)

### To Reproduce

1. Go to an existing dashboard
2. Click on an existing chart
3. Edit it
4. Try and replace the original chart with the new edited version
5. See error

### Expected behavior

Replace without an issue

### Information about your Metabase installation

```JSON
- latest Metabase version - 0.47.4
I saw that 1.47.4 is out but its not marked as latest.
```

### Severity

Need to edit dashboards for meeting tomorrow

**Comment by uladzimirdev** [comment] 2023-10-12 19:17
@natashamathur it would help us to react faster if you could provide an example using sample data

**Comment by natashamathur** [comment] 2023-10-12 19:24
@uladzimirdev I'm not sure what that means - there is an example of the error in the screenshot. I don't have any dashboards set up using the sample database so I'm not sure if I could re create the error.

**Comment by paoliniluis** [comment] 2023-10-12 19:59
It’s not clear how we can reproduce this

**Comment by paoliniluis** [comment] 2023-10-12 22:22
Probably a dupe of https://github.com/metabase/metabase/issues/34626

**Comment by paoliniluis** [comment] 2023-10-12 22:47
reopening, I just hit it on the sample db but can't repro consistently
![Uploading image.png…]()

**Comment by paoliniluis** [comment] 2023-10-12 22:47
No error in the console, backend returns 200
![image](https://github.com/metabase/metabase/assets/1711649/77081691-91f9-4392-b173-e4abfb7fc0a3)

**Comment by uladzimirdev** [comment] 2023-10-16 12:33
@paoliniluis what question configuration did you have with the error? I'm having hard time trying to reproduce it

**Comment by uladzimirdev** [comment] 2023-10-16 12:39
duplicate of https://github.com/metabase/metabase/issues/31766

**Comment by uladzimirdev** [comment] 2023-10-16 16:12
@natashamathur could you please tell us, which version did you upgrade from? also what kind of the chart, which visualziation type and did you go from the dashboard to chart to edit it and save with the modal where you made the screenshot from (with the error message)?

**Comment by paoliniluis** [comment] 2023-10-16 16:17
@uladzimirdev thanks

**Closed by paoliniluis** 2023-10-16 16:17 UTC
Labels: Type:Bug, Priority:P1, .Frontend, .Regression, .Team/42

**Comment by uladzimirdev** [comment] 2023-10-18 12:54
@natashamathur FYI we identified the issue and the fix should land in the next version

**Comment by Ravi9535** [comment] 2024-03-29 09:43
When I clicked on Save and it failed. 
Here is the log.
[log.log](https://github.com/metabase/metabase/files/14802336/log.log)
