### ISSUE TITLE
bug in line charts: several series but only 1 option to label them

### ISSUE THREAD

**Issue by rfr** [metabase/metabase#9344] opened 2019-01-30 02:32 UTC
After the latest upgrade I get a weird problem: if I add several series to a line chart, I get only 1 field to label which changes both lines (color and label). Please see the screenshot. Is that something going wrong on my installation or is it a bug? Thank you.

EDIT: this bug appear only if both series have the same type of view. In my example its a "Maximum of.."

![image](https://user-images.githubusercontent.com/1169589/51954219-af0e4b80-243f-11e9-948d-309412590f36.png)
![image](https://user-images.githubusercontent.com/1169589/51954228-b5042c80-243f-11e9-95ee-87cea7b7f9ef.png)

**Comment by flamber** [comment] 2019-01-30 15:39
Leave it open until I find the duplicate. Just in case someone finds this issue, then I would like to have a reference to somewhere.

**Comment by santaux** [comment] 2019-02-12 10:11
@flamber I have the same issue. And that's not only for line charts. The same thing for bar charts also.

for instance, when you add two questions on the same chart on the dashboard you see this:
![Screenshot](https://i.ibb.co/VmSRJpx/Screenshot-2019-02-12-at-13-03-24.png)

how can I resolve this issue? because as I understand this trick with custom expressions doesn't work for the dashboard or I am wrong?

**Comment by flamber** [comment] 2019-02-12 13:03
@santaux I cannot replicate your problem. Create a new issue and fill out the details and how to reproduce.

**Comment by flamber** [comment] 2019-02-25 20:57
@rfr I'm pretty sure this was fixed by #9350, which should be part of 0.32

**Comment by salsakran** [comment] 2019-04-10 05:15
this seems to be #9350 .

if it's not fixed by 0.32, chime in and I'll re-open.

**Closed by salsakran** 2019-04-10 05:15 UTC
