### ISSUE TITLE
Maximum call stack size exceeded opening a dashboard

### ISSUE THREAD

**Issue by pfinardi** [metabase/metabase#10127] opened 2019-06-11 07:13 UTC
browser: Chrome 74.0.3729.169 (Official Build) (64-bit) and Brave 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)
operating system: Ubuntu 18.04 LTS
databases: Postgres
Metabase version: 0.32.8
Metabase hosting environment: Docker
internal database: H2 (default)

Ciao,
I have obtain the message "Maximun call stack size exceeded" when I open a dashboard using Chrome or Brave. No problems with Firefox.
It didn't happen with the previous version 0.32.7.

![image](https://user-images.githubusercontent.com/12891452/59250906-cbf62f00-8c28-11e9-868d-8869657a7784.png)

![image](https://user-images.githubusercontent.com/12891452/59250918-d31d3d00-8c28-11e9-8ba7-4ce73737a639.png)

Thanks for your help

Paolo

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2019-06-11 19:28
Hi @pfinardi 
Do you have a zoom level different from 100%? If yes, then it might be duplicate of #6701

**Comment by pfinardi** [comment] 2019-06-12 09:11
Hi @flamber 
I found the #6701 but I don't use zoom. My zoom level is 100%

**Comment by CoreyScogin** [comment] 2019-06-14 21:53
I get this error consistently on OS X using a Chromium browser no matter what the zoom level as long as the viewport is a certain size. I haven't tested other sizes while holding the aspect ratio constant. I think it's related to the vertical size of the viewport.

Here are the steps I can use to replicate the issue:

1. Create a dashboard with graphs that extend down 12 rows.
2. In Chrome dev tools, set the viewport to 1886 x 1101.

**Comment by Vitiell0** [comment] 2019-10-04 13:56
I am constantly running into this issue as well. Has there been any updates related to a possible fix?

**Comment by awor** [comment] 2019-10-20 17:13
I had this problem on chrome with a public dashboard containing multiple pie charts which was embedded in another website (no matter what zoom level). I could fix it by increasing the height parameter in the embed code by 100px.

**Comment by bugo99iot** [comment] 2019-10-28 12:32
Same issue here. Chrome + Metabase 0.33.4

**Comment by gitim** [comment] 2019-11-26 18:25
Hi! I had the same issue, I submitted a pr with fix https://github.com/metabase/metabase/pull/11393

**Comment by paulrosenzweig** [comment] 2019-11-27 22:38
Fixed by #11393. I was unable to reproduce this with zooming my browser, so it's possible there were two separate issues at play. If anyone is still experiencing this after the next release, please reopen.

**Comment by Shadowsong27** [comment] 2020-02-19 09:34
I am seeing the same issue again, after upgrading to Metabase v0.34.2

![Screenshot 2020-02-19 at 5 29 16 PM](https://user-images.githubusercontent.com/12522657/74820809-9835e200-533d-11ea-9c17-d5fea8de5077.png)

Specs:
1. Browser: Version 79.0.3945.130 (Official Build) (64-bit)
2. OS: MacOS Catalina 10.15.3
3. Monitor: DELL U2414H Display 23.5-inch (1920 x 1080)

However, when I move the window from my monitor to my mbp screen, it works fine.
MBP: Built-in Display 13.3-inch (2560 x 1600)

Thanks.

**Comment by flamber** [comment] 2020-02-19 10:51
@Shadowsong27 
What's the size of the Chrome window?
Are you using zoom in Chrome?
Do you have any OS-level text zoom settings that are different between the displays?
Which type of questions do you have on the dashboard? Can you reproduce with just a single table question, or is it a specific combination.
As you can see, we have not been able to reproduce this, so it's really hard to fix the problem.

**Comment by andreychirikba** [comment] 2020-03-03 22:31
I have the same:

`Error getting setting table.columns TypeError: Cannot read property 'cols' of undefined
    at Object.getDefault (app-main.bundle.js?a10c9974cc03fead96be:5)
    at g (app-main.bundle.js?a10c9974cc03fead96be:5)
    at t.getComputedSettings (app-main.bundle.js?a10c9974cc03fead96be:5)
    at h (app-main.bundle.js?a10c9974cc03fead96be:5)
    at t.value (app-main.bundle.js?a10c9974cc03fead96be:5)
    at t.value (app-main.bundle.js?a10c9974cc03fead96be:5)
    at c.performInitialMount (vendor.bundle.js?a10c9974cc03fead96be:1)
    at c.mountComponent (vendor.bundle.js?a10c9974cc03fead96be:1)
    at Object.mountComponent (vendor.bundle.js?a10c9974cc03fead96be:1)
    at c.performInitialMount (vendor.bundle.js?a10c9974cc03fead96be:1)
g @ app-main.bundle.js?a10c9974cc03fead96be:5
app-main.bundle.js?a10c9974cc03fead96be:5 Error getting setting table._cell_background_getter TypeError: Cannot read property 'rows' of undefined
    at Object.getValue (app-main.bundle.js?a10c9974cc03fead96be:5)
    at g (app-main.bundle.js?a10c9974cc03fead96be:5)
    at t.getComputedSettings (app-main.bundle.js?a10c9974cc03fead96be:5)
    at h (app-main.bundle.js?a10c9974cc03fead96be:5)
    at t.value (app-main.bundle.js?a10c9974cc03fead96be:5)
    at t.value (app-main.bundle.js?a10c9974cc03fead96be:5)
    at c.performInitialMount (vendor.bundle.js?a10c9974cc03fead96be:1)
    at c.mountComponent (vendor.bundle.js?a10c9974cc03fead96be:1)
    at Object.mountComponent (vendor.bundle.js?a10c9974cc03fead96be:1)
    at c.performInitialMount (vendor.bundle.js?a10c9974cc03fead96be:1)
g @ app-main.bundle.js?a10c9974cc03fead96be:5
app-main.bundle.js?a10c9974cc03fead96be:5 RangeError: Maximum call stack size exceeded
    at c.updateComponent (vendor.bundle.js?a10c9974cc03fead96be:1)
    at c.receiveComponent (vendor.bundle.js?a10c9974cc03fead96be:1)
    at Object.receiveComponent (vendor.bundle.js?a10c9974cc03fead96be:1)
    at c._updateRenderedComponent (vendor.bundle.js?a10c9974cc03fead96be:1)
    at c._performComponentUpdate (vendor.bundle.js?a10c9974cc03fead96be:1)
    at c.updateComponent (vendor.bundle.js?a10c9974cc03fead96be:1)
    at c.receiveComponent (vendor.bundle.js?a10c9974cc03fead96be:1)
    at Object.receiveComponent (vendor.bundle.js?a10c9974cc03fead96be:1)
    at Object.updateChildren (vendor.bundle.js?a10c9974cc03fead96be:1)
    at Z._reconcilerUpdateChildren (vendor.bundle.js?a10c9974cc03fead96be:1)
(anonymous) @ app-main.bundle.js?a10c9974cc03fead96be:5
17vendor.bundle.js?a10c9974cc03fead96be:1 Uncaught Invariant Violation: Minified React error #44; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=44 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at e.exports (https://hostname.redacted.com/app/dist/vendor.bundle.js?a10c9974cc03fead96be:1:285930)
    at Object.e.exports [as findDOMNode] (https://hostname.redacted.com/app/dist/vendor.bundle.js?a10c9974cc03fead96be:1:2248145)
    at d.value (https://hostname.redacted.com/app/dist/app-main.bundle.js?a10c9974cc03fead96be:5:234493)
    at n._updateSize (https://hostname.redacted.com/app/dist/app-main.bundle.js?a10c9974cc03fead96be:5:233920)`

- Chrome Version 80.0.3987.122 (Official Build) (64-bit)
- MacOS Catalina 10.15.3
- MacBook Air

No special graphics settings.

**Comment by flamber** [comment] 2020-03-03 23:05
@andreychirikba It would be awesome if you could provide steps-to-reproduce, since we haven't been able to reproduce this issue. And by reproducible, I mean it should also create the error if you try on your friends/coworkers computer (different from yours).

**Comment by andreychirikba** [comment] 2020-03-03 23:16
@flamber, that's the problem: on my coworker's Mac with almost identical config (Chrome 79.0.3945.130 and after upgrading to 80.0.3987.132) it's working just fine. It's only consistently producing this error on a single dashboard on my Mac, not on any other dashboards.

**Comment by blair-anson** [comment] 2020-03-23 06:14
@andreychirikba I also had the same problem today on metabase v0.34.3, but resolved it by clearing the browser data (cookies, localstorge, application cache etc..).
While you have the current Chrome browser open on your metabase site, if you open the Chrome developer tools -> Application -> Clear Storage -> Clear site data

That will clear locally cached data from metabase, and not wipe out your other cookies etc.

**Comment by RoyHP** [comment] 2020-04-23 15:29
I'm having this problem as well. Metabase v0.35.3, macOS 10.15.4 Catalina, 4k display scaled in macOS to look like 2560x1440 and Chrome Version 81.0.4044.122 (Official Build) (64-bit). The window is mostly fullscreen - stopping vertically above the task bar at the bottom.

Every time I load the dashboard the page either shows me the "Call stack size exceeded error" or it becomes unresponsive and I have to close the tab. Because it becomes unresponsive I can't even open the error console. It also doesn't let me take a heap snapshot.

**Comment by RoyHP** [comment] 2020-04-23 16:20
After waiting for about 10 minutes, it finally loaded but gave a react error - screenshot below. Sometimes it will give me the callstack error, sometimes this.
<img width="2556" alt="Screen Shot 2020-04-23 at 12 19 24 PM" src="https://user-images.githubusercontent.com/1066439/80123373-d083b780-855c-11ea-8df0-c8b16bd2c995.png">

**Comment by RoyHP** [comment] 2020-04-23 16:53
Here is the call stack error
<img width="2556" alt="Screen Shot 2020-04-23 at 12 52 37 PM" src="https://user-images.githubusercontent.com/1066439/80126716-6a4d6380-8561-11ea-8c09-a6ba01bdc89b.png">

**Comment by paulrosenzweig** [comment] 2020-05-01 23:34
@RoyHP thanks for providing those details of your setup! Unfortunately, even trying for a while with a nearly identical setup, I'm still unable to reproduce it. I'm guessing it has to do with the specific questions on the dashboard. Are you able to isolate any one from the problematic dashboard? e.g. maybe certain types of legends or certain height/width ratios cause this. Thanks!

**Comment by RoyHP** [comment] 2020-05-02 19:34
@paulrosenzweig I noticed that when I resized the browser window to be slightly smaller, it stopped happening entirely. It also doesn't happen on my macbook pro's internal screen - only on the external monitor. I'm not sure if that's a result of scaling or just the smaller viewport.

When I see it happen again I will try to determine the exact viewport dimensions/scaling.

**Comment by jankatins** [comment] 2020-11-24 09:21
Here is one case in Chrome on mac on metabase 0.36.6:

```
app-main.bundle.js?b33c92a4486dd445d864:5 Error getting setting table.columns TypeError: Cannot read property 'cols' of undefined
    at Object.getDefault (app-main.bundle.js?b33c92a4486dd445d864:5)
    at g (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.getComputedSettings (app-main.bundle.js?b33c92a4486dd445d864:5)
    at h (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.value (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.value (app-main.bundle.js?b33c92a4486dd445d864:5)
    at c.performInitialMount (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c.mountComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at Object.mountComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c.performInitialMount (vendor.bundle.js?b33c92a4486dd445d864:1)
g @ app-main.bundle.js?b33c92a4486dd445d864:5
app-main.bundle.js?b33c92a4486dd445d864:5 Error getting setting table._cell_background_getter TypeError: Cannot read property 'rows' of undefined
    at Object.getValue (app-main.bundle.js?b33c92a4486dd445d864:5)
    at g (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.getComputedSettings (app-main.bundle.js?b33c92a4486dd445d864:5)
    at h (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.value (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.value (app-main.bundle.js?b33c92a4486dd445d864:5)
    at c.performInitialMount (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c.mountComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at Object.mountComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c.performInitialMount (vendor.bundle.js?b33c92a4486dd445d864:1)
g @ app-main.bundle.js?b33c92a4486dd445d864:5
app-main.bundle.js?b33c92a4486dd445d864:5 Error getting setting table.columns TypeError: Cannot read property 'cols' of undefined
    at Object.getDefault (app-main.bundle.js?b33c92a4486dd445d864:5)
    at g (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.getComputedSettings (app-main.bundle.js?b33c92a4486dd445d864:5)
    at h (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.value (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.value (app-main.bundle.js?b33c92a4486dd445d864:5)
    at c.performInitialMount (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c.mountComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at Object.mountComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c.performInitialMount (vendor.bundle.js?b33c92a4486dd445d864:1)
g @ app-main.bundle.js?b33c92a4486dd445d864:5
app-main.bundle.js?b33c92a4486dd445d864:5 Error getting setting table._cell_background_getter TypeError: Cannot read property 'rows' of undefined
    at Object.getValue (app-main.bundle.js?b33c92a4486dd445d864:5)
    at g (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.getComputedSettings (app-main.bundle.js?b33c92a4486dd445d864:5)
    at h (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.value (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.value (app-main.bundle.js?b33c92a4486dd445d864:5)
    at c.performInitialMount (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c.mountComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at Object.mountComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c.performInitialMount (vendor.bundle.js?b33c92a4486dd445d864:1)
g @ app-main.bundle.js?b33c92a4486dd445d864:5
app-main.bundle.js?b33c92a4486dd445d864:5 Error getting setting table.columns TypeError: Cannot read property 'cols' of undefined
    at Object.getDefault (app-main.bundle.js?b33c92a4486dd445d864:5)
    at g (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.getComputedSettings (app-main.bundle.js?b33c92a4486dd445d864:5)
    at h (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.value (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.value (app-main.bundle.js?b33c92a4486dd445d864:5)
    at c.performInitialMount (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c.mountComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at Object.mountComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c.performInitialMount (vendor.bundle.js?b33c92a4486dd445d864:1)
g @ app-main.bundle.js?b33c92a4486dd445d864:5
app-main.bundle.js?b33c92a4486dd445d864:5 Error getting setting table._cell_background_getter TypeError: Cannot read property 'rows' of undefined
    at Object.getValue (app-main.bundle.js?b33c92a4486dd445d864:5)
    at g (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.getComputedSettings (app-main.bundle.js?b33c92a4486dd445d864:5)
    at h (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.value (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.value (app-main.bundle.js?b33c92a4486dd445d864:5)
    at c.performInitialMount (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c.mountComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at Object.mountComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c.performInitialMount (vendor.bundle.js?b33c92a4486dd445d864:1)
g @ app-main.bundle.js?b33c92a4486dd445d864:5
app-main.bundle.js?b33c92a4486dd445d864:5 Error getting setting table.columns TypeError: Cannot read property 'cols' of undefined
    at Object.getDefault (app-main.bundle.js?b33c92a4486dd445d864:5)
    at g (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.getComputedSettings (app-main.bundle.js?b33c92a4486dd445d864:5)
    at h (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.value (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.value (app-main.bundle.js?b33c92a4486dd445d864:5)
    at c.performInitialMount (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c.mountComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at Object.mountComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c.performInitialMount (vendor.bundle.js?b33c92a4486dd445d864:1)
g @ app-main.bundle.js?b33c92a4486dd445d864:5
app-main.bundle.js?b33c92a4486dd445d864:5 Error getting setting table._cell_background_getter TypeError: Cannot read property 'rows' of undefined
    at Object.getValue (app-main.bundle.js?b33c92a4486dd445d864:5)
    at g (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.getComputedSettings (app-main.bundle.js?b33c92a4486dd445d864:5)
    at h (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.value (app-main.bundle.js?b33c92a4486dd445d864:5)
    at t.value (app-main.bundle.js?b33c92a4486dd445d864:5)
    at c.performInitialMount (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c.mountComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at Object.mountComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c.performInitialMount (vendor.bundle.js?b33c92a4486dd445d864:1)
g @ app-main.bundle.js?b33c92a4486dd445d864:5
app-main.bundle.js?b33c92a4486dd445d864:5 RangeError: Maximum call stack size exceeded
    at app-main.bundle.js?b33c92a4486dd445d864:5
    at Array.map (<anonymous>)
    at t.value (app-main.bundle.js?b33c92a4486dd445d864:5)
    at c._renderValidatedComponentWithoutOwnerOrContext (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c._renderValidatedComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c._updateRenderedComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c._performComponentUpdate (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c.updateComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at c.receiveComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
    at Object.receiveComponent (vendor.bundle.js?b33c92a4486dd445d864:1)
(anonymous) @ app-main.bundle.js?b33c92a4486dd445d864:5
9vendor.bundle.js?b33c92a4486dd445d864:1 Uncaught Invariant Violation: Minified React error #44; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=44 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at e.exports (https://metabase.live.zenjob.io/app/dist/vendor.bundle.js?b33c92a4486dd445d864:1:317976)
    at Object.e.exports [as findDOMNode] (https://metabase.live.zenjob.io/app/dist/vendor.bundle.js?b33c92a4486dd445d864:1:2527194)
    at d.value (https://metabase.live.zenjob.io/app/dist/app-main.bundle.js?b33c92a4486dd445d864:5:206445)
    at n._updateSize (https://metabase.live.zenjob.io/app/dist/app-main.bundle.js?b33c92a4486dd445d864:5:205872)
```

The problem goes away when I do the refresh after opening "Inspect" (all but the RangeError: Maximum call stack size exceeded" error remain) and also when I change the tab window size...

**Comment by flamber** [comment] 2020-11-24 09:26
@jankatins Try upgrading to latest release 0.37.2, which has a lot of changes to dashboards, and see if you can reproduce there.

**Comment by mr-ssi** [comment] 2021-02-18 11:39
Hi,

issue still exists in v0.38.0
Newest Chrome on Windows, Linux Fedora 31-33 (all across the company)

This is a dashboard with pie-charts, bars, tables (one with pivot), text fields, line charts... (no map)
When opening on my 24" screen -> Fails with 100% Zoom -> works with 90% or less and 110% or more
When opening on my 17" Laptop screen -> works always

**Comment by flamber** [comment] 2021-02-18 11:53
@mr-ssi So basically the opposite of #6701? Interesting. And that you have the problem on Windows and Linux as well.
It must have something to do with scaling/DPI/etc on your external screen.
Very frustrating that we haven't been able to reproduce.

**Comment by mr-ssi** [comment] 2021-02-18 12:31
Maybe it helps to share my screen data...

My 2 external screens:
Iiyama ProLite XUB2492HSU (ModelNo.: PL2492H)
- DP-3.1 connected 1920x1080+0+810 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+  59.94    50.00
- DP-3.2 connected 1920x1080+1920+810 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+  59.94    50.00
My Laptop screen
Lenovo P50
- DP-4 connected primary 1440x810+1232+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1920x1080     60.02*+  48.00

[I've my 2 big external screens next to each other and my laptop centered above]

I work on Fedora 33, Chrome is currently 76.0.3809.132 (64-bit)

**Comment by renankw** [comment] 2021-02-23 13:50
I upgraded my development instance to version 0.38.0.1 and started to experience the same issue.
There are some dashboards I copied from production just to confirm everything will work on the new version and they're not opening.

I'm using Chrome 88.0.4324.182 on Windows 10, two 1080p Dell monitors.

If I zoom the page to 90% or 110% the problem doesn't happen. If I resize the window to any size with 100% zoom it doesn't happen too. 

This issue does not happen on chromium Edge. I downloaded the last version of open-source Chromium (90.0.4427.0) and the problem didn't happen too, which is interesting.

**Comment by renankw** [comment] 2021-02-23 16:54
I was able to reproduce the issue creating a dashboard with three questions, resizing them to 7 x 5 and showing the bookmarks bar.

OK: new dashboard, three questions in original size, no bookmarks bar
![1](https://user-images.githubusercontent.com/12502847/108876888-78369f80-75dd-11eb-9048-b9e9d1079f26.png)

OK: resizing one question to 7x5
![2](https://user-images.githubusercontent.com/12502847/108877165-bb910e00-75dd-11eb-96c6-fb8ec54012b0.png)

OK: resizing all to 7 x 5
![3](https://user-images.githubusercontent.com/12502847/108877345-e5e2cb80-75dd-11eb-9540-a3dd4481c90b.png)

NOK: showing bookmarks bar. The page instantly freezes and reloading it doesn't work.
![4](https://user-images.githubusercontent.com/12502847/108877819-5b4e9c00-75de-11eb-94bc-55251a77ddf7.png)

Hope this helps :)

**Comment by dannyeuu** [comment] 2021-03-16 22:16
With us on version v0.37.9 received from one of our user the same error in a print, I cannot reproduce. @flamber I saw that was #6701 but are not the case here.

**Comment by jakobskytte** [comment] 2021-03-21 12:23
Getting this same error
Metabase v0.38.2 
Windows 10
Chrome Version 89.0.4389.90 (Official Build) (64-bit)

![Capture](https://user-images.githubusercontent.com/25202811/111904669-5ac3ec80-8a48-11eb-869c-2b37777b1754.PNG)

**Comment by eabdollahian** [comment] 2023-11-12 07:20
I see it again in 0.47.1 in Map charts.
chrome: Version 112.0.5615.165 (Official Build) (64-bit)
os: Ubuntu 22.04
db: postgresql
![image](https://github.com/metabase/metabase/assets/9780002/f9a8b092-3679-4c2d-aafe-9db81a912ee4)

**Comment by paoliniluis** [comment] 2023-11-13 00:54
@eabdollahian can you please provide us with the repro steps? specifically how you build the map, zoom levels and such

**Comment by eabdollahian** [comment] 2023-11-13 07:50
@paoliniluis We get the geojson from https://github.com/evansd/uk-ceremonial-counties/tree/master and used the github url as the input of metabase "URL for the GeoJSON file you want to use". We didn't set zoom. I think this default value.
I read somewhere this:

> If you need a map that focuses on a specific region, you may want to upload a custom GeoJSON map. We recommend a GeoJSON file size of 5MB or less.

But didn't use custom GeoJSON map.

**Comment by paoliniluis** [comment] 2024-11-10 19:00
I'm closing this as it has not been reported anymore, which is a huge win

**Closed by paoliniluis** 2024-11-10 19:00 UTC
Labels: Type:Bug, Priority:P2, Reporting/Dashboards, .Unable to Reproduce, Browser:Chrome, Difficulty:Hard, .Frontend, .Team/DashViz, .LongTerm
