### ISSUE TITLE
Error on 24-hour clock representation: 12.20 AM is showed as 24.20

### ISSUE THREAD

**Issue by marcellovetro** [metabase/metabase#11765] opened 2020-01-21 16:20 UTC
**Describe the bug**
Double Error on 24-hour clock representation: 
In some cases 12.20 AM is showed as 24.20 and in other cases 0:20 AM is showed as 24.20 !!!

**To Reproduce**
1. Go to 'Ask a question'
2. Use Custom Query on MySQL Database
3. write the query:
`select CAST('2020-01-01 0:20:00' as datetime) `
4. Open the settings panel and Set Time style as "24-hour "
5. See error: Showed as January 1, 2020, 24:20

**Expected behavior**
It have to show "January 1, 2020, 0:20"

**Screenshots**
![Screenshot](https://www.olomedia.com/wp-content/uploads/res/debug2020-01-21_17-09-43.png)

**Information about your Metabase Installation:**
Diagnostic Info:
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.15.0-74-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "run-mode": "prod",
    "version": {
      "date": "2020-01-13",
      "tag": "v0.34.1",
      "branch": "release-0.34.x",
      "hash": "265695c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Very annoing problem!

**Comment by dacort** [comment] 2020-01-21 23:10
Slightly related to #11394

**Comment by flamber** [comment] 2020-02-05 14:51
Duplicate of #9538

**Closed by flamber** 2020-02-05 14:51 UTC
Labels: .Correctness, .Duplicate, Customization/Formatting, Priority:P2, Type:Bug
