### ISSUE TITLE
Dashboard Filter: missing drop-down list for category in graphs with Join

### ISSUE THREAD

**Issue by ohld** [metabase/metabase#12373] opened 2020-04-22 11:02 UTC
**Describe the bug**
Drop-down list for category dashboard filter disappears when I select the filter column in table that was joined in graph.

![image](https://user-images.githubusercontent.com/5613295/79973428-39592a00-84a0-11ea-922c-004bba59459b.png)

**To Reproduce**
1. Create a dashboard
2. Chose a category column in your data
3. Add 2 graphs that have that category column in their original (base) table and when this table is left-joined to some other table
3. Create Dashboard filter for that category and choose this category in dashboard filter settings for each graph
4. Now the drop-down list disappears. 

**Expected behavior**
The drop-down list still available even in the case when the filter column was joined in the query.

**Screenshots**
When I create a category dashboard filter and select only columns to be filtered in the original SQL of the graphs - the drop-down list is available.
![image](https://user-images.githubusercontent.com/5613295/79973987-2d219c80-84a1-11ea-8c09-407e377847e8.png)
![image](https://user-images.githubusercontent.com/5613295/79974009-37dc3180-84a1-11ea-9f49-7d42b03f6c8f.png)

But when I add the filter by this column that was left joined to some table:
![image](https://user-images.githubusercontent.com/5613295/79974094-5c380e00-84a1-11ea-8133-0d35c89bf9cf.png)
the drop-down list for that filter disappears
![image](https://user-images.githubusercontent.com/5613295/79974133-6eb24780-84a1-11ea-8174-6611922cc352.png)

**Information about your Metabase Installation:**
latest - just updated. Run via docker.

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.15.0-91-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-21",
      "tag": "v0.35.3",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": "Europe/Moscow"
    }
  }
}
**Severity**
medium

**Comment by flamber** [comment] 2020-04-22 11:29
Duplicate of #12250 - upvote by clicking :+1: on the first post

**Closed** 2020-04-22 11:30 UTC
Labels: .Duplicate
