### ISSUE TITLE
Not able to open Data Ref with fresh install

### ISSUE THREAD

**Issue by simonflore** [metabase/metabase#3618] opened 2016-10-18 14:45 UTC
We've done a fresh install, but the page Data Reference gives problems on the api call /api/getting_started. It gives me this error, any idea?

{"message":"ERROR: syntax error at or near \")\"\n  Position: 135","stacktrace":["db$query.invokeStatic(db.clj:511)","db$query.doInvoke(db.clj:507)","db$simple_select.invokeStatic(db.clj:572)","db$simple_select.invoke(db.clj:564)","db$select.invokeStatic(db.clj:816)","db$select.doInvoke(db.clj:810)","api.getting_started$fn__23374$fn__23375.invoke(getting_started.clj:36)","api.common.internal$wrap_catch_api_exceptions.invokeStatic(internal.clj:220)","api.common.internal$wrap_catch_api_exceptions.invoke(internal.clj:217)","api.getting_started$fn__23374.invokeStatic(getting_started.clj:19)","api.getting_started$fn__23374.invoke(getting_started.clj:19)","middleware$enforce_authentication$fn__30557.invoke(middleware.clj:84)","api.routes$fn__30669.invokeStatic(routes.clj:46)","api.routes$fn__30669.invoke(routes.clj:46)","routes$fn__31329.invokeStatic(routes.clj:24)","routes$fn__31329.invoke(routes.clj:24)","middleware$log_api_call$fn__30645$fn__30647.invoke(middleware.clj:275)","db$_do_with_call_counting.invokeStatic(db.clj:447)","db$_do_with_call_counting.invoke(db.clj:441)","middleware$log_api_call$fn__30645.invoke(middleware.clj:274)","middleware$add_security_headers$fn__30604.invoke(middleware.clj:209)","middleware$bind_current_user$fn__30561.invoke(middleware.clj:104)"]}

- Chrome 53.0
- Your operating system: (macOS Sierra)
- Your databases: MySQL 
- Metabase version: 0.20
- Metabase hosting environment: Elastic Beanstalk with Docker
- Metabase internal database: Postgres

How to reproduce?: install fresh Metabase and go to Data Reference after connecting a MySQL Database.

**Comment by tlrobinson** [comment] 2016-10-18 17:01
Thank you. I believe this is a duplicate of #3571 which will be fixed in 0.20.0 shortly.

**Closed by tlrobinson** 2016-10-18 17:01 UTC
