### ISSUE TITLE
Sorting by metric causes an error "Column sum does not exist"

### ISSUE THREAD

**Issue by asusmsk** [metabase/metabase#8621] opened 2018-10-03 08:32 UTC
- Your browser and the version: Chrome 69.0.3497.100
- Your operating system: Ubuntu 16.03 LTS
- Your databases: Vertica
- Metabase version: 0.30.3
- Metabase hosting environment: Docker
- Metabase internal database: H2 (default)

***Repeatable steps to reproduce the issue***
1. Create a metric for Table1 (we use Sum((field1 / 10000) * field2 * field3) with a name "Metric1"
2. Make a new question for Table1 with View = "Metric1"
and  "Grouped by" = Field4
3. Click "Get answer" 
--> Result: the table with your metric values is displayed. 
4. Click on column "Metric1" and choose "Descending". 

***Expected**:*
- the table is sorted by descending "Metric1" values

***Actual**:*
- an error is dislayed: 
`[Vertica][VJDBC](2624) ERROR: Column "sum" does not exist`

**Comment by mazameli** [comment] 2018-10-04 23:30
This might be an issue specifically with Vertica. I wasn't able to reproduce this on the sample dataset on master. If you try this on the sample dataset are you seeing this behavior?

**Comment by steinmann321** [comment] 2019-03-05 14:09
This is reproducable for me as well in MySQL on Sample Dataset. Steps to reproduce:

- Create a metric with a cusom expression
- **Give this metric a name**. _If you leave the name blank the error does not appear_
- Ask a question on this metric, grouping by some random column
- Click the column header of our metric and select a sort

![image](https://user-images.githubusercontent.com/10723267/53810992-96221a00-3f58-11e9-8f51-2bb34d53067c.png)


- Browser: Chrome/Firefox/IE
- OS: Windows 10
- Database: MySQL 5.7
- Metabase version: 0.31.2
- Metabase hosting environment: Docker and Local standalone jar
- Metabase internal database: H2

**Comment by PauloHFM** [comment] 2019-06-13 18:37
Not sure is related but...
This happens to me EVERY time I try to order a "View" column in Custom Questions.
Anyone knows?
The query shows tha everytime I name a column (in Custom Questions.), the name that it receives is "named". 

![image](https://user-images.githubusercontent.com/38223133/59458373-b0d61b80-8df0-11e9-8111-30c4dc5ec755.png)
![image](https://user-images.githubusercontent.com/38223133/59458478-e418aa80-8df0-11e9-8ad0-b777f9e06451.png)

**Comment by flamber** [comment] 2020-05-27 15:29
I cannot reproduce on 0.35.3 - I think it was fixed in 0.33

**Closed by flamber** 2020-05-27 15:29 UTC
Labels: Administration/Metrics & Segments, Priority:P2, Type:Bug
