### ISSUE TITLE
Waterfall visualization is not working with unaggregated data

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#15465] opened 2021-04-02 18:03 UTC
**Describe the bug**
Waterfall visualization is not working with unaggregated data

**To Reproduce**
1) Run the following SQL
```
SELECT parsedatetime('2020-01-01', 'yyyy-MM-dd') AS "d", 1 AS "c" UNION ALL
SELECT parsedatetime('2020-01-01', 'yyyy-MM-dd') AS "d", 2 AS "c" UNION ALL
SELECT parsedatetime('2020-01-02', 'yyyy-MM-dd') AS "d", 3 AS "c"
```
2) Select "Waterfall" visualization - blank
![image](https://user-images.githubusercontent.com/1447303/133769482-10e80616-b9d5-4220-8c64-1bbd5bebdd69.png)

**Expected behavior**
A waterfall chart is shown

**Actual behavior**
Visualization is not shown and there is an error in console: `TypeError: Cannot read property 'data' of undefined`

**Comment by flamber** [comment] 2021-04-02 18:17
Duplicate of #15152 ?

**Comment by alxnddr** [comment] 2021-04-02 21:01
@flamber looks like it is different. I assume that Waterfall charts should work in this case as Line charts do

**Comment by flamber** [comment] 2021-04-03 07:11
When I follow the simple steps, then I cannot reproduce (0.38.3 or master) - only if I have done other settings to Line, like adding another breakout, or if the query contains extra columns.
![image](https://user-images.githubusercontent.com/1447303/113471445-8f7a6f80-945c-11eb-9c93-4c887ec413a5.png)

**Comment by alxnddr** [comment] 2021-04-03 13:26
@flamber sorry, because of the wrong markdown the first line of the query was not visible. I have updated the query

**Closed** 2021-09-21 16:15 UTC
Labels: Type:Bug, Priority:P2, .Frontend, Visualization/Charts, .Reproduced
