### ISSUE TITLE
Can't upload the Service account JSON on metabase mac app

### ISSUE THREAD

**Issue by sajkamal** [metabase/metabase#15272] opened 2021-03-21 13:51 UTC
**Describe the bug**
The Service account JSON button upload is not operations

**Logs**
{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko)",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+9-202002041938",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+9-202002041938",
    "os.name": "Mac OS X",
    "os.version": "10.15.5",
    "user.language": "en",
    "user.timezone": "Asia/Riyadh"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "osx",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-03-17",
      "tag": "v0.38.2",
      "branch": "release-x.38.x",
      "hash": "91f0ed6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**To Reproduce**

**Expected behavior**

**Screenshots**

**Severity**
High

**Additional context**

**Metabase Diagnostic Info**

**Comment by flamber** [comment] 2021-03-21 18:33
Duplicate of #15075

**Closed by flamber** 2021-03-21 18:33 UTC
