### ISSUE TITLE
Dashboard gives error when using the public shared link

### ISSUE THREAD

**Issue by turran** [metabase/metabase#20550] opened 2022-02-16 12:48 UTC
**Describe the bug**
A dashboard works correctly using the internal metabase link, but when seeing the exact same dashboard through the public link, it gives an error "An error occurred" with no further description.

**Logs**
`TypeError: Cannot read properties of undefined (reading 'source-query')
    at n.value (app-public.bundle.js:2)
    at app-public.bundle.js:2
    at l (app-public.bundle.js:2)
    at n.value (app-public.bundle.js:2)
    at n.value (app-public.bundle.js:2)
    at app-public.bundle.js:2
    at l (app-public.bundle.js:2)
    at n.value (app-public.bundle.js:2)
    at n.value (app-public.bundle.js:2)
    at c (app-public.bundle.js:2)
(anonymous)	@	PublicDashboard.jsx:85`

**To Reproduce**
Is kind of hard, it does not happen on every dashboard, just in some, and don't know how to track it.

**Expected behavior**
The public dashboard should be visible

**Information about your Metabase Installation:**
Version 0.42. On previous release, this was not happening.

You can get this information by going to Admin -> Troubleshooting.
`{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14+9",
    "os.name": "Linux",
    "os.version": "5.11.0-22-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.24"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-08",
      "tag": "v0.42.0",
      "branch": "release-x.42.x",
      "hash": "de1264e"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}`

**Severity**
This breaks any usage of sharing the dashboards with the team or stakeholders.

**Comment by flamber** [comment] 2022-02-16 12:51
Duplicate of #20493

**Closed by flamber** 2022-02-16 12:51 UTC
Labels: Type:Bug, .Needs Triage
