### ISSUE TITLE
Impossible to use saved questions with filters in SQL queries

### ISSUE THREAD

**Issue by maximepvrt** [metabase/metabase#13058] opened 2020-08-03 14:16 UTC
My question (with sample dataset) : 
![Capture d’écran 2020-08-03 à 16 01 35](https://user-images.githubusercontent.com/1840026/89191947-ed8c4580-d5a3-11ea-8248-4e648593c1cd.png)

my SQL question error :
![Capture d’écran 2020-08-03 à 16 02 37](https://user-images.githubusercontent.com/1840026/89192068-1f051100-d5a4-11ea-9ce4-fbde33d02a34.png)

This bug demo was performed on this environment
```
{
  "browser-info": {
    "language": "fr",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko)",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+9-202002041938",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+9-202002041938",
    "os.name": "Mac OS X",
    "os.version": "10.15.6",
    "user.language": "fr",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "osx",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-07-21",
      "tag": "v0.36.0",
      "branch": "release-0.36.x",
      "hash": "b31049f"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

```
Same bug with v0.36.2

**Comment by maximepvrt** [comment] 2020-08-03 14:20
same as #12236

**Comment by flamber** [comment] 2020-08-03 14:47
Duplicate of #12236

**Closed by flamber** 2020-08-03 14:47 UTC
Labels: .Needs Triage, Type:Bug
