### ISSUE TITLE
Dashboard is not updating query results

### ISSUE THREAD

**Issue by nautilus28** [metabase/metabase#13117] opened 2020-08-14 16:58 UTC
The left of the screenshot shows 4 results for the question, but on the right, it shows that there is no data for the query.

<img width="1644" alt="Screenshot 2020-08-14 at 17 47 09" src="https://user-images.githubusercontent.com/4472857/90273287-a2e9b380-de56-11ea-9cc2-712e3a748dee.png">

It seems that the query results are not updated in the dashboard.

Also, there are two frontend errors showing in the Console tab:

`Error getting setting table.columns TypeError: Cannot read property 'cols' of undefined`

`Error getting setting table._cell_background_getter TypeError: Cannot read property 'rows' of undefined`

`{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.6+10-post-Debian-1bpo91",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.6+10-post-Debian-1bpo91",
    "os.name": "Linux",
    "os.version": "4.9.0-7-amd64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "exasol",
      "postgres",
      "bigquery",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.16"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-08-13",
      "tag": "v0.35.4",
      "branch": "v0.35.4",
      "hash": "fcb99a5b"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}`

**Comment by flamber** [comment] 2020-08-14 17:23
Hi @nautilus28 
It would close to impossible to fix this without reproducible steps with a non-custom driver.
One of the queries looks like it's failing with a non-200 error, so there should be a stacktrace.
There has been a lot of changes since 0.35.4, so I would recommend that you test with the latest release.

**Comment by nautilus28** [comment] 2020-08-14 20:05
The behaviour I described is purely on frontend side, so it doesn't matter what drivers we use.

the non-200 error was because I refreshed the page, to the query was cancelled.

Okay, we will upgrade to v0.36 and see how it goes.

**Comment by flamber** [comment] 2020-08-14 20:22
@nautilus28 Okay, but then you should be able to reproduce with Sample Dataset without any problems.
I use many errors every day to reproduce problems with no clear steps, but I cannot reproduce this issue, so you need to provide a lot more information.

**Comment by flamber** [comment] 2020-08-20 13:39
Closing, but please comment with steps to reproduce if this is still happening on 0.36.4 or newer versions.

**Closed by flamber** 2020-08-20 13:39 UTC
Labels: .Need More Info, .Unable to Reproduce, Type:Bug
