### ISSUE TITLE
Changing column visibility/order in GUI questions can cause inconsistency

### ISSUE THREAD

**Issue by urkle** [metabase/metabase#22563] opened 2022-05-09 21:14 UTC
**Describe the bug**
I built a report today that has 6 "Grouped" fields (only a count summary) and 4 custom expression fields (to coerce an encoded integer into a dotted version) 

However, when trying to hide some of the columns (e.g the columns used to produce the custom expressions) it hides ALL of the grouped columns except the first one.

**Logs**
There are no logs generated around this error .  I encountered the error on metabase 0.42.0 AND 0.43.0

**To Reproduce**
1) Create a question inner joining two tables and grouping by 6 columns (all from the second table), and add a count summary.
2) create single custom expression. 
3) visualize the question
4) try to hide one of the grouped columns.  notice ALL the columns are hidden.

**Expected behavior**
Keep some of the grouped columns (but hide others) and keep one of the custom expressions (and hide the others).

**Partial workaround / more info**
Now, if I switch the table order so that my main table is where my grouping columns are from. Then I do not have any issues.
However the columns ARE listed two times still.

**Screenshots**
1) column settings initial (no column adjustments).. Note how the columns are showing up in the "more columns" when they should not.
<img width="320" alt="image" src="https://user-images.githubusercontent.com/101123/167498734-117ee0d5-ae70-452e-a237-d6727952e466.png">
2) after hiding "release - version"
<img width="330" alt="image" src="https://user-images.githubusercontent.com/101123/167498867-7ff82df2-863e-45d7-a862-28d645f2f415.png">
3) after adding "release - platform" back and then adding "release - status" in. (it only keeps the LAST one I added)
<img width="317" alt="image" src="https://user-images.githubusercontent.com/101123/167499034-6ebc522b-c6b4-4579-9377-1f006f4aec72.png">

Variation of switching the table order (where everything "works").. Notice how the "more columns" is still showing all the columns

<img width="329" alt="image" src="https://user-images.githubusercontent.com/101123/167499580-a598ba57-9be3-472d-969d-7f89bc10fd46.png">

**Information about your Metabase Installation:**

- Browser: Firefox 99.0.1
- OS OS X 10.15
- DB Postgresql 11
- Metabase version 0.42.0 and 0.43.0
- hosted on EBS
- Metabase internal DB Postgresql 11

**Severity**
Annoying.

**Comment by flamber** [comment] 2022-05-15 12:11
Almost a repeat of #12395. Likely very related to #13455 and maybe to #12044 and #22382

Steps to reproduce:
1. Question > Sample > Orders - join Products
2. Summarize Count grouped by Category and Title and Vendor
3. Create a Custom Column (`1 + 1`)
![image](https://user-images.githubusercontent.com/1447303/168471558-6867ed16-880f-4325-a40c-0e0085edbf37.png)
4. Visualize and open the visualization Settings sidebar - note the unintended columns in "More columns"
![image](https://user-images.githubusercontent.com/1447303/168471571-ca2f47d9-430e-45a8-a2cb-86450da297c3.png)
5. Now remove "Products.Vendor" in the sidebar - displays a Run-overlay first, where everything looks correct
![image](https://user-images.githubusercontent.com/1447303/168471611-c155c140-ad99-48fb-93d2-c210c53913e2.png)
6. After running it, then group-by columns are removed
![image](https://user-images.githubusercontent.com/1447303/168471640-fe452e36-de7f-4096-8e53-83c4a58f649c.png)
But going into the Notebook will show everything untouched (even has the Vendor grouping)
![image](https://user-images.githubusercontent.com/1447303/168471683-edd45d22-e234-4600-9a07-c7caa64b9eff.png)
7. Adding "Category" back seems to work
![image](https://user-images.githubusercontent.com/1447303/168471928-147837a8-efb3-4f16-a259-c7d52dc01685.png)
But going into the Notebook will still show inconsistent choices
![image](https://user-images.githubusercontent.com/1447303/168471969-f5e5368c-6f50-4df1-94f4-1f452ee7a02d.png)

**Comment by Beeskey** [comment] 2022-08-03 17:54
Having a similar issue, similar to the one that was just closed, #24292, but instead of hiding a column, I try to rearrange column order in the table settings sidebar and when I refresh all columns that aren't in the 1st table disappear. I can add columns back, but any time I attempt rearranging, the same thing happens.

**Comment by samhopwell** [comment] 2022-08-17 14:35
Just to confirm this is still an issue in v0.44.1. 

Is there a workaround for this at all?

**Comment by ranquild** [comment] 2023-10-31 17:20
Columns in viz settings are managed by MLv2 now

**Comment by WiNloSt** [comment] 2023-11-08 11:12
Reproducible on 1.42, but fixed in master (e0ebd085cc168d75692c4ec584bb71994011dc83)
![image](https://github.com/metabase/metabase/assets/1937582/ee02e061-12f7-4366-892d-e3d4ea03adca)

**Comment by bshepherdson** [comment] 2023-11-08 22:31
This issue no longer exists with the new viz settings UI.

In trying to write a test for it, I stumbled on a not-really-related MLv2 bug and have #35518 open for that. This issue can probably be closed.

The new column picker UI knows that breakout columns are not removable, and so won't even try to remove them. It allows reordering and hiding them too, but that's a UI concern not an MLv2 concern.

**Comment by salsakran** [comment] 2023-11-14 11:02
closing this since there's no way to test it given the UI changed.

**Closed by salsakran** 2023-11-14 11:02 UTC
Labels: Type:Bug, Priority:P2, .Correctness, Visualization/Chart Settings, .Backend, Querying/GUI, Querying/Notebook, Querying/Notebook/Custom Column, .Team/PixelPolice (DEPRECATED), .Wanted: MLv2
