### ISSUE TITLE
[Feature] Recognize MongoDB IDs as timestamps too

### ISSUE THREAD

**Issue by sylvinus** [metabase/metabase#8613] opened 2018-10-01 23:49 UTC
Some MongoDB collections omit a field "date_created" and use the "_id" field instead, which contains a timestamp.

It would be great to be able to use it as basis for grouping, as if it had been autodetected as a date field.

thanks!

**Comment by camsaul** [comment] 2020-05-13 01:41
Duplicate of #2987

**Closed by camsaul** 2020-05-13 01:41 UTC
Labels: .Proposal, Database/Mongo
