### ISSUE TITLE
This regex can be stucked by strings

### ISSUE THREAD

**Issue by 2bdenny** [metabase/metabase#7354] opened 2018-04-16 12:27 UTC
https://github.com/metabase/metabase/blob/b155205c60756276b48ccb0e54472b263c1d2111/frontend/src/metabase/lib/expressions/parser.js#L359

Hello =), I try to extract all regexes in the project and test them, and find this one can be stucked by inputs. If the string, `error.message` contains too many `\n`, like `"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"`, it will be stucked over 30 seconds.
Recommend `/(\s)*but found:?/` instead.

**Comment by senior** [comment] 2018-04-27 19:33
What version of Metabase were you testing this on? I created a test like the one below:
```
    it("can ignore whitespace", () => {
        let s = "A * \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n +"
        expect(compile(s, expressionOpts)).toEqual(["field-id", 1]);
    });
```
And it failed (as expected) but there so no noticeable impact on performance.

**Comment by mbvictoria** [comment] 2019-06-28 17:53
Closing - has been labeled as "needs more info" and "unable to reproduce" for over a year.

**Closed by mbvictoria** 2019-06-28 17:53 UTC
Labels: Bug, Need More Info, Priority/P3, Query Builder, Unable to Reproduce
