### ISSUE TITLE
We shouldn't be carrying over dashboard click behavior clicking through from it to the saved question

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#16044] opened 2021-05-13 18:00 UTC
On master, if you have click behavior configured on a table in a dashboard that's overriding that saved question's link formatting, when you click through to that saved question, we're incorrectly applying the dashboard's click behavior to the saved question. See the gif here:

https://share.getcloudapp.com/Z4uoX68k

**Comment by flamber** [comment] 2021-05-13 18:02
Duplicate of #13595

**Closed by flamber** 2021-05-13 18:02 UTC
Labels: Priority:P2, Reporting/Dashboards, Type:Bug, Visualization/Tables
