### ISSUE TITLE
Custom question EXPORT shows EMPTY file

### ISSUE THREAD

**Issue by mhd-adam** [metabase/metabase#19556] opened 2022-01-05 15:21 UTC
When downloading a custom question results (export) I get an empty file although the question had results on Metabase.

**To Reproduce**
1. Create a custom question with results
2. Download the results as CSV

**Comment by flamber** [comment] 2022-01-05 16:23
Duplicate of #19465

**Closed by flamber** 2022-01-05 16:23 UTC
Labels: Type:Bug, .Needs Triage
