### ISSUE TITLE
Chart tooltips sometimes show the wrong series

### ISSUE THREAD

**Issue by whbjob** [metabase/metabase#3803] opened 2016-11-23 09:08 UTC
### Bugs
When I am moving my mouse between different bars in a same chart, the hints just show the same y axis value of the first dataset.
Any suggestions? Thanks.

You can see the every stack in bar show a same y value(The second line in hints).
-------
![image](https://cloud.githubusercontent.com/assets/3796131/20555986/e3b534b2-b19f-11e6-84c7-6b98ab569fe2.png)

![image](https://cloud.githubusercontent.com/assets/3796131/20555960/c2334572-b19f-11e6-90f8-ac070e0ba092.png)

**Comment by tlrobinson** [comment] 2017-01-10 02:03
Duplicate of #3599

**Closed by tlrobinson** 2017-01-10 02:03 UTC
Labels: Bug, Visualization
