### ISSUE TITLE
Editing Models with joins shows confusing table references in query definition

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#23021] opened 2022-05-28 12:26 UTC
**Describe the bug**
Editing Models with joins shows confusing table references, when editing the query definition again.

**To Reproduce**
1. Question > Sample > Orders - join People and Products and Reviews
![image](https://user-images.githubusercontent.com/1447303/170825329-7180dedf-e876-4d04-ad4f-af2abbf2d89c.png)
2. Save question and turn into Model
3. Do a browser refresh #22518
4. Click "Edit query definition" - shows table references all over the place
![image](https://user-images.githubusercontent.com/1447303/170825429-83ad7f11-5cd6-44f9-8c96-362e691f5d79.png)

**Expected behavior**
Do not show references to the Model itself, show the correct table reference

**Information about your Metabase Installation:**
Tested 0.43.1

**Comment by calherries** [comment] 2022-08-22 21:59
@gusaiani I went down the rabbit hole on this one looking for a cause on the BE. But I'm sure it's FE related now. Maybe it's related to some of your other issues.

There's another way to reproduce the bug that might shine light on the cause. Instead of step 4, where flamber clicked "edit query definition", try to create the exact same question again (not a model), and the same issue will happen with the wrong table references. This confirms the cause isn't related to the BE.
<img width="791" alt="image" src="https://user-images.githubusercontent.com/39073188/186025444-59d570b2-4491-4657-afb4-9ef59993f5be.png">

**Comment by calherries** [comment] 2022-08-30 16:19
@gusaiani I created a loom to clarify what meant by the above.
https://www.loom.com/share/4f4ab363449846edb14ecca3442d87a8

**Comment by daltojohnso** [comment] 2022-09-12 19:07
Fixed by https://github.com/metabase/metabase/pull/25109

**Closed by daltojohnso** 2022-09-12 19:07 UTC
Labels: Type:Bug, Priority:P3, Querying/GUI, .Regression, Querying/Models
