### ISSUE TITLE
Latitude longitude decimal error

### ISSUE THREAD

**Issue by 100n0m3** [metabase/metabase#3862] opened 2016-12-05 01:00 UTC
I am having an error when making a slect to use on the map is turning the latitude and longitude into decimal numbers
some wone knows how to fix?
![decimal](https://cloud.githubusercontent.com/assets/13314118/20870808/61b42ac0-ba75-11e6-9f0d-81c51ac5529d.PNG)

**Comment by mazameli** [comment] 2016-12-05 19:14
Lat and long actually should be showing with decimal values. Do you mean the problem is that it's truncating the decimals? In the Data Model section of the Admin Panel, make sure your `longitude` and `latitude` fields are marked as `Longitude` and `Latitude`, respectively, in the `TYPE` dropdowns.

**Comment by 100n0m3** [comment] 2016-12-06 11:53
In version v0.20.3 works normally but we have the problem of the maps in the default position that gets with error, already in the compiled version we have the error described above.

**Comment by salsakran** [comment] 2016-12-06 21:20
what do you mean "compiled version"?

**Comment by 100n0m3** [comment] 2016-12-07 14:52
Build from source.

**Comment by 100n0m3** [comment] 2016-12-11 22:42
this only happens when we convert the question to sql.

**Comment by camsaul** [comment] 2016-12-13 03:43
@100n0m3 are you talking about the latitude and longitude being reversed? You said things worked in 0.20.3 but not in 0.21.0?

**Comment by 100n0m3** [comment] 2016-12-13 10:23
this is the question working 
![image](https://cloud.githubusercontent.com/assets/13314118/21136563/46560ca0-c10d-11e6-860d-bd0dbecc1b1e.png)

and this is exacly the same question convert to sql
![image](https://cloud.githubusercontent.com/assets/13314118/21136589/5f8bcc00-c10d-11e6-96e9-2ff6eb09be91.png)

**Comment by 100n0m3** [comment] 2016-12-13 10:25
in version 0.20.3 is working fine, but the map used is google and the default viewer of the map don't save.

**Comment by bmcbride** [comment] 2018-05-29 20:15
It looks like there is still an issue with this. I'm using Postgres double precision columns for latitude and longitude with the special Latitude and Longitude column types.

With the Custom Question Builder interface, you get nicely formatted values:

![image](https://user-images.githubusercontent.com/753187/40682527-fbce9ff8-6359-11e8-8435-79826e4cbbb9.png)

If you write the question in Native SQL, the values are truncated:

![image](https://user-images.githubusercontent.com/753187/40682844-c55b4722-635a-11e8-9894-5f561ade7d05.png)

**Comment by flamber** [comment] 2019-02-20 23:39
This was fixed in version 0.31, which allows you define number of decimals in table visualization :gear:
![image](https://user-images.githubusercontent.com/1447303/53132788-6de8f300-3536-11e9-9076-62fa26c200f9.png)

**Comment by mbvictoria** [comment] 2019-06-28 19:05
Closing - resolved.

**Closed by mbvictoria** 2019-06-28 19:05 UTC
Labels: Need More Info
