### ISSUE TITLE
Hiding tables doesn't appear to take effect until refreshing the browser

### ISSUE THREAD

**Issue by abouzarnouri** [metabase/metabase#11383] opened 2019-11-25 09:17 UTC
**Describe the bug**
Using v0.33.6 of metabase on a Postgres v11 DB, when I hide a table using "Data Model" menu in admin panel of metabase, it is hidden when I try to create a custom question. But when I open the database from the browse option in the bottom of first page, all the hidden tables are shown. 

**Logs**
No error log is printed in the logs output.

**Information about your Metabase Installation:**
The DB which I am monitoring it using metabase is a Postgres v11 instance. And the bug occurs when I installed metabase both on a Windows machine and a docker instance on Linux. Moreover when I when internal H2 DB and using Postgres DB for metabase, the bug didn't fix.

**Comment by flamber** [comment] 2019-11-25 19:08
Hi @abouzarnouri 
I think you're seeing old cache. Try refreshing your browser.
There's several issues covering problems with cache, like #10330, but I cannot find a specific issue for "Our Data", which is the same as accessing via "Browse Data" in the top.

**Comment by mazameli** [comment] 2020-01-16 23:38
@abouzarnouri did the tables correctly get hidden after refreshing your browser? That's the behavior I'm seeing.

**Comment by flamber** [comment] 2020-06-04 13:07
Duplicate of #9759 - fixed in upcoming 0.36.0

**Closed by flamber** 2020-06-04 13:07 UTC
Labels: Administration/Metadata & Sync, Priority:P2, Type:Bug
