### ISSUE TITLE
[BigQuery] Allow Setting Query Processing Location

### ISSUE THREAD

**Issue by indy-singh** [metabase/metabase#30897] opened 2023-05-21 17:29 UTC
**Is your feature request related to a problem? Please describe.**
We have three environments; LOCAL, DEMO, and LIVE. We keep a clear seperation of those environments but the schemes are identical. This means that projection/transformation of data is identical except for the dataset prefix:-

```sql
DECLARE startParam DATE DEFAULT DATE_SUB(CURRENT_DATE, INTERVAL {{days_back}} DAY);
DECLARE endParam DATE DEFAULT CURRENT_DATE();
DECLARE dealerIdParam STRING DEFAULT {{dealer_id}};
DECLARE envParam STRING DEFAULT {{environment}};
DECLARE externalSystemKeyParam STRING DEFAULT {{external_system_key}};

IF UPPER(envParam) = UPPER('LIVE') THEN
  SELECT * FROM `snowplow-233715.LIVE_calculations.recent_calcs_v2`(startParam, endParam, dealerIdParam, externalSystemKeyParam);
ELSEIF UPPER(envParam) = UPPER('DEMO') THEN
  SELECT * FROM `snowplow-233715.DEMO_calculations.recent_calcs_v2`(startParam, endParam, dealerIdParam, externalSystemKeyParam);
ELSEIF UPPER(envParam) = UPPER('LOCAL') THEN
  SELECT * FROM `snowplow-233715.LOCAL_calculations.recent_calcs_v2`(startParam, endParam, dealerIdParam, externalSystemKeyParam);
END IF;
```

Currently we have to duplicate the same [table-valued function](https://cloud.google.com/bigquery/docs/table-functions) within each environment's prefix. 

**Describe the solution you'd like**
I believe Metabase is integrated into this [BigQuery API](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query#QueryRequest). I think the ideal solution would be to surface a front-end configuration; either on the database connection or the question itself that allows you to selection the `location` that gets passed to the outgoing request to BigQuery.

**Describe alternatives you've considered**
So far I've tried and failed with:-

* string interpolation
* [EXECUTE IMMEDIATE](https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#execute_immediate)
* [Region qualifier](https://cloud.google.com/bigquery/docs/information-schema-intro#region_qualifier)

I can successfully set the dataset dynamic by using BigQuery's [system variable](https://cloud.google.com/bigquery/docs/reference/system-variables) `@@dataset_id`.

Which looks like this:-
![image](https://github.com/metabase/metabase/assets/1906778/e1647c84-a512-4817-9342-08da544ae5b2)

But that requires the setting of the query processing location _manually_ hence this feature request.

This is what it looks like without the query processing location set:-

![image](https://github.com/metabase/metabase/assets/1906778/930945c6-1a55-461b-af18-0db7bdaf30b9)

**How important is this feature to you?**
It's not a show stopper, but we want to reduce the friction of creating multiple questions/dashboards per environment and ideally want to reuse a question/dashboard and keep it environment agnostic. I'm aware that we could use things like DBT/Dataform to rollup/aggregate the data into one table and shove the environment into a column and then reference it in a WHERE clause, but that would violate our rule of keeping data between environments separate. We are in the financial services industry so a lot of these rules are "whoops now you get a fine" territory.

We are on `metabase-enterprise v1.46.3-X02-private` (hosted via metabaseapp.com). I did have quick look at the source, and it appears the relevant change would be made somewhere in [bigquery_cloud_sdk.clj](https://github.com/metabase/metabase/blob/master/modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj) but my day to day is in C# so I'm a little lost. Happy to work on a PR with some guidance though :)

Cheers,
Indy

**Comment by indy-singh** [comment] 2023-05-21 18:32
Ah, I see the source doesn't directly integrate with the [BigQuery API](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query#QueryRequest) it now goes via `com.google.cloud.bigquery` since https://github.com/metabase/metabase/pull/16746.

Which means we should be able to call [setLocation](https://cloud.google.com/java/docs/reference/google-cloud-bigquery/latest/com.google.cloud.bigquery.BigQueryOptions.Builder#com_google_cloud_bigquery_BigQueryOptions_Builder_setLocation_java_lang_String_) around here: 

https://github.com/metabase/metabase/blob/663ca8e5c73419f368780b344b176b7e331e3a53/modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj#L59

It looks like `setLocation` supports both a single region (e.g. `us-east5`, `europe-west2` et al) and multi region (`US` or `EU`):-

* [CancelJob.java#L50](https://github.com/googleapis/java-bigquery/blob/27fa7b12ea55ec70f4b59d4e99b34744f46e1fd9/samples/snippets/src/main/java/com/example/bigquery/CancelJob.java#L50)

* [StandardTableDefinitionTest.java#L77](https://github.com/googleapis/java-bigquery/blob/27fa7b12ea55ec70f4b59d4e99b34744f46e1fd9/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/StandardTableDefinitionTest.java#L77)

* [ITBigQueryTest.java#L1946](https://github.com/googleapis/java-bigquery/blob/27fa7b12ea55ec70f4b59d4e99b34744f46e1fd9/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java#L1946)

Am I along the right lines here?

Cheers,
Indy

**Comment by indy-singh** [comment] 2023-05-21 18:44
The `location` isn't contained in the Service account JSON file, so it would have to be provided as an optional parameter on the Admin Database page in Settings I think; much like the Project Id.

https://github.com/metabase/metabase/blob/663ca8e5c73419f368780b344b176b7e331e3a53/modules/drivers/bigquery-cloud-sdk/resources/metabase-plugin.yaml#L12

![image](https://github.com/metabase/metabase/assets/1906778/4a9bbbcf-cf55-4df3-b6c6-47d9c0370925)

**Comment by paoliniluis** [comment] 2023-05-22 13:33
Thanks for the detailed report. This is a duplicate of https://github.com/metabase/metabase/issues/21309

**Closed by paoliniluis** 2023-05-22 13:33 UTC
Labels: Type:New Feature, .Needs Triage

**Comment by indy-singh** [comment] 2023-05-22 14:00
Hey @paoliniluis,

You've closed that as not planned - is that correct? [The other ticket](https://github.com/metabase/metabase/issues/21309) has been left in limbo since March 2022. Just wondering if I should bother to put together a PR or not?

Cheers,
Indy
