### ISSUE TITLE
Request: Drag and Drop Filters to Different Place on Dashboard (not re-ordering request)

### ISSUE THREAD

**Issue by GiacchinoCinque** [metabase/metabase#15320] opened 2021-03-24 18:39 UTC
Would it be possible to make it so that we can drag and drop the filter (just like charts) to a different place on the dashboard... Not re-ordering the filters but actually putting them above the charts they reference.

I would say that this feature would be nice to have since I am doing multiple things on one dashboard and having all the filters at the top of the board just kind of looks messy and there's no clear reference for while filter relates to which dashboard.

If this is already possible please let me know! Thanks!

**Comment by flamber** [comment] 2021-03-24 18:42
Duplicate of #13821

**Closed by flamber** 2021-03-24 18:42 UTC
Labels: .Needs Triage, Type:New Feature
