### ISSUE TITLE
Add pulse errors to troubleshooting logs

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#9243] opened 2019-01-09 19:51 UTC
It would be useful to add pulse send errors to the troubleshooting logs.

**Comment by flamber** [comment] 2019-02-24 23:43
Isn't this a duplicate of #8417, which was fixed by #9372 ?

**Comment by camsaul** [comment] 2019-05-13 20:49
Duplicate of #8417 
Fixed by #9372

**Closed by camsaul** 2019-05-13 20:49 UTC
Labels: Admin Panel & Setup, Proposal
