### ISSUE TITLE
value may be nil, or if non-nil, value must be an array of valid results column metadata maps - blocks saving of existing questions 

### ISSUE THREAD

**Issue by Vandervoort** [metabase/metabase#12420] opened 2020-04-29 06:00 UTC
**Describe the bug**
Using PSQL and newly upgraded to 0.35.3.

Attempt to modify any existing question which return no results will give the error 'value may be nil, or if non-nil, value must be an array of valid results column metadata maps' when saving

This error was reported for the first time after upgrading to 0.35.3

**Logs**
[32fb8e9f-63e1-4afd-baaa-fbf4efb53aa8] 2020-04-29T13:38:50+08:00 DEBUG metabase.middleware.log POST /api/card 400 2.0 ms (0 DB calls)
{:errors {:result_metadata "value may be nil, or if non-nil, value must be an array of valid results column metadata maps."}}

**Severity**
High

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.14.171-105.231.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "postgres"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-21",
      "tag": "v0.35.3",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": "Asia/Kuala_Lumpur"
    }
  }
}
```

**Comment by flamber** [comment] 2020-04-29 08:25
Duplicate of #11256 - upvote by clicking :+1: on the first post

**Closed by flamber** 2020-04-29 08:25 UTC
Labels: .Duplicate
