### ISSUE TITLE
Relative Date Queries incorrect with Mongo

### ISSUE THREAD

**Issue by zorro2b** [metabase/metabase#5413] opened 2017-06-29 06:53 UTC
- Your browser and the version: Opera 45
- Your operating system: OSX 10.12.5
- Your databases: MongoDB
- Metabase version: 0.24.2
- Metabase hosting environment: Heroku
- Metabase internal database: H2

- *Repeatable steps to reproduce the issue*

Querying using "past 30 days" does not produce correct result.

Here is an example execute on 29 June 2017.

Query raw data:
![screen shot 2017-06-29 at 4 46 31 pm](https://user-images.githubusercontent.com/4575514/27674942-46598f36-5ceb-11e7-908e-14adf7331e50.png)

Query past 30 days:
![screen shot 2017-06-29 at 4 46 53 pm](https://user-images.githubusercontent.com/4575514/27674955-51ee7b9a-5ceb-11e7-984f-5f1c3f97f4d8.png)

Query from fixed date:
![screen shot 2017-06-29 at 4 47 51 pm](https://user-images.githubusercontent.com/4575514/27674963-61a49420-5ceb-11e7-94ec-7ee0882e0c48.png)

**Comment by salsakran** [comment] 2017-08-01 18:10
@camsaul what's the MBQL definition of "past N", does that include the current day or not? 

My memory is a bit muddled because I know we did want to provide the ability to exclude the current day to prevent the whole "why is my metric falling off a cliff"  chart problem.

**Comment by camsaul** [comment] 2017-08-01 18:11
[*last* N](https://github.com/metabase/metabase/wiki/Query-Language-'98#time-interval-filter) doesn't include the current day, we decided not to include it for the "falling off a cliff" reason you're thinking of

**Comment by salsakran** [comment] 2017-08-01 18:15
That's what I thought. 

Closing as not a bug, since this is a choice of what "past" means, and we've been pretty consistent in this for so long that changing it now would probably be more hassle to our usebase than it would be clarifying to new users.

**Closed by salsakran** 2017-08-01 18:15 UTC
Labels: Bug, Database/Mongo, Priority/P2, Timezones/Calendars
