### ISSUE TITLE
Feature Request: Dashboard Folders

### ISSUE THREAD

**Issue by sharedphysics** [metabase/metabase#7667] opened 2018-05-18 18:45 UTC
Not an issue, but a feature request: 
Can you create the ability to group dashboards into folders? 

Use case is the following: we have multiple dashboards per team member, and multiple company-wide dashboards. There is a lot of data we're looking at, and after a certain number of graphs/tables on a dashboard, they end up loading slowly -- too many queries run at the same time, and some end up timing out. For these two reasons, the number of dashboards we have has ballooned and is starting to become kind of hard to manage. We'd want to group all of our different ads dashboards in one folder, our different sales dashboards in a different folder, and then have user-specific folders. Same way we have folders for questions!

**Comment by mazameli** [comment] 2018-05-18 18:52
Yep, this is a very common request, and I'm happy to say it's one of the main features that we plan on including in version 0.30.

The current plan is to allow questions, dashboards, and pulses to all be saved in folders, and to also allow for sub-folders. We're also 90% sure that we'll be including private, personal folders for each user as a scratch space. There will also be the ability to "pin" important dashboards (and possibly other items) to the top of a collection, so that the most important one(s) are easy to find.

Check out this issue for links to more info: https://github.com/metabase/metabase/issues/7515

Closing this as a duplicate of #7515

**Closed by mazameli** 2018-05-18 18:52 UTC
Labels: Duplicate
