### ISSUE TITLE
Pie chart doesn't always render label/value (follow up issue discovered in #13721)

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#13770] opened 2020-11-12 21:55 UTC
**Describe the bug**
After following all repro steps from #13626 and after the fix from #13721, pie chart now renders but fails to display label and value consistently. All mechanism and logs are explained [HERE](https://github.com/metabase/metabase/pull/13721#issuecomment-724931075), but I'll include them in this issue for the sake of convenience.

---

#### 1. With no value set to the filter
Going to the dashboard from `/collection/root` results in data failing to load (it loads on mouse hover)
https://share.getcloudapp.com/NQu1PbvN (GIF screenshot)

#### 2. When you set the filter value manually, values in a card/chart don't load, but the URL updates:
https://share.getcloudapp.com/JrugJve1 (GIF screenshot)

#### 3. If you set the filter value directly through URL `/dashboard/1?id=1`, values in a card/chart eventually load:
https://share.getcloudapp.com/GGur1LPW (GIF screenshot)

#### 4. finally, when you manually add value `3` on top of an existing `1` to the filter, card/chart values are not initially rendered. Again, they render only on hover.
https://share.getcloudapp.com/v1uxpADq (GIF screenshot)

---

**Logs**
These are some JS console logs that might have some relation to the rendering issue:
```
DEPRECATED: metabase/redux/metadata addFields
DEPRECATED: metabase/redux/metadata fetchField
DEPRECATED: metabase/redux/metadata fetchFieldValues
```

```
Uncaught Invariant Violation: findDOMNode was called on an unmounted component.
    at invariant (http://localhost:8080/app/dist/vendor.hot.bundle.js?5b5e02b9818d518b76f2:84935:15)
    ...
```
Cannot read property of rows/slice/cols of undefined. (The same warning for each - don't want to repeat 3 logs)
```
settings.js:160 Error getting setting pie._metricIndex TypeError: Cannot read property 'cols' of undefined
    at Object.getValue (PieChart.jsx:157)
    ...
```

**To Reproduce**
1. Follow the steps in the original issue (#13626 ) or spin up Cypress based on the steps in #13673 
2. Then follow steps 1-4 (with screenshots) included in this issue

**Expected behavior**
Pie chart should immediately display associated label/value, regardless of the path one uses to reach the dashboard that contains this visualization.

**Screenshots**
Included as links. See above.
![](https://p58.f1.n0.cdn.getcloudapp.com/items/NQu1PbvN/Screen%20Recording%202020-11-10%20at%2008.50.49%20PM.gif?source=viewer&v=a7dc4f35d982154010d4a6dab0f47ab8)

**Information about your Metabase Installation:**
- Your browser and the version: N/A
- Your operating system: N/A
- Your databases: Sample Dataset
- Metabase version: latest `release-x.37.x` branch
- Metabase hosting environment: local dev.
- Metabase internal database: H2

**Severity**
Probably P3.

**Additional context**
There is a repro made for the original issue (#13626). It kept failing because of these rendering problems. It is still skipped. It should be unskipped and passing after this issue is solved.

**Comment by flamber** [comment] 2020-11-12 22:09
Duplicate of #12506

**Closed by flamber** 2020-11-12 22:09 UTC
Labels: .Needs Triage, Type:Bug
