### ISSUE TITLE
Same date filters give different results!

### ISSUE THREAD

**Issue by benjR** [metabase/metabase#6539] opened 2017-12-06 16:06 UTC
I have a basic dashboard where I count the number of rows returned that match a specific field being not null in a specific period, this gives me a total number per month, each one of the records has a date set like "2017-09-18 20:39:00"

I started to see weird results after the 0.27.1 upgrade but that may not be related to this specific release. Anyway, here are the results on filters that are supposed to be doing exactly the same.

Using query builder with last month filter: 951
Using a SQL query and grouping by month: 951
Using query builder with "month and year" date filter: 962
Using query builder with between date filter (from 01/11 to 30/11 both selected in the date picker): 962

When digging in a little bit and displaying results in raw mode, I can see that "month and year" and "between" filters are including values from the last day of the previous month the 31/09  and excluding values from the 30/11 aka last day of the month...

- Your browser and the version: (all browsers but Chrome 52.1  62.0.3202.94)
- Your operating system: OS X High Sierra for the client
- Your databases: MariaDB
- Metabase version: 0.27.1
- Metabase hosting environment: Docker
- Metabase internal database:  H2 (default)

Thanks

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by pushkar8723** [comment] 2017-12-09 04:41
![image](https://user-images.githubusercontent.com/2996493/33792545-1f03b6d8-dcc9-11e7-88fc-6168a0a7a279.png)
Having similar issue. We are on 0.27.1 and I can confirm that this issue was there at least in last release too.
Report Timezone is set to Asia/Calcutta

**Comment by senior** [comment] 2018-01-05 22:49
I think the different results you're seeing are caused by a bug in Metabase that is hit based on how the dates are being calculated. If Metabase is calculating the begin and end times (i.e. between 12/1/2017 and 12/31/2017) vs if a relative date is being used (i.e. current_date - 30 days) where the database does the calculation.

In @pushkar8723's example above, Metabase is providing two dates as query parameters. I think that's hitting a bug that I found in the MySQL driver. With https://github.com/metabase/metabase/pull/5729 we began including the report-timezone with date query parameters in the JDBC standard way. It looks like that doesn't work correctly for MySQL due to [this bug](https://bugs.mysql.com/bug.php?id=80201) in the MySQL driver. We've just merged a workaround for this issue https://github.com/metabase/metabase/pull/6643. That change attaches the date/timestamp as an ISO formatted string rather than the Java Date/Timestamp types.

@benjR @pushkar8723 I think this should fix the issue you're seeing. Could you verify? It's currently in master and will be included in the next release (probably 0.28.0 RC1).

**Comment by HelenMertes** [comment] 2018-02-08 13:36
We just upgraded to 28.0, but there still is this date bug in the query builder - not entirely sure this is the same issue (database is BigQuery). 
Basically, using the "between" date filter returns date from outside the chosen range: 

![image](https://user-images.githubusercontent.com/24734846/35975354-b6f5907c-0cdc-11e8-822b-d225772ccee6.png)

Same when using "On" e.g. "5 February", the results are only from 4 February.
Thanks!

**Comment by swatisinghi** [comment] 2018-05-07 05:50
@senior I am still seeing this issue, running my query against Redshift. I am on version 0.29. Please help.

**Comment by senior** [comment] 2018-05-08 13:49
The original issue here I believe has been resolved, as it was related to MySQL date handling, so I'm going to go ahead an close this. If you find another bug, please open up another issue.

@HelenMertes I was able to reproduce the issue you mentioned with BigQuery. This is a separate issue that I have written up as #7584 and I have the issue fixed in #7520. That PR still needs some work but should be merged soon.

@swatisinghi Could you open up an issue with more details on the bug you are seeing? Redshift uses a report timezone, which would make it a different problem and the one with BigQuery.  The original issue was related to a bug in the MySQL driver, so that wouldn't affect Redshift either.

**Closed by senior** 2018-05-08 13:49 UTC
Labels: Bug, Priority/P1, Timezones/Calendars
