### ISSUE TITLE
Change default display settings for all series in a graph

### ISSUE THREAD

**Issue by antoine-lizee** [metabase/metabase#16877] opened 2021-07-02 17:30 UTC
**Is your feature request related to a problem? Please describe.**

Display settings, like "Show dots on line" or "Replace missing values with", are typically applied to every series. Currently, you need to set it manually for every series.

This is a problem when:
 - There are filters in your dashboard / question that will change the series
 - There will be new series in the future
 - There are many series in your graph (10+ is quite common)

The first two "problems" are especially blocking when preparing results that you would share. It basically makes me unable to share some graphs because I know that they will be wrong once used by someone else.
In particular **the missing value extrapolation can render a graph actually wrong** because of its default to do "linear interpolation". It's not only aesthetics!

**Describe the solution you'd like**
Being able to chose a default for the display settings in the "Display" tab of the visualization "Settings", on top of the list of the series with their dropdowns.

**Describe alternatives you've considered**
I'm likely going to edit programatically the json in the visualization setting that is stored in the saved question. This is painful, error-prone and will not last in time.

**How important is this feature to you?**
Cf the problem description. It's an actual blocker in a few cases, and annoying in others.

**Additional Context**
Example of graph that is broken if you do the linear interpolation by default:
![image](https://user-images.githubusercontent.com/2957716/124310075-f72f7c00-db6b-11eb-971c-ba5f58a5abcb.png)

**Comment by flamber** [comment] 2021-07-02 17:56
Sounds like a duplicate of #11871/#10507

**Closed by flamber** 2021-07-02 17:56 UTC
Labels: .Needs Triage, Type:New Feature

**Comment by antoine-lizee** [comment] 2021-07-06 09:23
Hello @flamber , thanks for the duplicate detection.

So, it was flagged in 2019 for the first time. How can we help prioritize these small-but-useful features of the graph building? Do you guys have a vision on when you will be able to invest in this layer?

**Comment by flamber** [comment] 2021-07-06 10:22
@antoine-lizee I cannot give you a timeline. We try to plan a couple of releases into the future and prioritize based on various parameters (product goals, customers, feedback, updates, etc).
