### ISSUE TITLE
Referenced subqueries from questions don't use the aliased column name.

### ISSUE THREAD

**Issue by rjbergerud** [metabase/metabase#21147] opened 2022-03-22 00:34 UTC
**Describe the bug**
Referenced subqueries from questions don't use the aliased column name.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

First create the following query that counts the number of products by category and vendor
<img width="1259" alt="Screen Shot 2022-03-21 at 5 14 41 PM" src="https://user-images.githubusercontent.com/10406289/159383433-b13b0cc2-ddfc-45f8-9b46-91f08a1423ef.png">

and save it as a question
<img width="1259" alt="Screen Shot 2022-03-21 at 5 14 55 PM" src="https://user-images.githubusercontent.com/10406289/159383444-b8150cfe-5bfa-4f6a-9953-29df003a422b.png">

Then join it with this new query, and create a column derived by fields from each of the joined tables 
<img width="1259" alt="Screen Shot 2022-03-21 at 5 17 14 PM" src="https://user-images.githubusercontent.com/10406289/159383451-41f6dab2-162d-46e3-9dcc-9ad11ccfa4a4.png">

We get an error
```
Column """Question 21"".VENDOR" must be in the GROUP BY list; SQL statement: -- Metabase:: userID: 1 queryType: MBQL queryHash: c65247f59d74d8e7f5e5c3bb336dbe27115cda008ac1e447bf6ffc9479310f59 SELECT "source"."CATEGORY" AS "CATEGORY", "source"."count" AS "count", "source"."category_percentage_by_vendor" AS "category_percentage_by_vendor", "source"."Question 21__VENDOR" AS "Question 21__VENDOR", "source"."Question 21__CATEGORY" AS "Question 21__CATEGORY", "source"."Question 21__count" AS "Question 21__count" FROM (SELECT "source"."CATEGORY" AS "CATEGORY", "source"."count" AS "count", (CAST("Question 21"."count" AS float) / CASE WHEN count(*) = 0 THEN NULL ELSE count(*) END) AS "category_percentage_by_vendor", "Question 21"."VENDOR" AS "Question 21__VENDOR", "Question 21"."CATEGORY" AS "Question 21__CATEGORY", "Question 21"."count" AS "Question 21__count" FROM (SELECT "PUBLIC"."PRODUCTS"."CATEGORY" AS "CATEGORY", count(*) AS "count" FROM "PUBLIC"."PRODUCTS" GROUP BY "PUBLIC"."PRODUCTS"."CATEGORY" ORDER BY "PUBLIC"."PRODUCTS"."CATEGORY" ASC) "source" LEFT JOIN (SELECT "PUBLIC"."PRODUCTS"."VENDOR" AS "VENDOR", "PUBLIC"."PRODUCTS"."CATEGORY" AS "CATEGORY", count(*) AS "count" FROM "PUBLIC"."PRODUCTS" GROUP BY "PUBLIC"."PRODUCTS"."VENDOR", "PUBLIC"."PRODUCTS"."CATEGORY" ORDER BY "PUBLIC"."PRODUCTS"."VENDOR" ASC, "PUBLIC"."PRODUCTS"."CATEGORY" ASC) "Question 21" ON "source"."CATEGORY" = "Question 21"."CATEGORY") "source" LIMIT 2000 [90016-197]
```

When formatted a bit, this query looks like;
```sql
SELECT "source"."CATEGORY" AS "CATEGORY",
  "source"."count" AS "count",
  "source"."category_percentage_by_vendor" AS "category_percentage_by_vendor",
  "source"."Question 21__VENDOR" AS "Question 21__VENDOR",
  "source"."Question 21__CATEGORY" AS "Question 21__CATEGORY",
  "source"."Question 21__count" AS "Question 21__count"
FROM (
    SELECT "source"."CATEGORY" AS "CATEGORY",
      "source"."count" AS "count",
      (
        CAST("Question 21"."count" AS float) / CASE
          WHEN count(*) = 0 THEN NULL
          ELSE count(*)
        END
      ) AS "category_percentage_by_vendor",
      "Question 21"."VENDOR" AS "Question 21__VENDOR",
      "Question 21"."CATEGORY" AS "Question 21__CATEGORY",
      "Question 21"."count" AS "Question 21__count"
    FROM (
        SELECT "PUBLIC"."PRODUCTS"."CATEGORY" AS "CATEGORY",
          count(*) AS "count"
        FROM "PUBLIC"."PRODUCTS"
        GROUP BY "PUBLIC"."PRODUCTS"."CATEGORY"
        ORDER BY "PUBLIC"."PRODUCTS"."CATEGORY" ASC
      ) "source"
      LEFT JOIN (
        SELECT "PUBLIC"."PRODUCTS"."VENDOR" AS "VENDOR",
          "PUBLIC"."PRODUCTS"."CATEGORY" AS "CATEGORY",
          count(*) AS "count"
        FROM "PUBLIC"."PRODUCTS"
        GROUP BY "PUBLIC"."PRODUCTS"."VENDOR",
          "PUBLIC"."PRODUCTS"."CATEGORY"
        ORDER BY "PUBLIC"."PRODUCTS"."VENDOR" ASC,
          "PUBLIC"."PRODUCTS"."CATEGORY" ASC
      ) "Question 21" ON "source"."CATEGORY" = "Question 21"."CATEGORY"
  ) "source"
LIMIT 2000;
```
**Expected behavior**

In the subquery, the name for the aliased column `"source"."count"` should be used instead of `count(*)`
```sql
--(...)
   SELECT "source"."CATEGORY" AS "CATEGORY",
        "source"."count" AS "count",
        (
          CAST("Question 21"."count" AS float) / CASE
            WHEN "source"."count" = 0 THEN NULL
            ELSE "source"."count"
          END
        ) AS "category_percentage_by_vendor",
        "Question 21"."VENDOR" AS "Question 21__VENDOR",
        "Question 21"."CATEGORY" AS "Question 21__CATEGORY",
        "Question 21"."count" AS "Question 21__count"
      FROM (
          SELECT "PUBLIC"."PRODUCTS"."CATEGORY" AS "CATEGORY",
            count(*) AS "count"
          FROM "PUBLIC"."PRODUCTS"
          GROUP BY "PUBLIC"."PRODUCTS"."CATEGORY"
          ORDER BY "PUBLIC"."PRODUCTS"."CATEGORY" ASC
        ) "source"
--(...)
```

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```json
{
  "browser-info": {
    "language": "en-CA",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "5.4.0-1059-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-28",
      "tag": "v0.42.2",
      "branch": "release-x.42.x",
      "hash": "d6ff494"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
**Severity**
Might be a make or break on whether to use metabase, since this is typical of the sort of queries I'm trying to make.

**Comment by flamber** [comment] 2022-03-22 08:54
Duplicate of #20935

**Closed by flamber** 2022-03-22 08:54 UTC
Labels: Type:Bug, .Needs Triage
