### ISSUE TITLE
PieChart: Pulse card render error – No row values found for key {some name}

### ISSUE THREAD

**Issue by ivanb777** [metabase/metabase#50381] opened 2024-11-22 02:08 UTC
### Describe the bug

When creating an alert in Metabase that sends hourly notifications with a pie chart, the alert becomes unreliable if the underlying query's result set changes. Specifically, the messages (used as categories in the pie chart) seem to be set as fixed properties when the alert is created. If some of these messages are not present in the result set during subsequent runs, Metabase logs the following error:
`Pulse card render error, Error: No row values found for key Invalid Action`.

This issue is exclusive to pie charts and does not occur with other visualisation types like tables or bar charts.

### To Reproduce

Steps to reproduce the behaviour:

1. **Create a question**  
   - Use a table (e.g., `logs`) where messages are grouped and their counts are calculated.  
   - Example query:  

     ```sql
     SELECT message, COUNT(*) as count  
     FROM logs  
     GROUP BY message;
     ```  

     The result might look like this:  

     | Message            | Count |  
     |--------------------|-------|  
     | Invalid Action     | 10    |  
     | Successful Action  | 25    |  
     | Failed Attempt     | 5     |  

2. **Visualise the data as a pie chart**  
   - Open the question in Metabase.  
   - Choose "Visualisation" and select "Pie Chart".  

3. **Set up an hourly alert (pulse)**  
   - Go to the "Alerts & Actions" tab.  
   - Set up an hourly notification alert for the pie chart.

4. **Modify the data**  
   - Change the data in the `logs` table so that one or more messages (e.g., "Invalid Action") no longer appear in the query results.  

5. **Wait for the alert to trigger**  
   - Observe the next alert notification.  
   - Check the logs for the error: `Pulse card render error, Error: No row values found for key Invalid Action`.

### Expected behavior

The alert should dynamically handle changes in the result set. If a message category is missing from the query results, the pie chart should simply exclude it without logging an error or failing to render.

### Logs

[d0ac352a-ddae-4b8c-8c13-be831988491a] 2024-11-20T13:00:00+11:00 ERROR metabase.pulse.render Pulse card render error,Error: No row values found for key Expired Card,	at <js> :=>(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:315375:13198935-13198984),	at <js> getPieChartModel(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:315372-315381:13198797-13199071),	at <js> PieChart_PieChart(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:373350:16312180-16312238),	at <js> Db(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:83506:2405412-2405417),	at <js> Gb(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:83508:2406164-2406176),	at <js> X(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:83514:2408606-2408633),	at <js> Gb(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:83508:2406392-2406399),	at <js> X(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:83514:2408606-2408633),	at <js> Cb(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:83522:2411675-2411687),	at org.graalvm.polyglot.Value.execute(Value.java:880),	at metabase.pulse.render.js_engine$execute_fn_name.invokeStatic(js_engine.clj:67),	at metabase.pulse.render.js_engine$execute_fn_name.doInvoke(js_engine.clj:55),	at clojure.lang.RestFn.invoke(RestFn.java:493),	at metabase.pulse.render.js_svg$javascript_visualization.invokeStatic(js_svg.clj:151),	at metabase.pulse.render.js_svg$javascript_visualization.invoke(js_svg.clj:148),	at metabase.pulse.render.body$fn__78976$_AMPERSAND_f__78977.invoke(body.clj:454),	at metabase.pulse.render.body$fn__78976$fn__78984.invoke(body.clj:444),	at clojure.lang.MultiFn.invoke(MultiFn.java:261),	at metabase.pulse.render$render_pulse_card_body79344__79346.invokeStatic(render.clj:137),	at metabase.pulse.render$render_pulse_card_body79344__79346.invoke(render.clj:123),	at metabase.pulse.render$render_pulse_card79357__79358.invokeStatic(render.clj:164),	at metabase.pulse.render$render_pulse_card79357__79358.invoke(render.clj:147),	at metabase.channel.slack$payload__GT_attachment_data.invokeStatic(slack.clj:44),	at metabase.channel.slack$payload__GT_attachment_data.invoke(slack.clj:36),	at metabase.channel.slack$fn__112666$_AMPERSAND_f__112668.invoke(slack.clj:104),	at metabase.channel.slack$fn__112666$fn__112685.invoke(slack.clj:98),	at clojure.lang.MultiFn.invoke(MultiFn.java:239),	at metabase.pulse$send_pulse_BANG__STAR_$fn__104963$fn__104964.invoke(pulse.clj:365),	at metabase.pulse$send_pulse_BANG__STAR_$fn__104963.invoke(pulse.clj:363),	at metabase.pulse$send_pulse_BANG__STAR_.invokeStatic(pulse.clj:362),	at metabase.pulse$send_pulse_BANG__STAR_.invoke(pulse.clj:347),	at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:407),	at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:387),	at clojure.lang.RestFn.invoke(RestFn.java:442),	at metabase.task.send_pulses$send_pulse_BANG_$fn__109988.invoke(send_pulses.clj:57),	at metabase.models.task_history$do_with_task_history65689__65690.invokeStatic(task_history.clj:121),	at metabase.models.task_history$do_with_task_history65689__65690.invoke(task_history.clj:109),	at metabase.task.send_pulses$send_pulse_BANG_.invokeStatic(send_pulses.clj:52),	at metabase.task.send_pulses$send_pulse_BANG_.invoke(send_pulses.clj:49),	at metabase.task.send_pulses$send_pulse_BANG__STAR_.invokeStatic(send_pulses.clj:130),	at metabase.task.send_pulses$send_pulse_BANG__STAR_.invoke(send_pulses.clj:121),	at metabase.task.send_pulses.SendPulse.execute(send_pulses.clj:152),	at org.quartz.core.JobRunShell.run(JobRunShell.java:202),	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

### Information about your Metabase installation

```JSON
– Metabase version `v0.51.4`
```

### Severity

We cannot reliably use pie chart in alerts

**Comment by crisptrutski** [comment] 2024-11-22 03:34
Just to confirm, the question itself renders fine and its just the alerts that have this problem?

**Comment by ivanb777** [comment] 2024-11-22 20:28
> Just to confirm, the question itself renders fine and its just the alerts that have this problem?

Yes, the question itself renders perfectly, including the pie chart visualisation. The issue occurs only when a notification is sent. For instance, in Slack, we receive an error message in the form of an image instead of the rendered pie chart.

**Comment by maximepvrt** [comment] 2024-11-29 13:44
Hi,
I'm experiencing a similar issue with an embedded iframe. The error message displayed in French is:
"Quelque chose a mal tourné"
![Image](https://github.com/user-attachments/assets/ddd77502-c87c-4f0a-b727-2ae23593199e)
And in the console, I see the following error:
"Error: No row values found for key Mentorat / Parrainage"
![Image](https://github.com/user-attachments/assets/4ce81ee7-1957-4088-b377-5e731e0ff2fc)

Interestingly, the data export works correctly, and the dashboard functions as expected when not embedded. Additionally, the API returns the correct dataset, so it seems specific to the embedding context.

![Image](https://github.com/user-attachments/assets/b2c3df01-3917-488a-acc3-3bdd1ed66b69)

**Comment by alxnddr** [comment] 2024-12-07 02:32
Hi @ivanb777 @maximepvrt 👋  I've been looking at the issue but unfortunately I'm having trouble to reproduce the bug. Could you please share a bit more information that would make it easier to understand the root cause? 

I'd appreciate if you could email the following data to aleksandr@metabase.com

### Question that fails in Alerts
- Open Browser dev tools -> Network tab
- Open the question that fails in Alerts
- Find two requests with paths
  - `/api/card/:cardId`
  - `/api/card/:cardId/query`
- Copy all the content from the "Response" tab for every request

### Question that fails in embedding iframe
- Open Browser dev tools -> Network tab
- Open the question that fails in Alerts
- Find two requests with paths
  - `/api/embed/dashboard/:token` (or `/api/preview_embed/dashboard/:token` when previewing)
  - `/api/embed/dashboard/:token/dashcard/:id/card/:cardId` (or `/api/preview_embed/dashboard/:token/dashcard/:id/card/:cardId` when previewing)
- Copy all the content from the "Response" tab for every request

**Comment by paoliniluis** [comment] 2024-12-12 17:37
dupe of https://github.com/metabase/metabase/issues/50090

**Closed by paoliniluis** 2024-12-12 17:37 UTC
Labels: Type:Bug, Priority:P2, Reporting/Alerts, Visualization/Charts/Pie, .Team/DashViz

**Comment by ivanb777** [comment] 2024-12-12 21:51
hey @paoliniluis #50090 looks related but not duplicate to the issue reported here.

[#50090](https://github.com/metabase/metabase/issues/50090) reports the issue related to 

> an embedded dashboard with multiple pie charts ... an inner ring value disappears from the result set of _one_ of the pie chart questions but not the others.

the issue reported here is for a single pie chart and alert call – if during the subsequent renders the chart is missing a result set that was present when the chart/question was originally created
