### ISSUE TITLE
NGINX_SERVER_NAME directive denies any access on elastic beanstalk

### ISSUE THREAD

**Issue by lohrmann** [metabase/metabase#6233] opened 2017-10-23 08:06 UTC
- Metabase version: v0.26.1
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

Setting the `NGINX_SERVER_NAME` directive on elastic beanstalk as per [the documentation](https://www.metabase.com/docs/v0.18.1/operations-guide/running-metabase-on-elastic-beanstalk.html#protecting-against-invalid-hostname-access) results in all domains being inaccessible, including the hostname specified in the environment variable.

In the cloudwatch logs I can see that nginx is blocking off all incoming requests with a 444 error (as it should - but only for those requests without the correct hostname), which results in the browser showing a 504 gateway timeout.

I have tried only setting `NGINX_SERVER_NAME` without setting `NGINX_FORCE_SSL` at the same time, but to no avail. 

Looking at the nginx config files in the instance it seems as if server_name is not defined anywhere, so the `server_name()` doesn't seem to execute or execute incompletely.

**Comment by jcust** [comment] 2017-12-22 23:12
We ran into this issue as well, upgraded to v0.27.2 but it appears to still be a problem.

We had to remove the NGINX_SERVER_NAME env variable and cycle the instances out to fix.

**Comment by salsakran** [comment] 2017-12-22 23:21
Reproduced this. 

It has something to do with there being different versions of the beanstalk platform. Instances created SomeLongTimeAgo have a specific nginx config bootstrap file format that has changed since we wrote the documentation and configuration scripts for beanstalk. 

It's going to be a bit tricky because until AWS kills off the old platform (if they ever do), we might need to somehow support two different configuration formats for beanstalk.

**Comment by key88sf** [comment] 2018-01-29 02:15
I use NGINX_SERVER_NAME and it works fine until about a month goes by, and then I get this same issue. Once it happens the only solution has been to re-install a new beanstalk environment from scratch again.

**Comment by chadawagner** [comment] 2018-03-26 22:37
I think https://github.com/metabase/metabase/pull/7204 may help with this issue

**Comment by lohrmann** [comment] 2018-05-11 00:28
This seems to be working for me now (0.29.0). 

One aside: When using elastic beanstalk, the 5xx requests are counted as a deterioration of instance health (although intended) and hence result in a lot of notification emails. AWS Support has suggested to set `access_log  off;` for any intended 5xx returns (i.e. non-valid hostnames).

**Comment by camsaul** [comment] 2019-08-28 23:44
Fixed by #6722 & #10753

**Closed by camsaul** 2019-08-28 23:44 UTC
Labels: Operation/Elastic Beanstalk, Priority:P2, Type:Bug
