### ISSUE TITLE
Can't create a "Custom Expression" with a database field starting with "count"

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#10470] opened 2019-08-02 04:40 UTC
**Describe the bug**
I've got a table with a number field called "Counter", I wanted to sum them up as part of a "Custom Expression". I get an error "Expected field name, number, or expression but found  'count'" in the expression dialog.

**Logs**
Errors in the javascript console, screenshot:
![image](https://user-images.githubusercontent.com/4504437/62344754-685ef280-b543-11e9-9335-6991345f6c48.png)

**To Reproduce**
1. Create table with a number field called "Counter"
2. Query editor, Custom Expression
3. type `sum(Counter)` or select from the drop down
4. Error is presented

**Expected behavior**
I'd like to be able to use my Counter field in custom expressions.

**Screenshots**
Error in the Custom Expression dialog
![image](https://user-images.githubusercontent.com/4504437/62344173-174dff00-b541-11e9-8d4d-45f61d16a0f2.png)

**Information about your Metabase Installation:**
- Your browser and the version: Chrome Version 75.0.3770.142 (Official Build) (64-bit)
- Your operating system: Windows 7
- Your databases: MS SQL 2014
- Metabase version: v0.32.10, v0.33.0-RC1
- Metabase hosting environment: Windows server, jar file
- Metabase internal database: Postgres
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

**Severity**
Preventing usage of the custom expressions for some fields, can work around with native SQL queries but annoying.

**Additional context**
I'd guess it's going to impact other field names ath use key words but I don't have any handy to try it out.

**Comment by flamber** [comment] 2019-08-02 04:57
Hi @notrom 
It looks like a duplicate of #7373 - a work-around is to add quotes around `Sum("Counter")`, which then disappears once you leave the field, but allows you to save. If you focus the field again, then you need to reapply the quotes.

**Closed** 2019-08-02 16:27 UTC
Labels: Duplicate, Type:Bug
