### ISSUE TITLE
 Include the possibility of selecting colors using the Hexadecimal code.

### ISSUE THREAD

**Issue by renatofritola** [metabase/metabase#12757] opened 2020-06-23 11:46 UTC
This option is necessary to be able to separate categories of records by specific colors.
Currently there are only 6 predefined colors, which is not enough.

The inclusion of this possibility will increase the gain in viewing reports and dashboards.

**Comment by flamber** [comment] 2020-06-23 12:45
Metabase has 9 predefined colors. Duplicate of #9682

**Closed by flamber** 2020-06-23 12:45 UTC
Labels: .Needs Triage, Type:New Feature
