### ISSUE TITLE
[dc.js migration] dashcards look wonky after resizing

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#40206] opened 2024-03-15 22:02 UTC
dashboard/1907
https://metaboat.slack.com/archives/C06G94JTWBS/p1710540091417669?thread_ts=1710343866.091029&cid=C06G94JTWBS

**Comment by JesseSDevaney** [comment] 2024-03-26 22:13
Could reproduce on the original dashboard, but I could not reproduce the behavior locally. Also, after duplicating the wonky dashboard, removing all but 2 of the wonky dash-cards, and refreshing the page, it appears that the behavior no longer occurs. So I think the issue has something to do with the number of dash-cards being rendered. 

Spent quite some time on this, so I am going to move on from this issue for now.

---
**Summary**: When resizing a large dashboard, it appears that dash-cards are undergoing 2 or more rendering cycles. We get the weird visualizations displayed when the dash-card is not able to complete the 2nd or last rendering cycle. If you look at the width of the x-axis for the dash-card when the wonky resizing occurs, you can see that the x-axis/visualization is not taking up the full-space it has available, potentially part of the problem.

**Duplicated Dashboard**: `dashboard/2236-testing-duplicate`
- This is a duplicate of `dashboard/1907` with all but two of the dash-cards removed. If you load up this dashboard, you can see that the behavior no longer occurs. And all I did was remove other dash-cards.

**Closed** 2024-04-04 20:57 UTC
Labels: Priority:P2, .echarts-scope, .echarts-regression
