### ISSUE TITLE
Permissions errors when running queries or saving anything

### ISSUE THREAD

**Issue by johnmastro** [metabase/metabase#10897] opened 2019-09-16 16:28 UTC
**Describe the bug**
Since updating to v0.33.2 we're getting "Sorry, you don't have permission to see that" errors when trying to save anything (questions, dashboards, etc) and often even when running queries. The errors occur regardless of whether the user is an admin or not.

There's no single obvious "this is what makes a query error out", but simpler queries are more likely to work than complex ones. Queries with more joins, more aggregates, and/or more window functions are more likely to error out. In all cases the queries work correctly when run directly against the database.

We have two databases configured, one PostgreSQL and one Snowflake, and the same errors occur in both cases.

**Logs**
[Console log](https://gist.github.com/johnmastro/3f4b1636c51fb4d63781e92076b21f65)
[Server log](https://gist.github.com/johnmastro/b9beae279dd918bfae1443dfb57d225d)

**To Reproduce**
1. Click "Ask a Question"
2. Select "Native Query"
3. Enter a query
4. Run it [error probably occurs here]
5. If not, click "Save" and attempt to save the question [error definitely occurs here]

**Expected behavior**
Running queries and saving entities should not cause errors.

**Information about your Metabase Installation:**
- Chrome 76.0
- MacOS 10.14.6
- PostgreSQL and Snowflake
- 0.33.2
- ECS
- RDS MySQL

**Severity**
Blocking our ability to add any new questions or dashboards or modify existing ones, which is having a fairly large impact

**Comment by johnmastro** [comment] 2019-09-16 16:53
Because this is pretty disruptive (we have business users that are eager to modify/add new questions and dashboards) we're considering reverting to an earlier version, say 0.33.1 or 0.33.0.

Is that a plausible option since it's the same major version, or would be likely run into problems?

**Comment by flyingmachine** [comment] 2019-09-16 19:54
Sorry this is impacting you, and thank you for creating a bug report. I'm wondering if this might actually be an issue connecting to MySQL? In the backend logs you shared, I'm seeing this: `:sql-exception-chain ["SQLNonTransientConnectionException:" "Message: (conn=6628) Connection timed out (Write failed)" "SQLState: 08" "Error Code: 0"]}
`.

It looks like there's a separate issue with using Amazon Aurora MySQL with version 0.33.0 that might be related: https://github.com/metabase/metabase/issues/10709

I'm going to continue trying to reproduce the issue. I was wondering, what version of Metabase were you using before 0.33.2?

Thank you!

**Comment by johnmastro** [comment] 2019-09-16 20:30
@flyingmachine Thanks, I'll try to look into the possibility of a connection issue.

Regarding the version, I believe we were on 0.33.1. We definitely used 0.33.0, and I don't specifically remember seeing 0.33.1 in the version screen, but we were updating automatically so I assume we probably used each version (?)

**Comment by johnmastro** [comment] 2019-09-17 15:32
@flyingmachine I can't find any evidence of connection issues. Also, I experimented with re-trying actions, which I would expect to then sometimes succeed if the issue were transient connection issues, but if something doesn't work it will continue to fail reliably

**Comment by johnmastro** [comment] 2019-09-17 16:03
@flyingmachine what do you think about the idea of reverting to 0.33.1 or 0.33.0 temporarily, would that be expected to work?

**Comment by flyingmachine** [comment] 2019-09-23 14:50
@johnmastro thanks for looking for connection issues! I'm looking into this more and these additional details will help me figure out the underlying cause. As for reverting to a 0.33.1 or 0.33.0, I can't say with certainty that that will help because I haven't been able to reproduce the issue on my end - sorry about that! But if you do use an earlier version and can let us know the result I'd appreciate that!

**Comment by flyingmachine** [comment] 2019-09-23 22:30
Hi again @johnmastro - just to clarify, my suspicion is that this might somehow be tied to an issue with connecting the MySQL db rather than postgres or snowflake. The exceptions I saw in your logs all had `write failed` in them, and it makes me wonder if there are some cases where Metabase is trying to write to the MySQL db and some cases where it isn't. Are you able do things like add users or save settings?

**Comment by johnmastro** [comment] 2019-09-25 18:33
@flyingmachine Yes, we can add users and change settings (I tried adjusting permissions).

Also, we just came across the scenario where, given two semantically-identical queries (the only difference being the order of conditions in the `where` clause), one consistently works and one consistently fails with the permissions error. In both cases I'm starting from the main page, clicking "ask a question", then "native query", then pasting in the question and running the query.

The query that reliably works (table and column names obfuscated):

```sql
select *
from the_table
where column_1 is null
    and column_2 = 'value'
limit 5
```

The query that reliably fails (table and column names again obfuscated):

```sql
select *
from the_table
where column_2 = 'value'
    and column_1 is null
limit 5
```

At least from my understanding of what's likely happening under the hood, I can't think of any reason related to access to the MySQL instance why the first query would reliably work and the second would reliably fail.

**Comment by flyingmachine** [comment] 2019-09-26 22:25
@johnmastro thanks for your help, I'm going to have another look at this tomorrow

**Comment by flyingmachine** [comment] 2019-09-27 15:18
@johnmastro while I'm looking into this, would it be possible to share the logs that are printed when the query you mentioned in your most recent comment fails?

**Comment by johnmastro** [comment] 2019-09-27 16:10
@flyingmachine the only thing logged on the server (I believe unrelated) was 

```
09-27 16:07:53 [1mDEBUG middleware.log[0m :: [32mGET /api/automagic-dashboards/database/8/candidates 200 213.7 ms (7 DB calls) Jetty threads: 3/50 (9 idle, 0 queued) (105 total active threads) Queries in flight: 0[0m
```

and in the JavaScript console

```
app-main.bundle.js?fd220da862d7458722d7:1 POST https://meta.[redacted].com/api/dataset 403
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:1
value @ app-main.bundle.js?fd220da862d7458722d7:1
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:1
c @ vendor.bundle.js?fd220da862d7458722d7:1
m._invoke @ vendor.bundle.js?fd220da862d7458722d7:1
e.<computed> @ vendor.bundle.js?fd220da862d7458722d7:1
r @ app-main.bundle.js?fd220da862d7458722d7:1
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:1
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:1
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:1
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:1
c @ vendor.bundle.js?fd220da862d7458722d7:1
m._invoke @ vendor.bundle.js?fd220da862d7458722d7:1
e.<computed> @ vendor.bundle.js?fd220da862d7458722d7:1
r @ app-main.bundle.js?fd220da862d7458722d7:1
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:1
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:1
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:1
i @ app-main.bundle.js?fd220da862d7458722d7:1
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:1
c @ vendor.bundle.js?fd220da862d7458722d7:1
m._invoke @ vendor.bundle.js?fd220da862d7458722d7:1
e.<computed> @ vendor.bundle.js?fd220da862d7458722d7:1
r @ app-main.bundle.js?fd220da862d7458722d7:1
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:1
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:1
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:1
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:1
c @ vendor.bundle.js?fd220da862d7458722d7:1
m._invoke @ vendor.bundle.js?fd220da862d7458722d7:1
e.<computed> @ vendor.bundle.js?fd220da862d7458722d7:1
r @ app-main.bundle.js?fd220da862d7458722d7:1
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:1
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:1
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:1
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:1
(anonymous) @ vendor.bundle.js?fd220da862d7458722d7:1
n.handleKeyDown @ app-main.bundle.js?fd220da862d7458722d7:1
Show 8 more frames
app-main.bundle.js?fd220da862d7458722d7:1 Error: {status: 403}
```

**Comment by johnmastro** [comment] 2019-09-27 16:12
Also, we upgraded to 0.33.3 yesterday but haven't observed any change in the behaviors I've described

**Comment by flyingmachine** [comment] 2019-09-27 16:34
Thanks! Just to double check, were there any server logs that looked something like the following?

```
09-27 12:21:11 DEBUG middleware.log :: POST /api/dataset
```

**Comment by johnmastro** [comment] 2019-09-27 16:46
There is when I run the query that succeeds, but not when I run the one that fails

**Comment by flyingmachine** [comment] 2019-09-27 16:58
would it be possible to do a screen sharing session? if you'd like to coordinate that my email address is daniel@metabase.com

**Comment by flyingmachine** [comment] 2019-09-27 21:51
@johnmastro I'm going to be out for a little while, so if you don't hear from me that's why :)

**Comment by johnmastro** [comment] 2019-09-30 15:46
@flyingmachine That sounds good, just sent you an email to coordinate :)

**Comment by flamber** [comment] 2019-10-02 23:38
@flyingmachine I think there's another similar case in the forum.
https://discourse.metabase.com/t/changing-an-existing-question-sorry-you-dont-have-permission-to-see-that/7553

**Comment by mazameli** [comment] 2019-10-03 17:48
Sounds like this issue might be related? https://github.com/metabase/metabase/issues/11048

**Comment by salsakran** [comment] 2019-10-05 22:14
bumping this to an effective p1 since it's been reported by multiple people and makes an instance borderline unusable.

**Comment by flyingmachine** [comment] 2019-10-07 22:50
I'm still having difficulty reproing this issue. I'm documenting what I find when various requests return a 403:

--- 

GET http://localhost:3000/api/card/1

<img width="1307" alt="Screen Shot 2019-10-07 at 6 39 43 PM" src="https://user-images.githubusercontent.com/1421/66354547-22535000-e933-11e9-8dd4-53217ec4d29e.png">

--- 

POST http://localhost:3000/api/card/1/query

<img width="1268" alt="Screen Shot 2019-10-07 at 6 46 54 PM" src="https://user-images.githubusercontent.com/1421/66354553-28493100-e933-11e9-98c5-50a95489c004.png">

---

POST http://localhost:3000/api/dataset

<img width="1329" alt="Screen Shot 2019-10-07 at 6 50 04 PM" src="https://user-images.githubusercontent.com/1421/66354589-53338500-e933-11e9-9d6a-b8381bd6d134.png">

**Comment by flyingmachine** [comment] 2019-10-07 23:23
@johnmastro is your MB instance hosted behind a CDN by chance?

Other than that, I'm continuing to explore the idea that some step in the "check permissions" process is failing and causing a permission check function to return false when it should return true. (Some step other than a lack of permissions, since this is occurring even for admins.)

I'm exploring the possibility that an exception somewhere when accessing the MB database could result in a 403 getting a returned, but at the same time it seems that this is unlikely to be the cause because every time I've tried to "manually" throw an exception the response is a 500 and the exception's message is displayed; the response is not a 403 with the attendant "sorry, you don't have permission to see that". 

I'm hoping that a screen sharing session will let us get to the bottom of this.

**Comment by salsakran** [comment] 2019-10-07 23:25
@flyingmachine is it possible #10816 is the root cause?

**Comment by salsakran** [comment] 2019-10-07 23:25
and if so, that fixing that is the way to go here

**Comment by flyingmachine** [comment] 2019-10-07 23:39
I think fixing #10816 will be helpful here but I don't think it would address the root cause. The annoying thing is that some queries can't be run, and I think users would still be unable to run the queries even if 403's didn't block usage.

**Comment by ralfeus** [comment] 2020-01-07 13:44
I'm not sure I'm having same issue but it looks pretty much similar. When I make any changes in questions or change settings as admin I get "Sorry, you don’t have permission to see that." When I refresh the page it opens fine and changes I tried to made are really made. 
I checked logs and saw the requested URL, which caused the abovementioned error was executed with HTTP 200 result. So most likely it seems to be a client-side issue.

My diagnostic info is below:
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.15.0-72-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "run-mode": "prod",
    "version": {
      "date": "2019-12-19",
      "tag": "v0.34.0",
      "branch": "release-0.34.x",
      "hash": "1335215"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by antoineverger1** [comment] 2020-01-07 20:39
Hey folks, I am running into this issue since the last version bump (to 0.34.0).

Background infos : it's impacting an SQL query which is part of a subcollection. Users that get the 403 and the permission error page don't have any permission except on the given subcollection. 

Hope that helps and BTW, thanks for the great tool you guys provide to the community !

**Comment by aornugent** [comment] 2020-03-11 00:09
Hia, like @antoineverger1 I've started experiencing this issue since 0.34.0. Diagnostics below:

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "5.0.0-1023-azure",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-02-04",
      "tag": "v0.34.2",
      "branch": "release-0.34.x",
      "hash": "dab738c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2020-03-11 00:22
@ralfeus @antoineverger1 @aornugent 

I can almost positively say that you're having a different problem than this issue. You might be seeing some of the same error messages, but with a different root cause.

I would recommend that you either create a new issue or use the [forum](https://discourse.metabase.com/).
Remember to include as much information as possible, like steps on how to reproduce, and if it worked in a previous version (which), and please make sure to test with the latest 0.34.3 first.

**Comment by flamber** [comment] 2020-03-12 18:04
After several debug attempts, it seems like this was caused by an aggressive WAF (in this case CloudFlare).
Similar problem happened with #12097, but that was caused by Azure's WAF.
Closing this issue.

**Closed by flamber** 2020-03-12 18:04 UTC
Labels: Administration/Permissions, Priority:P1, Type:Bug

**Comment by salsakran** [comment] 2020-03-12 18:06
@flamber do you mind making a note about this somewhere in the troubleshooting guide somewhere?
