### ISSUE TITLE
Missing field MongoDB query

### ISSUE THREAD

**Issue by pollyannagoncalves-hotmart** [metabase/metabase#8500] opened 2018-09-11 11:02 UTC
Hi everyone, how are you?

I’m facing an issue on Metabase v0.30.1. I have a MongoDB query where I project a few fields, however one the these fields is inside a nested column, and not always exist. When I run the query this field does not come, even when there are some registers where this field is not null.

Anybody have any ideas what could fix it?

Thankss!

**Comment by priyankinfinnov** [comment] 2018-12-13 04:54
+1

**Comment by flamber** [comment] 2018-12-13 15:12
Duplicate of #4946 ?

**Comment by priyankinfinnov** [comment] 2018-12-13 16:20
Yes.

**Comment by salsakran** [comment] 2018-12-28 03:59
closing as a dupe

**Closed by salsakran** 2018-12-28 03:59 UTC
