### ISSUE TITLE
chart shows 24:00 if labels are daily

### ISSUE THREAD

**Issue by dah33** [metabase/metabase#14600] opened 2021-02-01 09:35 UTC
Run this SQL:

```
SELECT date_trunc('hour','2021-02-01 09:30:11'::datetime) as created_at, 2.0 as score
UNION ALL
SELECT date_trunc('hour','2021-02-01 13:21:01'::datetime), 3.0
UNION ALL
SELECT date_trunc('hour','2021-01-10 11:21:01'::datetime), 1.0
```

The chart shows 

![image](https://user-images.githubusercontent.com/17231347/106440209-7cedb500-6470-11eb-9083-14c7ea67cddb.png)

I would expect the x-axis to not show any timestamp if Metabase decides to use date granularity for the labels. The choice of 24:00 might be related to #14599.

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.198-152.320.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-12-03",
      "tag": "v0.37.3",
      "branch": "release-x.37.x",
      "hash": "2f1e783"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2021-02-01 10:44
Duplicate of #3842 - workaround is to change visualization Settings > Axis > X-axis scale = Ordinal

**Closed by flamber** 2021-02-01 10:44 UTC
Labels: .Needs Triage, Type:Bug
