### ISSUE TITLE
Filter by > Date > Exclude > "is/not empty" applies the opposite of what was selected

### ISSUE THREAD

**Issue by andrewler** [metabase/metabase#29713] opened 2023-03-31 05:10 UTC
**Describe the bug**
When using "Exclude" date filters in questions, I select "is Empty" from the available choices but "is NOT Empty" is applied.

**Logs**
Javascript logs: https://pastebin.com/kACxHXH8
Metabase logs: https://pastebin.com/wZ2fDSKN

**To Reproduce**
1. DATA > Browse data > Sample Database > Invoices
2. Filter > Date Received > ... > Exclude... > "is empty"
3. "is NOT empty" is applied

**Expected behavior**
When selecting "is empty", "is empty" filter should be applied.  Not "is NOT empty"

**Screenshots/videos**
Video: https://streamable.com/vkko7x

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.11.0-41-generic",
    "user.language": "en",
    "user.timezone": "Asia/Seoul"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.35"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-03-28",
      "tag": "v0.46.0",
      "branch": "release-x.46.x",
      "hash": "0ca7df3"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Not blocking but extremely annoying and hard for some users to understand and work around the issue since it was working as expected before we updated to 0.46.0

**Additional context**

**Comment by nemanjaglumac** [comment] 2023-03-31 08:41
Duplicate of https://github.com/metabase/metabase/issues/26771

**Closed by nemanjaglumac** 2023-03-31 08:41 UTC
Labels: Type:Bug, .Needs Triage
