### ISSUE TITLE
Splitting an optionnal SQL variable into multiple lines

### ISSUE THREAD

**Issue by stem** [metabase/metabase#4657] opened 2017-03-31 09:19 UTC
Hi,

First of all : thank you for this great software 👍 

- my browser and the version: Safari 10.0.3
- my operating system: OS X 10.12.3 on the client, some linux on the server
- my database: postgres 9.6
- Metabase version: 0.23.0 or 0.23.1
- Metabase hosting environment: heroku like
- Metabase internal database: postgres 9.6

I've some queries that have been working fine before upgrading to 0.23.0 or 0.23.1.
One of the problem I found is the following syntax :
```
SELECT *
FROM compta
WHERE true
[[ AND (
     "Libellé" = {{text}}
  OR "Pièce"   = {{text}}
) ]]
```
which generate this error message : `ERREUR: erreur de syntaxe sur ou près de « [ » Position: XXXX`

I've found that starting with 0.23.0 optional variables cannot be on multiple lines so this example should be rewriten like this :
```
SELECT *
FROM compta
WHERE true
[[ AND ("Libellé" = {{text}} OR "Pièce" = {{text}}) ]]
```

On a simple example like this, this is not a big deal, but for more complexe use case where you want to inject a variable with some additional hard written conditions, it rapidly grows to a very long and difficult to read line :(

**Comment by flamber** [comment] 2019-02-14 07:28
Hi @stem 
I've cannot reproduce this issue on 0.31.2 - could you try that version and see if it works for you?
Tested with sample data with this query:
```SQL
SELECT *
FROM PRODUCTS
WHERE TRUE
[[AND (
     TITLE    = {{text}}
  OR CATEGORY = {{text}}
)]]
LIMIT 10
```

**Comment by flamber** [comment] 2020-03-02 18:31
Closing issue because of no reply and I cannot reproduce on 0.34.3

**Closed by flamber** 2020-03-02 18:31 UTC
Labels: Querying/Parameters & Variables, Querying/Processor
