### ISSUE TITLE
Currency can not be undefined when style is "currency" when sending subscriptions (and you don't get the sign on the field)

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#43165] opened 2024-05-24 23:40 UTC
### Describe the bug

Probably won't cause any problem but if you do a custom expression, make the field format as currencym, use one of the new viz's and make a subscription, then you get the error in the logs

### To Reproduce

1) make this query (see that the s tax is a custom expression)
![image](https://github.com/metabase/metabase/assets/1711649/00985968-e0bd-4d29-8b3f-81400d5b012a)

2) use an area chart
![image](https://github.com/metabase/metabase/assets/1711649/f8b57519-bfb0-4d0f-9a70-fe50dddf62fb)

3) make sure tax is a currency

4) add the chart to a dashboard and send a subscription, hit that in the logs

### Expected behavior

there should be no error and the currency sign should be on the subscription chart

### Logs

```
Error formatting number TypeError: Currency can not be undefined when style is "currency".
Error formatting number TypeError: Currency can not be undefined when style is "currency".
Error formatting number TypeError: Currency can not be undefined when style is "currency".
Error formatting number TypeError: Currency can not be undefined when style is "currency".
Error formatting number TypeError: Currency can not be undefined when style is "currency".
Error formatting number TypeError: Currency can not be undefined when style is "currency".
Error formatting number TypeError: Currency can not be undefined when style is "currency".
Error formatting number TypeError: Currency can not be undefined when style is "currency".
Error formatting number TypeError: Currency can not be undefined when style is "currency".
Error formatting number TypeError: Currency can not be undefined when style is "currency".
Error formatting number TypeError: Currency can not be undefined when style is "currency".
Error formatting number TypeError: Currency can not be undefined when style is "currency".
Error formatting number TypeError: Currency can not be undefined when style is "currency".
2024-05-24 23:28:13,327 DEBUG middleware.log :: POST /api/pulse/test 200 5.7 s (77 DB calls) App DB connections: 0/7 Jetty threads: 7/50 (9 idle, 0 queued) (94 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/2 (0 threads blocked) {:metabase-user-id 1}

```

### Information about your Metabase installation

```JSON
v50
```

### Severity

P2

### Additional context

this is the chart (check the dollar sign on the x-axis)
![image](https://github.com/metabase/metabase/assets/1711649/52de0e0b-68a8-42af-a182-34c5c36eba8c)

this is the subscription
![image](https://github.com/metabase/metabase/assets/1711649/297289f2-7d9a-41b5-a570-3dbc7a1c3f84)

**Comment by EmmadUsmani** [comment] 2024-07-31 20:26
Tried reproducing, looks like it's fixed now.

https://github.com/user-attachments/assets/6158fefb-0785-4db1-8df8-df8d3a6f229d

**Closed by EmmadUsmani** 2024-07-31 20:26 UTC
Labels: Type:Bug, Priority:P2, Reporting/Pulses, Customization/Formatting, Visualization/Charts, Querying/Notebook/Custom Expression, .Team/DashViz
