### ISSUE TITLE
Google Analytics graph on dashboard doesn't support 'Add a Filter' by date 

### ISSUE THREAD

**Issue by stephenwspann** [metabase/metabase#4766] opened 2017-04-12 05:42 UTC
When you create a graph with data from Google Analytics in a dashboard, the 'Add a Filter' by 'Time' functionality doesn't work with data from Google Analytics.

Data for bug report:

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
`Chrome Version 57.0.2987.133 (64-bit)... via the 'link' icon in the OS X App`

- Your operating system: (e.x. OS X 10, Windows XP, etc)
`OS X 10.12.3`

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
`MySQL (Working), Google Analytics (Not Working)`

- Metabase version: (e.x. 0.19.3)
`You're on version v0.23.1
Built on 2017-03-30`

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
`Installed the Mac app, but load Metabase in Chrome via the 'link' icon in the upper right of the app`

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
`Not sure... whatever the OS X app uses.`

- *Repeatable steps to reproduce the issue*

1. Set up Metabase to connect to a Google Analytics account/database
2. Create a question for the graph... ex:

```
Users in the past 30 days:
{
  "ids": "ga:999999999",
  "start-date": "30daysAgo",
  "end-date": "yesterday",
  "metrics": "ga:users",
  "dimensions": "ga:date",
  "sort": "ga:date",
  "segment": "gaid::-2",
  "include-empty-rows": false,
  "max-results": 2000
}
```

3. After creating the question, add the question to an existing dashboard
4. Open the dashboard page, and click the pencil (Edit Dashboard) icon
5. Click the Filter+ icon (Add a Filter)
6. On the 'What do you want to filter?' menu, select 'Time'
7. On the 'What kind of filter?' menu, select 'Single Date' 
8. In the 'Select the field that should be filtered for each card' interface, select 'Date' for the Google Analytics graph
9. Click 'Save' on the 'You are editing a dashboard' toast
10. Observe there is an option to filter by date on the dashboard
11. Click the filter by date dropdown, and select a date with known data points
12. Observe the Google Analytics graph shows a warning triangle with a tooltip saying 'There was a problem displaying this chart.'
13. (Optional) observe other graphs, such as MySQL-based questions, obey the filter.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by toddheslin** [comment] 2017-09-08 05:10
Adding some colour from my own experience. This works fine if you use the query builder, but does not when you use the JSON builder.

**Comment by flamber** [comment] 2020-05-24 17:20
This is caused by Google Analytics not supporting multiple date filters. It shows the error:
`Multiple date filters are not supported in filters`
Removing the date filter from the question, will allow you to set a filter on the dashboard.
This would require #2763 to be "fixed".

Metabase currently doesn't support filter variables for Native query on Google Analytics.
#6320 - upvote by clicking :+1: on the first post

**Comment by camsaul** [comment] 2023-06-28 17:22
Closing as not planned due to dropping GA support

**Closed by camsaul** 2023-06-28 17:22 UTC
Labels: Type:Bug, Priority:P2, .Limitation, Database/Google Analytics
