### ISSUE TITLE
"All columns" in costum question cannot be deselected

### ISSUE THREAD

**Issue by maxschloegl** [metabase/metabase#12043] opened 2020-03-04 13:35 UTC
**Describe the bug**
"All columns" in costum question cannot be deselected. 

**To Reproduce**
1. Open a table. 
2. Click on "Open editor"
3. Click on "Fields"

--> You cannot deselect all fields, just one by one. That only occours to the first table in the question.

**Expected behavior**
That you can deselect all fields

**Screenshots**

![grafik](https://user-images.githubusercontent.com/3726156/75884309-de527180-5e24-11ea-8bd1-f75b9dbab9ff.png)

![grafik](https://user-images.githubusercontent.com/3726156/75884327-e4e0e900-5e24-11ea-8088-581272670c18.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox 73.0.1
- Your operating system: Windows 10 1909
- Your databases: Postgres
- Metabase version: 11.5
- Metabase hosting environment: Debian 10
- Metabase internal database: Postgres

**Comment by flamber** [comment] 2020-03-04 13:42
Duplicate of #10460

**Closed by flamber** 2020-03-04 13:42 UTC
Labels: .Needs Triage, Type:Bug
