### ISSUE TITLE
Environment variables are not shown in Metabse

### ISSUE THREAD

**Issue by AmirTKashi** [metabase/metabase#12661] opened 2020-06-09 01:55 UTC
**Describe the bug**
The environment variables (such as SMTP HOST and SMTP PORT) are not shown in the web application.

**To Reproduce**
Install Metabase (I installed it on a CentOS-7 machine) and set the SMTP environment variables based on this document:
https://www.metabase.com/docs/latest/operations-guide/environment-variables.html

When the installation is complete, go to Metabase > Admin > Email
As you can see the settings look empty (although the settings are effective and you can, for example, invite new members from the email address that you have set).

**Screenshots**
![metabase](https://user-images.githubusercontent.com/40166454/84097260-f0cbe080-a9fb-11ea-9911-f5e294dbde07.png)

**Information about your Metabase Installation:**
- OS: CentOS-7
- Metabase Version: v0.35.4
- Browser: FireFox

**Severity**
When the environment variables are not shown, the user will not know are they really empty or not. And, as a side note, if you put the same information (as you put in the environment config file) in the web interface, the information will disappear. So, I think it's important to show the latest value of these variables in the web interface.

**Comment by flamber** [comment] 2020-06-09 08:25
Duplicate of #12272

**Closed by flamber** 2020-06-09 08:25 UTC
Labels: .Needs Triage, Type:Bug
