### ISSUE TITLE
Running new native query should cancel previous

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#11727] opened 2020-01-15 16:28 UTC
The UI forces you to cancel a running query before clicking ▶️ again. However, if you use cmd+enter to run a query, any previously running query isn't cancelled. 

Mentioned here: https://github.com/metabase/metabase/issues/11713#issuecomment-574735788

**Comment by aejnsn** [comment] 2020-01-15 16:42
@paulrosenzweig Thanks so much!

**Comment by cwurm** [comment] 2022-01-10 14:13
This can cause serious database issues where a single Metabase user can impatiently run a very expensive query many times over by hitting Cmd+Enter several times, probably assuming (incorrectly) that the previous queries get discarded. 

Similarly, a user might have run a bad query (e.g. forgot the WHERE clause) and then fixed it and re-run it using Cmd+Enter instead of hitting the cancel button (I personally rarely hit buttons when there's a keyboard shortcut and I suspect so do many others). The UI is displaying the result of the now-fixed query, there is no indication of queries executing in the background and the user has long moved on, running query after query or even navigating away from the UI - but the queries keep going because they were never killed.

I would think the SQL editor ("Write SQL" / "New question") should really only ever run a single query at a time and always cancel the previous query if it hasn't returned yet by the time a new query is issued or the user navigates away. Maybe there should even be a default adjustable query timeout after which the query is explicitly killed.

**Comment by ranquild** [comment] 2022-04-18 16:59
Fixed by https://github.com/metabase/metabase/pull/12114

**Comment by flamber** [comment] 2022-04-18 17:56
I can still reproduce this - this is specifically when using hotkey to run query.

https://user-images.githubusercontent.com/1447303/163851646-20d8dc25-6585-42c0-a458-1a081691a964.mp4

**Comment by ranquild** [comment] 2022-05-03 09:06
@flamber I believe what you describing is that the underlying SQL query isn't aborted. The frontend simply aborts a request to the backend when cancelling the previous query, but I guess that doesn't cancel the database query. I'll tag this as a backend issue.

**Comment by flamber** [comment] 2022-05-03 09:37
Not sure this is a backend issue. It's correctly cancelling, when using the button, but when using hotkey (CTRL+Enter), then it doesn't cancel previous requests.
But we'll have to see what the backend devs figures out.

**Closed** 2022-05-04 14:13 UTC
Labels: Type:Bug, Priority:P2, .Performance, Querying/Native, .Frontend
