### ISSUE TITLE
Metabase fails to connect after being idle for a while

### ISSUE THREAD

**Issue by wrd90** [metabase/metabase#14842] opened 2021-02-16 10:38 UTC
**Describe the bug**
I am connected to a DB via an SSH tunnel. The initial connection works fine, but after leaving the app idle for a while, the following error message occurs when I try to refresh the contents:

`Socket fail to connect to host:localhost, port:63077. Connection refused (Connection refused)`

**Logs**
[localhost-1613471271456.log](https://github.com/metabase/metabase/files/5987892/localhost-1613471271456.log)
[metabaseLog.txt](https://github.com/metabase/metabase/files/5987919/metabaseLog.txt)

**To Reproduce**
1. Connect to DB via an SSH tunnel
2. Go make a coffee
3. Have a chat with your teammates
4. Come back to your desk
5. Click refresh button

**Expected behavior**
A refreshed DB view

**Screenshots**
<img width="809" alt="Screenshot 2021-02-16 at 11 30 06" src="https://user-images.githubusercontent.com/3441341/108050759-54f27a00-704a-11eb-9be2-e22b151b8ba2.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: see below
- Your operating system:  dito
- Your databases:  dito
- Metabase version: dito
- Metabase hosting environment: dito
- Metabase internal database:  dito
- 
{
  "browser-info": {
    "language": "en-gb",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+9-202002041938",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+9-202002041938",
    "os.name": "Mac OS X",
    "os.version": "10.15.7",
    "user.language": "en",
    "user.timezone": "Europe/Zurich"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "osx",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-02-11",
      "tag": "v0.37.9",
      "branch": "release-x.37.x",
      "hash": "a9a7fc8"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Annoying

**Additional context**

**Comment by flamber** [comment] 2021-02-16 11:26
Duplicate of #10081 - workaround is to create the SSH tunnel manually outside of Metabase and don't use the in-app tunnel.
https://www.metabase.com/docs/latest/administration-guide/01-managing-databases.html#what-if-the-built-in-ssh-tunnels-dont-fit-my-needs

**Closed by flamber** 2021-02-16 11:26 UTC
Labels: .Needs Triage, Type:Bug
