### ISSUE TITLE
Two column dataset, not allowed to create a line/bar chart

### ISSUE THREAD

**Issue by bjgbeelen** [metabase/metabase#24808] opened 2022-08-16 09:45 UTC
**Describe the bug**
I have a dataset of two columns, one with timetamps and with numerical values.
I want to create a very simple timeseries visualisation with the numerical value on the y-axis and the date on the x-axis

Somehow, creating this line or bar chart is not allowed (see screenshot below). It seems the numerical values (second column) is not being recognized (but it is displayed as you can see). 

The strange thing is when i run the SQL code generated by the editor, I get the same dataset, but the line and bar chart (and other options) also become available to me. There is one difference though, the numbers are displayed more 'nicely' as if it better understands the numbers, see second screenshot.

@relferreira have you perhaps experienced similar behaviour?

**Logs**
No specific logs in the browser or server.

**To Reproduce**
1. I pick a table
2. Go to the editor and filter `date_month` on `last 12 months` and summarize on `sum of...` some random numiercal field
3. The ressults get displayed (screenshot 1) but line or bar chart option is disabled.

**Expected behavior**
I would expect to be able to create a line or bar chart using the two columns in the dataset

**Screenshots**
Results when using the UI editor:
<img width="772" alt="image" src="https://user-images.githubusercontent.com/8626944/184841723-4d7f33d4-edc6-4809-ac44-b625aaed8750.png">

Results when executing the SQL query (generated by the editor):
<img width="662" alt="image" src="https://user-images.githubusercontent.com/8626944/184848259-b3c6e6f1-fcbf-43d8-9f6b-7e6b339645b8.png">

When clicking on 'barchart' anyway:

For the x-axis I can pick one of the two columns, so it appears to recognise two columns:
<img width="337" alt="image" src="https://user-images.githubusercontent.com/8626944/184849213-7733e3a7-8c9a-4a3f-bae4-74e3f51b5099.png">

For the y-axis it mentions no columns are available:
<img width="312" alt="image" src="https://user-images.githubusercontent.com/8626944/184849327-0a64b5e5-b1dc-40c4-ac1e-e747df90e0d4.png">

**Information about your Metabase Installation:**

- Browser: Chrome 104.0.5112.79
- Os: OS X 12.4
- Database: Databricks SQL Warehouse (the community databricks adapter from https://github.com/relferreira/metabase-sparksql-databricks-driver)
- Metabase: 0.43.4
- Hosting: docker on a gcp vm
- Internal database: in memory h2 at the moment

**Severity**
High, in the sentence that this is a showstopper for us to start using Metabase as this is something very trivial we would need to work properly. We are currently investigating whether Metabase is the BI tool that we want to work with.

**Comment by flamber** [comment] 2022-08-16 09:57
Hi @bjgbeelen 
Without knowing the metadata for the field, then it's difficult to know, but it looks like it is treated as a string.
Go to `/api/field/123`, where 123 is the field ID that you can find by going to Admin > Data Model > (db) > (table) > (field) :gear: > then look in the URL, which looks like `.../123/general`.
Duplicate of #18953 - see comment for workarounds.

**Closed by flamber** 2022-08-16 09:57 UTC
Labels: Type:Bug, .Needs Triage

**Comment by bjgbeelen** [comment] 2022-08-16 11:50
@flamber thanks for your reply! 

> Without knowing the metadata for the field, then it's difficult to know, but it looks like it is treated as a string.

If you mean metadata in the source database, the field is a `bigint`. Also tried with a column that was a `double`

If you refer to the metadata as specified in the Metabase admin: there was none. It was empty.
I can confirm the explicitly setting the field to a `price` (e.g.) makes it work as expected.

Could the difference between using the editor and the SQL prompt be explained by that using the editor the type as registered in the data model is used and in case a SQL statement is ran it uses the returned data type?

Another question that rises is why the data model does not inference the type from the source table?

**Comment by flamber** [comment] 2022-08-16 12:31
@bjgbeelen If you include the output from `/api/field/:id`, then I can tell you more.

**Comment by bjgbeelen** [comment] 2022-08-18 08:39
hi @flamber ,

Here's the output for `customerid`:

```json
{
	"description": null,
	"database_type": "bigint",
	"semantic_type": null,
	"table_id": 41,
	"coercion_strategy": null,
	"table": {
		"description": null,
		"entity_type": "entity/GenericTable",
		"schema": "dna_prod",
		"db": {
			"description": null,
			"features": ["full-join", "basic-aggregations", "standard-deviation-aggregations", "expression-aggregations", "percentile-aggregations", "foreign-keys", "right-join", "left-join", "native-parameters", "nested-queries", "expressions", "regex", "case-sensitivity-string-filter-options", "binning", "inner-join", "advanced-math-expressions"],
			"cache_field_values_schedule": "0 50 0 * * ? *",
			"timezone": null,
			"auto_run_queries": true,
			"metadata_sync_schedule": "0 50 * * * ? *",
			"name": "xxx",
			"settings": null,
			"caveats": null,
			"creator_id": 1,
			"is_full_sync": true,
			"updated_at": "2022-08-16T08:02:29.098",
			"cache_ttl": null,
			"details": {
				"ssl": true,
				"password": "**MetabasePass**",
				"let-user-control-scheduling": null,
				"port": 443,
				"advanced-options": true,
				"dbname": "xxx",
				"host": "xxxx.gcp.databricks.com",
				"jdbc-flags": ";transportMode=http;ssl=1;AuthMech=3;httpPath=/sql/1.0/endpoints/xxxx;UID=token;PWD=xxx",
				"user": "token"
			},
			"is_sample": false,
			"id": 2,
			"is_on_demand": false,
			"options": null,
			"engine": "sparksql-databricks",
			"initial_sync_status": "complete",
			"refingerprint": null,
			"created_at": "2022-08-16T08:02:02.746",
			"points_of_interest": null
		},
		"show_in_getting_started": false,
		"name": "fct_mrr",
		"caveats": null,
		"updated_at": "2022-08-16T08:04:40.791",
		"active": true,
		"id": 41,
		"db_id": 2,
		"visibility_type": null,
		"field_order": "database",
		"initial_sync_status": "complete",
		"display_name": "Fct Mrr",
		"created_at": "2022-08-16T08:02:04.385",
		"points_of_interest": null
	},
	"name": "customerid",
	"fingerprint_version": 5,
	"has_field_values": "none",
	"settings": null,
	"caveats": null,
	"fk_target_field_id": null,
	"dimensions": [],
	"updated_at": "2022-08-16T08:04:17.023",
	"custom_position": 0,
	"effective_type": "type/BigInteger",
	"active": true,
	"nfc_path": null,
	"parent_id": null,
	"id": 439,
	"last_analyzed": "2022-08-16T08:04:40.814",
	"position": 2,
	"visibility_type": "normal",
	"preview_display": true,
	"display_name": "Customerid",
	"database_position": 2,
	"name_field": null,
	"fingerprint": {
		"global": {
			"distinct-count": 228,
			"nil%": 0.0
		},
		"type": {
			"type/Number": {
				"min": 9.0,
				"q1": 582.5166708924949,
				"q3": 1172.8590822172123,
				"max": 1538.0,
				"sd": 384.8964893072734,
				"avg": 861.6809
			}
		}
	},
	"created_at": "2022-08-16T08:02:21.639",
	"base_type": "type/BigInteger",
	"points_of_interest": null
}
```

**Comment by flamber** [comment] 2022-08-18 09:29
@bjgbeelen Everything in that field metadata looks normal and should work. I cannot tell if it is a problem with the custom driver you're using, but it looks like it. You would have to look at the returned query metadata, which contains information about columns. Open your browser developer Network-tab and look at the request, when running the GUI question.
