### ISSUE TITLE
Exports of Pivot Table do not have the same positioning as columns

### ISSUE THREAD

**Issue by HumbertoLimaa** [metabase/metabase#15053] opened 2021-03-03 19:33 UTC
In version 0.38.1, when you export the PivotTable to XLSX, the information in the columns inside Excel is rows

Example:

In metabase:
![image](https://user-images.githubusercontent.com/56941229/109860568-190c0700-7c3d-11eb-8e13-23e83118088d.png)

In excel:
![image](https://user-images.githubusercontent.com/56941229/109860840-61c3c000-7c3d-11eb-9412-235bda743aae.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/56941229/109861450-10680080-7c3e-11eb-89c2-13d8d6694e31.png)

**Comment by flamber** [comment] 2021-03-03 19:40
Duplicate of #2473

**Closed by flamber** 2021-03-03 19:40 UTC
