### ISSUE TITLE
Migrations fails during upgrade to 0.50.14

### ISSUE THREAD

**Issue by pratesy** [metabase/metabase#46005] opened 2024-07-23 16:15 UTC
### Describe the bug

Upgrade Meatabse from 0.50.14 got the following error.

`2024-07-23T16:11:11.153Z INFO  - v0.50.14 Pulling from metabase/metabase
2024-07-23T16:11:11.154Z INFO  -  Digest: sha256:2cb63f8b3145516c0b245b9c6647bbce689436233a690a3803c86666b9b18fe7
2024-07-23T16:11:11.155Z INFO  -  Status: Image is up to date for metabase/metabase:v0.50.14
2024-07-23T16:11:11.166Z INFO  - Pull Image successful, Time taken: 1 Seconds
2024-07-23T16:11:11.172Z INFO  - Starting container for site
2024-07-23T16:11:11.173Z INFO  - docker run -d --expose=3000 --name app-metabase-size_0_85dcc28c -e WEBSITE_USE_DIAGNOSTIC_SERVER=false -e WEBSITES_ENABLE_APP_SERVICE_STORAGE=false -e WEBSITE_SITE_NAME=app-metabase-size -e WEBSITE_AUTH_ENABLED=False -e PORT=3000 -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=app-metabase-size.azurewebsites.net -e WEBSITE_INSTANCE_ID=8846bb390c5bca9e48006c82c6fd32a455abf47d795f7fc5cd48aeb21a10394c metabase/metabase:v0.50.14
2024-07-23T16:11:11.173Z INFO  - Logging is not enabled for this container.Please use https://aka.ms/linux-diagnostics to enable logging to see container logs here.
2024-07-23T16:11:11.378Z INFO  - Initiating warmup request to container app-metabase-size_0_85dcc28c for site app-metabase-size
2024-07-23T16:11:13.203193451Z Warning: environ value jdk-11.0.23+9 for key :java-version has been overwritten with 11.0.23
2024-07-23T16:11:16.078157261Z 2024-07-23 16:11:16,076 INFO metabase.util :: Maximum memory available to JVM: 6.6 GB
2024-07-23T16:11:18.613248037Z 2024-07-23 16:11:18,612 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
2024-07-23T16:11:18.613302838Z  For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
2024-07-23T16:11:24.255690113Z 2024-07-23 16:11:24,255 INFO driver.impl :: [34mRegistered abstract driver :sql[0m  🚚
2024-07-23T16:11:24.263507313Z 2024-07-23 16:11:24,263 INFO driver.impl :: [34mRegistered abstract driver :sql-jdbc[0m (parents: [:sql]) 🚚
2024-07-23T16:11:24.270394000Z 2024-07-23 16:11:24,270 INFO metabase.util :: [32mLoad driver :sql-jdbc took 44.8 ms[0m
2024-07-23T16:11:24.270640204Z 2024-07-23 16:11:24,270 INFO driver.impl :: [34mRegistered driver :h2[0m (parents: [:sql-jdbc]) 🚚
2024-07-23T16:11:24.458933702Z 2024-07-23 16:11:24,458 INFO driver.impl :: [34mRegistered driver :mysql[0m (parents: [:sql-jdbc]) 🚚
2024-07-23T16:11:24.498277104Z 2024-07-23 16:11:24,498 INFO driver.impl :: [34mRegistered driver :postgres[0m (parents: [:sql-jdbc]) 🚚
2024-07-23T16:11:26.500291701Z 2024-07-23 16:11:26,493 INFO metabase.core ::
2024-07-23T16:11:26.500331401Z Metabase v0.50.14 (26d21b1)
2024-07-23T16:11:26.500337301Z
2024-07-23T16:11:26.500340601Z Copyright © 2024 Metabase, Inc.
2024-07-23T16:11:26.500344502Z
2024-07-23T16:11:26.500347702Z Metabase Enterprise Edition extensions are NOT PRESENT.
2024-07-23T16:11:26.505267164Z 2024-07-23 16:11:26,504 INFO metabase.core :: Starting Metabase in STANDALONE mode
2024-07-23T16:11:26.555913108Z 2024-07-23 16:11:26,555 INFO metabase.server :: Launching Embedded Jetty Webserver with config:
2024-07-23T16:11:26.555961508Z  {:port 3000, :host "0.0.0.0"}
2024-07-23T16:11:26.555969708Z
2024-07-23T16:11:26.605729741Z 2024-07-23 16:11:26,605 INFO metabase.core :: Starting Metabase version v0.50.14 (26d21b1) ...
2024-07-23T16:11:26.610102196Z 2024-07-23 16:11:26,609 INFO metabase.core :: System info:
2024-07-23T16:11:26.610131097Z  {"file.encoding" "UTF-8",
2024-07-23T16:11:26.610136897Z  "java.runtime.name" "OpenJDK Runtime Environment",
2024-07-23T16:11:26.610140997Z  "java.runtime.version" "11.0.23+9",
2024-07-23T16:11:26.610148397Z  "java.vendor" "Eclipse Adoptium",
2024-07-23T16:11:26.610152197Z  "java.vendor.url" "https://adoptium.net/",
2024-07-23T16:11:26.610156497Z  "java.version" "11.0.23",
2024-07-23T16:11:26.610160097Z  "java.vm.name" "OpenJDK 64-Bit Server VM",
2024-07-23T16:11:26.610164397Z  "java.vm.version" "11.0.23+9",
2024-07-23T16:11:26.610167997Z  "os.name" "Linux",
2024-07-23T16:11:26.610185798Z  "os.version" "5.15.153.1-2.cm2",
2024-07-23T16:11:26.610190298Z  "user.language" "en",
2024-07-23T16:11:26.610194798Z  "user.timezone" "GMT"}
2024-07-23T16:11:26.610198298Z
2024-07-23T16:11:26.611846919Z 2024-07-23 16:11:26,611 INFO metabase.plugins :: Loading plugins in /plugins...
2024-07-23T16:11:26.768494910Z 2024-07-23 16:11:26,768 INFO util.files :: Extract file /modules/snowflake.metabase-driver.jar -> /plugins/snowflake.metabase-driver.jar
2024-07-23T16:11:27.122705412Z 2024-07-23 16:11:27,121 INFO util.files :: Extract file /modules/sqlite.metabase-driver.jar -> /plugins/sqlite.metabase-driver.jar
2024-07-23T16:11:27.151506278Z 2024-07-23 16:11:27,151 INFO util.files :: Extract file /modules/bigquery-cloud-sdk.metabase-driver.jar -> /plugins/bigquery-cloud-sdk.metabase-driver.jar
2024-07-23T16:11:27.372824891Z 2024-07-23 16:11:27,372 INFO util.files :: Extract file /modules/sqlserver.metabase-driver.jar -> /plugins/sqlserver.metabase-driver.jar
2024-07-23T16:11:27.381652903Z 2024-07-23 16:11:27,381 INFO util.files :: Extract file /modules/presto-jdbc.metabase-driver.jar -> /plugins/presto-jdbc.metabase-driver.jar
2024-07-23T16:11:27.433818866Z 2024-07-23 16:11:27,433 INFO util.files :: Extract file /modules/druid.metabase-driver.jar -> /plugins/druid.metabase-driver.jar
2024-07-23T16:11:27.437402411Z 2024-07-23 16:11:27,437 INFO util.files :: Extract file /modules/sparksql.metabase-driver.jar -> /plugins/sparksql.metabase-driver.jar
2024-07-23T16:11:27.494422436Z 2024-07-23 16:11:27,494 INFO util.files :: Extract file /modules/oracle.metabase-driver.jar -> /plugins/oracle.metabase-driver.jar
2024-07-23T16:11:27.495848954Z 2024-07-23 16:11:27,495 INFO util.files :: Extract file /modules/mongo.metabase-driver.jar -> /plugins/mongo.metabase-driver.jar
2024-07-23T16:11:27.512883871Z 2024-07-23 16:11:27,512 INFO util.files :: Extract file /modules/redshift.metabase-driver.jar -> /plugins/redshift.metabase-driver.jar
2024-07-23T16:11:27.519396754Z 2024-07-23 16:11:27,519 INFO util.files :: Extract file /modules/vertica.metabase-driver.jar -> /plugins/vertica.metabase-driver.jar
2024-07-23T16:11:27.520560068Z 2024-07-23 16:11:27,520 INFO util.files :: Extract file /modules/athena.metabase-driver.jar -> /plugins/athena.metabase-driver.jar
2024-07-23T16:11:27.599366270Z 2024-07-23 16:11:27,598 INFO util.files :: Extract file /modules/druid-jdbc.metabase-driver.jar -> /plugins/druid-jdbc.metabase-driver.jar
2024-07-23T16:11:27.842154556Z 2024-07-23 16:11:27,841 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :presto-jdbc...[0m
2024-07-23T16:11:27.842775764Z 2024-07-23 16:11:27,842 INFO driver.impl :: [34mRegistered driver :presto-jdbc[0m (parents: [:sql-jdbc]) 🚚
2024-07-23T16:11:27.849061744Z 2024-07-23 16:11:27,848 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :redshift...[0m
2024-07-23T16:11:27.849586350Z 2024-07-23 16:11:27,849 INFO driver.impl :: [34mRegistered driver :redshift[0m (parents: [:postgres]) 🚚
2024-07-23T16:11:28.019086405Z 2024-07-23 16:11:28,018 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :snowflake...[0m
2024-07-23T16:11:28.019568411Z 2024-07-23 16:11:28,019 INFO driver.impl :: [34mRegistered driver :snowflake[0m (parents: [:sql-jdbc]) 🚚
2024-07-23T16:11:28.025286283Z 2024-07-23 16:11:28,025 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :druid-jdbc...[0m
2024-07-23T16:11:28.025706889Z 2024-07-23 16:11:28,025 INFO driver.impl :: [34mRegistered driver :druid-jdbc[0m (parents: [:sql-jdbc]) 🚚
2024-07-23T16:11:28.031875067Z 2024-07-23 16:11:28,031 INFO plugins.dependencies :: [31mMetabase cannot initialize plugin Metabase Oracle Driver due to required dependencies.[0m Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.
2024-07-23T16:11:28.031902568Z
2024-07-23T16:11:28.033320186Z 2024-07-23 16:11:28,033 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
2024-07-23T16:11:28.033944294Z 2024-07-23 16:11:28,033 INFO plugins.dependencies :: [33mPlugins with unsatisfied deps: ["Metabase Oracle Driver"][0m
2024-07-23T16:11:28.036727229Z 2024-07-23 16:11:28,036 INFO plugins.dependencies :: [31mMetabase cannot initialize plugin Metabase Vertica Driver due to required dependencies.[0m Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.
2024-07-23T16:11:28.036755529Z
2024-07-23T16:11:28.037109634Z 2024-07-23 16:11:28,036 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
2024-07-23T16:11:28.037580140Z 2024-07-23 16:11:28,037 INFO plugins.dependencies :: [33mPlugins with unsatisfied deps: ["Metabase Vertica Driver" "Metabase Oracle Driver"][0m
2024-07-23T16:11:28.041246186Z 2024-07-23 16:11:28,040 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :sqlserver...[0m
2024-07-23T16:11:28.041794193Z 2024-07-23 16:11:28,041 INFO driver.impl :: [34mRegistered driver :sqlserver[0m (parents: [:sql-jdbc]) 🚚
2024-07-23T16:11:28.059887023Z 2024-07-23 16:11:28,059 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :bigquery-cloud-sdk...[0m
2024-07-23T16:11:28.060170827Z 2024-07-23 16:11:28,059 INFO driver.impl :: [34mRegistered driver :bigquery-cloud-sdk[0m (parents: [:sql]) 🚚
2024-07-23T16:11:28.063422968Z 2024-07-23 16:11:28,063 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :sqlite...[0m
2024-07-23T16:11:28.063794973Z 2024-07-23 16:11:28,063 INFO driver.impl :: [34mRegistered driver :sqlite[0m (parents: [:sql-jdbc]) 🚚
2024-07-23T16:11:28.073428995Z 2024-07-23 16:11:28,073 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :athena...[0m
2024-07-23T16:11:28.073877201Z 2024-07-23 16:11:28,073 INFO driver.impl :: [34mRegistered driver :athena[0m (parents: [:sql-jdbc]) 🚚
2024-07-23T16:11:28.077397746Z 2024-07-23 16:11:28,077 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :druid...[0m
2024-07-23T16:11:28.077747350Z 2024-07-23 16:11:28,077 INFO driver.impl :: [34mRegistered driver :druid[0m  🚚
2024-07-23T16:11:28.084787440Z 2024-07-23 16:11:28,084 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :hive-like...[0m
2024-07-23T16:11:28.085111344Z 2024-07-23 16:11:28,084 INFO driver.impl :: [34mRegistered abstract driver :hive-like[0m (parents: [:sql-jdbc]) 🚚
2024-07-23T16:11:28.085530049Z 2024-07-23 16:11:28,085 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :sparksql...[0m
2024-07-23T16:11:28.085849753Z 2024-07-23 16:11:28,085 INFO driver.impl :: [34mRegistered driver :sparksql[0m (parents: [:hive-like]) 🚚
2024-07-23T16:11:28.090885917Z 2024-07-23 16:11:28,090 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :mongo...[0m
2024-07-23T16:11:28.091158121Z 2024-07-23 16:11:28,090 INFO driver.impl :: [34mRegistered driver :mongo[0m  🚚
2024-07-23T16:11:28.097390300Z 2024-07-23 16:11:28,096 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
2024-07-23T16:11:28.099289824Z 2024-07-23 16:11:28,099 INFO db.setup :: [36mVerifying mysql Database Connection ...[0m
2024-07-23T16:11:28.228225663Z 2024-07-23 16:11:28,227 INFO db.setup :: Successfully verified MySQL 8.0.32 application database connection. ✅
2024-07-23T16:11:28.228653968Z 2024-07-23 16:11:28,228 INFO db.setup :: [36mChecking if a database downgrade is required...[0m
2024-07-23T16:11:28.944560068Z 2024-07-23 16:11:28,944 INFO db.setup :: Running Database Migrations...
2024-07-23T16:11:28.946093587Z 2024-07-23 16:11:28,945 INFO db.setup :: Setting up Liquibase...
2024-07-23T16:11:29.153820728Z 2024-07-23 16:11:29,153 INFO db.setup :: Liquibase is ready.
2024-07-23T16:11:29.154096131Z 2024-07-23 16:11:29,153 INFO db.liquibase :: Checking if Database has unrun migrations...
2024-07-23T16:11:29.691853467Z 2024-07-23 16:11:29,684 ERROR metabase.core :: Metabase Initialization FAILED
2024-07-23T16:11:29.691900667Z liquibase.exception.ValidationFailedException: Validation Failed:
2024-07-23T16:11:29.691906767Z      1 changesets check sum
2024-07-23T16:11:29.691910967Z           migrations/001_update_migrations.yaml::v50.2024-02-26T22:15:54::noahmoss was: 9:838ed8f582c11e79f574db21b2dcb999 but is now: 9:29e840f2e163f8795c220faee8201c81
2024-07-23T16:11:29.691915868Z
2024-07-23T16:11:29.691920468Z 	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:358)
2024-07-23T16:11:29.691925468Z 	at liquibase.Liquibase.lambda$listUnrunChangeSets$20(Liquibase.java:1149)
2024-07-23T16:11:29.691929268Z 	at liquibase.Scope.lambda$child$0(Scope.java:186)
2024-07-23T16:11:29.691933068Z 	at liquibase.Scope.child(Scope.java:195)
2024-07-23T16:11:29.691950468Z 	at liquibase.Scope.child(Scope.java:185)
2024-07-23T16:11:29.691953568Z 	at liquibase.Scope.child(Scope.java:164)
2024-07-23T16:11:29.691956268Z 	at liquibase.Liquibase.runInScope(Liquibase.java:1419)
2024-07-23T16:11:29.691959068Z 	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1141)
2024-07-23T16:11:29.691961968Z 	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1131)
2024-07-23T16:11:29.691964468Z 	at metabase.db.liquibase$unrun_migrations$fn__44491.invoke(liquibase.clj:186)
2024-07-23T16:11:29.691968268Z 	at metabase.db.liquibase$do_with_liquibase$f_STAR___44476.invoke(liquibase.clj:140)
2024-07-23T16:11:29.691972168Z 	at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:150)
2024-07-23T16:11:29.691976468Z 	at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:131)
2024-07-23T16:11:29.691982668Z 	at metabase.db.liquibase$unrun_migrations.invokeStatic(liquibase.clj:185)
2024-07-23T16:11:29.691986868Z 	at metabase.db.liquibase$unrun_migrations.invoke(liquibase.clj:176)
2024-07-23T16:11:29.691990869Z 	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:346)
2024-07-23T16:11:29.691995069Z 	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:342)
2024-07-23T16:11:29.691998969Z 	at metabase.db.setup$migrate_BANG_$fn__53475.invoke(setup.clj:84)
2024-07-23T16:11:29.692002769Z 	at metabase.db.liquibase$do_with_liquibase$f_STAR___44476.invoke(liquibase.clj:140)
2024-07-23T16:11:29.692007169Z 	at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:143)
2024-07-23T16:11:29.692011169Z 	at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:131)
2024-07-23T16:11:29.692015669Z 	at metabase.db.setup$migrate_BANG_.invokeStatic(setup.clj:73)
2024-07-23T16:11:29.692019869Z 	at metabase.db.setup$migrate_BANG_.doInvoke(setup.clj:55)
2024-07-23T16:11:29.692024069Z 	at clojure.lang.RestFn.invoke(RestFn.java:425)
2024-07-23T16:11:29.692028169Z 	at metabase.db.setup$run_schema_migrations_BANG_.invokeStatic(setup.clj:149)
2024-07-23T16:11:29.692033669Z 	at metabase.db.setup$run_schema_migrations_BANG_.invoke(setup.clj:144)
2024-07-23T16:11:29.692037769Z 	at metabase.db.setup$setup_db_BANG_$fn__53503$fn__53504.invoke(setup.clj:167)
2024-07-23T16:11:29.692041469Z 	at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
2024-07-23T16:11:29.692045369Z 	at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
2024-07-23T16:11:29.692049969Z 	at metabase.db.setup$setup_db_BANG_$fn__53503.invoke(setup.clj:161)
2024-07-23T16:11:29.692054369Z 	at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:160)
2024-07-23T16:11:29.692058269Z 	at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:153)
2024-07-23T16:11:29.692061969Z 	at metabase.db$setup_db_BANG_$fn__53528.invoke(db.clj:86)
2024-07-23T16:11:29.692070570Z 	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:81)
2024-07-23T16:11:29.692075070Z 	at metabase.db$setup_db_BANG_.doInvoke(db.clj:68)
2024-07-23T16:11:29.692078970Z 	at clojure.lang.RestFn.invoke(RestFn.java:421)
2024-07-23T16:11:29.692082970Z 	at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:117)
2024-07-23T16:11:29.692087470Z 	at metabase.core$init_BANG__STAR_.invoke(core.clj:98)
2024-07-23T16:11:29.692091670Z 	at metabase.core$init_BANG_.invokeStatic(core.clj:170)
2024-07-23T16:11:29.692096070Z 	at metabase.core$init_BANG_.invoke(core.clj:165)
2024-07-23T16:11:29.692100370Z 	at metabase.core$start_normally.invokeStatic(core.clj:182)
2024-07-23T16:11:29.692104570Z 	at metabase.core$start_normally.invoke(core.clj:176)
2024-07-23T16:11:29.692108670Z 	at metabase.core$entrypoint.invokeStatic(core.clj:215)
2024-07-23T16:11:29.692112670Z 	at metabase.core$entrypoint.doInvoke(core.clj:209)
2024-07-23T16:11:29.692116770Z 	at clojure.lang.RestFn.invoke(RestFn.java:397)
2024-07-23T16:11:29.692120870Z 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
2024-07-23T16:11:29.692125070Z 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
2024-07-23T16:11:29.692129270Z 	at clojure.lang.Var.applyTo(Var.java:705)
2024-07-23T16:11:29.692133270Z 	at clojure.core$apply.invokeStatic(core.clj:667)
2024-07-23T16:11:29.692137470Z 	at clojure.core$apply.invoke(core.clj:662)
2024-07-23T16:11:29.692141470Z 	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
2024-07-23T16:11:29.692145670Z 	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
2024-07-23T16:11:29.692149371Z 	at clojure.lang.RestFn.invoke(RestFn.java:397)
2024-07-23T16:11:29.692153071Z 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
2024-07-23T16:11:29.692156671Z 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
2024-07-23T16:11:29.692160571Z 	at metabase.bootstrap.main(Unknown Source)
2024-07-23T16:11:29.693979694Z 2024-07-23 16:11:29,693 INFO metabase.core :: Metabase Shutting Down ...
2024-07-23T16:11:29.694571901Z 2024-07-23 16:11:29,694 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
2024-07-23T16:11:29.702846606Z 2024-07-23 16:11:29,702 WARN db.liquibase :: ()
2024-07-23T16:11:29.703195711Z 2024-07-23 16:11:29,703 INFO metabase.core :: Metabase Shutdown COMPLETE
2024-07-23T16:11:41.396Z ERROR - Container app-metabase-size_0_85dcc28c for site app-metabase-size has exited, failing site start
2024-07-23T16:11:41.403Z ERROR - Container app-metabase-size_0_85dcc28c didn't respond to HTTP pings on port: 3000, failing site start. See container logs for debugging.`

### To Reproduce

Change image in docker run command.

### Expected behavior

Migrations successfully finished

### Information about your Metabase installation

```JSON
- Metabase in webapp azure
- Database MySQL 8.0.32
```

### Severity

metabase down

**Comment by ranquild** [comment] 2024-07-23 16:23
Duplicate of https://github.com/metabase/metabase/issues/45967

**Comment by ranquild** [comment] 2024-07-23 16:25
Duplicate of https://github.com/metabase/metabase/issues/45967

**Closed by ranquild** 2024-07-23 16:25 UTC
Labels: Type:Bug, Priority:P1, Operation/Database Migrations, .Backend, .Team/BackendComponents
