### ISSUE TITLE
Deep copy dashboard allows users with "No self-service" data permissions to duplicate questions

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#33098] opened 2023-08-10 16:51 UTC
### Describe the bug

Deep copy (duplicate) dashboard allows users with "No self-service" data permissions to duplicate questions, which they otherwise couldn't.

### To Reproduce

-  Prepare a dashboard with a single question in a root collection
- Make sure "All users" doesn't have data permissions but has collections curate permissions
- Have at least one non-admin user

1. Log in as a normal user
2. Open a dashboard with the question
3. Click on `...` and choose Duplicate
4. Make sure "Only duplicate the dashboard" is NOT checked
5. Click on "Duplicate" button in the modal
6. Go to the root collection or any collection you chose as a target
7. You will see a duplicated question, apart from the duplicated dashboard (which the user should be able to duplicate)

### Expected behavior

Users without data permissions should not be offered a deep copy dashboard option, and they shouldn't be able to duplicate questions.

### Information about your Metabase installation

```JSON
local dev, `master`, 9fef23dc6be04a0b83cd11f9090ee0c71d51b343, H2, Sample Database
```

### Severity

P3 - P2

**Comment by luizarakaki** [comment] 2024-02-06 12:35
This is working as intended...

The ability to duplicate or move items is governed by collection permissions. This user has "curate" permission to the collection, so they can perform these actions.

UX-wise, we try to disable actions that don't make sense for the user. In this case, it is not clear if this is not desirable. We let users without data access to move items. Duplicating is similar.

When the dashboard has a mix of questions the user has data access or not, it is unclear what we should do. Duplicating only parts of the dashboard isn't intuitive and will lead to more problems.

Closing this for now, but happy to discuss if it is unclear

**Closed by luizarakaki** 2024-02-06 12:35 UTC
Labels: Type:Bug, Priority:P3, Reporting/Dashboards, Administration/Permissions, .Product Input Needed, .Team/DashViz
