### ISSUE TITLE
Missing/incorrect data labels on ordinal vertical bar graphs and line graphs

### ISSUE THREAD

**Issue by kamilaberkalieva** [metabase/metabase#16020] opened 2021-05-12 19:54 UTC
Two issues:
1. When I set my visualization to a bar graph and the x-axis scale to Ordinal, some of the data labels are missing when you hover over the bars, while the y-axis label is not recognizing the Style (which I have set to Percent).
2.  When I set my visualization to a line graph, some of the data labels are either missing or completely incorrect when you hover over the series.

**Screenshots**

![Screen Shot 2021-05-12 at 3 52 49 PM](https://user-images.githubusercontent.com/77808105/118036070-1b27cb80-b33a-11eb-9979-13524aa47991.png)

![Screen Shot 2021-05-12 at 3 53 05 PM](https://user-images.githubusercontent.com/77808105/118036098-24b13380-b33a-11eb-8cd1-e958790780c7.png)

**Expected behavior**
The data labels should display the correct numbers. The data label style should also recognize the appropriate Style that it's set to.

**Logs**
![Screen Shot 2021-05-12 at 3 54 10 PM](https://user-images.githubusercontent.com/77808105/118036213-4ca09700-b33a-11eb-9aad-52088e511273.png)

**Severity**
This is severe because it renders the data in the dashboard unusable.

**Comment by paoliniluis** [comment] 2021-05-13 01:46
Hi, we don't know the version you're running, please post the troubleshooting info

**Comment by flamber** [comment] 2021-05-13 10:38
Duplicate of #15998

**Closed by flamber** 2021-05-13 10:38 UTC
Labels: .Needs Triage, Type:Bug
