### ISSUE TITLE
New users see whole feed even if they don't have permissions to something

### ISSUE THREAD

**Issue by ACPK** [metabase/metabase#6794] opened 2018-01-26 21:33 UTC
When a new user signs up, they see the full activity feed even with questions that they don't have permissions to. When they click on one of the activity links, they get:

    Sorry, you don’t have permission to see that.

**Comment by salsakran** [comment] 2018-02-02 19:21
Can you please share which version of Metabase (and ideally the rest of the information we ask for in the issue template) this is happening on?

**Comment by flamber** [comment] 2020-05-22 15:16
I cannot reproduce on 0.35.3 - think this was fixed in 0.30, with the big Collection change.

**Closed by flamber** 2020-05-22 15:16 UTC
Labels: Administration/Permissions, Priority:P2, Type:Bug
