### ISSUE TITLE
UI breaks and tables not showing completely when many columns added

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#6566] opened 2017-12-12 14:45 UTC
When having multiple columns to show, the UI breaks, also the tables cannot display more than 2 columns in the "View" part
![image](https://user-images.githubusercontent.com/1711649/33890323-aeb01618-df31-11e7-8e5f-6b01314f1f3b.png)

- Your browser and the version: latest chrome
- Your operating system: Mac OSX
- Your databases: Redshift
- Metabase version: 0.27.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

- *Repeatable steps to reproduce the issue*
create a query with more than 2 columns in the "View" part (like many sums), and many group by's, in a low resolution window. The UI will break, and also tables will not show more than 2 aggregated fields

**Comment by attekei** [comment] 2018-01-22 09:53
@paoliniluis What do you specifically mean with "tables will not show more than 2 aggregated fields"? I haven't been able to reproduce that kind of behavior yet.

**Comment by flamber** [comment] 2019-02-22 04:35
Looks like a duplicated of #5325

**Comment by camsaul** [comment] 2019-02-22 19:22
Duplicate of #5325

**Closed by camsaul** 2019-02-22 19:22 UTC
Labels: Bug, CSS, Priority/P2, Query Builder
