### ISSUE TITLE
the error time show all time end with 12:00AM

### ISSUE THREAD

**Issue by endend20000** [metabase/metabase#13328] opened 2020-09-30 06:20 UTC
the all time field end with 12:00AM but the date in database is 00:00AM
the version is v0.36.6
you can reproduct by the project's sample data

<img width="1377" alt="issue1" src="https://user-images.githubusercontent.com/17372268/94649767-4ff98c00-0330-11eb-95ae-8a13e0f55452.png">
<img width="1440" alt="issue2" src="https://user-images.githubusercontent.com/17372268/94649776-54be4000-0330-11eb-9b9b-a6430eb4941f.png">

**Comment by flamber** [comment] 2020-09-30 08:51
Hi @endend20000 
`12:00 AM` is the same as `00:00` on 24-hour.
Duplicate of #5859/#7494

**Closed by flamber** 2020-09-30 08:51 UTC
Labels: .Needs Triage, Type:Bug
