### ISSUE TITLE
Saved questions stop working after dropping column. Automatically remove archived columns when running query

### ISSUE THREAD

**Issue by shafy** [metabase/metabase#12721] opened 2020-06-16 12:42 UTC
**Describe the bug**
Saved questions through GUI stop working after deleting a column (with BigQuery, at least). It's because in the saved question it still tries to select the deleted field name, even if I remove all filters and aggregations. Looking at the Data Model, the sync happened correctly.

**To Reproduce**
1. Sync with your BigQuery database
2. Create and save a question through GUI
3. Delete one column in BigQuery
4. Run saved question and see that it still tries to select the deleted column

**Expected behavior**
I would expect that it stops selecting the deleted column.

**Information about your Metabase Installation:**
Metabase v0.35.4

**Severity**
Medium severity. It's annoying, but there are workarounds (like creating a new question).

**Comment by flamber** [comment] 2020-06-16 16:05
Hi @shafy 
How would Metabase know that it should stop selecting a column that you have dropped elsewhere?
Can you provide more detailed steps? Step 2 seems to involve not just a simple plain question. And isn't there a sync missing between step 3 and 4?
Without clear steps, which I doubt are specific to BigQuery, I think this is a duplicate of #7884.

**Comment by shafy** [comment] 2020-07-20 11:38
Sorry somehow this slipped through the cracks.

Regarding your questions:

- Step 2: It happens with simple plain questions, too
- No I did sync it also manually

> How would Metabase know that it should stop selecting a column that you have dropped elsewhere?

When it syncs with the schema and sees that a column ceases to exists, I would expect it to step seleting it in saved questions?

**Comment by sbelak** [comment] 2020-07-20 11:46
I think this is a general UX question -- how do we handle questions that got invalidated by changes to the underlying schema. If you drop a table, we archive all questions that draw from it, but what to do in case of fields? In some cases the question then becomes pointless (if it's just XvY), but with multi series it can still make sense. I'd archive questions that are made unworkable and correct the rest. Paging @mazameli

**Comment by shafy** [comment] 2020-07-20 11:54
Maybe instead of archiving, can we just flag them so users know what's up and can decide to archive or update?

**Comment by camsaul** [comment] 2024-06-26 03:21
See #39008 for more information, we want to add tools to replace removed/renamed columns and also automatically ignore removed columns in existing questions in the near future. Upgrading this to P2 since that's what #39008 was.

**Comment by camsaul** [comment] 2024-06-26 03:31
Actually, I thought we added those tools in #18022

**Comment by paoliniluis** [comment] 2024-09-05 16:25
I think this now transformed into a nasty bug according to the latest linked issue

**Comment by fer-batista** [comment] 2024-09-05 17:22
Hi! Could you please take a look at this bug? I sent a message via support since I'm paid user.

**Comment by ranquild** [comment] 2024-09-13 14:03
Workarounds:

1. If you selected a field in the "Data" step in the notebook editor and the field no longer exists, you can add any aggregation on the same stage (like "Count of rows") and remove it. This operation removes all the selected fields, including the broken one.
2. If you selected a field in the "Join" step in the notebook editor and the field no longer exists, you can click "Select all", then "Select none", and then "Select all" again the field picker for the selected table in joins. It would remove all broken fields.

**Closed** 2024-10-14 22:21 UTC
Labels: Type:Bug, Priority:P1, Querying/Processor, .Backend, .Escalation, .Team/Querying
