### ISSUE TITLE
clause Or in query

### ISSUE THREAD

**Issue by esaiekuitche** [metabase/metabase#6344] opened 2017-11-07 19:04 UTC
Hi everyone,

I'm using metabase to visualize my mongo database.

How can I make a query with a **Or clause**? 

I try to write without success in SQL mode.

Let suppose I what to find persons in collection person which name is "John" or "Paul"? 

Can you give an example?

Thank very much

**Comment by mazameli** [comment] 2017-11-07 19:37
Duplicate of #5870

**Closed by mazameli** 2017-11-07 19:37 UTC
Labels: Duplicate
