### ISSUE TITLE
Postgres type cast error in text filter

### ISSUE THREAD

**Issue by jtibrewala** [metabase/metabase#5305] opened 2017-06-09 18:52 UTC
Using Ubuntu 17.04 + Chrome 59 + postgresql + metabase standalone jar

When I try to do a simple query on a column in a single table, and add a filter which has a text value (ex. gender = 'f'), metabase fails with a type cast error.  Seems like it is passing the gender = 'f' as gender = "f" which postgres takes as a table name and not a value.  And all this is done in the query builder and not in SQL mode.  Gender filter automatically provides options of f and m because that is how value is stored in the database field. 

ERROR: operator does not exist: gender = character varying Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts. Position: 265

Request this be reviewed at the earliest.  Its preventing me from making simple filters for my dashboard. 
 Thanks for your support.

**Comment by camsaul** [comment] 2017-06-09 18:55
> operator does not exist: gender = character varying

Nope, it sounds like gender is an enum type and in postgres you're not allowed to compare strings to enums with casting. Closing as duplicate of #1623

**Comment by camsaul** [comment] 2017-06-09 18:55
> Request this be reviewed at the earliest.

done 😉

**Closed by camsaul** 2017-06-09 18:55 UTC
