### ISSUE TITLE
Unable to delete columns / fields

### ISSUE THREAD

**Issue by hden** [metabase/metabase#6275] opened 2017-10-26 09:52 UTC
- Your browser and the version: Chrome 61.0
- Your operating system: OS X 10
- Your databases: BigQuery
- Metabase version: master
- Metabase hosting environment: jar / Ubuntu 14
- Metabase internal database: MySQL

1. Connect to a new BigQuery dataset.
    - Minimal requirement: 1 table, 2 rows.
1. Manually add some metadata to the data models.
    - e.g. Descriptions, types, enums.
1. Delete the table via BigQuery console.
1. Create a table with the same name, but with fewer column via BigQuery console.
1. Trigger a schema sync via admin panel.
1. And the supposedly deleted columns / fields still exist.

Tried to clear the cache and re-scan field values, nothing worked.

We can hide the fields from user by setting the field visibility option, but query the raw data will yield an error e.g. `Field 'deleted.field_name' not found in table 'table.name'.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by camsaul** [comment] 2017-11-15 02:21
Hi @hden, is there any stacktrace in the server logs?

**Comment by mvrabel** [comment] 2017-11-15 09:31
related ? #6108

**Comment by hden** [comment] 2017-11-16 09:29
@camsaul 
Minimal steps to reproduce the error:

1. Start a fresh Metabase instance via `docker run --rm -p 3000:3000 metabase/metabase`.
1. Connect to a BigQuery dataset `hden_metabase_dev` which contains a single table `tupac_sightings`.
1. Wait until Metabase finished analyzing the table.
1. Replace `tupac_sightings` with a table contains exactly the same data except column `category_id` is removed.
1. Manually remove cashed field values and trigger a scan.
1. Wait until Metabase finished analyzing the table. (Note that https://gist.github.com/hden/287dd0ec840304f9d4590cf00e530ef4#file-log-txt-L205)
1. Run a custom query.

Screen Shot
<img width="1355" alt="screen shot 2017-11-16 at 18 28 39" src="https://user-images.githubusercontent.com/1910549/32883907-01468f82-cafc-11e7-87cd-c1b1d13637cc.png">

Log
https://gist.github.com/hden/287dd0ec840304f9d4590cf00e530ef4

**Comment by eladeyal-intel** [comment] 2017-11-28 15:05
same as #6155 ?

**Comment by camsaul** [comment] 2017-12-20 00:07
Duplicate of #6146

**Closed by camsaul** 2017-12-20 00:07 UTC
Labels: Bug, Metadata/Sync, Priority/P1
