### ISSUE TITLE
Field Filter - SQL Query as source

### ISSUE THREAD

**Issue by SelvaP** [metabase/metabase#7897] opened 2018-06-16 09:44 UTC

**Comment by SelvaP** [comment] 2018-06-16 09:49
Thanks for the wonderful product.

My doubt is ,can Field Filter field values be controlled?

For example I have a table that has products different types.If suppose I want a Field Filter with a particular product type alone  how should I do it?

Thanks in advance.

**Comment by wvengen** [comment] 2018-06-20 07:56
As far as I understand, Metabase supports SQL for power-users, but it is not the primary focus. Therefore, what about: _use another question as source for field filter values_? This allows for more flexibility, and then non-SQL-aware users can also make use of this feature.

**Comment by SelvaP** [comment] 2018-06-20 13:05
Please can you guide me on doing that.

**Comment by wvengen** [comment] 2018-06-21 07:50
I guess that would be a feature request :)

**Comment by SelvaP** [comment] 2018-06-21 12:29
Lol...

**Comment by salsakran** [comment] 2018-07-06 04:51
this is a dupe of #6820

**Closed by salsakran** 2018-07-06 04:51 UTC
