### ISSUE TITLE
Make Site url less strict

### ISSUE THREAD

**Issue by Zoharos** [metabase/metabase#11895] opened 2020-02-12 20:03 UTC
Hi,
**Is your feature request related to a problem? Please describe.**
I'm working inside a big organization and deployed metabase. The url I have for metabase is: https://emetabase.ng.tsc. I tried to edit the site url to above and get the error 'invalid site url'.
**Describe the solution you'd like**
Make a less strict requirements for the site url.
**Describe alternatives you've considered**
Remove restrictions on site url.
**How important is this feature to you?**
It's the last issue preventing us to make metabase our main db analytic tool. 
Thanks

**Comment by flamber** [comment] 2020-02-12 20:15
Hi @Zoharos 
This was fixed in 0.34.2 (released last week). Fixed by PR #11710, duplicate of issue #10469.

**Closed by flamber** 2020-02-12 20:15 UTC
Labels: .Already Fixed, .Duplicate, Type:New Feature
