### ISSUE TITLE
Queries with temporary tables do not work

### ISSUE THREAD

**Issue by twins-a** [metabase/metabase#17554] opened 2021-08-23 14:11 UTC
Queries with temporary tables do not work.
Error: The Select statement did not create a ResultSet for its own query

It all started after the update to the version 0.40.2

![1 - 2021-08-23_170033](https://user-images.githubusercontent.com/82577774/130460614-11af85dc-8c4f-40ca-a7d1-6d4f39dbfb25.png)

Browser Opera 78.0.4093.147
Operating system: Windows 10.19043.1165
Databases: MSSQL
Metabase version: 0.40.2
Metabase hosting environment: Docker
Metabase internal database: Postgres

Graphs and tables that use temporary tables are no longer displayed in queries.

Temporary tables in SQL now look like this:
![Screen-2](https://user-images.githubusercontent.com/82577774/130461696-b4e28f9e-cda7-4ba6-88f3-6642e6f74a3e.png)

After the update, there are other errors, but I will describe them separately

**Comment by flamber** [comment] 2021-08-23 14:14
Duplicate of #16182

**Closed by flamber** 2021-08-23 14:14 UTC
Labels: Type:Bug, .Needs Triage
