### ISSUE TITLE
Metabase setup from QA to Production - Questions, Dashboards?

### ISSUE THREAD

**Issue by kaulmonish** [metabase/metabase#6437] opened 2017-11-21 06:50 UTC

**Comment by kdoh** [comment] 2017-11-21 21:11
Hi @kaulmonish. I'm going to close this since it's not particularly actionable for us since I'm not really sure what the issue is asking. If you can provide details for an issue you're encountering we'll be happy to re-open this. If you have a more general question on how to use Metabase I'd recommend [using our discussion forum](http://discourse.metabase.com/).

**Closed by kdoh** 2017-11-21 21:11 UTC

**Comment by elmentdave** [comment] 2019-11-12 09:21
hi
