### ISSUE TITLE
Support MongoDB DBRef as Foreign Key

### ISSUE THREAD

**Issue by lchrennew** [metabase/metabase#14481] opened 2021-01-21 23:29 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I use DBRef fields as foreign keys. The current version seems cannot work even though I set the foreign keys manually on data models.

![image](https://user-images.githubusercontent.com/1522365/105424818-09cf8c00-5c83-11eb-8f11-4af254f017d8.png)

**Describe the solution you'd like**
The DBRef field could be recognized as foreign key automatively and it can be works correctly when I query data cross collections.

**Describe alternatives you've considered**

**How important is this feature to you?**
It's very important. If Metabase cannot support this feature, I must switch to other kinds of databases.

**Additional context**

**Comment by flamber** [comment] 2021-01-22 12:21
Duplicate of #9095/#1465

**Closed by flamber** 2021-01-22 12:21 UTC
Labels: .Needs Triage, Type:New Feature
