### ISSUE TITLE
Cropped value output

### ISSUE THREAD

**Issue by vasylkolomiets** [metabase/metabase#19389] opened 2021-12-16 12:07 UTC
Hello.
Please advise me how i can display the entire value of the field.
![Screenshot_29](https://user-images.githubusercontent.com/72972027/146367020-46682191-d1d8-474b-95c6-d341fb03aa9b.png)

I can copy and see the whole message but it is not displayed in ui. And i can expand here
![Untitled](https://user-images.githubusercontent.com/72972027/146368320-f4c1f5b3-67cd-459c-a604-a24c1d86414d.png)
but I have a messages that still does not displayed completely.

Maybe I can rebuild the custom version with certain changes?

**Comment by flamber** [comment] 2021-12-16 12:14
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Duplicate of #6826/#10372

**Closed by flamber** 2021-12-16 12:14 UTC
Labels: Type:Question, .Needs Triage
