### ISSUE TITLE
Can't save permission change on table

### ISSUE THREAD

**Issue by shijialee** [metabase/metabase#5158] opened 2017-05-21 16:04 UTC
Hi, 

I am using 0.24.1 and trying to setup permission in the admin panel. What I am trying to accomplish is to allow all tables to a group except 2 tables. The current permission for the group is no access.

So I select Limit Access on the database for that group, open a new view with list of the tables.  a banner shows `You've made changes to permissions.   cancel, save changes`

All tables' permission are 'no access' with a cross icon in each cell. If I click on one cell, a 'grant unrestricted access' popup with a green check. and the `cancel save changes` banner disappears. the cell still has a cross icon.

If I click the same cell, a popup shows 

```
Changing this database to limited access

Are you sure you want to do this?
```

If I click yes, popup disappears. 

But it looks like nothing changed. Go to the permission page, it still show no access for the database for this group.

Did I miss anything here?

**Comment by shijialee** [comment] 2017-05-23 15:06
using the 0.24.1 java jar in ubuntu 14.04.

I played more with permission. here is my findings:

* I can update permission per table in sample database.  there are corresponding logs.
* I can revoke access/grant unrestricted access on my database level. I can't do that in the table level for my database. there is no metabase log whatsoever when I try to make change to table permission.

anyone experienced this before?

**Comment by attekei** [comment] 2017-05-23 16:51
Thanks for reporting the problem @shijialee! This is probably caused by the changes I made in https://github.com/metabase/metabase/pull/4847. The same problem was mentioned in https://github.com/metabase/metabase/issues/4280#issuecomment-302849000 a few days ago.

I was also able to reproduce this on one of our test databases, so I think I'm able to figure out a fix with the information I have.

**Comment by ujjwal-gupta** [comment] 2017-05-24 03:51
This issue is really blocking some tasks for us:
- Is there any workaround? Maybe direct entries in application DB to set permissions?
- Can there be an HF release with this fix?

**Comment by attekei** [comment] 2017-05-25 04:57
@ujjwal-gupta Sad to hear that!

> Can there be an HF release with this fix?

Yes, our current plan is to release early next week 0.24.2 which will include this fix.

> Is there any workaround? Maybe direct entries in application DB to set permissions?

Theoretically you could manually edit the contents of `permissions` table in application database, but the hierarchical nature of permissions settings makes it tricky to do so. My recommendation is to wait until 0.24.2 is released.

**Comment by ujjwal-gupta** [comment] 2017-05-25 09:59
@attekei Thanks for the revert. 

Early next week sounds good. I'd rather not break things by messing with the db. Thanks!

**Comment by attekei** [comment] 2017-05-31 21:49
Resolved by #5178

**Closed by attekei** 2017-05-31 21:49 UTC
Labels: Bug, Permissions, Priority/P1

**Comment by ujjwal-gupta** [comment] 2017-06-05 09:30
@attekei This issue is still not fixed (at least in MongoDB). I've upgraded from 0.24.1 to 0.24.2

**Comment by attekei** [comment] 2017-06-05 18:08
@ujjwal-gupta I'm unable reproduce that with the official 0.24.2 jar and a MongoDB database with test data 😕 So the problem has remained exactly the same?

**Comment by ujjwal-gupta** [comment] 2017-06-06 03:50
@attekei It was... However, strangely, it worked after logging out and logging in. Sorry for the trouble. Thanks! :)

**Comment by attekei** [comment] 2017-06-06 15:41
@ujjwal-gupta Haha ok, good to hear 🙂 Seems that the frontend assets were cached for a while and you didn't see the latest changes immediately.
