### ISSUE TITLE
PERMISSIONS ISSUE

### ISSUE THREAD

**Issue by ACPK** [metabase/metabase#6796] opened 2018-01-26 21:45 UTC
In the admin's permissions section, a test user has zero permissions to the database and "Saved Questions".

However, they can still see the questions if they go to:

1. meta_url.com/questions
2. "Ask a question"
3. "New Question"
4. "Saved Questions" on the top-left drop-down list *
5. They can SEE all of the saved questions' titles.
6. If they click on one, they'll be redirected to a screen that says "Sorry, you don’t have permission to see that.".

*  Please note, that the user was given NO ACCESS to "Saved Questions" via the admin's permission dashboard.

**Comment by salsakran** [comment] 2018-02-02 19:21
Can you please share which version of Metabase (and ideally the rest of the information we ask for in the issue template) this is happening on?

**Comment by ACPK** [comment] 2018-02-02 21:22
@salsakran  - I installed it the day I wrote this story, so it should be the latest version.

**Comment by camsaul** [comment] 2018-04-09 21:45
This is a duplicate of #5617. Saved Permissions aren't supposed to show up on the Edit Permissions page; we fixed that in 0.25.1.

**Closed by camsaul** 2018-04-09 21:45 UTC
Labels: Bug, Permissions, Priority/P1
