### ISSUE TITLE
Filter dropdown does not work in embedded applications when `params` is not an object

### ISSUE THREAD

**Issue by AndreaScotti** [metabase/metabase#14474] opened 2021-01-21 13:56 UTC
As pointed by @beko1997 this issue still exist in embedded dashboards with token in version 0.37.7 but the issue #13639 is closed, I open this new one.

> @mazameli @camsaul @SG2019 I can indeed confirm this issue still exists with embeding dashboards. I've tested both v0.37.3 and v0.37.5. The filterlist stays empty on the embedded version, while it does get filled in MetaBase self.
> 
> The issue is a 400 response on the following request:
> 
> GET api/embed/dashboard/xxxxxxx/params/b2234673/values
> ````
> Output of chain-filter-merged-params does not match schema: 
> 
> 	 [0;33m  {(not (instance? java.lang.String nil)) invalid-key} [0m 
> ````
> 
> Any ideas on how to fix this one?
> 
> _Originally posted by @beko1997 in https://github.com/metabase/metabase/issues/13639#issuecomment-760060029_

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by beko1997** [comment] 2021-01-21 14:00
Thanks @AndreaScotti for opening a new issue for this.

Please let me know whether I could help with providing more information about this issue.

**Comment by flamber** [comment] 2021-01-21 14:10
@AndreaScotti @beko1997 Can you provide steps-to-reproduce - preferably with Sample Dataset?

**Comment by AndreaScotti** [comment] 2021-01-21 15:46
@beko1997 Thank you for the details.

@flamber in addition to this I see in the console log there is a 400 BadRequest:
GET {metabase_URL}/api/embed/dashboard/{dashboard_token}/params/37215656/values

Instead in a public embedded the same call return 200 Success with the values:
GET {metabase_URL}/api/public/dashboard/{dashboard_public_id}/params/37215656/values

**Comment by flamber** [comment] 2021-01-21 18:50
Okay, so it's not a problem with [Linked Filters](https://www.metabase.com/learn/building-analytics/dashboards/linking-filters.html), but single filter category dropdowns on [Embedding](https://www.metabase.com/docs/latest/administration-guide/13-embedding.html)?
I'm not able to reproduce on 0.37.7 with embedded following the steps - I'm getting a dropdown.
From the error log, it seems like there's too much time between the errors for them to be related. One of the errors is `Error fetching field values`, but haven't seen `Output of chain-filter-merged-params does not match schema` before.

**Comment by beko1997** [comment] 2021-01-22 07:52
I've found a solution for my situation 🎉

> Okay, so it's not a problem with Linked Filters, but single filter category dropdowns on Embedding?

Yes indeed the cause is not specific to linked filters. The dashboard where I first discovered this issue is using linked filters, but the issue is indeed occurring with the single filter category dropdowns when embedding. 

>From the error log, it seems like there's too much time between the errors for them to be related. 

About the log file, indeed you are right. I just copied the logs around the time of the occurrence. 

I've solved the issue for my situation. Thanks for testing this out! Since it is working in your situation I took a look at the differences. Changing the default localisation made no difference. So I figured it must be something withing the JWT token part. Since the token gets signed within my custom (PHP) application it is not exactly the same as the example code.

The issue in the end seems to be withing the claims part of the JWT. The `params` part was filled with an empty array. Which results in a valid token and it seems to work fine for receiving the information for the questions itself. However the filter list expects an object. So casting the array to an object fixed the error.

Before:
```php
->withClaim('params', [])
```

After:
```php
->withClaim('params', (object) [])
```

**Comment by AndreaScotti** [comment] 2021-01-22 08:30
@beko1997 good catch!!!
It's exactly the same here, php with Laravel and with your change it works perfectly.

I tried also with one locked params and one category editable and it's working as well.
Example:
`
->withClaim('params', (object) [
    'category' => 'AFR'
])
`

**Comment by flamber** [comment] 2021-01-22 12:45
Am I misunderstanding something, or is this working now and was just a problem with your embedding code? If yes, then please close this issue.

I would recommend that you look at the embedding reference app:
https://github.com/metabase/embedding-reference-apps/tree/master/laravel/embedded_analytics

**Comment by beko1997** [comment] 2021-01-22 13:52
@flamber Yes, the issue is caused by adding a claim as an array instead of an object. So that is fixed. 

I agree with you that the provided example (which seems to be a bit outdated) is providing an object as well. But it seems odd MetaBase is accepting the same token for loading the embedded page, loading data for each question, but is however failing to load the list with filter values. Their might be some improvements possible by validating the incoming params or a better error output.

For me this issue is closed. @AndreaScotti for you as well?

**Comment by flamber** [comment] 2021-01-22 15:25
@beko1997 Great it's solved for you. You are more than welcome to submit a PR for updating the reference app. We are a fairly small team, so it's difficult to keep everything up to date.

**Comment by souravlahoti** [comment] 2021-01-24 17:13
Hi,

I am receiving the same error on version 0.37.2 , 0.37.6 and 0.37.7 jar files. I am integrating using laravel

```
use Lcobucci\JWT\Builder;
use Lcobucci\JWT\Signer\Hmac\Sha256;
$signer = new Sha256();
        $token = (new Builder())
            ->set('resource', ['dashboard' => $dashboard])
            ->set('params', [])
            ->sign($signer, env('METABASE_SECRET_KEY'))
            ->getToken();
        $metabaseSiteUrl = env('METABASE_URL');
return "$metabaseSiteUrl/embed/dashboard/$token#bordered=false&titled=false";
```

Help will be appreciated

**Comment by AndreaScotti** [comment] 2021-01-26 10:04
@beko1997 yes fixed for me as well.

@flamber I agree with @beko1997 that probably the token should validate also the `params` in order to return an error during embedding. 
As explained seems odd that using the token generated with `->withClaim('params', [])` you are able to embed but it fail during load category values for filters. 
This will be difficult to discover and appear as a bug on MetaBase when it's a wrong token generation issue.

**Comment by flamber** [comment] 2021-01-26 14:26
There were a lot of filter changes in 0.37, so I think it might be using a more strict token structure, which is what is causing the problems. It would behave the same behavior for the dashboards/cards as it has for filters. I'll leave this issue open.

**Comment by albertoperdomo** [comment] 2023-11-10 19:24
We should try to reproduce as this issue is old and there hasn't been a lot of activity recently. It could be that it's no longer valid.

**Comment by WiNloSt** [comment] 2023-11-14 10:09
This doesn't seem to be the case anymore. Tested using [this setup](https://github.com/WiNloSt/metabase-embeddings-101/blob/main/app/page.tsx).

![image](https://github.com/metabase/metabase/assets/1937582/3e0af619-338f-42e1-8638-193c2bd0cd79)

**Comment by albertoperdomo** [comment] 2023-11-14 16:06
@WiNloSt I've looked at your code and it looks like you tested with empty params hash: `params: {}`
I think based on what I am seeing in the issue, we should also test with empty array (`params: []`).

Supplying a non-existing Locked param was deemed as won't fix in #20887, so need to validate that. I will update the title.

**Comment by WiNloSt** [comment] 2023-11-15 07:42
@albertoperdomo We've been passing `params` as an object for years

https://github.com/metabase/metabase/blob/6676158dfc9bc678501e9ecf9b3a99b20f406148/frontend/src/metabase/public/components/widgets/EmbedModalContent.jsx#L123

The line above was last edited in Aug 2021. And it has been returning an object.

This is the payload part generated by Metabase using Node option
```ts
var payload = {
  resource: { dashboard: 24 },
  params: {},
  exp: Math.round(Date.now() / 1000) + (10 * 60) // 10 minute expiration
};
```


I've also tried running 37.7 and the Node option still show a similar if the the same payload
```ts
var payload = {
  resource: { dashboard: 1 },
  params: {},
  exp: Math.round(Date.now() / 1000) + (10 * 60) // 10 minute expiration
};
```


I'm not sure about the BE endpoint but currently it doesn't support param as an array and it threw this error

```
"Invalid input: [\"invalid type\"]"
```

I've used the exact same reproduce steps from [this comment](https://github.com/metabase/metabase/issues/14474#issuecomment-764724524).

Do you think this is something we should still fix? I can see it's not apparent if users composed the wrong payload and sent it to a Metabase instance.

**Comment by WiNloSt** [comment] 2023-11-15 07:52
@albertoperdomo I have another look. After setting `params: []`, the visualization now doesn't render
![image](https://github.com/metabase/metabase/assets/1937582/347a5114-feb5-4084-840e-88d759c66f35)

which has the same behavior as https://github.com/metabase/metabase/issues/20887, so I think we're all good?

**Comment by albertoperdomo** [comment] 2023-11-15 13:22
@WiNloSt I think so. Does this also get registered in the logs like #20887 ?
If yes, I think this one can be closed.

**Comment by WiNloSt** [comment] 2023-11-15 13:40
I got a log like this on /admin/troubleshooting/logs

```
[f70f4b39-2366-45a2-a26a-5e8050a19931] 2023-11-15T20:38:31+07:00 DEBUG metabase.server.middleware.log GET /api/embed/dashboard/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjI0fSwicGFyYW1zIjpbXSwiZXhwIjoxNzAwMDU2MTExLCJpYXQiOjE3MDAwNTU1MTB9.IyytVNojvJKaPosF2TTSc3LP3jeQR3D9bfjas2EmVaM/dashcard/74/card/114 400 22.3 ms (2 DB calls) 
"Assert failed: (map? token-params)"
```

**Comment by albertoperdomo** [comment] 2023-11-15 15:41
Thanks @WiNloSt. Closing!

**Comment by albertoperdomo** [comment] 2023-11-15 15:53
Reopening so that we can add tests.

**Closed** 2023-11-20 10:56 UTC
Labels: Type:Bug, Querying/Parameters & Variables, Embedding/Signed, .Team/Embedding
