### ISSUE TITLE
Drill down broken in v.0.33.2 when joining tables

### ISSUE THREAD

**Issue by BenjaminGK** [metabase/metabase#10871] opened 2019-09-12 07:29 UTC
**Describe the bug**
When summarizing a group of orders and grouping on a column from another joined table, the drill-down to "view these orders" breaks as it only looks for it in the main table
![image](https://user-images.githubusercontent.com/23311430/64762773-eb269480-d568-11e9-9bd0-d2ff5e3fac89.png)

**Logs**
Log from metabase
![image](https://user-images.githubusercontent.com/23311430/64762593-a1d64500-d568-11e9-9984-013e7813091b.png)

No JS errors only warnings regarding mismatch of columns
![image](https://user-images.githubusercontent.com/23311430/64762849-17421580-d569-11e9-86d9-db6d68caa978.png)

**To Reproduce**
1. Go to  query builder
2. join two tables
3. summarize by count and group by column from the joined table
4. visualize results
5. click on count and select "view these orders"
6. See error

**Expected behavior**
I would expect to see those orders using the same query previously used

**Screenshots**
See above

**Information about your Metabase Installation:**
- Your browser and the version: Chrome
- Your operating system: Windows 10
- Your databases: MySQL 5.7
- Metabase version: 0.33.2
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
I would say this is of high severity as it was working in version 0.32.10 and stopped working in the new Query builder, rendering the drill down options useless

**Comment by flamber** [comment] 2019-09-12 07:56
Hi @BenjaminGK Why did you close this issue - could you share the solution, if you found it?

**Comment by flamber** [comment] 2019-09-25 01:06
Doing some more testing, since it's generating different errors - `release-0.33.x` (commit 445da0e12674c909fbd2e53cd7b028dfdc67c0f3)

Reproduce 1:
1. Custom question - select Reviews table
2. Join Products table
3. Summarize Count-of-rows by Product->Category
4. Drill bar (or whatever viz) and select "View these Reviews"
5. Error: `Column "Product.CATEGORY" not found`

Reproduce 2:
1. Custom question - select Orders table
2. Join People table
3. Summarize Count-of-rows by User->Source
4. Drill bar (or whatever viz) and select "View these Orders"
5. Error: `Bad :joined-field clause: join with alias 'User' does not exist. Found: #{"PRODUCTS__via__PRODUCT_ID"}`

**Comment by danbroun** [comment] 2019-10-01 09:49
Especially extremely problematic if you have joined several tables and all the filters no more work. All joins of the previous query should just stay.

**Comment by tlrobinson** [comment] 2019-10-01 18:57
> I would say this is of high severity as it was working in version 0.32.10 and stopped working in the new Query builder, rendering the drill down options useless

To clarify, this is definitely a bug, but we didn't have explicit joins in 0.32 so this isn't a regression. Implicit joins still work correctly.

**Comment by tlrobinson** [comment] 2019-10-15 17:04
Resolved by #11032

**Closed by tlrobinson** 2019-10-15 17:04 UTC
Labels: Priority:P2, Querying/GUI, Type:Bug

**Comment by flamber** [comment] 2019-10-18 22:30
@mazameli This was fixed in 0.33.4 - just closed some time later.
