### ISSUE TITLE
Category Filter does not list values when used accross two questions with different datasets

### ISSUE THREAD

**Issue by jasongi-actu** [metabase/metabase#8698] opened 2018-10-16 05:06 UTC
- Your browser and the version: Chrome
- Your operating system: OSX 10.13.6
- Your databases: Postgres
- Metabase version: 0.30.4
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

Reproduction steps
- Create two different datasets (tables/views) with a column called "name", set that to category in the data model and "A List of all values" under "Filtering on this field" in the field settings for both fields
- Create two questions querying each dataset
- Create a dashboard with both questions
- Create a filter and select "Name" from the drop down on both questions
- Refresh the page
- The filter will not show a list of all values, it will only show a text box that doesn't search.

I have discovered a work around to this, where if you create a second filter that only filters on one of the questions then it magically makes the first filter (filtering on both) appear with a dropdown again. I've had to name these filters IGNORE ME which isn't a great look for our users.

**Comment by poorlymac** [comment] 2018-10-17 05:13
Hi, another workaround I found is to make the questions SQL questions

**Comment by MarkRx** [comment] 2018-10-17 12:36
Looks like #7168

**Comment by salsakran** [comment] 2018-11-06 20:20
at the moment we take the first card and use that as a canonical set of values.

In general, we assume that a filter will end up pointed at the same column.

**Comment by jasongi-actu** [comment] 2018-12-10 23:11
> at the moment we take the first card and use that as a canonical set of values.

@salsakran I think this should be classed as a bug rather than a limitation. At the moment when you have filters across different columns then no values appear in the filter list, it does not use the values from the first card.

**Comment by MarkRx** [comment] 2018-12-11 14:15
The implementation would not be difficult - for each field pull in N values, combine the results of all, sort them as a set, then only show N values. It could become an issue however should filters becoming more advanced such as being able to filter by a segment (#3015). In that case the filter would become awkward as the segment would only apply to one field.

**Comment by vvaezian** [comment] 2019-03-27 17:19
In my case, this problem seems to occur only when I choose default values for dashboard filters that are hooked to multiple questions.

**Comment by flamber** [comment] 2019-04-02 00:25
I actually think this is a duplicate of #5677

**Comment by ATL64** [comment] 2019-04-02 18:18
Yes, it is a duplicate indeed.  Could we prioritize this bug? Seems like a rather basic feature that has not been working for a long time.

**Comment by vitoravancini** [comment] 2019-07-18 13:25
It seems to me that this is a frontend bug.

When I refresh the browser looking at the api logs there is no call to get the field and field values for parameters(filters) that are associated with two tables. 

I'm guessing that this [code](https://github.com/metabase/metabase/blob/050031f76497f06dcbd0914d07239fedaccb0044/frontend/src/metabase/dashboard/selectors.js#L201)  is setting the field_id to null [here](https://github.com/metabase/metabase/blob/050031f76497f06dcbd0914d07239fedaccb0044/frontend/src/metabase/dashboard/selectors.js#L224) 
and when the ParamaterValueWidget loads is wont fetch the values because of this null check [here](https://github.com/metabase/metabase/blob/050031f76497f06dcbd0914d07239fedaccb0044/frontend/src/metabase/parameters/components/ParameterValueWidget.jsx#L126)

**Comment by vitoravancini** [comment] 2019-07-18 16:20
I've tried now and it works when changing ===  to >=,  its the same fix someone posted in an old thread(this [one](https://github.com/metabase/metabase/issues/4909#issuecomment-309006722))

**Comment by Jyggafey** [comment] 2019-11-06 17:34
The workaround described by @vitoravancini fixes this in the current version (0.33.4) and restores the behavior described by @salsakran ("take the first card and use that as a canonical set of values").
Applying the fix to the current version jar:

In `frontend_client/app/dist/app-main.bundle.js`
replace the single occurrence of `field_id:1===i.length` with `field_id:1<=i.length`

To fix it in the source the same change would have to be applied here:
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/dashboard/selectors.js#L224

**Comment by dacort** [comment] 2020-01-09 00:40
This issue manifests in a few different ways depending on the underlying data model. That said, I think this is the set of different use cases that should be considered:

- 1 card w/"list of all issues": expect a list of items that can be selected
- 1 card w/"a search box": expect a free-form text input that auto-completes
- >=2 cards w/"list of all issues": expect a list of items merged from all cards (even if total number of items > whatever the upper limit is that converts a "list of all issues" to a "search box"?)
- >=2 cards w/"a search box": expect a free-form text input that auto-completes across all cards
- a mix of cards w/"list of all issues" and "a search box": a free-form text input that auto-completes across all cards

**Closed** 2020-01-31 17:19 UTC
Labels: Priority:P1, Querying/Parameters & Variables, Reporting/Dashboards, Type:Completeness
