### ISSUE TITLE
MIME type error when using non-root URL for Metabase behind reverse proxy

### ISSUE THREAD

**Issue by bentotroop** [metabase/metabase#8531] opened 2018-09-16 11:44 UTC
I'm using Metabase 0.30, and received CSS and JS MIME type error when mounting Metabase on non-root ("/metabase") URL behind a reverse proxy (Apache 2). The page is blank, although the HTML element title contains "Metabase" correctly.

I had set the Site URL to http://example.com/metabase accordingly, following error messages in Javascript console, and several readings on the Internet. However, I had to firstly mount Metabase on root URL, and then change the Site URL in Settings, because I couldn't load the application otherwise.

The MIME errors are:

```
Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported 
stylesheet MIME type, and strict MIME checking is enabled.

Refused to execute script from 'http://example.com/metabase/app/dist/vendor.bundle.js?
682711f41c583fc76758' because its MIME type ('text/html') is not executable, 
and strict MIME type checking is enabled.

```
Apache configuration as below:

```
<VirtualHost *:80>
  ProxyPreserveHost On
  ProxyRequests Off
  ServerName example.com
  <Location "/metabase">
    ProxyPass http://localhost:3000/
    ProxyPassReverse http://localhost:3000/
  </Location>
</VirtualHost>
```

I had read previous issues many times i.e. https://github.com/metabase/metabase/issues/2090 but still cant figure out how to resolve this.

**Comment by jornh** [comment] 2018-09-16 16:50
At this point it’s hard to say if what you’re reporting here is actually a Metabase issue - or if it’s more of a question of configuration of the proxy.

Apparently Apache httpd `mod_proxy` has a default behavior of setting the MIME type to `text/html` when it can not determine it.

Maybe the workaround suggested in 
https://patternbuffer.wordpress.com/2011/11/30/mime-type-issue-with-apache-mod_jk-and-mod_proxy-serving-plain-text/ with setting `DefaultType None` works for you?

**Comment by rdehouss** [comment] 2018-11-26 20:03
I can confirm the same "issue" with apache and that the suggested solution works! Thanks a lot!

**Comment by salsakran** [comment] 2018-12-28 03:50
closing since this didn't have to do with Metabase and is now working

**Closed by salsakran** 2018-12-28 03:50 UTC
