### ISSUE TITLE
Metabase v0.34 does not display date, datetime fields from AWS Athena. 

### ISSUE THREAD

**Issue by kiansiong** [metabase/metabase#11607] opened 2019-12-30 08:03 UTC
**Describe the bug**
All date and datetime fields are not being displayed. Underlying database is AWS Athena. 
Data is retrieved from database correctly, evident by casting the date field to string using date_format(). However, any field with data type = date / datetime is not displayed / render on screen.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
Select any fields with datatype = date / datetime, with database AWS Athena. 

**Expected behavior**
Date / Datetime fields should be displayed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12004803/71573061-ee945a80-2b1c-11ea-8b74-50ce526d4d58.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_111-internal-alpine-r0-b14",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_111-internal",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.111-b14",
    "os.name": "Linux",
    "os.version": "4.9.0-7-amd64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.0",
      "date": "2019-12-19",
      "branch": "release-0.34.x",

**Severity**
Severity High. This is affecting all datetime fields globally. Which limits any time series visualisations being displayed in Metabase. 

**Additional context**

**Comment by flamber** [comment] 2019-12-30 08:27
Hi @kiansiong 

It seems like parts of the Diagnostic Info is missing, can you copy it again? Admin > Troubleshooting.
Which version of Athena driver?
Which version of Metabase were you using before, since it sounds like it used to work?

Have you considered creating an issue on https://github.com/dacort/metabase-athena-driver since the problem is specific to the driver, not general about Metabase?

Besides the very old Java version, I don't know, but there are very few details. So you don't see any warnings/errors in the log or browser console?

**Comment by kiansiong** [comment] 2019-12-30 09:18
hi @flamber , thanks for the quick response. 

1. Yes this used to work in a previous version. Here's a screenshot of a different environment, reverted back to the previous version, and the data is displaying correctly. 
![image](https://user-images.githubusercontent.com/12004803/71575310-75e6cb80-2b27-11ea-942b-eefd2fc853fa.png)

2. @Rohit-github-cldcvr are you able to advise on the metabase-athena-driver? 

3. Here is the entire diagnostic info. 
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_111-internal-alpine-r0-b14",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_111-internal",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.111-b14",
    "os.name": "Linux",
    "os.version": "4.9.0-7-amd64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.0",
      "date": "2019-12-19",
      "branch": "release-0.34.x",
      "hash": "1335215"
    },
    "settings": {
      "report-timezone": "Asia/Kuala_Lumpur"
    }
  }
}

**Comment by flamber** [comment] 2019-12-30 19:10
Just for reference, looks like similar thing is happening with Oracle driver too:
https://discourse.metabase.com/t/format-date-to-month-has-missing-dimensions/8476
Very similar to #10285 too, which is MySQL specific, but I haven't been able to reproduce.

**Comment by dacort** [comment] 2020-01-04 00:48
I'm tracking this bug over on dacort/metabase-athena-driver#27 - the tl;dr is that the Athena JDBC driver doesn't support some of the new `java.time` types. :(

**Comment by camsaul** [comment] 2020-01-06 19:41
This is an upstream issue with the 3rd-party Athena driver (needs to be updated) but it should be an easy fix, there's shared implementation code to work around drivers with no Java 8 support already in place. I added notes about how to use that in the issue linked above

**Comment by dacort** [comment] 2020-01-14 06:27
Fixed in dacort/metabase-athena-driver#28 - download at https://github.com/dacort/metabase-athena-driver/releases/tag/v0.3.0

**Closed by dacort** 2020-01-14 06:27 UTC
Labels: Misc/Timezones, Querying/, bug with 3rd-party driver
