### ISSUE TITLE
Almost Duplicate Column Names break Metabase Schema Update

### ISSUE THREAD

**Issue by MchlUh** [metabase/metabase#25995] opened 2022-10-18 16:56 UTC
**Describe the bug**
Hello,
when there are two columns with almost a duplicate name, except for the capitalization of letters, the update of schema is broken.

Exemple, if I have a column named : niceColumnName, and another column names nicecolumnname, it will be an issue for the sync of schema.

**Logs**
[6de2e2e1-7673-4012-84a9-ce0b5cef7faf] 2022-10-18T18:52:54+02:00 DEBUG metabase.server.middleware.log GET /api/util/bug_report_details 200 2.6 ms (1 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (23 idle, 0 queued) (118 total active threads) Queries in flight: 0 (0 queued)
[6de2e2e1-7673-4012-84a9-ce0b5cef7faf] 2022-10-18T18:52:54+02:00 WARN metabase.models.field Invalid Field :semantic_type :type/Number: falling back to null
[6de2e2e1-7673-4012-84a9-ce0b5cef7faf] 2022-10-18T18:52:55+02:00 WARN metabase.models.field Invalid Field :semantic_type :type/Number: falling back to null
[6de2e2e1-7673-4012-84a9-ce0b5cef7faf] 2022-10-18T18:52:55+02:00 INFO metabase.sync.sync-metadata.fields.sync-metadata Database position of Table 52 'public.deliveries' Field 'driver_lastname' has changed from '60' to '59'.
[6de2e2e1-7673-4012-84a9-ce0b5cef7faf] 2022-10-18T18:52:55+02:00 INFO metabase.sync.sync-metadata.fields.sync-metadata Name of Table 52 'public.deliveries' Field 'driver_lastname' has changed from 'driver_lastname' to 'driver_lastName'.
[6de2e2e1-7673-4012-84a9-ce0b5cef7faf] 2022-10-18T18:52:55+02:00 WARN metabase.sync.util Error syncing Fields for Table 'Table 52 'public.deliveries''
java.sql.BatchUpdateException: Batch entry 0 UPDATE "metabase_field" SET "database_position" = 59, "name" = 'driver_lastName', "updated_at" = now() WHERE "id" = 5435 was aborted: ERROR: duplicate key value violates unique constraint "idx_uniq_field_table_id_parent_id_name_2col"
  Detail: Key (table_id, name)=(52, driver_lastName) already exists.  Call getNextException to see other errors in the batch.

**Expected behavior**
As it was the case in previous metabase version, we could have both column added to the table

**Severity**
It is annoying since we cannot use the no code interface with newly added tables :) 

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "5.10.0-0.bpo.15-amd64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.17"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-09-29",
      "tag": "v0.44.4",
      "branch": "release-x.44.x",
      "hash": "382d728"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
}
```

Cheers, and thanks for all the work ;)

**Comment by flamber** [comment] 2022-10-19 08:19
Duplicate of #17387

**Closed by flamber** 2022-10-19 08:19 UTC
