### ISSUE TITLE
Question title on dashboard 

### ISSUE THREAD

**Issue by maximepvrt** [metabase/metabase#14256] opened 2021-01-05 10:51 UTC
Why question title is not a html link `<a></a>` on dashboard ?
Currently it's not possible to show the left click menu to open the question in a new tab the question for example.

![Capture d’écran 2021-01-05 à 11 47 21](https://user-images.githubusercontent.com/1840026/103637804-4e9db800-4f4c-11eb-97e5-d7c54baef24f.png)

**Comment by flamber** [comment] 2021-01-05 11:09
Duplicate of #5168

**Closed by flamber** 2021-01-05 11:09 UTC
Labels: .Needs Triage, Type:New Feature
