### ISSUE TITLE
No drill down functionality on certain visualisations

### ISSUE THREAD

**Issue by magnusfoldager** [metabase/metabase#14301] opened 2021-01-07 09:32 UTC
**Describe the bug**
Setting up on click behaviour for certain visualisations (I noticed Gauge, but there might be others) will not allow you to perform any click action. Clicking the question name will direct you to that question, and there is no other clickability in the question.

**Logs**
N/A

**To Reproduce**
1. Set up Gauge in Dashboard
2. Set Click Behaviour to direct to another place (question/dashboard)
3. Try clicking the different parts of the question from the dashboard

**Expected behavior**
A redirect to the question/dashboard I specified during the click behaviour setup when clicking the number in the middle of the gauge or the gauge itself.

**Screenshots**
N/A

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

Built on 2020-12-03

- Your browser and the version: 87.0.4280.88 (Official Build) (x86_64)
- Your operating system: macOS 11.2 Beta (20D5029f)
- Your databases: Postgres, BigQuery
- Metabase version: v0.37.3
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
Annoying and blocking functionality.

**Additional context**
N/A

**Comment by flamber** [comment] 2021-01-07 10:19
Duplicate of #9549

**Closed by flamber** 2021-01-07 10:19 UTC
Labels: .Needs Triage, Type:Bug
