### ISSUE TITLE
Value is shown as key in some circumstances, while it should be shown as name

### ISSUE THREAD

**Issue by danaivehr** [metabase/metabase#12050] opened 2020-03-04 22:07 UTC
**Describe the bug**
Let me describe it on example.

Tables:
* Users
* Issues, has two columns
  - Author - foreign key of Users
  - Assignee - foreign key of Users also

Metabase scheme settings for Table Issues:
* Author - to show foreign key name of Users
* Assignee - to show foreign key name of Users also

If i make a query with both columns in list, i will get one of them as name (that is correct), but another will be just a key (that is the bug)

If i hide any of these columns, i will get another of them as name (that is correct)

Just to finalize - two columns of the keys fot the same table could not be shown as names simultaneous

**Screenshots**

Both columns:

![image](https://user-images.githubusercontent.com/1226019/75927240-0e2d6380-5e7d-11ea-8bfe-09aa24453e78.png)

One of them:

![image](https://user-images.githubusercontent.com/1226019/75927533-96ac0400-5e7d-11ea-88c5-f7e8f49a0a89.png)

Metabase version: 0.34.2

**Comment by flamber** [comment] 2020-03-04 22:32
Hi @danaivehr 
That's a duplicate of #9236 - upvote by clicking :+1: on the first post of the issue

**Closed by flamber** 2020-03-04 22:32 UTC
Labels: .Needs Triage, Type:Bug
