### ISSUE TITLE
Display original schema and human version

### ISSUE THREAD

**Issue by Philippe-M** [metabase/metabase#6745] opened 2018-01-23 08:24 UTC
on the page "datamodel", when editing a table, is it possible to display the original name of a field and the name "translated" next to each other?

**Comment by flamber** [comment] 2019-02-24 03:34
Hi @Philippe-M 
This is a duplicate of #1611 - but was really difficult to find, since says "metadata" instead of "data model".
But definitely something I would really like - please go and upvote by clicking :+1:

**Comment by mazameli** [comment] 2019-10-11 22:05
Closing as duplicate

**Closed by mazameli** 2019-10-11 22:05 UTC
Labels: .Duplicate, .Proposal, Admin Panel & Setup, Type:UX
