### ISSUE TITLE
Field Filter: Selecting Date Filter widget type as "None" makes it disappear forever

### ISSUE THREAD

**Issue by pawit-metabase** [metabase/metabase#17569] opened 2021-08-24 07:07 UTC
**Describe the bug**
For field filter, selecting Date Filter widget type as "None" makes it disappear forever

**Logs**
N/A

**To Reproduce**
1. Go to new SQL question
2. Type `SELECT * FROM orders WHERE {{created_at}}`
3. Select variable type "Field Filter"
4. Select field to map to "Created At"
5. Select filter widget type "None"
6. Select filter widget type "Month and Year"

**Expected behavior**
After selecting "None", the filter should disappear but after selecting "Month and Year" it should appear again.

**Screenshots**
<img width="1422" alt="Screen Shot 2564-08-24 at 14 06 14" src="https://user-images.githubusercontent.com/88995137/130572340-5d67ccaf-00e1-4909-aeae-3766943f8056.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 92.0.4515.159
- Your operating system: macOS 11.5.2
- Your databases: Sample DB
- Metabase version: 0.40.2
- Metabase hosting environment: Jar file on macOS
- Metabase internal database: H2

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

Annoying

**Additional context**
N/A

**Comment by flamber** [comment] 2021-08-24 08:03
Duplicate of #13825

**Closed by flamber** 2021-08-24 08:03 UTC
Labels: Type:Bug, .Needs Triage
