### ISSUE TITLE
category filter is showed different between user account 

### ISSUE THREAD

**Issue by Wind-hunter** [metabase/metabase#7264] opened 2018-04-04 06:28 UTC
Hi, everyone.

I find out an issue with category filters. 
with admin account, i setup a category filter show a list but in the others account type (without query permission), they can't see the list and must input text/number to a box to filter data.

I'm a dummy user and I don't know where the issue come from. Is that a bug? Can you fix it, please.
Thank you very much. :D 

db: amazon redshift (postgreSQL 8.0.2)

**Comment by mazameli** [comment] 2018-04-04 16:13
Could you tell us which version of Metabase you're using, please?

**Comment by Wind-hunter** [comment] 2018-04-05 04:26
We use metabase version 0.28.1

**Comment by salsakran** [comment] 2019-08-05 05:41
closing this in favor of #9270 since that has a reproduction scenario. Bumping that to a P1 to match this.

**Closed by salsakran** 2019-08-05 05:41 UTC
Labels: Priority:P1, Query Builder, Type:Bug
