### ISSUE TITLE
Bug in style of values on data points

### ISSUE THREAD

**Issue by ABUISSON** [metabase/metabase#16245] opened 2021-05-26 13:13 UTC
**Describe the bug**
In line and bar charts with multiple series, styling one series to **_Percent_** formats **all** series to **_percent_**.

**To Reproduce**
1. Go in the query editor
2. Create a toy example like
```
SELECT * FROM (
VALUES 
('a',2,0.02),
('b',1,0.03),
('c',-0.5,-0.04),
('d',-0.5,0.033)
)
```

3. Choose line chart
4. Click on Settings>Data>Format>Style>Percent for one the column

**Expected behavior**
Only the chosen series is formatted as _percent_. The other series keep their style.

**Observed behavior**
All series are converted to percent

**Screenshots**
![image](https://user-images.githubusercontent.com/28676186/118824248-fb545280-b8b9-11eb-9ecf-25adf4cd3af5.png)

**Severity**
It prevents us from integrating these charts in important reports.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_282-b08",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "1.8.0_282",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.282-b08",
    "os.name": "Linux",
    "os.version": "4.14.231-173.360.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.38.0",
      "date": "2021-02-16",
      "branch": "release-x.38.x",
      "hash": "471aa51"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Comment by flamber** [comment] 2021-05-26 13:26
Duplicate of #13095

**Closed by flamber** 2021-05-26 13:26 UTC
Labels: .Needs Triage, Type:Bug
