### ISSUE TITLE
Some panel questions are not processed randomly and intermittently

### ISSUE THREAD

**Issue by tatusis** [metabase/metabase#10966] opened 2019-09-23 22:54 UTC
**Describe the bug**
Some panel questions are not processed randomly and intermittently.

**Logs**

**Example 1**

:ex-data {:rollback #error {
 :cause "Ligação Fechada"
 :via

 [{:type java.sql.SQLRecoverableException
   :message "Ligação Fechada"
   :at [oracle.jdbc.driver.PhysicalConnection getAutoCommit "PhysicalConnection.java" 2089]}]
 :trace

 [[oracle.jdbc.driver.PhysicalConnection getAutoCommit "PhysicalConnection.java" 2089]
  [oracle.jdbc.driver.PhysicalConnection rollback "PhysicalConnection.java" 2218]
  [com.mchange.v2.c3p0.impl.NewProxyConnection rollback "NewProxyConnection.java" 1033]

**Example 2**

[java.lang.Thread run "Thread.java" 748]]}, :handling #error {
 :cause "Ligação Fechada"
 :via

 [{:type java.sql.SQLRecoverableException
   :message "Ligação Fechada"
   :at [oracle.jdbc.driver.PhysicalConnection getAutoCommit "PhysicalConnection.java" 2089]}]
 :trace

 [[oracle.jdbc.driver.PhysicalConnection getAutoCommit "PhysicalConnection.java" 2089]
  [oracle.jdbc.driver.PhysicalConnection rollback "PhysicalConnection.java" 2218]
  [com.mchange.v2.c3p0.impl.NewProxyConnection rollback "NewProxyConnection.java" 1033]

**To Reproduce**
All dashboards have the same error. A refresh usually resolves the issue.

**Expected behavior**
All questions should show results.

**Screenshots**

**Information about your Metabase Installation:**
- Your browser and the version: Firefox 69.0.1 and Chrome 77
- Your operating system: Windows Server 2012 R2
- Your databases: Oracle and Postgres
- Metabase version: 0.33.2
- Metabase hosting environment: Jar-file
- Metabase internal database: Postgres

**Severity**
Some users need to refresh a dashboard for a complete result.

**Additional context**
The same error appears in single questions.

**Comment by flamber** [comment] 2019-09-23 23:09
Hi @tatusis 
Do you also see the problem on dashboards that only has questions from Postgres? The errors you post are only related to Oracle.
The problem you describe is very similar to #9989, so even though it's referencing "SQL Server", some of the comments are saying it's happening on other database types too.

**Comment by tatusis** [comment] 2019-09-23 23:14
We currently have no dashboards accessing postgres. In isolated questions is rarer to happen. I read issue # 9989. Very similar. It even happens on panels without filters.

**Comment by tatusis** [comment] 2019-09-26 00:10
Hello, the problem also appears in Postgres. We were able to partially solve the problem by setting the database idle_time to unlimited. This way, sessions are not terminated by the database and Metabase pool can always get a valid session.

**Comment by flamber** [comment] 2019-09-26 00:17
@tatusis Great! Then I'm very sure it's issue #9989. And perfect you found a work-around :+1:

**Comment by salsakran** [comment] 2019-10-05 23:01
Hello @tatusis , closing this issue since we believe the root cause is fixed in #11018. We'll be releasing a new build shortly (0.33.4), and it would be very useful if you could confirm that this is fixed in your Oracle setup as well.

**Closed by salsakran** 2019-10-05 23:01 UTC
Labels: Type:Bug
