### ISSUE TITLE
Changing Metabase DB from H2 to oracle/mongodb

### ISSUE THREAD

**Issue by upalde129** [metabase/metabase#13318] opened 2020-09-25 23:05 UTC
Hi,

I need assistance in the migration of DB from H2 to oracle/MongoDB for Metabase.
as per I have read here https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html
It says for migration a new DB is required.
Please let me know if I can use an existing oracle DB which is used for an application that can be used for Metabase. I want to migrate the sample dataset from H2 to oracle. Also please let me know the process.

**Comment by flamber** [comment] 2020-09-26 08:33
Metabase will never support MongoDB as application database.
Currently only H2, Postgres and MySQL is supported.
Duplicate of #6321

**Closed by flamber** 2020-09-26 08:33 UTC
Labels: .Needs Triage, Type:Question
