### ISSUE TITLE
Strings with {0} aren't translating correctly - polish translation

### ISSUE THREAD

**Issue by rciszynski** [metabase/metabase#16261] opened 2021-05-27 13:08 UTC
**Describe the bug**
Bug related to https://github.com/metabase/metabase/issues/15642
Strings with {0} aren't translating correctly - in polish translation. Switching to English - no errors

**Logs**
-

**To Reproduce**
Examples: selecting several items in the field filter, number of lines in the query editor, number of assigned groups on the user list

**Expected behavior**

**Screenshots**
![mb2](https://user-images.githubusercontent.com/84914645/119829905-06cbfd00-befc-11eb-830a-c6dcc280fe6a.png)
![mb1](https://user-images.githubusercontent.com/84914645/119829910-07649380-befc-11eb-8739-9a3aefecbec9.png)

**Information about your Metabase Installation:**

- Your browser and the version: any
- Your operating system: any
- Your databases: MySQL, MS SQL
- Metabase version: 0.39.2, 0.39.1
- Metabase hosting environment: jar-file on Ubuntu Server 20.04
- Metabase internal database: Postgres

**Severity**
Important to some end-users but not blocking work

**Additional context**
-

**Comment by flamber** [comment] 2021-05-27 13:09
Duplicate of #15694

**Closed by flamber** 2021-05-27 13:09 UTC
Labels: .Needs Triage, Type:Bug
