### ISSUE TITLE
Adding Qs to Personal Collection

### ISSUE THREAD

**Issue by Opalevanescence** [metabase/metabase#12718] opened 2020-06-16 04:20 UTC
**Describe the bug**
When cypress testing (and only when cypress testing):

I cannot save a question to "My personal collection" as admin or user. When I select it as the collection I want the question to be stored in, the dropdown menu appears blank and an error comes on the screen after I hit save.

If, at the same point in the test, I redirect to the http://localhost:4000/api/user/current it confirms that the personal collection has been created even though I can't save to that collection.

**Logs**
cypress_runner.js:85969 GET http://localhost:4000/api/collection/1 404 (Not Found)
Request entities,collections,1,fetch failed: {status: 404, data: "Not found.", isCancelled: false}
redux.js:20 Uncaught (in promise) {status: 404, data: "Not found.", isCancelled: false}
redux.js:231 Request entities,questions,create failed: {status: 500, data: {…}, isCancelled: false}
Form.jsx:296 Form submission error {status: 500, data: {…}, isCancelled: false}
{status: 500, data: {…}, isCancelled: false}

**To Reproduce**
1. Create a simple question
2. Click 'Save'
3. Type a name and description
4. Got to the dropdown menu and select your personal collection as where you want to save your question.
5. Click 'Save'

**Expected behavior**
Admins and users should be able to save their questions in their personal collection.

**Screenshots**
The shot with the blank dropdown is after selecting "My Personal collection" and the shot with the error message is from after I clicked the Save button.

<img width="861" alt="Screen Shot 2020-06-15 at 8 58 04 PM" src="https://user-images.githubusercontent.com/58329466/84731277-3b45e380-af4d-11ea-951c-82c7ee633929.png">

<img width="865" alt="Screen Shot 2020-06-15 at 8 58 17 PM" src="https://user-images.githubusercontent.com/58329466/84731283-41d45b00-af4d-11ea-833d-3632470a1c7a.png">

**Severity**
Important for testing because that's an important feature and we should be able to check if it works for users from our tests.

**Additional context**
The specific files I've been working on that brought up this issue were in the metabase-smoketests folder on the feature/smoketests branch.

**Comment by Opalevanescence** [comment] 2020-06-18 20:43
Noticed I don't run into this problem with the Enterprise repository, only the Metabase repository.

**Comment by flamber** [comment] 2020-06-18 20:49
Probably caused by a migration changeset to `master` - which isn't merged with EE yet.
I'm also seeing constraint errors during setup, but it still completes the setup. Haven't nailed down the cause yet.

**Comment by flamber** [comment] 2020-07-16 22:13
@Opalevanescence Are you still seeing this on `master`? Also in Electron? Can you post the full stacktrace from the log?

**Comment by Opalevanescence** [comment] 2020-07-16 22:44
@flamber Nope, no longer seeing this. I'll unskip the smoketests that check for this later today or tommorrow.

**Closed** 2020-09-16 20:13 UTC
Labels: .CI & Tests, Type:Bug
