### ISSUE TITLE
Not showing information when you click on the points on the Scatter chart - mobile

### ISSUE THREAD

**Issue by sganderla** [metabase/metabase#12552] opened 2020-05-18 22:11 UTC
Scatter point information cannot be accessed when a point is selected (Click)
The point information is not showing. A format box is appearing.

Follow print

<img width="498" alt="Captura de Tela 2020-05-18 às 18 58 42" src="https://user-images.githubusercontent.com/10933066/82264367-2a4c8700-993b-11ea-8022-4791abb5263f.png">

**Comment by flamber** [comment] 2020-05-19 08:11
Hi @sganderla 
It would be helpful if you provided more information, like versions and browser.
And which type of information you expect, when clicking the point.

**Comment by sganderla** [comment] 2020-05-19 12:53
Hi @flamber

When the application is accessed by the browser (PC), the information (print) is displayed when the mouse is hovered over the point.

As the mobile device does not have a mouse, it is necessary to click on the point to display the information (print), however when you click on the point the format box appears.

The error only happens on mobile

The tests were performed on Tablets, Smartphones and Google Chrome 81.0.4044.138 in the mobile function.

![Captura-de-Tela-2020-05-19-às-08 57 03](https://user-images.githubusercontent.com/10933066/82325274-573b8100-99b1-11ea-9065-eb8f7b346564.jpg)

**Comment by flamber** [comment] 2020-05-19 13:25
Okay, then it's a duplicate of #11213 - upvote by clicking :+1: on the first post

**Closed by flamber** 2020-05-19 13:25 UTC
Labels: .Need More Info
