### ISSUE TITLE
Editing Field Types from Data Reference Doesn't Work

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#39860] opened 2024-03-08 17:11 UTC
### Describe the bug

If you attempt to edit "Field Types" for a table from the data dictionary, some of the functionality doesn't work.

- From the fields list for a table you cannot select a target for foreign key relationships
- If you navigate to a field and edit it directly, selecting a new field type from the menu does not work
- If you navigate to a field and edit it directly, you cannot set a target for foreign key relationships

### To Reproduce

1. Go to Browse Data -> Select Database -> Learn About this Table -> Fields in this table
2. Click "Edit"
3. Attempt to Select a Target for a foreign key field
4. Note that the menu is empty
5. Cancel the edit and select any field on the table
6. Click "Edit"
7. Attempt to change the field type
8. Note the menu selection does not work

Here's a short Loom recording:
https://www.loom.com/share/bf13d62a1bea4b739cea8234d8e58e11?sid=fea64350-7789-47a9-bea4-5e15abd8029d

### Expected behavior

Editing the field types should work

### Logs

[13ea2626-36d8-4e2d-a327-10ba8a25ff7a] 2024-03-08T11:08:28-06:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 15.8 ms (7 DB calls) App DB connections: 2/15 Jetty threads: 7/50 (3 idle, 0 queued) (125 total active threads) Queries in flight: 0 (0 queued)
[13ea2626-36d8-4e2d-a327-10ba8a25ff7a] 2024-03-08T11:08:28-06:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 29.7 ms (11 DB calls) App DB connections: 1/15 Jetty threads: 6/50 (3 idle, 0 queued) (125 total active threads) Queries in flight: 0 (0 queued)
[13ea2626-36d8-4e2d-a327-10ba8a25ff7a] 2024-03-08T11:08:28-06:00 DEBUG metabase.server.middleware.log GET /api/collection/root 200 6.7 ms (2 DB calls) App DB connections: 4/15 Jetty threads: 10/50 (1 idle, 0 queued) (125 total active threads) Queries in flight: 0 (0 queued)
[13ea2626-36d8-4e2d-a327-10ba8a25ff7a] 2024-03-08T11:08:28-06:00 DEBUG metabase.server.middleware.log GET /api/database 200 7.3 ms (3 DB calls) App DB connections: 5/15 Jetty threads: 10/50 (1 idle, 0 queued) (125 total active threads) Queries in flight: 0 (0 queued)
[13ea2626-36d8-4e2d-a327-10ba8a25ff7a] 2024-03-08T11:08:28-06:00 DEBUG metabase.server.middleware.log GET /api/util/bug_report_details 200 3.0 ms (1 DB calls) App DB connections: 4/15 Jetty threads: 10/50 (1 idle, 0 queued) (125 total active threads) Queries in flight: 0 (0 queued)
[13ea2626-36d8-4e2d-a327-10ba8a25ff7a] 2024-03-08T11:08:28-06:00 DEBUG metabase.server.middleware.log GET /api/bookmark 200 10.0 ms (1 DB calls) App DB connections: 2/15 Jetty threads: 8/50 (1 idle, 0 queued) (125 total active threads) Queries in flight: 0 (0 queued)
[13ea2626-36d8-4e2d-a327-10ba8a25ff7a] 2024-03-08T11:08:28-06:00 DEBUG metabase.server.middleware.log GET /api/collection/tree 200 13.0 ms (6 DB calls) App DB connections: 1/15 Jetty threads: 7/50 (1 idle, 0 queued) (125 total active threads) Queries in flight: 0 (0 queued)
[13ea2626-36d8-4e2d-a327-10ba8a25ff7a] 2024-03-08T11:08:28-06:00 DEBUG metabase.server.middleware.log GET /api/search 200 35.0 ms (5 DB calls) App DB connections: 1/15 Jetty threads: 6/50 (2 idle, 0 queued) (125 total active threads) Queries in flight: 0 (0 queued)
[13ea2626-36d8-4e2d-a327-10ba8a25ff7a] 2024-03-08T11:08:36-06:00 DEBUG metabase.server.middleware.log GET /api/database/2/schemas 200 10.3 ms (4 DB calls) App DB connections: 1/15 Jetty threads: 6/50 (3 idle, 0 queued) (125 total active threads) Queries in flight: 0 (0 queued)
[13ea2626-36d8-4e2d-a327-10ba8a25ff7a] 2024-03-08T11:08:36-06:00 DEBUG metabase.server.middleware.log GET /api/database/2/schema/public 200 15.3 ms (4 DB calls) App DB connections: 1/15 Jetty threads: 6/50 (3 idle, 0 queued) (125 total active threads) Queries in flight: 0 (0 queued)
[13ea2626-36d8-4e2d-a327-10ba8a25ff7a] 2024-03-08T11:08:36-06:00 DEBUG metabase.server.middleware.log GET /api/database/2 200 12.8 ms (7 DB calls) App DB connections: 1/15 Jetty threads: 6/50 (3 idle, 0 queued) (125 total active threads) Queries in flight: 0 (0 queued)
[13ea2626-36d8-4e2d-a327-10ba8a25ff7a] 2024-03-08T11:08:59-06:00 DEBUG metabase.server.middleware.log GET /api/database/2/metadata 200 329.1 ms (97 DB calls) App DB connections: 1/15 Jetty threads: 6/50 (3 idle, 0 queued) (125 total active threads) Queries in flight: 0 (0 queued)
[13ea2626-36d8-4e2d-a327-10ba8a25ff7a] 2024-03-08T11:09:31-06:00 DEBUG metabase.server.middleware.log PUT /api/field/858 200 27.0 ms (10 DB calls) App DB connections: 1/15 Jetty threads: 6/50 (5 idle, 0 queued) (122 total active threads) Queries in flight: 0 (0 queued)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.15.133.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.22 (Debian 11.22-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-02-22",
      "tag": "v1.48.7",
      "hash": "c192db1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Annoying. Field types can still be updated from table metadata.

**Comment by ixipixi** [comment] 2024-03-08 23:22
Sorry guys - I didn't see the original before I submitted this one: https://github.com/metabase/metabase/issues/37907

What's best practice here? Should just close it and refer to the other issue?

**Comment by ignacio-mb** [comment] 2024-03-12 18:24
@ixipixi yup, closing as not planned and dupe of that one

**Closed by ignacio-mb** 2024-03-12 18:24 UTC
Labels: Type:Bug, Priority:P3, Organization/Data Reference
