### ISSUE TITLE
Stacked Bar Chart Drill In Incorrect

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#9361] opened 2019-01-31 22:06 UTC
When a bar chart is stacked (either normal or percentage wise) the drill in sometimes does not produce the right query filter when creating a new question.

In the below bar chart highlighting the red "FAILURE" on January 31 and attempting to view the records generates a question with the filter being "SUCCESS" instead of "FAILURE":
![image](https://user-images.githubusercontent.com/17504314/52088739-b8e89980-257a-11e9-9a49-a0ed2b080035.png)

## Steps to reproduce:
1. Create the following query
![image](https://user-images.githubusercontent.com/17504314/52088367-a91c8580-2579-11e9-82e4-675ebd6110e5.png)

2. Change the visualization to be a stacked bar chart with date on the bottom
![image](https://user-images.githubusercontent.com/17504314/52088411-be91af80-2579-11e9-975b-e966164b9b74.png)

3. Drill in to the top right bar (Aerodynamic Leather Toucan) by clicking "view this order"
![image](https://user-images.githubusercontent.com/17504314/52088624-65764b80-257a-11e9-82d0-fe93c99a67cd.png)

The generated question uses a filter of Product > Title = "Aerodynamic Bronze Hat". It should be "Aerodynamic Leather Toucan".
![image](https://user-images.githubusercontent.com/17504314/52088518-17f9de80-257a-11e9-9b53-46827ea79448.png)

Your browser and the version: 71.0.3578.98 (Official Build) (64-bit)
Your operating system: Windows 7
Your databases: Oracle 12.2
Metabase version: 0.31.2
Metabase hosting environment: RHEL 7
Metabase internal database: MySQL

**Comment by evangreally** [comment] 2019-02-06 10:32
I also get this with a postgres and MySQL DB's.

**Comment by evangreally** [comment] 2019-02-07 17:16
We are also getting this issue it seems to always take the first value in the series.

**Comment by evangreally** [comment] 2019-04-03 12:25
@camsaul will this issue be fixed in the next release?

**Comment by saurabh7248** [comment] 2019-04-25 17:30
I can try to fix this if someone is able to point me in a right direction

**Comment by evangreally** [comment] 2019-05-09 12:32
Hi @saurabh7248 

I was investigating this issue recently but not had time to look at the cause. 
I traced the issue back as far as :
**UnderlyingRecordsDrill.jsx**
located here:
/metabase/frontend/src/metabase/modes/components/drill/UnderlyingRecordsDrill.jsx

**Comment by paulrosenzweig** [comment] 2019-09-03 20:16
Resolved by #10555

**Closed by paulrosenzweig** 2019-09-03 20:16 UTC
Labels: Actions, Priority:P1, Query Builder, Type:Bug
