### ISSUE TITLE
Pulses not working

### ISSUE THREAD

**Issue by ShipraShalini** [metabase/metabase#7682] opened 2018-05-22 17:26 UTC
I have set up a few pulses which are supposed to send mail and slack message every day though no mail or message has been received by the intended recipients.
When I send a test mail/message, it works fine.

When I grep `pulse` on metabase.log, I get:
```
ubuntu@host:/var/log$ grep -rn pulse metabase.log
2652:05-22 17:06:33 DEBUG metabase.middleware :: GET /api/pulse 200 (640 µs) (1 DB calls). Jetty threads: 8/50 (5 busy, 3 idle, 0 queued)
2666:05-22 17:06:34 DEBUG metabase.middleware :: GET /api/pulse/form_input 200 (723 ms) (0 DB calls). Jetty threads: 8/50 (5 busy, 3 idle, 0 queued)
2671:05-22 17:06:45 DEBUG metabase.middleware :: GET /api/pulse/5 200 (19 ms) (14 DB calls). Jetty threads: 8/50 (6 busy, 2 idle, 0 queued)
2673:05-22 17:06:45 DEBUG metabase.middleware :: GET /api/pulse/preview_card_info/3 200 (28 ms) (16 DB calls). Jetty threads: 8/50 (6 busy, 2 idle, 0 queued)
2674:05-22 17:06:46 DEBUG metabase.middleware :: GET /api/pulse/form_input 200 (665 ms) (0 DB calls). Jetty threads: 8/50 (5 busy, 3 idle, 0 queued)
2676:05-22 17:06:52 DEBUG metabase.middleware :: POST /api/pulse/test 200 (3 s) (17 DB calls). Jetty threads: 8/50 (5 busy, 3 idle, 0 queued)
2678:05-22 17:07:19 DEBUG metabase.middleware :: POST /api/pulse/test 200 (3 s) (17 DB calls). Jetty threads: 8/50 (5 busy, 3 idle, 0 queued)
2679:05-22 17:07:48 DEBUG metabase.middleware :: GET /api/pulse 200 (543 µs) (1 DB calls). Jetty threads: 8/50 (6 busy, 2 idle, 0 queued)
2693:05-22 17:07:50 DEBUG metabase.middleware :: GET /api/pulse/form_input 200 (1 s) (0 DB calls). Jetty threads: 8/50 (5 busy, 3 idle, 0 queued)
2713:05-22 17:14:49 DEBUG metabase.middleware :: GET /api/pulse 200 (633 µs) (1 DB calls). Jetty threads: 8/50 (6 busy, 2 idle, 0 queued)
2727:05-22 17:14:49 DEBUG metabase.middleware :: GET /api/pulse/form_input 200 (666 ms) (0 DB calls). Jetty threads: 8/50 (5 busy, 3 idle, 0 queued)
2729:05-22 17:14:51 DEBUG metabase.middleware :: GET /api/pulse/preview_card_info/3 200 (23 ms) (16 DB calls). Jetty threads: 8/50 (5 busy, 3 idle, 0 queued)
2734:05-22 17:14:51 DEBUG metabase.middleware :: GET /api/pulse/5 200 (10 ms) (14 DB calls). Jetty threads: 8/50 (5 busy, 3 idle, 0 queued)
2735:05-22 17:14:51 DEBUG metabase.middleware :: GET /api/pulse/form_input 200 (709 ms) (0 DB calls). Jetty threads: 8/50 (5 busy, 3 idle, 0 queued)
2737:05-22 17:14:58 DEBUG metabase.middleware :: POST /api/pulse/test 200 (3 s) (17 DB calls). Jetty threads: 8/50 (5 busy, 3 idle, 0 queued)
```

I am running `metabase 0.29.0` on `ubuntu 16.04`.
It would be useful if I could find documentation on how to debug this or how the scheduling works in metabase.

**Comment by salsakran** [comment] 2018-07-03 00:19
whats in the log files at the time you scheduled the pulse to go out? 

those are just the database operations for creating/showing pulses, not the attempt to send them.

**Comment by xjzhou** [comment] 2018-07-25 09:45
I can't receive my pulse mail too。 what the keywords about sending log ?

**Comment by jornh** [comment] 2018-07-25 23:17
@ShipraShalini A fix still send emails if Slack can’t be contacted https://github.com/metabase/metabase/issues/7409 has been added in 
https://github.com/metabase/metabase/blame/master/src/metabase/pulse.clj#L214-L219 — maybe your issue falls under this maybe not.

@xjzhou hard to say it depends on where it fails. It could be 
https://github.com/metabase/metabase/blob/7b1ff9637eaea5ce27b5b6e9243cac3894b3fc8d/src/metabase/pulse.clj#L219 or something else depending on where the problem is. **But** you know *when* your pulse is set to send - so you can search your log around that time. Also: Does it fail when you send a test pulse?

**Comment by vitorhirota** [comment] 2018-08-07 18:03
I'm also seeing the same behavior, though I have only email set up. Testing fires it without any problems, automatic pulses do not.  After several days without any pulse, I got one today, but no mention to that in the logs as to why it has successfully gone through.

Any suggestions to track the cause?

**Comment by jornh** [comment] 2018-08-19 15:30
Everybody, I found another older issue already covering missing pulses in https://github.com/metabase/metabase/issues/7389

@ShipraShalini please close this issue and move discussion to #7389 - it’s better to keep everyone in one common discussion.

Also, note there’s already one who found a fix/workaround over there in 
https://github.com/metabase/metabase/issues/7389#issuecomment-401621759 - maybe worth trying for you @ShipraShalini @xjzhou and @vitorhirota as well 😃 

I plan to post more suggestions on #7389

**Comment by kuil09** [comment] 2018-08-23 23:32
Well, I think the problem was timezone.
My environment is docker based container.

I checked database's quartz timezone. It was Asia/Seoul.
But alpine linux timezone wasn't.
So I chagned container's timezone to fit it. 
-- follow this guide https://wiki.alpinelinux.org/wiki/Setting_the_timezone
After then emails sended properly.

**Comment by camsaul** [comment] 2019-05-13 20:47
Hi @kuil09 @jornh @ShipraShalini are you still seeing this on Metabase 0.32.x? We have made big improvements to how Pulses are scheduled and sent in that version

**Comment by camsaul** [comment] 2019-05-13 20:48
This should be fixed in 0.32.0. Please chime in if not and I will reopen

**Closed by camsaul** 2019-05-13 20:48 UTC
Labels: Bug, Priority/P3, Pulses

**Comment by tashiritzy** [comment] 2020-09-03 00:13
> Hi @kuil09 @jornh @ShipraShalini are you still seeing this on Metabase 0.32.x? We have made big improvements to how Pulses are scheduled and sent in that version

We are using v0.34.2 and the pulse email is not consistent. It does send sometimes and after sometime it does not. Is it due to other factors like stale database connection? If so, i can still run my queries or send pulses manually using the send email button.

**Comment by flamber** [comment] 2020-09-03 09:12
@tashiritzy Check your log for errors - Admin > Troubleshooting > Logs.
You're likely seeing #10088 (ignore the Slack thing, just look at my comments), which is caused by the scheduler somehow getting out-of-sync. Though I would recommend that you try the latest release 0.36.4, since there has been a lot of connection handling changes since 0.34.2
