### ISSUE TITLE
js error

### ISSUE THREAD

**Issue by 8debug** [metabase/metabase#15204] opened 2021-03-18 06:07 UTC
# Version Open Source v0.38.2   
# Chrome viersion 88.0.4324.104

## After repeatedly switching the statistical graphs, and then click the Finish button, an error appears in the console
![image](https://user-images.githubusercontent.com/3394927/111579911-c8c2a680-87f1-11eb-9802-1bf287ece3a6.png)
![image](https://user-images.githubusercontent.com/3394927/111579954-d5df9580-87f1-11eb-8f8f-63d7c0f8a607.png)
## When I perform the operation shown in the figure below, the console also reports an error
![image](https://user-images.githubusercontent.com/3394927/111580440-7cc43180-87f2-11eb-8a72-8facee8f83d9.png)
![image](https://user-images.githubusercontent.com/3394927/111580465-88175d00-87f2-11eb-9741-19a25f5e6b93.png)

## Why not support multiple series？As shown below
![image](https://user-images.githubusercontent.com/3394927/111580820-27d4eb00-87f3-11eb-831e-fad9e2ca23a0.png)

**Comment by flamber** [comment] 2021-03-18 10:46
Duplicate of #5855 and #11394

**Closed by flamber** 2021-03-18 10:46 UTC
Labels: .Needs Triage, Type:Bug
