### ISSUE TITLE
App UI appears before initial setup flow is complete

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#25208] opened 2022-09-02 15:17 UTC
**Describe the bug**
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/6377293/188180667-544ad064-37d7-460e-b00c-29d3800824f2.png">

Picture should be self-explanatory. Setup workflow is not yet complete but app UI is showing.

**To Reproduce**
1. grab a jar from CI. I'm using one from https://github.com/metabase/metabase/pull/25149
2. Setup workflow
3. App UI appears after I've posted the user info but before i've clicked on "Take me to metabase" button

**Expected behavior**
app ui does not appear until i'm finished with the setup workflow

**Comment by ranquild** [comment] 2022-09-06 13:10
@dpsutton I've used the most recent jar from the referenced branch and I couldn't reproduce it. Also the same with a jar from master. Are you still able to reproduce it?

**Comment by ranquild** [comment] 2022-09-07 18:12
Closing it since I could not reproduce, feel free to re-open if you still can.

**Closed by ranquild** 2022-09-07 18:12 UTC
Labels: Type:Bug, .Frontend, First Experience/Onboarding, .Regression/master
