### ISSUE TITLE
Database connection errors appear on the wrong fields

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#10646] opened 2019-08-20 20:57 UTC
```Connection to asdf.asdf:1234 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.```

That error should appear under host or port rather than dbname.

![image](https://user-images.githubusercontent.com/691495/63383419-be68ce00-c36a-11e9-9a10-42223ef64322.png)

---

I think the issue comes from [here](https://github.com/metabase/metabase/blob/master/src/metabase/api/database.clj#L316-L334). All thrown errors are returned under `:dbname`

**Comment by kulyk** [comment] 2021-06-18 13:52
Currently on `master` connection errors are displayed near the "Save" button. I guess it can be even better than showing the message near "port" or "host" as a user would need to scroll to see what's wrong. Should we maybe leave it as is? 

![image](https://user-images.githubusercontent.com/17258145/122571424-63cb5680-d055-11eb-8fce-15facc38ffb3.png)

**Comment by flamber** [comment] 2021-06-18 13:56
@kulyk This issue is about the initial setup, which behaves differently than Admin > Databases.

**Comment by ranquild** [comment] 2022-04-18 12:54
This is a backend issue. The problem is that `/api/setup/validate` returns errors for fields that do not exist:

```json
{
  "errors": {
    "dbname":"Hmm, we couldn't connect to the database. Make sure your host and port settings are correct"
  }
}
``` 

To return generic errors not related to any particular field, that backend should set the error message under `message` key:

```json
{
  "message": "Hmm, we couldn't connect to the database. Make sure your host and port settings are correct"
}
```

**Comment by mazameli** [comment] 2022-06-10 00:23
Fixed in https://github.com/metabase/metabase/pull/22804

<img width="607" alt="image" src="https://user-images.githubusercontent.com/2223916/172966139-9119798c-79ad-4888-b8ba-ca81620b932f.png">

**Closed by mazameli** 2022-06-10 00:23 UTC
Labels: Type:Bug, Priority:P2, .Backend, First Experience/Setup
