### ISSUE TITLE
Column name collision when creating a custom question with a join when the name is the same

### ISSUE THREAD

**Issue by sigginet** [metabase/metabase#13856] opened 2020-11-20 12:10 UTC
**Describe the bug**
I am trying to join two tables in a custom 
When creating a custom question and joining data from two columns, each with a column called `name`.
I want the `name` from both of them, but for some reason, the results only output the first input `name` column for both output `name` columns.

**Logs**

**To Reproduce**
1. Create a new question
2. Select Custom question
3. Select a table with a column called `name`
4. Join the table with a different table that has a column called `name`
5. Add a custom column with some data
6. Only display the names from the first table and the second table and the custom column
7. Visualize the data
8. You will get the names from the first table in both column ouputs.

**Expected behavior**
Each `name` column should be different.

**Screenshots**
![image](https://user-images.githubusercontent.com/1608474/99797960-15d68a80-2b28-11eb-8b73-415e5a1a050e.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 86
- Your operating system: Ubuntu 20.04
- Your databases: MySQL 5.6
- Metabase version: 
- Metabase hosting environment: ECS Fargate on AWS ( Docker )
- Metabase internal database: Postgres
```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.193-149.317.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.18"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-10-26",
      "tag": "v0.37.0.2",
      "branch": "release-x.37.x",
      "hash": "ba7be09"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
**Severity**
I'll just convert this to SQL and fix it manually, so it's not severe. Still annoying to not being able to use the query builder because of this.

**Additional context**
SQL output:
```sql
SELECT `source`.`name` AS `name`, `source`.`Admin link` AS `Admin link`, `source`.`name` AS `name_2`
FROM (SELECT concat('https://foo/', `tours`.`id`) AS `Admin link`, `tours`.`name` AS `name`, `Establishments`.`name` AS `name_2`, `tours`.`id` AS `id`, `tours`.`visible` AS `visible`, `tours`.`establishment_id` AS `establishment_id`, `Establishments`.`id` AS `id_2` FROM `tours`
LEFT JOIN `establishments` `Establishments` ON `tours`.`establishment_id` = `Establishments`.`id`) `source`
WHERE `source`.`visible` = 1
LIMIT 1048576
```

The bug is in the outer select, it's selecting `` `source`.`name` `` twice, it should select `` `source`.`name_2` `` in the second selection.

**Comment by flamber** [comment] 2020-11-20 12:28
Duplicate of #12649

**Closed by flamber** 2020-11-20 12:28 UTC
Labels: .Needs Triage, Type:Bug
