### ISSUE TITLE
Inconsistent Behavior: "Is not empty" Filter Shows Empty Results for datetime fields

### ISSUE THREAD

**Issue by mrp97** [metabase/metabase#40723] opened 2024-03-28 12:02 UTC
### Describe the bug

When applying the "Is not empty" filter on a datetime field, the results are inconsistent and shows rows with "empty" fields.

### To Reproduce

1. Open a question with a datetime containing both empty and non-empty values.
2. Click the filter dropdown for the desired field.
3. Select the "Exclude" option.
4. Select the "Is not empty" option.
5. Observe that it shows the "empty" rows.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-CA",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.4.0-163-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.2 (Debian 15.2-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-14",
      "tag": "v0.49.0",
      "hash": "46c668b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Medium

### Additional context

![image](https://github.com/metabase/metabase/assets/15375579/979e4610-9986-415c-a278-0bbf6efab9f2)

**Comment by ranquild** [comment] 2024-07-10 19:27
We could use `is-empty` I think, need to double check

**Comment by nemanjaglumac** [comment] 2024-07-11 08:43
@mrp97 you chose to **exclude** (repro step 3) non-empty fields (repro step 4).
The result will show empty rows.

Did you mean to exclude the empty fields instead?

**Comment by nemanjaglumac** [comment] 2024-07-11 12:29
I think it's safe to close this issue because:
1. the OP described the expected behavior
2. we have A LOT of E2E tests that cover this

https://github.com/metabase/metabase/blob/e62d098b6d544fef2aa1d28e556767cc71be2e03/e2e/test/scenarios/filters/filter-types.cy.spec.js#L306-L375

@mrp97 if I misunderstood you, please let me know or provide some additional details and we can reopen the issue.

**Closed by nemanjaglumac** 2024-07-11 12:29 UTC
Labels: Type:Bug, Priority:P2, Querying/MBQL, .Frontend, .Backend, .Product Input Needed, .Team/QueryingComponents

**Comment by mrp97** [comment] 2024-07-19 15:18
> I think it's safe to close this issue because:
> 
>     1. the OP described the expected behavior
> 
>     2. we have A LOT of E2E tests that cover this
> 
> 
> https://github.com/metabase/metabase/blob/e62d098b6d544fef2aa1d28e556767cc71be2e03/e2e/test/scenarios/filters/filter-types.cy.spec.js#L306-L375
> 
> @mrp97 if I misunderstood you, please let me know or provide some additional details and we can reopen the issue.

@nemanjaglumac Actually I was wrong! Everything worked properly. It was a mistake by me that I clicked on the "Exclude" options!

Maybe it's a UX concern. For me finding rows where those specific field is "Non Empty" is important, so I should "Exclude Empty" rows. It confused me at first. By the way thanks for your follow up and I'm sorry for the mistake!
