### ISSUE TITLE
Pie chart looses responsiveness when browser screen zooms.

### ISSUE THREAD

**Issue by danishpatelcex** [metabase/metabase#9180] opened 2018-12-28 06:21 UTC
Please find the attachment, where part of  pie chart gets hidden when browser screen is zoom out and zoom in.

Steps to reproduce:
1) Create dashboard containing Pie Chart.
2) Zoom in (Ctrl - ) browser screen
3) Zoom out (Ctrl +) browser screen
4) Please check the attachment (Part of pie chart  gets hidden)

Please find details below:

Your browser and the version: Chrome 71.0.3578.80 (Official Build) (64-bit)
Your operating system: Windows 10
Your databases: MySQL
Metabase version: v0.32.0
Metabase hosting environment: Linux/Ubuntu
Metabase internal database: MySQL

![browser resize issue](https://user-images.githubusercontent.com/13693154/50504958-f0a18480-0a96-11e9-9e43-570b8fdad850.png)

**Comment by MarkRx** [comment] 2018-12-28 20:35
Yea I've noticed pie charts seem to scale funny too. I suggest making an animated git using a program called screentogif to demonstrate what you are reporting.

**Comment by danishpatelcex** [comment] 2018-12-31 10:54
Hi Mark,

Please find the attachment (gif demonstration for Pie chart losing responsiveness while resizing browser ) 
![piebrowserresizeissue](https://user-images.githubusercontent.com/13693154/50558975-594b6400-0d18-11e9-91b1-5f9d7ee35e45.gif)

**Comment by rafischer1** [comment] 2019-10-01 16:39
Still having this responsiveness issue when pie chart resizes after side-nav toggle.

**Comment by flamber** [comment] 2019-10-01 17:32
@rafischer1 Which version of Metabase and which browser? There has been a lot of changes to pie charts in 0.33, so I cannot reproduce this issue on 0.33.3

**Comment by rafischer1** [comment] 2019-10-01 22:49
@flamber 

"version":{ "tag":"v0.31.2","date":"2018-12-05"... }
browser: chrome

will look into upgrading. thanks!

**Comment by flamber** [comment] 2020-03-18 11:47
This was probably fixed in 0.33.1 - I cannot reproduce on 0.34.3

**Closed by flamber** 2020-03-18 11:47 UTC
Labels: Type:UX, Visualization/
