### ISSUE TITLE
Full-app embedding url parameters impact "New" dropdown options

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#27355] opened 2022-12-20 19:40 UTC
## Context
When I log into the Metabase app as "Mary Smith" and click the "New" CTA then I see several options as expected:

<img width="804" alt="Screenshot 2022-12-20 at 14 32 53" src="https://user-images.githubusercontent.com/16455495/208752583-3029749a-7819-47c9-88e2-66f712769128.png">

However, when this frame is full-app embedded with URL params `top_nav=true&new_button=true&side_nav=false` then "Question" is missing as an option. If I remove the `side_nav` param from the embed then "Question" reappears and things work as expected again.

<img width="1914" alt="Screenshot 2022-12-20 at 14 38 42" src="https://user-images.githubusercontent.com/16455495/208752543-7a2b4338-0ba2-4995-8122-eb098bb30205.png">

## Expected behavior
When I choose to remove the side navigation from a full-app embed using the `side_nav=false` URL param, it shouldn't impact the options that are shown in the "New" dropdown.

**Comment by flamber** [comment] 2022-12-21 09:27
Duplicate of #21511

**Closed by flamber** 2022-12-21 09:27 UTC
Labels: Type:Bug, .Frontend, Embedding/Interactive
