### ISSUE TITLE
Query builder date filter not formatted according to client language or database user language

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#8951] opened 2018-11-15 23:21 UTC
- Your browser and the version: 70.0.3538.77 (Official Build) (64-bit), also issue in IE and Firefox.
- Your operating system: Windows 7
- Your databases: SQL Server
- Metabase version: v0.31.0
- Metabase hosting environment: Windows jar file
- Metabase internal database: H2 (same result in Postgres though)

We're in New Zealand where dates should be formatted **"DD/MM/YYYY"** and our Windows machines have language set to NZ English, our SQL Server that Metabase uses is set to use "British English". I've tried various Metabase settings around reporting timezone without any luck.

Pull in any data set into the query builder. Attempt to add a date "between" filter.

Metabase query builder date filter only seems to show in "MM/DD/YYYY".
![image](https://user-images.githubusercontent.com/4504437/48587866-a8704c00-e999-11e8-9042-cedb70407a7b.png)

Am I missing a setting or is it not that simple?

Thanks

**Comment by flamber** [comment] 2018-11-16 03:37
@notrom This is a UI bug, not a data bug - right?
It would probably be most correct if the UI followed the new format-settings located in /admin/settings/formatting

**Comment by notrom** [comment] 2018-11-16 03:47
Yes I think it's a UI issue, it's the date filter fields in the query builder. I've just tried tweaking those settings as I hadn't spotted them before but it had no impact on the display in the filter.

**Comment by flamber** [comment] 2018-11-16 03:51
@notrom I can confirm it's a bug, but the formatting was added in 0.31 and there's still some minor issues with it - besides the filter-selectors you're talking about.

**Comment by flamber** [comment] 2020-06-01 16:42
@notrom I'm going to close this in favor of #9151, since I have just changed to a correctness bug

**Closed by flamber** 2020-06-01 16:42 UTC
Labels: Customization/Formatting, Priority:P3, Querying/GUI, Type:Bug
