### ISSUE TITLE
Refresh dependent graphs/tables in underlying column change

### ISSUE THREAD

**Issue by nitsujri** [metabase/metabase#20871] opened 2022-03-07 05:18 UTC
**Describe the bug**
Not sure if this is a bug or a feature request, thanks for helping me sort!

When writing native queries, [adding new columns were previously getting hidden](https://github.com/metabase/metabase/issues/15393). This was fixed in https://github.com/metabase/metabase/pull/16761.

But, any tables/charts based on the underlying query do not get updated. It requires a DB column sync in the admin area (not all users have the ability).

**To Reproduce**
1. Ask a question → Native question
1. Fill in `select 1 as visible, 2 as hidden`
1. Run the query, so there are some results
1. Click the "Settings" button in the bottom left
1. Press the X icon next to the column named hidden to hide it
2. Save native query as "Native Query"
3. Explore results.
4. Save explored results as "Explored Results"
1. Return to native query
2. Add 3 as added to the query, so it's `select 1 as visible, 2 as hidden, 3 as hidden_new`
6. Save & replace "Native Query"
7. Visit "Explored Results" table
8. See that the column `hidden_new` is missing.
9. Visit admin area.
10. Visit Database, select database
11. Run sync columns
12. Wait a moment
13. Go to "Explored Results" table
14. See `hidden_new` is available. 

**Expected behavior**
Changing native query columns should automatically refresh downstream graphs/tables that depend on it and should not require a manual DB column sync.

**Comment by flamber** [comment] 2022-03-07 12:47
Hi @nitsujri 
In step 11 you forgot to run the query before saving, which is what updates the `query.result_metadata`
Sync has no impact on SQL questions, but you probably viewed the SQL question at some point between step 11 and 19.
Duplicate of #14016

**Closed by flamber** 2022-03-07 12:47 UTC
Labels: Type:Bug, .Needs Triage
