### ISSUE TITLE
Chart with 2 x axis dimensions, all points incorrectly have the same colour

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#15585] opened 2021-04-13 01:42 UTC
**Describe the bug**
Plotting data (can be raw table or summary, it seems to apply to both) with 2 dimensions on the x axis produces charts with all the points having the same colour and breakout label, the breakout is incorrect. the underlying data appears to be correct this is a chart issue.

**To Reproduce**
1. New question > Sample Dataset > Products
2. Visualisation changed to Scatter
3. Settings > Data > x-axis "Title" and "Category"
4. y-axis "Price"
5. All dots are green and it's showing 4 "categories" in the legend at the top, all green and saying "Gadget"
6. Change plot type, all points remain green
7. Do a max Price summary by Title and Category, again plot as above, all still green.

**Expected behavior**
4 different categories in this table of data should give 4 different dot colours and 4 different labels.

**Screenshots**
Side by side difference between v.0.39-rc1 and v0.38.1 to show difference:
![image](https://user-images.githubusercontent.com/4504437/114483958-6bd5d700-9c5d-11eb-9c6a-d90c31aaf2a1.png)

Detail record and hover detail mismatch, Category is wrong in the hover:
![image](https://user-images.githubusercontent.com/4504437/114483868-434ddd00-9c5d-11eb-9b8b-8a96e703268b.png)
![image](https://user-images.githubusercontent.com/4504437/114483873-4943be00-9c5d-11eb-8ed2-ffbb1def501d.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "13.0.2+8",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-06",
      "tag": "v0.39.0-rc1",
      "branch": "release-x.39.x",
      "hash": "471eda1"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**
Unless I'm doing something wrong this is going to be a significant issue. Any chart with multiple dimensions is going to be affected.

**Comment by flamber** [comment] 2021-04-13 09:12
Hi @notrom 
I'm unsure what's going on, but I have a feeling that it might be browser cache. There has been a lot of underlying changes to how fields are defined, which I initially thought was the problem, and would definitely be a P1, but I cannot reproduce:
![image](https://user-images.githubusercontent.com/1447303/114527848-b862e780-9c48-11eb-91dc-84ea17d5aae9.png)
![image](https://user-images.githubusercontent.com/1447303/114525877-c283e680-9c46-11eb-9cef-cc662e39b2bf.png)
![image](https://user-images.githubusercontent.com/1447303/114525920-cca5e500-9c46-11eb-87cb-53c2ce4e5141.png)
Screenshot from 0.39.0-rc2, but the other versions shows exactly the same in the tooltip on hover.
![image](https://user-images.githubusercontent.com/1447303/114527039-d11ecd80-9c47-11eb-91de-e2f8ea8c4046.png)

**Comment by notrom** [comment] 2021-04-14 21:46
@flamber I tried this again with fresh browser session and the same instance of Metabase v0.39.0-rc1 and couldn't reproduce. At the time I was seeing the issue I was seeing it consistently.

You're probably right, cache related. Not ideal but could be very rare case? If I see it again I'll update this ticket.

**Comment by flamber** [comment] 2021-04-15 09:39
@notrom Since I don't know how you're accessing Metabase (reverse-proxy, CDN or ...), then it's difficult for me to tell if that could be the cause, but I've spend way too many hours tracking down really annoying problems with reverse-proxies:
https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html

When I switch versions 20-50 times daily, then I almost always browser refresh, since it can cause some really funky problems between most versions, but since 0.39 has upgraded React and a lot of other frontend stuff, then if I switch from 0.38.4 to 0.39 (or vice-versa) without doing a browser refresh, it causes a lot of things are behaving strange.

I'll close the issue, but please comment back if you see this again - double :thumbs: if it can be reproduced everywhere.

**Closed by flamber** 2021-04-15 09:39 UTC
Labels: .Needs Triage, Type:Bug

**Comment by notrom** [comment] 2021-04-18 22:18
@flamber this is with Metabase running on my local machine from the jar file, nothing in between me and Metabase except the browser (Chrome).

I had it happen again with my own data, refreshed the browser and it resolved it. No consistent repro sorry.

**Comment by flamber** [comment] 2021-04-19 08:06
@notrom Hmmm.... that's really frustrating, since that makes it sound like a React state issue, which can normally only be reproduced in the same tab doing a specific combination of things - doing a browser refresh or doing a slightly different combination of steps will not cause this.
Example of a state issues, which is only reproducible if a particular set of steps is followed in a specific order - 12904 - 15620
I really want to nail this, since it's a P1 (unless it requires some weird combination of steps that most people won't do).

**Comment by notrom** [comment] 2021-04-19 21:30
@flamber I've been trying to get a reliable repro for this but can't do it. I don't  think I was dong anything out of the ordinary when this happened.

In saying that it's not happening very often and is resolved by a refresh. I wouldn't want to distract away from feature development to hunt this down. Is there anything I can examine in the javascript console if this happens again that would help capture the state let me know.

**Comment by flamber** [comment] 2021-04-20 09:00
@notrom If you see anything in the browser console, which only happens, when you see this problem, then that might lead us in the right direction, but I have a feeling there might be anything in the console.
If you check the responses, I'm guessing that all the data results returned are actually correct - and exactly the same responses as when it works correct (after browser refresh) ? If there's difference, then the HAR dump of that would be great!
Capturing state issues would require you have the React browser extension loaded, but that's a lot of investigation.
