### ISSUE TITLE
Text blocks on dashboard clip when zoomed in

### ISSUE THREAD

**Issue by Limess** [metabase/metabase#12903] opened 2020-07-13 08:46 UTC
**Describe the bug**
If the text size of a dashboard text box results in the text overflowing the vertical height of the container, the text is clipped and there is no way to scroll to see the content.

**To Reproduce**
1. Create a dashboard
2. Edit the dashboard
3. Add a text-box which is 2 columns tall
4. Add a multi-line section of text to the new text-box to the point where the preview shows the text just fit in the text box
5. Zoom in on your browser (`ctrl/cmd +`)
6. Note that the bottom lines of the text are clipped and not visible

**Expected behavior**
I'd expect a scrollbar to be shown on the text boxes to prevent the clipping, as users are likely to have higher-than-default zoom for accessibility reasons.

**Screenshots**

Zoomed in 100%

![100% no clip example](https://user-images.githubusercontent.com/3199181/87283918-b5866b00-c4ed-11ea-8c57-bef107f3ea22.png)

Zoomed in 120%
![120% clipping example](https://user-images.githubusercontent.com/3199181/87283785-94257f00-c4ed-11ea-9c74-51fb104dea1a.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox 77.0.1. Chrome 83.0.4103.116 (Official Build) (64-bit)
- Your operating system: OSX 10.15.5
- Your databases: Not relevant
- Metabase version: (e.x. 0.35.4
- Metabase hosting environment: AWS ECS
- Metabase internal database: Postgres

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:77.0) Gecko/20100101 Firefox/77.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.173-137.229.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**
This affects a member of our team who operates with a higher-than-default zoom percentage, and as such we need to make the dashboard taller/less comfortable for other users as a result.

**Comment by flamber** [comment] 2020-07-13 08:57
Duplicate of #8333 - will be fixed by #12766

**Closed by flamber** 2020-07-13 08:57 UTC
Labels: .Needs Triage, Type:Bug
