### ISSUE TITLE
Matomo Analytics integration

### ISSUE THREAD

**Issue by Chardonneaur** [metabase/metabase#16286] opened 2021-05-29 19:22 UTC
**Is your feature request related to a problem? Please describe.**
Currently Metabase supports Google Analytics but not Matomo. As Metabase is a Free software solution, one would expect it to be integrated with other Free software project such as Matomo Analytics. Currently there is no easy way to bundle those two.

**Describe the solution you'd like**
Some people suggest to plug Metabase on the MySQL Matomo database, but this option does not really work as a report within Matomo is the sequence of probably 6 to 10 different SQL queries, so to say a mere analyst cannot go that far in just getting a simple report. In fact Matomo is designed to be request through its API which is super easy to handle: https://developer.matomo.org/api-reference/reporting-api you can find all the methods to call on the previous link.

**Describe alternatives you've considered**
As mentioned previously plugging it on the MySQL database is giving inaccurate results.

**How important is this feature to you?**
This integration is the only way that Matomo users can promote Metabase. Matomo is the second most used standard analytics solution on the planet after Google Analytics and the only real alternative to GA.

**Additional context**
Just have a try to the Matomo API, you don't even need to install it, you can directly play with the demo api at the following link if you don't feel comfortable with it (it just take 10 minutes to understand it): https://demo.matomo.cloud/index.php?module=API&action=listAllAPI&idSite=1&period=day&date=yesterday#Actions
for example: https://demo.matomo.cloud/index.php?module=API&method=Actions.getPageUrls&idSite=1&period=day&date=yesterday&format=Tsv&token_auth=anonymous&translateColumnNames=1 will give you the list of pages viewed yesterday on the website requested.

**Comment by flamber** [comment] 2021-05-29 19:32
It would require that there was a generic REST driver, which Matomo driver could be built upon. Duplicate of #4097/#4831

**Closed by flamber** 2021-05-29 19:32 UTC
Labels: .Needs Triage, Type:New Feature

**Comment by Dynnammo** [comment] 2021-06-02 15:40
@Chardonneaur a workaround I found is using the Matomo API, allowing yourself to pull CSV file that are hereafter concatenated in a SQLITE database https://github.com/OpenSourcePolitics/matomo_import

**Comment by Chardonneaur** [comment] 2021-06-08 06:52
@Dynnammo thank you so much, I haven't yet tested your script, but it seems that it is doing exactly what I am looking for.
My next question is how do you fix the row data date calculation? For the rest, if you let me one way to contact you I can advertise your script and help the community in a tremendous way.
