### ISSUE TITLE
Empty statement results causes reducer error, which causes the entire query to fail

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16182] opened 2021-05-21 11:29 UTC
**Describe the bug**
While multi-statements are officially not supported #4050, 0.39.0 introduced an upgraded driver #15287, which now causes empty statement results to produce an error like `Select statement did not produce a ResultSet for native query`, which prevent the entire query from working.

This is has been reported for SQL Server, but might be a more general problem.

It might be possible to rewrite some queries to [CTEs](https://www.metabase.com/learn/building-analytics/sql-templates/sql-cte.html), but for some queries this might not be feasible or require a lot of work.

Creating stored procedures on the db also errors unless they have `SET NOCOUNT ON` in the beginning of the procedure.
This seems to be an [old mssql-jdbc issue](https://github.com/microsoft/mssql-jdbc/issues/313), so not sure how the change in 0.39 made that different for us.

**To Reproduce**
1. Native query > SQL Server:
```
drop table if exists #myTemporaryTable;
select 1;
```
2. Errors with `Select statement did not produce a ResultSet for native query`
![image](https://user-images.githubusercontent.com/1447303/119130209-2fee1880-ba38-11eb-8603-b8178a8c2800.png)

<details><summary>Full stacktrace</summary>

```
2021-05-21 13:26:33,775 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 20,
 :started_at #t "2021-05-21T13:26:31.148017+02:00[Europe/Copenhagen]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__79533.invoke(execute.clj:470)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:467)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:453)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:462)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:453)"
    "driver.sql_jdbc$fn__80985.invokeStatic(sql_jdbc.clj:54)"
    "driver.sql_jdbc$fn__80985.invoke(sql_jdbc.clj:52)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47305.invoke(mbql_to_native.clj:25)"
    "query_processor.middleware.check_features$check_features$fn__46547.invoke(check_features.clj:39)"
    "query_processor.middleware.limit$limit$fn__47291.invoke(limit.clj:37)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__45999.invoke(cache.clj:211)"
    "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__47551.invoke(optimize_temporal_filters.clj:204)"
    "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__49481.invoke(validate_temporal_bucketing.clj:50)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__45118.invoke(auto_parse_filter_values.clj:43)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__41435.invoke(wrap_value_literals.clj:161)"
    "query_processor.middleware.annotate$add_column_info$fn__41310.invoke(annotate.clj:605)"
    "query_processor.middleware.permissions$check_query_permissions$fn__46419.invoke(permissions.clj:81)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__48409.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46620.invoke(cumulative_aggregations.clj:60)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__48708.invoke(resolve_joined_fields.clj:102)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__49021.invoke(resolve_joins.clj:171)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44694.invoke(add_implicit_joins.clj:190)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__47255.invoke(large_int_id.clj:59)"
    "query_processor.middleware.format_rows$format_rows$fn__47236.invoke(format_rows.clj:74)"
    "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__43988.invoke(add_default_temporal_unit.clj:23)"
    "query_processor.middleware.desugar$desugar$fn__46686.invoke(desugar.clj:21)"
    "query_processor.middleware.binning$update_binning_strategy$fn__45505.invoke(binning.clj:227)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__46222.invoke(resolve_fields.clj:34)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__44343.invoke(add_dimension_projections.clj:312)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__44572.invoke(add_implicit_clauses.clj:147)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__49430.invoke(upgrade_field_literals.clj:40)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44857.invoke(add_source_metadata.clj:123)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__48583.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45065.invoke(auto_bucket_datetimes.clj:147)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46269.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__48391.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46321.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__46942.invoke(expand_macros.clj:155)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44866.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49383.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48594$fn__48598.invoke(resolve_database_and_driver.clj:31)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48594.invoke(resolve_database_and_driver.clj:25)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47182.invoke(fetch_source_query.clj:274)"
    "query_processor.middleware.store$initialize_store$fn__49392$fn__49393.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__49392.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__49437.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__47318.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44712.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49368.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__46563.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__48480.invoke(process_userland_query.clj:135)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46503.invoke(catch_exceptions.clj:173)"
    "query_processor.reducible$async_qp$qp_STAR___37989$thunk__37990.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___37989.invoke(reducible.clj:109)"
    "query_processor.reducible$sync_qp$qp_STAR___37998$fn__38001.invoke(reducible.clj:135)"
    "query_processor.reducible$sync_qp$qp_STAR___37998.invoke(reducible.clj:134)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:241)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:237)"
    "query_processor$fn__49527$process_query_and_save_execution_BANG___49536$fn__49539.invoke(query_processor.clj:253)"
    "query_processor$fn__49527$process_query_and_save_execution_BANG___49536.invoke(query_processor.clj:245)"
    "query_processor$fn__49571$process_query_and_save_with_max_results_constraints_BANG___49580$fn__49583.invoke(query_processor.clj:265)"
    "query_processor$fn__49571$process_query_and_save_with_max_results_constraints_BANG___49580.invoke(query_processor.clj:258)"
    "api.dataset$run_query_async$fn__55784.invoke(dataset.clj:56)"
    "query_processor.streaming$streaming_response_STAR_$fn__55763$fn__55764.invoke(streaming.clj:72)"
    "query_processor.streaming$streaming_response_STAR_$fn__55763.invoke(streaming.clj:71)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$fn__16071.invoke(streaming_response.clj:84)"],
   :error_type :invalid-query,
   :ex-data
   {:sql
    "-- Metabase:: userID: 1 queryType: native queryHash: 1b671306840b04531e6a4a4fcc56cd0d6dbfdb671c65eb3c14850b139b358a26\ndrop table if exists #myTemporaryTable;\nselect 1;",
    :params nil,
    :type :invalid-query}}],
 :error_type :invalid-query,
 :json_query
 {:type "native",
  :native {:query "drop table if exists #myTemporaryTable;\nselect 1;", :template-tags {}},
  :database 20,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> driver.sql_jdbc.execute$fn__79453.invokeStatic(execute.clj:336)"
  "driver.sql_jdbc.execute$fn__79453.invoke(execute.clj:332)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:342)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:339)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__79533.invoke(execute.clj:468)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:467)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:453)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:462)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:453)"
  "driver.sql_jdbc$fn__80985.invokeStatic(sql_jdbc.clj:54)"
  "driver.sql_jdbc$fn__80985.invoke(sql_jdbc.clj:52)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
  "query_processor.context.default$default_runf.invoke(default.clj:66)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47305.invoke(mbql_to_native.clj:25)"
  "query_processor.middleware.check_features$check_features$fn__46547.invoke(check_features.clj:39)"
  "query_processor.middleware.limit$limit$fn__47291.invoke(limit.clj:37)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__45999.invoke(cache.clj:211)"
  "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__47551.invoke(optimize_temporal_filters.clj:204)"
  "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__49481.invoke(validate_temporal_bucketing.clj:50)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__45118.invoke(auto_parse_filter_values.clj:43)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__41435.invoke(wrap_value_literals.clj:161)"
  "query_processor.middleware.annotate$add_column_info$fn__41310.invoke(annotate.clj:605)"
  "query_processor.middleware.permissions$check_query_permissions$fn__46419.invoke(permissions.clj:81)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__48409.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46620.invoke(cumulative_aggregations.clj:60)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__48708.invoke(resolve_joined_fields.clj:102)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__49021.invoke(resolve_joins.clj:171)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44694.invoke(add_implicit_joins.clj:190)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__47255.invoke(large_int_id.clj:59)"
  "query_processor.middleware.format_rows$format_rows$fn__47236.invoke(format_rows.clj:74)"
  "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__43988.invoke(add_default_temporal_unit.clj:23)"
  "query_processor.middleware.desugar$desugar$fn__46686.invoke(desugar.clj:21)"
  "query_processor.middleware.binning$update_binning_strategy$fn__45505.invoke(binning.clj:227)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__46222.invoke(resolve_fields.clj:34)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__44343.invoke(add_dimension_projections.clj:312)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__44572.invoke(add_implicit_clauses.clj:147)"
  "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__49430.invoke(upgrade_field_literals.clj:40)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44857.invoke(add_source_metadata.clj:123)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__48583.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45065.invoke(auto_bucket_datetimes.clj:147)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46269.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48391.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46321.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__46942.invoke(expand_macros.clj:155)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44866.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49383.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48594$fn__48598.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48594.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47182.invoke(fetch_source_query.clj:274)"
  "query_processor.middleware.store$initialize_store$fn__49392$fn__49393.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__49392.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__49437.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__47318.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44712.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49368.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__46563.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__48480.invoke(process_userland_query.clj:135)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46503.invoke(catch_exceptions.clj:173)"
  "query_processor.reducible$async_qp$qp_STAR___37989$thunk__37990.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___37989.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___37998$fn__38001.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___37998.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:241)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:237)"
  "query_processor$fn__49527$process_query_and_save_execution_BANG___49536$fn__49539.invoke(query_processor.clj:253)"
  "query_processor$fn__49527$process_query_and_save_execution_BANG___49536.invoke(query_processor.clj:245)"
  "query_processor$fn__49571$process_query_and_save_with_max_results_constraints_BANG___49580$fn__49583.invoke(query_processor.clj:265)"
  "query_processor$fn__49571$process_query_and_save_with_max_results_constraints_BANG___49580.invoke(query_processor.clj:258)"
  "api.dataset$run_query_async$fn__55784.invoke(dataset.clj:56)"
  "query_processor.streaming$streaming_response_STAR_$fn__55763$fn__55764.invoke(streaming.clj:72)"
  "query_processor.streaming$streaming_response_STAR_$fn__55763.invoke(streaming.clj:71)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$fn__16071.invoke(streaming_response.clj:84)"],
 :context :ad-hoc,
 :error "Select statement did not produce a ResultSet for native query",
 :row_count 0,
 :running_time 0,
 :ex-data
 {:sql
  "-- Metabase:: userID: 1 queryType: native queryHash: 1b671306840b04531e6a4a4fcc56cd0d6dbfdb671c65eb3c14850b139b358a26\ndrop table if exists #myTemporaryTable;\nselect 1;",
  :driver :sqlserver},
 :data {:rows [], :cols []}}

2021-05-21 13:26:33,823 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 2.7 s (6 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (4 idle, 0 queued) (50 total active threads) Queries in flight: 1 (0 queued)
```

</details>

**Expected behavior**
The first statement to be executed and empty resultset to be ignored, and then run second statement and show result from that.
This is 0.38.4:
![image](https://user-images.githubusercontent.com/1447303/119129980-e56c9c00-ba37-11eb-9b34-97400025e1f9.png)

**Information about your Metabase Installation:**
Regression since 0.39.0 - tested 0.38.4 thru 0.39.2

**Additional context**
https://discourse.metabase.com/t/sql-queries-broken-in-0-39-0-1/14468

**Comment by camsaul** [comment] 2021-06-07 17:16
We don't support executing statements such as DDL or DML that don't return results, and we don't support running multiple queries/executing multiple statements at once/ Metabase is for running queries, not for `DROP TABLE` statements. Can you give us an example of a valid use case for this?

I'm not sure we should do anything to change this because we shouldn't encourage this. Ideally Metabase would throw an error immediately on the first statement because the connection is read-only.

**Comment by flamber** [comment] 2021-06-07 17:20
There's examples in ticket 5074 and https://discourse.metabase.com/t/sql-queries-broken-in-0-39-0-1/14468/7?u=flamber

**Comment by camsaul** [comment] 2021-06-22 20:58
Ok, those examples are ones we've explicitly tried not to support in the past. See for example #10258 where we're trying to figure out how to explictly disallow DDL/DML statements for BigQuery or #3916 which we closed as "won't fix" when someone asked us to allow read-write connections to H2.

Marking this as "Won't Fix" and removing the "Bug" designation since this behavior is by design.

**Closed** 2021-06-22 20:58 UTC
Labels: .Backend, .Can't Cypress Test, .Regression, .Won't Fix, Database/SQLServer, Difficulty:Easy, Priority:P2, Querying/Processor
