### ISSUE TITLE
Date filter enhancement

### ISSUE THREAD

**Issue by taker93** [metabase/metabase#7940] opened 2018-06-26 12:20 UTC
It'll helpful if there was an date filter for "greater than today".

Our tables are designed with a timestamp for the validity of every entry. So we have a "valid from" and "valid until" column in every table.

To make use of Metabase, we always have to use native SQL queries, because most of our SQLs need a Clause for "valid until" > today. At the moment this is not realizable with the builder.

We also cannot use segments and metrics because of that. They don't allow native queries.

**Comment by flamber** [comment] 2019-02-22 02:03
Hi @taker93 
This sounds like a duplicate of https://github.com/metabase/metabase/issues/4083#issuecomment-283915746 or #6433

**Comment by mazameli** [comment] 2019-10-11 00:11
Closing as duplicate of #4083

**Closed by mazameli** 2019-10-11 00:11 UTC
Labels: .Duplicate, .Proposal, .Query Language (MBQL), Query Builder
