### ISSUE TITLE
Export is not respecting filter

### ISSUE THREAD

**Issue by tatusis** [metabase/metabase#12621] opened 2020-05-30 03:32 UTC
**Export is not respecting filter**

After opening a saved question, if the filter is performed on the header of a column, the export does not respect the selected filter.

I realized that the question does not go into editing mode in this case, and that whenever the question goes into editing mode, the export starts to respect the filter.

**To Reproduce**
1. Browse the data, choose the sample dataset and the people table.
2. After that, save the question.
3. Open the saved question. Filter by the City field is Leakesville.
4. Export the result in xlsx or csv format.
5. Open the generated file.

**Expected behavior**
In any event, the export is expected to respect the filter displayed on the screen.

**Screenshots**
![Screenshot_1_Metabase](https://user-images.githubusercontent.com/55719904/83318454-5dc8c480-a20b-11ea-801b-84429910f0b2.png)

![image](https://user-images.githubusercontent.com/55719904/83318468-8486fb00-a20b-11ea-9739-5121a32b3350.png)

If the filter is removed and added again, apparently, the question goes into edit mode and starts exporting correctly.

![image](https://user-images.githubusercontent.com/55719904/83318526-3292a500-a20c-11ea-8210-d9dc9d37bd58.png)

![image](https://user-images.githubusercontent.com/55719904/83318534-40482a80-a20c-11ea-941c-a0d5006fbb4c.png)

If the user uses the filter button or the editor to perform the filter, the question always goes into editing mode and the export always respects the filter displayed on the screen. That is, only in the filter directly over the column header does the problem appear.

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_241-b07",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_241",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.241-b07",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "America/Sao_Paulo"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "oracle",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.14"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.3",
      "date": "2020-04-21",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
I think that this error is very serious as it can cause the user to generate a file with information different from the filter used.

**Comment by flamber** [comment] 2020-05-30 09:27
Duplicate of #11557

**Closed by flamber** 2020-05-30 09:27 UTC
Labels: .Needs Triage, Type:Bug
