### ISSUE TITLE
Running behind app load balancer fails because of absolute path in web assets

### ISSUE THREAD

**Issue by deitch** [metabase/metabase#4446] opened 2017-02-26 19:35 UTC
Using the latest metabase in container.

Metabase is running as one among many services. To consolidate them, we use an app load balancer: 

* `app.domain.com/a` -> `serviceA:80`
* `app.domain.com/b` -> `serviceB:443`

etc. and

* `app.comon.com/metabase` -> `metabase:3000`

Metabase itself doesn't know it is being proxied, and it mostly doesn't care, serving up the html correctly.

But because it _always_ serves up its assets (js, css, images) using absolute paths (`/app/dist/*` as best as I could tell), it fails.

It looks like metabase uses Webpack to package up the assets... but is there any reason why it has to use absolute paths? 

Conversely, is there any way to override it and say, "expect your root to be at `/foo/metabase/` or similar? Ideal would be completely relative paths, but even some env var to override it would be a start.

Thanks

**Comment by tlrobinson** [comment] 2017-02-27 17:24
Duplicate of #2090

**Closed by tlrobinson** 2017-02-27 17:24 UTC

**Comment by deitch** [comment] 2017-02-27 17:29
Thanks @tlrobinson
