### ISSUE TITLE
Ability to customize the visualization of a question on a dashboard

### ISSUE THREAD

**Issue by urkle** [metabase/metabase#25287] opened 2022-09-07 16:47 UTC
**Is your feature request related to a problem? Please describe.**
It would be nice (in combination to #3575 / #1543) to be able to add a question into a dashbaord and manipulate not only the parameters but also the visualization. 

**Describe the solution you'd like**
We have a dashboard that shows one question (as raw data) showing various groupings of data (pivot table like).

then we have that same source data shown as line graphs (there are multiple columns of data) but filtered to one of the sub-groupings.  We have 6 sub-groupings, thus 6 additional graphs.

Being able to set explicit filters on a single graph would allow reduction of the needed graphs to 1 source question (thus 2 total questions for the dashboard). As teh graph can be added multiple times with different fixed filter for the one parameter. (another parameter for all graphs is tied to a public dashboard filter).

Being able to "customize" the visualization (e.g. switch from TABLE view to line graph) would allow further reduction of source questions as the visualization could be changed and the fixed filter parameter set on the instances of that question in the dashboard.

**Describe alternatives you've considered**
Creating MULTIPLE questions all copies of the original one with different filters and visualizations (even though the underlying data is 100% the same)
OR having 2 copies of the question (one table one line-graph) and having MULTIPLE public dashboard filters that we need to tell users to not touch when looking at the dashboard.

**How important is this feature to you?**
Note: the more honest and specific you are here the more we will take you seriously. 

**Additional context**

**Comment by flamber** [comment] 2022-09-07 16:50
Duplicate of #1824

**Closed by flamber** 2022-09-07 16:50 UTC
Labels: Type:New Feature, .Needs Triage
