### ISSUE TITLE
Allow Sender Name along with email address in Setting > Email > "From Address"

### ISSUE THREAD

**Issue by nitzien** [metabase/metabase#14786] opened 2021-02-12 08:27 UTC
**Is your feature request related to a problem? Please describe.**
Currently "From Address" supports only email address. We cannot add name along with sender email id.

**Describe the solution you'd like**
SMTP additionally supports email from format as ' "Example Sender" <mail@example.com>'. Supporting this will be helpful.

**Describe alternatives you've considered**
I could set the value directly in database in settings table. And everything worked well. So, this is just an issue in front end. 

**How important is this feature to you?**
Not important as I can update from backend.

**Additional context**

![Screenshot from 2021-02-12 13-53-04](https://user-images.githubusercontent.com/531632/107745066-b9a39100-6d39-11eb-9767-4e5a2e9b924b.png)

**Comment by flamber** [comment] 2021-02-12 09:10
Duplicate of #11683/#5812

**Closed by flamber** 2021-02-12 09:10 UTC
Labels: .Needs Triage, Type:New Feature
