### ISSUE TITLE
Can't concatenate and match variables against some strings

### ISSUE THREAD

**Issue by xorwen** [metabase/metabase#7201] opened 2018-03-26 14:58 UTC
- Your browser and the version: Chrome Version 65.0.3325.162 (Official Build) (64-bit)
- Your operating system: Mac OSx 10.13.3 (17D102)
- Your databases: Postgres
- Metabase version: v0.28.3
- Metabase hosting environment: Docker
- Metabase internal database: default

**Replicate issue**

- Install metabase `v0.28.3`
- try `SELECT '{xx}' = concat('{', {{airlines}}, '}')` 
- I expect this to be transformed to `SELECT '{xx}' = concat('{', 'xx', '}')` and return boolean
- actually it gives `org.postgresql.util.PSQLException: ERROR: syntax error at or near "[" Position: 127` 

**Logs**:
```
:query "SELECT [['{xx}' = concat('{', {{airlines}}, '}')]]\n",
26/03/2018 16:35:09   :collection "ab_test_names",
26/03/2018 16:35:09   :template_tags {:airlines {:id "ed1e5bf5-3580-8591-a81e-fd70556be0d7", :name "airlines", :display_name "Airlines", :type "text"}}},
26/03/2018 16:35:09  :parameters [],
```

**In the real use-case** we are matching the variable against an Array (simulated on the left side of the condition). 
I understand that this functionality is not ready yet (https://github.com/metabase/metabase/issues/2974) but the query worked in version ` v0.28.0` that's why I consider it as bug rather than a feature request.

**Simple workaround**

Instead of surrounding  the variable with  `{` and `}`, try to remove the `{`,`}` signs from the other side of the condition like this:

`SELECT trim(both '{}' from '{xx}') =  {{airlines}}`

**Comment by walterl** [comment] 2020-03-12 20:11
Can't reproduce on current `master`. Closing this under the assumption that it was fixed somewhere along the way.

**Closed by walterl** 2020-03-12 20:11 UTC
Labels: Priority:P3, Querying/Native, Querying/Parameters & Variables, Type:Bug
