### ISSUE TITLE
Consider more data source support, such as Clickhouse

### ISSUE THREAD

**Issue by telltime** [metabase/metabase#10990] opened 2019-09-26 07:32 UTC
Consider more data source support, such as Clickhouse

**Comment by amoskaliov** [comment] 2019-09-26 13:00
I can advise you https://github.com/enqueue/metabase-clickhouse-driver . Works perfect.

**Comment by flamber** [comment] 2019-09-26 19:05
Hi @telltime 
As @amoskaliov pointed out, there's a third-party driver available.
You might want to update #3332, if you're asking for getting a driver integrated in main releases.
But please close this issue :+1:

**Comment by salsakran** [comment] 2019-09-26 20:55
duplicate of #3332

**Closed by salsakran** 2019-09-26 20:55 UTC
Labels: Type:New Feature
