### ISSUE TITLE
Value does not match schema: {:field {:field {:fingerprint {:type {:type/DateTime disallowed-key}}}}}

### ISSUE THREAD

**Issue by jonatasfreitasv** [metabase/metabase#7693] opened 2018-05-23 12:36 UTC
**Database:** Druid

Value does not match schema: {:field {:field {:fingerprint {:type {:type/DateTime disallowed-key}}}}}

When filter by period in DateTime filed.

This bug occurred after update to last version.

**Comment by senior** [comment] 2018-05-23 14:38
Can you include the full stacktrace, the steps to reproduce this error and the exact version of Metabase you are using?

**Comment by jonatasfreitasv** [comment] 2018-05-28 17:46
@senior 

```
05-28 17:45:20 WARN metabase.query-processor :: {:status :failed,
 :class clojure.lang.ExceptionInfo,
 :error "Value does not match schema: {:field {:field {:fingerprint {:type {:type/DateTime disallowed-key}}}}}",
 :stacktrace
 ["query_processor.middleware.resolve$fn__28001.invokeStatic(resolve.clj:240)"
  "query_processor.middleware.resolve$fn__28001.invoke(resolve.clj:222)"
  "query_processor.middleware.resolve$fn__27984$G__27979__27991.invoke(resolve.clj:218)"
  "query_processor.middleware.resolve$value_ph_resolve_field.invokeStatic(resolve.clj:276)"
  "query_processor.middleware.resolve$value_ph_resolve_field.invoke(resolve.clj:270)"
  "query_processor.middleware.resolve$fn__27892$G__27874__27899.invoke(resolve.clj:83)"
  "util$rpartial$fn__2828.doInvoke(util.clj:463)"
  "query_processor.middleware.resolve$resolve_fields.invokeStatic(resolve.clj:342)"
  "query_processor.middleware.resolve$resolve_fields.invoke(resolve.clj:325)"
  "query_processor.middleware.resolve$resolve.invokeStatic(resolve.clj:411)"
  "query_processor.middleware.resolve$resolve.invoke(resolve.clj:408)"
  "query_processor.middleware.resolve$resolve_middleware$fn__28067.invoke(resolve.clj:422)"
  "query_processor.middleware.expand$expand_middleware$fn__29767.invoke(expand.clj:601)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__28151.invoke(add_row_count_and_status.clj:14)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__29898.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__31311.invoke(resolve_driver.clj:15)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__28619.invoke(cache.clj:146)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__29815.invoke(catch_exceptions.clj:58)"
  "query_processor$process_query.invokeStatic(query_processor.clj:130)"
  "query_processor$process_query.invoke(query_processor.clj:126)"
  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:241)"
  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:235)"
  "query_processor$fn__31345$process_query_and_save_execution_BANG___31350$fn__31351.invoke(query_processor.clj:281)"
  "query_processor$fn__31345$process_query_and_save_execution_BANG___31350.invoke(query_processor.clj:267)"
  "query_processor$fn__31369$process_query_and_save_with_max_BANG___31374$fn__31375.invoke(query_processor.clj:302)"
  "query_processor$fn__31369$process_query_and_save_with_max_BANG___31374.invoke(query_processor.clj:298)"
  "api.dataset$fn__37889$fn__37892$fn__37893.invoke(dataset.clj:49)"
  "api.common$fn__20323$invoke_thunk_with_keepalive__20328$fn__20329$fn__20330.invoke(common.clj:402)"],
 :query
 {:type "query",
  :query {:source_table 530, :filter ["BETWEEN" ["field-id" 6930] "2018-05-28" "2018-05-29"], :aggregation [["count"]]},
  :parameters [],
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :info
  {:executed-by 13,
   :context :ad-hoc,
   :card-id nil,
   :nested? false,
   :query-hash [25, 81, -106, -42, -75, 18, 81, -28, -107, 16, 117, 127, -88, -52, 80, 57, 32, 74, -84, -65, 52, 37, 56, -47, -35, -91, 63, -29, 5, -81, -47, 56],
   :query-type "MBQL"}},
 :expanded-query nil,
 :ex-data
 {:type :schema.core/error,
  :value
  {:value #inst "2018-05-28T03:00:00.000000000-00:00",
   :field
   {:field
    {:field-id 6930,
     :field-name "timestamp",
     :field-display-name "Timestamp",
     :database-type "timestamp",
     :base-type :type/DateTime,
     :special-type :type/PK,
     :visibility-type :normal,
     :table-id 530,
     :schema-name nil,
     :table-name nil,
     :position nil,
     :fk-field-id nil,
     :description nil,
     :parent-id nil,
     :parent nil,
     :remapped-from nil,
     :remapped-to nil,
     :dimensions [],
     :values [],
     :fingerprint {:global {:distinct-count 9624}, :type {:type/DateTime {:earliest "2017-12-05T14:26:45.668Z", :latest "2017-12-05T21:19:37.801Z"}}}},
    :unit :day}},
  :error {:field {:field {:fingerprint {:type {:type/DateTime disallowed-key}}}}}}}

05-28 17:45:20 WARN metabase.query-processor :: Query failure: Value does not match schema: {:field {:field {:fingerprint {:type {:type/DateTime disallowed-key}}}}}
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:209)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:202)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:242)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:235)"
 "query_processor$fn__31345$process_query_and_save_execution_BANG___31350$fn__31351.invoke(query_processor.clj:281)"
 "query_processor$fn__31345$process_query_and_save_execution_BANG___31350.invoke(query_processor.clj:267)"
 "query_processor$fn__31369$process_query_and_save_with_max_BANG___31374$fn__31375.invoke(query_processor.clj:302)"
 "query_processor$fn__31369$process_query_and_save_with_max_BANG___31374.invoke(query_processor.clj:298)"
 "api.dataset$fn__37889$fn__37892$fn__37893.invoke(dataset.clj:49)"
 "api.common$fn__20323$invoke_thunk_with_keepalive__20328$fn__20329$fn__20330.invoke(common.clj:402)"]

```

**Comment by senior** [comment] 2018-05-29 15:05
@jonatasfreitasv  You have still not included the version information that I asked for (and was also asked for in the original issue template).

Based on what I have read in the code, the stacktrace you included along with the query, I don't understand how you could get this error on the most recent version of Metabase. It looks like maybe Metabase was upgraded (and sync ran) then the Metabase version was rolled back to an older version. Another possibility is that there are two versions of Metabase running.

**Comment by mbvictoria** [comment] 2019-06-28 19:00
Closing - has been needs more info for over a year, not reported by any other users.

**Closed by mbvictoria** 2019-06-28 19:00 UTC
Labels: Need More Info
