### ISSUE TITLE
Can't create personalized question

### ISSUE THREAD

**Issue by mrouland76** [metabase/metabase#12367] opened 2020-04-21 15:23 UTC
Hello, 
when i want to create a personalized question (question personalisée) in metabase, i click on button "choose your starting datas" and nothing happens... 
![2](https://user-images.githubusercontent.com/64090314/79883503-47ea0780-83f4-11ea-9634-70bc2c6a7c43.png)

I have javascript issues on my browser.
![1](https://user-images.githubusercontent.com/64090314/79883851-af07bc00-83f4-11ea-89a8-6cd2aab62930.png)

i tried with edge, firefox, IE11 and i still have the problem

Everything was fine until i update to the last version.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "fr",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.4.0-177-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.29-0ubuntu0.16.04.1"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-10",
      "tag": "v0.35.2",
      "branch": "release-0.35.x",
      "hash": "f3b2857"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2020-04-21 16:22
Hi @mrouland76 
Which version did you upgrade from?
Are you seeing any errors in the log? Admin > Troubleshooting > Logs
Are you using a proxy (example Cloudflare)? https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html

**Comment by mrouland76** [comment] 2020-05-04 09:02
Hi, i just update from 0.35.2 to 0.35.3 and i still have the problem.
I have 4 errors in my browser :
Each time i click on "Choisissez vos données..." nothing happens and i have errors:

[cid:dee01fb5-2d7a-4f5b-b1be-59c416d59944]

I don't use Proxy. I use it with Docker.

No errors in log.

I checked if it was a problem with ad blocker or other extension in browser but not... I tried with Edge chromium, firefox, IE11 ...

 here's the diag infos:

{   "browser-info": {     "language": "fr-FR",     "platform": "Win32",     "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 Edg/81.0.416.68",     "vendor": "Google Inc."   },   "system-info": {     "file.encoding": "UTF-8",     "java.runtime.name": "OpenJDK Runtime Environment",     "java.runtime.version": "11.0.5+10",     "java.vendor": "AdoptOpenJDK",     "java.vendor.url": "https://adoptopenjdk.net/",     "java.version": "11.0.5",     "java.vm.name": "OpenJDK 64-Bit Server VM",     "java.vm.version": "11.0.5+10",     "os.name": "Linux",     "os.version": "4.4.0-177-generic",     "user.language": "en",     "user.timezone": "GMT"   },   "metabase-info": {     "databases": [       "mysql"     ],     "hosting-env": "unknown",     "application-database": "mysql",     "application-database-details": {       "database": {         "name": "MySQL",         "version": "5.7.29-0ubuntu0.16.04.1"       },       "jdbc-driver": {         "name": "MariaDB Connector/J",         "version": "2.5.1"       }     },     "run-mode": "prod",     "version": {       "date": "2020-04-21",       "tag": "v0.35.3",       "branch": "release-0.35.x",       "hash": "1d424cb"     },     "settings": {       "report-timezone": null     }   } }


Have a nice day.
________________________________
De : flamber <notifications@github.com>
Envoyé : mardi 21 avril 2020 16:27
À : metabase/metabase <metabase@noreply.github.com>
Cc : mrouland76 <mrouland.divers@outlook.com>; Mention <mention@noreply.github.com>
Objet : Re: [metabase/metabase] Can't create personalized question (#12367)


Hi @mrouland76<https://github.com/mrouland76>
Which version did you upgrade from?
Are you seeing any errors in the log? Admin > Troubleshooting > Logs
Are you using a proxy (example Cloudflare)? https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html

**Comment by flamber** [comment] 2020-05-04 09:08
@mrouland76 You cannot attach images on Github, when using email.
I'm guessing that you have turned off Admin > Settings > General > "Enable Nested Queries"
Marking this a duplicate of #12323

**Closed by flamber** 2020-05-04 09:08 UTC
Labels: .Duplicate

**Comment by mrouland76** [comment] 2020-05-04 09:28
Thank you. It works now.
Have a nice day.

________________________________
De : flamber <notifications@github.com>
Envoyé : lundi 4 mai 2020 09:09
À : metabase/metabase <metabase@noreply.github.com>
Cc : mrouland76 <mrouland.divers@outlook.com>; Mention <mention@noreply.github.com>
Objet : Re: [metabase/metabase] Can't create personalized question (#12367)


@mrouland76<https://github.com/mrouland76> You cannot attach images on Github, when using email.
I'm guessing that you have turned off Admin > Settings > General > "Enable Nested Queries"
Marking this a duplicate of #12323<https://github.com/metabase/metabase/issues/12323>
