### ISSUE TITLE
Archiving a collection with pulses in it permanently deletes the pulse(s)

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8005] opened 2018-07-09 23:56 UTC
This is on our stats instance, and I believe on master. If you archive a collection that contains one or more pulses, it permanently deletes the pulse(s), even if you then click Undo on the archive notification toast, or if you go to the archive and un-archive the collection.

This of course would be resolved by making pulses archivable instead of deletable.

**Comment by senior** [comment] 2018-07-11 20:30
Related https://github.com/metabase/metabase/issues/7588

**Comment by camsaul** [comment] 2018-07-16 16:14
Duplicate of #7588. We need to make Pulses archivable in order to change this behavior

**Closed by camsaul** 2018-07-16 16:14 UTC
Labels: Bug, Collections, Pulses
