### ISSUE TITLE
Dashboard filters can not filter joined tables

### ISSUE THREAD

**Issue by Mrmiffo** [metabase/metabase#11409] opened 2019-11-29 07:19 UTC
**Describe the bug**
Fields in joined tables in custom questions are not available as dashboard filters.

**To Reproduce**
1. Create custom question for Sample database
2. From order, join products on productid and review on productid.
3. Summarize on count of product name
4. Save and add to dashboard
5. Create dashboard filter and filter on review rating (not possible as it doesn’t show up in the drop down)

**Expected behavior**
Fields in joined tables should be available in dashboard filters.

**Screenshots**
![Filter on reviews](https://user-images.githubusercontent.com/8545443/69850604-e926c480-127f-11ea-8b5c-5e07049991d3.png)

**Information about your Metabase Installation:**
0.33.6
`
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_144-b01",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_144",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.144-b01",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.6",
      "date": "2019-11-19",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
`
**Severity**
Annoying. The workaround is to create a native SQL query which supports these queries. 

**Additional context**
Also see: https://discourse.metabase.com/t/dashboard-filters-cant-filter-on-joined-fields-for-custom-questions/8175

**Comment by tlrobinson** [comment] 2020-02-04 17:37
This should be resolved by #11827 however your specific reproduction example doesn't work because `Rating` has a `special_type` of `Score` which is not `Category` (and there are no other `Category` fields on `Reviews`).

If you change the type of `Rating` to `Category` I've verified #11827 works.

**Closed** 2020-02-10 19:08 UTC
Labels: Priority:P2, Querying/Notebook, Querying/Parameters & Variables, Reporting/Dashboards, Type:Bug
