### ISSUE TITLE
37 RC-2: Dashboard cards layering on top of each other

### ISSUE THREAD

**Issue by jeff-bruemmer** [metabase/metabase#13498] opened 2020-10-15 18:59 UTC
**Describe the bug**
While using 37RC-2, dashboard cards layer on top of each other. See screenshot below.

**Logs**
Console logs:
```
app-main.bundle.js?53eca31c7f9d7c447a8c:5 Error getting setting graph.x_axis._is_timeseries TypeError: Cannot read property 'cols' of undefined
    at Object.getDefault (app-main.bundle.js?53eca31c7f9d7c447a8c:5)
    at g (app-main.bundle.js?53eca31c7f9d7c447a8c:5)
    at t.getComputedSettings (app-main.bundle.js?53eca31c7f9d7c447a8c:5)
    at h (app-main.bundle.js?53eca31c7f9d7c447a8c:5)
    at t.value (app-main.bundle.js?53eca31c7f9d7c447a8c:5)
    at t.value (app-main.bundle.js?53eca31c7f9d7c447a8c:5)
    at c.performInitialMount (vendor.bundle.js?53eca31c7f9d7c447a8c:1)
    at c.mountComponent (vendor.bundle.js?53eca31c7f9d7c447a8c:1)
    at Object.mountComponent (vendor.bundle.js?53eca31c7f9d7c447a8c:1)
    at c.performInitialMount (vendor.bundle.js?53eca31c7f9d7c447a8c:1)
g @ app-main.bundle.js?53eca31c7f9d7c447a8c:5
t.getComputedSettings @ app-main.bundle.js?53eca31c7f9d7c447a8c:5
h @ app-main.bundle.js?53eca31c7f9d7c447a8c:5
value @ app-main.bundle.js?53eca31c7f9d7c447a8c:5
value @ app-main.bundle.js?53eca31c7f9d7c447a8c:5
performInitialMount @ vendor.bundle.js?53eca31c7f9d7c447a8c:1
mountComponent @ vendor.bundle.js?53eca31c7f9d7c447a8c:1
mountComponent @ vendor.bundle.js?53eca31c7f9d7c447a8c:1
performInitialMount @ vendor.bundle.js?53eca31c7f9d7c447a8c:1
mountComponent @ vendor.bundle.js?53eca31c7f9d7c447a8c:1
mountComponent @ vendor.bundle.js?53eca31c7f9d7c447a8c:1
performInitialMount @ vendor.bundle.js?53eca31c7f9d7c447a8c:1
mountComponent @ vendor.bundle.js?53eca31c7f9d7c447a8c:1
mountComponent @ vendor.bundle.js?53eca31c7f9d7c447a8c:1
performInitialMount @ vendor.bundle.js?53eca31c7f9d7c447a8c:1
mountComponent @ vendor.bundle.js?53eca31c7f9d7c447a8c:1
mountComponent @ vendor.bundle.js?53eca31c7f9d7c447a8c:1
[truncated]
```
**To Reproduce**
Unable to reproduce the error. Noticed it when returning to a dashboard, so I don't know the sequence of steps that caused the error, and couldn't reproduce it in another dashboard.

The error occurred with two cards of the same question, each with a separate click behavior: one action menu, one to a dashboard. I don't remember adding the question to the dashboard twice, so maybe setting a different click behavior created a duplicate card with a different click behavior? 

Regardless, cards should never layer.

**Expected behavior**
Cards on a dashboard should not be able to layer.

**Screenshots**
<img width="846" alt="layered-cards" src="https://user-images.githubusercontent.com/17343328/96172435-4e58c800-0edb-11eb-989e-d230bd6b4731.png">

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Mac OS X",
    "os.version": "10.15.7",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "",
      "tag": "v0.37.0-rc2",
      "branch": "",
      "hash": ""
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Severe. If dashboard cards can get into a state where they can layer, that's a problem. 

**Additional context**
No errors in the server logs.

**Comment by mazameli** [comment] 2020-10-15 19:30
Was this a dashboard you'd created a while ago, i.e. before trying out RC-2 for the first time? Or one that you newly created?

**Comment by jeff-bruemmer** [comment] 2020-10-15 19:34
I believe I created the dashboard in 37 RC-2.

**Comment by rlotun** [comment] 2020-10-21 04:57
Have you managed to reproduce this by any chance?

**Comment by jeff-bruemmer** [comment] 2020-10-21 13:56
No. I saw it once. The layered cards survived multiple dashboard page refreshes. But once I edited the dashboard, and pulled apart the cards, I could not get them to layer again. And I have yet to see other layering cards.

**Comment by flamber** [comment] 2020-10-23 16:40
Closing this, since I haven't been able to reproduce either - think it might have been one of the many other bugs in RC2.
If someone knows how to reproduce this, then please comment.
And if you get in the bad state with overlapped cards, then please get all rows from application database table `report_dashboard_card` related to the dashboard ID.

**Closed by flamber** 2020-10-23 16:40 UTC
Labels: .Unable to Reproduce, Type:Bug
