### ISSUE TITLE
API/Export support for basic card/question visualisation settings

### ISSUE THREAD

**Issue by PeteCoward** [metabase/metabase#22572] opened 2022-05-10 03:31 UTC
**Is your feature request related to a problem? Please describe.**
We have a metabase instance used by multiple locales. 
We either create one base question, and set visualisation settings in multiple dashboards to apply translations for table column names, or we create multiple questions and set visualisations in those questions to apply translations for table column headers.
This works great for us in dashboards, and embeds.

The problem is that clicking export inside a question with visualisation settings defined, or from an embedded dashboard with visualisation settings applied to the question card, does not respect those visualisation settings.
The api documentation for `api/card/:card_id/query/:export-format` also does not describe/allow the passing of visualisation settings.

**Describe the solution you'd like**
I would like clicking export to csv/xlsx/json to match the column headers seen in the question or the dashboard.
I would like the ability to call the existing api, and map the column headers to translations

**Describe alternatives you've considered**
We've been using SQL questions, but this is OK to develop with but a pain to maintain.
We will be creating duplicate database views to support each language so that field names and column headers can be applied from our codebase

**How important is this feature to you?**
We have a solution described above we can use for now, but this involves throwing away some of the value metabase brings in export building.

**Additional context**
Simple reproduction is to create a one column table question from the sample database, change the column title in the UI visualisation settings, save and export as csv.

**Comment by flamber** [comment] 2022-05-10 07:39
Duplicate of #17753

**Closed by flamber** 2022-05-10 07:39 UTC
Labels: Type:New Feature, .Needs Triage
