### ISSUE TITLE
Ordering labels in X-axis 

### ISSUE THREAD

**Issue by juanrcanop** [metabase/metabase#29925] opened 2023-04-10 12:17 UTC
**Is your feature request related to a problem? Please describe.**
I have labels that I want to order in the X-axis but I can't do it properly because they are strings. Example: 5km, 10km, 25km ... 
I can't show them in the right order unless I write "00" before (see screenshot) so that it's ordered asc. It looks quite awful.

**Describe the solution you'd like**
Possibility to select the order of the labels of X-axis

<img width="969" alt="image" src="https://user-images.githubusercontent.com/85160827/230899746-9bdd7379-1489-47ca-9ad6-6d6b2022ddea.png">

**How important is this feature to you?**
Very important as it's client facing.

**Additional context**

**Comment by paoliniluis** [comment] 2023-04-15 19:55
this is a duplicate of https://github.com/metabase/metabase/issues/19346

**Closed by paoliniluis** 2023-04-15 19:55 UTC
Labels: Type:New Feature, .Needs Triage
