### ISSUE TITLE
Dashboards with mixed datasources: Dashboard filter is populated with values from only one datasource

### ISSUE THREAD

**Issue by hagen** [metabase/metabase#7741] opened 2018-05-28 04:14 UTC
- Your browser and the version: Chrome 67
- Your databases: MySQL compat.
- Metabase version: 29.0
- Metabase hosting environment: EB
- Metabase internal database: PG

# Repeat
1. Create two datasources, D1 and D2. These two databases share a common table, _Table_
2. Create two questions - they can be the same output, but Q1 uses _Table_ from D1, and Q2 uses _Table_ from D2
3. Place the questions on a dashboard and add a Category filter. Wire the filter to the same field in both questions.
4. The filter will alternate between showing values from _Table_ in D1 and _Table_ in D2. But not combine the values from both D1 and D2.

For example, D1 and D2 each have a table _Locations_ with a field _City_.
D1 has Australian locations and D2 has New Zealand locations.
I create a Question on D1 which is a raw listing of entries in _Location_, and the same for D2.
I place both Questions on a Dashboard, add a filter wired to _City_ on both.
On periodic reloads, the City Filter will show only cities in Australia or only cities in New Zealand.

Looking in the console of Chrome, I can see that on loading the dashboard, the filter values for City are fetched _only_ for the City field of the second Card. And these are what's shown in the Filter drop-down.
If I remove the second card, the filter values come from the first card.

Other dashboard-with-multi-datasource issue: #7633

**Comment by salsakran** [comment] 2018-07-03 00:30
the expectation of the current version of the dashboard parameter mapping to a table column is that the same(ish) underying column is used by all the charts.

**Comment by hagen** [comment] 2018-07-03 00:36
And that doesn't translate across databases/data sources?
i.e. database 1, table `fruit`, column `name` (text, category) - question is aggregation count() on column `name`
database 2, table `fruit`, column `name` (text, category) - question is aggregation count() on column `name`
If both questions are placed in a dashboard (card 1 and card 2), and a filter on `name` is used, wired to `name` in both cards, the filter shows only the fruit for one database/data source. Is that expected?

**Comment by salsakran** [comment] 2018-07-03 00:41
So I'm pretty sure what we do under the hood is grab the mapped column of the first card in the dashboard and use that to power the list of valid values. 

Will we do something more sophisticated in the future? Almost certainly, but that's how it works now.

**Comment by hagen** [comment] 2018-07-03 01:06
Nawww, okay. It would appear that's what happens. It's pretty much always the values from just one of the cards.
Can I get a Feature Request label?! 🙏

**Comment by flamber** [comment] 2019-02-25 19:27
This looks like a duplicate of #7168 - go and upvote by clicking :+1:

**Comment by flamber** [comment] 2020-05-28 16:26
Fixed in 0.35.0

**Closed by flamber** 2020-05-28 16:26 UTC
Labels: .Limitation
