### ISSUE TITLE
Insufficient memory error

### ISSUE THREAD

**Issue by baradhili** [metabase/metabase#7084] opened 2018-03-07 14:00 UTC
Hi all,
this is probably a silly setting error, but when I run metabase ' java -jar metabase.jar' I get
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000f9f86000, 47104000, 0) failed; error='Cannot allocate memory' (errno=12)

There is insufficient memory for the Java Runtime Environment to continue.
Native memory allocation (mmap) failed to map 47104000 bytes for committing reserved memory.
An error report file with more information is saved as:
/opt/metabase/hs_err_pid16544.log

BTW it wants to allocate 47GB of memory.. which can't be right.. Digging through the error log it seems to be trying to recompile the jar...

Java version is current
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

Metabase version also current (downloaded today)

Running on Ubuntu 16.04 against mariadb

Thanks

Bret

**Comment by senior** [comment] 2018-03-07 14:56
This is not a bug in Metabase but a problem with your setup. When you use `java -jar metabase.jar`, it will look at the total available memory on your system and attempt to size it up appropriately. Based on what you posted here, it's trying to allocate 47MB (not enough to run Metabase) and the system won't allow even that much memory. I'd guess that you have only allocated 100MB of memory total to that VM. By default, the JVM will attempt to allocate a maximum of half of the available system memory, up to 192 MB. If more memory is available, it will default to 1/4 of the system memory up to 1GB (docs on this default are [here](https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/parallel.html#default_heap_size)).

I'm going to close this as it's not really a Metabase bug. To get more help on configuring your Metabase instance, I'd suggest starting a thread over in our [support forum](http://discourse.metabase.com/).

**Closed by senior** 2018-03-07 14:56 UTC
