### ISSUE TITLE
MySQL TINYINT(1) columns are always interpreted as booleans

### ISSUE THREAD

**Issue by hugocar** [metabase/metabase#3506] opened 2016-10-11 15:54 UTC
> ### Bugs
> 
> If you're filing an issue about a bug please include as much information
> as you can including the following.

On a table "user" there is a colonne "gender" 
the value is 1 for men and 2 for women (I disapprove of this data model but this not the issue here)

Metabase sees it as a boolean : 

in results : 
<img width="1198" alt="capture d ecran 2016-10-11 a 5 35 10 pm" src="https://cloud.githubusercontent.com/assets/19691106/19277397/db5cf382-8fd9-11e6-84a4-06de6be2c1fd.png">

in filters : 
<img width="322" alt="capture d ecran 2016-10-11 a 5 41 30 pm" src="https://cloud.githubusercontent.com/assets/19691106/19277437/fd04468e-8fd9-11e6-8044-d41fa226257f.png">

despite being provided a data model form the admin panel : 

<img width="906" alt="capture d ecran 2016-10-11 a 5 42 15 pm" src="https://cloud.githubusercontent.com/assets/19691106/19277466/1483c122-8fda-11e6-945d-817dcc39a9af.png">

> - Your browser and the version: Firefox up to date
> - Your operating system: MacOS
> - Your databases: MySQL
> - Metabase version: (e.x. 0.19.3)
> - Metabase hosting environment: Linux Java
> - Metabase internal database:MySQL
> - _Repeatable steps to reproduce the issue_

To reproduce you would need to create a table with a column filled only with 1 and 2 
CREATE TABLE `user` (
  `gender` tinyint(1) NOT NULL DEFAULT '1',
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"

> ## Thanks for being part of the Metabase project!

Thank you guys

**Comment by hugocar** [comment] 2016-10-11 16:32
I feel like it is totally OK for Metabase to assume (a tinyint-typed column with a cardinality of 2) can be treated like a boolean.

But choosing "Number" in the Admin Data Model Panel should force Metabase to display integers instead of boolean.

**Comment by tlrobinson** [comment] 2016-11-14 20:49
@camsaul This looks like a backend issue. While the MySQL docs do say [`BOOL, BOOLEAN [...] are synonyms for TINYINT(1)`](https://dev.mysql.com/doc/refman/5.5/en/numeric-type-overview.html), `TINYINT(1)` is one byte, not one bit, so it can contain more than 2 values. Basically a `BOOL` is a `TINYINT(1)`, but a `TINYINT(1)` shouldn't necessarily be considered a boolean.

This is definitely unexpected:

```
mysql> CREATE TABLE user1 (gender tinyint(1) NOT NULL DEFAULT '1') ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
Query OK, 0 rows affected (0.02 sec)

mysql> insert into user1 values (1), (2), (3);
Query OK, 3 rows affected (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> select * from user1;
+--------+
| gender |
+--------+
|      1 |
|      2 |
|      3 |
+--------+
3 rows in set (0.00 sec)
```

![screen shot 2016-11-14 at 12 38 46 pm](https://cloud.githubusercontent.com/assets/18193/20282161/6d7495f6-aa68-11e6-8d25-a4836fe2e406.png)

```
   "data" : {
      "rows" : [
         [true],
         [true],
         [true]
      ],
      "cols" : [
         {
            "fk_field_id" : null,
            "description" : null,
            "table_id" : 342,
            "base_type" : "type/Boolean",
            "target" : null,
            "visibility_type" : "normal",
            "id" : 23654,
            "name" : "gender",
            "extra_info" : {},
            "schema_name" : null,
            "display_name" : "Gender",
            "source" : "fields",
            "special_type" : "type/Category"
         }
      ]
    }
```

**Comment by camsaul** [comment] 2016-11-14 20:52
@tlrobinson I'm not sure why `TINYINT(1)` is getting marked as a `type/Boolean`. It should be getting marked as a `type/Integer`. 

I'll look into this.

**Comment by tlrobinson** [comment] 2016-11-14 20:53
Related to #3454

**Comment by camsaul** [comment] 2016-11-14 20:54
This isn't really related to #3454. This is a metadata bug and that's a feature request.

**Comment by camsaul** [comment] 2016-11-16 00:02
@hugocar why did you use `TINYINT(1)` for an enum? `TINYINT` is always one byte; `(1)` is just the *display width* (i.e., only show 1 digit in the results). Seems to me like `TINYINT` width no display width would make more sense.

Since `BOOL`/`BOOLEAN` are just synonyms for `TINYINT(1)` it's a schema design that I could see causing lots of confusion.

**Comment by camsaul** [comment] 2016-11-16 00:12
It seems that `TINYINT(1)` meaning `BOOL` is such a common pattern that the JDBC driver just assumes that it's a boolean and reports it as such when we fetch metadata I'm not sure what we can do here; this is the behavior of the official MySQL JDBC library and not Metabase itself.

Just using `TINYINT`, however, works fine.

**Comment by camsaul** [comment] 2016-11-16 00:14
Looks like in the past someone actually opened a bug for the MySQL JDBC driver because it *didn't* automatically treat `TINYINT(1)` as a boolean:

http://bugs.mysql.com/bug.php?id=16854

**Comment by camsaul** [comment] 2016-11-16 00:21
Yup, confirmed that this is the expected behavior for the JDBC driver:

```
tinyInt1isBit

Should the driver treat the datatype TINYINT(1) as the BIT type (because the server silently converts BIT -> TINYINT(1) when creating tables)?

Default: true

Since version: 3.0.16
```

http://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html#connector-j-reference-set-config

**Comment by camsaul** [comment] 2016-11-16 00:49
@hugocar, I don't want to second-guess the default behavior of the MySQL JDBC driver lest we break things for other people. Luckily you can toggle this behavior by including a parameter in the JDBC connection string.

Metabase generates this string automatically, and in PR #3765 I made some minor tweaks so it will handle custom params correctly.

When Metabase 0.21 ships, appending `?tinyInt1isBit=false` to your database name will pass the parameter on to the JDBC driver, which I have confirmed forces the behavior you want.

So where you have:

![screen shot 2016-11-15 at 4 46 10 pm](https://cloud.githubusercontent.com/assets/1455846/20330350/07bbbca8-ab53-11e6-882c-59146ac2604c.png)

change it to:

![screen shot 2016-11-15 at 4 46 24 pm](https://cloud.githubusercontent.com/assets/1455846/20330353/1078a02c-ab53-11e6-98bf-2135c8c574e7.png)

*after* 0.21.0 ships and you've upgraded.


In the future, I'd recommend against using `TINYINT(1)` for anything besides a boolean, since it's such a standard pattern they made it the default for the JDBC driver. You can always use plain `TINYINT`.

**Comment by salsakran** [comment] 2016-11-16 00:52
I think separate from the driver connection, I agree with @hugocar which is that if I mark something as a `number`, regardless of what the driver returns it should be a `number`.  This is a bit annoying in that in clojure `(int true)` doesn't behave in a C-like manner.

**Comment by camsaul** [comment] 2016-11-16 00:53
Sorry @hugocar, please disregard that last comment, we've decided to go with a different approach to this problem.

I'll let you know when we revisit this issue. In the meantime, it might make sense to just use `TINYINT` instead of `TINYINT(1)`.

**Comment by camsaul** [comment] 2016-11-16 00:55
@salsakran the problem is that it's the default behavior of the MySQL JDBC driver to automatically treat `TINYINT(1)` columns as booleans unless you tell it not to. So there's no way we can know that it's actually a `TINYINT` column.

FWIW `TINYINT(1) == BOOLEAN` is a very standard MySQL convention which I assume is why they made that the default behavior.

**Comment by salsakran** [comment] 2016-11-16 00:57
yup, that all makes sense. My specific statement was that once it comes back from the jdbc driver as a boolean, if I set the type to "number" I'm asking Metabase to treat it as a number. In that case, we should treat it as a number =)

This is similar to the utc timestamp situation where the JDBC driver returns an integer for that column, and we cast/interpret it as a datetime.

This specific bug is an edge case of that general desired behaviour.

**Comment by camsaul** [comment] 2016-11-16 01:08
@salsakran if someone changed the type of a boolean column to `Number`, what would you expect us to return? `0` for `false` and `1` for `true`?

Keep in mind we never see the actual numeric values of these columns. The JDBC driver gives us `false` for zero and `true` for everything else. So if the actual underlying value is something else, like `2` or `3`, we'd be losing information there. There is no way to tell what number was actually there when all we see is `true`.

**Comment by tlrobinson** [comment] 2016-11-16 01:12
Given a `tinyint(1)` can store more than 2 values I think the ideal thing to do would be to *always* set `?tinyInt1isBit=false`, then when syncing we should try to detect whether any numeric columns are being used as booleans and mark them as such.

**Comment by camsaul** [comment] 2016-11-16 01:17
@tlrobinson since `TINYINT(1)` is the canonical way of of storing booleans in MySQL I'm very weary of second-guessing the MySQL devs to change a setting like that. 

I think detecting whether a numeric column is intended as a boolean column or something else is much easier said than done. If a table has millions of rows it's not feasible to scan the entire thing and it is entirely possible that we won't get the complete set of values used if we don't scan the entire table. While it would fix the issue for one person it could potentially break things for everyone else.

**Comment by salsakran** [comment] 2016-11-16 01:20
I think the issue is that while all Booleans are `TINYINT(1)`, there exist a small number of cases where a `TINYINT(1)` isn't a Boolean. I agree we should just swim with the stream of the MySQL driver here, and view a TI1 being a non-boolean as a special case we handle in some way.

**Comment by camsaul** [comment] 2016-11-16 01:23
I think the answers here are:

1.  We probably shouldn't use TINYINT(1) for non-boolean values
2.  We should let people specify arbitrary JDBC connection string params if they need special-case behavior for weird situations like this one

There are lots of other options available and somebody may or may not want to specify them, but they're presumably there for a reason.

**Comment by tlrobinson** [comment] 2016-11-16 01:24
@camsaul It sounds like this is a JDBC behavior. If I do `select my_tiny_int_1_column ...` it does shows all values, not booleans. Ditty for the node.js driver.

Just because the client we happen to use makes an assumption about how you should use a database doesn't mean we automatically should too. We have to work with every database, not just the ones people use with JDBC.

**Comment by salsakran** [comment] 2016-11-16 01:26
👍  on arbitrary JDBC connection strings.

I'll add a 
3. Allow users to coerce data into other types (eg a string -> int, int -> utc timestamp, bool -> int, etc)

**Comment by camsaul** [comment] 2016-11-16 01:26
@tlrobinson this is a behavior of the MySQL JDBC driver. So it was put in there by MySQL devs.

I'm not surprised the console doesn't display things as boolean values, because MySQL doesn't have a native boolean type.

**Comment by salsakran** [comment] 2016-11-16 01:27
and fwiw, I think this is a situation where MySQL is doing dumb things for historical reasons that we need to work around as opposed to them being especially insightful into the nature of boolean reality.

**Comment by camsaul** [comment] 2016-11-16 01:29
@salsakran like I mentioned above I don't think being able to coerce boolean to int would solve anything here. We'd still be losing all the extra values.

**Comment by tlrobinson** [comment] 2016-11-16 01:30
@camsaul Not if you set `?tinyInt1isBit=false`, right?

**Comment by camsaul** [comment] 2016-11-16 01:30
No then it's just an int, not a boolean

**Comment by salsakran** [comment] 2016-11-16 01:32
and to be honest, I think situations like this should be "fixed" via a way to remap values in a dimension ala #3454

There are lots of cases where the literal value of a column isn't what you want displayed.

**Comment by camsaul** [comment] 2016-11-16 21:13
Implemented by #3765

**Closed by camsaul** 2016-11-16 21:13 UTC
Labels: Bug, Database/MySQL, Metadata/Sync

**Comment by camsaul** [comment] 2016-11-16 21:17
@hugocar, we ended up adding a way to specify additional connection options to the MySQL driver. 

In the upcoming 0.21.0 release you'll be able to specify additional options in the database details page in the admin panel:

![screen shot 2016-11-16 at 1 15 08 pm](https://cloud.githubusercontent.com/assets/1455846/20366161/bcb30fd4-abfe-11e6-85d4-33819e6090ad.png)

If you add `tinyInt1IsBit=false` there, save, and hit "Sync", you'll see the `TINYINT(1)` columns treated as numbers instead of booleans.

**Comment by hugocar** [comment] 2016-11-28 08:46
@camsaul 
Sorry for my silence, I was away.
Thanks you for #3765 and all the reflexion and work.

>  why did you use TINYINT(1) for an enum? TINYINT is always one byte;
I agree this is not optimal, but as most databases I work with it wasn't design by developers specialized in data.

**Comment by robsonpeixoto** [comment] 2017-09-07 01:34
I added the parameter `tinyInt1IsBit=false` but metabase still interpreting as boolean.
Any tip?
I'm using MySQL 5.6.31.

**Comment by robsonpeixoto** [comment] 2017-09-10 13:02
Was a typo. `tinyInt1isBit=false` is working
