### ISSUE TITLE
Application throws me out and redirects to login page

### ISSUE THREAD

**Issue by abalfazl9776** [metabase/metabase#11594] opened 2019-12-26 07:01 UTC
When I change the language multiple times the application throws me out and redirects to login page and somehow I can't login again with my user pass, infact the sign in button does not work.

I'm using the latest commit [https://github.com/metabase/metabase/commit/5996deb09464ddb814ba42cf3a76ce63237e6957](url)
and I'm working in development mode with h2 database.

**Logs**
12-26 10:08:55 DEBUG middleware.log :: GET /api/setting 200 1.1 ms (0 DB calls) (49 total active threads) Queries in flight: 0
12-26 10:08:55 ERROR util.i18n :: Unable to translate string 'User lookup filter, the placeholder '{login}' will be replaced by the user supplied login.'
java.lang.IllegalArgumentException: can't parse argument number: login
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1429)
	at java.text.MessageFormat.applyPattern(MessageFormat.java:479)
	at java.text.MessageFormat.<init>(MessageFormat.java:380)
	at puppetlabs.i18n.core$fmt.invoke(core.clj:250)
	at puppetlabs.i18n.core$translate.doInvoke(core.clj:257)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:671)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.util.i18n$translate.invokeStatic(i18n.clj:29)
	at metabase.util.i18n$translate.invoke(i18n.clj:22)
	at clojure.core$partial$fn__5839.invoke(core.clj:2626)
	at metabase.util.i18n.UserLocalizedString.toString(i18n.clj:47)
	at clojure.core$str.invokeStatic(core.clj:553)
	at clojure.core$str.invoke(core.clj:544)
	at metabase.models.setting$user_facing_info.invokeStatic(setting.clj:606)
	at metabase.models.setting$user_facing_info.doInvoke(setting.clj:599)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at medley.core$mapply.invokeStatic(core.cljc:210)
	at medley.core$mapply.doInvoke(core.cljc:203)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at metabase.models.setting$all$iter__27712__27716$fn__27717.invoke(setting.clj:618)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:713)
	at clojure.core$next__5386.invokeStatic(core.clj:64)
	at clojure.core$next__5386.invoke(core.clj:64)
	at cheshire.generate$generate.invokeStatic(generate.clj:130)
	at cheshire.generate$generate.invoke(generate.clj:116)
	at cheshire.core$generate_stream.invokeStatic(core.clj:106)
	at cheshire.core$generate_stream.invoke(core.clj:81)
	at metabase.middleware.json$streamed_json_response$fn__78132.invoke(json.clj:80)
	at ring.util.io$piped_input_stream$fn__213.invoke(io.clj:28)
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NumberFormatException: For input string: "login"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1427)
	... 44 more
12-26 10:22:43 DEBUG middleware.log :: PUT /api/setting/site-locale 200 11,8 ms (4 DB calls) (47 total active threads) Queries in flight: 0
12-26 10:22:43 DEBUG middleware.log :: GET /api/session/properties 200 24,6 ms (1 DB calls) (47 total active threads) Queries in flight: 0
12-26 10:22:43 DEBUG middleware.log :: GET /api/setting 200 1,1 ms (0 DB calls) (49 total active threads) Queries in flight: 0
12-26 10:23:07 DEBUG middleware.log :: PUT /api/setting/admin-email 200 7,1 ms (4 DB calls) (49 total active threads) Queries in flight: 0
12-26 10:23:07 DEBUG middleware.log :: GET /api/session/properties 200 6,1 ms (1 DB calls) (49 total active threads) Queries in flight: 0
12-26 10:23:07 DEBUG middleware.log :: GET /api/setting 200 832,5 µs (0 DB calls) (49 total active threads) Queries in flight: 0
12-26 10:23:13 DEBUG middleware.log :: PUT /api/setting/site-locale 200 7,3 ms (4 DB calls) (49 total active threads) Queries in flight: 0
12-26 10:23:13 DEBUG middleware.log :: GET /api/session/properties 200 26,7 ms (1 DB calls) (49 total active threads) Queries in flight: 0
12-26 10:23:13 DEBUG middleware.log :: GET /api/setting 200 921,6 µs (0 DB calls) (49 total active threads) Queries in flight: 0
12-26 10:23:21 DEBUG middleware.log :: PUT /api/setting/site-locale 200 9,8 ms (4 DB calls) (49 total active threads) Queries in flight: 0
12-26 10:23:21 DEBUG middleware.log :: GET /api/session/properties 200 26,0 ms (1 DB calls) (49 total active threads) Queries in flight: 0
12-26 10:23:21 DEBUG middleware.log :: GET /api/setting 401 277,3 µs (0 DB calls) 
"Unauthenticated"

12-26 10:23:25 DEBUG middleware.log :: POST /api/session 400 151,8 ms (1 DB calls) 
{:value
 [:password
  #metabase.models.user.UserInstance{:ıd 1,
                                     :password_salt "2cf16051-5f61-4fd8-919d-5e00d1d35178",
                                     :password "$2a$10$i3qddUFkscN4wH63y/WokeDkN/wmLo6kIh7n0.aPi0.Vt3Cdcsv8S",
                                     :last_logın (t/local-date-time "2019-12-26T09:43:55.690")}],
 :error [nil (named {:id missing-required-key, :last_login missing-required-key} user)]}

12-26 10:23:28 DEBUG middleware.log :: POST /api/session 400 104,1 ms (1 DB calls) 
{:value
 [:password
  #metabase.models.user.UserInstance{:ıd 1,
                                     :password_salt "2cf16051-5f61-4fd8-919d-5e00d1d35178",
                                     :password "$2a$10$i3qddUFkscN4wH63y/WokeDkN/wmLo6kIh7n0.aPi0.Vt3Cdcsv8S",
                                     :last_logın (t/local-date-time "2019-12-26T09:43:55.690")}],
 :error [nil (named {:id missing-required-key, :last_login missing-required-key} user)]}

**Comment by flamber** [comment] 2019-12-26 14:40
Hi @abalfazl9776 
What do you mean by "change the language multiple times"? The browser's content language, or your OS language, ...? And which languages are you switching between?
How do you reproduce the issue?

How are you running Metabase, `lein ring server(-headless)`?
Can you post the output of the following:
```
# OS and version
 sed -nE 's/^PRETTY_NAME="([^"]+)"$/\1/p' /etc/os-release
# Git branch and commit
 echo `git status | head -1 && git log -1 --format="commit %H"`
# Java version and architecture
 java -version
# Java variable configuration
 echo $JAVA_HOME
# Java path configuration
 echo $PATH | grep --color=never -oe "/usr/lib/jvm/[^:]*"
# Lein version
 lein --version
# NodeJS version
 nodejs --version
# Yarn version
 yarn --version
```

**Comment by abalfazl9776** [comment] 2019-12-30 11:11
Thanks for answering...

Not OS or browser language... I mean changing the language in Admin>General>Language settings.
It does not matter which language to switch  to, if I change the language multiple times from this section the applications logs me out!

It does not matter how to run the application, I tried using jar file or running "`lein ring server`", the result is same.

# OS and version
ubuntu 18.04.3 lts
# Git branch and commit
master - 5996deb09464ddb814ba42cf3a76ce63237e6957
# Java version and architecture
openjdk version "1.8.0_232"
# Java variable configuration
/usr/lib/jvm/java-8-openjdk-amd64

# Lein version
Warning: implicit hook found: lein-environ.plugin/hooks 
Hooks are deprecated and will be removed in a future version.
Leiningen 2.9.1 on Java 1.8.0_232 OpenJDK 64-Bit Server VM

# NodeJS version
 v8.10.0

# Yarn version
 1.19.2

**Comment by flamber** [comment] 2019-12-30 17:26
@abalfazl9776 I cannot reproduce on latest `master`. Try 13352156f8a433d8b35727b9883c48f40de0f479 (0.34.0) or 7ee71934a7104d6ffd21dfd1643929d1e99d2822 (0.33.7.3)
Have you ever build the translation files? `./bin/build translations`
But I'm noticing that it changes some of the description texts, when changing the language, which it shouldn't, since that's not handled by that setting, but by the browser language (until #8384).
So it seems like that might have something to do with it. (I just changed from English to Chinese)
![image](https://user-images.githubusercontent.com/1447303/71592621-8c286380-2af6-11ea-98bb-e5d78b18e1b8.png)

**Comment by flamber** [comment] 2020-04-06 13:18
Closing this, since I haven't been able to reproduce. Opened #12276 for settings being applied to interface, when it shouldn't.

**Closed by flamber** 2020-04-06 13:18 UTC
Labels: .Unable to Reproduce, Administration/, Customization/i18n, Priority:P3, Type:Bug
