### ISSUE TITLE
Time datatype displayed in localtime

### ISSUE THREAD

**Issue by jens-totemic** [metabase/metabase#18955] opened 2021-11-12 03:52 UTC
When displaying results from a postgres table which has a column of datatype `time`, the values of that column are seemingly converted using the browsers timezone. This should not happen. The expected behavior is that the time is not converted.

In order to reproduce, run this in the Metabase SQL query editor (might require to connect to a postgres database for it to work):
```
WITH test (id,t) AS (VALUES
	(1, '13:00:56'::time),
	(2, '15:11:43'::time),
	(3, '17:22:35'::time),
	(4, '19:33:22'::time),
	(5, '21:44:19'::time),
	(6, '23:55:02'::time)
)
SELECT *
FROM test
```

Below is the wrong output in metabase. Notice how the times are adjusted by 8 hours (timezone of the browser is PST). In addition also the seconds are omitted.
```
1	9:00 PM
2	11:11 PM
3	1:22 AM
4	3:33 AM
5	5:44 AM
6	7:55 AM
```

This is the expected/correct output when directly running this through postgres (adjusting to 12/24 hours is not the issue here):
```
1	13:00:56
2	15:11:43
3	17:22:35
4	19:33:22
5	21:44:19
6	23:55:02
```

Another quick way to reproduce this in Metabase through H2 or Postgres database is this:

```
SELECT '23:45:23'::time
```
Wrong output:
```
7:45 AM
```

Expected correct output in sql shell such as pgAdmin
```
23:45:23
```
or
```
11:45:23 PM
```

System info:
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "5.4.95-42.163.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.2 (Ubuntu 13.2-1.pgdg18.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-11-09",
      "tag": "v0.41.2",
      "branch": "release-x.41.x",
      "hash": "ad599fd"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2021-11-12 11:20
Duplicate of #15876
As for seconds not being shown, that's by default and they can be enabled in the visualization Settings.

**Closed by flamber** 2021-11-12 11:20 UTC
Labels: Type:Bug, .Needs Triage

**Comment by jens-totemic** [comment] 2021-11-12 17:31
Thanks @flamber. I tried to show the seconds and I assume what is meant is to click on the column header for `t` and select "Column formatting". Any setting I made there is being ignored. Do you want me to file a separate bug for that?

Based on the info in #15876  I was able to build a workaround for the time conversion by simply adding 1 millisecond. Sharing here, maybe it's useful for someone else:
```
WITH test (id,t) AS (VALUES
	(1, '13:00:56'::time),
	(2, '15:11:43'::time),
	(3, '17:22:35'::time),
	(4, '19:33:22'::time),
	(5, '21:44:19'::time),
	(6, '23:55:02'::time)
)
SELECT id, (t + '.001')::time
FROM test
```

**Comment by flamber** [comment] 2021-11-12 17:35
@jens-totemic Sorry, I had forgotten about #11398 - frustrating
