### ISSUE TITLE
Charts in email dashboard subscriptions have y-axis auto split even if the option is off in questions

### ISSUE THREAD

**Issue by DrVolodya** [metabase/metabase#25743] opened 2022-10-02 22:53 UTC
**Describe the bug**
Charts when included in email subscriptions are formatted differently from what they are set up in questions. y-axis auto-split is used and date format is the default, not the one set by user. 

**To Reproduce**
1. Create a chart with more than one line having somewhat different values in the lines, say one with max y-value of 10 and another with max y-axis at 40
2. Save as a new question and add it to a dashboard
3. Click the subscription button and set up an email subscription to this dashboard
4. See error when email arrives

**Expected behavior**
When attaching chart images, they must be created with exact same settings as the user intended

**Screenshots**

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8-post-Ubuntu-0ubuntu120.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8-post-Ubuntu-0ubuntu120.04",
    "os.name": "Linux",
    "os.version": "5.15.0-48-generic",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.30-0ubuntu0.20.04.2"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-09-02",
      "tag": "v0.44.3",
      "branch": "release-x.44.x",
      "hash": "7d50282"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
High. 
Renders email subscription useless as is.

**Comment by flamber** [comment] 2022-10-03 07:41
Duplicate of #20559

**Closed by flamber** 2022-10-03 07:41 UTC
Labels: Type:Bug, .Needs Triage
