### ISSUE TITLE
Statistics are displayed in decimal places， could you display in percentage

### ISSUE THREAD

**Issue by matthewxuda** [metabase/metabase#19617] opened 2022-01-11 02:45 UTC
Statistics are displayed in decimal places， could you display in percentage
use chrome 97.0.4692.71

![image](https://user-images.githubusercontent.com/5927005/148872159-5ac63301-2df2-466a-8274-f13e2d0ff76e.png)

![image](https://user-images.githubusercontent.com/5927005/148872615-0dba8935-d288-412d-9467-eddc01553d4f.png)

![image](https://user-images.githubusercontent.com/5927005/148872658-b5000931-982d-42d7-a471-3cb8a8c9b0d9.png)

**Comment by flamber** [comment] 2022-01-11 09:07
Duplicate of #13778/#12152

**Closed by flamber** 2022-01-11 09:07 UTC
