### ISSUE TITLE
BigQuery StandardSQL functions raising error

### ISSUE THREAD

**Issue by gilhs** [metabase/metabase#3999] opened 2016-12-23 08:21 UTC
(Metabase version: 0.21.1)

As discussed in [http://discourse.metabase.com/t/biq-query-standard-sql/966/2](url), while there's no "official" support, it is believed that BigQuery's introduction of SQL version tags at the top of the script (i.e. #standardSQL vs #legacySQL) should work out of the box (also see #3012).

However, consider the following - 

This is legacySQL, which works well inside a card:

    select round(avg(cnt), 2) as avg_cnt
    from (
      select req_id , count(distinct id) as cnt
      from <dataset>.<table>
      where 1=1
      and date(open_date) > date(date_add(current_date(), -1, "YEAR"))
      group by 1
    )

Here's the same query, adapted to standardSQL (works well in the BQ console):

    #standardSQL
    select round(avg(cnt), 2) as avg_cnt
    from (
      select req_id , count(distinct id) as cnt
      from <dataset>.<table>
      where 1=1
      and date(open_date) > date_sub(current_date(), INTERVAL -1 YEAR)
      group by 1
    )

Which throws the following error:

    Encountered " <ID> "YEAR "" at line 8, column 62. Was expecting: ")" ...

I'm new to Metabase, but it would seem that there's some sort of failed validation done on the query being shipped to BQ - otherwise, it should work (as it does indeed work in the console).

**Comment by camsaul** [comment] 2017-01-05 01:52
@gilhs as mentioned in #3012 the `#standardSQL` tags *do not* work with Metabase because we prepend other information to the query.

Closing this as a duplicate of #3012 (support BigQuery standard SQL)

**Closed by camsaul** 2017-01-05 01:52 UTC
Labels: Bug, Database/BigQuery
