### ISSUE TITLE
Custom filter widget value dropped when Exploring Results of Native SQL question

### ISSUE THREAD

**Issue by rarup1** [metabase/metabase#19584] opened 2022-01-07 14:17 UTC
**Describe the bug**
The Explore Results feature doesn't use the Custom Filter Widget value when Exploring Results of a native script using variables. It always uses the default value set in the question which confuses end user and seems wrong.

**Logs**
N/A

**To Reproduce**
1. Go to "Ask Question" and start a "Native Query"
2. Pick a database
3. Enter `SELECT {{custom_or_default_date}}` in native SQL box
4. Configure variables:
 Set Variable type = Date
 Set Required = Yes
 Set default widget value = January 6, 2022
Save
5. If you explore the results now you would expect it to show **2022-01-06 00:00:00**
6. If you update the Custom or Default date widget - January 14, 2022 and explore results:
the URL updates to: https://metabase.eng.lendinvestinternal.com/question?custom_or_default_date=2022-01-14#eyJkYXRhc2V...
but the results still return **2022-01-06 00:00:00**

**Expected behavior**
It should return **2022-01-14 00:00:00** as the URL parameter/Custom filter should always over ride the initial default widget value.

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome
- Your operating system: Mac Monterwy
- Your databases: MySQL
- Metabase version:  Metabase 0.41.5 
- Metabase hosting environment: (K8s)
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely? 

**Annoying**
It is annoying as the new Explore Results feature is ace but this makes it less useful and risky to leave in the hands of the less attentive users who explore and export results from Native SQL stored questions

**Additional context**

**Comment by flamber** [comment] 2022-01-25 21:02
Duplicate of #6449, since it's currently not support to pass-thru variables to nested queries

**Closed by flamber** 2022-01-25 21:02 UTC
Labels: Type:Bug, .Needs Triage
