### ISSUE TITLE
Possible bug in query mongodb (if set more than one sum in view)

### ISSUE THREAD

**Issue by worotyns** [metabase/metabase#8939] opened 2018-11-14 20:27 UTC
Hi there,

Possible bug in query mongodb (if set more than one sum in view)

Metabase 0.31.1, driver MongoDB, example table structure:
```
{
  push: {
    clicked: 120,
    unsubscribed: 100 
  }
}
```

When I want to query sum of clicked and unsubscribed, native query retrurns:
```
[
  {
    "$project":{
        "push___clicked": "$push.clicked",
        "push___unsubscribed":"$push.unsubscribed"
  }
},{
  "$group":{
     "_id":null,
     "sum":{"$sum":"$push___unsubscribed"}
  }
}, {"$sort":{"_id":1}},{"$project":{"_id":false,"sum":true}}]
```

And table looks like:
clicked: 100, unsubscribed: 100

I think group is wrong in this case becouse of sum is only one?, 
Should be 2 times:
```
{
  "$group":{
     "_id":null,
     "push___unsubscribed___sum":{"$sum":"$push___unsubscribed"},
     "push___clicked___sum":{"$sum":"$push___clicked"}
  }

and of course:

{"$project":{"_id":false,"push___unsubscribed___sum":true, "push___clicked___sum": true}
```

Thanks for this awesome project!

**Comment by tlrobinson** [comment] 2018-11-14 20:32
I think this is a duplicate of #5393

**Comment by camsaul** [comment] 2018-11-16 01:50
Yup, duplicate of #5393

**Closed by camsaul** 2018-11-16 01:50 UTC
Labels: Bug, Database/Mongo, Duplicate
