### ISSUE TITLE
Modal for downloading large datasets have a wrong z-index on the background

### ISSUE THREAD

**Issue by MrMauricioLeite** [metabase/metabase#2106] opened 2016-03-08 18:06 UTC
It's impossible to click onde the csv download button inside the modal for large datasets, thats because the overlay is using z-index:4 and no z-index: -4.

Can't find where to change it on the sources, sorry guys.

**Comment by agilliland** [comment] 2016-03-08 18:08
This is dupe of #2077 which is fixed will be included in a patch release coming out soon.

**Closed by agilliland** 2016-03-08 18:08 UTC
Labels: Duplicate
