### ISSUE TITLE
moving a model from athena to redshift breaks all questions based on the model

### ISSUE THREAD

**Issue by gajanand-jm** [metabase/metabase#25056] opened 2022-08-27 08:12 UTC
**Describe the bug**
Moving a Metabase model (currently using Athena) to Redshift breaks all questions based on it

Steps to reproduce -
1. switch from Athena to Redshift query engine in Metabase native query editor (for any existing model)
2. make query changes (since Athena uses Presto, and Redshift has RedshiftSQL)
3. test the query (no errors here), save the model and its metadata
4. all the questions based on this model break
5. but we create the same question again from scratch using the updated model (based on redshift), and it works fine

**Expected behavior**

**Screenshots**
<img width="380" alt="Screenshot 2022-08-27 at 1 37 37 PM" src="https://user-images.githubusercontent.com/91305327/187021357-7ea9f21d-892b-4028-ae93-d50094cd5577.png">
<img width="1632" alt="Screenshot 2022-08-27 at 1 34 56 PM" src="https://user-images.githubusercontent.com/91305327/187021367-2b77ea78-f8dc-4932-b415-55b2324a0ce2.png">
<img width="703" alt="Screenshot 2022-08-27 at 1 35 08 PM" src="https://user-images.githubusercontent.com/91305327/187021370-581f1bbf-0f1a-4810-aefe-0e9344b81840.png">

**Severity**
medium, if this doesn't work then we'll have to recreate most of our Athena-based questions and dashboards again.

**Additional context**
we're planning to move to redshift (as a data warehouse) from athena to simplify our workflow and pipelines, and optimize cost.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_111-internal-alpine-r0-b14",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_111-internal",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.111-b14",
    "os.name": "Linux",
    "os.version": "5.4.149-73.259.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "presto-jdbc",
      "h2",
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.42.3",
      "date": "2022-03-23",
      "branch": "release-x.42.x",
      "hash": "33fb268"
    },
    "settings": {
      "report-timezone": "Asia/Kolkata"
    }
  }
}
```

**Comment by flamber** [comment] 2022-08-27 08:59
Hi @gajanand-jm 
You are changing a single Model to use another database as source (Redshift), but all the questions based on this Model is still running as if they are connected to the original database source (Athena).
You'll need to update the database source for the questions depending on that Model. Closing as a duplicate of #6496.
Also, you should update to Java 11: https://www.metabase.com/docs/latest/installation-and-operation/java-versions

**Closed by flamber** 2022-08-27 08:59 UTC
