### ISSUE TITLE
Refresh button for already-run SQL questions?

### ISSUE THREAD

**Issue by jongyonkim** [metabase/metabase#2787] opened 2016-06-16 21:33 UTC
It would be nice to have a button to re-submit the same SQL query. Once a query is run, the pop-up button ```Get Answer``` disappears.

The only way around it is to change the SQL query a little bit and get back the ```Get Answer``` button.

For example, if I run a query at 1:00PM, and 10 minutes later (after the data source is updated with more data), I cannot "refresh" the same query. Instead, I change the ```timestamp``` window a little bit to get the button back and re-run.

**Comment by tlrobinson** [comment] 2016-06-16 23:39
@jongyonkim This is a duplicate of #1547 which has been fixed in v0.18.0 which will be released in the next week or two.

**Closed by tlrobinson** 2016-06-16 23:39 UTC
