### ISSUE TITLE
Ask the mysql driver to use MySQL Connector/J instead of mariadb-connector-j

### ISSUE THREAD

**Issue by zhoujunhe** [metabase/metabase#26172] opened 2022-10-31 03:41 UTC
**Is your feature request related to a problem? Please describe.**
The Ali AnalyticDB for MySQL database engine I used is not compatible with mariadb-connector-j.

**Describe the solution you'd like**
Replace mariadb-connector-j with MySQL Connector/J.

**Describe alternatives you've considered**
Build a MySQL Connector/J version.

**How important is this feature to you? **
Very used, I am now using data warehouse engine is Ali AnalyticDB for MySQL.

**Additional context**
<img width="1064" alt="bb" src="https://user-images.githubusercontent.com/38268906/198926436-95bb5d83-98cf-4a1e-8902-4b80f81b23b6.png">

**Comment by flamber** [comment] 2022-10-31 08:49
Duplicate of #12537

**Closed by flamber** 2022-10-31 08:49 UTC
Labels: Type:New Feature, .Needs Triage
