### ISSUE TITLE
Cannot jump to the page correctly after clicking [show editor]

### ISSUE THREAD

**Issue by chendanli** [metabase/metabase#18865] opened 2021-11-05 11:10 UTC
**Describe the bug**
Before upgrading Metabase to v0.41.1, I associated two tables, but because the associated field data type is different, I did a concat (" ", [field name]) process (which failed to be reproduced later), after upgrading (probably), when click the show Editor, the page cannot be displayed and it keeps spinning.

**Logs**
don't have

**To Reproduce**
Unable to reproduce, because Metabase did not allow the association using the previous concat method to associate the two tables

**Expected behavior**
The page should be displayed after clicking show Editor.

**Screenshots**
![image](https://user-images.githubusercontent.com/92294741/140493848-a4202d65-733d-48d1-8e9e-881f823f2453.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 95.0.4638.69
- Your operating system: Windows 10.1607
- Your databases: Postgres
- Metabase version: v0.41.1
- Metabase hosting environment:I don‘t know
- Metabase internal database:I don‘t know

**Severity**
It’s serious. After taking many methods, the ‘edit’ page cannot be displayed correctly, and subsequent operations cannot be performed.

**Additional context**

**Comment by flamber** [comment] 2021-11-05 11:15
Duplicate of #18818

**Closed by flamber** 2021-11-05 11:15 UTC
Labels: Type:Bug, .Needs Triage
