### ISSUE TITLE
times get ignored in dates filter when using between filter type.

### ISSUE THREAD

**Issue by cyberhorse** [metabase/metabase#4504] opened 2017-03-08 21:57 UTC
If seems to add "date()" function around the field and returns wrong results

Chrome 55 x64
Metabase version: 0.22.2 on docker

Steps:
- New question
- Select date filter
- Select "between"
- Check the time box and enter times
- Result: times get ignored.

**Comment by camsaul** [comment] 2017-03-08 22:01
Duplicate of #4192

@cyberhorse, a fix for this is shipping with our upcoming release

**Closed by camsaul** 2017-03-08 22:01 UTC
Labels: Duplicate

**Comment by cyberhorse** [comment] 2017-03-08 22:29
Sorry for the duplication. I did search for it, but couldn't find the issue you referenced. All good - thank you.
