### ISSUE TITLE
Kubernetes non-privileged container with arbitrary user/groupid

### ISSUE THREAD

**Issue by nadilas** [metabase/metabase#13829] opened 2020-11-18 09:53 UTC
Hi everyone,

running the docker image on kubernetes fails with the following errors:

```
addgroup: permission denied (are you root?)
adduser: permission denied (are you root?)
mkdir: can't create directory '//metabase.db': Permission denied
chmod: /app/metabase.jar: Operation not permitted
su: must be suid to work properly
```

I imagine I can get around the first three, by setting the group and the user from the assigned  and setting the db path to an existing mapped folder from the pvc, however I don't see a way around `chmod` and `su` lines. Do I need to create my own image or is there already an existing one?

https://github.com/metabase/metabase/blob/2a0683bc3dcf1b3e11e41d073c84bac71b3ddce5/bin/docker/run_metabase.sh#L123

**Comment by flamber** [comment] 2020-11-18 09:56
Duplicate of #13147/#9861

**Closed by flamber** 2020-11-18 09:56 UTC
