### ISSUE TITLE
Joining twice on same table and renaming columns renames both tables' columns

### ISSUE THREAD

**Issue by JonCrawford** [metabase/metabase#23979] opened 2022-07-14 22:15 UTC
**Describe the bug**
I've got a model with 2 foreign columns to the same table. This is a relationship table, so each column describes a different role in the relationship. As expected, columns from the foreign table originally look like this: "Shops - _Storefront_ Shop → Name" and "Shops - _Storefront_ Shop → Name". Attempting to change these to "Storefront Name" and "Supplier Name" does not work. It changes both columns to "Storefront Name" and then both columns to "Supplier Name". It renames both columns every time.

**To Reproduce**
1. Start with a table with 2+ foreign keys to the same table.
2. Create JOINs to both instances of the foreign table.
3. Attempt to rename a column in the first instance of the foreign table.
4. Notice that the 2nd instance's name also changed to whatever you input.

**Expected behavior**
The two tables should have distinctly editable column names.

**Screenshots**
![Editor](https://p191.p3.n0.cdn.getcloudapp.com/items/yAu19yKj/734e9927-504d-4b07-a5c0-76326f3be41f.png?v=82bfe29279fb2598086f7bcd60be165a)

![Duplicate column names](https://p191.p3.n0.cdn.getcloudapp.com/items/8Lu0Y5pv/9012aaad-ae5f-46bb-8367-dc8869da2bc0.png?source=viewer&v=119cd29375e5fd7f9148a40653c7de60)

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.4.196-108.356.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-06-27",
      "tag": "v1.43.4",
      "branch": "release-x.43.x",
      "hash": "61cc28e"
    },
    "settings": {
      "report-timezone": "America/Los_Angeles"
    }
  }
}
```

**Additional Info**
This also seems to happen when attempting to filter by a column on one of the instances of the foreign table.

**Comment by flamber** [comment] 2022-07-21 15:30
Duplicate of #12685

**Closed by flamber** 2022-07-21 15:30 UTC
Labels: Type:Bug, Priority:P2, Querying/GUI
