### ISSUE TITLE
Ability to specify order with multiple categories on bar/line graphs

### ISSUE THREAD

**Issue by that0n3guy** [metabase/metabase#2339] opened 2016-04-08 13:55 UTC
I have a question with 5 categories, grouped by date and category:

![image](https://cloud.githubusercontent.com/assets/113870/14385566/cbca9cae-fd66-11e5-911d-20e5a8171c66.png)

It shows it almost perfectly (nice job!), but I am unable to set the color and order of the groups.  I realize I can do this on with multiseries charting (http://www.metabase.com/docs/v0.15.0/users-guide/09-multi-series-charting) but that requires 5 questions/queries (more in other cases) and this would be nice.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by agilliland** [comment] 2016-04-08 14:29
Just so that we have more information can you explain a bit more about why you need to control the order of the values and the specific colors?

**Comment by that0n3guy** [comment] 2016-04-08 14:37
Colors I don't care too much about. 

Order, those "categories" are actually stages in a sales process.  So they have an order.  Its confusing to look at this bar chart to non-tech people because the bars should go tall (on left) to short (on right) due to the drop off through all the sales stages.

**Comment by mazameli** [comment] 2016-04-08 17:11
This is great feedback and context. 👍🏽

**Comment by that0n3guy** [comment] 2016-05-03 14:13
Maybe something else that might help would be the `ORDER BY FIELD`.   Not sure why I didn't think of this before.

**Comment by that0n3guy** [comment] 2016-08-02 14:42
Looks like in the .19 version I can now specify color, woo hoo.

**But still cant specify order** so I think this issue should stay open until then.

**Comment by that0n3guy** [comment] 2018-01-04 22:54
@tlrobinson I'm on 0.26.1 and there still isn't an ability to specify order.   Can we re-open this issue or am I missing it someplace?

**Comment by vrnroman** [comment] 2018-09-04 14:04
I can't find an ability to reorder legend in charts. Could we reopen this issue?

**Comment by mazameli** [comment] 2018-11-12 18:29
Reopening this after checking with @tlrobinson. Currently you can only change the order in this scenario from ascending to descending; you can't yet define a custom order.

If and when we tackle this issue, we should think about it alongside the ability to reorder steps in a Funnel visualization. They're very similar problems.

**Comment by invalid-access** [comment] 2018-11-13 15:08
Facing this same issue. I'm doing a bar chart with two breakouts: year and month. I've used 'order by' in my SQL query. The tabular data (attached) is nicely ordered. However the bar chart messes up the ordering by no clear logic I.e. it'd be ok if it got confused between string-ordering vs int-ordering), but as you can see in the screenshot's legend, the resulting ordering is weird. Running version 0.30.4.


Tabular
<img width="452" alt="screen shot 2018-11-13 at 8 32 05 pm" src="https://user-images.githubusercontent.com/12869260/48422045-cc5a4480-e783-11e8-838b-6aad9cd1c839.png">

Bar
<img width="1401" alt="screen shot 2018-11-13 at 8 32 33 pm" src="https://user-images.githubusercontent.com/12869260/48422071-d8460680-e783-11e8-8d08-bd2b4d9ea2e7.png">

**Comment by noblemavely** [comment] 2019-03-29 04:33
Facing the same issue for multiple use cases. We have a workflow in the bar chart and the users who want to see the chart in a linear format.

**Comment by mangalprasad** [comment] 2019-07-19 11:26
Facing same issue. Multiple use cases. What are the chances this is getting prioritized?

**Comment by MarcGJA** [comment] 2019-09-24 17:52
Providing an "Order by field" option for breakouts would be ideal in comparing two or more questions with dissimilar x-axis ordering but sharing the same breakout in the same dashboard.  See this discourse post for a good case illustration:
https://discourse.metabase.com/t/provide-an-order-by-field-option-for-breakouts/7452

Upvoting the opening post to this issue is the best way to let the Metabase team know what is of most interest to users.  The more upvotes the more likely the issue will be taken up in a future release.  Those having recently posted to this thread may want to revisit, sign in, and upvote this issue.

**Comment by ajcoll5** [comment] 2020-04-27 16:44
> 
> 
> Reopening this after checking with @tlrobinson. Currently you can only change the order in this scenario from ascending to descending; you can't yet define a custom order.
> 
> If and when we tackle this issue, we should think about it alongside the ability to reorder steps in a Funnel visualization. They're very similar problems.

@mazameli I think this might be broken or not consistent on 0.35.3?

![LegendOrderBroken](https://user-images.githubusercontent.com/8853015/80397737-95e38d00-8884-11ea-8637-4f4cc8745851.png)

**Comment by flamber** [comment] 2020-04-27 16:50
@ajcoll5 This is specific to manually (custom) being able to change the order. You're likely seeing something else, but I cannot reproduce your pie issue on 0.35.3
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by AmandaGeorge** [comment] 2020-07-28 01:05
@tlrobinson It would be helpful if you would comment on why this is being removed from the 0.23.0 milestone when it is still an issue for so many.  My funnel at this point isn't even sorting alphabetically, making it useless.
![Screen Shot 2020-07-27 at 6 03 38 PM](https://user-images.githubusercontent.com/12942618/88607288-b661e580-d033-11ea-9a42-3f20e51c68c0.png)

**Comment by flamber** [comment] 2020-07-28 10:07
@AmandaGeorge Because 0.23.0 was released several years ago, but was wrongfully attached to this issue. The issue is still open, but there's no timeline for a fix. There's a specific issue #5401 for funnel ordering. Upvote by clicking :+1: on the first post.

**Comment by phaseOne** [comment] 2020-08-05 19:20
Also, I'm seeing that the order is based on order of appearance in the raw data, rather than the complete set (in v0.32.9 at least). Ideally I'd prefer manual control over the order, but I think it would help if there was some consistency between views as a first pass.

<img width="817" alt="CleanShot 2020-08-05 at 12 15 05@2x" src="https://user-images.githubusercontent.com/1310985/89454429-8c847f00-d715-11ea-9d67-0c0c9ba2f50f.png">
<img width="684" alt="CleanShot 2020-08-05 at 12 15 13@2x" src="https://user-images.githubusercontent.com/1310985/89454426-8b535200-d715-11ea-98a4-0fe1ddcbb386.png">

**Comment by phaseOne** [comment] 2020-08-05 19:30
Oh hey, just found a workaround for my use case! You can apply a sort on your series column like so:
![CleanShot 2020-08-05 at 12 25 08@2x](https://user-images.githubusercontent.com/1310985/89455465-37e20380-d717-11ea-85a6-47b2b33a891f.png)

It doesn't help those that need a custom order, but I suppose there's a way in SQL to remap column names with a numerical prefix to establish a custom sort order.

**Comment by flamber** [comment] 2020-08-05 19:35
@phaseOne A lot has changed since 0.32.9 - and it's also possible to sort in the latest release, 0.36.3:
https://www.metabase.com/docs/latest/users-guide/custom-questions.html#sorting-results

**Comment by bencooper222** [comment] 2021-01-28 19:31
Facing the issue with custom SQL editor. I'm trying to order by quarter here. However, I think the primary sorting of `latest_coverage` results in 2021-Q1 coming first so it just assumes that's first. Maddening. 

![image](https://user-images.githubusercontent.com/9143563/106188778-ffbef900-616c-11eb-9a98-38949680b973.png)

**Comment by psbelin** [comment] 2021-11-05 10:08
Like people have said, it would be great to have the possibility of reordering the legend fields in the same way the columns in a table view. Sometimes you need to have a different order in the chart from the one in the legend, and there seems to be no way to do it.

**Comment by alxnddr** [comment] 2022-10-28 10:46
Closed by https://github.com/metabase/metabase/issues/24840

**Closed by alxnddr** 2022-10-28 10:46 UTC
Labels: Type:New Feature, Visualization/Chart Settings, Visualization/Charts
