### ISSUE TITLE
Fails to "Explore results" of a native question with field filter

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#22589] opened 2022-05-10 14:19 UTC
**Describe the bug**

**To Reproduce**
1. Create a Native question with the following query
```sql
SELECT *
FROM Orders
LEFT JOIN Products
ON Orders.product_id = Products.id
WHERE {{category}};
```
2. In "Variable type" select "Field Filter"
3. In "Field to map to", select "Products => Category"
4. Save the question
5. Click Explore results

**Expected behavior**
Able to explore results without error

**Logs**
```
2022-05-10 14:17:41,291 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 1,
 :started_at #t "2022-05-10T14:17:41.110469Z[UTC]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error executing query: Duplicate column name \"ID\"; SQL statement:\n-- Metabase:: userID: 1 queryType: MBQL queryHash: b9b29d52ec0d61b8afd22e1a36839c6d13d54932d6a518b763f4d348be596551\nSELECT \"source\".\"ID\" AS \"ID\", \"source\".\"USER_ID\" AS \"USER_ID\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"source\".\"TAX\" AS \"TAX\", \"source\".\"TOTAL\" AS \"TOTAL\", \"source\".\"DISCOUNT\" AS \"DISCOUNT\", \"source\".\"CREATED_AT\" AS \"CREATED_AT\", \"source\".\"QUANTITY\" AS \"QUANTITY\", \"source\".\"ID_2\" AS \"ID_2\", \"source\".\"EAN\" AS \"EAN\", \"source\".\"TITLE\" AS \"TITLE\", \"source\".\"CATEGORY\" AS \"CATEGORY\", \"source\".\"VENDOR\" AS \"VENDOR\", \"source\".\"PRICE\" AS \"PRICE\", \"source\".\"RATING\" AS \"RATING\", \"source\".\"CREATED_AT_2\" AS \"CREATED_AT_2\" FROM (SELECT *\nFROM Orders\nLEFT JOIN Products\nON Orders.product_id = Products.id\nWHERE 1 = 1) \"source\" LIMIT 2000 [42121-197]",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__81512.invoke(execute.clj:502)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:499)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:494)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
    "driver.sql_jdbc$eval92323$fn__92324.invoke(sql_jdbc.clj:54)"
    "driver.h2$eval92416$fn__92417.invoke(h2.clj:90)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
    "query_processor.context.default$default_runf.invoke(default.clj:65)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___72860.invoke(cache.clj:220)"
    "query_processor.middleware.permissions$check_query_permissions$fn__75767.invoke(permissions.clj:109)"
    "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$check_download_permissions$fn__79524.invoke(permissions.clj:127)"
    "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__79768.invoke(column_level_perms_check.clj:30)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__77061.invoke(mbql_to_native.clj:23)"
    "query_processor$fn__80304$combined_post_process__80309$combined_post_process_STAR___80310.invoke(query_processor.clj:207)"
    "query_processor$fn__80304$combined_pre_process__80305$combined_pre_process_STAR___80306.invoke(query_processor.clj:204)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__78278$fn__78283.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:75)"
    "driver$do_with_driver.invoke(driver.clj:71)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__78278.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__76868.invoke(fetch_source_query.clj:318)"
    "query_processor.middleware.store$initialize_store$fn__79112$fn__79113.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__79112.invoke(store.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__77080.invoke(normalize_query.clj:22)"
    "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__79735.invoke(handle_audit_queries.clj:130)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__66431.invoke(constraints.clj:52)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__78151.invoke(process_userland_query.clj:145)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__75860.invoke(catch_exceptions.clj:162)"
    "query_processor.reducible$async_qp$qp_STAR___68042$thunk__68044.invoke(reducible.clj:100)"
    "query_processor.reducible$async_qp$qp_STAR___68042.invoke(reducible.clj:106)"
    "query_processor.reducible$async_qp$qp_STAR___68042.invoke(reducible.clj:91)"
    "query_processor$base_qp$fn__80316.doInvoke(query_processor.clj:225)"
    "query_processor.reducible$sync_qp$qp_STAR___68053.doInvoke(reducible.clj:126)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:326)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:322)"
    "query_processor$eval80351$process_query_and_save_execution_BANG___80360$fn__80363.invoke(query_processor.clj:337)"
    "query_processor$eval80351$process_query_and_save_execution_BANG___80360.invoke(query_processor.clj:330)"
    "query_processor$eval80395$process_query_and_save_with_max_results_constraints_BANG___80404$fn__80407.invoke(query_processor.clj:349)"
    "query_processor$eval80395$process_query_and_save_with_max_results_constraints_BANG___80404.invoke(query_processor.clj:342)"
    "api.dataset$run_query_async$fn__98416.invoke(dataset.clj:68)"
    "query_processor.streaming$streaming_response_STAR_$fn__88627$fn__88628.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__88627.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__49899.invoke(streaming_response.clj:84)"],
   :error_type :invalid-query,
   :ex-data
   {:sql
    "-- Metabase:: userID: 1 queryType: MBQL queryHash: b9b29d52ec0d61b8afd22e1a36839c6d13d54932d6a518b763f4d348be596551\nSELECT \"source\".\"ID\" AS \"ID\", \"source\".\"USER_ID\" AS \"USER_ID\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"source\".\"TAX\" AS \"TAX\", \"source\".\"TOTAL\" AS \"TOTAL\", \"source\".\"DISCOUNT\" AS \"DISCOUNT\", \"source\".\"CREATED_AT\" AS \"CREATED_AT\", \"source\".\"QUANTITY\" AS \"QUANTITY\", \"source\".\"ID_2\" AS \"ID_2\", \"source\".\"EAN\" AS \"EAN\", \"source\".\"TITLE\" AS \"TITLE\", \"source\".\"CATEGORY\" AS \"CATEGORY\", \"source\".\"VENDOR\" AS \"VENDOR\", \"source\".\"PRICE\" AS \"PRICE\", \"source\".\"RATING\" AS \"RATING\", \"source\".\"CREATED_AT_2\" AS \"CREATED_AT_2\" FROM (SELECT *\nFROM Orders\nLEFT JOIN Products\nON Orders.product_id = Products.id\nWHERE 1 = 1) \"source\" LIMIT 2000",
    :params nil,
    :type :invalid-query}}],
 :state "42S21",
 :error_type :invalid-query,
 :json_query
 {:database 1,
  :query {:source-table "card__5"},
  :type "query",
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT \"source\".\"ID\" AS \"ID\", \"source\".\"USER_ID\" AS \"USER_ID\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"source\".\"TAX\" AS \"TAX\", \"source\".\"TOTAL\" AS \"TOTAL\", \"source\".\"DISCOUNT\" AS \"DISCOUNT\", \"source\".\"CREATED_AT\" AS \"CREATED_AT\", \"source\".\"QUANTITY\" AS \"QUANTITY\", \"source\".\"ID_2\" AS \"ID_2\", \"source\".\"EAN\" AS \"EAN\", \"source\".\"TITLE\" AS \"TITLE\", \"source\".\"CATEGORY\" AS \"CATEGORY\", \"source\".\"VENDOR\" AS \"VENDOR\", \"source\".\"PRICE\" AS \"PRICE\", \"source\".\"RATING\" AS \"RATING\", \"source\".\"CREATED_AT_2\" AS \"CREATED_AT_2\" FROM (SELECT *\nFROM Orders\nLEFT JOIN Products\nON Orders.product_id = Products.id\nWHERE 1 = 1) \"source\" LIMIT 1048575",
  :params nil},
 :status :failed,
 :class org.h2.jdbc.JdbcSQLException,
 :stacktrace
 ["org.h2.message.DbException.getJdbcSQLException(DbException.java:357)"
  "org.h2.message.DbException.get(DbException.java:179)"
  "org.h2.message.DbException.get(DbException.java:155)"
  "org.h2.table.Table.setColumns(Table.java:431)"
  "org.h2.table.TableView.initColumnsAndTables(TableView.java:242)"
  "org.h2.table.TableView.init(TableView.java:113)"
  "org.h2.table.TableView.<init>(TableView.java:70)"
  "org.h2.table.TableView.createTempView(TableView.java:559)"
  "org.h2.command.Parser.readTableFilter(Parser.java:1367)"
  "org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:2138)"
  "org.h2.command.Parser.parseSelectSimple(Parser.java:2287)"
  "org.h2.command.Parser.parseSelectSub(Parser.java:2133)"
  "org.h2.command.Parser.parseSelectUnion(Parser.java:1946)"
  "org.h2.command.Parser.parseSelect(Parser.java:1919)"
  "org.h2.command.Parser.parsePrepared(Parser.java:463)"
  "org.h2.command.Parser.parse(Parser.java:335)"
  "org.h2.command.Parser.parse(Parser.java:307)"
  "org.h2.command.Parser.prepareCommand(Parser.java:278)"
  "org.h2.engine.Session.prepareLocal(Session.java:611)"
  "org.h2.engine.Session.prepareCommand(Session.java:549)"
  "org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)"
  "org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)"
  "org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)"
  "com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)"
  "--> driver.sql_jdbc.execute$eval81416$fn__81417.invoke(execute.clj:367)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:375)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:372)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__81512.invoke(execute.clj:500)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:499)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:494)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
  "driver.sql_jdbc$eval92323$fn__92324.invoke(sql_jdbc.clj:54)"
  "driver.h2$eval92416$fn__92417.invoke(h2.clj:90)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
  "query_processor.context.default$default_runf.invoke(default.clj:65)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
  "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___72860.invoke(cache.clj:220)"
  "query_processor.middleware.permissions$check_query_permissions$fn__75767.invoke(permissions.clj:109)"
  "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$check_download_permissions$fn__79524.invoke(permissions.clj:127)"
  "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__79768.invoke(column_level_perms_check.clj:30)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__77061.invoke(mbql_to_native.clj:23)"
  "query_processor$fn__80304$combined_post_process__80309$combined_post_process_STAR___80310.invoke(query_processor.clj:207)"
  "query_processor$fn__80304$combined_pre_process__80305$combined_pre_process_STAR___80306.invoke(query_processor.clj:204)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__78278$fn__78283.invoke(resolve_database_and_driver.clj:35)"
  "driver$do_with_driver.invokeStatic(driver.clj:75)"
  "driver$do_with_driver.invoke(driver.clj:71)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__78278.invoke(resolve_database_and_driver.clj:34)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__76868.invoke(fetch_source_query.clj:318)"
  "query_processor.middleware.store$initialize_store$fn__79112$fn__79113.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__79112.invoke(store.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__77080.invoke(normalize_query.clj:22)"
  "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__79735.invoke(handle_audit_queries.clj:130)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__66431.invoke(constraints.clj:52)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__78151.invoke(process_userland_query.clj:145)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__75860.invoke(catch_exceptions.clj:162)"
  "query_processor.reducible$async_qp$qp_STAR___68042$thunk__68044.invoke(reducible.clj:100)"
  "query_processor.reducible$async_qp$qp_STAR___68042.invoke(reducible.clj:106)"
  "query_processor.reducible$async_qp$qp_STAR___68042.invoke(reducible.clj:91)"
  "query_processor$base_qp$fn__80316.doInvoke(query_processor.clj:225)"
  "query_processor.reducible$sync_qp$qp_STAR___68053.doInvoke(reducible.clj:126)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:326)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:322)"
  "query_processor$eval80351$process_query_and_save_execution_BANG___80360$fn__80363.invoke(query_processor.clj:337)"
  "query_processor$eval80351$process_query_and_save_execution_BANG___80360.invoke(query_processor.clj:330)"
  "query_processor$eval80395$process_query_and_save_with_max_results_constraints_BANG___80404$fn__80407.invoke(query_processor.clj:349)"
  "query_processor$eval80395$process_query_and_save_with_max_results_constraints_BANG___80404.invoke(query_processor.clj:342)"
  "api.dataset$run_query_async$fn__98416.invoke(dataset.clj:68)"
  "query_processor.streaming$streaming_response_STAR_$fn__88627$fn__88628.invoke(streaming.clj:162)"
  "query_processor.streaming$streaming_response_STAR_$fn__88627.invoke(streaming.clj:161)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$task__49899.invoke(streaming_response.clj:84)"],
 :card_id 5,
 :context :ad-hoc,
 :error
 "Duplicate column name \"ID\"; SQL statement:\n-- Metabase:: userID: 1 queryType: MBQL queryHash: b9b29d52ec0d61b8afd22e1a36839c6d13d54932d6a518b763f4d348be596551\nSELECT \"source\".\"ID\" AS \"ID\", \"source\".\"USER_ID\" AS \"USER_ID\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"source\".\"TAX\" AS \"TAX\", \"source\".\"TOTAL\" AS \"TOTAL\", \"source\".\"DISCOUNT\" AS \"DISCOUNT\", \"source\".\"CREATED_AT\" AS \"CREATED_AT\", \"source\".\"QUANTITY\" AS \"QUANTITY\", \"source\".\"ID_2\" AS \"ID_2\", \"source\".\"EAN\" AS \"EAN\", \"source\".\"TITLE\" AS \"TITLE\", \"source\".\"CATEGORY\" AS \"CATEGORY\", \"source\".\"VENDOR\" AS \"VENDOR\", \"source\".\"PRICE\" AS \"PRICE\", \"source\".\"RATING\" AS \"RATING\", \"source\".\"CREATED_AT_2\" AS \"CREATED_AT_2\" FROM (SELECT *\nFROM Orders\nLEFT JOIN Products\nON Orders.product_id = Products.id\nWHERE 1 = 1) \"source\" LIMIT 2000 [42121-197]",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:database 1,
  :query
  {:source-card-id 5,
   :source-metadata
   [{:display_name "ID",
     :field_ref [:field "ID" {:base-type :type/BigInteger}],
     :name "ID",
     :base_type :type/BigInteger,
     :effective_type :type/BigInteger,
     :semantic_type :type/PK,
     :fingerprint nil}
    {:display_name "USER_ID",
     :field_ref [:field "USER_ID" {:base-type :type/Integer}],
     :name "USER_ID",
     :base_type :type/Integer,
     :effective_type :type/Integer,
     :semantic_type nil,
     :fingerprint
     {:global {:distinct-count 193, :nil% 0.0},
      :type
      {:type/Number
       {:min 1.0, :q1 65.75124219539381, :q3 215.0496485969564, :max 276.0, :sd 81.03924458071305, :avg 137.893}}}}
    {:display_name "PRODUCT_ID",
     :field_ref [:field "PRODUCT_ID" {:base-type :type/Integer}],
     :name "PRODUCT_ID",
     :base_type :type/Integer,
     :effective_type :type/Integer,
     :semantic_type nil,
     :fingerprint
     {:global {:distinct-count 200, :nil% 0.0},
      :type
      {:type/Number
       {:min 1.0, :q1 49.215431541775644, :q3 147.99543851531354, :max 200.0, :sd 57.76090574004626, :avg 98.553}}}}
    {:display_name "SUBTOTAL",
     :field_ref [:field "SUBTOTAL" {:base-type :type/Float}],
     :name "SUBTOTAL",
     :base_type :type/Float,
     :effective_type :type/Float,
     :semantic_type nil,
     :fingerprint
     {:global {:distinct-count 330, :nil% 0.0},
      :type
      {:type/Number
       {:min 15.691943673970439,
        :q1 49.985248755650794,
        :q3 105.75635962212282,
        :max 148.22900526552291,
        :sd 32.66637499877059,
        :avg 77.87581313233785}}}}
    {:display_name "TAX",
     :field_ref [:field "TAX" {:base-type :type/Float}],
     :name "TAX",
     :base_type :type/Float,
     :effective_type :type/Float,
     :semantic_type nil,
     :fingerprint
     {:global {:distinct-count 600, :nil% 0.0},
      :type
      {:type/Number
       {:min 0.0,
        :q1 2.383235294117647,
        :q3 5.576262636024203,
        :max 11.12,
        :sd 2.369881443862045,
        :avg 3.9948050000000004}}}}
    {:display_name "TOTAL",
     :field_ref [:field "TOTAL" {:base-type :type/Float}],
     :name "TOTAL",
     :base_type :type/Float,
     :effective_type :type/Float,
     :semantic_type nil,
     :fingerprint
     {:global {:distinct-count 1494, :nil% 0.0},
      :type
      {:type/Number
       {:min 13.703915846433869,
        :q1 52.16498672761125,
        :q3 110.74896236179433,
        :max 159.34900526552292,
        :sd 34.41222590732287,
        :avg 81.33739624585914}}}}
    {:display_name "DISCOUNT",
     :field_ref [:field "DISCOUNT" {:base-type :type/Float}],
     :name "DISCOUNT",
     :base_type :type/Float,
     :effective_type :type/Float,
     :semantic_type :type/Discount,
     :fingerprint
     {:global {:distinct-count 185, :nil% 0.8945},
      :type
      {:type/Number
       {:min 0.41329422842438834,
        :q1 3.1115483062325273,
        :q3 7.341641026703381,
        :max 9.669111943074371,
        :sd 2.452703604726128,
        :avg 5.054235890793273}}}}
    {:display_name "CREATED_AT",
     :field_ref [:field "CREATED_AT" {:base-type :type/DateTime, :temporal-unit :default}],
     :name "CREATED_AT",
     :base_type :type/DateTime,
     :effective_type :type/DateTime,
     :semantic_type :type/CreationTimestamp,
     :fingerprint
     {:global {:distinct-count 2000, :nil% 0.0},
      :type {:type/DateTime {:earliest "2016-06-01T18:12:52.802Z", :latest "2020-04-19T14:07:15.657Z"}}}}
    {:display_name "QUANTITY",
     :field_ref [:field "QUANTITY" {:base-type :type/Integer}],
     :name "QUANTITY",
     :base_type :type/Integer,
     :effective_type :type/Integer,
     :semantic_type :type/Quantity,
     :fingerprint
     {:global {:distinct-count 27, :nil% 0.0},
      :type
      {:type/Number
       {:min 0.0, :q1 1.7680340018414042, :q3 5.078814523684541, :max 68.0, :sd 3.5020851003402265, :avg 3.6885}}}}
    {:display_name "ID",
     :field_ref [:field "ID_2" {:base-type :type/BigInteger}],
     :name "ID",
     :base_type :type/BigInteger,
     :effective_type :type/BigInteger,
     :semantic_type :type/PK,
     :fingerprint nil}
    {:display_name "EAN",
     :field_ref [:field "EAN" {:base-type :type/Text}],
     :name "EAN",
     :base_type :type/Text,
     :effective_type :type/Text,
     :semantic_type nil,
     :fingerprint
     {:global {:distinct-count 200, :nil% 0.0},
      :type
      {:type/Text
       {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 13.0}}}}
    {:display_name "TITLE",
     :field_ref [:field "TITLE" {:base-type :type/Text}],
     :name "TITLE",
     :base_type :type/Text,
     :effective_type :type/Text,
     :semantic_type :type/Title,
     :fingerprint
     {:global {:distinct-count 199, :nil% 0.0},
      :type
      {:type/Text
       {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 21.4535}}}}
    {:display_name "CATEGORY",
     :field_ref [:field "CATEGORY" {:base-type :type/Text}],
     :name "CATEGORY",
     :base_type :type/Text,
     :effective_type :type/Text,
     :semantic_type nil,
     :fingerprint
     {:global {:distinct-count 4, :nil% 0.0},
      :type
      {:type/Text
       {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 6.3835}}}}
    {:display_name "VENDOR",
     :field_ref [:field "VENDOR" {:base-type :type/Text}],
     :name "VENDOR",
     :base_type :type/Text,
     :effective_type :type/Text,
     :semantic_type :type/Company,
     :fingerprint
     {:global {:distinct-count 200, :nil% 0.0},
      :type
      {:type/Text
       {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 20.517}}}}
    {:display_name "PRICE",
     :field_ref [:field "PRICE" {:base-type :type/Float}],
     :name "PRICE",
     :base_type :type/Float,
     :effective_type :type/Float,
     :semantic_type nil,
     :fingerprint
     {:global {:distinct-count 170, :nil% 0.0},
      :type
      {:type/Number
       {:min 15.691943673970439,
        :q1 37.70917044134707,
        :q3 76.19314929464217,
        :max 98.81933684368194,
        :sd 21.680952540957552,
        :avg 56.384908294046845}}}}
    {:display_name "RATING",
     :field_ref [:field "RATING" {:base-type :type/Float}],
     :name "RATING",
     :base_type :type/Float,
     :effective_type :type/Float,
     :semantic_type :type/Score,
     :fingerprint
     {:global {:distinct-count 23, :nil% 0.0},
      :type
      {:type/Number {:min 0.0, :q1 3.51, :q3 4.2234910866887745, :max 5.0, :sd 1.367470396441024, :avg 3.45545}}}}
    {:display_name "CREATED_AT",
     :field_ref [:field "CREATED_AT_2" {:base-type :type/DateTime, :temporal-unit :default}],
     :name "CREATED_AT",
     :base_type :type/DateTime,
     :effective_type :type/DateTime,
     :semantic_type :type/CreationTimestamp,
     :fingerprint
     {:global {:distinct-count 200, :nil% 0.0},
      :type {:type/DateTime {:earliest "2016-04-26T19:29:55.147Z", :latest "2019-04-15T13:34:19.931Z"}}}}],
   :fields
   [[:field "ID" {:base-type :type/BigInteger}]
    [:field "USER_ID" {:base-type :type/Integer}]
    [:field "PRODUCT_ID" {:base-type :type/Integer}]
    [:field "SUBTOTAL" {:base-type :type/Float}]
    [:field "TAX" {:base-type :type/Float}]
    [:field "TOTAL" {:base-type :type/Float}]
    [:field "DISCOUNT" {:base-type :type/Float}]
    [:field "CREATED_AT" {:base-type :type/DateTime, :temporal-unit :default}]
    [:field "QUANTITY" {:base-type :type/Integer}]
    [:field "ID_2" {:base-type :type/BigInteger}]
    [:field "EAN" {:base-type :type/Text}]
    [:field "TITLE" {:base-type :type/Text}]
    [:field "CATEGORY" {:base-type :type/Text}]
    [:field "VENDOR" {:base-type :type/Text}]
    [:field "PRICE" {:base-type :type/Float}]
    [:field "RATING" {:base-type :type/Float}]
    [:field "CREATED_AT_2" {:base-type :type/DateTime, :temporal-unit :default}]],
   :source-query
   {:params [], :native "SELECT *\nFROM Orders\nLEFT JOIN Products\nON Orders.product_id = Products.id\nWHERE 1 = 1;"},
   :limit 1048575,
   :metabase.query-processor.middleware.limit/original-limit nil},
  :type :query,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info {:executed-by 1, :context :ad-hoc, :card-id 5}},
 :data {:rows [], :cols []}}
```

**Information about your Metabase Installation:**

Your browser and the version: Safari 15.3
Your operating system: OSX 12.3.1
Your databases: Postgres
Metabase version: Current master (91b635deef4e05d71965c7525382328d6f30f788)

**Severity**
Not sure

**Additional context**
Still able to explore results with simpler query like: `select * from products where {{CATEGORY}}`

**Comment by flamber** [comment] 2022-05-10 14:21
Duplicate of #18475

**Closed by flamber** 2022-05-10 14:21 UTC
Labels: Type:Bug, .Needs Triage
