### ISSUE TITLE
Native question filter widget reordering doesn't work

### ISSUE THREAD

**Issue by fetanchaud** [metabase/metabase#9357] opened 2019-01-31 16:42 UTC
Hi all,

In the latest version,

Raw question filters have handles, but they do not work: 
you can move the filter, but when dropped, it comes back to its first place.

Is it intended behaviour ?

Best regards,

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2019-01-31 17:21
Hmmm.... I was searching for an existing bug on this, because I knew I had seen it before, but it turns out that it was only reported in the forum:
https://discourse.metabase.com/t/variable-fields-reorganising-after-save-native-query/4716

You'll see an error in the console, when you drag and drop the filter/parameter:
```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at app-main.bundle.js?78262faa1c529a733077:5
    at n.updateIn (vendor.bundle.js?78262faa1c529a733077:12)
    at t.value (app-main.bundle.js?78262faa1c529a733077:5)
    at n.setParameterIndex (app-main.bundle.js?78262faa1c529a733077:5)
    at r.handleSortEnd (app-main.bundle.js?78262faa1c529a733077:5)
    at e.handleSortEnd (vendor.bundle.js?78262faa1c529a733077:189)
```

**Comment by mazameli** [comment] 2019-10-10 20:57
I'm clarifying the title and bumping this up in priority given the number of folks who are experiencing this.

**Comment by nimeshnischal** [comment] 2019-11-22 17:44
On v0.32.9

Using native query, when I'm trying to drag and drop a filter, I get the following error in the console:

app-main.bundle.js?0d1325582067a4b57db2:5

Uncaught TypeError: Cannot read property 'id' of undefined
    at r.handleSortEnd (app-main.bundle.js?0d1325582067a4b57db2:5)
    at t.handleSortEnd (vendor.bundle.js?0d1325582067a4b57db2:1)
r.handleSortEnd @ app-main.bundle.js?0d1325582067a4b57db2:5
t.handleSortEnd @ vendor.bundle.js?0d1325582067a4b57db2:1

**Comment by walterl** [comment] 2020-03-13 21:28
On current `master` (0.35.0-RC) I see a different error:

```
NativeQuery.js:227 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at NativeQuery.js:227
    at e.updateIn (icepick.min.js:1)
    at NativeQuery.setParameterIndex (NativeQuery.js:226)
    at NativeQueryEditor._this.setParameterIndex (NativeQueryEditor.jsx:119)
    at Parameters._this.handleSortEnd (Parameters.jsx:130)
    at _this.handleSortEnd (index.js:329)
(anonymous) @ NativeQuery.js:227
e.updateIn @ icepick.min.js:1
setParameterIndex @ NativeQuery.js:226
NativeQueryEditor._this.setParameterIndex @ NativeQueryEditor.jsx:119
Parameters._this.handleSortEnd @ Parameters.jsx:130
_this.handleSortEnd @ index.js:329
```

**Comment by marcoruggine** [comment] 2020-04-23 12:21
Any news on this? I have been haunted by this nightmare for a long time...

**Comment by anton-khodak** [comment] 2020-06-14 12:50
I get a different error message when trying to reorder fields  (v0.35.3)
```
TypeError: can't convert undefined to object 
    app-main.bundle.js:5:317134
    value http://localhost:3000/app/dist/app-main.bundle.js?f24695780b695904f509:5
    updateIn http://localhost:3000/app/dist/vendor.bundle.js?f24695780b695904f509:1
    value http://localhost:3000/app/dist/app-main.bundle.js?f24695780b695904f509:5
    setParameterIndex http://localhost:3000/app/dist/app-main.bundle.js?f24695780b695904f509:5
    handleSortEnd http://localhost:3000/app/dist/app-main.bundle.js?f24695780b695904f509:5
    handleSortEnd http://localhost:3000/app/dist/vendor.bundle.js?f24695780b695904f509:1
```

**Comment by nemanjaglumac** [comment] 2021-02-24 18:47
Fixed in #14952.

**Closed by nemanjaglumac** 2021-02-24 18:47 UTC
Labels: Priority:P2, Querying/Native, Querying/Parameters & Variables, Type:Bug

**Comment by richxrich** [comment] 2021-03-25 06:08
On v0.38.2 it is not saving the psotion and rearranging on save again.

**Comment by flamber** [comment] 2021-03-25 08:42
@richxrich It works, when I'm testing it, but if you have more than 8 filters, then you're seeing this issue #5136

**Comment by richxrich** [comment] 2021-03-25 11:36
> @richxrich It works, when I'm testing it, but if you have more than 8 filters, then you're seeing this issue #5136

Yes you are correct, over 8 parameters they save in their own order and sometimes other options (like the chart type) doesn't save.

**Comment by Koojav** [comment] 2021-12-14 14:07
It's still broken in 0.41.4

**Comment by flamber** [comment] 2021-12-14 14:19
@Koojav What is broken? SQL filter widgets, when you have more than 8, which has it's own issue #5136 ?
This issue is closed, if you have found a regression, then create a new issue with steps-to-reproduce and other details requested.
