### ISSUE TITLE
occurs error when input a static string to expression in custom column

### ISSUE THREAD

**Issue by jodotlearn** [metabase/metabase#41718] opened 2024-04-23 08:41 UTC
### Describe the bug

occurs error when input a static string to expression in custom column, the same custom column expression in v0.48 works fine.
A sample is as follow, if cursor leaves the "expression" field (pic1), it will redirect to error page (pic2).

pic1.
![image](https://github.com/metabase/metabase/assets/8278560/22e76ad2-f952-4764-9598-34cc40503eca)

pic2.
![image](https://github.com/metabase/metabase/assets/8278560/cdf7e1ed-cfe8-4922-9fc8-84a460611581)

### To Reproduce

1. New a Question and choose any data
2. Add a custom column, and type any static string with double quote in expression field
3. Click the next field or other space (means to make the cursor not focus on the expression field)

### Information about your Metabase installation

```JSON
- Metabase version: v0.49.4
- Database: PostgreSQL
```

### Severity

blocking some key users

**Comment by paoliniluis** [comment] 2024-04-23 08:44
duplicate of https://github.com/metabase/metabase/issues/34776

**Closed by paoliniluis** 2024-04-23 08:44 UTC
Labels: Type:Bug, .Needs Triage
