### ISSUE TITLE
Equivalent of "Send email now" button for Slack

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#17424] opened 2021-08-11 22:41 UTC
When you configure an email dashboard subscription there's a "Send email now" button, but there's no equivalent button for Slack.

Email             |  Slack
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/32746338/129112793-fa668aa1-ef4b-4dd2-b714-059c4fea84b5.png)  |  ![](https://user-images.githubusercontent.com/32746338/129112888-cd328d7b-0c88-4e41-9e13-07d1aea231c9.png)

**Comment by flamber** [comment] 2021-08-12 08:34
Duplicate of #14515

**Closed by flamber** 2021-08-12 08:34 UTC
Labels: Type:New Feature, .Needs Triage
