### ISSUE TITLE
Unable to Filter Array Column - Postgres

### ISSUE THREAD

**Issue by MrChadMWood** [metabase/metabase#40688] opened 2024-03-27 16:34 UTC
### Describe the bug

Attempting to filter an array column on Postgres results in error:
![image](https://github.com/metabase/metabase/assets/90083658/923fda87-3489-4f37-b743-6e1dab42e75d)

### To Reproduce

Attempt to filter a column defined as `VARCHAR[]`.
Note that in my case, the column is created in a view with `ARRAY_AGG()`. Not sure if that matters.

### Expected behavior

The filter should not cause error

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "6.1.55-75.123.amzn2023.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-14",
      "tag": "v0.49.0",
      "hash": "46c668b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Low

**Comment by paoliniluis** [comment] 2024-03-27 16:36
duplicate of https://github.com/metabase/metabase/issues/18108

**Closed by paoliniluis** 2024-03-27 16:36 UTC
Labels: Type:Bug, .Needs Triage
