### ISSUE TITLE
when fetching rows, show columns in the same order as in table, not alphabetical order

### ISSUE THREAD

**Issue by raghotham** [metabase/metabase#3167] opened 2016-08-11 06:17 UTC
*  I am using the chrome browser.
*  My computer's OS is mac.
*  I'm running Metabase AWS [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.] and it is using the postgres database.
*  My data is in a Redshift database. 
*  My Metabase version is 0.18.

**Comment by camsaul** [comment] 2016-09-03 01:06
Hi @raghotham, it sounds like this is a duplicate of #2821. This was fixed by #2832, which shipped as part of Metabase 0.18.1. In #2931, which shipped as part of Metabase 0.19.0, we also added new options that let you order columns any way you like. [Upgrade to a newer version of Metabase](http://www.metabase.com/docs/latest/operations-guide/start.html#upgrading-metabase) and enjoy the new awesomeness! 

Closing as duplicate

**Closed by camsaul** 2016-09-03 01:06 UTC
Labels: Duplicate

**Comment by adrianON** [comment] 2017-02-08 21:25
Hello everyone,  I am running 0.22.2, using Postgres 9.4 and I see the same problem.  Columns are ordered alphabetically (A,B,C etc), I also do not see any ability in the Admin panel to modify column order.  What am I missing?

**Comment by kreno** [comment] 2017-10-27 23:03
![gear](https://user-images.githubusercontent.com/4562607/32128116-920aba30-bb38-11e7-9264-a3176b8cc8a0.png)
Click on the gear, see pic.  Once you're in that section, you can drag the column names up and down.  I couldn't find it either.
