### ISSUE TITLE
Change nashorn loading for java 15+

### ISSUE THREAD

**Issue by antoinep92** [metabase/metabase#16793] opened 2021-06-28 10:42 UTC
**Describe the bug**
Metabase uses nashorn scripting engine which is included in JDK but deprecated since java 11, and removed in java 15. This means we can't run metabase.jar with OpenJDK 15+.

Nashorn is now available as an external dependnecy, but just adding the jar at runtime is not enough because the package changed from `jdk.nashorn` (native, deprecated) and `org.openjdk.nashorn` (additional jar).

I labelled as a bug because metabase docs recommend using the latest version of OpenJDK, and that doesn't work anymore (since java 16 was released).

**Logs**
```
Exception in thread "main" java.lang.ExceptionInInitializerError
   ...
Caused by: java.lang.ClassNotFoundException: jdk.nashorn.api.scripting.JSObject
```

**To Reproduce**
Steps to reproduce the behavior: run:
```
java16 -jar metabase.jar -cp nashorn.jar
```
(fails with or without -cp)

**Expected behavior**
As explained [here](https://github.com/szegedi/nashorn/wiki/Using-Nashorn-with-different-Java-versions), the external dependency can be used since java 11, and also works with java >15. So the code can be made to work with java 11+

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: crashes before getting online
- Your operating system: ArchLinux x64, linux 5.1.10, libc 2.33
- Your databases: sqlite
- Metabase version: tested 0.39.4 and 0.34.3
- Metabase hosting environment: jar on OpenJDK 16
- Metabase internal database: H2

**Severity**
Not critical, but blocking java upgrade on our stack

**Comment by flamber** [comment] 2021-06-28 11:14
Duplicate of #13881 - fixed in upcoming 0.40.0

**Closed by flamber** 2021-06-28 11:14 UTC
Labels: .Needs Triage, Type:Bug
