### ISSUE TITLE
More flexible monthly dates for pulses / subscriptions

### ISSUE THREAD

**Issue by Torx999** [metabase/metabase#16979] opened 2021-07-12 09:47 UTC
Hello Team,

we are trying to implement a dashboard subscription/pulse to be sent every 4th day of the month, but there is no possibility to get it working. There is only possible to choose between first/last and middle of the month. Is it possible to solve this task?

Thanks & regards
Sergey

**Comment by flamber** [comment] 2021-07-12 10:19
Duplicate of #3846

**Closed by flamber** 2021-07-12 10:19 UTC
Labels: .Needs Triage, Type:New Feature
