### ISSUE TITLE
Visualization type gets reset to "Table" (different scenarios)

### ISSUE THREAD

**Issue by antoine-lizee** [metabase/metabase#12361] opened 2020-04-20 22:15 UTC
**Describe the bug**
Getting an error in a SQL query (eg: a column name changed) makes it be back to "table" visualization mode.

**Logs**
Nothing special

**To Reproduce**
1. Go to a SQL (edit:) or query-builder question that is a graph
2. Change the query to make it bug, for instance having a wrong column name
3. Play the query to get the results, see the error
4. Fix the error
5. Play the query, you're in table vizualisation mode.

[edit:] Other variant:
1. Create quickly a graph from a table
2. Refresh the tab, duplicate it, have your tab suspended by a browser plugin, or **share the link to a coworker**
3. The visualization is back to table mode

You need to get back in the proper visualization mode to get everything back again.

**Expected behavior**
Don't get stuck in the table visualization mode just because there is an error. Stay on the current mode, but switch to "data" view. instead of visualization view.

**Screenshots**

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_242-heroku-b08",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_242-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.242-b08",
    "os.name": "Linux",
    "os.version": "4.4.0-1062-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift",
      "h2"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.16"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.2",
      "date": "2020-04-10",
      "branch": "release-0.35.x",
      "hash": "f3b2857"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**
Severity is high. It's not been here forever, I think it's one of the secret gifts of the 0.34 :-) (but not sure, might be 0.35). Impact:
- when iterating on a complicated query with graphs, a few unneeded clicks and a poor UX
- [**more important**]: when fixing an existing query made wrong by underlying data changes, it's impossible to fix the question entirely because you have to "guess" if there was a visualization before and which one.
- [edit:] [**most important**]: you cannot share a question with a link to a coworker.

**Comment by flamber** [comment] 2020-04-21 08:02
This is likely a duplicate of #11960. And related to #11218 and #11675.
Leaving this open for now, since it feels like it's getting worse since 0.34.0

**Comment by antoine-lizee** [comment] 2020-04-22 16:51
After interacting with MB a lot in the last two days, here is more info:

This is linked to #11960 but not a duplicate: it got much worse than what is described in the OP there (it happens in much more cases)

I don't see how it could be linked to #11218 and #11675, but I might be missing context

It is actually much worse than the initial description above:
- the visualization comes back to Table mode whatever the type of question (editor or Query Builder)
- the visualization comes back to Table mode in any unsaved question if you refresh or share the link. It shows the same behvaiour than saved questions that have an error: the visualization settings are saved, but the visualization comes back to table mode. **This is a big deal because it makes sharing unsaved questions impossible** if they are anything else but a table.

-> I would revise and increase the severity of the bug I shared initially from "low" to "medium" or even "high".

**Comment by flamber** [comment] 2020-04-22 17:25
@antoine-lizee 
I'm not seeing questions resetting to table, when sharing an unsaved question. Can you help me reproduce that? As you know, the more info we have on various ways to reproduce, the more test cases can be made, so once this is fixed, then it won't creep back.

**Comment by antoine-lizee** [comment] 2020-05-06 18:32
@flamber sorry for the latency:
>Can you help me reproduce that?

I just reproduced it for SQL editor questions.
- "Write SQL" on the top right
- create a group by question with a sum per month (for instance
- select line visualization
- Refresh

--

I came here because I found another manifestation of this bug: if you are on a dashboard with a filter, clicking on a question that has a dashboard filter active will reset the visualization to table (because it's not a saved question anymore). It just bit me with a Query-builder question integrated in a dashboard with a "category" filter. It increased again a notch the "severity" of the bug.

**Comment by flamber** [comment] 2020-05-07 09:48
@antoine-lizee Okay, great, I can reproduce with:
1. SQL Sample Dataset:
```
SELECT parsedatetime(formatdatetime("PUBLIC"."ORDERS"."CREATED_AT", 'yyyyMM'), 'yyyyMM') AS "CREATED_AT", sum("PUBLIC"."ORDERS"."TOTAL") AS "sum"
FROM "PUBLIC"."ORDERS"
GROUP BY parsedatetime(formatdatetime("PUBLIC"."ORDERS"."CREATED_AT", 'yyyyMM'), 'yyyyMM')
ORDER BY parsedatetime(formatdatetime("PUBLIC"."ORDERS"."CREATED_AT", 'yyyyMM'), 'yyyyMM') ASC
```
2. Visualization as Line
3. Refresh or open URL in new tab, returns to Table visualization, even though the hash actually contains `"display":"line"`

I can see that Paul is looking into most of these issues now, so hopefully we'll have a fix soon.

**Closed** 2020-05-14 15:14 UTC
Labels: Priority:P2, Type:Bug, Visualization/
