### ISSUE TITLE
[`result_metadata`] Implicit binning on longitude from SQL question results in error

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16672] opened 2021-06-18 13:05 UTC
As part of on ongoing process of documenting and covering binning issues (#16387), I noticed a few irregularities that are not strictly bugs, but definitely feel weird. Although the root cause for this issue is probably very similar (related) to #16670 and #16671, this one is more severe because it results in an error.

To reproduce:
1. Save `select * from PEOPLE` as question ("SQL People")
2. Create a new (simple) question using the previously saved one ("SQL People")
3. Click on the table header cell with `LONGITUDE`
4. Choose "Distribution"
5. The query fails with the `not,Integer greater than zero,0` error

You can reach the same error by using Custom question
1. Create new question > Custom > Saved > Choose "SQL People"
2. Count of rows, and then click "Pick a column to group by"
3. Popover opens, click on `LONGITUDE` without choosing the bucket size (implicit auto binning)

![image](https://user-images.githubusercontent.com/31325167/122562445-5e651080-d043-11eb-9eea-05e1e30edf8a.png)

As the cherry on top, here's the video that documents the full circle of errors related to SQL longitude.
1. Error related to the implicit Auto binning
2. Error related to the explicit binning (simple question / sidebar)
3. Explicit binning drops the column (custom question / notebook)

https://user-images.githubusercontent.com/31325167/122565007-48a51a80-d046-11eb-8b08-14430977153a.mp4

**Comment by flamber** [comment] 2021-06-18 13:13
Likely a duplicate of #13914

**Comment by nemanjaglumac** [comment] 2021-06-23 11:06
This problem/solution behind this is `result_metadata` as well as behind https://github.com/metabase/metabase/issues/16671#issuecomment-864015639 and https://github.com/metabase/metabase/pull/16707#issuecomment-866126310.

Running the SQL query first (result metadata loads) results in the correct result:
![image](https://user-images.githubusercontent.com/31325167/123086474-c17bec00-d423-11eb-8133-1d33c94b020e.png)

**Comment by nemanjaglumac** [comment] 2023-11-08 13:13
This seems to have been fixed in `master` at d35c779976ae6bd79369e9cc6bec8540908f37d2

**Closed** 2023-11-14 20:41 UTC
Labels: Type:Bug, Priority:P3, Querying/Processor, .Backend, .Team/QueryProcessor, .Wanted: MLv2, Querying/Drill Thrus
