### ISSUE TITLE
Assert failed: Unable to connect to Metabase h2 DB.

### ISSUE THREAD

**Issue by Leoat12** [metabase/metabase#6510] opened 2017-11-30 12:13 UTC
**Browser:**  Opera 49.0.2725.47, Chrome 62.0.3202 or Firefox 57.0
**Operating System:** Windows 7 Ultimate Service Pack 1
**Databases:** SQL Server
Metabase version: 0.26.2
Metabase hosting environment: Metabase.jar on Windows Server 2012 R2
Metabase internal database: H2

Steps:

1) Shut down Metabase
2) Start Metabase
3) The following error appears:

`11-30 09:53:14 ←[1mINFO metabase.util←[0m :: Loading Metabase...
11-30 09:53:18 ←[1mINFO util.encryption←[0m :: DB details encryption is DISABLED for this Metabase instance.
See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
for more information.
11-30 09:53:30 ←[1mINFO metabase.core←[0m :: Starting Metabase in STANDALONE mode
11-30 09:53:30 ←[1mINFO metabase.core←[0m :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

11-30 09:53:30 ←[1mINFO metabase.core←[0m :: Starting Metabase version v0.26.2 (3b65f11 release-0.26.2) ...
11-30 09:53:30 ←[1mINFO metabase.core←[0m :: System timezone is 'America/Sao_Paulo' ...
11-30 09:53:31 ←[1mWARN metabase.driver←[0m :: No -init-driver function found for 'metabase.driver.google'
11-30 09:53:31 ←[1mINFO metabase.core←[0m :: Setting up and migrating Metabase DB. Please sit tight, this may take a min
ute...
11-30 09:53:31 ←[1mINFO metabase.db←[0m :: Verifying h2 Database Connection ...
11-30 09:53:36 ←[1mERROR metabase.driver←[0m :: Failed to connect to database: Timed out after 5000 milliseconds.
java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.drive
r/can-connect-with-details?)) engine details))
        at metabase.db$verify_db_connection.invokeStatic(db.clj:334)
        at metabase.db$verify_db_connection.invoke(db.clj:327)
        at metabase.db$verify_db_connection.invokeStatic(db.clj:330)
        at metabase.db$verify_db_connection.invoke(db.clj:327)
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:382)
        at metabase.db$setup_db_BANG_.doInvoke(db.clj:376)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at metabase.core$init_BANG_.invokeStatic(core.clj:103)
        at metabase.core$init_BANG_.invoke(core.clj:82)
        at metabase.core$start_normally.invokeStatic(core.clj:187)
        at metabase.core$start_normally.invoke(core.clj:181)
        at metabase.core$_main.invokeStatic(core.clj:285)
        at metabase.core$_main.doInvoke(core.clj:280)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
11-30 09:53:36 ←[1mERROR metabase.core←[0m :: Metabase Initialization FAILED:  Assert failed: Unable to connect to Metab
ase h2 DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.drive
r/can-connect-with-details?)) engine details))
11-30 09:53:36 ←[1mINFO metabase.core←[0m :: Metabase Shutting Down ...
11-30 09:53:36 ←[1mINFO metabase.core←[0m :: Metabase Shutdown COMPLETE`

4) Delete metabase.db.trace
5) Try start again and it comes back to life.

It started recently without any reason I can think of.

**Comment by toybaelescione** [comment] 2018-05-31 09:19
Solved by try to connect to h2 shell, then disconnect. OS is Centos 7
`java -cp metabase.jar org.h2.tools.Shell -url jdbc:h2:/opt/metabase/metabase.db`

**Comment by kuil09** [comment] 2018-07-26 01:47
I have same problem. But I'm running Metabase on Docker

**Comment by jornh** [comment] 2018-07-26 18:40
@kuil09 probably easiest to download a copy of Metabase in the jar version and do like 
https://github.com/metabase/metabase/issues/6510#issuecomment-393469491 (make sure you have proper backup 😀)

**Comment by snarfed** [comment] 2018-12-18 23:42
i had to debug the same problem recently. i can add some info.

we use postgres for our prod metabase db. however, we also run a small peripheral external facing app on metabase, https://data.color.com/v1/ . it's basically read only, so we made the decision to run it on h2, with a regular automatic backup.

its metabase died the other night. on restart, it failed with the same error here, notably:
```
INFO metabase.db :: Verifying h2 Database Connection ...
ERROR metabase.driver :: Failed to connect to database: Timed out after 5000 milliseconds.
java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
```

`metabase.db.mv.db` had grown surprisingly large, 1.6G for a single dashboard and a couple dozen questions with small to medium result sizes. i'd configured its query caching generously, but still, 1.6G was surprising. i tried running metabase with the backup db file instead; same error.

i initially thought both files had been corrupted, but i eventually realized that they were actually fine, except they were so big that H2 itself took longer than 5s to load them, at which point metabase timed out and gave up.

i did some research and eventually found that this is a known H2 behavior: while a db is connected and open, its file on disk may grow without bound. it's not compacted or defragmented until the client disconnects (assuming it sets `DEFRAG_ALWAYS=true`). https://github.com/h2database/h2database/issues/301 

i confirmed by opening the db and running the`SHUTDOWN DEFRAG` command. the file immediately shrank to 75M, and metabase happily loaded it within 5s and started ok.

evidently H2 has no way to defrag a db while it's open; that's an existing feature request: https://stackoverflow.com/questions/7544979. `CHECKPOINT` might help some, not sure.

so for long-running H2-backed metabase instances, i guess the options are 1) try `CHECKPOINT` and see if it helps, and if not, 2) reboot metabase periodically in order to defrag the H2 db file.

(...yes, i know, i know, i should just get off H2 already. i figured it would be ok for a read only instance with regular backups. guess not. 😁)

**Comment by snarfed** [comment] 2019-02-12 18:55
i finally got back to this. `CHECKPOINT` doesn't shrink the H2 file, at least for us, nor does `SHUTDOWN COMPACT`, but `SHUTDOWN DEFRAG` definitely works. so we now do that in a cron job, weekly:

```sh
pkill -9 java
java -cp metabase.jar org.h2.tools.Shell -url jdbc:h2:~/metabase.db -sql 'SHUTDOWN DEFRAG;'
~/metabase.sh
```

(`metabase.sh` just rotates logs and starts our metabase.)

**Comment by camsaul** [comment] 2019-02-12 19:34
@snarfed @Leoat12 we really don't recommend using H2 as the application database for a production Metabase deployment. We default to it mostly because it makes the product easy to evaluate. However as you have noticed here it is prone to doing things like eating up tons of memory or files getting corrupting without a clear reason. We recommend using Postgres, MySQL, or MariaDB instead.

We're not currently setting `DEFRAG_ALWAYS` as an H2 connection option but I'll add that to keep size in check so people don't need to manually run `SHUTDOWN DEFRAG`.

**Comment by snarfed** [comment] 2019-02-12 19:54
@camsaul thanks! yup, understood that H2 isn't for prod. i'd guessed it would be ok for a strictly read only, small deployment, but evidently it can't even do that ok. :trollface:

out of curiosity, afaik `DEFRAG_ALWAYS` would only help if metabase regularly closed and reopened its H2 db connection. does it do that?

**Comment by camsaul** [comment] 2019-02-12 21:42
@snarfed no, the H2 runs as part of the same JVM process that runs Metabase. So it would only help when shutting down Metabase.

**Comment by flamber** [comment] 2020-05-27 10:33
Closing, since this was likely caused by corrupted H2 application database. And there has been a few fixes since to mitigate some H2 issues.
H2 is not recommended for production:
https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html
https://www.metabase.com/docs/latest/troubleshooting-guide/application-database.html
https://discourse.metabase.com/t/metabase-db-cleanup/5079

**Closed by flamber** 2020-05-27 10:33 UTC
Labels: Operation/H2

**Comment by hiqiuyi** [comment] 2023-03-17 10:30
```
export MB_DB_CONNECTION_TIMEOUT_MS=50000
java -jar meatabase.jar
```
The default database connection is 5 seconds. You can make it bigger, like 50 seconds.

**Comment by ohadcn** [comment] 2023-06-04 22:52
I had similar problem
Turns out I was trying to run metabase from a backup made using a newer metabase version
