### ISSUE TITLE
Custom values in Dropdown List dashboard filter option is being used by Search List option

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#42364] opened 2024-05-07 20:43 UTC
### Describe the bug

In a dashboard filter, if you edit a Dropdown List to use custom values, and then switch to use the Search list, the search list will use the custom values instead of the values linked to the field filter. As Dropdown and Search lists are separate options, they should have nothing to do with each other. 

### To Reproduce

1. Add a field filter in a dashboard and map to a field
2. Select Dropdown list option and set custom values
3. Switch/select Search list
4. Save dashboard
5. Try searching in the field filter and it will only show the custom values instead of values linked to the table field.

### Expected behavior

Search list should always use values linked to the field -- and not custom values from Dropdown option as they are different options. 

### Information about your Metabase installation

```JSON
Master on Postgres
```

### Severity

Medium as fix isn't obvious. Confusing when switching drop dropdown with custom to search list and most users won't be able to figure out what is going on / think search list is broken

**Comment by ranquild** [comment] 2024-06-20 15:26
We don't reset custom source settings when going from Dropdown -> Search, that seems to be root cause here

**Comment by romeovs** [comment] 2024-07-12 09:19
AFAICT this is is the way this is suppossed to work, but maybe @mngr can weigh in?

**Comment by mngr** [comment] 2024-07-12 10:35
OK, so the problem here is not that we don't clear the custom values, but that we hide them behind the edit button which is linked to the option chosen (dropdown or search).
This is a UI problem, not the logic problem. This whole process of setting the filter options is so obscure that we have to redesign it completely.
@romeovs I would close this particular ticket as it is intended behavior indeed, but this is a valuable input @maxzheng to highlight the UI problems we have here.

**Closed** 2024-07-12 11:16 UTC
Labels: Type:Bug, Priority:P2, Querying/Parameters & Variables, .Frontend, .Product Input Needed, .Team/QueryingComponents

**Comment by maxzheng** [comment] 2024-07-12 17:01
@romeovs @mngr I don't understand how this is considered working as expected as the behavior does not make logical sense. So you have 2 filter options: Search & Custom. If you select Search, it uses the value linked to the db field (expected behavior). If you change to Custom and set a custom list of values, then it uses the custom list (expected behavior). Now if you switch back to Search, it is still using the custom list of values (and not the values linked to the db) -- this is unexpected behavior of the Search option, and therefore it's a bug. In order for a user to use the linked db value again, they would need to go back to Custom, clear the list, and then select Search again...

**Comment by mngr** [comment] 2024-07-12 17:06
@maxzheng both Search and Dropdown have the same options to set, either it's a custom list of values or linked to the db field - and this is set independently regardless of what you choose as a UI element
so basically what you selected from where to fetch the values is kept while you switching from Dropdown to Search and back

**Comment by maxzheng** [comment] 2024-07-12 17:12
@mngr Interesting. Did you guys changed how that worked? I remember they have different options but now both are the same. Since they are the same, then I guess it makes sense / it is working as expected.
