### ISSUE TITLE
Sending XLSX / CSV with Pulses instead only images

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#5813] opened 2017-08-24 16:18 UTC
There are some issues that was previews closed, but How about send as attach files (json / xlsx / csv) too instead only images? Using the same as manual download from question data.

**Comment by Rafaelathaydemello** [comment] 2017-08-29 07:46
Yes please - I have some regular updates I send via Slack but I have to send them in 2 different pictures! Pulses should be a bit more versatile when sending tables

**Comment by salsakran** [comment] 2017-09-07 00:05
dupe of #2623

**Closed by salsakran** 2017-09-07 00:05 UTC
