### ISSUE TITLE
Object detail page background overflow

### ISSUE THREAD

**Issue by omarchehab98** [metabase/metabase#9868] opened 2019-04-29 13:48 UTC
### Bug

- Your browser and the version: Chrome Version 73.0

- Your operating system: macOS Mojave 10.14.3

- Your databases: Postgres

- Metabase version: 0.32.5

- Metabase hosting environment: Heroku

- Metabase internal database: Postgres

- Navigate to question page

- Build a question that returns 1 result with sufficiently many rows to overflow past the viewport height

![biorender-metabase herokuapp com_question(iPad)](https://user-images.githubusercontent.com/12089120/56900193-2712fe80-6a8d-11e9-8bb0-6a760c852949.png)

- Scroll down

![biorender-metabase herokuapp com_question(iPad) (1)](https://user-images.githubusercontent.com/12089120/56900198-29755880-6a8d-11e9-81dd-abb568fb776c.png)

-------

**Comment by flamber** [comment] 2020-06-01 15:13
I cannot reproduce anymore on 0.35.4 - think it was fixed in 0.34

**Closed by flamber** 2020-06-01 15:13 UTC
Labels: Priority:P3, Querying/GUI, Type:Bug
