### ISSUE TITLE
Button "Done" outside the screen on dashboard

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#6188] opened 2017-10-17 16:12 UTC
Metabase 0.26.1

![image](https://user-images.githubusercontent.com/1708680/31676038-0d150a90-b36f-11e7-8f88-007c816ff522.png)

Or it is an easter egg? :)

**Comment by salsakran** [comment] 2017-10-18 22:43
What happens if you click it?

Also what browser/os versions are you on?

**Comment by mazameli** [comment] 2017-10-27 00:12
I can't reproduce this on 0.26.2 on Chrome on macOS. The only thing I'm seeing is inconsistent sizing/positioning of the box, maybe due to that PR we merged that trimmed down the height of the main nav?

![screen shot 2017-10-26 at 5 10 43 pm](https://user-images.githubusercontent.com/2223916/32082481-b763ce66-ba70-11e7-957a-a7ea2053268c.png)

![screen shot 2017-10-26 at 5 10 03 pm](https://user-images.githubusercontent.com/2223916/32082485-b9c38a84-ba70-11e7-8339-f3114a7e7c53.png)
 
![screen shot 2017-10-26 at 5 05 58 pm](https://user-images.githubusercontent.com/2223916/32082494-c38be7c8-ba70-11e7-98cc-e199b8003119.png)

**Comment by kdoh** [comment] 2017-10-27 00:19
@mazameli Ah yeah good catch I didn't realize that would be affected by trimming the nav down. I can cut something to look into that. 

As far as the done button goes the way to repro it is to use momentum scrolling, the rubber banding when you hit the top sometimes shows it. That to me says something is not properly un-mounting in the component when a user hits done, but since it's only discoverable if you really pull down I'm gonna say this is super low priority. 

The spacing on the confirmation shade is something we should fix quickly though. If I can fix this other thing while I'm in there then hey that's cool too.

**Comment by kdoh** [comment] 2019-07-05 18:41
I'm no longer able to reproduce this.

**Closed by kdoh** 2019-07-05 18:41 UTC
Labels: Bug, Priority/P3
