### ISSUE TITLE
UX Feedback: wasn't clear how to create a label

### ISSUE THREAD

**Issue by infomofo** [metabase/metabase#3837] opened 2016-11-30 20:45 UTC
I clicked on the "create labels to group and manage questions" section and nothing happened:

![image](https://cloud.githubusercontent.com/assets/539599/20770503/fd44cec8-b713-11e6-9648-dd2daa3a41c8.png)

then I tried putting my existing question in a label and the menu pops up but it's empty and doesn't have an option to create a new label:

![image](https://cloud.githubusercontent.com/assets/539599/20770482/e78e3592-b713-11e6-81e3-192680c8ee97.png)

Finally I clicked on the section header "Labels" and that is what triggers the creation but this was not intuitive.

I would recommend making the "Label As" dropdown have a "Create Label" option.  I would also make the icon and the words "Create labels to group and manage questions." clickable.

**Comment by mazameli** [comment] 2016-11-30 20:48
Totally agree, and sorry for the confusion. This is however a duplicate of #2533 (and partially #3163). Incidentally, we are currently working on improving and altering question organization in a big way.

**Closed** 2016-11-30 20:48 UTC
