### ISSUE TITLE
Sliding down query editor is a disaster

### ISSUE THREAD

**Issue by nshcylindo** [metabase/metabase#18889] opened 2021-11-08 10:05 UTC
**Describe the bug**
Now this animation with sliding down editor is true disaster in chrome/safari browsers on different Mac machines. Sometimes it stops midway, or hacks or just getting stuck not allowing me to explore results. 

It has been like this for at least 2 weeks. 

https://drive.google.com/file/d/1-SJyrtylefC9l3TMkw4h0HxlpKZtkYf4/view?usp=sharing

**To Reproduce**
1. Go to any heavy report (question)
2. Click on show editor
3. Click visualise

**Expected behavior**
It just shows me results with no animation, multilayer sliding or similar. 

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.12+7",
    "java.vendor": "Eclipse Foundation",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.12",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.12+7",
    "os.name": "Linux",
    "os.version": "4.14.219-164.354.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "mongo",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.9"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-10-21",
      "tag": "v1.41.1",
      "branch": "release-x.41.x",
      "hash": "68c0017"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Every time, happens always. Very annoying.

**Comment by flamber** [comment] 2021-11-08 10:14
Duplicate of #12378

**Closed by flamber** 2021-11-08 10:14 UTC
Labels: Type:Bug, .Needs Triage

**Comment by francisyan123** [comment] 2021-11-11 06:23
@flamber Is this bug in your plan lists? Please fix it ASAP.

**Comment by flamber** [comment] 2021-11-11 09:16
@francisyan123 Yes, it's a priority bug, but it's also very difficult to tackle - we're working on it.
