### ISSUE TITLE
Improve support for running on Google Cloud serverless platforms

### ISSUE THREAD

**Issue by jkeys089** [metabase/metabase#19270] opened 2021-12-08 20:10 UTC
**Is your feature request related to a problem? Please describe.**
When trying to deploy Metabase to Google App Engine we ran into issues getting connected to postgres (i.e. Google Cloud SQL). The preferred method for connecting to Cloud SQL from serverless platforms (e.g. App Engine / Cloud Run / Cloud Functions) in Google Cloud is via the [Cloud SQL Connector for Java](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory) which isn't currently supported in Metabase. We'd also like to be able to use the default service account credentials available to serverless platforms instead of explicitly creating new service account credentials for each data source (e.g. when connecting to BigQuery).

**Describe the solution you'd like**
Support a `MB_DB_CONNECTION_URI` value like: `jdbc:postgresql:///<db-name>?cloudSqlInstance=<instance-id>&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=<user>&password=<password>`.
Notice there is no host / port and we're instead relying on `socketFactory=com.google.cloud.sql.postgres.SocketFactory` from [Cloud SQL Connector for Java](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory). This is useful in serverless environments that provide default service account credentials.

**Describe alternatives you've considered**
For Cloud SQL it is possible to setup a [Serverless VPC Access connector](https://cloud.google.com/vpc/docs/configure-serverless-vpc-access) and connect directly to a Cloud SQL instance via a private IP. However, this complicates the setup and incurs additional cost for the same functionality.
For connecting to BigQuery, it is possible to provision separate service account credentials but these credentials are long-lived and must be managed separately. This incurs operational overhead and is less secure compared to utilizing default service account credentials available to serverless environments.

**How important is this feature to you?**
Utilizing default service account credentials is important to us from an operational perspective. We're not clojurians (currently) but we'd be happy to contribute these features as well as Google Cloud serverless documentation if there is interest.

**Additional context**
n/a

**Comment by flamber** [comment] 2021-12-08 20:17
Duplicate of #11414

**Closed by flamber** 2021-12-08 20:17 UTC
Labels: Type:New Feature, .Needs Triage
