### ISSUE TITLE
Question lineage when drilling through broken

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#5088] opened 2017-05-11 19:01 UTC
On `master` :-/

![screenshot 2017-05-11 12 01 07](https://cloud.githubusercontent.com/assets/18193/25966993/8ac1b7aa-3641-11e7-8654-5a2ce1d2cde2.png)

**Comment by attekei** [comment] 2017-05-11 19:22
Seems to be a regression caused by https://github.com/metabase/metabase/pull/5040 and applies only to visualization drill-through inside query builder (both dashboard drill-through and action widget actions don't cause the same problem).

**Comment by salsakran** [comment] 2017-06-01 18:21
fixed by #5208

**Closed by salsakran** 2017-06-01 18:21 UTC
Labels: Bug, Query Builder
