### ISSUE TITLE
Filtered Dashboard not refreshing correctly

### ISSUE THREAD

**Issue by TomUssery** [metabase/metabase#5132] opened 2017-05-17 20:30 UTC
We updated to 0.24 now our filter reports are not responding like before the update.

Prior to selecting a filter
![image](https://cloud.githubusercontent.com/assets/27392006/26174593/e9dedc0a-3b1d-11e7-8ae5-67242963e1f1.png)

After selecting a filter - the tiles that should not update are grayed out. 
![image](https://cloud.githubusercontent.com/assets/27392006/26174638/0fe1f4a0-3b1e-11e7-9d17-31bf9baf8a15.png)

**Comment by mazameli** [comment] 2017-05-19 22:41
Pretty sure this is a duplicate of https://github.com/metabase/metabase/issues/5081

Cards that aren't wired up to all active dashboard filters get faded out on purpose, but the team is discussing this behavior as we've heard from lots of users that this isn't expected.

**Closed by mazameli** 2017-05-19 22:41 UTC
Labels: Duplicate

**Comment by MiBaDK** [comment] 2017-07-06 08:33
HI @mazameli, any updates on this as a result of your discussions on the team?
