### ISSUE TITLE
Apply Reporting Timezone to the results of SQL queries

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2053] opened 2016-02-29 21:22 UTC
When displaying the results of a native SQL query it would be useful to take into account the reporting timezone global setting.

See conversation at http://discourse.metabase.com/t/problem-with-time-variable-timezone/242

**Comment by agilliland** [comment] 2016-02-29 23:34
This is a duplicate of #2034

**Closed by agilliland** 2016-02-29 23:34 UTC
Labels: Duplicate, Proposal
