### ISSUE TITLE
metabase application database: query_id in mb_instance_queryexecutions is always NULL

### ISSUE THREAD

**Issue by timabe** [metabase/metabase#2225] opened 2016-03-23 21:24 UTC
It would be very useful to know what cards are being called most for a metabase instance (to do a meta analysis of metabase usage. The field `query_id` in `mb_instance_queryexecutions` in the application database seems like it should be logging the card number, but it is null in each record. 

Example
`select COUNT(1) FROM mb_instance_queryexecutions where query_id IS NOT NULL`

Could even be a cool feature to ship a dashboard with this meta-analysis in each instance so users can see stats on who the most active users are, what the most common queries are, what queries take the most time, etc.

**Comment by camsaul** [comment] 2016-03-23 21:51
You mean the `query_queryexecution` table, right? 

`query_id` is actually just a relic from an older version of Metabase. I's a foreign key to the `query_query` table which is no longer used. As Metabase is pre-1.0, the internal database schema is in flux and there are still a few old tables that we haven't removed yet. We have an open ticket to remove unused fields and schemas like this one which might cause confusion: see #675.

For identifying slow queries, issue #609 has already been opened. 

Closing as duplicate of #609 / #675

**Closed by camsaul** 2016-03-23 21:51 UTC
