### ISSUE TITLE
Users without permissions to tables with columns included via FK can't fix errors caused by their lack of permissions

### ISSUE THREAD

**Issue by nickhamlin** [metabase/metabase#8765] opened 2018-10-24 18:38 UTC
- Your browser and the version: Chrome 69.0.3497.100
- Your operating system: OS X 10.12.6
- Your databases: MySQL
- Metabase version: 0.30.1
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

*Repeatable steps to reproduce the issue*
This one is a little complex to reproduce, so I'll try to use a simplified example based on how I just encountered this.

1. Create two tables. Let's say table X contains one column (x.id) and table Y contains its own id (y.id) and a foreign key to table X (y.x_id)
2. Create two users. Let's say Albert is an Admin and Bill is a regular user. Albert can access everything but Bill can only access table Y and NOT table x
3. Albert makes a question containing raw data from table Y and uses the table visualization settings menu (the little gear) to add x.id to his report (which is possible because of the FK relationship between the two).
4. Albert sends a link of the report to Bill
5. When Bill opens the report, he'll get a "there's a problem with your question" error. When he clicks to see more info, he sees a "permissions error" message. But, because the question doesn't run, the gear icon doesn't appear, so Bill has no way to resolve this permissions error (presumably by removing the columns from the table he's not allowed to see from the report).

I could imagine an argument that Bill shouldn't be able to modify the columns shown on the table because to do that he'd then have access to the column names (if not the data) in Table X (which his permissions don't allow). If that's the case, perhaps it would be better to automatically remove the columns that are causing the permissions error and then continue to render the table as normal? If that were the case, then at least Bill wouldn't be stonewalled at the error screen.

Thanks and please let me know if more info or clarification is helpful!

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2020-06-01 16:01
Steps to reproduce - 0.35.4:
1. Admin > Data Model > Sample Dataset > Orders > Product ID :gear: > "Display values" = "Use foreign key" "Title"
2. Admin > People > Create user "U1"
3. Admin > Permissions > Sample Dataset (View tables) > On "All Users" only set data access for Orders
4. Login as U1 > Browse Data > Sample Dataset > Orders - errors with
`You do not have permissions to run this query.`

<details><summary>stacktrace</summary>

```
06-01 17:50:39 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 4,
 :started_at (t/zoned-date-time "2020-06-01T17:50:39.115843+02:00[Europe/Copenhagen]"),
 :error_type :missing-required-permissions,
 :json_query {:database 4, :query {:source-table 11}, :type "query", :parameters [], :middleware {:add-default-userland-constraints? true}},
 :native nil,
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> query_processor.middleware.permissions$perms_exception.invokeStatic(permissions.clj:30)"
  "query_processor.middleware.permissions$perms_exception.invoke(permissions.clj:29)"
  "query_processor.middleware.permissions$fn__42280$check_ad_hoc_query_perms__42285$fn__42286.invoke(permissions.clj:43)"
  "query_processor.middleware.permissions$fn__42280$check_ad_hoc_query_perms__42285.invoke(permissions.clj:38)"
  "query_processor.middleware.permissions$fn__42312$check_query_permissions_STAR___42317$fn__42323.invoke(permissions.clj:54)"
  "query_processor.middleware.permissions$fn__42312$check_query_permissions_STAR___42317.invoke(permissions.clj:47)"
  "query_processor.middleware.permissions$check_query_permissions$fn__42338.invoke(permissions.clj:63)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__43813.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__42536.invoke(cumulative_aggregations.clj:61)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__44345.invoke(resolve_joins.clj:183)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39271.invoke(add_implicit_joins.clj:245)"
  "query_processor.middleware.limit$limit$fn__43135.invoke(limit.clj:38)"
  "query_processor.middleware.format_rows$format_rows$fn__43116.invoke(format_rows.clj:81)"
  "query_processor.middleware.desugar$desugar$fn__42602.invoke(desugar.clj:22)"
  "query_processor.middleware.binning$update_binning_strategy$fn__41628.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__42144.invoke(resolve_fields.clj:24)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__38807.invoke(add_dimension_projections.clj:272)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39027.invoke(add_implicit_clauses.clj:147)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39420.invoke(add_source_metadata.clj:105)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__44010.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__41269.invoke(auto_bucket_datetimes.clj:125)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__42191.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.parameters$substitute_parameters$fn__43795.invoke(parameters.clj:97)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__42243.invoke(resolve_referenced.clj:80)"
  "query_processor.middleware.expand_macros$expand_macros$fn__42858.invoke(expand_macros.clj:158)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__39451.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47166.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__44021$fn__44025.invoke(resolve_database_and_driver.clj:33)"
  "driver$do_with_driver.invokeStatic(driver.clj:61)"
  "driver$do_with_driver.invoke(driver.clj:57)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__44021.invoke(resolve_database_and_driver.clj:27)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__43064.invoke(fetch_source_query.clj:243)"
  "query_processor.middleware.store$initialize_store$fn__47175$fn__47176.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__47175.invoke(store.clj:10)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__42120.invoke(cache.clj:209)"
  "query_processor.middleware.validate$validate_query$fn__47184.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__43162.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39289.invoke(add_rows_truncated.clj:36)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47151.invoke(results_metadata.clj:128)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__42479.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__43884.invoke(process_userland_query.clj:136)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__42422.invoke(catch_exceptions.clj:174)"
  "query_processor.reducible$async_qp$qp_STAR___38090$thunk__38091.invoke(reducible.clj:101)"
  "query_processor.reducible$async_qp$qp_STAR___38090.invoke(reducible.clj:107)"
  "query_processor.reducible$sync_qp$qp_STAR___38099$fn__38102.invoke(reducible.clj:133)"
  "query_processor.reducible$sync_qp$qp_STAR___38099.invoke(reducible.clj:132)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:218)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:214)"
  "query_processor$fn__47350$process_query_and_save_execution_BANG___47359$fn__47362.invoke(query_processor.clj:233)"
  "query_processor$fn__47350$process_query_and_save_execution_BANG___47359.invoke(query_processor.clj:225)"
  "query_processor$fn__47394$process_query_and_save_with_max_results_constraints_BANG___47403$fn__47406.invoke(query_processor.clj:245)"
  "query_processor$fn__47394$process_query_and_save_with_max_results_constraints_BANG___47403.invoke(query_processor.clj:238)"
  "api.dataset$fn__50692$fn__50695.invoke(dataset.clj:52)"
  "query_processor.streaming$streaming_response_STAR_$fn__34128$fn__34129.invoke(streaming.clj:73)"
  "query_processor.streaming$streaming_response_STAR_$fn__34128.invoke(streaming.clj:72)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
  "async.streaming_response$do_f_async$fn__23118.invoke(streaming_response.clj:85)"],
 :context :ad-hoc,
 :error "You do not have permissions to run this query.",
 :row_count 0,
 :running_time 0,
 :preprocessed nil,
 :ex-data
 {:type :missing-required-permissions,
  :required-permissions #{"/db/4/schema/PUBLIC/table/11/query/" "/db/4/schema/PUBLIC/table/10/query/"},
  :actual-permissions #{"/collection/3/" "/db/4/schema/PUBLIC/table/11/" "/collection/9/read/" "/collection/2/read/"},
  :permissions-error? true},
 :data {:rows [], :cols []}}

06-01 17:50:39 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 511.1 ms (13 DB calls) App DB connections: 0/13 Jetty threads: 3/50 (3 idle, 0 queued) (121 total active threads) Queries in flight: 0 (0 queued)
```

</details>

Workaround is to set "Display values" = "Use original value"

Perhaps related to #12354

**Comment by iethree** [comment] 2023-12-20 20:00
Need some product input here:
- this might be working as intended?
- if there's a permissions error remapping values, we could automatically show original values, but that could lead to different users seeing different data 😢

**Comment by kamilmielnik** [comment] 2024-03-07 11:35
Reproducible on `master` at 78cb28816a.

It's not clear what we should do here, it needs discussion.

----

> * this might be working as intended?

I agree. The "show me as much data as I'm allowed to see" behavior seems unsafe and potentially confusing/misleading.

**Comment by ranquild** [comment] 2024-06-26 19:23
Closed as "working as intended".

**Closed by ranquild** 2024-06-26 19:23 UTC
Labels: Type:Bug, Priority:P3, Administration/Permissions, Querying/GUI, Querying/Remapping, .Team/QueryingComponents
