### ISSUE TITLE
Collection for dashboards

### ISSUE THREAD

**Issue by paulozip** [metabase/metabase#7615] opened 2018-05-10 20:30 UTC
As time goes by and the number of dashboards increases, it becomes a little difficult to find specific dashboards created for teams. For instance, let's assume that a Customer Success team would like to know what dashboards were created for their team. For that, they type a keyword that is relevant to their team and look at results, but they might be missing something. Currently, I'm working around the problem by naming the dashboard with team tags (e.g **[CUSTOMER SUCCESS]** - Churn rate).

However, **it would be great if we could organize dashboards just like we organize questions: by creating collections**. Metabase could be an option to store a specific dashboard in dashboards collections, making it easier to teams find and explore dashboards created for them.

Thank you guys

 
⚠️ Please click the 👍 reaction instead of leaving a +1 or 👍 comment

**Comment by mazameli** [comment] 2018-05-10 20:36
Yep, we wholeheartedly agree: we're working on this right now in https://github.com/metabase/metabase/pull/7358

The plan is that saved questions, dashboards, pulses, official metrics and segments, and even other collections will now be able to be saved in any collection.

Closing this issue as a duplicate of #7515.

**Closed by mazameli** 2018-05-10 20:36 UTC
