### ISSUE TITLE
"Distinct, non-empty sequence of Field clauses")}  How can this problem be solved?

### ISSUE THREAD

**Issue by dt1018614769** [metabase/metabase#11332] opened 2019-11-16 10:40 UTC
"Distinct, non-empty sequence of Field clauses")}  How can this problem be solved?

This problem occurred in my installation of jar and docker. I was querying mongodb

How should solve excuse me

:class clojure.lang.ExceptionInfo,
 :error "Distinct, non-empty sequence of Field clauses",
 :stacktrace
 ("--> query_processor.middleware.add_implicit_clauses$fn__35061$sorted_implicit_fields_for_table__35066.invoke(add_implicit_clauses.clj:47)"
  "query_processor.middleware.add_implicit_clauses$fn__35169$add_implicit_fields__35174$fn__35178.invoke(add_implicit_clauses.clj:92)"
  "query_processor.middleware.add_implicit_clauses$fn__35169$add_implicit_fields__35174.invoke(add_implicit_clauses.clj:85)"
  "query_processor.middleware.add_implicit_clauses$fn__35257$add_implicit_mbql_clauses__35262$fn__35266.invoke(add_implicit_clauses.clj:129)"
  "query_processor.middleware.add_implicit_clauses$fn__35257$add_implicit_mbql_clauses__35262.invoke(add_implicit_clauses.clj:125)"
  "query_processor.middleware.add_implicit_clauses$maybe_add_implicit_clauses.invokeStatic(add_implicit_clauses.clj:140)"
  "query_processor.middleware.add_implicit_clauses$maybe_add_implicit_clauses.invoke(add_implicit_clauses.clj:136)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__35684.invoke(add_source_metadata.clj:107)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__41181.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__35531.invoke(add_row_count_and_status.clj:16)"
  "driver.mongo$eval2143$fn__2144$fn__2146$f__857__auto____2148.invoke(mongo.clj:64)"
  "driver.mongo.util$_with_mongo_connection$fn__848.invoke(util.clj:205)"
  "util.ssh$with_ssh_tunnel_STAR_.invokeStatic(ssh.clj:106)"
  "util.ssh$with_ssh_tunnel_STAR_.invoke(ssh.clj:91)"
  "driver.mongo.util$_with_mongo_connection.invokeStatic(util.clj:199)"
  "driver.mongo.util$_with_mongo_connection.invoke(util.clj:194)"
  "driver.mongo$eval2143$fn__2144$fn__2146.invoke(mongo.clj:63)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__37567.invoke(driver_specific.clj:12)"
  "query_processor.middleware.add_settings$add_settings$fn__35554.invoke(add_settings.clj:45)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__40795.invoke(resolve_driver.clj:22)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__36881$fn__36882.invoke(bind_effective_timezone.clj:9)"
  "util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
  "util.date$call_with_effective_timezone.invoke(date.clj:77)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__36881.invoke(bind_effective_timezone.clj:8)"
  "query_processor.middleware.store$initialize_store$fn__43915$fn__43916.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__43915.invoke(store.clj:10)"
  "query_processor.middleware.async$async__GT_sync$fn__34195.invoke(async.clj:23)"
  "query_processor.middleware.async_wait$runnable$fn__36607.invoke(async_wait.clj:89)"),
 :query
 {:type "query",
  :query {:source-table 443},
  :parameters [],
  :async? true,
  :middleware {:add-default-userland-constraints? true, :userland-query? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :card-id nil,
   :nested? false,
   :query-hash [122, 64, 79, 14, 71, 80, 52, 64, -33, 12, 49, -95, -42, -59, 15, -41, -57, -39, -104, -72, -80, 31, -105, -120, 2, 44, 28, -127, 11, -9, -115, 3]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :preprocessed nil,
 :native nil,
 :ex-data {:type :schema.core/error, :value (), :error (named (not ("Non-empty" a-clojure.lang.LazySeq)) "Distinct, non-empty sequence of Field clauses")}}

**Comment by flamber** [comment] 2019-11-16 15:15
Hi @dt1018614769 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Please post the Diagnostic Info from Admin > Troubleshooting. Latest release is 0.33.5.1
Did Metabase finish scanning the database? You should see log entries of the scanning process. Admin > Troubleshooting > Logs.
Try running a forced sync+scan again, and check the log for any problems.
Admin > Databases > (db) > Sync database schema now + Re-scan field values now

**Comment by dt1018614769** [comment] 2019-11-18 03:02
Has anyone had this problem?

**Comment by dt1018614769** [comment] 2019-11-18 03:02
Has anyone had this problem

**Comment by flamber** [comment] 2019-11-18 03:09
@dt1018614769 Did you read my comment? Please provide more information.

**Comment by mazameli** [comment] 2019-11-19 23:13
Closing as duplicate of #11324.

**Closed by mazameli** 2019-11-19 23:13 UTC
Labels: .Duplicate
