### ISSUE TITLE
Allow for entering a date into the Default Filter Widget Value date picker

### ISSUE THREAD

**Issue by nbrustein** [metabase/metabase#13686] opened 2020-11-04 21:34 UTC
It is hard to pick a date years in the past with the date picker in the Default Filter Widget Value.  You have to scroll back through many months, and the button moves up and down in months that have different numbers of days, so you can't just bang on it really fast.

I think it should be possible to enter a date a text field.

It's usable as-is, but it can be really annoying.

**Comment by flamber** [comment] 2020-11-05 10:20
Duplicate of #4585

**Closed by flamber** 2020-11-05 10:20 UTC
Labels: .Needs Triage, Type:New Feature
