### ISSUE TITLE
Changing the global formatting of dates and numbers does not propagate to column formatting

### ISSUE THREAD

**Issue by rthouvenin** [metabase/metabase#12664] opened 2020-06-09 10:08 UTC
**Describe the bug**
This is a continuation of [the issue that I started to discuss in #11394](https://github.com/metabase/metabase/issues/11394#issuecomment-640650976)
After changing the global date and number formatting, many values still display with the old format. I think this is because the formatting set at column level when the schema was imported is not reset (even though I didn't change any of them and would like the global to still apply).

**To Reproduce**
1. Import a database
2. Go to Admin > Formatting and change the date style and separator style
2. Exit Admin and click on Browse data, and display a table with dates and numbers
3. See that the formatting of dates and numbers is as before changing them
4. Go to Admin > Data model > one of the date or number columns > Formatting. See that the settings is the old value, and there is no "reset" button

**Expected behavior**
I would expect that columns that use the global formatting setting still do so after changing it.

**Screenshots**
After setting dates to D/M/Y and numbers to 100 000,00, displaying orders:

![image](https://user-images.githubusercontent.com/7570541/84040381-db769800-a9a2-11ea-80d5-639de882bb5d.png)

Interestingly, the currency column is correctly displayed.

**Information about your Metabase Installation:**

- Metabase version: 0.35.2

**Severity**
Low severity, only prevents from displaying metrics consistently and avoiding confusion of users.

**Additional context**
https://discourse.metabase.com/t/formatting-options-have-no-effect/8019/2

This is difficult to reproduce:

 - I spun a fresh instance and couldn't reproduce
 - Came back to my existing instance, tried to change the global date format and back to what I want, and now it shows up correctly both in data model and questions! In another words, the problem seems somehow solved for dates
 - Did the same with the number format, but the problem did not disappear. I will now avoid touching the global formatting setting so I can keep reproducing and help understand the root problem.

My investigations so far:

 - This does not seem linked to browser cache, I can reproduce even when it is disabled
 - I checked the application DB, no formatting stored in the field: the column (that's in the `settings` column, right?) is null
 - Using the network tab of the browser console, I can see that
   + `/api/database/11/metadata` returns a null `settings` property for the field
   + Same thing for `/api/table/897/query_metadata`
   + `/admin/datamodel/database/11/table/897/7159/formatting` defines a `_metabaseBootstrap` element with the below JSON (I figured from reading the code this is how the global formatting reaches the frontend, but I could be wrong!): 
  ```
"custom-formatting":{
  "type/DateTime":{"date_style":"YYYY/M/D","date_separator":"-","time_style":"k:mm"},
  "type/Currency":{"currency":"EUR","currency_style":"symbol"},
  "type/Temporal":{"date_style":"D/M/YYYY","date_separator":"/"},
  "type/Number":{"number_separators":", "}
}
  ```

`/api/session/properties` also returns the same custom formatting JSON. `Temporal` and `Number` 
match my global settings but differ from what is displayed in data model admin. Not sure what's the difference between `DateTime` and `Temporal`, maybe a lead to follow for the problems with dates?

I really have no clue of what could explain the problem with numbers. Even if I haven't read any of the code that displays numbers I thought that by looking at all the API responses of displaying the data model, I would find where the wrong format comes from but no luck so far :(

**Comment by rthouvenin** [comment] 2020-06-09 10:14
Maybe the problem is in matching column type with the keys in `custom-formatting`. I am not familiar with all the types, but say if there is a type `Float` but the global settings store the format in type `Number`, then you need a logic to match those. I got this idea from seeing that there is a `Temporal` and `DateTime`.

**Comment by flamber** [comment] 2020-06-09 10:53
I still cannot reproduce. I think this is the same as #11394, where not setting a Field Type for a column will make it show the Default formatting instead of Global. That is why it shows correctly for Discount, but not the other number columns.

**Comment by rthouvenin** [comment] 2020-06-09 14:37
You're right, this was quite dumb of me to think of the type matching and not check that the columns I was looking at did have a type...

I believe this explains the number problem but not date, as the date columns I was looking did have a type and I didn't change it (for example I was seeing this on Orders.created_at which is flagged as creation timestamp on import). But I cannot reproduce this one anymore... :roll_eyes: 

@flamber Any idea why `DateTime` is not updated with global settings, but seems to have been earlier (the value in the JSON I show is not the default). How does it get updated? Maybe we can guess the scenario from that...

**Comment by flamber** [comment] 2020-06-09 14:54
Well, since I still cannot reproduce, then it's difficult for me to say what's going on, but I'm 99% sure that it's cache (more specifically state cache), so it's not enough for you just to refresh the browser, you have to open a new tab and go to Metabase in that tab.

There shouldn't be any difference between the different Field Type and how formatting is handled. It follows the same 5 levels as I've defined in the other issue.

But I'm going to close this, since without steps-to-reproduce it's impossible to know what's going on. And since I believe this is essentially the same problem as #11394.
I've already spent waaay too many hours troubleshooting this issue - see the forum.

**Closed by flamber** 2020-06-09 14:54 UTC
Labels: .Needs Triage, Type:Bug

**Comment by rthouvenin** [comment] 2020-06-10 07:30
I've tried in different tabs and across reboots, and the date formatting is still different for DateTime and Temporal. But fair enough, I understand very well your situation and I don't face the date problem anymore so fine by me :)
