### ISSUE TITLE
MongoDB filter query with the wrong timezone when set JAVA_TIMEZONE env

### ISSUE THREAD

**Issue by 9terz** [metabase/metabase#14598] opened 2021-02-01 05:42 UTC
**Describe the bug**
data in the report shown in GMT+7 timezone but the query still querying in UTC

**To Reproduce**
1. Set JAVA_TIMEZONE to Asia/Bangkok
2. Use a relative filter with previous 1 day
3. The query will query in native query with GMT+7 time but in UTC (plus 7 hours)

**Expected behavior**
the native query should query in +07:00 time too

**Screenshots**
![image](https://user-images.githubusercontent.com/9083980/106418699-82a3c480-6489-11eb-8568-a9b5a6f9ca82.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "4.14.209-160.339.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Bangkok"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "mysql",
      "h2"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-01-26",
      "tag": "v0.37.8",
      "branch": "release-x.37.x",
      "hash": "490cea7"
    },
    "settings": {
      "report-timezone": "Asia/Bangkok"
    }
  }
}
```

**Severity**
It's annoying to use the workaround to query the previous 7-8 hours instead of 1 hour ago. It would be nice if we can query with the correct time

**Comment by flamber** [comment] 2021-02-01 10:50
Looks like a duplicate of #14233

**Closed by flamber** 2021-02-01 10:50 UTC
Labels: .Needs Triage, Type:Bug

**Comment by 9terz** [comment] 2021-02-02 07:42
> Looks like a duplicate of #14233

Thanks, already give thumbs up to the original issue.
