### ISSUE TITLE
Search dropdown disappears when navigating with keyboard

### ISSUE THREAD

**Issue by oisincoveney** [metabase/metabase#34949] opened 2023-10-23 10:02 UTC
### Describe the bug

After typing a query in the search dropdown and navigating to a new question using the keyboard, the search dropdown disappears and doesn't reactivate until the user clicks on the search bar with the mouse. Video reproducing the issue below:

https://github.com/metabase/metabase/assets/25306947/d7c4b95d-b948-43a4-bdea-bcd2ea058bec

### To Reproduce

1. Click on the search dropdown with the mouse
2. Type in a search query
3. Navigate to a result with the down arrow
4. Click 'Enter' to navigate to the entity
5. See that the text is focused on the search bar still, but the dropdown isn't there.				

### Expected behavior

Either the dropdown should continue to be there (if we decide to keep focus on the search bar), or focus should be moved elsewhere.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "20.0.1",
    "java.vendor": "Homebrew",
    "java.vendor.url": "https://github.com/Homebrew/homebrew-core/issues",
    "java.version": "20.0.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "20.0.1",
    "os.name": "Mac OS X",
    "os.version": "13.5.2",
    "user.language": "en",
    "user.timezone": "Europe/Tallinn"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-10-19",
      "src_hash": "3b5c88c57d4d4d98d1f25913e642cf29013f5fdb",
      "tag": "v1.47.1-SNAPSHOT",
      "hash": "e8fe22e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Annoying, but may be a larger issue for someone navigating solely by keyboard

**Comment by kamilmielnik** [comment] 2024-05-20 08:36
Search bar is no more: #42603
Can't reproduce with the new command palette. Closing.

**Closed by kamilmielnik** 2024-05-20 08:36 UTC
Labels: Type:Bug, Priority:P2, Organization/Search, .Frontend, .Team/AdminWebapp
