### ISSUE TITLE
Redshift Table Sync not working on 0.32.9

### ISSUE THREAD

**Issue by TrineFN** [metabase/metabase#10267] opened 2019-06-27 15:04 UTC
**Describe the bug**
Since version 0.32.9 the 'sync-table' task is not working for our Redshift DB. Our tables are now not being synced at all. 

Note:
This bug is similar to issue [9844](https://github.com/metabase/metabase/issues/9844) where we could not trigger a 'Sync database schema now' from admin, but different as now the tables are never synced. 

**Logs**
The task 'sync-table'  does not appear in _".../admin/troubleshooting/tasks"_ for our Redshift DB

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 75

- Your operating system: mcOS Mojave

- Your databases: Redshift 

- Metabase version: 0.32.9

- Metabase hosting environment: Elastic Beanstalk

- Metabase internal database: H2

**Severity**
Syncing worked on version 0.32.8, so we downgraded. 
This will prevent us from updating to never versions.

**Comment by mrjk05** [comment] 2019-08-09 04:01
I assume this is still not resolved as on v0.32.10 it seems to have the same bug.

**Comment by mrjk05** [comment] 2019-08-09 04:04
Issue still present in 0.32.10

```Aug 09 04:00:04 INFO metabase.sync.util :: STARTING: Sync metadata for postgres Database 7 'AWS Redshift' Aug 09 04:00:04 DEBUG metabase.sync.util :: STARTING: step 'sync-timezone' for postgres Database 7 'AWS Redshift' Aug 09 04:00:04 ERROR metabase.driver.sql-jdbc.execute :: Failed to set timezone:  PSQLException: Message: ERROR: keyword SESSION not supported SQLState: XX000 Error Code: 0  Aug 09 04:00:04 DEBUG metabase.sync.util :: FINISHED: step 'sync-timezone' for postgres Database 7 'AWS Redshift' (20 ms) Aug 09 04:00:04 DEBUG metabase.sync.util :: STARTING: step 'sync-tables' for postgres Database 7 'AWS Redshift' Aug 09 04:00:04 ERROR metabase.sync.util :: Error running sync step: ERROR: type "e" does not exist ("org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)" "org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)" "org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)" "org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)" "org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)" "org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)" "org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)" "org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)" "org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:224)" "org.postgresql.jdbc.PgDatabaseMetaData.getTables(PgDatabaseMetaData.java:1316)" "com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getTables(NewProxyDatabaseMetaData.java:3010)" "--> driver.sql_jdbc.sync$get_tables.invokeStatic(sync.clj:90)" "driver.sql_jdbc.sync$get_tables.invoke(sync.clj:86)" "driver.sql_jdbc.sync$fast_active_tables$iter__64756__64762$fn__64763.invoke(sync.clj:106)" "driver.sql_jdbc.sync$fast_active_tables.invokeStatic(sync.clj:105)" "driver.sql_jdbc.sync$fast_active_tables.doInvoke(sync.clj:94)" "driver.sql_jdbc.sync$fn__64711.invokeStatic(sync.clj:35)" "driver.sql_jdbc.sync$fn__64711.invoke(sync.clj:34)" "driver.sql_jdbc.sync$describe_database.invokeStatic(sync.clj:189)" "driver.sql_jdbc.sync$describe_database.invoke(sync.clj:185)" "driver.sql_jdbc$fn__65183.invokeStatic(sql_jdbc.clj:50)" "driver.sql_jdbc$fn__65183.invoke(sql_jdbc.clj:49)" "sync.fetch_metadata$fn__47657$db_metadata__47662$fn__47663.invoke(fetch_metadata.clj:13)" "sync.fetch_metadata$fn__47657$db_metadata__47662.invoke(fetch_metadata.clj:10)" "sync.sync_metadata.tables$fn__49125$db_metadata__49130$fn__49131.invoke(tables.clj:144)" "sync.sync_metadata.tables$fn__49125$db_metadata__49130.invoke(tables.clj:141)" "sync.sync_metadata.tables$fn__49186$sync_tables_BANG___49191$fn__49192.invoke(tables.clj:161)" "sync.sync_metadata.tables$fn__49186$sync_tables_BANG___49191.invoke(tables.clj:156)" "sync.util$fn__40355$run_step_with_metadata__40360$fn__40364$fn__40366.invoke(util.clj:356)" "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)" "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)" "sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)" "sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)" "sync.util$fn__40355$run_step_with_metadata__40360$fn__40364.invoke(util.clj:353)" "sync.util$fn__40355$run_step_with_metadata__40360.invoke(util.clj:348)" "sync.util$fn__40547$run_sync_operation__40552$fn__40553$fn__40554.invoke(util.clj:441)" "sync.util$fn__40547$run_sync_operation__40552$fn__40553.invoke(util.clj:441)" "sync.util$fn__40547$run_sync_operation__40552.invoke(util.clj:435)" "sync.sync_metadata$fn__49239$sync_db_metadata_BANG___49244$fn__49245$fn__49246.invoke(sync_metadata.clj:51)" "sync.util$do_with_error_handling.invokeStatic(util.clj:149)" "sync.util$do_with_error_handling.invoke(util.clj:144)" "sync.util$do_with_error_handling.invokeStatic(util.clj:147)" "sync.util$do_with_error_handling.invoke(util.clj:144)" "driver$fn__17376.invokeStatic(driver.clj:668)" "driver$fn__17376.invoke(driver.clj:668)" "sync.util$sync_in_context$fn__40261.invoke(util.clj:140)" "sync.util$with_db_logging_disabled$fn__40258.invoke(util.clj:131)" "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)" "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)" "sync.util$with_start_and_finish_logging$fn__40247.invoke(util.clj:116)" "sync.util$with_sync_events$fn__40242.invoke(util.clj:90)" "sync.util$with_duplicate_ops_prevented$fn__40233.invoke(util.clj:69)" "sync.util$do_sync_operation.invokeStatic(util.clj:168)" "sync.util$do_sync_operation.invoke(util.clj:165)" "sync.sync_metadata$fn__49239$sync_db_metadata_BANG___49244$fn__49245.invoke(sync_metadata.clj:50)" "sync.sync_metadata$fn__49239$sync_db_metadata_BANG___49244.invoke(sync_metadata.clj:47)" "task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:39)")  Aug 09 04:00:04 INFO metabase.sync.util :: FINISHED: Sync metadata for postgres Database 7 'AWS Redshift' (105 ms) Aug 09 04:00:04 DEBUG metabase.sync.util :: Sync operations in flight: {:analyze #{7}} Aug 09 04:00:04 INFO metabase.sync.util :: STARTING: Analyze data for postgres Database 7 'AWS Redshift' Aug 09 04:00:04 DEBUG metabase.sync.util :: STARTING: step 'fingerprint-fields' for postgres Database 7 'AWS Redshift' Aug 09 04:00:04 DEBUG metabase.sync.util :: FINISHED: step 'fingerprint-fields' for postgres Database 7 'AWS Redshift' (297 µs) Aug 09 04:00:04 DEBUG metabase.sync.util :: STARTING: step 'classify-fields' for postgres Database 7 'AWS Redshift' Aug 09 04:00:04 DEBUG metabase.sync.util :: FINISHED: step 'classify-fields' for postgres Database 7 'AWS Redshift' (162 µs) Aug 09 04:00:04 DEBUG metabase.sync.util :: STARTING: step 'classify-tables' for postgres Database 7 'AWS Redshift' Aug 09 04:00:04 DEBUG metabase.sync.util :: FINISHED: step 'classify-tables' for postgres Database 7 'AWS Redshift' (123 µs) Aug 09 04:00:04 DEBUG metabase.sync.util ::  ################################################################# # Completed analyze on AWS Redshift # Start: 2019-08-09T04:00:04.694Z # End: 2019-08-09T04:00:04.695Z # Duration: 1000 µs # --------------------------------------------------------------- # Completed step 'fingerprint-fields' # Start: 2019-08-09T04:00:04.694Z # End: 2019-08-09T04:00:04.694Z # Duration: 0 ns # Fingerprint updates attempted null, updated null, no data found null, failed null # --------------------------------------------------------------- # Completed step 'classify-fields' # Start: 2019-08-09T04:00:04.694Z # End: 2019-08-09T04:00:04.695Z # Duration: 1000 µs # Total number of fields classified 0, 0 failed # --------------------------------------------------------------- # Completed step 'classify-tables' # Start: 2019-08-09T04:00:04.695Z # End: 2019-08-09T04:00:04.695Z # Duration: 0 ns # Total number of tables classified 0, 0 updated #################################################################  Aug 09 04:00:04 INFO metabase.sync.util :: FINISHED: Analyze data for postgres Database 7 'AWS Redshift' (4 ms) Aug 09 04:00:27 DEBUG metabase.middleware.log :: GET /api/session/properties 200 2 ms (1 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (119 total active threads) Queries in flight: 0 Aug 09 04:00:27 DEBUG metabase.middleware.log :: GET /api/setting 200 375 µs (0 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (119 total active threads) Queries in flight: 0 Aug 09 04:00:27 DEBUG metabase.middleware.log :: GET /api/setup/admin_checklist 200 30 ms (11 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (119 total active threads) Queries in flight: 0```

**Comment by sbelak** [comment] 2019-09-30 19:14
Duplicate of #9844

**Closed by sbelak** 2019-09-30 19:14 UTC
Labels: Database/Redshift, Priority:P1, Type:Bug
