### ISSUE TITLE
Timezone America_SaoPaulo Problems in PostgreSQL

### ISSUE THREAD

**Issue by guicouto** [metabase/metabase#13678] opened 2020-11-04 14:14 UTC
**Describe the bug**
Incorrect time calculation using the America / Sao_Paulo time zone using Postgres.

Some years ago Brazil had a time system called "Summer Time", which basically consisted of advancing the clock of some Brazilian states by 1 hour in some months of the year (usually from October to March)

In 2018 this law was repealed and since then, there is no longer this time difference.

**Logs**

```
[141323a4-fe8a-4635-af8c-0f37e4193ef6] 2020-11-04T11:00:25-03:00 ERROR metabase.driver.sql-jdbc.execute Falha ao definir o fuso horário ' America/Sao_Paulo ' para o banco de dados :postgres
org.postgresql.util.PSQLException: ERROR: invalid value for parameter "TimeZone": "America/Sao_Paulo"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:311)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:297)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:274)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:269)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
	at metabase.driver.sql_jdbc.execute$set_time_zone_if_supported_BANG_.invokeStatic(execute.clj:128)
	at metabase.driver.sql_jdbc.execute$set_time_zone_if_supported_BANG_.invoke(execute.clj:113)
	at metabase.driver.sql_jdbc.execute$fn__76678.invokeStatic(execute.clj:160)
	at metabase.driver.sql_jdbc.execute$fn__76678.invoke(execute.clj:155)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:389)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:386)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)
	at metabase.driver.sql_jdbc$fn__78112.invokeStatic(sql_jdbc.clj:49)
	at metabase.driver.sql_jdbc$fn__78112.invoke(sql_jdbc.clj:47)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.query_processor.context$executef.invokeStatic(context.clj:59)
	at metabase.query_processor.context$executef.invoke(context.clj:48)
	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:69)
	at metabase.query_processor.context.default$default_runf.invoke(default.clj:67)
	at metabase.query_processor.context$runf.invokeStatic(context.clj:45)
	at metabase.query_processor.context$runf.invoke(context.clj:39)
	at metabase.query_processor.reducible$pivot.invokeStatic(reducible.clj:34)
	at metabase.query_processor.reducible$pivot.invoke(reducible.clj:31)
	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47424.invoke(mbql_to_native.clj:26)
	at metabase.query_processor.middleware.check_features$check_features$fn__46699.invoke(check_features.clj:42)
	at metabase.query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__47589.invoke(optimize_datetime_filters.clj:133)
	at metabase.query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__45500.invoke(auto_parse_filter_values.clj:44)
	at metabase.query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__49155.invoke(wrap_value_literals.clj:149)
	at metabase.query_processor.middleware.annotate$add_column_info$fn__45262.invoke(annotate.clj:575)
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__46574.invoke(permissions.clj:70)
	at metabase.query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__48107.invoke(pre_alias_aggregations.clj:40)
	at metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46772.invoke(cumulative_aggregations.clj:61)
	at metabase.query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__48344.invoke(resolve_joined_fields.clj:36)
	at metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__48663.invoke(resolve_joins.clj:183)
	at metabase.query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__40987.invoke(add_implicit_joins.clj:254)
	at metabase.query_processor.middleware.large_int_id$convert_id_to_string$fn__47385.invoke(large_int_id.clj:44)
	at metabase.query_processor.middleware.limit$limit$fn__47410.invoke(limit.clj:38)
	at metabase.query_processor.middleware.format_rows$format_rows$fn__47365.invoke(format_rows.clj:84)
	at metabase.query_processor.middleware.desugar$desugar$fn__46838.invoke(desugar.clj:22)
	at metabase.query_processor.middleware.binning$update_binning_strategy$fn__45859.invoke(binning.clj:229)
	at metabase.query_processor.middleware.resolve_fields$resolve_fields$fn__46376.invoke(resolve_fields.clj:24)
	at metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__40531.invoke(add_dimension_projections.clj:318)
	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__40738.invoke(add_implicit_clauses.clj:141)
	at metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__41136.invoke(add_source_metadata.clj:105)
	at metabase.query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__48304.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)
	at metabase.query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45447.invoke(auto_bucket_datetimes.clj:125)
	at metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46423.invoke(resolve_source_table.clj:46)
	at metabase.query_processor.middleware.parameters$substitute_parameters$fn__48089.invoke(parameters.clj:114)
	at metabase.query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46475.invoke(resolve_referenced.clj:80)
	at metabase.query_processor.middleware.expand_macros$expand_macros$fn__47094.invoke(expand_macros.clj:158)
	at metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__41167.invoke(add_timezone_info.clj:15)
	at metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49025.invoke(splice_params_in_response.clj:32)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48315$fn__48319.invoke(resolve_database_and_driver.clj:33)
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:61)
	at metabase.driver$do_with_driver.invoke(driver.clj:57)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48315.invoke(resolve_database_and_driver.clj:27)
	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47312.invoke(fetch_source_query.clj:267)
	at metabase.query_processor.middleware.store$initialize_store$fn__49034$fn__49035.invoke(store.clj:11)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:44)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:40)
	at metabase.query_processor.middleware.store$initialize_store$fn__49034.invoke(store.clj:10)
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__46352.invoke(cache.clj:214)
	at metabase.query_processor.middleware.validate$validate_query$fn__49043.invoke(validate.clj:10)
	at metabase.query_processor.middleware.normalize_query$normalize$fn__47437.invoke(normalize_query.clj:22)
	at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__41005.invoke(add_rows_truncated.clj:36)
	at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49010.invoke(results_metadata.clj:143)
	at metabase.query_processor.reducible$async_qp$qp_STAR___39794$thunk__39795.invoke(reducible.clj:103)
	at metabase.query_processor.reducible$async_qp$qp_STAR___39794.invoke(reducible.clj:109)
	at metabase.query_processor.reducible$async_qp$qp_STAR___39794.invoke(reducible.clj:96)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___39803$fn__39804.invoke(reducible.clj:131)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___39803.invoke(reducible.clj:130)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.query_processor$process_query.invokeStatic(query_processor.clj:146)
	at metabase.query_processor$process_query.doInvoke(query_processor.clj:140)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.Var.invoke(Var.java:384)
	at metabase.db.metadata_queries$fn__57389$table_rows_sample__57398$fn__57404.invoke(metadata_queries.clj:112)
	at metabase.db.metadata_queries$fn__57389$table_rows_sample__57398.invoke(metadata_queries.clj:98)
	at metabase.sync.analyze.fingerprint$fn__57495$fingerprint_table_BANG___57500$fn__57501.invoke(fingerprint.clj:69)
	at metabase.sync.analyze.fingerprint$fn__57495$fingerprint_table_BANG___57500.invoke(fingerprint.clj:49)
	at metabase.sync.analyze.fingerprint$fn__57668$fingerprint_fields_BANG___57673$fn__57674$fn__57675.invoke(fingerprint.clj:173)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
	at metabase.sync.analyze.fingerprint$fn__57668$fingerprint_fields_BANG___57673$fn__57674.invoke(fingerprint.clj:171)
	at metabase.sync.analyze.fingerprint$fn__57668$fingerprint_fields_BANG___57673.invoke(fingerprint.clj:167)
	at metabase.sync.analyze.fingerprint$fn__57696$fingerprint_fields_for_db_BANG___57701$fn__57702$fn__57703$iter__57704__57708$fn__57709$fn__57710.invoke(fingerprint.clj:191)
	at metabase.sync.analyze.fingerprint$fn__57696$fingerprint_fields_for_db_BANG___57701$fn__57702$fn__57703$iter__57704__57708$fn__57709.invoke(fingerprint.clj:188)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1792)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.sync.analyze.fingerprint$fn__57696$fingerprint_fields_for_db_BANG___57701$fn__57702$fn__57703.invoke(fingerprint.clj:188)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:46)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:40)
	at metabase.sync.analyze.fingerprint$fn__57696$fingerprint_fields_for_db_BANG___57701$fn__57702.invoke(fingerprint.clj:185)
	at metabase.sync.analyze.fingerprint$fn__57696$fingerprint_fields_for_db_BANG___57701.invoke(fingerprint.clj:179)
	at metabase.sync.analyze$make_analyze_steps$fn__57842.invoke(analyze.clj:106)
	at metabase.sync.util$fn__44021$run_step_with_metadata__44026$fn__44030$fn__44032.invoke(util.clj:345)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:119)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:116)
	at metabase.sync.util$fn__44021$run_step_with_metadata__44026$fn__44030.invoke(util.clj:342)
	at metabase.sync.util$fn__44021$run_step_with_metadata__44026.invoke(util.clj:337)
	at metabase.sync.util$fn__44213$run_sync_operation__44218$fn__44219$fn__44220.invoke(util.clj:430)
	at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$mapv.invokeStatic(core.clj:6903)
	at clojure.core$mapv.invoke(core.clj:6903)
	at metabase.sync.util$fn__44213$run_sync_operation__44218$fn__44219.invoke(util.clj:430)
	at metabase.sync.util$fn__44213$run_sync_operation__44218.invoke(util.clj:424)
	at metabase.sync.analyze$fn__57854$analyze_db_BANG___57859$fn__57860$fn__57861.invoke(analyze.clj:123)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:145)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
	at clojure.core$partial$fn__5839.invoke(core.clj:2623)
	at metabase.driver$fn__22491.invokeStatic(driver.clj:550)
	at metabase.driver$fn__22491.invoke(driver.clj:550)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__43933.invoke(util.clj:138)
	at metabase.sync.util$with_db_logging_disabled$fn__43930.invoke(util.clj:129)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
	at metabase.sync.util$with_start_and_finish_logging$fn__43919.invoke(util.clj:114)
	at metabase.sync.util$with_sync_events$fn__43914.invoke(util.clj:88)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__43905.invoke(util.clj:67)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:164)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:161)
	at metabase.sync.analyze$fn__57854$analyze_db_BANG___57859$fn__57860.invoke(analyze.clj:120)
	at metabase.sync.analyze$fn__57854$analyze_db_BANG___57859.invoke(analyze.clj:115)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:52)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:40)
	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:55)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
```

HTTP REQUEST (api/dataset):

```
{"type":"native","native":{"query":"SELECT now()","template-tags":{}},"database":2,"parameters":[]}
``` 

HTTP RESPONSE (api/dataset):

```
{"data":{"rows":[
["2020-11-04T11:32:05.149701-02:00"]
],
"cols":[{"display_name":"now","source":"native","field_ref":["field-literal","now","type/DateTimeWithLocalTZ"],"name":"now","base_type":"type/DateTimeWithLocalTZ"}],"native_form":{"query":"SELECT now()","params":null},"results_timezone":"America/Sao_Paulo","requested_timezone":"America/Sao_Paulo","results_metadata":{"checksum":"jIdgLycPpR/A5YjxOtsq2A==","columns":[{"base_type":"type/DateTimeWithLocalTZ","display_name":"now","name":"now","special_type":null,"fingerprint":{"global":{"distinct-count":1,"nil%":0.0},"type":{"type/DateTime":{"earliest":"2020-11-04T11:32:05.149701-02:00","latest":"2020-11-04T11:32:05.149701-02:00"}}}}]},"insights":null},
"database_id":2,"started_at":"2020-11-04T10:32:04.703-03:00","json_query":{"type":"native","native":{"query":"SELECT now()","template-tags":{}},"database":2,"middleware":{"js-int-to-string?":true,"add-default-userland-constraints?":true}},"average_execution_time":null,"status":"completed","context":"ad-hoc","row_count":1,"running_time":575}
```

**To Reproduce**
1. Go to the Admin panel and change the time zone to America / Sao_Paulo
2. Then ask a new question using Native SQL.
3. Run the following query:
```SELECT NOW ()```

**Expected behavior**
A time will be displayed exactly 1 hour ahead of the correct time for the America / Sao_Paulo time zone

**Screenshots**
Query executed in Metabase
<img width="1280" alt="metabase_query" src="https://user-images.githubusercontent.com/8810377/98121899-ac4f4e80-1e8e-11eb-9eda-53d4afe2bf3e.png">

Query performed directly on the server
![Server_Query](https://user-images.githubusercontent.com/8810377/98121947-b83b1080-1e8e-11eb-985f-d0beece4dc20.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_192-b26",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_192",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.192-b26",
    "os.name": "FreeBSD",
    "os.version": "11.2-RELEASE-p4",
    "user.language": "en",
    "user.timezone": "America/Recife"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.8"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.37.0.2",
      "date": "2020-10-26",
      "branch": "release-x.37.x",
      "hash": "ba7be09"
    },
    "settings": {
      "report-timezone": "America/Recife"
    }
  }
}
```

**Severity**
It is preventing the correct functioning of any report that needs to be filtered by the current date. Because it's bringing the result to zero

**Additional context**
I ran the tests on several versions of the metabase, from 0.35.4 to 0.37.0.2, in all of them I got the same problem.

**Comment by flamber** [comment] 2020-11-04 15:23
Hi @guicouto 

I cannot reproduce on 0.37.0.2 with Postgres 12.2 on AdoptOpenJDK 11, but I'm a little unsure about the steps-to-reproduce.

Can you please try again with an updated version of Postgres (would also recommend upgrading Java too), since it looks like it's failing to set the timezone `America/Sao_Paulo` on the Postgres connection session.

I'm guessing that you don't have the timezone:
`SELECT * FROM pg_timezone_names WHERE name='America/Sao_Paulo';`

Check the current timezone:
`select * from pg_settings where name = 'TimeZone';`

Time debugging:
```
select now()                                  as "now()"
     , now()::timestamp                       as "now()::timestamp"
     , now()::timestamptz                     as "now()::timestamptz"
     , now() at time zone 'utc-0'             as "now() - utc-0"
     , now() at time zone 'America/Sao_Paulo' as "now() - sao paulo"
     , localtimestamp
     , timeofday()                            as "timeofday()"
  ;
```

**Comment by Eric108493** [comment] 2020-11-06 01:37
I am having a similar problem, 

When I use the `SELECT NOW ()`  the metabase returns the correct time for my time zone - América / São_Paulo

My specifications to try to find the error in the colleague's problem:

```
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_261-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_261",
    "java.vm.name": "Java HotSpot(TM) Client VM",
    "java.vm.version": "25.261-b12",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "pt",
    "user.timezone": "America/Sao_Paulo"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.36.4",
      "date": "2020-08-17",
      "branch": "release-0.36.x",
      "hash": "196c1f6"
    },
    "settings": {
      "report-timezone": "America/Sao_Paulo"
    }
  }
}
```

However in my case the time zone problem appears when I make a query using a field filter and select the type: unique date. 
The metabase always starts 3 hours before midnight, which indicates -3 hours in relation to UTC, this being my time zone, but I need it to start at exactly midnight.

Is there any way to adjust the time zone also for the field filter and make my queries start at midnight?

If more data is needed I can send it.

I appreciate any help.

**Comment by flamber** [comment] 2020-11-06 10:42
@Eric108493 
That's not the same issue as this. Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And you should migrate away from H2 if you're using Metabase in production: https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html
Latest release is 0.37.0.2

**Comment by Eric108493** [comment] 2020-11-09 16:58
I managed to solve this by putting "UTC" in the "Report time zone" option (my time zone is UTC -3).

Should I put this information somewhere to help anyone with a similar problem? 

Thank you for your help

**Comment by flamber** [comment] 2020-11-09 17:33
@Eric108493 It's very hard to troubleshoot timezone issues, so without all the information available, I wouldn't know what your issue actually was: https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html
Now you have commented here, so in case someone searches, then they might find your comment.

@guicouto I'm closing this issue, since it looks like your Postgres doesn't have updated `tzdata` (pg_timezone_names)

**Closed by flamber** 2020-11-09 17:33 UTC
Labels: .Needs Triage, Type:Bug
