### ISSUE TITLE
Slow content download from prestodb

### ISSUE THREAD

**Issue by yurkazaytsev** [metabase/metabase#16522] opened 2021-06-09 17:03 UTC
**Describe the bug**
Table from presto server loads very slow. I have a local metabase instance of version 0.39.3 . I also have a local prestodb server with in memory database with just a single table. When I explore this table with a metabase it takes more then 6 second to show it. Chrome network console shows that the most of this time goes for content download. The size of the content is 167kB. 

Rendering the table from Sample Dataset of pretty the same size (Reviews table of about 119kB) have no any issues of this kind. 

Both metabase and presto server runs locally in attempt to exclude any network effects. 
**Logs**
Logs show no errors, nor in metabase nor in chrome console. 
**To Reproduce**
1. run prestodb instance with in memory db
2. add prestodb in-memory database to metabase databases
3.  explore table with metabase

**Expected behavior**

Fast load of a table

**Screenshots**
![image](https://user-images.githubusercontent.com/8008717/121397098-f54b1200-c94b-11eb-8f8e-9e8ba1a15c09.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "13.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "13.0.2+8",
    "os.name": "Mac OS X",
    "os.version": "10.15.7",
    "user.language": "en",
    "user.timezone": "Europe/London"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "presto"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-27",
      "tag": "v0.39.3",
      "branch": "release-x.39.x",
      "hash": "598a112"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

- Your browser and the version: Chrome Version 91.0.4472.77 (Official Build) (x86_64)
- Your operating system: macOS Catalina 10.15.7
- Your databases: prestodb
- Metabase version: 0.39.3
- Metabase hosting environment: jar file
- Metabase internal database: H2

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
It literally doesn't allow to work with a data. Imagine you need to wait for a several seconds after every update, like filtering. 

**Additional context**
Nope

**Comment by flamber** [comment] 2021-06-09 17:10
Duplicate of #16380

**Closed by flamber** 2021-06-09 17:10 UTC
Labels: .Needs Triage, Type:Bug

**Comment by yurkazaytsev** [comment] 2021-06-09 17:13
@flamber I wasn't sure it is the same. Thanks!
