### ISSUE TITLE
Improve Metadata loading latency in the Query Builder Stage 2

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#11806] opened 2020-01-27 20:23 UTC
- [ ] Paginate/optimize large database metadata loading aka `fix Horrorshow`
- [ ] Update saved question picker in QB to respect nested collections (aka use the Collections picker from the Save Modal)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2020-05-23 10:55
When there's thousands of tables, then `/api/database?include=tables` can take 2½ minutes to load.
It's also reserving Jetty and DB threads for a long time, which means more resources is required/used.
https://discourse.metabase.com/t/debug-high-use-of-specific-datasources/10217/9

**Comment by nautilus28** [comment] 2020-08-11 22:32
We connect Metabase to our data warehouse which contains 4000 tables. Loading full metadata take ages.

I made a patch to cache this endpoint 24 hours, however, it is still consuming a lot of resources when loading this metadata. 

![Screenshot 2020-08-11 at 23 20 25](https://user-images.githubusercontent.com/4472857/89954566-3fc70980-dc29-11ea-86ef-ac5c6004e5a8.png)

**Comment by sbelak** [comment] 2020-08-12 10:15
Two additional things we could do is:
* streaming these responses 
* prune the response some (e.g do we really need fingerprints for all the fields in these responses)

**Comment by nautilus28** [comment] 2020-08-17 22:31
We have seen a huge performance improvement after removing the slow endpoint /api/database?include=tables. It is weird that everything seems to work properly, we haven't seen any thing broken yet.

**Comment by camsaul** [comment] 2021-02-26 22:30
I think this is a duplicate of #5504

**Comment by camsaul** [comment] 2021-02-26 22:30
See also #10134 where we talked a bit about how to implement this.

**Comment by flamber** [comment] 2021-11-12 19:51
This was fixed across several releases in 0.39, 0.40 and 0.41

**Closed by flamber** 2021-11-12 19:51 UTC
Labels: Priority:P1, Type:Performance
