### ISSUE TITLE
Feature Request: Most Recent Filter

### ISSUE THREAD

**Issue by alee792** [metabase/metabase#6280] opened 2017-10-26 18:19 UTC
I was hoping that the team could implement a "Most Recent" time filter in the GUI that would grab records with the MAX(report_dttm).  For example, if I am logging events in a table, instead of viewing events that occurred in the past X minutes/hours/days/etc., I would like to view the most recent event. 

Minor request, since it's easily accomplished through SQL, but useful nonetheless!

**Comment by mvrabel** [comment] 2017-10-30 09:17
@alee792 You can accomplish this by clicking on the colmn name of "report_dttm" column and then choose "Descending".

Example:
![last_modif_filter](https://user-images.githubusercontent.com/12628893/32163042-402c286e-bd5b-11e7-8dbc-7f7822952540.PNG)

**Comment by alee792** [comment] 2017-10-30 13:42
@mvrabel Almost, but not quite. That would just reorder data.

`SELECT report_dttm, feature
FROM table
ORDER BY report_dttm DESC`

I would like a query result or visualization to return **only and all** the records matching the maximum timestamp of a column. 

`SELECT report_dttm, feature
FROM table
WHERE report_dttm = (SELECT MAX(report_dttm) FROM table)
`

**Comment by flamber** [comment] 2019-02-17 21:27
Hi @alee792 
Have you tried to do something like this?
```
SELECT MAX(report_dttm), feature FROM table GROUP BY feature
```
I tried to use View selector "Maximum of ...", but it only allows me to chose numbers, so I created a Custom Expression. This is how it looks on 0.31.2:
![image](https://user-images.githubusercontent.com/1447303/52919382-a040e900-32c7-11e9-86a2-0b499f99c7bf.png)

**Comment by flamber** [comment] 2021-11-09 19:24
Duplicate of #4482 combined with the Notebook editor

**Closed by flamber** 2021-11-09 19:24 UTC
Labels: Priority:P3, Type:New Feature, Querying/GUI
