### ISSUE TITLE
New columns not appearing in the table visualisation if other columns have been removed before

### ISSUE THREAD

**Issue by flavie-dethe** [metabase/metabase#17260] opened 2021-07-30 17:17 UTC
**Describe the bug**
When removing a column from the `Table` visualization's output, if new columns are added to the query afterward, they appear in the query output, but not in the `Table` visualization and it's impossible to select them in the Table's `Settings` section. However, they are accessible when changing the visualization type. 
Changing the visualization type then switching back to Table or saving the query then modify don't make the column appear. 

**To Reproduce**
1. Execute a simple native SQL query, with 2 columns (eg.` SELECT 1 as col_1, 2 as col_2`)
2. Click on `visualisation` -> select `Table` -> in the settings, in the` visible columns` section, unclick one of the column 
3. Add another column to the query (eg. `SELECT 1 as col_1, 2 as col_2 , 3 as col_3`) and re-execute it. 
4. See error: the new column appears in the output but not in the table's visualization. It doesn't appear either in the settings. But, it's available when selecting another visualization type. 

**Expected behavior**
The new column should directly appear in the visualization or at least, the list of visible columns should be refreshed (automatically or manually). 

**Screenshots**

https://user-images.githubusercontent.com/51905655/127688674-0b7d847e-db9d-4213-b1a0-9be876ca2580.mp4

**Information about your Metabase Installation:**

`{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_282-b08",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "1.8.0_282",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.282-b08",
    "os.name": "Linux",
    "os.version": "4.14.238-182.422.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.39.4",
      "date": "2021-06-15",
      "branch": "release-x.39.x",
      "hash": "f538050"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}`

**Severity**
It deteriorates the dev experience: when wanting to add a column to an existing question (happens several times a day), I need to archive the old question, create a new one with the new column and re-do all the formatting (columns' name, value formatting, conditional formatting).

**Comment by flamber** [comment] 2021-07-30 17:20
Duplicate of #15393. Fixed in 0.40.0. Latest release is 0.40.1: https://github.com/metabase/metabase/releases/latest

**Closed by flamber** 2021-07-30 17:20 UTC
Labels: .Needs Triage, Type:Bug
