### ISSUE TITLE
Unable to add MySQL database

### ISSUE THREAD

**Issue by danieljelder** [metabase/metabase#10347] opened 2019-07-15 10:41 UTC
**Describe the bug**
When attempting to add a MySQL database, an error is displayed 
in red next to the `Save` button:

> class metabase.util.i18n.UserLocalizedString cannot be cast to class java.lang.String (metabase.util.i18n.UserLocalizedString is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')

**Logs**
javascript logs:
```
/api/database:1 Failed to load resource: the server responded with a status of 400 ()
app-main.bundle.js?5c9f8212684e279ce595:5 Request entities,databases,create failed: Objectdata: {valid: false, dbname: "class metabase.util.i18n.UserLocalizedString canno…ing is in module java.base of loader 'bootstrap')", message: "class metabase.util.i18n.UserLocalizedString canno…ing is in module java.base of loader 'bootstrap')"}isCancelled: falsestatus: 400__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
(anonymous) @ app-main.bundle.js?5c9f8212684e279ce595:5
app-main.bundle.js?5c9f8212684e279ce595:5 error creating a database Objectdata: {valid: false, dbname: "class metabase.util.i18n.UserLocalizedString canno…ing is in module java.base of loader 'bootstrap')", message: "class metabase.util.i18n.UserLocalizedString canno…ing is in module java.base of loader 'bootstrap')"}isCancelled: falsestatus: 400__proto__: Object
(anonymous) @ app-main.bundle.js?5c9f8212684e279ce595:5
create:1 Failed to load resource: the server responded with a status of 503 ()
```

Server logs:
```
07-15 10:19:57 DEBUG middleware.log :: POST /api/database 400 414 ms (0 DB calls) 
{:valid false,
 :dbname
 "class metabase.util.i18n.UserLocalizedString cannot be cast to class java.lang.String (metabase.util.i18n.UserLocalizedString is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')",
 :message
 "class metabase.util.i18n.UserLocalizedString cannot be cast to class java.lang.String (metabase.util.i18n.UserLocalizedString is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')"}
```

**To Reproduce**
1. Go to 'Settings' -> 'Admin' -> 'Databases'
2. Go to 'Databases'
3. Click on "Add database'
4. Choose Database type `MySQL`
5. Fill in any name, host, port, database name (I used `dbname`), database username and database password
3. Click on Save

**Expected behavior**
The save succeeds and the database is added.

**Screenshots**
![image](https://user-images.githubusercontent.com/23167821/61210366-2edd5900-a6f4-11e9-889b-df69a75b94f3.png)

**Information about your Metabase Installation:**
- Your browser and the version: Version 75.0.3770.100 (Official Build) (64-bit)

- Your operating system: Ubuntu 18.04.2 LTS

- Your databases: MySQL

- Metabase version: 0.33-preview2

- Metabase hosting environment: Kubernetes (Docker)

- Metabase internal database: MySQL

**Severity**
Blocking for new installations. In order to set up Metabase we downgraded 0.33-preview, added the databases, then upgraded to 0.33-preview2 again.

**Additional context**

**Comment by ShalbafZadeh** [comment] 2019-07-15 15:45
@danieljelder  does your mysql connection info contain any special character or non-ASCII character ?

**Comment by danieljelder** [comment] 2019-07-15 16:02
No. To reproduce, the only "special" character I used was a dash in the host name (required as our db host name has that).

Just to clarify, this is the `0.33-preview2` version.

**Comment by flamber** [comment] 2019-07-15 18:36
@danieljelder 
I can only reproduce part of the issue if I enter a wrong username/password or wrong database name.
But then I'm only seeing a shorter error:
```
07-15 12:28:38 DEBUG middleware.log :: POST /api/database 400 9 ms (0 DB calls) 
{:valid false, :dbname "metabase.util.i18n.UserLocalizedString cannot be cast to java.lang.String", :message "metabase.util.i18n.UserLocalizedString cannot be cast to java.lang.String"}
```
Tested with `0.33.0-preview2` and `mysql:5.7`

**Comment by danieljelder** [comment] 2019-07-16 09:21
I think in my case the connection details were correct, as I managed to set it up after downgrading to `0.33-preview`.

**Comment by ernoaapa** [comment] 2019-08-01 05:58
I had same error when starting up Metabase `0.33-preview2` with Postgres as application DB. Downgraded to version `0.33-preview` and it works!

**Comment by flamber** [comment] 2019-08-01 06:02
@ernoaapa Can you try with [0.33.0-RC1](https://github.com/metabase/metabase/releases/tag/v0.33.0-RC1), which was released yesterday?

**Comment by danieljelder** [comment] 2019-08-01 09:33
I managed to add a mysql db with the RC1.

To test your reproduction experience I tried again to add a db with preview2 and it did indeed succeed. When using an incorrect username I got the error I stated in the original message. Sorry about that!

The fact that I tried multiple times on both `preview` and `preview2` and only succeeded on `preview` made me sure I had input the right details.

I guess this ticket should really be about fixing the error message when the wrong details are used.

**Comment by ernoaapa** [comment] 2019-08-01 10:36
@flamber I can confirm that I don't have the problem with version `0.33.0-RC1`. It works (and I start using it right away :D )

**Comment by flamber** [comment] 2019-08-01 13:57
Okay, so everything is working on RC1 - except for a confusing error?
It sounds very related to #10409, which is not displaying the full error messages on MySQL.

**Comment by flamber** [comment] 2019-08-02 16:17
In the forum, it was reported that similar error was happening on Postgres, so it's not only MySQL.
https://discourse.metabase.com/t/digital-ocean-postgres-db-cant-connect/6913

**Comment by mazameli** [comment] 2019-08-02 16:38
Just to double-check: is anyone still experiencing this in `0.33.0-RC1`? It sounds like not, but if so, this would be a p0 and we'd fix it accordingly.

I've opened #10473 to track that confusing error message problem.

**Comment by eladeyal-intel** [comment] 2019-08-05 07:30
I tried to to see if `0.33.0-RC1` solved #9629 . I don't think it did. But I did get the error message below

```
   2019-08-05T10:22:16.11+0300 [RTR/0] OUT XXXXXXX - [2019-08-05T07:22:16.081+0000] "PUT /api/database/7 HTTP/1.1" 400 527 492 "https://XXXXXXX/admin/databases/7" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36" "10.109.192.100:60604" "10.109.202.102:61881" x_forwarded_for:"10.189.15.2, 10.109.192.100" x_forwarded_proto:"https" vcap_request_id:"5b9245d4-cfc0-4d16-6b6c-39aeca734e0d" response_time:0.034589523 app_id:"7b8a883c-1db5-470a-9b38-c6685b60bf96" app_index:"0" x_b3_traceid:"4115e1e465f68469" x_b3_spanid:"4115e1e465f68469" x_b3_parentspanid:"-" b3:"4115e1e465f68469-4115e1e465f68469"
   2019-08-05T10:22:16.11+0300 [RTR/0] OUT
   2019-08-05T10:22:16.16+0300 [RTR/0] OUT XXXXXXX - [2019-08-05T07:22:16.151+0000] "GET /api/database HTTP/1.1" 200 0 544 "https://XXXXXXX/admin/databases/7" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36" "10.109.192.100:60604" "10.109.202.102:61881" x_forwarded_for:"10.189.15.2, 10.109.192.100" x_forwarded_proto:"https" vcap_request_id:"76597499-a5fc-4cb2-721d-64013c6fc24e" response_time:0.017054285 app_id:"7b8a883c-1db5-470a-9b38-c6685b60bf96" app_index:"0" x_b3_traceid:"c7117640bb5cf66a" x_b3_spanid:"c7117640bb5cf66a" x_b3_parentspanid:"-" b3:"c7117640bb5cf66a-c7117640bb5cf66a"
   2019-08-05T10:22:16.16+0300 [RTR/0] OUT
   2019-08-05T10:22:16.20+0300 [APP/PROC/WEB/0] OUT 08-05 07:22:16 DEBUG middleware.log :: PUT /api/database/7 400 6 ms (1 DB calls)
   2019-08-05T10:22:16.20+0300 [APP/PROC/WEB/0] OUT {:valid false,
   2019-08-05T10:22:16.20+0300 [APP/PROC/WEB/0] OUT  :dbname
   2019-08-05T10:22:16.20+0300 [APP/PROC/WEB/0] OUT  "class metabase.util.i18n.UserLocalizedString cannot be cast to class java.lang.String (metabase.util.i18n.UserLocalizedString is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')",
   2019-08-05T10:22:16.20+0300 [APP/PROC/WEB/0] OUT  :message
   2019-08-05T10:22:16.20+0300 [APP/PROC/WEB/0] OUT  "class metabase.util.i18n.UserLocalizedString cannot be cast to class java.lang.String (metabase.util.i18n.UserLocalizedString is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')"}
   2019-08-05T10:22:16.20+0300 [APP/PROC/WEB/0] OUT
   2019-08-05T10:22:16.25+0300 [APP/PROC/WEB/0] OUT 08-05 07:22:16 DEBUG middleware.log :: GET /api/database 200 6 ms (3 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (50 total active threads) Queries in flight: 0
```

![image](https://user-images.githubusercontent.com/20379005/62446652-f1f10900-b76b-11e9-8ddc-c654514a9be8.png)

![image](https://user-images.githubusercontent.com/20379005/62446670-059c6f80-b76c-11e9-9f0b-24a743132f8b.png)

**Comment by medexdev** [comment] 2019-08-06 20:07
I'm getting the same error message when I try to migrate hb2 to mysql. I added mysql connection information as followed.
export MB_DB_TYPE=mysql
export MB_DB_DBNAME=metabase
export MB_DB_PORT=3306
export MB_DB_USER=metabase
MB_DB_PASS=XXX
MB_DB_HOST=XXX
Then, I run /usr/bin/java -jar metabase.jar load-from-h2. Here's the output.
[root@mi-app-24 /]# /usr/bin/java -jar metabase.jar load-from-h2
08-06 13:05:55 DEBUG plugins.classloader :: Using NEWLY CREATED classloader as shared context classloader: clojure.lang.DynamicClassLoader@367795c7
08-06 13:05:55 DEBUG plugins.classloader :: Setting current thread context classloader to shared classloader clojure.lang.DynamicClassLoader@367795c7...
08-06 13:05:55 INFO metabase.util :: Loading Metabase...
08-06 13:05:55 INFO metabase.util :: Maximum memory available to JVM: 1.7 GB
08-06 13:05:58 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
 For more information, see https://metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
08-06 13:06:00 INFO metabase.driver :: Registered abstract driver :sql  🚚
08-06 13:06:03 INFO metabase.db :: Verifying mysql Database Connection ...
08-06 13:06:03 INFO metabase.driver :: Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚
Load driver :sql-jdbc took 13 ms
08-06 13:06:03 INFO metabase.driver :: Registered driver :mysql (parents: [:sql-jdbc]) 🚚
Load driver :mysql took 60 ms
08-06 13:06:03 INFO metabase.driver :: Initializing driver :sql...
08-06 13:06:03 INFO metabase.driver :: Initializing driver :sql-jdbc...
08-06 13:06:03 INFO metabase.driver :: Initializing driver :mysql...
java.lang.ClassCastException: metabase.util.i18n.UserLocalizedString cannot be cast to java.lang.String
        at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:34)
        at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:18)
        at clojure.lang.RestFn.invoke(RestFn.java:442)
        at clojure.lang.Var.invoke(Var.java:393)
        at metabase.db$fn__16327$verify_db_connection__16336$fn__16339$fn__16340.invoke(db.clj:404)
        at metabase.db$fn__16327$verify_db_connection__16336$fn__16339.invoke(db.clj:402)
        at metabase.db$fn__16327$verify_db_connection__16336.invoke(db.clj:395)
        at metabase.db$fn__16327$verify_db_connection__16336$fn__16337.invoke(db.clj:398)
        at metabase.db$fn__16327$verify_db_connection__16336.invoke(db.clj:395)
        at metabase.db$setup_db_BANG__STAR_$fn__16372.invoke(db.clj:467)
        at metabase.util$do_with_us_locale.invokeStatic(util.clj:675)
        at metabase.util$do_with_us_locale.invoke(util.clj:661)
        at metabase.db$setup_db_BANG__STAR_.invokeStatic(db.clj:466)
        at metabase.db$setup_db_BANG__STAR_.invoke(db.clj:462)
        at metabase.db$fn__16376$fn__16377.invoke(db.clj:477)
        at clojure.lang.Delay.deref(Delay.java:42)
        at clojure.core$deref.invokeStatic(core.clj:2320)
        at clojure.core$deref.invoke(core.clj:2306)
        at clojure.core$partial$fn__5839.invoke(core.clj:2623)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:237)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:231)
        at clojure.lang.Var.invoke(Var.java:384)
        at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:38)
        at metabase.cmd$load_from_h2.invoke(cmd.clj:31)
        at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:34)
        at metabase.cmd$load_from_h2.invoke(cmd.clj:31)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$apply.invoke(core.clj:660)
        at metabase.cmd$run_cmd$fn__56245.invoke(cmd.clj:119)
        at metabase.cmd$run_cmd.invokeStatic(cmd.clj:119)
        at metabase.cmd$run_cmd.invoke(cmd.clj:115)
        at clojure.lang.Var.invoke(Var.java:388)
        at metabase.core$run_cmd.invokeStatic(core.clj:132)
        at metabase.core$run_cmd.invoke(core.clj:130)
        at metabase.core$_main.invokeStatic(core.clj:141)
        at metabase.core$_main.doInvoke(core.clj:137)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at metabase.core.main(Unknown Source)
Command failed with exception: metabase.util.i18n.UserLocalizedString cannot be cast to java.lang.String
I'm using version 0.32.10

**Comment by flamber** [comment] 2019-08-06 21:52
@mazameli P1? Seems like it's hitting multiple people (also in the forum) and difficult to debug.

**Comment by bacus99** [comment] 2019-08-07 15:56
Same for me in migration

08-07 11:52:52 INFO metabase.driver :: Initializing driver :mysql...
java.lang.ClassCastException: metabase.util.i18n.UserLocalizedString cannot be cast to java.lang.String
        at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:34)
        at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:18)
        at clojure.lang.RestFn.invoke(RestFn.java:442)
        at clojure.lang.Var.invoke(Var.java:393)
        at metabase.db$fn__16327$verify_db_connection__16336$fn__16339$fn__16340.invoke(db.clj:404)
        at metabase.db$fn__16327$verify_db_connection__16336$fn__16339.invoke(db.clj:402)
        at metabase.db$fn__16327$verify_db_connection__16336.invoke(db.clj:395)
        at metabase.db$fn__16327$verify_db_connection__16336$fn__16337.invoke(db.clj:398)
        at metabase.db$fn__16327$verify_db_connection__16336.invoke(db.clj:395)
        at metabase.db$setup_db_BANG__STAR_$fn__16372.invoke(db.clj:467)
        at metabase.util$do_with_us_locale.invokeStatic(util.clj:675)
        at metabase.util$do_with_us_locale.invoke(util.clj:661)
        at metabase.db$setup_db_BANG__STAR_.invokeStatic(db.clj:466)
        at metabase.db$setup_db_BANG__STAR_.invoke(db.clj:462)
        at metabase.db$fn__16376$fn__16377.invoke(db.clj:477)
        at clojure.lang.Delay.deref(Delay.java:42)
        at clojure.core$deref.invokeStatic(core.clj:2320)
        at clojure.core$deref.invoke(core.clj:2306)
        at clojure.core$partial$fn__5839.invoke(core.clj:2623)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:237)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:231)
        at clojure.lang.Var.invoke(Var.java:384)
        at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:38)
        at metabase.cmd$load_from_h2.invoke(cmd.clj:31)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$apply.invoke(core.clj:660)
        at metabase.cmd$run_cmd$fn__56245.invoke(cmd.clj:119)
        at metabase.cmd$run_cmd.invokeStatic(cmd.clj:119)
        at metabase.cmd$run_cmd.invoke(cmd.clj:115)
        at clojure.lang.Var.invoke(Var.java:388)
        at metabase.core$run_cmd.invokeStatic(core.clj:132)
        at metabase.core$run_cmd.invoke(core.clj:130)
        at metabase.core$_main.invokeStatic(core.clj:141)
        at metabase.core$_main.doInvoke(core.clj:137)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at metabase.core.main(Unknown Source)
Command failed with exception: metabase.util.i18n.UserLocalizedString cannot be cast to java.lang.String

**Comment by aerasoft** [comment] 2019-08-10 01:23
The same issue for me 

08-10 01:21:15 ERROR metabase.core :: Metabase Initialization FAILED
java.lang.ClassCastException: class metabase.util.i18n.UserLocalizedString cannot be cast to class java.lang.String (metabase.util.i18n.UserLocalizedString is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:34)
	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:18)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at clojure.lang.Var.invoke(Var.java:393)
	at metabase.db$fn__16327$verify_db_connection__16336$fn__16339$fn__16340.invoke(db.clj:404)
	at metabase.db$fn__16327$verify_db_connection__16336$fn__16339.invoke(db.clj:402)
	at metabase.db$fn__16327$verify_db_connection__16336.invoke(db.clj:395)
	at metabase.db$fn__16327$verify_db_connection__16336$fn__16337.invoke(db.clj:398)
	at metabase.db$fn__16327$verify_db_connection__16336.invoke(db.clj:395)
	at metabase.db$setup_db_BANG__STAR_$fn__16372.invoke(db.clj:467)
	at metabase.util$do_with_us_locale.invokeStatic(util.clj:675)
	at metabase.util$do_with_us_locale.invoke(util.clj:661)
	at metabase.db$setup_db_BANG__STAR_.invokeStatic(db.clj:466)
	at metabase.db$setup_db_BANG__STAR_.invoke(db.clj:462)
	at metabase.db$fn__16376$fn__16377.invoke(db.clj:477)
	at clojure.lang.Delay.deref(Delay.java:42)
	at clojure.core$deref.invokeStatic(core.clj:2320)
	at clojure.core$deref.invoke(core.clj:2306)
	at clojure.core$partial$fn__5839.invoke(core.clj:2623)
	at metabase.core$init_BANG_.invokeStatic(core.clj:76)
	at metabase.core$init_BANG_.invoke(core.clj:55)
	at metabase.core$start_normally.invokeStatic(core.clj:122)
	at metabase.core$start_normally.invoke(core.clj:116)
	at metabase.core$_main.invokeStatic(core.clj:142)
	at metabase.core$_main.doInvoke(core.clj:137)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
08-10 01:21:15 INFO metabase.core :: Metabase Shutting Down ...
08-10 01:21:15 INFO metabase.server :: Shutting Down Embedded Jetty Webserver

**Comment by camsaul** [comment] 2019-08-14 18:42
@walterl This is related to the i18n stuff and once your changes are merged I think this issue should be resolved. Can you verify that this is fixed once they're merged?

**Comment by camsaul** [comment] 2019-08-14 18:44
Also: it sounds like the issue is that something about the MySQL connection details are wrong (e.g. wrong username or password) but instead of displaying the actual error message it's failing somewhere because it's getting back an `UserLocalizedString` object when it expected a plain `String`

**Comment by walterl** [comment] 2019-08-14 18:53
@camsaul Yes, that all sounds accurate. I confirmed that the `UserLocalizedString` error was caused by a `tru` call that was not passed to `str` right when I picked up #10473, which @mazameli wisely split out.

From the discussions here, it certainly looks like #10571 will fix this too. :+1:

**Comment by camsaul** [comment] 2019-08-14 18:58
It sounds like #10473 is the same issue

**Comment by walterl** [comment] 2019-08-14 19:13
Ha! Seems like the general i18n fix we went for in #10571 resulted in this specific issue _not_ being fixed. A fix is being tested now.

It's a good thing you reminded me to check this again, @camsaul.

**Closed** 2019-08-14 20:44 UTC
Labels: Admin Panel & Setup, Database/MySQL, Priority:P1, Type:Bug

**Comment by zerho** [comment] 2020-10-01 18:49
This is still happening on Metabase version v0.36.6

**Logs**
api response:
`{"valid":false,"dbname":"Index 1 out of bounds for length 1","message":"Index 1 out of bounds for length 1"}`

Server logs:
```Database connection error
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.mariadb.jdbc.HostAddress.parseSimpleHostAddress(HostAddress.java:167)
	at org.mariadb.jdbc.HostAddress.parse(HostAddress.java:138)
```

**Comment by robdaemon** [comment] 2020-10-01 19:28
@zerho That appears to be a different error than this issue was originally. Can you open a new issue? This is likely an issue in the JDBC driver we use.
