### ISSUE TITLE
User Details / Password off-center in Account Settings

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#3129] opened 2016-08-05 00:29 UTC
This is in 0.19.1 in the Mac App running in El Capitan.

![screen shot 2016-08-04 at 5 27 46 pm](https://cloud.githubusercontent.com/assets/1455846/17422653/cebbd05e-5a68-11e6-8b98-4982041f1ea1.png)

**Comment by kdoh** [comment] 2016-12-30 00:20
I'm not able to reproduce this in the latest version of the Mac App or in other versions of Metabase running 0.21.* so I'm going to close this. If you see it again @camsaul feel free to re-open.

**Closed by kdoh** 2016-12-30 00:20 UTC
Labels: Admin Panel & Setup, CSS
