### ISSUE TITLE
BE flake: metabase.pulse-test/multiple-recipients-test

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#43130] opened 2024-05-24 16:50 UTC
example failure [here](https://github.com/metabase/metabase/actions/runs/9179973284/job/25243349924#step:6:1180)

logs:

```
FAIL in metabase.pulse-test/multiple-recipients-test (pulse_test.clj:397)
Pulse should be sent to two recipients sent to :email channel 
with temporary :model/Card with attributes
{:creator_id 1,
 :database_id 1,
 :dataset_query
 {:database 1,
  :type :query,
  :query {:source-table 8, :aggregation [["count"]], :breakout [[:field 49 {:temporal-unit :day}]]}},
 :display :line,
 :name "Test card",
 :visualization_settings {:graph.dimensions ["DATE"], :graph.metrics ["count"]},
 :created_at #t "2024-05-21T19:11:19.102324Z[UTC]",
 :updated_at #t "2024-05-21T19:11:19.102325Z[UTC]"}

 
with temporary :model/Pulse with attributes
{:creator_id 1,
 :name "Pulse Name",
 :created_at #t "2024-05-21T19:11:19.122568Z[UTC]",
 :updated_at #t "2024-05-21T19:11:19.122569Z[UTC]"}

 
with temporary :model/PulseCard with attributes
{:position 0, :include_csv false, :include_xls false, :pulse_id 267, :card_id 1800}

 
with temporary :model/PulseChannel with attributes
{:channel_type :email,
 :details {},
 :schedule_type :daily,
 :schedule_hour 15,
 :created_at #t "2024-05-21T19:11:19.127194Z[UTC]",
 :updated_at #t "2024-05-21T19:11:19.127195Z[UTC]",
 :pulse_id 267}

 
with temporary :model/PulseChannelRecipient with attributes
{:user_id 1, :pulse_channel_id 167}

 
Setting :email-smtp-host = "fake_smtp_host"
 
Setting :email-smtp-port = 587
 
Setting :site-url = "https://metabase.com/testmb"
 
with temporary :model/PulseChannelRecipient with attributes
{:user_id 3, :pulse_channel_id 167}


expected: {"crowberto@metabase.com" [{:bcc #{"crowberto@metabase.com"
                                             "rasta@metabase.com"},
                                      :body [{"Pulse Name" true}
                                             {:content #<Class@1a6c5a9e java.net.URL>,
                                              :content-id true,
                                              :content-type "image/png",
                                              :type :inline}
                                             {:content #<Class@1a6c5a9e java.net.URL>,
                                              :content-id true,
                                              :content-type "image/png",
                                              :type :inline}],
                                      :from "notifications@metabase.com",
                                      :subject "Pulse: Pulse Name"}],
           "rasta@metabase.com" [{:bcc #{"crowberto@metabase.com"
                                         "rasta@metabase.com"},
                                  :body [{"Pulse Name" true}
                                         {:content #<Class@1a6c5a9e java.net.URL>,
                                          :content-id true,
                                          :content-type "image/png",
                                          :type :inline}
                                         {:content #<Class@1a6c5a9e java.net.URL>,
                                          :content-id true,
                                          :content-type "image/png",
                                          :type :inline}],
                                  :from "notifications@metabase.com",
                                  :subject "Pulse: Pulse Name"}]}
  actual: {}
```

The test fails because there is no matching email in the inbox.

The first flake happened on May 17. It has flaked at least 6 times since then (writing this on 24 May). [Source here](https://stats.metabase.com/question#eyJuYW1lIjoiVGVzdCBmbGFrZXMgYnkgc3VpdGUgbmFtZSBhbmQgdGVzdCBuYW1lIChub3QgUVApIiwiZGVzY3JpcHRpb24iOiJodHRwczovL3N0YXRzLm1ldGFiYXNlLmNvbS9tb2RlbC8xNDgyOC10ZXN0LWZsYWtpbmVzcyIsImRhdGFzZXRfcXVlcnkiOnsiZGF0YWJhc2UiOjI2LCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJhZ2dyZWdhdGlvbiI6W1siY291bnQiXSxbIm1pbiIsWyJmaWVsZCIsIndvcmtmbG93X3J1bl91cmwiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dXV0sImJyZWFrb3V0IjpbWyJmaWVsZCIsInN1aXRlX25hbWUiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLFsiZmllbGQiLCJ0ZXN0X25hbWUiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLFsiZmllbGQiLCJ3b3JrZmxvd19ydW5fc3RhcnRlZF9hdCIseyJiYXNlLXR5cGUiOiJ0eXBlL0RhdGVUaW1lV2l0aExvY2FsVFoiLCJ0ZW1wb3JhbC11bml0IjoiZGF5In1dXSwic291cmNlLXRhYmxlIjoiY2FyZF9fMTQ4MjgiLCJmaWx0ZXIiOlsiYW5kIixbImRvZXMtbm90LWNvbnRhaW4iLFsiZmllbGQiLCJzdWl0ZV9uYW1lIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwicXVlcnktcHJvY2Vzc29yIix7ImNhc2Utc2Vuc2l0aXZlIjpmYWxzZX1dLFsiY29udGFpbnMiLFsiZmllbGQiLCJ3b3JrZmxvd19qb2JfbmFtZSIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sImJlLXRlc3RzLSIseyJjYXNlLXNlbnNpdGl2ZSI6ZmFsc2V9XSxbIj0iLFsiZmllbGQiLCJ0ZXN0X25hbWUiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCJtdWx0aXBsZS1yZWNpcGllbnRzLXRlc3QiXV19fSwiZGlzcGxheSI6InRhYmxlIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJwYXJhbWV0ZXJzIjpbXSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJ0YWJsZS5waXZvdF9jb2x1bW4iOiJzdWl0ZV9uYW1lIiwidGFibGUuY2VsbF9jb2x1bW4iOiJjb3VudCIsInRhYmxlLnBpdm90IjpmYWxzZSwidGFibGUuY29sdW1ucyI6W3sibmFtZSI6InN1aXRlX25hbWUiLCJrZXkiOiJbXCJuYW1lXCIsXCJzdWl0ZV9uYW1lXCJdIiwiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiZmllbGQiLCJzdWl0ZV9uYW1lIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XX0seyJuYW1lIjoidGVzdF9uYW1lIiwia2V5IjoiW1wibmFtZVwiLFwidGVzdF9uYW1lXCJdIiwiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiZmllbGQiLCJ0ZXN0X25hbWUiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dfSx7Im5hbWUiOiJjb3VudCIsImtleSI6IltcIm5hbWVcIixcImNvdW50XCJdIiwiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiYWdncmVnYXRpb24iLDBdfSx7Im5hbWUiOiJ3b3JrZmxvd19ydW5fc3RhcnRlZF9hdCIsImtleSI6IltcIm5hbWVcIixcIndvcmtmbG93X3J1bl9zdGFydGVkX2F0XCJdIiwiZmllbGRSZWYiOlsiZmllbGQiLCJ3b3JrZmxvd19ydW5fc3RhcnRlZF9hdCIseyJiYXNlLXR5cGUiOiJ0eXBlL0RhdGVUaW1lV2l0aExvY2FsVFoiLCJ0ZW1wb3JhbC11bml0IjoiZGF5In1dLCJlbmFibGVkIjp0cnVlfSx7Im5hbWUiOiJtaW4iLCJrZXkiOiJbXCJuYW1lXCIsXCJtaW5cIl0iLCJmaWVsZFJlZiI6WyJhZ2dyZWdhdGlvbiIsMV0sImVuYWJsZWQiOnRydWV9XSwiY29sdW1uX3NldHRpbmdzIjp7IltcIm5hbWVcIixcImNvdW50XCJdIjp7ImNvbHVtbl90aXRsZSI6IkNvdW50In0sIltcIm5hbWVcIixcIm1heFwiXSI6eyJjb2x1bW5fdGl0bGUiOiJMYXN0IGZhaWxlZCBydW4ifSwiW1wibmFtZVwiLFwibWF4XzJcIl0iOnsiY29sdW1uX3RpdGxlIjoiTGFzdCBmYWlsZWQgZGF0ZSIsImRhdGVfc3R5bGUiOiJNTU1NIEQsIFlZWVkiLCJ0aW1lX2VuYWJsZWQiOm51bGx9fX0sIm9yaWdpbmFsX2NhcmRfaWQiOjE1MjEyfQ==). It's interesting that the failures appear clustered on certain days, and not evenly distributed.

@Ngoc because this might have something to do with the pulse changes you merged to master on May 7

This flake is very similar and likely related: https://github.com/metabase/metabase/issues/43321

**Comment by qnkhuat** [comment] 2024-05-30 03:48
Tried to reproduce this today without any luck so far.

I don't think it relates to the recent change I made with pulse because those changes are purely about how pulses are scheduled. These tests are about pulse behavior.

It's interesting that both flaky tests are related to email tho.

**Comment by qnkhuat** [comment] 2024-06-21 03:28
Fixed by reworking how test setup works in https://github.com/metabase/metabase/pull/43924

**Closed by qnkhuat** 2024-06-21 03:28 UTC
Labels: .CI & Tests, flaky-test-fix, .Team/BackendComponents
