### ISSUE TITLE
v0.39.0.1: French localization - "{0}" instead of real values in strings interpolations on the UI

### ISSUE THREAD

**Issue by incyclum** [metabase/metabase#15832] opened 2021-04-27 15:24 UTC
Hi all!

I noticed "{0}" in strings like in "Showing {0} rows" in question pages
or other multiple uninterpolated places like the reset password strengths requirements.
I'm on french localization.

When I switch to English the problem disappears.

Thank you

**Comment by flamber** [comment] 2021-04-27 15:29
Duplicate of #15694

**Closed by flamber** 2021-04-27 15:29 UTC
Labels: .Needs Triage, Type:Bug

**Comment by incyclum** [comment] 2021-04-27 16:19
Thank you @flamber, I missed it even with searching with "{0}" in issue tab 🤔
