### ISSUE TITLE
select 'Previous 7 Days, starting 2 days ago' but responsed 8 days

### ISSUE THREAD

**Issue by ZhianLin** [metabase/metabase#27479] opened 2023-01-02 08:35 UTC
**Describe the bug**
select 7days but responsed 8days

**Logs**
No trouble logs.

**To Reproduce**
1. set time Component map to datetime field in table.
2. set Filter widget type on "Data Filter"
3. set day at the 'past' page,choose starting 2 days ago,it showed  'Dec 24, 2022 - Dec 30, 2022'
 ![set day](https://s1.ax1x.com/2023/01/02/pSP8cuV.png)

**Expected behavior**
 Dec 24, 2022 - Dec 30, 2022 not Dec 24, 2022 - Dec 31, 2022

**Screenshots**
[![responsed 8days](https://s1.ax1x.com/2023/01/02/pSP8og1.md.png)](https://imgse.com/i/pSP8og1)

**Information about your Metabase Installation:**
-  Chrome 108.0.5359.125
-  Windows 10.1809
- Databases: Postgres 13 or MSSQL 2012
- Metabase version:  1.44.4
- Metabase hosting environment:Docker
- Metabase internal database: Postgres

**Additional context**
It responsed 7days ,Only when I chose 'Previous 7 Days, starting 1 days ago'.

**Comment by flamber** [comment] 2023-01-02 09:00
Duplicate of #25481

**Closed by flamber** 2023-01-02 09:00 UTC
Labels: Type:Bug, .Needs Triage
