### ISSUE TITLE
Custom fields act weird when using new show/hide field settings

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8185] opened 2018-08-01 00:05 UTC
This is in 0.30-rc1.

- Do a raw data query
- In the visualization settings, add or remove a field or two
- Try creating a custom field and running your query. **You won't see your new field**, though I would expect to.
- If you go back into the visualization settings, you'll see your custom field listed, and you can add it in here.

![custom-field-with-add-fields](https://user-images.githubusercontent.com/2223916/43493542-5e6234e4-94e3-11e8-830c-9c04cb6383f0.gif)

- Not depicted in the GIF, if you try to delete your custom field _before_ removing it from the visible fields in the viz settings, **you'll hit an error**.

![screen shot 2018-07-31 at 5 04 02 pm](https://user-images.githubusercontent.com/2223916/43493624-c311fdb6-94e3-11e8-803f-e3d95880f4d1.png)

**Comment by jwarshaw** [comment] 2018-10-02 17:54
I have experienced a very similar issue. The difference being the custom field is NOT available in the visualization settings for me to add to the table. The custom field is selectable in the 'filter' dropdown and the 'grouped by' dropdown. If I use the visualization settings to display all fields and then recreate the custom field it is still not available for me to add to the table. I can only add custom fields to a question which I have not made changes to the columns displayed.

Chrome Version 69.0.3497.100
Ubuntu 18.04.1 LTS
MySQL
Metabase version v0.28.5
Elastic Beanstalk

Repeatable steps:
* Create a question
* Use the visualization settings to remove a column from the displayed table
* Create a custom field
Result: The custom field does not append to the displayed table nor does it appear in the list of fields in the visualization settings.

**Comment by flamber** [comment] 2019-02-20 20:15
First part of this issue is related to #6670 (#7612)
And has a workaround (as of 0.31.2) where you click the `Reset to defaults` in the table settings :gear: 

Second part, where removing Custom Field after changing visualization settings, can be reproduced on 0.31.2
And the same problem appears if you sort by a custom field, then remove the custom field.
Seems like Custom Field isn't cleaning up after itself.

**Comment by flamber** [comment] 2020-05-28 10:58
I cannot reproduce on 0.35.3 - fairly sure it was fixed in 0.33.0

**Closed by flamber** 2020-05-28 10:58 UTC
Labels: Type:Bug, Visualization/Chart Settings
