### ISSUE TITLE
improved dashboard organization 

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#2326] opened 2016-04-07 00:07 UTC
Just like in #2204 we want to give you tools to add meaning and structure to your list of dashboards, and make sure those tools scale as your company does. (he said scale, points to gryffindor).

![dashboard_page](https://cloud.githubusercontent.com/assets/5248953/14336759/f73f08bc-fc1b-11e5-9658-9183b98f6c81.png)

Some example problems:
- We have 3 dashboards just for the marketing team. How do I find them quickly teams.
- We need to retire the first version of our KPI dashboard, but need to keep it for posterity.
- I reference a set of dashboards all the time, how do I get to them quickly?

The new dashboard listing page will feature the same set of functionality as the new saved questions page: (here's a quick overview, but see #2204 for all the details)
- The ability to add labels label dashboards 
- Archiving dashboards (https://github.com/metabase/metabase/issues/1874)
- Favoriting dashboards
- Quick filters to view dashboards you've made, popular dashboards, recently viewed dashboards, and any dashboards you may have favorited.

One exception from the functionality between questions and dashboards at this stage is the notion of viewing dashboards by "topics", since dashboards can contain data referencing many aspects of your business.

As always we'd love to get feedback on this proposed design so please weigh in on these features and let us know if they'll help with managing your dashboards!

**Comment by agilliland** [comment] 2016-04-07 00:30
My only negative on this design is that it removes the dropdown menu for dashboards and thus forces an extra click & page load in order to reach dashboards.  My thinking is ...

1. not all teams have so many dashboards that the dropdown is unmanageable, in this case all we've accomplished is adding clicks.
2. even when there are many dashboards it's common for a user to go back to a small handful of them most of the time, so it's nice when they are easy to get to.
3. I personally find that when I'm looking at data I will jump from one dash to another and check out maybe 3 dashboards in a row, which will now require clicking to the listing page first, then getting to the dashboard :disappointed: 
4. overall this makes MB __feel__ more like a website and less like an application.

To offer a constructive option.  I think it would be preferable if the dropdown remained and perhaps just showed the top N dashboards recently visited by the user, or some sensible mixture of the users dashboard views plus recent dashboards from the whole MB instance.  Then at the bottom of the dropdown there could be a link to the full listing page for users to access when needed.

**Comment by moumny** [comment] 2016-06-17 13:12
Totally makes sense !
If i may suggest, we can put "favorites"+users dashboard there so that the list is decided by the user and fixed.
(If you use the agile dropdown of JIRA you will know that recent visited dashboards is a bad idea)

**Comment by MrMauricioLeite** [comment] 2016-06-18 14:35
I completely agree that this is a desired improvement on organization.
Thanks @kdoh for the design.
And again @agilliland pointed a great customer centered matter, the dropdown that we all love is going away.

But as @moumny just said, we may use the dropdown but populated with users favorite dashboards. That is really a great idea. 

What I want to know is:
how can I help?
Do you guys have a to-do list for that?

**Comment by lately** [comment] 2016-06-28 01:13
Search + labels seems like a pretty solid solution. I was imagining a more structured ordering + grouping, but I don't see why this isn't better. 

To Allen's point, quick dropdown shortcuts seem nice, too. Populating with e.g. "Most frequently visited in last X days" may help overcome some of the challenges with "most recently visited" that @moumny points out.

**Comment by jesusrtc** [comment] 2016-09-28 03:37
+1

**Comment by mazameli** [comment] 2017-03-24 23:44
It's been a while since we've taken a look at this issue. Metabase has changed a fair amount since Kyle created the designs in this issue description, so I'm going to propose the following bite-sized, additive designs in order to solve some of the basic problems that still exist with dashboards in Metabase.

**1: Give dashboards their own screen**
All this requires is a new `Dashboards` section that replaces the dropdown. The only new functionality is the ability to filter the list of dashboards. This solves the problem of having more dashboards than the dropdown can handle, and finding a specific dashboard amidst many. The date below the name of the dashboard is the date it was last modified (which might = its creation date).

![01 most basic](https://cloud.githubusercontent.com/assets/2223916/24316910/46a71c84-10af-11e7-9392-f00d36f6e2eb.png)

**2: filtering and favorites**
Adds the same kind of filter as we have on lists of questions, and adds the ability to mark dashboards as favorites (starring them).

![02 filtering and favorites](https://cloud.githubusercontent.com/assets/2223916/24316863/ae7a56d8-10ae-11e7-8d40-8703e38c4b7d.png)

**3: archiving (and other actions)**
Adds the ability to archive dashboards, and a button to view the archive (my presumption would be that they'd be listed in the same über archive as questions and collections):

![03 archive and other actions](https://cloud.githubusercontent.com/assets/2223916/24316864/ae7fad04-10ae-11e7-9491-69c134a3d72f.png)

**4: Reordering dashboards**
Click and drag to move them around:

![04 move and reorder](https://cloud.githubusercontent.com/assets/2223916/24316866/ae87ae32-10ae-11e7-9861-325c85be86f8.png)

**5: toggle from grid view to list view**
Grid view:

![05a list and grid toggle](https://cloud.githubusercontent.com/assets/2223916/24316865/ae86a690-10ae-11e7-9e47-a2f45657f814.png)

List view: 

![05b list view](https://cloud.githubusercontent.com/assets/2223916/24316867/ae8abcee-10ae-11e7-89e7-a2ab870b022d.png)


**side note**
I did a bunch of explorations where I made each dashboard have a sort of abstracted tile representation like this, but I think it might be fairly complicated to take a dashboard's layout and dynamically create the little micro cards that these tiles display. Not to mention it's totally cosmetic/aesthetic:

![bigger tiles](https://cloud.githubusercontent.com/assets/2223916/24317054/0cc47ae6-10b1-11e7-9885-1b2888bbefb0.png)

**Comment by salsakran** [comment] 2017-03-24 23:50
Like it. Not personally convinced of the need for 5, but I'm a strong 👍  for 1-4

**Comment by luissancho** [comment] 2017-03-27 07:03
I think all 1 to 5 are really great improvement, list view offers more info in less space, so I'd also add it as an option.

**Comment by tlrobinson** [comment] 2017-03-27 19:19
Duplicate of #1150? More discussion here so we should close that one if so.

**Comment by mazameli** [comment] 2017-03-27 19:24
I think #1150 is a subset of this issue — it only really refers to reordering. I don't care if we close #1150.

**Comment by camsaul** [comment] 2017-03-27 19:33
Yeah I think closing #1150 in favor of this makes sense

**Comment by moumny** [comment] 2017-04-05 08:55
Great to see this happening ! We have 20-30 dashboards and the dropdown is getting very long.

Would it be possible to have "official" dashboards pinned by Admins ?
Could be a separate section or just a "tag"

**Comment by mazameli** [comment] 2017-05-01 17:46
Resolved by https://github.com/metabase/metabase/pull/4868 and https://github.com/metabase/metabase/pull/4698

**Closed by mazameli** 2017-05-01 17:46 UTC
Labels: Dashboards, Help Wanted, New Feature

**Comment by TomUssery** [comment] 2017-05-08 19:18
Taken from Ticket 4900

These solutions are nice, but can we still incorporate a folder structure? 

Our business has over 40 clients, each that will require multiple dashboards. Is there a way to organize the dashboards in the drop down? Ideal State would be - 

Client 1 >
Client 2>
Dash 1
Dash 2
Dash 3
Client 3>
Dash 1
Dash 2
Dash 3

**Comment by TomUssery** [comment] 2017-05-08 19:18
Also, when do you see this rolling out (any of the solutions you have proposed)?
