### ISSUE TITLE
BigInt (timestamp) variable filter field not working correctly for Native queries - casting issue for Postgres

### ISSUE THREAD

**Issue by aaron-coolfront** [metabase/metabase#5071] opened 2017-05-10 21:18 UTC
When attempting to define the following variable for a native query:
```
select * from "Invoice"
where "companyId" = {{company_id}}::uuid
and {{date_range}}
limit 5
```

*Filter label*: Date range
*Variable type*: Field Filter
*Field*: INVOICE, System Updated Time <--- this is a bigint unix timestamp
*Widget*: Month and Year

The query that gets generated is not casting the field we have as a bigint unix timestamp correctly to a date.

``` 
QUERY: ??
 {:database 2,
  :type "native",
  :native
  {:query "select * from \"Invoice\"\nwhere \"companyId\" = {{company_id}}::uuid\nand {{date_range}}\nlimit 5",
   :template_tags
   {:company_id {:id "dc51c2c7-1257-1876-8900-ac39b34f297f", :name "company_id", :display_name "Company", :type "text", :required true},
    :date_range
    {:id "01fa7274-e25e-a8a5-b87e-61785cd6f3c4", :name "date_range", :display_name "Date range", :type "dimension", :dimension ["field-id" 639], :default "today", :widget_type "date/month-year"}}},
  :parameters
  [{:type "category", :target ["variable" ["template-tag" "company_id"]], :value "918592f3-0d76-409f-a6ed-2629d341a48a"}
   {:type "date/month-year", :target ["dimension" ["template-tag" "date_range"]], :value "2017-04"}],
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :query-hash [-111, -86, 39, 102, 35, 82, 7, 102, 7, -26, -22, -87, 115, -107, 9, 103, -24, -64, -106, 17, -28, -48, -53, -81, -23, 27, -103, 122, -112, 123, -23, -39],
   :query-type "native"}}
 
 05-10 21:11:03 DEBUG query-processor.sql-parameters :: PARAM INFO: ??
 ({:param-key :company_id,
   :original-snippet "{{company_id}}",
   :variable-snippet "{{company_id}}",
   :optional-snippet nil,
   :replacement-snippet "?",
   :prepared-statement-args ("918592f3-0d76-409f-a6ed-2629d341a48a")}
  {:param-key :date_range,
   :original-snippet "{{date_range}}",
   :variable-snippet "{{date_range}}",
   :optional-snippet nil,
   :replacement-snippet "CAST(\"public\".\"Invoice\".\"systemUpdatedTime\" AS date) BETWEEN ? AND ?",
   :prepared-statement-args [#inst "2017-04-01T00:00:00.000000000-00:00" #inst "2017-04-30T00:00:00.000000000-00:00"]})
 
 05-10 21:11:03 DEBUG middleware.parameters :: 
 
 PARAMS/SUBSTITUTED: ??
 {:native
  {:query "select * from \"Invoice\"\nwhere \"companyId\" = ?::uuid\nand CAST(\"public\".\"Invoice\".\"systemUpdatedTime\" AS date) BETWEEN ? AND ?\nlimit 5",
   :params ("918592f3-0d76-409f-a6ed-2629d341a48a" #inst "2017-04-01T00:00:00.000000000-00:00" #inst "2017-04-30T00:00:00.000000000-00:00")}}
 
 05-10 21:11:03 DEBUG query-processor.permissions :: Permissions Check ?? : Does user have permissions for /db/2/native/?
 05-10 21:11:03 DEBUG query-processor.permissions :: Permissions Check ?? : Yes ?  because user has permissions for /.
 05-10 21:11:03 DEBUG middleware.mbql-to-native :: NATIVE FORM: ??
 {:query "select * from \"Invoice\"\nwhere \"companyId\" = ?::uuid\nand CAST(\"public\".\"Invoice\".\"systemUpdatedTime\" AS date) BETWEEN ? AND ?\nlimit 5",
  :template_tags
  {:company_id {:id "dc51c2c7-1257-1876-8900-ac39b34f297f", :name "company_id", :display_name "Company", :type "text", :required true},
   :date_range
   {:id "01fa7274-e25e-a8a5-b87e-61785cd6f3c4", :name "date_range", :display_name "Date range", :type "dimension", :dimension ["field-id" 639], :default "today", :widget_type "date/month-year"}},
  :params ("918592f3-0d76-409f-a6ed-2629d341a48a" #inst "2017-04-01T00:00:00.000000000-00:00" #inst "2017-04-30T00:00:00.000000000-00:00")}
 
 PSQLException:
  Message: ERROR: cannot cast type bigint to date
   Position: 176
  SQLState: 42846
```

Chrome 57.0.2987.133 (Official Build) (32-bit)
Windows 7
Postgres
Metabase 0.23.1 hosted on Heroku
Metabase internal db - Postgres

**Comment by camsaul** [comment] 2017-05-10 21:20
Sounds like a duplicate of #4058

**Comment by mazameli** [comment] 2020-02-29 00:52
Closing as duplicate of #4058

**Closed by mazameli** 2020-02-29 00:52 UTC
Labels: .Duplicate, Database/Postgres, Priority:P3, Querying/Native, Type:Bug
