### ISSUE TITLE
Error in `TO_TIMESTAMP` for `NUMERIC` data type [already fixed -- add test]

### ISSUE THREAD

**Issue by Shashwat986** [metabase/metabase#7487] opened 2018-04-29 09:14 UTC
I have an Amazon Redshift table in which my `timestamp` field is of the `NUMERIC` data type.
When I use the Data Model tool to change the type of the `timestamp` field to `UNIX Timestamp (Seconds)`, it throws the following error:

```
[Amazon](500310) Invalid operation: function to_timestamp(numeric) does not exist
```

##### Possible Solution?
- I'm assuming the solution will be to cast to string before running `TO_TIMESTAMP`. That should take care of most edge. That definitely works if I use custom SQL for the same problem.
- Is there any other way we can deal with this?

### Information
- Metabase Version: 0.26.2
- Database: Amazon Redshift

Do let me know if anything else is required.

**Comment by Shashwat986** [comment] 2018-04-29 09:15
This happens with the `NUMERIC` data type and `UNIX Timestamp (Seconds)`. I tried testing this with the `DECIMAL` data type (in another DB, so not exactly the same), and the error was not happening, weirdly enough. Not sure what the issue may be.

With `DECIMAL`, the SQL translates to `(TIMESTAMP '1970-01-01T00:00:00Z' + ("public"."table"."time_stamp" * INTERVAL '1 second'))` which doesn't throw any errors.

Can someone help me confirm?

**Comment by jeff303** [comment] 2021-01-26 21:36
@Shashwat986 , any chance you can check again the most recent version?  I'm not able to reproduce this now (see screenshots).  Table DDL was: `CREATE TABLE tbl_with_ts(pk INT PRIMARY KEY NOT NULL, ts NUMERIC(12));`

<img width="1288" alt="Redshift_NUMERIC_timestamp_model" src="https://user-images.githubusercontent.com/3521562/105908709-2c97d280-5fec-11eb-805d-4deeb4964daa.png">
<img width="342" alt="Redshift_NUMERIC_timestamp_query" src="https://user-images.githubusercontent.com/3521562/105908711-2d306900-5fec-11eb-9ea4-b5d848051fc9.png">

**Comment by camsaul** [comment] 2021-04-23 00:42
It sounds like this was is already fixed, so let's add a test for it and close it out

**Comment by camsaul** [comment] 2022-01-20 21:12
Test added in #19810

**Closed by camsaul** 2022-01-20 21:12 UTC
Labels: Type:Tech Debt, Database/Redshift, Good Backend Starter Issue
