### ISSUE TITLE
Scroll bar starts to above table

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#773] opened 2015-07-22 02:13 UTC
Well this is obviously not a huge deal but I feel like the top of the scroll bar should be the first row of the results since the column names don't scroll

![screenshot 2015-07-21 19 11 45](https://cloud.githubusercontent.com/assets/1455846/8816482/63eccbfa-2fdc-11e5-8464-6aefc48cea28.png)

**Comment by kdoh** [comment] 2016-01-26 16:46
I haven't noticed this in a while. Just checked in Chrome (v47), Safari (v9) and Firefox (v41) and I'm not able to reproduce it. My guess is this got inadvertently fixed, when @tlrobinson was working on some of the column size adjustments. If someone on @metabase/core-developers could quickly double check then I think we can close this one out.

**Comment by agilliland** [comment] 2016-01-26 16:59
I just checked and I can't reproduce it either.  Closing it.

**Closed by agilliland** 2016-01-26 16:59 UTC
Labels: Bug, Visualization
