### ISSUE TITLE
Variables pane/button doesn't show up in SQL editor on fresh install until page is refreshed

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#10927] opened 2019-09-18 19:58 UTC
On `release-0.33.x` branch. Steps to repro:

*  Launch fresh instance of Metabase
*  Complete setup, go directly to "New Question" screen, create native query
*  Type a query with template params like `{{whatever}}`

Expected: Variables pane to pop up
Actual: Nothing. `X` (variables) button does not appear.

Refreshing the page causes the button to appear.

It sounds like this is related to the complex of issues where newly added databases don't have full information in the client until you completely refresh the page -- see #10330, #9517, #5129, etc. See also: #10524 

Marking as P1 [because this is related to Query Builder](https://github.com/metabase/metabase/wiki/Bug-Prioritization)

**Comment by paulrosenzweig** [comment] 2019-09-20 21:25
@camsaul, I can't repro this. To simulate a new install, I'm deleting the H2 files and restarting. Is that enough?

Redux doesn't have any databases during the setup process, but we fetch them when you land on the question.

**Comment by tlrobinson** [comment] 2019-09-20 21:49
Could it be a race condition with sync or something?

**Comment by camsaul** [comment] 2019-10-05 01:02
I'm guessing it's a race condition with not having the `:features` set for the sample data DB because that metadata doesn't get reloaded until you refresh the page

**Comment by Elest** [comment] 2020-03-25 10:24
Hey @flamber 

We started to use Snowflake on Metabase version v0.34.3.  And when I try to write a date parameter, it is not recognized and side panel doesn't open... I guess this issue is discussed here, right? What would be your suggestion to that?

Thanks in advance!

**Comment by flamber** [comment] 2020-03-27 11:55
@Elest Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by flamber** [comment] 2021-04-08 12:46
I can consistently reproduce on an instance with many different database types, where I startup the instance and go directly to Native query after login, and select one of the non-core databases (like BigQuery). This is on 0.39.0-rc1
![image](https://user-images.githubusercontent.com/1447303/114025838-dbbb1a80-9875-11eb-9f9a-494ede07935a.png)

It's likely caused by two `GET /api/database` requests:
1. First is fast (milliseconds) to `/api/database?include=tables`
2. Second is slow (5+ seconds) to `/api/database?saved=true` - should this even be loaded for Native queries?

```
2021-04-08 14:27:20,531 INFO driver.impl :: Initializing driver :sqlserver...
2021-04-08 14:27:20,532 INFO plugins.classloader :: Added URL file:/home/hansen/Downloads/Metabase/plugins/sqlserver.metabase-driver.jar to classpath
2021-04-08 14:27:20,533 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.sqlserver...
2021-04-08 14:27:20,585 DEBUG middleware.log :: GET /api/collection 200 55.5 ms (3 DB calls) App DB connections: 3/7 Jetty threads: 7/50 (2 idle, 0 queued) (50 total active threads) Queries in flight: 0 (0 queued)
2021-04-08 14:27:20,627 DEBUG middleware.log :: GET /api/database 200 329.1 ms (4 DB calls) App DB connections: 1/7 Jetty threads: 6/50 (2 idle, 0 queued) (50 total active threads) Queries in flight: 0 (0 queued)
2021-04-08 14:27:20,632 DEBUG middleware.log :: GET /api/native-query-snippet 200 107.2 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (2 idle, 0 queued) (50 total active threads) Queries in flight: 0 (0 queued)
2021-04-08 14:27:20,642 INFO driver.impl :: Registered driver :sqlserver (parents: [:sql-jdbc]) 🚚
2021-04-08 14:27:21,107 DEBUG plugins.jdbc-proxy :: Registering JDBC proxy driver for com.microsoft.sqlserver.jdbc.SQLServerDriver...
Load lazy loading driver :sqlserver took 575.5 ms
2021-04-08 14:27:21,144 INFO driver.impl :: Initializing driver :postgres...
2021-04-08 14:27:21,147 INFO driver.impl :: Initializing driver :mongo...
2021-04-08 14:27:21,148 INFO plugins.classloader :: Added URL file:/home/hansen/Downloads/Metabase/plugins/mongo.metabase-driver.jar to classpath
2021-04-08 14:27:21,148 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.mongo...
2021-04-08 14:27:23,633 INFO driver.impl :: Registered driver :mongo  🚚
Load lazy loading driver :mongo took 2.6 s
2021-04-08 14:27:23,776 INFO driver.impl :: Initializing driver :google...
2021-04-08 14:27:23,777 INFO plugins.classloader :: Added URL file:/home/hansen/Downloads/Metabase/plugins/google.metabase-driver.jar to classpath
2021-04-08 14:27:23,784 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.google...
2021-04-08 14:27:23,816 INFO driver.impl :: Registered abstract driver :google  🚚
Load lazy loading driver :google took 226.0 ms
2021-04-08 14:27:24,011 INFO driver.impl :: Initializing driver :bigquery...
2021-04-08 14:27:24,011 INFO plugins.classloader :: Added URL file:/home/hansen/Downloads/Metabase/plugins/bigquery.metabase-driver.jar to classpath
2021-04-08 14:27:24,012 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.google...
2021-04-08 14:27:24,013 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.bigquery...
2021-04-08 14:27:24,667 INFO driver.impl :: Registered driver :bigquery (parents: [:sql :google]) 🚚
Load lazy loading driver :bigquery took 835.7 ms
2021-04-08 14:27:24,851 INFO driver.impl :: Initializing driver :oracle...
2021-04-08 14:27:24,853 INFO plugins.classloader :: Added URL file:/home/hansen/Downloads/Metabase/plugins/oracle.metabase-driver.jar to classpath
2021-04-08 14:27:24,854 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.oracle...
2021-04-08 14:27:24,881 INFO driver.impl :: Registered driver :oracle (parents: [:sql-jdbc]) 🚚
2021-04-08 14:27:25,024 DEBUG plugins.jdbc-proxy :: Registering JDBC proxy driver for oracle.jdbc.OracleDriver...
Load lazy loading driver :oracle took 170.9 ms
2021-04-08 14:27:25,027 INFO driver.impl :: Initializing driver :redshift...
2021-04-08 14:27:25,027 INFO plugins.classloader :: Added URL file:/home/hansen/Downloads/Metabase/plugins/redshift.metabase-driver.jar to classpath
2021-04-08 14:27:25,028 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.postgres...
2021-04-08 14:27:25,028 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.redshift...
2021-04-08 14:27:25,042 INFO driver.impl :: Registered abstract driver :metabase.driver.sql-jdbc.execute.legacy-impl/use-legacy-classes-for-read-and-set  🚚
2021-04-08 14:27:25,050 INFO driver.impl :: Registered driver :redshift (parents: [:postgres :metabase.driver.sql-jdbc.execute.legacy-impl/use-legacy-classes-for-read-and-set]) 🚚
2021-04-08 14:27:25,133 DEBUG plugins.jdbc-proxy :: Registering JDBC proxy driver for com.amazon.redshift.jdbc42.Driver...
Load lazy loading driver :redshift took 106.9 ms
2021-04-08 14:27:25,137 INFO driver.impl :: Initializing driver :sqlite...
2021-04-08 14:27:25,139 INFO plugins.classloader :: Added URL file:/home/hansen/Downloads/Metabase/plugins/sqlite.metabase-driver.jar to classpath
2021-04-08 14:27:25,139 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.sqlite...
2021-04-08 14:27:25,154 INFO driver.impl :: Registered driver :sqlite (parents: [:sql-jdbc]) 🚚
2021-04-08 14:27:25,271 DEBUG plugins.jdbc-proxy :: Registering JDBC proxy driver for org.sqlite.JDBC...
Load lazy loading driver :sqlite took 132.5 ms
2021-04-08 14:27:25,273 INFO driver.impl :: Initializing driver :csv...
2021-04-08 14:27:25,274 INFO plugins.classloader :: Added URL file:/home/hansen/Downloads/Metabase/plugins/csv.metabase-driver.jar to classpath
2021-04-08 14:27:25,274 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.csv...
2021-04-08 14:27:25,282 INFO driver.impl :: Registered driver :csv (parents: [:sql-jdbc]) 🚚
2021-04-08 14:27:25,290 DEBUG plugins.jdbc-proxy :: Registering JDBC proxy driver for org.relique.jdbc.csv.CsvDriver...
Load lazy loading driver :csv took 16.3 ms
2021-04-08 14:27:25,299 INFO driver.impl :: Initializing driver :snowflake...
2021-04-08 14:27:25,299 INFO plugins.classloader :: Added URL file:/home/hansen/Downloads/Metabase/plugins/snowflake.metabase-driver.jar to classpath
2021-04-08 14:27:25,300 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.snowflake...
2021-04-08 14:27:25,325 INFO driver.impl :: Registered driver :snowflake (parents: [:sql-jdbc :metabase.driver.sql-jdbc.execute.legacy-impl/use-legacy-classes-for-read-and-set]) 🚚
2021-04-08 14:27:25,459 DEBUG plugins.jdbc-proxy :: Registering JDBC proxy driver for net.snowflake.client.jdbc.SnowflakeDriver...
Load lazy loading driver :snowflake took 160.7 ms
2021-04-08 14:27:25,463 INFO driver.impl :: Initializing driver :mysql...
2021-04-08 14:27:25,469 INFO driver.impl :: Initializing driver :druid...
2021-04-08 14:27:25,469 INFO plugins.classloader :: Added URL file:/home/hansen/Downloads/Metabase/plugins/druid.metabase-driver.jar to classpath
2021-04-08 14:27:25,475 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.druid...
2021-04-08 14:27:26,900 INFO driver.impl :: Registered driver :druid  🚚
Load lazy loading driver :druid took 1.4 s
2021-04-08 14:27:26,991 DEBUG middleware.log :: GET /api/database 200 6.7 s (23 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (2 idle, 0 queued) (50 total active threads) Queries in flight: 0 (0 queued)
```

The only difference I see in the browser log between working and non-working state is:
`Warning: can't clean query without metadata!`

Workaround is to do a browser refresh, then the requests has been memorized and loads in milliseconds:
```
2021-04-08 14:32:07,021 DEBUG middleware.log :: GET /api/collection 200 17.6 ms (3 DB calls) App DB connections: 3/7 Jetty threads: 7/50 (0 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
2021-04-08 14:32:07,055 DEBUG middleware.log :: GET /api/native-query-snippet 200 52.0 ms (2 DB calls) App DB connections: 2/7 Jetty threads: 6/50 (0 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
2021-04-08 14:32:07,113 DEBUG middleware.log :: GET /api/database 200 227.2 ms (4 DB calls) App DB connections: 1/7 Jetty threads: 5/50 (0 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
2021-04-08 14:32:07,137 DEBUG middleware.log :: GET /api/database 200 253.0 ms (22 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (0 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
```

----

The slow request (the second) also causes the database selector ("Pick your data") in Simple/Custom question to show a spinner, since it needs to load all the drivers first. That is only a UX P3, since it only happens once after start of an instance, and doesn't cause any problems (from what I can tell) like this issue.

**Comment by flamber** [comment] 2022-07-25 14:36
I cannot reproduce on 0.44.0-rc1 anymore, since it looks like the PersistRefresh task seems to load all drivers on initialization.
```
2022-07-25 16:25:39,481 INFO metabase.task :: Task scheduler initialized into standby mode.
2022-07-25 16:25:39,486 INFO metabase.task :: Initializing task SyncDatabases 📆
2022-07-25 16:25:39,565 INFO task.sync-databases :: Updated default schedules for 0 databases
2022-07-25 16:25:39,566 INFO metabase.task :: Initializing task PersistRefresh 📆
2022-07-25 16:25:39,600 INFO driver.impl :: Initializing driver :sql...
2022-07-25 16:25:39,600 INFO driver.impl :: Initializing driver :sql-jdbc...
2022-07-25 16:25:39,601 INFO driver.impl :: Initializing driver :sqlserver...
...
```
Not going to close this, since it seems like a possible mistake that the task loads the drivers, and we don't have a test for this.

**Comment by NevRA** [comment] 2023-12-28 14:46
Since there is no reproduction, I will close this bug. Feel free to re-open it.

**Closed by NevRA** 2023-12-28 14:46 UTC
Labels: Type:Bug, Priority:P2, Querying/Parameters & Variables, Querying/Native, Difficulty:Medium, .Frontend
