### ISSUE TITLE
On mobile, a large number cannot be displayed

### ISSUE THREAD

**Issue by AlvaroNortes** [metabase/metabase#25431] opened 2022-09-15 11:33 UTC
**Describe the bug**
If you go to your mobile or any small screen, in a simple question to show a number, you can't see the full number when it has equal or more than 6 characters. Bigger numbers are cut, and you can't scroll right to see them.
Happens to any number bigger than 99,999.

**Logs**
NA

**To Reproduce**
1. Go to your mobile phone
2. Click on any question with just a number, bigger than 99,999 (5, 6 characters)
3. The number is cut because Mobile screen is smaller.

**Expected behavior**
In small screens, in number questions, numbers size should adjust (reduce) accordingly to fit in the screen. So that you can fully see them, no matter how many characters they have.

**Screenshots**
<img width="467" alt="image (34)" src="https://user-images.githubusercontent.com/42941129/190392215-ccbae7c4-1587-4d8c-a1e4-7352d91b4688.png">
<img width="616" alt="image (35)" src="https://user-images.githubusercontent.com/42941129/190392554-697b9a0b-490f-4e72-a1cf-97688a6bb4de.png">

**Information about your Metabase Installation:**
 v0.43.4

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: NA
- Your operating system: NA
- Your databases: Snowflake
- Metabase version: 0.43.4
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

**Severity**
Honestly quite important as 30 % of our users check these numbers in Mobile.

**Comment by flamber** [comment] 2022-09-15 11:36
Duplicate of #23093

**Closed by flamber** 2022-09-15 11:36 UTC
Labels: Type:Bug, .Needs Triage
