### ISSUE TITLE
Materialized Views lose metadata column type upon re-creation

### ISSUE THREAD

**Issue by marcoruggine** [metabase/metabase#12937] opened 2020-07-17 08:27 UTC
Hi, I'm running 0.35.4 with a Postgresql db and everything has always worked fine until the latest update.

What is happening:

1. I create a materialized view 
2. I go to admin / settings / data model and assign the correct type to each column + foreign keys
3. I need to add new columns, so I drop the view, add the columns, re-create the view
🔥  I have lost all metadata previously created at point #2
🔥 Without metadata all my filters (location, date, category) won't work anymore

Before I was able to drop and create views without losing all this valuable info, it is extremely annoying having to map everything once again.

I have noticed that previously the default for every column was "category", now it's "No special type". 
Maybe this is something that could have impacted?

Thanks in advance.

**Comment by flamber** [comment] 2020-07-17 08:49
Duplicate of #12680 - fixed in upcoming 0.36.0

**Closed by flamber** 2020-07-17 08:49 UTC
Labels: .Needs Triage, Type:Bug
