### ISSUE TITLE
Issues with custom columns since new query designer release

### ISSUE THREAD

**Issue by Swift-Jr** [metabase/metabase#11071] opened 2019-10-07 14:15 UTC
**Describe the bug**
Previously I could use custom columns to add calculated columns e.g. `sum(sold_price)/count_distinct(customer)`

However - there are now 2 separate custom columns. The first one does not allow a user to enter functions. The second allows me use to columns from the 'group' however with no alias (so if I have several 'sums' I only get the first as an option called 'sum').

When I update the report by adding a new grouping the custom columns are removed.

**To Reproduce**
1.  Create a new questions
2. Group table by a category
3. Add several 'sum of ...' to the summarise by, along with a count
4. In the editor, try and create a % by doing sum(x)/count
4a. The first column editor will not accept functions
4b. the second column editor only allows you use to 'count' and 'sum' - unable to choose which sum to use
5. Now summarise by an additional column, all custom columns vanish

**Expected behavior**
I expected to be able to create custom columns using both the fields available in in the query and available functions as per before this update.

I also expect the custom columns to not be removed when I make other changes to the report

**Screenshots**
Can't use functions in the first custom column option:
![image](https://user-images.githubusercontent.com/11637969/66319408-fc1eb780-e914-11e9-9ea1-717c2d08e638.png)

2nd custom column does not allow fields to be used
![image](https://user-images.githubusercontent.com/11637969/66319498-207a9400-e915-11e9-9fa9-b869f0eda542.png)

2nd custom column only allows use of summarise by columns, but unclear which 'sum' this is using (there are several sums on this query)
![image](https://user-images.githubusercontent.com/11637969/66319531-30927380-e915-11e9-865a-0169138bf027.png)

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.4+11",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.4",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.4+11",
    "os.name": "Linux",
    "os.version": "4.15.0-1031-azure",
    "user.language": "en",
    "user.timezone": "Europe/London"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-09-20",
      "tag": "v0.33.3",
      "branch": "release-0.33.x",
      "hash": "86d32bf"
    },
    "settings": {
      "report-timezone": "GMT"
    }
  }
}

**Severity**
We have upgraded on our main server - so this is now blocking our users from making reports.

**Comment by flamber** [comment] 2019-10-07 18:44
Hi @Swift-Jr 
This is a duplicate of #10985 - work-around, just give the Custom Expression a name.

**Comment by salsakran** [comment] 2019-10-09 02:42
@Swift-Jr can you verify whether that giving the custom expression a name fixes this for you?

**Comment by Swift-Jr** [comment] 2019-10-09 06:42
This was specifically for the custom column functionality making use of a summarised column.

Changing the summarised column to be a custom expression and giving it a name does partially solve this issue - however the custom expression seems limited to fields on the primary table.

So if I had a distinct count of table -> relationship -> field - converting to a custom expression results in a field not found error.

**Comment by flamber** [comment] 2019-10-09 06:52
@Swift-Jr 
Have you seen that version 0.33.4 has just been released and has a bunch of fixes and features specifically about Custom Expressions? Check the [release notes](https://github.com/metabase/metabase/releases/tag/v0.33.4) for more details.

> So if I had a distinct count of table -> relationship -> field - converting to a custom expression results in a field not found error.

What do you mean by this? I'm not sure I understand - do you see an error message? Can you show a screenshot of what you're trying to do?

**Comment by Swift-Jr** [comment] 2019-10-09 08:43
So begin with 2 tables that are correctly linked

Create a new view using one of the tables, and select summarise by a column in the adjoined table

e.g.

![image](https://user-images.githubusercontent.com/11637969/66465249-69972900-ea78-11e9-9bc8-e9921ab7c079.png)

![image](https://user-images.githubusercontent.com/11637969/66465271-73209100-ea78-11e9-9c07-cdb27ae4deb0.png)

In query builder this shows as just the label 'sum' as per original issue

Now edit the summary to change it to a custom expression (so we can add a label)

![image](https://user-images.githubusercontent.com/11637969/66465544-ede9ac00-ea78-11e9-903a-eceb56c8283c.png)

When trying to save I get the error "Unknown field Search Amount"

We will try upgrading to 33.4 and see if this solves our problems or not

**Comment by flamber** [comment] 2019-10-09 19:08
@Swift-Jr Okay, both of those issues should be solved in 0.33.4

**Comment by flamber** [comment] 2020-02-25 13:54
Closing, since it was fixed in 0.33.4 - please comment if you're still experiencing problems with this.

**Closed by flamber** 2020-02-25 13:54 UTC
Labels: Priority:P2, Querying/Notebook, Type:Bug
