### ISSUE TITLE
Formatting Option "Multiply by a number" not applied when exporting

### ISSUE THREAD

**Issue by LukeAbell** [metabase/metabase#23017] opened 2022-05-28 02:05 UTC
### Issue
When exporting a column that has a configured "Multiply by a number" set in the data model, the multiplication is not applied when exporting.

### To replicate:

Example dataset:
`Total (1000)`

Steps:
- Configure currency column to multiply by 0.01
- Create question that displays column
- Display value in Metabase correctly shows 10.
- Export dataset
- CSV and XLSX row value is 1000 instead of 10.

### How it affects us:
We store all currency columns as USD cents. In Metabase, we have all currency columns configured to multiply by 0.01 which correctly converts to US dollars. Users would like to export metabase data in dollars instead of cents (and have export match what's displayed in the metabase report UI).

---

It looks like #10879 was intended to resolve this issue, but it might have missed the multiplication option?

Might be related to #17753

**Comment by flamber** [comment] 2022-05-28 08:01
Formatting is applied to XLSX, but not to CSV. Duplicate of #17422
Please always include "Diagnostic Info", and use the bug template for easier recognition.

**Closed by flamber** 2022-05-28 08:01 UTC
Labels: Type:Bug, .Needs Triage

**Comment by paoliniluis** [comment] 2022-06-06 22:14
@LukeAbell can you guide us into the reproduction with the sample dataset? I tried to go over the steps that we went together a few days ago but I couldn't find the issue (I'm mostly sure I forgot something)
