### ISSUE TITLE
Custom columns ordering not respected in JSON format

### ISSUE THREAD

**Issue by ywarnier** [metabase/metabase#23096] opened 2022-06-01 23:36 UTC
**Describe the bug**
The JSON format doesn't seem to respect the custom column order set in the web interface.

**Logs**
No logs

**To Reproduce**
1. Create a query
2. Change fields order manually (in "Configuration") and save
3. Export as JSON. The custom order is not maintained.
4. As a reference, download it as xlsx. The custom order is maintained

**Expected behavior**
The custom order should be respected in the JSON export as well (the issue is the same using the API and the web interface).

**Screenshots**
Setting the columns order.
![mb-column-order-setting](https://user-images.githubusercontent.com/609839/171518302-4491ff42-3536-45be-92bf-9f58e4a30d98.png)
Checking the columns order in JSON (in Postman).
![mb-column-order-json](https://user-images.githubusercontent.com/609839/171518303-2c55e51a-b145-4d04-8058-459763c7a8e5.png)

**Information about your Metabase Installation:**

- Your browser and the version: Irrelevant
- Your operating system: Irrelevant
- Your databases: MySQL
- Metabase version: 0.41.4
- Metabase hosting environment: Docker
- Metabase internal database: not sure

**Severity**
Annoying but not blocking to me.

**Comment by flamber** [comment] 2022-06-02 08:05
Duplicate of #12247

**Closed by flamber** 2022-06-02 08:05 UTC
Labels: Type:Bug, .Needs Triage
