### ISSUE TITLE
While setting up an alert in Metabase, it always add an email alert, even when I uncheck the boxe

### ISSUE THREAD

**Issue by PetiPandaRou** [metabase/metabase#12822] opened 2020-07-01 15:20 UTC
**Describe the bug**
While setting up an alert in Metabase, it always add an email alert, even when I uncheck the boxe:  
![image](https://user-images.githubusercontent.com/323248/86260604-c960d180-bbbd-11ea-80f8-986c81cb2381.png)

Here is the result of my query:  
![image](https://user-images.githubusercontent.com/323248/86260649-d8e01a80-bbbd-11ea-9d78-d9e3e5a46bdf.png)

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Got to a request
2. Set up an alert with Slack
3. Click on done
4. Check your alert

**Expected behavior**
Normally, it shouldn't select the email such as it is not selected in my query.

**Screenshots**
Added above.

**Severity**
Not blocking but a little annoying, such as I have to permanently check alerts I set up

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.9.0-8-amd64",
    "user.language": "en",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "clickhouse"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-11-19",
      "tag": "v0.33.6",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2020-07-01 15:23
Duplicate of #12349. If you edit it again, then the setting is applied. Latest release is 0.35.4

**Closed by flamber** 2020-07-01 15:23 UTC
