### ISSUE TITLE
Wrong labels/colors with combined questions

### ISSUE THREAD

**Issue by elderapo** [metabase/metabase#9645] opened 2019-03-31 17:33 UTC
# Environment

- Browser and the version: Version 71.0.3578.98 (Official Build) (64-bit)
- Operating system: Ubuntu 14.04
- Databases: mysql:5.7.10
- Metabase version: newest one from docker image
- Metabase hosting environment: docker
- Metabase internal database: mysql:5.7.10

# Problem/How to reproduce:
1. Create question "Total users":
 - DATA: `People`
 - FILTERED BY: `none`
 - VIEW: `Cumulative count of rows`
 - GROUPED BY: `Created At: Day`
 - VISUALIZATION: `Line`
2. Create question "Total fb users":
 - DATA: `People`
 - FILTERED BY: `Source is Facebook`
 - VIEW: `Cumulative count of rows`
 - GROUPED BY: `Created At: Day`
 - VISUALIZATION: `Line`
3. Create new dasboard.
4. Add question `Total users`.
5. Add data to this question: `Total fb users`.

Now I would expect metabase to nicely display 2 questions on a single chart with correct labels/colors but intead [this](https://i.imgur.com/N3UKQEW.png) is displayed. If both questions are displayed next to each other they [work just fine](https://i.imgur.com/tyJsmVl.png).

**Comment by flamber** [comment] 2019-03-31 18:32
Hi @elderapo It looks like a duplicate of #9636 - if yes, go and upvote by clicking :+1: on the first post.

**Comment by flamber** [comment] 2019-03-31 23:06
@elderapo And please close this issue.

**Closed** 2019-03-31 23:19 UTC
