### ISSUE TITLE
Korean text not rendered on email and Slack alerts

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#35100] opened 2023-10-26 15:11 UTC
### Describe the bug

Visualizations in email and Slack alerts do not display Korean characters correctly:
- charts (email and Slack): legend and axis text
- table (Slack): cell content, and column titles

### To Reproduce

Create any table or chart visualization, with content / column titles / axis labels in Korean.
Set up an alert, and see the rendering errors in email and Slack.

### Expected behavior

Korean text is rendered correctly

### Logs

n/a

### Information about your Metabase installation

```JSON
1.47.5
```

### Severity

Reported by a user

### Additional context

**Metabase UI**
<img width="824" alt="image" src="https://github.com/metabase/metabase/assets/11080638/a4a2a8ca-a866-47a7-b8f2-4b22c6da99b9">
<img width="1039" alt="image" src="https://github.com/metabase/metabase/assets/11080638/a6e013aa-e85b-49ab-83dd-7401a0fb7e12">
Email alerts:

**Slack**
<img width="825" alt="image" src="https://github.com/metabase/metabase/assets/11080638/ec2ad54e-d0b3-4a39-bd82-53b3d94fe7f8">
<img width="1035" alt="image" src="https://github.com/metabase/metabase/assets/11080638/4a984e7d-ab62-4b1c-933e-77c3c584b082">

**Email alerts**
<img width="595" alt="image" src="https://github.com/metabase/metabase/assets/11080638/6d9bd9fd-ad23-4f09-818f-cad4dcde5f8e">
<img width="579" alt="image" src="https://github.com/metabase/metabase/assets/11080638/dddcc655-f481-42ab-801d-4dab70cd4dda">

**Comment by paoliniluis** [comment] 2023-10-26 15:54
Dupe of https://github.com/metabase/metabase/issues/2342 @zbodi74

**Closed** 2023-10-27 02:19 UTC
Labels: Type:Bug, Reporting/Alerts, .Needs Triage, Misc/Emails, Notifications/Slack
