### ISSUE TITLE
Wrong results with grouped cummulative sums

### ISSUE THREAD

**Issue by dfx413** [metabase/metabase#8196] opened 2018-08-02 12:20 UTC
Hello, 
I want to display cumulative sums grouped by month and partner. 
When grouped only by month the results are just fine.
But when I add grouping by partner I get roughly double results.
Happens in graphs and also in table views.

**Screens attached below:**

**Grouping by month:**
![image](https://user-images.githubusercontent.com/1764151/43583116-ce19aa48-965e-11e8-8ecd-9c5f518090a4.png)
![image](https://user-images.githubusercontent.com/1764151/43583123-d339f0c8-965e-11e8-86c7-64c8b77f2c99.png)

**Grouping by month & partner:**
![image](https://user-images.githubusercontent.com/1764151/43583129-d82239e2-965e-11e8-91d2-bc18c8ebee8d.png)
![image](https://user-images.githubusercontent.com/1764151/43583370-a4242d20-965f-11e8-940c-a17bdc156c30.png)

**environment:**
Metabase version 0.29.3
Chrome 68.0.3440.84 (behaves the same way in Firefox)
macOS Mojave
MSSQL2016
hosted in Docker on private server running Ubuntu 18.04
H2 database

**Comment by dfx413** [comment] 2018-08-13 13:30
Sorry, looks like I misunderstood how this display mode works.
But I still see a problem when looking at the last image. 
The green area suddenly decreases in the last interval despite any negative value in the table. 
That is obviously wrong.

**Comment by salsakran** [comment] 2018-08-13 22:55
dupe of #6720

**Closed by salsakran** 2018-08-13 22:55 UTC
