### ISSUE TITLE
Missing custom fields and expressions in query builder for BigQuery data

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#4896] opened 2017-04-27 09:20 UTC
Hi,
Is there a plan to include options to add custom fields/expressions in the query builder for BigQuery data as well? This would be quite useful.
Thanks

**Comment by camsaul** [comment] 2017-04-27 17:39
Duplicate of #3997 

This is shipping as part of our upcoming release.

**Closed by camsaul** 2017-04-27 17:39 UTC
Labels: Database/BigQuery, Query Processor

**Comment by andrew4forbes** [comment] 2017-05-11 19:13
Hi is there a timeframe on when this release will be live?

**Comment by mazameli** [comment] 2017-05-11 19:15
@andrew4forbes it just shipped yesterday :) http://www.metabase.com/blog/Metabase-0.24

**Comment by stevenvdr** [comment] 2017-11-24 13:47
Is there also a plan to add this to the Question builder?

**Comment by stevenvdr** [comment] 2017-11-27 11:23
To elaborate my question a bit. When you use the graphical interface the aggregation expressions do not show in the additional options:
![capture](https://user-images.githubusercontent.com/1979067/33264267-24b10b72-d36d-11e7-99d1-f62ea1bab1b0.PNG)

This is due to the bigquery database definition that has the "expression-aggregation" feature, but not "expressions" feature (https://github.com/metabase/metabase/blob/5688c060de14b88481fc2f90df6b6f3baf35feb3/src/metabase/driver/bigquery.clj#L492), which is used in frontend to hide the 'Custom Fields' widget (https://github.com/metabase/metabase/blob/136dfb17954f4e4302b3bf2fee99ff7b7b12fd7c/frontend/src/metabase/query_builder/components/ExtendedOptions.jsx#L157).

Not sure whether this is a bug, or feature request.

**Comment by FleetOpsLiam** [comment] 2019-01-22 15:27
wondering did this ever get released? 
Currently connected to a BQ and cant see the UI for adding custom query... using v1.0.3

**Comment by awoehrl** [comment] 2019-02-04 12:07
Same here, can't seem to get custom fields for BigQuery databases.

**Comment by flamber** [comment] 2019-02-04 19:41
@FleetOpsLiam @awoehrl Which version of Metabase are you using?

**Comment by awoehrl** [comment] 2019-02-05 06:58
@flamber Im on the most recent version.

**Comment by FleetOpsLiam** [comment] 2019-02-05 10:13
hi @flamber - im on 1.0.3

**Comment by flamber** [comment] 2019-02-05 15:06
@awoehrl I cannot find a specific bug tracking this, so maybe it broke since then and now. Can you create a new issue, fill in the requested data and reference this issue.

@FleetOpsLiam There's no such version. But wait until there's an active bug filed on this.

**Comment by camsaul** [comment] 2019-02-06 02:20
Second that. There is no Metabase 1.0.3 so if you're running it you're from the future

**Comment by FallenChromium** [comment] 2019-02-06 07:16
@camsual, I'd say there is. Basically it's something between 0.31 and 0.32,
published on DockerHub, [here](
https://hub.docker.com/r/metabase/metabase-enterprise)

**Comment by FleetOpsLiam** [comment] 2019-02-06 07:45
Yep, it's the enterprise version.  I took the version from the 'about' in the application. I'll have a closer look today and see if there's something a little more useful for you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
