### ISSUE TITLE
Option to disable login with username password if SSO enabled

### ISSUE THREAD

**Issue by shubham9411** [metabase/metabase#11057] opened 2019-10-04 07:27 UTC
**Is your feature request related to a problem? Please describe.**
If any user leave from the organization then we have to remove their access from various places but if we have only one option(SSO) then it become easier to revoke access for the users as we just have to disable their account from the GSuite and we can be sure that the access is revoked from all other places.

**Describe the solution you'd like**
In `Authentication` setting we can give a checkbox/select along with the `Sign in with Google` option that if we have enabled SSO than:
  1. Prefer SSO over Username/Email signin
  2. Only use SSO
  3. Disable SSO

**Describe alternatives you've considered**

**How important is this feature to you?**
For security purposes we don't want to allow users to sign in using username/email because it is hard to manage users in an organization if they leave we have to find out the places where they have the signin using the username/email and than we have to disable it manually at all the places. But if you give this option we just have to revoke the access from our GSuite.

**Additional context**

**Comment by flamber** [comment] 2019-10-04 13:23
Hi @shubham9411 
It sounds like a duplicate of #3136 (check for work-around). The [Enterprise Edition](https://www.metabase.com/enterprise/) has this option.

**Comment by salsakran** [comment] 2019-10-05 22:08
closing since this is something we do in the EE

**Closed by salsakran** 2019-10-05 22:08 UTC
Labels: Type:New Feature
