### ISSUE TITLE
Database scope in SQL 'Native Query' page unaltered between user sessions.

### ISSUE THREAD

**Issue by dvanrijswijk** [metabase/metabase#6904] opened 2018-02-08 16:17 UTC
The drop-down list of databases in the 'Native Query' page does not change between different user sessions on the same machine.

Example consequences:
When a user with access to less databases logs in and out first, followed by a user with access to more, the user with greater permissions is limited in what databases he/she can access from the 'Native Query' screen.

When a user with access to more databases logs in and out first, followed by a user with less access, the user with less permissions can see the names of the other databases it doesn't have permission to.  As the user with less permissions begins to type, the autocomplete feature's 'scope' extends beyond their permissions, and their typing is immediately cut off with the permission denied splash screen.  This effectively prevents the user with less access from writing native queries.

Clearing the browser cache resolves this problem completely.

Browsers:
Chrome 63.0.3239.132

OS:
Windows 7

Datbase:
Postgres

Metabase version:
0.28

Metabase hosting environment:
Linux/Ubuntu 16.04

Metabase internal database:
Postgres

Repeatable steps to reproduce the issue:

Clear the browser cache.
Log in as a user with 'larger' access permissions.  (A superset of the second user's access permissions)
Click on 'New Question' -> 'Native Query'.
Being to write a query.
Log out.
Log in as a user with 'lesser' access permissions.  *nb.  Lesser, as in a subset of the 'larger' access permissions.
Click on 'New Question' -> 'Native Query'.
Being to write a query.
The autocomplete seeks beyond it's scope (the scope of the first user), and immediately throws the splash screen up.

**Comment by flamber** [comment] 2019-02-22 05:09
Related to or duplicate of #5202 - but I'm not able to reproduce this on 0.31.2 (Firefox 65 Chromium 71)

**Comment by flamber** [comment] 2020-05-29 20:44
This was fixed by #7600 in 0.30.0

**Closed by flamber** 2020-05-29 20:44 UTC
Labels: Priority:P2, Querying/Native, Type:Bug
