### ISSUE TITLE
Database show table can't open 

### ISSUE THREAD

**Issue by jzdayz** [metabase/metabase#12303] opened 2020-04-10 08:27 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/35563513/78975844-98857900-7b47-11ea-8f53-c9c0eaa1b7a9.png)
This can't open.
**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)
```txt
vendor.bundle.js?edf30a198cc9250a4cbd:1 Uncaught TypeError: Cannot read property 'tables' of null
    at app-main.bundle.js?edf30a198cc9250a4cbd:5
    at vendor.bundle.js?edf30a198cc9250a4cbd:1
    at vendor.bundle.js?edf30a198cc9250a4cbd:1
    at vendor.bundle.js?edf30a198cc9250a4cbd:1
    at vendor.bundle.js?edf30a198cc9250a4cbd:1
    at Function.mapToProps (app-main.bundle.js?edf30a198cc9250a4cbd:5)
    at i (vendor.bundle.js?edf30a198cc9250a4cbd:1)
    at Function.i.mapToProps (vendor.bundle.js?edf30a198cc9250a4cbd:1)
    at i (vendor.bundle.js?edf30a198cc9250a4cbd:1)
    at vendor.bundle.js?edf30a198cc9250a4cbd:1
```
**To Reproduce**

**Expected behavior**

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.19.76-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-02",
      "tag": "v0.35.1",
      "branch": "release-0.35.x",
      "hash": "e67f169"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by flamber** [comment] 2020-04-10 09:17
Duplicate of #12269

**Closed by flamber** 2020-04-10 09:17 UTC
Labels: .Needs Triage, Type:Bug
