### ISSUE TITLE
Dashboard Subscription: include minutes when scheduling

### ISSUE THREAD

**Issue by jrca025** [metabase/metabase#22575] opened 2022-05-10 08:13 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Option to choose the minute like even every 15mins not just per hour when scheduling daily

![image](https://user-images.githubusercontent.com/89201548/167581502-0e632a83-5ba5-41e9-8ec7-360a7cf51f28.png)

**Comment by flamber** [comment] 2022-05-10 08:14
Duplicate of #3846

**Closed by flamber** 2022-05-10 08:14 UTC
Labels: Type:New Feature, .Needs Triage
