### ISSUE TITLE
GUI based dump/load

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#16184] opened 2021-05-21 14:10 UTC
A GUI based dump/load process would greatly enhance the experience when doing this process in Metabase. This will allow everyone to have several Metabase instances to perform the steps needed to copy a question/dashboard/configuration from a instance to another one without having to know the nitty-gritty of a shell.

**How to Test This Feature Out**

Same tests as the ones we have for serialization right now, but adding cypress front-end tests

**Comment by flamber** [comment] 2021-05-21 14:12
Duplicate of #15286

**Closed by flamber** 2021-05-21 14:12 UTC
Labels: Operation/Serialization, Type:New Feature
