### ISSUE TITLE
BigQuery regular expression in SELECT clause populating WHERE variables

### ISSUE THREAD

**Issue by toddheslin** [metabase/metabase#9660] opened 2019-04-02 09:51 UTC
## Background info
- Your browser and the version: Chrome 73.0.3683.86
- Your operating system: MacOS
- Your databases: BigQuery
- Metabase version: N/A
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

# Steps

Here's a fun bug. When my query looks like this:
```sql
SELECT
  REGEXP_EXTRACT(page_path, r"(?: \/land\/)(stage\-.*?)(?:\-)") AS `Stage`,
  REGEXP_EXTRACT(page_path, r"(?:\/land\/stage\-.*\-lot\-)(.*)") AS `Lot`,
  COUNT(distinct unique_user) AS `Unique_Page_Views`
FROM `reporting.web_raw_reporting`
WHERE host = 'somewebsite.com.au'
  AND page_path like '%/land/stage%' [[AND {{date}}]]
GROUP BY page_path
ORDER BY `Unique_Page_Views` DESC
```

Metabase will take the first two `?:` characters and replace them with the values from the `{{date}}` variable. Here is the corresponding BigQuery trace:

```sql
-- Metabase:: userID: 1 queryType: native queryHash: 0685de775984e39850e17907c847a94ad1700f90b9a960308309ee1e88fa5263
SELECT
  REGEXP_EXTRACT(page_path, r"(timestamp('2019-02-28T13:00:00.000Z'): \/land\/)(stage\-.*timestamp('2019-03-30T13:00:00.000Z'))(?:\-)") AS `Stage`,
  REGEXP_EXTRACT(page_path, r"(?:\/land\/stage\-.*\-lot\-)(.*)") AS `Lot`,
  COUNT(distinct unique_user) AS `Unique_Page_Views`
FROM `reporting.web_raw_reporting`
WHERE host = 'somewebsite.com.au'
  AND page_path like '%/land/stage%' AND timestamp_trunc(CAST(`reporting.web_raw_reporting`.`date` AS timestamp), day) BETWEEN ? AND ?
GROUP BY page_path
ORDER BY `Unique_Page_Views` DESC
```

It turns out that this only happens for the *first* two variables matching the pattern `?:`, so my hack around it is this:

```sql
WITH q as (
  SELECT page_path, unique_user
	FROM `reporting.web_raw_reporting`
	WHERE 
    host = 'somewebsite.com.au'
    AND page_path like '%/land/stage%'
    [[AND {{date}}]]
)

SELECT
  REGEXP_EXTRACT(page_path, r"(?:\/land\/)(stage\-.*?)(?:\-)") AS `Stage`,
  REGEXP_EXTRACT(page_path, r"(?:\/land\/stage\-.*\-lot\-)(.*)") AS `Lot`,
  COUNT(distinct unique_user) AS `Unique_Page_Views`
FROM q
GROUP BY page_path
ORDER BY `Unique_Page_Views` DESC
```

Hope this helps anyone experiencing the same issue and a patch come through at some point. Let me know if you need me to test anything specifically.

**Comment by flamber** [comment] 2019-04-02 18:12
This looks like a duplicate of #5091 - almost the same report as #7325

**Comment by toddheslin** [comment] 2019-04-03 01:58
Thanks @flamber, sorry must had missed these previous issues. I guess searching for `?` isn't necessarily the easiest thing to do :-)

**Comment by flamber** [comment] 2019-04-03 02:06
Hahah - no :-)
But I've been looking through every issue for the past couple of months, so I kinda remember most.
Please remember to close this issue, if you agree that it's a duplicate.

**Closed** 2019-04-03 02:07 UTC
