### ISSUE TITLE
Custom question filter names disappear

### ISSUE THREAD

**Issue by DannyK85** [metabase/metabase#9714] opened 2019-04-08 11:26 UTC
Noticed that since using 0.31.2 the filter categories in custom questions based on native questions sql disappear in the interface.
I see the same result in the latest version 0.32.2
![Screenshot 2019-04-08 at 13 15 16](https://user-images.githubusercontent.com/5367750/55720667-a4ed6800-5a01-11e9-9ac1-207124e96291.png)

When using multiple filters you can't see which one is what filter. You have to remove all to apply changes to the filters.

- Your browser and the version: Chrome 73.0.3683.86
- Your operating system: OS X 10
- Your databases: Postgres
- Metabase version: 0.32.2

Reproduce:

Create a native query based on Postgres database.
When adding a filter in a custom question based on that native query the filter category is empty when saving the custom question

**Comment by flamber** [comment] 2019-04-08 15:04
Hi @DannyK85 
This is a duplicate of #8971 - please go and upvote by clicking :+1: and then close this issue

**Closed** 2019-04-08 15:08 UTC
