### ISSUE TITLE
Pivot Table Visualization: grand totals truncated when window too small

### ISSUE THREAD

**Issue by addison-grant** [metabase/metabase#37712] opened 2024-01-15 19:16 UTC
### Describe the bug

The column grand totals on my pivot table visualization is being truncated when I scroll all the way down. The only way I can get it to show is if I collapse everything and get the vertical height of the table to be smaller than the browser window height.

This is my first pivot table report, and I don't know when this bug would have been introduced.

![image](https://github.com/metabase/metabase/assets/10889879/86b0cd46-eef8-46a8-a5a1-959953cbc763)

### To Reproduce

1. Create a pivot table with many rows and grand totals turned on.
2. View it
3. See how the grand totals at the bottom are cut off if the window isn't big enough

### Expected behavior

You should be able to scroll down to the grand totals and be able to see them without having to collapse the rows.

### Information about your Metabase installation

- Chrome is up to date
   - Version 120.0.6099.217 (Official Build) (64-bit)
- Using Metabase v0.48.2 (will upgrade to v0.48.3 soon)

### Severity

annoying

### Additional context

I have been able to collapse the data enough to fit it on my screen, but I expect the report I am looking at the grow in the number of rows throughout the year (I only have part of one month so far).

**Comment by maximepvrt** [comment] 2024-02-06 18:07
same issue with v0.48.4

**Comment by maximepvrt** [comment] 2024-02-06 18:08
@paoliniluis it's a regression. it worked fine before

**Comment by maximepvrt** [comment] 2024-02-12 09:48
@paoliniluis it's a regression. it worked fine before V0.48

**Comment by EmmadUsmani** [comment] 2024-07-18 22:09
I was able to reproduce on 48.2, but it looks like it's no longer happening on master, see the comparison below. I'm not 100% sure, but it's likely that this was fixed by https://github.com/metabase/metabase/pull/44514. You should no longer experience this issue after upgrading to the latest v50 minor release.

**48.2** 

https://github.com/user-attachments/assets/1944edd2-62bc-4694-b23c-5aa2f782b13f 

**master (commit `df2d409`)**

https://github.com/user-attachments/assets/b641cb27-8cef-4bbf-932f-717405f4cc71

**Closed by EmmadUsmani** 2024-07-18 22:09 UTC
Labels: Type:Bug, Priority:P2, .Frontend, Visualization/Tables, .Regression, .Team/DashViz

**Comment by addison-grant** [comment] 2024-07-18 22:15
Awesome, thanks for following up!
