### ISSUE TITLE
Commented filter causes query to fail despite correct presence of query elsewhere in query

### ISSUE THREAD

**Issue by HugoWickham** [metabase/metabase#21612] opened 2022-04-12 10:57 UTC
**Describe the bug**
When using an optional filter in a query, commenting out said filter then entering a value in the UI causes the query to fail (unsurprisingly) with an index out of range error. However, if you have a filter commented out, and the same filter elsewhere in the query (e.g. you're reorganising the query an leave a filter commented in one alias while you move it to another), the presence of the commented filter will cause the query to fail with the same index error - despite the filter also being present intact and uncommented in the query.

**Logs**
`error class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
react-dom.production.min.js:49 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at react-dom.production.min.js:49:67
    at it (react-dom.production.min.js:50:217)
    at Object.t.findDOMNode (react-dom.production.min.js:289:336)
    at s.value (ExplicitSize.jsx:31:23)
    at ExplicitSize.jsx:101:28
    at c (throttle.js:32:21)
3metadata.js:18 DEPRECATED: metabase/redux/metadata fetchDatabaseMetadata
y @ metadata.js:18
metadata.js:18 DEPRECATED: metabase/redux/metadata fetchRealDatabases
y @ metadata.js:18
metadata.js:18 DEPRECATED: metabase/redux/metadata fetchDatabaseMetadata
y @ metadata.js:18
6react-dom.production.min.js:49 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at react-dom.production.min.js:49:67
    at it (react-dom.production.min.js:50:217)
    at Object.t.findDOMNode (react-dom.production.min.js:289:336)
    at s.value (ExplicitSize.jsx:31:23)
    at ExplicitSize.jsx:101:28
    at c (throttle.js:32:21)
2metadata.js:18 DEPRECATED: metabase/redux/metadata fetchDatabaseMetadata
y @ metadata.js:18
15index.js:108 [re-reselect] Invalid cache key "undefined" has been returned by keySelector function.
m @ index.js:108
3react-dom.production.min.js:49 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at react-dom.production.min.js:49:67
    at it (react-dom.production.min.js:50:217)
    at Object.t.findDOMNode (react-dom.production.min.js:289:336)
    at s.value (ExplicitSize.jsx:31:23)
    at ExplicitSize.jsx:101:28
    at c (throttle.js:32:21)
2index.js:108 [re-reselect] Invalid cache key "undefined" has been returned by keySelector function.
m @ index.js:108
2VisualizationError.jsx:94 error The column index is out of range: 2, number of columns: 1.
21StructuredQuery.js:326 Warning: can't clean query without metadata!
value @ StructuredQuery.js:326
63VisualizationError.jsx:94 error The column index is out of range: 2, number of columns: 1.
5VisualizationError.jsx:94 error The column index is out of range: 1, number of columns: 0.
8VisualizationError.jsx:94 error The column index is out of range: 2, number of columns: 1.
4VisualizationError.jsx:94 error ERROR: syntax error at or near "with"
  Position: 490
69VisualizationError.jsx:94 error The column index is out of range: 3, number of columns: 2.
11VisualizationError.jsx:94 error The column index is out of range: 2, number of columns: 1.
VisualizationError.jsx:94 error The column index is out of range: 2, number of columns: 1.`

**To Reproduce**

1. Create a SELECT statement
2. Add a filter (can be optional or required) using a WHERE clause
3. Add a second filter with the same name (semantics of the filter do not matter, but the name must be the same as the first)
4. Comment out the filter created in 3
5. Add a value to pass to the filter in the UI above the SQL editor
6. Run the query. You should get a "column index out of range" error

**Expected behavior**
The query should run as usual. When you add a filter and comment it out, but keep a value in the UI to pass to it, the error is to be expected, as you are passing the value to a filter that is not present in the query. However, in the case described above, the filter *is* present in the query; the presence of the commented-out filter is what breaks it. Uncommenting (if the commented query is identical to the uncommented one) or deleting the filter causes the query to run as normal.

**Screenshots**

Case 1: Single optional filter, providing a successful query. 
![InkedCorrect output_LI](https://user-images.githubusercontent.com/15078762/162941630-179c0827-d37a-49cf-9773-cf418c75bda7.jpg)

Case 2: Commenting out the query. Causes "column index out of range error" as you are passing a filter parameter to a commented-out filter.
![InkedExpected failure_LI](https://user-images.githubusercontent.com/15078762/162941669-6ed3b3e3-e2f6-496c-9f11-710d93775f9c.jpg)

Case 3: Adding same filter twice, once commented and once uncommented. Passing a value to the filter causes query to fail again with a "column index out of range" error. This is despite the fact that the filter is present in the query - the presence of the commented filter is what causes the query to break.
![InkedUnexpected behaviour_LI](https://user-images.githubusercontent.com/15078762/162941691-1f2a8c2c-c984-4be6-9548-054bb5eb3b49.jpg)

Case 4: The same query will run successfully if you stop passing any values to the filter.
![No values successful query](https://user-images.githubusercontent.com/15078762/162941703-35446329-1ada-451f-94c7-7f994d03c137.jpg)

(Apologies for censored table names, etc. Organisation security and all that.)

**Information about your Metabase Installation:**

- Windows 10, OS Build 19044.1586
- Metabase v.1.41.6
- Chrome Version 100.0.4896.75 (Official Build) (64-bit)
- Postgres database
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Aurora RDS with Postgres compatibililty

**Severity**
Not hugely severe as only causes issues during creating/editing of queries. Mainly causes issues when refactoring/reorganising existing queries as a single commented out filter will cause the query break and commented code isn't usually a place you look for bugs.

**Comment by flamber** [comment] 2022-04-12 11:05
Duplicate of #7742

**Closed by flamber** 2022-04-12 11:05 UTC
Labels: Type:Bug, .Needs Triage
