### ISSUE TITLE
Pulse/sync/etc schedule stops sending after a while and requires restart to work again

### ISSUE THREAD

**Issue by NTag** [metabase/metabase#10088] opened 2019-06-04 12:34 UTC
Hello,
First, thank you for Metabase, it's an awesome tool ❤.

We use Metabase, through its Docker image `metabase/metabase` (v0.32.8).

It's correctly connected to Slack, I can create a Pulse, and clicking "Send to Slack now" works, I receive the Pulse on Slack.

However, the Pulse is scheduled to be sent hourly, but nothing arrives on Slack. Same thing if I choose a daily frequency. After a few searches on Google, people having the same problem said they solved it with a restart of Metabase. Which I did multiple times, but it didn't change anything. Sometimes, the pulse is sent once, but then nothing.

Some information which may help you, from the Troubleshooting part of Metabase:
```
Quartz Scheduler (v2.1.7) 'MetabaseScheduler' with instanceId 'metabase-deployment-fcddbd6d9-8cg5r1559121767103'
  Scheduler class: 'org.quartz.impl.StdScheduler' - running locally.
  Running since: Wed May 29 09:22:47 GMT 2019
  Not currently in standby mode.
  Number of jobs executed: 3
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.impl.jdbcjobstore.JobStoreTX' - which supports persistence. and is clustered.
```

<img width="1194" alt="Capture d’écran 2019-06-04 à 14 18 27" src="https://user-images.githubusercontent.com/906276/58878473-a5d60980-86d3-11e9-84b5-54157af532c6.png">
(☝ this screenshot has been taken at 12:18Z)

<img width="1004" alt="Capture d’écran 2019-06-04 à 14 21 53" src="https://user-images.githubusercontent.com/906276/58879126-33662900-86d5-11e9-9279-63e4d261219d.png">
(I don't know why I don't see anything more recent in the "Tasks" section).

Thank you!

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by AntonTsaberyaby** [comment] 2019-06-05 09:33
I have the same issue

**Comment by AntonTsaberyaby** [comment] 2019-06-05 09:49
Sending to emails also not working

**Comment by mazameli** [comment] 2019-06-20 17:42
Related to https://github.com/metabase/metabase/issues/7986?

**Comment by NTag** [comment] 2019-06-21 08:55
Not sure, because in my case the button "Send to Slack right now" works. It's the scheduling which doesn't, Pulses aren't sent automatically as the scheduled interval.

**Comment by gokula-binary** [comment] 2019-07-17 03:15
We are facing the same issue on Email. Any updates?

**Comment by AntonTsaberyaby** [comment] 2019-08-28 07:35
@flyingmachine I'm installing this version tomorrow and I'll let you know

**Comment by NTag** [comment] 2019-08-28 13:10
I upgraded last week my metabase instance to 0.33.0. I still have the issue.

`Sent to Slack now` works perfectly, but the pulse isn't sent automatically hourly.

<img width="1042" alt="Capture d’écran 2019-08-28 à 15 07 37" src="https://user-images.githubusercontent.com/906276/63858473-d2818080-c9a5-11e9-849c-15f17a2509d3.png">
<img width="1249" alt="Capture d’écran 2019-08-28 à 15 07 49" src="https://user-images.githubusercontent.com/906276/63858474-d31a1700-c9a5-11e9-9968-32586da257be.png">

**Comment by flyingmachine** [comment] 2019-09-04 14:10
Thanks @NTag! I'll look into this more.

**Comment by flyingmachine** [comment] 2019-09-04 20:29
After exploring this more I still can't reproduce the issue :( @NTag are there any other details you could share about your setup that might help us?

* How many pulses are scheduled to be sent?
* How many recipients are there?
* Are there any log entries that include "pulse" or "notificaton" or "quartz" that you could share?
* Do the pulses' questions take a long time to load?

Thanks so much for taking time already to provide details and attach screen shots :) I wish I could figure out what the dang problem is!

@camsaul I also looked into upgrading to the latest version of Quartz and it's not a simple drop-in replacement.

**Comment by NTag** [comment] 2019-09-05 12:10
Ooook, I think I got it working!

When I searched for `quartz` in the logs, I found this:
```
08-20 14:51:47 ERROR core.ErrorLogger :: An error occurred while scanning for the next triggers to fire.
org.quartz.JobPersistenceException: Couldn't acquire next trigger: The database has been closed [90098-197] [See nested exception: org.h2.jdbc.JdbcSQLException: The database has been closed [90098-197]]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2827)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2755)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3798)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2751)
        at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:264)
Caused by: org.h2.jdbc.JdbcSQLException: The database has been closed [90098-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.message.DbException.get(DbException.java:144)
        at org.h2.engine.Database.checkPowerOff(Database.java:536)
        at org.h2.command.Command.executeQuery(Command.java:228)
        at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:114)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)
        at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTriggerToAcquire(StdJDBCDelegate.java:2571)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2778)
        ... 4 more
```

and this:
```
08-22 22:38:22 ERROR jdbcjobstore.JobStoreTX :: ClusterManager: Error managing cluster: Failure identifying failed instances when checking-in: The database has been closed [90098-197]
org.quartz.JobPersistenceException: Failure identifying failed instances when checking-in: The database has been closed [90098-197] [See nested exception: org.h2.jdbc.JdbcSQLException: The database has been closed [90098-197]]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.findFailedInstances(JobStoreSupport.java:3330)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.clusterCheckIn(JobStoreSupport.java:3380)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3240)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3857)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3894)
Caused by: org.h2.jdbc.JdbcSQLException: The database has been closed [90098-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.message.DbException.get(DbException.java:144)
        at org.h2.engine.Database.checkPowerOff(Database.java:536)
        at org.h2.command.Command.executeQuery(Command.java:228)
        at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:114)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)
        at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectSchedulerStateRecords(StdJDBCDelegate.java:2949)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.findFailedInstances(JobStoreSupport.java:3294)
        ... 4 more
```
and nothing related to Quartz since then (22th of August).

So I googled this error, and I found some metabase Github issues where people were advised to avoid H2 database in production and migrate to Postgres or MySQL. This is what I did. And since (three hours) the pulses have been correctly sent to Slack, without any error in the logs 🥳.

So I think the problem is solved for me 🎉 

Thank you very much for your time!

**Comment by NTag** [comment] 2019-09-11 14:12
Hum, I may have spoked a bit too fast, because pulses stopped from being sent 😞. When looking for `quartz` in the logs, I got the following line: `Exception in thread "MetabaseScheduler_QuartzSchedulerThread" java.lang.OutOfMemoryError: Java heap space`

My metabase Docker has 3 Go of RAM. Do you think it's not enough? It's also a shame Quartz didn't restart automatically (because I believe it crashed and never worked from then).

**Comment by flyingmachine** [comment] 2019-09-16 21:43
Thanks for the update! Sorry this happened again. It does seem odd that the scheduling library would be throwing this exception.

This extra info is very useful though. I'm not sure how much memory gets allocated to the JVM process but I'll look into it more.

**Comment by websirnik** [comment] 2019-10-22 16:04
I had this issue when Metabase was deployed to AWS Elastic Beanstack and had a custom domain pointed to AWS via Cloudflare with https support. I had no certificate on the AWS instance.

I've added an SSL certificate for the AWS instance and now I have scheduled pulses getting sent.

**Comment by flamber** [comment] 2020-05-07 14:39
This was encountered in the [forum again](https://discourse.metabase.com/t/pulses-dont-send-automatically/5400/24?u=flamber), and "Next Fire Time" has a time similar to "Start Time", which is similar to https://github.com/metabase/metabase/issues/10088#issuecomment-525738179:
![image](https://user-images.githubusercontent.com/1447303/81306910-5553f280-9080-11ea-916b-adbc97aa78ba.png)
But all instances I have access to has a "Next Fire Time" by the hour on the hour
![image](https://user-images.githubusercontent.com/1447303/81307213-b7acf300-9080-11ea-8ba8-7aa51a0e2eba.png)

**Comment by danwolch** [comment] 2020-06-02 14:52
This is happening to me too. I am logging into elastic beanstalk and rebooting Metabase every couple of days and that seems to fix it. I 👍 the original request.

**Comment by flamber** [comment] 2020-06-02 14:56
@danwolch Can you please post "Diagnostic Info" and a screenshot of the "metabase.task.send-pulses.job"  from Admin > Troubleshooting > Jobs

**Comment by jlisyc** [comment] 2020-06-29 06:14
Hi all,
when a pulse is sending to an email theres's an error like
![image](https://user-images.githubusercontent.com/33416503/85979276-7251d580-b9e0-11ea-8a8e-2f2e3c511834.png)
in the email sended.
(v.0.35.4)

**Comment by flamber** [comment] 2020-06-29 11:04
@jlisyc Check the logs for errors - Admin > Troubleshooting > Logs. It's very likely not related to this issue at all.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by jlisyc** [comment] 2020-06-30 06:45
Hi @flamber
If I go to this pulse report (link to the report of the pulse ) it's executing Ok (it's a simple count) .
In logs I can see:
![image](https://user-images.githubusercontent.com/33416503/86092464-d1c9e700-baad-11ea-9557-e5c3238ad71d.png)

**Comment by flamber** [comment] 2020-06-30 09:12
@jlisyc And you left out the most important part of the log, the actual stacktrace. Please paste errors as text instead of images. Again, I'm 99% sure that you're not seeing this issue.

**Comment by jlisyc** [comment] 2020-07-01 06:11
@flamber You are absolutely right. It was a matter of permissions. Someone had removed permissions to see that card to that user. I'm Sorry.

**Comment by abdidarmawan007** [comment] 2020-08-30 03:17
have same issue

**Comment by tsmacdonald** [comment] 2020-10-28 21:50
I just spent a day trying to reproduce this locally, including stress-testing my memory and DB usage (both H2 and Postgres), running the pulse-sending job every second (instead of every hour), and killing the Postgres server. I couldn't get a repro though.

My suspicion is that Quartz is behaving reasonably and we're seeing this failure because for other reasons. H2 is a problem, and the only error I see with not-H2 (Postgres) is an `OutOfMemoryError`, which is a separate problem. Also, per @camsaul, recent versions of Metabase are much more responsible with memory management.

@flamber, do you think it's okay to close this, or at least relabel it to not-a-P1?

**Comment by rlotun** [comment] 2020-12-14 19:46
It would be great if there were any reproductions of this on 37.2+. We included a bunch of fixes for memory usage related to sync in that version, which _might_ have been one of the conditions leading to this bug. Since we can't verify it's hard for us to say for sure. 

A few things:
1. Could any/all of @abdidarmawan007 @danwolch @NTag @AntonTsaberyaby @gokula-binary kindly try to see if they can still reproduce it on 0.37.2 or 0.37.3? Any other information will help us tremendously - we'd love to fix this old P1 ASAP
2. I'm going to move this to our last maintenance milestone for 37 to see if we get any information in time to include a fix in the 37 series. If we don't get anything to reproduce it by then we'll probably have to label this issue with `.cannot reproduce`.

**Comment by AntonTsaberyaby** [comment] 2020-12-15 06:48
@rlotun Thanks. Will check on weekend

**Comment by rlotun** [comment] 2021-01-06 02:58
Any update @AntonTsaberyaby ?

**Comment by abchk1234** [comment] 2021-01-06 18:59
@rlotun facing this issue on a metabase instance hosted in docker and using postgres as DB. Metabase version is v0.37.5.

Task status pic below. Restarted it recently so last fired is empty.
![image (4)](https://user-images.githubusercontent.com/5509426/103809213-2b275a00-507f-11eb-8f66-76519c227ac6.png)

Happy to provide any more info as needed. Thanks!

**Comment by paoliniluis** [comment] 2021-02-15 21:43
@abchk1234 I'm looking into this one and we strongly believe this is due to having long-running pulses that might prevent all pulses from firing. Will you be able to detail the pulses you have with the running time of the queries that generate those pulses? thanks

**Comment by abdidarmawan007** [comment] 2021-02-16 08:03
im create new fresh install metabase version metabase:v0.36.4
now i don't have problem with pulse

pulse not working if you upgrade from very old metabase to new version, my advice just create/install new metabase

**Comment by abchk1234** [comment] 2021-02-16 13:38
> @abchk1234 I'm looking into this one and we strongly believe this is due to having long-running pulses that might prevent all pulses from firing. Will you be able to detail the pulses you have with the running time of the queries that generate those pulses? thanks

Thanks for checking @paoliniluis ! Its quite possible that other pulses run around time to the one we are monitoring. I have access of a certain section of our metabase server; will try to get hold of an admin and see what all pulses we have running.

If someone else can provide this information, that would be great as well. Thanks! CC @AntonTsaberyaby @NTag

**Comment by camsaul** [comment] 2021-02-26 22:46
@paoliniluis adding you as the assignee since you're currently looking in to it

**Comment by camsaul** [comment] 2022-02-25 13:24
I think this should be fixed with the changes from #20343 and the changes to use custom `javax.sql.DataSource`s for the application DB -- going to close this as fixed in 43 and we can reopen if we get more reports after than

**Comment by flamber** [comment] 2022-05-29 08:45
I had really hoped this was solved, but 43.1 can still get into a state, where the entire Quartz scheduler stops working - even sync stops running. This is the entire log from 20:12:03 thru 04:50:31, where there's normally multiple databases being synced hourly.
```
2022-05-28 20:12:03,656 INFO sync.util :: [35mFINISHED: Analyze data for postgres Database 2 'ProdDB' (20.6 mins)[0m
2022-05-28 20:12:03,929 INFO task.send-pulses :: Sending scheduled pulses...
2022-05-28 20:20:31,093 INFO jdbcjobstore.JobStoreTX :: Handling 2 trigger(s) that missed their scheduled fire-time.
2022-05-28 20:35:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 2 trigger(s) that missed their scheduled fire-time.
2022-05-28 20:50:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 2 trigger(s) that missed their scheduled fire-time.
2022-05-28 21:20:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 5 trigger(s) that missed their scheduled fire-time.
2022-05-28 21:35:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 2 trigger(s) that missed their scheduled fire-time.
2022-05-28 21:50:31,094 INFO jdbcjobstore.JobStoreTX :: Handling 3 trigger(s) that missed their scheduled fire-time.
2022-05-28 22:20:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 4 trigger(s) that missed their scheduled fire-time.
2022-05-28 22:35:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 2 trigger(s) that missed their scheduled fire-time.
2022-05-28 22:50:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 3 trigger(s) that missed their scheduled fire-time.
2022-05-28 23:20:31,093 INFO jdbcjobstore.JobStoreTX :: Handling 4 trigger(s) that missed their scheduled fire-time.
2022-05-28 23:35:31,093 INFO jdbcjobstore.JobStoreTX :: Handling 2 trigger(s) that missed their scheduled fire-time.
2022-05-28 23:50:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 3 trigger(s) that missed their scheduled fire-time.
2022-05-29 00:05:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 1 trigger(s) that missed their scheduled fire-time.
2022-05-29 00:20:31,093 INFO jdbcjobstore.JobStoreTX :: Handling 5 trigger(s) that missed their scheduled fire-time.
2022-05-29 00:35:31,093 INFO jdbcjobstore.JobStoreTX :: Handling 3 trigger(s) that missed their scheduled fire-time.
2022-05-29 00:50:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 3 trigger(s) that missed their scheduled fire-time.
2022-05-29 01:05:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 1 trigger(s) that missed their scheduled fire-time.
2022-05-29 01:20:31,093 INFO jdbcjobstore.JobStoreTX :: Handling 4 trigger(s) that missed their scheduled fire-time.
2022-05-29 01:35:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 3 trigger(s) that missed their scheduled fire-time.
2022-05-29 01:50:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 3 trigger(s) that missed their scheduled fire-time.
2022-05-29 02:05:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 1 trigger(s) that missed their scheduled fire-time.
2022-05-29 02:20:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 4 trigger(s) that missed their scheduled fire-time.
2022-05-29 02:35:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 3 trigger(s) that missed their scheduled fire-time.
2022-05-29 02:50:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 3 trigger(s) that missed their scheduled fire-time.
2022-05-29 03:05:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 1 trigger(s) that missed their scheduled fire-time.
2022-05-29 03:20:31,093 INFO jdbcjobstore.JobStoreTX :: Handling 5 trigger(s) that missed their scheduled fire-time.
2022-05-29 03:35:31,093 INFO jdbcjobstore.JobStoreTX :: Handling 3 trigger(s) that missed their scheduled fire-time.
2022-05-29 03:50:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 3 trigger(s) that missed their scheduled fire-time.
2022-05-29 04:05:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 1 trigger(s) that missed their scheduled fire-time.
2022-05-29 04:20:31,093 INFO jdbcjobstore.JobStoreTX :: Handling 5 trigger(s) that missed their scheduled fire-time.
2022-05-29 04:35:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 3 trigger(s) that missed their scheduled fire-time.
2022-05-29 04:50:31,092 INFO jdbcjobstore.JobStoreTX :: Handling 3 trigger(s) that missed their scheduled fire-time.
```
The `qrtz_triggers.prev_fire_time` is `1653768000000` (at 20:00:00, the last time it tries to send pulses), but it has set `qrtz_triggers.next_fire_time` to `1653798031101` (at 04:20:31)

Looks like we need some check somewhere, so if next_fire_time is not on a specific hour, then redo the schedule. Or have it automatically fire and reschedule, when current_timestamp>next_fire_time.

**Comment by Chandra-cp** [comment] 2023-02-27 06:19
I currently using Metabase version v0.35.4. It doesn't send the auto-scheduled emails(pulse reports) and also doesn't send when I press **"Send Email Now"** for a week. I have checked the error message in the log and it's showing as **"2023-02-27T00:00:21+05:30 WARN metabase.email Failed to send email"**. Is there a way that I can debug it?

![image](https://user-images.githubusercontent.com/126444481/221488744-59ca65fa-2b96-4feb-a9c8-7c09e6001be1.png)

**Comment by paoliniluis** [comment] 2023-02-27 06:46
@Chandra-cp upgrade Metabase

**Comment by markbastian** [comment] 2024-02-12 20:50
Related to https://github.com/metabase/metabase/issues/37459?

**Comment by qnkhuat** [comment] 2024-05-24 07:25
might relate to this issue we see on stats a while ago: https://metaboat.slack.com/archives/C078VCLF3/p1715339633521029

**Comment by qnkhuat** [comment] 2024-07-23 02:12
We've refactored how we schedule send pulse in https://github.com/metabase/metabase/pull/41772. Before, we had one trigger that sent all pulses; now, each pulse will have its own trigger.

Hopefully this fixes the issue. If anyone still encounters this issue, please reopen it.

**Closed by qnkhuat** 2024-07-23 02:12 UTC
Labels: Type:Bug, Priority:P1, Reporting/Pulses, Operation/, Difficulty:Hard, .Backend, .Cannot Cypress Test, .Team/BackendComponents
