### ISSUE TITLE
Generic discussions/threads

### ISSUE THREAD

**Issue by Obsecurus** [metabase/metabase#13292] opened 2020-09-22 14:56 UTC
**Is your feature request related to a problem? Please describe.**
It's frustrating when you're writing queries or constructing dashboards and you want to share context outside of the queries/dashboards themselves but have that discussion natively in Metabase.

**Describe the solution you'd like**
Having a generic discussion mechanism where authenticated users can leave notes on a dashboard, answer, or group/container would be extremely helpful. This would enable a more social/collaborative environment in metabase.

**Describe alternatives you've considered**
We find that we have to use Slack or other communications methods and just reference various metabase boards. However, this feels clunky and means you have to bounce between whatever communication component and metabase. 

**How important is this feature to you?**
This feature could significantly reduce communication barriers across our analysis team.

**Comment by flamber** [comment] 2020-09-22 14:59
Duplicate of #9553

**Closed by flamber** 2020-09-22 14:59 UTC
Labels: .Needs Triage, Type:New Feature
