### ISSUE TITLE
Korean type problem

### ISSUE THREAD

**Issue by iamkyu** [metabase/metabase#4354] opened 2017-02-10 01:57 UTC
When I Type in Korean on Query editor, It input with irregular sequence.
[Check my record (GIF)](https://lh3.googleusercontent.com/tnME12jmlpIoRxTMf8NyL5TEbtPEW6xfq2Wfy5PA8Bs9hd8_9-RXhZgjhA-fjGFZGAjg5-5w0w4Ij93KLea0SMnbxh9ah2FxHpbf4cQ8QxSOYLFqfC_tk-z1uFljruE65jXSCqogxlh2avSo7Dx9yqaDZ39a_PZzuUu2u9G5HVdteUQpM6HZcY51K4m4WfiEkj1-54zQQcnHPbFd1r86btc_lDMiRQiGwxEVmTy19ByT-e5dm70ekZZoOUQ5IUjxbJV8SeAaxHtzDHeLG_ICvq9C13v66dzLOtdZgXPIYTVTOMPnnTHa80sySTABUwwv7tCwTTpAyCntVhw25Yt2W845bOtpA4xaffUGp8bOosH2upxnfzw-Phl08F4p3VBSrfyIRB0-TEP6vsqNBvhj15LLrdEEmSiUi6S5mpHA38ShXITisTMgASVZo1C6z_pfyva_KkBTTZNhHrh4pCjwlezj156y6CsP58VlgEPNhn6VW9nmgCDZlrNHOstk5n9rhvGj2-2qa6rjoXaf9TL8YcYBLW5qO-2TljrwEpCdoMFYN4S3cQs6QfsdH6yKy-lGSaclKhDA2K3WuGQRSNXKiV-_-0GDLlvz5t_449ONCAVxgZDXOU32e317LyQRGOcvinIgXW3XcCf_mrF60_ULc3UTWJ8dp3Kd0B8vMiAqzQ=w544-h361-no)

[Environment]
- macOS Sierra 10.12.3
- Metabase v0.22.2
- Chrome 56.0.2924.87 (64-bit)
- Firefox Developer Edition 52.0a2 (2017-01-03) (64bit)
- Safari v.10.0.3(12602.4.8) => `Working Exactly`

**Comment by camsaul** [comment] 2017-02-10 18:50
Hi @iamkyu, this sounds like a duplicate of #2344.

Unfortunately the ACE Editor library we're using has a few issues with Unicode support but hopefully they'll be addressed in the future.

**Closed by camsaul** 2017-02-10 18:50 UTC
Labels: Duplicate
