### ISSUE TITLE
No tables found in database

### ISSUE THREAD

**Issue by im360john** [metabase/metabase#6825] opened 2018-01-30 20:38 UTC
About 2-3 times a week, we see a no tables found in database error.  This is fixed by manually initiating a sync.  The table and field entries still exist within the metabase db, and nothing is noticeably wrong within the log (entries of Sync completing without error).   This doesn't happen on Mysql DBs but does on Postgres.   

1)  Is there an endpoint or command line that we can trigger on server side to force the manual database sync?  

2)  Any other logs we can check out for more details?   

Thanks,

https://imgur.com/NyT3xkV

- Your browser and the version: Various, mostly Chrome latest 63.0
- Your operating system: Various, mostly Windows 10
- Your databases: PostGres 9.2 through Amazon RDS
- Metabase version: 0.27.2
- Metabase hosting environment: Both Elastic and Ubuntu 14.x
- Metabase internal database: Mysql

Thanks for being part of the Metabase project!
-------

**Comment by salsakran** [comment] 2018-02-02 19:51
When the sync process runs a schema check and finds no tables, it will mark existing tables as "inactive". 

How are those tables being populated in Postgres?

**Comment by aviggiano** [comment] 2018-03-06 03:03
I am having the same issue with MongoDB

**Comment by someshwarbhale** [comment] 2018-03-15 04:50
I am also having same issue with oracle DB while using custom query builder.
Someone Plzz help.

**Comment by blopker** [comment] 2018-04-04 23:52
I just want to confirm the is happening in MySQL for us. It seems like the scheduled sync is *causing* it to happen. When I run the schema sync manually the tables come back for about an hour until the scheduler runs again.

The other odd thing is we have 10 other MySQL databases that are fine. Only one is having schema issues.

**Comment by petit-pois** [comment] 2018-06-13 13:19
We also observe **occasional sync issues on some tables** that have scheduled syncs configured (at the datasource level). We are using mySQL as metadata storage. To us, it looks like the sync process "missed" existing tables when query the metadata, so assume they are new and insert a new entry to the metadata which overwrite the changes we made to the tables (e.g display name, description, associated questions)

**Comment by dannyeuu** [comment] 2018-08-27 21:40
@salsakran This happens when I use multiples database, cuz in MySQL they use databases like same modern databases use schemas, right?!

Maybe for MySQL is not necessary at connection setup explicit a database name and read all that the given user can see.

**Comment by asyncopation** [comment] 2019-02-26 17:36
Your browser and the version: Chrome/FF
Your operating system: Debian/macOS
Your databases: Redshift
Metabase version: 0.31.2
Metabase hosting environment: Docker
Metabase internal database: Postgres

We are experiencing the same issue with one added detail: only the `public` schema is experiencing the random deactivation via the scheduled sync.  We have not seen this issue with any other schema in the Redshift db.

Nothing obvious in the logs, and a manually triggered Sync brings it back.

**Comment by josteinaj** [comment] 2019-03-06 08:59
I was about to create a new issue but I think this is the same issue as I'm having so I'm adding the description here instead (let me know if I should create a separate issue). This seems similar to #9492 as well but I'm not sure if it's the same issue or not.

## Tables disappear from database when atomically swapping out the table

- Your browser and the version: Chromium 72.0.3626.119
- Your operating system: Ubuntu 18.04.2 LTS
- Your databases: MariaDB Ver 15.1 Distrib 10.1.38-MariaDB
- Metabase version: v0.31.2
- Metabase hosting environment: Docker
- Metabase internal database: MariaDB Ver 15.1 Distrib 10.1.34-MariaDB

**Repeatable steps to reproduce the issue:**
- Set up a database with some tables and columns
- Do an atomic swap of the tables with a new version of the table:
  - `RENAME TABLE tablename TO old_tablename, new_tablename TO tablename;`
- Sometimes (not sure if it happens every time but at least very often), the database will appear in Metabase with "No tables found in this database." (new question) / "0 schemas" (data model)
- If I go to "Databases" > database name > "Sync database schema now", then Metabase finds all the tables again, and restores all the table names, column names, column comments, metrics etc.

So it seems like the tables are marked as "inactive", even though the tables are swapped atomically (as far as I know). Maybe Metabase references the tables by some internal MariaDB identifier instead of the table names, if there is such a thing, and those identifiers change when swapping out the table?

**Comment by camsaul** [comment] 2019-03-29 21:53
Fixed by #9638

**Closed by camsaul** 2019-03-29 21:53 UTC
Labels: Bug, Metadata/Sync
