### ISSUE TITLE
Filtering Multiple IDs on Metabase Dashboard

### ISSUE THREAD

**Issue by psrawke** [metabase/metabase#9531] opened 2019-03-08 06:40 UTC
Hi

I have created a metabase dashboard for my application and added a filter on **user id** field. I am able to view the data on the dashboard by filtering user id one at a time properly, like user id = 10, user id 15 etc.

I was wondering if is it possible to select multiple user ids through the filter. I have **comma-separated** list of user ids, and it will be really helpful if I can enter the list directly. Any help will be appreciated. :)

(PS.: I am open to change the **delimiter** from comma to any other character like space / hyphen etc.)

Thanks,
Prasanna

**Comment by flamber** [comment] 2019-03-08 16:54
Hi @psrawke 
When I paste a string like this `1,3,5,32` into a filter, then it gets converted to `1`  `3`  `5`  `32`
Which version are you using?

**Comment by psrawke** [comment] 2019-03-14 05:56
Hey @flamber 
I know how to recreate the bug. If the dashboard has a **default value** to the **id filter**, then pasting a comma separated string gets converted to distinct ids,  and it results properly.

But when there is no default value to the id filter, it doesnt convert the entered comma separated string into distinct ids.

**Comment by flamber** [comment] 2019-03-14 13:07
@psrawke 
I cannot reproduce your issue on 0.31.2 with Firefox 65 or Chromium 72

**Comment by camsaul** [comment] 2019-09-28 01:55
Closing as already fixed. Thanks @flamber

**Closed by camsaul** 2019-09-28 01:55 UTC
Labels: .Unable to Reproduce, Parameters/Variables, Priority:P3, Reporting/Dashboards, Type:Bug
