### ISSUE TITLE
Duplicated subdimensions for date/time binning

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#15574] opened 2021-04-12 16:59 UTC
**To Reproduce**
1. Ask a question, Custom question
2. Sample Dataset, Orders table
3. For _Summarize_, Pick a column to group by
4. Created At click on "by month >" to open a popup

**Expected behavior**
The popup does not have duplicated entries.

**Actual behavior**

The popup contains duplicated entries, e.g. for "Minutes".

![image](https://user-images.githubusercontent.com/7288/114432653-c85dc700-9b75-11eb-9c8e-194b9132a07c.png)

**Comment by camsaul** [comment] 2021-04-13 20:49
@ariya Please don't forget to check that the GH issues get closed once you've merged a PR to fix them 😉

**Comment by nemanjaglumac** [comment] 2021-04-13 20:51
@camsaul this issue **wasn't** fixed in 15582. Those are two separate issues, although very related.

**Comment by camsaul** [comment] 2021-04-13 20:52
Ok. Maybe don't put

> It fixes #15574

in the PR description if it doesn't actually fix it 😉

**Comment by nemanjaglumac** [comment] 2021-04-13 20:57
I am sorry for the confusion caused by reopening and then closing the issue again. I confused it with the related issue.

**Closed** 2021-04-13 20:57 UTC
Labels: .Regression, .Reproduced, Priority:P2, Querying/GUI, Type:Bug
