### ISSUE TITLE
Data model does not populate fields for a view containing count and group by in SQLite

### ISSUE THREAD

**Issue by JohnAtFenestra** [metabase/metabase#9276] opened 2019-01-16 21:28 UTC
### Bugs

If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: N/A
- Your operating system: Ubuntu 16.04
- Your databases: SQLite
- Metabase version: 0.31.2
- Metabase hosting environment: Ubuntu running local jar file
- Metabase internal database: default

### Repeatable steps to reproduce the issue

Using SQLite, create the following table and view

```
create table foo (id int, value text, tag text);
create view foo2 as select tag, count(*) total from foo group by tag;
create view foo3 as select value from foo where tag = 'a';
```

Populate the table with random data; e.g. using Ruby:

```ruby
require 'sequel'

filename = 'demo-db.sqlite'

File.delete(filename) if File.exists?('demo-db.sqlite')

Sequel::sqlite(filename) do |client|
    client.run <<-eof
create table foo (id int, value text, tag text);
create view foo2 as select tag, count(*) total from foo group by tag;
create view foo3 as select value from foo where tag = 'a';
    eof

    dataset = client[:foo]

    client.transaction do
        1000.times do |i|
            dataset.insert(id: i, value: i.to_s, tag: (i % 4) == 0 ? 'a' : 'b')
        end
    end
end

```
Attach the database.
Examine the data model

foo and foo3 have fields
foo2 does not have any fields

Attempt to question foo2 you get

There was a problem with your question
Most of the time this is caused by an invalid selection or bad input value. Double check your inputs and retry your query.

### Log

```
Jan 16 16:23:12 WARN metabase.query-processor :: {:status :failed,
:class java.lang.Exception,
:error "Table 'foo2' has no Fields associated with it.",
:stacktrace
("--> query_processor.middleware.add_implicit_clauses$fn__30627$add_implicit_fields__30632$fn__30638.invoke(add_implicit_clauses.clj:81)"
"query_processor.middleware.add_implicit_clauses$fn__30627$add_implicit_fields__30632.invoke(add_implicit_clauses.clj:64)"
"query_processor.middleware.add_implicit_clauses$fn__30721$add_implicit_mbql_clauses__30726$fn__30732.invoke(add_implicit_clauses.clj:107)"
"query_processor.middleware.add_implicit_clauses$fn__30721$add_implicit_mbql_clauses__30726.invoke(add_implicit_clauses.clj:105)"
"query_processor.middleware.add_implicit_clauses$maybe_add_implicit_clauses.invokeStatic(add_implicit_clauses.clj:116)"
"query_processor.middleware.add_implicit_clauses$maybe_add_implicit_clauses.invoke(add_implicit_clauses.clj:114)"
"query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__30830.invoke(add_row_count_and_status.clj:15)"
"query_processor.middleware.driver_specific$process_query_in_context$fn__32181.invoke(driver_specific.clj:12)"
"query_processor.middleware.resolve_driver$resolve_driver$fn__35350.invoke(resolve_driver.clj:15)"
"query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31376$fn__31377.invoke(bind_effective_timezone.clj:9)"
"util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
"util.date$call_with_effective_timezone.invoke(date.clj:77)"
"query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31376.invoke(bind_effective_timezone.clj:8)"
"query_processor.middleware.store$initialize_store$fn__37567$fn__37568.invoke(store.clj:11)"
"query_processor.store$do_with_new_store.invokeStatic(store.clj:34)"
"query_processor.store$do_with_new_store.invoke(store.clj:30)"
"query_processor.middleware.store$initialize_store$fn__37567.invoke(store.clj:10)"
"query_processor.middleware.cache$maybe_return_cached_results$fn__31798.invoke(cache.clj:127)"
"query_processor.middleware.catch_exceptions$catch_exceptions$fn__31846.invoke(catch_exceptions.clj:64)"
"query_processor$process_query.invokeStatic(query_processor.clj:213)"
"query_processor$process_query.invoke(query_processor.clj:209)"
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:322)"
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:316)"
"query_processor$fn__37732$process_query_and_save_execution_BANG___37737$fn__37738.invoke(query_processor.clj:354)"
"query_processor$fn__37732$process_query_and_save_execution_BANG___37737.invoke(query_processor.clj:340)"
"query_processor$fn__37756$process_query_and_save_with_max_BANG___37761$fn__37762.invoke(query_processor.clj:373)"
"query_processor$fn__37756$process_query_and_save_with_max_BANG___37761.invoke(query_processor.clj:369)"
"api.dataset$fn__44259$fn__44262.invoke(dataset.clj:45)"
"api.common$fn__23158$invoke_thunk_with_keepalive__23163$fn__23164$fn__23165.invoke(common.clj:435)"),
:query
{:type "query",
:query {:source-table 19},
:parameters [],
:constraints {:max-results 10000, :max-results-bare-rows 2000},
:info
{:executed-by 1,
:context :ad-hoc,
:card-id nil,
:nested? false,
:query-hash [-6, -48, 53, -108, 64, -26, 57, 22, 94, -122, -92, -44, -36, -7, -78, -120, -89, 83, 23, -64, -112, 35, 25, -55, 85, 113, 109, -111, -128, -67, 56, 74],
:query-type "MBQL"}},
:preprocessed nil,
:native nil}

Jan 16 16:23:12 WARN metabase.query-processor :: Query failure: Table 'foo2' has no Fields associated with it.
("clojure.core$ex_info.invokeStatic(core.clj:4739)"
"clojure.core$ex_info.invoke(core.clj:4739)"
"--> query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:285)"
"query_processor$assert_query_status_successful.invoke(query_processor.clj:277)"
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:323)"
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:316)"
"query_processor$fn__37732$process_query_and_save_execution_BANG___37737$fn__37738.invoke(query_processor.clj:354)"
"query_processor$fn__37732$process_query_and_save_execution_BANG___37737.invoke(query_processor.clj:340)"
"query_processor$fn__37756$process_query_and_save_with_max_BANG___37761$fn__37762.invoke(query_processor.clj:373)"
"query_processor$fn__37756$process_query_and_save_with_max_BANG___37761.invoke(query_processor.clj:369)"
"api.dataset$fn__44259$fn__44262.invoke(dataset.clj:45)"
"api.common$fn__23158$invoke_thunk_with_keepalive__23163$fn__23164$fn__23165.invoke(common.clj:435)")
```

**Comment by JohnAtFenestra** [comment] 2019-01-16 21:49
The example shows that it works fine with a VIEW that does not contain a group by:

```
create view foo3 as select value from foo where tag = 'a';
```

**Comment by camsaul** [comment] 2020-07-09 21:03
This sounds like fundamentally the same issue as #12191, #8630, #10681, and others. PR #11358 would likely address this

**Comment by sbelak** [comment] 2020-07-13 12:50
Duplicate of #12547

**Closed by sbelak** 2020-07-13 12:50 UTC
Labels: Administration/Metadata & Sync, Database/SQLite, Priority:P2, Type:Bug
