### ISSUE TITLE
Introduce option to hide or select filter based on Tab

### ISSUE THREAD

**Issue by ivishalgandhi** [metabase/metabase#33361] opened 2023-08-19 16:43 UTC
**Is your feature request related to a problem? Please describe.**
Not all filters on the dashboard apply to data in a specific tab. Allow option to have filter based on tabs. e.g. Filter 1 may be applicable for Tab 1, 4, 5 and may not be applicable for questions, charts, queries in tab 2.

**Describe the solution you'd like**
Not all filters on the dashboard apply to data in a specific tab. Allow option to have filter based on tabs. e.g. Filter 1 may be applicable for Tab 1, 4, 5 and may not be applicable for questions, charts, queries in tab 2.

**Describe alternatives you've considered**
Add additional filters which may not be relevant to tab

**How important is this feature to you?**
Very important

**Additional context**

Provide option to select the tab
![image](https://github.com/metabase/metabase/assets/12184532/f99d7dc2-4444-4382-9aae-c2c16a9a026c)

**Comment by paoliniluis** [comment] 2023-08-24 14:18
I think this is a dupe of https://github.com/metabase/metabase/issues/31621

**Closed by paoliniluis** 2023-08-24 14:18 UTC
Labels: Type:New Feature, .Needs Triage
