### ISSUE TITLE
Cannot find an archived collection in the archives

### ISSUE THREAD

**Issue by capmann** [metabase/metabase#28444] opened 2023-02-20 12:43 UTC
I archived one question inside a a collection, and it seems like this archived the whole collection (because it disappeared from its place), but I cannot find the collection in the archives. 

Could you please help? A whole collection with dashboards and questions disappears, and that is going to be very painful for my team.

Thanks a lot!

**Comment by paoliniluis** [comment] 2023-02-20 13:59
It’s a duplicate of https://github.com/metabase/metabase/issues/21341. Please post your question in the forum

**Closed by paoliniluis** 2023-02-20 13:59 UTC
Labels: Type:Bug, .Needs Triage
