### ISSUE TITLE
region’s display name show Garbled in chinese

### ISSUE THREAD

**Issue by 8debug** [metabase/metabase#15610] opened 2021-04-14 07:25 UTC
**Describe the bug**
region’s display name show Garbled in chinese

**Logs**

**To Reproduce**
1. Go to Settings > Admin > Maps
2. Click on 'Add a map' 
3. input name: 沈阳; URL of GenJSON: https://geo.datav.aliyun.com/areas_v2/bound/210100_full.json; region’s identifier: adcode; region’s display name: name
4. region’s display name is Garbled

**Expected behavior**
region’s display name can be displayed normally

**Screenshots**
![image](https://user-images.githubusercontent.com/3394927/114670250-5fbd4880-9d35-11eb-99f9-06dfc700d144.png)

**Information about your Metabase Installation:**
```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "GBK",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_101-b13",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_101",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.101-b13",
    "os.name": "Windows NT (unknown)",
    "os.version": "10.0",
    "user.language": "zh",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.38.4",
      "date": "2021-04-08",
      "branch": "release-x.38.x",
      "hash": "057b6bb"
    },
    "settings": {
      "report-timezone": "Asia/Shanghai"
    }
  }
}
```

- Chrome 88.0.4324.104
- Windows 10 Pro
- MySQL5.7
- Metabase version: v0.38.4
- Metabase hosting environment: Windows Server 2016 Datacenter、Windows 10 Pro
- Metabase internal database: H2

**Comment by flamber** [comment] 2021-04-14 07:54
Duplicate of #12962

**Closed by flamber** 2021-04-14 07:54 UTC
Labels: .Needs Triage, Type:Bug
