### ISSUE TITLE
The dashboards loads for a long time

### ISSUE THREAD

**Issue by tonny0718** [metabase/metabase#5651] opened 2017-08-01 10:06 UTC
I have a large Mysql database with many tables, when I look at my database, I need to wait for a long time to see and slide my page. It seems that there is a large file called 'metadata' that affects the page display and sliding, is there any way to not load that seems to have a lot of irrelevant data

**Comment by camsaul** [comment] 2017-08-01 17:24
Duplicate of #5607 

@tonny0718 we're looking at how to address this issue.

**Closed by camsaul** 2017-08-01 17:24 UTC
