### ISSUE TITLE
Email Subscriptions don't respect Split Y-Axis or Manual Y-Axis Settings

### ISSUE THREAD

**Issue by joebi3** [metabase/metabase#23195] opened 2022-06-07 14:13 UTC
**Describe the bug**
Email Subscriptions don't respect Split Y- Axis or Manual Y-Axis Settings. 
In the below question "Auto Y Axis" is turned off, and I've manually set the Y Axis size, as shown in the screenshot underneath

![image](https://user-images.githubusercontent.com/29917166/172399321-42e90237-385e-4c82-9ac6-f04aa11fa152.png)

![image](https://user-images.githubusercontent.com/29917166/172399495-35c59534-0c72-46d9-9e0d-42a5a1b0a63b.png)

When the chart is generated for an email subscription it appears to ignore both the split the axis setting and the manually set Y Axis settings. This causes confusion amongst end users, as the series on the chart are scaled differently, but at first glance this isn't obvious. 
![image](https://user-images.githubusercontent.com/29917166/172402552-d949ea2b-794b-4d55-99da-7d809f0fc080.png)

**To Reproduce**
1. create a question with more than one data set on the Y Axis using a bar chart as the display method. 
2. Add the question to a dashboard.
3. Create a dashboard subscription for the question to be sent as an email. 
4. Send the dashboard email to yourself. 

**Expected behavior**
Y Axis behaviour for Subscriptions should follow the settings applied in the question. 
If Auto Split Y Axis is disabled in the question, it should be disabled in the Subscription. Similarly if A manual axis is specified in the question it should be applied in the subscription. 

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "4.14.268-205.500.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.28"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.5"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-04-07",
      "tag": "v0.42.4",
      "branch": "release-x.42.x",
      "hash": "7c3ce2d"
    },
    "settings": {
      "report-timezone": "Europe/London"
    }
  }
}

**Severity**
This is blocking us from being able to share reports with key stakeholders as we don't use slack internally, and most of them just use it for overview reports so very rarely log into the application itself.

**Comment by flamber** [comment] 2022-06-07 14:14
Duplicate of #20559

**Closed by flamber** 2022-06-07 14:14 UTC
Labels: Type:Bug, .Needs Triage
