### ISSUE TITLE
Pulse sends table instead of pie to slack

### ISSUE THREAD

**Issue by michabbb** [metabase/metabase#4567] opened 2017-03-21 21:12 UTC
You're on version v0.22.2
Built on 2017-01-26
Docker

hi, 
i wanted to ask, if its a bug or a wanted feature.
a question with a pie gets posted to slack as a simple table.

thanks,
micha

**Comment by mazameli** [comment] 2017-03-21 21:15
Yeah, the Slack/Metabot behavior is that it tries to convert included questions to formats that are nicer and more compact for email/Slack, but we've definitely heard from users that this can be unexpected and undesirable.

Duplicate of #2937.

**Closed** 2017-03-21 21:15 UTC
Labels: Duplicate

**Comment by michabbb** [comment] 2017-03-21 21:21
@mazameli pardon, i don´t understand this, because [the website](http://www.metabase.com/docs/latest/users-guide/10-metabot) shows me this image:

![img](http://www.metabase.com/docs/latest/users-guide/images/metabot/MetabotShow.png)

okay, its not a pie, but its no table at all... so what does this mean ? shows the website wrong infos,
or are only special kind of graphs possible, and if yes, which ones ?

thanks !

**Comment by mazameli** [comment] 2017-03-21 21:37
Sorry, I should've explained more. Pulses can display one of the following:
- number (scalar)
- spark line
- horizontal bar graph
- truncated table

The [logic for this is here](https://github.com/metabase/metabase/blob/8f1a287496899250d89a20ec57ac8477cd20bce5/src/metabase/pulse/render.clj#L385-L397), but basically, time series get shown as spark lines (like the image in your comment); pie charts, bar graphs, region maps, funnels, and anything else that's an aggregation broken out by a non-time dimension get turned into horizontal bar graphs; and any other aggregation + breakout is shown as a truncated table. Raw, unaggregated tables can't be included. What's going on is that the Pulse logic is looking at the format of the underlying data table; it doesn't care about the visualization that the saved question is using.

**Comment by michabbb** [comment] 2017-03-21 21:39
okay, **NOW** i understand 😄 thanks !

**Comment by mazameli** [comment] 2017-03-21 21:40
You bet. Sorry about the confusion!
