### ISSUE TITLE
Smarter dashboard cards refresh

### ISSUE THREAD

**Issue by Olaktal** [metabase/metabase#18105] opened 2021-09-28 20:49 UTC
Hello guys,

In dashboards, why does changing a filter value refresh all cards instead of refreshing only cards linked to the filter ?

For example i have a dashboard with 2 cards: one with a product list and another card which is a graph representing this specific product sales.
I added a click behavior which when I click on the product, will fulfill a filter (Product ID) that will refresh the product sales graph. But it refresh my product list as well (and the card pages goes back to the first one which is quite anoying when you have a lot a product)

If it's too complicated, maybe we could add a toggle on the top right of each cards to disable refresh manually ?

Thanks for the answer(s) !

**Comment by flamber** [comment] 2021-09-28 21:01
Duplicate of #14138/#8030

**Closed by flamber** 2021-09-28 21:01 UTC
Labels: Type:New Feature, .Needs Triage
