### ISSUE TITLE
Metabase version v0.45.1 - Metadata bug repeat description field

### ISSUE THREAD

**Issue by Breriv22** [metabase/metabase#27438] opened 2022-12-28 09:27 UTC
**When edit metadata in metabse on description field the first description added instantly added to the next fields **

**To Reproduce**
1. Go to any model 
2. Click on edit metadata
3. Select any field (you will see the details on it)
4. Edith the description field 
5. Go to next field 
6. Description field will appear with previous comment 

**Expected behavior**
1. Go to any model 
2. Click on edit metadata
3. Select any field 
4. Edith the description field 
5. Go to next field 
7. description field appears in blank

**Screenshots**
![image](https://user-images.githubusercontent.com/120091217/209789156-7c8d1800-a818-4b70-a996-c3b760147c9a.png)
![image](https://user-images.githubusercontent.com/120091217/209789209-1a504e51-3a69-45b2-9c79-c157963f0c32.png)
![image](https://user-images.githubusercontent.com/120091217/209789249-4dd4d6d1-559a-4d73-8786-102be7fbcbd6.png)
![image](https://user-images.githubusercontent.com/120091217/209789275-899a7d2d-c77a-490b-a0ce-562479be86b6.png)

**Severity**
How severe an issue is this bug to you? Is this annoying,not blocking but when fixing metadata with largest fields its a bit painful

**Comment by flamber** [comment] 2022-12-28 09:36
Duplicate of #25884

**Closed by flamber** 2022-12-28 09:36 UTC
Labels: Type:Bug, .Needs Triage
