### ISSUE TITLE
disable usage of FieldValues when the cardinality of a field exceeds a reasonable maximum

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1965] opened 2016-02-18 19:44 UTC
Initial issue discussed here .. https://github.com/metabase/metabase/issues/1040

There are times when Metabase attempts to use pre-calculated FieldValues for fields that have a very large number of values and this should be avoided.  If it's known that a field has a lot of values we should discontinue any attempts to use pre-calculated FieldValues.

**Comment by camsaul** [comment] 2016-02-18 22:13
Duplicate of #1499

**Closed by camsaul** 2016-02-18 22:13 UTC
