### ISSUE TITLE
Log Action runs in audit/usage analytics

### ISSUE THREAD

**Issue by jessicaul** [metabase/metabase#49008] opened 2024-10-22 19:40 UTC
**Is your feature request related to a problem? Please describe.**
Currently, action runs are not being logged. Difficult to tell when or who executed an action. 

**Describe the solution you'd like**
I would like actions runs to be logged in the `Query Log` table in the `Usage Analytics` collection. There's already an `Action Qualified ID` field in that table. 

**How important is this feature to you?**
Important for visibility and audit purposes.

**Comment by andyhernandez** [comment] 2024-10-23 15:42
An additional nicety to the Query Log would be the ability for some sort of variable we could use to actually log the user id/name as part of the action.

```
INSERT INTO table_name (
  column1, 
  column2, 
  created_by
)
VALUES (
  value1, 
  value2, 
  {{ MB_current_user_id }}
);
```
^ some sort of global variable for the logged in user would be useful in many many contexts.  Personalized dashboards, action logging, etc.

**Comment by brunobergher** [comment] 2024-12-30 15:24
Duplicate of #33659

**Closed by brunobergher** 2024-12-30 15:24 UTC
Labels: Type:New Feature, Administration/Usage analytics, Querying/Actions
