### ISSUE TITLE
Zoom In for a table cell shows the values of the cell above, when using Group By Date Period

### ISSUE THREAD

**Issue by bakavic** [metabase/metabase#11251] opened 2019-11-01 08:18 UTC
**Describe the bug**
Selecting Zoom In/View These... on a table cell seems to provide results of the cell above. This only seems to happen for table results which used Group By.. time period.

**Logs**
No logs, seems to be a UI issue.

**To Reproduce**
1. Create a question on a table which has a date column. Group by a time period.
![Create new question group by time period](https://user-images.githubusercontent.com/1281844/68011295-ec9b5000-fcc1-11e9-87d0-94a954d6feda.png)

2. Select Zoom In on a table cell (`14` for `Q1 2017`) , taking note of the value above (`17` for `Q4 2016`)
![zoom in for 2017 Q1](https://user-images.githubusercontent.com/1281844/68011417-41d76180-fcc2-11e9-891b-eec1db04164c.png)

3. Zoomed In results show results of the table cell above (`17` for `Q4 2016`), even though the filter shows as "Created At Q1 - 2017".
![zoomed in](https://user-images.githubusercontent.com/1281844/68011468-64697a80-fcc2-11e9-9fe0-244e941a437d.png)

**Expected behavior**
The Zoom In/View These... option should show the values for the selected table cell, as opposed to the cell above.

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 78.0.3904.7
- Your operating system: OS X 10.14.6
- Your databases: MySQL
- Metabase version: v0.33.4
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

**Severity**
Slight annoying, but there is a workaround that my users know (select the cell above for the value below)

**Comment by notrom** [comment] 2019-11-04 22:57
I'm getting exactly the same thing. To me this is more than a slight annoyance, this is just plain wrong and is currently destroying all trust in the system. To me this is a bug in one of the core functions of the system. There's no work around that I'm aware of. I'd like to see this as a P1.

My setup:
- SQL Server database
- Metabase internal database: Postgres
- Metabase v0.33.4

I'm starting on the simple query builder and both the "View these" and "Zoom In" buttons are producing the wrong data, giving the data for the period before the one selected.

Here's some screen shots.

This is the output after clicking on the count bar for "Sept 2019". You can see that although the filter says September, all the data is from August.
![image](https://user-images.githubusercontent.com/4504437/68164620-32a62b80-ffc2-11e9-8689-e69f2b73d2d8.png)

Looking at the generated SQL for that we can see that the generated SQL date range is off by one.
![image](https://user-images.githubusercontent.com/4504437/68164796-aa745600-ffc2-11e9-8d69-71dae935f6ee.png)

This seems to be happening with all period types (year, month, day, hour).

I'm quite concerned about this.

**Comment by notrom** [comment] 2019-11-04 23:04
I've just tried this in the Sample Dataset and it's doing the same thing.
![image](https://user-images.githubusercontent.com/4504437/68165322-068baa00-ffc4-11e9-8852-1bc0c4504d43.png)

Doesn't matter if it's a bar chart, line graph, table. If you click a period aggregate the drilldown is wrong.

This feels like something fundamental that should have a test? Am I missing something?

**Comment by mazameli** [comment] 2019-11-04 23:11
Hmm, when I do this same thing, zooming in using drill-through in the simple query builder, I'm seeing this on `master`, which appears to be correct:

![image](https://user-images.githubusercontent.com/2223916/68165691-ecdf5980-ff14-11e9-8be6-3b4434a1e70a.png)

In general, I'm not yet able to reproduce this in master. @paulrosenzweig or @camsaul, is it likely this is something we've fixed recently around timezones?

**Comment by paulrosenzweig** [comment] 2019-11-05 21:25
@mazameli I'm not sure if it's been fixed already, but I'm guessing this will be by @camsaul's changes.

**Comment by spacepluk** [comment] 2019-12-03 09:22
some extra discussion about this [here](https://discourse.metabase.com/t/aggregations-on-individual-grouped-by-fields-and-showing-the-records-within-each-group/6754/19?u=spacepluk).

I'm also seeing this on my setup (macOS 10.14.6 app 0.33.6 with PostgreSQL 12), here's one way I can reproduce it with the sample data set:

![image](https://user-images.githubusercontent.com/824762/70037303-a08c4580-15b6-11ea-854b-edf93ea4accd.png)
![image](https://user-images.githubusercontent.com/824762/70037340-b6016f80-15b6-11ea-99f6-3dde2460d9ff.png)
![image](https://user-images.githubusercontent.com/824762/70037381-c6194f00-15b6-11ea-98de-f08503162a5c.png)

**Comment by flamber** [comment] 2019-12-03 14:34
@spacepluk 
I cannot reproduce on `master` (upcoming 0.34.0). I think this issue was fixed by #11081 (or #11280)

**Comment by mazameli** [comment] 2019-12-03 18:55
@spacepluk I followed the same steps on `master` and ended up with the following, which appears correct to me: 

![image](https://user-images.githubusercontent.com/2223916/70080468-72f5cb00-15bb-11ea-9b81-75b8f26cad0b.png)

I'm going to close this as fixed in the upcoming 0.34, which we're aiming to release next week.

**Closed by mazameli** 2019-12-03 18:55 UTC
Labels: Misc/Timezones, Priority:P1, Type:Bug

**Comment by spacepluk** [comment] 2019-12-03 19:14
thanks! I'll test again when the new version is out.

**Comment by notrom** [comment] 2019-12-15 20:08
@mazameli at this point I can't reproduce in v0.34.0-rc1 which is great news for me and my users. Looking good.

Thanks

**Comment by mazameli** [comment] 2019-12-16 17:42
@notrom That's great to hear! Thanks for chiming in.
