### ISSUE TITLE
X-axis show error infomation

### ISSUE THREAD

**Issue by lx1054331851** [metabase/metabase#17498] opened 2021-08-18 03:09 UTC
![image](https://user-images.githubusercontent.com/12423206/129830512-ba71f2c1-14ea-438b-bee8-8344a8a6a661.png)

As showed in the this image, the label should be 0, but -8.8817...e-17 shows.

metabase verison is : 0.40.2

**Comment by flamber** [comment] 2021-08-18 08:33
Duplicate of #14218

**Closed by flamber** 2021-08-18 08:33 UTC
Labels: Type:Bug, .Needs Triage
