### ISSUE TITLE
Issue adding new columns to an existing question

### ISSUE THREAD

**Issue by jabari-teampay** [metabase/metabase#27979] opened 2023-01-31 20:25 UTC
**Describe the bug**
We (Teampay) are unable to add new columns to questions while using Metabase

**Logs**
[e1cc563b-95a1-4c46-8450-f905556d7666] 2023-01-31T15:21:21-05:00 WARN metabase.query-processor.middleware.upgrade-field-literals Warning: clause [:field "Total 3 Months Prior" {:base-type :type/Float}] does not match a column in the source query. Attempting to correct this to [:field "Total 3 Months Prior" {:base-type :type/Float}]
[e1cc563b-95a1-4c46-8450-f905556d7666] 2023-01-31T15:21:24-05:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 3.1 s (20 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (1 idle, 0 queued) (118 total active threads) Queries in flight: 0 (0 queued); snowflake DB 2 connections: 0/1 (0 threads blocked)
[e1cc563b-95a1-4c46-8450-f905556d7666] 2023-01-31T15:21:26-05:00 INFO metabase.query-processor.middleware.fetch-source-query Trimming trailing comment from card with id 454
[e1cc563b-95a1-4c46-8450-f905556d7666] 2023-01-31T15:21:26-05:00 INFO metabase.query-processor.middleware.fetch-source-query Trimming trailing comment from card with id 454
[e1cc563b-95a1-4c46-8450-f905556d7666] 2023-01-31T15:21:26-05:00 WARN metabase.query-processor.middleware.upgrade-field-literals Warning: clause [:field "Total 3 Months Prior" {:base-type :type/Float}] does not match a column in the source query. Attempting to correct this to [:field "Total 3 Months Prior" {:base-type :type/Float}]
[e1cc563b-95a1-4c46-8450-f905556d7666] 2023-01-31T15:21:28-05:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 2.8 s (20 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (1 idle, 0 queued) (118 total active threads) Queries in flight: 0 (0 queued); snowflake DB 2 connections: 0/1 (0 threads blocked)

**To Reproduce**
1. Go to 'https://teampay.metabaseapp.com/question/489-current-customer-pacing-report-with-sfdc-details-duplicate'
2. Click on 'settings'
3. Try to add additional columns to the question but only a single column shows up when trying to add more

**Expected behavior**
We should be able to add columns to questions without this being a problem
**Screenshots**

**Severity**
This is a high priority since it is preventing the team from building out metrics properly
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.4.209-116.367.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-01-18",
      "tag": "v1.45.2.1",
      "branch": "release-x.45.2.x",
      "hash": "3f73d30"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Comment by ignacio-mb** [comment] 2023-09-05 19:00
Closing as dupe of https://github.com/metabase/metabase/issues/28093

**Closed by ignacio-mb** 2023-09-05 19:00 UTC
