### ISSUE TITLE
Relative dates filter uses invalid date range

### ISSUE THREAD

**Issue by rstml** [metabase/metabase#34573] opened 2023-10-11 16:45 UTC
### Describe the bug

When using "relative dates" filter option, invalid range is returned due to incorrect end date.

### To Reproduce

1. Use date range filter and select "Relative dates..." 
2. Enter: "Past 1 month"
3. Scroll down to '...' and add "Starting from..."
4. Enter: "Starting from 2 months ago"
5. Click Update filter

<img width="366" alt="Screenshot 2023-10-11 at 17 24 45" src="https://github.com/metabase/metabase/assets/589231/1f42097e-9384-4e45-ab21-e03ad871043d">

Even though on the screenshot the selected date range is shown as "Jul 1 - Jul 31", database query actually is between "Jul 1 00:00 - Aug 1 00:00".

In my case, that date field is truncated to YYYY-MM only and that causes the query to encompass all Jul and Aug.

### Expected behavior

Filter should only query "Jul 1 00:00:00 - Jul 31 23:59:59"

### Logs

This filter adds the following lines to the query:

```sql
SELECT (...) AS "source"
WHERE
  DATE_ADD('month', 2,
    DATE_TRUNC('month',"source"."billing_period")
  ) 
  BETWEEN DATE_TRUNC('month', DATE_ADD('month', -1, NOW())) AND DATE_TRUNC('month', NOW())
```

We can run a simple query against Athena to check those values and confirm that the end date is incorrect:
```sql
SELECT 
  DATE_TRUNC('month', DATE_ADD('month', -1, NOW())) AS date_from,
  DATE_TRUNC('month', NOW()) AS date_to

--Result
-- date_from: 2023-9-1, 12:00 AM
-- date_to: 2023-10-1, 12:00 AM
```

### Information about your Metabase installation

```JSON
- Queried database: AWS Athena
- Internal database: Postgres
- Metabase version: 0.73.3
- OS: Ubuntu
```

### Severity

medium

**Comment by ranquild** [comment] 2023-10-31 15:46
We call a MLv2 `formatRelativeDateRange` to format the date range now, so it's a BE bug if it still exists

**Comment by WiNloSt** [comment] 2023-11-08 11:57
Reproducible on 1.47.0 and https://github.com/metabase/metabase/pull/34851 (e546daa65437dd32bed1d91ce133c022eb5bbabb)

![Screenshot 2023-11-08 at 6 55 39 PM](https://github.com/metabase/metabase/assets/1937582/afa2aca9-c181-4500-8c4c-2c9726978d1b)
![Screenshot 2023-11-08 at 6 56 22 PM](https://github.com/metabase/metabase/assets/1937582/fd813bf9-2b40-48b9-8264-2c8be6274851)

**Comment by camsaul** [comment] 2023-11-09 22:39
This is actually an MLv1 filter bug, but the reasoning might be a little counterintuitive. It has to do with MBQL `:between` being inclusive, like SQL `BETWEEN`.

<img width="287" alt="image" src="https://github.com/metabase/metabase/assets/1455846/d700dfb9-1f8f-45ac-bcf9-606b9052f853">

generates the following MBQL

```clj
{:database 6803,
 :type :query,
 :query
 {:source-table 50919,
  :filter
  [:between
   [:+ [:field 216429 {:base-type :type/DateTimeWithLocalTZ}] [:interval 2 :month]]
   [:relative-datetime -1 :month]
   [:relative-datetime 0 :month]]}}
```

Which is not quite what the UI suggests.

The MBQL query is asking for a  `BETWEEN` filter like this:

```
month(CREATED_AT) + 2 months
BETWEEN
month(now) - 1 month 
AND 
month(now) [inclusive]
```

Simplifying the expression a bit and assuming `now = November` gives us

```
month(CREATED_AT) + 2 months
BETWEEN
month(now) - 1 month  [inclusive]
AND 
month(now) [inclusive]

=>

month(CREATED_AT)
BETWEEN
month(now) - 3 months [inclusive]
AND 
month(now) - 2 months [inclusive]

=> 

month(CREATED_AT)
BETWEEN
November - 3 months [inclusive]
AND 
November  - 2 months [inclusive]

=>

month(CREATED_AT)
BETWEEN
August [inclusive]
AND 
September [inclusive]
```

Which basically translates to

```
month(CREATED_AT) >= August
AND
month(CREATED_AT) <= September

=>

month(CREATED_AT) IN (August, September)
```

The SQL we generate is a little less optimized, but it clearly matches the MBQL:

```sql
SELECT
  *
FROM
  "PUBLIC"."ORDERS"
WHERE
  DATEADD('month', 2, "PUBLIC"."ORDERS"."CREATED_AT") 
  BETWEEN 
    DATE_TRUNC('month', DATEADD('month', -1, NOW()))
    AND 
    DATE_TRUNC('month', NOW())
LIMIT
  1048575
```

So as far as I'm concerned this is an MLv1 bug. Once filters are ported to MLv2, we can fix it there.

**Comment by camsaul** [comment] 2023-11-09 22:41
Test that I used while working on the writeup above.

Note that once MLv2 is in place we will probably want to write a proper end-to-end test that uses MLv2 to generate the query in the same way the FE would

```clj
(deftest ^:parallel relative-date-filter-test
  (testing "#34573"
    (qp.store/with-metadata-provider meta/metadata-provider
      (driver/with-driver :h2
        (let [query (lib.tu.macros/mbql-query orders
                      {:filter [:between
                                [:+ $created-at [:interval -2 :month]]
                                [:relative-datetime -1 :month]
                                [:relative-datetime 0 :month]]})]
          (is (= {:query  ["SELECT"
                           "  \"PUBLIC\".\"ORDERS\".\"ID\" AS \"ID\","
                           "  \"PUBLIC\".\"ORDERS\".\"USER_ID\" AS \"USER_ID\","
                           "  \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\","
                           "  \"PUBLIC\".\"ORDERS\".\"SUBTOTAL\" AS \"SUBTOTAL\","
                           "  \"PUBLIC\".\"ORDERS\".\"TAX\" AS \"TAX\","
                           "  \"PUBLIC\".\"ORDERS\".\"TOTAL\" AS \"TOTAL\","
                           "  \"PUBLIC\".\"ORDERS\".\"DISCOUNT\" AS \"DISCOUNT\","
                           "  \"PUBLIC\".\"ORDERS\".\"CREATED_AT\" AS \"CREATED_AT\","
                           "  \"PUBLIC\".\"ORDERS\".\"QUANTITY\" AS \"QUANTITY\""
                           "FROM"
                           "  \"PUBLIC\".\"ORDERS\""
                           "WHERE"
                           "  DATEADD("
                           "    'month',"
                           "    -2,"
                           "    CAST(\"PUBLIC\".\"ORDERS\".\"CREATED_AT\" AS datetime)"
                           "  ) BETWEEN DATE_TRUNC('month', DATEADD('month', -1, NOW()))"
                           "  AND DATE_TRUNC('month', NOW())"
                           "LIMIT"
                           "  1048575"]
                  :params nil}
                 (-> (qp/compile query)
                     (m/update-existing :query #(str/split-lines (driver/prettify-native-form :h2 %)))))))))))
```

**Comment by bshepherdson** [comment] 2024-02-15 19:49
This seems to be no repro on master. I tried this filter 
![2024-02-15-143435_976x652_scrot](https://github.com/metabase/metabase/assets/157812/a7f4601f-2958-4c81-aabd-e33022e433b8)
and it seems to correctly select only November 2023. (Today is Feb 15 2024, so two months ago is Dec 15 2023, making the 1 previous month Nov 2023.)

The UI shows that range correctly, and the returned data has only November.

I can't reproduce this issue in 48.3, 47.12, or even 1.47.0 which had this repro'd! I must be doing something wrong. I'm using the H2 built in database, but possibly the semantics of `BETWEEN` are not so standardized as one would hope?

I'll try to get Athena set up so I can attempt to repro it there.

**Comment by bshepherdson** [comment] 2024-02-15 20:00
Okay... in 1.47.0 I did `Past 1 month starting from 50 months ago` (because the old sample data loaded in our test Athena runs up to mid-2020, so I'm targeting November 2019). That correctly returns exactly the rows for November 2019, without running into December, even December 1.

The legacy MBQL looks exactly like Cam's example, and it's working correctly for me. There must be some subtlety I'm missing here.

**Comment by camsaul** [comment] 2024-02-15 20:34
This only affects `DATE` columns, see notes here https://metaboat.slack.com/archives/C04DN5VRQM6/p1708029162683819?thread_ts=1707995442.019769&cid=C04DN5VRQM6

**Comment by camsaul** [comment] 2024-05-07 04:05
After looking at this a bit further I'm 90% sure the wrong filter clause originates from

https://github.com/metabase/metabase/blob/2aa3cec610588238132afbc789da0845c7c2ec5d/frontend/src/metabase/querying/components/DatePicker/RelativeDatePicker/RelativeDatePicker.tsx

which doesn't seem to use MLv2 to create filter clauses (even worse, it's creating MBQL clauses in the React component itself)

We should update that UI to use MLv2.

**Comment by camsaul** [comment] 2024-05-07 18:35
Ok so Alex P says the code in question that is buggy is doing questionable things is here

https://github.com/metabase/metabase/blob/9887f2222dac336f58ee2ed58ac28516c224e908/frontend/src/metabase-lib/filter.ts#L359-L397

**Comment by ranquild** [comment] 2024-06-25 15:49
It seems that it can be fixed with the following expression:
```
[
  "and",
  [
    ">=",
    [
      "+",
      ["field", 41, {"base-type": "type/DateTime"}],
      ["interval", 7, "day"]
    ],
    ["relative-datetime", -30, "day"]
  ],
  [
    "<",
    [
      "+",
      ["field", 41, {"base-type": "type/DateTime"}],
      ["interval", 7, "day"]
    ],
    ["relative-datetime", 0, "day"]
  ]
]
```

The problem is, when the FE starts to generate such expressions for relative date time filters with offset, the MBQL lib doesn't recognize this pattern. It should be fixed both in MBQL lib and the FE (also MBQL lib) at the same time.

**Closed** 2024-08-01 09:12 UTC
Labels: Type:Bug, Priority:P2, Querying/MBQL, Difficulty:Hard, .Frontend, .Backend, .metabase-lib, .Team/QueryProcessor, .Team/QueryingComponents
