### ISSUE TITLE
Data options in Simple/Custom Question showing views/tables that DB user does not have permission

### ISSUE THREAD

**Issue by arjunk** [metabase/metabase#13200] opened 2020-09-02 10:21 UTC
**Describe the bug**
The Pick data drop-down in Simple and Custom Questions is not respecting the DB user boundaries and showing views that the DB user, with which Metabase database connection is created, does not have access to. This leads to a lot of noise and confusion and bad UX. When user tries to use the view for which she (rather her database connection) doesn't have access then Metabase gives a permission denied error. It should not show those views/tables in the first place.

**Logs**

**To Reproduce**
1. In your Postgres DB, have 2 DB users and set of views accessible only to each user. Let's say [User: User 1, View : view_user1; User: User 2, View: view_user2]
2. Add 1 Metabase Database each for the 2 users
3. Create a simple or Custom question using lets say User 1
4. In the 'Pick Data' dropdown you see both view_user1 and view_user2.

**Expected behavior**
The pick data drop-down should only show view_user1 and not view_user2

**Screenshots**
![image](https://user-images.githubusercontent.com/426156/91969275-775e3880-ed33-11ea-8437-f9b8490a6244.png) Screenshot 1 showing views visible in dropdown

![image](https://user-images.githubusercontent.com/426156/91969345-9361da00-ed33-11ea-8a49-ef5e6d8e8407.png) Screenshot 2 showing permission denied error on trying to use the view

**Severity**
Its not a blocker but since we have a lot of databases like this - one per tenant and lot of views per tenant/user, its a lot of noise to other users causing confusion to them. This consumes more of our resources in training and support and a bad UX for users. This hampers our ability to offer this as easily self-serviceable. 

**Additional context**
We (https://avniproject.org/) have a multi-tenant open-source data collection platform and have been using Metabase as the default reporting tool. We are using Postgres. The DB architecture we are using in single database single schema with tables having discriminator column. We use the local installation of Metabase. 
The unwanted views can also be removed by hiding the queryable tables when configuring the database but that would be a workaround. It would involve lot of repetitive work everytime a database is configured and to automate APIs are not available. Creating a separate issue for making APIs available. 
Not sure if this would be helpful and i haven't yet checked how Metabase is doing this underneath but in case its helpful : if you query pg_views it returns all views but if you query information_schema.views it respects the user boundaries. 

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_201-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_201",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.201-b09",
    "os.name": "Linux",
    "os.version": "4.9.76-3.78.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "Zulu"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.36.2",
      "date": "2020-07-31",
      "branch": "release-0.36.x",
      "hash": "13f0225"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

**Comment by flamber** [comment] 2020-09-02 10:44
Duplicate of #10139/#1654

**Closed by flamber** 2020-09-02 10:44 UTC
