### ISSUE TITLE
Using plain SQL in Filters

### ISSUE THREAD

**Issue by joelluijmes** [metabase/metabase#23378] opened 2022-06-16 10:06 UTC
**Is your feature request related to a problem? Please describe.**
I'm frustrated that I'm limited in filtering. If I could use plain SQL, I could write any condition I want. For instance, I noticed I can't even use conditional operators such as AND/OR. 

![image](https://user-images.githubusercontent.com/4273556/174045938-45ac93cd-1c6c-4a6e-9c77-390c165b521b.png)

**Describe the solution you'd like**
Allow entering plain SQL, which is just passed through. Maybe it should be tagged as an advanced feature so it might not throw off less technical users.

**Describe alternatives you've considered**
None really, I suppose the filter should be created in the underlying table then.

**How important is this feature to you?**
For me flexibility in a BI solution is really important. I like that its flexible from a user perspective (e.g., the way Metabase can join tables). But, as a more advanced user, its really limited to what and how it can calculate. 

**Additional context**
I think this strongly relates to #16873. However, I'm not sure if that also covers the use case in using SQL for filtering. Feel free to close this in favor of the previous one. At least its explicitly mentioned now 👍

**Comment by joelluijmes** [comment] 2022-06-16 10:06
What would be necessary to implement this? Maybe I can try to contribute it. I would be fine if an initial version doesn't support referring columns, i.e., it only passes through the SQL -> so it would only work with the actual column name.

**Comment by flamber** [comment] 2022-06-16 10:25
Hi @joelluijmes 
You are showing a screenshot of Custom Column, which is not the same as Custom Expressions.
You can do `AND`/`OR` on filters (Custom Expressions).
https://www.metabase.com/docs/latest/users-guide/expressions.html
![image](https://user-images.githubusercontent.com/1447303/174049443-11fe978e-de12-4e0d-b4e1-03c19e23d9b2.png)

Closing a duplicate of #16873/#15922

**Closed by flamber** 2022-06-16 10:25 UTC
Labels: Type:New Feature, .Needs Triage
