### ISSUE TITLE
Add a `/admin/settings/manage_alerts` for Admins to manage alerts

### ISSUE THREAD

**Issue by johanjvrens** [metabase/metabase#12428] opened 2020-04-30 08:02 UTC
**Is your feature request related to a problem? Please describe.**
Some of our company data is sensitive and as people change roles and need access to different questions and report alerts, I need a central place to see all active alerts in one spot as this is really hard to manage on a per question-level when you have 250+ questions as we do.

**Describe the solution you'd like**
It would be really awesome if you can add an option under Admin similar to
Public Sharing - /admin/settings/public_sharing
Maby something like 
Manage Alerts - /admin/settings/manage_alerts
which contains a summary of all questions with alerts set.

**Describe alternatives you've considered**
Currently, as an Admin I have to routinely go through each question, see if it has alerts and look at each recipient and delete the email addresses that should not have access anymore as they have left the company, or change roles, etc. 

**How important is this feature to you?**
I think this is a great time saver and would really be helpful. 

**Additional context**

**Comment by flamber** [comment] 2020-04-30 08:44
Looks like a duplicate of #11203 - upvote by clicking :+1: on the first post

**Closed by flamber** 2020-04-30 08:44 UTC
Labels: .Duplicate
