### ISSUE TITLE
Hide Column Headers in the Table Visualization

### ISSUE THREAD

**Issue by zusamann** [metabase/metabase#2878] opened 2016-07-04 14:00 UTC
A lot of our data models have a high number of column headers and we'd like to hide one or more than one while creating a table visualization, simply because they'd be redundant while consumption. Is there a way to go about achieving it?

**Comment by salsakran** [comment] 2016-07-05 21:37
we're currently working on this! 
Dupe of #1445

**Closed by salsakran** 2016-07-05 21:37 UTC
