### ISSUE TITLE
Questions for saved questions on permissions admin panel

### ISSUE THREAD

**Issue by cyhhao** [metabase/metabase#10092] opened 2019-06-05 10:59 UTC
<img width="1055" alt="Snipaste_2019-06-05_18-13-05" src="https://user-images.githubusercontent.com/5381613/58951501-e4e38800-87c3-11e9-87ef-951410cdfa42.png">

It’s weired that on permissions admin panel, sometimes saved questions isn’t showed up in the permissions list. So we have trouble giving access to users. Could you show saved questions in the permissions section?  

Version  0.32.8

**Comment by flamber** [comment] 2019-06-05 16:43
Hi @cyhhao 
Sounds like a duplicate of #5610

**Comment by mazameli** [comment] 2019-06-06 21:08
@cyhhao Currently, whether users can use specific Questions as a data source for a new question is determined by the Collection permissions they have for each Question. For now, the fact that `Saved Questions` is showing up as a database in the Data Permissions section is effectively a bug.

[Read more about how you can use Collection permissions to grant or revoke access to specific questions](https://metabase.com/docs/latest/administration-guide/06-collections.html).

**Closed** 2019-06-06 21:08 UTC
Labels: Duplicate
