### ISSUE TITLE
Converting a GUI query with a "starts/ends with" or "contains" filter to SQL doesn't work

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4232] opened 2017-01-25 19:50 UTC
If you have a gui query that includes a "starts with," "ends with," or "contains" filter, when you convert it to SQL, it generates a clause like this: `WHERE ("PRODUCTS__via__PRODUCT_ID"."TITLE" like ?)`. The value input into the filter gets replaced with a question mark. Running the SQL query returns this error: `Parameter "#1" is not set`

![screen shot 2017-01-25 at 11 46 28 am](https://cloud.githubusercontent.com/assets/2223916/22306380/f4588c30-e2f3-11e6-88ac-5b23d1144ec2.png)

![screen shot 2017-01-25 at 11 46 35 am](https://cloud.githubusercontent.com/assets/2223916/22306390/fa3a8054-e2f3-11e6-93df-1d6f08c28a26.png)

**Comment by tlrobinson** [comment] 2017-01-25 19:59
Duplicate of #3549

**Closed by tlrobinson** 2017-01-25 19:59 UTC
Labels: Bug, Query Builder, Query Builder/Native
