### ISSUE TITLE
Feature Request: Row Bar Charts vs Column Bar Charts

### ISSUE THREAD

**Issue by arabold** [metabase/metabase#3708] opened 2016-11-01 15:58 UTC
To my understanding Metabase supports only column charts; that is bar charts with vertical bars (= columns). For datasets with many values it sometimes might be advantageous to display horizontal bars instead. Here's a screenshot of my data:

![image](https://cloud.githubusercontent.com/assets/1548229/19875313/07f947ec-9f89-11e6-8f22-796ca482c1d4.png)

As you can see this isn't very readable as a lot of columns are missing their label and the more values I add, the narrower and less readable the bars get as it tries to fit all values into the available horizontal space. It would be better to render the values in a vertical list (with horizontal bars) so the user scrolls vertically like through a table.

**Comment by camsaul** [comment] 2016-11-01 18:40
I think that's just called a Horizontal Bar Chart. We don't call vertical ones "Row Charts" 😉

**Comment by tlrobinson** [comment] 2016-11-01 20:54
Actually, dc.js does call them row charts https://dc-js.github.io/dc.js/examples/row.html

**Comment by gilhs** [comment] 2016-12-14 10:28
This would be very helpful for us as well!

**Comment by tlrobinson** [comment] 2017-02-03 20:07
Closing as dupe of #2167

**Closed by tlrobinson** 2017-02-03 20:07 UTC
Labels: Proposal, Visualization, Visualization/Chart Settings
