### ISSUE TITLE
It is impossible to turn off all table's columns

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#12135] opened 2020-03-16 15:57 UTC
**Describe the bug**
In the question editor, I turn off table's columns one by one, but as soon as I turn off the last column, all columns get turned on automatically.

**To Reproduce**
1. Start a custom question.
2. Turn off selection of all columns from the table.
3. Notice that all columns get turned back on automatically at the moment you turn off the last column.

**Expected behavior**
The columns should stay turned off.

**Information about your Metabase Installation:**
`{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1; Windows for Workgroups 3.11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "13.0.2",
    "java.vm.name": "Eclipse OpenJ9 VM",
    "java.vm.version": "openj9-0.18.0",
    "os.name": "Linux",
    "os.version": "4.15.0-66-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.29"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-02-25",
      "tag": "v0.34.3",
      "branch": "release-0.34.x",
      "hash": "1a83edb"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}`

**Severity**
Minor.

**Additional context**
Same happens when I turn the columns off in the table view's settings. Use case is joining another table and only showing data from there.

**Comment by flamber** [comment] 2020-03-16 16:06
Duplicate of #10460

**Closed by flamber** 2020-03-16 16:06 UTC
Labels: .Duplicate
