### ISSUE TITLE
Non-optimal conversion of custom questions to queries for SQL Server DB's

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#9934] opened 2019-05-09 18:31 UTC
Custom question on SQL Server DB: Average of units grouped by month (not "month of year")

Metabase converted this to 
```SQL
SELECT CAST(format("dbo"."Sales"."SaleDate", 'yyyy-MM-01') AS datetime) AS "SaleDate", avg("dbo"."Sales"."Units") AS "avg"
FROM "dbo"."Sales"
GROUP BY CAST(format("dbo"."Sales"."SaleDate", 'yyyy-MM-01') AS datetime)
ORDER BY CAST(format("dbo"."Sales"."SaleDate", 'yyyy-MM-01') AS datetime) ASC
```
For a table with 300 million rows this didn't return results after 30 minutes. I gave up. I ran the following query in the SQL server management studio, which basically answers the same question:
```SQL
select year(saledate), month(saledate), avg(units) from sales
group by year(saledate), month(saledate)
order by year(saledate), month(saledate)
```
It returned the results in 28 seconds.

So the conversion of the custom questions involving these types of groupings to SQL queries for SQL Server db's is not optimal. 

- Metabase version: 0.31.2
- Metabase internal database: Postgres

**Comment by flamber** [comment] 2019-05-09 18:41
Hi @vvaezian 
Looks like a duplicate of #4043 - it might be fixed by PR #9860

**Comment by vvaezian** [comment] 2019-05-09 19:10
Hi @flamber, thanks for the reply.

Regarding #4043, I think the problem I mentioned is specific to SQL Server as Postgres already uses `date_trunc` for the type of question I mentioned (haven't checked MySQL and others yet).

I skimmed through #9860, but didn't see how that can solve the problem I mentioned.

**Comment by flamber** [comment] 2019-05-09 22:04
From what I can see, it seems like multiple different drivers are mentioned in #4043, so that's why I thought it might be an all-in-one issue.

For reference, just did a quick check on my test bench with 0.32.6:
```SQL
#H2
parsedatetime(formatdatetime("PUBLIC"."ORDERS"."CREATED_AT", 'yyyyMM'), 'yyyyMM')

#MySQL (actually MariaDB)
str_to_date(concat(date_format(`ORDERS`.`CREATED_AT`, '%Y-%m'), '-01'), '%Y-%m-%d')

#Postgres
date_trunc('month', CAST("SampleData"."orders"."created_at" AS timestamp))

#SQLite
date("orders"."created_at", 'start of month')
```

@nikita2206 Sorry to ping you, but I'm unsure if #9860 will also fix date index usage on MSSQL?

**Comment by nikita2206** [comment] 2019-05-10 09:24
@flamber I don’t think #9860 will fix this particular issue, it only fixes inefficiencies in the `WHERE` clause I believe. I think what @vvaezian suggests could be implemented in a driver but I’m not sure if driver can yield more than one grouping column per one MBQL’s grouping column so that might require a change in Metabase and not only in the MSSQL driver.

**Comment by nikita2206** [comment] 2019-05-10 12:27
@vvaezian this optimization shouldn't be too hard to implement but it will require a change in all [sql] drivers which might be a sort of too big of a change to make in the point-release (or it might not be).  

You can look into fixing it in your fork for the start and then decide if you want to persuade maintainers to merge those changes to upstream.  

Places to look for:
 - [Converts every MBQL field in the breakout to SQL's GROUP BY](https://github.com/metabase/metabase/blob/b9cf7b736ac1f554a100ff0853c7836c1637096c/src/metabase/driver/sql/query_processor.clj#L370) - this needs to be changed to support multiple fields: you'll be getting something like `[:datetime-field [:field-id 123] :month-of-year]` and will need to convert this into your proposed `year(field), month(field)`
- You'll also need to change the `ORDER BY` handling - this is happening [here](https://github.com/metabase/metabase/blob/b9cf7b736ac1f554a100ff0853c7836c1637096c/src/metabase/driver/sql/query_processor.clj#L476)

**Comment by camsaul** [comment] 2021-02-17 03:31
We've changed the SQL that gets generated in this situation in #9398 and #10561. The SQL generated in 0.33.0+ for the query in question would look something like:

```sql
SELECT datefromparts(year(dbo.Sales.SaleDate), month(dbo.Sales.SaleDate), 1) AS SaleDate, avg(dbo.Sales.Units) as avg
FROM dbo.Sales
GROUP BY datefromparts(year(dbo.Sales.SaleDate), month(dbo.Sales.SaleDate), 1) 
ORDER BY datefromparts(year(dbo.Sales.SaleDate), month(dbo.Sales.SaleDate), 1) ASC
```

I'm looking at optimizing it a bit more, to something like

```sql
SELECT datefromparts(source.SaleDate__year, source.SaleDate__month, 1) AS SaleDate, source.avg
FROM (
    SELECT year(dbo.Sales.SaleDate) AS SaleDate__year,
      month(dbo.Sales.SaleDate) AS source.SaleDate__month,
      avg(dbo.Sales.Units) as avg
    FROM dbo.Sales
    GROUP BY year(dbo.Sales.SaleDate), month(dbo.Sales.SaleDate)
    ORDER BY year(dbo.Sales.SaleDate) ASC, month(dbo.Sales.SaleDate) ASC
) source
```

That's a little easier said than done however

**Closed** 2021-03-11 18:13 UTC
Labels: Database/SQLServer, Type:Performance
