### ISSUE TITLE
describe-table calls with Postgres do not respect ssh tunneling

### ISSUE THREAD

**Issue by lionelbarrow** [metabase/metabase#9278] opened 2019-01-16 22:51 UTC
### describe-table calls with Postgres do not respect ssh tunneling

- Your browser and the version: N/A
- Your operating system: Observed on OSX 10.13 and Amazon Linux
- Your databases: Postgres 9.6.6
- Metabase version: 0.31.1 and 0.31.2
- Metabase hosting environment: Mac App, my OSX development environment, Heroku
- Metabase internal database: H2 and Postgres

Hey there!

I'm running Metabase on Heroku and connecting to my Postgres 9.6 database (running on RDS) through an SSH tunnel. Many features in Metabase work correctly, but features that require Metabase to understand my schema do not. I documented a few symptoms on [this Discourse issue](http://discourse.metabase.com/t/postgres-syntax-error-when-asking-a-new-question/5208/5) but the tl; dr is that the 'Sync Fields' button in the Admin panel fails on a connection issue, which then leads to query syntax errors in the `/automagic-dashboards` route and other features.

I believe the root cause is that [this code](https://github.com/metabase/metabase/blob/c809b91d07b7c7e84da7a31f397c95d60dff6c25/src/metabase/driver/postgres.clj#L82-L98) in the Postgres driver executes a raw `jdbc/query` call without the tunnel context, although I don't know enough Clojure to quite understand the specifics.

To reproduce the issue:

* Create a Postgres database somewhere. I recommend RDS since you can easily set up an IP blocklist to prohibit direct connection from your dev environment.
* Configure Metabase to communicate with the database via an SSH tunnel. Importantly, make sure that the SSH tunnel is *required*. If a direct connection will succeed, the bug will not manifest.
* Notice that Metabase succeeds in connecting to the database (and you can even build questions with SQL), but many introspection-related features will not work. For example, try to build a custom query.
* Remove the IP blocklist and re-sync the fields in the admin panel. Observe that introspection-related features now work again - this is because the `describe-tables` call is now able to succeed.

I'm going to try to open a PR to fix this but I have no Clojure experience so don't wait up for me if you think this is a quick fix!

Lionel

**Comment by stevenvdr** [comment] 2019-01-28 10:32
I'm getting a similar issue (wondering if the root cause is the same).

Behaviour is exactly the same, so syncing the fields does not work, but writing a custom query does. However I get a password failed error. (The password is correct, as I can do custom SQL queries and using `psql` using that same password works.)

```
Jan 28 11:24:34 metabase metabase[20205]: Jan 28, 2019 11:24:34 AM org.postgresql.core.v3.ConnectionFactoryImpl log
Jan 28 11:24:34 metabase metabase[20205]: WARNING: SQLException occurred while connecting to localhost:5432
Jan 28 11:24:34 metabase metabase[20205]: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "metabase"
```

[stacktrace.txt](https://github.com/metabase/metabase/files/2802489/stacktrace.txt)

**Comment by stevenvdr** [comment] 2019-01-28 11:07
@camsaul Is this something that might have been introduced in https://github.com/metabase/metabase/pull/8931 ? We started having this issue when migrating to v0.31, We didn't have this issue in v0.30.4.

**Comment by iqbalaydrus** [comment] 2020-01-17 10:29
I'm also getting this issue while trying to sync db schema. Table scan seems ok, but field scan doesn't.

`01-17 17:21:36 INFO sync.util :: STARTING: Sync metadata for postgres Database 70 'NMS Paring'
01-17 17:21:36 INFO sync.util :: STARTING: step 'sync-timezone' for postgres Database 70 'NMS Paring'
01-17 17:21:36 INFO util.ssh :: creating ssh tunnel metabase@139.162.60.78:22 -L 43281:127.0.0.1:6432
01-17 17:21:37 WARN sync-metadata.sync-timezone :: Error syncing database timezone
java.lang.Exception: Unable to parse date string '2020-01-17 17:21:37.031 +07' for database engine 'postgres'
01-17 17:21:37 INFO sync.util :: FINISHED: step 'sync-timezone' for postgres Database 70 'NMS Paring' (484.8 ms)
01-17 17:21:37 INFO sync.util :: STARTING: step 'sync-tables' for postgres Database 70 'NMS Paring'
01-17 17:21:37 INFO sync.util :: FINISHED: step 'sync-tables' for postgres Database 70 'NMS Paring' (56.9 ms)
01-17 17:21:37 INFO sync.util :: STARTING: step 'sync-fields' for postgres Database 70 'NMS Paring'
01-17 17:21:37 ERROR sync.util :: Error syncing Fields for Table 'Table 1,674 '_timescaledb_internal._hyper_3_149_chunk'': Connection to 127.0.0.1:6432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
01-17 17:21:37 ERROR sync.util :: Error running sync step: Output of sync-fields-for-table! does not match schema: 
01-17 17:21:37 INFO sync.util :: FINISHED: Sync metadata for postgres Database 70 'NMS Paring' (783.5 ms)
01-17 17:21:37 INFO sync.util :: STARTING: Analyze data for postgres Database 70 'NMS Paring'
01-17 17:21:37 INFO sync.util :: STARTING: step 'fingerprint-fields' for postgres Database 70 'NMS Paring'
01-17 17:21:37 INFO sync.analyze :: fingerprint-fields Analyzed [*****·············································] 😢   10% Table 1,458 '_timescaledb_internal._hyper_6_99_chunk'
01-17 17:21:37 INFO sync.analyze :: fingerprint-fields Analyzed [**********········································] 😞   20% Table 1,519 '_timescaledb_internal._hyper_4_27_chunk'
01-17 17:21:37 INFO sync.analyze :: fingerprint-fields Analyzed [***************···································] 😕   30% Table 1,608 '_timescaledb_internal._hyper_2_83_chunk'
01-17 17:21:37 INFO sync.util :: FINISHED: step 'fingerprint-fields' for postgres Database 70 'NMS Paring' (560.0 ms)
01-17 17:21:37 INFO sync.util :: STARTING: step 'classify-fields' for postgres Database 70 'NMS Paring'
01-17 17:21:37 INFO sync.analyze :: classify-fields Analyzed [********************······························] 😐   40% Table 1,574 '_timescaledb_internal._hyper_3_6_chunk'
01-17 17:21:38 INFO sync.analyze :: classify-fields Analyzed [*************************·························] 😬   50% Table 1,590 'timescaledb_information.continuous_aggregates'
01-17 17:21:38 INFO sync.analyze :: classify-fields Analyzed [******************************····················] 😌   60% Table 1,638 '_timescaledb_internal._hyper_7_69_chunk'
01-17 17:21:38 INFO sync.util :: FINISHED: step 'classify-fields' for postgres Database 70 'NMS Paring' (349.1 ms)
01-17 17:21:38 INFO sync.util :: STARTING: step 'classify-tables' for postgres Database 70 'NMS Paring'
01-17 17:21:38 INFO sync.analyze :: classify-tables Analyzed [***********************************···············] 😏   70% Table 1,488 'public.group_availability'
01-17 17:21:38 INFO sync.analyze :: classify-tables Analyzed [****************************************··········] 😊   80% Table 1,482 '_timescaledb_internal._hyper_1_121_chunk'
01-17 17:21:38 INFO sync.analyze :: classify-tables Analyzed [*********************************************·····] 😍   90% Table 1,543 '_timescaledb_internal._hyper_5_40_chunk'
01-17 17:21:38 INFO sync.util :: FINISHED: step 'classify-tables' for postgres Database 70 'NMS Paring' (376.4 ms)
01-17 17:21:38 INFO sync.util :: FINISHED: Analyze data for postgres Database 70 'NMS Paring' (1.3 s)`

**Comment by iqbalaydrus** [comment] 2020-01-17 10:32
I'm also getting this issue while trying to sync db schema. Table scan seems ok, but field scan doesn't.

```01-17 17:21:36 INFO sync.util :: STARTING: Sync metadata for postgres Database 70 'NMS Paring'
01-17 17:21:36 INFO sync.util :: STARTING: step 'sync-timezone' for postgres Database 70 'NMS Paring'
01-17 17:21:36 INFO util.ssh :: creating ssh tunnel xx@xxx:22 -L 43281:127.0.0.1:6432
01-17 17:21:37 WARN sync-metadata.sync-timezone :: Error syncing database timezone
java.lang.Exception: Unable to parse date string '2020-01-17 17:21:37.031 +07' for database engine 'postgres'
01-17 17:21:37 INFO sync.util :: FINISHED: step 'sync-timezone' for postgres Database 70 'NMS Paring' (484.8 ms)
01-17 17:21:37 INFO sync.util :: STARTING: step 'sync-tables' for postgres Database 70 'NMS Paring'
01-17 17:21:37 INFO sync.util :: FINISHED: step 'sync-tables' for postgres Database 70 'NMS Paring' (56.9 ms)
01-17 17:21:37 INFO sync.util :: STARTING: step 'sync-fields' for postgres Database 70 'NMS Paring'
01-17 17:21:37 ERROR sync.util :: Error syncing Fields for Table 'Table 1,674 '_timescaledb_internal._hyper_3_149_chunk'': Connection to 127.0.0.1:6432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
01-17 17:21:37 ERROR sync.util :: Error running sync step: Output of sync-fields-for-table! does not match schema: 
01-17 17:21:37 INFO sync.util :: FINISHED: Sync metadata for postgres Database 70 'NMS Paring' (783.5 ms)
01-17 17:21:37 INFO sync.util :: STARTING: Analyze data for postgres Database 70 'NMS Paring'
01-17 17:21:37 INFO sync.util :: STARTING: step 'fingerprint-fields' for postgres Database 70 'NMS Paring'
01-17 17:21:37 INFO sync.analyze :: fingerprint-fields Analyzed [*****·············································] 😢   10% Table 1,458 '_timescaledb_internal._hyper_6_99_chunk'
01-17 17:21:37 INFO sync.analyze :: fingerprint-fields Analyzed [**********········································] 😞   20% Table 1,519 '_timescaledb_internal._hyper_4_27_chunk'
01-17 17:21:37 INFO sync.analyze :: fingerprint-fields Analyzed [***************···································] 😕   30% Table 1,608 '_timescaledb_internal._hyper_2_83_chunk'
01-17 17:21:37 INFO sync.util :: FINISHED: step 'fingerprint-fields' for postgres Database 70 'NMS Paring' (560.0 ms)
01-17 17:21:37 INFO sync.util :: STARTING: step 'classify-fields' for postgres Database 70 'NMS Paring'
01-17 17:21:37 INFO sync.analyze :: classify-fields Analyzed [********************······························] 😐   40% Table 1,574 '_timescaledb_internal._hyper_3_6_chunk'
01-17 17:21:38 INFO sync.analyze :: classify-fields Analyzed [*************************·························] 😬   50% Table 1,590 'timescaledb_information.continuous_aggregates'
01-17 17:21:38 INFO sync.analyze :: classify-fields Analyzed [******************************····················] 😌   60% Table 1,638 '_timescaledb_internal._hyper_7_69_chunk'
01-17 17:21:38 INFO sync.util :: FINISHED: step 'classify-fields' for postgres Database 70 'NMS Paring' (349.1 ms)
01-17 17:21:38 INFO sync.util :: STARTING: step 'classify-tables' for postgres Database 70 'NMS Paring'
01-17 17:21:38 INFO sync.analyze :: classify-tables Analyzed [***********************************···············] 😏   70% Table 1,488 'public.group_availability'
01-17 17:21:38 INFO sync.analyze :: classify-tables Analyzed [****************************************··········] 😊   80% Table 1,482 '_timescaledb_internal._hyper_1_121_chunk'
01-17 17:21:38 INFO sync.analyze :: classify-tables Analyzed [*********************************************·····] 😍   90% Table 1,543 '_timescaledb_internal._hyper_5_40_chunk'
01-17 17:21:38 INFO sync.util :: FINISHED: step 'classify-tables' for postgres Database 70 'NMS Paring' (376.4 ms)
01-17 17:21:38 INFO sync.util :: FINISHED: Analyze data for postgres Database 70 'NMS Paring' (1.3 s)```

**Comment by flamber** [comment] 2020-06-04 13:40
This is actually a duplicate of #8396 - upvote by clicking :+1: on the first post
Leaving this open, since it's well documented :heart:

**Comment by robdaemon** [comment] 2020-07-08 21:33
This is directly related to #10081 also

**Comment by opsydev** [comment] 2020-07-10 00:37
Ran into this issue today. It's also very hard to debug as it looks like everything fine based on the logs and even going to view the database schema as all the tables show up. But you get `Distinct, non-empty sequence of Field clauses` when trying to browse the data.

Based on what I have read so far this makes using SSH tunneling completely broken for postgres databases, is that correct? Or is there a workaround?

**Comment by flamber** [comment] 2020-07-10 09:01
@opsydev The workaround is to setup a tunnel manually and not using the built-in Metabase tunnel:
https://www.metabase.com/docs/latest/administration-guide/01-managing-databases.html#what-if-the-built-in-ssh-tunnels-dont-fit-my-needs

**Comment by opsydev** [comment] 2020-07-12 00:18
Thanks for the info @flamber, but running it in docker and having multiple databases to connect to that approach isn't very practical. For now I have defaulted to publicly listening for connections but limiting it to one user.

Hoping that this is resolved soon.

**Comment by camsaul** [comment] 2020-07-16 20:49
Duplicate of #8396.

**Comment by camsaul** [comment] 2020-07-16 20:50
Duplicate of #8396

**Closed by camsaul** 2020-07-16 20:49 UTC
Labels: Administration/Metadata & Sync, Database/Postgres, Priority:P2, Type:Bug
