### ISSUE TITLE
TypeError: Cannot read properties of null (reading toLowerCase)

### ISSUE THREAD

**Issue by micael95** [metabase/metabase#30402] opened 2023-04-26 20:40 UTC
### Describe the bug

Hello, When I set  filter field, I got an erro in react dom

![Screenshot 2023-04-26 at 08 58 43](https://user-images.githubusercontent.com/39862092/234695975-e700d67f-88be-4296-94a7-e6bc612c20f5.png)
![Screenshot 2023-04-26 at 08 59 28](https://user-images.githubusercontent.com/39862092/234695982-5375a1bb-196b-4036-b254-c9a66ab62f60.png)
![Screenshot 2023-04-26 at 09 01 18](https://user-images.githubusercontent.com/39862092/234695983-9df178ef-accf-4e10-a46b-298b4b07ea3f.png)
![Screenshot 2023-04-26 at 09 00 56](https://user-images.githubusercontent.com/39862092/234695985-f063830d-4f1f-437b-a49d-c411445e7447.png)
![Screenshot 2023-04-26 at 09 00 19](https://user-images.githubusercontent.com/39862092/234695990-817ebac4-83a4-481f-a9ef-84a2fa5646bd.png)

### To Reproduce

-  Create a question with native SQL
-  Set a field filter
-  Got an error 

### Information about your Metabase installation

```JSON
- Latest Chrome version
- Metabase v0.46.1
- MySQL 8.0
- Docker environment
- Internal MySQL Database
```

### Severity

medium

**Comment by paoliniluis** [comment] 2023-04-26 23:43
This is a duplicate of https://github.com/metabase/metabase/issues/29786

**Closed by paoliniluis** 2023-04-26 23:43 UTC
Labels: Type:Bug, .Needs Triage
