### ISSUE TITLE
WARN models.card :: Card nil is missing its read_permissions. Calculating them now...

### ISSUE THREAD

**Issue by JBrame** [metabase/metabase#7211] opened 2018-03-27 11:35 UTC
After upgrading to 0.28.3 I'm getting the following warning several times when looking through Pulses:

03-27 12:32:39 WARN models.card :: Card nil is missing its read_permissions. Calculating them now...
03-27 12:32:39 WARN models.card :: Card nil is missing its read_permissions. Calculating them now...
03-27 12:32:39 WARN models.card :: Card nil is missing its read_permissions. Calculating them now...
03-27 12:32:39 WARN models.card :: Card nil is missing its read_permissions. Calculating them now...
03-27 12:32:39 WARN models.card :: Card nil is missing its read_permissions. Calculating them now...
03-27 12:32:39 WARN models.card :: Card nil is missing its read_permissions. Calculating them now...

Nothing is obviously not working, other than the issue I've already raised (https://github.com/metabase/metabase/issues/7210). Worth noting that I tried to downgrade to 0.27.2 after the issue above then back to 0.28.3 after getting the Pulse issue. Could that have caused it, is there an easy fix?

**Comment by Siim** [comment] 2018-03-27 23:26
I have noticed that the calculation results an empty `read_permissions` field in the `report_card` table. And this causes other groups to see the dashboards that they have no access to.

So the quick SQL level fix I used was 

```sql
UPDATE report_card 
SET 
    read_permissions=concat('["/db/',database_id,'/schema/public/table/', table_id,'/"]') 
WHERE 
    read_permissions='[]' 
    AND table_id IS NOT NULL
```

This fixed the permissions, I'm not sure, for how long does the correct permissions last.

**Comment by VikramTiwari** [comment] 2018-03-27 23:48
The correct permissions will last until an edit is made to the question. During that save process, the permissions will be re-calculated (hopefully correct) and update that row. This should have been solved by 0.28.3 but seems like there are still some questions which are not. @salsakran

**Comment by TheCondorman** [comment] 2018-03-28 10:12
Looks like I could have a bigger issue with my DB...
![image](https://user-images.githubusercontent.com/6168847/38022945-db8fbcca-3278-11e8-9d22-e9ea3dc2adf1.png)

**Comment by jornh** [comment] 2018-03-28 13:05
@TheCondorman what connection string did you use to connect from H2? 

I've fallen into this myself: use `<somepath>/metabase.db` *NOT* what you might think the full filename `<somepath>/metabase.db.mv.db`!

**Comment by TheCondorman** [comment] 2018-03-28 14:50
This is path that I used:

jdbc:h2:~/Users/[USER]/metabase.db.mv.db

**Comment by TheCondorman** [comment] 2018-03-28 14:53
I was actually using `metabase.db.mv.db` but the same issue when using `metabase.db.mv`

![image](https://user-images.githubusercontent.com/6168847/38037187-3682d564-32a0-11e8-83c8-40d7617ac471.png)

**Comment by jornh** [comment] 2018-03-28 14:54
Get rid of `.mv` as well 😄

**Comment by TheCondorman** [comment] 2018-03-28 14:55
That was just a typo... updated the comment

**Comment by jornh** [comment] 2018-03-28 16:05
Ah OK 👍 typo's are common mistaeks

I just did this on Windows in both Powershell and Cmd:

```
C:\Hub> java -jar .\h2-1.4.196.jar -url "jdbc:h2:file:C:/Hub/metabase.db;IFEXISTS=TRUE"
``` 
Obviously with both the H2 .jar and *a copy* of a `metabase.db.mv.db` in `C:\Hub` (from your redacted screenshots it seems like you left the `~` in your JDBC URL - and that makes the path start with a pointer to your HOME directory as far as I know)

This forum post: [Migrate from H2 to PostgreSQL](http://discourse.metabase.com/t/migrate-from-h2-to-postgresql/597/11?u=jornh) had a tip on adding `;IFEXISTS=TRUE` - to make sure you've got hold of the right URL

As a result I get:
![h2 console - google chrome_2](https://user-images.githubusercontent.com/766423/38041554-490c9cee-32b2-11e8-8de5-a52e94d0703d.jpg)

**Comment by TheCondorman** [comment] 2018-03-28 19:56
Ok, so adding `;IFEXISTS=TRUE` to the connection gets me in where I needed (thanks for that!) but the issue is now that all instances that have `read_permissions = '[]'` have `null` in the table_id. However I see the `source_table` in the `DATASET_QUERY`. Is it a question of extracting that and inserting it into the concat statement?

**Comment by camsaul** [comment] 2020-05-19 19:38
Closing as no longer relevant since Card read permissions are inherited from their parent Collection now (we made this change in 0.30.0 I think)

**Closed by camsaul** 2020-05-19 19:38 UTC
Labels: Administration/Permissions, Type:Performance, Type:Question
