### ISSUE TITLE
BigQuery BigNumeric breaks visualisations

### ISSUE THREAD

**Issue by carstenkadmos** [metabase/metabase#25505] opened 2022-09-20 11:51 UTC
**Describe the bug**
When aggregating over tables with the BQ field type BigNumeric the visualisation are bugged. The scaling of the axis does not work. The bars have the wrong size. The label format is immutable and preceded by a 0. The table itself looks fine, only the visualisation is impacted.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Create a table in BigQuery with the type BigNumeric. 
2. Fill the table with dummy data
3. In Metabase query the table and summarise values in e.g. a SUM function
4. Visualise the results in a any chart type.
5. See error. The scaling will not work. The number formatting will not work.

**Expected behavior**
It is expected that the visualisation labels can be formatted and the axis scaling works properly.

**Screenshots**
<img width="1371" alt="Screenshot 2022-09-20 at 11 22 44" src="https://user-images.githubusercontent.com/113892067/191249145-bcd9d9b7-ac6f-4ace-8c7f-f7a460bd1932.png">

<img width="1917" alt="Screenshot 2022-09-20 at 11 22 36" src="https://user-images.githubusercontent.com/113892067/191249161-d69e2e08-8c1f-493e-99b4-97d7806b8b15.png">

<img width="923" alt="Screenshot 2022-09-20 at 11 21 10" src="https://user-images.githubusercontent.com/113892067/191249242-c02bf7d4-4928-4845-8a69-6b8c4d7a7fa9.png">

<img width="932" alt="Screenshot 2022-09-20 at 11 21 40" src="https://user-images.githubusercontent.com/113892067/191249261-b9f31387-6d0b-460c-8426-9a98d9659150.png">

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "ANSI_X3.4-1968",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8-post-Debian-1deb10u1",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8-post-Debian-1deb10u1",
    "os.name": "Linux",
    "os.version": "5.4.188+",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.4.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-09-02",
      "tag": "v0.44.3",
      "branch": "release-x.44.x",
      "hash": "7d50282"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Further Info**
Card Info:
{
description: null,
archived: false,
collection_position: null,
table_id: 115,
result_metadata: [
{
description: null,
semantic_type: null,
table_id: 115,
coercion_strategy: null,
unit: "day",
name: "date",
settings: null,
source: "breakout",
field_ref: [
"field",
2021,
{
temporal-unit: "day"
}
],
effective_type: "type/Date",
nfc_path: null,
parent_id: null,
id: 2021,
visibility_type: "normal",
display_name: "Date",
fingerprint: {
global: {
distinct-count: 5,
nil%: 0
},
type: {
type/DateTime: {
earliest: "2000-01-01T00:00:00Z",
latest: "2000-01-05T00:00:00Z"
}
}
},
base_type: "type/Date"
},
{
base_type: "type/Decimal",
semantic_type: null,
settings: null,
name: "sum",
display_name: "Sum of Value",
source: "aggregation",
field_ref: [
"aggregation",
0
]
}
],
creator: {
email: "xx@xx.xx",
first_name: "xx ",
last_login: "2022-09-14T12:43:01.679387Z",
is_qbnewb: false,
is_superuser: true,
id: 20,
last_name: "xx",
date_joined: "2022-09-02T08:41:55.064013Z",
common_name: "xx  xx"
},
can_write: true,
database_id: 3,
enable_embedding: false,
collection_id: 37,
query_type: "query",
name: "Test Bug Bignumerics",
last_query_start: null,
dashboard_count: 0,
average_query_time: null,
creator_id: 20,
moderation_reviews: [ ],
updated_at: "2022-09-20T09:27:35.832537Z",
made_public_by_id: null,
embedding_params: null,
cache_ttl: null,
dataset_query: {
database: 3,
query: {
source-table: 115,
aggregation: [
[
"sum",
[
"field",
2022,
null
]
]
],
breakout: [
[
"field",
2021,
{
temporal-unit: "day"
}
]
]
},
type: "query"
},
id: 223,
parameter_mappings: [ ],
display: "line",
entity_id: "BSE00kIdzGSMAfntEL8WB",
collection_preview: true,
last-edit-info: {
id: 20,
email: "xx@xx.xx",
first_name: "xx ",
last_name: "xx",
timestamp: "2022-09-20T09:27:35.848959Z"
},
visualization_settings: {
graph.show_values: true,
graph.dimensions: [
"date"
],
graph.metrics: [
"sum"
]
},
collection: {
authority_level: null,
description: null,
archived: false,
slug: "xxpersonal_collection",
color: "#31698A",
name: "xxPersonal Collection",
personal_owner_id: 20,
id: 37,
entity_id: "JxWdvaPIjp3tqCAi49RSy",
location: "/",
namespace: null
},
parameters: [ ],
dataset: false,
created_at: "2022-09-20T09:27:35.832537Z",
public_uuid: null
}

Field Metadata:

{
description: null,
database_type: "BIGNUMERIC",
semantic_type: null,
table_id: 115,
coercion_strategy: null,
table: {
description: null,
entity_type: "entity/GenericTable",
schema: "misc",
db: {
description: null,
features: [
"full-join",
"basic-aggregations",
"standard-deviation-aggregations",
"expression-aggregations",
"percentile-aggregations",
"foreign-keys",
"right-join",
"left-join",
"native-parameters",
"nested-queries",
"expressions",
"regex",
"case-sensitivity-string-filter-options",
"binning",
"inner-join",
"advanced-math-expressions"
],
cache_field_values_schedule: "0 0 21 * * ? *",
timezone: "UTC",
auto_run_queries: true,
metadata_sync_schedule: "0 0 0 * * ? *",
name: "Datawarehouse",
settings: null,
caveats: null,
creator_id: 12,
is_full_sync: false,
updated_at: "2022-09-19T15:22:03.265192Z",
cache_ttl: null,
details: {
dataset-filters-type: "inclusion",
project-id-from-credentials: "xx-xx-xx",
dataset-filters-patterns: "xx,xx,misc",
let-user-control-scheduling: true,
advanced-options: true,
use-jvm-timezone: false,
service-account-json: "**MetabasePass**",
project-id: null,
include-user-id-and-hash: true
},
is_sample: false,
id: 3,
is_on_demand: true,
options: null,
engine: "bigquery-cloud-sdk",
initial_sync_status: "complete",
refingerprint: true,
created_at: "2022-06-02T12:17:07.725042Z",
points_of_interest: null
},
show_in_getting_started: false,
name: "test_bug_bignumeric",
caveats: null,
updated_at: "2022-09-20T08:47:54.211328Z",
active: true,
id: 115,
db_id: 3,
visibility_type: null,
field_order: "database",
initial_sync_status: "complete",
display_name: "Test Bug Bignumeric",
created_at: "2022-09-20T08:47:33.377487Z",
points_of_interest: null
},
name: "value",
fingerprint_version: 5,
has_field_values: "none",
settings: null,
caveats: null,
fk_target_field_id: null,
dimensions: [ ],
updated_at: "2022-09-20T08:47:47.999628Z",
custom_position: 0,
effective_type: "type/Decimal",
active: true,
nfc_path: null,
parent_id: null,
id: 2022,
last_analyzed: "2022-09-20T08:47:54.30067Z",
position: 1,
visibility_type: "normal",
preview_display: true,
display_name: "Value",
database_position: 1,
name_field: null,
fingerprint: {
global: {
distinct-count: 6,
nil%: 0
},
type: {
type/Number: {
min: null,
q1: null,
q3: null,
max: null,
sd: null,
avg: null
}
}
},
created_at: "2022-09-20T08:47:36.663662Z",
base_type: "type/Decimal",
points_of_interest: null
}

**Severity**
It is blocking all self-serve users that cannot fall back to the SQL-editor and cast the column manually. This has a profound effect on how Metabase is currently used in our organizsation.

**Additional context**

**Comment by flamber** [comment] 2022-09-20 13:05
Duplicate of #25508

**Closed by flamber** 2022-09-20 13:05 UTC
Labels: Type:Bug, .Needs Triage
