### ISSUE TITLE
Scalars number doesn't apply number format configuration when decimal places is negative

### ISSUE THREAD

**Issue by KlingerMatheus** [metabase/metabase#24662] opened 2022-08-08 13:09 UTC
**Describe the bug**
When a value is viewed as Scalar and i tries to apply some format to the number such as: separator style and type of number(currency, scientific or percent), the configuration i set doesn't work when decimal places is set to less than 0.

**To Reproduce**
1. Create a new Question
2. Choose `Sample database` > `Orders`
3. Go to Summarize and click `Pick the metric you want to see`
4. Click on `Sum of...` > `Total`
5. Click on Visualize
6. You must see it in Scalar mode
7. Click in `Settings`
8. Set `Minimum number of decimal places` to a number less than `0`
9. Make change with `Separator Style` and/or `Style`

**Expected behavior**
The options `Style` and `Separator Style` should be applied correctly even when minimal number of decimal places is less than 0.
Also shouldn't get an error when trying to set `Style` as `Scientific` in the same case.

**Demo**
https://www.loom.com/share/4f46bba98d4042a3b4a0824917c3669b

**Information about your Metabase Installation:**

**Severity**
P2 or P3

**Comment by KlingerMatheus** [comment] 2022-08-08 13:29
I am working on it

**Comment by KlingerMatheus** [comment] 2022-08-08 13:33
It is fixed in this https://github.com/GitStartHQ/client-metabase/pull/135

**Comment by kdoh** [comment] 2023-12-12 14:49
Seems to be a duplicate of #24333

**Closed by kdoh** 2023-12-12 14:49 UTC
Labels: Type:Bug, Priority:P3, Visualization/Chart Settings, .Frontend, Visualization/Scalars
