### ISSUE TITLE
[Windows 10] - Metabase Initialization FAILED:  Assert failed: Unable to connect to Metabase h2 DB.

### ISSUE THREAD

**Issue by wingedpanther** [metabase/metabase#3250] opened 2016-08-22 10:47 UTC
I'm running _metabase_ on _windows 10_, _java version "1.8.0_101"_ is installed.I got following error message when I tried to start metabase

```
E:\AFNAM\MB-BI>java -jar metabase.jar
08-22 13:26:04 INFO metabase.core :: Starting Metabase in STANDALONE mode
08-22 13:26:04 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

08-22 13:26:04 INFO metabase.core :: Starting Metabase version v0.19.3 (796613e release-0.19.3) ...
08-22 13:26:04 INFO metabase.core :: System timezone is 'Asia/Riyadh' ...
08-22 13:26:07 DEBUG metabase.driver :: Registered driver :bigquery ?
08-22 13:26:07 DEBUG metabase.driver :: Registered driver :crate ?
08-22 13:26:08 DEBUG metabase.driver :: Registered driver :druid ?
08-22 13:26:08 DEBUG metabase.driver :: Registered driver :h2 ?
08-22 13:26:09 DEBUG metabase.driver :: Registered driver :mongo ?
08-22 13:26:09 DEBUG metabase.driver :: Registered driver :mysql ?
08-22 13:26:09 DEBUG metabase.driver :: Registered driver :postgres ?
08-22 13:26:09 DEBUG metabase.driver :: Registered driver :redshift ?
08-22 13:26:09 DEBUG metabase.driver :: Registered driver :sqlite ?
08-22 13:26:09 DEBUG metabase.driver :: Registered driver :sqlserver ?
08-22 13:26:10 INFO metabase.db :: Verifying h2 Database Connection ...
08-22 13:26:15 ERROR metabase.driver :: Failed to connect to database: Timed out after 5000 milliseconds.
java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
        at metabase.db$verify_db_connection.invokeStatic(db.clj:223)
        at metabase.db$verify_db_connection.invoke(db.clj:218)
        at metabase.db$setup_db.invokeStatic(db.clj:237)
        at metabase.db$setup_db.doInvoke(db.clj:229)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at metabase.core$init_BANG_.invokeStatic(core.clj:142)
        at metabase.core$init_BANG_.invoke(core.clj:126)
        at metabase.core$start_normally.invokeStatic(core.clj:226)
        at metabase.core$start_normally.invoke(core.clj:220)
        at metabase.core$_main.invokeStatic(core.clj:260)
        at metabase.core$_main.doInvoke(core.clj:255)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
08-22 13:26:15 ERROR metabase.core :: Metabase Initialization FAILED:  Assert failed: Unable to connect to Metabase h2 DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
08-22 13:26:15 INFO metabase.core :: Metabase Shutting Down ...
08-22 13:26:15 INFO metabase.core :: Metabase Shutdown COMPLETE
```

After above command a file(_metabase.db.lock.db_) is generated in the root folder in which _metabase.jar_ is located 

_Note: This is the first time am using metabase, if the above information aren't enough to fix my issue please let me know_

Any help would be much appreciated.

TIA

**Comment by salsakran** [comment] 2016-08-22 18:27
Where are you running the jar from? It sounds like a filesystem permissions issue if you're not also seeing a metabase.db.h2.db file in that directory as well.

**Comment by wingedpanther** [comment] 2016-08-23 05:37
@salsakran  Executing from a local drive.

I don't think that it related with permissions.


I have downloaded metabase in my colleague's system(Windows 7), it worked well and database was created w/o a single issue.I moved metabase.jar and database from his system to mine, now metabase is running on my system as well

**Comment by wilsongichuki** [comment] 2016-08-31 14:53
Maybe its an OS issue. I also had the same problem on Windows 10.

**Comment by camsaul** [comment] 2016-08-31 19:36
I'll try this out later when I'm by a Windows 10 PC it seems like there's an issue creating the `metabase.db.h2.db` file

**Comment by camsaul** [comment] 2016-08-31 22:28
Looks like this is actually a duplicate of #1871

**Closed by camsaul** 2016-08-31 22:28 UTC
Labels: Bug, Duplicate, OS/Windows, Running Metabase

**Comment by shoeb751** [comment] 2017-05-18 14:49
One more reason why this might happen is because of firewall rules.

Even though it is not evident, metabase is trying to connect to h2 using a TCP socket. I had some aggressive rules that blocked connections even to loop-back addresses on the box. Had to add an exception in the firewall to get it working.

**Comment by wredwan** [comment] 2018-03-07 15:16
you must run it as a windows admin like sudo with linux

**Comment by NasreenUstad** [comment] 2019-09-06 12:36
I was getting the same issue, it was all related to antivirus and firewalls. Turn off firewalls in Antivirus the Internet and Security options, then turn off your firewalls. after turning off, run your metabase commands, it will connect with metabase h2 db
