### ISSUE TITLE
Second clic on same cell on a table in a dashboard set an emtpy filter (clic to filter)

### ISSUE THREAD

**Issue by prigal** [metabase/metabase#26545] opened 2022-11-16 17:06 UTC
**Describe the bug**
In a dashboard I have a card with a table. I use the first colum to update a filter on the dashboard.
First clic is working, second not. The value is cleared. 

**Logs**
Nothing usefull I think.
[metabase.domain.tld-1668617999081.log](https://github.com/metabase/metabase/files/10024060/metabase.domain.tld-1668617999081.log)

**To Reproduce**
1. Go to a dashboard
2. Click on a cell of a card that apply a filter : filter is applied
3. Click again on the same cell : filter is cleared 

**Expected behavior**
Should keep the same value in the filter.

**Screenshots**
Look the screecast attached, the "Période" filter, it's cleared after the second clic on the same cell.

[Screencast from 2022-11-16 17-13-43.webm](https://user-images.githubusercontent.com/895267/202245738-125b1c3c-9291-4275-bb98-d9c3d78dc077.webm)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "4.15.18-2-pve",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-11-01",
      "tag": "v0.44.6",
      "branch": "release-x.44.x",
      "hash": "5c6ae21"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
**Severity**

**Additional context**

**Comment by flamber** [comment] 2022-11-16 17:09
Duplicate of #16304

**Closed by flamber** 2022-11-16 17:09 UTC
Labels: Type:Bug, .Needs Triage
