### ISSUE TITLE
Indicate invalid input in setup wizard

### ISSUE THREAD

**Issue by flyingmachine** [metabase/metabase#10622] opened 2019-08-19 19:10 UTC
**Describe the bug**

When going through the setup wizard, I skipped the Company Name field. When I tried to click Next, it turned out the button was disabled. Because the UI didn't indicate what was invalid, I wasn't sure if I needed to fill out Company Name, or if there was something else I needed to do.

**To Reproduce**

1. Run metabase in a new docker container, `docker run -d -p 3000:3000 --name mb-invalid-input metabase/metabase`
2. In step 1 of setup wizard, fill out all fields except company name (or otherwise enter invalid data)

**Expected behavior**

A couple possibilities:

* Show asterisks by all required fields
* Display validation messages for all fields after blurring them (for example, show a message if password and password confirmation after blurring password confirmation)

**Screenshots**

<img width="746" alt="Screen Shot 2019-08-19 at 3 10 27 PM" src="https://user-images.githubusercontent.com/1421/63292376-82166e80-c293-11e9-9705-aebcc8e02a6e.png">

**Information about your Metabase Installation:**

- Docker
- Mac 10.14.6

**Severity**

annoying

**Comment by flamber** [comment] 2019-08-19 19:30
Hi @flyingmachine 
Looks like a duplicate of #3077 - if you agree, then please close this and upvote the other issue.

**Comment by flyingmachine** [comment] 2019-08-21 13:35
@flamber I think this is different :) The other required fields, like First name and Last name, should also have visual indicators that they are required

**Comment by brunobergher** [comment] 2024-12-30 13:45
Not applicable anymore, we redesigned this a bunch.

**Closed by brunobergher** 2024-12-30 13:45 UTC
Labels: Type:UX, Priority:P2, First Experience/Setup
