### ISSUE TITLE
Cannot sort when using 2 similar aggregations (ex: 2 sums)

### ISSUE THREAD

**Issue by niparis** [metabase/metabase#5950] opened 2017-09-13 10:07 UTC
### Steps to reproduce:

1. Start a new question
2. Groupby anything
3. In view, select sum of >> any column, *twice*

Click get answer, the answers comes out fine.

Then if try to sort, either directly from the table, you will get the following error: 
![image](https://user-images.githubusercontent.com/3415960/30371595-aabc314c-98ad-11e7-8b54-bdcce3010012.png)

SQL query from the logs (with minimal formatting)

```
SELECT sum(\"public\".\"users\".\"age\") AS \"sum\"
      , sum(\"public\".\"users\".\"spend\") AS \"sum\"
      , date_trunc('month', CAST(\"public\".\"users\".\"signupdate\" AS timestamp)) AS \"signupdate\" 
FROM \"public\".\"users\" 
GROUP BY date_trunc('month', CAST(\"public\".\"users\".\"signupdate\" AS timestamp)) 
ORDER BY \"sum\" DESC, date_trunc('month', CAST(\"public\".\"users\".\"signupdate\" AS timestamp)) ASC"
```

### Technical info

- db: postgres RDS (data + backend)
- Metabase version: 0.25.2
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

**Comment by salsakran** [comment] 2017-09-25 22:43
closing as a dupe of #6042 just because we threw out some options for solutions in that one.

**Closed by salsakran** 2017-09-25 22:43 UTC
