### ISSUE TITLE
Download button disapears after saving question

### ISSUE THREAD

**Issue by sudoaza** [metabase/metabase#11272] opened 2019-11-06 15:52 UTC
**Describe the bug**
After saving a question the button for downloading the results dissapears, this causes the user to re run the query just to get the button displayed. This amounts to 3 runs of a query to get the results (original, after save, generate download).

**To Reproduce**
1. Go to write an SQL question.
2. Run it (download button becomes visible)
3. Save it
4. Download button disapears

**Expected behavior**
Download button should remain visible if there was no change in the query.

**Related**
This other issue would probably fix this too
https://github.com/metabase/metabase/issues/4820

**Comment by mazameli** [comment] 2019-11-21 22:38
I think that fixing https://github.com/metabase/metabase/issues/11006 would fix this. The download button disappears whenever a query is "dirty." This actually does happen with GUI questions as well if auto-running is turned off for the DB that's being queried.

**Comment by salsakran** [comment] 2020-02-22 03:21
closing since #11006 was the root cause

**Closed by salsakran** 2020-02-22 03:21 UTC
Labels: Priority:P2, Querying/, Type:UX
