### ISSUE TITLE
Kylin JDBC connect

### ISSUE THREAD

**Issue by sushmagoravar** [metabase/metabase#27668] opened 2023-01-13 10:13 UTC
https://github.com/metabase/metabase/issues/new/choose

iam trying to load tables from jdbc into kylin i did all configuration in kylin ,still kylin not able to load tables

**Comment by paoliniluis** [comment] 2023-01-13 10:18
This is a duplicate of https://github.com/metabase/metabase/issues/5672

**Closed by paoliniluis** 2023-01-13 10:18 UTC
