### ISSUE TITLE
Dashboard filter refresh all questions, not only the linked ones

### ISSUE THREAD

**Issue by Olaktal** [metabase/metabase#20251] opened 2022-02-04 13:20 UTC
Hello community 

We have a dashboard with multiple questions inside as follow

![image](https://user-images.githubusercontent.com/5711131/152535435-c5b19243-1ca9-4f94-b884-8cbf85a7d089.png)

When updating filter 'ID Produit comparatif' value, I'd like only questions linked to the filter (i.e 'Quantité de produits vendus' & 'Liste Quantité Perte') to be refreshed instead of all questions in the dashboard being refreshed.

It make us lost every sort/action made + it is costly for the database

Do you have any idea when it can be fixed ?

Thanks !
Best regards, Vincent

**Comment by flamber** [comment] 2022-02-04 13:29
Duplicate of #8030

**Closed by flamber** 2022-02-04 13:29 UTC
Labels: Type:New Feature, .Needs Triage
