### ISSUE TITLE
Permissions Stage 1

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3362] opened 2016-09-15 23:59 UTC
This feature will allow admins to:

* Assign users to groups
* Control access of these groups to Databases, Namespaces and Tables
* Control a given group's ability to create SQL questions on a given database 

Schema access in a database is controlled as follows
* A user group has access to all schema in a database
* A user group has access to no schema in a database 
* A user has access to a white list of schemas in a database 

Table access within a schema (or within a database without multiple namespaces)
* A user group has access to all tables
* A user group has access to no tables
* A user has access to a white list of tables

This is being worked on in #3088

**Comment by camsaul** [comment] 2016-09-16 00:02
@salsakran duplicate of #3087

**Comment by salsakran** [comment] 2016-09-16 00:03
good point. merge either into the other.  wanted to break this out vs #3363 and use similar formats. you have a preference for keeping #3087?

**Comment by camsaul** [comment] 2016-09-16 00:04
No feel free to close it in favor of this

**Comment by cagiraudo** [comment] 2016-09-29 13:07
Hi, just one question.

This new user and permissions managment for v0.20 will allow me to make user or group to only be able to see certain dashboard?

Becouse that's the most important to me

**Comment by tlrobinson** [comment] 2016-09-29 15:01
@cagiraudo the first stage, in v0.20, include access limits on databases, schemas, tables (and the ability to write SQL queries). If a user doesn't have sufficient data permissions for a question they can't view that question, and if they can't view any questions on a dashboard they can't see that particular dashboard.

So in a way, yes, but probably not exactly what you want.

The next stage will include dashboard and question permissions.

**Comment by salsakran** [comment] 2016-09-29 18:16
@cagiraudo there will be more direct support for limiting access to dashboards that specific groups own in #3363 as well.

**Comment by cagiraudo** [comment] 2016-09-29 18:55
Excelent. If the user can't see the question in the dashboards for table permission it's good enough for me right now.

It will be perfect with dashboards permissions becouse take for example i have a table "Incoming" and i want a group for example "Comercial" to only see a dashboard with the info of the incoming only they generate. If i block the table incoming i wont be able to do it, but if i don't block it they will be able to see the incomings of other areas in other dashboards. I hope you can understand my example despite my bad english.

Will be waiting foward v0.21 then, but it's still a great improvement for next version

**Comment by camsaul** [comment] 2016-10-01 02:19
Implemented by #3376

**Closed by camsaul** 2016-10-01 02:19 UTC
Labels: Enhancement
