### ISSUE TITLE
Deleted dashboards show up in the entity picker

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#44973] opened 2024-07-01 13:10 UTC
### Describe the bug

Dashboards that are in "Trash" (archived) or even the ones that are permanently deleted will still show up in an entity picker.
At first, I thought this was only a cache problem, but even the hard refresh doesn't help. So it might be an actual flaw in the logic.

### To Reproduce

1. Create a new dashoard
2. Then "trash" it.

From here we have two ways to reproduce this and both should be covered in an E2E test.
1. Create a new question
2. Save it
3. Modal will ask you to 

or

1. Open an existing question
2. Click on `...` menu and click on "Add to dashboard"

### Expected behavior

We should never show archived or deleted items in the entity picker.

### Logs

`GET http://localhost:3000/api/activity/most_recently_viewed_dashboard 404 (Not Found)`

### Information about your Metabase installation

local dev, `master`, 781c948, H2, Sample Database

### Severity

P2, but I'm closer to give this a P1 because the "common feature" is broken

**Comment by npfitz** [comment] 2024-08-28 13:18
I'll confirm with @escherize , but I believe there was some BE work done to remove archived items from recents in the not-too-distant past. I'm unable to reproduce on `master` or on `50.20`

**Comment by escherize** [comment] 2024-09-30 16:03
I also was unable to reproduce. I think it got fixed by [Don't return an archived dashboard as the most recently viewed dashboard](https://github.com/metabase/metabase/pull/45229).

**Closed by escherize** 2024-09-30 16:03 UTC
Labels: Type:Bug, Priority:P2, .Regression/master, Organization/Trash, .Team/AdminWebapp
