### ISSUE TITLE
database connection via ssh key

### ISSUE THREAD

**Issue by GuangyuLi1** [metabase/metabase#9481] opened 2019-02-23 03:51 UTC
I know that some guys had asked for this function, but It seems to have no progress, so I would like to ask again for help.
If anyone working for metabase, please do consider this important function. Thanks!!

**Comment by flamber** [comment] 2019-02-23 06:33
Duplicate of #5153. Have you tried the workaround? https://github.com/metabase/metabase/issues/5153#issuecomment-446608031

Creating new issues doesn't help.
There's currently 1928 open issues. More than half are duplicates, invalid, or already fixed issues. It's difficult enough already to try to have an overview relevant issues without all the duplicates.

**Comment by tlrobinson** [comment] 2019-02-26 18:39
Duplicate of #5153

**Closed by tlrobinson** 2019-02-26 18:39 UTC
Labels: Duplicate
