### ISSUE TITLE
Grouping by PK/FK with values higher than 1000 incorrectly makes them Timeseries

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16981] opened 2021-07-12 11:15 UTC
**Describe the bug**
Grouping by PK/FK with values higher than 1000 incorrectly makes them Timeseries by default, which looks and behaves wrong.

**Workaround**: Manually changing "X-axis scale" to Linear or Ordinal in the visualization settings Axes tab

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Filter by ID (or UserID) = `1000,1001,1002,1003`
3. Summarize Count by ID (or UserID)
![image](https://user-images.githubusercontent.com/1447303/125277577-e58b6880-e311-11eb-93bd-bf197cf4ee26.png)
4. Change visualization to Line/Bar/Area - incorrectly marked as Timeseries instead of Ordinal, Linear or Histogram.
![image](https://user-images.githubusercontent.com/1447303/125277442-b5dc6080-e311-11eb-891c-3f97cf1e76bd.png)
5. Drag-to-select will incorrectly parse as date types
![image](https://user-images.githubusercontent.com/1447303/125277855-43b84b80-e312-11eb-821c-eac71618eb78.png)

<details><summary>Full stacktrace</summary>

```
2021-07-12 13:14:52,756 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 4,
 :started_at #t "2021-07-12T13:14:51.852321+02:00[Europe/Copenhagen]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error filtering against :type/BigInteger Field: unable to parse String \"1970-01-01T01:00:00+01:00\" to a :type/BigInteger",
   :stacktrace
   ["--> query_processor.middleware.auto_parse_filter_values$fn__42166$parse_value_for_base_type__42171$fn__42172.invoke(auto_parse_filter_values.clj:26)"
    "query_processor.middleware.auto_parse_filter_values$fn__42166$parse_value_for_base_type__42171.invoke(auto_parse_filter_values.clj:15)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values_STAR_$fn__42188$replace_42189__42190.invoke(auto_parse_filter_values.clj:34)"
    "mbql.util.match$replace_in_collection.invokeStatic(match.clj:135)"
    "mbql.util.match$replace_in_collection.invoke(match.clj:126)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values_STAR_$fn__42188$replace_42189__42190.invoke(auto_parse_filter_values.clj:34)"
    "mbql.util.match$replace_in_collection$iter__26261__26265$fn__26266.invoke(match.clj:132)"
    "mbql.util.match$replace_in_collection.invokeStatic(match.clj:131)"
    "mbql.util.match$replace_in_collection.invoke(match.clj:126)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values_STAR_$fn__42188$replace_42189__42190.invoke(auto_parse_filter_values.clj:34)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values_STAR_$fn__42188.invoke(auto_parse_filter_values.clj:34)"
    "mbql.util$update_in_unless_empty.invokeStatic(util.clj:183)"
    "mbql.util$update_in_unless_empty.doInvoke(util.clj:178)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values_STAR_.invokeStatic(auto_parse_filter_values.clj:34)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values_STAR_.invoke(auto_parse_filter_values.clj:33)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__42204.invoke(auto_parse_filter_values.clj:44)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__45861.invoke(wrap_value_literals.clj:149)"
    "query_processor.middleware.annotate$add_column_info$fn__41959.invoke(annotate.clj:575)"
    "query_processor.middleware.permissions$check_query_permissions$fn__43281.invoke(permissions.clj:71)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__44813.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__43479.invoke(cumulative_aggregations.clj:61)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__45050.invoke(resolve_joined_fields.clj:36)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__45369.invoke(resolve_joins.clj:183)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__37684.invoke(add_implicit_joins.clj:254)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__44091.invoke(large_int_id.clj:44)"
    "query_processor.middleware.format_rows$format_rows$fn__44071.invoke(format_rows.clj:75)"
    "query_processor.middleware.desugar$desugar$fn__43545.invoke(desugar.clj:22)"
    "query_processor.middleware.binning$update_binning_strategy$fn__42563.invoke(binning.clj:229)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__43081.invoke(resolve_fields.clj:24)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__37228.invoke(add_dimension_projections.clj:318)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__37435.invoke(add_implicit_clauses.clj:141)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__37833.invoke(add_source_metadata.clj:105)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__45010.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__42151.invoke(auto_bucket_datetimes.clj:140)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__43128.invoke(resolve_source_table.clj:46)"
    "query_processor.middleware.parameters$substitute_parameters$fn__44795.invoke(parameters.clj:114)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__43180.invoke(resolve_referenced.clj:80)"
    "query_processor.middleware.expand_macros$expand_macros$fn__43801.invoke(expand_macros.clj:158)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__37864.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__45731.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__45021$fn__45025.invoke(resolve_database_and_driver.clj:33)"
    "driver$do_with_driver.invokeStatic(driver.clj:61)"
    "driver$do_with_driver.invoke(driver.clj:57)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__45021.invoke(resolve_database_and_driver.clj:27)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__44019.invoke(fetch_source_query.clj:267)"
    "query_processor.middleware.store$initialize_store$fn__45740$fn__45741.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
    "query_processor.store$do_with_store.invoke(store.clj:40)"
    "query_processor.middleware.store$initialize_store$fn__45740.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__45749.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__44143.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__37702.invoke(add_rows_truncated.clj:36)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__45716.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__43422.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__44884.invoke(process_userland_query.clj:136)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__43365.invoke(catch_exceptions.clj:174)"
    "query_processor.reducible$async_qp$qp_STAR___36491$thunk__36492.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___36491.invoke(reducible.clj:109)"
    "query_processor.reducible$sync_qp$qp_STAR___36500$fn__36503.invoke(reducible.clj:135)"
    "query_processor.reducible$sync_qp$qp_STAR___36500.invoke(reducible.clj:134)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:237)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:233)"
    "query_processor$fn__45907$process_query_and_save_execution_BANG___45916$fn__45919.invoke(query_processor.clj:249)"
    "query_processor$fn__45907$process_query_and_save_execution_BANG___45916.invoke(query_processor.clj:241)"
    "query_processor$fn__45951$process_query_and_save_with_max_results_constraints_BANG___45960$fn__45963.invoke(query_processor.clj:261)"
    "query_processor$fn__45951$process_query_and_save_with_max_results_constraints_BANG___45960.invoke(query_processor.clj:254)"
    "api.dataset$fn__52618$fn__52621.invoke(dataset.clj:59)"
    "query_processor.streaming$streaming_response_STAR_$fn__52599$fn__52600.invoke(streaming.clj:73)"
    "query_processor.streaming$streaming_response_STAR_$fn__52599.invoke(streaming.clj:72)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
    "async.streaming_response$do_f_async$fn__24642.invoke(streaming_response.clj:85)"],
   :error_type :invalid-query,
   :ex-data {:type :invalid-query}}],
 :error_type :invalid-query,
 :json_query
 {:type "query",
  :query {:source-table 11, :filter ["between" ["field-id" 83] "1970-01-01T01:00:00+01:00" "1970-01-01T01:00:01+01:00"], :aggregation [["count"]], :breakout [["field-id" 83]]},
  :database 4,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native nil,
 :status :failed,
 :class java.lang.NumberFormatException,
 :stacktrace
 ["java.base/java.math.BigInteger.<init>(BigInteger.java:492)"
  "java.base/java.math.BigInteger.<init>(BigInteger.java:672)"
  "java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)"
  "java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)"
  "java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)"
  "java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)"
  "clojure.lang.Reflector.invokeConstructor(Reflector.java:305)"
  "clojure.core$bigint.invokeStatic(core.clj:3624)"
  "clojure.core$bigint.invoke(core.clj:3619)"
  "--> query_processor.middleware.auto_parse_filter_values$fn__42166$parse_value_for_base_type__42171$fn__42172.invoke(auto_parse_filter_values.clj:19)"
  "query_processor.middleware.auto_parse_filter_values$fn__42166$parse_value_for_base_type__42171.invoke(auto_parse_filter_values.clj:15)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values_STAR_$fn__42188$replace_42189__42190.invoke(auto_parse_filter_values.clj:34)"
  "mbql.util.match$replace_in_collection.invokeStatic(match.clj:135)"
  "mbql.util.match$replace_in_collection.invoke(match.clj:126)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values_STAR_$fn__42188$replace_42189__42190.invoke(auto_parse_filter_values.clj:34)"
  "mbql.util.match$replace_in_collection$iter__26261__26265$fn__26266.invoke(match.clj:132)"
  "mbql.util.match$replace_in_collection.invokeStatic(match.clj:131)"
  "mbql.util.match$replace_in_collection.invoke(match.clj:126)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values_STAR_$fn__42188$replace_42189__42190.invoke(auto_parse_filter_values.clj:34)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values_STAR_$fn__42188.invoke(auto_parse_filter_values.clj:34)"
  "mbql.util$update_in_unless_empty.invokeStatic(util.clj:183)"
  "mbql.util$update_in_unless_empty.doInvoke(util.clj:178)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values_STAR_.invokeStatic(auto_parse_filter_values.clj:34)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values_STAR_.invoke(auto_parse_filter_values.clj:33)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__42204.invoke(auto_parse_filter_values.clj:44)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__45861.invoke(wrap_value_literals.clj:149)"
  "query_processor.middleware.annotate$add_column_info$fn__41959.invoke(annotate.clj:575)"
  "query_processor.middleware.permissions$check_query_permissions$fn__43281.invoke(permissions.clj:71)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__44813.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__43479.invoke(cumulative_aggregations.clj:61)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__45050.invoke(resolve_joined_fields.clj:36)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__45369.invoke(resolve_joins.clj:183)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__37684.invoke(add_implicit_joins.clj:254)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__44091.invoke(large_int_id.clj:44)"
  "query_processor.middleware.format_rows$format_rows$fn__44071.invoke(format_rows.clj:75)"
  "query_processor.middleware.desugar$desugar$fn__43545.invoke(desugar.clj:22)"
  "query_processor.middleware.binning$update_binning_strategy$fn__42563.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__43081.invoke(resolve_fields.clj:24)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__37228.invoke(add_dimension_projections.clj:318)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__37435.invoke(add_implicit_clauses.clj:141)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__37833.invoke(add_source_metadata.clj:105)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__45010.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__42151.invoke(auto_bucket_datetimes.clj:140)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__43128.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.parameters$substitute_parameters$fn__44795.invoke(parameters.clj:114)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__43180.invoke(resolve_referenced.clj:80)"
  "query_processor.middleware.expand_macros$expand_macros$fn__43801.invoke(expand_macros.clj:158)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__37864.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__45731.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__45021$fn__45025.invoke(resolve_database_and_driver.clj:33)"
  "driver$do_with_driver.invokeStatic(driver.clj:61)"
  "driver$do_with_driver.invoke(driver.clj:57)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__45021.invoke(resolve_database_and_driver.clj:27)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__44019.invoke(fetch_source_query.clj:267)"
  "query_processor.middleware.store$initialize_store$fn__45740$fn__45741.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__45740.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__45749.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__44143.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__37702.invoke(add_rows_truncated.clj:36)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__45716.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__43422.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__44884.invoke(process_userland_query.clj:136)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__43365.invoke(catch_exceptions.clj:174)"
  "query_processor.reducible$async_qp$qp_STAR___36491$thunk__36492.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___36491.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___36500$fn__36503.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___36500.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:237)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:233)"
  "query_processor$fn__45907$process_query_and_save_execution_BANG___45916$fn__45919.invoke(query_processor.clj:249)"
  "query_processor$fn__45907$process_query_and_save_execution_BANG___45916.invoke(query_processor.clj:241)"
  "query_processor$fn__45951$process_query_and_save_with_max_results_constraints_BANG___45960$fn__45963.invoke(query_processor.clj:261)"
  "query_processor$fn__45951$process_query_and_save_with_max_results_constraints_BANG___45960.invoke(query_processor.clj:254)"
  "api.dataset$fn__52618$fn__52621.invoke(dataset.clj:59)"
  "query_processor.streaming$streaming_response_STAR_$fn__52599$fn__52600.invoke(streaming.clj:73)"
  "query_processor.streaming$streaming_response_STAR_$fn__52599.invoke(streaming.clj:72)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
  "async.streaming_response$do_f_async$fn__24642.invoke(streaming_response.clj:85)"],
 :context :ad-hoc,
 :error "Illegal embedded sign character",
 :row_count 0,
 :running_time 0,
 :preprocessed nil,
 :data {:rows [], :cols []}}
```

</details>

**Expected behavior**
It will not mark as Timeseries if there's a value below 1000. It will default to Linear. PK/FK should never be Timeseries (unless it's actually a date type column).

**Information about your Metabase Installation:**
Tested 0.37.8 thru 0.40.0

**Comment by alxnddr** [comment] 2024-12-20 21:19
Duplicate of https://github.com/metabase/metabase/issues/30102

**Closed by alxnddr** 2024-12-20 21:19 UTC
Labels: Type:Bug, Priority:P3, Visualization/Charts, .Team/DashViz
