### ISSUE TITLE
Can't login via Chrome in iOS (iPhone)

### ISSUE THREAD

**Issue by nutteen** [metabase/metabase#6355] opened 2017-11-09 07:49 UTC
Chrome version: 62.0 last updated on 27 of oct in iPhone 7. 

To reproduce:
 1. Go to the first page of app from chrome
 2. Enter username and password so signin button show up 
 3. click sign in, this leads to nothing.

Try over and over again I can never login.

However it works in Safari application.

**Comment by salsakran** [comment] 2017-11-10 18:37
Can't reproduce this on an chrome 62.0 on an iphone 6s.

**Comment by camsaul** [comment] 2017-12-07 03:13
@nutteen are you still running into this issue?

**Comment by kdoh** [comment] 2018-07-31 17:17
Going to go ahead and close this since we weren't able to reproduce it.

**Closed by kdoh** 2018-07-31 17:17 UTC
Labels: Need More Info, Unable to Reproduce
