### ISSUE TITLE
Manual joins in Custom questions break suggestions in dashboard category filters

### ISSUE THREAD

**Issue by mlm603** [metabase/metabase#12788] opened 2020-06-26 16:19 UTC
**Describe the bug**
When you join two tables in a Custom question that are not already joined based on primary/foreign key in the data model, `category` dashboard filters no longer suggest values.

**To Reproduce**
1. Using the sample dataset, change `user_id` on the `Orders` table to `category` type to break the FK/PK relationship.
![Screen Shot 2020-06-26 at 12 10 47 PM](https://user-images.githubusercontent.com/13624950/85878099-32071300-b7a6-11ea-8758-feea6d437b9a.png)
2. Manually recreate the join in a custom question
![Screen Shot 2020-06-26 at 12 12 30 PM](https://user-images.githubusercontent.com/13624950/85878211-5cf16700-b7a6-11ea-87c6-7d5c2fdbffce.png)
3. Add a category filter on the `Name` field from the `People` table
![Screen Shot 2020-06-26 at 12 13 41 PM](https://user-images.githubusercontent.com/13624950/85878367-94601380-b7a6-11ea-869d-1a8879509f22.png)
4. You'll see that the filter only accepts text input and does not provide suggestions of values
![Screen Shot 2020-06-26 at 12 14 35 PM](https://user-images.githubusercontent.com/13624950/85878451-b3f73c00-b7a6-11ea-9c17-2413db64ec49.png)

**Expected behavior**
The same question using the implicit join created by the FK/PK relationship works as expected and prompts the user with suggestions for filter values.
![Screen Shot 2020-06-26 at 12 17 48 PM](https://user-images.githubusercontent.com/13624950/85878744-31bb4780-b7a7-11ea-9f45-ad58825cce13.png)

**Information about your Metabase Installation:**
Metabase v1.35.4

**Severity**
This is a Medium-High priority for our team. We often need multi layered joins that are not supported based on the current primary/foreign key structure. Our temporary solution is to use SQL questions with parameters when we do these kind of joins, but many of our end users are not comfortable writing SQL.

**Comment by flamber** [comment] 2020-06-26 17:35
Duplicate of #12250 - fixed in upcoming 0.36 - please use support email, when using Enterprise Edition.

**Closed by flamber** 2020-06-26 17:35 UTC
Labels: .Needs Triage, Type:Bug

**Comment by mlm603** [comment] 2020-06-26 17:48
@flamber sorry to flood you with requests, especially with my subpar issue vetting 😬  Will use email going forward
