### ISSUE TITLE
Apply Visualization Data settings by default across all categories 

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#27864] opened 2023-01-25 14:34 UTC
**Is your feature request related to a problem? Please describe.**
 Lets say right now I have 4 categories which i go on manually in each 4 categories and set them to show the dot on line but in a couple of months a new category gets introduced this new addition will end up in the chart without a dot and i have to manually keep updating this for every new category. 

![image](https://user-images.githubusercontent.com/110378427/214589931-00c8684b-efca-4fa1-94c2-eb39e6c31654.png)

Now imagine you have a dashboard with 10 charts and you have to go and change the setting for each individual new category

**Describe the solution you'd like**

Have a way to apply the line dots or turn them off by default across all dimensions in a report without having to apply the toggle one by on.

Maybe put a 3 dots here that would be the default kind of and new categories (objects) will inherit from this default. 

![image](https://user-images.githubusercontent.com/110378427/214590102-93fc0161-4c2a-4e45-b841-a488b24b28e8.png)

**Comment by brunobergher** [comment] 2024-12-30 15:45
Looks like a duplicate of #11871

**Closed by brunobergher** 2024-12-30 15:45 UTC
Labels: Type:New Feature, Visualization/Chart Settings, .Team/DashViz
