### ISSUE TITLE
Cannot click on some of "Saved Questions" in my personnal collection, that sometime disappear

### ISSUE THREAD

**Issue by EBoisseauSierra** [metabase/metabase#11496] opened 2019-12-11 12:22 UTC
## Describe the bug
I want to create a nested query (thus, based on one already existing query). In the editor, when asking a Custom Question, I browse to "Saved Questions- Étienne Boisseau-Sierra's Personal Collection".

The question I want to start building on is called _"Total Lines by Depot_lean"_

* _Issue number 1:_ **Some questions saved in the collection _intermittently_ do not appear in the list** (at the beginning of the recording below — the question was listed a few moments earlier). Note that the same happens for the personnal collections themselves: some users (me — i.e., the current user) are sometimes not listed when selecting _Data/Saved Questions_.
* _Issue number 2:_ When the question does finally appear in the list, **I cannot click on it**.

## **Logs**
Logs do not show a lot (in the recording below, I'm showing the logs in real time).

## **Screen recording**
![Peek 2019-12-11 10-55_redacted](https://user-images.githubusercontent.com/37387755/70620949-5dfae680-1c10-11ea-863c-232440f3cc0a.gif)

1. I show the log, and enter a few blank lines to remember where we started
2. The question  _"Total Lines by Depot_lean"_ is missing in the list (it appeared before, and is not concurrently being modified).
3. I refresh the page, and now I can see the question listed, however…
4. … I can't click on it (or when I do, nothing happen — unlike for _"Lines 1_lean"_ or _"Lines 2_lean"_ )

## **To Reproduce**
That's the hard bit: it's intermittently, so I haven't found what is the common factor among the questions/collections behaving weirdly.

## **Expected behavior**
All items appear all the time (issue 1), and I can click on each of them (issue 2).

## **Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_232-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_232",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.232-b09",
    "os.name": "Linux",
    "os.version": "5.1.16-300.fc30.x86_64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.6",
      "date": "2019-11-19",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

## **Severity**
Blocking some users in their usage of Metabase (i.e. they cannot ask the questions they want — where these question require a join of two previously created questions).

**Comment by flamber** [comment] 2019-12-11 13:59
Hi @EBoisseauSierra 
Could it be that your Saved Question is constructed in a way, that it isn't allowed as source?
https://www.metabase.com/docs/latest/users-guide/custom-questions.html#picking-your-starting-data
Of course, that still shouldn't show it on refresh. Related to #11194.
Are you seeing errors in the browser console?

**Comment by EBoisseauSierra** [comment] 2019-12-11 16:25
>  Could it be that your Saved Question is constructed in a way, that it isn't allowed as source?

Well, I should have posted the question indeed, which is a **Sum of** aggregate:

![Screenshot from 2019-12-11 16-12-38](https://user-images.githubusercontent.com/37387755/70638674-37997300-1c31-11ea-97fe-96ccf96f27ad.png)

This sum is based on a question that is itself a **(Count of) Distinct values** (+ some filters) from a standard SQL table:

![Screenshot from 2019-12-11 16-15-25](https://user-images.githubusercontent.com/37387755/70638865-82b38600-1c31-11ea-948e-ab04d07c171b.png)

➥ So **it is using allowed sources**, as far as I know. (Yet thanks for the pointer to the documentation, as I wasn't aware of it.)

> Are you seeing errors in the browser console?

You had the right intuition: I am getting an `TypeError: this.metadata(...).table(...).database is null` JS error:

![Peek 2019-12-11 16-21_redacted](https://user-images.githubusercontent.com/37387755/70639708-c0fd7500-1c32-11ea-827b-3e859535891c.gif)

**Comment by flamber** [comment] 2019-12-11 17:21
@EBoisseauSierra I might be misunderstanding something, but you have two `Warehouse Code`, so that would create a conflict, as noted in the documentation. I'm fairly sure that is causing the missing Saved Question. There's still a bug, since it can reappear with refresh.

**Comment by EBoisseauSierra** [comment] 2019-12-11 18:02
In this case, we have a first question (`Lines_2_lean`) that looks like:
```
SELECT <columns for GROUP BY: "warehouse_code", "transaction_date", "issue_code", "requisition_code">,
       count(distinct "requisition_line") AS "count"
FROM "transactions"
WHERE <filter>
GROUP BY  "warehouse_code", "transaction_date", "issue_code", "requisition_code"
```
and returns a result (neglecting what the visualisation actually is) similar to:

| Warehouse Code | Transaction Date | Issue Code | Requisition Code | Distinct values of Requisition Line |
| --- | --- | --- | --- | --- |
|WH-1 | 2019-12-42 | 2 | BMT216A | 13 |
|WH-1 | 2019-12-42 | 2 | BMT214A | 17 |
|WH-2 | 2019-12-42 | 2 | 56526 | 42 |

Then, in `Total lines per depot lean`, I'm querying on the table/result above, and `GROUP BY "warehouse_code"`… Do you think this would cause an issue?

**Comment by flamber** [comment] 2019-12-11 18:06
@EBoisseauSierra Yes, because Group By also adds it to the `SELECT` clause, which means you have two `warehouse_code`.

**Comment by EBoisseauSierra** [comment] 2019-12-11 18:25
Here is how the code looks like:
```
SELECT "source"."sum" AS "sum", <------- 1st SELECT
       "Warehouse"."full_name" AS "full_name"
FROM (
    SELECT "source"."warehouse_code" AS "warehouse_code",    <------- 2nd SELECT
         sum("source"."count") AS "sum"
    FROM (
            SELECT "Transactions"."warehouse_code" AS "warehouse_code", <------- 3rd SELECT
            CAST("Transactions"."transaction_date" AS date) AS "transaction_date",
            "Transactions"."issue_code" AS "issue_code",
            "Transactions"."requisition_code" AS "requisition_code",
            count(distinct "Transactions"."requisition_line") AS "count"
            FROM "Transactions"
            WHERE (<filter>)
            GROUP BY  "Transactions"."warehouse_code", CAST("Transactions"."transaction_date" AS date), "Transactions"."issue_code", "Transactions"."requisition_code"
            ORDER BY […]
        ) "source"
        GROUP BY  "source"."warehouse_code"
        ORDER BY  […]
) "source"
LEFT JOIN "Warehouse"
ON "source"."warehouse_code" = "Warehouse"."warehouse_code"
ORDER BY  […]
``` 

I'm not sure which `SELECT` clause you are talking about — could you please precise it for me?

The documentation reads:
> questions that have columns that are named the same or similar thing, like Count and Count 2

My understanding is that there shouldn't be 2 columns which have similar name _at the same time_ in the query/result… which isn't — as far as I can tell, cf. how the results look like above — the case here. But I'm afraid I'm not understanding something here…

**Comment by flamber** [comment] 2019-12-11 19:59
@EBoisseauSierra Okay, so I have reproduced with Sample Dataset and getting these errors, when trying to create a new question based on the second Saved Question. I would guess it's because of the conflicting `warehouse_code` (both returned and joined), but it might have something to do with the amount of levels of Saved Question.
```
Firefox: TypeError: this.metadata(...).table(...).database is null
Chromium: Uncaught TypeError: Cannot read property 'id' of null
```
**Reproduce:**
_Replace Transactions with Orders (warehouse_code => product_id) and Warehouse with Products._
1. First question:
![image](https://user-images.githubusercontent.com/1447303/70653457-28f39180-1c1a-11ea-91f3-4eccb924be57.png)
2. Second question is based on first:
![image](https://user-images.githubusercontent.com/1447303/70653499-34df5380-1c1a-11ea-9024-d5c6f763c24a.png)

**Comment by mazameli** [comment] 2020-01-22 19:20
Fixed by https://github.com/metabase/metabase/pull/11760

**Closed by mazameli** 2020-01-22 19:20 UTC
Labels: Priority:P2, Querying/Notebook, Type:Bug
