### ISSUE TITLE
Formatting for field in Data Modeling is no longer working

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#30920] opened 2023-05-22 22:22 UTC
### Describe the bug

Browse to any field in any table in Data Modeling (admin) and click on the gear icon to show the field details page, and then click on Formatting. Everything on this page seems to be read-only as you can't change anything. For anything that you can change, it reverts back to original if you click on General tab and click back to Formatting. 

Specifically, I was trying to add a suffix, which doesn't work as it doesn't save. I also noticed that it is showing currency settings even though the display style is normal (for a quantity field). 

### To Reproduce

See steps in description

### Expected behavior

Changes for any field in Formatting should save

### Logs

No errors in JavsScript console / it seems to do nothing when changes happen in UI

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "5.4.209-116.367.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-05-22",
      "tag": "vUNKNOWN",
      "branch": "master",
      "hash": "f60e1e4"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

### Severity

It blocks field formatting changes

### Additional context

<img width="1163" alt="Screenshot 2023-05-22 at 3 09 26 PM" src="https://github.com/metabase/metabase/assets/9684260/a0559ce3-6889-4e94-be24-78a5360cf24a">

**Comment by iethree** [comment] 2023-08-17 19:29
unable to reproduce this locally or on stats. these settings seem to save properly, and the formatting options appear in tables

. | admin metadata formatting settings | table view
---|---|---
local (postgres)| ![Screen Shot 2023-08-17 at 1 24 24 PM](https://github.com/metabase/metabase/assets/30528226/af18d135-5a14-4ade-929f-138614c30044) | ![Screen Shot 2023-08-17 at 1 24 00 PM](https://github.com/metabase/metabase/assets/30528226/b6e3e8cd-4339-4459-a79c-dc9c5d618011)
stats (sample db) | ![Screen Shot 2023-08-17 at 1 27 29 PM](https://github.com/metabase/metabase/assets/30528226/9459d0bb-8649-4969-a355-7c318b6596da) | ![Screen Shot 2023-08-17 at 1 26 56 PM](https://github.com/metabase/metabase/assets/30528226/9033435d-0ade-4cf5-b7cb-a39d19920e94)

**Comment by iethree** [comment] 2023-08-21 16:33
since this is confirmed working now, closing it, and moving the formatting options issue to this P3 issue: https://github.com/metabase/metabase/issues/33377

**Closed by iethree** 2023-08-21 16:33 UTC
Labels: Type:Bug, Priority:P1, .Frontend, Querying/Models, .Team/PixelPolice :police_officer:
