### ISSUE TITLE
Results with slash can break JSON parser for pulses as it's intepreted as comments

### ISSUE THREAD

**Issue by kaushiksa** [metabase/metabase#14450] opened 2021-01-19 11:44 UTC
When creating a pulse from a question that has query as below:

` SELECT 
  CAST(
    "This is an auto generated mail. For more information checkout the dashboard at " AS NCHAR
  ) AS "",
  CAST(
    "http:\/\/abcd.efgh.com:3000\/public\/dashboard\/1c1c7b19-027d-4481-86e6-096d45181526 " AS NCHAR
  ) AS "" ;
`

The result would load in the question's page, but will get infinitely stuck in the pulse's page. Sending mail also fails for the same.

Metabase Logs:

{:via
 [{:type com.fasterxml.jackson.core.JsonParseException,
   :message
   "Unexpected character ('/' (code 47)): maybe a (non-standard) comment? (not recognized as one since Feature 'ALLOW_COMMENTS' not enabled for parser)\n at [Source: (StringReader); line: 1, column: 2]",
   :at [com.fasterxml.jackson.core.JsonParser _constructError "JsonParser.java" 1840]}],
 :trace
 [[com.fasterxml.jackson.core.JsonParser _constructError "JsonParser.java" 1840]
  [com.fasterxml.jackson.core.base.ParserMinimalBase _reportError "ParserMinimalBase.java" 712]
  [com.fasterxml.jackson.core.base.ParserMinimalBase _reportUnexpectedChar "ParserMinimalBase.java" 637]
  [com.fasterxml.jackson.core.json.ReaderBasedJsonParser _skipComment "ReaderBasedJsonParser.java" 2436]
  [com.fasterxml.jackson.core.json.ReaderBasedJsonParser _skipWSOrEnd2 "ReaderBasedJsonParser.java" 2411]
  [com.fasterxml.jackson.core.json.ReaderBasedJsonParser _skipWSOrEnd "ReaderBasedJsonParser.java" 2362]
  [com.fasterxml.jackson.core.json.ReaderBasedJsonParser nextToken "ReaderBasedJsonParser.java" 672]
  [cheshire.parse$parse invokeStatic "parse.clj" 90]
  [cheshire.parse$parse invoke "parse.clj" 88]
  [cheshire.core$parse_string invokeStatic "core.clj" 208]
  [cheshire.core$parse_string invoke "core.clj" 194]
  [cheshire.core$parse_string invokeStatic "core.clj" 204]
  [cheshire.core$parse_string invoke "core.clj" 194]
  [clojure.core$comp$fn__5807 invoke "core.clj" 2569]
  [clojure.core$comp$fn__5807 invoke "core.clj" 2569]
  [medley.core$map_keys$fn__1769$fn__1770 invoke "core.cljc" 103]
  [clojure.core$fn__8429$fn__8431 invoke "core.clj" 6840]
  [clojure.core.protocols$iter_reduce invokeStatic "protocols.clj" 49]
  [clojure.core.protocols$fn__8140 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8140 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8088$G__8083__8101 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6828]
  [clojure.core$fn__8429 invokeStatic "core.clj" 6830]
  [clojure.core$fn__8429 invoke "core.clj" 6830]
  [clojure.core.protocols$fn__8167$G__8162__8176 invoke "protocols.clj" 175]
  [clojure.core$reduce_kv invokeStatic "core.clj" 6856]
  [clojure.core$reduce_kv invoke "core.clj" 6847]
  [medley.core$reduce_map invokeStatic "core.cljc" 84]
  [medley.core$reduce_map invoke "core.cljc" 81]
  [medley.core$map_keys invokeStatic "core.cljc" 103]
  [medley.core$map_keys invoke "core.cljc" 100]
  [metabase.pulse.render.body$column_name invokeStatic "body.clj" 71]
  [metabase.pulse.render.body$column_name invoke "body.clj" 67]
  [metabase.pulse.render.body$query_results__GT_header_row$iter__48452__48456$fn__48457 invoke "body.clj" 86]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5402 invokeStatic "core.clj" 137]
  [clojure.core$seq__5402 invoke "core.clj" 137]
  [metabase.pulse.render.table$render_table_head$iter__48293__48297$fn__48298 invoke "table.clj" 83]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5402 invokeStatic "core.clj" 137]
  [clojure.core$map$fn__5866 invoke "core.clj" 2746]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5402 invokeStatic "core.clj" 137]
  [clojure.core$apply invokeStatic "core.clj" 660]
  [clojure.core$apply invoke "core.clj" 660]
  [hiccup.compiler$fn__47641 invokeStatic "compiler.clj" 88]
  [hiccup.compiler$fn__47641 invoke "compiler.clj" 82]
  [hiccup.compiler$fn__47624$G__47619__47629 invoke "compiler.clj" 68]
  [clojure.core$map$fn__5866 invoke "core.clj" 2753]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5402 invokeStatic "core.clj" 137]
  [clojure.core$apply invokeStatic "core.clj" 660]
  [clojure.core$apply invoke "core.clj" 660]
  [hiccup.compiler$fn__47641 invokeStatic "compiler.clj" 88]
  [hiccup.compiler$fn__47641 invoke "compiler.clj" 82]
  [hiccup.compiler$fn__47624$G__47619__47629 invoke "compiler.clj" 68]
  [hiccup.compiler$render_element invokeStatic "compiler.clj" 78]
  [hiccup.compiler$render_element invoke "compiler.clj" 72]
  [hiccup.compiler$fn__47639 invokeStatic "compiler.clj" 85]
  [hiccup.compiler$fn__47639 invoke "compiler.clj" 82]
  [hiccup.compiler$fn__47624$G__47619__47629 invoke "compiler.clj" 68]
  [clojure.core$map$fn__5866 invoke "core.clj" 2753]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5402 invokeStatic "core.clj" 137]
  [clojure.core$apply invokeStatic "core.clj" 660]
  [clojure.core$apply invoke "core.clj" 660]
  [hiccup.compiler$fn__47641 invokeStatic "compiler.clj" 88]
  [hiccup.compiler$fn__47641 invoke "compiler.clj" 82]
  [hiccup.compiler$fn__47624$G__47619__47629 invoke "compiler.clj" 68]
  [hiccup.compiler$render_element invokeStatic "compiler.clj" 78]
  [hiccup.compiler$render_element invoke "compiler.clj" 72]
  [hiccup.compiler$fn__47639 invokeStatic "compiler.clj" 85]
  [hiccup.compiler$fn__47639 invoke "compiler.clj" 82]
  [hiccup.compiler$fn__47624$G__47619__47629 invoke "compiler.clj" 68]
  [clojure.core$map$fn__5866 invoke "core.clj" 2753]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5402 invokeStatic "core.clj" 137]
  [clojure.core$apply invokeStatic "core.clj" 660]
  [clojure.core$apply invoke "core.clj" 660]
  [hiccup.compiler$fn__47641 invokeStatic "compiler.clj" 88]
  [hiccup.compiler$fn__47641 invoke "compiler.clj" 82]
  [hiccup.compiler$fn__47624$G__47619__47629 invoke "compiler.clj" 68]
  [hiccup.compiler$render_element invokeStatic "compiler.clj" 78]
  [hiccup.compiler$render_element invoke "compiler.clj" 72]
  [hiccup.compiler$fn__47639 invokeStatic "compiler.clj" 85]
  [hiccup.compiler$fn__47639 invoke "compiler.clj" 82]
  [hiccup.compiler$fn__47624$G__47619__47629 invoke "compiler.clj" 68]
  [clojure.core$map$fn__5866 invoke "core.clj" 2753]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5402 invokeStatic "core.clj" 137]
  [clojure.core$apply invokeStatic "core.clj" 660]
  [clojure.core$apply invoke "core.clj" 660]
  [hiccup.compiler$fn__47641 invokeStatic "compiler.clj" 88]
  [hiccup.compiler$fn__47641 invoke "compiler.clj" 82]
  [hiccup.compiler$fn__47624$G__47619__47629 invoke "compiler.clj" 68]
  [hiccup.compiler$render_element invokeStatic "compiler.clj" 78]
  [hiccup.compiler$render_element invoke "compiler.clj" 72]
  [hiccup.compiler$fn__47639 invokeStatic "compiler.clj" 85]
  [hiccup.compiler$fn__47639 invoke "compiler.clj" 82]
  [hiccup.compiler$fn__47624$G__47619__47629 invoke "compiler.clj" 68]
  [clojure.core$map$fn__5866 invoke "core.clj" 2755]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5402 invokeStatic "core.clj" 137]
  [clojure.core$apply invokeStatic "core.clj" 660]
  [clojure.core$apply invoke "core.clj" 660]
  [hiccup.compiler$fn__47641 invokeStatic "compiler.clj" 88]
  [hiccup.compiler$fn__47641 invoke "compiler.clj" 82]
  [hiccup.compiler$fn__47624$G__47619__47629 invoke "compiler.clj" 68]
  [clojure.core$map$fn__5866 invoke "core.clj" 2753]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5402 invokeStatic "core.clj" 137]
  [clojure.core$apply invokeStatic "core.clj" 660]
  [clojure.core$apply invoke "core.clj" 660]
  [hiccup.compiler$fn__47641 invokeStatic "compiler.clj" 88]
  [hiccup.compiler$fn__47641 invoke "compiler.clj" 82]
  [hiccup.compiler$fn__47624$G__47619__47629 invoke "compiler.clj" 68]
  [hiccup.compiler$render_element invokeStatic "compiler.clj" 78]
  [hiccup.compiler$render_element invoke "compiler.clj" 72]
  [hiccup.compiler$fn__47639 invokeStatic "compiler.clj" 85]
  [hiccup.compiler$fn__47639 invoke "compiler.clj" 82]
  [hiccup.compiler$fn__47624$G__47619__47629 invoke "compiler.clj" 68]
  [clojure.lang.Var invoke "Var.java" 384]
  [metabase.api.pulse$fn__70168 invokeStatic "pulse.clj" 175]
  [metabase.api.pulse$fn__70168 invoke "pulse.clj" 168]
  [compojure.core$wrap_response$fn__1993 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__1977 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__1982 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 151]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [metabase.middleware.auth$enforce_authentication$fn__72912 invoke "auth.clj" 14]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2033 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 296]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [metabase.api.routes$fn__73033$fn__73035 invoke "routes.clj" 73]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 665]
  [clojure.core$apply invoke "core.clj" 660]
  [metabase.routes$fn__74362$fn__74363 doInvoke "routes.clj" 60]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2033 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 296]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [metabase.routes$fn__74350$fn__74352 invoke "routes.clj" 44]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [metabase.middleware.exceptions$catch_uncaught_exceptions$fn__73024 invoke "exceptions.clj" 96]
  [metabase.middleware.exceptions$catch_api_exceptions$fn__73021 invoke "exceptions.clj" 84]
  [metabase.middleware.log$log_api_call$fn__74810$fn__74811 invoke "log.clj" 197]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.middleware.log$log_api_call$fn__74810 invoke "log.clj" 191]
  [metabase.middleware.security$add_security_headers$fn__72987 invoke "security.clj" 143]
  [metabase.middleware.json$wrap_json_body$fn__74513 invoke "json.clj" 64]
  [metabase.middleware.json$wrap_streamed_json_response$fn__74531 invoke "json.clj" 100]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__75076 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__75092 invoke "params.clj" 69]
  [metabase.middleware.misc$maybe_set_site_url$fn__34513 invoke "misc.clj" 59]
  [metabase.middleware.session$bind_current_user$fn__69491$fn__69492 invoke "session.clj" 278]
  [metabase.middleware.session$do_with_current_user invokeStatic "session.clj" 260]
  [metabase.middleware.session$do_with_current_user invoke "session.clj" 252]
  [metabase.middleware.session$bind_current_user$fn__69491 invoke "session.clj" 277]
  [metabase.middleware.session$wrap_current_user_info$fn__69478 invoke "session.clj" 238]
  [metabase.middleware.session$wrap_session_id$fn__69464 invoke "session.clj" 184]
  [metabase.middleware.auth$wrap_api_key$fn__72920 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__74996 invoke "cookies.clj" 216]
  [metabase.middleware.misc$add_content_type$fn__34498 invoke "misc.clj" 28]
  [metabase.middleware.misc$disable_streaming_buffering$fn__34521 invoke "misc.clj" 76]
  [ring.middleware.gzip$wrap_gzip$fn__75038 invoke "gzip.clj" 86]
  [metabase.middleware.misc$bind_request$fn__34524 invoke "misc.clj" 93]
  [metabase.middleware.ssl$redirect_to_https_middleware$fn__74827 invoke "ssl.clj" 39]
  [metabase.server$async_proxy_handler$fn__74588 invoke "server.clj" 72]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 383]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 556]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 375]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 273]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 336]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 313]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 171]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 129]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 375]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 773]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 905]
  [java.lang.Thread run "Thread.java" 748]],
 :cause
 "Unexpected character ('/' (code 47)): maybe a (non-standard) comment? (not recognized as one since Feature 'ALLOW_COMMENTS' not enabled for parser)\n at [Source: (StringReader); line: 1, column: 2]",
 :message
 "Unexpected character ('/' (code 47)): maybe a (non-standard) comment? (not recognized as one since Feature 'ALLOW_COMMENTS' not enabled for parser)\n at [Source: (StringReader); line: 1, column: 2]",
 :type com.fasterxml.jackson.core.JsonParseException}
 
 
 Image :  
 
 
![image](https://user-images.githubusercontent.com/31251013/105029227-0f0cbb00-5a78-11eb-8dcc-568a5fdbb885.png)

Steps to reproduce: 

1. Add a question with a static query as above.
2. Create a pulse with the question

Metabase information : 
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_252-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_252",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.252-b09",
    "os.name": "Linux",
    "os.version": "3.10.0-1127.10.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Kolkata"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.20"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.37.6",
      "date": "2021-01-13",
      "branch": "release-x.37.x",
      "hash": "344e5e0"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

Severity : Moderate (Since there is no option to customize pulse mail, ability to add such information as query would help)

Additional Information:

I also tried using a single string as select in the query. But when i add the question in pulse, the string would appear in bold and in a big font which would not be pleasing in a mail.

**Comment by flamber** [comment] 2021-01-19 12:34
Hi @kaushiksa 
Change `\/` to `/`, then it will work, but not like you have intended to use it - you will be interested in #14211 and #6659 and #3315

**Comment by kaushiksa** [comment] 2021-01-19 14:02
Hi @flamber ,
Thanks for the reply. I did try with that. It still does not work.

**Comment by flamber** [comment] 2021-01-19 14:48
@kaushiksa Okay, are you seeing the same error?
Try using Java 11: https://www.metabase.com/docs/latest/operations-guide/java-versions.html

**Comment by kaushiksa** [comment] 2021-01-20 07:33
@flamber Updated Java to the below . Still getting the same error.

java -version
openjdk version "11.0.9" 2020-10-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.9+11-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9+11-LTS, mixed mode, sharing)

**Comment by flamber** [comment] 2021-01-20 09:27
@kaushiksa Please check "Diagnostic Info" from Admin > Troubleshooting to make sure that Metabase is started with Java 11.
I cannot reproduce querying MySQL 8.0.20. I've only seen this error querying MongoDB #11786.
Try giving the columns a unique name:
```
SELECT "This is an auto generated mail. For more information checkout the dashboard at " AS ".", "http://abcd.efgh.com:3000/public/dashboard/1c1c7b19-027d-4481-86e6-096d45181526" AS ".."
```

**Comment by kaushiksa** [comment] 2021-01-20 09:42
@flamber  Metabase information shows the below. (It is using java 11)

[31f09c74-b1c6-4a03-bb53-f7072734951d] 2021-01-20T12:46:36+05:30 INFO metabase.core Starting Metabase version v0.37.6 (344e5e0 release-x.37.x) ...
[31f09c74-b1c6-4a03-bb53-f7072734951d] 2021-01-20T12:46:36+05:30 INFO metabase.core System info:
 {"file.encoding" "UTF-8",
 "java.runtime.name" "OpenJDK Runtime Environment",
 "java.runtime.version" "11.0.9+11-LTS",
 "java.vendor" "Red Hat, Inc.",
 "java.vendor.url" "https://www.redhat.com/",
 "java.version" "11.0.9",
 "java.vm.name" "OpenJDK 64-Bit Server VM",
 "java.vm.version" "11.0.9+11-LTS",
 "os.name" "Linux",
 "os.version" "3.10.0-1127.10.1.el7.x86_64",
 "user.language" "en",
 "user.timezone" "Asia/Kolkata"}

I tried with your query too. It still does not load for me

**Comment by flamber** [comment] 2021-11-10 12:29
Closing, as it is now possible to include Textbox comments in Dashboard Subscriptions:
https://www.metabase.com/docs/latest/users-guide/dashboard-subscriptions.html
And most of the visualization rendering has been completely updated.

If anyone is still experiencing this issue, then include "Diagnostic Info" from Admin > Troubleshooting, and the full stacktrace from Admin > Troubleshooting > Logs, and the steps-to-reproduce.

**Closed by flamber** 2021-11-10 12:29 UTC
Labels: Type:Bug, Priority:P3, Reporting/Pulses, .Unable to Reproduce
