### ISSUE TITLE
Date filter is not working on time series questions on dashboards where the filter is linked to charts with different source.

### ISSUE THREAD

**Issue by SrancsikAtBitrise** [metabase/metabase#9635] opened 2019-03-29 12:04 UTC
OS: macOS 10.14.3
Browser: Chrome 73.0.3683.86
Data source: Heroku Postgres
Metabase: 0.31.2
Metabase is hosted on Heroku
Metabase internal database is Heroku Postgres

Time series charts are not shown at all when a date filter is linked on a dashboard to attributes from other tables.
The questions work properly but once added to a dashboard where 

- there are charts based on one or more different tables
- and date filter is linked to the date attribute presented in the question 

the chart goes empty. Even the name of it is shown only as "Count" on line and area charts (but not on tables).
The issue exists even we add a new date filter linked only to the time series chart and not to the ones based on another table.

The same happens with both area and line charts but not with tables. Pie charts (where the date is only a filter) works properly as well.

When all the charts are based on the same table there is no issue. We experience it only when charts from created from different tables are used.

When clicking on the head of the broken chart it opens it as a "New question" not the existing one.

![Screenshot 2019-03-29 at 12 32 05](https://user-images.githubusercontent.com/39155393/55230503-49142980-5220-11e9-97c1-c24595030e92.png)

![Screenshot 2019-03-29 at 12 46 04](https://user-images.githubusercontent.com/39155393/55231341-98f3f000-5222-11e9-8629-1873a922b366.png)

**Comment by salsakran** [comment] 2019-04-10 03:47
@SrancsikAtBitrise can you give us a specific reproduction using the sample dataset? 

This doesn't seem to happen on our test instances.

**Comment by SrancsikAtBitrise** [comment] 2019-04-12 11:05
Actually, I have updated Metabase to ver 0.32.
But you are right, it is not related to the tables linked to the filter.

It is an issue with the presentation of line graphs in case there are no results.

When there is a table with no results the title is shown. Line charts with no results: the title says "Count".

![Screenshot 2019-04-12 at 12 57 34](https://user-images.githubusercontent.com/39155393/56032836-6a4a3f00-5d23-11e9-9b6b-51c177a58dc2.png)
![Screenshot 2019-04-12 at 13 01 55](https://user-images.githubusercontent.com/39155393/56032838-6ae2d580-5d23-11e9-9e5b-d10448e5b6af.png)

**Comment by flamber** [comment] 2019-04-12 14:17
I'm pretty sure this is a duplicate of #6765 - if yes, then please close this issue and upvote by clicking :+1:

**Closed** 2019-04-12 23:01 UTC
Labels: Bug, Dashboards, Parameters/Variables, Priority/P3
