### ISSUE TITLE
Schema sync does not update changes in column type case

### ISSUE THREAD

**Issue by pajachiet** [metabase/metabase#7923] opened 2018-06-22 09:51 UTC
# Bugs
- Your databases: Postgres
- Metabase version: v0.29.3
- Metabase hosting environment: Docker
- Metabase internal database: H2 (default)

# Repeatable steps to reproduce the issue
- Create a table in PostgreSQL
`create table test_table( test_column integer);
`

- Sync the schema in Metabase
- Change column case
`ALTER TABLE public.test_table RENAME COLUMN test_column TO "Test_column";`

- And optionnaly also add a new column
`ALTER TABLE public.test_table ADD column_2 int NULL;`

- Sync the schema in Metabase. 
- Look at the raw schema in the data model => **the case of column test_column as not been updated**, where as column_2 is recognized

This also produce the following error
- Try to create a question to get raw data from test_table : this raise the following error in Metabase.

`org.postgresql.util.PSQLException: ERROR: column test_table.test_column does not exist Hint: Perhaps you meant to reference the column "test_table.Test_column". Position: 124
`

- PostgreSQL log which shows that schema was not updated

```
2018-06-22 09:40:10.542 UTC [11110] ERROR:  column test_table.test_column does not exist at character 124
2018-06-22 09:40:10.542 UTC [11110] HINT:  Perhaps you meant to reference the column "test_table.Test_column".
2018-06-22 09:40:10.542 UTC [11110] STATEMENT:  -- Metabase:: userID: 1 queryType: MBQL queryHash: 3d0ad5f33075363456e9f4fc46694ed88f1552e8cce125bbc6c513ed8b0c6ffb
	SELECT "public"."test_table"."test_column" AS "test_column" FROM "public"."test_table" LIMIT 2000
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by ebrett** [comment] 2018-06-24 11:10
I have the same issue, but with a view.

**Comment by kuppa-riptlabs** [comment] 2018-10-25 01:35
We are also seeing the similar issue, changed one of the ID column from int8 to UUID.  The schema is not re-synching hence our dashboard is broken.  
Is anyone working on this issue, do we have any ETA?
Is there any workaround to resolve this issue, something like changing the data directly on the table?

**Comment by Oberonhive** [comment] 2019-02-04 17:53
Same issue. When column case changed in DB it's impossible to update it in metabase.

**Comment by camsaul** [comment] 2019-02-05 20:04
Column names for most databases are case-sensitive so Metabase thinks you've added a new column rather than changed and existing one

**Comment by cqcn1991** [comment] 2019-08-07 07:18
same issue here.

**Comment by nigelainscoe** [comment] 2019-08-19 11:05
Same problem here. Changing PostCode to Postcode in a Snowflake data warehouse has broken all the things.

**Comment by jacobr2009** [comment] 2019-09-06 20:44
We are seeing the same issue in Snowflake

**Comment by sbelak** [comment] 2019-09-07 08:27
@nigelainscoe, @jacobr2009 on which version of Metabase are you?

**Comment by vvaezian** [comment] 2019-10-10 02:00
Had the same issue in 0.33.3. As a workaround I transferred the data to a new table with the desired column names and deleted the old one.

**Comment by billjwilliamson** [comment] 2020-06-23 07:52
Refresh the webpage

**Comment by vvaezian** [comment] 2020-10-02 18:18
The issue is that the column name doesn't get updated in the internal DB of Metabase because it probably does a cases-insensetive search for column name, and it sees that the column name is already there, so it thinks no change is needed.  

A workaround is to update the value manually in the internal DB of Metabase:
```sql
--- find the id of the table
select id 
from metabase_table
where name = [my_table_name]

-- update the column name
update metabase_field
set name = [new_col_name], display_name=[new_col_name]
where table_id = [the_id_found_from_previous_step]
and name = [current_col_name]
```

**Comment by jankatins** [comment] 2020-12-17 21:09
I did a bit of digging (could be wrong findings, as I can't really read clojure...):

* Where it figures out if a field is new: https://github.com/metabase/metabase/blob/2a0683bc3dcf1b3e11e41d073c84bac71b3ddce5/src/metabase/sync/sync_metadata/fields/sync_instances.clj#L103-L106

* Where "canonical_name" is ignoring cases: https://github.com/metabase/metabase/blob/2a0683bc3dcf1b3e11e41d073c84bac71b3ddce5/src/metabase/sync/sync_metadata/fields/common.clj#L38 

This canonical name seems to have been introduced in this commit: https://github.com/metabase/metabase/commit/a133aba4588718e5a450eb0ddbc97aa0110e04b2 but the lower comparison seems to go back to https://github.com/metabase/metabase/commit/206c1430e22e688953872bf34f7de704e2e80048#diff-fcbc67149f48554b35e85208009bc7cd27be9a752357f774eee1e652cbe0f9baR107-R108 (by @camsaul) which replaced this code which does not contain the lowering, as far as I can make out: https://github.com/metabase/metabase/blob/99121ef2916bfdb4012da7607919abeb41c95dbe/src/metabase/db/migrations.clj#L188-L206

Unfortunately, no clues why lower is needed near any of these places.  Probably because other DBs than pg will have case insensitive column names?

**Closed** 2021-03-19 14:29 UTC
Labels: Administration/Metadata & Sync, Type:Bug
