### ISSUE TITLE
Translations marked as "fuzzy" in POEditor are not translated in UI

### ISSUE THREAD

**Issue by LucasSegersFabro** [metabase/metabase#14581] opened 2021-01-29 03:25 UTC
### Current Behavior
On a dashboard with an "all options" date filter and the Language set to Portuguese, the first option is not translated (Previous).  
Also makes the Embedded dashboard default value (on which Year was selected) to be half translated: "Previous Ano" or "Previous Mês".   

### Desired Behavior
The all options date filter should have the "Previous" date selection translated, like "Ano Anterior" or "Mês Anterior".   

### Prints

![image](https://user-images.githubusercontent.com/29109459/106227688-66253500-61c8-11eb-88a7-2ae07b3ee88f.png)

![image](https://user-images.githubusercontent.com/29109459/106227709-75a47e00-61c8-11eb-8e81-c69ceeb7adbe.png)

Will take some time to understand how translation works within the project, so that on the next time I can open a PR myself, sorry about that :(

**Comment by flamber** [comment] 2021-01-29 14:05
Not sure why it's not translated - it is translated in https://poeditor.com/join/project/ynjQmwSsGh but it was set to **fuzzy**, and when I check the other fuzzy strings, then they seem to not be correct either - example "Save" button in many dialogs:
![image](https://user-images.githubusercontent.com/1447303/106283556-619d6280-6242-11eb-9d11-cbf696bfd3fe.png)

Changing priority to P2, since this affects 176 strings in all translations. This might be the cause of other translation issues.
It might be a backend issue in how the PO-files are read.
@mazameli Have you noticed this?

**Comment by mazameli** [comment] 2021-02-02 00:01
Interesting. No, I had not noticed this, @flamber. I wonder what's causing these strings to get marked as fuzzy. I'll poke around POEditor to see if I can spot a pattern/reason.

**Comment by flamber** [comment] 2021-02-02 10:39
@mazameli I think it's the translators that mark those manually as fuzzy, when the translation isn't completely correct, but it's the best they can do. Like some languages would word things differently, but the string is used in a way, where it's reused multiple places in the English version.

**Comment by mazameli** [comment] 2021-02-02 16:52
Hmm, I think you're right that all fuzzy strings aren't showing up correctly translated, though oddly that save button looks translated to me on master on the account page, but not on the new DB form page (screenshots below).

I'm wondering if the way we implement translations ignores strings marked as fuzzy. Any idea @camsaul or @paulrosenzweig?

E.g., the `Save` string looks like this in the portuguese po file, with a `#, fuzzy` tag:

```
#: enterprise/frontend/src/metabase-enterprise/sandboxes/components/GTAPModal.jsx:253
#: frontend/src/metabase/admin/databases/containers/DatabaseEditApp.jsx:175
#: frontend/src/metabase/admin/datamodel/components/FieldRemapping.jsx:428
#: frontend/src/metabase/admin/permissions/containers/CollectionPermissionsModal.jsx:106
#: frontend/src/metabase/admin/settings/components/widgets/GroupMappingsWidget.jsx:209
#: frontend/src/metabase/components/ActionButton.jsx:51
#: frontend/src/metabase/components/ButtonWithStatus.jsx:7
#: frontend/src/metabase/containers/SaveQuestionModal.jsx:153
#: frontend/src/metabase/dashboard/components/DashboardHeader.jsx:172
#: frontend/src/metabase/query_builder/components/template_tags/SnippetModal.jsx:46
#: frontend/src/metabase/query_builder/components/view/EditQuestionInfoModal.jsx:15
#: frontend/src/metabase/query_builder/components/view/ViewHeader.jsx:213
#: frontend/src/metabase/reference/components/EditHeader.jsx:54
#: frontend/src/metabase/reference/components/EditHeader.jsx:69
#: frontend/src/metabase/user/components/SetUserPassword.jsx:30
#, fuzzy
msgid "Save"
msgstr "Salvar"
```

---

![image](https://user-images.githubusercontent.com/2223916/106632589-c7d00100-6532-11eb-9967-880c64bd32dc.png)

DB form:

![image](https://user-images.githubusercontent.com/2223916/106632754-f2ba5500-6532-11eb-8bc9-3bc70c2582a4.png)

**Comment by flamber** [comment] 2021-02-02 17:21
`Atualizar` => `Update`, whereas if you click "Senha"-tab, then you'll see `Save` button.

**Comment by phsantiago** [comment] 2021-02-21 17:03
@flamber @mazameli is [this line](https://github.com/metabase/metabase/blob/master/src/metabase/pulse/render/datetime.clj#L113) related to the error?

**Comment by flamber** [comment] 2021-02-21 17:06
@phsantiago No, the problem is much larger than any single strings - it's all translations marked as "fuzzy" in POEditor.

**Closed** 2021-03-17 21:13 UTC
Labels: Customization/i18n, Priority:P2, Type:Bug
