### ISSUE TITLE
Scalar with prefix and/or suffix is not sized correctly in dashboard

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#24014] opened 2022-07-15 17:38 UTC
**Describe the bug**
If you save a question with a scalar numerical value, add it to a dashboard, and then a long suffix or prefix to the number using visualization settings, the value will not be sized correctly for the dashcard.

**To Reproduce**
1. Create and save a scalar question like `select 1;`
2. Add the question to a dashboard
3. On the dashcard, click "visualization options"
4. Add a very long prefix and/or suffix and save
5. The value should now overflow the card 

**Expected behavior**
The entire value should be resized to fit the card so it's visible and/or the added text should wrap.

**Screenshots**
![image](https://user-images.githubusercontent.com/32746338/179279195-cca9befb-f731-44d7-afec-7fc51d889ef3.png)

**Comment by MuriloAmarals** [comment] 2022-07-15 21:11
Hey @noahmoss , could you add a Loom Video showing the bug ?

**Comment by flamber** [comment] 2022-07-21 16:11
Duplicate of #23093

**Closed by flamber** 2022-07-21 16:11 UTC
Labels: Type:Bug, .Needs Triage
