### ISSUE TITLE
Changing the filter type in the filter settings panel

### ISSUE THREAD

**Issue by nomorethat** [metabase/metabase#29385] opened 2023-03-21 08:57 UTC
**Is your feature request related to a problem? Please describe.**
My team and I have made a feature that allows you to change the filter type in the filter settings panel (ParameterSidebar). 
Motivation: When adding a new filter, if I make a mistake, the only way to change the filter type is to delete the existing filter and create a new one. It's not very convenient =). We want to be able to change the filter type in the filter settings panel =).

**Describe the solution you'd like**
Example
1) I made a mistake and added the "Month and Year" filter (1)
2) Linked the filter to the card (2)
3) Set the default value... and I realized that I was wrong (3)
4) Changed the filter type in the filter settings panel to the "Single Date" filter (4)(5)
5) The filter type has changed (6)
6) The default value has been reset (7)

**Describe alternatives you've considered**
I did it as a RadioGroup component, but it can also be a dropdown.

**How important is this feature to you?**
Greater user experience ;)

**Additional context**
![ksnip_20230321-111649](https://user-images.githubusercontent.com/46302088/226557400-61e4dc06-a99c-464b-b944-f9de5a7bd206.png)

![ksnip_20230321-111821](https://user-images.githubusercontent.com/46302088/226557406-2d429e0a-4c73-441e-a381-c079c39de880.png)

Best regards ;)

**Comment by paoliniluis** [comment] 2023-03-29 22:32
Thanks, why don't you contribute to the project and merge it?

**Comment by paoliniluis** [comment] 2023-03-29 22:33
BTW: this is a duplicate of https://github.com/metabase/metabase/issues/14296

**Closed by paoliniluis** 2023-03-29 22:33 UTC
Labels: Type:New Feature, .Needs Triage
