### ISSUE TITLE
[new sql search]The value of the query result is displayed abnormally  

### ISSUE THREAD

**Issue by Enderyu** [metabase/metabase#41624] opened 2024-04-19 08:35 UTC
### Describe the bug

![image](https://github.com/metabase/metabase/assets/18453612/eec86254-219b-47b6-997b-611c997167bb)

example:
Incorrect id display:1474863126805505000

Correct id display:1474863126805505024	

If the value is too large, the last two digits are automatically converted to 00 , The data cannot be used correctly

### To Reproduce

1. Go to SQL query page，http://127.0.0.1:3000/question
2.Input SQL
3. click search

### Expected behavior

![image](https://github.com/metabase/metabase/assets/18453612/d2ef50af-8c42-46ac-b408-f40dc4c1b670)

Correct display

### Information about your Metabase installation

```JSON
Chrome 124.0.6367.60(arm64)

clickhouse

clickhouse.metabase-driver.jar 1.4.0
```

### Severity

Very serious

**Comment by paoliniluis** [comment] 2024-04-22 07:34
duplicate of https://github.com/metabase/metabase/issues/5816

**Closed by paoliniluis** 2024-04-22 07:34 UTC
Labels: Type:Bug, .Needs Triage
