### ISSUE TITLE
Ability to change first day of the week

### ISSUE THREAD

**Issue by benjR** [metabase/metabase#5171] opened 2017-05-23 08:22 UTC
Would it be possible to specify the day on which the week starts at the admin level for all requests based on dates (filters, group by, ...) ?

In Europe, Asia, Oceania and according to ISO-8601, the first day of the week is Monday, so it's kind of an issue for us at the moment on metabase making it difficult to compare with data from other sources.
I guess it would also be an issue for other countries, in the middle east, the first day of the week is saturday : https://en.wikipedia.org/wiki/Week#Week_numbering

Made a really quick mockup of how it could look (near the timezone selection):
![firstdayoftheweek](https://cloud.githubusercontent.com/assets/1074675/26344570/6dd2c3ba-3fa0-11e7-8a7b-b6fa99a19648.png)

Thanks!

**Comment by mazameli** [comment] 2017-05-23 17:24
This is a duplicate of https://github.com/metabase/metabase/issues/1779.

I think that's a pretty reasonable place to put the setting, incidentally.

**Closed by mazameli** 2017-05-23 17:24 UTC
Labels: Duplicate
