### ISSUE TITLE
Not possible to restore Visibility after setting "Do Not Include" in Data Model

### ISSUE THREAD

**Issue by bhaskoro-muthohar** [metabase/metabase#14194] opened 2020-12-24 13:59 UTC
**Describe the bug**
I accidentally clicked to hide my table and then I realize that I'm unable to restore it by clicking the `eyes button` and the `Quaryable button`

**Logs**
```bash
2020-12-24 21:52:15,158 DEBUG middleware.log :: GET /api/database/2/metadata 200 107.0 ms (7 DB calls) App DB connections: 3/15 Jetty threads: 5/50 (10 idle, 0 queued) (62 total active threads) Queries in flight: 0 (0 queued)
2020-12-24 21:52:17,484 ERROR middleware.log :: PUT /api/table/5 500 2.1 s (2 DB calls)
{:via
 [{:type org.h2.jdbc.JdbcSQLException,
   :message "Timeout trying to lock table ; SQL statement:\nUPDATE \"METABASE_TABLE\" SET \"VISIBILITY_TYPE\" = NULL, \"UPDATED_AT\" = now() WHERE \"ID\" = 5 [50200-197]",
   :at [org.h2.message.DbException getJdbcSQLException "DbException.java" 357]}
  {:type org.h2.jdbc.JdbcSQLException,
   :message "Concurrent update in table \"METABASE_TABLE\": another transaction has updated or deleted the same row [90131-197]",
   :at [org.h2.message.DbException getJdbcSQLException "DbException.java" 357]}
  {:type java.lang.IllegalStateException, :message "Entry is locked [1.4.197/101]", :at [org.h2.mvstore.DataUtils newIllegalStateException "DataUtils.java" 870]}],
 :trace
 [[org.h2.mvstore.DataUtils newIllegalStateException "DataUtils.java" 870]
  [org.h2.mvstore.db.TransactionStore$TransactionMap set "TransactionStore.java" 1067]
  [org.h2.mvstore.db.TransactionStore$TransactionMap remove "TransactionStore.java" 1026]
  [org.h2.mvstore.db.MVSecondaryIndex remove "MVSecondaryIndex.java" 246]
  [org.h2.mvstore.db.MVTable removeRow "MVTable.java" 706]
  [org.h2.table.Table updateRows "Table.java" 490]
  [org.h2.command.dml.Update update "Update.java" 177]
  [org.h2.command.CommandContainer update "CommandContainer.java" 102]
  [org.h2.command.Command executeUpdate "Command.java" 261]
  [org.h2.jdbc.JdbcPreparedStatement executeUpdateInternal "JdbcPreparedStatement.java" 199]
  [org.h2.jdbc.JdbcPreparedStatement executeUpdate "JdbcPreparedStatement.java" 153]
  [com.mchange.v2.c3p0.impl.NewProxyPreparedStatement executeUpdate "NewProxyPreparedStatement.java" 462]
  [clojure.java.jdbc$db_do_execute_prepared_statement$fn__19170 invoke "jdbc.clj" 1049]
  [clojure.java.jdbc$db_transaction_STAR_ invokeStatic "jdbc.clj" 807]
  [clojure.java.jdbc$db_transaction_STAR_ invoke "jdbc.clj" 776]
  [clojure.java.jdbc$db_transaction_STAR_ invokeStatic "jdbc.clj" 789]
  [clojure.java.jdbc$db_transaction_STAR_ invoke "jdbc.clj" 776]
  [clojure.java.jdbc$db_do_execute_prepared_statement invokeStatic "jdbc.clj" 1048]
  [clojure.java.jdbc$db_do_execute_prepared_statement invoke "jdbc.clj" 1042]
  [clojure.java.jdbc$db_do_prepared invokeStatic "jdbc.clj" 1080]
  [clojure.java.jdbc$db_do_prepared invoke "jdbc.clj" 1060]
  [clojure.java.jdbc$execute_BANG_$execute_helper__19244 invoke "jdbc.clj" 1464]
  [clojure.java.jdbc$execute_BANG_ invokeStatic "jdbc.clj" 1468]
  [clojure.java.jdbc$execute_BANG_ invoke "jdbc.clj" 1435]
  [toucan.db$execute_BANG_ invokeStatic "db.clj" 427]
  [toucan.db$execute_BANG_ doInvoke "db.clj" 422]
  [clojure.lang.RestFn invoke "RestFn.java" 410]
  [toucan.db$update_BANG_ invokeStatic "db.clj" 482]
  [toucan.db$update_BANG_ invoke "db.clj" 471]
  [toucan.db$update_BANG_ invokeStatic "db.clj" 491]
  [toucan.db$update_BANG_ invoke "db.clj" 471]
  [metabase.api.table$update_table_BANG_ invokeStatic "table.clj" 58]
  [metabase.api.table$update_table_BANG_ invoke "table.clj" 51]
  [metabase.api.table$fn__59763 invokeStatic "table.clj" 89]
  [metabase.api.table$fn__59763 invoke "table.clj" 77]
  [compojure.core$wrap_response$fn__1993 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__1977 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__1982 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 151]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [metabase.middleware.auth$enforce_authentication$fn__72906 invoke "auth.clj" 14]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2033 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 296]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [metabase.api.routes$fn__73027$fn__73029 invoke "routes.clj" 73]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 665]
  [clojure.core$apply invoke "core.clj" 660]
  [metabase.routes$fn__74355$fn__74356 doInvoke "routes.clj" 60]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2033 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 296]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [metabase.routes$fn__74343$fn__74345 invoke "routes.clj" 44]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [metabase.middleware.exceptions$catch_uncaught_exceptions$fn__73018 invoke "exceptions.clj" 96]
  [metabase.middleware.exceptions$catch_api_exceptions$fn__73015 invoke "exceptions.clj" 84]
  [metabase.middleware.log$log_api_call$fn__74803$fn__74804 invoke "log.clj" 197]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.middleware.log$log_api_call$fn__74803 invoke "log.clj" 191]
  [metabase.middleware.security$add_security_headers$fn__72981 invoke "security.clj" 143]
  [metabase.middleware.json$wrap_json_body$fn__74506 invoke "json.clj" 64]
  [metabase.middleware.json$wrap_streamed_json_response$fn__74524 invoke "json.clj" 100]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__75069 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__75085 invoke "params.clj" 69]
  [metabase.middleware.misc$maybe_set_site_url$fn__34511 invoke "misc.clj" 59]
  [metabase.middleware.session$bind_current_user$fn__69485$fn__69486 invoke "session.clj" 278]
  [metabase.middleware.session$do_with_current_user invokeStatic "session.clj" 260]
  [metabase.middleware.session$do_with_current_user invoke "session.clj" 252]
  [metabase.middleware.session$bind_current_user$fn__69485 invoke "session.clj" 277]
  [metabase.middleware.session$wrap_current_user_info$fn__69472 invoke "session.clj" 238]
  [metabase.middleware.session$wrap_session_id$fn__69458 invoke "session.clj" 184]
  [metabase.middleware.auth$wrap_api_key$fn__72914 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__74989 invoke "cookies.clj" 216]
  [metabase.middleware.misc$add_content_type$fn__34496 invoke "misc.clj" 28]
  [metabase.middleware.misc$disable_streaming_buffering$fn__34519 invoke "misc.clj" 76]
  [ring.middleware.gzip$wrap_gzip$fn__75031 invoke "gzip.clj" 86]
  [metabase.middleware.misc$bind_request$fn__34522 invoke "misc.clj" 93]
  [metabase.middleware.ssl$redirect_to_https_middleware$fn__74820 invoke "ssl.clj" 39]
  [metabase.server$async_proxy_handler$fn__74581 invoke "server.clj" 72]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 383]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 556]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 375]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 273]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 336]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 313]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 171]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 129]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 375]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 773]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 905]
  [java.lang.Thread run "Thread.java" 748]],
 :cause "Entry is locked [1.4.197/101]",
 :message "Timeout trying to lock table ; SQL statement:\nUPDATE \"METABASE_TABLE\" SET \"VISIBILITY_TYPE\" = NULL, \"UPDATED_AT\" = now() WHERE \"ID\" = 5 [50200-197]",
 :type org.h2.jdbc.JdbcSQLException,
 :sql-exception-chain
 ["JdbcSQLException:"
  "Message: Timeout trying to lock table ; SQL statement:"
  "UPDATE \"METABASE_TABLE\" SET \"VISIBILITY_TYPE\" = NULL, \"UPDATED_AT\" = now() WHERE \"ID\" = 5 [50200-197]"
  "SQLState: HYT00"
  "Error Code: 50200"]}
```

**To Reproduce**
1. Go to Metabase Admin then Data Model
2. Click on Table and click the hide button
3. Try to click the unhide or queryable button
4. Doesn't work

**Expected behavior**
Unhide my tables

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```bash
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "ANSI_X3.4-1968",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_272-b10",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "1.8.0_272",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.272-b10",
    "os.name": "Linux",
    "os.version": "4.18.0-147.8.1.el8_1.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.37.4",
      "date": "2020-12-17",
      "branch": "release-x.37.x",
      "hash": "e0d5287"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Need urgent help!

**Comment by paoliniluis** [comment] 2020-12-24 14:11
Hi! As I'm seeing in the logs the internal H2 database that is doing the operation (unhide) has the row locked and does not let you revert the operation. Did you try again after a couple of seconds? I would truly recommend you to move to postgres or mysql as the Metabase application database as stated in the documentation (https://www.metabase.com/docs/latest/faq/setup/what-is-h2.html). Regards

**Comment by bhaskoro-muthohar** [comment] 2020-12-24 14:59
> Hi! As I'm seeing in the logs the internal H2 database that is doing the operation (unhide) has the row locked and does not let you revert the operation. Did you try again after a couple of seconds? I would truly recommend you to move to postgres or mysql as the Metabase application database as stated in the documentation (https://www.metabase.com/docs/latest/faq/setup/what-is-h2.html). Regards

Thank you, now I migrating to postgres. But seems like the issue still persists.

**Comment by paoliniluis** [comment] 2020-12-24 15:04
can you please post the logs of the application when the issue occurs now with postgres? are you seeing something in the console of the browser when trying to un-hide the table?

**Comment by bhaskoro-muthohar** [comment] 2020-12-24 15:22
> can you please post the logs of the application when the issue occurs now with postgres? are you seeing something in the console of the browser when trying to un-hide the table?

![image](https://user-images.githubusercontent.com/35159954/103096372-4b462a80-4636-11eb-8d4d-27753249333d.png)

Yes, the log in console said `Table 'table_name' is now visible. Resyncing`, I've waited for 10-20 minutes but still, nothing happened

**Comment by paoliniluis** [comment] 2020-12-24 15:24
ok, so the issue is now not on the backend or the DB but on the frontend that might not be reflecting the change, can you please refresh your browser on the page you are having the issue with ctrl+shift+r or clearing the cache? it should be showing that the table is now visible, can you please confirm?

**Comment by bhaskoro-muthohar** [comment] 2020-12-24 15:28
> ok, so the issue is now not on the backend or the DB but on the frontend that might not be reflecting the change, can you please refresh your browser on the page you are having the issue with ctrl+shift+r or clearing the cache? it should be showing that the table is now visible, can you please confirm?

![image](https://user-images.githubusercontent.com/35159954/103096690-5d749880-4637-11eb-9de5-26aee038a376.png)

Refreshed and still no luck on me

**Comment by paoliniluis** [comment] 2020-12-24 15:30
Thanks, can you please post the browser console when refreshing? I would like to see if there is an issue in the front end

**Comment by bhaskoro-muthohar** [comment] 2020-12-24 15:32
> Thanks, can you please post the browser console when refreshing? I would like to see if there is an issue in the front end

![image](https://user-images.githubusercontent.com/35159954/103096843-d70c8680-4637-11eb-99df-2c6f90c27869.png)

Here you are

**Comment by bhaskoro-muthohar** [comment] 2020-12-24 15:33
Is it possible because of the computing power of my machine? Because it only has 2 gigs ram and 1 core

**Comment by paoliniluis** [comment] 2020-12-24 16:21
I managed to replicate it locally and we'll be looking into it, in the meantime try the following: go to the postgres Metabase database and unhide the table by going to the table named 'metabase_table' and set the field 'visilbility_type' of the table you are trying to unhide to a null value. 
Be sure to back up your DB first to avoid any damages from editing your DB directly. Please report once done and let me know the results

**Comment by bhaskoro-muthohar** [comment] 2020-12-24 17:59
> I managed to replicate it locally and we'll be looking into it, in the meantime try the following: go to the postgres Metabase database and unhide the table by going to the table named 'metabase_table' and set the field 'visilbility_type' of the table you are trying to unhide to a null value.
> Be sure to back up your DB first to avoid any damages from editing your DB directly. Please report once done and let me know the results

Ok, all good! Thank you for assisting!

**Comment by nemanjaglumac** [comment] 2020-12-24 22:23
> I managed to replicate it locally and we'll be looking into it...

Can you please share the exact steps so that I can try to repro this in Cypress? I wasn't able to replicate it using sample dataset (H2).

**Comment by 08mitesh** [comment] 2021-02-10 18:44
Is there any update on this issue? i am also getting same issue. Not able to unhide all the table and because of that my entire dashboard is stucked.

**Comment by flamber** [comment] 2021-03-14 14:54
Closing in favor of #15165

**Closed by flamber** 2021-03-14 14:54 UTC
Labels: .Needs Triage, Type:Bug
