### ISSUE TITLE
SAML Integration / Support ?

### ISSUE THREAD

**Issue by iamfool** [metabase/metabase#8394] opened 2018-08-24 12:54 UTC
Hello Everyone,

How to implement SAML Integration of metabase with other identity provider. Has any one achieved this ? please help.

**Comment by jornh** [comment] 2018-08-24 14:40
There’s already an existing request https://github.com/metabase/metabase/issues/4308 asking for SAML support.

Please just 👍 vote for that instead of opening yet another issue.

**Comment by mazameli** [comment] 2018-08-24 22:03
Closing as duplicate of #4308

**Closed by mazameli** 2018-08-24 22:03 UTC
Labels: Duplicate
