### ISSUE TITLE
Elastic beanstalk upgrades broken in 0.25-rc2

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5537] opened 2017-07-20 23:37 UTC
#5118 breaks upgrading Elastic beanstalk instances in some cases.
Error message below in an upgrade from 0.24.0 -> 0.25.0-rc2
```
/etc/nginx/sites-enabled/elasticbeanstalk-nginx-docker-proxy.conf:11
  nginx: [emerg] unknown log format "healthd" in /etc/nginx/sites-enabled/elasticbeanstalk-nginx-docker-proxy.conf:19
  nginx: configuration file /etc/nginx/nginx.conf test failed
  Failed to start nginx, abort deployment (ElasticBeanstalk::ExternalInvocationError)
caused by: nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/sites-enabled/elasticbeanstalk-nginx-docker-proxy.conf:11
  nginx: [emerg] unknown log format "healthd" in /etc/nginx/sites-enabled/elasticbeanstalk-nginx-docker-proxy.conf:19
  nginx: configuration file /etc/nginx/nginx.conf test failed
  Failed to start nginx, abort deployment (Executor::NonZeroExitStatus)
```

This is a blocking bug on releasing 0.25

**Comment by senior** [comment] 2017-07-24 21:58
I've tried to recreate this several different ways and have not been successful. Following the instructions on the website with 0.25-rc2 everything was working fine. After talking with @salsakran I tried simulating an older installation by starting with 0.22.2, then upgrading to 0.24.2, then 0.25-rc2. This was all good as well. I tried load balanced instances and single instances with success as well.

It seems like @salsakran must have been dealing with some cruft or something as this was a pretty old instance and once we deployed it as a single instance the issue went away (with no code change).

Closing this as it's not reproducible.

**Comment by salsakran** [comment] 2017-07-26 19:46
repro-d this with a fresh instance 
<img width="1060" alt="screen shot 2017-07-26 at 12 39 00 pm" src="https://user-images.githubusercontent.com/107439/28640400-6b012144-7200-11e7-945c-e2413418fe56.png">
and http://discourse.metabase.com/t/unknown-log-format-healthd/1816/5

**Comment by senior** [comment] 2017-07-27 15:44
The problem with healthd is related to whether the instance has enhanced logging enabled or not. The old elastic beanstalk API defaults to enhancing logging. This puts the necessary healthd log_format in place, which allows 0.25.0 to work. The new elastic beanstalk UI defaults to "Basic" which does not put the healthd log_format in place. This will cause 0.25.0 to fail. Since we don't know whether enhanced logging is enabled, and the user could change it back to Basic at any time, it's best to just not reference healthd at all. PR #5609 makes that change.

**Closed** 2017-07-27 20:31 UTC
Labels: Bug, Priority/P1, Running Metabase/Elastic Beanstalk
