### ISSUE TITLE
DST on Snowflake can be offset by one day

### ISSUE THREAD

**Issue by joshi-hiren** [metabase/metabase#16125] opened 2021-05-18 10:46 UTC
**Describe the bug**
When selecting days, for 2020, the 29th March (the day the clockas gor forward) gets displayed twice and all days after that show the data for the previous day. For the 25th October (the day the clocks go back), that date is missing but every subsiquent day shows the correct data. For example:
```...
28-3-2020, 24:00 --shows data for the 28th
29-3-2020, 24:00 --shows data for the 29th
29-3-2020, 24:00 --shows data for the 30th
30-3-2020, 24:00 --shows data for the 31st
...
23-10-2020, 24:00 --shows data for the 24th
24-10-2020, 24:00 --shows data for the 25th
26-10-2020, 24:00 --shows data for the 26th
...
```

**Logs**
```{ "browser-info": { "language": "en", "platform": "MacIntel", "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0", "vendor": "" }, "system-info": { "file.encoding": "UTF-8", "java.runtime.name": "OpenJDK Runtime Environment", "java.runtime.version": "11.0.11+9", "java.vendor": "AdoptOpenJDK", "java.vendor.url": "https://adoptopenjdk.net/", "java.version": "11.0.11", "java.vm.name": "OpenJDK 64-Bit Server VM", "java.vm.version": "11.0.11+9", "os.name": "Linux", "os.version": "4.14.231-173.360.amzn2.x86_64", "user.language": "en", "user.timezone": "Europe/London" }, "metabase-info": { "databases": [ "snowflake", "h2" ], "hosting-env": "elastic-beanstalk", "application-database": "postgres", "application-database-details": { "database": { "name": "PostgreSQL", "version": "12.5" }, "jdbc-driver": { "name": "PostgreSQL JDBC Driver", "version": "42.2.18" } }, "run-mode": "prod", "version": { "date": "2021-04-27", "tag": "v0.39.1", "branch": "release-x.39.x", "hash": "6beba48" }, "settings": { "report-timezone": "Europe/London" } } }```
**To Reproduce**

1. Create a table called cal_date, populate it with 2020-01-01 through to 2020-12-31
2. Select that table either via a report or SQL in a question
3. Should see the same behaviour as above

**Severity**
All reports/questions that use date/time need to be aware of this bug and work around it.

**Aditional Context**
Looks very similar to the closed issue: #7286

**Comment by flamber** [comment] 2021-05-18 11:42
Hi @joshi-hiren 
This is not related to #7286, which is a frontend issue, whereas this is a backend issue involving DST.

From what I can tell, it seems to be specific to Snowflake, and I'm 90% sure that it's a duplicate of #8804.
I haven't checked what the consequences might be from changing to UTC in step 4.

To reproduce:
1. Start instance with Java parameter `-Duser.timezone="Europe/London"` and set Report Timezone to "Europe/London"
2. Native query > Snowflake db
```
select "string" as "string for validation", "string"::date as "date", "string"::datetime as "datetime", "string"::timestamp as "timestamp", "string"::timestamptz as "timestamptz" from (
    select '2020-03-28' "string" union all
    select '2020-03-29' "string" union all
    select '2020-03-30' "string" union all
    select '2020-03-31' "string" union all
    select '2020-10-24' "string" union all
    select '2020-10-25' "string" union all
    select '2020-10-26' "string"
)
```
3. Shows incorrect handling of switching DST
![image](https://user-images.githubusercontent.com/1447303/118643812-52382a00-b7dd-11eb-9053-036a226bea5d.png)
4. Start with `-Duser.timezone=UTC` while Report Timezone can be "Use database default" or any value "Europe/London", then correctly handles it:
![image](https://user-images.githubusercontent.com/1447303/118644745-69c3e280-b7de-11eb-99ef-1a2074cbb382.png)

**Comment by joshi-hiren** [comment] 2021-05-18 12:18
Fantastic, I'll try the workaround. But for what it's worth, we once saw the same issue on dbeaver and resolved that by updateing the JDBC driver, do you know if the snowflake connector on metabase is tha latest one?

**Comment by flamber** [comment] 2021-05-18 12:26
Metabase 0.39.2 uses JDBC 3.12.13, which is ~8 months old - it would be great if you could test on DBeaver and see if a newer driver fixes it - then it's a lot easier to fix the issue.
For reference:
https://github.com/metabase/metabase/blob/release-x.39.x/modules/drivers/snowflake/project.clj
https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/

**Comment by joshi-hiren** [comment] 2021-05-18 14:08
Good news!
On dbeaver using driver 3.12.13, I see 2 2020-03-29, missing 2020-10-25 and 2 2021-03-28
With version 3.13.3, all is well with the world and I see one of each date.

**Comment by joshi-hiren** [comment] 2021-06-23 09:26
I tried updateing the connector version but the intergration tests are failing, do you know who mantains them?

**Comment by flamber** [comment] 2021-06-23 09:36
@joshi-hiren Third-party PRs does not run all tests - because of security. You will have to wait for a developer run it internally.

**Comment by jeff303** [comment] 2021-08-13 17:56
Hi @joshi-hiren , I created a new PR for this into the current `master` branch.  We [switched](https://github.com/metabase/metabase/wiki/Migrating-from-Leiningen-to-tools.deps) from Leiningen over to `deps.edn` so the change is slightly different.  This will also run the full CI suite, so stay tuned.

**Closed** 2021-08-16 14:41 UTC
Labels: Type:Bug, Priority:P2, Misc/Timezones, Database/Snowflake
