### ISSUE TITLE
Visualization of time series only shows dates without times

### ISSUE THREAD

**Issue by jens-totemic** [metabase/metabase#18956] opened 2021-11-12 04:14 UTC
Using a "Native query" to display a postgres table with time series data. The time series data is using timestamps and integer values. When using e.g. a line chart and selecting `X-axis scale` for the timestamp data, then the visualization has a couple of issues:
* the x axis labels only show dates and omit hours/min
* When moving the mouse on a data point in the graph, the overlay with the values of a point also doesn't show the times.
* Any kind of modification of the `X-axis` setting regarding the time ("Time style" 12/24, "Show the time" style are ignored)

To reproduce, run this kind of query in the sql editor (might require to connect to a postgres database for it to work):
```
WITH test(ts, v) AS (VALUES
	('2021-11-11 13:00:56Z'::timestamptz, 6),
	('2021-11-11 15:11:43Z'::timestamptz, 5),
	('2021-11-11 17:22:35Z'::timestamptz, 4),
	('2021-11-11 19:33:22Z'::timestamptz, 6),
	('2021-11-11 21:44:19Z'::timestamptz, 5),
	('2021-11-11 23:55:02Z'::timestamptz, 4)
)
SELECT *
FROM test
```

And then just display this with a simple line visualization. See attached picture for more details:

<img width="997" alt="Screen Shot 2021-11-11 at 20 01 19" src="https://user-images.githubusercontent.com/44175225/141408290-c0619b64-684f-4be9-a774-8e90988ed72a.png">

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "5.4.95-42.163.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.2 (Ubuntu 13.2-1.pgdg18.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-11-09",
      "tag": "v0.41.2",
      "branch": "release-x.41.x",
      "hash": "ad599fd"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2021-11-12 11:22
Duplicate of #11435

**Closed by flamber** 2021-11-12 11:22 UTC
Labels: Type:Bug, .Needs Triage
