### ISSUE TITLE
Fields containing brackets break the custom expression editor

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#21074] opened 2022-03-17 23:28 UTC
**Describe the bug**
If the table has a column with brackets in the name, the custom expression editor in the filter breaks

**Logs**
Nothing on the BE, but FE:
"String currently can't contain brackets: Test [deprecated]"

**To Reproduce**
1) sync a column that has brackets in the name (or change the name of one)
2) go to the notebook and try to do a custom expression in the filter
3) hit the error

**Expected behavior**
Either we replace these special characters on the column names or we encode them so the custom expression builder does not break

**Screenshots**
![broken_editor](https://user-images.githubusercontent.com/1711649/158910046-5bc13857-b2d8-4808-aae4-a74bdcf5341d.gif)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 20.04
- Your databases: Postgres 14
- Metabase version: 1.42.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14

**Severity**
Non-critical

**Additional context**
Workaround: change the column name in the data model and remove the brackets

**Comment by ariya** [comment] 2022-03-18 03:43
Is this the same as #15316?

**Comment by flamber** [comment] 2022-03-18 08:16
Duplicate of #15316

**Closed by flamber** 2022-03-18 08:16 UTC
Labels: Type:Bug, Priority:P3, .Frontend, Querying/Notebook/Custom Expression
