### ISSUE TITLE
New tables not showing

### ISSUE THREAD

**Issue by bractus** [metabase/metabase#24940] opened 2022-08-23 13:08 UTC
**Describe the bug**
I've created some tables (in Redshift), and they are not showing on browser (also not appearing in metabase_tables on postgresql).

I could do queries on SQL, but not showing on Questions and Data Model.

Already resync, see the logs, see the database, updated.

**Expected behavior**
See the new tables on Questions and Data Model

**Severity**

Block usage.

**Metabase Diagnostic Info**

```{
  "browser-info": {
    "language": "pt-BR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8",
    "os.name": "Linux",
    "os.version": "4.14.287-215.504.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.4.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-08-16",
      "tag": "v0.44.1",
      "branch": "release-x.44.x",
      "hash": "112f5aa"
    },
    "settings": {
      "report-timezone": "America/Sao_Paulo"
    }
  }
}```

**Comment by flamber** [comment] 2022-08-23 13:18
Hi @bractus 
Which types of tables have you created? Regular tables, Late binding, Views, ...?
So let's say you have two tables, `old_table` and `new_table`, then you are only seeing "Old Table" in the GUI, but you can still make a query against `select * from new_table` in Metabase, and the `new_table` lives in the same database and schema as `old_table` ?
And your logs does not show any errors or warnings during sync ?

**Comment by bractus** [comment] 2022-08-23 13:21
> Hi @bractus Which types of tables have you created? Regular tables, Late binding, Views, ...? So let's say you have two tables, `old_table` and `new_table`, then you are only seeing "Old Table" in the GUI, but you can still make a query against `select * from new_table` in Metabase, and the `new_table` lives in the same database and schema as `old_table` ? And your logs does not show any errors or warnings during sync ?

Hi flamber,

It's regular tables, new tables, there weren'`t any old table with the same name, just other tables in schema.

Logs not showing any error.

**Comment by flamber** [comment] 2022-08-23 13:27
@bractus 
Okay, so you have never used Metabase before?
Which schemas have you configured Metabase to be able to see? All? Admin > Databases > (db) > Schemas

**Comment by bractus** [comment] 2022-08-23 13:30
> @bractus Okay, so you have never used Metabase before? Which schemas have you configured Metabase to be able to see? All? Admin > Databases > (db) > Schemas

We're using metabase for some time now, and updated to 0.44.1 yesterday to see if it solves this problem. This problem is just one week old, before that it's all ok (no updates in this time).

We're able to see all tables and schemas in Redshift.

**Comment by flamber** [comment] 2022-08-23 13:43
@bractus Okay, so if nothing has changed in Metabase, besides it just stopped working last week all by itself, then I'm guessing something has changed on Redshift (either some privileges or perhaps auto-upgrade of Redshift)?

I cannot reproduce on Metabase 0.44.1 with Redshift 1.0.40677

Are you able to run this query from within Metabase (not on Redshift) > New > SQL Query > `select * from yourschema.yourmissingtable limit 1`

1. Start your instance with debug logging `log4j.configurationFile="https://log4j.us/v2/templates/metabase?trace=metabase.sync"`
2. Do a manual sync via Admin > Databases > (db) > Sync database schema now
3. Include the logs here

**Comment by bractus** [comment] 2022-08-24 11:53
@flamber I've tested your solution and no success, but today I've created a new connection to the same database and the new tables showed... Now I ask, there's a way to change all my old connection Questions to this new connection? Thanks.

**Comment by flamber** [comment] 2022-08-24 12:02
@bractus Make a backup, then check `metabase_database.details` and compare between those two databases. There is no simple way of changing database ID references, so don't do that. Fix the current connection.

If you need further help with troubleshooting, then please use the forum: https://discourse.metabase.com/

Closing, since there's no way for us to know what has caused this and without reproducible steps, then there isn't much we can do.

**Closed by flamber** 2022-08-24 12:02 UTC
Labels: Type:Bug, .Needs Triage
