### ISSUE TITLE
Map view clipping nordic countries

### ISSUE THREAD

**Issue by brylie** [metabase/metabase#6474] opened 2017-11-27 14:19 UTC
- Your browser and the version:  Firefox 57
- Your operating system: Ubuntu 17.10
- Your databases: Postgres
- Metabase version: v0.26.2
- Metabase hosting environment: Docker
- Metabase internal database: H2

# Steps to reproduce
1. create a region map with world regions
2. make sure region data contains records for nordic countries
3. view map

# Observed result
The nordic countries are trimmed off at the top of the map:

![screenshot from 2017-11-27 16-16-43](https://user-images.githubusercontent.com/17307/33271048-c31c1ba0-d38e-11e7-8694-c29d614ec0f0.png)

# Expected result
Nordic countries would not be clipped below the arctic circle.

**Comment by jornh** [comment] 2018-08-12 07:59
Duplicate of #4378

If you agree, please close this and add your 👍 vote over there.

**Closed** 2018-08-12 09:34 UTC
Labels: Bug, Priority/P3, Visualization
