### ISSUE TITLE
Spurious permission errors after upgrading to Metabase 0.30.0 from 0.29.3

### ISSUE THREAD

**Issue by jombooth** [metabase/metabase#8438] opened 2018-09-01 23:32 UTC
### Bugs

- Your browser and the version: chrome 68.0.3440.84
- Your operating system: ubuntu bionic beaver
- Your databases: postgres
- Metabase version: 0.30.0
- Metabase hosting environment: elastic beanstalk
- Metabase internal database: postgres

Despite my having Admin permissions in our Metabase instance, I've found with the switch to 0.30.0 that many common queries result in a permissions denied screen:

![image](https://user-images.githubusercontent.com/3943358/44950712-08386b80-ae1d-11e8-81e6-2d22cf55f060.png)

An example query that works on most Postgres tables and which consistently will trigger this error is

`SELECT table_schema,table_name FROM information_schema.tables`

I initially discovered this while trying to select substrings of fields using the substr() function, but quickly found that many queries trigger it. Worse yet, when you press the 'back' button from this permissions denied screen, your query will be gone.

**Comment by alexezimm** [comment] 2018-09-10 18:33
Having similar issues -- got a "Sorry you do not have permission" screen when I was just trying to save a new question. I'm an Admin and should have access to all tables and questions.

**Comment by alexezimm** [comment] 2018-09-12 17:44
It appears to be happening when there are somewhat uncommon sql functions being used -- we've failed on a couple of internal ones, as well as `HAVING` and `EXISTS`

**Comment by mazameli** [comment] 2018-09-27 16:43
@alexezimm Hmm, I'll need to look into this. Are you also querying a postgres db like @jombooth? Can you also provide details about the environment you're running Metabase in and which specific version you're running? Thanks.

**Comment by alexezimm** [comment] 2018-09-27 21:07
@mazameli this is now happening even when all I am doing is adding a question to a dashboard -- it goes to 'saving' and then says I do not have permission.

**Comment by alexezimm** [comment] 2018-09-28 02:15
In many cases I am having difficulty editing and re-saving any old question or dashboard -- maybe it has something to do with the new permissions model?

**Comment by alexezimm** [comment] 2018-10-04 02:48
@mazameli any updates here? It appears that nearly all dashboards are un-editable (any time I save it gives me the permission error) and even simple queries (3-4 lines) don't work.

At this point we have moved nearly all our BI work off of Metabase.

**Comment by DEVELByte** [comment] 2019-07-05 06:44
@mazameli facing the same issue after upgrading to Metabase v0.32.9
we have out dashboard on redshift

**Comment by AlmogCohen** [comment] 2019-08-07 21:05
Anything new here? I experience the same now when upgrading from 0.28.0 to 0.32.0 over AWS Elastic Beanstalk

**Comment by AlmogCohen** [comment] 2019-08-07 21:09
I think the instructions here might be helpful for those who upgrade... 
https://metabase.com/blog/before-upgrading-to-0.30/

**Comment by flamber** [comment] 2020-05-31 17:34
Closing, since there were several fixes to the permissions through the past many versions.
If you're still seeing spurious permission errors in 0.35.4+, then please comment with details on how to reproduce and/or logs from Admin > Troubleshooting and the browser developer console.

**Closed by flamber** 2020-05-31 17:34 UTC
Labels: Administration/Permissions, Operation/
