### ISSUE TITLE
Add Number filter type for Dashboards

### ISSUE THREAD

**Issue by MixMe** [metabase/metabase#4189] opened 2017-01-18 19:54 UTC
![capture](https://cloud.githubusercontent.com/assets/3535911/22080448/50a540f4-ddc8-11e6-8845-0314bd1065b6.PNG)

Thanks to everybody for this great tool, can you please add 1 more filter by "Number" for integer values.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by salsakran** [comment] 2017-01-22 19:44
Would this just be an integer input field?

**Comment by MixMe** [comment] 2017-01-23 08:52
yes, for ID's like on image:
![capture](https://cloud.githubusercontent.com/assets/3535911/22197283/04451afa-e15a-11e6-82f1-6dc3378d4d36.PNG)

**Comment by tlrobinson** [comment] 2017-02-02 07:05
Alternatively we could just rename "Other Categories" to something like "Category", and add an "Other" option. As I mentioned in #3816 I believe we should always be able to tell whether the "target" of a parameter expects a number, string, or date.

**Comment by MixMe** [comment] 2017-03-16 18:21
Version 0.23.0

`Mar 16 19:19:41 WARN metabase.query-processor :: Query failure: ERROR: operator does not exist: integer = character varying
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 1707
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:154)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:147)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:187)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:181)"
 "query_processor$dataset_query.invokeStatic(query_processor.clj:220)"
 "query_processor$dataset_query.invoke(query_processor.clj:193)"
 "api.card$run_query_for_card.invokeStatic(card.clj:369)"
 "api.card$run_query_for_card.doInvoke(card.clj:357)"
 "api.card$fn__25132$fn__25135.invoke(card.clj:374)"
 "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:229)"
 "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:224)"
 "api.card$fn__25132.invokeStatic(card.clj:371)"
 "api.card$fn__25132.invoke(card.clj:371)"
 "middleware$enforce_authentication$fn__34463.invoke(middleware.clj:119)"
 "api.routes$fn__34580.invokeStatic(routes.clj:53)"
 "api.routes$fn__34580.invoke(routes.clj:53)"
 "routes$fn__35604.invokeStatic(routes.clj:44)"
 "routes$fn__35604.invoke(routes.clj:44)"
 "middleware$log_api_call$fn__34562$fn__34564.invoke(middleware.clj:331)"
 "middleware$log_api_call$fn__34562.invoke(middleware.clj:330)"
 "middleware$add_security_headers$fn__34512.invoke(middleware.clj:246)"
 "middleware$bind_current_user$fn__34467.invoke(middleware.clj:139)"
 "middleware$maybe_set_site_url$fn__34516.invoke(middleware.clj:268)"]

Mar 16 19:19:41 DEBUG metabase.middleware :: POST /api/card/45/query 200 (585 ms) (11 DB calls)`


It still not works :(

**Comment by MixMe** [comment] 2017-03-16 18:21
Mar 16 19:19:41 WARN metabase.query-processor :: {:status :failed,
 :class java.lang.Exception,
 :error "ERROR: operator does not exist: integer = character varying\n  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.\n  Position: 1707",
 :stacktrace
 ["driver.generic_sql.query_processor$do_with_try_catch.invokeStatic(query_processor.clj:323)"
  "driver.generic_sql.query_processor$do_with_try_catch.invoke(query_processor.clj:319)"
  "driver.generic_sql.query_processor$execute_query.invokeStatic(query_processor.clj:365)"
  "driver.generic_sql.query_processor$execute_query.invoke(query_processor.clj:361)"
  "driver$fn__19562$G__19555__19569.invoke(driver.clj:43)"
  "query_processor$execute_query.invokeStatic(query_processor.clj:37)"
  "query_processor$execute_query.invoke(query_processor.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__23115.invoke(mbql_to_native.clj:28)"
  "query_processor.middleware.annotate_and_sort$annotate_and_sort$fn__21783.invoke(annotate_and_sort.clj:37)"
  "query_processor.middleware.limit$limit$fn__23087.invoke(limit.clj:14)"
  "query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__22948.invoke(cumulative_aggregations.clj:46)"
  "query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__22948.invoke(cumulative_aggregations.clj:46)"
  "query_processor.middleware.format_rows$format_rows$fn__23078.invoke(format_rows.clj:21)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__21463.invoke(add_row_count_and_status.clj:14)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__22968.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__24054.invoke(resolve_driver.clj:14)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__22890.invoke(catch_exceptions.clj:51)"
  "query_processor$process_query.invokeStatic(query_processor.clj:62)"
  "query_processor$process_query.invoke(query_processor.clj:57)"
  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:186)"
  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:181)"
  "query_processor$dataset_query.invokeStatic(query_processor.clj:220)"
  "query_processor$dataset_query.invoke(query_processor.clj:193)"
  "api.card$run_query_for_card.invokeStatic(card.clj:369)"
  "api.card$run_query_for_card.doInvoke(card.clj:357)"
  "api.card$fn__25132$fn__25135.invoke(card.clj:374)"
  "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:229)"
  "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:224)"
  "api.card$fn__25132.invokeStatic(card.clj:371)"
  "api.card$fn__25132.invoke(card.clj:371)"
  "middleware$enforce_authentication$fn__34463.invoke(middleware.clj:119)"
  "api.routes$fn__34580.invokeStatic(routes.clj:53)"
  "api.routes$fn__34580.invoke(routes.clj:53)"
  "routes$fn__35604.invokeStatic(routes.clj:44)"
  "routes$fn__35604.invoke(routes.clj:44)"
  "middleware$log_api_call$fn__34562$fn__34564.invoke(middleware.clj:331)"
  "middleware$log_api_call$fn__34562.invoke(middleware.clj:330)"
  "middleware$add_security_headers$fn__34512.invoke(middleware.clj:246)"
  "middleware$bind_current_user$fn__34467.invoke(middleware.clj:139)"
  "middleware$maybe_set_site_url$fn__34516.invoke(middleware.clj:268)"],
 :query
 {:type "query",
  :query
  {:source_table 93,
   :breakout
   [["field-id" 712]
    ["datetime_field" ["field-id" 698] "as" "minute"]
    ["field-id" 700]
    ["fk->" 701 126]
    ["fk->" 1074 1077]
    ["fk->" 727 1079]
    ["field-id" 708]
    ["field-id" 714]
    ["field-id" 718]
    ["field-id" 720]
    ["field-id" 723]
    ["datetime_field" ["field-id" 730] "as" "day"]
    ["datetime_field" ["field-id" 729] "as" "day"]],
   :limit 100},
  :parameters [{:type "id", :target ["dimension" ["fk->" 697 86]], :value "222"}],
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :info {:executed-by 1, :card-id 45, :uuid "87f49236-7053-4916-ac46-14ee0e675d58", :query-hash -1362640055, :query-type "MBQL"}},
 :expanded-query
 {:type "query",
  :query
  {:source-table {:schema "public", :name "special_order_orders", :id 93},
   :breakout
   [{:field-id 712,
     :field-name "id",
     :field-display-name "ID",
     :base-type :type/Integer,
     :special-type :type/PK,
     :visibility-type :normal,
     :table-id 93,
     :schema-name "public",
     :table-name "special_order_orders",
     :position nil,
     :fk-field-id nil,
     :description nil,
     :parent-id nil,
     :parent nil}
    {:field
     {:field-id 698,
      :field-name "client_deadline",
      :field-display-name "Client Deadline",
      :base-type :type/DateTime,
      :special-type nil,
      :visibility-type :normal,
      :table-id 93,
      :schema-name "public",
      :table-name "special_order_orders",
      :position nil,
      :fk-field-id nil,
      :description nil,
      :parent-id nil,
      :parent nil},
     :unit :minute}
    {:field-id 700,
     :field-name "client_price",
     :field-display-name "Client Price",
     :base-type :type/Float,
     :special-type nil,
     :visibility-type :normal,
     :table-id 93,
     :schema-name "public",
     :table-name "special_order_orders",
     :position nil,
     :fk-field-id nil,
     :description nil,
     :parent-id nil,
     :parent nil}
    {:field-id 126,
     :field-name "name",
     :field-display-name "Name",
     :base-type :type/Text,
     :special-type :type/Name,
     :visibility-type :normal,
     :table-id 18,
     :schema-name nil,
     :table-name "countries__via__country_id",
     :position nil,
     :fk-field-id 701,
     :description nil,
     :parent-id nil,
     :parent nil}
    {:field-id 1077,
     :field-name "status",
     :field-display-name "Status",
     :base-type :type/Text,
     :special-type :type/Category,
     :visibility-type :normal,
     :table-id 151,
     :schema-name nil,
     :table-name "order_statuses__via__current_s",
     :position nil,
     :fk-field-id 1074,
     :description nil,
     :parent-id nil,
     :parent nil}
    {:field-id 1079,
     :field-name "name",
     :field-display-name "Name",
     :base-type :type/Text,
     :special-type :type/Name,
     :visibility-type :normal,
     :table-id 152,
     :schema-name nil,
     :table-name "drawing_styles__via__type_id",
     :position nil,
     :fk-field-id 727,
     :description nil,
     :parent-id nil,
     :parent nil}
    {:field-id 708,
     :field-name "exaggeration_level",
     :field-display-name "Exaggeration Level",
     :base-type :type/Integer,
     :special-type :type/Category,
     :visibility-type :normal,
     :table-id 93,
     :schema-name "public",
     :table-name "special_order_orders",
     :position nil,
     :fk-field-id nil,
     :description nil,
     :parent-id nil,
     :parent nil}
    {:field-id 714,
     :field-name "is_deleted",
     :field-display-name "Is Deleted",
     :base-type :type/Boolean,
     :special-type :type/Category,
     :visibility-type :normal,
     :table-id 93,
     :schema-name "public",
     :table-name "special_order_orders",
     :position nil,
     :fk-field-id nil,
     :description nil,
     :parent-id nil,
     :parent nil}
    {:field-id 718,
     :field-name "market",
     :field-display-name "Market",
     :base-type :type/Text,
     :special-type :type/Category,
     :visibility-type :normal,
     :table-id 93,
     :schema-name "public",
     :table-name "special_order_orders",
     :position nil,
     :fk-field-id nil,
     :description nil,
     :parent-id nil,
     :parent nil}
    {:field-id 720,
     :field-name "objects_number",
     :field-display-name "Objects Number",
     :base-type :type/Integer,
     :special-type :type/Number,
     :visibility-type :normal,
     :table-id 93,
     :schema-name "public",
     :table-name "special_order_orders",
     :position nil,
     :fk-field-id nil,
     :description nil,
     :parent-id nil,
     :parent nil}
    {:field-id 723,
     :field-name "original_client_price",
     :field-display-name "Original Client Price",
     :base-type :type/Text,
     :special-type nil,
     :visibility-type :normal,
     :table-id 93,
     :schema-name "public",
     :table-name "special_order_orders",
     :position nil,
     :fk-field-id nil,
     :description nil,
     :parent-id nil,
     :parent nil}
    {:field
     {:field-id 730,
      :field-name "when_created",
      :field-display-name "When Created",
      :base-type :type/DateTime,
      :special-type nil,
      :visibility-type :normal,
      :table-id 93,
      :schema-name "public",
      :table-name "special_order_orders",
      :position nil,
      :fk-field-id nil,
      :description nil,
      :parent-id nil,
      :parent nil},
     :unit :day}
    {:field
     {:field-id 729,
      :field-name "when_client_received",
      :field-display-name "When Client Received",
      :base-type :type/DateTime,
      :special-type nil,
      :visibility-type :normal,
      :table-id 93,
      :schema-name "public",
      :table-name "special_order_orders",
      :position nil,
      :fk-field-id nil,
      :description nil,
      :parent-id nil,
      :parent nil},
     :unit :day}],
   :limit 100,
   :join-tables
   [{:source-field {:field-id 701, :field-name "country_id"},
     :pk-field {:field-id 125, :field-name "id"},
     :table-id 18,
     :table-name "countries",
     :schema "public",
     :join-alias "countries__via__country_id"}
    {:source-field {:field-id 727, :field-name "type_id"},
     :pk-field {:field-id 1078, :field-name "id"},
     :table-id 152,
     :table-name "drawing_styles",
     :schema "public",
     :join-alias "drawing_styles__via__type_id"}
    {:source-field {:field-id 1074, :field-name "current_status"},
     :pk-field {:field-id 1076, :field-name "id"},
     :table-id 151,
     :table-name "order_statuses",
     :schema "public",
     :join-alias "order_statuses__via__current_s"}]},
  :parameters [{:type "id", :target ["dimension" ["fk->" 697 86]], :value "222"}],
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :info {:executed-by 1, :card-id 45, :uuid "87f49236-7053-4916-ac46-14ee0e675d58", :query-hash -1362640055, :query-type "MBQL"},
  :fk-field-ids #{727 701 1074},
  :table-ids #{151 93 152 18}}}

**Comment by MixMe** [comment] 2017-03-16 18:24
![capture222](https://cloud.githubusercontent.com/assets/3535911/24012326/43b7b03a-0a86-11e7-9669-c33c2bd60fb8.PNG)

I want to find all order by Client ID (PostgreSQL Database)
Client ID is "Foreign Key"

**Comment by rjazhenka** [comment] 2018-03-29 09:59
Exactly the same behaviour in 0.28.3

**Comment by flamber** [comment] 2019-02-19 22:00
This is related to (maybe duplicate of) #3035

**Comment by mazameli** [comment] 2019-02-19 22:03
Closing as dupe of #3035

**Closed by mazameli** 2019-02-19 22:03 UTC
Labels: Duplicate, Parameters/Variables, Proposal
