### ISSUE TITLE
Duplicate Dashboard with Action

### ISSUE THREAD

**Issue by MateusRamos10** [metabase/metabase#45525] opened 2024-07-13 17:57 UTC
### Describe the bug

Guys, I went to duplicate a dashboard that has actions and it gave the image error, if I fill in some parameters like description or archived via the api, is it possible to duplicate a dashboard with action?

![bug metabase dashboard duplicate](https://github.com/user-attachments/assets/116c295d-984a-4063-913d-d1def74b3ab7)

### To Reproduce

1. Go to your Dashboard that has Action
2. Click on Duplicate Dashboard
3. See this error

### Information about your Metabase installation

```JSON
- Metabase version: v0.49.20
```

### Severity

Low Severity

**Comment by bshepherdson** [comment] 2024-07-15 20:56
Needs investigation to see whether this is a FE or BE issue.

**Comment by kulyk** [comment] 2024-07-17 16:52
Possibly a duplicate of #38224

**Comment by kulyk** [comment] 2024-07-23 15:45
Duplicate of https://github.com/metabase/metabase/issues/38224

**Closed by kulyk** 2024-07-23 15:45 UTC
Labels: Type:Bug, Priority:P2, Reporting/Dashboards, .Frontend, .Backend, Querying/Actions, .Team/DashViz
