### ISSUE TITLE
MongoDB driver doesn't support joins

### ISSUE THREAD

**Issue by dareid** [metabase/metabase#1465] opened 2015-11-10 10:32 UTC
Queries using joins are offered when using the mongo driver. I think it would be best to avoid showing this to the user if their connector does not offer the functionality.

**Comment by salsakran** [comment] 2015-11-10 22:48
Can you give examples of collections where this is offered? We offer the ability to reference nested dictionaries, which may look similar to joins. Is that what you're seeing? Or is this a situation where you are manually defining a foreign key in the admin?

**Comment by camsaul** [comment] 2015-11-18 20:03
Here's how we can fix this: 
*  The drivers that support joins (i.e., the SQL drivers) declare support for `foreign-keys` in their `features` list. 
*  The frontend should look for this key and only show join-specific stuff if it's present

**Comment by dareid** [comment] 2015-11-19 10:44
Yes I did manually set foreign keys in admin, with the assumption that metabase must be doing some aggregation locally to mock the functionality. So I suppose the key is to hide the foreign key option in admin if the connector does not support it.

**Comment by camsaul** [comment] 2015-11-19 16:51
@dareid Sorry, that's not what I was referring to. I was making a note about the Metabase internals for @tlrobinson or whoever ends up implementing this thicket. Internally each of our drivers has a "features" list for things it supports so we can show or hide bits of UI when appropriate.

**Comment by camsaul** [comment] 2015-11-19 16:53
@salsakran We just need to hide FK-related stuff in the UI for Mongo

**Comment by emmanuelbuah** [comment] 2018-10-30 14:38
I don't think this ticket is valid anymore. Mongodb supports joins via its `lookup` feature, hence, joins can and would be good to implement for mongo driver. It looks like https://github.com/metabase/metabase/pull/8319 tracks work relating to this.

**Comment by camsaul** [comment] 2019-08-01 17:13
@tlrobinson this ticket is no longer relevant, right?

**Comment by ianmartorell** [comment] 2019-08-01 18:44
Rather than Mongo not supporting joins, it's the Metabase Mongo driver that doesn't. See #1687.

**Comment by luizarakaki** [comment] 2023-12-27 12:16
Related / duplicate of https://github.com/metabase/metabase/issues/9095
And that was closed/shipped on 45.

**Closed by luizarakaki** 2023-12-27 12:16 UTC
Labels: Type:Bug, Priority:P3, Querying/Processor, .Team/QueryProcessor
