### ISSUE TITLE
Adding the ability to sync 'COMMENT' data as table/column description for DBs that support. [Help Wanted]

### ISSUE THREAD

**Issue by EvilPuppetMaster** [metabase/metabase#6379] opened 2017-11-14 02:11 UTC
I'd like to contrib a feature that will sync the `COMMENT` data that can be added to tables and columns in many common DBs, as the default description for the table/column when metabase is synced. In JDBC, this is exposed as `REMARKS` on the getColumns and getTables results. This is supported by H2, Postgres, MySQL, Oracle, and Presto, and possibly others.

Help wanted though:

I have already got a mostly working version with tests against H2, however I am now trying to test it on Postgres and the other databases I know support it. I am running into some issues figuring out how to unit test on the other DBs though.

Dev docs mention that the tests can run against different DB drivers by changing an env var called ENGINES. And that is about it. They don’t explain how the tests actually access an running instance of a DB to do the tests. By trial and error I discovered that at least with Postgres, if I have a blank default DB running on localhost with no password when I run the unit tests, then some tests appear to be run. However I get some unit test failures when doing this, even when running against an unmodified master branch. So I’m not sure this is quite right.

It also appears that some unit tests don’t run on certain DB engines… but it’s unclear why this is or where it’s configured. The particular functionality I am testing involves changes to the metabase.sync.sync-metadata.tables-test test. I can get it working on H2, but when running on postgres, this test appears to be skipped.

Can anyone point me to docs that explain more about how to run tests against different dbs… or if not, provide specific answers to the above issues?

**Comment by camsaul** [comment] 2017-11-14 02:54
Closing as a duplicate of #3089.

@EvilPuppetMaster for the most part to test against different DBs you just need to specify appropriate env vars and add it to the `ENGINES` list. Take a look at [our CI script](https://github.com/metabase/metabase/blob/master/bin/ci) and the various env vars are specified there. They're specified in the codebase in files like [this one](https://github.com/metabase/metabase/blob/master/test/metabase/test/data/postgres.clj). So postgres for example you would do

```bash
ENGINES=h2,postgres \
  POSTGRESQL_TEST_USER=cam \
  POSTGRESQL_TEST_PASSWORD=toucans123 \
  POSTGRESQL_TEST_HOST=localhost \
  POSTGRESQL_TEST_PORT=5432
```

**Closed by camsaul** 2017-11-14 02:54 UTC

**Comment by EvilPuppetMaster** [comment] 2017-11-14 03:11
Thanks
