### ISSUE TITLE
After we upgraded to v0.35.3, the Custom question mode is broken. 

### ISSUE THREAD

**Issue by Folyd** [metabase/metabase#12480] opened 2020-05-08 02:49 UTC
**Describe the bug**
After we upgraded from the **v0.32.3** to **v0.35.3**, the Custom question mode is broken. 

**Logs**
Here is the console log:
```
app-main.bundle.js?f24695780b695904f509:5 Uncaught (in promise) TypeError: Cannot read property 'name' of null
    at app-main.bundle.js?f24695780b695904f509:5
    at Array.map (<anonymous>)
    at DatabaseSchemaPicker (app-main.bundle.js?f24695780b695904f509:5)
    at c._constructComponentWithoutOwner (vendor.bundle.js?f24695780b695904f509:1)
    at c._constructComponent (vendor.bundle.js?f24695780b695904f509:1)
    at c.mountComponent (vendor.bundle.js?f24695780b695904f509:1)
    at Object.mountComponent (vendor.bundle.js?f24695780b695904f509:1)
    at Z.mountChildren (vendor.bundle.js?f24695780b695904f509:1)
    at Z._createInitialChildren (vendor.bundle.js?f24695780b695904f509:1)
    at Z.mountComponent (vendor.bundle.js?f24695780b695904f509:1)
```

**To Reproduce**
1. Click on 'Ask a question..'
2. Click on 'Custom question'
3. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/3369694/81364974-85030900-9119-11ea-895c-97ca965354c4.png)

**Metabase Diagnostic Info**
```json
{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.4.178-1.el7.elrepo.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Hong_Kong"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.20-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-21",
      "tag": "v0.35.3",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": "Asia/Hong_Kong"
    }
  }
}
```

**Comment by Folyd** [comment] 2020-05-08 02:54
Also the same to the Simple question page. :(

**Comment by Folyd** [comment] 2020-05-08 02:58
Possible duplicated with #12477

**Comment by flamber** [comment] 2020-05-08 08:33
Duplicate of #12323. Workaround: turn on Admin > Settings > General > "Enable Nested Queries"

**Closed by flamber** 2020-05-08 08:33 UTC
Labels: .Duplicate
