### ISSUE TITLE
Download CSV/XLSX Timeout

### ISSUE THREAD

**Issue by vindentyang** [metabase/metabase#9533] opened 2019-03-08 15:03 UTC
Metabase: source code https://github.com/metabase/metabase/archive/v0.31.2.zip and update the sparksql.clj 214L to use our partitioned table.
(str "describe " (dash-to-underscore (:name table))))]) :while (and (not(clojure.string/blank? (:col_name result))) (not(clojure.string/blank? (:data_type result))))]
Browser: Chrome 72.0.3626.119
Result: Timeout:timeout shown in browser
DB: sparksql
When we use the builder to select datas with sparksql, it cost about 2 minutes to response. 
But when we download the full result in the button,  the browser always response "Timeout:timeout". Doesnt metabase use the result shown directly when we click download? 
Or it will do one more time calculate?

**Comment by flamber** [comment] 2019-03-08 17:08
Hi @vindentyang 
Please edit your issue and remove the template, and fill out the requested information and steps to reproduce as well as any errors in the Metabase log or browser console. It makes it easier for others to try to reproduce your issue and find the cause of the problem.

**Comment by vindentyang** [comment] 2019-03-11 03:25
> Hi @vindentyang
> Please edit your issue and remove the template, and fill out the requested information and steps to reproduce as well as any errors in the Metabase log or browser console. It makes it easier for others to try to reproduce your issue and find the cause of the problem.

Sorry for that as it was my first time to submit the issue in github, already updated! Thanks

**Comment by salsakran** [comment] 2019-04-10 04:26
@vindentyang are you experiencing this with the official release of Metabase or your own fork?

**Comment by vindentyang** [comment] 2019-04-30 07:21
> @vindentyang are you experiencing this with the official release of Metabase or your own fork?

Hi @salsakran we use the source code of the official release( https://github.com/metabase/metabase/archive/v0.31.2.zip) and run the service by lein.

**Comment by camsaul** [comment] 2019-04-30 20:36
If there's a reverse proxy in front of your Metabase instance such as `nginx` or and Elastic Load Balancer you may need to adjust their timeouts so they don't close the connection before we get a chance to return the result

**Comment by vindentyang** [comment] 2019-05-07 07:37
> their

Yes, we have nginx but we have set the timeout a long time(such as 3600s), but it always happended, it is so strange

**Comment by vindentyang** [comment] 2019-05-07 08:06
> If there's a reverse proxy in front of your Metabase instance such as `nginx` or and Elastic Load Balancer you may need to adjust their timeouts so they don't close the connection before we get a chance to return the result

Yes, we have nginx but we have set the timeout a long time(such as 3600s), but it always happended, it is so strange

**Comment by m1l0sz** [comment] 2019-06-18 23:49
shouldn't the export be made asynchronous? we are hitting the heroku timeout w/ csv and xlsx exports. this basically torpedoes the heroku app for us.

**Comment by flamber** [comment] 2019-06-19 00:20
@m1l0sz Which Metabase version are you using? Don't hang me up on it, but I don't think the current download/export functionality is async/streamed. There is some work being done on trying to stream the download (#9614), but it's only for csv.

**Comment by m1l0sz** [comment] 2019-06-19 00:44
we're on 0.32.9. it's not async, otherwise it wouldn't hit the timeout. if just csv exports of large datasets would work on heroku that would be fine. as it stands i think we're going to have to use lightsail or similar instead.

**Comment by duanshiqiang** [comment] 2019-08-20 15:09
We are facing the same problem and we are sure it's not the load balancer that caused the timeout.

And our metabase server logs doesn't reveal any useful log:

```
08-20 15:05:29 INFO middleware.exceptions :: Request canceled before finishing.
08-20 15:05:29 ERROR middleware.log :: Error logging API request
java.lang.NullPointerException
```

**Comment by flamber** [comment] 2019-08-20 17:29
@duanshiqiang That looks like the LB might have closed the connection. Check the logs of the LB.

**Comment by flamber** [comment] 2020-04-02 12:52
Closing this, since 0.35.0 now uses streaming responses and a fully async requests. See #11832
If you're still experiencing problems, then please comment with details and it will be reopened.

**Closed by flamber** 2020-04-02 12:52 UTC
Labels: .Need More Info, Database/Spark, Reporting/Export
