### ISSUE TITLE
oracle field filter generates invalid query 

### ISSUE THREAD

**Issue by jsantana3c** [metabase/metabase#42338] opened 2024-05-07 15:17 UTC
**Describe the bug**
when creating a field filter, the generated SQL contains the schema, which creates an error on SQL.

**Error**
ORA-00904: "schema"."table"."column": invalid identifier 

**Generated SQL**
WHERE TRUNC(SCHEME.TABLE.DATE_COLUMN, 'dd') BETWEEN date '2023-05-01' AND date '2024-04-30';

**Logs**
```
 ORA-00904: "SCHEME"."TABLE"."DATE_COLUMN": invalid identifier
2024-05-07T15:09:38.932113404Z 
2024-05-07T15:09:38.932116984Z {:database_id 2,
2024-05-07T15:09:38.932119442Z  :started_at #t "2024-05-07T15:09:38.821280Z[GMT]",
2024-05-07T15:09:38.932121869Z  :via
2024-05-07T15:09:38.932124087Z  [{:status :failed,
```

**To Reproduce**
1. Create a Question with native query
2. define a variable with a field filter
3. Map the filter to an table column with a schema
4. Run the Query
5. Exception is generated

**Expected behavior**
the generated query must run, excluding the schema path from the query, this example is working
`WHERE TRUNC(TABLE.DATE_COLUMN, 'dd') BETWEEN date '2023-05-01' AND date '2024-04-30';`

**Severity**
isn't possible to use the product properly.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "it-IT",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.146.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "oracle"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.2 (Debian 16.2-1.pgdg120+2)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-05-02",
      "tag": "v0.49.8",
      "hash": "38cb850"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by ranquild** [comment] 2024-11-01 13:56
Could be driver specific. I don't think it's okay to exclude the schema name in all cases like this

**Comment by appleby** [comment] 2024-11-09 00:10
@jsantana3c are you able to provide the complete query that is failing or ideally a minimal reproduction?

So far I can only reproduce this for queries which have table aliases, but in such cases simply dropping the schema still does not produce a working query, so I'm worried the failure you're seeing might be slightly different.

(these example are querying the HR schema from oracle's [db-sample-schemas](https://github.com/oracle-samples/db-sample-schemas)).

**working example**

```sql
SELECT *
FROM JOB_HISTORY
WHERE {{date}}
```

The field filter expands to the following, but including the schema here is fine.

```sql
WHERE TRUNC("HR"."JOB_HISTORY"."START_DATE", 'dd') BETWEEN date '2000-11-08'
   AND date '2001-11-08'
```

**failing example**

```
SELECT * FROM HR.JOB_HISTORY J
WHERE {{date}}
```

The field filter expands to the same, but in this case Oracle considers `"HR"."JOB_HISTORY"."START_DATE"` an invalid identifier and instead wants `"J"."START_DATE"`

**Comment by appleby** [comment] 2024-11-11 23:19
I realized that the behavior @jsantana3c reports could be explained by picking a table alias (a.k.a. [correlation name](https://docs.oracle.com/javadb/10.6.2.1/ref/rrefcorrelationname.html)) that happens to correspond to the schema-less table name. For example, the following query works, but replacing the column reference in the `WHERE` clause with `HR.JOB_HISTORY.START_DATE` produces the same "ORA-00904: invalid identifier" error.

```sql
SELECT * FROM HR.JOB_HISTORY JOB_HISTORY
WHERE JOB_HISTORY.START_DATE = date '2001-01-13'
```

If this is indeed related to table aliases, then this is likely a dup of #3324.

Things get more awkward in the presence of nested queries, especially if you are referencing a saved model / question like so

```sql
SELECT * FROM {{#123-saved-question}} WHERE {{my-field-filter}}
```

but again this is a known limitation, and our [docs recommend](https://www.metabase.com/docs/latest/questions/native-editor/referencing-saved-questions-in-queries#limitations-and-tradeoffs) duplicating the saved question and adding the filter there for a [related-but-not-quite-the-same issue](https://github.com/metabase/metabase/issues/6449) of wanting to reference field filters from source queries.

**Comment by joaquinjsb** [comment] 2024-11-12 00:02
Yes, 
sorry for the late reply, I do confirm it's a duplicate of #3324, I guess this issue can be closed.

thanks

**Closed** 2024-11-12 00:03 UTC
Labels: Type:Bug, Priority:P1, Querying/Processor, Database/Oracle, .Backend, .Team/Querying
