### ISSUE TITLE
Table aliases don't work with Field Widgets?

### ISSUE THREAD

**Issue by 949mac** [metabase/metabase#20572] opened 2022-02-17 00:47 UTC
Is this a feature or a bug? The documentation is not clear, but I see issues from 6 years ago referencing something similar.

❗ Does not work
![Image](https://bytelaunch15.s3.amazonaws.com/Screen-Shot-2022-02-16-16-45-00.50.png)

✅ This works
![Image](https://bytelaunch15.s3.amazonaws.com/Screen-Shot-2022-02-16-16-46-00.53.png)

**Comment by flamber** [comment] 2022-02-17 08:15
Duplicate of #3324
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#field-filters-dont-work-with-table-aliases

**Closed by flamber** 2022-02-17 08:15 UTC
Labels: Type:Bug, .Needs Triage
