### ISSUE TITLE
Type inference fails for metabase parameters

### ISSUE THREAD

**Issue by willhurley004** [metabase/metabase#11870] opened 2020-02-07 22:38 UTC
**Describe the bug**
Type inference fails for metabase parameters
<img width="1175" alt="Screen Shot 2020-02-07 at 5 29 13 PM" src="https://user-images.githubusercontent.com/10673246/74071073-d1cb2c80-49d0-11ea-8d52-b78b66f1c1d1.png">
<img width="356" alt="Screen Shot 2020-02-07 at 5 29 49 PM" src="https://user-images.githubusercontent.com/10673246/74071074-d1cb2c80-49d0-11ea-9de4-853f68cd92d3.png">

<img width="585" alt="Screen Shot 2020-02-07 at 5 37 03 PM" src="https://user-images.githubusercontent.com/10673246/74070970-7d27b180-49d0-11ea-8f98-8bf007be188d.png">

**Expected behavior**
params of type integer would remain an integer

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.14.128-112.105.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-11-19",
      "tag": "v0.33.6",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by flamber** [comment] 2020-02-08 15:35
Hi @willhurley004 
Could you please try 0.34.2?
It looks like a possible regression of #5632
Adding error, so it's searchable: `ERROR: operator does not exist: bigint = character varying Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts. Position: 284`

**Comment by sarahgriffis** [comment] 2020-02-10 17:57
@flamber Thanks for the quick response, we will do the update tomorrow and let you know!

**Comment by dacort** [comment] 2020-02-11 00:07
Duplicate of #11883 - please follow that one, thanks for the report!

**Closed by dacort** 2020-02-11 00:07 UTC
Labels: Database/Postgres, Priority:P2, Querying/Native, Querying/Parameters & Variables, Type:Bug
