### ISSUE TITLE
Request canceled before finishing.

### ISSUE THREAD

**Issue by agladboy** [metabase/metabase#11790] opened 2020-01-24 05:33 UTC
**Describe the bug**
When trying to download the query results to the csv file, the metabase become unavailable.
query result records are far less then million. 

**Logs**
`{"log":"01-23 21:10:21 \u001b[1mDEBUG middleware.log\u001b[0m :: \u001b[32mGET /api/card/549 200 386 ms (5 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (54 total active threads) Queries in flight: 0\u001b[0m\n","stream":"stdout","time":"2020-01-24T05:10:21.069047397Z"}
{"log":"01-23 21:10:21 \u001b[1mDEBUG middleware.log\u001b[0m :: \u001b[32mGET /api/collection/root 200 152 ms (2 DB calls) Jetty threads: 6/50 (1 idle, 0 queued) (55 total active threads) Queries in flight: 0\u001b[0m\n","stream":"stdout","time":"2020-01-24T05:10:21.423560271Z"}
{"log":"01-23 21:10:21 \u001b[1mDEBUG middleware.log\u001b[0m :: \u001b[32mGET /api/alert/question/549 200 77 ms (1 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (56 total active threads) Queries in flight: 0\u001b[0m\n","stream":"stdout","time":"2020-01-24T05:10:21.512860139Z"}
{"log":"01-23 21:10:21 \u001b[1mINFO api.card\u001b[0m :: Question's average execution duration is 160850 ms; using 'magic' TTL of 1609 seconds 💾\n","stream":"stdout","time":"2020-01-24T05:10:21.750183979Z"}
{"log":"01-23 21:10:21 \u001b[1mINFO middleware.cache\u001b[0m :: Returning cached results for query 💾\n","stream":"stdout","time":"2020-01-24T05:10:21.973009673Z"}
{"log":"01-23 21:10:22 \u001b[1mDEBUG middleware.log\u001b[0m :: \u001b[32mPOST /api/card/549/query 200 [ASYNC: completed] 577 ms (6 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (56 total active threads) Queries in flight: 0\u001b[0m\n","stream":"stdout","time":"2020-01-24T05:10:22.044643026Z"}
{"log":"01-23 21:10:58 \u001b[1mINFO api.card\u001b[0m :: Question's average execution duration is 123314 ms; using 'magic' TTL of 1233 seconds 💾\n","stream":"stdout","time":"2020-01-24T05:10:58.797079065Z"}
{"log":"01-23 21:13:50 \u001b[1mINFO middleware.cache\u001b[0m :: Query took 171779 ms to run; miminum for cache eligibility is 60000 ms\n","stream":"stdout","time":"2020-01-24T05:13:50.576844888Z"}
{"log":"01-23 21:13:50 \u001b[1mINFO middleware.cache\u001b[0m :: Caching results for next time for query 💾\n","stream":"stdout","time":"2020-01-24T05:13:50.576882615Z"}
{"log":"01-23 21:13:50 \u001b[1mINFO cache-backend.db\u001b[0m :: Results are too large to cache. 😫\n","stream":"stdout","time":"2020-01-24T05:13:50.977636309Z"}
{"log":"01-23 21:13:52 \u001b[1mDEBUG middleware.log\u001b[0m :: \u001b[32mPOST /api/card/549/query/csv 200 3 mins (11 DB calls) Jetty threads: 3/50 (5 idle, 0 queued) (54 total active threads) Queries in flight: 0\u001b[0m\n","stream":"stdout","time":"2020-01-24T05:13:52.859236449Z"}
{"log":"01-23 21:13:52 \u001b[1mINFO middleware.exceptions\u001b[0m :: Request canceled before finishing.\n","stream":"stdout","time":"2020-01-24T05:13:52.865846228Z"}
{"log":"01-23 21:13:52 \u001b[1mERROR middleware.log\u001b[0m :: Error logging API request\n","stream":"stdout","time":"2020-01-24T05:13:52.866187238Z"}
{"log":"java.lang.NullPointerException\n","stream":"stdout","time":"2020-01-24T05:13:52.86620453Z"}`

**Expected behavior**
The CSV file should be able to be downloaded.

**Severity**
It prevents to use the download functionality and cannot save the query results.

**Comment by dacort** [comment] 2020-01-24 22:34
Hi @agladboy 

Can you provide some more info for us or help to reproduce this? It's tough to say what's going on here.

- Metabase instance details (Diagnostic info from Admin --> Troubleshooting page)
- Which database you are connecting to
- How long it takes before you get the error
- Do you receive an error in the browser?

It's certainly possible that whatever data source you're connecting to is timing out the connection if it's taking too long. This is very common if you have a load balancer or proxy in front of Metabase like nginx - here's how other folks have solved that specific issue on the [forum](https://discourse.metabase.com/t/504-error-on-download-csv-xlsx/7402/7?u=dacort).

**Comment by flamber** [comment] 2020-04-02 13:12
This is likely a duplicate of #10108 or #9533, which most likely have been fixed in 0.35.0

**Closed by flamber** 2020-04-02 13:12 UTC
Labels: .Need More Info, Type:Bug

**Comment by gilnei-ferraz** [comment] 2020-09-01 01:37
I had the same problem using Metabase 0.36.3 in Rancher / Heml. I initially checked the Nginx reverse proxy timeout settings, but they were all correct. So I activated the option to automatically redirect all requests to HTTPS option and I didn't notice these errors in the log anymore.

**Comment by NickYang1988** [comment] 2021-09-01 07:50
Same problem in 0.39.1

**Comment by flamber** [comment] 2021-09-01 07:57
@NickYang1988 
Latest release is 0.40.3.1: https://github.com/metabase/metabase/releases/latest
And without more details of the actual errors you're seeing, then it's impossible to help.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
