### ISSUE TITLE
Filter after a date is exclusive

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#22465] opened 2022-05-05 18:24 UTC
**Describe the bug**
When filtering by dates, the "after" filter shifts 1 day from the day you select, forcing you to select the time in order to make it inclusive

e.g.: orders after 6th of Dec 2019:
```
SELECT "public"."orders"."id" AS "id", "public"."orders"."user_id" AS "user_id", "public"."orders"."product_id" AS "product_id", "public"."orders"."subtotal" AS "subtotal", "public"."orders"."tax" AS "tax", "public"."orders"."total" AS "total", "public"."orders"."discount" AS "discount", "public"."orders"."created_at" AS "created_at", "public"."orders"."quantity" AS "quantity"
FROM "public"."orders"
WHERE "public"."orders"."created_at" >= timestamp with time zone '2019-12-07 00:00:00.000Z'
LIMIT 1048575
```

orders before 6th of Dec 2019:
```
SELECT "public"."orders"."id" AS "id", "public"."orders"."user_id" AS "user_id", "public"."orders"."product_id" AS "product_id", "public"."orders"."subtotal" AS "subtotal", "public"."orders"."tax" AS "tax", "public"."orders"."total" AS "total", "public"."orders"."discount" AS "discount", "public"."orders"."created_at" AS "created_at", "public"."orders"."quantity" AS "quantity"
FROM "public"."orders"
WHERE "public"."orders"."created_at" < timestamp with time zone '2019-12-06 00:00:00.000Z'
LIMIT 1048575
```

**Logs**
NA

**To Reproduce**
1) go to new->question->orders
2) filter by created_at before Dec 6th 2019, everything is fine
3) now filter by created_at after Dec 6th 2019, you'll see that it starts on the 7th

**Expected behavior**
Filter should be inclusive like
```
SELECT "public"."orders"."id" AS "id", "public"."orders"."user_id" AS "user_id", "public"."orders"."product_id" AS "product_id", "public"."orders"."subtotal" AS "subtotal", "public"."orders"."tax" AS "tax", "public"."orders"."total" AS "total", "public"."orders"."discount" AS "discount", "public"."orders"."created_at" AS "created_at", "public"."orders"."quantity" AS "quantity"
FROM "public"."orders"
WHERE "public"."orders"."created_at" >= timestamp with time zone '2019-12-06 00:00:00.000Z'
LIMIT 1048575
```

**Screenshots**
NA

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop-os 22.04
- Your databases: Postgres 14
- Metabase version: 1.43.0
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14

**Severity**
P2ish

**Additional context**
I don't know why Metabase uses timestamp with timezone in the query if the field in the DB is defined as a timestamp only

**Comment by flamber** [comment] 2022-05-10 12:58
If we were creating incorrect results based on a regular filter like Before/After, then this would have been a P1 bug.

Using 2019-12-06 as the date:
Selecting **After** means it will show anything from the 7th and onward.
Selecting **Before** will showing anything from the 5th and previous.

Neither will be inclusive, since that's not what the wording means.

This is not a bug.

**Closed by flamber** 2022-05-10 12:58 UTC
Labels: Type:Bug, Priority:P2, Querying/Parameters & Variables

**Comment by paoliniluis** [comment] 2022-05-11 18:56
Thanks! can we add this to the documentation? @jeff-bruemmer
