### ISSUE TITLE
Questions List not showing all questions when Adding from Dashboard

### ISSUE THREAD

**Issue by sabino** [metabase/metabase#7813] opened 2018-06-06 18:55 UTC
### Bug

When we try to add a question from within a dashboard, not all the questions are showing up.
Looks like a limit or something.

- Your browser and the version: Chrome 66.0.3359.181
- Your operating system: OSX 10.13.4
- Your databases: Redshift
- Metabase version: 0.29.3
- Metabase hosting environment: EC2
- Metabase internal database: RDS Postgres

*Repeatable steps to reproduce the issue*
- Add 25+ questions
- Create an empty dashboard
- Use the button Add Question from the dashboard
- Check if all the questions are showing

![questions list](https://user-images.githubusercontent.com/982190/41059046-d64746ba-69a1-11e8-8515-6c4020cdc0d2.gif)

**Comment by salsakran** [comment] 2018-07-06 04:28
I can't seem to reproduce this, @sabino . 

Can you double check what the API response is returning via the network inspector in chrome? I.e. is it getting more than 25 back but not showing them, or is the api not returning all of them?

**Comment by kdoh** [comment] 2018-11-30 20:31
I'm going to go ahead and close this issue since we've completely revamped both this UI and how we load questions in the add to dash modal since it was reported. @sabino if you've upgraded to version 0.30 or greater and still see this problem please let us know and we can reopen this.

**Closed by kdoh** 2018-11-30 20:31 UTC
Labels: Bug, Dashboards, Priority/P3
