### ISSUE TITLE
Redshift results are not showing up on Metabase post update to 0.36.0

### ISSUE THREAD

**Issue by gaurav-dingolia-vogo** [metabase/metabase#13049] opened 2020-07-31 16:29 UTC
**Describe the bug**
Post updating to `v0.36.0` from `v0.35.4`, results from Redshift are not showing on Metabase.

**Logs**
```
metabase-temp-687bc4b9b-l8mmb metabase   "com.amazon.redshift.api.PGTimestamp.toString(Unknown Source)"
metabase-temp-687bc4b9b-l8mmb metabase   "com.amazon.redshift.api.PGTimestamp.getPostgresqlString(Unknown Source)"
metabase-temp-687bc4b9b-l8mmb metabase   nil],
metabase-temp-687bc4b9b-l8mmb metabase  :context :ad-hoc,
metabase-temp-687bc4b9b-l8mmb metabase  :error nil,
metabase-temp-687bc4b9b-l8mmb metabase  :row_count 0,
metabase-temp-687bc4b9b-l8mmb metabase  :running_time 0,
metabase-temp-687bc4b9b-l8mmb metabase  :data {:rows [], :cols []}}
```
**To Reproduce**
1. Go to Native Query
2. Write any simple `SELECT *` query

**Expected behavior**
Results from Redshift should display on Metabase

**Screenshots**
<img width="1407" alt="Screenshot 2020-07-31 at 9 56 48 PM" src="https://user-images.githubusercontent.com/45032008/89055907-d1589080-d378-11ea-879e-e5191dbfee3d.png">

**Severity**
Blocking usage of Metabase

**Comment by flamber** [comment] 2020-07-31 16:47
Hi @gaurav-dingolia-vogo 
Please post "Diagnostic Info" from Admin > Troubleshooting.
And can you post the full stacktrace?
Please try 0.36.1, which was released yesterday and fixed a problem with filters on Redshift.

**Comment by gaurav-dingolia-vogo** [comment] 2020-07-31 18:49
```
{
  "browser-info": {
    "language": "en-gb",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "4.14.181-140.257.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Calcutta"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-07-30",
      "tag": "v0.36.1",
      "branch": "release-0.36.x",
      "hash": "55312e4"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

Yes, I already tried updating it to 0.36.1 but it didn't help, issue still persists.

**Comment by flamber** [comment] 2020-07-31 18:52
@gaurav-dingolia-vogo Please post the full stacktrace error.
Which column types do you have in that table?

**Comment by flamber** [comment] 2020-08-11 12:39
Closing, since not enough information has been provided to reproduce this issue.

**Closed by flamber** 2020-08-11 12:39 UTC
Labels: .Need More Info, .Unable to Reproduce, Database/Redshift, Type:Bug
