### ISSUE TITLE
Slack preview diverges from original on unstacked bar chart (sql)

### ISSUE THREAD

**Issue by kassi** [metabase/metabase#21666] opened 2022-04-14 06:11 UTC
**Describe the bug**
A bar graph with high variance in the bars looks completely different in the slack preview than on the dashboard.
Seems like each bar uses its own scaling.
I had to remove stacking because of https://github.com/metabase/metabase/issues/20752 (got the same error).

1. The colors are different.
2. The dates shown are off by one day. (My week in metabase is calculated to Monday while slack preview obviously still starts at Sunday).
3. The bars are too big for second to last group bar.
4. There's a second y-axis label on the right in slack which is not set up in metabase (I intentionally disabled "Use a split y-axis when necessary).

If I take a deep look into each graph, I can see the same pattern week by week for each bar individually. However the number on the left y-axis only fits to the leftmost bar.

**To Reproduce**
Sorry, we don't have the samples database installed.
1. Create question (from SQL query) with timestamp, some group and count. Roughly
```
SELECT created_at, username, count(*) as count
FROM (
  SELECT str_to_date(concat(yearweek(`slack_messages`.`created_at`), ' Monday'), '%X%V %W') AS `created_at`, username
) as msgs
GROUP BY created_at, username
ORDER BY str_to_date(concat(yearweek(`created_at`), ' Monday'), '%X%V %W') ASC, `username` ASC
```
2. Set stacking to don't stack
3. Enable Auto y-axis range (because I don't know the range upfront)
2. Create dashboard with this one question
4. Create dashboard subscription and send to slack
5. Compare graphs

**Expected behavior**
The  graph in the slack preview should look the same as in metabase.

**Screenshots**
Metabase:
<img width="1065" alt="Metabase screenshot" src="https://user-images.githubusercontent.com/993392/163321468-cc657b6d-3100-4e3b-9675-7a3b610405e3.png">
Slack:
<img width="1189" alt="Slack sceenshot" src="https://user-images.githubusercontent.com/993392/163321358-0794da9d-a339-4323-b974-dbdf0e4e6dab.png">

**Information about your Metabase Installation:**
- Your operating system: Ubuntu
- Your databases:MySQL 8.0.19
- Metabase version: 0.42.2
- Metabase hosting environment: Docker
- Metabase internal database: MySQL 8.0.19

**Severity**
Blocked: Makes metabot slack connector unusable.

**Additional context**
Metabase settings: First day of week: Monday

**Comment by flamber** [comment] 2022-04-18 11:39
Duplicate of #20559/#21506

**Closed by flamber** 2022-04-18 11:39 UTC
Labels: Type:Bug, .Needs Triage
