### ISSUE TITLE
The field filtering function does not automatically execute the query

### ISSUE THREAD

**Issue by 8debug** [metabase/metabase#15326] opened 2021-03-25 00:34 UTC
v0.38.2

The field filtering function does not automatically execute the query

After setting the filter conditions, I need to manually execute the query

https://user-images.githubusercontent.com/3394927/112401087-b3df9900-8d44-11eb-903a-500aa6a8d85f.mp4

**Comment by flamber** [comment] 2021-03-25 08:53
Duplicate of #13694

**Closed by flamber** 2021-03-25 08:53 UTC
Labels: .Needs Triage, Type:Bug
