### ISSUE TITLE
Really Impossible Slow - Data Reference and MultiCard Questions

### ISSUE THREAD

**Issue by sabino** [metabase/metabase#5195] opened 2017-05-25 19:54 UTC
### Bug
- Your browser and the version: Chrome 58.0.3029.110 (64-bit)
- Your operating system: Manjaro 17.0.1
- Your databases: Postgres
- Metabase version: 0.24
- Metabase hosting environment: Ubuntu 12
- Metabase internal database: Postgres

# 
- *Repeatable steps to reproduce the issue*

I'm not sure how to repeat this.
We currently have a huge database with 15 schemas and 381 tables that translates to 4080 columns. It takes roughly two days to finish syncing and by that time more columns and values will be added.

I am aware that this is being refactored. But our problem is that because of the big database it simply doesn't not load (it actually does but it takes 15min+) the Data Reference, nor when you add a chart onto another chart.

https://gifyu.com/images/0d825cca456cc1149348ee63237e9a7d.gif (18mb accelerated gif)

**Comment by salsakran** [comment] 2017-06-03 02:44
This was partially alleviated in #5197 (which is in 0.24.2) and is a dupe of #5196, where we will do a bit more performance improvement for 0.25.0

**Closed by salsakran** 2017-06-03 02:44 UTC
Labels: Performance
