### ISSUE TITLE
"select" admin settings are busted: showing keys instead of user-friendly descriptions

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#12560] opened 2020-05-20 22:05 UTC
This is in `master`. Instead of `advanced` it should be displaying `Enabled` -- `advanced` is the internal value, and `Enabled` is the user-facing description.

![image](https://user-images.githubusercontent.com/1455846/82502078-3a837400-9aab-11ea-9dac-ea99b32d0d6f.png)

**Comment by kdoh** [comment] 2020-05-22 21:58
I *think* this was introduced by changes in https://github.com/metabase/metabase/pull/11522  It only seems to be an issue if a setting is using the out of the box default.

**Comment by flamber** [comment] 2020-06-06 14:04
This is fixed on `master`, but not sure which PR it was.

**Comment by daltojohnso** [comment] 2021-02-05 19:14
Can confirm that the issue is fixed, so I am closing this issue. I've opened #14682 to fix the issue with the Report Timezone dropdown that @flamber noted.

**Closed by daltojohnso** 2021-02-05 19:14 UTC
Labels: .Frontend, Admin Panel & Setup, Administration/Settings, Priority:P3, Type:Bug
