### ISSUE TITLE
Y axis scale / proportion of emailed bar chart does not match dashboard bar chart

### ISSUE THREAD

**Issue by linovitz** [metabase/metabase#25760] opened 2022-10-03 17:38 UTC
**Describe the bug**
Y axis scale and proportion of emailed bar charts does not match dashboard. It also looks like y axis is being rounded to a whole number when it shouldn't be rounded - it should just match the formatting in the dashboard. 

**To Reproduce**
1. Create a bar chart in a dashboard with manually set Y axis scale
2. Schedule an alert to email you a report
3. Compare the charts in email to the one in the dashboard

**Expected behavior**
Emailed bar charts should match bar chart in dashboard (scale number rounder formatting and proportion)

**Screenshots**
Emailed version:
<img width="517" alt="Screen Shot 2022-10-03 at 10 21 08 AM" src="https://user-images.githubusercontent.com/87673011/193640682-f189ac6e-50ff-478d-b4e7-48ae386c4249.png">

Dashboard version:
<img width="349" alt="Screen Shot 2022-10-03 at 10 23 33 AM" src="https://user-images.githubusercontent.com/87673011/193640704-25b4366a-3fab-452a-8638-4f644c090b8a.png">

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "3.13.0-142-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-17",
      "tag": "v0.42.1",
      "branch": "release-x.42.x",
      "hash": "629f4de"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

- Your browser and the version: N/A
- Your operating system: N/A
- Your databases:  Postgres
- Metabase version: 0.42.1

**Severity**
This makes the reporting functionality hard to use. You can get a sense of the metric but not the exact numbers. So you can't use this report to compare previous weeks or months.

**Comment by flamber** [comment] 2022-10-03 17:58
Duplicate of #20552

**Closed by flamber** 2022-10-03 17:58 UTC
Labels: Type:Bug, .Needs Triage

**Comment by linovitz** [comment] 2022-10-03 18:39
@flamber this is not a duplicate. what I am referring to is only visible in the scheduled email report notifications. https://metabase.syncsketch.com/account/notifications

**Comment by flamber** [comment] 2022-10-03 18:41
@linovitz Exactly what the issue is, but you are using an old version of Metabase, so upgrade to latest before opening issues.

**Comment by linovitz** [comment] 2022-10-03 18:43
@flamber it was not clear in your bug that it applied to emailed charts too. thank you for explaining the versioning - didn't realize. I am a new admin on the site so have not been aware of versioning changes.
