### ISSUE TITLE
Disable editing rights on Dashboards

### ISSUE THREAD

**Issue by kapilssn001506** [metabase/metabase#6005] opened 2017-09-19 08:22 UTC
Team,

Need to remove the rights to edit the dashboard from All Users group.

Please suggest a way for it.

**Comment by flamber** [comment] 2019-02-16 23:58
Hi @kapilssn001506 
I cannot reproduce your issue on 0.31.2 - I think this was fixed as part of the Collections overhaul in 0.30

**Comment by flamber** [comment] 2020-03-02 18:47
Closing issue because of no reply and I cannot reproduce on 0.34.3

**Closed by flamber** 2020-03-02 18:47 UTC
Labels: .Proposal, Administration/Permissions
