### ISSUE TITLE
Informix Driver

### ISSUE THREAD

**Issue by grimete** [metabase/metabase#10820] opened 2019-09-06 08:15 UTC
**Describe the solution you'd like**
Possibility to define an IBM Informix database as a database type, i.e. as data source for our queries. 

**Describe alternatives you've considered**
A lot of our "reporting" data is also ingested by Elastic Search, but there is no driver either for ELK...

**How important is this feature to you?**
Our company is an Informix shop, gradually moving to MySQL, Oracle, etc... but we still have lots of data and applications, running Informix databases.

**Comment by flamber** [comment] 2019-09-06 08:18
Hi @grimete Looks like a duplicate of #5248, which you commented on...?

**Comment by grimete** [comment] 2019-09-06 08:19
Hi @flamber you are right, I did not remember !
Shall I close it?
Sorry for duplicating issues :-(

**Comment by flamber** [comment] 2019-09-06 08:20
Yes, please close this issue. And in the future, please do a quick search :+1:

**Closed** 2019-09-06 08:21 UTC
Labels: Type:New Feature
