### ISSUE TITLE
Collections View Permissions failing after upgrade to 0.33.5

### ISSUE THREAD

**Issue by timmclaughlin** [metabase/metabase#11297] opened 2019-11-12 10:57 UTC
Upgraded to 0.33.5 and now the ability to view Saved Questions is broken.  On the previous version, Users with View permissions on a Sub-collection previously could view the Question without access to the underlying data, but now they cannot.  If I give "Grant Unrestricted Access" to the group, then the user can run the saved question.  I believe that the new behavior is incorrect because it kind of defeats the point of saved collections.

Here's the javascript console of the error:
![image](https://user-images.githubusercontent.com/3425622/68666034-1ef24c00-0511-11ea-8c2f-3889f0f17510.png)

To be clear, the user can see the Subcollection and Question, but clicking on the question only provides the perpetual spinner with the error above.

**Comment by flamber** [comment] 2019-11-12 14:15
Hi @timmclaughlin 
Can you post the Diagnostic Info from Admin > Troubleshooting?
Do you see any errors in the log, when it's just spinning?
Which version did you upgrade from?

**Comment by timmclaughlin** [comment] 2019-11-12 17:45
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_232-heroku-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_232-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.232-b09",
    "os.name": "Linux",
    "os.version": "4.4.0-1048-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.5",
      "date": "2019-11-08",
      "branch": "release-0.33.x",
      "hash": "d9d6f72"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}

And logs are:
[1af00049-8ce7-4249-8940-199ad3b0889e] 2019-11-12T12:44:07-05:00 DEBUG metabase.middleware.log GET /api/collection/13 200 22.0 ms (3 DB calls) Jetty threads: 5/50 (3 idle, 0 queued) (63 total active threads) Queries in flight: 0
[1af00049-8ce7-4249-8940-199ad3b0889e] 2019-11-12T12:44:09-05:00 DEBUG metabase.middleware.log GET /api/card/46 200 17.3 ms (6 DB calls) Jetty threads: 5/50 (3 idle, 0 queued) (63 total active threads) Queries in flight: 0
[1af00049-8ce7-4249-8940-199ad3b0889e] 2019-11-12T12:44:10-05:00 DEBUG metabase.middleware.log GET /api/alert/question/46 200 7.8 ms (1 DB calls) Jetty threads: 5/50 (3 idle, 0 queued) (63 total active threads) Queries in flight: 0
[1af00049-8ce7-4249-8940-199ad3b0889e] 2019-11-12T12:44:10-05:00 WARN metabase.middleware.log GET /api/table/308/query_metadata 403 7.7 ms (3 DB calls)
"You don't have permissions to do that."

[1af00049-8ce7-4249-8940-199ad3b0889e] 2019-11-12T12:44:10-05:00 WARN metabase.middleware.log GET /api/table/308/fks 403 9.5 ms (3 DB calls)
"You don't have permissions to do that."

I can't remember the version, but I probably upgraded less than 3 or 4 months ago to the most recent version.

**Comment by mazameli** [comment] 2019-11-12 18:21
Here's what I've found:

**As of 0.33.0 up through 0.33.3,** there was a problem where if a user only had view/curate permissions for a collection, but not underlying data permissions for the table the question was based on, you'd see a screen like this when trying to view the question:

![Screen Shot 2019-11-12 at 10 07 37 AM](https://user-images.githubusercontent.com/2223916/68698173-33484000-0535-11ea-9369-c6ddc5d291af.png)

**In 0.33.4 and continuing in 0.33.5**, there seems to be a problem specifically with GUI-based questions (not SQL/native ones) where users that have view/curate collection permissions, but not data access permissions to the table the saved question uses, are getting a 403 error when trying to open a saved question: `Failed to load resource: the server responded with a status of 403 (Forbidden)`

![Screen Shot 2019-11-12 at 10 11 43 AM](https://user-images.githubusercontent.com/2223916/68698257-6985bf80-0535-11ea-9b31-fcafa6406f6c.png)

Marking this as a P1 rather than a P0 because it's restricting more access than should be allowed instead of _granting_ more access, but if anyone on @metabase/core-developers disagrees, please chime in.

**Comment by mazameli** [comment] 2019-11-12 18:26
Another note: if you have a dashboard that includes GUI questions in that same collection, the questions _do_ render there, but clicking on any GUI question to go to its detail still results in that same 403 error.

![image](https://user-images.githubusercontent.com/2223916/68698910-cfbf1200-0536-11ea-8407-28c1e265b70c.png)

Are you experiencing that same behavior, @timmclaughlin?

**Comment by timmclaughlin** [comment] 2019-11-12 19:40
@mazameli You are correct.  Dashboards do show the data without the data permissions, but clicking into the question fails.

**Comment by timmclaughlin** [comment] 2019-11-14 22:03
@mazameli Not sure how important a P1 is, but I can say this makes my use of Metabase dead in the water because nobody can access their reports.  Is this an edge case use of Metabase?  The best work around I can think of is to create a new view for each user and give them data access to that view to make this work.  Kludgy, but if this isn't considered a core feature, I'll go ahead with some kind of work around.

**Comment by camsaul** [comment] 2019-11-14 22:42
@mazameli In 0.33.5 we changed the type of the `database_type` column to be `TEXT` instead of `VARCHAR` (#11043) so if you're running H2 and then revert back to pre-0.33.5 you'll see that error. It doesn't affect Postgres or MySQL.

**Comment by flamber** [comment] 2019-11-14 22:57
@timmclaughlin 
I did a quick test on 0.33.3 and it does not have this issue. Of course, you're missing out on all the other fixes, but if they're not impacting you at the same level, then take 0.33.3 for a spin.
Remember to always backup before downgrading/upgrading!
That's probably the quickest workaround - and then when this is fixed, then you can upgrade.

**Comment by timmclaughlin** [comment] 2019-11-14 23:00
@flamber I'll give that a go.  Thanks!

**Comment by paulrosenzweig** [comment] 2019-11-14 23:46
It looks like this was the change that broke it: `https://github.com/metabase/metabase/pull/10981/files#diff-f6fa358f37cc8e642b13e3a9f07d3204L455`

**Comment by camsaul** [comment] 2019-11-15 01:47
This seems like it's almost an exact regression of #10402, we should really get some tests around rendering questions with limited permissions

**Comment by paulrosenzweig** [comment] 2019-11-18 22:49
The main issue where the question fails to load is fixed in #11326 and will go out with the next release.

I've created #11344 for the set of other improvements for this state.

**Closed by paulrosenzweig** 2019-11-18 22:49 UTC
Labels: Administration/Permissions, Priority:P1, Type:Bug

**Comment by timmclaughlin** [comment] 2019-11-18 22:58
thanks, guys!
