### ISSUE TITLE
Dashboard Embedded. Error passing various parameters when using a list of values

### ISSUE THREAD

**Issue by jlisyc** [metabase/metabase#16123] opened 2021-05-18 09:37 UTC
**Describe the bug**
Dashboard Embedded. Error passing various parameters when using a list of values

**To Reproduce**
1. REPORT PRODUCTS with ID and TITLE columns
2. Embed Dashboard with that report and a filter ID 
![image](https://user-images.githubusercontent.com/33416503/118626947-97536080-b7cb-11eb-8a78-aef32e89f286.png)

3. Embed dashboard with filter ID locked . Use value 1. It works ok
![image](https://user-images.githubusercontent.com/33416503/118627084-b520c580-b7cb-11eb-9da3-9b0937527d9e.png)

4. Use various values. ERROR/BUG
![image](https://user-images.githubusercontent.com/33416503/118627257-da153880-b7cb-11eb-8feb-c9ccdd1ca73b.png)

Error passing a list 
![image](https://user-images.githubusercontent.com/33416503/118627393-f6b17080-b7cb-11eb-8b6f-a6cedf4394b7.png)

**Expected behavior**
When passing various parameters as a list, it should show results correctly (it works in previous versions)

**Severity**
Very important because we use a lot embeded dashboards with parameters.

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.214 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "5.4.0-70-generic",
    "user.language": "en",
    "user.timezone": "Europe/Brussels"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.21"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-03-03",
      "tag": "v0.36.12",
      "branch": "release-0.36.x",
      "hash": "1ea38d4"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}

**Comment by flamber** [comment] 2021-05-18 09:55
Duplicate of #9266

**Closed by flamber** 2021-05-18 09:55 UTC
Labels: .Needs Triage, Type:Bug
