### ISSUE TITLE
Metabase jar behind a reverse proxy fails to load assets

### ISSUE THREAD

**Issue by roemhildtg** [metabase/metabase#2206] opened 2016-03-22 19:09 UTC
If this is a bug report, please fill in the blanks:

*  I am using the Chrome 49.0.2623.87 browser.
*  My computer's OS is Windows 7 x64.
*  I'm running Metabase locally from the JAR with a reverse proxy from nginx. 
*  My database is Postgresql
*  My Metabase version is latest

Metabase is running on a dev machine at http://ipaddress/metabase but it is trying to load files from /app/...

The url should be /metabase/app/...

```
http://192.168.10.133/app/dist/styles.bundle.css?58534d1700eb72fa332b331556e0f4a7 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
http://192.168.10.133/app/dist/vendor.bundle.js?99f33dfda584cd25b4af Failed to load resource: the server responded with a status of 404 (NOT FOUND)
http://192.168.10.133/app/dist/styles.bundle.js?99f33dfda584cd25b4af Failed to load resource: the server responded with a status of 404 (NOT FOUND)
http://192.168.10.133/app/dist/app.bundle.js?99f33dfda584cd25b4af Failed to load resource: the server responded with a status of 404 (NOT FOUND)
http://192.168.10.133/app/dist/styles.bundle.css?58534d1700eb72fa332b331556e0f4a7 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
```

**Comment by tlrobinson** [comment] 2016-03-22 19:10
Duplicate of #2090

**Closed by tlrobinson** 2016-03-22 19:10 UTC
