### ISSUE TITLE
Newly saved question not listed when starting a new question until page refresh

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#11812] opened 2020-01-28 12:27 UTC
**Describe the bug**
After saving a question and starting a new one, the saved question is not listed in the "Saved questions" list until user refreshes the page.

**To Reproduce**
1. Create a new simple question from any table and save it.
2. Start creating a new simple question.
3. When presented with the table selection dialog, choose "Saved questions".
4. Observe the question saved in (1) is not listed.

**Expected behavior**
The table selection dialog should present real-time instead of cached data.

**Information about your Metabase Installation:**
`{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1; Windows for Workgroups 3.11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.15.0-66-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "date": "2019-12-19",
      "tag": "v0.34.0",
      "branch": "release-0.34.x",
      "hash": "1335215"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}`

**Severity**
A nuisance as we have to explain this to our customers. This somewhat undermines the trust in our product.

**Comment by andreychirikba** [comment] 2020-01-28 12:32
Another case of caching the state:
1. Configure mail server info.
2. Reload the page.
3. Delete mail server info.
4. Create a new user.
5. Observe Metabase reports an invitation mail has been sent out (actually it hasn't).
Now the password is unknown and admin needs to reload the page and reset user password to see it.

I would suggest Metabase needs to refresh its state on every page navigation, at least the relevant part of it.

**Comment by dacort** [comment] 2020-01-29 00:27
Hi @andreychirikba, thanks for the bug report! The first issue is a duplicate of #9027. Please upvote that issue by adding a 👍 to the top comment.

I need to look around to see if the second issue exists anywhere.

**Closed** 2020-01-29 01:19 UTC
Labels: .Duplicate, Type:Bug
