### ISSUE TITLE
When using aggregate functions in SQL Query, Pivot Option in Visualisation should be enabled. Or Provide Workaround in Tablular Viz

### ISSUE THREAD

**Issue by dixitshubhashish** [metabase/metabase#25147] opened 2022-08-31 15:23 UTC
If a user is writing question with count('column3') and group by column1, column2, Metabase allows users to do a pivot table, but when the same thing user tries to do by writing SQL queries, the functionality of the pivot table is disabled, it should be enabled as sometimes user expects total as well in the end. 

If this can't be done for the question, then at least in the "Table" format where the pivot is allowed add an option to show "Total", and "SubTotal". This will solve the pivot problem, and this can be treated as workaround for the former requirements.

Please use the issue chooser, when creating a new issue:

https://github.com/metabase/metabase/issues/new/choose

**Comment by flamber** [comment] 2022-08-31 15:27
Metabase doesn't know you are doing aggregations in SQL.
https://www.metabase.com/learn/visualization/how-to-create-pivot-tables#how-to-create-pivot-tables-limitations
Duplicate of #19862

**Closed by flamber** 2022-08-31 15:27 UTC

**Comment by dixitshubhashish** [comment] 2022-08-31 15:31
Metabase can read SQL and then identify the string like count, sum, min,
max etc to decide that the user is trying to do aggregate. Even if it is
not, you can ask users whether they are trying to aggregate as yes/no pop
and let the user decide what to do. Why blocking on such small issues?



*Warm Regards,Dixit Shubhashish*
 *Volunteering is not a choice, it's a responsibility**.*
LEGAL DISCLAIMER: This e-mail may contain confidential and/or legally
privileged information and is meant for the intended recipient(s) only. If
you have received this e-mail in error and are not the intended
recipient(s, kindly notify us at ***@***.***
***@***.***> and then delete this e-mail immediately from
your system.
