### ISSUE TITLE
Impossible to add more options for a kpi in a combo visualization

### ISSUE THREAD

**Issue by ZohaSpark** [metabase/metabase#17917] opened 2021-09-16 09:32 UTC
**Describe the bug**
When going into the settings of a combo question, we can not click on the more options button.

**To Reproduce**
1. Go to a combo question
2. Click on Settings
3. Scroll down to a kpi
4. Try clicking on "More options"

**Expected behavior**
Being able to add more options for a given kpi.

**Screenshots**
![image](https://user-images.githubusercontent.com/87467508/133586398-19d9b176-dab9-42f1-a644-51623c95c0a7.png)

**Information about your Metabase Installation:**

```{
  "browser-info": {
    "language": "fr-FR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.14.238-182.422.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.9"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-08-17",
      "tag": "v0.40.3",
      "branch": "release-x.40.x",
      "hash": "c82665c"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}
```

**Severity**
It can be annoying, it's not preventing us from using the data, but the visualization is not quite on point for us and our colleagues.

**Comment by flamber** [comment] 2021-09-16 09:57
Duplicate of #17619 - fixed in 0.40.3.1 - latest release is 0.40.4: https://github.com/metabase/metabase/releases/latest

**Closed by flamber** 2021-09-16 09:57 UTC
Labels: Type:Bug, .Needs Triage
