### ISSUE TITLE
Mixing area and line chart mis-align labels for ordinal x-axis

### ISSUE THREAD

**Issue by EBoisseauSierra** [metabase/metabase#12033] opened 2020-03-03 13:00 UTC
## Bug description

When creating a combo graph mixing area and line traces, the labels of an ordinal x-axis are offset by half an interval:

* **Actual**  
![Screenshot from 2020-03-03 12-45-37_shadow](https://user-images.githubusercontent.com/37387755/75777120-49c91000-5d4d-11ea-8229-ecbf352bf4b5.png)
* **Expected**   
(See how the labels align with the ticks) 
![Screenshot from 2020-03-03 12-45-37_shadow (copy)](https://user-images.githubusercontent.com/37387755/75777431-e095cc80-5d4d-11ea-801c-4a6f8e98b2e9.png)

## Reproduce

The example has been created with the following question:  
![Screenshot from 2020-03-03 12-53-23_shadow](https://user-images.githubusercontent.com/37387755/75777630-31a5c080-5d4e-11ea-8b78-a02516011b85.png)

Note that the error disappear when using non-ordinal x-axis:
![Screenshot from 2020-03-03 12-53-50_shadow](https://user-images.githubusercontent.com/37387755/75777670-44b89080-5d4e-11ea-9bf1-9022c1f166c8.png)
![Screenshot from 2020-03-03 12-54-00_shadow](https://user-images.githubusercontent.com/37387755/75777666-441ffa00-5d4e-11ea-8cdc-56c3c3d15b02.png)

## Expected behaviour

Well, x-axis ticks aligned.

## Metabase setup
```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_232-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_232",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.232-b09",
    "os.name": "Linux",
    "os.version": "5.1.16-300.fc30.x86_64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.3",
      "date": "2020-02-25",
      "branch": "release-0.34.x",
      "hash": "1a83edb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

## Severity

Makes my life a bit less beautiful and fosters my OCDs.

**Comment by flamber** [comment] 2020-03-03 14:03
Hi @EBoisseauSierra 
Unless I'm misreading something, this looks like a duplicate of #11216 - right? Closing as such :-)

**Closed by flamber** 2020-03-03 14:03 UTC
Labels: .Needs Triage, Type:Bug

**Comment by EBoisseauSierra** [comment] 2020-03-03 14:11
I visibly didn't looked for already existing issues well enough! Thanks for closing.
