### ISSUE TITLE
Legend missing on multiple Series Bar chart

### ISSUE THREAD

**Issue by danishpatelcex** [metabase/metabase#9213] opened 2019-01-04 05:56 UTC
Please find the attachment (Bar chart and table data for the same)

Please find details below:
Your browser and the version: Chrome 71.0.3578.80 (Official Build) (64-bit)
Your operating system: Windows 10
Your databases: MySQL
Metabase version: v0.32.0
Metabase hosting environment: Linux/Ubuntu
Metabase internal database: MySQL

![multipleseries](https://user-images.githubusercontent.com/13693154/50675342-826b3d80-1013-11e9-975c-94fa8169371d.png)

![multipleseriestable](https://user-images.githubusercontent.com/13693154/50675345-85fec480-1013-11e9-857f-03bf49faa887.png)

**Comment by salsakran** [comment] 2019-01-05 01:30
It looks like we're either ignoring the last column or the last row somehow.

If you hover over the "Operator" bar, do you get a value of 116 or 118?

Also, if you swap the order to Functionality, Status, Counts does that fix things?

**Comment by paulrosenzweig** [comment] 2019-06-04 19:29
@danishpatelcex I can't seem to reproduce this on v0.32.0. Here's the query I'm trying:

```sql
select 'Deposit' as functionality, 274 as counts, 'Passed' as status
union all
select 'Operator' as functionality, 116 as counts, 'Passed' as status
union all
select 'Operator' as functionality, 2 as counts, 'Failed' as status
```

With that query my default bar chart doesn't show any legend at all. If I add a second series, a legend appears, but it works correctly.

My data didn't actually come from an aggregation, so I'm guessing my metadata is different from yours even if the tables looks the same. Are you able to reproduce this on the sample data?

**Comment by flamber** [comment] 2020-06-03 15:17
Closing, since no reply and unable to reproduce.

**Closed by flamber** 2020-06-03 15:17 UTC
Labels: .Unable to Reproduce, Priority:P3, Type:Bug, Visualization/, Visualization/Chart Settings
