### ISSUE TITLE
Updating filters in the visualisation view deletes custom columns / 2nd level aggregations

### ISSUE THREAD

**Issue by jack-cook-repo** [metabase/metabase#25571] opened 2022-09-22 10:37 UTC
**Describe the bug**
When in the visualisation view and update a filter at the top, it deletes any custom columns or second level aggregations. This doesn't happen in the query builder UI.

Setup in UI builder:
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/61659989/191724551-e461a2e6-172e-48aa-ab68-465f403fa3ac.png">

Update the filter in the visualisation screen:
<img width="474" alt="image" src="https://user-images.githubusercontent.com/61659989/191724684-a206df6d-b112-4e50-b0ac-0d0fddf8cdf6.png">

Custom column disappears completely:
<img width="360" alt="image" src="https://user-images.githubusercontent.com/61659989/191724744-28e5c864-75dd-4f40-89aa-df989cf63fe9.png">

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/61659989/191724787-68751c1e-599f-429f-8fc0-84ad957b7643.png">

If I update the filter in the UI, the column doesn't disappear - it's just in the visualisation screen.

The same thing happens with 2nd level aggregations, e.g. with this setup:
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/61659989/191725120-e80be22d-fa60-49c9-89f9-5a0050d65ec2.png">
Updating the filter in the visualisation screen deletes the "Sum of Count" column.

This is quite a frustrating bug for us as it means having to navigate back to the UI for every filter change, or to avoid using custom columns / 2nd level aggregations with Metabase .

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "5.4.196-108.356.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.4.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-09-13",
      "tag": "v1.44.3-SNAPSHOT",
      "branch": "release-x.44.x",
      "hash": "cb12797"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2022-09-22 10:46
Duplicate of #14193

**Closed by flamber** 2022-09-22 10:46 UTC
Labels: Type:Bug, .Needs Triage
