### ISSUE TITLE
Chart titles changed to y-axis labels for questions on dashboard

### ISSUE THREAD

**Issue by jobevers** [metabase/metabase#3157] opened 2016-08-10 11:42 UTC
All of the charts on my dashboard lost their titles after upgrading:

![image](https://cloud.githubusercontent.com/assets/2380127/17552455/aef627c2-5ec5-11e6-81af-21bcf5ea3ef0.png)

If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is OSX.
*  I'm running Metabase locally with the Mac App and it is using the H2 (default) database.
*  My data is in a Postgres database.
*  My Metabase version is 0.19.1.

**Comment by markpdowney** [comment] 2016-08-10 12:54
Happening to me also, and replicated on the sample dataset.

Title appears correctly when displayed as a table, but title changes to y-axis label when switch to chart

Table view
![image](https://cloud.githubusercontent.com/assets/15235231/17554238/de2c0a2a-5f01-11e6-81fd-ba93452b9d9c.png)



Chart view
![image](https://cloud.githubusercontent.com/assets/15235231/17554222/c3c1122a-5f01-11e6-9c28-a9640c0387e1.png)

**Comment by markpdowney** [comment] 2016-08-10 13:10
Just spotted this got fixed in 0.19.2 released last night

**Comment by mazameli** [comment] 2016-08-10 16:37
Yes, this is a dupe of #3146, which was fixed by #3148.

**Closed** 2016-08-10 16:37 UTC
