### ISSUE TITLE
Can't get acess to filters and hided columns in Horizontal bar chart click

### ISSUE THREAD

**Issue by mamodo123** [metabase/metabase#16105] opened 2021-05-17 13:54 UTC
When try to make a click action in Horizontal Bar Chart and use some filters/columns like:
- My question has a column in X named 'NAME', a column in Y named 'VALUE'.
- My question has a column 'CPF', hided from view.
- My dashboard has a filter named 'COMPANY_ID'.

When i embed my dashboard in my web page, and send filter 'CPF' programmatically, I can't access my filter 'CPF' as much my hided column 'COMPANY_ID' in on click, like:

https://somesite.com/{CPF}
or
https://somesite.com/{COMPANY_ID}

I can access only:
https://somesite.com/{NAME}
or
https://somesite.com/{VALUE}

DETAIL:
I can access my hided column 'CPF' normally in Vertical Bar Chart, only in Horizontal I can't.

**Comment by lucasvieirawerner** [comment] 2021-05-17 14:00
same thing here

**Comment by flamber** [comment] 2021-05-17 14:36
Duplicate of #13927

**Closed by flamber** 2021-05-17 14:36 UTC
Labels: .Needs Triage, Type:Bug
