### ISSUE TITLE
Update field name in model metadata reverts to the default one when it's a SUM

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#47825] opened 2024-09-10 22:31 UTC
### Describe the bug

Some weird (FE?) error that doesn't let the user update the field name when it's a sum

### To Reproduce

1) create the following model
![image](https://github.com/user-attachments/assets/c6eedb72-d346-4981-bfd6-fe1e278d8c4a)
2) save it and then try to change the name of the sum column. Save it, see that the column didn't change the name

### Expected behavior

It should change the name

### Logs

no logs on the BE, FE only
```
"Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n"
e8 @ core.cljs:4009
core.cljs:4009 [metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n"
e8 @ core.cljs:4009
```

### Information about your Metabase installation

```JSON
- v50+

Maybe this comes back from before, but I'm not sure
```

### Severity

P2

**Comment by bshepherdson** [comment] 2024-09-11 12:03
Duplicate of #26755.

**Closed by bshepherdson** 2024-09-11 12:03 UTC
Labels: Type:Bug, .Needs Triage
