### ISSUE TITLE
When clicking the chart,  open a new modal to a searchable data

### ISSUE THREAD

**Issue by lanner22** [metabase/metabase#3962] opened 2016-12-15 18:00 UTC
Hey guys.

Would like to know if it's possible that when clicking on a column or piece of a pie chart, it might open a modal with a searchable data corresponding to that specific interval.

### Something like this:

I have this chart that presents the amount of users and when they've last changed their passwords.
![image](https://cloud.githubusercontent.com/assets/20980488/21235069/694f8526-c2dc-11e6-94fe-bab175a9247c.png)

Then, when clicking on a column, the magic should happend.
![image](https://cloud.githubusercontent.com/assets/20980488/21235713/0affe3dc-c2df-11e6-853c-034906022086.png)
### The question is: Who is this 38 users?

If I wanted to know who last changed the password on august, 2016, I'd have to make a new question, and it would be a unnecessary rework.

If I could just click on the column and it opens the search modal with the data, It would be a really helpful tool.

BTW, searched about it, didn't find anything similar. Sorry if it passed unnoticed.

**Comment by 100n0m3** [comment] 2016-12-15 18:17
Same function as I need #3817

**Comment by mazameli** [comment] 2016-12-15 19:13
Thanks for the feedback. I believe this is a duplicate of #1884, but let me know if you disagree.

**Closed by mazameli** 2016-12-15 19:13 UTC
