### ISSUE TITLE
Our stats instance's archive appears to be blank :-O

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#15080] opened 2021-03-05 19:57 UTC
Where did all our archived items go?

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/2223916/110166951-e4698e00-7da9-11eb-9bb6-809fba1e3d66.png">

**Comment by nemanjaglumac** [comment] 2021-03-17 19:03
I can reproduce it on `master`. Cypress repro coming soon.

**Comment by nemanjaglumac** [comment] 2021-03-17 19:16
Not only that, but it seems you CAN'T actually archive a collection. I tried with the new/empty collection (not sure if that matters).
So, create a collection, archive it but UI still shows it. I thought it's just a matter of refresh - nope. Still there.
![image](https://user-images.githubusercontent.com/31325167/111525003-64560780-875d-11eb-872c-98e1b4f842a7.png)

One more weird thing is that I can edit that "archived" collection in the UI (for example, change its name) but I'm not seeing any `PUT` request in the network tab.

@flamber do we have anything similar or should I file a new issue around this?

**Comment by nemanjaglumac** [comment] 2021-03-17 19:48
FWIW, this works on a `release-x.38.x` branch.

**Comment by flamber** [comment] 2021-03-17 19:49
@nemanjaglumac I just tagged it as regressions, so we didn't miss this, since I need the archive yesterday on stats.
Don't think there's an issue about archiving collections - likely very related.

**Comment by tsmacdonald** [comment] 2021-04-14 15:13
Fixed by #15604

**Closed by tsmacdonald** 2021-04-14 15:13 UTC
Labels: .Regression, .Reproduced, Organization/Collections, Priority:P2, Type:Bug
