### ISSUE TITLE
Oracle Sync fails with ORA-01000: maximum open cursors exceeded 

### ISSUE THREAD

**Issue by ricardoj-br** [metabase/metabase#6467] opened 2017-11-25 13:51 UTC
My environment is : Metabase 0.26.2 Ubuntu 16.04

Let me explain what I did so far 

- changed from open-jdk to oracle jdk
- changed from SID to service
- changed jdbc driver versions ( ojdbc7.jar and ojdbc6.jar )

No luck !

From this same machine and using the same oracle configuration I can connect **_dremio_** to the oracle without problems and browse the schema and its contents.

Any idea ? What else could be tested ?

Thanks,

Ricardo Jorge

**Comment by Philippe-M** [comment] 2017-12-02 09:50
I've the same problem

Metabase 0.27.1 - Fedora 25 - Oracle 10

**Comment by ricardoj-br** [comment] 2017-12-02 11:21
Thank you Philippe-M what we know so far

- different MetaBase versions ( mine is 0.26.2 )
- different O.S. versions ( mine is Ubuntu 16.04 )
- different Oracle versions ( mine is 11 )

All have the same issue.

Anybody succeed to connect ?

If so, please, what O.S, Oracle and MetaBase version as well as are you using SID or Service ? Is this a production or test environment that you can fine tunning till you access the Oracle ?

Thanks again,

Ricardo Jorge

**Comment by Philippe-M** [comment] 2017-12-04 13:49
@ricardoj-br , the connect it's ok, it's a prod environment (ERP Sage X3) and i'm use a SID, the oracle server is on redhat 5.

**Comment by MarkRx** [comment] 2018-01-31 15:44
In oracle there can be multiple cursors per a connection. If more cursors are opened before others are closed (possibly due to recursion) you can run out of cursors.

select  sql_text, count(*) as "OPEN CURSORS", user_name from v$open_cursor
group by sql_text, user_name order by count(*) desc;

> SELECT NULL AS pktable_cat,        p.owner as pktable_schem,	174	MBASE
> SELECT  NULL AS table_cat,        t.owner AS table_schem,   	52	MBASE
> SELECT NULL AS table_cat,        c.owner AS table_schem,    	52	MBASE
> select 'TABLE' as table_type from dual union select 'VIEW' a	19	MBASE
> SELECT NULL AS table_cat,        o.owner AS table_schem,    	19	MBASE
> ...

**Comment by MarkRx** [comment] 2018-01-31 16:13
Here is some cursor data when the sync runs with 37 tables:

```
select * 
from (
  select  sid, 
          v$sql.sql_id, 
          count(*) as "OPEN CURSORS"
  from v$open_cursor join v$sql on v$open_cursor.sql_id = v$sql.sql_id
  where user_name = 'MBASE' group by sid, v$sql.sql_id
  order by count(*) desc) aggr
join v$sql on v$sql.sql_id = aggr.sql_id;
```

125 cursors:
```
SELECT NULL AS pktable_cat,
       p.owner as pktable_schem,
       p.table_name as pktable_name,
       pc.column_name as pkcolumn_name,
       NULL as fktable_cat,
       f.owner as fktable_schem,
       f.table_name as fktable_name,
       fc.column_name as fkcolumn_name,
       fc.position as key_seq,
       NULL as update_rule,
       decode (f.delete_rule, 'CASCADE', 0, 'SET NULL', 2, 1) as delete_rule,
       f.constraint_name as fk_name,
       p.constraint_name as pk_name,
       decode(f.deferrable,       'DEFERRABLE',5      ,'NOT DEFERRABLE',7      , 'DEFERRED', 6      ) deferrability 
      FROM all_cons_columns pc, all_constraints p,
      all_cons_columns fc, all_constraints f
WHERE 1 = 1
  AND f.table_name = :2
  AND f.owner = :4
  AND f.constraint_type = 'R'
  AND p.owner = f.r_owner
  AND p.constraint_name = f.r_constraint_name
  AND p.constraint_type = 'P'
  AND pc.owner = p.owner
  AND pc.constraint_name = p.constraint_name
  AND pc.table_name = p.table_name
  AND fc.owner = f.owner
  AND fc.constraint_name = f.constraint_name
  AND fc.table_name = f.table_name
  AND fc.position = pc.position
ORDER BY pktable_schem, pktable_name, key_seq
```

72 cursors:
```
SELECT NULL AS pktable_cat,
       p.owner as pktable_schem,
       p.table_name as pktable_name,
       pc.column_name as pkcolumn_name,
       NULL as fktable_cat,
       f.owner as fktable_schem,
       f.table_name as fktable_name,
       fc.column_name as fkcolumn_name,
       fc.position as key_seq,
       NULL as update_rule,
       decode (f.delete_rule, 'CASCADE', 0, 'SET NULL', 2, 1) as delete_rule,
       f.constraint_name as fk_name,
       p.constraint_name as pk_name,
       decode(f.deferrable,       'DEFERRABLE',5      ,'NOT DEFERRABLE',7      , 'DEFERRED', 6      ) deferrability 
      FROM all_cons_columns pc, all_constraints p,
      all_cons_columns fc, all_constraints f
WHERE 1 = 1
  AND f.table_name = :2
  AND f.owner = :4
  AND f.constraint_type = 'R'
  AND p.owner = f.r_owner
  AND p.constraint_name = f.r_constraint_name
  AND p.constraint_type = 'P'
  AND pc.owner = p.owner
  AND pc.constraint_name = p.constraint_name
  AND pc.table_name = p.table_name
  AND fc.owner = f.owner
  AND fc.constraint_name = f.constraint_name
  AND fc.table_name = f.table_name
  AND fc.position = pc.position
ORDER BY pktable_schem, pktable_name, key_seq
```

47 cursors:
```
SELECT  NULL AS table_cat,
       t.owner AS table_schem,
       t.table_name AS table_name,
       t.column_name AS column_name,
DECODE(  (SELECT a.typecode 
     FROM ALL_TYPES A 
     WHERE a.type_name = t.data_type), 
  'OBJECT', 2002, 
  'COLLECTION', 2003, 
  DECODE(substr(t.data_type, 1, 9), 
    'TIMESTAMP', 
      DECODE(substr(t.data_type, 10, 1), 
        '(', 
          DECODE(substr(t.data_type, 19, 5), 
            'LOCAL', -102, 'TIME ', -101, 93), 
        DECODE(substr(t.data_type, 16, 5), 
          'LOCAL', -102, 'TIME ', -101, 93)), 
    'INTERVAL ', 
      DECODE(substr(t.data_type, 10, 3), 
       'DAY', -104, 'YEA', -103), 
    DECODE(t.data_type, 
      'BINARY_DOUBLE', 101, 
      'BINARY_FLOAT', 100, 
      'BFILE', -13, 
      'BLOB', 2004, 
      'CHAR', 1, 
      'CLOB', 2005, 
      'COLLECTION', 2003, 
      'DATE', 93, 
      'FLOAT', 6, 
      'LONG', -1, 
      'LONG RAW', -4, 
      'NCHAR', -15, 
      'NCLOB', 2011, 
      'NUMBER', 3, 
      'NVARCHAR', -9, 
      'NVARCHAR2', -9, 
      'OBJECT', 2002, 
      'OPAQUE/XMLTYPE', 2009, 
      'RAW', -3, 
      'REF', 2006, 
      'ROWID', -8, 
      'SQLXML', 2009, 
      'UROWID', -8, 
      'VARCHAR2', 12, 
      'VARRAY', 2003, 
      'XMLTYPE', 2009, 
      1111)))
 AS data_type,
       t.data_type AS type_name,
       DECODE (t.data_precision,                null, DECODE(t.data_type,                        'NUMBER', DECODE(t.data_scale,                                    null, 38                                   , 38),          DECODE (t.data_type, 'CHAR', t.char_length,                   'VARCHAR', t.char_length,                   'VARCHAR2', t.char_length,                   'NVARCHAR2', t.char_length,                   'NCHAR', t.char_length,                   'NUMBER', 0,           t.data_length)                           ),         t.data_precision)
              AS column_size,
       0 AS buffer_length,
       DECODE (t.data_type,                'NUMBER', DECODE(t.data_precision,                                 null, DECODE(t.data_scale,                                              null, 0                                             , t.data_scale),                                  t.data_scale),                t.data_scale) AS decimal_digits,
       10 AS num_prec_radix,
       DECODE (t.nullable, 'N', 0, 1) AS nullable,
       NULL AS remarks,
       t.data_default AS column_def,
       0 AS sql_data_type,
       0 AS sql_datetime_sub,
       t.data_length AS char_octet_length,
       t.column_id AS ordinal_position,
       DECODE (t.nullable, 'N', 'NO', 'YES') AS is_nullable,
         null as SCOPE_CATALOG,
       null as SCOPE_SCHEMA,
       null as SCOPE_TABLE,
       null as SOURCE_DATA_TYPE,
       'NO' as IS_AUTOINCREMENT
FROM all_tab_columns t
WHERE t.owner LIKE :1 ESCAPE '/'
  AND t.table_name LIKE :2 ESCAPE '/'
  AND t.column_name LIKE :3 ESCAPE '/'

ORDER BY table_schem, table_name, ordinal_position
```

47 cursors:
```
SELECT NULL AS table_cat,
       c.owner AS table_schem,
       c.table_name,
       c.column_name,
       c.position AS key_seq,
       c.constraint_name AS pk_name
FROM all_cons_columns c, all_constraints k
WHERE k.constraint_type = 'P'
  AND k.table_name = :1
  AND k.owner like :2 escape '/'
  AND k.constraint_name = c.constraint_name 
  AND k.table_name = c.table_name 
  AND k.owner = c.owner 
ORDER BY column_name
```

17 cursors:
```
select 'TABLE' as table_type from dual
union select 'VIEW' as table_type from dual
union select 'SYNONYM' as table_type from dual
```

17 cursors:
```
SELECT NULL AS table_cat,
       o.owner AS table_schem,
       o.object_name AS table_name,
       o.object_type AS table_type,
       NULL AS remarks
  FROM all_objects o
  WHERE o.owner LIKE :1 ESCAPE '/'
    AND o.object_name LIKE :2 ESCAPE '/'
    AND o.object_type IN ('xxx', 'TABLE', 'VIEW')
  ORDER BY table_type, table_schem, table_name
```

**Comment by MarkRx** [comment] 2018-01-31 16:21
Cursors may be getting left open too. I increased the number of open cursors on the database to get the sync to fire but after it completed there still were 100's of open cursors.

**Comment by ricardoj-br** [comment] 2018-01-31 17:08
Maybe cursors is not the only problem but the way Oracle is being "queried". I succeed to connect to the same Oracle environment using Dremio. I don not know why Dremio succeed and MetaBase fails. Regards.

**Comment by joboyx** [comment] 2018-02-28 10:08
Also happens with:

Metabase: v0.28.1
OS: Ubuntu 16.04.3 LTS
Oracle: Oracle Database 11g Release 11.2.0.4.0 - 64bit Production

**Comment by bkasap** [comment] 2018-07-24 07:07
Metabase v0.29.3
Docker image with ojdbc7

no control over the oracle database

```
Error running sync step: ORA-01000: maximum open cursors exceeded

("driver.generic_sql$get_tables.invokeStatic(generic_sql.clj:298)"
"driver.generic_sql$get_tables.invoke(generic_sql.clj:295)"
"driver.generic_sql$fast_active_tables$iter__50997__51003$fn__51004.invoke(generic_sql.clj:312)"
"driver.generic_sql$fast_active_tables.invokeStatic(generic_sql.clj:311)"
"driver.generic_sql$fast_active_tables.invoke(generic_sql.clj:301)"
"driver.generic_sql$fn__50704$G__50583__50711.invoke(generic_sql.clj:30)"
"driver.generic_sql$describe_database.invokeStatic(generic_sql.clj:366)"
"driver.generic_sql$describe_database.invoke(generic_sql.clj:361)"
"driver$fn__25702$G__25638__25709.invoke(driver.clj:61)"
"sync.fetch_metadata$fn__34265$db_metadata__34270$fn__34271.invoke(fetch_metadata.clj:13)"
"sync.fetch_metadata$fn__34265$db_metadata__34270.invoke(fetch_metadata.clj:10)"
"sync.sync_metadata.tables$fn__35395$db_metadata__35400$fn__35401.invoke(tables.clj:127)"
"sync.sync_metadata.tables$fn__35395$db_metadata__35400.invoke(tables.clj:124)"
"sync.sync_metadata.tables$fn__35455$sync_tables_BANG___35460$fn__35461.invoke(tables.clj:144)"
"sync.sync_metadata.tables$fn__35455$sync_tables_BANG___35460.invoke(tables.clj:139)"
"sync.sync_metadata$fn__35485$sync_db_metadata_BANG___35490$fn__35491$fn__35492.invoke(sync_metadata.clj:26)"
"sync.util$do_with_error_handling.invokeStatic(util.clj:124)"
"sync.util$do_with_error_handling.invoke(util.clj:119)"
"sync.util$do_with_error_handling.invokeStatic(util.clj:122)"
"sync.util$do_with_error_handling.invoke(util.clj:119)"
"driver$fn__25884.invokeStatic(driver.clj:245)"
"driver$fn__25884.invoke(driver.clj:245)"
"driver$fn__25819$G__25626__25828.invoke(driver.clj:61)"
"sync.util$sync_in_context$fn__32553.invoke(util.clj:115)"
"sync.util$with_db_logging_disabled$fn__32550.invoke(util.clj:106)"
"sync.util$with_start_and_finish_logging$fn__32545.invoke(util.clj:92)"
"sync.util$with_sync_events$fn__32542.invoke(util.clj:75)"
"sync.util$with_duplicate_ops_prevented$fn__32533.invoke(util.clj:54)"
"sync.util$do_sync_operation.invokeStatic(util.clj:142)"
"sync.util$do_sync_operation.invoke(util.clj:139)"
"sync.sync_metadata$fn__35485$sync_db_metadata_BANG___35490$fn__35491.invoke(sync_metadata.clj:23)"
"sync.sync_metadata$fn__35485$sync_db_metadata_BANG___35490.invoke(sync_metadata.clj:20)"
"task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:36)")

```

**Comment by camsaul** [comment] 2018-09-17 17:51
Sounds like a duplicate of #6029

**Comment by camsaul** [comment] 2018-09-17 17:52
Also: #4389

**Comment by senior** [comment] 2018-09-18 16:39
@ricardoj-br @bksap @MarkRx @joboyx @Philippe-M Can you try this out again with a recent version of Metabase (v0.30.0+)?

From what I have read, Oracle cursors are tied to JDBC ResultSets. According to the JDBC spec, closing a JDBC connection should close any ResultSets created from that connection, but we found that wasn't always the case Specifically the JDBC metadata calls on Redshift weren't getting closed and remained in memory. It would eventually would cause memory issues. I'm thinking Oracle might have a similar issue, but rather than running out of memory, the open ResultSets were causing us to run out of cursors.

To fix that, in https://github.com/metabase/metabase/pull/7666 I added code to explicitly close ResultSets. Although the PR says Redshift, we should now be explicitly closing the ResultSets on those metadata calls for our SQL backends. That change was included in `0.30.0` that version or anything after should have the fix.

If you still get the error, please include a stacktrace so that I can narrow down the places we might be leaving those ResultSets open.

**Comment by MarkRx** [comment] 2018-09-24 17:06
Much better. I compared 0.28.2 against 0.30.3. Running a scan on 0.28.2 resulted in about 875 open cursors. Running a scan in 0.30.3 resulted in 2. Running it again and again revealed two statements that randomly leak (resulting in a higher open cursor count). Rerunning it sometimes results in them getting closed.

1. Some kind of internal oracle cursor? Literally all the SQL_TEXT says is this:
```
table_1_ff_208_0_0_0
```

2. Some cursor obtaining metadata about tables in a schema:
```
  SELECT NULL        AS table_cat,
         o.owner     AS table_schem,
         o.object_name AS table_name,
         o.object_type AS table_type,
         NULL        AS remarks
    FROM all_objects o
   WHERE     o.owner LIKE :1 ESCAPE '/'
         AND o.object_name LIKE :2 ESCAPE '/'
         AND o.object_type IN ('xxx', 'TABLE')
ORDER BY table_type, table_schem, table_name
```


```
-- User is 'MBASE'
select * from v$open_cursor where user_name = 'MBASE' and cursor_type like '%OPEN%';

select s.username, sum(a.value) as count
from v$sesstat a, v$statname b, v$session s 
where a.statistic# = b.statistic# 
and s.sid=a.sid and b.name = 'opened cursors current'
and s.username is not null
group by s.username;
```

**Comment by tonig** [comment] 2018-09-29 08:27
@senior We're experiencing this bug connecting 0.30.3 and Oracle12c.
"ERROR sync.util :: Error running sync step: ORA-01000: maximum open cursors exceeded"

We've configured max open cursors to 2000 in our preprod oracle to debug what are the harmful queries and we found this:

select 'TABLE' as table_type from dual union select 'VIEW' as table_type from dual union select 'SYNONYM' as table_type from dual
**1124 opened cursors**

Hope this helps solving the problem.

**Comment by MarkRx** [comment] 2018-10-01 15:04
What driver are you using? Worked for ojdbc8 12.2.0.1

**Comment by senior** [comment] 2018-10-01 15:14
@tonig Is there a stacktrace you can include? Those queries are generated by the JDBC driver when we make metadata calls. Since it's closed source and not Metabase code, I'm not entirely sure where they are coming from.

**Comment by tonig** [comment] 2018-10-02 07:40
@MarkRx changing the driver to OJDBC 8 (12.2.0.1.0) solved the problem, thanks!

We were using OJDBC 7 (12.1.0.2.0). Please note the docs point to ojdbc7. https://metabase.com/docs/v0.30.3/administration-guide/databases/oracle.html

@senior I'm sorry logs at dev server have rotated and I have not such stack trace. If you need it I'll try to find time for configuring ojdc7 and restart the tests.

**Comment by senior** [comment] 2018-10-02 13:54
@tonig Thanks for testing that out, seems like a good idea to just update our docs to reflect the more recent Oracle JDBC release as the one the doc references is pretty old. I just opened up https://github.com/metabase/metabase/pull/8617 to update our Oracle docs.

Closing this as it appears closing the result sets fixes the open cursors issue on recent Oracle JDBC driver releases.

**Closed by senior** 2018-10-02 13:54 UTC
Labels: Bug, Database/Oracle, Priority/P2
