### ISSUE TITLE
Font not loading

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4756] opened 2017-04-11 17:31 UTC
@ArtursO [reported on Gitter](https://gitter.im/metabase/metabase) that he's encountering a font loading bug, specifically on the pulses section:

> I was wondering if it's normal that the fonts are different on the Pulse page - the font used for the actual questions is in times new roman whereas the rest of Metabase is always standard (I think Arial) . The "Create a pulse" button is also in times new roman font.

![blob-1](https://cloud.githubusercontent.com/assets/2223916/24921984/8b335156-1ea1-11e7-8e88-c01a6c8c4add.png)

Here's the JS error he's seeing:

![blob](https://cloud.githubusercontent.com/assets/2223916/24921931/5c5da58e-1ea1-11e7-8e88-cbc8acc5d084.png)

And here are his system details:

> Metabase V 0.23.1, on Heroku , using Chrome Version 57.0.2987.133 (64-bit) on macOS Sierra Version 10.12.4

I haven't been able to reproduce this yet.

**Comment by marszall87** [comment] 2017-04-18 10:52
Happens to me also (see the buttons):
![image](https://cloud.githubusercontent.com/assets/4551693/25127310/abecf458-2435-11e7-83f5-4f7a91f21edd.png)

Metabase v0.23.1
Chrome Version 58.0.3029.68 beta (64-bit)
macOS 10.12.3

**Comment by kdoh** [comment] 2017-04-18 17:03
I haven't been able to reproduce this myself yet but there are two things going on here.

1. for some reason the font is being blocked for CSP reasons
2. for buttons specifically the backup sans-serif font family isn't being picked up like it is elsewhere.

The second one will be fixed by #4805. Could be that the first is something specific to Heroku.

**Comment by marszall87** [comment] 2017-04-19 11:40
It's definitely not Heroku because I was running Metabase on localhost as a Docker container.

**Comment by camsaul** [comment] 2017-11-06 02:16
Are we still running into this issue?

**Comment by kdoh** [comment] 2018-04-06 22:07
I'm 99% convinced that the underlying issue for this was fixed by #6154 so I'm going to go ahead and close this.

**Closed by kdoh** 2018-04-06 22:07 UTC
Labels: Bug, Priority/P3
