### ISSUE TITLE
Add "GAUGE" type visualization to metabase

### ISSUE THREAD

**Issue by seko777** [metabase/metabase#6721] opened 2018-01-18 14:49 UTC
We`d love to see a "GAUGE" type visualization in metabase.

Gauges are really useful view when monitoring thins, for example: temperature, humidity, volts or any other value bem monitored.

Take an example from this page to monitor UPS:

http://gokoni2.dmesg.com.br

We have all these values in MySQL and use amcharts for the gauges. We tried Metabase with "line" and "progress" visualization but we really miss GAUGES. Even better if possible to customize the ALERT and CRITICAL ranges (yellow and red on this example) and receive email alerts when something goes wrong, like "Nagios, Zabbix" and other monitoring software.

**Comment by jornh** [comment] 2018-01-18 16:34
Related #4500 and #2989

**Comment by mazameli** [comment] 2018-01-18 17:21
As superuser and all-around good guy Jørn pointed out, this is a duplicate of #4500.

**Closed by mazameli** 2018-01-18 17:21 UTC
Labels: Duplicate

**Comment by mnlbox** [comment] 2018-06-10 10:15
@mazameli Are you any plan to add gauge chart?
