### ISSUE TITLE
database migration issue : "Unexpected character ('A' (code 65)) in numeric value:"

### ISSUE THREAD

**Issue by thomasLeclaire** [metabase/metabase#10027] opened 2019-05-23 08:54 UTC
- Your databases: Postgres 9.6
- Metabase version: 0.30.4, 0.32.8
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 9.6

I want to migrate my metabases from a standard postgres install to a GCP cloud SQL one. 

I did it without issue on several instances with simple pg_dump/pg_restore. 

But on a specific one, even if dump and restore sounds to be correct, when I start the "new" metabase (try several versions without success) it doesn't work. 
There is this error reported during syncdatabase task : 

`May 22 17:40:21 INFO metabase.task :: Initializing task SyncDatabases 📆
May 22 17:40:21 ERROR metabase.task :: Error initializing task :metabase.task.sync-databases/SyncDatabases
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('A' (code 65)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value
at [Source: (StringReader); line: 1, column: 3]
at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:669)`

Logs don't provide anymore details even in full DEBUG mode and I can't see what could be the issue in metabase tables. 

Do you have any suggestion ?

thx for any help!

**Comment by flamber** [comment] 2020-05-30 17:02
Closing, since this should have been posted in the forum: https://discourse.metabase.com/
This might be caused by a bad migration, when upgrading between other versions, while has caused a problem in the database.
But without [debug logging](https://www.metabase.com/docs/latest/operations-guide/log-configuration.html), then it's difficult to say for sure - looks like it's failing on [task sync](https://github.com/metabase/metabase/blob/f58c7043302c6ee19576fdc14ddea643e8800e23/src/metabase/task/sync_databases.clj#L186-L192)

**Closed by flamber** 2020-05-30 17:02 UTC
Labels: Operation/, Priority:P2, Type:Bug
