### ISSUE TITLE
Java NullPointerException when using custom query

### ISSUE THREAD

**Issue by lwqcz** [metabase/metabase#8302] opened 2018-08-13 13:19 UTC
Hi there,

I've just noticed a Java NulPointerException when I tried to run custom query using foregin key containng diacritics.

There is print screen and metabase log down below.
![metabase_java_nullpointer](https://user-images.githubusercontent.com/39486334/44033873-fdac8d60-9f0b-11e8-87d4-a611f232d2c3.jpg)

If anathing is unclear - write to me and wait nomore 😉 👍 

08-13 15:11:53 WARN metabase.query-processor :: {:status :failed,
 :class java.lang.NullPointerException,
 :error "java.lang.NullPointerException",
 :stacktrace
 ["query_processor.middleware.add_dimension_projections$col__GT_dim_map.invokeStatic(add_dimension_projections.clj:71)"
  "query_processor.middleware.add_dimension_projections$col__GT_dim_map.invoke(add_dimension_projections.clj:64)"
  "query_processor.middleware.add_dimension_projections$remap_results.invokeStatic(add_dimension_projections.clj:127)"
  "query_processor.middleware.add_dimension_projections$remap_results.invoke(add_dimension_projections.clj:114)"
  "query_processor.middleware.expand$expand_middleware$fn__30484.invoke(expand.clj:607)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__28868.invoke(add_row_count_and_status.clj:14)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__30615.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__32147.invoke(resolve_driver.clj:15)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__29336.invoke(cache.clj:147)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__30532.invoke(catch_exceptions.clj:58)"
  "query_processor$process_query.invokeStatic(query_processor.clj:132)"
  "query_processor$process_query.invoke(query_processor.clj:128)"
  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:245)"
  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:239)"
  "query_processor$fn__32181$process_query_and_save_execution_BANG___32186$fn__32187.invoke(query_processor.clj:285)"
  "query_processor$fn__32181$process_query_and_save_execution_BANG___32186.invoke(query_processor.clj:271)"
  "query_processor$fn__32205$process_query_and_save_with_max_BANG___32210$fn__32211.invoke(query_processor.clj:306)"
  "query_processor$fn__32205$process_query_and_save_with_max_BANG___32210.invoke(query_processor.clj:302)"
  "api.dataset$fn__37762$fn__37765$fn__37766.invoke(dataset.clj:51)"
  "api.common$fn__20698$invoke_thunk_with_keepalive__20703$fn__20704$fn__20705.invoke(common.clj:404)"],
 :query
 {:type "query",
  :query {:source_table 80, :filter ["=" ["fk->" 781 2511] "Kučerová"]},
  :parameters [],
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :info
  {:executed-by 7,
   :context :ad-hoc,
   :card-id nil,
   :nested? false,
   :query-hash [-91, 124, 77, -96, 100, -35, -78, -34, 80, -127, 101, 24, -57, 82, -40, -68, 69, 10, -66, 115, -14, -66, 68, 64, -40, 11, -15, -26, 28, 100, 118, -127],
   :query-type "MBQL"}},
 :expanded-query nil}

08-13 15:11:53 WARN metabase.query-processor :: Query failure: java.lang.NullPointerException
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:213)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:206)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:246)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:239)"
 "query_processor$fn__32181$process_query_and_save_execution_BANG___32186$fn__32187.invoke(query_processor.clj:285)"
 "query_processor$fn__32181$process_query_and_save_execution_BANG___32186.invoke(query_processor.clj:271)"
 "query_processor$fn__32205$process_query_and_save_with_max_BANG___32210$fn__32211.invoke(query_processor.clj:306)"
 "query_processor$fn__32205$process_query_and_save_with_max_BANG___32210.invoke(query_processor.clj:302)"
 "api.dataset$fn__37762$fn__37765$fn__37766.invoke(dataset.clj:51)"
 "api.common$fn__20698$invoke_thunk_with_keepalive__20703$fn__20704$fn__20705.invoke(common.clj:404)"]

**Comment by jornh** [comment] 2018-08-13 14:45
- What's the underlying database for this? 
- Do you know if the problem is related to a specific database only or not? 
- What character set has it been configured to run with? 

I've previous been involved in an issue, see https://github.com/metabase/metabase/issues/7438#issuecomment-386206859 where character set was of importance. Not sure this is related at all - but you got to start somewhere... 😉  

I tried briefly to reproduce on H2 with the `Demô Dætasèt` with a FK mapping - and asking for someone matching/not matching e.g "Kocûrek" (but that dataset currently has no special chars in it, so wasn't really able to test with FK. IMO it really should, to allow for easier testing)

This is with v0.30.0 - or? Do you know if it's a regression from earlier?

**Comment by lwqcz** [comment] 2018-08-14 06:08
@jornh thnx for reply - and I am sorry to fail to provide basic facts about our setup, I was really badly in hurry.

- underlying DB is Postgres 9.5
- queried DB is Postgres 10.2.0.4
- Metabase runs as JAR file on Ubuntu powered machine with locate set to en_US.UTF-U UTF-8
- Metabase version is 0.29.0-snapshot built on 2018-05-11; branch: master; hash: f8921ce
- this problem is occuring in our whole DB, regardsless of which table or view is used
- I've tried that on another instance - Metabase 0.29.3 with MySQL works but I cannot find there any FK reference in Custom Query at all (I'm not the admin of this instance)

**Comment by lwqcz** [comment] 2018-08-14 06:38
@salsakran I've just upgraded to 0.30 and everything is working just fine now. You can close this issue if you wish so.

**Comment by lwqcz** [comment] 2018-08-15 06:36
@salsakran @jornh sorry guys but this error appears again just few second ago.

2018-08-15T08:07:51.694+0200: [GC (Allocation Failure) 2018-08-15T08:07:51.694+0200: [DefNew: 280933K->1560K(313024K), 0.0180525 secs] 771184K->491811K(1008332K), 0.0183346 secs] [Times: user=0.02 sys=0.00, real=0.01 secs] 
08-15 08:35:56 WARN metabase.query-processor :: {:status :failed,
 :class java.lang.NullPointerException,
 :error "java.lang.NullPointerException",
 :stacktrace [],
 :query
 {:query {:source_table 258, :filter ["=" ["fk->" 2510 2511] "Kučerová"]},
  :type "query",
  :parameters [],
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :info
  {:executed-by 7,
   :context :ad-hoc,
   :card-id nil,
   :nested? false,
   :query-hash [15, 74, 55, 41, 43, -5, -63, 93, -21, 3, 14, 10, 82, -35, 7, -68, 36, 65, 43, -8, -58, 115, -82, -53, -23, -124, -20, -7, -77, 92, 94, 122],
   :query-type "MBQL"}},
 :expanded-query nil}

08-15 08:35:56 WARN metabase.query-processor :: Query failure: java.lang.NullPointerException
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:217)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:210)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:250)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:243)"
 "query_processor$fn__36878$process_query_and_save_execution_BANG___36883$fn__36884.invoke(query_processor.clj:289)"
 "query_processor$fn__36878$process_query_and_save_execution_BANG___36883.invoke(query_processor.clj:275)"
 "query_processor$fn__36902$process_query_and_save_with_max_BANG___36907$fn__36908.invoke(query_processor.clj:310)"
 "query_processor$fn__36902$process_query_and_save_with_max_BANG___36907.invoke(query_processor.clj:306)"
 "api.dataset$fn__43354$fn__43357.invoke(dataset.clj:45)"
 "api.common$fn__20621$invoke_thunk_with_keepalive__20626$fn__20627$fn__20628.invoke(common.clj:433)"]

**Comment by senior** [comment] 2018-08-15 19:16
@lwqcz so as long as your metadata is recent, you do not see an error?

**Comment by lwqcz** [comment] 2018-08-16 04:55
@senior sorry I do not understand your question. You mean if there is an error before I change something?

**Comment by senior** [comment] 2018-08-17 17:53
Above in EDIT 4, you mentioned

> I've noticed that this NullPointer error will occur when I change metadata and I do not "Re-scan" table.

It sounds like your issue is that you changed some FK related attributes of a table, you immediately ran a query, then it failed with a NullPointerException. You then scanned the table (which will populate that FK metadata) and you no longer received a NullPointerException. Is that correct?

**Comment by lwqcz** [comment] 2018-08-21 06:01
@senior Yes, I see it now. I did not imagine that this behaviour is controlled by setting hidden there (as I am writing this I am getting an idea of having something like about:config browser's page would be great, to access various settings via "expert way" and not to have think where is what hidden ...)
And also - I agree that instead NullPointerException there should be another reaction or maybe the sync trigger?

Thank you.

**Comment by senior** [comment] 2018-10-08 15:51
I think this issue must have been fixed with other remapping bug fixes. The original exception was a Null Pointer trying to get the manually specified remappings of a value. I just recreated that scenario by setting up a remapping, then via the admin panel removing the field values for that remapped column. It no longer throws a `NullPointerException` and the query returns successfully. That remapped column is empty (which makes sense as those values had just been cleared) but theres no error that results from it.

If you hit this again on newer versions of Metabase please open up a new issue with the metadata changes you made along with the query that triggers the error.

**Closed by senior** 2018-10-08 15:51 UTC
Labels: Bug, Priority/P2, Query Processor
