### ISSUE TITLE
DATABASECHANGELOG has no key

### ISSUE THREAD

**Issue by Albertsaab** [metabase/metabase#23818] opened 2022-07-09 17:37 UTC
**Describe the bug**
DATABASECHANGELOG has no key and that prevent intallation on a DB with replication

**Logs**
java.sql.SQLTransientConnectionException: (conn=601448) Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.

**To Reproduce**
Run migration on mysql db with sql_require_primary_key is set to true

**Expected behavior**
A generick autoincrement key can be added to prevent this problem

**Comment by flamber** [comment] 2022-07-21 11:01
Duplicate of #7561

**Closed by flamber** 2022-07-21 11:01 UTC
Labels: Type:Bug, .Needs Triage
