### ISSUE TITLE
User cannot be reactivated

### ISSUE THREAD

**Issue by Overbryd** [metabase/metabase#7337] opened 2018-04-12 13:41 UTC
### Bug

- Your databases: MySQL, Google Analytics
- Metabase version: 0.28.1
- Metabase hosting environment: Docker/Kubernetes
- Metabase internal database: MySQL

We have a user that was successfully using Metabase. We deactivated him, and now we would like to reactive his account. But it does not work.

It is not reproducible with other users.

We are using Google Apps Sign on. It works for new users, it works for existing users, it works for existing users that have been removed/reactivated.

Just for this users it does not work.

What can we do to debug this and what can we do to get rid of this problem.

We cannot login any more, but he need access to Metabase.

**Comment by jornh** [comment] 2018-04-12 14:16
Related issues: https://github.com/metabase/metabase/issues/1093, https://github.com/metabase/metabase/issues/7312 and not the forget https://github.com/metabase/metabase/issues/4936 which has `Design` for improving the UX on this + a https://github.com/metabase/metabase/issues/4936#issuecomment-318129241 giving one users workaround.

> What can we do to debug this and what can we do to get rid of this problem?

I think first step towards debugging this would be to connect to (a copy of) the Metabase application database and peek into/modify the `CORE_USER` table (having documented how this user differ would be useful for test code!), then look at working around as per https://github.com/metabase/metabase/issues/4936#issuecomment-318129241 mentioned above.

**Comment by salsakran** [comment] 2019-08-19 22:07
was this fixed in #7481?

**Comment by flyingmachine** [comment] 2019-09-13 16:01
@salsakran Given that we don't have steps to reproduce and this process was re-examined and tested for #7481, I'm inclined to close this ticket.

**Comment by salsakran** [comment] 2019-09-13 17:23
@flyingmachine @mazameli what happens when a user who comes in via SSO is deactivated? 

Down to close this if it can't be reproduced

**Comment by mazameli** [comment] 2019-09-13 18:34
@salsakran They're added to the `Deactivated` tab on `/admin/people` and can be restored from there. This was implemented in https://github.com/metabase/metabase/pull/7481. You can look at our internal stats instance to see what it looks like (e.g. Atte).

**Closed** 2019-09-13 18:37 UTC
Labels: Admin Panel & Setup, Priority:P1, Type:Bug
