### ISSUE TITLE
Scrollbar does not appear in Text Cards on Firefox

### ISSUE THREAD

**Issue by alain-andre** [metabase/metabase#7159] opened 2018-03-20 10:10 UTC
This issue is related to [#6436](https://github.com/metabase/metabase/pull/6436) and [#6360](https://github.com/metabase/metabase/issues/6360)

When having a text longer than the Text Card, no scroll appears on Firefox, but it does on Google Chrome.

## Bug
- Browser and version: Firefox 59.0.1
- Operating system: Ubuntu 17.10
- Metabase version: v0.28.1

*Repeatable steps to reproduce the issue*
- Add a Text Cards to a Dashboard
- Write text longer than the card height
- Save

![screenshot-2018-3-20 mtw-behavior dashboard metabase](https://user-images.githubusercontent.com/3098101/37647465-999e0e86-2c2c-11e8-8667-4a9d4f3dc329.png)

To work on Firefox, the `.DashCard` div has a defined height that should be the `max-height` of the father div of the `.text-card-markdown` (the overflowed div where the text is written).

**Comment by jornh** [comment] 2018-08-15 16:28
Prompted by [this topic on Discourse](http://discourse.metabase.com/t/issue-with-text-boxs/4170) I just re-tested this.

The issue seems to have been spreading since originally reported 
Now, with both `v0.30.0` and `v0.29.3` across Chrome, Edge and Firefox on Windows I don't get any scrollbar. I'm speculating it's possibly gotten worse since the otherwise awesome "background-less" heading textboxes introduced together with X-ray automagic dashboards.

**Comment by jornh** [comment] 2018-08-15 16:30
To add a bit to the case I think a sensible behavior would be no scrollbars when it's a "backgroundless" heading-card. And that it keeps to old vertical scrollbar behavior on overflow behavior for "normal bordered" cards.

**Comment by flamber** [comment] 2019-02-18 20:53
Duplicate of #8333 (seems to be an issue on all browsers now) - still exists on 0.31.2

**Comment by salsakran** [comment] 2019-05-09 02:07
should be closed in #9919

**Closed by salsakran** 2019-05-09 02:07 UTC
Labels: Bug, Dashboards, Priority/P3, Visualization
