### ISSUE TITLE
Date breakout "by" selection box display issues if too low on screen

### ISSUE THREAD

**Issue by jeff303** [metabase/metabase#15445] opened 2021-04-01 18:34 UTC
**Describe the bug**
The box where users can select the date breakdown "by" (ex: hour, day of month, etc.) is tiny and doesn't grow on scroll, when it initially expands near the bottom of the window.

**Logs**
N/A

**To Reproduce**
1. Create a question based on the sample Orders table
2. Create an aggregation and then click Created at for the breakdown selection
3. Click the "by" option to open the breakdown resolution popup
4. Notice the box is tiny if the Created at row was low on the screen in step 2, and it does not expand when scrolling the viewport down

**Expected behavior**
This dialog should be large enough to show most of the options, regardless of how much space exists between its "top" when opened and the bottom of the viewport.

**Screenshots**
After step 3 above:
<img width="1167" alt="breakout_resolution_box_1" src="https://user-images.githubusercontent.com/3521562/113338449-bdda3c80-92ee-11eb-9db6-7cbdd165a6fa.png">

Scrolling within that tiny dialog box (difficult):
<img width="564" alt="breakout_resolution_box_2" src="https://user-images.githubusercontent.com/3521562/113338521-d8141a80-92ee-11eb-95d4-2d2f05a97684.png">

If scrolling the viewport up (i.e. scrolling directly on the question editor canvas):
<img width="572" alt="breakout_resolution_box_3" src="https://user-images.githubusercontent.com/3521562/113338553-e104ec00-92ee-11eb-96fe-4161282010f4.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 89
- Your operating system: OS X 11
- Your databases: SQL Server
- Metabase version: 0.39
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Minor

**Additional context**

**Comment by flamber** [comment] 2021-04-01 21:10
I'm not sure if this is a side-effect of #15446 or upgrade of React, but this makes it difficult to use.

**Comment by nemanjaglumac** [comment] 2021-04-07 11:33
@howonlee Not sure if you've already started to work on a fix for this. Just a note that there is now a repro for this issue that should be unskipped and merged together with the fix.
Thanks

**Comment by howonlee** [comment] 2021-04-07 21:16
OK, it does look like the react 16 upgrade popover issues have one common root cause, which is that popover's sizeToFit option is borked. I will attempt to unbork and upload fix which will hopefully be overall fix

**Closed** 2021-04-14 01:06 UTC
Labels: .Regression, .Reproduced, Priority:P2, Querying/Notebook, Type:UX
