### ISSUE TITLE
.48.0 upgrade: js front error regression on some questions 

### ISSUE THREAD

**Issue by wadjeroudi** [metabase/metabase#36895] opened 2023-12-18 12:36 UTC
### Describe the bug

After upgrade to .48.0, we have a js error when displaying some results, the ajax request returns the data, everything seems good but on the front we have two errors :

![image](https://github.com/metabase/metabase/assets/7465362/c4d04ce5-24ff-49cf-8475-5afe59b07be7)

![image](https://github.com/metabase/metabase/assets/7465362/7bcd1406-c290-4fcf-9442-52222f9965e5)

Don't have a lot of information, but maybe it's enough explicit for you guys ?

### Logs

nothing in the logs, because the results are returned correctly

### Information about your Metabase installation

```JSON
happens on chrome & firefox
```

### Severity

medium

**Comment by paoliniluis** [comment] 2023-12-18 12:56
We would need to know the question type and parameters

**Comment by wadjeroudi** [comment] 2023-12-18 13:31
find how to reproduce, when using trend, if you have a value null, you have a js error
```
SELECT DATE_SUB( CURDATE(), INTERVAL 1 YEAR ) as date, null as percent
union
select CURDATE(), 0.05

**Comment by paoliniluis** [comment] 2023-12-18 14:10
Hi, I created that native SQL
![image](https://github.com/metabase/metabase/assets/1711649/164e049a-c8c3-4b5f-93a3-dd4a0c17e004)

added a trend line
![image](https://github.com/metabase/metabase/assets/1711649/0af3afa5-6f78-40f5-8518-ea0ccc226b45)

but I'm not getting any error

**Comment by wadjeroudi** [comment] 2023-12-18 14:17
not a trend line
https://www.metabase.com/docs/latest/questions/sharing/visualizations/trend

this kind of trend (it auto compares with previous line when you have a two line result);
![image](https://github.com/metabase/metabase/assets/7465362/6159a635-9327-4332-90dd-b2831c30235f)

**Comment by JesseSDevaney** [comment] 2023-12-18 18:32
Here is a query that reproduces the issue (without needing a specific external DB)

```sql
SELECT '2022-12-01'::DATE as date, null as percent
union
select '2023-12-01'::DATE, 0.05
```

**Comment by wadjeroudi** [comment] 2023-12-18 18:41
thank you @JesseSDevaney 

if i'm not mistaken it also bugs when your return only one line
for example first select returns nothing (it was handled correctly before .48.0).

**Comment by JesseSDevaney** [comment] 2023-12-18 18:55
> regression comes from this PR #35184 if I'm not mistaken

The error is coming from this line https://github.com/metabase/metabase/blob/release-x.48.x/frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.jsx#L110 where we introduced date displays with trend values (introduced in a PR earlier than #35184).

The issue in this case is that we are trying to format a date with an invalid `unit` of time (`null` in this case). This occurs because of the use of a native query where units are not always inferred because of the potential irregularity of the data. Since this query does not have a given date unit for which to format dates, it is throwing an error because `unit` on line 110 is null.

We just need to display the full dates in the event that the date unit is not supplied.

**Comment by JesseSDevaney** [comment] 2023-12-18 19:17
> if i'm not mistaken it also bugs when your return only one line for example first select returns nothing (it was handled correctly before .48.0).

Thank you for mentioning this! Yes, it was doing that. This PR
- https://github.com/metabase/metabase/pull/36912

fixes that case as well.

**Comment by JesseSDevaney** [comment] 2023-12-19 17:45
Waiting on backport to merge before closing

**Closed** 2023-12-20 01:19 UTC
Labels: Type:Bug, Priority:P2, .Frontend, .Regression
