### ISSUE TITLE
[Flaky test] models/reproductions.cy.spec.js 

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#43908] opened 2024-06-10 05:22 UTC
[job](https://github.com/metabase/metabase/actions/runs/9416878147/job/26004328722?pr=43821#step:13:608)

**Comment by iethree** [comment] 2024-06-10 14:54
duplicate of https://github.com/metabase/metabase/issues/43934

**Closed by iethree** 2024-06-10 14:54 UTC
Labels: .CI & Tests, .Frontend, flaky-test-fix
