### ISSUE TITLE
App + Web properties of Google Analytics don't appear on Metabase Editor

### ISSUE THREAD

**Issue by GuiCarneiro** [metabase/metabase#11396] opened 2019-11-27 14:03 UTC
I migrated my data from Firebase Analytics to Google Analytics, which creates a new property in Google Analytics of type Web App.

However, this property does not appear in the Metabase editor.
Do we not support this type of property? Is it some kind of bug?

Example:
![image](https://user-images.githubusercontent.com/5458742/69729652-772a7000-1105-11ea-961c-ad37d7a32552.png)

![image](https://user-images.githubusercontent.com/5458742/69729681-89a4a980-1105-11ea-819f-d15c820aad15.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment] 2020-01-17 23:11
Hmm, did you try re-syncing the Google Analytics "database" in Metabase manually and refreshing the query builder page after a few minutes? You can check on the stats of the sync process from the Troubleshooting tab of the Admin Panel.

**Comment by erashdan** [comment] 2020-02-13 09:46
Any update with this ? still not solved

**Comment by rubenarevalo** [comment] 2020-05-13 14:44
any updates on this? I have the same issue @mazameli

**Comment by mustafashabib** [comment] 2020-08-27 23:12
I have the same issue - I've rescanned my connection and even re-added the GA connection. It looks like only `WebProperties` are being picked up? https://github.com/metabase/metabase/blob/ce84557570477382419a5c7517288a4deda6df79/src/metabase/driver/googleanalytics.clj#L42-L43

**Comment by flamber** [comment] 2020-08-28 08:32
@mustafashabib But which property should Metabase also be requesting? Can you link to some documentation?

**Comment by lukabirsa** [comment] 2020-08-31 16:05
I'm having the same issue. I've migrated the data from Firebase to GA and I'd like to query the data via Metabase. 

I get all the other properties but the web+app ones. Is it possible to address this?

**Comment by lukabirsa** [comment] 2020-09-01 14:21
@flamber if you require additional operational information from my end please let me know. I'm really looking towards having this bug fixed.

**Comment by flamber** [comment] 2020-09-01 14:29
@lukabirsa We have been asking for more information since the start, but no one has provided any, so yes, please do.
This is not a bug - this is a feature request - it's not something that Metabase has ever supported.

**Comment by lukabirsa** [comment] 2020-09-01 15:04
@flamber - Google Analytics supports two types of properties that you can track events on (just to be clear "property" in this case means Google Analytics Account -> Google Analytics Property which is also listed in the Metabase dropdown). 

The two properties are:
1. Web Properties - this are the standard GA properties .This is the legacy stuff that runs on most web pages. **These are listed** in the metabase dropdown.
2. Web+App Properties (as seen in the screen grab)  - these are the new Google Analytics properties, that are also used when you migrate Firebase analytics to Google Analytics. I would venture a guess that the same Web+App was also used before Google integrated Firebase with Google Analytics, but not as often.  GA Properties that are of this type are not detected by Metabase and you do not have the option of querying via Metabase.

It's not clear if this is a feature request, you might just be sanitizing the output from Google when creating the "DB" connection and filtering all non-Web Properties. It's actually likely that Google kept the same API for both (I could not find an alternative API to enable).

**Comment by flamber** [comment] 2020-09-01 15:09
@lukabirsa I'm fairly sure that Web+App didn't exists, when the GA driver was created, which is why I call this a feature request.

**Comment by lukabirsa** [comment] 2020-09-01 15:09
@flamber All good. Do let me know if you require additional information.

**Comment by lukabirsa** [comment] 2020-09-11 06:57
@flamber any updates here?

**Comment by flamber** [comment] 2020-09-11 10:16
@lukabirsa There's 1700 other open issues, so unless you submit a PR, I don't expect this to implemented soon.

**Comment by Jihadik** [comment] 2020-11-10 19:47
Up and subscribe to the issue.

**Comment by camsaul** [comment] 2023-06-28 17:21
Closing as not planned due to dropping GA support

**Closed by camsaul** 2023-06-28 17:21 UTC
Labels: Priority:P2, .Limitation, Type:New Feature, Database/Google Analytics
