### ISSUE TITLE
Query Editor loses information when Views are dropped and then recreated

### ISSUE THREAD

**Issue by Jyggafey** [metabase/metabase#3331] opened 2016-09-08 11:50 UTC
We have several (materialized) views in our postgres db.
We regularly DROP those Views and then CREATE them again (same schema."name" each).
When we do that, the cards based on questions using data from those Views display result data in dashboards but when i look at a single card, the query editor does not display the information which source and filter was used (while retaining grouping and view type). 
- I can view the SQL for the Question and SQL based questions are unaffected.
- When i select the data source for the card again (the recreated materialized view) and save the changes, replacing the original Question, the query editor retains the information until the next drop/create of the view.
- Triggering a database sync does not fix the issue.

Is Metabase using something other than schema."name" to identify source tables in the editor or is there some known Bug affecting the editor?
### Bug Report Info
-  I'm running Metabase:
  - [x] Locally from the JAR
- _Internally_, Metabase is using this database: 
  - [x] H2
-  My data is in a database of this type:
  - [x] Postgres
-  I'm using Metabase version:
  - [x] 0.19.3

**Comment by Jyggafey** [comment] 2016-10-04 15:06
The same happens with plain tables, all meta data is lost and the query editor, for cards based on the dropped/created views, looses all information related to the source and fields of the source.
Can this be fixed? Does it have to be fixed in the metabase table model oder in the frontend?

**Comment by rafaelveloso** [comment] 2016-10-04 15:42
I'm having this issue as well.

**Comment by tlrobinson** [comment] 2016-10-04 17:31
This sounds like a metadata sync issue. @camsaul knows this better, but I believe tables are identified by their name (and schema), so I'm not sure what's going on. If Metabase happens to sync between the time you drop and recreate the table/view it might be possible it's marking it as removed then creating a new one.

**Comment by Jyggafey** [comment] 2016-10-06 17:27
the DROP and CREATE for each view/table are executed within a second or two, the script is executed each night at 5:37 and runs just a couple of seconds, so timing should not be the issue.

Maybe a related issue and a conclusion based on glancing at metabase source:
When i change a field name in one of the tables, i have to trigger a sync roughly 3 times until the field is properly shown in the data model section of the admin. 
While this might be related to the "stale data in frontend" issue, could it be that rawtable and rawcolumns are beeing updated but the table model is then not actually updated until the next sync?

**Comment by Jyggafey** [comment] 2016-11-14 13:40
is there any chance this gets fixed in the next release? this really diminishes the usefulness of metabase for people not fluent in sql.
I dont know if it was something in 0.20.3 but now the cards are empty after each DROP/CREATE cycle.
I have to either re build the query using the UI or "touch" the sql after converting to sql (i usually add a * in the converted sql since it is always missing.)
Only after triggering an onchange event in the converted sql textbox or re building the query with the QueryBuilder the get answer button becomes usable again.
All meta data for the database is still lost every day so every feature related to that is not usable.

**Comment by Jyggafey** [comment] 2016-12-12 14:23
😢

**Comment by Jyggafey** [comment] 2016-12-13 17:15
I would be interested in the current status of this issue. 
Can we help with this somehow?
Is it feasible to dig into it ourselves or did you already determine the needed changes and deemed them too big for the release or fused them into a bigger effort regarding a refactoring?

**Comment by rigoleto** [comment] 2017-01-20 23:02
This issue has affected us as well. Postgres's materialized views are a great way to organize a complex data model to make data more digestible by non-technical users, but it appears (as suggested above) that they're being recognized internally by some sort of incrementing ID rather than by name, hence the data loss on recreation.

Since this doesn't affect regular tables, pur workaround for the time being is to use `CREATE TABLE not_really_a_view AS ();` instead of materialized views. While you lose the benefit of on-command refreshes, you get the same performance characteristics of having expensive joins and calculations done ahead of time.

In the future I'd love to be able to use materialized views. Is there a way I could copy questions & configuration from the regular tables I'm using to materialized views down the road?

**Comment by salsakran** [comment] 2017-01-22 19:57
this is a regression. we should definitely be finding schemas, table or fields that disappear and maintaining that relationship.

**Closed** 2017-03-01 22:47 UTC
Labels: Bug, Metadata/Sync, Priority/P1

**Comment by Jyggafey** [comment] 2017-03-07 17:06
🎉  ❤️

**Comment by tbatchelli** [comment] 2018-01-24 21:10
I am still experiencing this, and I am now on 0.27.2 ... is there a way to start with a clean slate without losing all the created queries and dashboards?
