### ISSUE TITLE
Deleting a column description in the data model causes an error

### ISSUE THREAD

**Issue by nickhamlin** [metabase/metabase#15528] opened 2021-04-08 14:10 UTC
**Describe the bug**
If I want to remove the description of a column, I'd go to the data model and delete it. When I do that, my changes aren't saved when I click out of 

**Logs**
JS console (there's a bunch of these, but the gist is that the PUT request that's trying to write that value back to the DB is getting a 400 error:
```
VM164:1 PUT https://<OUR_METABASE_URL_HAS_BEEN_REDACTED>/api/field/20692 400
(anonymous) @ VM164:1
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
value @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
l @ vendor.bundle.js?fc4444c0c12ca7310634:98
(anonymous) @ vendor.bundle.js?fc4444c0c12ca7310634:98
(anonymous) @ vendor.bundle.js?fc4444c0c12ca7310634:98
r @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
l @ vendor.bundle.js?fc4444c0c12ca7310634:98
(anonymous) @ vendor.bundle.js?fc4444c0c12ca7310634:98
(anonymous) @ vendor.bundle.js?fc4444c0c12ca7310634:98
r @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
l @ vendor.bundle.js?fc4444c0c12ca7310634:98
(anonymous) @ vendor.bundle.js?fc4444c0c12ca7310634:98
(anonymous) @ vendor.bundle.js?fc4444c0c12ca7310634:98
r @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
l @ vendor.bundle.js?fc4444c0c12ca7310634:98
(anonymous) @ vendor.bundle.js?fc4444c0c12ca7310634:98
(anonymous) @ vendor.bundle.js?fc4444c0c12ca7310634:98
r @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ vendor.bundle.js?fc4444c0c12ca7310634:485
r.updateField @ app-main.bundle.js?fc4444c0c12ca7310634:5
r.handleChangeDescription @ app-main.bundle.js?fc4444c0c12ca7310634:5
value @ app-main.bundle.js?fc4444c0c12ca7310634:5
i @ vendor.bundle.js?fc4444c0c12ca7310634:115
s @ vendor.bundle.js?fc4444c0c12ca7310634:115
executeDispatchesInOrder @ vendor.bundle.js?fc4444c0c12ca7310634:115
d @ vendor.bundle.js?fc4444c0c12ca7310634:98
f @ vendor.bundle.js?fc4444c0c12ca7310634:98
e.exports @ vendor.bundle.js?fc4444c0c12ca7310634:448
processEventQueue @ vendor.bundle.js?fc4444c0c12ca7310634:98
(anonymous) @ vendor.bundle.js?fc4444c0c12ca7310634:485
handleTopLevel @ vendor.bundle.js?fc4444c0c12ca7310634:485
f @ vendor.bundle.js?fc4444c0c12ca7310634:485
perform @ vendor.bundle.js?fc4444c0c12ca7310634:98
batchedUpdates @ vendor.bundle.js?fc4444c0c12ca7310634:485
batchedUpdates @ vendor.bundle.js?fc4444c0c12ca7310634:92
dispatchEvent @ vendor.bundle.js?fc4444c0c12ca7310634:485
Show 25 more frames
app-main.bundle.js?fc4444c0c12ca7310634:5 Request entities,fields,20692,update failed: {status: 400, data: {…}, isCancelled: false}
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
l @ vendor.bundle.js?fc4444c0c12ca7310634:98
(anonymous) @ vendor.bundle.js?fc4444c0c12ca7310634:98
(anonymous) @ vendor.bundle.js?fc4444c0c12ca7310634:98
r @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
Promise.then (async)
r @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
l @ vendor.bundle.js?fc4444c0c12ca7310634:98
(anonymous) @ vendor.bundle.js?fc4444c0c12ca7310634:98
(anonymous) @ vendor.bundle.js?fc4444c0c12ca7310634:98
r @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ app-main.bundle.js?fc4444c0c12ca7310634:5
(anonymous) @ vendor.bundle.js?fc4444c0c12ca7310634:485
r.updateField @ app-main.bundle.js?fc4444c0c12ca7310634:5
r.handleChangeDescription @ app-main.bundle.js?fc4444c0c12ca7310634:5
value @ app-main.bundle.js?fc4444c0c12ca7310634:5
i @ vendor.bundle.js?fc4444c0c12ca7310634:115
s @ vendor.bundle.js?fc4444c0c12ca7310634:115
executeDispatchesInOrder @ vendor.bundle.js?fc4444c0c12ca7310634:115
d @ vendor.bundle.js?fc4444c0c12ca7310634:98
f @ vendor.bundle.js?fc4444c0c12ca7310634:98
e.exports @ vendor.bundle.js?fc4444c0c12ca7310634:448
processEventQueue @ vendor.bundle.js?fc4444c0c12ca7310634:98
(anonymous) @ vendor.bundle.js?fc4444c0c12ca7310634:485
handleTopLevel @ vendor.bundle.js?fc4444c0c12ca7310634:485
f @ vendor.bundle.js?fc4444c0c12ca7310634:485
perform @ vendor.bundle.js?fc4444c0c12ca7310634:98
batchedUpdates @ vendor.bundle.js?fc4444c0c12ca7310634:485
batchedUpdates @ vendor.bundle.js?fc4444c0c12ca7310634:92
dispatchEvent @ vendor.bundle.js?fc4444c0c12ca7310634:485
Show 8 more frames
app-main.bundle.js?fc4444c0c12ca7310634:5 Uncaught (in promise) {status: 400, data: {…}, isCancelled: false}
```

**To Reproduce**
1. Go to the data model
2. Click on the description of a column that already has one in place
3. Delete all the text in that field
4. Click out of the field, which normally auto-saves changes
5. The original text will reappear, along with errors in the JS console

**Expected behavior**
I should be able to delete all text in a description and have it save my change

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "4.9.41-moby",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.26-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-03-09",
      "tag": "v0.38.2-SNAPSHOT",
      "branch": "globalgiving-v0.38.1.1",
      "hash": "00c03d3"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```

**Severity**
Not a huge deal, just annoying.

**Comment by flamber** [comment] 2021-04-08 14:24
Duplicate of #11097
The interesting part would be in the stacktrace in the Admin > Troubleshooting > Logs, not the browser in this case.

**Closed by flamber** 2021-04-08 14:24 UTC
Labels: .Needs Triage, Type:Bug
