### ISSUE TITLE
Metabase is consistently freezing up

### ISSUE THREAD

**Issue by rbhalla** [metabase/metabase#8284] opened 2018-08-10 14:58 UTC
## Setup

I'm using the metabase docker image and have experienced this on version 0.29.3 and 0.30.0 when using a Redshift (5 node) cluster as a data source and a Postgres database as a data source.

Metabase is using another Postgres database as an internal cluster and is being hosted on an m4.large aws ec2 instance.

## Issue
The issue seems to be that longer running queries seem to be freezing up the container (CPU spikes to 100%). This makes any other request unresponsive/incredibly slow. This has 2 side effects:

1) No other user can make a query or use the app
2) Health checks aren't responded to in time which causes the container to be restarted

From a user's perspective, one person doing a long query can cause the entire thing to be down for several minutes without the query ever really showing the result.

## Observations
I'm not too familiar with the internals, but I'm not entirely sure why CPU should be spiking so intensley as the results are being streamed back. I imagine some sort of post processing is happening. One error I've consistently seen to make me think this is:

`Error recording results metadata for query: Input to infer-special-type does not match schema`

However, the application doesn't always throw an error before it is forced to restart, so it's possible this error is a red herring.

I'm currently giving everything (Redshift, Postgres and Metabase) a lot more resources than is probably needed and yet I've not been able to get to a point where someone can reliably use Metabase. I have been using Metabase for a little while now and have only been experiencing these problems in the last few months, unfortunately I've not been able to pinpoint it to a specific version upgrade, but nothing on here indicates that the latest versions should be worse.

Does anyone have any ideas on how I can go about improving the reliability of the application and/or what could be causing the problem?

**Comment by phamnamlong** [comment] 2018-08-14 17:04
Just to confirm that we also experience a similar problem and have to consider not using Metabase for production. The problem is that Metabase takes up too much memory, most probably due to periodic queries for schemas which helps the system pop up suggestion quickly.

**Comment by sbelak** [comment] 2018-08-14 17:10
@rbhalla do you happen to have a full trace for that error?

**Comment by phishy** [comment] 2018-08-14 20:32
It also seems that java will only use 25% of the CPU, even when given more resources..

**Comment by rjurado01** [comment] 2018-08-23 13:01
We have similiar problem and we have detected that only happens with ssl added. This is very strange.

**Comment by vijayvenkatesh** [comment] 2018-08-28 21:03
we are seeing this and are running v0.30.0 - having to restart the java proc about 2-3x a day. We are trying to tune the queries and move to a larger box, but wish the logs were available if the web metabase console was unresponsive.

**Comment by fdegiuli** [comment] 2018-08-29 19:42
This could be related to https://github.com/metabase/metabase/issues/8311 and https://github.com/metabase/metabase/issues/8202

**Comment by jornh** [comment] 2018-09-07 05:13
With #8312 resolved in 0.30.2 I’m wondering if this one got squashed as well?

Please retest with 0.30.2 just out. Thanks! 🙂

As @fdegiuli so helpfully noted in https://github.com/metabase/metabase/issues/8284#issuecomment-417080160 this could be related to a bunch of other resource exhaustion bug reports. So important to know how many can be swept under the same rug (or not!)

@rbhalla   I’m not sure if you’re running https, so unsure if this has the criteria mentioned in https://github.com/metabase/metabase/issues/8312#issuecomment-417326691

**Comment by rodriguealcazar** [comment] 2019-03-21 09:26
We are experiencing the same issue using Metabase 0.31.2 installed on an AWS EC2 t3.medium instance using a Redshift database. We see a surge in CPU usage, an OOM and then Metabase is unresponsive.

**Comment by MarkRx** [comment] 2019-03-21 16:30
Check to see if someone launched off an x-ray. We have them turned off because they tank our database.

**Comment by mazameli** [comment] 2019-09-30 23:12
@metabase/core-developers Any suggestions for how we might go about verifying if this issue is in fact resolved? It was reported over a year ago, and there doesn't appear to have been more reports of it since 0.30.2, except for one instance that might have been actually related to an x-ray (i.e. not this issue).

**Comment by salsakran** [comment] 2019-09-30 23:16
We made some pretty big stability improvements in 0.32 (async + reduced memory consumption). I vote we close this and see if something similar crops back up?

**Closed** 2019-09-30 23:19 UTC
Labels: Operation/, Type:Performance
