### ISSUE TITLE
Unused variables slow down query execution

### ISSUE THREAD

**Issue by dtheodor** [metabase/metabase#4640] opened 2017-03-29 13:34 UTC
_Running metabase 0.23 against mariadb columnstore._

I have a simple query

```sql
SELECT count(distinct event_id) AS "Events"
FROM events
```
which I want to be able to heavily parametrize through dashboard filters, so I am adding several field and text filters to it

```sql
SELECT count(distinct event_id) AS "Events"
FROM events
[[WHERE {{organization}}]]
[[AND {{timestamp}}]]
[[AND {{continent}}]]
[[AND {{country}}]]
[[AND {{event_category}}]]
[[AND {{event_type}}]]
[[AND {{acting_user_email}}]]
[[AND {{acting_user_domain}}]]
[[AND (acting_user_is_organization_member = {{is_external}} OR target_user_is_organization_member = {{is_external}})]]
[[AND {{device}}]]
...
```

for a total of 20 filters (yes, I know the metabase dashboards suck at displaying 20 filters at the moment but that's a different problem).

Running the query before defining any of these variables results in **67 ms** execution time

```sh
03-29 16:14:18 DEBUG middleware.mbql-to-native :: NATIVE FORM: 😳
{:query "SELECT count(distinct event_id) AS \"Events\"\nFROM events\n", :template_tags {}}
03-29 16:14:18 DEBUG metabase.middleware :: POST /api/dataset 200 (67 ms) (5 DB calls)
```

Running the query with all the variables defined but _none of them used_ results in **589 ms** execution time

```sh
...
PARAMS/SUBSTITUTED: 😻
{:native
 {:query
  "SELECT count(distinct event_id) AS \"Events\"\nFROM events\nWHERE 1 = 1\nAND 1 = 1\nAND 1 = 1\nAND 1 = 1\nAND 1 = 1\nAND 1 = 1\nAND 1 = 1\nAND 1 = 1\nAND 1 = 1\n\nAND 1 = 1\nAND 1 = 1\nAND 1 = 1\nAND 1 = 1\nAND 1 = 1\nAND 1 = 1\nAND 1 = 1\nAND 1 = 1\nAND 1 = 1\nAND 1 = 1\nAND 1 = 1\nAND 1 = 1",
  :params ()}}
03-29 16:14:33 DEBUG middleware.mbql-to-native :: NATIVE FORM: 😳 ...big wall of text with all the parameters ...
03-29 16:14:33 DEBUG metabase.middleware :: POST /api/dataset 200 (589 ms) (26 DB calls)
```

Why is metabase emitting different SQL and amount of SQL queries in the case where there's not a single variable used compared to the SQL emitted when there's no variables defined? Which obviously is the reason of this terrible slowdown

**Comment by tlrobinson** [comment] 2017-03-30 20:54
I would expect the database to compile those `1=1`'s away, but I guess not.

For "field filter" tags we emit `1=1` so you don't need to put the `[[...]]` brackets around optional clauses.

However, if you *do* include the brackets then I think it would make sense to remove those clauses like we do for non-field filter clauses.

BTW if we did do that this won't work correctly if `organization` is omitted:

```sql
FROM events
[[WHERE {{organization}}]]
[[AND {{timestamp}}]]
```

you'd end up with `FROM events AND {{timestamp}}`

You'd need to do

```sql
FROM events
WHERE 1=1
[[AND {{organization}}]]
[[AND {{timestamp}}]]
```

Alternatively, it would probably be safe for us to replace a series of `AND 1=1 AND 1=1 ...` with a single `AND 1=1`.

**Comment by salsakran** [comment] 2017-03-30 20:55
My hunch is that this might be due to DB calls in the QueryProcessor middleware.

**Comment by flamber** [comment] 2021-11-07 20:17
Closing, since I cannot reproduce in 0.41.1, but a lot has changed in QP since 0.23

**Closed by flamber** 2021-11-07 20:17 UTC
Labels: Type:Performance, Querying/Parameters & Variables
