### ISSUE TITLE
Dashboard Graphs containing more than one question cannot be formatted

### ISSUE THREAD

**Issue by tomalbon** [metabase/metabase#9676] opened 2019-04-03 09:02 UTC
### When did this start?

Yesterday we updated to version 0.32.1, which seems to have caused a graph formatting issue with dashboard graph blocks that contain more than one question.

### Bug

When adding more than one question to a dashboard block that is using a visual display, such as a bar chart, the individual questions can no longer be formatted within the block. Instead, all subsequent questions copy the formatting and name of the original question. For example, the below chart contains two stacked questions: *Call Centre PPC Bookings* and *Online PPC Bookings* (axis figures have bee redacted). However, both bars are the same colour and have the same title:

![Screenshot 2019-04-03 at 09 32 48](https://user-images.githubusercontent.com/10614152/55466205-a5979000-55f6-11e9-977a-6954ac8af740.png)

The edit options for this graph block no long allow each question to be independently formatted. Instead, we see just one formatting option:

![Screenshot 2019-04-03 at 09 38 01](https://user-images.githubusercontent.com/10614152/55466433-0f179e80-55f7-11e9-8bc2-2641b13305ea.png)

Graph blocks prior to the update express the same issue, as do new blocks added to dashboards that have more than one graph.

I can fix my specific use case by condensing data into a single query, but because this looks like a bug, I thought it would be helpful to report it.

### Environment

- Browser and the version: Tested in Safari 12.0.3 and Chrome 72.0.3626.121
- Operating system: Mac OS Mojave 10.14.3 
- Databases: MySQL, Google Analytics
- Metabase version: 0.32.1

### Repeatable steps to reproduce the issue

Add a graph question block to a dashboard, and add a second question to the same block.

**Comment by flamber** [comment] 2019-04-03 17:38
Duplicate of #9636

**Comment by mazameli** [comment] 2019-04-03 17:40
Yep, this is a dupe. We believe we have a fix in https://github.com/metabase/metabase/pull/9673

**Closed by mazameli** 2019-04-03 17:40 UTC
Labels: Duplicate
