### ISSUE TITLE
Multiple Cumulative Sums fail to calculate correctly

### ISSUE THREAD

**Issue by littlegoblin9876** [metabase/metabase#6720] opened 2018-01-18 03:23 UTC
I have a dataset that has two numerical columns - Actual and Budget associated with a month:

| Month | Actual | Budget |
| ------- | ------- | -------- |
| Jan | 10 | 5 |
| Feb | 2 | 5 |
| Mar | 15| 5|
etc...

If I create a question with a single cumulative sum on either Actual or Budget I get what I expect, however if I try to create a question with Cumulative(Actual) and Cumulative(Budget) the first displays correctly however the second reports the values in the correlating "Actual" field rather than the cum budget:

| Month | cum(Actual) | cum(Budget) |
| ------------- | ------- | ------ |
| Jan | 10 | **10** |
| Feb | 12 | **2**|
| Mar | 27| **15**|

Browser: Version 63.0.3239.132 (Official Build) (64-bit)
Client OS: Windows Server 2008
Server OS: Centos 6
Database: Postgres 9
Metabase: v0.27.2

**Comment by salsakran** [comment] 2018-02-02 01:52
related to #2862

**Comment by tmpkn** [comment] 2018-06-28 03:50
Wasted hours trying to debug this issue, it should be clearly marked in UI / docs.

**Comment by Sire** [comment] 2021-01-07 10:32
@flamber, this seems to be a dupe of #2862 and can be closed?

If so, the bug is soon celebrating 5 years 😅 
(Hope you guys get more customers / funding / resources soon, the product is otherwise excellent).

**Comment by flamber** [comment] 2021-01-07 11:21
@Sire No, this issue is about 2 CumSum columns with 1 breakout, whereas #2862 is about 1 CumSum with multiple breakouts.
But this issue is fixed. I tested 0.34.3 thru 0.37.5 and I'm seeing correct calculations on both columns.
![image](https://user-images.githubusercontent.com/1447303/103886651-1f20b400-50e2-11eb-865c-52dd81fb61b1.png)

**Closed by flamber** 2021-01-07 11:21 UTC
Labels: Priority:P2, Querying/GUI, Type:UX
