### ISSUE TITLE
Joining GA and SQL

### ISSUE THREAD

**Issue by yasinsancaktutan** [metabase/metabase#9205] opened 2019-01-03 11:54 UTC
Hello,

I have managed to add my Google Analytics data to Metabase. I also have another DB consisting website related data (Postgresql). Is there a way to simply join these two?

Thank you all for providing this amazing product!

**Comment by flamber** [comment] 2019-01-03 13:09
Duplicate of #3953

**Comment by salsakran** [comment] 2019-01-03 23:33
closing as a dupe.

**Closed by salsakran** 2019-01-03 23:33 UTC
