### ISSUE TITLE
Migration h2 -> MySQL (Windows Server); Error Code: "90013-194" 

### ISSUE THREAD

**Issue by leowmjw** [metabase/metabase#6588] opened 2017-12-18 07:42 UTC
Hit the following when attempting migration to MySQL (on AWS RDS); did not find previous reported issue:
``` 
Command failed with exception: Database "mem:" not found [90013-194]
```

# Bugs

System Details:
-----------------
- H2 migrate to AWS RDS (MySQL 5.7.17)
- Windows Server 2016
- Metabase v0.27.1

Logs
-----
```
Mon Dec 18 12:27:28 SRET 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must
be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disab
le SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
12-18 12:27:28 INFO metabase.db :: Setting up Liquibase...
Mon Dec 18 12:27:28 SRET 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must
be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disab
le SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
12-18 12:27:28 INFO metabase.db :: Liquibase is ready.
12-18 12:27:28 INFO metabase.db :: Checking if Database has unrun migrations...
12-18 12:27:31 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
12-18 12:27:31 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
12-18 12:27:31 INFO metabase.db :: Database has unrun migrations. Waiting for migration lock to be cleared...
12-18 12:27:31 INFO metabase.db :: Migration lock is cleared. Running migrations...
12-18 12:27:32 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
12-18 12:27:32 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
12-18 12:28:27 INFO metabase.db :: Database Migrations Current ...
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
Mon Dec 18 12:28:27 SRET 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must
be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disab
le SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Temporarily disabling DB constraints...
[OK]
org.h2.jdbc.JdbcSQLException: Database "mem:" not found [90013-194]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.engine.Engine.openSession(Engine.java:62)
        at org.h2.engine.Engine.openSession(Engine.java:176)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
        at org.h2.engine.Engine.createSession(Engine.java:137)
        at org.h2.engine.Engine.createSession(Engine.java:27)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
        at org.h2.Driver.connect(Driver.java:69)
        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:358)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:225)
        at metabase.cmd.load_from_h2$load_data_BANG_.invokeStatic(load_from_h2.clj:143)
        at metabase.cmd.load_from_h2$load_data_BANG_.invoke(load_from_h2.clj:142)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__45530.invoke(load_from_h2.clj:217)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:714)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:740)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:697)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:214)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:207)
        at clojure.lang.Var.invoke(Var.java:379)
        at metabase.core$load_from_h2.invokeStatic(core.clj:217)
        at metabase.core$load_from_h2.invoke(core.clj:210)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.core$apply.invoke(core.clj:641)
        at metabase.core$run_cmd$fn__46460.invoke(core.clj:277)
        at metabase.core$run_cmd.invokeStatic(core.clj:277)
        at metabase.core$run_cmd.doInvoke(core.clj:276)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$apply.invoke(core.clj:641)
        at metabase.core$_main.invokeStatic(core.clj:291)
        at metabase.core$_main.doInvoke(core.clj:287)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at metabase.core.main(Unknown Source)
Command failed with exception: Database "mem:" not found [90013-194]
```

**Comment by camsaul** [comment] 2017-12-18 20:05
@leowmjw what command-line arguments are you passing?

**Comment by leowmjw** [comment] 2017-12-30 11:21
@camsaul After setting up the env variables; the jar is started as below:

```
$env:MB_JETTY_HOST=“0.0.0.0”
$env:MB_DB_TYPE=“mysql”
$env:MB_DB_DBNAME=“metabase”
$env:MB_DB_PORT=“3306”
$env:MB_DB_USER=“presto”
$env:MB_DB_PASS="<db_pass>”
$env:MB_DB_HOST=“<db_host>”

java -jar —add-modules java.xml.bind .\metabase.jar load-from-h2  .
```

**Comment by flamber** [comment] 2020-05-24 22:42
Closing. This was likely caused by `load-from-h2  .` not referring to the H2 file:
https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html

**Closed by flamber** 2020-05-24 22:42 UTC
Labels: Operation/
