### ISSUE TITLE
Unable to Save Custom Query with Join

### ISSUE THREAD

**Issue by alpha1** [metabase/metabase#11160] opened 2019-10-17 01:05 UTC
**Describe the bug**
I am using Metabase hosted by a provider version 0.33.4, but am happy to run a docker instance to help test. Multiple users, with different databases, are having the same issues.
This seems similar to #11054 and #10805.

**Logs**
`
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
app-main.bundle.js:5:131612
TypeError: e is undefined
app-main.bundle.js:5:173252
`
**To Reproduce**
1. Click ask a question
2. Click Custom question
3. Select a table
4. Click the join data button
5. Select the table you want to join
6. Select the columns being joined
7. Click Save
8. See "Saving Failed" and the error log from the console above.

**Expected behavior**
I expect it to save.

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
- This occurs on Chrome and Firefox, Windows 10, both latest.
- This is a Amazon Datawarehouse, I believe using mysql or something compatable with mysql.
- Metabase 0.33.4
I am not the admin on this instance but I will ask our provider to jump in. 

**Severity**
This is blocking all usability of the Custom Question involving a JOIN. 

Thanks for any assistance and if there's anything I can do to help, please let me know.

**Comment by flamber** [comment] 2019-10-17 01:20
Hi @alpha1 
I have a feeling that you might be using MySQL for the application database (metadata), but without access to the logs, it's difficult to know, since the error you have posted is only the frontend, which doesn't give a lot of information in this case.
It is important to use `utf8mb4` as charset/collation for all tables/columns of the metadata, when using MySQL.
It would also help to know which version of MySQL being used for metadata.
You can find some information in :gear: > Admin > Troubleshooting > Diagnostic Info and Logs.

**Comment by alpha1** [comment] 2019-10-17 01:38
Thanks @flamber I'm not an admin, but I've asked our instance admin to jump on here and post that info. I will try to setup my own instance and duplicate - so good to know you think its a mysqlDB.

**Comment by flamber** [comment] 2019-10-17 01:53
@alpha1 It's going to be close to impossible for you to reproduce this on your own instance, if you don't know all the technical details of the current instance. It might be better to wait for the admin to provide more info either here or directly to you.

But if MySQL+`utf8mb4` is used already - or if you're using another metadata database - then the issue could be a WAF (web application firewall) is causing the problems. There has been a few problems with Cloudflare and similar reverse-proxy services being a little too aggressive. And the errors produced are all over the place, so it has been difficult to debug those too.

**Comment by damusix** [comment] 2019-10-17 23:00
I am having a similar issue. it seems to happen when you add a lot of joins. Apparently the `copy` function inside of some object is getting passed `undefined`, so it tries to JSON parse and stringify undefined.

<img width="1477" alt="Screen Shot 2019-10-17 at 6 17 07 PM" src="https://user-images.githubusercontent.com/4218587/67053780-6226ee00-f110-11e9-975e-e8cc9a53f751.png">
<img width="1247" alt="Screen Shot 2019-10-17 at 6 16 54 PM" src="https://user-images.githubusercontent.com/4218587/67053782-6226ee00-f110-11e9-8835-aa4d42c52688.png">

**Comment by damusix** [comment] 2019-10-17 23:01
I think after like the 3rd join, you can no longer save the query

**Comment by damusix** [comment] 2019-10-17 23:03
This is minified, but maybe you can extract where in the code it happen using this:
```js
    var w = {
        generatePassword: function(e) {
            e = e || h.default.passwordComplexityRequirements() || {};
            for (var t, n, r, a, i, o = Math.max(e.total || 0, 14), l = "", u = 0; void 0,
            void 0,
            void 0,
            void 0,
            n = (t = l).match(/([A-Z])/g),
            r = t.match(/([a-z])/g),
            a = t.match(/([\d])/g),
            i = t.match(/([!@#\$%\^\&*\)\(+=._-{}])/g),
            !(n && n.length >= (e.upper || 0) && r && r.length >= (e.lower || 0) && a && a.length >= (e.digit || 0) && i && i.length >= (e.special || 0)) && u < 100; )
                l = (0,
                p.default)(o, !1, /[\w\d\?\-]/),
                u++;
            return l
        },
        isEmpty: function(e) {
            return null != e && (e = String(e)),
            null == e || 0 === e.length || null != e.match(/^\s+$/)
        },
        numberToWord: function(e) {
            var t = [(0,
            m.t)(r), (0,
            m.t)(a), (0,
            m.t)(i), (0,
            m.t)(o), (0,
            m.t)(l), (0,
            m.t)(u), (0,
            m.t)(s), (0,
            m.t)(c), (0,
            m.t)(d), (0,
            m.t)(f)];
            return e >= 0 && e <= 9 ? t[e] : "" + e
        },
        uuid: function() {
            return E() + E() + "-" + E() + "-" + E() + "-" + E() + "-" + E() + E() + E()
        },
        isUUID: function(e) {
            return "string" == typeof e && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(e)
        },
        isBase64: function(e) {
            return "string" == typeof e && /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(e)
        },
        isJWT: function(e) {
            return "string" == typeof e && /^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/.test(e)
        },
        validEmail: function(e) {
            return /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(e)
        },
        equals: function(e, t) {
            return y.default.isEqual(e, t)
        },
        propertiesEqual: function(e, t) {
            var n = arguments.length > 2 && void 0 !== arguments[2] ? arguments[2] : [].concat(b(Object.keys(e)), b(Object.keys(t)))
              , r = !0
              , a = !1
              , i = void 0;
            try {
                for (var o, l = n[Symbol.iterator](); !(r = (o = l.next()).done); r = !0) {
                    var u = o.value;
                    if (e[u] !== t[u])
                        return !1
                }
            } catch (e) {
                a = !0,
                i = e
            } finally {
                try {
                    !r && l.return && l.return()
                } finally {
                    if (a)
                        throw i
                }
            }
            return !0
        },

        // IT HAPPENS HERE
        copy: function(e) {
            return JSON.parse(JSON.stringify(e))
        },
        compareVersions: function(e, t) {
            for (var n = {
                snapshot: -4,
                alpha: -3,
                beta: -2,
                rc: -1
            }, r = function(e) {
                return e.toLowerCase().replace(/^v/, "").split(/[.-]*([0-9]+)[.-]*/).filter(function(e) {
                    return e
                }).map(function(e) {
                    return n[e] || parseInt(e, 10)
                })
            }, a = r(e), i = r(t), o = 0; o < Math.max(a.length, i.length); o++) {
                var l = a[o]
                  , u = i[o];
                if (null == u || l < u)
                    return -1;
                if (null == l || u < l)
                    return 1
            }
            return 0
        }
    };
```

**Comment by flamber** [comment] 2019-10-17 23:16
@damusix Since you're seeing different errors and seems to only be a problem after 3rd join, then I think you might be seeing a different issue. Could you create a new issue and fill in the details too?
Just for good measures, since it's not possible to search images, your error messages:
`Unexpected token u in JSON at position 0` and `Cannot read property 'type' of undefined`

**Comment by damusix** [comment] 2019-10-18 02:54
@flamber no it's the same issue. His error is likely different because he's using another browser. I just tried in Safari and my error is different, but it's the same thing: Attempting to `JSON.parse(JSON.stringify(undefined))`.

<img width="985" alt="Screen Shot 2019-10-17 at 10 53 16 PM" src="https://user-images.githubusercontent.com/4218587/67062355-10429000-f131-11e9-99a1-392fe155bcd5.png">

**Comment by damusix** [comment] 2019-10-18 02:55
I just attempted to save queries with only 1 join and it gives me the same issue.

**Comment by damusix** [comment] 2019-10-18 02:57
Also, spoke with a friend who runs metabase for his apps. He is on version 0.28 and doesn't get this issue.

**Comment by damusix** [comment] 2019-10-18 03:00
Also, to specify, I am running these on a mysql DB, if that matters.

First browser screenshots was latest chrome, second is latest safari.

Here's the troubleshooting JSON dump:
```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.4+11",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.4",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.4+11",
    "os.name": "Linux",
    "os.version": "4.14.138-114.102.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "date": "2019-10-07",
      "tag": "v0.33.4",
      "branch": "release-0.33.x",
      "hash": "9559406"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2019-10-18 03:03
@damusix But you're using Cloudfront. Try disabling that. Most advanced web applications does not work with the aggressive WAF/CDN that such services provide.

**Comment by flamber** [comment] 2019-10-18 03:18
@damusix Could you provide the logs for the request errors shown in the console? Admin > Troubleshooting > Logs.
And again, just to have text that is searchable:
`SyntaxError: JSON Parse error: Unexpected identifier "undefined"`
`TypeError: undefined is not an object (evaluating 'e.type')`

**Comment by damusix** [comment] 2019-10-22 21:42
@flamber nope no cloudfront. Also, there is nothing relevant in `Admin > Troubleshooting > Logs` because it never makes an AJAX request, therefore the server can never log anything. This issue is 100% on the frontend.

I think you have to look into whatever is using the `w.copy(e)` coming from wherever custom queries are being saved.

**Comment by flamber** [comment] 2019-10-22 21:47
@damusix On the image you posted on https://github.com/metabase/metabase/issues/11160#issuecomment-543465331, there's a `403` request to Cloudfront. And there's also a couple of `401` request errors, which are server-side errors too.
I'm not saying that this isn't a frontend problem, but since no-one has been able to reproduce this problem, then it's really difficult to fix.

**Comment by damusix** [comment] 2019-10-23 22:18
@flamber oooh yeah just caught some network data, my bad. The 401 and 403 were only ever seen on safari and may have been from previously browsing other parts of the site. Logs never clear since UI is a SPA.

```
Request URL: https://mymetabase.com/api/card
Request Method: POST
Status Code: 200 
```

Request Payload:
```js
{
  "name": "Area Regions",
  "dataset_query": {
    "database": 2,
    "type": "query",
    "query": {
      "source-table": 5,
      "joins": [
        {
          "fields": "all",
          "source-table": 11,
          "condition": [
            "=",
            [
              "field-id",
              38
            ],
            [
              "joined-field",
              "Region",
              [
                "field-id",
                67
              ]
            ]
          ],
          "alias": "Region"
        }
      ]
    }
  },
  "display": "table",
  "description": "ats",
  "visualization_settings": {},
  "collection_id": null,
  "result_metadata": null,
  "metadata_checksum": null
}
```

Request Response:
```js
{
  "message": "(conn=274003) Incorrect string value: '\\xE2\\x86\\x92 ID...' for column 'result_metadata' at row 1",
  "type": "class java.sql.SQLDataException",
  "stacktrace": [
    "org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:225)",
    "org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)",
    "org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)",
    "org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:232)",
    "org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)",
    "org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:194)",
    "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:462)",
    "clojure.java.jdbc$db_do_execute_prepared_return_keys$exec_and_return_keys__14686.invoke(jdbc.clj:961)",
    "clojure.java.jdbc$db_do_execute_prepared_return_keys.invokeStatic(jdbc.clj:989)",
    "clojure.java.jdbc$db_do_execute_prepared_return_keys.invoke(jdbc.clj:945)",
    "clojure.java.jdbc$db_do_prepared_return_keys.invokeStatic(jdbc.clj:1020)",
    "clojure.java.jdbc$db_do_prepared_return_keys.invoke(jdbc.clj:997)",
    "toucan.db$simple_insert_many_BANG_$iter__17743__17747$fn__17748$fn__17749.invoke(db.clj:560)",
    "toucan.db$simple_insert_many_BANG_$iter__17743__17747$fn__17748.invoke(db.clj:558)",
    "clojure.lang.LazySeq.sval(LazySeq.java:42)",
    "clojure.lang.LazySeq.seq(LazySeq.java:51)",
    "clojure.lang.RT.seq(RT.java:535)",
    "clojure.core$seq__5402.invokeStatic(core.clj:137)",
    "clojure.core$dorun.invokeStatic(core.clj:3133)",
    "clojure.core$doall.invokeStatic(core.clj:3148)",
    "clojure.core$doall.invoke(core.clj:3148)",
    "toucan.db$simple_insert_many_BANG_.invokeStatic(db.clj:557)",
    "toucan.db$simple_insert_many_BANG_.invoke(db.clj:543)",
    "toucan.db$simple_insert_BANG_.invokeStatic(db.clj:590)",
    "toucan.db$simple_insert_BANG_.invoke(db.clj:579)",
    "toucan.db$insert_BANG_.invokeStatic(db.clj:607)",
    "toucan.db$insert_BANG_.invoke(db.clj:594)",
    "--> api.card$save_new_card_async_BANG_$fn__60472$fn__60473.invoke(card.clj:212)",
    "api.card$save_new_card_async_BANG_$fn__60472.invoke(card.clj:208)",
    "async.util$fn__20641$do_on_separate_thread_STAR___20646$fn__20647$fn__20648.invoke(util.clj:71)"
  ],
  "sql-exception-chain": [
    "SQLDataException:",
    "Message: (conn=274003) Incorrect string value: '\\xE2\\x86\\x92 ID...' for column 'result_metadata' at row 1",
    "SQLState: 22007",
    "Error Code: 1366"
  ]
}
```


Metabase `/admin/troubleshooting/logs`:
```
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:00:00-04:00 INFO metabase.sync.util FINISHED: step 'classify-tables' for mysql Database 2 'MYDATABASE' (19.4 ms)
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:00:00-04:00 INFO metabase.sync.util FINISHED: Analyze data for mysql Database 2 'MYDATABASE' (127.8 ms)
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:01:32-04:00 DEBUG metabase.middleware.log GET /api/session/properties 200 2.8 ms (1 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (107 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:01:32-04:00 DEBUG metabase.middleware.log GET /api/user/current 200 9.8 ms (3 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (108 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:01:32-04:00 DEBUG metabase.middleware.log GET /api/user/current 200 9.1 ms (3 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (108 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:01:32-04:00 DEBUG metabase.middleware.log GET /api/database 200 4.7 ms (4 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (108 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:01:32-04:00 DEBUG metabase.middleware.log GET /api/collection/root/items 200 6.5 ms (7 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (108 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:01:32-04:00 DEBUG metabase.middleware.log GET /api/setting 200 973.1 µs (0 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (108 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:01:32-04:00 DEBUG metabase.middleware.log GET /api/collection/root 200 5.1 ms (2 DB calls) Jetty threads: 9/50 (0 idle, 1 queued) (112 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:01:32-04:00 DEBUG metabase.middleware.log GET /api/database 200 4.1 ms (3 DB calls) Jetty threads: 3/50 (5 idle, 0 queued) (113 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:01:33-04:00 DEBUG metabase.middleware.log GET /api/automagic-dashboards/database/3/candidates 200 157.0 ms (6 DB calls) Jetty threads: 3/50 (5 idle, 0 queued) (113 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:01:35-04:00 DEBUG metabase.middleware.log GET /api/database 200 90.2 ms (7 DB calls) Jetty threads: 3/50 (5 idle, 0 queued) (113 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:01:43-04:00 DEBUG metabase.middleware.log GET /api/table/22/query_metadata 200 12.8 ms (9 DB calls) Jetty threads: 3/50 (5 idle, 0 queued) (113 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:01:43-04:00 DEBUG metabase.middleware.log GET /api/table/22/fks 200 5.4 ms (5 DB calls) Jetty threads: 3/50 (5 idle, 0 queued) (113 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:01:48-04:00 DEBUG metabase.middleware.log GET /api/table/14/query_metadata 200 9.5 ms (9 DB calls) Jetty threads: 3/50 (5 idle, 0 queued) (113 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:01:54-04:00 INFO metabase.api.card Card results metadata passed in to API is MISSING. Running query to fetch correct metadata.
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:01:55-04:00 DEBUG metabase.async.util Running metabase.api.card$save_new_card_async_BANG_$fn__60472@72f38a31 on separate thread...
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:01:55-04:00 ERROR metabase.async.util Caught error running metabase.api.card$save_new_card_async_BANG_$fn__60472@72f38a31
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:01:55-04:00 DEBUG metabase.middleware.log POST /api/card 200 [ASYNC: completed] 559.2 ms (58 DB calls) Jetty threads: 2/50 (6 idle, 0 queued) (113 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:04-04:00 INFO metabase.api.card Card results metadata passed in to API is MISSING. Running query to fetch correct metadata.
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:04-04:00 DEBUG metabase.async.util Running metabase.api.card$save_new_card_async_BANG_$fn__60472@3c2864f on separate thread...
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:04-04:00 ERROR metabase.async.util Caught error running metabase.api.card$save_new_card_async_BANG_$fn__60472@3c2864f
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:04-04:00 DEBUG metabase.middleware.log POST /api/card 200 [ASYNC: completed] 460.3 ms (58 DB calls) Jetty threads: 2/50 (6 idle, 0 queued) (113 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:10-04:00 INFO metabase.api.card Card results metadata passed in to API is MISSING. Running query to fetch correct metadata.
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:10-04:00 DEBUG metabase.async.util Running metabase.api.card$save_new_card_async_BANG_$fn__60472@24de1438 on separate thread...
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:11-04:00 ERROR metabase.async.util Caught error running metabase.api.card$save_new_card_async_BANG_$fn__60472@24de1438
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:11-04:00 DEBUG metabase.middleware.log POST /api/card 200 [ASYNC: completed] 269.3 ms (58 DB calls) Jetty threads: 2/50 (6 idle, 0 queued) (113 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:15-04:00 INFO metabase.api.card Card results metadata passed in to API is MISSING. Running query to fetch correct metadata.
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:16-04:00 DEBUG metabase.async.util Running metabase.api.card$save_new_card_async_BANG_$fn__60472@3e172050 on separate thread...
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:16-04:00 ERROR metabase.async.util Caught error running metabase.api.card$save_new_card_async_BANG_$fn__60472@3e172050
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:16-04:00 DEBUG metabase.middleware.log POST /api/card 200 [ASYNC: completed] 237.8 ms (58 DB calls) Jetty threads: 2/50 (6 idle, 0 queued) (113 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:31-04:00 DEBUG metabase.middleware.log GET /api/table/5/query_metadata 200 10.9 ms (11 DB calls) Jetty threads: 3/50 (5 idle, 0 queued) (113 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:31-04:00 DEBUG metabase.middleware.log GET /api/table/5/fks 200 4.8 ms (5 DB calls) Jetty threads: 3/50 (5 idle, 0 queued) (113 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:31-04:00 DEBUG metabase.middleware.log GET /api/table/12/query_metadata 200 11.3 ms (10 DB calls) Jetty threads: 3/50 (5 idle, 0 queued) (113 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:31-04:00 DEBUG metabase.middleware.log GET /api/table/11/query_metadata 200 7.9 ms (8 DB calls) Jetty threads: 3/50 (5 idle, 0 queued) (113 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:48-04:00 INFO metabase.api.card Card results metadata passed in to API is MISSING. Running query to fetch correct metadata.
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:48-04:00 DEBUG metabase.async.util Running metabase.api.card$save_new_card_async_BANG_$fn__60472@3b1e0cf0 on separate thread...
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:48-04:00 ERROR metabase.async.util Caught error running metabase.api.card$save_new_card_async_BANG_$fn__60472@3b1e0cf0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:48-04:00 DEBUG metabase.middleware.log POST /api/card 200 [ASYNC: completed] 418.6 ms (58 DB calls) Jetty threads: 2/50 (5 idle, 0 queued) (108 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:55-04:00 DEBUG metabase.middleware.log GET /api/user/current 200 7.9 ms (3 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (108 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:55-04:00 DEBUG metabase.middleware.log GET /api/session/properties 200 9.6 ms (1 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (108 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:55-04:00 DEBUG metabase.middleware.log GET /api/database 200 3.9 ms (3 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (108 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:55-04:00 DEBUG metabase.middleware.log GET /api/session/properties 200 2.0 ms (1 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (108 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:55-04:00 DEBUG metabase.middleware.log GET /api/setting 200 580.1 µs (0 DB calls) Jetty threads: 4/50 (4 idle, 1 queued) (108 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:55-04:00 DEBUG metabase.middleware.log GET /api/setting 200 821.4 µs (0 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (108 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:55-04:00 DEBUG metabase.middleware.log GET /api/setup/admin_checklist 200 10.6 ms (11 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (110 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:58-04:00 DEBUG metabase.middleware.log GET /api/util/bug_report_details 200 2.2 ms (1 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (110 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:02:59-04:00 DEBUG metabase.middleware.log GET /api/task/info 200 2.4 ms (0 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (110 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:03:37-04:00 DEBUG metabase.middleware.log GET /api/session/properties 200 2.7 ms (1 DB calls) Jetty threads: 4/50 (5 idle, 0 queued) (112 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:03:37-04:00 DEBUG metabase.middleware.log GET /api/user/current 200 2.9 ms (3 DB calls) Jetty threads: 4/50 (5 idle, 0 queued) (112 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:03:37-04:00 DEBUG metabase.middleware.log GET /api/database 200 3.6 ms (3 DB calls) Jetty threads: 3/50 (6 idle, 0 queued) (112 total active threads) Queries in flight: 0
[1cc1de5e-eb83-4f12-8bab-66780dd02f40] 2019-10-23T18:03:37-04:00 DEBUG metabase.middleware.log GET /api/setting 200 649.3 µs (0 DB calls) Jetty threads: 3/50 (6 idle, 0 queued) (112 total active threads) Queries in flight: 0
```

**Comment by damusix** [comment] 2019-10-23 22:22
If it helps:
- We are running metabase in an ECS docker container
- Metabase is using MariaDB as persistent storage
- We are hooking into other DBs within same server as Metabase DB
- MariaDB version 10.3.8 on AWS RDS
- There is no cloudfront, only an ALB with rules to proxy Metabase container based on DNS.

**Comment by flamber** [comment] 2019-10-23 22:29
@damusix 
Make sure you're using `utf8mb4` on all charset/collation in the MariaDB Metabase database.
Almost guaranteed that's your problem. Check #10691 for more details on how to check.

**Comment by rylonian** [comment] 2019-11-06 17:45
This seemed to be an issue for me as well.  I noticed that any question that linked to another table via a foreign key set in the data model would not save.  As long as it was a simple question only dealing with one table, the question could be saved.

Thanks to flamber's suggestion of using utf8mb4 for the database (MySQL) we were able to save questions linking to other tables.

**Comment by alejandrorial** [comment] 2019-11-26 16:10
Really necessary to fix it asap! Metabase is used to provide data to the company and is not possible to save any question :(

**Comment by flamber** [comment] 2019-11-26 16:33
@alejandrorial 
It would be great if you provided more information, like I asked in the [forum](https://discourse.metabase.com/t/unable-to-save-questions/8134/2).
- Which version of Postgres?
- Please post Diagnostic Info. Admin > Troubleshooting
- Please provide logs, when save fails. Admin > Troubleshooting > Logs
- Are you using a CDN or WAF on your domain, like Cloudflare, Cloudfront or another proxy?

**Comment by alejandrorial** [comment] 2019-11-28 09:48
Connection installed (DWH):  PostgreSQL 9.6.11 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9), 64-bit
MySQL (Metabase metadata): 5.7.12

We have change the encoding of the Metabase metadata in MySQL and it has improve, we can save more questions (that why I could not answer early) but we are still having problems.

### Admin > Troubleshooting > Logs
**[11c5e64e-ce59-48f8-850a-4c16f243f3f5] 2019-11-28T10:44:20+01:00 DEBUG metabase.middleware.log POST /api/card 400 3.3 ms (0 DB calls)
{:errors {:result_metadata "el valor puede ser nulo, o si no es nulo, value must be an array of valid results column metadata maps."}}**

**Comment by flamber** [comment] 2019-11-28 17:11
@alejandrorial Okay, so now you're seeing a different problem.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

@mazameli Please close this. I think it's been covered enough times that the problem is using MySQL/MariaDB without `utf8mb4`. For more details about how to check and convert, see #10691.

**Comment by alejandrorial** [comment] 2019-11-28 18:02
I have checked it and that's another error, thanks a lot!

**Comment by mazameli** [comment] 2019-12-18 23:47
Closing this. For details on the MySQL/MariaDB utf8mb4 topic, see https://github.com/metabase/metabase/issues/10691

**Closed by mazameli** 2019-12-18 23:47 UTC
Labels: .Needs Triage, Type:Bug
