### ISSUE TITLE
Document MBQL expanded/resolved forms

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2520] opened 2016-05-03 18:41 UTC
There is a significant difference between the documented MBQL forms https://github.com/metabase/metabase/wiki/Query-Language-'98 and the structure of queries that are used to write database drivers.  We should have some documentation around this to make it clear for developers what the interface is meant to look like.

**Comment by camsaul** [comment] 2016-05-03 18:48
Duplicate of #2457

**Closed by camsaul** 2016-05-03 18:48 UTC
Labels: Documentation, Duplicate
