### ISSUE TITLE
In Settings > Email, “Save changes” button doesn’t enable until onBlur event

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14748] opened 2021-02-10 20:01 UTC
UX Issue (not a regression): In Settings > Email, “Save changes” button doesn’t enable until `onBlur` event… I sat around confused for a minute or so wondering why I couldn’t save my email settings. This might be an issue with admin forms in general. Consider changing the checks for button enabling to the `onChange` event?

**Comment by flamber** [comment] 2021-02-10 20:41
Duplicate of #12692

**Closed by flamber** 2021-02-10 20:41 UTC
Labels: .Frontend, Admin Panel & Setup, Priority:P3, Type:UX
