### ISSUE TITLE
add features to display long text like code blocks or logs queried from database.

### ISSUE THREAD

**Issue by horusli** [metabase/metabase#33907] opened 2023-09-15 14:27 UTC
**Is your feature request related to a problem? Please describe.**
In our analysis work, we need to refer to detailed analysis logs or code block, It would be great if metabase support embedding query result into dashboard, with scrollable tooltips and configurable font size. even great if we could have keyword highlight feature.

**Describe the solution you'd like**
Much the same way as number figure, but with small font size(better configuration font size) and scrollable tooltips to display the full log(code)

**Describe alternatives you've considered**
allow text block to use database query result as input. and enable keyword highlight feature.

**How important is this feature to you?**
very import for us to find the direct cause of some issue.

**Comment by paoliniluis** [comment] 2023-10-20 00:30
I think this is a duplicate of many current issues like custom css, query results in text cards and such

**Closed by paoliniluis** 2023-10-20 00:30 UTC
Labels: Type:New Feature, .Needs Triage
