### ISSUE TITLE
Empty and not empty mixed in filter

### ISSUE THREAD

**Issue by Afusette** [metabase/metabase#25283] opened 2022-09-07 14:17 UTC
**Describe the bug**
Filter "empty" returns "not empty" and "not empty" returns empty

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to "question"
2. Click on "filters"
3. Choose "deleted at" 
4. Choose exclude
5. Select "is empty" or "empty" 
6. See error

**Expected behavior**
Empty filter should return empty 

**Screenshots*
![Capture d’écran 2022-09-07 à 15 47 13](https://user-images.githubusercontent.com/20115980/188900753-c7128b01-c1fd-4736-8c2c-2fdbfc0cb2f9.png)
*

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Chrome
- Your operating system: (e.g., OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.g, MySQL, Postgres, MongoDB, …)
- Vous êtes en version v0.44.2
- Metabase hosting environment: (e.g., Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.g., H2 (default), Postgres or MySQL)

**Severity**
Annoying as I kept clicking and understood after it was certainly a bug. But I can live with that. 
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**
English is not my first language. PLUS I'm not a tech at all. I hope the issue is clear tho !

**Comment by flamber** [comment] 2022-09-07 14:49
Duplicate of #24806

**Closed by flamber** 2022-09-07 14:49 UTC
Labels: Type:Bug, .Needs Triage
