### ISSUE TITLE
After adding a database we should provide a "next step" (review metadata, ask a question)

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2831] opened 2016-06-24 18:52 UTC
Basically 100% of the time I add a new database I want to go straight to the query builder to try it out, which currently takes about 4 clicks. It would be nice if there were a direct link. The caveat is the database may not be synced immediately, but we should also surface the sync status (#649)

Alternatively we could suggest the admin review/edit the database metadata.

**Comment by mazameli** [comment] 2016-06-24 18:54
To yes-and this: I think having a link or button to `Ask a question about this data` from the Admin Panel when viewing a database or table makes a lot of sense. Would make even more sense if the Admin Panel and the rest of the product weren't in separate spaces, IMHO, but that's another issue for another time.

**Comment by camsaul** [comment] 2016-06-24 18:55
Duplicate of #2558

**Closed by camsaul** 2016-06-24 18:55 UTC
Labels: Proposal, UX

**Comment by mazameli** [comment] 2016-06-24 18:56
Wow, yeah, I literally wrote almost the exact same comment on #2558 two months ago. derp

**Comment by tlrobinson** [comment] 2016-06-24 18:58
Doh. Why can't Github Issue search read my mind?
