### ISSUE TITLE
Column names duplicate when foreign relation is the same table, for 2 different fields on base table

### ISSUE THREAD

**Issue by ok200paul** [metabase/metabase#33945] opened 2023-09-18 23:04 UTC
### Describe the bug

I have 2 tables: 

**voucher_sets**
- id
- created_by_team_id
- assigned_to_team_id
- ..etc

**teams**
- id
- name
- ..etc

If I load a question with voucher sets, and configure the teams to be connected to it (twice, using different source fields), the UI shows this:

![image](https://github.com/metabase/metabase/assets/22406523/7f9de2f1-e418-4d7b-b664-91a367a9e077)

When I change the names of ONE team name field to (say) "Agency Team", I get the following:
![image](https://github.com/metabase/metabase/assets/22406523/bd5b09ad-d007-4aa1-8d57-ad1f5206518f)

Then, if I change the name of the other (or, any) team name field to something, they all change:
![image](https://github.com/metabase/metabase/assets/22406523/93d6966b-5e33-40b2-9953-9b8055cccfd8)

We need the field to be allowed to be appropriately named.
 

### To Reproduce

1. Create a new question source table must have 2+ fields (A,B) pointing to IDs on another table (X) with 
2. Join the data from field A to table X based on table1.A = X.id - select (say) a field like "name" to place into visualisation
3. Join the data from field B to table X based on table1.A = X.id - select (say) a field like "name" to place into visualisation
4. In the visualisation, 2 fields data will point to the same data on the foreign table (all good)
5. Try to rename the column for either field in the visualisation
6. Both names update

### Expected behavior

The column names should be able to be individually named

### Information about your Metabase installation

```JSON
- Chrome Version 117.0.5938.88 (Official Build) (arm64)
- Mac OS Ventura Version 13.5.2 (22G91)
- Databases: MySQL
- Metabase: Cloud
```

### Severity

Low

**Comment by calherries** [comment] 2023-09-19 06:10
What version of Metabase are you using? If you can, go to Admin Settings > Troubleshooting > Diagnostic info and paste the JSON in the "Information about your Metabase installation" section of the description.

**Comment by calherries** [comment] 2023-09-19 06:19
This was fixed in the 47 release. Can you upgrade? Duplicate of https://github.com/metabase/metabase/issues/12685

**Closed** 2023-09-19 06:23 UTC
Labels: Type:Bug, .Needs Triage

**Comment by ok200paul** [comment] 2023-09-19 06:38
Ah - amazing. Thank you so much Cal!
