### ISSUE TITLE
Regression in exports returns "502 Bad Gateway" in files

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#29839] opened 2023-04-05 16:44 UTC
**Describe the bug**
We have the exact same problem as https://github.com/metabase/metabase/issues/29118 but it was reported in Redshift and Snowflake as well

**Logs**
No logs in the backend

**To Reproduce**
1) go to the activities table in our stats instance
2) make sure you have permission to download 1M rows
3) Download an excel file

you should get a beautiful 502 Bad Gateway file like this one
[query_result_2023-04-05T16_36_15.681Z.xlsx](https://github.com/metabase/metabase/files/11161183/query_result_2023-04-05T16_36_15.681Z.xlsx)

**Expected behavior**
File should have the contents

**Screenshots/videos**
NA

**Information about your Metabase Installation:**
- Your databases: Redshift, also reported to happen on Snowflake
- Metabase version: 46, but was reported in 45.3 as well
- Metabase hosting environment: master

**Severity**
P1

**Additional context**
NA

**Comment by dpsutton** [comment] 2023-04-11 22:22
I tried on stats against the activities table (question 3812 on stats). I got a sheet in 2.4 minutes, with 1048576 rows, and weighing in at 84 mb. I'll try again tomorrow and would appreciate any help you can give @paoliniluis

**Comment by paoliniluis** [comment] 2023-04-14 16:23
Just did a test:
v42
- table has 100K rows with massive amount of columns
![image](https://user-images.githubusercontent.com/1711649/232099311-9b7146d5-7bf2-4fa7-8d24-aee43acea9d1.png)

- export took 40 seconds
![image](https://user-images.githubusercontent.com/1711649/232099177-f883a5d0-f036-4480-afc4-5cc939914ad3.png)

then upgraded to 46
- same export from same table times out
![image](https://user-images.githubusercontent.com/1711649/232100062-16300b44-c1df-43ca-8d62-b3978f0ba2c0.png)
[query_result_2023-04-14T16_17_44.994Z.xlsx](https://github.com/metabase/metabase/files/11234940/query_result_2023-04-14T16_17_44.994Z.xlsx)

If I raise the timeout to see how much more it takes: 2.0 min, 300% more
![image](https://user-images.githubusercontent.com/1711649/232101062-3206d3a2-3a7d-4070-bfa0-7491014adc3f.png)

**Comment by paoliniluis** [comment] 2023-04-14 17:26
About my previous comment regarding cursors and fetching of those: please take into account that I run my postgres databases with "-c log_statement=all" when they start, so I know exactly what's going on when Metabase runs its queries.

Also, the type of export I did was XLSX, which we know it's not "streamable" due to the limitations of the library we use (docjure), so the order of the operations is the following:
![image](https://user-images.githubusercontent.com/1711649/232114918-07e43853-a958-4755-a8d0-7928abfc8c4d.png)

**Comment by dpsutton** [comment] 2023-04-14 23:32
So I've found one interesting thing. It seems that the java library we ultimately use to write spreadsheets has gotten slower.

On 0.42.1 we used
- docjure 1.16.0 (clojure wrapper)
- apache poi 5.0.0 (java lib that does the actual work) (we overrode the version to use 5.0.0)

For 0.46.1 we are now on
- docjure 1.19.0
- apache poi 5.2.3

And the following performance:

| version | time       |
|---------|------------|
| 0.46.1  | 29.57 sec  |
| 0.42.1  | 14.21  sec |

Profiling, in 0.46.1 we're spending a lot of time in `org.apache.poi.xssf.streaming.SheetDataWriter.writeCell`
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/6377293/232167540-9bed4f03-90da-4ed8-a4d7-959dca158362.png">

The file has changed location, but the diff from 5.0.0 -> 5.2.3 is
https://gist.github.com/dpsutton/453d627705638cc215234de0ef20b487

There is a [bug](https://bz.apache.org/bugzilla/show_bug.cgi?id=66532) and a PR https://github.com/apache/poi/pull/443 that improves the speed of this by 43%. I think we can just keep an eye out for a new release and get those changes when they are ready.

Diff from 5.2.3 to unreleased master is https://gist.github.com/dpsutton/cd10c516ebcb13cd45449a610b47e36a or https://github.com/apache/poi/pull/443/files

**Comment by qnkhuat** [comment] 2023-04-19 08:42
Follow up on Dan's theory, I created the towns table and exported with 3 different configurations:

```
- master with `apache poi 5.2.3` : ~20.8s
- master with `apache poi 5.0.0`:  ~16.5s
- 1.42.1:                          ~14.8s
```

**Comment by paoliniluis** [comment] 2023-04-28 13:32
changing tag as this is database agnostic

**Comment by tsmacdonald** [comment] 2023-06-20 10:33
The fixed version of Apache POI (presumably 5.2.4) still hasn't been released. In theory we could create a fork, but that seems high-effort for a bug like this.

**Comment by DamienOrain** [comment] 2023-08-14 06:25
Hello, 
I'm coming back to this bug that hasn't been fixed. Can you move forward on it?

**Comment by paoliniluis** [comment] 2023-10-11 13:32
The bump in the dep hasn´t fixed this issue

**Comment by markbastian** [comment] 2023-11-28 18:06
I'm trying to reproduce this with the following steps:

## On Stats

### Step 1 - Find a Redshift instance

I run the following native query against `Application Database (prod)`:

```
select D.name, T.name, D.dbms_version::json->>'flavor' AS db_flavor from metabase_table T
left join metabase_database D on D.id = T.db_id
where T.name = 'activity' and D.dbms_version::json->>'flavor' = 'Redshift'
```

### Step 2 - Find a large table

From the entries, I choose `Hosting Insights (prod)`

Next, I run a new native query against `Hosting Insights (prod)`:

```
select count(*) from activity
```

This produces 9,044,713, so we're in the realm of the right size to try to download.

### Step 3 - Download the data

Change the above query to `select * from activity` then attempt a download.

I was able to successfully download the file `query_result_2023-11-28T17_27_49.387386Z.xlsx` (Took 1.3 minutes) and open it in Numbers (I don't have Excel).

@paoliniluis -- Are you still having issues with these downloads?

**Comment by markbastian** [comment] 2023-11-28 18:42
I was able to reproduce it once (sample size of 7) and the remaining times it worked.

<img width="1776" alt="image" src="https://github.com/metabase/metabase/assets/8381441/b2cd9e55-c1e7-418c-a11a-7bc79214a56a">

**Comment by DamienOrain** [comment] 2023-12-04 16:42
Hi

To reproduce the problem, what you can do is have a report with established filters and then open this report with a user with restricted rights and then change a filter and download the report.

Sincerely,
[Company logo]<https://scribe.jenji.io/s2/cxzleaen>
Damien Orain
Email
***@***.******@***.***>
Connect with me on LinkedIn


De : Luis Paolini ***@***.***>
Date : jeudi, 30 novembre 2023 à 13:13
À : metabase/metabase ***@***.***>
Cc : DamienOrain ***@***.***>, Comment ***@***.***>
Objet : Re: [metabase/metabase] Regression in exports returns "502 Bad Gateway" in files (Issue #29839)

@markbastian<https://github.com/markbastian> i had the same experience, on one hit this failed but subsequent it worked, I believe this has to be due to caching in redshift but I might be wrong

**Comment by paoliniluis** [comment] 2023-12-15 22:12
Confirmed that customers are still seeing this :(

**Comment by markbastian** [comment] 2023-12-19 23:26
> To reproduce the problem, what you can do is have a report with established filters and then open this report with a user with restricted rights and then change a filter and download the report.

@paoliniluis -- Can you provide a more detailed set of steps for this? Here is what @adam-james-v and I are doing to try to reproduce this:
* As the default admin user in enterprise mode:
	* Create a dataset with a large number of records (> 1M)
	* Create a simple question that selects the dataset
	* Add that question to a new dashboard on save
	* Add a filter to the dashboard
* Log out and log back in as a test user (We used Lucky)
	* Ensure this user is in the restricted users' group
	* Block access to the data source for the query for that group
	* Navigate to the dashboard
	* The card is now locked and the option to download is no longer available

**Comment by markbastian** [comment] 2024-01-10 20:20
We've been using `activity` in Hosting Insights (prod). which has 13 columns. Another thing to try is a table with >1M rows and a very large number of columns as well.

@paoliniluis, you say:
>table has 100K rows with massive amount of columns

How many columns are we talking? I want to see if I can make a reasonable repro.

**Comment by paoliniluis** [comment] 2024-01-10 20:48
I just got an email from a customer with 25/30 columns @markbastian, that seems a reasonable number to test I believe

**Comment by perivamsi** [comment] 2024-07-14 00:36
@paoliniluis are you able to repro this still?

**Comment by paoliniluis** [comment] 2024-07-15 23:05
new tests:
db is 100K rows with 400 columns only booleans and numbers
45.4.3: 
23 secs pulling a csv (331MB file)
![image](https://github.com/user-attachments/assets/fa5c781d-89cb-44f9-9bf1-e85ae3381368)
2.1 min pulling a xlsx (270MB file) 
![image](https://github.com/user-attachments/assets/65a030b0-c773-42b4-b675-3f752d8df9d2)

v50.13
1.2 min for csv
![image](https://github.com/user-attachments/assets/00a4354b-fc83-41b8-a031-e66f4f998940)

xlsx times out

this got way worse now

**Comment by paoliniluis** [comment] 2024-07-15 23:19
v45 memory consumption
![image](https://github.com/user-attachments/assets/5d9c1031-2223-4cbe-8c5e-7e20621fd993)
![image](https://github.com/user-attachments/assets/7acff0ad-106a-4166-bce2-d294419bd4d8)

v45 cpu usage
![image](https://github.com/user-attachments/assets/bea093b8-71b0-4068-9784-8fbca6aee916)
![image](https://github.com/user-attachments/assets/aab5c579-43bc-42b7-8094-48ddd993684c)

v50 memory usage
![image](https://github.com/user-attachments/assets/5430d61b-3b63-4e3b-9962-8553b1043042)
![image](https://github.com/user-attachments/assets/2e3fa763-b9e5-4d3e-97dc-e220e18e455b)

v50 cpu time
![image](https://github.com/user-attachments/assets/2a4d4b9d-1329-4f74-a3ca-ebc67bcda063)
![image](https://github.com/user-attachments/assets/d9acce92-88a7-43bc-a053-76c9ee6b85ad)

**Comment by paoliniluis** [comment] 2024-07-17 16:42
@alexander-yakushev congrats, you made it go back to the 2.1 mins :)
![image](https://github.com/user-attachments/assets/e0f6b723-9001-4b50-9c9b-c7c5adb820ae)
![image](https://github.com/user-attachments/assets/3c1a4244-2c25-497e-af17-60c6838ee67e)

cpu is still using much of its time on GC though
![image](https://github.com/user-attachments/assets/5240479c-53d4-47be-a566-df28d704bdf2)
![image](https://github.com/user-attachments/assets/2c364087-5118-4c2b-881d-99c05f050e33)

I guess there are many other optimizations (mostly in the CPU side) we can do though, probably not for this time? @perivamsi

**Comment by paoliniluis** [comment] 2024-07-17 16:43
@alexander-yakushev I'm wondering why it's using libzip so much though...

**Comment by alexander-yakushev** [comment] 2024-07-17 16:56
I don't see any more easy wins. It can be improved another ~20%, I assume, by chipping away bit by bit, but the most of time is still spent doing POI stuff.

I assume that libzip is because XSLX is a zipped format.

**Comment by snoe** [comment] 2024-07-17 21:03
@paoliniluis Now that https://github.com/metabase/metabase/pull/45669 and https://github.com/metabase/metabase/pull/45667 are merged it would be worth looking at the profiler again.

**Comment by snoe** [comment] 2024-07-18 20:07
Spoke with @paoliniluis  and this is ok to close

**Closed by snoe** 2024-07-18 20:07 UTC
Labels: Type:Bug, Database/, Priority:P1, Reporting/Export, .Regression, .Team/QueryProcessor
