### ISSUE TITLE
Add support for imagesPullSecrets helm chart and kubernetes deployments

### ISSUE THREAD

**Issue by esteban1983cl** [metabase/metabase#13754] opened 2020-11-11 17:23 UTC
**Is your feature request related to a problem? Please describe.**
I need support for helm chart. I need pull images using credentials in k8s

**Describe the solution you'd like**
Please add field imagePullSecrets in helm chart templates and helm chart values file

**Describe alternatives you've considered**
N/A

**How important is this feature to you?**
Very important, because I have errors from docker hub, respect limits.
https://docs.docker.com/docker-hub/download-rate-limit/#how-do-i-authenticate-pull-requests 

**Additional context**
N/A

Thanks team for this support

**Comment by flamber** [comment] 2020-11-12 10:29
Duplicate of #13581

**Closed by flamber** 2020-11-12 10:29 UTC
Labels: .Needs Triage, Type:New Feature
