### ISSUE TITLE
Wrong results groupping by month (MongoDB database)

### ISSUE THREAD

**Issue by AndreLuizRego** [metabase/metabase#21430] opened 2022-04-01 19:15 UTC
Metabase is not groupping correctly when choosing to group by month using data from a MongoDB database.

**To Reproduce**
1. Choose any data source that has at least one date field

![Data](https://user-images.githubusercontent.com/56892990/161326078-d990f9bc-4601-49e8-af4d-23d0f01e371e.png)

2. Choose any sumarize operation
3. Choose a date field to "group by month"

![Question](https://user-images.githubusercontent.com/56892990/161326136-c85b9db7-7fc2-4dde-8161-1195eb07c452.png)

5. See that the results show the month date as it was of the previous month than originnaly were on the database

![Question_Results](https://user-images.githubusercontent.com/56892990/161326167-bdd60ed4-c71f-4257-99ad-64b0d3b9b4ff.png)

**Expected behavior**
The expected behavior would be dates to be unchanged and grouped correctly

**Information about your Metabase Installation:**
Metabase 0.42.2 
Using MongoDB and MySQL Databases

**Severity**
Incorrect results are shown which can lead to wrong actions and decisions. Results obtained from Metabase are under doubt by now.

**Comment by flamber** [comment] 2022-04-02 08:32
Hi @AndreLuizRego 
Post "Diagnostic Info" from Admin > Troubleshooting.
Timezones are complicated: https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html
Very likely a duplicate of #11149

**Comment by AndreLuizRego** [comment] 2022-04-02 10:24
> Hi @AndreLuizRego Post "Diagnostic Info" from Admin > Troubleshooting. Timezones are complicated: https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html Very likely a duplicate of #11149

Hi @flamber,

Here is the troubleshooting info:

{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.12+7",
    "java.vendor": "Eclipse Foundation",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.12",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.12+7",
    "os.name": "Linux",
    "os.version": "5.4.0-73-generic",
    "user.language": "en",
    "user.timezone": "America/Argentina/Buenos_Aires"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.28"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-28",
      "tag": "v0.42.2",
      "branch": "release-x.42.x",
      "hash": "d6ff494"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by flamber** [comment] 2022-04-02 10:28
@AndreLuizRego It is a duplicate of #11149 - see the comments for potential workaround.

**Closed by flamber** 2022-04-02 10:28 UTC
Labels: Type:Bug, .Needs Triage

**Comment by AndreLuizRego** [comment] 2022-04-04 11:14
> @AndreLuizRego It is a duplicate of #11149 - see the comments for potential workaround.

Hi @flamber,

You are right! Thanks for the information of the workaround!
