### ISSUE TITLE
Feature request: Saving screenshots of graphs directly from the interface

### ISSUE THREAD

**Issue by qerelt** [metabase/metabase#17724] opened 2021-09-02 05:36 UTC
**Is your feature request related to a problem? Please describe.**
I make lots of graphs for my team using MetaBase and we always take screenshots of them to use in business reports and analysis. After a while, it becomes a bit burdensome since the screenshot quality varies and the reports become inconsistent, visually.

**Describe the solution you'd like**
If there was an option to just push one button and get the screenshot of my graph saved to my device, it would have been awesome!

**Describe alternatives you've considered**
Using default screenshotting tools of my devices

**How important is this feature to you?**
It is important to me since I took around 100 screenshots a day on our instance of MetaBase.

**Additional context**
N/A

**Comment by flamber** [comment] 2021-09-02 07:04
Duplicate of #4701

**Closed by flamber** 2021-09-02 07:04 UTC
Labels: Type:New Feature, .Needs Triage
