### ISSUE TITLE
Turn off "Friendly table and field names"

### ISSUE THREAD

**Issue by matejkramny** [metabase/metabase#4409] opened 2017-02-20 10:15 UTC
I have a database which was configured during setup.

Later I discovered the friendly renaming of database fields isn't so helpful (to me). I wanted to turn this off, in the settings: "Friendly table and field names".

> Metabase can attempt to transform your table and field names into more sensible human readable versions, e.g. "somehorriblename" becomes "Some Horrible Name". This doesn’t work all that well if the names are in a language other than English, however. Do you want us to take a guess?

I turned it off, but it still shows me friendly field and table names.. Effectively changes nothing. I also triggered a re-scan of the database, but doesn't help.

**How can I get the original schema to display through metabase?**

- Your browser and the version: not relevant
- Your operating system: not relevant
- Your databases: MySQL
- Metabase version: v0.22.2
- Metabase hosting environment: docker
- Metabase internal database: Postgres

**Comment by salsakran** [comment] 2017-02-25 00:51
can you show examples of what is happening? That toggle should be resetting things.

**Comment by matejkramny** [comment] 2017-02-25 00:52
I might not be understanding what it does..

I basically want to disable any "friendly table names" such as `my__table_name` becoming "My Table Name", including columns..

**Comment by camsaul** [comment] 2017-02-25 01:00
Duplicate of #3948

**Closed by camsaul** 2017-02-25 01:00 UTC
Labels: Bug, Metadata/Sync
