### ISSUE TITLE
Weird Button position in the Edit menu

### ISSUE THREAD

**Issue by Varunram** [metabase/metabase#5167] opened 2017-05-22 18:17 UTC
### Operating System: macOS 10.12.5

After adding a graph to the dashboard, the `done`, `cancel` and `reset defaults` buttons overlap existing edit parameters such as "show goal" and "place missing values with". It would be amazing if they could be restructured to the bottom of the modal box (assuming the edit window is a modal box i.e.)

**Comment by mazameli** [comment] 2017-05-22 18:23
Hmm, is this the web app or Mac app? If it's the web app, what browser are you using, and which version of Metabase?

**Comment by Varunram** [comment] 2017-05-22 18:27
Hi @mazameli ! Its the Mac app. It must be latest release since I started experimenting only today. Thanks!

**Comment by mazameli** [comment] 2017-05-22 20:49
Ah, I see. This is happening any time there are enough input fields such that the left column in the modal _should_ scroll. It happens regardless of whether or not it's on a dashboard, too. And it's of course also happening in Safari because it's happening in the Mac app, but I confirmed it's not happening in Chrome.

On a dashboard:

![screen shot 2017-05-22 at 1 44 57 pm](https://cloud.githubusercontent.com/assets/2223916/26327766/65708dac-3ef5-11e7-942f-544fc6c4209c.png)

On a question detail page:

![screen shot 2017-05-22 at 1 45 52 pm](https://cloud.githubusercontent.com/assets/2223916/26327785/77c4de68-3ef5-11e7-9853-bc5239d1eecd.png)

**Comment by mbvictoria** [comment] 2019-06-19 19:58
Closing - no longer relevant in current design.

**Closed by mbvictoria** 2019-06-19 19:58 UTC
Labels: Browser/Safari, Bug
