### ISSUE TITLE
Export to .xlsx with Group By Day field fails

### ISSUE THREAD

**Issue by tomas-kucera** [metabase/metabase#13356] opened 2020-10-03 09:34 UTC
**Describe the bug**
If a date field is used in query as a simple GROUP BY day then the export to Excel fails.

**Logs**
Attached you can find an excerpt from the metabase logfile and the generated xlsx that contains errors as well.

**To Reproduce**
1. Create a simple question - I used table view with a few fields and Date field that I selected as Break By Day
2. Export the data to Excel
3. See the generated file (cannot open - contains error) and metabase logfiles

**Expected behavior**
Correctly generated xlsx file.

**Screenshots**
Not applicable.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: 85.0.4183.121 (Official Build) (64-bit)
- Your operating system: MacOS Catalina 10.15.7
- Your databases: Postgres
- Metabase version: 0.36.6
- Metabase hosting environment: Ubuntu 18.04 on Digital Ocean
- Metabase internal database: H2 (default)

**Severity**
I am using this feature quite regularly to provide raw data to customers. It is not P1 but makes things more complicated.

**Additional context**
It used to work up to release 0.36.5 without any issues.  

[query_result_2020-10-03T09_06_34.227Z.xlsx](https://github.com/metabase/metabase/files/5321363/query_result_2020-10-03T09_06_34.227Z.xlsx)
[metabase.log](https://github.com/metabase/metabase/files/5321364/metabase.log)

**Comment by flamber** [comment] 2020-10-03 09:37
Duplicate of #13298

**Closed by flamber** 2020-10-03 09:37 UTC
Labels: .Needs Triage, Type:Bug
