### ISSUE TITLE
Metabase drops a section of the query when duplicating

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#24126] opened 2022-07-19 22:32 UTC
**Describe the bug**
When you build a query that uses a custom column of a single field and then use a group by of that custom field and the same field, the duplication of the query wipes one of those

**Logs**
NA

**To Reproduce**
1) new question -> people -> custom column using email field (just email). Then group by the custom column and also the real emai field
2) save it
3) duplicate it
4) see one of the 2 groupings being deleted

**Expected behavior**
Nothing gets deleted on duplication

**Screenshots**
![image](https://user-images.githubusercontent.com/1711649/179859325-77eaedfe-2b8f-42dc-a47e-d045d4311ef8.png)

source question
![image](https://user-images.githubusercontent.com/1711649/179859396-7291f88e-20d4-4aa3-a644-126f2f3fba4c.png)

duplicate question
![image](https://user-images.githubusercontent.com/1711649/179859422-3ad5ffcd-17af-42ad-8526-e9afbe180453.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: pop 22.04
- Your databases: Postgres 14.4
- Metabase version: 1.43.4
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14.4

**Severity**
P2/P1'ish

**Additional context**
Reported by a customer

**Comment by flamber** [comment] 2022-07-23 10:41
Quite sure it's a duplicate of #17769 and probably very related to #4726.

Can be reproduced without duplicating question.
1. Question > Sample > Products
2. Add Custom Column `[Category]` as "Cat"
3. Summarize grouped by "Cat" and Category
4. Add another Custom Column after summarize section, `1+1`
![image](https://user-images.githubusercontent.com/1447303/180601508-bebecde7-8a92-4868-9c2a-14e6c724ede3.png)

Workaround is to change "Cat" to `concat([Category], "")` instead of plain field reference.
![image](https://user-images.githubusercontent.com/1447303/180601699-ce71b4ff-4a83-4624-8a5b-007c96bcdd27.png)

**Comment by npfitz** [comment] 2022-07-27 13:08
I spent some time reviewing this yesterday. @flamber This is actually a separate issue than what you described. In your case, it's getting dropped by the API, but In @paoliniluis's case, we end up dropping the column when we clean the query just before sending it to the API (specifically when we clean the breakouts). This is because we end up resolving the cat column to a field number, which gets seen twice and we drop one of them. With the more complicated expression, we don't resolve it to a field ID so we end up leaving it alone. I'm going to put up a proposed fix sometime today, but where this is such a specific issue it may not quite be a P1.

**Closed** 2022-08-05 20:33 UTC
Labels: Type:Bug, Priority:P2, .Frontend, Querying/GUI, Querying/Notebook/Custom Column
