### ISSUE TITLE
Enable non admin user to share Dashboards.

### ISSUE THREAD

**Issue by jonatasfreitasv** [metabase/metabase#6482] opened 2017-11-28 04:25 UTC
Have any way to make this permission ?

**Comment by mazameli** [comment] 2017-11-28 04:39
You mean you'd like for non-admins to be able to enable public links for a dashboard, or at least to have a permission setting to turn that behavior on/off?

**Comment by jonatasfreitasv** [comment] 2017-12-12 11:20
Yes @mazameli, exactly!

**Comment by socratec** [comment] 2018-01-11 18:36
Access to a dashboard should be granted to a group of users or individual user. Depending on the type of dashboard (financial, sales, production), different audience require the information.  I am surprised that this is not implemented in the product. Individual collections provide permissions to a group of users.

**Comment by flamber** [comment] 2019-02-18 03:50
Duplicate of #4333

**Closed** 2020-05-13 10:12 UTC
Labels: .Proposal, Administration/Permissions, Reporting/Dashboards
