### ISSUE TITLE
Variables pane not in SQL editor on `master`

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#20502] opened 2022-02-14 19:01 UTC
<img width="1905" alt="image" src="https://user-images.githubusercontent.com/1455846/153928438-5593bdd2-e797-471f-b891-2039ff9ca22e.png">

Steps to repro:

1. SQL Query > Sample Database
2. Paste `SELECT COUNT(*) FROM "PRODUCTS" WHERE {{cat}}` into the editor. Variables sidebar does not open
3. Do whatever you can to get the variables pane to pop up -- delete `{{cat}}` and type it back in manually, type in a new variable, etc.
4. Manually open variables pane. Does not detect the variable.

Another way to repro:

1. SQL Query > Sample Database
2. Type in `SELECT {{x}}`
3. Still doesn't open the Variables sidebar 
4. Still doesn't show `{{x}}` if you manually open it

**Comment by camsaul** [comment] 2022-02-14 19:02
I just see `StructuredQuery.ts:340 Warning: can't clean query without metadata!` hundreds of times in the browser logs

**Comment by camsaul** [comment] 2022-02-14 19:04
Ok I was finally able to get this working after refreshing the page a bunch of times. It's still a pretty annoying bug.

**Comment by flamber** [comment] 2022-02-14 19:05
Duplicate of #10927

**Closed by flamber** 2022-02-14 19:05 UTC
Labels: Type:Bug, .Frontend, Querying/GUI, .Needs Triage, .Regression
