### ISSUE TITLE
Trying to do a subsequent aggregation on a custom expression in the Notebook results in an error

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14649] opened 2021-02-04 00:56 UTC
On `master`. I've labeled this a P2, but could be talked into it being a P1.

- Start a new notebook query using Orders
- Summarize by a custom aggregation expression, like `Sum([Subtotal])` and name it anything, e.g. "Revenue"
- Break out by anything
- Try getting the average of your custom column (though any aggregation you choose demonstrates the bug)
- Hit Preview or Visualize
- You'll see this bug:

`Column "source.Revenue" not found; SQL statement: -- Metabase:: userID: 1 queryType: MBQL queryHash: 52fe7037875414b6d156c70a5c7e018c0f11b3f5f0e24beffb5f51873e1932b8 SELECT avg("source"."Revenue") AS "avg" FROM (SELECT parsedatetime(formatdatetime("PEOPLE__via__USER_ID"."CREATED_AT", 'yyyyMM'), 'yyyyMM') AS "PEOPLE__via__USER_ID__CREATED_AT", sum("PUBLIC"."ORDERS"."SUBTOTAL") AS "sum" FROM "PUBLIC"."ORDERS" LEFT JOIN "PUBLIC"."PEOPLE" "PEOPLE__via__USER_ID" ON "PUBLIC"."ORDERS"."USER_ID" = "PEOPLE__via__USER_ID"."ID" GROUP BY parsedatetime(formatdatetime("PEOPLE__via__USER_ID"."CREATED_AT", 'yyyyMM'), 'yyyyMM') ORDER BY parsedatetime(formatdatetime("PEOPLE__via__USER_ID"."CREATED_AT", 'yyyyMM'), 'yyyyMM') ASC) "source" [42122-197]`

![second-aggregation-bug](https://user-images.githubusercontent.com/2223916/106829230-96ddf200-6640-11eb-85a0-607b49bc2bbb.gif)

**Comment by flamber** [comment] 2021-02-04 10:18
Very likely a duplicate of #13857/#12839

**Comment by TeddyAfro** [comment] 2021-02-04 11:25
That issue exists now for a long time.

**Comment by nemanjaglumac** [comment] 2021-02-09 16:33
Not sure if it makes sense to write a repro for this since all 3 issues Flamber linked to are already reproduced.

**Comment by flamber** [comment] 2021-02-09 16:38
@nemanjaglumac When in Rome - it should only take you a couple of minutes :wink:

**Comment by flamber** [comment] 2021-06-01 14:34
Fixed by #16259

**Closed by flamber** 2021-06-01 14:34 UTC
Labels: .Reproduced, Priority:P2, Querying/Nested Queries, Querying/Notebook, Type:Bug
