### ISSUE TITLE
Drill through resets question filter value

### ISSUE THREAD

**Issue by enqueue** [metabase/metabase#15184] opened 2021-03-16 06:05 UTC
**Describe the bug**
When drilling through into the results ("View these Orders") of a question that has a filter set on the grouped field, this filter is reset.

**Logs**
n/a

**To Reproduce**
1. Create a new question based on sample dataset, table Orders
2. Filter by: Created At = Previous Year
3. Summarize: Count
4. By: Created At = Week of year
3. Visualize as bar chart (default)
4. Click on the bar for week 15 and perform action "View these Orders"

**Expected behavior**
Table showing all orders of week 15 in the previous year (125 rows)

**Actual behavior**
Table showing all orders of week 15 in _all_ years (427 rows)

**Screenshots**
Query definition:
![Screenshot_20210316_065250](https://user-images.githubusercontent.com/5407006/111262632-d971f180-8624-11eb-8391-0d13676486ec.png)

Resulting bar chart and action to perform:
![Screenshot_20210316_065408](https://user-images.githubusercontent.com/5407006/111262641-dd9e0f00-8624-11eb-89df-384b63ef4cc4.png)

Final result table:
![Screenshot_20210316_065527](https://user-images.githubusercontent.com/5407006/111262644-e0006900-8624-11eb-8301-23b7897f6235.png)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_282-b08",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "1.8.0_282",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.282-b08",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.15.2.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "clickhouse",
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.32-35-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.38.1",
      "date": "2021-03-03",
      "branch": "release-x.38.x",
      "hash": "79ef63a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Wrong results are returned, and this behavior is not always obvious to the user. The bug reduces our users' confidence in the quality of our Data Warehouse in general, and Metabase as a professional front-end in particular.

**Additional context**
n/a

**Comment by flamber** [comment] 2021-03-16 10:26
Duplicate of #10767

**Closed by flamber** 2021-03-16 10:26 UTC
Labels: .Needs Triage, Type:Bug
