### ISSUE TITLE
Disable datetime unit 

### ISSUE THREAD

**Issue by Crusader4Christ** [metabase/metabase#9282] opened 2019-01-17 10:01 UTC
Using mysql in metabase I try to see raw data in table with basic filters (created=today, status>0) when I first run this query I get right values, but if I refresh the page - all datetime columns become rounded by day. 

I propose DO NOT make any granularity by default at all. 

As it work in SQL: DateTime is date and time and date(DateTime) is rounded by day, so why metabase do this if I do not ask?

**Comment by flamber** [comment] 2019-02-25 04:29
Hi @Crusader4Christ 
I cannot reproduce your issue on 0.31.2 with MySQL 5.7, MariaDB 10.3 and Postgres 11.2
Which version of Metabase and MySQL?
Can you reproduce your issue on the sample database? If yes, how?
Can you provide the query being executed? Check your browser console, which will show the request under Network and inside that you can find the Response-tab, look for `data > native_form > query`.
![image](https://user-images.githubusercontent.com/1447303/53314322-62bdfc00-3883-11e9-9a44-227d6f3f75a6.png)

**Comment by Crusader4Christ** [comment] 2019-02-26 13:38
Metabase: You're on version v0.30.3 Built on 2018-09-13
MySQL: 5.7
SQL Query: 
first-time: 
```
SELECT `download`.`download_id` AS `download_id`,  `download`.`created` AS `created`,  `download`.`status` AS `status`
FROM `download` 
WHERE ((`download`.`status` > 0 AND date(`download`.`deletedAt`) IS NULL AND  date(`download`.`created`) = date(now())) 
ORDER BY `download`.`created` ASC 
LIMIT 2000
```
after refresh:
```
SELECT 
    `download`.`download_id` AS `download_id`,
    DATE(`download`.`created`) AS `created`,
    `download`.`status` AS `status`
FROM
    `download`
WHERE
    ((`download`.`status` > 0
        AND DATE(`download`.`deletedAt`) IS NULL
        AND DATE(`download`.`created`) = DATE(NOW())))
ORDER BY `download`.`created` ASC
LIMIT 2000
```

**Comment by Crusader4Christ** [comment] 2019-02-26 14:06
I see the "unit:day" in metadata of column created. But I didn`t set it and I can`t chenge it:
```
{
	"started_at": "2019-02-26T13:36:21.344Z",
	"json_query": {
		"database": 2,
		"type": "query",
		"query": {
			"source_table": 49,
			"filter": ["and", ["SEGMENT", 1],
				["time-interval", ["field-id", 241], "current", "day"]
			],
			"order_by": [
				[
					["field-id", 241], "ascending"
				]
			],
			"fields": [
				["field-id", 245],
				["field-id", 241],
				["field-id", 248]
			]
		},
		"parameters": [],
		"constraints": {
			"max-results": 10000,
			"max-results-bare-rows": 2000
		}
	},
	"average_execution_time": null,
	"status": "completed",
	"context": "ad-hoc",
	"row_count": 353,
	"running_time": 99,
	"data": {
		"rows": [...]
		"columns": ["download_id", "created", "status", "Status"],
		"native_form": {
			"query": "SELECT `download`.`download_id` AS `download_id`, date(`download`.`created`) AS `created`, `download`.`status` AS `status` FROM `download` WHERE ((`download`.`status` > 0 AND date(`download`.`deletedAt`) IS NULL AND NOT (lower(`download`.`email`) like ?) AND `download`.`brand_id` <> 152) AND date(`download`.`created`) = date(now())) ORDER BY `download`.`created` ASC LIMIT 2000",
			"params": ["%test%"]
		},
		"cols": [{
			"description": null,
			"table_id": 49,
			"schema_name": null,
			"special_type": "type/PK",
			"name": "download_id",
			"source": "fields",
			"remapped_from": null,
			"extra_info": {},
			"fk_field_id": null,
			"remapped_to": null,
			"id": 245,
			"visibility_type": "normal",
			"target": null,
			"display_name": "Download ID",
			"fingerprint": null,
			"base_type": "type/Integer"
		}, {
			"description": null,
			"table_id": 49,
			"schema_name": null,
			"special_type": "type/CreationTime",
			"unit": "day",
			"name": "created",
			"source": "fields",
			"remapped_from": null,
			"extra_info": {},
			"fk_field_id": null,
			"remapped_to": null,
			"id": 241,
			"visibility_type": "normal",
			"target": null,
			"display_name": "Created",
			"fingerprint": {
				"global": {
					"distinct-count": 95
				},
				"type": {
					"type/DateTime": {
						"earliest": "2018-06-19T21:00:00.000Z",
						"latest": "2018-09-25T21:00:00.000Z"
					}
				}
			},
			"base_type": "type/DateTime"
		}, {
			"description": null,
			"table_id": 49,
			"schema_name": null,
			"special_type": "type/Category",
			"name": "status",
			"source": "fields",
			"remapped_from": null,
			"extra_info": {},
			"fk_field_id": null,
			"remapped_to": "Status",
			"id": 248,
			"visibility_type": "normal",
			"target": null,
			"display_name": "Status",
			"fingerprint": {
				"global": {
					"distinct-count": 16
				},
				"type": {
					"type/Number": {
						"min": -20.0,
						"max": 401.0,
						"avg": 12.808195202306187
					}
				}
			},
			"base_type": "type/Integer"
		}, {
			"description": null,
			"table_id": null,
			"name": "Status",
			"expression-name": "Status",
			"source": "fields",
			"remapped_from": "status",
			"extra_info": {},
			"remapped_to": null,
			"id": null,
			"target": null,
			"display_name": "Status"
		}],
		"results_metadata": {
			"checksum": "br7ELkIxUPW831gN6efRBHIoXUt8XSvxLGRj1aU20gvKyzXwvG/M+9QjBMIo7ghC/RmAAfhgesyDmylYZXIBbtCl2CX4iuy38r5WKzdjNaA=",
			"columns": [{
				"name": "download_id",
				"display_name": "Download ID",
				"base_type": "type/Integer",
				"special_type": "type/PK",
				"fingerprint": null
			}, {
				"name": "created",
				"display_name": "Created",
				"base_type": "type/DateTime",
				"special_type": "type/CreationTime",
				"unit": "day",
				"fingerprint": {
					"global": {
						"distinct-count": 95
					},
					"type": {
						"type/DateTime": {
							"earliest": "2018-06-19T21:00:00.000Z",
							"latest": "2018-09-25T21:00:00.000Z"
						}
					}
				}
			}, {
				"name": "status",
				"display_name": "Status",
				"base_type": "type/Integer",
				"special_type": "type/Category",
				"fingerprint": {
					"global": {
						"distinct-count": 16
					},
					"type": {
						"type/Number": {
							"min": -20.0,
							"max": 401.0,
							"avg": 12.808195202306187
						}
					}
				}
			}]
		}
	}
}
```

**Comment by Crusader4Christ** [comment] 2019-02-26 15:03
Also where I can read about creation/join datetime/timestamp column special type?

**Comment by flamber** [comment] 2019-02-26 15:15
Really nice to have so much information - makes it so much easier to help.
It looks like the Field Type is wrong for `created`, which is currently "Creation Time", when it should be "Creation Timestamp".
You can change that under Settings > Admin > Data Model > (database) > (table) > (column)
Read more about metadata and how it works here:
https://www.metabase.com/docs/latest/administration-guide/03-metadata-editing.html

**Comment by Crusader4Christ** [comment] 2019-03-06 18:02
Sorry, Timestamp works better (it switch to the "day" unit only when you save the question, not every refresh)
here is `created` column
```
base_type: "type/DateTime"
description: null
display_name: "Created"
extra_info: {}
fingerprint: {global: {distinct-count: 95},…}
fk_field_id: null
id: 241
name: "created"
remapped_from: null
remapped_to: null
schema_name: null
source: "fields"
special_type: "type/CreationTimestamp"
table_id: 49
target: null
unit: "day"
visibility_type: "normal"
```

**Comment by Crusader4Christ** [comment] 2019-03-06 18:07
Why you don't want to add the unit to the column settings? Just add it here and issue will be solved:
![image](https://user-images.githubusercontent.com/929827/53903023-a1a63b80-4053-11e9-8afa-96666c6086bb.png)

**Comment by flamber** [comment] 2020-05-31 21:22
Closing, since this was caused by incorrect Field Type in Admin > Data Model.

**Closed by flamber** 2020-05-31 21:22 UTC
Labels: Priority:P3, Querying/GUI, Type:Bug
