### ISSUE TITLE
Improve `ambiguous column name X` error message to include the line number

### ISSUE THREAD

**Issue by aarthi-subramanian** [metabase/metabase#43683] opened 2024-06-05 19:14 UTC
### Describe the bug

We often run into this error message. BUt like which line is the error in? Or which block?
<img width="506" alt="Screenshot 2024-06-04 at 3 14 09 PM" src="https://github.com/metabase/metabase/assets/47357846/a9ed8876-15dd-4357-9e3f-00f35319da39">

### To Reproduce

Create a query with a few ctes or a long query and try to reference some ambiguous column names. See this error message and you dont know which block the issue is in

### Expected behavior

Error message should say which line the error is happening in. JUst like other metabase error messages

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.10.216-204.855.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-04",
      "tag": "v0.48.8",
      "hash": "a900c85"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Annoying, slows down dev time

**Comment by ignacio-mb** [comment] 2024-06-05 20:09
Hi @aarthi-subramanian can this be duplicate of https://github.com/metabase/metabase/issues/625 ?

**Comment by WiNloSt** [comment] 2024-06-06 08:01
Based on https://github.com/metabase/metabase/issues/30333#issuecomment-1973885041. This is a duplicate of https://github.com/metabase/metabase/issues/625. I'll close this issue for now. You can also upvote #625 if you haven't.

Thanks for reporting!

**Closed by WiNloSt** 2024-06-06 08:01 UTC
Labels: Type:Bug, Querying/Native, .Needs Triage
