### ISSUE TITLE
Bug: Metrics don't load 

### ISSUE THREAD

**Issue by StraightUpCode** [metabase/metabase#12982] opened 2020-07-22 22:27 UTC
**Describe the bug**
When going into Metrics the spinner keeps loading forever and there are errors in the javascript console

**Logs**
```
[Violation] 'setTimeout' handler took <N>ms
[Violation] 'setTimeout' handler took <N>ms
[Violation] 'setTimeout' handler took <N>ms
[Violation] 'setTimeout' handler took <N>ms
[Violation] 'setTimeout' handler took <N>ms
vendor.bundle.js?d4167a17e88b8bf103b8:1 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(anonymous) @ vendor.bundle.js?d4167a17e88b8bf103b8:1
o @ vendor.bundle.js?d4167a17e88b8bf103b8:1
value @ vendor.bundle.js?d4167a17e88b8bf103b8:1
e.notifyAll @ vendor.bundle.js?d4167a17e88b8bf103b8:1
close @ vendor.bundle.js?d4167a17e88b8bf103b8:1
closeAll @ vendor.bundle.js?d4167a17e88b8bf103b8:1
perform @ vendor.bundle.js?d4167a17e88b8bf103b8:1
perform @ vendor.bundle.js?d4167a17e88b8bf103b8:1
perform @ vendor.bundle.js?d4167a17e88b8bf103b8:1
M @ vendor.bundle.js?d4167a17e88b8bf103b8:1
close @ vendor.bundle.js?d4167a17e88b8bf103b8:1
closeAll @ vendor.bundle.js?d4167a17e88b8bf103b8:1
perform @ vendor.bundle.js?d4167a17e88b8bf103b8:1
perform @ vendor.bundle.js?d4167a17e88b8bf103b8:1
M @ vendor.bundle.js?d4167a17e88b8bf103b8:1
closeAll @ vendor.bundle.js?d4167a17e88b8bf103b8:1
perform @ vendor.bundle.js?d4167a17e88b8bf103b8:1
batchedUpdates @ vendor.bundle.js?d4167a17e88b8bf103b8:1
e @ vendor.bundle.js?d4167a17e88b8bf103b8:1
a @ vendor.bundle.js?d4167a17e88b8bf103b8:1
enqueueSetState @ vendor.bundle.js?d4167a17e88b8bf103b8:1
s.setState @ vendor.bundle.js?d4167a17e88b8bf103b8:1
i.onStateChange @ vendor.bundle.js?d4167a17e88b8bf103b8:1
notify @ vendor.bundle.js?d4167a17e88b8bf103b8:1
e.notifyNestedSubs @ vendor.bundle.js?d4167a17e88b8bf103b8:1
i.onStateChange @ vendor.bundle.js?d4167a17e88b8bf103b8:1
g @ vendor.bundle.js?d4167a17e88b8bf103b8:1
(anonymous) @ vendor.bundle.js?d4167a17e88b8bf103b8:1
(anonymous) @ vendor.bundle.js?d4167a17e88b8bf103b8:1
(anonymous) @ app-main.bundle.js?d4167a17e88b8bf103b8:5
dispatch @ vendor.bundle.js?d4167a17e88b8bf103b8:1
(anonymous) @ app-main.bundle.js?d4167a17e88b8bf103b8:5
Show 2 more frames
vendor.bundle.js?d4167a17e88b8bf103b8:1 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(anonymous) @ vendor.bundle.js?d4167a17e88b8bf103b8:1
o @ vendor.bundle.js?d4167a17e88b8bf103b8:1
value @ vendor.bundle.js?d4167a17e88b8bf103b8:1
e.notifyAll @ vendor.bundle.js?d4167a17e88b8bf103b8:1
close @ vendor.bundle.js?d4167a17e88b8bf103b8:1
closeAll @ vendor.bundle.js?d4167a17e88b8bf103b8:1
perform @ vendor.bundle.js?d4167a17e88b8bf103b8:1
perform @ vendor.bundle.js?d4167a17e88b8bf103b8:1
perform @ vendor.bundle.js?d4167a17e88b8bf103b8:1
M @ vendor.bundle.js?d4167a17e88b8bf103b8:1
close @ vendor.bundle.js?d4167a17e88b8bf103b8:1
closeAll @ vendor.bundle.js?d4167a17e88b8bf103b8:1
perform @ vendor.bundle.js?d4167a17e88b8bf103b8:1
perform @ vendor.bundle.js?d4167a17e88b8bf103b8:1
M @ vendor.bundle.js?d4167a17e88b8bf103b8:1
closeAll @ vendor.bundle.js?d4167a17e88b8bf103b8:1
perform @ vendor.bundle.js?d4167a17e88b8bf103b8:1
batchedUpdates @ vendor.bundle.js?d4167a17e88b8bf103b8:1
e @ vendor.bundle.js?d4167a17e88b8bf103b8:1
a @ vendor.bundle.js?d4167a17e88b8bf103b8:1
enqueueSetState @ vendor.bundle.js?d4167a17e88b8bf103b8:1
s.setState @ vendor.bundle.js?d4167a17e88b8bf103b8:1
i.onStateChange @ vendor.bundle.js?d4167a17e88b8bf103b8:1
notify @ vendor.bundle.js?d4167a17e88b8bf103b8:1
e.notifyNestedSubs @ vendor.bundle.js?d4167a17e88b8bf103b8:1
i.onStateChange @ vendor.bundle.js?d4167a17e88b8bf103b8:1
g @ vendor.bundle.js?d4167a17e88b8bf103b8:1
(anonymous) @ vendor.bundle.js?d4167a17e88b8bf103b8:1
(anonymous) @ vendor.bundle.js?d4167a17e88b8bf103b8:1
(anonymous) @ app-main.bundle.js?d4167a17e88b8bf103b8:5
dispatch @ vendor.bundle.js?d4167a17e88b8bf103b8:1
(anonymous) @ app-main.bundle.js?d4167a17e88b8bf103b8:5
Show 2 more frames
app-main.bundle.js?d4167a17e88b8bf103b8:5 formatQueryDescription {parts: {…}, options: {…}}
app-main.bundle.js?d4167a17e88b8bf103b8:5 formatQueryDescription {parts: {…}, options: {…}}
app-main.bundle.js?d4167a17e88b8bf103b8:5 formatQueryDescription {parts: {…}, options: {…}}
app-main.bundle.js?d4167a17e88b8bf103b8:5 formatQueryDescription {parts: {…}, options: {…}}
app-main.bundle.js?d4167a17e88b8bf103b8:5 formatQueryDescription {parts: {…}, options: {…}}
app-main.bundle.js?d4167a17e88b8bf103b8:5 formatQueryDescription {parts: {…}, options: {…}}
app-main.bundle.js?d4167a17e88b8bf103b8:5 formatQueryDescription {parts: {…}, options: {…}}options: jsx: truesections: Array(3)0: "table"1: "aggregation"2: "filter"length: 3__proto__: Array(0)__proto__: Objectparts: aggregation: [{…}]filter: [{…}]table: "Property Ra W2"__proto__: Object__proto__: Object
app-main.bundle.js?d4167a17e88b8bf103b8:5 formatQueryDescription {parts: {…}, options: {…}}
react_devtools_backend.js:12513 Uncaught TypeError: Cannot read property 'map' of undefined
    at Object.z [as aggregation] (app-main.bundle.js?d4167a17e88b8bf103b8:5)
    at app-main.bundle.js?d4167a17e88b8bf103b8:5
    at Array.map (<anonymous>)
    at t.formatQueryDescription (app-main.bundle.js?d4167a17e88b8bf103b8:5)
    at t.value (app-main.bundle.js?d4167a17e88b8bf103b8:5)
    at c._renderValidatedComponentWithoutOwnerOrContext (vendor.bundle.js?d4167a17e88b8bf103b8:1)
    at c._renderValidatedComponent (vendor.bundle.js?d4167a17e88b8bf103b8:1)
    at c.performInitialMount (vendor.bundle.js?d4167a17e88b8bf103b8:1)
    at c.mountComponent (vendor.bundle.js?d4167a17e88b8bf103b8:1)
    at Object.mountComponent (vendor.bundle.js?d4167a17e88b8bf103b8:1)
z @ app-main.bundle.js?d4167a17e88b8bf103b8:5
(anonymous) @ app-main.bundle.js?d4167a17e88b8bf103b8:5
```

**To Reproduce**
1. Go to 'admin'
2. Select 'Data Model'
3. Select the Table you are working with
2. Click on 'Metrics'

**Expected behavior**
To load the Metrics

**Screenshots**
I made a video showing the error: https://drive.google.com/file/d/1PuCcATRk4gkFluqNfD6XPm5rNdnkyw2Z/view

**Severity**
Severe because I can't create metrics 

**Metabase Diagnostic Info**
```json
{
  "browser-info": {
    "language": "en",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_252-8u252-b09-1~18.04-b09",
    "java.vendor": "Private Build",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_252",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.252-b09",
    "os.name": "Linux",
    "os.version": "4.15.0-101-generic",
    "user.language": "en",
    "user.timezone": "America/Boise"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.1 (Ubuntu 12.1-1.pgdg18.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.36.0",
      "date": "2020-07-21",
      "branch": "release-0.36.x",
      "hash": "b31049f"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2020-07-23 14:00
Interesting, I'm seeing `Unexpected input given to normalize. Expected type to be "object", found "string".` and nothing else in UI:
![image](https://user-images.githubusercontent.com/1447303/88295262-79c57f80-ccfd-11ea-914d-59e9c22b19d9.png)

**Comment by paulrosenzweig** [comment] 2020-07-27 22:21
@StraightUpCode, I wasn't able to reproduce what you're seeing, so I took a shot in the dark and guarded against the error you're seeing. Are you able to check if it fixes this for you? Here's the branch: `https://github.com/metabase/metabase/tree/fix-12982`

I suspect it will reveal a less bad bug where one or more metrics don't display their descriptions. If that's the case, can you send me the response to the `GET /api/metric` call? If there are references to sensitive data that you don't want posted online, you could send it to paul@metabase.com.

---

@flamber, are you able to repro that locally? I see it on stats, but can't seem figure out why `/api/metric` is returning an empty response.

**Comment by flamber** [comment] 2020-07-28 09:55
@paulrosenzweig I have figured out how to reproduce. Guess it has something to do with the Custom Expression:

1. On a clean 0.35.4, create a Metric, Orders, Custom Expression `Sum([Discount] * [Quantity])` as "CE", save as "Metric".
2. Then start in 0.36.0

Opening the DB on 0.35.4, then I see the following from `/api/table/2/query_metadata?include_sensitive_fields=true`
```
...
{"metrics":[{"description":"-","archived":false,"table_id":2,"definition":{"source-table":2,"aggregation":[["aggregation-options",["sum",["*",["field-id",10],["field-id",14]]],{"display-name":"CE"}]]},"show_in_getting_started":false,"name":"Metric","caveats":null,"creator_id":1,"updated_at":"2020-07-28T11:48:36.22","id":1,"how_is_this_calculated":null,"created_at":"2020-07-28T11:48:36.22","points_of_interest":null}]}
...
```

**Comment by paulrosenzweig** [comment] 2020-07-28 13:43
@flamber nice repro! It looks like you don't need to start on 0.35.4 either. That custom expression broke things for me starting on 0.36.0.

I think that's a separate root cause, so I'll split it into another issue.

**Comment by flamber** [comment] 2020-07-28 16:19
@StraightUpCode @dfx413 If you have a way to reproduce this issue, then please comment, since it seems like the error I was seeing might have been a different issue.

**Comment by dfx413** [comment] 2020-07-28 16:33
Hello @flamber 
I am not sure whether this is the same error or not. 
Please see the attached gif.
![Kapture 2020-07-28 at 18 30 45](https://user-images.githubusercontent.com/1764151/88694398-c5629980-d100-11ea-8336-37a3280f31d8.gif)

**Comment by flamber** [comment] 2020-07-28 16:42
@dfx413 No, that's #13022.

**Comment by dfx413** [comment] 2020-07-28 16:43
@flamber OK, sorry for the confusion then.

**Comment by flamber** [comment] 2020-07-30 19:01
I'm going to close this, since we haven't been able to reproduce. We have just release 0.36.1, which fixes the other issue, but there's a possible fix for this too.
If anyone is still experiencing this, then please comment and provide as much details as possible, so we can try to reproduce.

**Closed by flamber** 2020-07-30 19:01 UTC
Labels: .Unable to Reproduce, Administration/Metrics & Segments, Priority:P1, Type:Bug
