### ISSUE TITLE
Schema sync issue, only on certain Metabase instances, with certain schemas.

### ISSUE THREAD

**Issue by BrieucVanThienen** [metabase/metabase#11677] opened 2020-01-10 14:56 UTC
Hello,

I am experiencing some issues with the sync of the database schema.

It happens that newly created tables / columns do not show on Metabase, even after triggering the sync. More precisely, the tables / columns can be queried, but they do not show under the data models page and the tables / columns cannot be used as filters in the queries.

We run different instances of Metabase at our company for our different departments. What is weird is that I am only facing such issues on certains instances, and not all.

For now, this issue only arises with only one of our schemas (DBT: https://www.getdbt.com/).

thanks in advance for your availability and support!

Brieuc Van Thienen

**Comment by mazameli** [comment] 2020-01-17 23:04
Sync can sometimes take a bit. Do you still not see the added tables / columns now?

**Comment by camsaul** [comment] 2020-01-17 23:06
@BrieucVanThienen you may need to refresh the page (this is a known issue). Can you give that a try?

**Comment by flamber** [comment] 2020-06-04 14:32
Closing, since no reply. Likely a duplicate of #10330. Related to #11354

**Closed by flamber** 2020-06-04 14:32 UTC
Labels: .Need More Info, Administration/Metadata & Sync, Type:Question
