### ISSUE TITLE
Migration issue between v0.41.6 and v0.43.0

### ISSUE THREAD

**Issue by Sytten** [metabase/metabase#22668] opened 2022-05-12 15:30 UTC
**Describe the bug**
Cannot upgrade from v0.41.6 to v0.43.0

**Logs**
```
May 12 11:24:16 AM  2022-05-12 15:24:16,259 ERROR metabase.core :: Metabase Initialization FAILED
May 12 11:24:16 AM  liquibase.exception.LiquibaseException: liquibase.exception.DatabaseException: ERROR: duplicate key value violates unique constraint "idx_databasechangelog_id_author_filename"
May 12 11:24:16 AM    Detail: Key (id, author, filename)=(v43.00-029, camsaul, migrations/000_migrations.yaml) already exists. [Failed SQL: (0) INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('v43.00-029', 'camsaul', 'migrations/000_migrations.yaml', NOW(), 440, '8:4d5632ee6fae1f8d0d5e6068700ccb2e', 'sql', 'Added 0.43.0. Clear local password for Users using LDAP auth.', 'EXECUTED', NULL, NULL, '4.8.0', '2369055461')]
May 12 11:24:16 AM      at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:126)
May 12 11:24:16 AM      at liquibase.Liquibase.lambda$null$0(Liquibase.java:265)
May 12 11:24:16 AM      at liquibase.Scope.lambda$child$0(Scope.java:180)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:189)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:179)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:158)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:243)
May 12 11:24:16 AM      at liquibase.Liquibase.lambda$update$1(Liquibase.java:264)
May 12 11:24:16 AM      at liquibase.Scope.lambda$child$0(Scope.java:180)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:189)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:179)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:158)
May 12 11:24:16 AM      at liquibase.Liquibase.runInScope(Liquibase.java:2405)
May 12 11:24:16 AM      at liquibase.Liquibase.update(Liquibase.java:211)
May 12 11:24:16 AM      at liquibase.Liquibase.update(Liquibase.java:197)
May 12 11:24:16 AM      at liquibase.Liquibase.update(Liquibase.java:193)
May 12 11:24:16 AM      at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:142)
May 12 11:24:16 AM      at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:130)
May 12 11:24:16 AM      at metabase.db.setup$fn__34820$migrate_BANG___34825$fn__34826$fn__34827.invoke(setup.clj:68)
May 12 11:24:16 AM      at metabase.db.liquibase$fn__30484$do_with_liquibase__30489$fn__30490.invoke(liquibase.clj:59)
May 12 11:24:16 AM      at metabase.db.liquibase$fn__30484$do_with_liquibase__30489.invoke(liquibase.clj:51)
May 12 11:24:16 AM      at metabase.db.setup$fn__34820$migrate_BANG___34825$fn__34826.invoke(setup.clj:63)
May 12 11:24:16 AM      at metabase.db.setup$fn__34820$migrate_BANG___34825.invoke(setup.clj:40)
May 12 11:24:16 AM      at metabase.db.setup$fn__34879$run_schema_migrations_BANG___34884$fn__34885.invoke(setup.clj:121)
May 12 11:24:16 AM      at metabase.db.setup$fn__34879$run_schema_migrations_BANG___34884.invoke(setup.clj:115)
May 12 11:24:16 AM      at metabase.db.setup$fn__34931$setup_db_BANG___34936$fn__34937$fn__34940$fn__34941.invoke(setup.clj:147)
May 12 11:24:16 AM      at metabase.util$do_with_us_locale.invokeStatic(util.clj:715)
May 12 11:24:16 AM      at metabase.util$do_with_us_locale.invoke(util.clj:701)
May 12 11:24:16 AM      at metabase.db.setup$fn__34931$setup_db_BANG___34936$fn__34937$fn__34940.invoke(setup.clj:145)
May 12 11:24:16 AM      at metabase.db.setup$fn__34931$setup_db_BANG___34936$fn__34937.invoke(setup.clj:144)
May 12 11:24:16 AM      at metabase.db.setup$fn__34931$setup_db_BANG___34936.invoke(setup.clj:138)
May 12 11:24:16 AM      at metabase.db$setup_db_BANG_$fn__34966.invoke(db.clj:65)
May 12 11:24:16 AM      at metabase.db$setup_db_BANG_.invokeStatic(db.clj:60)
May 12 11:24:16 AM      at metabase.db$setup_db_BANG_.invoke(db.clj:51)
May 12 11:24:16 AM      at metabase.core$init_BANG_.invokeStatic(core.clj:96)
May 12 11:24:16 AM      at metabase.core$init_BANG_.invoke(core.clj:79)
May 12 11:24:16 AM      at metabase.core$start_normally.invokeStatic(core.clj:137)
May 12 11:24:16 AM      at metabase.core$start_normally.invoke(core.clj:131)
May 12 11:24:16 AM      at metabase.core$_main.invokeStatic(core.clj:170)
May 12 11:24:16 AM      at metabase.core$_main.doInvoke(core.clj:164)
May 12 11:24:16 AM      at clojure.lang.RestFn.invoke(RestFn.java:397)
May 12 11:24:16 AM      at clojure.lang.AFn.applyToHelper(AFn.java:152)
May 12 11:24:16 AM      at clojure.lang.RestFn.applyTo(RestFn.java:132)
May 12 11:24:16 AM      at metabase.core.main(Unknown Source)
May 12 11:24:16 AM  Caused by: liquibase.exception.DatabaseException: ERROR: duplicate key value violates unique constraint "idx_databasechangelog_id_author_filename"
May 12 11:24:16 AM    Detail: Key (id, author, filename)=(v43.00-029, camsaul, migrations/000_migrations.yaml) already exists. [Failed SQL: (0) INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('v43.00-029', 'camsaul', 'migrations/000_migrations.yaml', NOW(), 440, '8:4d5632ee6fae1f8d0d5e6068700ccb2e', 'sql', 'Added 0.43.0. Clear local password for Users using LDAP auth.', 'EXECUTED', NULL, NULL, '4.8.0', '2369055461')]
May 12 11:24:16 AM      at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:397)
May 12 11:24:16 AM      at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:83)
May 12 11:24:16 AM      at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:151)
May 12 11:24:16 AM      at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:135)
May 12 11:24:16 AM      at liquibase.changelog.StandardChangeLogHistoryService.setExecType(StandardChangeLogHistoryService.java:391)
May 12 11:24:16 AM      at liquibase.database.AbstractJdbcDatabase.markChangeSetExecStatus(AbstractJdbcDatabase.java:1136)
May 12 11:24:16 AM      at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:67)
May 12 11:24:16 AM      at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:113)
May 12 11:24:16 AM      at liquibase.Scope.lambda$child$0(Scope.java:180)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:189)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:179)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:158)
May 12 11:24:16 AM      at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:112)
May 12 11:24:16 AM      at liquibase.Scope.lambda$child$0(Scope.java:180)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:189)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:179)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:158)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:243)
May 12 11:24:16 AM      at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:93)
May 12 11:24:16 AM      at liquibase.Scope.lambda$child$0(Scope.java:180)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:189)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:179)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:158)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:243)
May 12 11:24:16 AM      at liquibase.Scope.child(Scope.java:247)
May 12 11:24:16 AM      at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:65)
May 12 11:24:16 AM      ... 43 more
May 12 11:24:16 AM  Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "idx_databasechangelog_id_author_filename"
May 12 11:24:16 AM    Detail: Key (id, author, filename)=(v43.00-029, camsaul, migrations/000_migrations.yaml) already exists.
May 12 11:24:16 AM      at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
May 12 11:24:16 AM      at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
May 12 11:24:16 AM      at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
May 12 11:24:16 AM      at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
May 12 11:24:16 AM      at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
May 12 11:24:16 AM      at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:329)
May 12 11:24:16 AM      at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:315)
May 12 11:24:16 AM      at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:291)
May 12 11:24:16 AM      at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:286)
May 12 11:24:16 AM      at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
May 12 11:24:16 AM      at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393)
May 12 11:24:16 AM      ... 68 more
May 12 11:24:16 AM  2022-05-12 15:24:16,268 INFO metabase.core :: Metabase Shutting Down ...
May 12 11:24:16 AM  2022-05-12 15:24:16,292 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
May 12 11:24:16 AM  2022-05-12 15:24:16,302 INFO metabase.core :: Metabase Shutdown COMPLETE
```

**To Reproduce**
1. Install 0.41.6 and setup
2. Upgrade to 0.43.0
3. See failure

**Information about your Metabase Installation:**

- Metabase version: 0.43.0
- Metabase hosting environment: Render (with Docker)
- Metabase internal database: Postgres

**Severity**
Blocking an upgrade and now my installation doesnt work.

**Comment by Sytten** [comment] 2022-05-12 15:38
I restarted the service and it worked since the migrations have been applied.
You seem to have a concurrency issue in the migration application or something since the row was inserted and the migration seems to have been successful.

**Comment by paoliniluis** [comment] 2022-05-12 17:14
Hi, I just tried to reproduce this by spinning up a new 41.6, filling it up with dashboards and questions and then moving to 43, but I couldn't reproduce this. Did you do some modification on the DB at some point? or maybe some downgrade?

**Closed by paoliniluis** 2022-05-12 17:14 UTC
Labels: Type:Bug, .Needs Triage

**Comment by Sytten** [comment] 2022-05-12 20:11
I didnt do any downgrade or modification. Unsure what went wrong, not a big deal anyway.
