### ISSUE TITLE
Link to Sharing Settings in the embedding pane for admins

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#31727] opened 2023-06-20 15:02 UTC
[slack discussion](https://metaboat.slack.com/archives/C01LQQ2UW03/p1687272988138109?thread_ts=1686926957.980749&cid=C01LQQ2UW03)

When an admin goes to share a question, and all the options are greyed out, it's unclear why. 

- For admin and settings admin users, we should add some text that explains that sharing is disabled and provide a link to the relevant settings page.
- For non-admins, should we also add some text and explain that sharing is disabled and they can ask an admin to enable it?

**Comment by albertoperdomo** [comment] 2023-06-20 15:20
We are also currently rendering a URL that doesn't work, e.g. `https://metabase.mydomain.com/public/dashboards/null`. It doesn't provide any value and could confuse folks. I certainly was confused by the URL thinking it was greyed out because I was running Metabase from localhost.

**Comment by albertoperdomo** [comment] 2023-10-27 18:59
Related / dupe of #4592
Going to be addressed in upcoming re-design of the sharing modal.

**Comment by albertoperdomo** [comment] 2023-11-24 16:43
Closing as addressed as part of a redesign of the flow in #35961

**Comment by albertoperdomo** [comment] 2023-11-24 16:43
Closing as addressed as part of a redesign of the flow in https://github.com/metabase/metabase/issues/35961

**Closed by albertoperdomo** 2023-11-24 16:43 UTC
Labels: Type:New Feature, Embedding/Public, .Team/Embedding
