### ISSUE TITLE
the url for downloading data for a question is incorrect

### ISSUE THREAD

**Issue by Roman2nc** [metabase/metabase#33943] opened 2023-09-18 21:49 UTC
### Describe the bug

metabase is configured with the MB_SITE_URL environment variable as "https:/my_domain/metabase".

When a download is requested, the application addresses the following url:
https://my_domain/api/dashboard/15/dashcard/77/card/62/query/xlsx

The path "metabase" is missing from the url

### To Reproduce

1. Go to dashboard
2. export menu question

![image](https://github.com/metabase/metabase/assets/66816029/e59a38d2-4225-4020-90bf-8bd218109f4d)

### Information about your Metabase installation

```JSON
- metabase 0.47.1
- postgres 15
```

### Severity

blocking download feature

**Comment by uladzimirdev** [comment] 2023-09-19 04:49
Seems to be a duplicate of https://github.com/metabase/metabase/issues/33244, which should be addressed in 0.47.2

**Comment by uladzimirdev** [comment] 2023-09-19 06:40
@Roman2nc please check 0.47.2. I'm closing this issue, but feel free to reopen if it's still not solved

**Closed** 2023-09-19 06:41 UTC
Labels: Type:Bug
