### ISSUE TITLE
Common metrics of right join table doesn't appear in question tool

### ISSUE THREAD

**Issue by claire-go** [metabase/metabase#24145] opened 2022-07-20 14:55 UTC
**Describe the bug**
When I join 2 tables with both common segments / metrics, only the segments / metrics of the 1st table selected tool is available
I can't see the other tables common metrics & filters in the dropdown

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to New question
2. Add a first data source
3. Join with a second data source
4. Click on summarize : you can see common metrics of the 1st table, but none of the 2nd

**Expected behavior**
You should be able to use common metrics / segments of all data sources of query

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.g., Chrome 52.1, Firefox 48.0, Safari 11.1, …)
Chrome
- Your operating system: (e.g., OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
Windows
- Your databases: (e.g, MySQL, Postgres, MongoDB, …)
BigQuery
- Metabase version: (e.g., 0.19.3) 
0.43.3
- Metabase hosting environment: (e.g., Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.g., H2 (default), Postgres or MySQL)
Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.
Can be manageable - can still re-create manually metrics in every query but totally undermines concept of common metrics

**Additional context**

**Comment by flamber** [comment] 2022-07-21 14:45
Duplicate of #2958/#15914

**Closed by flamber** 2022-07-21 14:45 UTC
Labels: Type:Bug, .Needs Triage
