### ISSUE TITLE
Dragging and dropping dashboard charts during edit often opens the question, losing your pending edits

### ISSUE THREAD

**Issue by bcherry** [metabase/metabase#11084] opened 2019-10-08 00:38 UTC
**Describe the bug**

When you enter edit mode on a dashboard and click to drag a graph item, then drop it, the browser frequently navigates to the link and you lose all unsaved edits to the dashboard.

I don't know if others have the same UX issue, but this is a source of unending frustration for me when trying to build dashboards for our instance.

**Logs**
There was nothing in the log during this interaction.

**To Reproduce**
1. Go to any dashboard
2. Start edit
3. Add a chart question to the dashboard
4. Try to drag and drop the question by its body

Note: I observed this with area charts but not with numbers. I haven't tried every type of chart.

**Expected behavior**
You'd expect it to drop and you remain on the page.

**Screenshots**
Happy to provide if they actually sound useful.

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 77.0
- Your operating system: OS X Mojave 10.14.6
- Your databases: PostgreSQL
- Metabase version: v0.33.2
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: PostgreSQL

**Severity**
Very annoying

**Additional context**

**Comment by flamber** [comment] 2019-10-08 04:21
Hi @bcherry 
Sounds like a duplicate of #6888, fixed by #10931 and included in 0.33.4 released a few hours ago.

**Comment by mazameli** [comment] 2019-10-08 16:17
Thanks for the report, Ben! As @flamber mentioned, this should be fixed in 0.33.4. If and when you upgrade, let us know if you're still running into this.

**Closed by mazameli** 2019-10-08 16:17 UTC
Labels: Already Fixed, Duplicate, Type:Bug

**Comment by bcherry** [comment] 2019-10-09 04:19
Great, thanks everyone!  I'll try to do a more comprehensive search next time :)
