### ISSUE TITLE
Problems with DNS on AWS Fargate

### ISSUE THREAD

**Issue by felipefdl** [metabase/metabase#8373] opened 2018-08-21 13:46 UTC
I can’t found solution for that problem, it was working normal before 0.30 version.

## Log Output:

``` bash
08-21 13:33:19 INFO metabase.util :: Loading Metabase...
08-21 13:33:39 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
For more information, see https://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
08-21 13:34:11 INFO metabase.core :: Starting Metabase in STANDALONE mode
08-21 13:34:11 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
{:port 3000, :host "0.0.0.0"}
08-21 13:34:11 INFO metabase.core :: Starting Metabase version v0.30.1 (b4e9050 release-0.30.1) ...
08-21 13:34:11 INFO metabase.core :: System timezone is 'GMT' ...
WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collection, being replaced by: #'monger.collection/any?
08-21 13:34:17 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
08-21 13:34:17 INFO metabase.db :: [36mVerifying postgres Database Connection ...
08-21 13:34:17 INFO metabase.db :: Verify Database Connection ... ✅
08-21 13:34:17 INFO metabase.db :: Running Database Migrations...
08-21 13:34:17 INFO metabase.db :: Setting up Liquibase...
08-21 13:34:17 INFO metabase.db :: Liquibase is ready.
08-21 13:34:17 INFO metabase.db :: Checking if Database has unrun migrations...
08-21 13:34:28 INFO metabase.db :: Database Migrations Current ... ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
08-21 13:34:29 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
08-21 13:34:29 INFO db.migrations :: Finished running data migrations.
08-21 13:34:29 INFO metabase.events :: Starting events listener: [34mmetabase.events.notifications
08-21 13:34:29 INFO metabase.events :: Starting events listener: [34mmetabase.events.metabot-lifecycle
08-21 13:34:29 INFO metabase.events :: Starting events listener: [34mmetabase.events.dependencies
08-21 13:34:29 INFO metabase.events :: Starting events listener: [34mmetabase.events.activity-feed
08-21 13:34:29 INFO metabase.events :: Starting events listener: [34mmetabase.events.last-login
08-21 13:34:29 INFO metabase.events :: Starting events listener: [34mmetabase.events.revision
08-21 13:34:29 INFO metabase.events :: Starting events listener: [34mmetabase.events.sync-database
08-21 13:34:29 INFO metabase.events :: Starting events listener: [34mmetabase.events.view-log
08-21 13:34:29 INFO metabase.events :: Starting events listener: [34mmetabase.events.driver-notifications
08-21 13:34:30 ERROR impl.StdSchedulerFactory :: Couldn't generate instance Id!
org.quartz.SchedulerException: Couldn't get host name! [See nested exception: java.net.UnknownHostException: 00bcf2fe65d4: 00bcf2fe65d4: Name does not resolve]
at org.quartz.simpl.SimpleInstanceIdGenerator.generateInstanceId(SimpleInstanceIdGenerator.java:36)
at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1202)
at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1502)
at org.quartz.impl.StdSchedulerFactory.getDefaultScheduler(StdSchedulerFactory.java:1518)
at clojurewerkz.quartzite.scheduler$initialize.invokeStatic(scheduler.clj:22)
at clojurewerkz.quartzite.scheduler$initialize.invoke(scheduler.clj:22)
at metabase.task$start_scheduler_BANG_.invokeStatic(task.clj:79)
at metabase.task$start_scheduler_BANG_.invoke(task.clj:72)
at metabase.core$init_BANG_.invokeStatic(core.clj:173)
at metabase.core$init_BANG_.invoke(core.clj:138)
at metabase.core$start_normally.invokeStatic(core.clj:245)
at metabase.core$start_normally.invoke(core.clj:239)
at metabase.core$_main.invokeStatic(core.clj:265)
at metabase.core$_main.doInvoke(core.clj:260)
at clojure.lang.RestFn.invoke(RestFn.java:397)
at clojure.lang.AFn.applyToHelper(AFn.java:152)
at clojure.lang.RestFn.applyTo(RestFn.java:132)
at metabase.core.main(Unknown Source)
Caused by: java.net.UnknownHostException: 00bcf2fe65d4: 00bcf2fe65d4: Name does not resolve
at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
at org.quartz.simpl.SimpleInstanceIdGenerator.generateInstanceId(SimpleInstanceIdGenerator.java:34)
... 17 more
Caused by: java.net.UnknownHostException: 00bcf2fe65d4: Name does not resolve
at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
... 18 more
08-21 13:34:30 ERROR metabase.core :: Metabase Initialization FAILED
java.lang.IllegalStateException: Cannot run without an instance id.
at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1206)
at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1502)
at org.quartz.impl.StdSchedulerFactory.getDefaultScheduler(StdSchedulerFactory.java:1518)
at clojurewerkz.quartzite.scheduler$initialize.invokeStatic(scheduler.clj:22)
at clojurewerkz.quartzite.scheduler$initialize.invoke(scheduler.clj:22)
at metabase.task$start_scheduler_BANG_.invokeStatic(task.clj:79)
at metabase.task$start_scheduler_BANG_.invoke(task.clj:72)
at metabase.core$init_BANG_.invokeStatic(core.clj:173)
at metabase.core$init_BANG_.invoke(core.clj:138)
at metabase.core$start_normally.invokeStatic(core.clj:245)
at metabase.core$start_normally.invoke(core.clj:239)
at metabase.core$_main.invokeStatic(core.clj:265)
at metabase.core$_main.doInvoke(core.clj:260)
at clojure.lang.RestFn.invoke(RestFn.java:397)
at clojure.lang.AFn.applyToHelper(AFn.java:152)
at clojure.lang.RestFn.applyTo(RestFn.java:132)
at metabase.core.main(Unknown Source)
08-21 13:34:30 INFO metabase.core :: Metabase Shutting Down ...
08-21 13:34:30 INFO metabase.core :: Metabase Shutdown COMPLETE
```

**Comment by doodlebro** [comment] 2018-08-23 19:56
Same here, my docker image gets to running migrations and then appears to restart itself ad-infinitum.

**Comment by doodlebro** [comment] 2018-09-04 19:03
Anybody? Pretty major bug here preventing upgrades.

**Comment by felipefdl** [comment] 2018-09-04 19:05
I'm still having this problem also.

**Comment by felipefdl** [comment] 2018-09-04 19:38
@lenn4rd 
My AWS ECS Task Configuration, I've changed some characters to hide my credentials.

The ```00bcf2fe65d4``` should be the docker ID and the hostname as well.

FYI: The versions before 0.30, works well, with same configuration, I've just switch de image version.

```javascript
{
  "executionRoleArn": "arn:aws:iam::6274221234786:role/taskRoleEc2",
  "containerDefinitions": [
    {
      "dnsSearchDomains": null,
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group": "Services",
          "awslogs-region": "us-east-1",
          "awslogs-stream-prefix": "Metabase-BI"
        }
      },
      "entryPoint": null,
      "portMappings": [
        {
          "hostPort": 3000,
          "protocol": "tcp",
          "containerPort": 3000
        }
      ],
      "command": null,
      "linuxParameters": null,
      "cpu": 0,
      "environment": [
        {
          "name": "MB_DB_DBNAME",
          "value": "metabase"
        },
        {
          "name": "MB_DB_HOST",
          "value": "metabase-bi.LrdXJpJqjiYkLTRBEfKtHvC7.us-east-1.rds.amazonaws.com"
        },
        {
          "name": "MB_DB_PASS",
          "value": "crQwQqfiPtGdF7UUWdJCUCQs"
        },
        {
          "name": "MB_DB_PORT",
          "value": "5432"
        },
        {
          "name": "MB_DB_TYPE",
          "value": "postgres"
        },
        {
          "name": "MB_DB_USER",
          "value": "rMFErDZe4dtGssHLHJcGvZwi"
        }
      ],
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "dockerSecurityOptions": null,
      "memory": null,
      "memoryReservation": null,
      "volumesFrom": [],
      "image": "metabase/metabase",
      "disableNetworking": null,
      "healthCheck": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "privileged": null,
      "name": "Metabase"
    }
  ],
  "placementConstraints": [],
  "memory": "1024",
  "taskRoleArn": "arn:aws:iam::627422104722:role/core_container",
  "compatibilities": [
    "EC2",
    "FARGATE"
  ],
  "taskDefinitionArn": "arn:aws:ecs:us-east-1:627422104733:task-definition/Metabase-BI:11",
  "family": "Metabase-BI",
  "requiresAttributes": [
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.task-eni"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.task-iam-role"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.execution-role-awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
    }
  ],
  "requiresCompatibilities": [
    "FARGATE"
  ],
  "networkMode": "awsvpc",
  "cpu": "512",
  "revision": 11,
  "status": "ACTIVE",
  "volumes": []
}
```

**Comment by lenn4rd** [comment] 2018-09-04 20:37
I wonder where that ID comes from. Is that hostname somewhere in the Metabase configuration? I was kind of expecting it to show up in the task definition. Ours looks very similar. I’m not an ECS expert so I can’t tell some inconspicuous setting like roles lacking permissions could cause this. Sorry, I don’t think I can help here.

BTW, the task definition has full database credentials so you might want to treat them as compromised and change them. Depending on the RDS settings an attacker won’t even be able to connect though.

**Comment by felipefdl** [comment] 2018-09-04 20:49
@lenn4rd the configuration above is not real credentials as I said, I changed the strings, also it is on my private network (VPC). But thanks, I'm still waiting for solution.

**Comment by lenn4rd** [comment] 2018-09-04 21:00
Oops, my bad, didn’t see that due to the screen size on the phone.

**Comment by jornh** [comment] 2018-09-25 05:34
@doodlebro it seems like a configuration issue specifically  related to using the Docker image on AWS ECS. It of course has a big impact on the ability to upgrade for those running in that specific environment.

From the error log above it’s relatively clear the issue has to do with the AWS ECS environment not providing a resolvable host name. That’s a pretty basic thing for many applications to be able to do. AFAICT that additional requirement/dependency got added to support another feature request regarding scaling vertically out to several hosts. 
It also seems [if you google for it](https://www.google.com/search?client=safari&hl=en-dk&ei=AnyoW9WJEIiasAGWm4jwDg&ins=false&q=aws+%2Becs+get+hostname&oq=aws+%2Becs+get+hostname&gs_l=mobile-gws-wiz-serp.3...75087.75087..76710...0.0..0.106.106.0j1......0....1.........0i71.eMLPzNDkZN8) like an issue others have been running into with AWS services:
https://serverfault.com/questions/892199/aws-private-instance-cannot-resolve-hostname-vpc-with-nat-instance. On top of that I note both `"dnsServers": null,` and `"hostname": null,` in the config @felipefdl shared above. Not sure if configuring that differently can help. I’m not familiar with AWS ECS myself - yet!

I don’t think it’s reasonable to expect the core developers to have the bandwidth to be able to help resolve configuration issues in environments they may not be familiar with themselves. That’s basically asking for free support from a startup company providing free open source under the AGPL license.

Note I’m just another another Metabase user choosing to spend some of my time on trying to help out triaging issues etc. as best I can. I hope some of the above can help you guys or others in the community to resolve the problem.

**Comment by doodlebro** [comment] 2018-09-26 02:56
@jornh I'm not saying that the core developers have to help with anything, it's just that this issue is pervasive enough to have multiple open issues without any real plan of action or even acknowledgement of the problem.

Many of those issues don't even have messaging/reply from the core devs! They don't have to make it their number 1 priority, but it'd be great to know that they see the issue and plan to fix it. That's all.

**Comment by janidipak** [comment] 2018-10-19 17:33
Need some help. I am using metabase (0.29.3) on Amazon EC2 with Postgres DB. Works like a charm. Decided to upgrade to metabase (latest - 0.30.4). Followed instructions from webpage. (Stop the service, restarted the service after replacing new jar. Now....I see the some issue with Hostname error. 

'''
10-18 15:36:20 ERROR impl.StdSchedulerFactory :: Couldn't generate instance Id!
org.quartz.SchedulerException: Couldn't get host name! [See nested exception: java.net.UnknownHostException: ip-xx-xx-x-xxx: ip-xx-xx-x-xxx: No address associated with hostname]
	at org.quartz.simpl.SimpleInstanceIdGenerator.generateInstanceId(SimpleInstanceIdGenerator.java:36)
'''
When I do hostname on EC2 - I get ip-xx-xx-x-xxx. 

Downloaded the source code and updated the resources/quartz.properties
From : org.quartz.scheduler.instanceId = AUTO
To : org.quartz.scheduler.instanceId = SomeString

Complied on local machine with ./bin/build. Jar was successfully created. But then it failed for something else. Not pasting that error here. 

Any pointer, on how to resolve this issue? I rolled back to previous jar and it is working right now. However in this process, it was not able to bring back to original state of the DB, so had to restore DB to a previous point in time.

**Comment by jornh** [comment] 2018-10-22 18:29
Maybe https://github.com/quartznet/quartznet/issues/503 is helpful? It not only mentions overriding `org.quartz.scheduler.instanceId` As you did but also `org.quartz.scheduler.instanceName`

**Comment by janidipak** [comment] 2018-10-24 23:35
I am running on Amazon EC2 with RDS - ostgreSQL 9.6.3. 
First I faced HostName issue as above, I was able to resolve this. 
Resolution : Add Hostname IP to /etc/hosts. 

Now I cloned my existing postgres db to try this out. But not able to start Metabase. 
If I use Local H2 Database, I am able to start Metabase and then Add Postgres DB through UI using Add Database Functionality. 

But to use existing Metabase Database Tables, If I start Metabase with Postgres options, It doesn't work. Now it's showing below error. 

"org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "xx.xx.x.xxx", user "myusername", database "mydatabase", SSL off"

Looked through so many postings. Common solution was to add below within MB_DB_CONNECTION_URI. 
ssl=true
sslmode=require
sslfactory=org.postgresql.ssl.NonValidatingFactory

None of this is working as expected or explained. There is no way I can update pg_hdb.conf file on Amazon Managed RDS box. In face, I am able to psql into postgres DB from the EC2 where I want to run Metabase Jar. So there is nothing related to RDS at this point. 

So...I am sure there is a way to avoid this error through Metabase backend while migrating Metabase Jar from 29.3 to 30.4. 

Same settings work for 29.3 but not for 30.4. 
First issue encountered was HostName issue by "org.quartz.SchedulerException"
Second issue encountered was "org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host"

Any expert advice on how to handle this situation? For now we are running 29.3 but really want to upgrade to use some of the newly added features. 

Thank You

**Comment by janidipak** [comment] 2018-10-26 15:04
Update: I was able to get away with this issue by creating brand new RDS Instance (Aurora PostgreSQL 10.4). I guess for some reason, previously installed DB (Aurora PostgreSQL 9.6.3) doesn't work due to compatibility issue or metabase metadata issue.

**Comment by doodlebro** [comment] 2018-10-31 18:57
FWIW, the latest 0.31 RC appears to not have issues starting up with a postgres backend. I am waiting on the full 0.31 release to upgrade my prod instance, but on test everything looks good.

**Comment by mazameli** [comment] 2018-12-15 01:33
That's good to hear, @doodlebro. @janidipak and @felipefdl, have you been able to test and verify if version 0.31.x still has this issue?

**Comment by felipefdl** [comment] 2018-12-15 23:07
@mazameli it's still not working to me, same problem.

**Comment by janidipak** [comment] 2018-12-17 16:04
@mazameli. I was able to successfully migrate to the latest version. I am using 31.1 now. 
I had to change the connection url to : 
Option : ssl=true&sslmode=require
It was this earlier : 
Option : ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory

Other than that, my hack for the hostname issue is fixed by putting below line in my userdata script. 

echo $IP `hostname` >> /etc/hosts

So this time I was able to migrate to a newer version with no issues at all. Have been testing and running few things. No issues seen so far.

**Comment by flamber** [comment] 2020-09-23 08:57
Reopening, since it depends on if the hostname can be resolved.
Possible workaround stolen from https://github.com/uktrade/data-workspace/commit/8061d2b1c31648d7bfe0084a22a6a8fb996ba828 would be to add the following to [/bin/docker/run_metabase.sh](https://github.com/metabase/metabase/blob/master/bin/docker/run_metabase.sh), but that would probably cause problems for non-root, when #9861 is addressed.
Not sure if there's other side-effects from this too.
```
HOSTNAME=`cat /etc/hostname`
echo "${HOSTNAME} 127.0.0.1" >> /etc/hosts
```
Related to #7258

**Comment by countrodrigo** [comment] 2020-09-23 15:48
The issue is in particular with ECS Fargate, and since it particularly disables setting host names in /etc/hosts via the task config, this might not work. Will try it and report back.

**Comment by Thomas-dd3** [comment] 2020-11-17 14:02
After many attempts, I found something.
It was working on my default VPC and not on my own VPC.
So if you have this issue, first make sure that you have "enable_dns_hostnames" of your VPC set to true.
(After changing false to true, it worked for me with ECS Fargate.)

**Comment by andotorg** [comment] 2020-12-18 06:59
Modify the value of hostname corresponding to 127.0.0.1 in the / etc / hosts file, and then run the container again

**Comment by narroyog** [comment] 2021-02-06 15:31
there is an alternative if you are not able to enable enable_dns_hostnames on the VPC (based on @flamber workaround above and [this post](http://www.mceith.com/blog/?p=282) )

```
export IP_ADDRESS=$(curl -s http://169.254.170.2/v2/metadata | jq -r .Containers[0].Networks[0].IPv4Addresses[0])
echo $IP_ADDRESS $(cat /etc/hostname) >> /etc/hosts
```

**Comment by pauldraper** [comment] 2022-11-13 00:24
Confirmed that https://github.com/metabase/metabase/issues/8373#issuecomment-728948066 fixes this.

I have not run into this issue with other programs.

**Comment by otavioribeiromedeiros** [comment] 2023-02-01 20:28
> After many attempts, I found something. It was working on my default VPC and not on my own VPC. So if you have this issue, first make sure that you have "enable_dns_hostnames" of your VPC set to true. (After changing false to true, it worked for me with ECS Fargate.)

You saved my day, thank you!

**Comment by redoh** [comment] 2024-07-02 10:54
> After many attempts, I found something. It was working on my default VPC and not on my own VPC. So if you have this issue, first make sure that you have "enable_dns_hostnames" of your VPC set to true. (After changing false to true, it worked for me with ECS Fargate.)

You're a perfect player

**Comment by darksciencebase** [comment] 2024-07-03 12:23
Since this is not a bug in metabase, we're going to close this issue.

**Closed by darksciencebase** 2024-07-03 12:23 UTC
Labels: Type:Bug, Priority:P2, Operation/Docker, .Custom/BEC

**Comment by abobakrahmed** [comment] 2024-07-04 15:40
@Thomas-dd3 Really Thank you !
