### ISSUE TITLE
min or max  view does not support date type

### ISSUE THREAD

**Issue by witwall** [metabase/metabase#6484] opened 2017-11-28 06:30 UTC
------
Before filing an issue we'd appreciate it if you could take a moment to ensure
there isn't already an open issue or pull-request.
-----

If there's an existing issue, please add a :+1: reaction to the description of
the issue. One way we prioritize issues is by the number of :+1: reactions on
their descriptions. Please DO NOT add `+1` or :+1: comments.

### Database support

For requests for new database drivers, please include the name
of the database and the version. Additionally, giving us a sense of how and what
you use it for, and other high-level details about the database, can help us get
a better picture of what would need to done to support it.

### Feature requests and proposals
We're excited to hear how we can make Metabase better. Please add as much detail
as you can on your use case.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Chrome 62.0.3202.94
- Your operating system: (e.x. OS X 10, Windows XP, etc)
OS X 10
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Postgres
- Metabase version: (e.x. 0.19.3)
0.26.2
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Mac app
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
H2
- *Repeatable steps to reproduce the issue*
I want to know the min date or max date in the view, but Custom question does not support it.
![image](https://user-images.githubusercontent.com/3222056/33305344-b424c970-d448-11e7-8428-28fb02387186.png)

Thanks for being part of the Metabase project!
-------

**Comment by c-schmitz** [comment] 2017-12-20 11:26
Duplicate of #4482

**Comment by mazameli** [comment] 2019-10-24 21:29
Closing as dupe of #4482

**Closed by mazameli** 2019-10-24 21:29 UTC
Labels: .Duplicate, .Proposal, Query Builder

**Comment by maxko87** [comment] 2020-03-05 01:26
I fixed it by doing this:

`to_char(your_date_column,'YYYYMMDD')::integer as your_date_column_integer,`
