### ISSUE TITLE
Second aggregation impossible if first aggregation is grouped by a custom column

### ISSUE THREAD

**Issue by BertrandToulas** [metabase/metabase#25231] opened 2022-09-05 13:48 UTC
**Describe the bug**
Cannot aggregate data based on an aggregation that is grouped by a custom column. (with query builder)

**To Reproduce**
1. Create a question with the query builder with a custom column
2. Aggregate some data, group it by the custom column (e.g. Sum grouped by custom column)
3. Do another aggregation below it (e.g. Average of the previous sum)
4. Click "Visualize". The following error message appears:
`400 Bad Request POST https://www.googleapis.com/bigquery/... { "code" : 400, "errors" : [ { "domain" : "global", "location" : "q", "locationType" : "parameter", "message" : "SELECT list expression references `table`.column which is neither grouped nor aggregated at [2:83]", "reason" : "invalidQuery" } ], "message" : "SELECT list expression references `table`.column which is neither grouped nor aggregated at [2:83]", "status" : "INVALID_ARGUMENT" }`

**Expected behavior**
The result of the question should be displayed properly when clicking "Visualize", without any error message.

**Information about your Metabase Installation:**
- Your browser and the version: Firefox 104.0.1 (64-bit)
- Your operating system: Windows 11
- Your databases: BigQuery
- Metabase version: v0.44.0
- Metabase hosting environment: Kubernetes with Docker image :  'metabase/metabase:v0.44.0 on a public cloud (scaleway.fr)
- Metabase internal database: H2

**Severity**
Prevents me from doing some very basic analytics that the company expects to have.

**Additional context**
Possibly related, but if I try to do the first aggregation only and then save it as a new question, it runs fine. However, if I then create a new question based on that question and try to visualize it, I get an error message similar to the one above ("neither grouped nor aggregated"), even if the question amounts to visualizing the raw data.

**Comment by flamber** [comment] 2022-09-05 14:02
Hi @BertrandToulas 
I cannot reproduce with the steps you have provided, and without the full stacktrace error, then it's difficult to tell how you have constructed the query.
I'm guessing that you are seeing #23862, which has been fixed in 0.44.1: https://github.com/metabase/metabase/releases/latest

**Comment by BertrandToulas** [comment] 2022-09-05 14:46
> 

Hi @flamber . I hadn't seen issue #23862 actually, cheers! This sounds like it should at the very least fix the issue I mentioned in Additional Context (though the error message is different). Unfortunately I can't upgrade our installation myself, and I need to wait 2 more weeks before the admin who handles upgrades can do it, so I won't know if 0.44.1 fixes the issue until then.

I'm not used to doing bug reports on GitHub yet. How should I go about getting the full stacktrace error?

**Comment by flamber** [comment] 2022-09-05 14:55
@BertrandToulas Every database generates different errors. You can find full stacktrace by going to Admin > Troubleshooting > Logs.
If you can reproduce issues with the Sample Database, then it makes it a lot easier for everyone to verify.
Closing, since I'm quite sure it's #23862

**Closed by flamber** 2022-09-05 14:55 UTC
Labels: Type:Bug, .Needs Triage

**Comment by BertrandToulas** [comment] 2022-09-06 09:19
> 

Reopening this issue since I've managed to get a hold of the full stacktrace (see attached). However, like you, I haven't been able to reproduce the error via the sample database. I think it's unrelated to #23862 after all, but I'm unclear what's wrong, or if it has to do with Metabase or our particular setup. Any help appreciated!
[metabase.log](https://github.com/metabase/metabase/files/9495199/metabase.log)

**Comment by flamber** [comment] 2022-09-06 09:47
@BertrandToulas If you follow the steps in #23862 using `case` in the Custom Expression, then you can reproduce, but not on 44.1+

**Comment by BertrandToulas** [comment] 2022-09-06 09:52
@flamber I've managed to reproduce #23862 using those steps earlier, but the error message I've been getting with my database seems different altogether. I'm referring specifically to the part that says `SELECT list expression references table.column which is neither grouped nor aggregated at [2:83]` in my case. Do you think it's the same issue regardless?

**Comment by BertrandToulas** [comment] 2022-09-06 10:16
@flamber Gotcha! Will update whenever possible. Fingers crossed, and thank you again!
