### ISSUE TITLE
When joining, the Raw Data selection shouldn't make me pick the database I'm using again

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#20406] opened 2022-02-10 00:18 UTC
1. Make sure your instance has at least one modal in it so that you'll see the alternate data picker
2. Start a new notebook question
3. Pick Orders as your starting table
4. And a Join step
5. When the popup appears to allow you to select the table/data you want to join with, pretend you want to join to a saved question rather than another raw table, and so click the back button in the popup
6. Notice that you go to the step that shows you databases instead of the initial state of the popover, which only shows the sample database since you can only join to tables in the same database as your starting data — so this step feels nonsensical
7. Click back again to get to the initial state of the popover with the 3 choices
8. Then click raw data again and see that yet again you're supposed to choose the only valid database: the sample database

Video with sound

https://user-images.githubusercontent.com/1447303/168582121-a745bc4c-2704-4077-a1da-fa38e4ee3a42.mp4

We should skip that database selection step in this scenario since you can only ever choose the database that your initial data uses.

**Comment by nemanjaglumac** [comment] 2024-07-02 12:34
The repro is not possible anymore because we overhauled the data picker component.
I'm closing this as "unable to reproduce".

**Closed by nemanjaglumac** 2024-07-02 12:34 UTC
Labels: Type:Bug, Priority:P3, .Unable to Reproduce, Querying/Notebook, .Regression, .Team/QueryingComponents
