### ISSUE TITLE
Tooltip in bar graph clipping with taller bars

### ISSUE THREAD

**Issue by netvinod** [metabase/metabase#15390] opened 2021-03-30 05:21 UTC
**Describe the bug**
When bar chart contains taller bars, tooltip is getting cropped. 
The tool tip must automatically change indirection so that it fits within the browser screen.

Refer screenshot

**To Reproduce**
1. Click "Ask a Question"
2. Select "Simple Question"
3. Select "Sample Dataset"
4. Select "Orders"
5. Select "Visualization"->Bar graph
6. Select "CREATED_AT" as X Axis and "TOTAL" as Y Axis
7. Hover over some values above say 140.
8. The tooltip that shows all the variable values at that point is clipped

**Expected behavior**
The tooltip should automatically detect that its is going out of bounds from the UI and adjust accordigly (say wrap or show up below or the sides)

**Screenshots**

![image](https://user-images.githubusercontent.com/5174331/112937858-115d5680-9146-11eb-84a9-2456e30594a2.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.63",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "5.4.0-1030-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```
**Severity**
Currently there is no workaround available. Hence to see the variable at a specific points for a table with large number of features is cumbersome, and end up having to refer the actual data each time.
Medium severity

**Comment by flamber** [comment] 2021-03-30 09:40
Cannot reproduce latest release 0.38.2 - duplicate of #5176
![image](https://user-images.githubusercontent.com/1447303/112968478-a19e9a00-914c-11eb-9712-13003958e769.png)

**Closed by flamber** 2021-03-30 09:40 UTC
Labels: .Needs Triage, Type:Bug
