### ISSUE TITLE
csv download does not apply filters

### ISSUE THREAD

**Issue by samiyabroudi** [metabase/metabase#3756] opened 2016-11-14 15:35 UTC
Hello!

I have a nice question written and I applied a numeric filter. When I download the csv it's not giving me the table that I'm looking at in Metabase but rather the table that is outputted when no filters are applied.

Thanks!

------
Before filing an issue we'd appreciate it if you could take a moment to ensure
there isn't already an open issue or pull-request.
-----

### Database support
If there's an exisiting issue, please add a +1 in the comments as we
prioritize drivers by the level of support. Otherwise, please include the name
of the database and the version.

### Feature requests and proposals
We're excited to hear how we can make Metabase better. Please add as much detail
as you can on your use case.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

- *Repeatable steps to reproduce the issue*

Thanks for being part of the Metabase project!
-------

**Comment by salsakran** [comment] 2016-11-14 19:36
this is a dupe of #3695

**Closed by salsakran** 2016-11-14 19:36 UTC
Labels: Bug, Duplicate
