### ISSUE TITLE
MySQL now() function seems inconsistent

### ISSUE THREAD

**Issue by ipeevski** [metabase/metabase#6861] opened 2018-02-05 23:01 UTC
For some reason, when using now() in metabase queries, it gives different result than when the same query is run on the database directly.

It looks like it's an issue with timezones (for some reason it looks like now() is evaluated in the browser or metabase timezone, while the curdate() is evaluated in the server's timezone)

Steps to reproduce:
- Browser timezone ACDT
- Metabase timezone ACDT
- MySQL server timezone GMT
- Create a new SQL question: `select now(), curdate()` (it has to be run in ACDT morning time to replicate the results)
- The result is `Tuesday, February 6, 2018 9:25 AM, Monday, February 5, 2018 12:00 AM`
- Expected result is `Tuesday, February 5, 2018 10:55 PM, Monday, February 5, 2018 12:00 AM` (that's what I get when I run the same SQL statement in MySQL)

Environment:
- Your browser and the version: Chrome 64
- Your operating system: Ubuntu
- Your databases: MariaDB
- Metabase version: 27.1
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Comment by cyberhorse** [comment] 2018-02-05 23:18
Ok, I found some clues as to what is happening. It looks like the cause is that the mysql timezone data didn't exist on the server. Because of that, it looks like when metabase passes the configured timezone (Australia/Adelaide in my case), it would get ignored and continue to operate in GMT. That explains why curdate() is returning the wrong date. After fixing the timezone info in the MySQL server, things work as expected - curdate() and now() both report my local date/time (as configured in metabase).

Still don't understand why now() magically worked in the correct timezone before?!?!

To populate the timezone data, you can do something similar to this:
`mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql`

**Comment by salsakran** [comment] 2018-02-15 21:58
Ironically, I think it's because we've been fixing timezone bugs and there are fewer places where we set arbitrary timezones. We used to inadvertently (and incorrectly) re-cast some dates with the server timezone, which I think masked the underlying problem you found (that the timezone data wasn't on the mysql server). 

I'm going to close this as you seem to have gotten things working again. Feel free to re-open if I there's another problem.

**Closed by salsakran** 2018-02-15 21:58 UTC
Labels: Timezones/Calendars

**Comment by ipeevski** [comment] 2018-02-15 22:27
Well, it would be good for curdate() and now() to be consistent even on a misconfigured server ... not for my sake, but for someone else that's bashing their head against a wall one day :)
