### ISSUE TITLE
Ability for a Dashboard to be Public/Shareable?

### ISSUE THREAD

**Issue by orware** [metabase/metabase#4368] opened 2017-02-13 00:04 UTC
### Feature requests and proposals

This also hasn't seemed to be asked so far, but it'd be nice to be able to share a dashboard publicly and have some options surrounding that (allow for auto refreshing to be turned on, caching the results, maybe allowing for fixed snapshots of the data to take place on a schedule, and allow users to go through those if they wish, etc.).

**Comment by camsaul** [comment] 2017-02-13 18:09
Duplicate of #3681. @orware we're planning on shipping this feature in our upcoming release.

**Closed by camsaul** 2017-02-13 18:09 UTC
Labels: Duplicate
