### ISSUE TITLE
Version 0.35 regression : column not found error after custom column

### ISSUE THREAD

**Issue by Xlagrap** [metabase/metabase#12243] opened 2020-04-02 07:06 UTC
**Describe the bug**
When creating a question with a summurize and a Custom Column based on the summurize the error "column not found" appears

**To Reproduce**
you just have to create a query in 0.35.0 or 0.35-RC2 like this one to reproduce the problem (the same query works in 0.34.3 :

![78033204-59e10900-7366-11ea-91eb-2b3f854b9e3e](https://user-images.githubusercontent.com/19491368/78220029-0d5e1080-74c1-11ea-866a-a6fcf843d34f.jpg)

![78033217-5e0d2680-7366-11ea-98ef-560131bb5299](https://user-images.githubusercontent.com/19491368/78220039-10f19780-74c1-11ea-961e-4442567674ee.jpg)

Thanks

**Comment by sbelak** [comment] 2020-04-03 16:40
It seems this is actually a front-end error -- the generated MBQL query is wrong, instead of `[:field-literal "expression" :type/Float]`, it should have been `[:field-literal "sum" :type/Float]`

**Comment by tlrobinson** [comment] 2020-04-03 19:59
I believe this may have been fixed in 0.35.1

**Comment by Xlagrap** [comment] 2020-04-03 20:35
@tlrobinson is right the issue about he aggregation's column name seams to be resolved but I the query is still in error.

**Comment by sbelak** [comment] 2020-04-13 18:16
Likely same root cause as #12252

**Comment by sbelak** [comment] 2020-04-20 18:50
Fixed in #12328

**Closed by sbelak** 2020-04-20 18:50 UTC
Labels: Priority:P2, Querying/Notebook, Querying/Processor, Type:Bug
