### ISSUE TITLE
Date Label Always Lagged a Month

### ISSUE THREAD

**Issue by ans-4175** [metabase/metabase#8639] opened 2018-10-05 14:26 UTC
### Bugs
Hey guys, I had trouble presenting data because of confusing label.
I filtered data within 3 months, but unfortunately why
<img width="1241" alt="screen shot 2018-10-05 at 21 17 00" src="https://user-images.githubusercontent.com/3961872/46540993-07479d80-c8e5-11e8-9850-bfc50941b9af.png">

As you can see, I filtered from July-September, but bar stacked on June-August.

Any ideas?
- Your browser and the version: (Google Chrome is up to date
Version 69.0.3497.100 (Official Build) (64-bit))
- Your operating system: (OS X 10.14)
- Your databases: (Big Query…)
- Metabase version: (0.30.4)
- Metabase hosting environment: (Linux/Ubuntu)
- Metabase internal database: (MySQL)

- *Repeatable steps to reproduce the issue*
Just look at my screenshot of UI builder

**Comment by MarkRx** [comment] 2018-10-08 22:02
I think this is #5246. There is a open PR to fix it - #7247

**Comment by mazameli** [comment] 2019-09-30 21:45
Closing as a duplicate of #5246, which we're looking into.

**Closed by mazameli** 2019-09-30 21:45 UTC
Labels: Duplicate, Priority:P2, Timezones/Calendars, Type:Bug, Visualization/
