### ISSUE TITLE
[`result_metadata`] Auto-binning on number field is different for SQL than it is for QB

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16670] opened 2021-06-18 11:56 UTC
As part of on ongoing process of documenting and covering binning issues (#16387), I noticed a few irregularities that are not strictly bugs, but definitely feel weird.

Auto binning on the number field is different (granularity) than on any other question/table.

#### Total, Auto binned

Orders table saved as a question
![image](https://user-images.githubusercontent.com/31325167/122556577-fbbc4680-d03b-11eb-9ea8-06d89d9d8dba.png)

vs

SQL (`select * from ORDERS`) saved as a question
![image](https://user-images.githubusercontent.com/31325167/122557035-869d4100-d03c-11eb-85f8-27e69f12b203.png)

Note, this "auto binning" works **only** when one clicks directly on the `TOTAL`, without explicitly choosing the "Auto bin" from the popover. Choosing **any** value from the popover will result in the failing query, which is covered by tests in #16660.

OTOH, it doesn't matter whether one chooses explicit or implicit "Auto bin" for table/QB question.

**Comment by flamber** [comment] 2021-06-18 12:55
See https://github.com/metabase/metabase/issues/16671#issuecomment-864015639

**Comment by kamilmielnik** [comment] 2023-11-08 11:50
Cannot reproduce, I tried `0.34.3` (auto-binning crashes visualization there), `0.36.0`, `0.38.0`, `0.39.0`, `0.39.4`, `0.40.0`, `0.45.1` & `master` ([d35c779](https://github.com/metabase/metabase/commit/d35c779976ae6bd79369e9cc6bec8540908f37d2)).

**Comment by uladzimirdev** [comment] 2023-11-08 15:39
I was able to reproduce it on 0.39.5 and it's fixed on 0.40.8 

Most likely this is a fix https://github.com/metabase/metabase/pull/17960, so we have a test already

**Closed by uladzimirdev** 2023-11-08 15:39 UTC
Labels: Type:Bug, Priority:P3, Querying/Native, Querying/Nested Queries, .Backend, .Reproduced, .Wanted: MLv2
