### ISSUE TITLE
When visualization returns `null` (No results), then UI becomes broken

### ISSUE THREAD

**Issue by epaolillo** [metabase/metabase#13801] opened 2020-11-16 04:35 UTC
If a question return 0, stuck spinning and all nexts question in same dashboard too.
From console all request to card there result correct (all request response 200  and content if exists).
No associate JS errors shows in console.

To Reproduce:
1. Create a Dashboard
2. Put 3 questions. First one response non zero value ie: 5, the next question response 0. the next question (top to bottom, left to right) return non zero ie: 6.
3. Shows first question ok, next spinning stuck, next spinning stuck.

1. First question return 5
2. Second question return 0
3 Third question return 6

![Selección_551](https://user-images.githubusercontent.com/2317905/99213345-2abfc080-27ac-11eb-875d-a88cd672f199.png)

{
  "browser-info": {
    "language": "es-ES",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_252-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_252",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.252-b09",
    "os.name": "Linux",
    "os.version": "4.14.181-108.257.amzn1.x86_64",
    "user.language": "es",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "googleanalytics",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.32-0ubuntu0.18.04.1"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.37.2-SNAPSHOT",
      "date": "2020-11-12",
      "branch": "?",
      "hash": "ba57ab6"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}

Severity
Is Blocking

**Comment by flamber** [comment] 2020-11-16 11:39
Steps to reproduce (might have to do everything in 0.37.0, since UI will brake in 0.37.1):
1. Native question - `SELECT null` - save as "Q1"
2. Native question - `SELECT 0` - save as "Q2"
3. Add to dashboard, where "Q1" is the first card, "Q2" is the second card - save dashboard
4. Refresh dashboard

How it looks in 0.37.0.2:
![image](https://user-images.githubusercontent.com/1447303/99248124-4658b480-2808-11eb-8a83-87586cf7fbb3.png)
Regression in 0.37.1:
![image](https://user-images.githubusercontent.com/1447303/99248184-58d2ee00-2808-11eb-82b7-1c15ca2f65a9.png)

**Comment by paulrosenzweig** [comment] 2020-11-16 18:57
Closed by #13808

**Closed by paulrosenzweig** 2020-11-16 18:58 UTC
Labels: .Regression, Priority:P0, Type:Bug
