### ISSUE TITLE
MongoDB - Certain tables will cause NullPointerException when attempting to sync fields.

### ISSUE THREAD

**Issue by jontsai** [metabase/metabase#6975] opened 2018-02-19 03:41 UTC
Certain tables will cause a `NullPointerException when attempting to sync fields.

Metabase v0.28.1 (AWS + Docker)
MongoDB v3.4.13 (MongoDB Atlas M10)

More details in the discussion forum here: 

http://discourse.metabase.com/t/when-asking-questions-some-tables-return-every-field-is-hidden-right-now/2634/8

One thing that I noticed: On my `customer_address` table, it used to sync properly, and then I added a `latitude` and `longitude` field, and then it stopped syncing. It could be something else as well, but that's just what I noticed.

(I did check for other issues, and I think this was previously not reported).

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jornh** [comment] 2018-02-19 13:06
> One thing that I noticed: On my customer_address table, it used to sync properly, and then I added a latitude and longitude field, and then it stopped syncing. It could be something else as well, but that's just what I noticed.

Good observation! Can you share the specifics of how the schema for the table looked before/after? (essentially get it down to that you create a "[MCVE](https://stackoverflow.com/help/mcve)" - Minimal, Complete, and Verifiable Example) for the devs to be able to reproduce 👍

**Comment by zuf** [comment] 2018-02-21 10:34
I have this issue with this one object in collection:

```json
{
  "_id": {
    "$oid": "595d329a7982e21fab85e84d"
  },
  "title": "test",
  "link": "/test",
  "author": "test",
  "meta": [
    {
      "name": "test",
      "val": "test"
    },
    {
      "name": "x",
      "val": "z"
    }
  ],
  "body": [
    {
      "text": "123"
    },
    {
      "text": "456"
    },
    {
      "img": "http:/example.com/url/to/img.jpg",
      "caption": "",
      "gallery": ""
    }
  ],
  "cover": "http:/example.com/url/to/cover.jpg",
  "status": null
}```

mongodump: https://www.dropbox.com/s/fmgnii9ydidga9p/dump.tar.gz?dl=0#

**Comment by aviggiano** [comment] 2018-03-28 16:03
Hey, did anyone on the metabase team have time to review this? I have a feeling that this should be a simple fix, but I can't dig any deeper because I don't know Clojure :slightly_frowning_face:

**Comment by VikramTiwari** [comment] 2018-03-28 16:08
Might be same issue: https://github.com/metabase/metabase/issues/7191 that's still happening in 0.28.3 @camsaul @salsakran

**Comment by aviggiano** [comment] 2018-03-28 16:14
Yes it seems to be the same issue (the stack trace shows a problem on the same line)

**Comment by wxqp** [comment] 2018-03-28 17:16
So, what it is the solution?

**Comment by aviggiano** [comment] 2018-03-29 04:07
Ok, so this is definitely related to fields with `null` values, since I did an ugly hack to sync my table and it worked. 

What I did was to basically set 100% of the document values (those which were `null`) to something, like a placeholder, then to trigger the metabase `sync_schema`, then to revert back the placeholder to `null`.

**DO THIS AT YOUR OWN RISK**

```javascript
// mongo shell

var database = db.my_database

// this array must contain all fields of your collection schema
var updates = [
      {query: {'name': {$eq: null}}, update: {$set: {'name': 'N/A'}}},
      {query: {'price_usd': {$eq: null}}, update: {$set: {'price_usd': -9999999.0}}},
      {query: {'total_supply': {$eq: null}}, update: {$set: {'total_supply': -9999999.0}}},
]

updates.forEach(obj => database.update(obj.query, obj.update, {multi:true}))
```

```bash
# curl or metabase admin
# trigger the sync_schema endpoint manually or via cURL

curl '.../api/database/.../sync_schema' ...headers...  --data-binary '{}' --compressed
```

```javascript
// mongo shell

// this array must contain all fields of your collection schema
var rollbacks = [
      {query: {'name': {$eq: 'N/A'}}, update: {$set: {'name': null}}},
      {query: {'price_usd': {$eq: -9999999.0}}, update: {$set: {'price_usd': null}}},
      {query: {'total_supply': {$eq: -9999999.0}}, update: {$set: {'total_supply': null}}},
]

rollbacks.forEach(obj => database.update(obj.query, obj.update, {multi:true}))
```

**Comment by johngrogg** [comment] 2018-04-09 23:31
Encountered this today, but can't do the manual workaround as suggested (due to working against production data).

There wouldn't be a way to manually provide a schema for use when the DB type is a schema-less datastore?

**Comment by 0xicl33n** [comment] 2018-06-10 23:30
any updates on this? i really want to use metabase but the workaround would break production data...

**Comment by vietvudanh** [comment] 2018-06-13 08:28
Any update? It seems @aviggiano was right on this, since I just add a dumb collection with no null value and it's fine.

**Comment by gkoberger** [comment] 2018-06-24 20:08
We're also waiting on a fix for this. Mongo being schema-less means we have a lot of documents missing certain keys... and I'm worried about messing with production data just to make this work!

**Comment by tschut** [comment] 2018-06-27 06:59
Ran into the same issue yesterday. I'm running metabase on Heroku.

Stacktrace:
```
2018-06-27T06:32:11.376252+00:00 app[web.1]: 06-27 06:32:11 [1mDEBUG metabase.middleware[0m :: [32mPOST /api/database/38/sync_schema 200 (5 ms) (1 DB calls). Jetty threads: 8/50 (6 busy, 5 idle, 0 queued)[0m
2018-06-27T06:32:11.384665+00:00 app[web.1]: 06-27 06:32:11 [1mDEBUG sync.util[0m :: Sync operations in flight: {:sync-metadata #{38}}
2018-06-27T06:32:11.385695+00:00 app[web.1]: 06-27 06:32:11 [1mINFO sync.util[0m :: [35mSTARTING: Sync metadata for mongo Database 38 'ProductFeeder'[0m
2018-06-27T06:32:16.292297+00:00 app[web.1]: 06-27 06:32:16 [1mERROR sync.util[0m :: [31mError syncing fields for Table 49 'catalog': class java.lang.NullPointerException
2018-06-27T06:32:16.292316+00:00 app[web.1]: ("driver.mongo$describe_table_field.invokeStatic(mongo.clj:123)"
2018-06-27T06:32:16.292317+00:00 app[web.1]:  "driver.mongo$describe_table_field.invoke(mongo.clj:120)"
2018-06-27T06:32:16.292319+00:00 app[web.1]:  "driver.mongo$describe_table$f__53055__auto____53941$iter__53942__53946$fn__53947.invoke(mongo.clj:165)"
2018-06-27T06:32:16.292321+00:00 app[web.1]:  "driver.mongo$describe_table$f__53055__auto____53941.invoke(mongo.clj:164)"
2018-06-27T06:32:16.292323+00:00 app[web.1]:  "driver.mongo$describe_table.invokeStatic(mongo.clj:160)"
2018-06-27T06:32:16.292324+00:00 app[web.1]:  "driver.mongo$describe_table.invoke(mongo.clj:159)"
2018-06-27T06:32:16.292326+00:00 app[web.1]:  "driver$fn__25804$G__25636__25813.invoke(driver.clj:61)"
2018-06-27T06:32:16.292328+00:00 app[web.1]:  "sync.fetch_metadata$fn__34289$table_metadata__34294$fn__34295.invoke(fetch_metadata.clj:18)"
2018-06-27T06:32:16.292329+00:00 app[web.1]:  "sync.fetch_metadata$fn__34289$table_metadata__34294.invoke(fetch_metadata.clj:15)"
2018-06-27T06:32:16.292331+00:00 app[web.1]:  "sync.sync_metadata.fields$fn__34850$db_metadata__34855$fn__34856.invoke(fields.clj:294)"
2018-06-27T06:32:16.292332+00:00 app[web.1]:  "sync.sync_metadata.fields$fn__34850$db_metadata__34855.invoke(fields.clj:290)"
2018-06-27T06:32:16.292334+00:00 app[web.1]:  "sync.sync_metadata.fields$fn__34878$sync_fields_for_table_BANG___34887$fn__34890$fn__34891.invoke(fields.clj:307)"
2018-06-27T06:32:16.292335+00:00 app[web.1]:  "sync.util$do_with_error_handling.invokeStatic(util.clj:124)"
2018-06-27T06:32:16.292336+00:00 app[web.1]:  "sync.util$do_with_error_handling.invoke(util.clj:119)"
2018-06-27T06:32:16.292338+00:00 app[web.1]:  "sync.sync_metadata.fields$fn__34878$sync_fields_for_table_BANG___34887$fn__34890.invoke(fields.clj:306)"
2018-06-27T06:32:16.292339+00:00 app[web.1]:  "sync.sync_metadata.fields$fn__34878$sync_fields_for_table_BANG___34887.invoke(fields.clj:301)"
2018-06-27T06:32:16.292341+00:00 app[web.1]:  "sync.sync_metadata.fields$fn__34916$sync_fields_BANG___34921$fn__34922.invoke(fields.clj:318)"
2018-06-27T06:32:16.292342+00:00 app[web.1]:  "sync.sync_metadata.fields$fn__34916$sync_fields_BANG___34921.invoke(fields.clj:314)"
2018-06-27T06:32:16.292344+00:00 app[web.1]:  "sync.sync_metadata$fn__35485$sync_db_metadata_BANG___35490$fn__35491$fn__35492.invoke(sync_metadata.clj:28)"
2018-06-27T06:32:16.292345+00:00 app[web.1]:  "sync.util$do_with_error_handling.invokeStatic(util.clj:124)"
2018-06-27T06:32:16.292346+00:00 app[web.1]:  "sync.util$do_with_error_handling.invoke(util.clj:119)"
2018-06-27T06:32:16.292348+00:00 app[web.1]:  "sync.util$do_with_error_handling.invokeStatic(util.clj:122)"
2018-06-27T06:32:16.292349+00:00 app[web.1]:  "sync.util$do_with_error_handling.invoke(util.clj:119)"
2018-06-27T06:32:16.292351+00:00 app[web.1]:  "driver.mongo$sync_in_context$f__53055__auto____53845.invoke(mongo.clj:70)"
2018-06-27T06:32:16.292352+00:00 app[web.1]:  "driver.mongo.util$_with_mongo_connection$fn__53048.invoke(util.clj:116)"
2018-06-27T06:32:16.292354+00:00 app[web.1]:  "util.ssh$with_ssh_tunnel_STAR_.invokeStatic(ssh.clj:106)"
2018-06-27T06:32:16.292355+00:00 app[web.1]:  "util.ssh$with_ssh_tunnel_STAR_.invoke(ssh.clj:91)"
2018-06-27T06:32:16.292356+00:00 app[web.1]:  "driver.mongo.util$_with_mongo_connection.invokeStatic(util.clj:95)"
2018-06-27T06:32:16.292358+00:00 app[web.1]:  "driver.mongo.util$_with_mongo_connection.invoke(util.clj:90)"
2018-06-27T06:32:16.292359+00:00 app[web.1]:  "driver.mongo$sync_in_context.invokeStatic(mongo.clj:69)"
2018-06-27T06:32:16.292360+00:00 app[web.1]:  "driver.mongo$sync_in_context.invoke(mongo.clj:68)"
2018-06-27T06:32:16.292362+00:00 app[web.1]:  "driver$fn__25819$G__25626__25828.invoke(driver.clj:61)"
2018-06-27T06:32:16.292363+00:00 app[web.1]:  "sync.util$sync_in_context$fn__32553.invoke(util.clj:115)"
2018-06-27T06:32:16.292365+00:00 app[web.1]:  "sync.util$with_db_logging_disabled$fn__32550.invoke(util.clj:106)"
2018-06-27T06:32:16.292366+00:00 app[web.1]:  "sync.util$with_start_and_finish_logging$fn__32545.invoke(util.clj:92)"
2018-06-27T06:32:16.292367+00:00 app[web.1]:  "sync.util$with_sync_events$fn__32542.invoke(util.clj:75)"
2018-06-27T06:32:16.292369+00:00 app[web.1]:  "sync.util$with_duplicate_ops_prevented$fn__32533.invoke(util.clj:54)"
2018-06-27T06:32:16.292370+00:00 app[web.1]:  "sync.util$do_sync_operation.invokeStatic(util.clj:142)"
2018-06-27T06:32:16.292371+00:00 app[web.1]:  "sync.util$do_sync_operation.invoke(util.clj:139)"
2018-06-27T06:32:16.292372+00:00 app[web.1]:  "sync.sync_metadata$fn__35485$sync_db_metadata_BANG___35490$fn__35491.invoke(sync_metadata.clj:23)"
2018-06-27T06:32:16.292374+00:00 app[web.1]:  "sync.sync_metadata$fn__35485$sync_db_metadata_BANG___35490.invoke(sync_metadata.clj:20)"
2018-06-27T06:32:16.292375+00:00 app[web.1]:  "api.database$fn__42297$fn__42298$fn__42299.invoke(database.clj:510)")
2018-06-27T06:32:16.292377+00:00 app[web.1]: [0m
2018-06-27T06:32:16.324054+00:00 app[web.1]: 06-27 06:32:16 [1mINFO sync.util[0m :: [35mFINISHED: Sync metadata for mongo Database 38 'ProductFeeder' (5 s)[0m
```

**Comment by aledrjones** [comment] 2018-07-09 07:28
Would be great if we could get a fix for this as most of our "interesting" data is in Mongo.  Aurora works fine.

I would think its a simple fix to treat the schema as a union of all discovered fields, and treat any docs where they don't exist as having a null value for that field.

**Comment by Coolomina** [comment] 2018-07-09 09:09
Also playing with production data here. I'd be great if we could have this soon :smiley:

**Comment by nunojsferreira** [comment] 2018-07-13 13:50
I am experiencing the same. Would be great to see it fixed.

**Comment by jsfrocha** [comment] 2018-07-13 16:15
Still happening on the following setup:

Metabase v0.29.3 (EB)
MongoDB Atlas M10 (3.6.5)

**Closed** 2018-07-16 19:38 UTC
Labels: Bug, Database/Mongo, Priority/P1
