### ISSUE TITLE
Missing fields when using a native MongoDB query

### ISSUE THREAD

**Issue by manishrc** [metabase/metabase#13208] opened 2020-09-04 15:59 UTC
**Describe the bug**
Certain fields when selected using the UI appear in the results, but when the same question is converted to a Native query, some fields are missing.

The converted query appears correct and works as expected when used directly in the MongoDB console.

What's puzzling is that the same query works for other fields with the same pattern. 

### Example:

```javascript
[
  { "$project": { "a__name": "$a.name", "ps__name": "$ps.name" } }
]
```

Shows only "a__name" but not "ps__name" field in the result.

On modifying the above query to:

```
[
  { "$project": { "b__name": "$ps.name" } }
]
```

The result area says "Every field is hidden right now".

I checked to see if this field is hidden in the Data Model and it isn't. "a.name" is exactly the same as "ps.name" and so are "a" and "ps" fields.

I've been able to use a hack currently to make this work:

```javascript
[
  { "$project": { "a__name": "$a.name", "ps__name":  { "$concat": ["$ps.name", ""] }  } }
]
```

**Severity**
Blocking a few reports from being used.

**Metabase Diagnostic Info**

Metabase Version: 0.36.4

**Comment by flamber** [comment] 2020-09-04 16:12
Looks like a duplicate of #4946
Otherwise please provide more information about your schema - preferably with steps to reproduce.

**Comment by manishrc** [comment] 2020-09-04 17:54
@flamber I believe the issue I'm facing is the inverse of #4946, in that the UI works fine, but not the Native Query -- even the one generated by the UI.

I'll try to reproduce this outside of the project and steps.

**Comment by flamber** [comment] 2020-09-04 18:08
@manishrc True, I was just remembering the comment in the bottom from a couple of months ago.

**Comment by camsaul** [comment] 2022-12-14 20:47
This is due to the way we compile MongoDB queries. We generate some extra info (stored under the `:projections` key) when we compile the query and then do some sort of magic with this in `metabase.driver.mongo.execute` when we process the results. 

I'm not sure if this is what's happening or not, but I'm guessing that original generated `:projections` information is still present when we run the updated native version of the query, and in post-processing it's looking for columns that are no longer there and ignoring new ones.

Ideally I think we should try to figure out if we can do away with `:projections` altogether and generate what we want directly in the query with a final `$project` stage. If that can't be made to work, we should do something to make sure it doesn't get passed along when we convert the query to native, or just ignore it for native queries.

**Comment by metamben** [comment] 2023-01-04 21:18
One of the problem seems to be that for native queries we don't have the `projections` field. The general problem is of course that we want to determine the columns based on the first row returned which is obviously not enough for MongoDB.

A work-around could be using the `$project` stage (if any) to determine the columns. That way users can at least influence what columns are returned.

**Closed** 2023-01-06 14:43 UTC
Labels: Type:Bug, Database/Mongo, .Limitation, .Correctness, Querying/Native
