### ISSUE TITLE
Line Chart vs Table - different data ordering

### ISSUE THREAD

**Issue by Matiovsky** [metabase/metabase#7664] opened 2018-05-18 10:56 UTC
My setup:

- Your browser and the version: Firefox ESR 52.7.2 (64-bit)
- Your operating system: CentOS release 6.9 (Final)
- Your databases:  MySQL
- Metabase version: 0.29.3
- Metabase hosting environment: Linux/Debian 9.4
- Metabase internal database: MySQL

I have my data already ordered in correct way in my MySQL table.
SQL query in metabase looks like this:
`SELECT * FROM mastermind.v_tests_simulator_performance__xxxxxxx;`

This is exact order as it is in my database:
![screenshot-6](https://user-images.githubusercontent.com/6945043/40231235-978291b6-5a9a-11e8-845f-59cb93b4e490.png)

But line chart somehow reorder my data like this:
![3](https://user-images.githubusercontent.com/6945043/40231245-a23d8bb0-5a9a-11e8-9f46-c80881402dd2.png)

I would assume that order will be the same as in table (table is ordered by Build Number), but Line chart is ending with Build ID: 7.2.0-2000... instead of 7.2.0-2004...

Am I doing something nasty with using two columns as X-axis or is it bug?

Thanks

**Comment by salsakran** [comment] 2018-07-03 00:06
Hmmm. Check what scale the x-axis is using (i.e. click on "axes" above). I think what's happening is that we're finding a timestamp format, and dropping the `n.XXXXXX` portion. If you switch to ordinal I think it should sort properly.

**Comment by Matiovsky** [comment] 2018-07-04 14:35
I have this option greyed and I am not able to change it, but it looks like "Ordinal" is already there but data still in wrong order.
![ordinal](https://user-images.githubusercontent.com/6945043/42282794-f0a3f6fe-7fa7-11e8-965a-c15473378b4f.png)

**Comment by flamber** [comment] 2019-06-20 19:38
Hi @Matiovsky 
This looks like a duplicate of #6847, if you agree, then please close this issue and upvote the other :+1:

**Comment by flamber** [comment] 2020-05-30 18:08
Fixed in 0.33.1

**Closed by flamber** 2020-05-30 18:08 UTC
Labels: Visualization/, Visualization/Chart Settings
