### ISSUE TITLE
Cannot filter on UUID column unless it's a PK/FK

### ISSUE THREAD

**Issue by maximepvrt** [metabase/metabase#13294] opened 2020-09-22 15:35 UTC
impossible to check if a uuid column is empty with psql

![Capture d’écran 2020-09-22 à 17 31 43](https://user-images.githubusercontent.com/1840026/93904219-e955ec00-fcf9-11ea-80ac-728089459a5a.png)
![Capture d’écran 2020-09-22 à 17 31 54](https://user-images.githubusercontent.com/1840026/93904227-ebb84600-fcf9-11ea-8ae2-fead1eb1e063.png)

<details><summary>Full stacktrace</summary>

```
[da808c88-7732-4b00-bfda-aa0305dfb6d3] 2020-09-22T22:41:36+02:00 ERROR metabase.query-processor.middleware.catch-exceptions Erreur lors du traitement de la requête : null
{:database_id 2,
:started_at #t "2020-09-22T20:41:35.771665Z[UTC]",
:json_query
{:type "query", :query {:source-table 76, :filter ["is-empty" ["field-id" 1308]]}, :database 2, :parameters [], :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
:native nil,
:status :failed,
:class java.lang.IllegalArgumentException,
:stacktrace
["java.base/java.util.UUID.fromString(UUID.java:215)"
"--> driver.postgres$fn__73238.invokeStatic(postgres.clj:159)"
"driver.postgres$fn__73238.invoke(postgres.clj:154)"
"driver.sql.query_processor$fn__64820.invokeStatic(query_processor.clj:607)"
"driver.sql.query_processor$fn__64820.invoke(query_processor.clj:605)"
"driver.sql.query_processor$fn__64838.invokeStatic(query_processor.clj:619)"
"driver.sql.query_processor$fn__64838.invoke(query_processor.clj:617)"
"driver.sql.query_processor$fn__64850.invokeStatic(query_processor.clj:627)"
"driver.sql.query_processor$fn__64850.invoke(query_processor.clj:625)"
"driver.sql.query_processor$apply_top_level_clauses$fn__64956.invoke(query_processor.clj:788)"
"driver.sql.query_processor$apply_top_level_clauses.invokeStatic(query_processor.clj:786)"
"driver.sql.query_processor$apply_top_level_clauses.invoke(query_processor.clj:782)"
"driver.sql.query_processor$apply_clauses.invokeStatic(query_processor.clj:863)"
"driver.sql.query_processor$apply_clauses.invoke(query_processor.clj:848)"
"driver.sql.query_processor$fn__65033$build_honeysql_form__65038$fn__65042.invoke(query_processor.clj:868)"
"driver.sql.query_processor$fn__65033$build_honeysql_form__65038.invoke(query_processor.clj:865)"
"driver.sql.query_processor$mbql__GT_honeysql.invokeStatic(query_processor.clj:879)"
"driver.sql.query_processor$mbql__GT_honeysql.invoke(query_processor.clj:877)"
"driver.sql.query_processor$mbql__GT_native.invokeStatic(query_processor.clj:885)"
"driver.sql.query_processor$mbql__GT_native.invoke(query_processor.clj:881)"
"driver.sql$fn__73908.invokeStatic(sql.clj:40)"
"driver.sql$fn__73908.invoke(sql.clj:38)"
"query_processor.middleware.mbql_to_native$query__GT_native_form.invokeStatic(mbql_to_native.clj:15)"
"query_processor.middleware.mbql_to_native$query__GT_native_form.invoke(mbql_to_native.clj:10)"
"query_processor.middleware.mbql_to_native$mbql__GT_native$fn__45635.invoke(mbql_to_native.clj:23)"
"query_processor.middleware.check_features$check_features$fn__44911.invoke(check_features.clj:42)"
"query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__45800.invoke(optimize_datetime_filters.clj:133)"
"query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47328.invoke(wrap_value_literals.clj:137)"
"query_processor.middleware.annotate$add_column_info$fn__43532.invoke(annotate.clj:574)"
"query_processor.middleware.permissions$check_query_permissions$fn__44786.invoke(permissions.clj:64)"
"query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__46318.invoke(pre_alias_aggregations.clj:40)"
"query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__44984.invoke(cumulative_aggregations.clj:61)"
"query_processor.middleware.resolve_joins$resolve_joins$fn__46850.invoke(resolve_joins.clj:183)"
"query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39262.invoke(add_implicit_joins.clj:245)"
"query_processor.middleware.large_int_id$convert_id_to_string$fn__45596.invoke(large_int_id.clj:44)"
"query_processor.middleware.limit$limit$fn__45621.invoke(limit.clj:38)"
"query_processor.middleware.format_rows$format_rows$fn__45576.invoke(format_rows.clj:81)"
"query_processor.middleware.desugar$desugar$fn__45050.invoke(desugar.clj:22)"
"query_processor.middleware.binning$update_binning_strategy$fn__44076.invoke(binning.clj:229)"
"query_processor.middleware.resolve_fields$resolve_fields$fn__44592.invoke(resolve_fields.clj:24)"
"query_processor.middleware.add_dimension_projections$add_remapping$fn__38811.invoke(add_dimension_projections.clj:318)"
"query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39018.invoke(add_implicit_clauses.clj:141)"
"query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39411.invoke(add_source_metadata.clj:105)"
"query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__46515.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
"query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__43717.invoke(auto_bucket_datetimes.clj:125)"
"query_processor.middleware.resolve_source_table$resolve_source_tables$fn__44639.invoke(resolve_source_table.clj:46)"
"query_processor.middleware.parameters$substitute_parameters$fn__46300.invoke(parameters.clj:114)"
"query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__44691.invoke(resolve_referenced.clj:80)"
"query_processor.middleware.expand_macros$expand_macros$fn__45306.invoke(expand_macros.clj:158)"
"query_processor.middleware.add_timezone_info$add_timezone_info$fn__39442.invoke(add_timezone_info.clj:15)"
"query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47212.invoke(splice_params_in_response.clj:32)"
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526$fn__46530.invoke(resolve_database_and_driver.clj:33)"
"driver$do_with_driver.invokeStatic(driver.clj:61)"
"driver$do_with_driver.invoke(driver.clj:57)"
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526.invoke(resolve_database_and_driver.clj:27)"
"query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45524.invoke(fetch_source_query.clj:267)"
"query_processor.middleware.store$initialize_store$fn__47221$fn__47222.invoke(store.clj:11)"
"query_processor.store$do_with_store.invokeStatic(store.clj:46)"
"query_processor.store$do_with_store.invoke(store.clj:40)"
"query_processor.middleware.store$initialize_store$fn__47221.invoke(store.clj:10)"
"query_processor.middleware.cache$maybe_return_cached_results$fn__44568.invoke(cache.clj:209)"
"query_processor.middleware.validate$validate_query$fn__47230.invoke(validate.clj:10)"
"query_processor.middleware.normalize_query$normalize$fn__45648.invoke(normalize_query.clj:22)"
"query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39280.invoke(add_rows_truncated.clj:36)"
"query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47197.invoke(results_metadata.clj:147)"
"query_processor.middleware.constraints$add_default_userland_constraints$fn__44927.invoke(constraints.clj:42)"
"query_processor.middleware.process_userland_query$process_userland_query$fn__46389.invoke(process_userland_query.clj:136)"
"query_processor.middleware.catch_exceptions$catch_exceptions$fn__44870.invoke(catch_exceptions.clj:174)"
"query_processor.reducible$async_qp$qp_STAR___38074$thunk__38075.invoke(reducible.clj:101)"
"query_processor.reducible$async_qp$qp_STAR___38074.invoke(reducible.clj:107)"
"query_processor.reducible$sync_qp$qp_STAR___38083$fn__38086.invoke(reducible.clj:133)"
"query_processor.reducible$sync_qp$qp_STAR___38083.invoke(reducible.clj:132)"
"query_processor$process_userland_query.invokeStatic(query_processor.clj:215)"
"query_processor$process_userland_query.doInvoke(query_processor.clj:211)"
"query_processor$fn__47372$process_query_and_save_execution_BANG___47381$fn__47384.invoke(query_processor.clj:227)"
"query_processor$fn__47372$process_query_and_save_execution_BANG___47381.invoke(query_processor.clj:219)"
"query_processor$fn__47416$process_query_and_save_with_max_results_constraints_BANG___47425$fn__47428.invoke(query_processor.clj:239)"
"query_processor$fn__47416$process_query_and_save_with_max_results_constraints_BANG___47425.invoke(query_processor.clj:232)"
"api.dataset$fn__50707$fn__50710.invoke(dataset.clj:55)"
"query_processor.streaming$streaming_response_STAR_$fn__35496$fn__35497.invoke(streaming.clj:73)"
"query_processor.streaming$streaming_response_STAR_$fn__35496.invoke(streaming.clj:72)"
"async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
"async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
"async.streaming_response$do_f_async$fn__23282.invoke(streaming_response.clj:85)"],
:context :ad-hoc,
:error "Invalid UUID string: ",
:row_count 0,
:running_time 0,
:preprocessed
{:type :query,
:query
{:source-table 76,
:filter
[:or
[:= [:field-id 1308] [:value nil {:base_type :type/UUID, :special_type nil, :database_type "uuid", :name "id"}]]
[:= [:field-id 1308] [:value "" {:base_type :type/UUID, :special_type nil, :database_type "uuid", :name "id"}]]],
:fields
[[:field-id 1313]
[:datetime-field [:field-id 1307] :default]
[:datetime-field [:field-id 3128] :default]
[:field-id 1308]
[:field-id 1305]
[:field-id 1869]
[:field-id 1306]
[:field-id 1309]
[:field-id 1310]
[:field-id 1312]
[:datetime-field [:field-id 1311] :default]],
:limit 2000},
:database 2,
:middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
:info
{:executed-by 1,
:context :ad-hoc,
:nested? false,
:query-hash [-32, 15, -90, 75, -43, -122, 110, 18, 104, 28, -89, 34, -65, 37, -55, -97, 100, -20, -82, 108, -39, -75, 8, 29, 59, 82, 70, 44, -82, 61, -128, 21]},
:constraints {:max-results 10000, :max-results-bare-rows 2000}},
:data {:rows [], :cols []}}
```

</details>

```
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "13.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "13.0.2+8",
    "os.name": "Linux",
    "os.version": "5.8.1+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-09-15",
      "tag": "v0.36.6",
      "branch": "release-0.36.x",
      "hash": "cb258fb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2020-09-22 15:52
Hi @maximepvrt 
I cannot reproduce. Please provide sample table. And the full stacktrace from Admin > Troubleshooting > Logs.

**Comment by maximepvrt** [comment] 2020-09-22 20:44
<img width="1022" alt="Capture d’écran 2020-09-22 à 22 41 50" src="https://user-images.githubusercontent.com/1840026/93935618-34392900-fd25-11ea-9f8d-b6c4d0cc23ac.png">
<img width="803" alt="Capture d’écran 2020-09-22 à 22 42 04" src="https://user-images.githubusercontent.com/1840026/93935626-38654680-fd25-11ea-9fdd-586130559cff.png">


```
[da808c88-7732-4b00-bfda-aa0305dfb6d3] 2020-09-22T22:41:36+02:00 ERROR metabase.query-processor.middleware.catch-exceptions Erreur lors du traitement de la requête : null
{:database_id 2,
:started_at #t "2020-09-22T20:41:35.771665Z[UTC]",
:json_query
{:type "query", :query {:source-table 76, :filter ["is-empty" ["field-id" 1308]]}, :database 2, :parameters [], :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
:native nil,
:status :failed,
:class java.lang.IllegalArgumentException,
:stacktrace
["java.base/java.util.UUID.fromString(UUID.java:215)"
"--> driver.postgres$fn__73238.invokeStatic(postgres.clj:159)"
"driver.postgres$fn__73238.invoke(postgres.clj:154)"
"driver.sql.query_processor$fn__64820.invokeStatic(query_processor.clj:607)"
"driver.sql.query_processor$fn__64820.invoke(query_processor.clj:605)"
"driver.sql.query_processor$fn__64838.invokeStatic(query_processor.clj:619)"
"driver.sql.query_processor$fn__64838.invoke(query_processor.clj:617)"
"driver.sql.query_processor$fn__64850.invokeStatic(query_processor.clj:627)"
"driver.sql.query_processor$fn__64850.invoke(query_processor.clj:625)"
"driver.sql.query_processor$apply_top_level_clauses$fn__64956.invoke(query_processor.clj:788)"
"driver.sql.query_processor$apply_top_level_clauses.invokeStatic(query_processor.clj:786)"
"driver.sql.query_processor$apply_top_level_clauses.invoke(query_processor.clj:782)"
"driver.sql.query_processor$apply_clauses.invokeStatic(query_processor.clj:863)"
"driver.sql.query_processor$apply_clauses.invoke(query_processor.clj:848)"
"driver.sql.query_processor$fn__65033$build_honeysql_form__65038$fn__65042.invoke(query_processor.clj:868)"
"driver.sql.query_processor$fn__65033$build_honeysql_form__65038.invoke(query_processor.clj:865)"
"driver.sql.query_processor$mbql__GT_honeysql.invokeStatic(query_processor.clj:879)"
"driver.sql.query_processor$mbql__GT_honeysql.invoke(query_processor.clj:877)"
"driver.sql.query_processor$mbql__GT_native.invokeStatic(query_processor.clj:885)"
"driver.sql.query_processor$mbql__GT_native.invoke(query_processor.clj:881)"
"driver.sql$fn__73908.invokeStatic(sql.clj:40)"
"driver.sql$fn__73908.invoke(sql.clj:38)"
"query_processor.middleware.mbql_to_native$query__GT_native_form.invokeStatic(mbql_to_native.clj:15)"
"query_processor.middleware.mbql_to_native$query__GT_native_form.invoke(mbql_to_native.clj:10)"
"query_processor.middleware.mbql_to_native$mbql__GT_native$fn__45635.invoke(mbql_to_native.clj:23)"
"query_processor.middleware.check_features$check_features$fn__44911.invoke(check_features.clj:42)"
"query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__45800.invoke(optimize_datetime_filters.clj:133)"
"query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47328.invoke(wrap_value_literals.clj:137)"
"query_processor.middleware.annotate$add_column_info$fn__43532.invoke(annotate.clj:574)"
"query_processor.middleware.permissions$check_query_permissions$fn__44786.invoke(permissions.clj:64)"
"query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__46318.invoke(pre_alias_aggregations.clj:40)"
"query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__44984.invoke(cumulative_aggregations.clj:61)"
"query_processor.middleware.resolve_joins$resolve_joins$fn__46850.invoke(resolve_joins.clj:183)"
"query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39262.invoke(add_implicit_joins.clj:245)"
"query_processor.middleware.large_int_id$convert_id_to_string$fn__45596.invoke(large_int_id.clj:44)"
"query_processor.middleware.limit$limit$fn__45621.invoke(limit.clj:38)"
"query_processor.middleware.format_rows$format_rows$fn__45576.invoke(format_rows.clj:81)"
"query_processor.middleware.desugar$desugar$fn__45050.invoke(desugar.clj:22)"
"query_processor.middleware.binning$update_binning_strategy$fn__44076.invoke(binning.clj:229)"
"query_processor.middleware.resolve_fields$resolve_fields$fn__44592.invoke(resolve_fields.clj:24)"
"query_processor.middleware.add_dimension_projections$add_remapping$fn__38811.invoke(add_dimension_projections.clj:318)"
"query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39018.invoke(add_implicit_clauses.clj:141)"
"query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39411.invoke(add_source_metadata.clj:105)"
"query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__46515.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
"query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__43717.invoke(auto_bucket_datetimes.clj:125)"
"query_processor.middleware.resolve_source_table$resolve_source_tables$fn__44639.invoke(resolve_source_table.clj:46)"
"query_processor.middleware.parameters$substitute_parameters$fn__46300.invoke(parameters.clj:114)"
"query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__44691.invoke(resolve_referenced.clj:80)"
"query_processor.middleware.expand_macros$expand_macros$fn__45306.invoke(expand_macros.clj:158)"
"query_processor.middleware.add_timezone_info$add_timezone_info$fn__39442.invoke(add_timezone_info.clj:15)"
"query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47212.invoke(splice_params_in_response.clj:32)"
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526$fn__46530.invoke(resolve_database_and_driver.clj:33)"
"driver$do_with_driver.invokeStatic(driver.clj:61)"
"driver$do_with_driver.invoke(driver.clj:57)"
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526.invoke(resolve_database_and_driver.clj:27)"
"query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45524.invoke(fetch_source_query.clj:267)"
"query_processor.middleware.store$initialize_store$fn__47221$fn__47222.invoke(store.clj:11)"
"query_processor.store$do_with_store.invokeStatic(store.clj:46)"
"query_processor.store$do_with_store.invoke(store.clj:40)"
"query_processor.middleware.store$initialize_store$fn__47221.invoke(store.clj:10)"
"query_processor.middleware.cache$maybe_return_cached_results$fn__44568.invoke(cache.clj:209)"
"query_processor.middleware.validate$validate_query$fn__47230.invoke(validate.clj:10)"
"query_processor.middleware.normalize_query$normalize$fn__45648.invoke(normalize_query.clj:22)"
"query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39280.invoke(add_rows_truncated.clj:36)"
"query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47197.invoke(results_metadata.clj:147)"
"query_processor.middleware.constraints$add_default_userland_constraints$fn__44927.invoke(constraints.clj:42)"
"query_processor.middleware.process_userland_query$process_userland_query$fn__46389.invoke(process_userland_query.clj:136)"
"query_processor.middleware.catch_exceptions$catch_exceptions$fn__44870.invoke(catch_exceptions.clj:174)"
"query_processor.reducible$async_qp$qp_STAR___38074$thunk__38075.invoke(reducible.clj:101)"
"query_processor.reducible$async_qp$qp_STAR___38074.invoke(reducible.clj:107)"
"query_processor.reducible$sync_qp$qp_STAR___38083$fn__38086.invoke(reducible.clj:133)"
"query_processor.reducible$sync_qp$qp_STAR___38083.invoke(reducible.clj:132)"
"query_processor$process_userland_query.invokeStatic(query_processor.clj:215)"
"query_processor$process_userland_query.doInvoke(query_processor.clj:211)"
"query_processor$fn__47372$process_query_and_save_execution_BANG___47381$fn__47384.invoke(query_processor.clj:227)"
"query_processor$fn__47372$process_query_and_save_execution_BANG___47381.invoke(query_processor.clj:219)"
"query_processor$fn__47416$process_query_and_save_with_max_results_constraints_BANG___47425$fn__47428.invoke(query_processor.clj:239)"
"query_processor$fn__47416$process_query_and_save_with_max_results_constraints_BANG___47425.invoke(query_processor.clj:232)"
"api.dataset$fn__50707$fn__50710.invoke(dataset.clj:55)"
"query_processor.streaming$streaming_response_STAR_$fn__35496$fn__35497.invoke(streaming.clj:73)"
"query_processor.streaming$streaming_response_STAR_$fn__35496.invoke(streaming.clj:72)"
"async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
"async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
"async.streaming_response$do_f_async$fn__23282.invoke(streaming_response.clj:85)"],
:context :ad-hoc,
:error "Invalid UUID string: ",
:row_count 0,
:running_time 0,
:preprocessed
{:type :query,
:query
{:source-table 76,
:filter
[:or
[:= [:field-id 1308] [:value nil {:base_type :type/UUID, :special_type nil, :database_type "uuid", :name "id"}]]
[:= [:field-id 1308] [:value "" {:base_type :type/UUID, :special_type nil, :database_type "uuid", :name "id"}]]],
:fields
[[:field-id 1313]
[:datetime-field [:field-id 1307] :default]
[:datetime-field [:field-id 3128] :default]
[:field-id 1308]
[:field-id 1305]
[:field-id 1869]
[:field-id 1306]
[:field-id 1309]
[:field-id 1310]
[:field-id 1312]
[:datetime-field [:field-id 1311] :default]],
:limit 2000},
:database 2,
:middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
:info
{:executed-by 1,
:context :ad-hoc,
:nested? false,
:query-hash [-32, 15, -90, 75, -43, -122, 110, 18, 104, 28, -89, 34, -65, 37, -55, -97, 100, -20, -82, 108, -39, -75, 8, 29, 59, 82, 70, 44, -82, 61, -128, 21]},
:constraints {:max-results 10000, :max-results-bare-rows 2000}},
:data {:rows [], :cols []}}
```

**Comment by flamber** [comment] 2020-09-23 09:46
Related to #13263 and #5816

**Comment by maqen** [comment] 2021-11-25 19:31
Are there any updates on this?

Seems like #13263 didn't fix this for _UUID_ fields (non PK) being `NULL` in PostgreSQL

**Comment by metamben** [comment] 2022-05-13 18:00
The change #22667 should solve the immediate problem related to testing emptiness, but doesn't solve the general problem that UUIDs are treated as strings (the frontend offers operations like `starts with` for it), which results in errors during the compilation.

@flamber Do you think this ticket should be closed or should it stay until we address the general (but more difficult to solve) problem?

**Comment by flamber** [comment] 2022-05-13 18:31
@metamben Let's close this, since I would think that the majority are just looking for emptiness capabilities. A new issue can be opened for partial string filtering.

**Closed by flamber** 2022-05-13 18:31 UTC
Labels: Type:Bug, Priority:P2, Database/Postgres, Querying/
