### ISSUE TITLE
Enable re-ordering fields in the summarize "by" field (Question builder)

### ISSUE THREAD

**Issue by beefstew** [metabase/metabase#41547] opened 2024-04-17 20:12 UTC
Hello and thank you! I'm a new user with time-sensitive data analysis needs who figured it's faster to learn Metabase than muck about in Excel; and I'm pretty good with Excel. I recently encountered an issue that cost me significant time:

There is no way to re-order the columns in the "by" field. This is important functionality for two reasons:

1. When trying to build a stacked bar chart, I learned that the order in which I define my "by" criteria is very important. The field that I want to use to drive the stacking must be declared _first_ in the "by" field. Since there is no affordance for re-ordering, I assumed order did not matter; it took significant trial and error plus web searches to figure out the solution.
2. User work is lost when a "Custom column" is defined based on a column in the "by" field that must be moved. Worse, removing the column in the "by" field does not warn the user that their custom column will be automatically removed.

Luckily, the expression editor is so small and lacks an indenting feature, that users are likely to develop their complex expressions in a text editor and copy/paste them into the expression... helping prevent them from losing work.

Concrete example:
![Screenshot 2024-04-17 at 16 08 24](https://github.com/metabase/metabase/assets/2262454/f7268106-2c78-4988-bab3-413987ebd97a)
I needed the ability to re-order Geography and Product Code so that my stacked bar would work and the CNP Product custom column would not be automatically removed.

**Comment by gabriel-r** [comment] 2024-06-12 12:50
It seems weird that this issues is not a duplicate of one or many older ones.

**Comment by mngr** [comment] 2024-11-06 15:09
We've implemented drag-to-reorder behavior in the Question Builder

**Closed by mngr** 2024-11-06 15:09 UTC
Labels: Type:New Feature, .Needs Triage
