### ISSUE TITLE
archived dashboards are visible in list to everyone regardless of permissions

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#6614] opened 2017-12-23 02:06 UTC
- Metabase version: 0.27.2
- Metabase internal database: MySQL

Just click on the archived dashboards logo and you will be able to see all the dashboards archived by you or someone else regardless of permissions. You can't see anything on those dashboards but it shouldn't even show those in that archived dashboards list.

**Comment by VikramTiwari** [comment] 2018-01-23 16:01
@camsaul Though this (https://github.com/metabase/metabase/issues/4194) is not the same issue but might be interesting to tackle along with current issue.

**Comment by camsaul** [comment] 2018-01-25 00:28
@VikramTiwari I'm not able to reproduce this. We check permissions for viewing Dashboards, archived or not. Dashboards that you would be able to see if *not* archived will still show up in the archived page, but if you wouldn't be able to see them they won't show up there.

**Comment by VikramTiwari** [comment] 2018-01-25 01:05
My bad on the clarity. The dashboards are visible on the list, not the dashboard itself. Updated the issue title.

**Comment by camsaul** [comment] 2018-01-25 01:10
@VikramTiwari I understood that from the original description. What I am saying is we do indeed check read permissions when fetching a list of Dashboards, whether or not those Dashboards are archived. If you can see a Dashboard that is archived it is because you would be able to see it if it was not. This likely means one or more of the Cards in that Dashboard are visible to the current user.

This code right here filters out dashboards for which the current user does not have read permission:
https://github.com/metabase/metabase/blame/master/src/metabase/api/dashboard.clj#L45

**Comment by VikramTiwari** [comment] 2018-01-25 02:13
@camsaul Ah! Just rechecked. It's the same as https://github.com/metabase/metabase/issues/4194 but happening at archived dashboards page as well. The list contains the dashboards which are empty. Since there is no way to stop them, those dashboards are also visible here.

Please close this if you wanna treat it as a duplicate. Though a solution to the original issue will be really helpful.

**Comment by camsaul** [comment] 2018-01-25 18:52
Our current thinking is that you're allowed to see a Dashboard unless you can't see *all* of it's Cards. So currently everyone can see empty dashboards, archived or not. So going to go ahead and close this as a duplicate of #4194

**Closed by camsaul** 2018-01-25 18:52 UTC
Labels: Bug, Permissions, Priority/P1, Unable to Reproduce

**Comment by salsakran** [comment] 2018-01-25 18:54
@camsaul just to ask a hopefully dumb question -- we don't count dashcards (i.e. text cards) as cards, right? So a dashboard with one card I can't see and a text-only "card" should be invisible to me?
