### ISSUE TITLE
Client-side filters

### ISSUE THREAD

**Issue by nickcarenza** [metabase/metabase#13195] opened 2020-09-01 20:32 UTC
What if we could define client-side filters to make manipulating queried data snappier. We could write our queries to be more inclusive and just let the user cut the data a bunch of ways without having to go back to the database each time.

**Comment by flamber** [comment] 2020-09-01 20:34
Duplicate of #8895/#6240. Related to #11329.

**Closed by flamber** 2020-09-01 20:34 UTC
Labels: .Needs Triage, Type:New Feature
