### ISSUE TITLE
Dashboard breaks after changing question variable that is already linked on dashboard

### ISSUE THREAD

**Issue by AlixHn** [metabase/metabase#9299] opened 2019-01-22 11:42 UTC
Hi,

We have a problem with a dashboard : we modified a query and now, impossible to open the dashboard, there is a message : "Cannot read property 'customers' of undefined".

We tried to get back to an older version of the query but it fails every time.

What can we do ?

System : Chrome & Metabase v0.31.1

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by salsakran** [comment] 2019-01-22 14:40
Can you narrow the specific problem down to card? If so, what is in that card, and can you share the response from the server for that dataset query?

**Comment by AlixHn** [comment] 2019-01-23 17:32
The card is a SQL query, with multiple tables joined but no filters. The query still works.

**Comment by sethia** [comment] 2019-02-05 13:02
Facing a similar issue, had modified a question and added it to dashboard , now getting "Cannot read property 'card' of undefined " , basically the chart now has a bar and a line combined, is that causing issues? Couldn't find anything in Chrome console

**Comment by Delia-Balaoi** [comment] 2019-05-22 16:35
Hello.
 I am facing the same issue with v0.32.4 version. Did you find any fix?

**Comment by astratto** [comment] 2019-06-11 13:49
We're facing the same issue with a dashboard that was working fine.
How can we start troubleshooting this? It doesn't seem to provide much more information.

**Comment by flamber** [comment] 2019-06-11 20:15
Which version did you upgrade from?
Try upgrading to 0.32.8

**Comment by Delia-Balaoi** [comment] 2019-06-12 07:58
The problem is when you change the query and you remove one of the columns or filters that are used in the dashboard.

**Comment by vrsttl** [comment] 2019-08-27 06:00
Same issue here. Can revert to an older version, removing the filter in any sequence doesn't solve the issue.

**Comment by Kieranflock** [comment] 2019-11-19 17:10
Same issue here on v0.33.5.1

**Comment by eikku** [comment] 2020-01-31 11:24
Same issue here, having error `undefined is not an object (evaluating 't.native["template-tags"][String(n[1])]')` as admin and others have `Cannot read property 'distributor_var' of undefined`. Running on  0.32.9.

**Comment by anoakie** [comment] 2020-02-20 19:19
I'm having a similar issue with 0.34.2

```
TypeError: Cannot read property 'card' of undefined
    at j (app-main.bundle.js?1283043d8d6d3679e46b:5)
    at Object.series (app-main.bundle.js?1283043d8d6d3679e46b:5)
    at app-main.bundle.js?1283043d8d6d3679e46b:5
    at app-main.bundle.js?1283043d8d6d3679e46b:5
    at W (app-main.bundle.js?1283043d8d6d3679e46b:5)
    at Object.t.barRenderer [as renderer] (app-main.bundle.js?1283043d8d6d3679e46b:5)
    at t.value (app-main.bundle.js?1283043d8d6d3679e46b:5)
    at t.value (app-main.bundle.js?1283043d8d6d3679e46b:5)
    at e.notifyAll (vendor.bundle.js?1283043d8d6d3679e46b:1)
    at d.close (vendor.bundle.js?1283043d8d6d3679e46b:1)
value @ app-main.bundle.js?1283043d8d6d3679e46b:5
----------
app-main.bundle.js?1283043d8d6d3679e46b:5 Cannot read property 'card' of undefined
n.onRenderError @ app-main.bundle.js?1283043d8d6d3679e46b:5
```

I'm able to reproduce the issue that @sethia reported, but I'm not sure if it's related to the parent bug.

Steps to reproduce:

1. Add a graph that has at least 3 possible Y axis variables
2. Remove one of the Y-axis variables, mark the other two variables as a bar and a line
3. Add a trend line

It looks like the error occurs when `graph.show_trendline` is looking for the index that you removed from the display (`c.default.findIndex()`'s `c.default.findWhere()`'s `{ name: ... }` parameter returns `-1` because it can't find the removed Y-axis variable (removed in step 2), which causes the `o.series(i[n])` call (where `n === -1`) to throw.

**Comment by matcastelo** [comment] 2020-02-27 14:31
I had the same problem here, but I found a solution. 

In my case, the problem was that there was a question in SQL with a filter that had not relationship with the BI's filter. I tried do archive this question and it worked. 

v0.34.1

**Comment by flamber** [comment] 2020-05-25 10:21
As noted in https://github.com/metabase/metabase/issues/9299#issuecomment-501163355, this happens, when a question (that is already connected to filters on the dashboard) is modified to not include that variable/filter.

Steps to reproduce:
1. Create a Native question > Sample Dataset
2. `SELECT * FROM ORDERS WHERE {{filter}}`
3. Make `{{filter}}` a Field Filter connected to Orders > Created At
4. Save question, add to dashboard
5. On dashboard, create filter Time > All Options, and connect to question, and save dashboard
6. Edit question, change query to `SELECT * FROM ORDERS`, and save
7. Go to dashboard, which will just show an error:
![image](https://user-images.githubusercontent.com/1447303/82800037-49876f00-9e7b-11ea-8b22-b9aadfbeee23.png)
8. To make the dashboard workable again, go to the question, click the pencil next to title, View revision history, click Revert (and then do a browser refresh, because of #12581)

On Firefox the error displayed is `t.native['template-tags'] is undefined`
On Chrome, it would be `Cannot read property 'filter' of undefined` (where "filter" changes depending on the variable name)
Changing priority, since it can be really difficult to figure out which question caused this.

@sethia I'm fairly sure you're seeing a different issue. Are you still seeing your problem on latest release, 0.35.3? The problems with titles sounds like #6765.
@anoakie I might be misunderstanding your steps to reproduce, but can you provide more precise steps (preferably with Sample Dataset)?

**Comment by mtthsbrr** [comment] 2020-07-24 10:34
We are facing the "Cannot read property 'type' of undefined" error for one of our oldest dashboards after updating to 0.36.0 from 0.35.4. What we found out is that it seems user rights related because everyone with admin rights can still access it but we did not touch the permissions at all.

**Comment by flamber** [comment] 2020-07-24 11:11
@mtthsbrr Please post errors from Admin > Troubleshooting > Logs, and your browser developer console.
And if possible, please provide steps-to-reproduce.

**Comment by silversilver** [comment] 2020-07-27 05:19
We have the same issue as @mtthsbrr mentioned after an upgrade from 0.35.4 to 0.36.0

**Comment by flamber** [comment] 2020-07-27 08:39
@silversilver Without knowing how to reproduce your error, it's going to be a lot harder to fix the problem.

**Comment by silversilver** [comment] 2020-07-27 12:17
> @silversilver Without knowing how to reproduce your error, it's going to be a lot harder to fix the problem.

@flamber Apologies, It's a permission issue I think, if the dashboard contains queries that are in a collection that the user does not have access too (in this case the root collection) that error occurs.

**Comment by flamber** [comment] 2020-07-27 14:28
@mtthsbrr @silversilver Thank you for putting me on the right track - I've created a new issue #13005, since it's unrelated to this.

**Comment by nemanjaglumac** [comment] 2020-10-13 11:28
This one is fixed in the latest master?
I am just finishing the repro and it works just fine.

**Closed** 2020-10-13 11:38 UTC
Labels: Priority:P1, Querying/Native, Querying/Parameters & Variables, Reporting/Dashboards, Type:Bug
