### ISSUE TITLE
Include question description in Pulses

### ISSUE THREAD

**Issue by petar777** [metabase/metabase#6981] opened 2018-02-20 07:08 UTC
Hello everyone!

I am currently experiencing the following issue (it is not a big deal but something can easily be done in order to make the software better). In some previous questions, I mentioned that I am using Metabase for the development of a Call Center. With the help of this software, I created different dashboards for the operators in order to allow them to look after some key details about their workday. However, I named the questions with the same name and the only difference between them is their description (where I enter the name or in our case the unique ID of the operator). 

So, my question is- is it possible to send the description of the question as a message in Slack? It is not very important but it can make things a bit more organized. And I would be able to avoid writing huge question names.

Thank you in advance, all the best!

**Comment by brunobergher** [comment] 2021-11-02 22:30
This is possible as for 41.

**Comment by flamber** [comment] 2021-11-03 08:46
Closing as duplicate of #15744, which is part of 0.41

**Closed by flamber** 2021-11-03 08:46 UTC
Labels: .Proposal, Reporting/Pulses
