### ISSUE TITLE
"ERROR: operator does not exist: integer = character" when trying to view a single record from a table

### ISSUE THREAD

**Issue by bturndorf** [metabase/metabase#13274] opened 2020-09-18 13:31 UTC
**Describe the bug**
When viewing a table, and trying to click into a single record based on an integer ID field, we've started getting a "There was a problem with your question" error. The full error details: `ERROR: operator does not exist: integer = character varying Hint: No operator matches the given name and argument types. You might need to add explicit type casts. Position: 4096`

**Logs**
No console errors, and all network requests are returning 200s.

**To Reproduce**

1. New custom question, just viewing a table, e.g. our `Store Cart` or `Store Order` table.
2. Navigate to the `ID` column.
3. Click on the ID for the single record you want to view.
4. Receive the error.
5. Accessing the single record by filtering works as normal.

Possible related: clicking to view related records from the sidebar of a single record also returns the same error.

**Expected behavior**
When clicking the ID field from a table, the single record for that ID should display.

**Screenshots**
Video of the error: https://share.getbento.com/rRu72K2K

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "4.14.193-113.317.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "US/Eastern"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-09-11",
      "tag": "v0.36.5.1",
      "branch": "release-0.36.x",
      "hash": "a3459e8"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```

**Severity**
This is annoying. It worked until recently. We can filter to view the records we need, but not being able to use the sidebar of related records from the single record means we need to just start a new query. Not a total blocker, just frustrating and adds time to lots of tasks.

**Additional context**
We recently switched our application from Python 2 to 3. Doubt it's relevant, but maybe there's a typecasting issue etc.

**Comment by flamber** [comment] 2020-09-18 13:46
Duplicate of #13263
Downgrade to 0.36.4

**Closed by flamber** 2020-09-18 13:46 UTC
Labels: .Needs Triage, Type:Bug
