### ISSUE TITLE
Map Field filter to user defined values

### ISSUE THREAD

**Issue by omkar1610** [metabase/metabase#16616] opened 2021-06-16 08:33 UTC
I sometimes need a field filter to show 4-5 values of my choice. Please add a feature to map a field filter to list of values given by the user.

The way I am doing it is by creating a temp table for all such values and map it to that table. I have already have >20 temp tables having <10 values in each.

This would really be helpful for simple yes/no, true/false type choices too.

**Comment by flamber** [comment] 2021-06-16 08:40
Duplicate of #6820

**Closed by flamber** 2021-06-16 08:40 UTC
Labels: .Needs Triage, Type:New Feature
