### ISSUE TITLE
Questions failing often but queries are running on the Database

### ISSUE THREAD

**Issue by HelmiRifai** [metabase/metabase#5682] opened 2017-08-04 09:19 UTC
- Your browser and the version: Chrome 59.0
- Your operating system: Mac 10.11.5
- Your databases: Redshift
- Metabase version: 0.25.1
- Metabase hosting environment: Docker on EC2 instance
- Metabase internal database: MySQL

Questions are failing with the 'Your question took too long' message though when using developer tools and inspecting the network what I see is attached below. The queries keep running on Redshift so our users are also overloading Redshift by repeating the same queries.

<img width="412" alt="question_ _metabase_1" src="https://user-images.githubusercontent.com/4684370/28962624-eeb1308c-790e-11e7-9b2d-f25b881a86db.png">

<img width="1206" alt="question_ _metabase" src="https://user-images.githubusercontent.com/4684370/28962653-05d845a2-790f-11e7-9db8-132566133c76.png">

**Comment by ricardojmendez** [comment] 2017-08-04 13:53
I'm seeing similar behavior on 0.25.1 with PostgreSQL, even with straightforward `select count(*)` queries.

It's not even one of our heavier databases - a different one with ~800k records runs swimmingly.  CPU and memory usage on both the database server that the queries are timing out for and on Metabase's own database server are normal.

**Comment by salsakran** [comment] 2017-08-04 14:46
If you're on beanstalk, it looks like one of
1. The ELB load balancer
2. The nginx reverse proxy
3. Our jetty container (unlikely)
4. The JDBC driver 
is timing out or having a connection dropped. 

Are you certain that nothing other than the Metabase version changed in your config?

Do you have access to the host server logs? The nginx logs would be especially useful.

**Comment by salsakran** [comment] 2017-08-04 14:46
related to #4928

**Comment by ricardojmendez** [comment] 2017-08-04 15:16
- The database where the queries are failing is a PostgreSQL 9.3.14 on RDS.
- Metabase is using a PostgreSQL 9.6.2 on RDS
- Nothing other than the Metabase version changed on our configuration that I'm aware of.
- It didn't start failing right after an upgrade. I upgraded to 0.25.1 four days ago, the issues did not start until today.
- There are no relevant errors on the query DB's logs.They are unrelated to the queries failing (no error is logged when a query times out).
- Metabase's on logs do not register any errors that I can see, just a lot of debug and info lines.

If it was a problem with the nginx reverse proxy, it doesn't sound like it would fail for one specific database, would it?

**Comment by HelmiRifai** [comment] 2017-08-04 15:46
My issue has been going on for a while, before v0.25.1, but as the number of people using Metabase internally has grown so have the complaints.

The deployment we have is directly with a docker container launch on an ec2 instance. The docker logs of the Metabase container indicate nothing when this happens. The issue I'm assuming is on the Jetty side as we don't use nginx; we just have the docker container listen on port 80 and use that.

I have access to the ec2 instance, the metbase docker logs, and I can open a terminal inside the container if needed to debug. Let me know how to help get more info. Do note that between Metabase and Redshift the query keeps running normally, only the client is in limbo and doesn't get the results.

**Comment by ricardojmendez** [comment] 2017-08-07 10:25
As an update: after changing the log settings to ensure an important message doesn't get drowned out by the debug information, I still don't see any relevant WARN or ERROR messages when a query times out.

The database is up and running, and we can query it from elsewhere, so we're also reviewing if there was some infrastructure change that could cause query connections to be dropped. Metabase can connect correctly and initiate a sync, though, so it's only queries that fail (and seem to do so silently).

**Comment by ricardojmendez** [comment] 2017-08-08 09:12
Following up: on our case, it was some glitch specifically on the read replica. It seemed to be failing specifically for Metabase queries.  I can't say why Metabase was logging neither database errors or warnings when this happened, though, which also helped made it look like it was a Metabase glitch.

**Comment by salsakran** [comment] 2017-08-08 18:20
@ricardojmendez if the timeout is happening external to the metabase server, we won't catch it until we try to write to that connection. So ELB or nginx timeouts wouldn't be present in our logs. They'd be present in those logs instead.

**Comment by HelmiRifai** [comment] 2017-08-08 18:41
After reverting to 0.24.2 I'm no longer seeing the issue. Will monitor with rest of our users to see if anyone is still facing it. It used to happen before 0.25.1 update but after we updated the number of times it occurred skyrocketed.

**Comment by ricardojmendez** [comment] 2017-08-08 18:43
> if the timeout is happening external to the metabase server, we won't catch it until we try to write to that connection.

@salsakran In our case the issue seems to have been on the communication between Metabase and Postgres, not desktop->web server. The issue was with the RDS instance.

**Comment by farzadshafiee** [comment] 2017-12-05 14:45
We have a similar case with Postgres 9.6. The Metabase instance becomes totally unresponsive (**503 gateway timeout errors**). The error log says it cannot establish a connection to the database. We have to restart the Metabase for it to become functional again, but the queries keep running like forever in the database and never terminate. We have to manually terminate them with `pg_cancel_backend` command. I know that big queries are the root cause of the issue, but I believe that Metabase should have some safeguards or timeout mechanism to terminate the query and open up connections if such cases occur. I simple mistake in the `WHERE` clause can easily cause the application to become unresponsive.

**Comment by camsaul** [comment] 2017-12-07 02:56
@salsakran is this a bug? It sounds like it's a duplicate of #2399 rather than a P1 Bug?

**Comment by stefanproell** [comment] 2018-02-06 10:22
I do see a similar behavior with MySQL.

- Metabase  v0.27.2 (Docker container)
- Metabase internal database: Postgres 9.6 (Linked Docker container)
- MySQL 5.6 (Docker container, Port exposed, SSL enabled)

The services are deployed on the same physical Debian server in our office. The connection string for JDBC has these parameters:

`verifyServerCertificate=false&useSSL=true&requireSSL=true&connectTimeout=3600000&socketTimeout=3600000&enableQueryTimeouts=False`

I already tried to set very high values (1h) for the timeout settings, but this has no effect.

Some queries run for  few minutes, when I execute them with my Database IDE. Metabase aborts the execution and shows this message exactly after 60 seconds:

> Your question took too long
We didn't get an answer back from your database in time, so we had to stop. You can try again in a minute, or if the problem persists, you can email an admin to let them know.

I cannot save a question which runs for longer than 1 minute. I did not find a setting for increasing the timeout. The process list of my MySQL instance shows that the execution of the query continues also after Metabase shows the error message. Clicking on retry triggers a new execution doubling the load on the server. The Metabase log does not show any information about the query hitting a timeout nor anything else. 

Shorter running queries are not causing any problems. What to do?

**Comment by salsakran** [comment] 2018-02-23 01:29
We just cleaned up cancellation logic in #6848  and I think this should be fixed. 

If you still see this problem in 0.29 please chime in and I'll re-open this.

**Closed by salsakran** 2018-02-23 01:29 UTC
Labels: Bug, Priority/P1

**Comment by swatisinghi** [comment] 2018-03-27 07:42
When will 0.29 release? We are facing a similar issue with version 0.25.2. Does any other interim version have a fix for this. Thanks in advance.

**Comment by efron** [comment] 2018-04-19 15:12
We have the same problem here using the version 0.28.5 and this is avoiding Metabase to be more used around the company.

**Comment by lkraav** [comment] 2018-04-20 07:01
I see 0.29.0-RC1 released and things seem better.

**Comment by swatisinghi** [comment] 2018-05-04 19:10
The issue still seems to exist with 0.29. We just upgraded, but cancelling the query did not cancel it on Redshift.

**Comment by arun-28** [comment] 2018-06-11 13:45
We are using Metabase v0.29.0 and still facing this issue. Cancelled query still runs on the database.

**Comment by JoeSham** [comment] 2018-06-29 12:04
Same for us, still occasionally getting the "Your question took too long" but it runs in db and it also later gets written into the **query_execution** table when it finishes, so apparently the connections works.

**Comment by coderberry** [comment] 2018-07-09 14:08
We are having the same issue on v0.29.3. We are pointing to a DB on Heroku (read-only).

**Comment by JoeSham** [comment] 2018-07-09 16:07
After more research it seems like our issue is that the connection is timing out somewhere along the way. We have 2 load balancers and an oauth proxy there, so likely not a MB problem. Except that the error message could/should point out to this possibility.

**Comment by salsakran** [comment] 2018-07-09 16:35
@coderberry what's between you and the metabase instance (proxy/load balancer-wise), and what's in between the metabase instance and the DB? Anything in the server logs or JS when you run that query that times out?

**Comment by lkraav** [comment] 2018-08-06 10:41
Who's testing this on 0.30-rc?

**Comment by LucasBSC** [comment] 2018-09-17 19:04
This happens for us also. We have the 1-click Heroku deployed and connected to a MySQL database.

I tested with 0.30.3 Metabase and still have this problem for bigger queries. Empirically for queries that return more than 700-800 rows it does not work.

Directly on the database we do not have any problem by querying.

**Comment by mewwts** [comment] 2018-09-21 05:13
Chiming in here. We see the "Your question took to long" in the metabase ui. We have metabase deployed on Google Kubernetes Engine talking to a Postgres database on Google Cloud SQL through a cloudsql_proxy in a separate deployment. This is the logs of the metabase pod:
```
09-21 05:08:52 DEBUG metabase.middleware :: POST /api/dataset 200 (1 s) (4 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
09-21 05:09:22 INFO api.common :: connection closed, canceling request
org.eclipse.jetty.io.EofException
        at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
        at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
        at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302)
        at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:129)
        at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:702)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208)
        at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:480)
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:768)
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:801)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:147)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:140)
        at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:242)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.BufferedWriter.flush(BufferedWriter.java:254)
        at metabase.api.common$fn__20614$fn__20615.invoke(common.clj:394)
        at metabase.api.common$fn__20614.invokeStatic(common.clj:392)
        at metabase.api.common$fn__20614.invoke(common.clj:383)
        at ring.core.protocols$fn__20507$G__20502__20516.invoke(protocols.clj:8)
        at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:105)
        at ring.util.servlet$update_servlet_response.invoke(servlet.clj:90)
        at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:94)
        at ring.util.servlet$update_servlet_response.invoke(servlet.clj:90)
        at ring.adapter.jetty$proxy_handler$fn__60362.invoke(jetty.clj:26)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
        at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
        at sun.nio.ch.IOUtil.write(IOUtil.java:148)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
        at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:172)
        ... 34 more
09-21 05:09:23 WARN generic-sql.query-processor :: Client closed connection, cancelling query
java.lang.InterruptedException
        at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:404)
        at java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at clojure.core$deref_future.invokeStatic(core.clj:2292)
        at clojure.core$future_call$reify__8097.deref(core.clj:6894)
        at clojure.core$deref.invokeStatic(core.clj:2312)
        at clojure.core$deref.invoke(core.clj:2298)
        at metabase.driver.generic_sql.query_processor$cancellable_run_query.invokeStatic(query_processor.clj:485)
        at metabase.driver.generic_sql.query_processor$cancellable_run_query.invoke(query_processor.clj:477)
        at metabase.driver.generic_sql.query_processor$run_query.invokeStatic(query_processor.clj:502)
        at metabase.driver.generic_sql.query_processor$run_query.invoke(query_processor.clj:497)
        at clojure.core$partial$fn__5563.invoke(core.clj:2623)
        at clojure.core$partial$fn__5561.invoke(core.clj:2615)
        at metabase.driver.generic_sql.query_processor$do_with_auto_commit_disabled.invokeStatic(query_processor.clj:535)
        at metabase.driver.generic_sql.query_processor$do_with_auto_commit_disabled.invoke(query_processor.clj:524)
        at metabase.driver.generic_sql.query_processor$do_in_transaction$fn__56668.invoke(query_processor.clj:540)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:747)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:717)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:717)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:730)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:717)
        at metabase.driver.generic_sql.query_processor$do_in_transaction.invokeStatic(query_processor.clj:539)
        at metabase.driver.generic_sql.query_processor$do_in_transaction.invoke(query_processor.clj:538)
        at metabase.driver.generic_sql.query_processor$run_query_without_timezone.invokeStatic(query_processor.clj:553)
        at metabase.driver.generic_sql.query_processor$run_query_without_timezone.invoke(query_processor.clj:552)
        at metabase.driver.generic_sql.query_processor$execute_query$fn__56692.invoke(query_processor.clj:577)
        at metabase.driver.generic_sql.query_processor$do_with_try_catch.invokeStatic(query_processor.clj:519)
        at metabase.driver.generic_sql.query_processor$do_with_try_catch.invoke(query_processor.clj:514)
        at metabase.driver.generic_sql.query_processor$execute_query.invokeStatic(query_processor.clj:574)
        at metabase.driver.generic_sql.query_processor$execute_query.invoke(query_processor.clj:570)
        at clojure.lang.Var.invoke(Var.java:385)
        at metabase.driver$fn__28369$G__28176__28376.invoke(driver.clj:104)
        at metabase.query_processor$execute_query.invokeStatic(query_processor.clj:54)
        at metabase.query_processor$execute_query.invoke(query_processor.clj:48)
        at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__33121.invoke(mbql_to_native.clj:30)
        at metabase.query_processor.middleware.annotate_and_sort$annotate_and_sort$fn__31435.invoke(annotate_and_sort.clj:42)
        at clojure.core$comp$fn__5529.invoke(core.clj:2561)
        at clojure.core$comp$fn__5529.invoke(core.clj:2561)
        at metabase.query_processor.middleware.limit$limit$fn__33076.invoke(limit.clj:15)
        at metabase.query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__32926.invoke(cumulative_aggregations.clj:58)
        at metabase.query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__32926.invoke(cumulative_aggregations.clj:58)
        at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__37053.invoke(results_metadata.clj:51)
        at metabase.query_processor.middleware.format_rows$format_rows$fn__33066.invoke(format_rows.clj:26)
        at metabase.query_processor.middleware.binning$update_binning_strategy$fn__31529.invoke(binning.clj:165)
        at metabase.query_processor.middleware.resolve$resolve_middleware$fn__30920.invoke(resolve.clj:492)
        at clojure.core$comp$fn__5529.invoke(core.clj:2561)
        at clojure.core$comp$fn__5529.invoke(core.clj:2561)
        at clojure.core$comp$fn__5529.invoke(core.clj:2561)
        at clojure.core$comp$fn__5529.invoke(core.clj:2561)
        at metabase.query_processor.middleware.expand$expand_middleware$fn__32806.invoke(expand.clj:607)
        at metabase.query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__31109.invoke(add_row_count_and_status.clj:15)
        at clojure.core$comp$fn__5529.invoke(core.clj:2561)
        at clojure.core$comp$fn__5529.invoke(core.clj:2561)
        at metabase.query_processor.middleware.driver_specific$process_query_in_context$fn__32946.invoke(driver_specific.clj:12)
        at clojure.core$comp$fn__5529.invoke(core.clj:2561)
        at metabase.query_processor.middleware.resolve_driver$resolve_driver$fn__35593.invoke(resolve_driver.clj:15)
        at metabase.query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31443$fn__31444.invoke(bind_effective_timezone.clj:9)
        at metabase.util.date$call_with_effective_timezone.invokeStatic(date.clj:82)
        at metabase.util.date$call_with_effective_timezone.invoke(date.clj:71)
        at metabase.query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31443.invoke(bind_effective_timezone.clj:8)
        at clojure.core$comp$fn__5529.invoke(core.clj:2561)
        at clojure.core$comp$fn__5529.invoke(core.clj:2561)
        at metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__31618.invoke(cache.clj:149)
        at clojure.core$comp$fn__5529.invoke(core.clj:2561)
        at metabase.query_processor.middleware.catch_exceptions$catch_exceptions$fn__32857.invoke(catch_exceptions.clj:58)
        at metabase.query_processor$process_query.invokeStatic(query_processor.clj:135)
        at metabase.query_processor$process_query.invoke(query_processor.clj:131)
        at metabase.query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:249)
        at metabase.query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:243)
        at metabase.query_processor$fn__37091$process_query_and_save_execution_BANG___37096$fn__37097.invoke(query_processor.clj:289)
        at metabase.query_processor$fn__37091$process_query_and_save_execution_BANG___37096.invoke(query_processor.clj:275)
        at metabase.query_processor$fn__37115$process_query_and_save_with_max_BANG___37120$fn__37121.invoke(query_processor.clj:310)
        at metabase.query_processor$fn__37115$process_query_and_save_with_max_BANG___37120.invoke(query_processor.clj:306)
        at metabase.api.dataset$fn__43568$fn__43571.invoke(dataset.clj:45)
        at metabase.api.common$fn__20630$invoke_thunk_with_keepalive__20635$fn__20636$fn__20637.invoke(common.clj:433)
        at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
09-21 05:09:23 WARN metabase.query-processor :: {:status :failed,
 :class java.lang.InterruptedException,
 :error "java.lang.InterruptedException",
 :stacktrace
 ["driver.generic_sql.query_processor$cancellable_run_query.invokeStatic(query_processor.clj:485)"
  "driver.generic_sql.query_processor$cancellable_run_query.invoke(query_processor.clj:477)"
  "driver.generic_sql.query_processor$run_query.invokeStatic(query_processor.clj:502)"
  "driver.generic_sql.query_processor$run_query.invoke(query_processor.clj:497)"
  "driver.generic_sql.query_processor$do_with_auto_commit_disabled.invokeStatic(query_processor.clj:535)"
  "driver.generic_sql.query_processor$do_with_auto_commit_disabled.invoke(query_processor.clj:524)"
  "driver.generic_sql.query_processor$do_in_transaction$fn__56668.invoke(query_processor.clj:540)"
  "driver.generic_sql.query_processor$do_in_transaction.invokeStatic(query_processor.clj:539)"
  "driver.generic_sql.query_processor$do_in_transaction.invoke(query_processor.clj:538)"
  "driver.generic_sql.query_processor$run_query_without_timezone.invokeStatic(query_processor.clj:553)"
  "driver.generic_sql.query_processor$run_query_without_timezone.invoke(query_processor.clj:552)"
  "driver.generic_sql.query_processor$execute_query$fn__56692.invoke(query_processor.clj:577)"
  "driver.generic_sql.query_processor$do_with_try_catch.invokeStatic(query_processor.clj:519)"
  "driver.generic_sql.query_processor$do_with_try_catch.invoke(query_processor.clj:514)"
  "driver.generic_sql.query_processor$execute_query.invokeStatic(query_processor.clj:574)"
  "driver.generic_sql.query_processor$execute_query.invoke(query_processor.clj:570)"
  "driver$fn__28369$G__28176__28376.invoke(driver.clj:104)"
  "query_processor$execute_query.invokeStatic(query_processor.clj:54)"
  "query_processor$execute_query.invoke(query_processor.clj:48)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__33121.invoke(mbql_to_native.clj:30)"
  "query_processor.middleware.annotate_and_sort$annotate_and_sort$fn__31435.invoke(annotate_and_sort.clj:42)"
  "query_processor.middleware.limit$limit$fn__33076.invoke(limit.clj:15)"
  "query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__32926.invoke(cumulative_aggregations.clj:58)"
  "query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__32926.invoke(cumulative_aggregations.clj:58)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__37053.invoke(results_metadata.clj:51)"
  "query_processor.middleware.format_rows$format_rows$fn__33066.invoke(format_rows.clj:26)"
  "query_processor.middleware.binning$update_binning_strategy$fn__31529.invoke(binning.clj:165)"
  "query_processor.middleware.resolve$resolve_middleware$fn__30920.invoke(resolve.clj:492)"
  "query_processor.middleware.expand$expand_middleware$fn__32806.invoke(expand.clj:607)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__31109.invoke(add_row_count_and_status.clj:15)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__32946.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__35593.invoke(resolve_driver.clj:15)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31443$fn__31444.invoke(bind_effective_timezone.clj:9)"
  "util.date$call_with_effective_timezone.invokeStatic(date.clj:82)"
  "util.date$call_with_effective_timezone.invoke(date.clj:71)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31443.invoke(bind_effective_timezone.clj:8)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__31618.invoke(cache.clj:149)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__32857.invoke(catch_exceptions.clj:58)"
  "query_processor$process_query.invokeStatic(query_processor.clj:135)"
  "query_processor$process_query.invoke(query_processor.clj:131)"
  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:249)"
  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:243)"
  "query_processor$fn__37091$process_query_and_save_execution_BANG___37096$fn__37097.invoke(query_processor.clj:289)"
  "query_processor$fn__37091$process_query_and_save_execution_BANG___37096.invoke(query_processor.clj:275)"
  "query_processor$fn__37115$process_query_and_save_with_max_BANG___37120$fn__37121.invoke(query_processor.clj:310)"
  "query_processor$fn__37115$process_query_and_save_with_max_BANG___37120.invoke(query_processor.clj:306)"
  "api.dataset$fn__43568$fn__43571.invoke(dataset.clj:45)"
  "api.common$fn__20630$invoke_thunk_with_keepalive__20635$fn__20636$fn__20637.invoke(common.clj:433)"],
 :query
 {:type "native",
  :native
  {:query
   "select distinct topics[3]\nfrom logs\nwhere logs.topics[1]=decode('xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef', 'ESCAPE')\nand logs.contract_address=decode('0F5D2fB29fb7d3CFeE444a200298f468908cC942', 'hex');",
   :template_tags {}},
  :parameters [],
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :card-id nil,
   :nested? false,
   :query-hash [10, 37, 16, 96, 126, 73, 60, -68, -102, -30, -37, 106, -35, 48, -9, -60, 69, 15, 16, 112, -43, -11, -63, -6, -11, -61, 14, 88, 101, 126, 105, 4],
   :query-type "native"}},
 :expanded-query nil}

09-21 05:09:23 WARN metabase.query-processor :: Query failure: java.lang.InterruptedException
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:217)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:210)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:250)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:243)"
 "query_processor$fn__37091$process_query_and_save_execution_BANG___37096$fn__37097.invoke(query_processor.clj:289)"
 "query_processor$fn__37091$process_query_and_save_execution_BANG___37096.invoke(query_processor.clj:275)"
 "query_processor$fn__37115$process_query_and_save_with_max_BANG___37120$fn__37121.invoke(query_processor.clj:310)"
 "query_processor$fn__37115$process_query_and_save_with_max_BANG___37120.invoke(query_processor.clj:306)"
 "api.dataset$fn__43568$fn__43571.invoke(dataset.clj:45)"
 "api.common$fn__20630$invoke_thunk_with_keepalive__20635$fn__20636$fn__20637.invoke(common.clj:433)"]
```
