### ISSUE TITLE
Application Page Shakes

### ISSUE THREAD

**Issue by elmentdave** [metabase/metabase#11419] opened 2019-12-02 13:25 UTC
**Describe the bug**
The page keeps shaking. This only happens at the admin section

**To Reproduce**
1. Go to Admin Section
2. Click on Permissions
4. See error (Pages keeps shaking)

**Expected behavior**
No shaking on the page

**Severity**
This issue is very annoying and making my usage of Metabase difficult?

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.15.0-70-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "run-mode": "prod",
    "version": {
      "date": "2019-11-19",
      "tag": "v0.33.6",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2019-12-02 17:55
Hi @elmentdave 
Sounds like a duplicate of #8165 - if you agree, then please close this and upvote the other issue :+1:

**Comment by mazameli** [comment] 2019-12-02 18:06
Closing as duplicate

**Closed by mazameli** 2019-12-02 18:06 UTC
Labels: .Duplicate
