### ISSUE TITLE
TypeError: Cannot read property 'tagName' of null

### ISSUE THREAD

**Issue by riorulzz** [metabase/metabase#1731] opened 2016-01-13 16:18 UTC
I am getting cannot read property 'tagname' of null exception while visualizing as bar chart if data contains '-' . Pie chart works fine .

It works just fine if i replace '-' from data .

Please refer attached screenshots .
![screen shot 2016-01-13 at 9 38 59 pm](https://cloud.githubusercontent.com/assets/7091402/12299865/e08ea754-ba3e-11e5-88cb-75104f07f443.png)
![screen shot 2016-01-13 at 9 40 02 pm](https://cloud.githubusercontent.com/assets/7091402/12299870/e7384fd8-ba3e-11e5-95f0-d9317046ffbc.png)

Can someone please look into this ?

**Comment by tlrobinson** [comment] 2016-01-25 21:10
@riorulzz I'm unable to reproduce this, at least on Postgres. What database are you using? What browser are you using?

Could you give me the results of the API request to `/api/dataset` (available in the developer tools network panel of most browsers)

FYI in my test I'm using this query: `SELECT id, count(*) FROM (VALUES ('foo-bar'), ('foo-baz'), ('foo-baz')) AS test(id) GROUP BY id;`

**Comment by camsaul** [comment] 2016-02-10 19:49
Motion to close since we don't have enough details, can't reproduce this, and the OP hasn't responded to requests for more details :scream:

**Comment by agilliland** [comment] 2016-02-10 19:52
:+1:

**Comment by camsaul** [comment] 2016-02-10 20:06
Ran into the issue here: https://staging.metabase.com/card/16

**Comment by agilliland** [comment] 2016-02-10 23:28
Actually, I think this problem is a relic of an old version of metabase where the saved question likely has some kind of issue on it.  I am able to reproduce the same question without any issues if I start from scratch.

**Comment by tlrobinson** [comment] 2016-02-17 08:47
I'm now fairly certain this is due to this bug in d3-tip: https://github.com/Caged/d3-tip/pull/96

This should be resolved by #1859.

I have no idea why it was being triggered by the conditions @riorulzz mentioned.

**Closed** 2016-02-23 06:12 UTC
Labels: Bug, Visualization
