### ISSUE TITLE
When editing a dashboard, clicking on a filter should display its options sidebar even if the add-questions sidebar is open

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#17381] opened 2021-08-09 20:41 UTC
**To reproduce:**
1. Go to a dashboard and enter edit mode
2. Add a dashboard filter if the dashboard doesn't have one already
3. Open up the add-questions sidebar
4. Click on the dashboard filter

**Expected behavior:** the filter options sidebar should be displayed.
**Actual behavior:** the options sidebar is not visible until the add-questions sidebar is manually closed.

Example GIF:

![sidebar-behavior](https://user-images.githubusercontent.com/2223916/128771594-139fd1ac-a5a0-4039-886a-4bfa89b70758.gif)

**Comment by flamber** [comment] 2021-08-09 20:45
Duplicate of #16783

**Closed** 2021-08-31 16:00 UTC
Labels: Type:Bug, Priority:P2, Reporting/Dashboards
