### ISSUE TITLE
Binned latitude and longitude does not work

### ISSUE THREAD

**Issue by BenjaminGK** [metabase/metabase#10486] opened 2019-08-04 07:49 UTC
**Describe the bug**
When trying to bin latitude and longitude for questions where you want to join other tables, it works in preview, but the results do not bin meaning you can't use the grid map

**Logs**
No errors seen in metabase log only the below<:
![image](https://user-images.githubusercontent.com/23311430/62421045-0a0e4d00-b6c6-11e9-8fca-fd08c2b75ef6.png)
![image](https://user-images.githubusercontent.com/23311430/62421070-3924be80-b6c6-11e9-80ed-30f4807b45ae.png)

**To Reproduce**
1. Go to "custom question"
2. Select "orders"
3. Join "people" table
4. Summarize with a count and group by latitude and longitude
5. Click preview = working
6. Click visualize results
7. See error 

**Expected behavior**
It shall be possible to bin the results so grid map can be used - even better if it would work for Native SQL as well

**Screenshots**
Builder
![image](https://user-images.githubusercontent.com/23311430/62421122-e5ff3b80-b6c6-11e9-910f-f529c6e2122a.png)
Results
![image](https://user-images.githubusercontent.com/23311430/62421116-d41d9880-b6c6-11e9-81f2-ebb799d9bca1.png)

**Information about your Metabase Installation:**
- Your browser and the version: Version 75.0.3770.142 (Official Build) (64-bit)

- Your operating system: (Windows 10)

- Your databases: MySQL & sample DB

- Metabase version:  0.33 RC1

**Severity**
This is a big issue as it renders the whole binning feature useless, and grid map as example can't be used

**Comment by flamber** [comment] 2019-08-04 17:16
Hi @BenjaminGK 
Good catch. It doesn't seem to be related to Join. If you just use the linked table, then you get the same non-working result.
Looking at the POST parameters, the preview-results does not wrap the `query` in `source-query`.

**Comment by tlrobinson** [comment] 2019-08-07 18:49
I believe this is partially fixed by #10512, which strips the useless `source-query` (if there's no other clauses like post-aggregation filters). 

However, (similar to #10511) this still doesn't work correctly if the query is nested, I believe due to the `cols` for nested queries not including `binning_info`.

**Comment by flamber** [comment] 2020-06-02 15:08
I cannot reproduce on 0.35.4 - think it was fixed in 0.33.x

**Closed by flamber** 2020-06-02 15:08 UTC
Labels: .Backend, Priority:P2, Querying/GUI, Type:Bug, Visualization/Maps
