### ISSUE TITLE
Dropdown field type in question

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#4388] opened 2017-02-15 11:04 UTC
Having a field type of `Text`, `Number` is great to have, But sometime there is a situation that field content is limited to a list of specific values like: `OK`, `Failed`:  

![screen shot 2017-02-15 at 2 34 20 pm](https://cloud.githubusercontent.com/assets/6417083/22971728/e855b1a8-f38b-11e6-929d-66291ff2d133.png)

Is it possible to have dropdown field type when creating a new question?

**Comment by tanzoniteblack** [comment] 2017-02-15 18:04
This is probably effectively a duplicate of https://github.com/metabase/metabase/issues/4346

**Comment by flamber** [comment] 2020-05-26 12:13
Closing in favor of #5245/#6820

**Closed by flamber** 2020-05-26 12:13 UTC
Labels: .Proposal, Querying/Parameters & Variables
