### ISSUE TITLE
Cannot get line graph to display correct y-values when using timeseries x-scale

### ISSUE THREAD

**Issue by BenWoodford** [metabase/metabase#5458] opened 2017-07-12 11:14 UTC
I have a bunch of `created_at` values in a DB, and I'm trying to get a line graph of their values going to show creations of rows over time. The tabulated data correctly shows the number of entries for each date, but when I switch to line and change the x-axis scale to "Timeseries" and set "Replace missing values" with "Zero" it shows a value of 1 for the first date and the remaining are 0.

![image](https://user-images.githubusercontent.com/503263/28114739-fe7e4af8-66f9-11e7-9492-4f1f7d4cb2a9.png)

![image](https://user-images.githubusercontent.com/503263/28114745-07ab18c2-66fa-11e7-9104-be62a5be93c8.png)

It may be that I just don't have this in the correct format, but this is an SQL query generated by the non-SQL question creator and then I switched to SQL form to tweak it.

- Your browser and the version: Chrome 59.0.3071.115
- Your operating system: Windows 10
- Your databases: MySQL
- Metabase version: 0.24.2 
- Metabase hosting environment: Docker
- Metabase internal database: H2

- *Repeatable steps to reproduce the issue*

1.) Give the above tabulated data to Metabase, or use a query like this:

```
SELECT count(*) AS `count`, date(`entity_table`.`created_at`) AS `created_at`
FROM `entity_table`
GROUP BY date(`entity_table`.`created_at`)
ORDER BY date(`entity_table`.`created_at`) ASC
```

`created_at` is from Laravel, and is just a MySQL datetime field. `date` is used to group by the date rather than show individual times

2.) Try to create a line graph with zero for missing values, use time-series on x. Scales are `created_at` along the x, `count` along the y.

3.) It... doesn't display what you'd expect.

Interestingly, if you try doing this without the `date` functions (so don't group by the date) then it outright crashes the page. Possibly due to too many X values?

**Comment by camsaul** [comment] 2017-11-06 23:46
Sounds like a duplicate of #4802 ?

**Comment by flamber** [comment] 2020-05-24 19:34
Closing in favor of #4802

**Closed by flamber** 2020-05-24 19:34 UTC
Labels: Priority:P2, Type:Bug, Visualization/Chart Settings
