### ISSUE TITLE
csv/xlsx downloads ignore table visualization settings

### ISSUE THREAD

**Issue by robokaso** [metabase/metabase#5773] opened 2017-08-17 19:56 UTC
After I tweak the the table visualization settings (reordering and hiding columns) I expect the csv/xlsx/json download to be identical to the displayed table. However the downloaded files always contain all columns sorted alphabetically ignoring the desired formatting. 

- Your databases: Postgres 9.5
- Metabase version: 0.25.2
- Metabase internal database: H2

**Comment by mvrabel** [comment] 2017-08-18 15:44
Already created an issue for it #5295

**Comment by salsakran** [comment] 2017-09-06 22:00
dupe of #5295

**Closed by salsakran** 2017-09-06 22:00 UTC
