### ISSUE TITLE
Values for text fields using in filters are replaced by "?" in SQL mode

### ISSUE THREAD

**Issue by M4zD4i** [metabase/metabase#6187] opened 2017-10-17 13:44 UTC
- Your browser and the version: Safari 11.0 (12604.1.38.1.7)
- Your operating system: MacOS Sierra 10.12.6
- Your databases: Apache Impala
- Metabase version: fork from 0.26.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

Steps to reproduce:
1. Create a custom query with some fields in Filters having text type in data model and run it to get answer
2. Click "View in SQL" button 
![2017-10-17 16 04 23](https://user-images.githubusercontent.com/1096609/31668013-acb2244a-b359-11e7-8b53-6c7cfbf70d9e.png)

Values for filter fields having text type are replaced by "?" sign in SQL pop-up:
![image 2017-10-17 16-14-59](https://user-images.githubusercontent.com/1096609/31668080-e2a6d87a-b359-11e7-9cdb-780f16bf162b.png)

3. Click "Convert this question to SQL" button

The same strange behavior is in SQL mode. Query is broken, so "Get Answer" button results with error:
![question metabase 2017-10-17 16-13-56](https://user-images.githubusercontent.com/1096609/31668199-2e43a880-b35a-11e7-8575-ce825ad9ba66.png)

**Comment by camsaul** [comment] 2017-10-17 22:04
This is a duplicate of #3549.

Also, how are you using Impala? We don't have a driver for it

**Closed by camsaul** 2017-10-17 22:04 UTC

**Comment by M4zD4i** [comment] 2017-10-18 12:32
Hi @camsaul , thanks for feedback!
We are based onto this PR: https://github.com/metabase/metabase/issues/3002
