### ISSUE TITLE
Unable to resolve driver for query.

### ISSUE THREAD

**Issue by mrdeds** [metabase/metabase#6309] opened 2017-11-01 01:55 UTC
I'm using a new metabase installation in a server, with a postgres database for the backend.

I did some questions in the platform, but suddenly the questions when opened showed this:
![image 1](https://user-images.githubusercontent.com/9302082/32256551-b2a49d7c-be7d-11e7-8012-4ab3ad1f8398.png)

If i make another question with the exact same query it shows the data without problems. The issue is only with already made questions.

Also, it doesn't let me edit the query.

The server is Ubuntu
The metabase version is v0.26.2
Using Chrome on a Mac

Here's the log for that query:
![captura de pantalla 2017-10-31 a la s 20 13 21](https://user-images.githubusercontent.com/9302082/32257012-84415102-be80-11e7-985e-f32c7fe147d8.png)

**Comment by lindsay-stevens** [comment] 2017-11-01 03:54
I've seen this problem too, with chrome, postgres, and metabase v.0.26 and SQL questions, but on Windows.

When it happened for me, the cause was that the source database for the question was removed. So if you check the Chrome developer tab, and look in the query definition (the "card" endpoint, or just out of view in the log you posted) there'll be a "dataset query" object with a "database" ID. This ID should correspond to a database / connection (visible in admin panel) that no longer exists. 

To fix it I edited the question and re-selected the source database. The same could be done via a put request to the card/:id endpoint with the updated database id.

If it is the same problem and the above fixes it then maybe a more precise error message would be helpful to have in Metabase, and/or deleting any associated questions when deleting a database.

**Comment by mrdeds** [comment] 2017-11-01 04:21
Great! I’ll try that

**Comment by mrdeds** [comment] 2017-11-02 01:25
So I changed the queries of the questions and now they are working with the new database. 
I think @lindsay-stevens 's suggestion is good, but also the chance to change the data source of the questions.

**Comment by camsaul** [comment] 2017-11-15 02:13
@metabase/core-developers it sounds like if you delete a database the cards are still sticking around, no longer able to run

We can definitely add better error messages in this case but should we still keep the Cards around? Or archive/delete them?

**Comment by mrdeds** [comment] 2017-11-29 06:25
Well, in my case, it would’ve been really helpful just to let me choose another data base.

**Comment by flamber** [comment] 2020-05-24 20:48
This was fixed by #7230 in 0.28.4

**Closed by flamber** 2020-05-24 20:48 UTC
Labels: Type:UX
