### ISSUE TITLE
Metabase sends duplicate pulse to Slack if the Elastic Beanstalk environment scales up

### ISSUE THREAD

**Issue by imsky** [metabase/metabase#4397] opened 2017-02-16 18:30 UTC
Steps:

- Create an Elastic Beanstalk deployment of Metabase
- Set up a pulse to a Slack channel
- Scale up the deployment to 2+ replicas
- Pulse should now be posted multiple times

Pulses should be de-duplicated, otherwise scaling Metabase out has undesirable side effects.

**Comment by camsaul** [comment] 2017-02-16 18:39
@imsky Metabase isn't currently designed to work with multiple instances (in this case, each instance is scheduling its own Pulse tasks). It's something we're planning on addressing in the future. We've explained this is a little more detail in #3367

Closing as duplicate of #3367

**Closed by camsaul** 2017-02-16 18:39 UTC
Labels: Duplicate

**Comment by alexsonnay** [comment] 2017-07-19 17:06
Hello !

I have only one instance, and two bots are sending the same notification on Slack. One is MetaBot, the other one is the custom one I set up to connect Slack with Metabase. Both are sending the same pulse everytime it shoots.

Any idea ?

Thanks !

**Comment by astrojuanlu** [comment] 2022-06-27 10:02
@alexauvray xref: https://discourse.metabase.com/t/duplicated-slack-notifications/20794?u=juanlu_orchest (5 years late, I know)
