### ISSUE TITLE
Column title settings are not respected for pivot table values

### ISSUE THREAD

**Issue by gabriel-r** [metabase/metabase#17986] opened 2021-09-21 12:44 UTC
**Describe the bug**
When setting a custom name for a Pivot table value field, it is not applied to the table. 

**Logs**
No errors appear in the console or Network tab.

**To Reproduce**
1. Set up a Pivot table
2. Add two fields for Rows, i.e. two levels in the Pivot table
3. Add a few fields for Values. I used Count, Sum and Distinct operators.
4. Edit the names of the Rows and Values fields
5. RESULT: *Custom row names appear correctly. Value field names don't.*

**Expected behavior**
Custom names appear at the top of the table.

**Screenshots**
![image](https://user-images.githubusercontent.com/51084/134172975-40b9e024-2910-478f-937e-447cea706184.png)

**Information about your Metabase Installation:**

* CLOUD

- Your browser and the version: Chrome Version 93.0.4577.82 (Official Build) (x86_64)
- Your operating system: macOS 11.6 
- Your databases: Snowflake
- Metabase version: CLOUD

**Severity**
This makes using pivot tables very hard, as normal users will not guess that "Distinct values of Campaign → Name" should be "# Campaigns"

**Comment by flamber** [comment] 2021-09-21 12:49
Duplicate of #15353

**Closed by flamber** 2021-09-21 12:49 UTC
Labels: Type:Bug, .Needs Triage
