### ISSUE TITLE
Creating sandboxed access to a table based on a saved question from a different table is nonsensical

### ISSUE THREAD

**Issue by jeff303** [metabase/metabase#15228] opened 2021-03-18 19:41 UTC
**Describe the bug**

Creating a saved question `Q` for table `T1`, then defining sandboxed access to table `T2` (a completely different table, with different columns) using `Q` is allowed by the UI, but the result doesn't make any sense.

**Logs**
N/A

**To Reproduce**
1. Create any saved question `Q` for some table `T1`
2. As an admin, create sandboxed access to a different table, `T2`, using the question `Q`
3. As a limited (sandboxed) user, navigate to the table `T2`
4. Notice the results (limited columns, but all rows)

**Expected behavior**
Probably, no rows should be shown at all.

**Screenshots**

Sample of what can be seen when `T1` is the Users table from the sample dataset, and `T2` is the Orders table.

<img width="314" alt="disjoint_sandbox_question_table" src="https://user-images.githubusercontent.com/3521562/111687028-ce22ef80-87f7-11eb-90d0-00102aac9741.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 89
- Your operating system: OS X 11.2
- Your databases: H2
- Metabase version: 0.39 (snapshot)
- Metabase hosting environment: N/A
- Metabase internal database: H2

**Severity**
Moderate, since it's unclear what rows are actually shown, it might be the case that the intended data sandboxing aspect (i.e. hiding rows) isn't working at all.

**Additional context**
N/A

**Comment by flamber** [comment] 2021-03-18 19:47
This is a duplicate of #14612 - see issue(s) and PR(s) for more history.

**Closed** 2021-03-18 19:52 UTC
Labels: .Needs Triage, Type:Bug
