### ISSUE TITLE
Tooltip will not close on click

### ISSUE THREAD

**Issue by saho-tabakov** [metabase/metabase#6711] opened 2018-01-17 11:22 UTC
Hi,

When you click on a chart, except for PIE charts, the tooltip that pops-up will not close even if you click outside of it until page reload. This is really annoying especially on mobile devices. Can you please fix it or propose a workaround.

Thanks in advance.

- Your browser and the version: Chrome 63 both mobile and desktop, Firefox 52
- Your operating system: WinXP, Win10, Android
- Metabase version: 0.26, 0.27.1
- Metabase hosting environment: Linux
- Metabase internal database: H2

![image 1](https://user-images.githubusercontent.com/19468740/35040321-56a7e6de-fb89-11e7-9df5-ec4973467abb.png)

**Comment by ranquild** [comment] 2021-09-17 13:22
@flamber I couldn't reproduce this bug. When I click on a bar, it always shows a popover with actions, e.g. "Zoom in", "Breakout by" etc. Should we close this issue?

**Comment by flamber** [comment] 2021-09-17 13:56
@ranquild :+1: I guess it was fixed long ago, when one of the libraries was updated perhaps.

**Closed by flamber** 2021-09-17 13:56 UTC
Labels: Type:Bug, Type:UX, Priority:P3, Visualization/, Client:Mobile Web, Embedding/
