### ISSUE TITLE
Dashboards breaking after adding new question cards

### ISSUE THREAD

**Issue by alexandre-martins** [metabase/metabase#11142] opened 2019-10-15 16:34 UTC
**Describe the bug**
Sometimes, when I try to add a new question to a dashboard, it doesen't load properly. The new card with the question is added over an already existing card and, when I try to resize or move it, it sticks to the mouse cursor. Therefore I can't place it on the dash and can't save it.

It is important to note that this bug doesn't happen every time when I try to add a new question to a dashboard. However, once it happens, it keeps happening every time to a specific dashboard.

**Logs**
![image](https://user-images.githubusercontent.com/52791883/66850406-24c73280-ef4f-11e9-90d8-1acd272ca5ba.png)
![image](https://user-images.githubusercontent.com/52791883/66850429-2e509a80-ef4f-11e9-9dfd-04d85551301e.png)

**To Reproduce**
Create a new dashboard and try to import a question to it. It **can** happen. Not necessarly it will. But once it does happen, the bug is permanently installed in that dashboard.

**Expected behavior**
To properly load, place and resize new question cards to dashboards.

**Screenshots**
When it is loaded:

![image](https://user-images.githubusercontent.com/52791883/66850598-84254280-ef4f-11e9-9144-38b1c4dd3561.png)

When I try to move or resize the cards:

![image](https://user-images.githubusercontent.com/52791883/66850623-91423180-ef4f-11e9-898e-b78e8ff7f00a.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome/77.0.3865.75
- Your operating system: Ubuntu 19.04 and macOS 10.15 Catalina
- Your databases: postgres, mysql and bigquery
- Metabase version: 0.33.4
- Metabase hosting environment: Docker running on kubernetes
- Metabase internal database: Postgres

**Severity**
Blocking your usage of Metabase entirely

**Comment by flamber** [comment] 2019-10-15 16:50
Hi @alexandre-martins 
By any chance, are your questions Native (SQL)? And have you changed some of the columns of the question, which was used in the dashboard, after the question was added to the dashboard?
If yes, then it might be a duplicate of #9299 (check some of the comments)

If you can narrow down a way to reproduce the issue, then it would help a lot to fix the issue.

Just adding `Cannot read property 'card' of undefined`, since images cannot be searched.

**Comment by alexandre-martins** [comment] 2019-10-16 13:03
Hey @flamber!

Yes, the questions are all native SQL. The bug happens when I try to import a new question card, not when I try to modify one.

The problem with this bug is that it is not easily reproducible. I noticed it happening when the dashboard start getting big (~20 cards). Then, when I try to import a new question card, the bug happens. All the questions that I'am using come from querying a bigquery database, although we have mysql and postgres also connected to metabase.

Thanks for your reply! :)

**Comment by freakinruben** [comment] 2019-10-17 13:03
@alexandre-martins maybe we're experiencing the same thing (#11163 ), at least the symptoms sound the same! Can you try if the question that gives a problem works when you change the visualisation to `table`?

**Comment by flamber** [comment] 2020-05-25 09:17
@alexandre-martins 
There has been several fixes later versions for sticky cards on dashboards, when editing.
Are you still seeing this problem on latest release, 0.35.3?
If it only happens, when you add new cards to a dashboard - is there anything specific about the card you're adding or does it happen with any card?
Or are you combining multiple questions into a single card?

**Comment by flamber** [comment] 2021-11-07 18:46
Closing in favor of #13736

**Closed by flamber** 2021-11-07 18:46 UTC
Labels: Type:Bug, Priority:P2, Reporting/Dashboards
