### ISSUE TITLE
Add optional coloring of text in Number visualization

### ISSUE THREAD

**Issue by nodesocket** [metabase/metabase#27641] opened 2023-01-12 06:29 UTC
**Is your feature request related to a problem? Please describe.**
Requesting the ability to select a color for Number visualization text like we can currently select graph colors.

<img width="2030" alt="Screenshot 2023-01-12 at 12 24 53 AM" src="https://user-images.githubusercontent.com/523312/211993921-33e6a505-7542-49a3-b21d-8f6bcd07f2a2.png">

**Describe the solution you'd like**
Color picker for Number text same as graph color picker.

**How important is this feature to you?**
Would be a great new addition.

**Comment by paoliniluis** [comment] 2023-01-12 14:56
Hi @nodesocket, this is a duplicate of https://github.com/metabase/metabase/issues/5760

**Closed by paoliniluis** 2023-01-12 14:56 UTC
Labels: Type:New Feature, .Needs Triage
