### ISSUE TITLE
sql qb run button not showing when pasting a query on a saved question.

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#886] opened 2015-08-12 21:29 UTC

**Comment by tlrobinson** [comment] 2016-01-25 23:18
Unable to reproduce this, unless I'm misunderstanding:

![screencast](http://g.recordit.co/5hvaYOL9j3.gif)

**Comment by agilliland** [comment] 2016-01-25 23:59
I concur.  I can't reproduce this one either.  I think it's safe to close this one.

**Closed** 2016-01-26 02:00 UTC
Labels: Bug, Query Builder
