### ISSUE TITLE
Unable to save Permissions/Application

### ISSUE THREAD

**Issue by alyakh-gegi-llc** [metabase/metabase#33008] opened 2023-08-08 13:56 UTC
### Describe the bug

We use the Metabase with the SITE URL `https://example.com/reports/` setting (`/` at the end).
There is an error when we try to save changes on the `admin/permissions/application` page in the browser console:
```
PUT https://example.com/reportsapi/ee/advanced-permissions/application/graph 404
``` 
Changes are not saved.

It seems that the `/` at the end of the configured SITE URL is not taken into account and the url looks incorrect: `…reportsapi…`

### To Reproduce

1. Configure SITE URL `https://company.com/reports/`.
2. Go to `https://company.com/reports/admin/permissions/application`.
3. Change `Settings access`.
4. Click `Save changes`, `Yes`.
5. See error.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-EN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8",
    "os.name": "Linux",
    "os.version": "5.10.0-0.deb10.16-cloud-amd64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.42-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-07-28",
      "tag": "v1.46.6.4",
      "branch": "release-x.46.6.x",
      "hash": "7c60aca"
    },
    "settings": {
      "report-timezone": "America/Los_Angeles"
    }
  }
}
```

### Severity

There is no way to set permissions for a user group.

**Comment by paoliniluis** [comment] 2023-08-08 19:06
Duplicate of https://github.com/metabase/metabase/issues/30895

**Closed by paoliniluis** 2023-08-08 19:06 UTC
Labels: Type:Bug, .Needs Triage
