### ISSUE TITLE
Unable to click "Learn more" on custom expression

### ISSUE THREAD

**Issue by pawit-metabase** [metabase/metabase#17548] opened 2021-08-23 10:57 UTC
**Describe the bug**
Unable to click "Learn more" on custom expression

**Logs**
N/A

**To Reproduce**
1. Go to notebook editor
2. Add custom expression for filter or summary
3. Select  a function
4. Click "Learn More"

**Expected behavior**
A new tab should be opened to the documentation

Actual: the dialog closes

**Screenshots**

https://user-images.githubusercontent.com/88995137/130436218-18265aef-d8a9-4f56-bfaa-3d7084dc2b02.mov

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 92.0.4515.159
- Your operating system: macOS 11.5.2
- Your databases: Sample DB
- Metabase version: 0.40.2
- Metabase hosting environment: Jar file on macOS
- Metabase internal database: H2

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

Annoying

**Additional context**
N/A

**Comment by flamber** [comment] 2021-08-23 13:34
Regression since 0.39.4 - #15891
We want to allow focus in the helper, so links can be clicked and text can be copied.

**Comment by nemanjaglumac** [comment] 2021-08-23 16:38
Yeah, the link seems to be correct.
But the popover is closing too soon.

**Closed** 2021-09-08 02:49 UTC
Labels: Type:Bug, Priority:P3, .Frontend, Querying/GUI, .Regression
