### ISSUE TITLE
click Sharing or Sharing and embedding button, nothing happened but get DOMException message on console

### ISSUE THREAD

**Issue by xyd113** [metabase/metabase#20411] opened 2022-02-10 03:14 UTC
**Describe the bug**
**Chrome 96.0.4664.93** click Sharing or Sharing and embedding button, nothing happened but get DOMException message on console
**Safari** everything are ok

**Logs**
react-dom.production.min.js:209 DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of '@@History/c9m53r' exceeded the quota.
    at t.saveState (http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2295454)
    at f (http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2294816)
    at t.pushLocation (http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2294889)
    at http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2305930
    at http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2305614
    at c (http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2293780)
    at t.loopAsync (http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2293786)
    at w (http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2305452)
    at M (http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2305713)
    at Object.x [as push] (http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2306100)
os @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
vo @ react-dom.production.min.js:131
us @ react-dom.production.min.js:212
Ml @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
wl @ react-dom.production.min.js:248
ll @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
z @ react-dom.production.min.js:287
Zt @ react-dom.production.min.js:68
react-dom.production.min.js:123 Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of '@@History/c9m53r' exceeded the quota.
    at t.saveState (http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2295454)
    at f (http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2294816)
    at t.pushLocation (http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2294889)
    at http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2305930
    at http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2305614
    at c (http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2293780)
    at t.loopAsync (http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2293786)
    at w (http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2305452)
    at M (http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2305713)
    at Object.x [as push] (http://xx.x.xx.xxx:xxxx/app/dist/vendor.bundle.js?71ae27fc0b3400163d31:2:2306100)

**To Reproduce**
1. open chrome console
2. Go to dashboard
3. Click on Sharing and embedding

**Screenshots**
![image](https://user-images.githubusercontent.com/39815896/153330927-c5ffc3ce-1a98-465a-a1e3-35c0d91e2fa4.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: **Chrome 96.0.4664.93**
- Your operating system: OS X 10.15.5
- Your databases:  MySQL
- Metabase version:  v0.42.0
- Metabase hosting environment:  Docker
- Metabase internal database: default

**Comment by flamber** [comment] 2022-02-10 08:14
Duplicate of #20357

**Closed by flamber** 2022-02-10 08:14 UTC
Labels: Type:Bug, .Needs Triage
