### ISSUE TITLE
Binning is broken

### ISSUE THREAD

**Issue by mngr** [metabase/metabase#40708] opened 2024-03-28 00:47 UTC
### Describe the bug

Auto-binning is not helpful and setting the arbitrary bins count doesn't work

### To Reproduce

1. Go to New question
2. Choose Sample Database -> Accounts
3. Summarize Count by Seats
4. Visualize. You'll see 5 bins with 99% of values in the 1st bin:
<img width="1477" alt="Captura de ecrã 2024-03-28, às 00 31 29" src="https://github.com/metabase/metabase/assets/777800/fc7210a1-9f35-4812-843c-8265a9c26c71">

5. Open the editor again
6. Choose 100 bins as binning for Seats
7. Visualize. You'll see 26 bins, which is a bit more useful, but it's not 100:
<img width="1474" alt="Captura de ecrã 2024-03-28, às 00 34 42" src="https://github.com/metabase/metabase/assets/777800/9ae06599-703b-40b9-942f-feed8604f729">

### Expected behavior

When you set arbitrary amount of bins you should get the exact amount of bins you've set.
When you keep auto-binning it should choose the minimum amount of bins needed to have not more than 50% of the total in each of the bins (but not more than 100 bins).

### Information about your Metabase installation

```JSON
last version
```

### Severity

Very annoying, you have to set it to "don't bin" every time

**Comment by paoliniluis** [comment] 2024-03-28 00:54
Isn’t this a duplicate of https://github.com/metabase/metabase/issues/12004?

**Comment by ojjj13** [comment] 2024-03-28 03:11
You might get a more meaningful result if you choose x-axis to be linear and set up a filter, say < 200 in your case.

**Comment by ranquild** [comment] 2024-03-28 08:28
Duplicate https://github.com/metabase/metabase/issues/12004

**Closed by ranquild** 2024-03-28 08:28 UTC
Labels: Type:Bug, Priority:P2, Querying/Processor, .Backend
