### ISSUE TITLE
bug: JOINs on Saved Questions fail since last update

### ISSUE THREAD

**Issue by soltanianalytics** [metabase/metabase#13737] opened 2020-11-09 15:43 UTC
**Describe the bug**
Since the last update to v0.37.0.2, questions with joins on saved questions fail. It appears that the generated SQL is simply incorrect.

**To Reproduce**
1. Go to 'Ask a question'
2. Click on 'Custom question'
3. Select any table as starting data
4. Add a saved question as join
5. Click on Visualize

**Expected behavior**
Get a result

**Screenshots**
![image](https://user-images.githubusercontent.com/46958547/98561035-b2876580-22a8-11eb-9cd9-9779cf5b2b53.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.173-106.229.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-10-26",
      "tag": "v0.37.0.2",
      "branch": "release-x.37.x",
      "hash": "ba7be09"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

**Severity**
VERY severe. A lot of questions broke completely. Unfortunately, we also had an unrelated mistake in our backup retentions, so we cannot rollback the migration anymore. This is breaking a lot of reports across the entire company.

**Additional context**
It looks to me like the SQL generator fails. It simply uses the wrong alias in the query. Here is a sample generated query (this is a real query that I only anonymized and formatted):

```sql
SELECT
  "source"."A different field name" AS "A different field name"
  , count(distinct "source"."id") AS "count"
FROM (
  SELECT
      coalesce("analytics"."table_2"."field_1", 'Nicht vorhanden') AS "A different field name"
    , "analytics"."table_2"."id" AS "id"
    , "Question 594"."company_id" AS "company_id"
    , "analytics"."table_1"."field_2" AS "field_2"
    , "analytics"."table_1"."field_3" AS "field_3"
    , "analytics"."table_1"."field_4" AS "field_4"
    , "analytics"."table_1"."company_id" AS "company_id_2"
    , "analytics"."table_1"."field_5" AS "field_5"
    , "analytics"."table_2"."field_1" AS "field_1"
    , "analytics"."table_2"."field_6" AS "field_6"
    , "analytics"."table_2"."created_at" AS "created_at"
    , "analytics"."table_2"."field_7" AS "field_7"
    , "analytics"."table_2"."field_8" AS "field_8"
    FROM "analytics"."table_2"
      LEFT JOIN (
        SELECT
            "analytics"."table_1"."field_2" AS "field_2"
          , "analytics"."table_1"."field_3" AS "field_3"
          , "analytics"."table_1"."field_4" AS "field_4"
          , "analytics"."table_1"."company_id" AS "company_id"
          , "analytics"."table_1"."field_5" AS "field_5"
        FROM "analytics"."table_1"
        WHERE (
          ("analytics"."table_1"."field_2" = 'a value'
          OR "analytics"."table_1"."field_2" = 'a different value')
          AND "analytics"."table_1"."field_5" = TRUE)
      ) "Question 594" ON "analytics"."table_2"."id" = "Question 594"."company_id"
    ) "source"
WHERE (
  "source"."field_6" = 'another value'
  AND "source"."created_at" >= timestamp with time zone '2020-08-02 00:00:00.000+02:00'
  AND ("source"."field_7" = 'yet another value' OR "source"."field_7" = 'and one more value')
  AND "source"."field_8" > 0
  AND CAST("source"."created_at" AS date) BETWEEN CAST((CAST(now() AS timestamp) + (INTERVAL '-30 day')) AS date) AND CAST(now() AS date))
GROUP BY "source"."A different field name"
ORDER BY "count" DESC, "source"."A different field name" ASC
```
The corresponding Metabase screenshot:
![image](https://user-images.githubusercontent.com/46958547/98562120-faf35300-22a9-11eb-9ad9-81ea5971cfc1.png)

I also re-created the bug with this screenshot and SQL:
![image](https://user-images.githubusercontent.com/46958547/98562345-3ee65800-22aa-11eb-9b94-6a16c2c57fa1.png)

In that case, this happens when I want to see the SQL of that new question:
![image](https://user-images.githubusercontent.com/46958547/98562675-984e8700-22aa-11eb-941d-d5f488204fbc.png)

**Comment by flamber** [comment] 2020-11-09 16:03
From the error, it looks like a duplicate of #12928, but some of the referenced issues might come into play.

**Closed by flamber** 2020-11-09 16:03 UTC
Labels: .Needs Triage, Type:Bug

**Comment by soltanianalytics** [comment] 2020-11-09 16:06
May well be, however, if I remember correctly we had a newer version than 0.35.4.1

**Comment by flamber** [comment] 2020-11-09 16:10
@soltanianalytics Without specific version numbers or a way to reproduce (non-redacted, example with Sample Dataset), then it's difficult to tell.
