### ISSUE TITLE
Permissions Tab UI Stutters

### ISSUE THREAD

**Issue by fjcamillo** [metabase/metabase#6415] opened 2017-11-17 06:08 UTC
UI BUG

Here's a screenshot of which tab:
<img scr=https://ibin.co/3hZZlDnxdhDo.png>
https://ibin.co/3hZZlDnxdhDo.png

Permissions Dashboard Lower Part and Right Part Stutters if there are more than 4 or 5 groups as of now I have 7.
On the right part, the RD image and scroll bar moves left and right making it hard to be clicked properly.
On the lower part, the scroll bar moves up and down, making it also hard to be moved left or right.
Encountered this bug only at the Permissions Tab.
Will try uploading a video of the stutter later or the following day.

Browser: Chrome Version 62.0.3202.75 (Official Build) (64-bit)
Operating System: Ubuntu 16.04 LTS
Database: Postgres 9.6
Metabase Version: v0.26.1 Built on 2017-09-26
Metabase Hosting: Docker
Metabase Internal Database: Postgres 9.6

**Comment by attekei** [comment] 2018-01-22 11:09
Yeah, seems that our scroll syncing mechanism (`<ScrollSync>`+`<Grid>` React component combo) doesn't work very smoothly when you have scroll bars enabled and lots of overflowing horizontal content.

This is what I see when I scroll to the rightmost position, seems like the empty space between permissions grid and scroll bar equals to the width of the scroll bar:

<img width="1232" alt="screen shot 2018-01-22 at 13 01 25" src="https://user-images.githubusercontent.com/6034928/35217730-f8d1dff2-ff74-11e7-9aed-ccabd3b45a11.png">

**Comment by attekei** [comment] 2018-01-22 11:14
Seems to be caused by this hack
https://github.com/metabase/metabase/blob/69b10261c0e1d3e8e282fe7f6975969c060ac73a/frontend/src/metabase/admin/permissions/components/FixedHeaderGrid.jsx#L81

But that maybe doesn't explain the stuttering (or maybe it does).

**Comment by flamber** [comment] 2020-06-02 09:44
Closing in favor of #8165

**Closed by flamber** 2020-06-02 09:44 UTC
Labels: Administration/Permissions, Priority:P2, Type:Bug
