### ISSUE TITLE
Split y-axis manually

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4228] opened 2017-01-25 14:55 UTC
Now splitting works automatically:
![image](https://cloud.githubusercontent.com/assets/1708680/22295144/eb5ba6b6-e326-11e6-8939-6365cfd47111.png)

And I faced with problem when I want to show "Count" metric and "Percent" metric on the one chart:

![image](https://cloud.githubusercontent.com/assets/1708680/22295280/728dcaf6-e327-11e6-9477-69dbed173501.png)

**Comment by tlrobinson** [comment] 2017-01-25 16:19
Duplicate of #3242

**Closed by tlrobinson** 2017-01-25 16:19 UTC
Labels: Duplicate
