### ISSUE TITLE
Change local dynamic port

### ISSUE THREAD

**Issue by cwilby** [metabase/metabase#15318] opened 2021-03-24 18:26 UTC
**Is your feature request related to a problem? Please describe.**
I have an instance of Metabase on Docker that runs using `network_mode: host` in docker-compose.

I do this so that Metabase can communicate with a database that is within a Cisco VPN.

**Describe the solution you'd like**
It would be helpful to be able to change the port at the Dockerfile level via a `MB_PORT` environment variable.  I would use `ports: \n-51432:3000` but it is not supported in host networking mode.

**Describe alternatives you've considered**
I've thought about extending Metabase's docker file to install Cisco VPN, bypassing the need to use host networking.

**How important is this feature to you?**
I can work without it, I also think it could be useful to give users that flexibility.

**Comment by flamber** [comment] 2021-03-24 18:41
Hi @cwilby 
Sounds like a duplicate of #3734
Have you looked at `MB_JETTY_PORT`? https://www.metabase.com/docs/latest/operations-guide/environment-variables.html#mb_jetty_port

**Closed by flamber** 2021-03-24 18:41 UTC
Labels: .Needs Triage, Type:New Feature

**Comment by cwilby** [comment] 2021-03-25 20:04
🤦‍♂️ 

thanks!
