### ISSUE TITLE
Clicking on a Number card doesn't have "See these [records]" button

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#31830] opened 2023-06-23 19:16 UTC
**Is your feature request related to a problem? Please describe.**
For the Number card, when you click on the number, it only provides a breakout option. There is no "See these [records]" option. 

**Describe the solution you'd like**
There should be a "See these [records]" option so the user can easily see the individual records from the dashboard. 

**Describe alternatives you've considered**
Manually aggregate from Summarize. From a dashboard, I have to click thru to the question first, and then remove the aggregate function. 

**How important is this feature to you?**
Just convenience. 

**Additional context**
n/a

**Comment by paoliniluis** [comment] 2023-06-23 21:06
dupe of https://github.com/metabase/metabase/issues/4983

**Closed by paoliniluis** 2023-06-23 21:06 UTC
Labels: Type:New Feature, .Needs Triage
