### ISSUE TITLE
Ability to sort properly by both dimensions when there is a series in a graph

### ISSUE THREAD

**Issue by antoine-lizee** [metabase/metabase#25814] opened 2022-10-06 17:24 UTC
## Is your feature request related to a problem? Please describe

When you have a series breakout, the order cannot be fully controlled.

If you consider a simple `sales_table` as such
```
Year  |  Region | Sales 
---------------------
2016  |    US   | 10
2017  |    US   | 20
2018  |    US   | 10
2017  |   ASIA  | 8
2018  |   ASIA  | 36
```
... you cannot easily show a bar graph per region with most overall sales with a year breakout that makes sense.

Here is what I get:

<img width="645" alt="image" src="https://user-images.githubusercontent.com/2957716/194510747-9b0346d6-95a9-44d6-9770-c42926a86d62.png">

<details>
<summary> <strong>Full Code for REPEX </strong></summary>

```
WITH sales_table AS (
    SELECT *
    FROM (VALUES
    ('2017', 'ASIA', 8),
    ('2018', 'ASIA', 36),
    ('2016', 'US', 10),
    ('2017', 'US', 20),
    ('2018', 'US', 10)
    ) AS t(year, region, sales)
)
SELECT *
FROM sales_table
ORDER BY region, year
```
</details>

Here is what I want:

<img width="654" alt="image" src="https://user-images.githubusercontent.com/2957716/194510500-0fcfab87-a7a3-48e2-a7c4-4c295e4adca2.png">

## Describe the solution you'd like

When there is a breakout, you can select the order of the series (ASC, DESC), so that you can separately order series from the main dimension ( which can rely on the overall ordering)

## Describe alternatives you've considered

The only way to have the graph properly showed is to create a "dense template" with a cross join of all unique observations for each dimension, so that all possible rows are present, and the ordering of the table by both dimensions can be relied on to sort the main dimension _and_ the series. In the example, we need to add a `ASIA |  2016 | 0` row.

Practically, something like the following is needed:
```
WITH dense_template AS (
  SELECT *
  FROM (SELECT DISTINCT year FROM sales_table) AS t1
  CROSS JOIN (SELECT DISTINCT region FROM sales_table) AS t2
)
SELECT dense_template.year
, dense_template.region
, coalesce(sales_table.sales, 0)
FROM dense_template
LEFT JOIN sales_table USING (region, year)
ORDER BY region, year
```

## How important is this feature to you?
Creating those templates is super annoying, boilerplate, and actually prevent the use of the tool without SQL-wizardy and makes use of the query builder impossible.
It's one of those things that make SQL + Metabase feel like a cheap tool for junior analysts vs R or python. I want to root for SQL!

It's truly those seemingly little things that prevent broader use of MB in our company, so it's a bit more than "midly annoying" and a bit less than "blocking to get the job done".

Note that I'm super surprised that there are no issue talking about that problem, especially after so many improvements of MB over the recent years and what looks like a clear increase in user base. This problem seems like a pretty clear limitation of the "basic" usage of the tool, so there is a high probability that I've overlooked something. Please accept my apologies if I have!

**Comment by antoine-lizee** [comment] 2022-10-06 17:28
From the example above, here is what I'd like 
![image](https://user-images.githubusercontent.com/2957716/194379573-64c3ec31-49f3-4fa4-8b48-6c23545a0eff.png)

**Comment by antoine-lizee** [comment] 2022-10-07 08:10
(I Updated the OP for more clarity)

**Comment by antoine-lizee** [comment] 2022-10-07 08:42
(I Updated the OP for more clarity)

**Comment by flamber** [comment] 2022-10-07 08:46
Duplicate of #2339/#7625, which is being worked on in #24840

**Closed by flamber** 2022-10-07 08:46 UTC
Labels: Type:New Feature, .Needs Triage
