### ISSUE TITLE
nondeterministic JS crash when loading connections in object details

### ISSUE THREAD

**Issue by snarfed** [metabase/metabase#1254] opened 2015-10-14 20:57 UTC
...specifically, the _This X is connected to_ right side pane. sometimes happens very often, sometimes rarely. on average maybe 1/4-1/3 of all object detail page loads for me personally. when it happens, the spinners just keep spinning, and i see this crash in the JS console. probably not too useful since it's compiled/not symbolized, but still.

```
Error: ae is null
F/<@https://.../app/dist/app.bundle.js?aa53db267f5e69bc6c99:37:22754
l/</C[a]/E<@https://.../app/dist/vendor.bundle.js?aa53db267f5e69bc6c99:33:3048
dt/s/l.promise.then/c@https://.../app/dist/vendor.bundle.js?aa53db267f5e69bc6c99:36:27614
dt/a/<.then/<@https://.../app/dist/vendor.bundle.js?aa53db267f5e69bc6c99:36:28300
pt/this.$get</u.prototype.$eval@https://.../app/dist/vendor.bundle.js?aa53db267f5e69bc6c99:37:1626
pt/this.$get</u.prototype.$digest@https://.../app/dist/vendor.bundle.js?aa53db267f5e69bc6c99:37:189
pt/this.$get</u.prototype.$apply@https://.../app/dist/vendor.bundle.js?aa53db267f5e69bc6c99:37:1958
l@https://.../app/dist/vendor.bundle.js?aa53db267f5e69bc6c99:36:13325
v@https://.../app/dist/vendor.bundle.js?aa53db267f5e69bc6c99:36:15876
Ue/</b.onreadystatechange@https://.../app/dist/vendor.bundle.js?aa53db267f5e69bc6c99:36:16469
```

<img width="274" alt="screen shot 2015-10-14 at 1 56 43 pm" src="https://cloud.githubusercontent.com/assets/778068/10497569/742ab112-727b-11e5-9f86-5c50b3825460.png">

**Comment by salsakran** [comment] 2015-11-16 19:51
@snarfed you still getting bitten by this?

**Comment by snarfed** [comment] 2015-11-16 21:35
thanks for checking! i wasn't able to repro it just now after 10 tries. just fwiw.

**Comment by agilliland** [comment] 2015-11-16 23:00
cool.  closing this then as couldn't reproduce.

**Closed by agilliland** 2015-11-16 23:00 UTC
Labels: bug
