### ISSUE TITLE
Graph dates, still an issue in 0.25.1

### ISSUE THREAD

**Issue by cwbeck** [metabase/metabase#5642] opened 2017-07-31 11:00 UTC
The bug whereby dates are present on the x-axis are still showing the wrong (previous) month.

![screen shot 2017-07-31 at 11 55 19](https://user-images.githubusercontent.com/425262/28774914-6cf1b65e-75e7-11e7-84f1-868d723ff142.png)

The date here shows July 1st on mouse over which is correct, but the date at the bottom translated by the UI shows June.

**Comment by anki-code** [comment] 2017-07-31 12:31
Seems like this is the same as #4245

**Comment by cwbeck** [comment] 2017-07-31 13:07
@anki-code - it would look to be the same issue. I'm surprised it has not been resolved. There was a recent commit related to dates and I assumed this was part of it.

We get this only where grouping by month with BigQuery as our back-end.

**Comment by camsaul** [comment] 2017-07-31 23:03
Closing as duplicate of #4245

@cwbeck @anki-code we're doing a major effort to squash timezone-related bugs like this for our next major release so hopefully this will be fixed soon. Thanks for you patience while we figure things out 👍

**Closed by camsaul** 2017-07-31 23:03 UTC
Labels: Duplicate
