### ISSUE TITLE
Pointer stuck on left most character when typing a custom expression in query builder with Chrome 0.58

### ISSUE THREAD

**Issue by Digma** [metabase/metabase#4980] opened 2017-05-05 14:38 UTC
Hi,

I noticed a small but annoying bug when upgrading from Chrome 0.57 to chrome 0.58 on Mac OSX. In the query builder, the pointer get stuck on left most character when typing a custom expression. Neither using the mouse pointer or the keyboard arrow helps. Bug was the same for several of our users.

<img width="813" alt="screen shot 2017-05-05 at 16 32 48" src="https://cloud.githubusercontent.com/assets/3279847/25750163/25342dd0-31b1-11e7-8196-6229bd920b7f.png">

Steps to reproduce the bug:

- Open query builder
- Select any db / table
- Try to type a custom expression

Information:
- Your browser and the version: Chrome 0.58 (does not affect Chrome 0.57)
- Your operating system: OS X Sierra
- Metabase version: 0.23.1

**Comment by tlrobinson** [comment] 2017-05-05 15:06
Duplicate of #4906, resolved by #4969

**Closed by tlrobinson** 2017-05-05 15:06 UTC
