### ISSUE TITLE
Mysql datasource Part of the permission can't be open

### ISSUE THREAD

**Issue by jzdayz** [metabase/metabase#12331] opened 2020-04-16 04:59 UTC
**Describe the bug**

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Add new mysql datasource
2. Go to 'permissions'
3. Click on 'Part of the permission '

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/35563513/79416241-d5d38600-7fe1-11ea-849c-bf06ab90d61a.png)

js console:
```log
vendor.bundle.js?1636e40125c6bad14763:1 Uncaught TypeError: Cannot read property 'tables' of null
    at app-main.bundle.js?1636e40125c6bad14763:5
    at vendor.bundle.js?1636e40125c6bad14763:1
    at vendor.bundle.js?1636e40125c6bad14763:1
    at vendor.bundle.js?1636e40125c6bad14763:1
    at vendor.bundle.js?1636e40125c6bad14763:1
    at Function.mapToProps (app-main.bundle.js?1636e40125c6bad14763:5)
    at i (vendor.bundle.js?1636e40125c6bad14763:1)
    at Function.i.mapToProps (vendor.bundle.js?1636e40125c6bad14763:1)
    at i (vendor.bundle.js?1636e40125c6bad14763:1)
    at vendor.bundle.js?1636e40125c6bad14763:1


vendor.bundle.js?1636e40125c6bad14763:1 Uncaught (in promise) TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (vendor.bundle.js?1636e40125c6bad14763:1)
    at c.getHostNode (vendor.bundle.js?1636e40125c6bad14763:1)
    at Object.getHostNode (vendor.bundle.js?1636e40125c6bad14763:1)
    at Object.updateChildren (vendor.bundle.js?1636e40125c6bad14763:1)
    at Z._reconcilerUpdateChildren (vendor.bundle.js?1636e40125c6bad14763:1)
    at Z._updateChildren (vendor.bundle.js?1636e40125c6bad14763:1)
    at Z.updateChildren (vendor.bundle.js?1636e40125c6bad14763:1)
    at Z._updateDOMChildren (vendor.bundle.js?1636e40125c6bad14763:1)
    at Z.updateComponent (vendor.bundle.js?1636e40125c6bad14763:1)
    at Z.receiveComponent (vendor.bundle.js?1636e40125c6bad14763:1)
```

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.19.76-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-10",
      "tag": "v0.35.2",
      "branch": "release-0.35.x",
      "hash": "f3b2857"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by jzdayz** [comment] 2020-04-16 05:02
Also show table not working 

### step 1:
![image](https://user-images.githubusercontent.com/35563513/79416453-51353780-7fe2-11ea-8e70-eddeac689d5e.png)
### step 2:
![image](https://user-images.githubusercontent.com/35563513/79416478-5e522680-7fe2-11ea-8069-abab9e31c2ec.png)
### step 3:
![image](https://user-images.githubusercontent.com/35563513/79416507-6ca04280-7fe2-11ea-98e4-ba0b0935217f.png)
### step 4:
![image](https://user-images.githubusercontent.com/35563513/79416540-7cb82200-7fe2-11ea-9225-b53e5a29dded.png)

**Comment by flamber** [comment] 2020-04-16 09:18
Duplicate of #12269. It is fixed and will be part of 0.35.3

**Closed by flamber** 2020-04-16 09:18 UTC
Labels: .Needs Triage, Type:Bug

**Comment by jzdayz** [comment] 2020-04-22 02:03
> Duplicate of #12269. It is fixed and will be part of 0.35.3

It didn't work in my tests ( in version 0.35.3)

**Comment by jzdayz** [comment] 2020-04-22 02:04
same error

**Comment by flamber** [comment] 2020-04-22 09:38
Click "View tables" on the left instead of clicking "Limit access". There's an issue open on it #12372
