### ISSUE TITLE
Filters on static embedding are not respecting the filter dropdown type and defaulting to an input box when filters are connected to models

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#44702] opened 2024-06-25 17:56 UTC
### Describe the bug

A filter that's configured as a dropdown list of "a list of all values" is setting itself up as an input box on static embedding. This is a ux regression as the users don't know what's the value to input beforehand. This is only when a filter is connected to a model

### To Reproduce

1) set zip as "a list of all values" in the table metadata
2) build a GUI model (orders + people)
3) add the model to a dashboard
4) connect 2 filters: source and zip. Check that zip displays a list
![image](https://github.com/metabase/metabase/assets/1711649/cad9735c-6c27-41b3-b0b8-06190727fe41)

5) embed it passing the source as a parameter
6) see that zip doesn't display a list
![image](https://github.com/metabase/metabase/assets/1711649/02d774ac-38c8-44cd-9b6d-e41a77616bc3)

### Expected behavior

It shoul display the list on the embedded context

### Logs

NA, it does not even fire an api call

### Information about your Metabase installation

```JSON
v50.x
```

### Severity

P1 - regression - escalation as it's hitting a pro customer

### Additional context

If you don't use models this works
![image](https://github.com/metabase/metabase/assets/1711649/edb4b4bd-d009-408f-9eb4-02e097709f92)

**Comment by calherries** [comment] 2024-06-25 18:00
Looks like a duplicate of https://github.com/metabase/metabase/issues/44565. @ranquild since this was escalated and I probably misattributed it to the embedding team, perhaps you can close it as a dupe?

**Comment by ranquild** [comment] 2024-06-25 18:29
Closed by https://github.com/metabase/metabase/pull/44440

**Closed by ranquild** 2024-06-25 18:29 UTC
Labels: Type:Bug, Priority:P1, Querying/Parameters & Variables, .Escalation, .Team/QueryingComponents
