### ISSUE TITLE
On a fresh instance on 0.33, the SQL editor is not properly defaulting to the sample dataset and cannot be used

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#10568] opened 2019-08-13 16:47 UTC
**Describe the bug**
If you haven't added your own database and go to the native editor via "Ask a question" the editor is unresponsive and can't be used.

<img width="1691" alt="Screen Shot 2019-08-13 at 9 27 05 AM" src="https://user-images.githubusercontent.com/5248953/62960101-d494ee00-bdae-11e9-825e-307b2d6c2ea7.png">

**Logs**
<img width="578" alt="Screen Shot 2019-08-13 at 9 35 01 AM" src="https://user-images.githubusercontent.com/5248953/62959735-343ec980-bdae-11e9-91ca-74b051afcb08.png">

**To Reproduce**
1. On a fresh instance, go through the setup flow and then start a new native question 

**Information about your Metabase Installation:**
- Your browser and the version: Brave , Safari, Firefox
- Your operating system: OSX
- Your databases: H2
- Metabase version: release-0.33.x
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: H2

**Comment by flamber** [comment] 2019-08-13 19:50
@kdoh If you click the Write SQL button, does it then work? If yes, then it's the same as #10527

**Comment by tlrobinson** [comment] 2019-08-13 23:30
Duplicate of #10527

**Closed by tlrobinson** 2019-08-13 23:30 UTC
Labels: Priority:P0, Type:Bug
