### ISSUE TITLE
Timestamp field missing dropdown to cast data to Unix timestamp

### ISSUE THREAD

**Issue by josh289** [metabase/metabase#36377] opened 2023-12-04 21:34 UTC
**Describe the bug**

**Logs**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.10.184-175.731.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-11-07",
      "tag": "v1.47.7",
      "branch": "?",
      "hash": "dd51fd4"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
**To Reproduce**
1. Go to table metadata
2. Select table 18
3. Go to settings for Last Log In field
4. Not able to cast data

**Severity**
Blocking users on an urgent report

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.10.184-175.731.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-11-07",
      "tag": "v1.47.7",
      "branch": "?",
      "hash": "dd51fd4"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by zbodi74** [comment] 2024-05-17 16:01
@josh289 - Are you still experiencing this? Please describe the issue in detail and provide detailed reproduction instructions that are not specific to your database.

**Comment by darksciencebase** [comment] 2024-06-26 08:09
@josh289 have you been able to figure out the steps to reproduce this issue?

**Comment by darksciencebase** [comment] 2024-07-17 12:40
@josh289 closing the issue since there's not much for us to go on from, please leave a comment with more information if the problem persists.

**Closed by darksciencebase** 2024-07-17 12:40 UTC
Labels: .Needs Triage
