### ISSUE TITLE
Metabase assumes foriegn key is of type varchar

### ISSUE THREAD

**Issue by saarwasserman** [metabase/metabase#13281] opened 2020-09-21 08:57 UTC
**When pressing the link of a foreign key in a table, I am getting the following error:**

**ERROR: operator does not exist: integer = character varying Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts. Position: 931**

**I am seeing in the sql editor that the sql WHERE clause trying to equal == '1' and not == 1 (integer)**

**To Reproduce**
1. flask sql alchemy with postgres setup.
2. the primary keys and foreign keys are of type 'Integer'
3. storing relevant data in the database
4. In metabase, browsing data of the relevant table
5. Clicking on the foreign key link

**Expected behavior**
Seeing the foreign key's data model table

**Comment by flamber** [comment] 2020-09-21 09:03
Duplicate of #13263

**Closed by flamber** 2020-09-21 09:03 UTC
Labels: .Needs Triage, Type:Bug
