### ISSUE TITLE
Missing horizontal scrollbars on dashboards for wide data tables

### ISSUE THREAD

**Issue by VasekPurchart** [metabase/metabase#5372] opened 2017-06-21 15:02 UTC
Dashboard does not show any kind of horizontal scrollbar for a table, whose data are too wide. **The problem is then that the overflowing data are nowhere to be seen and even the user has no chance knowing, that they are even there if the column cutoff is in a particular place**. In my case these are links to other dashboards:

![2017-06-21_165031](https://user-images.githubusercontent.com/406821/27390577-efd0f3ce-56a1-11e7-89af-7270c4a59a53.png)

On the other hand the question view has this ability:

![2017-06-21_165054](https://user-images.githubusercontent.com/406821/27390648-1800e70a-56a2-11e7-969d-f06992bf736e.png)

Although here, there are two separate horizontal scrollbars (both working), which is not pretty, but at least this is usable (but probably still worth looking into, but prob a separate minor issue, because this is purely cosmetic).

---

- Your browser and the version: Version 59.0.3071.104 (Official Build) (64-bit)
- Your operating system: Ubuntu 16.04
- Metabase version: 0.24.2

- *Repeatable steps to reproduce the issue*:

1) Create question showing data which will not break on line end, probably good example is an URL, like in my case
2) Add this question to a dashboard, the needed data width of course depends on you resolution (but I tested it on multiple resolutions and no scrollbar ever appeared)

---

A bit offtopic - if anyone knows how to make the links shorter, this would of course be preferred, but until  there will be column types or something like that, I don't know about any other solution. Other option will be probably some drill downs, but that would probably work only for other metabase parts, but these links can as well be links to custom administration etc.

**Comment by flamber** [comment] 2019-02-15 18:51
Hi @VasekPurchart 
This seems to have been fixed - I cannot reproduce in 0.31.2 - but it also depends on the browser.
Firefox 65 (Ubuntu) without hovering the table:
![image](https://user-images.githubusercontent.com/1447303/52877511-cf1c5b00-311f-11e9-8abb-46aba4091eae.png)
Chromium 71 (Ubuntu) without hovering the table:
![image](https://user-images.githubusercontent.com/1447303/52877547-ed825680-311f-11e9-8d1d-2f0c0c5323ed.png)
Chromium 71 (Ubuntu) hovering the table:
![screenshot 2019-02-15 12 49 31](https://user-images.githubusercontent.com/1447303/52877657-3e924a80-3120-11e9-8a9d-3d703367c380.png)

**Comment by flamber** [comment] 2020-03-02 18:39
Closing issue because of no reply and I cannot reproduce on 0.34.3

**Closed by flamber** 2020-03-02 18:39 UTC
Labels: Reporting/Dashboards, Type:UX
