### ISSUE TITLE
Rename "last" to "previous" in smart numbers

### ISSUE THREAD

**Issue by mallchin** [metabase/metabase#9040] opened 2018-11-28 16:20 UTC
This is a suggestion to rename the wording in the smart description for smart numbers.

It currently says "last" but it would be better to use the word "previous".

The current description is suitable only if comparing the current period to the previous period as the previous period is also the last one (say this month to last month), but if comparing a previous period to a period before that it is nonsensical to say last (say last month to the month before that).

Assuming we're comparing sales for last month to the month before the automatic "smart" figure should read "was x sales the previous month" instead of "was x sales the last month".

**Comment by mazameli** [comment] 2018-11-28 18:39
Valid suggestion, but closing this issue as a duplicate of https://github.com/metabase/metabase/issues/8919

**Closed by mazameli** 2018-11-28 18:39 UTC
Labels: Duplicate

**Comment by mallchin** [comment] 2018-11-28 19:18
Sorry for the dupe!
