### ISSUE TITLE
Request for New Report Frequency Options

### ISSUE THREAD

**Issue by ubreathtaking** [metabase/metabase#35080] opened 2023-10-26 06:37 UTC
I am writing to request a new feature for our subscription report system. Currently, we have options for hourly, daily, weekly, and monthly reports, but we need the ability to generate reports at intervals of 6 months and 4 months as well.

This new feature will provide more flexibility for our reporting needs and allow us to align with specific project timelines. I kindly ask for your assistance in implementing this enhancement.

**Comment by paoliniluis** [comment] 2023-10-29 01:46
Duplicate of https://github.com/metabase/metabase/issues/3135

**Closed by paoliniluis** 2023-10-29 01:46 UTC
Labels: Type:New Feature, .Needs Triage
