### ISSUE TITLE
Admin Panel not showing error messages when adding Oracle DB

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#10583] opened 2019-08-14 19:08 UTC
When attempting to add an Oracle DB in 0.32.9 I was hitting `Next` and saw this error in the UI:

![Screen Shot 2019-08-14 at 12 05 25 PM](https://user-images.githubusercontent.com/1455846/63048653-d4b6eb80-be8b-11e9-828d-4bb14328c5d5.png)

However, in the server logs, I saw:

```
08-14 12:03:50 DEBUG middleware.log :: POST /api/setup/validate 400 1 ms (0 DB calls) 
{:errors {:dbname "You must specify the SID and/or the Service Name."}}
```

In other words, the API is returning an absolutely essential error message, but it is not being shown in the admin panel UI. I think the root issue is that since this error is not specific to a field we gave it `:dbname` (following the usual pattern of `{:errors {field message}` for DB setup error messages), but Oracle does not have a `dbname` field. 

In that case, I would expect the UI to show that message at the bottom instead of eating it and showing a generic `Server error encountered` error message.

**Comment by flamber** [comment] 2019-08-19 19:32
Is this a duplicate of #8298 - seems like it's a non-specific Oracle issue.

**Comment by paulrosenzweig** [comment] 2019-08-22 14:10
Resolved by #10644

**Closed by paulrosenzweig** 2019-08-22 14:10 UTC
Labels: .Frontend, Admin Panel & Setup, Priority:P1, Type:Bug
