### ISSUE TITLE
0.49.11:The data retrieved using a date picker is different from the data retrieved by directly entering the date.

### ISSUE THREAD

**Issue by congzhouliang** [metabase/metabase#43059] opened 2024-05-23 10:22 UTC
### Describe the bug

![image](https://github.com/metabase/metabase/assets/101546352/37024c5e-bb0c-483c-a015-a62e2cf08eb9)
 this is right
![image](https://github.com/metabase/metabase/assets/101546352/0d0e4246-0189-4898-8de7-34e5154ab7f3)
this wrong
The data retrieved using a date picker is different from the data retrieved by directly entering the date.
use oracle database
please helpme

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.0-58-generic",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "oracle",
      "mysql",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.2.0"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-05-16",
      "tag": "v0.49.11",
      "hash": "b894f2d"
    },
    "settings": {
      "report-timezone": "Asia/Shanghai"
    }
  }
}
```

### Severity

Severity

**Comment by ranquild** [comment] 2024-07-15 17:46
@congzhouliang could it be the case that you accidentally added time to the date? There is an issue that the filter widgets do not display time until you open the popover. If you specify your filter value via the URL it can happen as well.

![Image](https://github.com/user-attachments/assets/42915e92-b00f-4ed9-8b32-e54891fa1340)

**Comment by paoliniluis** [comment] 2024-09-01 01:29
@congzhouliang do you still hit this? otherwise we'll be closing the issue due to non-response

**Comment by ranquild** [comment] 2024-10-22 20:14
Duplicate of https://github.com/metabase/metabase/issues/39627

**Closed** 2024-10-22 20:14 UTC
Labels: Type:Bug, Priority:P2, Database/Oracle, Querying/Parameters & Variables, Querying/Native, .Frontend, .Team/Querying
