### ISSUE TITLE
Bug: Visualisation changes when translated into German

### ISSUE THREAD

**Issue by TrineFN** [metabase/metabase#9376] opened 2019-02-05 13:12 UTC
**Visualisation changes with German translation.** 

Users with English and German browsers see different visualisations in Metabase. 
We are using redshift, but replicated the issue using the sample dataset. 

**Example using the 'orders' table from the Sample Dataset.**
When using the custom question builder _Count_ column is translated into _Anzahl_ and the visualisation settings on _Count_ seems to be lost and _Anzahl_ is handled as a new column. 

I (with English browser) visualise "count" as a bar and save the question like this: 

![image](https://user-images.githubusercontent.com/24959279/52274295-88bf4300-294c-11e9-92ce-c4e49be00f71.png)

My colleagues with German browsers sees this: 

![image](https://user-images.githubusercontent.com/24959279/52274320-9e346d00-294c-11e9-9fa4-d36cc31ce369.png)

'Anzahl' (count) is now a line instead of bar and colour setting is also lost. 

Columns made as custom expression are not affected. 
![image](https://user-images.githubusercontent.com/24959279/52275303-75fa3d80-294f-11e9-81b9-ca3c35efbb39.png)

Details:
- My browser and the version: Chrome 71
- My operating system: OS X 10.14.1
- Metabase version: 0.31.2
- Metabase hosting environment:  Elastic Beanstalk

**Comment by flamber** [comment] 2019-06-20 18:11
Hi @TrineFN 
I think it was fixed by PR #9350. I cannot reproduce on 0.32.9

**Comment by flamber** [comment] 2020-03-03 14:56
Closing since there hasn't been any new reports and I cannot reproduce on 0.34.3

**Closed by flamber** 2020-03-03 14:56 UTC
Labels: .Unable to Reproduce, Customization/i18n, Priority:P3, Type:Bug, Visualization/Chart Settings
