### ISSUE TITLE
Can't upgrade/deploy Metabase to Heroku

### ISSUE THREAD

**Issue by TheoMorice** [metabase/metabase#9661] opened 2019-04-02 10:18 UTC
I am currently using the v0.30.0 version of Metabase on Heroku and need a new feature available in new versions. So i tried to upgrade my existing version of Metabase.

- Your browser and the version: Chrome 73.0
- Your operating system: MacOS Mojave 10.14.3
- Your databases: Postgres
- Metabase version: v0.32.1
- Metabase hosting environment: Heroku
- Metabase internal database: Postgres

### Repeatable steps to reproduce the issue
Since the "deploy to heroku" button does not allow to get the latest version of metabase, I tried this process instead: 

- Clone the latest version to your local machine:
git clone https://github.com/metabase/metabase-deploy.git  
cd metabase-deploy

- Add a git remote with your metabase setup:
git remote add heroku https://git.heroku.com/your-metabase-app.git

- Force push the new version to Heroku:
git push -f heroku master

Issues
--------
### - I first get an error with the version of npm (related to this topic : https://github.com/metabase/metabase/issues/8716 ) but resolved this by modify the package.json and specify my local version.

 Resolving node version >=8.11.4...
       Downloading and installing node 11.13.0...
       Bootstrapping npm 8.11.4 (replacing 6.7.0)...
       Unable to install npm 8.11.4; does it exist?
-----> Change to Node.js build process 
       Heroku has begun executing the "build" script defined in package.json
       during Node.js builds.
       Read more: https://devcenter.heroku.com/changelog-items/1573
-----> Build failed

### - Then i get another error and add to install yarn 

-----> Build
       Running build
       
       > metabase@0.0.0 build /tmp/build_682c182c0a4d9998cbf3a4b9ce297eca
       > yarn && webpack --bail
       
sh: 1: yarn: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! metabase@0.0.0 build: `yarn && webpack --bail`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the metabase@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.dt8qK/_logs/2019-03-27T09_55_20_792Z-debug.log
-----> Change to Node.js build process 
       Heroku has begun executing the "build" script defined in package.json
       during Node.js builds.
       Read more: https://devcenter.heroku.com/changelog-items/1573
-----> Build failed

### - Then the devDependencies started to be a problem

-----> Build
       Running build (yarn)
       yarn run v1.15.2
       $ yarn && webpack --bail
       $ echo $npm_execpath | grep -q yarn || echo '\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
       [1/5] Validating package.json...
       [2/5] Resolving packages...
       [3/5] Fetching packages...
warning gitbook-plugin-atoc@1.0.3: The engine "gitbook" appears to be invalid.
       info fsevents@1.2.7: The platform "linux" is incompatible with this module.
       info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
       [4/5] Linking dependencies...
warning " > grid-styled@4.3.3" has unmet peer dependency "styled-components@>=2.0 || >=3.0".
warning " > grid-styled@4.3.3" has unmet peer dependency "emotion@>=9.0".
warning " > grid-styled@4.3.3" has unmet peer dependency "react-emotion@>=9.0".
warning " > babel-plugin-styled-components@1.10.0" has unmet peer dependency "styled-components@>= 2".
warning " > postcss-cssnext@2.11.0" has unmet peer dependency "caniuse-db@^1.0.30000652".
       [5/5] Building fresh packages...
       success Saved lockfile.
internal/modules/cjs/loader.js:657
    throw err;
    ^
Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/tmp/build_30da1bc62d156168c14f11ce9f563e4a/webpack.config.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
-----> Change to Node.js build process 
       Heroku has begun executing the "build" script defined in package.json
       during Node.js builds.
       Read more: https://devcenter.heroku.com/changelog-items/1573
-----> Build failed

### - So, I tried both change the settings in Heroku for yarn_production=false; or put all the devDependencies into the dependencies for the package.json file. But get this error : 

ID 41ab43bf-4746-4418-b088-64fe82a09f9b
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       YARN_PRODUCTION=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  11.12.*
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  1.15.*
       
       Resolving node version 11.12.*...
       Downloading and installing node 11.12.0...
       Using default npm version: 6.7.0
       Resolving yarn version 1.15.*...
       Downloading and installing yarn (1.15.2)...
       Installed yarn 1.15.2
       
-----> Restoring cache
       Cached directories were not restored due to a change in version of node, npm, yarn or stack
       Module installation may take longer for this build
       
-----> Installing dependencies
       Installing node modules (yarn.lock)
       yarn install v1.15.2
       $ echo $npm_execpath | grep -q yarn || echo '\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       info fsevents@1.2.7: The platform "linux" is incompatible with this module.
       info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       warning " > grid-styled@4.3.3" has unmet peer dependency "styled-components@>=2.0 || >=3.0".
       warning " > grid-styled@4.3.3" has unmet peer dependency "emotion@>=9.0".
       warning " > grid-styled@4.3.3" has unmet peer dependency "react-emotion@>=9.0".
       warning " > babel-plugin-styled-components@1.10.0" has unmet peer dependency "styled-components@>= 2".
       warning " > postcss-cssnext@2.11.0" has unmet peer dependency "caniuse-db@^1.0.30000652".
       [4/4] Building fresh packages...
       Done in 67.10s.
       
-----> Build
       Running build (yarn)
       yarn run v1.15.2
       $ yarn && webpack --bail
       $ echo $npm_execpath | grep -q yarn || echo '\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
       [1/5] Validating package.json...
       [2/5] Resolving packages...
       [3/5] Fetching packages...
warning gitbook-plugin-atoc@1.0.3: The engine "gitbook" appears to be invalid.
       info fsevents@1.2.7: The platform "linux" is incompatible with this module.
       info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
       [4/5] Linking dependencies...
warning " > grid-styled@4.3.3" has unmet peer dependency "styled-components@>=2.0 || >=3.0".
warning " > grid-styled@4.3.3" has unmet peer dependency "emotion@>=9.0".
warning " > grid-styled@4.3.3" has unmet peer dependency "react-emotion@>=9.0".
warning " > babel-plugin-styled-components@1.10.0" has unmet peer dependency "styled-components@>= 2".
warning " > postcss-cssnext@2.11.0" has unmet peer dependency "caniuse-db@^1.0.30000652".
       [5/5] Building fresh packages...
       success Saved lockfile.
ModuleNotFoundError: Module not found: Error: Can't resolve 'styled-components' in '/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/frontend/src/metabase'
    at factoryCallback (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/webpack/lib/Compilation.js:282:40)
    at factory (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/webpack/lib/NormalModuleFactory.js:237:20)
    at resolver (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
    at asyncLib.parallel (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
    at /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/async/dist/async.js:3888:9
    at /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/async/dist/async.js:1062:13)
    at /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/async/dist/async.js:969:16
    at /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/async/dist/async.js:3885:13
    at resolvers.normal.resolve (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/webpack/lib/NormalModuleFactory.js:119:22)
    at onError (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/tapable/lib/Tapable.js:252:11)
    at /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/enhanced-resolve/lib/Resolver.js:166:11)
    at loggingCallbackWrapper (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/tapable/lib/Tapable.js:249:35)
resolve 'styled-components' in '/tmp/build_bb7bc16a2d2678650400867e5a7a83ac/frontend/src/metabase'
  Parsed request is a module
  using description file: /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/package.json (relative path: ./frontend/src/metabase)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/package.json (relative path: ./frontend/src/metabase)
    resolve as module
      /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/frontend/src/metabase/node_modules doesn't exist or is not a directory
      /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/frontend/src/node_modules doesn't exist or is not a directory
      /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/frontend/node_modules doesn't exist or is not a directory
      /tmp/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules
        using description file: /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/package.json (relative path: ./node_modules)
          using description file: /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/package.json (relative path: ./node_modules/styled-components)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/styled-components doesn't exist
            .webpack.js
              Field 'browser' doesn't contain a valid alias configuration
              /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/styled-components.webpack.js doesn't exist
            .web.js
              Field 'browser' doesn't contain a valid alias configuration
              /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/styled-components.web.js doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/styled-components.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/styled-components.jsx doesn't exist
            .css
              Field 'browser' doesn't contain a valid alias configuration
              /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/styled-components.css doesn't exist
            as directory
              /tmp/build_bb7bc16a2d2678650400867e5a7a83ac/node_modules/styled-components doesn't exist
Node#before is deprecated. Use Node#raws.before
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
-----> Change to Node.js build process 
       Heroku has begun executing the "build" script defined in package.json
       during Node.js builds.
       Read more: https://devcenter.heroku.com/changelog-items/1573
-----> Build failed

### - Other things tried : 
I tried to upgrade for less recent version of Metabase (30.0 , 31.0 , 32.0 ) -> same errors
I tried to launch a complete new application of Metabase on Heroku -> same errors

So I would appreciate any help to manage this upgrade, 
I can give further informations if needed.

Thank you, 
Théo

**Comment by camsaul** [comment] 2019-04-05 00:35
@tlrobinson when you're back in the pocket I could use some help figuring out how to fix this

**Comment by TomSesselmann** [comment] 2019-06-26 04:53
Not sure if this helps, but it could be related to the Buildpack? This is the error I was getting when I was trying to use the NodeJS Buildpack.

https://github.com/metabase/metabase/issues/8716#issuecomment-505716199

**Comment by flamber** [comment] 2020-05-30 18:20
Closing, since this was probably caused by outdated documentation/links, which has been corrected:
https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-heroku.html

**Closed by flamber** 2020-05-30 18:20 UTC
Labels: Operation/Heroku, Priority:P2, Type:Bug
