### ISSUE TITLE
Question isn't showing join in notebook editor

### ISSUE THREAD

**Issue by cbalusek** [metabase/metabase#50216] opened 2024-11-19 15:14 UTC
### Describe the bug

I have at least two older questions that start with a model that are joined to another model, and the joined model no longer appears in the notebook editor.  I have not made any changes to these questions in months.  I can see the join in the SQL editor, so the join is "there" - it's just not visible.

Example:  https://stats.metabase.com/question/13128-tickets-created-prior-month/notebook
Another example:  https://stats.metabase.com/question/19872-new-success-tickets-by-week-by-source

![Image](https://github.com/user-attachments/assets/979683a6-378c-4617-a2ff-dd7cc3ddabc2)

This makes editing the question almost impossible.  If I wanted to change this to a table and edit  the columns, I have to recreate the question from scratch.

### To Reproduce

I haven't been able to reproduce it 

### Information about your Metabase installation

```JSON
chrome
Built on 2024-11-19

Hash: 55ebe0b
```

### Severity

Very bad

**Comment by ranquild** [comment] 2024-11-22 20:54
Duplicate of https://github.com/metabase/metabase/issues/45041

**Closed by ranquild** 2024-11-22 20:54 UTC
Labels: Type:Bug, Priority:P1, Querying/GUI, .Team/Querying
