### ISSUE TITLE
After upgrading to 0.19.2 the card buttons have disappeared from LineAreaBarChart

### ISSUE THREAD

**Issue by andreeib** [metabase/metabase#3169] opened 2016-08-11 10:42 UTC
When editing a dashboard the "Add series" and "Remove" buttons have disappeared from the LineAreaBarChart cards.

This seems to be related to #3154 and the logic for LegendHeader.

*  I am using the Mozilla Firefox 47.0 browser.
*  My computer's OS is Ubuntu 14.04.4 LTS.
*  I'm running Metabase locally from the JAR and it is using the Postgres database.
*  My data is in a Postgres database.
*  My Metabase version is 0.19.2.

**Comment by tlrobinson** [comment] 2016-08-11 16:41
Duplicate of #3146

**Comment by andreeib** [comment] 2016-08-11 16:59
This seems to be happening only with the jar file. I checked out release-0.19.2 branch and made a dev build, the buttons are there

**Comment by andreeib** [comment] 2016-08-11 17:16
If the card already has multiple series then it shows the buttons.

**Comment by salsakran** [comment] 2016-08-12 22:45
@andreeib thank you for the catch!

we just pushed 0.19.3 which should fix this. apologies for the regression.

**Closed by salsakran** 2016-08-12 22:45 UTC

**Comment by andreeib** [comment] 2016-08-18 11:19
No problem. Thank you for fixing this so fast.
