### ISSUE TITLE
Added the ability to download data to publicly shared dashboards

### ISSUE THREAD

**Issue by Avey777** [metabase/metabase#38949] opened 2024-02-20 09:29 UTC
![image](https://github.com/metabase/metabase/assets/35259040/c4d1fea6-3903-47b0-84d8-1c215778f25e)

The dashboard of the system's public link can have the function of downloading results as shown above.

**Comment by ignacio-mb** [comment] 2024-02-20 17:53
Dupe of https://github.com/metabase/metabase/issues/6687

**Closed by ignacio-mb** 2024-02-20 17:53 UTC
Labels: Type:New Feature, .Needs Triage
