### ISSUE TITLE
Region Map does not render with "TypeError: X[t] is undefined" in browser console

### ISSUE THREAD

**Issue by shrike71** [metabase/metabase#9634] opened 2019-03-29 11:59 UTC
This issue might be possibly related to  #4684 . Might it be to do with the small number of rows?

The query is below.

![image](https://user-images.githubusercontent.com/748514/55231104-8f19bf00-5219-11e9-99dd-e3d47bb4611f.png)

Trying to apply a region map  to the query, although correctly identifying the metric and country columns, results in the error above.

I first saw this in a recent build of 0.32.0-RC, and it seems to have propagated into the 0.32 version.

Database is PostGres 10.4. 
System is Ubuntu 18.04 with Docker version 18.09.3, build 774a1f4
Issue evident in both jar file and Docker image version
Both jar and docker image produced from latest git master (0.32) without visible issues to either

I can see this in both the Docker version and the jar file version.

**Comment by flamber** [comment] 2019-03-29 13:29
Hi @shrike71 
It's actually a duplicate of #4684
You're seeing this because there's less than 5 different `Count` - if try something like this, then it works:
```SQL
SELECT 'AU' AS "COUNTRY", 1 AS "COUNT"
UNION ALL SELECT 'CA' AS "COUNTRY", 2 AS "COUNT"
UNION ALL SELECT 'DE' AS "COUNTRY", 3 AS "COUNT"
UNION ALL SELECT 'FR' AS "COUNTRY", 4 AS "COUNT"
UNION ALL SELECT 'GB' AS "COUNTRY", 5 AS "COUNT"
UNION ALL SELECT 'US' AS "COUNTRY", 6 AS "COUNT"
```

**Comment by shrike71** [comment] 2019-03-29 13:44
Hi Flamber,

Thanks for this. Altered my tests to reflect and it worked. However, we have a real scenario where we could have a query with a spread of less than 5 counts. Do you know if this an issue still to be addressed, or is it a limitation in that I have to consider not using the map as a visualization?

**Comment by flamber** [comment] 2019-03-29 14:15
@shrike71 
Go and upvote #4684 by clicking :+1:  - the more votes an issue gets, the more likely it'll be fixed sooner.
Right now I would avoid maps, if you know that there will be less than 5 different row counts.
And please close this issue :-)

**Closed** 2019-03-29 15:11 UTC
