### ISSUE TITLE
"Deploy to Heroku" button in `master` broken (*not* production Heroku deploys)

### ISSUE THREAD

**Issue by tannerchung** [metabase/metabase#8716] opened 2018-10-17 21:29 UTC
- Metabase hosting environment: Heroku
- Metabase internal database: Postgres

- *Repeatable steps to reproduce the issue*

Click on the Heroku button on the ReadME

```
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  >=8.11.4
       engines.npm (package.json):   8.11.4
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version >=8.11.4...
       Downloading and installing node 10.12.0...
       Bootstrapping npm 8.11.4 (replacing 6.4.1)...
       Unable to install npm 8.11.4; does it exist?
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by jorgeorpinel** [comment] 2019-01-30 00:52
Hello. Hoping I'm not just stating the obvious but I think the problem is there's no `npm` version 8.11.4

See https://github.com/metabase/metabase/blob/master/package.json#L10

I also left a note in https://github.com/metabase/metabase/commit/84c692a77b349d7498e83739baa2058b9bd77c28#commitcomment-32111645

**Comment by jorgeorpinel** [comment] 2019-01-30 01:35
Also @tlrobinson I think you meant to point us to https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-heroku.html#deploying-new-versions-of-metabase ?

**Comment by TomSesselmann** [comment] 2019-06-26 04:45
I was having this issue when I was trying to deploy a forked version of Metabase to Heroku.

I was able to fix it by changing the Heroku Buildpack. The above error occurs when you try to use the NodeJS Buildpack but because it's a Clojure app you need to use the Clojure Buildpack.
However, the problem with the default Heroku Clojure Buildpack is that it fails because it doesn't include Yarn, so I had to copy some of the code from the NodeJS Buildpack to the Clojure Buildpack.

You can see my custom Buildpack here https://github.com/heroku/heroku-buildpack-clojure/compare/master...TomSesselmann:master

You can see that it's just the standard [Clojure Buildpack](https://github.com/heroku/heroku-buildpack-clojure/blob/master/lib/common.sh) with some of the code from the [NodeJS Buildpack](https://github.com/heroku/heroku-buildpack-nodejs/blob/master/lib/binaries.sh)

Feel free to use my Buildpack, but I'd recommend forking it because I may need to change it in the future.

**Comment by tlrobinson** [comment] 2019-06-27 19:54
@TomSesselmann the solution to that is to use both `nodejs` and `clojure` buildbpacks, which we automatically do when using the Deploy button via `app.json`: https://github.com/metabase/metabase/blob/master/app.json#L20-L23

If you don't use the "Deploy" button you need to manually set the buildpacks like this:

```
heroku buildpacks:add https://github.com/heroku/heroku-buildpack-nodejs
heroku buildpacks:add https://github.com/heroku/heroku-buildpack-clojure
```

I think @jorgeorpinel is correct that at least part of the problem is that we're declaring a non-existent `npm` version in engines. We should be declaring `yarn` anyway since we don't support using `npm`. I tried fixing that but ran into another issue with the `babel-register` module not being found.

**Comment by salsakran** [comment] 2019-07-30 22:39
calling this a  P3 since we don't really recommend deploying master to Heroku

**Comment by flamber** [comment] 2020-10-07 08:21
Closing this, since we really don't recommend deploying master on Heroku and we're removing the link from the readme.

**Closed by flamber** 2020-10-07 08:21 UTC
Labels: .Building & Releasing, Operation/Heroku, Priority:P3, Type:Bug
