### ISSUE TITLE
Cannot filter by date from Dashboard on Custom Columns containing dates

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#27366] opened 2022-12-21 13:56 UTC
**Describe the bug**
When a Custom Column outputs a date, then it's not possible to filter by date from the Dashboard.

**Logs**

`ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: Output of unwrap-field-clause does not match schema:`

<details><summary>Full stacktrace</summary>

```
[(not (present? :field)) (not (present? "id-or-name")) (not (present? "options"))]  
{:database_id 1,
 :started_at #t "2022-12-21T13:43:30.053466Z[GMT]",
 :error_type :invalid-query,
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true, :ignore-cached-results? false},
  :database 1,
  :query {:source-table 2, :expressions {"custom_time" [:field 41 nil]}},
  :parameters
  [{:type :date/relative, :value "past1weeks", :target [:dimension [:expression "custom_time"]], :id "aa2fa77f"}],
  :async? true,
  :cache-ttl nil},
 :native nil,
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> models.params$fn__40605$unwrap_field_clause__40610.invoke(params.clj:35)"
  "query_processor.middleware.parameters.mbql$fn__51255$build_filter_clause__51260$fn__51270.invoke(mbql.clj:57)"
  "query_processor.middleware.parameters.mbql$fn__51255$build_filter_clause__51260.invoke(mbql.clj:44)"
  "query_processor.middleware.parameters.mbql$expand.invokeStatic(mbql.clj:86)"
  "query_processor.middleware.parameters.mbql$expand.invoke(mbql.clj:72)"
  "query_processor.middleware.parameters$expand_mbql_params.invokeStatic(parameters.clj:36)"
  "query_processor.middleware.parameters$expand_mbql_params.invoke(parameters.clj:32)"
  "query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:48)"
  "query_processor.middleware.parameters$expand_one.invoke(parameters.clj:40)"
  "query_processor.middleware.parameters$expand_all$replace_51356__51357.invoke(parameters.clj:58)"
  "mbql.util.match.impl$replace_in_collection$iter__23552__23556$fn__23557.invoke(impl.cljc:44)"
  "mbql.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:43)"
  "mbql.util.match.impl$replace_in_collection.invoke(impl.cljc:38)"
  "query_processor.middleware.parameters$expand_all$replace_51356__51357.invoke(parameters.clj:58)"
  "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:58)"
  "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:52)"
  "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:55)"
  "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:52)"
  "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:76)"
  "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:72)"
  "query_processor.middleware.parameters$fn__51372$substitute_parameters_STAR___51377$fn__51378.invoke(parameters.clj:81)"
  "query_processor.middleware.parameters$fn__51372$substitute_parameters_STAR___51377.invoke(parameters.clj:78)"
  "query_processor.middleware.parameters$substitute_parameters.invokeStatic(parameters.clj:108)"
  "query_processor.middleware.parameters$substitute_parameters.invoke(parameters.clj:100)"
  "query_processor$preprocess_STAR_$fn__54997.invoke(query_processor.clj:127)"
  "query_processor$preprocess_STAR_.invokeStatic(query_processor.clj:125)"
  "query_processor$preprocess_STAR_.invoke(query_processor.clj:120)"
  "query_processor$fn__55005$combined_pre_process__55006$combined_pre_process_STAR___55007.invoke(query_processor.clj:209)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__53450$fn__53455.invoke(resolve_database_and_driver.clj:35)"
  "driver$do_with_driver.invokeStatic(driver.clj:76)"
  "driver$do_with_driver.invoke(driver.clj:72)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__53450.invoke(resolve_database_and_driver.clj:34)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__49450.invoke(fetch_source_query.clj:314)"
  "query_processor.middleware.store$initialize_store$fn__49640$fn__49641.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:45)"
  "query_processor.store$do_with_store.invoke(store.clj:39)"
  "query_processor.middleware.store$initialize_store$fn__49640.invoke(store.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__53722.invoke(normalize_query.clj:22)"
  "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__60456.invoke(handle_audit_queries.clj:130)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__50728.invoke(constraints.clj:53)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__53661.invoke(process_userland_query.clj:145)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__54033.invoke(catch_exceptions.clj:167)"
  "query_processor.reducible$async_qp$qp_STAR___45482$thunk__45484.invoke(reducible.clj:100)"
  "query_processor.reducible$async_qp$qp_STAR___45482$fn__45486.invoke(reducible.clj:105)"],
 :card_id 1,
 :context :dashboard,
 :error
 "Output of unwrap-field-clause does not match schema: \n\n\t   [(not (present? :field)) (not (present? \"id-or-name\")) (not (present? \"options\"))]  \n\n",
 :row_count 0,
 :running_time 0,
 :preprocessed nil,
 :ex-data
 {:type :schema.core/error,
  :value nil,
  :error [(not (present? :field)) (not (present? "id-or-name")) (not (present? "options"))]},
 :data {:rows [], :cols []}}
```

</details>

**To Reproduce**
1. Question > Sample Dataset > Orders
2. Custom Column [Created At] as "CC"
3. Save Question -> Add it to Dashboard
4. Add Filter -> Time -> All Options -> Link to CC
5. Select Today and notice error

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/110378427/208921530-c5d9b117-d020-49f4-8ce2-469770abc262.png">

**Expected behavior**
I am able to filter by the selected date. If i filter directly on the question I have no issue it's when i filter from the dashboard that i get the error

**Information about your Metabase Installation:**

Metabase 44.6 and 45.1

**Comment by flamber** [comment] 2022-12-21 14:01
Duplicate of #17775

**Closed by flamber** 2022-12-21 14:01 UTC
Labels: Type:Bug, .Needs Triage
