### ISSUE TITLE
Custom Columns are not working on 0.36.x when joining tables

### ISSUE THREAD

**Issue by alekseyp** [metabase/metabase#13272] opened 2020-09-18 03:51 UTC
**Describe the bug**
Requests will fail when joining multiple tables and trying to add _any_ custom column.
Basically ALL (100%) of our question with custom column are failing after upgrading to 0.36.6.
Those were working on 0.35.3.

I was able to reproduce it with Sample Dataset:

**Logs**
```
Column "Product.ID" not found; SQL statement: CREATE FORCE VIEW PUBLIC._15 AS SELECT (1 + 1) AS "test", "source".PRODUCT_ID AS PRODUCT_ID, "Product".ID AS ID, "source".TAX AS TAX, "source".PRODUCT_ID AS PRODUCT_ID_2, "source"."sum" AS "sum" FROM ( SELECT PUBLIC.ORDERS.PRODUCT_ID AS PRODUCT_ID, SUM(PUBLIC.ORDERS.TAX) AS "sum" FROM PUBLIC.ORDERS LEFT OUTER JOIN PUBLIC.PRODUCTS "Product" ON PUBLIC.ORDERS.PRODUCT_ID = "Product".ID GROUP BY PUBLIC.ORDERS.PRODUCT_ID ORDER BY 1 ) "source" [42122-197]
```

```
09-18 03:43:09 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 1,
 :started_at #t "2020-09-18T03:43:08.875356Z[UTC]",
 :state "42S22",
 :json_query
 {:type "query",
  :query
  {:source-query
   {:source-table 2,
    :joins [{:fields "all", :source-table 1, :condition ["=" ["field-id" 3] ["joined-field" "Product" ["field-id" 26]]], :alias "Product"}],
    :aggregation [["sum" ["field-id" 8]]],
    :breakout [["field-id" 3]]},
   :expressions {:test ["+" 1 1]}},
  :database 1,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"sum\" AS \"sum\", \"source\".\"test\" AS \"test\" FROM (SELECT (1 + 1) AS \"test\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"Product\".\"ID\" AS \"ID\", \"source\".\"TAX\" AS \"TAX\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID_2\", \"source\".\"sum\" AS \"sum\" FROM (SELECT \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", sum(\"PUBLIC\".\"ORDERS\".\"TAX\") AS \"sum\" FROM \"PUBLIC\".\"ORDERS\" LEFT JOIN \"PUBLIC\".\"PRODUCTS\" \"Product\" ON \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" = \"Product\".\"ID\" GROUP BY \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" ORDER BY \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" ASC) \"source\") \"source\" LIMIT 2000",
  :params nil},
 :status :failed,
 :class org.h2.jdbc.JdbcSQLException,
 :stacktrace
 ["org.h2.message.DbException.getJdbcSQLException(DbException.java:357)"
  "org.h2.message.DbException.get(DbException.java:179)"
  "org.h2.message.DbException.get(DbException.java:155)"
  "org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)"
  "org.h2.expression.Alias.optimize(Alias.java:51)"
  "org.h2.command.dml.Select.prepare(Select.java:858)"
  "org.h2.command.Parser.prepare(Parser.java:263)"
  "org.h2.engine.Session.prepare(Session.java:576)"
  "org.h2.table.TableView.compileViewQuery(TableView.java:120)"
  "org.h2.table.TableView.initColumnsAndTables(TableView.java:172)"
  "org.h2.table.TableView.init(TableView.java:113)"
  "org.h2.table.TableView.<init>(TableView.java:70)"
  "org.h2.table.TableView.createTempView(TableView.java:559)"
  "org.h2.command.Parser.readTableFilter(Parser.java:1367)"
  "org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:2138)"
  "org.h2.command.Parser.parseSelectSimple(Parser.java:2287)"
  "org.h2.command.Parser.parseSelectSub(Parser.java:2133)"
  "org.h2.command.Parser.parseSelectUnion(Parser.java:1946)"
  "org.h2.command.Parser.parseSelect(Parser.java:1919)"
  "org.h2.command.Parser.parsePrepared(Parser.java:463)"
  "org.h2.command.Parser.parse(Parser.java:335)"
  "org.h2.command.Parser.parse(Parser.java:307)"
  "org.h2.command.Parser.prepareCommand(Parser.java:278)"
  "org.h2.engine.Session.prepareLocal(Session.java:611)"
  "org.h2.engine.Session.prepareCommand(Session.java:549)"
  "org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)"
  "org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)"
  "org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1135)"
  "com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:267)"
  "--> driver.sql_jdbc.execute$fn__72545.invokeStatic(execute.clj:239)"
  "driver.sql_jdbc.execute$fn__72545.invoke(execute.clj:237)"
  "driver.sql_jdbc.execute$prepared_statement_STAR_.invokeStatic(execute.clj:257)"
  "driver.sql_jdbc.execute$prepared_statement_STAR_.invoke(execute.clj:254)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:387)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)"
  "driver.sql_jdbc$fn__73933.invokeStatic(sql_jdbc.clj:49)"
  "driver.sql_jdbc$fn__73933.invoke(sql_jdbc.clj:47)"
  "driver.h2$fn__72752.invokeStatic(h2.clj:82)"
  "driver.h2$fn__72752.invoke(h2.clj:79)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
  "query_processor.context.default$default_runf.invoke(default.clj:67)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__45635.invoke(mbql_to_native.clj:26)"
  "query_processor.middleware.check_features$check_features$fn__44911.invoke(check_features.clj:42)"
  "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__45800.invoke(optimize_datetime_filters.clj:133)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47328.invoke(wrap_value_literals.clj:137)"
  "query_processor.middleware.annotate$add_column_info$fn__43532.invoke(annotate.clj:574)"
  "query_processor.middleware.permissions$check_query_permissions$fn__44786.invoke(permissions.clj:64)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__46318.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__44984.invoke(cumulative_aggregations.clj:61)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__46850.invoke(resolve_joins.clj:183)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39262.invoke(add_implicit_joins.clj:245)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__45596.invoke(large_int_id.clj:44)"
  "query_processor.middleware.limit$limit$fn__45621.invoke(limit.clj:38)"
  "query_processor.middleware.format_rows$format_rows$fn__45576.invoke(format_rows.clj:81)"
  "query_processor.middleware.desugar$desugar$fn__45050.invoke(desugar.clj:22)"
  "query_processor.middleware.binning$update_binning_strategy$fn__44076.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__44592.invoke(resolve_fields.clj:24)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__38811.invoke(add_dimension_projections.clj:318)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39018.invoke(add_implicit_clauses.clj:141)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39411.invoke(add_source_metadata.clj:105)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__46515.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__43717.invoke(auto_bucket_datetimes.clj:125)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__44639.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.parameters$substitute_parameters$fn__46300.invoke(parameters.clj:114)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__44691.invoke(resolve_referenced.clj:80)"
  "query_processor.middleware.expand_macros$expand_macros$fn__45306.invoke(expand_macros.clj:158)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__39442.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47212.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526$fn__46530.invoke(resolve_database_and_driver.clj:33)"
  "driver$do_with_driver.invokeStatic(driver.clj:61)"
  "driver$do_with_driver.invoke(driver.clj:57)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526.invoke(resolve_database_and_driver.clj:27)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45524.invoke(fetch_source_query.clj:267)"
  "query_processor.middleware.store$initialize_store$fn__47221$fn__47222.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__47221.invoke(store.clj:10)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__44568.invoke(cache.clj:209)"
  "query_processor.middleware.validate$validate_query$fn__47230.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__45648.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39280.invoke(add_rows_truncated.clj:36)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47197.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__44927.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__46389.invoke(process_userland_query.clj:136)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__44870.invoke(catch_exceptions.clj:174)"
  "query_processor.reducible$async_qp$qp_STAR___38074$thunk__38075.invoke(reducible.clj:101)"
  "query_processor.reducible$async_qp$qp_STAR___38074.invoke(reducible.clj:107)"
  "query_processor.reducible$sync_qp$qp_STAR___38083$fn__38086.invoke(reducible.clj:133)"
  "query_processor.reducible$sync_qp$qp_STAR___38083.invoke(reducible.clj:132)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:215)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:211)"
  "query_processor$fn__47372$process_query_and_save_execution_BANG___47381$fn__47384.invoke(query_processor.clj:227)"
  "query_processor$fn__47372$process_query_and_save_execution_BANG___47381.invoke(query_processor.clj:219)"
  "query_processor$fn__47416$process_query_and_save_with_max_results_constraints_BANG___47425$fn__47428.invoke(query_processor.clj:239)"
  "query_processor$fn__47416$process_query_and_save_with_max_results_constraints_BANG___47425.invoke(query_processor.clj:232)"
  "api.dataset$fn__50707$fn__50710.invoke(dataset.clj:55)"
  "query_processor.streaming$streaming_response_STAR_$fn__35496$fn__35497.invoke(streaming.clj:73)"
  "query_processor.streaming$streaming_response_STAR_$fn__35496.invoke(streaming.clj:72)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
  "async.streaming_response$do_f_async$fn__23282.invoke(streaming_response.clj:85)"],
 :context :ad-hoc,
 :error
 "Column \"Product.ID\" not found; SQL statement:\nCREATE FORCE VIEW PUBLIC._15 AS\nSELECT\n    (1 + 1) AS \"test\",\n    \"source\".PRODUCT_ID AS PRODUCT_ID,\n    \"Product\".ID AS ID,\n    \"source\".TAX AS TAX,\n    \"source\".PRODUCT_ID AS PRODUCT_ID_2,\n    \"source\".\"sum\" AS \"sum\"\nFROM (\n    SELECT\n        PUBLIC.ORDERS.PRODUCT_ID AS PRODUCT_ID,\n        SUM(PUBLIC.ORDERS.TAX) AS \"sum\"\n    FROM PUBLIC.ORDERS\n    LEFT OUTER JOIN PUBLIC.PRODUCTS \"Product\"\n        ON PUBLIC.ORDERS.PRODUCT_ID = \"Product\".ID\n    GROUP BY PUBLIC.ORDERS.PRODUCT_ID\n    ORDER BY 1\n) \"source\" [42122-197]",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:type :query,
  :query
  {:source-query
   {:source-table 2,
    :joins [{:strategy :left-join, :source-table 1, :condition [:= [:field-id 3] [:joined-field "Product" [:field-id 26]]], :alias "Product"}],
    :aggregation [[:aggregation-options [:sum [:field-id 8]] {:name "sum"}]],
    :breakout [[:field-id 3]],
    :order-by [[:asc [:field-id 3]]]},
   :expressions {:test [:+ 1 1]},
   :source-metadata
   [{:name "PRODUCT_ID", :id 3, :table_id 2, :display_name "Product ID", :base_type :type/Integer, :special_type :type/FK, :fingerprint {:global {:distinct-count 200, :nil% 0.0}}, :settings nil}
    {:name "sum", :display_name "Sum of Tax", :base_type :type/Float, :special_type nil, :settings nil}],
   :fields [[:field-literal "PRODUCT_ID" :type/Integer] [:field-literal "sum" :type/Float] [:expression "test"]],
   :limit 2000},
  :database 1,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :nested? false,
   :query-hash [36, -3, 122, 75, -101, 45, -61, 60, 23, 12, -116, 54, 124, 98, -57, -92, 58, -104, -38, -51, -68, 63, -75, -101, 118, 101, 111, 107, -85, 70, -85, 22]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :data {:rows [], :cols []}}
```

**To Reproduce**
Steps to reproduce the behaviour:
Join Sample Dataset Orders with Products and add custom Test column with 1+1 formula.
Try to visualize and you will get an error. 

**Expected behavior**
See test column  with values of 2

**Screenshots**
<img width="1246" alt="Screen Shot 2020-09-17 at 11 38 24 PM" src="https://user-images.githubusercontent.com/1569335/93553052-109a6b00-f940-11ea-9c97-ebb5822e082f.png">

<img width="1268" alt="Screen Shot 2020-09-17 at 11 38 33 PM" src="https://user-images.githubusercontent.com/1569335/93553051-109a6b00-f940-11ea-88e1-91e439d6c68e.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome/85.0.4183.102
- Your operating system: Intel Mac OS X 10_15_6
- Your databases: Postgres
- Metabase version: 0.36.6
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
blocking some users

**Comment by alekseyp** [comment] 2020-09-18 04:12
Maybe related to https://github.com/metabase/metabase/issues/12762

**Comment by flamber** [comment] 2020-09-18 08:00
Duplicate of #12762

**Closed by flamber** 2020-09-18 08:00 UTC
Labels: .Needs Triage, Type:Bug
