### ISSUE TITLE
Adding a user with no email settings enabled still attempts to send an email with account info

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5622] opened 2017-07-27 19:39 UTC
On master, when I try to add a user on a test instance without email enabled I get a confirmation that an email was sent.

In the server logs, I see
```
07-27 12:37:22 WARN metabase.email :: Failed to send email:  null
07-27 12:37:22 DEBUG metabase.middleware :: POST /api/user 200 (187 ms) (6 DB calls)
```

I'd expect to get a confirmation dialog with the new users password

**Comment by camsaul** [comment] 2017-07-27 19:45
@salsakran I just did the exact same thing about half hour ago (created a user on a new instance with no email set up) and got the dialog with the password

**Comment by camsaul** [comment] 2017-07-27 19:46
FWIW I also see a `Failed to send email` message in the logs but I get the Temporary Password dialog

**Comment by attekei** [comment] 2017-08-30 19:26
I can't reproduce the issue. Seems that the temporary password dialog is shown based on `email_configured` setting that is received from the backend. I don't know if there are scenarios when `email_configured` accidentally has wrong value – maybe a failure to load user settings on page load or something like that?

It's true that backend calls the email sending method in `POST /api/user` and logs `Failed to send email:  SMTP host is not set.` warning.

Closing this for now, let's open again if we are able to reproduce the issue.

**Closed by attekei** 2017-08-30 19:26 UTC
Labels: Admin Panel & Setup, Bug, Priority/P1
