### ISSUE TITLE
auto-calculated value for the default value of the Date type Field Filter

### ISSUE THREAD

**Issue by xujijun** [metabase/metabase#26032] opened 2022-10-20 09:50 UTC
![QQ截图20221020175158](https://user-images.githubusercontent.com/5730332/196917195-469ecc49-c5d8-4b1f-a257-a42781e89068.png)
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am seeing the default Filter Date always the same date, like "2021-10-20". It is getting more and more data from DB.

**Describe the solution you'd like**
I'd like the default value in the Date Filter changeable, such as, today minus 30 days.

**Describe alternatives you've considered**
There is not any alternatives.

**How important is this feature to you?**
Lots of my colleagues have the same pain.

**Additional context**

**Comment by flamber** [comment] 2022-10-20 09:57
Duplicate of #4509

**Closed by flamber** 2022-10-20 09:57 UTC
Labels: Type:New Feature, .Needs Triage
