### ISSUE TITLE
Display as Foreign field doesn't work when used in table view with joined fields

### ISSUE THREAD

**Issue by jrosenthal** [metabase/metabase#8422] opened 2018-08-29 01:04 UTC
Your databases: default custom dataset
Metabase version: 0.30.1
Metabase hosting environment: windows, jar 
Metabase internal database: default

Using default dataset and a clean install
-  Query Orders
- change data model for orders so that product id display values is using another field - ie: title
- refresh (notice product id column displays titles)
- Using table visualization interface, add the product.ein to the viewed fields
- refresh (notice product id column displays id again)

Possibly related to: 
https://github.com/metabase/metabase/issues/8421

**Comment by flamber** [comment] 2019-02-21 22:19
Hi @jrosenthal 
I cannot reproduce your issue on 0.31.2 - can you test that version and see if you still see the problem?
![image](https://user-images.githubusercontent.com/1447303/53205423-e2ce3280-35f3-11e9-93d0-1d3ab9b9740b.png)

**Comment by camsaul** [comment] 2019-06-17 19:31
This should be fixed in 0.32.9

**Comment by flamber** [comment] 2020-03-18 11:38
Closing since I have not been able to reproduce since 0.31.2 - latest release is 0.34.3

**Closed by flamber** 2020-03-18 11:38 UTC
Labels: Administration/Data Model, Priority:P3, Querying/GUI, Type:Bug
