### ISSUE TITLE
API - Searching for archived card with pagination doesn't work

### ISSUE THREAD

**Issue by MathRobin** [metabase/metabase#46564] opened 2024-08-07 10:08 UTC
### Describe the bug

When i ask the API for archived cards, I only get the first 2000 results (always the same so), with this 

```https://***.metabaseapp.com/api/card?f=archived```

But i know that i have more than 2000 cards archived. So i wanted to get next page of results or full result maybe (like with json card query). But nothing seems to work.
I've tried requests like this one:

```https://***.metabaseapp.com/api/card?f=archived&offset=2000```
or
```https://***.metabaseapp.com/api/card?f=archived&offset=2000&limit=1000```
Both not working

### To Reproduce

1. Have more than 2000 questions archived
2. Use your API keys to request your archived questions
3. try to access to the 2001+ questions archived

### Expected behavior

Maybe be query filter are not limit & offset. Nothing in doc or wasn't able to find how pagination works.

### Information about your Metabase installation

```JSON
- Cloud version
```

### Severity

very annoying

### Additional context

I use this to know wich questions i can automatically force cache refresh. Without correct & complete results, i can't do my work correctly

**Comment by dpsutton** [comment] 2024-08-07 13:55
On a recent master, I see

```shell
❯ http get "localhost:3000/api/card?f=archived" x-api-key:$API_KEY -pb  | jq 'length'
3108
```

On 0.49.15,

```shell
❯ http get 'localhost:3049/api/card?f=archived' x-api-key:$API_KEY -pb | jq 'length'
3000
```

Checking on 0.50.17:

```shell
❯ http get 'localhost:3050/api/card?f=archived' x-api-key:$API_KEY -pb | jq 'length'
3000
```

I"m not sure I'm able to reproduce.

(if the 3,000 number looks suspicious, i just created that many in a fresh 49 instance and then upgraded to 50)
```clojure
card=> (let [coll (t2/insert-returning-instance! :model/Collection {:name "lots-of-archived-cards"})]
         (t2/insert! :model/Card (repeatedly 3000 (fn [] {:name (str (gensym "archived-card"))
                                                          :dataset_query {}
                                                          :collection_id (:id coll)
                                                          :archived true
                                                          :database_id 1
                                                          :display :table
                                                          :visualization_settings {}
                                                          :creator_id 1}))))
3000
```

In the version based on master, was a local dev instance with some other cruft in it which is why count is 3108.

**Comment by MathRobin** [comment] 2024-08-12 14:39
@dpsutton maybe i'm wrong, maybe i misunderstood your answer. For me, you're talking about counting hits possible, not the real results.
Imagine limit is not 2000 but 2 (for our readability). Your full table is :
```
A
B
C
D
E
F
G
H
I
J
```
With the current API call, i will get :

- without any param
```
A
B
```
- with any other param combination inside (count, limit, offset, page...)
```
A
B
```
same result, yes.
My hope was to get this when 
```
api/card?f=archived&offset=2&limit=2
C
D
```

**Comment by dpsutton** [comment] 2024-08-19 16:17
@MathRobin I'm pushing back on your original complaint.

> When i ask the API for archived cards, I only get the first 2000 results (always the same so), with this

I demonstrate that this is false. I get 3000 results back and do not see any limit. 

> For me, you're talking about counting hits possible, not the real results. The api is sending back 3000 archived cards.

I'm using `jq` to count the number of "real results" that come back.

To your original repro:

> To Reproduce
>    Have more than 2000 questions archived
>    Use your API keys to request your archived questions
>    try to access to the 2001+ questions archived

I piped 3000 cards through `jq` and counted them.

Note here

```
❯ http get 'localhost:3050/api/card?f=archived' x-api-key:$API_KEY | jq 'length'
3000
```
Is getting all 3000 archived cards back from the api

Here's the last one, using `jq '.[-1]'`

```
❯ http get 'localhost:3050/api/card?f=archived' x-api-key:$API_KEY | jq '.[-1]'
{
  "cache_invalidated_at": null,
  "description": null,
  "archived": true,
  "view_count": 0,
  "collection_position": null,
  "table_id": null,
  "result_metadata": null,
  "creator": {
    "email": "dan@metabase.com",
    "first_name": "dan",
    "last_login": "2024-08-19T11:07:02.960006-05:00",
    "is_qbnewb": true,
    "is_superuser": true,
    "id": 1,
    "last_name": "sutton",
    "date_joined": "2024-08-19T11:07:02.849951-05:00",
    "common_name": "dan sutton"
  },
  "initially_published_at": null,
  "database_id": 1,
  "enable_embedding": false,
  "collection_id": 3,
  "query_type": null,
  "name": "archived-card4302",
  "last_used_at": null,
  "type": "question",
  "creator_id": 1,
  "updated_at": "2024-08-19T11:08:32.451865-05:00",
  "made_public_by_id": null,
  "embedding_params": null,
  "cache_ttl": null,
  "dataset_query": {},
  "id": 3026,
  "parameter_mappings": [],
  "display": "table",
  "entity_id": "N8k6V_IFTDk_yJt2b_SAM",
  "collection_preview": true,
  "visualization_settings": {},
  "collection": {
    "authority_level": null,
    "description": null,
    "archived": false,
    "slug": "lots_of_archived_cards",
    "name": "lots-of-archived-cards",
    "personal_owner_id": null,
    "type": null,
    "is_sample": false,
    "id": 3,
    "entity_id": "Z7mBS2qDfqLw9tagqOw0L",
    "location": "/",
    "namespace": null,
    "created_at": "2024-08-19T11:08:30.711111-05:00"
  },
  "metabase_version": "v0.50.19 (0b97bf8)",
  "parameters": [],
  "created_at": "2024-08-19T11:08:32.451865-05:00",
  "public_uuid": null
}
```


```
# I'm getting 3,880,955 characters back from the API
❯ http get 'localhost:3050/api/card?f=archived' x-api-key:$API_KEY  | wc
       0    6001 3880955

# pretty print it with `jq` and it's 177,000 lines!
❯ http get 'localhost:3050/api/card?f=archived' x-api-key:$API_KEY  |jq |  wc -l
  177002
```

I think all of this demonstrates that I'm getting _all_ cards back from the endpoint

```
When i ask the API for archived cards, I only get the first 2000 results (always the same so), with this

https://***.metabaseapp.com/api/card?f=archived
```
So I believe that this is false.

The API is not paginated at all. There is no expectation to get the second page because you get all cards. I'm not sure why you are seeing only 2,000 results but it doesn't seem to be the standard behavior for Metabase.

**Comment by paoliniluis** [comment] 2024-08-19 20:37
I just did a test:
1) archived all the questions
![image](https://github.com/user-attachments/assets/62ba2fdb-bbee-460f-b49a-c131d8de0a1f)

2) hit the endpoint and sent it to a json file
![image](https://github.com/user-attachments/assets/b1ca2d08-2923-48a0-840c-ec4443c98023)

3) counted how many "result_ metadata" keys I got
![image](https://github.com/user-attachments/assets/fda64368-415e-43c6-b9c4-09e381095414)


tl,dr; we're not paginating the results of this endpoint unless you're using anything in the middle

p.s. tested with 50.20.3

**Comment by dpsutton** [comment] 2024-08-23 13:25
Closing this as it seems we provide all cards and there is no expectation to paginate at the moment.

**Closed by dpsutton** 2024-08-23 13:25 UTC
Labels: Type:Bug, Priority:P2, .Team/AdminWebapp

**Comment by MathRobin** [comment] 2024-08-23 20:01
Are hou kidding me ? I've more than 3k questions archived. And i confirm that pagination should be there.

**Comment by MathRobin** [comment] 2024-08-23 20:03
I dont understand how as database query tool, you can say "no pagination need". It's the first useful thing when querying results

**Comment by dpsutton** [comment] 2024-08-26 13:35
@MathRobin I'm confused by your response. We send all cards in the response. I've demonstrated that above. Thus at the moment there is no need for pagination to see all results because all results are sent over. 

I'm demonstrating here that I'm able to get all 6,640 archived cards in a cloud hosted instance of Metabase.

```shell
❯ http get "$CLOUD_HOST/api/card?f=archived" x-api-key:$API_KEY -pb | jq 'length'
6640
```

We seem to be talking past each other here. I've show that I'm able to get all archived cards both in the cloud and locally hosted.

It seems for some reason you are unable to get all of your archived cards. I don't know why this is the case but it is not the design or implementation of Metabase to paginate these results at the moment. I do not understand why you are not seeing every archived card in your instance.

**Comment by MathRobin** [comment] 2025-04-16 09:08
I can confirm there is a current limit on your cloud version. You can say what you want, i'm still capped at 2000 results for this call.
