### ISSUE TITLE
Pie overflow on dashboard

### ISSUE THREAD

**Issue by orthagh** [metabase/metabase#8589] opened 2018-09-26 08:44 UTC
- Your browser and the version: Firefox 60 ESR
- Your operating system: Win 7 / Ubuntu 18.04
- Your databases: Mysql
- Metabase version: 0.30.4
- Metabase hosting environment: Linux/Centos 6.7
- Metabase internal database: H2

- *Repeatable steps to reproduce the issue*
A pie chart inserted in a dashboard, with a lot of slices and legend displayed, overflows from its card (4*5)

![image](https://user-images.githubusercontent.com/418844/46068208-92e85e00-c170-11e8-93c1-c693ca0711f9.png)

If i hide legend or increase card size, it's ok, but before 0.30, this pie card displayed correctly with legend

**Comment by mazameli** [comment] 2018-10-24 17:02
Reproduced this on master.

**Comment by vi-vsn** [comment] 2018-12-04 16:22
Any chance of the fix for this making it into the next point release?

**Comment by flamber** [comment] 2020-05-12 08:34
This was fixed in one of the 0.33.x releases - I cannot reproduce on 0.35.3:
![image](https://user-images.githubusercontent.com/1447303/81661038-d7a33480-943b-11ea-9dda-81c5d2328cdf.png)

**Closed by flamber** 2020-05-12 08:34 UTC
Labels: Priority:P2, Type:Bug, Visualization/
