### ISSUE TITLE
changing a model's query, resets custom column-names to default (when using joined tables)

### ISSUE THREAD

**Issue by Harm01** [metabase/metabase#26128] opened 2022-10-27 11:21 UTC
**Describe the bug**
When I create a model from a question that has joined tables, every time I change the definition of the model, the custom-column names from the joined tables are reset to their default values.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. create a model from a question with some joined tables and change the column names of the joined tables.
2. create a new question with your model
3. change the query-definition
4. change something on your query (for example add an extra column to show)
5. re-run your question or save your definition.
6. See error (the column names of the joined tables are changed to their default values)

**Expected behavior**
The custum column names should stay the same after changing something in the query.

**Screenshots**
In the animated gif below I show the procedure to reproduce the problem. Please note that I cut the bottom of the browser window so you see no real results, only the column headers. You can clearly see that the custom-column-name 'Projectnaam' is changed to 'Applications Vtab - A_65f98792 → Projectnaam', where Applications Vtab is the name of the joined table.

![animated gif to show the problem](https://grietman.raldee.net/index.php/s/fenSc3ZfCx3jCyE/download/changing_query_within_a_model.gif)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "nl",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "5.4.0-126-generic",
    "user.language": "en",
    "user.timezone": "Europe/Amsterdam"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "oracle"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-10-17",
      "tag": "v0.44.5",
      "branch": "release-x.44.x",
      "hash": "29fab4d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
It is rather annoying to change these column names every time I change something to the query of a model. It would save a lot of time (and frustration) when this is fixed.

**Additional context**

**Comment by flamber** [comment] 2022-10-27 11:32
Duplicate of #22517

**Closed by flamber** 2022-10-27 11:32 UTC
Labels: Type:Bug, .Needs Triage
