### ISSUE TITLE
Pie or donut charts turn off the total function

### ISSUE THREAD

**Issue by snycc15** [metabase/metabase#19904] opened 2022-01-25 09:17 UTC
It is suggested to add a selector switch for the intermediate aggregation function of pie or donut visual resources to turn off or turn on the aggregation function.
![image](https://user-images.githubusercontent.com/67908124/150947014-5585e1ca-8587-45c0-8c43-26c67931c186.png)

**Comment by flamber** [comment] 2022-01-25 09:20
Duplicate of #9432

**Closed by flamber** 2022-01-25 09:20 UTC
Labels: Type:New Feature, .Needs Triage
