### ISSUE TITLE
Dashboards rerun all queries when saving

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#9778] opened 2019-04-12 19:49 UTC
Not such a big deal for tons of smaller queries but if you have a huge number of Cards on the dashboard or the queries are very slow running it's a lot of unnecessary server and data warehouse load.

**Comment by flamber** [comment] 2019-07-29 21:23
Isn't this a duplicate of #5332?

**Comment by flamber** [comment] 2020-05-31 16:40
Closing in favor of #5332

**Closed by flamber** 2020-05-31 16:40 UTC
Labels: Reporting/Dashboards, Type:Performance

**Comment by camsaul** [comment] 2020-05-31 16:58
This happens even if your dashboard doesn't have parameters

**Comment by flamber** [comment] 2020-05-31 17:13
@camsaul I cannot reproduce that - I can see requests `/api/dashboard/:id` on Cancel/Save of dashboard with/out filters, but no requests to `/api/card/:id/query`. Can you help reproduce?
Or do you mean #8030 ?
