### ISSUE TITLE
Google Analytics data is not output normally.

### ISSUE THREAD

**Issue by haji8-balaan** [metabase/metabase#12682] opened 2020-06-11 12:37 UTC
**Describe the bug**

I am investigating GA data.

I created a chart to add and compare user and sassion metrics.

User data is coming out as 0 in question.

If I put this question in the dashboard, the data is output normally.

**Logs**

No error log is displayed.
Below may be an unrelated error log.
```
[]  ERROR metabase.driver.sql-jdbc.execute Failed to set timezone 'Asia/Seoul' for :mysql database
[]  ERROR metabase.driver.sql-jdbc.execute Failed to set timezone 'Asia/Seoul' for :mysql database
[]  DEBUG metabase.middleware.log POST /api/card/24/query 202 [ASYNC: completed] 45.8 ms (12 DB calls) App DB connections: 1/1 Jetty threads: 4/50 (2 idle, 0 queued) (137 total active threads) Queries in flight: 3 (0 queued)
[]  DEBUG metabase.middleware.log POST /api/card/31/query 202 [ASYNC: completed] 18.7 ms (11 DB calls) App DB connections: 1/1 Jetty threads: 4/50 (2 idle, 0 queued) (137 total active threads) Queries in flight: 2 (0 queued)
[]  DEBUG metabase.middleware.log POST /api/card/38/query 202 [ASYNC: completed] 572.7 ms (10 DB calls) App DB connections: 0/1 Jetty threads: 4/50 (2 idle, 0 queued) (137 total active threads) Queries in flight: 1 (0 queued)
[]  ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: null
{:database_id 8,
:started_at (t/zoned-date-time "2020-06-11T12:22:18.368Z[Etc/UTC]"),
:via
[{:status :failed,
:class org.eclipse.jetty.io.EofException,
:error nil,
:stacktrace
["org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:283)"
"org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422)"
"org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)"
"org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381)"
"org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:827)"
"org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)"
"org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223)"
"org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:549)"
"org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:829)"
"org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:901)"
"org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:283)"
"org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:267)"
"org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:705)"
"java.util.zip.DeflaterOutputStream.flush(DeflaterOutputStream.java:282)"
"--> async.streaming_response$delay_output_stream$fn__23135.invoke(streaming_response.clj:120)"
"async.streaming_response.proxy$java.io.OutputStream$ff19274a.flush(Unknown Source)"
"query_processor.streaming.json$fn$reify__33619.write_row_BANG_(json.clj:62)"
"query_processor.streaming$streaming_rff$fn__34073$fn__34074.invoke(streaming.clj:35)"
"query_processor.middleware.process_userland_query$add_and_save_execution_info_xform_BANG_$execution_info_rf_STAR___43875.invoke(process_userland_query.clj:95)"
"query_processor.reducible$combine_additional_reducing_fns$fn__38113.invoke(reducible.clj:212)"
"query_processor.middleware.add_rows_truncated$add_rows_truncated_xform$fn__39284.invoke(add_rows_truncated.clj:28)"
"query_processor.middleware.format_rows$format_rows_xform$fn__43109.invoke(format_rows.clj:75)"
"query_processor.middleware.limit$limit_xform$fn__43132.invoke(limit.clj:25)"
"query_processor.context.default$default_reducef$fn__38004.invoke(default.clj:59)"
"query_processor.context.default$default_reducef.invokeStatic(default.clj:58)"
"query_processor.context.default$default_reducef.invoke(default.clj:49)"
"query_processor.context$reducef.invokeStatic(context.clj:69)"
"query_processor.context$reducef.invoke(context.clj:62)"
"query_processor.context.default$default_runf$respond_STAR___38008.invoke(default.clj:70)"
"driver.googleanalytics.execute$execute_reducible_query.invokeStatic(execute.clj:129)"
"driver.googleanalytics.execute$execute_reducible_query.invoke(execute.clj:122)"
"driver.googleanalytics$eval108056$fn__108057.invoke(googleanalytics.clj:157)"
"query_processor.context$executef.invokeStatic(context.clj:59)"
"query_processor.context$executef.invoke(context.clj:48)"
"query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
"query_processor.context.default$default_runf.invoke(default.clj:67)"
"query_processor.context$runf.invokeStatic(context.clj:45)"
"query_processor.context$runf.invoke(context.clj:39)"
"query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
"query_processor.reducible$pivot.invoke(reducible.clj:31)"
"query_processor.middleware.mbql_to_native$mbql__GT_native$fn__43149.invoke(mbql_to_native.clj:26)"
"query_processor.middleware.check_features$check_features$fn__42463.invoke(check_features.clj:42)"
"query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__43314.invoke(optimize_datetime_filters.clj:133)"
"query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47282.invoke(wrap_value_literals.clj:137)"
"query_processor.middleware.annotate$add_column_info$fn__41084.invoke(annotate.clj:577)"
"query_processor.middleware.permissions$check_query_permissions$fn__42338.invoke(permissions.clj:64)"
"query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__43813.invoke(pre_alias_aggregations.clj:40)"
"query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__42536.invoke(cumulative_aggregations.clj:61)"
"query_processor.middleware.resolve_joins$resolve_joins$fn__44345.invoke(resolve_joins.clj:183)"
"query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39271.invoke(add_implicit_joins.clj:245)"
"query_processor.middleware.limit$limit$fn__43135.invoke(limit.clj:38)"
"query_processor.middleware.format_rows$format_rows$fn__43116.invoke(format_rows.clj:81)"
"query_processor.middleware.desugar$desugar$fn__42602.invoke(desugar.clj:22)"
"query_processor.middleware.binning$update_binning_strategy$fn__41628.invoke(binning.clj:229)"
"query_processor.middleware.resolve_fields$resolve_fields$fn__42144.invoke(resolve_fields.clj:24)"
"query_processor.middleware.add_dimension_projections$add_remapping$fn__38807.invoke(add_dimension_projections.clj:272)"
"query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39027.invoke(add_implicit_clauses.clj:147)"
"query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39420.invoke(add_source_metadata.clj:105)"
"query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__44010.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
"query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__41269.invoke(auto_bucket_datetimes.clj:125)"
"query_processor.middleware.resolve_source_table$resolve_source_tables$fn__42191.invoke(resolve_source_table.clj:46)"
"query_processor.middleware.parameters$substitute_parameters$fn__43795.invoke(parameters.clj:97)"
"query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__42243.invoke(resolve_referenced.clj:80)"
"query_processor.middleware.expand_macros$expand_macros$fn__42858.invoke(expand_macros.clj:158)"
"query_processor.middleware.add_timezone_info$add_timezone_info$fn__39451.invoke(add_timezone_info.clj:15)"
"query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47166.invoke(splice_params_in_response.clj:32)"
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__44021$fn__44025.invoke(resolve_database_and_driver.clj:33)"
"driver$do_with_driver.invokeStatic(driver.clj:61)"
"driver$do_with_driver.invoke(driver.clj:57)"
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__44021.invoke(resolve_database_and_driver.clj:27)"
"query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__43064.invoke(fetch_source_query.clj:243)"
"query_processor.middleware.store$initialize_store$fn__47175$fn__47176.invoke(store.clj:11)"
"query_processor.store$do_with_store.invokeStatic(store.clj:46)"
"query_processor.store$do_with_store.invoke(store.clj:40)"
"query_processor.middleware.store$initialize_store$fn__47175.invoke(store.clj:10)"
"query_processor.middleware.cache$maybe_return_cached_results$fn__42120.invoke(cache.clj:209)"
"query_processor.middleware.validate$validate_query$fn__47184.invoke(validate.clj:10)"
"query_processor.middleware.normalize_query$normalize$fn__43162.invoke(normalize_query.clj:22)"
"query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39289.invoke(add_rows_truncated.clj:36)"
"query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47151.invoke(results_metadata.clj:128)"
"query_processor.middleware.constraints$add_default_userland_constraints$fn__42479.invoke(constraints.clj:42)"
"query_processor.middleware.process_userland_query$process_userland_query$fn__43884.invoke(process_userland_query.clj:136)"
"query_processor.middleware.catch_exceptions$catch_exceptions$fn__42422.invoke(catch_exceptions.clj:174)"
"query_processor.reducible$async_qp$qp_STAR___38090$thunk__38091.invoke(reducible.clj:101)"
"query_processor.reducible$async_qp$qp_STAR___38090$fn__38093.invoke(reducible.clj:106)"]}
{:status :failed,
:class clojure.lang.ExceptionInfo,
:error "Error reducing result rows",
:stacktrace
["--> query_processor.context.default$default_reducef$fn__38004.invoke(default.clj:61)"
"query_processor.context.default$default_reducef.invokeStatic(default.clj:58)"
"query_processor.context.default$default_reducef.invoke(default.clj:49)"
"query_processor.context$reducef.invokeStatic(context.clj:69)"
"query_processor.context$reducef.invoke(context.clj:62)"
"query_processor.context.default$default_runf$respond_STAR___38008.invoke(default.clj:70)"
"driver.googleanalytics.execute$execute_reducible_query.invokeStatic(execute.clj:129)"
"driver.googleanalytics.execute$execute_reducible_query.invoke(execute.clj:122)"
"driver.googleanalytics$eval108056$fn__108057.invoke(googleanalytics.clj:157)"
"query_processor.context$executef.invokeStatic(context.clj:59)"
"query_processor.context$executef.invoke(context.clj:48)"
"query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
"query_processor.context.default$default_runf.invoke(default.clj:67)"
"query_processor.context$runf.invokeStatic(context.clj:45)"
"query_processor.context$runf.invoke(context.clj:39)"
"query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
"query_processor.reducible$pivot.invoke(reducible.clj:31)"
"query_processor.middleware.mbql_to_native$mbql__GT_native$fn__43149.invoke(mbql_to_native.clj:26)"
"query_processor.middleware.check_features$check_features$fn__42463.invoke(check_features.clj:42)"
"query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__43314.invoke(optimize_datetime_filters.clj:133)"
"query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47282.invoke(wrap_value_literals.clj:137)"
"query_processor.middleware.annotate$add_column_info$fn__41084.invoke(annotate.clj:577)"
"query_processor.middleware.permissions$check_query_permissions$fn__42338.invoke(permissions.clj:64)"
"query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__43813.invoke(pre_alias_aggregations.clj:40)"
"query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__42536.invoke(cumulative_aggregations.clj:61)"
"query_processor.middleware.resolve_joins$resolve_joins$fn__44345.invoke(resolve_joins.clj:183)"
"query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39271.invoke(add_implicit_joins.clj:245)"
"query_processor.middleware.limit$limit$fn__43135.invoke(limit.clj:38)"
"query_processor.middleware.format_rows$format_rows$fn__43116.invoke(format_rows.clj:81)"
"query_processor.middleware.desugar$desugar$fn__42602.invoke(desugar.clj:22)"
"query_processor.middleware.binning$update_binning_strategy$fn__41628.invoke(binning.clj:229)"
"query_processor.middleware.resolve_fields$resolve_fields$fn__42144.invoke(resolve_fields.clj:24)"
"query_processor.middleware.add_dimension_projections$add_remapping$fn__38807.invoke(add_dimension_projections.clj:272)"
"query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39027.invoke(add_implicit_clauses.clj:147)"
"query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39420.invoke(add_source_metadata.clj:105)"
"query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__44010.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
"query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__41269.invoke(auto_bucket_datetimes.clj:125)"
"query_processor.middleware.resolve_source_table$resolve_source_tables$fn__42191.invoke(resolve_source_table.clj:46)"
"query_processor.middleware.parameters$substitute_parameters$fn__43795.invoke(parameters.clj:97)"
"query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__42243.invoke(resolve_referenced.clj:80)"
"query_processor.middleware.expand_macros$expand_macros$fn__42858.invoke(expand_macros.clj:158)"
"query_processor.middleware.add_timezone_info$add_timezone_info$fn__39451.invoke(add_timezone_info.clj:15)"
"query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47166.invoke(splice_params_in_response.clj:32)"
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__44021$fn__44025.invoke(resolve_database_and_driver.clj:33)"
"driver$do_with_driver.invokeStatic(driver.clj:61)"
"driver$do_with_driver.invoke(driver.clj:57)"
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__44021.invoke(resolve_database_and_driver.clj:27)"
"query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__43064.invoke(fetch_source_query.clj:243)"
"query_processor.middleware.store$initialize_store$fn__47175$fn__47176.invoke(store.clj:11)"
"query_processor.store$do_with_store.invokeStatic(store.clj:46)"
"query_processor.store$do_with_store.invoke(store.clj:40)"
"query_processor.middleware.store$initialize_store$fn__47175.invoke(store.clj:10)"
"query_processor.middleware.cache$maybe_return_cached_results$fn__42120.invoke(cache.clj:209)"
"query_processor.middleware.validate$validate_query$fn__47184.invoke(validate.clj:10)"
"query_processor.middleware.normalize_query$normalize$fn__43162.invoke(normalize_query.clj:22)"
"query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39289.invoke(add_rows_truncated.clj:36)"
"query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47151.invoke(results_metadata.clj:128)"
"query_processor.middleware.constraints$add_default_userland_constraints$fn__42479.invoke(constraints.clj:42)"
"query_processor.middleware.process_userland_query$process_userland_query$fn__43884.invoke(process_userland_query.clj:136)"
"query_processor.middleware.catch_exceptions$catch_exceptions$fn__42422.invoke(catch_exceptions.clj:174)"
"query_processor.reducible$async_qp$qp_STAR___38090$thunk__38091.invoke(reducible.clj:101)"
"query_processor.reducible$async_qp$qp_STAR___38090$fn__38093.invoke(reducible.clj:106)"],
:error_type :qp,
:ex-data {:type :qp}}],
:error_type :qp,
:json_query
{:constraints {:max-results 10000, :max-results-bare-rows 2000},
:type :query,
:middleware nil,
:database 8,
:query {:source-table 579, :breakout [[:datetime-field [:field-id 34697] :month]], :aggregation [[:metric "ga:users"] [:metric "ga:sessions"]]},
:parameters [{:type "date/all-options", :target ["dimension" ["field-id" 34697]], :value "past12months~"}],
:async? true,
:cache-ttl nil},
:native nil,
:status :failed,
:class java.io.IOException,
:stacktrace
["sun.nio.ch.FileDispatcherImpl.writev0(Native Method)"
"sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)"
"sun.nio.ch.IOUtil.write(IOUtil.java:148)"
"sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)"
"org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:263)"
"org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422)"
"org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)"
"org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381)"
"org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:827)"
"org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)"
"org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223)"
"org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:549)"
"org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:829)"
"org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:901)"
"org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:283)"
"org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:267)"
"org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:705)"
"java.util.zip.DeflaterOutputStream.flush(DeflaterOutputStream.java:282)"
"--> async.streaming_response$delay_output_stream$fn__23135.invoke(streaming_response.clj:120)"
"async.streaming_response.proxy$java.io.OutputStream$ff19274a.flush(Unknown Source)"
"query_processor.streaming.json$fn$reify__33619.write_row_BANG_(json.clj:62)"
"query_processor.streaming$streaming_rff$fn__34073$fn__34074.invoke(streaming.clj:35)"
"query_processor.middleware.process_userland_query$add_and_save_execution_info_xform_BANG_$execution_info_rf_STAR___43875.invoke(process_userland_query.clj:95)"
"query_processor.reducible$combine_additional_reducing_fns$fn__38113.invoke(reducible.clj:212)"
"query_processor.middleware.add_rows_truncated$add_rows_truncated_xform$fn__39284.invoke(add_rows_truncated.clj:28)"
"query_processor.middleware.format_rows$format_rows_xform$fn__43109.invoke(format_rows.clj:75)"
"query_processor.middleware.limit$limit_xform$fn__43132.invoke(limit.clj:25)"
"query_processor.context.default$default_reducef$fn__38004.invoke(default.clj:59)"
"query_processor.context.default$default_reducef.invokeStatic(default.clj:58)"
"query_processor.context.default$default_reducef.invoke(default.clj:49)"
"query_processor.context$reducef.invokeStatic(context.clj:69)"
"query_processor.context$reducef.invoke(context.clj:62)"
"query_processor.context.default$default_runf$respond_STAR___38008.invoke(default.clj:70)"
"driver.googleanalytics.execute$execute_reducible_query.invokeStatic(execute.clj:129)"
"driver.googleanalytics.execute$execute_reducible_query.invoke(execute.clj:122)"
"driver.googleanalytics$eval108056$fn__108057.invoke(googleanalytics.clj:157)"
"query_processor.context$executef.invokeStatic(context.clj:59)"
"query_processor.context$executef.invoke(context.clj:48)"
"query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
"query_processor.context.default$default_runf.invoke(default.clj:67)"
"query_processor.context$runf.invokeStatic(context.clj:45)"
"query_processor.context$runf.invoke(context.clj:39)"
"query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
"query_processor.reducible$pivot.invoke(reducible.clj:31)"
"query_processor.middleware.mbql_to_native$mbql__GT_native$fn__43149.invoke(mbql_to_native.clj:26)"
"query_processor.middleware.check_features$check_features$fn__42463.invoke(check_features.clj:42)"
"query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__43314.invoke(optimize_datetime_filters.clj:133)"
"query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47282.invoke(wrap_value_literals.clj:137)"
"query_processor.middleware.annotate$add_column_info$fn__41084.invoke(annotate.clj:577)"
"query_processor.middleware.permissions$check_query_permissions$fn__42338.invoke(permissions.clj:64)"
"query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__43813.invoke(pre_alias_aggregations.clj:40)"
"query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__42536.invoke(cumulative_aggregations.clj:61)"
"query_processor.middleware.resolve_joins$resolve_joins$fn__44345.invoke(resolve_joins.clj:183)"
"query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39271.invoke(add_implicit_joins.clj:245)"
"query_processor.middleware.limit$limit$fn__43135.invoke(limit.clj:38)"
"query_processor.middleware.format_rows$format_rows$fn__43116.invoke(format_rows.clj:81)"
"query_processor.middleware.desugar$desugar$fn__42602.invoke(desugar.clj:22)"
"query_processor.middleware.binning$update_binning_strategy$fn__41628.invoke(binning.clj:229)"
"query_processor.middleware.resolve_fields$resolve_fields$fn__42144.invoke(resolve_fields.clj:24)"
"query_processor.middleware.add_dimension_projections$add_remapping$fn__38807.invoke(add_dimension_projections.clj:272)"
"query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39027.invoke(add_implicit_clauses.clj:147)"
"query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39420.invoke(add_source_metadata.clj:105)"
"query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__44010.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
"query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__41269.invoke(auto_bucket_datetimes.clj:125)"
"query_processor.middleware.resolve_source_table$resolve_source_tables$fn__42191.invoke(resolve_source_table.clj:46)"
"query_processor.middleware.parameters$substitute_parameters$fn__43795.invoke(parameters.clj:97)"
"query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__42243.invoke(resolve_referenced.clj:80)"
"query_processor.middleware.expand_macros$expand_macros$fn__42858.invoke(expand_macros.clj:158)"
"query_processor.middleware.add_timezone_info$add_timezone_info$fn__39451.invoke(add_timezone_info.clj:15)"
"query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47166.invoke(splice_params_in_response.clj:32)"
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__44021$fn__44025.invoke(resolve_database_and_driver.clj:33)"
"driver$do_with_driver.invokeStatic(driver.clj:61)"
"driver$do_with_driver.invoke(driver.clj:57)"
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__44021.invoke(resolve_database_and_driver.clj:27)"
"query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__43064.invoke(fetch_source_query.clj:243)"
"query_processor.middleware.store$initialize_store$fn__47175$fn__47176.invoke(store.clj:11)"
"query_processor.store$do_with_store.invokeStatic(store.clj:46)"
"query_processor.store$do_with_store.invoke(store.clj:40)"
"query_processor.middleware.store$initialize_store$fn__47175.invoke(store.clj:10)"
"query_processor.middleware.cache$maybe_return_cached_results$fn__42120.invoke(cache.clj:209)"
"query_processor.middleware.validate$validate_query$fn__47184.invoke(validate.clj:10)"
"query_processor.middleware.normalize_query$normalize$fn__43162.invoke(normalize_query.clj:22)"
"query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39289.invoke(add_rows_truncated.clj:36)"
"query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47151.invoke(results_metadata.clj:128)"
"query_processor.middleware.constraints$add_default_userland_constraints$fn__42479.invoke(constraints.clj:42)"
"query_processor.middleware.process_userland_query$process_userland_query$fn__43884.invoke(process_userland_query.clj:136)"
"query_processor.middleware.catch_exceptions$catch_exceptions$fn__42422.invoke(catch_exceptions.clj:174)"
"query_processor.reducible$async_qp$qp_STAR___38090$thunk__38091.invoke(reducible.clj:101)"
"query_processor.reducible$async_qp$qp_STAR___38090$fn__38093.invoke(reducible.clj:106)"],
:context :question,
:error "Broken pipe",
:row_count 0,
:running_time 0,
:preprocessed
{:constraints {:max-results 10000, :max-results-bare-rows 2000},
:type :query,
:info
{:executed-by 53,
:context :question,
:card-id 38,
:query-hash [-28, -50, -73, 58, 67, 43, 20, -22, 38, 86, 82, -112, -109, 28, -87, 121, -53, -57, -98, 0, 57, -15, -119, 120, 47, -48, 33, 53, 102, -115, 75, 115]},
:database 8,
:query
{:source-table 579,
:breakout [[:datetime-field [:field-id 34697] :month]],
:aggregation [[:aggregation-options [:metric "ga:users"] {:name "metric"}] [:aggregation-options [:metric "ga:sessions"] {:name "metric_2"}]],
:filter [:between [:datetime-field [:field-id 34697] :month] [:relative-datetime -12 :month] [:relative-datetime 0 :month]],
:order-by [[:asc [:datetime-field [:field-id 34697] :month]]]},
:async? true},
:data {:rows [], :cols []}}

```

**To Reproduce**
1. Add User and Sessions metrics from GA data and Qustion by Date Month.
2. Add the added qustion to the dashboard.
3. Compare two charts.

**Expected behavior**
The same data should be output

**Screenshots**
![image](https://user-images.githubusercontent.com/65528008/84385076-f0b12800-ac29-11ea-8952-a1c8c34a2a0f.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version:  Chrome 83.0.4103.61
- Your operating system: Windows
- Your databases: GA
- Metabase version: Metabase 0.35.4 
- Metabase hosting environment: Ubuntu
- Metabase internal database:  H2 (default), 

**Severity**
I am testing GA integration. It's not a big deal and it doesn't interfere with use.
However, user information cannot be viewed.

**Additional context**

**Comment by flamber** [comment] 2020-06-11 14:03
Hi @haji8-balaan 
The difference between the question and the dashboard card is that the question does not include a date filter.

Looking at your log, I can see the error `Error reducing result rows`, which was fixed in 0.35.3, but still had problems with `null` values, which is fixed on the upcoming 0.36.0

But it's a little difficult to know if that is related. It would be helpful if you reproduced the problem and copied the relevant logs for each step.

I cannot reproduce on `master` (upcoming 0.36.0)

**Comment by haji8-balaan** [comment] 2020-06-12 06:14
It is identified as a problem with date filters.

**Comment by flamber** [comment] 2020-06-12 11:36
Closing, since it seems like it was just a lacking filter that was causing the difference.

**Closed by flamber** 2020-06-12 11:36 UTC
Labels: .Unable to Reproduce, Database/Google Analytics, Type:Bug
