### ISSUE TITLE
Custom formatting not applied to native query columns cast to `time`

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#17357] opened 2021-08-06 21:14 UTC
If you cast a column to `time` in a native query, you can open the format sidebar, but the "show the time" and "time style" options have no effect. I'm assuming this would be the case for time columns in MBQL queries too, but I haven't tested it.

The actual value displayed is also incorrect, but I think I saw a separate issue open for that, though I can't find it now.

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/32746338/128571521-6b95dc92-8a0e-4d47-867b-633add53d177.png">

**Comment by noahmoss** [comment] 2021-08-06 21:22
There's also the more general problem that times (not datetimes) don't seem to be treated as a first-class data type in Metabase. The format setting options assume that a date is always being displayed, and that the time is optional, but you can't disable the date and just display the time.

**Comment by flamber** [comment] 2021-08-07 08:41
Duplicate of #11398 (and #11427)

**Closed by flamber** 2021-08-07 08:41 UTC
Labels: Type:Bug, .Needs Triage
