### ISSUE TITLE
Missing translation for SchedulePicker in Summarize

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#18766] opened 2021-10-29 18:27 UTC
**Describe the bug**
When summarizing by a datetime field, the translations for minute...year are not there

**Logs**
N/A

**To Reproduce**
1) Start metabase, change language to french?
2) summarize by date in the orders table, you'll see that there are no translations

**Expected behavior**
Every word should be translated

**Screenshots**
![image](https://user-images.githubusercontent.com/1711649/139484505-09883c7c-3dcf-4f49-9a6c-9c7b08b7fd0e.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 21.10
- Your databases: H2
- Metabase version: 41.1
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
cosmetic

**Additional context**
N/A

**Comment by flamber** [comment] 2021-10-29 18:39
Duplicate of #15660

**Closed by flamber** 2021-10-29 18:39 UTC
Labels: Type:Bug, Priority:P3, Customization/i18n
