### ISSUE TITLE
Week Definition Configuration

### ISSUE THREAD

**Issue by chucksense** [metabase/metabase#10004] opened 2019-05-17 15:25 UTC
## Goal
It would be really useful to be able to alter the definition of week.

## Background
While there exists, of course, a nice ISO definition of weeks going Monday-Sunday, businesses and other tools often instead choose Sunday-Saturday (for many reasons, not here to debate the merit of doing so).

It would be really useful to be able to modify this definition such that reports and dashboards can align with the business/tool definitions.

As it stands, there is already an issue with Google Analytics Questions not aligning as Google Analytics defines weeks as Sun-Sat as well.

Thanks in advance for consideration and happy to help provide ideas on how to do this, if desired.

**Comment by tlrobinson** [comment] 2019-05-17 17:46
Duplicate of #1779

**Closed by tlrobinson** 2019-05-17 17:46 UTC
