### ISSUE TITLE
Confusing fading out of cards on dashboards with filters

### ISSUE THREAD

**Issue by rthouvenin** [metabase/metabase#5784] opened 2017-08-21 16:08 UTC
When a dashboard has filter(s) and a card on the dashboard is not mapped to all the filters, that card is greyed out. This seems to be a feature, since [it is documented](http://www.metabase.com/docs/latest/users-guide/08-dashboard-filters.html). I find it quite confusing, and I don't understand why there is this feature. I can understand when a card is greyed when some of its parameters are not mapped, or when there is no result for the current filter, but I don't see why the card should be faded when a dashboard filter does not apply to it.

Consider these use cases:

 - A dashboard with two identical questions, used to compare 2 metrics (e.g. compare the revenue of product A and B). I'd set 2 filters: filter A mapped to card 1, and filter B mapped to card 2. After selecting a value for both filters, both cards are greyed and I can't see anything...
 - A dashboard with two similar questions, but one is an aggregated result (e.g. to compare the revenue of a product to the average of all products). I'd set 1 filter mapped to card 1, and nothing mapped to card 2 (it doesn't have parameters). Card 2 is greyed and I can't see the results...

Does this make sense or am I misusing Metabase? If it makes sense, how can this be solved? Making the fading configurable?

Thanks for the great tool!

**Comment by mazameli** [comment] 2017-08-21 18:37
This is a duplicate of https://github.com/metabase/metabase/issues/4220

Definitely something we're exploring changing. We understand it's confusing for lots of users.

**Closed by mazameli** 2017-08-21 18:37 UTC
Labels: Duplicate

**Comment by swatisinghi** [comment] 2017-09-25 09:00
+1, this is a little confusing. Will be great if this fading out can be avoided. Also, I am no longer able to right click on a card and open it in a new tab.
