### ISSUE TITLE
Metabot / slack bot doesn't start

### ISSUE THREAD

**Issue by apinstein** [metabase/metabase#3965] opened 2016-12-15 19:35 UTC
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: na / any
- Your operating system: na / any
- Your databases: na / any
- Metabase version: v0.22.0-snapshot/ 6c76feb
- Metabase hosting environment: Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: n/a

I cannot get the slack bot working.

I have created the bot user, added in the API token, and clicked ENABLE, but the `metabase` bot user is 'not green' and the metabase logs only show:

```
Dec 15 19:30:07 INFO metabase.metabot :: Stopping MetaBot... 🤖
```

I get that log line regardless of the setting of the "Enable" switch when saving changes on the slack integration setup.

I expect that I'd see a `Starting MetaBot` log entry if I save it with the switch enabled...  maybe it's not wired up successfully to the switch and just isn't starting the bot?

**Comment by salsakran** [comment] 2016-12-15 19:37
Does this occur on the stable builds, eg v0.21.1?

**Comment by apinstein** [comment] 2016-12-15 19:39
lemme check... I did just look in the console and it's `PUT`'ing `metabot-enabled: true`... so probably not a goofy UI bug. standby...

**Comment by apinstein** [comment] 2016-12-15 20:31
Ok, we just updated our stack to v0.21.1 and the bug is still there. On boot of the docker, the `metabot` is alive and works, but as soon as you hit `save` on the slack config change, it kills the bot and it doesn't come back up. It reproduces reliably.

**Comment by j005u** [comment] 2016-12-19 12:05
I haven't been able to correlate this with my own actions quite yet, but I'm also seeing metabot go offline for seemingly random amounts of time and not responding. The next moment it'll come back up and reply to the last query I'd sent it.

Last time I looked, didn't see anything interesting in the logs, will keep an eye out though.

**Comment by salsakran** [comment] 2016-12-20 02:07
So I've found one issue w/ the current code in #3987 

It might be the problem you're facing. It keeps Metabase from being enabled until a restart in some situations.

I'll keep poking at the code, as I have a hunch there are some other weird things going on.

**Comment by salsakran** [comment] 2016-12-23 23:22
So I think I found the root cause, and fixed what I found in Master. This will be going in 0.22 which should be released in about 2 weeks.

**Closed by salsakran** 2016-12-23 23:22 UTC
Labels: Bug, Metabot, Priority/P1

**Comment by apinstein** [comment] 2016-12-23 23:31
Cool, thanks! We will let you know if the problem persists after upgrade.

**Comment by timiyay** [comment] 2017-02-13 21:39
We are experiencing similar symptoms, and I've jumped on this issue rather than filing a new one, though they may be different.

We're on Metabase 0.22.2, and we have the Slackbot integration set up, but it constantly drops (@metabase user won't go green 🍏  in the sidebar).

We find that if we go into the Metabase Admin Panel and resave the Slack settings (no changes), the @metabase user will come back online. It also comes back online sometimes when a user is using the web-hosted dashboard.

If noone has bumped the web app or Slack settings in a while, the @metabase user will stay offline indefinitely.

**Comment by Leen15** [comment] 2017-02-27 22:50
Same problem here. Metabase 0.22.2 on a dedicated host with Docker.

**Comment by salsakran** [comment] 2017-02-28 04:06
@Leen15 what do you see in the server logs?

**Comment by Leen15** [comment] 2017-02-28 08:11
@salsakran nothing related to metabot. I see only introspect and query-processor logs.
The bot goes offline for 1-2 minutes, then goes online and so on.

**Comment by tspacek** [comment] 2017-02-28 23:43
We're experiencing the same. Metabase inside Docker with Kubernetes. On 0.22.2.

**Comment by VikramTiwari** [comment] 2017-03-01 17:54
Not 100% sure how Metabot is implemented but I have seen [Botkit](https://github.com/howdyai/botkit) use pulses to keep the channel open and running all the time. Thos are handled behind the scene so until debug flag is activated, one does not see them in logs. If the connection is dropped because of network issues, it is reconnected automatically.

But I assume that since this is (might be) working fine on mac app, then it's more about Docker/VM/K8S cluster deciding to close the port that Metabot is using for communication, but again, as I remember last, it's all built using webhooks, so there shouldn't be any problems.

**Comment by salsakran** [comment] 2017-03-01 18:40
We keep a websocket open for Metabot, and that might be getting closed by K8S. 

This is the sort of thing we're going to have a really hard time reproducing, as my guess is that it's connectivity issue based on what you've shared.

**Comment by KidkArolis** [comment] 2017-03-03 14:45
Same issue, running 0.22.2, slack bot never responds, if I save settings the bot never comes back online:

```
Mar 03 14:42:58 INFO metabase.metabot :: Metabot already running. Killing the previous WebSocket listener first.
Mar 03 14:42:58 INFO metabase.metabot :: Stopping MetaBot... 🤖
Mar 03 14:42:58 INFO metabase.metabot :: Starting MetaBot WebSocket monitor thread...
```

Running metabase on Mesos, in Docker, behind ELB.

**Comment by tspacek** [comment] 2017-03-04 02:00
As another anecdotal data point: we have Hubot running in a docker container in a similar k8s cluster and it stays connected to Slack over a websocket fine.

**Comment by VikramTiwari** [comment] 2018-07-06 03:33
Any update on this? Seems like this is still happening in 0.29.3 version. One common theme I can see is packaging in Docker container might be the reason for connections dropping, but then Hubot example means that it shouldn't be an issue.

cc: @salsakran @camsaul

**Comment by VikramTiwari** [comment] 2018-07-06 17:47
This might be useful.

```
07-06 02:15:29 DEBUG metabase.middleware :: POST /api/dataset 200 (1 s) (12 DB calls). Jetty threads: 8/50 (8 busy, 1 idle, 0 queued)
07-06 02:15:32 DEBUG metabase.middleware :: POST /api/dataset 200 (1 s) (12 DB calls). Jetty threads: 8/50 (3 busy, 6 idle, 0 queued)
07-06 04:00:00 WARN middleware.expand :: You shouldn't specify an :and filter with only one subclause.
Fri Jul 06 05:20:12 GMT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Fri Jul 06 07:00:00 GMT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
07-06 07:00:00 ERROR core.JobRunShell :: Job DEFAULT.metabase.task.send-pulses.job threw an unhandled Exception: 
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 3,600,014 milliseconds ago.  The last packet sent successfully to the server was 16 milliseconds ago.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3559)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3459)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3900)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
        at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:993)
        at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:987)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1016)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:996)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1090)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1047)
        at toucan.db$query.invokeStatic(db.clj:278)
        at toucan.db$query.doInvoke(db.clj:274)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at toucan.db$simple_select.invokeStatic(db.clj:383)
        at toucan.db$simple_select.invoke(db.clj:372)
        at toucan.db$select.invokeStatic(db.clj:640)
        at toucan.db$select.doInvoke(db.clj:634)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at metabase.models.pulse_channel$retrieve_scheduled_channels.invokeStatic(pulse_channel.clj:165)
        at metabase.models.pulse_channel$retrieve_scheduled_channels.invoke(pulse_channel.clj:141)
        at metabase.task.send_pulses$send_pulses_BANG_.invokeStatic(send_pulses.clj:92)
        at metabase.task.send_pulses$send_pulses_BANG_.invoke(send_pulses.clj:82)
        at metabase.task.send_pulses.SendPulses.execute(send_pulses.clj:59)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3008)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3469)
        ... 29 more
07-06 07:00:00 ERROR core.ErrorLogger :: Job (DEFAULT.metabase.task.send-pulses.job threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 3,600,014 milliseconds ago.  The last packet sent successfully to the server was 16 milliseconds ago.]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:224)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 3,600,014 milliseconds ago.  The last packet sent successfully to the server was 16 milliseconds ago.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3559)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3459)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3900)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
        at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:993)
        at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:987)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1016)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:996)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1090)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1047)
        at toucan.db$query.invokeStatic(db.clj:278)
        at toucan.db$query.doInvoke(db.clj:274)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at toucan.db$simple_select.invokeStatic(db.clj:383)
        at toucan.db$simple_select.invoke(db.clj:372)
        at toucan.db$select.invokeStatic(db.clj:640)
        at toucan.db$select.doInvoke(db.clj:634)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at metabase.models.pulse_channel$retrieve_scheduled_channels.invokeStatic(pulse_channel.clj:165)
        at metabase.models.pulse_channel$retrieve_scheduled_channels.invoke(pulse_channel.clj:141)
        at metabase.task.send_pulses$send_pulses_BANG_.invokeStatic(send_pulses.clj:92)
        at metabase.task.send_pulses$send_pulses_BANG_.invoke(send_pulses.clj:82)
        at metabase.task.send_pulses.SendPulses.execute(send_pulses.clj:59)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        ... 1 more
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3008)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3469)
        ... 29 more
```

Metabot is currently down

**Comment by VikramTiwari** [comment] 2018-07-06 17:51
Related issue: https://github.com/metabase/metabase/issues/5380
