### ISSUE TITLE
Upgrade from v0.30.1 to v0.31.2 breaks embedded dashboard

### ISSUE THREAD

**Issue by codyjroberts** [metabase/metabase#9217] opened 2019-01-04 18:25 UTC
- Your browser and the version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- Your operating system: COS
- Your databases: Postgres 9.6 on CloudSQL
- Metabase version: v0.31.2
- Metabase hosting environment: Helm/Docker/GKE 1.11.2-gke.25
- Metabase internal database: Postgres 9.6 on CloudSQL

* helm upgrade <RELEASE NAME> stable/metabase --reuse-values --set image.tag=v0.31.2

A single embedded dashboard fails with error:

```Input to field-clause->id-or-literal does not match schema: \n\n\t \u001b[0;33m  [(named (named (not (some-matching-condition? nil)) \"Must be a valid instance of one of these clauses: :field-id, :field-literal, :fk->, :datetime-field, :expression, :binning-strategy\") clause)] \u001b[0m \n\n``` displayed in the iframe (similar to commenter in https://github.com/metabase/metabase/issues/8917). The dashboard within Metabase works fine as well as the questions themselves. All of our other 6 embedded dashboards are working fine. I'm posting this as a new issue as thats the only comment in that thread that seems to have a somewhat similar error message although they don't mention embedding.

Thanks!

**Comment by camsaul** [comment] 2019-01-04 23:16
Duplicate of #8917

**Closed by camsaul** 2019-01-04 23:16 UTC
