### ISSUE TITLE
Use result of a dashboard tile in another tile

### ISSUE THREAD

**Issue by reza-keshavarz** [metabase/metabase#13535] opened 2020-10-20 12:13 UTC
This scenario has occurred for us a few times in the past few weeks:

We need to make a dashboard and its queries are on different databases. Sometimes, we need to combine the results of two tiles (queries) from different databases.
 For instance:
 **X** is a single number and it's the result of a query on the database **A**, and it's shown in a dashboard tile
 **Y** is a single number and it's the result of a query on database **B**, and it's shown in a dashboard tile

What we want to see is **X/Y**. It's not possible at the moment to query two databases in one metabase question. However,  we could  perhaps just have a third tile, which just receives two other tiles as input and does some arithmetic calculations (starting with the very basic, such as multiplication) and shows the result.

This features use cases will not be limited just to the specific scenario I described above. It could be also be used to avoid redundant processing.

**Comment by flamber** [comment] 2020-10-20 12:17
Sounds like a duplicate of #10273

**Closed by flamber** 2020-10-20 12:17 UTC
Labels: .Needs Triage, Type:New Feature
