### ISSUE TITLE
Creating/editing database connection with SSH tunnel fails silently, when database port is not filled out

### ISSUE THREAD

**Issue by scronide** [metabase/metabase#20756] opened 2022-02-26 03:07 UTC
**Describe the bug**
I'm attempting to edit a MySQL connection to use an SSH tunnel through a bastion server to Google Cloud SQL. The tunnel uses SSH key authentication. The changes fail silently, returning me to the edit screen with the tunnel options reset, while spitting out a 400 error to the troubleshooting logs.

The same SSH tunnel works ok for other, self-hosted databases connected to Metabase and also from my desktop machine. I manually cloned the details from another connection in the metabase_database table, adjusted them to suit, and the actual tunnelled connection appears to work fine.

**Logs**
I've blanked out the server and key details.
```
[62f0d42b-8177-4d38-8dc3-a4d7a5ba8e72] 2022-02-25T18:12:57-08:00 WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier ParameterizedMessage[messagePattern=Server at {} presented unverified {} key: {}, stringArgs=[XXX, EC, XXX], throwable=null]
[62f0d42b-8177-4d38-8dc3-a4d7a5ba8e72] 2022-02-25T18:12:57-08:00 ERROR metabase.driver.util Database connection error
java.lang.NullPointerException
	at clojure.lang.RT.intCast(RT.java:1221)
	at metabase.util.ssh$start_ssh_tunnel_BANG_.invokeStatic(ssh.clj:63)
	at metabase.util.ssh$start_ssh_tunnel_BANG_.invoke(ssh.clj:49)
	at metabase.util.ssh$include_ssh_tunnel_BANG_.invokeStatic(ssh.clj:89)
	at metabase.util.ssh$include_ssh_tunnel_BANG_.invoke(ssh.clj:83)
	at metabase.util.ssh$fn__33886.invokeStatic(ssh.clj:115)
	at metabase.util.ssh$fn__33886.invoke(ssh.clj:105)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.sql_jdbc.connection$details__GT_connection_spec_for_testing_connection.invokeStatic(connection.clj:239)
	at metabase.driver.sql_jdbc.connection$details__GT_connection_spec_for_testing_connection.invoke(connection.clj:235)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:253)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:249)
	at metabase.driver.sql_jdbc$fn__81966.invokeStatic(sql_jdbc.clj:35)
	at metabase.driver.sql_jdbc$fn__81966.invoke(sql_jdbc.clj:33)
	at metabase.driver.mysql$fn__79845.invokeStatic(mysql.clj:71)
	at metabase.driver.mysql$fn__79845.invoke(mysql.clj:67)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__19263.invoke(util.clj:48)
	at metabase.util$do_with_timeout$fn__6209.invoke(util.clj:352)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[62f0d42b-8177-4d38-8dc3-a4d7a5ba8e72] 2022-02-25T18:12:57-08:00 ERROR metabase.api.database Cannot connect to Database
java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Unknown Source)
	at java.base/java.util.regex.Matcher.reset(Unknown Source)
	at java.base/java.util.regex.Matcher.<init>(Unknown Source)
	at java.base/java.util.regex.Pattern.matcher(Unknown Source)
	at clojure.core$re_matcher.invokeStatic(core.clj:4845)
	at clojure.core$re_matches.invokeStatic(core.clj:4875)
	at clojure.core$re_matches.invoke(core.clj:4875)
	at metabase.driver.mysql$fn__79855.invokeStatic(mysql.clj:117)
	at metabase.driver.mysql$fn__79855.invoke(mysql.clj:115)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:53)
	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:36)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at metabase.api.database$test_database_connection.invokeStatic(database.clj:431)
	at metabase.api.database$test_database_connection.doInvoke(database.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at metabase.api.database$fn__73371.invokeStatic(database.clj:587)
	at metabase.api.database$fn__73371.invoke(database.clj:566)
	at compojure.core$wrap_response$fn__32271.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__32255.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__32260.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:151)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:153)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__65343.invoke(auth.clj:14)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at compojure.core$make_context$handler__32311.invoke(core.clj:289)
	at compojure.core$make_context$fn__32315.invoke(core.clj:299)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at metabase.api.routes$fn__76468$fn__76471.invoke(routes.clj:56)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__76613$fn__76614.doInvoke(routes.clj:57)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at compojure.core$make_context$handler__32311.invoke(core.clj:289)
	at compojure.core$make_context$fn__32315.invoke(core.clj:299)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:153)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:153)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:153)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at metabase.server.routes$fn__76601$fn__76603.invoke(routes.clj:41)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__73596.invoke(exceptions.clj:98)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__73593.invoke(exceptions.clj:86)
	at metabase.server.middleware.log$log_api_call$fn__77079$fn__77080$fn__77081.invoke(log.clj:209)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
	at metabase.server.middleware.log$log_api_call$fn__77079$fn__77080.invoke(log.clj:201)
	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
	at toucan.db$_do_with_call_counting.invoke(db.clj:209)
	at metabase.server.middleware.log$log_api_call$fn__77079.invoke(log.clj:200)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__80432.invoke(browser_cookie.clj:38)
	at metabase.server.middleware.security$add_security_headers$fn__55203.invoke(security.clj:148)
	at metabase.server.middleware.json$wrap_json_body$fn__79587.invoke(json.clj:62)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__79605.invoke(json.clj:98)
	at metabase.server.middleware.offset_paging$handle_paging$fn__55227.invoke(offset_paging.clj:42)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__80699.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__80715.invoke(params.clj:69)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__34377.invoke(misc.clj:59)
	at metabase.server.middleware.session$bind_current_user$fn__45720$fn__45721.invoke(session.clj:262)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:243)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:235)
	at metabase.server.middleware.session$bind_current_user$fn__45720.invoke(session.clj:261)
	at metabase.server.middleware.session$wrap_current_user_info$fn__45707.invoke(session.clj:221)
	at metabase.server.middleware.session$wrap_session_id$fn__45693.invoke(session.clj:167)
	at metabase.server.middleware.auth$wrap_api_key$fn__65351.invoke(auth.clj:27)
	at ring.middleware.cookies$wrap_cookies$fn__80619.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__34360.invoke(misc.clj:27)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__34385.invoke(misc.clj:76)
	at ring.middleware.gzip$wrap_gzip$fn__80661.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__34388.invoke(misc.clj:93)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__80448.invoke(ssl.clj:48)
	at metabase.server$async_proxy_handler$fn__76852.invoke(server.clj:73)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
[62f0d42b-8177-4d38-8dc3-a4d7a5ba8e72] 2022-02-25T18:12:57-08:00 DEBUG metabase.server.middleware.log PUT /api/database/12 400 437.5 ms (1 DB calls) 
{:valid false, :dbname nil, :message nil}
```

**To Reproduce**
n/a

**Expected behavior**
Either:

- For the SSH tunnel to successfully connect, or;
- For a connection error to be reported in-page, retaining the details that were submitted.

**Screenshots**
n/a

**Information about your Metabase Installation:**
Running the Docker image on a Kubernetes cluster.
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "5.4.144+",
    "user.language": "en",
    "user.timezone": "US/Pacific"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "mysql",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.24"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-17",
      "tag": "v0.42.1",
      "branch": "release-x.42.x",
      "hash": "629f4de"
    },
    "settings": {
      "report-timezone": "America/Vancouver"
    }
  }
}
```

**Severity**
Blocking usage, prior to direct database manipulation. Could not connect to significant service database.

**Additional context**
n/a

**Comment by flamber** [comment] 2022-03-03 17:02
Hi @scronide 
No matter how I setup a MySQL connection through SSH, then it works as expected, when I setup a new connection or edit an existing connection.
What exactly are you trying to edit on the connection? Perhaps it requires something specific for it to fail.
Also, it should not send you back to the overview or reload the page if there was a 400-error, then that message should be displayed with "Save failed".

**Comment by scronide** [comment] 2022-03-04 03:05
> What exactly are you trying to edit on the connection?

I was trying to enable the SSH tunnel and set:

- SSH tunnel host
- SSH tunnel username
- SSH private key
 
The key has no passphrase.

Originally I had set up the direct connection first and was just trying to add the tunnel, but I get the same result if I try to add it all at once: it refreshes the page and returns me to the previous state without any error messages. If I'm starting from scratch, it's a blank form.

In the JS console, I see the following errors:
![Screen Shot 2022-03-03 at 6 55 06 PM](https://user-images.githubusercontent.com/231853/156690617-99ed835a-dbc7-47a1-b3f1-adb19ba756df.png)

...and the response from the `/api/database` POST that 400s is just:
```
{"valid":false,"dbname":null,"message":null}
```

I can't attach the outgoing payload for that request unredacted but there's nothing unusual about it.
```
{
   "engine":"mysql",
   "name":"XXX",
   "details":{
      "host":"XXX",
      "port":null,
      "dbname":"XXX_XXX",
      "user":"XXX_XXX",
      "password":"XXX-XXX-XXX",
      "ssl":false,
      "tunnel-enabled":true,
      "tunnel-host":"XXX.XXX.com",
      "tunnel-port":22,
      "tunnel-user":"XXX",
      "tunnel-auth-option":"ssh-key",
      "tunnel-private-key":"-----BEGIN RSA PRIVATE KEY-----\nXXX\n-----END RSA PRIVATE KEY-----",
      "tunnel-private-key-passphrase":null,
      "advanced-options":false
   },
   "is_full_sync":true
}
```

**Comment by scronide** [comment] 2022-03-04 03:07
Actually, that outgoing payload highlighted the problem: the port is missing. The port number isn't required to save a new connection but it also doesn't fall back to the default if you don't provide it. That causes the request to fail silently.

Once I explicitly added the port it was fine.

**Comment by flamber** [comment] 2022-03-04 11:04
@scronide That did the trick, thank you.

**Comment by paoliniluis** [comment] 2022-03-04 13:44
For more information, check ticket 7361 in our internal ticketing system

**Comment by paoliniluis** [comment] 2023-05-23 18:31
Seems it happened again

**Comment by paoliniluis** [comment] 2023-05-30 17:23
I just checked and it now fails when not filling the DB port, not even with SSH

**Comment by john-metabase** [comment] 2023-06-27 13:04
@paoliniluis I'm having trouble reproducing this one. I'm leaving the `:port` field (the DB port, not the tunnel port) blank, and using an SSH tunnel, but it seems to work fine.

**Comment by john-metabase** [comment] 2023-07-07 02:09
Based on stack traces from @paoliniluis it looks like we may have a different issue around the SSH port default value, not the database port.

**Comment by paoliniluis** [comment] 2023-07-07 16:52
Closing this one in favor of https://github.com/metabase/metabase/issues/32234

**Closed by paoliniluis** 2023-07-07 16:52 UTC
Labels: Type:Bug, Priority:P1, .Backend, First Experience/Setup, .Regression, Administration/Databases, .Team/QueryProcessor :hammer_and_wrench:
