### ISSUE TITLE
Google Auth flow doesn't work on Mobile Safari

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4661] opened 2017-03-31 18:13 UTC
A common flow I have is to look at daily pulses in Slack on my commute, then see something interesting on one of the cards and hence click on it to find out more detail. Because iOS is iOS, this launches mobile Safari (instead of my preferred Chrome), on which I'm not logged in to Metabase. Trying to log in to MB using Google Auth results in an endless loading loop; hitting refresh puts me back at `Choose an account` google auth screen (my phone has both a personal and a work google account). The auth flow works fine on mobile Chrome, but it's annoying to basically not be able to click through on pulses and have to switch over manually to Chrome.

I'm curious if anyone else can re-pro.

**Comment by snarfed** [comment] 2018-06-19 21:16
fwiw i see this on chrome on android too.

**Comment by dannyeuu** [comment] 2018-08-24 14:41
@mazameli I found today that I have this trouble too, all our external workers that use their phones for daily jobs cannot sign-up for Metabase, only sign-in, the redirect returns only to the login page.

**Comment by limaisabela** [comment] 2018-08-24 14:58
This is the error that occurs when a new user try to sign up over google.

![screenshot from 2018-08-24 11-57-01](https://user-images.githubusercontent.com/40770582/44591711-d841f600-a794-11e8-807d-ab51d885f068.png)

**Comment by salsakran** [comment] 2019-10-11 23:08
Tried to reproduce this and failed. Been using it regularly on Chrome + Safari on iOS and haven't seen it.

Since it's been over a year since the last report and I can't reproduce this, I'll close this. If anyone encounters this again, please chime in and we'll reopen.

**Closed by salsakran** 2019-10-11 23:08 UTC
Labels: Administration/Auth, Client:Mobile Web, Type:UX
