### ISSUE TITLE
Bug on Questions: Boolean datatypes aren't correctly supported on question filters

### ISSUE THREAD

**Issue by Nish-George** [metabase/metabase#17653] opened 2021-08-27 22:53 UTC
**Describe the bug**

Context: I open my employee-data question which is pre-filtered on a variable {{Offboarded}} = false ("Offboarded" maps to a field in my table named is_offboarded, which is a boolean data type). 
Expected Result: Question should correctly filter for non-offboarded employees.
Actual Result: I see: 
ERROR: operator does not exist: boolean = character varying Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts. Position: 976

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome Version 92.0.4515.159
- Your operating system: Windows 10 Build 19043.1165
- Your databases: Postgres
- Metabase version: 0.40.3
- Metabase hosting environment: Heroku
- Metabase internal database: Postgres

**Severity**
This is blocking some users and erodes trust in the Analytics team.

**Additional context**

![image](https://user-images.githubusercontent.com/82229111/131195922-834e4c9d-2e04-43ac-8004-af4d3faa5c3c.png)

**Comment by flamber** [comment] 2021-08-28 12:41
Duplicate of #15498

**Closed by flamber** 2021-08-28 12:41 UTC
Labels: Type:Bug, .Needs Triage
