### ISSUE TITLE
Connection to MongoDB cluster

### ISSUE THREAD

**Issue by davidmir** [metabase/metabase#4157] opened 2017-01-13 15:43 UTC
Hi,

Is it possible for the Metabase to connect to a MongoDB master-slave cluster? 

Thanks

**Comment by camsaul** [comment] 2017-01-16 21:26
@davidmir check out the discussion on #1374. You can just manually point Metabase to a slave instance right now, and we plan to add better support for connecting to replica sets and master/slave setups in the future

Closing as duplicate of #1374

**Closed by camsaul** 2017-01-16 21:26 UTC
Labels: Database/Mongo, Question
