### ISSUE TITLE
A user/person is losing Group access when authenticating via LDAP.

### ISSUE THREAD

**Issue by mdeimel** [metabase/metabase#13352] opened 2020-10-02 18:19 UTC
**Describe the bug**
Two different users have had problems that they lose their group access when authenticating. All of our users authenticate with LDAP. This doesn't happen

**Logs**
**_Set group permission on user_**
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T11:41:23-05:00 DEBUG metabase.middleware.log GET /api/permissions/group 200 3.2 ms (2 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (3 idle, 0 queued) (126 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T11:41:23-05:00 DEBUG metabase.middleware.log GET /api/user 200 7.3 ms (3 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (3 idle, 0 queued) (126 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T11:41:23-05:00 DEBUG metabase.middleware.log GET /api/permissions/membership 200 2.1 ms (1 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (126 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T11:41:27-05:00 DEBUG metabase.middleware.log POST /api/permissions/membership 200 6.7 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (126 total active threads) Queries in flight: 0 (0 queued)

**_User authenticating_**
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:16-05:00 DEBUG metabase.middleware.log GET /api/session/properties 200 5.4 ms (2 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (3 idle, 0 queued) (124 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:16-05:00 DEBUG metabase.middleware.log GET /api/user/current 200 12.1 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (3 idle, 0 queued) (124 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:16-05:00 DEBUG metabase.middleware.log GET /api/database 200 13.0 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (124 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:16-05:00 DEBUG metabase.middleware.log GET /api/user 200 6.7 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (124 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:16-05:00 DEBUG metabase.middleware.log GET /api/permissions/group 200 4.2 ms (2 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (124 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:16-05:00 DEBUG metabase.middleware.log GET /api/permissions/membership 200 2.3 ms (1 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (124 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:19-05:00 DEBUG metabase.middleware.log GET /api/session/properties 200 1.1 ms (0 DB calls) App DB connections: 0/15 Jetty threads: 6/50 (2 idle, 0 queued) (124 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:19-05:00 DEBUG metabase.middleware.log GET /api/user/current 401 352.5 µs (0 DB calls)
"Unauthenticated"
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:42-05:00 DEBUG metabase.middleware.log POST /api/session 200 77.5 ms (6 DB calls) App DB connections: 1/15 Jetty threads: 3/50 (4 idle, 0 queued) (124 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:42-05:00 DEBUG metabase.middleware.log GET /api/user/current 200 9.6 ms (3 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (3 idle, 0 queued) (124 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:42-05:00 DEBUG metabase.middleware.log GET /api/session/properties 200 6.7 ms (2 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (3 idle, 0 queued) (124 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:42-05:00 DEBUG metabase.middleware.log GET /api/database 200 11.3 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (124 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:42-05:00 DEBUG metabase.middleware.log GET /api/collection/root/items 200 13.3 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (124 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:42-05:00 DEBUG metabase.middleware.log GET /api/collection/root 200 3.9 ms (2 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (124 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:42-05:00 DEBUG metabase.middleware.log GET /api/database 200 10.4 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (124 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:44-05:00 DEBUG metabase.middleware.log GET /api/collection/root 200 4.0 ms (2 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (124 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:52-05:00 DEBUG metabase.middleware.log GET /api/collection/20 200 6.1 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (124 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:53-05:00 DEBUG metabase.middleware.log GET /api/collection/20/items 200 10.1 ms (7 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (124 total active threads) Queries in flight: 0 (0 queued)
[af675d66-1987-421a-8a44-f4efdd8d3111] 2020-10-02T13:11:56-05:00 DEBUG metabase.middleware.log GET /api/database 200 7.7 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (125 total active threads) Queries in flight: 0 (0 queued)

**To Reproduce**
1. In the Admin > People table, set the user's Group to the specified group.
2. Have the user from step #1 login
3. Notice they do not have access, and their group in the People table has been reverted to "Default"
This happened every time, no matter what method I used to set the user's group. Once when I deactivated the user and reactivated them, it worked for the remainder of the day, and the second day it started happening again (and deactivating did not resolve the issue).

**Expected behavior**
I would not expect authentication to set the user's group to "Default".

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.2+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.2+9",
    "os.name": "Linux",
    "os.version": "4.15.0-70-generic",
    "user.language": "en",
    "user.timezone": "America/Chicago"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres",
      "sqlserver",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.16"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-07-31",
      "tag": "v0.36.2",
      "branch": "release-0.36.x",
      "hash": "13f0225"
    },
    "settings": {
      "report-timezone": "US/Central"
    }
  }
}
```

**Severity**
This has happened for 2 of our users. So for those users, it is a blocking issue, but it has not happened for anyone else - so clearly it's not blocking for the majority of our users.

**Additional context**
I looked through any existing issues and bug reports, but could not find anything related to this, although I admit I might not be searching for the terms that others have used.

Thanks for your help. Metabase is a great product, and I'm really glad to be able to use it!

**Comment by flamber** [comment] 2020-10-02 18:22
Duplicate of #7571

**Closed by flamber** 2020-10-02 18:22 UTC
Labels: .Needs Triage, Type:Bug
