### ISSUE TITLE
Metabot show question id error 'long sun.font.FreetypeFontScaler.getLayoutTableCacheNative(long)'

### ISSUE THREAD

**Issue by anshulk** [metabase/metabase#12144] opened 2020-03-17 09:25 UTC
**Describe the bug**
`metabot show 10` gives error 'long sun.font.FreetypeFontScaler.getLayoutTableCacheNative(long)'

**Logs**
```shell
03-17 09:15:16 ERROR metabot.slack :: Error in Metabot command
java.lang.UnsatisfiedLinkError: 'long sun.font.FreetypeFontScaler.getLayoutTableCacheNative(long)'
        at java.desktop/sun.font.FreetypeFontScaler.getLayoutTableCacheNative(Native Method)
        at java.desktop/sun.font.FreetypeFontScaler.getLayoutTableCache(FreetypeFontScaler.java:167)
        at java.desktop/sun.font.TrueTypeFont.getLayoutTableCache(TrueTypeFont.java:902)
        at java.desktop/sun.font.SunLayoutEngine.layout(SunLayoutEngine.java:169)
        at java.desktop/sun.font.GlyphLayout$EngineRecord.layout(GlyphLayout.java:687)
        at java.desktop/sun.font.GlyphLayout.layout(GlyphLayout.java:468)
        at java.desktop/sun.font.ExtendedTextSourceLabel.createGV(ExtendedTextSourceLabel.java:329)
        at java.desktop/sun.font.ExtendedTextSourceLabel.getGV(ExtendedTextSourceLabel.java:315)
        at java.desktop/sun.font.ExtendedTextSourceLabel.createLogicalBounds(ExtendedTextSourceLabel.java:225)
        at java.desktop/sun.font.ExtendedTextSourceLabel.getAdvance(ExtendedTextSourceLabel.java:134)
        at java.desktop/java.awt.font.TextLine.init(TextLine.java:281)
        at java.desktop/java.awt.font.TextLine.<init>(TextLine.java:129)
        at java.desktop/java.awt.font.TextLine.fastCreateTextLine(TextLine.java:978)
        at java.desktop/java.awt.font.TextLayout.fastInit(TextLayout.java:611)
        at java.desktop/java.awt.font.TextLayout.<init>(TextLayout.java:392)
        at org.fit.cssbox.layout.VisualContext.updateForGraphics(VisualContext.java:356)
        at org.fit.cssbox.layout.ElementBox.loadBasicStyle(ElementBox.java:1293)
        at org.fit.cssbox.layout.ElementBox.setStyle(ElementBox.java:315)
        at org.fit.cssbox.layout.InlineBox.setStyle(InlineBox.java:92)
        at org.fit.cssbox.layout.BoxFactory.createElementInstance(BoxFactory.java:825)
        at org.fit.cssbox.layout.BoxFactory.createBox(BoxFactory.java:744)
        at org.fit.cssbox.layout.BoxFactory.createElementBox(BoxFactory.java:447)
        at org.fit.cssbox.layout.BoxFactory.createSubtree(BoxFactory.java:263)
        at org.fit.cssbox.layout.BoxFactory.createViewportTree(BoxFactory.java:169)
        at org.fit.cssbox.layout.BrowserCanvas.createLayout(BrowserCanvas.java:169)
        at org.fit.cssbox.layout.BrowserCanvas.createLayout(BrowserCanvas.java:142)
        at metabase.pulse.render.png$content_canvas.invokeStatic(png.clj:58)
        at metabase.pulse.render.png$content_canvas.invoke(png.clj:46)
        at metabase.pulse.render.png$render_to_png_BANG_.invokeStatic(png.clj:65)
        at metabase.pulse.render.png$render_to_png_BANG_.invoke(png.clj:60)
        at metabase.pulse.render.png$fn__29309$render_html_to_png__29314$fn__29318.invoke(png.clj:78)
        at metabase.pulse.render.png$fn__29309$render_html_to_png__29314.invoke(png.clj:68)
        at metabase.pulse.render$render_pulse_card_to_png.invokeStatic(render.clj:157)
        at metabase.pulse.render$render_pulse_card_to_png.invoke(render.clj:154)
        at metabase.pulse$create_slack_attachment_data$iter__60843__60847$fn__60848$fn__60849$fn__60852.invoke(pulse.clj:73)
        at metabase.pulse$create_and_upload_slack_attachments_BANG_$iter__60866__60870$fn__60871$fn__60872.invoke(pulse.clj:84)
        at metabase.pulse$create_and_upload_slack_attachments_BANG_$iter__60866__60870$fn__60871.invoke(pulse.clj:83)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5402.invokeStatic(core.clj:137)
        at clojure.core$dorun.invokeStatic(core.clj:3133)
        at clojure.core$doall.invokeStatic(core.clj:3148)
        at clojure.core$doall.invoke(core.clj:3148)
        at metabase.pulse$create_and_upload_slack_attachments_BANG_.invokeStatic(pulse.clj:82)
        at metabase.pulse$create_and_upload_slack_attachments_BANG_.invoke(pulse.clj:79)
        at metabase.metabot.command$fn__61084$fn__61088.invoke(command.clj:176)
        at metabase.metabot.slack$do_async$fn__61024$fn__61025.invoke(slack.clj:42)
        at metabase.metabot.slack$do_async$fn__61024.invoke(slack.clj:41)
        at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10-post-Ubuntu-0ubuntu1.118.04",
    "java.vendor": "Private Build",
    "java.vendor.url": "Unknown",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10-post-Ubuntu-0ubuntu1.118.04",
    "os.name": "Linux",
    "os.version": "4.15.0-46-generic",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "date": "2019-11-19",
      "tag": "v0.33.6",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

**Comment by flamber** [comment] 2020-03-17 10:10
Hi @anshulk 
Please test with latest release 0.34.3
I would recommend that you try using the Docker version, since the error seems to be specific to your Java version.
And can you include information on how to reproduce this? Like which question type, the result data.

**Comment by flamber** [comment] 2020-06-06 12:33
Closing, since no reply on how to reproduce or any additional information.

**Closed by flamber** 2020-06-06 12:33 UTC
Labels: .Need More Info, Type:Bug
