### ISSUE TITLE
Add Hours and Minutes to dashboard time filter

### ISSUE THREAD

**Issue by edmarriner** [metabase/metabase#6660] opened 2018-01-08 10:35 UTC
On the question page, the date filters allow you to select "minutes" or "hours". The smallest time option on the dashboard filter however is "days".

It would be helpful to have the hours and minutes options added to the dashboard date filters. 

![screenshot from 2018-01-08 10-33-57](https://user-images.githubusercontent.com/655769/34667112-7583dae4-f45f-11e7-837c-4714f0bf6976.png)

![screenshot from 2018-01-08 10-33-35](https://user-images.githubusercontent.com/655769/34667114-77e1fbb8-f45f-11e7-9634-55b73774ba51.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment] 2018-07-22 14:36
At this stage in the game, this feels like a bug to me rather than a proposal: you can add the "all options" date filter to a dashboard, which ostensibly is exactly the same as the query builder date filter, but the former is still missing minutes and hours:

<img width="488" alt="screen shot 2018-07-22 at 10 34 01 am" src="https://user-images.githubusercontent.com/2223916/43046719-09740a4c-8d9b-11e8-95fc-322f619fc33d.png">

Query builder for comparison:

<img width="667" alt="screen shot 2018-07-22 at 10 34 30 am" src="https://user-images.githubusercontent.com/2223916/43046721-0e7121a6-8d9b-11e8-96ec-89e49a54630c.png">

**Comment by jornh** [comment] 2018-09-13 05:42
Similar issue: https://github.com/metabase/metabase/issues/3785 (this might even be called a dupe?)

**Comment by tlrobinson** [comment] 2018-09-14 17:51
Technically it's a limitation, not a bug, since we've never supported time in any of the dashboard filters. I don't think it will be particularly hard, but it will require a little bit of both frontend and backend work. Backend needs to support `(past|next)N(hours|minutes)` and the frontend just needs a few changes to show those options.

**Comment by jkindness** [comment] 2020-02-06 18:40
Any update on this one?

**Comment by derekm1215** [comment] 2020-02-09 19:00
Also asking for an update. This is a HUGE limitation for us currently and doesn't make a lot of sense. Has anyone come up with a workaround?

**Comment by trannamtrung1st** [comment] 2020-03-29 04:27
Anything new from here? I agree with @derekm1215

**Comment by wumfi** [comment] 2020-04-03 15:19
Adding my wish to the pile.  We look at net flow data, and need to go down to minute/second granularity.  If seconds are a no-go, then minutes would be ok.  Thank you!

**Comment by bennweze** [comment] 2020-05-05 12:53
is there any update here, this is an important function to have

**Comment by cpeterson-ata** [comment] 2020-06-30 19:02
+1 seriously need this functionality. Is it in the current plans?

**Comment by zxh326** [comment] 2020-09-01 12:00
any update for here?

**Comment by maxschloegl** [comment] 2021-01-29 12:39
When do you plan to do this? It is not possible to filter by time in a dashboard.
BR

**Comment by paoliniluis** [comment] 2021-01-29 12:47
Hi @maxschloegl, we don't provide ETA's for features, but as you can see in the thread the feature is being worked on so it will arrive soon. What you can do is build your own container or binary once the previous PR has been merged to the master branch. Thanks

**Comment by flamber** [comment] 2021-02-12 22:34
Fixed by #14794

**Closed by flamber** 2021-02-12 22:34 UTC
Labels: .Backend, .Frontend, Difficulty:Easy, Priority:P2, Reporting/Dashboards, Type:Completeness

**Comment by aaron-kahn** [comment] 2021-03-10 14:09
@flamber I am running the latest version of Metabase 0.38.1 and I am only seeing the hours and minutes option available for relative time filters. Is this intended? I was really hoping that the capability would be extended to the between filter. Should I open a new issue?

**Comment by aaron-kahn** [comment] 2021-03-10 14:32
@flamber Ah yes, thank you, missed that one.

**Comment by maxschloegl** [comment] 2021-03-10 16:57
Hi @flamber @aaron-kahn!
Actually this does not support the case of filtering just for a timestamp without date. For example you want to filter between a time range over several days. 
Let’s say you want to see all entries which were created between 10:00AM - 11:00AM but in different days. 
BR Max

**Comment by flamber** [comment] 2021-03-10 18:01
@maxgashkov Okay, then please open a new feature request, since that wasn't what this issue was requesting.

**Comment by maxgashkov** [comment] 2021-03-11 00:46
@flamber I believe you should be mentioning @maxschloegl.

**Comment by flamber** [comment] 2021-03-11 17:40
@MchlUh This issue was for dashboards. Sounds like you're looking for #7418. But we should unify all the selectors #4874
