### ISSUE TITLE
SQL Field Filter with date not working if day larger then 12 (only SQL-Server?)

### ISSUE THREAD

**Issue by devaxel** [metabase/metabase#4320] opened 2017-02-07 09:28 UTC
Hi metabase fans and developers,

actual I recognized an issue with a field filter for a date range.
I'm using a SQL Server 2014 Table. In metabase I wrote this SQL query:

```sql
SELECT count(*) AS "Anzahl Clippings", "PRODUKT" AS "Produkt", sum("Auflage") AS "Auflage"
FROM "MRANALYSTDATA_FOR_MR" 
where 1=1 [[AND {{ErschDatum}}]]
GROUP BY "PRODUKT" 
ORDER BY "PRODUKT" ASC
```

The variable "ErschDatum" is a Field Filter for the column "Erscheindatum", which is from datatype smalldatetime in the SQL-Server Table.
When I use the filter at the dashboard for a date range like " 1 January to 11 March" everything works fine. But as soon as I choose a date range like "1 January to 13 March" the widget says "There was a problem displaying the chart".

Conclusion: **When I choose a date range where the start or the end-date contains a day larger then 12, the error occurs**.
This problem occurs only in SQL queries.

**My Environment:**
Browser Chrome, Firefox latest
Client operating system: Windows 7, Windows 10
Databases: MS-SQL Server 2014
Metabase version: 0.22.2
Metabase hosting environment: Ubuntu Server 16
Metabase internal database: H2 

**metabase logfile:**

```
:query {:type "native", :native {:query 
"SELECT \"dbo\".\"MRANALYSTDATA_FOR_MR\".\"PRODUKT\" AS \"Produkt\", count(*) AS \"Anzahl Clippings\", sum(\"dbo\".\"MRANALYSTDATA_FOR_MR\".\"Auflage\") AS \"Auflage\", sum(\"dbo\".\"MRANALYSTDATA_FOR_MR\".\"Reichweite\") AS \"Reichweite\", sum(\"dbo\".\"MRANALYSTDATA_FOR_MR\".\"KOSTEN_EU\") AS \"Äquivalenzkosten\"\r\nFROM \"dbo\".\"MRANALYSTDATA_FOR_MR\" WHERE 1=1 [[AND {{**ErschDatum**}}]] [[AND {{NurProdukt}}]] [[AND {{NurKunde}}]] [[AND {{NurVATitel}}]] [[AND {{NurEigen}}]] [[AND {{NurFP}}]]\r\nGROUP BY \"dbo\".\"MRANALYSTDATA_FOR_MR\".\"PRODUKT\"\r\nORDER BY \"dbo\".\"MRANALYSTDATA_FOR_MR\".\"PRODUKT\" ASC",
 :template_tags {:ErschDatum {:id "e329b4d3-c588-c22f-e621-a8c76ed1c3d8", :name "ErschDatum", :display_name "Erschdatum", :type "dimension", :dimension ["field-id" 6626]}, :NurProdukt {:id "e6e88bf5-60cc-57c4-2c10-b8a1be7f275d", :name "NurProdukt", :display_name "Nurprodukt", :type "dimension", :dimension ["field-id" 6636]}, :NurKunde {:id "b1f5fa83-873f-8194-41ff-cad38e099274", :name "NurKunde", :display_name "Nurkunde", :type "dimension", :dimension ["field-id" 6633]}, :NurVATitel {:id "c9b48ba2-7a4c-4976-9990-98e31f643971", :name "NurVATitel", :display_name "Nurvatitel", :type "dimension", :dimension ["field-id" 6644]}, :NurEigen {:id "05fe42f6-a5c3-efd1-1f68-3f0e897a9a2e", :name "NurEigen", :display_name "Nureigen", :type "dimension", :dimension ["field-id" 6625]}, :NurFP {:id "10c841f6-3abb-d94d-2ed9-fbd422c94a6f", :name "NurFP", :display_name "Nurfp", :type "dimension", :dimension ["field-id" 6627]}}}, :parameters [{:type "date/range", :target ["dimension" ["template-tag" "ErschDatum"]], :value "2016-12-01~2016-12-15"}], :constraints {:max-results 10000, :max-results-bare-rows 2000}, :info {:executed-by 1, :card-id 25, :uuid "42b48916-b391-4b1d-922c-b03a032e79a9", :query-hash 568771100, :query-type "native"}}, :expanded-query nil}  Feb 07 09:13:15 WARN metabase.query-processor :: **Query failure: Bei der Konvertierung eines varchar-Datentyps in einen datetime-Datentyp liegt der Wert außerhalb des gültigen Bereichs**. 
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:565)" 
"query_processor$assert_query_status_successful.invoke(query_processor.clj:558)" 
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:598)" 
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:592)" 
"query_processor$dataset_query.invokeStatic(query_processor.clj:631)" 
"query_processor$dataset_query.invoke(query_processor.clj:604)" 
"api.card$run_query_for_card.invokeStatic(card.clj:357)" 
"api.card$run_query_for_card.doInvoke(card.clj:345)" 
"api.card$fn__23326$fn__23329.invoke(card.clj:362)" 
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:222)" 
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:219)" 
"api.card$fn__23326.invokeStatic(card.clj:359)" "api.card$fn__23326.invoke(card.clj:359)" 
"middleware$enforce_authentication$fn__31538.invoke(middleware.clj:84)" 
"api.routes$fn__31638.invokeStatic(routes.clj:41)" "api.routes$fn__31638.invoke(routes.clj:41)" 
"routes$fn__32636.invokeStatic(routes.clj:24)" "routes$fn__32636.invoke(routes.clj:24)" 
"middleware$log_api_call$fn__31626$fn__31628.invoke(middleware.clj:275)" 
"db$_do_with_call_counting.invokeStatic(db.clj:470)" 
"db$_do_with_call_counting.invoke(db.clj:464)" 
"middleware$log_api_call$fn__31626.invoke(middleware.clj:274)" 
"middleware$add_security_headers$fn__31585.invoke(middleware.clj:209)"
"middleware$bind_current_user$fn__31542.invoke(middleware.clj:104)"]
```

**Comment by tlrobinson** [comment] 2017-02-07 16:13
I'm not able to reproduce this with the Sample Dataset, which uses H2, so it might be a SQL Server issue.

@devaxel If you see a section of the logs starting with `PARAMS/SUBSTITUTED:` could you post that? Thanks.

**Comment by devaxel** [comment] 2017-02-08 08:43
@tlrobinson : Thanks for your feedback.
Heres the part of the logfile:

PARAMS/SUBSTITUTED: 😻 {:database 4, :type "native", :native {:query "SELECT \"dbo\".\"MRANALYSTDATA_FOR_MR\".\"PRODUKT\" AS \"Produkt\", count(*) AS \"Anzahl Clippings\", sum(\"dbo\".\"MRANALYSTDATA_FOR_MR\".\"Auflage\") AS \"Auflage\", sum(\"dbo\".\"MRANALYSTDATA_FOR_MR\".\"Reichweite\") AS \"Reichweite\", sum(\"dbo\".\"MRANALYSTDATA_FOR_MR\".\"KOSTEN_EU\") AS \"Äquivalenzkosten\"\r\nFROM \"dbo\".\"MRANALYSTDATA_FOR_MR\" WHERE 1=1 AND **CAST(CAST(\"dbo\".\"MRANALYSTDATA_FOR_MR\".\"ERSCHEINDATUM\" AS date) AS datetime) BETWEEN '2016-01-01' AND '2016-01-15'** AND 1 = 1 AND 1 = 1 AND 1 = 1 AND 1 = 1 AND 1 = 1\r\nGROUP BY \"dbo\".\"MRANALYSTDATA_FOR_MR\".\"PRODUKT\"\r\nORDER BY \"dbo\".\"MRANALYSTDATA_FOR_MR\".\"PRODUKT\" ASC", :template_tags {:ErschDatum {:id "e329b4d3-c588-c22f-e621-a8c76ed1c3d8", :name "ErschDatum", :display_name "Erschdatum", :type "dimension", :dimension ["field-id" 6626]}, :NurProdukt {:id "e6e88bf5-60cc-57c4-2c10-b8a1be7f275d", :name "NurProdukt", :display_name "Nurprodukt", :type "dimension", :dimension ["field-id" 6636]}, :NurKunde {:id "b1f5fa83-873f-8194-41ff-cad38e099274", :name "NurKunde", :display_name "Nurkunde", :type "dimension", :dimension ["field-id" 6633]}, :NurVATitel {:id "c9b48ba2-7a4c-4976-9990-98e31f643971", :name "NurVATitel", :display_name "Nurvatitel", :type "dimension", :dimension ["field-id" 6644]}, :NurEigen {:id "05fe42f6-a5c3-efd1-1f68-3f0e897a9a2e", :name "NurEigen", :display_name "Nureigen", :type "dimension", :dimension ["field-id" 6625]}, :NurFP {:id "10c841f6-3abb-d94d-2ed9-fbd422c94a6f", :name "NurFP", :display_name "Nurfp", :type "dimension", :dimension ["field-id" 6627]}}}, :parameters [{:type "date/range", :target ["dimension" ["template-tag" "ErschDatum"]], :value "2016-01-01~2016-01-15"}], :constraints {:max-results 10000, :max-results-bare-rows 2000}, :info {:executed-by 1, :card-id 25, :uuid "50113861-2c92-4eed-bc94-c3ec20d2725d", :query-hash 949182373, :query-type "native"}, :driver {}, :settings {}}

I took the Where-Clause from the metabase SQL-Statement and tried this query in SQL-Server.
**Result:**
_where (CAST(CAST(ERSCHEINDATUM AS date) AS datetime) BETWEEN '2016-01-01' AND '2016-01-15')_ produces the same error in SQL-Server.
_where (CAST(CAST(ERSCHEINDATUM AS date) AS datetime) BETWEEN '20160101' AND '20160115')_ works.

**Comment by devaxel** [comment] 2017-02-08 09:12
I think I've found the cause of this error.
The statement metabase creates (BETWEEN '2016-01-01' AND '2016-01-15') assumes that the dateformat is  MDY. But the language seeting of my database is german with a dateformat DMY. Because of this the metabase statement treats the month as day and vice versa.

Wouldn't it be better that metabase creates a statement like BETWEEN '20160101' AND '20160115'? Because this would be the ISO-format which is language independent.

Could you agree to this?

**Comment by devaxel** [comment] 2017-02-08 09:54
In the meanwhile I've found the following workaround, that works for me.

In my SQL Server I added a new user "metabase" with the default language "englisch".
In the Metabase Backend (Admin-->Databases) I changed the "Database username/password" to the new user.
Now everything is fine! The error is gone.

**Comment by camsaul** [comment] 2017-07-18 17:40
@devaxel I opened PR #5491 (branch `allow-additional-options-for-sqlserver`) which switches the JDBC driver we use under the hood from jTDS to the official Microsoft one. It seems to fix several issues with SQL Server and I have a feeling it might fix this one as well. Is there a chance you could try that branch out and see if it fixes this issue for you?

**Comment by camsaul** [comment] 2017-12-07 03:14
I believe this was fixed by the switch to the Microsoft SQL Server driver. Either way it sounds like this issue is no longer affecting you @devaxel so I'm going to go ahead and close it out. If you're still seeing it or any other problems please let us know.

**Closed by camsaul** 2017-12-07 03:14 UTC
Labels: Database/SQLServer, Need More Info, Parameters/Variables, Unable to Reproduce
