### ISSUE TITLE
Leaking dashboard permissions while using `Sample Dataset`

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#4454] opened 2017-02-28 03:51 UTC
If a user creates a question using `Sample Dataset` and saves it into his/her private dashboard, the whole dashboard is public because of permissions clashing. This would be fine since cards do not leak the data, but dashboard in itself is not. It allows any other user to now mess up the whole dashboard layout, add/remove cards to it thereby overtaking the whole dashboard.

**Comment by salsakran** [comment] 2017-02-28 21:56
Yeah, that's "by design" but is pretty annoying. Another kick in the pants to get some sort of dashboard permissions setup.

**Comment by flamber** [comment] 2019-02-13 17:36
Hi @VikramTiwari 

I've tried to reproduce your issue on 0.31.2 without success - can you try the new version to see if this issue is still valid? I would think this was resolved by the massive change in collections in 0.30

Steps I've tried, but they all give me what I would expect:
- Give data access to Sample to All Users. And View permissions to all collections.
- With Admin, create a QB question based on Sample and save it to "Our collection", then add it to a dashboard, which is located Admin's "My collection".
- With User, dashboard=denied and question=granted, as expected.
- With Admin, move the dashboard to "Our collection" and move the question to Admin's "My collection"
- With User, dashboard=granted (but card=denied) and question=denied, as expected.

**Comment by salsakran** [comment] 2019-10-11 23:06
No longer relevant since we have collection permissions now.

**Closed by salsakran** 2019-10-11 23:06 UTC
Labels: Administration/Permissions, Type:UX
