### ISSUE TITLE
Database connection errors are not shown in the setup

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#20285] opened 2022-02-07 11:54 UTC
**Describe the bug**
When there is an issue with connection to the database, the generic `An error occurred` message is shown without any field-specific error message.

**Logs**
Nothing in the browser logs.

**To Reproduce**
1. Run a fresh instance
2. Complete language and user details steps
3. Select `H2` database and type some nonsense into database form fields
4. Click `Next`
5. `An error occurred` is shown

**Expected behavior**
The backend returns a more specific field-level error message, which should be shown in the form.

**Screenshots**
<img width="722" alt="Screenshot 2022-02-07 at 14 48 10" src="https://user-images.githubusercontent.com/8542534/152783385-776eebb2-d23e-4d62-a967-c82bb6068dd1.png">
<img width="814" alt="Screenshot 2022-02-07 at 14 53 48" src="https://user-images.githubusercontent.com/8542534/152783433-6bf244fe-5d2f-4534-9e49-ecc9b21db5b2.png">

**Additional details**
Turns out to be a backend bug as it returns `errors` with `dbname`, but there is no `dbname` field for a H2 database. The correct field name is `db`.

**Comment by flamber** [comment] 2022-02-07 12:41
Seems like it's caused by frontend changes. Likely a duplicate of #10646

**Closed** 2022-08-04 07:50 UTC
Labels: Type:Bug, .Backend, First Experience/Setup
