### ISSUE TITLE
on `GET /api/actions` Cards, `dataset_query` is not deserialized properly but should be.

### ISSUE THREAD

**Issue by escherize** [metabase/metabase#23201] opened 2022-06-07 15:59 UTC
cards in the request body should have their dataset_query be json, not a string of json.

Reported here:
https://metaboat.slack.com/archives/C03E7PBDQJH/p1654610587714709

**To Reproduce**
Send a GET to /api/actions 

**Expected behavior**
On each card in the request, the dataset_query value should be json, not a string.

**Comment by camsaul** [comment] 2022-07-06 18:18
@flamber I'm removing the `Regression/master` tag since this code isn't in `master` yet. I'm not sure I would call a small bug with a _new_ API endpoint that's not present in 43.x a _regression_ either FWIW

**Comment by camsaul** [comment] 2022-07-06 19:02
Ok this was actually already fixed by #23201 but we forgot to close the issue

**Closed by camsaul** 2022-07-06 19:02 UTC
Labels: Type:Bug, Misc/API, .Backend, Actions/
