### ISSUE TITLE
BigQuery: Summarize with report/system timezone

### ISSUE THREAD

**Issue by kounoike** [metabase/metabase#15271] opened 2021-03-21 08:48 UTC
**Is your feature request related to a problem? Please describe.**

Currently, BigQuery database driver works only UTC for summarize feature. It has become an obstacle in determining the strategy of our business.

For example: I'm live in Japan, Timezone is JST+0900 (Asia/Tokyo).

|purchace_num|purchase_at(JST)|UTC to explain|
|----------------|------------------|--------------------------------|
|3|2021/3/21 08:00:00|2021/3/20 23:00:00|
|5|2021/3/21 15:00:00|2021/3/21 06:00:00|

BigQuery console:

![image](https://user-images.githubusercontent.com/6997928/111898603-81931a80-8a6a-11eb-9bc5-97448d14020c.png)

Metabase(v0.38.2)
![image](https://user-images.githubusercontent.com/6997928/111898607-88ba2880-8a6a-11eb-8093-24af8cbc96dc.png)

by hour of day/sum of purchace_num result:
![image](https://user-images.githubusercontent.com/6997928/111898649-c61eb600-8a6a-11eb-9c8a-f820560413a3.png)

by day/sum of purchace_num result:
![image](https://user-images.githubusercontent.com/6997928/111898671-e6e70b80-8a6a-11eb-9c5f-2788e0550a9e.png)

**Describe the solution you'd like**

Summarize with report timezone.

results above should be:

|hour of day|num|
|--|--|
|8 AM|3|
|3 PM|5|

|day|num|
|---|---|
|March 21|8|

**Describe alternatives you've considered**
No idea.0

**How important is this feature to you?**
Every time we write custom SQL, it slows down our decision making.

**Additional context**
I already have a solution. I will create PR for fix BigQuery driver's timezone related issues.

**Comment by flamber** [comment] 2021-03-21 08:58
Hi @kounoike 
Sounds like a duplicate of #10772 - currently Metabase does not support Report Timezone for BigQuery:
https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html
Have you considered starting with a different JVM timezone and enabling the "Use the Java Virtual Machine (JVM) timezone" in Admin > Databases > (your-BQ) ?

**Comment by kounoike** [comment] 2021-03-21 09:29
Hi @flamber
Yes, #10772 is **general** issue. This issue describe detailed problem like #12380.

I already have a solution. https://github.com/kounoike/metabase/tree/bigquery-timestamp-from-v0.38.1 this branch resolves this issue and #12380. (but, it doesn't work with current master branch)

![image](https://user-images.githubusercontent.com/6997928/111899942-08e48c00-8a73-11eb-8d55-1a5ceb310708.png)

![image](https://user-images.githubusercontent.com/6997928/111899960-1a2d9880-8a73-11eb-81ed-6031e5a6eefd.png)


I think, many RDBMS uses timezone data as **implicitly** (maybe supplied by session variable/connection parameter or others). but BQ require **explicitly** timezone for each function call.
for example, [extract](https://cloud.google.com/bigquery/docs/reference/standard-sql/timestamp_functions#extract) can get timezone, but current metabase code doesn't pass it. so, bq returns result by UTC.

for #12380, [current_datetime](https://cloud.google.com/bigquery/docs/reference/standard-sql/datetime_functions#current_datetime) also accepts timezone and metabase doesn't pass it.

So, passing timezone for these function (like my branch) can resolves above issues.

**Comment by flamber** [comment] 2021-03-21 09:39
@kounoike Okay, so should we close this feature request in favor of #12380, which is a bug report?
We are working on splitting up the Report Timezone, which should send timezone for each call - see #14056

**Comment by kounoike** [comment] 2021-03-21 09:57
I was wondering if I should make this Issue a Feature Request or a Bug Report.
I think #12380 is a bug, which root cause is "didn't pass the timezone for current_datetime(or _date, _time)".
#15271 is also a bug, "didn't pass the timezone for timestamp_trunc and extract".
These are two individual bugs.

I want to solve this issue and #12380. It makes sense if #14056 solves these issues.

**Comment by jeff303** [comment] 2021-07-22 15:10
I believe the new BigQuery driver will handle this correctly, once it's merged (via #16746).  The new driver incorporates the report timezone and is passing all our current timezone test cases.

**Comment by rlotun** [comment] 2021-09-14 16:49
new bigquery driver is merged: https://github.com/metabase/metabase/pull/16746

**Closed by rlotun** 2021-09-14 16:49 UTC
Labels: Type:Bug, Database/BigQuery, .Correctness, Misc/Timezones
