### ISSUE TITLE
Content breaking out of window frame MacBook Air. 

### ISSUE THREAD

**Issue by omassamo** [metabase/metabase#4427] opened 2017-02-22 14:23 UTC
On a MacBook Air (13'', primo 2014) and Metabase ver. 0.22.2.1, I'm experiencing that the layout breaks. 

As you can see, the right part of the window sits outside the window frame. On the screenshot I've scrolled horisontally to see the part outside of the window frame.

![skaermbillede 2017-02-22 kl 15 08 08](https://cloud.githubusercontent.com/assets/4628377/23214993/137510ec-f911-11e6-941e-9edac82de096.png)
![skaermbillede 2017-02-22 kl 15 10 58](https://cloud.githubusercontent.com/assets/4628377/23215011/1ce69b5a-f911-11e6-8c38-cda81e8f1e43.png)

This is the case in dashboard window also. 
![skaermbillede 2017-02-22 kl 15 18 14](https://cloud.githubusercontent.com/assets/4628377/23215464/c71bf538-f912-11e6-80b4-0db770629836.png)
![skaermbillede 2017-02-22 kl 15 18 09](https://cloud.githubusercontent.com/assets/4628377/23215463/c7199770-f912-11e6-9c48-69c4d94daa51.png)

**Comment by mazameli** [comment] 2017-02-22 18:03
Hmm, I'm unable to reproduce this, but I'm on MacOS Sierra, and I noticed you're on Yosemite. I'm also on a macbook pro. Have you tried restarting both your computer and the Metabase app?

**Comment by salsakran** [comment] 2017-02-22 18:10
@omassamo what version of safari are you running on that laptop?

**Comment by camsaul** [comment] 2017-02-22 18:17
I have the same issue in Safari 7.0, I think this is an old-Safari bug and duplicate of #2716

**Comment by omassamo** [comment] 2017-02-25 08:20
Hi. Thanks for the help. I updated to MacOS Sierra and the problem is gone. So I guess it was that old bug. Thanks for helping!

**Comment by camsaul** [comment] 2017-02-27 18:12
Cool, since it's fixed I'm going to go ahead and close this out

**Closed by camsaul** 2017-02-27 18:12 UTC
Labels: Browser/Safari, CSS, Need More Info, UX
