### ISSUE TITLE
Upgrading to 0.36.1 removes all foreign key metadata

### ISSUE THREAD

**Issue by landreville** [metabase/metabase#13075] opened 2020-08-05 18:23 UTC
**Describe the bug**
After upgrading from 0.33.4 to 0.36.1 all foreign key target metadata is gone.

Each data model has foreign keys still as the "foreign key" type, but the target is now empty.

Additionally, the dropdown menu to select the target has duplicates for each foreign key. One where the foreign key column name is correct and one where the name is incorrect. An example is "Dim Customer ID" (correct) and "Customer DIM Id" (incorrect). Every duplicate follows this pattern of swapping parts of the column name. If the wrong entry is selected then questions will not work because the column doesn't exist.

In one case there is no duplicate and only the incorrect name appears in the drop down.

**Logs**
During scan this repeats for most tables:
```
ERROR metabase.sync.util Error fingerprinting Table 572
```
During question
```
:class org.postgresql.util.PSQLException,
 :stacktrace
 ["org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)"
  "org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)"
  "org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)"
  "org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)"
  "org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)"
  "org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)"
  "org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)"
  "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)"
  "--> driver.sql_jdbc.execute$fn__72531.invokeStatic(execute.clj:267)"
  "driver.sql_jdbc.execute$fn__72531.invoke(execute.clj:265)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:389)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)"
  "driver.sql_jdbc$fn__73846.invokeStatic(sql_jdbc.clj:49)"
  "driver.sql_jdbc$fn__73846.invoke(sql_jdbc.clj:47)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
  "query_processor.context.default$default_runf.invoke(default.clj:67)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__45532.invoke(mbql_to_native.clj:26)"
  "query_processor.middleware.check_features$check_features$fn__44834.invoke(check_features.clj:42)"
  "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__45697.invoke(optimize_datetime_filters.clj:133)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47225.invoke(wrap_value_literals.clj:137)"
  "query_processor.middleware.annotate$add_column_info$fn__43455.invoke(annotate.clj:574)"
  "query_processor.middleware.permissions$check_query_permissions$fn__44709.invoke(permissions.clj:64)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__46215.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__44907.invoke(cumulative_aggregations.clj:61)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__46747.invoke(resolve_joins.clj:183)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39185.invoke(add_implicit_joins.clj:245)"
  "query_processor.middleware.limit$limit$fn__45518.invoke(limit.clj:38)"
  "query_processor.middleware.format_rows$format_rows$fn__45499.invoke(format_rows.clj:81)"
  "query_processor.middleware.desugar$desugar$fn__44973.invoke(desugar.clj:22)"
  "query_processor.middleware.binning$update_binning_strategy$fn__43999.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__44515.invoke(resolve_fields.clj:24)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__38734.invoke(add_dimension_projections.clj:272)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__38941.invoke(add_implicit_clauses.clj:141)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39334.invoke(add_source_metadata.clj:105)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__46412.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__43640.invoke(auto_bucket_datetimes.clj:125)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__44562.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.parameters$substitute_parameters$fn__46197.invoke(parameters.clj:114)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__44614.invoke(resolve_referenced.clj:80)"
  "query_processor.middleware.expand_macros$expand_macros$fn__45229.invoke(expand_macros.clj:158)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__39365.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47109.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46423$fn__46427.invoke(resolve_database_and_driver.clj:33)"
  "driver$do_with_driver.invokeStatic(driver.clj:61)"
  "driver$do_with_driver.invoke(driver.clj:57)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46423.invoke(resolve_database_and_driver.clj:27)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45447.invoke(fetch_source_query.clj:267)"
  "query_processor.middleware.store$initialize_store$fn__47118$fn__47119.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__47118.invoke(store.clj:10)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__44491.invoke(cache.clj:209)"
  "query_processor.middleware.validate$validate_query$fn__47127.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__45545.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39203.invoke(add_rows_truncated.clj:36)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47094.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__44850.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__46286.invoke(process_userland_query.clj:136)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__44793.invoke(catch_exceptions.clj:174)"
  "query_processor.reducible$async_qp$qp_STAR___38013$thunk__38014.invoke(reducible.clj:101)"
  "query_processor.reducible$async_qp$qp_STAR___38013.invoke(reducible.clj:107)"
  "query_processor.reducible$sync_qp$qp_STAR___38022$fn__38025.invoke(reducible.clj:133)"
  "query_processor.reducible$sync_qp$qp_STAR___38022.invoke(reducible.clj:132)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:213)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:209)"
  "query_processor$fn__47269$process_query_and_save_execution_BANG___47278$fn__47281.invoke(query_processor.clj:225)"
  "query_processor$fn__47269$process_query_and_save_execution_BANG___47278.invoke(query_processor.clj:217)"
  "query_processor$fn__47313$process_query_and_save_with_max_results_constraints_BANG___47322$fn__47325.invoke(query_processor.clj:237)"
  "query_processor$fn__47313$process_query_and_save_with_max_results_constraints_BANG___47322.invoke(query_processor.clj:230)"
  "api.dataset$fn__50604$fn__50607.invoke(dataset.clj:54)"
  "query_processor.streaming$streaming_response_STAR_$fn__35435$fn__35436.invoke(streaming.clj:73)"
  "query_processor.streaming$streaming_response_STAR_$fn__35435.invoke(streaming.clj:72)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
  "async.streaming_response$do_f_async$fn__23249.invoke(streaming_response.clj:85)"],
 :context :ad-hoc,
 :error "ERROR: column dim_customers__via__dim_custom.customer_dim_id does not exist\n  Position: 2319",
```

**To Reproduce**

I haven't been able to reproduce on a clean install yet.

**Expected behavior**
Foreign key targets to continue to exist across upgrades. 
Correct column names for foreign key targets.

**Screenshots**

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_252-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_252",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.252-b09",
    "os.name": "Linux",
    "os.version": "3.10.0-1127.18.2.el7.x86_64",
    "user.language": "en",
    "user.timezone": "America/Toronto"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.18"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.36.1",
      "date": "2020-07-30",
      "branch": "release-0.36.x",
      "hash": "55312e4"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```

**Severity**

This requires manually editing every foreign key field on every data model to select the target. It also proves to be impossible in some cases to select the correct foreign key target.

**Additional context**
Re-scanning the database also did not correct the missing foreign key targets.

**Comment by flamber** [comment] 2020-08-05 19:01
Hi @landreville 

I would recommend that you revert to your backup, then run with [MB_DB_AUTOMIGRATE](https://github.com/metabase/metabase/blob/master/docs/operations-guide/environment-variables.md#mb_db_automigrate)=false, so you can see which queries it's using to change.

You cannot assign a Foreign Key if there's no Entity Key, so it sounds like you might have lost those too in some cases.

Not sure if I have ever seen the mix of the column names - I'm going to ignore that right now, since I think it's a side-effect of some of the other problems.

Might need to use some debug logging to understand what is happening during the sync:
`java -Dlog4j.configuration=https://log4j.us/templates/metabase?trace=metabase.sync -jar metabase.jar`

By the way, latest is 0.36.3 (fixes some unrelated things)

**Comment by landreville** [comment] 2020-08-05 19:25
Thanks for the info.

I'm poking around in the internal database to see if I can fix it.

So far I've found that metabase_field rows with active = false are displayed in the foreign key target drop downs. It also appears that some metabase_fields have been changed to have visibility type "sensitive" during the upgrade and these do not appear in the target drop downs or on the data model pages.

I've deleted the inactive fields and changed all records from visibility_type sensitive to normal. This at least lets me manually choose the correct targets.

**Comment by flamber** [comment] 2020-08-05 19:45
We suspect that you might have had some corruption before upgrading, which just caused everything to explode on this upgrade, since there has been a lot of changes (and fixes) to the sync process.
Have you manually edited the application database before - instead of using the API? If not done with care, this can lead to corruption.
I still think it might be better to return to a backup, then investigate the metadata there and possibly fix it, and then upgrade.

**Comment by flamber** [comment] 2020-08-05 20:11
I've done a couple of migrations with various old instances from 0.32/0.33, but I cannot reproduce what you're experiencing at all.
I know you're just trying to fix your instance, but I would love to figure out the root cause of this, so we might be able to create a fix for it or have a script that clears up the corruption before migrations are being executed, so it doesn't explode.

**Comment by landreville** [comment] 2020-08-05 20:31
I hadn't logged into the application database prior to this.

The extra logging didn't provide anything informative. It does say `ERROR metabase.sync.util Error fingerprinting Table`, but it seems to be mostly foreign data wrappers and a couple normal tables that consist of only two foreign key columns (like a bridge table).

It appears that it's not even trying to scan the data model tables. Also if I go to the data model page and scan that table only, it doesn't appear to do anything. The logs show the post request, but no message about starting the scan.

You're advice is great and I'd encourage anyone with similar problems to follow that advice. However I went ahead and updated the metabase_fields programmatically with the correct information.

**Comment by flamber** [comment] 2020-08-05 21:04
Are you sure that it enabled the debug logging correctly? There should be a lot of extra logging about all the sync processes.
You should see something like this when starting:
```
$ java -Dlog4j.configuration=https://log4j.us/templates/metabase?trace=metabase.sync -jar metabase.jar

log4j: Parsing for [root] with value=[WARN, console].
log4j: Level token is [WARN].
log4j: Category root set to WARN
...and about 30 more lines...
08-05 23:02:01 INFO metabase.util :: Loading Metabase...
08-05 23:02:01 INFO metabase.util :: Maximum memory available to JVM: 1.9 GB
...
```

**Comment by landreville** [comment] 2020-08-06 14:28
I did see extra information, but no extra lines around the `ERROR metabase.sync.util Error fingerprinting Table` or scanning lines. Then Metabase was killed by OOM. 

Now that I've "fixed" my instance, I'll try loading a backup separately and re-doing the upgrade to see if there's any more info I can get.

**Comment by landreville** [comment] 2020-08-06 17:17
I loaded my backup into a new instance of 0.33.4 and upgraded it to 0.34.1.
The database fields look fine, the fk_target_field_id continues to be populated correctly.

However when I look at the data model on the web interface it shows an empty FK target:
![image](https://user-images.githubusercontent.com/24076/89561687-db4e1980-d7e6-11ea-903a-f59af15d0917.png)

The questions on this model continue to work though.

**Comment by landreville** [comment] 2020-08-06 17:21
Looks like fields with visibility_type "sensitive" are not included in the foreign key target options (even if they are already set as the target in the metabase_field table). Fields with active "false" are included in the foreign key target options. This leads to a confusing set of options in the foreign key target.

**Comment by flamber** [comment] 2020-08-06 18:28
@landreville I don't if you have gotten :heart: today, but here you go ;-)

Let me see if I understood you right:

1. You did the upgrade again from a backup, and now it doesn't explode? And you didn't do anything to the data before upgrading? That makes me think there was a corruption that caused many of your problems that you listed originally, but I don't understand why it's not triggering, when you run it again. This is definitely the reason for the high priority. Upgrades shouldn't explode.

2. I can reproduce the problem of setting "Do not display" on a column, then other columns referencing that column in Foreign Key will display hidden. I actually noticed this long ago, when we made some of the changes https://github.com/metabase/metabase/pull/12513#issuecomment-632238820. I would consider this a low priority bug, but perhaps you have a use-case that I didn't think of?

3. And I can also reproduce setting Foreign Key to a column, which is then removed from the schema, and sync, then it still shown as selected, and listed in the available reference. Also a bug, but low priority too.

I will probably create two separate issues for 2 and 3, but it's still 1 that has my attention.

**Comment by boardmain** [comment] 2020-08-07 07:36
i have similiar problem, after the 0.36.1 metabase filters stopped to work

**Comment by flamber** [comment] 2020-08-07 08:54
@boardmain It doesn't sound like the same problem, perhaps related. I would recommend that you create a new issue and provide as much details as possible, so we can reproduce.

**Comment by flamber** [comment] 2020-08-18 14:15
Closing this, since it seems like corrupted metadata was likely the cause of the breakage. Without reproducible steps, it's close to impossible to fix such issue. Created two issues for foreign key selectors not being handled correct.

**Closed by flamber** 2020-08-18 14:15 UTC
Labels: Administration/Metadata & Sync, Operation/Database Migrations, Priority:P1, Type:Bug
