### ISSUE TITLE
Scheduled Pulse not sending

### ISSUE THREAD

**Issue by websirnik** [metabase/metabase#11003] opened 2019-09-27 16:26 UTC
**Describe the bug**
I currently have a fairly standard Pulse. It does send out messages when I press "Send Email Now" & "Send to Slack now". But it does not send schedule messages, neither email, not Slack messages. It was working back in April, but I can't be certain which was the last Metabase version for which scheduled Pulse worked for me. Is there a way I can debug what's going on? 

<img width="453" alt="image" src="https://user-images.githubusercontent.com/282871/65784056-27511c00-e149-11e9-8c6f-8ddd48316a24.png">

**Logs**
I don't see any relevant error logs in:
`/var/log/nginx/error.log` & `/var/log/eb-docker/containers/eb-current-app/eb-7bd1e889662c-stdouterr.log`

**Information about your Metabase Installation:**

- Your operating system: Docker running on 64bit Amazon Linux/2.12.17
- Your databases:  MongoDB
- Metabase version: v0.33.2
- Metabase hosting environment:  Elastic Beanstalk
- Metabase internal database: Postgres

**Comment by flyingmachine** [comment] 2019-09-27 17:35
Thanks for reporting this, @websirnik! I believe it's a duplicate of #10088; I'm going to close this for now unless we find that it's a separate issue.

**Closed by flyingmachine** 2019-09-27 17:35 UTC
Labels: Type:Bug
