### ISSUE TITLE
Loading a dashboards sometimes query the card twice (1x without default filters and 1x with)

### ISSUE THREAD

**Issue by Digma** [metabase/metabase#3923] opened 2016-12-12 12:46 UTC
- Your browser and the version: Chrome 54.0
- Your operating system: Mac OS X El Capitan
- Your databases: Druid
- Metabase version: 20.1 (will try to reproduce the issue with 21.0)
- Metabase hosting environment: RHEL 6.7
- Metabase internal database: MySQL

Hi,

It happens from time to time (~1/15)  that when loading a dashboards (clicking on the link from the dropdown inside metabase), metabase queries data without the default filters once before then displaying the proper values with the filter. It seems to happen more often for some of our largest dashboard (~30 queries). The issue does not seem to be linked to the load as that happens also when there is a single user.

To give you a bit more context, here is the sequence of events leading sometimes to this issue (at random it appears):

1. Click on metabase dashboard from dropdown (maybe also happens from URL)
2. The cards in the dashboards are loaded a first time without any of the default filters (e.g. default value "Past 7 days" is ignored). All the cards display the incorrect results. 
(e.g. it is clearly visible that the whole timeseries has been loaded not only the "Past 7 days")
3. After a few seconds, the cards are updated and now display the proper timeseries with the proper default filter (e.g. the timeseries plot now only shows the last 7 days)

Looking at my browser request, I indeed see 2 "query" for each cards and no other events in-between.

`{"cardID":290,"parameters":[]}`
`{"cardID":290,"parameters":[{"type":"date/relative","target":["dimension",["field-id",340]],"value":"past7days"}]}`

We haven't updated yet to 0.21 and I haven't see any bug fix for this issue. However I will try to recreate this issue with the last version of metabase and I'll keep you posted.

I attached some logs that could be useful for you with this issue

[metabase-log-2016-12-12-card-loaded-twice.txt](https://github.com/metabase/metabase/files/645928/metabase-log-2016-12-12-card-loaded-twice.txt)

**Comment by parisholley** [comment] 2016-12-12 15:51
ran into this issue as well, causes the dashboard to delay because hitting the entire the entire dataset is expensive, vs. just querying for the last 30 days etc.

**Comment by Digma** [comment] 2016-12-13 15:26
I updated our metabase version and the issue is still there with metabase 0.21.0

**Comment by ralf-rf** [comment] 2016-12-16 09:56
Same experience here; but we happen to use BigQuery with a large dataset; viewing a simple dashboard now costs some good bucks... Metabase is not usable for us (cost wise) in the current condition. Hope you can find a nice fix for this 'show stopper'...

**Comment by moumny** [comment] 2016-12-19 22:07
Yep this is quite critical when the backend is slow it makes metabase unusable :( (metabase hangs while waiting for the query to complete)

Not familiar with redux but after taking a quick look it seems that while the state is being updated with dashboard data (parameters + cards) (and between each update) the query are sent. Looks like a dependency issue.

**Comment by tlrobinson** [comment] 2017-01-20 22:34
@Digma @parisholley @ralf-rf @moumny I believe this is fixed in #4123, which refactored the way parameters work. It would be great if any of you could try that branch and verify it's fixed in all cases.

**Comment by moumny** [comment] 2017-01-28 11:26
I managed to reproduce this on 

Thanks for using Metabase!
You're on version v0.23.0-snapshot
Built on 2017-01-26
Hash: c3c0f46
Branch: public-cards-and-dashboards-2.0


Setup:
I have two dashboards querying the sample dataset.
1 dashboard has 3 querys
1 dashboard has 5 querys

Both are configured with a time filter with default value = last 7 days

steps to reproduce
1. open the devtools in chrome.
2. go to network tab (i have the disable cache option ticked) (occasionally clear the logs for more readability)

3. go to questions tab
4. open a dashboard from the drop down
5. count number of query request
6. repeat 3-6 until the count is equal to double the cards in the dashboard.

**Closed** 2017-02-27 18:57 UTC
Labels: Bug, Dashboards, Performance, Priority/P1
