### ISSUE TITLE
Cannot add filter for an integer field in a question based on a saved question

### ISSUE THREAD

**Issue by sergekzhr** [metabase/metabase#15808] opened 2021-04-26 13:18 UTC
**Describe the bug**
Button "Add filter" doesn't appear after choosing an integer field and a value of this field while building a question based on a saved question.

**To Reproduce**
1. Go to 'Ask question'
2. Click on 'Simple question'
3. Click on 'Saved Questions'
4. Choose any saved question
5. Click on the purple button 'Filter'
6. Choose any integer field
7. Put some integer value

**Expected behavior**
Button "Add filter" appears

- Metabase version: (0.39.0.1)

**Comment by flamber** [comment] 2021-04-26 13:40
This only happens when the Saved Question is a Native query. Regression since 0.39.0

**Reproduce**
1. Native query > Sample Dataset > `select * from products` and save as "Q1"
2. Simple question > Saved Questions > "Q1"
3. Try to filter Rating in sidebar - or Notebook - any operator selected will show "Cancel" button or disabled "Add filter" button
4. Workaround is to click the column and "Filter by this column"
![image](https://user-images.githubusercontent.com/1447303/116091316-fdedce80-a6a4-11eb-9ca9-462f41dc132a.png)

Think it's related to #15620, but doesn't have the same workaround.

**Comment by michelle-arzul** [comment] 2021-05-03 08:00
Probably not helpful but this occurs on hosted solution as well, encountered on v1.39.1.

**Comment by pawit-metabase** [comment] 2021-09-14 03:27
I can no longer reproduce this in 0.40.4 or on master. Will create a PR to un-skip the repro.

**Comment by flamber** [comment] 2021-09-14 08:51
Fixed in 0.40.0 as part of the type inference work.

**Closed by flamber** 2021-09-14 08:51 UTC
Labels: Type:Bug, Priority:P2, Querying/Native, Querying/Nested Queries, .Reproduced, .Regression
