### ISSUE TITLE
Elastic Search (ELK) driver or connector

### ISSUE THREAD

**Issue by grimete** [metabase/metabase#10821] opened 2019-09-06 08:17 UTC
**Describe the solution you'd like**
Possibility to have our ELK cluster as a data source in Metabase.

**How important is this feature to you?**
Nice to have, as in our ELK we have already calculations done, this would complement quite well our analysis/reporting toolset. Kibana is nice for some things but for others falls short.

**Comment by flamber** [comment] 2019-09-06 08:19
Hi @grimete Duplicate of #1300. Please close this issue.

**Comment by grimete** [comment] 2019-09-06 08:20
Duplicate

**Closed** 2019-09-06 08:20 UTC
Labels: Type:New Feature
