### ISSUE TITLE
Translation message the email sent to user invite

### ISSUE THREAD

**Issue by lfandrade** [metabase/metabase#19407] opened 2021-12-17 18:53 UTC
How i can translation a message has sent to user in mail where they accepted thier metabase invitaton. See screen.

My language in the aplication is Português Brasil.

![image](https://user-images.githubusercontent.com/1465516/146593941-517b02f3-fe03-4c02-a8c7-4f68a76bd105.png)

**Comment by flamber** [comment] 2021-12-18 09:12
Duplicate of #7535

**Closed by flamber** 2021-12-18 09:12 UTC
Labels: Type:Question, .Needs Triage
