### ISSUE TITLE
Long table names can cause generated SQL errors

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#20757] opened 2022-02-27 22:08 UTC
**Describe the bug**
I've stuck this a couple of times in our production environment but struggled to reproduce from the Sample data or get a good grasp on exact steps to reproduce.

Long table names can cause incorrect SQL to be generated and questions to error. I think these long names could be either explicitly the name of the table in the database, or maybe the name generated by Metabase for the implicit joins from foreign key relationships in the data model (not so sure about this).

It feels like this has only popped up since upgrading to v0.42.x but I haven't confirmed that.

**Logs**
Javascript console:
```
error Invalid column name 'Superlongtablenametryingtofigureoutwhatsgoingonwith_11653127'.
```

Server log:
```
2022-02-28 10:48:05,147 [streaming-response-thread-pool-13] ERROR metabase.query-processor.middleware.catch-exceptions - Error processing query: null
{:database_id 2,
 :started_at #t "2022-02-28T10:48:03.377569400+13:00[Pacific/Auckland]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query: Invalid column name 'Superlongtablenametryingtofigureoutwhatsgoingonwith_11653127'.",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__53275.invoke(execute.clj:504)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:501)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:487)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:496)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:487)"
    "driver.sql_jdbc$fn__81974.invokeStatic(sql_jdbc.clj:54)"
    "driver.sql_jdbc$fn__81974.invoke(sql_jdbc.clj:52)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49660.invoke(mbql_to_native.clj:25)"
    "query_processor.middleware.check_features$check_features$fn__50406.invoke(check_features.clj:42)"
    "query_processor.middleware.limit$limit$fn__47989.invoke(limit.clj:37)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__50789.invoke(cache.clj:204)"
    "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__51822.invoke(optimize_temporal_filters.clj:204)"
    "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__51866.invoke(validate_temporal_bucketing.clj:50)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__49717.invoke(auto_parse_filter_values.clj:43)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__39778.invoke(wrap_value_literals.clj:161)"
    "query_processor.middleware.annotate$add_column_info$fn__44544.invoke(annotate.clj:659)"
    "query_processor.middleware.permissions$check_query_permissions$fn__46286.invoke(permissions.clj:108)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__51011.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46682.invoke(cumulative_aggregations.clj:60)"
    "query_processor.middleware.visualization_settings$update_viz_settings$fn__46620.invoke(visualization_settings.clj:63)"
    "query_processor.middleware.escape_join_aliases$escape_join_aliases_middleware$fn__48037.invoke(escape_join_aliases.clj:67)"
    "query_processor.middleware.fix_bad_references$fix_bad_references_middleware$fn__50976.invoke(fix_bad_references.clj:91)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47567.invoke(resolve_joined_fields.clj:111)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__51592.invoke(resolve_joins.clj:178)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__51134.invoke(add_implicit_joins.clj:193)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__47586.invoke(large_int_id.clj:59)"
    "query_processor.middleware.format_rows$format_rows$fn__51186.invoke(format_rows.clj:74)"
    "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__46954.invoke(add_default_temporal_unit.clj:23)"
    "query_processor.middleware.desugar$desugar$fn__46593.invoke(desugar.clj:21)"
    "query_processor.middleware.binning$update_binning_strategy$fn__39507.invoke(binning.clj:229)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__45928.invoke(resolve_fields.clj:34)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__50343.invoke(add_dimension_projections.clj:487)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__50637.invoke(add_implicit_clauses.clj:164)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__47974.invoke(upgrade_field_literals.clj:117)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__47331.invoke(add_source_metadata.clj:125)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__50888.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__48975.invoke(auto_bucket_datetimes.clj:147)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45909.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__48629.invoke(parameters.clj:109)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45982.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__52250.invoke(expand_macros.clj:184)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__48409.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__51201.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50648$fn__50653.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50648.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46528.invoke(fetch_source_query.clj:286)"
    "query_processor.middleware.store$initialize_store$fn__46719$fn__46720.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__46719.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__50983.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__50990.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__48355.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49646.invoke(results_metadata.clj:82)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__48373.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__50924.invoke(process_userland_query.clj:146)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51281.invoke(catch_exceptions.clj:169)"
    "query_processor.reducible$async_qp$qp_STAR___43280$thunk__43281.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___43280.invoke(reducible.clj:109)"
    "query_processor.reducible$sync_qp$qp_STAR___43289$fn__43292.invoke(reducible.clj:135)"
    "query_processor.reducible$sync_qp$qp_STAR___43289.invoke(reducible.clj:134)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:247)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:243)"
    "query_processor$fn__52298$process_query_and_save_execution_BANG___52307$fn__52310.invoke(query_processor.clj:258)"
    "query_processor$fn__52298$process_query_and_save_execution_BANG___52307.invoke(query_processor.clj:251)"
    "query_processor$fn__52342$process_query_and_save_with_max_results_constraints_BANG___52351$fn__52354.invoke(query_processor.clj:270)"
    "query_processor$fn__52342$process_query_and_save_with_max_results_constraints_BANG___52351.invoke(query_processor.clj:263)"
    "api.dataset$run_query_async$fn__65277.invoke(dataset.clj:69)"
    "query_processor.streaming$streaming_response_STAR_$fn__38416$fn__38417.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__38416.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__26888.invoke(streaming_response.clj:84)"],
   :error_type :invalid-query,
   :ex-data
   {:sql
    "-- Metabase:: userID: 1 queryType: MBQL queryHash: 8f4f22bdecd9334959135e3407fd10726c201c60cfe3d40f33310075c5eaf42e\nSELECT TOP 2000 \"rel\".\"superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation\".\"col1\" AS \"col1\", \"rel\".\"superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation\".\"col2\" AS \"col2\", \"rel\".\"superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation\".\"col3\" AS \"col3\", \"rel\".\"superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation\".\"col4\" AS \"col4\", \"Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791\".\"col1\" AS \"Superlongtablenametryingtofigureoutwhatsgoingonwith_b3f9ca3d\", \"Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791\".\"col2\" AS \"Superlongtablenametryingtofigureoutwhatsgoingonwith_2af09b87\", \"Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791\".\"col3\" AS \"Superlongtablenametryingtofigureoutwhatsgoingonwith_5df7ab11\", \"Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791\".\"col4\" AS \"Superlongtablenametryingtofigureoutwhatsgoingonwith_c3933eb2\" FROM \"rel\".\"superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation\" LEFT JOIN \"rel\".\"superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation\" \"Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791\" ON \"rel\".\"superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation\".\"col1\" = \"Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791\".\"col1\" WHERE \"rel\".\"superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation\".\"Superlongtablenametryingtofigureoutwhatsgoingonwith_11653127\" = 4 ",
    :params nil,
    :type :invalid-query}}],
 :state "S0001",
 :error_type :invalid-query,
 :json_query
 {:type "query",
  :query
  {:source-table 196,
   :joins
   [{:fields "all",
     :source-table 196,
     :condition
     ["="
      ["field" 3896 nil]
      ["field" 3896 {:join-alias "Superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation"}]],
     :alias "Superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation"}],
   :filter ["=" ["field" 3895 {:join-alias "Superlongtablenametryingtofigureoutwhatsgoingonwith_6127514c"}] 4]},
  :database 2,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT TOP 2000 \"rel\".\"superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation\".\"col1\" AS \"col1\", \"rel\".\"superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation\".\"col2\" AS \"col2\", \"rel\".\"superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation\".\"col3\" AS \"col3\", \"rel\".\"superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation\".\"col4\" AS \"col4\", \"Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791\".\"col1\" AS \"Superlongtablenametryingtofigureoutwhatsgoingonwith_b3f9ca3d\", \"Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791\".\"col2\" AS \"Superlongtablenametryingtofigureoutwhatsgoingonwith_2af09b87\", \"Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791\".\"col3\" AS \"Superlongtablenametryingtofigureoutwhatsgoingonwith_5df7ab11\", \"Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791\".\"col4\" AS \"Superlongtablenametryingtofigureoutwhatsgoingonwith_c3933eb2\" FROM \"rel\".\"superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation\" LEFT JOIN \"rel\".\"superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation\" \"Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791\" ON \"rel\".\"superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation\".\"col1\" = \"Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791\".\"col1\" WHERE \"rel\".\"superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation\".\"Superlongtablenametryingtofigureoutwhatsgoingonwith_11653127\" = 4 ",
  :params nil},
 :status :failed,
 :class com.microsoft.sqlserver.jdbc.SQLServerException,
 :stacktrace
 ["com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)"
  "com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)"
  "com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:872)"
  "com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:767)"
  "com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)"
  "com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3272)"
  "com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)"
  "com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)"
  "com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:743)"
  "com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)"
  "--> driver.sql_jdbc.execute$fn__53195.invokeStatic(execute.clj:368)"
  "driver.sql_jdbc.execute$fn__53195.invoke(execute.clj:366)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:376)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:373)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__53275.invoke(execute.clj:502)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:501)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:487)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:496)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:487)"
  "driver.sql_jdbc$fn__81974.invokeStatic(sql_jdbc.clj:54)"
  "driver.sql_jdbc$fn__81974.invoke(sql_jdbc.clj:52)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
  "query_processor.context.default$default_runf.invoke(default.clj:66)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49660.invoke(mbql_to_native.clj:25)"
  "query_processor.middleware.check_features$check_features$fn__50406.invoke(check_features.clj:42)"
  "query_processor.middleware.limit$limit$fn__47989.invoke(limit.clj:37)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__50789.invoke(cache.clj:204)"
  "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__51822.invoke(optimize_temporal_filters.clj:204)"
  "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__51866.invoke(validate_temporal_bucketing.clj:50)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__49717.invoke(auto_parse_filter_values.clj:43)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__39778.invoke(wrap_value_literals.clj:161)"
  "query_processor.middleware.annotate$add_column_info$fn__44544.invoke(annotate.clj:659)"
  "query_processor.middleware.permissions$check_query_permissions$fn__46286.invoke(permissions.clj:108)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__51011.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46682.invoke(cumulative_aggregations.clj:60)"
  "query_processor.middleware.visualization_settings$update_viz_settings$fn__46620.invoke(visualization_settings.clj:63)"
  "query_processor.middleware.escape_join_aliases$escape_join_aliases_middleware$fn__48037.invoke(escape_join_aliases.clj:67)"
  "query_processor.middleware.fix_bad_references$fix_bad_references_middleware$fn__50976.invoke(fix_bad_references.clj:91)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47567.invoke(resolve_joined_fields.clj:111)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__51592.invoke(resolve_joins.clj:178)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__51134.invoke(add_implicit_joins.clj:193)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__47586.invoke(large_int_id.clj:59)"
  "query_processor.middleware.format_rows$format_rows$fn__51186.invoke(format_rows.clj:74)"
  "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__46954.invoke(add_default_temporal_unit.clj:23)"
  "query_processor.middleware.desugar$desugar$fn__46593.invoke(desugar.clj:21)"
  "query_processor.middleware.binning$update_binning_strategy$fn__39507.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__45928.invoke(resolve_fields.clj:34)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__50343.invoke(add_dimension_projections.clj:487)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__50637.invoke(add_implicit_clauses.clj:164)"
  "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__47974.invoke(upgrade_field_literals.clj:117)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__47331.invoke(add_source_metadata.clj:125)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__50888.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__48975.invoke(auto_bucket_datetimes.clj:147)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45909.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48629.invoke(parameters.clj:109)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45982.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__52250.invoke(expand_macros.clj:184)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__48409.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__51201.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50648$fn__50653.invoke(resolve_database_and_driver.clj:35)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50648.invoke(resolve_database_and_driver.clj:34)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46528.invoke(fetch_source_query.clj:286)"
  "query_processor.middleware.store$initialize_store$fn__46719$fn__46720.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__46719.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__50983.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__50990.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__48355.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49646.invoke(results_metadata.clj:82)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__48373.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__50924.invoke(process_userland_query.clj:146)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51281.invoke(catch_exceptions.clj:169)"
  "query_processor.reducible$async_qp$qp_STAR___43280$thunk__43281.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___43280.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___43289$fn__43292.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___43289.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:247)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:243)"
  "query_processor$fn__52298$process_query_and_save_execution_BANG___52307$fn__52310.invoke(query_processor.clj:258)"
  "query_processor$fn__52298$process_query_and_save_execution_BANG___52307.invoke(query_processor.clj:251)"
  "query_processor$fn__52342$process_query_and_save_with_max_results_constraints_BANG___52351$fn__52354.invoke(query_processor.clj:270)"
  "query_processor$fn__52342$process_query_and_save_with_max_results_constraints_BANG___52351.invoke(query_processor.clj:263)"
  "api.dataset$run_query_async$fn__65277.invoke(dataset.clj:69)"
  "query_processor.streaming$streaming_response_STAR_$fn__38416$fn__38417.invoke(streaming.clj:162)"
  "query_processor.streaming$streaming_response_STAR_$fn__38416.invoke(streaming.clj:161)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$task__26888.invoke(streaming_response.clj:84)"],
 :card_id nil,
 :context :ad-hoc,
 :error "Invalid column name 'Superlongtablenametryingtofigureoutwhatsgoingonwith_11653127'.",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:type :query,
  :query
  {:source-table 196,
   :filter
   [:=
    [:field 3895 {:join-alias "Superlongtablenametryingtofigureoutwhatsgoingonwith_6127514c"}]
    [:value
     4
     {:base_type :type/Integer,
      :effective_type :type/Integer,
      :coercion_strategy nil,
      :semantic_type :type/Category,
      :database_type "int",
      :name "col4"}]],
   :fields
   [[:field 3896 nil]
    [:field 3893 nil]
    [:field 3894 nil]
    [:field 3895 nil]
    [:field 3896 {:join-alias "Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791"}]
    [:field 3893 {:join-alias "Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791"}]
    [:field 3894 {:join-alias "Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791"}]
    [:field 3895 {:join-alias "Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791"}]],
   :joins
   [{:strategy :left-join,
     :fields
     [[:field 3896 {:join-alias "Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791"}]
      [:field 3893 {:join-alias "Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791"}]
      [:field 3894 {:join-alias "Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791"}]
      [:field 3895 {:join-alias "Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791"}]],
     :source-table 196,
     :condition
     [:= [:field 3896 nil] [:field 3896 {:join-alias "Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791"}]],
     :alias "Superlongtablenametryingtofigureoutwhatsgoingonwith_1cff7791"}],
   :limit 2000},
  :database 2,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :nested? false,
   :query-hash
   [-113, 79, 34, -67, -20, -39, 51, 73, 89, 19, 94, 52, 7, -3, 16, 114, 108, 32, 28, 96, -49, -29, -44, 15, 51, 49, 0,
    117, -59, -22, -12, 46]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :data {:rows [], :cols []}}
```

**To Reproduce**
1. Create a view in source DB with a long name, I used this in SQL Serve:
```sql
CREATE view [rel].[superlongtablenametryingtofigureoutwhatsgoingonwiththetruncation]
as

Select 1 as col1, 2 as col2, 3 as col3, 4 as col4
union all
Select 2 as col1, 1 as col2, 3 as col3, 4 as col4
GO
```
2. Schema update in Metabase
3. Create new query on that table
4. Join to new table
5. Visualize
6. Click on a value from the returned table, from "Filter by this value" select "="
7. Error is presented

**Expected behavior**
SQL generated should be valid.

**Screenshots**
![image](https://user-images.githubusercontent.com/4504437/155901353-9d65eef7-4cef-427a-9ab6-de0f5fadce30.png)
![image](https://user-images.githubusercontent.com/4504437/155901491-fcf0caf1-d1df-4590-906b-002ea6990b60.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.2+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.2+8",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "clickhouse",
      "h2",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-17",
      "tag": "v0.42.1",
      "branch": "release-x.42.x",
      "hash": "629f4de"
    },
    "settings": {
      "report-timezone": "NZ"
    }
  }
}
```

**Severity**
I've get a few tables that have long names and this has tripped me up a few times. Can work around but end users won't be able to, they jsut see and error.

**Additional context**
There are also ways to trigger the same error when performing aggregates then joins on that aggregate values, this one happens in the notebook preview. I haven't been able to reliably reproduce that one but it was generally after I did an aggregate, then joined on that, then removed the aggregate step. The more spets in the notebook the more likely I am to see this error.

Resulting question looked liked this with the error shown in the final preview:
![image](https://user-images.githubusercontent.com/4504437/155901803-179f6141-cdd6-4494-a9ea-525c76e91631.png)

**Comment by flamber** [comment] 2022-02-28 08:45
Duplicate of #20627

**Closed by flamber** 2022-02-28 08:45 UTC
Labels: Type:Bug, .Needs Triage

**Comment by notrom** [comment] 2022-02-28 20:03
@flamber oops, only searched for existing open issues. Glad this one is getting fixed, it got me again yesterday after logging the issue.

**Comment by flamber** [comment] 2022-02-28 20:06
@notrom Yeah, tricked me up as well, when I was working on a different nested aliasing issue. Release coming very soon.
