### ISSUE TITLE
Permissions on collection does not allow use of filter on dashboard

### ISSUE THREAD

**Issue by jasongi-actu** [metabase/metabase#9270] opened 2019-01-15 23:35 UTC
- Your browser and the version: Chrome 71
- Your operating system: OSX Mojave
- Your databases: Postgresql
- Metabase version: 0.31.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgresql

- *Repeatable steps to reproduce the issue*

1. Create Dashboard, Add a question to the dashboard and add a filter to the dashboard and assign it to a field on the question.
2. Create new group "test"
3. Assign collection access to "test" on the dashboard
4. Create a user and assign to group "test"
5. Log in as the user in "test" and open the dashboard. You will be able to see the questions, but you won't be able to filter.

My work around for this is to also give the users data permissions on the underlying tables, but I feel like I should be able to give people access to a dashboard without giving them access to all the data.

**Comment by CoconutTherapy** [comment] 2019-02-01 16:41
I have the same issue. I can still use the filter as a basic string/int/date field but I am not able to get a list of value or a search box.

**Comment by flamber** [comment] 2019-02-10 19:15
This looks like a duplicate of #8472 or at least related.

**Comment by zDogwatch** [comment] 2019-02-10 19:29
I'm experiencing the same issue here, Granting access to the tables isn't an option for me, and as @flamber says it looks like these 2 are related.

**Comment by flamber** [comment] 2019-06-20 20:22
Actually think this is a duplicate of #7264

**Comment by flyingmachine** [comment] 2019-09-03 23:28
This has changed over time, so here is the current state of affairs:

---

In 0.33, if you load a dashboard that has a filter for a table that you don't have permissions for, then the filter will not load possible filter values. The frontend performs GET calls for `/api/field/:id` and `/api/field/:id/values`, but these both return 403. Users are therefore unable to load possible filter values if they don't have access to the underlying table.

---

It appears that the dashboard otherwise works ok. If you add an "id" filter, for example, and a user without data permission enters the number "3", then associated tables will correctly get filtered.

@paulrosenzweig helped tremendously in finding a possible solution, which is to [modify the function for getting dashboards](https://github.com/metabase/metabase/blob/release-0.33.x/src/metabase/api/dashboard.clj#L196) by adding `:param_values` and `:param_fields` to `hydrate`. A few concerns:

* It appears those hydrations were added 2018-02-20, and that has been other work to wire up these values on the frontend. So the question is, is there a reason why those hydrations aren't used?
* The dashboard still makes "forbidden" requests for the field and field values, but it looks like (what appears to be) a bandaid was applied by adding those endpoints to a [whitelist of endpoints that it's ok to receive 403 from](https://github.com/metabase/metabase/blob/release-0.33.x/frontend/src/metabase/app-main.js#L20) Is this a bandaid, and should we search for a better solution so that we're not making those API calls in the first place?
* Are we missing anything?

**Comment by camsaul** [comment] 2019-09-04 19:26
@flyingmachine @paulrosenzweig I think the `:param_values` and `:param_fields` approach is definitely the right way to go. 👍 

WRT to why those hydrate methods existed but aren't in use: they might have been used at some point in the past, or we might have added them with the intention of using them to fix the same sort of problems we're running into now, or for improving performance. If they're already there then we should definitely leverage them because they are hopefully already tested and ready to go. 

In the past if there has been code in the backend that we didn't think we should use in the future for one reason for another we've usually just went ahead and deleted it. My thinking is that you can always add it back later, but most of the time that never happens and no one benefits from looking at a bunch of dead or commented-out code.

Failing that we've at the very least marked it `^:deprecated`, and adding a blurb about why it has been declared so and what to use instead in the docstring. So generally you can assume there is no code in the Metabase backend codebase that should not be used going forward other than the small handful of things marked `^:deprecated`. If you run into something like this it unused function was almost certainly an oversight.

WRT to the 403 whitelist calls: 

Personally I think the whitelist seems like a bit of a code smell. The 403s are probably API calls we shouldn't try to be making in the first place, because permissions for them are neither implied nor guaranteed (such as the `GET /api/field/:id/values` request). It seems to me like ignoring them could be a big source of bugs that we won't see, since most the time we're testing locally with admin perms and won't run into issues caused by those endpoints failing.

To fix that we'll need to make sure approved alternative ways of getting the same data exist in the REST API, preferably by bundling the required info together into existing endpoints used to power various views (e.g. what you guys did with `:param_values`). This is a good opportunity to improve performance: just like we don't want to make N+1 requests to the application DB to load children in a parent-child relationship, ideally we don't want to end up making N+1 API requests to render a given view. 

I've seen a two-card Dashboard on Stats make 15 API calls. So getting down to N+1 is actually a good starting point here. The required data from all the calls except for the `POST /api/card/:id/query` could probably easily be rolled into the main `GET /api/dashboard/:id` endpoint. It seems like a general problem we're facing. Maybe using GraphQL could help us here. 🤷‍♂ 

One last thought: for all the 403s we *don't* ignore, I don't think aborting the entire page load is a good idea. It would be better to try to degrade gracefully and continue loading as much as possible -- for example if Dashboards can't load their FieldValues there's no reason we can't still load the filter widgets (even without loading the values), let alone the rest of the Dashboard. Aborting the entire Dashboard load because a FieldValues request failed seems like a bad fault tolerance. 

It would probably better not to ignore *any* 403s, but aggressively log them when they happen rather than aborting any page loads.

**Comment by paulrosenzweig** [comment] 2019-09-05 22:49
> for all the 403s we don't ignore, I don't think aborting the entire page load is a good idea

Unrelated to this issue, but we had another issue caused by this core problem: #10810

**Comment by paulrosenzweig** [comment] 2019-09-17 23:03
Resolved by #10799

**Closed by paulrosenzweig** 2019-09-17 23:03 UTC
Labels: Parameters/Variables, Permissions, Priority:P1, Reporting/Dashboards, Type:Bug
