### ISSUE TITLE
Add info about a user and a card to the query comment

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4438] opened 2017-02-24 03:11 UTC
Users do bad queries sometimes or saved questions begins slow execution after change the logic. Probably the good solution is to provide info about a user and a question in the comment of query.

Example:
```
/* Metabase: user=Cam Saül, card=31 */ 
SELECT * FROM table
```
or
```
/* Metabase: user=Cam Saül, card=new */ 
SELECT * FROM table
```

Also it helps to get most slowest queries. It could be for Vertica:
```
SELECT
	request as "Query",
	datediff('second', start_timestamp, end_timestamp) as "Elapsed time, sec"
FROM v_monitor.query_requests
WHERE 
	request like '%Metabase%' 
	AND datediff('second', start_timestamp, end_timestamp) > 5
ORDER BY transaction_id desc
LIMIT 30
```

**Comment by anki-code** [comment] 2017-07-25 09:42
Seems like this is the same as #2386

**Comment by mazameli** [comment] 2017-07-25 16:39
Yeah, agreed. Closing as a duplicate of #2386, which was implemented by https://github.com/metabase/metabase/pull/2687

**Closed by mazameli** 2017-07-25 16:39 UTC
Labels: Duplicate, Proposal, Query Processor
