### ISSUE TITLE
Variables - BigQuery - Error while using AS

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#4315] opened 2017-02-07 05:29 UTC
Image:
![screen shot 2017-02-06 at 21 26 09](https://cloud.githubusercontent.com/assets/1330677/22678948/318481cc-ecb3-11e6-92d0-120205010993.png)

Expected result: Query should execute and produce result properly.
Seems like this is one of the cases for #4313

**Comment by tlrobinson** [comment] 2017-02-07 18:54
The "text" type emits the variable as a single quoted string like `'value'`, but the `AS` clause is expecting an identifier or double quoted string like `"value"`.

What's the reason for needing to parameterize an `AS` clause?

**Comment by tlrobinson** [comment] 2017-02-07 18:55
Also I think this is a duplicate of #3370. Let me know if you disagree.

**Closed by tlrobinson** 2017-02-07 18:55 UTC

**Comment by VikramTiwari** [comment] 2017-02-07 19:48
Reason on parameterizing an `AS` clause: For separate teams working on the same table, the result of similar query could mean different things. For example:
  - Parameterized Query for website visits: `select sum(unique_visits) as {{visit_type}} from visits_table where landing_url={{landing_url}}`
  - Group 1: `{landing_url: 'mywebsite.com/home', visit_type: 'landing page visits'}`
  - Group 2: `{landing_url: 'mywebsite.com/offer', visit_type: 'offer visits'}`
  - Group 3: `{landing_url: 'mywebsite.com/checkout', visit_type: 'checkouts'}`

A naive case, but happens.
