### ISSUE TITLE
Exit Admin link visible from non-admin section

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#993] opened 2015-09-15 23:22 UTC
In a user testing video, I was able to see the "Exit Admin" link from a normal user's view in the main application. Browser was Safari.

![screen shot 2015-09-15 at 4 20 50 pm](https://cloud.githubusercontent.com/assets/107439/9892667/dcb70b76-5bc5-11e5-9bff-00cdcc5e3fb9.png)

**Comment by agilliland** [comment] 2015-11-26 00:49
I'm not able to reproduce this one.  @salsakran do we have any other information to go on?  i'm using safari.

**Comment by camsaul** [comment] 2016-01-21 00:52
Is this still an issue?

**Comment by camsaul** [comment] 2016-01-21 04:14
It looks like their UI was just generally in a weird/not-fully-loaded state. The "New Question" button isn't normally right next to that menu either. Motion to close @salsakran @agilliland

**Comment by agilliland** [comment] 2016-01-21 04:38
yeah, we can close this.

**Closed by agilliland** 2016-01-21 04:38 UTC
Labels: Bug, Unable to Reproduce, UX
