### ISSUE TITLE
run . ./bin/build  ,log4j:ERROR Could not instantiate class [metabase.logger.Appender].

### ISSUE THREAD

**Issue by zhangdoudou** [metabase/metabase#8178] opened 2018-07-31 09:15 UTC
### Bugs
run . ./bin/build  ,log4j:ERROR Could not instantiate class [metabase.logger.Appender].

- Your browser and the version: (e.x. Chrome 52.1)
- Your operating system: (e.x. OS X 10)
- Your databases: (default databases …)
- Metabase version: (e.x. 0.29.3)

- *Repeatable steps to reproduce the issue*

-------
run . ./bin/build  ,log4j:ERROR Could not instantiate class [metabase.logger.Appender].
Retrieving kixi/stats/0.4.1/stats-0.4.1.jar from clojars
Retrieving toucan/toucan/1.1.9/toucan-1.1.9.jar from clojars
Compiling metabase.pulse
log4j:ERROR Could not instantiate class [metabase.logger.Appender].
java.lang.ClassNotFoundException: metabase.logger.Appender
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:291)
	at org.apache.log4j.helpers.Loader.loadClass(Loader.java:198)
	at org.apache.log4j.helpers.OptionConverter.instantiateByClassName(OptionConverter.java:327)
	at org.apache.log4j.helpers.OptionConverter.instantiateByKey(OptionConverter.java:124)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:785)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.slf4j.impl.Log4jLoggerFactory.<init>(Log4jLoggerFactory.java:66)
	at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:45)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at clojure.tools.logging$eval376$reify__377.get_logger(logging.clj:286)
	at metabase.util$fn__2146.invokeStatic(util.clj:21)
	at metabase.util$fn__2146.invoke(util.clj:21)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3695)
	at clojure.lang.Compiler.compile1(Compiler.java:7609)
	at clojure.lang.Compiler.compile(Compiler.java:7676)
	at clojure.lang.RT.compile(RT.java:413)
	at clojure.lang.RT.load(RT.java:458)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5929)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:805)
	at metabase.driver$loading__6434__auto____380.invoke(driver.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3695)
	at clojure.lang.Compiler.compile1(Compiler.java:7609)
	at clojure.lang.Compiler.compile1(Compiler.java:7599)
	at clojure.lang.Compiler.compile(Compiler.java:7676)
	at clojure.lang.RT.compile(RT.java:413)
	at clojure.lang.RT.load(RT.java:458)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5929)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:805)
	at metabase.pulse$loading__6434__auto____180.invoke(pulse.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3695)
	at clojure.lang.Compiler.compile1(Compiler.java:7609)
	at clojure.lang.Compiler.compile1(Compiler.java:7599)
	at clojure.lang.Compiler.compile(Compiler.java:7676)
	at clojure.lang.RT.compile(RT.java:413)
	at clojure.lang.RT.load(RT.java:458)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$compile$fn__6553.invoke(core.clj:6056)
	at clojure.core$compile.invokeStatic(core.clj:6056)
	at clojure.core$compile.invoke(core.clj:6048)
	at user$eval164$fn__173.invoke(form-init18254021157524013133.clj:1)
	at user$eval164.invokeStatic(form-init18254021157524013133.clj:1)
	at user$eval164.invoke(form-init18254021157524013133.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
log4j:ERROR Could not instantiate appender named "metabase".
07-31 17:26:35 INFO metabase.util :: Loading Metabase...

-------

after appear this error, 
run java -jar metabase.jar
will happen default database can't link 

please help me to resolve this problem ,
thanks

**Comment by camsaul** [comment] 2018-07-31 20:40
Hi @zhangdoudou, you can ignore that error message, it's a know issue but it does not cause any problems. If you can't connect to your database it has nothing to do with that error message

**Comment by tlrobinson** [comment] 2018-08-01 17:04
Dupe of #7347 and #2624 which was previously closed as "Won't Fix"

**Closed by tlrobinson** 2018-08-01 17:04 UTC

**Comment by zhangdoudou** [comment] 2018-08-02 03:03
Hi@camsaul ,thank you for answer my question.my problem is solved.
