### ISSUE TITLE
Column settings sidebar doesn't update when one clicks on another column settings

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16053] opened 2021-05-13 22:11 UTC
**Describe the bug**
When you already have settings sidebar open for one column in a question, clicking on another column settings doesn't update the sidebar.

**Logs**
N/A

**To Reproduce**
1. Go to any question that has tabular view (Let's say Products table saved as a question)
2. Click on the header cell title (for example: "Category")
3. Click on cog/settings icon
4. Sidebar will appear
5. Now click on some other header cell (for example: "Rating")
6. Click its settings icon
7. Observe that the sidebar still shows settings for "Category"

**Expected behavior**
I would expect sidebar to update with the currently clicked column settings.

**Screenshots**
https://share.getcloudapp.com/4gu2B1d8

**Information about your Metabase Installation:**
- local dev, v0.39.2-SNAPSHOT (doesn't matter)

**Severity**
Annoying, visual. P3 at most.

**Comment by flamber** [comment] 2021-05-13 22:14
Duplicate of #16043

**Closed by flamber** 2021-05-13 22:14 UTC
Labels: .Needs Triage, Type:Bug
