### ISSUE TITLE
Unable to change date formatting in a card or column

### ISSUE THREAD

**Issue by brenonahuz** [metabase/metabase#27485] opened 2023-01-03 15:32 UTC
**Describe the bug**
When trying to change the timestamp format in columns, it is not possible to click and, consequently, change the type of formatting of a date either in a card or in a column. Even trying to change the table settings the problem persists.

**Logs**
Not aplicable

**To Reproduce**
1. Go to a collum with timestamp type.
2. Click on collum formatting.
3. Inside of 'show clock' change HH:MM to any other type of format.
  a.Even clicking in config and change the parameters no changes. 
5. See error

**Expected behavior**
Instead of showing just the minutes, it should show minutes and seconds

**Screenshots**
![image](https://user-images.githubusercontent.com/87027378/210387744-2f4dc3f3-42b3-4b29-82f6-5c57d6a8b400.png)
![image](https://user-images.githubusercontent.com/87027378/210387775-24124dff-cce4-47b1-94ea-643f017b6f2b.png)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.17+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.17",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.17+8",
    "os.name": "Linux",
    "os.version": "4.14.296-222.539.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "athena",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-12-07",
      "tag": "v0.45.1",
      "branch": "release-x.45.x",
      "hash": "019d31c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
**Severity**
This is a problem that impacts all the daily metrics of the CS team attendants. The team leader cannot correctly measure the response time for ticket openings.

Because of this, it is not possible to run the weekly attendant productivity report.

**Comment by flamber** [comment] 2023-01-04 11:59
Duplicate of #11398

**Closed by flamber** 2023-01-04 11:59 UTC
Labels: Type:Bug, .Needs Triage

**Comment by brenonahuz** [comment] 2023-01-04 12:15
@flamber We weren't having this problem before 0.44.6. Right after updating to 0.45.1 this formatting error occurred, is this expected?

**Comment by flamber** [comment] 2023-01-04 12:21
@brenonahuz Formatting of `TIME` columns has never worked. I'm seeing the same behavior on 0.44.6.

**Comment by brenonahuz** [comment] 2023-01-04 18:11
![image](https://user-images.githubusercontent.com/87027378/210621282-cd17ca67-c44d-4b72-89a6-813109777b7c.png)
We rollback to v0.44.6. In this version the formatting did not occur, and the values ​​appeared as expected.

**Comment by flamber** [comment] 2023-01-05 09:42
@brenonahuz Okay, please include the question metadata by going to the URL `/api/card/123`, where 123 is the question ID.
