### ISSUE TITLE
Connection Refused while connecting to upstream

### ISSUE THREAD

**Issue by AlexandraLouise** [metabase/metabase#3854] opened 2016-12-02 08:22 UTC
Hi - has anyone else experienced this error with Elastic Beanstalk? I am hosting the application in Ireland in a VPC and am not sure why this error is occurring.
![screen shot 2016-11-29 at 10 38 10 am](https://cloud.githubusercontent.com/assets/7575801/20827216/1e36f244-b879-11e6-9ee1-9623917e25f2.png)

**Comment by salsakran** [comment] 2016-12-07 01:58
This usually means that the java process in the container died somehow. It happens if there is an error on startup, or another critical failure.

Can you poke through the rest of the beanstalk logs and see if there are any errors that suggest the root cause?

**Comment by AlexandraLouise** [comment] 2016-12-07 08:25
Hi @salsakran - see the log file attached. Can you see anything? I don't understand what's going on really. 

[Log Files.txt](https://github.com/metabase/metabase/files/636053/Log.Files.txt)

**Comment by camsaul** [comment] 2016-12-13 03:35
@salsakran did you get a chance to look at this? I'll fix this for 0.21.1 if we can diagnose the issue

**Comment by camsaul** [comment] 2017-01-09 18:35
@salsakran did you get a chance to look at those logs yet?

**Comment by salsakran** [comment] 2017-01-09 19:15
you can look at them too ;)

the secondary symptom is that the underlying process can't connect to the application database -

```

12-07 08:20:33 [1mERROR metabase.driver[0m :: Failed to connect to database: org.postgresql.util.PSQLException: Protocol error.  Session setup failed.
java.lang.AssertionError: Assert failed: Unable to connect to Metabase DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
	at metabase.db$verify_db_connection.invokeStatic(db.clj:148)
	at metabase.db$verify_db_connection.invoke(db.clj:143)
	at metabase.db$setup_db.invokeStatic(db.clj:162)
	at metabase.db$setup_db.doInvoke(db.clj:154)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:129)
	at metabase.core$init_BANG_.invoke(core.clj:113)
	at metabase.core$start_normally.invokeStatic(core.clj:213)
	at metabase.core$start_normally.invoke(core.clj:207)
	at metabase.core$_main.invokeStatic(core.clj:247)
	at metabase.core$_main.doInvoke(core.clj:242)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
12-07 08:20:33 [1mERROR metabase.core[0m :: Metabase Initialization FAILED:  Assert failed: Unable to connect to Metabase DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
```

As to why that is happening, I'm not sure. @AlexandraLouise can you see if the RDS instance supporting that Elastic Beanstalk environment is still up and reachable?

**Comment by camsaul** [comment] 2017-05-01 22:27
@AlexandraLouise ?

**Comment by camsaul** [comment] 2017-05-05 23:24
Not sure if this is the same issue that was resolved in http://discourse.metabase.com/t/youre-question-took-too-long-using-aws-elb/730/9

**Comment by salsakran** [comment] 2017-05-05 23:30
not sure. This issue is from Dec, and her last post on the discourse issue was from October.

**Comment by camsaul** [comment] 2017-05-05 23:30
oh. good point. NVM

**Comment by mbvictoria** [comment] 2019-06-19 20:29
Closing - no updates/new reports for a long time.

**Closed by mbvictoria** 2019-06-19 20:29 UTC
Labels: Bug, Need More Info, Priority/P2, Running Metabase/Elastic Beanstalk, Unable to Reproduce
