### ISSUE TITLE
Big size of footer

### ISSUE THREAD

**Issue by deejayluk** [metabase/metabase#17230] opened 2021-07-28 09:11 UTC
**Describe the bug**
After upgrade Metabase from 0.39.2 to 0.40.1 the footer changed size (height).

**To Reproduce**
1. Go to dashboards
2. Open dashboard
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/73607094/127296162-a84d4528-9ec5-4c54-8790-eb1102f57782.png)

**Information about your Metabase Installation:**

- Your browser and the version: 92.0.4515.107
- Your operating system: Windows 10
- Your databases: MS SQL
- Metabase version: 0.40.1
- Metabase hosting environment: Ubuntu
- Metabase internal database: PostgreSQL

**Comment by flamber** [comment] 2021-07-28 09:15
Duplicate of #16798

**Closed by flamber** 2021-07-28 09:15 UTC
Labels: .Needs Triage, Type:Bug
