### ISSUE TITLE
Bar chart doesn't handle null data well

### ISSUE THREAD

**Issue by CaliLuke** [metabase/metabase#12138] opened 2020-03-16 21:49 UTC
**Is your feature request related to a problem? Please describe.**

Currently when displaying data with categorical labels, the bar chart doesn't have a way to either add a "null" category or remove it from display.

**Describe the solution you'd like**

Add a "null" category by default, and allow users to hide it or show it.

**Describe alternatives you've considered**

we could filter the values but the visualizations should be robust to a very common data issue.

**How important is this feature to you?**

very, it breaks most visualizations containing null data

**Additional context**

![2020-03-16_14-43-16](https://user-images.githubusercontent.com/73209/76802644-5ca00380-6795-11ea-89d3-edba22f32dd0.jpeg)

![2020-03-16_14-41-31](https://user-images.githubusercontent.com/73209/76802648-5e69c700-6795-11ea-9125-ac8ee92ea935.jpeg)

**Comment by flamber** [comment] 2020-03-16 22:37
Hi @CaliLuke 
Am I misunderstanding this or should it be reported as a bug, since you say it's breaking something?
And could you provide an example using Sample Dataset or static SQL, so it's easier to reproduce?

**Comment by alxnddr** [comment] 2021-04-08 22:18
The same happens when the X axis is a numeric column that contains both 0 and null:
<img width="596" alt="Screen Shot 2021-04-09 at 01 13 54" src="https://user-images.githubusercontent.com/14301985/114102922-ddfe9280-98d0-11eb-856a-ab7737fb42dd.png">

This is happening because of a bug in the `crossfilter` dependency
https://github.com/crossfilter/crossfilter/issues/164

**Comment by alxnddr** [comment] 2021-04-12 21:53
Fixed by https://github.com/metabase/metabase/pull/15554

Repro is needed

**Closed by alxnddr** 2021-04-12 21:53 UTC
Labels: .Correctness, Priority:P2, Type:Bug, Visualization/Charts
