### ISSUE TITLE
Postgres JSONB support

### ISSUE THREAD

**Issue by puhrez** [metabase/metabase#2905] opened 2016-07-06 22:19 UTC
*  I am using the Chrome browser.
*  My computer's OS is OS X Yosemite.
*  I'm running Metabase via `lein ring server` . [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is Postgres.
*  My Metabase version is 0.19.0-snapshot

got this stacktrace when syncing my db:

```
07-06 18:12:06 ERROR metabase.util :: Caught exception: 
PSQLException:
 Message: ERROR: operator does not exist: jsonb ~~ unknown
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 44
 SQLState: 42883
 Error Code: 0

["driver.generic_sql$query.invokeStatic(generic_sql.clj:204)"
 "driver.generic_sql$query.invoke(generic_sql.clj:201)"
 "driver.generic_sql$query.invokeStatic(generic_sql.clj:207)"
 "driver.generic_sql$query.invoke(generic_sql.clj:201)"
 "driver.generic_sql$fast_field_percent_urls.invokeStatic(generic_sql.clj:281)"
 "driver.generic_sql$fast_field_percent_urls.invoke(generic_sql.clj:274)"
 "driver.generic_sql$eval38315$fn__38398$G__38288__38405.invoke(generic_sql.clj:23)"
 "util$wrap_try_catch$fn__7442.doInvoke(util.clj:496)"
 "util$try_apply.invokeStatic(util.clj:520)"
 "util$try_apply.doInvoke(util.clj:508)"
 "sync_database.analyze$test_COLON_url_special_type.invokeStatic(analyze.clj:99)"
 "sync_database.analyze$test_COLON_url_special_type.invoke(analyze.clj:91)"
 "sync_database.analyze$test_COLON_new_field.invokeStatic(analyze.clj:150)"
 "sync_database.analyze$test_COLON_new_field.invoke(analyze.clj:144)"
 "sync_database.analyze$make_analyze_table$fn__33420$iter__33421__33425$fn__33426$fn__33427.invoke(analyze.clj:166)"
 "sync_database.analyze$make_analyze_table$fn__33420$iter__33421__33425$fn__33426.invoke(analyze.clj:162)"
 "sync_database.analyze$analyze_table_data_shape_BANG_.invokeStatic(analyze.clj:182)"
 "sync_database.analyze$analyze_table_data_shape_BANG_.invoke(analyze.clj:175)"
 "sync_database.analyze$analyze_data_shape_for_tables_BANG_$fn__33469.invoke(analyze.clj:218)"
 "sync_database.analyze$analyze_data_shape_for_tables_BANG_.invokeStatic(analyze.clj:217)"
 "sync_database.analyze$analyze_data_shape_for_tables_BANG_.invoke(analyze.clj:205)"
 "sync_database$sync_database_with_tracking_BANG_$fn__33872.invoke(sync_database.clj:86)"
 "sync_database$sync_database_with_tracking_BANG_.invokeStatic(sync_database.clj:74)"
 "sync_database$sync_database_with_tracking_BANG_.invoke(sync_database.clj:68)"
 "driver$fn__16859.invokeStatic(driver.clj:241)"
 "driver$fn__16859.invoke(driver.clj:241)"
 "driver$eval16629$fn__16805$G__16596__16814.invoke(driver.clj:45)"
 "sync_database$sync_database_BANG_.invokeStatic(sync_database.clj:43)"
 "sync_database$sync_database_BANG_.doInvoke(sync_database.clj:24)"
 "events.sync_database$process_sync_database_event$fn__47223.invoke(sync_database.clj:32)"]```

**Comment by camsaul** [comment] 2016-07-06 22:37
Hi @puhrez, Postgres JSON fields aren't yet supported. This exception shouldn't affect your ability to use other columns in the database normally. 

Closing as duplicate of #708

**Closed by camsaul** 2016-07-06 22:37 UTC
Labels: Duplicate
