### ISSUE TITLE
Collection Drop-Down in v0.40.0

### ISSUE THREAD

**Issue by JadAbdallah** [metabase/metabase#17169] opened 2021-07-22 13:56 UTC
**Is your feature request related to a problem? Please describe.**
In v0.40.0, when navigating through collections, the left-side pannel allows you to toggle in and out collections to get to the collection you are looking for. When you click on a question and then navigate back to the collection in which the question lives, the previously toggled / dropped-down collections disapear. 
In previous versions, the left-side navigation bar would toggle automatically to the collection you are in. This allows for efficient navigation. 

**Describe the solution you'd like**
Allow navigation bar to be auto-toggled to the collection / sub-collection in which you are. 

**Describe alternatives you've considered**
Alternative is simply retoggling and opening collections to the level you are interested in.

**How important is this feature to you?**
Can definitely live without this feature but it's something that was available in the past and was lost in the new version upgrade.

**Comment by flamber** [comment] 2021-07-22 14:02
Duplicate of #16947

**Closed by flamber** 2021-07-22 14:02 UTC
Labels: .Needs Triage, Type:New Feature
