### ISSUE TITLE
Connection Pool constantly rebuilt due to db details changes causes queries to be interrupted

### ISSUE THREAD

**Issue by vieira** [metabase/metabase#24243] opened 2022-07-23 12:35 UTC
**Describe the bug**
From what I am able to understand queries triggered by Metabase dashboards (X-Rays?) are never completed because they get interrupted `java.sql.SQLException: An SQLException was provoked by the following failure: java.lang.InterruptedException`. This seems to be caused by very frequent rebuilds of the connection pool due to metabase wrongly detecting changes in the database connection details: `Hash of database 2 details changed; marking pool invalid to reopen it`.

From #23487 this seems to happen when certificates are used in the connection details. In that case it seems that only the server ca was being used by the client to validate the server, so not veryfing the cert resolved it. 

However in our case the client certificate and private key are required by the server to validate the client, so we can't connect without using them.

**Logs**
```
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:55+01:00 DEBUG metabase.server.middleware.log GET /api/table/70/query_metadata 200 15.3 ms (9 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (69 total active threads) Queries in flight: 0 (0 queued)
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:56+01:00 DEBUG metabase.server.middleware.log GET /api/field/878 200 4.1 ms (6 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (69 total active threads) Queries in flight: 0 (0 queued)
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:56+01:00 DEBUG metabase.server.middleware.log GET /api/field/878/values 200 3.3 ms (4 DB calls) App DB connections: 3/15 Jetty threads: 5/50 (3 idle, 0 queued) (69 total active threads) Queries in flight: 0 (0 queued)
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:56+01:00 DEBUG metabase.server.middleware.log GET /api/field/864/values 200 4.5 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (0 idle, 0 queued) (69 total active threads) Queries in flight: 0 (0 queued)
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:56+01:00 DEBUG metabase.server.middleware.log GET /api/field/885/values 200 7.0 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (0 idle, 0 queued) (69 total active threads) Queries in flight: 0 (0 queued)
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:56+01:00 DEBUG metabase.server.middleware.log GET /api/field/864 200 67.6 ms (6 DB calls) App DB connections: 0/15 Jetty threads: 6/50 (1 idle, 0 queued) (69 total active threads) Queries in flight: 0 (0 queued)
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:56+01:00 DEBUG metabase.server.middleware.log GET /api/field/882 200 16.1 ms (6 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (3 idle, 0 queued) (69 total active threads) Queries in flight: 0 (0 queued)
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:56+01:00 DEBUG metabase.server.middleware.log GET /api/field/885 200 124.6 ms (6 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (2 idle, 0 queued) (73 total active threads) Queries in flight: 2 (0 queued)
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:57+01:00 WARN metabase.driver.sql-jdbc.connection Hash of database 2 details changed; marking pool invalid to reopen it
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:58+01:00 WARN metabase.driver.sql-jdbc.connection Hash of database 2 details changed; marking pool invalid to reopen it
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:58+01:00 WARN metabase.driver.sql-jdbc.connection Hash of database 2 details changed; marking pool invalid to reopen it
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:58+01:00 WARN metabase.driver.sql-jdbc.connection Hash of database 2 details changed; marking pool invalid to reopen it
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:58+01:00 WARN metabase.driver.sql-jdbc.connection Hash of database 2 details changed; marking pool invalid to reopen it
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:58+01:00 WARN metabase.driver.sql-jdbc.connection Hash of database 2 details changed; marking pool invalid to reopen it
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:58+01:00 WARN metabase.driver.sql-jdbc.connection Hash of database 2 details changed; marking pool invalid to reopen it
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:58+01:00 WARN metabase.driver.sql-jdbc.connection Hash of database 2 details changed; marking pool invalid to reopen it
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:58+01:00 WARN metabase.driver.sql-jdbc.connection Hash of database 2 details changed; marking pool invalid to reopen it
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:58+01:00 WARN metabase.driver.sql-jdbc.connection Hash of database 2 details changed; marking pool invalid to reopen it
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:58+01:00 WARN metabase.driver.sql-jdbc.connection Hash of database 2 details changed; marking pool invalid to reopen it
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:58+01:00 WARN metabase.driver.sql-jdbc.connection Hash of database 2 details changed; marking pool invalid to reopen it
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:58+01:00 WARN metabase.driver.sql-jdbc.connection Hash of database 2 details changed; marking pool invalid to reopen it
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:58+01:00 DEBUG metabase.server.middleware.log GET /api/activity/recent_views 200 195.4 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (11 idle, 0 queued) (108 total active threads) Queries in flight: 15 (0 queued)
[48f2f2cf-1d12-4e7f-94b9-1aba3f5129c3] 2022-07-23T12:12:58+01:00 ERROR metabase.models.field-values Error fetching field values
java.sql.SQLException: An SQLException was provoked by the following failure: java.lang.InterruptedException
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:74)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:694)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
	at metabase.driver.sql_jdbc.execute$fn__53784.invokeStatic(execute.clj:190)
	at metabase.driver.sql_jdbc.execute$fn__53784.invoke(execute.clj:188)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:497)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:494)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)
	at metabase.driver.sql_jdbc$fn__83581.invokeStatic(sql_jdbc.clj:54)
	at metabase.driver.sql_jdbc$fn__83581.invoke(sql_jdbc.clj:52)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.query_processor.context$executef.invokeStatic(context.clj:59)
	at metabase.query_processor.context$executef.invoke(context.clj:48)
	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:67)
	at metabase.query_processor.context.default$default_runf.invoke(default.clj:65)
	at metabase.query_processor.context$runf.invokeStatic(context.clj:45)
	at metabase.query_processor.context$runf.invoke(context.clj:39)
	at metabase.query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)
	at metabase.query_processor.reducible$identity_qp.invoke(reducible.clj:9)
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___51447.invoke(cache.clj:220)
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__47230.invoke(permissions.clj:109)
	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__50388.invoke(mbql_to_native.clj:23)
	at metabase.query_processor$fn__52921$combined_post_process__52926$combined_post_process_STAR___52927.invoke(query_processor.clj:207)
	at metabase.query_processor$fn__52921$combined_pre_process__52922$combined_pre_process_STAR___52923.invoke(query_processor.clj:204)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51368$fn__51373.invoke(resolve_database_and_driver.clj:35)
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:75)
	at metabase.driver$do_with_driver.invoke(driver.clj:71)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51368.invoke(resolve_database_and_driver.clj:34)
	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47473.invoke(fetch_source_query.clj:281)
	at metabase.query_processor.middleware.store$initialize_store$fn__47661$fn__47662.invoke(store.clj:11)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:44)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
	at metabase.query_processor.middleware.store$initialize_store$fn__47661.invoke(store.clj:10)
	at metabase.query_processor.middleware.normalize_query$normalize$fn__51640.invoke(normalize_query.clj:22)
	at metabase.query_processor.reducible$async_qp$qp_STAR___44200$thunk__44202.invoke(reducible.clj:100)
	at metabase.query_processor.reducible$async_qp$qp_STAR___44200.invoke(reducible.clj:106)
	at metabase.query_processor.reducible$async_qp$qp_STAR___44200.invoke(reducible.clj:91)
	at metabase.query_processor.reducible$async_qp$qp_STAR___44200.invoke(reducible.clj:88)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___44211.doInvoke(reducible.clj:126)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.query_processor$process_query.invokeStatic(query_processor.clj:242)
	at metabase.query_processor$process_query.doInvoke(query_processor.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.db.metadata_queries$qp_query$fn__65664.invoke(metadata_queries.clj:21)
	at metabase.db.metadata_queries$qp_query.invokeStatic(metadata_queries.clj:20)
	at metabase.db.metadata_queries$qp_query.invoke(metadata_queries.clj:18)
	at metabase.db.metadata_queries$field_query.invokeStatic(metadata_queries.clj:31)
	at metabase.db.metadata_queries$field_query.invoke(metadata_queries.clj:29)
	at metabase.db.metadata_queries$fn__65684$field_distinct_values__65693$fn__65696.invoke(metadata_queries.clj:76)
	at metabase.db.metadata_queries$fn__65684$field_distinct_values__65693.invoke(metadata_queries.clj:69)
	at metabase.db.metadata_queries$fn__65684$field_distinct_values__65693$fn__65694.invoke(metadata_queries.clj:73)
	at metabase.db.metadata_queries$fn__65684$field_distinct_values__65693.invoke(metadata_queries.clj:69)
	at clojure.lang.Var.invoke(Var.java:384)
	at metabase.models.field_values$distinct_values.invokeStatic(field_values.clj:132)
	at metabase.models.field_values$distinct_values.invoke(field_values.clj:124)
	at metabase.models.field_values$create_or_update_field_values_BANG_.invokeStatic(field_values.clj:154)
	at metabase.models.field_values$create_or_update_field_values_BANG_.doInvoke(field_values.clj:148)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at metabase.models.field_values$get_or_create_field_values_BANG_.invokeStatic(field_values.clj:219)
	at metabase.models.field_values$get_or_create_field_values_BANG_.doInvoke(field_values.clj:211)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.models.params.field_values$default_get_or_create_field_values_for_current_user_BANG__STAR_.invokeStatic(field_values.clj:27)
	at metabase.models.params.field_values$default_get_or_create_field_values_for_current_user_BANG__STAR_.invoke(field_values.clj:25)
	at metabase.models.params.field_values$reify__39377.get_or_create_field_values_for_current_user_BANG__STAR_(field_values.clj:52)
	at metabase.models.params.field_values$get_or_create_field_values_for_current_user_BANG_.invokeStatic(field_values.clj:88)
	at metabase.models.params.field_values$get_or_create_field_values_for_current_user_BANG_.invoke(field_values.clj:74)
	at metabase.api.field$field__GT_values.invokeStatic(field.clj:212)
	at metabase.api.field$field__GT_values.invoke(field.clj:200)
	at metabase.api.field$check_perms_and_return_field_values.invokeStatic(field.clj:220)
	at metabase.api.field$check_perms_and_return_field_values.invoke(field.clj:214)
	at metabase.api.field$fn__71165.invokeStatic(field.clj:227)
	at metabase.api.field$fn__71165.invoke(field.clj:223)
	at compojure.core$wrap_response$fn__28036.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__28020.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__28025.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__28029.invoke(core.clj:151)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__28029.invoke(core.clj:152)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__28029.invoke(core.clj:153)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__28029.invoke(core.clj:153)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__28029.invoke(core.clj:153)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__28029.invoke(core.clj:153)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__66770.invoke(auth.clj:14)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048.invoke(core.clj:200)
	at compojure.core$make_context$handler__28076.invoke(core.clj:289)
	at compojure.core$make_context$fn__28080.invoke(core.clj:299)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$make_context$fn__28080.invoke(core.clj:300)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$make_context$fn__28080.invoke(core.clj:300)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$make_context$fn__28080.invoke(core.clj:300)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$make_context$fn__28080.invoke(core.clj:300)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$make_context$fn__28080.invoke(core.clj:300)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$make_context$fn__28080.invoke(core.clj:300)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$make_context$fn__28080.invoke(core.clj:300)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$make_context$fn__28080.invoke(core.clj:300)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$make_context$fn__28080.invoke(core.clj:300)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$make_context$fn__28080.invoke(core.clj:300)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$make_context$fn__28080.invoke(core.clj:300)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at metabase.api.routes$fn__78132$fn__78135.invoke(routes.clj:59)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__78282$fn__78283.doInvoke(routes.clj:67)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048.invoke(core.clj:200)
	at compojure.core$make_context$handler__28076.invoke(core.clj:289)
	at compojure.core$make_context$fn__28080.invoke(core.clj:299)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__28029.invoke(core.clj:152)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__28029.invoke(core.clj:152)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__28029.invoke(core.clj:152)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
	at metabase.server.routes$fn__78268$fn__78270.invoke(routes.clj:45)
	at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
	at compojure.core$routes$fn__28048.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__75094.invoke(exceptions.clj:98)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__75091.invoke(exceptions.clj:86)
	at metabase.server.middleware.log$log_api_call$fn__78752$fn__78753$fn__78754.invoke(log.clj:211)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
	at metabase.server.middleware.log$log_api_call$fn__78752$fn__78753.invoke(log.clj:203)
	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
	at toucan.db$_do_with_call_counting.invoke(db.clj:209)
	at metabase.server.middleware.log$log_api_call$fn__78752.invoke(log.clj:202)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__81988.invoke(browser_cookie.clj:38)
	at metabase.server.middleware.security$add_security_headers$fn__60363.invoke(security.clj:148)
	at metabase.server.middleware.json$wrap_json_body$fn__81127.invoke(json.clj:63)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__81145.invoke(json.clj:99)
	at metabase.server.middleware.offset_paging$handle_paging$fn__60387.invoke(offset_paging.clj:42)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__82255.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__82274.invoke(params.clj:77)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__35185.invoke(misc.clj:59)
	at metabase.server.middleware.session$bind_current_user$fn__46657$fn__46658.invoke(session.clj:291)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:270)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:259)
	at metabase.server.middleware.session$bind_current_user$fn__46657.invoke(session.clj:290)
	at metabase.server.middleware.session$wrap_current_user_info$fn__46639.invoke(session.clj:240)
	at metabase.server.middleware.session$wrap_session_id$fn__46623.invoke(session.clj:173)
	at metabase.server.middleware.auth$wrap_api_key$fn__66778.invoke(auth.clj:27)
	at ring.middleware.cookies$wrap_cookies$fn__82175.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__35168.invoke(misc.clj:27)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__35193.invoke(misc.clj:76)
	at ring.middleware.gzip$wrap_gzip$fn__82217.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__35196.invoke(misc.clj:93)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__82004.invoke(ssl.clj:48)
	at metabase.server$async_proxy_handler$fn__78524.invoke(server.clj:73)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1503)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
	... 210 more
```

**To Reproduce**
1. Go to Admin -> Database. 
2. Upload a SSL Client Certificate (PEM)3. 
3. Upload a SSL Client Key (PKCS-8/DER or PKCS-12)
4. Save the changes. 
5. Try to use X-ray. 

**Expected behavior**
Queries are not interrupted by constant rebuilds of the connection pool due to false-positive detection of database details changes.

**Screenshots**
<img width="1148" alt="Screen Shot 2022-07-23 at 13 30 58" src="https://user-images.githubusercontent.com/207460/180604992-7d8853c5-c8e1-4e29-8c7d-80eb217492f8.png">

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.10.90+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-06-27",
      "tag": "v0.43.4",
      "branch": "release-x.43.x",
      "hash": "61cc28e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
This still allows using Metabase for simple, quick executing queries that are able to go thorugh, but any longer running queries are never returned blocking most use cases for metabase.

**Additional context**
Probably related to #23487.

My experience with metabase is limited, we were still trying to deploy and evaluate but let me know if there is any futher information we can provide or any way in which we can help.

**Comment by flamber** [comment] 2022-07-23 12:39
Duplicate of #23034

**Closed by flamber** 2022-07-23 12:39 UTC
Labels: Type:Bug, .Needs Triage

**Comment by vieira** [comment] 2022-07-24 09:13
In case anyone else is facing this issue, disabling SSL in the admin interface and specifying `ssl=true&sslcert=/path/to/cert.pem&sslkey=/path/to/key.der` etc in the additional JDBC connection string  options seems to be a working workaround for this issue for us. 

<img width="765" alt="Screen Shot 2022-07-24 at 10 12 12" src="https://user-images.githubusercontent.com/207460/180640369-a533aa4c-b2fd-451a-b7b4-24a331cb725b.png">
