### ISSUE TITLE
Tick boxes on dashboard subscription email panel are inconsistent widths

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#18924] opened 2021-11-09 22:43 UTC
**Describe the bug**
UI only, functionality works as expected. 

On the side panel for setting up and managing email subscriptions, in the section for attaching result files, when the question name is long and wrapped the question check boxes seem to get squashed and become different widths.

**Logs**
Not applicable

**To Reproduce**
1. Create questions with long names, the auto suggested names like "Orders, Filtered by Product → Rating and Product → Category" and "Orders, Count, Grouped by Product → Category and Product → Title and Created At (year), Filtered by Product → Rating" showed this for me.
2. Create dashboard and add those questions
3. Click "Sharing" > "Dashboard subscriptions" > "Email it"
4. Turn on "Attach results" toggle
5. Note the sizing of the tick boxes, they're no longer square and they are different widths

**Expected behavior**
I expected all these tick boxes to be equal height and width for all questions.

**Screenshots**
![image](https://user-images.githubusercontent.com/4504437/141017010-d7ce1587-1049-45a0-8e72-f6048698c2c5.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "13.0.2+8",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-11-09",
      "tag": "v0.41.2",
      "branch": "release-x.41.x",
      "hash": "ad599fd"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**
UI issue only, everything functions as expected, it just looks odd.

**Comment by flamber** [comment] 2021-11-09 22:47
@notrom :wave: Duplicate of #14754 :wink:

**Closed by flamber** 2021-11-09 22:47 UTC
Labels: Type:Bug, .Needs Triage
