### ISSUE TITLE
Broken visualization options for custom fields.

### ISSUE THREAD

**Issue by marketingnerds** [metabase/metabase#2639] opened 2016-05-20 19:02 UTC
*  I am using the ___Chromium 50________ browser.
*  My computer's OS is __Linux_________.
*  I'm running Metabase ___on AWS EBS_____. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is ___MariaDB________.
*  My Metabase version is __0.17.0_________.

Visualization options are limited to Table and Pie when trying to visualize two column query output: date and integer. Works well when I use an already existing column value instead of a custom one.

![image](https://cloud.githubusercontent.com/assets/15113386/15438737/9d89c404-1e9b-11e6-904d-0e2fb3a3e531.png)

**Comment by camsaul** [comment] 2016-05-23 21:52
This is a duplicate of #2546, which was fixed in 0.17.1. @marketingnerds if you upgrade to the latest version of Metabase things should work as expected 👍

**Closed by camsaul** 2016-05-23 21:52 UTC
Labels: Bug

**Comment by marketingnerds** [comment] 2016-05-24 13:43
My bad, thanks!
