### ISSUE TITLE
Pulse Missing Columns after updating from v0.29.1 to v0.29.3

### ISSUE THREAD

**Issue by HelmiRifai** [metabase/metabase#7743] opened 2018-05-28 08:37 UTC
- Your databases: Redshift
- Metabase version: v0.29.3
- Metabase hosting environment: AWS EC2 Linux
- Metabase internal database: MySQL

When updating from v0.29.1 to v0.29.3 the "name" columns in pulses disappeared. 
v0.29.1
![image](https://user-images.githubusercontent.com/4684370/40605628-9d7a6106-626b-11e8-8625-a97e6187ea62.png)

v0.29.3
![image](https://user-images.githubusercontent.com/4684370/40605441-16489554-626b-11e8-9764-e20db98d9e17.png)

I rolled back to no avail so it looks like an issue with migration. Let me know what I can query from the internal metabase db to help pinpoint what went wrong. I can't rollback the internal db and lose the work of my colleagues in between the update and me noticing the issue.

**Comment by flamber** [comment] 2020-06-03 16:39
Closing, since I haven't been able to reproduce and it doesn't seem like anyone else have had similar problems. Without field details or steps to reproduce it's difficult to know what went wrong.

**Closed by flamber** 2020-06-03 16:39 UTC
Labels: .Backend, Priority:P1, Reporting/Pulses, Type:Bug
