### ISSUE TITLE
Custom destination Click behaviour not adding Column value to Dashboard filter in URL

### ISSUE THREAD

**Issue by ChristineChetty11** [metabase/metabase#15997] opened 2021-05-11 09:20 UTC
Version 38.2

Created custom click behavior with destination as a dashboard which contains 3 filters. 
UserID is a column on the chart --> mapped to new dashboard UserID filter
Startdate is original dashboard filter -->  mapped to new dashboard StartDate filter
Enddate is original dashboard filter -->  mapped to new dashboard EndDate filter

Only StartDate and EndDate successfully pass through to new dashboard, UserID does not (UserId is not a visible field in the chart but exists in the query for the purpose of click behaviour and shows up when defining custom click behaviour). Observing network I cans ee that only startdate and endatae are passed through the url, not userid

UPDATE:
If I use the UserID in the visualization itself then it gets passed down to dashboard filter. I want to display username but pass the userID associated with the name down to the dashboard filter. Is this possible?

**Comment by flamber** [comment] 2021-05-11 09:26
Duplicate of #13927

**Closed by flamber** 2021-05-11 09:26 UTC
Labels: .Needs Triage, Type:Question
