### ISSUE TITLE
Sync of JSON columns fails in schemas where schema names contains system characters

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#23027] opened 2022-05-29 12:13 UTC
**Describe the bug**
Sync of JSON columns in a schema name with system characters fails because the schema name is not escaped.
Regression since 0.43.1 (#22523)

**To Reproduce**
1. Create a schema with silly characters
```
CREATE SCHEMA "special_/_#_%_'_""_._&_>_:_ _end";
CREATE TABLE "special_/_#_%_'_""_._&_>_:_ _end".x_jsontest ( id bigserial NOT NULL, col1 jsonb NULL, col2 jsonb NULL );
INSERT INTO "special_/_#_%_'_""_._&_>_:_ _end".x_jsontest (id, col1, col2) VALUES(1, '{"test": 1}'::jsonb, '{"test": 2}'::jsonb);
```
2. Admin > Databases > add database or sync existing database, will fail with `ERROR: syntax error at or near ""_._&_>_:_ _end.x_jsontest.col2, special_/_#_%_'_""`, because Metabase is not escaping characters of the schema name in the sync query:
```
SELECT special_/_#_%_'_"_._&_>_:_ _end.x_jsontest.col2, special_/_#_%_'_"_._&_>_:_ _end.x_jsontest.col1 FROM special_/_#_%_'_"_._&_>_:_ _end.x_jsontest LIMIT 500
```

<details><summary>Full stacktrace</summary>

```
2022-05-29 13:42:33,964 INFO api.table :: Table 'x_jsontest' is now visible. Resyncing.
2022-05-29 13:42:34,031 WARN sync.util :: Error syncing Fields for Table 'Table 6,967 'special_/_#_%_'_"_._&_>_:_ _end.x_jsontest''
org.postgresql.util.PSQLException: ERROR: syntax error at or near ""_._&_>_:_ _end.x_jsontest.col2, special_/_#_%_'_""
  Position: 73
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1090)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1084)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1113)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$reducible_query$reify__28497.reduce(jdbc.clj:1357)
	at clojure.core$transduce.invokeStatic(core.clj:6885)
	at clojure.core$transduce.invokeStatic(core.clj:6881)
	at clojure.core$transduce.invoke(core.clj:6872)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_nested_field_columns.invokeStatic(describe_table.clj:354)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_nested_field_columns.invoke(describe_table.clj:338)
	at metabase.driver.postgres$fn__59114.invokeStatic(postgres.clj:187)
	at metabase.driver.postgres$fn__59114.invoke(postgres.clj:184)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.fetch_metadata$fn__64220$nfc_metadata__64225$fn__64226.invoke(fetch_metadata.clj:33)
	at metabase.sync.fetch_metadata$fn__64220$nfc_metadata__64225.invoke(fetch_metadata.clj:28)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__64440$db_metadata__64445$fn__64446.invoke(fetch_metadata.clj:90)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__64440$db_metadata__64445.invoke(fetch_metadata.clj:84)
	at metabase.sync.sync_metadata.fields$fn__64938$sync_fields_for_table_BANG___64947$fn__64950$fn__64951.invoke(fields.clj:72)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:158)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:151)
	at metabase.sync.sync_metadata.fields$fn__64938$sync_fields_for_table_BANG___64947$fn__64950.invoke(fields.clj:71)
	at metabase.sync.sync_metadata.fields$fn__64938$sync_fields_for_table_BANG___64947.invoke(fields.clj:65)
	at metabase.sync.sync_metadata.fields$fn__64938$sync_fields_for_table_BANG___64947$fn__64948.invoke(fields.clj:68)
	at metabase.sync.sync_metadata.fields$fn__64938$sync_fields_for_table_BANG___64947.invoke(fields.clj:65)
	at metabase.sync.sync_metadata$fn__66506$sync_table_metadata_BANG___66511$fn__66512.invoke(sync_metadata.clj:58)
	at metabase.sync.sync_metadata$fn__66506$sync_table_metadata_BANG___66511.invoke(sync_metadata.clj:55)
	at metabase.sync$fn__66586$sync_table_BANG___66591$fn__66592.invoke(sync.clj:62)
	at metabase.sync$fn__66586$sync_table_BANG___66591.invoke(sync.clj:58)
	at metabase.api.table$sync_unhidden_tables$fn__74111.invoke(table.clj:76)
	at metabase.sync.concurrent$submit_task$fn__71055.invoke(concurrent.clj:20)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1977)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1977)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:671)
	at clojure.core$bound_fn_STAR_$fn__5767.doInvoke(core.clj:2007)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

**Information about your Metabase Installation:**
Tested 0.43.0 thru 0.43.1

**Severity**
Very unlikely that someone has a schema name with quotes, but not escaping names and quoting correctly can lead to other problems like case-sensitivity #23026.

**Comment by rishisv** [comment] 2022-06-07 18:05
We are on v0.43.2 (433d533 release-x.43.x) and seeing an error when syncing JSONB columns, one column name with uppercase chars and another in a table that has an underscore. Could the fix for this issue apply to the issue we are seeing or should we file a separate issue?

```
[9f6004e3-8c42-4b7c-b168-afb4aab4e9c8] 2022-06-07T23:09:40+05:30 WARN metabase.sync.util Error syncing Fields for Table 'Table 14 'public.user''
org.postgresql.util.PSQLException: ERROR: column user.metadatastored does not exist
  Hint: Perhaps you meant to reference the column "user.metaInfo".
  Position: 8
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1090)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1084)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1113)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$reducible_query$reify__28497.reduce(jdbc.clj:1357)
	at clojure.core$transduce.invokeStatic(core.clj:6885)
	at clojure.core$transduce.invokeStatic(core.clj:6881)
[......]



[9f6004e3-8c42-4b7c-b168-afb4aab4e9c8] 2022-06-07T23:09:41+05:30 WARN metabase.sync.util Error syncing Fields for Table 'Table 10 'public.user_details''
org.postgresql.util.PSQLException: ERROR: column user_details.metaInfo does not exist
  Hint: Perhaps you meant to reference the column "user_details.metaInfo".
  Position: 8
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1090)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1084)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1113)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$reducible_query$reify__28497.reduce(jdbc.clj:1357)
	at clojure.core$transduce.invokeStatic(core.clj:6885)
	at clojure.core$transduce.invokeStatic(core.clj:6881)
	at clojure.core$transduce.invoke(core.clj:6872)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_nested_field_columns.invokeStatic(describe_table.clj:354)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_nested_field_columns.invoke(describe_table.clj:
```

**Comment by howonlee** [comment] 2022-06-13 16:28
Root cause is default behavior of jdbc reducer is to transform identifier. This confuses the json query gen when we pull out the identifier for the query. Fix was to turn off transformations.

**Closed by howonlee** 2022-06-13 16:28 UTC
Labels: Type:Bug, Priority:P2, Database/Postgres, Administration/Metadata & Sync, .Backend, .Regression
