### ISSUE TITLE
Dashboard editing state isn't cleared properly

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3625] opened 2016-10-18 22:33 UTC
Previously added cards are carried over into a new dashboard sometimes.
This is on Chrome, and branch `fix-multiple-sql-filters-for-same-field`

Steps to repro:
1. create a SQL Question with a filter clause
2. save + add to an existing dashboard
3. cancel edit mode on the dashboard
4. create a new dashboard

on the new dashboard editing screen, I see the card I created in step 2.

**Comment by salsakran** [comment] 2016-10-18 22:33
and for bonus points, if I try to hit `save`, I get a failure message.

**Comment by attekei** [comment] 2017-07-18 00:52
I'm unable to reproduce this anymore – should I close the issue?

**Comment by salsakran** [comment] 2017-07-18 00:53
likely. let me try to reproduce it, but there have been enough changes to the dashboard code in the 4 months, that I imagine this has changed.

**Comment by mazameli** [comment] 2017-09-05 22:16
I just tried to repro this, too, and couldn't. Since @attekei also failed to repro it, I'm going to close.

**Closed by mazameli** 2017-09-05 22:16 UTC
Labels: Bug, Dashboards, Priority/P3
