### ISSUE TITLE
Columns with date extracts aren't sortable when clicking on column actions

### ISSUE THREAD

**Issue by jlisyc** [metabase/metabase#7673] opened 2018-05-21 11:12 UTC
### "Ascending","descending" by date error. org.postgresql.util.PSQLException: ERROR.

- Your browser and the version: (Firefox 60.0.1,)
- Your operating system: (ubuntu 16.04)
- Your databases: (Postgres)
- Metabase version: (0.28.6)
- Metabase hosting environment: (Linux/Ubuntu)
- Metabase internal database: (Postgres)

## Steps to reproduce
1. Database. Table "a_test" as 
![image](https://user-images.githubusercontent.com/33416503/40304682-f9102894-5cf7-11e8-9b8a-56c40d1a8e95.png)

2. Metabase. Ascending/Descending OK
![image](https://user-images.githubusercontent.com/33416503/40304747-2b2a46a2-5cf8-11e8-9d60-b1ea4cd75ee1.png)

3. Metabase. Grouped by DATE. Ascending/Descending KO. org.postgresql.util.PSQLException: ERROR
![image](https://user-images.githubusercontent.com/33416503/40304822-6b05dcb4-5cf8-11e8-81b1-62933cd47b5c.png)
...
![image](https://user-images.githubusercontent.com/33416503/40304846-8026b9ce-5cf8-11e8-9d42-ca4d2bb0a7b5.png)

-------------------
Thanks for Metabase project!
-------

**Comment by flamber** [comment] 2019-02-21 19:13
Hi @jlisyc 
I cannot reproduce your issue on 0.31.2 with Postgres 11.2 filled with sample data. Can you still generate the error on newer versions of Metabase?
I even did a sort by two columns - one is datetime and the other is date.
![image](https://user-images.githubusercontent.com/1447303/53194808-e2c13900-35d9-11e9-89af-9de0ea4cbc9f.png)

**Comment by jlisyc** [comment] 2019-02-22 13:49
Thanks a lot Flamber. Tested in 0.31.2 and postgres 9.6 and works OK.

**Comment by flamber** [comment] 2019-02-22 16:56
@jlisyc Great! Please close this issue then :wink:

**Closed** 2019-02-22 18:05 UTC
Labels: Bug, Priority/P3, Query Builder
