### ISSUE TITLE
Grouped by lists not showing all available fields

### ISSUE THREAD

**Issue by lucameazzaidb** [metabase/metabase#22834] opened 2022-05-19 10:10 UTC
We have a table containing descriptions (varchar column type database mysql).
Does not show fields in group by selection
After 1 day the fileds appear inside the group by selection.

1. Create a new questions
2. Select the table
3. Open the group by selection

We expect that we find all the table field inside the group by selection.

![image](https://user-images.githubusercontent.com/97533518/169268339-2edb39f2-a669-43d0-aefe-91ee5fe70850.png)
Field "GroupAccountDescription" disappears from group by selection.
![image](https://user-images.githubusercontent.com/97533518/169268493-675d339c-9bbc-4376-bb62-8c367089767f.png)

**Information about your Metabase Installation:**
- Chrome,Safari,Firefox
- Ubuntu, Windows,  Mac
- Database: Mysql
- Metabase version: 0.41.2
- Metabase hosting environment: AWS Ubuntu
- Metabase internal database: MySQL

**Comment by flamber** [comment] 2022-05-19 10:17
You should upgrade immediately to a newer version of Metabase: https://github.com/metabase/metabase/releases/latest
It's because the field type is "Description" or is set as only visible in details view in the Data Model:
https://www.metabase.com/docs/latest/administration-guide/03-metadata-editing.html
Duplicate of #13926

**Closed by flamber** 2022-05-19 10:17 UTC
Labels: Type:Bug, .Needs Triage
