### ISSUE TITLE
It is not possible to select data in the simple question and the customized question

### ISSUE THREAD

**Issue by tatusis** [metabase/metabase#12477] opened 2020-05-07 21:19 UTC
**Describe the bug**
It is not possible to select data in the simple question and the customized question. Databases do not load, even after a refresh.

**Logs**
The log does not present any error messages related to these reported events.

**To Reproduce**
1. Go to 'Ask a question'
2. Click on 'Simple question' or 'custom question'

**Expected behavior**
It is expected that it will be possible to select a database and, subsequently, the desired table or view. Native query is working.

**Screenshots**
![image](https://user-images.githubusercontent.com/55719904/81344916-ff864700-908d-11ea-86bc-1b99e312c119.png)

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_241-b07",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_241",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.241-b07",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "America/Sao_Paulo"
  },
  "metabase-info": {
    "databases": [
      "oracle",
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.14"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.3",
      "date": "2020-04-21",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
It is impossible for a user to create a simple question or a customized question.

**Additional context**
Through the "browse data" option, all databases and tables are accessible. I have used this path to create such questions.

**Comment by flamber** [comment] 2020-05-08 08:32
Duplicate of #12330. Workaround: turn on Admin > Settings > General > "Enable Nested Queries"

**Closed by flamber** 2020-05-08 08:32 UTC
Labels: .Duplicate, Type:Bug
