### ISSUE TITLE
Ability to manually reorder funnel steps

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7937] opened 2018-06-25 21:32 UTC
Right now it's a bit annoying when creating a funnel that the order of the steps is tied to the sort order for the step column. If you have steps whose values are text labels (`Cold lead`, `Qualified lead` etc.), they very likely might not be meant to be sequenced in alphabetical order. This means you currently have to append numbers to your steps to get them to show up in the right order.

A decent solution would be to list each of the step field's values in the viz options and let you drag and drop to reorder them.

**Comment by tlrobinson** [comment] 2018-09-05 17:29
Duplicate of #5401

**Closed by tlrobinson** 2018-09-05 17:29 UTC
Labels: Enhancement, UX, Visualization/Chart Settings
