### ISSUE TITLE
Color picker for Scalar visualization

### ISSUE THREAD

**Issue by derekbrimley** [metabase/metabase#7357] opened 2018-04-16 22:13 UTC
We have a dashboard that uses several cards with the scalar visualization, and it would be useful to use different colors to differentiate them. It could use the same color picker that the current bar chart uses, in the same settings tab as the rest of the settings currently.

**Comment by alvaroc1** [comment] 2018-04-17 14:52
Maybe some different colors based on custom thresholds too?

**Comment by flamber** [comment] 2019-02-17 21:09
Hi @derekbrimley 
This is a duplicate of #5760, but you probably didn't find it because it doesn't contain the word "Scalar".
By the way, there's a visualization called `Gauge`, which was added in 0.31.
![image](https://user-images.githubusercontent.com/1447303/52919115-6a4e3580-32c4-11e9-8f73-94f175399557.png)

**Comment by flamber** [comment] 2020-06-03 08:25
Closing in favor of #5760

**Closed by flamber** 2020-06-03 08:25 UTC
Labels: Type:New Feature, Visualization/Chart Settings
