### ISSUE TITLE
order   of columns 

### ISSUE THREAD

**Issue by qhuiliuliu** [metabase/metabase#9864] opened 2019-04-28 08:29 UTC
when i select the table ,the fields ware order by alphabet. i want to change the order by The database which the source table in . how should i do

**Comment by flamber** [comment] 2019-04-28 14:51
Hi @qhuiliuliu 
Please only create your question in one place - and use the forum for questions and troubleshooting:
https://discourse.metabase.com/t/field-order-problem/6067

**Comment by mazameli** [comment] 2019-05-13 21:02
I think this is an implicit request for the ability to define the default sort order of columns for tables, which is a dupe of https://github.com/metabase/metabase/issues/3720

**Closed by mazameli** 2019-05-13 21:02 UTC
Labels: Duplicate
