### ISSUE TITLE
Add filter to all cards in dashboard with single button

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#22885] opened 2022-05-23 13:59 UTC
**Is your feature request related to a problem? Please describe.**
When you're building big dashboards (let's say 15 questions) and you have 3 filters, connecting those 3 filters to the questions won't be a good experience as you'll have to do 45 clicks not considering the edit and save.

**Describe the solution you'd like**
When defining a filter, have a way of connecting the filter to all the cards in the dashboard on the same field, to improve ergonomics

**Describe alternatives you've considered**
Programatically do it, but won't be accesible to everyone

**How important is this feature to you?**
Interesting feature, nice to have

**Additional context**
Reported by a lead

**Comment by flamber** [comment] 2022-05-23 14:40
Duplicate of #4767

**Closed by flamber** 2022-05-23 14:40 UTC
Labels: Reporting/Dashboards, Type:New Feature, Querying/Parameters & Variables
