### ISSUE TITLE
Aggregating with Custom Column doesn't show sub-totals in pivot table

### ISSUE THREAD

**Issue by cbalusek** [metabase/metabase#36046] opened 2023-11-22 16:19 UTC
### Describe the bug

When you aggregate by a custom column, pivot tables do not show totals.

### To Reproduce

1.  Create a new GUI question using the sample data
2. Start with the order table
3. Join the Products table
4. Create a custom column.  I created "better year" :  year([Created At])
5. Summarize count by "Product Category" and "better year". 
<img width="657" alt="image" src="https://github.com/metabase/metabase/assets/22856340/5a81224a-13ce-4221-b07b-14e9a700d862">

Output:
<img width="356" alt="image" src="https://github.com/metabase/metabase/assets/22856340/94dd9c72-c86d-4b7f-8ae5-197f75e5475d">

### Expected behavior

Pivot tables should do totals

### Information about your Metabase installation

```JSON
- running on Master
```

### Severity

Fairly annoying, especially as I can't download this information either

### Additional context

Related to https://github.com/metabase/metabase/issues/26919 but worse

**Comment by cdeweyx** [comment] 2024-07-01 14:06
Dupe of https://github.com/metabase/metabase/issues/26919?

**Comment by cdeweyx** [comment] 2024-08-06 21:15
Unable to reproduce [here](https://stats.metabase.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoxLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjMsImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdLFsic3VtIixbImZpZWxkIiwyNCx7ImJhc2UtdHlwZSI6InR5cGUvRmxvYXQifV1dXSwiYnJlYWtvdXQiOltbImZpZWxkIiwxNix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSxbImV4cHJlc3Npb24iLCJiZXR0ZXIgeWVhciIseyJiYXNlLXR5cGUiOiJ0eXBlL0ludGVnZXIifV1dLCJleHByZXNzaW9ucyI6eyJiZXR0ZXIgeWVhciI6WyJnZXQteWVhciIsWyJmaWVsZCIsMjkseyJiYXNlLXR5cGUiOiJ0eXBlL0RhdGVUaW1lIn1dXX19fSwiZGlzcGxheSI6InBpdm90IiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7InBpdm90X3RhYmxlLmNvbHVtbl9zcGxpdCI6eyJyb3dzIjpbWyJmaWVsZCIsMTYseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sWyJleHByZXNzaW9uIiwiYmV0dGVyIHllYXIiXV0sImNvbHVtbnMiOltdLCJ2YWx1ZXMiOltbImFnZ3JlZ2F0aW9uIiwwXSxbImFnZ3JlZ2F0aW9uIiwxXV19LCJwaXZvdF90YWJsZS5jb2x1bW5fd2lkdGhzIjp7ImxlZnRIZWFkZXJXaWR0aHMiOls5NiwxMDBdLCJ0b3RhbExlZnRIZWFkZXJXaWR0aHMiOjE5NiwidmFsdWVIZWFkZXJXaWR0aHMiOnt9fSwicGl2b3RfdGFibGUuY29sbGFwc2VkX3Jvd3MiOnsidmFsdWUiOltdLCJyb3dzIjpbWyJmaWVsZCIsMTYseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sWyJleHByZXNzaW9uIiwiYmV0dGVyIHllYXIiXV19fSwidHlwZSI6InF1ZXN0aW9uIn0=). Likely was addressed in v49 like [this issue](https://github.com/metabase/metabase/issues/26919) was

**Closed by cdeweyx** 2024-08-06 21:15 UTC
Labels: Type:Bug, Priority:P2, .Frontend, Visualization/Tables, .Team/DashViz
