### ISSUE TITLE
Dashboard: Click Custom destination don't respect Site URL

### ISSUE THREAD

**Issue by gustavotrott** [metabase/metabase#16185] opened 2021-05-21 15:13 UTC
**Describe the bug**
In a Dashboard _Number Element_ I changed **Click behavior** and set "Go to a custom destination" -> "Link to question"
When I click in the dashboard element it goes to the question URL but loses the configured site param of the URL.

**To Reproduce**

1. Configure a reverse proxy in Apache as `ProxyPass /bi http://0.0.0.0:3000`
2. Configure Metabase Site URL as: http://sistema.local/bi
3. Create a Dashboard with a Number Element
4. Edit the Dashboard and change the click behavior of this _Number Element_ and link to a Question.
5. Click in the Element

**Expected behavior**
Expected Url: `http://sistema.local/bi/question/17`
Actual...Url: `http://sistema.local/question/17` (missing the /bi)

**Screenshots**
Change click Behavior
![image](https://user-images.githubusercontent.com/5660191/119159495-a76a7a80-ba2d-11eb-8cdc-65e373e0a1ee.png)

Link to a question
![image](https://user-images.githubusercontent.com/5660191/119159507-ab969800-ba2d-11eb-8c73-1bff7230a62e.png)

Click in the element
![image](https://user-images.githubusercontent.com/5660191/119159523-b0f3e280-ba2d-11eb-8003-55aab39d2b3e.png)

Went to a wrong URL (missing /bi)
![image](https://user-images.githubusercontent.com/5660191/119159534-b4876980-ba2d-11eb-9172-8662a3e99eeb.png)

Configured Site URL (with /bi)
![image](https://user-images.githubusercontent.com/5660191/119159545-b6e9c380-ba2d-11eb-905e-736b08216d4f.png)

**Information about your Metabase Installation:**
Metabase v0.39.2 running on Linux CentOS

**Comment by flamber** [comment] 2021-05-21 15:16
Duplicate of #13602

**Closed by flamber** 2021-05-21 15:16 UTC
Labels: .Needs Triage, Type:Bug
