### ISSUE TITLE
High CPU usage after upgrade to 0.26.1

### ISSUE THREAD

**Issue by rbhalla** [metabase/metabase#6209] opened 2017-10-19 16:02 UTC
Running on ECS (using docker image), connecting to Redshift. 

CPU spikes at 45 past the hour, and reduces at ~20 past the hour. Restarting the task doesn't seem to do much, for now I've increased CPU allocation, but ideally would like to resolve any problem.

Not sure if this is related to the deadlock issue raised in another issue. If it is, feel free to close.

Let me know if you need anymore specific information.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by firiz** [comment] 2017-10-20 00:49
I'am running jar version on Ubuntu 16 and this is happening to me as well.

**Comment by Eilliar** [comment] 2017-10-23 11:51
Yeah, it happens to me too. The process consumes 100% of CPU and metabase completely freezes. One can't access the interface, it keeps loading forever. So I have to restart the process.

Some infos:
Running metabase on a 	t2.medium instance in AWS, Ubuntu 16.04 with openjdk version "1.8.0_131". Also starting the jar with -Xmx1024M.

When this happens, the log does not give any clue on the cause, it just show some errors from Slack integration (but this is turned off in the admin panel) and stops logging until I restart the process.

**Comment by rbhalla** [comment] 2017-10-26 16:06
<img width="883" alt="screen shot 2017-10-26 at 17 03 07" src="https://user-images.githubusercontent.com/5897045/32063728-d7cc2758-ba6f-11e7-8ad5-644acb071e30.png">

Upgraded to 0.26.2. Seemed better at the beginning but now in alarm state for longer periods of time. Seems like a buildup of something being processed? Complete guess but I'll try and dig in a bit more.

**Comment by rbhalla** [comment] 2017-10-30 11:48
For anyone stumbling upon this issue, disabling xray "solved" this problem.

**Comment by rbhalla** [comment] 2017-11-14 09:50
Resurrecting this old thread again, apologies.

After monitoring it for a couple of weeks now past that, disabling xrays did reduce how long the spikes persisted, but didn't completely eliminate hourly spikes. Again this only seems to be something happening on the latest version (now 0.26.2)

<img width="1264" alt="screen shot 2017-11-14 at 09 47 30" src="https://user-images.githubusercontent.com/5897045/32773468-2b440148-c921-11e7-93b8-a680e8da4612.png">

**Comment by camsaul** [comment] 2017-11-15 01:23
@sbelak is this the X-ray sync stuff that's causing these performance spikes?

**Comment by sbelak** [comment] 2017-11-15 07:32
No. X-rays are purely on demand/frontend triggered. If it's as nicely periodic as this, it's something else.

**Comment by rbhalla** [comment] 2017-11-15 07:36
I've been digging more into metabase's settings and it seems like turning off hourly scanning for filter values drastically reduces the peaks hourly. I'm guessing the remaining smaller peaks are related to the database syncing that happens.

<img width="1417" alt="screen shot 2017-11-15 at 07 35 26" src="https://user-images.githubusercontent.com/5897045/32824116-9d5c0e68-c9d7-11e7-904c-c77eda5d7e69.png">

I did initially tie some of the improvement to xrays, so I'm going to switch those back on and confirm that wasn't actually affecting anything.

**Comment by nkconnor** [comment] 2017-11-15 19:04
Yes, turning off the scanning has fixed this issue for us as well. I hope this is addressed in a patch as the scans could easily take down or cripple a production database after upgrade

**Comment by hexleyOlive** [comment] 2018-01-08 09:05
Same issues, after upgrade Metabase from 0.25 to the latest 0.27.2, DATABASE SYNCING
 and SCANNING FOR FILTER VALUES have created performance impact and high activities on SQL Server.

DATABASE SYNCING take around 1hr and around 30% of SQL CPU (I've setup one time Daily).
SCANNING FOR FILTER VALUES take 2hrs and around 50% of SQL CPU (I've setup one time Weekly).

DATABASE SYNCING should be "lightweight process", but is very (too) high to only checks updates to database schema.

**Comment by abronte** [comment] 2018-07-23 20:35
I see the same issue on 0.29.3.

Other details:
* syncing configured for 6am daily
* scanning for filter values set to manual 
* x-rays disabled
* metabase CPU pegged at 100% seems to happen randomly
* Presto/hive and postgres backends configured. Don't see CPU issues with them

**Comment by sbelak** [comment] 2020-07-02 08:23
Closing this, since we've done a lot of work on performance and how we manage connections.

**Closed** 2020-07-02 08:23 UTC
Labels: Administration/Metadata & Sync, Type:Performance
