### ISSUE TITLE
aggregation result exceeds maximum document size (16MB)

### ISSUE THREAD

**Issue by esaiekuitche** [metabase/metabase#6347] opened 2017-11-07 20:23 UTC
Hi 
How can I handle with this error?

There was a problem with your question
Most of the time this is caused by an invalid selection or bad input value. Double check your inputs and retry your query.
`
Show error details
Here's the full error message
Command failed with error 16389: 'aggregation result exceeds maximum document size (16MB)' on server 127.0.0.1:27017. The full response is { "ok" : 0.0, "errmsg" : "aggregation result exceeds maximum document size (16MB)", "code" : 16389 }
`

**Comment by kdoh** [comment] 2017-11-07 23:36
@esaiekuitche Mind giving us more information like your Metabase version, your database, and other information [we ask for in the issue template](https://github.com/metabase/metabase/blob/master/.github/ISSUE_TEMPLATE.md#bugs)?

**Comment by esaiekuitche** [comment] 2017-11-08 15:33
Sorry for missing these informations @kdoh ,

My Metabase version is  v0.26.1,
And MongoDB version is v3.2.12,
I running these two tools on ubuntu 14.

Thank you for your help.

**Comment by salsakran** [comment] 2017-12-04 20:24
This is a mongo error thrown when you are trying to pull down more in a result than mongo likes. Can you share the specific query? Is it generated by the GUI or a native mongo query?

**Comment by flamber** [comment] 2020-05-24 20:36
Duplicate of #6134

**Closed by flamber** 2020-05-24 20:36 UTC
Labels: Database/Mongo
