### ISSUE TITLE
Chart Name does not update

### ISSUE THREAD

**Issue by Varunram** [metabase/metabase#5193] opened 2017-05-25 16:02 UTC
### Version: Latest version of the mac app

I don't know if this is a bug, but lets say you have two chart named bar1 and bar2 and want to merge them into one. But you decide to rename their names to foo1 and foo2. Inside the edit option of the chart on the dashboard, we get foo1 and bar2 (i.e. Second chart's name has not been updated).

**Comment by mazameli** [comment] 2017-05-25 18:52
Could you provide some screenshots of what you're describing exactly? I tried this both on the Mac app as well as the web app but couldn't reproduce what I think you're describing.

**Comment by Varunram** [comment] 2017-05-25 19:21
@mazameli Here are the relevant screenshots

<img width="558" alt="screen shot 2017-05-26 at 12 37 49 am" src="https://cloud.githubusercontent.com/assets/18598959/26466713/5aa8d9aa-41ad-11e7-989d-fb7757f1f981.png">
<img width="1129" alt="screen shot 2017-05-26 at 12 37 44 am" src="https://cloud.githubusercontent.com/assets/18598959/26466722/5f53a5de-41ad-11e7-8c60-d13a49cd484a.png">
<img width="991" alt="screen shot 2017-05-26 at 12 37 03 am" src="https://cloud.githubusercontent.com/assets/18598959/26466719/5e42ca08-41ad-11e7-9ff2-016821bf836a.png">

**Comment by mazameli** [comment] 2017-05-25 19:58
I see. I think what you're actually experiencing is that you changed the title of the _card_ rather than the saved question. I.e., if you click on the gear/settings icon on a dashboard card, and then put something in the "Title" input box, that changes the title of the _card_, not the name of the underlying saved question. So the add-graph menu is showing the titles of the saved questions; not the title of the card that you edited in the settings menu.

I'm going to close this unless you think there's something else going on here.

**Closed by mazameli** 2017-05-25 19:58 UTC
Labels: Need More Info

**Comment by Varunram** [comment] 2017-05-26 13:12
Ah, thanks. I didn't notice that there was a difference there. Sorry for the issue!
