### ISSUE TITLE
0.23.1 broke TIMESTAMP {{date}} variable use case in postgres

### ISSUE THREAD

**Issue by marko8904** [metabase/metabase#4675] opened 2017-04-03 18:40 UTC
I've been using queries with

TIMESTAMP {{date}}

peppered throughout SQL.

As of 0.23.1 using this construct gives me
ERROR: syntax error at or near "$1"

but if I use the date explicitly
TIMESTAMP '2017-02-18'

then it's all fine.

Switching the variable type to Text and quoting it didn't help.

**Comment by camsaul** [comment] 2017-04-03 18:42
Duplicate of #4545

**Closed by camsaul** 2017-04-03 18:42 UTC

**Comment by camsaul** [comment] 2017-04-03 18:46
@marko8904 as explained in #4545 we made some security improvements in the most recent release so you should use `{{date}}::timestamp` syntax instead of `TIMESTAMP {{date}}`.
