### ISSUE TITLE
Postgres Money Column Prevents Metabase From Seeing Table

### ISSUE THREAD

**Issue by JColeH** [metabase/metabase#14196] opened 2020-12-24 19:47 UTC
**Describe the bug**
When creating a Postgres table with a currency column and then the data in that column is of a particular form, Metabase is unable to find, show, or analyze the those tables.  

**To Reproduce**
* Create a Postgres database
* Load in the following 6 tables.  3 of them will not be viewable in Metabase and 3 of them will be.  The ones that are not viewable in Metabase are named "broken_table_..." and the ones that are viewable are named "working_table_..."
```
-- This table works fine.  Notice the last two rows which are the problem values, are last
DROP TABLE IF EXISTS "working_table_1" CASCADE;
CREATE TABLE "working_table_1" (
    "amount" MONEY
);
INSERT INTO "working_table_1" ("amount") VALUES
('$223.20'),
('$1,294.61'),
('$485.00'),
('$485.00'),
('$1,300.00'),
('$3,800.00'),
('$4,023.19');


DROP TABLE IF EXISTS "broken_table_1" CASCADE;
CREATE TABLE "broken_table_1" (
    "amount" MONEY
);
INSERT INTO "broken_table_1" ("amount") VALUES
('$4,023.19'),
('$3,800.00'), -- These two rows being put up to top seems to break something in Metabase's introspection
('$223.20'),
('$1,294.61'),
('$485.00'),
('$485.00'),
('$1,300.00');

DROP TABLE IF EXISTS "broken_table_2" CASCADE;
CREATE TABLE "broken_table_2" (
    "amount" MONEY
);
INSERT INTO "broken_table_2" ("amount") VALUES
('$3,800.00'); -- Even when we put one single value in the table Metabase is unable to see it

DROP TABLE IF EXISTS "broken_table_3" CASCADE;
CREATE TABLE "broken_table_3" (
    "amount" MONEY
);
INSERT INTO "broken_table_3" ("amount") VALUES
('$4,023.19'); -- This value is also problematic

DROP TABLE IF EXISTS "working_table_2" CASCADE;
CREATE TABLE "working_table_2" (
    "amount" numeric -- Instead of being a MONEY type, if we use NUMERIC type then things will work fine
);
INSERT INTO "working_table_2" ("amount") VALUES
('4023.19');


DROP TABLE IF EXISTS "working_table_3" CASCADE;
CREATE TABLE "working_table_3" (
    "amount" MONEY
);
INSERT INTO "working_table_3" ("amount") VALUES
('$485.00'), -- Putting a single 'working' value before the bad value, seems to allow metabase to recognize the table again
('4023.19');

SELECT * FROM pg_tables WHERE schemaname='public';
```
* Note the output of the final select statement in the code above should show that all six tables were successfully created and should look like this:

SELECT

>  * FROM pg_tables WHERE schemaname='public';
>  schemaname |    tablename    |   tableowner   | tablespace | hasindexes | hasrules | hastriggers | rowsecurity 
> ------------+-----------------+----------------+------------+------------+----------+-------------+-------------
>  public     | working_table_1 | aczagkuzlrlqis |            | f          | f        | f           | f
>  public     | broken_table_1  | aczagkuzlrlqis |            | f          | f        | f           | f
>  public     | broken_table_2  | aczagkuzlrlqis |            | f          | f        | f           | f
>  public     | broken_table_3  | aczagkuzlrlqis |            | f          | f        | f           | f
>  public     | working_table_2 | aczagkuzlrlqis |            | f          | f        | f           | f
>  public     | working_table_3 | aczagkuzlrlqis |            | f          | f        | f           | f

* Connect the new Postgres database to Metabase
* View all of the tables in that database by existing the admin pages, and then clicking on the database.  You should see tables listed as follows:

<img width="1519" alt="image" src="https://user-images.githubusercontent.com/2365069/103104608-1e195e00-45dd-11eb-9589-66acc236a717.png">

**Expected behavior**
Only the three "working..." tables are visible in Metabase.  There is no logical reason for all six tables not to be visible.  We would expect to see working_table_1, working_table_2, working_table_3, broken_table_1, broken_table_2, and broken_table_3 all visible within the Metabase application and analyzable.  In practice we only see three tables.  

**Screenshots**
See screenshots above

**Severity**
We have a workaround but it necessitates us using Numeric columns instead of Money columns in our database.  We would much prefer not to change our schema for the sake of getting our BI tool to view it.  Without this workaround we cannot use Metabase as some key tables use MONEY columns and just happen to have data in such a way that break Metabase.  

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-us",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.186-146.268.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-10-26",
      "tag": "v1.37.0.2",
      "branch": "release-x.37.x",
      "hash": "7996551"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Metabase Logs **
Below are the logs during a database sync against the database that has six tables, only 3 of which are ultimately visible:

```
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 DEBUG metabase.middleware.log POST /api/database/36/sync_schema 200 3.6 ms (1 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (4 idle, 0 queued) (58 total active threads) Queries in flight: 0 (0 queued)
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util STARTING: Sync metadata for postgres Database 36 'Currency Test'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util STARTING: step 'sync-timezone' for postgres Database 36 'Currency Test'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util FINISHED: step 'sync-timezone' for postgres Database 36 'Currency Test' (10.8 ms)
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util STARTING: step 'sync-tables' for postgres Database 36 'Currency Test'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util FINISHED: step 'sync-tables' for postgres Database 36 'Currency Test' (36.2 ms)
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util STARTING: step 'sync-fields' for postgres Database 36 'Currency Test'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util FINISHED: step 'sync-fields' for postgres Database 36 'Currency Test' (44.6 ms)
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util STARTING: step 'sync-fks' for postgres Database 36 'Currency Test'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util FINISHED: step 'sync-fks' for postgres Database 36 'Currency Test' (49.9 ms)
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util STARTING: step 'sync-metabase-metadata' for postgres Database 36 'Currency Test'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util FINISHED: step 'sync-metabase-metadata' for postgres Database 36 'Currency Test' (29.1 ms)
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util FINISHED: Sync metadata for postgres Database 36 'Currency Test' (202.5 ms)
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util STARTING: Analyze data for postgres Database 36 'Currency Test'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util STARTING: step 'fingerprint-fields' for postgres Database 36 'Currency Test'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [*****·············································] 😢   10% Table 696 'public.working_table_1'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [**********········································] 😞   20% Table 695 'public.working_table_2'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [***************···································] 😕   30% Table 697 'public.working_table_3'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util FINISHED: step 'fingerprint-fields' for postgres Database 36 'Currency Test' (10.6 ms)
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util STARTING: step 'classify-fields' for postgres Database 36 'Currency Test'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.analyze classify-fields Analyzed [********************······························] 😐   40% Table 696 'public.working_table_1'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.analyze classify-fields Analyzed [*************************·························] 😬   50% Table 695 'public.working_table_2'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.analyze classify-fields Analyzed [******************************····················] 😌   60% Table 697 'public.working_table_3'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util FINISHED: step 'classify-fields' for postgres Database 36 'Currency Test' (4.4 ms)
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util STARTING: step 'classify-tables' for postgres Database 36 'Currency Test'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.analyze classify-tables Analyzed [**********************************················] 😏   70% Table 696 'public.working_table_1'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.analyze classify-tables Analyzed [****************************************··········] 😊   80% Table 695 'public.working_table_2'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.analyze classify-tables Analyzed [********************************************······] 😍   90% Table 697 'public.working_table_3'
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util FINISHED: step 'classify-tables' for postgres Database 36 'Currency Test' (6.3 ms)
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:20-08:00 INFO metabase.sync.util FINISHED: Analyze data for postgres Database 36 'Currency Test' (41.6 ms)
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:28-08:00 DEBUG metabase.middleware.log GET /api/session/properties 200 4.1 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (3 idle, 0 queued) (59 total active threads) Queries in flight: 0 (0 queued)
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:28-08:00 DEBUG metabase.middleware.log GET /api/user/current 200 3.9 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (3 idle, 0 queued) (59 total active threads) Queries in flight: 0 (0 queued)
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:28-08:00 DEBUG metabase.middleware.log GET /api/database 200 6.4 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (4 idle, 0 queued) (60 total active threads) Queries in flight: 0 (0 queued)
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:28-08:00 DEBUG metabase.middleware.log GET /api/database/36/schemas 200 6.0 ms (4 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (4 idle, 0 queued) (60 total active threads) Queries in flight: 0 (0 queued)
[75c0887a-10ce-4cea-b135-fa7bf7d26d0f] 2020-12-24T11:46:28-08:00 DEBUG metabase.middleware.log GET /api/database/36/schema/public 200 5.9 ms (4 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (4 idle, 0 queued) (60 total active threads) Queries in flight: 0 (0 queued)
```

**Comment by flamber** [comment] 2020-12-25 11:24
Hi @JColeH 
There were some issues with syncing some types of columns, which made it not sync the entire table, but those should have been fixed - please try latest release, 1.37.4 - I cannot reproduce on that version.
```
2020-12-25 12:22:38,977 INFO sync.util :: STARTING: Sync metadata for postgres Database 22 'postgres-12'
2020-12-25 12:22:38,979 INFO driver.impl :: Initializing driver :postgres...
2020-12-25 12:22:38,982 INFO sync.util :: STARTING: step 'sync-timezone' for postgres Database 22 'postgres-12'
2020-12-25 12:22:39,183 INFO sync.util :: FINISHED: step 'sync-timezone' for postgres Database 22 'postgres-12' (200.7 ms)
2020-12-25 12:22:39,184 INFO sync.util :: STARTING: step 'sync-tables' for postgres Database 22 'postgres-12'
2020-12-25 12:22:39,247 INFO sync-metadata.tables :: Found new tables: (Table  'public.working_table_2' Table  'public.working_table_1' Table  'public.broken_table_2' Table  'public.broken_table_3' Table  'public.broken_table_1' Table  'public.working_table_3')
2020-12-25 12:22:39,291 INFO sync-metadata.tables :: Updating description for tables: (Table  'public.working_table_2' Table  'public.broken_table_3' Table  'public.broken_table_1' Table  'public.working_table_3' Table  'public.broken_table_2' Table  'public.working_table_1')
2020-12-25 12:22:39,292 INFO sync.util :: FINISHED: step 'sync-tables' for postgres Database 22 'postgres-12' (107.3 ms)
2020-12-25 12:22:39,293 INFO sync.util :: STARTING: step 'sync-fields' for postgres Database 22 'postgres-12'
2020-12-25 12:22:39,510 WARN sync.describe-table :: Don't know how to map column type '_x_types_set' to a Field base_type, falling back to :type/*.
2020-12-25 12:22:39,766 INFO sync.util :: FINISHED: step 'sync-fields' for postgres Database 22 'postgres-12' (473.5 ms)
2020-12-25 12:22:39,767 INFO sync.util :: STARTING: step 'sync-fks' for postgres Database 22 'postgres-12'
2020-12-25 12:22:40,002 INFO sync.util :: FINISHED: step 'sync-fks' for postgres Database 22 'postgres-12' (234.9 ms)
2020-12-25 12:22:40,003 INFO sync.util :: STARTING: step 'sync-metabase-metadata' for postgres Database 22 'postgres-12'
2020-12-25 12:22:40,039 INFO sync.util :: FINISHED: step 'sync-metabase-metadata' for postgres Database 22 'postgres-12' (36.2 ms)
2020-12-25 12:22:40,107 INFO sync.util :: FINISHED: Sync metadata for postgres Database 22 'postgres-12' (1.1 s)
2020-12-25 12:22:40,109 INFO sync.util :: STARTING: Analyze data for postgres Database 22 'postgres-12'
2020-12-25 12:22:40,114 INFO sync.util :: STARTING: step 'fingerprint-fields' for postgres Database 22 'postgres-12'
2020-12-25 12:22:40,149 INFO sync.analyze :: fingerprint-fields Analyzed [*****·············································] 😢   12% Table 1,284 'sampledata.reviews'
2020-12-25 12:22:40,457 INFO sync.analyze :: fingerprint-fields Analyzed [***********·······································] 😒   23% Table 1,369 'public.working_table_2'
2020-12-25 12:22:40,677 INFO sync.util :: FINISHED: step 'fingerprint-fields' for postgres Database 22 'postgres-12' (562.9 ms)
2020-12-25 12:22:40,677 INFO sync.util :: STARTING: step 'classify-fields' for postgres Database 22 'postgres-12'
2020-12-25 12:22:40,684 INFO sync.analyze :: classify-fields Analyzed [*****************·································] 😕   35% Table 1,278 'sampledata.products'
2020-12-25 12:22:40,690 INFO sync.analyze :: classify-fields Analyzed [***********************···························] 😬   46% Table 1,285 'sampledata.x_types'
2020-12-25 12:22:40,721 INFO sync.analyze :: classify-fields Analyzed [****************************······················] 😌   58% Table 1,370 'public.working_table_1'
2020-12-25 12:22:40,733 INFO sync.util :: FINISHED: step 'classify-fields' for postgres Database 22 'postgres-12' (54.9 ms)
2020-12-25 12:22:40,733 INFO sync.util :: STARTING: step 'classify-tables' for postgres Database 22 'postgres-12'
2020-12-25 12:22:40,741 INFO sync.analyze :: classify-tables Analyzed [**********************************················] 😏   69% Table 1,280 'sampledata.test2'
2020-12-25 12:22:40,747 INFO sync.analyze :: classify-tables Analyzed [****************************************··········] 😊   81% Table 1,286 'sampledata.test4'
2020-12-25 12:22:40,764 INFO sync.analyze :: classify-tables Analyzed [**********************************************····] 😍   92% Table 1,371 'public.broken_table_2'
2020-12-25 12:22:40,776 INFO sync.util :: FINISHED: step 'classify-tables' for postgres Database 22 'postgres-12' (42.6 ms)
2020-12-25 12:22:40,790 INFO sync.util :: FINISHED: Analyze data for postgres Database 22 'postgres-12' (680.1 ms)
```
![image](https://user-images.githubusercontent.com/1447303/103133693-15438d80-46ac-11eb-9702-3d047fda0267.png)

**Comment by JColeH** [comment] 2020-12-25 22:50
Thank you @flamber,  sorry if this is a dumb question, but we are using Metabase hosted.  My upgrade screen shows this.  Is there another way to upgrade our version?

<img width="454" alt="image" src="https://user-images.githubusercontent.com/2365069/103142886-75dcc580-46c0-11eb-8256-0c429b34a9f1.png">

**Comment by flamber** [comment] 2020-12-26 10:46
@JColeH 
Please use support email and request an upgrade via store.metabase.com - I'm unsure why your instance haven't been upgraded.
I'm unsure if you had already run sync before the log you showed, since there should normally be a line like this on first table sync:
`INFO sync-metadata.tables :: Found new tables: (Table ... Table ... Table ...)`

**Comment by flamber** [comment] 2021-01-29 18:02
@JColeH Closing, since all instances are now using x.37.7, so it should work - please comment back if it doesn't.

**Closed by flamber** 2021-01-29 18:02 UTC
Labels: .Needs Triage, Type:Bug
