### ISSUE TITLE
Question breaking after source column drop / rename

### ISSUE THREAD

**Issue by rrr2rrr** [metabase/metabase#39008] opened 2024-02-21 14:39 UTC
### Describe the bug

Question breaking after source column drop / rename

![telegram-cloud-photo-size-2-5382109736247350706-y](https://github.com/metabase/metabase/assets/18265924/ebd4e62d-4b55-41e0-91ae-9303caa77110)

Question don't self-rebuild a list of fields even after manually opening the dropdown and changing something.

<img width="382" alt="image" src="https://github.com/metabase/metabase/assets/18265924/b58a9d28-b338-4ee8-82de-fd6a0395162b">

### I suggest

- Automatically fix Question Definition (SQL) for all Questions, if the column isn't used in Question while syncing the database
- Give options in broken queries: remove column, choose another column, sync database (if u decide to return the field3)

### To Reproduce

1. Create table `tmp(field1, field2, field3, field4)`
2. Create a Question in the Metabase interface. Select **Field 1**, **Field 2** and **Field 3**
3. Remove column `field3` from table `tmp`. Add `field5` to table `tmp`
4. Sync schema
5. Open Question in the Metabase and see the error `...column field3 does not exists...`
6. Open Question Editor, and press dropdown on the table. You will see **Field 1**, **Field 2**, **Field 4** and **Field 5**
7. There is no obvious way to do something to fix the Question
8. The only way to fix, this is to press "Select all" and then manually uncheck **Field 4** and **Field 5**

### Expected behavior
_Product team update:_
The expected behavior is to ignore inactive fields in the query processor pipeline but **keep** it in the query definition.
It is important to keep the field in the query definition because if we implement a tool to let users "find and replace" fields, the reference must still be there. [Slack discussion](https://metaboat.slack.com/archives/C04DN5VRQM6/p1708527955950719)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "ru-RU",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "5.4.0-169-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "googleanalytics"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.6 (Debian 11.6-1.pgdg90+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-07-24",
      "tag": "v0.46.6.2",
      "branch": "patch-google-sso-button",
      "hash": "a4c740a"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

### Severity

I was almost fired with the words “you broke our working tool”

**Comment by luizarakaki** [comment] 2024-02-21 18:48
Updated the issue with the expected behavior

**Comment by camsaul** [comment] 2024-06-26 03:16
Removing bug label since the planned solution (adding new tools to replace removed columns) is a new feature and not a a problem with existing functionality

**Comment by camsaul** [comment] 2024-06-26 03:20
Duplicate of #12721

**Closed by camsaul** 2024-06-26 03:20 UTC
Labels: Priority:P2, Querying/Processor, .Backend, .Team/QueryProcessor
