### ISSUE TITLE
Feature Request: 100% Stacked Charts (Bars and Area) 

### ISSUE THREAD

**Issue by arabold** [metabase/metabase#3705] opened 2016-10-31 23:36 UTC
I'm using stacked bar chart to visualize retention numbers segmented by different criteria. My calculations are based on absolute numbers and every segment (a column in the graph below) has a different number of total entries which makes the bar have different heights. This is how the raw data looks like visualized using the current bar chart:
![image](https://cloud.githubusercontent.com/assets/1548229/19875066/10be4bc2-9f87-11e6-9863-7ea5ac34d71f.png)

What I _actually_ would want to see is a normalization to 100% of every column, so all bars have the same height and I can visually compare the distribution of values (the differently colored bar segments). This is how I _want_ it to look like:
![image](https://cloud.githubusercontent.com/assets/1548229/19875045/ea52588e-9f86-11e6-99d3-e3ba9cab7e13.png)

Of course I can update my queries to return percentage values instead of absolute ones, but my preferred solution would be the chart itself normalizing the values for me (e.g. compare with Excel's "100% Stacked Column" chart). This applies to both stacked bar charts and stacked area charts.

**Comment by arabold** [comment] 2016-11-01 21:54
Looking at this again, I think it would make sense to add a new entry "100%" in Y-axis scale options here:

![image](https://cloud.githubusercontent.com/assets/1548229/19909024/067a6a62-a043-11e6-9935-486b3278e8d1.png)

**Comment by tlrobinson** [comment] 2016-11-01 21:57
That makes sense to me. @mazameli @kdoh @salsakran?

Also this is a duplicate of @3246, lets continue the discussion there.

**Closed by tlrobinson** 2016-11-01 21:57 UTC
Labels: Duplicate

**Comment by freakinruben** [comment] 2016-11-08 09:09
@tlrobinson Not sure if it's a duplicate of #3246, the title also names area-charts. Any chance they could also be normalized?

**Comment by tlrobinson** [comment] 2016-11-08 16:28
@freakinruben Area charts are included as well.
