### ISSUE TITLE
Error when using saved questions as a CTE + parameters

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#14199] opened 2020-12-25 00:12 UTC
**Describe the bug**
If you have a native SQL question with both a parameter with an input widget as well as a question template variable (eg `{{#1}}` an error gets thrown:

`Invalid value "1" for parameter "parameterIndex" [90008-197]`

**Logs**
Stacktrace

```
"org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:64)","org.postgresql.core.v3.SimpleParameterList.setStringParameter(SimpleParameterList.java:127)","org.postgresql.jdbc.PgPreparedStatement.bindString(PgPreparedStatement.java:1002)","org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:332)","org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:319)","org.postgresql.jdbc.PgPreparedStatement.setObject(PgPreparedStatement.java:902)","com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.setObject(NewProxyPreparedStatement.java:1008)","--> driver.sql_jdbc.execute$set_object.invokeStatic(execute.clj:180)","driver.sql_jdbc.execute$set_object.invoke(execute.clj:177)","driver.sql_jdbc.execute$fn__76995.invokeStatic(execute.clj:189)","driver.sql_jdbc.execute$fn__76995.invoke(execute.clj:187)","driver.sql_jdbc.execute$set_parameters_BANG_$fn__77013.invoke(execute.clj:233)","driver.sql_jdbc.execute$set_parameters_BANG_.invokeStatic(execute.clj:229)","driver.sql_jdbc.execute$set_parameters_BANG_.invoke(execute.clj:225)","driver.sql_jdbc.execute$fn__77017.invokeStatic(execute.clj:247)","driver.sql_jdbc.execute$fn__77017.invoke(execute.clj:236)","driver.sql_jdbc.execute$prepared_statement_STAR_.invokeStatic(execute.clj:256)","driver.sql_jdbc.execute$prepared_statement_STAR_.invoke(execute.clj:253)","driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:389)","driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:376)","driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:385)","driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:376)","driver.sql_jdbc$fn__78599.invokeStatic(sql_jdbc.clj:49)","driver.sql_jdbc$fn__78599.invoke(sql_jdbc.clj:47)","query_processor.context$executef.invokeStatic(context.clj:59)","query_processor.context$executef.invoke(context.clj:48)","query_processor.context.default$default_runf.invokeStatic(default.clj:69)","query_processor.context.default$default_runf.invoke(default.clj:67)","query_processor.context$runf.invokeStatic(context.clj:45)","query_processor.context$runf.invoke(context.clj:39)","query_processor.reducible$pivot.invokeStatic(reducible.clj:34)","query_processor.reducible$pivot.invoke(reducible.clj:31)","query_processor.middleware.mbql_to_native$mbql__GT_native$fn__46221.invoke(mbql_to_native.clj:26)","query_processor.middleware.check_features$check_features$fn__45497.invoke(check_features.clj:42)","query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__46386.invoke(optimize_datetime_filters.clj:133)","query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__44298.invoke(auto_parse_filter_values.clj:44)","query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__39953.invoke(wrap_value_literals.clj:149)","query_processor.middleware.annotate$add_column_info$fn__39816.invoke(annotate.clj:575)","query_processor.middleware.permissions$check_query_permissions$fn__45372.invoke(permissions.clj:70)","query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__46904.invoke(pre_alias_aggregations.clj:40)","query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__45570.invoke(cumulative_aggregations.clj:61)","query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47141.invoke(resolve_joined_fields.clj:36)","query_processor.middleware.resolve_joins$resolve_joins$fn__47460.invoke(resolve_joins.clj:183)","query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__43896.invoke(add_implicit_joins.clj:254)","query_processor.middleware.large_int_id$convert_id_to_string$fn__46182.invoke(large_int_id.clj:44)","query_processor.middleware.limit$limit$fn__46207.invoke(limit.clj:38)","query_processor.middleware.format_rows$format_rows$fn__46162.invoke(format_rows.clj:75)","query_processor.middleware.desugar$desugar$fn__45636.invoke(desugar.clj:22)","query_processor.middleware.binning$update_binning_strategy$fn__44657.invoke(binning.clj:229)","query_processor.middleware.resolve_fields$resolve_fields$fn__45174.invoke(resolve_fields.clj:24)","query_processor.middleware.add_dimension_projections$add_remapping$fn__43444.invoke(add_dimension_projections.clj:316)","query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__43647.invoke(add_implicit_clauses.clj:141)","query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44045.invoke(add_source_metadata.clj:105)","query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__47101.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)","query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__44245.invoke(auto_bucket_datetimes.clj:140)","query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45221.invoke(resolve_source_table.clj:46)","query_processor.middleware.parameters$substitute_parameters$fn__46886.invoke(parameters.clj:114)","query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45273.invoke(resolve_referenced.clj:80)","query_processor.middleware.expand_macros$expand_macros$fn__45892.invoke(expand_macros.clj:158)","query_processor.middleware.add_timezone_info$add_timezone_info$fn__44054.invoke(add_timezone_info.clj:15)","query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47822.invoke(splice_params_in_response.clj:32)","query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47112$fn__47116.invoke(resolve_database_and_driver.clj:33)","driver$do_with_driver.invokeStatic(driver.clj:61)","driver$do_with_driver.invoke(driver.clj:57)","query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47112.invoke(resolve_database_and_driver.clj:27)","query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46110.invoke(fetch_source_query.clj:267)","query_processor.middleware.store$initialize_store$fn__47831$fn__47832.invoke(store.clj:11)","query_processor.store$do_with_store.invokeStatic(store.clj:46)","query_processor.store$do_with_store.invoke(store.clj:40)","query_processor.middleware.store$initialize_store$fn__47831.invoke(store.clj:10)","query_processor.middleware.cache$maybe_return_cached_results$fn__45150.invoke(cache.clj:214)","query_processor.middleware.validate$validate_query$fn__47840.invoke(validate.clj:10)","query_processor.middleware.normalize_query$normalize$fn__46234.invoke(normalize_query.clj:22)","query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__43914.invoke(add_rows_truncated.clj:36)","query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47807.invoke(results_metadata.clj:147)","query_processor.middleware.constraints$add_default_userland_constraints$fn__45513.invoke(constraints.clj:42)","query_processor.middleware.process_userland_query$process_userland_query$fn__46975.invoke(process_userland_query.clj:136)","query_processor.middleware.catch_exceptions$catch_exceptions$fn__45456.invoke(catch_exceptions.clj:174)","query_processor.reducible$async_qp$qp_STAR___36611$thunk__36612.invoke(reducible.clj:103)","query_processor.reducible$async_qp$qp_STAR___36611.invoke(reducible.clj:109)","query_processor.reducible$sync_qp$qp_STAR___36620$fn__36623.invoke(reducible.clj:135)","query_processor.reducible$sync_qp$qp_STAR___36620.invoke(reducible.clj:134)","query_processor$process_userland_query.invokeStatic(query_processor.clj:238)","query_processor$process_userland_query.doInvoke(query_processor.clj:234)","query_processor$fn__47886$process_query_and_save_execution_BANG___47895$fn__47898.invoke(query_processor.clj:250)","query_processor$fn__47886$process_query_and_save_execution_BANG___47895.invoke(query_processor.clj:242)","query_processor$fn__47930$process_query_and_save_with_max_results_constraints_BANG___47939$fn__47942.invoke(query_processor.clj:262)","query_processor$fn__47930$process_query_and_save_with_max_results_constraints_BANG___47939.invoke(query_processor.clj:255)","api.dataset$fn__49120$fn__49123.invoke(dataset.clj:59)","query_processor.streaming$streaming_response_STAR_$fn__49101$fn__49102.invoke(streaming.clj:73)","query_processor.streaming$streaming_response_STAR_$fn__49101.invoke(streaming.clj:72)","async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)","async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)","async.streaming_response$do_f_async$fn__24641.invoke(streaming_response.clj:85)"]
```

**To Reproduce**
Create a saved question with the sample dataset --  "Orders" with no filtering or aggregation
Go to the Native SQL editor on the same database  with the following query

```
with any_question as ({{#1684}})

select * from any_question
[[where title like '%{{substr}}%']]
```

enter any value for the substr parameter and you'll get an error.

**Information about your Metabase Installation:**

- Your browser and the version: Chrome Version 87.0.4280.88 (Official Build) (x86_64)
- Your operating system: Beanstalk running the default docker image
- Your databases: H2 + PG are both affected 
- Metabase version: (e.x. latestv0.39.0-SNAPSHOT)
- Metabase hosting environment:  Elastic Beanstalk
- Metabase internal database: Postgres

**Severity**
Pretty annoying. Not show-stopping but prevented a pretty compelling demo to the team ;)

**Comment by flamber** [comment] 2020-12-26 11:08
The variable gets quoted to protect against injections, but this would work:
`like '%'||{{substr}}||'%'` or `like concat('%',{{substr}},'%')`
Duplicate of #5231

**Closed by flamber** 2020-12-26 11:08 UTC
Labels: Priority:P2, Querying/Native, Querying/Nested Queries, Type:Bug

**Comment by salsakran** [comment] 2020-12-28 22:51
aahhhh. Thanks @flamber !
