### ISSUE TITLE
Database settings aren't included in GET "/api/database" response, regardless of their visibility

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#28149] opened 2023-02-08 16:11 UTC
Settings defined with `defsetting` have a "visibility" that determines whether a user can read from .

However, database-local settings aren't included in the response of the GET "api/database" or GET "api/database/:id" endpoints, regardless of their visibility. This means the FE doesn't know about the value of settings like `database-enable-actions`.

## More context

From the `defsetting` docstring:
```
    Visibility       | Who Can See It?              | Who Can Update It?
    ---------------- | ---------------------------- | --------------------
    :public          | The entire world             | Admins and Settings Managers
    :authenticated   | Logged-in Users              | Admins and Settings Managers
    :settings-manager| Admins and Settings Managers | Admins and Settings Managers
    :admin           | Admins                       | Admins
    :internal        | Nobody                       | No one (usually for env-var-only settings)
```

When the FE makes a request with GET "api/setting" or GET "/api/session/properties", the response includes a map of settings that are filtered based on the `visibility` rules above. 

However, database local settings like `database-enable-actions` or `max-results-bare-rows` are not returned with the database information as we would expect at GET "api/database" or GET "api/database/:id". This is because the settings are explicitly removed when encoding database instances to JSON.

Removing settings when encoding database instances was done by @camsaul way back [here](https://github.com/metabase/metabase/pull/19399/commits/59cde8b4e7080519a5ece4767e75441e9ee958f5#diff-08f05088ade450091841832831efb413eb5204f0cd7eb1f253d5dfb9f7b50dc7R265). I suspect the reason was to keep the PR small and to be conservative about setting visibility, because there was no need for the FE to read any database settings. All database settings until this point have only affected the query processor, so their values were not needed on the FE.

## Why do we need this now?

The FE needs to only show the “Actions” tab on the model detail page if actions are enabled for the database of the model. So the value of the `database-enable-actions` setting is needed in the response to GET "api/database" and GET "api/database/:id".

**Comment by camsaul** [comment] 2023-02-08 16:54
Duplicate of #22683 ?

**Comment by calherries** [comment] 2023-02-08 18:16
Yes, closing as it's a duplicate

**Closed** 2023-02-08 18:17 UTC
Labels: .Backend
