### ISSUE TITLE
Supporting JPEG and images in general

### ISSUE THREAD

**Issue by FrostKiwi** [metabase/metabase#23097] opened 2022-06-02 01:50 UTC
**Is your feature request related to a problem? Please describe.**
I'm interested in using Metabase to sift through sensor data, which is a use-case mentioned from time to time  https://github.com/metabase/metabase/issues/2680#issuecomment-222239921
For me, this includes small grayscale JPEGs being saved as raw binary BLOBs into an SQLite database. I am interested in visualizing that. This may combine well with the use-case of visualizing datasets used for training neural networks.

**Describe the solution you'd like**
I care about two features.
Being able to generate basic statistics of said image and display it as a chart along side other visualizations. Like combining the column 'power draw' with 'Average brightness' pulled from an image.
More over, when hovering over a datapoint in a visualization it would be excellent, if the image of said database row would be displayed as a floating thumbnail.

**Describe alternatives you've considered**
I am able to connect to the database via R, read out the BLOB column, decode the images, perform any needed image statistics and write this information back into a new column. Then I can use Metabase to display information of such column. In my specific use case I generate a column 'count of pixels above value 128 in a circular region in the middle' and use Metabase to combine that with a chart from the column 'power draw'.
Being able to do basic variations of image analysis within Metabase itself would be quite the feature boost.

**How important is this feature to you?**
Image analysis is the core of my work and I'm constantly looking for new ways of presenting what I do. I think Metabase might be a good fit for that, so I think it is quite the important feature to me.

**Additional context**
I thought my approach of saving raw jpegs into a database was fairly niche, but I am pleasantly surprised, that this is not the case. Some database tools support jpeg files as a database entry. For instance the the "DB Browser for SQLite" supports displaying, importing and exporting of those files.
![grafik](https://user-images.githubusercontent.com/60887273/171527989-1f9185ff-d90d-4360-a724-5ddf0db2b98d.png)
Besides that any data analysis package does the same. For instance R, which can connect to a database, decode JPEG and do more sophisticated image analysis.

I am fully aware, that this feature request is fairly outside of Metabase's target audience and the amount of potential users of such a feature may not justify the mountain of work such an implementation brings. Still, I would like proposal to exist.

**Comment by flamber** [comment] 2022-06-02 07:52
Duplicate of #12922

**Closed by flamber** 2022-06-02 07:52 UTC
Labels: Type:New Feature, .Needs Triage
