### ISSUE TITLE
Grid map requires binned longitude/latitude 

### ISSUE THREAD

**Issue by psrawke** [metabase/metabase#8551] opened 2018-09-19 07:36 UTC
I am grouping the data by the integer values of latitude and longitude. I am able to plot the **Pin Map**, but **Grid Map** shows the `Grid map requires binned longitude/latitude.` error.

Can you share some **sample binned latitude-longitude (which is compatible with metabase)**, so that I can convert my latitude-longitude data into that format?

My query is something like this: 
```
SELECT  CAST(latitude AS INTEGER) latitude, CAST(longitude AS INTEGER) longitude, COUNT(*)
FROM location_table
GROUP BY CAST(latitude AS INTEGER), CAST(longitude AS INTEGER) 
LIMIT 20
```

The data returned by the Query is of the following form:

| latitude | longitude | count | 
| - | - | - |
| 22 | 69 | 1 |
| 13| 76| 6 |
| 21| 84| 3 |
| 20| 82| 1 |
| 17| 77| 1 |

_Originally posted by @psrawke in https://github.com/metabase/metabase/issues/8362#issuecomment-422665075_

**Comment by jornh** [comment] 2018-09-19 16:13
The `People` table part of the Sample Dataset that (you can) install together with Metabase when spinning up a (new) instance - is such a dataset:

![image](https://user-images.githubusercontent.com/766423/45765826-4c59a780-bc36-11e8-80eb-5450b539c527.png)

Also, I think I would just use the GUI custom queries in place of a raw SQL question. Metabase can then take data type hints (e.g. knowing something is lan/lon) set through the admin interface.

In general - a better place for asking questions is the Metabase Discourse forum: http://discourse.metabase.com/ ... the core development team has more than enough to do to try keeping up with enhancement requests and bug reports here on GitHub.

**Comment by salsakran** [comment] 2018-12-28 03:47
@tlrobinson am I reading this correctly - given that we have a specific return format for binned results in the query builder, it isn't easily possible to use grid maps for native queries?

**Comment by flamber** [comment] 2019-01-31 13:23
This is either a forum question or a duplicate of #8362

**Comment by flamber** [comment] 2020-05-25 13:21
Closing in favor of #8362

**Closed by flamber** 2020-05-25 13:21 UTC
Labels: Priority:P2, Type:Bug, Visualization/

**Comment by sdekna** [comment] 2023-02-23 03:10
If anyone is still having this issue.
Go to admin settings > databases > then choose database, then enable `Periodically refingerprint tables`.
Then Data Model > go to your table and change type of the fields to `latitude` and `longitude` respectively.
Then on each of the fields, click on the settings icon to its right, then `Discard cached field values` and `Re-scan this field`.
Now should be working properly.

**Comment by zell180** [comment] 2023-06-20 10:53
I have this issue on Sample Dataset and on my dataset too and i can't fix
