### ISSUE TITLE
"Download this data" Feature Exports Data Only Based on Default Values 

### ISSUE THREAD

**Issue by sandeepkini** [metabase/metabase#3857] opened 2016-12-02 21:59 UTC
### Bugs

- Your browser and the version: Chrome Version 54.0.2840.98 
- Your operating system: OS Sierra 10.12 
- Your databases: Postgres
- Metabase version:  v0.20.3
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres 9.4.5

I wrote a query and made the default values for the start and end date to be a November 1, 2015 and November 30, 2016, resulting in about 1000 rows of data. When I changed the dates in the variable input area right above the SQL query box, to the past 6 months, the resulting query then has 500 rows. 

However, when I download the data, the data download is not the 500 rows from the past 6 months. Instead it is the 1000 rows, which is based off of the default values. 

It can sometimes be difficult to explain to end users to change the default values of variables in addition to the values of variables above the SQL box. 

My ask is that the data downloads be based off of the values selected in the variable entry above the SQL query box.

**Comment by camsaul** [comment] 2016-12-02 22:05
@sandeepkini a fix for this will be shipping with our upcoming 0.21.0 release.

Closing as duplicate of #3695 / #3704

**Closed by camsaul** 2016-12-02 22:05 UTC
Labels: Bug, Duplicate
