### ISSUE TITLE
PostgreSQL time is different when running the same query

### ISSUE THREAD

**Issue by beanaroo** [metabase/metabase#19258] opened 2021-12-07 23:11 UTC
**Describe the bug**
When querying `current_time` or `localtime`, the result can be different. Rerunning the same query produces different results.

It looks like it will use either Report Time Zone or Browser Time Zone.

**Logs**
_No log output on backend or frontend when executing query_

**To Reproduce**
1. Go to 'Write SQL'
2. Select Database
3. Enter query: 
   ```sql
   select current_setting('TIMEZONE') as TIMEZONE, current_timestamp, current_date, current_time, localtime, now();
   ```
4. Click 'Run Selected Text'
5. Repeat

**Expected behavior**
Consistent results

**Screenshots**

https://user-images.githubusercontent.com/1748909/145118727-878467c2-e480-4fc0-8d4e-c2cca45a8842.mp4

**Information about your Metabase Installation:**

- Reproduced on Firefox and Chrome
- Browser TZ: `Pacific/Auckland`
- Database TZ: `UTC`
- Metabase Host TZ: `UTC`
- Metabase Report TZ: `UTC`

<details>
  <summary>Diagnostic Info</summary>

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "4.14.192-147.314.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.9 (Debian 12.9-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-12-02",
      "tag": "v0.41.3.1",
      "branch": "release-x.41.x",
      "hash": "20f9097"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

</details>

**Severity**
This is concerning to us and makes us doubt the results of produced reports.

**Additional context**
- We have read through https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html

**Comment by flamber** [comment] 2021-12-08 09:20
Duplicate of #15876

**Closed by flamber** 2021-12-08 09:20 UTC
Labels: Type:Bug, .Needs Triage
