### ISSUE TITLE
Postgres date fields displaying as timestamps

### ISSUE THREAD

**Issue by arcreative** [metabase/metabase#11321] opened 2019-11-14 19:46 UTC
**Describe the bug**
Date fields display as `December 1, 2019 12:00 AM` despite not having time information.

**To Reproduce**
1. Open any table of data either in main interface or embeds

**Expected behavior**
Date fields should display as `December 1, 2019`

**Screenshots**

In schema:
![Screen Shot 2019-11-14 at 11 44 30 AM](https://user-images.githubusercontent.com/1896026/68890637-27df4b00-06d4-11ea-8421-e0db4c431f6c.png)

In Data:
![Screen Shot 2019-11-14 at 11 40 38 AM](https://user-images.githubusercontent.com/1896026/68890465-cdde8580-06d3-11ea-8301-1a44f4f2906c.png)

In metabase:
![Screen Shot 2019-11-14 at 11 40 23 AM](https://user-images.githubusercontent.com/1896026/68890460-c9b26800-06d3-11ea-9037-534c28b5e6af.png)

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.4+11-post-Ubuntu-1ubuntu218.04.3",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.4",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.4+11-post-Ubuntu-1ubuntu218.04.3",
    "os.name": "Linux",
    "os.version": "4.15.0-1054-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-11-13",
      "tag": "v0.33.5.1",
      "branch": "release-0.33.x",
      "hash": "26159d2"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
It's a minor annoyance in some places, but the overall inconsistency of some dates being displayed as JSON zulu time, others being dates, and still more being times is really grating after a while.  If converted to varchar, exported CSVs don't have the ability to parse, and thus intelligently filter the output.

**Comment by flamber** [comment] 2019-11-14 20:03
Hi @arcreative 
This is a general issue, not specific to Postgres, if I understand you correctly.
It sounds very similar to #10944 and #10879 - if you think it might be a duplicate of those, then please close this and upvote the other issue :+1:

**Comment by arcreative** [comment] 2019-11-15 03:13
@flamber Thanks, I think #10879 is somewhat relevant from the CSV perspective, but I'm not sure I think this is entirely related to #10944 because that seems to be more in the context of the special field types and not general field types.  I know it's a bear, but I think that in general, the rendering format of different datatypes on the frontend should have some sort of mapping to its respective data type.  An added bonus would be having the ability to customize it in the data model, and a double bonus would be the ability to override it on a particular question, although I think that's almost certainly overkill for most use cases.

**Comment by flamber** [comment] 2019-11-15 03:41
@arcreative 
I'm not sure I understand. What is it that this issue covers that is not covered in the two referenced?
The Data Model is for mapping to the database type. In most cases, this is done automatically, when the database is sync'ed. In some cases it's done manually. And you can adjust formatting there too. It currently also shows time for `Date` types by default, which is what #10944 covers.
For questions, you can change formatting by clicking visualization Settings > Column > (column) :gear:

**Comment by flamber** [comment] 2019-11-27 17:59
Actually this is probably a duplicate of #5859 or #7494

**Closed** 2019-12-13 23:35 UTC
Labels: .Duplicate
