### ISSUE TITLE
Unbinned geo mapping defaults to Grid instead of Pins

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#10734] opened 2019-08-27 21:06 UTC
Sample dataset; Orders grouped by Users/long, Users/lat, both unbinned, then it defaults to Grid map and errors:
`Grid map requires binned longitude/latitude.`

1. ![image](https://user-images.githubusercontent.com/1447303/141643814-7b4f8927-dded-4c7b-a7b3-9254e123e2e7.png)
2. ![image](https://user-images.githubusercontent.com/1447303/141643818-37d6f142-1ac6-4f57-ad16-294f79bff7c4.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2020-05-30 10:29
Update on 0.35.4:
1. Errors with `Grid map requires binned longitude/latitude.`, because it defaults to Grid, like you say
![image](https://user-images.githubusercontent.com/1447303/83325903-45d75c00-a270-11ea-8faa-51e15933ba71.png)
2. Duplicate of #9421

**Closed** 2024-06-26 16:03 UTC
Labels: Type:Bug, Priority:P2, Visualization/Maps, .Team/DashViz
