### ISSUE TITLE
adding filters to dashboards has weird AF spacing

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#6380] opened 2017-11-14 02:14 UTC
On 0.27.0-SNAPSHOT (`master`) on Chrome 61 which is the latest as well as Firefox "Quantum" 57.0. Seems to me like the Done button is trying to hide from me. Oh yeah also the entire nav bar at the top is gone so there's a no vertical padding before the "Select the field..." text. There are lots of warnings in the console but I'm not sure if any of them are related so I will avoid spamming with them here

![screen shot 2017-11-13 at 6 08 07 pm](https://user-images.githubusercontent.com/1455846/32759373-fc5a3c9a-c89d-11e7-8394-c24ef6b14df7.png)

![screen shot 2017-11-13 at 6 10 35 pm](https://user-images.githubusercontent.com/1455846/32759368-f939637e-c89d-11e7-9a1d-f14692a11f3d.png)

I believe this is a regression in 0.27.0

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by mazameli** [comment] 2017-11-14 05:04
Gonna call this a dupe of https://github.com/metabase/metabase/issues/6188

**Closed by mazameli** 2017-11-14 05:04 UTC
Labels: Bug, Dashboards, Duplicate
