### ISSUE TITLE
Wrong link on "Getting set up" page

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4298] opened 2017-02-02 08:13 UTC
Metabase 0.22.1

![image](https://cloud.githubusercontent.com/assets/1708680/22541637/9810b7c2-e938-11e6-9a12-d24117a720bf.png)

**Comment by mazameli** [comment] 2017-02-02 17:07
Dupe of #4260, thanks.

**Closed by mazameli** 2017-02-02 17:07 UTC
Labels: Duplicate
