### ISSUE TITLE
Turkish character problem.

### ISSUE THREAD

**Issue by yunusdgntr** [metabase/metabase#8518] opened 2018-09-14 08:33 UTC
We were not able to open the application(v0.30.3) because of the Turkish character issues below in the picture.
![image](https://user-images.githubusercontent.com/22774511/45539180-a19a5100-b811-11e8-9373-74f5de61e3f2.png)

**Comment by jornh** [comment] 2018-09-19 20:49
To help others help please provide info on your environment as requested by the issue template: 
https://github.com/metabase/metabase/issues/new

In addition other relevant info for this particular case is what locale settings you have for Java - and maybe the Metabase application database.

I general your issue all reminds me of this (long) topic: 
http://discourse.metabase.com/t/metabase-centos-install-error-please-help-turkish-locale/2943/ 
Maybe it or the liquibase links it ended with pointers to possible workarounds?

**Comment by jornh** [comment] 2018-10-02 09:34
Duplicate of #8565

Turns out #8565 has better info than #8518 - lets point to this. Please vote over there and close this issue.

Thanks! 🙂

**Closed** 2018-10-03 04:32 UTC
