### ISSUE TITLE
Table doesn't sync if a JSON field has the same name as a column, with JSON unfolding on

### ISSUE THREAD

**Issue by dustinblanchard** [metabase/metabase#44188] opened 2024-06-14 01:38 UTC
**Describe the bug**
We currently use pgvector (https://github.com/pgvector/pgvector) in our postgres database, adding the fields `vector` and `aggregated_vector` to several tables, along with the HNSW indexes. I've noticed that these tables are not importing their fields schema at all, while our other tables are loading fine  There's a lot of errors logged like the ones below.

I'm guessing we just need a way to exclude/ignore the vector fields and their indexes from the schema import.

**Logs**
Linked as they are too long for github issues
https://docs.google.com/document/d/1KPBglnkIitEEELmtk4bg2agn2add7fgrBKx6wfNybr8/edit?usp=sharing

**To Reproduce**
1. Set up Metabase
2. Set up a postgres database with pgvector
3. Add `vector` fields and include calculated vectors.
4. Connect database to metabase.

**Expected behavior**
Tables should import correctly for use in metabase

**Severity**
This is entirely blocking our metabase usage as the vectorized tables are critical for our use case.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "4.4.0",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.17"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-13",
      "tag": "v0.50.3",
      "hash": "855535b"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```

**Comment by calherries** [comment] 2024-06-14 20:13
@dustinblanchard I tested pgvector 0.7.2 with version 50.3, and the table metadata sync works just fine. This is what I did to set up a table before syncing it:

```
CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE items (id bigserial PRIMARY KEY, embedding vector(3));
INSERT INTO items (embedding) VALUES ('[1,2,3]'), ('[4,5,6]');
CREATE INDEX items_embedding_idx ON items USING hnsw (embedding vector_l2_ops);
```

Can you confirm you can create such a table and sync its metadata with Metabase correctly?

In the logs you attached, I notice Metabase is picking up two instances of a column name "vector":
```
Error checking if Fields ("vector" "aggregate_vector" "vector" "ai_processing_status" "name" "pg_vector" "vector_uuid" "id" "pg_aggregate_vector") need to be created or reactivated
```
Metabase doesn't allow syncing tables with duplicate column names for obvious reasons: there's no way to disambiguate them. So, can you help explain why Metabase might be picking up on two "vector" columns in the same table? Maybe there's something to the table beyond what I've demonstrated above.

**Comment by dustinblanchard** [comment] 2024-06-14 20:53
That is extremely strange as we don't have any tables with two columns named "vector", and this seems to be happening on all models where the vector fields are present. 

Is there anything else that could cause metabase to load in a column name that doesn't explicitly exist like that?

**Comment by calherries** [comment] 2024-06-15 00:51
Okay thanks, I've had a closer look again at your stack trace and I see now that you have a column called "vector" with a JSONB type and JSON unfolding is enabled on that field. When JSON unfolding is enabled Metabase considers each field inside the JSON values as a separate column. And it looks like we've detected a field _inside_ the JSONB column called "vector", which we're pulling out and trying to make a separate column out of. This is indeed a thorny edge-case with JSON unfolding, and we'll fix that. 

But for your case, if you can get away with turning off JSON unfolding, it should fix your issue. There are two workarounds you can try: either (a) disable JSON unfolding for the database, or (b) disable JSON unfolding for each table. [The docs](https://www.metabase.com/docs/latest/data-modeling/json-unfolding#toggling-json-unfolding-for-a-database) on working with JSON might be helpful.

**Comment by dustinblanchard** [comment] 2024-06-15 03:50
Thank you! Disabling Unfolding did the trick! Sorry for the initial false assumption about the cause.

**Comment by qnkhuat** [comment] 2024-06-21 03:55
@calherries do you think this is the same bug as https://github.com/metabase/metabase/issues/44459 ?

**Comment by calherries** [comment] 2024-06-21 16:36
Yeah good spotting, Dustin's issue was created by the fact that there was a value in a JSON array that had the name "vector". But it's still possible for a JSON field to have the same name as a column, and to cause the same error.

**Comment by calherries** [comment] 2024-07-09 00:15
> But it's still possible for a JSON field to have the same name as a column, and to cause the same error. 

Actually, I assumed wrong. I just tested this exact case and it's so unlikely I think we can just ignore it for now. A JSON field has a `:name` value that has arrows in it mimicking the path, e.g. "a → b". Because of these arrows it seems unlikely that there will be a top-level column with the same name.

**Comment by calherries** [comment] 2024-07-09 00:16
Closing this because the original issue is solved. It's a dupe of https://github.com/metabase/metabase/issues/44459

**Closed by calherries** 2024-07-09 00:16 UTC
Labels: Type:Bug, Priority:P2, Database/Postgres, Administration/Metadata & Sync, .Backend, .Team/BackendComponents
