### ISSUE TITLE
If you don't have permission to tables used in a question's filter/breakout clauses, things get weird

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5064] opened 2017-05-10 19:42 UTC
Not sure if this is a 0.24 regression or not, but this was viewed on 0.24-rc5 on Chrome.

**Question definition**

<img width="1397" alt="screen shot 2017-05-10 at 12 39 36 pm" src="https://cloud.githubusercontent.com/assets/2223916/25917702/d2608c2c-357d-11e7-88aa-d9c331ba1bc9.png">

**When viewed by a user who only has access to Orders table, not to Pie or Users tables**

![screen shot 2017-05-10 at 12 39 34 pm](https://cloud.githubusercontent.com/assets/2223916/25917721/e783a5bc-357d-11e7-9622-cd628a2ddaa1.png)

**Permissions**

<img width="1397" alt="screen shot 2017-05-10 at 12 37 56 pm" src="https://cloud.githubusercontent.com/assets/2223916/25917739/f718e62c-357d-11e7-9e4e-844f1206a6f8.png">

**JS errors for that user when trying to view the chart**

![screen shot 2017-05-10 at 12 36 55 pm](https://cloud.githubusercontent.com/assets/2223916/25917754/006512c8-357e-11e7-8d65-d3dfa07eff2e.png)

What do we think the UX should be in this case? Filter(s) and breakout(s) are visible but unalterable?

**Comment by tlrobinson** [comment] 2017-05-10 20:19
I don't think the user should be able to view that quesiton at all, should they?

**Comment by salsakran** [comment] 2017-05-10 20:20
yeah, drill-through or actions shouldn't take you to questions you don't have permissions to see.

**Comment by salsakran** [comment] 2017-05-10 20:22
I think at one point we decided that if you didn't have all the self-server data access permissions for the entire question, you shouldn't be able to see it

**Comment by attekei** [comment] 2017-05-15 18:11
I was able to reproduce this only when a question is inside a collection, and when that collection is visible to a user group. If the question isn't in any collection, then I correctly saw the "Sorry, you don’t have permission to see that." error state.

Haven't checked yet whether fixing this would involve modifications in backend, frontend or both.

**Comment by attekei** [comment] 2017-05-15 21:00
Seems this requires only a backend change: currently in [`perms-objects-set`](https://github.com/metabase/metabase/blob/d868b9b786bcf687e699ea74718172037330d53d/src/metabase/models/card.clj#L78) of card model the collection permissions completely override the query permissions if the question belongs to a collection. The method should probably merge those two (collection permissions + query permissions) instead.

**Comment by camsaul** [comment] 2017-05-15 21:02
A required permissions set means you have to have permissions for *everything* in that set. For example, a question that refers to two tables would require permissions for *both* of those tables. So combining the two permissions sets would mean you'd require permissions for both the collection and the normal things like the tables referenced, which is probably not what we want either.

**Comment by flamber** [comment] 2020-05-25 19:44
This was probably fixed in 0.30 as part of the Collection permissions. I cannot reproduce on 0.35.3

**Closed by flamber** 2020-05-25 19:44 UTC
Labels: Administration/Permissions, Query Builder, Type:Bug
