### ISSUE TITLE
BE - Migrate `card.dataset` to `card.type`

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#38709] opened 2024-02-13 12:57 UTC

**Comment by camsaul** [comment] 2024-02-13 19:35
How is this different from #37367?

**Comment by camsaul** [comment] 2024-02-13 19:36
Actually in #38074 I find it extremely worrisome that there were no MLv2 changes at all... I hope nothing broke as a result

**Comment by camsaul** [comment] 2024-02-13 19:44
Closing as duplicate of #37367

**Closed by camsaul** 2024-02-13 19:44 UTC
Labels: .Backend, .Team/QueryProcessor
