### ISSUE TITLE
Select All / Unselect all checkbox missing in table fields view

### ISSUE THREAD

**Issue by Lebrero-CETEIN** [metabase/metabase#5494] opened 2017-07-17 21:38 UTC
When I'm selecting which fields I like to view in a question, always search unsuccsessfully for any checkbox that allow me to select or unselect all the fields (to select a few fields to show in a query). I manage very large tables and uncheck fieldd one by one is annoying and time-consumming.  

May be this will be a very usefull feature to help users to build questions faster and in a more user-frendly  way. 

Thanks a lot!!  Metabase is a very nice application, congrats!

Alejandro.

**Comment by camsaul** [comment] 2017-07-17 21:38
Wasn't this implemented in #4436?

**Comment by camsaul** [comment] 2017-07-17 21:54
Oops. I guess that's not merged. Either way this is a duplicate of #3951

**Closed by camsaul** 2017-07-17 21:54 UTC
