### ISSUE TITLE
Cannot apply filter to number columns in question/notebook from saved sql question.

### ISSUE THREAD

**Issue by dannydnz** [metabase/metabase#16172] opened 2021-05-20 21:31 UTC
**Describe the bug**
Cannot apply filter to number columns in question/notebook from saved sql question.

String field filters can be applied.

**Logs**

JS Logs

````
app-main.bundle.js?9…74feab3bbb496e6f0:5 Warning: can't clean query without metadata!
value	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
value	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
value	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
(anonymous)	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
(anonymous)	@	vendor.bundle.js?98974fe…:19
(anonymous)	@	vendor.bundle.js?98974fe…:19
(anonymous)	@	vendor.bundle.js?98974fe…:19
(anonymous)	@	vendor.bundle.js?98974fe…:19
(anonymous)	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
i	@	vendor.bundle.js?989…feab3bbb496e6f0:434
(anonymous)	@	vendor.bundle.js?989…feab3bbb496e6f0:495
p	@	vendor.bundle.js?989…feab3bbb496e6f0:495
(anonymous)	@	vendor.bundle.js?989…feab3bbb496e6f0:495
run	@	vendor.bundle.js?989…feab3bbb496e6f0:434
c.componentWillReceiveProps	@	vendor.bundle.js?989…feab3bbb496e6f0:434
bo	@	vendor.bundle.js?989…feab3bbb496e6f0:487
Ia	@	vendor.bundle.js?989…feab3bbb496e6f0:487
vs	@	vendor.bundle.js?989…feab3bbb496e6f0:487
vu	@	vendor.bundle.js?989…feab3bbb496e6f0:487
gu	@	vendor.bundle.js?989…feab3bbb496e6f0:487
uu	@	vendor.bundle.js?989…feab3bbb496e6f0:487
(anonymous)	@	vendor.bundle.js?989…feab3bbb496e6f0:487
t.unstable_runWithPriority	@	vendor.bundle.js?989…feab3bbb496e6f0:495
Wi	@	vendor.bundle.js?989…feab3bbb496e6f0:487
Vi	@	vendor.bundle.js?989…feab3bbb496e6f0:487
Ui	@	vendor.bundle.js?989…feab3bbb496e6f0:487
iu	@	vendor.bundle.js?989…feab3bbb496e6f0:487
enqueueSetState	@	vendor.bundle.js?989…feab3bbb496e6f0:487
b.setState	@	vendor.bundle.js?989…feab3bbb496e6f0:448
c.onStateChange	@	vendor.bundle.js?989…feab3bbb496e6f0:434
Promise.then (async)		
r	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
(anonymous)	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
(anonymous)	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
(anonymous)	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
(anonymous)	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
(anonymous)	@	vendor.bundle.js?989…feab3bbb496e6f0:495
(anonymous)	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
(anonymous)	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
l	@	vendor.bundle.js?98974fe…:98
(anonymous)	@	vendor.bundle.js?98974fe…:98
(anonymous)	@	vendor.bundle.js?98974fe…:98
r	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
(anonymous)	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
Promise.then (async)		
r	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
(anonymous)	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
(anonymous)	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
(anonymous)	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
(anonymous)	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
l	@	vendor.bundle.js?98974fe…:98
(anonymous)	@	vendor.bundle.js?98974fe…:98
(anonymous)	@	vendor.bundle.js?98974fe…:98
r	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
(anonymous)	@	app-main.bundle.js?9…74feab3bbb496e6f0:5
Show 53 more frames
````

**To Reproduce**
1. Goto Ask a question
2. Select Custom question
3. Select a Saved sql question
4. Filter by a number field.
5. Add filter button is disable. Unable to apply the filter.

**Expected behavior**
After entering a valid number the Add Filter button should be enabled.

**Screenshots**
![Screen Shot 2021-05-21 at 9 17 30 AM](https://user-images.githubusercontent.com/13537902/119050287-c1985e80-ba15-11eb-9bf3-57a7398a9266.png)

![Screen Shot 2021-05-21 at 9 17 38 AM](https://user-images.githubusercontent.com/13537902/119050211-a3326300-ba15-11eb-8cc0-3a9165379daf.png)

**Information about your Metabase Installation:**

````json
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "5.4.0-1045-aws",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.25"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-17",
      "tag": "v0.39.2",
      "branch": "release-x.39.x",
      "hash": "b0d9436"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
````
Running as a docker container.

**Severity**
A lot of our uses are unable to generate reports. Priority 1 in my view.

**Comment by flamber** [comment] 2021-05-22 09:10
@dannydnz This is the same root cause as #15725, which is fixed and will be part of 0.39.3

**Closed by flamber** 2021-05-22 09:10 UTC
Labels: .Needs Triage, Type:Bug
