### ISSUE TITLE
This page is not working / system completely shut down

### ISSUE THREAD

**Issue by boranb** [metabase/metabase#38028] opened 2024-01-23 06:49 UTC
### Describe the bug

When I change some settings in the admin panel, I suddenly get the This page is not working error. What I did was press the custom home button a few times

same problem here: https://github.com/metabase/metabase/issues/37161

![image](https://github.com/metabase/metabase/assets/61060561/9eb769fb-030b-461f-819e-fd3b8f52134f)

### To Reproduce

1. go to admin panel
2. Go to the custom home page screen
3. press toggle button and press again

### Expected behavior
The admin panel freezes and when I refresh the page, I cannot access the web page again.

### Logs

Diagnostic Info:

{
"browser-info": {
"language": "tr-TR",
"platform": "Win32",
"userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
"vendor": "Google Inc."
},
"system-info": {
"file.encoding": "UTF-8",
"java.runtime.name": "OpenJDK Runtime Environment",
"java.runtime.version": "11.0.20.1+1-post-Ubuntu-0ubuntu122.04",
"java.vendor": "Ubuntu",
"java.vendor.url": "https://ubuntu.com/",
"java.version": "11.0.20.1",
"java.vm.name": "OpenJDK 64-Bit Server VM",
"java.vm.version": "11.0.20.1+1-post-Ubuntu-0ubuntu122.04",
"os.name": "Linux",
"os.version": "5.15.0-89-generic",
"user.language": "en",
"user.timezone": "Europe/Istanbul"
},
"metabase-info": {
"databases": [
"postgres",
"sqlserver"
],
"hosting-env": "unknown",
"application-database": "postgres",
"application-database-details": {
"database": {
"name": "PostgreSQL",
"version": "14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)"
},
"jdbc-driver": {
"name": "PostgreSQL JDBC Driver",
"version": "42.6.0"
}
},
"run-mode": "prod",
"version": {
"date": "2023-12-19",
"tag": "v0.48.1",
"hash": "a8302d4"
},
"settings": {
"report-timezone": "Turkey"
}
}
}

### Information about your Metabase installation

```JSON
Browser:		117.0.5938.132 64x
Database:		Mssql,Postgresql
Metabase version:	v0.48
Operating system:	w10 pro
Metabase host env:	Ubuntu 22.04 LTS
```

### Severity

very serious, system completely shut down

**Comment by paoliniluis** [comment] 2024-01-23 10:34
Are you running in a sub path? If so, can you please check the url when you change any settings? Also please share the logs

**Comment by dpsutton** [comment] 2024-07-02 14:23
Closing because we are unable to reproduce. If anyone has steps to reproduce this we'd happily revisit this.

**Closed by dpsutton** 2024-07-02 14:23 UTC
Labels: Type:Bug, Priority:P1, .Frontend, Administration/Settings, .Team/AdminWebapp
