### ISSUE TITLE
we log "WARN middleware.log :: OST /api/dataset 404 116.6 µs (0 DB calls)" on 404

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#36774] opened 2023-12-13 21:45 UTC
### Describe the bug

It should be "POST" and not "OST" on the errors

### To Reproduce

1) use 47.x and sync the CI redshift DB
2) do an x-ray in the public events list, see the error happening

### Expected behavior

P3

### Information about your Metabase installation

```JSON
v47.9
```

### Severity

P3

### Additional context

```
2023-12-13 21:36:54,635 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: canceled] 1.3 s (15 DB calls) App DB connections: 1/15 Jetty threads: 7/50 (9 idle, 0 queued) (136 total active threads) Queries in flight: 6 (0 queued); redshift DB 2 connections: 4/15 (0 threads blocked)
2023-12-13 21:36:54,650 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 1.1 s (15 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (10 idle, 0 queued) (136 total active threads) Queries in flight: 5 (0 queued); redshift DB 2 connections: 6/15 (0 threads blocked)
2023-12-13 21:36:54,651 WARN middleware.log :: OST /api/dataset 404 133.0 µs (0 DB calls) 
#metabase.util.i18n.UserLocalizedString{:format-string "API endpoint does not exist.", :args [], :pluralization-opts {}}

2023-12-13 21:36:54,651 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 1.1 s (15 DB calls) App DB connections: 1/15 Jetty threads: 8/50 (10 idle, 0 queued) (136 total active threads) Queries in flight: 4 (0 queued); redshift DB 2 connections: 9/15 (0 threads blocked)
2023-12-13 21:36:54,652 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: canceled] 1.3 s (15 DB calls) App DB connections: 1/15 Jetty threads: 9/50 (9 idle, 0 queued) (136 total active threads) Queries in flight: 3 (0 queued); redshift DB 2 connections: 2/15 (0 threads blocked)
2023-12-13 21:36:54,653 WARN middleware.log :: OST /api/dataset 404 123.5 µs (0 DB calls) 
#metabase.util.i18n.UserLocalizedString{:format-string "API endpoint does not exist.", :args [], :pluralization-opts {}}

2023-12-13 21:36:54,654 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 1.1 s (15 DB calls) App DB connections: 0/15 Jetty threads: 8/50 (10 idle, 0 queued) (136 total active threads) Queries in flight: 3 (0 queued); redshift DB 2 connections: 7/15 (0 threads blocked)
2023-12-13 21:36:54,654 WARN middleware.log :: OST /api/dataset 404 74.5 µs (0 DB calls) 
#metabase.util.i18n.UserLocalizedString{:format-string "API endpoint does not exist.", :args [], :pluralization-opts {}}

2023-12-13 21:36:54,656 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 1.1 s (15 DB calls) App DB connections: 2/15 Jetty threads: 9/50 (10 idle, 0 queued) (136 total active threads) Queries in flight: 2 (0 queued); redshift DB 2 connections: 11/15 (0 threads blocked)
2023-12-13 21:36:54,657 WARN middleware.log :: OST /api/dataset 404 116.6 µs (0 DB calls) 
#metabase.util.i18n.UserLocalizedString{:format-string "API endpoint does not exist.", :args [], :pluralization-opts {}}

```

**Comment by camsaul** [comment] 2024-07-02 20:49
The fact that it's returning an `API endpoint does not exist` error seems to suggest that we really **were** trying to use the `OST` method rather than `POST` somewhere. This probably originated from the FE code since the backend doesn't make REST API calls to itself

At any rate I cannot repro this anymore and I'm guessing this was already fixed at some point in the past.

**Comment by camsaul** [comment] 2024-07-02 20:54
Maybe this was fixed by the recent change to RTK query

**Comment by camsaul** [comment] 2024-07-03 16:41
ok after investigating this with others we can no longer reproduce it so going to close as Already Fixed 

https://metaboat.slack.com/archives/C505ZNNH4/p1719953609157149

**Closed by camsaul** 2024-07-03 16:41 UTC
Labels: Type:Bug, Priority:P3, .Unable to Reproduce, Misc/API, Administration/Troubleshooting, .Team/QueryProcessor
