### ISSUE TITLE
Dashboard question sidebar is blocking dashboard filter options

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16831] opened 2021-06-30 13:15 UTC
**Describe the bug**
On a dashboard with a dashboard filter applied to a question, one cannot remove or edit filter if the question sidebar is open.

**Logs**
N/A

**To Reproduce**
1. Open a dashboard with a question and at least one filter connected to that question (or create one)
2. While in the edit mode, click on add new question (it will open a sidebar)
3. Click on the filter "gear" icon to edit/remove it
4. Notice the question sidebar stays open

Alternative version would be to first click on the gear icon and enter filter editing mode, which still doesn't prevent question sidebar from opening.

**Expected behavior**
1. Sidebar should close on the click outside of it
2. Sidebar should not be possible to open when filter options are active

**Screenshots**
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/JruDyzNX/28f170f2-798e-49e1-8fe4-945a1937534f.gif?source=viewer&v=eb2539301a11a8e93d53fc64b3fb893c)

**Information about your Metabase Installation:**
local dev, master, x.40.0-snapshot, aa78e38494811da129b2c2af5ddc9d3df3d8fe30

**Severity**
UI/UX annoyance. P3.

**Comment by flamber** [comment] 2021-06-30 13:16
Duplicate of #16783

**Closed by flamber** 2021-06-30 13:16 UTC
Labels: .Needs Triage, Type:Bug
