### ISSUE TITLE
bar graphs barf when a row comes back with a "null"

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2898] opened 2016-07-06 20:31 UTC
When a result comes back with a null, it gets added to the previous column.

plotting the below as a bar graph will cause this to happen.
```
SELECT 'A', 2
UNION ALL SELECT 'B', 5
UNION ALL SELECT null, 8
```
![screen shot 2016-07-06 at 1 33 40 pm](https://cloud.githubusercontent.com/assets/107439/16633368/db8e63d4-437d-11e6-84a0-f98be4e002f8.png)

If this is a bug report, please fill in the blanks:

*  I am using the _Chrome_ browser.
*  My computer's OS is _Mac OS X_.
*  I'm running Metabase _on Heroku_. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is _Postgres_.
*  My Metabase version is _0.18.1_.

**Comment by camsaul** [comment] 2016-07-22 00:36
This affects line charts as well

**Comment by RickyMcMaster** [comment] 2016-08-01 15:26
I was experiencing an issue with nulls in my source Redshift table - this prevented Metabase displaying results as anything other than a table and a pie chart, when using a combined metric e.g. sales conversion (in this case, orders divided by clicks).

The solution was to use the Redshift function NVL [().](http://docs.aws.amazon.com/redshift/latest/dg/r_NVL_function.html) in conjunction with a case statement to get rid of all nulls.

Original code:
SELECT
  date_part(w, any_date)     AS cal_week,
  cast(sum(no_orders) AS FLOAT) /
  cast(sum(clicks) AS FLOAT) AS conv_rate
FROM source_table
GROUP BY cal_week
ORDER BY cal_week;

Amended code:
SELECT
  date_part(w, any_date)                   AS week,
  CASE WHEN nvl(sum(Clicks), 0) = 0
    THEN 0
  ELSE
    cast(nvl(sum(no_orders), 0) AS FLOAT)
    / cast(sum(Clicks) AS FLOAT) * 100 END AS "conversion rate %"
FROM source_table
GROUP BY week
ORDER BY week;

**Comment by RickyMcMaster** [comment] 2016-08-01 15:31
I was experiencing an issue with nulls in my source Redshift table - this prevented Metabase displaying results as anything other than a table and a pie chart.  The solution was to use the Redshift function [NVL](http://docs.aws.amazon.com/redshift/latest/dg/r_NVL_function.html), in conjunction with CASE, to replace the nulls with zeroes.

Original code:
SELECT
  date_part(w, any_date)     AS cal_week,
  cast(sum(no_orders) AS FLOAT) /
  cast(sum(clicks) AS FLOAT) AS conv_rate
FROM source_table
GROUP BY cal_week
ORDER BY cal_week;


Amended code:
SELECT
  date_part(w, any_date)                   AS week,
  CASE WHEN nvl(sum(Clicks), 0) = 0
    THEN 0
  ELSE
    cast(nvl(sum(no_orders), 0) AS FLOAT)
    / cast(sum(Clicks) AS FLOAT) * 100 END AS "conversion rate %"
FROM source_table
GROUP BY week
ORDER BY week;


This works, although not that efficient of course.  Would love to see if this could be avoided.

**Comment by tlrobinson** [comment] 2016-08-04 08:29
@salsakran This appears to be fixed in 0.19.0 and master. Can you confirm? https://stats.metabase.com/card/130

**Comment by salsakran** [comment] 2016-08-04 19:39
@tlrobinson confirmed that it looks fixed for me. 

@RickyMcMaster can you check to see if this bug is still affecting you in version 0.19?

**Comment by camsaul** [comment] 2016-09-01 02:10
@RickyMcMaster ??

**Comment by camsaul** [comment] 2016-09-10 02:38
@RickyMcMaster ??

**Comment by camsaul** [comment] 2016-09-13 19:28
@RickyMcMaster ?

**Comment by tlrobinson** [comment] 2016-09-16 20:07
I'm unable to reproduce this on Postgres, and I can't think of any reason why Redshift would behave differently, so I'm going to close this. If @RickyMcMaster can still reproduce this we'll reopen it.

**Closed by tlrobinson** 2016-09-16 20:07 UTC
Labels: Bug, Unable to Reproduce, Visualization

**Comment by camsaul** [comment] 2016-09-16 20:08
@tlrobinson yeah Redshift is just Postgres 8.x with some features taken out, so there shouldn't be any difference WRT this
