### ISSUE TITLE
Duplicate column name "DATABASE_ID"

### ISSUE THREAD

**Issue by anshulk** [metabase/metabase#8947] opened 2018-11-15 10:34 UTC
I've a Metabase v0.30.4 running via jar on a Ubuntu box.
Downloaded v31 and tried running that instead but got this error : 

**11-15 04:29:09 ERROR metabase.core :: Metabase Initialization FAILED
org.h2.jdbc.JdbcSQLException: Duplicate column name "DATABASE_ID"; SQL statement:
ALTER TABLE PUBLIC.query_execution ADD database_id INT; [42121-197]**

How can I fix this ?

**Comment by benmod** [comment] 2018-11-19 11:49
I am having the same issue. Did you find anything to solve it?

**Comment by camsaul** [comment] 2018-11-19 18:50
@anshulk @benmod 

try running 

```
java -jar metabase.jar migrate force
```

that should fix it

**Comment by camsaul** [comment] 2018-11-19 22:44
Duplicate of #8937 

Should have a fix shortly.

**Closed by camsaul** 2018-11-19 22:44 UTC
