### ISSUE TITLE
Performance Issues with Line replace missing with null

### ISSUE THREAD

**Issue by analyticsdriven** [metabase/metabase#9192] opened 2019-01-02 19:07 UTC
Our team is trying to do line visualization on a data set with many missing values. The current default of  "Linear Interpolated" is especially misleading to the users when there is a particularly large gap in the data.  However changing this setting to "Replace missing values with Nothing" is incredibly slow, to the point of sometimes crashing the browser. 

Our current workaround is the Scatter Visualization. However our users prefer the look of the Line visualization and generally like having the line where data is not missing. In the meantime, if anyone else has a solution or suggestion for making the Scatter bubbles smaller please let me know.

Unlike previous issues, all of our data displays correctly but it is exponentially slower / causes browser crashes to display when "Replace missing values with Nothing" is selected. Is anyone else experiencing this? If not I will get with our team about our environment.

- Your browser and the version: Chrome Version 67 and IE 11
- Your operating system: Windows 7 Enterprise 64-bit
- Your databases: MySQL
- Metabase version: 0.31.2
- Metabase hosting environment: Linux
- Metabase internal database: MySQL

**Comment by salsakran** [comment] 2019-01-03 23:39
how many points are you rendering?

**Comment by analyticsdriven** [comment] 2019-01-04 03:06
Thank you for the response, we have lag for as few as 200 or so data points. We've been doing native SQL questions with limit. If you'd like I can try to give you a more detailed response.

**Comment by flamber** [comment] 2020-05-26 17:15
I think this was fixed in 0.32. I cannot reproduce on 0.35.3

**Closed by flamber** 2020-05-26 17:15 UTC
Labels: Type:Performance, Visualization/, Visualization/Chart Settings
