### ISSUE TITLE
Metric (v2) `visualization_settings` can sometimes contain the metric name instead of an aggregation

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#44140] opened 2024-06-13 13:55 UTC
### Describe the bug

When we create a new ad-hoc question based on a metric (v2), the visualization settings will contain that metric name in the `visualization_settings` instead of the aggregation metric. This leads to a lot of problems down the line, each of which will be documented separately.

Each of those should link to this issue as the cause.

### To Reproduce

Let's use: Orders, count of rows broken down by month - let's call it  "Foo Metric"

1. Either create a new metric or open a saved one
2. Click on the `i` icon (More info)
3. Edit a metric description and blur
4. This should trigger the `PUT` request because we just edited the metric

Check out the network tab for the response of that request, and you'll see the following:
```js
visualization_settings: {
  "graph.dimensions": [
    "CREATED_AT"
  ],
  "graph.metrics": [
    "Foo Metric" // this should've been ["count"]
  ]
}
```

### Expected behavior

Keep the aggregation metric (such as "count", "average of", etc.) in the viz_settings for metrics.

### Information about your Metabase installation

```JSON
local dev, master @ 68bd978, H2, Sample Database
```

### Severity

P2 or P1 since this can lead to crashes

**Comment by mngr** [comment] 2024-10-04 16:45
From the product point of view, it rather should always be a metric name

**Comment by mngr** [comment] 2024-10-04 16:51
"When we create a new ad-hoc question based on a metric (v2), the visualization settings will contain that metric name in the visualization_settings instead of the aggregation metric."
I can't reproduce this

**Comment by ranquild** [comment] 2024-10-21 14:57
Can't reproduce; was fixed by recent BE changes

**Closed by ranquild** 2024-10-21 14:57 UTC
Labels: Type:Bug, Priority:P2, .Frontend, .Regression/master, .Team/Querying, Querying/Metrics
