### ISSUE TITLE
Cannot use Saved Question, when original question uses "Display values"="Use foreign key"

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#10474] opened 2019-08-02 17:39 UTC
**Describe the bug**
When a field in Admin > Data Model has "Display values"="Use foreign key", then the question cannot be used as Saved Question.
It will just return an error that the foreign table column was not found (depending on database, the error might be different):
`Invalid column name "TITLE"`
`Column "source.TITLE" not found`

**To Reproduce**
Steps to reproduce with Sample Dataset:
1. Go to Admin > Data Model > Sample Dataset > Orders > Product ID :gear: 
2. Change "Display values"="Use foreign key", connected to "Title"
3. Create a QB/Simple question of Orders and save it as "Q1"
4. Create a new question and use the "Q1" in Saved Questions, and run it.
5. Fails with the error: `Column "source.TITLE" not found`

**Information about your Metabase Installation:**
Metabase 0.32.10 (prod) and 0.33.0-RC1 (test)
This used to work in 0.32.9

**Comment by camsaul** [comment] 2020-09-11 19:22
Fixed by #13202

**Comment by nemanjaglumac** [comment] 2021-02-03 17:09
Should we reopen and move the milestone to 38?

**Comment by flamber** [comment] 2021-02-03 17:13
No, it's no an issue in any official releases.

**Comment by nemanjaglumac** [comment] 2021-02-03 17:15
But it is a regression?

**Comment by flamber** [comment] 2021-02-03 17:18
But it's not in any releases. Issues only get a milestone, when it's fixed in that - this was fixed and a PR before 0.38 has caused a regression, which will be fixed before 0.38.0 - otherwise it will be reopened and regression added. It's mainly tracked in #14629

**Comment by camsaul** [comment] 2021-02-05 20:04
If it's a regression in `master` or whatever we should definitely reopen it. Otherwise the eng team won't find out about it until we ship 0.38.0. I didn't know about it until today.

It doesn't sound like the same issue as #14629, because otherwise I wouldn't have been able to fix #14629 without fixing this

**Comment by camsaul** [comment] 2021-02-05 20:12
Reopened and self-assigned so I know this is something I need to look at

**Comment by camsaul** [comment] 2021-02-09 21:45
Fixed by #14695

**Closed by camsaul** 2021-02-09 21:45 UTC
Labels: .Reproduced, Priority:P2, Querying/Nested Queries, Type:Bug
