### ISSUE TITLE
Changes in date and number format- when fetching results through API query/csv or xlsx or json endpoint

### ISSUE THREAD

**Issue by Varshini-S-5007402** [metabase/metabase#40544] opened 2024-03-24 15:38 UTC
### Describe the bug

In Metabase version 0.49.0, there is a discrepancy in the formatting of downloaded CSV, XLSX, or JSON files when compared to the previous version. Specifically, the issue arises with visualizations containing percentages or numbers with comma separators, as well as date formats are reflected as such is downloads without raw numbers and value.

Affected Functionality:
Downloading CSV, XLSX, or JSON files through the API endpoint (api/card/query/csv).
Date formats in downloaded files.
example result: February 19, 2024, 12:00 AM	60.58%

Expected Behavior:
In previous versions of Metabase, the downloaded files retained the raw values with many decimal places for numerical data and followed a consistent date format.
actual result: 2024-02-19T00:00:00Z	      0.605767631	

Impact:
The formatting differences in the downloaded files make it challenging to compare results between the current and previous versions of Metabase, especially when migrating reports or analyzing data.

### To Reproduce

Output from sample database:
![image](https://github.com/metabase/metabase/assets/139036730/3c7ee1e0-ed31-4aa9-9d90-32fa05f0e516)

Downloaded result through api/card/csv has same visualization results.
![image](https://github.com/metabase/metabase/assets/139036730/6f2d4a82-db5c-4e26-8be8-45561df49e98)

Expected result (as in previous metabase version before v0.49.0):
![image](https://github.com/metabase/metabase/assets/139036730/86a04ae4-3166-4621-891d-de6658282b29)

### Expected behavior

The downloaded files / fetched results through API  retained the raw values with many decimal places for numerical data and followed a consistent date format.
Date format to return to how it worked prior to 0.49.0

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.15.133+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "bigquery-cloud-sdk",
      "mongo",
      "postgres",
      "presto-jdbc",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.39-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.5"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-06-13",
      "tag": "v0.43.3",
      "branch": "release-x.43.x",
      "hash": "c9c7ef0"
    },
    "settings": {
      "report-timezone": "Asia/Dhaka"
    }
  }
}
```

### Severity

2- Causing issue in migrating reports

### Additional context

This was working good before v0.49.0

**Comment by paoliniluis** [comment] 2024-03-25 15:06
Duplicate of https://github.com/metabase/metabase/issues/40420

**Closed by paoliniluis** 2024-03-25 15:06 UTC
Labels: Type:Bug, .Needs Triage
