### ISSUE TITLE
Collection Permissions - sub-collections sometimes not visible until browser window re-sized or the scroll left/right

### ISSUE THREAD

**Issue by lindsay-stevens** [metabase/metabase#17185] opened 2021-07-23 10:47 UTC
**Describe the bug**
Sometimes in the Collection Permissions page, the list of nested/sub collections is empty initially, even though the collections exist. The collections become visible once the browser window is re-sized or the collection table is scrolled (if there's a scroll bar). It doesn't happen every time, but it can be reliably reproduced with a bit of clicking around the collections permissions UI.

**Logs**

Browser console is as follows. No network activity occurs when the collection becomes visible.

```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). utils.js:35:9
Setting moment.js start of week for Locale en to sunday app-main.bundle.js:5:1142496
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! root
DEPRECATED: metabase/redux/metadata fetchRealDatabases
```

**To Reproduce**
1. Go to Admin -> Permissions -> Collection permissions
2. Click on Our analytics -> View sub-collections (for a collection that has sub-collections)
3. See no sub-collections listed.
4. Re-size the browser window a bit - sometimes a few times to get it to work. If there's a scroll bar then scrolling left/right can work too.
5. See the expected sub-collections pop into existence.

**Expected behavior**
The sub-collections list should reliably populate without having to resize the browser window.

**Screenshots**
Before

![image](https://user-images.githubusercontent.com/6345269/126771194-1940f870-67cc-46c2-b4e9-a421b9580984.png)

After

![image](https://user-images.githubusercontent.com/6345269/126771231-290f0cd1-8c6d-46d3-8e4c-b319a6248bf0.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox 88
- Your operating system: Windows 10
- Your databases: Postgres
- Metabase version: v0.39.2
- Metabase hosting environment: CentOS service
- Metabase internal database: Postgres

**Severity**
It blocks users from managing their collection permissions until they are informed of the workaround.

**Comment by flamber** [comment] 2021-07-23 11:10
Hi @lindsay-stevens 
I haven't been able to reproduce, but I have a feeling that it might already have been fixed by #16677 (v40.0), since that fixed a race-condition, which could occur sometimes.
Otherwise it will likely be completely solved, when the permissions page gets an overhaul #15771 - slated for v41.0 currently.
Can you reproduce on 40.1?

**Comment by lindsay-stevens** [comment] 2021-08-12 11:11
Hi @flamber I can reproduce this on Firefox 88.0 with Metabase v1.40.2. The problem seems to be associated with the browser viewport dimensions. I was testing with the browser Responsive Design Mode and it seems to happen at widths 326px or less (327px and up is OK), or 665px height or less (666px and up is OK).

So that would affect e.g. iPhone 5 (320x568), Galaxy S5 (360x640), or people tiling their browser windows; but not e.g. iPhone 6/7/8 (375x667), Galaxy S9 (360x740), or full / half-screen browsers. Maybe it is more a limitation then than a bug.

**Comment by flamber** [comment] 2021-08-12 12:10
@lindsay-stevens Okay, yeah, it's not responsive currently - for reference #15232

I can reproduce, when I go into a collection, which is far down on the root collection, so I think this is one of the React issues with elements outside of the DOM. Not sure why the Data permissions doesn't cause the same problem.

Only giving P3, since it feels like an edge-case - and has a quick workaround (beside window resize) - and because it will be fixed in v41 with the overhaul.
![image](https://user-images.githubusercontent.com/1447303/129193984-a265ad0c-9491-4252-b915-f71fae8ab84b.png)
![image](https://user-images.githubusercontent.com/1447303/129194251-40a1d33b-e952-4f35-af92-ba440f7c97e5.png)

**Closed** 2021-08-24 18:30 UTC
Labels: Type:Bug, Priority:P3, Administration/Permissions
