### ISSUE TITLE
Don't load all saved questions when opening a saved question

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10938] opened 2019-09-19 17:12 UTC
As described in https://github.com/metabase/metabase/issues/10163#issuecomment-531609641:

- `database?include_tables=true&include_cards=true` takes about 2-5 seconds (120+kb of json goodness to serialize, from our 3K cards)
- this calls is fired systematically, even to see a question that has been built with the SQL or the simple question viewer

@tlrobinson suggested that the `include_cards` parameter and possibly the `include_tables` parameter should be eliminated. He additionally opined, `I’m not sure where the regression is though. Maybe we didn’t previously load it for sql questions or maybe we're not caching it.`

**Comment by salsakran** [comment] 2019-09-24 17:25
@tlrobinson does this actually fix the case where a user clicks into a saved question?

**Comment by tlrobinson** [comment] 2019-09-24 18:25
@salsakran I think so. I interpreted this issue, which was a response to https://github.com/metabase/metabase/issues/10163#issuecomment-531609641 to be a performance regression in 0.33.

The only regression I could find was we stopped essentially pre-loading the database metadata on the new question page. That actually didn't affect saved questions since if you navigate directly to a saved question you might not have previously hit the new question page.

So AFAICT there wasn't a regression for saved questions, but I looked to see if there was anything I could improve anyway, and I did this:

> improve saved question latency: in the query builder don't block initializeQB on loading /api/database?include_tables=true&include_cards=true, which allows saved questions (including query itself) to begin loading immediately

We have #10163 to address loading all the saved questions when loading the query builder up front. I proposed one solution but I'm open to others. At least it's no longer blocking loading saved questions.

**Comment by salsakran** [comment] 2019-09-24 18:29
Separate from the regression, we are currently "loading all saved questions when opening a saved question" no? 

👍  on not blocking

**Comment by tlrobinson** [comment] 2019-09-24 18:39
Yes, but this is basically a duplicate of #10163

**Comment by salsakran** [comment] 2019-09-24 18:43
Cool, I mainly didn't want this to get lost. I agree it is captured in #10163, and will reclose =)

**Closed by salsakran** 2019-09-24 18:43 UTC
Labels: API, Priority:P1, Type:Bug, Type:Performance
