### ISSUE TITLE
some strings is not completly spanish translated

### ISSUE THREAD

**Issue by johnfelipe** [metabase/metabase#9042] opened 2018-11-28 18:59 UTC
![panoramica-0000](https://user-images.githubusercontent.com/428820/49175073-bfa62680-f315-11e8-834c-a2b8b30adb6b.png)

all strings with red shape is not translated
i want contribute, but i need method or instructions for add that translations
Stay alert

**Comment by mazameli** [comment] 2018-11-28 19:08
Which version of Metabase are you using? We added translations for x-rays like in your screenshot in version 0.31.0. Not every language got to 100% complete translation by version 0.31.0, but I'm pretty sure Spanish did, so if you're running that version you should be seeing translated x-rays. Let me know if you don't.

As for helping with translations, we use [POEditor](https://poeditor.com/join/project/ynjQmwSsGh) to allow members of the community to help translate Metabase into various languages. We'd love it if you'd like to join the translation project on that site.

**Comment by johnfelipe** [comment] 2018-11-29 03:36
minor errors show in my poeditor

![snag-0030](https://user-images.githubusercontent.com/428820/49197711-ea1bd200-f35d-11e8-9254-92f72a176a42.png)

spaces, "?" missing, i wil solved soon

**Comment by johnfelipe** [comment] 2018-11-29 04:11
[es.zip](https://github.com/metabase/metabase/files/2627559/es.zip)

![snag-0031](https://user-images.githubusercontent.com/428820/49198771-ce66fa80-f362-11e8-95f4-8abf4ff9066d.png)

I have warning in that strings because capital letter in translate and not in original text

How can review again in my v0.31.1, build 2018-11-2 instance?

**Comment by jrvidotti** [comment] 2019-03-06 17:58
@johnfelipe in order to make translations last, you have to make it in the POEditor project: https://poeditor.com/join/project/ynjQmwSsGh

**Comment by flamber** [comment] 2020-03-17 16:48
Closing since this was likely caused by trying to translation manually instead of via [POEditor](https://poeditor.com/join/project/ynjQmwSsGh).

**Closed by flamber** 2020-03-17 16:48 UTC
Labels: .Need More Info, Customization/i18n
