### ISSUE TITLE
Upgrading to v50 broke all queries that have summaries with custom expressions on unix timestamp columns

### ISSUE THREAD

**Issue by MarkoTukiainen** [metabase/metabase#48721] opened 2024-10-15 09:40 UTC
### Describe the bug

Seems like the upgrade to v50 broke all of our queries that have summaries with custom expressions on tables with timestamp columns for dates. 

Specifically what happens is that the FROM clause in the query converts the timestamp to date and assigns that as the "ts" field of the "source" alias, but then the SUM calculations perform another FROM_UNIXTIME conversion on that value, which will obviously fail. 

Converting the query to SQL and manually removing the extraneous FROM_UNIXTIME calls from all the SUM columns restores the original functionality, but this is not desirable. 

I tried manually adjusting the table's metadata in the admin settings and converting it from unix timestamp (seconds) to datetime, however this had no effect.

### To Reproduce

Upgrade Metabase to v50.

### Information about your Metabase installation

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-10-02",
      "tag": "v0.50.28",
      "hash": "3179ef2"
    },
    "settings": {
      "report-timezone": "Europe/Helsinki"
    },
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.4.13-MariaDB-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.10.214-202.855.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}

### Severity

Blocking the usage of Metabase entirely

**Comment by paoliniluis** [comment] 2024-10-15 13:05
Hi @MarkoTukiainen any example of a question you can give us also with a table definition?

**Comment by MarkoTukiainen** [comment] 2024-10-15 13:12
The table contains fields:

ts int (11) unsigned
shopid varchar(32)
sales double
commission double
invoices int(11) unsigned
consolidatedorders int(11) unsigned
consolidatedsales double

Here's a question that gets generated. 

```
SELECT
  CEIL(
    DAYOFYEAR(
      DATE_ADD(
        STR_TO_DATE(
          CONCAT(
            YEARWEEK(DATE_ADD(`source`.`ts`, INTERVAL -1 day)),
            ' Sunday'
          ),
          '%X%V %W'
        ),
        INTERVAL 1 day
      )
    ) / 7.0
  ) AS `ts`,
  SUM(
    CASE
      WHEN
FROM_UNIXTIME(`source`.`ts`) BETWEEN DATE(
        convert_tz(
          '2022-01-01 00:00:00.000',
          '+02:00',
          @@session.time_zone
        )
      )
     
   AND DATE(
        convert_tz(
          '2022-12-31 00:00:00.000',
          '+02:00',
          @@session.time_zone
        )
      ) THEN `source`.`commission`
      ELSE 0.0
    END
  ) AS `Commission 2022`,
  SUM(
    CASE
      WHEN FROM_UNIXTIME(`source`.`ts`) BETWEEN DATE(
        convert_tz(
          '2023-01-01 00:00:00.000',
          '+02:00',
          @@session.time_zone
        )
      )
      AND DATE(
        convert_tz(
          '2023-12-31 00:00:00.000',
          '+02:00',
          @@session.time_zone
        )
      ) THEN `source`.`commission`
      ELSE 0.0
    END
  ) AS `Commission 2023`,
  SUM(
    CASE
      WHEN FROM_UNIXTIME(`source`.`ts`) BETWEEN DATE(
        convert_tz(
          '2024-01-01 00:00:00.000',
          '+02:00',
          @@session.time_zone
        )
      )
      AND DATE(
        convert_tz(
          '2024-12-31 00:00:00.000',
          '+02:00',
          @@session.time_zone
        )
      ) THEN `source`.`commission`
      ELSE 0.0
    END
  ) AS `Commission 2024`,
  SUM(
    CASE
      WHEN FROM_UNIXTIME(`source`.`ts`) BETWEEN DATE(
        convert_tz(
          '2023-01-01 00:00:00.000',
          '+02:00',
          @@session.time_zone
        )
      )
      AND DATE(
        convert_tz(
          '2023-12-31 00:00:00.000',
          '+02:00',
          @@session.time_zone
        )
      ) THEN `source`.`Commission Goal 2`
      ELSE 0.0
    END
  ) AS `Commission Goal 2024 (+19%)`
FROM
  (
    SELECT
      FROM_UNIXTIME(`dailysales`.`ts`) AS `ts`,
      `dailysales`.`commission` AS `commission`,
      (`dailysales`.`commission` * 0.19) + `dailysales`.`commission` AS `Commission Goal 2`
    FROM
      `dailysales`
  ) AS `source`
GROUP BY
  CEIL(
    DAYOFYEAR(
      DATE_ADD(
        STR_TO_DATE(
          CONCAT(
            YEARWEEK(DATE_ADD(`source`.`ts`, INTERVAL -1 day)),
            ' Sunday'
          ),
          '%X%V %W'
        ),
        INTERVAL 1 day
      )
    ) / 7.0
  )
ORDER BY
  CEIL(
    DAYOFYEAR(
      DATE_ADD(
        STR_TO_DATE(
          CONCAT(
            YEARWEEK(DATE_ADD(`source`.`ts`, INTERVAL -1 day)),
            ' Sunday'
          ),
          '%X%V %W'
        ),
        INTERVAL 1 day
      )
    ) / 7.0
  ) ASC
```

**Comment by Tony-metabase** [comment] 2024-10-17 14:25
Hi Marko,

If you downgrade to 50.27 do you get the same behaviour?

**Comment by MarkoTukiainen** [comment] 2024-10-18 05:25
> If you downgrade to 50.27 do you get the same behaviour?

Downgraded to v0.50.27.4, it does the same thing.

**Comment by Tony-metabase** [comment] 2024-10-18 08:02
Interesting cause we tested this on different versions and cannot seem to hit what is going on. Even our cloud is currently on 50.30 and no one flagged such a case.

You are converting to unix timestamp at metabase level right? When you go to Admin -> Table Metadata -> Table -> Column and inside the settings right? Can you share a screenshot of this column `ts`

**Comment by MarkoTukiainen** [comment] 2024-10-18 08:08
![Image](https://github.com/user-attachments/assets/6706f2af-15b1-4bda-abe0-225154c6dd8b)

This is the ts field (it's title is Date in the metadata settings).

**Comment by MarkoTukiainen** [comment] 2024-10-25 10:53
> Interesting cause we tested this on different versions and cannot seem to hit what is going on. Even our cloud is currently on 50.30 and no one flagged such a case.
> 
> You are converting to unix timestamp at metabase level right? When you go to Admin -> Table Metadata -> Table -> Column and inside the settings right? Can you share a screenshot of this column `ts`

Hey @Tony-metabase, a quick update on this. I'm not sure if my downgrade didn't work properly immediately or if there's some sort of caching involved in this, but I just got a message that said that the graphs were suddenly working again (without anyone doing anything). Now, with v0.50.27.4 installed the query looks like this (FROM_UNIXTIME is done to dailysales.ts and not source.ts as in my previous example):

```SELECT
  CEIL(
    DAYOFYEAR(
      DATE_ADD(
        STR_TO_DATE(
          CONCAT(
            YEARWEEK(
              DATE_ADD(FROM_UNIXTIME(`dailysales`.`ts`), INTERVAL -1 day)
            ),
            ' Sunday'
          ),
          '%X%V %W'
        ),
        INTERVAL 1 day
      )
    ) / 7.0
  ) AS `ts`,
  SUM(
    CASE
      WHEN
FROM_UNIXTIME(`dailysales`.`ts`) BETWEEN DATE(
        convert_tz(
          '2022-01-01 00:00:00.000',
          '+02:00',
          @@session.time_zone
        )
      )
     
   AND DATE(
        convert_tz(
          '2022-12-31 00:00:00.000',
          '+02:00',
          @@session.time_zone
        )
      ) THEN `dailysales`.`commission`
      ELSE 0.0
    END
  ) AS `Commission 2022`,
  SUM(
    CASE
      WHEN FROM_UNIXTIME(`dailysales`.`ts`) BETWEEN DATE(
        convert_tz(
          '2023-01-01 00:00:00.000',
          '+02:00',
          @@session.time_zone
        )
      )
      AND DATE(
        convert_tz(
          '2023-12-31 00:00:00.000',
          '+02:00',
          @@session.time_zone
        )
      ) THEN `dailysales`.`commission`
      ELSE 0.0
    END
  ) AS `Commission 2023`,
  SUM(
    CASE
      WHEN FROM_UNIXTIME(`dailysales`.`ts`) BETWEEN DATE(
        convert_tz(
          '2024-01-01 00:00:00.000',
          '+02:00',
          @@session.time_zone
        )
      )
      AND DATE(
        convert_tz(
          '2024-12-31 00:00:00.000',
          '+02:00',
          @@session.time_zone
        )
      ) THEN `dailysales`.`commission`
      ELSE 0.0
    END
  ) AS `Commission 2024`
FROM
  `dailysales`
GROUP BY
  CEIL(
    DAYOFYEAR(
      DATE_ADD(
        STR_TO_DATE(
          CONCAT(
            YEARWEEK(
              DATE_ADD(FROM_UNIXTIME(`dailysales`.`ts`), INTERVAL -1 day)
            ),
            ' Sunday'
          ),
          '%X%V %W'
        ),
        INTERVAL 1 day
      )
    ) / 7.0
  )
ORDER BY
  CEIL(
    DAYOFYEAR(
      DATE_ADD(
        STR_TO_DATE(
          CONCAT(
            YEARWEEK(
              DATE_ADD(FROM_UNIXTIME(`dailysales`.`ts`), INTERVAL -1 day)
            ),
            ' Sunday'
          ),
          '%X%V %W'
        ),
        INTERVAL 1 day
      )
    ) / 7.0
  ) ASC```

**Comment by paoliniluis** [comment] 2024-10-25 15:27
@MarkoTukiainen should we close this then?

**Comment by MarkoTukiainen** [comment] 2024-10-25 15:46
@paoliniluis No, I mean I downgraded from a newer version (as suggested) and things started eventually working again. I can try upgrading to the newer version and see if the issue reappears.

**Comment by MarkoTukiainen** [comment] 2024-10-25 16:07
@paoliniluis @Tony-metabase So seems like I was mistaken about the downgrade actually doing anything. I asked around and turns out that someone had modified the questions so that they would at least partially work again. 

And what they did to fix it was as follows:
There are three custom columns in the question, which are dynamically calculated from other fields. For example the custom "goal" column is some value + a percentage. Now, if you attempt to create a custom summarize expression based on the custom column, for example `SumIf([Commission Goal 2], between([Date], "2022-01-01", "2022-12-31"))` then everything in the question goes to zero, since all the columns start referring to the dynamic "source.ts" instead of "dailysales.ts" and they perform an extra FROM_UNIXTIME on the source, since those values have already been converted to dates.

**Comment by ranquild** [comment] 2024-11-01 13:53
Seems like a duplicate of https://github.com/metabase/metabase/issues/47940

**Comment by metamben** [comment] 2024-11-19 20:15
The following query works in v49, but fails on master at 893e297e0d:
![Image](https://github.com/user-attachments/assets/419d5530-49c2-4f80-aeae-4e81cc8727e8)

**Closed** 2024-11-21 20:21 UTC
Labels: Type:Bug, Priority:P1, Querying/Processor, .Backend, .Team/Querying
