### ISSUE TITLE
Webservice support

### ISSUE THREAD

**Issue by thejeshgn** [metabase/metabase#6207] opened 2017-10-19 12:33 UTC
Is there any plans for supporting webservices (JSON or XML) as way to pull data?

This will be for pulling data from third party services to be included as part of metabase. Simple and stupid examples would be weather or currency exchange information.

**Comment by camsaul** [comment] 2017-10-19 22:27
Duplicate of #4831

**Closed by camsaul** 2017-10-19 22:27 UTC
