### ISSUE TITLE
dash board filter failed to present question

### ISSUE THREAD

**Issue by vincentsjtu** [metabase/metabase#9327] opened 2019-01-25 04:46 UTC
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
chrome 71.0.3578.98
- Your operating system: (e.x. OS X 10, Windows XP, etc)
os x 10.1
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
postgres
- Metabase version: (e.x. 0.19.3)
v0.31.2
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
aws beanstalk
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
postgres
- *Repeatable steps to reproduce the issue*
add single date filter to a dashboard, then the questions show "There was a problem displaying this chart." .It works well when i click into the question with that filter.
Thanks for being part of the Metabase project!
metabase log:
Query failure: Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-null, :not-null, :time-interval, :segment
("clojure.core$ex_info.invokeStatic(core.clj:4739)"
"clojure.core$ex_info.invoke(core.clj:4739)"
"--> query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:285)"
"query_processor$assert_query_status_successful.invoke(query_processor.clj:277)"
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:323)"
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:316)"
"query_processor$fn__37732$process_query_and_save_execution_BANG___37737$fn__37738.invoke(query_processor.clj:354)"
"query_processor$fn__37732$process_query_and_save_execution_BANG___37737.invoke(query_processor.clj:340)"
"api.card$run_query_for_card.invokeStatic(card.clj:580)"
"api.card$run_query_for_card.doInvoke(card.clj:566)"
"api.card$fn__47036$fn__47039.invoke(card.clj:587)"
"api.card$fn__47036.invokeStatic(card.clj:586)"
"api.card$fn__47036.invoke(card.clj:582)"
"middleware$enforce_authentication$fn__56174.invoke(middleware.clj:113)"
"api.routes$fn__56320.invokeStatic(routes.clj:62)"
"api.routes$fn__56320.invoke(routes.clj:62)"
"routes$fn__56409$fn__56410.doInvoke(routes.clj:108)"
"routes$fn__56409.invokeStatic(routes.clj:103)"
"routes$fn__56409.invoke(routes.clj:103)"
"middleware$catch_api_exceptions$fn__56309.invoke(middleware.clj:436)"
"middleware$log_api_call$fn__56287$fn__56289.invoke(middleware.clj:364)"
"middleware$log_api_call$fn__56287.invoke(middleware.clj:363)"
"middleware$add_security_headers$fn__56229.invoke(middleware.clj:252)"
"core$wrap_streamed_json_response$fn__62673.invoke(core.clj:67)"
"middleware$bind_current_user$fn__56179.invoke(middleware.clj:137)"
"middleware$maybe_set_site_url$fn__56239.invoke(middleware.clj:290)"
"middleware$add_content_type$fn__56232.invoke(middleware.clj:262)")
-------

**Comment by flamber** [comment] 2019-01-25 14:55
Hi @vincentsjtu 
It sounds like you're using variables and something goes wrong. Could it be that you're using Field Filter, but haven't matched your query, since it's different than normal variables - have a look at the tutorial:
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html

**Comment by vincentsjtu** [comment] 2019-01-28 08:22
@flamber thanks for feed back.
 i dont use any defined variable. actually i haven't used native sql, but put some saved question on the dashboard and added a dashboard filter. it s simply a date filter to select only data by specific date. it works well when i add that filter in the question but failed on the dashboard![2019-01-28 4 20 21](https://user-images.githubusercontent.com/28680080/51822952-cc94c580-2318-11e9-9503-fbeb251ddfa8.png)

**Comment by vincentsjtu** [comment] 2019-01-28 08:22
it works well when i use the relative date

**Comment by flamber** [comment] 2019-01-28 13:39
@vincentsjtu 
Ahhh okay, then it's a duplicate of #9090

**Closed** 2019-02-19 23:16 UTC
Labels: Duplicate
