### ISSUE TITLE
[Flaky Test]: should not clip dashcard actions (metabase#31274)

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#43710] opened 2024-06-05 23:24 UTC
Last Flake: https://github.com/metabase/metabase/actions/runs/9378777427
Last Flake Time: 2024-06-04T23:37:00-07:00
Flakes in the last day: 1
Flakes in the last 3d: 1
Flakes in the last 7d: 1

**Comment by github-automation-metabase** [comment] 2024-06-07 20:16
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9378777427
Last Flake Time: 2024-06-04T23:37:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 1
Flakes in the last 7d: 1

**Comment by JesseSDevaney** [comment] 2024-06-19 19:32
Closing as this test does not appear to be flaking anymore according to replay.io/cannot reproduce the flake to fix it since it is no longer occurring

**Closed by JesseSDevaney** 2024-06-19 19:32 UTC
Labels: .CI & Tests, flaky-test-fix, .Team/DashViz
