### ISSUE TITLE
Input to date-string->range does not match schema (metabase v0.35.0)

### ISSUE THREAD

**Issue by Olaktal** [metabase/metabase#12230] opened 2020-04-01 15:25 UTC
Hello everyone

**Describe the bug**
We've tried to migrate from metabase v0.34.3 to the newly released v0.35.0 and we are facing the following error on questions with relative date filter:

`Input to date-string->range does not match schema: [0;33m [(named (not (instance? java.lang.String ["past7days"])) date-string) nil] [0m`

here is a question as example:
 
![image](https://user-images.githubusercontent.com/5711131/78153531-726f2300-743b-11ea-92e8-60f835ba8754.png)

**Logs**

![image](https://user-images.githubusercontent.com/5711131/78154720-dfcf8380-743c-11ea-9e4f-647d1c25aea7.png)

![image](https://user-images.githubusercontent.com/5711131/78154958-28873c80-743d-11ea-9cff-64b502c3b0d0.png)

**To Reproduce**
Create a question with relative filter and migrate to 0.35.0
Does anyone have the same error ?

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Chrome Version 80.0.3987.149
- OS X cataline 10.15.3 
- Redshift
- 0.35.0
- Docker
- MySQL

**Severity**
We had to rollback, it impacts a lot of questions.

Thanks

**Comment by mazameli** [comment] 2020-04-01 15:30
Duplicate of #12228 I think.

**Closed by mazameli** 2020-04-01 15:30 UTC
Labels: .Duplicate, Type:Bug
