### ISSUE TITLE
FULL JOIN rearrengment causes SQL errors

### ISSUE THREAD

**Issue by codingjoe** [metabase/metabase#17118] opened 2021-07-20 07:59 UTC
**Describe the bug**
If you add a FULL JOIN metabase will rearrange the query and position the FULL JOIN at the end of the JOIN chain. Of course, the position of joins is not arbitrary. This may not only alter the result, but cause SQL errors if the JOIN condition references a table that isn't selected yet.

**Logs**
ERROR: missing FROM-clause entry for table "Foo Bar" Position: 1234

**To Reproduce**

Create the following schema:
```sql
CREATE TABLE a (id int PRIMARY KEY);
CREATE TABLE b (id int PRIMARY KEY);
CREATE TABLE c (id int PRIMARY KEY);
```

Create the following question:
<img width="337" alt="Screenshot 2021-07-21 at 17 03 55" src="https://user-images.githubusercontent.com/1772890/126511823-dc4e7899-2215-4756-bd2a-73aa677c2494.png">

1. Select a table A
2. FULL JOIN another table B (to A)
3. LEFT JOIN another table C (to B).

The SQL query generated by Metabase will be:
```sql
SELECT "public"."a"."id" AS "id", "B"."id" AS "B__id", "C"."id" AS "C__id"
FROM "public"."a"
LEFT JOIN "public"."c" "C" ON "B"."id" = "C"."id" FULL JOIN "public"."b" "B" ON "public"."a"."id" = "B"."id"
LIMIT 1048575
```

The JOINS have been rearranged, resulting in the following error:
```
ERROR: missing FROM-clause entry for table "B" Position: 240
```

**Expected behavior**
The JOIN order that specified in the editor should be retained.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "de",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_292-heroku-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_292-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.292-b10",
    "os.name": "Linux",
    "os.version": "4.4.0-1093-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.12 (Ubuntu 11.12-1.pgdg16.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.40.1",
      "date": "2021-07-14",
      "branch": "release-x.40.x",
      "hash": "ed8f9c8"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

**Severity**
This prevents users who do not have experience or access to SQL from building queries.

**Comment by paoliniluis** [comment] 2021-07-20 13:04
Hi @codingjoe, can provide the reproduction steps with the sample dataset? thanks :)

**Comment by codingjoe** [comment] 2021-07-21 15:05
@paoliniluis I added a schema, screenshots, the query and error message. Hope it helps.

**Comment by flamber** [comment] 2021-07-22 10:23
Duplicate of #15342

**Closed by flamber** 2021-07-22 10:23 UTC
Labels: .Query Language (MBQL), Priority:P1, Querying/GUI, Querying/Notebook, Querying/Processor, Type:Bug
