### ISSUE TITLE
Frontend Error pivoting a column with Display values-custom mapping 

### ISSUE THREAD

**Issue by skaboy007** [metabase/metabase#15164] opened 2021-03-13 21:00 UTC
**Describe the bug**
Whenever trying to use the pivot table visualization on a column that I have previously mapped its values in the data module section of admin, I get a frontend error. and the whole frontend is going crazy without the ability to recover till a full page reload 
Please see the screenshot
![image](https://user-images.githubusercontent.com/50078277/111043929-2e0f4400-844e-11eb-87cd-bf6977e80356.png)

The bug was tested and confirmed on both Clickhouse and regular MySQL. putting this info as clarification as the debug info below shows I'm using clickhouse. 

**Logs**
Google console log
Setting moment.js start of week for Locale en to sunday
app-main.bundle.js?6af835044d5f3f6749b7:5 error TypeError: Cannot read property '0' of null
    at o (app-main.bundle.js?6af835044d5f3f6749b7:5)
    at app-main.bundle.js?6af835044d5f3f6749b7:5
    at Array.findIndex (<anonymous>)
    at app-main.bundle.js?6af835044d5f3f6749b7:5
    at Array.map (<anonymous>)
    at app-main.bundle.js?6af835044d5f3f6749b7:5
    at Function.t.a [as mapObject] (vendor.bundle.js?6af835044d5f3f6749b7:462)
    at app-main.bundle.js?6af835044d5f3f6749b7:5
    at a (app-main.bundle.js?6af835044d5f3f6749b7:5)
    at Array.map (<anonymous>)

**To Reproduce**
1. Map certain column values with the custom mapping option  
![image](https://user-images.githubusercontent.com/50078277/111043991-88100980-844e-11eb-8640-501d0ac0c131.png)
2. go to the simple query builder create a suitable query to use the pivot visualization, don't forget to use the custom mapped column in groupe by

**Expected behavior**
for the Pivot visualization to work 

**Screenshots**
a few attached above

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7-Ubuntu-1ubuntu218.04.1",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7-Ubuntu-1ubuntu218.04.1",
    "os.name": "Linux",
    "os.version": "4.15.0-34-generic",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "sqlserver",
      "h2",
      "clickhouse"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.26-0ubuntu0.18.04.1-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-03-03",
      "tag": "v0.38.1",
      "branch": "release-x.38.x",
      "hash": "79ef63a"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}

**Severity**
well, all of the old things are working. but the new Pivot feature is not. we and I personally are very excited about the pivot feature but we cannot use it on the current data structure. I use custom mapping a lot to avoid performance issues using heavy and expensive joins. which BTW worked great for 2 years)) + Metabase clickhouse driver cannot use clickhouse dictionaries directly.
so it would be great to  have the ability to use pivot in production but this challenge is holding us back

**Comment by flamber** [comment] 2021-03-14 09:42
Duplicate of #14985

**Closed by flamber** 2021-03-14 09:42 UTC
Labels: .Needs Triage, Type:Bug

**Comment by skaboy007** [comment] 2021-04-21 08:41
Upvote
