### ISSUE TITLE
 Specific visualization_settings can cause empty export (even in v0.41.6)

### ISSUE THREAD

**Issue by mhd-adam** [metabase/metabase#19717] opened 2022-01-17 14:24 UTC
Hi,
it's been reported [here](https://github.com/metabase/metabase/issues/19556#issue-1094467002) that some export cause empty files

I have checked v0.41.6 which is supposed to ship a fix for the issue but it seems like the issue persists in the latest version.

**Comment by flamber** [comment] 2022-01-17 14:34
@mhd-adam Without you providing steps-to-reproduce or metadata or anything, then it would be absolutely impossible to know what the problem is or how to fix it.

**Comment by mhd-adam** [comment] 2022-01-17 14:38
@flamber it is well described here #19465

**Comment by flamber** [comment] 2022-01-17 14:46
@mhd-adam 
That issue is fixed in 0.41.6.
When opening an issue on our tracker, please provide all the information requested.
I cannot reproduce and just linking to my own issues or not providing exact steps to reproduce means we cannot fix the issue and hence I will just close this issue.

**Closed by flamber** 2022-01-17 14:46 UTC
Labels: Type:Bug, .Needs Triage

**Comment by ds-clearago** [comment] 2022-01-18 12:06
I can confirm the same issue, that even with v0.41.6 this issue #19465 seems to not be solved 100% just yet

**Describe the bug**
Even after the upgrade, trying to export a specific saved custom SQL question yields empty exports. But as soon as you edit the SQL query (just by adding a space in the end for example) the exports work just like they should.

Unfortunately I cannot share the whole SQL query publicly (and also not our proprietary data), so let me know how I can help otherwise.

**Logs**
Don't know how to get these, and there is no description in https://metabase.com/docs/latest/troubleshooting-guide/bugs.html

**Screenshots**
![2022-01-18 at 12 59](https://user-images.githubusercontent.com/26897541/149933777-76bb4756-0338-429e-949e-5e4f9ae39bfb.png)

Trying to recreate a simple analogue export with the Metabase Sample Set didn't yield the same result though:
![2022-01-18 at 13 04](https://user-images.githubusercontent.com/26897541/149934463-205d7183-4e1f-40c7-9b22-9e2f2643bd6f.png)
Here the export worked from the saved question too...

**Information about your Metabase Installation:**
Chrome Version 97.0.4692.71 (Official Build) (x86_64)
Mac OS X 10.15.7
Hosted on AWS Elastic Beanstalk
Internal and queried database is Postgres

```
{
  "browser-info": {
    "language": "de-DE",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "4.14.256-197.484.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-01-10",
      "tag": "v0.41.6",
      "branch": "release-x.41.x",
      "hash": "296635f"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

**Comment by ds-clearago** [comment] 2022-01-22 17:22
@flamber Find below an excerpt from the JSON output at `/api/card/195`:
```
{
	"description": null,
	"archived": false,
	"collection_position": null,
	"table_id": null,
	"result_metadata": [...],
	"creator": {...},
	"can_write": true,
	"database_id": 2,
	"enable_embedding": false,
	"collection_id": 26,
	"query_type": "native",
	"name": "Clearago KPIs",
	"last_query_start": "2022-01-22T17:05:17.8343Z",
	"dashboard_count": 0,
	"average_query_time": 828.8292682926829268,
	"creator_id": 12,
	"moderation_reviews": [],
	"updated_at": "2022-01-22T17:05:18.584438Z",
	"made_public_by_id": null,
	"embedding_params": null,
	"cache_ttl": null,
	"dataset_query": {
		"type": "native",
		"native": {
			"query": "XXX",
			"template-tags": {}
		},
		"database": 2
	},
	"id": 195,
	"display": "table",
	"last-edit-info": {
		"id": 12,
		"email": "XXX",
		"first_name": "XXX",
		"last_name": "XXX",
		"timestamp": "2021-07-15T06:59:03.498998Z"
	},
	"visualization_settings": {
		"table.columns": [{
			"name": "x_date_XXX",
			"fieldRef": ["field-literal", "x_date_XXX", "type/DateTimeWithLocalTZ"],
			"enabled": true
		}, {
			"name": "x_date",
			"fieldRef": ["field-literal", "x_date", "type/DateTimeWithLocalTZ"],
			"enabled": false
		}, {
			"name": "sessions",
			"fieldRef": ["field-literal", "sessions", "type/BigInteger"],
			"enabled": true
		}, {
			"name": "new_sessions",
			"fieldRef": ["field-literal", "new_sessions", "type/Float"],
			"enabled": true
		}, {
			"name": "bounce_rate",
			"fieldRef": ["field-literal", "bounce_rate", "type/Float"],
			"enabled": true
		}, {
			"name": "unique_page_views",
			"fieldRef": ["field-literal", "unique_page_views", "type/BigInteger"],
			"enabled": true
		}, {
			"name": "x_cost",
			"fieldRef": ["field-literal", "x_cost", "type/Decimal"],
			"enabled": true
		}, {
			"name": "x_clicks",
			"fieldRef": ["field-literal", "x_clicks", "type/BigInteger"],
			"enabled": true
		}, {
			"name": "cpc",
			"fieldRef": ["field-literal", "cpc", "type/Float"],
			"enabled": true
		}, {
			"name": "cr",
			"fieldRef": ["field-literal", "cr", "type/Float"],
			"enabled": true
		}, {
			"name": "onumber",
			"fieldRef": ["field-literal", "onumber", "type/BigInteger"],
			"enabled": true
		}],
		"table.pivot_column": "x_date",
		"table.cell_column": "onumber",
		"table.column_formatting": [{
			"columns": ["Date"],
			"type": "single",
			"operator": "contains",
			"value": "Total",
			"color": "#F9D45C",
			"highlight_row": true
		}, {
			"columns": ["Date"],
			"type": "single",
			"operator": "contains",
			"value": "YT",
			"color": "#88BF4D",
			"highlight_row": true
		}],
		"table.column_widths": [null, null, null, null, null, null, 112, null, null, null, null, null, null, null, null, null, null, null, 115, null, null, null, null, 114, null, 96],
		"column_settings": {
			"[\"name\",\"% New Sessions\"]": {
				"number_style": "percent",
				"decimals": 1
			},
			"[\"name\",\"cr\"]": {
				"number_style": "percent",
				"column_title": "% CR",
				"decimals": 2
			},
			"[\"name\",\"% Man. Orders\"]": {
				"number_style": "percent",
				"decimals": 1
			},
			"[\"name\",\"new_sessions\"]": {
				"column_title": "% New Sessions",
				"number_style": "percent",
				"decimals": 2
			},
			"[\"name\",\"x_cost\"]": {
				"column_title": "Cost"
			},
			"[\"name\",\"ø CM2\"]": {
				"suffix": " €",
				"decimals": 2
			},
			"[\"name\",\"% XXX\"]": {
				"number_style": "percent",
				"decimals": 1
			},
			"[\"name\",\"# Orders YOY\"]": {
				"number_style": "percent",
				"decimals": 1
			},
			"[\"name\",\"% Rep. Orders\"]": {
				"number_style": "percent",
				"decimals": 1
			},
			"[\"name\",\"ø CPC\"]": {
				"suffix": " €"
			},
			"[\"name\",\"% Rep. Cust.\"]": {
				"number_style": "percent",
				"decimals": 2
			},
			"[\"name\",\"CM1\"]": {
				"suffix": " €",
				"decimals": 2
			},
			"[\"name\",\"ø Order Size\"]": {
				"suffix": " €",
				"decimals": 2
			},
			"[\"name\",\"cpc\"]": {
				"column_title": "ø CPC"
			},
			"[\"name\",\"CM2\"]": {
				"suffix": " €",
				"decimals": 2
			},
			"[\"name\",\"onumber\"]": {
				"column_title": "Orders"
			},
			"[\"name\",\"Spend\"]": {
				"suffix": " €",
				"decimals": 2
			},
			"[\"name\",\"bounce_rate\"]": {
				"column_title": "Bounce Rate",
				"number_style": "percent",
				"decimals": 2
			},
			"[\"name\",\"B2B CM1\"]": {
				"suffix": " €"
			},
			"[\"name\",\"Year\"]": {
				"number_separators": "."
			},
			"[\"name\",\"CM2 YOY\"]": {
				"number_style": "percent",
				"decimals": 1
			},
			"[\"name\",\"unique_page_views\"]": {
				"column_title": "Unique Page Views",
				"number_style": "decimal"
			},
			"[\"name\",\"GOV YOY\"]": {
				"number_style": "percent",
				"decimals": 1
			},
			"[\"name\",\"% CM2\"]": {
				"number_style": "percent",
				"decimals": 1
			},
			"[\"name\",\"% CR\"]": {
				"number_style": "percent",
				"decimals": 1
			},
			"[\"name\",\"% Rep. B2B Orders\"]": {
				"number_style": "percent",
				"decimals": 1
			},
			"[\"name\",\"€ GOV\"]": {
				"suffix": " €",
				"column_title": "GOV"
			},
			"[\"name\",\"x_date_placed\"]": {
				"column_title": "Year",
				"time_enabled": null,
				"date_style": "MMMM D, YYYY",
				"number_separators": "."
			},
			"[\"name\",\"ø CM1\"]": {
				"suffix": " €",
				"decimals": 2
			},
			"[\"name\",\"GOV MOM\"]": {
				"number_style": "percent",
				"decimals": 1
			},
			"[\"name\",\"Bounce Rate\"]": {
				"number_style": "percent",
				"decimals": 1
			},
			"[\"name\",\"GOV\"]": {
				"suffix": " €",
				"decimals": 2
			},
			"[\"name\",\"# Orders MOM\"]": {
				"number_style": "percent",
				"decimals": 1
			},
			"[\"name\",\"x_clicks\"]": {
				"column_title": "Clicks"
			},
			"[\"name\",\"% CM1\"]": {
				"number_style": "percent",
				"decimals": 1
			},
			"[\"name\",\"ROI\"]": {
				"decimals": 2
			},
			"[\"name\",\"Date\"]": {
				"time_enabled": null,
				"date_style": "MMMM D, YYYY"
			},
			"[\"name\",\"CM1 YOY\"]": {
				"number_style": "percent",
				"decimals": 1
			},
			"[\"name\",\"B2B € CM1\"]": {
				"suffix": " €",
				"decimals": 2
			},
			"[\"name\",\"% Cancelled\"]": {
				"number_style": "percent",
				"decimals": 1
			},
			"[\"name\",\"% GOV B2B\"]": {
				"number_style": "percent",
				"decimals": 1
			},
			"[\"name\",\"B2B % CM1\"]": {
				"number_style": "percent",
				"decimals": 1
			},
			"[\"name\",\"sessions\"]": {
				"column_title": "Sessions"
			},
			"[\"name\",\"ø CAC\"]": {
				"suffix": " €",
				"decimals": 2
			}
		}
	},
	"collection": {
		"authority_level": null,
		"description": null,
		"archived": false,
		"slug": "XXX",
		"color": "#509EE3",
		"name": "XXX",
		"personal_owner_id": null,
		"id": 26,
		"location": "/30/",
		"namespace": null
	},
	"created_at": "2021-05-13T11:48:07.437989Z",
	"public_uuid": null
}
```
(some things redacted with `XXX`)

**Comment by flamber** [comment] 2022-01-23 11:21
@ds-clearago You'll need to send unredacted version to me, I cannot reproduce - my username `@metabase.com`
