### ISSUE TITLE
Field Filters broken on 0.39.0.1 when working from Saved Question

### ISSUE THREAD

**Issue by lukedappleton** [metabase/metabase#15841] opened 2021-04-27 21:55 UTC
**Describe the bug**

I currently have many dashboards that have Category filters from saved questions. When we upgraded to the latest version of 0.39.0.1, these filters all no longer worked. When I clicked on the filter that was still there, none of the saved questions had the particular column chosen anymore and were just blank. It also would not give me the option to select these columns anymore as it looks like it no longer recognized these text fields as Category from the saved questions.

I wish I had screenshots and logs, but we downgraded in a hurry yesterday after we found this issue as it broke all of our dashboards in our applications. We are going to create a test instance in a week or so to test new MB releases before deploying to production, so can probably provide more information then. I primarily just wanted to post this here in case anybody else was experiencing the same problem. 

I am not sure if it is related to this issue https://github.com/metabase/metabase/issues/15352 , but thought I would include the link in case it was as it also referenced Saved Questions. 

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information about your Metabase Installation:**

Docker on ECS

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.x. OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

Severe as we downgraded our MB version. 

**Additional context**

**Comment by flamber** [comment] 2021-04-27 21:58
Going to close this until there's more information.

**Closed by flamber** 2021-04-27 21:58 UTC
Labels: .Needs Triage, Type:Bug

**Comment by lukedappleton** [comment] 2021-06-11 16:21
We spun up a staging instance and have monitored the past several releases and have run into the same issue in each upgrade. 

Screenshots 

[https://ibb.co/nQ1T1y1](url)
[https://ibb.co/9wpnjRm](url)
[https://ibb.co/R9bwqKM](url)
[https://ibb.co/8jswz7F](url)

In the first screenshot, we can see the category icon next to Member Type. In the second screenshot, you can see I am in edit mode and that the member type column has been chosen for the Weekly Active Users graphic.

When we upgrade, the member type icon changes to Aa (as seen in the third link) and when I click into edit, you can see in the fourth link that it says no columns are available to filter on. What is strange is that my 60 or so existing dashboards, when I actually put a member type in the staging environment into the filter, it filters accurately. But when I try and create any new dashboards, I run into the problem where I am not able to select that column anymore which is strange.

Below is my basic setup info for the staging environment. Any help would be appreciated!

`{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.14.231-173.361.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-27",
      "tag": "v0.39.3",
      "branch": "release-x.39.x",
      "hash": "598a112"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

**Comment by flamber** [comment] 2021-06-11 20:39
@lukedappleton 
Nothing normally gets fixed automatically unless it's properly reported and with steps-to-reproduce.
It sounds like some combination of #13186 (make sure to read my comment) or #12985, but without much more details and logs, then it will be close to impossible to know what's going on or how to fix it.
To begin with:
1. Which version did you upgrade from?
2. Can you reproduce with Sample Dataset? If yes, great, then provide the steps. If no, then it sounds like it's something specific to the field and the response data from `/api/field/:id` (where :id is the field ID) is needed.

**Comment by lukedappleton** [comment] 2021-06-14 20:52
@flamber 
1. We are still on .38.3 which was the last version before this occurred. We always kept our MB version up to date and haven't had an issue in the past year or so. 
2. I was not able to reproduce using this basic query in our staging environment/current production environment:

`SELECT SUM(subtotal) AS total_spent,
       name,
       source
FROM orders
INNER JOIN people on orders.user_id = people.id
GROUP BY name, source
ORDER BY total_spent DESC`

I used that in a native SQL question and then pressed Ask Question ->> Simple Question and then just pressed save and added it to a dashboard. Then pressed categories ->> and was able to view the last two columns as potential field filters in both instances. This is the exact same procedure I follow in our production environment- it looks like [#13186 ](https://github.com/metabase/metabase/issues/13186) ferarnoled mentioned that it only occured to him on more complex queries. 

I was looking in the inspector and noticed this in the staging console which I did not see in our production .38.3 instance: [https://ibb.co/CHmmymJ](url)

This kind of seems like what you were referencing in your response in the first linked issue. Apart from that, when I went into Network in the Inspector in Firefox, I did see some 404 errors with API endpoint does not exist. I also spotted some of the same 404's in our production environment so not sure if it is relevant.

**Comment by flamber** [comment] 2021-06-20 18:33
@lukedappleton 
I think too many different things are going on at the same time. You are likely seeing multiple different issues, like #15725.
I provided a detailed comment on the reason, and a simple reproduction, so no, it happens on any queries https://github.com/metabase/metabase/issues/13186#issuecomment-683830860
But without steps-to-reproduce or complete information about your questions and fields used, then it's impossible to guess.

**Comment by lukedappleton** [comment] 2021-06-29 17:41
I agree- I think it is a multitude of things currently and I appreciate the help. Just going to post this here as I found this in the logs. If this doesn't help, then I'll probably cease to post unless somebody else has a similar issue. Thanks again! @flamber 

```
[6f68959e-7f91-4ea6-be8e-bc783d345b98] 2021-06-29T11:35:22-06:00 INFO metabase.query-processor.middleware.cache Query took 2.4 s to run; minimum for cache eligibility is 1000.0 ms
[6f68959e-7f91-4ea6-be8e-bc783d345b98] 2021-06-29T11:35:22-06:00 INFO metabase.query-processor.middleware.cache Caching results for next time for query with hash "9b5d8dd8". 💾
[6f68959e-7f91-4ea6-be8e-bc783d345b98] 2021-06-29T11:35:22-06:00 DEBUG metabase.server.middleware.log POST /api/card/2756/query 202 [ASYNC: completed] 5.4 s (13 DB calls) App DB connections: 1/30 Jetty threads: 2/50 (47 idle, 0 queued) (155 total active threads) Queries in flight: 11 (0 queued)
[6f68959e-7f91-4ea6-be8e-bc783d345b98] 2021-06-29T11:35:23-06:00 INFO metabase.query-processor.middleware.cache Query took 1.5 s to run; minimum for cache eligibility is 1000.0 ms
[6f68959e-7f91-4ea6-be8e-bc783d345b98] 2021-06-29T11:35:23-06:00 INFO metabase.query-processor.middleware.cache Caching results for next time for query with hash "a0b55d7c". 💾
[6f68959e-7f91-4ea6-be8e-bc783d345b98] 2021-06-29T11:35:23-06:00 DEBUG metabase.server.middleware.log POST /api/card/2835/query 202 [ASYNC: completed] 5.9 s (13 DB calls) App DB connections: 2/30 Jetty threads: 2/50 (47 idle, 0 queued) (155 total active threads) Queries in flight: 10 (0 queued)
[6f68959e-7f91-4ea6-be8e-bc783d345b98] 2021-06-29T11:35:24-06:00 WARN metabase.server.middleware.log GET /api/field/field%2Cmember_type%2C%5Bobject%20Object%5D 404 231.6 µs (0 DB calls) 
"API endpoint does not exist."
```
