### ISSUE TITLE
Embedded dashboards filters converting varchar to int

### ISSUE THREAD

**Issue by cedmo8** [metabase/metabase#46300] opened 2024-07-30 20:30 UTC
**Describe the bug**
Since updating from version 0.50.13 (currently 0.50.17) all of the static embedded dashboards I have an issue with their filters.

Specifically there is a filter called CompanyNumber coming from SQL Server as a varchar(8) and set as a entity key in metabase metadata (changing this to a few diffrent options had no effect), many of the records are numerical strings e.g. '12345678' but some have letters e.g. 'SC123456'.

On the embedded dashboard there is a filter for CompanyNumber that is linked to several cards, when a value is selected that is purely numerical e.g. '12345678' every card that is linked to that filter show the error "There was a problem displaying this chart."

The logs indicate that the embedded version of the dashboard is converting the string value of '12345678' in the filter to an int and then passing it to the cards that throw an error as the date type of int is incompatible with the underlying query.

The issue does not occur if the filter is set to a value that has letters e.g. 'SC123456', nor does it occur in public links or when browsing the dashboard directly.

**Logs**
[cb63b40f-e723-4668-8cf6-5b4d95ab26ca] 2024-07-30T21:16:43+01:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: An error occurred during the current command (Done status 0). Conversion failed when converting the varchar value 'CE029299' to data type int.

```json
{:database_id 13,
 :started_at #t "2024-07-30T20:16:43.437515Z[GMT]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error reducing result rows: An error occurred during the current command (Done status 0). Conversion failed when converting the varchar value 'CE029299' to data type int.",
   :stacktrace
   ["--> query_processor.pipeline$_STAR_reduce_STAR_$fn__56905.invoke(pipeline.clj:74)"
    "query_processor.pipeline$_STAR_reduce_STAR_.invokeStatic(pipeline.clj:62)"
    "query_processor.pipeline$_STAR_reduce_STAR_.invoke(pipeline.clj:49)"
    "query_processor.middleware.cache$run_query_with_cache$reduce_SINGLEQUOTE___70094$fn__70095.invoke(cache.clj:214)"
    "query_processor.middleware.cache.impl$do_with_serialization.invokeStatic(impl.clj:83)"
    "query_processor.middleware.cache.impl$do_with_serialization.invoke(impl.clj:54)"
    "query_processor.middleware.cache.impl$do_with_serialization.invokeStatic(impl.clj:73)"
    "query_processor.middleware.cache.impl$do_with_serialization.invoke(impl.clj:54)"
    "query_processor.middleware.cache$run_query_with_cache$reduce_SINGLEQUOTE___70094.invoke(cache.clj:210)"
    "query_processor.pipeline$_STAR_run_STAR_$respond__56917.invoke(pipeline.clj:95)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__81863.invoke(execute.clj:724)"
    "driver.sql_jdbc.execute$fn__81656$fn__81657.invoke(execute.clj:397)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:337)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:320)"
    "driver.sql_jdbc.execute$fn__81656.invokeStatic(execute.clj:391)"
    "driver.sql_jdbc.execute$fn__81656.invoke(execute.clj:389)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:707)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:693)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:704)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:693)"
    "driver.sql_jdbc$fn__109630.invokeStatic(sql_jdbc.clj:78)"
    "driver.sql_jdbc$fn__109630.invoke(sql_jdbc.clj:76)"
    "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47)"
    "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34)"
    "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:97)"
    "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:90)"
    "query_processor.execute$run.invokeStatic(execute.clj:61)"
    "query_processor.execute$run.invoke(execute.clj:55)"
    "query_processor.execute$add_native_form_to_result_metadata$fn__70117.invoke(execute.clj:24)"
    "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__70122.invoke(execute.clj:35)"
    "query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:215)"
    "query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:188)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___70108.invoke(cache.clj:241)"
    "query_processor.middleware.permissions$check_query_permissions$fn__64090.invoke(permissions.clj:118)"
    "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__64700.invoke(enterprise.clj:51)"
    "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__64710.invoke(enterprise.clj:64)"
    "query_processor.execute$execute$fn__70149.invoke(execute.clj:93)"
    "query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:225)"
    "query_processor.setup$do_with_qp_setup.invoke(setup.clj:216)"
    "query_processor.execute$execute.invokeStatic(execute.clj:92)"
    "query_processor.execute$execute.invoke(execute.clj:88)"
    "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:47)"
    "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:43)"
    "query_processor.middleware.enterprise$fn__64727$handle_audit_app_internal_queries__64728$fn__64730.invoke(enterprise.clj:96)"
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__64738.invoke(enterprise.clj:103)"
    "query_processor.middleware.process_userland_query$process_userland_query_middleware$fn__75925.invoke(process_userland_query.clj:186)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__75994.invoke(catch_exceptions.clj:128)"
    "query_processor$process_query$fn__76031.invoke(query_processor.clj:78)"
    "query_processor.setup$do_with_canceled_chan$fn__65142.invoke(setup.clj:189)"
    "query_processor.setup$do_with_database_local_settings$fn__65137.invoke(setup.clj:181)"
    "query_processor.setup$do_with_driver$fn__65132$fn__65133.invoke(setup.clj:166)"
    "driver$do_with_driver.invokeStatic(driver.clj:105)"
    "driver$do_with_driver.invoke(driver.clj:100)"
    "query_processor.setup$do_with_driver$fn__65132.invoke(setup.clj:165)"
    "query_processor.setup$do_with_metadata_provider$fn__65125$fn__65128.invoke(setup.clj:151)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:171)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:151)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:160)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:151)"
    "query_processor.setup$do_with_metadata_provider$fn__65125.invoke(setup.clj:150)"
    "query_processor.setup$do_with_resolved_database$fn__65119.invoke(setup.clj:128)"
    "query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:232)"
    "query_processor.setup$do_with_qp_setup.invoke(setup.clj:216)"
    "query_processor$process_query.invokeStatic(query_processor.clj:76)"
    "query_processor$process_query.invoke(query_processor.clj:69)"
    "query_processor.card$process_query_for_card_default_qp.invokeStatic(card.clj:170)"
    "query_processor.card$process_query_for_card_default_qp.invoke(card.clj:166)"
    "api.public$process_query_for_card_with_id_run_fn$run__98466$fn__98467$fn__98468.invoke(public.clj:140)"
    "server.middleware.session$do_with_current_user.invokeStatic(session.clj:425)"
    "server.middleware.session$do_with_current_user.invoke(session.clj:408)"
    "api.public$process_query_for_card_with_id_run_fn$run__98466$fn__98467.invoke(public.clj:139)"
    "query_processor.streaming$_streaming_response$fn__68592$fn__68593$fn__68594.invoke(streaming.clj:175)"
    "query_processor.streaming$_streaming_response$fn__68592$fn__68593.invoke(streaming.clj:174)"
    "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:165)"
    "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:152)"
    "query_processor.streaming$_streaming_response$fn__68592.invoke(streaming.clj:171)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:68)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:66)"
    "async.streaming_response$do_f_async$task__52331.invoke(streaming_response.clj:87)"],
   :error_type :qp,
   :ex-data {:type :qp}}],
 :action_id nil,
 :state "S0001",
 :error_type :qp,
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true, :ignore-cached-results? false, :userland-query? true},
  :cache-strategy {:multiplier 10, :min_duration_ms 3000, :type :ttl, :avg-execution-ms 0},
  :viz-settings
  {:gauge.segments [{:color "#EDF2F5", :label "", :max 50000, :min 0}],
   :table.cell_column "AVG Turnover",
   :table.columns [{:name "avg", :enabled true}],
   :table.pivot_column "Accounts Count",
   :column_settings
   {"[\"name\",\"sum\"]" {:prefix "£"},
    "[\"ref\",[\"field\",14781,null]]"
    {:link_url "https://find-and-update.company-information.service.gov.uk/company/{{Company Number}}", :view_as nil}}},
  :database 13,
  :query {:limit 1, :source-table 845, :aggregation [[:avg [:field 14904 {:base-type :type/BigInteger}]]]},
  :parameters
  [{:type :string/=,
    :value [1234567],
    :slug "company_number",
    :id "3d8d1af0",
    :target [:dimension [:field 14907 {:base-type :type/Text}]]}]},
 :native
 {:query
  "SELECT TOP(1) AVG(\"dbo\".\"TargetAccounts\".\"AVG Turnover\") AS \"avg\" FROM \"dbo\".\"TargetAccounts\" WHERE \"dbo\".\"TargetAccounts\".\"Company Number\" = 1234567",
  :params nil},
 :status :failed,
 :class com.microsoft.sqlserver.jdbc.SQLServerException,
 :stacktrace
 ["com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:261)"
  "com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer$FetchBufferTokenHandler.onDone(SQLServerResultSet.java:5455)"
  "com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:103)"
  "com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:42)"
  "com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer.nextRow(SQLServerResultSet.java:5558)"
  "com.microsoft.sqlserver.jdbc.SQLServerResultSet.fetchBufferNext(SQLServerResultSet.java:1821)"
  "com.microsoft.sqlserver.jdbc.SQLServerResultSet.next(SQLServerResultSet.java:1079)"
  "com.mchange.v2.c3p0.impl.NewProxyResultSet.next(NewProxyResultSet.java:685)"
  "--> driver.sql_jdbc.execute$row_thunk$row_thunk_STAR___81842.invoke(execute.clj:644)"
  "query_processor.reducible$reducible_rows$reify__56930.reduce(reducible.clj:55)"
  "query_processor.pipeline$_STAR_reduce_STAR_$fn__56905.invoke(pipeline.clj:63)"
  "query_processor.pipeline$_STAR_reduce_STAR_.invokeStatic(pipeline.clj:62)"
  "query_processor.pipeline$_STAR_reduce_STAR_.invoke(pipeline.clj:49)"
  "query_processor.middleware.cache$run_query_with_cache$reduce_SINGLEQUOTE___70094$fn__70095.invoke(cache.clj:214)"
  "query_processor.middleware.cache.impl$do_with_serialization.invokeStatic(impl.clj:83)"
  "query_processor.middleware.cache.impl$do_with_serialization.invoke(impl.clj:54)"
  "query_processor.middleware.cache.impl$do_with_serialization.invokeStatic(impl.clj:73)"
  "query_processor.middleware.cache.impl$do_with_serialization.invoke(impl.clj:54)"
  "query_processor.middleware.cache$run_query_with_cache$reduce_SINGLEQUOTE___70094.invoke(cache.clj:210)"
  "query_processor.pipeline$_STAR_run_STAR_$respond__56917.invoke(pipeline.clj:95)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__81863.invoke(execute.clj:724)"
  "driver.sql_jdbc.execute$fn__81656$fn__81657.invoke(execute.clj:397)"
  "driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:337)"
  "driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:320)"
  "driver.sql_jdbc.execute$fn__81656.invokeStatic(execute.clj:391)"
  "driver.sql_jdbc.execute$fn__81656.invoke(execute.clj:389)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:707)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:693)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:704)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:693)"
  "driver.sql_jdbc$fn__109630.invokeStatic(sql_jdbc.clj:78)"
  "driver.sql_jdbc$fn__109630.invoke(sql_jdbc.clj:76)"
  "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47)"
  "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34)"
  "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:97)"
  "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:90)"
  "query_processor.execute$run.invokeStatic(execute.clj:61)"
  "query_processor.execute$run.invoke(execute.clj:55)"
  "query_processor.execute$add_native_form_to_result_metadata$fn__70117.invoke(execute.clj:24)"
  "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__70122.invoke(execute.clj:35)"
  "query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:215)"
  "query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:188)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___70108.invoke(cache.clj:241)"
  "query_processor.middleware.permissions$check_query_permissions$fn__64090.invoke(permissions.clj:118)"
  "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__64700.invoke(enterprise.clj:51)"
  "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__64710.invoke(enterprise.clj:64)"
  "query_processor.execute$execute$fn__70149.invoke(execute.clj:93)"
  "query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:225)"
  "query_processor.setup$do_with_qp_setup.invoke(setup.clj:216)"
  "query_processor.execute$execute.invokeStatic(execute.clj:92)"
  "query_processor.execute$execute.invoke(execute.clj:88)"
  "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:47)"
  "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:43)"
  "query_processor.middleware.enterprise$fn__64727$handle_audit_app_internal_queries__64728$fn__64730.invoke(enterprise.clj:96)"
  "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__64738.invoke(enterprise.clj:103)"
  "query_processor.middleware.process_userland_query$process_userland_query_middleware$fn__75925.invoke(process_userland_query.clj:186)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__75994.invoke(catch_exceptions.clj:128)"
  "query_processor$process_query$fn__76031.invoke(query_processor.clj:78)"
  "query_processor.setup$do_with_canceled_chan$fn__65142.invoke(setup.clj:189)"
  "query_processor.setup$do_with_database_local_settings$fn__65137.invoke(setup.clj:181)"
  "query_processor.setup$do_with_driver$fn__65132$fn__65133.invoke(setup.clj:166)"
  "driver$do_with_driver.invokeStatic(driver.clj:105)"
  "driver$do_with_driver.invoke(driver.clj:100)"
  "query_processor.setup$do_with_driver$fn__65132.invoke(setup.clj:165)"
  "query_processor.setup$do_with_metadata_provider$fn__65125$fn__65128.invoke(setup.clj:151)"
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:171)"
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:151)"
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:160)"
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:151)"
  "query_processor.setup$do_with_metadata_provider$fn__65125.invoke(setup.clj:150)"
  "query_processor.setup$do_with_resolved_database$fn__65119.invoke(setup.clj:128)"
  "query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:232)"
  "query_processor.setup$do_with_qp_setup.invoke(setup.clj:216)"
  "query_processor$process_query.invokeStatic(query_processor.clj:76)"
  "query_processor$process_query.invoke(query_processor.clj:69)"
  "query_processor.card$process_query_for_card_default_qp.invokeStatic(card.clj:170)"
  "query_processor.card$process_query_for_card_default_qp.invoke(card.clj:166)"
  "api.public$process_query_for_card_with_id_run_fn$run__98466$fn__98467$fn__98468.invoke(public.clj:140)"
  "server.middleware.session$do_with_current_user.invokeStatic(session.clj:425)"
  "server.middleware.session$do_with_current_user.invoke(session.clj:408)"
  "api.public$process_query_for_card_with_id_run_fn$run__98466$fn__98467.invoke(public.clj:139)"
  "query_processor.streaming$_streaming_response$fn__68592$fn__68593$fn__68594.invoke(streaming.clj:175)"
  "query_processor.streaming$_streaming_response$fn__68592$fn__68593.invoke(streaming.clj:174)"
  "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:165)"
  "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:152)"
  "query_processor.streaming$_streaming_response$fn__68592.invoke(streaming.clj:171)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:68)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:66)"
  "async.streaming_response$do_f_async$task__52331.invoke(streaming_response.clj:87)"],
 :card_id 1229,
 :context :embedded-dashboard,
 :error
 "An error occurred during the current command (Done status 0). Conversion failed when converting the varchar value 'CE029299' to data type int.",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true, :ignore-cached-results? false, :userland-query? true},
  :cache-strategy {:multiplier 10, :min-duration-ms 3000, :type :ttl, :avg-execution-ms 0},
  :user-parameters
  [{:value [1234567],
    :type :string/=,
    :slug "company_number",
    :id "3d8d1af0",
    :target [:dimension [:field 14907 {:base-type :type/Text}]]}],
  :viz-settings
  {:gauge.segments [{:color "#EDF2F5", :label "", :max 50000, :min 0}],
   :table.cell_column "AVG Turnover",
   :table.columns [{:name "avg", :enabled true}],
   :table.pivot_column "Accounts Count",
   :column_settings
   {"[\"name\",\"sum\"]" {:prefix "£"},
    "[\"ref\",[\"field\",14781,null]]"
    {:link_url "https://find-and-update.company-information.service.gov.uk/company/{{Company Number}}", :view_as nil}}},
  :info
  {:context :embedded-dashboard,
   :card-id 1229,
   :card-name "Average Turnover 2",
   :dashboard-id 232,
   :visualization-settings
   {:gauge.segments [{:color "#EDF2F5", :label "", :max 50000, :min 0}],
    :table.cell_column "AVG Turnover",
    :table.columns [{:name "avg", :enabled true}],
    :table.pivot_column "Accounts Count",
    :column_settings
    {"[\"name\",\"sum\"]" {:prefix "£"},
     "[\"ref\",[\"field\",14781,null]]"
     {:link_url "https://find-and-update.company-information.service.gov.uk/company/{{Company Number}}"}}}},
  :database 13,
  :query
  {:limit 1,
   :source-table 845,
   :aggregation [[:aggregation-options [:avg [:field 14904 {:base-type :type/BigInteger}]] {:name "avg"}]],
   :filter
   [:=
    [:field 14907 {:base-type :type/Text}]
    [:value
     1234567
     {:base_type :type/Text,
      :effective_type :type/Text,
      :coercion_strategy nil,
      :semantic_type :type/PK,
      :database_type "varchar",
      :name "Company Number"}]]}},
 :data {:rows [], :cols []}}
```

**To Reproduce**
1. Create dataset that has some purely numerical values (mine is 95% numerical)
2. Create a dashboard that has a filter on that column
3. Create a card that is linked to that filter
4. Staticly embed the dashboard
5. load the embeded dashboard and insert a numerical value into the filter
6. Get error

**Expected behavior**
Cards would apply the filter to their underlying data the same as direct view & publick links

**Screenshots**
![image](https://github.com/user-attachments/assets/6b6cfc07-5c1f-4fbd-b8a2-6dda8af30f93)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**
Data source is a MS SQL Server view and the issue has afffected the last few versions after 0.50.13 (tested on 0.50.16, 0.50.17)

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.15.0-117-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.37-0ubuntu0.22.04.3"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-07-26",
      "tag": "v0.50.17",
      "hash": "afd6b17"
    },
    "settings": {
      "report-timezone": "GMT"
    }
  }
}
```

**Comment by cedmo8** [comment] 2024-07-31 08:55
0.50.18 (patch release) looks like it has a fix for this "Text Filters turn number like entries into numeric when filtering on static embedding", I will test tonight.

**Comment by noahmoss** [comment] 2024-08-02 12:41
Closing as dupe of https://github.com/metabase/metabase/issues/46240. @cedmo8 Please open a new issue if you continue to see problems

**Closed by noahmoss** 2024-08-02 12:41 UTC
