### ISSUE TITLE
Dashboard Click doesn't work if use Custom Question

### ISSUE THREAD

**Issue by kalyagin-private** [metabase/metabase#28020] opened 2023-02-02 12:33 UTC
**Describe the bug**
I created Qestion based on Clickhouse table. After that I created chart based on the question and added on dashboard. Its works fine, but when I click on this chart I get error in browser console and "Drilldown" doesn't work. Nothing happens. I can't see context menu for example(See Screenshot below) . I tried add "Move to destination" and chose the same question, and Drilldown start work, but after refresh page (press F5) - it's broken again

**Logs**
```
drilldown.js:412 Uncaught TypeError: Cannot read properties of undefined (reading 'fields')
    at drilldown.js:412:58
    at J (drilldown.js:431:16)
    at question (zoom-drill.js:9:21)
    at Se.drills (ZoomDrill.jsx:8:8)
    at Mode.ts:33:50
    at Array.flatMap (<anonymous>)
    at e.value (Mode.ts:33:33)
    at s.value (Visualization.jsx:243:14)
    at Visualization.jsx:282:12
    at SVGCircleElement.t (apply_tooltips.js:353:11)
```

**To Reproduce**
1. Create question
2. Create chart for question
3. Add chart on dashboard
4. Click on this chart
5. See error

**Expected behavior**
When I click on chart I must see "context menu". Expample:
![image](https://user-images.githubusercontent.com/3599574/216325073-7dbeaa8a-0d36-40f0-899e-68700811c1ce.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/3599574/216321732-e6902483-a051-46ec-bc4a-e651bf813773.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "ru-RU",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.17+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.17",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.17+8",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.42.2.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Europe/Moscow"
  },
  "metabase-info": {
    "databases": [
      "clickhouse",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.1 (Debian 14.1-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-12-07",
      "tag": "v0.45.1",
      "branch": "release-x.45.x",
      "hash": "019d31c"
    },
    "settings": {
      "report-timezone": "Europe/Moscow"
    }
  }
}
```

**Additional context**
A few weeks ago we updated Metabase, before we use ~0.41.5 version and my case worked fine.

**Comment by paoliniluis** [comment] 2023-02-02 13:42
Can you upgrade to v45.2.1 and check if this issue is still there?

**Comment by paoliniluis** [comment] 2023-02-03 00:30
Also, can you reproduce this with the sample dataset?

**Comment by paoliniluis** [comment] 2023-03-05 21:28
Closing due to no answer

**Closed** 2023-03-05 21:28 UTC
Labels: Type:Bug, .Needs Triage
