### ISSUE TITLE
Date filter "current month" not working with Microsoft SQL Server (2008)

### ISSUE THREAD

**Issue by matsc-h** [metabase/metabase#5983] opened 2017-09-15 12:50 UTC
- Your browser and the version: FF 54 / 55 and Chrome 60.x
- Your operating system: Windows 10
- Your databases: Microsoft SQL Server
- Metabase version: v0.25.2 Built on 2017-08-09
- Metabase hosting environment: .jar running on Windows Server 2012R2
- Metabase internal database: H2

![Screenshot](https://user-images.githubusercontent.com/31989534/30482358-f87c2150-9a22-11e7-8e8c-c63cedd59d4e.png)

The above filter is using the FORMAT function which has only been introduced in SQL Server 2012. 
Any chance that this could be changed from 
`AND CAST(format(\"dbo\".\"table\".\"datefield\", 'yyyy-MM-01') AS datetime) = CAST(format(getutcdate(), 'yyyy-MM-01') AS datetime))`
to
`datepart(mm, datefield) = datepart(mm, getutcdate()))` 
?

I believe this should net the same results 

unfortunately upgrading to a newer SQL Server version is currently not possible for us :(

**Comment by jornh** [comment] 2017-09-15 14:24
Just another Metabase user here that happened to stumble across the same a while ago. At that point in time I just worked around it by simply stating a day range - which can work for a one off query, but of course not for building dashboards etc.

Guess it could relate to this line https://github.com/metabase/metabase/blob/v0.25.2/src/metabase/driver/sqlserver.clj#L100 in the SqlServer driver. But you're referring to `wk` ([week](https://docs.microsoft.com/en-us/sql/t-sql/functions/datepart-transact-sql)) in your **to** suggestion, shouldn't that rather be `mm` for month?

**Comment by matsc-h** [comment] 2017-09-15 14:46
Yea I meant mm instead of wk. Fixed in the original post, thanks. :) 
Friday afternoon, seems like my brain checked out a few hours early

**Comment by salsakran** [comment] 2017-09-25 22:29
this is a dupe of #2330

The core team really doesn't have the bandwidth to support a 9 year old version of SQL Server. We'll take a PR that fixes this, but can't commit to supporting old DBs indefinitely.

**Closed by salsakran** 2017-09-25 22:29 UTC
Labels: Database/SQLServer
