### ISSUE TITLE
Conditional Formatting for Dots on Line Chart

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#46653] opened 2024-08-08 18:53 UTC
**Is your feature request related to a problem? Please describe.**
We'd like to be able to plot multiple lines on a line chart and, for each line, change the color of the plots points based on a KPI. So, for example, one line might have conditional formatting for the plot points that indicate under 10% is green and over 10% is red. This give s a visual for when KPIs were hit or missed over time across multiple series.

**Describe the solution you'd like**
We'd like to apply conditional formatting to change the color of the dots/plot points of a line chart.

**Describe alternatives you've considered**
There is a workaround to do this in PowerBI but we would like similar functionality in Metabase.

**Comment by paoliniluis** [comment] 2024-11-05 15:46
duplicate of https://github.com/metabase/metabase/issues/11461

**Closed by paoliniluis** 2024-11-05 15:46 UTC
Labels: Type:New Feature, Visualization/Charts
