### ISSUE TITLE
collections without subcollections have an "expand" arrow

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#14753] opened 2021-02-10 20:43 UTC
**Describe the bug**

Empty collections show arrows misleadingly indicating they can expand and contain sub collections

**To Reproduce**

Add a new collection and it will appear with an expansion arrow even though it does not contain any sub collections

**Expected behavior**

No arrow, indicating it is not expandable

**Screenshots**

<img width="886" alt="image" src="https://user-images.githubusercontent.com/6377293/107569205-a82d7e00-6bad-11eb-88b4-3bc873d6fe21.png">

Note there is one more state that isn't indicated as well. You can see here that `A look at your People table` has questions in it even though it has no subcollections. This distinction is not made from a collection that has no questions in it. Perhaps a lighter font weight to indicate there are no questions contained in a collection?

**Information about your Metabase Installation:**

`v0.38.0-rc5`

**Severity**

super low

**Comment by flamber** [comment] 2021-02-10 20:50
This is a regression since rc4 - I'm inclined to give it P2, since it makes it difficult to understand which collections has children.

**Comment by mazameli** [comment] 2021-02-18 00:58
Yeah, bumping this up to P2 — this sucks.

**Comment by kulyk** [comment] 2021-04-15 17:21
Fixed by #15626

**Closed by kulyk** 2021-04-15 17:21 UTC
Labels: .Reproduced, Organization/Collections, Priority:P2, Type:Bug
