### ISSUE TITLE
Mismatched timeseries axes and labels in a Bar chart

### ISSUE THREAD

**Issue by mmcf** [metabase/metabase#8413] opened 2018-08-28 09:28 UTC
Using a custom question against a BigQuery view, I see a discrepancy between the timestamps reported in the _axes_ and _labels_ of a **Bar** chart.  Incidentally, a **Row** chart displays correctly against the same data shows matched labels correctly.

- Browser: Chrome v68.0.3440.106 (64-bit)
- OS: OS X (v10.13.4)
- Databases: Google BigQuery
- Metabase version: 0.30.0 (using Docker image `metabase/metabase:v0.30.0`)
- Hosted: on Google Kubernetes engine
- Internal database: hosted via Google Cloud SQL PostgreSQL

**Question definition**

 ![question_definition](https://user-images.githubusercontent.com/6311525/44713169-7215e580-aaaa-11e8-82f9-65b6fc9e0f25.png)

**Bar Chart**
_Incorrectly showing events from 24th August against the 23rd axes label_

![bar_mismatched_labels](https://user-images.githubusercontent.com/6311525/44712803-89080800-aaa9-11e8-8ee9-88b964bd9b86.png)

**Row Chart**
_Correctly showing events from 24th August against the 24th axes label (apologies, the axes label is very feint)_
![row_correct_labels](https://user-images.githubusercontent.com/6311525/44712813-8dccbc00-aaa9-11e8-9ab0-c47b0b353498.png)

**Raw Data**

![rawdata_correct_dates](https://user-images.githubusercontent.com/6311525/44712844-a0df8c00-aaa9-11e8-8879-ade062a3325e.png)

**BigQuery - view data**
_Subset of data showing event_timestamp field stored as TIMESTAMP with timezone information_
![bigquery_view_timestamp](https://user-images.githubusercontent.com/6311525/44712966-f2881680-aaa9-11e8-8020-fe7a78aed798.png)

Having read through some of the other issues referencing timezones as a potential cause (e.g. issues 2340, 5246 and PR 7247), I can confirm that the Metabase server is running in UTC timezone, Metabase "Report Timezone" is UTC, and the underlying raw data in Bigquery is stored with UTC timezone.  My browser timezone is currently set as BST (GMT+1) - manually setting this to an earlier timezone (e.g. Azores/GMT) fixes the display of the Bar chart (bars then appear under the correct axis label).

**Comment by kakobrekla** [comment] 2019-01-29 12:00
It was suggested to me to add my observation of likely same bug.

I see an offset between the timestamps and labels on the x-axis. This affects `bar`, `line`, `area` and `line+bar` chart. Data found in `table` 'visualization' (as seen below) is correct.

- Browser: Chromium 67 (64-bit)
- OS: Ubuntu 17.10
- Databases: MariaDB 10.1
- Metabase version: v0.31.2 (running jar)
- Hosted: Debian stretch 9.6
- Internal database: MariaDB 10.1

**Question**
![metabase-question](https://user-images.githubusercontent.com/2829864/51906877-86e20680-23c5-11e9-9137-324f4690b73c.png)

**Result**
![metabase-bug](https://user-images.githubusercontent.com/2829864/51906257-0bcc2080-23c4-11e9-9f8d-39498ac8f18f.png)


Metabase jar is running with `JAVA_TIMEZONE=UTC` / `-Duser.timezone=UTC`, MariaDB is running in `UTC` zone, timestamp data is stored as unix timestamps.

**Database timezone**
![metabase-time-diff](https://user-images.githubusercontent.com/2829864/51906641-db38b680-23c4-11e9-80a7-42fc28644781.png)

**Comment by tlrobinson** [comment] 2019-08-23 23:50
Probably related to #5916 and/or #5246

**Comment by antoine-lizee** [comment] 2019-09-16 00:00
This is exactly the bug reported (and diagnosed) here: https://github.com/metabase/metabase/issues/5246#issuecomment-494425479

Honestly, I objectively don't understand why this has been deprioritized for so long. Isn't any user of Metabase relying on time axes? Are we the only company that actually takes MB seriously as a tool? What am I missing?

**Comment by smic-datalabs-von** [comment] 2019-10-28 02:55
Is there a workaround on this? This is quite an issue that might lead to misunderstanding of data.

**Comment by paulrosenzweig** [comment] 2019-10-28 13:12
@smic-datalabs-von there's no workaround but a fix is coming. We've updated how Metabase communicates timezone info in its internal API. The next release shouldn't have this issue. Sorry for the delay in getting this fixed!

**Comment by antoine-lizee** [comment] 2019-10-28 14:44
@smic-datalabs-von I shared a quick fix in my previous diagnosis of this problem there: #5246 . 
Basically, start another instance of chrome in a corresponding timezone.

**Comment by mazameli** [comment] 2019-11-28 00:19
I'm pretty certain this is a duplicate of https://github.com/metabase/metabase/issues/4245, which, as [I just noted there](https://github.com/metabase/metabase/issues/4245#issuecomment-559290162), is fixed in 0.33.6. Going to close this as such since I was able to repro this bug in 0.32.10, but it appears fixed for me in 0.33.6 and master. Please let me know if you're still experiencing this.

**Closed by mazameli** 2019-11-28 00:19 UTC
Labels: Misc/Timezones, Priority:P1, Type:Bug, Visualization/
