### ISSUE TITLE
Mongo nested field with same name as top level field

### ISSUE THREAD

**Issue by thomasleveil** [metabase/metabase#9684] opened 2019-04-03 22:23 UTC
While having Metabase figuring out nested fields on MongoDB document is neat, the way the flattening is done can bring confusing results. Take for instance the following document:

```json
{
    "_id": { "$oid": "5be9854e44429b000ddb94cc" },
    "status": "foo",
    "subObject": {"status": "bar"}
}
```
Metabase will present us two columns with the same name: `status`, with no help for us to figure out which one is which.

### Feature request

It would be very helpful if Metabase was able to name the column for the nested field `subObject.status` .

![image](https://user-images.githubusercontent.com/42300/55516955-2c884f00-566f-11e9-8e7f-79a190cfbca4.png)

### Context

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: MongoDB 3.6
- Metabase version: 0.32.1
- Metabase hosting environment: Docker
- Metabase internal database: H2

### Repeatable steps to reproduce the issue

Start the following Docker compose project to reproduce: https://github.com/thomasleveil/tmp-metabase-mongo-issue-columns

```shell
git clone https://github.com/thomasleveil/tmp-metabase-mongo-issue-columns mongo_nested_fields
cd mongo_nested_fields
# hack a bit docker-compose.yml to publish ports on your host
docker-compose up -d
```

**Comment by flamber** [comment] 2019-04-03 22:38
Hi @thomasleveil 
Pretty extensive reproduce tutorial :-)
Out of curiosity, what do you see in References (i.e. `https://metabase.example.com/reference/databases/X/tables/X/fields`), since it shows the "real" column name too. Just not sure how flattening is handled.
Related to #1611

**Comment by thomasleveil** [comment] 2019-04-04 06:50
![image](https://user-images.githubusercontent.com/42300/55535174-a98ae700-56b6-11e9-933b-1881ed189ea1.png)

**Comment by sergeyfilimonov** [comment] 2019-09-22 01:25
@thomasleveil hI! have you figured this out? it seems the problem is that Metabase is not supporting nested objects of Mongo.

**Comment by flamber** [comment] 2021-11-12 14:54
Closing in favor of #1611

**Closed by flamber** 2021-11-12 14:54 UTC
Labels: Type:UX, Database/Mongo, Administration/Metadata & Sync
