### ISSUE TITLE
Interactive dashboards with custom destination and nginx for reverse proxy fail!

### ISSUE THREAD

**Issue by happydentist** [metabase/metabase#18973] opened 2021-11-13 13:19 UTC
I issue the bug before #18928, and was close by Flamber.
He suggest to use the forum for questions and troubleshooting: https://discourse.metabase.com/

## The same problem was happydened that design interactive dashboards with customizing click behavior on the question of dashboards, go to a custom destination over column.
![metabase](https://user-images.githubusercontent.com/35398116/141645031-0377134b-9986-4b56-8dda-8e3bebf188a8.png)

**Comment by flamber** [comment] 2021-11-13 14:05
It's a duplicate of #10743 and #11684 and #12580 and #13602

Metabase does not officially support non-root locations. You'll have to make rewrites, like mentioned in the comments of the issues.

**Closed by flamber** 2021-11-13 14:05 UTC
Labels: Type:Bug, .Needs Triage
