### ISSUE TITLE
how to stop sync field-value ?

### ISSUE THREAD

**Issue by Liudon** [metabase/metabase#14181] opened 2020-12-23 11:52 UTC
![image](https://user-images.githubusercontent.com/5969707/102993393-12d01f00-4558-11eb-940c-cca9182be70e.png)

i choose the option "Never, I’ll do this manually if I need to",but it still sync field-value.

![image](https://user-images.githubusercontent.com/5969707/102993546-4e6ae900-4558-11eb-8351-0c02f0fc005d.png)

version: 0.32.9

**Comment by flamber** [comment] 2020-12-23 11:58
Hi @Liudon 
You cannot disable sync - the screenshot you are showing if for the scan. Duplicate of #10398
Latest release is 0.37.4

**Closed by flamber** 2020-12-23 11:58 UTC
