### ISSUE TITLE
When multiple users have the same email, but with different casing, then upgrading to 0.37 causes problems

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13890] opened 2020-11-25 14:18 UTC
**Describe the bug**
When the application database contains multiple users with the same email, but with different casing, then upgrading to 0.37+ causes different types of problems depending on which application database type used.

**To Reproduce H2**
1. Setup a new Metabase 0.36.8.2 on H2 and create two users with the same email, but different casing (eg. `test2@test.test` and `TEST2@test.test`)
2. Upgrade to 0.37.0.2 (or newer), and try to create another user (eg `another@test.test`), which fails with `Output of user->personal-collection does not match schema: �[0;33m (not (instance? metabase.models.collection.CollectionInstance nil)) �[0m`
There are also two new tables in the H2 after it has become corrupted - `CORE_USER_COPY_5_0` and `CORE_USER_COPY_5_1`.
This error will now be persistent on Admin > People, so it's not possible to view/edit/remove users anymore. It will require reverting to a backup. Or manual removing the newly created user from `CORE_USER` or adding a new collection referencing the newly created user in `COLLECTION`, as well as deleting the two new tables as well, and of course fix the users with similar email (lowercase all emails).

**To Reproduce Postgres**
1. Setup a new Metabase 0.36.8.2 on Postgres and create two users with the same email, but different casing (eg. `test2@test.test` and `TEST2@test.test`) and create an extra user with just uppercase (eg. `TEST3@test.test`).
2. Upgrade to 0.37.0.2 (or newer), and go to Admin > People. It has now lowercased `test3@test.test` (correct), but the user with email `TEST2@test.test` is not lowercased. And trying to login as `test2@test.test` will actually login as the user with `TEST2@test.test`

And on MySQL it depends on if collation is set to be case insensitive `utf8mb4_unicode_ci` (the default), then it's not even possible to generate the second user in step 1 on 0.36.8.2 (constraint error), but if collate was sensitive, then I think it behaves similar to Postgres.

**Additional context**
Do **not** use H2 in production - migrate away: https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html
Make sure to **always** have backups of the application database before upgrading, downgrading or doing any other major changes.
Caused by #3047
Related to #13739 at least with respect to Postgres step 2 - and related to #10961

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by bkrn** [comment] 2020-11-25 14:36
For what it's worth, I have opinions now!

I pulled down the source this morning to take a look at #13739. I assumed that all I needed to do was lower case the email on the way back from LDAP but after edits I ran into the problem you describe here.

Migrations 269 to 271 leave postgres users in a complicated state where the email column can be either citext or varchar and there may be duplicates of email when ignoring case (the issue here). 

If case doesn't matter I think you have to make the call and not allow duplicates (when ignoring case) and it you're going to use citext (I think you should) instead of lower I think you need to make the migration fail for users (like us) who hadn't given the application DB user permission to create extensions.

No doubt this will make the migration path harder for some users (like us) and I'm curious if you all see other ways forward.

As always, thanks for your work, Metabase is just fantastic.

**Comment by noahmoss** [comment] 2021-06-21 20:51
Did some digging and figured out the root cause of the issue on H2.

The migration introduced in 0.37.0 (https://github.com/metabase/metabase/blob/master/resources/migrations/000_migrations.yaml#L7803-L7806) tries to convert the `email` column of the `core_user` table to `varchar_ignorecase(254)`. If two users have the same case-insensitive email, this fails with the following error:
```
Error: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "CORE_USER_COPY_3_0_CONSTRAINT_4_INDEX_C ON PUBLIC.CORE_USER_COPY_3_0(EMAIL) VALUES (CAST('test@metabase.com' AS VARCHAR_IGNORECASE), 2)";
```

The new tables with `COPY` suffixes are apparently artifacts of the failed `ALTER TABLE` operation, according to https://github.com/h2database/h2database/issues/2157#issuecomment-539646024

Subsequently, when an admin tries to add a new user, Metabase tries to create a personal collection for the user (https://github.com/metabase/metabase/blob/master/src/metabase/models/collection.clj#L951-L955). This fails with the following SQL error, and directly causes the schema error that is surfaced to the user:
```
Referential integrity constraint violation: "CORE_USER_COPY_5_0_FK_COLLECTION_PERSONAL_OWNER_ID: PUBLIC.COLLECTION FOREIGN KEY(PERSONAL_OWNER_ID) REFERENCES PUBLIC.CORE_USER_COPY_5_0(ID) (5)"; SQL statement:
INSERT INTO "COLLECTION" ("NAME", "PERSONAL_OWNER_ID", "COLOR", "SLUG") VALUES (?, 5, ?, ?) [23506-197]
```

This indicates that because the datatype update didn't fail atomically, foreign keys in the collections table are expected to refer to users in the `COPY` table, which is causing the update to error.

I'm not sure what the best option would be to fix this. We probably don't want to just handle the collection update error since the H2 database is fundamentally corrupted by the `COPY` tables after the migration. It would be better to fail the upgrade and tell the admin to fix the conflicting email addresses manually (as @bkrn suggested) but I'm not sure how to do that. (cc @camsaul)

**Comment by noahmoss** [comment] 2021-06-21 21:40
On Postgres, I tried creating three users pre-update: `test@metabase.com`, `TEST@metabase.com`, and `TEST2@metabase.com`. After update, I see `test@`, `TEST@`, and `test2@`. However, neither `test@` nor `TEST@` can log in with either accounts' password. After changing `TEST@` to a different email address, all accounts can log in successfully. I can't reproduce the behavior where one user is logged in as another; @flamber are you still seeing that?

What I'm seeing doesn't seem like a huge issue (at least, not a security or privacy-related one) but maybe we can show a more helpful error message if login fails for this reason, rather than the generic invalid password message. I'll play around with it and see if I can improve this area.

**Comment by flamber** [comment] 2021-06-22 09:00
@noahmoss The problem is that the migration is executed, and fails, but we continue as if it worked. This then causes the integrity of the schema to divert from what we expect, which might not be a problem right now, but it might be some time in the future.
Kinda of what happened in #10087, which might not be causing problems initially, but it did later on.

This issue is not a security/privacy issue, since it's extremely unlikely that anyone is using case-sensitive emails for different people. While the standard dictates it as different addresses, no MTA respects that by default and just uses case-insensitive.

Given that most people who have encountered this issue has likely found workarounds, my concern is only the integrity of the schema, which might give us problems in future migrations.

**Comment by tsmacdonald** [comment] 2023-08-01 18:04
Closing this as unplanned since it (now) only affects old versions of Metabase we're no longer actively developing. If anyone is still running into this bug please comment here on the issue.

**Closed by tsmacdonald** 2023-08-01 18:04 UTC
Labels: Type:Bug, Priority:P2, Operation/H2, Operation/Database Migrations, .Backend, .Regression, .Cannot Cypress Test
