### ISSUE TITLE
Timezone incorrect when query with previous filter in MongoDB

### ISSUE THREAD

**Issue by sytuacmdyh** [metabase/metabase#16333] opened 2021-06-03 03:56 UTC
**Describe the bug**
When create a  question in mongodb collection, which contains a time field, the "previous" filter seems have timezone problem.
I have set the timezone to Asia/Shanghai both in java env and admin backend report timezone

**Logs**
No error log.

**To Reproduce**
1. insert `test` table data
```
{
	"_id" : ObjectId("60b844c26fca73798be8cce6"),
	"name" : 2,
	"time" : ISODate("2021-06-02T00:00:00.000+08:00")
},
{
	"_id" : ObjectId("60b844c26fca73798be8cce5"),
	"name" : 1,
	"time" : ISODate("2021-06-03T00:00:00.000+08:00")
}
```
2. create question
<img width="977" alt="图片" src="https://user-images.githubusercontent.com/13233969/120581752-ee109980-c45d-11eb-9df7-f3dc6c1d4347.png">
3. view the native query
<img width="637" alt="图片" src="https://user-images.githubusercontent.com/13233969/120581832-113b4900-c45e-11eb-9d41-289d19b29bf1.png">

**Expected behavior**
In step 2, the result should be the record which name is 2 and time is 2021-06-02, since tody is 2021-06-03.
In step 3, the query sql seems not to deal with timezone, and I tried some other filter like `current`, `before`, `between`, these works fine.

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_20-b26",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_20",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.20-b23",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.11.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.25-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.39.3",
      "date": "2021-05-27",
      "branch": "release-x.39.x",
      "hash": "598a112"
    },
    "settings": {
      "report-timezone": "Asia/Shanghai"
    }
  }
}
```

**Severity**
blocking some users

**Comment by flamber** [comment] 2021-06-03 11:54
Duplicate of #14233.

On an unrelated note, you should really upgrade your Java, which is very outdated: https://www.metabase.com/docs/latest/operations-guide/java-versions.html

**Closed by flamber** 2021-06-03 11:54 UTC
Labels: .Needs Triage, Type:Bug
