### ISSUE TITLE
Duplicate column name error on simple sql join

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#18988] opened 2021-11-15 11:27 UTC
**Describe the bug**
When SQL question results have columns with duplicated names it is not possible to "Explore results" and use this question as a base for a custom question.

**To Reproduce**
1. Native query editor -> Sample dataset
2. Create and save People + Orders question
```
select * from PEOPLE
inner join ORDERS
on PEOPLE.ID = ORDERS.USER_ID
```
3. Click explore results to see the error
4. Create new custom question based on the `People + Orders` question and try to see the rows — it will show an error too

**Screenshots**
<img width="1440" alt="Screen Shot 2021-11-15 at 15 21 27" src="https://user-images.githubusercontent.com/14301985/141773902-129f2f93-c888-4b33-9c20-8d0e3721aac3.png">

<img width="1440" alt="Screen Shot 2021-11-15 at 15 21 02" src="https://user-images.githubusercontent.com/14301985/141773926-a5d01874-b408-448a-b480-49cad8df28ad.png">

**Information about your Metabase Installation:**
Latest master

**Comment by flamber** [comment] 2021-11-15 11:34
Duplicate of #18475

**Closed by flamber** 2021-11-15 11:34 UTC
Labels: Type:Bug, .Backend, .Needs Triage
