### ISSUE TITLE
Toast to enable notifications when a dashboard is done loading appears incorrectly when a user has no perms for a card

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#28756] opened 2023-02-28 21:34 UTC
**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Create a question and put it in a collection C1
2. Create a dashboard that includes the question and no others, and put it in another collection C2
3. Create a non-admin user and update permissions so that they have no access to C1
4. As the non-admin user, view the dashboard. You should correctly see a permissions error instead of the card.
5. Wait a few moments, and a toast will appear at the bottom left of the page prompting you to turn on notifications for when the dashboard is fully loaded.

**Expected behavior**
Cards blocked due to permissions shouldn't count as unloaded cards in this case.

**Screenshots/videos**
<img width="783" alt="Screenshot 2023-02-28 at 4 30 40 PM" src="https://user-images.githubusercontent.com/32746338/221985801-c4707e17-15c0-43cc-9150-db645e83f222.png">

**Information about your Metabase Installation:**
Current master

**Severity**
P3

**Comment by kamilmielnik** [comment] 2023-08-04 12:43
Fixed by #31691.

It even has a test: https://github.com/metabase/metabase/blob/31a8c32133942465ce5992a0b5f179ef40cbceb9/e2e/test/scenarios/dashboard-filters/dashboard-filters-auto-apply.cy.spec.js#L394

**Comment by kamilmielnik** [comment] 2023-08-08 10:34
I cannot reproduce it in `master`.
I can reproduce it in `v0.45.3`.

**Closed** 2023-08-10 05:27 UTC
Labels: Type:Bug, Priority:P3, Reporting/Dashboards, .Frontend, .Team/42 :milky_way:, .FixScope42
