### ISSUE TITLE
Bubble size in scatter chart wrong when 2nd series breakout is defined

### ISSUE THREAD

**Issue by jrirei** [metabase/metabase#25004] opened 2022-08-25 07:37 UTC
**Describe the bug**
The size attribute in scatter charts is not used correctly when a series breakout is used. In that case the relative size of bubbles is calculated for each breakout value separately which does not make much sense.

**To Reproduce**
This is using the hosted Metabase version (v0.44.1).

1. Use this SQL query:
```
select 1 as size, 1 as x, 5 as y, 1 as breakout union all
select 10 as size, 2 as x, 5 as y, 2 as breakout union all
select 100 as size, 1 as x, 10 as y, 2 as breakout union all
select 1000 as size, 2 as x, 10 as y, 1 as breakout
```

2. Setup a scatter chart using attributes size, x, and y => everything works fine

3. Add the column `breakout` as a breakout series for the X-axis => bubble sizes are "broken"
With "broken" I mean that size bubble are correct only when compared to other records of the same value of the breakout series. This means that the last two records in the example query are rendering using the same bubble size.

**Expected behavior**
I would expect that relative size of bubble are calculated *independent of any defined breakout series*, i.e. the relative size match for *all* given records of the query

**Screenshots**
Here is a screenshot of the chart with and without specifying `breakout` as a breakout series:
Step 2 (without breakout series defined):
<img width="939" alt="Screenshot 2022-08-25 at 09 36 43" src="https://user-images.githubusercontent.com/684238/186604274-2e208596-63cd-48cf-b080-2fd5441dcb28.png">

Step 3 (with breakout series defined)
<img width="942" alt="Screenshot 2022-08-25 at 09 37 17" src="https://user-images.githubusercontent.com/684238/186604386-47d9e78c-5af3-4c2f-936e-5ebfc2225d93.png">

**Severity**
It is not production critical. It affects one of our reports where we rely on breaking down contract values by sales agent. This bug prevents us from using from using different colors per sales agent. (The effect is much worse in production than in the example as the chart becomes random and misdirecting as small contract values can be displayed much larger than big contracts.)

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "de",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8",
    "os.name": "Linux",
    "os.version": "5.4.196-108.356.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.4.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-08-16",
      "tag": "v1.44.1",
      "branch": "release-x.44.x",
      "hash": "112f5aa"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2022-08-25 13:08
Duplicate of #24936

**Closed by flamber** 2022-08-25 13:08 UTC
