### ISSUE TITLE
Clicking on the ellipsis next to an item in a collection doesn't close another that's already open

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#42358] opened 2024-05-07 19:02 UTC
### Describe the bug

If you click on the `...` icon to open additional options on an item in a collection, and then you click on one for a different item, it doesn't close the first one automatically. And one might cover up the other if they overlap.

### To Reproduce

https://www.loom.com/share/143a17cfe562405a99cb047fe0fbd8c9

### Information about your Metabase installation

```JSON
Current master
```

### Severity

P3

**Comment by calherries** [comment] 2024-05-08 16:55
Closing, dupe of https://github.com/metabase/metabase/issues/42235

**Closed by calherries** 2024-05-08 16:55 UTC
Labels: Type:Bug, Priority:P3, Organization/Collections, .Frontend
