### ISSUE TITLE
Filtered By in Question view gets truncated

### ISSUE THREAD

**Issue by joboyx** [metabase/metabase#6858] opened 2018-02-05 12:21 UTC
**Details**
- Your browser and the version: Chrome Version 64.0.3282.119
- Your operating system: Ubuntu 17.10
- Your databases: Oracle 11c
- Metabase version: v0.27.2 build from source from tag v0.27.2
- Metabase hosting environment: Ubuntu 17.10
- Metabase internal database: MySQL 5.7

**Steps to Reproduce**
- Add more entries in "Filtered By" until the view gets truncated.
- You can see that the view gets truncated. And there is no scroll bar
- There's no way to remove the last filter

**Chrome:**
![screenshot from 2018-02-05 19-28-47](https://user-images.githubusercontent.com/920888/35803096-87136fea-0aad-11e8-80af-f29f0bc3b073.png)

**But in firefox it is visible:**
![screenshot from 2018-02-05 19-49-49](https://user-images.githubusercontent.com/920888/35804264-01dae4de-0ab2-11e8-847c-b6e8fbd2912d.png)

**Comment by mazameli** [comment] 2018-02-05 14:57
Duplicate of #5470 and will be fixed by #6835.

**Closed by mazameli** 2018-02-05 14:57 UTC

**Comment by joboyx** [comment] 2018-02-06 01:51
Thanks!
