### ISSUE TITLE
Custom question, unselect all columns

### ISSUE THREAD

**Issue by zeqk** [metabase/metabase#11140] opened 2019-10-15 11:09 UTC
**Is your feature request related to a problem? Please describe.**
When I am creating a custom question, and onlyw want to show some fields, I want first unselect all fields, and next select the fields I want

**Describe the solution you'd like**
When "Select all" check is selected, allow uncheck for unselect all columns

**Describe alternatives you've considered**
New check "Unselect all"

**How important is this feature to you?**
Some table has many fields, and is really very tedious uncheck the field I dont want to show one by one.

![image](https://user-images.githubusercontent.com/11799393/66826327-9d63ca00-ef22-11e9-85f2-6085ba732683.png)

**Comment by mazameli** [comment] 2019-10-15 16:38
Totally agree, though this is indeed a duplicate of #10460.

**Closed by mazameli** 2019-10-15 16:38 UTC
Labels: .Duplicate, .Needs Triage, Type:New Feature
