### ISSUE TITLE
You're running Metabase {this.removeVersionPrefixIfNeeded(currentVersion)} which is the latest and greatest!

### ISSUE THREAD

**Issue by dvanrijswijk** [metabase/metabase#6903] opened 2018-02-08 13:55 UTC
Admin panel shows:

You're running Metabase {this.removeVersionPrefixIfNeeded(currentVersion)} which is the latest and greatest!

Browsers:
Chrome 63.0.3239.132
Firefox 58.0.1
IE 11.0.9600.18893

OS:
Windows 7

Datbase:
Postgres

Metabase version:
0.28

Metabase hosting environment: 
Linux/Ubuntu 16.04

Metabase internal database: 
Postgres

Repeatable steps to reproduce the issue:
Open the admin panel, go to Updates.

**Comment by kdoh** [comment] 2018-02-08 17:53
Duplicate of #6896, fixed here https://github.com/metabase/metabase/pull/6898. Thanks for the heads up.

**Closed by kdoh** 2018-02-08 17:53 UTC
