### ISSUE TITLE
Filter not available after changing type in Data Model in v0.30.3 and v0.30.4

### ISSUE THREAD

**Issue by dizzydes** [metabase/metabase#8627] opened 2018-10-04 07:39 UTC
### Bug

- Your browser and the version: Chrome 69
- Your operating system: OS X, Ubuntu
- Your databases: PostgreSQL
- Metabase version: Broken in v0.30.3, v0.30.4 // Working in v0.29.3
- Metabase hosting environment: Mac app, Ubuntu Server, Ubuntu Desktop
- Metabase internal database: H2

## Repeatable steps to reproduce the issue

- Go to Admin -> Data Model
- Find a field that applies to that viz that doesn't have a type (e.g. category or date) defined
- Give it the relevant type
- Save a question to a dashboard, in my case it was a simple table viz presenting most columns in DB, that the adjusted column would apply to
- Attempt to add a new filter to that dashboard, of the type you had just defined in data model
- Although defined as that type, it won't appear in the list of potential options:
<img width="1104" alt="screen shot 2018-10-04 at 08 36 53" src="https://user-images.githubusercontent.com/10514807/46459379-ad45bb80-c7b0-11e8-9373-ae58ae4b4070.png">
- You can try rescan/removing cached versions of the fields after adjusting the type, it doesn't help

----

I guess this might have been broken in one of v0.3's bug fixes as it works fine in v0.29.3 but doesn't in v0.30.3 and v0.30.4. I see no bug fixes or features in v0.30.1 or v0.30.2 that look suspect but I'm just guessing.

Any more questions just shout 😄 

-------

**Comment by mazameli** [comment] 2018-10-04 23:14
I wasn't able to reproduce this. :/ 

- Does this happen with every field type? 
- In your screenshot it looks like you added an ID filter widget; is the field you're trying to filter on set to an `entity key` or `foreign key`?
- Is your saved question a SQL one?

**Comment by dizzydes** [comment] 2018-10-05 06:37
Maz,

Thanks for your response.

An ID I used as an example but Category type seems to be the one that fails
me most often. It has also failed me on date - so essentially every field
that I've tried.

Perhaps try doing it on fields that arent auto categorised in some way whem
first connecting.

When I change the name in the data model tab that comes through fine, it
jjst seems to be the type causing issue. Happy to give you a login to my
instance if you would like to see the issue there.

The questions were coming straight from the tables in the raw data, no SQL
adjustments.

Thanks.

**Comment by flamber** [comment] 2020-05-24 11:36
Closing this, since there has been many fixes and because it doesn't seem to have been reported by anyone else. If this is still reproducible, then please provide steps with Sample Dataset and check for errors in the log and browser console.

**Closed by flamber** 2020-05-24 11:36 UTC
Labels: .Need More Info, .Unable to Reproduce
