### ISSUE TITLE
Region map should be display on public shared question

### ISSUE THREAD

**Issue by amyuki** [metabase/metabase#8993] opened 2018-11-21 03:23 UTC
metabase v0.31.0

1. Create a question using Region map and make it public.
2. Log out and visit the above public question URL.
3. The map cannot be shown and open browser developer console, it is said that `/api/geojson/4808fd2a-d040-8b16-c9ad-818b3c0abd 22:1 Failed to load resource: the server responded with a status of 401 ()`

![image](https://user-images.githubusercontent.com/6037977/48817101-c4039a00-ed7f-11e8-8796-9a9c4f5cb787.png)

**Comment by jasongi-actu** [comment] 2018-11-22 05:40
I am also getting this error in v0.30.4

**Comment by flamber** [comment] 2019-02-23 23:06
I can see the map on 0.31.2, if I select one of the two built-in maps (World and US), but it fails using Custom Map.

This issue is most likely a duplicate of #5338, despite referencing embedded, since both issues are failing to get the map from the same end point `/api/geojson/:UUID`

**Comment by tlrobinson** [comment] 2019-02-26 23:54
Duplicate of #5338

**Closed by tlrobinson** 2019-02-26 23:54 UTC
Labels: Bug, Embedding
