### ISSUE TITLE
IE 11 Public Dashboard does not render 

### ISSUE THREAD

**Issue by kylelt** [metabase/metabase#5965] opened 2017-09-14 01:21 UTC
### Bug
Opening a publicly published dashboard, using the share option and
copying the link into browser and so on.

All that shows is the Dashboard Name, none of the cards display
IE 11 Render result 
- Expecting Two card 1 is a table, the other is a count of rows in the table
https://imgur.com/a/8XgnJ

IE 11 Console shows very little:
https://imgur.com/ypA5MTm

Note dashboard displays fine in ie11 if you use the
traditional method of viewing it, as in log into metabase and
click on the dashboard and so on...

- Your browser and the version: 11
- Your operating system: Win 7
- Your databases: MySQL
- Metabase version: You're on version v0.25.2 Built on 2017-08-09
- Metabase hosting environment: Ubuntu 16.04
- Metabase internal database: MySQL

#### Reproduction

- Publish any dashboard with a link via the share option
- Navigate to link with IE11 Browser

**Comment by camsaul** [comment] 2017-09-14 17:52
@kylelt can you just post your screenshots inline in the issue? Just drag the image into the text box and GitHub takes care of the rest

**Comment by mtucker** [comment] 2017-09-25 15:31
Same issue here with embedding.

This is the dashboard rendering correctly in the dashboard builder area of Metabase:

![image](https://user-images.githubusercontent.com/1233959/30815848-5ed94e16-a1e2-11e7-85d0-63ba746745e1.png)

However, in the publicly embedded version, I'm only seeing the title:

![image](https://user-images.githubusercontent.com/1233959/30816286-920d18ac-a1e3-11e7-9d00-2cb601250a30.png)

In fact, if you go into "Sharing and Embedding" > "Embed this Dashboard...", the issue is also present in the Preview:

![image](https://user-images.githubusercontent.com/1233959/30816007-c458f688-a1e2-11e7-9b66-2df54702fa8f.png)

Here's a look at dev tools:

![image](https://user-images.githubusercontent.com/1233959/30816746-d116c830-a1e4-11e7-95ca-c04c442f790c.png)

* Your browser and the version: IE11 (believe it's also an issue in IE10)
* Your operating system: Win 7
* Your databases: Postgres
* Metabase version: You're on version v0.25.1
* Metabase hosting environment: Heroku
* Metabase internal database: Postgres

This is really important to me because I have a customer running IE that is not seeing their dashboards right now so would love the teams thoughts. Thanks!

**Comment by mtucker** [comment] 2017-09-25 16:06
@camsaul  This issue thread in the React repo might shed some light on this? https://github.com/facebook/react/issues/8379

**Comment by mtucker** [comment] 2017-09-25 20:20
After more investigation, I'm pretty sure this is actually the result of a flexbox bug in IE, as described here: https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items

After cloning the repo and running Metabase locally, I found the dashboard is rendered in IE if I update the definition of the `flex-full` css class to:

```css
.flex-full, :local(.flex-full) {
    flex: 1 0 auto;
}
```

Not sure if that is actually a good solution given that the class is used in a lot of places.

**Comment by mtucker** [comment] 2017-09-25 22:43
Found an easy workaround for my use case. I explicitly set the height of the iframe containing the  embedded dashboard and it now renders in IE11.

**Comment by mazameli** [comment] 2017-09-26 17:18
@kdoh, if I'm remembering correctly, you love dealing with IE flexbox bugs, right? 😍

**Comment by yannickcornaille** [comment] 2018-04-30 14:18
I just opened a pull request with @mtucker 's solution.
PR here #7489

**Comment by salsakran** [comment] 2018-05-09 20:38
closed via #7489

**Closed by salsakran** 2018-05-09 20:38 UTC
Labels: Browser/IE, Bug, Priority/P2

**Comment by jlisyc** [comment] 2018-09-03 12:34
Related: filter widget cannot display in IE11
https://github.com/metabase/metabase/issues/8195

**Comment by jlisyc** [comment] 2018-11-28 11:43
related https://github.com/metabase/metabase/issues/9038
