### ISSUE TITLE
SQL question with Field Filters linked to dashboard filters fails in public view

### ISSUE THREAD

**Issue by leafstorm** [metabase/metabase#13918] opened 2020-11-30 20:42 UTC
**Describe the bug**
I created an SQL question with Field Filters and added it to a dashboard, linking the dashboard's filters to the Field Filters. The question with filters works when I view the dashboard from the normal URL (i.e., for a logged-in user) but shows a "There was a problem displaying this chart" message when I use the public dashboard view.

**Logs**
For full Metabase and console logs, see this gist: https://gist.github.com/leafstorm/b32d45edf25629ec12bdbe1e75fba28e

Here's the specific exception on the server side:
```clojure
{:database_id 2,
 :started_at #t "2020-11-30T15:07:55.355642500-05:00[America/New_York]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error building query parameter map",
   :stacktrace "omitted here - see gist for full stacktrace",
   :error_type :invalid-query,
   :ex-data
   {:type :schema.core/error,
    :tags
    {"month" {:id "c181bc98-c402-78ac-fd83-179d769665dc", :name "month", :display-name "Month", :type :dimension, :default nil, :dimension [:field-id 1720], :widget-type :date/month-year},
     "customer" {:id "3a31b407-d64f-6eeb-796c-480e14bf6279", :name "customer", :display-name "Customer", :type :dimension, :dimension [:field-id 332], :widget-type :category, :default nil}},
    :params
    [{:slug "month_and_year",
      :name "Month and Year",
      :value "2020-01",
      :type :date/month-year,
      :id "54ca1665",
      :field_ids [614],
      :target [:dimension [:template-tag "month"]],
      :field_id 1720,
      :hasOnlyFieldTargets true}
     {:slug "customer",
      :name "Customer",
      :value ["XYZ"],
      :type :category,
      :id "609a556d",
      :field_ids [332],
      :target [:dimension [:template-tag "customer"]],
      :field_id 332,
      :hasOnlyFieldTargets true}]}}],
 :error_type :invalid-query,
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :native,
  :middleware {:js-int-to-string? true},
  :native
  {:template-tags
   {"month" {:id "c181bc98-c402-78ac-fd83-179d769665dc", :name "month", :display-name "Month", :type :dimension, :default nil, :dimension [:field-id 1720], :widget-type :date/month-year},
    "customer" {:id "3a31b407-d64f-6eeb-796c-480e14bf6279", :name "customer", :display-name "Customer", :type :dimension, :dimension [:field-id 332], :widget-type :category, :default nil}},
   :query
   "-- omitting query... but it does include [[and {{month}}]] and [[and {{customer}}]]"},
  :database 2,
  :parameters
  ({:slug "month_and_year",
    :name "Month and Year",
    :value "2020-01",
    :type "date/month-year",
    :id "54ca1665",
    :field_ids [614],
    :target ["dimension" ["template-tag" "month"]],
    :field_id 1720,
    :hasOnlyFieldTargets true}
   {:slug "customer",
    :name "Customer",
    :value ["XYZ"],
    :type "category",
    :id "609a556d",
    :field_ids [332],
    :target ["dimension" ["template-tag" "customer"]],
    :field_id 332,
    :hasOnlyFieldTargets true}),
  :async? true,
  :cache-ttl nil},
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace "omitted here - see gist for full stacktrace",
 :context :public-dashboard,
 :error
 "Input to value-for-tag does not match schema: \n\n\t   [nil (named [{:field_ids disallowed-key, :field_id disallowed-key, :hasOnlyFieldTargets disallowed-key} {:field_ids disallowed-key, :field_id disallowed-key, :hasOnlyFieldTargets disallowed-key}] params)]  \n\n",
 :row_count 0,
 :running_time 0,
 :ex-data
 {:type :schema.core/error,
  :value
  [{:id "c181bc98-c402-78ac-fd83-179d769665dc", :name "month", :display-name "Month", :type :dimension, :default nil, :dimension [:field-id 1720], :widget-type :date/month-year}
   [{:slug "month_and_year",
     :name "Month and Year",
     :value "2020-01",
     :type :date/month-year,
     :id "54ca1665",
     :field_ids [614],
     :target [:dimension [:template-tag "month"]],
     :field_id 1720,
     :hasOnlyFieldTargets true}
    {:slug "customer",
     :name "Customer",
     :value ["XYZ"],
     :type :category,
     :id "609a556d",
     :field_ids [332],
     :target [:dimension [:template-tag "customer"]],
     :field_id 332,
     :hasOnlyFieldTargets true}]],
  :error
  [nil
   (named [{:field_ids disallowed-key, :field_id disallowed-key, :hasOnlyFieldTargets disallowed-key} {:field_ids disallowed-key, :field_id disallowed-key, :hasOnlyFieldTargets disallowed-key}] params)]},
 :data {:rows [], :cols []}}
```

**To Reproduce**
1. Create a SQL question with a Field Filter of the "Month and Year" type and one of the "Category" type.
2. Add it to a Dashboard.
3. Add a "Time/Month and Year" filter and an "Other Category" filter to the dashboard.
4. Link the dashboard filters to the Field Filters of the SQL question.
5. Confirm that the dashboard filters work as expected.
5. Go to "Sharing and Embedding" and check "Enable sharing."
6. Visit the public dashboard link.
7. The SQL question displays "There was a problem displaying this chart."

**Expected behavior**
The SQL question should work in the public dashboard view, as it does in the non-public view and as the other dashboard questions do work in the public view.

**Screenshots**
Here is the question working in the non-public dashboard view (it's heavily redacted, but you can see that it is a table-returning question):
![image](https://user-images.githubusercontent.com/271305/100661044-e3474180-3320-11eb-8514-2d116e93ddc2.png)

And here is it not working in the public dashboard view:
![image](https://user-images.githubusercontent.com/271305/100661291-3faa6100-3321-11eb-8688-fac8f35b1b33.png)

**Additional context**
I am running Metabase from the .jar on a Windows Server 2008 R2 system with AdoptOpenJDK JRE 11.0.9.

**Severity**
I am still evaluating Metabase for my organization. This bug wouldn't necessarily block us from using Metabase, but it would limit our ability to take full advantage of it.

**Metabase Diagnostic Info**
```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0",
    "vendor": ""
  }
}
```

**Comment by flamber** [comment] 2020-11-30 21:21
Hi @leafstorm 
Please provide all the information requested.
Post the full "Diagnostic Info" from Admin > Troubleshooting, and which database you are querying.
You are redacting too much from the stacktrace - I cannot reproduce.
Try reproducing with some data and query that can be shown.

**Comment by leafstorm** [comment] 2020-12-01 00:23
Hi, @flamber,

I apologize for leaving out the full diagnostic information. I added it to the gist https://gist.github.com/leafstorm/b32d45edf25629ec12bdbe1e75fba28e, which also contains the full Clojure stack trace and the JavaScript console log. The affected question is running against a PostgreSQL 9.5 database.

I attempted to reproduce the issue on the Sample Dataset included with Metabase, but the question I created against the Sample Dataset (with a similar Field Filter setup) does work correctly in the dashboard view. The issue may be peculiar to PostgreSQL or to the fact that the "Month and Year" filter targets the table's primary key. I can at least offer this more detailed (still slightly edited for confidentiality) version of the SQL text:

```sql
with selected_month as (
    select start_date as current_month
    from monthlydataset
    where true [[and {{month}}]]
    order by start_date desc
    limit 1
),
fy_months as (
    select
        start_date as month,
        start_date = current_month as is_current_month
    from monthlydataset
    cross join selected_month
    where start_date <= current_month
        and start_date >= make_date(
            cast(extract(year from current_month) as int) -
            case when extract(month from current_month) < 7 then 1 else 0 end,
        7, 1)
)
select
  coalesce(product.name, 'Total') as "Product",
  sum(case when is_current_month then mct.quantity end) as "Quantity",
  sum(mct.quantity) as "FYTD Quantity",
  sum(case when is_current_month then mct.total_sales end) as "Sales",
  sum(mct.total_sales) as "FYTD Sales"
from monthlycustomertotal as mct
join customer on (mct.customer_id = customer.id)
join product on (mct.product_id = product.id)
join fy_months on (mct.month_id = fy_months.month)
where true [[and {{customer}}]]
group by rollup (product.name)
```

The "Month and Year" filter is linked to `monthlydataset.start_date`, which is the table's primary key and the actual first day of the month. (The intent is that it will select exactly one `monthlydataset`, and the `with` query will identify all of the `monthlydataset`s that preceded that month in the fiscal year.) The "Customer" filter is linked to `customer.name`. If I can provide additional data to help diagnose the problem (such as API responses from specific endpoints) I would be happy to do so, but I cannot share the actual dataset.

Thanks,
Matthew Frazier

**Comment by flamber** [comment] 2020-12-01 10:29
@leafstorm 
I'm not asking for your data, I'm looking for some way to reproduce this. Please provide a sample schema.
From the errors, it seems like filter does not get applied correctly, so what is the URL parameters?
Does this happen to only involve the month-filter, or does the error only occur when category-filter is also applied?
If you create a new question with the same query, but re-do the variables and save that question to a new dashboard, can you reproduce the problem?

**Comment by leafstorm** [comment] 2020-12-01 14:01
Hi, @flamber,

Thanks for the suggestion to retry creating the query and add it to another dashboard. When I did that, the new dashboard worked. I was curious what the difference was between the two dashboards, so I opened up `/api/public/dashboard/<uuid>` for the old version and the new version, and the only differences I found were in the top-level `"parameters"` list. This is the version in the non-functioning dashboard:

```json
  [
    {
      "name": "Month and Year",
      "slug": "month_and_year",
      "id": "54ca1665",
      "type": "date/month-year",
      "field_ids": [
        614
      ],
      "field_id": 1720,
      "hasOnlyFieldTargets": true
    },
    {
      "name": "Customer",
      "slug": "customer",
      "id": "609a556d",
      "type": "category",
      "field_ids": [
        332
      ],
      "field_id": 332,
      "hasOnlyFieldTargets": true
    }
  ]
```

And this is the version in the functioning dashboard:

```json
  [
    {
      "name": "Month and Year",
      "slug": "month_and_year",
      "id": "7156e292",
      "type": "date/month-year"
    },
    {
      "name": "Category",
      "slug": "category",
      "id": "fddc8e2a",
      "type": "category"
    }
  ]
```

This suggests that the issue is the three extra keys in the `"parameters"` list elements: `"field_ids"`, `"field_id"`, and `"hasOnlyFieldTargets"`. I followed up by removing the two filters from the original dashboard and re-adding them, and the extra keys disappeared from the original dashboard and it started working again.

I'm not very familar with either React or Clojure, but I searched the codebase for `hasOnlyFieldTargets` and it looks like a name that is only referenced on the frontend code, not by any Clojure backend code. So my hypothesis is that there is some circumstance where the dashboard editor UI will save that variable to the backend even though it's supposed to only exist in frontend code.

Thanks,
Matthew Frazier

**Comment by flamber** [comment] 2020-12-01 14:26
@leafstorm I noticed that too, but I really don't know how you ended up in this state.
I'm going to close this, but if you figure out a way to reproduce the `parameters` with the extra keys, then please comment.

**Closed by flamber** 2020-12-01 14:26 UTC
Labels: .Unable to Reproduce

**Comment by leafstorm** [comment] 2020-12-01 18:03
Sure. Thanks for your help troubleshooting the issue!

**Comment by marcoruggine** [comment] 2020-12-22 15:19
Hi @flamber , I've just had the same exact problem! 
I had a dashboard embedded via JWT that was working perfectly. I've added 2 more filters in order to have them connected to some already existing ones and now it doesn't work anymore.

I've tried deleting those filters but it doesn't work.

this is what I have from the logs:

`[cda61806-acfa-4586-9826-b962dd7b6bb6] 2020-12-22T16:12:00+01:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: null
{:database_id 2,
 :started_at #t "2020-12-22T15:11:56.367515Z[GMT]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error building query parameter map",
   :stacktrace
   ["--> driver.common.parameters.values$fn__76311$query__GT_params_map__76316$fn__76320.invoke(values.clj:339)"
    "driver.common.parameters.values$fn__76311$query__GT_params_map__76316.invoke(values.clj:321)"
    "driver.sql$fn__78119.invokeStatic(sql.clj:46)"
    "driver.sql$fn__78119.invoke(sql.clj:42)"
    "query_processor.middleware.parameters.native$expand_inner.invokeStatic(native.clj:39)"
    "query_processor.middleware.parameters.native$expand_inner.invoke(native.clj:30)"
    "query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:53)"
    "query_processor.middleware.parameters$expand_one.invoke(parameters.clj:44)"
    "query_processor.middleware.parameters$expand_all$replace_48080__48081.invoke(parameters.clj:62)"
    "mbql.util.match$replace_in_collection$iter__26258__26262$fn__26263.invoke(match.clj:132)"
    "mbql.util.match$replace_in_collection.invokeStatic(match.clj:131)"
    "mbql.util.match$replace_in_collection.invoke(match.clj:126)"
    "query_processor.middleware.parameters$expand_all$replace_48080__48081.invoke(parameters.clj:62)"
    "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:62)"
    "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:56)"
    "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:59)"
    "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:56)"
    "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:80)"
    "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:76)"
    "query_processor.middleware.parameters$fn__48096$substitute_parameters_STAR___48101$fn__48102.invoke(parameters.clj:85)"
    "query_processor.middleware.parameters$fn__48096$substitute_parameters_STAR___48101.invoke(parameters.clj:82)"
    "query_processor.middleware.parameters$substitute_parameters$fn__48122.invoke(parameters.clj:114)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46508.invoke(resolve_referenced.clj:80)"
    "query_processor.middleware.expand_macros$expand_macros$fn__47127.invoke(expand_macros.clj:158)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__41200.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49058.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48348$fn__48352.invoke(resolve_database_and_driver.clj:33)"
    "driver$do_with_driver.invokeStatic(driver.clj:61)"
    "driver$do_with_driver.invoke(driver.clj:57)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48348.invoke(resolve_database_and_driver.clj:27)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47345.invoke(fetch_source_query.clj:267)"
    "query_processor.middleware.store$initialize_store$fn__49067$fn__49068.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
    "query_processor.store$do_with_store.invoke(store.clj:40)"
    "query_processor.middleware.store$initialize_store$fn__49067.invoke(store.clj:10)"
    "query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:187)"
    "query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:178)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__46385.invoke(cache.clj:213)"
    "query_processor.middleware.validate$validate_query$fn__49076.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__47470.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__41038.invoke(add_rows_truncated.clj:36)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49043.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__46748.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__48211.invoke(process_userland_query.clj:136)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46691.invoke(catch_exceptions.clj:174)"
    "query_processor.reducible$async_qp$qp_STAR___39827$thunk__39828.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___39827$fn__39830.invoke(reducible.clj:108)"],
   :error_type :invalid-query,
   :ex-data
   {:type :schema.core/error,
    :tags
    {"time"
     {:id "65e5c901-84f0-ba37-3da5-08611d20bbec",
      :name "time",
      :display-name "Time",
      :type :dimension,
      :dimension [:field-id 1861],
      :widget-type :date/all-options,
      :default "past1weeks",
      :required true},
     "tenant_id" {:id "34017ca3-2e95-8332-6af9-f81bd76b3be8", :name "tenant_id", :display-name "tenant_id", :type :text, :required false},
     "match_origin"
     {:id "0faee907-ee41-5b73-1403-199252cf28a3", :name "match_origin", :display-name "Match origin", :type :dimension, :dimension [:field-id 1854], :widget-type :category, :default nil},
     "tenant_name" {:id "e0571441-28bc-4490-233d-298bd60317af", :name "tenant_name", :display-name "Tenant name", :type :dimension, :dimension [:field-id 1850], :widget-type :category, :default nil},
     "court" {:id "b453b9a7-afbc-dbe8-e636-c70334207df4", :name "court", :display-name "Court", :type :dimension, :dimension [:field-id 1831], :widget-type :category, :default nil}},
    :params
    [{:type :date/all-options, :target [:dimension [:template-tag "time"]], :slug "%F0%9F%97%93", :value "thisweek", :name "🗓", :id "8d45a40f", :default "thisweek"}
     {:type :id,
      :target [:variable [:template-tag "tenant_id"]],
      :slug "tenant_id",
      :value "da785b1b-43b3-11e8-8674-52540049669c",
      :name "tenant_id",
      :id "462fb1f8",
      :default "da785b1b-43b3-11e8-8674-52540049669c",
      :filteringParameters ["5a4581f5"]}]}}],
 :error_type :invalid-query,
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :native,
  :middleware {:js-int-to-string? true},
  :native
  {:template-tags
   {"time"
    {:id "65e5c901-84f0-ba37-3da5-08611d20bbec",
     :name "time",
     :display-name "Time",
     :type :dimension,
     :dimension [:field-id 1861],
     :widget-type :date/all-options,
     :default "past1weeks",
     :required true},
    "tenant_id" {:id "34017ca3-2e95-8332-6af9-f81bd76b3be8", :name "tenant_id", :display-name "tenant_id", :type :text, :required false},
    "match_origin"
    {:id "0faee907-ee41-5b73-1403-199252cf28a3", :name "match_origin", :display-name "Match origin", :type :dimension, :dimension [:field-id 1854], :widget-type :category, :default nil},
    "tenant_name" {:id "e0571441-28bc-4490-233d-298bd60317af", :name "tenant_name", :display-name "Tenant name", :type :dimension, :dimension [:field-id 1850], :widget-type :category, :default nil},
    "court" {:id "b453b9a7-afbc-dbe8-e636-c70334207df4", :name "court", :display-name "Court", :type :dimension, :dimension [:field-id 1831], :widget-type :category, :default nil}},
   :query
   "WITH \n-- setting up a rule to use later on for dynamic timeserie grouping\ngrouping_rule as (\n    SELECT \n        CASE \n            WHEN TIMESTAMP_DIFF(max(local_start_date), min(local_start_date), day) > 366 then 'year'\n            WHEN TIMESTAMP_DIFF(max(local_start_date), min(local_start_date), day) >= 32 and TIMESTAMP_DIFF(max(local_start_date), min(local_start_date), day) <= 366 then 'month'\n            WHEN TIMESTAMP_DIFF(max(local_start_date), min(local_start_date), day) >= 1 and TIMESTAMP_DIFF(max(local_start_date), min(local_start_date), day) < 32 then 'day'\n            WHEN TIMESTAMP_DIFF(max(local_start_date), min(local_start_date), day) < 1 then 'minute'\n        END as rule, \n    FROM `pro.h_manager_dashboard_pro`\n    WHERE 1=1\n        AND match_status != 'CANCELED'\n        [[AND tenant_id = {{tenant_id}}]]\n        [[AND {{time}}]]\n        [[AND {{match_origin}}]]\n        [[AND {{court}}]]\n        [[AND {{tenant_name}}]]\n    ),\n-- 🔥 I need to do this otherwise when formatting it orders time considering it as text, if I don't format it prints horribly\nfinal_table as (\n    SELECT\n        CASE\n            WHEN rule = 'year' then TIMESTAMP_TRUNC(local_start_date, year) \n            WHEN rule = 'month' then TIMESTAMP_TRUNC(local_start_date, month)\n            WHEN rule = 'week' then TIMESTAMP_TRUNC(local_start_date, week)\n            WHEN rule = 'day' then TIMESTAMP_TRUNC(local_start_date, day)\n            WHEN rule = 'minute' then TIMESTAMP_TRUNC(local_start_date, minute)\n        END as time_to_format,\n        count(distinct match_id) as key_metric\n    FROM `pro.h_manager_dashboard_pro`\n        CROSS JOIN grouping_rule\n    WHERE 1=1\n        AND match_status != 'CANCELED'\n        [[AND tenant_id = {{tenant_id}}]]\n        [[AND {{time}}]]\n        [[AND {{match_origin}}]]\n        [[AND {{court}}]]\n        [[AND {{tenant_name}}]]\n    GROUP BY \n        time_to_format\n    ORDER BY \n        time_to_format ASC\n)\n----------------------------------------------\nSELECT \n    CASE \n        WHEN (SELECT rule FROM grouping_rule) = 'year'THEN FORMAT_TIMESTAMP( \"%Y\", time_to_format) \n        WHEN (SELECT rule FROM grouping_rule) = 'month'THEN FORMAT_TIMESTAMP( \"%b %Y\", time_to_format) \n        WHEN (SELECT rule FROM grouping_rule) = 'week'THEN FORMAT_TIMESTAMP( \"Week %d %b\", time_to_format) \n        WHEN (SELECT rule FROM grouping_rule) = 'day'THEN FORMAT_TIMESTAMP( \"%a %d %b\", time_to_format) \n        WHEN (SELECT rule FROM grouping_rule) = 'minute'THEN FORMAT_TIMESTAMP( \"%H:%M\", time_to_format) \n    END as `When`,\n    key_metric as `Matches`\nFROM final_table\nORDER BY time_to_format ASC"},
  :database 2,
  :parameters
  ({:type "date/all-options", :target [:dimension [:template-tag "time"]], :slug "%F0%9F%97%93", :value "thisweek", :name "🗓", :id "8d45a40f", :default "thisweek"}
   {:type "id",
    :target [:variable [:template-tag "tenant_id"]],
    :slug "tenant_id",
    :value "da785b1b-43b3-11e8-8674-52540049669c",
    :name "tenant_id",
    :id "462fb1f8",
    :default "da785b1b-43b3-11e8-8674-52540049669c",
    :filteringParameters ["5a4581f5"]}),
  :async? true,
  :cache-ttl 20},
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> driver.common.parameters.values$fn__76287$value_for_tag__76292.invoke(values.clj:309)"
  "driver.common.parameters.values$fn__76311$query__GT_params_map__76316$fn__76320$iter__76322__76326$fn__76327.invoke(values.clj:331)"
  "driver.common.parameters.values$fn__76311$query__GT_params_map__76316$fn__76320.invoke(values.clj:330)"
  "driver.common.parameters.values$fn__76311$query__GT_params_map__76316.invoke(values.clj:321)"
  "driver.sql$fn__78119.invokeStatic(sql.clj:46)"
  "driver.sql$fn__78119.invoke(sql.clj:42)"
  "query_processor.middleware.parameters.native$expand_inner.invokeStatic(native.clj:39)"
  "query_processor.middleware.parameters.native$expand_inner.invoke(native.clj:30)"
  "query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:53)"
  "query_processor.middleware.parameters$expand_one.invoke(parameters.clj:44)"
  "query_processor.middleware.parameters$expand_all$replace_48080__48081.invoke(parameters.clj:62)"
  "mbql.util.match$replace_in_collection$iter__26258__26262$fn__26263.invoke(match.clj:132)"
  "mbql.util.match$replace_in_collection.invokeStatic(match.clj:131)"
  "mbql.util.match$replace_in_collection.invoke(match.clj:126)"
  "query_processor.middleware.parameters$expand_all$replace_48080__48081.invoke(parameters.clj:62)"
  "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:62)"
  "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:56)"
  "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:59)"
  "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:56)"
  "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:80)"
  "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:76)"
  "query_processor.middleware.parameters$fn__48096$substitute_parameters_STAR___48101$fn__48102.invoke(parameters.clj:85)"
  "query_processor.middleware.parameters$fn__48096$substitute_parameters_STAR___48101.invoke(parameters.clj:82)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48122.invoke(parameters.clj:114)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46508.invoke(resolve_referenced.clj:80)"
  "query_processor.middleware.expand_macros$expand_macros$fn__47127.invoke(expand_macros.clj:158)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__41200.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49058.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48348$fn__48352.invoke(resolve_database_and_driver.clj:33)"
  "driver$do_with_driver.invokeStatic(driver.clj:61)"
  "driver$do_with_driver.invoke(driver.clj:57)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48348.invoke(resolve_database_and_driver.clj:27)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47345.invoke(fetch_source_query.clj:267)"
  "query_processor.middleware.store$initialize_store$fn__49067$fn__49068.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__49067.invoke(store.clj:10)"
  "query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:187)"
  "query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:178)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__46385.invoke(cache.clj:213)"
  "query_processor.middleware.validate$validate_query$fn__49076.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__47470.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__41038.invoke(add_rows_truncated.clj:36)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49043.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__46748.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__48211.invoke(process_userland_query.clj:136)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46691.invoke(catch_exceptions.clj:174)"
  "query_processor.reducible$async_qp$qp_STAR___39827$thunk__39828.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___39827$fn__39830.invoke(reducible.clj:108)"],
 :context :embedded-dashboard,
 :error "Input to value-for-tag does not match schema: \n\n\t   [nil (named [nil {:filteringParameters disallowed-key}] params)]  \n\n",
 :row_count 0,
 :running_time 0,
 :ex-data
 {:type :schema.core/error,
  :value
  [{:id "65e5c901-84f0-ba37-3da5-08611d20bbec",
    :name "time",
    :display-name "Time",
    :type :dimension,
    :dimension [:field-id 1861],
    :widget-type :date/all-options,
    :default "past1weeks",
    :required true}
   [{:type :date/all-options, :target [:dimension [:template-tag "time"]], :slug "%F0%9F%97%93", :value "thisweek", :name "🗓", :id "8d45a40f", :default "thisweek"}
    {:type :id,
     :target [:variable [:template-tag "tenant_id"]],
     :slug "tenant_id",
     :value "da785b1b-43b3-11e8-8674-52540049669c",
     :name "tenant_id",
     :id "462fb1f8",
     :default "da785b1b-43b3-11e8-8674-52540049669c",
     :filteringParameters ["5a4581f5"]}]],
  :error [nil (named [nil {:filteringParameters disallowed-key}] params)]},
 :data {:rows [], :cols []}}
`

**Comment by flamber** [comment] 2020-12-22 15:27
@marcoruggine You are likely seeing a different problem, but I'm not sure what you mean by this:
> I've added 2 more filters in order to have them connected to some already existing ones and now it doesn't work anymore

Sounds like you are using Linked Filters, which has a known issue: #13868

**Comment by marcoruggine** [comment] 2020-12-22 15:33
Sorry @flamber, I meant that after having tested the dashboard was working fine when embedded via JWT using a few basic filters, I've added 2 more that are chained to one of those already tested.

Unfortunately, removing the chained filters did not solve my problem as reported in #13868

**Comment by flamber** [comment] 2020-12-22 15:44
@marcoruggine Okay, try removing all the filters, save the dashboard, add the filters again (no Linked/Chained filters) and connect them to the the cards.
Otherwise please provide steps to reproduce in a new issue - use Sample Dataset, so we can all reproduce.

**Comment by marcoruggine** [comment] 2020-12-22 15:46
I'll try right now

**Comment by marcoruggine** [comment] 2020-12-22 15:52
@flamber that solved my issue!! thanks
