### ISSUE TITLE
Error in Question when a field no longer exists

### ISSUE THREAD

**Issue by fer-batista** [metabase/metabase#47633] opened 2024-09-04 19:57 UTC
### Describe the bug

I`m using Questions selecting some fields.  If I change my table deleting fields and one of these selected fields no longer exists, the query breaks without automatically keeping the field in the calculation. 

### To Reproduce

1. Create a new Question.
2. Select a table - in my case, I am using BigQuery.
3. Select only a few fields.
4. Save the question.
5. In BigQuery, delete one of the selected fields.
6. Return to Metabase, synchronize the schema and field values (admin menu).
7. Go back to the Question, and the error appears:

```
400 Bad Request
POST https://bigquery.googleapis.com/bigquery/v2/projects/xxxxx/queries
{
  "code": 400,
  "errors": [
    {
      "domain": "global",
      "location": "q",
      "locationType": "parameter",
      "message": "Name current_balance not found inside skill_dev.dev_teste_metabase_campo_alterado at [2:342]",
      "reason": "invalidQuery"
    }
  ],
  "message": "Name current_balance not found inside skill_dev.dev_teste_metabase_campo_alterado at [2:342]",
  "status": "INVALID_ARGUMENT"
}
```

8. Upon opening the notebook editor, there is no option to remove the faulty field; it can only be removed by selecting all items.

![image](https://github.com/user-attachments/assets/c0ce87a3-421e-4e19-bd64-f245da025797)
![image](https://github.com/user-attachments/assets/f44ff9d7-d805-418d-a6a6-87e623e0ee9d)

### Expected behavior

When a field no longer exists, the query should remove it from the code instead of the user having to select all the fields and then select some of the fields again.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "bigquery-cloud-sdk",
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-self-hosted-yearly",
    "version": {
      "date": "2024-08-29",
      "tag": "v1.50.23",
      "hash": "7040ff1"
    },
    "settings": {
      "report-timezone": "America/Sao_Paulo"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "6.1.90+",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

annoying

**Comment by andrewillard** [comment] 2024-09-04 20:11
+1

**Comment by paoliniluis** [comment] 2024-09-04 20:48
@fer-batista if you're a paid customer, please contact us

**Comment by paoliniluis** [comment] 2024-09-05 16:24
duplicate of https://github.com/metabase/metabase/issues/12721

**Closed by paoliniluis** 2024-09-05 16:24 UTC
Labels: Type:Bug, Priority:P2, Administration/Metadata & Sync, Querying/, .Team/BackendComponents
