### ISSUE TITLE
Metabot not render image with Chinese characters correctly

### ISSUE THREAD

**Issue by on99** [metabase/metabase#6174] opened 2017-10-15 03:07 UTC
The issue may duplicate #2032 #2027 #1796 #1730 but all those are closed or resolved.
However it does not work for me.

- Browser: Version 61.0.3163.100 (Official Build) (64-bit)
- OS: macOS Sierra
- Database: MySQL
- Metabase: 0.26.1
- Metabase hosting environment: docker
- Metabase internal database: MySQL

![image](https://user-images.githubusercontent.com/13196393/31581244-075ad544-b199-11e7-826e-27b47c73498f.png)

**Comment by nickhudkins** [comment] 2017-10-20 18:17
I'd be more than happy to dig in, I presume this is as a result of https://github.com/metabase/metabase/blob/17d0e57ba68ff8d1e4fa17034c588db9d20bf3ee/src/metabase/pulse/render.clj#L47 Lato does not support the characters but seems to have mappings for them resulting in those lovely empty boxes.

**Comment by camsaul** [comment] 2017-10-20 18:23
Duplicate of #2342

**Closed by camsaul** 2017-10-20 18:23 UTC
Labels: Type:Bug, .Duplicate, Priority:P2, Reporting/Pulses
