### ISSUE TITLE
`GET /api/activity/most_recently_viewed_dashboard` should not return archived dashboards

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#45223] opened 2024-07-08 14:22 UTC
### Describe the bug

If the most recently viewed dashboard is archived, the `/api/activity/most_recently_viewed_dashboard` endpoint will still return it and the FE will request it and then show weird state.

<img width="1303" alt="image" src="https://github.com/metabase/metabase/assets/6377293/9b80431a-60ce-4ee0-8d4b-348ba423bc89">

I'm updating to a p1 because of the behavior on master:

have two dashboards. Visit one, and then archive that. You want that to be the most recent. Go to a question and click on add to a dashboard.

Normally the most recent dashboard is highlighted and the blue button is ready to choose that dashboard
<img width="1329" alt="image" src="https://github.com/metabase/metabase/assets/6377293/57ae56c2-b571-4949-8964-2a2cd8ff5f63">

But if the archived dash is most recent, it is returned from the BE. But the FE will not show it, but it is still "selected" and the blue button will confirm that as your choice

<img width="1471" alt="image" src="https://github.com/metabase/metabase/assets/6377293/40e79e75-05ee-45ed-bbe2-77ebb6b50033">

If you select this, you are in an invalid state as you are "moving" a card into the archive.

<img width="1471" alt="image" src="https://github.com/metabase/metabase/assets/6377293/49712a6b-826d-4d51-a576-19aff2e2a605">
<img width="1471" alt="image" src="https://github.com/metabase/metabase/assets/6377293/63949b5c-40c8-450c-8491-aace28d682b1">

## How to fix

Make sure that both `release-x.50.x` and `master` have a tested fix for this.

### To Reproduce

Create a dashboard, then archive it. Go to question, on the menu click "add to a dashboard" and see the above UI state.

### Expected behavior

it should gracefully handle archived dashboards. Don't return that

### Information about your Metabase installation

```JSON
0.50.9
```

### Severity

p1

**Comment by paoliniluis** [comment] 2024-07-08 16:01
dupe of https://github.com/metabase/metabase/issues/44382

**Closed** 2024-07-08 17:41 UTC
Labels: Type:Bug, Priority:P1, Reporting/Dashboards, Organization/Collections, Organization/Trash, .Team/AdminWebapp, Organization/Browse Data
