### ISSUE TITLE
Chart details panel position is wrong in full app embedding dashboard

### ISSUE THREAD

**Issue by losrebellos** [metabase/metabase#26989] opened 2022-12-06 09:54 UTC
**Describe the bug**

The position of a chart details panel can appear on the next chart on a full app embedding dashboard.

**To Reproduce**

1. Go to the [overview](https://embedding-demo.metabase.com/) section of the embedding demo
2. Click on the `Number of Students` chart to get some details
3. The panel appears on the top left corner of the chart below

**Expected behavior**

The panel should appear on the targeted chart, not the one below.

**Screenshots**

![image](https://user-images.githubusercontent.com/348552/205877587-ab0a96b8-9a1b-4c9e-8ce9-14d4fb180ca2.png)

**Information about your Metabase Installation:**

- Metabase version: v1.44.6 (built on 2022-11-01)

**Severity**

Impacting the embedding demo and probably some customers embedding too.

**Additional context**

The overview section embeds a dashboard.

**Comment by flamber** [comment] 2022-12-06 11:30
This has nothing to do with embedding nor click behavior and is specific to Pie chart's drill action menu. Regression since v44.0. Fixed in v45.0.
44.6 in question:
![image](https://user-images.githubusercontent.com/1447303/205899569-45a30ac9-cb11-4731-aad0-f1775580da01.png)
44.6 in dashboard:
![image](https://user-images.githubusercontent.com/1447303/205899687-1e31388f-78a8-44a3-ac49-64f25a5a15a9.png)

45.0 in question:
![image](https://user-images.githubusercontent.com/1447303/205900096-356b0b4f-4dec-4c30-92ae-2268cb8c114c.png)
45.0 in dashboard:
![image](https://user-images.githubusercontent.com/1447303/205900047-e9617f32-7262-40e4-9da1-7929541dd9be.png)

**Closed by flamber** 2022-12-06 11:30 UTC
Labels: Type:Bug, Reporting/Dashboards, .Frontend, .Regression, Visualization/Charts/Pie
