### ISSUE TITLE
Some email clients show embedded images as attachments

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#6710] opened 2018-01-17 10:17 UTC
e.x. iOS and OS X Mail.app.

I believe setting the `Content-Type` of the email to `multipart/related` instead of `multipart/mixed` will fix this. I haven't figured out how to do that yet.

<img width="832" alt="screenshot 2018-01-17 17 12 47" src="https://user-images.githubusercontent.com/18193/35037264-a828e290-fba9-11e7-895e-a4ce923231ea.png">

![image-1](https://user-images.githubusercontent.com/18193/35037414-04bba236-fbaa-11e7-93fb-7c24c161acac.jpg)

**Comment by flamber** [comment] 2019-02-18 03:58
Duplicate of #1954

**Closed** 2020-05-27 11:39 UTC
Labels: Reporting/Pulses, Type:UX
