### ISSUE TITLE
0.31.2: Date filter in Querybuilder does not show full last day of filter

### ISSUE THREAD

**Issue by EvaSchreyer** [metabase/metabase#10824] opened 2019-09-06 08:40 UTC
Using Metabase v0.31.2. 
I run a question with the querybuilder and use the date filter between. 
When I enter two dates and run the query I don´t get all results I expect. 
When I use the time 11:59 for the last day in addition I get the full results. 

It seems when only using days not the full day is covered?

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2019-09-06 09:04
Hi @EvaSchreyer 
Sounds similar to #9089.
Which database are you querying?
Have you tried one of the later versions, like 0.33.2, which has fixed a lot of other timezone issues? Or what is the reason why you're using that older version?

**Comment by EvaSchreyer** [comment] 2019-09-06 09:08
Hi @flamber thanks for that! I wasn´t sure the issues are related ... I use a mySQL database behind metabase. 
Simple reason that I didn´t update to 0.33 yet is that there are still some bugs I would like to avoid and overall I didn´t have time to test it yet 😬 .. If that issue is fixed in 0.33 that would be another reason to get some free time to test it :)

**Comment by prigal** [comment] 2019-10-15 12:43
Same problem here with metabase 0.33.2.

![Capture d’écran 2019-10-15 à 14 42 43](https://user-images.githubusercontent.com/895267/66832384-17fc0c00-ef5a-11e9-9338-b94e5155bd6d.png)

is converted to : 

```
BETWEEN convert_tz('2019-09-30T22:00:00.000', '+00:00', '+02:00') 
AND convert_tz('2019-10-13T22:00:00.000', '+00:00', '+02:00') 
```

Last day (october 14 is excluded)

**Comment by flamber** [comment] 2019-10-15 15:37
@prigal There was a major overhaul (#10980) of how datetime filters work in 0.33.4, so could you test with that version?

**Comment by prigal** [comment] 2019-10-15 16:04
Sure, I will. Thanks for the info.

**Comment by prigal** [comment] 2019-10-18 05:55
We have just migrated our metabase to 0.33.4 but problem is still there, last day of selection is not included.

New test with an other question: 

<img width="443" alt="Capture d’écran 2019-10-18 à 07 51 11" src="https://user-images.githubusercontent.com/895267/67069062-24f84580-f17c-11e9-82f5-8cbdc7583bc3.png">

is translated to : 


`(checkout_completed_at >= convert_tz('2019-09-30T00:00:00.000', '+00:00', '+02:00') AND checkout_completed_at < convert_tz('2019-10-17T00:00:00.000', '+00:00', '+02:00'))
`

My timezone is setted to Europe/Brussel in Metabase config (GMT +2)

sql should be 

`(checkout_completed_at >= convert_tz('2019-09-30T00:00:00.000', '+00:00', '+02:00') AND checkout_completed_at < convert_tz('2019-10-18T00:00:00.000', '+00:00', '+02:00'))`

**Comment by prigal** [comment] 2019-10-18 06:35
Update : If I set metabase to GMT, it's fixed.

SQL is now : 

> (`sylius_order`.`checkout_completed_at` >= timestamp('2019-09-01T00:00:00.000Z') AND `sylius_order`.`checkout_completed_at` < timestamp('2019-10-01T00:00:00.000Z')))

**Comment by flamber** [comment] 2019-10-18 10:30
@prigal 
Could you have a look at the timezone troubleshooter and return the answer for the 6 points?
https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html
Also, could you post the Diagnostic Info from Admin > Troubleshooting?

**Comment by mazameli** [comment] 2019-10-18 19:46
Bumping this to a P1 since it deals with correctness and timezones.

**Comment by prigal** [comment] 2019-10-18 22:07
**What is the time zone of the data you think is being displayed improperly? (I.e., in the database itself.)**

GMT+2 (Europe/Paris)

**Are you using an explicit time zone setting on each timestamp, or are the timestamps being stored without a timestamp? (E.g., Dec 1, 2019 00:00:00Z00 is an explicitly timestamped value, but Dec 1, 2019 has an implied time zone.)**

Without timetstamp "2019-10-18 23:55:00" in MySQL database

**What time zone is the database server set to?**

GMT+2 (Europe/Paris)

```
prigal@db:~$ date
Fri Oct 18 23:55:46 CEST 2019
```

**What time zone is the server that is running Metabase set to?**

GMT+2 (Europe/Paris)

```
prigal@metabase:~$ date
Fri Oct 18 23:56:34 CEST 2019
```

**What is your Reporting Time zone setting?**

If you mean in Metabase configuration in admin : Europe/Brussel (GMT+2)

**What is your browser time zone setting?**

```
new Date().toString()
"Sat Oct 19 2019 00:06:59 GMT+0200 (heure d’été d’Europe centrale)"
```

**Comment by prigal** [comment] 2019-10-18 22:11
And diag info : 

```
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.4+11-post-Debian-1bpo91",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.4",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.4+11-post-Debian-1bpo91",
    "os.name": "Linux",
    "os.version": "4.15.18-4-pve",
    "user.language": "en",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "date": "2019-10-07",
      "tag": "v0.33.4",
      "branch": "release-0.33.x",
      "hash": "9559406"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}
```

**Comment by prigal** [comment] 2019-10-25 08:51
@flamber any news on this problem ? Can I help more with some testing ?

**Comment by flamber** [comment] 2019-10-25 18:20
@prigal I'm fairly sure this issue is a duplicate of #9089, but this issue has been given priority 1, so that's good.
There's a lot of work being done right now to fixing those pesky timezone issues and version 0.34.0 will have that as one of it's main focuses. Timezones and Daylight Savings are just very tricky.

**Comment by TurkerTunali** [comment] 2019-11-07 18:36
Hello @flamber , I appreciated your work. I believe that this is a bug fix and it should be in something like 0.33.5. Because 0.34.0 means more features which need more bug fixing.

**Comment by lins05** [comment] 2020-01-10 03:35
Seems this problem no longer happens on latest master (at least for mysql).

The generated sql no longer uses relative time but refers to the session timezone to get the correct time range:

```sql
WHERE (`Invoice`.`InvoiceTS` >= convert_tz('2009-01-01 00:00:00.000', 'UTC', @@session.time_zone)
       AND `Invoice`.`InvoiceTS` < convert_tz('2009-01-04 00:00:00.000', 'UTC', @@session.time_zone))
```

**Comment by salsakran** [comment] 2020-01-13 00:59
Closing since this should have been fixed in 0.34 and we have at least one confirmation that it has been. 34 involved a big reworking of how we deal with timezones, and while I'm sure there will be come new corner cases, this should be fixed. 

if you're still seeing it, please chime in and I'll re-open this issue

**Comment by notrom** [comment] 2020-04-09 01:55
@salsakran I'm still seeing this in 0.34.3 and 0.35.1 against SQL Server data sources. I'm missing the last half of the last day for date filters (I'm in New Zealand time zone, +12). This is continuing to cause confusion for us and creates a lack of confidence in the system.

If you want me to log a new issue please let me know, but I think it's the same issue.

![image](https://user-images.githubusercontent.com/4504437/78849879-cd230300-7a69-11ea-940a-38e0063c69bb.png)



```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "13.0.2+8",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-02",
      "tag": "v0.35.1",
      "branch": "release-0.35.x",
      "hash": "e67f169"
    },
    "settings": {
      "report-timezone": "Pacific/Auckland"
    }
  }
}
```

**Comment by dpsutton** [comment] 2021-01-20 15:37
@notrom can you explain what you think should be the correct behavior here because that query appears correct to me. If you are in UTC+12 and want the events that happened in the 7th month, a date query that is between `DateTimeOffsetFromParts (2019, 7, 1, 0, 0, 0, 0, 12, 0, 7)` and `DateTimeOffsetFromParts (2019, 8, 1, 0, 0, 0, 0, 12, 0, 7)` would seem to be the way to do it.

**Comment by notrom** [comment] 2021-01-21 01:57
@dpsutton I'm not an expert so take with a grain of salt. SQL Server `datetime` fields do not have a time zone offset or UTC attached to them. Our systems record everything in local time. Luckily everything we do is within one time zone so we're currently getting away with it.

See this screenshot:
![image](https://user-images.githubusercontent.com/4504437/105268455-27571400-5bf7-11eb-806e-cf76c03253d6.png)

4 different ways of getting data for yesterday from a table in our system based on a `datetime` field `DateReceived`. 3 return the same results, but the one using the `DateTimeOffsetFromParts (2021, 1, 21, 0, 0, 0, 0, 12, 0, 7)` (i.e. with the +12 offset) returns a different result. This is also the only one that returns dates outside the range I was expecting to get, it also happens to be the query that Metabase generates.

I don't fully understand the mechanism or reasons, but I think this shows that it's not doing what I was expecting.

**Comment by dpsutton** [comment] 2021-01-21 03:06
@notrom thanks for the information. Your example there is very detailed and helpful. Let me think on this and get back to you. Thanks for taking the time to create this query.

**Comment by qnkhuat** [comment] 2023-06-15 07:58
Tested on 45, 46, and master and it works correctly
![Screenshot 2023-06-15 at 14 58 24](https://github.com/metabase/metabase/assets/25661381/2fde9746-a871-4267-907e-cb264149f9c0)

We probably fixed this at some point in the past.

**Closed by qnkhuat** 2023-06-15 07:58 UTC
Labels: Type:Bug, Priority:P1, Misc/Timezones, .Backend, Querying/GUI, .Team/42 :milky_way:, .Wanted: MLv2
