### ISSUE TITLE
Users without write permissions can't download csv

### ISSUE THREAD

**Issue by samiyabroudi** [metabase/metabase#3641] opened 2016-10-21 15:52 UTC
Hello!

So we're trying to make use of the new metabase permissions features. However, we've found that unless users have permissions to write native sql queries they can't download csv's from the questions we've written for them. We're hoping this is a mistake?

Thanks!!

# If you're filing an issue about a bug please include as much information as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

**Comment by salsakran** [comment] 2016-10-22 00:27
Yup, this is not the intended behavior! Let me try to reproduce it.

**Comment by salsakran** [comment] 2016-10-22 00:34
repro'd. 

How embarassing!

**Comment by camsaul** [comment] 2016-10-25 19:47
Fixed by #3648

**Closed by camsaul** 2016-10-25 19:47 UTC
Labels: API, Bug, Permissions
