### ISSUE TITLE
Combo Charts with Multiple Series shows 0 for some series

### ISSUE THREAD

**Issue by elawre02** [metabase/metabase#17155] opened 2021-07-21 18:50 UTC
**Describe the bug**
Multiple Series Charts, show all values checked seems to show 0 for the series. It seems to be happening when one of the measured metrics is in the billions. Removing either of the metrics, while keeping show value on points intact, properly shows the value of each metric. 

**Logs**
None

**To Reproduce**
config: 
<img width="764" alt="Screen Shot 2021-07-21 at 2 42 05 PM" src="https://user-images.githubusercontent.com/20978783/126542849-5a2dc55d-deea-426d-b78e-e18730786552.png">

when visualized: 
<img width="1418" alt="Screen Shot 2021-07-21 at 2 46 03 PM" src="https://user-images.githubusercontent.com/20978783/126543196-29d277ac-c86e-45fd-8885-a38b07a24745.png">

**Expected behavior**
Each value should show its proper format.

**Screenshots**
available above

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.9.1+1",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.9.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.9.1+1",
    "os.name": "Linux",
    "os.version": "5.4.0-1045-aws",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "athena",
      "redshift",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-07-20",
      "tag": "v1.40.2-SNAPSHOT",
      "branch": "?",
      "hash": "fc70e06"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Low - Medium

**Additional context**

**Comment by paoliniluis** [comment] 2021-07-22 01:17
Good find, thanks for reporting

**Comment by flamber** [comment] 2021-07-22 10:41
Duplicate of #16523

**Closed by flamber** 2021-07-22 10:41 UTC
Labels: .Frontend, Priority:P3, Querying/GUI, Type:Bug, Type:Completeness, Visualization/Charts
