### ISSUE TITLE
After using date filter,downloading  pivot table data lack column `day`

### ISSUE THREAD

**Issue by aCrazyOnion** [metabase/metabase#25538] opened 2022-09-21 08:56 UTC
description:

I use the dashboard's filter to choose a period of data,then I turn to the question which is filtered.After that,i download the question's data(this question's visualization is pivot table).As a result,the downloaded excel lack the `day` column.

steps to reproduce:
![image](https://user-images.githubusercontent.com/40635300/191461337-71315a0c-2136-4721-a2fd-7384c7f4998b.png)
![image](https://user-images.githubusercontent.com/40635300/191461411-a611fc42-b85d-444c-80eb-90d18914c4c0.png)

**Comment by flamber** [comment] 2022-09-21 09:05
Duplicate of #15034

**Closed by flamber** 2022-09-21 09:05 UTC
Labels: Type:Bug, .Needs Triage

**Comment by aCrazyOnion** [comment] 2022-09-21 09:12
> Duplicate of #15034

Thank you flamber
