### ISSUE TITLE
Filter on SQL Server on datetimeoffset return incorrect result 

### ISSUE THREAD

**Issue by nitzien** [metabase/metabase#11599] opened 2019-12-27 09:23 UTC
I have read through timezone troubleshooting guide and I understand SQL server is not supported for report time zone.  https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html. I am still trying my luck by reporting this as bug because passing datetime parameter in report timezone can fix this issue.  :) 

**Describe the bug**
Filter on SQL Server on dateimeoffset returns incorrect result.

**Logs**
None

**To Reproduce**
1. Have a sql server in table with column datetimeoffset. Have some data in this table spaced over couple of days and in different timzones. Data is stored in UTC timezone.
2. Have metabase report timezone set to something but UTC.
2. Create a report with native query - select timecolumn from example_table where {{timecolumn}}
3. Set variable type for variable timecolumn to field filter. Map it to example_table > timecolumn. Set widget type as Date Range
4. Run report to see if data is returned for a previous date or later date based on UTC timezone.

Note: Timezone is displayed correctly based on report timezone. Only filtering is issue here.

**Expected behavior**
Data should be filtered according to parameter based on report timezone.

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10-post-Ubuntu-0ubuntu1.118.04",
    "java.vendor": "Private Build",
    "java.vendor.url": "Unknown",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10-post-Ubuntu-0ubuntu1.118.04",
    "os.name": "Linux",
    "user.language": "en",
    "user.timezone": "Asia/Kolkata"
  },
  "metabase-info": {
    "databases": [
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "date": "2019-12-26",
      "tag": "v0.34.0"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}

**Severity**
We don't have very good solution to overcome this. 

**Additional context**

**Comment by flamber** [comment] 2019-12-27 11:53
Hi @nitzien 
It would be great if you could provide a sample table or some other way to reproduce this.
If I understand you correctly, the problem is caused between the visual filter widget date selector and the query being generated? It sounds like you're seeing #10824.

**Comment by flamber** [comment] 2020-05-24 21:43
Closing, since no reply - and likely duplicate of #10824.

**Closed by flamber** 2020-05-24 21:43 UTC
Labels: .Need More Info, Database/SQLServer, Misc/Timezones, Type:Bug
