### ISSUE TITLE
Pulse no results

### ISSUE THREAD

**Issue by qin4zhang** [metabase/metabase#6285] opened 2017-10-27 02:44 UTC
### Bugs
- Your browser and the version: Chrome 61.0.3163.79
- Your operating system: Windows 7
- Your databases: Postgres 9.6.5
- Metabase version: v0.24.1
- Metabase internal database: H2 (default)

- *Repeatable steps to reproduce the issue*
I have installed metabase of the above version and when I use pulse to sent email to test, it shows "no results", in fact the questions have results, how to solve it? oh ,I use foxmail to recive email.

Thanks for being part of the Metabase project!
-------

**Comment by camsaul** [comment] 2017-11-11 02:23
@qin4zhang are you sure the question has results? The pulse should show the same results as you see in the browser

**Comment by qin4zhang** [comment] 2017-11-11 03:44
@camsaul the question in the dashboard is the pie chart, and it shows great in the browser. But the pluse cannot show results in the email, it shows "No results", ten charts in a pluse are sent to the email. Maybe, they are too many charts??

**Comment by salsakran** [comment] 2017-12-04 20:36
@qin4zhang does this bug still show up in more recent versions?

**Comment by flamber** [comment] 2020-05-24 20:50
Closing, since no reply and there's no reproducible steps or logs.

**Closed by flamber** 2020-05-24 20:50 UTC
Labels: Priority:P3, Reporting/Pulses, Type:Bug
