### ISSUE TITLE
In the simple query builder, it's too hard to see and modify the selected grouping field(s)

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14297] opened 2021-01-07 01:13 UTC
If the data I'm working with has lots of fields to choose from in the Group By section, if I already have one or more groupings picked, it can be tough to see what I'm grouping by, or to change the granularity of a time or binned dimension.

Here's an example:

![changing-grouping](https://user-images.githubusercontent.com/2223916/103837916-97cf3400-5040-11eb-8b1e-1f4089291a11.gif)

One of many potential solutions to explore would be moving all selected groupings to the top of the Group By list after closing the summarize sidebar, so that when you reopen it they're at the top. (I don't think you'd want them to immediately move to the top when added, or immediately move down to their original position in the list when removed as a grouping, as that would cause a lot of things shifting out from under you.)

**Somewhat related:** the probably of changing time dimension granularity is exacerbated by this regression from way back in 0.33.3 or so when we accidentally removed the time series widgets at the bottom of the visualization: https://github.com/metabase/metabase/issues/11183

**Comment by notrom** [comment] 2021-01-07 03:53
Oh yes please. Related to #11019

**Comment by flamber** [comment] 2021-11-13 14:18
Fixed by #18587, but closing as duplicate of #11019, so there's only a single release note.

**Closed by flamber** 2021-11-13 14:18 UTC
Labels: Type:UX, Querying/GUI
