### ISSUE TITLE
MongoDb to support pivot table

### ISSUE THREAD

**Issue by xuheng925** [metabase/metabase#20450] opened 2022-02-11 16:01 UTC
Pls help scope the capability of support pivot table with mongodb. We currently use mongodb and pivot table is a major use for us, but now we have to write a hacky script to move incremental records from the mongodb tables to MySQL tables which causes tons of hassle for us.

_Originally posted by @xuheng925 in https://github.com/metabase/metabase/issues/15008#issuecomment-1036361622_

**Comment by flamber** [comment] 2022-02-11 16:02
Duplicate of #15008

**Closed by flamber** 2022-02-11 16:02 UTC
