### ISSUE TITLE
Implement visualization plug-in architecture for custom visualizations

### ISSUE THREAD

**Issue by howardmalec** [metabase/metabase#13889] opened 2020-11-25 11:07 UTC
There's ~170 open issues related to visualizations. Metabase's viz capabilities are limited to a small set of chart types (lines, tables, bars, maps, big numbers), especially when compared to alternative platforms like Mode and Apache Superset. 

Mirroring Apache Superset and Mode, Metabase should consider implementing a visualization plug-in architecture that makes it easy for users to add custom visualizations to Metabase. Examples include:

- [Superset](https://superset.apache.org/docs/installation/building-custom-viz-plugins/)
- [Mode](https://mode.com/blog/custom-charts-gallery/)

Right now every new visualization requires an issue to be filed and prioritized as a feature request. Metabase is missing many must-have viz types like [box-plots](https://github.com/metabase/metabase/issues/10783) and [sparklines](https://github.com/metabase/metabase/issues/10338). 

Enabling a self-service architecture to let users install custom visualizations from libraries like d3, kepler, etc. would eliminate a significant # of requests for custom viz that are currently requested as one-off implementations. 

Limited visualization capabilities are a major reason to consider alternatives over Metabase.

**Comment by flamber** [comment] 2020-11-25 11:28
Duplicate of #1710/#2318/#7351

**Closed by flamber** 2020-11-25 11:28 UTC
Labels: .Needs Triage, Type:New Feature
