### ISSUE TITLE
0.22.1 jar installation does not start on Open JDK 7

### ISSUE THREAD

**Issue by zaiddabaeen** [metabase/metabase#4242] opened 2017-01-26 08:42 UTC
I have just upgraded from 0.18 to 0.22.1 using jar installation. The jar does not work, and fails with this error message:

```
01-26 08:35:04 INFO metabase.util :: Loading Metabase...
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at clojure.lang.RT.loadClassForName(RT.java:2196)
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5778)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at metabase.core$loading__5569__auto____32127.invoke(core.clj:2)
	at metabase.core__init.load(Unknown Source)
	at metabase.core__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at clojure.lang.RT.loadClassForName(RT.java:2196)
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.Util.loadWithClass(Util.java:250)
	at metabase.core.<clinit>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: java.util.jar.JarFile$JarEntryIterator
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForNameNonLoading(RT.java:2181)
	at metabase.db$loading__5569__auto____6297.invoke(db.clj:1)
	at metabase.db__init.load(Unknown Source)
	at metabase.db__init.<clinit>(Unknown Source)
	... 42 more

```

0.22.0 version is unaffected, it can be run normally.

java version:
```
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

**Comment by MathiasDL** [comment] 2017-01-26 09:38
Installation of 0.22.1 on Elastic Beanstalk worked fine

**Comment by anki-code** [comment] 2017-01-26 09:43
I have no problem with migration JAR 0.22.0 → 0.22.1

**Comment by zaiddabaeen** [comment] 2017-01-26 10:35
I also ran 0.22.0 successfully then tried to run 0.22.1, but it didn't work. Same error.

**Comment by hannesroos** [comment] 2017-01-26 11:42
Same error here.

**Comment by tlrobinson** [comment] 2017-01-26 16:05
@zaiddabaeen @hannesroos Can you tell me your Java version (`java -version`)?

**Comment by tlrobinson** [comment] 2017-01-26 16:12
Reproduced with OpenJDK 7:

```
docker run -it --rm openjdk:7 sh -c 'curl -O http://downloads.metabase.com/v0.22.1/metabase.jar && java -jar metabase.jar'
```

Works fine with OpenJDK 8:

```
docker run -it --rm openjdk:8 sh -c 'curl -O http://downloads.metabase.com/v0.22.1/metabase.jar && java -jar metabase.jar'
```

**Comment by hannesroos** [comment] 2017-01-26 16:30
@tlrobinson 
`java version "1.7.0_121"
OpenJDK Runtime Environment (IcedTea 2.6.8) (7u121-2.6.8-1ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.121-b00, mixed mode)
`

**Comment by camsaul** [comment] 2017-01-26 17:16
Not sure why this would happen; one of the libraries we use might have stopped supporting Java 7. I've been trying to be careful when adding and updating dependencies but it happens sometimes. 

It might make sense to start requiring Java 8 at some point in the future because we already can't upgrade several of our libraries

**Comment by camsaul** [comment] 2017-01-26 17:16
But it works correctly with Oracle JRE 7, right? Weird

**Comment by camsaul** [comment] 2017-01-26 17:18
Oh looks like the new logic I added to speed up launch time by skipping loading Liquibase wasn't implemented in OpenJDK 7 yet

**Comment by camsaul** [comment] 2017-01-26 17:22
Java 8 has been out for 3 years now, it might make sense just to bump or minimum requirements

**Comment by salsakran** [comment] 2017-01-26 17:30
can we do the old thing if we check something like `System.getProperty("java.version").startsWith("1.7")`? 

My read is that there are a bunch of people on amis with old versions of the openjdk.

**Comment by camsaul** [comment] 2017-01-26 17:42
We could certainly do that but we'd have to use reflection everywhere and dynamically load the missing classes we're using, do dynamic runtime method resolution in order to invoke their methods, etc. It would end up being messy 💔

**Comment by salsakran** [comment] 2017-01-26 17:52
@zaiddabaeen @hannesroos how did you pick which version of OpenJDK to run? Are you using specific AWS AMIs or Docker base images?

**Comment by salsakran** [comment] 2017-01-26 23:12
closed and fixed in the new release. 
@zaiddabaeen @hannesroos please try the new version (0.22.2)

**Closed by salsakran** 2017-01-26 23:12 UTC
Labels: Bug, Priority/P1
