### ISSUE TITLE
Error when creating custom column from summarized data

### ISSUE THREAD

**Issue by engenex** [metabase/metabase#15366] opened 2021-03-29 08:10 UTC
**Describe the bug**
"There was a problem with your question"
Attempted to create a "percentage change" custom column from summarized data for use in a Combo Chart.
Chart Bars would represent year-over-year performance by month-of-year and the overlaying line chart will represent the percentage change between the two years by month-of-year.

**Logs**
`Column "source.Created in 2018" not found; SQL statement: CREATE FORCE VIEW PUBLIC._4 AS SELECT "source"."Created in 2018" AS "Created in 2018", "source"."Created in 2017" AS "Created in 2017", "source".CREATED_AT AS CREATED_AT, "source"."count-where" AS "count-where", "source"."count-where_2" AS "count-where_2", (CAST(("source"."Created in 2018" - "source"."Created in 2017") AS DOUBLE) / CASE WHEN ("source"."Created in 2017" = 0) THEN NULL ELSE "source"."Created in 2017" END) AS "Percent change" FROM ( SELECT MONTH(PUBLIC.ORDERS.CREATED_AT) AS CREATED_AT, SUM(CASE WHEN ((PUBLIC.ORDERS.CREATED_AT >= ?1) AND (PUBLIC.ORDERS.CREATED_AT <= ?2)) THEN 1 ELSE 0.0 END) AS "count-where", SUM(CASE WHEN ((PUBLIC.ORDERS.CREATED_AT >= ?3) AND (PUBLIC.ORDERS.CREATED_AT <= ?4)) THEN 1 ELSE 0.0 END) AS "count-where_2" FROM PUBLIC.ORDERS GROUP BY MONTH(PUBLIC.ORDERS.CREATED_AT) ORDER BY 1 ) "source" [42122-197]`

**To Reproduce**
1. Sample DB > Orders
2. Summarize > Custom Expression:
  Created in 2017:  `CountIf(between([Created At], "2017-01-01", "2017-12-31"))`
  Created in 2018: `CountIf(between([Created At], "2018-01-01", "2018-12-31"))`
  by
  Created At: Month of year
3. Visualize > No Errors.  Year-over-year data is displayed correctly
4. Show Editor > Add Custom Column:
  Percent change: `([Created in 2018] - [Created in 2017]) / [Created in 2017]`
5. Visualize > "There was a problem with your question"

**Expected behavior**
I expected the custom column to appear with no errors.
I assumed (incorrectly?) that this issue was fixed in #12762 and the fix was already applied to stable releases?

**Screenshots**
![image](https://user-images.githubusercontent.com/769585/112805262-533bbd80-90b0-11eb-99fc-773844f6dd12.png)

**Severity**
Low severity.  There is no blocking.  Possibly user-error as I'm not an expert user.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_282-8u282-b08-0ubuntu1~16.04-b08",
    "java.vendor": "Private Build",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_282",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.282-b08",
    "os.name": "Linux",
    "os.version": "4.4.0-197-generic",
    "user.language": "ko",
    "user.timezone": "Asia/Seoul"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.38.0",
      "date": "2021-02-16",
      "branch": "release-x.38.x",
      "hash": "471aa51"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2021-03-29 08:24
Duplicate of #13857

**Closed by flamber** 2021-03-29 08:24 UTC
