### ISSUE TITLE
It is possible to enter and submit text in the SQL `Number` filter

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16771] opened 2021-06-25 13:32 UTC
**Describe the bug**
SQL filter widget of type `Number` has input with the type `text` allowing one to type a string, which triggers an error on the backend `Unparseable number: "string"`. We should be smarter about this and use FE to guard against such behavior.
Using `input type="number"` would prevent this from happening ever again.

**To Reproduce**
1. From the home page click the SQL icon in the top right corner
2. In SQL editor, type `SELECT * FROM products WHERE products.rating = {{numberFilter}}`
3. In the sidebar on the right side, choose variable type (change it from "Text" to "Number")
4. Notice that the filter widget above sql editor now changes to reflect this
  - there is a number icon
  - the label/placeholder says "Numberfilter"
5. If you inspect it in the dev tools, you'll notice that the `input` field's type is still set to `text`
6. Click on the filter widget and type "foo"
7. Click the play icon to run the query
8. It fails with an error
![image](https://user-images.githubusercontent.com/31325167/123431913-15c0d080-d5ca-11eb-988e-f0545ca42ced.png)

**Expected behavior**
It shouldn't be possible to even enter/submit text for the number filter.

**Information about your Metabase Installation:**
local dev, `master`, 8bd6ccf5c63ed7ab526828c5a12eae6432572c2d

**Severity**
P3, because the validation on the backend still works as expected.

**Comment by flamber** [comment] 2021-06-25 13:34
Duplicate of #15295

**Closed by flamber** 2021-06-25 13:34 UTC
Labels: .Tech Debt or Refactoring, Querying/Native, Type:UX
