### ISSUE TITLE
Reordering columns in a question breaks join

### ISSUE THREAD

**Issue by carstenkadmos** [metabase/metabase#27544] opened 2023-01-06 09:54 UTC
**Describe the bug**
When having a question with a join of two or more tables and wanting to reorder the columns, Metabase drops all the joins. Reordering columns is not possible.

**Expected behavior**
Either ordering is disabled for joins, or preferred reordering columns does not break joins and works.

**Information about your Metabase Installation:**

Information about your Metabase Installation:
```
{
"browser-info": {
"language": "en-GB",
"platform": "MacIntel",
"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
"vendor": "Google Inc."
},
"system-info": {
"file.encoding": "ANSI_X3.4-1968",
"java.runtime.name": "OpenJDK Runtime Environment",
"java.runtime.version": "11.0.16+8-post-Debian-1deb10u1",
"java.vendor": "Debian",
"java.vendor.url": "https://tracker.debian.org/openjdk-11",
"java.version": "11.0.16",
"java.vm.name": "OpenJDK 64-Bit Server VM",
"java.vm.version": "11.0.16+8-post-Debian-1deb10u1",
"os.name": "Linux",
"os.version": "5.4.202+",
"user.language": "en",
"user.timezone": "Etc/UTC"
},
"metabase-info": {
"databases": [
"bigquery-cloud-sdk"
],
"hosting-env": "unknown",
"application-database": "postgres",
"application-database-details": {
"database": {
"name": "PostgreSQL",
"version": "13.7"
},
"jdbc-driver": {
"name": "PostgreSQL JDBC Driver",
"version": "42.5.0"
}
},
"run-mode": "prod",
"version": {
"date": "2022-12-03",
"tag": "v0.45.0",
"branch": "release-x.45.x",
"hash": "4e41d76"
},
"settings": {
"report-timezone": null
}
}
}
```

**Severity**
Medium. Information cannot be shown in the place desired.

**Comment by flamber** [comment] 2023-01-06 10:01
Duplicate of #27464

**Closed by flamber** 2023-01-06 10:01 UTC
Labels: Type:Bug, .Needs Triage
