### ISSUE TITLE
It's not possible to put a box somewhere in the middle of the dashboard 

### ISSUE THREAD

**Issue by saeedesmaili** [metabase/metabase#17272] opened 2021-08-02 15:33 UTC
After upgrading our Metabase to the latest one, when I want to put a text box or a chart somewhere in the middle (to organize the dashboard in a visually appealing way), the box goes back to the top of the page, if there isn't any box above it. In the previous versions, the box was staying in wherever the user wanted.

**To Reproduce**
1. Create a new dashboard or edit any saved dashboard
2. Click on "edit dashboard"
3. Try to insert a text box or a chart somewhere in the middle of the page (not top of the page)
4. The box will go back to the top of the page

**Expected behavior**
The box should stay wherever the user puts it.

**Screenshots**
![image](https://im3.ezgif.com/tmp/ezgif-3-891622d718d9.gif)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome
- Your operating system: Ubuntu
- Your databases: Postgres
- Metabase version: v0.40.1

**Severity**
Low priority.

**Comment by paoliniluis** [comment] 2021-08-02 20:06
Hi @saeedesmaili, I believe this one is a duplicate of https://github.com/metabase/metabase/issues/17272

**Closed by paoliniluis** 2021-08-02 20:06 UTC
Labels: .Needs Triage, Type:Bug

**Comment by saeedesmaili** [comment] 2021-08-02 20:15
@paoliniluis I think you have linked to this issue.

**Comment by flamber** [comment] 2021-08-03 09:06
Duplicate of #16786
