### ISSUE TITLE
New dashboard does not show up under dashboards

### ISSUE THREAD

**Issue by coussej** [metabase/metabase#3097] opened 2016-08-02 07:44 UTC
Created a dashboard:

<img width="705" alt="screen shot 2016-08-02 at 09 41 47" src="https://cloud.githubusercontent.com/assets/9944663/17320783/8b07e7a0-5895-11e6-840b-e7112afc9a6a.png">

and it shows up under recently viewed, gets mentioned when I add questions to it, but it's not available under dashboards:

<img width="1178" alt="screen shot 2016-08-02 at 09 41 30" src="https://cloud.githubusercontent.com/assets/9944663/17320803/a7f99fa2-5895-11e6-81fd-82c39cb7ad40.png">

*  ~~I am using the ___________ browser.~~
*  My computer's OS is OSX El Capitan.
*  I'm running Metabase locally with the Mac App and it is using the H2 database.
*  My data is in a Postgres database. 
*  My Metabase version is 0.19.

**Comment by marktheunissen** [comment] 2016-08-02 13:10
Yeah, I also encountered this. You have to refresh the page (browser refresh) in the web app version, in the Mac version... not sure...

**Comment by camsaul** [comment] 2016-08-02 19:05
Duplicate of #2871.

**Closed by camsaul** 2016-08-02 19:05 UTC
Labels: Duplicate
