### ISSUE TITLE
SQL date parameter relative default value

### ISSUE THREAD

**Issue by federicokeen** [metabase/metabase#3211] opened 2016-08-17 00:08 UTC
This is a question that i'm not sure how to solve with Metabase, but there is probably a way. 

I have 3 or 4 SQL questions, that have a start_date and an end_date parameter. Basically I want to add them to a dashboard with a parameter that defaults to show the last 2 weeks, so it should default to something like end_date = `CURDATE()` and start_date =` CURDATE() - X Days` by default if nothing is chosen, but allow the user to change the dates...

How can I do this?

**Comment by federicokeen** [comment] 2016-08-17 00:17
I think this might be a duplicate of https://github.com/metabase/metabase/issues/3156

**Comment by salsakran** [comment] 2016-08-17 00:32
You should probably use a "relative date" dashboard filter widget -

![screen shot 2016-08-16 at 5 30 39 pm](https://cloud.githubusercontent.com/assets/107439/17720427/abcd33c2-63d6-11e6-885f-fafe44ab40d2.png)


![screen shot 2016-08-16 at 5 30 49 pm](https://cloud.githubusercontent.com/assets/107439/17720426/abbadd58-63d6-11e6-8549-f627c20004eb.png)

we don't support 2 weeks out of the box, but we can probably add that. 

You would then use something similar to 
```
SELECT count(*)
FROM products
WHERE {{created_at}}
```
 and mark `created_at` as a field filter.

**Comment by federicokeen** [comment] 2016-08-17 00:35
Mmm but the query is something like:

set @start_date = 'some_date';
set @end_date = 'some_date';

`select * from table where field between @start_date - INTERVAL X DAY and @end_date + INTERVAL Y DAY`

**Comment by salsakran** [comment] 2016-08-17 00:43
you'd need to parameterize `X` and `Y` in the above and link that to a "Other filter".

We'd STRONGLY suggest using a field filter in this context however as it dramatically simplifies the SQL and linkages in question.

**Comment by camsaul** [comment] 2016-09-03 01:11
@federicokeen I think you're right, this is a duplicate of #3156.

Closing as duplicate.

**Closed by camsaul** 2016-09-03 01:11 UTC
Labels: Duplicate
