### ISSUE TITLE
Can google tag manager be used for metabase to track which user is using particular questions/dashboards?

### ISSUE THREAD

**Issue by adysssal** [metabase/metabase#12099] opened 2020-03-11 05:39 UTC
Can google tag manager be used for metabase to track which user is using particular questions/dashboards? The activity window is does not suffice investigation on the most used question/dashboard by which dept.

**Comment by flamber** [comment] 2020-03-11 10:15
Hi @adysssal 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
The Enterprise Edition currently has audit functionality: https://www.metabase.com/docs/latest/enterprise-guide/audit.html
You might want to look at this too: https://discourse.metabase.com/t/metabase-metadata-sql/3688
Probably a duplicate of #5462

**Closed by flamber** 2020-03-11 10:15 UTC
Labels: .Needs Triage, Type:Question
