### ISSUE TITLE
Support pre-sql satements

### ISSUE THREAD

**Issue by liorbenzeev** [metabase/metabase#14564] opened 2021-01-28 11:26 UTC
**Is your feature request related to a problem? Please describe.**
I want to execute pre-sql statement for two reasons
1. To set the user time zone on the session so the result would be aligned with the user time zone
2. To tag the user sql on the data warehouse by setting tag on the user session

**Describe the solution you'd like**
1. I will be able to define a cross database configuration a list of pre-sql statements
2. The pre-sql statements would be able to include placeholder like {user-time-zone} and {question-name}
3. When a user login to Metabase there is a need to be able to associate variables to this user like the {user-time-zone}

**Describe alternatives you've considered**
No alternatives

**How important is this feature to you?**
Note: the more honest and specific you are here the more we will take you seriously. 
Very important, it is a must, as well I assume it is a must for other enterprise organizations

**Additional context**

**Comment by flamber** [comment] 2021-01-28 11:49
Hi @liorbenzeev 
Sounds like a duplicate of #4284, since there's more than just session timezone involved, and attributes are part of the Enterprise Edition: https://www.metabase.com/docs/latest/enterprise-guide/data-sandboxes.html

**Comment by liorbenzeev** [comment] 2021-01-28 11:59
Hi @flamber 

According to the sandbox configuration the user variables can be used only to filter the question generated SQL.
Is it possible with sandboxing to add a pre-sql statement to change the data warehouse session timezone?

For example if the question SQL is
_select time,order from Orders;_

To support timezone per user we would need this SQLs to be executed,
_alter session set TIMZE_ZONE={{user_time_zone}};
select time,order from Orders;_

**Comment by flamber** [comment] 2021-01-28 12:19
@liorbenzeev You can parse user attributes to SQL parameter: https://www.metabase.com/docs/latest/enterprise-guide/data-sandboxes.html#example-2-using-variables-in-a-saved-question
But it will likely not completely work as expected, since timezones are not just handled in the connection session - it's also part of the UI. Have a look at #14055 and #14056, which details current state and what we're trying to do.
I'm going to close this in favor of #4284 and #5147. What will end up in Open Source vs Enterprise Edition is still to be determined.

**Closed by flamber** 2021-01-28 12:19 UTC
Labels: .Needs Triage, Type:New Feature
