### ISSUE TITLE
CSV date

### ISSUE THREAD

**Issue by Alejandrasm1** [metabase/metabase#40426] opened 2024-03-21 07:46 UTC
### Describe the bug

When I try to download this question in CSV format the date is incorrect. I try to download 2024 but in the csv it shows as 2025

https://luxury-tenerife.metabase.wavyssa.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJhZ2dyZWdhdGlvbiI6W1sic3VtIixbImZpZWxkIiwxOTAxLHsiYmFzZS10eXBlIjoidHlwZS9JbnRlZ2VyIn1dXSxbIm1heCIsWyJmaWVsZCIsMTg5OCx7ImJhc2UtdHlwZSI6InR5cGUvRGF0ZVRpbWVXaXRoTG9jYWxUWiIsInRlbXBvcmFsLXVuaXQiOiJkYXkifV1dXSwiYnJlYWtvdXQiOltbImZpZWxkIiwxODk1LHsiYmFzZS10eXBlIjoidHlwZS9EYXRlIiwidGVtcG9yYWwtdW5pdCI6ImRheSJ9XSxbImZpZWxkIiwxODk0LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLFsiZmllbGQiLDE5MDQseyJiYXNlLXR5cGUiOiJ0eXBlL0Jvb2xlYW4ifV0sWyJmaWVsZCIsMjk5MSx7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCIsImpvaW4tYWxpYXMiOiJDaGFubmVsIn1dLFsiZmllbGQiLDE5MDUseyJiYXNlLXR5cGUiOiJ0eXBlL0ludGVnZXIiLCJiaW5uaW5nIjp7InN0cmF0ZWd5IjoiZGVmYXVsdCJ9fV0sWyJmaWVsZCIsMTQwMyx7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCIsImpvaW4tYWxpYXMiOiJIb3RlbCJ9XV0sImpvaW5zIjpbeyJhbGlhcyI6IkNoYW5uZWwiLCJjb25kaXRpb24iOlsiYW5kIixbIj0iLFsiZmllbGQiLDE5MDUseyJiYXNlLXR5cGUiOiJ0eXBlL0ludGVnZXIifV0sWyJmaWVsZCIsMjk5OCx7ImJhc2UtdHlwZSI6InR5cGUvSW50ZWdlciIsImpvaW4tYWxpYXMiOiJDaGFubmVsIn1dXSxbIj0iLFsiZmllbGQiLDE4OTkseyJiYXNlLXR5cGUiOiJ0eXBlL0ludGVnZXIifV0sWyJmaWVsZCIsMjk5Nix7ImJhc2UtdHlwZSI6InR5cGUvSW50ZWdlciIsImpvaW4tYWxpYXMiOiJDaGFubmVsIn1dXV0sInNvdXJjZS10YWJsZSI6MTk1fSx7ImFsaWFzIjoiSG90ZWwiLCJjb25kaXRpb24iOlsiPSIsWyJmaWVsZCIsMTkwNSx7ImJhc2UtdHlwZSI6InR5cGUvSW50ZWdlciJ9XSxbImZpZWxkIiwxNDAyLHsiYmFzZS10eXBlIjoidHlwZS9JbnRlZ2VyIiwiam9pbi1hbGlhcyI6IkhvdGVsIn1dXSwic291cmNlLXRhYmxlIjo3MX1dLCJzb3VyY2UtdGFibGUiOjE0MywiZmlsdGVyIjpbImFuZCIsWyJ0aW1lLWludGVydmFsIixbImZpZWxkIiwxODk1LHsiYmFzZS10eXBlIjoidHlwZS9EYXRlIn1dLDIsInllYXIiLHsiaW5jbHVkZS1jdXJyZW50Ijp0cnVlfV0sWyIhPSIsWyJmaWVsZCIsMTQwMyx7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCIsImpvaW4tYWxpYXMiOiJIb3RlbCJ9XSwiSG90ZWwgVGVzdCIsIkhvdGVsIFRFc3QiXSxbImJldHdlZW4iLFsiZmllbGQiLDE4OTUseyJiYXNlLXR5cGUiOiJ0eXBlL0RhdGUifV0sIjIwMjQtMTItMjkiLCIyMDI0LTEyLTMxIl1dfX0sImRpc3BsYXkiOiJ0YWJsZSIsImRpc3BsYXlJc0xvY2tlZCI6dHJ1ZSwicGFyYW1ldGVycyI6W10sInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsicGl2b3RfdGFibGUuY29sdW1uX3NwbGl0Ijp7ImNvbHVtbnMiOltbImZpZWxkIiwxODk1LHsiYmFzZS10eXBlIjoidHlwZS9EYXRlIiwidGVtcG9yYWwtdW5pdCI6ImRheSJ9XSxbImZpZWxkIiwxODk0LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dXSwicm93cyI6W1siZmllbGQiLDE5MDQseyJiYXNlLXR5cGUiOiJ0eXBlL0Jvb2xlYW4ifV0sWyJmaWVsZCIsMjk5MSx7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCIsImpvaW4tYWxpYXMiOiJDaGFubmVsIn1dLFsiZmllbGQiLDE0MDMseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQiLCJqb2luLWFsaWFzIjoiSG90ZWwifV1dLCJ2YWx1ZXMiOltbImFnZ3JlZ2F0aW9uIiwwXV19LCJwaXZvdF90YWJsZS5jb2x1bW5fd2lkdGhzIjp7ImxlZnRIZWFkZXJXaWR0aHMiOls4MiwxMzMsMTUwXSwidG90YWxMZWZ0SGVhZGVyV2lkdGhzIjozNjUsInZhbHVlSGVhZGVyV2lkdGhzIjp7fX0sInRhYmxlLnBpdm90X2NvbHVtbiI6InN1Y2Nlc3MiLCJ0YWJsZS5jZWxsX2NvbHVtbiI6InN1bSIsImNvbHVtbl9zZXR0aW5ncyI6eyJbXCJuYW1lXCIsXCJtYXhcIl0iOnsiY29sdW1uX3RpdGxlIjoiTGFzdCBTZW5kIERhdGUifX19LCJvcmlnaW5hbF9jYXJkX2lkIjoyMzB9

<img width="1234" alt="333" src="https://github.com/metabase/metabase/assets/163538527/8dec0260-0175-4a51-a61a-08721329964f">

### To Reproduce

1. Go to the link above
2. Click on download csv
3. See error

### Expected behavior

Show correct date

### Information about your Metabase installation

```JSON
edge
```

### Severity

High

**Comment by calherries** [comment] 2024-03-21 08:20
Assuming this is version 0.49.0, this is probably a dupe of https://github.com/metabase/metabase/issues/40306. Please reopen if this is an older version

**Closed by calherries** 2024-03-21 08:20 UTC
Labels: Type:Bug, .Needs Triage
