### ISSUE TITLE
Multiple filters cause all cards to be faded

### ISSUE THREAD

**Issue by danielsitnik** [metabase/metabase#4220] opened 2017-01-24 13:50 UTC
Currently when you apply a filter to a dashboard it will fade out all cards that are not affected by that filter. I understand this behavior is about usability, so users can easily distinguish what data is being affected by the filter they applied. However, if you happen to have more than one filter and apply them all at once, the end result is that all cards get faded and the dashboard becomes hard to read.

As an example, I have the following dashboard where initially users set the Company ID filter. This fills the data for 3 cards and fades out the bottom left one (Prize Winners):
![filter1](https://cloud.githubusercontent.com/assets/1395838/22249492/51da6132-e22a-11e6-8c98-d11b97dd9cfd.png)

If users want more detail, they can pick the "ID" number from the top left card and insert it into the "Prize ID" filter. This fills the data for the bottom left card, but at the same time fades out the other 3 cards... resulting in a totally faded dashboard that is hard to read:
![filter2](https://cloud.githubusercontent.com/assets/1395838/22249555/a88454de-e22a-11e6-8c8a-a01ec6c1c8e6.png)

Maybe the frontend could not fade everything when more than 1 filter is applied?

I'm using 0.22 now but have been experiencing this since filters were introduced in an older release.

Browser: Chrome 55.0.2883.95 (64-bit)
OS: OS X El Capitan (10.11)
Database: MySQL 5.5
Metabase: 0.22
Hosting: Amazon Linux (runs inside my EC2 instance on AWS)
Internal DB: H2

Thanks!

**Comment by tlrobinson** [comment] 2017-01-24 17:56
I don't think the issue is multiple filters, per se. If both filters were applied to a card, that card wouldn't be faded out. The problem is you have different filters applied to different cards.

We fade out cards that aren't mapped to an active filter because it would be misleading to suggest the data being shown is being filtered when it is not. I think the expectation was that you'd have dashboards related to a single topic and all the parameters would apply to all the cards, or perhaps only have filters for one "topic" on a dashboard active at any given time.

Solutions:

At a minimum we could detect which filters are "mutually exclusive" and prevent or warn when trying to set a filter that would cause every card to be faded, but that breaks down if at least one card is mapped to both filters.

 Alternatively we could do something less obtrusive than fading the cards out.

**Comment by mazameli** [comment] 2017-01-24 18:53
What tlrobinson said. Another possible route to explore is dashboard card groupings or sections which could have scoped filters, but that adds a fair bit of complexity. When we originally were designing this feature, we also explored not fading the cards, but instead putting visual indications to show which cards were being affected by which filters, but it makes a dashboard cluttered and hard to reason about.

**Comment by dtheodor** [comment] 2017-02-16 12:48
I don't see the reasoning behind the current fade out behavior. As a user, I expect my filters to apply in the charts where the filters make sense, and this works fine. However, I don't expect my other charts to stop working when the filter does not apply to it. The fade out behavior makes the charts barely visible and indicates that "this chart is no longer valid". What does it mean for a chart to be valid? It is valid when it fulfills the filtering requirements. If a filter's data is not contained at all in the chart data, it means the filter is irrelevant for the chart. Is it better to consider the chart invalid then, or to still consider the chart relevant? I think that, if someone chose to put the chart in a dashboard with a filter that does not concern the chart, then the chart is relevant and we should always consider the chart valid. At least for my use-cases this is the only scenario.

**Comment by mattes** [comment] 2017-03-16 17:38
Just ran into this as well. Instead of fading out, maybe show the filter applied on each card.

**Comment by sailxjx** [comment] 2017-05-12 10:29
#5081

**Comment by mazameli** [comment] 2017-05-19 23:35
So, clearly this has caused a fair amount of confusion with users (particularly because this behavior wasn't happening for a brief period in version 0.23, and then was "fixed" in 0.24).

The way that we think we want to fix this more holistically is to provide a feature to allow sections or groupings in dashboards, and to have filters apply to groups, so that clarity about what is being filtered is preserved.

In the interim, a bandaid would be something like the below design, where instead of fading out cards that aren't mapped to an active filter, we'd show a warning icon with a hover state that would enumerate which active filters don't apply to that card. Recall that currently in this state, we fade out all the cards (like in danielsitnik's original example).

![warning icons hover](https://cloud.githubusercontent.com/assets/2223916/26270598/f135a4a4-3cb0-11e7-9880-812d93f92795.png)

The super extreme, edge case-y, worst-case scenario would be a hypothetical and wacky dashboard that had a bunch of filters, none of which are mapped to every card, and all of which are active. In that case, every card would have a warning, since all of them would have at least one active filter to which they are not mapped. 

![all filters](https://cloud.githubusercontent.com/assets/2223916/26270602/fd1649b8-3cb0-11e7-9c1d-9cd9ca1b6eb6.png)

**Comment by kdoh** [comment] 2017-05-19 23:43
@mazameli My initial reaction is that the use of the warning icon here makes me think something might be wrong with the card and that it doesn't really match what's going on semantically (we also use that icon treatment for actual card result errors so that might create confusion). I think I agree the long term solution is finding ways to avoid the lack of application all together, but I wonder if in the interim we could use a different visual cue like mimicking the blue border of the filter inputs on cards that are affected by filters.

**Comment by mazameli** [comment] 2017-05-20 00:11
Yeah, fair point about the specific icon. I don't think we're going to want to highlight all cards that _are_ being filtered, since I think that's the positive state, and bordering all of them could get pretty noisy. Not to mention I think one advantage about the design above is that it provides some clarity about _which_ filters aren't acting on a given card.

**Comment by sailxjx** [comment] 2017-05-22 01:43
@mazameli Great design!
Metabase have a lot of behaviors hide in the logic of code (for example, the card style in pulses is decided by columns numbers and orders), can we have a FAQ list to record all these questions? Finally, I hope we can discuss features and problems in a slack channel.

**Comment by mazameli** [comment] 2017-05-26 00:24
Two more quick thoughts on this:

1. In the interim (i.e., before doing dashboard card groups), we could just revert back to the state before we "fixed" this. I.e., we don't fade the cards out, full stop.
2. An additional interim approach I just thought of was to put the info/warning icon on the filter(s) itself rather than each card, like so:

![filter warnings](https://cloud.githubusercontent.com/assets/2223916/26475750/850ab856-416e-11e7-89f7-ff35842568f7.png)

Maybe when hovering over that info icon, we also highlight the cards that aren't connected to the filter:

![filter warnings copy](https://cloud.githubusercontent.com/assets/2223916/26475825/ee8778a0-416e-11e7-8507-e959535119f1.png)

**Comment by sailxjx** [comment] 2017-05-26 01:29
@mazameli I don't think this is a good idea. The problem is on the card, not on the filter, and we need to know which card is not apply the filter. So just use the corner tip please.

**Comment by VasekPurchart** [comment] 2017-06-16 16:58
I have also encountered this, but before I found this issue I wanted to propose another solution - I think the graying out or icons etc. has one purpose - warning the user, that there *might* be seeing something different than they were thinking they are seeing. Which is completely valid and I am not sure, if this will completely go away with the future solutions.

I think the key in this is in the *might*, because its all about user expectations. But then there are situations where we *know for sure* that can't have any impact on other cards. I think this will be mostly case when using filters to not actually filter, but rather specify a user required parameter. In my case this is for example a timezone parameter, which is required for all timeseries data, but logically would have no impact on a "total number" card.

The solution to these *know for sure* cases could be, that like now you can pick for each card which parameter matches the filter, you could instead of that pick something like `this card is not affected by this filter`, which would mean that the warning (however visually is represented) would not show for a card with this picked.

This could be also used for other cases, where it is indeed about filtering, but the dashboard has a different usecase, like in the opening comment of this issue. It would all be about how the dashboard is configured based on the actual usecases, which is why I like this solution.

---

Other than what I proposed I like the 2nd interim suggestion in https://github.com/metabase/metabase/issues/4220#issuecomment-304158843.

@mazameli is there already an open issue (or something) for the card groups? It seems really interesting and would like to read more on that, but I couldn't find anything.

**Comment by sailxjx** [comment] 2017-07-20 01:41
I find this problem is still exists in 0.25-rc. This behavior affects almost every dashboard. Please pay attention to this problem, it may be more important than add other `features`. @camsaul @mazameli @tlrobinson

**Comment by rthouvenin** [comment] 2017-08-22 13:05
I think that with a proper title and description, the user who creates the dashboard can make it clear what a card shows and that a filter does not apply. For that reason, I wouldn't be against removing the existing cue and come back to the "fixed" version as an interim solution.
I also liked @kdoh's suggestion to use border colors, it doesn't strike me as too noisy.

In any case, this is currently quite confusing for all my use cases, can someone point me to the commit that removes this fading out, so I can fork and cherry-pick while a long-term solution is sought and developed? Is it the revert of https://github.com/metabase/metabase/commit/0ab5f2c65328a656c368da51b79bea19f7c94941?

**Comment by mazameli** [comment] 2017-08-25 23:44
Gonna try and resurrect this discussion and see if we can find an incremental way to move forward.

I've tried to address some of the concerns voiced in the comments about the designs I proposed, and I'm thinking more that we want to address the core issue ("what is being filtered?") rather than trying to highlight an "error" or "warning" state. So one thing we could do is spell out the actual filter values that apply to each card:

![filter-labels](https://user-images.githubusercontent.com/2223916/29735806-a5d1f326-89b0-11e7-9cae-1717853f978f.png)

Pros:
- seems very clear
- no ambiguity about what's being filtered, and by which filter(s)
- no additional icons

Cons:
- could be redundant if all filters apply to all cards
- takes up space, and charts might have to slightly resize in order to accommodate the filter labels

**Comment by MiBaDK** [comment] 2017-08-27 05:51
Looks very slick. Great idea!

**Comment by salsakran** [comment] 2017-09-06 00:20
I'm a little skittish on just how much text is involved, and the fact that it looks like it is a description to me.

**Comment by salsakran** [comment] 2017-09-06 00:21
Also, it's really weird that some cards but not others are being filtered. I can't help but feel like what is really being done here is that a filter is tied to a group of cards. I.e. how often will people have 2 filters on 3 cards, where cards 1+2 are tied to filter 1 and 2+3 are tied to filter 2?

**Comment by MiBaDK** [comment] 2017-09-06 09:18
I have multiple dashboards right now with the issue.

One example is a dashboard for my quarterly reports.

![dbfade](https://user-images.githubusercontent.com/27769361/30104061-1cea1752-9327-11e7-9548-755b398f4519.png)

Another approach could be just to show an icon as when there is additional info on a dashboard

![screen shot 2017-09-06 at 5 17 04 pm](https://user-images.githubusercontent.com/27769361/30104163-5fe40e28-9327-11e7-9874-eb0f2f432242.png)

**Comment by swatisinghi** [comment] 2017-09-25 09:03
+1, this is a little confusing. I just upgraded from 0.23.1 to 0.25.2. Will be great if this fading out can be avoided. Also, I am no longer able to right click on a card and open it in a new tab.

**Comment by mazameli** [comment] 2017-09-25 16:42
@swatisinghi just FYI, the issue you mentioned regarding not being able to open card links in new windows or tabs is being tracked here: https://github.com/metabase/metabase/issues/5168

**Comment by eddies** [comment] 2017-11-15 06:08
I really like @mazameli's [framing of the problem above](https://github.com/metabase/metabase/issues/4220#issuecomment-325057670) as answering the question "what is being filtered?" rather than trying to highlight an "error" or "warning" state.

I think the specific way of answering that question still needs discussion (describing each filter in effect will definitely take too much space in a number of cases). I'm in favor of lighter-weight cues to answer the question of "what is being filtered?". For example, when hovering over a specific card, highlight each applied filter. 

But frankly, I'd much rather have @mazameli's suggestion as-is than the current behavior or to spend weeks (let alone months) discussing a mythical, "ideal" solution.

**Comment by MarkRx** [comment] 2018-02-02 14:04
This is a problem for me. I plan on having multiple independent but related cards on the same dashboard where each card uses a different independent filter. The current filtering behavior makes this impossible:

> When you activate a dashboard filter, any card that isn’t wired up to the filter will fade out to indicate it’s not being filtered. If you activate more than one filter at the same time, cards will fade out unless they’re wired up to every active filter.

**Comment by MarkRx** [comment] 2018-03-16 16:45
Did this get fixed in 0.28.1? The cards don't fade anymore (which is good).

**Comment by sfortis** [comment] 2018-06-20 15:27
for me is pretty bad, since users now are getting confused wherever putting filter and some data are not updated. So they consider the filters "broken" :(

**Comment by flamber** [comment] 2020-03-11 16:01
I'm going to close this, since I don't see us reverting to faded cards.

**Closed by flamber** 2020-03-11 16:01 UTC
Labels: .Proposal, Reporting/Dashboards, Type:UX
