### ISSUE TITLE
Export is not working with filter

### ISSUE THREAD

**Issue by sumputhi** [metabase/metabase#5868] opened 2017-09-01 03:29 UTC
Metabase filter is working correctly, however, when export, filter simply not work, it will always export all. Please help update it.

**Comment by salsakran** [comment] 2017-09-07 00:56
What kind of question is this, what version of MB are you on, and what is the filter?

**Comment by mvrabel** [comment] 2017-09-07 07:43
@salsakran I think (s)he reffers to https://github.com/metabase/metabase/issues/5295 :)

**Comment by camsaul** [comment] 2017-12-07 03:07
Sounds like a duplicate of #6407, which we fixed in 0.27.1. @sumputhi please chime in if that doesn't sound right. Closing as duplicate

**Closed by camsaul** 2017-12-07 03:07 UTC
Labels: Need More Info
