### ISSUE TITLE
Is there a way to merge bar chart stacked data when more than 20 cols?

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#5734] opened 2017-08-12 12:21 UTC
As in PIE chart that merge data into something like `OTHER`, is there a way in bar chart to merge 21st, 22nd, etc columns into a cell called other?

I'm having problem when end user change date resolution (daily, monthly, yearly). When he goes to monthly or yearly more status is stacked and bar chart gives error.

Is there any workaround for now to solve this problem?

This is my query in Metabase:

```
SELECT DATE_FORMAT(start_time, {{resolution}}) start_time, status, count(*) stat_count
FROM files WHERE direction='out' 
AND start_time > {{start_time}} 
GROUP BY DATE_FORMAT(start_time, {{resolution}}), status HAVING stat_count>100 ORDER BY start_time, stat_count DESC
```

I use `HAVING stat_count>100` to reduce column fields but when resolution changes, this number is useless and more fields are fed to bar chart.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by salsakran** [comment] 2017-09-06 22:38
not at this time, but that's a good idea.

**Comment by MarkRx** [comment] 2019-01-31 22:19
The problem is you would need semantic knowledge of what a number means. If a number represents some quantity then the value can be summed. If the number represents a percentage then how would you "sum" them? It can't be a sum nor can it be an average (that would be an average of averages which wouldn't be properly weighted).

Another option would be to just drop the data and only use the first 20 series: https://github.com/metabase/metabase/issues/3656#issuecomment-450679863

**Comment by flamber** [comment] 2021-11-09 22:28
Closing in favor of #11325

**Closed by flamber** 2021-11-09 22:28 UTC
Labels: Type:New Feature, Visualization/Charts
