### ISSUE TITLE
Hiding a table makes it impossible to edit existing questions that uses that table

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15947] opened 2021-05-06 12:57 UTC
**Describe the bug**
When questions have been built on tables, which are hidden later, then it's either impossible to edit the question or the question will drop all references to the hidden table.

Possible workaround: Change the table name in Admin > Data Model by prepending `~DEPRECATED` or similar, so the table is added to the end of tables.

**To Reproduce**
1. Custom question > Sample Dataset > create a question like this and save as "Q1":
![image](https://user-images.githubusercontent.com/1447303/117299096-6cd2e080-ae78-11eb-99ee-02d9310d6b8b.png)
2. Admin > Data Model > Sample Dataset > hide Orders table - refresh browser and view "Q1"
It's now not possible to edit the question at all - almost looks like a user without data access
![image](https://user-images.githubusercontent.com/1447303/117299379-c63b0f80-ae78-11eb-9eb5-deacb746287a.png)
3. Admin > Data Model > Sample Dataset > show Orders, but hide Products table - refresh browser and view "Q1"
It's possible to edit the question, but making any changes will drop all references to Products table
![image](https://user-images.githubusercontent.com/1447303/117299740-2b8f0080-ae79-11eb-915b-bcfa470dd38c.png)

**Expected behavior**
This issue might not be straight forward, since it should probably allow existing questions to keep working, but should not include all hidden tables in the API response by default, since that could introduce a performance issue on instances, where perhaps 1k tables have been hidden for technical reasons, because it's not possible to limit via the db privileges.
A possible solution would be to introduce a "Deprecated" along with "Technical" and "Cruft", which would then include those tables in the API.

**Information about your Metabase Installation:**
Tested 0.37.8 thru 0.39.1

Related to #6445 and #6298

**Comment by likeshumidity** [comment] 2023-08-25 21:11
Should Metabase show a warning or prevent marking a table hidden if it is used in a question?

**Comment by krschacht** [comment] 2023-09-29 13:22
Another possibility would be: once a table is hidden still let the query be shown even if you don't allow editing of it. Or, even more minor, at least let the user know *why* they can't edit the query. I lost a bunch of cycles on this issue so 👍 to getting it fixed.

**Comment by nemanjaglumac** [comment] 2023-09-29 18:16
@krschacht upvote the original issue. We look at the number of those upvotes.
Upvote in a comment will get lost.

**Comment by krschacht** [comment] 2023-09-29 18:26
@nemanjaglumac I don't see an option to upvote anywhere on this issues page. Maybe that's only for people who are part of the Metabase organization?

**Comment by nemanjaglumac** [comment] 2023-09-29 18:27
@krschacht the left bottom of the first post
![image](https://github.com/metabase/metabase/assets/31325167/a4e30d74-8a5f-43d4-bb2d-f8a5f9de4683)

**Comment by nemanjaglumac** [comment] 2023-11-08 09:39
Still able to reproduce this on latest master at d35c779976ae6bd79369e9cc6bec8540908f37d2
The existing E2E reproductions seems to be valid.

Please note that converting a question into a model shows "Filter" and "Summarize", and converting it back to the saved question again removes them.

**Comment by bshepherdson** [comment] 2024-02-15 21:19
I think this should remain with the QC team and be triaged by them. There's only a couple of basic conversions of the `visibility_state` fields on tables or fields in MLv2; I think the logic for eg. not allowing editing of a question based on a hidden table belongs to the FE components.

**Comment by kamilmielnik** [comment] 2024-03-07 11:00
Reproducible in `master` at 78cb28816a.

If the fix is to disallow editing queries referencing hidden tables, then it's QC area. I'll change label from BE to FE.

**Comment by ranquild** [comment] 2024-06-28 20:08
The issue with hidden joined tables is the same as https://github.com/metabase/metabase/issues/37753 and https://github.com/metabase/metabase/issues/37751 and will be fixed by making the query readonly in such cases.

As for the main issue here, if you hide your source table, you won’t be able to edit the query in the query builder. Is it even a bug? Currently hiding a table makes it invisible in the entire app everywhere except Admin.

**Closed** 2024-10-22 15:47 UTC
Labels: Type:Bug, Priority:P2, Organization/Saved Questions, Administration/Table Metadata, .Frontend, Querying/GUI, .Reproduced, .Wanted: MLv2, .Team/Querying, Frequency:Often
