### ISSUE TITLE
Pie Chart Texts Cut Off

### ISSUE THREAD

**Issue by noa-dav** [metabase/metabase#32689] opened 2023-07-27 08:29 UTC
### Describe the bug

Long text is overlapping the pie chart.
For instance:
![image](https://github.com/metabase/metabase/assets/110764216/541ec781-3dad-4b35-be42-43346af10603)

### Expected behavior

Truncate string with ellipsis.

### Information about your Metabase installation
Metabase version 1.46.6.1

### Severity

minor

**Comment by adam-james-v** [comment] 2024-05-17 20:50
I think this is a duplicate of: https://github.com/metabase/metabase/issues/30996
Or, it might at least be solvable together.

**Comment by adam-james-v** [comment] 2024-05-17 21:14
I can repro this. The text renders above non-highlighted slices, but below the slice that is being hovered over.

**Comment by EmmadUsmani** [comment] 2024-07-08 18:22
I'm going to close this as a duplicate of https://github.com/metabase/metabase/issues/30996 since it's the same issue

**Closed by EmmadUsmani** 2024-07-08 18:22 UTC
Labels: Type:Bug, Priority:P3, Visualization/Charts/Pie, .echarts-scope, .Team/DashViz
