### ISSUE TITLE
JS errors when adding a filter

### ISSUE THREAD

**Issue by jstenquist** [metabase/metabase#2709] opened 2016-06-07 20:23 UTC
Ever since upgrading to 0.17.1, trying to add filters in a new or existing question causes JS errors as shown in the attachment. I have hard refreshed, rebuilt the installation with the latest .zip for ELB. No luck.

*  I am using the Chrome, Firefox and Safari browser.
*  My computer's OS is OSX 10.11.5.
*  I'm running Metabase AWS via ELB.
*  My database is MySQL.
*  My Metabase version is 0.17.1.

![metabase_bug](https://cloud.githubusercontent.com/assets/1971648/15873254/c87690a0-2ccb-11e6-9697-0a217e121bd3.png)

**Comment by tlrobinson** [comment] 2016-06-07 20:24
Duplicate of #2617, fixed in master, will be fixed in v0.18

**Closed by tlrobinson** 2016-06-07 20:24 UTC
