### ISSUE TITLE
Cannot save questions without results

### ISSUE THREAD

**Issue by nautilus28** [metabase/metabase#12402] opened 2020-04-27 15:54 UTC
**Describe the bug**
An error occurred when I tried to save a questions with no results

For example:

[select * from reviews limit 0;](url) from Sample Dataset

**Screenshots**
<img width="1040" alt="Screenshot 2020-04-27 at 16 48 34" src="https://user-images.githubusercontent.com/4472857/80392559-3f3b7a80-88a7-11ea-8fab-5372c1800bab.png">

<img width="613" alt="Screenshot 2020-04-27 at 16 46 55" src="https://user-images.githubusercontent.com/4472857/80392174-b7557080-88a6-11ea-9807-05914ad2e331.png">

**Information about your Metabase Installation:**

Metabase version 0.35.3

**Comment by flamber** [comment] 2020-04-27 16:13
Duplicate of #11256

**Closed by flamber** 2020-04-27 16:13 UTC
Labels: .Needs Triage, Type:Bug
