### ISSUE TITLE
Quick Action button to restore archived items when we open their pages via URL

### ISSUE THREAD

**Issue by mhd-adam** [metabase/metabase#14503] opened 2021-01-23 12:08 UTC
**Is your feature request related to a problem? Please describe.**
It is hard to know the name of an **archived** question or a dashboard when it is open via a URL

**Describe the solution you'd like**
A placeholder page where it says your dashboard is archived (same page that currently appears for an archived question), with a quick action button to restore it or just show the name of it so that we can go to the archived items and look for it.

**How important is this feature to you?**
One time a client complained about a lost dashboard without knowing what its name was. We had to go to the archived items and restore almost all of them to know exactly the dashboard he wanted.

**Additional context**
The following image of the page placeholder for an archived question is very nice, it only needs a quick action button to restore the item, or to go to the archive page where the archived item is highlighted.
![image](https://user-images.githubusercontent.com/65082505/105577767-3b7c4c00-5d84-11eb-812f-e20c0ecc12d6.png)

**Comment by flamber** [comment] 2021-01-23 12:39
Duplicate of #10987

**Closed by flamber** 2021-01-23 12:39 UTC
Labels: .Needs Triage, Type:New Feature
