### ISSUE TITLE
Handle illogical (reverse) manual input in the Between Filter

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#25187] opened 2022-09-01 17:53 UTC
**Describe the bug**
It is possible to enter the later date as the starting date in the Between filter manually and there doesn't seem to be any validation for it.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Open orders table
2. Click on Filter
3. Choose Created At > ... > Specific dates
4. Enter some date in the future for the **starting date**
5. Notice that "Add filter" button is still enabled > click it
6. The UI seems to comply with the illogical request and shows "Created at is between FUTURE PAST"
<img width="647" alt="image" src="https://user-images.githubusercontent.com/31325167/187979869-9016223c-5661-4c15-9235-a04c2a8dc7af.png">
7. Click "Apply Filters" button
8. The final filter actually gets implemented correctly
<img width="1719" alt="image" src="https://user-images.githubusercontent.com/31325167/187980047-f3d1f5bb-a1aa-4bd4-819a-48afee095d75.png">

**Expected behavior**
Adjust UI to in the mid-step (step 6) either by disabling the "Add filter" button or by switching the order of date fields

**Information about your Metabase Installation:**
local dev, `master`, fb35f2b54ad4e39c450a8dc5d67f419a1bbd8e83, H2, Sample Database

**Severity**
P3 since the final filter is actually corect

**Additional context**
BugBashed

**Comment by camsaul** [comment] 2023-03-31 18:31
Duplicate of #16745

**Closed by camsaul** 2023-03-31 18:31 UTC
Labels: Type:Bug, Priority:P3, Querying/Parameters & Variables, .Frontend, Querying/GUI, .bugbash
