### ISSUE TITLE
Question gives different results when placed on a dashboard

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#48298] opened 2024-10-03 12:59 UTC
### Describe the bug

Dashboard, 1077 rows: [image](https://github.com/user-attachments/assets/19bd689f-19dc-46bb-995a-289218310cef)
Query builder, 4308 rows: [image](https://github.com/user-attachments/assets/26d6639a-73eb-4b40-93aa-5ca75224af39)

https://github.com/user-attachments/assets/fd7e363a-d2f0-4813-a4b6-641d7e6efab8

### To Reproduce

(this surely isn't the minimal example, apologies for this huge query)

1. Create a question Q1 based on Orders table
2. Create a question Q2 based on Q1
3. Create a question Q3 based on Q2 ([image](https://github.com/user-attachments/assets/b19f2b18-1f9e-43fc-9ee9-13ab9727a5e5))
    - join Reviews on Product ID = Product ID
    - add custom column `Net` with this expression: `[Total] - [Tax]`
    - add aggregations: Count and Sum of Total
    - add breakouts: Created At: Month, Product -> Category, User -> Created At: Year
    - join Reviews on Created At: Month = Created At: Month
    - add custom column `5 * Count` with this expression: `5 * [Count]`
    - add Count aggregation
    - add breakouts: Reviews -> Created At: Month -> Reviewer and Product -> Category
4. Visualize, notice rows count is 4308 (⚠ **shouldn't it be limited to 2000?**, see https://github.com/metabase/metabase/issues/48439#issuecomment-2399416349) 
5. Add this question to a dashboard and save it
6. Notice rows count for the question is 1077

### Expected behavior

Rows count is the same in dashboard and in query builder

### Information about your Metabase installation

master, 3a3785d

### Severity

P1/P2

### Additional info

- https://metaboat.slack.com/archives/C07BWMG9C8M/p1727960401955539
- https://metaboat.slack.com/archives/C07A3CC0WUX/p1727959355063309

**Comment by appleby** [comment] 2024-10-16 00:15
A simplified version of the above query that returns the same results is the following ![Image](https://github.com/user-attachments/assets/618daff5-0167-4f39-a53f-f8dce62c8238)

* Create a question Q0 based on the Orders table
* add aggregations: Count
* add breakouts: Created At: Month, Product -> Category
* join Reviews on Created At: Month = Created At: Month
* add Count aggregation
* add breakouts: Reviews -> Created At: Month -> Reviewer and Product -> Category

But I think this is a duplicate of #12522 and any pivot table will do (see the simpler query in that issue, e.g.).

Note that 1,077 = 4,308 / 4, i.e. the number of rows reported in the dashcard (1,077) is equal to the number of rows reported in the query builder (4,308) divided by the number of product categories that we pivot on (4).

Interestingly, if I convert the question to SQL, the 2,000 row limit is respected in the query builder view, and then the number of rows reported in the dashcard is instead 500 = 2,000 / 4.

**Comment by appleby** [comment] 2024-10-16 19:04
Close as dup per slack discussion here

https://metaboat.slack.com/archives/C0645JP1W81/p1729095615943569

**Comment by mngr** [comment] 2024-10-16 19:12
Duplicate of https://github.com/metabase/metabase/issues/12522

**Closed by mngr** 2024-10-16 19:12 UTC
Labels: Type:Bug, Priority:P1, Reporting/Dashboards, Querying/Processor, .Backend, .Team/Querying

**Comment by appleby** [comment] 2024-10-16 19:26
As for the row count exceeding the default limit of 2,000 for UI queries, this also appears to be working as designed. Apparently the 2,000 limit is passed as `:max-results-bare-rows` (`HARD_ROW_LIMIT` on the FE) which is only used for queries *without* aggregations.

Queries *with* aggregations instead use `:max-results`, which for this query is 10,000

```json
"constraints": {
    "max-results": 10000,
    "max-results-bare-rows": 2000
},
```

See

https://github.com/metabase/metabase/blob/94496eb579f860385e38847cfc6d169a4525c008/src/metabase/legacy_mbql/util.cljc#L735

https://github.com/metabase/metabase/blob/94496eb579f860385e38847cfc6d169a4525c008/test/metabase/legacy_mbql/util_test.cljc#L804

https://github.com/metabase/metabase/blob/94496eb579f860385e38847cfc6d169a4525c008/src/metabase/cmd/env_var_dox.clj#L52
