### ISSUE TITLE
Hourly Date Filter Issue for Native Questions

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#18362] opened 2021-10-08 19:13 UTC
If the date range chosen is later than start of current day, it doesn't show any data.

DB:
```sql
select cast('2021-10-08 11:00:00' as datetime) the_date
into test
```
Metabase Native Question:
```
select *
from test
where 1 = 1 
[[ and {{d}} ]]  -- Date Filter for the column 'the_date' of the 'test' table above
```
Now if I select the past 5 hours in the date filter it returns no record, but selecting the past 20 hours (or any amount of time that falls before the start of current day) it shows the data.

Tested on Postgres and SQL Server.

v .40.4

**Comment by flamber** [comment] 2021-10-08 19:18
Hi @vvaezian 
Sounds like a duplicate of #18315. If not, then you need to include "Diagnostic Info" from Admin > Troubleshooting. Timezone issues are hard, and less information makes them even harder.

**Comment by vvaezian** [comment] 2021-10-08 19:48
This seems to be a duplicate of that ticket.

Note that this is not a timezone issue.
AFAIK previously filtering by hour was not available in the date filters of native questions. Now that it is available, it doesn't work if the chosen `past n hours` doesn't fall before the start of current day.
Also this seems to be not related to a certain DB Server. I tested with SQL Server and Postgres, and the ticket you mentioned is for MySQL.

**Comment by flamber** [comment] 2021-10-09 10:43
@vvaezian Please upgrade to 1.40.5. There's so much timezone handling in that part of the code, so it gets difficult to tell it all apart. I know we're focusing on timezone and filter in v42, so hopefully that will help prioritizing 18315. Closing in favor of that issue.

**Closed by flamber** 2021-10-09 10:43 UTC
Labels: Type:Bug, .Needs Triage
