### ISSUE TITLE
Impossible to change the column order from a dashboard

### ISSUE THREAD

**Issue by ZohaSpark** [metabase/metabase#17062] opened 2021-07-15 09:33 UTC
**Describe the bug**
When trying to drag and drop a column, the drag does not happen at all. The selected column name kind of floats, following your scrolling even if you are not clicking anymore and the window does not respond at all. In the end, the only solution is to cancel. We also experience some issues at the editor level for the order of columns sometimes (cannot drag it at once as the first column, need to put it in the middle and then gradually put it on top, but this one we can work with a little).

**To Reproduce**
1. Go to any dashboard with a table.
2. Click on Visualization options.
3. Scroll down to any given column and try to change the order of the columns.

**Expected behavior**
A neat drag and drop of the selected column.

**Screenshots**

**Before:**
![image](https://user-images.githubusercontent.com/87467508/125765288-5aef5ba7-8927-422a-8603-532bcb679238.png)

**After clicking and trying to drag it:**
![image](https://user-images.githubusercontent.com/87467508/125765430-a2ecb09a-f756-42ae-a5bd-beca3af2bdcf.png)

**Information about your Metabase Installation:**

> {
  "browser-info": {
    "language": "fr-FR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.14.232-177.418.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.9"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-07-08",
      "tag": "v0.40.0",
      "branch": "master",
      "hash": "961caed"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}

**Severity**
It is very annoying and prevents from visualizing tables as we would want to.

**Comment by flamber** [comment] 2021-07-15 09:50
Duplicate of #16229

**Closed by flamber** 2021-07-15 09:50 UTC
Labels: .Needs Triage, Type:Bug
