### ISSUE TITLE
All columns doesn't show up in pivot tables

### ISSUE THREAD

**Issue by upasana-mittal** [metabase/metabase#11673] opened 2020-01-10 06:58 UTC
**Bug Description**
Table was pivot upon a column which have 8 distinct categories. After pivot, it only shows 6 columns whereas it should be showing 8 columns

**Expected behavior**
It should have shown all defined categories as columns

**Information about Metabase Installation:**
- Your browser and the version: all browsers
- Your operating system: hosted
- Your databases: MySQL
- Metabase version: latest
- Metabase hosting environment: Docker

**Severity**
This has become a problem to us because we had to create another chart to show the left categories

**Comment by mazameli** [comment] 2020-01-16 01:19
Wasn't able to reproduce this in version 0.34.1 with a MySQL database. Can you please provide some additional details:

- If you can provide screenshots, that would be super helpful
- Specific MB version (I see you wrote "latest" but I just want to verify which exactly you're running)
- Is this with native/SQL queries, GUI queries, or both?
- Does this happen when pivoting by any categorical column, or only that specific one? If the latter what data type is that column, and what metadata type is it set to in the Data Model within Metabase?

**Comment by upasana-mittal** [comment] 2020-01-19 06:22
> Wasn't able to reproduce this in version 0.34.1 with a MySQL database. Can you please provide some additional details:
> 
> * If you can provide screenshots, that would be super helpful
> * Specific MB version (I see you wrote "latest" but I just want to verify which exactly you're running)
> * Is this with native/SQL queries, GUI queries, or both?
> * Does this happen when pivoting by any categorical column, or only that specific one? If the latter what data type is that column, and what metadata type is it set to in the Data Model within Metabase?

1. Metabase version is 0.33.6
2. It is with SQl Queries
3. This happens when we are pivoting by any categorical column

I wont be able to provide screenshots as this is includes company's confidential data

I will try to explain more.

The column by which we are pivoting holds 8 different categories so that means when we pivot by that column, it show produce and show 8 different columns but that doesn't happen. we see only 6 of them.

**Comment by mazameli** [comment] 2020-01-20 23:00
Hmm, here is an example sql query on a mysql table in version 0.34.1 visualized as a pivot table:

![image](https://user-images.githubusercontent.com/2223916/72762703-74904800-3b95-11ea-90d2-2b184df70846.png)

Just to verify, if you _don't_ pivot, are you seeing all 8 distinct values in the column?

**Comment by upasana-mittal** [comment] 2020-02-03 04:02
> Hmm, here is an example sql query on a mysql table in version 0.34.1 visualized as a pivot table:
> 
> ![image](https://user-images.githubusercontent.com/2223916/72762703-74904800-3b95-11ea-90d2-2b184df70846.png)
> 
> Just to verify, if you _don't_ pivot, are you seeing all 8 distinct values in the column?

yes. If i am not pivoting then i can see all distinct columns. 

I have updated metabase but issue is still there

**Comment by mazameli** [comment] 2020-02-11 18:52
@flamber, I'm curious to see if you have better luck than I did in trying to reproduce this.

**Comment by flamber** [comment] 2020-02-11 20:55
@mazameli I've tried multiple ways, but cannot reproduce - multiple datasets and databases.
I'm getting 8 columns all the time, so unless we can see a screenshot (with obsured sensitive data) or a way to reproduce with Sample Dataset, then it's going to be really difficult to figure out what's going on.
![image](https://user-images.githubusercontent.com/1447303/74278098-f13bbf80-4d18-11ea-9f81-621c692f7732.png)

**Comment by upasana-mittal** [comment] 2020-02-12 07:02
Here are the screenshots:
<img width="1167" alt="sc1" src="https://user-images.githubusercontent.com/29627522/74310591-84194000-4d93-11ea-85db-d7c7c4b0fd95.png">
<img width="535" alt="sc2" src="https://user-images.githubusercontent.com/29627522/74310594-85e30380-4d93-11ea-8930-d20befd7d71a.png">

We have used MySQL Views to build the tables. Here you can see, that data has been divided into two because as in first screenshot, we were not able to see data for **sound therapies** and **yoga**.
That's why we had to add a seperate table.

@flamber @mazameli

**Comment by flamber** [comment] 2020-02-12 08:24
@upasana-mittal 
But the first screenshot looks to be from a question, while the second screenshot is from a dashboard.
Is this a problem everywhere? Or only specific places - like dashboards?

Showing how it currently looks, when you're using a `View` doesn't help, since the result is split already and will never return the 8 columns.

If you can reproduce the problem with non-sensitive data, then that would be great. I still cannot reproduce this issue.
![image](https://user-images.githubusercontent.com/1447303/74316196-558e6b80-4d79-11ea-9663-d0f7d9fb5e55.png)
```
SELECT 'Assestments/care plan' AS Treatment, 'no@no.tld (Employee)' AS Email, 24 AS Value UNION ALL
SELECT 'Body and Beauty Treatments' AS Treatment, 'no@no.tld (Employee)' AS Email, 25 AS Value UNION ALL
SELECT 'Fitness' AS Treatment, 'no@no.tld (Employee)' AS Email, 26 AS Value UNION ALL
SELECT 'Mindfulness' AS Treatment, 'no@no.tld (Employee)' AS Email, 27 AS Value UNION ALL
SELECT 'Nutrition' AS Treatment, 'no@no.tld (Employee)' AS Email, 28 AS Value UNION ALL
SELECT 'Short Treatments' AS Treatment, 'no@no.tld (Employee)' AS Email, 29 AS Value UNION ALL
SELECT 'Sound Therapies' AS Treatment, 'no@no.tld (Employee)' AS Email, 30 AS Value UNION ALL
SELECT 'Yoga' AS Treatment, 'no@no.tld (Employee)' AS Email, 31 AS Value UNION ALL
SELECT 'Assestments/care plan' AS Treatment, 'no2@no.tld (Non-Employee)' AS Email, 55 AS Value UNION ALL
SELECT 'Body and Beauty Treatments' AS Treatment, 'no2@no.tld (Non-Employee)' AS Email, 56 AS Value UNION ALL
SELECT 'Fitness' AS Treatment, 'no2@no.tld (Non-Employee)' AS Email, 57 AS Value UNION ALL
SELECT 'Mindfulness' AS Treatment, 'no2@no.tld (Non-Employee)' AS Email, 58 AS Value UNION ALL
SELECT 'Nutrition' AS Treatment, 'no2@no.tld (Non-Employee)' AS Email, 12 AS Value UNION ALL
SELECT 'Short Treatments' AS Treatment, 'no2@no.tld (Non-Employee)' AS Email, 13 AS Value UNION ALL
SELECT 'Sound Therapies' AS Treatment, 'no2@no.tld (Non-Employee)' AS Email, 14 AS Value UNION ALL
SELECT 'Yoga' AS Treatment, 'no2@no.tld (Non-Employee)' AS Email, 15 AS Value
```

**Comment by upasana-mittal** [comment] 2020-02-12 08:42
@flamber problem is everywhere. I just took screenshots from different places. We had to add two charts on dashboard because two categories were not showing up in both places.

<img width="1617" alt="sc3" src="https://user-images.githubusercontent.com/29627522/74317420-6521aa80-4da1-11ea-9dd1-8cad0e77e529.png">

Here is the query and settings section: 

`SELECT 
       CONCAT(customer_email,' (', user_classification,')') as 'email (usertype)',
       main_service AS main_service,
       COUNT(service_title) AS Counts
FROM vw_wbc_emp_mertics_v1
WHERE  {{staff_location}} AND {{email}} AND {{weekstartend}} AND {{formated_date_m}} 
AND {{formated_date_y}} AND {{main_service}} AND {{service_title}} AND {{status}} AND {{user_classification}}
CONCAT('%','round.glass','%'))
AND (service_title != '' AND service_title IS NOT NULL)
GROUP BY CONCAT(customer_email,' (', user_classification,')'),main_service
ORDER BY main_service ASC, COUNT(service_title)  DESC
`

![image](https://user-images.githubusercontent.com/29627522/74317521-9601df80-4da1-11ea-81f7-e42d30d6ef04.png)

**Comment by flamber** [comment] 2020-02-12 09:02
@upasana-mittal 
I don't have access to your data, so the query doesn't help a lot with this issue. If you can, please reproduce it with Sample Dataset or static SQL.
Interesting that you're getting 991 rows in the question with 6 columns, but only 667 rows in the one with 2 columns. Are you sure the questions are based on the same query and using the same filters?

**Comment by upasana-mittal** [comment] 2020-02-12 09:09
> @upasana-mittal
> I don't have access to your data, so the query doesn't help a lot with this issue. If you can, please reproduce it with Sample Dataset or static SQL.
> Interesting that you're getting 991 rows in the question with 6 columns, but only 667 rows in the one with 2 columns. Are you sure the questions are based on the same query and using the same filters?

That could be because to build 2nd chart, **i have filtered data for sound therapy and yoga** only

**Comment by flamber** [comment] 2020-04-28 16:09
Closing this, since we haven't been able to reproduce the issue. If you can provide steps-to-reproduce, then please comment and the issue be reopened.

**Closed by flamber** 2020-04-28 16:09 UTC
Labels: .Unable to Reproduce, Type:Bug, Visualization/Tables

**Comment by macductan** [comment] 2023-10-09 06:52
Hi @upasana-mittal, has you resolved this problem?
