### ISSUE TITLE
User with Limited Permissions (Collection Only) Receives "You don't have permissions to do that." Message When Filtering Question

### ISSUE THREAD

**Issue by orware** [metabase/metabase#14711] opened 2021-02-08 22:39 UTC
**Describe the bug**
My colleague is attempting to move forward with an experiment we started last year and the user trying out the functionality appears to be running into this "You don't have permissions to do that." message when attempting to filter data within a question they have access to within a Collection.

In the Chrome Devtools, it shows a few API Access Errors and then there's the additional Log info down below:

```
/api/table/[TABLE_ID]/query_metadata (fetchMetadata) Fails with 403
```

**Logs**

```
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:13:28-08:00 DEBUG metabase.middleware.log GET /api/alert/question/292 200 1.3 ms (1 DB calls) App DB connections: 1/15 Jetty threads: 8/50 (13 idle, 0 queued) (131 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:13:28-08:00 DEBUG metabase.middleware.log GET /api/table/26341/query_metadata 200 19.1 ms (8 DB calls) App DB connections: 1/15 Jetty threads: 8/50 (13 idle, 0 queued) (131 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:13:28-08:00 INFO metabase.api.card Question's average execution duration is 527.0 ms; using 'magic' TTL of 5.0 s 
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:13:29-08:00 INFO metabase.query-processor.middleware.cache Query took 339.0 ms to run; minimum for cache eligibility is 15.0 s
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:13:29-08:00 DEBUG metabase.middleware.log POST /api/card/292/query 202 [ASYNC: completed] 402.2 ms (26 DB calls) App DB connections: 2/15 Jetty threads: 7/50 (13 idle, 0 queued) (133 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:13:31-08:00 DEBUG metabase.middleware.log GET /api/database 200 2.6 s (4 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (13 idle, 0 queued) (133 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:14:27-08:00 DEBUG metabase.middleware.log GET /api/setting 200 1.5 ms (0 DB calls) App DB connections: 1/15 Jetty threads: 9/50 (13 idle, 0 queued) (132 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:14:27-08:00 DEBUG metabase.middleware.log GET /api/session/properties 200 3.2 ms (2 DB calls) App DB connections: 0/15 Jetty threads: 9/50 (13 idle, 0 queued) (132 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:14:28-08:00 DEBUG metabase.middleware.log GET /api/setup/admin_checklist 200 9.2 ms (11 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (13 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:14:30-08:00 DEBUG metabase.middleware.log GET /api/permissions/graph 200 51.1 ms (3 DB calls) App DB connections: 2/15 Jetty threads: 9/50 (13 idle, 0 queued) (132 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:14:33-08:00 DEBUG metabase.middleware.log GET /api/database 200 2.9 s (4 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (13 idle, 0 queued) (132 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:14:38-08:00 DEBUG metabase.middleware.log GET /api/collection/graph 200 14.6 ms (5 DB calls) App DB connections: 0/15 Jetty threads: 8/50 (13 idle, 0 queued) (132 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:15:24-08:00 DEBUG metabase.middleware.log GET /api/util/bug_report_details 200 10.8 ms (1 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (13 idle, 0 queued) (132 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:16:23-08:00 WARN metabase.driver.sql-jdbc.sync.describe-table Don't know how to map column type 'WB_RT_SERVICE_REQUEST_T' to a Field base_type, falling back to :type/*.
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:17:44-08:00 WARN metabase.driver.sql-jdbc.sync.describe-table Don't know how to map column type 'WB_RT_ACKNOWLEDGE_T' to a Field base_type, falling back to :type/*.
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:18:18-08:00 WARN metabase.driver.sql-jdbc.sync.describe-table Don't know how to map column type 'WB_RT_NOTIFY_T' to a Field base_type, falling back to :type/*.
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:18:58-08:00 DEBUG metabase.middleware.log GET /api/card/473 200 6.2 ms (6 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (11 idle, 0 queued) (126 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:18:58-08:00 DEBUG metabase.middleware.log GET /api/alert/question/473 200 1.1 ms (1 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (11 idle, 0 queued) (126 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:18:58-08:00 INFO metabase.api.card Question's average execution duration is 119.0 ms; using 'magic' TTL of 1000.0 ms 
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:18:58-08:00 INFO metabase.query-processor.middleware.fetch-source-query Fetched source query from Card 292: 
 {:source-table 26341,
 :fields
 [[:field-id 514708]
  [:field-id 514731]
  [:field-id 514724]
  [:field-id 514703]
  [:field-id 514695]
  [:field-id 514726]
  [:field-id 514700]
  [:field-id 514733]
  [:field-id 514728]
  [:field-id 514719]
  [:field-id 514715]
  [:field-id 514725]
  [:field-id 514694]
  [:field-id 514696]]}

[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:18:58-08:00 INFO metabase.query-processor.middleware.fetch-source-query Fetched source query from Card 292: 
 {:source-table 26341,
 :fields
 [[:field-id 514708]
  [:field-id 514731]
  [:field-id 514724]
  [:field-id 514703]
  [:field-id 514695]
  [:field-id 514726]
  [:field-id 514700]
  [:field-id 514733]
  [:field-id 514728]
  [:field-id 514719]
  [:field-id 514715]
  [:field-id 514725]
  [:field-id 514694]
  [:field-id 514696]]}

[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:18:58-08:00 INFO metabase.query-processor.middleware.cache Query took 25.0 ms to run; minimum for cache eligibility is 15.0 s
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:18:58-08:00 DEBUG metabase.middleware.log POST /api/card/473/query 202 [ASYNC: completed] 99.5 ms (14 DB calls) App DB connections: 1/15 Jetty threads: 6/50 (11 idle, 0 queued) (127 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:18:59-08:00 DEBUG metabase.middleware.log GET /api/collection/39 200 3.4 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 8/50 (10 idle, 0 queued) (127 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:19:00-08:00 DEBUG metabase.middleware.log GET /api/card/292 200 5.9 ms (6 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (10 idle, 0 queued) (129 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:19:01-08:00 DEBUG metabase.middleware.log GET /api/alert/question/292 200 1.6 ms (1 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (10 idle, 0 queued) (129 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:19:01-08:00 WARN metabase.middleware.log GET /api/table/26341/query_metadata 403 2.9 ms (3 DB calls) 
"You don't have permissions to do that."

[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:19:01-08:00 INFO metabase.api.card Question's average execution duration is 514.0 ms; using 'magic' TTL of 5.0 s 
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:19:01-08:00 INFO metabase.query-processor.middleware.cache Query took 386.0 ms to run; minimum for cache eligibility is 15.0 s
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:19:01-08:00 DEBUG metabase.middleware.log POST /api/card/292/query 202 [ASYNC: completed] 444.7 ms (26 DB calls) App DB connections: 1/15 Jetty threads: 7/50 (10 idle, 0 queued) (129 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:19:04-08:00 DEBUG metabase.middleware.log GET /api/card/292 200 7.0 ms (6 DB calls) App DB connections: 1/15 Jetty threads: 7/50 (10 idle, 0 queued) (129 total active threads) Queries in flight: 0 (0 queued)
[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:19:04-08:00 WARN metabase.middleware.log POST /api/dataset 403 3.2 ms (3 DB calls) 
"You don't have permissions to do that."

[3e7436b5-f94a-4897-9649-d19f3af070a5] 2021-02-08T14:19:04-08:00 WARN metabase.middleware.log GET /api/table/26341/query_metadata 403 6.1 ms (3 DB calls) 
"You don't have permissions to do that."
```

**To Reproduce**
1. We have created a group (e.g. "Human Resources")
2. A user has been assigned to this group
3. The group does not have any access to any of the Databases by default (everything under the "Permissions" area for "Data permissions" is set to "No Access" for this group.
4. The only permissions assigned to the group are to a Collection containing a few Questions/Charts (e.g. "Human Resources Collection". The Collection permissions are to "Can view items in this Collection" only.
5. The question being tested is not complex one. Normally we have to write complicated queries across multiple tables for our database, which means using Custom SQL all the time within Metabase, but in order to take advantage of the Question interface/functionality provided by Metabase for use by one of our other departments my colleague has put together a view beforehand in the database, to allow for things to be queried more easily using the Question interface.
6. My colleague created his question, and has placed it within the "Human Resources Collection" where the "Human Resources" group has access, and the test user is assigned to this group.
7. Testing with the test user, we are able to see the Collection, and we are able to see the Question listed, and we can click on the Question and see the data it contains, but if the test user attempts to filter on a column, they receive the "You don't have permissions to do that." error message.

We already tested out a few things on our end to see if they might help:

* We were on 0.37.3 so I updated to the current version to see if that might help. Did not seem to change the result.
* We tested adding the group to have access to the database view my colleague created within the Permissions / Data Permissions / [Schema] / [Table] area. Did not seem to change the result.
* We tested switching the group to "Curate" permissions on the Collection to see if that would help (rather than the view only permissions the group had). Did not seem to change the result.

**Expected behavior**
We feel that the user should have the ability to filter the data within the question based on the permissions they are assigned at the Collection level (the second test we attempted above seemed like it would be an unnecessary step if it were to have worked...ideally, for limited permissions needs like this one, we would want to limit the permissions we assign to a group as much as possible, but for what they are assigned at the Collection level, they should be able to filter and perform any of those types of needed actions that one would expect them to want to use).

**Screenshots**
Not sure if I can easily share screenshots of this at the moment.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "13.0.2+8",
    "os.name": "Windows Server 2019",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "oracle",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.2.6-MariaDB"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-01-26",
      "tag": "v0.37.8",
      "branch": "release-x.37.x",
      "hash": "490cea7"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

**Severity**
I would rate this as somewhat severe (in terms of this being a blocker for rolling out more limited access views similar to the one we're trying to roll out here to a specific group in the organization).

**Comment by flamber** [comment] 2021-02-09 09:24
Hi @orware 
Sounds like it's a duplicate of #12720, but I'm unsure exactly what type of questions you're using in your steps-to-reproduce.

**Comment by orware** [comment] 2021-02-09 15:06
Good morning @flamber, it's possible it could be related to that other item, so could be a different manifestation of the same issue (the other issue is similar in that it seems to have a user with basically no permissions except the view-only permissions on a collection, but since it uses the Sample Dataset that might make it easier for the Development Team to reproduce, so hopefully if a solution were found for #12720 it would solve our issue as well).

This particular item is a bit of a blocker, since it throws off our expectations for the behavior of the application with the limited permissions we have set currently, and therefore would prevent proceeding with pushing metabase for the current use case (which actually was a good one for us...as mentioned above, we normally end up writing questions with native queries since our schema is complicated with hundreds of tables in our ERP, so my colleague created this view with just the data HR would need to access regularly so they could start creating some of their own ad-hoc questions more easily, however the permissions issue will prevent the HR users from using the question as we'd like them to be able to use it for the time being until a solution is found).

**Comment by flamber** [comment] 2021-02-09 15:23
@orware 
Would you be able to do a quick test using the Sample Dataset? Doesn't have to be on your production instance. And then provide me with steps to reproduce.

I'm 90% sure from your description that it's a duplicate. And while I can definitely see the problem for you, if this issue is a duplicate, then the problem has existed at least since 0.34.0 (I didn't test earlier versions), so I don't think it's a regression, but a very annoying permission issue that has been there for a very long time.

Having issues that we cannot reproduce makes it close to impossible to know how to fix them or if they're fixed - and we cannot add tests to ensure it doesn't become a regression.
I'm trying to make sure that every issue can be reproduce and tested, since it makes it much easier for the developers - and I close every other issue, since it's difficult enough for me to try to keep track of 2000 issues already.

**Comment by orware** [comment] 2021-02-09 15:54
@flamber,

I just ran a quick test on my end and was able to reproduce our issue detailed above with the Sample Dataset as well.

The steps to reproduce are basically the same as above:

1. Create a "Human Resources" group
2. Add a new test user and assign them to the group
3. Make sure the group doesn't have any permissions on the "Sample Dataset" directly,
4. Create a "Human Resources Collection".
5. Add the "Human Resources" group to the "Human Resources Collection" with view-only permissions.
6. As an Admin, create a new Question (I used the "Ask a Question | Simple Question" option, then selected the "Sample Dataset | Orders" table and didn't do anything else except save it to the "Human Resources Collection".
7. I then logged in as the test user and browsed to the Question that was just created and opened it and then tried a simple filtering action such as clicking on a cell value in the Quantity column and attempting to filter on one of those values).

Hopefully these extra details are helpful, and thank you for your replies :-)!

**Comment by flamber** [comment] 2021-02-09 16:04
@orware Excellent. Okay, then it's exactly the same as #12720 - going from dashboard with filters set, then applies the filters on the question, so that the same as you're seeing, while you're just setting the filter directly on the question instead.
Related to #11914 too.
Closing this then :+1:

**Closed by flamber** 2021-02-09 16:04 UTC
Labels: .Needs Triage, Type:Bug
