### ISSUE TITLE
Feature - Possibility to save and import sub queries

### ISSUE THREAD

**Issue by robertobitbond** [metabase/metabase#8082] opened 2018-07-17 09:00 UTC
Most of the time I copy and paste small sub-queries into bigger queries.
This provokes a lot of duplicated code difficult to maintain and to keep up to date.
It would be amazing to have a feature to import a sub query already saved somewhere else, for example.

__________________________________________________
WITH test_sub_query AS (
    SELECT *
    FROM **sub_query_saved_somewhere_else**
)
SELECT *
FROM test_sub_query
__________________________________________________

Thanks a lot.

**Comment by salsakran** [comment] 2018-07-17 19:51
dupe of #1825
still a great idea, though =)

**Closed by salsakran** 2018-07-17 19:51 UTC
