### ISSUE TITLE
React rendering fails 

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6592] opened 2017-12-19 02:17 UTC
This is a p1 since it's in the setup flow -

![screen shot 2017-12-18 at 6 16 09 pm](https://user-images.githubusercontent.com/107439/34137392-94c357fe-e41f-11e7-98c8-4a818b1c9919.png)

I'll be adding others that I see in this issue

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by attekei** [comment] 2018-01-17 17:23
I couldn't reproduce this anymore, I think this was fixed in https://github.com/metabase/metabase/pull/6635

**Closed by attekei** 2018-01-17 17:23 UTC
Labels: Bug, Priority/P1
