### ISSUE TITLE
Toolbar graphics glitch

### ISSUE THREAD

**Issue by kellyniel** [metabase/metabase#5151] opened 2017-05-19 23:22 UTC
- Chrome Version 58.0.3029.110 (zoom at 100%)
- MacOS Sierra 10.12.4  
- Your databases: MySQL
- Metabase version: 0.23.1
- Metabase hosting environment: Linux
- Metabase internal database: H2 (default)

The toolbar graphics seem to have some type of glitch. Every time I open a window the navigation looks like one of these:

<img width="1255" alt="screen shot 2017-05-19 at 1 22 44 pm" src="https://cloud.githubusercontent.com/assets/28815123/26266041/7611fe5c-3c98-11e7-9b2f-455655cce7b8.png">

<img width="1280" alt="screen shot 2017-05-19 at 1 33 55 pm" src="https://cloud.githubusercontent.com/assets/28815123/26266021/62206762-3c98-11e7-97e2-17451dcff916.png">
<img width="444" alt="screen shot 2017-05-01 at 4 07 09 pm" src="https://cloud.githubusercontent.com/assets/28815123/26266064/97652f2a-3c98-11e7-94cc-9add5431f266.png">
<img width="1278" alt="screen shot 2017-05-19 at 1 44 15 pm" src="https://cloud.githubusercontent.com/assets/28815123/26266209/4a156fcc-3c99-11e7-8e9e-48937ae7b556.png">
<img width="1280" alt="screen shot 2017-05-19 at 1 45 37 pm" src="https://cloud.githubusercontent.com/assets/28815123/26266253/79ec22ae-3c99-11e7-9e78-4f25e30837d8.png">

**Comment by mazameli** [comment] 2017-05-19 23:44
I think this was fixed in version 0.24 when we removed the diamond pattern in the top nav.

**Comment by mazameli** [comment] 2017-05-20 00:06
Yeah, dupe of https://github.com/metabase/metabase/issues/4823
Fixed in 0.24 by https://github.com/metabase/metabase/pull/4850

**Closed by mazameli** 2017-05-20 00:06 UTC
Labels: Bug, CSS, Duplicate, Priority/P2
