### ISSUE TITLE
Filter "A list of all values" on enumerated columns

### ISSUE THREAD

**Issue by Thomassso** [metabase/metabase#15541] opened 2021-04-09 09:49 UTC
**Describe the bug**
Our database model contains many foreign key columns (enumerated values for products, statuses, etc.). In Metabase we configured the Data Model:
- *Field Type* seeting of status_id column: ```Foreign Key > enum_table```
- *Display Values* setting: ```Use foreign key > title_column```
- *Filtering on this field* setting: ```A list of all values```.

Filter on the status_id column works not: it gives an empty report regardles of choosen values.

I found a workaround. I changed
- *Filtering on this field* setting: ```Search box```.

In this case the filter worked as expected.

**Logs**
N/A

**To Reproduce**
I tried to reproduce this behaviour on Sample Dataset. The Orders table has ```Product_ID``` column.
![ ](https://user-images.githubusercontent.com/27001370/114161869-cd7a0680-9928-11eb-8afa-e40f8ac3e66d.gif)

I configured to show Product Title instead of Product ID in the Orders table because this is what report consumers wish. Still the filtering is based on the ```Product_ID```. Strange...
![ ](https://user-images.githubusercontent.com/27001370/114161916-dc60b900-9928-11eb-9811-7d17fceff05f.gif)

I changed the Filter type to ```Search box```. Great! Everything worked as expected.
![ ](https://user-images.githubusercontent.com/27001370/114161939-e387c700-9928-11eb-83c6-c3501b4a99ef.gif)

Our users prefer to see the list of all values. I changed the Filter type again, I changed to: ```A list of all values```. I realized that there is too many products in Sample Dataset therefore I see no list. Even I'm not allowed to search products based on their title, I have to enter the the Product ID like in ```Plain input box```.
![ ](https://user-images.githubusercontent.com/27001370/114161956-e8e51180-9928-11eb-927a-248c9a33d78a.gif)

On the next screenshot I will show the behaviour of ```A list of all values``` filte type on our contracts table. It's *Policy Status* column has only few values, so I will be able to demonstrate the bug. First I properly configured the Data Model. Then I created a report with few columns (unfortunatelly Metabase doesn't allow to uncheck all columns at once - it is possible only on joined tables). Finally the list of all statuses showed up in the filter widget. I choosed the status I saw in the first rows (without filters).
You see the bug: no rows found.
![ ](https://user-images.githubusercontent.com/27001370/114161978-eedaf280-9928-11eb-939f-472dce9847c2.gif)

I got an idea based on previous experience. What if I try to enter the code of *Policy Status* and not it's Title? From this test case it is clear: this filter widget does not transalate the Titles into codes.
![ ](https://user-images.githubusercontent.com/27001370/114161997-f5696a00-9928-11eb-8a4e-fc32fde8a435.gif)

**Expected behavior**
Filter widget ```A list of all values``` should show the enumerated Titles and use ID's in the background (in DB query). For example ```Search box``` filter widget works as expected.

**Screenshots**
...

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_201-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_201",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.201-b09",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Europe/Prague"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "oracle",
      "postgres",
      "sqlserver",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.38.3",
      "date": "2021-04-01",
      "branch": "release-x.38.x",
      "hash": "8332830"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
High
Filters on enumerated columns are used the most in everyday reporting and the list of all values is extremely helpful (in case when there is no hundreds of values).

**Comment by flamber** [comment] 2021-04-09 10:58
Hi @Thomassso 
This is a duplicate of #13235. And have created an issue for a problem with cached values being shown #15542.

**Closed by flamber** 2021-04-09 10:58 UTC
Labels: .Needs Triage, Type:Bug
