### ISSUE TITLE
Drill-down doesn't apply filter from dashboard when filter is null

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#12817] opened 2020-06-30 17:00 UTC
**Describe the bug**
When I try to drill-down a single bar whose value is "(empty)" (the number of NULLs in the column), on a bar chart from a dashboard, no filter is applied and all bars' data are shown (as opposed to only with NULLs in the column concerned). When doing the same from the question itself (not from the dashboard), it does work correctly.

**Logs**
N/A

**To Reproduce**
1. Create a new bar chart with one bar showing the number of NULLs in the column.
2. Add it to a dashboard.
3. Go to the dashboard.
4. Drill-down the bar showing the NULL count on the card -> the question is opened.
5. Notice the question doesn't have the filter "<column> is empty" applied.

When doing the same without (2, 3), ie. directly from the question, it does work. The sample data unfortunately doesn't contain any NULLs, so I'm unable to demonstrate it there.

**Expected behavior**
A expect only the data from the selected bar to be shown, even if the column value is NULL.

**Screenshots**
N/A

**Information about your Metabase Installation:**
`{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1; Windows for Workgroups 3.11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "13.0.2",
    "java.vm.name": "Eclipse OpenJ9 VM",
    "java.vm.version": "openj9-0.18.0",
    "os.name": "Linux",
    "os.version": "4.15.0-66-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.29"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}`

**Severity**
We have to explain a workaround to the customer -> customer loses trust in us.

**Additional context**
I'm sure this has already been reported, but was unable to find the bug.

**Comment by flamber** [comment] 2020-06-30 17:08
Hi @andreychirikba 
I cannot reproduce your issue, but you haven't provided much details on how to reproduce. It would help if you provided an example with Sample Dataset.
Perhaps you're seeing #12496, but without more details I have no idea.

**Comment by andreychirikba** [comment] 2020-06-30 20:15
@flamber, I've updated the issue above. Summed up: only applies to the bar displaying the NULLs count (showing "(empty)").

**Comment by flamber** [comment] 2020-07-01 08:11
Duplicate of #11345

**Closed by flamber** 2020-07-01 08:11 UTC
Labels: .Unable to Reproduce, Type:Bug
