### ISSUE TITLE
Data filter and timestamp setting

### ISSUE THREAD

**Issue by tiagoferrucio** [metabase/metabase#13169] opened 2020-08-26 13:11 UTC
**Describe the bug**
I'm trying to do a filter in Metabase but the values are incorrect. I checked the query generated of Metabase and is considering this filter DateTimeOffsetFromParts(2010, 12, 1, 0, 0, 0, 0, **-2**, 0, 7) independent of timestamp I set.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to question 
2. Click on SQL for this question
4. See the filter

**Expected behavior**
When I change timestamp in Admin Portal this configuration should reflect in query/filter/question. 

**Screenshots**
My timestamp configuration:
![image](https://user-images.githubusercontent.com/38772077/91306807-75b8d180-e783-11ea-99cc-7f15f834b7f6.png)
My query: 
![image](https://user-images.githubusercontent.com/38772077/91306899-9a14ae00-e783-11ea-9b8d-be781bbbbe88.png)
Now I change timestamp:
![image](https://user-images.githubusercontent.com/38772077/91306956-b284c880-e783-11ea-88ea-d4691aa6123a.png)
But my query is the same:
![image](https://user-images.githubusercontent.com/38772077/91307049-d6480e80-e783-11ea-8972-aec1dcc305d6.png)

**Information about your Metabase Installation:**
I'm using Enterprise Edition trial - v1.36.3

You can get this information by going to Admin -> Troubleshooting.

Your browser and the version: Firefox 79.0
Your operating system: Ubuntu 20.04.1 LTS
Your databases: SQLServer 2017
Metabase version: v1.36.3
Metabase hosting environment: Jar-file on Ubuntu
Metabase internal database: H2 (default)

**Severity**
Critical. Date filter is mandatory requirement in my project and I not want aprove this tool.

**Additional context**
We are only testing what the Metabase is capable of doing.

**Comment by flamber** [comment] 2020-08-26 14:30
Hi @tiagoferrucio 
Please use the support email, when using the Enterprise Edition.
Metabase currently doesn't support Reporting Timezone for SQL Server, so you should use instance timezone. If you provided "Diagnostic Info" from Admin > Troubleshooting, then it's easier to see which timezone you are using.
Timezone issues are notoriously difficult to debug, which is why we have a troubleshooting guide for it:
https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html
This might be a duplicate of #10824

**Closed** 2020-08-28 15:48 UTC
Labels: .Needs Triage, Type:Bug
