### ISSUE TITLE
Not catching mongodb queries

### ISSUE THREAD

**Issue by davidvirgilnaranjo** [metabase/metabase#27420] opened 2022-12-25 08:37 UTC
**Describe the bug**
Expecting mongodb queries done by saved questions to be populated from the cache. I tried to see in the chrome response if it contained a cached field and it doesn't. 

**Logs**
This is the response from the server for one of the questions:

```
{
  "data": {
    "rows": [
      ...
    ],
    "cols": [
        ...
    ],
    "native_form": {
      "projections": [
        "createdDate~~~month",
        "xxx",
        "sum"
      ],
      "query": [
        {
          "$match": {
            "$and": [
              {
                "$expr": {
                  "$gte": [
                    "$createdDate",
                    {
                      "$dateFromString": {
                        "dateString": "2022-09-01T00:00Z"
                      }
                    }
                  ]
                }
              },
              {
                "$expr": {
                  "$lt": [
                    "$createdDate",
                    {
                      "$dateFromString": {
                        "dateString": "2023-01-01T00:00Z"
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "$group": {
            "_id": {
              "createdDate~~~month": {
                "$let": {
                  "vars": {
                    "parts": {
                      "$dateToParts": {
                        "timezone": "GMT",
                        "date": "$createdDate"
                      }
                    }
                  },
                  "in": {
                    "$dateFromParts": {
                      "timezone": "GMT",
                      "year": "$$parts.year",
                      "month": "$$parts.month"
                    }
                  }
                }
              },
              "exchange": "$exchange"
            },
            "sum": {
              "$sum": "$notional"
            }
          }
        },
        {
          "$sort": {
            "_id": 1
          }
        },
        {
          "$project": {
            "_id": false,
            "createdDate~~~month": "$_id.createdDate~~~month",
            "exchange": "$_id.exchange",
            "sum": true
          }
        },
        {
          "$sort": {
            "createdDate~~~month": 1,
            "exchange": 1
          }
        }
      ],
      "collection": "analytics_trades",
      "mbql?": true
    },
    "results_timezone": "GMT",
    "results_metadata": {
      "columns": [
        {
          "description": null,
          "semantic_type": "type/CreationTimestamp",
          "coercion_strategy": null,
          "unit": "month",
          "name": "createdDate",
          "settings": null,
          "field_ref": [
            "field",
            2204,
            {
              "temporal-unit": "month"
            }
          ],
          "effective_type": "type/Instant",
          "id": 2204,
          "visibility_type": "normal",
          "display_name": "CreatedDate",
          "fingerprint": {
            "global": {
              "distinct-count": 454,
              "nil%": 0.0
            },
            "type": {
              "type/DateTime": {
                "earliest": "2020-07-02T13:07:15Z",
                "latest": "2022-11-03T14:37:22.409Z"
              }
            }
          },
          "base_type": "type/Instant"
        },
        {
          "description": null,
          "semantic_type": "type/Category",
          "coercion_strategy": null,
          "name": "exchange",
          "settings": null,
          "field_ref": [
            "field",
            2205,
            null
          ],
          "effective_type": "type/Text",
          "id": 2205,
          "visibility_type": "normal",
          "display_name": "Exchange",
          "fingerprint": {
            "global": {
              "distinct-count": 3,
              "nil%": 0.0
            },
            "type": {
              "type/Text": {
                "percent-json": 0.0,
                "percent-url": 0.0,
                "percent-email": 0.0,
                "percent-state": 0.0,
                "average-length": 7.386427898209236
              }
            }
          },
          "base_type": "type/Text"
        },
        {
          "display_name": "xxx",
          "semantic_type": null,
          "settings": null,
          "field_ref": [
            "aggregation",
            0
          ],
          "name": "sum",
          "base_type": "type/Decimal",
          "effective_type": "type/Decimal",
          "fingerprint": {
            "global": {
              "distinct-count": 10,
              "nil%": 0.0
            },
            "type": {
              "type/Number": {
                "min": 162979.57710673782,
                "q1": 536142.0,
                "q3": 2.8971599087402E9,
                "max": 5.9856977315218E9,
                "sd": 2.073094226194324E9,
                "avg": 1.3846013028346431E9
              }
            }
          }
        }
      ]
    },
    "insights": null
  },
  "database_id": 35,
  "started_at": "2022-12-25T08:29:23.834914Z",
  "json_query": {
    "constraints": {
      "max-results": 10000,
      "max-results-bare-rows": 2000
    },
    "type": "query",
    "middleware": {
      "js-int-to-string?": true,
      "ignore-cached-results?": false
    },
    "database": 35,
    "query": {
      "source-table": 117,
      "aggregation": [
        [
          "sum",
          [
            "field",
            2211,
            null
          ]
        ]
      ],
      "breakout": [
        [
          "field",
          2204,
          {
            "temporal-unit": "month"
          }
        ],
        [
          "field",
          2205,
          null
        ]
      ]
    },
    "parameters": [
      {
        "type": "date/all-options",
        "value": "past3months~",
        "target": [
          "dimension",
          [
            "field",
            2204,
            null
          ]
        ],
        "id": "ced2935b"
      }
    ],
    "async?": true,
    "cache-ttl": 3013
  },
  "average_execution_time": null,
  "status": "completed",
  "context": "dashboard",
  "row_count": 10,
  "running_time": 22771
}
```
I am omitting the data and columns from the response. But you can see all the other fields. There is no cached field.

**Screenshots**
<img width="827" alt="Screenshot 2022-12-25 at 09 24 20" src="https://user-images.githubusercontent.com/107469028/209461607-92ac4bd6-7a52-42ed-9266-6af7941bb928.png">

**Information about your Metabase Installation:**

Metabase Version: v0.45.1

**Comment by flamber** [comment] 2022-12-25 11:52
Duplicate of #25915

**Closed by flamber** 2022-12-25 11:52 UTC
Labels: Type:Bug, .Needs Triage
