### ISSUE TITLE
Pivot tables: dynamic column heading widths

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14350] opened 2021-01-11 19:32 UTC
It would be good if the width for columns were a bit wider so that we don't need to ellipsify headings like this. I think we'd want them to be the width of the widest value or the width of the column title, whichever is wider. Though there should be a max-width to guard against extremely long titles; maybe 200px?

![](https://user-images.githubusercontent.com/2223916/102947342-f361c500-4477-11eb-8522-81d2e993286f.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by cchaussat** [comment] 2021-04-24 07:37
Why did you remove this story from 0.38.3 ???
I must say that now the pivot tables are just not usable for me due to this limitation of fixed (short) column width. I think it is a must to implement this feature. Thanks.

**Comment by ybakshi** [comment] 2021-05-11 10:43
Why not to keep it customizable/movable so that it is 100% useful to 100% users as 200px may be a need for some but may be a waste space for others

**Comment by jereh16** [comment] 2021-06-11 14:30
The width of the columns should 
a) adjust to the size of the widget and
b) customizable by the user (by e.g. dragging a width handle in the header of the column)

**Comment by IcyrinI** [comment] 2021-09-29 09:32
Some hate needed:
I thought Metabase is reporting tool.
If I cannot read numbers in simple pivot table, the whole metabase is useless.

**Comment by cchaussat** [comment] 2021-09-30 04:25
After several postpones to a future version, it now seems that #14350 and #16391 have both been closed. Does it mean that you will never implement adjustable pivot table column width ??? If yes it is important for me to know, because at the moment I am still waiting for this feature. If it never comes then I have to know and to switch from Metabase to another solution. Thanks for clarifying.

**Comment by flamber** [comment] 2021-09-30 07:45
@cchaussat #14350 (this issue) is not closed. #16391 is a duplicate of this issue. There's currently no timeline for this issue.

**Comment by SAMZONG** [comment] 2022-03-29 07:52
follow

**Comment by jernestosuarez** [comment] 2022-09-07 15:42
Adding this feature will be a great improvement for pivot tables, at least enabling an option to make wider a column. Exists people with varchar(50) fields ; )

**Comment by ifurnas** [comment] 2022-11-17 13:47
> The width of the columns should
> a) adjust to the size of the widget and
> b) customizable by the user (by e.g. dragging a width handle in the header of the column)

I think that you should have both options available. My suggestion for the implementation is:

- When you open the visualization the columns should auto-size to fit the header and content.
- When you expand a column it should auto-size to fit the header and content
- It should always be possible for the user to resize the column for the width that he prefers along the process.

**Closed** 2023-01-12 16:14 UTC
Labels: Priority:P2, Type:New Feature, .Frontend, Visualization/Tables

**Comment by thanhnhhuvt2000** [comment] 2023-05-22 18:46
> > The width of the columns should
> > a) adjust to the size of the widget and
> > b) customizable by the user (by e.g. dragging a width handle in the header of the column)
> 
> I think that you should have both options available. My suggestion for the implementation is:
> 
> * When you open the visualization the columns should auto-size to fit the header and content.
> * When you expand a column it should auto-size to fit the header and content
> * It should always be possible for the user to resize the column for the width that he prefers along the process.

any update bro

**Comment by thalibarrifqi** [comment] 2023-10-02 01:57
> > The width of the columns should
> > a) adjust to the size of the widget and
> > b) customizable by the user (by e.g. dragging a width handle in the header of the column)
> 
> I think that you should have both options available. My suggestion for the implementation is:
> 
> * When you open the visualization the columns should auto-size to fit the header and content.
> * When you expand a column it should auto-size to fit the header and content
> * It should always be possible for the user to resize the column for the width that he prefers along the process.

any update from thsi question?
