### ISSUE TITLE
metabase v0.39.4, connects to mysql8,  error :Client does not support authentication protocol requested by server. plugin type was = 'mysql_native_password'

### ISSUE THREAD

**Issue by gaofei8704** [metabase/metabase#16709] opened 2021-06-22 08:07 UTC
**Describe the bug**
connects to mysql8,it reports a error:Client does not support authentication protocol requested by server. plugin type was = 'mysql_native_password'. We changed to version 39.2，it's was running successful on the same database.

our mysql 8 configuration ：
+------------------+-----------+-----------------------+
| USER             | HOST      | PLUGIN                |
+------------------+-----------+-----------------------+
| root             | %         | mysql_native_password |
| mysql.infoschema | localhost | mysql_native_password |
| mysql.session    | localhost | mysql_native_password |
| mysql.sys        | localhost | mysql_native_password |
+------------------+-----------+-----------------------+

**Logs**

stacktrace
 ["org.mariadb.jdbc.authentication.AuthenticationPluginLoader.get(AuthenticationPluginLoader.java:52)"
  "org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authenticationHandler(AbstractConnectProtocol.java:727)"
  "org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:546)"
  "org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1367)"
  "org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:635)"
  "org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)"
  "org.mariadb.jdbc.Driver.connect(Driver.java:89)"
  "java.sql.DriverManager.getConnection(DriverManager.java:664)"
  "java.sql.DriverManager.getConnection(DriverManager.java:208)"
  "--> connection_pool$proxy_data_source$reify__35108.getConnection(connection_pool.clj:29)"],
 :context :ad-hoc,
 :error
 "Client does not support authentication protocol requested by server. plugin type was = 'mysql_native_password'",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:database 2,
  :query
  {:source-table 6,
   :fields
   [[:field 61 nil]
    [:field 43 nil]
    [:field 46 nil]
    [:field 50 nil]
    [:field 40 nil]
    [:field 60 nil]
    [:field 37 nil]
    [:field 53 nil]
    [:field 42 nil]
    [:field 56 nil]
    [:field 59 nil]
    [:field 51 nil]
    [:field 63 nil]
    [:field 52 {:temporal-unit :default}]
    [:field 41 nil]
    [:field 47 {:temporal-unit :default}]
    [:field 57 nil]
    [:field 62 nil]
    [:field 44 nil]
    [:field 49 nil]
    [:field 55 nil]
    [:field 54 {:temporal-unit :default}]
    [:field 58 nil]
    [:field 48 {:temporal-unit :default}]
    [:field 45 nil]
    [:field 38 nil]
    [:field 39 nil]],
   :limit 2000},
  :type :query,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :nested? false,
   :query-hash
   [-68, -85, 119, 43, -34, -40, 6, 44, -82, 40, 32, -48, 107, 13, 112, 38, -101, -119, 5, 31, 113, -101, -1, 82, -106,
    -65, 52, 59, 6, -47, 38, -11]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :data {:rows [], :cols []}}
**To Reproduce**

**Expected behavior**

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.x. OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)

**Comment by flamber** [comment] 2021-06-22 08:37
Duplicate of #16710

**Closed by flamber** 2021-06-22 08:37 UTC
Labels: .Needs Triage, Type:Bug
