### ISSUE TITLE
Drill action on charts with date axis produces incorrect filter states

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#22644] opened 2022-05-11 20:44 UTC
**Describe the bug**
The drill action on charts with date axis produces incorrect filter states. It happens when you drill from the query builder or from a dashboard.

**To Reproduce**
1. New question -> Sample Database -> Orders
2. Summarize by Created At (month) and show as a line chart
3. Click on any point on of the chart line and select "View these Orders"
4. Click on the filter pill
5. Even though the filter is applied is correct, it shows an invalid date in the filter widget

**Expected behavior**
Filter widgets should show correct values.

**Screenshots**

<video src="https://user-images.githubusercontent.com/14301985/167943864-95a3747d-4b7a-4989-b04d-91af8136ac6f.mov" />

**Information about your Metabase Installation:**
In the latest `master` and `release-x.43.x` it shows today date. However, the bug existed before and the filter date input was just empty on `release-x.42.x`.

**Comment by flamber** [comment] 2022-05-13 11:29
Duplicate of #12496

**Closed by flamber** 2022-05-13 11:29 UTC
Labels: Type:Bug, Querying/GUI, .Needs Triage
