### ISSUE TITLE
Custom expression input appends its current value on every alphabet typed

### ISSUE THREAD

**Issue by yappkahowe** [metabase/metabase#20437] opened 2022-02-11 03:05 UTC
**Describe the bug**
When I try to add custom column, for every alphabet I typed into the field formula input, the input appends its current value to itself before inserting the alphabet I just typed. I attached two screen recordings. In first recording, I type five alphabets: a, b, c, d, e, f. In second recording, I type five numbers: 1, 2, 3, 4, 5. The bug only appears if an alphabet is typed.

**Logs**
Uncaught Error: String currently can't contain brackets: Item Application → field,Destination or Origin,[object Object]
    at y (index.js:115:13)
    at a (index.js:24:10)
    at p (index.js:81:10)
    at suggest.js:93:17
    at Array.map (<anonymous>)
    at r.query (suggest.js:90:10)
    at i.value (ExpressionEditorTextfield.jsx:338:39)
    at Object.onFocus (ExpressionEditorTextfield.jsx:207:12)
    at t.onFocus (ace.js:275:24)
    at _.ace.define.r._emit.r._dispatchEvent (ace.js:3462:19)

**To Reproduce**
1. Go to 'New Question'
2. Select a saved question/model which has at least one custom column as 'Data'
3. Add a new custom column
4. Type alphabet into field formula
5. See error

**Screenshots**

https://user-images.githubusercontent.com/3599324/153529742-da0c0645-d676-4bd4-9036-fb7550d1e6a8.mp4

https://user-images.githubusercontent.com/3599324/153530294-5295705b-5108-4ddb-9642-deff997d9c42.mp4

**Information about Metabase Installation:**

- Browser: Chrome 98.0.4758.82
- operating system: Windows 11 OS Build 22000.493
- Database: MariaDB 10.5
- Metabase version: 0.42
- Metabase hosting environment: Docker
- Metabase internal database: MariaDB 10.5

**Severity**
This issue is blocking some users to add custom column to their questions.

**Comment by flamber** [comment] 2022-02-11 12:02
Duplicate of #15316

**Closed by flamber** 2022-02-11 12:02 UTC
Labels: Type:Bug, .Needs Triage
