### ISSUE TITLE
Dashboard category filter only filtering on a subset of values

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5150] opened 2017-05-19 23:02 UTC
I have a category filter on a dashboard mapped to a card on a category field (`Last Name`). The question returns 2,000 rows. The filter dropdown shows the first 300 values for Last Name, but if I type in a value that I know is present in the table but is past the first 300 values, I get no results.

Here I've typed "Bryant" into the filter box and would expect the dropdown to show "Bryant" as a valid selection below the filter box, since as you can see, I've scrolled my table to the corresponding row, and that value is definitely present in the table:

![screen shot 2017-05-19 at 3 55 45 pm](https://cloud.githubusercontent.com/assets/2223916/26269875/4d390bb0-3cac-11e7-8984-413d1387858e.png)

"Banister" is the last value it shows:

![screen shot 2017-05-19 at 3 56 01 pm](https://cloud.githubusercontent.com/assets/2223916/26269881/505785ce-3cac-11e7-8627-271349ece96a.png)

Shouldn't this filter widget be giving me a plain input box rather than a dropdown plus filter box since there are > 300 values for the field I'm filtering on?

**Comment by moumny** [comment] 2017-05-23 15:37
Related https://github.com/metabase/metabase/issues/5128

**Comment by tlrobinson** [comment] 2017-05-23 17:22
Yeah I think this is a duplicate of #5128. If we have field values we show them instead of an input.

**Comment by moumny** [comment] 2017-06-16 18:10
Also, apart from the fact that field/value api endpoint fetches values without checking for cardinality, there's another in the cardinality check during the analysis.
If your column contains a null value and it ends up being on of the 301 values queries, then condition checks that there are less than or equal 300 non nil values. in this case it will be true regardless of the cardinality of the column. We fixed it by querying for 302 values...

**Comment by camsaul** [comment] 2017-08-03 23:09
Basically the same underlying issue as #5323. This was resolved by #5510.

**Closed by camsaul** 2017-08-03 23:09 UTC
Labels: Bug, Dashboards, Priority/P1

**Comment by mazameli** [comment] 2017-08-29 21:54
If this is a duplicate of #5128 and/or #5323, should we close those as well? I noticed @salsakran reopened those two issues.

**Comment by mazameli** [comment] 2017-09-27 19:05
Hey everyone. Just a heads up that [we've shipped version 0.26](http://www.metabase.com/blog/Metabase-0.26) which fixes this issue.
