### ISSUE TITLE
Query editor got broken after a while

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#30817] opened 2023-05-17 11:18 UTC
### Describe the bug

Got `Something's gone wrong` with the query below

### To Reproduce

1. New question
2. Orders
3. join with people
4. Group by created at
5. summarize by count
6. sort created at
7. should see `Something's gone wrong` now

### Logs

Looks like a metabase lib bug
```
Uncaught Error: :all is not ISeqable
    cljs$core$seq core.cljs:1253
    cljs$core$IFn$_invoke$arity$3 core.cljs:2498
    cljs$core$IFn$_invoke$arity$3 core.cljs:2585
    cljs$core$IFn$_invoke$arity$4 core.cljs:2626
    cljs$core$IFn$_invoke$arity$3 core.cljs:5275
    metabase$lib$util$remove_clause util.cljc:74
    5 core.cljs:5390
    cljs$core$IFn$_invoke$arity$5 app-main.hot.bundle.js:569196
    cljs$core$apply_to core.cljs:3917
    cljs$core$IFn$_invoke$arity$5 core.cljs:3996
    cljs$core$IFn$_invoke$arity$variadic util.cljc:251
    remove_replace_STAR_ remove_replace.cljc:56
    nval core.cljs:2500
    cljs$core$IFn$_invoke$arity$3 app-main.hot.bundle.js:557548
    cljs$core$IReduce$_reduce$arity$3 core.cljs:3529
    cljs$core$IFn$_invoke$arity$3 core.cljs:2570
    metabase$lib$remove_replace$remove_replace_STAR_ remove_replace.cljc:53
    cljs$core$IFn$_invoke$arity$3 remove_replace.cljc:80
    cljs$core$IFn$_invoke$arity$5 core.cljs:3952
    cljs$core$IFn$_invoke$arity$4 core.cljs:3948
    cljs$core$IFn$_invoke$arity$3 core.cljs:3942
    cljs$core$IFn$_invoke$arity$2 core.cljs:3936
    cljs$core$IFn$_invoke$arity$2 core.cljs:3971
    metabase$lib$core$remove_clause__delegate core.cljc:55
    cljs$core$IFn$_invoke$arity$3 js.cljs:176
    metabase$lib$js$remove_clause js.cljs:171
    clearOrderBys order_by.ts:60
    clearOrderBys order_by.ts:59
    revert steps.ts:122
    revert steps.ts:247
    _loop steps.ts:326
    getStageSteps steps.ts:302
    getQuestionSteps steps.ts:180
    steps NotebookSteps.tsx:50
    React 3
    NotebookSteps NotebookSteps.tsx:46
    React 11
    unstable_runWithPriority scheduler.development.js:653
    React 6
```

### Information about your Metabase installation

[master](3f5168c655dafdc8b3f78b38b0e967ff0899177f)

### Severity

High

**Comment by kulyk** [comment] 2023-05-17 11:49
Duplicate of #30743

**Closed by kulyk** 2023-05-17 11:49 UTC
Labels: Type:Bug, .Needs Triage
