### ISSUE TITLE
MySQL datetime filed filter is too slow

### ISSUE THREAD

**Issue by gojuukaze** [metabase/metabase#12587] opened 2020-05-26 09:47 UTC
Metabase generate the following sql when filter datetime. And MySQL cannot use index
```sql
SELECT count(*) AS `count`
FROM `table`
WHERE date(created_at) = date(now());
```
It's better to use `date_add()` or string ,

```sql
SELECT count(*) AS `count`
FROM `table`
WHERE created_at between date(now()) and date(date_add(now(),interval 1 day));
# or
SELECT count(*) AS `count`
FROM `table`
WHERE created_at between '2020-5-26' and '2020-5-27';
```

**Comment by flamber** [comment] 2020-05-26 09:56
Duplicate of #11502

**Closed by flamber** 2020-05-26 09:56 UTC
Labels: .Needs Triage, Type:New Feature
