### ISSUE TITLE
Current metabase shows datetime values with time after midnight as 24:xy instead of 00:xy

### ISSUE THREAD

**Issue by lubikx** [metabase/metabase#13956] opened 2020-12-04 07:43 UTC
**Describe the bug**
Current metabase shows datetime values with time after midnight as 24:xy instead of 00:xy

**Logs**
Not applicable, UI problem.

**To Reproduce**
1. Have data with for example datetime 2020-12-02 00:45:12 (using mariadb backend)
2. Add it to easy question result
3. Show result
4. It shows time as 24:45

**Expected behavior**
Show time as 00:45 instead of 24:45

**Screenshots**
![Screenshot 2020-12-04 084256](https://user-images.githubusercontent.com/11309431/101135882-c060aa00-360c-11eb-9333-f94aa1b2a461.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
- Your operating system: Windows 10 64 bit
- Your databases: Maria DB
- Metabase version: v0.37.3
- Metabase hosting environment: docker
- Metabase internal database: Postgres

**Severity**
annoying

**Additional context**
Not applicable

**Comment by flamber** [comment] 2020-12-04 09:48
Duplicate of #9538

**Closed by flamber** 2020-12-04 09:48 UTC
Labels: .Needs Triage, Type:Bug
