### ISSUE TITLE
Filters from dashboard not used in question

### ISSUE THREAD

**Issue by jhettler** [metabase/metabase#11503] opened 2019-12-11 20:55 UTC
**Describe the bug**
If you choose two or more values in one dashboard filter (e.g. 2 ids), these values filter dashboard correctly, but if you navigate to the detail (question) only first of those values is used in filter. I would expect that all filter values from dashboard should be used in question (navigated from dashboard).

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2019-12-11 21:58
Reproduced on `master`.
**Steps:**
1. Simple question > Sample Dataset > Orders, save and add to dashboard
2. Add two ID filters, ID1=>Orders.ID and ID2=>Products.ID
3. Input `1`,`2` in filter ID1 and click question. Result: Object Detail of Orders.ID=1
4. Input `1`,`2` in filter ID2 and click question. Result: Shows all orders with Products.ID=1

**Comment by daltojohnso** [comment] 2021-06-14 22:56
Looks like this was fixed at some point, so I'm closing the issue.

Following the instructions from @flamber here is what I see.

for order ids 1,2:
![Screen Shot 2021-06-14 at 3 52 04 PM](https://user-images.githubusercontent.com/13057258/121969274-c7d5de00-cd28-11eb-804f-61bc6cc1e3c3.png)
and drilling down to the question:
![Screen Shot 2021-06-14 at 3 52 13 PM](https://user-images.githubusercontent.com/13057258/121969290-d15f4600-cd28-11eb-9809-2c574d70add0.png)

for product ids 1,2:
![Screen Shot 2021-06-14 at 3 52 24 PM](https://user-images.githubusercontent.com/13057258/121969298-d623fa00-cd28-11eb-9917-094a60d49c68.png)
and drilling down to the question:
![Screen Shot 2021-06-14 at 3 52 33 PM](https://user-images.githubusercontent.com/13057258/121969307-d8865400-cd28-11eb-9a33-10988f79f17f.png)

**Closed** 2021-06-14 22:56 UTC
Labels: .Correctness, Priority:P2, Querying/GUI, Querying/Parameters & Variables, Reporting/Dashboards, Type:Bug
