### ISSUE TITLE
Dashboard can't be filtered by text key column

### ISSUE THREAD

**Issue by nefremov** [metabase/metabase#15171] opened 2021-03-15 17:34 UTC
**Describe the bug**
If  question primary key is text column then neither "ID" not "Category" type filter cann't be bound to on-click action

**To Reproduce**
1. Create question based on db table with text primary key TextID
2. Create dashboard
3. Add created question to the new dashboard
4. Add two dashboard filters - "ID" and "Category"
5. Click on "Click behavior" button on question area
6. Select any column and choose "Update a dashboard filter" action
7. TextID column is not proposed as filer value neither for "ID" filter not for "Category" filter

**Expected behavior**
Propose TextID column at least for one of the filters

**Information about your Metabase Installation:**

 v1.38.1

Chrome Version 88.0.4324.190 (Official Build) (64-bit)

**Severity**
Blocker

**Comment by flamber** [comment] 2021-03-15 18:08
Duplicate of #15170

**Closed by flamber** 2021-03-15 18:08 UTC
