### ISSUE TITLE
Column list is not updated in saved questions

### ISSUE THREAD

**Issue by mvrabel** [metabase/metabase#6823] opened 2018-01-30 12:16 UTC
- *Repeatable steps to reproduce the issue*

1. Create table my_table with columns column_1, column_2, column_3
2. Metabase -> new question -> select a table -> my_table
3. Save question AS my_question
4. Add column column_4 to my_table
5. Sync with database 
6. Check admin panel -> data model -> my_table  ... column_4 was added 
7. Open my_question
8. my_question displays columns columns column_1, column_2, column_3 (AS expected)  
Now to the problem
9. Click the gear wheel to customize columns
10. column_4 Is not listed. 
workaround:
11. Click "Reset to defaults"
12. column_4 is now listed. 

The biggest problem is that when you have a large number of columns that you rearanged you have to manualy rearange them again.   Repeat this every time you have to rename, delete, add a column to a table

- Your browser and the version: Chrome e 63.0.3239.132
- Your operating system: Windows 10
- Your databases: Postgres 9.6
- Metabase version: 0.27.2
- Metabase hosting environment: CentOS 7
- Metabase internal database: (default). Probably H2, I didnt cahnge it.

**Comment by mvrabel** [comment] 2018-01-30 12:16
It is pracical the same issue as #6670

**Comment by mvrabel** [comment] 2018-06-18 15:07
Hi @salsakran, has there been any update on this ?
This issue is still present in version 0.29.3. 
If you don't have resources/time to fix this, could you please show me direct me to the code which retrieves the column list ? I could dig around and create a PR with the fix :)

**Comment by flamber** [comment] 2020-05-28 11:11
I cannot reproduce on 0.35.3 - think it might have been fixed in 0.33 (if not before)

**Closed by flamber** 2020-05-28 11:11 UTC
Labels: Priority:P2, Type:Bug, Visualization/Chart Settings
