### ISSUE TITLE
Bar graph truncating last value when grouping by date

### ISSUE THREAD

**Issue by dudleycarr** [metabase/metabase#1895] opened 2016-02-06 16:42 UTC
Metabase: 0.14.1

Here's a sample table in Postgres:
```sql
CREATE TABLE test (
  value INT,
  date DATE
  );
  
INSERT INTO test (value, date) VALUES
  (10, '2015-12-01'),
  (20, '2016-01-01'),
  (30, '2016-02-01')
  ;
```

Here is the query in Metabase displayed as a table:
<img width="778" alt="screenshot 2016-02-06 08 36 48" src="https://cloud.githubusercontent.com/assets/218825/12867831/41d3352c-ccad-11e5-95e9-4e4a9944bb22.png">

Here's the bar graph visualization with February data not showing:
<img width="942" alt="screenshot 2016-02-06 08 41 08" src="https://cloud.githubusercontent.com/assets/218825/12867839/6e94a7c6-ccad-11e5-9492-154f45ce1c8e.png">

**Comment by camsaul** [comment] 2016-02-10 19:52
This looks like the same issue as #1635. @agilliland or @tlrobinson can you confirm or deny these allegations :question:

**Comment by dudleycarr** [comment] 2016-02-13 15:01
@camsul for what it's worth, I think this issue is a duplicate of #1635 in spite of it's deceptive issue name :)

**Comment by camsaul** [comment] 2016-02-16 00:52
Duplicate of #1635

**Comment by tlrobinson** [comment] 2016-02-17 08:00
Reopening this to specifically track the truncated bar issue, which is separate from the timezone off-by-1 issue in #1635

**Closed** 2016-02-23 06:12 UTC
Labels: Bug, Visualization
