### ISSUE TITLE
pg type/Time cannot be summarized properly (bin set to month automatically)

### ISSUE THREAD

**Issue by flavienSindou** [metabase/metabase#17898] opened 2021-09-15 09:52 UTC
**Describe the bug**
Using a postgresql db time field, it is not possible to summarize the data from the UI. We cannot select the bin which is automatically set to "month".

**Logs**
No server or Js error

**To Reproduce**
1.Create a pg table with a Time field
2. Go to Metabase >> ask a question >> simple question
3. Click on Summarize, select your time field , no option is available for binning.

**Expected behavior**
As for datetime object, we expect time values to be groupable by minute/ quarter / hour

**Screenshots**
![image](https://user-images.githubusercontent.com/62057754/133411011-3cced584-c128-43c6-b82e-cb570e3d93dc.png)
![image](https://user-images.githubusercontent.com/62057754/133411308-cc2ea4de-e676-4379-95ec-a5edc144b07d.png)
![image](https://user-images.githubusercontent.com/62057754/133411503-f7ead2bb-12a1-44a3-a8ed-07c750693878.png)
![image](https://user-images.githubusercontent.com/62057754/133411753-59e78a26-f294-40df-8a14-9e99d6d6a235.png)

**Information about your Metabase Installation:**
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 Edg/93.0.961.38",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "5.4.109+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.7 (Debian 10.7-1.pgdg90+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-08-26",
      "tag": "v0.40.3.1",
      "branch": "release-x.40.x",
      "hash": "0550b86"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by flavienSindou** [comment] 2021-09-15 09:55
Possible duplication of https://github.com/metabase/metabase/issues/17598

**Comment by flamber** [comment] 2021-09-15 10:03
Duplicate of #17598

**Closed by flamber** 2021-09-15 10:03 UTC
Labels: Type:Bug, .Needs Triage
