### ISSUE TITLE
Filters from different databases are not working in new versions of Metabase

### ISSUE THREAD

**Issue by LuckyDSh** [metabase/metabase#25901] opened 2022-10-12 17:43 UTC
**Describe the bug**
# No one field filter that is related to different DB is not working (an error thrown by Meta)

### we faced the problem in SQL/Native questions that contain tables from different DataBases: 

![image](https://user-images.githubusercontent.com/60887607/195410509-dfaf9bf9-4c17-4056-a359-8ec7aca43388.png)

## Kindly ask you to solve the issue** 

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
## we create a field filter in the SQL/Native Query
![image](https://user-images.githubusercontent.com/60887607/195509915-aff5c864-fa21-419b-9a50-b7fd757532d3.png)

## we change the data base on the left-top corner
![image](https://user-images.githubusercontent.com/60887607/195509985-d0baf2de-28a5-4348-a9c4-073fb15cc31b.png)
![image](https://user-images.githubusercontent.com/60887607/195509994-0c3d7c67-3f06-4791-815b-712948216e30.png)

## Configure the filter
![image](https://user-images.githubusercontent.com/60887607/195510068-b41cef3b-b9f3-46b1-b4ed-264ec8c26dd7.png)

## Run the query - and got this type of error
![image](https://user-images.githubusercontent.com/60887607/195510116-576ae68a-665c-4330-b5e7-5cb2a0d0df72.png)

**Expected behavior**

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.g., Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.g., OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.g, MySQL, Postgres, MongoDB, …)
- Metabase version: (e.g., 0.19.3)
- Metabase hosting environment: (e.g., Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.g., H2 (default), Postgres or MySQL)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by paoliniluis** [comment] 2022-10-12 19:31
Hi @LuckyDSh , it's very difficult for us to identify what's going on here if we don't have reproduction steps, information about your instance and databases, etc. Kindly ask you to please complete the information that we ask or close the issue

**Comment by LuckyDSh** [comment] 2022-10-13 05:37
> Hi @LuckyDSh , it's very difficult for us to identify what's going on here if we don't have reproduction steps, information about your instance and databases, etc. Kindly ask you to please complete the information that we ask or close the issue

Good day sir, noticed - we uploaded screenshots + the steps of execution (hope it help)

**Comment by flamber** [comment] 2022-10-13 08:37
Duplicate of #14145

**Closed by flamber** 2022-10-13 08:37 UTC
Labels: Type:Bug, .Needs Triage

**Comment by LuckyDSh** [comment] 2022-10-13 13:07
> Duplicate of #14145

Not satisfied with the solution 

(1) In issue #14145 there is a problem just in frontal visualization 
Like this: 
![image](https://user-images.githubusercontent.com/60887607/195602635-db5e9ac3-5503-4c0a-b3ea-b3cfffec8d80.png)

## easily can be solved by switching Database 
Like this: 
![image](https://user-images.githubusercontent.com/60887607/195603022-68a40ac9-3845-4878-ab6a-4ac8aaf1cdbb.png)

## However NO Error is thrown and query runs in a normal way 

## In our case there is a fatal error 
### and NO Result can be shown 
![image](https://user-images.githubusercontent.com/60887607/195603337-7949ed36-c8ab-4fbc-bf63-23e80079cdbc.png)

# Supposed problem: 
## Meta denies any "Field filter" that is out of the defined Data base

**Comment by flamber** [comment] 2022-10-13 13:11
Metabase will not allow using filters that are not in the database. We will not change that. Then you have to stay on pre-42.
