### ISSUE TITLE
Error generating fingerprint for Field, Dashboards do not show the data

### ISSUE THREAD

**Issue by ArtmanMichael19** [metabase/metabase#13092] opened 2020-08-10 17:28 UTC
**Describe the bug**
Some dashboards are not displayed if global date filters are applied
Error message in the logs: Error generating fingerprint for Field
The questions work  correctly, but in dashboards - the error appears

**Logs**
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:56:59+01:00 DEBUG metabase.middleware.log GET /api/session/properties 200 202.5 ms (2 DB calls) App DB connections: 3/15 Jetty threads: 5/50 (28 idle, 0 queued) (179 total active threads) Queries in flight: 1 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:56:59+01:00 DEBUG metabase.middleware.log GET /api/user/current 200 287.2 ms (3 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (28 idle, 0 queued) (179 total active threads) Queries in flight: 1 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:00+01:00 DEBUG metabase.middleware.log GET /api/database 200 290.1 ms (3 DB calls) App DB connections: 4/15 Jetty threads: 6/50 (26 idle, 0 queued) (179 total active threads) Queries in flight: 1 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:01+01:00 DEBUG metabase.middleware.log POST /api/card/722/query 202 [ASYNC: canceled] 28.5 s (6 DB calls) App DB connections: 3/15 Jetty threads: 5/50 (27 idle, 0 queued) (179 total active threads) Queries in flight: 0 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:01+01:00 DEBUG metabase.middleware.log GET /api/dashboard/43 200 1.9 s (19 DB calls) App DB connections: 3/15 Jetty threads: 3/50 (29 idle, 0 queued) (179 total active threads) Queries in flight: 0 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:02+01:00 DEBUG metabase.middleware.log GET /api/collection/root 200 193.8 ms (2 DB calls) App DB connections: 14/15 Jetty threads: 32/50 (1 idle, 0 queued) (179 total active threads) Queries in flight: 0 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:02+01:00 INFO metabase.api.card Question's average execution duration is 1.9 s; using 'magic' TTL of 56.0 s 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:02+01:00 INFO metabase.api.card Question's average execution duration is 1.6 s; using 'magic' TTL of 49.0 s 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:02+01:00 INFO metabase.api.card Question's average execution duration is 46.8 s; using 'magic' TTL of 23.4 mins 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:02+01:00 INFO metabase.api.card Question's average execution duration is 1.7 s; using 'magic' TTL of 50.0 s 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:02+01:00 DEBUG metabase.middleware.log GET /api/field/10182/values 200 406.9 ms (4 DB calls) App DB connections: 15/15 Jetty threads: 30/50 (2 idle, 0 queued) (179 total active threads) Queries in flight: 4 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:02+01:00 INFO metabase.api.card Question's average execution duration is 2.1 s; using 'magic' TTL of 1.0 mins 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:02+01:00 INFO metabase.api.card Question's average execution duration is 2.2 s; using 'magic' TTL of 1.1 mins 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:02+01:00 INFO metabase.api.card Question's average execution duration is 1.7 s; using 'magic' TTL of 50.0 s 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:02+01:00 DEBUG metabase.middleware.log GET /api/field/2196/values 200 605.9 ms (3 DB calls) App DB connections: 14/15 Jetty threads: 27/50 (5 idle, 0 queued) (179 total active threads) Queries in flight: 7 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:02+01:00 INFO metabase.api.card Question's average execution duration is 1.6 s; using 'magic' TTL of 49.0 s 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:02+01:00 INFO metabase.api.card Question's average execution duration is 1.7 s; using 'magic' TTL of 50.0 s 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:03+01:00 DEBUG metabase.middleware.log GET /api/field/10173/values 200 769.2 ms (3 DB calls) App DB connections: 15/15 Jetty threads: 24/50 (8 idle, 0 queued) (179 total active threads) Queries in flight: 9 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:03+01:00 DEBUG metabase.middleware.log GET /api/field/10182 200 590.4 ms (6 DB calls) App DB connections: 14/15 Jetty threads: 24/50 (8 idle, 0 queued) (179 total active threads) Queries in flight: 9 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:03+01:00 DEBUG metabase.middleware.log GET /api/database/6/metadata 200 953.9 ms (7 DB calls) App DB connections: 15/15 Jetty threads: 22/50 (10 idle, 0 queued) (179 total active threads) Queries in flight: 9 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:03+01:00 INFO metabase.api.card Question's average execution duration is 2.6 s; using 'magic' TTL of 1.3 mins 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:03+01:00 DEBUG metabase.middleware.log GET /api/field/10129/values 200 452.5 ms (4 DB calls) App DB connections: 15/15 Jetty threads: 21/50 (11 idle, 0 queued) (179 total active threads) Queries in flight: 10 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:03+01:00 DEBUG metabase.middleware.log GET /api/field/2196 200 891.3 ms (7 DB calls) App DB connections: 15/15 Jetty threads: 20/50 (12 idle, 0 queued) (179 total active threads) Queries in flight: 10 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:03+01:00 INFO metabase.api.card Question's average execution duration is 1.8 s; using 'magic' TTL of 55.0 s 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:03+01:00 INFO metabase.api.card Question's average execution duration is 2.2 s; using 'magic' TTL of 1.1 mins 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:03+01:00 INFO metabase.api.card Question's average execution duration is 1.6 s; using 'magic' TTL of 49.0 s 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:03+01:00 INFO metabase.api.card Question's average execution duration is 2.0 s; using 'magic' TTL of 59.0 s 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:03+01:00 DEBUG metabase.middleware.log GET /api/field/10485/values 200 1.2 s (4 DB calls) App DB connections: 15/15 Jetty threads: 15/50 (17 idle, 0 queued) (179 total active threads) Queries in flight: 14 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:03+01:00 INFO metabase.api.card Question's average execution duration is 1.7 s; using 'magic' TTL of 50.0 s 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:03+01:00 INFO metabase.api.card Question's average execution duration is 46.8 s; using 'magic' TTL of 23.4 mins 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:03+01:00 INFO metabase.api.card Question's average execution duration is 1.7 s; using 'magic' TTL of 50.0 s 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:03+01:00 DEBUG metabase.middleware.log GET /api/field/10485 200 1.6 s (6 DB calls) App DB connections: 15/15 Jetty threads: 11/50 (22 idle, 0 queued) (179 total active threads) Queries in flight: 17 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:03+01:00 INFO metabase.api.card Question's average execution duration is 2.3 s; using 'magic' TTL of 1.2 mins 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:03+01:00 INFO metabase.api.card Question's average execution duration is 2.0 s; using 'magic' TTL of 59.0 s 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 INFO metabase.api.card Question's average execution duration is 2.5 s; using 'magic' TTL of 1.3 mins 💾
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 DEBUG metabase.middleware.log GET /api/field/10173 200 1.6 s (7 DB calls) App DB connections: 15/15 Jetty threads: 5/50 (27 idle, 0 queued) (180 total active threads) Queries in flight: 20 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 DEBUG metabase.middleware.log GET /api/field/10129 200 1.9 s (6 DB calls) App DB connections: 14/15 Jetty threads: 5/50 (27 idle, 0 queued) (180 total active threads) Queries in flight: 20 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 DEBUG metabase.middleware.log GET /api/database/2/metadata 200 2.2 s (9 DB calls) App DB connections: 14/15 Jetty threads: 5/50 (27 idle, 0 queued) (181 total active threads) Queries in flight: 20 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 ERROR metabase.sync.util Error generating fingerprint for Field 'date'
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 INFO metabase.query-processor.middleware.cache Query took 1.3 s to run; miminum for cache eligibility is 10.0 s
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 ERROR metabase.sync.util Error generating fingerprint for Field 'date'
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 INFO metabase.query-processor.middleware.cache Query took 1.2 s to run; miminum for cache eligibility is 10.0 s
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 ERROR metabase.sync.util Error generating fingerprint for Field 'date'
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 INFO metabase.query-processor.middleware.cache Query took 1.5 s to run; miminum for cache eligibility is 10.0 s
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 ERROR metabase.sync.util Error generating fingerprint for Field 'DATE'
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 INFO metabase.query-processor.middleware.cache Query took 1.3 s to run; miminum for cache eligibility is 10.0 s
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 DEBUG metabase.middleware.log POST /api/card/774/query 202 [ASYNC: completed] 2.6 s (12 DB calls) App DB connections: 10/15 Jetty threads: 4/50 (29 idle, 0 queued) (183 total active threads) Queries in flight: 19 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 ERROR metabase.sync.util Error generating fingerprint for Field 'DATE'
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 INFO metabase.query-processor.middleware.cache Query took 1.2 s to run; miminum for cache eligibility is 10.0 s
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 DEBUG metabase.middleware.log POST /api/card/706/query 202 [ASYNC: completed] 2.4 s (10 DB calls) App DB connections: 11/15 Jetty threads: 3/50 (29 idle, 0 queued) (183 total active threads) Queries in flight: 18 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 DEBUG metabase.middleware.log POST /api/card/702/query 202 [ASYNC: completed] 2.7 s (12 DB calls) App DB connections: 11/15 Jetty threads: 3/50 (29 idle, 0 queued) (183 total active threads) Queries in flight: 17 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 DEBUG metabase.middleware.log POST /api/card/707/query 202 [ASYNC: completed] 2.5 s (10 DB calls) App DB connections: 11/15 Jetty threads: 3/50 (29 idle, 0 queued) (183 total active threads) Queries in flight: 16 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:04+01:00 DEBUG metabase.middleware.log POST /api/card/707/query 202 [ASYNC: completed] 2.8 s (10 DB calls) App DB connections: 10/15 Jetty threads: 3/50 (29 idle, 0 queued) (183 total active threads) Queries in flight: 15 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:05+01:00 DEBUG metabase.middleware.log POST /api/card/710/query 202 [ASYNC: completed] 2.9 s (10 DB calls) App DB connections: 8/15 Jetty threads: 3/50 (29 idle, 0 queued) (183 total active threads) Queries in flight: 14 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:05+01:00 ERROR metabase.sync.util Error generating fingerprint for Field 'date'
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:05+01:00 INFO metabase.query-processor.middleware.cache Query took 1.1 s to run; miminum for cache eligibility is 10.0 s
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:05+01:00 DEBUG metabase.middleware.log POST /api/card/774/query 202 [ASYNC: completed] 2.8 s (12 DB calls) App DB connections: 8/15 Jetty threads: 4/50 (28 idle, 0 queued) (183 total active threads) Queries in flight: 13 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:05+01:00 DEBUG metabase.middleware.log POST /api/card/710/query 202 [ASYNC: completed] 2.9 s (10 DB calls) App DB connections: 8/15 Jetty threads: 3/50 (29 idle, 0 queued) (183 total active threads) Queries in flight: 12 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:05+01:00 DEBUG metabase.middleware.log POST /api/card/773/query 202 [ASYNC: completed] 3.2 s (12 DB calls) App DB connections: 7/15 Jetty threads: 3/50 (29 idle, 0 queued) (183 total active threads) Queries in flight: 11 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:05+01:00 DEBUG metabase.middleware.log POST /api/card/703/query 202 [ASYNC: completed] 3.4 s (12 DB calls) App DB connections: 7/15 Jetty threads: 4/50 (29 idle, 0 queued) (183 total active threads) Queries in flight: 10 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:05+01:00 DEBUG metabase.middleware.log POST /api/card/773/query 202 [ASYNC: completed] 2.5 s (12 DB calls) App DB connections: 7/15 Jetty threads: 3/50 (29 idle, 0 queued) (183 total active threads) Queries in flight: 9 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:05+01:00 DEBUG metabase.middleware.log POST /api/card/706/query 202 [ASYNC: completed] 3.6 s (10 DB calls) App DB connections: 6/15 Jetty threads: 3/50 (29 idle, 0 queued) (183 total active threads) Queries in flight: 8 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:05+01:00 ERROR metabase.sync.util Error generating fingerprint for Field 'date'
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:05+01:00 INFO metabase.query-processor.middleware.cache Query took 1.9 s to run; miminum for cache eligibility is 10.0 s
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:05+01:00 DEBUG metabase.middleware.log POST /api/card/703/query 202 [ASYNC: completed] 3.5 s (12 DB calls) App DB connections: 8/15 Jetty threads: 4/50 (29 idle, 0 queued) (183 total active threads) Queries in flight: 7 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:06+01:00 DEBUG metabase.middleware.log POST /api/card/775/query 202 [ASYNC: completed] 3.0 s (12 DB calls) App DB connections: 6/15 Jetty threads: 3/50 (29 idle, 0 queued) (183 total active threads) Queries in flight: 6 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:06+01:00 DEBUG metabase.middleware.log POST /api/card/775/query 202 [ASYNC: completed] 4.1 s (12 DB calls) App DB connections: 6/15 Jetty threads: 2/50 (30 idle, 0 queued) (183 total active threads) Queries in flight: 5 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:06+01:00 ERROR metabase.sync.util Error generating fingerprint for Field 'date'
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:06+01:00 INFO metabase.query-processor.middleware.cache Query took 2.4 s to run; miminum for cache eligibility is 10.0 s
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:06+01:00 DEBUG metabase.middleware.log POST /api/card/702/query 202 [ASYNC: completed] 4.1 s (12 DB calls) App DB connections: 7/15 Jetty threads: 2/50 (30 idle, 0 queued) (183 total active threads) Queries in flight: 4 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:06+01:00 DEBUG metabase.middleware.log POST /api/card/708/query 202 [ASYNC: completed] 4.3 s (10 DB calls) App DB connections: 6/15 Jetty threads: 2/50 (30 idle, 0 queued) (183 total active threads) Queries in flight: 3 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:06+01:00 DEBUG metabase.middleware.log POST /api/card/708/query 202 [ASYNC: completed] 4.1 s (10 DB calls) App DB connections: 5/15 Jetty threads: 3/50 (30 idle, 0 queued) (183 total active threads) Queries in flight: 2 (0 queued)
[7e08d9ed-e460-42f3-a855-d87bf0c860f7] 2020-08-10T17:57:33+01:00 DEBUG metabase.middleware.log POST /api/card/722/query 202 [ASYNC: canceled] 31.4 s (6 DB calls) App DB connections: 1/15 Jetty threads: 2/50 (29 idle, 0 queued) (182 total active threads) Queries in flight: 1 (0 queued)

**To Reproduce**

**Expected behavior**
Filtering and displaying correctly.

**Screenshots**
![Metabase_bug_fingerprint](https://user-images.githubusercontent.com/69476014/89810453-001ef580-db35-11ea-915c-79a589b9df8f.png)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_242-8u242-b08-1~deb9u1-b08",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_242",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.242-b08",
    "os.name": "Linux",
    "os.version": "4.19.112+",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.25-google-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.2",
      "date": "2020-04-10",
      "branch": "release-0.35.x",
      "hash": "f3b2857"
    },
    "settings": {
      "report-timezone": "Europe/London"
    }
  }
}

**Severity**
Very severe, annoying and blocking.
When questions work separately but dashboards not - very annoying.
Final users just can't get the data they need.

**Comment by flamber** [comment] 2020-08-10 17:37
@ArtmanMichael19 There has been a lot of changes to fingerprinting in later versions, 0.36.3, so try one of those. Remember to backup before upgrading.

**Comment by flamber** [comment] 2020-08-11 11:56
Closing, since there's not enough details to reproduce. Please try latest release, 0.36.3, and if you're still having problems, then please provide steps to reproduce.

**Closed by flamber** 2020-08-11 11:56 UTC
Labels: .Needs Triage, Type:Bug
