### ISSUE TITLE
/api/dashboard/:id/params/:param-key/values seems very slow

### ISSUE THREAD

**Issue by FranzBusch** [metabase/metabase#15195] opened 2021-03-17 12:47 UTC
**Describe the bug**
The filters in my dashboard load very slowly compared to the rest of the data. When looking into the console logs I can see a very long duration for the calls to get the values. I am using the [Metabase Athena Driver](https://github.com/dacort/metabase-athena-driver)

This even applies to boolean fields where the input is known by the model aka (true/false)

**Logs**
```
[2f6edc35-d695-4f6d-9e37-2f9171362b71] 2021-03-17T13:40:08+01:00 DEBUG metabase.server.middleware.log GET /api/dashboard/7/params/fbf1f4d3/values 200 11.5 s (15 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (3 idle, 0 queued) (111 total active threads) Queries in flight: 0 (0 queued)
[2f6edc35-d695-4f6d-9e37-2f9171362b71] 2021-03-17T13:40:22+01:00 DEBUG metabase.server.middleware.log GET /api/dashboard/7/params/fbf1f4d3/values 200 11.5 s (15 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (3 idle, 0 queued) (110 total active threads) Queries in flight: 0 (0 queued)
[2f6edc35-d695-4f6d-9e37-2f9171362b71] 2021-03-17T13:42:43+01:00 DEBUG metabase.server.middleware.log GET /api/dashboard/7/params/12cb703d/values 200 11.5 s (17 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (3 idle, 0 queued) (107 total active threads) Queries in flight: 0 (0 queued)
[2f6edc35-d695-4f6d-9e37-2f9171362b71] 2021-03-17T13:43:02+01:00 DEBUG metabase.server.middleware.log GET /api/dashboard/7/params/fbf1f4d3/values 200 11.4 s (15 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (3 idle, 0 queued) (107 total active threads) Queries in flight: 0 (0 queued)
```

**To Reproduce**
1. Connect Athena database
2. Use a filter in the dashboard
3. See long loading time

**Expected behavior**
I expect the filter dropdown to be fast and responsive using cached values.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-us",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "4.14.214-160.339.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "athena",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.1 (Debian 13.1-1.pgdg100+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-03-03",
      "tag": "v0.38.1",
      "branch": "release-x.38.x",
      "hash": "79ef63a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
It is rather annoying that this is so slow and users won't understand why there are no values.

**Comment by flamber** [comment] 2021-03-17 13:44
Duplicate of #13832

**Closed by flamber** 2021-03-17 13:44 UTC
Labels: .Needs Triage, Type:Bug
