### ISSUE TITLE
The download results report an invalid time zone setting

### ISSUE THREAD

**Issue by caochangshan** [metabase/metabase#13800] opened 2020-11-16 03:43 UTC
**Describe the bug**
The download results report an invalid time zone setting.

**versions**
v0.37.1

**Comment by flamber** [comment] 2020-11-16 09:33
Duplicate of #13677

**Closed by flamber** 2020-11-16 09:33 UTC

**Comment by caochangshan** [comment] 2020-11-19 01:52
The version 0.36.6 works fine.
When will it be fixed?
