### ISSUE TITLE
Unable to add text dashboard filter to native question

### ISSUE THREAD

**Issue by pranayat** [metabase/metabase#30104] opened 2023-04-14 09:28 UTC
**Describe the bug**
Main issue - I'm trying to add a 'text' filter to my dashboard so I can connect it to a native mongoDB question. I see the following text in edit mode - "Add a string variable to this question to connect it to a dashboard filter.".
I already have a string variable in this question and I'm not sure what else is needed.

Secondary issues -
a. Furthermore, the usage of the different kinds of text filters for native queries is unclear. If I have a variable in my native query, the "is, is not, contains etc." filter variations have no meaning. I just want the value in the filter to be substituted in my variable.
b. The only type of text filter I am able to add to the native question is the 'Is' type. This always seems to substitute the variable as an array of strings, even when 'A single value' option is selected, causing my mongodb query to fail. I can create a separate ticket for this if this is not intended behaviour.

**To Reproduce**
Create a native MongoDB query as below
```
[
    {
          "$match": {
            "name": {
              "$regex": {{meal_name}},
              "$options": "i"
            }
          }
    },
  {
    "$project": {
      "_id": "$_id",
      "name": "$name",
      "price": "$price",
      "order": "$order",
      "restaurantId": "$restaurantId",
      "category": "$category",
      "description": "$description",
      "menuCardId": "$menuCardId",
      "old_id": "$old_id",
      "old_restaurantId": "$old_restaurantId",
      "old_menuCardId": "$old_menuCardId",
      "__v": "$__v",
      "days": "$days",
      "updatedAt": "$updatedAt",
      "createdAt": "$createdAt"
    }
  },
  { "$project" : { "term_array" : { "$split": ["$description", " ",] } } },
{ "$unwind" : "$term_array" },
{ "$project" : { "term_array" : { "$split": [{"$toLower": "$term_array"}, ",",] } } },
{ "$unwind" : "$term_array" },
{ "$group" : { "_id":  "$term_array" , "total" : { "$sum" : 1 } } },
{ "$sort" : { "total" : -1 } },
{
    "$match": {
       "_id": {
        "$nin": ["","+","/","-","|","&","0","1","2"]
        }
    }
},
{
    "$project": {
        "_id": true,
        "total": true
    }
},
  {
    "$limit": 1048575
  }
]
```

Then add a text filter to the dashboard to connect to {{meal_name}}

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/6952713/232002924-bd9c7698-67ee-4ad3-8a5f-0a1ac43f039a.png)

**Information about your Metabase Installation:**
v0.46.1
Browser - Google Chrome Version 112.0.5615.49 (Official Build) (arm64)

**Severity**
Unable to set a text filter

**Comment by paoliniluis** [comment] 2023-04-15 16:31
hi, my mongodb skills are a little rusty, if you add the match with the param at the bottom, that changes the query right? I'm guessing this is a nested question?

**Comment by pranayat** [comment] 2023-04-20 10:40
This is a mongodb aggregation pipeline query. The first  $match is just the first stage in the pipeline and is doing a regex match.

**Comment by kamilmielnik** [comment] 2023-07-06 09:39
It looks like a backend issue. Reassigning.

----

The error coming from backend POST `/api/card/:id/query`:

```
Command failed with error 2 (BadValue): '$regex has to be a string' on server localhost:27004. The full response is {"ok": 0.0, "errmsg": "$regex has to be a string", "code": 2, "codeName": "BadValue"}
```

This happens with any "Contains" filter - it will cause `$regex` to be used in Mongo query.
The important fragment of Mongo query to reproduce this:

```
[
  {
    "$match": {
      "name": {
        "$regex": {{name}}
      }
    }
  },
  /* ... */
]
```

----

Note: exact string matching works this way without any issues:
```
[
  {
    "$match": {
      "name": {{name}}
    }
  },
  /* ... */
```

**Comment by tsmacdonald** [comment] 2023-07-06 13:04
Looks like a QP issue; reassigning

**Comment by lbrdnk** [comment] 2023-10-11 22:21
@pranayat, please see [this comment](https://github.com/metabase/metabase/issues/30136#issuecomment-1669332876) and linked issue with its fix. PR added capability of using _is filter_ as text variable also for the mongo, which solves the main issue you are describing. If you would be interested in having variables in dashboards, plase file a feature request.

**Closed by lbrdnk** 2023-10-11 22:21 UTC
Labels: Type:Bug, Priority:P2, Database/Mongo, .Backend, .Team/QueryProcessor :hammer_and_wrench:
