### ISSUE TITLE
Filtering a saved question by date using the Query Builder fails under Postgresql

### ISSUE THREAD

**Issue by jeffreyhorner** [metabase/metabase#5908] opened 2017-09-06 19:05 UTC
Google Chrome 60.0.3112.113 (Official Build) (64-bit) linux
Client OS: Ubuntu 16.04.3 LTS
- Database: Postgres 9.5.6
- Metabase version: v0.26.0-snapshot
- Metabase hosting environment: Ubuntu 16.04.2 LTS
- Metabase internal database: Postgres 9.5.6

To reproduce:

1. Create a SQL question with this query and save:
  select to_date('20170101','YYYYMMDD') as date;

2. Attempt to create a Custom question with the query builder using the question from step 1 as the Data source, then add a Filter on the Date field.

Result:
![image](https://user-images.githubusercontent.com/306214/30129669-49c9d0a2-930c-11e7-93e4-49a98433ab76.png)

ERROR: operator does not exist: date = character varying Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts. Position: 201

**Comment by jeffreyhorner** [comment] 2017-09-07 13:48
This is a duplicate of https://github.com/metabase/metabase/issues/5893
but the one I wrote seems clearer.

**Comment by flamber** [comment] 2019-02-16 21:50
Hi @jeffreyhorner 
I cannot reproduce your problem in 0.31.2 with Postgres 11.1 - can you please try again with the newer version of Metabase?

**Comment by flamber** [comment] 2020-03-02 18:46
Closing issue because of no reply and I cannot reproduce on 0.34.3

**Closed by flamber** 2020-03-02 18:46 UTC
Labels: Priority:P2, Querying/Nested Queries, Type:Bug
