### ISSUE TITLE
Enable functions that return boolean values as custom column

### ISSUE THREAD

**Issue by carstenkadmos** [metabase/metabase#28740] opened 2023-02-28 15:29 UTC
**Is your feature request related to a problem? Please describe.**
When creating a custom column that returns a boolean value the following error shows.
<img width="391" alt="Screenshot 2023-02-28 at 16 26 53" src="https://user-images.githubusercontent.com/113892067/221899820-ec81c27a-a0ca-4360-a304-aa2d6afe03a0.png">

**Describe the solution you'd like**
The column should return the boolean value.

**How important is this feature to you?**
Quality of life improvement

**Comment by paoliniluis** [comment] 2023-02-28 15:41
Hi! this is a duplicate of https://github.com/metabase/metabase/issues/15922

**Closed by paoliniluis** 2023-02-28 15:41 UTC
Labels: Type:New Feature, .Needs Triage
