### ISSUE TITLE
Personal subcollections are not displayed on side bar

### ISSUE THREAD

**Issue by AndreLuizRego** [metabase/metabase#22625] opened 2022-05-11 11:43 UTC
Subcollections that are under other user's main collection are not displayed on side bar (I´m the admin).

![Personal_Collection](https://user-images.githubusercontent.com/56892990/167840877-b47d46b7-2bdf-4534-a6a0-c3d23f8ce1d2.png)

The only way to see if there are subcollections under a user collection is to save a question as a new one, select the user´s main collection and then you can see other subcollections:

![Personal_Collection_Subcollections](https://user-images.githubusercontent.com/56892990/167841182-89eb215f-eef2-43e8-b0dd-fd54dc6b711e.png)

Not sure if we can call it a bug, but certainly it makes very difficult to curate collections.

I´m using Metabase 0.43 but had notice this behavior on previous versions too.

**Comment by flamber** [comment] 2022-05-11 11:45
Duplicate of #15339

**Closed by flamber** 2022-05-11 11:45 UTC
Labels: Type:Bug, .Needs Triage
