### ISSUE TITLE
Dashboard editing can get into confused states

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5533] opened 2017-07-20 22:48 UTC
I added a card to a dashboard, tried to add a filter, decided against it and hit cancel.

After that, the edit state of the dashboard was a bit weird. See below.

![screen shot 2017-07-20 at 3 47 13 pm](https://user-images.githubusercontent.com/107439/28442015-cef0fad2-6d62-11e7-98cf-e1f90b008edd.png)

**Comment by salsakran** [comment] 2017-07-20 22:49
![screen shot 2017-07-20 at 3 48 42 pm](https://user-images.githubusercontent.com/107439/28442040-f10f8c0a-6d62-11e7-806e-fc784c1f0f42.png)

**Comment by mazameli** [comment] 2017-07-24 21:37
I've gotten into some similar states before, but I haven't figured out a reliable way to reproduce them. Included these images here just for context. This images were taken of a local build of master on 6/26/2017.

**Overlapping cards**

<img width="959" alt="screen shot 2017-06-26 at 3 27 11 pm" src="https://user-images.githubusercontent.com/2223916/28545808-3f247b72-707d-11e7-9d8d-b5b604c669fd.png">

**Overlapping card with JS console output, plus tiny card**

<img width="959" alt="screen shot 2017-06-26 at 3 27 23 pm" src="https://user-images.githubusercontent.com/2223916/28545810-44b7feec-707d-11e7-8614-124a08188176.png">

**Tiny overlapping card, no longer in editing state:**

![screen shot 2017-06-26 at 3 28 30 pm](https://user-images.githubusercontent.com/2223916/28545818-498f9ca4-707d-11e7-97c2-464d865d3d8e.png)

**These dashboard card types normally aren't allowed to be this small:**

![screen shot 2017-06-26 at 3 33 08 pm](https://user-images.githubusercontent.com/2223916/28545854-73c37e0a-707d-11e7-96df-d2c72f22034c.png)

**Comment by flamber** [comment] 2020-05-25 19:48
Some of this was fixed in 0.32.10 (#10206) and some of it before. I cannot reproduce on 0.35.3

**Closed by flamber** 2020-05-25 19:48 UTC
Labels: Priority:P3, Reporting/Dashboards, Type:Bug
