### ISSUE TITLE
Cannot see the collection content on mobile browser

### ISSUE THREAD

**Issue by xiaofanr** [metabase/metabase#16767] opened 2021-06-25 01:41 UTC
**Describe the bug**
Sidebar in the collection page is not responsive. Its width is fixed.

**To Reproduce**
1. Go to 'Analytics'
2. See error

**Expected behavior**
The sidebar is reponsive.

**Screenshots**
![image](https://user-images.githubusercontent.com/5674208/123355957-4b999100-d599-11eb-9738-7d489ef7cc8b.png)

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 91.0.4472.101
- Your operating system: Android 10
- Metabase version: v0.39.4
- Metabase hosting environment: Docker

**Severity**
Annoying

**Comment by flamber** [comment] 2021-06-25 08:50
Duplicate of #15006

**Closed by flamber** 2021-06-25 08:50 UTC
Labels: .Needs Triage, Type:Bug
