### ISSUE TITLE
Ability to send Quarterly Email-Slack Pulse

### ISSUE THREAD

**Issue by zaiddabaeen** [metabase/metabase#7161] opened 2018-03-20 14:26 UTC
Since most organisations run on quarterly reports, can we have Metabase sending pulses over quarterly basis?

If you think this is a good idea, I'd be willing to contribute this feature to metabase.

**Comment by flamber** [comment] 2019-02-18 23:56
Duplicate of #3237

**Comment by mbvictoria** [comment] 2019-06-19 20:24
Closing since it's a duplication of #3237

**Closed by mbvictoria** 2019-06-19 20:24 UTC
Labels: Proposal, Pulses
