### ISSUE TITLE
Can't do division on cumulative sums

### ISSUE THREAD

**Issue by akajb84** [metabase/metabase#4348] opened 2017-02-09 22:59 UTC
BUG

Mac App Version 0.22.2.1
Database is MongoDB
OS is OS X 10.11.6

I am trying to run a query where I get a cumulative sum and do a division on it. 

I've tried putting the / 60000 within the cumulative sum and also outside (see attached images). 

![screen shot 2017-02-09 at 2 52 15 pm](https://cloud.githubusercontent.com/assets/3442754/22806735/56ba70ce-eed8-11e6-966e-e6abb282530a.jpeg)
![screen shot 2017-02-09 at 2 51 34 pm](https://cloud.githubusercontent.com/assets/3442754/22806734/56b4d394-eed8-11e6-8648-b85a9b535085.jpeg)

**Comment by camsaul** [comment] 2017-02-09 23:00
Duplicate of #4001

**Closed by camsaul** 2017-02-09 23:00 UTC
