### ISSUE TITLE
Can't combine charts in dashboard (can't add multiple series)

### ISSUE THREAD

**Issue by BertrandToulas** [metabase/metabase#26510] opened 2022-11-15 15:23 UTC
**Describe the bug**
While in edit mode on a dashboard, clicking the "Add series" button on a card will just refresh the page instead of asking the user to specify a series to add.

**Logs**

Metabase server log:

```
[e3b5baaa-ef35-46e3-bd1d-510c2cd00afc] 2022-11-15T15:25:15+01:00 DEBUG metabase.server.middleware.log GET /api/dashboard/153 200 32.5 ms (10 DB calls) App DB connections: 1/15 Jetty threads: 3/50 (4 idle, 0 queued) (132 total active threads) Queries in flight: 0 (0 queued)
[e3b5baaa-ef35-46e3-bd1d-510c2cd00afc] 2022-11-15T15:25:15+01:00 DEBUG metabase.server.middleware.log POST /api/dashboard/153/dashcard/1683/card/1259/query 202 [ASYNC: completed] 88.0 ms (21 DB calls) App DB connections: 2/15 Jetty threads: 2/50 (4 idle, 0 queued) (132 total active threads) Queries in flight: 0 (0 queued); h2 DB 79 connections: 0/1 (0 threads blocked)
```

Javascript console log:
```
TypeError: a is undefined
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    c https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    g https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    g https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    useMemo https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    useMemo https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    je https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    Qo https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Ys https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Fs https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    $s https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    xa https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    yl https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    ml https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    ll https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Zi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    unstable_runWithPriority https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Vi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Zi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Ki https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    N https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Zt https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
[vendor.bundle.js:2:3961596](https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd)
    oa https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    callback https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    vo https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    ua https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Ml https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    unstable_runWithPriority https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Vi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    wl https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    ll https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Zi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    unstable_runWithPriority https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Vi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Zi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Ki https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    N https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Zt https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
Warning: can't clean query without metadata! [app-main.bundle.js:2:623425](https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991)
Error getting setting graph.x_axis._is_timeseries TypeError: undefined has no properties
    getDefault https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    ft https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    st https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    v https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    Lo https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Hs https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    xa https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    yl https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    ml https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    ll https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Zi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    unstable_runWithPriority https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Vi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Zi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Ki https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    rl https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    enqueueSetState https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    setState https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    h https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    c https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    r https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    r https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    r https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
[app-main.bundle.js:2:4818135](https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991)
Error getting setting graph.x_axis._is_numeric TypeError: undefined has no properties
    getDefault https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    ft https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    st https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    v https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    Lo https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Hs https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    xa https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    yl https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    ml https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    ll https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Zi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    unstable_runWithPriority https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Vi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Zi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Ki https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    rl https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    enqueueSetState https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    setState https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    h https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    c https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    r https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    r https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    r https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
[app-main.bundle.js:2:4818135](https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991)
Error getting setting graph.x_axis._is_histogram TypeError: undefined has no properties
    getDefault https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    ft https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    st https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    v https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    Lo https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Hs https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    xa https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    yl https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    ml https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    ll https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Zi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    unstable_runWithPriority https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Vi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Zi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Ki https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    rl https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    enqueueSetState https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    setState https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    h https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    c https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    r https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    r https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    r https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
[app-main.bundle.js:2:4818135](https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991)
Error getting setting graph.x_axis.title_text TypeError: undefined has no properties
    getDefault https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    ft https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    st https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    v https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    Lo https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Hs https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    xa https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    yl https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    ml https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    ll https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Zi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    unstable_runWithPriority https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Vi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Zi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Ki https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    rl https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    enqueueSetState https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    setState https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    h https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    c https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    r https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    r https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    r https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
[app-main.bundle.js:2:4818135](https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991)
Error getting setting graph.y_axis.title_text TypeError: undefined has no properties
    r https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    getDefault https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    ft https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    st https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    v https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    value https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    Lo https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Hs https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    xa https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    yl https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    ml https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    ll https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Zi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    unstable_runWithPriority https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Vi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Zi https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    Ki https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    rl https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    enqueueSetState https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    setState https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    h https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    c https://b-i.moodwork.com/app/dist/vendor.bundle.js?122d41bbf7a022e2b7cd:2
    r https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    r https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
    r https://b-i.moodwork.com/app/dist/app-main.bundle.js?cce3d02cccbdc5632991:2
```

**To Reproduce**
1. Go to/create a dashboard;
2. Add any question that can normally be combined with another series;
3. Enter edit mode on the dashboard, then hover over the question and click the "Add series" icon.

At this point, either of the following will happen:
- the page will refresh almost instantly;
- a pop-in window will start to load, then the page will refresh after a couple seconds.

**Expected behavior**
Instead of refreshing, the page should ask the user what series they want to add.

**Screenshots**
For example, here's the dashboard I made, using the Sample Database:

![image](https://user-images.githubusercontent.com/71009735/201942365-6fcdfe44-4591-4dd5-92d2-75503dba9a9c.png)

and the question:

![image](https://user-images.githubusercontent.com/71009735/201942489-74c5ab44-1b67-4fb9-a3f7-c3f0e31d446d.png)

**Information about your Metabase Installation:**
- Browsers tested: Firefox 106.0.5 , Brave v1.45.123
- Your operating system: Windows 11 Pro 22H2, OS build 22621.819
- Databases: BigQuery, Postgres, H2
- Metabase version: 0.44.6

**Severity**
Being able to combine charts makes some of the more complex dashboards we create much more understandable and readable. I can always make separate charts, but it's not optimal.

**Comment by paoliniluis** [comment] 2022-11-15 16:32
Hi Bertrand, another customer reported this regression but I'm not able to reproduce it with the steps you detail here. Is there something missing?

**Comment by BertrandToulas** [comment] 2022-11-15 17:07
Hi Luis, I'm not sure to be honest. Those are all the steps that I've taken. All I can tell you on top of that is that:
- I've disabled/turned off pretty much every browser feature I can think of that could potentially create this issue (e.g. adblockers, scriptblockers).
- I used to be able to create multi-series charts, though I don't remember when the last time I used them was. Most likely before 0.44 though.

Maybe you'll find a clue in the logs? Is there any other technical detail that you want me to provide?

**Comment by BertrandToulas** [comment] 2022-11-16 22:17
By instance, do you mean our entire Metabase installation? How many questions we've created in total? I'll have to check later, but probably upwards of 100. Will let you know.

**Comment by BertrandToulas** [comment] 2022-11-17 10:09
I've had a closer look. We have more than 700 questions in our Metabase instance, though I'd say only about 100 of them are used in dashboards. Only a few of those questions are used in combined charts. We have roughly 20 dashboards, though only about half of those get used with any degree of frequency, if at all. And only by a handful people at the most. However, some dashboards tend to be quite big - think 15-30 questions each, with a mix of SQL and editor-based questions and some dashboard filters.

However, for the purposes of this issue, I was able to reproduce the bug consistently like in the example I gave above, i.e. with a completely new dashboard made up of one single question using the sample database, with no dashboard filters. The dashboard and the question themselves load fast.

**Comment by BertrandToulas** [comment] 2022-11-17 13:07
Hi @Tony-metabase , gotcha, I'll ask my admin and report back to you. Do you think the culprit could be any question, or would it most likely be question that is used in a combined chart somewhere, or maybe the combined chart itself?

**Comment by Tony-metabase** [comment] 2022-11-17 13:23
No I don't think it is related to the chart/combined chart. Since the issue is popping when you press the `Add Series` and usually a prompt loads showing you the available questions. With some of the questions metadata already loaded by metabase since in some you get a message like this one:

![image](https://user-images.githubusercontent.com/110378427/202457679-0138ab41-e1d5-4b60-85f2-2ff35ef252ff.png)

The assumption is that when it tries to load some metadata for a particular question it crashes or reloads in your case. Again this is just an assumption since at present I cannot replicate

**Comment by BertrandToulas** [comment] 2022-11-17 13:26
I see! I'll investigate whenever possible and let you know my findings. Thank you.

**Comment by paoliniluis** [comment] 2022-11-17 14:49
This is due to a corrupted card, I just reproduced by corrupting a card in the DB. It's a duplicate of https://github.com/metabase/metabase/issues/15222

**Closed by paoliniluis** 2022-11-17 14:49 UTC
Labels: Type:Bug, Priority:P1, .Unable to Reproduce, .Frontend
