### ISSUE TITLE
"Can't copy data from rows" on Safari - Mac

### ISSUE THREAD

**Issue by mertsalik** [metabase/metabase#7242] opened 2018-03-30 07:28 UTC
Cant copy selected data from result table to clipboard. ( does not work with keyboard or mouse, it works on Chrome )

Safari - Version 11.0.3 (12604.5.6.1.1)
MacOs - Sierra Version 10.12.6
Metabase - v0.27.1
Database - Postgresql

![screen shot 2018-03-30 at 10 21 41](https://user-images.githubusercontent.com/652489/38128841-fcca8ad6-3404-11e8-860f-f3d67011c414.png)

**Comment by alexjv89** [comment] 2018-08-09 04:34
experiencing the same issue here

**Comment by jornh** [comment] 2018-08-09 05:10
Hey @alexjv89, one way the team prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍 comments, please just upvote by adding a reaction to the issue description.

**Comment by flamber** [comment] 2019-02-22 07:01
This looks like a duplicate of #6247

**Comment by camsaul** [comment] 2019-02-22 19:23
Duplicate of #6247

**Closed by camsaul** 2019-02-22 19:23 UTC
Labels: Browser/Safari, Bug, OS/Mac, Priority/P3, UX
