### ISSUE TITLE
Chart tooltip not showing all series in breakout

### ISSUE THREAD

**Issue by XtremeAnalytics** [metabase/metabase#34901] opened 2023-10-20 12:58 UTC
### Tooltip Not Showing Top Series in Stacked Line Chart

I created a stacked line chart using a date variable, a categorical variable and numeric variable (see image attached).

When I hover over a point on the top line of the chart, I get the tooltip, that only shows info about the bottom line, disregarding the top line.

![image](https://github.com/metabase/metabase/assets/148552660/18d5193f-9c47-4add-9d28-b9208074b0ff)

I have tried this with other data, and was able to reproduce the issue. As you can see, the top line is ignored in the tooltip, whereas the summary for the rest is okay.

![image](https://github.com/metabase/metabase/assets/148552660/434a9045-4b9a-494e-83a5-8494c1c68ecf)

### To Reproduce

I have tried to reproduce this on the Sample Database, but the issue doesn't happen there.

The underlying data structure of both charts in sample database & my database is identical: [date,text,int], yet however the chart behaviour is different in my case.

![image](https://github.com/metabase/metabase/assets/148552660/cf329068-b096-463b-9ff5-d8f1621b86ca)

### Expected behavior

The tooltip should should all values in the series. 

### Logs

[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:20:56+02:00 DEBUG metabase.server.middleware.log GET /api/activity/recent_views 200 27.5 ms (7 DB calls) App DB connections: 1/10 Jetty threads: 5/50 (1 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:20:56+02:00 DEBUG metabase.server.middleware.log GET /api/activity/popular_items 200 38.9 ms (10 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (1 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:21:00+02:00 DEBUG metabase.server.middleware.log GET /api/database/7 200 7.4 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (1 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:21:00+02:00 DEBUG metabase.server.middleware.log GET /api/database/7/schema/data_ramp 200 12.9 ms (4 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (1 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:21:02+02:00 DEBUG metabase.server.middleware.log GET /api/table/22/query_metadata 200 22.6 ms (9 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (1 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:21:02+02:00 WARN metabase.driver.sql.query-processor.deprecated Warning: Driver :clickhouse is using Honey SQL 1. This method was deprecated in 0.46.0 and will be removed in a future release.
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:21:02+02:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 67.3 ms (21 DB calls) App DB connections: 0/10 Jetty threads: 3/50 (1 idle, 0 queued) (73 total active threads) Queries in flight: 0 (0 queued); clickhouse DB 7 connections: 0/1 (0 threads blocked)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:22:23+02:00 DEBUG metabase.server.middleware.log GET /api/database 200 25.3 ms (10 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (3 idle, 0 queued) (69 total active threads) Queries in flight: 0 (0 queued)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:22:26+02:00 DEBUG metabase.server.middleware.log GET /api/database/7/schema/data_ramp 200 7.7 ms (4 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (3 idle, 0 queued) (71 total active threads) Queries in flight: 0 (0 queued)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:23:06+02:00 WARN metabase.driver.sql.query-processor.deprecated Warning: Driver :clickhouse is using Honey SQL 1. This method was deprecated in 0.46.0 and will be removed in a future release.
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:23:06+02:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 43.2 ms (11 DB calls) App DB connections: 0/10 Jetty threads: 3/50 (3 idle, 0 queued) (72 total active threads) Queries in flight: 1 (0 queued); clickhouse DB 7 connections: 0/1 (0 threads blocked)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:27:27+02:00 DEBUG metabase.server.middleware.log POST /api/card 200 99.0 ms (17 DB calls) App DB connections: 1/10 Jetty threads: 4/50 (3 idle, 0 queued) (70 total active threads) Queries in flight: 0 (0 queued)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:27:28+02:00 DEBUG metabase.server.middleware.log GET /api/search 200 6.4 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (3 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:27:28+02:00 DEBUG metabase.server.middleware.log GET /api/database 200 6.4 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (2 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:27:28+02:00 DEBUG metabase.server.middleware.log GET /api/card/12 200 27.7 ms (10 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (2 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:27:29+02:00 DEBUG metabase.server.middleware.log GET /api/activity/most_recently_viewed_dashboard 200 11.9 ms (4 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (2 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:27:29+02:00 DEBUG metabase.server.middleware.log GET /api/collection/root/items 200 28.7 ms (4 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (2 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:27:58+02:00 DEBUG metabase.server.middleware.log POST /api/dashboard 200 26.5 ms (7 DB calls) App DB connections: 1/10 Jetty threads: 4/50 (2 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:27:58+02:00 DEBUG metabase.server.middleware.log GET /api/search 200 5.6 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (2 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:27:58+02:00 DEBUG metabase.server.middleware.log GET /api/dashboard/3 200 18.8 ms (7 DB calls) App DB connections: 1/10 Jetty threads: 4/50 (2 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:27:58+02:00 DEBUG metabase.server.middleware.log GET /api/pulse/form_input 200 1.5 ms (0 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (2 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:27:59+02:00 WARN metabase.driver.sql.query-processor.deprecated Warning: Driver :clickhouse is using Honey SQL 1. This method was deprecated in 0.46.0 and will be removed in a future release.
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:27:59+02:00 DEBUG metabase.server.middleware.log POST /api/card/12/query 202 [ASYNC: completed] 77.6 ms (17 DB calls) App DB connections: 0/10 Jetty threads: 3/50 (2 idle, 0 queued) (73 total active threads) Queries in flight: 0 (0 queued); clickhouse DB 7 connections: 0/1 (0 threads blocked)
[ecab7a1d-5574-4518-b2b7-8206ee3e32b2] 2023-10-20T13:28:00+02:00 INFO metabase.task.sync-databases Starting sync task for Database 1.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.15.0-83-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "clickhouse",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.4 (Debian 15.4-2.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-10-11",
      "tag": "v0.47.4",
      "branch": "?",
      "hash": "c96dc65"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

It's annoying

**Comment by alxnddr** [comment] 2024-05-17 17:48
I could not reproduce this. At the same time, we changed 100% of the code that was responsible for selecting data for the tooltip so it should be fixed by https://github.com/metabase/metabase/pull/41395

**Closed by alxnddr** 2024-05-17 17:48 UTC
Labels: Type:Bug, Visualization/Charts, .echarts-scope, .Team/DashViz
