### ISSUE TITLE
Kylin OLAP Support

### ISSUE THREAD

**Issue by hzwuxk** [metabase/metabase#7621] opened 2018-05-11 00:57 UTC
### Database support

Is there a way to connect metabase to Apache Kylin ?

**Comment by jornh** [comment] 2018-05-11 05:46
Duplicate of #5672

Please close this issue and add your 👍 vote on #5672

**Comment by salsakran** [comment] 2018-06-24 23:42
as @jornh mentioned, this is a dupe

**Closed by salsakran** 2018-06-24 23:42 UTC
