### ISSUE TITLE
Redirect after login is broken again

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14781] opened 2021-02-12 03:16 UTC
Steps to repro:

1. Be logged out
2. Click a link like https://metabase.example.com/question/1915
3. You are redirected to login page
4. Log in
5. You are taken to https://metabase.example.com/, not the link you originally clicked!

See also: #2971, #4430, #6317, https://github.com/metabase/metabase/issues?q=is%3Aissue+login+redirect+is%3Aclosed+author%3Acamsaul

**Comment by flamber** [comment] 2021-02-12 09:33
I cannot reproduce - related to #14436 I guess

**Comment by flamber** [comment] 2021-06-16 20:29
Closing this in favor of #16216, which has been reproduced, fixed and with a test.

**Closed by flamber** 2021-06-16 20:29 UTC
Labels: .Frontend, Administration/Auth, Priority:P3, Type:Bug
