### ISSUE TITLE
A question opened from a dashboard may look broken

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#26849] opened 2022-12-01 01:36 UTC
**Describe the bug**
A question opened from certain dashboards may look broken. We don't have clear repro steps, the issue can be reproduced in our instance, the [slack thread](https://metaboat.slack.com/archives/C505ZNNH4/p1669769452223819) contains all the details.

**To Reproduce**
Check the [slack thread](https://metaboat.slack.com/archives/C505ZNNH4/p1669769452223819)

**Comment by flamber** [comment] 2022-12-04 12:21
So this is caused by the question referencing a Model, which has lost it's Metadata. Used to be much worse with #22517, which is likely also what caused the problem initially for the specific question. And the problem only happens on dashboard click-through, since we're sending queryhash to be able to apply permissions (and some steps to avoid #13595).

Reproduce:
1. SQL > Sample > `select * from products` - save and turn into a Model
2. In the Model's metadata, map columns to fields (just Category is enough) - save
3. Question > Models > (the model) - filter Category by something, summarize Count and group by Category - save question and add to dashboard
4. Edit the Model's metadata, remove the mapping on Category column - save
5. On dashboard, click question title - will show "broken" question and the Notebook will not have the filter section or group-by section anymore.

**Comment by WiNloSt** [comment] 2023-08-22 14:48
The problem doesn't occur with the question mentioned in [slack thread](https://metaboat.slack.com/archives/C505ZNNH4/p1669769452223819) anymore.

I wound back to commit 707b38d8a72e65f80c6c1da59aa7f356f8f49462 (Nov 29) which was before the date this issue was created. And still couldn't reproduce using the steps above.

Without a reliable repro steps I won't be able to create an E2E to cover this issue.

**Comment by NevRA** [comment] 2023-08-22 15:35
We will close it because we can't reproduce it. Please, feel free to re-open.

**Closed by NevRA** 2023-08-22 15:35 UTC
Labels: Type:Bug, Priority:P3, Reporting/Dashboards, .Unable to Reproduce, .Correctness, Querying/Models, .Team/42 :milky_way:, .FixScope42

**Comment by WiNloSt** [comment] 2023-08-28 07:12
Since there are no reliable repro steps I'd put this in milestone 48 which is the most recent milestone.
