### ISSUE TITLE
Line/Area graphs don't reflect tabular results

### ISSUE THREAD

**Issue by brnt** [metabase/metabase#6536] opened 2017-12-05 23:42 UTC
Browser: Chrome 62.0.3202.94 (Official Build) (64-bit)
Operating System: OSX 10.13.1
Database: PostgreSQL
Metabase Version: 0.27.1
Hosting Env: Heroku
Internal DB: PostgreSQL

Sample query:

```
SELECT to_char('2017-12-01'::date AT TIME ZONE 'UTC', 'Mon YYYY') AS "d1",
    123.56 AS "Revenue",
    to_char('2017-12-01'::date AT TIME ZONE 'UTC', 'YYMM') AS "d2"
    
UNION

SELECT to_char('2017-11-01'::date AT TIME ZONE 'UTC', 'Mon YYYY') AS "d1",
    234.67 AS "Revenue",
    to_char('2017-11-01'::date AT TIME ZONE 'UTC', 'YYMM') AS "d2"

ORDER BY d2
```
The query is specific to PostgreSQL, but doesn't require any underlying DB schema to work. The output in tabular form is as expected:

<img width="296" alt="screen shot 2017-12-05 at 4 37 04 pm" src="https://user-images.githubusercontent.com/1072638/33636714-a9d7935c-d9da-11e7-824a-3dc144920b35.png">

But switching the visualization to Line  or Area Graph breaks the column alignment (see the column d2 mismatch):

<img width="530" alt="screen shot 2017-12-05 at 4 37 27 pm" src="https://user-images.githubusercontent.com/1072638/33636720-b0528f48-d9da-11e7-89e3-b713c462304c.png">

It's worth noting that I've forced both d1 and d2 to types other than native date/time/stamp types to ensure that there's no funky parsing and then skewing by TZ or other artifact.

**Comment by camsaul** [comment] 2018-01-15 19:31
@salsakran I think this is a duplicate of #6401 which I fixed early in the 0.28.0 cycle

**Closed** 2018-01-15 19:32 UTC
Labels: Bug, Duplicate, Priority/P1, Visualization
