### ISSUE TITLE
Bigquery - Error with simple and custom question

### ISSUE THREAD

**Issue by tiagoferrucio** [metabase/metabase#17811] opened 2021-09-08 20:35 UTC
**Describe the bug**
The problem is happing when the dataset name starts with a number, and Metabase is lost when building a query.

For example, the connection from this dataset (1b05f6177063445b8a7d0e6f8e027346) has the error but this other one (abae8b30ac9b11e692000401f8d88101) hasn't.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Add database 
2. Database type is BigQuery
3. Go to Ask a question
4. Simple or Custom question
5. Visualize

**Expected behavior**

**Screenshots**
- Adding database: ![image](https://user-images.githubusercontent.com/38772077/132581362-2131663d-ec36-4820-9472-bc6f22be7ffa.png)
- Simple Question: ![image](https://user-images.githubusercontent.com/38772077/132579722-ba4a0430-f5ff-42d1-8052-affb1a0f4af5.png)
- Custom Question: ![image](https://user-images.githubusercontent.com/38772077/132581480-53f0d194-d1ab-412e-ab7b-9777f156ff74.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: OS
- Your databases: BiqQuery
- Metabase version: 11.12
- Metabase hosting environment: VM Linux
- Metabase internal database: PostgreSQL

**Severity**
This issue is blocked just when clients uses simple or custom questions, if they don't know T-SQL, they don't want to use metabase.

**Additional context**

**Comment by flamber** [comment] 2021-09-08 20:47
Duplicate of #9388

**Closed by flamber** 2021-09-08 20:47 UTC
Labels: Type:Bug, .Needs Triage
