### ISSUE TITLE
Failed to set timezone 'US/Eastern' for mysql database in Metabase

### ISSUE THREAD

**Issue by premsahu73** [metabase/metabase#19088] opened 2021-11-24 18:02 UTC
While running Metabase 0.41.0 source code in our company. We are getting the below error?
Could you please help with this?

11-24 12:01:57 ERROR sql-jdbc.execute :: Failed to set timezone 'US/Eastern' for :mysql database
java.sql.SQLTransientConnectionException: (conn=2577789) Unknown or incorrect time zone: 'US/Eastern'
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:79) ~[metabase.jar:?]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153) ~[metabase.jar:?]
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274) ~[metabase.jar:?]
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:363) ~[metabase.jar:?]
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:501) ~[metabase.jar:?]
	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75) ~[metabase.jar:?]
	at metabase.driver.sql_jdbc.execute$set_time_zone_if_supported_BANG_.invokeStatic(execute.clj:161) [metabase.jar:?]
	at metabase.driver.sql_jdbc.execute$set_time_zone_if_supported_BANG_.invoke(execute.clj:146) [metabase.jar:?]
	at metabase.driver.sql_jdbc.execute$fn__52145.invokeStatic(execute.clj:193) [metabase.jar:?]
	at metabase.driver.sql_jdbc.execute$fn__52145.invoke(execute.clj:188) [metabase.jar:?]
	at clojure.lang.MultiFn.invoke(MultiFn.java:239) [metabase.jar:?]
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:475) [metabase.jar:?]
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:463) [metabase.jar:?]
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:472) [metabase.jar:?]
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:463) [metabase.jar:?]
	at metabase.driver.sql_jdbc$fn__85045.invokeStatic(sql_jdbc.clj:54) [metabase.jar:?]
	at metabase.driver.sql_jdbc$fn__85045.invoke(sql_jdbc.clj:52) [metabase.jar:?]
	at clojure.lang.MultiFn.invoke(MultiFn.java:244) [metabase.jar:?]
	at metabase.query_processor.context$executef.invokeStatic(context.clj:59) [metabase.jar:?]
	at metabase.query_processor.context$executef.invoke(context.clj:48) [metabase.jar:?]
	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:68) [metabase.jar:?]
	at metabase.query_processor.context.default$default_runf.invoke(default.clj:66) [metabase.jar:?]
	at metabase.query_processor.context$runf.invokeStatic(context.clj:45) [metabase.jar:?]
	at metabase.query_processor.context$runf.invoke(context.clj:39) [metabase.jar:?]
	at metabase.query_processor.reducible$pivot.invokeStatic(reducible.clj:34) [metabase.jar:?]
	at metabase.query_processor.reducible$pivot.invoke(reducible.clj:31) [metabase.jar:?]
	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49073.invoke(mbql_to_native.clj:25) [metabase.jar:?]
	at metabase.query_processor.middleware.check_features$check_features$fn__49560.invoke(check_features.clj:39) [metabase.jar:?]
	at metabase.query_processor.middleware.limit$limit$fn__47446.invoke(limit.clj:37) [metabase.jar:?]
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__49934.invoke(cache.clj:204) [metabase.jar:?]
	at metabase.query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__50927.invoke(optimize_temporal_filters.clj:204) [metabase.jar:?]
	at metabase.query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__50971.invoke(validate_temporal_bucketing.clj:50) [metabase.jar:?]
	at metabase.query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__49130.invoke(auto_parse_filter_values.clj:43) [metabase.jar:?]
	at metabase.query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__39232.invoke(wrap_value_literals.clj:161) [metabase.jar:?]
	at metabase.query_processor.middleware.annotate$add_column_info$fn__43663.invoke(annotate.clj:615) [metabase.jar:?]
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__45601.invoke(permissions.clj:108) [metabase.jar:?]
	at metabase.query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__50111.invoke(pre_alias_aggregations.clj:40) [metabase.jar:?]
	at metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__45999.invoke(cumulative_aggregations.clj:60) [metabase.jar:?]
	at metabase.query_processor.middleware.visualization_settings$update_viz_settings$fn__45937.invoke(visualization_settings.clj:63) [metabase.jar:?]
	at metabase.query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47044.invoke(resolve_joined_fields.clj:102) [metabase.jar:?]
	at metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__50697.invoke(resolve_joins.clj:171) [metabase.jar:?]
	at metabase.query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__50233.invoke(add_implicit_joins.clj:190) [metabase.jar:?]
	at metabase.query_processor.middleware.large_int_id$convert_id_to_string$fn__47063.invoke(large_int_id.clj:59) [metabase.jar:?]
	at metabase.query_processor.middleware.format_rows$format_rows$fn__50285.invoke(format_rows.clj:74) [metabase.jar:?]
	at metabase.query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__46435.invoke(add_default_temporal_unit.clj:23) [metabase.jar:?]
	at metabase.query_processor.middleware.desugar$desugar$fn__45910.invoke(desugar.clj:21) [metabase.jar:?]
	at metabase.query_processor.middleware.binning$update_binning_strategy$fn__39132.invoke(binning.clj:229) [metabase.jar:?]
	at metabase.query_processor.middleware.resolve_fields$resolve_fields$fn__45244.invoke(resolve_fields.clj:34) [metabase.jar:?]
	at metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__49485.invoke(add_dimension_projections.clj:314) [metabase.jar:?]
	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__49783.invoke(add_implicit_clauses.clj:147) [metabase.jar:?]
	at metabase.query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__47431.invoke(upgrade_field_literals.clj:40) [metabase.jar:?]
	at metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__46812.invoke(add_source_metadata.clj:123) [metabase.jar:?]
	at metabase.query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__50033.invoke(reconcile_breakout_and_order_by_bucketing.clj:100) [metabase.jar:?]
	at metabase.query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__48382.invoke(auto_bucket_datetimes.clj:147) [metabase.jar:?]
	at metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45225.invoke(resolve_source_table.clj:45) [metabase.jar:?]
	at metabase.query_processor.middleware.parameters$substitute_parameters$fn__48036.invoke(parameters.clj:111) [metabase.jar:?]
	at metabase.query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45298.invoke(resolve_referenced.clj:79) [metabase.jar:?]
	at metabase.query_processor.middleware.expand_macros$expand_macros$fn__51355.invoke(expand_macros.clj:184) [metabase.jar:?]
	at metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__47815.invoke(add_timezone_info.clj:15) [metabase.jar:?]
	at metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__50300.invoke(splice_params_in_response.clj:32) [metabase.jar:?]
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49794$fn__49798.invoke(resolve_database_and_driver.clj:31) [metabase.jar:?]
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:60) [metabase.jar:?]
	at metabase.driver$do_with_driver.invoke(driver.clj:56) [metabase.jar:?]
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49794.invoke(resolve_database_and_driver.clj:25) [metabase.jar:?]
	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45848.invoke(fetch_source_query.clj:274) [metabase.jar:?]
	at metabase.query_processor.middleware.store$initialize_store$fn__46036$fn__46037.invoke(store.clj:11) [metabase.jar:?]
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:44) [metabase.jar:?]
	at metabase.query_processor.store$do_with_store.invoke(store.clj:38) [metabase.jar:?]
	at metabase.query_processor.middleware.store$initialize_store$fn__46036.invoke(store.clj:10) [metabase.jar:?]
	at metabase.query_processor.middleware.validate$validate_query$fn__50083.invoke(validate.clj:10) [metabase.jar:?]
	at metabase.query_processor.middleware.normalize_query$normalize$fn__50090.invoke(normalize_query.clj:22) [metabase.jar:?]
	at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__47761.invoke(add_rows_truncated.clj:35) [metabase.jar:?]
	at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49059.invoke(results_metadata.clj:147) [metabase.jar:?]
	at metabase.query_processor.middleware.constraints$add_default_userland_constraints$fn__47779.invoke(constraints.clj:42) [metabase.jar:?]
	at metabase.query_processor.middleware.process_userland_query$process_userland_query$fn__50069.invoke(process_userland_query.clj:146) [metabase.jar:?]
	at metabase.query_processor.middleware.catch_exceptions$catch_exceptions$fn__50380.invoke(catch_exceptions.clj:169) [metabase.jar:?]
	at metabase.query_processor.reducible$async_qp$qp_STAR___42483$thunk__42484.invoke(reducible.clj:103) [metabase.jar:?]
	at metabase.query_processor.reducible$async_qp$qp_STAR___42483.invoke(reducible.clj:109) [metabase.jar:?]
	at metabase.query_processor.reducible$sync_qp$qp_STAR___42492$fn__42495.invoke(reducible.clj:135) [metabase.jar:?]
	at metabase.query_processor.reducible$sync_qp$qp_STAR___42492.invoke(reducible.clj:134) [metabase.jar:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:156) [metabase.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) [metabase.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:669) [metabase.jar:?]
	at clojure.core$apply.invoke(core.clj:662) [metabase.jar:?]
	at metabase.query_processor$process_userland_query.invokeStatic(query_processor.clj:241) [metabase.jar:?]
	at metabase.query_processor$process_userland_query.doInvoke(query_processor.clj:237) [metabase.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:423) [metabase.jar:?]
	at metabase.query_processor$fn__51403$process_query_and_save_execution_BANG___51412$fn__51415.invoke(query_processor.clj:253) [metabase.jar:?]
	at metabase.query_processor$fn__51403$process_query_and_save_execution_BANG___51412.invoke(query_processor.clj:245) [metabase.jar:?]
	at metabase.query_processor$fn__51447$process_query_and_save_with_max_results_constraints_BANG___51456$fn__51459.invoke(query_processor.clj:265) [metabase.jar:?]
	at metabase.query_processor$fn__51447$process_query_and_save_with_max_results_constraints_BANG___51456.invoke(query_processor.clj:258) [metabase.jar:?]
	at metabase.api.dataset$run_query_async$fn__57769.invoke(dataset.clj:63) [metabase.jar:?]
	at metabase.query_processor.streaming$streaming_response_STAR_$fn__38041$fn__38042.invoke(streaming.clj:160) [metabase.jar:?]
	at metabase.query_processor.streaming$streaming_response_STAR_$fn__38041.invoke(streaming.clj:159) [metabase.jar:?]
	at metabase.async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65) [metabase.jar:?]
	at metabase.async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63) [metabase.jar:?]
	at metabase.async.streaming_response$do_f_async$fn__25230.invoke(streaming_response.clj:84) [metabase.jar:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:152) [metabase.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) [metabase.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:667) [metabase.jar:?]
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1977) [metabase.jar:?]
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1977) [metabase.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:425) [metabase.jar:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:156) [metabase.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:132) [metabase.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:671) [metabase.jar:?]
	at clojure.core$bound_fn_STAR_$fn__5767.doInvoke(core.clj:2007) [metabase.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:397) [metabase.jar:?]
	at clojure.lang.AFn.run(AFn.java:22) [metabase.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Unknown or incorrect time zone: 'US/Eastern'
	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34) ~[metabase.jar:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194) ~[metabase.jar:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:262) ~[metabase.jar:?]
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:357) ~[metabase.jar:?]
	... 110 more
Caused by: java.sql.SQLException: Unknown or incorrect time zone: 'US/Eastern'
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1688) ~[metabase.jar:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1550) ~[metabase.jar:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1513) ~[metabase.jar:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:256) ~[metabase.jar:?]
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:357) ~[metabase.jar:?]
	... 110 more

**Comment by flamber** [comment] 2021-11-24 18:04
Duplicate of #10365

**Closed by flamber** 2021-11-24 18:04 UTC
Labels: Type:Bug, .Needs Triage
