### ISSUE TITLE
Abandonment email job regularly fails

### ISSUE THREAD

**Issue by robdaemon** [metabase/metabase#14446] opened 2021-01-18 21:07 UTC
**Describe the bug**
In multiple hosted customers, a schema failure regularly occurs in the abandonment-emails task. Customer 203534897c3a can be used as a reference.

**Logs**
2021-01-18T04:00:02.467-08:00	2021-01-18 12:00:02,459 ERROR core.JobRunShell :: Job DEFAULT.metabase.task.abandonment-emails.job threw an unhandled Exception:
2021-01-18T04:00:02.467-08:00	clojure.lang.ExceptionInfo: Input to should-send-abandoment-email? does not match schema:
2021-01-18T04:00:02.467-08:00	[nil (named (not (instance? java.time.temporal.Temporal a-metabase.models.user.UserInstance)) last-user) (named (not (instance? java.time.temporal.Temporal a-metabase.models.activity.ActivityInstance)) last-activity) (named (not (instance? java.time.temporal.Temporal a-metabase.models.view_log.ViewLogInstance)) last-view)] 
2021-01-18T04:00:02.467-08:00	at metabase.task.follow_up_emails$fn__82502$should_send_abandoment_email_QMARK___82511.invoke(follow_up_emails.clj:95) ~[metabase.jar:?]
2021-01-18T04:00:02.467-08:00	at metabase.task.follow_up_emails$fn__82502$should_send_abandoment_email_QMARK___82511$fn__82512.invoke(follow_up_emails.clj:97) ~[metabase.jar:?]
2021-01-18T04:00:02.467-08:00	at metabase.task.follow_up_emails$fn__82502$should_send_abandoment_email_QMARK___82511.invoke(follow_up_emails.clj:95) ~[metabase.jar:?]
2021-01-18T04:00:02.467-08:00	at metabase.task.follow_up_emails$send_abandoment_email_if_needed_BANG_.invokeStatic(follow_up_emails.clj:119) ~[metabase.jar:?]
2021-01-18T04:00:02.467-08:00	at metabase.task.follow_up_emails$send_abandoment_email_if_needed_BANG_.invoke(follow_up_emails.clj:114) ~[metabase.jar:?]
2021-01-18T04:00:02.467-08:00	at metabase.task.follow_up_emails.AbandonmentEmail.execute(follow_up_emails.clj:135) ~[metabase.jar:?]
2021-01-18T04:00:02.467-08:00	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [metabase.jar:?]
2021-01-18T04:00:02.467-08:00	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [metabase.jar:?]
2021-01-18T04:00:02.502-08:00	2021-01-18 12:00:02,502 ERROR core.ErrorLogger :: Job (DEFAULT.metabase.task.abandonment-emails.job threw an exception.
2021-01-18T04:00:02.502-08:00	org.quartz.SchedulerException: Job threw an unhandled exception.
2021-01-18T04:00:02.502-08:00	at org.quartz.core.JobRunShell.run(JobRunShell.java:224) [metabase.jar:?]
2021-01-18T04:00:02.502-08:00	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [metabase.jar:?]
2021-01-18T04:00:02.502-08:00	Caused by: clojure.lang.ExceptionInfo: Input to should-send-abandoment-email? does not match schema:
2021-01-18T04:00:02.502-08:00	[nil (named (not (instance? java.time.temporal.Temporal a-metabase.models.user.UserInstance)) last-user) (named (not (instance? java.time.temporal.Temporal a-metabase.models.activity.ActivityInstance)) last-activity) (named (not (instance? java.time.temporal.Temporal a-metabase.models.view_log.ViewLogInstance)) last-view)] 
2021-01-18T04:00:02.502-08:00	at metabase.task.follow_up_emails$fn__82502$should_send_abandoment_email_QMARK___82511.invoke(follow_up_emails.clj:95) ~[metabase.jar:?]
2021-01-18T04:00:02.502-08:00	at metabase.task.follow_up_emails$fn__82502$should_send_abandoment_email_QMARK___82511$fn__82512.invoke(follow_up_emails.clj:97) ~[metabase.jar:?]
2021-01-18T04:00:02.502-08:00	at metabase.task.follow_up_emails$fn__82502$should_send_abandoment_email_QMARK___82511.invoke(follow_up_emails.clj:95) ~[metabase.jar:?]
2021-01-18T04:00:02.502-08:00	at metabase.task.follow_up_emails$send_abandoment_email_if_needed_BANG_.invokeStatic(follow_up_emails.clj:119) ~[metabase.jar:?]
2021-01-18T04:00:02.502-08:00	at metabase.task.follow_up_emails$send_abandoment_email_if_needed_BANG_.invoke(follow_up_emails.clj:114) ~[metabase.jar:?]
2021-01-18T04:00:02.502-08:00	at metabase.task.follow_up_emails.AbandonmentEmail.execute(follow_up_emails.clj:135) ~[metabase.jar:?]
2021-01-18T04:00:02.502-08:00	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) ~[metabase.jar:?]

Metabase version v1.37.2

**Comment by flamber** [comment] 2021-01-18 21:17
Related to #11618 and #12068

**Comment by camsaul** [comment] 2021-04-23 00:54
Duplicate of #12068

**Closed by camsaul** 2021-04-23 00:54 UTC
Labels: Operation/, Type:Bug
