### ISSUE TITLE
Metabase doesn't recognize date fields in SQLite

### ISSUE THREAD

**Issue by nigeljyng** [metabase/metabase#3190] opened 2016-08-15 14:55 UTC
Hey guys,

I'm using SQLite as my database, but when connecting to it, Metabase doesn't recognize the date fields as date, and I'm not able to filter by date. The only way I could get it to work is to convert all dates to UNIX epochs, then select "UNIX epoch (seconds)" in the data model page. I'd much rather be able to output human readable dates into SQLite. I know SQLite doesn't have a date type, so I've output the datefield as text, but Metabase doesn't seem to detect it. Has anyone else run into this problem?

If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is Ubuntu.
*  I'm running Metabase on Docker on a Ubuntu instance and it is using the SQLite database.
*  My data is in a SQLite database. [Postgres / MySQL / Redshift / BigQuery / MongoDB / SQLite / SQL Server / etc.]
*  My Metabase version is  v0.19.2.

**Comment by salsakran** [comment] 2016-08-15 22:38
this is effectively a dupe of #1576

**Closed by salsakran** 2016-08-15 22:38 UTC
Labels: Limitation

**Comment by vvaezian** [comment] 2019-03-19 23:00
@nigeljyng You need to use a time function when inserting the data into the SQLite db. For example
````
cursor.executemany("INSERT INTO test ('id','date','sales') VALUES (?, strftime('%Y-%m-%d %H:%M',?), ?);", values_list)
````
