### ISSUE TITLE
bordered=false in static embedding does not seem to cause any effect

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#35419] opened 2023-11-06 13:22 UTC
### Describe the bug

We seem to have broken the bordered=false on static embeds, it doesn't matter if you set it to true or false, it will always be enabled

### To Reproduce

1) enable embedding
2) make a dashboard
3) click on embedding and disable the bordered attribute

see that the embedding doesn't change, it will stay the same

### Expected behavior

we should remove the borders of the charts

### Logs

NA

### Information about your Metabase installation

```JSON
v47
```

### Severity

P2

**Comment by mazameli** [comment] 2023-11-14 19:02
Isn't it the case that those appearance options in the static embedding setup modal don't do anything at all, and that you have to change that variable/attribute in the embedding code itself? I.e., I believe this is a UX issue, not a bug, which we're addressing in a project of @albertoperdomo's.

**Comment by albertoperdomo** [comment] 2023-11-14 19:33
Actually, I don't know what effect `bordered=true/false` should have and can only guess. The [docs](https://www.metabase.com/docs/latest/embedding/static-embedding-parameters#customizing-the-appearance-of-a-static-embed) list the parameters available, but don't describe what happens.

I can see that there is a border around the entire dashboard that is rendered or not, depending on this parameter.

Screenshots:

`bordered=false`
<img width="1088" alt="image" src="https://github.com/metabase/metabase/assets/24216/21677718-302a-42fb-baee-4d7e86c0dac3">


`bordered=true`
<img width="1087" alt="image" src="https://github.com/metabase/metabase/assets/24216/05c98ab8-fc04-4b11-af64-502117a6907e">

The difference is subtle but is there. Let me know if you think this is not how it's supposed to work @paoliniluis .

**Comment by paoliniluis** [comment] 2023-11-14 20:03
I thought it was the border of the cards @albertoperdomo. Maybe I'm wrong

**Comment by mazameli** [comment] 2023-11-15 17:36
It's the border around the outside of the dashboard.

**Comment by mazameli** [comment] 2023-11-15 17:37
So I motion we either close this issue or characterize it as a UX one.

**Comment by albertoperdomo** [comment] 2023-11-22 17:59
I have seen no reference that sets the expectation for this to look differently. The docs also don't provide a definition of what the parameter does, so I am biased to consider this to work as expected, and if our customers have other needs create specific feature requests.

**Closed by albertoperdomo** 2023-11-22 17:59 UTC
Labels: Type:Bug, Priority:P2, Embedding/Signed, .Regression, .Team/Embedding
