### ISSUE TITLE
Custom query generates wrong endpoint when number of map features exceeds 1000 records

### ISSUE THREAD

**Issue by rburhum** [metabase/metabase#11353] opened 2019-11-19 23:07 UTC
Queries that have more than 1000 records are generating wrong URLs.

I have metabase connected to a Postgres with PostGIS with the following query:

```sql
Select ST_X(wkb_geometry) as X, ST_Y(wkb_geometry) AS Y 
from dataset_166637
where st_y(wkb_geometry) is not null and st_x(wkb_geometry) is not null
limit 999
```
This generates the right result:

![Screen Shot 2019-11-19 at 5 41 02 PM](https://user-images.githubusercontent.com/138918/69192989-cbc16000-0af3-11ea-82a5-07de55c31153.png)

However, if we have more than 1000 records like so:
```sql
Select ST_X(wkb_geometry) as X, ST_Y(wkb_geometry) AS Y 
from dataset_166637
where st_y(wkb_geometry) is not null and st_x(wkb_geometry) is not null
limit 1000
```
it starts generating invalid urls for fetching results:

![Screen Shot 2019-11-19 at 5 58 32 PM](https://user-images.githubusercontent.com/138918/69194075-3e333f80-0af6-11ea-9e63-35e42b2a21a7.png)

```
Request URL: https://dashboard.amigocloud.com/api/tiles/12/1243/2452/undefined/undefined/1/0/?query=%7B%22native%22%3A%7B%22query%22%3A%22Select%20ST_X(wkb_geometry)%20as%20X%2C%20ST_Y(wkb_geometry)%20AS%20Y%20%5Cnfrom%20dataset_166637%5Cnwhere%20st_y(wkb_geometry)%20is%20not%20null%20and%20st_x(wkb_geometry)%20is%20not%20null%5Cnlimit%201000%22%2C%22template-tags%22%3A%7B%7D%7D%2C%22type%22%3A%22native%22%2C%22database%22%3A34%7D
Request Method: GET
Status Code: 404 Not Found
Remote Address: 66.160.128.230:443
Referrer Policy: no-referrer-when-downgrade

query: {"native":{"query":"Select ST_X(wkb_geometry) as X, ST_Y(wkb_geometry) AS Y \nfrom dataset_166637\nwhere st_y(wkb_geometry) is not null and st_x(wkb_geometry) is not null\nlimit 1000","template-tags":{}},"type":"native","database":34}

Response:
"API endpoint does not exist."
```

No records are shown.

**Severity**
I can't use the maps because I have more than 1000 records :(

**Version**
Metabase version 0.33.5.1

**Comment by flamber** [comment] 2019-11-19 23:20
Hi @rburhum 
Looks like a duplicate of #4394 - if you agree, then please close this and upvote the other issue :+1:

**Comment by mazameli** [comment] 2019-11-19 23:24
Closing as duplicate of #4394

**Closed by mazameli** 2019-11-19 23:24 UTC
Labels: .Duplicate
