### ISSUE TITLE
Option to set decimal points in chart series

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#31338] opened 2023-06-05 20:25 UTC
**Is your feature request related to a problem? Please describe.**
There is currently no way to set decimal points for series on pie charts. 

You can change the results but not the series

<img width="1235" alt="Screenshot 2023-06-05 at 5 23 58 PM" src="https://github.com/metabase/metabase/assets/132273646/67cc8846-ae28-4431-aa57-a505a91d1407">
(browser view zoomed out on purpose)

**Describe the solution you'd like**
Would be useful to have an option on the chart settings to set decimal points

**Additional context**
Might be related to https://github.com/metabase/metabase/issues/26006

**Comment by gdoron** [comment] 2023-06-07 20:24
Adding to that @paoliniluis .

Also in line charts, you can have people count chart, and the y axis would be 0.0, 0.1, 0.2 ... for charts that show small numbers.
Obviously for integers it should know not to show decimal numbers, but even for real numbers, there should be a way of setting a min value.

Currently if you set the min value, you must also set the max value, which is even worst, because 1 chart might show numbers between 1-3 and 1 chart 1-1,000,000 so you can't set the values.

**Comment by cdeweyx** [comment] 2023-12-13 00:25
Closing as a dupe of https://github.com/metabase/metabase/issues/12152

**Closed** 2023-12-13 00:25 UTC
Labels: Type:New Feature, Visualization/Charts
