### ISSUE TITLE
Upgrade to v0.31.1 converts questions with "Today" incorrectly

### ISSUE THREAD

**Issue by key88sf** [metabase/metabase#9014] opened 2018-11-24 12:22 UTC
After upgrading to v0.31.1, all questions of the form "some_timestamp = Today" have the underlying sql converted to:
`some_timestamp = now()`,  which is just comparing the exact time, instead of the full day.

When creating a new question from scratch, though, and selecting the same filter, Metabase correctly computes the SQL as:
`CAST(some_timestamp AS date) = CAST(now() AS date))`

The upgrade to v0.31.1 has of course now broken all of our existing questions of this form.

**Comment by tlrobinson** [comment] 2018-11-26 19:30
Possibly related to #8927?

**Comment by camsaul** [comment] 2018-11-27 19:48
@key88sf to confirm, you're seeing this with 0.31.1, not 0.31.0? We fixed #8927 (which sounded like the same issue) for 0.31.1

**Comment by key88sf** [comment] 2018-11-27 20:43
@camsaul Yes 0.31.1.

I think it's slightly different than #8927 though.

1) This only was a problem for queries that existed prior to the upgrade.  New queries created in 0.31.1 with the visual query builder had no problem.

2) It only seemed to affect queries that were built using the visual query builder, *and* had a "date = today" clause.

**Comment by camsaul** [comment] 2018-11-27 22:21
@key88sf can you post one of the queries that's failing?

Specifically the `dataset_query` column of the Question that's failing. If you use the browser console and view the Question you should see it come back in the API response

**Comment by camsaul** [comment] 2018-11-27 22:21
Or if you run the query that fails it should come back as `json_query` IIRC

**Comment by camsaul** [comment] 2018-11-27 23:51
Haven't been able to repro :(

**Comment by camsaul** [comment] 2018-11-28 00:18
If anyone else can repro or give us more information please ping me! I'll fix this if I can

**Comment by mr-devop** [comment] 2018-12-10 21:57
@camsaul so this is a bit tricky. This issue is happening to me as well. When I upgrade my existing metabase that has been in action and along the upgrade path for a while I get this issue. However if I create a brand new new metabase thats empty at 0.30.4 create a question, save. then upgrade to 0.31.2 its fine.

**Comment by mr-devop** [comment] 2019-01-17 01:37
@camsaul just to provide a bit more info.
here's the SQL for a question on 0.30.4:
```
SELECT count(*) AS "count"
FROM "public"."thing"
WHERE (CAST("public"."thing"."set_at" AS date) = CAST(now() AS date)
   AND "public"."thing"."type" = ?)
```
here's the SQL on the same question after an upgrade to 0.31.2
```
SELECT count(*) AS "count"
FROM "public"."thing"
WHERE ("public"."thing"."set_at" = now()
   AND "public"."thing"."type" = ?)
```

**Comment by mr-devop** [comment] 2019-01-17 09:36
I am seeing the same issue going between `0.30.4` -> `0.31.0`

**Comment by mr-devop** [comment] 2019-01-17 10:37
Here's some additional info from the database I was able to gather.

Table: `report_card`,  column: `dataset_query`
v0.30.4 WORKING
```
{"database":2,"type":"query","query":{"source_table":8,"aggregation":["count"],"breakout":[],"filter":["AND",["=",75,["relative_datetime","current"]],["=",86,"thing"]]}}
```
v0.31.0 BROKEN ( does not make use of "CAST" )
```
{"database":2,"type":"query","query":{"source_table":8,"aggregation":["count"],"breakout":[],"filter":["AND",["=",75,["relative_datetime","current"]],["=",86,"thing"]]}}
```
v0.31.0 WORKING (once deleted and added back manually)
```
{"database":2,"type":"query","query":{"source-table":8,"aggregation":[["count"]],"filter":["and",["time-interval",["field-id",75],"current","day"],["=",["field-id",86],"thing"]]}}
```

**Comment by mr-devop** [comment] 2019-01-31 19:14
@camsaul is there any information I can dig up to help you in resolving this?

**Comment by sinkzink** [comment] 2019-03-26 11:45
@camsaul 
we are occured this issue too with redshift DB.

**Comment by key88sf** [comment] 2019-04-02 02:54
@camsaul Do u think we can fix this one? It prevents users like us from ever being able to upgrade.

**Comment by sinkzink** [comment] 2019-04-02 11:16
@camsaul
we want to upgrade. but this issue is show stopper... fix this please.

**Comment by key88sf** [comment] 2019-04-30 21:38
@camsaul Any idea on this? Stuck on an old version and can't upgrade :(

**Comment by sinkzink** [comment] 2019-05-02 11:50
@key88sf  @camsaul 

I confirmed fix it since 0.32.2.
probably, this problem was solved by the following
#9090 

I'm glad we can use metabase without any problems.
sorry, late feedback.

**Comment by MarkRx** [comment] 2019-05-02 13:30
May want to have the OP validate before closing as dates are tricky and there may be more than one issue at play here.

**Comment by key88sf** [comment] 2019-05-02 13:31
We will give the latest version a try again and report back soon. Thanks!

**Comment by key88sf** [comment] 2019-05-02 20:01
@MarkRx @camsaul Nope, same bug.

Version 0.30.4 SQL:
```

**Comment by key88sf** [comment] 2019-05-02 20:04
This is from a question created with the Metabase UI with this filter:
<img width="118" alt="Screen Shot 2019-05-02 at 4 03 40 PM" src="https://user-images.githubusercontent.com/211776/57103500-eff25680-6cf3-11e9-837a-9a4b238e430b.png">

**Closed** 2019-10-01 03:32 UTC
Labels: Priority:P1, Query Processor, Type:Bug
