### ISSUE TITLE
On Date filter returns no results on a summarized question

### ISSUE THREAD

**Issue by eiternme** [metabase/metabase#18769] opened 2021-10-29 18:54 UTC
**Describe the bug**
For a summarized custom question that is grouped by each day, filtering on any specific day returns no results.

**To Reproduce**
1. Custom question > `Orders` > Summarize `Count` by `Created Date: Day` (should match below screenshot)
![image](https://user-images.githubusercontent.com/91676712/139485249-ee8f9c92-8f3e-437c-b196-9c99c5341920.png)
2. Filter on any specific day
3. No results

**Expected behavior**
Should return row for that specific date

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

* Your browser and the version: Chrome (Latest)
* Your operating system: Windows Version 21H1 (OS Build 19043.1288)
* Your databases: Microsoft SQL Server 2019 (RTM-CU12) (KB5004524) - 15.0.4153.1 (X64)
* Metabase version: 0.41.1 (Latest)
* Metabase hosting environment: Jar-file on Windows
* Metabase internal database: H2 (default)

**Additional context**
This problem was found when I was filtering on a summarized custom question based off of another summarized question. When I performed an on date filter, I kept receiving results from the day after what I wanted to filter for. This was based off of a more complex question, so I wasn't able to reproduce that using the sample dataset. I was trying to create a minimal reproducible example (above) but then I got unexpected results. I've attached a screenshot on my original problem below. Note the last filtering criteria and the resulting dates for Date Order Shipped. Hopefully resolving the problem on this issue would fix what I am seeing here.

![image](https://user-images.githubusercontent.com/91676712/139486293-c39ae69e-f187-4e10-a62d-bcb80078259c.png)

**Comment by flamber** [comment] 2021-10-29 19:03
Hi @eiternme 

I cannot reproduce with your steps:
![image](https://user-images.githubusercontent.com/1447303/139488524-8ce1d9e2-4e39-4dc2-844a-1c09fa56a956.png)

Post "Diagnostic Info" from Admin > Troubleshooting.

And go to the Notebook editor and click "View the SQL" and post the SQL, when you have filtered like you do in your screenshot.

**Comment by eiternme** [comment] 2021-10-29 20:05
<details><summary>Diagnostic Info</summary>

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9-Ubuntu-0ubuntu2.20.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9-Ubuntu-0ubuntu2.20.04",
    "os.name": "Linux",
    "os.version": "5.10.16.3-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlserver",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-10-21",
      "tag": "v0.41.1",
      "branch": "release-x.41.x",
      "hash": "76aa4a5"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

</details>

Hi @flamber, I appreciate the quick response.

I think I found why this problem is occurring. For Step 2, instead of using the editor, I clicked Visualize > Table View > Clicked on a date > Click on '=' and it results in filtering before the summarizations which is why it returns no results (screenshot below). Using the editor, you can explicitly filter after summarization as a workaround. Would it make sense for Metabase to keep track of these steps and filter at the latest step so this confusion does not arise?

![image](https://user-images.githubusercontent.com/91676712/139491915-0a3f5a75-d180-4f34-a92f-c455038a5708.png)

Also, in regards to my problem I've listed under **additional context**, it appears that the generated SQL uses the `DateTimeOffsetFromParts` which offsets by some hours to convert the timezone from what appears to be UTC to where I am now, although those times are not supposed to be in UTC. That appears to be why I am receiving results from the previous day, because the dates that I have listed are at 12:00AM. I would be able to try as a workaround to write the results in SQL to avoid the offsetting, but then I would not be able to have the ability to drill down in my dashboards where I use this question. Are these timezone issues due to the source database settings? 

I do have another source that uses UTC time so I have to offset it in my SQL, but it doesn't offset automatically when using custom question builder in Metabase. Do you have any idea why this offsetting occurs for one of my data sources, but not the other? Or have any ideas for me to be able to investigate further?

Thanks for all that you and your team are doing for the open source analytics community.

**Comment by flamber** [comment] 2021-10-29 20:49
Very related to #17807 if not a duplicate

Steps to reproduce:
1. Custom question > Sample Dataset > Products - summarize Count grouped by CreatedAt:Day
![image](https://user-images.githubusercontent.com/1447303/139499309-c0a12567-a978-431e-99dc-24955059822c.png)
2. Change visualization to Table, click first date row and click `=` filter
![image](https://user-images.githubusercontent.com/1447303/139499617-a5196433-4ba9-4d81-92a8-0f2ab16bcfb7.png)
3. "No results!" because it's trying to filter on the datetime instead of just the date (`"filter":["and",["=",["field",108,null],"2016-04-26T00:00:00+02:00"]]`)
![image](https://user-images.githubusercontent.com/1447303/139499713-6b9acfe3-d3ff-4a80-80a5-c7b3243af006.png)

**Comment by camsaul** [comment] 2023-11-09 01:09
repro'ed on `master`.

**Comment by camsaul** [comment] 2023-11-09 01:29
The actual problem here is that the generated query is not including date bucketing in the filter clause, it should be 

```clj
{:filters [[:= {} [:field {:temporal-unit :day} 108] "2016-04-26T00:00:00+02:00"]]}
```

but what the MLv1 drill is generating is actually just

```clj
{:filters [[:= {} [:field {} 108] "2016-04-26T00:00:00+02:00"]]}
```

Confirmed that this is working as expected in the MLv2 version of drills. I'll push a test in a second

**Comment by camsaul** [comment] 2023-11-09 01:29
Once https://github.com/metabase/metabase/issues/33973 lands we can close this out

**Comment by camsaul** [comment] 2023-11-09 02:25
Actually I'm not really 100% sure why the `auto-bucket-datetime-fields` middleware isn't applying default `:day` bucketing here anyway

**Closed** 2023-11-09 15:40 UTC
Labels: Type:Bug, Priority:P2, Querying/Parameters & Variables, .Backend, Querying/GUI, .Wanted: MLv2, Querying/Drill Thrus
