### ISSUE TITLE
Change casing auto-completion in SQL editor

### ISSUE THREAD

**Issue by nick-at** [metabase/metabase#12412] opened 2020-04-28 06:31 UTC
**Is your feature request related to a problem? Please describe.**
Our SQL style guide requires that all SQL operators are written in uppercase e.g.
`SELECT
  *
FROM table`

Without opening up the upper vs lowercase debate for SQL operators, it's fair to say that there are many people that write SQL using uppercase operators.

The autocomplete in the SQL editor assumes all SQL operators are written in lowercase and will replace your uppercase operators with lower case ones as you type.

**Describe the solution you'd like**
Provide an account-level setting to change all auto-complete SQL operators to uppercase e.g. `SELECT` not `select`.

**How important is this feature to you?**
Is this the most important thing you could work on? Far from it. But it will save a large cumulative amount of time across all our users over time.

**Comment by flamber** [comment] 2020-04-28 08:45
Duplicate of #4469 - upvote by clicking :+1: on the first post

**Closed by flamber** 2020-04-28 08:45 UTC
Labels: .Duplicate
