### ISSUE TITLE
public links are not working after updating to the latest version

### ISSUE THREAD

**Issue by Shra25** [metabase/metabase#8347] opened 2018-08-17 05:45 UTC
browser and the version: Chrome Version 68.0.3440.106 (Official Build) (64-bit)  
operating system: Windows 10 
databases: MySQL  Metabase version: 0.30  
Metabase hosting environment:  Linux/Ubuntu 16.04  
Metabase internal database: H2 (default)  
Repeatable steps to reproduce the issue 
public links are not accessible

**Comment by lwqcz** [comment] 2018-08-17 06:38
Can you share an image of issue or what was done before issue occured, even some log file records about this issue? It would help a lot.

**Comment by mazameli** [comment] 2018-08-17 17:28
Are you getting a 404 when trying to go to a public link? Is this only happening with old public links, or only with new ones, or both?

**Comment by mazameli** [comment] 2018-08-20 17:45
I tried all of our own previously existing public dashboard and question links, and all of them worked.

Could you provide a screenshot with sensitive data scrubbed out to show us what you're seeing (or not seeing)? We'll need to figure out if there are any commonalities between the questions/dashboards that aren't working. Any javascript or server log errors that you can provide would also be helpful.

**Comment by Shra25** [comment] 2018-08-21 05:28
### check server log 


08-21 10:43:39 INFO middleware.cache :: Query took 52 ms to run; miminum for cache eligibility is 300000 ms
08-21 10:43:39 DEBUG metabase.middleware :: GET /api/public/dashboard/-----/card/258 200 (58 ms) (16 DB call                            s). Jetty threads: 8/50 (8 busy, 3 idle, 0 queued)
08-21 10:43:39 INFO middleware.cache :: Query took 71 ms to run; miminum for cache eligibility is 300000 ms
08-21 10:43:39 DEBUG metabase.middleware :: GET /api/public/dashboard/-----/card/265 200 (80 ms) (16 DB call                            s). Jetty threads: 8/50 (7 busy, 4 idle, 0 queued)
08-21 10:43:39 DEBUG metabase.middleware :: GET /api/user/current 401 (114 µs) (0 DB calls).

**Comment by toddheslin** [comment] 2018-11-15 04:49
I had this same issue and it was actually a problem with one of the dashboard cards. After the recent upgrade it went a bit funky but the result was that the public URL was returning a 400 error.

After I removed this card, the report worked.

The preview looked like this:
![image](https://user-images.githubusercontent.com/1883112/48530884-d475c980-e8d4-11e8-9bb5-6d65b9b79168.png)

But the actual display on the dashboard looked like this:
![image](https://user-images.githubusercontent.com/1883112/48530899-e5263f80-e8d4-11e8-92b7-8bc8efb43167.png)

Couldn't quite pin down what the issue was but deleting and re-adding the card worked.

**Comment by flamber** [comment] 2020-05-25 16:25
Closing, since without detailed logs or reproducible steps, it's hard to know what happened.

**Closed by flamber** 2020-05-25 16:25 UTC
Labels: Administration/Permissions, Priority:P3, Reporting/Dashboards, Type:Bug
