### ISSUE TITLE
Pinned sql queries with required date filter can't be rendered anymore since 0.48.x

### ISSUE THREAD

**Issue by notz** [metabase/metabase#38398] opened 2024-02-02 15:43 UTC
### Describe the bug

We use several pinned sql queries with date filters with default values, but the can't be rendered anymore.
The bug is related to #37831 and #38012

![image](https://github.com/metabase/metabase/assets/697251/7d689a4d-c007-40e5-a02e-146743146013)

If the required flag on the filter is not set the query is displayed but without the default filter values applied

### To Reproduce

1. Create a new sql query with a date variable
2. Set the date variable to a field filter and configure a default value for the filter

![image](https://github.com/metabase/metabase/assets/697251/48d32a8c-9671-4739-b405-9575907dceea)

3. Pin the query on collection
4. See the error

### Expected behavior

Like in 0.47.x

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "de-DE",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "6.5.0-4-amd64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-01-29",
      "tag": "v0.48.4",
      "hash": "62145b0"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Blocking our upgrade

**Comment by paoliniluis** [comment] 2024-02-02 15:49
I can't reproduce, but I'm trusting @dpsutton here
![image](https://github.com/metabase/metabase/assets/1711649/ab977dc6-3660-4430-85b4-f59302ca2547)
![image](https://github.com/metabase/metabase/assets/1711649/10122942-4db4-47b2-809c-d50fb93adfca)

**Comment by notz** [comment] 2024-02-02 15:51
@paoliniluis Please read my explanation. You also don't get the right result because it should be 0. But if you set the filter as required you will get the error.

**Comment by notz** [comment] 2024-02-02 15:56
@dpsutton The bug happens also with 0.48.0 and still happens with 0.48.4

**Comment by dpsutton** [comment] 2024-02-02 15:57
ah. i missed `0.48.x` and read it as `0.48.3`. Yes this won't be related to that bugfix. Sorry about that.

**Comment by paoliniluis** [comment] 2024-02-06 14:42
just reproduced, duplicate of https://github.com/metabase/metabase/issues/37831

**Closed by paoliniluis** 2024-02-06 14:42 UTC
Labels: Type:Bug, Organization/Collections, .Regression
