### ISSUE TITLE
Unable to add database(s) via environment variables

### ISSUE THREAD

**Issue by saidimu** [metabase/metabase#2607] opened 2016-05-15 23:34 UTC
If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is Linux.
*  I'm running Metabase on Docker (hosted at Docker Cloud)
*  My database is Postgres.
*  My Metabase version is v0.17.1

Adding databases for analysis via environment variables doesn't seem to be supported. This means auto-configuring isn't possible (one has to manually setup each database to analyze).

**Comment by salsakran** [comment] 2016-05-16 00:59
Closing as a duplicate of #2052 

It would be useful if you could chime in on that issue to let us know what you're trying to do and why you need this feature. We're primarily building Metabase as an end-user installed/configured application, so it would be helpful to understand your end goals with this feature request, as there might be a better way to get there.

**Closed by salsakran** 2016-05-16 00:59 UTC

**Comment by saidimu** [comment] 2016-05-16 01:23
The specific issue concerns a Docker environment where the database details (host, port etc) are specified via Docker links and only accessible as environment variables. These values aren't static as a different database container may be linked to the Metabase container or the existing database container may be restarted (in which case a different IP may be assigned).

**Comment by salsakran** [comment] 2016-05-16 01:42
While this makes sense for the application database, where we support using env variables, I don't think this really works for the case of a data warehouse.

Typically a data warehouse will be accessed by any number of tools, for everything from loading, transforms, pre-processing and enrichment, etc. It really should have a dns name and a stable location. What you're describing isn't a deployment scenario we see very often, and would strongly recommend you not use for an analytics database/ data warehouse deployment.

**Comment by jeremyjh** [comment] 2017-11-03 11:50
@salsakran This issue also prevents me from effectively using Heroku Postgres as a reporting source. Heroku Postgres will randomly change usernames/passwords. Since I'm also running Metabase in Heroku, I can attach the source database and access it's connection string via environment variables that are guaranteed to be correct. But unfortunately Metabase provides us no means to make use of it.

**Comment by salsakran** [comment] 2017-11-03 17:46
@jeremyjh Heroku will inject an applications database creds via environment variables, but to my knowledge doesn't do that cross application. I.e. in your situation, you'd be able to access the _Metabase application database_ but not your actual applications, unless you're doing something weird and running us side by side your server in a single Heroku application. 

Practically, any database that will change its connection string out from under you is going to be a pain to use as a reporting source. IMO this is Heroku not really caring about this use case. Folks have had success pushing their application database into a data warehouse (eg, Redshift or BigQuery) and pointing Metabase at that.

**Comment by jeremyjh** [comment] 2017-11-03 20:32
@salsakran You can attach a Heroku database to multiple applications, which will mean the credentials are injected into each. I agree that Heroku doesn't care about anything not running in Heroku, but in our case Metabase runs in Heroku. 

Even outside of Heroku, I could see using environment variables for security credentials but admit its probably not something a lot of people are asking for.

If I submit a proper PR for this do you think I would be able to get it accepted?

**Comment by jeremyjh** [comment] 2017-11-04 16:02
@salsakran Nevermind, I learned that if you create additional credentials in Heroku that they are not rotated automatically; they would only rotate manually. So that looks like the proper answer here. https://devcenter.heroku.com/articles/heroku-postgresql-credentials

**Comment by kivutar** [comment] 2018-10-24 04:51
@jeremyjh I'm reading the documentation of Heroku, and I don't see where it's suggested that additional credentials are never rotated automatically.

**Comment by jeremyjh** [comment] 2018-10-24 10:49
@kivutar Perhaps it is only [implied here](https://devcenter.heroku.com/articles/heroku-postgresql-credentials#pg-credentials-rotate), where it suggests you should manually rotate credentials. The credentials are never rotated; I've used the same ones for nearly a year in one application.
