### ISSUE TITLE
"Pick your data" menu is too small for connections with lots of tables

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#15649] opened 2021-04-16 04:47 UTC
**Describe the bug**
Sample Dataset
![image](https://user-images.githubusercontent.com/4504437/114972591-e196a880-9ed2-11eb-9608-19f3b1763ba8.png)

Our actual data (~50 tables)
![image](https://user-images.githubusercontent.com/4504437/114972505-bb710880-9ed2-11eb-8d99-246df87ba5ea.png)

**Logs**
Nothing

**To Reproduce**
1. New simple question > select data connection with many tables
2. Selector very small with scroll bars

**Expected behavior**
Useable table selector as in v0.38.1

**Screenshots**
See above

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "13.0.2+8",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-13",
      "tag": "v0.39.0-rc2",
      "branch": "release-x.39.x",
      "hash": "f06180f"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**
Can still use the selector but it's not user friendly

**Comment by flamber** [comment] 2021-04-16 09:15
Duplicate of #15591 - it's fixed after rc2

**Closed by flamber** 2021-04-16 09:15 UTC
Labels: .Needs Triage, Type:Bug
