### ISSUE TITLE
Collection name unique constraint confusion

### ISSUE THREAD

**Issue by lindsay-stevens** [metabase/metabase#8738] opened 2018-10-22 11:14 UTC
## Environment
- Your browser and the version: Chrome 69
- Your operating system: Windows 10
- Your databases: Postgres
- Metabase version: 0.28.6
- Metabase hosting environment: Jar
- Metabase internal database: Postgres

## Description

This is probably best described as a UX / documentation issue.

- When creating a collection, a POST goes to /api/collection. [code](https://github.com/metabase/metabase/blob/master/src/metabase/api/collection.clj#L180)
- The collection name is slugify-ed, i.e. it's lowercased and [a-z0-9] whitelisted. [code](https://github.com/metabase/metabase/blob/master/src/metabase/util.clj#L374)
- Duplicate collection names are allowed, but duplicate collection slugs aren't. [code](https://github.com/metabase/metabase/blob/master/resources/migrations/000_migrations.yaml#L3258)
- The error message says the name already exists but the duplicate slug is the problem.

## Steps to Reproduce

Either via the Metabase UI or the API, create 2 collections with the following names.

- "My cool collection (the best)", which is slugified to "my_cool_collection__the_best_"
- "My cool collection [the best]", which is slugified to "my_cool_collection__the_best_"

This would probably also happen for emoji too, but I didn't test it. The whitelist is pretty strict.

Observe HTTP 400 error on second one, error message: "A collection with this name already exists".

Or as JSON: `'{"errors":{"name":"A collection with this name already exists"}}'`

## Possible solutions

- Change the API/UI error to indicate that the duplicate slug is the real problem, not the name.
  - i.e. clarify how a user can fix the issue, wrt. special chars / emoji, such as a "slug preview".
- Change the database/UI policy for collections such that unique names are required.
- Change URL routing to use the numeric ID instead of slug, i.e. remove collection slugs
- Change the API to accept a slug value, which must validate against the existing slugify rules.

**Comment by camsaul** [comment] 2018-11-21 00:45
Duplicate of #8738

**Closed by camsaul** 2018-11-21 00:45 UTC
Labels: Bug, Collections, Priority/P3

**Comment by lindsay-stevens** [comment] 2018-11-21 04:39
@camsaul this was closed as a duplicate of itself - did you mean #6737? Although that one seems to be about certain characters preventing collection curation. This issue is about the collection slug character whitelist causing duplicate constraint violations.

**Comment by camsaul** [comment] 2018-11-21 21:31
@lindsay-stevens sorry. I meant #7397
