### ISSUE TITLE
Choosing which schemas metabase will work on

### ISSUE THREAD

**Issue by Alexsandr0x** [metabase/metabase#13314] opened 2020-09-25 18:48 UTC
Will be awesome if Metabase had a mode where I can decide which schemas will be updated/scanned. To avoid execute time consuming SELECTS in views on heavy tables in test/development schemas

I didn't found anything like these and select the checkbox to make me choose when scan is not

**Comment by flamber** [comment] 2020-09-25 18:56
Duplicate of #2591/#5500/#6286

**Closed by flamber** 2020-09-25 18:56 UTC
Labels: .Needs Triage, Type:Question
