### ISSUE TITLE
Pulse Email Attachments Should Follow Download File Limits (not display limit of 2000)

### ISSUE THREAD

**Issue by kevinconroy** [metabase/metabase#10930] opened 2019-09-18 20:35 UTC
**Is your feature request related to a problem? Please describe.**
In Metabase 0.32.1, pulses with file attachments would allow you to include the full data set. I can see in https://github.com/metabase/metabase/issues/9831 that additional limits were added.

I think the Pulse email attachments should mirror the limits use for file downloads. Our users are confused as to why a CSV file generated via the pulse is truncated while the CSV file generated when accessing a report isn't truncated.

**Describe the solution you'd like**
Change the constraint use for Pulse attachments to match the JSON/CSV endpoint limits.

**Describe alternatives you've considered**
Absent this change, I may need to setup my own cron job to request the CSV endpoint and email the results, effectively duplicating the Pulse functionality.

**How important is this feature to you?**
Highly critical issue to ensure that our data pulse are still providing the full details needed.

**Additional context**
Currently using metabase v0.33.2

**Comment by flamber** [comment] 2019-09-18 20:51
Hi @kevinconroy 
Sounds like duplicate of #7622, which has several good comments on why the behavior is like that.
If you agree, then please close this and upvote the other issue by clicking :+1: on the first post.

**Comment by kevinconroy** [comment] 2019-09-19 00:11
Well, they are similar, but I guess more what I'm trying to point out is that you've applied technical logic to why the files you download get more data than the files that pulses can email. For end users, this doesn't make sense.

I'm happy to close this issue and upvote the other one, but it's clear that having configurable limits is going to be increasingly important.

**Closed** 2019-09-19 00:11 UTC
Labels: Type:New Feature

**Comment by flamber** [comment] 2019-09-19 01:22
@kevinconroy You might want to upvote #4564 too.
