### ISSUE TITLE
Pulse Never Sends Emails Automatically

### ISSUE THREAD

**Issue by landreville** [metabase/metabase#14037] opened 2020-12-10 18:30 UTC
**Describe the bug**

Pulses never send scheduled emails. On restart or clicking "Send Email Now" does send an single email, but the next schedule run never happens.

The jobs page shows that the Pulses last ran at the time Metabase started. The next scheduled run appears to be the correct time to next run the pulse job, but it never runs. The "Last Fired" time is never updated to past the Metabase start time (see screenshot below).

**Logs**
There are no error logs.

**To Reproduce**
1. Create a Pulse
2. Select a scheduled time to run (eg daily at 6:00 am)
3. Click save

**Expected behavior**
Pulse email is sent at 6am.
Actual results: Nothing is sent out and there are no error logs.

**Screenshots**
![image](https://user-images.githubusercontent.com/24076/101814061-9a934380-3aeb-11eb-8dfc-9b1259ac55cb.png)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_272-b10",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "1.8.0_272",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.272-b10",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.2.2.el7.x86_64",
    "user.language": "en",
    "user.timezone": "America/Toronto"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.20"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.37.1",
      "date": "2020-11-12",
      "branch": "release-x.37.x",
      "hash": "ba57ab6"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```

**Severity**

Pulses don't work at all. There is no way to have an email sent out periodically with results.

**Comment by flamber** [comment] 2020-12-10 19:23
Duplicate of #10088

**Closed by flamber** 2020-12-10 19:23 UTC
Labels: .Needs Triage, Type:Bug
