### ISSUE TITLE
Bug in converting question filters to SQL

### ISSUE THREAD

**Issue by Simbul** [metabase/metabase#6626] opened 2017-12-29 10:09 UTC
I noticed what I think is a bug in converting question filters to SQL in the Mac app. Here are the steps to reproduce the issue.

First, create a new question with the sample dataset and add a filter on a text field. Everything works as intended.

![screen shot 2017-12-29 at 10 57 10](https://user-images.githubusercontent.com/147104/34434595-70f0a636-ec87-11e7-9a99-0cd6e5904063.png)

However, the SQL generated for the question does not include the filter:

```sql
SELECT count(*) AS "count"
FROM "PUBLIC"."PRODUCTS"
WHERE "PUBLIC"."PRODUCTS"."VENDOR" = ?
```

That question mark looks like a placeholder. My guess would be that Metabase is using a prepared statement and passing the correct value to it. The SQL query alone, however, is not a complete representation of the question.

Converting the question to SQL results - not surprisingly - in an error.

![screen shot 2017-12-29 at 11 01 42](https://user-images.githubusercontent.com/147104/34434645-b3dc63fe-ec87-11e7-8f82-b9c2d5eb17d4.png)

I'm on the latest Metabase Mac App (0.27.2.0), using H2. Not sure it matters, but I'm on macOS Sierra (10.12.6).

**Comment by Arrowofdarkness** [comment] 2017-12-29 17:48
I experienced the same problem from 0.26+ and it still happens, using HE w/jar and a MASALA datasource, upgraded each time with no fix and currently on 0.27.2

**Comment by mazameli** [comment] 2017-12-29 18:02
I believe this is a duplicate of https://github.com/metabase/metabase/issues/3549. The issue is that prepared statements parameters aren't being substituted when converting a GUI query to SQL/native. Please let me know if you disagree that this is a duplicate of that issue.

**Closed by mazameli** 2017-12-29 18:02 UTC
Labels: Duplicate

**Comment by Simbul** [comment] 2017-12-29 18:09
The symptoms are definitely the same: I think you're right in deduping this issue @mazameli.
