### ISSUE TITLE
Dashboard filter on foreign key does not work

### ISSUE THREAD

**Issue by brainsbucket** [metabase/metabase#9055] opened 2018-11-30 09:33 UTC
Hi everyone,

First thanks for your great work with metabase !

This is my issue :
I get an SQL error when trying to filter a card on a foreign key, on a dashboard with an ID filter.

Step tu reproduce with sample data : 

I create this question : 
![orders nombre de lignes metabase](https://user-images.githubusercontent.com/4415399/49280261-0ae14600-f48a-11e8-871b-3c2e11b4cb55.png)

Then I create a dashboard with an id filter link on the User_id : 
![link_dashboard](https://user-images.githubusercontent.com/4415399/49280481-a1156c00-f48a-11e8-821b-1935191ee351.png)

Then,  if no filter is apply it work : 
![working](https://user-images.githubusercontent.com/4415399/49280569-d28e3780-f48a-11e8-83fb-b1e4f8965d14.png)

But if I chose a user, it failed : 
![not_working](https://user-images.githubusercontent.com/4415399/49280630-f81b4100-f48a-11e8-8421-7bf1bad7b7fc.png)

And this is the error I get in the console : 

> Function "ID" not found; SQL statement: SELECT "METABASE_FIELD"."BASE_TYPE" FROM "METABASE_FIELD" WHERE field-id("ID", 21) LIMIT 1 [90022-197]

Thanks for your help.

This is mys specs : 
- Browser : Firefox 64.0beta
- Your operating system: Ubuntu 16
- Your databases: Mysql
- Metabase version: 0.31.1
- Metabase hosting environment: Docker
- Metabase internal database: default

**Comment by brainsbucket** [comment] 2018-11-30 14:32
I have seen that if you click on the title of the card to see it in detail, it work as expected : 
![working_detail](https://user-images.githubusercontent.com/4415399/49295010-e9e21a80-f4b4-11e8-8979-fbfa25083a58.png)

**Comment by camsaul** [comment] 2018-11-30 22:21
Duplicate of #8837

**Closed by camsaul** 2018-11-30 22:21 UTC
