### ISSUE TITLE
Hidden column on dashboard does not work in click behavior 

### ISSUE THREAD

**Issue by vasekjares** [metabase/metabase#16305] opened 2021-06-01 11:56 UTC
**Describe the bug**
A hidden column in a dashboard can be used as a value for a dashboard filter in click behavior but does not populate the filter. (see attached GIF)
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/1984178/120319285-2343ad00-c2e1-11eb-99b8-a845e4dd2312.gif)

**To Reproduce**
1. Setup click behavior on dashboard widget to fill up a dashboard filter by one of the columns of the widget
2. Hide the column on the dashboard
3. Try the click behavior - it **will not** populate the filter
4. Unhide the column and try again - it **will** populate the filter

**Expected behavior**
Even hidden columns should be working in click behavior (or should not be possible to be configured for that)

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: https://www.whatsmybrowser.org/b/17UPX
- Your databases: Postgres
- Metabase version: v0.39.0.1

**Severity**
Low severity - has workaround (columns can be left visible)

**Comment by flamber** [comment] 2021-06-01 14:31
Duplicate of #13927

**Closed by flamber** 2021-06-01 14:31 UTC
Labels: .Needs Triage, Type:Bug
