### ISSUE TITLE
Field filter - direct query to another table/view

### ISSUE THREAD

**Issue by rciszynski** [metabase/metabase#17330] opened 2021-08-05 09:49 UTC
**Is your feature request related to a problem? Please describe.**

Currently, for field filters to work, the most convenient way to use reports is SQL views, which do not need to be efficient. When we have a lot of such data sources in Metabase, it takes a lot of time to synchronize the list of values on a daily basis. In the case of a large number of values, searching in filters also takes a long time.

**Describe the solution you'd like**
It would be useful to be able to get a list of values from a SQL query / specified column in a different table than those contained in the query.

**Additional context**
This will improve performance if you use the data from the dictionary table directly in the filter instead of the column in the view. Very often, several dictionary tables are common for a very large number of queries.

**Comment by flamber** [comment] 2021-08-05 10:27
Duplicate of #5245/#6820

**Closed by flamber** 2021-08-05 10:27 UTC
Labels: .Needs Triage, Type:New Feature
