### ISSUE TITLE
Show loading indicator while export request is processing

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#16971] opened 2021-07-09 22:53 UTC
Currently when you click the button to export a table to CSV/JSON/XLSX, the UI doesn't change at all, so it's not clear whether the request is being processed until the browser's download dialogue appears (sometimes after quite a bit of time). We should show a spinner or some other kind of loading indicator to show that the request was received.

**Comment by flamber** [comment] 2021-07-10 09:21
Duplicate of #10566

**Closed by flamber** 2021-07-10 09:21 UTC
Labels: .Needs Triage, Type:New Feature
