### ISSUE TITLE
Metabase query settings on postgres read slave

### ISSUE THREAD

**Issue by nickcarenza** [metabase/metabase#3730] opened 2016-11-04 23:24 UTC
I have Metabase connected to a postgres slave so queries are run in readonly mode. I see a lot of errors in the logs of it trying to run `UPDATE pg_settings SET setting = $1 WHERE name ILIKE 'timezone'`. The postgres documentation says

>The view pg_settings provides access to run-time parameters of the server. It is essentially an alternative interface to the SHOW and SET commands. It also provides access to some facts about each parameter that are not directly available from SHOW, such as minimum and maximum values.

Alternatively, the SET command allows you to specify SESSION or LOCAL so that it can actually take affect in a readonly transaction.

> SET [ SESSION | LOCAL ] configuration_parameter { TO | = } { value | 'value' | DEFAULT }
SET [ SESSION | LOCAL ] TIME ZONE { timezone | LOCAL | DEFAULT }

I would imagine it to be pretty common to have Metabase connected to readonly slaves. The actual errors I am seeing in the logs are:

> 2016-11-04 22:56:54 UTC [21333-1] user@db ERROR:  cannot execute SELECT in a read-only transaction
2016-11-04 22:56:54 UTC [21333-2] user@db STATEMENT:  UPDATE pg_settings SET setting = $1 WHERE name ILIKE 'timezone'
2016-11-04 22:56:54 UTC [21333-3] user@db ERROR:  current transaction is aborted, commands ignored until end of transaction block
2016-11-04 22:56:54 UTC [21333-4] user@db STATEMENT:  SELECT NULL AS TABLE_CAT, n.nspname AS TABLE_SCHEM, c.relname AS TABLE_NAME,  CASE n.nspname ~ '^pg_' OR n.nspname = 'information_schema'  WHEN true THEN CASE  WHEN n.nspname = 'pg_catalog' OR n.nspname = 'information_schema' THEN CASE c.relkind   WHEN 'r' THEN 'SYSTEM TABLE'   WHEN 'v' THEN 'SYSTEM VIEW'   WHEN 'i' THEN 'SYSTEM INDEX'   ELSE NULL   END  WHEN n.nspname = 'pg_toast' THEN CASE c.relkind   WHEN 'r' THEN 'SYSTEM TOAST TABLE'   WHEN 'i' THEN 'SYSTEM TOAST INDEX'   ELSE NULL   END  ELSE CASE c.relkind   WHEN 'r' THEN 'TEMPORARY TABLE'   WHEN 'i' THEN 'TEMPORARY INDEX'   WHEN 'S' THEN 'TEMPORARY SEQUENCE'   WHEN 'v' THEN 'TEMPORARY VIEW'   ELSE NULL   END  END  WHEN false THEN CASE c.relkind  WHEN 'r' THEN 'TABLE'  WHEN 'i' THEN 'INDEX'  WHEN 'S' THEN 'SEQUENCE'  WHEN 'v' THEN 'VIEW'  WHEN 'c' THEN 'TYPE'  WHEN 'f' THEN 'FOREIGN TABLE'  WHEN 'm' THEN 'MATERIALIZED VIEW'  ELSE NULL  END  ELSE NULL  END  AS TABLE_TYPE, d.description AS REMARKS  FROM pg_catalog.pg_namespace n, pg_catalog.pg_class c  LEFT JOIN pg_catalog.pg_description d ON (c.oid = d.objoid AND d.objsubid = 0)  LEFT JOIN pg_catalog.pg_class dc ON (d.classoid=dc.oid AND dc.relname='pg_class')  LEFT JOIN pg_catalog.pg_namespace dn ON (dn.oid=dc.relnamespace AND dn.nspname='pg_catalog')  WHERE c.relnamespace = n.oid  AND c.relname LIKE 'PROBABLYNOT' AND (false  OR ( c.relkind = 'r' AND n.nspname !~ '^pg_' AND n.nspname <> 'information_schema' ) )  ORDER BY TABLE_TYPE,TABLE_SCHEM,TABLE_NAME

I don't know if this error is causing timezone issues by not taking effect the way it is expected to.

**Comment by camsaul** [comment] 2016-11-04 23:38
Hi @nickcarenza, we already have an open issue for this, #1699.

`SET SESSION TIME ZONE ...` sounds like it might be a better way to set the timezone if it works on readonly connections, I'll take a look at that 👍 

Closing as duplicate of #1699

**Closed by camsaul** 2016-11-04 23:38 UTC
