### ISSUE TITLE
iFrame, Public embed, 401 (Unauthorized)

### ISSUE THREAD

**Issue by MixMe** [metabase/metabase#5269] opened 2017-06-05 13:54 UTC
If you have drop down list(Category filter) on iframe, and you are no login on metabase app in any browser tab, then you give 401 (Unauthorized)
![screenshot from 2017-06-05 16-49-17](https://cloud.githubusercontent.com/assets/3535911/26786534/a4539e36-4a0f-11e7-89c7-c52bc175655a.png)

**Comment by attekei** [comment] 2017-08-30 19:30
I think that this is a duplicate of #5060 and was resolved in #5349.

**Closed by attekei** 2017-08-30 19:30 UTC
Labels: Bug, Embedding, Parameters/Variables, Priority/P1
