### ISSUE TITLE
Incorrect graphing when generating a bar chart

### ISSUE THREAD

**Issue by okaeiz** [metabase/metabase#28838] opened 2023-03-02 13:38 UTC
**Describe the bug**
I have a table that I have sorted descendingly and the 3rd and 4th records are equal in numbers but their bars are not the same in size.

**Expected behavior**
I expect two equal numbers to be equal sizewise.

**Screenshots/videos**
![cap1](https://user-images.githubusercontent.com/100111649/222444091-bad74b84-02c5-43ef-99b7-0852cb10d2de.PNG)
![cap2](https://user-images.githubusercontent.com/100111649/222444116-f2911986-53f8-4a19-a45d-d5009cb61d93.PNG)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.15.0-60-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-01-27",
      "tag": "v0.45.2.1",
      "branch": "release-x.45.2.x",
      "hash": "1a59de7"
    },
    "settings": {
      "report-timezone": "Asia/Tehran"
    }
  }
}

**Severity**
This malfunctioning can cause problems because we need exact and correct graphs and charts.

**Comment by paoliniluis** [comment] 2023-03-02 14:41
Thanks! is this a chart? or an email subscription? can you reproduce with the sample dataset?

by the way, you seem to be running Metabase with the embedded H2 application database. That database can suffer corruptions and you'll lose everything you did, please consider moving to Postgres or MySQL for the application database

**Comment by alxnddr** [comment] 2024-06-11 16:29
@okaeiz thanks for the report. We've reworked charts in v50 so there is a high change the issue has been fixed. Could you please have a look if your chart works now? I was not able to reproduce it

**Comment by cdeweyx** [comment] 2024-07-23 16:27
Also unable to reproduce on v50 — Closing this for now.

**Closed by cdeweyx** 2024-07-23 16:27 UTC
Labels: Type:Bug, Priority:P2, Visualization/, .Frontend, .Team/DashViz, .Needs Clarification, .Possibly Already Fixed
