### ISSUE TITLE
Dashboard cards' add data modal should display nested collections

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8122] opened 2018-07-22 00:45 UTC
Currently the add data modal shows a flat list of saved questions that are compatible with the current question. It should probably instead show a list of collections and allow you to navigate through them to pick a compatible saved question.

<img width="1036" alt="screen shot 2018-07-20 at 3 59 19 pm" src="https://user-images.githubusercontent.com/2223916/43041204-e991ce0e-8d26-11e8-8de2-e355afb5292a.png">

**Comment by flamber** [comment] 2020-06-29 16:02
Duplicate of #4202

**Closed by flamber** 2020-06-29 16:02 UTC
Labels: Organization/Collections, Type:UX
