### ISSUE TITLE
Clicking "Add series to breakout" crashes the visualisation options editor

### ISSUE THREAD

**Issue by romeovs** [metabase/metabase#49523] opened 2024-11-05 09:10 UTC
### Describe the bug

Introduced in https://github.com/metabase/metabase/pull/48265
Related to https://github.com/metabase/metabase/issues/49529

The viz settings editor crashes when selecting `Add series to breakout` for specific query.

This happens on `master` at 518e79b8fb292ba17b402042b05ccdfb64b30ad6. 

https://github.com/user-attachments/assets/b47c0d3d-9d66-4d8a-804f-babc1a3005be

### To Reproduce

To reproduce:

1. New > Question > Orders > Visualize
3. Visualize or Save the question
4. Pick any visualization that allows breakouts (Row, Bar, Line, ...)
5. In the viz settings, for the X-Axis (or Y-axis, depending on the viz type) pick `main_group`.
6. Click `Add series breakout`

❌ The viz settings editor crashes
❌ The problem persists after reloading the page

The following error is displayed in the browser console:

```
TypeError: transformedSeries is undefined
    getHidden graph.js:173
    getSettingWidget settings.js:150
    getSettingsWidgets settings.js:189
    getSettingsWidgets settings.js:189
    getSettingsWidgetsForSeries visualization.js:118
    widgets QuestionChartSettings.tsx:22
    React 3
    QuestionChartSettings QuestionChartSettings.tsx:22
```

coming from [ChartSettingSeriesOrder.tsx#L83](https://github.com/metabase/metabase/blob/9b4d3d2b2ebb24975ed8a673f86e15d9417d1215/frontend/src/metabase/visualizations/components/settings/ChartSettingSeriesOrder.tsx#L83).

### Expected behavior

The viz editor should not crash and allow me to pick `sub_group` as a breakout.

### Logs

Labelled it as P1 because there is no workaround. It might be limited to this pathological SQL query however, so feel free to bump the priority down.

### Information about your Metabase installation

<details>

<summary>Installation Details</summary>

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "run-mode": "dev",
    "plan-alias": "",
    "version": {
      "date": "2024-11-04",
      "src_hash": "cc7c5fadd76698e2f7a64d1eafd541abbdc5698e",
      "tag": "v1.2.0-SNAPSHOT",
      "hash": "516f03f"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Mac OS X",
    "os.version": "14.6.1",
    "user.language": "en",
    "user.timezone": "Australia/Melbourne"
  }
}
```

</details>

### Severity

P1

**Comment by ranquild** [comment] 2024-11-05 14:38
Most likely caused by recent SDK-related changes

**Comment by cdeweyx** [comment] 2024-11-21 21:41
Closing as dupe of https://github.com/metabase/metabase/issues/49529

**Comment by cdeweyx** [comment] 2024-11-21 21:42
Closing as dupe of https://github.com/metabase/metabase/issues/49529

**Closed by cdeweyx** 2024-11-21 21:42 UTC
Labels: Type:Bug, Priority:P1, Visualization/Chart Settings, .Frontend, .Regression/master, .Team/DashViz
