### ISSUE TITLE
Proposal. Permissions. Control download permissions for embedding dashboards (allow , not allow). 

### ISSUE THREAD

**Issue by jlisyc** [metabase/metabase#10153] opened 2019-06-13 11:40 UTC
### Proposal. Permissions. Control download permissions for embedding dashboards (allow , not allow). 

![image](https://user-images.githubusercontent.com/33416503/59429686-9431e780-8de0-11e9-969f-a58d9bd44639.png)

Thanks for Metabase project!
-------

**Comment by jlisyc** [comment] 2019-06-13 11:40
Related https://github.com/metabase/metabase/issues/9264

**Comment by flamber** [comment] 2019-06-13 17:43
Looks like a duplicate of #6369

**Closed** 2020-05-15 11:30 UTC
Labels: Administration/Permissions, Embedding/, Type:New Feature
