### ISSUE TITLE
Numeric input fields accept and pass a list of comma separated numbers

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#36569] opened 2023-12-08 10:12 UTC
### Describe the bug

A numeric input field will accept numbers separated by commas and passes them as a list of numbers to a native query.

### To Reproduce

1. Create a native query: `select {{ var1 }}`
2. Set the type of `var1` to Number 
3. In the input field enter numbers separated by commas, for instance _1,2.3,3_ , and run the query
4. (!) The query runs, despite the value entered is not a number - and an incorrect, multi-column result will be returned
<img width="715" alt="image" src="https://github.com/metabase/metabase/assets/11080638/2b9c4c89-ac2f-453b-ac01-0299a52a0298">

### Expected behavior

Since the input is not a number, the query should not run, and an appropriate error should be returned instead..

### Information about your Metabase installation

```JSON
1.47.8
```

### Severity

Probably minor, I found this accidentally

### Additional context

The same problem also happens with numeric filters on dashboards, if they are linked to a native question. 
Select table visualization for the question to demonstrate it.

**Comment by nemanjaglumac** [comment] 2024-01-26 14:22
Duplicate of https://github.com/metabase/metabase/issues/15295

**Closed by nemanjaglumac** 2024-01-26 14:22 UTC
Labels: Type:Bug, Querying/Parameters & Variables, Querying/Native, .Needs Triage
