### ISSUE TITLE
MySQL DB over SSH : `com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure`

### ISSUE THREAD

**Issue by incyclum** [metabase/metabase#5277] opened 2017-06-06 08:44 UTC
Hi all,

I'm having an error while trying to connect to a distant MySQL DB over SSH. I get a red message when I click on Save.

> No matching clause: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

My configuration is :
- MySQL 5.5.46 on a distant server
- Metabase 0.24.1 running in a Docker container

I found https://stackoverflow.com/a/2985169, but it doesn't help much for my case. I don't know what
else to try.

Thank you :+1:

**Comment by mivbeard** [comment] 2017-06-09 21:26
I have the same error. Please help

**Comment by camsaul** [comment] 2017-06-09 21:38
Closing as duplicate of #3941

**Closed by camsaul** 2017-06-09 21:38 UTC
