### ISSUE TITLE
Feature request: UI support of multiline log text

### ISSUE THREAD

**Issue by runminlook** [metabase/metabase#14253] opened 2021-01-05 08:31 UTC
**Is your feature request related to a problem? Please describe.**

I use metabase for viewing text log. It's great!
But for too long text and multiline text, it is unfriendly.

**Describe the solution you'd like**

When click, pop up a dialog to show the detail data.
Or use multiline to show one row.

**Describe alternatives you've considered**

**How important is this feature to you?**
Note: the more honest and specific you are here the more we will take you seriously. 
Very important!

**Additional context**

**Comment by flamber** [comment] 2021-01-05 11:00
Duplicate of #10372/#6826/#6178

**Closed by flamber** 2021-01-05 11:00 UTC
Labels: .Needs Triage, Type:New Feature
