### ISSUE TITLE
Allow added series to be of different measure types. Share only x-axis.

### ISSUE THREAD

**Issue by adjenks** [metabase/metabase#22301] opened 2022-04-29 21:46 UTC
**Is your feature request related to a problem? Please describe.**
I have a multi line chart and a stacked bar chart, and I would like to plot them both on the same time x-axis. The "Add Series" feature almost accomplishes this, however the stacked bars become unstacked and it also assumes that the data is of the same measure type, so the Y-Axis is labelled the same on both sides.

**Describe the solution you'd like**
I would like to be able to combine two charts that share the same x-axis, but have two entirely different Y axis, and would like it to preserve the chart types if one is bar and the other is line.

**Describe alternatives you've considered**
I could simply show the two graphs separately, but I would like an easier visual comparison with them right on top of each other.

**How important is this feature to you?**
Fairly important, because competing software offers this ability and it will be harder to make a case to switch to Metabase if we can't do most of the same things that we are already doing.

**Additional context**

Pardon all the censoring. I tried to combine this:

![image](https://user-images.githubusercontent.com/10687569/166072560-e27b54eb-8cac-4f91-be41-243d42f4bc9c.png)

With this:

![image](https://user-images.githubusercontent.com/10687569/166072647-205a8f93-ef45-49bd-8cf1-a95a0691998c.png)

But I got this:

![image](https://user-images.githubusercontent.com/10687569/166073068-7defd6a5-cf2d-485f-b110-01726aa4eab5.png)

As you can see, I cannot stack the bar chart anymore, and also both the axis say "test", because I wanted to see if they could be edited independently, but the labels are linked together.

If there is already an issue open for this, please direct me to it, I could not find it. Thank you.

**Comment by flamber** [comment] 2022-04-30 08:41
Duplicate of #12008

**Closed by flamber** 2022-04-30 08:41 UTC
Labels: Type:New Feature, .Needs Triage
