### ISSUE TITLE
Migration from H2 > MySQL fails

### ISSUE THREAD

**Issue by JAC2703** [metabase/metabase#7952] opened 2018-06-28 08:28 UTC
Looks like a bug:

- Your browser and the version: N/ A
- Your operating system: N/ A
- Your databases: MySql 8.0.11
- Metabase version: 29.3
- Metabase hosting environment: Docker, Ubuntu 16.04
- Metabase internal database: H2 > Mysql 8.0.11

- *Repeatable steps to reproduce the issue*
Migrating to MySql after creating a couple of dashboards. 
Set env variables as follows:
```
export MB_DB_TYPE=mysql
export MB_DB_DBNAME=metabase_dev
export MB_DB_PORT=3306
export MB_DB_USER=metabase_dev
export MB_DB_PASS=xxx
export MB_DB_HOST=xxx
```

Then run the migration command as per the wiki:
`java -jar metabase.jar load-from-h2 /metabase.db/metabase.db`

Results in a java stack:
```
bash-4.3# java -jar metabase.jar load-from-h2 /metabase.db/metabase.db
06-28 08:22:32 INFO metabase.util :: Loading Metabase...
06-28 08:22:41 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓
See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
06-28 08:22:57 INFO metabase.db :: Verifying mysql Database Connection ...
06-28 08:22:57 INFO metabase.db :: Verify Database Connection ...  ✅
06-28 08:22:57 INFO metabase.db :: Running Database Migrations...
Thu Jun 28 08:22:57 GMT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
06-28 08:22:57 INFO metabase.db :: Setting up Liquibase...
Thu Jun 28 08:22:58 GMT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
06-28 08:22:58 INFO metabase.db :: Liquibase is ready.
06-28 08:22:58 INFO metabase.db :: Checking if Database has unrun migrations...
06-28 08:23:02 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
06-28 08:23:02 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
06-28 08:23:02 INFO metabase.db :: Database has unrun migrations. Waiting for migration lock to be cleared...
06-28 08:23:02 INFO metabase.db :: Migration lock is cleared. Running migrations...
06-28 08:23:03 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
06-28 08:23:03 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'admin BIT(1) NOT NULL, user_id INT NOT NULL, organization_id INT NOT NULL, CONST' at line 1
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
        at clojure.java.jdbc$db_do_execute_prepared_statement$fn__1839.invoke(jdbc.clj:952)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:784)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:724)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:951)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:945)
        at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:983)
        at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:963)
        at clojure.java.jdbc$execute_BANG_$execute_helper__1910.invoke(jdbc.clj:1364)
        at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1366)
        at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1337)
        at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1356)
        at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1337)
        at metabase.db$migrate_up_if_needed_BANG_.invokeStatic(db.clj:169)
        at metabase.db$migrate_up_if_needed_BANG_.invoke(db.clj:155)
        at metabase.db$migrate_BANG_$fn__4418.invoke(db.clj:258)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:741)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:776)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:724)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
        at metabase.db$migrate_BANG_.invokeStatic(db.clj:246)
        at metabase.db$migrate_BANG_.invoke(db.clj:227)
        at metabase.db$run_schema_migrations_BANG_.invokeStatic(db.clj:381)
        at metabase.db$run_schema_migrations_BANG_.invoke(db.clj:376)
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:399)
        at metabase.db$setup_db_BANG_.doInvoke(db.clj:392)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:221)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:215)
        at clojure.lang.Var.invoke(Var.java:379)
        at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:36)
        at metabase.cmd$load_from_h2.invoke(cmd.clj:29)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.core$apply.invoke(core.clj:641)
        at metabase.cmd$run_cmd$fn__38501.invoke(cmd.clj:132)
        at metabase.cmd$run_cmd.invokeStatic(cmd.clj:132)
        at metabase.cmd$run_cmd.invoke(cmd.clj:128)
        at clojure.lang.Var.invoke(Var.java:383)
        at metabase.core$run_cmd.invokeStatic(core.clj:269)
        at metabase.core$run_cmd.invoke(core.clj:267)
        at metabase.core$_main.invokeStatic(core.clj:278)
        at metabase.core$_main.doInvoke(core.clj:274)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at metabase.core.main(Unknown Source)
Command failed with exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'admin BIT(1) NOT NULL, user_id INT NOT NULL, organization_id INT NOT NULL, CONST' at line 1
```

**Comment by jornh** [comment] 2018-06-28 16:51
Duplicate of https://github.com/metabase/metabase/issues/7596

MySQL 8 migration is not possible yet. Either drop back to MySQL 5 or manually apply workaround steps in discourse topic referenced in OP of #7596

**Comment by salsakran** [comment] 2018-07-06 05:21
closing since it's a dupe as @jornh helpfully pointed out

**Closed by salsakran** 2018-07-06 05:21 UTC
