### ISSUE TITLE
Improve organization of FK target field dropdown

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3260] opened 2016-08-23 18:05 UTC
If you have a lot of primary keys in a database, it can be brutal scrolling down to find it.

We should provide a better organization structure and/or a search widget.

**Comment by tlrobinson** [comment] 2016-08-23 18:12
As part of this we should explore supporting joins across multiple tables #1173 

IIRC the QP already supports it, it's just not exposed on the frontend.

**Comment by mazameli** [comment] 2019-10-11 23:42
Pretty sure this is a dupe of https://github.com/metabase/metabase/issues/2805

**Closed by mazameli** 2019-10-11 23:42 UTC
Labels: .Duplicate, Admin Panel & Setup, Type:UX
