### ISSUE TITLE
date_trunc displays hour as 24:00 in table view

### ISSUE THREAD

**Issue by dah33** [metabase/metabase#14599] opened 2021-02-01 09:29 UTC
Run this query

```
SELECT date_trunc('day','2021-02-01 09:30:11'::datetime) as created_at, 2.0 as score
UNION ALL
SELECT date_trunc('day','2021-01-31 13:21:01'::datetime), 3.0
```

In the table you see:

![image](https://user-images.githubusercontent.com/17231347/106439384-86c2e880-646f-11eb-8e46-43e12c1d948a.png)

I would expect either no timestamp to be shown, or "00:00".
```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.198-152.320.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-12-03",
      "tag": "v0.37.3",
      "branch": "release-x.37.x",
      "hash": "2f1e783"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2021-02-01 10:42
Duplicate of #5859/#9538

**Closed by flamber** 2021-02-01 10:42 UTC
Labels: .Needs Triage, Type:Bug
