### ISSUE TITLE
Appytown is failing on question 6

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#44127] opened 2024-06-13 13:07 UTC
### Describe the bug

Our Appytown demo has a failing question:
https://appytown.metabase.com/

In https://appytown.metabaseapp.com/api/public/dashboard/ea8c2738-2518-422f-b497-d21d5418a166/dashcard/4/card/6?parameters=%5B%7B%22type%22%3A%22string%2F%3D%22%2C%22value%22%3Anull%2C%22id%22%3A%22531be19c%22%2C%22target%22%3A%5B%22dimension%22%2C%5B%22field%22%2C1267%2Cnull%5D%5D%7D%2C%7B%22type%22%3A%22string%2F%3D%22%2C%22value%22%3Anull%2C%22id%22%3A%2226c7f5a8%22%2C%22target%22%3A%5B%22dimension%22%2C%5B%22field%22%2C1268%2Cnull%5D%5D%7D%5D

it returns:
```
{
    "status": "failed",
    "error": "An error occurred while running the query.",
    "error_type": "invalid-query"
}
```

### To Reproduce

1) go to https://appytown.metabase.com/
2) see the dashboard

### Expected behavior

Questions should work

### Logs

NA

### Information about your Metabase installation

```JSON
v50.3
```

### Severity

P1

**Comment by bshepherdson** [comment] 2024-06-14 12:01
The big link is broken (at least for me), and I can't see any errors now on loading the main page [https://appytown.metabase.com/](https://appytown.metabase.com/).

I also don't see any requests for question 6 - has it been removed to prevent the error from bringing down the whole dashboard? If so, where can I see that query and trigger the error?

I do see `org.eclipse.jetty.io.EofException`s while streaming query results in the logs from around when this issue was raised. But the error log indicates that it was executing question 5, which is now working (the stacked bar chart of top-earning developers). I actually still see the same error logs now, even though that question is working.

**Comment by paoliniluis** [comment] 2024-06-14 12:19
@bshepherdson the question is now removed, if you access the instance you will be able to see it

**Comment by bshepherdson** [comment] 2024-06-14 14:26
Okay, I have visibility now.

This is failing to validate the query because the argument to `:sum` isn't returning a number. That's wrong; it's clearly a numeric column (1266, weekly active users) and all the metadata agrees it's `:type/BigInteger`.

I'm going to try reproducing this locally with a similar CSV upload, model and query.

**Comment by bshepherdson** [comment] 2024-06-14 14:49
I can't reproduce this directly. Also if I duplicate the query on the Appytown instance, it works fine.

Looking at those two queries, the obvious difference is that the original broken one uses `[:sum [:field 1266 {...}]]` and the new working one uses `[:sum [:field "weekly_active_users" {...}]]`. The latter (using the model's column names rather than Field IDs) is what I'd expect to see for queries against a model.

Hypothesis: This `Apps` model used to be either a saved question, or a direct table reference, and then its source was changed to the model, but the refs stayed broken.

I'll see if I can reproduce it like that.

**Comment by bshepherdson** [comment] 2024-06-14 14:58
No repro with those two paths.

- Changing the data source from the table to the model dropped everything from the rest of the query; the rebuilt aggregation used a correct ref.
- Starting with a SQ and then turning that into a model did keep the ID refs, but the query still works. So that probably was the path but it doesn't repro locally.

Without a repro on master, I'm not sure what else to say here. I think dropping that aggregation and replacing it will fix the Appytown question, and if that doesn't work then a duplicate of the query works fine.

**Comment by bshepherdson** [comment] 2024-07-02 15:50
@paoliniluis This one is sort of ambiguous. I suspect it was fixed by something like #44418, but I'm not certain of that.

Is it worth debugging further, or should we just duplicate the question and move on?

**Comment by paoliniluis** [comment] 2024-07-03 20:27
Duplicating the query doesn't work, recreating does the trick

there are some major differences between the old question and recreating this in 50:
v50:
```
{
    "cache_invalidated_at": null,
    "description": null,
    "archived": false,
    "view_count": 1,
    "collection_position": null,
    "table_id": 54,
    "can_run_adhoc_query": true,
    "result_metadata": [
        {
            "description": "The team who developed it.",
            "semantic_type": "type/Category",
            "name": "developer",
            "field_ref": [
                "field",
                "developer",
                {
                    "base-type": "type/Text"
                }
            ],
            "effective_type": "type/Text",
            "id": 1267,
            "visibility_type": "normal",
            "display_name": "Developer",
            "fingerprint": {
                "global": {
                    "distinct-count": 10,
                    "nil%": 0
                },
                "type": {
                    "type/Text": {
                        "percent-json": 0,
                        "percent-url": 0,
                        "percent-email": 0,
                        "percent-state": 0,
                        "average-length": 12.4
                    }
                }
            },
            "base_type": "type/Text"
        },
        {
            "display_name": "Sum of Weekly Active Users",
            "semantic_type": "type/Quantity",
            "field_ref": [
                "aggregation",
                0
            ],
            "name": "sum",
            "base_type": "type/Decimal",
            "effective_type": "type/Decimal",
            "fingerprint": {
                "global": {
                    "distinct-count": 10,
                    "nil%": 0
                },
                "type": {
                    "type/Number": {
                        "min": 190,
                        "q1": 321,
                        "q3": 3155,
                        "max": 4803,
                        "sd": 1704.2764805694592,
                        "avg": 1419.9
                    }
                }
            }
        }
    ],
    "creator": {
        "email": "dahyei@metabase.com",
        "first_name": "Dahyei ",
        "last_login": "2024-07-03T17:43:05.874549Z",
        "is_qbnewb": false,
        "is_superuser": true,
        "id": 35,
        "last_name": "Kim",
        "date_joined": "2024-03-15T18:49:38.326395Z",
        "common_name": "Dahyei  Kim"
    },
    "initially_published_at": null,
    "can_write": true,
    "database_id": 2,
    "enable_embedding": false,
    "collection_id": null,
    "query_type": "query",
    "name": "Luis test",
    "last_query_start": null,
    "dashboard_count": 0,
    "last_used_at": null,
    "type": "question",
    "average_query_time": null,
    "creator_id": 35,
    "moderation_reviews": [],
    "updated_at": "2024-07-03T17:58:55.346292Z",
    "made_public_by_id": null,
    "embedding_params": null,
    "cache_ttl": null,
    "dataset_query": {
        "database": 2,
        "type": "query",
        "query": {
            "aggregation": [
                [
                    "sum",
                    [
                        "field",
                        "weekly_active_users",
                        {
                            "base-type": "type/BigInteger"
                        }
                    ]
                ]
            ],
            "breakout": [
                [
                    "field",
                    "developer",
                    {
                        "base-type": "type/Text"
                    }
                ]
            ],
            "order-by": [
                [
                    "desc",
                    [
                        "aggregation",
                        0
                    ]
                ]
            ],
            "source-table": "card__1"
        }
    },
    "id": 142,
    "parameter_mappings": [],
    "display": "bar",
    "entity_id": "Js2m-6kDEWUJ2pBfp033c",
    "collection_preview": true,
    "last-edit-info": {
        "id": 35,
        "email": "xxxxxx@metabase.com",
        "first_name": "xxxx ",
        "last_name": "xxxx",
        "timestamp": "2024-07-03T17:58:55.35857Z"
    },
    "visualization_settings": {
        "graph.dimensions": [
            "developer"
        ],
        "graph.metrics": [
            "sum"
        ]
    },
    "collection": {
        "metabase.models.collection.root/is-root?": true,
        "authority_level": null,
        "name": "Our analytics",
        "is_personal": false,
        "id": "root",
        "can_write": true
    },
    "metabase_version": "v1.50.3 (855535b)",
    "parameters": [],
    "created_at": "2024-07-03T17:58:55.346292Z",
    "parameter_usage_count": 0,
    "public_uuid": null
}
```

version unknown:
```
{
    "cache_invalidated_at": null,
    "description": "How many weekly active users a developer has across all their apps.",
    "archived": false,
    "view_count": 18419,
    "collection_position": null,
    "table_id": 54,
    "can_run_adhoc_query": true,
    "result_metadata": [
        {
            "description": "The team who developed it.",
            "semantic_type": "type/Category",
            "table_id": 54,
            "coercion_strategy": null,
            "name": "developer",
            "settings": null,
            "source": "breakout",
            "fk_target_field_id": null,
            "field_ref": [
                "field",
                1267,
                {
                    "base-type": "type/Text"
                }
            ],
            "effective_type": "type/Text",
            "nfc_path": null,
            "parent_id": null,
            "id": 1267,
            "position": 5,
            "visibility_type": "normal",
            "display_name": "Developer",
            "fingerprint": {
                "global": {
                    "distinct-count": 10,
                    "nil%": 0.0
                },
                "type": {
                    "type/Text": {
                        "percent-json": 0.0,
                        "percent-url": 0.0,
                        "percent-email": 0.0,
                        "percent-state": 0.0,
                        "average-length": 12.4
                    }
                }
            },
            "base_type": "type/Text"
        },
        {
            "settings": null,
            "semantic_type": null,
            "base_type": "type/BigInteger",
            "name": "sum",
            "display_name": "Sum of Weekly Active Users",
            "source": "aggregation",
            "field_ref": [
                "aggregation",
                0
            ],
            "aggregation_index": 0
        }
    ],
    "creator": {
        "email": "xxxxxx@metabase.com",
        "first_name": "Alex",
        "last_login": "2024-03-15T18:41:26.21811Z",
        "is_qbnewb": false,
        "is_superuser": true,
        "id": 2,
        "last_name": "xxxxx",
        "date_joined": "2023-06-30T21:37:03.441437Z",
        "common_name": "xxxxx"
    },
    "initially_published_at": null,
    "can_write": true,
    "database_id": 2,
    "enable_embedding": false,
    "collection_id": null,
    "query_type": "query",
    "name": "Weekly Active Users by Developer",
    "last_query_start": "2024-06-13T12:34:57.927862Z",
    "dashboard_count": 0,
    "last_used_at": null,
    "type": "question",
    "average_query_time": 71.3750725825733511,
    "creator_id": 2,
    "moderation_reviews": [],
    "updated_at": "2024-05-28T18:29:20.074683Z",
    "made_public_by_id": null,
    "embedding_params": null,
    "cache_ttl": null,
    "dataset_query": {
        "database": 2,
        "type": "query",
        "query": {
            "aggregation": [
                [
                    "sum",
                    [
                        "field",
                        1266,
                        {
                            "base-type": "type/BigInteger"
                        }
                    ]
                ]
            ],
            "breakout": [
                [
                    "field",
                    1267,
                    {
                        "base-type": "type/Text"
                    }
                ]
            ],
            "order-by": [
                [
                    "desc",
                    [
                        "aggregation",
                        0
                    ]
                ]
            ],
            "source-table": "card__1"
        }
    },
    "id": 6,
    "parameter_mappings": [],
    "display": "bar",
    "entity_id": "WVNMC7Oqmq_L3aphXN7hC",
    "collection_preview": true,
    "last-edit-info": {
        "id": 34,
        "email": "xxxxxx@metabase.com",
        "first_name": "xxxxx",
        "last_name": "xxxxx",
        "timestamp": "2024-05-28T18:29:20.140203Z"
    },
    "visualization_settings": {
        "graph.dimensions": [
            "developer"
        ],
        "series_settings": {
            "sum": {
                "color": "#F2A86F"
            }
        },
        "graph.metrics": [
            "sum"
        ]
    },
    "collection": {
        "metabase.models.collection.root/is-root?": true,
        "authority_level": null,
        "name": "Our analytics",
        "is_personal": false,
        "id": "root",
        "can_write": true
    },
    "metabase_version": null,
    "parameters": [],
    "created_at": "2023-07-05T18:28:56.80812Z",
    "parameter_usage_count": 0,
    "public_uuid": null
}
```

so in order to reproduce this we need for sure to create the card in a very old version and then move to v50

**Comment by snoe** [comment] 2024-07-18 19:51
@paoliniluis 

So this happening because the "Weekly Active Users" Field has an `effective-type` of `type/Text` and base-type of `type/BigInteger` Fingerprinting is also still marked as `type/Text`. The aggregation blows up because it's picking this up due to the field id being used rather than the field name we use if we rebuild the query.

This data seems to have come from a spreadsheet, I wonder if it was initially imported as a Text and switched to integer later. The other way it gets set is if a coersion strategy was (incorrectly) allowed to be set on the int field and then switched off - but that should go back to base-type.

This should be fixable in appytown by setting a coercion on the table and setting it back. I'd also think that sync should solve it but we'd need to see logs.

![Image](https://github.com/user-attachments/assets/062ed1ac-2ba4-4af2-b3bf-7964cda1370d)

**Comment by snoe** [comment] 2024-07-18 20:07
Spoke with @paoliniluis  and this is ok to close

**Closed by snoe** 2024-07-18 20:07 UTC
Labels: Type:Bug, Priority:P1, Reporting/Dashboards, Querying/Processor, .Backend, .Regression, .Team/QueryProcessor

**Comment by Somtom** [comment] 2024-07-23 05:46
Might be related to #45938
