### ISSUE TITLE
Wrong legend on a multi-series graph on dashboard.

### ISSUE THREAD

**Issue by nkanish2002** [metabase/metabase#3616] opened 2016-10-18 11:54 UTC
Hi, I just setup a metebase server for my company and connected it with our MySQL DB. While creating **multi-series graphs**, one of the analysts discovered a bug in the rendering of a multi-series graph as shown in the images below.

## On load screen

![how it ought to be](https://cloud.githubusercontent.com/assets/3245911/19476496/2a57635a-9557-11e6-9161-ac853b0b2b32.png)

## On rendered screen

![how it is](https://cloud.githubusercontent.com/assets/3245911/19476506/3872fcf6-9557-11e6-88fb-744d191bc660.png)

He followed the steps provided in the User guide. Please help us. 

We are planning to use metabase for analysing our data since it supports MongoDB as well as MySQL. 

Thank you.

**Comment by tlrobinson** [comment] 2016-10-18 12:41
Thank you. Duplicate of #3545, will be fixed in 0.20.1 shortly.

**Closed by tlrobinson** 2016-10-18 12:41 UTC
