### ISSUE TITLE
Column format sidebar is blank for primary/foreign keys, when non-table visualization is selected

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#17000] opened 2021-07-12 23:20 UTC
**To Reproduce**
1. Go to any table
2. Change visualization type any non-table visualization, like a line or bar chart
3. Click toggle at bottom to see table view
4. Open column format settings sidebar for any primary or foreign key column

**Logs**
In the browser console:
```
column is missing field_ref 
Object { name: "x", base_type: "type/Integer" }
```

**Expected behavior**
Should show the expected format setting options.

**Screenshots**

https://user-images.githubusercontent.com/32746338/125367302-bf26f680-e32c-11eb-88de-d80ba37e34ac.mov

**Information about your Metabase Installation:**

Current master (v40) on Firefox 89.0.2 on macOS Big Sur

**Comment by flamber** [comment] 2021-07-13 10:19
Duplicate of #14401

**Closed by flamber** 2021-07-13 10:19 UTC
Labels: .Needs Triage, Type:Bug
