### ISSUE TITLE
Redirect to homepage from Metabase Logo no longer working

### ISSUE THREAD

**Issue by gvisniuc** [metabase/metabase#10254] opened 2019-06-26 09:21 UTC
Hi there,

Recently I have upgraded from version **0.32.8** to **0.32.9** and have been getting the following error (image below) when clicking the top left Metabase logo to go to the homepage.
It's of course nothing critical but thought I would at least create an issue for awareness.

![Screenshot 2019-06-26 at 11 15 42](https://user-images.githubusercontent.com/1614747/60167872-4071c600-9804-11e9-8bf7-cc574e2045eb.png)

Thanks!

Your browser and the version: Chrome 75.x (but also tested in Safari and Firefox)
Your operating system: macOS Mojave
Metabase version: 0.32.9
Metabase hosting environment: Official Metabase Docker image running in Kubernetes.
Metabase internal database: AWS RDS Postgres

⬇️ Please click the 👍 reaction instead of leaving a +1 or 👍 comment

**Comment by flamber** [comment] 2019-06-26 10:00
Hi @gvisniuc 
Do you see any other errors earlier? Besides `Cannot read property '_currentElement' of null`
I cannot reproduce your issue on any browser.

**Comment by gvisniuc** [comment] 2019-06-26 11:12
Hi @flamber ,

Yes, I see this error when the page is loading.

![image](https://user-images.githubusercontent.com/1614747/60175476-fb559000-9813-11e9-9a03-bf56bb7ed701.png)

**Comment by flamber** [comment] 2019-06-26 11:15
That was fixed yesterday - it will be included in next release. See issue #10191 for work-around.

**Comment by gvisniuc** [comment] 2019-06-26 11:16
Hi @flamber,

Yes I see this error when the page is loading.

![image](https://user-images.githubusercontent.com/1614747/60175682-8a62a800-9814-11e9-84f8-b1b9ee5abfef.png)

**Comment by gvisniuc** [comment] 2019-06-26 11:17
@flamber Thank you for the solution. Will do.

**Comment by flamber** [comment] 2019-06-26 11:17
Please close this issue.

**Closed** 2019-06-26 11:22 UTC
Labels: Bug
