### ISSUE TITLE
Filters missing for string(K)

### ISSUE THREAD

**Issue by cl-juni** [metabase/metabase#50022] opened 2024-11-14 11:12 UTC
### Describe the bug

Strings have a lot of filters ![Image](https://github.com/user-attachments/assets/63ffa1eb-845f-40bf-adbe-0ceb31b6155a)
Strings with a fixed-length, like string(255), string(40) etc only have 2 filters ![Image](https://github.com/user-attachments/assets/eecd2c83-e136-4c68-b601-64c1fba6a9c1)

I don't know if this matters but the source here is BigQuery

### To Reproduce

1. Go to a view through the Browse -> Databases -> Select a database -> Select a dataset -> Select a table
2. Click on the arrow on a string (or string(255)) column name, click on "filter by this column".
3. Strings will have a lot of filter options, string(255) will only have "empty" or "not empty"

### Expected behavior

String and string(255) (and string(40 etc)) should have the same filter options

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk",
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-self-hosted",
    "version": {
      "date": "2024-10-23",
      "tag": "v1.51.1",
      "hash": "b8178a8"
    },
    "settings": {
      "report-timezone": "UTC"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.16"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "6.5.0-1024-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

annoying

**Comment by snoe** [comment] 2024-11-14 16:14
This is a duplicate of https://github.com/metabase/metabase/issues/49786 fixed in 51.3

**Closed by snoe** 2024-11-14 16:14 UTC
Labels: Type:Bug, Priority:P2, Database/BigQuery, Querying/Parameters & Variables, .Team/Querying
