### ISSUE TITLE
SAML Identity Provider URL and Certificate fields don't validate properly

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#25666] opened 2022-09-27 21:46 UTC
**Describe the bug**
These two fields don't seem to correctly validate values, preventing the form from being submitted.

**To Reproduce**
1. Run Metabase EE with a valid token with the `sso` feature enabled
2. Go to Admin -> Settings -> Authentication -> SAML
3. Put in arbitrary values for the `SAML Identity Provider URL` and `SAML Identity Provider Certificate` fields, then click out of the fields. (Any values will work, including legitimate values for these fields)
4. The fields should be highlighted in red and say "required" even though they're filled in. The "Save Changes` button at the bottom should also be grayed out.

**Expected behavior**
The form should correctly detect that these fields have values and allow submission.

**Screenshots**
![image](https://user-images.githubusercontent.com/32746338/192641410-4a21a3ee-340a-432e-b8f4-a4b8a275b138.png)

**Information about your Metabase Installation:**
Current master; doesn't repro on 44.0

**Severity**
P1? Completely blocks setting up SAML

**Comment by flamber** [comment] 2022-09-28 08:47
Duplicate of #24738

**Closed by flamber** 2022-09-28 08:47 UTC
Labels: Type:Bug, .Needs Triage
