### ISSUE TITLE
Unable to filter by some searchable fields

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#38702] opened 2024-02-13 11:06 UTC
### Describe the bug

https://metaboat.slack.com/archives/C05MPF0TM3L/p1707822061007859

### To Reproduce

https://metaboat.slack.com/archives/C05MPF0TM3L/p1707822061007859

### Expected behavior

The search endpoint should return an empty array instead of 204 no content

### Information about your Metabase installation

```JSON
-
```

### Severity

P1

**Comment by calherries** [comment] 2024-02-14 12:07
Dupe of https://github.com/metabase/metabase/issues/37492

**Closed by calherries** 2024-02-14 12:07 UTC
Labels: Type:Bug, Priority:P1, .Backend, .Team/BackendComponents
