### ISSUE TITLE
Datetimes display on UI and backend do not match when there are timezone differences

### ISSUE THREAD

**Issue by eiternme** [metabase/metabase#18781] opened 2021-11-01 15:07 UTC
**Describe the bug**
When I performed an "on date" filter using custom question, I kept receiving results from the day after what I wanted to filter for. It appears that the generated SQL is offsetting due to timezone differences.

**To Reproduce**

I am unsure how to reproduce the first step for this problem as I do not know how timezones are set or handled in databases/Metabase. Here is the best I can come up with:

1. 
    a. Have different timezone for Metabase and database where timezone for accessing Metabase is behind timezone of database (e.g. db timezone of UTC and user time zone of EST)
    b. Have a dataset where column of datetimes have varied dates but times at 12:00 AM
2. Custom question > Use mentioned dataset from 1b > Filter on any date
3. The date that is displayed on UI does not match date displayed in filter (see screenshot below for example). It appears that the generated SQL offsets for this timezone difference

*Example screenshot:*
![image](https://user-images.githubusercontent.com/91676712/139686798-3cc2efda-5314-4d6c-833d-9938df135aa7.png)

*Generated SQL:*
```
SELECT 
    [...]
FROM
    [...]
WHERE 
    [...]
    AND "source"."Pick Ticket (User Defined) - Pick Ticket No__date_order_shipped" >= DateTimeOffsetFromParts(2021, 10, 28, 0, 0, 0, 0, -4, 0, 7)
    AND "source"."Pick Ticket (User Defined) - Pick Ticket No__date_order_shipped" < DateTimeOffsetFromParts(2021, 10, 29, 0, 0, 0, 0, -4, 0, 7))
```

**Expected behavior**
Metabase should filter based on the displayed times instead of quietly offsetting for timezone differences

**Information about your Metabase Installation:**

* Your browser and the version: Chrome (Latest)
* Your operating system: Windows Version 21H1 (OS Build 19043.1288)
* Your databases: Microsoft SQL Server 2019 (RTM-CU12) (KB5004524) - 15.0.4153.1 (X64)
* Metabase version: 0.41.1 (Latest)
* Metabase hosting environment: Jar-file on Windows
* Metabase internal database: H2 (default)

<details><summary>Diagnostic information</summary>

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9-Ubuntu-0ubuntu2.20.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9-Ubuntu-0ubuntu2.20.04",
    "os.name": "Linux",
    "os.version": "5.10.16.3-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlserver",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-10-21",
      "tag": "v0.41.1",
      "branch": "release-x.41.x",
      "hash": "76aa4a5"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

</details>

**Severity**
Low-medium as this is an obvious bug an end user will see, but can also be overlooked.

**Comment by flamber** [comment] 2021-11-01 15:20
Timezones are complicated. Have a look here: https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html
You can change Reporting Timezone in Admin > Settings > Localization.
Looks like a duplicate of #10824, so closing as such.

**Closed by flamber** 2021-11-01 15:20 UTC
Labels: Type:Bug, .Needs Triage
