### ISSUE TITLE
OpenGraph tags for public embeds

### ISSUE THREAD

**Issue by heliostatic** [metabase/metabase#5146] opened 2017-05-19 17:19 UTC
With the addition of publicly embeddable charts and dashboards, I've started passing around links to more of those entities in Slack and other tools.

It would be great to have opengraph meta tags (http://ogp.me/) for those entities, so that people I share with have context about what is being shared.

**Comment by flamber** [comment] 2019-02-15 04:40
Duplicate of #3374

**Closed** 2020-05-27 11:24 UTC
Labels: .Proposal, Reporting/Dashboards, Type:Question
