### ISSUE TITLE
Reporting timezone isn't consistent in multi-instance deployments

### ISSUE THREAD

**Issue by dsmegha** [metabase/metabase#4282] opened 2017-02-01 13:09 UTC
The time stamp on the database is not consistent and is fluctuating.

I have a query running 
SELECT current_timestamp
from XXX
Where ID ='YYY'
limit 1

This is giving me inconsistent time. I am getting both the below time as a result. It changes randomly when I refresh.

Wednesday, February 1, 2017 6:23 PM
Wednesday, February 1, 2017 11:55 PM

Also the current_time is giving the following result.

SELECT current_time
from XXX
Where ID ='YYY'
limit 1

Thursday, January 1, 1970 6:28 PM

My browser : Chrome Version 55.0.2883.95 (64-bit)
OS : maxOS 10.12.2
Database : MySQL 5.7
Metabase version: 22.0
Metabase hosting environment:  Elastic Beanstalk
Metabase internal database : MySQL

The Timezone of my Metabase is Asia/Calcutta.
We also tried this with the Databae Default time which is GMT. The issue still existed.
<img width="1297" alt="screen shot 2017-02-01 at 6 35 15 pm" src="https://cloud.githubusercontent.com/assets/13366094/22507849/67ffdd78-e8ad-11e6-9f47-ba0dbf2392e7.png">
![Uploading Screen Shot 2017-02-01 at 6.33.30 PM.png…]()
![Uploading Screen Shot 2017-02-01 at 6.31.38 PM.png…]()

**Comment by dsmegha** [comment] 2017-02-01 16:58
<img width="1314" alt="screen shot 2017-02-01 at 6 33 30 pm" src="https://cloud.githubusercontent.com/assets/13366094/22517010/b5833890-e8cd-11e6-97e3-26d53b03255c.png">
<img width="1373" alt="screen shot 2017-02-01 at 6 31 38 pm" src="https://cloud.githubusercontent.com/assets/13366094/22517011/b58dcada-e8cd-11e6-954c-09265e38943b.png">

**Comment by salsakran** [comment] 2017-02-01 23:46
Can you look into elastic beanstalk and see how many instances are running? Is it possible there are 2? I have no idea what in our code path would exhibit this behaviour.

**Comment by dsmegha** [comment] 2017-02-02 07:46
Hi Sameer,

Yes there are 2 instances running since we need to loadbalance. Ideally
that should not cause this right?

And the current_time is showing Thursday, January 1, 1970 6:44 PM even when
we have only one instance running.

Thanks,
Megha

**Comment by camsaul** [comment] 2017-02-02 19:14
Hi @dsmegha, we don't yet support running multiple Metabase servers for the purposes of load-balancing. You can always use a larger instance if you need to scale up but for most people a single smaller instance is enough.

**Comment by salsakran** [comment] 2017-02-02 19:18
@dsmegha the reason I ask, is that the only hypothesis I have for how the same query returns two different times in that the two servers have different timezones set.

**Comment by salsakran** [comment] 2017-02-02 19:21
it's possible that our reporting timezone setting is behaving differently on a second server due to caching as well. But in any event, the only scenario that leads to the behaviour you're seeing was multiple servers, so I'm glad you confirmed that and I'm not going crazy.

Can you list:
1. your database timezone
2. your reporting timezone
3. the server timezones for each instance
4. your client timezone

I'd be curious to figure out exactly where a second timezone is leaking in.

**Comment by camsaul** [comment] 2017-02-02 19:36
@sameer the problem is that one of the servers has the reporting timezone set and the other doesn't

**Comment by salsakran** [comment] 2017-02-02 19:51
to elaborate further @dsmegha --

Out settings framework (which we use for reporting timezones, among other things) is predicated on a single server installation. A number of things also work this way.

Our current scaling model is to scale vertically. In general the server is pretty efficient and to the best of my knowledge, most people are able to run BI for a 100 person company on a medium or a large without too much hassle. The data warehouse is almost always the bottleneck, and aside from configuration mishaps (eg, jetty threadpool a while back), the app server is pretty chill.

Our HA story is fast recovery (it takes a few minutes for beanstalk to respawn a dead instance).

**Comment by salsakran** [comment] 2019-10-11 22:51
closing since we now have a consistent settings framework across instances and have for a year or more.

**Closed by salsakran** 2019-10-11 22:51 UTC
Labels: .Limitation, Misc/Timezones, Operation/
