### ISSUE TITLE
Dashboard subscription failing to bind parameter

### ISSUE THREAD

**Issue by mustafashabib** [metabase/metabase#15373] opened 2021-03-29 14:41 UTC
**Describe the bug**
A dashboard with native query powered widgets containing a field filter of type date range renders properly but the subscription fails with the "An error occurred while displaying this card" message (both email and slack subscriptions).

**Logs**
```logs
[356cac36-e1f0-4b61-ae49-3cd873588c22] 2021-03-29T09:24:52-05:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: null
{:database_id 2,
 :started_at #t "2021-03-29T10:24:48.034309-04:00[US/Eastern]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Unable to substitute parameters",
   :stacktrace
   ["--> driver.sql.parameters.substitute$substitute$fn__79134.invoke(substitute.clj:83)"
    "driver.sql.parameters.substitute$substitute.invokeStatic(substitute.clj:80)"
    "driver.sql.parameters.substitute$substitute.invoke(substitute.clj:71)"
    "driver.sql$fn__79167.invokeStatic(sql.clj:44)"
    "driver.sql$fn__79167.invoke(sql.clj:40)"
    "query_processor.middleware.parameters.native$expand_inner.invokeStatic(native.clj:39)"
    "query_processor.middleware.parameters.native$expand_inner.invoke(native.clj:30)"
    "query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:50)"
    "query_processor.middleware.parameters$expand_one.invoke(parameters.clj:41)"
    "query_processor.middleware.parameters$expand_all$replace_47083__47084.invoke(parameters.clj:59)"
    "mbql.util.match$replace_in_collection$iter__17913__17917$fn__17918.invoke(match.clj:139)"
    "mbql.util.match$replace_in_collection.invokeStatic(match.clj:138)"
    "mbql.util.match$replace_in_collection.invoke(match.clj:133)"
    "query_processor.middleware.parameters$expand_all$replace_47083__47084.invoke(parameters.clj:59)"
    "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:59)"
    "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)"
    "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:56)"
    "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)"
    "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:77)"
    "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:73)"
    "query_processor.middleware.parameters$fn__47099$substitute_parameters_STAR___47104$fn__47105.invoke(parameters.clj:82)"
    "query_processor.middleware.parameters$fn__47099$substitute_parameters_STAR___47104.invoke(parameters.clj:79)"
    "query_processor.middleware.parameters$substitute_parameters$fn__47125.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45488.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__46102.invoke(expand_macros.clj:155)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44267.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__48127.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47351$fn__47355.invoke(resolve_database_and_driver.clj:31)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47351.invoke(resolve_database_and_driver.clj:25)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46342.invoke(fetch_source_query.clj:274)"
    "query_processor.middleware.store$initialize_store$fn__48136$fn__48137.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__48136.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__48198.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__46468.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44123.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__48112.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__45723.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__47214.invoke(process_userland_query.clj:135)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__45666.invoke(catch_exceptions.clj:173)"
    "query_processor.reducible$async_qp$qp_STAR___37431$thunk__37432.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___37431.invoke(reducible.clj:109)"
    "query_processor.reducible$async_qp$qp_STAR___37431.invoke(reducible.clj:96)"
    "query_processor.reducible$sync_qp$qp_STAR___37440$fn__37441.invoke(reducible.clj:131)"
    "query_processor.reducible$sync_qp$qp_STAR___37440.invoke(reducible.clj:130)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:237)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:233)"
    "query_processor$fn__48244$process_query_and_save_execution_BANG___48253$fn__48254.invoke(query_processor.clj:246)"
    "query_processor$fn__48244$process_query_and_save_execution_BANG___48253.invoke(query_processor.clj:241)"
    "query_processor$fn__48288$process_query_and_save_with_max_results_constraints_BANG___48297$fn__48298.invoke(query_processor.clj:258)"
    "query_processor$fn__48288$process_query_and_save_with_max_results_constraints_BANG___48297.invoke(query_processor.clj:254)"
    "pulse$execute_dashboard_subscription_card$fn__70434$fn__70435.doInvoke(pulse.clj:76)"
    "api.card$run_query_for_card_async.invokeStatic(card.clj:619)"
    "api.card$run_query_for_card_async.doInvoke(card.clj:594)"
    "pulse$execute_dashboard_subscription_card$fn__70434.invoke(pulse.clj:69)"
    "server.middleware.session$do_with_current_user.invokeStatic(session.clj:258)"
    "server.middleware.session$do_with_current_user.invoke(session.clj:250)"
    "pulse$execute_dashboard_subscription_card.invokeStatic(pulse.clj:68)"
    "pulse$execute_dashboard_subscription_card.invoke(pulse.clj:57)"
    "pulse$execute_dashboard$iter__70446__70450$fn__70451$fn__70452.invoke(pulse.clj:88)"
    "pulse$execute_dashboard$iter__70446__70450$fn__70451.invoke(pulse.clj:87)"
    "pulse$fn__70570.invokeStatic(pulse.clj:217)"
    "pulse$fn__70570.invoke(pulse.clj:212)"
    "pulse$results__GT_notifications$iter__70602__70606$fn__70607.invoke(pulse.clj:265)"
    "pulse$send_notifications_BANG_.invokeStatic(pulse.clj:307)"
    "pulse$send_notifications_BANG_.invoke(pulse.clj:306)"
    "pulse$send_pulse_BANG_.invokeStatic(pulse.clj:333)"
    "pulse$send_pulse_BANG_.doInvoke(pulse.clj:315)"
    "api.pulse$fn__71132.invokeStatic(pulse.clj:212)"
    "api.pulse$fn__71132.invoke(pulse.clj:201)"
    "server.middleware.auth$enforce_authentication$fn__73874.invoke(auth.clj:14)"
    "api.routes$fn__73995$fn__73997.invoke(routes.clj:69)"
    "server.routes$fn__76228$fn__76229.doInvoke(routes.clj:57)"
    "server.routes$fn__76216$fn__76218.invoke(routes.clj:41)"
    "server.middleware.exceptions$catch_uncaught_exceptions$fn__73986.invoke(exceptions.clj:96)"
    "server.middleware.exceptions$catch_api_exceptions$fn__73983.invoke(exceptions.clj:84)"
    "server.middleware.log$log_api_call$fn__76144$fn__76145.invoke(log.clj:195)"
    "server.middleware.log$log_api_call$fn__76144.invoke(log.clj:189)"
    "server.middleware.security$add_security_headers$fn__73949.invoke(security.clj:142)"
    "server.middleware.json$wrap_json_body$fn__75925.invoke(json.clj:62)"
    "server.middleware.json$wrap_streamed_json_response$fn__75943.invoke(json.clj:98)"
    "server.middleware.misc$maybe_set_site_url$fn__35084.invoke(misc.clj:58)"
    "server.middleware.session$bind_current_user$fn__41955$fn__41956.invoke(session.clj:277)"
    "server.middleware.session$do_with_current_user.invokeStatic(session.clj:258)"
    "server.middleware.session$do_with_current_user.invoke(session.clj:250)"
    "server.middleware.session$bind_current_user$fn__41955.invoke(session.clj:276)"
    "server.middleware.session$wrap_current_user_info$fn__41942.invoke(session.clj:236)"
    "server.middleware.session$wrap_session_id$fn__41928.invoke(session.clj:182)"
    "server.middleware.auth$wrap_api_key$fn__73882.invoke(auth.clj:27)"
    "server.middleware.misc$add_content_type$fn__35067.invoke(misc.clj:27)"
    "server.middleware.misc$disable_streaming_buffering$fn__35092.invoke(misc.clj:75)"
    "server.middleware.misc$bind_request$fn__35095.invoke(misc.clj:92)"
    "server.middleware.ssl$redirect_to_https_middleware$fn__76161.invoke(ssl.clj:48)"
    "server$async_proxy_handler$fn__75758.invoke(server.clj:71)"
    "server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)"],
   :error_type :invalid-query,
   :ex-data
   {:type :schema.core/error,
    :params
    {"created_at"
     (metabase.driver.common.parameters/map->FieldFilter
      {:field
       {:name "created_at", :parent_id nil, :table_id 9, :base_type :type/DateTimeWithLocalTZ, :special_type nil},
       :value
       {:name "Date Filter", :slug "date_filter", :id "affdfed", :type :date/all-options, :default "past8weeks~"}})},
    :parsed-query
    ["with weekly_orders as \n    (select date_part('week', created_at) as order_week, \n    case when date_part('week', created_at) > 52 and date_part('day', created_at) <= 4 then date_part('year', created_at) - 1 else date_part('year', created_at) end as order_year,\n    coalesce(payload->'someFloat', '0.0')::numeric as invoice_amount\n    from event where name = 'EXAMPLE_EVENT'\n    and "
     (param "created_at")
     "\n    order by created_at desc\n    )\n    \nselect order_week::text, order_year::text as order_year, \norder_week || '_' || order_year as week_year, \nsum(invoice_amount) as total_invoiced_amount \nfrom weekly_orders\ngroup by order_year, order_week, week_year\norder by order_year::int  asc, order_week::int asc\n"]}}],
 :error_type :invalid-query,
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :native,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :native
  {:query
   "with weekly_orders as \n    (select date_part('week', created_at) as order_week, \n    case when date_part('week', created_at) > 52 and date_part('day', created_at) <= 4 then date_part('year', created_at) - 1 else date_part('year', created_at) end as order_year,\n    coalesce(payload->'someFloat', '0.0')::numeric as invoice_amount\n    from event where name = 'EXAMPLE_EVENT'\n    and {{created_at}}\n    order by created_at desc\n    )\n    \nselect order_week::text, order_year::text as order_year, \norder_week || '_' || order_year as week_year, \nsum(invoice_amount) as total_invoiced_amount \nfrom weekly_orders\ngroup by order_year, order_week, week_year\norder by order_year::int  asc, order_week::int asc\n",
   :template-tags
   {"created_at"
    {:id "436052ce-2083-3646-8fee-34d7da06413d",
     :name "created_at",
     :display-name "Date range",
     :type :dimension,
     :dimension [:field-id 70],
     :widget-type :date/all-options,
     :default "past8weeks",
     :required true}}},
  :database 2,
  :parameters
  ({:name "Date Filter",
    :slug "date_filter",
    :id "affdfed",
    :type "date/all-options",
    :default "past8weeks~",
    :target [:dimension [:template-tag "created_at"]]}),
  :async? false,
  :cache-ttl nil},
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> driver.common.parameters.dates$fn__46873$date_string__GT_range__46882.invoke(dates.clj:274)"
  "driver.common.parameters.dates$fn__46873$date_string__GT_range__46882$fn__46883.invoke(dates.clj:290)"
  "driver.common.parameters.dates$fn__46873$date_string__GT_range__46882.invoke(dates.clj:274)"
  "driver.sql.parameters.substitution$fn__78906$date_range_field_filter__GT_replacement_snippet_info__78911$fn__78912.invoke(substitution.clj:199)"
  "driver.sql.parameters.substitution$fn__78906$date_range_field_filter__GT_replacement_snippet_info__78911.invoke(substitution.clj:197)"
  "driver.sql.parameters.substitution$fn__78978$field_filter__GT_replacement_snippet_info__78983$fn__78987.invoke(substitution.clj:218)"
  "driver.sql.parameters.substitution$fn__78978$field_filter__GT_replacement_snippet_info__78983.invoke(substitution.clj:213)"
  "driver.sql.parameters.substitution$fn__79058.invokeStatic(substitution.clj:263)"
  "driver.sql.parameters.substitution$fn__79058.invoke(substitution.clj:248)"
  "driver.sql.parameters.substitute$substitute_field_filter.invokeStatic(substitute.clj:14)"
  "driver.sql.parameters.substitute$substitute_field_filter.invoke(substitute.clj:9)"
  "driver.sql.parameters.substitute$substitute_param.invokeStatic(substitute.clj:31)"
  "driver.sql.parameters.substitute$substitute_param.invoke(substitute.clj:25)"
  "driver.sql.parameters.substitute$substitute_STAR_$fn__79125.invoke(substitute.clj:64)"
  "driver.sql.parameters.substitute$substitute_STAR_.invokeStatic(substitute.clj:57)"
  "driver.sql.parameters.substitute$substitute_STAR_.invoke(substitute.clj:54)"
  "driver.sql.parameters.substitute$substitute$fn__79134.invoke(substitute.clj:81)"
  "driver.sql.parameters.substitute$substitute.invokeStatic(substitute.clj:80)"
  "driver.sql.parameters.substitute$substitute.invoke(substitute.clj:71)"
  "driver.sql$fn__79167.invokeStatic(sql.clj:44)"
  "driver.sql$fn__79167.invoke(sql.clj:40)"
  "query_processor.middleware.parameters.native$expand_inner.invokeStatic(native.clj:39)"
  "query_processor.middleware.parameters.native$expand_inner.invoke(native.clj:30)"
  "query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:50)"
  "query_processor.middleware.parameters$expand_one.invoke(parameters.clj:41)"
  "query_processor.middleware.parameters$expand_all$replace_47083__47084.invoke(parameters.clj:59)"
  "mbql.util.match$replace_in_collection$iter__17913__17917$fn__17918.invoke(match.clj:139)"
  "mbql.util.match$replace_in_collection.invokeStatic(match.clj:138)"
  "mbql.util.match$replace_in_collection.invoke(match.clj:133)"
  "query_processor.middleware.parameters$expand_all$replace_47083__47084.invoke(parameters.clj:59)"
  "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:59)"
  "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)"
  "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:56)"
  "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)"
  "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:77)"
  "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:73)"
  "query_processor.middleware.parameters$fn__47099$substitute_parameters_STAR___47104$fn__47105.invoke(parameters.clj:82)"
  "query_processor.middleware.parameters$fn__47099$substitute_parameters_STAR___47104.invoke(parameters.clj:79)"
  "query_processor.middleware.parameters$substitute_parameters$fn__47125.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45488.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__46102.invoke(expand_macros.clj:155)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44267.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__48127.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47351$fn__47355.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47351.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46342.invoke(fetch_source_query.clj:274)"
  "query_processor.middleware.store$initialize_store$fn__48136$fn__48137.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__48136.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__48198.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__46468.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44123.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__48112.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__45723.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__47214.invoke(process_userland_query.clj:135)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__45666.invoke(catch_exceptions.clj:173)"
  "query_processor.reducible$async_qp$qp_STAR___37431$thunk__37432.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___37431.invoke(reducible.clj:109)"
  "query_processor.reducible$async_qp$qp_STAR___37431.invoke(reducible.clj:96)"
  "query_processor.reducible$sync_qp$qp_STAR___37440$fn__37441.invoke(reducible.clj:131)"
  "query_processor.reducible$sync_qp$qp_STAR___37440.invoke(reducible.clj:130)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:237)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:233)"
  "query_processor$fn__48244$process_query_and_save_execution_BANG___48253$fn__48254.invoke(query_processor.clj:246)"
  "query_processor$fn__48244$process_query_and_save_execution_BANG___48253.invoke(query_processor.clj:241)"
  "query_processor$fn__48288$process_query_and_save_with_max_results_constraints_BANG___48297$fn__48298.invoke(query_processor.clj:258)"
  "query_processor$fn__48288$process_query_and_save_with_max_results_constraints_BANG___48297.invoke(query_processor.clj:254)"
  "pulse$execute_dashboard_subscription_card$fn__70434$fn__70435.doInvoke(pulse.clj:76)"
  "api.card$run_query_for_card_async.invokeStatic(card.clj:619)"
  "api.card$run_query_for_card_async.doInvoke(card.clj:594)"
  "pulse$execute_dashboard_subscription_card$fn__70434.invoke(pulse.clj:69)"
  "server.middleware.session$do_with_current_user.invokeStatic(session.clj:258)"
  "server.middleware.session$do_with_current_user.invoke(session.clj:250)"
  "pulse$execute_dashboard_subscription_card.invokeStatic(pulse.clj:68)"
  "pulse$execute_dashboard_subscription_card.invoke(pulse.clj:57)"
  "pulse$execute_dashboard$iter__70446__70450$fn__70451$fn__70452.invoke(pulse.clj:88)"
  "pulse$execute_dashboard$iter__70446__70450$fn__70451.invoke(pulse.clj:87)"
  "pulse$fn__70570.invokeStatic(pulse.clj:217)"
  "pulse$fn__70570.invoke(pulse.clj:212)"
  "pulse$results__GT_notifications$iter__70602__70606$fn__70607.invoke(pulse.clj:265)"
  "pulse$send_notifications_BANG_.invokeStatic(pulse.clj:307)"
  "pulse$send_notifications_BANG_.invoke(pulse.clj:306)"
  "pulse$send_pulse_BANG_.invokeStatic(pulse.clj:333)"
  "pulse$send_pulse_BANG_.doInvoke(pulse.clj:315)"
  "api.pulse$fn__71132.invokeStatic(pulse.clj:212)"
  "api.pulse$fn__71132.invoke(pulse.clj:201)"
  "server.middleware.auth$enforce_authentication$fn__73874.invoke(auth.clj:14)"
  "api.routes$fn__73995$fn__73997.invoke(routes.clj:69)"
  "server.routes$fn__76228$fn__76229.doInvoke(routes.clj:57)"
  "server.routes$fn__76216$fn__76218.invoke(routes.clj:41)"
  "server.middleware.exceptions$catch_uncaught_exceptions$fn__73986.invoke(exceptions.clj:96)"
  "server.middleware.exceptions$catch_api_exceptions$fn__73983.invoke(exceptions.clj:84)"
  "server.middleware.log$log_api_call$fn__76144$fn__76145.invoke(log.clj:195)"
  "server.middleware.log$log_api_call$fn__76144.invoke(log.clj:189)"
  "server.middleware.security$add_security_headers$fn__73949.invoke(security.clj:142)"
  "server.middleware.json$wrap_json_body$fn__75925.invoke(json.clj:62)"
  "server.middleware.json$wrap_streamed_json_response$fn__75943.invoke(json.clj:98)"
  "server.middleware.misc$maybe_set_site_url$fn__35084.invoke(misc.clj:58)"
  "server.middleware.session$bind_current_user$fn__41955$fn__41956.invoke(session.clj:277)"
  "server.middleware.session$do_with_current_user.invokeStatic(session.clj:258)"
  "server.middleware.session$do_with_current_user.invoke(session.clj:250)"
  "server.middleware.session$bind_current_user$fn__41955.invoke(session.clj:276)"
  "server.middleware.session$wrap_current_user_info$fn__41942.invoke(session.clj:236)"
  "server.middleware.session$wrap_session_id$fn__41928.invoke(session.clj:182)"
  "server.middleware.auth$wrap_api_key$fn__73882.invoke(auth.clj:27)"
  "server.middleware.misc$add_content_type$fn__35067.invoke(misc.clj:27)"
  "server.middleware.misc$disable_streaming_buffering$fn__35092.invoke(misc.clj:75)"
  "server.middleware.misc$bind_request$fn__35095.invoke(misc.clj:92)"
  "server.middleware.ssl$redirect_to_https_middleware$fn__76161.invoke(ssl.clj:48)"
  "server$async_proxy_handler$fn__75758.invoke(server.clj:71)"
  "server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)"],
 :context :pulse,
 :error
 "Input to date-string->range does not match schema: \n\n\t   [(named (not (instance? java.lang.String nil)) date-string) nil]  \n\n",
 :row_count 0,
 :running_time 0,
 :ex-data
 {:type :schema.core/error, :value [nil nil], :error [(named (not (instance? java.lang.String nil)) date-string) nil]},
 :data {:rows [], :cols []}}

```

**To Reproduce**
1. Create a dashboard containing a query similar to the one I've written (native query, field filter of type date range bound to a datetime column)
2. Subscribe to it
3. Note the error

**Expected behavior**
Expect to receive the subscription data with the graph's or a table of the data populated.

**Screenshots**

NA

**Severity**

Annoying 

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-us",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  }
}
```

**Comment by flamber** [comment] 2021-03-29 14:56
Duplicate of #15067

**Closed by flamber** 2021-03-29 14:56 UTC
