### ISSUE TITLE
(Updated) Add Ability to Differentiate Between Y-Axis Using Min/Max Limit (on cards)

### ISSUE THREAD

**Issue by GiacchinoCinque** [metabase/metabase#17936] opened 2021-09-16 23:21 UTC
Hi there,

This is an updated version of the initial request with the appropriate labels.

I was using a bar chart to create a graph that showed two different series of data on the same chart (one a bar, the other a line - created from a SQL question). I noticed that when I use "auto-y-axis-range", it works fine (shows series 1 on the left y axis and series 2 on the right, bar and line charts respectively).

However, when I try to manually set a max limit on the y-axis for series 1, it doesn't seem to be able to differentiate between the two series and just ends up combining them. Is it possible to add the ability to manually edit the y-axis max/min for a certain series.

series 1 range 0-2400
series 2 range 0-1 (0-100%)

**Comment by flamber** [comment] 2021-09-17 08:07
Duplicate of #3897

**Closed by flamber** 2021-09-17 08:07 UTC
Labels: Type:New Feature, .Needs Triage
