### ISSUE TITLE
Pick smarter default columns for SQL visualizations

### ISSUE THREAD

**Issue by timabe** [metabase/metabase#3870] opened 2016-12-05 23:14 UTC
This might be a bug but also might just be due to the way metabase expects data to be formatted.

Using an SQL query. Example with the Sample Dataset

`
SELECT p.CATEGORY, r.RATING , COUNT(1) as cnt 
FROM 
PRODUCTS p JOIN REVIEWS r ON p.ID = r.PRODUCT_ID
GROUP BY p.CATEGORY, r.RATING;
`
Returns this table
![table_output](https://cloud.githubusercontent.com/assets/1427277/20906040/23e90b62-bafb-11e6-895c-070233dbba6c.png)

I converted it to bar chart. Without getting into what I assumed it would display, here's what it did display

![bar_chart_output](https://cloud.githubusercontent.com/assets/1427277/20906338/67fc19c4-bafc-11e6-8dd7-d7573214c7bd.png)

The legend shows Rating and Cnt as blue and green, respectively. But the bars in the chart are measuring the SUM of the ratings column (1+2+3+4+5=15) for the Blue bar and the SUM of the count of the ratings as the green bar.

I was expecting to see the Categories on the X axis and different bars for each value of rating (1,2,3,4 and 5) with the height of the bar proportional to the count of the ratings.

**Comment by tlrobinson** [comment] 2016-12-08 20:22
@timabe First of all, is it just the tooltip that's wrong, or is the entire chart not what you expected?

There are a couple things going on.

It's sometimes difficult for Metabase to guess what your intentions are, especially for SQL queries, since we don't know the structure of the query (vs. our query builder, which we do). In this case it looks like we assumed the first column was the dimension and the subsequent 2 columns are metrics, but you probably wanted to use the first two columns as dimensions and the 3rd as the metric. You can adjust this in the chart settings (the gear icon):

![screenshot 2016-12-08 12 12 47](https://cloud.githubusercontent.com/assets/18193/21026032/b55d879e-bd3f-11e6-9063-03c3f56bb2a3.png)

As for the summing behavior, for legacy reasons we sum unaggregated columns when charting them, though this definitely isn't the intended way to to use Metabase. We recently added a warning indicator when this is happening:

![screenshot 2016-12-08 12 18 29](https://cloud.githubusercontent.com/assets/18193/21026208/7b88a566-bd40-11e6-8d29-306fd474a081.png)

One possible improvement would be to detect the unaggregated column when automatically picking the dimension/metrics, and use it as a dimension instead of a metric.

**Comment by tlrobinson** [comment] 2016-12-08 20:24
Also now I'm not sure the text in that tooltip makes sense...

**Comment by flamber** [comment] 2021-11-07 13:37
Closing, since I cannot reproduce on 0.41.1 - tooltips was fixed in 0.39.1 #11907, and auto-viz shows a table by default.
![image](https://user-images.githubusercontent.com/1447303/140647358-35ecc70a-c15b-4823-8cf0-652103a64cbb.png)

**Closed by flamber** 2021-11-07 13:37 UTC
Labels: Visualization/
