### ISSUE TITLE
Unable to scroll SQL error message vertically

### ISSUE THREAD

**Issue by gvwilson** [metabase/metabase#16034] opened 2021-05-13 13:02 UTC
**Describe the bug**

When the SQL error message is taller than the box provided for it, I am unable to scroll vertically to see the whole message.

**To Reproduce**

1. Enlarge text size (for screenshotting/making video/accessibility/just because).
2. Sample dataset.
3. Create new SQL question.
4. Deliberately mangle the SQL a bit.
5. Run.

Error message appears, but I am unable to scroll vertically to view all of it.

**Expected behavior**

I expected a vertical scroll bar so that I could see the whole error message. Note that I have enlarged the log window using the vertical divider as large as it will go and also shrunk it down - no scroll bar either way.

**Screenshots**

![Screen Shot 2021-05-13 at 8 53 32 AM](https://user-images.githubusercontent.com/911566/118129184-dd728380-b3c9-11eb-8882-c37876506f05.png)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_291-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_291",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.291-b10",
    "os.name": "Mac OS X",
    "os.version": "10.16",
    "user.language": "en",
    "user.timezone": "America/Toronto"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "vUNKNOWN",
      "date": "2021-04-30",
      "branch": "master",
      "hash": "8df9d95"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

- Chrome Version 90.0.4430.93 (Official Build) (arm64)
- MacOS 11.2.3 (Big Sur) on M1
- Sample database in H2

**Severity**

Low: makes debugging sessions more difficult.

**Comment by flamber** [comment] 2021-05-13 13:35
Duplicate of #11885

**Closed by flamber** 2021-05-13 13:35 UTC
Labels: .Needs Triage, Type:Bug
