### ISSUE TITLE
Columns getting parsed as timestamps incorrectly

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2379] opened 2016-04-19 20:36 UTC
If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is OS X.
*  I'm running Metabase locally via `lein ring server`
*  My database is H2
*  My Metabase version is 0.17-SNAPSHOT

![out](https://cloud.githubusercontent.com/assets/1455846/14654532/02ae4034-0633-11e6-9839-5092f3d53f7a.gif)

This is just a query against the sample dataset. As seen in the video "Line" is a suggested visualization type, but all of the values of the Y-axis are "1970-01-01". Not sure what's getting parsed as a timestamp but I'm guessing it's one of the non-datetime columns getting parsed as a Unix timestamps for some reason (?).

**Comment by agilliland** [comment] 2016-04-19 23:14
I think this is a dupe of this issue https://github.com/metabase/metabase/issues/2183

The underlying problem is that we don't attempt to do anything particularly clever when you take the raw data from a table and attempt to chart it.

**Comment by camsaul** [comment] 2016-04-19 23:44
It would be one thing if nothing clever happened but it looks like something wrong is happening... either: 

1.  Something is getting parsed as a timestamp that definitely isn't (why?)
2.  The timestamp column is getting parsed incorrectly 

At any rate if this is hard to fix maybe we shouldn't highlight it as one of the suggested visualizations when is produces broken charts?

**Comment by agilliland** [comment] 2016-04-20 00:09
I don't understand what is confusing.  You ran a query which produced output with these columns (in order): Id, Created At, Product Id, Subtotal, ...

When you attempt to chart that all that we do is take the first to columns (Id, Created At) and attempt to use those as the tuples for the charted series.  And the ordering matters, so the first value (Id) is treated as the dimension and placed on the x-axis while the second value (Created At) is treated as the metric and placed on the y-axis.

So that's what you are seeing.  It's not particularly clever for sure, but we've never tried to do anything about the scenario of charting a big table of data that's not organized in any way.

We had this same discussion here https://github.com/metabase/metabase/issues/2183

**Comment by camsaul** [comment] 2016-04-20 00:21
That would make sense if it worked that way, but something is going wrong with `created_at`. Look at the dates in the table visualization... they're all in the 2015-2017 range. Then when I switch to line visualization they're all `1970-01-01`.

![screen shot 2016-04-19 at 5 20 19 pm](https://cloud.githubusercontent.com/assets/1455846/14659697/108e0958-0653-11e6-8f64-8279d00762ac.png)
![screen shot 2016-04-19 at 5 20 14 pm](https://cloud.githubusercontent.com/assets/1455846/14659698/109143b6-0653-11e6-8bc8-626ae2f2b898.png)

**Comment by tlrobinson** [comment] 2016-04-27 20:27
Are we really planning on fixing this in 0.17.0? If so what is the desired fix?

**Comment by camsaul** [comment] 2016-04-27 20:29
I think the desired fix would be for the columns to stop getting parsed incorrectly / stop displaying the wrong data

**Comment by camsaul** [comment] 2016-04-27 20:30
i.e. first we need to diagnose the root cause of the issue then fix it

**Comment by tlrobinson** [comment] 2016-04-27 20:41
It doesn't really make sense to use a date/time as a metric so IMO the correct fix is to not suggest those charts for results that are not `[dimension, metric]`,  `[dimension, metric, metric, ...]`, or `[dimension, dimension, metric]`.

**Comment by camsaul** [comment] 2016-04-27 20:55
Not suggesting a broken chart type is preferable to the status quo but we should at least try to see if we can fix the bug the breaks the chart type. Better to bite the bullet and address the root cause of a bug than to write code to work around it. Interest on tech debt compounds, as they say

**Comment by agilliland** [comment] 2016-04-27 21:00
I'm with Tom here, I don't see this as a bug really because there's no existing intended behavior other than a failure in this case.  As Tom said, we can't do anything when you have a timestamp that you are trying to chart as a metric.

If you want to rename/relabel this as a feature where you get to pick the columns you want to chart from all of the columns in the resulting data then that's fine, but since there is not clear way to fix this then it shouldn't be a bug.

**Comment by tlrobinson** [comment] 2016-04-27 21:01
At some point the charting code tries to convert the date to a number (crossfilter's `reduceSum`, I believe), and the tooltip tries to convert it back to a date. It's an edge case that's not worth fixing because the chart will never make sense.

It does make sense to prevent the user from trying to make choices we know are non-sensical though.

**Comment by camsaul** [comment] 2016-04-27 21:04
@agilliland I'm not really sure how "don't see this as a bug". If my data says "2016-04-27" and it shows up *anywhere* as "1970-01-01" I think that's a bug.

**Comment by tlrobinson** [comment] 2016-04-27 21:11
@camsaul The bug is that we a) suggest an unsuitable chart type for the data, and b) don't show you a friendly error message instead of a broken chart if you select it anyway. That's covered by #2183.

**Comment by salsakran** [comment] 2016-04-27 22:10
Hey - 

In my opinion, the root cause of this is #612 . Strictly speaking, a user wanting to create a line graph of an entire multi-column raw table is non-sensical.

Let's fix that underlying problem, but in the meantime, do #2183 

For situations where someone wants to put a time on the Y-Axis (eg for a scatter plot), we should deal with that gracefully. Let's do that work when we do #645

**Closed** 2016-04-28 18:48 UTC
Labels: Bug, Visualization
