### ISSUE TITLE
MongoDB Native query for grouping on date

### ISSUE THREAD

**Issue by ujjwal-gupta** [metabase/metabase#5127] opened 2017-05-17 04:31 UTC
In order to create a line graph for the average of a field grouped by datetime: by day, query builder can be used. 

![screenshot from 2017-05-17 09-36-40_mod](https://cloud.githubusercontent.com/assets/4945922/26138446/da4f42de-3ae6-11e7-9f41-9fca3aaa729f.png)

However, if we convert the same to a native query, line graphs are not plotted by default and if you go to choose the x-axis as the datetime field, the following message is shown: 

![screenshot from 2017-05-17 09-38-48_mod](https://cloud.githubusercontent.com/assets/4945922/26138450/eb9d2bf0-3ae6-11e7-9b09-66c9a3cfafe2.png)

There is a valid use case for using native query here as I want to use the absolute value "$abs" of the field to average.

PS. Other alternative (like Area) don't work either and in table, the format of dates's changes too. 
Eg: **{"___date":"2017-04-11"}** rather than **April 11, 2017**

Observed on:
- Chrome Version 58.0.3029.81 (64-bit)
- Ubuntu 16.04
- MongoDB
- Metabase version: 0.23.1
- Hosted on Ubuntu
- Metabase internal database: H2 (default)

**Comment by Serfenia** [comment] 2017-05-17 11:17
Hi @ujjwal-gupta,

This is also related to this bug: #4603 
Please upvote the proposal to solve these kind of issues: #4789

**Comment by camsaul** [comment] 2020-05-13 01:42
Duplicate of #4603

**Closed by camsaul** 2020-05-13 01:42 UTC
Labels: Database/Mongo, Priority:P2, Type:Bug, Visualization/
