### ISSUE TITLE
"Column formatting" button broken if sidebar already open for another column

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#16818] opened 2021-06-29 21:45 UTC
**Describe the bug**
When viewing a table, if the column formatting sidebar is open, you can't open the formatting options for another column from the dropdown that opens when you click the column name.

**To Reproduce**
1. View a table
2. Click on a column name to open the dropdown
3. Click on the gear icon to open the formatting options
4. Repeat for a different column

**Screenshots**

https://user-images.githubusercontent.com/32746338/123871359-8167ae00-d8e8-11eb-81ef-7dc4ce250109.mov

(Unrelated, and I know there's a separate issue for this, but that flickering when the sidebar opens is very annoying.)

**Information about your Metabase Installation:**

Current master (`v0.39.5`) on Firefox 89.0.1 on macOS Big Sur

**Comment by flamber** [comment] 2021-06-30 09:18
Duplicate of #16043

**Closed by flamber** 2021-06-30 09:18 UTC
Labels: .Needs Triage, Type:Bug
