### ISSUE TITLE
Activity Permission 

### ISSUE THREAD

**Issue by witwall** [metabase/metabase#5093] opened 2017-05-12 06:56 UTC
How to only show relative activities to the users with limited permission? 

-------

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Chrome 56.0.2924.87
- Your operating system: (e.x. OS X 10, Windows XP, etc)
OS X 10

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Postgres

- Metabase version: (e.x. 0.19.3)
0.24.0

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Windows 2008 R2

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
H2

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by mazameli** [comment] 2017-05-12 18:40
I'm not sure I totally understand your question. Are users seeing items in their activity feed that they don't have permission to view? I tried testing that, both with a question in a locked-down collection, and one outside of a collection but from a DB that the user doesn't have access to, and neither of those items showed up in my test user's activity feed (as expected).

Can you clarify the problem you're seeing, please?

**Comment by witwall** [comment] 2017-05-13 14:54
how about a example, 
user a belongs to group A, then he can only see the activity info created by this group, he even do not know any other activity created by other group.

**Comment by hagen** [comment] 2017-09-08 09:30
Is this a local storage quirk? I've found swapping between accounts without refreshing the browser leads to 'seeing' things that your account shouldn't. Bear in mind that your users won't be logging in and out of admin accounts; just their limited permissions account.

**Comment by camsaul** [comment] 2017-12-07 03:10
@hagen that sounds like a local storage issue for sure. It would probably make sense if we cleared out the local data when you log out. @tlrobinson @attekei can we clear the React store when someone logs out?

**Comment by 2color** [comment] 2018-01-24 14:40
A user without any permissions can see other members who've joined. Is there a way to restrict that type of activity?

A common scenario is when giving an external person access to metabase, he shouldn't be able to see internal activity.

**Comment by hagen** [comment] 2018-01-24 21:07
@2color @camsaul There is also #6184 which is a distinct problem to this one. A user joining is visible to all groups. Resolved with a trigger in Postgres.

**Comment by flamber** [comment] 2020-05-22 17:47
I cannot reproduce on 0.35.3 - think this was fixed in 0.30, with the big Collection change.

**Closed by flamber** 2020-05-22 17:47 UTC
Labels: .Need More Info
