### ISSUE TITLE
Custom fields is not shown when adding groupby columns.

### ISSUE THREAD

**Issue by strong84** [metabase/metabase#6119] opened 2017-10-08 10:58 UTC
Custom fields is now shown when adding groupby columns.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Chrome 61.0.3163.100
- Linux
- MySQL
- Metabase 0.26.1
- Metabase hosting environment: Linux
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

- Repeatable steps to reproduce the issue:
create a custom field, and this field cant be found when adding custom groupby columns.

Thanks for being part of the Metabase project!
-------

**Comment by flamber** [comment] 2019-02-17 22:34
Hi @strong84 
I cannot reproduce your issue on 0.31.2 - can you please test that version?
![image](https://user-images.githubusercontent.com/1447303/52920435-d5eacf80-32d1-11e9-8f66-a1fc7cb69acf.png)

**Comment by mazameli** [comment] 2019-10-24 21:23
Can't reproduce this in 0.33.4 either. Closing since the original bug was reported in 0.26, long ago.

**Closed by mazameli** 2019-10-24 21:23 UTC
Labels: .Limitation, .Query Language (MBQL), Query Builder
