### ISSUE TITLE
Cannot use question with filter on joined column as input to another question

### ISSUE THREAD

**Issue by gvwilson** [metabase/metabase#16107] opened 2021-05-17 14:29 UTC
**Describe the bug**

If Question A does a join and filters by a column in the first table, its result can be used as an input to Question B. If Question A does the same join and filters by a column in the second table, its result *cannot* be used as an input to Question B: it produces a SQL error.

**Logs**

Server log:

```
  "query_processor$fn__49443$process_query_and_save_execution_BANG___49452.invoke(query_processor.clj:243)"
  "query_processor$fn__49487$process_query_and_save_with_max_results_constraints_BANG___49496$fn__49499.invoke(query_processor.clj:263)"
  "query_processor$fn__49487$process_query_and_save_with_max_results_constraints_BANG___49496.invoke(query_processor.clj:256)"
  "api.dataset$run_query_async$fn__55712.invoke(dataset.clj:56)"
  "query_processor.streaming$streaming_response_STAR_$fn__55691$fn__55692.invoke(streaming.clj:72)"
  "query_processor.streaming$streaming_response_STAR_$fn__55691.invoke(streaming.clj:71)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$fn__16071.invoke(streaming_response.clj:84)"],
 :context :ad-hoc,
 :error
 "Parameter \"#1\" is not set; SQL statement:\n-- Metabase:: userID: 1 queryType: native queryHash: 95d4b9e3b4274c2d4903ae3d6505f92b79d454d6afb563091c6f9b68db65ca19\nselect * from (SELECT \"PEOPLE__via__USER_ID\".\"STATE\" AS \"PEOPLE__via__USER_ID__STATE\", count(*) AS \"count\" FROM \"PUBLIC\".\"ORDERS\" LEFT JOIN \"PUBLIC\".\"PRODUCTS\" \"Products\" ON \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" = \"Products\".\"ID\" LEFT JOIN \"PUBLIC\".\"PEOPLE\" \"PEOPLE__via__USER_ID\" ON \"PUBLIC\".\"ORDERS\".\"USER_ID\" = \"PEOPLE__via__USER_ID\".\"ID\" WHERE \"Products\".\"CATEGORY\" = ? GROUP BY \"PEOPLE__via__USER_ID\".\"STATE\" ORDER BY \"PEOPLE__via__USER_ID\".\"STATE\" ASC) [90012-197]",
 :row_count 0,
 :running_time 0,
 :data {:rows [], :cols []}}
```

JavaScript console log

```
app-main.bundle.js?2fcd5d7922659aca83d2:5 error Parameter "#1" is not set; SQL statement:
-- Metabase:: userID: 1 queryType: native queryHash: 95d4b9e3b4274c2d4903ae3d6505f92b79d454d6afb563091c6f9b68db65ca19
select * from (SELECT "PEOPLE__via__USER_ID"."STATE" AS "PEOPLE__via__USER_ID__STATE", count(*) AS "count" FROM "PUBLIC"."ORDERS" LEFT JOIN "PUBLIC"."PRODUCTS" "Products" ON "PUBLIC"."ORDERS"."PRODUCT_ID" = "Products"."ID" LEFT JOIN "PUBLIC"."PEOPLE" "PEOPLE__via__USER_ID" ON "PUBLIC"."ORDERS"."USER_ID" = "PEOPLE__via__USER_ID"."ID" WHERE "Products"."CATEGORY" = ? GROUP BY "PEOPLE__via__USER_ID"."STATE" ORDER BY "PEOPLE__via__USER_ID"."STATE" ASC) [90012-197]
app-main.bundle.js?2fcd5d7922659aca83d2:5 error Parameter "#1" is not set; SQL statement:
-- Metabase:: userID: 1 queryType: native queryHash: 95d4b9e3b4274c2d4903ae3d6505f92b79d454d6afb563091c6f9b68db65ca19
select * from (SELECT "PEOPLE__via__USER_ID"."STATE" AS "PEOPLE__via__USER_ID__STATE", count(*) AS "count" FROM "PUBLIC"."ORDERS" LEFT JOIN "PUBLIC"."PRODUCTS" "Products" ON "PUBLIC"."ORDERS"."PRODUCT_ID" = "Products"."ID" LEFT JOIN "PUBLIC"."PEOPLE" "PEOPLE__via__USER_ID" ON "PUBLIC"."ORDERS"."USER_ID" = "PEOPLE__via__USER_ID"."ID" WHERE "Products"."CATEGORY" = ? GROUP BY "PEOPLE__via__USER_ID"."STATE" ORDER BY "PEOPLE__via__USER_ID"."STATE" ASC) [90012-197]
```

**To Reproduce**

Create a question that joins Orders to Products and counts users by state. (This is question #7 in our case.)
<img width="1031" alt="Screen Shot 2021-05-17 at 10 16 26 AM" src="https://user-images.githubusercontent.com/911566/118505135-24c68000-b6fa-11eb-82eb-b38209def4f3.png">

Output looks like this:
<img width="450" alt="Screen Shot 2021-05-17 at 10 16 39 AM" src="https://user-images.githubusercontent.com/911566/118505181-2e4fe800-b6fa-11eb-95b0-3d3423d297ee.png">

Create a second question that uses the output of the first one as its input - it runs as expected.
<img width="587" alt="Screen Shot 2021-05-17 at 10 16 51 AM" src="https://user-images.githubusercontent.com/911566/118505274-458ed580-b6fa-11eb-8f66-c528ede2792f.png">

Modify the original question to filter by a column in the left-hand table
<img width="679" alt="Screen Shot 2021-05-17 at 10 17 39 AM" src="https://user-images.githubusercontent.com/911566/118505426-62c3a400-b6fa-11eb-9e88-12ef1f599ae6.png">

Second question still works:
<img width="776" alt="Screen Shot 2021-05-17 at 10 17 59 AM" src="https://user-images.githubusercontent.com/911566/118505473-6f47fc80-b6fa-11eb-9196-1701dfbacdf7.png">

Modify the original question to filter by a column in the **second** (right-hand) table instead (removing the previous filter so there's still just one filter):
<img width="691" alt="Screen Shot 2021-05-17 at 10 18 24 AM" src="https://user-images.githubusercontent.com/911566/118505503-7969fb00-b6fa-11eb-8ddb-a5e7ed6fc34d.png">

Second (dependent) question no longer works because of a SQL error:
<img width="1095" alt="Screen Shot 2021-05-17 at 10 18 31 AM" src="https://user-images.githubusercontent.com/911566/118505581-8ab30780-b6fa-11eb-9be6-c80023e4425e.png">

**Expected behavior**

The second (dependent) question should continue to work.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_291-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_291",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.291-b10",
    "os.name": "Mac OS X",
    "os.version": "10.16",
    "user.language": "en",
    "user.timezone": "America/Toronto"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "vUNKNOWN",
      "date": "2021-04-30",
      "branch": "master",
      "hash": "8df9d95"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

- Chrome Version 90.0.4430.93 (Official Build) (arm64)
- MacOS 11.2.3 (Big Sur) on M1
- Sample database in H2

**Severity**

Blocking query construction - I want to filter by a column from each table, so switching the order of tables in the join won't save me.

**Comment by flamber** [comment] 2021-05-17 14:39
Duplicate of #12236

**Closed by flamber** 2021-05-17 14:39 UTC
Labels: .Needs Triage, Type:Bug
