### ISSUE TITLE
If Google Auth is enabled, "Sign in with email" doesn't show error messages

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#16274] opened 2021-05-27 21:23 UTC
If Google Auth is `enabled` using the "Sign in with email" option will redirect you to original sign in page without showing errors if the API returns an error response. I'm seeing this on both `master` (40-SNAPSHOT) and the `release-x.39.x` branch.

1.  Google Auth is enabled. Click "Sign in with email"

![image](https://user-images.githubusercontent.com/1455846/119898535-d7ff5800-bef6-11eb-8b83-f583029baa0a.png)

2. Enter incorrect email and/or password, click "Sign In"

![image](https://user-images.githubusercontent.com/1455846/119898597-e9e0fb00-bef6-11eb-8b77-ff20cecaf58a.png)

3.  API returns a 401 response

   ```json
   {"errors":{"password":"did not match stored password"}}
   ```

4.  FE client immediately redirects back to original login page and error is never displayed

![image](https://user-images.githubusercontent.com/1455846/119898535-d7ff5800-bef6-11eb-8b83-f583029baa0a.png)

I though auth was broken for a minute before I thought to check the Network inspector.

**Comment by camsaul** [comment] 2021-05-27 21:25
This may have something to do with the recent change from 400 to 401 (#13184) for bad auth responses, but I don't know if this was working or not before that PR landed.

**Comment by flamber** [comment] 2021-05-28 07:51
Duplicate of #16122

**Closed by flamber** 2021-05-28 07:51 UTC
Labels: .Needs Triage, Type:Bug
