### ISSUE TITLE
Add specific HH:MM for scheduling the dashboard subscription

### ISSUE THREAD

**Issue by jrca025** [metabase/metabase#24422] opened 2022-07-29 05:31 UTC
I run metabase on a separate server which is alwayson during weekdays but turned off on weekends. However there is a report needed on last day of the month but during weekends, the server is available around 7pm-9pm. Because of this dashboard subscription feature of per hour only, I could not set the email to send on 7pm (VM is still starting) or 9pm(VM is being shutdown already) this is why my report is being sent at 8pm. If we could have this feature I am able to just make the VM running around 1hr or less during weekends.

![image](https://user-images.githubusercontent.com/89201548/181689248-5f6bbeff-daa8-4d4e-a17b-ff4c637816f6.png)

**Comment by flamber** [comment] 2022-07-29 07:59
Duplicate of #3846

**Closed by flamber** 2022-07-29 07:59 UTC
Labels: Type:New Feature, .Needs Triage
