### ISSUE TITLE
Saved Metrics which use custom expressions can't be placed on y-axis of charts

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5125] opened 2017-05-16 22:33 UTC
Possibly related to https://github.com/metabase/metabase/issues/3952

This saved (or "Common") metric, `Average of Run Differential`, is defined as `Average("Field1" - "Field2")`. If I try to break it out by `runs scored by home team`, I can get a table just fine:

<img width="1355" alt="screen shot 2017-05-16 at 3 26 07 pm" src="https://cloud.githubusercontent.com/assets/2223916/26131086/b57d84e2-3a4c-11e7-9b86-52e5d5d59067.png">

If I change the visualization to line or bar, however, MB doesn't recognize the saved metric as being a column that can be plotted on the y-axis:

<img width="1355" alt="screen shot 2017-05-16 at 3 25 36 pm" src="https://cloud.githubusercontent.com/assets/2223916/26131115/e9396e9a-3a4c-11e7-880c-5dd7e0258d92.png">

Here's the visualization settings modal:

<img width="1355" alt="screen shot 2017-05-16 at 3 25 24 pm" src="https://cloud.githubusercontent.com/assets/2223916/26131118/f295cfce-3a4c-11e7-968d-152481267ba4.png">

This problem doesn't seem to occur when using a saved metric that just uses a basic aggregation (i.e. not a custom expression).

**Comment by tlrobinson** [comment] 2017-05-17 15:04
Yeah, duplicate of #3952

**Closed by tlrobinson** 2017-05-17 15:04 UTC
Labels: Bug, Metrics & Segments, Visualization
