### ISSUE TITLE
Add dashboard/card name to the Title tag 

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#3985] opened 2016-12-19 18:43 UTC
How it looks now:
![image](https://cloud.githubusercontent.com/assets/1708680/21323803/29f0d2e8-c630-11e6-8581-80829d204ee3.png)

Suggest — add dashboard/card name to the Title tag. Example:
* "Registrations / Metabase"
* "Our metrics / Metabase"
* "Our chart with MAU / Metabase"

**Comment by kdoh** [comment] 2016-12-19 18:45
Yup we definitely need to work on this. The main tracking issue for this is #1484 and there's a POC implementation in PR #3826  so I'm going to close this as a duplicate.

**Comment by tlrobinson** [comment] 2016-12-19 18:45
Duplicate of #1484

Also, you're not fooling us by 👍  and ❤️ ing your own issues ;)

**Closed by kdoh** 2016-12-19 18:45 UTC

**Comment by anki-code** [comment] 2016-12-19 18:48
Thank you!

@tlrobinson I'm add 👍 to my issues for signal to other users for using it instead of "+1" messages.
