### ISSUE TITLE
Column "Custom title" not working in tooltips

### ISSUE THREAD

**Issue by gaoyang-projects** [metabase/metabase#11395] opened 2019-11-27 08:39 UTC
**Describe the bug**
1.
if char has many lines(visualization), when user try to custom display name;
the display name does not effect all lines;
if you change first display name, it just effect line1, like this;
label1 -> line1
label2 -> line2
...
labelN  -> lineN 

2. data x-axis is readonly and how to set display name? 

**Screenshots**
![1](https://user-images.githubusercontent.com/6829668/69702177-9509cc00-1129-11ea-9814-91f36c88102f.png)
![2](https://user-images.githubusercontent.com/6829668/69702206-a9e65f80-1129-11ea-892b-b27579c265cc.png)
![3](https://user-images.githubusercontent.com/6829668/69705270-29772d00-1130-11ea-92f1-b90f4c65a274.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Chrome 78.0.3904.97
- Windows 10
- Metabase version v0.33.5.1
- Metabase hosting environment: Jar-file on centos
- Metabase internal database: MySQL

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2019-11-27 19:56
Hi @gaoyang-projects 
If I understand you correctly, you are missing the "Column title" field that is available on Table viz?
Then I would consider this a Feature Request and not a Bug, since I don't remember that field being available ever.
![image](https://user-images.githubusercontent.com/1447303/69755151-33dbfb80-111d-11ea-8fcc-684ec3a4263f.png)

**Comment by gaoyang-projects** [comment] 2019-11-28 02:29
> Hi @flamber , I cannot see "Column title " selection , is my browser problems ? 

![4](https://user-images.githubusercontent.com/6829668/69771332-693d2380-11c7-11ea-987e-d3c9b1500be8.png)
![5](https://user-images.githubusercontent.com/6829668/69771404-a0abd000-11c7-11ea-9ea6-2649104f4b5b.png)
![20181212002](https://user-images.githubusercontent.com/6829668/69771968-9985c180-11c9-11ea-8833-5a0c59091429.gif)

**Comment by flamber** [comment] 2019-11-28 02:45
@gaoyang-projects 
You need to select Table under Visualization - not click the raw-data-icon in the bottom-middle.
But I still don't understand what the problem is, or if you are requesting a new feature?

**Comment by gaoyang-projects** [comment] 2019-11-28 03:22
@flamber i want to set metic name, but it's does not work , when mouse over line and show metics. the metic name is originally .
![step1](https://user-images.githubusercontent.com/6829668/69774417-dbfecc80-11d0-11ea-846a-83abf5df3be1.png)
![step2](https://user-images.githubusercontent.com/6829668/69774418-dbfecc80-11d0-11ea-9fad-09644d88a7cc.png)
![step3](https://user-images.githubusercontent.com/6829668/69774422-dc976300-11d0-11ea-961c-016804dcbd2e.png)
![step4](https://user-images.githubusercontent.com/6829668/69774423-dd2ff980-11d0-11ea-8e9d-71fb34371cb7.png)
![step5](https://user-images.githubusercontent.com/6829668/69774425-ddc89000-11d0-11ea-9707-e09fbb334575.png)

**Comment by flamber** [comment] 2019-11-28 04:31
@gaoyang-projects Okay, now I understand. I can confirm the problem on 0.33.6 and master.
The custom display name for a series is only shown in the tooltip of the series being hovered, whereas the others show the default column name.
I think that part was missed in PR #10555. Before that PR, it would not show other series on hover.

Pinging @paulrosenzweig, since he's the tooltip :godmode: 

As for changing the display name of columns on the X-axis (like `Created At` in your example). That has never been possible, as far as I can remember. But that should have it's own feature request.

**Comment by gaoyang-projects** [comment] 2019-11-28 08:30
@flamber   X-axis `Created At` is a group by value , in my case i think if set **custom title** by **column title** in  table mode successfully ,  X-axis can updated together . because X-axis label value can select  from one of table column , so readonly is ok, it's unnecessary to be editable .
@paulrosenzweig 😄

**Comment by gaoyang-projects** [comment] 2019-12-16 06:36
@flamber hi~will this issue be fixed in the next release? 😄

**Comment by flamber** [comment] 2019-12-16 17:21
@gaoyang-projects 
As you can see, there's more than 2000 issues open, so please allow some time to fix issues.

**Comment by flamber** [comment] 2020-02-14 07:49
**Steps to reproduce**
1. Simple question > Sample Dataset > Orders (creates a line viz)
2. Summarize by "Sum of Total" and "Sum of Quantity", group by CreatedAt:Year
3. Visualization Settings > Display > change the column names to something different
4. Hover the Total line, the name is correct for that line, but displays original column name for Quantity. And hovering Quantity, shows correct name for that line, but original name for Total.
![Screenshot_00000](https://user-images.githubusercontent.com/1447303/74511662-c911b380-4f06-11ea-8a53-b894de5983e3.png)

**Comment by silvaarapi** [comment] 2020-12-28 14:43
Hello, 

I was wondering if there is a bounty towards this issue one can donate to? 

Punctum Books, a not-for-profit open-access publisher is using Metabase to Visualize their Book Usage Statistics and they are wondering if they can support somehow to get this issue fixed. 

Here you can find more details on their usage of Metabase: https://punctumbooks.pubpub.org/pub/visualization-book-usage-statistics-metabase/release/1 

Thanks,
Silva

**Comment by alxnddr** [comment] 2021-04-01 23:37
Fixed in https://github.com/metabase/metabase/pull/15435

**Closed by alxnddr** 2021-04-01 23:37 UTC
Labels: .Reproduced, Priority:P2, Type:Bug, Visualization/Chart Settings
