### ISSUE TITLE
Adding new filter to dashboard attempt to find in existing charts by name

### ISSUE THREAD

**Issue by csyperski** [metabase/metabase#24505] opened 2022-08-02 11:53 UTC
**Is your feature request related to a problem? Please describe.**

Yes, when adding new filters to dashboards, it can take a long time to select the matching filter on the individual charts.   

**Describe the solution you'd like**

I'd love when a new filter is added to an existing dashboard with many charts on it that when you enter the name of the filter, it attempt to auto match the filter on the child charts do you don't have to click on every single chart to link the filter.  We have many dashboards with many charts on each and each dashboard can have 20+ filters. 

**Describe alternatives you've considered**

None

**How important is this feature to you?**

It would be very helpful

**Comment by flamber** [comment] 2022-08-02 11:56
Duplicate of #4767

**Closed by flamber** 2022-08-02 11:56 UTC
Labels: Type:New Feature, .Needs Triage
