### ISSUE TITLE
Dashboard filters don't work on saved questions

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#11966] opened 2020-02-24 15:16 UTC
**Describe the bug**
I start a new query with a saved question as source, make some changes to it and add it to a dashboard. When I add a dashboard filter, I am allowed to select a field from the underlying saved question, but its values are not enumerated in the filter dropdown and setting the filter manually leads to an error.

**To Reproduce**
1. Save a question.
2. Start a new question and choose the saved question as its source.
3. Save the question and add it to a dashboard.
4. Create a dashboard filter.
5. Observe you are allowed to select a field from the underlying saved question to link to the filter, but the filter values are not populated from the field and inputting a filter value manually leads to an error.

**Expected behavior**
Saved questions (as question sources) should support filtering on their fields.

**Information about your Metabase Installation:**
`{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1; Windows for Workgroups 3.11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.15.0-66-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.29"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-02-04",
      "tag": "v0.34.2",
      "branch": "release-0.34.x",
      "hash": "dab738c"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}`

**Severity**
Unpleasant, as, instead of using a single question as source, I have to duplicate the actual question and modify it.

**Comment by flamber** [comment] 2020-02-24 17:32
Hi @andreychirikba 
It sounds like a duplicate of #9802.
Which type is the question in step1, Native or Custom?
Are you not seeing "No valid fields" in step4?
I don't understand step5.

**Comment by andreychirikba** [comment] 2020-02-24 18:44
Hi, @flamber, it's a custom question. No, I actually could select the fields, but the filter was not populated with their values. I then tried to input a value manually (by writing text), and at that point I received an error. Looks indeed like a duplicate of the one you mentioned (had tried to find an existing one before posting this, but couldn't).

**Comment by DataDrivenAngel** [comment] 2020-02-24 19:12
Same issue on 34.0

**Comment by flamber** [comment] 2020-02-24 20:47
Closing as duplicate of #9802 - upvote by clicking :+1: on the first post
I think you might be seeing a glitch, where going directly from a question to the dashboard keeps the filter-link-options cache, but if you refreshed the browser on the dashboard, they would probably not be available and it would just say "No valid fields". As you can read in the other issue, it's not a simple fix, but it's definitely not a forgotten issue at all.

**Closed by flamber** 2020-02-24 20:47 UTC
Labels: .Needs Triage, Type:Bug
