### ISSUE TITLE
Smart Number not working after upgrade from 0.31.2 to 0.33

### ISSUE THREAD

**Issue by jelle82** [metabase/metabase#10729] opened 2019-08-27 15:06 UTC
After upgrading to version 0.33 all the smart number diagrams do not work anymore. It says I need to "choose a datelike column", or something like that.

I already changed back to version 0.31.2, so I unfortunately have anymore information or screenshots. If you can't replicate the issue or need more information, I can provide these.

**Comment by paulrosenzweig** [comment] 2019-09-10 14:18
@jelle82 is there any more info you have to help us reproduce? Thanks!

**Comment by jelle82** [comment] 2019-09-17 12:53
Sorry for not responding sooner. I didn't have any quick means to test it. I think I know the source of the bug.

I have my own "calendar" table in the database (with added columns like YTD, etc.) and after I "connect" the date in my revenues table to this calendar table, the smart number visualization stops working. If I remove the connection, the smart number works again.

**Comment by paulrosenzweig** [comment] 2019-09-17 23:35
@jelle82 maybe you can construct a minimal query that replicates the error? For example, it'd be awesome to have a replication example like this:
```sql
select '2019-01-01'::date as t, 123 as x
union all
select '2019-02-01'::date as t, 321 as x
```

Also, when you say you "connect" them, how are you doing that join? Is it done in the query builder or a raw SQL query?

**Comment by jelle82** [comment] 2019-09-23 07:04
@paulrosenzweig I am not sure if I understand your request. This is the SQL with which the smart number visualization doesn't work when I connect the "umsatzdatum" column as a foreign key with the calendar table.

`SELECT str_to_date(concat(yearweek(`fact_revenue`.`umsatzdatum`), ' Sunday'), '%X%V %W') AS `umsatzdatum`, sum(`fact_revenue`.`umsatz`) AS `sum`
FROM `fact_revenue`
GROUP BY str_to_date(concat(yearweek(`fact_revenue`.`umsatzdatum`), ' Sunday'), '%X%V %W')
ORDER BY str_to_date(concat(yearweek(`fact_revenue`.`umsatzdatum`), ' Sunday'), '%X%V %W') ASC`

I connect the date key as a foreign key under data model in the administrator panel with the entity key in my calendar table. Maybe I haven't constructed the calendar table correctly. However, all worked fine under 0.31.2 .

**Comment by paulrosenzweig** [comment] 2019-09-23 15:08
@jelle82 sorry I wasn't clear. I want some way to reproduce this on my computer. If we can't find an example with the sample dataset, sometimes we can find a snippet of SQL that reliably reproduces the issue on its own. We can do that by union-ing together single select lines. That's not always possible though.

A few questions:
* What are the types of the columns used in foreign key relationship?
* What database are you using? (probably not relevant, but still good to find out)
* You're using a GUI question, right? That SQL was what's generated when you click "view as SQL"?

**Comment by flamber** [comment] 2020-05-20 10:01
Closing this, since we haven't been able to reproduce and it hasn't been reported by anyone else.

**Closed by flamber** 2020-05-20 10:01 UTC
Labels: .Unable to Reproduce, Priority:P2, Type:Bug, Visualization/Chart Settings
