### ISSUE TITLE
Pulse/Dashboard not rendering when different date format are to be displayed

### ISSUE THREAD

**Issue by TusharShrivastava** [metabase/metabase#20057] opened 2022-01-31 14:38 UTC
**Describe the bug**
I am creating a new pulse and while selecting "Snowflake date question" pulse not rendering

**Logs**

```
[metabase.server.middleware.log$log_api_call$fn__80447$fn__80448$fn__80449 invoke "log.clj" 209]

[metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 15]

[metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 9]

[metabase.server.middleware.log$log_api_call$fn__80447$fn__80448 invoke "log.clj" 201]

[toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]

[toucan.db$_do_with_call_counting invoke "db.clj" 209]

[metabase.server.middleware.log$log_api_call$fn__80447 invoke "log.clj" 200]

[metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__83660 invoke "browser_cookie.clj" 30]

[metabase.server.middleware.security$add_security_headers$fn__59285 invoke "security.clj" 147]

[metabase.server.middleware.json$wrap_json_body$fn__82804 invoke "json.clj" 62]

[metabase.server.middleware.json$wrap_streamed_json_response$fn__82822 invoke "json.clj" 98]

[metabase.server.middleware.offset_paging$handle_paging$fn__59309 invoke "offset_paging.clj" 42]

[ring.middleware.keyword_params$wrap_keyword_params$fn__83927 invoke "keyword_params.clj" 55]

[ring.middleware.params$wrap_params$fn__83943 invoke "params.clj" 69]

[metabase.server.middleware.misc$maybe_set_site_url$fn__34077 invoke "misc.clj" 59]

[metabase.server.middleware.session$bind_current_user$fn__44982$fn__44983 invoke "session.clj" 257]

[metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 238]

[metabase.server.middleware.session$do_with_current_user invoke "session.clj" 230]

[metabase.server.middleware.session$bind_current_user$fn__44982 invoke "session.clj" 256]

[metabase.server.middleware.session$wrap_current_user_info$fn__44969 invoke "session.clj" 216]

[metabase.server.middleware.session$wrap_session_id$fn__44955 invoke "session.clj" 162]

[metabase.server.middleware.auth$wrap_api_key$fn__70378 invoke "auth.clj" 27]

[ring.middleware.cookies$wrap_cookies$fn__83847 invoke "cookies.clj" 216]

[metabase.server.middleware.misc$add_content_type$fn__34060 invoke "misc.clj" 27]

[metabase.server.middleware.misc$disable_streaming_buffering$fn__34085 invoke "misc.clj" 76]

[ring.middleware.gzip$wrap_gzip$fn__83889 invoke "gzip.clj" 86]

[metabase.server.middleware.misc$bind_request$fn__34088 invoke "misc.clj" 93]

[metabase.server.middleware.ssl$redirect_to_https_middleware$fn__83676 invoke "ssl.clj" 38]

[metabase.server$async_proxy_handler$fn__80220 invoke "server.clj" 71]

[metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]

[org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]

[org.eclipse.jetty.server.Server handle "Server.java" 516]

[org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 388]

[org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 633]

[org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 380]

[org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 277]

[org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]

[org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]

[org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]

[org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 883]

[org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1034]

[java.lang.Thread run nil -1]],

:cause "Unsupported field: MonthOfYear",

:message "Unsupported field: MonthOfYear"}

```

**To Reproduce**
1. Go to 'create new pulse'
2. Click on 'Select a question'
3. Scroll down to 'Snowflake date question'

**Expected behavior**
Pulse should display the data

**Screenshots**

![image](https://user-images.githubusercontent.com/79984925/151812439-ed68175e-2a18-47b0-b7ff-1f7ca5abd23a.png)

![image](https://user-images.githubusercontent.com/79984925/151812505-42eb9393-df13-4d64-81bf-d57521c4e97b.png)

**Information about your Metabase Installation:**
I am using the latest Metabase image v0.41.6

**Comment by flamber** [comment] 2022-01-31 14:40
Duplicate of #15146

**Closed by flamber** 2022-01-31 14:40 UTC
Labels: Type:Bug, .Needs Triage
