### ISSUE TITLE
Popup when user is closing a SQL question that's not saved

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#24459] opened 2022-08-01 12:51 UTC
**Is your feature request related to a problem? Please describe.**
A user might do a great SQL question, but then because of closing a tab or the browser by error that query might dissapear. It would be good to introduce some popup when we detect the closing of the tab to ask for confirmation

**Describe the solution you'd like**
Pop up asking the user if they want to save the question before closing the tab

**Describe alternatives you've considered**
NA

**How important is this feature to you?**
Requested by a customer

**Additional context**
NA

**Comment by flamber** [comment] 2022-08-01 12:55
Duplicate of #8712/#12389

**Closed by flamber** 2022-08-01 12:55 UTC
Labels: Type:New Feature, Querying/Native
