### ISSUE TITLE
Allow renaming x-axis series name in viz settings

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#28734] opened 2023-02-28 13:46 UTC
## What
You can easily rename x- and y-axis labels in the "Axes" tab of viz settings today. But if I want to also change the "series name" that's reflected in our tooltips, there's no way to do so for x-axis series. Furthermore, if I update the series name it's not intuitive that it's not propagated to the axes settings.

![Image](https://user-images.githubusercontent.com/16455495/221873131-792f9246-c2bc-4b8e-8dbf-8c91ff1cdc8e.png)

## Expected Behavior
There's two parts of this. If we can only get 1) then that's good. If we can get 2) as well then great.
1. Bring label inputs to the popover for x-axes series. Should behave the same as other series.
2. When "Axes" labels haven't yet been changed, and the user updates a "Data" series label, automatically propagate those changes to the "Axes" label settings. Doesn't apply for x-axis breakouts. Only applicable before the user manually changes "Axes" settings, in that case we shouldn't propagate.

**Comment by paoliniluis** [comment] 2023-02-28 14:24
Dupe of https://github.com/metabase/metabase/issues/28700?

**Closed** 2023-02-28 14:27 UTC
Labels: Priority:P3, Type:New Feature, .Product/Pothole
