### ISSUE TITLE
Bad performance in `GET /api/activity/recent_views`

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#29103] opened 2023-03-09 21:34 UTC
The queries that power `GET /api/activity/recent_views`, in `metabase.api.activity/views-and-runs`, result in full table scans against ViewLog and QueryExecution respectively. These tables can get pretty big and are currently unbounded. Collectively the queries take 9 seconds or so on the stats application database, so it would probably take significantly longer on larger instances.

We should figure out how to tweak the queries to avoid full table scans and improve the performance there a bit

**Comment by camsaul** [comment] 2023-03-09 21:38
Since this is `recent_views` maybe a WHERE clause on the timestamp columns would do the trick, I think both of those columns have indexes on them. We'll have to play around with `EXPLAIN` tho

**Comment by camsaul** [comment] 2023-03-09 21:39
Additional context in Slack thread https://metaboat.slack.com/archives/CKZEMT1MJ/p1678396587238539

**Comment by paoliniluis** [comment] 2023-03-09 21:50
dupe of https://github.com/metabase/metabase/issues/27216 :)

**Closed by paoliniluis** 2023-03-09 21:50 UTC
Labels: Priority:P1, .Performance, Misc/API, .Backend, Organization/Activity Log
