### ISSUE TITLE
Is there a way to use dashboard filter to overwrite the question filter?

### ISSUE THREAD

**Issue by neptune19821220** [metabase/metabase#12670] opened 2020-06-10 05:07 UTC
Because this projects has so many open issues, I am not sure if my question is already in the issues.

For BI usage, we often add some questions whose dataset may just has 2 column, date and value.
For example, the total count of active users based on date.

For question itself, we would get a large query result if we do not have a query filter on date.
For dashboard, we also would  a dashboard filter to show the data in time period we are interest in.
But these two filter seems has a "AND" relation which caused me having trouble to show correct time period of data.

The perfect way is as following:
When we access the questions itself, the chart of question should based on the date  filter in the questions.
When we access the question from dashboard, the chart of question should based on the date filter of dashboard , not the combination of question date  filter and dashboard date filter.

Is there anyway to archive the above goal ?

Thanks.

**Comment by flamber** [comment] 2020-06-10 10:06
Hi @neptune19821220 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

Duplicate of #2763

That is by design. If you create a question called "Time records for September" and add it to the dashboard, then allowing you to modify the filter would be counter intuitive. And would also make it impossible to impose any restrictions or permissions.
Create a question that returns all records and set default filters in the dashboard.
https://www.metabase.com/docs/latest/users-guide/08-dashboard-filters.html

**Closed by flamber** 2020-06-10 10:06 UTC
Labels: .Needs Triage, Type:Question
