### ISSUE TITLE
No Option to "Select None" Columns in Custom Question

### ISSUE THREAD

**Issue by JamesVorder** [metabase/metabase#12483] opened 2020-05-08 14:58 UTC
## Describe the bug
When selecting columns to show in a "Custom Question," I cannot "de-select all" columns. The check-box labelled "Select All" (which is selected by default) appears to be disabled.

## To Reproduce
1. Create a new Custom Question
2. Select some database table
3. Click on "Columns"
4. "Select All" is grayed out, and cannot be used to de-select all the columns.

## Expected behavior
The "Select All" checkbox is enabled, and I am able to unselect it to **de**-select all.
**Note:** If you join to another table and click on "Columns" for the "Join data," this expected behavior is implemented there. It's just the first data set where it is broken.

## Screenshots

The "Select All" box is disabled for the original data set.
<img width="860" alt="Bug" src="https://user-images.githubusercontent.com/5509670/81417449-32c1e800-9119-11ea-9515-c3ff2a7986c2.png">

There is a "Select None" option on joined tables by default. This is how I would expect the feature to work on the first data set too.
<img width="1164" alt="Working" src="https://user-images.githubusercontent.com/5509670/81418369-8da80f00-911a-11ea-9cb7-43d95afba2d3.png">

## Information about your Metabase Installation:
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.14.173-137.229.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "googleanalytics",
      "h2"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-21",
      "tag": "v0.35.3",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

## Severity
It's pretty annoying, but since I am able to write SQL, this does not block me from completing my work.

**Comment by flamber** [comment] 2020-05-08 15:00
Duplicate of #10460

**Closed by flamber** 2020-05-08 15:00 UTC
Labels: .Duplicate, Type:Bug
