### ISSUE TITLE
Old Postgres scheme is not removed after "sync db scheme"

### ISSUE THREAD

**Issue by abouzarnouri** [metabase/metabase#9781] opened 2019-04-14 08:27 UTC
Bug report:
I am using metabase.jar 0.32.4 with H2 internal database on Windows. My analytics data is located on a Postgres DB. I have some old schemes on Postgres which do not exist anymore, but metabase shows them since long times ago it has seen them and "Sync database schema now" has no effect on it.

**Comment by flamber** [comment] 2019-04-14 15:28
@abouzarnouri Do you see any warnings/errors in the log, when sync'ing?

**Comment by abouzarnouri** [comment] 2019-04-15 07:09
> @abouzarnouri Do you see any warnings/errors in the log, when sync'ing?

Nope. I checked the logs, I didn't find any errors or warning. Neither I found the name of deleted schemes in the logs.

**Comment by tsibley** [comment] 2019-04-23 16:31
I also have this issue and there's no clear way to remove the non-existent schemas. Clicking on one from the "Our data > $dbname" page goes to a non-working URL like `…/metabase/browse/2/schema/staging` (where `staging` is the name of the non-existent schema).

Metabase docker image, 0.31.2 with H2 internal database on Ubuntu pointed at PostgreSQL 10.6 (on AWS RDS).

**Comment by calz1** [comment] 2019-11-29 22:04
I still get this issue with PostgreSQL both for Metabase and as the data source.

**Comment by AxelFurlanF** [comment] 2019-12-20 19:22
I have the same issue. We use https://github.com/fishtown-analytics/dbt in our analytics warehouse, it creates a different schema for each new PR and gets deleted when the PR is merged. Right now we have all these old schemas that shouldn't be there.
![image](https://user-images.githubusercontent.com/19914428/71285826-e4b46f80-2344-11ea-8055-d8608a04b737.png)

**Comment by lindsay-stevens** [comment] 2020-02-28 06:00
It looks like the following might be the cause. The first code chunk is for `/api/database/:id/schemas` which is used by the "Our Data" browser to show the list of schemas after clicking on a database name. The second code chunk is for `/api/database/:id/schema/:schema` which is used after clicking on a schema name.

Since the first one doesn't filter for `:active true`, it returns schemas for which there are no active tables i.e. previously scanned / synced tables that now no longer exist in the reporting database for whatever reason. The second one does filter for `:active true` so when clicking on the deleted schema's name, the back-end returns a 404 which is shown as "Not found" in the UI.

@camsaul Would you be willing to merge a PR (like #8835) that added an `:active true` filter to the `select-field` call in the `/:id/schemas` endpoint?

https://github.com/metabase/metabase/blob/master/src/metabase/api/database.clj#L572-L578

```clojure
(api/defendpoint GET "/:id/schemas"
  "Returns a list of all the schemas found for the database `id`"
  [id]
  (api/read-check Database id)
  (->> (db/select-field :schema Table :db_id id)
       (filter (partial can-read-schema? id))
       sort))
```

https://github.com/metabase/metabase/blob/master/src/metabase/api/database.clj#L583-L591

```clojure
(api/defendpoint GET "/:id/schema/:schema"
  "Returns a list of tables for the given database `id` and `schema`"
  [id schema]
  (api/read-check Database id)
  (api/check-403 (can-read-schema? id schema))
  (->> (db/select Table :db_id id, :schema schema, :active true, {:order-by [[:name :asc]]})
       (filter mi/can-read?)
       seq
       api/check-404))
```

**Closed** 2020-03-02 22:52 UTC
Labels: Administration/Metadata & Sync, Priority:P3, Type:Bug
