### ISSUE TITLE
Mis-labeled series in line graphs

### ISSUE THREAD

**Issue by brnt** [metabase/metabase#3896] opened 2016-12-08 16:05 UTC
OS: OSX 10.12.1
Browser: Chrome 54.0.2840.98 (64-bit), 55.0.2883.75 (64-bit)
Data DB: PostgreSQL 9.5.2
Metabase DB: PosgtreSQL 9.5.5
Env: Heroku
Metabase Version (hash): 76e1ab9

To produce the error, generate a line graph with two series. Give the series names in your query. In the graph, the legend is accurate ("Series A" and "Series B") but the series title in the mouseover box for the data points in Series B all say "Series A". See attached screenie.

<img width="387" alt="screen shot 2016-12-08 at 9 04 16 am" src="https://cloud.githubusercontent.com/assets/1072638/21017076/52d41fee-bd25-11e6-8bb6-b06f78ea76f4.png">

**Comment by tlrobinson** [comment] 2016-12-09 08:23
Duplicate of #3669

**Closed by tlrobinson** 2016-12-09 08:23 UTC
