### ISSUE TITLE
Have field filter search show all results that contain the search query, instead of only those that start with it.

### ISSUE THREAD

**Issue by Tbodewes** [metabase/metabase#11428] opened 2019-12-03 08:05 UTC
**Is your feature request related to a problem? Please describe.**
Dashboard users in my organization are always frustrated if they can't find a particular customer in the field filter search of a dashboard. This is because the search query has to exactly match the start of the string being searched, i.e. the matching seems to be done as 
```
WHERE
    column_to_be_searched LIKE '<search query>%'
```

As a particular example, in case one searches for organization 'foo bar' using 'bar', no results are found. Searching on 'foo' does find the right organization (see below for example).

**Describe the solution you'd like**
When entering 'bar' in a field filter search, strings like 'foo bar' also show in the results. In technical terms, matching is done as 
```
WHERE
    column_to_be_searched LIKE '%<search query>%'
```

**Describe alternatives you've considered**
Currently, end-users have to look up the precise customer name in a different system. However, they often forget that they have to do this this and get confused when they seemingly can't find an organization by name because they didn't start the name exactly right. For example, they will start searching for 'Association of Dutch Dentists' with 'Dutch Dentists', which does not give any results. 

**How important is this feature to you?**
The current search is workable and already quite nice. However, the way search works now often leads to confusion and makes true self-serve a lot more difficult.

**Additional context**
Illustrating the problem:

Here we start the search query exactly right:
![image](https://user-images.githubusercontent.com/40305973/70031629-f5768e80-15ab-11ea-9bbf-580fe894f1bb.png)

Here we forget the first part of the search query:
![image](https://user-images.githubusercontent.com/40305973/70031649-00c9ba00-15ac-11ea-9995-4906d1123b47.png)

In the latter case, I'd like 'ZIVVER Demo OWA' to also be found.

**Comment by flamber** [comment] 2019-12-03 15:54
Hi @Tbodewes 
Sounds like a duplicate of #8219. If you agree, then please close this and upvote the other issue :+1:
There's a PR too, but as noted https://github.com/metabase/metabase/pull/7951#issuecomment-449747349, this become a performance issue.

**Closed** 2019-12-03 16:04 UTC
Labels: .Needs Triage, Type:New Feature
