### ISSUE TITLE
Add Filter icon clobbers text

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2095] opened 2016-03-07 17:21 UTC
In Safari, the '+' icon for filters clobbers the text. See attached screenshot.

If this is a bug report, please fill in the blanks:

*  I am using the Safari browser.
*  My computer's OS is OS X.
*  My database is Postgres.
*  My Metabase version is HEAD.

<img width="450" alt="screen shot 2016-03-07 at 9 20 38 am" src="https://cloud.githubusercontent.com/assets/107439/13577159/eef094d4-e445-11e5-8637-dc3c87314443.png">

**Comment by kdoh** [comment] 2016-03-07 17:28
Duplicate of #2092

**Closed by kdoh** 2016-03-07 17:28 UTC
Labels: Duplicate
