### ISSUE TITLE
Error filtering by a sumarize column on PostgreSQL

### ISSUE THREAD

**Issue by jaimepineiro** [metabase/metabase#11366] opened 2019-11-21 10:17 UTC
**Describe the bug**
When i create a simple grouping query with a filter in the count column as shown in the attached image, i get an error because comparison is done as "character" in stead of as "numeric" field.

**Logs**
`11-21 09:20:07 ERROR sql-jdbc.execute :: nil
11-21 09:20:08 WARN middleware.process-userland-query :: Query failure {:status :failed,
 :class org.postgresql.util.PSQLException,
 :error "ERROR: operator does not exist: bigint > character varying\n  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.\n  Position: 549",
 :stacktrace
 ("org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)"
  "org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)"
  "org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)"
  "org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)"
  "org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)"
  "org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)"
  "org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)"
  "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)"
  "clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1072)"
  "clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1066)"
  "clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1081)"
  "clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)"
  "clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)"
  "clojure.java.jdbc$query.invoke(jdbc.clj:1126)"
  "--> driver.sql_jdbc.execute$cancelable_run_query$fn__66651.invoke(execute.clj:182)"
  "driver.sql_jdbc.execute$do_with_ensured_connection.invokeStatic(execute.clj:159)"
  "driver.sql_jdbc.execute$do_with_ensured_connection.invoke(execute.clj:157)"
  "driver.sql_jdbc.execute$cancelable_run_query.invokeStatic(execute.clj:174)"
  "driver.sql_jdbc.execute$cancelable_run_query.invoke(execute.clj:170)"
  "driver.sql_jdbc.execute$run_query.invokeStatic(execute.clj:196)"
  "driver.sql_jdbc.execute$run_query.invoke(execute.clj:192)"
  "driver.sql_jdbc.execute$do_with_auto_commit_disabled.invokeStatic(execute.clj:243)"
  "driver.sql_jdbc.execute$do_with_auto_commit_disabled.invoke(execute.clj:231)"
  "driver.sql_jdbc.execute$do_in_transaction$fn__66672.invoke(execute.clj:248)"
  "driver.sql_jdbc.execute$do_in_transaction.invokeStatic(execute.clj:247)"
  "driver.sql_jdbc.execute$do_in_transaction.invoke(execute.clj:246)"
  "driver.sql_jdbc.execute$run_query_without_timezone.invokeStatic(execute.clj:265)"
  "driver.sql_jdbc.execute$run_query_without_timezone.invoke(execute.clj:264)"
  "driver.sql_jdbc.execute$execute_query$fn__66699.invoke(execute.clj:297)"
  "driver.sql_jdbc.execute$do_with_try_catch.invokeStatic(execute.clj:223)"
  "driver.sql_jdbc.execute$do_with_try_catch.invoke(execute.clj:217)"
  "driver.sql_jdbc.execute$execute_query.invokeStatic(execute.clj:291)"
  "driver.sql_jdbc.execute$execute_query.invoke(execute.clj:285)"
  "driver.sql_jdbc$fn__67318.invokeStatic(sql_jdbc.clj:44)"
  "driver.sql_jdbc$fn__67318.invoke(sql_jdbc.clj:43)"
  "query_processor$fn__44023$execute_query__44028$fn__44029.invoke(query_processor.clj:71)"
  "query_processor$fn__44023$execute_query__44028.invoke(query_processor.clj:65)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__34284.invoke(mbql_to_native.clj:38)"
  "query_processor.middleware.annotate$result_rows_maps__GT_vectors$fn__36550.invoke(annotate.clj:541)"
  "query_processor.middleware.annotate$add_column_info$fn__36456.invoke(annotate.clj:485)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__37491.invoke(cumulative_aggregations.clj:57)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__41131.invoke(resolve_joins.clj:184)"
  "query_processor.middleware.limit$limit$fn__38092.invoke(limit.clj:19)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__43890.invoke(results_metadata.clj:87)"
  "query_processor.middleware.format_rows$format_rows$fn__38080.invoke(format_rows.clj:26)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__35043.invoke(add_dimension_projections.clj:234)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__35684.invoke(add_source_metadata.clj:107)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__41181.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__35531.invoke(add_row_count_and_status.clj:16)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__37567.invoke(driver_specific.clj:12)"
  "query_processor.middleware.add_settings$add_settings$fn__35554.invoke(add_settings.clj:45)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__40795.invoke(resolve_driver.clj:22)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__36881$fn__36882.invoke(bind_effective_timezone.clj:9)"
  "util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
  "util.date$call_with_effective_timezone.invoke(date.clj:77)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__36881.invoke(bind_effective_timezone.clj:8)"
  "query_processor.middleware.store$initialize_store$fn__43915$fn__43916.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__43915.invoke(store.clj:10)"
  "query_processor.middleware.async$async__GT_sync$fn__34195.invoke(async.clj:23)"
  "query_processor.middleware.async_wait$runnable$fn__36607.invoke(async_wait.clj:89)"),
 :query
 {:type "query",
  :query {:source-query {:source-table 194, :aggregation [["count"]], :breakout [["fk->" ["field-id" 3797] ["field-id" 821]]]}, :filter [">" ["field-literal" "count" "type/Integer"] "4"]},
  :parameters [],
  :async? true,
  :middleware {:add-default-userland-constraints? true, :userland-query? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :card-id nil,
   :nested? false,
   :query-hash [-102, -105, -39, 7, 122, 55, -123, 4, -92, 119, 83, -109, -54, -57, 80, -54, 27, 118, 1, 7, -73, 74, 47, -123, 31, -11, -3, 114, 119, -33, 68, 127]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :preprocessed
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:add-default-userland-constraints? true, :userland-query? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :nested? false,
   :query-hash [-102, -105, -39, 7, 122, 55, -123, 4, -92, 119, 83, -109, -54, -57, 80, -54, 27, 118, 1, 7, -73, 74, 47, -123, 31, -11, -3, 114, 119, -33, 68, 127]},
  :preprocessing-level 1,
  :database 2,
  :driver :postgres,
  :query
  {:source-query
   {:source-table 194,
    :aggregation [[:aggregation-options [:count] {:name "count"}]],
    :breakout [[:joined-field "owner__via__id_owner" [:field-id 821]]],
    :order-by [[:asc [:joined-field "owner__via__id_owner" [:field-id 821]]]],
    :joins [{:strategy :left-join, :source-table 33, :alias "owner__via__id_owner", :fk-field-id 3797, :condition [:= [:field-id 3797] [:joined-field "owner__via__id_owner" [:field-id 823]]]}]},
   :filter [:> [:field-literal "count" :type/Integer] [:value "4" nil]],
   :source-metadata
   [{:name "full_name",
     :id 821,
     :table_id 33,
     :display_name "ID Owner → Full Name",
     :base_type :type/Text,
     :special_type :type/Name,
     :fingerprint {:global {:distinct-count 879, :nil% 0.0}, :type {:type/Text {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :average-length 22.9453734671126}}},
     :settings nil}
    {:name "count", :display_name "Count", :base_type :type/Integer, :special_type :type/Number}],
   :fields [[:field-literal "full_name" :type/Text] [:field-literal "count" :type/Integer]],
   :limit 2000}},
 :native
 {:query
  "SELECT \"source\".\"full_name\" AS \"full_name\", \"source\".\"count\" AS \"count\" FROM (SELECT \"owner__via__id_owner\".\"full_name\" AS \"full_name\", count(*) AS \"count\" FROM \"dpgis_sfin\".\"unity\" LEFT JOIN \"dpgis_sfin\".\"owner\" \"owner__via__id_owner\" ON \"dpgis_sfin\".\"unity\".\"id_owner\" = \"owner__via__id_owner\".\"id_owner\" GROUP BY \"owner__via__id_owner\".\"full_name\" ORDER BY \"owner__via__id_owner\".\"full_name\" ASC) \"source\" WHERE \"source\".\"count\" > ? LIMIT 2000",
  :params ("4")}}`

**To Reproduce**
1. Go to Ask a question -> Simple question
2. Pick a table
3. Go to 'editor'
4. Click on 'Sumarize' pick "Count of rows" and a column
5. Click on 'Filter' an choose the "Count" column "Greater than" and a number
6. Click on 'Visualize'

**Expected behavior**
View the result of the query

**Screenshots**
![image](https://user-images.githubusercontent.com/45460679/69328900-61720200-0c50-11ea-932c-27a28fd21007.png)
![image](https://user-images.githubusercontent.com/45460679/69328920-6afb6a00-0c50-11ea-9573-39199c1f4c6b.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox 70.0.1 (64-bit)
- Your operating system: Docker image 
- Your databases: PostgreSQL
- Metabase version: v0.33.5.1 and v0.33.6
- Metabase hosting environment: Docker
- Metabase internal database: H2 (default)

**Severity**
Blocking, I think grouping and filtering is a basic functionality that must work properly

**Comment by sbelak** [comment] 2019-11-21 10:58
I think this is related to (or even same as) #11208

**Comment by jaimepineiro** [comment] 2019-11-21 11:14
I agree, is the same

**Comment by flamber** [comment] 2019-11-21 14:08
I think it's a duplicate of #11223, not #11208, since the filter options are numeric on this issue.

**Comment by mazameli** [comment] 2019-11-21 20:33
Yeah, closing as duplicate of #11223.

**Closed by mazameli** 2019-11-21 20:33 UTC
Labels: .Duplicate
