### ISSUE TITLE
SQL Query Variable Parsing Does Not Ignore Comments 

### ISSUE THREAD

**Issue by andrewdibiasio6** [metabase/metabase#24857] opened 2022-08-17 21:14 UTC
**Describe the bug**
When parsing for variables in SQL text, metabase does not ignore variables in comments. This causes issues for drivers that use stored procedures because the number of parameters will be off. Note this will not impact DBs whose drivers are not using stored procedures since no parameters are supplied. Likely a change can be made here: https://github.com/metabase/metabase/blob/995cc80bfa15605ab39edbebe077da3f80e6124c/src/metabase/driver/sql/parameters/substitute.clj#L76

**Logs**
```
2022-08-17 17:11:38,390 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 43,
 :started_at #t "2022-08-17T17:11:37.816220-04:00[America/New_York]",
 :via
 [{:status :failed,
   :class java.sql.SQLException,
   :error
   "Query failed (#20220817_211138_03629_bzer7): line 1:1: Incorrect number of parameters: expected 1 but found 2",
   :stacktrace
   ["io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1937)"
    "io.trino.jdbc.TrinoResultSet.getColumns(TrinoResultSet.java:285)"
    "io.trino.jdbc.TrinoResultSet.create(TrinoResultSet.java:61)"
    "io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:262)"
    "io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)"
    "io.trino.jdbc.TrinoPreparedStatement.executeQuery(TrinoPreparedStatement.java:135)"
    "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)"
    "--> driver.sql_jdbc.execute$eval48134$fn__48135.invoke(execute.clj:363)"
    "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:376)"
    "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:372)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__48234.invoke(execute.clj:500)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:499)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:494)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
    "driver.sql_jdbc$eval71763$fn__71764.invoke(sql_jdbc.clj:54)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
    "query_processor.context.default$default_runf.invoke(default.clj:65)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___58345.invoke(cache.clj:220)"
    "query_processor.middleware.permissions$check_query_permissions$fn__58808.invoke(permissions.clj:109)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__59944.invoke(mbql_to_native.clj:23)"
    "query_processor$fn__62362$combined_post_process__62367$combined_post_process_STAR___62368.invoke(query_processor.clj:207)"
    "query_processor$fn__62362$combined_pre_process__62363$combined_pre_process_STAR___62364.invoke(query_processor.clj:204)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__61161$fn__61166.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:75)"
    "driver$do_with_driver.invoke(driver.clj:71)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__61161.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__59751.invoke(fetch_source_query.clj:281)"
    "query_processor.middleware.store$initialize_store$fn__61995$fn__61996.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__61995.invoke(store.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__59963.invoke(normalize_query.clj:22)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__47571.invoke(constraints.clj:53)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__61034.invoke(process_userland_query.clj:145)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__58901.invoke(catch_exceptions.clj:162)"
    "query_processor.reducible$async_qp$qp_STAR___47773$thunk__47775.invoke(reducible.clj:100)"
    "query_processor.reducible$async_qp$qp_STAR___47773.invoke(reducible.clj:106)"
    "query_processor.reducible$async_qp$qp_STAR___47773.invoke(reducible.clj:91)"
    "query_processor$base_qp$fn__62374.doInvoke(query_processor.clj:225)"
    "query_processor.reducible$sync_qp$qp_STAR___47784.doInvoke(reducible.clj:126)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:326)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:322)"
    "query_processor$eval62409$process_query_and_save_execution_BANG___62418$fn__62421.invoke(query_processor.clj:337)"
    "query_processor$eval62409$process_query_and_save_execution_BANG___62418.invoke(query_processor.clj:330)"
    "query_processor$eval62453$process_query_and_save_with_max_results_constraints_BANG___62462$fn__62465.invoke(query_processor.clj:349)"
    "query_processor$eval62453$process_query_and_save_with_max_results_constraints_BANG___62462.invoke(query_processor.clj:342)"
    "api.dataset$run_query_async$fn__77702.invoke(dataset.clj:68)"
    "query_processor.streaming$streaming_response_STAR_$fn__68002$fn__68003.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__68002.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__26224.invoke(streaming_response.clj:84)"],
   :state nil}
  {:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error executing query: Query failed (#20220817_211138_03629_bzer7): line 1:1: Incorrect number of parameters: expected 1 but found 2",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__48234.invoke(execute.clj:502)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:499)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:494)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
    "driver.sql_jdbc$eval71763$fn__71764.invoke(sql_jdbc.clj:54)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
    "query_processor.context.default$default_runf.invoke(default.clj:65)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___58345.invoke(cache.clj:220)"
    "query_processor.middleware.permissions$check_query_permissions$fn__58808.invoke(permissions.clj:109)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__59944.invoke(mbql_to_native.clj:23)"
    "query_processor$fn__62362$combined_post_process__62367$combined_post_process_STAR___62368.invoke(query_processor.clj:207)"
    "query_processor$fn__62362$combined_pre_process__62363$combined_pre_process_STAR___62364.invoke(query_processor.clj:204)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__61161$fn__61166.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:75)"
    "driver$do_with_driver.invoke(driver.clj:71)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__61161.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__59751.invoke(fetch_source_query.clj:281)"
    "query_processor.middleware.store$initialize_store$fn__61995$fn__61996.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__61995.invoke(store.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__59963.invoke(normalize_query.clj:22)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__47571.invoke(constraints.clj:53)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__61034.invoke(process_userland_query.clj:145)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__58901.invoke(catch_exceptions.clj:162)"
    "query_processor.reducible$async_qp$qp_STAR___47773$thunk__47775.invoke(reducible.clj:100)"
    "query_processor.reducible$async_qp$qp_STAR___47773.invoke(reducible.clj:106)"
    "query_processor.reducible$async_qp$qp_STAR___47773.invoke(reducible.clj:91)"
    "query_processor$base_qp$fn__62374.doInvoke(query_processor.clj:225)"
    "query_processor.reducible$sync_qp$qp_STAR___47784.doInvoke(reducible.clj:126)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:326)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:322)"
    "query_processor$eval62409$process_query_and_save_execution_BANG___62418$fn__62421.invoke(query_processor.clj:337)"
    "query_processor$eval62409$process_query_and_save_execution_BANG___62418.invoke(query_processor.clj:330)"
    "query_processor$eval62453$process_query_and_save_with_max_results_constraints_BANG___62462$fn__62465.invoke(query_processor.clj:349)"
    "query_processor$eval62453$process_query_and_save_with_max_results_constraints_BANG___62462.invoke(query_processor.clj:342)"
    "api.dataset$run_query_async$fn__77702.invoke(dataset.clj:68)"
    "query_processor.streaming$streaming_response_STAR_$fn__68002$fn__68003.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__68002.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__26224.invoke(streaming_response.clj:84)"],
   :error_type :invalid-query,
   :ex-data
   {:sql
    "-- Metabase:: userID: 1 queryType: native queryHash: 995645b79e19d3332b4a11a49e6580c593e8786f8c692cc93956e79cfb1a5930\nSELECT count(*) \n-- ?\nFROM products\nWHERE category = ?",
    :params ["test" "test"],
    :type :invalid-query}}],
 :error_type :invalid-query,
 :json_query
 {:database 43,
  :native
  {:template-tags
   {:category {:id "0539c9a0-988f-675e-58b3-c58932ec4903", :name "category", :display-name "category", :type "text"}},
   :query "SELECT count(*) \n-- {{category}}\nFROM products\nWHERE category = {{category}}"},
  :type "native",
  :parameters
  [{:type "category",
    :value "test",
    :target ["variable" ["template-tag" "category"]],
    :id "0539c9a0-988f-675e-58b3-c58932ec4903"}],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :status :failed,
 :class io.trino.jdbc.$internal.client.FailureInfo$FailureException,
 :stacktrace
 ["io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)"
  "io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)"
  "io.trino.execution.QueryPreparer.validateParameters(QueryPreparer.java:88)"
  "io.trino.execution.QueryPreparer.prepareQuery(QueryPreparer.java:80)"
  "io.trino.execution.QueryPreparer.prepareQuery(QueryPreparer.java:56)"
  "io.trino.dispatcher.DispatchManager.createQueryInternal(DispatchManager.java:180)"
  "io.trino.dispatcher.DispatchManager.lambda$createQuery$0(DispatchManager.java:149)"
  "io.trino.$gen.Trino_392_e_34_gaa543f5____20220812_154120_2.run(Unknown Source)"
  "java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)"
  "java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)"
  "java.base/java.lang.Thread.run(Thread.java:833)"
  nil],
 :card_id nil,
 :context :ad-hoc,
 :error
 "Query failed (#20220817_211138_03629_bzer7): line 1:1: Incorrect number of parameters: expected 1 but found 2",
 :row_count 0,
 :running_time 0,
 :data {:rows [], :cols []}}
```

**To Reproduce**
1. Go to new/sql query
2. Select a DB that uses stored procedures, like Starburst
3. enter: 
4. 
```
SELECT count(*) 
-- {{category}}
FROM products
WHERE category = {{category}}
```

5. Add a variable for category
6. Run query

**Expected behavior**
As a user, I expect to be able to have valid comment strings in my sql as needed and I would expect these to be ignored by any parsing done by metabase. 

**Screenshots**
<img width="1781" alt="Screen Shot 2022-08-17 at 5 00 51 PM" src="https://user-images.githubusercontent.com/8988880/185242233-8c73dc22-1e43-4767-918c-eaae524401f3.png">

See image above, I expect one parameter, but the second one in the comment is picked up causing an error.

**Information about your Metabase Installation:**

Using local instance to reproduce the issue that reported by a client.
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "18.0.2+9-61",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "18.0.2",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "18.0.2+9-61",
    "os.name": "Mac OS X",
    "os.version": "12.4",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "starburst"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2022-08-03",
      "tag": "v1.44.1-SNAPSHOT",
      "branch": "?",
      "hash": "e0c5592"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
**Severity**
Currently blocking some users as this was reported to Starburst from a user, but will cause issues to any DBs that are using stored procedures.

**Comment by flamber** [comment] 2022-08-18 07:26
Duplicate of #7742

**Closed by flamber** 2022-08-18 07:26 UTC
Labels: Type:Bug, .Needs Triage
