### ISSUE TITLE
Error generating fingerprint for Field : class java.lang.String cannot be cast to class java.lang.Number

### ISSUE THREAD

**Issue by anoopk19** [metabase/metabase#10617] opened 2019-08-19 15:23 UTC
This error is seen on druid database. Finger printer fails if a dimension column is a non-string type. I have a column with datatype 'float'

**Stacktrace**
```
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]: 08-19 14:58:57 ERROR sync.util :: Error generating fingerprint for Field 'riskScore': class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]: ("clojure.lang.RT.doubleCast(RT.java:1355)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "bigml.histogram.core$when_double.invokeStatic(core.clj:104)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "bigml.histogram.core$when_double.invoke(core.clj:103)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "bigml.histogram.core$insert_simple_BANG_.invokeStatic(core.clj:109)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "bigml.histogram.core$insert_simple_BANG_.invoke(core.clj:106)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "--> sync.analyze.fingerprint.fingerprinters$histogram.invokeStatic(fingerprinters.clj:179)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "sync.analyze.fingerprint.fingerprinters$histogram.invoke(fingerprinters.clj:175)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "sync.analyze.fingerprint.fingerprinters$with_error_handling$fn__43316$fn__43321.invoke(fingerprinters.clj:116)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "sync.util$do_with_error_handling.invokeStatic(util.clj:149)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "sync.util$do_with_error_handling.invoke(util.clj:144)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "sync.analyze.fingerprint.fingerprinters$with_error_handling$fn__43316.invoke(fingerprinters.clj:116)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "sync.analyze.fingerprint.fingerprinters$col_wise$fn__43279$fn__43284.invoke(fingerprinters.clj:32)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "sync.analyze.fingerprint.fingerprinters$col_wise$fn__43279.invoke(fingerprinters.clj:29)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "sync.analyze.query_results$results__GT_column_metadata.invokeStatic(query_results.clj:70)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "sync.analyze.query_results$results__GT_column_metadata.invoke(query_results.clj:63)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__43686.invoke(results_metadata.clj:90)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "query_processor.middleware.format_rows$format_rows$fn__37872.invoke(format_rows.clj:26)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "query_processor.middleware.add_dimension_projections$add_remapping$fn__34714.invoke(add_dimension_projections.clj:234)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__35330.invoke(add_source_metadata.clj:101)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__40970.invoke(resolve_source_table.clj:48)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__35193.invoke(add_row_count_and_status.clj:16)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "query_processor.middleware.driver_specific$process_query_in_context$fn__37359.invoke(driver_specific.clj:12)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "query_processor.middleware.resolve_driver$resolve_driver$fn__40590.invoke(resolve_driver.clj:22)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__36550$fn__36551.invoke(bind_effective_timezone.clj:9)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "util.date$call_with_effective_timezone.invoke(date.clj:77)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__36550.invoke(bind_effective_timezone.clj:8)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "query_processor.middleware.store$initialize_store$fn__43711$fn__43712.invoke(store.clj:11)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "query_processor.store$do_with_store.invoke(store.clj:40)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "query_processor.middleware.store$initialize_store$fn__43711.invoke(store.clj:10)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "query_processor.middleware.async$async__GT_sync$fn__33933.invoke(async.clj:23)"
Aug 19 14:58:57 ip-172-31-13-76 metabase[1851]:  "query_processor.middleware.async_wait$runnable$fn__36278.invoke(async_wait.clj:89)")
```

**Information about your Metabase Installation:**

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)

- Metabase version: latest master branch

- Metabase hosting environment: Linux/Ubuntu

- Metabase internal database: Postgres

**Comment by sbelak** [comment] 2019-08-21 22:29
The root cause of this seems to be, that we wrongly assign types to numeric dimensions.

@anoopk19: to confirm this, could you show me the output of /api/field/:id where :id is the id of one of the float dimensions

**Comment by sbelak** [comment] 2019-08-28 13:27
Also, @anoopk19 can you show me what's the DataSchema for this table.

**Comment by sbelak** [comment] 2019-08-28 13:59
I think what happens is that the dimension comes down the wire as a string. Not entirely sure why. My knowledge of Druid is limited, but if I understand correctly we should be setting `outputType` via extraction DataSchema (https://druid.apache.org/docs/latest/querying/dimensionspecs.html), else you get dimensions back as strings. However even that only solves for some types of queries. I'm thinking of hardening the fingerprinting & insights code to work with strings and add the extraction DataSchema to the Druid driver. Thoughts @camsaul, @anoopk19

**Comment by Kieranflock** [comment] 2019-11-19 09:20
I think I am also seeing this issue as well. We are currently trying to use v.0.33.5.1, is there a workaround we use?

This is preventing Metabase from scanning new schemas, which is preventing me from fixing any questions that were created using the UI and not native SQL.

**Comment by exherb** [comment] 2020-04-01 04:12
any progress on that?

**Comment by qnkhuat** [comment] 2024-07-19 03:08
It's been a while, but is anyone still experiencing this issue?

I just tested with a simple data

```json
{"timestamp": "2023-01-02T00:00:00Z", "long_col": 11, "float_col": 31.5, "double_col": 41.5}
```

and it syncs successfully with the correct type.

**Comment by darksciencebase** [comment] 2024-08-01 13:58
doesn't seem to reproduce with the new driver, so, closing as already fixed

**Closed by darksciencebase** 2024-08-01 13:58 UTC
Labels: Type:Bug, Priority:P2, Administration/Metadata & Sync, Database/Druid, .Team/BackendComponents
