### ISSUE TITLE
Ability to edit metadata for a schema

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#25002] opened 2022-08-24 22:18 UTC
**Is your feature request related to a problem? Please describe.**

For a table, you can edit metadata like changing the display name and description. It would be great to be able to do the same thing for schema as well. The key is to be able to change the display name of a schema (and optionally be able to add a description). Changing the name could make it look nicer and more descriptive and it could be used to append a deprecation message to tell users not to use it. 

**Describe the solution you'd like**

When browsing data, add a button next to a schema (similar to table) to edit meta data. 

**Describe alternatives you've considered**

When deprecating a schema, I edit the first table's name to append a deprecation message. 

**How important is this feature to you?**

It is definitely nice to have, but doesn't block. 

**Additional context**
n/a

**Comment by flamber** [comment] 2022-08-25 07:19
Duplicate of #6619

**Closed by flamber** 2022-08-25 07:19 UTC
Labels: Type:New Feature, .Needs Triage
