### ISSUE TITLE
Connect ClickhouseDB

### ISSUE THREAD

**Issue by hieule1997** [metabase/metabase#11961] opened 2020-02-24 01:48 UTC
The clickhouse is a very fast query db. so I want to try connecting to the clickhouse to see its usability.
Thank you

**Comment by lindsay-stevens** [comment] 2020-02-24 07:32
Requires using custom driver but it's pretty straightforward to set up, see here: https://github.com/enqueue/metabase-clickhouse-driver

**Comment by flamber** [comment] 2020-02-24 11:02
Duplicate of #3332

**Closed by flamber** 2020-02-24 11:02 UTC
Labels: .Needs Triage, Type:New Feature
