### ISSUE TITLE
All columns disappear on Table view while trying to hide one column

### ISSUE THREAD

**Issue by diraol** [metabase/metabase#24292] opened 2022-07-26 01:52 UTC
**Describe the bug**
After creating a Table view (on a multi-table join + summarization query) I was trying to hide one specific column and then, suddenly, all columns except the "summary" one were hidden.

Moreover, while trying to re-add the columns to the Table View I could only add one extra column. If I try to add a second column then the UI just replaces the previously added column with the new one.

**Logs**
```
missing join? 
missing join? 
Object { _metadata: {…}, _datasetQuery: {…}, _originalQuestion: {…}, _structuredDatasetQuery: {…} }
​
_datasetQuery: Object { type: "query", query: {…}, database: 1 }
​​
database: 1
​​
query: Object { "source-query": {…} }
​​​
"source-query": Object { "source-table": 2, joins: (3) […], aggregation: (1) […], … }
​​​​
aggregation: Array [ (2) […] ]
​​​​
breakout: Array(3) [ (3) […], (3) […], (3) […] ]
​​​​
joins: Array(3) [ {…}, {…}, {…} ]
​​​​
"source-table": 2
​​​​
<prototype>: Object { … }
​​​
<prototype>: Object { … }
​​
type: "query"
​​
<prototype>: Object { … }
​
_metadata: Object { _plainObject: {}, databases: {…}, schemas: {…}, … }
​​
_plainObject: Object {  }
​​
databases: Object { 1: {…} }
​​
fields: Object { 1: {…}, 2: {…}, 3: {…}, … }
​​
metrics: Object {  }
​​
schemas: Object { "1:PUBLIC": {…} }
​​
segments: Object {  }
​​
tables: Object { 1: {…}, 2: {…}, 3: {…}, … }
​​
<prototype>: Object { … }
​
_originalQuestion: Object { _card: {…}, _metadata: {…}, _parameterValues: {}, … }
​​
_card: Object { creationType: "custom_question", dataset_query: {…}, display: "table", … }
​​
_metadata: Object { _plainObject: {}, databases: {…}, schemas: {…}, … }
​​
_parameterValues: Object {  }
​​
_update: function T()
​​
<prototype>: Object { … }
​
_structuredDatasetQuery: Object { type: "query", query: {…}, database: 1 }
​​
database: 1
​​
query: Object { "source-query": {…} }
​​
type: "query"
​​
<prototype>: Object { … }
​
<prototype>: Object { … }
 
Object { _parent: null, _args: (2) […], _metadata: {…}, _query: {…}, _options: {…}, _fieldIdOrName: 25 }
dataset.js:157:22

```

**To Reproduce**
1. Create a new Questions using the Orders sample dataset
2. Join all tables (Orders, People, Product and Review)
3. Create a new Summarize field with the Sum of Quantity
4. Group by "People -> City", "People -> State", "Products -> Category"
5. Click at Visualize (you will see the full table with all the before mentioned fields
6. Click on "Settings"
7. Remove the "City" field by clicking in the "X" on the left bar
8. Now click on "Play" to see all columns removed.
9. Now click on the "+" button to re-add a columns (city)
10. Now, after is was added, click in the "+"  button from the State column to re-add it

**Expected behavior**
* Removing/hiding a column shouldn't remove all other columns.
* Re-adding a Column shouldn't replace other previously added questions.

**Screenshots**

https://user-images.githubusercontent.com/192702/180905033-8dd36721-afee-4630-b59e-3d09258f117b.mp4

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox 102.0.1
- Your operating system: Linux Debian
- Your databases: Either MySQL/MariaDB and H2
- Metabase version: v.0.43.4
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
It is blocking me from building some of the dashboards I need to build there.

**Additional context**

**Comment by flamber** [comment] 2022-07-26 10:10
Duplicate of #22563

**Closed by flamber** 2022-07-26 10:10 UTC
Labels: Type:Bug, .Needs Triage
