### ISSUE TITLE
已归档的集合不能删除

### ISSUE THREAD

**Issue by bold-rabbit** [metabase/metabase#40680] opened 2024-03-27 15:15 UTC
### Describe the bug

![image](https://github.com/metabase/metabase/assets/49431955/6d5de072-14d6-4e7a-82c6-ff574beec107)
![image](https://github.com/metabase/metabase/assets/49431955/805f4df9-87bb-4517-88e9-fef90d812781)

### To Reproduce

在删除已归档的集合时候，点击删除报错了

### Information about your Metabase installation

```JSON
docker metabase/metabase:v0.49.1
```

### Severity

历史归档无法删除

**Comment by paoliniluis** [comment] 2024-03-27 15:49
duplicate of https://github.com/metabase/metabase/issues/18372

**Closed by paoliniluis** 2024-03-27 15:49 UTC
Labels: Type:Bug, .Needs Triage
