### ISSUE TITLE
multiple values error in parametes Parameters when destination is public  url

### ISSUE THREAD

**Issue by MeharG811** [metabase/metabase#40939] opened 2024-04-03 07:28 UTC
### Describe the bug

i have a dashboard and applied clickable  behavior on a card . apllied some filters on dashboard but the values of filters are not passing correctly on the destination url . when i change the destination to question or dashboard it worked fine.
check this screen recording
https://drive.google.com/file/d/1JMokoXzeLExFeqG1vphN0sklMLL2VrO9/view

### To Reproduce

Create a card (card 1) 
write query 
add parameters in it

create another question (card 2)
make it available to public

create a clickable behavior link  card 1 to card 2

apply filters specially one that has multiple values 

now click on card 1 to trigger clickable behavior 

you will notice filters are not applied correctly

check this screen recording
https://drive.google.com/file/d/1JMokoXzeLExFeqG1vphN0sklMLL2VrO9/view

### Information about your Metabase installation

```JSON
chrome Version 123.0.6312.86 (Official Build) (64-bit)
ubuntu 22.04
mysql 
metabase  0.48.7
jar file
mysql
```

### Severity

blocking the usage

**Comment by uladzimirdev** [comment] 2024-04-03 07:58
@MeharG811 could you please provide more information about the click behaviour settings?

**Comment by uladzimirdev** [comment] 2024-04-03 08:08
I can confirm the broken behaviuor with a custom URL on click action:

1. create a question from People
2. add it to a dashboard, create a filter with a name "param" and map name column on it
3. save dashboard and make it public, copy public URL
4. add a custom click behaviour on e.g. email column and put url in destionation as `public url + ?param={{param}}`, e.g. `http://localhost:3000/public/dashboard/b56b0464-f609-439f-a74b-f8ee4912f8f8?param={{param}}`
5. save dashboard, select 2 values in a filter, make sure question is filtered, then click on any email from the question -> you'll be redirected to a public URL with `param=value1,value2` which is wrong

**Comment by paoliniluis** [comment] 2024-04-03 09:02
Isn´t this a duplicate of https://github.com/metabase/metabase/issues/26412?

**Comment by uladzimirdev** [comment] 2024-04-03 10:08
@paoliniluis you're right

**Closed by uladzimirdev** 2024-04-03 10:08 UTC
Labels: Type:Bug, Priority:P3, Querying/Parameters & Variables, .Needs Clarification, Sharing/Public
