### ISSUE TITLE
Users unable to load dashboard due to 'syntax error at or near ")"'

### ISSUE THREAD

**Issue by jamesvl** [metabase/metabase#44069] opened 2024-06-12 15:44 UTC
### Describe the bug

Users visiting dashboard they could view in 0.49.x can no longer do so in 0.50.0

We have repeated errors in our logs, triggered for different user ids and dashboard ids, that all log the same error.

The core of the issue seems to be Metabase issuing an improper query in the form `"SELECT * FROM "metabase_database" WHERE "id" IN ()"` (n.b. no ids or placeholders are given)

Logs included below.

### To Reproduce

Cannot consistently reproduce; some users can view the dashboard normally, but others trigger the above error.

### Expected behavior

Dashboards that loaded in 0.49 should continue to load in 0.50

### Logs

```
[ae7775f3-42f4-46ef-b1dc-66830a1bc2a1] 2024-06-12T10:37:21-04:00 ERROR metabase.server.middleware.log GET /api/dashboard/201/query_metadata 500 334.7 ms (71 DB calls) {:metabase-user-id 48} 
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message "ERROR: syntax error at or near \")\"\n  Position: 50",
   :data
   {:toucan2/context-trace
    [["execute SQL with class com.mchange.v2.c3p0.impl.NewProxyConnection"
      {:toucan2.jdbc.query/sql-args ["SELECT * FROM \"metabase_database\" WHERE \"id\" IN ()"]}]
     ["resolve connection" {:toucan2.connection/connectable metabase.db.connection.ApplicationDB}]
     ["resolve connection" {:toucan2.connection/connectable :default}]
     ["resolve connection" {:toucan2.connection/connectable nil}]
     {:toucan2.pipeline/rf
      #object[clojure.core$map$fn__5931$fn__5932 0x3304f710 "clojure.core$map$fn__5931$fn__5932@3304f710"]}
     ["with compiled query"
      {:toucan2.pipeline/compiled-query ["SELECT * FROM \"metabase_database\" WHERE \"id\" IN ()"]}]
     ["with built query"
      {:toucan2.pipeline/built-query {:select [:*], :from [[:metabase_database]], :where [:in :id #{}]}}]
     ["with resolved query" {:toucan2.pipeline/resolved-query {}}]
     ["with parsed args"
      {:toucan2.pipeline/query-type :toucan.query-type/select.instances,
       :toucan2.pipeline/parsed-args {:kv-args {:id [:in #{}]}, :queryable {}}}]
     ["with model" {:toucan2.pipeline/model :model/Database}]
     ["with unparsed args"
      {:toucan2.pipeline/query-type :toucan.query-type/select.instances,
       :toucan2.pipeline/unparsed-args (:model/Database :id [:in #{}])}]]},
   :at [org.postgresql.core.v3.QueryExecutorImpl receiveErrorResponse "QueryExecutorImpl.java" 2725]}
  {:type org.postgresql.util.PSQLException,
   :message "ERROR: syntax error at or near \")\"\n  Position: 50",
   :at [org.postgresql.core.v3.QueryExecutorImpl receiveErrorResponse "QueryExecutorImpl.java" 2725]}],
 :trace
 [[org.postgresql.core.v3.QueryExecutorImpl receiveErrorResponse "QueryExecutorImpl.java" 2725]
  [org.postgresql.core.v3.QueryExecutorImpl processResults "QueryExecutorImpl.java" 2412]
  [org.postgresql.core.v3.QueryExecutorImpl execute "QueryExecutorImpl.java" 371]
  [org.postgresql.jdbc.PgStatement executeInternal "PgStatement.java" 502]
  [org.postgresql.jdbc.PgStatement execute "PgStatement.java" 419]
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "6.1.79-99.164.amzn2023.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-10",
      "tag": "v0.50.0",
      "hash": "4fe42d3"
    },
    "settings": {
      "report-timezone": "America/New_York"
    }
  }
}
```

### Severity

blocking some users

**Comment by ranquild** [comment] 2024-06-12 15:48
Duplicate of https://github.com/metabase/metabase/issues/44043

**Closed by ranquild** 2024-06-12 15:48 UTC
Labels: Type:Bug, .Backend, .Needs Triage

**Comment by jamesvl** [comment] 2024-06-12 15:51
Agreed; I tried looking first for anything similar...

May close this one as a dupe.
