### ISSUE TITLE
Unable to discard cached field values

### ISSUE THREAD

**Issue by thibauds** [metabase/metabase#48738] opened 2024-10-15 15:47 UTC
**Describe the bug**
When trying to discard cached field values, I get the following error:
>  PreparedStatement can have at most 65,535 parameters. Please consider using arrays, or splitting the query in several ones, or using COPY. Given query has 1,967,379 parameters.

**To Reproduce**
Add a MongoDB collection with a lot of different field values and field names.
Go to Admin settings > Table Metadata > gear icon > Discard cached field values.

**Metabase Diagnostic Info**

```json
{
  "metabase-info": {
    "databases": [
      "mongo"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-09-24",
      "tag": "v0.50.27",
      "hash": "8b9a8fc"
    },
    "settings": {
      "report-timezone": null
    },
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.8 (Ubuntu 14.8-1.pgdg18.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  }
}
```

**Comment by paoliniluis** [comment] 2024-11-07 14:48
duplicate of https://github.com/metabase/metabase/issues/33037

**Closed by paoliniluis** 2024-11-07 14:48 UTC
