### ISSUE TITLE
"Starting from" logic when used with larger granularities than "Day" is incorrect

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#22284] opened 2022-04-29 18:39 UTC
It's hard for me to tell if this is only a problem with the date range _preview_ text, or if the query itself is wrong because I don't have data in these time ranges. This came up in https://discourse.metabase.com/t/relative-date-filter-ui-inconsistency-v0-43-rc1/19697, so cc @flamber.

The expectation when doing something like "Past 3 months, starting from 2 months ago" is that you'd be selecting 3 _whole_ months, starting from day 1 of the month through the last day of the month.

Instead, the preview is showing that it's seemingly pushing things back by perhaps 60 or 62 days instead of by two whole months, and consequently is showing the range starting on a day other than day 1 of the month.

In this example below, because it's April right now for me, I'm expecting it to select November, December, and January, i.e., Nov 1 through Jan 31 — because first it's going back two whole months from April, meaning February; then selecting the 3 previous months before February: November, December, and January.

Here's what I'm observing:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/2223916/166003298-9545a14b-dac1-4625-a840-70599329f1f6.png">

Here's another example with quarters, where again I'm expecting the start of the range to be day 1 of some month. Starting two quarters ago would mean Q4 2021 (since it's Q2 2022 for me right now), and then it should select Q1, Q2, and Q3 of 2021 — aka Jan 1, 2021 – Sep 30 2021.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/2223916/166003555-4b4cc59e-0fc6-4235-8e97-188ffc8053d5.png">

**Comment by flamber** [comment] 2022-05-02 09:29
Isn't this a duplicate of #22225 ?

**Closed** 2022-05-03 11:06 UTC
Labels: Type:Bug, Querying/GUI, .Needs Triage, .bugbash
