### ISSUE TITLE
bug - can't use results Common Metrics or Custom Expressions in graphs

### ISSUE THREAD

**Issue by BembelGmbH** [metabase/metabase#5265] opened 2017-06-04 20:31 UTC
I am using MB 2.4.1. For a table, When trying to use Custom Expressions like "sum(amount*price)" I am getting a result, so a table like this: 

<img src="http://i.imgur.com/e3y46LB.png" />

But when I am navigating to the "graph" part, I can't choose the second column:

<img src="http://i.imgur.com/rsYJZRl.png" />

Same happens if I use a metric. 
It hapens if a "Custom Expression" - name, is not equal to one of the column names. If I give it a name, that equals one of the columns of this table, than it works

**Comment by Varunram** [comment] 2017-06-05 06:31
@BembelGmbH Ah, I've experienced a similar issue before. I didn't notice that this was the exact cause though, although I was wondering why I couldn't plot a bar graph for a perfectly suitable dataset. Thanks! I'll look into it and report my findings.

**Comment by mazameli** [comment] 2017-06-06 16:45
I'm pretty sure this is a duplicate of https://github.com/metabase/metabase/issues/3952

**Closed by mazameli** 2017-06-06 16:45 UTC
Labels: Duplicate
