### ISSUE TITLE
Models created in SQL joined in a GUI question requires Native query editing permissions to be able to run

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#30077] opened 2023-04-13 16:00 UTC
**Describe the bug**
Models created in SQL joined in GUI questions require Native query editing permissions to be able to run and filter

**To Reproduce**

SETUP: 

1. Go to New -> Collection -> Test
2. New -> SQL query -> `Select * From Orders` -> Save in Test Collection -> Turn into a Model
3. New -> Question -> Products -> Join Model created on step 2 On products.ID = model.product_ID

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/110378427/231809425-d18b2ec2-7b0f-4009-b88e-a77220c5b724.png">

4. Admin -> People -> Groups ->  Create New Group -> Save
5. Admin -> People -> Add New user -> Assign it to the Group created in step 4:

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/110378427/231811491-7cae9fcd-ad73-41a2-872b-c76facc827cb.png">

6. Admin -> Permissions -> Data -> make sure you give unrestricted Access to the Group and No Native Query Editing
6a.  Make sure that All users has No Native Query Editing

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/110378427/231812024-ca9e1ca0-0603-4260-9b72-d5ce1e18d7b7.png">

8. Admin -> Permissions -> Collections -> make sure you give Curate permission to the Group

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/110378427/231812412-64841b33-1fe6-49fb-bc90-e8e2ffafcc06.png">

ERROR: 

1. Login as the non-Admin user created above and notice that you are able to click the model and even filter

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/110378427/231813175-a41f30f7-9690-41bb-8fd3-ea77f806b293.png">

2. Click on the GUI question created in Step 3 and notice you are able to load data:

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/110378427/231813993-59a9a006-1ccd-4b84-8e67-c20b30ae60a5.png">

3. Now try to filter and it fails:

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/110378427/231814664-24250a3e-7c12-4a64-b815-0d14b9265314.png">

4. To add with the above it also fails in the GUI preview

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/110378427/231815124-5d0a8f33-b1b9-4aac-b795-8fdcb91d94d9.png">

Fails with below error:

<details><summary>Full stacktrace</summary>

```
 {:database_id 1,
 :started_at #t "2023-04-13T15:49:54.527867Z[GMT]",
 :error_type :missing-required-permissions,
 :json_query
 {:type "query",
  :query
  {:source-table 1,
   :joins
   [{:fields "all",
     :source-table "card__5",
     :condition ["=" ["field" 60 nil] ["field" "PRODUCT_ID" {:base-type "type/Integer", :join-alias "Question 5"}]],
     :alias "Question 5"}],
   :limit 10},
  :database 1,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native nil,
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> query_processor.middleware.permissions$perms_exception.invokeStatic(permissions.clj:34)"
  "query_processor.middleware.permissions$perms_exception.doInvoke(permissions.clj:28)"
  "query_processor.middleware.permissions$perms_exception.invokeStatic(permissions.clj:31)"
  "query_processor.middleware.permissions$perms_exception.invoke(permissions.clj:28)"
  "query_processor.middleware.permissions$fn__64607$check_ad_hoc_query_perms__64612$fn__64613.invoke(permissions.clj:88)"
  "query_processor.middleware.permissions$fn__64607$check_ad_hoc_query_perms__64612.invoke(permissions.clj:84)"
  "query_processor.middleware.permissions$fn__64634$check_query_permissions_STAR___64635.invoke(permissions.clj:116)"
  "query_processor.middleware.permissions$check_query_permissions$fn__64643.invoke(permissions.clj:125)"
  "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$check_download_permissions$fn__105770.invoke(permissions.clj:125)"
  "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__107204.invoke(column_level_perms_check.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__68062.invoke(mbql_to_native.clj:24)"
  "query_processor$fn__70690$combined_post_process__70695$combined_post_process_STAR___70696.invoke(query_processor.clj:243)"
  "query_processor$fn__70690$combined_pre_process__70691$combined_pre_process_STAR___70692.invoke(query_processor.clj:240)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__69082$fn__69087.invoke(resolve_database_and_driver.clj:36)"
  "driver$do_with_driver.invokeStatic(driver.clj:90)"
  "driver$do_with_driver.invoke(driver.clj:86)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__69082.invoke(resolve_database_and_driver.clj:35)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__64952.invoke(fetch_source_query.clj:310)"
  "query_processor.middleware.store$initialize_store$fn__65130$fn__65131.invoke(store.clj:12)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:47)"
  "query_processor.store$do_with_store.invoke(store.clj:41)"
  "query_processor.middleware.store$initialize_store$fn__65130.invoke(store.clj:11)"
  "query_processor.middleware.normalize_query$normalize$fn__69371.invoke(normalize_query.clj:25)"
  "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__75976.invoke(handle_audit_queries.clj:131)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__66308.invoke(constraints.clj:54)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__69307.invoke(process_userland_query.clj:150)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__69684.invoke(catch_exceptions.clj:171)"
  "query_processor.reducible$async_qp$qp_STAR___59455$thunk__59457.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___59455.invoke(reducible.clj:109)"
  "query_processor.reducible$async_qp$qp_STAR___59455.invoke(reducible.clj:94)"
  "query_processor.reducible$sync_qp$qp_STAR___59467.doInvoke(reducible.clj:129)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:362)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:358)"
  "query_processor$fn__70738$process_query_and_save_execution_BANG___70747$fn__70750.invoke(query_processor.clj:373)"
  "query_processor$fn__70738$process_query_and_save_execution_BANG___70747.invoke(query_processor.clj:366)"
  "query_processor$fn__70783$process_query_and_save_with_max_results_constraints_BANG___70792$fn__70795.invoke(query_processor.clj:385)"
  "query_processor$fn__70783$process_query_and_save_with_max_results_constraints_BANG___70792.invoke(query_processor.clj:378)"
  "api.dataset$run_query_async$fn__87329.invoke(dataset.clj:73)"
  "query_processor.streaming$streaming_response_STAR_$fn__54305$fn__54306.invoke(streaming.clj:166)"
  "query_processor.streaming$streaming_response_STAR_$fn__54305.invoke(streaming.clj:165)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
  "async.streaming_response$do_f_async$task__36922.invoke(streaming_response.clj:88)"],
 :card_id nil,
 :context :ad-hoc,
 :error "You do not have permissions to run this query.",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:type :query,
  :query
  {:source-table 1,
   :limit 10,
   :fields
   [[:field 60 nil]
    [:field 64 nil]
    [:field 59 nil]
    [:field 62 nil]
    [:field 61 nil]
    [:field 58 nil]
    [:field 65 nil]
    [:field 63 {:temporal-unit :default}]
    [:field "ID" {:base-type :type/BigInteger, :join-alias "Question 5"}]
    [:field "USER_ID" {:base-type :type/Integer, :join-alias "Question 5"}]
    [:field "PRODUCT_ID" {:base-type :type/Integer, :join-alias "Question 5"}]
    [:field "SUBTOTAL" {:base-type :type/Float, :join-alias "Question 5"}]
    [:field "TAX" {:base-type :type/Float, :join-alias "Question 5"}]
    [:field "TOTAL" {:base-type :type/Float, :join-alias "Question 5"}]
    [:field "DISCOUNT" {:base-type :type/Float, :join-alias "Question 5"}]
    [:field "CREATED_AT" {:base-type :type/DateTime, :join-alias "Question 5"}]
    [:field "QUANTITY" {:base-type :type/Integer, :join-alias "Question 5"}]],
   :joins
   [{:source-query {:native "Select * From Orders"},
     :fields
     [[:field "ID" {:base-type :type/BigInteger, :join-alias "Question 5"}]
      [:field "USER_ID" {:base-type :type/Integer, :join-alias "Question 5"}]
      [:field "PRODUCT_ID" {:base-type :type/Integer, :join-alias "Question 5"}]
      [:field "SUBTOTAL" {:base-type :type/Float, :join-alias "Question 5"}]
      [:field "TAX" {:base-type :type/Float, :join-alias "Question 5"}]
      [:field "TOTAL" {:base-type :type/Float, :join-alias "Question 5"}]
      [:field "DISCOUNT" {:base-type :type/Float, :join-alias "Question 5"}]
      [:field "CREATED_AT" {:base-type :type/DateTime, :join-alias "Question 5"}]
      [:field "QUANTITY" {:base-type :type/Integer, :join-alias "Question 5"}]],
     :source-metadata
     [{:display_name "ID",
       :field_ref [:field "ID" {:base-type :type/BigInteger}],
       :name "ID",
       :base_type :type/BigInteger,
       :effective_type :type/BigInteger,
       :semantic_type :type/PK,
       :fingerprint nil}
      {:display_name "USER_ID",
       :field_ref [:field "USER_ID" {:base-type :type/Integer}],
       :name "USER_ID",
       :base_type :type/Integer,
       :effective_type :type/Integer,
       :semantic_type nil,
       :fingerprint
       {:global {:distinct-count 193, :nil% 0},
        :type
        {:type/Number
         {:min 1, :q1 65.75124219539381, :q3 215.0496485969564, :max 276, :sd 81.03924458071305, :avg 137.893}}}}
      {:display_name "PRODUCT_ID",
       :field_ref [:field "PRODUCT_ID" {:base-type :type/Integer}],
       :name "PRODUCT_ID",
       :base_type :type/Integer,
       :effective_type :type/Integer,
       :semantic_type nil,
       :fingerprint
       {:global {:distinct-count 200, :nil% 0},
        :type
        {:type/Number
         {:min 1, :q1 49.215431541775644, :q3 147.99543851531354, :max 200, :sd 57.76090574004626, :avg 98.553}}}}
      {:display_name "SUBTOTAL",
       :field_ref [:field "SUBTOTAL" {:base-type :type/Float}],
       :name "SUBTOTAL",
       :base_type :type/Float,
       :effective_type :type/Float,
       :semantic_type nil,
       :fingerprint
       {:global {:distinct-count 330, :nil% 0},
        :type
        {:type/Number
         {:min 15.691943673970439,
          :q1 49.985248755650794,
          :q3 105.75635962212282,
          :max 148.22900526552291,
          :sd 32.66637499877059,
          :avg 77.87581313233785}}}}
      {:display_name "TAX",
       :field_ref [:field "TAX" {:base-type :type/Float}],
       :name "TAX",
       :base_type :type/Float,
       :effective_type :type/Float,
       :semantic_type nil,
       :fingerprint
       {:global {:distinct-count 600, :nil% 0},
        :type
        {:type/Number
         {:min 0,
          :q1 2.383235294117647,
          :q3 5.576262636024203,
          :max 11.12,
          :sd 2.369881443862045,
          :avg 3.9948050000000004}}}}
      {:display_name "TOTAL",
       :field_ref [:field "TOTAL" {:base-type :type/Float}],
       :name "TOTAL",
       :base_type :type/Float,
       :effective_type :type/Float,
       :semantic_type nil,
       :fingerprint
       {:global {:distinct-count 1494, :nil% 0},
        :type
        {:type/Number
         {:min 13.703915846433869,
          :q1 52.16498672761125,
          :q3 110.74896236179433,
          :max 159.34900526552292,
          :sd 34.41222590732287,
          :avg 81.33739624585914}}}}
      {:display_name "DISCOUNT",
       :field_ref [:field "DISCOUNT" {:base-type :type/Float}],
       :name "DISCOUNT",
       :base_type :type/Float,
       :effective_type :type/Float,
       :semantic_type :type/Discount,
       :fingerprint
       {:global {:distinct-count 185, :nil% 0.8945},
        :type
        {:type/Number
         {:min 0.41329422842438834,
          :q1 3.1115483062325273,
          :q3 7.341641026703381,
          :max 9.669111943074371,
          :sd 2.452703604726128,
          :avg 5.054235890793273}}}}
      {:display_name "CREATED_AT",
       :field_ref [:field "CREATED_AT" {:base-type :type/DateTime, :temporal-unit :default}],
       :name "CREATED_AT",
       :base_type :type/DateTime,
       :effective_type :type/DateTime,
       :semantic_type :type/CreationTimestamp,
       :fingerprint
       {:global {:distinct-count 2000, :nil% 0},
        :type {:type/DateTime {:earliest "2016-06-01T18:12:52.802Z", :latest "2020-04-19T14:07:15.657Z"}}}}
      {:display_name "QUANTITY",
       :field_ref [:field "QUANTITY" {:base-type :type/Integer}],
       :name "QUANTITY",
       :base_type :type/Integer,
       :effective_type :type/Integer,
       :semantic_type :type/Quantity,
       :fingerprint
       {:global {:distinct-count 27, :nil% 0},
        :type
        {:type/Number
         {:min 0, :q1 1.7680340018414042, :q3 5.078814523684541, :max 68, :sd 3.5020851003402265, :avg 3.6885}}}}],
     :source-query/dataset? true,
     :alias "Question 5",
     :strategy :left-join,
     :source-card-id 5,
     :condition [:= [:field 60 nil] [:field "PRODUCT_ID" {:base-type :type/Integer, :join-alias "Question 5"}]]}]},
  :database 1,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info {:executed-by 2, :context :ad-hoc}},
 :ex-data
 {:type :missing-required-permissions,
  :required-permissions #{"/db/1/schema/PUBLIC/table/1/query/" "/db/1/native/"},
  :actual-permissions
  #{"/collection/2/"
    "/collection/namespace/snippets/root/"
    "/collection/3/"
    "/data/db/1/"
    "/collection/root/"
    "/application/subscription/"
    "/db/1/schema/"
    "/query/db/1/schema/"},
  :permissions-error? true},
 :data {:rows [], :cols []}}

```
</details>

**Information about your Metabase Installation:**

Able to replicate `1.46.1` and `master`

**Workaround**

You need to give user Native Query Editing Permissions

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/110378427/231817654-e1ea6c1f-334e-46a9-a895-408c04fc7c10.png">

**Comment by cbalusek** [comment] 2023-04-14 22:17
I was not able to replicate this in 1.45.3.1

**Comment by paoliniluis** [comment] 2023-04-18 00:27
I just realized this is a duplicate of https://github.com/metabase/metabase/issues/14495

**Comment by carstenkadmos** [comment] 2023-08-18 07:49
hey, is there any movement? as described in #33041 this problem leads to issues on a daily basis in our organization.

**Comment by NevRA** [comment] 2024-11-04 15:42
@dpsutton will reassign to the AWA team, fyi

**Closed** 2024-11-08 18:58 UTC
Labels: Type:Bug, Priority:P1, Administration/Permissions, .Backend, .Escalation, .Team/AdminWebapp
