### ISSUE TITLE
Summarize by day displays previous day

### ISSUE THREAD

**Issue by titanzrule32** [metabase/metabase#19190] opened 2021-12-03 06:38 UTC
**Describe the bug**
While attempting to report on the number of records per day, we are experiencing issues with the summarize feature in that it is accurately reporting the days of the week. 

**Logs**
<details><summary>Unimportant logs</summary>

```
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:07:51-06:00 DEBUG metabase.server.middleware.log POST /api/card/357/query 202 [ASYNC: completed] 38.4 ms (16 DB calls) App DB connections: 2/15 Jetty threads: 6/50 (0 idle, 0 queued) (141 total active threads) Queries in flight: 8 (0 queued); postgres DB 7 connections: 1/2 (0 threads blocked)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:07:51-06:00 DEBUG metabase.server.middleware.log POST /api/card/205/query 202 [ASYNC: completed] 42.0 ms (16 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (1 idle, 0 queued) (141 total active threads) Queries in flight: 7 (0 queued); postgres DB 7 connections: 1/1 (0 threads blocked)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:07:51-06:00 INFO metabase.query-processor.middleware.cache Query took 42.0 ms to run; minimum for cache eligibility is 60.0 s
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:07:51-06:00 INFO metabase.query-processor.middleware.cache Query took 43.0 ms to run; minimum for cache eligibility is 60.0 s
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:07:51-06:00 DEBUG metabase.server.middleware.log POST /api/card/207/query 202 [ASYNC: completed] 100.0 ms (18 DB calls) App DB connections: 1/15 Jetty threads: 6/50 (0 idle, 0 queued) (147 total active threads) Queries in flight: 6 (0 queued); postgres DB 7 connections: 2/3 (0 threads blocked)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:07:51-06:00 DEBUG metabase.server.middleware.log POST /api/card/208/query 202 [ASYNC: completed] 96.4 ms (18 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (1 idle, 0 queued) (147 total active threads) Queries in flight: 5 (0 queued); postgres DB 7 connections: 1/3 (0 threads blocked)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:07:51-06:00 INFO metabase.query-processor.middleware.cache Query took 68.0 ms to run; minimum for cache eligibility is 60.0 s
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:07:51-06:00 DEBUG metabase.server.middleware.log POST /api/card/209/query 202 [ASYNC: completed] 110.6 ms (18 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (1 idle, 0 queued) (147 total active threads) Queries in flight: 4 (0 queued); postgres DB 7 connections: 3/3 (0 threads blocked)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:07:51-06:00 INFO metabase.query-processor.middleware.cache Query took 110.0 ms to run; minimum for cache eligibility is 60.0 s
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:07:51-06:00 DEBUG metabase.server.middleware.log POST /api/card/337/query 202 [ASYNC: completed] 131.3 ms (16 DB calls) App DB connections: 4/15 Jetty threads: 4/50 (1 idle, 0 queued) (147 total active threads) Queries in flight: 3 (0 queued); postgres DB 7 connections: 2/2 (0 threads blocked)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:07:51-06:00 INFO metabase.query-processor.middleware.cache Query took 66.0 ms to run; minimum for cache eligibility is 60.0 s
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:07:51-06:00 DEBUG metabase.server.middleware.log POST /api/card/210/query 202 [ASYNC: completed] 115.5 ms (18 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (1 idle, 0 queued) (147 total active threads) Queries in flight: 2 (0 queued); postgres DB 7 connections: 4/4 (1 threads blocked)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:07:51-06:00 INFO metabase.query-processor.middleware.cache Query took 87.0 ms to run; minimum for cache eligibility is 60.0 s
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:07:51-06:00 DEBUG metabase.server.middleware.log POST /api/card/218/query 202 [ASYNC: completed] 126.9 ms (18 DB calls) App DB connections: 2/15 Jetty threads: 4/50 (1 idle, 0 queued) (147 total active threads) Queries in flight: 1 (0 queued); postgres DB 7 connections: 4/4 (0 threads blocked)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:07:51-06:00 INFO metabase.query-processor.middleware.cache Query took 72.0 ms to run; minimum for cache eligibility is 60.0 s
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:07:51-06:00 DEBUG metabase.server.middleware.log POST /api/card/358/query 202 [ASYNC: completed] 128.4 ms (18 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (1 idle, 0 queued) (147 total active threads) Queries in flight: 0 (0 queued); postgres DB 7 connections: 5/5 (1 threads blocked)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:08:02-06:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [**********········································] 😞   20% Table 705 'securitygroups_default'
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:08:26-06:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [***************···································] 😕   30% Table 771 'aow_processed'
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:08:34-06:00 INFO metabase.sync.util FINISHED: step 'fingerprint-fields' for mysql Database 73 'CareCRM-Prod' (1.4 mins)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:08:34-06:00 INFO metabase.sync.util STARTING: step 'classify-fields' for mysql Database 73 'CareCRM-Prod'
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:08:34-06:00 INFO metabase.sync.analyze classify-fields Analyzed [********************······························] 😐   40% Table 620 'aos_contracts_documents'
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:08:34-06:00 INFO metabase.sync.analyze classify-fields Analyzed [*************************·························] 😬   50% Table 684 'aos_products_quotes_audit'
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:08:34-06:00 INFO metabase.sync.analyze classify-fields Analyzed [******************************····················] 😌   60% Table 750 'surveyquestionresponses_audit'
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:08:34-06:00 INFO metabase.sync.util FINISHED: step 'classify-fields' for mysql Database 73 'CareCRM-Prod' (53.1 ms)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:08:34-06:00 INFO metabase.sync.util STARTING: step 'classify-tables' for mysql Database 73 'CareCRM-Prod'
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:08:34-06:00 INFO metabase.sync.analyze classify-tables Analyzed [**********************************················] 😏   70% Table 599 'fp_events_contacts_c'
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:08:34-06:00 INFO metabase.sync.analyze classify-tables Analyzed [****************************************··········] 😊   80% Table 663 'fp_events_fp_event_locations_1_c'
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:08:34-06:00 INFO metabase.sync.analyze classify-tables Analyzed [********************************************······] 😍   90% Table 728 'securitygroups_audit'
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:08:34-06:00 INFO metabase.sync.util FINISHED: step 'classify-tables' for mysql Database 73 'CareCRM-Prod' (59.6 ms)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:08:34-06:00 INFO metabase.sync.util FINISHED: Analyze data for mysql Database 73 'CareCRM-Prod' (1.4 mins)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:10:00-06:00 INFO metabase.task.sync-databases Starting sync task for Database 5.
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:10:00-06:00 INFO metabase.sync.util STARTING: Sync metadata for mysql Database 5 'CareCRM'
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:10:00-06:00 INFO metabase.sync.util FINISHED: step 'sync-timezone' for mysql Database 5 'CareCRM' (704.1 µs)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:10:00-06:00 INFO metabase.sync.util STARTING: step 'sync-tables' for mysql Database 5 'CareCRM'
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:10:00-06:00 INFO metabase.sync.util STARTING: step 'sync-timezone' for mysql Database 5 'CareCRM'
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:10:00-06:00 INFO metabase.sync.util FINISHED: step 'sync-tables' for mysql Database 5 'CareCRM' (59.9 ms)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:10:00-06:00 INFO metabase.sync.util STARTING: step 'sync-fields' for mysql Database 5 'CareCRM'
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:10:00-06:00 INFO metabase.sync.util FINISHED: step 'sync-fields' for mysql Database 5 'CareCRM' (828.9 ms)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:10:00-06:00 INFO metabase.sync.util STARTING: step 'sync-fks' for mysql Database 5 'CareCRM'
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:10:01-06:00 INFO metabase.sync.util FINISHED: step 'sync-fks' for mysql Database 5 'CareCRM' (270.7 ms)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:10:01-06:00 INFO metabase.sync.util STARTING: step 'sync-metabase-metadata' for mysql Database 5 'CareCRM'
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:10:01-06:00 INFO metabase.sync.util FINISHED: step 'sync-metabase-metadata' for mysql Database 5 'CareCRM' (55.3 ms)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:10:01-06:00 INFO metabase.sync.util FINISHED: Sync metadata for mysql Database 5 'CareCRM' (1.2 s)
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:10:01-06:00 INFO metabase.sync.util STARTING: Analyze data for mysql Database 5 'CareCRM'
[f507a07b-961c-48f6-88a9-7c0cccc4c602] 2021-12-02T21:10:01-06:00 INFO metabase.sync.util STARTING: step 'fingerprint-fields' for mysql Database 5 'CareCRM'
```

</details>

**To Reproduce**
1. Go to a question
2. Click on 'Summarize'
3. Select 'Count' and 'Opportunity Submit Date - by day'
4. Filter records between 9/1/21 and 12/2/21
5. Notice count includes dates for 8/31/21

**Expected behavior**
Accurate and reliable data available for analysis 

**Screenshots**
![image](https://user-images.githubusercontent.com/16417948/144556794-d7231290-6cab-4cb7-9a70-89edf4ac5238.jpeg)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "iPhone",
    "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 15_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Mobile/15E148 Safari/604.1",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "3.10.105",
    "user.language": "en",
    "user.timezone": "US/Central"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2",
      "mysql",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-12-01",
      "tag": "v0.41.3",
      "branch": "release-x.41.x",
      "hash": "b0ac6f2"
    },
    "settings": {
      "report-timezone": "US/Central"
    }
  }
}
```

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
This is preventing our CEO from properly analyzing team performance.

**Comment by flamber** [comment] 2021-12-03 09:55
Hi @titanzrule32 
Timezones are difficult: https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html
Is your Postgres database column without timezone? If yes, then this is a duplicate of #3914/#6259/#11819

**Comment by titanzrule32** [comment] 2021-12-09 22:07
This database is MongoDB, not PG. We are also experiencing a similar display issue with month labels.
![image](https://user-images.githubusercontent.com/16417948/145483370-33e14d69-eb7e-4afb-9a38-2c8761955b4c.png)

**Comment by flamber** [comment] 2021-12-10 09:12
@titanzrule32 Okay, that would have been helpful information, since the logs you included only had information about Postgres.
Duplicate of #11149

**Closed by flamber** 2021-12-10 09:12 UTC
Labels: Type:Bug, .Needs Triage
