### ISSUE TITLE
When clicking 'Switch to SQL', remember database selection if no table chosen

### ISSUE THREAD

**Issue by powderham** [metabase/metabase#4710] opened 2017-04-06 09:54 UTC
If you choose a database, but not a table, if you then click 'Switch to SQL' such as to paste a template you revert back to the default database.

It would be better if the chosen database was persisted through the clicking of the switch to SQL button.

**Comment by tlrobinson** [comment] 2017-04-07 17:14
Duplicate of #2410

**Closed by tlrobinson** 2017-04-07 17:14 UTC
Labels: Enhancement, Query Builder/Native, UX
