### ISSUE TITLE
Anonymous Access

### ISSUE THREAD

**Issue by Woklet** [metabase/metabase#3559] opened 2016-10-13 14:07 UTC
This is not necessarily a feature request _yet_ but is there any way to allow anonymous access to Metabase's reports? Ideally, I'd like to have some questions that are accessible to the public.

**Comment by camsaul** [comment] 2016-10-13 18:19
Related to (or possible duplicate of) #1380

**Comment by camsaul** [comment] 2016-10-13 18:20
@Woklet unfortunately Metabase doesn't currently support any sort of anonymous access.

**Comment by salsakran** [comment] 2016-12-29 23:14
this is subsumed of #3680  and #3681

**Closed by salsakran** 2016-12-29 23:14 UTC
Labels: Proposal
