### ISSUE TITLE
Replace missing values with zero in line graphs seems to be working incorrectly

### ISSUE THREAD

**Issue by fernandosjp** [metabase/metabase#5800] opened 2017-08-23 12:33 UTC
**Context:**
-Chrome Version 56.0.2924.87 (64-bit)
-Ubuntu 16.04 LTS
-Database: Postgres
-Metabase version: 0.25.2
-Metabase hosting environment: Linux/Ubuntu 16
-Metabase internal database: Postgres

**Description:** The weird behavior I'm facing is that when trying to replace missing values by zero in a line graph, all graph data points become zeroes.

**Repeatable steps to reproduce the issue**
1. Buil a line graph with missing values
2. Enter configuration and in the display section try to set replace the missing value setting from 'linear interpoled' to 'zero' (image 1)
3. BUG: all graph data points become zero (image 2)

![image](https://user-images.githubusercontent.com/4928401/29615840-c201a5b8-87e5-11e7-91b3-26b9bd29c18d.png)
![image](https://user-images.githubusercontent.com/4928401/29615874-e66af99a-87e5-11e7-87b3-cb1c007d6787.png)

**Comment by mazameli** [comment] 2017-08-23 18:50
Seems like [this old issue](https://github.com/metabase/metabase/issues/4277) has resurfaced?

**Comment by fernandosjp** [comment] 2017-08-23 18:56
Exactly the same behavior!

**Comment by ricardojmendez** [comment] 2017-08-29 12:18
This is also the same issue as #4802

**Comment by camsaul** [comment] 2017-10-20 00:37
Yup, this is the same issue

Closing as duplicate of #4802

**Closed by camsaul** 2017-10-20 00:37 UTC
Labels: Bug, Priority/P2, Visualization/Chart Settings
