### ISSUE TITLE
Base type change of a field used in aggregations partially breaks questions

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#23155] opened 2022-06-03 21:51 UTC
**Describe the bug**

When a field base type used in an aggregation changes it breaks duplicating the question and drilling into the question from a dashboard.

**To Reproduce**
1. Create a native question Q1 and save it
```sql
select 1 x, 1 y 
union all select 2 x, 2 y 
union all select 3 x, 3 y 
union all select 4 x, 4 y 
```
2. Click "Explore results"
3. Group by X Unbinned, Summarize by Sum of Y and save as a Q2
4. Add it on a D1 dashboard
5. Change the Q1 question query:
```sql
select 1 x, 1 y 
union all select 2 x, 2 y 
union all select 3 x, 3 y 
union all select 4 x, 4.5 y 
```
6. Open D1 dashboard and click on the Q1 question title — it opens a broken question
7. Open Q1 and duplicate the question — the duplicated question is broken

**Comment by alxnddr** [comment] 2022-06-03 21:58
@flamber I'm wondering if you have any thoughts about the root cause. Seems like an upgrade issue.

**Comment by flamber** [comment] 2022-06-05 11:34
Looks like the question was stored with Sum as `["sum",["field","column_name",{"base-type":"type/BigInteger"}]]`, but the new base-type is now `type/Decimal`, which seems to remove the field and by such the entire summarize section.
Not sure if this is BE or FE, but feels like it's related #19757 and #14016

**Comment by uladzimirdev** [comment] 2023-11-08 12:28
I tried 4 different versions: 0.40.8, 0.43.2 (which was actual at the moment of reporting), 0.45.0 and master (0.47.7) - and couldn't reproduce it

**Comment by bshepherdson** [comment] 2024-02-16 14:22
I can't reproduce this in 0.43.2 or master. It's not clear that the original report was against a released version instead of master. I'm closing this issue; we can reopen if there's still a way to reproduce this.

**Closed by bshepherdson** 2024-02-16 14:22 UTC
Labels: Type:Bug, Priority:P2, Querying/Native, .Backend, Querying/GUI, .Wanted: MLv2
