### ISSUE TITLE
Cannot read property 'type' of undefined - Bug After adding Markdown Component

### ISSUE THREAD

**Issue by kevalkothari** [metabase/metabase#12915] opened 2020-07-15 07:07 UTC
**Describe the bug**

Getting error below as soon as you add markdown in existing dashboard,  After that dashboard no longer accessible. Need to archive it and create new from fresh.

`Cannot read property 'type' of undefined`

**Logs**
```
app-main.bundle.js?99a5979f407148c10717:5 TypeError: Cannot read property 'type' of undefined
    at Function.value (app-main.bundle.js?99a5979f407148c10717:5)
    at e.value (app-main.bundle.js?99a5979f407148c10717:5)
    at app-main.bundle.js?99a5979f407148c10717:5
    at i (app-main.bundle.js?99a5979f407148c10717:5)
    at e.n.value (app-main.bundle.js?99a5979f407148c10717:5)
    at app-main.bundle.js?99a5979f407148c10717:5
    at Array.map (<anonymous>)
    at app-main.bundle.js?99a5979f407148c10717:5
    at app-main.bundle.js?99a5979f407148c10717:5
    at dispatch (vendor.bundle.js?99a5979f407148c10717:1)
```

**To Reproduce**
1. Create New Dashboard or Edit Existing Dashboard
2. Add Markdown component in dashboard 
3. Add any text in Markdown editor
4. Save Dashboard 
5. Reload page - Boom - you will see the error

**Expected behavior**
Should open dashboard normally

**Screenshots**
Create New Dashboard
![Dashboard1](https://user-images.githubusercontent.com/1439447/87514329-b529d380-c697-11ea-9780-9c8c8c90b7bd.jpg)

Edit Dashboard and Add Markdown
![Dashboard2](https://user-images.githubusercontent.com/1439447/87514390-cecb1b00-c697-11ea-811e-25f1813d6f4c.jpg)

Save Dashboard and Refresh - Error will come
![Dashboard3](https://user-images.githubusercontent.com/1439447/87514491-f28e6100-c697-11ea-8b52-609c7c27f915.jpg)

**Information about your Metabase Installation:**
- Metabase v0.36.0-rc2
- Running on Windows using Jar

You can get this information by going to Admin -> Troubleshooting.

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_161-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_161",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.161-b12",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Asia/Calcutta"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.36.0-rc2",
      "date": "2020-07-08",
      "branch": "remove-equiv-method-implementations",
      "hash": "5956b4d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
N/A.

**Additional context**
N/A

**Comment by flamber** [comment] 2020-07-15 08:18
Duplicate of #12873

**Closed by flamber** 2020-07-15 08:18 UTC
Labels: .Needs Triage, Type:Bug
