### ISSUE TITLE
Add multi language support for the UI

### ISSUE THREAD

**Issue by djvulee** [metabase/metabase#3385] opened 2016-09-23 14:42 UTC
### Feature requests and proposals
If the Metabase can support multi language beside the English, it may be more attractive to people. 

I do not know the community has any plan?  If we can set up a mechanism for this, the volunteer may can help this, such as me is likely to help to provide Chinese version.

**Comment by tlrobinson** [comment] 2016-09-26 18:00
Duplicate of #1451

**Closed by tlrobinson** 2016-09-26 18:00 UTC
Labels: Duplicate
