### ISSUE TITLE
Stop refreshing query's everytime a dashboard is opened

### ISSUE THREAD

**Issue by FlorianHoevelmann** [metabase/metabase#2429] opened 2016-04-26 16:58 UTC
We are currently having the problem that our server is heavily used by Metabase.  Is there any way to update all Dashboards every half hour or something and not update them every time the website is opened?
Thanks in advance

**Comment by tlrobinson** [comment] 2016-04-27 02:41
Duplicate of #1666?

**Closed** 2016-04-27 07:45 UTC
