### ISSUE TITLE
Relative date filter field evades indices

### ISSUE THREAD

**Issue by nickcarenza** [metabase/metabase#6098] opened 2017-10-04 19:56 UTC
I set up a field filter on a timestamp column like this:

![image](https://user-images.githubusercontent.com/1222375/31196331-3855e37c-a902-11e7-9bc7-3d4dcaa2c8fc.png)
![image](https://user-images.githubusercontent.com/1222375/31196337-3d942510-a902-11e7-993a-b9261e3077c6.png)

My query in metabase looks like:
```sql
select ...
from ...
where ...
[[and {{created}}]]
```

The resulting sql is:

```sql
select ...
from ...
where ...
and date(`table`.`created`) BETWEEN '2017-09-27 00:00:00' AND '2017-10-03 00:00:00'
```

which cannot use an index on `created` which in this case is the most efficient.

Whereas this sql could:

```sql
select ...
from ...
where ...
and `table`.`created` BETWEEN '2017-09-27 00:00:00' AND '2017-10-03 00:00:00'
```

Why does Metabase add the `date` function when selecting a Relative date filter field and is there a way to stop it from doing that automatically? It makes my queries take 10x longer.

Metabase version v0.23.1

**Comment by Teods** [comment] 2018-02-15 12:26
Same problem here with Metabase version v0.28.1
The relative date widget encapsulate the field with the date function which cannot use an index.

Maybe a select box to activate or not the date function encapsulation when the widget "relative date" is selected could be a workaround.

**Comment by GabrielCampbellHaud** [comment] 2018-07-05 09:49
Same problem with V0.29.3  was wondering if any1 has some update

**Comment by flamber** [comment] 2019-02-19 04:52
This is most likely a duplicate of #4043

**Comment by tlrobinson** [comment] 2019-07-10 00:58
Duplicate of #4043

**Closed by tlrobinson** 2019-07-10 00:58 UTC
Labels: Performance, Query Processor
