### ISSUE TITLE
Possibility to select a month in the future in the 'month and year" date filter.

### ISSUE THREAD

**Issue by Guillaume-CORRE** [metabase/metabase#49588] opened 2024-11-06 10:50 UTC
**Is your feature request related to a problem? Please describe.**
I can't select a month in the future using the 'month and year" date filter. But I can select a month from 1901 which is frustrating.

**Describe the solution you'd like**
I can select a month in the future. January 2025 - 2026

**Describe alternatives you've considered**
Using other filter date type. But the the 'month and year" date filter is the most adapted filter to my monitoring.

**How important is this feature to you?**
Very important, we are monitoring deals performance month by month

**Additional context**
![Image](https://github.com/user-attachments/assets/32c6c644-8a2f-4e82-93fb-bfe79ed0c6c9)

**Comment by paoliniluis** [comment] 2024-11-06 11:43
duplicate of https://github.com/metabase/metabase/issues/26386

**Closed by paoliniluis** 2024-11-06 11:43 UTC
Labels: Type:New Feature, .Needs Triage
