### ISSUE TITLE
Couldn't delete collection folder in the "Archive View"

### ISSUE THREAD

**Issue by arunura** [metabase/metabase#39917] opened 2024-03-09 19:01 UTC
### Describe the bug

Within the Archive view, unable to delete items by selecting the checkbox and hitting the "Delete" button at the bottom of the screen.

### To Reproduce

1. Go to 'View archive' screen
2. Check the checkbox next to a collection **Folder**  (not a question or dashboard)
3. Scroll down to the bottom of the view and click on the delete button.
4. See error in console. No action taken on the GUI. 
![image](https://github.com/metabase/metabase/assets/12698493/2e47f446-6492-4b16-9ad9-88fe5abf2930)

### Expected behavior

Should delete the folder

### Logs

Not applicable. Frontend error. Please see screenshot.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.10+7-Debian-1deb12u1",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-17",
    "java.version": "17.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.10+7-Debian-1deb12u1",
    "os.name": "Linux",
    "os.version": "6.1.0-18-cloud-amd64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-02-22",
      "tag": "v0.48.7",
      "hash": "c192db1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Low

**Comment by paoliniluis** [comment] 2024-03-09 19:03
Duplicate of https://github.com/metabase/metabase/issues/39916

**Closed by paoliniluis** 2024-03-09 19:03 UTC
Labels: Type:Bug, .Needs Triage
