### ISSUE TITLE
Native query execution without editing query permissions

### ISSUE THREAD

**Issue by x670** [metabase/metabase#11590] opened 2019-12-25 10:40 UTC
**Is your feature request related to a problem? Please describe.**
Running native queries requires /db/X/native permission, that could be gathered only by enabling sql editing. I want to write queries by myself, but allow other users to run them directly without permission to edit queries, they could write.

**Describe the solution you'd like**
Make possible to allow running native queries, but not editing them in data permissions tab.

**How important is this feature to you?**
Very important

**Additional context**
To reproduce:
Analyst with sql writing query permissions:
1. Write some native query and save it
2. Try to run it or download result
3. Ok
User, having access to tables, that used in query and to collection where query saved:
1. Open native query directly from collection
2. Try to run it or download result
3. Permission error

**Comment by flamber** [comment] 2019-12-25 20:46
Hi @x670 
That's already possible via Admin > Permission > Collection permission.
You can give the user no data/SQL permissions, and then give them view-only to a collection.
It seems like you're reporting a bug, since you provided steps to reproduce, but which version of Metabase are you using?

**Comment by x670** [comment] 2019-12-26 08:20
I am using Metabase 0.34 and used 0.33.4 with same behavior before 
[diagnostic info](https://pastebin.com/uEcBah6L)

If all data permissions unchecked:
```
[5d2ef905-f4cc-4194-bdf3-3a68617f7460] 2019-12-26T11:09:06+03:00 WARN metabase.middleware.log POST /api/dataset 403 2.3 ms (3 DB calls) "У вас нет полномочий на выполнение данного действия."
```
If group have access to tables, used in query without sql editing permission:
```[5d2ef905-f4cc-4194-bdf3-3a68617f7460] 2019-12-26T11:17:36+03:00 WARN metabase.query-processor.middleware.process-userland-query Query failure {:status :failed,
 :class clojure.lang.ExceptionInfo,
 :error "У вас нет разрешения на выполнение данного запроса.",
 :stacktrace
 ("--> query_processor.middleware.permissions$perms_exception.invokeStatic(permissions.clj:23)"
  "query_processor.middleware.permissions$perms_exception.invoke(permissions.clj:22)"
  "query_processor.middleware.permissions$fn__42264$check_ad_hoc_query_perms__42269$fn__42270.invoke(permissions.clj:32)"
  "query_processor.middleware.permissions$fn__42264$check_ad_hoc_query_perms__42269.invoke(permissions.clj:28)"
  "query_processor.middleware.permissions$fn__42287$check_query_permissions_STAR___42292$fn__42298.invoke(permissions.clj:40)"
  "query_processor.middleware.permissions$fn__42287$check_query_permissions_STAR___42292.invoke(permissions.clj:34)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__40540.invoke(cumulative_aggregations.clj:57)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__42873.invoke(resolve_joins.clj:184)"
  "query_processor.middleware.limit$limit$fn__41651.invoke(limit.clj:19)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__45642.invoke(results_metadata.clj:87)"
  "query_processor.middleware.format_rows$format_rows$fn__41639.invoke(format_rows.clj:76)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__37181.invoke(add_dimension_projections.clj:232)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__37904.invoke(add_source_metadata.clj:107)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__42923.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__37741.invoke(add_row_count_and_status.clj:16)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__40615.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__42537.invoke(resolve_driver.clj:22)"
  "query_processor.middleware.store$initialize_store$fn__45667$fn__45668.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__45667.invoke(store.clj:10)"
  "query_processor.middleware.async$async__GT_sync$fn__22968.invoke(async.clj:23)"
  "query_processor.middleware.async_wait$runnable$fn__39657.invoke(async_wait.clj:89)"),
 :query
 {:native {:query "select car_id from car limit 100", :template-tags {}},
  :type "native",
  :parameters [],
  :async? true,
  :middleware {:add-default-userland-constraints? true, :userland-query? true},
  :info
  {:executed-by 111,
   :context :ad-hoc,
   :card-id nil,
   :nested? false,
   :query-hash [83, -26, 119, 78, -57, 8, -26, -58, 120, 115, 84, 90, 6, -64, -64, 126, 95, 21, 19, 121, 96, 23, 33, -107, -41, 91, 58, -113, 121, 13, 81, -4]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :ex-data {:required-permissions #{"/db/2/native/"}, :actual-permissions #{"/collection/2/" "/collection/236/" "/db/2/schema/public/table/80/" "/collection/182/"}, :permissions-error? true}}

[5d2ef905-f4cc-4194-bdf3-3a68617f7460] 2019-12-26T11:17:36+03:00 DEBUG metabase.middleware.log POST /api/dataset 200 [ASYNC: completed] 58.5 ms (8 DB calls) Jetty threads: 2/50 (6 idle, 0 queued) (109 total active threads) Queries in flight: 0```

**Comment by flamber** [comment] 2019-12-26 15:12
@x670 
`POST /api/dataset` is used for queries that are not saved. If you visit a saved question, then the request should be `POST /api/card/:id/query`.
There's a small issue with 0.34.0, which might be causing this for some questions - #11572.

Can you give more details about the native questions the can/cannot be opened?
I'm not able to reproduce your issue, so any details you can provide would help.

Just translating error message for search:
`У вас нет полномочий на выполнение данного действия.`: `You don't have permissions to do that.`
`У вас нет разрешения на выполнение данного запроса.` : `You do not have permissions to run this query.`

**Comment by x670** [comment] 2019-12-27 08:45
@flamber 
I believe, this is another issue.

Only difference, I found - "unsaved" questions had no any filters. Just adding `[[and {{a}}]]` to query resolved permission error. So, to reproduce bug you need to save question without any filters.

**Comment by flamber** [comment] 2019-12-27 11:32
@x670 I'm unable to reproduce your issue. I've done multiple tries, but without more details or a complete steps-to-reproduce, I'm not sure what's going on.

**Comment by x670** [comment] 2019-12-27 15:41
@flamber 
Which details could help you?
I am just configured server and working with it for a long time and at one time discovered, that native queries couldn't be opened by users. First time wath around a year ago, but then there was another ways to solve tasks and that was not such  unhandy.

-There is nothing unusual in logs. 
-I checked metabase db (using Postgres 9.6), compared both queries in tables, where they could be (report_card, revision, query_execution, query) and there is no any  suspicious differences. 
Checked requests, that made by frontend after page loaded and before /api/dataset or /api/card/:id/query and there no differences too. Only difference - after page loaded, some data (hash or b64) added to url as when question is edited
Maybe I need somehow debug frontend scripts to catch moment where behavior is changed and api/dataset is fired?

**Comment by flamber** [comment] 2019-12-27 16:42
@x670 Okay, I'm still trying to reproduce this. I'll do some more tests.
1. That's #11572
2. There was a change in 0.34.0 (#11517), where missing template-tags are treated as empty, but that shouldn't have any impact on permissions (I'm still testing, so there might be something here)

Both of those points are introduced in 0.34.0, so since you said that the problem also existed on 0.33.4, then we can disregard those.
There was an issue on 0.33.4/5 (#11297), where non-Native questions would fail to load with certain permissions, which was fixed on 0.33.6, but your problem is specific to Native questions.
Could you test 0.33.7.3?

**Comment by flamber** [comment] 2019-12-27 17:51
@x670 Now I've reproduced your issue on 0.34.0! :tada: 
It is caused by the same problems as issue #11572. The problem is that Metabase thinks the query has been changed and tries to run the "new" query, but since the user is not allowed to change the query, then it gives a permission error.
But I cannot reproduce your issue on 0.33.7.3 or 0.33.4

**Comment by salsakran** [comment] 2019-12-28 00:18
closing as a dupe of #11572 , and escalated that to a P1 @x670

**Closed by salsakran** 2019-12-28 00:18 UTC
Labels: .Needs Triage, Type:New Feature
