### ISSUE TITLE
Filtered by - use "OR" alternative to "AND" operator ?

### ISSUE THREAD

**Issue by mokra** [metabase/metabase#5870] opened 2017-09-01 15:14 UTC
Is there a possibility for a normal user to decide whether chosen filters in the "Filtered by" section are applied as "and" or "or" ?
Of not, the is the only alternative a custom SQL Question?

**Comment by joshuashort** [comment] 2017-09-01 20:29
I'd really like to see filter logic in the query builder -- maybe as an 'advanced' option if the goal is to present the simplest approach by default.

**Comment by salsakran** [comment] 2017-09-07 00:56
Has anyone come up with an UI for this that doesn't look like a jumbled up puzzle?

**Comment by salsakran** [comment] 2017-09-07 00:56
we're not opposed to adding ORs, it's just been a matter of UX and real estate.

**Comment by mokra** [comment] 2017-09-09 13:52
@salsakran 
how about something like this:
![untitled-1](https://user-images.githubusercontent.com/1849512/30240715-fd33b00c-9575-11e7-883e-5ddabf9dc252.jpg)

I belive that for most applications this will be enough.
So in the end, the algorithm should descide how to put the brackets. But it should work the way it does in the machine logic:
* *A* AND *B* OR *C* = (*A* AND *B*) OR *C*
* *A* OR *B* OR *C* = *A* OR  *B* OR *C*
* *A* OR *B* AND *C* = *A* OR (*B* AND *C*)
* *A* AND *B* OR *C* AND *D* OR *E* = (*A* AND *B*) OR (*C* AND *D*) OR *E*

This procedure should be enough and if a user wishes for more complex stuff, I believe he should go for custom SQL.
What do you say?

**Comment by mokra** [comment] 2017-09-16 14:18
@salsakran - do you have any comments?

**Comment by mazameli** [comment] 2017-10-27 19:49
I've thought about this a little, and here's one way that I think this could work:
1. The filter popover menu doesn't change at all.
2. When each filter after the first is added, it defaults to ANDs in between, as this is the existing (invisible) behavior.
3. Clicking on the AND simply toggles it to an OR, and vice a versa.
4. The X button on filters has been moved into the filter token to reduce clutter.
5. I think @mokra's suggestion for how the mixed and/or logic should work is reasonable enough.

Screens:

Starting scenario, with one filter already present:

![00 start state](https://user-images.githubusercontent.com/2223916/32115754-e1d80e50-bafc-11e7-9cbd-b7798888c357.png)

Subsequent filters that are added default to having ANDs between them:

![01 and and](https://user-images.githubusercontent.com/2223916/32115794-04094994-bafd-11e7-86fc-0b79156c6901.png)

The ANDs can be clicked on to change them to ORs, and vice a versa:

![02 click](https://user-images.githubusercontent.com/2223916/32115848-3c919a64-bafd-11e7-886d-b9e90312cf8b.png)

The AND has been changed to an OR:

![03 and or](https://user-images.githubusercontent.com/2223916/32115860-45f4fbfa-bafd-11e7-9f8c-d6dc6a901001.png)

One possible riff would be to increase the padding between ORs and decrease the padding between ANDs when they're mixed in order to clarify the logical groupings:

![spaced out or](https://user-images.githubusercontent.com/2223916/32122346-dcd073b2-bb14-11e7-9d6f-32cc1e3502b9.png)

This would hopefully clarify a scenario like this, where the user is trying to find orders from female users in either one group of states, or orders from female users in a different group of states:

![spaced out or with 2nd and](https://user-images.githubusercontent.com/2223916/32122402-0fab5b26-bb15-11e7-8e96-884bc1318bfa.png)

**Comment by mokra** [comment] 2017-11-02 06:13
This is great! 
I like it, how you simplified it - especially with the "X" moving to the filter

**Comment by camsaul** [comment] 2017-11-11 02:12
Duplicate of #3217.

@mazameli I'll copy over your designs to that issue

**Closed by camsaul** 2017-11-11 02:12 UTC
Labels: New Feature, Proposal, Query Builder
