### ISSUE TITLE
Relative date filter query not using index

### ISSUE THREAD

**Issue by andreme** [metabase/metabase#26655] opened 2022-11-21 23:14 UTC
**Describe the bug**

When using the `Relative Date` Field Filter the query that is created casts the column, which prevents index usage. 

Query: `SELECT * FROM "user" WHERE {{user_created}}`
Plan: `Filter: (((created_at)::date >= '2022-11-14'::date) AND ((created_at)::date <= '2022-11-20'::date))`

`user.create_at` is a `timestamptz` column.

**To Reproduce**
- Create a SQL question in a postgres db for a table that has a timestamptz column and use a Relative Date Field Filter on it
- Look at the created query or use explain

**Expected behavior**
I expect the column not to be cast as implemented here: #14835

**Information about your Metabase Installation:**

- Your databases: Postgres
- Metabase version: v0.44.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
Annoying, makes queries for much longer than necessary.

**Additional context**
Seems to be the same as #15275

**Comment by paoliniluis** [comment] 2022-11-21 23:29
Hi! this is a duplicate of https://github.com/metabase/metabase/issues/21133 and/or https://github.com/metabase/metabase/issues/20333

**Closed by paoliniluis** 2022-11-21 23:29 UTC
Labels: Type:Bug, .Needs Triage
