### ISSUE TITLE
MB Custom Query: Cannot format column aggregated with a "Sum of..."

### ISSUE THREAD

**Issue by antoine-lizee** [metabase/metabase#9865] opened 2019-04-28 23:26 UTC
### Reproducible steps

- Go to the custom query builder
- Chose a Group, create a sum of ... aggregation

I can only change the name of the columns, whereas I would need to remove the decimal places, etc....

See:
![image](https://user-images.githubusercontent.com/2957716/56871402-7c172c00-6a1d-11e9-90f2-0be3947334d4.png)

Compare to:
![image](https://user-images.githubusercontent.com/2957716/56871410-c698a880-6a1d-11e9-804a-fb2310eae5a1.png)

This might be the case for other aggregations, but works okay with count()

---

If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: **Chrome 73.0**
- Your operating system: **OSX 10.14**
- Your databases: **PostGres**
- Metabase version: **0.32.2**
- Metabase hosting environment: **Heroku**
- Metabase internal database: **Postgres**

**Comment by flamber** [comment] 2019-04-29 01:33
Hi @antoine-lizee 
I cannot reproduce on 0.32.5 - here's an example using Sample Dataset (H2) from `Orders` with "Sum of `Total`" and grouped by "`Created at`: Year"
![image](https://user-images.githubusercontent.com/1447303/56872984-12325e80-69ec-11e9-89e7-fc5ee4cc6916.png)
What is the Field Type of column you're trying to sum?
Admin Settings > Data Model > (database) > (table) > (field) :gear:

**Comment by flamber** [comment] 2020-03-03 15:11
Closing since there hasn't been any new reports and I cannot reproduce on 0.34.3

**Closed by flamber** 2020-03-03 15:11 UTC
Labels: .Unable to Reproduce
