### ISSUE TITLE
Metabase v0.47.0 export **json, csv, excel** failed.

### ISSUE THREAD

**Issue by xoxmono** [metabase/metabase#33488] opened 2023-08-25 03:54 UTC
**Describe the bug**
 Metabase v0.47.0 export **json, csv, excel** failed.

**Logs**

**To Reproduce**

1. Go to some question.
2. Click on export ".xlsx".
3. Downloaded file.
4. Open file with error "File format or file extention is not valid."

**Expected behavior**
Open file without any error

**Severity**
Severity level: High
Note: Some business user need to export data and analyze on other tools.

**Metabase Diagnostic Info**

```
{
  "browser-info": {
    "language": "th-TH",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.53.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-08-16",
      "tag": "v0.47.0",
      "branch": "release-x.47.x",
      "hash": "682ec2d"
    },
    "settings": {
      "report-timezone": "Asia/Bangkok"
    }
  }
}
```

**Comment by paoliniluis** [comment] 2023-08-25 06:41
Dupe of https://github.com/metabase/metabase/issues/33244

**Closed by paoliniluis** 2023-08-25 06:41 UTC
