### ISSUE TITLE
Sorting issue

### ISSUE THREAD

**Issue by sashankQ** [metabase/metabase#6336] opened 2017-11-06 17:48 UTC
I am using Query builder for generating reports on Google Analytics. When I try to add a sort field, I see only Groupby field or dimension field that can be added to sort list. But Can not see any metric fields under sort list.
I can manipulate it using a native query, But when I use the native query, I have filtering issues in case of the dashboard.
Can you guys please provide any solution for such situation.

**Comment by flamber** [comment] 2020-05-24 17:26
Duplicate of #4811

**Closed by flamber** 2020-05-24 17:26 UTC
Labels: Database/Google Analytics
