### ISSUE TITLE
Autoscale for Y axis does not support offset

### ISSUE THREAD

**Issue by LucasVerneyDGE** [metabase/metabase#12730] opened 2020-06-17 08:12 UTC
Hi,

**Is your feature request related to a problem? Please describe.**

I am drawing graphs with slight variations around a huge offset, such as:
![image](https://user-images.githubusercontent.com/58298410/84872478-3e8ebb80-b082-11ea-9cc8-de3c27a83d05.png)

When using automatic Y axis scale, it always shows the 0 values, instead of looking for a convenient offset.

**Describe the solution you'd like**

I'd like the graphs to have an offset feature (ideally automatic, could be manually specified as well) to make the scale easier to read. Drawing libraries such as matplotlib usually offer such a feature.

**Describe alternatives you've considered**

The only alternative I've found so far is to drop autoscale altogether and manually specify limits.

**How important is this feature to you?**

The alternative solution is a good workaround. It is doable, but definitely not very convenient in the long run or when dealing with tens of such graphs.

**Additional context**

**Comment by flamber** [comment] 2020-06-17 09:52
Hi @LucasVerneyDGE 
Looks like a duplicate of #7196 - upvote by clicking :+1: on the first post.

**Closed by flamber** 2020-06-17 09:52 UTC
Labels: .Needs Triage, Type:New Feature
