### ISSUE TITLE
Add binary operators in Custom Expressions and/or Segments

### ISSUE THREAD

**Issue by janmpeterka** [metabase/metabase#15332] opened 2021-03-25 12:10 UTC
**Is your feature request related to a problem? Please describe.**
We have many information encoded in `flags` BIGINT column (each bit representing one flag True/False).
Currently I didn't find a way to filter by this in Metabase (outside of Native query).

**Solution**
1) Add binary operators in Filter > Custom Expression or Allow raw SQL here.
2) Add Custom Expression to Segment creation

or 

1) Add way to create computed column for table in Admin Data panel - this will be simple as you can probably add raw SQL (as admin) and then all users can filter by this column.

**Alternatives**
For now one way is to create database views to do this. However, it clutters database and must go through some validation process in our team

**How important is this feature to you?**
Part of our data is not easily queriable because of this. We will probably use view-based approach for now, which mostly solves the issue.

**Comment by flamber** [comment] 2021-03-25 12:26
Sounds like a duplicate of #14054 / #13069 / #10327 / #1723

**Closed by flamber** 2021-03-25 12:26 UTC
Labels: .Needs Triage, Type:New Feature

**Comment by janmpeterka** [comment] 2021-03-25 12:33
Damn, I'm bad at searching. Thanks and sorry for bothering you with this :)

**Comment by ahmedsayedabdelsalam** [comment] 2024-01-22 12:15
is there a way to add a custom column to the table to check `flags & 1 = 1` ?

**Comment by janpeterka** [comment] 2024-01-22 13:08
@ahmedsayedabdelsalam You can create Model now, using SQL to add this sort of column

**Comment by ahmedsayedabdelsalam** [comment] 2024-01-22 16:30
thanks for your quick response. in which version please cuz i can't find how to do so.
