### ISSUE TITLE
Line chart seems not to do well with gaps in time series data

### ISSUE THREAD

**Issue by slangwald** [metabase/metabase#1395] opened 2015-10-28 21:35 UTC
"Gaps" in the data seem to be a problem for the line and area chart.
given:
![screenshot 2015-10-28 22 21 35](https://cloud.githubusercontent.com/assets/3797942/10803485/ad548bb4-7dc2-11e5-8916-b28a99f011bc.png)

the resulting line chart is:
![screenshot 2015-10-28 22 25 14](https://cloud.githubusercontent.com/assets/3797942/10803507/d14e4a3c-7dc2-11e5-9401-803b1998e95e.png)

Even though the missing dates are filled in automagically, the line chart suggests that there was a steady growth over the period each day. 

Cheers & thank you! :beers:

**Comment by agilliland** [comment] 2015-10-30 01:19
This is actually a duplicate of #896 which proposes that in scenarios like this the missing days should be accounted for.

**Closed by agilliland** 2015-10-30 01:19 UTC
Labels: duplicate
