### ISSUE TITLE
No visual feedback on clicking csv/xls etc on query download widget (download full result)

### ISSUE THREAD

**Issue by nitzien** [metabase/metabase#11901] opened 2020-02-13 04:01 UTC
**Is your feature request related to a problem? Please describe.**
Currently there is no visual feedback on clicking csv/xlsx/json etc on query download widget. Due to this users sometimes click it multiple time without realizing there are already requests in process. 

**Describe the solution you'd like**
Possibly, the widget should close and there should be a toast message informing user that request is being processed.

**Describe alternatives you've considered**
None

**How important is this feature to you?**
Not stopping us to use the tool but will help us to improve database server performance. 

**Additional context**
None

**Comment by flamber** [comment] 2020-02-13 21:45
Duplicate of #10566

**Closed by flamber** 2020-02-13 21:45 UTC
Labels: Reporting/Export, Type:UX
