### ISSUE TITLE
Assertion failure in mongodb driver when using saved question as source table

### ISSUE THREAD

**Issue by Subv** [metabase/metabase#5821] opened 2017-08-27 22:26 UTC
## Steps to reproduce:
* Connect Metabase to a MongoDB instance
* Create and save a new question (We will call this question A).
* Try to create a new question using A as a source table.

## Expected outcome:
Metabase properly uses the result of A as the input data for the new question.

## Actual outcome:
Assertion failure in `mbql->native` of the mongodb driver, specifically in the `(string? source-table-name)` precondition

I did some digging and found out that when using a normal table as the input, the `:source-table` member of `:query` is expanded to `:source-table {:name "collections.tst", :id 7}`, whereas when using a saved question, query is `:query {:source_table "card__1"}`; `source-table` doesn't have a `name` in this case.

Here's a stack trace of the problem:

```
08-27 16:24:00 WARN metabase.query-processor :: {:status :failed,
 :class java.lang.AssertionError,
 :error "Assert failed: (string? source-table-name)",
 :stacktrace
 ["driver.mongo.query_processor$mbql__GT_native.invokeStatic(query_processor.clj:457)"
  "driver.mongo.query_processor$mbql__GT_native.invoke(query_processor.clj:457)"
  "driver$fn__22570$G__22448__22577.invoke(driver.clj:45)"
  "query_processor.middleware.mbql_to_native$query__GT_native_form.invokeStatic(mbql_to_native.clj:17)"
  "query_processor.middleware.mbql_to_native$query__GT_native_form.invoke(mbql_to_native.clj:12)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__26496.invoke(mbql_to_native.clj:26)"
  "query_processor.middleware.annotate_and_sort$annotate_and_sort$fn__25019.invoke(annotate_and_sort.clj:41)"
  "query_processor.middleware.limit$limit$fn__26451.invoke(limit.clj:14)"
  "query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__26299.invoke(cumulative_aggregations.clj:46)"
  "query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__26299.invoke(cumulative_aggregations.clj:46)"
  "query_processor.middleware.format_rows$format_rows$fn__26442.invoke(format_rows.clj:21)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__27720.invoke(results_metadata.clj:88)"
  "query_processor.middleware.resolve$resolve_middleware$fn__24627.invoke(resolve.clj:329)"
  "query_processor.middleware.expand$expand_middleware$fn__26193.invoke(expand.clj:536)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__24711.invoke(add_row_count_and_status.clj:14)"
  "driver.mongo$process_query_in_context$fn__44997$f__44342__auto____44999.invoke(mongo.clj:59)"
  "driver.mongo.util$_with_mongo_connection$fn__44335.invoke(util.clj:116)"
  "util.ssh$with_ssh_tunnel_STAR_.invokeStatic(ssh.clj:106)"
  "util.ssh$with_ssh_tunnel_STAR_.invoke(ssh.clj:91)"
  "driver.mongo.util$_with_mongo_connection.invokeStatic(util.clj:95)"
  "driver.mongo.util$_with_mongo_connection.invoke(util.clj:90)"
  "driver.mongo$process_query_in_context$fn__44997.invoke(mongo.clj:58)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__26319.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__27730.invoke(resolve_driver.clj:14)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__25099.invoke(cache.clj:146)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__26241.invoke(catch_exceptions.clj:58)"
  "query_processor$process_query.invokeStatic(query_processor.clj:124)"
  "query_processor$process_query.invoke(query_processor.clj:120)"
  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:232)"
  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:227)"
  "query_processor$fn__27764$process_query_and_save_execution_BANG___27769$fn__27770.invoke(query_processor.clj:270)"
  "query_processor$fn__27764$process_query_and_save_execution_BANG___27769.invoke(query_processor.clj:256)"
  "api.dataset$fn__29566$fn__29569.invoke(dataset.clj:63)"
  "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:227)"
  "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:222)"
  "api.dataset$fn__29566.invokeStatic(dataset.clj:54)"
  "api.dataset$fn__29566.invoke(dataset.clj:54)"
  "middleware$enforce_authentication$fn__28955.invoke(middleware.clj:122)"
  "api.routes$fn__40141.invokeStatic(routes.clj:60)"
  "api.routes$fn__40141.invoke(routes.clj:60)"
  "routes$fn__40784$fn__40785.doInvoke(routes.clj:75)"
  "routes$fn__40784.invokeStatic(routes.clj:71)"
  "routes$fn__40784.invoke(routes.clj:71)"
  "middleware$log_api_call$fn__29054$fn__29056.invoke(middleware.clj:331)"
  "middleware$log_api_call$fn__29054.invoke(middleware.clj:330)"
  "middleware$add_security_headers$fn__29004.invoke(middleware.clj:245)"
  "middleware$bind_current_user$fn__28959.invoke(middleware.clj:142)"
  "middleware$maybe_set_site_url$fn__29008.invoke(middleware.clj:268)"],
 :query
 {:type "query",
  :query {:source_table "card__1"},
  :parameters [],
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :card-id 1,
   :nested? true,
   :query-hash [-111, 52, 7, -84, -21, 99, 43, 98, -39, 109, 97, 3, -41, -97, 74, -21, 45, 77, 57, -104, 9, 121, -46, 52, -32, -10, -119, -54, 59, 114, 12, -11],
   :query-type "MBQL"}},
 :expanded-query nil}

08-27 16:24:00 WARN metabase.query-processor :: Query failure: Assert failed: (string? source-table-name)
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:201)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:194)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:233)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:227)"
 "query_processor$fn__27764$process_query_and_save_execution_BANG___27769$fn__27770.invoke(query_processor.clj:270)"
 "query_processor$fn__27764$process_query_and_save_execution_BANG___27769.invoke(query_processor.clj:256)"
 "api.dataset$fn__29566$fn__29569.invoke(dataset.clj:63)"
 "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:227)"
 "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:222)"
 "api.dataset$fn__29566.invokeStatic(dataset.clj:54)"
 "api.dataset$fn__29566.invoke(dataset.clj:54)"
 "middleware$enforce_authentication$fn__28955.invoke(middleware.clj:122)"
 "api.routes$fn__40141.invokeStatic(routes.clj:60)"
 "api.routes$fn__40141.invoke(routes.clj:60)"
 "routes$fn__40784$fn__40785.doInvoke(routes.clj:75)"
 "routes$fn__40784.invokeStatic(routes.clj:71)"
 "routes$fn__40784.invoke(routes.clj:71)"
 "middleware$log_api_call$fn__29054$fn__29056.invoke(middleware.clj:331)"
 "middleware$log_api_call$fn__29054.invoke(middleware.clj:330)"
 "middleware$add_security_headers$fn__29004.invoke(middleware.clj:245)"
 "middleware$bind_current_user$fn__28959.invoke(middleware.clj:142)"
 "middleware$maybe_set_site_url$fn__29008.invoke(middleware.clj:268)"]
```

----
And here's a log of the expanded query when using a **normal table**:

```
08-27 16:30:10 DEBUG middleware.log ::
QUERY: ?
{:database 2,
 :type "query",
 :query {:source_table 7},
 :parameters [],
 :constraints {:max-results 10000, :max-results-bare-rows 2000},
 :info
 {:executed-by 1,
  :context :ad-hoc,
  :card-id nil,
  :nested? false,
  :query-hash [42, -23, 22, -18, -89, -73, -49, -84, 30, 69, 38, -107, -95, -19, 85, 125, -112, 106, -22, -104, -50, 58, 45, -56, 106, 51, 125, 43, -106, -110, 110, -17],
  :query-type "MBQL"}}

08-27 16:30:10 DEBUG mongo.util :: << OPENED NEW MONGODB CONNECTION >>
08-27 16:30:10 DEBUG query-processor.sort :: Sorted fields:
([:3-other 0 :0-id "_id"] [:3-other 0 :2-other "type"])

08-27 16:30:10 DEBUG middleware.log ::
PREPROCESSED/EXPANDED: ?
{:database {:name "test", :id 2, :engine :mongo, :details "? ", :features #{:basic-aggregations :nested-fields :dynamic-schema}},
 :type "query",
 :query
 {:source-table {:name "collections.tst", :id 7},
  :fields-is-implicit true,
  :fields
  ({:base-type :type/MongoBSONID,
    :table-id 7,
    :special-type :type/PK,
    :field-name "_id",
    :dimensions [],
    :field-display-name "ID",
    :values [],
    :visibility-type :normal,
    :position 0,
    :field-id 49,
    :table-name "collections.tst"}
   {:base-type :type/Float,
    :table-id 7,
    :special-type :type/Category,
    :field-name "type",
    :dimensions [],
    :field-display-name "Type",
    :values
    {:field-value-id 19, :field-id 48, :values (1.0 2.0), :human-readable-values {}, :created-at #inst "2017-08-27T21:23:25.288000000-00:00", :updated-at #inst "2017-08-27T21:23:25.288000000-00:00"},
    :visibility-type :normal,
    :position 0,
    :field-id 48,
    :table-name "collections.tst"}),
  :limit 2000},
 :constraints {:max-results 10000, :max-results-bare-rows 2000},
 :info
 {:executed-by 1,
  :context :ad-hoc,
  :nested? false,
  :query-hash [42, -23, 22, -18, -89, -73, -49, -84, 30, 69, 38, -107, -95, -19, 85, 125, -112, 106, -22, -104, -50, 58, 45, -56, 106, 51, 125, 43, -106, -110, 110, -17],
  :query-type "MBQL"},
 :driver "MongoDB",
 :settings {},
 :fk-field-ids #{}}
```

## Specs
Browser: Firefox Nightly 57.0a1
OS: Windows 10
Database: MongoDB
Metabase version: v0.25.2 (35bce2dfd29cb44b252b6ce61456262eb2f40344)
Hosting environment: Windows 10 localhost

**Comment by salsakran** [comment] 2017-09-07 00:41
dupe of #5645

**Closed by salsakran** 2017-09-07 00:41 UTC
