### ISSUE TITLE
Links to related table when viewing record detail

### ISSUE THREAD

**Issue by littlegoblin9876** [metabase/metabase#7927] opened 2018-06-22 19:37 UTC
- Your browser and the version: Chrome 49.0.2623.75 
- Your operating system: Linux
- Your databases:Postgres
- Metabase version: v0.29.3
- Metabase hosting environment: Linux/Centos 6
- Metabase internal database:  Postgres

- *Repeatable steps to reproduce the issue*
Drill down to a record that is FK'd to one or more tables as defined in the metabase data model. 
When page renders, the "This XXXXXX is Connected to" section displays  searching icon - never resolves.
If you press "refresh" the cursor disappears and link summary is displayed.

**Comment by flamber** [comment] 2019-02-22 01:51
Hi @littlegoblin9876 
This looks like a duplicate of #6830

**Comment by salsakran** [comment] 2019-08-05 05:20
closing this as a dupe of #6830 which is already a P1

**Closed by salsakran** 2019-08-05 05:20 UTC
Labels: Priority:P2, Query Builder, Type:Bug
