### ISSUE TITLE
Connect MongoDB with SSL and self-signed certificate

### ISSUE THREAD

**Issue by gsuess** [metabase/metabase#3877] opened 2016-12-06 17:58 UTC
Still cannot use metabase with mongodb hosted on compose.io.

Reason:

Compose.IO uses self-signed SSL certificates for each deployment.

Therefore need a way to supply a custom pem file for this.

Without it I get this error:

```
12-06 17:50:48 ERROR metabase.driver :: Failed to connect to database: com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=aws-eu-west-1-portal.X.dblayer.com:XXXXX, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}, caused by {sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}, caused by {sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}}] 
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or :+1: comment

**Comment by camsaul** [comment] 2016-12-06 19:38
Hi @gsuess, if you have a sense of what options need to be passed to Mongo to support this and some basic familiarity with Clojure, we'd love to have you as a contributor and would welcome a PR to support this 👍

**Comment by gsuess** [comment] 2016-12-06 21:03
Not at all familiar with clojure (or LISP), but here is what I can share...

https://www.compose.com/articles/connecting-to-the-new-mongodb-at-compose/#whatsthatsslallowinvalidcertificates

So to add support for it, an option on the UI where users can paste the public key is required, which would be basically just another connection option.

**Comment by j005u** [comment] 2016-12-09 14:38
This worked for me:

Save your certificate to disk and convert it to a jks trust store with keytool like so:
`keytool -import -alias cacert -keypass changeit -keystore cacerts.jks -file *compose-cert.pem*`

Then run metabase with:
`java -Djavax.net.ssl.trustStore=cacerts.jks -Djavax.net.ssl.trustStorePassword=changeit -DinvalidHostNameAllowed=true -jar metabase.jar`

Only figured this out because I was running into similar problems with another Java based BI tool. Their error messaging was even worse...

**Comment by camsaul** [comment] 2016-12-09 19:27
@j005u thanks for the tip. @gsuess can you try and see if that works for you?

If so I'll add this to the documentation so others can find it as well 😻

**Comment by gsuess** [comment] 2016-12-11 15:31
Well I guess I would have to fork the heroku build for that... Not an easy undertaking, but will look into it.

**Comment by j005u** [comment] 2016-12-14 12:53
So I can confirm that the above method will break connecting to other SSL services as they're no longer in the trust store. For example Slack integration will no longer work.

This will work however:

`cp /usr/lib/jvm/default-jvm/jre/lib/security/cacerts ./cacerts.jks
keytool -import -alias cacert -storepass changeit -keystore cacerts.jks -file compose-cert.pem

java -Djavax.net.ssl.trustStore=cacerts.jks -Djavax.net.ssl.trustStorePassword=changeit -jar metabase.jar`

Also, for Docker, one can use _JAVA_OPTIONS instead of JAVA_OPTIONS to pass the extra arguments as the latter is overwritten by /app/run_metabase.sh.

**Comment by gsuess** [comment] 2016-12-20 17:12
Yea that works. Thank you @j005u.

For heroku I had to commit the keystore a metabase-deploy fork and modify `/bin/start` accordingly, which is not ideal.

**Comment by camsaul** [comment] 2017-05-04 18:56
@j005u, do you think you could submit a PR to support programmatically adding another trust store? If you have a sense of what needs to be done and some basic familiarity with Clojure, we'd love to have you as a contributor and would welcome a PR to support this 👍

**Comment by j005u** [comment] 2017-05-04 20:36
Sorry, I'm not familiar with Clojure at all.

http://stackoverflow.com/a/24561444

I believe that answer encapsulates pretty much everything you need to do in Java to get this to work smoothly, unless you're willing to specify trust stores per connection.

http://stackoverflow.com/a/21777005

And instead of loading from a .jks file you can just create it programatically from the .pem. Translating this to Clojure (same vm and libs, no?) will have to be an exercise for someone else.

Good luck.

**Comment by camsaul** [comment] 2017-05-04 23:18
Looks like Mongo has documentation for doing all these things at http://mongodb.github.io/mongo-java-driver/3.0/driver/reference/connecting/ssl/

**Comment by jsmestad** [comment] 2018-02-06 01:30
Would love to get a way to upload a self-signed cert in the UI :(

**Comment by madhums** [comment] 2018-05-15 20:29
Has anyone gotten this to work?

**Comment by phthano** [comment] 2018-05-24 02:12
This is a pain again for me. Please update metabase to be  more usable through the UI using self-signed certs.

**Comment by Kalli** [comment] 2018-08-08 17:43
I'm having some issues with a Compose hosted MongoDB as well. I've followed the instructions above, I believe that the trust store should have the certificate (following j005u recommendations from above and the ssl certificate that Compose provides). Is there a way to confirm that this is working? 

* Running Metabase 0.29.3 via Docker (kubernetes). 
* Using MongoDB 3.2.11

This is the error that I get when trying to add the Mongo db: 

```
com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=***, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}]
``` 

I'm seeing reports of similar errors in #6678  but the solutions mentioned there do not help. Any help appreciated, thanks!

**Comment by tjramage** [comment] 2018-11-12 21:44
@Kalli — I had the exact same issues as you with my Compose hosted MongoDB (3.6.8) setup. However, @BoLaMN's custom Docker image fixed everything for me, as outlined in #6678. Have you tried that?

**Comment by Kalli** [comment] 2018-11-19 19:39
Thanks for the info @tjramage, had not tried that image, I will investigate

**Comment by 0xicl33n** [comment] 2018-12-12 22:00
I am having a similar problem with my scalegrid cluster and self signed cert

    12-12 21:53:57 WARN driver.uri :: Unsupported option 'ssl_ca_certs' in the connection string 'mongodb://localhost/?readPreference=nearest&replicaSet=RS-spykedbShared-0&ssl=true&ssl_ca_certs=db.key'.

Except, i didnt put in `localhost`, i put in the actual hostname but metabase doesnt read that either?

I thought this would be fixed by https://github.com/metabase/metabase/issues/6678#issuecomment-445800318 because  [v0.31.2](https://github.com/metabase/metabase/releases/tag/v0.31.2) is supposed to fix this (it doesnt)

**Comment by Kalli** [comment] 2018-12-19 21:46
@tjramage apologies for the late reply, we ended up not needing to try it out, we were able to connect now that compose is using letsencrypt certs https://www.compose.com/articles/mongodb-and-lets-encrypt-certificates-noteworthy-at-compose/

**Comment by soerenmartius** [comment] 2019-04-05 08:11
did anyone find a workarround for `Unsupported option 'ssl_ca_certs' in the connection strin` yet?

**Comment by 0xicl33n** [comment] 2019-04-11 00:10
Is there really no fix to this?

**Comment by Gmulti** [comment] 2019-11-27 08:42
So no one has found a solution to connect with an SSL certificate?
I have the same problem with my instance at Scalegrid, we need to use an SSL certificate

**Comment by soerenmartius** [comment] 2019-11-27 09:17
@Gmulti this solution works. Please notice that we are working with AWS RDS. You are able to import any certificate though.

`
FROM metabase/metabase-head

ADD https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem \
 /usr/local/share/ca-certificates/rds-combined-ca-bundle.pem

RUN ${JAVA_HOME}/bin/keytool -importcert -v -trustcacerts \
    -alias metabase \
    -file "/usr/local/share/ca-certificates/rds-combined-ca-bundle.pem" \
    -keystore ${JAVA_HOME}/lib/security/cacerts \
    -storepass changeit -noprompt
`

**Comment by Gmulti** [comment] 2019-11-27 09:19
Your Metabase instance is on a docker, right?
I am currently deploying it with Heroku.

**Comment by soerenmartius** [comment] 2019-11-27 09:25
yeah, we are deploying a containerized version of metabase but the steps should be replicable for any kind of deployment. I haven't worked with Heroku since ages so I can't really tell. The RUN instruction mentioned in my previous post basically imports the certificate to Java's Keystore. Metabase will be aware of the certificate once it's imported to the underlying JVM.

**Comment by 0xicl33n** [comment] 2020-03-06 01:56
4 years later still no built in fix. feels bad

**Comment by flamber** [comment] 2020-03-10 11:57
:wave: Everyone, please make sure that you click the :+1: on the first post.
That's one of the indicators used for prioritizing issues.

**Closed** 2020-05-27 00:05 UTC
Labels: .Help Wanted, .Proposal, Database/Mongo

**Comment by esobolievv** [comment] 2020-06-12 13:23
Still have this issue while running on AWS Glue to connect to Mongo instance via https://mvnrepository.com/artifact/org.mongodb.spark/mongo-spark-connector_2.11/2.4.2 connector using Spark2.4.* + Glue1.0

**Comment by flamber** [comment] 2020-06-12 17:50
@esobolievv You will have to use the keytool and trustStore until 0.36.0, where it will be possible to input a custom certificate, like so:
![image](https://user-images.githubusercontent.com/1447303/84531524-0b94a280-ace5-11ea-8056-4a106a9ac22b.png)
