### ISSUE TITLE
Define Field Filter in Sql

### ISSUE THREAD

**Issue by m-lce** [metabase/metabase#12463] opened 2020-05-05 13:34 UTC
With Big Query nested fields and repeated fields are not well managed by Metabase interface.
I would like to use those fields in Field Filter and I think a quite easy way to manage this is to define the Field Filter not in the dropdown menu but programmaticaly in SQL. What I want is to bypass the WYSIWYG interface and have access to the way Metabase define the Field Filter in SQL.
This is quite a blocking feature for us to use more massively Metabase

Thanks

**Comment by flamber** [comment] 2020-05-05 13:54
Hi @m-lce 
It sounds like a duplicate of #3324, but without more details it's hard to know.

**Comment by m-lce** [comment] 2020-05-05 14:16
Yes as suggested in #3324 it would be great to do something like this in Big Query
``` sql 
select bla_bla
from `my_project.my_dataset.my_table`
where {{some_field:my_project.my_dataset.some_column.some_column_field}}
```

**Comment by flamber** [comment] 2020-05-05 14:32
Okay, then please upvote the other issue by clicking :+1: on the first post

**Closed by flamber** 2020-05-05 14:32 UTC
Labels: .Needs Triage, Type:New Feature
