### ISSUE TITLE
The Sample Dataset should have a default description

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2975] opened 2016-07-19 17:22 UTC
Now that we're including descriptions for databases in the new Data Reference, we should write a simple default description for the Sample Dataset.

Maybe:

> This sample dataset includes Orders, People, Products, and Reviews for an imaginary company. You can use it to try things like seeing orders over time by product category. You can remove this dataset from the Admin Panel.

**Comment by mbvictoria** [comment] 2019-06-19 19:52
Closing - basically a duplicate of #3131

**Closed by mbvictoria** 2019-06-19 19:52 UTC
Labels: UX
