### ISSUE TITLE
After upgrade to 0.30.2 counting/grouping/filtering by nested record crushed

### ISSUE THREAD

**Issue by katlesz** [metabase/metabase#8483] opened 2018-09-07 13:41 UTC
Hey there,

After upgrading  to 0.30.2 all questions that were using nested values in custom expression crushed. Mostly using for grouping, filtering. We were using those fields also for dashboard filters.

![image](https://user-images.githubusercontent.com/39829548/45222276-64374000-b2b4-11e8-90c2-a290d497b05e.png)

I am using:
- Browser: Chrome 68.1
- Operating system: OS 
- Batabases: BigQuery
- Metabase version: 0.30.2
- Metabase hosting environment: Google App Engine
- Metabase internal database: Google SQL

**Comment by jornh** [comment] 2018-09-07 14:46
I see you're using BigQuery. 

Is the problem specifically related to this BQ feature: https://cloud.google.com/bigquery/docs/legacy-nested-repeated

**Comment by salsakran** [comment] 2018-12-28 04:05
dupe of #8488

**Closed by salsakran** 2018-12-28 04:05 UTC
