### ISSUE TITLE
Is there any way to use microsoft azure SSO? 

### ISSUE THREAD

**Issue by alexberd** [metabase/metabase#14892] opened 2021-02-19 17:38 UTC
The only reference I found was the following but did not mention anything about Microsoft.
https://github.com/metabase/metabase/blob/master/docs/faq/setup/how-do-i-integrate-with-sso.md

**Comment by flamber** [comment] 2021-02-19 17:50
You can use SAML with Azure in the Enterprise Edition: https://www.metabase.com/docs/latest/enterprise-guide/authenticating-with-saml.html
Duplicate of #5915

**Closed by flamber** 2021-02-19 17:50 UTC
Labels: .Needs Triage, Type:Question
