### ISSUE TITLE
v0.43 Regression : Unusable on Firefox 101.0b5 (64-bit)

### ISSUE THREAD

**Issue by deepakinseattle** [metabase/metabase#22673] opened 2022-05-12 17:20 UTC
## Describe the bug

* Viewing a question results in a completely blank page [Screen recording](https://recordit.co/tJNJm1KyIK)
* Viewing a dashboard results in an infinite loop while attempting to load the page. [Screen recording](https://recordit.co/FPM46MdVHA)
* Adding a question to a dashboard doesn't add it to the dashboard [Screen recording](https://recordit.co/uoHNLmZqja)

## Logs

These are all browser console logs.

<details><summary>Adding a new question to a dashboard error</summary>
<p>

```
Error getting setting table.columns TypeError: Wf(...)[0].data is undefined
    getDefault Table.jsx:180
    vt settings.js:101
    bt settings.js:43
    v visualization.js:77
    value Visualization.jsx:150
    value Visualization.jsx:81
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    h ExplicitSize.jsx:125
    c Underscore
    t resize-observer.ts:15
    t resize-observer.ts:15
    t resize-observer.ts:13
    n raf-schd.esm.js:18
    r raf-schd.esm.js:16
settings.js:110:12
Error getting setting table._cell_background_getter TypeError: n is undefined
    getValue Table.jsx:227
    vt settings.js:87
    bt settings.js:43
    v visualization.js:77
    value Visualization.jsx:150
    value Visualization.jsx:81
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    h ExplicitSize.jsx:125
    c Underscore
    t resize-observer.ts:15
    t resize-observer.ts:15
    t resize-observer.ts:13
    n raf-schd.esm.js:18
    r raf-schd.esm.js:16
settings.js:110:12
ReferenceError: Notification is not defined
    O9 DashboardApp.jsx:126
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    Redux 2
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    v query_time.js:610
    a query_time.js:610
    promise callback*v query_time.js:610
    a query_time.js:610
    g query_time.js:610
    g query_time.js:610
    n Redux
    y store.js:23
    dispatch Redux
    e actions.js:262
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    q Toggle.tsx:41
    a Toggle.tsx:41
    promise callback*q Toggle.tsx:41
    a Toggle.tsx:41
    M Toggle.tsx:41
    M Toggle.tsx:41
    Ue actions.js:238
    y store.js:23
    T Redux
    j DashboardSidebars.jsx:74
    onClick BaseSelectListItem.jsx:38
    React 12
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
react-dom.production.min.js:209:194
Warning: can't clean query without metadata!
```

</p></details>

<details><summary>Viewing dashboard error</summary>
<p>

```
ReferenceError: Notification is not defined
    O9 DashboardApp.jsx:126
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    Vi React
react-dom.production.min.js:209:194
    React 5
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    Redux 2
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    v query_time.js:610
    a query_time.js:610
    (Async: promise callback)
    v query_time.js:610
    a query_time.js:610
    g query_time.js:610
    g query_time.js:610
    n Redux
    y store.js:23
    dispatch Redux
    i actions.js:470
    Ye actions.js:468
    t Redux
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    v query_time.js:610
    a query_time.js:610
    g query_time.js:610
    g query_time.js:610
    n Redux
    y store.js:23
    T Redux
    value Dashboard.jsx:133
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    Redux 2
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    v query_time.js:610
    a query_time.js:610
    (Async: promise callback)
    v query_time.js:610
    a query_time.js:610
    g query_time.js:610
    g query_time.js:610
    n Redux
    y store.js:23
    T Redux
    e Dashboard.jsx:161
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    z7 stickyParameters.js:55
    a Dashboard.jsx:144
    k7 Dashboard.jsx:144
    i Dashboard.jsx:144
    value Dashboard.jsx:144
    value Dashboard.jsx:115
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
Warning: can't clean query without metadata! StructuredQuery.ts:340:14
Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 3
    value ExplicitSize.jsx:47
    h ExplicitSize.jsx:121
    Underscore 6
    t resize-observer.ts:15
    t resize-observer.ts:15
    t resize-observer.ts:13
    n raf-schd.esm.js:18
    r raf-schd.esm.js:16
react-dom.production.min.js:50:150
DEPRECATED: metabase/redux/metadata addParamValues metadata.js:19:38
DEPRECATED: metabase/redux/metadata addFields metadata.js:19:38
Error getting setting map.latitude_column TypeError: t is undefined
    getDefault Map.jsx:210
    vt settings.js:101
    vt settings.js:70
    bt settings.js:43
    v visualization.js:77
    value Visualization.jsx:150
    value Visualization.jsx:81
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    h ExplicitSize.jsx:125
    c Underscore
    setTimeout handler*value ExplicitSize.jsx:59
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    Redux 2
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    v query_time.js:610
    a query_time.js:610
    promise callback*v query_time.js:610
    a query_time.js:610
    g query_time.js:610
    g query_time.js:610
    n Redux
    y store.js:23
    T Redux
    e Dashboard.jsx:161
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    z7 stickyParameters.js:55
    a Dashboard.jsx:144
    k7 Dashboard.jsx:144
    i Dashboard.jsx:144
    value Dashboard.jsx:144
    value Dashboard.jsx:115
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
settings.js:110:12
Error getting setting map.longitude_column TypeError: t is undefined
    getDefault Map.jsx:217
    vt settings.js:101
    vt settings.js:70
    bt settings.js:43
    v visualization.js:77
    value Visualization.jsx:150
    value Visualization.jsx:81
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    h ExplicitSize.jsx:125
    c Underscore
    setTimeout handler*value ExplicitSize.jsx:59
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    Redux 2
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    v query_time.js:610
    a query_time.js:610
    promise callback*v query_time.js:610
    a query_time.js:610
    g query_time.js:610
    g query_time.js:610
    n Redux
    y store.js:23
    T Redux
    e Dashboard.jsx:161
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    z7 stickyParameters.js:55
    a Dashboard.jsx:144
    k7 Dashboard.jsx:144
    i Dashboard.jsx:144
    value Dashboard.jsx:144
    value Dashboard.jsx:115
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
settings.js:110:12
Error getting setting map.metric_column TypeError: t is undefined
    getDefault utils.js:43
    vt settings.js:101
    vt settings.js:70
    bt settings.js:43
    v visualization.js:77
    value Visualization.jsx:150
    value Visualization.jsx:81
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    h ExplicitSize.jsx:125
    c Underscore
    setTimeout handler*value ExplicitSize.jsx:59
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    Redux 2
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    v query_time.js:610
    a query_time.js:610
    promise callback*v query_time.js:610
    a query_time.js:610
    g query_time.js:610
    g query_time.js:610
    n Redux
    y store.js:23
    T Redux
    e Dashboard.jsx:161
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    z7 stickyParameters.js:55
    a Dashboard.jsx:144
    k7 Dashboard.jsx:144
    i Dashboard.jsx:144
    value Dashboard.jsx:144
    value Dashboard.jsx:115
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
settings.js:110:12
Error getting setting map.pin_type TypeError: n is undefined
    getDefault Map.jsx:196
    vt settings.js:101
    bt settings.js:43
    v visualization.js:77
    value Visualization.jsx:150
    value Visualization.jsx:81
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    h ExplicitSize.jsx:125
    c Underscore
    setTimeout handler*value ExplicitSize.jsx:59
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    Redux 2
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    v query_time.js:610
    a query_time.js:610
    promise callback*v query_time.js:610
    a query_time.js:610
    g query_time.js:610
    g query_time.js:610
    n Redux
    y store.js:23
    T Redux
    e Dashboard.jsx:161
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    z7 stickyParameters.js:55
    a Dashboard.jsx:144
    k7 Dashboard.jsx:144
    i Dashboard.jsx:144
    value Dashboard.jsx:144
    value Dashboard.jsx:115
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
settings.js:110:12
Error getting setting map.region TypeError: r is undefined
    getDefault Map.jsx:233
    vt settings.js:101
    bt settings.js:43
    v visualization.js:77
    value Visualization.jsx:150
    value Visualization.jsx:81
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    h ExplicitSize.jsx:125
    c Underscore
    setTimeout handler*value ExplicitSize.jsx:59
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    Redux 2
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    v query_time.js:610
    a query_time.js:610
    promise callback*v query_time.js:610
    a query_time.js:610
    g query_time.js:610
    g query_time.js:610
    n Redux
    y store.js:23
    T Redux
    e Dashboard.jsx:161
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    z7 stickyParameters.js:55
    a Dashboard.jsx:144
    k7 Dashboard.jsx:144
    i Dashboard.jsx:144
    value Dashboard.jsx:144
    value Dashboard.jsx:115
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
settings.js:110:12
Error getting setting scalar.field TypeError: Ga(...)[0].data is undefined
    getDefault Scalar.jsx:100
    vt settings.js:101
    bt settings.js:43
    v visualization.js:77
    value Visualization.jsx:150
    value Visualization.jsx:81
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    h ExplicitSize.jsx:125
    c Underscore
    setTimeout handler*value ExplicitSize.jsx:59
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    Redux 2
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    v query_time.js:610
    a query_time.js:610
    promise callback*v query_time.js:610
    a query_time.js:610
    g query_time.js:610
    g query_time.js:610
    n Redux
    y store.js:23
    T Redux
    e Dashboard.jsx:161
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    z7 stickyParameters.js:55
    a Dashboard.jsx:144
    k7 Dashboard.jsx:144
    i Dashboard.jsx:144
    value Dashboard.jsx:144
    value Dashboard.jsx:115
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
settings.js:110:12
Error getting setting scalar.field TypeError: Ga(...)[0].data is undefined
    getDefault Scalar.jsx:100
    vt settings.js:101
    bt settings.js:43
    v visualization.js:77
    value Visualization.jsx:150
    value Visualization.jsx:81
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    h ExplicitSize.jsx:125
    c Underscore
    setTimeout handler*value ExplicitSize.jsx:59
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    Redux 2
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    v query_time.js:610
    a query_time.js:610
    promise callback*v query_time.js:610
    a query_time.js:610
    g query_time.js:610
    g query_time.js:610
    n Redux
    y store.js:23
    T Redux
    e Dashboard.jsx:161
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    z7 stickyParameters.js:55
    a Dashboard.jsx:144
    k7 Dashboard.jsx:144
    i Dashboard.jsx:144
    value Dashboard.jsx:144
    value Dashboard.jsx:115
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
settings.js:110:12
Error getting setting graph.x_axis._is_timeseries TypeError: n is undefined
    getDefault graph.js:379
    vt settings.js:101
    bt settings.js:43
    v visualization.js:77
    value Visualization.jsx:150
    value Visualization.jsx:81
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    h ExplicitSize.jsx:125
    c Underscore
    setTimeout handler*value ExplicitSize.jsx:59
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    Redux 2
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    v query_time.js:610
    a query_time.js:610
    promise callback*v query_time.js:610
    a query_time.js:610
    g query_time.js:610
    g query_time.js:610
    n Redux
    y store.js:23
    T Redux
    e Dashboard.jsx:161
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    z7 stickyParameters.js:55
    a Dashboard.jsx:144
    k7 Dashboard.jsx:144
    i Dashboard.jsx:144
    value Dashboard.jsx:144
    value Dashboard.jsx:115
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
settings.js:110:12
Error getting setting graph.x_axis._is_numeric TypeError: n is undefined
    getDefault graph.js:390
    vt settings.js:101
    bt settings.js:43
    v visualization.js:77
    value Visualization.jsx:150
    value Visualization.jsx:81
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    h ExplicitSize.jsx:125
    c Underscore
    setTimeout handler*value ExplicitSize.jsx:59
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    Redux 2
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    v query_time.js:610
    a query_time.js:610
    promise callback*v query_time.js:610
    a query_time.js:610
    g query_time.js:610
    g query_time.js:610
    n Redux
    y store.js:23
    T Redux
    e Dashboard.jsx:161
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    z7 stickyParameters.js:55
    a Dashboard.jsx:144
    k7 Dashboard.jsx:144
    i Dashboard.jsx:144
    value Dashboard.jsx:144
    value Dashboard.jsx:115
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
settings.js:110:12
Error getting setting graph.x_axis._is_histogram TypeError: Qv(...)[0].data is undefined
    getDefault graph.js:399
    vt settings.js:101
    bt settings.js:43
    v visualization.js:77
    value Visualization.jsx:150
    value Visualization.jsx:81
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    h ExplicitSize.jsx:125
    c Underscore
    setTimeout handler*value ExplicitSize.jsx:59
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    Redux 2
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    v query_time.js:610
    a query_time.js:610
    promise callback*v query_time.js:610
    a query_time.js:610
    g query_time.js:610
    g query_time.js:610
    n Redux
    y store.js:23
    T Redux
    e Dashboard.jsx:161
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    z7 stickyParameters.js:55
    a Dashboard.jsx:144
    k7 Dashboard.jsx:144
    i Dashboard.jsx:144
    value Dashboard.jsx:144
    value Dashboard.jsx:115
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
settings.js:110:12
Error getting setting graph.x_axis.title_text TypeError: e[0].data is undefined
    getDefault graph.js:551
    vt settings.js:101
    bt settings.js:43
    v visualization.js:77
    value Visualization.jsx:150
    value Visualization.jsx:81
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    h ExplicitSize.jsx:125
    c Underscore
    setTimeout handler*value ExplicitSize.jsx:59
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    Redux 2
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    v query_time.js:610
    a query_time.js:610
    promise callback*v query_time.js:610
    a query_time.js:610
    g query_time.js:610
    g query_time.js:610
    n Redux
    y store.js:23
    T Redux
    e Dashboard.jsx:161
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    z7 stickyParameters.js:55
    a Dashboard.jsx:144
    k7 Dashboard.jsx:144
    i Dashboard.jsx:144
    value Dashboard.jsx:144
    value Dashboard.jsx:115
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
settings.js:110:12
Error getting setting graph.y_axis.title_text TypeError: e.data is undefined
    r graph.js:571
    getDefault graph.js:571
    vt settings.js:101
    bt settings.js:43
    v visualization.js:77
    value Visualization.jsx:150
    value Visualization.jsx:81
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    h ExplicitSize.jsx:125
    c Underscore
    setTimeout handler*value ExplicitSize.jsx:59
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    Redux 2
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    v query_time.js:610
    a query_time.js:610
    promise callback*v query_time.js:610
    a query_time.js:610
    g query_time.js:610
    g query_time.js:610
    n Redux
    y store.js:23
    T Redux
    e Dashboard.jsx:161
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    z7 stickyParameters.js:55
    a Dashboard.jsx:144
    k7 Dashboard.jsx:144
    i Dashboard.jsx:144
    value Dashboard.jsx:144
    value Dashboard.jsx:115
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
settings.js:110:12
Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 3
    value ExplicitSize.jsx:47
    h ExplicitSize.jsx:121
    Underscore 2
    t resize-observer.ts:15
    t resize-observer.ts:15
    t resize-observer.ts:13
    n raf-schd.esm.js:18
    r raf-schd.esm.js:16
react-dom.production.min.js:50:150
Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 3
    value ExplicitSize.jsx:47
    h ExplicitSize.jsx:121
    Underscore 6
    t resize-observer.ts:15
    t resize-observer.ts:15
    t resize-observer.ts:13
    n raf-schd.esm.js:18
    r raf-schd.esm.js:16
2 react-dom.production.min.js:50:150
ReferenceError: Notification is not defined
    O9 DashboardApp.jsx:126
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    Vi React
```

</p></details>

<details><summary>Viewing a question error</summary>
<p>

```
Request to access cookie or storage on “<URL>” was blocked because it came from a tracker and content blocking is enabled. 2
Request to access cookie or storage on “https://apis.google.com/js/api:client.js” was blocked because it came from a tracker and content blocking is enabled.

Request to access cookie or storage on “https://apis.google.com/_/scs/abc-static/_/js/k=gapi.lb.en.iTmf4rxOyWc.O/m=client/rt=j/sv=1/d=1/ed=1/rs=AHpOoo-LTnDn-AS2QlMWYZdnaV1OuFR7Iw/cb=gapi.loaded_0?le=scs” was blocked because it came from a tracker and content blocking is enabled.

Setting moment.js start of week for Locale en to sunday i18n.js:49:10
Warning: can't clean query without metadata! StructuredQuery.ts:340:14
ReferenceError: Notification is not defined
    QBe QueryBuilder.jsx:392
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    dispatch Redux
    action store.js:20
    n actions.js:1428
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    de utils.js:98
    a utils.js:98
    pe utils.js:98
    pe utils.js:98
    sn actions.js:1394
    y store.js:23
    dispatch Redux
    e actions.js:1364
    promise callback*35123/on/e/< actions.js:1354
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    de utils.js:98
    a utils.js:98
    pe utils.js:98
    pe utils.js:98
    on actions.js:1308
    y store.js:23
    dispatch Redux
    n actions.js:699
    setTimeout handler*35123/st/n/< actions.js:696
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    de utils.js:98
    a utils.js:98
    promise callback*de utils.js:98
    a utils.js:98
    promise callback*de utils.js:98
    a utils.js:98
    pe utils.js:98
    pe utils.js:98
    st actions.js:419
    y store.js:23
    T Redux
    QBe QueryBuilder.jsx:307
    o use-on-mount.ts:5
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 4
react-dom.production.min.js:209:194
Warning: can't clean query without metadata! StructuredQuery.ts:340:14
ReferenceError: Notification is not defined
    QBe QueryBuilder.jsx:392
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    dispatch Redux
    action store.js:20
    n actions.js:1428
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    de utils.js:98
    a utils.js:98
    pe utils.js:98
    pe utils.js:98
    sn actions.js:1394
    y store.js:23
    dispatch Redux
    e actions.js:1364
    promise callback*35123/on/e/< actions.js:1354
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    de utils.js:98
    a utils.js:98
    pe utils.js:98
    pe utils.js:98
    on actions.js:1308
    y store.js:23
    dispatch Redux
    n actions.js:699
    setTimeout handler*35123/st/n/< actions.js:696
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    de utils.js:98
    a utils.js:98
    promise callback*de utils.js:98
    a utils.js:98
    promise callback*de utils.js:98
    a utils.js:98
    pe utils.js:98
    pe utils.js:98
    st actions.js:419
    y store.js:23
    T Redux
    QBe QueryBuilder.jsx:307
    o use-on-mount.ts:5
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 4
react-dom.production.min.js:209:194
Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 3
    value ExplicitSize.jsx:47
    h ExplicitSize.jsx:121
    c Underscore
    setTimeout handler*value ExplicitSize.jsx:59
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    dispatch Redux
    action store.js:20
    n actions.js:1428
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    de utils.js:98
    a utils.js:98
    pe utils.js:98
    pe utils.js:98
    sn actions.js:1394
    y store.js:23
    dispatch Redux
    e actions.js:1364
    promise callback*35123/on/e/< actions.js:1354
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    de utils.js:98
    a utils.js:98
    pe utils.js:98
    pe utils.js:98
    on actions.js:1308
    y store.js:23
    dispatch Redux
    n actions.js:699
    setTimeout handler*35123/st/n/< actions.js:696
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    de utils.js:98
    a utils.js:98
    promise callback*de utils.js:98
    a utils.js:98
    promise callback*de utils.js:98
    a utils.js:98
    pe utils.js:98
    pe utils.js:98
    st actions.js:419
    y store.js:23
    T Redux
    QBe QueryBuilder.jsx:307
    o use-on-mount.ts:5
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 4
3 react-dom.production.min.js:49:66
Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 3
    value ExplicitSize.jsx:47
    h ExplicitSize.jsx:121
    Underscore 2
    setTimeout handler*value ExplicitSize.jsx:59
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 7
    y store.js:25
    dispatch Redux
    action store.js:20
    n actions.js:1428
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    de utils.js:98
    a utils.js:98
    pe utils.js:98
    pe utils.js:98
    sn actions.js:1394
    y store.js:23
    dispatch Redux
    e actions.js:1364
    promise callback*35123/on/e/< actions.js:1354
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    de utils.js:98
    a utils.js:98
    pe utils.js:98
    pe utils.js:98
    on actions.js:1308
    y store.js:23
    dispatch Redux
    n actions.js:699
    setTimeout handler*35123/st/n/< actions.js:696
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    de utils.js:98
    a utils.js:98
    promise callback*de utils.js:98
    a utils.js:98
    promise callback*de utils.js:98
    a utils.js:98
    pe utils.js:98
    pe utils.js:98
    st actions.js:419
    y store.js:23
    T Redux
    QBe QueryBuilder.jsx:307
    o use-on-mount.ts:5
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    Redux 4
react-dom.production.min.js:49:66
Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 3
    value ExplicitSize.jsx:47
    h ExplicitSize.jsx:121
    Underscore 2
    t resize-observer.ts:15
    t resize-observer.ts:15
    t resize-observer.ts:13
    n raf-schd.esm.js:18
    r raf-schd.esm.js:16
    Z resize-observer.ts:19
    80932 resize-observer.ts:47
    Webpack 51
react-dom.production.min.js:50:150
```

</p></details>

## To Reproduce

1. Go to the home page
2. Click on either a saved question or a dashboard to view it.
3. Observe behavior shown in the screen recordings above
4. See error in the browser console.

## Expected behavior

* I can view questions
* I can view dashboards
* I can add quesitons to dashboards

## Screenshots

Screen recordings included in description at the top.

## Information about your Metabase Installation:

<details><summary>Results of Admin > Troubleshooting</summary>
<p>

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.4.181-99.354.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.8"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-02",
      "tag": "v0.43.0",
      "branch": "release-x.43.x",
      "hash": "ee686fc"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

</p></details>

- Your browser and the version: Firefox 101.0b5 (64-bit) *all extensions disabled*
- Your operating system: macOS 12.3.1 (21E258)
- Your databases: Postgres
- Metabase version: 0.43
- Metabase hosting environment: Docker/Kubernetes
- Metabase internal database: Postgres

## Severity

It is severe to me, because I use Firefox, but given its market share I suspect it's not highly severe to folks that don't use Firefox. This works fine on Google Chrome.

**Comment by flamber** [comment] 2022-05-12 17:24
Duplicate of #22172 - make sure that you enable Web Notifications API - you don't need to do allow the notifications.
Go to `about:config` - find `dom.webnotifications.enabled` and set it to `true`

**Closed by flamber** 2022-05-12 17:24 UTC
Labels: Type:Bug, .Needs Triage
