### ISSUE TITLE
"Every field is hidden right now" - Visualisation error at the editor stage

### ISSUE THREAD

**Issue by ZohaSpark** [metabase/metabase#17057] opened 2021-07-15 07:58 UTC
**Describe the bug**

When working on a question, it randomly bugs after making changes and running it several times. Once this message appears, it never disappears even if we go back to a code version where it previously worked. Even if saved and used on a dashboard, the visualisation will not be displayed.

I was also able to see that it is not linked to the code itself, as a copy & paste of the code onto a new question gives normal results.

**The visualisation tool is broken and this error message appears: "Every field is hidden right now"**

**To Reproduce**
1. Go to any question - the heavier the queries the better, it seems to happen more easily.
2. Click on the editor
3. Make some changes (I change the ASC or DESC in the ORDER BY) and run your code again. Repeat until the bug appears.

**Expected behavior**
A normal visualisation of my rows or of the visualisation of my choice (if there is no error in my code)

**Screenshots**
![image](https://user-images.githubusercontent.com/87467508/125748728-bd16ddbd-3a52-420a-bf48-820fc0db4968.png)

![image](https://user-images.githubusercontent.com/87467508/125750941-5d918945-3b51-4de9-addd-e4ce47fac67a.png)

**Information about your Metabase Installation:**

> {
  "browser-info": {
    "language": "fr-FR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.14.232-177.418.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.9"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-07-08",
      "tag": "v0.40.0",
      "branch": "master",
      "hash": "961caed"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}

**Severity**
It is quite annoying and time-consuming. We need to copy & paste it onto a new question and set again our filters and their specifications. It is also a frequent issue, making it worse for us. On the other hand, for now it is not destroying our abilities to work with Metabase.

**Comment by flamber** [comment] 2021-07-15 10:07
Hi @ZohaSpark 
Upgrade to 0.40.1 - duplicate of #16914.

**Closed by flamber** 2021-07-15 10:07 UTC
Labels: .Needs Triage, Type:Bug
