### ISSUE TITLE
App crashes when editing custom expression referencing metric when dependent metadata is not loaded

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#47058] opened 2024-08-21 10:06 UTC
### Describe the bug

Original report: https://metaboat.slack.com/archives/C5XHN8GLW/p1724161690436689
Got a failure in CI: https://github.com/metabase/metabase/actions/runs/10471883147/job/29000500799?pr=47009
The failure is "correct", test is not flaky.

![image](https://github.com/user-attachments/assets/0be412fd-bebf-4c48-858e-f662150ec5bf)

```
app-main.hot.bundle.js:714521 Error: metric with ID: 5 does not exist
    at formatMetric (app-main.hot.bundle.js:235066:15)
    at format (app-main.hot.bundle.js:235019:16)
    at transformPropsToState (app-main.hot.bundle.js:533945:95)
    at new ExpressionEditorTextfield (app-main.hot.bundle.js:534216:22)
    at constructClassInstance (vendor.hot.bundle.js:267178:18)
    at updateClassComponent (vendor.hot.bundle.js:272538:5)
    at beginWork (vendor.hot.bundle.js:274461:16)
    at beginWork$1 (vendor.hot.bundle.js:280276:14)
    at performUnitOfWork (vendor.hot.bundle.js:279407:12)
    at workLoopSync (vendor.hot.bundle.js:279316:5)
```

### To Reproduce

1. New > Metric > Orders > Count > Save
2. New > Question > Orders > Summarize by metric created in previous step > Save > Stay in notebook editor
3. Throttle your network or block `/api/card/:id/query_metadata` URL in network tab in developer tools
4. Refresh the page
5. Before GET `/api/card/:id/query_metadata` request completes, try to edit the aggregation's custom expression

App crashes

### Information about your Metabase installation

master, 63c074d2a226c459141be5ed548ee464a5267806

### Severity

P2

**Comment by romeovs** [comment] 2024-10-10 08:45
AFAICT I can no longer reproduce this issue. When I throttle the `/api/card/:id/query_metadata` query and refresh, the Notebook editor just stays in the loading state until the request to that URL resolves.

There is no intermediate state where I could edit the custom expression and cause a crash.

Completely blocking the call to `/api/card/:id/query_metadata` _does_ crash the editor but I think that is acceptable.

I can't see the failed test runs so I don't have full context, so @kamilmielnik can you confirm this can be closed if what I said above is true?

**Comment by kamilmielnik** [comment] 2024-10-10 09:07
> AFAICT I can no longer reproduce this issue. When I throttle the /api/card/:id/query_metadata query and refresh, the Notebook editor just stays in the loading state until the request to that URL resolves.

Looks fixed 👍 

> Completely blocking the call to `/api/card/:id/query_metadata` _does_ crash the editor but I think that is acceptable.

I'm not sure if this is acceptable.
The entire page crashes but I'm pretty sure we could still show the visualization and the [header](https://github.com/user-attachments/assets/8ede6c1f-1b89-47db-b4cf-d2082f7a2b42) to let users inspect question history, edit sharing, move it to trash, etc.

Notebook editor itself is the only thing that would be allowed to crash here.

Try this patch to see for yourself:
```patch
diff --git a/frontend/src/metabase/api/card.ts b/frontend/src/metabase/api/card.ts
index f0f6d3bf64..4db387509b 100644
--- a/frontend/src/metabase/api/card.ts
+++ b/frontend/src/metabase/api/card.ts
@@ -48,6 +48,13 @@ export const cardApi = Api.injectEndpoints({
         method: "GET",
         url: `/api/card/${id}/query_metadata`,
       }),
+      transformResponse: () => {
+        return {
+          databases: [],
+          tables: [],
+          fields: [],
+        };
+      },
       providesTags: (metadata, error, id) =>
         metadata ? provideCardQueryMetadataTags(id, metadata) : [],
     }),
```



> can you confirm this can be closed if what I said above is true?

It can be closed when we have a repro for it 🙏

**Comment by romeovs** [comment] 2024-10-10 10:59
> @kamilmielnik 
> The entire page crashes but I'm pretty sure we could still show the visualization and the header

Applying that patch works to show the query editor, but interacting with the custom expression makes it crash either way.

We don't but guardrails around other pages/components like this (eg. the `/question/:id` page also completely crashes when `/api/card/:id/query_metadata` is blocked), and doing so would be quite the undertaking, since the fetching of this data is built deeply into redux AFAICT and handling exceptions there is not that straightforward.

We could start adding:
```tsx
transformErrorResponse() {
  return { databases: [] }, // or whatever "empty" state
}
```
to all the api requests but I don't think that would make things more stable or predictable, but just shifts the issue to the users of the data.

Maybe we just need to add an `ErrorBoundary` around the notebook editor itself?

> @kamilmielnik 
> It can be closed when we have a repro for it 🙏

Is the fact that the flake is fixed not enough in this case?

The way the page currently works, the bug no longer exists because it shows the loading state before the metadata resolves. I can add a test for that but it will be trivial.

**Comment by kamilmielnik** [comment] 2024-10-10 11:18
> Applying that patch works to show the query editor, but interacting with the custom expression makes it crash either way.

> We don't but guardrails around other pages/components like this (eg. the /question/:id page also completely crashes when /api/card/:id/query_metadata is blocked), 

With this patch you can navigate to `/question/:id` and see the visualization.
Without it - page crashes.


> We could start adding: (...) to all the api requests but I don't think that would make things more stable or predictable, but just shifts the issue to the users of the data.

If we were to use the Null Object Pattern to address this, `transformErrorResponse` would not be the right place for it. We should do it "higher" up the stack.

> Maybe we just need to add an ErrorBoundary around the notebook editor itself?

That's one way out. I'm not sure if it will be enough though.

> Is the fact that the flake is fixed not enough in this case?

That was not a flake, see 3rd sentence in original issue report.

> I can add a test for that but it [will be trivial](https://github.com/metabase/metabase/commit/4471b5562080ea4f6815d21fdb3cc02425ceb5ee).

This test is incorrect, we need to simulate the race condition, e.g. like this: https://github.com/metabase/metabase/blob/205f2239bd3286a9a5a0c29ffafa68d7bbeb3169/e2e/test/scenarios/dashboard/dashboard-reproductions.cy.spec.js#L1580

**Comment by romeovs** [comment] 2024-10-10 12:38
I've updated the test to test the actual race condition (or the sidestepping of it really): https://github.com/metabase/metabase/pull/48560.

I think we can make the page load better when certain requests fail but that is out of scope for this issue IMHO, so I've set up an issue to track it: https://github.com/metabase/metabase/issues/48562.

**Closed** 2024-10-11 10:22 UTC
Labels: Type:Bug, Priority:P2, .Frontend, Querying/Notebook, .Team/Querying, Querying/Metrics, Frequency:Rare
