### ISSUE TITLE
New Feature: Scatter Plots

### ISSUE THREAD

**Issue by AlgyTaylor** [metabase/metabase#1400] opened 2015-10-29 13:40 UTC
Would it be possible to include scatter plots:

https://en.wikipedia.org/wiki/Scatter_plot

It would be immensely useful for analysing genetic data here, to try to show whether there is a correlation between different attributes.

**Comment by tlrobinson** [comment] 2015-10-29 16:40
Duplicate of #645

**Closed by tlrobinson** 2015-10-29 16:40 UTC
