### ISSUE TITLE
Saving changes in Permissions matrix doesn't work 

### ISSUE THREAD

**Issue by vsusnova** [metabase/metabase#8343] opened 2018-08-16 14:57 UTC
Hi, 
when I start editing permissions then two buttons appear in the top right corner: cancel and save changes. I set up permissions and hit the "save changes", a banner opens with changes summary, asking whether I am sure I want to do that, I hit "yes" button but nothing happens = two buttons (cancel, save changes) in the top right corner are still there. When I try to leave the page I got a notification that there are unsaved changes. 

Cancel button works fine, though. 

- Your browser and the version: Chrome Version 68.0.3440.106
- Your operating system: macOS Sierra 10.12.6
- Your databases: Postgres
- Metabase version: v0.28.0
- Metabase hosting environment: Linux/ubuntu
- Metabase internal database: Postgres

**Comment by jornh** [comment] 2018-08-16 15:28
Hard to say - because I don't on what particular permissions you are experiencing this ... BUT ... this could maybe perhaps be a duplicate of e.g. https://github.com/metabase/metabase/issues/6739. You can check that that description + it's error log to see if yours is the same issue or not.

Anyway, the above probably won't help you a lot, with your current version v0.28.0 (from February). Since then a lot of stuff has already happened, including *a lot of changes, to the permissions in particular in v0.30.0* so your best option is probably to take that for a test spin.

Start by reading up on this though (to not be taken too much by surprise. Some others found that their 🧀 got moved - particularly regarding collections, UI changes and permissions ;):
* https://metabase.com/blog/before-upgrading-to-0.30/index.html#before-you-upgrade
* https://metabase.com/blog/0.30/index.html

Happy to continue on here if v0.30.0 doesn't fix it for you.

**Comment by salsakran** [comment] 2018-08-16 19:05
hello @vsusnova - 
We've changed a lot of the permissions code, as well as fixed many bugs since 0.28. We don't take bug reports on old versions unless they are also present in the most recent version.

If you are still seeing this in 0.30, please chime in and I'll re-open this.

**Closed by salsakran** 2018-08-16 19:05 UTC
Labels: Permissions
