### ISSUE TITLE
How to set dynamic goal in progress bar via query

### ISSUE THREAD

**Issue by yee-mon** [metabase/metabase#14077] opened 2020-12-15 04:06 UTC
I used mongodb database  with metabase. My intention is to set goal and actual count in progress bar via native query by using mongo aggregation pipeline. But I can just set only actual count via query .How can I do to set dynamic goal via query.Does metabase support for dynamic goal via native query in progress bar? I'm stuck in this issue. If anyone know this, please help me. Thank in advance

**Comment by flamber** [comment] 2020-12-15 10:01
Duplicate of #6514

**Closed by flamber** 2020-12-15 10:01 UTC
