### ISSUE TITLE
`report_card.result_metadata` on MySQL limited to 64KB (uses `TEXT` instead of `LONGTEXT`)

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11977] opened 2020-02-25 12:59 UTC
**Describe the bug**
When using MySQL/MariaDB for application database and having large query results, will give problems because MySQL's `TEXT` column type is only 64KB, whereas `LONGTEXT` is 4GB, which is closer to Postgres/H2's 1GB on `TEXT`. (MySQL `MEDIUMTEXT` is "only" 16MB)
It also blocks migrate from H2 to MySQL - stopping with `java.sql.SQLException: Data too long for column 'result_metadata'`

**Workaround**
Change the affected column in the application database from `TEXT` to `LONGTEXT` - might have to do it during migration several times, see forum post.

**Proposed fix**
Similar to changeset 97, but I'm not sure if this should only be done on `report_card.result_metadata` or perhaps include several/all other `TEXT` columns too? Could visualization settings or queries potentially exceed 64KB?
https://github.com/metabase/metabase/blob/aced697af9c7bc71d95427a7a995fd6655bc8ea0/resources/migrations/000_migrations.yaml#L5144-L5158

**Additional context**
(filing as bug instead of feature, since it makes migration difficult)
I've encountered this on a few setups and it's been reported a couple of times in the forum:
https://discourse.metabase.com/t/metabase-h2-fails-to-load-migration-to-mysql-fails/9126
Probably worth fixing this together with #7006 (re-opened issue) and #9624 and #13088

**Comment by camsaul** [comment] 2021-02-18 02:18
Same underlying issue as #7006. Closing as duplicate of #7006

**Closed by camsaul** 2021-02-18 02:18 UTC
Labels: Database/MySQL, Operation/Database Migrations, Priority:P2, Querying/, Type:Bug
