### ISSUE TITLE
Got a really weird error displayed to me

### ISSUE THREAD

**Issue by infomofo** [metabase/metabase#2165] opened 2016-03-16 18:18 UTC
If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is Mac OSX.
*  I'm running Metabase 0.15. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is psql.
*  My Metabase version is 0.15.

I'm in the admin panel

I clicked a table name, and then I tried to see the "Hidden" visibility fields and i saw this crazy xml error.

![image](https://cloud.githubusercontent.com/assets/539599/13823866/df977f96-eb81-11e5-93d8-85bfb387123b.png)

**Comment by camsaul** [comment] 2016-03-16 18:27
Hi @infomofo, this bug was fixed in Metabase 0.15.1. 

Closing as duplicate of #2084.

**Closed by camsaul** 2016-03-16 18:27 UTC
