### ISSUE TITLE
sync database schema but table column isn't in the order of the original table

### ISSUE THREAD

**Issue by xqwbx163** [metabase/metabase#10312] opened 2019-07-09 08:18 UTC
Os  :centos 7.2
metabase : 0.32.8

sync database schema but table column isn't in the order of the original table,
This is too inconvenient，i see the metabase source table :(metabase_field) 
![image](https://user-images.githubusercontent.com/20455410/60870887-420ba700-a264-11e9-85b6-1cd7222600c7.png)

the column position value is zero, so i must modify the value on source table every time. 

When actually sync the table schema, the order of columns can get, why not written to the source metabase_field?
![image](https://user-images.githubusercontent.com/20455410/60871063-9c0c6c80-a264-11e9-8ba5-1a3678a4e9bf.png)

**Comment by flamber** [comment] 2019-07-09 15:39
Related to #3720. Seems like `position` is a legacy feature according to https://github.com/metabase/metabase/issues/4329#issuecomment-282357216

**Comment by xqwbx163** [comment] 2019-07-10 03:35
i found that this issue has been appeared long time ago, why not solve the issue?

**Comment by flamber** [comment] 2019-07-10 05:15
@xqwbx163 I don't understand your question. Like the comment states, it seems like the functionality of `position` is a legacy feature, which hasn't been removed completely. This is an open source project, so you're more than welcome to dig into the code and create a pull request.

**Comment by RMMSecurity** [comment] 2019-07-10 21:11
It sounds like from both issues that no one remembers exactly when it was removed which to me seems like less of an intentional decision to remove it than something possibly overlooked in a UI overhaul. 

I frequently ran into this issue on my end which lead me to creating nested questions for our users to build off of... until drilldowns/agg was broken. The vendor has 40+ columns on so hundreds of tables it's actually painful to go through them all more than once. 

I envision the sort being something you can change under the Data Model where you could drag and drop or possibly a vertical ellipsis to drag and drop into the right order and this on the side to send to top/bottom.

![image](https://user-images.githubusercontent.com/802527/61005189-bd895900-a335-11e9-98dd-fa7886ef3c70.png)

**Comment by RMMSecurity** [comment] 2019-07-10 21:22
Maybe something like this:

![image](https://user-images.githubusercontent.com/802527/61006004-51a7f000-a337-11e9-97e2-2c97a6ef650e.png)

**Comment by salsakran** [comment] 2019-10-07 00:18
dupe of #3720

**Closed by salsakran** 2019-10-07 00:18 UTC
Labels: Type:Bug
