### ISSUE TITLE
Distribution on cached models that were originally JSONB does not work

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#35636] opened 2023-11-12 17:35 UTC
### Describe the bug

An interesting turnaround of events that lead to the query processor making wrong choices in which the distribution functionality will generate wrong SQL

### To Reproduce

1) get a postgres
2) run
```
-- Creating the table
CREATE TABLE sample_table (
    id SERIAL PRIMARY KEY,
    json_data JSONB
);

-- Inserting 10 sample values
INSERT INTO sample_table (json_data) VALUES
  ('{"name": "John Doe", "age": 25, "address": {"city": "New York", "zipcode": "10001"}}'),
  ('{"name": "Alice Smith", "age": 30, "address": {"city": "Los Angeles", "zipcode": "90001"}}'),
  ('{"name": "Bob Johnson", "age": 28, "address": {"city": "Chicago", "zipcode": "60601"}}'),
  ('{"name": "Eva Brown", "age": 35, "address": {"city": "San Francisco", "zipcode": "94105"}}'),
  ('{"name": "Chris White", "age": 22, "address": {"city": "Seattle", "zipcode": "98101"}}'),
  ('{"name": "Olivia Davis", "age": 27, "address": {"city": "Miami", "zipcode": "33101"}}'),
  ('{"name": "Daniel Lee", "age": 32, "address": {"city": "Dallas", "zipcode": "75201"}}'),
  ('{"name": "Sophia Garcia", "age": 29, "address": {"city": "Denver", "zipcode": "80202"}}'),
  ('{"name": "Matthew Taylor", "age": 26, "address": {"city": "Boston", "zipcode": "02108"}}'),
  ('{"name": "Emma Martinez", "age": 31, "address": {"city": "Phoenix", "zipcode": "85001"}}');
```
3) enable model caching
4) go to the sample_table table and make a question out of it
5) then save it as a model
6) enable model caching (cron expression to make it run every minute)
7) then do a distribution on the age column, see the error

ERROR: column "source.json_data" must appear in the GROUP BY clause or be used in an aggregate function
  Position: 125

### Logs

SELECT ("source"."json_data"#>> array[$1]::text[])::bigint AS "json_data → age", COUNT(*) AS "count" FROM (select * from "metabase_cache_f3484_2"."model_6_sample_tab") AS "source" GROUP BY "json_data → age" ORDER BY "json_data → age" ASC

### Information about your Metabase installation

```JSON
v47.x
```

### Severity

P2

### Additional context

Way out: disable model caching

**Comment by bshepherdson** [comment] 2024-02-29 22:30
This is a duplicate of #34930 .

**Closed** 2024-03-04 16:29 UTC
Labels: Type:Bug, Querying/Processor
