### ISSUE TITLE
Url values of generated fields should also be clickable

### ISSUE THREAD

**Issue by michael-jiang** [metabase/metabase#4502] opened 2017-03-08 18:46 UTC
Very similar to https://github.com/metabase/metabase/issues/3334 that was already improved, but it only applies to the URL typed fields in existing tables.

Would it be easy to apply this to fields in query-generated tables as well even if they are not able to be specified URL type explicitly? Best if it's possible to assign data types to all query generated table columns?

For example, I have a column in an existing table called ticket_token, while I query generate a URL column by prefixing it with the ticket system of the website, it should be clickable.

**Comment by tlrobinson** [comment] 2017-03-08 18:54
Duplicate of #4493

**Closed by tlrobinson** 2017-03-08 18:54 UTC
