### ISSUE TITLE
New dashboard modal takes the previous dashboard context when pressing "enter"

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#43157] opened 2024-05-24 21:51 UTC
### Describe the bug

Modal mayhem

### To Reproduce

1) create an empty dashboard, save it on the our analytics with name "first"
2) now create a question, save it, click "yes" when it asks you to add it to a dashboard
3) in the modal that opens, click on "create a new dashboard"
4) type in the 2nd modal "second" and press the "ENTER" key on your keyboard

... your question will be saved to "first" and not to "second" (second will never be created)

### Expected behavior

Second should be created with the question

### Logs

NA

### Information about your Metabase installation

```JSON
v50
```

### Severity

P2

**Comment by rafpaf** [comment] 2024-07-18 20:11
Illustration of the bug: https://www.loom.com/share/85925cd6f9f04cfba99a5e401990ca87?sid=aa7ed458-19b0-49f4-a55c-1f586ed038e5

**Comment by npfitz** [comment] 2024-07-26 13:13
Closing as a duplicate of https://github.com/metabase/metabase/issues/45360. Fix should already be in 50.16.

**Closed by npfitz** 2024-07-26 13:13 UTC
Labels: Type:Bug, .Duplicate, Priority:P2, Reporting/Dashboards, .Frontend, .Team/AdminWebapp
