### ISSUE TITLE
Error: Plan Should Not Reference Subplan's Variable on basic queries with Variables

### ISSUE THREAD

**Issue by doodlebro** [metabase/metabase#7216] opened 2018-03-27 17:18 UTC
I am running into an issue from time to time with certain views in my DB, however I cannot determine what it is about these views that causes this aside from the variable being used to filter on dates.

DB: Redshift
Metabase Version: 0.28.1

Gist of bug is in this picture:
![screen shot 2018-03-27 at 11 16 28 am](https://user-images.githubusercontent.com/7634378/37983334-62a0a1e4-31b0-11e8-9912-45d25e750add.png)

As you can see, this query won't run, however if I run this query on an actual SQL client and still filter on date using the where clause, it has no issue. I know that the problem lies in how the query is being built and accounting for the variable field, but I am unsure of how I can dig deeper than this.

Thanks

**Comment by doodlebro** [comment] 2018-03-29 16:15
I am also receiving this error when using the query builder on the same view and filtering on a date.

**Comment by tejasattoor** [comment] 2019-04-04 21:04
I am facing the same error even when just filtering the fields in Report Builder or Query Builder. The fields are from views created in Redshift. I wonder if it has to do with the way the views are built?

**Comment by jeff303** [comment] 2021-01-22 18:20
@doodlebro and/or @tejasattoor, do you happen to have any DDL statements you can share for the creation of these views and the backing tables?

**Comment by jeff303** [comment] 2021-02-04 15:53
Also, if anyone is able, please capture the native query form that is executed.  This can be seen in the JSON response to the `/query` API request.  If you know how to use Chrome dev tools, it looks something like this:

<img width="607" alt="Screen Shot 2021-02-04 at 9 50 57 AM" src="https://user-images.githubusercontent.com/3521562/106918084-81170e00-66ce-11eb-8439-2d652de38c55.png">

In particular, we're after the `native_form` from the Preview or Response tabs.

<img width="989" alt="Screen Shot 2021-02-04 at 9 51 28 AM" src="https://user-images.githubusercontent.com/3521562/106918286-aa379e80-66ce-11eb-82f3-45f90b477efb.png">

If this is too much trouble, you can also capture this full API call by right clicking on "query" on the left and choosing "Save all as HAR with content".  Redact any sensitive information and then attach that file.  Having this information will help us in reproducing/fixing the issue.  Thanks.

**Comment by flamber** [comment] 2021-11-10 15:56
Closing, since a lot has changed since and we haven't received any information and we're not able to reproduce.

**Closed by flamber** 2021-11-10 15:56 UTC
Labels: Type:Bug, Priority:P2, Database/Redshift, Querying/Parameters & Variables, Querying/Native
