### ISSUE TITLE
Nested queries using metrics need to include all columns used in metric filters

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8856] opened 2018-11-05 21:16 UTC
This is in RC 0.31, and I'm not sure if this is expected behavior or not.

If you have a saved metric, like the Average of Rating, filtered to `current year`, if you then create a saved question with it, like this:

![screen shot 2018-11-05 at 1 03 47 pm](https://user-images.githubusercontent.com/2223916/48027123-c23da380-e0fc-11e8-81b4-9ee550f3e40e.png)

…using that saved question as a nested query doesn't work because it seems it can't find the column used in the metric's filter:

![screen shot 2018-11-05 at 1 03 35 pm](https://user-images.githubusercontent.com/2223916/48027163-df727200-e0fc-11e8-8f43-e9f9f2631863.png)

Adding the "missing" column to the saved question fixes the nested query:

![screen shot 2018-11-05 at 1 15 54 pm](https://user-images.githubusercontent.com/2223916/48027202-fca74080-e0fc-11e8-96df-a4d904423509.png)

**Comment by nemanjaglumac** [comment] 2020-11-17 15:31
If I understand this correctly, [repro](https://github.com/metabase/metabase/pull/13816) for #12507 directly reproduces this issue as well?

**Comment by flamber** [comment] 2020-11-17 15:55
It's not quite the same, but since this metric is using a column, which isn't included - and when you add that, then the query works.
They are very related though, since it's all about how the nested references are done.

**Comment by sbelak** [comment] 2021-01-14 17:01
It is effectively the same in the sense that the fix for one will also fix the other

**Comment by flamber** [comment] 2021-05-27 16:30
Fixed by #16241

**Closed by flamber** 2021-05-27 16:30 UTC
Labels: Administration/Metrics & Segments, Priority:P2, Querying/Nested Queries, Type:Bug
