### ISSUE TITLE
Viewing Dashboard causes app to restart.

### ISSUE THREAD

**Issue by rberger** [metabase/metabase#4006] opened 2016-12-28 07:07 UTC
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Not using a browser with Metabase, Using Mac Client

- Your operating system: (e.x. OS X 10, Windows XP, etc)
macOS Sierra 10.12.2

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Postgres 9.5 (AWS RDS via ssh tunnel)

- Metabase version: (e.x. 0.19.3)
v0.21.1

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Mac App downloaded from Metabase site

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
Not sure what this is.

- *Repeatable steps to reproduce the issue*

I created 7 questions. After creating each one, I added it to the dashboard. Resized them a bit each time.

When I added the 6th one to the dashboard, the app restarted (See the dashboard starting to load and then it goes away and see the Metabase logo as if the app was just starting)

I then added the 6th manually (Opened the dashboard, hit the `+` button and added the question. That worked.

Then created the 7th question, tried to save it to the dashboard and the same restart happened.
Tried to open the Dashboard from the navigation bar and it shows the dashboard starting to load and then the app restarts. Can no longer view the Dashboard, let alone add new questions to it.

I don't see anything obvious in the logs, but I don't know what the logs should be looking like. (i.e no exceptions or strings like ERROR).

Any idea how to debug this?

Thanks!

**Comment by tlrobinson** [comment] 2016-12-28 19:47
@rberger I'm having trouble reproducing this. A couple questions:

1. Can you consistently reproduce this from scratch, or just the one dashboard that's broken?
2. When you say it "causes app to restart" I assume you mean the app in the browser, not the backend server, right?
3. Which logs are you looking at, the browser or server logs? Assuming you did mean the frontend app was restarting, could you check the browser console logs (the browser Web Inspector / Developer Tools)
4. What sort of visualizations did the questions have?
5. Was there anything different/notable about the 6th card?
6. Can you post (or send to tom@metabase.com) the JSON for the dashboard you're having problems with. Just load http://YOUR_METABASE_DOMAIN/api/dashboard/DASHBOARD_ID in the browser and copy the JSON. DASHBOARD_ID is the same as in http://YOUR_METABASE_DOMAIN/dash/DASHBOARD_ID when you try to view the dashboard in the app

**Comment by tlrobinson** [comment] 2016-12-28 19:51
Oh I just noticed you're using the Mac app. Is the entire Mac app crashing?

You can select "Copy Current URL to Clipboard" from the "Navigate" menu and view in a web browser on the same computer to see if it's a problem specific to the Mac app, and if not to view the browser logs.

**Comment by camsaul** [comment] 2017-01-09 17:41
@rberger can you try opening the link in your browser like @tlrobinson suggested? It will help us triage this issue.

**Comment by bhanna** [comment] 2017-02-07 16:12
I was having the same problem in the mac app, but it worked fine for me in chrome when I copied the link. Here is a video of the crash/restart happening in the mac app.

[metabase.mp4.zip](https://github.com/metabase/metabase/files/758254/metabase.mp4.zip)

**Comment by timiyay** [comment] 2017-02-09 23:52
I've been having this same issue on the Mac App v0.22.2.1.

Created a dashboard that links with a Postgres DB. Worked sweet yesterday.

Today, I load the Metabase app, go to the Welcome screen, click on my Dashboard. It opens for a couple of seconds, with loading spinners in each Question. Then, it transitions to an all-white loading screen with nothing but the Metabase logo. Then, it transitions back to the Welcome screen.

Works fine in Chrome.

**Comment by camsaul** [comment] 2017-03-01 22:53
Duplicate of #3950

**Closed by camsaul** 2017-03-01 22:53 UTC
Labels: Bug, Client/Mac App, Duplicate, Need More Info, Priority/P1
