### ISSUE TITLE
Error filter between dates in nested queries 

### ISSUE THREAD

**Issue by vitorfraga** [metabase/metabase#5893] opened 2017-09-05 19:36 UTC
First, metabase is really a very interesting tool and I intend to contribute in a more active way soon.
Throughout my usage I encountered a small problem, I would like to report.

- Your browser and the version:  Chrome 59.0.3071.115
- Your operating system:  Ubuntu 15.04
- Your databases: PostgresSQL v9.5.4
- Metabase version: v0.25.2
- Metabase hosting environment: Ubuntu 16.04
- Metabase internal database: PostgreSQL v9.6.3

Step 1

![image](https://user-images.githubusercontent.com/4948363/30079943-57b49a8a-9258-11e7-8426-f1d3966ce599.png)

Step 2

![image](https://user-images.githubusercontent.com/4948363/30079802-d388653e-9257-11e7-80f1-e4dfbb985198.png)

Step 3

![image](https://user-images.githubusercontent.com/4948363/30079833-ee7e9084-9257-11e7-8382-8f1a12f3b915.png)

obs: Sorry for my English.

Take care,

**Comment by flamber** [comment] 2019-02-16 21:49
Hi @vitorfraga 
I cannot reproduce your problem in 0.31.2 with Postgres 11.1 - can you please try again with the newer version of Metabase?

**Comment by flamber** [comment] 2020-03-02 18:46
Closing issue because of no reply and I cannot reproduce on 0.34.3

**Closed by flamber** 2020-03-02 18:46 UTC
Labels: Priority:P2, Querying/Nested Queries, Type:Bug
