### ISSUE TITLE
Allow sorting the column in public question

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4360] opened 2017-02-11 13:39 UTC
v0.23.0-snapshot / Built on 2017-02-10 / Branch: master / Hash: f1500ce

![image](https://cloud.githubusercontent.com/assets/1708680/22854107/b25d5ec8-f077-11e6-8115-dc4c53636887.png)

This is could be a bit similar on #4226

**Comment by tlrobinson** [comment] 2017-02-12 17:20
We can't safely allow users to modify sort order in public links queries.  e.x. "Top 10 salespeople this month" becomes "10 worst salespeople this month"

Closing this as a dupe of #4226 which I've renamed to cover both cases.

**Closed by tlrobinson** 2017-02-12 17:20 UTC
