### ISSUE TITLE
The question mark "?" character in the "?|" operator is interpreted as prepared statement parameter

### ISSUE THREAD

**Issue by anoakie** [metabase/metabase#41151] opened 2024-04-08 23:30 UTC
### Describe the bug

When using the [`?|` operator](https://www.postgresql.org/docs/9.5/functions-json.html#FUNCTIONS-JSONB-OP-TABLE) in a Postgres query, the Metabase interpreter interprets the `?` in the operator as a prepared statement parameter.

### To Reproduce

1. Go to New SQL Query
2. Enter `select '["a","b","c"]'::jsonb ?| array['c','d','e']::text[] where {{var}}  = 'asdf'`
3. Set `var`s Variable "Default filter widget value" as `asdf`
4. Hit the `|>` button

### Expected behavior

I'd expect any `?|` operator in the initial query to be preserved after the prepared statement is generated.

Instead, I get the error `No value specified for parameter 2.`

Here is the query preview:
```sql
select '["a","b","c"]'::jsonb 'asdf'| array['c','d','e']::text[] where ? = 'asdf'
```
(note the `'asdf'|` in the above query preview - That should be `?|`)

Here's what I'd expect it to be:
```sql
select '["a","b","c"]'::jsonb ?| array['c','d','e']::text[] where 'asdf' = 'asdf';
```

### Logs

Admin logs follow:
```[cc6e031f-71e8-4497-98df-5c80fe8cc5eb] 2024-04-08T16:04:06-07:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: No value specified for parameter 2.```

```js
{:database_id 4,
 :started_at #t "2024-04-08T16:04:06.127859-07:00[US/Pacific]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query: No value specified for parameter 2.",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__79250$fn__79251.invoke(execute.clj:701)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__79250.invoke(execute.clj:698)"
    "driver.sql_jdbc.execute$fn__79043$fn__79044.invoke(execute.clj:388)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:334)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:317)"
    "driver.sql_jdbc.execute$fn__79043.invokeStatic(execute.clj:382)"
    "driver.sql_jdbc.execute$fn__79043.invoke(execute.clj:380)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:692)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:689)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
    "driver.sql_jdbc$fn__106638.invokeStatic(sql_jdbc.clj:78)"
    "driver.sql_jdbc$fn__106638.invoke(sql_jdbc.clj:76)"
    "query_processor.context$executef.invokeStatic(context.clj:60)"
    "query_processor.context$executef.invoke(context.clj:49)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:44)"
    "query_processor.context.default$default_runf.invoke(default.clj:42)"
    "query_processor.context$runf.invokeStatic(context.clj:46)"
    "query_processor.context$runf.invoke(context.clj:40)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:39)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:36)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___72138.invoke(cache.clj:229)"
    "query_processor.middleware.permissions$check_query_permissions$fn__66516.invoke(permissions.clj:140)"
    "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__71959.invoke(enterprise.clj:51)"
    "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__71969.invoke(enterprise.clj:64)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__71401.invoke(mbql_to_native.clj:24)"
    "query_processor$fn__73306$combined_post_process__73311$combined_post_process_STAR___73312.invoke(query_processor.clj:262)"
    "query_processor$fn__73306$combined_pre_process__73307$combined_pre_process_STAR___73308.invoke(query_processor.clj:259)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__66613.invoke(fetch_source_query.clj:303)"
    "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__72049$fn__72053.invoke(resolve_database_and_driver.clj:77)"
    "driver$do_with_driver.invokeStatic(driver.clj:97)"
    "driver$do_with_driver.invoke(driver.clj:92)"
    "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__72049.invoke(resolve_database_and_driver.clj:76)"
    "query_processor.middleware.store$initialize_store$fn__67219$fn__67220.invoke(store.clj:14)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
    "query_processor.middleware.store$initialize_store$fn__67219.invoke(store.clj:13)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database$fn__72046.invoke(resolve_database_and_driver.clj:60)"
    "query_processor.middleware.normalize_query$normalize$fn__72351.invoke(normalize_query.clj:38)"
    "query_processor.middleware.enterprise$fn__71986$handle_audit_app_internal_queries__71987$fn__71989.invoke(enterprise.clj:96)"
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__71997.invoke(enterprise.clj:103)"
    "query_processor.middleware.constraints$mark_needs_default_userland_constraints$fn__71112.invoke(constraints.clj:104)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__72282.invoke(process_userland_query.clj:156)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__72883.invoke(catch_exceptions.clj:171)"
    "query_processor.reducible$async_qp$qp_STAR___62758$thunk__62760.invoke(reducible.clj:126)"
    "query_processor.reducible$async_qp$qp_STAR___62758.invoke(reducible.clj:132)"
    "query_processor.reducible$sync_qp$qp_STAR___62770.doInvoke(reducible.clj:153)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:402)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:398)"
    "query_processor$process_query_and_save_execution_BANG_.invokeStatic(query_processor.clj:416)"
    "query_processor$process_query_and_save_execution_BANG_.invoke(query_processor.clj:406)"
    "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invokeStatic(query_processor.clj:431)"
    "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invoke(query_processor.clj:421)"
    "api.dataset$run_query_async$fn__93841.invoke(dataset.clj:79)"
    "query_processor.streaming$streaming_response_STAR_$fn__53188$fn__53190.invoke(streaming.clj:168)"
    "query_processor.streaming$streaming_response_STAR_$fn__53188.invoke(streaming.clj:167)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
    "async.streaming_response$do_f_async$task__43756.invoke(streaming_response.clj:88)"],
   :error_type :invalid-query,
   :ex-data
   {:driver :postgres,
    :sql
    ["-- Metabase:: userID: REDACTED queryType: native queryHash: 7868f8dd211e1e48f15967e9a9ebf0d87d22a98babd6274e1da28038319f4ad9"
     "select"
     "  '[\"a\",\"b\",\"c\"]' :: jsonb ? | array [ 'c',"
     "  'd',"
     "  'e' ] :: text [ ]"
     "where"
     "  ? = 'asdf'"],
    :params ["asdf"],
    :type :invalid-query}}],
 :action_id nil,
 :state "22023",
 :error_type :invalid-query,
 :json_query
 {:type "native",
  :database 4,
  :native
  {:query "select '[\"a\",\"b\",\"c\"]'::jsonb ?| array['c','d','e']::text[]\nwhere {{variable}} = 'asdf'",
   :template-tags
   {:variable
    {:type "text",
     :name "variable",
     :id "40defe9d-77af-498a-9a8a-d830f7f7e568",
     :display-name "Variable",
     :default "asdf"}}},
  :parameters
  [{:id "40defe9d-77af-498a-9a8a-d830f7f7e568",
    :type "category",
    :value ["asdf"],
    :target ["variable" ["template-tag" "variable"]]}],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :status :failed,
 :class org.postgresql.util.PSQLException,
 :stacktrace
 ["org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:346)"
  "org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)"
  "org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)"
  "org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)"
  "org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194)"
  "org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:137)"
  "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)"
  "--> driver.sql_jdbc.execute$fn__79167.invokeStatic(execute.clj:556)"
  "driver.sql_jdbc.execute$fn__79167.invoke(execute.clj:554)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:569)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:565)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__79250$fn__79251.invoke(execute.clj:699)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__79250.invoke(execute.clj:698)"
  "driver.sql_jdbc.execute$fn__79043$fn__79044.invoke(execute.clj:388)"
  "driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:334)"
  "driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:317)"
  "driver.sql_jdbc.execute$fn__79043.invokeStatic(execute.clj:382)"
  "driver.sql_jdbc.execute$fn__79043.invoke(execute.clj:380)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:692)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:689)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
  "driver.sql_jdbc$fn__106638.invokeStatic(sql_jdbc.clj:78)"
  "driver.sql_jdbc$fn__106638.invoke(sql_jdbc.clj:76)"
  "query_processor.context$executef.invokeStatic(context.clj:60)"
  "query_processor.context$executef.invoke(context.clj:49)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:44)"
  "query_processor.context.default$default_runf.invoke(default.clj:42)"
  "query_processor.context$runf.invokeStatic(context.clj:46)"
  "query_processor.context$runf.invoke(context.clj:40)"
  "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:39)"
  "query_processor.reducible$identity_qp.invoke(reducible.clj:36)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___72138.invoke(cache.clj:229)"
  "query_processor.middleware.permissions$check_query_permissions$fn__66516.invoke(permissions.clj:140)"
  "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__71959.invoke(enterprise.clj:51)"
  "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__71969.invoke(enterprise.clj:64)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__71401.invoke(mbql_to_native.clj:24)"
  "query_processor$fn__73306$combined_post_process__73311$combined_post_process_STAR___73312.invoke(query_processor.clj:262)"
  "query_processor$fn__73306$combined_pre_process__73307$combined_pre_process_STAR___73308.invoke(query_processor.clj:259)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__66613.invoke(fetch_source_query.clj:303)"
  "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__72049$fn__72053.invoke(resolve_database_and_driver.clj:77)"
  "driver$do_with_driver.invokeStatic(driver.clj:97)"
  "driver$do_with_driver.invoke(driver.clj:92)"
  "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__72049.invoke(resolve_database_and_driver.clj:76)"
  "query_processor.middleware.store$initialize_store$fn__67219$fn__67220.invoke(store.clj:14)"
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)"
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)"
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
  "query_processor.middleware.store$initialize_store$fn__67219.invoke(store.clj:13)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database$fn__72046.invoke(resolve_database_and_driver.clj:60)"
  "query_processor.middleware.normalize_query$normalize$fn__72351.invoke(normalize_query.clj:38)"
  "query_processor.middleware.enterprise$fn__71986$handle_audit_app_internal_queries__71987$fn__71989.invoke(enterprise.clj:96)"
  "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__71997.invoke(enterprise.clj:103)"
  "query_processor.middleware.constraints$mark_needs_default_userland_constraints$fn__71112.invoke(constraints.clj:104)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__72282.invoke(process_userland_query.clj:156)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__72883.invoke(catch_exceptions.clj:171)"
  "query_processor.reducible$async_qp$qp_STAR___62758$thunk__62760.invoke(reducible.clj:126)"
  "query_processor.reducible$async_qp$qp_STAR___62758.invoke(reducible.clj:132)"
  "query_processor.reducible$sync_qp$qp_STAR___62770.doInvoke(reducible.clj:153)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:402)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:398)"
  "query_processor$process_query_and_save_execution_BANG_.invokeStatic(query_processor.clj:416)"
  "query_processor$process_query_and_save_execution_BANG_.invoke(query_processor.clj:406)"
  "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invokeStatic(query_processor.clj:431)"
  "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invoke(query_processor.clj:421)"
  "api.dataset$run_query_async$fn__93841.invoke(dataset.clj:79)"
  "query_processor.streaming$streaming_response_STAR_$fn__53188$fn__53190.invoke(streaming.clj:168)"
  "query_processor.streaming$streaming_response_STAR_$fn__53188.invoke(streaming.clj:167)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
  "async.streaming_response$do_f_async$task__43756.invoke(streaming_response.clj:88)"],
 :card_id nil,
 :context :ad-hoc,
 :error "No value specified for parameter 2.",
 :row_count 0,
 :running_time 0,
 :data {:rows [], :cols []}}
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.10.209-198.812.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "US/Pacific"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.22"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-04-02",
      "tag": "v0.49.3",
      "hash": "dba0992"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

annoying

### Additional context

I'm using `??|` to escape the question mark in the operator for now.

**Comment by ignacio-mb** [comment] 2024-04-10 15:00
Related to https://github.com/metabase/metabase/issues/34402

**Comment by camsaul** [comment] 2024-07-01 22:52
This is a limitation, since `?` in JDBC is interpreted as a parameter placeholder you have to escape Postgres JSON operators and use `??` instead; in this case you need to use `??|` instead of `?|`.

Duplicate of #1964

**Closed by camsaul** 2024-07-01 22:52 UTC
Labels: Type:Bug, Priority:P2, Database/Postgres, Querying/Processor, .Team/QueryProcessor
