### ISSUE TITLE
Support postgres inet type

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3182] opened 2016-08-12 17:29 UTC
None of the available filters for the IP address field seem to work. I've tried switching the field's metadata type both to none as well as category. It always returns this error:

```
ERROR: operator does not exist: inet = character varying Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts. Position: 1148
```

![ip-addresses](https://cloud.githubusercontent.com/assets/2223916/17631114/8d7b1df6-6077-11e6-9a79-87a72dca8fea.png)

**Comment by tlrobinson** [comment] 2016-08-12 17:39
I'm guessing this is more of a query processor / sync issue than a query builder issue.

**Comment by camsaul** [comment] 2016-08-12 18:40
Yeah this isn't a bug this is just a field type we don't currently support. This is another thing that would be easy to fix if we implement #2663

**Comment by camsaul** [comment] 2016-08-12 18:40
Actually this is a duplicate of #1891

**Comment by mazameli** [comment] 2016-08-12 18:41
I guess my expectation was that MB would just treat this as a string and let me filter the string.

**Comment by camsaul** [comment] 2016-08-12 18:41
MB needs to convert the string to a `inet` address type before sending it to postgres in the query processor

**Closed** 2016-08-12 18:41 UTC
Labels: Duplicate, Metadata/Sync, Query Language (MBQL), Query Processor
