### ISSUE TITLE
Simple Question: column formatting sidebar doesn't update when another column is selected

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#16272] opened 2021-05-27 18:56 UTC
**Describe the bug**
In the "Simple Question" editor, if I open the column formatting options sidebar and then try to open formatting options for another column, the sidebar displays settings for the column I selected first. It works fine if I close the sidebar and then open it again for another column. 

**To Reproduce**
1. From the main page, click "Ask a question" in the header
2. Select "Simple Question"
3. Pick any table
4. Click any column (let's pretend it's called "Title")
5. Click a gear icon in the popup
6. A column formatting sidebar appears on the left
7. Click any other column (let's pretend it's called "Tax")
8. Click a gear icon in the popup
9. The column formatting sidebar still displays the "Title" column's settings

**Expected behavior**
The column formatting sidebar has to display "Tax" column formatting settings

**Video**

https://user-images.githubusercontent.com/17258145/119881603-1f590900-bf36-11eb-809f-0dd94e4698d2.mov

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Safari 14.1 (16611.1.21.161.6)
- Your operating system: macOS Big Sur 11.3.1
- Metabase version: latest `master` ([this commit](https://github.com/metabase/metabase/commit/dfca7086fee5763168b074550220b00fbcaac0dc) specifically)
- Metabase hosting environment: JAR file
- Metabase internal database: H2 (default)

**Comment by flamber** [comment] 2021-05-27 19:00
Duplicate of #16043

**Closed by flamber** 2021-05-27 19:00 UTC
Labels: .Needs Triage, .bugbash, Querying/GUI, Type:Bug
