### ISSUE TITLE
line chart using a single series w/ 2 high-cardinality dimensions is generating an empty graph

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#2030] opened 2016-02-26 00:06 UTC
Since we added the ability to do multi-series charting in the query builder with 2 dimensions some high cardinality fields seem to be causing issues with how the charting assigns values to the axis. 

In the example I found that broke, looking at Cound of people by CreatedAt and State the state was assigned to the X axis

**Comment by agilliland** [comment] 2016-02-26 20:43
ack.  we really need a better set of information when filing issues like this.  it's tough to start working on this without any information beyond the title.

**Comment by kdoh** [comment] 2016-02-26 21:05
Yeah my bad on that. Updated with more details in the description.

**Comment by agilliland** [comment] 2016-02-26 22:49
So, I'm actually going to defer this until the next release because I don't see a clear path to resolving this quickly.  

The example you gave is not so much about putting the date value on the x-axis and is more so a problem because you are using 2 high cardinality dimensions, specifically 700+ and 60+ values, for the 2 dimensions mentioned in your query.  Trying to chart data like that is effectively always going to blow up because it's too much to show in a chart at the same time.  Everything is working just fine as long as at least one of the dimensions is less than 10 (e.g. count of products grouped by category & created_at looks fine)

So the more important long term question is what should a user see when they try to chart a multi-dimensional series that has 2 high cardinality dimensions?  What's the intended behavior?

**Comment by kdoh** [comment] 2016-02-26 22:59
Gotcha. It'd be nice if we could find a way to fail more gracefully in cases like this. I agree its a bit nonsensical to try and see every state at once but since its an easy choice to make in the UI we should probably do better than just showing an empty chart or a broken one. 

Shorter term we could show a message like "Too many values of <Non time high cardinality dimension>. Please choose which values of <dimension> you'd like to see" to at least give some feedback. 

It wouldn't work for every case necessarily but I wonder if longer term we could do something like produce an average of the values of the dimension as an overview and then prompt the user to refine, or have them select up to 10 of the values of the dimension and then produce the chart.

**Comment by mazameli** [comment] 2016-02-26 23:19
"Remember to index the dimension first" ;)

**Comment by agilliland** [comment] 2016-03-16 17:58
@tlrobinson this may be something that's easier for you to look at (or maybe is already handled).  @kdoh i do also think this is a special case that requires some design consideration because at the most basic level trying to chart any dataset which has 2+ high cardinality dimensions is likely to be very difficult, so we need a desired UX approach to this.

**Comment by kdoh** [comment] 2016-03-16 23:34
Yeah this is definitely a tricky one. I've been trying to think of a simple solution and I can't at the moment without a bit more consideration / exploration. One random idea I had was could you somehow "paginate"  so you're only ever showing N at a time but then you lose a sense of relativity for the set overall. Although I don't know if I can think of a way to get a sense of the whole set when the dimensions are high cardinality like the examples we're talking about here.

**Comment by agilliland** [comment] 2016-03-18 00:32
Okay, I'm going to downgrade this one to a Limitation then because realistically we don't even know what the intended behavior is, so it can't really be a Bug.  I'm also going to un-assign it from 0.16 unless we feel that we will have the solution in the next day or so.

**Comment by flamber** [comment] 2021-03-15 15:51
I cannot reproduce on 0.38.1 - closing
![image](https://user-images.githubusercontent.com/1447303/111181709-88bfb180-85ae-11eb-9f3e-23fe2f3044e8.png)

**Closed by flamber** 2021-03-15 15:51 UTC
Labels: .Limitation, Visualization/
