### ISSUE TITLE
Conditionally show the available option from the table when using field filter

### ISSUE THREAD

**Issue by jie970326** [metabase/metabase#8821] opened 2018-10-30 04:10 UTC
Can I conditionally show the list of the available options (maybe 5) for the dropdown while using field filter that map to a table column which have 20 available options?

- Current Metabase version v0.30.4

**Comment by jornh** [comment] 2018-10-30 17:16
Is what you want similar to the enhancement request in https://github.com/metabase/metabase/issues/5540?

**Comment by walterl** [comment] 2020-03-11 18:56
Yes, @jornh, I think it is. Closing this one as a duplicate of #5540.

**Closed by walterl** 2020-03-11 18:56 UTC
Labels: .Proposal, Querying/Native, Querying/Parameters & Variables
