### ISSUE TITLE
Impossible to filter on "null" foreign key

### ISSUE THREAD

**Issue by ronny35** [metabase/metabase#12464] opened 2020-05-05 13:53 UTC
Currently, when I use "is empty" filter option on corresponding foreign key, I have this error:
`invalid hexadecimal representation of an ObjectId: []`

**Logs**
05-05 13:49:15 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 3,
:started_at (t/zoned-date-time "2020-05-05T13:49:14.432849Z[GMT]"),
:json_query {:type "query", :query {:source-table 16, :filter ["is-null" ["field-id" 219]]}, :database 3, :parameters [], :middleware {:add-default-userland-constraints? true}},
:native nil,
:status :failed,
:class java.lang.IllegalArgumentException,
:stacktrace
["org.bson.types.ObjectId.parseHexString(ObjectId.java:550)"
"org.bson.types.ObjectId.<init>(ObjectId.java:239)"
"--> driver.mongo.query_processor$eval570$fn__572.invoke(query_processor.clj:230)"

**Settings**
- Your databases: MongoDB
- Metabase version: metabase/metabase:v0.35.3
- Metabase hosting environment: Dokcer
- Metabase internal database: H2

**Severity**
This report is critical in order to get orphan object for example.

**Comment by flamber** [comment] 2020-05-05 13:56
Duplicate of #11134

**Closed by flamber** 2020-05-05 13:56 UTC
Labels: .Duplicate
