### ISSUE TITLE
JAR download should be HTTPS and/or include checksum

### ISSUE THREAD

**Issue by fulldecent** [metabase/metabase#8714] opened 2018-10-17 15:21 UTC
At the main install URL:

> https://www.metabase.com/start/jar.html

The main call to action is to click the DOWNLOAD METABASE.JAR button.

The URL for this button links to: 

> http://downloads.metabase.com/v0.30.4/metabase.jar

Therefore, this recommendation is to download over HTTP, don't validate the file and then (probably) run it as root on your production server.

This is not best practice.

---

# Recommendations:

1. Set up HTTPS on downloads.metabase.com and link to that version.
2. Include SHA sum on the pages that recommend users to download the JAR.

**Comment by jornh** [comment] 2018-10-17 19:09
Duplicate of https://github.com/metabase/metabase/issues/3993

If you agree please close this issue and add your 👍 vote over there.

**Closed** 2018-10-18 00:06 UTC
