### ISSUE TITLE
Foreign key filter returns no data

### ISSUE THREAD

**Issue by marcuszani** [metabase/metabase#16751] opened 2021-06-24 12:00 UTC
**Describe the bug**

The problem occurs when filtering a column in the top header that has a linked foreign key.
Let's say the foreign key is product ID (table 1) which is linked to the product ID (table 2) of another table and what is displayed is the product name (table 2) of this second table.

Clicking on the top header to filter it shows the categories based on product name (table 2) ok this is wonderful, but clicking on the category you want to filter the data returns blank.
Most likely it at this point uses the product name as the search and not the product ID causing the bug.

**Comment by flamber** [comment] 2021-06-24 12:04
Without more information I have no idea, but closing a duplicate of #13235

**Closed by flamber** 2021-06-24 12:04 UTC
Labels: .Needs Triage, Type:Bug
