### ISSUE TITLE
Download straight to excel

### ISSUE THREAD

**Issue by Hermii2** [metabase/metabase#34308] opened 2023-10-03 10:35 UTC
**Is your feature request related to a problem? Please describe.**
I want the option to download straight to excel, instead of having to run the query before you get the option.

**Describe the solution you'd like**
Click the download to excel button straight away, so you dont have to run the query twise

**Describe alternatives you've considered**
only alternative is running the query beforehand, which takes more time.

**How important is this feature to you?**
would save me some time

**Comment by paoliniluis** [comment] 2023-10-04 17:03
@Hermii2 please add more context or we'll have to close the issue

**Comment by Hermii2** [comment] 2023-10-04 17:59
Im using metabase for running queries and dumping them to excel yes. It often takes a few minutes (3-4) to run the query, then the same to get the data. Would be convenient if you could do it in one go.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by paoliniluis** [comment] 2023-10-05 04:18
duplicate of https://github.com/metabase/metabase/issues/4820

**Closed by paoliniluis** 2023-10-05 04:18 UTC
Labels: Type:New Feature, .Needs Triage
