### ISSUE TITLE
Upgrade org.liquibase/liquibase-core '4.11.0' to '4.18.0'

### ISSUE THREAD

**Issue by john-metabase** [metabase/metabase#27370] opened 2022-12-21 16:44 UTC
Liquibase 4.18 causes issues with certain change types that need to be investigated. We either need to update the migrations, or determine if there is a bug in Liquibase that prevents us from upgrading to this version and then plan on upgrading to a later version when available.

**Comment by camsaul** [comment] 2023-03-13 17:29
Duplicate of #29107

**Closed by camsaul** 2023-03-13 17:29 UTC
Labels: Type:Tech Debt, .Backend
