### ISSUE TITLE
Enter submits Entity Picker modal and Create dashboard modal simultaneously

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#43994] opened 2024-06-11 09:37 UTC
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/f31c7c0f-51fb-4ee9-bcc9-c95b180b013e

### To Reproduce

1. Be on some dashboard
2. New > Question > Orders > Save > Save > Yes please!
3. Open "Dashboards" tab
4. Click "Create a new dashboard"
5. Type "Totally new dashboard" and hit Enter in the "Create a new dashboard" modal

Question is added to dashboard from step 1

### Expected behavior

Dashboard is created and selected in the Entity Picker modal, but Entity Picker modal is still shown and not submitted.

### Information about your Metabase installation

master, 4594299

### Severity

P2

**Comment by npfitz** [comment] 2024-07-31 19:03
Closing this as a duplicate of https://github.com/metabase/metabase/issues/45360, which was resolved with https://github.com/metabase/metabase/pull/45989

**Closed by npfitz** 2024-07-31 19:03 UTC
Labels: Type:Bug, Priority:P2, Reporting/Dashboards, .Frontend, .Team/AdminWebapp
