### ISSUE TITLE
Cannot filter by second Left Join in Nested Query

### ISSUE THREAD

**Issue by c-oreills** [metabase/metabase#9799] opened 2019-04-17 12:42 UTC
I have manually made a SQL question which left joins visits to two ratings tables (using Postgres)

The SQL looks like this:

```
SELECT "public"."work_visit".*,
       "public"."rating_visitrating"."id" AS "customer_rating_id", "public"."rating_visitrating"."rating" AS "customer_rating_rating", ...
       "public"."rating_workervisitrating"."id" AS "worker_rating_id", "public"."rating_workervisitrating"."rating" AS "worker_rating_rating", ... 
FROM "public"."work_visit"
LEFT JOIN "public"."rating_visitrating" ON "public"."rating_visitrating"."visit_id" = "public"."work_visit"."id"
LEFT JOIN "public"."rating_workervisitrating" ON "public"."rating_workervisitrating"."visit_id" = "public"."work_visit"."id"
```

I'm then using this to try to power other Questions using nested queries.

Metabase successfully recognises the fields in customer ratings (e.g. it knows that `customer_rating_rating` is an int and can filter by it using methods like greater than) but it doesn't do the same for worker ratings (filtering on `worker_rating_rating` I only get the options for is/is not/is empty/not empty, and trying to use `is` fails)

Metabase knows that both the rating tables I'm joining on have foreign keys to the visit table.

There are just under 60 fields in total across all 3 tables - not sure if this should cause the issue though?

**Comment by flamber** [comment] 2019-04-17 20:00
Hi @c-oreills 
I cannot reproduce this issue on 0.32.4 with Sample Dataset on Postgres.
What is the real Postgres column type of `"public"."rating_workervisitrating"."rating"`?
And what is the Field Type in Settings > Admin > Data Model > (database) > (table) > (column) :gear: ?
```
SELECT "SampleData"."orders".*, "SampleData"."products"."rating" AS "product_rating", "SampleData"."reviews"."rating" AS "review_rating"
FROM "SampleData"."orders"
LEFT JOIN "SampleData"."products" ON "SampleData"."orders"."product_id" = "SampleData"."products"."id"
LEFT JOIN "SampleData"."reviews" ON "SampleData"."reviews"."product_id" = "SampleData"."orders"."product_id"
```
![image](https://user-images.githubusercontent.com/1447303/56316942-d27c9480-6118-11e9-9a60-0ca603054603.png)

**Comment by c-oreills** [comment] 2019-04-18 07:36
Both `rating` fields are Score types in Metabase admin, `smallints` in Postgres.

Could be unrelated, but we have a different table with a foreign key to `workervisitrating`: `ratingissues`. If I start a new question using `ratingissues` and try to add `workervisitrating` columns to the raw data table view, nothing happens upon clicking the '+' button.

The sanitised API response from api/dataset after hitting plus button is in [this gist](https://gist.github.com/c-oreills/d451ee83640e6a27a554004280f5ae20) - hopefully that's helpful in diangosing.

**Comment by flamber** [comment] 2019-04-18 16:56
If nothing happens, when you click the `+` button, then check your browser console or Metabase log for any warnings/errors.
Looking at the gist, it looks like a different query from the one you first posted. And it has two aliases with the same name, which should result in an error:
`... "rating_workervisitrating__via_"."rating" AS "rating", "rating_workervisitrating__via_"."rating" AS "rating" ...`

**Comment by c-oreills** [comment] 2019-04-19 06:23
Yes, sorry, to be clear the gist is from the plus button case, not the
original thing, just thought it may be helpful in diagnosing the
issue/seeing the table structure in a more simple way.

The aliases have been autogenerated after clicking + (potentially twice, I
can check this). Do they come from Metabase or Postgres? And is there a
reason the length is capped? Not sure if that's a Metabase issue or not.

I can get you output from the original nested query case but not sure what
would be best to debug with? What would be most helpful?

**Comment by c-oreills** [comment] 2019-04-19 07:28
Re: checking logs, will do that when I have access to my machine later.

**Comment by flamber** [comment] 2019-04-19 15:09
@c-oreills I'm not sure what's going on, but I cannot reproduce this issue, so I think you need to provide full database examples. And don't mix different issues.

**Comment by flamber** [comment] 2020-03-03 15:07
Closing since no new reports and I cannot reproduce on 0.34.3
And 0.33.0 introduced a new advanced interface to make joins via the Notebook editor:
https://www.metabase.com/docs/latest/users-guide/custom-questions.html
If you have any new information, then please comment and I'll reopen this issue.

**Closed by flamber** 2020-03-03 15:07 UTC
Labels: .Unable to Reproduce
