### ISSUE TITLE
Events do not appear for current week when filtering on previous weeks

### ISSUE THREAD

**Issue by cbalusek** [metabase/metabase#42219] opened 2024-05-03 16:16 UTC
### Describe the bug

When filtering on "Show previous x weeks" and also choosing "Include this week" the events calendar does not include the current week.  The events sidebar nicely tells you that it's excluding your current week.  For example, I created an event occurring on May 1st (which is the week in which I'm writing this) and it's not appearing as the sidebar shows:

<img width="236" alt="image" src="https://github.com/metabase/metabase/assets/22856340/597a546b-d8ab-4080-8f34-f63127f86830">

### To Reproduce

1. Create a report with a time series that includes today (the Orders table seemed to do okay in the sample database)
2. Used the Created At (if using the Orders table) and do a Distribution from the column header
3. Change the filter at the bottom of the screen to "View Previous 13 weeks by week"
4. Change the filter from the filter dialogue at the top of the chart to Include This Week
5. (Remind yourself to file another issue about how annoying it is that it's not at the bottom of the screen too)
6. Click on the Events side bar  (it's the calendar icon on the bottom right)
7. Create a new event that falls between the start of the week and today
8. Notice how it does not appear.  
9. If you are me, you'll also create the event again, thinking you did something wrong.

### Expected behavior

If an event is this week and I'm showing this week, I should see the event.

### Information about your Metabase installation

```JSON
- On master
```

### Severity

It's annoying but it's not blocking

**Comment by calherries** [comment] 2024-05-07 09:15
Reproduced on 49 branch (dd71f00dd7) and master (43c0ce979a)

**Comment by kulyk** [comment] 2024-06-13 13:13
Duplicate of #23336

**Closed by kulyk** 2024-06-13 13:13 UTC
Labels: Type:Bug, Priority:P2, .Frontend, Visualization/Charts/Events, .Team/DashViz
