### ISSUE TITLE
Metabase Filters issue

### ISSUE THREAD

**Issue by AnasTauha** [metabase/metabase#5725] opened 2017-08-10 10:34 UTC
------
Metabase Filters on questions not working for varchar field
-----
I have integrated metabase with mysql and added several filters on varchar field in a question, from the snapshot below we can see that the question is bringing correct value.
![error1](https://user-images.githubusercontent.com/30893984/29166652-b659e810-7de0-11e7-9a5c-4b919123fe5b.png)

However when I try and copy the value for the filtered column Msisdn, it doesnt let me select it to filter it.
![error2](https://user-images.githubusercontent.com/30893984/29166680-dce04d1c-7de0-11e7-8c8c-1ab6b0c4edd2.png)

The Date filter is working fine, the Varchar field that is under primary key is also working fine, the only issue is when a normal column is varchar and the widget type is **category**. This is just one example and I am facing the same issue on different varchar columns. Any idea what is causing this issue?

**Comment by salsakran** [comment] 2017-09-06 22:47
does it appear when you autocomplete?

Also, is it a value that has been added recently? While we try to scan field values (to populate category widgets), it's an expensive process that we don't do all that often.

**Comment by AnasTauha** [comment] 2017-09-07 09:09
It is not a value that has been added recently it is a pretty old value and this was just an example its not working for any of the values entered. And no it is not appearing in the autocomplete as well even though it is their in the data table.

**Comment by flamber** [comment] 2020-06-02 15:26
Closing, since this was likely caused by an incomplete scan. There has been many improvements right up until latest release 0.35.4 - please comment with details if you're still experiencing this.

**Closed by flamber** 2020-06-02 15:26 UTC
Labels: Administration/Metadata & Sync, Querying/Native
