### ISSUE TITLE
Support Referencing SQL of Other Questions in for SQL Questions

### ISSUE THREAD

**Issue by friendofasquid** [metabase/metabase#12000] opened 2020-02-27 10:52 UTC
It's possible to compose questions from others in the Custom Question type, which is a great way to do some modelling in Metabase using SQL. 

However, there is no way to leverage the SQL of other questions in "Native Query" question type. What I'm propose is a small enhancement to the templating language the replaces a variable with the SQL of a question.

For example, say we had a saved question the looked like this:

```sql
SELECT SUM(value) AS value, account_id FROM transactions GROUP BY account_id
```

and we saved that as a question with id `12`.

Now I want to reuse that query, so I could do:

```sql
SELECT AVG(value) FROM ( {{question:12}} )
```

which would generate the query

```sql
SELECT AVG(value) FROM ( 
  SELECT SUM(value) AS value, account_id FROM transactions GROUP BY account_id
)
```

Note that this could work regardless of whether the referenced question was native or not, as they all generate some SQL behind the scenes.

**Comment by flamber** [comment] 2020-02-27 10:57
Duplicate of #5579. Was added yesterday and will be part of 0.35.0

**Closed by flamber** 2020-02-27 10:57 UTC
Labels: .Needs Triage, Type:New Feature
