### ISSUE TITLE
Latitude, Longitude reversed on Leaflet maps?

### ISSUE THREAD

**Issue by mattxbart** [metabase/metabase#3946] opened 2016-12-14 00:07 UTC
I just upgraded to the new metabase release with leaflet maps. All of my map points now appear in a line (they don't appear to have the proper lat, lon on them). When I flip the latitude and longitude field types in the data model they appear correctly, so seems like leaflet is reading the points in reverse, probably an artifact of switching from google maps... I also built a .jar off master and the problem still exists. 

- Your databases: postgresql
- Metabase version: master
- Metabase hosting environment: ubuntu 16
- Metabase internal database: postgres 9.5

**Comment by tlrobinson** [comment] 2016-12-14 00:08
Duplicate of #3906, fixed by #3907, will be fixed in v0.21.1.

**Closed by tlrobinson** 2016-12-14 00:08 UTC
