### ISSUE TITLE
Garbled text when sending emails

### ISSUE THREAD

**Issue by weiyu199** [metabase/metabase#33903] opened 2023-09-15 08:14 UTC
### Describe the bug

There is no problem in metabase, but when the mail is sent, the mail page display is garbled
<img width="796" alt="image" src="https://github.com/metabase/metabase/assets/145106886/da463647-9603-409a-8795-4665e154a832">
<img width="612" alt="image" src="https://github.com/metabase/metabase/assets/145106886/8c65bdbc-a402-4035-8745-9a1f8467b0a7">

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8-LTS",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8-LTS",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.92.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.38-220701-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-05-18",
      "tag": "v0.46.3",
      "branch": "release-x.46.x",
      "hash": "8d74de2"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

 certainly

**Comment by paoliniluis** [comment] 2023-09-15 12:28
dupe of https://github.com/metabase/metabase/issues/2342

**Closed by paoliniluis** 2023-09-15 12:28 UTC
Labels: Type:Bug, .Needs Triage
