### ISSUE TITLE
Error processing query: Input to store-field! does not match schema with MySQL JSON field

### ISSUE THREAD

**Issue by hejhugo** [metabase/metabase#32913] opened 2023-08-03 15:35 UTC
### Describe the bug

We're facing an issue similar to [#22873](https://github.com/metabase/metabase/issues/22873). A particular table in our database is unqueryable unless the user explicitly de-selects the "Review Count By Purpose →" field. This table has a MySQL JSON column named "review_count_by_purpose".

The error thrown is:
```
Error processing query: Input to store-field! does not match schema: 
[(named {:nfc_path [nil (not ("Non-blank string" ""))]} field)]
```

A complete stack trace of the error is attached below.

### Workaround

We had many fields like:

```
Review Count By Purpose → 135
Review Count By Purpose → 1730
...
```

which we excluded in Admin » Data Model, but one last field "Review Count By Purpose →" is left and can't be excluded. We have to manually deselect this in the question every time, which is not ideal.

### Environment
Metabase version: 0.46.6.4
Database: MySQL 8.0.26
Deployment: GKE

### To Reproduce

1. Go to 'Question'.
2. Click on the affected 'Database'.
3. Select the affected 'Products'.
4. An error is thrown unless the "Review Count By Purpose →" json field is explicitly de-selected.

### Expected behavior

We expect the table to be queried without any errors, with the JSON fields properly parsed and displayed, even if the "Review Count By Purpose →" json field is not explicitly de-selected.

### Logs
```
[c11446e1-b8c3-4877-aed0-46824efe2110] 2023-08-03T17:01:08+02:00 INFO metabase.query-processor.middleware.cache Query took 29.1 s to run; minimum for cache eligibility is 60.0 s
[c11446e1-b8c3-4877-aed0-46824efe2110] 2023-08-03T17:01:09+02:00 DEBUG metabase.server.middleware.log POST /api/dashboard/108/dashcard/1322/card/1578/query 202 [ASYNC: completed] 29.7 s (21 DB calls) App DB connections: 2/15 Jetty threads: 3/50 (38 idle, 0 queued) (215 total active threads) Queries in flight: 3 (0 queued); mysql DB 2 connections: 4/13 (0 threads blocked)
[c11446e1-b8c3-4877-aed0-46824efe2110] 2023-08-03T17:01:13+02:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: Input to store-field! does not match schema: 

	   [(named {:nfc_path [nil (not ("Non-blank string" ""))]} field)]  


{:database_id 8,
 :started_at #t "2023-08-03T15:01:13.120163Z[UTC]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error resolving Fields in query: Input to store-field! does not match schema: \n\n\t   [(named {:nfc_path [nil (not (\"Non-blank string\" \"\"))]} field)]  \n\n",
   :stacktrace
   ["--> query_processor.middleware.resolve_fields$resolve_fields.invokeStatic(resolve_fields.clj:26)"
    "query_processor.middleware.resolve_fields$resolve_fields.invoke(resolve_fields.clj:16)"
    "query_processor$preprocess_STAR_$fn__70750.invoke(query_processor.clj:158)"
    "query_processor$preprocess_STAR_.invokeStatic(query_processor.clj:156)"
    "query_processor$preprocess_STAR_.invoke(query_processor.clj:151)"
    "query_processor$fn__70758$combined_pre_process__70759$combined_pre_process_STAR___70760.invoke(query_processor.clj:240)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__69150$fn__69155.invoke(resolve_database_and_driver.clj:36)"
    "driver$do_with_driver.invokeStatic(driver.clj:92)"
    "driver$do_with_driver.invoke(driver.clj:88)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__69150.invoke(resolve_database_and_driver.clj:35)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__65021.invoke(fetch_source_query.clj:316)"
    "query_processor.middleware.store$initialize_store$fn__65199$fn__65200.invoke(store.clj:12)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:47)"
    "query_processor.store$do_with_store.invoke(store.clj:41)"
    "query_processor.middleware.store$initialize_store$fn__65199.invoke(store.clj:11)"
    "query_processor.middleware.normalize_query$normalize$fn__69439.invoke(normalize_query.clj:25)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__66377.invoke(constraints.clj:54)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__69375.invoke(process_userland_query.clj:151)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__69752.invoke(catch_exceptions.clj:171)"
    "query_processor.reducible$async_qp$qp_STAR___59520$thunk__59522.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___59520.invoke(reducible.clj:109)"
    "query_processor.reducible$async_qp$qp_STAR___59520.invoke(reducible.clj:94)"
    "query_processor.reducible$sync_qp$qp_STAR___59532.doInvoke(reducible.clj:129)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:366)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:362)"
    "query_processor$fn__70807$process_query_and_save_execution_BANG___70816$fn__70819.invoke(query_processor.clj:377)"
    "query_processor$fn__70807$process_query_and_save_execution_BANG___70816.invoke(query_processor.clj:370)"
    "query_processor$fn__70852$process_query_and_save_with_max_results_constraints_BANG___70861$fn__70864.invoke(query_processor.clj:389)"
    "query_processor$fn__70852$process_query_and_save_with_max_results_constraints_BANG___70861.invoke(query_processor.clj:382)"
    "api.dataset$run_query_async$fn__86959.invoke(dataset.clj:73)"
    "query_processor.streaming$streaming_response_STAR_$fn__54383$fn__54384.invoke(streaming.clj:166)"
    "query_processor.streaming$streaming_response_STAR_$fn__54383.invoke(streaming.clj:165)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
    "async.streaming_response$do_f_async$task__36968.invoke(streaming_response.clj:88)"],
   :error_type :qp,
   :ex-data
   {:field-ids
    #{11601
      6629
      10793
      6807
      8685
      10949
      6356
      6353
      11604
      11515
      6625
      6357
      10950
      10708
      10866
      6360
      6823
      11605
      10862
      11183
      10710
      6361
      7985
      11514
      11184
      6824
      11343
      6783
      10995
      10508
      11603
      10794
      11738
      10861
      6351
      11606
      6355
      10712
      6784
      6624
      11608
      6359
      10863
      6358
      10864
      6811
      6354
      11616
      11607
      10996
      6352
      6822
      11602
      10714
      10795
      10759
      6362
      10709
      10865
      10711
      6785
      6685
      10860},
    :query
    {:database 8,
     :query
     {:source-table 812,
      :fields
      [[:field 6352 nil]
       [:field 6358 {:temporal-unit :default}]
       [:field 6353 nil]
       [:field 6359 nil]
       [:field 6361 nil]
       [:field 6360 nil]
       [:field 6362 nil]
       [:field 11738 nil]
       [:field 6355 nil]
       [:field 6351 nil]
       [:field 6357 nil]
       [:field 6354 {:temporal-unit :default}]
       [:field 6356 nil]
       [:field 6624 nil]
       [:field 6625 nil]
       [:field 6629 nil]
       [:field 6685 nil]
       [:field 10795 nil]
       [:field 10793 nil]
       [:field 6784 nil]
       [:field 6785 nil]
       [:field 6783 nil]
       [:field 6807 nil]
       [:field 6811 nil]
       [:field 6824 nil]
       [:field 6823 nil]
       [:field 6822 nil]
       [:field 7985 nil]
       [:field 8685 {:temporal-unit :default}]
       [:field 11343 nil]
       [:field 10508 nil]
       [:field 10708 nil]
       [:field 10710 nil]
       [:field 11616 nil]
       [:field 10709 nil]
       [:field 10711 nil]
       [:field 10712 nil]
       [:field 10714 nil]
       [:field 10759 {:temporal-unit :default}]
       [:field 10794 nil]
       [:field 10863 nil]
       [:field 10860 nil]
       [:field 10861 nil]
       [:field 10866 nil]
       [:field 10865 nil]
       [:field 10864 nil]
       [:field 10862 nil]
       [:field 10949 nil]
       [:field 10950 nil]
       [:field 10995 nil]
       [:field 10996 nil]
       [:field 11183 nil]
       [:field 11514 nil]
       [:field 11184 nil]
       [:field 11515 {:temporal-unit :default}]
       [:field 11605 nil]
       [:field 11601 nil]
       [:field 11602 nil]
       [:field 11608 nil]
       [:field 11607 nil]
       [:field 11604 nil]
       [:field 11603 nil]
       [:field 11606 nil]]},
     :type :query,
     :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
     :info
     {:executed-by 55,
      :context :ad-hoc,
      :query-hash
      [115, 114, 99, 61, -53, -21, -4, 72, -127, -117, -101, 45, 66, 5, 109, -106, -1, -70, -125, 20, 115, 52, 87, 95,
       14, -74, 52, 18, 100, -58, 109, -47]},
     :constraints {:max-results 10000, :max-results-bare-rows 2000}},
    :type :qp}}],
 :error_type :invalid-query,
 :json_query
 {:database 8,
  :query {:source-table 812},
  :type "query",
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native nil,
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> query_processor.store$fn__53075$store_field_BANG___53080.invoke(store.clj:146)"
  "query_processor.store$fn__53186$fetch_and_store_fields_BANG___53191$fn__53192.invoke(store.clj:229)"
  "query_processor.store$fn__53186$fetch_and_store_fields_BANG___53191.invoke(store.clj:203)"
  "query_processor.middleware.resolve_fields$resolve_fields_with_ids_BANG_.invokeStatic(resolve_fields.clj:12)"
  "query_processor.middleware.resolve_fields$resolve_fields_with_ids_BANG_.invoke(resolve_fields.clj:10)"
  "query_processor.middleware.resolve_fields$resolve_fields.invokeStatic(resolve_fields.clj:24)"
  "query_processor.middleware.resolve_fields$resolve_fields.invoke(resolve_fields.clj:16)"
  "query_processor$preprocess_STAR_$fn__70750.invoke(query_processor.clj:158)"
  "query_processor$preprocess_STAR_.invokeStatic(query_processor.clj:156)"
  "query_processor$preprocess_STAR_.invoke(query_processor.clj:151)"
  "query_processor$fn__70758$combined_pre_process__70759$combined_pre_process_STAR___70760.invoke(query_processor.clj:240)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__69150$fn__69155.invoke(resolve_database_and_driver.clj:36)"
  "driver$do_with_driver.invokeStatic(driver.clj:92)"
  "driver$do_with_driver.invoke(driver.clj:88)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__69150.invoke(resolve_database_and_driver.clj:35)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__65021.invoke(fetch_source_query.clj:316)"
  "query_processor.middleware.store$initialize_store$fn__65199$fn__65200.invoke(store.clj:12)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:47)"
  "query_processor.store$do_with_store.invoke(store.clj:41)"
  "query_processor.middleware.store$initialize_store$fn__65199.invoke(store.clj:11)"
  "query_processor.middleware.normalize_query$normalize$fn__69439.invoke(normalize_query.clj:25)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__66377.invoke(constraints.clj:54)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__69375.invoke(process_userland_query.clj:151)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__69752.invoke(catch_exceptions.clj:171)"
  "query_processor.reducible$async_qp$qp_STAR___59520$thunk__59522.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___59520.invoke(reducible.clj:109)"
  "query_processor.reducible$async_qp$qp_STAR___59520.invoke(reducible.clj:94)"
  "query_processor.reducible$sync_qp$qp_STAR___59532.doInvoke(reducible.clj:129)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:366)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:362)"
  "query_processor$fn__70807$process_query_and_save_execution_BANG___70816$fn__70819.invoke(query_processor.clj:377)"
  "query_processor$fn__70807$process_query_and_save_execution_BANG___70816.invoke(query_processor.clj:370)"
  "query_processor$fn__70852$process_query_and_save_with_max_results_constraints_BANG___70861$fn__70864.invoke(query_processor.clj:389)"
  "query_processor$fn__70852$process_query_and_save_with_max_results_constraints_BANG___70861.invoke(query_processor.clj:382)"
  "api.dataset$run_query_async$fn__86959.invoke(dataset.clj:73)"
  "query_processor.streaming$streaming_response_STAR_$fn__54383$fn__54384.invoke(streaming.clj:166)"
  "query_processor.streaming$streaming_response_STAR_$fn__54383.invoke(streaming.clj:165)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
  "async.streaming_response$do_f_async$task__36968.invoke(streaming_response.clj:88)"],
 :card_id nil,
 :context :ad-hoc,
 :error
 "Input to store-field! does not match schema: \n\n\t   [(named {:nfc_path [nil (not (\"Non-blank string\" \"\"))]} field)]  \n\n",
 :row_count 0,
 :running_time 0,
 :preprocessed nil,
 :ex-data
 {:type :schema.core/error,
  :value
  [(toucan2.instance/instance
    :metabase.models.field/Field
    {:description nil,
     :database_type "bigint",
     :semantic_type nil,
     :table_id 812,
     :coercion_strategy nil,
     :name "review_count_by_purpose → ",
     :settings nil,
     :effective_type :type/Integer,
     :nfc_path ("review_count_by_purpose" ""),
     :parent_id nil,
     :id 11738,
     :visibility_type :normal,
     :display_name "Review Count By Purpose →",
     :fingerprint nil,
     :base_type :type/Integer})],
  :error [(named {:nfc_path [nil (not ("Non-blank string" ""))]} field)]},
 :data {:rows [], :cols []}}

[c11446e1-b8c3-4877-aed0-46824efe2110] 2023-08-03T17:01:13+02:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 219.1 ms (19 DB calls) App DB connections: 2/15 Jetty threads: 3/50 (38 idle, 0 queued) (215 total active threads) Queries in flight: 3 (0 queued)
[c11446e1-b8c3-4877-aed0-46824efe2110] 2023-08-03T17:01:14+02:00 INFO metabase.server.middleware.exceptions Request canceled before finishing.
[c11446e1-b8c3-4877-aed0-46824efe2110] 2023-08-03T17:01:15+02:00 DEBUG metabase.server.middleware.log PUT /api/field/11738 400 719.9 µs (0 DB calls) 
{:errors {:nfc_path "value may be nil, or if non-nil, value must be an array. Each value must be a non-blank string."}}
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8",
    "os.name": "Linux",
    "os.version": "5.10.162+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.26-google"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-07-28",
      "tag": "v0.46.6.4",
      "branch": "release-x.46.6.x",
      "hash": "7c60aca"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

### Severity

This issue is blocking some users sometimes.

### Additional context

Similar issue reported: [#29407](https://github.com/metabase/metabase/issues/29407)

**Comment by paoliniluis** [comment] 2023-08-04 18:33
duplicate of https://github.com/metabase/metabase/issues/29407

**Closed by paoliniluis** 2023-08-04 18:33 UTC
Labels: Type:Bug, .Needs Triage
