### ISSUE TITLE
Metabase unable to create own application tables in a schema other than `public` on startup. Migrations fail.

### ISSUE THREAD

**Issue by maxmarcon** [metabase/metabase#46646] opened 2024-08-08 15:09 UTC
### Describe the bug

Hello. We've been using metabase version `0.46.8` on PostgeSQL for some time. The important point here is that we want metabase to create its application tables on startup in a schema called `metabase` (i.e. **not** in the `public` schema).

We were able to achieve that by setting the following env var:

```
MB_DB_CONNECTION_URI=jdbc:postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE}?options=-csearch_path%3Dmetabase
```

Then, all of metbases' application tables would be created in the metabase schema. Great!

However, recently we moved to `0.50.9` and this stopped working.

When starting with an empty metabase schema, what  happen is that metabase creates some tables, like:

  * action
  * databasechangelog
  * databasechangeloglock
 
in the correct `metabase` schema, but also creates some other tables in the `public` schema. Eventually, the intialization process fails with errors like this one:

```
Caused by: liquibase.exception.DatabaseException: ERROR: relation "metabase.report_card" does not exist [Failed SQL: (0) CREATE TABLE "metabase"."query_action" ("action_id" INTEGER NOT NULL, "card_id" INTEGER NOT NULL, CONSTRAINT "fk_query_action_ref_action_id" FOREIGN KEY ("action_id") REFERENCES "metabase"."action"("id") ON DELETE CASCADE, CONSTRAINT "fk_query_action_ref_card_id" FOREIGN KEY ("card_id") REFERENCES "metabase"."report_card"("id") ON DELETE CASCADE)]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179)
        at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141)
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1285)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:755)
        ... 81 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "metabase.report_card" does not exist
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)
        at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464)
        ... 86 more
```

where a migration tries to create a table `metabase.query_action` in the right schema, but that table references a table (`metabase.report_card`) that doesn't exist. Well, it actually does exist, but in the wrong schema (i.e. `public`) so the migration fails.

This seems to be an issue caused by the migration code ignoring the target schema for some migrations.
We also tried the latest version at the time of writing (0.50.19) and the problem was still there

### To Reproduce

1. Create a schema `metabase` in your postgres database, and grant all permissions on it to your database user 
2. export MB_DB_CONNECTION_URI=jdbc:postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE}?options=-csearch_path%3Dmetabase
3. java -jar metabase.jar 

### Expected behavior

The migrations should run successfully, and all of metbases' own tables should be created in the `metabase` schema

### Logs

2024-08-08 17:04:15,004 INFO metabase.util :: Maximum memory available to JVM: 8,0 GB
2024-08-08 17:04:16,008 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓 
 For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
2024-08-08 17:04:18,374 INFO driver.impl :: [34mRegistered abstract driver :sql[0m  🚚
2024-08-08 17:04:18,389 INFO driver.impl :: [34mRegistered abstract driver :sql-jdbc[0m (parents: [:sql]) 🚚
2024-08-08 17:04:18,392 INFO metabase.util :: [32mLoad driver :sql-jdbc took 4,9 ms[0m
2024-08-08 17:04:18,392 INFO driver.impl :: [34mRegistered driver :h2[0m (parents: [:sql-jdbc]) 🚚
2024-08-08 17:04:18,462 INFO driver.impl :: [34mRegistered driver :mysql[0m (parents: [:sql-jdbc]) 🚚
2024-08-08 17:04:18,475 INFO driver.impl :: [34mRegistered driver :postgres[0m (parents: [:sql-jdbc]) 🚚
2024-08-08 17:04:19,205 INFO metabase.core :: 
Metabase v0.50.19 (0b97bf8) 

Copyright © 2024 Metabase, Inc. 

Metabase Enterprise Edition extensions are NOT PRESENT.
2024-08-08 17:04:19,209 INFO metabase.core :: Starting Metabase in STANDALONE mode
2024-08-08 17:04:19,228 INFO metabase.server :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

2024-08-08 17:04:19,251 INFO metabase.core :: Starting Metabase version v0.50.19 (0b97bf8) ...
2024-08-08 17:04:19,253 INFO metabase.core :: System info:
 {"file.encoding" "UTF-8",
 "java.runtime.name" "OpenJDK Runtime Environment",
 "java.runtime.version" "22.0.2",
 "java.vendor" "Homebrew",
 "java.vendor.url" "https://github.com/Homebrew/homebrew-core/issues",
 "java.version" "22.0.2",
 "java.vm.name" "OpenJDK 64-Bit Server VM",
 "java.vm.version" "22.0.2",
 "os.name" "Mac OS X",
 "os.version" "14.6",
 "user.language" "en",
 "user.timezone" "Europe/Berlin"}

2024-08-08 17:04:19,255 INFO metabase.plugins :: Loading plugins in /Users/mmarcon/tb-ii/plugins...
2024-08-08 17:04:19,444 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :bigquery-cloud-sdk...[0m
2024-08-08 17:04:19,444 INFO driver.impl :: [34mRegistered driver :bigquery-cloud-sdk[0m (parents: [:sql]) 🚚
2024-08-08 17:04:19,466 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :snowflake...[0m
2024-08-08 17:04:19,466 INFO driver.impl :: [34mRegistered driver :snowflake[0m (parents: [:sql-jdbc]) 🚚
2024-08-08 17:04:19,470 INFO plugins.dependencies :: [31mMetabase cannot initialize plugin Metabase Oracle Driver due to required dependencies.[0m Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.

2024-08-08 17:04:19,471 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
2024-08-08 17:04:19,471 INFO plugins.dependencies :: [33mPlugins with unsatisfied deps: ["Metabase Oracle Driver"][0m
2024-08-08 17:04:19,475 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :mongo...[0m
2024-08-08 17:04:19,475 INFO driver.impl :: [34mRegistered driver :mongo[0m  🚚
2024-08-08 17:04:19,477 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :druid...[0m
2024-08-08 17:04:19,477 INFO driver.impl :: [34mRegistered driver :druid[0m  🚚
2024-08-08 17:04:19,481 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :redshift...[0m
2024-08-08 17:04:19,481 INFO driver.impl :: [34mRegistered driver :redshift[0m (parents: [:postgres]) 🚚
2024-08-08 17:04:19,483 INFO plugins.dependencies :: [31mMetabase cannot initialize plugin Metabase Vertica Driver due to required dependencies.[0m Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.

2024-08-08 17:04:19,483 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
2024-08-08 17:04:19,483 INFO plugins.dependencies :: [33mPlugins with unsatisfied deps: ["Metabase Vertica Driver" "Metabase Oracle Driver"][0m
2024-08-08 17:04:19,484 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :sqlite...[0m
2024-08-08 17:04:19,485 INFO driver.impl :: [34mRegistered driver :sqlite[0m (parents: [:sql-jdbc]) 🚚
2024-08-08 17:04:19,489 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :presto-jdbc...[0m
2024-08-08 17:04:19,489 INFO driver.impl :: [34mRegistered driver :presto-jdbc[0m (parents: [:sql-jdbc]) 🚚
2024-08-08 17:04:19,492 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :druid-jdbc...[0m
2024-08-08 17:04:19,492 INFO driver.impl :: [34mRegistered driver :druid-jdbc[0m (parents: [:sql-jdbc]) 🚚
2024-08-08 17:04:19,493 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :sqlserver...[0m
2024-08-08 17:04:19,494 INFO driver.impl :: [34mRegistered driver :sqlserver[0m (parents: [:sql-jdbc]) 🚚
2024-08-08 17:04:19,506 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :athena...[0m
2024-08-08 17:04:19,506 INFO driver.impl :: [34mRegistered driver :athena[0m (parents: [:sql-jdbc]) 🚚
2024-08-08 17:04:19,509 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :hive-like...[0m
2024-08-08 17:04:19,510 INFO driver.impl :: [34mRegistered abstract driver :hive-like[0m (parents: [:sql-jdbc]) 🚚
2024-08-08 17:04:19,510 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :sparksql...[0m
2024-08-08 17:04:19,510 INFO driver.impl :: [34mRegistered driver :sparksql[0m (parents: [:hive-like]) 🚚
2024-08-08 17:04:19,512 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
2024-08-08 17:04:19,512 INFO db.setup :: [36mVerifying postgres Database Connection ...[0m
2024-08-08 17:04:19,699 INFO db.setup :: Successfully verified PostgreSQL 16.2 application database connection. ✅
2024-08-08 17:04:19,699 INFO db.setup :: [36mChecking if a database downgrade is required...[0m
2024-08-08 17:04:20,031 INFO db.setup :: Running Database Migrations...
2024-08-08 17:04:20,032 INFO db.setup :: Setting up Liquibase...
2024-08-08 17:04:20,142 INFO db.liquibase :: Updating liquibase table to reflect consolidated changeset filenames
2024-08-08 17:04:20,152 INFO db.liquibase :: No migration lock found.
2024-08-08 17:04:20,152 INFO db.liquibase :: Migration lock acquired.
2024-08-08 17:04:20,163 INFO db.setup :: Liquibase is ready.
2024-08-08 17:04:20,163 INFO db.liquibase :: Checking if Database has unrun migrations...
2024-08-08 17:04:20,393 INFO db.liquibase :: Database has unrun migrations. Checking if migration lock is taken...
2024-08-08 17:04:20,407 INFO db.liquibase :: No migration lock found.
2024-08-08 17:04:20,407 INFO db.liquibase :: Migration lock acquired.
2024-08-08 17:04:20,528 INFO db.liquibase :: Running 352 migrations ...
2024-08-08 17:04:21,439 ERROR liquibase.changelog :: ChangeSet migrations/001_update_migrations.yaml::v45.00-002::snoe encountered an exception.
liquibase.exception.DatabaseException: ERROR: relation "metabase.report_card" does not exist [Failed SQL: (0) CREATE TABLE "metabase"."query_action" ("action_id" INTEGER NOT NULL, "card_id" INTEGER NOT NULL, CONSTRAINT "fk_query_action_ref_card_id" FOREIGN KEY ("card_id") REFERENCES "metabase"."report_card"("id") ON DELETE CASCADE, CONSTRAINT "fk_query_action_ref_action_id" FOREIGN KEY ("action_id") REFERENCES "metabase"."action"("id") ON DELETE CASCADE)]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179)
	at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1285)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:755)
	at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:133)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:122)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.Scope.child(Scope.java:252)
	at liquibase.Scope.child(Scope.java:256)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:89)
	at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:110)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:108)
	at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105)
	at liquibase.command.CommandScope.execute(CommandScope.java:217)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:245)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.Liquibase.runInScope(Liquibase.java:1419)
	at liquibase.Liquibase.update(Liquibase.java:234)
	at liquibase.Liquibase.update(Liquibase.java:212)
	at liquibase.Liquibase.update(Liquibase.java:194)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__44437.invoke(liquibase.clj:360)
	at metabase.db.liquibase$run_in_scope_locked$reify__44433.run(liquibase.clj:325)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at metabase.db.liquibase$run_in_scope_locked.invokeStatic(liquibase.clj:318)
	at metabase.db.liquibase$run_in_scope_locked.invoke(liquibase.clj:301)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:349)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:342)
	at metabase.db.setup$migrate_BANG_$fn__53373.invoke(setup.clj:84)
	at metabase.db.liquibase$do_with_liquibase$f_STAR___44374.invoke(liquibase.clj:140)
	at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:143)
	at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:131)
	at metabase.db.setup$migrate_BANG_.invokeStatic(setup.clj:73)
	at metabase.db.setup$migrate_BANG_.doInvoke(setup.clj:55)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at metabase.db.setup$run_schema_migrations_BANG_.invokeStatic(setup.clj:149)
	at metabase.db.setup$run_schema_migrations_BANG_.invoke(setup.clj:144)
	at metabase.db.setup$setup_db_BANG_$fn__53401$fn__53402.invoke(setup.clj:167)
	at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
	at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
	at metabase.db.setup$setup_db_BANG_$fn__53401.invoke(setup.clj:161)
	at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:160)
	at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:153)
	at metabase.db$setup_db_BANG_$fn__53426.invoke(db.clj:86)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:81)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:68)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:117)
	at metabase.core$init_BANG__STAR_.invoke(core.clj:98)
	at metabase.core$init_BANG_.invokeStatic(core.clj:170)
	at metabase.core$init_BANG_.invoke(core.clj:165)
	at metabase.core$start_normally.invokeStatic(core.clj:182)
	at metabase.core$start_normally.invoke(core.clj:176)
	at metabase.core$entrypoint.invokeStatic(core.clj:215)
	at metabase.core$entrypoint.doInvoke(core.clj:209)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.bootstrap.main(Unknown Source)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "metabase.report_card" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464)
	... 86 more

UPDATE SUMMARY
Run:                        352
Previously run:               0
Filtered out:                50
-------------------------------
Total change sets:          402

FILTERED CHANGE SETS SUMMARY
DBMS mismatch:               50

2024-08-08 17:04:21,477 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v45.00-002::snoe:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "metabase.report_card" does not exist [Failed SQL: (0) CREATE TABLE "metabase"."query_action" ("action_id" INTEGER NOT NULL, "card_id" INTEGER NOT NULL, CONSTRAINT "fk_query_action_ref_card_id" FOREIGN KEY ("card_id") REFERENCES "metabase"."report_card"("id") ON DELETE CASCADE, CONSTRAINT "fk_query_action_ref_action_id" FOREIGN KEY ("action_id") REFERENCES "metabase"."action"("id") ON DELETE CASCADE)]
	at liquibase.command.CommandScope.execute(CommandScope.java:253)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:245)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.Liquibase.runInScope(Liquibase.java:1419)
	at liquibase.Liquibase.update(Liquibase.java:234)
	at liquibase.Liquibase.update(Liquibase.java:212)
	at liquibase.Liquibase.update(Liquibase.java:194)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__44437.invoke(liquibase.clj:360)
	at metabase.db.liquibase$run_in_scope_locked$reify__44433.run(liquibase.clj:325)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at metabase.db.liquibase$run_in_scope_locked.invokeStatic(liquibase.clj:318)
	at metabase.db.liquibase$run_in_scope_locked.invoke(liquibase.clj:301)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:349)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:342)
	at metabase.db.setup$migrate_BANG_$fn__53373.invoke(setup.clj:84)
	at metabase.db.liquibase$do_with_liquibase$f_STAR___44374.invoke(liquibase.clj:140)
	at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:143)
	at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:131)
	at metabase.db.setup$migrate_BANG_.invokeStatic(setup.clj:73)
	at metabase.db.setup$migrate_BANG_.doInvoke(setup.clj:55)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at metabase.db.setup$run_schema_migrations_BANG_.invokeStatic(setup.clj:149)
	at metabase.db.setup$run_schema_migrations_BANG_.invoke(setup.clj:144)
	at metabase.db.setup$setup_db_BANG_$fn__53401$fn__53402.invoke(setup.clj:167)
	at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
	at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
	at metabase.db.setup$setup_db_BANG_$fn__53401.invoke(setup.clj:161)
	at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:160)
	at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:153)
	at metabase.db$setup_db_BANG_$fn__53426.invoke(db.clj:86)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:81)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:68)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:117)
	at metabase.core$init_BANG__STAR_.invoke(core.clj:98)
	at metabase.core$init_BANG_.invokeStatic(core.clj:170)
	at metabase.core$init_BANG_.invoke(core.clj:165)
	at metabase.core$start_normally.invokeStatic(core.clj:182)
	at metabase.core$start_normally.invoke(core.clj:176)
	at metabase.core$entrypoint.invokeStatic(core.clj:215)
	at metabase.core$entrypoint.doInvoke(core.clj:209)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.bootstrap.main(Unknown Source)
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v45.00-002::snoe:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "metabase.report_card" does not exist [Failed SQL: (0) CREATE TABLE "metabase"."query_action" ("action_id" INTEGER NOT NULL, "card_id" INTEGER NOT NULL, CONSTRAINT "fk_query_action_ref_card_id" FOREIGN KEY ("card_id") REFERENCES "metabase"."report_card"("id") ON DELETE CASCADE, CONSTRAINT "fk_query_action_ref_action_id" FOREIGN KEY ("action_id") REFERENCES "metabase"."action"("id") ON DELETE CASCADE)]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:151)
	at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:110)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:108)
	at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105)
	at liquibase.command.CommandScope.execute(CommandScope.java:217)
	... 58 more
Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v45.00-002::snoe:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "metabase.report_card" does not exist [Failed SQL: (0) CREATE TABLE "metabase"."query_action" ("action_id" INTEGER NOT NULL, "card_id" INTEGER NOT NULL, CONSTRAINT "fk_query_action_ref_card_id" FOREIGN KEY ("card_id") REFERENCES "metabase"."report_card"("id") ON DELETE CASCADE, CONSTRAINT "fk_query_action_ref_action_id" FOREIGN KEY ("action_id") REFERENCES "metabase"."action"("id") ON DELETE CASCADE)]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:797)
	at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:133)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:122)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.Scope.child(Scope.java:252)
	at liquibase.Scope.child(Scope.java:256)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:89)
	... 66 more
Caused by: liquibase.exception.DatabaseException: ERROR: relation "metabase.report_card" does not exist [Failed SQL: (0) CREATE TABLE "metabase"."query_action" ("action_id" INTEGER NOT NULL, "card_id" INTEGER NOT NULL, CONSTRAINT "fk_query_action_ref_card_id" FOREIGN KEY ("card_id") REFERENCES "metabase"."report_card"("id") ON DELETE CASCADE, CONSTRAINT "fk_query_action_ref_action_id" FOREIGN KEY ("action_id") REFERENCES "metabase"."action"("id") ON DELETE CASCADE)]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179)
	at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1285)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:755)
	... 81 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "metabase.report_card" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464)
	... 86 more
2024-08-08 17:04:21,479 INFO metabase.core :: Metabase Shutting Down ...
2024-08-08 17:04:21,479 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
2024-08-08 17:04:21,483 WARN db.liquibase :: ()
2024-08-08 17:04:21,483 INFO metabase.core :: Metabase Shutdown COMPLETE

### Information about your Metabase installation

```JSON
- Metabase versions: 0.50.9 and 0.50.19
- Hosting environment: Docker and MacOS
- Database: PostgreSQL
```

### Severity

Severe, it's preventing metabase from initializing a new database

**Comment by paoliniluis** [comment] 2024-08-08 16:09
dupe of https://github.com/metabase/metabase/issues/37836

**Closed by paoliniluis** 2024-08-08 16:09 UTC
Labels: Type:Bug, .Needs Triage
