### ISSUE TITLE
Changing the language doesn't translate the "from now" in Date Filters

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#27912] opened 2023-01-27 09:28 UTC
**Describe the bug**
In the screenshot below, you can read "giornoi from now", "settimane from now" etc. "from now" is not translated in Italian. This happens in every language

<img width="805" alt="image" src="https://user-images.githubusercontent.com/110378427/215047496-74a40061-2e9a-4613-9f50-9fde72065d27.png">

**To Reproduce**
1. Go to Account Settings -> Change Language (any language you understand except for English) -> Update
2. Click on New -> Dashboard -> Add Date Filter -> All Options -> Save
3. Click on Filter -> Relative Dates -> Next -> Starting From -> Notice lack of translation

<img width="805" alt="image" src="https://user-images.githubusercontent.com/110378427/215047496-74a40061-2e9a-4613-9f50-9fde72065d27.png">

**Expected behavior**
I expect language to be translated at Date Filter level as well

**Information about your Metabase Installation:**
Replicated on 45.2 and Master

**Comment by paoliniluis** [comment] 2023-01-27 20:27
Dupe of https://github.com/metabase/metabase/issues/24624

**Closed by paoliniluis** 2023-01-27 20:27 UTC
Labels: Type:Bug, Customization/i18n
