### ISSUE TITLE
Feature request: Display/Access generated query

### ISSUE THREAD

**Issue by stringbeans** [metabase/metabase#10145] opened 2019-06-12 21:44 UTC
### Feature request

It would be amazing if there was a way to display the generated queries for reports (both custom and native). I'd love to use it for debugging purposes but also to tweak in native queries  (for example, start with a custom query and then tweak it after in a native sql query)

**Comment by flamber** [comment] 2019-06-12 21:50
Hi @stringbeans This is a duplicate of #6096

**Comment by mazameli** [comment] 2019-06-12 21:56
For custom queries, there is already a View-the-SQL button which opens a modal and gives you an option to bring it over to the SQL editor:

![image](https://user-images.githubusercontent.com/2223916/59389006-1dceb000-8d22-11e9-8854-8e76aaac3bde.png)

![image](https://user-images.githubusercontent.com/2223916/59389015-232bfa80-8d22-11e9-88d4-ce6f00c88cd8.png)

**Closed by mazameli** 2019-06-12 21:56 UTC
Labels: Duplicate

**Comment by stringbeans** [comment] 2019-06-12 22:01
@mazameli thanks! i actually never noticed that and nothing turned up after a quick search.

ive found the documentation for "field filters" variables is very lacking and doesnt provide good examples... being able to see the generated query for native queries would be VERY useful!

**Comment by mazameli** [comment] 2019-06-12 22:15
Thanks for the feedback, @stringbeans. Was or is there anything specific about trying to use or set up field filters that particularly confused you? Any concrete examples or explanations you wish were in the documentation?

**Comment by stringbeans** [comment] 2019-06-13 00:21
@mazameli thanks for the response!

so im looking to do something like this in a native query (this is simplified):

```
select *
from student
where student_type_id = {{studentTypeId}}
```

and i was looking to use the field filter to display a user friendly list of "student types" that i have stored in a separate table `student_types` (`student_type_id` is an FK on the student table)

perhaps i dont understand the purpose of field filters, but i was under the impression that this was what the field filter option was meant to address. but its unclear how i do this...

**Comment by flamber** [comment] 2019-06-13 00:40
@stringbeans 
Then you should make the Field Filter lookup on `student_types.name` and your query should be:
```
select *
from student
left join student_types ON student_types.id=student.student_type_id
where {{studentType}}
```
Make sure to check "Filter Type" is one of the [types allowed](https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#the-field-filter-variable-type) for use with Field Filter.
And "Filtering on this field" can either be a list (if you only have few student types) or a search field.
Admin > Data Model > (database) > (table `student_types`) > (column `name`) :gear:
