### ISSUE TITLE
When running ee edition without a token, remove Metabase analytics collection in list

### ISSUE THREAD

**Issue by qwef** [metabase/metabase#35671] opened 2023-11-13 18:16 UTC
https://metaboat.slack.com/archives/C01LQQ2UW03/p1699525120236779

**Comment by WiNloSt** [comment] 2023-11-14 08:05
Ahh I didn't search this before filing the issue, but I include some info there. https://github.com/metabase/metabase/issues/35700

**Comment by WiNloSt** [comment] 2023-11-14 08:06
Duplicate of #35700

**Closed** 2023-11-14 08:06 UTC
Labels: .Team/AdminWebapp
