### ISSUE TITLE
Dashboards containing any question with public link, are visible to people.

### ISSUE THREAD

**Issue by rhnBen** [metabase/metabase#7070] opened 2018-03-04 13:10 UTC
This happens even when they don't have access to the collection of any question on that dashboard
and there's no way to hide it.

**Comment by salsakran** [comment] 2018-03-06 23:46
What version of Metabase are you on? 

Aka can you please fill out the bug report template that is in a new issue?

**Comment by rhnBen** [comment] 2018-03-07 08:32
v: 0.28.1

**Comment by camsaul** [comment] 2018-04-09 21:38
@rhnBen @salsakran this isn't a bug, but a product of the way our permissions for Dashboards work. One is allowed to see a Dashboard if you're allowed to see at least one of the Questions in it (even if all the others are locked). And anyone is allowed to see a public Question.

**Comment by camsaul** [comment] 2018-04-09 21:41
We're planning on changing how permissions work for Dashboards by using Collections to set their permissions. After that change you'll have control over this sort of behavior. I'm going to close this as a duplicate of our tracking issue for our new Dashboards permissions model, #3363

**Comment by salsakran** [comment] 2018-04-09 21:41
I think the main notion is that a card with a public link shouldn't be defined by any public links as far as visibility.

Eg. I have a dashboard. I want to share a single card with a trusted partner, and I create a public link. Having that dashboard suddenly be visible is not what was intended with our visibility rules. I.e. we should ignore public links in deciding dashboard visibility.

But the honest answer is that with the new collections permissions revamp, we should do away with this whole thing.

**Closed by camsaul** 2018-04-09 21:41 UTC
Labels: Bug, Permissions, Priority/P1
