### ISSUE TITLE
Cannot Delete Database from Metabase - ERROR: update or delete on table "report_card" violates foreign key constraint "fk_card_label_ref_card_id" on table "card_label" Detail: Key (id)=(23) is still referenced from table "card_label".

### ISSUE THREAD

**Issue by anazapata** [metabase/metabase#15544] opened 2021-04-09 17:33 UTC
ERROR: update or delete on table "report_card" violates foreign key constraint "fk_card_label_ref_card_id" on table "card_label" Detail: Key (id)=(23) is still referenced from table "card_label".

[2ae8e69b-984c-44ad-b535-b4b4c1e4b285] 2021-04-08T17:05:02-06:00 ERROR metabase.driver.sql-jdbc.execute nil [2ae8e69b-984c-44ad-b535-b4b4c1e4b285] 2021-04-08T17:05:08-06:00 ERROR metabase.driver.sql-jdbc.execute nil [2ae8e69b-984c-44ad-b535-b4b4c1e4b285] 2021-04-08T17:05:08-06:00 ERROR metabase.middleware.log DELETE /api/database/4 500 56.5 ms (9 DB calls) {:message "ERROR: update or delete on table \"report_card\" violates foreign key constraint \"fk_card_label_ref_card_id\" on table \"card_label\"\n Detail: Key (id)=(23) is still referenced from table \"card_label\".", :type org.postgresql.util.PSQLException, :stacktrace

**Comment by flamber** [comment] 2021-04-09 17:45
Duplicate of #8492

**Closed by flamber** 2021-04-09 17:45 UTC
