### ISSUE TITLE
Manual Setup of Foreign Key - Can't search for specific table

### ISSUE THREAD

**Issue by cah-brandon-trebbien** [metabase/metabase#6312] opened 2017-11-01 17:33 UTC
Your browser and the version: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

Your operating system: Windows 10

Your databases: Oracle 12

Metabase version: 0.26.2

Metabase hosting environment: Linux/RHEL 7

Metabase internal database: MySQL 5.7

Repeatable steps to reproduce the issue

1. Go to data model. Find a field which was imported as a category but really is a foreign key. Change the  type to Foreign Key
2. Click on the entry field which now shows. A popup of the first 10ish tables in the schema are shown (of the hundreds available). Cannot see any other potential tables to join to.

**Comment by ywadi** [comment] 2018-03-28 18:44
+1 Having an issue here similar to that using MongoDB. 
No tables to filter from

**Comment by lwqcz** [comment] 2018-08-14 06:51
I have noticed this behaviour just a moment ago (in version 0.30) but did not you noticed that this list of that popup is scrollable to browse all candidates in schema?

_Anyway - I am going to open issue about lack of search bar in this popup, as it will be very handy for large schemas as ours are, counting hundreds of tables._

**Comment by flamber** [comment] 2019-02-22 18:50
Hi @cah-brandon-trebbien 
I cannot reproduce your issue on 0.31.2 with multiple different datasources (MySQL, MariaDB, SQL2008, Postgres, H2).
But due note that for you to be able to select a Foreign Key reference, you have to make sure that the table you're trying to reference has an Entity Key (Primary Key) defined on one field. If your database structure has PK and FK defined, then this should automatically be synchronized by Metabase.

**Comment by flamber** [comment] 2020-06-01 21:54
Closing, since it sounds like it was a request for a searchable foreign key selector, which was introduced in 0.35.0

**Closed by flamber** 2020-06-01 21:54 UTC
Labels: Administration/Data Model, Type:UX
