### ISSUE TITLE
Unable to Generate SQL Query with Contains Function Due to Data Type Mismatch

### ISSUE THREAD

**Issue by MarleTangible** [metabase/metabase#47329] opened 2024-08-27 20:35 UTC
### Describe the bug

I'm creating this issue as an addition to the https://github.com/metabase/metabase/issues/44431

Metabase fails to generate a query when the original schema data type is `type/*` and the contains function is used to filter. The question creation shows the following error:

```
Error generating the query.
```

Error details shows the following output:

```
Invalid query: {:stages [{:filters [[nil nil ["expression returning a string"]]]}]}
```

Please also see the attached log for the error details when the contains function is used for query generation.

A sample question is created:
![image](https://github.com/user-attachments/assets/bd2d24e5-ddab-495d-b6c5-2160654ed692)

A filter is added that uses the contains function on one of the columns:
![image](https://github.com/user-attachments/assets/42c2a3d0-b1a6-4824-a4fc-6d5db9c4609b)

Query generation fails which leads to no results being shown to the user:
![image](https://github.com/user-attachments/assets/8840222d-6d00-43bd-82ee-ba502c87fb4f)

The data type is being recognized as `type/*`:
![image](https://github.com/user-attachments/assets/d389c6a3-e8b0-4bd6-9b55-4af2cecb76c6)

Syncing the database schema, rescanning for values, or changing the type to Entity Name did not resolve the issue. The column is defined as VARCHAR(15).

Please let me know if I can provide any additional information. Thank you.

### To Reproduce

1. Find a table column where the underlying data type is text (e.g. varchar etc.) but recognized as `type/*` by Metabase.
2. Create a new question and select the source table. Open the SQL pane to see the statement created.
3. Add a filter for the selected column and select the contains function with a sample input.
4. SQL generation fails and the SQL pane shows an error.

### Expected behavior

Metabase should allow users to filter by string functions if the underlying data is string.

### Logs

```
2024-08-27 20:21:36,149 ERROR middleware.log :: POST /api/dataset/native 500 19.0 ms (3 DB calls) {:metabase-user-id 1} 
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message
   "Error preprocessing query in metabase.query_processor.preprocess$ensure_pmbql$fn__65774@17953c15: Invalid query: {:stages [{:filters [[nil nil [\"expression returning a string\"]]]}]}",
   :data
   {:fn
    #object[metabase.query_processor.preprocess$ensure_pmbql$fn__65774 0x17953c15 "metabase.query_processor.preprocess$ensure_pmbql$fn__65774@17953c15"],
    :query
    {:lib/type :mbql/query,
     :stages
     [{:lib/type :mbql.stage/mbql,
       :source-table 91,
       :filters
       [[:contains
         {:case-sensitive false, :lib/uuid "f6da5ec1-7d3b-4d06-a88a-134d74a55060"}
         [:field {:base-type :type/*, :lib/uuid "5cdb05f5-9aaf-468b-83ab-841f3c9777d9", :effective-type :type/*} 1372]
         "ABC"]]}],
     :database 2,
     :lib.convert/converted? true,
     :lib/metadata
     (metabase.lib.metadata.invocation-tracker/invocation-tracker-provider (metabase.lib.metadata.cached-provider/cached-metadata-provider (metabase.lib.metadata.jvm/->UncachedApplicationDatabaseMetadataProvider 2)))},
    :type :qp},
   :at [metabase.query_processor.preprocess$preprocess$fn__65778$fn__65779 invoke "preprocess.clj" 133]}
  {:type clojure.lang.ExceptionInfo,
   :message "Invalid query: {:stages [{:filters [[nil nil [\"expression returning a string\"]]]}]}",
   :data
   {:type :invalid-query,
    :error {:stages [{:filters [[nil nil ["expression returning a string"]]]}]},
    :original
    {:schema :metabase.lib.schema/query,
     :value
     {:lib/type :mbql/query,
      :stages
      [{:lib/type :mbql.stage/mbql,
        :source-table 91,
        :filters
        [[:contains
          {:case-sensitive false, :lib/uuid "f6da5ec1-7d3b-4d06-a88a-134d74a55060"}
          [:field {:base-type :type/*, :lib/uuid "5cdb05f5-9aaf-468b-83ab-841f3c9777d9", :effective-type :type/*} 1372]
          "ABC"]]}],
      :database 2,
      :lib.convert/converted? true,
      :lib/metadata
      (metabase.lib.metadata.invocation-tracker/invocation-tracker-provider (metabase.lib.metadata.cached-provider/cached-metadata-provider (metabase.lib.metadata.jvm/->UncachedApplicationDatabaseMetadataProvider 2)))},
     :errors
     ({:path [0 0 :stages 0 0 0 0 1 :mbql.stage/mbql 0 0 :filters 0 0 0 0 0 true 0 :contains 0 0 :args 0 0 1],
       :in [:stages 0 :filters 0 2],
       :schema
       [:fn {:error/message "expression returning a string"} #object[metabase.lib.schema.expression$expression_schema$fn__14627 0x6a188d9b "metabase.lib.schema.expression$expression_schema$fn__14627@6a188d9b"]],
       :value
       [:field
        {:base-type :type/*, :lib/uuid "5cdb05f5-9aaf-468b-83ab-841f3c9777d9", :effective-type :type/*}
        1372]})}},
   :at [metabase.query_processor.middleware.validate$validate_query invokeStatic "validate.clj" 16]}],
 :trace
 [[metabase.query_processor.middleware.validate$validate_query invokeStatic "validate.clj" 16]
  [metabase.query_processor.middleware.validate$validate_query invoke "validate.clj" 10]
  [clojure.lang.Var invoke "Var.java" 384]
  [metabase.query_processor.preprocess$ensure_pmbql$fn__65774 invoke "preprocess.clj" 68]
  [metabase.query_processor.preprocess$preprocess$fn__65778$fn__65779 invoke "preprocess.clj" 128]
  [clojure.lang.PersistentVector reduce "PersistentVector.java" 343]
  [clojure.core$transduce invokeStatic "core.clj" 6947]
  [clojure.core$transduce invoke "core.clj" 6934]
  [metabase.query_processor.preprocess$preprocess$fn__65778 invoke "preprocess.clj" 119]
  [metabase.query_processor.setup$do_with_qp_setup invokeStatic "setup.clj" 225]
  [metabase.query_processor.setup$do_with_qp_setup invoke "setup.clj" 216]
  [metabase.query_processor.preprocess$preprocess invokeStatic "preprocess.clj" 118]
  [metabase.query_processor.preprocess$preprocess invoke "preprocess.clj" 114]
  [metabase.query_processor.compile$compile$fn__66464 invoke "compile.clj" 33]
  [metabase.query_processor.setup$do_with_qp_setup invokeStatic "setup.clj" 225]
  [metabase.query_processor.setup$do_with_qp_setup invoke "setup.clj" 216]
  [metabase.query_processor.compile$compile invokeStatic "compile.clj" 32]
  [metabase.query_processor.compile$compile invoke "compile.clj" 29]
  [metabase.query_processor.compile$compile_and_splice_parameters$fn__66469 invoke "compile.clj" 54]
  [metabase.query_processor.setup$do_with_canceled_chan$fn__65263 invoke "setup.clj" 189]
  [metabase.query_processor.setup$do_with_database_local_settings$fn__65258 invoke "setup.clj" 181]
  [metabase.query_processor.setup$do_with_driver$fn__65253$fn__65254 invoke "setup.clj" 166]
  [metabase.driver$do_with_driver invokeStatic "driver.clj" 105]
  [metabase.driver$do_with_driver invoke "driver.clj" 100]
  [metabase.query_processor.setup$do_with_driver$fn__65253 invoke "setup.clj" 165]
  [metabase.query_processor.setup$do_with_metadata_provider$fn__65246$fn__65249 invoke "setup.clj" 151]
  [metabase.query_processor.store$do_with_metadata_provider invokeStatic "store.clj" 171]
  [metabase.query_processor.store$do_with_metadata_provider invoke "store.clj" 151]
  [metabase.query_processor.store$do_with_metadata_provider invokeStatic "store.clj" 160]
  [metabase.query_processor.store$do_with_metadata_provider invoke "store.clj" 151]
  [metabase.query_processor.setup$do_with_metadata_provider$fn__65246 invoke "setup.clj" 150]
  [metabase.query_processor.setup$do_with_resolved_database$fn__65240 invoke "setup.clj" 128]
  [metabase.query_processor.setup$do_with_qp_setup invokeStatic "setup.clj" 232]
  [metabase.query_processor.setup$do_with_qp_setup invoke "setup.clj" 216]
  [metabase.query_processor.compile$compile_and_splice_parameters invokeStatic "compile.clj" 53]
  [metabase.query_processor.compile$compile_and_splice_parameters invoke "compile.clj" 45]
  [metabase.api.dataset$fn__97235$fn__97238 invoke "dataset.clj" 175]
  [metabase.api.dataset$fn__97235 invokeStatic "dataset.clj" 171]
  [metabase.api.dataset$fn__97235 invoke "dataset.clj" 166]
  [compojure.core$wrap_response$fn__52960 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__52944 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__52949 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__52953 invoke "core.clj" 151]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52953 invoke "core.clj" 152]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52953 invoke "core.clj" 152]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52953 invoke "core.clj" 152]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52953 invoke "core.clj" 152]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [metabase.server.middleware.auth$enforce_authentication$fn__97278 invoke "auth.clj" 18]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972 invoke "core.clj" 200]
  [compojure.core$make_context$handler__53000 invoke "core.clj" 290]
  [compojure.core$make_context$fn__53004 invoke "core.clj" 300]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53004 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53004 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53004 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53004 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53004 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53004 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53004 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53004 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53004 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53004 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52953 invoke "core.clj" 153]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [metabase.api.routes$fn__104854$fn__104857 invoke "routes.clj" 73]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__105134$fn__105135 doInvoke "routes.clj" 73]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972 invoke "core.clj" 200]
  [compojure.core$make_context$handler__53000 invoke "core.clj" 290]
  [compojure.core$make_context$fn__53004 invoke "core.clj" 300]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52953 invoke "core.clj" 153]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52953 invoke "core.clj" 153]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52953 invoke "core.clj" 153]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52953 invoke "core.clj" 153]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972$f__52973$respond_SINGLEQUOTE___52974 invoke "core.clj" 197]
  [metabase.server.routes$fn__105117$fn__105119 invoke "routes.clj" 47]
  [compojure.core$routes$fn__52972$f__52973 invoke "core.clj" 198]
  [compojure.core$routes$fn__52972 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__101248 invoke "exceptions.clj" 107]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__101245 invoke "exceptions.clj" 96]
  [metabase.server.middleware.log$log_api_call$fn__105414$fn__105415$fn__105416 invoke "log.clj" 236]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 18]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 12]
  [metabase.server.middleware.log$log_api_call$fn__105414$fn__105415 invoke "log.clj" 227]
  [toucan2.execute$do_with_call_counts invokeStatic "execute.clj" 112]
  [toucan2.execute$do_with_call_counts invoke "execute.clj" 103]
  [metabase.server.middleware.log$log_api_call$fn__105414 invoke "log.clj" 226]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__108684 invoke "browser_cookie.clj" 40]
  [metabase.server.middleware.security$add_security_headers$fn__101204 invoke "security.clj" 241]
  [ring.middleware.json$wrap_json_body$fn__108943 invoke "json.clj" 64]
  [metabase.server.middleware.offset_paging$handle_paging$fn__87451 invoke "offset_paging.clj" 43]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__54493 invoke "json.clj" 83]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__109032 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__109051 invoke "params.clj" 77]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__70595 invoke "misc.clj" 60]
  [metabase.server.middleware.session$reset_session_timeout$fn__77725 invoke "session.clj" 552]
  [metabase.server.middleware.session$bind_current_user$fn__77691$fn__77692 invoke "session.clj" 446]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 425]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 408]
  [metabase.server.middleware.session$bind_current_user$fn__77691 invoke "session.clj" 445]
  [metabase.server.middleware.session$wrap_current_user_info$fn__77670 invoke "session.clj" 383]
  [metabase.server.middleware.session$wrap_session_id$fn__77642 invoke "session.clj" 259]
  [metabase.server.middleware.auth$wrap_static_api_key$fn__97286 invoke "auth.clj" 32]
  [ring.middleware.cookies$wrap_cookies$fn__108871 invoke "cookies.clj" 200]
  [metabase.server.middleware.misc$add_content_type$fn__70577 invoke "misc.clj" 28]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__70603 invoke "misc.clj" 77]
  [ring.middleware.gzip$wrap_gzip$fn__108913 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__70606 invoke "misc.clj" 94]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__108700 invoke "ssl.clj" 41]
  [metabase.server$async_proxy_handler$fn__70941 invoke "server.clj" 77]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.StatisticsHandler handle "StatisticsHandler.java" 173]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 122]
  [org.eclipse.jetty.server.Server handle "Server.java" 563]
  [org.eclipse.jetty.server.HttpChannel$RequestDispatchable dispatch "HttpChannel.java" 1598]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 753]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 501]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 287]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 314]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 100]
  [org.eclipse.jetty.io.SelectableChannelEndPoint$1 run "SelectableChannelEndPoint.java" 53]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 969]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner doRunJob "QueuedThreadPool.java" 1194]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1149]
  [java.lang.Thread run nil -1]],
 :cause "Invalid query: {:stages [{:filters [[nil nil [\"expression returning a string\"]]]}]}",
 :data
 {:type :invalid-query,
  :error {:stages [{:filters [[nil nil ["expression returning a string"]]]}]},
  :original
  {:schema :metabase.lib.schema/query,
   :value
   {:lib/type :mbql/query,
    :stages
    [{:lib/type :mbql.stage/mbql,
      :source-table 91,
      :filters
      [[:contains
        {:case-sensitive false, :lib/uuid "f6da5ec1-7d3b-4d06-a88a-134d74a55060"}
        [:field {:base-type :type/*, :lib/uuid "5cdb05f5-9aaf-468b-83ab-841f3c9777d9", :effective-type :type/*} 1372]
        "ABC"]]}],
    :database 2,
    :lib.convert/converted? true,
    :lib/metadata
    (metabase.lib.metadata.invocation-tracker/invocation-tracker-provider (metabase.lib.metadata.cached-provider/cached-metadata-provider (metabase.lib.metadata.jvm/->UncachedApplicationDatabaseMetadataProvider 2)))},
   :errors
   ({:path [0 0 :stages 0 0 0 0 1 :mbql.stage/mbql 0 0 :filters 0 0 0 0 0 true 0 :contains 0 0 :args 0 0 1],
     :in [:stages 0 :filters 0 2],
     :schema
     [:fn {:error/message "expression returning a string"} #object[metabase.lib.schema.expression$expression_schema$fn__14627 0x6a188d9b "metabase.lib.schema.expression$expression_schema$fn__14627@6a188d9b"]],
     :value
     [:field {:base-type :type/*, :lib/uuid "5cdb05f5-9aaf-468b-83ab-841f3c9777d9", :effective-type :type/*} 1372]})}},
 :message
 "Error preprocessing query in metabase.query_processor.preprocess$ensure_pmbql$fn__65774@17953c15: Invalid query: {:stages [{:filters [[nil nil [\"expression returning a string\"]]]}]}",
 :fn
 #object[metabase.query_processor.preprocess$ensure_pmbql$fn__65774 0x17953c15 "metabase.query_processor.preprocess$ensure_pmbql$fn__65774@17953c15"],
 :query
 {:lib/type :mbql/query,
  :stages
  [{:lib/type :mbql.stage/mbql,
    :source-table 91,
    :filters
    [[:contains
      {:case-sensitive false, :lib/uuid "f6da5ec1-7d3b-4d06-a88a-134d74a55060"}
      [:field {:base-type :type/*, :lib/uuid "5cdb05f5-9aaf-468b-83ab-841f3c9777d9", :effective-type :type/*} 1372]
      "ABC"]]}],
  :database 2,
  :lib.convert/converted? true,
  :lib/metadata
  (metabase.lib.metadata.invocation-tracker/invocation-tracker-provider (metabase.lib.metadata.cached-provider/cached-metadata-provider (metabase.lib.metadata.jvm/->UncachedApplicationDatabaseMetadataProvider 2)))}}


```

### Information about your Metabase installation

```JSON
Client Browser: Chrome v128
Host OS: Debian Bookworm
Host Database: Postgres
Host Metabase: v0.50.20
Host Environment: Docker
```

### Severity

Medium - Blocking Access to Some Filtered Questions

### Additional context

Updated from Metabase v49 to v50.
Roughly 10% of questions failed.
Some questions could be fixed by reapplying the existing filters.

**Comment by ranquild** [comment] 2024-08-27 20:54
@MarleTangible please upgrade to 50.22 where the issue is solved

**Comment by alxnddr** [comment] 2024-08-27 21:39
Closing the issue as it has already been fixed

**Closed by alxnddr** 2024-08-27 21:39 UTC
Labels: Type:Bug, .Needs Triage
