### ISSUE TITLE
Do not offer "Turn into a model" unless database supports it (and Nested Queries are enabled)

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#25475] opened 2022-09-17 09:21 UTC
**Describe the bug**
Similar to #22822, don't offer Models for databases that doesn't support nested queries, but also don't offer it if Nested Queries is disabled.

**To Reproduce**
1. Question > **Mongo** > (table) - save question
2. Click `...` menu in upper-right > "Turn into a model"
![image](https://user-images.githubusercontent.com/1447303/190849681-c1492dd3-526a-4fd1-b748-7634fa679737.png)

Alternatively
1. Admin > Settings > General > disabled "Nested Queries"
2. Question > Sample > Products - save question
3. Click `...` menu in upper-right > "Turn into a model"
![image](https://user-images.githubusercontent.com/1447303/190849744-33056f07-b8ac-4c8c-a7fd-206ae59bc93f.png)

**Information about your Metabase Installation:**
Tested 0.44.3

**Comment by kamilmielnik** [comment] 2024-04-04 14:28
I can't reproduce following the 1st reproduction steps, but I can using the alternative path. `master` at c059d8d585.

**Comment by nemanjaglumac** [comment] 2024-07-05 08:29
The requirements changed:
https://github.com/metabase/metabase/pull/44931/files#diff-acb4f0691090b21c587a7bdab67915b2b2958784edd0775eabac945211ec3598L89-L92

This issue will most likely be closed as not planned.

**Closed** 2024-07-05 13:06 UTC
Labels: Type:Bug, Priority:P3, .Frontend, Querying/Models, .Team/QueryingComponents
