### ISSUE TITLE
"Howdy" (etc.) greeting changes after every letter when you create a dashboard from the home page

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#12517] opened 2020-05-13 03:32 UTC
1.  Go to the home page
2.  Click `+` > `New dashboard`
3.  Start typing the Name
4.  The greeting changes after every letter you type, from "Howdy" to "Greetings" to "How's it going" etc.

I'm guessing it's re-rendering the entire page after every ~letter I type~ state change and as part of re-rendering it's randomly selecting a different greeting.

**Comment by flamber** [comment] 2020-05-13 09:37
Duplicate of #11952

**Closed by flamber** 2020-05-13 09:37 UTC
Labels: .Frontend, .Needs Triage, Type:Bug
