### ISSUE TITLE
Refused to execute inline script because it violates the CSP when published on sub URI

### ISSUE THREAD

**Issue by danaivehr** [metabase/metabase#12020] opened 2020-03-02 14:35 UTC
**Describe the bug**

Blank screen when loading any metabase page, if metabase is under sub URI (https://mysite.com/metabase)

Something is with CSP (Content-Security Policy), since metabase loading is OK when CSP is disabled

**Logs**
Browser console logs shows error:

```
Refused to execute inline script because it violates the following Content Security Policy directive:
"script-src 'self' 'unsafe-eval' https://maps.google.com https://apis.google.com 
https://www.google-analytics.com https://*.googleapis.com *.gstatic.com  
'sha256-lMAh4yjVuDkQ9NqkK4H+YHUga+anpFs5JAuj/uZh0Rs=' 
'sha256-7t0fjA/BVlVoDzQGo5fjx1QcGZGP/YHzqHjtle6rQr0=' 
'sha256-JJa56hyDfUbgNfq+0nq6Qs866JKgZ/+qCq2pkDJED8k='". 
Either the 'unsafe-inline' keyword, a hash 
('sha256-ZK8hqm7VGNvsYjBNbMWmJD1MH49Ia5DBJXO8XI7dtsU='), 
or a nonce ('nonce-...') is required to enable inline execution.
``` 

**To Reproduce**
1. Publish metabase on https://mysite.com/metabase/ behind the proxy
2. Go to https://mysite.com/metabase/ with Google Chrome 79.0.3945.130
3. See blank screen
4. See error in browser console
5. Disable CSP (with some browser plugin, for example "Disable Content-Security-Policy", id ieelmcmcagommplceebfedjlakkhpden)
6. Reload page
7. Metabase is loading OK without errors

**Expected behavior**
Metabase page shows up with CSP enabled.

**Information about your Metabase Installation:**

- Browser and the version: Google Chrome 79.0.3945.130, also tested with Firefox - the same issue
- Your operating system: Windows 10 / Windows 7
- Metabase version: 0.34.3 JAR, and any other version >= 0.33 (0.32.3 is working well)
- Metabase hosting environment: Jar-file on Ubuntu 14 LTS
- Metabase internal database: H2
- Web server Apache 2 proxy from https://mysite.com/metabase/ to http://localhost:3000

**Severity**
Always

**Comment by flamber** [comment] 2020-03-02 15:23
Hi @danaivehr 

It looks like a duplicate of #11979.

Metabase works with a reverse proxy, also as non-root, but it's impossible to know every reverse proxy configuration, so make sure that you're not using any modules in Apache that might be modifying the content (i.e. PageSpeed) or try another reverse proxy (i.e. Nginx or Caddy), if you still cannot make it work with your Apache.

Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And I would recommend that you post your Apache configs too, and what modules are loaded.

You should also migrate away from H2 if you're using Metabase in production:
https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html

**Closed by flamber** 2020-03-02 15:23 UTC
Labels: .Needs Triage, Type:Bug
