### ISSUE TITLE
Model metadatas descriptions disappears after column mapping

### ISSUE THREAD

**Issue by alxsbn** [metabase/metabase#30725] opened 2023-05-12 10:05 UTC
### Describe the bug

When you update a model metadata column (description / semantic) disappear when you linked your column with a database table column

### To Reproduce

1. Go to a saved model
2. Click on 'Edit meta-data'
3. Click on a column, add a description
4. Click on 'Save changes'
5. Refresh the model view, pass your mouse on the column header to see the description
6. Click on 'Edit meta-data'
7. Click on the same column, map with database column (e.g. an entity key)
8. Click on 'Save changes'
9. Refresh the model view, pass your mouse on the column header to see the description are gone (but the mapping yes)

### Expected behavior

The column descriptions need be preserved

### Information about your Metabase installation

```JSON
- Chromium 112.0 on Pop_OS 22.04! LTS
- MySQL database
- Metabase v0.46.2 host on Docker
- Internal Metabase database host on Postgres
```

### Severity

Non-blocking

**Comment by ranquild** [comment] 2024-07-03 16:10
I can repro it like this:
- Have a field without description
- Create a SQL model with a query that selected this field
- Map the column from the query results to the field in the db
- Save the model
- Go to Table Metadata and set the description
- Now the UI in Edit metadata would incorrectly show the description from the mapped field but actually the description is not set in the model metadata

**Comment by ranquild** [comment] 2024-07-03 20:12
It seems that the user expectation here is that after mapping the DB field, all subsequent metadata updates (`display_name`, `description`, `semantic_type`, `fk_target_field_id`, `visibility_type`, `settings`) to the underlying field are propagated to models metadata. Same as https://github.com/metabase/metabase/issues/27967.

**Comment by ranquild** [comment] 2024-07-04 12:26
Duplicate of https://github.com/metabase/metabase/issues/27967

**Closed by ranquild** 2024-07-04 12:26 UTC
Labels: Type:Bug, Priority:P2, .Frontend, Querying/Models, .Team/QueryingComponents
