### ISSUE TITLE
Support Mysql Cross-data source queries

### ISSUE THREAD

**Issue by Avey777** [metabase/metabase#31597] opened 2023-06-15 01:26 UTC
Our data is stored in MySQL databases in multiple regions. It would be great if Metabase could query and merge data from multiple different MySQL data sources. (Currently, Redash solves this problem through Python data sources.)

**Comment by paoliniluis** [comment] 2023-06-15 09:13
I think this is a duplicate of https://github.com/metabase/metabase/issues/3953

**Closed by paoliniluis** 2023-06-15 09:13 UTC
Labels: Type:New Feature, .Needs Triage

**Comment by Avey777** [comment] 2023-06-15 09:52
> I think this is a duplicate of #3953

This is a different feature from 3953.

**Comment by paoliniluis** [comment] 2023-06-15 12:44
I’m having a difficult time understanding what you need if this is not about joining 2 datasets

**Comment by Avey777** [comment] 2023-06-15 12:51
> I’m having a difficult time understanding what you need if this is not about joining 2 datasets

The issue is discussing secondary queries based on queries. I hope to be able to directly query data from multiple different data sources and merge the queried data.
