### ISSUE TITLE
Google Analytics dynamic column names not accessible

### ISSUE THREAD

**Issue by philipptri** [metabase/metabase#4717] opened 2017-04-07 09:49 UTC
When I try to query one of the following columns of the Google Analytics driver

- Page Group XX
- Custom Variable (Key XX)
- Custom Variable (Value XX)
- Custom Dimension XX
- Landing Page Group XX
- Previous Page Group XX
- Product Category Level XX

... the New Question view returns this error message:

```
Unknown dimension(s): ga:contentGroupXX For details see
https://developers.google.com/analytics/devguides/reporting/core/dimsmets.
```

These columns need to be split up into [separate columns for each index](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=content_grouping&jump=ga_contentgroupxx). E.g. `ga:contentGroup1, ga:contentGroup[N], ga:contentGroup5`

If there's a way to configure it differently on our end, let me know. Otherwise, it would be great to enable this feature since it's quite important for us to query some of these columns.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by etburke** [comment] 2017-09-13 23:10
I've run into this, too.

**Comment by maicolpractiodk** [comment] 2017-12-14 17:08
Just stumbled upon the same for "GoalXX...".

I wonder if a feature for entering the XX value (defined as index in Google Analytics Documentation) 
will be accepted...but I am afraid it is too much of an edge case! https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=goal_conversions&jump=ga_goalxxcompletions

**Comment by maicolpractiodk** [comment] 2017-12-15 14:20
Hi, I think I found a solution @philipptri!
You "simply" have to "Switch to native query" and substitute XX with the number needed. 

I know it sounds like trolling but, in my goal conversion case, it was super simple to solve the problem! 
First I built a query for all site conversations with an aggregation similar to the one I needed but without the XX. The, I simply opened the editor and manually changed the aggregation and it worked perfectly :)

I hope it helps.

**Comment by apognu** [comment] 2018-10-12 18:55
Any news on this? This is quite cumbersome for non-tech people on our team.

**Comment by dacort** [comment] 2020-01-21 16:24
Was just trying to do this as well for a custom dimension. This syntax works for a native query for a custom dimension (`dimension1`):

```
{
  "ids": "ga:1234567",
  "start-date": "180daysAgo",
  "end-date": "today",
  "metrics": "ga:totalEvents",
  "dimensions": "ga:dimension1,ga:eventLabel",
  "filters": "ga:eventCategory==SomeCategory;ga:eventAction==SomeAction;ga:dimension1=~^ABC.*",
  "include-empty-rows": false,
  "max-results": 10000
}
```

**Comment by paulvolk** [comment] 2020-08-14 17:54
> Any news on this? This is quite cumbersome for non-tech people on our team.

Same here -- Any word on an enhancement for this? -- Noticed you closed it @flamber  but the ticket still shows as open :/

**Comment by flamber** [comment] 2020-08-14 17:58
@paulvolk I didn't close this issue - I closed another issue that was a duplicate of this.

**Comment by camsaul** [comment] 2023-06-28 17:22
Closing as not planned due to dropping GA support

**Closed by camsaul** 2023-06-28 17:22 UTC
Labels: .Limitation, Type:New Feature, Database/Google Analytics
