### ISSUE TITLE
Fields order in data model not work.

### ISSUE THREAD

**Issue by sbonnet** [metabase/metabase#15829] opened 2021-04-27 13:58 UTC
When you want to order the fields in the data model you get a 400 error.

We receive a 400 error on when make a PUT onhttps://metabase.dispofi.fr/api/table/98/fields/order.

Error is : {"errors":{"field_order":"la valeur doit être un tableau. Chaque la valeur doit être un entier supérieur à zéro."}}
Request Payload Contains a table with null values [ null , null , null ......].

1. Go to 'Administration'
2. Click on 'Data Model'
3. Choose a collection
4. Change the order of fields with drag and drop.

I use MongoDB 4.4 and Metabase 0.39.1 on aws linux 2.

Chrome Version 90.0.4430.85 on MacOS 10.15.7 for client

**Comment by flamber** [comment] 2021-04-27 14:01
Duplicate of #13132

**Closed by flamber** 2021-04-27 14:01 UTC
Labels: .Needs Triage, Type:Bug
