### ISSUE TITLE
Pulses not loading anymore

### ISSUE THREAD

**Issue by luissancho** [metabase/metabase#5799] opened 2017-08-23 09:10 UTC
- Your browser and the version: Chrome 60.0
- Your operating system: OS X 10.12.6
- Your databases: MySQL
- Metabase version: {"tag":"v0.26.0-snapshot","date":"2017-08-22","branch":"master","hash":"8cb7896"}
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

It appears to be an issue with a variable called "channel" (see screenshot below), so the Pulses page stays at "Loading..." forever and never renders.

![metabase-pulses-issue](https://user-images.githubusercontent.com/12734676/29608148-a4e8528e-87f3-11e7-839c-9066a4dec9ce.png)

Regards.
LuisS

**Comment by camsaul** [comment] 2017-08-23 18:19
@metabase/core-developers sounds like Pulses are broken on master?

**Comment by attekei** [comment] 2017-08-23 18:24
I couldn't immediately reproduce (on our internal stats instance everything works normally) but will take a closer look later today.

**Comment by camsaul** [comment] 2017-08-23 18:34
Another new (?) Pulses bug we could potentially address at the same time: #5742

**Comment by camsaul** [comment] 2017-08-23 18:39
I can't reproduce this locally either. What object is it expecting that would `channel`? For Pulses I see `channels`, but not `channel`. Trying to figure out the message

```
Cannot read property `channel` of undefined
```

It seems like an object is coming back as `null` and the frontend code isn't checking for `null` before trying to access a property of it

**Comment by luissancho** [comment] 2017-08-25 11:26
Can I provide more info? Data, browser info, anything to help you figure it out.

**Comment by attekei** [comment] 2017-08-30 20:31
My current assumption is that some saved pulse is in an invalid state where where it is supposed to send pulses to Slack but the Slack channel isn't set. I'll check if it's easy to get a pulse to that state while creating a new pulse / editing an existing pulse.

**Comment by attekei** [comment] 2017-08-30 21:25
I couldn't reproduce the issue in the UI so I had to modify the channel db entity directly; I created #5851 which addresses this issue

**Comment by camsaul** [comment] 2017-09-06 23:01
Fixed by #5851

**Closed by camsaul** 2017-09-06 23:01 UTC
Labels: Bug, Priority/P2, Pulses

**Comment by mazameli** [comment] 2017-09-27 20:55
@luissancho just a heads up that [we've just shipped version 0.26](http://www.metabase.com/blog/Metabase-0.26) which fixes this issue.
