### ISSUE TITLE
Filter by foreign MongoDB ID does not seem to work (?)

### ISSUE THREAD

**Issue by nodesocket** [metabase/metabase#1340] opened 2015-10-23 00:08 UTC
Doing a filter using a foreign MongoDB id, returns 0 results.

**Comment by salsakran** [comment] 2015-10-27 19:29
What do you mean by foreign MongoDB id in this context? Could you give us an example document and the filter you're trying to add?

**Comment by camsaul** [comment] 2015-11-18 22:29
See also #1367

**Comment by camsaul** [comment] 2015-11-18 22:56
Duplicate of #1340

**Comment by camsaul** [comment] 2015-11-18 22:57
* Duplicate of #1367

**Closed by camsaul** 2015-11-18 22:56 UTC
Labels: bug
