### ISSUE TITLE
Date localization options does not affect in filters

### ISSUE THREAD

**Issue by PiRomant** [metabase/metabase#19419] opened 2021-12-18 10:24 UTC
**Describe the bug**
Changing localization options does not affect in date filters

**Screenshots**
![image](https://user-images.githubusercontent.com/29551044/146637393-8cef46cc-0ef9-4f62-8cc8-fb2eb274a53f.png)
![image](https://user-images.githubusercontent.com/29551044/146637413-01763f74-1138-4411-a6fe-23b78bbd6537.png)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "ru-RU",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.12+7",
    "java.vendor": "Eclipse Foundation",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.12",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.12+7",
    "os.name": "Linux",
    "os.version": "5.4.0-84-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-10-21",
      "tag": "v0.41.1",
      "branch": "release-x.41.x",
      "hash": "76aa4a5"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Very annoying. Prevent copy-paste to filter.

**Comment by flamber** [comment] 2021-12-18 10:28
You should upgrade: https://github.com/metabase/metabase/releases/latest
Duplicate of #9151

**Closed by flamber** 2021-12-18 10:28 UTC
Labels: Type:Bug, .Needs Triage
