### ISSUE TITLE
Line chart is not displaying result in Builder but in native query

### ISSUE THREAD

**Issue by gowshalinirajalingam** [metabase/metabase#9345] opened 2019-01-30 09:40 UTC
We are facing issues when creating metabase charts.One is:
When creating line chart where x axis is Timestamp(Day) and y axis is count of rows the chart is not displaying.
The screenshot of this is below
![image](https://user-images.githubusercontent.com/31157711/51972322-23c5a200-24a1-11e9-8f70-9233c9e45260.png)

But when we go to the particular chart’s native query and click refresh it is displaying the chart.
The screenshot of this is below
![image](https://user-images.githubusercontent.com/31157711/51971886-430fff80-24a0-11e9-91e1-f05e10efb27f.png)

**Comment by flamber** [comment] 2019-01-30 14:25
@gowshalinirajalingam 
Which browser and version? Which Metabase version?
Do you see anything in the browser console or Metabase log, when it fails to show the graph?

**Comment by gowshalinirajalingam** [comment] 2019-02-05 10:54
metabase version: 31.0.1
Chrome version: Version 71.0.3578.98 (Official Build) (64-bit)

Error in console is shown in the below image
![image](https://user-images.githubusercontent.com/31157711/52268811-6c2e0580-2962-11e9-9b8c-04633997d4ee.png)

**Comment by flamber** [comment] 2019-02-05 15:09
Related to #7604

**Comment by denisesenguel** [comment] 2019-05-20 15:55
I have the same issue. All charts are broken when grouping by day using the query builder, while both the exact same native query as well as all other timestamp granularities in the query builder are working just fine!

**Comment by flamber** [comment] 2019-05-20 16:51
@denisesenguel 
Are you seeing the same errors in the browser console?
Does it work if you change from Timeseries to Ordinal in the Visualization settings :gear: ?

**Comment by denisesenguel** [comment] 2019-05-21 08:07
i'm not seeing any errors in the brower console, only warnings:
![Screenshot 2019-05-21 at 10 02 23](https://user-images.githubusercontent.com/17010657/58078910-206d3800-7bb0-11e9-81e7-4c730b6e10ee.png)


changing viz settings to ordinal doesn't work either..

**Comment by viblo** [comment] 2019-06-25 09:19
I have the same issue, and get the same warning in console.

Charts with this problem: line, bar and area charts (scatter seems a bit strange as well)
Charts that work: table, row, pie
Browser: Firefox 67.0.3
Datasource: Druid
Metabase: 0.32.9

**Comment by paulrosenzweig** [comment] 2019-07-23 18:25
I think the warnings in console are unrelated.

Is anyone able to see the "A negative value is not valid" error without zooming? I can reproduce that when zooming the browser (like mentioned in #7604), but not at the standard zoom level.

@gowshalinirajalingam, from your screenshot it looks like you're at the default zoom. Are you able to reproduce this on the sample dataset that comes with Metabase? If not, can you provide a minimal example of what data is needed to trigger this error? Thanks!

**Comment by denisesenguel** [comment] 2019-10-03 09:56
After updating to Metabase 0.33.2., the workaround with displaying Line Charts by converting the built query to a native query and re-running doesn't work anymore either! This makes the issue much more severe for us! :-(

**Comment by flamber** [comment] 2019-10-03 17:34
@denisesenguel Upgrade to 0.33.3 - there were several fixes, specially a problem where histograms without the first column not being a date-type would cause issues.

**Comment by denisesenguel** [comment] 2019-10-04 07:34
Awesome, this issue seems to be fixed entirely with version 0.33.3!! Thanks people! 🙏 💯

**Comment by mazameli** [comment] 2019-10-04 16:29
@gowshalinirajalingam have you also tried updating to 0.33.3 (latest)? @denisesenguel reports that the issue is fixed in that version. Just make sure to back up your application database any time you upgrade.

**Comment by mazameli** [comment] 2019-10-10 21:00
Closing this as fixed in 0.33.3, but will reopen if there are more reports of this in 0.33.3 or 0.33.4 (latest).

**Closed by mazameli** 2019-10-10 21:00 UTC
Labels: Priority:P2, Query Builder, Type:Bug, Visualization/
