### ISSUE TITLE
Query with timestamp grouping fails in Windows Server 2008 R2

### ISSUE THREAD

**Issue by efredz** [metabase/metabase#5577] opened 2017-07-25 21:48 UTC
Operating System: Windows Server 2008 R2
Database: SQL Server 2012
Metabase Version: 0.24.2
Internal Database: H2

Steps to Reproduce:

- Set Timezone to anything besides UTC
- Try to make a query that involves timestamp grouping
- The result is: 
`We're experiencing server issues
Try refreshing the page after waiting a minute or two. If the problem persists we'd recommend you contact an admin.`
- In the server logs:
```
07-25 16:25:53 ←[1mDEBUG driver.generic-sql←[0m :: ←[35mCreating new connection pool for database 2 ...←[0m
07-25 16:25:54 ←[1mDEBUG query-processor.sort←[0m :: ←[33mSorted fields:
([:0-breakout 0 :2-other :fecha] [:1-aggregation 2147483647 :2-other :cant_acompa±antes] [:1-aggregation 2147483647 :2-o
ther :sum] [:3-other 2147483647 :2-other :fecha])
←[0m
07-25 16:25:54 ←[1mDEBUG metabase.middleware←[0m :: ←[32mPOST /api/dataset 200 (1 s) (13 DB calls)←[0m
07-25 16:25:54 ←[1mWARN server.HttpChannel←[0m :: /api/dataset
java.lang.IllegalArgumentException: The datetime zone id 'GMT-05:00' is not recognised
```

This happens even if there's a TimeZone configured in the the 'General' Tab in the 'Admin Panel'

**Comment by salsakran** [comment] 2017-08-01 18:17
what version of the JVM are you using @efredz ?

**Comment by senior** [comment] 2017-08-29 16:26
@efredz I think the problem is the timezone string you're using "GMT-05:00" is recognized by the JVM list of timezones, but not by the JodaTime (a commonly used Java library) list of timezones. I validated this on 0.25.2 and the error is coming from JodaTime.

It looks like the equivalent string that is recognized by both is "Etc/GMT+5". The +5 part threw me off at first, but the JVM confirms that these are the same:
```
(.hasSameRules  (java.util.TimeZone/getTimeZone "GMT-05:00")
                            (java.util.TimeZone/getTimeZone "Etc/GMT+5"))
;=> true
```
Not exactly sure what your timezone situation is, but you might want to use a more specific timezone than just a GMT-05:00, i.e. 'America/New_York' or 'America/Chicago' as it will better handle things like daylight savings time. More info on JodaTime timezone IDs is [here](http://joda-time.sourceforge.net/timezones.html).

**Comment by aespinosaMD** [comment] 2018-05-28 17:20
how to solve? i have this problem, but I change the zone of my PC and nothing...
error: 
Could not send response error 500: java.lang.IllegalArgumentException: The datetime zone id 'GMT-05:00' is not recognised 

I must change the zone in my server?
(if my english dont understand sorry, I speak spanish :( )

**Comment by TurkerTunali** [comment] 2018-07-26 10:56
I also got this error with SQL Server 2008 on my server. @aespinosaMD  did you solve it? Can we set timezone via java jar command line parameter?

**Comment by jornh** [comment] 2018-07-26 15:43
@TurkerTunali said:
> Can we set timezone via java jar command line parameter?

Yes, according to https://metabase.com/docs/latest/troubleshooting-guide/timezones.html either `-Duser.timezone<..>` on the command line or environment variable `JAVA_TIMEZONE`. It's a standard Java thing. You will have to google what valid strings work in your timezone, specially with the Joda time mentioned above.

**Comment by TurkerTunali** [comment] 2018-07-30 08:06
Thank you @jornh.
This did the trick for me.
java -Duser.timezone=Europe/Istanbul -jar metabase.jar

**Comment by camsaul** [comment] 2020-07-16 17:52
Closing as no longer relevant since we're not using JodaTime anymore

**Closed by camsaul** 2020-07-16 17:52 UTC
Labels: Database/SQLServer, Misc/Timezones, Priority:P2, Type:Bug
