### ISSUE TITLE
Table joins and Custom Column returns same results for columns with the same name

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12649] opened 2020-06-04 21:41 UTC
**Describe the bug**
A question with joins and a Custom Column, will overwrite results from same-named columns.

**Logs** No errors.

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Join Products on ProductID=ID - result should look like this (correct):
![image](https://user-images.githubusercontent.com/1447303/83810646-c7881900-a6b8-11ea-91d2-0313702e1d28.png)
3. Now add Custom Column, formula `1+1`, name `X`
Notice that all columns with the same name have the same result. First column `ID` is showing the value of `Product.ID`, and `Product.CreatedAt` is showing value of `CreatedAt`
![image](https://user-images.githubusercontent.com/1447303/83810961-40877080-a6b9-11ea-9566-d56baf959226.png)

**Information about your Metabase Installation:**
Metabase 0.35.0, 0.35.1, 0.35.2, 0.35.4 and `master` - multiple backends and stats.

**Additional context**
Results are correct in 0.35.3
Maybe related to what fixed #12588, which only existed in 0.35.3

**Comment by rthouvenin** [comment] 2020-06-09 14:48
Any idea of when a fix could be released? Is it a candidate for next release? We have a number of questions with a join and custom columns, and the bug makes all these questions display a wrong result.

**Comment by camsaul** [comment] 2020-06-16 21:20
@flamber this is definitely a serious bug, but please don't add stuff to the 0.36.0 board without discussing it. The goal is to get everything in the 0.36.0 board finished and then continue tackling other bugs and features (such as this one).

**Comment by mlm603** [comment] 2020-09-22 22:57
Experiencing an issue that probably has the same underlying cause as this one: 
I have 2 columns from different tables both called `name`. I created a custom column, then tried to filter for `table1.name = x` and `table2.name = y`, but the SQL that is generated doesn't use the correct aliases.

This is what the generated sql looks like:

```
SELECT count(*) AS "count"
FROM (
     SELECT [calculated field] AS "Calculated Field"
     , "table1"."name" AS "name"
     , "table2"."name" AS "name_2"
     FROM "schema"."table1"
     LEFT JOIN "schema"."table2"
          ON "table1"."field1" = "table2"."field1"
) "source"
WHERE (
     "source"."Calculated Field" = 1
     AND "source"."name" = 'x' AND "source"."name" = 'y'
)
```

it should be filtering for `"source"."name" = 'x' AND "source"."name_2" = 'y'` in the last line

**Comment by nemanjaglumac** [comment] 2020-10-21 21:05
### Note:
- this issue has been reproduced with Cypress test (merged as https://github.com/metabase/metabase/commit/2670f6c8dd535a96bea9851f4f7eae1929b6d648)
- the instructions on how to test in isolation, with a note to unskip and merge this test are described in https://github.com/metabase/metabase/pull/13557

**Comment by rlotun** [comment] 2021-02-01 04:06
Fixed by https://github.com/metabase/metabase/pull/14014

**Closed by rlotun** 2021-02-01 04:06 UTC
Labels: .Backend, .Reproduced, Priority:P1, Querying/, Type:Bug
