### ISSUE TITLE
SQL Server filtering null dateTime fields broke after update

### ISSUE THREAD

**Issue by bilalsavas** [metabase/metabase#41005] opened 2024-04-04 09:08 UTC
### Describe the bug

After the update some charts broke, when I investigate the root cause is on handling datetime fields. The question have filter checking if that datetime field is null. But in query it generates

SELECT
  SUM(
    "Stok Kart Fiyat - StokKartId"."usdFiyat" * "dbo"."AMBALAJ"."ambalajIciMiktar" * 0.4
  ) AS "USD Tutar"
FROM
  "dbo"."AMBALAJ"
  FULL JOIN "dbo"."STOK_KART_FIYAT" AS "Stok Kart Fiyat - StokKartId" ON "dbo"."AMBALAJ"."stokKartId" = "Stok Kart Fiyat - StokKartId"."stokKartId"
WHERE
  ("dbo"."AMBALAJ"."kapatildi" = 1)
 
   AND ("dbo"."AMBALAJ"."irsaliyeId" IS NULL)
  AND ("Stok Kart Fiyat - StokKartId"."fiyatListeId" = 7)
  AND (
    **"dbo"."AMBALAJ"."deletedAt" = CAST(NULL AS datetimeoffset)**
  )

Having this line like this returns null, It should be dbo.AMBALAJ IS NULL

### To Reproduce

1. Go to 'New Question'
2. Add a "IS NULL" filter to datetime field 
3. Results will be null

### Information about your Metabase installation

```JSON
- Metabase 0.49.3
- SQL Server 2016
```

### Severity

Severe

**Comment by paoliniluis** [comment] 2024-04-04 09:10
I think we fixed it already, cc @lbrdnk

**Comment by paoliniluis** [comment] 2024-04-04 11:28
e.g. https://github.com/metabase/metabase/issues/40885

**Comment by lbrdnk** [comment] 2024-04-04 11:39
Fix for the issue is part of the PR https://github.com/metabase/metabase/pull/40957.

**Comment by paoliniluis** [comment] 2024-04-04 11:43
Closing due to duplicate then

**Closed by paoliniluis** 2024-04-04 11:43 UTC
Labels: Type:Bug, .Needs Triage
