### ISSUE TITLE
"keep data pivoted" on the download menu is not translated at all

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#50427] opened 2024-11-22 21:49 UTC
### Describe the bug

Seems we missed that specific section 
![Image](https://github.com/user-attachments/assets/e65f66c6-05c8-4e6e-ad08-a0b7b76c182e)

### To Reproduce

Set the instance to another language
try to download a pivot

### Expected behavior

we should translate everything on the FE

### Logs

NA

### Information about your Metabase installation

```JSON
v51
```

### Severity

P2

### Additional context

NA

**Comment by dpsutton** [comment] 2024-11-22 22:21
dupe of https://github.com/metabase/metabase/issues/50196 and already fixed.

**Closed by dpsutton** 2024-11-22 22:21 UTC
Labels: Type:Bug, .Needs Triage
