### ISSUE TITLE
Saving a question does not really persist changes

### ISSUE THREAD

**Issue by Mapiarz** [metabase/metabase#16699] opened 2021-06-21 15:46 UTC
**Describe the bug**
We have a custom question that uses another nested question. In total, there are more than 6 data series available but only 2 are selected to show in the graph. When I enter question settings and add more series to the graph, they show up correctly. When I hit save question (either replace or new), the saved question goes back to showing only 2 series. The question is: https://happydogsnyc.metabaseapp.com/question/33

This is the question:
![image](https://user-images.githubusercontent.com/2741167/122788198-61b40280-d2b6-11eb-8a71-e6b54ce4559b.png)

Here I'm adding more series:
![image](https://user-images.githubusercontent.com/2741167/122788300-78f2f000-d2b6-11eb-8e8d-16c739a79a7f.png)

And then the question goes back to looking like on the first screenshot.

As I was reproducing this for the screenshots, I think the question got corrupted further and now refuses to display anything:
![image](https://user-images.githubusercontent.com/2741167/122790191-5d88e480-d2b8-11eb-8871-5192f5242276.png)

**Information about your Metabase Installation:**

Using metabase cloud (1.39.2), not self hosted.

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.14.219-164.354.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "googleanalytics",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.9"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-17",
      "tag": "v1.39.2",
      "branch": "release-x.39.x",
      "hash": "b0d9436"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}

```

**Additional context**
I know this is pretty vague. If this is not fit for a bug report but instead for some kind of support ticket, do let me know please.

**Comment by flamber** [comment] 2021-06-21 16:00
99% sure it's a duplicate of #15882

**Closed by flamber** 2021-06-21 16:00 UTC
Labels: .Needs Triage, Type:Bug
