### ISSUE TITLE
Unable to share the dashboard

### ISSUE THREAD

**Issue by sathiyasarathi** [metabase/metabase#4947] opened 2017-05-03 09:35 UTC
While trying to view the dashboard upon clicking the public link.

From the Logs:
POST /api/dataset/duration 401 (67 µs) (0 DB calls) "Unauthenticated" metabase

The user can visualize the dashboard until the page fully loads and finally, the page is redirected to:
http://localhost:3000/auth/login

Any help would be much appreciated.

**Comment by camsaul** [comment] 2017-05-03 17:21
Sounds like a duplicate of #4557

**Comment by salsakran** [comment] 2017-05-04 01:40
yup, this is pretty much exactly #4557 
@sathiyasarathi this is fixed in master and will be in our upcoming 0.24 release.

**Closed by salsakran** 2017-05-04 01:40 UTC
