### ISSUE TITLE
Edit text on trend visualization

### ISSUE THREAD

**Issue by ryanr-trustengine** [metabase/metabase#31038] opened 2023-05-25 17:36 UTC
We're currently producing a handful of trend visualizations, for 1 month ago vs prior month, but also for 2 months ago vs prior month, etc. Currently the text on our trend visualization reads "was X last month".  

The mention of "last month" can be confusing if you're comparing against a historical period of time.

Can we create the option to edit that text? or perhaps change to the more generic "was X in previous [time period]"?

**Comment by paoliniluis** [comment] 2023-05-25 19:20
I think this is a duplicate of https://github.com/metabase/metabase/issues/8919

**Closed by paoliniluis** 2023-05-25 19:20 UTC
Labels: Type:New Feature, .Needs Triage
