### ISSUE TITLE
Histogram: Enable custom bin number and width

### ISSUE THREAD

**Issue by EBoisseauSierra** [metabase/metabase#12878] opened 2020-07-09 09:43 UTC
## Current situation

Currently (v0.35.4), I can aggregate a summarized metric (e.g. count of rows) by another continuously distributed column (e.g. “total price”).

As a user, I can choose between:
* no binning — i.e. using every single price value, which often leads to only 1 occurrence per price,
* pre-defined number of bins — 10, 50, or 100,
* auto-magical binning — Metabase does wonders.

## Wished solution

Yet when creating an histogram, I would like to chose:

* either a custom number of bins (e.g., 7, and not being limited to 10, 50, 100, or “auto-magical”),
* or a custom bin width (e.g. a bin every $25).

## Workaround

This can be setup with more or less effort via a custom SQL query. However, this solution has some drawbacks:

* hardcoded limits,
* requiring SQL skills,
* not available to “regular” users (i.e. those without SQL privileges)

## Importance
Nice to have.

**Comment by flamber** [comment] 2020-07-09 09:48
Duplicate of #12847?

**Closed** 2020-07-09 10:24 UTC
Labels: .Needs Triage, Type:New Feature

**Comment by EBoisseauSierra** [comment] 2020-07-09 10:42
Indeed, thanks! (sorry I only searched for “histogram” issues…)
I would say the only variation would be to be able to directly specify the bin width, rather the number of them ￫ I'll detail it on that issue.
