### ISSUE TITLE
Moving fields to the end of a big field list in Metabase models causes a scroll to the beginning

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#28172] opened 2023-02-08 21:25 UTC
**Describe the bug**
I have many fields in a Metabase model -- it requires scrolling to the right to see the last field. In edit mode, if I move one field to the end of the list, it will cause a scroll jump to the beginning of the field list -- first issue. 

**Logs**
n/a

**To Reproduce**
1. Create a Metabase model with many fields that require scrolling to the right to see the last field. 
2. Move one field from left to the end of the list. 
3. Browser will jump to the beginning of the field list

**Expected behavior**
Browser scroll should not change / jump after moving field. 

**Screenshots**
n/a

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome
- Your operating system: OS X
- Your databases: Postgres
- Metabase version: master
- Metabase hosting environment: Metabase Cloud Dev
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
It's annoying and hard to move things to the end if there are many fields that needs to be moved. 

**Additional context**
n/a

**Comment by ranquild** [comment] 2024-07-03 16:11
Duplicate of https://github.com/metabase/metabase/issues/41419

**Closed by ranquild** 2024-07-03 16:11 UTC
Labels: Type:Bug, Priority:P3, .Frontend, Querying/Models, .Team/QueryingComponents
