### ISSUE TITLE
Proposal: Set a pulse to be sent more than once per day (and few minor other improvements to Pulses)

### ISSUE THREAD

**Issue by plailleur** [metabase/metabase#8458] opened 2018-09-05 09:58 UTC
Hi,

Pulses are great but if you need them to be sent more than once per day then you need to manually duplicate them.

Would be great to be able to set a daily pulse to be sent more than once with two options:
- Every x hour
- At a given time (a + button under the first hour so add another line/time)

Would be also great if we could deactivate Pulses rather than having to delete/re-create them (could be under each Pulses page of at the root page of Pulses with a radio-button). Also it'd be useful if we could duplicate and archive them.

**Comment by flamber** [comment] 2019-02-24 19:11
Hi @plailleur 
It sounds like a duplicate of #3135 - and related to #3846
You can de/activate "Where should this data go?", when you edit them. And you can also un/archive pulses. This is how it looks on 0.31.2:
![image](https://user-images.githubusercontent.com/1447303/53303911-92deae00-3835-11e9-849e-f52342b89ff7.png)

**Comment by flamber** [comment] 2020-05-07 10:05
Closing in favor of #3846 (and #3135)

**Closed by flamber** 2020-05-07 10:05 UTC
Labels: .Proposal, Reporting/Pulses
