### ISSUE TITLE
"Friendlier Fields" Foreign Key Display Value Remapping Not Working?

### ISSUE THREAD

**Issue by sherbondy** [metabase/metabase#5671] opened 2017-08-02 23:30 UTC
### Bug
Trying to use the new "Friendlier Fields" feature in a v0.25.1 Metabase instance.
The underlying database I am querying is Postgres, as is the Metabase internal db.

When I try to remap the field through the Data Model Admin Panel, I am able to change the settings and save them successfully:

<img width="901" alt="screenshot 2017-08-02 19 19 46" src="https://user-images.githubusercontent.com/193187/28899211-c549a9c0-77b7-11e7-9a40-cce063ef8ac3.png">

But the new Display value does not show in my queries, even after triggering a refresh. They still continue to display the raw ID value instead of the "Name" value from, e.g. the "Category" table in this example:

<img width="852" alt="screenshot 2017-08-02 19 22 29" src="https://user-images.githubusercontent.com/193187/28899241-f666bd68-77b7-11e7-82f3-cf27784e7a0d.png">

Am I just not understanding how the feature is supposed to work? Or is this a bug?

I have query caching enabled on my Metabase instance, fwiw.

**Comment by mazameli** [comment] 2017-08-02 23:34
Just to clarify, if you run a raw data query on `Order Item`, does `Category` correctly display the name values instead of numbers?

If so, I think this issue is a dupe of https://github.com/metabase/metabase/issues/5600. Either way, this is revealing a UX "bug" with this feature: users are expecting the remapping to happen when grouping by a remapped FK field (which totally makes sense).

**Comment by sherbondy** [comment] 2017-08-04 16:54
Yes it does, you are correct, this is a dupe! Definitely expecting the display remapping to happen with group by foreign key!

**Closed** 2017-08-04 16:57 UTC
Labels: Duplicate, UX
