### ISSUE TITLE
Sharing a question with a user who doesnt have access to question's database works, but Field Filters are broken

### ISSUE THREAD

**Issue by tommyh** [metabase/metabase#33061] opened 2023-08-09 18:53 UTC
### Describe the bug

When a question is shared with a user who does not have permissions to the question's database, they can view the results of the question (which is good), but they can't see the autocomplete dropdown results from a Field Filter (which is bad).

### To Reproduce

1. Alice is in the "Query Writers Group".  (Alice is seen in the red chrome window, on the left)
2. The Query Writers Group has access to the "Snowflake" metabase database.
3. Tom is in the "Human Resources Query Writers Group".  (Tom is seen in the blue chrome window, on the right)
4. The "Human Resources Query Writers Group" has access to the "Snowflake: Human Resources" metabase database.
5. Tom creates a question called "Tom Hallett Test - HR Question", which uses the "Snowflake: Human Resources" metabase database
6. The question has a "Field Filter" "Dropdown" on it, so that users can filter the results.
7. Tom shares the "Tom Hallett Test - HR Question" question with all users, so Alice has access to view it.
8. Tom can view the question and sees "OPEN EDITOR" (which is good).
9. Alice can view the question and does not see "OPEN EDITOR" (which is good).
10. When Tom views the question and clicks on the "Name" filter, Tom sees autocomplete options (which is good).
11. When Alice views the question and clicks on the "Name" filter, Alice does NOT autocomplete options (which is bad).

Screenshot for step 8 and 9:
![Screen Shot 2023-08-09 at 14 42 00 ](https://github.com/metabase/metabase/assets/348581/56f0814b-a386-4c7c-88a3-9213702fd3a7)

Screenshots for steps 10 and 11:
![Screen Shot 2023-08-09 at 14 44 56 ](https://github.com/metabase/metabase/assets/348581/d766b6c9-a410-4c3a-a8b4-4b9d8a709a42)

Note: I totally understand why this might not work, because a Field filter is essentially a `select distinct column from table`.  So it's disabled for the Alice user for security reasons.  Curious if this could work, or if it's a desired limitation.

One could make a case that the privileged user, Tom, is deciding to create the field filter, thereby knowing what data they are exposing to the less privileged user, Alice, so this "leak" of access is intentional.

### Expected behavior

Step 11 should be: When Alice views the question and clicks on the "Name" filter, Alice should see autocomplete options.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "4.14.238-182.422.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.14"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-07-24",
      "tag": "v0.46.6.2",
      "branch": "patch-google-sso-button",
      "hash": "a4c740a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

low

**Comment by luizarakaki** [comment] 2023-08-11 12:42
Thanks for the detailed bug report. This is a duplicate of #29422.
We want to fix this, but unfortunately this is more complex that we'd like to.

**Closed by luizarakaki** 2023-08-11 12:42 UTC
Labels: Type:Bug, .Needs Triage
