### ISSUE TITLE
Add option to include today's data when filtering date fields

### ISSUE THREAD

**Issue by MaxSavenkov** [metabase/metabase#2496] opened 2016-05-01 11:13 UTC
I'd like to be able to view data for last 30 days, including today's most recent data. Currently, Query Builder provides no way to do that: "This month" includes today's data, but stops on month boundaries, and "Past 30 days" does not include today. Perhaps this options could be added as a checkbox below "Past 7" and "Past 30" days?

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by timiyay** [comment] 2017-02-10 02:57
I support this feature request. We ran afoul of this on day 1 of using Metabase, as our business users intuitively expect "today" to be part of "past 30 days".

**Comment by zaiddabaeen** [comment] 2017-07-27 08:56
This is one of the reasons I go back to writing SQLs rather than using Metabase editor.

**Comment by mazameli** [comment] 2017-12-06 21:34
Closing as duplicate of #4749. Favoring the more recent issue because it has more recent activity as well as designs in it.

**Closed by mazameli** 2017-12-06 21:34 UTC
Labels: Duplicate, Proposal, Query Builder, Query Language (MBQL), Query Processor
