### ISSUE TITLE
Incorrect content in the "View the native query" popup with mongo db

### ISSUE THREAD

**Issue by lbrdnk** [metabase/metabase#30705] opened 2023-05-11 16:20 UTC
### Describe the bug

Content of the "View the native query" popup is incorrect. Same content is presented in the query editor after a conversion to native and is not executable.

### To Reproduce

1. Create mongo db `sample-dataset` database
2. New > Question > `sample-dataset`
3. Select People

<img width="671" alt="Screenshot 2023-05-11 at 15 06 16" src="https://github.com/metabase/metabase/assets/8920752/dd9491af-9532-4e4d-8099-b83d8b4f2034">

5. Open "View the native query"

<img width="668" alt="Screenshot 2023-05-11 at 15 09 02" src="https://github.com/metabase/metabase/assets/8920752/0f5b3993-45af-4cd7-99cc-e0aaa7e2dfef">

Content is incorrect:

```
"[{\"$project\" #ordered/map ([\"_id\" \"$_id\"] [\"address\" \"$address\"] [\"email\" \"$email\"] [\"password\" \"$password\"] [\"name\" \"$name\"] [\"city\" \"$city\"] [\"longitude\" \"$longitude\"] [\"state\" \"$state\"] [\"source\" \"$source\"] [\"birth_date\" \"$birth_date\"] [\"zip\" \"$zip\"] [\"latitude\" \"$latitude\"] [\"created_at\" \"$created_at\"])} {\"$limit\" 1048575}]"
```

Then convert to a native query. Incorrect non executable query appears in query editor.

### Expected behavior

Correct native representation of the query should be presented to the user.

### Logs

Server log:
```
2023-05-11 16:15:11,888 DEBUG middleware.log :: GET /api/user/current 200 35.0 ms (8 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (0 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
2023-05-11 16:15:11,892 INFO public-settings.premium-features :: GETTING ACTIVE USER COUNT!
2023-05-11 16:15:11,894 INFO public-settings.premium-features :: => 1
2023-05-11 16:15:11,905 DEBUG middleware.log :: GET /api/session/properties 200 44.2 ms (5 DB calls) App DB connections: 0/10 Jetty threads: 5/50 (0 idle, 0 queued) (73 total active threads) Queries in flight: 0 (0 queued)
2023-05-11 16:15:11,999 DEBUG middleware.log :: GET /api/collection/root 200 47.7 ms (2 DB calls) App DB connections: 2/10 Jetty threads: 10/50 (0 idle, 0 queued) (76 total active threads) Queries in flight: 0 (0 queued)
2023-05-11 16:15:12,025 DEBUG middleware.log :: GET /api/search 200 56.6 ms (3 DB calls) App DB connections: 2/10 Jetty threads: 9/50 (0 idle, 0 queued) (76 total active threads) Queries in flight: 0 (0 queued)
2023-05-11 16:15:12,026 DEBUG middleware.log :: GET /api/database 200 57.8 ms (3 DB calls) App DB connections: 2/10 Jetty threads: 9/50 (0 idle, 0 queued) (76 total active threads) Queries in flight: 0 (0 queued)
2023-05-11 16:15:12,030 DEBUG middleware.log :: GET /api/bookmark 200 27.6 ms (1 DB calls) App DB connections: 0/10 Jetty threads: 9/50 (0 idle, 0 queued) (78 total active threads) Queries in flight: 0 (0 queued)
2023-05-11 16:15:12,033 DEBUG middleware.log :: GET /api/collection/tree 200 29.6 ms (5 DB calls) App DB connections: 2/10 Jetty threads: 9/50 (0 idle, 0 queued) (79 total active threads) Queries in flight: 0 (0 queued)
2023-05-11 16:15:12,069 DEBUG middleware.log :: GET /api/collection 200 66.9 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (0 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
2023-05-11 16:15:12,210 DEBUG middleware.log :: GET /api/timeline 200 5.0 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 5/50 (2 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
2023-05-11 16:15:12,238 DEBUG middleware.log :: GET /api/database/2/schemas 200 11.7 ms (4 DB calls) App DB connections: 1/10 Jetty threads: 6/50 (2 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
2023-05-11 16:15:12,277 DEBUG middleware.log :: GET /api/table/10/query_metadata 200 47.3 ms (9 DB calls) App DB connections: 0/10 Jetty threads: 5/50 (2 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
2023-05-11 16:15:12,588 DEBUG middleware.log :: GET /api/database 200 16.2 ms (7 DB calls) App DB connections: 0/10 Jetty threads: 5/50 (2 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
2023-05-11 16:15:12,724 DEBUG middleware.log :: GET /api/database/2/schema/ 200 12.9 ms (6 DB calls) App DB connections: 0/10 Jetty threads: 5/50 (2 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
2023-05-11 16:15:15,537 WARN api.common :: Unexpected parameters at [:post "/native"]: [:type :database :query :parameters]
Please add them to the schema or remove them from the API client
2023-05-11 16:15:15,651 DEBUG middleware.log :: POST /api/dataset/native 200 113.4 ms (13 DB calls) App DB connections: 0/10 Jetty threads: 5/50 (2 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
```

### Information about your Metabase installation

```JSON
- Browser: Chrome 113.0.5672.92 (Official Build) (x86_64)
- Database: circleci/mongo:4.2
- Metabase version: master 6c04ac4d39
```

### Severity

It does not affect me, but I would expect it to work as conversion and view are not disabled for mongo.

**Comment by paoliniluis** [comment] 2023-05-30 21:53
dupe of https://github.com/metabase/metabase/issues/31121

**Closed by paoliniluis** 2023-05-30 21:53 UTC
Labels: Type:Bug, .Needs Triage
