### ISSUE TITLE
When using aggregate functions in SQL Query, Pivot Option in Visualisation should be enabled. Or Provide Workaround in Tablular Viz

### ISSUE THREAD

**Issue by dixitshubhashish** [metabase/metabase#25148] opened 2022-08-31 15:25 UTC
**Is your feature request related to a problem? Please describe.**
If a user is writing question with count('column3') and group by column1, column2, Metabase allows users to do a pivot table, but when the same thing user tries to do by writing SQL queries, the functionality of the pivot table is disabled, it should be enabled as sometimes user expects total as well in the end.

If this can't be done for the question, then at least in the "Table" format where the pivot is allowed add an option to show "Total", and "SubTotal". This will solve the pivot problem, and this can be treated as workaround for the former requirements.

**Describe the solution you'd like**
Enable pivot for aggregated queries 

**Describe alternatives you've considered**
Enable total in the tabular visusalisation

**How important is this feature to you?**
It is quite important for most of the users who are using pivot while writing queries and use SQL more often than question.

**Additional context**

**Comment by flamber** [comment] 2022-08-31 15:27
Metabase doesn't know you are doing aggregations in SQL.
https://www.metabase.com/learn/visualization/how-to-create-pivot-tables#how-to-create-pivot-tables-limitations
Duplicate of #19862

**Closed by flamber** 2022-08-31 15:27 UTC
Labels: Type:New Feature, .Needs Triage

**Comment by dixitshubhashish** [comment] 2022-08-31 15:36
@flamber @Metabase can read SQL as a string and then identify the string like count, sum, min, max etc to decide that the user is trying to do aggregate. Even if it is not, you can ask users whether they are trying to aggregate as yes/no pop and let the user decide what to do. Why blocking on such small issues?

**Comment by flamber** [comment] 2022-08-31 15:44
@dixitshubhashish You are misunderstanding how Metabase works. If you think it's a really simple thing to fix, then please submit a PR. But you can create SQL, save, then click "Explore results" to be able to use Pivot Table.
