### ISSUE TITLE
In custom question while selecting columns add a filter for remove all except

### ISSUE THREAD

**Issue by jaindamini1111** [metabase/metabase#16319] opened 2021-06-02 06:16 UTC
**Is your feature request related to a problem? Please describe.**
A lot of times I have to deal with the beginning table where the number of columns is a lot. I know while joining we have an option of selecting no column but there should be an option for the beginning data too.

**Describe the solution you'd like**
A user will have to select at least one column and instead of unchecking the checkboxes for the columns not required we can have a filter where the visualization won't proceed unless at least one column is selected. 

**Describe alternatives you've considered**
Going into the native query mode and selecting required columns from the initial data.

**How important is this feature to you?**
On a scale of 1-10, I would say 9.

**Comment by flamber** [comment] 2021-06-02 09:22
Hi @jaindamini1111 
I don't understand what you trying to do or what you are looking for. Can you explain in more details? Possibly with a screenshot?

**Comment by flamber** [comment] 2021-06-02 09:32
Duplicate of #10460

**Closed by flamber** 2021-06-02 09:32 UTC
Labels: .Needs Triage, Type:New Feature
