### ISSUE TITLE
Sequence also fetched as tables.

### ISSUE THREAD

**Issue by sunnyakaxd** [metabase/metabase#9622] opened 2019-03-28 06:43 UTC
We have recently started using sequences, which are auto-created based on keys, and they will eventually be in thousands to autogenerate next number against a key. These are also being fetched as tables in Data Model (Due to their underlying implementation as tables). Should syncing Sequences be part of a configuration??

- Database: MariaDB 10.3.x
- Metabase version: v0.31.2
- Metabase hosting environment: Docker
- Metabase internal database: MariaDB

**Comment by flamber** [comment] 2019-03-28 07:44
Just for reference, we're talking about this feature in MariaDB - right?
https://mariadb.com/kb/en/library/sequence-overview/

From what I can understand, it is treated like a `table`, but when looking in `information_schema.TABLES.TABLE_TYPE` it's defined as `SEQUENCE`, where as a normal table is `BASE TABLE`, but I don't think Metabase is getting that deep, when sync'ing.

There's a list of known "crufty" tables, which means it's hidden by default, but it sounds like sequences shouldn't even be included as tables - meaning, not even show up in Metabase anywhere.
https://github.com/metabase/metabase/blob/master/src/metabase/sync/sync_metadata/tables.clj

**Comment by sunnyakaxd** [comment] 2019-03-28 08:52
> Just for reference, we're talking about this feature in MariaDB - right?
> https://mariadb.com/kb/en/library/sequence-overview/
Yep

> There's a list of known "crufty" tables, which means it's hidden by default, but it sounds like sequences shouldn't even be included as tables - meaning, not even show up in Metabase anywhere.
Exactly. The data they keep isn't required anywhere except select queries.

**Comment by sunnyakaxd** [comment] 2020-02-17 17:36
Iguess this is fixed.

**Comment by flamber** [comment] 2020-02-17 17:43
@sunnyakaxd 
Can you provide more details on why you think this is fixed? Which version are you now using?
I don't remember seeing any commits that excluded `sequence` tables from the scanning process.
Reopening issue.

**Comment by flamber** [comment] 2020-07-02 15:11
This was likely fixed by the shift from MySQL to MariaDB Connector/J in 0.32.0 - I cannot reproduce on 0.35.4 with /J 2.5.1

**Closed by flamber** 2020-07-02 15:11 UTC
Labels: Administration/Metadata & Sync, Database/MySQL, Priority:P3, Type:Bug
