### ISSUE TITLE
Search during selection of Foreign Key within Data Model

### ISSUE THREAD

**Issue by bohlian** [metabase/metabase#4408] opened 2017-02-20 06:57 UTC
To have search functionality when selecting Foreign Keys within the Data Model section. For very long lists it is very hard to find the FK which you are looking for.

**Comment by siggibjarna** [comment] 2017-04-26 12:57
If implementing search is difficult, it would help a lot to have the FK list in sorted order

**Comment by flamber** [comment] 2019-02-23 00:06
Related to #7586

**Comment by mazameli** [comment] 2019-10-11 23:54
Duplicate of https://github.com/metabase/metabase/issues/2805

**Closed by mazameli** 2019-10-11 23:54 UTC
Labels: .Duplicate, .Proposal, Admin Panel & Setup, Type:UX
