### ISSUE TITLE
Pulses not loading

### ISSUE THREAD

**Issue by dnmabra12** [metabase/metabase#12414] opened 2020-04-28 15:34 UTC
**Describe the bug**
Pulses are not loading or sending due to seemingly random questions within the pulse not loading. The questions themselves do load, just not within the pulse. 

**Logs**

04-14 10:00:30 ERROR middleware.log :: GET /api/pulse/preview_card_info/1986 500 2.1 s (9 DB calls) 
{:message "temporal",

 :type java.lang.NullPointerException,

 :stacktrace

 ["java.base/java.util.Objects.requireNonNull(Unknown Source)"

  "java.base/java.time.format.DateTimeFormatter.formatTo(Unknown Source)"

  "java.base/java.time.format.DateTimeFormatter.format(Unknown Source)"

  "java_time.format$format.invokeStatic(format.clj:50)"

  "java_time.format$format.invoke(format.clj:43)"

  "--> pulse.render.datetime$reformat_temporal_str.invokeStatic(datetime.clj:14)"

  "pulse.render.datetime$reformat_temporal_str.invoke(datetime.clj:13)"

  "pulse.render.datetime$format_temporal_str.invokeStatic(datetime.clj:33)"

  "pulse.render.datetime$format_temporal_str.invoke(datetime.clj:16)"

  "pulse.render.body$fn__32493$format_cell__32498$fn__32499.invoke(body.clj:48)"

  "pulse.render.body$fn__32493$format_cell__32498.invoke(body.clj:45)"

  "pulse.render.body$fn__32573$query_results__GT_row_seq__32578$fn__32579$iter__32580__32584$fn__32585$iter__32618__32622$fn__32623.invoke(body.clj:110)"

  "pulse.render.table$render_table_body$iter__32407__32411$fn__32412$iter__32445__32449$fn__32450.invoke(table.clj:75)"

  "api.pulse$fn__63984.invokeStatic(pulse.clj:166)"

  "api.pulse$fn__63984.invoke(pulse.clj:159)"

  "middleware.auth$enforce_authentication$fn__66723.invoke(auth.clj:14)"

  "routes$fn__68247$fn__68248.doInvoke(routes.clj:56)"

  "middleware.exceptions$catch_uncaught_exceptions$fn__66822.invoke(exceptions.clj:97)"

  "middleware.exceptions$catch_api_exceptions$fn__66819.invoke(exceptions.clj:85)"

  "middleware.log$log_api_call$fn__68625$fn__68626.invoke(log.clj:197)"

  "middleware.log$log_api_call$fn__68625.invoke(log.clj:191)"

  "middleware.security$add_security_headers$fn__66785.invoke(security.clj:121)"

  "middleware.json$wrap_json_body$fn__68328.invoke(json.clj:64)"

  "middleware.json$wrap_streamed_json_response$fn__68346.invoke(json.clj:100)"

  "middleware.misc$maybe_set_site_url$fn__68655.invoke(misc.clj:59)"

  "middleware.session$bind_current_user$fn__63312$fn__63313.invoke(session.clj:209)"

  "middleware.session$do_with_current_user.invokeStatic(session.clj:184)"

  "middleware.session$do_with_current_user.invoke(session.clj:177)"

  "middleware.session$bind_current_user$fn__63312.invoke(session.clj:208)"

  "middleware.session$wrap_current_user_id$fn__63297.invoke(session.clj:161)"

  "middleware.session$wrap_session_id$fn__63241.invoke(session.clj:125)"

  "middleware.auth$wrap_api_key$fn__66731.invoke(auth.clj:27)"

  "middleware.misc$bind_user_locale$fn__68660.invoke(misc.clj:78)"

  "middleware.misc$add_content_type$fn__68641.invoke(misc.clj:29)"

  "middleware.misc$disable_streaming_buffering$fn__68669.invoke(misc.clj:94)"

  "server$async_proxy_handler$fn__68403.invoke(server.clj:70)"

  "server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)"]}

**To Reproduce**
1. Create a question
2. Load question into pulse
3. Will not load (not a consistent error)

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 52.1
- Your operating system: OS X 10.10
- Your databases: Redshift
- Metabase version: 0.35.1
- Metabase hosting environment: Docker

**Severity**
This is effecting several pulses critical to the business.

**Comment by flamber** [comment] 2020-04-28 15:36
Duplicate of #11665 - upvote by clicking :+1: on the first post - and have a look in the comments for possible workarounds until it's fixed.

**Comment by dnmabra12** [comment] 2020-04-28 15:43
I don't believe this is a duplicate. The offending questions do not have date fields.

**Comment by flamber** [comment] 2020-04-28 15:49
@dnmabra12 Okay, it's the exact same error and it's failing on DateTime-functions.
Can you check question 1986 - go to Editor (top-right) and click "View the SQL", which will show if you have any linked tables (via foreign keys in Admin > Data Model), which might be causing this?
Does this happen on every question, no matter which table you're querying?
Does it happen on Native questions like `SELECT 1` ?

**Comment by flamber** [comment] 2020-05-12 17:16
@notrom @markberger Can you help reproduce this issue? Or are you just seeing #11665?

**Comment by notrom** [comment] 2020-05-13 01:17
@flamber I can only reproduce if the question has a datetime column in it that is null. I tried a number of other data types with null values and the pulse still worked, as soon as I add a null datetime it fails. SQL Server as data store, v0.35.3.

It looks like #11665 to me.

**Comment by ctivanovich** [comment] 2020-05-13 04:27
I am unable to receive any pulses, scheduled or tested. It doesn't matter what the data source looks like -- I've tested postgresql and mysql, hand-written queries on tables with and without date fields. I can interact with the bot in the channel, but every request to send a question answer ends with `uh oh...null` from the bot. Let me add that in my case, metabase is deployed in a container running the jar on Google App Engine. It has no trouble accessing the backend in Cloud SQL.

**Comment by flamber** [comment] 2020-05-13 09:43
@notrom Okay, thank you! Closing again, since I'm 99% sure it's #11665.

@dnmabra12 If you can provide steps to reproduce, then please comment.

@ctivanovich You're likely seeing #5380 - or a different issue.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Closed by flamber** 2020-05-13 09:43 UTC
Labels: .Need More Info, Priority:P2, Reporting/Pulses, Type:Bug
