### ISSUE TITLE
Grab table/column description automatically from Redshift

### ISSUE THREAD

**Issue by andrioni** [metabase/metabase#3147] opened 2016-08-08 17:00 UTC
Hi! Redshift has a builtin feature to describe objects using the [`COMMENT` statement](http://docs.aws.amazon.com/redshift/latest/dg/r_COMMENT.html), and it would be great if Metabase could grab them automatically from the database after a sync, with maybe an option to overwrite already existing ones.

One of the easy ways to grab them programmatically is to use the function `obj_description` together with the hidden column `oid` in the `pg_class` and `pg_attribute` tables, e.g.:

```sql
select relname, obj_description(oid) from pg_class where relname = 'mytest';

 relname | obj_description 
---------+-----------------
 mytest  | A test table
 mytest  | 
(2 rows)
```

**Comment by salsakran** [comment] 2016-08-08 17:06
@andrioni I *think* this is a dupe of #3089 
Is a comment the same as a remark?

**Comment by andrioni** [comment] 2016-08-08 20:32
Yeah, comments seem to be the Redshift/Postgres variant.

**Comment by camsaul** [comment] 2016-09-03 00:55
Yup, this is a duplicate. Same thing just slightly different terminology. 

Closing as duplicate of #3089

**Closed by camsaul** 2016-09-03 00:55 UTC
Labels: Duplicate
