### ISSUE TITLE
[MongoDB] Timezone issue when using relative time filters

### ISSUE THREAD

**Issue by anandsiddharth** [metabase/metabase#14233] opened 2020-12-31 07:49 UTC
I am using data source as MongoDB, where I have `createdAt` in each document, it's of date type and is always in UTC (GMT +0) Timezone, I have configured Metabase accordingly to show me these values on IST, it's working as expected. Now the difference is when I set a filter on a specific date the count of rows is different from the one when I set relative date.

## Using on the specific date filter 
I have set a data filter (On Specific Date) to 30th Dec 2020, then the count of rows is 45.

#### What went weird?
Everything seems fine, Data looks perfect as it should be.

## Using on a relative date filter
Now when I change the filter to Previous 1 Day (Do not include today), then the count of rows is 43.

#### What went weird?
1. I can see 2 records of 31st Dec as well. (I didn't select include today, also today has more data).
Those 2 extra records are: December 31, 2020, 2:22 AM, December 31, 2020, 1:44 AM 

2. 4 records went missing, and those are:
    i. December 30, 2020, 12:37 AM
    ii. December 30, 2020, 12:58 AM
    iii. December 30, 2020, 1:38 AM
    iv. December 30, 2020, 1:45 AM

**Assumptions**
I think when using the relative time filter the query is not using the local timezone, the data has a difference of +05:30

### Severity
Low or Medium

### Metabase Diagnostic Info

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.19.0-0.bpo.11-amd64",
    "user.language": "en",
    "user.timezone": "Asia/Calcutta"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.1 (Debian 13.1-1.pgdg100+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-12-17",
      "tag": "v0.37.4",
      "branch": "release-x.37.x",
      "hash": "e0d5287"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Comment by flamber** [comment] 2020-12-31 11:15
I have a feeling it's very related to #10824

**Comment by anandsiddharth** [comment] 2020-12-31 12:23
Not sure!
Here is the native query, It only has a date, I think which should have time as well, in this case, In my opinion, the query should be $gt and $lt, instead of $eq, $gt: should have started of IST day of the selected date, and $lt should be end of IST day of the selected end date.



![Screenshot 2020-12-31 at 5 47 47 PM](https://user-images.githubusercontent.com/6649533/103410216-66fa8500-4b90-11eb-90ee-4b236f2a57b1.png)

**Comment by camsaul** [comment] 2021-06-07 17:09
This might be fixed after #14835 -- need to check.

Otherwise #6439 or #14056 might be necessary to address this

**Comment by mrangelba** [comment] 2023-01-13 00:34
I believe that if you add the timezone in the $dateFromString, it seems to solve the problem.

```
[
  {
    "$match": {
      "$and": [
        {
          "$expr": {
            "$gte": [
              "$created_at",
              {
                "$dateFromString": {
                  "dateString": "2023-01-06T00:00",
                  "timeZone": "Brazil/East"
                }
              }
            ]
          }
        },
        {
          "$expr": {
            "$lt": [
              "$created_at",
              {
                "$dateFromString": {
                  "dateString": "2023-01-13T00:00",
                  "timeZone": "Brazil/East"
                }
              }
            ]
          }
        }
      ]
    }
  }
]
```

**Comment by snoe** [comment] 2023-02-09 17:08
This issue seems to have been fixed in https://github.com/metabase/metabase/pull/14840, [here](https://github.com/metabase/metabase/pull/14840/files#diff-80f8b3e7a16493f91fedaacf81ebc4063ed837396ac8c8ba3752ca2702852b79R234) and [here](https://github.com/metabase/metabase/pull/14840/files#diff-80f8b3e7a16493f91fedaacf81ebc4063ed837396ac8c8ba3752ca2702852b79R268).

The `dateString` emitted by the mongo driver after those commits, are timezone qualified instants like `2023-02-09T00:00Z` that compare properly to `ISODate` values.

My only confusion is @mrangelba recent comment, as I believe this issue was fixed about 2 years ago. Is this still happening? Perhaps there's another code path I haven't been able to find, so any steps to reproduce this in a recent version would be helpful.

**Closed** 2023-02-09 17:13 UTC
Labels: Type:Bug, Priority:P2, Database/Mongo, Querying/Processor, .Correctness, Misc/Timezones, Difficulty:Medium, .Backend

**Comment by anjoshua** [comment] 2023-12-06 09:34
I think this issue has regressed. I found this problem after updating from v0.45.4.3 to v0.47.9.

In v0.45.4.3, I was using `-Duser.timezone=Japan` to set the timezone and that worked as expected. It looks like [since x.46.x](https://github.com/metabase/metabase/pull/27937) MongoDB supports Report Timezone and the Java timezone is no longer having any effect.

Setting Report Timezone to "Japan" displays the data in the correct timezone. But setting the Date Filter to "Today" will use UTC "Today" in the query, like this:

```
{$match: {$and: [{\"report_date\": {$gte: ISODate(\"2023-12-06T00:00:00Z\")}}, {\"report_date\": {$lt: ISODate(\"2023-12-07T00:00:00Z\")}}]} }\r\n
``` 
Since Japan is +9 hours, this is only showing data since 9am today.

Metabase Diagnostic Info
```json
{
  "browser-info": {
    "language": "en",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Japan"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.1 (Debian 16.1-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-12-01",
      "tag": "v0.47.9",
      "branch": "?",
      "hash": "d05b06e"
    },
    "settings": {
      "report-timezone": "Japan"
    }
  }
}
```

(Also, I have tried both "Japan" and "Asia/Tokyo" for timezones, and it's the same)
