### ISSUE TITLE
Question crashes after adding Sort By on Group by field after table joined and aggregate value calclulated

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#30743] opened 2023-05-12 19:38 UTC
### Describe the bug

Question crashes after selecting Sort By when selecting either a Group by or aggregated field in question with left join.

### To Reproduce

1. New + > Question > from Sample Database > Accounts LEFT JOINed to Invoices ON Accounts.ID = Invoices.Account ID
2. Summarize by Sum of Invoices > Payment grouped by Accounts > Source
![image](https://github.com/metabase/metabase/assets/8808703/bf25ac66-3590-4eba-8bd5-3b5a340dc1de)

3. Click Visualize, and bar chart is created
4. Click Query Editor
5. Click Order by > Source
6. Question crashes and becomes unrecoverable
![image](https://github.com/metabase/metabase/assets/8808703/c7af29b2-0d4f-4a1c-9a13-0491ffc4966c)

### Expected behavior

- Expect column sort order to change as selected, and expect question not to crash

### Information about your Metabase installation

- `master` as of 2023-05-12 (broken in stats)
- Not broken in v1.46.2

### Severity

P1: Question crashes and is unrecoverable if not saved prior to crash

### Additional context

- Same thing happens if you start with Invoices and then join Accounts.
- Same thing happens if you try to Order By Invoices > Payment

**Comment by nemanjaglumac** [comment] 2023-05-15 07:04
This seems to be related to joins. Cannot reproduce if I don't join, although I run into a different error (recoverable) without joins.

## No joins
1. New question > Orders
2. Summarize Count of Rows by Total (auto-binned)
3. Click on Sort and choose Total
![image](https://github.com/metabase/metabase/assets/31325167/4fd6cf93-0ffc-4c00-b143-37610c343e05)
4. Visualize

It fails (but the UI is still responsive and it's possible to go back to the notebook editor)
```
Column "PUBLIC.ORDERS.TOTAL" must be in the GROUP BY list;
SQL statement: -- Metabase:: userID: 1 queryType: MBQL queryHash: 681366c14b2bbbba74f1780603918ec37843aebb857a8ad76ad3cd0df2b0a98b
SELECT FLOOR(("PUBLIC"."ORDERS"."TOTAL" / 20)) * 20 AS "TOTAL", COUNT(*) AS "count" [90016-214]
```
The workaround is to visualize without sorting, choose the table and then click on the "total" table header cell. Sort from there and it works.

## With joins (simplified repro steps of the original issue)
1. New question > Orders
2. Left join Products (conditions will auto-populate)
3. Click on Summarize > Count of Rows
![image](https://github.com/metabase/metabase/assets/31325167/b29474ad-a4dc-4f06-a653-84e9ba13faae)
4. The moment you click Total the UI crashes
![image](https://github.com/metabase/metabase/assets/31325167/7a6171bd-af5a-4432-9ff6-8e64f210af26)
```
Uncaught Error: :all is not ISeqable
    at Object.cljs$core$seq [as seq] (core.cljs:1253:1)
    at Function.cljs$core$IFn$_invoke$arity$3 (core.cljs:2498:1)
    at Function.cljs$core$IFn$_invoke$arity$3 (core.cljs:2585:1)
    at Function.cljs$core$IFn$_invoke$arity$4 (core.cljs:2626:1)
    at Function.cljs$core$IFn$_invoke$arity$3 (core.cljs:5275:1)
    at metabase$lib$util$remove_clause (util.cljc:74:1)
    at core.cljs:5390:1
    at Function.cljs$core$IFn$_invoke$arity$5 (core.cljs:5390:1)
    at Object.cljs$core$apply_to [as apply_to] (core.cljs:3917:1)
    at Function.cljs$core$IFn$_invoke$arity$5 (core.cljs:3996:1)
```

**Comment by nemanjaglumac** [comment] 2023-05-15 11:56
The workaround:
1. Click visualize BEFORE you sort
2. In the visualization choose the table
3. Click on the table header cell that you want to sort
4. Sort
5. Save question

DO NOT go back to the notebook editor between steps 4 and 5.

**Comment by nemanjaglumac** [comment] 2023-05-16 07:30
Seems that this is a duplicate of https://github.com/metabase/metabase/issues/30712

**Closed** 2023-05-18 18:43 UTC
Labels: Type:Bug, Priority:P1, .Backend, Querying/GUI, .Reproduced, .Regression/master, .Team/QueryProcessor :hammer_and_wrench:
