### ISSUE TITLE
Subscription email not being sent due to pulse render error

### ISSUE THREAD

**Issue by shamimmirzai** [metabase/metabase#25897] opened 2022-10-12 14:37 UTC
**Bug description**
One of our dashboards which has a email subscription setup is not sending emails in an automated fashion.  I can click the "Send email now" button and that works, but if I wait for the email to be sent on schedule it doesn't work and the log shows an error (below).

**Logs**
[42a1489a-ee97-4002-b8b8-385448b12264] 2022-10-12T15:00:00+01:00 INFO metabase.task.send-pulses Sending scheduled pulses...
[42a1489a-ee97-4002-b8b8-385448b12264] 2022-10-12T15:00:01+01:00 INFO metabase.task.persist-refresh Unpersisting model with card-id 3,591
[42a1489a-ee97-4002-b8b8-385448b12264] 2022-10-12T15:00:01+01:00 ERROR metabase.pulse.render Pulse card render error
TypeError: Cannot read property '1' of undefined
	at <js> Rg(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:390911-390914)
	at <js> r(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:399617-399632)
	at <js> :anonymous(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:398686-399680)
	at <js> l(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:398659-399722)
	at <js> ld(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:398640-399726)
	at <js> a(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:212821-212834)
	at <js> n(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:213839-213844)
	at <js> n.render(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:212170-213890)
	at org.graalvm.polyglot.Value.execute(Value.java:841)
	at metabase.pulse.render.js_engine$execute_fn_name.invokeStatic(js_engine.clj:48)
	at metabase.pulse.render.js_engine$execute_fn_name.doInvoke(js_engine.clj:42)
	at clojure.lang.RestFn.invoke(RestFn.java:490)
	at metabase.pulse.render.js_svg$combo_chart.invokeStatic(js_svg.clj:155)
	at metabase.pulse.render.js_svg$combo_chart.invoke(js_svg.clj:147)
	at metabase.pulse.render.body$lab_image_bundle.invokeStatic(body.clj:600)
	at metabase.pulse.render.body$lab_image_bundle.invoke(body.clj:574)
	at metabase.pulse.render.body$fn__57360$render__57349__57365$fn__57366.invoke(body.clj:630)
	at metabase.pulse.render.body$fn__57360$render__57349__57365.invoke(body.clj:628)
	at clojure.lang.MultiFn.invoke(MultiFn.java:261)
	at metabase.pulse.render$fn__57889$render_pulse_card_body__57894$fn__57898.invoke(render.clj:143)
	at metabase.pulse.render$fn__57889$render_pulse_card_body__57894.invoke(render.clj:133)
	at metabase.pulse.render$fn__57928$render_pulse_card__57933$fn__57934.invoke(render.clj:169)
	at metabase.pulse.render$fn__57928$render_pulse_card__57933.invoke(render.clj:157)
	at metabase.pulse.render$fn__57957$render_pulse_section__57962$fn__57966$fn__57969.invoke(render.clj:201)
	at metabase.pulse.render$fn__57957$render_pulse_section__57962$fn__57966.invoke(render.clj:199)
	at metabase.pulse.render$fn__57957$render_pulse_section__57962.invoke(render.clj:196)
	at metabase.email.messages$render_result_card.invokeStatic(messages.clj:466)
	at metabase.email.messages$render_result_card.invoke(messages.clj:463)
	at metabase.email.messages$render_message_body$fn__59303$fn__59304.invoke(messages.clj:514)
	at clojure.core$mapv$fn__8535.invoke(core.clj:6979)
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$mapv.invokeStatic(core.clj:6970)
	at clojure.core$mapv.invoke(core.clj:6970)
	at metabase.email.messages$render_message_body$fn__59303.invoke(messages.clj:514)
	at metabase.email.messages$render_message_body.invokeStatic(messages.clj:513)
	at metabase.email.messages$render_message_body.invoke(messages.clj:511)
	at metabase.email.messages$render_pulse_email.invokeStatic(messages.clj:540)
	at metabase.email.messages$render_pulse_email.invoke(messages.clj:537)
	at metabase.pulse$fn__78227.invokeStatic(pulse.clj:300)
	at metabase.pulse$fn__78227.invoke(pulse.clj:289)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.pulse$results__GT_notifications$iter__78257__78261$fn__78262.invoke(pulse.clj:352)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$seq__5467.invoke(core.clj:139)
	at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:472)
	at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:471)
	at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:500)
	at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:480)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at metabase.task.send_pulses$fn__83276$send_pulses_BANG___83285$fn__83288$fn__83306$fn__83307.invoke(send_pulses.clj:56)
	at metabase.models.task_history$fn__42164$do_with_task_history__42169$fn__42170.invoke(task_history.clj:113)
	at metabase.models.task_history$fn__42164$do_with_task_history__42169.invoke(task_history.clj:108)
	at metabase.task.send_pulses$fn__83276$send_pulses_BANG___83285$fn__83288$fn__83306.invoke(send_pulses.clj:52)
	at metabase.task.send_pulses$fn__83276$send_pulses_BANG___83285$fn__83288.invoke(send_pulses.clj:51)
	at metabase.task.send_pulses$fn__83276$send_pulses_BANG___83285.invoke(send_pulses.clj:38)
	at metabase.task.send_pulses$fn__83276$send_pulses_BANG___83285$fn__83286.invoke(send_pulses.clj:45)
	at metabase.task.send_pulses$fn__83276$send_pulses_BANG___83285.invoke(send_pulses.clj:38)
	at metabase.task.send_pulses.SendPulses$fn__83342.invoke(send_pulses.clj:96)
	at metabase.models.task_history$fn__42164$do_with_task_history__42169$fn__42170.invoke(task_history.clj:113)
	at metabase.models.task_history$fn__42164$do_with_task_history__42169.invoke(task_history.clj:108)
	at metabase.task.send_pulses.SendPulses.execute(send_pulses.clj:82)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

**Expected behavior**
I expect the email to be sent out on schedule.

**Severity**
It's a daily email for management and it's not being sent right now.  I can't figure out how to get it to work.  Only alternative I have is to write a program to generate this report using code.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "4.14.225-169.362.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.8"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-09-29",
      "tag": "v0.44.4",
      "branch": "release-x.44.x",
      "hash": "382d728"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

Thanks

**Comment by flamber** [comment] 2022-10-12 14:41
Duplicate of #20752

**Closed by flamber** 2022-10-12 14:41 UTC
