### ISSUE TITLE
Admin panel database view blows up in an unacceptable way if Database `details` is `NULL`

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#25715] opened 2022-09-29 19:06 UTC
See #25658

Theoretically we disallow people from creating or updating Databases with invalid `details`, but this is not enforced in the application database schema itself; in some cases when using SerDes v2 it is possible to create a Database without `details`. That is probably a bug. Either way, the error behavior in the frontend client in this situation is unacceptable from a user perspective; we **need** to wrap the whole thing in some sort of `try-catch` to handle **unexpected** errors like this one.

To repro: 

1. Add a row to the `metabase_database` Table in the application database with `NULL` `details` or change an existing row
2. Visit the admin panel details view for that Database e.g. http://localhost:3000/admin/databases/2
3. Frontend application blows up with no error messages at all

   <img width="777" alt="image (1)" src="https://user-images.githubusercontent.com/1455846/193119984-3c000f6d-060a-4eb0-b3dc-98ce056ec1f5.png">

The error itself is some sort of "cannot access property of undefined" error. But the problem isn't the error itself, but that we have no fallback unexpected error handling code. There will always be unexpected errors like these, and we need to handle them in some way better than letting it crash with a blank screen.

I would expect it to show some sort of "unexpected error" message/graphic, preferably with a details toggle and maybe a "please report this" and a button to open a GH issue. 

This should be done globally somewhere (perhaps in our component base class?) so we can eliminate blank screen situations altogether. I don't want to see a one-off fix for this specific page leaving the rest of the application open to the same issues.

**Comment by nemanjaglumac** [comment] 2022-10-10 20:18
This is what I see now (after 25717 has been merged) when I remove `details` property from the response in Cypress.
![image](https://user-images.githubusercontent.com/31325167/194945491-7074db40-6302-42a9-af12-ab70c1239e93.png)

Would that constitute a valid reproduction?
I know it's not what @camsaul asked for about better error handling but it at least prevents blank page from happening again (at least for this scenario).

**Comment by nemanjaglumac** [comment] 2023-02-07 23:56
@camsaul this issue has regressed since [my last comment](https://github.com/metabase/metabase/issues/25715#issuecomment-1273775036) in October, 2022.
The page again blows up completely.

See [E2E repro](https://github.com/metabase/metabase/pull/28138) for more details.

**Closed** 2023-02-27 18:50 UTC
Labels: Type:Bug, Priority:P2, .Frontend, .Reproduced, .Regression, Administration/Databases
