### ISSUE TITLE
Not able to remove or combine charts in a dashboard

### ISSUE THREAD

**Issue by subodhpareek18** [metabase/metabase#3313] opened 2016-09-05 13:19 UTC
### Bug Report Info

Not able to remove certain types of charts from the dashboard after getting into editing mode. The `X` icon only appears for table view and not for something like an area view.

Also the ability to combine multiple questions of similar types has disappeared. It was a really useful feature to have while creating funnels by combining multiple bar charts, etc.

One final thing I have noticed is the tool gets stuck at _Doing Science_ at times, and when I open and close the dev tools, it starts working again. Not sure what the reason for that is.
-  I'm using this browser: Chrome
-  My computer's OS is: Windows 10
-  I'm running Metabase: On AWS (via Docker)
-  My data is in a database of this type: MongoDB
-  I'm using Metabase version: 0.19.2

**Comment by andreeib** [comment] 2016-09-05 19:47
Hey @zusamann this is fixed in 0.19.3:
https://github.com/metabase/metabase/releases/tag/v0.19.3

**Comment by zusamann** [comment] 2016-09-05 20:27
Hey @andreeib I actually did update to 0.19.3 and these are my findings:

> Not able to remove certain types of charts from the dashboard after getting into editing mode. The X icon only appears for table view and not for something like an area view.

> Also the ability to combine multiple questions of similar types has disappeared. It was a really useful feature to have while creating funnels by combining multiple bar charts, etc.

These two buttons have started appearing again, but I'm not able to click on them with my mouse. Though they work fine by touching them (I have a laptop with touchscreen).

> One final thing I have noticed is the tool gets stuck at Doing Science at times, and when I open and close the dev tools, it starts working again. Not sure what the reason for that is.

This is something I'm still able to see. Can you tell me why this could occur?

**Comment by andreeib** [comment] 2016-09-06 08:20
Problem 1:
I tested in Chrome on Windows 7 and indeed it's not working, it does work in Firefox.
I also tested in Chrome and Firefox on Ubuntu and it works in both.

Problem 2:
I can't replicate this problem. Do you have any errors in the console?

**Comment by HelenMertes** [comment] 2018-05-23 09:59
I have the same problem in Chrome, I cannot edit questions in the dashboard by clicking on the settings button - nothing happens. It works in Firefox though.


Your browser and the version: Chrome Version 66.0.3359.181 
Your operating system: Windows 10
Your databases: BigQuery
Metabase version: v0.29.0
Metabase hosting environment: Heroku

**Comment by liransmartlighthouse** [comment] 2018-08-30 22:03
I have the same problem in Chrome, I cannot edit questions in the dashboard by clicking on the settings button - nothing happens. It works on my Macbook using Google Chrome (Chrome Version Version 68.0.3440.106 (Official Build) (64-bit))

Your browser and the version: Chrome Version Version 68.0.3440.106 (Official Build) (64-bit)
Your operating system: Windows 10
Your databases: BigQuery
Metabase version: You're on version v0.30.1 Built on 2018-08-20
Metabase hosting environment: Google Cloud Kubernetes

**Comment by jornh** [comment] 2018-08-31 02:32
Related #7246

Duplicate of #2187 

@subodhpareek18 If you agree it’s the same issue, please close this issue and add your 👍 vote directly on the initial post over there to keep it neat and tidy in here.

There’s a proposed workaround in 
https://github.com/metabase/metabase/issues/7246#issuecomment-391287318

**Comment by mazameli** [comment] 2019-09-30 21:09
This should be fixed by #10206 in version 0.32.10 or later (current latest is v0.33.3), so I'm going to close this, but please let us know if you're still experiencing it.

**Closed by mazameli** 2019-09-30 21:09 UTC
Labels: OS:Windows
