### ISSUE TITLE
Map does not work with custom SQL query

### ISSUE THREAD

**Issue by Tobi28** [metabase/metabase#9346] opened 2019-01-30 12:10 UTC
Hi,

as soon as I try to use an own SQL query to be shown in a map, a javascript error occurs and nothing can be done anymore. I tried it with different browsers: Chrome (71), Firefox (, Edge.
Operating System: Windows 10
Official docker image used as installation (version: 0.31.2)

It is easy to reproduce:
- Take table People from the Sample Dataset
- Select map
- Map is opened and that works
- Now modify it to an SQL query
- After that, the map is not shown any more and the settings cannot be adjusted. Javascript error is thrown:
`app-main.bundle.js?78262faa1c529a733077:5 Uncaught TypeError: Cannot read property 'map' of undefined
    at t.value (app-main.bundle.js?78262faa1c529a733077:5)
    at u._renderValidatedComponentWithoutOwnerOrContext (vendor.bundle.js?78262faa1c529a733077:145)
    at u._renderValidatedComponent (vendor.bundle.js?78262faa1c529a733077:145)
    at u.performInitialMount (vendor.bundle.js?78262faa1c529a733077:145)
    at u.mountComponent (vendor.bundle.js?78262faa1c529a733077:145)
    at Object.mountComponent (vendor.bundle.js?78262faa1c529a733077:83)
    at J.mountChildren (vendor.bundle.js?78262faa1c529a733077:145)
    at J._createInitialChildren (vendor.bundle.js?78262faa1c529a733077:145)
    at J.mountComponent (vendor.bundle.js?78262faa1c529a733077:145)
    at Object.mountComponent (vendor.bundle.js?78262faa1c529a733077:83)'

Thank you,
Tobias

**Comment by flamber** [comment] 2019-01-30 15:28
@Tobi28 
I can replicate some of this. Using People, group by Name/Longitude/Latitude and Limit 100. This works fine in QB and when I "Convert this question to SQL", then I still see the map until I click "Get Answer".
Then it just displays an error: "Please select a region map."
And when I click "Edit Settings", then in browser console I see this error: `TypeError: T is undefined`
But if I click the gear-icon instead of "Edit Settings", then I can set the Map Type and everything works.

**Comment by Tobi28** [comment] 2019-01-31 09:58
Hi,
thank you, that works! Strange, I tried exactly this a few days ago and had also some problems with that approach... But I cannot reproduce it any more.

**Comment by Tobi28** [comment] 2019-01-31 10:39
I have a similar problem now with the grid map. I autopin latitude and longitude from People in the sample data set. The grid map is shown perfectly.
But when I convert it to sql, the grid map cannot be configured properly (it says that it needs classified longitudes/latitudes). Although this is the automatically created query, that I used before. Thanks!

**Comment by flamber** [comment] 2019-04-10 07:57
@salsakran This issue is still valid in 0.32.4 - updated my [previous comment](https://github.com/metabase/metabase/issues/9346#issuecomment-458985874) to make it more clear

**Comment by benoror** [comment] 2019-04-15 21:22
Getting the same bug with any kind of question, custom and native query

**Comment by flamber** [comment] 2019-04-15 21:43
@benoror If you're getting the same error, how do you reproduce it with Custom Question?

**Comment by calfzhou** [comment] 2019-04-29 09:38
Just upgraded to Metabase 0.32.5.0, the same issue, for any question.

@flamber's method works, "click the gear icon near 'Visulation'".  +1

**Comment by ribeirojose** [comment] 2019-05-02 03:19
Also getting the same bug. Tried replacing country names with ISO 3166-1 alpha-2 codes, but this is ineffective. The `Edit Settings` button changes on hover, but is disabled.

**Comment by flamber** [comment] 2020-05-25 13:20
I cannot reproduce on 0.35.3 - think it was fixed in 0.32.9 or 0.33.0 with the new UI.

**Closed by flamber** 2020-05-25 13:20 UTC
Labels: Priority:P2, Querying/Native, Type:Bug, Visualization/
