### ISSUE TITLE
[PROPOSAL] Assign table segments permissions to group/user

### ISSUE THREAD

**Issue by FallenChromium** [metabase/metabase#8862] opened 2018-11-06 10:34 UTC
Well, title tells it all. Feels a bit wonky if I'll count that awesome user key-value system will be there soon, but for now it feels reasonable way to implement row-level security to tables. I think it can look like assigning rights to sub-collection, but there's a problem then - to make this look easy to user there should be only one table segment assigned to it, so it will look just like a table and not sets of tables. It's just an idea and it's really interesting what users, contributors and developers think about it.

**Comment by salsakran** [comment] 2018-11-06 19:19
closing this as a dupe of #2824 

In general, if you intend to propose a solution to a problem described in an issue, we'd rather all the discussion happen under the issue.

**Closed by salsakran** 2018-11-06 19:19 UTC
