### ISSUE TITLE
Multi series charts Y-Axis control and Colors of stacked bars

### ISSUE THREAD

**Issue by robinfrick** [metabase/metabase#2178] opened 2016-03-17 10:24 UTC
I have a chart where I combine two bar charts into one. One is a single Bar chart which is total and the other is a stacked bar chart with a subgroup of the total. 
Here I experience two problems:
1. The Y Axis are slightly different. I'd prefer if they could be both on the same Y Axis as I want to compare the two. As you can see in the screenshot the highest value for the stacked series is around 5600 and for the single (blue) series at ca 6200. Those are very close together and can easily be on the same axis without dwarfing the smaller series.
2. Colors. The Stacked chart consists of a red and yellow part. When combining it with the blue series it turns all red-ish with the former red part being in a brighter red and the former yellow part in a dark red. These colors look out of place in Metabase, as it deviates from the regular colors and also makes it really hard to distinguish on first glance between the two reds (the actual chart I had this problem with was a 30 day chart, I was just too lazy now to think of enough values for 30 day mock data I can post publically here. In that case the bars are far smaller.).

The combined chart:
![image](https://cloud.githubusercontent.com/assets/8144392/13843149/463f93ea-ec32-11e5-9997-fc18dc71ec46.png)

The correctly colored stacked bar charts before combining: 
![image](https://cloud.githubusercontent.com/assets/8144392/13843199/8bf9b622-ec32-11e5-9a77-8b899648150b.png)

If this is a bug report, please fill in the blanks:
-  I am using the Chrome browser.
-  My computer's OS is Mac.
-  I'm running Metabase v0.15.1.on AWS 
-  My database is postgres.

**Comment by agilliland** [comment] 2016-03-18 18:32
The colors portion of this sounds like it's related to #2094

**Comment by tlrobinson** [comment] 2016-03-18 19:05
What would you expect to see when adding a combination of stacked and non-stacked bar charts? I feel like it could be fairly confusing to see a combination of the two.

Additionally, I believe the fix I implemented for #2094 actually makes it impossible to make dashboard-level multiseries (overlaying individual cards) out of card-level multiseries cards (i.e. dimension-dimension-metric or dimension-metric-metric+).

**Comment by tlrobinson** [comment] 2016-08-13 00:23
@robinfrick I believe # 1 was resolved with the addition of the chart settings in 0.19

I'm still not sure whether we should even attempt to support a combination of stacked and side-by-side bar charts.

**Comment by flamber** [comment] 2021-11-06 14:43
Closing, I cannot reproduce this on 0.41.1.

**Closed by flamber** 2021-11-06 14:43 UTC
Labels: Visualization/, Visualization/Chart Settings
