### ISSUE TITLE
Excel/CSV export in application embed dashboard lose custom columns name

### ISSUE THREAD

**Issue by awatrelotwoop** [metabase/metabase#24633] opened 2022-08-05 14:37 UTC
**Describe the bug**
In an application embed dashboard, when you export a specific question with custom column names, column names are not keep in Excel or CSV downloaded file 

**To Reproduce**
1. Create a question with table view
2. Change the name of a column using metabase UI column formatting
3. Create a dashboard with this question
4. Embed this dashboard in a application
5. In this application, export the result of the question in Excel/CSV using cloud pictogram on the top right
6. In the resulting file, custom column's name disappear

**Expected behavior**
In an application embed dashboard, when you export a specific question with custom column names, custom columns name are in the resulting file.

**Information about your Metabase Installation:**

- Chrome 103.0.5060.134
- OSX 12.4
- BigQuery
- Metabase version: v0.43.4.2

**Severity**
low

**Comment by flamber** [comment] 2022-08-05 14:46
Duplicate of #17753

**Closed by flamber** 2022-08-05 14:46 UTC
Labels: Type:Bug, .Needs Triage
