### ISSUE TITLE
Bug: visualization line generate a graph with nonexistent value

### ISSUE THREAD

**Issue by gusgustavo** [metabase/metabase#6668] opened 2018-01-09 13:53 UTC
Hi, when I use "visualization line" to generate a graph, it shows some spikes that actually doesn't exist.

Example:
![visualization_line_metabase02702](https://user-images.githubusercontent.com/15200517/34723886-2def1200-f533-11e7-92ff-ac5c7f21d149.png)

Maximum of Humidity:

![max_humidity_2018](https://user-images.githubusercontent.com/15200517/34723905-3986cd06-f533-11e7-8368-068568884452.png)

My data sample imported in MongoDB:

```
humidity,temperature,timestamp
66.0,19.7,2018-01-09 01:48
53.4,24.8,2018-01-09 01:18
64.0,20.3,2018-01-09 00:47
56.5,23.7,2018-01-09 00:17
65.8,21.1,2018-01-08 23:47
53.7,23.7,2018-01-08 23:20
59.2,21.6,2018-01-08 23:17
64.2,18.7,2018-01-08 23:17
62.5,19.6,2018-01-08 22:50
50.1,25.0,2018-01-08 22:20
64.6,18.7,2018-01-08 21:50
51.9,24.0,2018-01-08 21:20
57.2,21.7,2018-01-08 20:50
59.0,20.9,2018-01-08 20:20
52.3,24.0,2018-01-08 19:50
63.4,19.4,2018-01-08 19:20
49.8,25.5,2018-01-08 18:50
65.9,18.9,2018-01-08 18:20
52.9,24.4,2018-01-08 17:50
63.9,19.8,2018-01-08 17:20
56.4,22.7,2018-01-08 16:50
57.5,22.3,2018-01-08 16:20
60.0,21.1,2018-01-08 15:50
53.3,24.1,2018-01-08 15:20
```

Database Driver: MongoDB.
Metabase version: 0.27.2
Metabase hosting: Linux/Debian Stretch
Metabase internal database: default

**Comment by salsakran** [comment] 2018-02-02 00:45
This happens when we find data that is duplicated. 

My hunch is that if you hover over the triangular warning icon, you'd see a message to that affect. Given that we can't know whether to sum, average or use the last data point for that timestamp, we're using the default of our underlying library.

Closing as a duplicate of #2913

**Closed by salsakran** 2018-02-02 00:45 UTC
