### ISSUE TITLE
Model column re-ordering forces you to save as a new model

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#30353] opened 2023-04-25 08:21 UTC
### Describe the bug

Model column re-ordering forces you to save as a new model

### To Reproduce

1. Go to New Question -> Orders -> Save -> Turn into a Model
2. Go to Settings -> Move a column around and try to Save -> You will get prompted to Save a new Model rather than replace existing one

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/110378427/234216628-647b2cc5-47d9-4006-a4b9-810b1ba1e837.png">

### Expected behavior

Allow to either create a new Model or replace existing one

### Logs

None

### Information about your Metabase installation

```JSON
Able to replicate in 1.45.3.1 and `master`
```

### Severity

Medium

### Additional context

The only workaround seems to be to reorder columns from the `Edit metadata section`

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/110378427/234217069-1da0c098-e3d1-4f98-a155-455d8c06c6e3.png">

NOTE:

This doesn't happen in case there is a question and not a model

**Comment by brunobergher** [comment] 2023-05-02 18:23
How is this a bug? It's working as intended, no? Once a model is created, it behaves similar to a table, in that any changes you make to the table viz are a new viz, and not related to the model at all.

**Comment by Tony-metabase** [comment] 2023-05-03 07:42
If that is the case then we can close the ticket.

But I need to add that there is an aspect of confusion here, let me explain. The problem with that logic is that you can add the Model to a Dashboard while you cannot add a table to a Dashboard. So at face value they look completely different. Why would i have the option to add a datasource (a model) to a dashboard?

So once you create a Model we have to make it clear that this ends up being a datasource. Since at first glance it looks like a table visualisation (as i mentioned I am able to add it to a Dashboard) and that is the case why the customer got confused but I have to say that even I got confused, and asked myself why is metabase prompting a new save when I am simply re-ordering the columns. 

But i get your point, so feel free to close this issue.

**Comment by brunobergher** [comment] 2023-05-03 11:56
You shouldn't be able to add a model to a dashboard. We've had many discussions about it on Slack, though not conclusive enough, clearly.

I'll close this one and move the "only viz in dashboards" aspect of it forward.

**Closed by brunobergher** 2023-05-03 11:56 UTC
Labels: Type:Bug, Priority:P2, Visualization/, Querying/Models, .Team/QueryBuilder :abacus:
