### ISSUE TITLE
Filtering on models with links that have the same field name generates invalid SQL

### ISSUE THREAD

**Issue by mogest** [metabase/metabase#25370] opened 2022-09-12 20:23 UTC
**Describe the bug**
When filtering on a model using the question editor, the generated SQL is invalid because it uses the column name of the linked field instead of the column name from the model's SQL.

**Logs**
n/a

**To Reproduce**
1. Create a model, enter SQL which pulls from two tables with the same column name (`name` for the example below).  Alias the two names differently.
2. Using the metadata page, link the columns up to their respective source tables.
3. Save the model
4. Click on the Filter button 
5. Add a filter for one of the names (it correctly brings up values from the linked table)
6. Click "apply filters"
7. Error message appears: "There was a problem with your question"

**Screenshots**
![image](https://user-images.githubusercontent.com/23133/189750711-2683a7c2-3ad6-4564-91fa-a0269b833c46.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Safari 15.6.1
- Your operating system: MacOS 12.5.1
- Your databases: PostgreSQL
- Metabase version: 0.44.2
- Metabase hosting environment: Kubernetes
- Metabase internal database: PostgreSQL

**Severity**
It's blocking our ability to use models.

**Additional context**
Here's the SQL it generated:

```
SELECT "source"."interaction_at" AS "interaction_at", "source"."student_token" AS "student_token", "source"."student_name" AS "student_name", "source"."employer_token" AS "employer_token", "source"."employer_name" AS "employer_name", "source"."organisation" AS "organisation", "source"."organisation_slug" AS "organisation_slug", "source"."rating" AS "rating", "source"."tags" AS "tags", "source"."notes" AS "notes"
FROM (select
    interactions.interaction_at at time zone 'utc' at time zone 'Pacific/Auckland' as interaction_at,
    students.token as student_token,
    students.name as student_name,
    employers.token as employer_token,
    employers.name as employer_name,
    organisations.name as organisation,
    organisations.slug as organisation_slug,
    rating,
    tags,
    notes
from
    interactions
    join employers on employers.id = interactions.employer_id
    join organisations on organisations.id = employers.organisation_id
    join students on students.id = interactions.student_id
order by
    interactions.interaction_at desc) "source"
WHERE "source"."name" = 'Student Name'
LIMIT 1048575
```

The "source" SQL is my custom SQL used to make the model.  Everything else was generated by the Question generator.  The problem is on the second to last line: I selected a filter on student name, so that line should have read:

```
WHERE "source"."student_name" = 'Student Name'
```

It doesn't seem to happen if I filter on things that aren't "name", e.g. the `organisation_slug`—that works fine.

**Comment by flamber** [comment] 2022-09-13 08:08
Duplicate of #22715

**Closed by flamber** 2022-09-13 08:08 UTC
Labels: Type:Bug, .Needs Triage
