### ISSUE TITLE
Data Sync Issue - Scheduled Job Sync Fails  - 'Triggers for metabase.task.sync-and-analyse.job'

### ISSUE THREAD

**Issue by Suchithra-Suresh** [metabase/metabase#44194] opened 2024-06-14 06:45 UTC
**Description:**
Data is not syncing as per scheduled timing from the database to Metabase, resulting in the latest data not being updated in the reports and dashboards. This issue also leads to a slowdown in Metabase performance. Monitoring shows no CPU or memory issues, but restarting the service resolves the problem temporarily. This recurring issue is impacting Metabase usage, making it difficult to restart the service every time. 

**Expected Behavior:**
The latest data should sync from the database to Metabase according to the schedule, and the reports and dashboards should be updated without any performance degradation.

**Actual Behavior:**
Data does not sync as scheduled.
Reports and dashboards do not reflect the latest data.
Metabase performance degrades.
Issue temporarily resolves upon restarting the service.

**Screenshots:**
![image](https://github.com/metabase/metabase/assets/172746072/74960663-fec9-44a3-9e23-bad66264e152)
As per the attached screenshot, the job with the key metabase.task.sync-and-analyze.job is reflecting a state of 'Blocked', while other job states are normal. If this is causing the issue, please guide us on how to resolve it.

**Severity:**
How severe an issue is this bug to you? 
It is blocking our usage of Metabase due to Performance Degradation.

**Note:**
Screenshots, logs, or additional context can be provided if needed.

**Metabase Diagnostic Info:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "11.0.22+9-LTS-219",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://openjdk.java.net/",
    "java.version": "11.0.22",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "11.0.22+9-LTS-219",
    "os.name": "Linux",
    "os.version": "3.10.0-1062.9.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Kolkata"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres",
      "oracle",
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.8"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-07",
      "tag": "v0.47.1",
      "branch": "release-x.47.x",
      "hash": "bd278b9"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}

**Comment by darksciencebase** [comment] 2024-06-14 09:08
@Suchithra-Suresh could you see if the issue is still there with a newer version like 49.16?

**Comment by Suchithra-Suresh** [comment] 2024-06-14 09:45
We haven't checked it yet, but we have been facing this issue recently. Could you please guide us on how to troubleshoot this?
Is this a known issue? If yes, could you please explain it to us?

**Comment by qnkhuat** [comment] 2024-06-14 10:41
It's often hard for us to debug an older version, especially when you're 3 major versions apart from the latest. 

If feels like what you're seeing here is this issue: https://github.com/quartz-scheduler/quartz/issues/145.

Could you give us a dump of this query?

```sql
select * from qrtz_triggers where job_name = 'metabase.task.sync-and-analyze.job';
```
Before and after you restart Metabase?

And also another dump of the task history.

```sql
 select * from task_history where started_at > current_date - interval '14 days' order by started_at desc;
```

**Comment by Suchithra-Suresh** [comment] 2024-06-14 15:12
Hi ,
Please do find the Dump details here ,
[Metabase Trigger job details.xlsx](https://github.com/user-attachments/files/15839973/Metabase.Trigger.job.details.xlsx)

**Comment by qnkhuat** [comment] 2024-06-17 05:43
I suspect this is a performance issue. Here is what I see:
- You have 49 dbs, out of which, 36 dbs are being synced on the 14th. So it crosses out the quartz#145 bug.
- On 13th, your instance ran 68 hours of background jobs in total
- You also mentioned the overall performance of Metabase is degraded

So it's possible that some DBs are not being synced because the background thread pool is too busy.

I suggest you try these options:
- Upgrade to the latest MB version, we have lots of performance improvements on 49
- Scale up your instance
- Give quartz a bigger thread pool by running with `-Dorg.quartz.threadPool.threadCount=20` (the default is 10)

**Comment by Suchithra-Suresh** [comment] 2024-06-17 07:12
Thank you for the suggestions! I appreciate the guidance.

I will proceed with upgrading to the latest MB version to leverage the performance improvements in version 49. 
Additionally, I will scale up the instance and give Quartz a bigger thread pool by running with -Dorg.quartz.threadPool.threadCount=20.

I'll let you know how it works post-upgrade.

Thanks again!

**Comment by qnkhuat** [comment] 2024-06-21 03:41
@Suchithra-Suresh how is it going?

**Comment by Suchithra-Suresh** [comment] 2024-06-24 10:05
Hi Team, 

We have installed version 49 and are currently testing it. In the meantime, could we get information on the basic database configuration and instance setup for version 49? This information will help us scale up our instance.

**Comment by qnkhuat** [comment] 2024-06-24 12:10
Please take a look at https://www.metabase.com/learn/administration/metabase-in-production ?

**Comment by qnkhuat** [comment] 2024-07-09 14:18
@Suchithra-Suresh any progress?

**Comment by Suchithra-Suresh** [comment] 2024-07-10 12:20
Hi Team, 

Thank you for inquiring. Currently, we are monitoring version 0.49 with an increased pool size and threads. We need some more time for testing and will reach out if we encounter any issues.

**Comment by qnkhuat** [comment] 2024-07-31 02:21
I'll close this, as it's been a while. Please re-open if you encounter this issue again.

**Closed by qnkhuat** 2024-07-31 02:21 UTC
Labels: Type:Bug, Priority:P2, .Performance, Administration/Metadata & Sync, .Backend, .Team/BackendComponents
