### ISSUE TITLE
Free text on Dashboard and custom CSS triggers

### ISSUE THREAD

**Issue by skuliaxe** [metabase/metabase#6048] opened 2017-09-26 16:16 UTC
### Feature requests

**1. Free Text**
I would like to see and option for "Free text" on a Dashboard. For example where "Customer X", "New Tickets" and "Open Tickets" below are free text field and the numbers are Metbase Questions.

                                New tickets            Open Tickets
"Customer A"                  5                             10
"Customer B"                  1                              8
"Customer C"                 10                           50

**2. Custom CSS based on Dashboard data in "Number" type**
Additionally, It would be great to have customer CSS triggers for when the Metabase Questions are below, equal to or greather than a set value.

For example, if "Customer A" number of new tickets > 10, then the number 10 would turn red. If the umber is greather than 20, then Red + Flashing.

Example (from a manually built system):
![image](https://user-images.githubusercontent.com/31598328/30871298-a0beea02-a2e6-11e7-9a4b-950f0380ef08.png)

**Comment by mazameli** [comment] 2017-09-26 17:03
1 is a duplicate of https://github.com/metabase/metabase/issues/3221 and 2 is very similar to  https://github.com/metabase/metabase/issues/4121

**Closed by mazameli** 2017-09-26 17:03 UTC
Labels: Duplicate
