### ISSUE TITLE
Integrate metabase with AI models

### ISSUE THREAD

**Issue by e-gaulue** [metabase/metabase#44214] opened 2024-06-14 13:15 UTC
**Describe the solution you'd like**
 * 1rst stage
Learn how the dataware house is structured. Generate information schema from the data field. Allow admins to help it understand (training).
Allow to build query in natural langage: "I want to get all my orders of the last year" 
 * 2nd stage
Help users to present their data using natural language: "I want in a bar chart the number of order each month"
 * 3nd stage
Mix them all: "I want a chart with the number of order by month this year compared with last year."

**Describe alternatives you've considered**
SQLAI. Excel Copilote. PandsAI. MindsDB.

**How important is this feature to you?**
Ready to pay for, while now we are on Free on promise system.

**Comment by samtuke** [comment] 2024-10-05 14:00
I would guess most Metabase users want AI features. Any news?

**Comment by paoliniluis** [comment] 2024-10-07 05:37
Please check our roadmap

**Comment by mjftw** [comment] 2024-10-11 12:01
Just to add to this - this is also a feature my company is likely to be willing to pay for!

**Comment by brunobergher** [comment] 2024-12-30 15:43
Duplicate of #38272

**Closed by brunobergher** 2024-12-30 15:43 UTC
Labels: Type:New Feature, .Needs Triage
