### ISSUE TITLE
Why decimal value is shown as an integer value in dashboard?

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#6045] opened 2017-09-26 10:41 UTC
- Your browser and the version: Chrome 60.0.3112
- Your operating system: OS X 10.10.4
- Your databases: MySQL
- Metabase version: 0.24.1
- Metabase hosting environment: Linux

I have added a single value widget to Metabase dashboard that shows a single value. It is a decimal value and when I get the same query in question section it is shown in decimal format like `10.52`. When I add this question to dashboard it is shown as integer. **In setting section** of the question I changed number of decimal places to 2 as below:

![screen shot 2017-09-26 at 2 10 46 pm](https://user-images.githubusercontent.com/6417083/30856220-9038b2ac-a2c4-11e7-85e8-3814aa6ea447.png)

But again it is shown as int. What is the problem? is this a bug?

**Comment by salsakran** [comment] 2017-09-29 20:00
can you screenshot it? Is this in a chart, a table cell, or something else?

**Comment by alirezastack** [comment] 2017-10-01 12:53
It is set to table, but as it has a single value it is displaying one big number.

**Comment by alirezastack** [comment] 2017-10-09 11:36
Is there any plan for the issue to get fixed?

**Comment by flamber** [comment] 2019-02-17 01:45
Hi @alirezastack 
I cannot reproduce your issue on 0.31.2 - I've tried adding as Number and Table, but I can format the decimal value every time - unless I specifically cast it as a string.
Could you test the new version of Metabase, which also has a lot of new formatting options?

**Comment by flamber** [comment] 2020-03-13 20:25
Closing, since I cannot reproduce on 0.34.3

**Closed by flamber** 2020-03-13 20:25 UTC
Labels: .Need More Info, Priority:P3, Type:Bug, Visualization/
