### ISSUE TITLE
Cannot find source table when using custom field on two joined questions

### ISSUE THREAD

**Issue by attaxia** [metabase/metabase#22235] opened 2022-04-29 08:16 UTC
**Describe the bug**
When joining two questions that end with a summary into a new question, the two outcomes of the joined queries can't be summed. In addition the query builder UI shows wrong labels.

**Logs**
[server log](https://github.com/metabase/metabase/files/8589245/server.log)

**To Reproduce**

Create and save the following questions (using the sample database):
![Screen Shot 2022-04-29 at 10 34 30](https://user-images.githubusercontent.com/4743303/165911091-0cea23b3-2c7e-432c-8e63-04c3e66b6284.png)
![Screen Shot 2022-04-29 at 10 34 41](https://user-images.githubusercontent.com/4743303/165911097-388c5e3d-91e9-49dc-adc2-ce935427e6ae.png)

Now, the goal is to make a new question from the people table, and join in the above two queries to sum up the two numbers as "total orders". Please note that in the video below, the question building interface shows the wrong labels when configuring the joins. As soon as the second question is joined in, the labels for the already configured join change (#12930 probably).

https://user-images.githubusercontent.com/4743303/165907600-ef86ddf1-91ab-4106-a690-67a47a95e0ed.mp4

The error shown is:
`Cannot determine the source table or query for Field clause [:field 5 {:join-alias "Orders", :metabase.query-processor.util.add-alias-info/source-table "Orders", :metabase.query-processor.util.add-alias-info/source-alias "PRODUCT_ID"}]`

**Expected behavior**

- The UI should show the correct labels
- The custom column should not fail

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Edge 100.0.1185.50
- Your operating system: macOS 12.3.1
- Your databases: Sample Database
- Metabase version: v0.42.4
- Metabase hosting environment: Docker
- Metabase internal database: Amazon RDS for PostgreSQL

**Severity**
This is basic functionality that is broken, and it blocks me personally from making the reports I want to make. From that point of view I would rate the severity as high.

**Comment by flamber** [comment] 2022-05-02 11:54
Duplicate of #20809

**Closed by flamber** 2022-05-02 11:54 UTC
Labels: Type:Bug, .Needs Triage

**Comment by attaxia** [comment] 2022-08-29 08:53
@flamber I would like to reopen this bug. Although #20809 has been closed for 0.44 which I'm now running, and the error is indeed gone, the function is still not working as expected.

Using the same reproduction path as in the initial post, I would expect the **Total** custom column to contain the SUM of the two joined **Counts**. However, the column is empty.
![Screen Shot 2022-08-29 at 10 52 38](https://user-images.githubusercontent.com/4743303/187163149-68ccae26-7a09-4a37-8eb1-9521466d1b61.png)

In the screenshot above, you can see the Total column stays empty.

**Comment by flamber** [comment] 2022-08-29 11:25
@attaxia You are now seeing #12394
