### ISSUE TITLE
Select/Unselect All fields checkbox

### ISSUE THREAD

**Issue by joebordes** [metabase/metabase#6231] opened 2017-10-22 14:23 UTC
This is a feature request to mass select and unselect fields to include in a table

![metabaseselectallfield](https://user-images.githubusercontent.com/1237191/31862854-59e57cc2-b745-11e7-9ff6-950834d8cd12.png)

**Comment by mazameli** [comment] 2017-10-23 17:16
This is something I've wanted for a while. It's a duplicate of https://github.com/metabase/metabase/issues/3951, and we there's an open PR for it that has been stagnating, but which I'd love for us to try and merge: https://github.com/metabase/metabase/pull/4436

**Closed by mazameli** 2017-10-23 17:16 UTC
Labels: Duplicate
