### ISSUE TITLE
Download results from personal collection is restricted

### ISSUE THREAD

**Issue by Crusader4Christ** [metabase/metabase#10050] opened 2019-05-27 12:24 UTC
Your browser and the version: Chromium 73.0.3683.75 (Official Build) Built on Ubuntu 16.04 (64-bit)
Your operating system: Ubuntu 16.04 (64-bit)
Your databases: MySQL
Metabase version: v0.30.4
Metabase hosting environment: Docker
Metabase internal database: MySQL

Repeatable steps to reproduce the issue
Create restricted-everything group
Add user to it
Create a question and save it to PC of this user

Result: User can view this question and data in it, but can't download. Response for 'api/dataset/csv': You do not have permissions to run this query.
Expected: Every user have full access to their PCs

**Comment by flamber** [comment] 2019-05-27 17:00
@Crusader4Christ I'm pretty sure this was fixed in 0.32.6 by #9872

**Comment by mazameli** [comment] 2019-05-30 17:47
Can't reproduce this on master. @Crusader4Christ, upgrading to the latest version of Metabase should fix this for you. Closing as fixed.

**Closed by mazameli** 2019-05-30 17:47 UTC
Labels: Unable to Reproduce
