### ISSUE TITLE
Persist user selected colours on Bar Charts

### ISSUE THREAD

**Issue by christamlyn-bridge** [metabase/metabase#6143] opened 2017-10-11 07:57 UTC
We use Bar Charts on a Dashboard with a number of Series and Columns.  We set the colours of the Series to represent the item (e.g. red=error, green=good) etc.

As the data updates, if a series returns null or zero its removed from the chart as expected.  On the next refresh when there is data in the series again, the colours have all gone back to their default.

It would be useful if the user selected colour were persisted, especially as the Bar Charts on a dashboard don't show a Key.

**Comment by mazameli** [comment] 2017-10-11 16:08
Agreed, though this is a duplicate of #5910

**Closed by mazameli** 2017-10-11 16:08 UTC
Labels: Duplicate
