### ISSUE TITLE
Visualization single-series does not show the grouped column

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#18975] opened 2021-11-14 09:58 UTC
**Describe the bug**
When converting a single-series chart to Table or using RawData-toggle, then it does not show the grouped column.

**To Reproduce**
1. Custom question > Sample Dataset > Products - summarize Count by Category
![image](https://user-images.githubusercontent.com/1447303/141676157-d54d9924-5e0d-4f99-afe6-5028c303b04f.png)
2. Change visualization to Table (the grouped column can manually be added) or click RawData-toggle
![image](https://user-images.githubusercontent.com/1447303/141676195-a0022a28-6856-4189-8227-df4b6f97a86b.png)

**Expected behavior**
Changing to Table/RawData should show all columns.

**Information about your Metabase Installation:**
Tested 0.37.8 thru 0.41.2

**Severity**
Only giving P3, since it seems like no-one has noticed this, but I'm unsure if this perhaps is causing other problems.

**Comment by kulyk** [comment] 2022-04-20 19:35
@flamber I guess it's fixed now? Can't reproduce following your steps

https://user-images.githubusercontent.com/17258145/164308960-cbfc98d4-219f-47fb-8751-e2a4d3d43f3b.mp4

**Closed** 2022-04-21 17:45 UTC
Labels: Type:Bug, Priority:P3, .Correctness, .Frontend, Querying/GUI, Visualization/Charts
