### ISSUE TITLE
Time series bar graph dates doen't match (popup and bar name)

### ISSUE THREAD

**Issue by that0n3guy** [metabase/metabase#2340] opened 2016-04-08 14:00 UTC
If this is a bug report, please fill in the blanks:

*  I am using the chrome browser.
*  My computer's OS is window 10.
*  I'm running Metabase docker on aws
*  My database is mysql.
*  My Metabase version is v0.16.1 built on 2016-04-05.

![image](https://cloud.githubusercontent.com/assets/113870/14385917/4f3a94ee-fd68-11e5-8eac-5cab3198e8be.png)

My bar says December below it, but the hover popup thing says November.

**Comment by agilliland** [comment] 2016-04-08 14:15
Do you mind switching the visualization over to Table real quickly and providing the last couple values?  I'm curious if the data actually ends on November, December, etc.

**Comment by that0n3guy** [comment] 2016-04-08 14:22
Yup: 
![image](https://cloud.githubusercontent.com/assets/113870/14386660/5e70a02c-fd6b-11e5-811e-1c856f670b16.png)

That says the wrong thing in the createDate: month

**Comment by agilliland** [comment] 2016-04-08 14:32
Ah, so you think it's formatting the dates incorrectly?  

I suppose one last piece of information would be helpful to get a final confirmation then.  If you open up your browser and inspect the network calls after running the query, there should be a call against the `dataset` endpoint which will have the raw JSON output of the query result that goes into the chart.  You mind checking that?  I'm curious if this is some kind of timezone/date parsing issue.

**Comment by that0n3guy** [comment] 2016-04-08 14:56
I'm not sure if this is the right json, but its the dataset response:

```
{"finished_at":"2016-04-08T14:45:54.000Z","started_at":"2016-04-08T14:45:53.000Z","json_query":{"database":2,"type":"query","query":{"source_table":115,"aggregation":["count"],"breakout":[["datetime_field",309,"as","month"]],"filter":["AND",["BETWEEN",309,"2015-01-01","2015-12-31"],["=",328,"DI-Quote"]]},"constraints":{"max-results":10000,"max-results-bare-rows":2000}},"status":"completed","id":428,"uuid":"3329d473-0e13-439f-a788-84ad4aae6f9c","row_count":12,"running_time":438,"data":{"cols":[{"description":null,"table_id":115,"schema_name":null,"special_type":"timestamp_seconds","unit":"month","name":"createDate","extra_info":{},"id":309,"visibility_type":"normal","target":null,"display_name":"Createdate","base_type":"BigIntegerField"},{"description":null,"id":null,"table_id":null,"base_type":"IntegerField","name":"count","display_name":"count","special_type":"number","target":null,"extra_info":{}}],"columns":["createDate","count"],"rows":[["2014-12-31T18:00:00.000-06:00",36],["2015-01-31T18:00:00.000-06:00",24],["2015-02-28T18:00:00.000-06:00",67],["2015-03-31T19:00:00.000-05:00",44],["2015-04-30T19:00:00.000-05:00",265],["2015-05-31T19:00:00.000-05:00",555],["2015-06-30T19:00:00.000-05:00",134],["2015-07-31T19:00:00.000-05:00",16],["2015-08-31T19:00:00.000-05:00",21],["2015-09-30T19:00:00.000-05:00",14],["2015-10-31T19:00:00.000-05:00",11],["2015-11-30T18:00:00.000-06:00",257]]}}
```

My database contains a unix timestamp that I set in the metadata as such (in seconds).  I created a table view to test if metabase is screwing up.  I did `FROM_UNIXTIME(A.createDate) AS createDate` so that metabase doesn't have too.  Same result as above (november for december, etc..).

**Comment by that0n3guy** [comment] 2016-04-08 15:05
Oh also, if I set the year to "this year" the first month is december of last year... so yes, I think its formatting the dates in correctly, even in the table it shows.

**Comment by agilliland** [comment] 2016-04-08 15:49
Yeah, that's perfect.  So it looks like you are probably running into this issue https://github.com/metabase/metabase/issues/2035

There is a mismatch on the expectations around timezone handling.  What is the report timezone that you chose in the admin settings?  US/Central?

**Comment by that0n3guy** [comment] 2016-04-08 16:07
Yup, US/Central it is.  Its like you can read my mind.

**Comment by that0n3guy** [comment] 2016-04-08 16:10
I selected "database default" and now my months line up.  Stuff like "today" or "yesterday" isn't quite right because its hours off, but you already understand the problem it sounds like.

**Comment by fimpfimp** [comment] 2016-04-11 10:33
Is a fix for this sheduled for the next release?

**Comment by agilliland** [comment] 2016-04-11 15:05
No, there isn't a possible fix scheduled for this right now.  As I said above I believe you are running into the limitation caused by issue #2035 which is caused when the system running Metabase is not set to your desired reporting timezone, which is causing some timezone related operations to get misaligned.

So in this case for @that0n3guy I believe the reason this is happening is because the system is likely running in UTC but the desired timezone is US/Central.  I'm looking at some ways to get past that limitation inside the application, but the simplest and best thing to do is to ensure that your server/computer is running in the same timezone that you want to be reporting in.  If you are using java locally this would be done by running ...

`java -Duser.timezone=US/Central -jar metabase.jar`

**Comment by that0n3guy** [comment] 2016-04-11 15:12
This may be a side question, but do we have the ability to do that w/ the docker image?

**Comment by fimpfimp** [comment] 2016-04-11 15:12
Our system is running UTC. 

Setting Metabase's "Report Timezone" to UTC does not fix the issue [I described here](http://discourse.metabase.com/t/wrong-month-labels/305/3).

Does this mean the issue I am experiencing is separate from the one described in this thread?

**Comment by agilliland** [comment] 2016-04-11 15:30
@that0n3guy unfortunately no, not right now.  i opened issue #2350 to capture that need.  to do that you'd need to build the docker image yourself, which isn't terribly difficult but it'll require setting up an environment to do so.

@fimpfimp hmmm, your issue looks similar.  what database are you using?  and like above would you be able to capture the network output from the `dataset` api endpoint when you run one of your cards and post the output here?  in order to troubleshoot what's happening we need to see the raw data with it's timezone offsets.

**Comment by fimpfimp** [comment] 2016-04-12 08:55
We have both an MySQL and a Postgres database connected to Metabase. I don't have access to the network output, however I found a workaround (at least for my MySQL questions):

Replacing
`DATE_FORMAT(create_time, '%Y-%m') AS 'month'`
with
`DATE_FORMAT(create_time, '%Y %b') AS 'month'`
fixed the issue. Don't know if that gives you a hint as to the source of the problem.

**Comment by fimpfimp** [comment] 2016-04-12 10:39
PostgreSQL workaround confirmed:
Replace
`to_char(create_time, 'YYYY-MM') AS year_month`
with
`to_char(create_time, 'YYYY Mon') AS year_month`

**Comment by agilliland** [comment] 2016-04-12 16:21
I tried to replicate you issue yesterday @fimpfimp and I couldn't get the same result you are seeing.  The fact that you are directly using SQL and the date_format/to_char functions definitely makes this a different issue.  In both of those cases your query results are going to come back as string values instead of timestamps when the query is run (which is what would be nice to validate).  In any case, the only reason I could see your charts not lining up correctly is because your browser timezone is different from the timezone the data was meant to be interpreted in, although I couldn't make that particular situation happen for me.

**Comment by fimpfimp** [comment] 2016-04-19 14:51
For regular (non-SQL) questions I have the same issue as described by @that0n3guy . I have already set the Report Timezone in Metabase Admin settings to Database Default.

Is there something else I should do?

**Comment by fimpfimp** [comment] 2016-04-20 10:46
Here is the dataset response when inspecting in the browser:
`{"finished_at":"2016-04-20T10:43:56.249Z","started_at":"2016-04-20T10:43:56.155Z","json_query":{"database":3,"type":"query","query":{"source_table":92,"aggregation":["count"],"breakout":[["datetime_field",907,"as","month"]],"filter":["AND",["NOT_NULL",904]]},"constraints":{"max-results":10000,"max-results-bare-rows":2000}},"status":"completed","id":15106,"uuid":"ee19d79c-0e95-457b-be47-401572d4f0d1","row_count":23,"running_time":94,"data":{"cols":[{"description":null,"table_id":92,"schema_name":"public","special_type":null,"unit":"month","name":"create_time","extra_info":{},"id":907,"visibility_type":"normal","target":null,"display_name":"Create Time","base_type":"DateTimeField"},{"description":null,"id":null,"table_id":null,"base_type":"IntegerField","name":"count","display_name":"count","special_type":"number","target":null,"extra_info":{}}],"columns":["create_time","count"],"rows":[["2014-06-01T00:00:00.000Z",10],["2014-07-01T00:00:00.000Z",19],["2014-08-01T00:00:00.000Z",61],["2014-09-01T00:00:00.000Z",93],["2014-10-01T00:00:00.000Z",77],["2014-11-01T00:00:00.000Z",60],["2014-12-01T00:00:00.000Z",53],["2015-01-01T00:00:00.000Z",33],["2015-02-01T00:00:00.000Z",39],["2015-03-01T00:00:00.000Z",26],["2015-04-01T00:00:00.000Z",41],["2015-05-01T00:00:00.000Z",47],["2015-06-01T00:00:00.000Z",65],["2015-07-01T00:00:00.000Z",67],["2015-08-01T00:00:00.000Z",37],["2015-09-01T00:00:00.000Z",60],["2015-10-01T00:00:00.000Z",55],["2015-11-01T00:00:00.000Z",58],["2015-12-01T00:00:00.000Z",52],["2016-01-01T00:00:00.000Z",64],["2016-02-01T00:00:00.000Z",57],["2016-03-01T00:00:00.000Z",45],["2016-04-01T00:00:00.000Z",41]]}}`

**Comment by agilliland** [comment] 2016-04-20 14:24
So @fimpfimp , based on that last response I don't see what could still be wrong.  You are clearly getting back bucketed months which properly represent the starting date at the beginning of each month.  What problem are you seeing when you chart that?

**Comment by fimpfimp** [comment] 2016-04-20 14:36
See the label on the horizontal axis compared to the label shown on mouse-over.
<img width="389" alt="screen shot 2016-04-20 at 4 35 53 pm" src="https://cloud.githubusercontent.com/assets/3314319/14678461/0b646512-0716-11e6-8fbc-42ae175d345f.png">

**Comment by agilliland** [comment] 2016-04-20 14:43
Okay, I haven't been able to reproduce that specific issue unless the data was misaligned due to timezones as I mentioned above, but now that I have your exact data I'll try again to reproduce it.

What timezone is your browser in?

**Comment by agilliland** [comment] 2016-04-20 14:45
@tlrobinson can you take a couple minutes and see if you can recreate this problem?  the data appears to all be correct, but the labels on the chart axis are off by 1 month which may be something to do with the way timezones and date parsing are happening specifically on the chart axis (note that the tooltip is correct and showing the right data).

**Comment by fimpfimp** [comment] 2016-04-20 14:46
My computer is in CET (4.46PM at the time of this post). I assume my browser is the same.

**Comment by fimpfimp** [comment] 2016-04-20 14:53
http://whatismytimezone.com/ tells me "You are currently at GMT+/--2:00"

**Comment by that0n3guy** [comment] 2016-05-04 20:01
@agilliland I'm reporting back because your v0.17 release page points to this issue...

I thought I would just report in.   I have updated my docker to version v0.17.0 built on 2016-05-02 and the timezones using the environment variable and admin selection.   Now my counts are right for "today" or "yesterday" (for example)....

But the original post (and 3rd post above) are still happening.   The thing below the bar graph says "may" but the hover popup shows "april" (like the orginal post in this thread).  Also my table shows "april" when rather than "may".

Here is an image with table and bar graph overlayed: 
![image](https://cloud.githubusercontent.com/assets/113870/15027303/c4d52e80-1208-11e6-989b-3e4699b53c0a.png)

Also, here is the dataset like you requested previously of me:

```
{"finished_at":"2016-05-04T19:58:40.000Z","started_at":"2016-05-04T19:58:38.000Z","json_query":{"database":2,"type":"query","query":{"source_table":115,"aggregation":["count"],"breakout":[["datetime_field",309,"as","month"]],"filter":["AND",["TIME_INTERVAL",309,"current","year"],["=",328,"DI-Quote"]]},"constraints":{"max-results":10000,"max-results-bare-rows":2000}},"status":"completed","id":1570,"uuid":"b8943a74-4297-44e1-a1dd-bbca38715ae5","row_count":5,"running_time":1269,"data":{"cols":[{"description":null,"table_id":115,"schema_name":null,"special_type":"timestamp_seconds","unit":"month","name":"createDate","extra_info":{},"id":309,"visibility_type":"normal","target":null,"display_name":"Createdate","base_type":"BigIntegerField"},{"description":null,"id":null,"table_id":null,"base_type":"IntegerField","name":"count","display_name":"count","special_type":"number","target":null,"extra_info":{}}],"columns":["createDate","count"],"rows":[["2015-12-31T18:00:00.000-06:00",29],["2016-01-31T18:00:00.000-06:00",15],["2016-02-29T18:00:00.000-06:00",32],["2016-03-31T19:00:00.000-05:00",84],["2016-04-30T19:00:00.000-05:00",33]]}}
```

**Comment by agilliland** [comment] 2016-05-04 20:39
thanks for helping out with this @that0n3guy , we'll get this sorted out eventually!

so, based on the JSON data that you posted it looks to me like there is still a mismatch between the understood timezone of your Metabase instance and the report timezone setting that you have set in Metabase.  That is why the timestamps in your data are not at the 0th hour of the day, which is what is ultimately leading to this issue. (e.g. `"2016-01-31T18:00:00.000-06:00"`).

when I run a local instance of metabase (via Docker) and set the JAVA_TIMEZONE=US/Pacific and then set my report timezone to US/Pacific in Metabase, the values come out as expected where the timestamp is the 0th hour and my timezone offset properly reflects that we are working in US/Pacific `"2015-02-01T00:00:00.000-08:00"`.  so the goal is to get your timestamps coming out like that.

the application logs now provide an entry indicating the system timezone when you start up Metabase, you mind double checking what that value is?

`05-03 11:06:18 INFO metabase.core :: System timezone is 'US/Pacific' ...`

that setting should ideally align with the value you chose for your Report Timezone in Metabase.

**Comment by that0n3guy** [comment] 2016-05-04 20:48
I used JVM_TIMEZONE since thats what the docs say here: http://www.metabase.com/docs/v0.17.0/operations-guide/running-metabase-on-docker.html

I now have JAVA_TIMEZONE=US/Central and JVM_TIMEZONE=US/Central in my env vars and .... IT WORKS! :).

I'm guessing I just need JAVA_TIMEZONE and don't need JVM_TIMEZONE... correct?

**Comment by agilliland** [comment] 2016-05-04 20:50
Ahhh ... documentation fail 😢 

sorry about that.  we'll get that fixed up.  glad to hear everything is working properly now though 👍

**Comment by agilliland** [comment] 2016-05-04 20:50
and yes, JVM_TIMEZONE is just a typo, you only need JAVA_TIMEZONE.

**Comment by that0n3guy** [comment] 2016-05-04 21:07
Gotcha... call this closed :).

Maybe add something to docs?

**Comment by agilliland** [comment] 2016-05-04 22:26
I fixed the reference in the documentation, and we did add a section about making sure timezone handling, so hopefully that gives us enough coverage ... http://www.metabase.com/docs/v0.17.0/operations-guide/start.html#handling-timezones-in-metabase

**Closed by agilliland** 2016-05-04 22:26 UTC
Labels: Limitation, Visualization

**Comment by artem-levashov** [comment] 2018-10-10 09:31
I had same problem with GA reports when usied yearMonth grouping. To fix it i made 2 steps

    in Admin panel set report timezone to UTC
    rewrote service which is running metabes. jar:
    from
    java -jar metabase.jar
    to
    java -Duser.timezone=US/Central -jar metabase.jar
    After restart all dates show correctly

**Comment by kevincolten** [comment] 2021-11-29 20:20
For those using Heroku, set the [environment variable](https://github.com/Zollege/metabase-deploy/blob/master/bin/start#L117-L121) `JAVA_TIMEZONE`
