### ISSUE TITLE
UI for aggregation dropdown w/out any metric fields

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1622] opened 2015-12-02 22:51 UTC
Right now we can get into cases where a given table doesn't have any numerical fields that could be averaged or summed. This leads to a suboptimal dropdown presentation in the UI when you select average, sum, etc. from the aggregation dropdown in the query builder:

<img width="332" alt="screen shot 2015-12-02 at 2 46 06 pm" src="https://cloud.githubusercontent.com/assets/2223916/11546753/f7eb9846-9903-11e5-91b8-634ad5692769.png">

We should either:
* gray out aggregation options that don't make sense for the table
* or put some empty state content in the field dropdown that says something like, "no numerical fields in this table."

**Comment by camsaul** [comment] 2016-01-20 22:33
Duplicate of #1502

**Closed by camsaul** 2016-01-20 22:33 UTC
Labels: UX
