### ISSUE TITLE
Emails don't respect formatting of underlying questions / dashboard content

### ISSUE THREAD

**Issue by awor** [metabase/metabase#15927] opened 2021-05-05 07:16 UTC
**Describe the bug**
Formatting regarding thousand separators and decimal places are not respected in email version of content

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Create a dashboard with a question on it that has numeric formatting applied (in our case swiss thousand separator and zero decimal places)
2. Create a dashboard subscription or click on "send on email now"
3. Compare formatting of email content to dashboard content

**Expected behavior**
Numeric formatting in email content should be the same as applied to question/dashboard

**Screenshots**

{
  "browser-info": {
    "language": "en",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "4.18.0-193.el8.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlserver",
      "googleanalytics",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.5.9-MariaDB-1:10.5.9+maria~focal"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-03-03",
      "tag": "v0.38.1",
      "branch": "release-x.38.x",
      "hash": "79ef63a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

- Your browser and the version: Chrome 90.0.4430.93 (Official Build) (64-bit)
- Your operating system: Windows 10 Client, Server see above
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: Docker
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)

**Severity**
This is not a complete show-stopper but irritating for users and throws an unpolished light on product, as this email content is high visibility

**Additional context**

**Comment by flamber** [comment] 2021-05-05 07:22
Duplicate of #3735

**Closed by flamber** 2021-05-05 07:22 UTC
Labels: .Needs Triage, Type:Bug
