### ISSUE TITLE
Display the entire error message

### ISSUE THREAD

**Issue by bkowshik** [metabase/metabase#10409] opened 2019-07-25 10:17 UTC
When an SQL query has a syntax error, the error message from the database is not shown. Instead, the following generic message is shown to the user.

<img width="1440" alt="Screenshot 2019-07-25 at 15 43 28" src="https://user-images.githubusercontent.com/2899501/61866690-3fab7d00-aef3-11e9-9a8c-82f4116e19ac.png">

It's quite common to iterate over SQL queries and there could be error messages. When the entire message is shown to the user, using the line-numbers, would help debug the issue better.

**Comment by bkowshik** [comment] 2019-07-25 10:43
I see the error message in the logs. Ex:

> :error "(conn=142946) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 17

**Comment by salsakran** [comment] 2019-10-06 23:43
Practically speaking, this is a dupe of #625

**Closed by salsakran** 2019-10-06 23:43 UTC
Labels: Type:UX

**Comment by flamber** [comment] 2019-10-07 00:00
@salsakran 
This is a specific MySQL problem, where the error message is truncated at the semicolon.
Normally the full message would look like this:
`
(conn=24393) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'İNNER JOIN permissions_group pg ON pgm.group_id = pg.id İNNER JOIN' at line 1
`
