### ISSUE TITLE
Allow inserting questions into middle of dashboard (allow drag and drop to swap questions)

### ISSUE THREAD

**Issue by bturndorf** [metabase/metabase#13365] opened 2020-10-05 15:30 UTC
**Is your feature request related to a problem? Please describe.**
We use a dashboard that's broken into sections for different products across our company, and when we need to add a new question in the middle of the dashboard (instead of the bottom), there's no way to drag and drop a question to where we'd like it directly. Instead, we have to drag every question in the dashboard down, one-by-one, to make more space. With 30+ questions, this is a slow and error-prone process.

**Describe the solution you'd like**
I'd most like the dashboard editing grid to allow question tiles on the dashboard to swap with each other, but I'd also be into any of the following solutions:

- Shrink a question to fit, if it's dragged to an area of the dashboard where it doesn't fit at its current size
- Allow inserting or deleting rows in the dashboard grid

Or anything else that allows putting a saved question in the middle of a dashboard by just editing around the part of the dashboard I want to edit, without having to edit the entire dashboard from that point down.

**How important is this feature to you?**
This would be really nice to have. It's not crucial, but would make updating a large dashboard much easier and faster.

**Comment by flamber** [comment] 2020-10-05 15:41
Duplicate of #9895

**Closed by flamber** 2020-10-05 15:41 UTC
Labels: .Needs Triage, Type:New Feature
