### ISSUE TITLE
pulse getting missed after running for 4 days 

### ISSUE THREAD

**Issue by danishdshadab** [metabase/metabase#11587] opened 2019-12-23 14:52 UTC
**Describe the bug**
Our pulse is getting missed after running for 4 consecutive day in a row.
And the error looks like of timezone.

The database is snowflake which is running in PST for which I set the REPORT TIMEZONE
 in Metabase to 'Default Database' and even to PST . Even in metabase container i updated the timezone to PST. But every case the meta base pulse misses to send pulse after 4 day.

**Logs**
{“status”:“failed”,“exception”:“class clojure.lang.ExceptionInfo”,“message”:“Input to defaulted-timezone does not match schema: \n\n\t \u001b[0;33m [(named (not (instance? metabase.models.card.CardInstance nil)) card)] \u001b[0m \n\n”,“stacktrace”:["–> pulse$fn__60819$defaulted_timezone__60824.invoke(pulse.clj:51)",“pulse$fn__60917.invokeStatic(pulse.clj:165)”,“pulse$fn__60917.invoke(pulse.clj:160)”,“pulse$results__GT_notifications$iter__60947__60951$fn__60952.invoke(pulse.clj:212)”,“pulse$send_notifications_BANG_.invokeStatic(pulse.clj:248)”,“pulse$send_notifications_BANG_.invoke(pulse.clj:247)”,“pulse$send_pulse_BANG_.invokeStatic(pulse.clj:274)”,“pulse$send_pulse_BANG_.doInvoke(pulse.clj:256)”,“task.send_pulses$fn__67957$send_pulses_BANG___67966$fn__67969$fn__67987$fn__67988.invoke(send_pulses.clj:59)”,“models.task_history$fn__41262$do_with_task_history__41267$fn__41268.invoke(task_history.clj:77)”,“models.task_history$fn__41262$do_with_task_history__41267.invoke(task_history.clj:72)”,“task.send_pulses$fn__67957$send_pulses_BANG___67966$fn__67969$fn__67987.invoke(send_pulses.clj:56)”,“task.send_pulses$fn__67957$send_pulses_BANG___67966$fn__67969.invoke(send_pulses.clj:55)”,“task.send_pulses$fn__67957$send_pulses_BANG___67966.invoke(send_pulses.clj:42)”,“task.send_pulses$fn__67957$send_pulses_BANG___67966$fn__67967.invoke(send_pulses.clj:49)”,“task.send_pulses$fn__67957$send_pulses_BANG___67966.invoke(send_pulses.clj:42)”,“task.send_pulses.SendPulses$fn__68023.invoke(send_pulses.clj:100)”,“models.task_history$fn__41262$do_with_task_history__41267$fn__41268.invoke(task_history.clj:77)”,“models.task_history$fn__41262$do_with_task_history__41267.invoke(task_history.clj:72)”,“task.send_pulses.SendPulses.execute(send_pulses.clj:86)”],“ex-data”:{“type”:“schema.core/error”,“schema”:[{“schema”:“class metabase.models.card.CardInstance”,“optional?”:false,“name”:“card”}],“value”:[null],“error”:[“schema.utils.NamedError@2b446b44”]},“original-info”:null}

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'pulse' create a new pulse with timezone variable (I am not sure if it is needed)
2. The pulse fails after 4 day of consecutive run.

**Expected behaviour**
Pulse sent every day.

**Screenshots**

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.14.106-97.85.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "US/Pacific"
  },
  "metabase-info": {
    "databases": [
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-11-19",
      "tag": "v0.33.6",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": "Canada/Eastern"
    }
  }
}

**Severity**
This is very severe issue as the work is on hold to create any new pulse and our team is very worried about the dependency 

**Additional context**
One very important point is one of the pulse is not having this issue  and sending pulse every day but all the other pulse are.

another point to mention is if i navigate to the pulse
https://metabase.myurl.com/pulse/9
The question disappear.

**Comment by flamber** [comment] 2019-12-24 03:25
I have not been able to reproduce this - and it's the first time I've ever encountered this in issue/forum.
For whoever is investigating this. This is a bit more severe than "just" pulses stopping after 4 days. After the error mentioned, it then removes the question from the pulse too.
There's a couple of long troubleshooting topics in the forum:
https://discourse.metabase.com/t/pulse-failing-after-every-4-day-run/8299/
https://discourse.metabase.com/t/question-getting-deleted-from-pulse/7991

**Comment by camsaul** [comment] 2021-04-23 00:58
It sounds like the issue is the Card doesn't exist anymore, which is why it's not able to send a Pulse

```
(not (instance? metabase.models.card.CardInstance nil))
```

**Comment by flamber** [comment] 2021-11-14 12:59
Closing in favor of #10088

**Closed by flamber** 2021-11-14 12:59 UTC
Labels: Type:Bug, Priority:P2, Reporting/Pulses, Misc/Timezones
