### ISSUE TITLE
Too many group by items results in blank chart

### ISSUE THREAD

**Issue by singpolyma** [metabase/metabase#18775] opened 2021-10-31 00:57 UTC
**Describe the bug**

I have a query

`select customer_id, date_trunc('month', start) as month, sum(thing) from table group by date_trunc('month', start), customer_id having sum(thing) > 120;`

This worked until this month we got too many customers and now the chart just renders blank.  If I remove the series breakout for `customer_id` then it renders again.  It would be fine if it just rendered the top N breakouts and grouped the rest as "other" but instead I get a blank chart.

**Screenshots**

![Screenshot_2021-10-30_19-51-45](https://user-images.githubusercontent.com/12770/139562477-7f5d4a03-976f-4dab-9b27-10ea91287cef.png)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-CA",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17-ea+19-Debian-1",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-17",
    "java.version": "17-ea",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17-ea+19-Debian-1",
    "os.name": "Linux",
    "os.version": "4.19.0-17-amd64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.10 (Debian 11.10-0+deb10u1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-07-14",
      "tag": "v0.40.1",
      "branch": "release-x.40.x",
      "hash": "ed8f9c8"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2021-10-31 09:12
Duplicate of #16000 - upgrade to 0.40.5 or the latest release 0.41.1: https://github.com/metabase/metabase/releases

**Closed by flamber** 2021-10-31 09:12 UTC
Labels: Type:Bug, .Needs Triage

**Comment by singpolyma** [comment] 2021-10-31 23:57
I upgraded but now the chart just renders an error instead of blank.

**Comment by flamber** [comment] 2021-11-01 09:56
@singpolyma Yes, Metabase does not support more than 100 series in a chart. There's a request to make that limit configurable: #7958 - upvote by clicking :+1: on the first post
