### ISSUE TITLE
[TRANSLATION] Missing on update a Pulse

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#15089] opened 2021-03-08 16:52 UTC
**Describe the bug**
Missing translation on email when a Pulse is updated

**Screenshots**
![Screenshot from 2021-03-08 13-46-06](https://user-images.githubusercontent.com/6808348/110353008-54c81780-8015-11eb-95f2-a38d9e4c2c9f.png)

**Information about your Metabase Installation:**
```json
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_275-8u275-b01-1~deb9u1-b01",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_275",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.275-b01",
    "os.name": "Linux",
    "os.version": "4.9.0-14-amd64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres",
      "mysql",
      "clickhouse",
      "bigquery",
      "athena",
      "cubejs",
      "sqlserver",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.37.9",
      "date": "2021-02-11",
      "branch": "release-x.37.x",
      "hash": "a9a7fc8"
    },
    "settings": {
      "report-timezone": "America/Sao_Paulo"
    }
  }
}
```

**Comment by flamber** [comment] 2021-03-08 16:56
Duplicate of #7535

**Closed by flamber** 2021-03-08 16:56 UTC
Labels: .Needs Triage, Type:Bug
