### ISSUE TITLE
Support quarter filter in custom question page

### ISSUE THREAD

**Issue by wbchn** [metabase/metabase#17064] opened 2021-07-15 10:22 UTC
**Is your feature request related to a problem? Please describe.**

We want filtered like current/previous quarter when "add filters to narrow your answer" in "Custom question".
Now the date type filed only support unit like minutes/hours/days/weeks/months/years, no quarter here.

**Describe the solution you'd like**
We want select quarter unit when filter the date filed.

**Describe alternatives you've considered**
yes, I start "Native query" with write SQL, but our friend use "Custom query" frequently which can not do that.
I look into `dates.clj` source, no idea about how modify it.

**How important is this feature to you?**
yes, we often analysis our data in quarter unit, it work fine in group, but no method do filter data from large of data(severval years).

**Additional context**
![image](https://user-images.githubusercontent.com/7692193/125771042-c7cb9a13-a424-41d6-a475-701f67320876.png)

----
Thanks all of you, metabase is my lovely data dashboard.

**Comment by flamber** [comment] 2021-07-15 10:25
Duplicate of #4742

**Closed by flamber** 2021-07-15 10:25 UTC
Labels: .Needs Triage, Type:New Feature
