### ISSUE TITLE
Nested field formulas break the browser

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#15675] opened 2021-04-19 16:29 UTC
**Describe the bug**
Nesting functions in field formulas breaks the browser by using 100% CPU till the browser kills the tab.

**Logs**
Unfortunately we can't get the logs here as the tab is killed and it's a frontend issue only

**To Reproduce**
1. go to our internal instance, question 1811
2. try adding a new "replace" in the "plan" field in the notebook
3. your tab will be killed as it's clogging your CPU
 
**Expected behavior**
Nesting the functions to work without killing the tab!

**Screenshots**
Not needed and also internal info

**Information about your Metabase Installation:**
Internal instance

- Your browser and the version: tried with Brave latest and also Firefox latest
- Your operating system: Ubuntu LTS latest
- Your databases: ???
- Metabase version: HEAD
- Metabase hosting environment: Internal instance
- Metabase internal database: Postgres

**Severity**
S3, a workaround for this specific case is to build a lookup table

**Additional context**
None

**Comment by flamber** [comment] 2021-04-21 21:32
I cannot reproduce. Have tried on stats with Firefox, and tried to create various crazy looking expressions on 0.39.0.1.
It would be great if you can trigger the problem on Sample Dataset, so we can get a test around it.

**Comment by flamber** [comment] 2021-05-16 09:30
Closing in favor of #16094

**Closed by flamber** 2021-05-16 09:30 UTC
Labels: .Unable to Reproduce, Type:Bug
