### ISSUE TITLE
Trends should use "Year-to-date" or "period to date" comparisons

### ISSUE THREAD

**Issue by that0n3guy** [metabase/metabase#11978] opened 2020-02-25 13:26 UTC
**Is your feature request related to a problem? Please describe.**
I can currently create a trend number like so:
![image](https://user-images.githubusercontent.com/113870/75248808-81a6e500-579a-11ea-8e7c-20f58cb4505c.png)

This looks nice, but its not actually useful data.  Last month it says I had 220 quotes (a full month), this month only 156 quotes (a parital month).  BUT if its only half way through THIS month, then we are comparing a full month vs a partial month... not really a fair comparison.

The 156 is a partial months number, the 220 is a full month number.  If I was to compare last months first 15 days vs this months first 15 days,   The comparison percentage would be positive, not negative.

As far as I can tell, the trend feature will always be wrong if it always compares the last _full_ period vs this _partial_ period.  It will only be right on the very last day of the period (like last day of the month).

**Describe the solution you'd like**
I would like to compare the current period (month, qrtr, yr) vs last period with the last period's being truncated to make the data equivalent.

**Describe alternatives you've considered**
I can do this with custom sql, but its kinda a pain for people to modify.

**How important is this feature to you?**
We use previous period comparisons on every single dashboard we have.  The way the current trend visualization works (ex full month vs partial month) the data is not valid and confuses users.

**Comment by that0n3guy** [comment] 2020-02-25 13:36
I think this is similar to #8977

**Comment by flamber** [comment] 2020-02-25 18:51
Hi @that0n3guy 
Sounds like a duplicate of #9393 (which also references #8977). Going to close this issue.

**Closed by flamber** 2020-02-25 18:51 UTC
Labels: .Needs Triage, Type:New Feature

**Comment by sbelak** [comment] 2020-02-25 19:04
Would something like https://github.com/metabase/metabase/pull/9400 be useful for you?

**Comment by alexsonnay** [comment] 2020-10-02 17:11
It's not a duplicate to those references according to me. It is a persisting issue.

**Comment by eriklive** [comment] 2021-04-26 19:51
Facing the same problem here.

**Comment by jakesing** [comment] 2021-10-06 14:43
1000% agree.

**Comment by devurandom** [comment] 2021-10-08 22:57
Another useful insight would be: How did the last *completed* month compare to its previous month. I.e. today on 2021-10-09, it would show me how 2021-09 compared to 2021-08. Something like a dynamic "Before" might solve that, where I could select "before the 1st of the month", or similar.

**Comment by jike212** [comment] 2021-12-07 14:48
I thought I was the only one having this issue. I'm not sure how trends can even be a useful feature if it's not comparing apples to apples. Hoping it's something that can be resolved soon but it seems this issue has been open for a while.

**Comment by jkokatjuhha** [comment] 2022-07-22 12:33
I would love to have this one!
