### ISSUE TITLE
group by one date multiple times (year and month)

### ISSUE THREAD

**Issue by mvrabel** [metabase/metabase#5312] opened 2017-06-12 10:48 UTC
We want to be able to group by one date column multiple times. 
e.g. something like this:

![grooup_by_year_and_month](https://user-images.githubusercontent.com/12628893/27030588-294a5e60-4f6d-11e7-80b2-3e26410cc604.PNG)

I created this by adding 'Year' and 'Month' integer columns into the table. 

browser and the version: 59.0.3071.86 (64-bit)
operating system: Win 10
databases: Postgressql 9.6
Metabase version: v0.24.2 Built on 2017-06-01
Metabase hosting environment: CentOS 7
Metabase internal database: I think H2 (default), I only downloaded the jar and conected to the database.

**Comment by eljakim** [comment] 2017-10-23 22:43
Is there a workaround for this available? This is a major issue for us. Not only for charts, but also for tables where you would want to be able to do something like:

|   |  2015 | 2016   | 2017  | 2018  |
|---|---|---|---|---|
|  Q1 |   |   |   |   |
|  Q2 |   |   |   |   |
|  Q3 |   |   |   |   |
| Q4 | | | | |

in order to be able to compare turnover.

**Comment by mvrabel** [comment] 2017-10-24 07:08
@eljakim 
My workaround for this is to add quartal column into the table. Then group by qurtal and the date.

**Comment by eljakim** [comment] 2017-10-24 07:11
But that would mean that for every table where people sort by dates I have to add extra columns for quarter, month, day_of_week, week_number, day_of_month. That seems a bit over the top because that would be 5 extra fields per date field, and if we go this way, probably also the year field because otherwise my users won't be able to find that field. That seems to defeat the purpose.

**Comment by mvrabel** [comment] 2017-10-24 09:21
@eljakim We have the same problem as you, but that's the workaround that we know of. 
![inception](https://user-images.githubusercontent.com/12628893/31934817-7cec3184-b8ad-11e7-9540-2f97a9d02f5a.PNG)
When you group by a column (e.g. Date) the column is then removed from the list of columns you can possibly group by. 
So the only way is to add another column.
Hi, @salsakran do you know if there is some other workaround for this issue ?

**Comment by georghendrik** [comment] 2018-02-01 12:34
@salsakran Thank you for looking into this. It's a bit odd that this is labeled as a proposal, since grouping on the same date field twice (in the query builder) used to be possible, somewhere around Metabase 0.22. Isn't this a regression?

**Comment by jornh** [comment] 2018-05-21 17:28
Related issue marked as a bug: #4726 (is this issue in reality a dupe?)

**Comment by vuchl** [comment] 2019-09-26 07:23
Still present in 0.33.3

**Comment by lp-lima** [comment] 2019-09-26 17:32
This feels like a major design flaw in the query builder, That is a pretty basic feature when you want to do some level of analysis. Using 0.32.10, and the issue is still here. Too bad this has so little upvotes.

**Comment by flamber** [comment] 2019-09-26 19:35
Likely because it's a duplicate of #4726 - which has received milestone 0.34 (not a guarantee).

**Comment by mazameli** [comment] 2019-10-03 20:09
Closing this as a duplicate of #4726, which we are looking into.

**Closed by mazameli** 2019-10-03 20:09 UTC
Labels: Duplicate, Query Builder, Type:New Feature
