### ISSUE TITLE
Date filters in the URL are deleted upon entry

### ISSUE THREAD

**Issue by basistom** [metabase/metabase#16731] opened 2021-06-23 08:47 UTC
**Describe the bug**
When opening an dashboard with a date-filter as URL-param, the param will be removed and the neither the value from the param nor the default value will be used as filter. 

**To Reproduce**
1. Create a question with a date-filter as fieldfilter on a unix-timestamp field
2. Place the question on a dashboard and add a filter 
3. Share the Dashboard with a paramter-link:
https://url/public/dashboard/6bf6cace-fa58-4ae2-b85a-958711f5967e?daterange=thismonth

**Expected behavior**
This kind of paramter-url works for filter on other categories-columns. We expect, that the value from the url will be placed inside the filter and the selected dashboards should be filtered.

Instead the param "daterange" is removed from the url.
Selecting the date-filter again will add the value to the url again and the questions gets filtered.

https://url/public/dashboard/6bf6cace-fa58-4ae2-b85a-958711f5967e?daterange=thismonth
=>
https://url/public/dashboard/6bf6cace-fa58-4ae2-b85a-958711f5967e

**Screenshots**

<img width="1392" alt="Bildschirmfoto 2021-06-23 um 10 31 48" src="https://user-images.githubusercontent.com/4112968/123066171-19105c80-d410-11eb-9997-d9efc6c7a6f2.png">
<img width="1392" alt="Bildschirmfoto 2021-06-23 um 10 35 16" src="https://user-images.githubusercontent.com/4112968/123066181-1c0b4d00-d410-11eb-96e0-e9650f629dae.png">

**Information about your Metabase Installation:**

- Metabase version:  v0.39.3
- Tested in Safari Version 14.1.1 (16611.2.7.1.4) and Chrome 91.0.4472.106 
- On macOS Big Sur 11.4 
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)

**Severity**
This bug is not blocking but super annoying and makes us working with metabase less efficient.
Also our customer (for which we use the buggy-boards mainly) is frustrated. 
We place many links for a variety of filter-combinations on the board to switch the informations faster. Now we have to select the daterange at any visit.

**Comment by flamber** [comment] 2021-06-23 08:55
Duplicate of #16177 - see comment for workaround.

**Closed by flamber** 2021-06-23 08:55 UTC
Labels: .Needs Triage, Type:Bug
