### ISSUE TITLE
"Locked" keyword used in ebedded dashboards causes card fail

### ISSUE THREAD

**Issue by MarcGJA** [metabase/metabase#12893] opened 2020-07-10 18:07 UTC
**Describe the bug**
Using the keyword "Locked" in embedded dashboard widget labels associated with a locked parameter, i.e. "Widget Label (Locked)", causes all cards in the dashboard to error out as "There was a problem displaying this chart." including cards without field associations (e.g. plain number or text).

**Logs**
NA

**To Reproduce**
1. Create a dashboard with an intended locked parameter
2. Label that parameter with the word "Locked" in the dropdown widget label text e.g. "User (Locked)", "Territory (Locked)", etc.
3. Publish as an embed locking that parameter
4. Pull up the embed

**Expected behavior**
Dashboard cards should render without issue

**Screenshots**
NA

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 6.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.181-108.257.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "US/Pacific"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "h2"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}

**Severity**
At first VERY!  An innocuous way of tagging a field as a reminder to lock a particular parameter had unintended consequences.  It took several hours of troubleshooting to find the problem.  Once the keyword "Locked" was removed from the locked parameter widget's title the embedded dashboard cards rendered as expected.

**Additional context**
This is probably not something that needs fixing per say.  It is apparently a very particular, and bizarre, issue isolated to just one circumstance.  Users should just be aware that there are certain keywords that are a No-No when embedding dashboards.

**Comment by flamber** [comment] 2020-07-10 18:13
I cannot reproduce, but I don't understand the steps-to-reproduce either.

**Comment by flamber** [comment] 2020-08-11 13:14
Closing, since not enough information has been provided to reproduce this issue. I'm sure there's errors in the log, when it was displaying "There was a problem displaying this chart".

**Closed by flamber** 2020-08-11 13:14 UTC
Labels: .Unable to Reproduce, Type:Bug
