### ISSUE TITLE
Pie chart legend cut off

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#3979] opened 2016-12-18 01:26 UTC
![image](https://cloud.githubusercontent.com/assets/1708680/21290823/1a0fd88a-c4da-11e6-96d0-6d189b683ab6.png)

⬇️ Please click "like" instead of "+1" comment

**Comment by moumny** [comment] 2016-12-19 19:06
If we improve the pie chart would make sense to fix the overflow of the number in the middle of the pie as well :)

**Comment by salsakran** [comment] 2016-12-20 20:06
Hmm... what grid size is that and how many elements?

**Comment by anki-code** [comment] 2016-12-21 08:35
@salsakran :
![image](https://cloud.githubusercontent.com/assets/1708680/21382415/96f97cc2-c771-11e6-86d6-281c69920638.png)

**Comment by mazameli** [comment] 2017-04-07 16:17
Slightly different, but very much related: if you have a small dashboard card with a donut chart in it, the total value gets cut off. Seems like at this size we should move the total below the chart.

<img width="230" alt="pie" src="https://cloud.githubusercontent.com/assets/2223916/24808980/dea8eda0-1b72-11e7-86b7-05aef9d6750f.png">

**Comment by flamber** [comment] 2020-05-12 08:35
This was fixed in one of the 0.33.x releases - I cannot reproduce on 0.35.3:
![image](https://user-images.githubusercontent.com/1447303/81661038-d7a33480-943b-11ea-9dda-81c5d2328cdf.png)

**Closed by flamber** 2020-05-12 08:35 UTC
Labels: Type:New Feature, Visualization/
