### ISSUE TITLE
No data displayed when pivoting data

### ISSUE THREAD

**Issue by wieki** [metabase/metabase#8926] opened 2018-11-12 12:39 UTC
With Metabase 0.30.4 and before pivoting a table worked by selecting 3 columns, where 2 columns were displayed and the last one was used as the information column at the intersections of column 1 and 2. With version 0.31 this seems no longer be working, the appreciated column selector works, but no data is displayed on the intersections.

Running Metabase 0.31.0 within Docker connected to a PostgreSQL database.

Steps to reproduce:
* Create a question in table form, where 3 columns are selected for display
* Select pivot and the pivoting column in the table settings
* Metabase displays empty intersection where data should be

![screenshot_pivot3](https://user-images.githubusercontent.com/10417108/48349089-8027db00-e683-11e8-97a1-12a16fe02d32.png)

![screenshot_pivot2](https://user-images.githubusercontent.com/10417108/48348852-c597d880-e682-11e8-9fc2-9f638c144795.png)

**Comment by sapplaudience** [comment] 2018-12-04 13:16
I'm experiencing exactly the same issue with Metabase 0.31.0 + PosgreSQL.

**Comment by mohit091** [comment] 2018-12-18 11:58
Any update on this

**Comment by dgindin-cp** [comment] 2018-12-28 21:18
Me too. No column data is displayed when I pivot the table. I am running Metabase v0.31.2. Any ETA on a fix? This bug is affecting one of our most important questions used for reporting. Thanks!

**Comment by wieki** [comment] 2019-01-22 09:56
Is there any timeline on updated pivot features? I see a number of PR/Tickets go around but no timeline when pivot functionality would work again?

**Comment by NicoBerthoz** [comment] 2019-03-04 17:49
Would love to get this problem solved, would change my life. Thanks! (i +1 already)

**Comment by alex-mcleod** [comment] 2019-03-12 03:43
I am also experiencing this issue. It seems to work correctly if the information in the cells is numeric, but other values are not displaying (e.g. text or dates).

**Comment by pulkitjalan** [comment] 2019-03-26 06:32
Having the same issue v0.31.2,  would be great to have this fixed.

**Comment by dgindin-cp** [comment] 2019-04-02 11:41
Help! Please fix and I will send beer. :)

**Comment by muriloht** [comment] 2019-04-10 22:04
the same on latest 0.34.2.

the pivot table works only when the data column is of type numeric.

If I want to show a "COUNT(*)" it's OK:

| Activity     | Date 1  | Date 2  | Date 3  |
| ------------- |:----------|:----------|:----------:|
| A-1           |      1     |      0     |     0      |
| A-2           |      0     |      1     |      1     |
| A-3           |      0     |      0     |      1     |


But if I try to show some text (customer name for example) the table is blank:

| Activity     | Date 1  | Date 2  | Date 3  |
| ------------- |:----------|:----------|:----------:|
| A-1           |      customer X     |      0     |     0      |
| A-2           |      0     |      customer Y     |      customer Z     |
| A-3           |      0     |      0     |      customer X     |

**Comment by mazameli** [comment] 2019-05-30 18:55
I'm not sure when this stopped working or why, but I can confirm that trying to set a non-numeric column as the values to appear within the cells, nothing shows up.

Part of this is because usually when you create a pivot table like this, you typically need to summarize the column to be used as the values (e.g. using `count`), because otherwise there's a funny question of what should happen if there's more than one value that should appear in a given cell?

Using @muriloht's second table as an example, what would you expect to happen if more than one customer matches a given Activity + Date pair? Would you expect:
1. The cell to show a comma separated list of all the values that match? (`Customer X, Customer Z`)
2. The cell to show only one of the values that matches? (e.g. just the first value, like `Customer X`)
3. Something else I'm not thinking of?

@metabase/core-developers There appear to be quite a lot of folks who are reporting this as a problem for them. Do we think this is a valid way to use a pivot table (i.e. without any aggregating)? As one data point, I don't believe Google Sheets lets you do this.

**Comment by flamber** [comment] 2019-05-30 19:07
@mazameli Pretty sure it stopped working with PR #8552 - at least when I look through the code, the PR now has more requirements for the columns than before.

**Comment by muriloht** [comment] 2019-06-11 01:44
hi @mazameli ,

for my usecase the first option (show a comma separated list) is the best choice, but I understand that this can different for each user.

**Comment by mazameli** [comment] 2019-06-11 17:20
@tlrobinson This one has 22+ upvotes, is marked as a p1, and has the 0.33 milestone slapped on it. Mind if I assign it to you? Seems like @flamber spotted that things broke with pr #8552.

**Closed** 2019-07-26 20:42 UTC
Labels: Priority:P1, Type:Bug, Visualization/

**Comment by salsakran** [comment] 2019-07-30 21:48
Hello all, this is fixed in 0.32.10 which just went out.

**Comment by rravi6** [comment] 2023-07-31 21:01
Hi, I know it has been four years but I am working with a pivot table and this behavior (https://github.com/metabase/metabase/issues/8926#issuecomment-481884106) still applies... is there any fix?
