### ISSUE TITLE
Field filter dropdown

### ISSUE THREAD

**Issue by mariosergioti** [metabase/metabase#3161] opened 2016-08-10 19:56 UTC
Friends, I am trying to make a field Dropdown:

![capturar](https://cloud.githubusercontent.com/assets/20670250/17568404/022a7908-5f1a-11e6-9158-6529a206f573.PNG)

But it's not showing up the field;

How did:

card:
![capturar2](https://cloud.githubusercontent.com/assets/20670250/17568569/bfbbf186-5f1a-11e6-86d0-944a3a8f86f6.PNG)

![capturar3](https://cloud.githubusercontent.com/assets/20670250/17568574/c3fac182-5f1a-11e6-8bbc-31bad2432fc6.PNG)

reference/databases:
![capturar4](https://cloud.githubusercontent.com/assets/20670250/17568656/0c67d2e8-5f1b-11e6-91cd-f2989f456b0a.PNG)

If this is a bug report, please fill in the blanks:

*  I am using the **chrome** browser.
*  My computer's OS is **Windows 10**.
*  I'm running Metabase **JAR** [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.] and it is using the **MySQL** [Postgres / MySQL / H2 (default)] database.
*  My data is in a **MySQL** database. [Postgres / MySQL / Redshift / BigQuery / MongoDB / SQLite / SQL Server / etc.]
*  My Metabase version is **0.19.2**.

**Comment by federicokeen** [comment] 2016-08-15 23:43
@mariosergioti does https://github.com/metabase/metabase/issues/2739 explain your issue?

**Comment by salsakran** [comment] 2016-08-17 00:35
@mariosergioti do you get just an input field when you try to do that?

Due to an oversight,  SQL backed cards don't expose their field values for a dropdown yet. We'll be fixing this shortly.

If the above is what's happening, this is a dupe of #3120

**Comment by mariosergioti** [comment] 2016-08-18 11:12
Apparently it's the same goal.
I shall look for new updates so;
hug

**Comment by mariosergioti** [comment] 2016-08-18 11:14
@salsakran are several fields that this query back, however only set the Line field to the filter

**Comment by camsaul** [comment] 2016-09-03 00:59
From the conversation here it sounds like this is indeed a duplicate of #3120. @mariosergioti we're planning on fixing #3120 for our next release, Metabase 0.20, which should ship in the next few weeks.

Closing as duplicate.

**Closed by camsaul** 2016-09-03 00:59 UTC
Labels: Dashboards, Duplicate
