### ISSUE TITLE
Canceling a query in the UI should cancel the query in the database

### ISSUE THREAD

**Issue by nickcarenza** [metabase/metabase#7270] opened 2018-04-04 18:36 UTC
Hi Metabase team,

<table>
<tr>
<td width="25%">
<img src="https://user-images.githubusercontent.com/1222375/38326335-68fe7340-37fa-11e8-9dfd-f1d7089b6bb8.png" width="600">
</td>
<td width="75%">
I have noticed that when clicking the Cancel button, the query actually keeps running on the database (MySQL 5.7). This can have big performance impact when questions and dashboards auto-run with no filters or when writing and revising custom queries. Can the Cancel button be made to cancel the query in the database as well?
</td>
</tr>
</table>

Thank you for the great app.

**Comment by salsakran** [comment] 2018-04-04 18:41
Dupe of #2399 which is closed in master and will be going out in 0.29 next week.

**Closed by salsakran** 2018-04-04 18:41 UTC

**Comment by nickcarenza** [comment] 2018-04-04 20:05
Great news! And I apologize, I only searched open issues. 😞
