### ISSUE TITLE
Colorize map pins based on category or better affect SGV icons for each categories

### ISSUE THREAD

**Issue by DMDatak** [metabase/metabase#29471] opened 2023-03-23 09:34 UTC
**Is your feature request related to a problem? Please describe.**
Currently we have no choice, the pins are all the same color

**Describe the solution you'd like**
Add an option in Map Options for define color from a category
Or Better Add an option in Map Options for define a sgv icon for each categories

**Describe alternatives you've considered**
Currently I create two maps

**How important is this feature to you?**
My need concerns financing, I have 4 types of financing and I would like to see at a glance the distribution by type on my territory.

**Additional context**
![MetaBase](https://user-images.githubusercontent.com/99891554/227161945-c70386a2-8249-4931-bdd7-34ee9fc17edf.png)

**Comment by paoliniluis** [comment] 2023-03-29 22:18
I think your issue is a duplicate of https://github.com/metabase/metabase/issues/5973

**Closed by paoliniluis** 2023-03-29 22:18 UTC
Labels: Type:New Feature, .Needs Triage
