### ISSUE TITLE
Limit clause breaks query results

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#42509] opened 2024-05-10 13:53 UTC
e2e repro in this PR: #42455 (test is skipped for now)

-----

Repro steps:
1. Create a question based on orders table
2. Add custom expression aggregation: `Offset(Sum([Total]), -1)`
3. Add a breakout by Orders > Created At: Month
4. Add a breakout by Products > Category
5. Visualize the query as a table - [it works as expected (5 columns, 193 rows)](https://github.com/metabase/metabase/assets/6830683/db383048-07e5-4245-9424-220a30da5b58)
6. Go back to notebook editor
7. Add row limit 5
8. Visualize the query

The [results have only 4 rows and 3 columns](https://github.com/metabase/metabase/assets/6830683/879f53a0-b109-4611-a2c0-f53a8db6a182) and the table has been transposed compared to results in step 5.

It's expected that the results will look the same as in step 5, but limited to 5 first rows.

**Comment by camsaul** [comment] 2024-05-16 00:46
Turns out query results are actually just fine, but the FE is visualizing things as a pivot table by default. Disabling pivot visualization shows you 5 rows

![image](https://github.com/metabase/metabase/assets/1455846/0d63ba94-04ad-4af2-b83c-63f08ad7a4ab)

**Comment by camsaul** [comment] 2024-05-16 00:47
Note: you can easily verify that the QP returned 5 rows by looking at the response in the Network inspector

**Comment by camsaul** [comment] 2024-05-16 00:50
Closing as not a bug

See Slack discussion for more info https://metaboat.slack.com/archives/C06P22KS4JH/p1715820619367019

**Closed by camsaul** 2024-05-16 00:50 UTC
Labels: Type:Bug, Querying/Processor, .Backend, .Team/QueryProcessor
