### ISSUE TITLE
Day of the week translation error（Chinese Simplified） in DateTimePicker

### ISSUE THREAD

**Issue by linchixiong** [metabase/metabase#23294] opened 2022-06-13 03:44 UTC
**Describe the bug**
Day of the week translation error（Chinese Simplified） in DateTimePicker, when i updagred metabase from v0.42 to v0.43.2 (jar).
It's correct in v0.42.

**To Reproduce**
1. Go to any question view with DatetimePicker control

**Screenshots**
![image](https://user-images.githubusercontent.com/10416854/173274477-ca917bc8-421d-45bd-8ad8-2aa2056acb5f.png)

**Information about your Metabase Installation: 
`
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.39",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_181-b13",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_181",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.181-b13",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.31.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "oracle",
      "clickhouse"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.43.2",
      "date": "2022-05-31",
      "branch": "release-x.43.x",
      "hash": "433d533"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
`

**Comment by flamber** [comment] 2022-06-13 07:28
Duplicate of #22871

**Closed by flamber** 2022-06-13 07:28 UTC
Labels: Type:Bug, .Needs Triage
