### ISSUE TITLE
/api/databases endpoint idempotence

### ISSUE THREAD

**Issue by Matt-Yorkley** [metabase/metabase#11877] opened 2020-02-10 13:35 UTC
**Is your feature request related to a problem? Please describe.**
I'm configuring Metabase with Ansible and using the Metabase API to add new databases programmatically. The endpoint `(POST) /api/database` is not idempotent, so if I run the same task multiple times I end up with lots of duplicate entries. 

**Describe the solution you'd like**
It would be really nice if the endpoint responded with something else if the exact same data is posted twice, and used more standard REST response codes. Currently it always returns `200` (OK), but it would be nice to get: `201` (created) when a new record is added, and something like `409` (conflict) if the data being posted is the same as an existing record.

**Describe alternatives you've considered**
An endpoint that lets me check if a database with a given name is already registered would be nice as a different option. Part of the issue is that I'm running these tasks from nicely defined configs (with predefined database names), but my configs don't know the id of the databases after they're created. My other alternative is to query all databases and do some _really_ horrible json parsing, which is pretty awful in Ansible.

**How important is this feature to you?**
It would be really nice to have...

**Additional context**
Relevant docs: https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#post-apidatabase

**Comment by flamber** [comment] 2020-02-10 14:07
Hi @Matt-Yorkley 
It sounds like a duplicate of #11106, which has a PR being worked on right now #11228.
Please let me know if I misunderstood what you're asking for.

**Closed by flamber** 2020-02-10 14:07 UTC
Labels: .Needs Triage, Type:New Feature

**Comment by Matt-Yorkley** [comment] 2020-02-10 16:37
Ah sorry, I searched the open issues first, but I missed that one. :+1:
