### ISSUE TITLE
Incorrect text on admin panel for setting up bigquery 

### ISSUE THREAD

**Issue by FionnD** [metabase/metabase#13110] opened 2020-08-13 08:10 UTC
**Describe the bug**
When setting up a new bigquery table via the admin, the panel suggests you choose 'other' as the application type when you set up the google client keys. Google no longer offers this option in the dropdown menu. 

**Logs**
NA

**To Reproduce**
1. Go to the admin panel. 
2. Databases 
3. Add new database 
4. Choose bigquery 
5. Under CLIENT ID press _click here_

**Expected behavior**
The admin panel explantation suggests you should choose _other_ as the application type, I had to choose _desktop_ 

**Screenshots**
[One](https://drive.google.com/file/d/1c25WvOCyFaZLdD5IQosKSIwUvO4H_QCJ/view?usp=sharing) and [two](https://drive.google.com/file/d/1GaA2oTBxCjFu3WTi9CnzZWcHclysXUAi/view?usp=sharing) 

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.19.104+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "bigquery"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-12-19",
      "tag": "v0.34.0",
      "branch": "release-0.34.x",
      "hash": "1335215"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

**Severity**
Not severe. Maybe just confusing

**Comment by flamber** [comment] 2020-08-13 08:52
Duplicate of #12491 
Latest release is 0.36.3, which uses Service Accounts instead, so this doesn't apply anymore.

**Closed by flamber** 2020-08-13 08:52 UTC
Labels: .Needs Triage, Type:Bug
