### ISSUE TITLE
Impossible to select a joined attribute to filter

### ISSUE THREAD

**Issue by maximepvrt** [metabase/metabase#12246] opened 2020-04-02 11:58 UTC
![Capture d’écran 2020-04-02 à 13 55 55](https://user-images.githubusercontent.com/1840026/78246689-d819e880-74e9-11ea-9b7a-432faddc5a78.png)

No action if i click on status attribute since last release
No js error on console

```
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "10.0.2.13+0",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "10.0.2.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "10.0.2.13+0",
    "os.name": "Linux",
    "os.version": "5.6.0+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-03-31",
      "tag": "v0.35.0",
      "branch": "master",
      "hash": "3f96c47"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2020-04-02 12:02
Duplicate of #12221

**Closed by flamber** 2020-04-02 12:02 UTC
Labels: .Needs Triage, Type:Bug

**Comment by maximepvrt** [comment] 2020-04-02 12:06
sorry :/
