### ISSUE TITLE
Metabase users (Metabase v0.44.6) cannot change their language from the account settings

### ISSUE THREAD

**Issue by ritikasri23** [metabase/metabase#27696] opened 2023-01-15 20:34 UTC
**Describe the bug**

Metabase users (Metabase v0.44.6) cannot change their language from the account settings. The admin settings for "instance language" is English and as per the documentation, users can individually override this default language from their own account settings. Is this a known bug for Metabase version v0.44.6? 

**To Reproduce**
1. Go to Account settings as a non-admin user
2. Click on 'profile' 
3. Scroll down to 'English' from 'language' and press 'update'
4. See error : "You don't have permissions to do that"

**Expected behavior**
Metabase users should be able to change the language as and when required. 

**Screenshots**
Issue:

![image (5)](https://user-images.githubusercontent.com/29100044/212564923-dc8fe52c-9f50-4b2b-aa6c-41e527e2634e.png)

admin settings for "instance language":
<img width="1119" alt="Screenshot 2023-01-15 at 20 58 35" src="https://user-images.githubusercontent.com/29100044/212564634-35555ed8-0150-4c40-8281-66733c486128.png">

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

We have people from different nationalities working at our company and not being able to change the language is annoying for them. 

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "5.4.170+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake",
      "postgres",
      "bigquery-cloud-sdk",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-11-01",
      "tag": "v0.44.6",
      "branch": "release-x.44.x",
      "hash": "5c6ae21"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by ritikasri23** [comment] 2023-01-18 00:21
Thanks for looking into this @nemanjaglumac!
Yes, we have SSO enabled as it is much more secure and convenient and we use google SSO.

**Comment by ignacio-mb** [comment] 2023-11-21 18:04
Hi @ritikasri23,

I tested in a recent version (47.8) with SSO and couldn't reproduce either. Is this still a thing?

Thanks!

**Comment by fernandobrito** [comment] 2023-11-22 13:50
Hi! @ritikasri23 is no longer working at our company but I can follow up on it for her.

We have just tested it (0.47.2), and it worked. We cannot reproduce it anymore. Feel free to close this ticket.

**Comment by fernandobrito** [comment] 2023-11-22 13:52
Hi @ignacio-mb! @ritikasri23 is no longer working at our company but I can follow up on it for her.

We have just tested it on 0.47.2 and it worked. We cannot reproduce the original issue anymore. Feel free to close this issue.

**Closed** 2023-11-22 13:56 UTC
Labels: .Unable to Reproduce
