### ISSUE TITLE
can it support elasticsearch as a datasource

### ISSUE THREAD

**Issue by lovelivestyle1102** [metabase/metabase#13032] opened 2020-07-29 06:28 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**How important is this feature to you?**
Note: the more honest and specific you are here the more we will take you seriously. 

**Additional context**

**Comment by flamber** [comment] 2020-07-29 09:13
Duplicate of #1300

**Closed by flamber** 2020-07-29 09:13 UTC
Labels: .Needs Triage, Type:New Feature
