### ISSUE TITLE
Pie chart justification

### ISSUE THREAD

**Issue by atranel** [metabase/metabase#10837] opened 2019-09-07 19:59 UTC
I hope it is a bug as it was working well in 0.32. I have 0.33.2 and all my dashboards are ugly. It seems like legend and pie chart are not using full space but are trying to fit to left instead of using whole box. Now I get legend text cut early and a lot of empty space after the pie chart. I made the box large so I can see full text.
![obrazek](https://user-images.githubusercontent.com/42370527/64479698-b1e1d380-d1ba-11e9-8dd2-8161e94b8adb.png)

**Comment by paulrosenzweig** [comment] 2019-09-09 13:47
@atranel, this was a styling change requested in #10201 that shipped in 0.33.1. 

The new behavior attempts to keep the pie chart centered as much as possible. If the card shrinks, the legend can push the chart away from the middle.

I think this new behavior looks better at large widths, but I see your point that the whitespace on the right here feels awkward. cc @mazameli to see if he has any thoughts on how to balance large and small views.

**Comment by atranel** [comment] 2019-09-09 14:21
Thanks a lot. Meanwhile I will try to recompile 0.33.2 with piechart.css and piechart.jsx from 0.33.0

**Comment by paulrosenzweig** [comment] 2019-09-09 15:09
Here's the diff: https://github.com/metabase/metabase/pull/10406/files

The change was done centrally in `ChartWithLegend`, so it might be a bit risky to revert just that change and keep things working everywhere.

**Comment by atranel** [comment] 2019-09-09 20:26
Thank you for help. I copied all those 5 files from 0.33.0 to 0.33.2 and compiled it. It seems to work as I need.
![image](https://user-images.githubusercontent.com/42370527/64563958-d66fb400-d350-11e9-82e1-beab0f5c1346.png)

**Comment by atranel** [comment] 2019-09-10 07:46
Maybe introduce some kind of switch in Pie chart settings? :)

**Comment by salsakran** [comment] 2019-10-06 00:08
@mazameli  @kdoh should we treat legends in dashboards and the QB differently? 

I agree with @atranel that the previous version looks better in his dashboard. Is this a universal thing?

**Comment by Olaktal** [comment] 2019-10-10 10:18
We're facing the same issue. It is very annoying since our sales team make screenshot to send data to customers and having a truncated legend is not an option :( 

A switch in the pie chart settings looks like a great option !

**Comment by FWalder** [comment] 2019-11-12 21:39
We are also affected by this issue and it's a major cause of frustration to be honest.

In the first example it's anything but great since there is so much free space on the right while the legend is being cut off.

However, in the second example the whole thing goes bananas if I add a suffix ... :-) ... cut off legends, line breaks, misalignment.

![image](https://user-images.githubusercontent.com/52678499/68712409-f7949100-059b-11ea-90a8-aa2f7d50f51b.png)


Here is how it looked like in 0.31.2, which is pretty much what you would expect it to look like:
![image](https://user-images.githubusercontent.com/52678499/68712944-0891d200-059d-11ea-9dde-6427eec5505a.png)

**Comment by mazameli** [comment] 2019-11-12 21:45
@paulrosenzweig How hard do you think it'd be to revert to the old justification behavior _just for dashboard cards?_

**Comment by atranel** [comment] 2019-11-13 08:24
@FWalder If you have no trouble to recompile Metabase yourself I have temporary "fix" I use until it is fixed. I run 0.33.5 with old pie chart behaviour. 

**Change PieChart justification**
Download 0.33.0 source code and use 5 files controlling pie chart behavior from this version. Files to downgrade:

frontend/src/metabase/visualizations/components/ChartWithLegend.css
frontend/src/metabase/visualizations/components/ChartWithLegend.jsx
frontend/src/metabase/visualizations/visualizations/PieChart.css
frontend/src/metabase/visualizations/visualizations/PieChart.jsx
frontend/test/metabase/visualizations/components/Visualization-pie.unit.spec.js

**Comment by FWalder** [comment] 2019-11-13 10:25
@atranel , thanks for that hint. I'm not sure if that is an option for us, but I appreciate you taking the time to share experience!

**Comment by paulrosenzweig** [comment] 2019-11-18 14:52
As @mazameli suggested, I tweaked the display just for dashboard cards in #11314. The chart will no longer center itself so aggressively. Here's a screenshot Maz took:

![image](https://user-images.githubusercontent.com/2223916/68908308-b9b07d80-06ff-11ea-9ccb-ac6cf9f0fc3e.png)

That change will go out with the next release sometime this week I expect. I'm going to close this issue for now, but if the new layout is still problematic, please reopen so we can keep iterating!

**Closed by paulrosenzweig** 2019-11-18 14:52 UTC
Labels: Reporting/Dashboards, Type:UX, Visualization/Charts

**Comment by FWalder** [comment] 2019-11-18 15:46
Good stuff, looking forward to get my hands on 0.33.6 and test it. I'll provide feedback here if some issues remain. Thanks guys!

**Comment by atranel** [comment] 2019-11-18 16:31
Great. I will test for sure 😀

**Comment by atranel** [comment] 2019-11-20 13:56
Looks great here :)
Thanks for fix

**Comment by FWalder** [comment] 2019-11-20 16:06
I can confirm it looks good again. Thanks for the quick reaction!

![image](https://user-images.githubusercontent.com/52678499/69255459-23c19a80-0bb8-11ea-966b-02f3617625e1.png)
