### ISSUE TITLE
Cannot deactivate users with ID over 50

### ISSUE THREAD

**Issue by ebar0n** [metabase/metabase#17113] opened 2021-07-19 19:15 UTC
**Describe the bug**

From the 0.40.0 version, this bug was introduced, in the 0.39.3 or previous version, it's working normally.

**To Reproduce**

1. Go to admin
2. Click on people
3. Filter one user
4. Click the options for a user 
5. Click on deactivate user
4. See error, nothing happens for that action!

**Expected behavior**

Deactivate a user.

**Screenshots**

<img width="421" alt="Screen Shot 2021-07-19 at 14 06 27" src="https://user-images.githubusercontent.com/1896362/126213592-8783e782-5ea2-413c-9487-21515df001b1.png">

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.203",
    "vendor": "Google Inc."
  },
  ...
}
```

**Severity**

I can't upgrade until that bug will be fixed! Because I need constantly add and deactivate users.

**Comment by julesie** [comment] 2021-07-19 20:23
I can confirm I'm also experiencing the same behaviour since upgrading to 0.40.1

**Comment by paoliniluis** [comment] 2021-07-19 21:26
Hi @ebar0n @julesie, I can't reproduce it on my machine (new instance with docker). Can you please try to set up a new instance and try to give us some information about how to reproduce this? are you using some sort of embedding?

**Comment by ebar0n** [comment] 2021-07-21 15:05
Of course, I forget to specify that, I use Cloudflare.


I read that the CSP has problems with optimizers like rocket from Cloudflare, but I don't use it, only use Firewall and Access for protected these urls in my organization.

**Comment by paoliniluis** [comment] 2021-07-21 16:15
Thanks @ebar0n, then Cloudflare is the issue here. You should disable Cloudflare for everthing that goes to /api or /admin in Metabase, or only enable bot detection at the most. I'm going to close this issue as it does not seem to be related to Metabase but to how Cloudflare is acting as a reverse proxy here. This is the same as https://github.com/metabase/metabase/issues/17146

**Comment by julesie** [comment] 2021-07-21 16:26
@paoliniluis I don't have Cloudflare and am experiencing the same issue. 

In fact, I have two instances both hosted on Heroku, different subdomains of the same domain.

- One is our older instance which I upgraded to `0.40.1` this week and am experiencing this issue with.
- The other instance is about 10 days old and was a fresh install of `0.40.0` and it does not exhibit the same issue.

They have the same Heroku setup and I can't explain the differing behaviour.

**Comment by paoliniluis** [comment] 2021-07-21 16:39
@julesie ok, so can you please send the browser and backend logs when you perform these actions? thanks

**Comment by ebar0n** [comment] 2021-07-21 17:07
In my case, the solution don't can be disabled Cloudflare, the Firewall, and Access does not modify any part from the content, I think that must need exists another solution

**Comment by julesie** [comment] 2021-07-21 17:23
**Console Error**
![2021-07-21 at 18 21](https://user-images.githubusercontent.com/1015643/126532161-af4d271f-3e54-4b74-84c3-236582d79626.png)

**Diagnostic Info**
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_292-heroku-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_292-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.292-b10",
    "os.name": "Linux",
    "os.version": "4.4.0-1093-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.6 (Ubuntu 12.6-1.pgdg16.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.40.1",
      "date": "2021-07-14",
      "branch": "release-x.40.x",
      "hash": "ed8f9c8"
    },
    "settings": {
      "report-timezone": "Europe/London"
    }
  }
}

**Comment by julesie** [comment] 2021-07-21 17:30
Ok bit of a breakthrough. If I click 'Deactivate User' on the initial page of users displayed it works as expected but if I search for a user or paginate to second page and beyond it does not work.

**Comment by paoliniluis** [comment] 2021-07-21 18:03
Thanks, I just deployed a new instance in Heroku with 0.40.1 and can't reproduce this issue. Please send, if you can, specific environment variables that you have configured or the full browser logs (including network logs and console)

**Comment by julesie** [comment] 2021-07-21 18:43
There seems to be no consistency whatsoever in the console errors or network logs. 

I know this sounds weird but it seems like the 'Deactivate User' linke works for precisely the first 40 users (so all of the first page of records and part of the second page). The modal does not work after user #40 either via pagination or search.

**Comment by flamber** [comment] 2021-07-23 15:25
@ebar0n @julesie 
I have created 50 users on an old instance and have tried multiple ways, but cannot reproduce.

Various WAF/CDN/cache proxies can cause the weirdest problems - specially after upgrades: https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html
And try with Incognito-mode, so any browser extensions are not causing something either.

Check your browser developer Network-tab to see requests. Deactivating a user should send a `DELETE /api/user/:id` request.

**Comment by julesie** [comment] 2021-07-25 15:21
Thanks for trying to replicate it @flamber.

I have tried it on multiple browsers across multiple devices and I'm getting the same behaviour on all of them. It is a plain vanilla Heroku deployment so I'm not sure what WAF/CDN settings I could possibly change?

Also just to clarify the issue is that for anything after the first 40 users this modal window does not show when you click on 'Deactivate User' from the dropdown menu. We never even get the chance to send a delete request for a particular user.

![2021-07-25 at 16 18](https://user-images.githubusercontent.com/1015643/126904296-047d6066-764f-4a9e-9ee6-afa815e594d7.png)

**Example of modal that is not opening**
![2021-07-25 at 16 15](https://user-images.githubusercontent.com/1015643/126904270-d88ec312-1d6f-44b6-a18a-e0104758a9e2.png)

The only network activity I'm seeing on both successful and unsuccessful attempts is a get request to google analytics.

**Comment by flamber** [comment] 2021-07-25 16:38
@julesie Okay, it doesn't make any sense that you're only seeing activity to GA for the successful attempts.
There has to be a request to `DELETE /api/user/:id` otherwise it would not be successful in deactivating a user.
I think you need to export the HAR in the Network-tab, so everything is captured.
I have a feeling that it has nothing to do with after 40th user, but perhaps there's a character in one of the users that breaks something.

@lcmartinezdev Since you're upvoting the issue, I'm guessing you're having this problem too. Can you please provide as many details as possible, since we cannot reproduce.

**Comment by julesie** [comment] 2021-07-25 16:40
Sorry @flamber I may have confused you in my last post. I see a delete request if I actually follow through and click on the red 'Deactivate' button on the modal. The issue is that the modal itself fails to appear for the users we are having issues with.

**Comment by flamber** [comment] 2021-07-25 17:03
@julesie Yes, I understand that. My guess is still that it has something to do with the response of the second list.
But without logs, errors or anything else to go on, then it's close to impossible to figure out what is going wrong.
Feel free to setup a new instance and try to reproduce, if you cannot share anything from your existing instance.

**Comment by julesie** [comment] 2021-07-26 06:37
@flamber I've generated the HAR exports of both a user where the modal loads and one where it does not. I have just masked our domain name in both files.

[with_modal_har.txt](https://github.com/metabase/metabase/files/6876131/with_modal_har.txt)
[no_modal_har.txt](https://github.com/metabase/metabase/files/6876132/no_modal_har.txt)

**Comment by flamber** [comment] 2021-07-26 10:12
@julesie Okay, so I can see that the URL is `/admin/people/81` for both, which must mean that you're not just going to Admin > People > paginating to next page and trying to deactivate the user. Seems like you're doing other things first, which might be the root cause of the problem, which is why I'm asking for a complete HAR of the entire process.

It opens the modal for `/admin/people/164/deactivate` but not `/admin/people/212/deactivate`
My guess is that it's failing to get complete results for the list of users where 212 is included. But there should be errors either in the browser developer console or Metabase > Admin > Troubleshooting > Logs.

If you manually go directly to `/admin/people/212/deactivate` does that work?

**Comment by jcorrea-tkww** [comment] 2021-07-29 07:33
It didn't work for me, only if the user_id you want to de-activate is in the first 50

**Comment by flamber** [comment] 2021-07-30 16:26
Okay, so this has nothing to do with CSP. Very related to #17164. But perhaps we should handle it more graceful in the frontend.

**Workaround:**
Try to deactivate a user, where it just shows a dimmed down screen because of overlay. Note the ID of the user in the URL (example `/admin/people/60/deactivate`, where `60` is the user ID).
Open your browser developer console and adjust this command with your Metabase URL and replace `123` with the user ID.
```
await fetch("https://metabase.example.com/api/user/123", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "method": "DELETE", "mode": "cors" });
```

**Reproduce:**
1. Create 60 users
<details><summary>Fetch example</summary>

```
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"01","email":"example01@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"02","email":"example02@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"03","email":"example03@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"04","email":"example04@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"05","email":"example05@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"06","email":"example06@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"07","email":"example07@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"08","email":"example08@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"09","email":"example09@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"10","email":"example10@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"11","email":"example11@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"12","email":"example12@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"13","email":"example13@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"14","email":"example14@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"15","email":"example15@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"16","email":"example16@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"17","email":"example17@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"18","email":"example18@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"19","email":"example19@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"20","email":"example20@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"21","email":"example21@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"22","email":"example22@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"23","email":"example23@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"24","email":"example24@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"25","email":"example25@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"26","email":"example26@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"27","email":"example27@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"28","email":"example28@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"29","email":"example29@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"30","email":"example30@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"31","email":"example31@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"32","email":"example32@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"33","email":"example33@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"34","email":"example34@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"35","email":"example35@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"36","email":"example36@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"37","email":"example37@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"38","email":"example38@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"39","email":"example39@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"40","email":"example40@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"41","email":"example41@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"42","email":"example42@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"43","email":"example43@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"44","email":"example44@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"45","email":"example45@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"46","email":"example46@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"47","email":"example47@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"48","email":"example48@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"49","email":"example49@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"50","email":"example50@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"51","email":"example51@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"52","email":"example52@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"53","email":"example53@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"54","email":"example54@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"55","email":"example55@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"56","email":"example56@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"57","email":"example57@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"58","email":"example58@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"59","email":"example59@test.test"}', "method": "POST", "mode": "cors" });
await fetch("http://localhost:3000/api/user", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": '{"first_name":"ZExample","last_name":"60","email":"example60@test.test"}', "method": "POST", "mode": "cors" });
```

</details>

2. Go to Admin > People - paginate to third page, 51 - 60, for user 60 click the three-dots > Deactivate user
Or just go to this URL `/admin/people/60/deactivate`
3. It will just show a dimmed overlay without a modal. This is because the modal makes a request to `/api/user?include_deactivated=true` before showing (to populate it with data), but since the API is limited to 50 results, then the user we're trying to deactivate is not part of the results and the modal fails with showing any errors anywhere.
![image](https://user-images.githubusercontent.com/1447303/127682287-d52bc98d-3d5d-410e-84e2-049efc3c31ab.png)

**Closed** 2021-07-31 01:16 UTC
Labels: .Frontend, .Regression, Admin/People, Priority:P1, Type:Bug
