### ISSUE TITLE
Read-only profile switch to "New question" mode after applying a filter on native query

### ISSUE THREAD

**Issue by p-bizouard** [metabase/metabase#11225] opened 2019-10-29 15:36 UTC
**Describe the bug**
Native query question switch to edit mode ("New question") by applying a drop-down filter. This produce an error "You do not have permissions to run this query." for read-only profiles.

**Logs**
None

**To Reproduce**
1. Go to a saved question that provide drop-down filter (/question/QUESTION_ID)
2. Select one or more value on the filter
3. Play the query
4. The query fully load as expected, but the url of the page switch to "/question?FILTER_NAME=FILTER_VALUE"
5. Play the same query again (reload button next to "save")
6. See error "You do not have permissions to run this query."

**Expected behavior**
The query should not switch to edit mode and stay to the url "/question/QUESTION_ID?FILTER_NAME=FILTER_VALUE"

**Screenshots**
Field filter configuration :
![image](https://user-images.githubusercontent.com/3728646/67782165-bd3dd680-fa68-11e9-84a0-f6aa459c9302.png)

Profile configuration : 
![image](https://user-images.githubusercontent.com/3728646/67782659-62f14580-fa69-11e9-9c6f-750564ff0a3d.png)
Then "Data access" to the dedicated materialized view.

**Information about your Metabase Installation:**
System info:
Metabase v0.33.4
{"java.runtime.name" "Java(TM) SE Runtime Environment",
"java.runtime.version" "1.8.0_101-b13",
"java.vendor" "Oracle Corporation",
"java.vendor.url" "http://java.oracle.com/",
"java.version" "1.8.0_101",
"java.vm.name" "Java HotSpot(TM) 64-Bit Server VM",
"java.vm.version" "25.101-b13",
"os.name" "Linux",
"os.version" "3.10.0-693.11.6.el7.x86_64",
"user.language" "fr",
"user.timezone" "Europe/Paris"}
Database : PostgreSQL

**Severity**
Read-only profiles can't use drop down filters

**Comment by flamber** [comment] 2019-11-07 22:54
Hi @p-bizouard 
I'm cannot reproduce your issue. When I set a collection to "View collection" for a user, then changing the filters does not active Edit-mode, where the user can save the question.
Can you give more details on what the Admin > Permissions are for the database and collections?
Even better if you can reproduce it with Sample Dataset, since we all have access to that.

**Comment by flamber** [comment] 2020-02-26 11:36
Closing as duplicate of #11964, since it contains more information.

**Closed by flamber** 2020-02-26 11:36 UTC
Labels: .Unable to Reproduce, Administration/Permissions, Querying/Native, Type:Bug
