### ISSUE TITLE
SQL Server - Queries not executing in recent versions

### ISSUE THREAD

**Issue by roemhildtg** [metabase/metabase#7408] opened 2018-04-23 17:05 UTC
I just updated to the recent version from version 0.25.2 and have tested the release candidate as well, but I'm running into a problem. Queries in the browser sit and spin until they time out. On the console, the following messages are shown:

![image](https://user-images.githubusercontent.com/5471079/39141753-4bd20414-46ee-11e8-8bf0-5293fc62c410.png)

- Your browser and the version: Chrome - latest
- Your operating system: Windows 7 x64/Windows Server 2008
- Your databases: SQL Server 2017
- Metabase version:0.29 - Also tried 0.28.6 which has the same result
- Metabase hosting environment: java - jar file
- Metabase internal database: H2 (Default)

- *Repeatable steps to reproduce the issue*
1. Run the jar file
2. Wait for initialization to complete
3. Run a query

**Comment by mazameli** [comment] 2018-04-23 17:08
This is with any query you run? Are you running a native query or one from the graphical query builder? You weren't running into this problem on 0.25.2?

**Comment by roemhildtg** [comment] 2018-04-23 17:10
I was not having a problem running on 0.25.2. I'm able to start that jar up and the queries are executing. It does appear to happen with any query I run.

**Comment by roemhildtg** [comment] 2018-04-23 17:14
When I run a simple query that returns Raw data, this is the console log:

![image](https://user-images.githubusercontent.com/5471079/39142301-e470e18a-46ef-11e8-80e0-c9a7c0fb3ef3.png)

**Comment by jornh** [comment] 2018-08-03 18:55
Between 0.25.2 and now the database driver was changed from jTDS to Microsoft’s. Turns out the old driver was more forgiving on one specific point.

There’s a very good write up in https://github.com/metabase/metabase/issues/7597 of the problem that affects setups where SQL Server is setup with a dynamic port. 

The fix allowing you to specify a blank port setting as described in #7597 is available in version 0.30.0 RC1 just out. Would be very good to know if that works for you! 😀

**Comment by flamber** [comment] 2020-05-24 00:49
Closing, since there's no further activity and it was very likely caused by dynamic ports - fixed in 0.30.0

**Closed by flamber** 2020-05-24 00:49 UTC
Labels: Database/SQLServer, OS:Windows
