### ISSUE TITLE
Making Alerts more frequent

### ISSUE THREAD

**Issue by DonovnOptalitix** [metabase/metabase#14081] opened 2020-12-15 13:20 UTC
Would it be possible to make the alerts more frequent then just being sent once per hour,

Would it be possible to sent out alerts every 15 minutes, 30 minutes or when there is an alert, it send out the notification at that time?

**Comment by flamber** [comment] 2020-12-15 13:29
Duplicate of #6648

**Closed by flamber** 2020-12-15 13:29 UTC
Labels: .Needs Triage, Type:Bug
