### ISSUE TITLE
Dashboard Time Filter vs Question Filter Error

### ISSUE THREAD

**Issue by TomUssery** [metabase/metabase#4899] opened 2017-04-27 12:05 UTC
While connected to Google Analytics

I set up a question for display on my dashboard
 - Filter: Date after Jan 1 2017
   View Sessions 
   Result as a Number
   Dashboard label  = Sessions Month To Date
- Desired end state -  two tiles where one shows year to date, the other by month that is selected as a dashboard filter on Month and Year

However, the date filter within the original question is causing the dashboard level filter to throw an error is message. is this by design?

**Comment by salsakran** [comment] 2017-05-04 01:50
what is the error that is returned?

**Comment by TomUssery** [comment] 2017-05-04 12:42
![error msg](https://cloud.githubusercontent.com/assets/27392006/25703910/838cfebe-30a5-11e7-97b1-f00ba189a7b1.JPG)
As seen on the dashboard

**Comment by sashankQ** [comment] 2017-10-26 23:37
@TomUssery  @salsakran  any update on this issue? I am also stuck in this situation.

**Comment by flamber** [comment] 2020-05-24 19:31
Duplicate of #4766

**Closed by flamber** 2020-05-24 19:31 UTC
Labels: Database/Google Analytics, Priority:P3, Querying/Parameters & Variables, Reporting/Dashboards, Type:Bug
