### ISSUE TITLE
Setup "Last name" field is overflown in mobile screens

### ISSUE THREAD

**Issue by enolal826** [metabase/metabase#18870] opened 2021-11-05 14:22 UTC
**Describe the bug**
The `Last name` field in the setup page is overflown in mobile screens.

**Logs**
NA

**To Reproduce**
1. Go to the setup page with a mobile screen size.
2. Select a language.
3. In the user information page, `First name` and `Last name` fields are in the same row, which causes `Last name` to be overflown. 

**Expected behavior**
In mobile screens, `Last name` should be in another row.

**Screenshots**
![metabase-lastname](https://user-images.githubusercontent.com/51820585/140524415-715723e3-59dc-4847-a999-e31bd9c3943f.png)

**Information about your Metabase Installation:**

- Your browser and the version: 95.0
- Your operating system: macOS (Apple Sillicon)
- Your databases: NA
- Metabase version: Metabase v0.41.1
- Metabase hosting environment: JAR file on macOS
- Metabase internal database: H2

**Severity**
Not severe at all

**Comment by flamber** [comment] 2021-11-05 14:23
Duplicate of #18411

**Closed by flamber** 2021-11-05 14:23 UTC
Labels: Type:Bug, .Needs Triage
