### ISSUE TITLE
Issues with Dates in Month and Quarter values 

### ISSUE THREAD

**Issue by shyam2794** [metabase/metabase#5584] opened 2017-07-26 08:14 UTC
I am facing the same issue , my chart starts with december'15 but the data actually is from Jan 2016 , 
But when i mouse over the bar the tool tip show it as Jan'16 , the same happens for year and quarter  

![screenshot from 2017-07-26 13-43-22](https://user-images.githubusercontent.com/30238125/28611133-6ab9ae7e-7208-11e7-94f7-6d506bc6171e.png)

![screenshot from 2017-07-26 13-39-02](https://user-images.githubusercontent.com/30238125/28610988-ecb79d1a-7207-11e7-8820-e36298cf0062.png)

**Comment by salsakran** [comment] 2017-07-26 19:53
which version of the app are you on, and what are 
1. your reporting timezone if one is set
2. the timezone on your server
3. the timezones of the underlying data

**Comment by mazameli** [comment] 2017-07-26 20:15
Possibly a dupe of https://github.com/metabase/metabase/issues/5324 or https://github.com/metabase/metabase/issues/2517

We have a number of issues reporting a symptom where the x-axis label is wrong (off by 1 unit), but the tooltips are right.

**Comment by shyam2794** [comment] 2017-07-27 13:21
The issue has been fixed , the report timezone were not set previously now its working absolutely fine . I just changed the report timezone to Asia/Calcutta . 

/home/emperor/Desktop/project/Cygnus /screenshots/Screenshot from 2017-07-27 18-50-25.png

**Closed** 2017-08-01 01:06 UTC
Labels: Bug, Priority/P1, Timezones/Calendars, Visualization
