### ISSUE TITLE
Have to refresh page before seeing newly created Metrics

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#5796] opened 2017-08-23 00:46 UTC
In master. Create a new Metric in the Admin Panel, and then exit to Query Builder. New Metrics do not show up until you refresh the page.

I would assume this applies to Segments as well.

I'm guessing this is another bug with the new (ish) API response caching. It seems like we added the caching but did not add any logic to *ever* mark it dirty  😕

**Comment by ranquild** [comment] 2022-01-04 15:07
Couldn't reproduce these 2 issues. Closing

**Closed by ranquild** 2022-01-04 15:07 UTC
Labels: Type:Bug, Priority:P2, Administration/Metrics & Segments, Querying/GUI
