### ISSUE TITLE
One table has 59 columns missing out of 72 in metabase

### ISSUE THREAD

**Issue by niparis** [metabase/metabase#6133] opened 2017-10-10 02:17 UTC
Our main user table has 72 columns. 

Since updating to the latest version of Metabase, we can only see 13 columns in Metabase.

- It's still possible to query those "missing columns" from Metabase using the SQL interface
- Those 13 columns are the most recent columns added to the table.
- We've tried using the "Sync database schema now" and "Re-scan field values now" with no results.

**Environment info**
- Your browser and the version: Chrome 61.0.3163.100
- Your operating system: OS X
- Your databases: Postgres 9.6.2
- Metabase version: 0.26.1 (worked fine on 0.25.2)
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres 9.6.2

**Comment by Jyggafey** [comment] 2017-10-12 15:22
We have a similar? issue with Postgres 9.6 on 0.26.1
For two of our tables we get the following log WARN output:
```
10-12 17:02:21 DEBUG analyze.table-row-count :: Set table row count for Table 1301 'aschema.TableA' to 24020
10-12 17:04:43 WARN middleware.add-implicit-clauses :: Table 'TableA' has no Fields associated with it.
10-12 17:04:43 WARN query-processor.annotate :: There are fields we (maybe) weren't expecting in the results: #{:[lists all the fields here]}
Expected: #{}
Actual: #{[lists all the fields again]}
```

The Query Builder UI has no filter or group functionality for those Tables because the query_metadata json response contains fields: []

**Comment by andlt** [comment] 2018-01-03 14:02
We're having the same issue here. Several columns won't load in the raw dataset and will not be displayed in the query builder options; but if you query them by writing SQL the columns are correctly displayed.

**Comment by xjzhou** [comment] 2018-10-17 09:40
We have a similar issue  after upgraded to 0.30.3

![image](https://user-images.githubusercontent.com/1255410/47077499-a51b6080-d233-11e8-9c30-b476d4213938.png)

After click "Analyze the results of this query"  we get the following log WARN output:

2018-10-17 17:37:02,375 [clojure-agent-send-off-pool-3755] WARN metabase.query-processor.annotate - There are fields we (maybe) weren't expecting in the results: #{:ID :PRODUCT_ID :QUANTITY :SUBTOTAL :DISCOUNT :TOTAL :USER_ID :TAX :CREATED_AT}
Expected: #{}
Actual: #{:ID :PRODUCT_ID :QUANTITY :SUBTOTAL :DISCOUNT :TOTAL :USER_ID :TAX :CREATED_AT}

**Comment by kakavi** [comment] 2018-12-13 08:31
I also have the same issue when using the querybuilder, it thros an error 'Table '_343_xxxxxxxx' has no Fields associated with it.' yet when i query the same table in native sql.. i get the fields

**Comment by salsakran** [comment] 2019-08-05 05:12
@kakavi are you still seeing this?

This is a bit hard to reproduce as what it means is that the database sync operation failed somewhere along the way.

We added a troubleshooting section to the admin panel in 0.32, and you can see the results (and any errors) of the sync process there. 

Closing since the last report was 8 months ago, and we need a more concrete error message before we can really help. 

If you see this again, please look at the admin panel and copy+paste any error messages in the sync tasks here

**Closed by salsakran** 2019-08-05 05:12 UTC
Labels: Metadata/Sync, Priority:P1, Type:Bug
