### ISSUE TITLE
Specify which columns to use in chart

### ISSUE THREAD

**Issue by spectr** [metabase/metabase#1419] opened 2015-10-31 18:51 UTC
Since there doesn't seem to be a way to "SELECT col1, col2 FROM table" with the query builder one should be able to specify the columns to be used in a chart's x and y coordinates like Re:dash allows.

**Comment by agilliland** [comment] 2015-11-26 01:00
closing this as a dupe of #612 .

**Closed by agilliland** 2015-11-26 01:00 UTC
