### ISSUE TITLE
AWS DocumentDB support

### ISSUE THREAD

**Issue by nodesocket** [metabase/metabase#13080] opened 2020-08-07 06:21 UTC
Currently breaks with:

```
Command failed with error 305: 'Aggregation project operator not supported: '$let'' on server xxxyyyzzz.us-east-2.docdb.amazonaws.com:27017. The full response is { "ok" : 0.0, "errmsg" : "Aggregation project operator not supported: '$let'", "code" : 305 }
```

There are differences between MongoDB and AWS DocumentDB. It might be good to just add a new type of database **DocumentDB** and then write a driver that works for it specifically.

**Comment by flamber** [comment] 2020-08-07 08:47
Duplicate of #10943

**Closed by flamber** 2020-08-07 08:47 UTC
Labels: .Needs Triage, Type:New Feature
