### ISSUE TITLE
Filter on aggregation

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1444] opened 2015-11-04 18:57 UTC
It would be useful to be able to, for example, say "show me all the users who have a sum of orders totals greater than $25". Currently the best we can do is "show me the top N users by the sum of their order totals" if we sort by the aggregation then limit.

**Comment by salsakran** [comment] 2015-11-04 18:59
+1

**Comment by iwaffles** [comment] 2015-11-04 19:38
:+1:

**Comment by camsaul** [comment] 2015-11-18 22:38
Duplicate of #1207

**Closed by camsaul** 2015-11-18 22:38 UTC
Labels: enhancement, proposal
