### ISSUE TITLE
No message on loginpage if login incorrect

### ISSUE THREAD

**Issue by mschmidt291** [metabase/metabase#11448] opened 2019-12-05 12:23 UTC
**Describe the bug**
When a user tries to login e.g. with a incorrect e-mail or an incorrect password, metabase should fire an information/error message which tells the user his credentials are wrong.

**Expected behavior**
I expect a warning or info message on the login page after clicking login, telling me my credentials are wrong

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: **Brave Browser 1.0.1**
- Your operating system: **Arch Linux**
- Your databases: **MySQL, BigQuery**
- Metabase version: **0.33.6**
- Metabase hosting environment: **Docker / Kubernetes with Helm Chart**
- Metabase internal database: **MySQL**

**Comment by flamber** [comment] 2019-12-05 14:17
Hi @mschmidt291 
Are you using regular login, or LDAP or Google?
Do you see the failed login error in the Metabase log? Admin > Troubleshooting > Logs
Are you seeing any errors in your browser console?
This is how it looks with wrong email and/or password with Firefox:
![image](https://user-images.githubusercontent.com/1447303/70242166-fa674980-1735-11ea-9f5e-698c7c515dd9.png)

**Comment by mschmidt291** [comment] 2019-12-05 14:25
@flamber 
Yes, the development console is showing a 400 on /api/session when using a non-existent e-mail
The metabase log says the following:
`2019-12-05T15:23:58+01:00 DEBUG metabase.middleware.log POST /api/session 400 2.4 ms (1 DB calls)
{:errors {:password "did not match stored password"}}`

And no, i'm not using ldap or google, it's the regular metabase login.

**Comment by flamber** [comment] 2019-12-05 14:41
@mschmidt291 
Okay, so even when that error is shown in the console, it still doesn't show a visible message?
Does it also happen if you input correct email, but incorrect password?
Is the email valid? - meaning the structure - i.e. this is invalid `email@example.123`

**Comment by mschmidt291** [comment] 2019-12-06 07:07
@flamber 
Yep, the E-Mail is a valid one. I also tried to use my E-Mail and a wrong password, but there is no error message shown.

**Comment by flamber** [comment] 2019-12-06 17:16
@mschmidt291 
That's so strange. I can only reproduce if I use an email that looks like `email@example.com2` (invalid) and `email@grønland.tld` (actually valid, but really uncommon)
Can you try a different browser (Chromium or Firefox) without any extensions, just to see if it's a problem with Brave or some extension?
I can see that work being done on an updated login form (#11087), and I've tested that too, and then it warns me on the two edge-case emails I tried, so I guess this might be fixed by that, if it's not a problem with your browser/extension.

**Comment by mschmidt291** [comment] 2019-12-09 08:32
@flamber 
Yeah it's very strange.. I actually tried every possible browser - also everyone in our company has this problem, and they all use different browsers and extensions. So it's a issue on metabase' end, or maybe some bug with the docker instance?

**Comment by mschmidt291** [comment] 2019-12-10 07:57
@flamber 

Diagnostic Info:
`{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.14.138+",
    "user.language": "en",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "bigquery"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "date": "2019-11-19",
      "tag": "v0.33.6",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}`

The Site URL in settings is correct. 
And thanks for all your help and effort. I hope this can be solved or fixed

**Comment by kdoh** [comment] 2020-01-13 15:52
Should be fixed by #11087

**Comment by mschmidt291** [comment] 2020-01-14 07:58
@kdoh Thanks for all the effort. But it seems like the commit is not included in 0.34.1?

**Comment by flamber** [comment] 2020-02-05 16:20
@mschmidt291 Sorry for the late response. The PR #11087 is part of larger re-write, so currently it's scheduled for 0.35.0 (no due date yet). I'm going to close this, since the PR has already been merged to `master`.

**Closed by flamber** 2020-02-05 16:20 UTC
Labels: Administration/Auth, Type:Bug
