### ISSUE TITLE
Variable gets replaced by question mark

### ISSUE THREAD

**Issue by aleloi** [metabase/metabase#35275] opened 2023-11-01 10:47 UTC
### Describe the bug

I tried out metabase with ```docker run -d -p 3000:3000 metabase/metabase```, entered my google service account key and connected to my bigquery database. Queries without variables work fine, but variables are replaced by question mark according to the BigQuery project history.

Here is my query:

```
SELECT
  `my_table.total_sales_per_day_agg`.`total_sales_this_month_all_customers` AS `total_sales_this_month_all_customers`,
  `my_table.total_sales_per_day_agg`.`invoice_date` AS `invoice_date`
FROM
  `my_table.total_sales_per_day_agg`
WHERE TIMESTAMP(invoice_date) => ({{ date_min }}) and TIMESTAMP(invoice_date) <= ({{ date_max }})
LIMIT
  1048575
```

Here is what metabase says that my query will be after expanding variables:

```
SELECT
  `my_table.total_sales_per_day_agg`.`total_sales_this_month_all_customers` AS `total_sales_this_month_all_customers`,
  `my_table.total_sales_per_day_agg`.`invoice_date` AS `invoice_date`
FROM
  `my_table.total_sales_per_day_agg`
WHERE TIMESTAMP(invoice_date) => (timestamp "2023-08-03 00:00:00Z") and TIMESTAMP(invoice_date) <= (timestamp "2023-11-30 00:00:00Z")
LIMIT
  1048575
```

Here is what BigQuery says my query actually was:

```
-- Metabase:: userID: 1 queryType: native queryHash: afecd4e18e2f1fcc658a7fa0006782460caf7026766b15a4e6e1640b1db0e027
SELECT
  `my_table.total_sales_per_day_agg`.`total_sales_this_month_all_customers` AS `total_sales_this_month_all_customers`,
  `my_table.total_sales_per_day_agg`.`invoice_date` AS `invoice_date`
FROM
  `my_table.total_sales_per_day_agg`
WHERE TIMESTAMP(invoice_date) => (?) and TIMESTAMP(invoice_date) <= (?)
LIMIT
  1048575
```

and here is the sql error:

```
400 Bad Request POST https://www.googleapis.com/bigquery/v2/projects/<project>/queries { "code": 400, "errors": [ { "domain": "global", "location": "q", "locationType": "parameter", "message": "Syntax error: Expected end of input but got \"=>\" at [7:31]", "reason": "invalidQuery" } ], "message": "Syntax error: Expected end of input but got \"=>\" at [7:31]", "status": "INVALID_ARGUMENT" }
```

### To Reproduce

Run as `docker run -d -p 3000:3000 metabase/metabase`

select 'Swedish language' for Metabase ui

enter google service account and project for accessing bigquery

make a query against bigquery with variables inside

### Expected behavior

variables sent to bigquery correctly

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "6.2.0-35-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-10-26",
      "tag": "v0.47.6",
      "branch": "?",
      "hash": "3a7ed7a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

I will not use metabase if variables do not work

**Comment by paoliniluis** [comment] 2023-11-03 11:15
Hi, I just tested this and can't reproduce what you're mentioning above @aleloi , can you double check?
![image](https://github.com/metabase/metabase/assets/1711649/8ece446a-bed4-429e-91fe-b23ed55ad77d)

**Comment by zbodi74** [comment] 2023-11-30 11:47
@aleloi, I'm closing this as the issue appears to be due to a typo in the comparison operator in you example.
It should be written as `>=` not `=>`. Feel free to reopen if you find it otherwise.

**Closed by zbodi74** 2023-11-30 11:47 UTC
Labels: .Unable to Reproduce

**Comment by paoliniluis** [comment] 2023-11-30 12:04
@Tony-metabase isn’t this the same issue you created some time ago?
