### ISSUE TITLE
Self-referencing columns broken on Oracle and Redshift

### ISSUE THREAD

**Issue by senior** [metabase/metabase#8510] opened 2018-09-12 17:32 UTC
While putting together a test to reproduce https://github.com/metabase/metabase/issues/8371 I found that Metabase doesn't currently allow self-referencing columns with Oracle and Redshift. For Oracle at least, it might be due to my usage of a limit clause. When we have a limit with Oracle, we wrap the query with another query that includes the `rownum` limit.

For now I have disabled running the tests on those two backends (will include a link to the code once it's up) as it was broken before `0.30.1` which was referenced in https://github.com/metabase/metabase/issues/8371

**Comment by MarkRx** [comment] 2018-09-12 18:04
I'm curious - what's the exact use case you are running in to this error with? Here is an example of a self-referencing column being used in 0.29 with Oracle 12.2:

Jira Issue references Jira Issue via "Parent"

![jira_parent_smudge](https://user-images.githubusercontent.com/17504314/45444111-95d55000-b694-11e8-8bfb-1dd0d3858b90.png)

**Comment by senior** [comment] 2018-09-12 19:05
@MarkRx I was using a remapping with a self-referencing foreign key. So it was a `users` table with `[id, name, last_login, password, created_by]` columns where `created_by` was a reference to `id` on that same users table. I used the remapping to replace the `created_by` id with the name of the user that created this user.

**Comment by senior** [comment] 2018-10-09 17:50
This is also broken on Vertica. This wasn't caught originally because there was a bug in our CI config that was causing Vertica tests to not run. Now that the config issue has been fixed, we see
```
SQLSyntaxErrorException:
 Message: [Vertica][VJDBC](4901) ERROR: Table name "ta_self_referencing_user_users" specified more than once
 SQLState: 42712
 Error Code: 4901
ERROR generic-sql.query-processor :: nil
{:status :failed,
 :class java.lang.Exception,
 :error "[Vertica][VJDBC](4901) ERROR: Table name \"ta_self_referencing_user_users\" specified more than once",
 :stacktrace
 ["driver.generic_sql.query_processor$do_with_try_catch.invokeStatic(query_processor.clj:527)"
  "driver.generic_sql.query_processor$do_with_try_catch.invoke(query_processor.clj:519)"
  "driver.generic_sql.query_processor$execute_query.invokeStatic(query_processor.clj:579)"
  "driver.generic_sql.query_processor$execute_query.invoke(query_processor.clj:575)"
  "driver$eval34853$fn__35040$G__34842__35047.invoke(driver.clj:105)"
  "query_processor$execute_query.invokeStatic(query_processor.clj:60)"
  "query_processor$execute_query.invoke(query_processor.clj:54)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47788.invoke(mbql_to_native.clj:28)"
  "query_processor.middleware.annotate_and_sort$annotate_and_sort$fn__45179.invoke(annotate_and_sort.clj:34)"
  "query_processor.middleware.limit$limit$fn__47730.invoke(limit.clj:15)"
...
SQLSyntaxErrorException:
 Message: [Vertica][VJDBC](4901) ERROR: Table name "ta_self_referencing_user_users" specified more than once
 SQLState: 42712
 Error Code: 4901
ERROR generic-sql.query-processor :: nil
{:status :failed,
 :class java.lang.Exception,
 :error "[Vertica][VJDBC](4901) ERROR: Table name \"ta_self_referencing_user_users\" specified more than once",
 :stacktrace
 ["driver.generic_sql.query_processor$do_with_try_catch.invokeStatic(query_processor.clj:527)"
  "driver.generic_sql.query_processor$do_with_try_catch.invoke(query_processor.clj:519)"
  "driver.generic_sql.query_processor$execute_query.invokeStatic(query_processor.clj:579)"
  "driver.generic_sql.query_processor$execute_query.invoke(query_processor.clj:575)"
  "driver$eval34853$fn__35040$G__34842__35047.invoke(driver.clj:105)"
  "query_processor$execute_query.invokeStatic(query_processor.clj:60)"
  "query_processor$execute_query.invoke(query_processor.clj:54)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47788.invoke(mbql_to_native.clj:28)"
  "query_processor.middleware.annotate_and_sort$annotate_and_sort$fn__45179.invoke(annotate_and_sort.clj:34)"
  "query_processor.middleware.limit$limit$fn__47730.invoke(limit.clj:15)"
```

**Comment by jeff303** [comment] 2021-02-04 18:03
@senior , any chance you can capture the DB mapping screen for an instance of this problem happening in Redshift?  I tried to reproduce, but am still somewhat new so I may not have understood the setup fully.

DDL/DML:

```CREATE TABLE schema_name.SELF_REFERENCING_COL(id BIGINT NOT NULL PRIMARY KEY, val VARCHAR(255), parent_id BIGINT NULL);
INSERT INTO schema_140.SELF_REFERENCING_COL VALUES (1, 'First', null);
INSERT INTO schema_140.SELF_REFERENCING_COL VALUES (2, 'Next', null);
INSERT INTO schema_140.SELF_REFERENCING_COL VALUES (3, 'Third', 1);
INSERT INTO schema_140.SELF_REFERENCING_COL VALUES (4, 'Last', 2);
```

Then synced to Metabase, then updated the data model such that `parent_id` was marked as a FK pointing to `id` in the same table, and was also renamed to `ID`:

<img width="1280" alt="Screen Shot 2021-02-04 at 11 59 03 AM" src="https://user-images.githubusercontent.com/3521562/106934966-69488580-66e0-11eb-9943-8dd2c21ab184.png">

Questions seemed to work fine, including filtering.

<img width="480" alt="Screen Shot 2021-02-04 at 12 02 15 PM" src="https://user-images.githubusercontent.com/3521562/106935368-e07e1980-66e0-11eb-84b0-8ddc2881f9e3.png">

<img width="405" alt="Screen Shot 2021-02-04 at 12 02 20 PM" src="https://user-images.githubusercontent.com/3521562/106935382-e4aa3700-66e0-11eb-9353-8f210b7f9253.png">

Is this different from what you were trying?  Thanks for any more info.

**Comment by flamber** [comment] 2021-11-09 13:29
Closing, since I cannot reproduce on 0.41.1 with Redshift/Oracle, when using a table with self-referencing FK with remapping:
![image](https://user-images.githubusercontent.com/1447303/140932585-ea4c334d-640d-4b19-a749-69360cada642.png)

**Closed by flamber** 2021-11-09 13:29 UTC
Labels: Type:Bug, Database/Redshift, Database/Oracle
