### ISSUE TITLE
metabase.driver.generic-sql.query-processor error

### ISSUE THREAD

**Issue by bishu05** [metabase/metabase#8934] opened 2018-11-13 09:18 UTC
- Your browser and the version: (Chrome 70.x, Firefox 63)
- Your operating system: (Ubuntu 19.04)
- Your databases: (MySQL)
- Metabase version: (0.31.0)
- Metabase hosting environment: (Centos 7.5)
- Metabase internal database: H2 (default), MySQL)

After upgrading from 0.30.4 to 0.31.0 queries are not running properly:

ov 13 14:38:11 ERROR metabase.driver.generic-sql.query-processor :: nil
Nov 13 14:38:11 WARN metabase.query-processor :: {:status :failed,
:class java.lang.Exception,
:error "Connections could not be acquired from the underlying database!",
:stacktrace
["driver.generic_sql.query_processor$do_with_try_catch.invokeStatic(query_processor.clj:522)"
"driver.generic_sql.query_processor$do_with_try_catch.invoke(query_processor.clj:514)"
"driver.generic_sql.query_processor$execute_query.invokeStatic(query_processor.clj:574)"
"driver.generic_sql.query_processor$execute_query.invoke(query_processor.clj:570)"
"driver$fn__28276$G__28083__28283.invoke(driver.clj:104)"
"query_processor$execute_query.invokeStatic(query_processor.clj:54)"
"query_processor$execute_query.invoke(query_processor.clj:48)"
"query_processor.middleware.mbql_to_native$mbql__GT_native$fn__33022.invoke(mbql_to_native.clj:30)"
"query_processor.middleware.annotate_and_sort$annotate_and_sort$fn__31336.invoke(annotate_and_sort.clj:42)"
"query_processor.middleware.limit$limit$fn__32977.invoke(limit.clj:15)"
"query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__32827.invoke(cumulative_aggregations.clj:58)"
"query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__32827.invoke(cumulative_aggregations.clj:58)"
"query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__36951.invoke(results_metadata.clj:51)"
"query_processor.middleware.format_rows$format_rows$fn__32967.invoke(format_rows.clj:26)"
"query_processor.middleware.binning$update_binning_strategy$fn__31430.invoke(binning.clj:165)"
"query_processor.middleware.resolve$resolve_middleware$fn__30924.invoke(resolve.clj:483)"
"query_processor.middleware.expand$expand_middleware$fn__32707.invoke(expand.clj:607)"
"query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__31010.invoke(add_row_count_and_status.clj:15)"
"query_processor.middleware.driver_specific$process_query_in_context$fn__32847.invoke(driver_specific.clj:12)"
"query_processor.middleware.resolve_driver$resolve_driver$fn__35494.invoke(resolve_driver.clj:15)"
"query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31344$fn__31345.invoke(bind_effective_timezone.clj:9)"
"util.date$call_with_effective_timezone.invokeStatic(date.clj:82)"
"util.date$call_with_effective_timezone.invoke(date.clj:71)"
"query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31344.invoke(bind_effective_timezone.clj:8)"
"query_processor.middleware.cache$run_query_and_save_results_if_successful_BANG_.invokeStatic(cache.clj:116)"
"query_processor.middleware.cache$run_query_and_save_results_if_successful_BANG_.invoke(cache.clj:114)"
"query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:127)"
"query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:124)"
"query_processor.middleware.cache$maybe_return_cached_results$fn__31519.invoke(cache.clj:150)"
"query_processor.middleware.catch_exceptions$catch_exceptions$fn__32758.invoke(catch_exceptions.clj:58)"
"query_processor$process_query.invokeStatic(query_processor.clj:135)"
"query_processor$process_query.invoke(query_processor.clj:131)"
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:249)"
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:243)"
"query_processor$fn__36989$process_query_and_save_execution_BANG___36994$fn__36995.invoke(query_processor.clj:289)"
"query_processor$fn__36989$process_query_and_save_execution_BANG___36994.invoke(query_processor.clj:275)"
"api.card$run_query_for_card.invokeStatic(card.clj:582)"
"api.card$run_query_for_card.doInvoke(card.clj:568)"
"api.card$fn__46200$fn__46203.invoke(card.clj:589)"
"api.card$fn__46200.invokeStatic(card.clj:588)"
"api.card$fn__46200.invoke(card.clj:584)"
"middleware$enforce_authentication$fn__55250.invoke(middleware.clj:116)"
"api.routes$fn__55390.invokeStatic(routes.clj:61)"
"api.routes$fn__55390.invoke(routes.clj:61)"
"routes$fn__55477$fn__55478.doInvoke(routes.clj:108)"
"routes$fn__55477.invokeStatic(routes.clj:103)"
"routes$fn__55477.invoke(routes.clj:103)"
"middleware$catch_api_exceptions$fn__55379.invoke(middleware.clj:424)"
"middleware$log_api_call$fn__55356$fn__55358.invoke(middleware.clj:351)"
"middleware$log_api_call$fn__55356.invoke(middleware.clj:350)"
"middleware$add_security_headers$fn__55304.invoke(middleware.clj:253)"
"core$wrap_streamed_json_response$fn__60666.invoke(core.clj:67)"
"middleware$bind_current_user$fn__55255.invoke(middleware.clj:140)"
"middleware$maybe_set_site_url$fn__55308.invoke(middleware.clj:277)"],

**Comment by camsaul** [comment] 2018-11-28 00:03
> Connections could not be acquired from the underlying database!

Sounds like it can't connect to your database

**Comment by salsakran** [comment] 2018-12-28 02:58
@bishu05 have you checked your database connectivity? it sounds like the issue is that Metabase can't access your database. Closing as it seems to be an issue with that, and not a bug in Metabase. If you follow our troubleshooting guide on this - https://metabase.com/docs/latest/troubleshooting-guide/datawarehouse.html and find that it is a bug, I'm happy to re-open this.

**Closed by salsakran** 2018-12-28 02:58 UTC

**Comment by bishu05** [comment] 2018-12-28 03:32
Please close the issue, issue was resolved!

Thanks & Regards,

Bishu


- Sent from mobile. Excuse for typo.
