### ISSUE TITLE
pressing return on a 'Contains' filter textarea swaps text with first list element  

### ISSUE THREAD

**Issue by kidd** [metabase/metabase#15443] opened 2021-04-01 18:32 UTC
**Describe the bug**

On a 'Contains' filter, type some text, and click some of the suggestions in the dropdown. The content gets selected but the focus still remains in the textfield. Pressing Return multiple times swaps the first element in the list and the current value in the textbox

**To Reproduce**
- Create a dashboard with a card of Products table
- Create a "contains" filter 
- type text to trim 
![sshot--2021-04-01--192545](https://user-images.githubusercontent.com/25607/113338002-7076c300-9320-11eb-957e-37b3468748c4.png)
- select with mouse
![sshot--2021-04-01--192803](https://user-images.githubusercontent.com/25607/113337997-6f459600-9320-11eb-906c-2987cfc8fbf5.png)
- press return continuously
![sshot--2021-04-01--192736](https://user-images.githubusercontent.com/25607/113337999-6fde2c80-9320-11eb-810d-65aa9f865530.png)
Specs:
- Firefox & Linux
- metabase-head

**Comment by ariya** [comment] 2021-04-01 18:35
I can reproduce the issue!

**Comment by flamber** [comment] 2021-05-25 14:12
Closing, since this has now been changed to not show the auto-complete list for non-exact operators #15477

**Closed by flamber** 2021-05-25 14:12 UTC
Labels: Priority:P2, Querying/Parameters & Variables, Type:UX
