### ISSUE TITLE
Developers Guide Link is Broken

### ISSUE THREAD

**Issue by loganfrederick** [metabase/metabase#2775] opened 2016-06-15 23:08 UTC
This page on the site is broken: http://www.metabase.com/docs/v0.17.1/v0.17.1/developers-guide

Prominently linked to from: http://www.metabase.com/docs/v0.17.1/

Thanks!

**Comment by salsakran** [comment] 2016-06-15 23:11
Good eyes!

It's a dupe of #2637 . Should be fixed in our next milestone.

**Closed by salsakran** 2016-06-15 23:11 UTC
