### ISSUE TITLE
LDAP Group Membership  from v0.32.10 on back 

### ISSUE THREAD

**Issue by DoctorOgg** [metabase/metabase#10788] opened 2019-09-03 14:10 UTC
**Describe the bug**
Members randomly get removed from groups in Metabase, when their LDAP group membership remains constant, seems to happen when a user tries to login. 

**To Reproduce**
with a ldap configured Metabase, try to log in, perhaps with the wrong password, and members will be removed from a Metabase group. 

**Expected behavior**
members should remain members of a Metabase group as long as they are STILL members in the ldap group. 

**Information about your Metabase Installation:**
any browser, we have tried chrome, firefox, and safari

**Severity**
BLOCKING< SEVERE

**Comment by DoctorOgg** [comment] 2019-09-13 19:44
Any update, im having to manually repopulate our Metabase groups on multiple times a day bases now..

**Comment by DoctorOgg** [comment] 2019-09-16 23:22
yay, another day,  more manual fixes to work around this bug, any idea if or when this will be addressed?

**Comment by mazameli** [comment] 2019-09-16 23:56
Hey, @DoctorOgg. Are you saying this is occurring in version 0.32.10, or is this also happening to you in version 0.33?

**Comment by DoctorOgg** [comment] 2019-09-17 00:07
i can upgrade to 0.33 to test, will get back to you on that

**Comment by mazameli** [comment] 2019-09-17 21:52
Thanks, yeah, that'll help us track this down. Please make sure to backup your Metabase app DB before upgrading!

**Comment by flamber** [comment] 2019-09-25 18:59
Hi @DoctorOgg Did you find time to test with 0.33.3? Also, this looks like a duplicate of #7571, which you have commented on, would that be correct to assume that?

**Comment by DoctorOgg** [comment] 2019-09-25 19:01
sorry, the upgrade did not take, and i was forced to revert, so im trying to find a path forward, and yes this is a dup. sorry for the delay

**Comment by mazameli** [comment] 2019-09-25 19:16
Sorry to hear the upgrade didn't help. Marking this as a dupe and closing it, but we're taking a look at #7571.

**Comment by DoctorOgg** [comment] 2019-10-24 16:18
was finally able to upgrade to 0.33.4 and we are still experiencing the same issue.

**Comment by chandlertee** [comment] 2019-10-24 19:18
Hi @mazameli I work with @DoctorOgg - it is not a dupe of #7571 because we only use LDAP for authentication, i.e., there are no users that exist in Metabase that don't exist in our LDAP groups. However, users are still randomly removed from the Metabase Group that corresponds to their LDAP group 4-5 times a week. 

All users/groups are added to LDAP and we have the group mappings configured. The users are able to log in initially, and inspection of users in Metabase shows they have been correctly added to the proper group; then they'll try to log in a different day and they'll no longer have access to that group.

**Comment by DoctorOgg** [comment] 2019-10-24 19:38
I would add that we have 2 different Metabase installs, and both of them use the same ldap server, the other instance is on 0.32.10 and has zero issues with ldap groups.

**Comment by mazameli** [comment] 2019-10-24 19:40
@chandlertee @DoctorOgg Thanks for the additional context. I'll reopen this unless/until someone above my pay grade can confirm for certain if this is in fact the same underlying root cause as #7571 or not.

**Comment by DoctorOgg** [comment] 2019-10-25 16:42
We have disabled LDAP group sync, for the time being, I am curious to see if the behavior will continue.

**Comment by walterl** [comment] 2020-01-17 23:53
Hi @DoctorOgg, @chandlertee! I haven't (yet) managed to reproduce this issue on my side. Do you perhaps have any more information on how I can I trigger this behavior?

Could you maybe also have a look at your LDAP server logs around the time that this happens? Maybe the LDAP query to lookup the user succeeds, but then the one to query group info fails, and that causes Metabase to believe that the user isn't assigned to any groups?

That made me think of another question: when a user "loses" group memberships as you described, do they always lose _all_ group memberships, or only memberships to some/specific groups?

**Comment by DoctorOgg** [comment] 2020-01-17 23:56
we have frankly given up on solving this and have disabled many of the LDAP features as it was too disruptive to have to fix this...almost everyone, our LDAP servers are standard OpenLDAP with nothing remarkable in the logs... its as vanilla LDAP as you can get... without any Microsoft nastiness. as far as group memberships go, we off the groups at the time were LDAP groups, so AFAIK we lost all memberships.

**Comment by DoctorOgg** [comment] 2020-01-18 00:01
i will add we don't have a large userbase (less than 200 objects) , and our LDAP servers are rather idle most of the time.... so its not an issue of load or their inability to respond to a query...

**Comment by walterl** [comment] 2020-01-18 00:03
@DoctorOgg Thanks for the quick response! I'll have a look through the relevant code to see if I can spot anything that could've caused this.

**Comment by walterl** [comment] 2020-01-22 16:16
I was unable to find any code changes that seems like it would've caused this. I've added some more detailed logging for this in #11761, so that if/when this happens again, we'll have more data to work with.

Closing this for now.

**Closed** 2023-09-29 13:40 UTC
Labels: Type:Bug, Priority:P1, .Unable to Reproduce, Administration/Auth
