### ISSUE TITLE
Allow user-defined URL titles

### ISSUE THREAD

**Issue by ctmay4** [metabase/metabase#12288] opened 2020-04-07 19:24 UTC
**Is your feature request related to a problem? Please describe.**
URL fields are rendered as links in the results which is really nice.  However some URLs are very long and it would be really helpful to be able to have a link title like when you use an <a> tag.   Instead of seeing:

https://server.com/long/url/path/here/12272

I'd like the option of seeing the link like this:

[12272](https://server.com/long/url/path/here/12272)

**Describe the solution you'd like**
I'm not sure best way to accomplish this, but one idea I had was to be able to create a custom field using a new field formula (maybe called "url").  It would return a URL field type and maybe look like:

```
url(title, url)
```

So I could create the example above with:

```
url("12272", "https://server.com/long/url/path/here/12272")
```

**Describe alternatives you've considered**
I haven't found any alternative way of displaying links this way in Metabase.  

**How important is this feature to you?**
In the current state, I just don't use URLs in my results because they are too long to fit in with everything else.  Having short links would allow them to be placed in many more places.

**Comment by flamber** [comment] 2020-04-07 19:42
Duplicate of #7188 - upvote by clicking :+1: on the first post.
You can define a custom name for the entire column like "View details" via visualization Settings > Columns > (link column) :gear: > Link text

**Closed by flamber** 2020-04-07 19:42 UTC
Labels: .Needs Triage, Type:New Feature
