### ISSUE TITLE
Unable to create Region map when all regions have identical metric values

### ISSUE THREAD

**Issue by nroi** [metabase/metabase#8805] opened 2018-10-29 14:30 UTC
- Browser version: Firefox version 62.0.3
- OS: Reproducible on both Windows 10 and Linux
- Database: PostgreSQL 10.4
- Metabase version: 0.30.4 
- Metabase hosting environment: Docker on Ubuntu 18.04.1
- Metabase internal database: PostgreSQL 10.4

It seems that Metabase is unable to produce region maps when all regions have the same metric values, with more than one region. For instance, with the following queries, I _am_ able to produce a region map:
```SQL
select 'DE40A' as nuts3, 1 as count_
```

```SQL
select 'DE40A' as nuts3, 1 as count_
union
select 'DEA23' as nuts3, 2 as count_
```

```SQL
select 'DE40A' as nuts3, 1 as count_
union
select 'DEA23' as nuts3, 2 as count_
union
select 'DEA11' as nuts3, 2 as count_
```

With the following queries, I am _not_ able to produce a region map:

```SQL
select 'DE40A' as nuts3, 1 as count_
union
select 'DE23A' as nuts3, 1 as count_
```

```SQL
select 'DE40A' as nuts3, 2 as count_
union
select 'DE23A' as nuts3, 2 as count_
```

```SQL
select 'DE40A' as nuts3, 1 as count_
union
select 'DE23A' as nuts3, 1 as count_
union
select 'DE23A' as nuts3, 1 as count_
```

Detailed steps to reproduce:

1. Add a GeoJSON map with german NUTS3 regions. For instance: choose [this url](https://gist.githubusercontent.com/nroi/c46b89be647fb896a5302db133f25834/raw/5472db831f2067bb2ec1d95f2832b82e6f34f5fd/germany-de-nuts-3-regions.geojson) with `FID` as region identifier and `NUTS_NAME` as the region's name.
2. Create a new question from a "Native Query", choose a PostgreSQL database as data source.
3. Enter the following SQL statement:
```SQL
select 'DE40A' as nuts3, 1 as count_
union
select 'DEA23' as nuts3, 1 as count_
```
4. Click "Get answer" to obtain a table with two rows.
5. Change the Visualization type from table to map.
6. Edit the map settings and choose the region map (the GeoJSON file linked above). Choose `count_` as metric field and `nuts3` as Region field. Click "done".

Expected result: A region map with two regions highlighted.
Actual result: It just keeps loading and nothing happens.

**Comment by flamber** [comment] 2020-05-24 13:42
I think this was fixed in 0.32.9, but without the javascript error from step 6, then I'm unsure.
I cannot reproduce on 0.35.3
![image](https://user-images.githubusercontent.com/1447303/82755625-138faf80-9dd5-11ea-98fb-a9dfd2a49c20.png)

**Closed by flamber** 2020-05-24 13:42 UTC
Labels: Priority:P2, Type:Bug, Visualization/, Visualization/Chart Settings
