### ISSUE TITLE
Postgres wrong handle of BIGINT type

### ISSUE THREAD

**Issue by duc-ctm-jacobins-digital** [metabase/metabase#28255] opened 2023-02-13 09:06 UTC
**Describe the bug**
My database use BIGINT as primary key/foreign key. Metabase does not recognize BIGINT type. Metabase will truncate some last digit to 0 (see pic below).
![image](https://user-images.githubusercontent.com/70874681/218410903-687a45bf-81cb-4d29-a39b-ba709df556f6.png)

When I filter by UI, it will show no result.
![metaabse bug](https://user-images.githubusercontent.com/70874681/218415838-6c49baf9-65b6-42df-999a-cc3f0cdd71f3.gif)

However, if the column is primary key, it recognizes correctly
![image](https://user-images.githubusercontent.com/70874681/218413156-c63b8c64-e93c-4ef9-96ce-ace263d953cd.png)

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**Expected behavior**
It should show correct BIGINT value and filter must work.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "5.15.0-1008-gcp",
    "user.language": "en",
    "user.timezone": "Asia/Ho_Chi_Minh"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.5 (Ubuntu 14.5-0ubuntu0.22.04.1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.4.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-09-02",
      "tag": "v1.44.3",
      "branch": "release-x.44.x",
      "hash": "7d50282"
    },
    "settings": {
      "report-timezone": "Asia/Ho_Chi_Minh"
    }
  }
}
```

**Severity**
Annoying, can not use UI for filtering BIGINT column

**Comment by paoliniluis** [comment] 2023-02-13 16:24
Hi @duc-ctm-jacobins-digital, this is a duplicate of https://github.com/metabase/metabase/issues/5816. I'll proceed to close the issue but thanks for reporting!

**Closed by paoliniluis** 2023-02-13 16:24 UTC
Labels: Type:Bug, .Needs Triage
