### ISSUE TITLE
point map not showing in static embedding on METABASE CLOUD

### ISSUE THREAD

**Issue by mfhanif** [metabase/metabase#40714] opened 2024-03-28 08:55 UTC
**Describe the bug**
point map not showing in static embedding on metabase cloud

**Logs**
```
[c6798e9b-c5aa-4573-bbc8-52175b19bd82] 2024-03-28T15:47:13+07:00 DEBUG metabase.server.middleware.log GET /api/tiles/8/205/132/45706/45719 401 119.0 µs (0 DB calls) 
"Unauthenticated"

[987394a2-6c42-4a80-b727-7cfb22c93180] 2024-03-28T15:47:13+07:00 DEBUG metabase.server.middleware.log GET /api/tiles/8/206/132/45706/45719 401 95.5 µs (0 DB calls) 
"Unauthenticated"

[c6798e9b-c5aa-4573-bbc8-52175b19bd82] 2024-03-28T15:47:13+07:00 DEBUG metabase.server.middleware.log GET /api/tiles/8/205/133/45706/45719 401 70.5 µs (0 DB calls) 
"Unauthenticated"

[987394a2-6c42-4a80-b727-7cfb22c93180] 2024-03-28T15:47:13+07:00 DEBUG metabase.server.middleware.log GET /api/tiles/8/206/133/45706/45719 401 80.6 µs (0 DB calls) 
"Unauthenticated"

[c6798e9b-c5aa-4573-bbc8-52175b19bd82] 2024-03-28T15:47:13+07:00 DEBUG metabase.server.middleware.log GET /api/tiles/8/204/132/45706/45719 401 75.2 µs (0 DB calls) 
"Unauthenticated"

[987394a2-6c42-4a80-b727-7cfb22c93180] 2024-03-28T15:47:13+07:00 DEBUG metabase.server.middleware.log GET /api/tiles/8/207/132/45706/45719 401 45.9 µs (0 DB calls) 
"Unauthenticated"

[c6798e9b-c5aa-4573-bbc8-52175b19bd82] 2024-03-28T15:47:13+07:00 DEBUG metabase.server.middleware.log GET /api/tiles/8/204/133/45706/45719 401 61.6 µs (0 DB calls) 
"Unauthenticated"

[987394a2-6c42-4a80-b727-7cfb22c93180] 2024-03-28T15:47:13+07:00 DEBUG metabase.server.middleware.log GET /api/tiles/8/207/133/45706/45719 401 39.6 µs (0 DB calls) 
"Unauthenticated"

[c6798e9b-c5aa-4573-bbc8-52175b19bd82] 2024-03-28T15:47:13+07:00 DEBUG metabase.server.middleware.log GET /api/tiles/8/203/132/45706/45719 401 115.2 µs (0 DB calls) 
"Unauthenticated"

[987394a2-6c42-4a80-b727-7cfb22c93180] 2024-03-28T15:47:13+07:00 DEBUG metabase.server.middleware.log GET /api/tiles/8/208/132/45706/45719 401 43.4 µs (0 DB calls) 
"Unauthenticated"

[c6798e9b-c5aa-4573-bbc8-52175b19bd82] 2024-03-28T15:47:13+07:00 DEBUG metabase.server.middleware.log GET /api/tiles/8/203/133/45706/45719 401 64.0 µs (0 DB calls) 
"Unauthenticated"

[987394a2-6c42-4a80-b727-7cfb22c93180] 2024-03-28T15:47:13+07:00 DEBUG metabase.server.middleware.log GET /api/tiles/8/208/133/45706/45719 401 57.4 µs (0 DB calls) 
"Unauthenticated"
```

**To Reproduce**
1. make dashboard with point map
2. publish static embedding
3. open dashboard with published link
4. map not showing

**Expected behavior**
<img width="1472" alt="Screenshot 2024-03-28 at 15 51 33" src="https://github.com/metabase/metabase/assets/10842521/5b3d5db3-ea62-406c-9803-760d34e13455">

**Screenshots**
https://klikpeta.metabaseapp.com/public/dashboard/b8126c9b-7522-484d-962d-03f889b78a97
<img width="1494" alt="Screenshot 2024-03-28 at 15 53 41" src="https://github.com/metabase/metabase/assets/10842521/65bc2ad7-84ef-4336-bc22-cc71a927b860">

**Severity**
super annoying

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.10.209-198.812.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-02-22",
      "tag": "v1.48.7",
      "hash": "c192db1"
    },
    "settings": {
      "report-timezone": "Asia/Jakarta"
    }
  }
}
```

**Comment by paoliniluis** [comment] 2024-03-28 11:44
This is a duplicate of https://github.com/metabase/metabase/issues/9420, please contact support so we can tag this to your account and prioritize

**Closed by paoliniluis** 2024-03-28 11:44 UTC

**Comment by mfhanif** [comment] 2024-03-28 14:31
I dis contact [help@metabase.com](mailto:help@metabase.com) but no luck. Is there any other contact?
