### ISSUE TITLE
Issue with Java Heap Space Error and GPU Usage Spike after Metabase V0.48 Update

### ISSUE THREAD

**Issue by maximepvrt** [metabase/metabase#37446] opened 2024-01-09 14:14 UTC
### Describe the bug

Since updating to Metabase version V0.48, I have been encountering a critical issue where the interface fails to load, displaying the following error message:

```json
{"via":[{"type":"java.lang.OutOfMemoryError","message":"Java heap space"}],"trace":[],"cause":"Java heap space","message":"Java heap space"}
```

## Observations

Upon further analysis of my machine's GPU and RAM usage, I noticed a significant change in GPU behavior after the update. While RAM usage remains relatively stable, the GPU utilization experiences a substantial spike. This spike ultimately leads to the unavailability of the Metabase instance, requiring a manual application restart to regain access.

## Additional Information

I will be attaching graphical representations of RAM and GPU usage for both Metabase V0.47 and V0.48 to provide visual context and aid in the investigation.

### CPU V0.47
![Capture d’écran 2024-01-09 à 13 47 10](https://github.com/metabase/metabase/assets/1840026/c41af759-0931-45f5-8092-9b8d6bd687c2)

### CPU V0.48
![Capture d’écran 2024-01-09 à 13 46 09](https://github.com/metabase/metabase/assets/1840026/22e9ab3d-238f-4706-af30-39588043f864)

### RAM V0.47
![Capture d’écran 2024-01-09 à 13 47 19](https://github.com/metabase/metabase/assets/1840026/fcf2e43d-4865-4ebf-9bd2-f165e25ab27c)

### RAM V0.48
![Capture d’écran 2024-01-09 à 13 45 51](https://github.com/metabase/metabase/assets/1840026/a5b9984c-06e9-4b81-a1e5-4c5fc7e725f7)

### To Reproduce

1. Update Metabase from V0.47 to V0.48.
2. Attempt to load the Metabase interface.
3. Experience the Java Heap Space error after a certain duration.
4. Observe the increased GPU usage.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "6.4.13-dirty",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-12-19",
      "tag": "v0.48.1",
      "hash": "a8302d4"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

blocking my usage of Metabase entirely

**Comment by paoliniluis** [comment] 2024-01-26 10:42
This is a duplicate of https://github.com/metabase/metabase/issues/38072 now

**Closed by paoliniluis** 2024-01-26 10:42 UTC
Labels: Type:Bug, .Needs Triage
