### ISSUE TITLE
CSS hides top three rows of some dashboards in Chrome only

### ISSUE THREAD

**Issue by snarfed** [metabase/metabase#1902] opened 2016-02-08 20:08 UTC
hi all! we're seeing an odd problem on some but not all of our dashboards, in Chrome only. (cross browser compatibility, whee!) screenshots and app versions below. not sure what additional data would be useful, but i'm happy to send the (sanitized) raw HTML and CSS or anything else if you want. thanks in advance!

cc @wendymc

* Metabase v0.13.3
* OS X El Capitan 10.11.3 (15D21)
* Chrome: 48.0.2564.103 (64-bit)
* Firefox: 43.0.4
* Safari: 9.0.3 (11601.4.4)

<img width="1280" alt="screen shot 2016-02-08 at 11 53 05 am" src="https://cloud.githubusercontent.com/assets/778068/12897512/a5e8cf30-ce5c-11e5-81a7-a345ff469533.png">
<img width="1280" alt="screen shot 2016-02-08 at 11 53 07 am" src="https://cloud.githubusercontent.com/assets/778068/12897513/a60ec532-ce5c-11e5-95fe-589d85f7f8bc.png">
<img width="1280" alt="screen shot 2016-02-08 at 11 54 37 am" src="https://cloud.githubusercontent.com/assets/778068/12897514/a6196046-ce5c-11e5-9ce2-8c0c5c7195e4.png">

**Comment by salsakran** [comment] 2016-02-08 20:13
That's due to a chrome bug. We added a workaround in version 0.14.1

**Comment by tlrobinson** [comment] 2016-02-08 20:13
Duplicate of #1843

**Closed by tlrobinson** 2016-02-08 20:13 UTC
Labels: New

**Comment by snarfed** [comment] 2016-02-08 20:43
damn, sorry for the dupe. i searched but evidently not for the right keywords. thanks for the fix!
