### ISSUE TITLE
ERROR: column source.avg does not exist after update to v0.36.8.2

### ISSUE THREAD

**Issue by matheusmvinhas** [metabase/metabase#13696] opened 2020-11-05 18:56 UTC
**Describe the bug**
After Update, I have a custom question that stop work. On a PostgreSQL 

**Logs**
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_272-8u272-b10-0+deb9u1-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_272",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.272-b10",
    "os.name": "Linux",
    "os.version": "4.9.0-6-amd64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres",
      "mysql",
      "clickhouse",
      "bigquery",
      "athena",
      "cubejs",
      "sqlserver",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.18"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.36.8.2",
      "date": "2020-10-26",
      "branch": "release-0.36.x",
      "hash": "8eb8b49"
    },
    "settings": {
      "report-timezone": "America/Sao_Paulo"
    }
  }
}
![image](https://user-images.githubusercontent.com/68671393/98283671-bea8b580-1f7e-11eb-91ee-790345909597.png)
``` sql 
SELECT "source"."semana" AS "semana",
       "source"."sum" AS "sum",
       "source"."sum_2" AS "sum_2",
       "source"."Ociosidade Prevista" AS "Ociosidade Prevista"
FROM (SELECT (1.000000001*(1 -(CAST("source"."sum_2" AS FLOAT) / CASE WHEN "source"."sum" = 0 THEN NULL ELSE "source"."sum" END))) AS "Ociosidade Prevista",
             "source"."sum_2" AS "sum_2",
             "source"."sum" AS "sum",
             "source"."semana" AS "semana",
             "source"."sum" AS "sum_2_2",
             "source"."sum_2" AS "sum_2_3",
             "source"."avg" AS "avg",
             "source"."data_coleta" AS "data_coleta",
             "source"."tipo" AS "tipo",
             "source"."carga_horaria" AS "carga_horaria",
             "source"."tempo_total" AS "tempo_total",
             "source"."semana" AS "semana_2",
             "source"."pesquisador" AS "pesquisador"
      FROM (SELECT "source"."semana" AS "semana",
                   SUM("source"."avg") AS "sum",
                   SUM("source"."sum") AS "sum_2"
            FROM (SELECT "dimensionamento"."previsao_campo"."semana" AS "semana",
                         "dimensionamento"."previsao_campo"."pesquisador" AS "pesquisador",
                         AVG("dimensionamento"."previsao_campo"."carga_horaria") AS "avg",
                         SUM("dimensionamento"."previsao_campo"."tempo_total") AS "sum"
                  FROM "dimensionamento"."previsao_campo"
                  WHERE (date_trunc('year',CAST("dimensionamento"."previsao_campo"."data_coleta" AS TIMESTAMP)) = date_trunc('year',CAST(NOW() AS TIMESTAMP)) AND "dimensionamento"."previsao_campo"."tipo" = 'PREVISTO')
                  GROUP BY "dimensionamento"."previsao_campo"."semana",
                           "dimensionamento"."previsao_campo"."pesquisador"
                  ORDER BY "dimensionamento"."previsao_campo"."semana" ASC,
                           "dimensionamento"."previsao_campo"."pesquisador" ASC) "source"
            GROUP BY "source"."semana"
            ORDER BY "source"."semana" ASC) "source") "source"
LIMIT 1048576
```

**Comment by flamber** [comment] 2020-11-05 19:34
Duplicate of #12762

**Closed by flamber** 2020-11-05 19:34 UTC
Labels: .Needs Triage, Type:Bug
