### ISSUE TITLE
The result's format of the question sent to email via dashboard subscription has changed.

### ISSUE THREAD

**Issue by jrca025** [metabase/metabase#22403] opened 2022-05-04 03:17 UTC
Here is my question visually:
![image](https://user-images.githubusercontent.com/89201548/166618647-2be4a456-2892-4b92-bd19-7c9ce8c7d3d0.png)

While this is the one being sent to email:
![image](https://user-images.githubusercontent.com/89201548/166618661-0999c226-6ce1-4c2d-9fce-1ca7d6f8df70.png)

Column positioning is different, user_id format is different.

and while I disable the "attach result" option, it still is sending with attachments. and here is the attached result visually.
![image](https://user-images.githubusercontent.com/89201548/166618734-50add1f7-09b4-49b1-bdd6-7ef9601b4f5c.png)

overall not what I expected as a frequent user of pulse from previous versions

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10-Ubuntu-0ubuntu0.18.04.1",
    "java.vendor": "Private Build",
    "java.vendor.url": "Unknown",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10-Ubuntu-0ubuntu0.18.04.1",
    "os.name": "Linux",
    "os.version": "5.4.0-1077-azure",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "mongo",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-04-07",
      "tag": "v0.42.4",
      "branch": "release-x.42.x",
      "hash": "7c3ce2d"
    },
    "settings": {
      "report-timezone": "Asia/Hong_Kong"
    }
  }
}

**Comment by flamber** [comment] 2022-05-04 07:33
Duplicate of #17753

**Closed by flamber** 2022-05-04 07:33 UTC
Labels: Type:Bug, .Needs Triage
