### ISSUE TITLE
`Could not find table` when running query across three tables

### ISSUE THREAD

**Issue by rossbeale** [metabase/metabase#5654] opened 2017-08-01 19:29 UTC
I've attempted to look for a dupe issue but haven't found one related.  This may be a limitation, rather than a bug (but UX behaviour suggests it should be possible).

I have three entities tied together, such that:

Game belongs to Client
Client belongs to Licensee

When I set up a query utilising the form builder, it permits me to group by game -> client -> licensee field (as pictured), yet we get an error on running the query.  Game -> Client -> Licensee have all been configured as Foreign Key types with the right table.  Any ideas if this is a limitation or bug?  Thanks for any help.

![screen shot 2017-08-01 at 20 22 41](https://user-images.githubusercontent.com/888271/28843108-efcbbb9a-76f7-11e7-983c-43db93f2a757.jpg)

![screen shot 2017-08-01 at 20 22 48](https://user-images.githubusercontent.com/888271/28843159-19b866ba-76f8-11e7-9c2f-b5df49138bcd.jpg)

- Your browser and the version: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
- Your operating system: Mac Sierra 
- Your databases: Postgres
- Metabase version: v0.25.1
- Metabase hosting environment: Heroku
- Metabase internal database: Postgres

**Comment by rossbeale** [comment] 2017-08-04 06:15
As an advisory FYI rather than being rude... 

In the time it's taken to even respond to/acknowledge this issue, I've moved to a paid competitor.  You guys need to be more proactive if you want to convert users into those with paid support plans.  Your product is amazing, but this (and a couple other tickets with no response) is a major blocker.

**Comment by salsakran** [comment] 2017-08-07 22:04
Hello Ross -

If you still have this instance up, can you "convert to sql" and let us know what SQL gets generated? I tried to reproduce this using our sample dataset, but a 3-table query with a filter on an FK and a breakout on a different FK worked just fine.

![screen shot 2017-08-07 at 2 58 36 pm](https://user-images.githubusercontent.com/107439/29047546-f5aca852-7b80-11e7-8afc-22897aea8ff0.png)

Also, while we would of course prefer you use us, there are certain realities to the fact that Metabase is a *free* open source project that gets a very significant volume of inbound to a small team. One of them is we certainly can't guarantee a 2 day turnaround on a non-reproducible bug report for a free product. We're doing what we can, but we have a very limited amount of bandwidth.

**Comment by hagen** [comment] 2017-10-04 01:31
Perhaps I can help. I'm getting the same issue.
I have these three entities:
- invoice items (line items)
- invoices
- patients
Patient has many Invoices (invoice.patient_id), Invoice has many Invoice Items (invoice_item.invoice_id).
I'm trying to build a Question based on Invoice Items, then enrich the output with the patient's Name. In the data model, the FKs are set up correctly to allow this.
I select Invoice Items as my lead table, add a grouping of Invoice > Patient > First Name:
![image](https://user-images.githubusercontent.com/5161952/31155748-2770debe-a8fc-11e7-9311-11d6faa85a03.png)

And when I hit Get Answer, I get that same error - Query expansion failed.
![image](https://user-images.githubusercontent.com/5161952/31155759-40870db0-a8fc-11e7-8623-f5d32f8a77d9.png)

Because the Query expansion fails, there's no generated SQL. If I dial it back and skip the second relationship to get the Patient's First Name, and only ask for the Patient ID from the Invoce table, it'll work and the SQL is this:

SELECT `invoices__via__invoice_id`.`patient_id` AS `patient_id`
FROM `invoice_items`
LEFT JOIN `invoices` `invoices__via__invoice_id` ON `invoice_items`.`invoice_id` = `invoices__via__invoice_id`.`id`
GROUP BY `invoices__via__invoice_id`.`patient_id`
ORDER BY `invoices__via__invoice_id`.`patient_id` ASC
LIMIT 2000

**Comment by hagen** [comment] 2017-10-26 21:42
Related to #5482 (Nested-nested queries not working)
and #1173 (joins across multiple tables)
It's unclear whether this functionality is now in metabase or not, and whether this is a bug or feature request.

**Comment by camsaul** [comment] 2017-12-07 03:11
Yeah, this sounds like a duplicate of #1173. Closing as such

**Closed by camsaul** 2017-12-07 03:11 UTC
Labels: Query Builder, Unable to Reproduce
