### ISSUE TITLE
Allow more than one metric in a table view

### ISSUE THREAD

**Issue by jaimebarroso** [metabase/metabase#3804] opened 2016-11-23 15:47 UTC
Hi,

I didn't find the way to create a table with more than one metric in Metabase, grouped by my Client dimension, as it is possible in a line chart for instance.

![image](https://cloud.githubusercontent.com/assets/23703473/20568227/b498b228-b193-11e6-84f3-bccd0e322144.png)

I could get it with an SQL query to my table, but then I would lose my capacity to filter by data range in the dashboard.

Is it possible?

Thanks in advance!

**Comment by mfpinhal** [comment] 2016-11-24 15:52
Related to #3220.

**Comment by salsakran** [comment] 2016-12-05 05:31
closing this as a dupe of #3364

**Closed by salsakran** 2016-12-05 05:31 UTC
Labels: Proposal
