### ISSUE TITLE
Chart Customization Gone

### ISSUE THREAD

**Issue by MarcGJA** [metabase/metabase#7781] opened 2018-06-01 18:22 UTC
Browser: Firefox 52.8.0
OS: Microsoft Windows [Version 6.0.6002]
Databases: H2 internal default, Server SQL external (joined in)
Metabase: 0.29.2
Host: Localhost:3000

What happened to all the beautiful options that used to exist across the top of the chart customization window?  They're gone!  This isn't normal, there's something going on here...
![image](https://user-images.githubusercontent.com/38047661/40856734-bc8bac42-658d-11e8-9edb-60189666556a.png)

**Comment by mazameli** [comment] 2018-06-01 19:03
I can't reproduce this with macOS High Sierra on Chrome (v66) or Firefox (v60) using version 0.29.3 or on master. Could someone else in @metabase/core-developers check this on Windows?

**Comment by ivashin** [comment] 2018-06-02 13:54
@mazameli I can reproduce it too (Firefox 60 on Ubuntu 16.04). It happens on smaller screens, e.g. laptop running at 1920x1080 with 125% scaling. In line chart settings when the number of settings on the left gets high (e.g. Axes tab), the dialog resizes and top buttons get clipped. Scrollbar appears sometimes but can't scroll all the way up to the buttons.
This does not happen on external monitor running at 256x1440 with 125% scaling.

**Comment by MarcGJA** [comment] 2018-06-02 17:08
THANK YOU @ivashin! Scaling is indeed the issue!  Something must have changed in recent updates because this has never been the case before.  Working on a 24 inch desktop screen (corner to corner) and with Firefox at 100% scaling the customization menus are gone, but at 90% they're back!  Very odd behaviour indeed, whether this is a bug-status issue or not is up to the Metabase moderators.

**Comment by mazameli** [comment] 2018-06-04 16:38
Got it. Was able to repro on macOS + Chrome by making the window height really small:

![tabs](https://user-images.githubusercontent.com/2223916/40929840-ce8e720e-67da-11e8-8403-601bb88992b8.gif)

**Comment by EvaSchreyer** [comment] 2018-07-13 09:54
Hi, this is still the case in v 0.28 and 0.29.3. Funny thing is that it does not happen with a bar chart. just with line charts ... I use firefox 60.0.2 on a mac OS Sierra. Seems to be a bug?

**Comment by jornh** [comment] 2018-08-05 23:51
With the new nicer layout (👍 Maz!) in 0.30 this buglet seems to have gone to the eternal bit-fields - also for line charts. At least I couldn't reproduce it on my Firefox.

**Comment by mazameli** [comment] 2018-08-06 17:46
Yep, closing as fixed in master. 👍

**Closed by mazameli** 2018-08-06 17:46 UTC
Labels: Bug, CSS, Visualization/Chart Settings
