### ISSUE TITLE
Show databases in admin/setup that are disabled due to missing JDBC driver (Oracle, Vertica)

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#4523] opened 2017-03-15 17:34 UTC
We advertise support for Oracle and Vertica, but can't distribute the JDBC drivers, so they are disabled by default and do not appear in the list of databases in the database create/edit panel, which is confusing.

We should somehow indicate in the UI that these databases are supported, and link to instructions on installing the JDBC drivers.

http://www.metabase.com/docs/latest/administration-guide/databases/vertica.html
http://www.metabase.com/docs/latest/administration-guide/databases/oracle.html

**Comment by mazameli** [comment] 2019-10-12 00:00
Duplicate of https://github.com/metabase/metabase/issues/3935

**Closed by mazameli** 2019-10-12 00:00 UTC
Labels: .Design Needed, .Duplicate, .Proposal, Admin Panel & Setup, Type:UX
