### ISSUE TITLE
Changing Date Granularity on the go

### ISSUE THREAD

**Issue by mehdimeskin** [metabase/metabase#43989] opened 2024-06-11 08:11 UTC
**Problem:**
As a visitor of a dashboard, you may want to change date granularity of a graph to get better insight while analyzing. right now, this is not possible, and the way we have solved it in our company is adding all daily, weekly and monthly versions of each graph in one dashboard. But in this way, the dashboard becomes veryyyy long and hard to read for audience.

**Suggestion**
I think if we can define some parameteres like current filters, to define how each query is written related to the date fields, we can show date granualrity for each graph or for a whole dashbaord.

![date granularity](https://github.com/metabase/metabase/assets/9046779/33e326f4-3072-4695-bdbb-007ea30debcc)

This change makes it much easier for audience to get insight from each dashboard. and already almost all other platforms like power BI have this.

**Comment by paoliniluis** [comment] 2024-06-11 10:44
This is coming soon, it’s a duplicate of another feature request

**Closed by paoliniluis** 2024-06-11 10:44 UTC
Labels: Reporting/Dashboards, Type:New Feature, .Needs Triage
