### ISSUE TITLE
Multibyte characters are not displayed correctly in email subscriptions

### ISSUE THREAD

**Issue by tomoo-morikawa** [metabase/metabase#32580] opened 2023-07-24 00:52 UTC
### Describe the bug

Multibyte characters are not displayed correctly in email subscriptions.  
like the following image.

<img width="544" alt="image" src="https://github.com/metabase/metabase/assets/102127280/e02f6863-b537-4ed5-84e0-c11ccb8e478c">

### To Reproduce

Use email subscriptions on any dashboard

### Expected behavior

displayed correctly

### Information about your Metabase installation

```JSON
- metabase v0.46.6
- my os: ubuntu 20.2LTS
- my database : Postgres
- metabase hosting env: docker on aws-ec2
- metabase internal db: Postgres
- language: JP
```

### Severity

low

**Comment by paoliniluis** [comment] 2023-07-24 02:06
how should they appear?

**Comment by tomoo-morikawa** [comment] 2023-07-24 02:44
Sorry for the lack of explanation.  
I think they should appear the following.

<img width="428" alt="image" src="https://github.com/metabase/metabase/assets/102127280/f5063b97-ac79-435a-a129-2115186caeca">

**Comment by paoliniluis** [comment] 2023-07-24 11:59
Duplicate of https://github.com/metabase/metabase/issues/2342

**Closed by paoliniluis** 2023-07-24 11:59 UTC
Labels: Type:Bug, .Needs Triage
