### ISSUE TITLE
Rename Summarize Columns in Charts

### ISSUE THREAD

**Issue by nachosan2** [metabase/metabase#44018] opened 2024-06-11 17:32 UTC
**Is your feature request related to a problem? Please describe.**
Columns in most of visualizations can be renamed but it's no the case in Pie Charts 
![image](https://github.com/metabase/metabase/assets/109289055/1191af05-d2e6-472e-8bf1-35bf4ef7fbff)

**Describe the solution you'd like**
Just to add the option to rename the meausre column would be enough like in these cases
![image](https://github.com/metabase/metabase/assets/109289055/aa728589-476d-4ed2-8e17-17530902d2e8)

**How important is this feature to you?**
This lets details in visualizations have more customizable options. It may apply also to the other summarize columns that may appear in the details of a value, although it may be another request? I'm not sure.
![image](https://github.com/metabase/metabase/assets/109289055/3661bdc1-3220-41d6-98e6-30f2684fb436)

**Comment by cdeweyx** [comment] 2024-07-31 18:21
Dupe of https://github.com/metabase/metabase/issues/9312

**Closed** 2024-07-31 18:21 UTC
Labels: Type:New Feature, Visualization/Charts/Pie
