### ISSUE TITLE
Allow filtering of FieldValues in dashboard widgets

### ISSUE THREAD

**Issue by Sieboldianus** [metabase/metabase#8043] opened 2018-07-12 12:53 UTC
Your databases: PostgresQL 10.0
Metabase version: Metabase 0.29.3
Metabase hosting environment: Docker
-------

I've read [Documentation: SQL Parameters](https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html) but I still am not able to get it to work.
My problem:
- we have a large list of users
- some users are of specific type ("Member of German Bundestag")
- I wish to offer the Metabase user a Drop Down Selection Filter Widget on the Dashboard
- this Filter Widget should show a list of all "Member of German Bundestag"
- based on the name the user selects, the Dashboard Visuals should be filtered

I was able to write the SQL-Widget, and it works:

```sql
SELECT
 user_fullname
FROM
 data."user"
LEFT JOIN relations._user_memberof_group 
	ON data."user".user_guid = relations._user_memberof_group.user_guid
WHERE
relations._user_memberof_group.group_guid = 'MdB (Bundestag)'
[[AND {{MdB}}]]
```

... this SQL-Question looks like this:

![image](https://user-images.githubusercontent.com/13646666/42634101-9addb386-85e2-11e8-85a4-d910e31a9073.png)

But I can't add this as a Dashboard Filter List. I've added a Filter and Linked it to the SQL-Question inserted on the Dashboard, but..
- I don't get a list, I get a search box
- when I type a name, I get results from all names, not just from the "Member of German Bundestag" Group, e.g.:

![image](https://user-images.githubusercontent.com/13646666/42634261-037bc266-85e3-11e8-981d-8094b1de8764.png)

.. I was thinking of other ways of doing this, such as creating dynamic links based on the Table Question inserted on the Dashboard, but Custom Functions are not available in SQL-Questions:
![image](https://user-images.githubusercontent.com/13646666/42634338-3acd3c40-85e3-11e8-9490-e2b3c12904e0.png)

Is there any other solution to this problem?

**Comment by salsakran** [comment] 2018-08-14 00:07
We do not currently have a way to filter the values we pull from a column to power the filters.

**Comment by salsakran** [comment] 2018-08-14 00:07
simplest thing might be to create a one-off sql view for this.

**Comment by Sieboldianus** [comment] 2018-08-14 07:04
Many thanks @salsakran! I was confused as to how Dashboard filters are supposed to work, but we got it sorted out now (yes, SQL Filters and custom queries were the key!). It would be nice to have a feature to limit what users can select in a dashboard (independent of whats in the database), as you suggest, but it is not so important anymore for us. We can get around this with the tools that already exist.

**Comment by flamber** [comment] 2019-02-24 01:38
This looks very related to (possibly duplicate of) #5245 and #6820

**Comment by develar** [comment] 2019-11-19 06:53
I have the same problem — my dashboard has 3 filters (product, branch and project). Each next one depends on previous. But in the project list I see irrelevant values (not from selected product).

**Comment by flamber** [comment] 2019-11-19 06:58
@develar Sounds like you're looking for #5540 - upvote by clicking :+1: on the first post.

**Comment by flamber** [comment] 2020-05-28 14:55
Closing in favor of #5245/#6820
Also related #7603

**Closed by flamber** 2020-05-28 14:55 UTC
Labels: .Proposal, Querying/Native, Querying/Parameters & Variables, Reporting/Dashboards
