### ISSUE TITLE
Non-admin users see question query when they click on a question

### ISSUE THREAD

**Issue by atanas0** [metabase/metabase#14106] opened 2020-12-17 11:48 UTC
**Describe the bug**
Users with view only access to collections are seeing the question query whenever they click on a question in the dashboard and are lead to start a new question.
I've tested with removing filters from the dashboard one by one and at some point the bug disappears.
There are 4 filters in total.

**Logs**

![Screen Shot 2020-12-17 at 13 45 02](https://user-images.githubusercontent.com/13204176/102483891-1d794880-406e-11eb-8b38-76340ed87e14.png)

**To Reproduce**
1. Go to the Dashboard
2. Click on any of the questions

**Expected behavior**
User is supposed to be lead to the question page where he can e.g. download a csv export of a table.
Instead the user is lead to a new question started from the initial question where he sees the query and an error message:
"You do not have permissions to run this query."

Upon clicking on the hyperlink to the original question the user is lead to the question page as it should be.

**Screenshots**
![Screen Shot 2020-12-17 at 12 36 59](https://user-images.githubusercontent.com/13204176/102482875-8e1f6580-406c-11eb-955c-99a0e06100ba.png)

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.158-129.185.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-12-03",
      "tag": "v0.37.3",
      "branch": "release-x.37.x",
      "hash": "2f1e783"
    },
    "settings": {
      "report-timezone": "Europe/Athens"
    }
  }
}

**Severity**
It is annoying for users

**Additional context**
Issue has been persistent through the several previous versions.

**Comment by flamber** [comment] 2020-12-17 12:20
Hi @atanas0 
It looks like a duplicate of #12720, except that you are saying that it happens with SQL questions, which I cannot reproduce.
Can you reproduce with Sample Dataset?
And I think you are misunderstanding Collection and Data permissions. You can have users that have view-only collections, but they can still create their own questions because they have data permissions.
https://www.metabase.com/learn/organization/organization/data-permissions.html
https://www.metabase.com/learn/organization/organization/collection-permissions.html

**Comment by atanas0** [comment] 2020-12-17 17:42
Hi @flamber 
Thanks for the heads up. I think it's a different manifestation of the same issue - I had data access granted to the user for one of the tables. When I revoke it I get the same result as in #12720.
What seems to be working is creating a new question with some non-essential changes to the query and substituting the problematic query with it. It is working for now. I'll be reporting on whether this works around the issue for good.

**Comment by flamber** [comment] 2020-12-17 17:51
@atanas0 I'm not sure I understand, but I cannot reproduce. If you can reproduce with Sample Dataset, then please provide steps-to-reproduce.

**Closed by flamber** 2020-12-17 17:51 UTC
Labels: .Needs Triage, Type:Bug
