### ISSUE TITLE
Metabot Permissions Won't Save

### ISSUE THREAD

**Issue by bvallelunga** [metabase/metabase#18077] opened 2021-09-27 17:53 UTC
**Describe the bug**
By default all users do not have data or query access. When trying to give Metabot read and write permissions the save event fails.

**Logs**
This bug fails silently

**To Reproduce**
1. Metabase Admin
2. Permissions
3. Remove data and query permissions from all users
4. Save
4. Give Metabot data and query permissions
4. Save
5. Dashboard still shows it does not have permissions

**Expected behavior**
Permissions are updated

**Screenshots**
Slack Pulse Failing
<img width="463" alt="Screen Shot 2021-09-27 at 10 52 36 AM" src="https://user-images.githubusercontent.com/1920007/134959881-25a71365-81d6-4cb5-ade4-4756a69c3e56.png">

Before
<img width="2560" alt="Screen Shot 2021-09-27 at 10 51 04 AM" src="https://user-images.githubusercontent.com/1920007/134959713-f1f6e53d-33ce-47a2-8b06-adb8eec53799.png">

Save Modal
<img width="2560" alt="Screen Shot 2021-09-27 at 10 51 28 AM" src="https://user-images.githubusercontent.com/1920007/134959751-253a31f3-418a-451d-bab6-7083d29a4498.png">

After
<img width="2560" alt="Screen Shot 2021-09-27 at 10 51 04 AM" src="https://user-images.githubusercontent.com/1920007/134959713-f1f6e53d-33ce-47a2-8b06-adb8eec53799.png">

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
High. Our company relies on Slack pulses which are now not working.

**Comment by flamber** [comment] 2021-09-27 18:23
MetaBot does not have Data permissions, only Collection permissions. Duplicate of #10920.

**Closed by flamber** 2021-09-27 18:23 UTC
Labels: Type:Bug, .Needs Triage
