### ISSUE TITLE
Allow any numeric fields to be selected for lat/lon to support pin maps in SQL queries

### ISSUE THREAD

**Issue by camilonova** [metabase/metabase#5196] opened 2017-05-25 21:34 UTC
Seems it is supported if you have a column for latitude and a column for longitude, but since a database can have geospatial information it makes sense to support a PointField.

In case is not possible to support a PointField, there is a way to split a column into the values supported by the current map implementation?

**Comment by tlrobinson** [comment] 2017-05-25 22:06
Possibly a duplicate of #2327? I'm not familiar with `PointField`, from Googling it sounds like it might be a GeoDjango model, which I assume corresponds to a Postgres `point`?

@camilonova We don't currently support `point` columns directly. The easiest workaround right now would be to create a Postgres view that extracts it into latitude and longitude columns.

**Comment by camilonova** [comment] 2017-05-26 13:18
@tlrobinson You're right. I'm doing this query which extracts the latitude and longitude but the map is not recognizing the fields.
```
SELECT split_part(substring(ST_AsText(delivery_location) from '\((.*)\)'), ' ', 1) AS lat, split_part(substring(ST_AsText(delivery_location) from '\((.*)\)'), ' ', 2) AS lon from order_order;
```

And I get results on the table as:
![screen shot 2017-05-26 at 8 17 22 am](https://cloud.githubusercontent.com/assets/202559/26496113/cee9004a-41eb-11e7-80da-297cd6def855.png)

But I can't see the columns at the map configuration:
![screen shot 2017-05-26 at 8 17 33 am](https://cloud.githubusercontent.com/assets/202559/26496124/dbcab4d4-41eb-11e7-8c1d-df5141112cbe.png)

Do you know how I can make it work?

**Comment by tlrobinson** [comment] 2017-05-27 16:49
Ah. Unfortunately I think the frontend currently requires the columns to be marked as Latitude/Longitude types which isn't possible with SQL.

I think we'll have a way to do this in the next release.

If you want to do your own build of Metabase I think you could change all the instances of `isLatitude` and `isLongitude` to `isNumeric` in this file: https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/visualizations/Map.jsx#L61

**Comment by camilonova** [comment] 2017-05-27 17:27
Thanks. How it will be addressed in the next release? and when do you think is going to be released?

**Comment by brylie** [comment] 2017-11-20 13:59
I am also having this issue.

Is there a way to cast the floating point values to lat/lon types in the Postgres query?

**Comment by brylie** [comment] 2017-11-21 08:14
It just seems that data in decimal degrees is pretty common. Also, requiring the lat and lon to be stored in separate columns might be difficult for some projects that use WKT geometries (i.e. points). The only answers I have found about casting lat/lon decimal degrees to geometries recommends using [ST_GeogFromText](https://postgis.net/docs/ST_GeogFromText.html), which requires the lat/lon be in a single string:

https://stackoverflow.com/questions/34300616/how-to-cast-latitude-longitude-coordinates-as-postgres-geography-type

**Comment by Sieboldianus** [comment] 2018-05-23 08:37
> It just seems that data in decimal degrees is pretty common. Also, requiring the lat and lon to be stored in separate columns might be difficult for some projects that use WKT geometries (i.e. points). The only answers I have found about casting lat/lon decimal degrees to geometries recommends using ST_GeogFromText, which requires the lat/lon be in a single string:
> 
> https://stackoverflow.com/questions/34300616/how-to-cast-latitude-longitude-coordinates-as-postgres-geography-type

Can you describe how you implemented this in Metabase? We use a GEOM_Point column to store our lat/lng coordinates as PostGIS points in a single column and realize Metabase isn't recognizing this as a spatial data column.

**Comment by bmcbride** [comment] 2018-08-03 17:28
Any updates on the status of this issue?

**Comment by terrancesnyder** [comment] 2018-08-09 07:41
Yes, would like an update, while the data browser is nice, I'd like to use sql editor as well and pull in these fields.

**Comment by willlam** [comment] 2019-04-18 18:38
Having this issue as well and using a query like this to pull out lat/lon but I don't have the option of using the fields I've selected.

```SELECT
    JSON_EXTRACT(userGPSLocation, '$.latitude') as latitude,
    JSON_EXTRACT(userGPSLocation, '$.longitude') as longitude
    
from
taplytics:project_584724db5b0cb61200d0daa1.event_appActive
WHERE 
  userCreatedAt >= '2019-04-11T00:00:00.000Z' AND userCreatedAt < NOW()
  limit 100;```

**Comment by emetselaar** [comment] 2019-07-09 12:04
I have more or less the same issue. One column with lat,lon in there combined, but no way for me to seperate them in two columns. So now I cannot use the lat/lon in metabase visualizations.

**Comment by flamber** [comment] 2020-05-31 16:13
I cannot reproduce this on 0.32.9 thru 0.35.4, but looking at the screenshots, all the coordinates are left-aligned, which means they are strings. Casting as `float` would fix that.

Example from Sample Dataset):`SELECT * FROM PRODUCTS LIMIT 5`

This will show the numeric columns in pin map latitude/longitude selector:
![image](https://user-images.githubusercontent.com/1447303/83357012-fbd2a100-a369-11ea-8447-6b77c79f4444.png)

It's also possible to do with a database view, so Metabase UI could be used on those view-tables.

**Closed by flamber** 2020-05-31 16:13 UTC
Labels: Visualization/, Visualization/Chart Settings
