### ISSUE TITLE
unnecessary column appeared  when do  join from two questions  

### ISSUE THREAD

**Issue by szsuyuji** [metabase/metabase#14200] opened 2020-12-25 09:20 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/1931764/103129798-1210c780-46d5-11eb-9049-8e68633b49de.png)
 "source"."channel_name" and "source"."remark" is not exist in the first query，so i guess they were from the original table

metabase version: 0.37.4

**Comment by flamber** [comment] 2020-12-25 11:00
Duplicate of #13649

**Closed by flamber** 2020-12-25 11:00 UTC
Labels: .Needs Triage, Type:Bug
