### ISSUE TITLE
Include "today/this week/this month/this year" in relative date filters

### ISSUE THREAD

**Issue by christopheg** [metabase/metabase#4749] opened 2017-04-10 20:18 UTC
The Date filter to show 'past 2 years' (executed in 2017) will return results for 2015 + 2016.
Is there a filter where I can include the current year?
There seems to be no filter that does that and it is also not possible to combine multiple filters with 'OR' statement.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doodlebro** [comment] 2017-04-10 21:09
This sounds more like a bug with the "past X years" implementation.

**Comment by camsaul** [comment] 2017-04-10 21:24
@doodlebro it's intentional, we decided not to include the current year/month/day/etc. in `past <n> <units>` because partial data for the current year/month/day/etc. would be less useful for comparisons

@christopheg you could just do something like `year >= 2015`

**Comment by mazameli** [comment] 2017-04-10 21:35
What Cam said. You could also do `Previous 730 days` if you're looking for a rolling 2-year window.

**Comment by doodlebro** [comment] 2017-04-10 21:36
Why not add a 'rolling' option to the filter? Seems more user friendly than either solution offers.

**Comment by Microsheep** [comment] 2017-04-11 01:46
I have some dashboards that keep track of error job counts in the past 14 days.
I would love if we can fit the current day in the ```previous <n> <units>``` filters.
This can help me remove one card simply used to access the error job counts on the current day, making the dashboard cleaner.

Maybe add a checkbox to include the current day when using ```previous <n> <units>``` and ```next <n> <units>``` filters?

**Comment by christopheg** [comment] 2017-04-11 08:07
@mazameli 'Previous 730 days' is not completely what I'm looking for. This would the result would start for dates after april 2015, while 'last 1 year + current year' would start from januari.

**Comment by mazameli** [comment] 2017-04-11 19:38
@christopheg For sure; I wasn't sure what exactly your desired outcome was. As Cam suggested, does `After Dec 31 2014` fit your needs? That would include all of 2015 and 2016, and all of 2017 year-to-date. I understand this issue is more about what the expected behavior of `Past x [time units]` is, but the `After…` filter should be able to meet your immediate need.

**Comment by christopheg** [comment] 2017-04-11 19:58
Yes off course, that could be a solution. However if I only want to have the last 2 years, I have to modify my question every year.
I could fix this by going into SQL mode and change the condition to 'YEAR(created) >= YEAR(created)-2'
I prefer though to use the graphical query builder.

**Comment by moumny** [comment] 2017-04-11 20:35
I receive lots of questions about this behavior by our users. Perhaps adding the abiltity to include current unit would make it more explicit.
The problem with after is that is not a relative date.

**Comment by GuiSim** [comment] 2017-05-19 12:57
I came to github to report the missing current day/month/hour/minute bug.

It's especially tricky if you filter on one thing and group by another. I could look at the past 2 weeks, grouped by days.

I think the best solution would be to include the current day with some sort of visual cue telling you that the latest data point is "not complete". Perhaps some sort of "dotted outline" of the column above the current value which would let you know on hover that the current day/week/month is not completed yet.

**Comment by elburro1887** [comment] 2017-06-02 23:41
this is a serious oversight.

+1 for a checkbox that says "include today/current month/current year/etc".

Doing the "last XX days" or "after XX" is a hack and not what the user would be able to easily figure out. also, it doesn't work for every scenario. For example, we want to look at sales data that occurs during the last 30 days, and that would include the current day as well.

**Comment by mazameli** [comment] 2017-06-07 22:51
> +1 for a checkbox that says "include today/current month/current year/etc". …we want to look at sales data that occurs during the last 30 days, and that would include the current day as well.

@elburro1887 I do think the idea of an option to include the current, incomplete unit of time has some merit. Would you expect that to do the last 30 days _plus_ today so far, or the last _29 days_ plus today so far? I'm assuming the first option.

FWIW, one frame of reference we used for this was how other tools, like Google Analytics, treat things like "Last month," or "last 30 days" — in GA, "Last month" does not mean "the last 30 days;" and "the last 30 days" does not include today's partial data.

**Comment by mazameli** [comment] 2017-08-03 21:46
This could be a quick and dirty way to include this:

![include-current-period](https://user-images.githubusercontent.com/2223916/28945149-2462a860-785a-11e7-801c-03add5e0ccdc.png)

For `Previous` filters, the label says "Include this [x] **so far**" to reinforce it's only partial data for that time period. But one thing that remains ambiguous to me about this is whether the `Next` filter should include the entirety of the current period, or just the _remaining_ portion. E.g., if it's August 15, and I say `Next 3 months, including this month`, should it be August 15–November 30, or August **1**–November 30?

**Comment by doodlebro** [comment] 2017-08-04 16:10
@mazameli 

> E.g., if it's August 15, and I say Next 3 months, including this month, should it be August 15–November 30, or August 1–November 30?

If you wanted it to be August 15-November 30, setting the granularity to 'Next X days' and having a checkbox for 'Include the current day' seems like the most user friendly and intuitive way.

When you want it to be August 1 to November 30, saying 'Next 3 months, including this month' makes sense in terms of the semantics. It would not make sense to have an option to 'include this month' on monthly data and only include a partial month.

A month is a month, it is defined by the time between the first and last day of the month.

This seems unnecessarily complex for something that most BI reporting tools do not have trouble with. The way this functionality currently sits, there is much confusion about why dates are/are not included in a 'Next/Last 3 months' filter.

I don't think its wise to assume how much of a month the user wants to include. It should simply be up to the user. If a user wants to exclude the current month, couldn't they add another date filter where date > current month?

Keep it simple.

**Comment by darylteo** [comment] 2017-08-22 04:59
Just came across this myself. Selecting "Past 7 days" does not include the current day, which led me to panic because apparently my emails were not sending. Commenting to push issue. 

They were, but simply weren't being displayed "live". 

Just my 2c. The "checkbox" idea seems the best at clearing up misunderstanding.

**Comment by larntz** [comment] 2017-08-25 19:09
Wanted to add to the thread that I would be overjoyed with the option to include the current day/week/month/year/decade/century/etc.

Metabase is really freaking cool! Thanks for your work thus far!

**Comment by elburro1887** [comment] 2017-09-25 20:58
@mazameli In Google Data Studio, there is a checkbox, and they shift the date range by +1 day automatically if one chooses to include the current day (see screenshots). I guess metabase could adapt this behavior as well?


<img width="466" alt="screen shot 2017-09-25 at 22 52 11" src="https://user-images.githubusercontent.com/13376225/30830473-6f4b337e-a244-11e7-8692-2fa46c1d6e11.png">

<img width="464" alt="screen shot 2017-09-25 at 22 52 03" src="https://user-images.githubusercontent.com/13376225/30830472-6f4a29ca-a244-11e7-9c28-9e7131e13354.png">

**Comment by viniciusoyama** [comment] 2017-11-14 12:51
👍  Same problem here. I would really appreciate a 'Include today|this month|this year...' checkbox.

**Comment by mazameli** [comment] 2017-11-21 20:24
I think that the designs I included in [this comment above](https://github.com/metabase/metabase/issues/4749#issuecomment-320098922) still work for this issue as an incremental step.

I showed @kdoh and @salsakran some updated designs today, but the layout and visual tweaks I included in those designs aren't required for shipping the checkbox. (Though I will create a separate issue to propose the layout changes.)

**Comment by dgleba** [comment] 2017-12-01 17:39
I like the checkbox to include current period idea. I also like the idea of a visual cue to indicate that it is a partial period. It could be hashed or colored. It could have an asterisk and a note saying that is a partial period.

**Comment by camsaul** [comment] 2017-12-04 21:11
Duplicate of #2496? Ping @kdoh

**Comment by camsaul** [comment] 2017-12-06 21:30
@kdoh @mazameli bump. Since #2496 is a duplicate we should close one or the other. The both have a decent amount of activity, but since you've been the ones working on this, I thought you guys could decide which one we keep around? No point in having two issues for one feature.

LMK. Otherwise I can just go ahead and close this out in favor of the other one

**Comment by camsaul** [comment] 2018-01-15 18:41
Implemented by #6530

**Closed by camsaul** 2018-01-15 18:41 UTC
Labels: Proposal, Query Builder
