### ISSUE TITLE
Date/Time Question does not match View these Records

### ISSUE THREAD

**Issue by liransmartlighthouse** [metabase/metabase#10767] opened 2019-08-30 18:59 UTC
**Describe the bug**
I have a Question that shows a table that counts rows by Day and Time. 
For example: how many sessions took place on Monday at 4pm for example.

I have read the Time FAQ guide and don't think the issue is related to this.The reason I think this is because I can confirm that the Database record timestamp matches the Metabase value.

**To Reproduce**
Create a Table and group by Day of Week AND Time Hour of Day (they are the same in my case):
![image](https://user-images.githubusercontent.com/42851040/64044405-4f3e6700-cb2c-11e9-91ca-8e268ac477ec.png)

Click on the numbers associated with 4 pm (or whatever row you want) to view these Records and you see No results:
![image](https://user-images.githubusercontent.com/42851040/64044484-8745aa00-cb2c-11e9-9064-09824724c08c.png)

**Expected behavior**
Since the initial table tells me there are 2 records at the 4 pm time slot, I would expect to be able to see 2 records

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 76.0.3809.100 (Official Build) (64-bit)
- Your operating system: Windows 10 version 1903
- Your databases: MySQL
- Metabase version: 0.32.4
- Metabase hosting environment: EC2
- Metabase internal database: MySQL

**Severity**
High, showing inaccurate information and reducing user confidence in the system

**Additional context**
Since the database value for the record is 4:30 pm, the table shows records between 4 pm and 4:59 pm for which there are 2 (4:30 pm, 4:45 pm). 

When clicking to view these records, Metabase applies a filter of Time:Hour of day is 4 PM (as shown in screenshot 2)

It seems like the way the table is filtered/grouped is different than the filters when viewing the records.

**Comment by Sire** [comment] 2019-12-05 14:50
Let me know if you haven't been able to reproduce this in the sample database. I can send an example.

**Comment by flamber** [comment] 2019-12-05 17:21
@Sire If you have a way to reproduce on Sample Dataset, then please post that. It makes debugging a lot easier, since we all have access to that.

**Comment by Sire** [comment] 2019-12-06 07:32
Sure. I think I located the bug as well. With the filter "previous 12 months", for 2019-12 there are 550 rows (which is correct):

![image](https://user-images.githubusercontent.com/205954/70303848-dc1a5000-1800-11ea-96a0-da5bba77fafe.png)

But when drilling down to "view these orders" there are only 541 rows.
Filter is "created_at is December, 2019. This type of filter doesn't seem to exist in the GUI.

![image](https://user-images.githubusercontent.com/205954/70304004-37e4d900-1801-11ea-8358-4d6be7e724f0.png)

The two queries explains the incorrecrt data. Query 2 has a off-by-one error, where you have selected November instead of December:

```
SELECT parsedatetime(formatdatetime("PUBLIC"."ORDERS"."CREATED_AT", 'yyyyMM'), 'yyyyMM') AS "CREATED_AT", count(*) AS "count"
FROM "PUBLIC"."ORDERS"
WHERE parsedatetime(formatdatetime("PUBLIC"."ORDERS"."CREATED_AT", 'yyyyMM'), 'yyyyMM') BETWEEN parsedatetime(formatdatetime(dateadd('month', -12, now()), 'yyyyMM'), 'yyyyMM')
   AND parsedatetime(formatdatetime(now(), 'yyyyMM'), 'yyyyMM')
GROUP BY parsedatetime(formatdatetime("PUBLIC"."ORDERS"."CREATED_AT", 'yyyyMM'), 'yyyyMM')
ORDER BY parsedatetime(formatdatetime("PUBLIC"."ORDERS"."CREATED_AT", 'yyyyMM'), 'yyyyMM') ASC
```

```
SELECT "PUBLIC"."ORDERS"."ID" AS "ID", "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT", "PUBLIC"."ORDERS"."DISCOUNT" AS "DISCOUNT", "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID", "PUBLIC"."ORDERS"."QUANTITY" AS "QUANTITY", "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL", "PUBLIC"."ORDERS"."TAX" AS "TAX", "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL", "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID"
FROM "PUBLIC"."ORDERS"
WHERE ("PUBLIC"."ORDERS"."CREATED_AT" >= timestamp '2019-11-01T00:00:00.000Z'
   AND "PUBLIC"."ORDERS"."CREATED_AT" < timestamp '2019-12-01T00:00:00.000Z')
LIMIT 1048576
```

**Comment by flamber** [comment] 2019-12-06 17:33
@Sire Excellent. There has been a lot of timezone fixes lately, but there's a couple of big ones in  upcoming 0.34.0, which fixes your example. I can reproduce on 0.33.6, but not on `master`.
The generate query now includes `with time zone`:
```
SELECT "PUBLIC"."ORDERS"."ID" AS "ID", "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT", "PUBLIC"."ORDERS"."DISCOUNT" AS "DISCOUNT", "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID", "PUBLIC"."ORDERS"."QUANTITY" AS "QUANTITY", "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL", "PUBLIC"."ORDERS"."TAX" AS "TAX", "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL", "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID"
FROM "PUBLIC"."ORDERS"
WHERE ("PUBLIC"."ORDERS"."CREATED_AT" >= timestamp with time zone '2019-12-01 00:00:00.000-06:00'
   AND "PUBLIC"."ORDERS"."CREATED_AT" < timestamp with time zone '2020-01-01 00:00:00.000-06:00')
LIMIT 1048576
```
The question now is if this is the same problem that @liransmartlighthouse was having?

**Comment by liransmartlighthouse** [comment] 2019-12-06 18:49
Hey guys,

Let me provide more details on my issue.

The first thing that's different is my issue was not in SQL - this may 
or may not be relevant. I am using the UI to pose a question. The other 
difference is that my filter was a Time: Hour of day filter.

Using the sample data (Orders) I have the following question:

Notice 12 AM has 6 records.

When I click to View these Orders the first issue is that the date 
filter is not applied. This may be another issue altogether that's out 
of scope in this example. After applying a date filter to match the 
question this is my result:


Notice the hours are off (6 AM). Also, the record count does not match. 
I would have expected to see the 6 records associated with the 12 am 
time slot.

One more example. In the first screenshot, 5 AM had 7 records. However 
when clicking to view these orders, then applying the date filter, no 
results appear:

I believe this is the core of my issue. That when clicking on 5 AM - 7 
records, I'd like to see those matching records.


------ Original Message ------

**Comment by flamber** [comment] 2019-12-06 20:21
@liransmartlighthouse 
Think images/attachments gets stripped from emails by Github, so it seems it's lacking some info.

On your first post, what's the first filter that is being clipped on the "No results" screenshot?
Are you seeing a different behavior on 0.33.6?

I think I have reproduced your issue with Sample Dataset, but I'm not getting "No results", instead I'm getting all results from all dates, but on the specific "Day of Week" and "Hour of Day".
I would think that you're seeing "No results" because of some of the timezone fixes.

**Reproduce:** When you use the same date field/column in Filter and Group By, then when doing drill-through, it will only apply a single filter for the date field, which will be the "group by" selection.
![Screenshot_2019-12-06 Question · TestA1](https://user-images.githubusercontent.com/1447303/70352832-ac377080-1831-11ea-860f-d4444e9c6c45.png)
![Screenshot_2019-12-06 Question · TestA2](https://user-images.githubusercontent.com/1447303/70352842-af326100-1831-11ea-9078-6a9eb00ffbc1.png)
![Screenshot_2019-12-06 Question · TestA3](https://user-images.githubusercontent.com/1447303/70352846-b194bb00-1831-11ea-973d-9a12f27daff4.png)

**Workaround:** Join with the main table again, and make sure Filter is using the main table, while the Group By uses the joined tables.
![Screenshot_2019-12-06 Question · TestB1](https://user-images.githubusercontent.com/1447303/70352948-e9036780-1831-11ea-8bc3-856785c43de3.png)
![Screenshot_2019-12-06 Question · TestB2](https://user-images.githubusercontent.com/1447303/70353596-595eb880-1833-11ea-9682-10decadb3c80.png)
![Screenshot_2019-12-06 Question · TestB3](https://user-images.githubusercontent.com/1447303/70352965-ee60b200-1831-11ea-9c37-a1ac56b657b8.png)

**Comment by liransmartlighthouse** [comment] 2019-12-06 20:37
@flamber - first, thank you for your help.

Updated comment from 2 hrs ago with screenshots.

Will try workaround on 0.33.6 later today and post update.

**Comment by flamber** [comment] 2019-12-06 21:02
@liransmartlighthouse 
Okay, now I understand [your comment](https://github.com/metabase/metabase/issues/10767#issuecomment-562692835) with the images added :smile: 

1. "Notice 12 AM has 6 records." only showing 5 records, and "5 AM had 7 records" showing nothing, when drilling, that's a timezone issue, which is fixed and will be part of 0.34.0. I'm seeing all the records on `master`. There was a separate issue on that (#11251) and a long [forum thread](https://discourse.metabase.com/t/aggregations-on-individual-grouped-by-fields-and-showing-the-records-within-each-group/6754), if you're interested in reading about it.
2. As for the date filter getting removed, that's the same problem as I pointed out in [previous comment](https://github.com/metabase/metabase/issues/10767#issuecomment-562723808), where it doesn't allow using Filter and Group By, when also using drill-through, since it replaces the original Filter instead of adding a new one.
For me, this is the core issue here, but if you feel that was a secondary problem, then please close this issue and I'll open a new issue about it.

**Comment by kulyk** [comment] 2021-06-23 10:08
After some investigation around the issue, I can say the root cause is probably the `drillFilter` function at the models lib. As you can see [here](https://github.com/metabase/metabase/blob/88fd71e0ccf5153e82ec84e0290544a9862f4cf1/frontend/src/metabase/modes/lib/actions.js#L146), when drilling through a date column, the filter is going to be always replaced with `=`. It was like that since the drill-through feature has been implemented (see [here](https://github.com/metabase/metabase/blob/8f544c90d8c6286ee6afa4ca70c5c58db9435256/frontend/src/metabase/qb/lib/actions.js#L76) from #4496)

Unfortunately, it doesn't look like a simple thing to fix. We'll probably need to build some more tooling for drilling-through dates specifically (please correct me if we already have something for that)

**Comment by WiNloSt** [comment] 2023-11-08 11:35
Reproducible on 0.33.6 and master (e0ebd085cc168d75692c4ec584bb71994011dc83)

![image](https://github.com/metabase/metabase/assets/1937582/6602a75b-0ba7-48b2-a2ff-6454b3c756ff)
![image](https://github.com/metabase/metabase/assets/1937582/1644d99f-fe4e-4940-82ab-52798e46857a)

**Comment by bshepherdson** [comment] 2024-02-15 20:31
I can repro this on 0.33.6 as above but not on master. It now correctly selects three filters: `Created At is Feb 14, 2024`, `Created At: Day of week is equal to 4`, `Product -> Created At: Hour of day is equal to 14`, showing the same 2 results that were claimed by the aggregation.

![2024-02-15-153055_1816x1392_scrot](https://github.com/metabase/metabase/assets/157812/bd0c05bd-7ad8-4c43-aa63-5546c1e324ee)
![2024-02-15-153108_1919x445_scrot](https://github.com/metabase/metabase/assets/157812/8d97a9ae-44c7-4fb1-8422-e86b42d9f900)

**Closed by bshepherdson** 2024-02-15 20:31 UTC
Labels: Type:Bug, Priority:P2, .Correctness, .Backend, Querying/GUI, .Wanted: MLv2, .Team/QueryingComponents
