### ISSUE TITLE
[P0] Scaffolding from a custom model completely fails

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26700] opened 2022-11-23 13:49 UTC
1. Create a model manually
2. Try to create an app using it as starting data
3. Get an error

Not sure if this is FE or BE, so assigning to both Anton and Case.

**Comment by kulyk** [comment] 2022-11-23 14:43
Closing as it seems to be reproduced on an outdated build of `data-apps-main`

**Closed by kulyk** 2022-11-23 14:43 UTC
