### ISSUE TITLE
Maridb Rocksdb engine support

### ISSUE THREAD

**Issue by hemmat** [metabase/metabase#44270] opened 2024-06-16 15:16 UTC
When i connect to a Mariadb databse and sync the tables, tables that use Rocksdb engine are not being detected, seems like Metabase mysql connector is unable to read these tables.

**Comment by paoliniluis** [comment] 2024-06-17 10:26
I think this is a duplicate of https://github.com/metabase/metabase/issues/42734

**Closed** 2024-06-17 10:27 UTC
Labels: Database/MySQL, Type:New Feature, .Needs Triage
