### ISSUE TITLE
SQL Server RowCount Override not persisting

### ISSUE THREAD

**Issue by brywhi** [metabase/metabase#39789] opened 2024-03-07 17:27 UTC
### Describe the bug

After upgrading to Metabase 0.48.8, MS SQL Server database connections are yielding bad results due to the ROWCOUNT Override not saving in the UI. You can change it from blank to 0  or 1,000,000 or any number, and after refreshing the page, it goes back to blank again. Furthermore, watching in SQL Server Profiler, you can see on the trace that the rowcount is still being set to 2,000.

### To Reproduce

1. Go to Metabase Admin
2. Open a MS SQL Server database
3. Set ROWCOUNT Override to some value
4. Click save changes, get success message
5. Refresh browser, and Rowcount override is back to null

### Expected behavior

Rowcount override should persist

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7-post-Ubuntu-0ubuntu222.04.1",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7-post-Ubuntu-0ubuntu222.04.1",
    "os.name": "Linux",
    "os.version": "5.15.0-97-generic",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "h2",
      "mysql",
      "athena",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.36-0ubuntu0.22.04.1"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-04",
      "tag": "v0.48.8",
      "hash": "a900c85"
    },
    "settings": {
      "report-timezone": "US/Mountain"
    }
  }
}
```

### Severity

High, we are rolling back updates

**Comment by brywhi** [comment] 2024-03-07 17:54
We rolled back to 0.48.4 which we were running before, and it seems the UI bug still exists- after refreshing, we can't see the value in database configuration. However, it does persist the configuration properly, and I can confirm in SQL Server Profiler that it is setting the rowcount correctly in 0.48.4, even though the UI is still wrong.

**Comment by brywhi** [comment] 2024-03-14 18:04
Has anyone else experienced this? Just trying to understand if we did something wonky, or if other folks are experiencing it too.

**Comment by paoliniluis** [comment] 2024-03-14 21:13
@luizarakaki maybe this has to do with the new env vars for aggregated and non-aggregated queries?

**Comment by lssdo12** [comment] 2024-04-06 05:23
Encountered the same problem, but it still hasn't been fixed in 0.49.3

**Comment by brywhi** [comment] 2024-04-08 15:13
> @luizarakaki maybe this has to do with the new env vars for aggregated and non-aggregated queries?

FYI- I did try playing with the new env var settings in my environment, but no luck in fixing this issue.

**Comment by luizarakaki** [comment] 2024-04-08 16:35
@brywhi did you try setting 
[MB_UNAGGREGATED_QUERY_ROW_LIMIT](https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_unaggregated_query_row_limit) to 1000000
And [MB_AGGREGATED_QUERY_ROW_LIMIT](https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_aggregated_query_row_limit) to 1000000 too?

**Comment by luizarakaki** [comment] 2024-04-08 16:51
Hm... actually, I think this should still work.
Can you wipe your plugins directory?

My best guess is that you have an old driver that didn't get this PR https://github.com/metabase/metabase/pull/36753/files

**Comment by brywhi** [comment] 2024-04-08 16:53
> Hm... actually, I think this should still work. Can you wipe your plugins directory?
> 
> My best guess is that you have an old driver that didn't get this PR https://github.com/metabase/metabase/pull/36753/files

I'm running off the .jar for this particular instance- so unless the build didn't get that PR, it should have it, right?

**Comment by brywhi** [comment] 2024-04-08 16:54
> @brywhi did you try setting [MB_UNAGGREGATED_QUERY_ROW_LIMIT](https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_unaggregated_query_row_limit) to 1000000 And [MB_AGGREGATED_QUERY_ROW_LIMIT](https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_aggregated_query_row_limit) to 1000000 too?

Pretty sure we did try both. We'll make a clone of the environment where it is running and double check.

**Comment by luizarakaki** [comment] 2024-04-08 16:59
> > Hm... actually, I think this should still work. Can you wipe your plugins directory?
> > My best guess is that you have an old driver that didn't get this PR https://github.com/metabase/metabase/pull/36753/files
> 
> I'm running off the .jar for this particular instance- so unless the build didn't get that PR, it should have it, right?

It should, but if you are running in the same env as previous versions, it is possible that it didn't update the plugins.

> Pretty sure we did try both. We'll make a clone of the environment where it is running and double check.
Cool, let me know

**Comment by luizarakaki** [comment] 2024-04-08 19:24
Ok, for who is going to fix this:

This is likely caused by https://github.com/metabase/metabase/pull/36753
---

This SQL Server specific setting is weird. It is changing a global instance setting that applies to all queries from all databases. Since we introduced `unaggregated-query-row-limit` and `aggregated-query-row-limit` on v48 (that are truly global), this solution for this is:

- if sql server row count is set, migrate this to the new settings (both aggregated and unaggregated)
- drop this driver-specific detail and remove it from driver specs

---
workaround while we don't fix:
- the new env vars should work (you need to set both)

**Comment by camsaul** [comment] 2024-04-08 19:28
>if sql server row count is set, migrate this to the new settings (both aggregated and unaggregated)

Hmmm, setting a global Setting based on an override for one specific database seems a little dangerous for a "fix", query results for non-SQL Server DBs could change and people would not know why it happened.

**Comment by metamben** [comment] 2024-06-03 14:29
@luizarakaki what's the desired behavior? How should `unaggregated-query-row-limit` and `aggregated-query-row-limit` interact with this setting?

**Comment by luizarakaki** [comment] 2024-06-03 20:55
I think we should drop the SQL Server specific env var and ask people to use the new env vars (they need to manually set it)

**Comment by metamben** [comment] 2024-06-11 20:09
Discussing with @luizarakaki, the conclusion is that we want to drop the `rowcount-override` support from the connection details.

**Closed** 2024-07-08 22:14 UTC
Labels: Type:Bug, Priority:P1, Database/SQLServer, .Regression, .Team/QueryProcessor
