### ISSUE TITLE
bug: multiple summarization on one date

### ISSUE THREAD

**Issue by merchantsally** [metabase/metabase#34989] opened 2023-10-23 20:43 UTC
### Describe the bug

I'm noticing with this version of metabase that you will be able to group by a date column multiple times by accident. usually if you select a date column, the column turns green, and you can only edit the date grouping (between day, week, year, etc.), but in this version, after you select the date column, the column does not turn green, and you can repeatedly add a bunch of date groupings on the same column, but you will get an error like screenshot 1.
when this happens you want to go into edit and you will find screenshot 2. if you delete all the irrelevant groupings then the error will go away.
![image](https://github.com/metabase/metabase/assets/47093097/ac340b89-568a-4ec8-b54d-7bad60c7410e)
![image](https://github.com/metabase/metabase/assets/47093097/89eaa511-59cb-4141-bca1-759b2af26735)

### To Reproduce

1. group by a date field
2. group by the date field more

### Expected behavior

date field should turn green and look like a summarized column so people don't accidentally press it again

### Information about your Metabase installation

```JSON
n/a
```

### Severity

not severe, has work arounds

**Comment by kulyk** [comment] 2023-10-24 14:33
@merchantsally, thanks for reporting the issue 🙏 I've tried a few ways to reproduce it, but I'm afraid I couldn't. Could you please share more detailed repro steps?

Also, it would really help if you let us know which version of Metabase you're running. If you're an instance admin, please copy-paste the "Diagnostics info" JSON from `/admin/troubleshooting/help` and include it in the issue. if you're not an admin, please click the "gear" icon at the top right, and click "About Metabase" to see which version you're on

**Comment by zbodi74** [comment] 2023-10-24 15:06
This looks like a duplicate of https://github.com/metabase/metabase/issues/34662 .

**Closed** 2023-10-24 19:58 UTC
Labels: Type:Bug, .Needs Triage
