### ISSUE TITLE
Same model showing multiple times after doing joins to other tables

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#37027] opened 2023-12-20 23:55 UTC
### Describe the bug

I have joined Account model with 5 other models that has foreign keys to the Account model and Customer model.
When I try to filter or summarize, there seems to be several Account and Customer models. I am guessing they are for each joined models, but it's too confusing as I can't tell them apart as they look the same. 

### To Reproduce

1. Join a model with many other models that have foreign key mapping to the starting model and other common models. 
2. Notice the starting/common models show up multiple times and look exactly the same when filtering or summarizing.

### Expected behavior

Only show once or show them with more info to differentiate them

### Logs

n/a

### Information about your Metabase installation

```JSON
master @ Postgres
```

### Severity

Can't use filtering effectively as I can't tell which model to filter on

**Comment by darksciencebase** [comment] 2023-12-21 05:47
https://github.com/metabase/metabase/issues/36185 ?

**Comment by paoliniluis** [comment] 2023-12-21 18:34
@maxzheng can you check @darksciencebase comment above_

**Comment by maxzheng** [comment] 2024-03-21 16:39
Not the same as this is multiple tables and not related to columns.

**Comment by kamilmielnik** [comment] 2024-06-28 08:38
I can't tell from the description what the symptoms are exactly.
@maxzheng can you please provide recording or a screenshot? They're invaluable in bug reports.

**Comment by ranquild** [comment] 2024-07-01 20:47
Repro on stats

1. Open https://stats.metabase.com/question/18477-repro-37027/notebook
2. Click filter (in the first stage, before aggregation)
3. Collapse the first section
4. See there are multiple `Customer` groups. 

MLv2 function calls:
- `filterableColumns` -> `groupColumns` -> `displayInfo` on each group

Expected behavior:
- There should be no duplicate column names

Ideas how to fix this:
1. Add the join alias if there are multiple implicit join groups with the same name
2. At least run `unique-name-fn` or similar for names to be unique

**Comment by ranquild** [comment] 2024-08-21 19:01
Duplicate of https://github.com/metabase/metabase/issues/46845

**Closed by ranquild** 2024-08-21 19:01 UTC
Labels: Type:Bug, Priority:P2, Querying/MBQL, .Backend, .Team/Querying
