### ISSUE TITLE
Users with "No self-service" permissions on tables can't use cascading filters

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#24029] opened 2022-07-15 20:19 UTC
**Describe the bug**
When configuring cascading filters with 2 categorical fields, if a user doesn't have self-service permissions the cascading will fail and the user will have a search box only. The crazy thing is: if you click on the filters separately, you'll see the values

**Logs**
You'll get "You don't have permissions to do that." on the backend and a 403 on the FE

**To Reproduce**
1) New->question->people. Save this question and add it to a dashboard
2) on the dashboard add 2 filters: Location connected to State column, and category, connected to Source in the card. Link them, doesn't matter which. Save it
3) go to settings->admin->people-> create a new user
4) go to settings->admin->permissions. Remove from the all users the permission to do self service on the table "People"
5) Authenticate as the newly created user- >Go to the dashboard ->Click on the first filter and see the options // Click on the second filter and also see the options
6) Click on the source filter (the one that is not linked) and select any option. Then click on the second filter, you'll get a search box and the network tab will show 403

**Expected behavior**
If you have permissions to get the filter values without the cascading, you should have the permissions to do the cascading as well, even though you have "no self service"

**Screenshots**
Dashboard with linked filters seen as an admin
![image](https://user-images.githubusercontent.com/1711649/179304142-683916d1-f017-42e0-b922-dfab56002544.png)
![image](https://user-images.githubusercontent.com/1711649/179304099-103c6c10-7d69-4197-b5de-40a4205e2b81.png)

Dashboard with linked filters seen as a user who doesn't have self service permissions on the people table
Now you see
![image](https://user-images.githubusercontent.com/1711649/179304354-d59bcaba-e9f2-46f6-a4a5-d86de0f08d29.png)
![image](https://user-images.githubusercontent.com/1711649/179304393-e006de88-4ed6-47b8-914d-a78c6472d09e.png)

Now you don't
![image](https://user-images.githubusercontent.com/1711649/179304439-ad84f63b-6f93-4b12-8ed9-737baef21d82.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop-OS 22.04
- Your databases: Postgres 14.2
- Metabase version: 1.43.4
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14.2

**Severity**
P1'ish?

**Additional context**
Maybe a cousin of https://github.com/metabase/metabase/issues/12654?

**Comment by flamber** [comment] 2022-07-23 10:48
This is a duplicate of #13537, which is very related to #12654. If you clear cached field values, then no-data user would not see dropdown either.

**Closed** 2023-03-01 02:20 UTC
Labels: Type:Bug, Priority:P2, Reporting/Dashboards, Administration/Permissions, Querying/Parameters & Variables
