### ISSUE TITLE
scatter plot 'y-Axis auto range' uses poor values 

### ISSUE THREAD

**Issue by rfriedr1** [metabase/metabase#11969] opened 2020-02-24 16:34 UTC
**Description**
When using the "y-axis auto range" of a scatter plot the minimum value is always set to "0" which results in a unusable Y-axis range when plotting small number. See screen shot.

**To Reproduce**
1. Go to a scatter plot
2. Click on 'setting'
3. Click on 'axis'
4. Toggle on 'Auto y-axis range'
5, y-axis min is set to zero

**Expected behavior**
y-axis min should be set to a sensible value depending on the numbers that are plotted. E.g. when plotting alot of numbers that fall around 1.3 the min value should be around 1.2 or so and not 0. Otherwise the y-scale is so much spread out that the scatter in the data is not visible. autorange should adjust to the min/max of the plotted data, like min_y = min_data+5% (see Screenshot)

**Screenshots**
![screenshot_metabase2](https://user-images.githubusercontent.com/4603154/75171240-9d26d700-572b-11ea-8a67-c51a7a012f19.png)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_221-b11",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_221",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.221-b11",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "de",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.2",
      "date": "2020-02-04",
      "branch": "release-0.34.x",
      "hash": "dab738c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
not severe

**Comment by flamber** [comment] 2020-02-24 18:29
Hi @rfriedr1 

This is not specific to scatter charts - it's the same for line/bar/area too - starting value is always 0, when using "Y-axis scale"=Linear.
If you set the "Y-axis scale"=Log, then you should get what you want.

It feels like a duplicate of #7196 - just reversed - you might recognize the issue :wink:
What do you think - should we close this as a duplicate?

As for step5, when you disable auto-range, then the value is always 0-100 - that's covered by #3061.

**Comment by rfriedr1** [comment] 2020-02-24 20:29
yes, that's a doublicate then. I somehow thought the issue was fixed an reappeared... Thanks!

**Comment by flamber** [comment] 2020-02-25 15:14
Duplicate of #7196

**Closed by flamber** 2020-02-25 15:14 UTC
Labels: .Duplicate, Type:Bug
