### ISSUE TITLE
Incorrect numeric formatting in subscription

### ISSUE THREAD

**Issue by jkeys089** [metabase/metabase#24770] opened 2022-08-15 19:24 UTC
**Describe the bug**
Dashboards delivered via email subscription are incorrect when applying numeric formatting to schema.

**Logs**
N/A

**To Reproduce**
1. Create a `test` table and insert sample data ([test.mv.db](https://github.com/metabase/metabase/files/9339357/test.mv.db.zip)):
    ```sql
    CREATE TABLE IF NOT EXISTS PUBLIC.TEST
    AS (
      SELECT CURRENT_TIMESTAMP() AS ts, 123 AS total_cents
      UNION ALL
      SELECT CURRENT_TIMESTAMP() AS ts, 99 AS total_cents
      UNION ALL
      SELECT CURRENT_TIMESTAMP() AS ts, 1999 AS total_cents
      UNION ALL
      SELECT CURRENT_TIMESTAMP() AS ts, 321 AS total_cents
    );
    ```
2. Add `test` H2 database to Metabase with display name `test`
3. In `Admin settings` > `Data Model` > `test` > `Test` set `TOTAL_CENTS` type to `Currency`
4. Click setting gear icon next to `TOTAL_CENTS` then click `Formatting` and set `Multiply by a number` to `0.01` and exit admin
5. Create a question from `Raw Data` > `test` > `Test` and summarize by `Sum of Total Cents`
6. Click on `Visualize` and initially see a value of `$25.42`
7. Click `Visualization` in bottom left and switch to a `Progress` bar visualization and set a `Goal` of `5000`
8. Click `Save` and then add to a dashboard to see the progress bar a little more than half complete (`$25.42` of `$50.00`)
9. Click the envelope-plus `Subscriptions` icon in the top-right and select `Email it` and add yourself in the `To:` field
10. Click `Send email now` and get an email showing a progress bar a little more than half complete (`2,542` of `5,000`)

**Expected behavior**
Progress bar chart delivered via email should match values of progress bar chart displayed on web

**Screenshots**
Dashboard in browser:
![browser](https://user-images.githubusercontent.com/1695857/184696290-5036c8ae-68e0-45f7-bdc6-a0b59c4906ef.png)

Dashboard delivered via email:
![email](https://user-images.githubusercontent.com/1695857/184696328-5d81b84a-650d-4661-b65f-defd7d3d1ea2.png)

**Information about your Metabase Installation:**
```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "18+0",
    "java.vendor": "Homebrew",
    "java.vendor.url": "https://github.com/Homebrew/homebrew-core/issues",
    "java.version": "18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "18+0",
    "os.name": "Mac OS X",
    "os.version": "12.5",
    "user.language": "en",
    "user.timezone": "America/Indiana/Indianapolis"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2022-07-26",
      "tag": "v0.44.1-SNAPSHOT",
      "branch": "tf-v0.44.0",
      "hash": "b0f60fe"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

- Your browser and the version: Chrome 104.0.5112.79 (Official Build) (arm64)
- Your operating system: macOS 12.5
- Your databases: H2, BigQuery
- Metabase version: v0.44.0
- Metabase hosting environment: run locally from latest release (https://github.com/metabase/metabase/releases/tag/v0.44.0)
- Metabase internal database: H2

**Severity**
How severe an issue is this bug to you? It is impacting all subscriptions for all users. Although the data is technically correct it is off by a factor of 100 which make the data very difficult to read / understand.

**Additional context**
We were able to replicate this issue with both H2 and BigQuery.

**Comment by flamber** [comment] 2022-08-15 19:40
Duplicate of #3735

**Comment by alxnddr** [comment] 2022-12-08 00:23
@jkeys089 the issue got better but still persists — it does not show a currency symbol defined in the data model. Reopening the issue

**Comment by cdeweyx** [comment] 2024-07-22 20:22
Dupe of https://github.com/metabase/metabase/issues/33798 which was closed

**Closed by cdeweyx** 2024-07-22 20:22 UTC
Labels: Type:Bug, Priority:P2, Reporting/Pulses, Customization/Formatting, Visualization/Static, .echarts-scope, .Team/DashViz
