### ISSUE TITLE
[Epic] Sidesheets

### ISSUE THREAD

**Issue by rafpaf** [metabase/metabase#47243] opened 2024-08-26 16:00 UTC
```[tasklist]
### Tasks
- [ ] Basic sidesheet components (#47100)
- [ ] Question info sidesheet
- [ ] Question settings sidesheet
- [ ] Dashboard settings sidesheet
- [ ] Dashboard info sidesheet
```

**Comment by iethree** [comment] 2024-08-28 14:03
duplicate of https://github.com/metabase/metabase/issues/42527

**Closed by iethree** 2024-08-28 14:03 UTC
Labels: .Epic
