### ISSUE TITLE
Users with view access to a dashboard should have access to filter field values

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#26874] opened 2022-12-01 16:56 UTC
# Context
Product doc: [Users with view access to a dashboard should have access to filter field values](https://www.notion.so/metabase/Users-with-view-access-to-a-dashboard-should-have-access-to-filter-field-values-5590f7109fb4408a934b4ea1406a7e8a)

- This project depends on https://github.com/metabase/metabase/issues/26873
- There is previous work on https://github.com/metabase/metabase/pull/24832

# Requirements
- If a user has `view` collection access to a dashboard, they should have access to the dashboard filter field values (even if they have `no self-service` access to that db/schema/table).
  - If they have `sandboxed` access, we should respect the sandbox, as we do today.
  - If they have `block` they don't have access to the field values.

**Comment by camsaul** [comment] 2022-12-01 21:33
This looks like a duplicate of #15926

**Comment by luizarakaki** [comment] 2022-12-12 18:51
I believe this was settled in this [discussion](https://www.notion.so/metabase/Access-to-dashboard-field-values-for-restricted-users-6c898d26d2224cfc8bbf96489dbe4ba0)

So, we are making field values access consistent with collection permissions and creating an alternative for creators (define a custom list of values).

The custom list of values project is WIP in the app backend team: https://github.com/metabase/metabase/issues/26873

**Comment by noahmoss** [comment] 2023-03-01 16:34
Closing since https://github.com/metabase/metabase/pull/28581 is merged

**Closed by noahmoss** 2023-03-01 16:34 UTC
Labels: Reporting/Dashboards, Administration/Permissions, .Epic
