### ISSUE TITLE
how to Change the secondary y-axis label in multi series bar chart 

### ISSUE THREAD

**Issue by shyam2794** [metabase/metabase#5583] opened 2017-07-26 07:55 UTC
Unable to change the label for secondary y-axis the y-axis on the left needs to be volume and the right needs to be revenue, but changing the value in y-axis changes both the axes . 

![screenshot from 2017-07-26 13-55-47](https://user-images.githubusercontent.com/30238125/28611662-3106c7f0-720a-11e7-8691-4d15c5a933f3.png)

**Comment by mazameli** [comment] 2017-07-26 20:41
Seems like we should be showing an additional form field on this screen in the event that there is a second y-axis, with the label `Secondary y-axis label`.

**Comment by gukras** [comment] 2017-09-18 19:02
Yes, this is difficult with more than 2 fields there. I have reports with Sum 1 , Sum2, Sum 3, and its difficult to follow

**Comment by MarcGJA** [comment] 2018-04-07 16:07
Same problem, solution for the time being is to type into the single Y-axis label box "xyz (left) -- abc (right)" to let users know what's what; not pretty but gets it done...

**Comment by flamber** [comment] 2020-05-23 21:42
This is a duplicate of #3897

**Comment by flamber** [comment] 2021-08-02 10:47
Closing in favor of #3897

**Closed by flamber** 2021-08-02 10:47 UTC
Labels: Priority:P3, Type:Bug, Visualization/Chart Settings
