### ISSUE TITLE
Don't show View these X for databases that don't support raw data 

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5148] opened 2017-05-19 21:59 UTC
Basically Google Analytics

**Comment by mazameli** [comment] 2017-05-19 22:00
Related to or dupe of https://github.com/metabase/metabase/issues/5110

**Comment by mazameli** [comment] 2018-04-20 18:37
Forgot to close this as a dupe of #5110. This is still a thing, and is annoying.

**Closed by mazameli** 2018-04-20 18:37 UTC
Labels: Database/Google Analytics, Duplicate, Query Builder, UX
