### ISSUE TITLE
Trying to refresh a question you were denied access to causes app to crash

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5026] opened 2017-05-09 00:22 UTC
When turning off self-serve data permissions to a database, if I have a window open that has a query builder unsaved question against that database, and I refresh, it gives me a permission error. 

That's expected but what's not expected is that the app then ignores any further clicks on the nav bar.

<img width="1440" alt="screen shot 2017-05-08 at 5 22 07 pm" src="https://cloud.githubusercontent.com/assets/107439/25830617/e6af6ae8-3412-11e7-83cc-2588d9b63925.png">

**Comment by flamber** [comment] 2019-02-15 03:27
Hi @salsakran 
I cannot reproduce this in 0.31.2
I used incognito with a user, ran query in QB - then normal window with admin, I revoked permissions to the database - then with user I clicked "Refresh", which resulted in a nice:
![image](https://user-images.githubusercontent.com/1447303/52832630-00a11200-309f-11e9-9449-e1fd856651ef.png)
The browser console only had `Error: Object { status: 403 }` and interface is fully functional. Though, the database is still shown in QB selector until I browser-refresh, but that's another existing issue.

**Comment by mbvictoria** [comment] 2019-07-10 19:19
Closing - appears to be fixed in more recent versions.

**Closed by mbvictoria** 2019-07-10 19:19 UTC
Labels: Bug, Permissions, Priority/P3
