### ISSUE TITLE
Druid float/long type automatically treated as metric

### ISSUE THREAD

**Issue by dgregoire** [metabase/metabase#9900] opened 2019-05-07 03:26 UTC
If a data type in a druid schema is actually long or float

```
	      "dimensionsSpec" : {
	        "dimensions": [
	          { "name" : "userid", "type" : "long" },
```

it gets automatically treated as a metric, generating filtering errors
```
05-07 02:55:45 WARN druid.query-processor :: WARNING: Filtering only works on dimensions! 'userid' is a metric. Ignoring filter.
```

seems like this code makes that assumption

https://github.com/metabase/metabase/blob/d7c6d1f41e8bd6db3b418e6e92aba87466c2a868/modules/drivers/druid/src/metabase/driver/druid/query_processor.clj#L129

is there any work around to this?

**Comment by flamber** [comment] 2019-05-07 03:37
Hi @dgregoire This looks similar to #7300 - perhaps even duplicate of it?

**Comment by dgregoire** [comment] 2019-05-07 03:42
Yes it does - not a long of movement. Any suggestions?

**Comment by flamber** [comment] 2019-05-07 04:11
No, I don't know anything about Druid.
But if you think it's a duplicate, then please close this issue and :+1: the other issue.

**Closed** 2019-05-07 04:22 UTC
