### ISSUE TITLE
Unable to give secondary y axis a unique label when there are more than 2 metrics

### ISSUE THREAD

**Issue by jrhabu** [metabase/metabase#23776] opened 2022-07-07 21:43 UTC
**Describe the bug**
While using a combo chart with three metrics - two on the left/primary axis and 1 on the right/secondary axis, there is no option to assign unique labels to the primary axis and secondary axis. 

**Logs**
N/A

**To Reproduce**
1. Create a combo chart with 3 metrics
2. Assign 2 metrics to the left y axis and 1 metric to the right y axis
3. Navigate to Combo Options>Label
4. Toggle on y-axis label
5. Attempt to assign separate labels for left y axis and right y axis

**Expected behavior**
Two input boxes once you toggle on y-axis label. 1 input for the left axis and another for right axis

**Screenshots**
![Screen Shot 2022-07-07 at 5 37 00 PM](https://user-images.githubusercontent.com/85518832/177875717-044e2c03-3f89-4250-a83e-2359015a9930.png)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Some combo charts are visually confusing with no labels or overly verbose labels

**Additional context**

**Metabase Diagnostic Info**

**Comment by flamber** [comment] 2022-07-21 10:42
Duplicate of #3897

**Closed by flamber** 2022-07-21 10:42 UTC
Labels: Type:New Feature, .Correctness, Visualization/Charts
