### ISSUE TITLE
Feature Request: When doing "IS" queries while browsing tables, don't use separate different OR comparisons, use a single "IN" instead

### ISSUE THREAD

**Issue by nutsnox** [metabase/metabase#45900] opened 2024-07-21 06:37 UTC
**Is your feature request related to a problem? Please describe.**
I'm evaluating this product for potential deployment for my company and love it so far......

....but my server CPU is being blown out by inefficient queries when filtering on columns using "IS" filters on a MSSQL database. It will literally use 96 cores and take a whole minute or more to return a search on 1000 entries when doing an "IS" query. When running an "IN" query doing the exact same thing it returns instantaneously and uses little CPU.

End-Users are faced with super-slow filters when filtering on even moderate numbers of filter criteria.

**Describe the solution you'd like**
Use IN when doing "IS" queries (or change the word "IS" to "IN" since that's technically what you're doing). Something along the lines of "WHERE lower([value]) IN ( {{ comma-delimited-list }} )"

**Describe alternatives you've considered**
I am forced to make a parameterized question which removes the drill-through or filter capabilities. I just basically implement the above "IN" functionality and it returns instantaneously with little CPU utilization when filtering on 1,000 criteria.

**How important is this feature to you?**
This is (or should be) important to everyone, not just me. I believe that this is bordering on a bug.

**Additional context**
This is using Microsoft SQL Server (I imagine this is true on other DBMS and equally slow) and I looked at the query monitor when filtering a column on 1,000 different strings using an "IS" filter. I then found a mountain of this in the resultant query text:

OR (LOWER("dbo"."exampletable"."FieldToISQuery") =  '123456788' ) OR (LOWER("dbo"."exampletable"."FieldToISQuery") =  '123456789' )

^ this is massively inefficient and blows out CPU utilization. The correct way to do this would be WHERE lower("dbo"."exampletable"."FieldToISQuery") IN ('123456788','123456789')

I'm assuming the string text that users input is LOWER() prior to search. This should work on all DBMS.

Thank You.

**Comment by paoliniluis** [comment] 2024-07-24 12:55
duplicate of https://github.com/metabase/metabase/issues/23101

**Closed by paoliniluis** 2024-07-24 12:55 UTC
Labels: Type:New Feature, .Needs Triage
