### ISSUE TITLE
Prevent language auto-detection by browser

### ISSUE THREAD

**Issue by wxiaoguang** [metabase/metabase#9340] opened 2019-01-29 17:33 UTC
Is it possible to prevent the language auto-detection?

Reasons:

1. Many developers may set the browser's language for other purpose during development, which may not be suitable for daily use.

2. Some translations are missing or difficult to understand. English is very clear and accurate.

3. When do bug report, English screenshot is more clear.

If there is a chance to let users decide which language they want, it will be cool.

**Comment by flamber** [comment] 2019-01-29 18:14
Duplicate of #8384 
If you use a reverse-proxy, then you can force language by setting the `Accept-Language` header.

**Comment by wxiaoguang** [comment] 2019-01-30 01:33
`proxy_set_header Accept-Language en_US;`

It saves my time, thanks!!

**Comment by flamber** [comment] 2019-01-30 01:39
@wxiaoguang 
Great. Please close this issue.

**Closed** 2019-01-30 02:21 UTC
