### ISSUE TITLE
Native Question Field Filter not working properly in 0.33.4 and 0.33.5 (tested on Postgres)

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#11313] opened 2019-11-13 18:26 UTC
When there are multiple statements in the WHERE clause (e.g. `WHERE a =1 AND b = 2`) and one of them is a variable (`[[ WHERE {{a}} AND b = 2 ]]`), the `WHERE` clause gets applied only if all filters have values chosen for them.

**To Reproduce**
```
create table test (x varchar(100), y varchar(100), z int)

insert into test values ('a1', 'b1', 1), ('a2', 'b2', 2), ('a3', 'b3', 3), ('a4', 'b4', 4)
```
Create a native question:
```
select *
from test
[[ where {{x}}
and {{y}}
and z = 2
]]
```
This shows all rows (the `z=2` doesn't get applied):

![b1](https://user-images.githubusercontent.com/15974735/68791801-e16bec80-05fe-11ea-8027-bd5a0b8210d5.png)

Choosing a value for one of the filter still shows all rows:

![b2](https://user-images.githubusercontent.com/15974735/68791812-e630a080-05fe-11ea-8aee-dfcc855212e6.png)

It works as expected only when we choose values for all filters:

![b3](https://user-images.githubusercontent.com/15974735/68791892-18420280-05ff-11ea-9bc3-03fa0e8a2b94.png)

- Metabase version: (0.33.4 and 0.33.5)
- **Severity**: Impacts all native questions that have conjunctive WHERE clauses with Field Filters
- Tested on Postgres 11.4. Not sure if other RDBMS's are impacted.

**Comment by flamber** [comment] 2019-11-13 19:01
@vvaezian This is caused by the total rewrite of how parameters are substituted in #10947 (0.33.4+), which finally fixed the use of [Complex Default Value](https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#default-value-in-the-query).
But the correct way would be to do something like this:
```
select *
from test
where 1=1
[[and {{x}} and z = 2]]
[[and {{y}} and z = 2]]
```

**Comment by vvaezian** [comment] 2019-11-13 19:27
I thought patch releases do not change the behavior of the app and only fix bugs.

**Comment by flamber** [comment] 2019-11-13 19:35
@vvaezian Yes, that's generally the norm, but it fixed complex default value - and having multiple multiple variables in [Optional Clauses](https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#optional-clauses) has never been supported officially as far as I know.
The workaround (and possibly the correct way) would be to have multiple Optional Clauses.

**Comment by mazameli** [comment] 2019-11-15 20:47
Would it be possible to rewrite your query like this?

```
select *
from test
where z = 2
[[ and {{x}} ]]
[[ and {{y}} ]]
```

**Comment by vvaezian** [comment] 2019-11-15 23:50
@mazameli Sure. I was just not expecting things that were working before, break after upgrade, given that this was a patch release.
I believe it would be nice if the policy for backward-compatibility is clearly stated. E.g. minor (third-level) increments (x.y.z to x.y.z+1) are backward-compatible but 2nd-level upgrades (x.y to x.y+1) are not necessarily backward-compatible, etc.

**Comment by flamber** [comment] 2021-11-14 10:31
Closing in favor of #13148

**Closed by flamber** 2021-11-14 10:31 UTC
Labels: Type:UX, Priority:P3, Querying/Native
