### ISSUE TITLE
sortBy in CardRenderer overwrites ORDER BY from query

### ISSUE THREAD

**Issue by jerser** [metabase/metabase#2609] opened 2016-05-16 14:01 UTC
I'm running Metabase (from JAR), version 0.17.1.

The labels on the x axis no longer respect the order they have in the query result.

I checked the dataset coming back from the server and the data is (as expected) correctly sorted there. Then looking at the Metabase source I noticed the [sortBy](https://github.com/metabase/metabase/blob/57ef8a8eb42464b800e3e392e329e6adbd1271bb/frontend/src/visualizations/lib/CardRenderer.js#L464) in CardRenderer.
It seems like this is a change coming from this [commit]( https://github.com/metabase/metabase/commit/4c1ba6b0709e76ae986a1506a142cfb8b8d4dcb5
).

I'm not sure what the proper solution is, I understand why the sortBy is done. However there is no way now to influence this except prepending the labels so that they come out in the right order after sortBy.

**Comment by tlrobinson** [comment] 2016-05-16 17:02
Duplicate of #2085

**Closed by tlrobinson** 2016-05-16 17:02 UTC
