### ISSUE TITLE
The points of the map are not shown on the dashboard sharing link (when the points exceed 1000)

### ISSUE THREAD

**Issue by osiastossou** [metabase/metabase#18992] opened 2021-11-15 16:01 UTC
**Describe the bug**
The points of the map are not shown on the dashboard sharing link (when the points exceed 1000)

**Logs**
No log

**To Reproduce**
1. Go to metabase
2. Create map with points more than 1000 (me I have more than 15000 points)
3. Add the map to dashboard
4. Make public the dashboard
5. Go to the public link of dashboard
4. See error (No point in the public dashboard)

**Screenshots**
Before sharing in the metabase application
![Capture](https://user-images.githubusercontent.com/20375424/141812996-4bde3bb7-1ff9-414b-be42-15ac3ec1f149.PNG)

After sharing (on the public sharing link)
![Capture1](https://user-images.githubusercontent.com/20375424/141813059-9a521df5-0c2c-4c5e-acd5-1a8cff0547c3.PNG)

**Information about your Metabase Installation:**

- Browser and the version: Chrome Version 95.0.4638.69 (Build officiel)
- Databases: MongoDB
- Metabase version: 0.41.2
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

**Comment by flamber** [comment] 2021-11-15 16:12
Duplicate of #9420

**Closed by flamber** 2021-11-15 16:12 UTC
Labels: Type:Bug, .Needs Triage
