### ISSUE TITLE
Postgres native query using JSON operators fails

### ISSUE THREAD

**Issue by nskalis** [metabase/metabase#14680] opened 2021-02-05 18:49 UTC
**Describe the bug**

When I issue a query using the official postgresql client (`psql`), it works. 
When  I issue the same query using the native query functionality in metabase, it fails.

The query in question is:
```
SELECT  "ip"."aws_inet"."pulse"
FROM    "ip"."aws_inet"
WHERE   "ip"."aws_inet"."service" = 'S3' 
AND     "ip"."aws_inet"."is_ok" IS true
AND     "ip"."aws_inet"."metadata" ->> 'region' = 'eu-central-1'
AND     "ip"."aws_inet"."pulse" ?| ARRAY['nl-ams09c-ri1','uk-lon01b-ri1'] ;
```

`metabase` complains about
```
No value specified for parameter 1.
```

Note: `?|` in this query is a special Postgres operator for JSON types; see [here](https://www.postgresql.org/docs/9.5/functions-json.html).

**Logs**

```
[65692d92-b09a-4f09-82af-4a1a7c8620b7] 2021-02-05T19:34:01+01:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: null
{:database_id 9,
 :started_at #t "2021-02-05T19:34:00.379+01:00[Europe/Amsterdam]",
 :state "22023",
 :json_query
 {:type "native",
  :native
  {:query
   "SELECT  \"ip\".\"aws_inet\".\"pulse\"\nFROM    \"ip\".\"aws_inet\"\nWHERE   \"ip\".\"aws_inet\".\"service\" = 'S3' \nAND     \"ip\".\"aws_inet\".\"is_ok\" IS true\nAND     \"ip\".\"aws_inet\".\"metadata\" ->> 'region' = 'eu-central-1'\nAND     \"ip\".\"aws_inet\".\"pulse\" ?| ARRAY['nl-ams09c-ri1','uk-lon01b-ri1'] ;",
   :template-tags {}},
  :database 9,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :status :failed,
 :class org.postgresql.util.PSQLException,
 :stacktrace
 ["org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:264)"
  "org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:294)"
  "org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)"
  "org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)"
  "org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)"
  "org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)"
  "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)"
  "--> driver.sql_jdbc.execute$fn__76636.invokeStatic(execute.clj:266)"
  "driver.sql_jdbc.execute$fn__76636.invoke(execute.clj:264)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:391)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:376)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:385)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:376)"
  "driver.sql_jdbc$fn__78141.invokeStatic(sql_jdbc.clj:49)"
  "driver.sql_jdbc$fn__78141.invoke(sql_jdbc.clj:47)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
  "query_processor.context.default$default_runf.invoke(default.clj:67)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47457.invoke(mbql_to_native.clj:26)"
  "query_processor.middleware.check_features$check_features$fn__46732.invoke(check_features.clj:42)"
  "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__47622.invoke(optimize_datetime_filters.clj:133)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__45533.invoke(auto_parse_filter_values.clj:44)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__49188.invoke(wrap_value_literals.clj:149)"
  "query_processor.middleware.annotate$add_column_info$fn__45295.invoke(annotate.clj:575)"
  "query_processor.middleware.permissions$check_query_permissions$fn__46607.invoke(permissions.clj:70)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__48140.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46805.invoke(cumulative_aggregations.clj:61)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__48377.invoke(resolve_joined_fields.clj:36)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__48696.invoke(resolve_joins.clj:183)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__41020.invoke(add_implicit_joins.clj:254)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__47418.invoke(large_int_id.clj:44)"
  "query_processor.middleware.limit$limit$fn__47443.invoke(limit.clj:38)"
  "query_processor.middleware.format_rows$format_rows$fn__47398.invoke(format_rows.clj:84)"
  "query_processor.middleware.desugar$desugar$fn__46871.invoke(desugar.clj:22)"
  "query_processor.middleware.binning$update_binning_strategy$fn__45892.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__46409.invoke(resolve_fields.clj:24)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__40564.invoke(add_dimension_projections.clj:316)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__40771.invoke(add_implicit_clauses.clj:141)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__41169.invoke(add_source_metadata.clj:105)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__48337.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45480.invoke(auto_bucket_datetimes.clj:125)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46456.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48122.invoke(parameters.clj:114)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46508.invoke(resolve_referenced.clj:80)"
  "query_processor.middleware.expand_macros$expand_macros$fn__47127.invoke(expand_macros.clj:158)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__41200.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49058.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48348$fn__48352.invoke(resolve_database_and_driver.clj:33)"
  "driver$do_with_driver.invokeStatic(driver.clj:61)"
  "driver$do_with_driver.invoke(driver.clj:57)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48348.invoke(resolve_database_and_driver.clj:27)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47345.invoke(fetch_source_query.clj:267)"
  "query_processor.middleware.store$initialize_store$fn__49067$fn__49068.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__49067.invoke(store.clj:10)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__46385.invoke(cache.clj:214)"
  "query_processor.middleware.validate$validate_query$fn__49076.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__47470.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__41038.invoke(add_rows_truncated.clj:36)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49043.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__46748.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__48211.invoke(process_userland_query.clj:136)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46691.invoke(catch_exceptions.clj:174)"
  "query_processor.reducible$async_qp$qp_STAR___39827$thunk__39828.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___39827.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___39836$fn__39839.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___39836.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:237)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:233)"
  "query_processor$fn__49234$process_query_and_save_execution_BANG___49243$fn__49246.invoke(query_processor.clj:249)"
  "query_processor$fn__49234$process_query_and_save_execution_BANG___49243.invoke(query_processor.clj:241)"
  "query_processor$fn__49278$process_query_and_save_with_max_results_constraints_BANG___49287$fn__49290.invoke(query_processor.clj:261)"
  "query_processor$fn__49278$process_query_and_save_with_max_results_constraints_BANG___49287.invoke(query_processor.clj:254)"
  "api.dataset$fn__52603$fn__52606.invoke(dataset.clj:59)"
  "query_processor.streaming$streaming_response_STAR_$fn__37131$fn__37132.invoke(streaming.clj:73)"
  "query_processor.streaming$streaming_response_STAR_$fn__37131.invoke(streaming.clj:72)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
  "async.streaming_response$do_f_async$fn__24639.invoke(streaming_response.clj:85)"],
 :context :ad-hoc,
 :error "No value specified for parameter 1.",
 :row_count 0,
 :running_time 0,
 :data {:rows [], :cols []}}
```

**To Reproduce**
See https://dba.stackexchange.com/questions/284325/check-if-a-list-of-strings-in-a-jsonb-contains-or-not-an-array-of-strings

**Expected behavior**
In `psql`(https://www.postgresql.org/docs/12/app-psql.html), the above query returns
```
                        pulse                        
-----------------------------------------------------
 ["de-fra02a-ri1", "nl-ams09c-ri1", "uk-lon01b-ri1"]
 ["de-fra02a-ri1", "nl-ams09c-ri1", "uk-lon01b-ri1"]
 ["de-fra02a-ri1", "nl-ams09c-ri1", "uk-lon01b-ri1"]
 ["de-fra02a-ri1", "nl-ams09c-ri1", "uk-lon01b-ri1"]
 ["de-fra02a-ri1", "nl-ams09c-ri1", "uk-lon01b-ri1"]
 ["de-fra02a-ri1", "nl-ams09c-ri1", "uk-lon01b-ri1"]
 ["de-fra02a-ri1", "nl-ams09c-ri1", "uk-lon01b-ri1"]
 ["de-fra02a-ri1", "nl-ams09c-ri1", "uk-lon01b-ri1"]
 ["de-fra02a-ri1", "nl-ams09c-ri1", "uk-lon01b-ri1"]
 ["de-fra02a-ri1", "nl-ams09c-ri1", "uk-lon01b-ri1"]
 ["de-fra02a-ri1", "nl-ams09c-ri1", "uk-lon01b-ri1"]
(11 rows)
```

**Information about your Metabase Installation:**

- Your browser and the version: Safari Version 14.0.3 (15610.4.3.1.6, 15610)
- Your operating system: CentOS Linux release 7.9.2009 (Core)
- Your databases: PostgreSQL 12.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
- Metabase version: v0.37.3
- Metabase hosting environment: Jar-file
- Metabase internal database: Postgres

**Severity**
The purpose of this query is to participate in a metabase pulse that will notify a team to trigger a ci/cd job for a config rollout in the core network.

**Comment by jeff303** [comment] 2021-02-05 18:53
@nskalis , I think you need to use this syntax for parameters in native queries: https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html

**Comment by nskalis** [comment] 2021-02-05 18:55
Thanks @jeff303 for looking into it. I am not sure if I am get this right. I don't make use of any input parameters in metabase. It is about a hard-coded query.

**Comment by jeff303** [comment] 2021-02-05 18:58
The `?` syntax is how you indicate a parameter in parameterized SQL (not talking about Metabase, yet).  So whoever gave you that query is expecting you to supply a parameter value when executing.  The way you designate and supply the parameter value in Metabase is different, even with native queries, and hence you need to use that syntax.

**Comment by nskalis** [comment] 2021-02-05 19:04
Please see table 9-41 https://www.postgresql.org/docs/9.5/functions-json.html
`?|` is an operator on `jsonb` columns.

**Comment by jeff303** [comment] 2021-02-05 19:07
Ah, I see.  Thanks for the clarification.  In that case, it will have to be triaged to figure out why it's complaining about it (as if it was a parameter) instead of being the operator.

**Comment by flamber** [comment] 2021-02-06 09:15
Duplicate of #1964

**Closed by flamber** 2021-02-06 09:15 UTC
Labels: .Backend, .Needs Triage, Database/Postgres, Querying/Native, Type:Bug
