### ISSUE TITLE
Running an embedded question will dump a stack trace with exception

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#31098] opened 2023-05-26 19:35 UTC
### Describe the bug

This will fill the logs very very fast:

When going to a embedded Metabase and running a question, the folling ST will get dumped:
```
2023-05-26 19:29:53,109 WARN events.view-log :: Failed to process activity event. :card-query #error {
 :cause Site-wide values are not allowed for Setting :user-recent-views
 :data {:setting :user-recent-views}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message Site-wide values are not allowed for Setting :user-recent-views
   :data {:setting :user-recent-views}
   :at [metabase.models.setting$fn__45120$set_value_of_type_BANG___45111__45125$fn__45126 invoke setting.clj 636]}]
 :trace
 [[metabase.models.setting$fn__45120$set_value_of_type_BANG___45111__45125$fn__45126 invoke setting.clj 636]
  [metabase.models.setting$fn__45120$set_value_of_type_BANG___45111__45125 invoke setting.clj 613]
  [clojure.lang.MultiFn invoke MultiFn.java 239]
  [metabase.models.setting$fn__45158 invokeStatic setting.clj 700]
  [metabase.models.setting$fn__45158 invoke setting.clj 698]
  [clojure.lang.MultiFn invoke MultiFn.java 239]
  [metabase.events.view_log$fn__97955$fn__97956 invoke view_log.clj 106]
  [metabase.models.setting$get invokeStatic setting.clj 566]
  [metabase.models.setting$get invoke setting.clj 557]
  [metabase.models.setting$setting_fn$setting_getter_STAR___45190 invoke setting.clj 846]
  [metabase.events.view_log$update_users_recent_views_BANG_$fn__97971 invoke view_log.clj 142]
  [metabase.server.middleware.session$do_with_current_user invokeStatic session.clj 315]
  [metabase.server.middleware.session$do_with_current_user invoke session.clj 304]
  [metabase.events.view_log$update_users_recent_views_BANG_ invokeStatic view_log.clj 139]
  [metabase.events.view_log$update_users_recent_views_BANG_ invoke view_log.clj 137]
  [metabase.events.view_log$handle_view_event_BANG_ invokeStatic view_log.clj 160]
  [metabase.events.view_log$handle_view_event_BANG_ invoke view_log.clj 148]
  [metabase.events$start_event_listener_BANG_$fn__55571$state_machine__34146__auto____55578$fn__55581 invoke events.clj 101]
  [metabase.events$start_event_listener_BANG_$fn__55571$state_machine__34146__auto____55578 invoke events.clj 101]
  [clojure.core.async.impl.runtime$run_state_machine invokeStatic runtime.clj 62]
  [clojure.core.async.impl.runtime$run_state_machine invoke runtime.clj 61]
  [clojure.core.async.impl.runtime$run_state_machine_wrapped invokeStatic runtime.clj 66]
  [clojure.core.async.impl.runtime$run_state_machine_wrapped invoke runtime.clj 64]
  [clojure.core.async.impl.runtime$take_BANG_$fn__30339 invoke runtime.clj 75]
  [clojure.core.async.impl.channels.ManyToManyChannel$fn__30181 invoke channels.clj 140]
  [clojure.lang.AFn run AFn.java 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker nil -1]
  [java.util.concurrent.ThreadPoolExecutor$Worker run nil -1]
  [clojure.core.async.impl.concurrent$counted_thread_factory$reify__30068$fn__30069 invoke concurrent.clj 29]
  [clojure.lang.AFn run AFn.java 22]
  [java.lang.Thread run nil -1]]}
2023-05-26 19:29:53,112 WARN events.view-log :: Failed to process activity event. :card-query #error {
 :cause Site-wide values are not allowed for Setting :user-recent-views
 :data {:setting :user-recent-views}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message Site-wide values are not allowed for Setting :user-recent-views
   :data {:setting :user-recent-views}
   :at [metabase.models.setting$fn__45120$set_value_of_type_BANG___45111__45125$fn__45126 invoke setting.clj 636]}]
 :trace
 [[metabase.models.setting$fn__45120$set_value_of_type_BANG___45111__45125$fn__45126 invoke setting.clj 636]
  [metabase.models.setting$fn__45120$set_value_of_type_BANG___45111__45125 invoke setting.clj 613]
  [clojure.lang.MultiFn invoke MultiFn.java 239]
  [metabase.models.setting$fn__45158 invokeStatic setting.clj 700]
  [metabase.models.setting$fn__45158 invoke setting.clj 698]
  [clojure.lang.MultiFn invoke MultiFn.java 239]
  [metabase.events.view_log$fn__97955$fn__97956 invoke view_log.clj 106]
  [metabase.models.setting$get invokeStatic setting.clj 566]
  [metabase.models.setting$get invoke setting.clj 557]
  [metabase.models.setting$setting_fn$setting_getter_STAR___45190 invoke setting.clj 846]
  [metabase.events.view_log$update_users_recent_views_BANG_$fn__97971 invoke view_log.clj 142]
  [metabase.server.middleware.session$do_with_current_user invokeStatic session.clj 315]
  [metabase.server.middleware.session$do_with_current_user invoke session.clj 304]
  [metabase.events.view_log$update_users_recent_views_BANG_ invokeStatic view_log.clj 139]
  [metabase.events.view_log$update_users_recent_views_BANG_ invoke view_log.clj 137]
  [metabase.events.view_log$handle_view_event_BANG_ invokeStatic view_log.clj 160]
  [metabase.events.view_log$handle_view_event_BANG_ invoke view_log.clj 148]
  [metabase.events$start_event_listener_BANG_$fn__55571$state_machine__34146__auto____55578$fn__55581 invoke events.clj 101]
  [metabase.events$start_event_listener_BANG_$fn__55571$state_machine__34146__auto____55578 invoke events.clj 101]
  [clojure.core.async.impl.runtime$run_state_machine invokeStatic runtime.clj 62]
  [clojure.core.async.impl.runtime$run_state_machine invoke runtime.clj 61]
  [clojure.core.async.impl.runtime$run_state_machine_wrapped invokeStatic runtime.clj 66]
  [clojure.core.async.impl.runtime$run_state_machine_wrapped invoke runtime.clj 64]
  [clojure.core.async.impl.runtime$take_BANG_$fn__30339 invoke runtime.clj 75]
  [clojure.core.async.impl.channels.ManyToManyChannel$fn__30181 invoke channels.clj 140]
  [clojure.lang.AFn run AFn.java 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker nil -1]
  [java.util.concurrent.ThreadPoolExecutor$Worker run nil -1]
  [clojure.core.async.impl.concurrent$counted_thread_factory$reify__30068$fn__30069 invoke concurrent.clj 29]
  [clojure.lang.AFn run AFn.java 22]
  [java.lang.Thread run nil -1]]}
```

### To Reproduce

1) Clone https://github.com/metabase/embedding-reference-apps
2) run it with 46.4
3) open the embedding page, see the errors

### Expected behavior

No exceptions?

### Logs

Above

### Information about your Metabase installation

```JSON
v1.46.4, only with embeddings
```

### Severity

P1?

**Comment by calherries** [comment] 2023-06-06 09:01
@paoliniluis I couldn't reproduce this with the steps given above. Can you check I'm not missing something? Loom here: https://www.loom.com/share/71824f671a7043768a9d93ea1720ae41

**Comment by calherries** [comment] 2023-06-12 09:59
This was fixed by https://github.com/metabase/metabase/issues/31103 two weeks ago

**Comment by NevRA** [comment] 2023-06-14 07:00
@paoliniluis can you close it? Please check Cal's comment above

**Comment by calherries** [comment] 2023-06-14 07:48
I think I'm at liberty to close this

**Closed by calherries** 2023-06-14 07:48 UTC
Labels: Type:Bug, Priority:P1, .Backend, Embedding/Signed, .Team/42 :milky_way:
