### ISSUE TITLE
[BUG] Question working but e-mail Pulse mixing line dots

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#9207] opened 2019-01-03 18:54 UTC
### Bug Question working but e-mail Pulse mixing line dots

- Your browser and the version: Chrome
- Your operating system: Ubuntu
- Your databases: MySQL, Postgres, MongoDB, SQL Server
- Metabase version: **v0.31.1**
- Metabase hosting environment: Linux/Debian 9
- Metabase internal database: Postgres

Look how we are receiving the Pulse by e-mail:
![screenshot from 2019-01-03 16-49-01](https://user-images.githubusercontent.com/6808348/50655682-040d8d80-0f78-11e9-844f-bfa5cd0ab897.png)

**Comment by salsakran** [comment] 2019-01-03 23:32
What is the output of that question, and what are the types of each column?

This can happen if you are spitting out strings instead of date or datetimes.

**Comment by flamber** [comment] 2019-02-24 22:02
Hi @dannyeuu 
This looks like a duplicate of #5628

**Closed** 2020-05-25 20:08 UTC
Labels: Priority:P3, Reporting/Pulses, Type:Bug
