### ISSUE TITLE
Front end displaying a wrong number for BIGINT

### ISSUE THREAD

**Issue by alrevuelta** [metabase/metabase#27882] opened 2023-01-25 22:30 UTC
**Describe the bug**
Seems oddly specific, my postgres database contains a `BIGINT` field with the following value: `26365685914635112`. However, the metabase frontend displays `26365685914635110`.

**Logs**

**To Reproduce**

* Create one table in a postgres database `my_table`
* Store the value `26365685914635112` as a `BIGINT` field in a given table, as field `my_field`
* Connecet metabase to that postgres database
* Write a query in metabase, `select * from my_table`
* Observe that the front end displays a different value `26365685914635110` instead.

**Expected behavior**
The value `26365685914635112` should be displayed.

**Screenshots**
Left metabase, right db visualizer. Same table, same field, **but different value!!**

![image](https://user-images.githubusercontent.com/8811422/214705916-91fff8c7-b53c-4898-8748-66bf1e1fbb11.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

Using metabase witg docker:

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.17+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.17",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.17+8",
    "os.name": "Linux",
    "os.version": "5.15.0-56-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-12-07",
      "tag": "v0.45.1",
      "branch": "release-x.45.x",
      "hash": "019d31c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
High, wrong data is displayed in the frontend.

**Comment by paoliniluis** [comment] 2023-01-26 17:37
duplicate of https://github.com/metabase/metabase/issues/5816

**Closed by paoliniluis** 2023-01-26 17:37 UTC
Labels: Type:Bug, .Needs Triage
