### ISSUE TITLE
Lineage of nested questions results in strange save behavior

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#7032] opened 2018-02-27 20:54 UTC
If I start a nested question (eg , from a SQL question), and save the result, the save modal defaults to asking me if I want to overwrite the original question. 

This seems odd. On one hand, it's useful to maintain that "based on Blah". On the other hand, it's seems really odd to overwrite question X with a question based on a it. If I actually click `save` and overwrite it, the resulting question is meaningless and can't be run any longer.

**Comment by flamber** [comment] 2019-02-18 21:47
Hi @salsakran 
I cannot reproduce this issue on 0.31.2 - or maybe I'm misunderstanding the issue?
1. Created a SQL question called "Nested SQL".
2. Create a Custom based on "Nested SQL" and click Save.
3. Gives me the normal "save as new" dialog, not "overwrite original"
![image](https://user-images.githubusercontent.com/1447303/52977824-5b36b880-3394-11e9-9b1e-74127adc6962.png)

**Comment by flamber** [comment] 2020-03-13 20:39
Closing, since this was likely fixed shortly after the report

**Closed** 2020-07-29 13:06 UTC
Labels: Priority:P2, Querying/Nested Queries, Type:Bug, Type:UX
