### ISSUE TITLE
Add heatmap to map widget

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#4670] opened 2017-04-03 10:35 UTC
In the current map when I add a map or when use the default map, it always use `pin` to refer to a location.

I need a map like below:
![screen shot 2017-04-03 at 3 06 14 pm](https://cloud.githubusercontent.com/assets/6417083/24605719/33aae714-187f-11e7-9376-2d376ca0f719.png)

Is it possible to add a heatmap or even adding a custom icon rather than `pin` symbol to map? For the current time I couldn't find a way in map setting that I could change the symbol.

**Comment by mazameli** [comment] 2017-04-03 16:33
Closing as a duplicate of #3206. Please feel free to add your support to that issue via a 👍  reaction.

**Closed by mazameli** 2017-04-03 16:33 UTC
Labels: Duplicate
