### ISSUE TITLE
Flexible Alerts

### ISSUE THREAD

**Issue by JStezy** [metabase/metabase#14042] opened 2020-12-10 22:50 UTC
**Is your feature request related to a problem? Please describe.**
We often use Metabase for operational alerts such as the creation of a rare task or thresholds crossed on KPIs for account management. In most cases we have to recreate the same alert/pulse 10+ times changing one small condition in the where clause (like "customer") and changing the recipient (e.g. which account owner email/slack channel to send it to). 

**Describe the solution you'd like**
I would like to be able to define conditions in the WHERE clause based on the recipient of an alert and/or pulse.

**Describe alternatives you've considered**
The only other solution I've thought of is if we could utilize parameters in pulse definitions then we could write one metabase question and then just have to duplicate the pulses themselves. It would be a small improvement over the current workflow. 

**How important is this feature to you?**
I build around 25 alerts/pulses per month but often times there are only 2-3 unique use cases. This would save me alone at least a full work day of tedious copy and pasting each month as well as massively reduce code drift (though snippets have helped with the latter problem). 

**Additional context**
As an example we have 13 operational pods each with their own channels and I needed to send them an alert when this certain rare event occurred that pertained to their pod. The SQL logic was identical except the customer in the WHERE clause which was determined by the recipient. So I had to make 13 metabase questions and set up alerts on each of them.

**Comment by flamber** [comment] 2020-12-10 23:06
Hi @JStezy Unless I'm misunderstanding, it sounds like a duplicate of #5771/#5770

**Comment by JStezy** [comment] 2020-12-10 23:23
Hey @flamber - it is similar, sorry I missed that one. 

It sounds like #5771/#5770 is suggesting that we still have many pulses (one for each recipient) but they can be configured without having to go in and edit the query by allowing you to access the parameters / filters in the pulse definition. 

I think this is the _alternative_ solution I'm proposing here. 

The key difference is that I am proposing there be one singular pulse where the recipient is utilized as a parameter in the query. Would you prefer I leave separate or consolidate this suggestion into that ticket?

**Comment by flamber** [comment] 2020-12-11 10:31
@JStezy Okay, so that sounds like it's almost what Sandboxes does, where the recipient only receives results they have access to.
It's part of the Enterprise Edition: https://www.metabase.com/docs/latest/enterprise-guide/data-sandboxes.html

**Comment by JStezy** [comment] 2020-12-11 17:57
Yes, it is similar for sure! 
In my use case I am wanting filtered reports to go to specific recipients but I still want those recipients to be able to access other recipients' data in Metabase more generally. 

I think I'm fine with archiving this and backing the horse on #5771/#5770 
It would be awesome if I could triage reports to different recipients using variables in the pulse definition and do it all from one pulse. Is that what that feature request is suggesting? I'm a little unclear if you would have to make, say, 3 pulses all using one query but you can filter the query in each pulse definition or  if you would only need one pulse where the reports are filtered and triaged within that single pulse definition. I'd prefer the latter but even the former would be awesome!

**Comment by flamber** [comment] 2020-12-11 18:20
@JStezy It basically sounds like you are looking for a mix of multiple things - including #12091.
I'm going to close this, since until some of the other requests have been addressed, then it's difficult to see how this should be implemented.

**Closed by flamber** 2020-12-11 18:20 UTC
Labels: .Needs Triage, Type:New Feature
