### ISSUE TITLE
Dashboard filter with small-width 

### ISSUE THREAD

**Issue by SrMouraSilva** [metabase/metabase#10238] opened 2019-06-21 13:47 UTC
**Describe the bug**

In the filter pop-up field, the filter type combobox is not displayed because of the maximum size limitation applied in html.

![image](https://user-images.githubusercontent.com/5341804/59926585-fb6b1f80-9410-11e9-8416-4ef6bab474c0.png)

**Logs**

No necessary

**To Reproduce**

1. Create a new question
2. Add a filter with relative big width

**Expected behavior**

No max-width in:
```
#FilterPopover > div {
    min-width: 300px; max-width: 500px
}
```

![image](https://user-images.githubusercontent.com/5341804/59926763-5d2b8980-9411-11e9-9c9d-8104d48acb2b.png)

Or a horizontal bar, or the filter combobox above...

**Information about your Metabase Installation:**

- Browser: Firefox 67.0.2 (64-bits) for Ubuntu
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- database: Postgres
- Metabase version: Current lastest 0.32.somerhing
- Metabase hosting environment: Docker
- Metabase internal database: Postgres with docker

**Severity**

The problem does not affect me because I know that I can modify the CSS of the page at hand, but the tool becomes ineffective for users without this profile, so I could not make it available as a BI tool for other users.

**Comment by flamber** [comment] 2019-06-21 14:18
Hi @SrMouraSilva 
This is a duplicate of #9616 - please close this issue and go and upvote by clicking :+1: on the first post.

**Comment by mazameli** [comment] 2019-06-21 16:27
Closing as dupe of #9616

**Closed by mazameli** 2019-06-21 16:27 UTC
Labels: Bug, Duplicate
