### ISSUE TITLE
Bad page title on question load

### ISSUE THREAD

**Issue by TLazarevic** [metabase/metabase#40894] opened 2024-04-02 12:06 UTC
### Describe the bug

While a dashboard is loading, the page browser tab title displays odd lambda values 

<img width="84" alt="Screenshot 2024-04-02 at 14 02 21" src="https://github.com/metabase/metabase/assets/18078190/ba5e41d0-9bb5-479f-a2f9-9c039415fc3f">

### To Reproduce

1. Go to a slow loading dashboard question
2. Inspect the title in the tab name
3. See error

### Expected behavior

Human readable title should be displayed

### Information about your Metabase installation

```JSON
- v0.49.1
```

### Severity

Not severe in any way

**Comment by uladzimirdev** [comment] 2024-04-02 12:07
duplicate of https://github.com/metabase/metabase/issues/40051

**Comment by uladzimirdev** [comment] 2024-04-02 12:08
@TLazarevic thanks for reporting, we're working on it

**Closed by uladzimirdev** 2024-04-02 12:07 UTC
Labels: Type:Bug, .Needs Triage
