### ISSUE TITLE
Column Ordering

### ISSUE THREAD

**Issue by thekantian** [metabase/metabase#2821] opened 2016-06-23 16:13 UTC
If this is a bug report, please fill in the blanks:

*  I am using the chrome browser.
*  My computer's OS is Mac OS.
*  I'm running Metabase 0.18.0. on Google Container Engine via a docker container
*  My database is BigQuery.
*  My Metabase version is 0.18.0

We're seeing column ordering change in the returned results from 0.17.1 to 0.18.0 - now it seems that columns are returned in ABC order instead of as specified by the query.

I'm going to attempt a downgrade until we have more of an idea of exactly what's up, but wanted to add that info here in case it helps.

**Comment by tlrobinson** [comment] 2016-06-23 21:40
Likely due to #2733

Related to #2819

**Comment by tlrobinson** [comment] 2016-06-23 22:18
@thekantian I think I know what's happening. Does this only occur when you're trying to sort by something other than the breakout (i.e. the aggregation or something else, if you're using SQL)?

i.e. "count of rows by category, order by count" ends up ordering by category instead of count, but "count of rows by category, order by category" orders correctly (both ascending and descending)?

**Comment by thekantian** [comment] 2016-06-23 22:23
Hey @tlrobinson thanks for digging here. I'm talking about the ordering of the columns in our results, not the ordering of rows - so in a query like `select pc_count, apple_count from table_one` I'd expect the results to come back with pc_count as column number 1, and in 0.17.1 it was, but now we're getting ABC order on the columns returned, it seems.

**Comment by tlrobinson** [comment] 2016-06-23 22:35
Oh sorry, totally spaced and interpreted "columns" as "rows". Disregard everything I said.

I haven't been able to reproduce this with simple queries like `SELECT email, address, city, name FROM people;`:

<img width="843" alt="screenshot 2016-06-23 15 34 17" src="https://cloud.githubusercontent.com/assets/18193/16322444/fdf035b8-3957-11e6-9944-efef4653c281.png">

What type of database are you querying?

@camsaul Any idea what might be going on?

**Comment by thekantian** [comment] 2016-06-23 22:56
Understood. We're using bigquery. On mobile but will provide a more detailed example tomorrow. The biggest impact here is that charts break because they depend on column order. Thanks for the help here!!

**Comment by camsaul** [comment] 2016-06-23 22:58
Yeah we apply sort logic to the columns in the results but they're only supposed to apply to queries built using the GUI. I'm guessing here the logic is applying to BigQuery even when a plain SQL query is ran

**Comment by camsaul** [comment] 2016-06-23 23:00
@tlrobinson Several things chained in 0.18, allen's MBQL -> native stuff and my fix for bigquery native queries. I can take a look at this.

**Comment by camsaul** [comment] 2016-06-24 20:17
Fixed by #2832

**Closed by camsaul** 2016-06-24 20:17 UTC
Labels: Bug, Database/BigQuery, Query Processor

**Comment by thekantian** [comment] 2016-06-24 20:18
Nice, thanks guys! Any idea when a patch release will be cut with this included?

**Comment by camsaul** [comment] 2016-06-27 19:20
@thekantian Patch release 0.18.1 should be live later today or tomorrow 👍

**Comment by tlrobinson** [comment] 2016-06-28 00:47
@thekantian We just released [0.18.1](https://github.com/metabase/metabase/releases/tag/v0.18.1) which should fix this. Thanks for reporting it.
