### ISSUE TITLE
Query builder should have horizontal scrolling with many metrics or dimensions

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8669] opened 2018-10-10 18:04 UTC
When adding many metrics or group-bys, the query builder used to have a max width and would scroll the overflow. But now on master on Chrome I'm seeing this:

![screen shot 2018-10-10 at 11 03 13 am](https://user-images.githubusercontent.com/2223916/46756420-4460b680-cc7c-11e8-850e-83ceb00d6b8f.png)

**Comment by flamber** [comment] 2019-02-18 04:34
Hi @mazameli 
This looks like a duplicate of #6566

**Comment by notrom** [comment] 2019-05-06 21:32
I'm seeing the exact same thing in Firefox too.

**Comment by salsakran** [comment] 2019-07-30 22:39
dupe of #5325!

**Closed by salsakran** 2019-07-30 22:39 UTC
Labels: Query Builder, Type:Bug
