### ISSUE TITLE
Title drill-through leads to different destinations depending on whether the question is nested or not

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#17213] opened 2021-07-26 22:17 UTC
**Describe the bug**
When you apply an ID dashboard filter to both nested and "normal" qb questions and then click on each of their titles, it takes you to different pages.
- Nested question shows a table with the "ID=num" filter applied
- Regular question takes you to a object detail page

**To Reproduce**
1. Save Sample Dataset "Products" as a question
2. Ask a question > Custom > Saved > Choose previously saved "Products" and save it as "Products nested"
3. Add them both to a new dashboard
4. Add ID dashboard filter and connect it to both cards to the only possible "ID" field
5. Save the dashboard
6. Click on the filter widget and enter any number to filter on the ID
![image](https://user-images.githubusercontent.com/31325167/127066023-a04ab37d-40e1-4fc0-a4f4-c4fc6fa6dff6.png)

7. Click on "Products Nested" title - it will take you to the "Products" question page with applied filter
<details>

![image](https://user-images.githubusercontent.com/31325167/127066082-4b35cc1f-3ad4-44f0-80bd-757b8bac868e.png)

</details>

8. Click on "Products" title - it will take you to the object details page of that product ID
<details>

![image](https://user-images.githubusercontent.com/31325167/127066238-bc5db605-fffe-489e-82d4-dd8200d49e59.png)

</details>

**Expected behavior**
I'd expect them to behave the same.

**Screenshots**
Expand the "Details" above to see the screenshots.

**Information about your Metabase Installation:**
local dev, H2, `master`

**Severity**
P3?

**Comment by flamber** [comment] 2021-07-27 10:32
This is not specific to dashboards. Filtering directly on the nested question also doesn't show Object Details.
![image](https://user-images.githubusercontent.com/1447303/127139279-2e0d14f3-376b-4507-bf6d-2572352b1600.png)

Something makes me things that we're not parsing the PK thru correctly in the nested question - perhaps duplicate of #5595.

**Closed** 2023-09-26 06:07 UTC
Labels: Type:Bug, Priority:P3, .Frontend, Querying/GUI, .Team/42 :milky_way:, .FixGUIScope42
