### ISSUE TITLE
World region map zoom-in doesn't zoom to US states map on a saved question

### ISSUE THREAD

**Issue by ZahiC** [metabase/metabase#29483] opened 2023-03-23 15:14 UTC
**Describe the bug**
After saving a 'Region map' world question, zooming-in to the US stops working. It changes the query correctly to use the 'state' field with the same aggregation but the visualization doesn't change to US region map. It does work on unsaved question.

**To Reproduce**
1. Create a new question
2. Choose a table that has valid Country & State columns
3. Summarize - Count by Country
4. Click 'Visualize'
5. Click on the US area on the World Map
6. (optional) Click '(+) Zoom in' (a US states map is shown as expected)
7. (optional) Navigate back to the World Map (browser back button)
8. Save the question
9. Refresh the page when viewing the saved question
10. Click on the US area
11. Click '(+) Zoom in' 
12. A invalid world map is shown. Clicking on the 'Show editor' button shows that it has changed to region field aggregation, but the visualization isn't changed accordingly

**Expected behavior**
We were expecting the saved world map to behave the same as unsaved question, showing a states map when zooming in to the US.

**Information about your Metabase Installation:**
```json
"version": {
  "date": "2023-01-27",
  "tag": "v1.45.2.1",
  "branch": "release-x.45.2.x",
  "hash": "1a59de7"
},
```

**Severity**
Low

**Comment by paoliniluis** [comment] 2023-03-23 16:20
I think your issue is a duplicate of https://github.com/metabase/metabase/issues/4724 or https://github.com/metabase/metabase/issues/13533

**Closed by paoliniluis** 2023-03-23 16:20 UTC
Labels: Type:Bug, .Needs Triage

**Comment by ZahiC** [comment] 2023-03-26 12:30
@paoliniluis I think it's not the same issue. Here it seems like a bug as zooming into a region is already supported. It works when the question is not saved, but stops working on a saved question.
