### ISSUE TITLE
Column alignment off with Pulses and table visualizations

### ISSUE THREAD

**Issue by senior** [metabase/metabase#8170] opened 2018-07-30 17:45 UTC
I'm seeing the column heading alignment off with current master https://github.com/metabase/metabase/commit/18887fc9a52b5f57691115da2d9de398320ff661.
![3-column-pulse](https://user-images.githubusercontent.com/215910/43413580-0f5fc304-93f6-11e8-9649-c795ac29030e.png)
Not sure if this info is relevant or not but it's just a query against the Orders table with a `fields` clause that only includes 3 columns.

**Comment by ryanfoxsquire** [comment] 2018-09-12 05:03
@senior is there a rough timeline (days, weeks, months) that this bug and https://github.com/metabase/metabase/issues/8446 may be addressed?

**Comment by mazameli** [comment] 2018-09-25 16:56
I'm seeing this, too:

![screen shot 2018-09-25 at 9 43 36 am](https://user-images.githubusercontent.com/2223916/46029680-f909ae00-c0a8-11e8-8d7a-758385ed8f5c.png)

Pulses with conditional formatting seem to be aligning better, with the exception of the date column in this example. There is also not enough left padding on the date column, and the font size between the date column vs. the numeric columns appears to be different to my discerning eyes.

![screen shot 2018-09-25 at 9 43 30 am](https://user-images.githubusercontent.com/2223916/46029677-f5762700-c0a8-11e8-92d8-8ab9c1eb5284.png)

**Comment by ryanfoxsquire** [comment] 2018-09-25 18:40
@mazameli and everyone -- one thing I realized is that the column widths are being set by column name / row length. So one workaround for my problem was to artificially extend the column names like this. Not perfect at all, but at least makes it readable for me (compared to my earlier examples shown here: https://github.com/metabase/metabase/issues/8446#issuecomment-419599912). . 





<img width="364" alt="screen shot 2018-09-25 at 11 38 10 am" src="https://user-images.githubusercontent.com/6432906/46035330-a5eb2780-c0b7-11e8-90d3-e59414654b18.png">

**Comment by flamber** [comment] 2020-06-06 21:49
I cannot reproduce on 0.35.4 - I think it was fixed in 0.33.1
![image](https://user-images.githubusercontent.com/1447303/83955151-2f249c80-a850-11ea-945b-5b36e62f0610.png)

**Closed by flamber** 2020-06-06 21:49 UTC
Labels: Reporting/Pulses, Type:Bug, Visualization/
