### ISSUE TITLE
Call to "values" endpoint for filter params slow in the embedded context

### ISSUE THREAD

**Issue by synweap15** [metabase/metabase#20549] opened 2022-02-16 12:36 UTC
**Describe the bug**

Refers to v0.41.6.

Given a dashboard with filter parameters, upon opening a category filter, a call is made to the backend.

If viewed in the metabase directly, the call is issued to `https://{domain}/api/dashboard/{dashboard_id}/params/{hash}/values`. This call is very quick:
![image](https://user-images.githubusercontent.com/2964879/154264623-f357ab4f-f7c0-42fd-bc7b-2b70c342e7df.png)

However, in the embedded context, a call issued to `https://{domain}/api/embed/dashboard/{jwt_token}/params/{hash}/values` is much slower. It's slow on the first, but also all subsequent calls.

![image](https://user-images.githubusercontent.com/2964879/154264874-ee278cd1-3e71-45e5-bee9-049b866f5cec.png)

Moreover, there's no indication that the values are loading, so the users of the dashboard report back that "they don't see the values to choose".

For what it's worth, the embedded dashboard has one parameter locked.

**To Reproduce**
1. Create a dashboard that has a filter over a certain category
2. Check the timing in the metabase directly
3. Check the timing in the embedded context

**Expected behavior**
Both calls should use a similar caching strategy/routine resulting in quick suggestion loads.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "pl-PL",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "4.19.0-18-cloud-amd64",
    "user.language": "en",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.28"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-01-10",
      "tag": "v0.41.6",
      "branch": "release-x.41.x",
      "hash": "296635f"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

```

**Comment by flamber** [comment] 2022-02-16 13:44
Duplicate of #16109

**Closed by flamber** 2022-02-16 13:44 UTC
Labels: Type:Bug, .Needs Triage
