### ISSUE TITLE
"Cannot read property 'getAttribute' of undefined" in sample dataset

### ISSUE THREAD

**Issue by flyingmachine** [metabase/metabase#10626] opened 2019-08-19 19:46 UTC
**Describe the bug**

I'm seeing the error message "Cannot read property 'getAttribute' of undefined" when zooming into Reviews data in the sample dataset

**Logs**

```
TypeError: Cannot read property 'getAttribute' of undefined
    at H.<anonymous> (app-main.bundle.js:5)
    at H.r [as renderlet] (vendor.bundle.js?db89dea08bd003ad80f4:1)
    at Object.r._activateRenderlets (vendor.bundle.js?db89dea08bd003ad80f4:1)
    at Object.r.render (vendor.bundle.js?db89dea08bd003ad80f4:1)
    at V (app-main.bundle.js:5)
    at Object.t.barRenderer [as renderer] (app-main.bundle.js:5)
    at t.value (app-main.bundle.js:5)
    at t.value (app-main.bundle.js:5)
    at t.notifyAll (vendor.bundle.js?db89dea08bd003ad80f4:1)
    at h.close (vendor.bundle.js?db89dea08bd003ad80f4:1)
value @ app-main.bundle.js:5
```

**To Reproduce**

1. Open the sample dataset
2. Click on "a look at your Reviews table"
3. Click on a column under "Reviews by Rating"

**Expected behavior**

I expected to see charts

**Screenshots**

<img width="982" alt="Screen Shot 2019-08-19 at 3 41 33 PM" src="https://user-images.githubusercontent.com/1421/63294436-534ec700-c298-11e9-8d9b-67cacd91176b.png">

**Information about your Metabase Installation:**

- Dockerized MB 0.32.10
- OS X 10.14
- Chrome 76

**Severity**

annoying

**Comment by mazameli** [comment] 2019-08-19 19:53
A bunch of stuff has changed about the query builder since 0.32.10, and I can't reproduce this in `release-0.33.x`, so I'm going to go ahead and close this one.

**Closed by mazameli** 2019-08-19 19:53 UTC
Labels: Type:Bug
