### ISSUE TITLE
How to maintain formatting and display long text

### ISSUE THREAD

**Issue by wypdao** [metabase/metabase#46710] opened 2024-08-12 10:34 UTC
There is a field in my MySQL database that contains a long amount of text content with many carriage returns and line breaks. I used a metabase to display this field, but it couldn't display carriage returns and line breaks. All the text was displayed on one line, which looked very inconvenient，How can I configure to keep displaying carriage returns and line breaks format！

**Comment by paoliniluis** [comment] 2024-08-12 13:03
Duplicate of text wrap feature request

**Closed by paoliniluis** 2024-08-12 13:03 UTC
Labels: Type:New Feature, .Needs Triage

**Comment by wypdao** [comment] 2024-08-13 02:56
@paoliniluis I have provided you with the email address paoliniluis@gmail.com, I sent you an email with my metabase address and account
