### ISSUE TITLE
Mongo custom query about "previous time" performance Improvement.

### ISSUE THREAD

**Issue by hxnan** [metabase/metabase#7007] opened 2018-02-23 03:00 UTC
I try the mongo "New Question -> Custom -> filterd by - > previous 1 hour " function.
The Navive query use the "$dateToString" then "$eq" a string like "2018-02-23T01:00:00".
If the datasize is large , most of the time will be spend in "$dateToString".

Maybe "$gt":ISOdate("2018-02-23T01:00:00") will take a better performance .

**Comment by smohsensh** [comment] 2019-01-19 04:57
It is worth noting that this is not merely a performance issue, always running a `$project`  stage before applying any kind of filters is practically impossible when you just 1M docs in your collection. 

**To describe the issue in more detail:** 
Consider a question with date range filter that just counts the documents. something like this:
<img width="657" alt="screen shot 2019-01-13 at 5 29 38 pm" src="https://user-images.githubusercontent.com/5060107/51086201-da631c00-1758-11e9-9ea4-d54e463d5e28.png">
the aggregation query generated by Metabase to perform this query is this:
```
[
    {"$project":{"date~~~day":{"$let":{"vars":{"column":"$date"},"in":{"___date":{"$dateToString":{"format":"%Y-%m-%d","date":"$$column"}}}}}}},
    {"$match":{"date~~~day":{"$gte":{"___date":"2019-01-10"},"$lte":{"___date":"2019-01-12"}}}},
    {"$group":{"_id":null,"count":{"$sum":1}}},
    {"$sort":{"_id":1}},
    {"$project":{"_id":false,"count":true}}
]
```
The project stage here runs is the first stage (and because the field ```date~~~day``` defined by it is referenced in the next `$match` stage, MongoDB query planner cannot swap these two) so the project stage is ran on all documents. This causes the query to timeout on a medium or large collection. 
However if the query started with a `$match`, it could take advantage of a possible index defined on `date` field and would run and return a result. 

**Solution:** 
This can be achieved by using MongoDB's `ISODate()` constructor to avoid the `$project` stage.  

```
[
    {"$match":{"date":{"$gte":ISODate("2019-01-10"),"$lte":ISODate("2019-01-12")}}},
    {"$group":{"_id":null,"count":{"$sum":1}}},
...
]
```

**Comment by thomasnordquist** [comment] 2019-03-20 07:32
Duplicate of https://github.com/metabase/metabase/issues/7007

**Comment by camsaul** [comment] 2020-05-13 01:46
Duplicate of #4216

**Closed by camsaul** 2020-05-13 01:46 UTC
Labels: .Proposal, Database/Mongo, Type:Performance
