### ISSUE TITLE
Activity Feed can't update after I upgrade v0.29.2 to v0.29.3

### ISSUE THREAD

**Issue by xjzhou** [metabase/metabase#7680] opened 2018-05-22 07:50 UTC
I logged in as admin, activity page like this (no news for recent)：
![image](https://user-images.githubusercontent.com/1255410/40349006-da1f452e-5dd7-11e8-93cb-79373899296d.png)

**Comment by salsakran** [comment] 2018-07-03 00:15
Are there any errors in the logs when you save a question? I can't reproduce this.

**Comment by xjzhou** [comment] 2018-07-06 14:00
The following screen is the logs when I log in and save a question, no errors.

![image](https://user-images.githubusercontent.com/1255410/42382734-cde37d44-8167-11e8-96ae-d6a2ff8f43a7.png)

**Comment by kdoh** [comment] 2018-10-31 02:35
I can't seem to reproduce this either so I'm going to close it for now. If you're able to provide more details or if we see more people report this we'll happily open the issue again.

**Closed by kdoh** 2018-10-31 02:35 UTC
Labels: Unable to Reproduce
