### ISSUE TITLE
Start day of week is not respected with snowflake driver

### ISSUE THREAD

**Issue by joshi-hiren** [metabase/metabase#13804] opened 2020-11-16 10:44 UTC
**Describe the bug**
Metabase 0.37.0 introduced a config to set start of week (from the defualt Sunday to say Monday, for business reporting), with snowflake this doesn't seem to work, if set to Monday, the days of weeks in all reports are off by one.

**To Reproduce**
1. Go to settings
2. Set day of week for Monday
3. Make any report that aggrogates by day of week
4. You'll notice that the entrey labled Friday is actully Saturday's numbers

**Expected behavior**
When agragating by days of week, the correct number should be labled with the cirrect day

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.198-152.320.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Europe/London"
  },
  "metabase-info": {
    "databases": [
      "snowflake"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-10-26",
      "tag": "v0.37.0.2",
      "branch": "release-x.37.x",
      "hash": "ba7be09"
    },
    "settings": {
      "report-timezone": "GMT"
    }
  }
}

**Severity**
Workaround is to leave start of week to Sunday but then that's a feture a snowflake user can't use

**Additional context**
https://github.com/metabase/metabase/wiki/What's-new-in-0.37.0-for-Metabase-driver-authors

I beleive this needs implementing in the snowflake driver.

**Comment by flamber** [comment] 2020-11-16 10:48
Hi @joshi-hiren 
Sounds like a duplicate of #13604, which is part of 0.37.1

**Closed by flamber** 2020-11-16 10:48 UTC
Labels: .Needs Triage, Type:Bug
