### ISSUE TITLE
[Epic] Index individual entities and surface them in search

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#29405] opened 2023-03-21 17:27 UTC
**Links**
- product doc: https://www.notion.so/metabase/Index-individual-entities-and-surface-them-in-search-9558b3e1f6bc45c39f5d14bfe18417e4

**Implementation Plan**

- [ ] FE: Add [the column indexing toggle](https://www.notion.so/metabase/Index-individual-entities-and-surface-them-in-search-9558b3e1f6bc45c39f5d14bfe18417e4?pvs=4#716866613eb945148f14847223a2fcc5) to the column editing view
- [ ] FE: Support new search model for individual rows which should open the object detail view for them

TODO: Add BE work

**Comment by darksciencebase** [comment] 2023-07-05 13:22
closing as duplicate of #29651

**Closed by darksciencebase** 2023-07-05 13:22 UTC
Labels: .Epic
