### ISSUE TITLE
In the dashboard picker, when creating a dashboard, the wrong dashboard is chosen when you press enter

### ISSUE THREAD

**Issue by rafpaf** [metabase/metabase#45579] opened 2024-07-15 16:43 UTC
When you go to add a question to a dashboard, and you try to create a dashboard through the modal, if you press the enter key rather than clicking select, the wrong dashboard is chosen (the enter key presses the main button on the modal that is behind the modal you're looking at).

https://www.loom.com/share/85925cd6f9f04cfba99a5e401990ca87?sid=aa7ed458-19b0-49f4-a55c-1f586ed038e5

**Comment by paoliniluis** [comment] 2024-07-15 17:11
dupe of https://github.com/metabase/metabase/issues/43157

**Closed by paoliniluis** 2024-07-15 17:11 UTC
Labels: Priority:P2
