### ISSUE TITLE
Any Join when filtering on both left and right table will always reduce to inner join

### ISSUE THREAD

**Issue by carstenkadmos** [metabase/metabase#27520] opened 2023-01-05 10:00 UTC
**Describe the bug**
With the current setup of the query editor, any join where both input tables are filtered on will reduce to an inner join as the join is done first in a subquery and filtering is done after that. This leads to easily queries that show as for instance left join but are inner joins after all.

**To Reproduce**
1. Take two tables.
2. Left join them
3. Filter both on a column like for instance date
4. See that the output is actually an inner join

**Expected behavior**
When selecting left join in the query editor it should also perform one.

**Screenshots**

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "ANSI_X3.4-1968",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8-post-Debian-1deb10u1",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8-post-Debian-1deb10u1",
    "os.name": "Linux",
    "os.version": "5.4.202+",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-12-03",
      "tag": "v0.45.0",
      "branch": "release-x.45.x",
      "hash": "4e41d76"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
High. Non-expert users expect a left join and will be left with wrong results.

**Comment by flamber** [comment] 2023-01-05 11:31
Hi @carstenkadmos 
I don't think I understand the problem. Can you include the SQL generated (click "View the SQL" in upper-right of Notebook editor) and then include the SQL you are expecting?

**Comment by carstenkadmos** [comment] 2023-01-05 11:40
**Screenshot:**
<img width="1763" alt="Screenshot 2023-01-05 at 12 38 21" src="https://user-images.githubusercontent.com/113892067/210771764-f098d58d-2bdc-48b6-9a43-5d55e96b5727.png">

**Generated SQL:**
SELECT `source`.`id` AS `id`, `source`.`customer_name` AS `customer_name`, `source`.`dt` AS `dt`, `source`.`Payments__id` AS `Payments__id`
FROM (SELECT **ALL COL NAMES FROM TABLE REDACTED** FROM `datamart.completed_payouts`
LEFT JOIN `datalake.payments` `Payments` ON `datamart.completed_payouts`.`payment_id` = `Payments`.`id`) `source`
WHERE (`source`.`dt` >= date_trunc(date_add(current_date(), INTERVAL -3 month), month)
   AND `source`.`dt` < date_trunc(date_add(current_date(), INTERVAL 1 month), month) AND `source`.`Payments__dt` >= date_trunc(date_add(current_date(), INTERVAL -3 month), month) AND `source`.`Payments__dt` < date_trunc(current_date(), month))
ORDER BY `dt` DESC
LIMIT 1048575

**Comment by carstenkadmos** [comment] 2023-01-05 11:43
As the generated SQL does the left join in the subquery, the filter actions are performed on the table resulting from the subquery.

This leads to the non-matches being filtered out as a filter is set on the right-side tables and resulting in an inner join.

**Comment by flamber** [comment] 2023-01-05 12:02
@carstenkadmos I cannot reproduce this unless I start adding Custom Columns into the mix or other nested query functions. Please create a question, then go to the URL `/api/card/123`, where 123 is the question ID and include the metadata here.

**Comment by carstenkadmos** [comment] 2023-01-05 16:53
Ahh, yes you are right. A custom column is needed for issue to occur. Do you still want me to create an example card?

**Comment by carstenkadmos** [comment] 2023-01-05 17:16
Okay, so I investigated a bit. It seems like as soon as you start adding Custom Columns, the generated SQL creates a nested query. However for me I can also reproduce this issue without custom columns with just two filters. I will attach metadata for two questions. First has the left join that is actually an inner join. The second is just the base table. For me the line items are reduced to 336 from 848 with the left join.

```
{
description: null,
archived: false,
collection_position: null,
table_id: 146,
result_metadata: [
{
description: null,
semantic_type: "type/PK",
coercion_strategy: null,
name: "id",
settings: null,
field_ref: [
"field",
2392,
null
],
effective_type: "type/Text",
id: 2392,
visibility_type: "normal",
display_name: "ID",
fingerprint: null,
base_type: "type/Text"
},
{
description: null,
semantic_type: "type/Category",
coercion_strategy: null,
name: "type",
settings: null,
field_ref: [
"field",
2430,
null
],
effective_type: "type/Text",
id: 2430,
visibility_type: "normal",
display_name: "Type",
fingerprint: {
global: {
distinct-count: 2,
nil%: 0
},
type: {
type/Text: {
percent-json: 0,
percent-url: 0,
percent-email: 0,
percent-state: 0,
average-length: 7.455357142857143
}
}
},
base_type: "type/Text"
},
{
description: null,
semantic_type: null,
coercion_strategy: null,
name: "id_2",
settings: null,
field_ref: [
"field",
328,
{
join-alias: "Payments"
}
],
effective_type: "type/Text",
id: 328,
visibility_type: "normal",
display_name: "Payments → ID",
fingerprint: {
global: {
distinct-count: 94,
nil%: 0
},
type: {
type/Text: {
percent-json: 0,
percent-url: 0,
percent-email: 0,
percent-state: 0,
average-length: 36
}
}
},
base_type: "type/Text"
}
],
creator: {
last_login: "2023-01-04T09:51:13.005383Z",
is_qbnewb: false,
is_superuser: true,
id: 20,
date_joined: "2022-09-02T08:41:55.064013Z",
},
can_write: true,
database_id: 3,
enable_embedding: false,
collection_id: 42,
query_type: "query",
name: "Test1 - Bug Always Inner Join",
last_query_start: "2023-01-05T17:10:08.385061Z",
dashboard_count: 0,
average_query_time: 848,
creator_id: 20,
moderation_reviews: [ ],
updated_at: "2023-01-05T17:10:09.229572Z",
made_public_by_id: null,
embedding_params: null,
cache_ttl: null,
dataset_query: {
type: "query",
query: {
source-table: 146,
joins: [
{
fields: [
[
"field",
328,
{
join-alias: "Payments"
}
]
],
source-table: 27,
condition: [
"=",
[
"field",
2387,
null
],
[
"field",
328,
{
join-alias: "Payments"
}
]
],
alias: "Payments",
strategy: "left-join"
}
],
filter: [
"and",
[
"time-interval",
[
"field",
2414,
null
],
-1,
"month",
{
include-current: false
}
],
[
"time-interval",
[
"field",
345,
{
join-alias: "Payments"
}
],
-1,
"month",
{
include-current: false
}
]
],
fields: [
[
"field",
2392,
null
],
[
"field",
2430,
null
]
]
},
database: 3
},
id: 543,
parameter_mappings: [ ],
display: "table",
entity_id: "BqRpxAZxcYPFT2AaoHsS0",
collection_preview: true,
last-edit-info: {
id: 20,
timestamp: "2023-01-05T17:09:05.79203Z"
},
visualization_settings: {
table.pivot_column: "type",
table.cell_column: "id_2"
},
is_write: false,
collection: {
authority_level: null,
description: "For purposes of metabase feature testing",
archived: false,
slug: "testing",
color: "#509EE3",
name: "Testing",
personal_owner_id: null,
id: 42,
entity_id: "uSrIy12_ffpiqLRkfsOyw",
location: "/37/",
namespace: null,
created_at: "2022-10-20T13:11:43.713669Z"
},
parameters: [ ],
dataset: false,
created_at: "2023-01-05T17:09:05.772453Z",
public_uuid: null
}
```

```
{
description: null,
archived: false,
collection_position: null,
table_id: 146,
result_metadata: [
{
description: null,
semantic_type: "type/PK",
coercion_strategy: null,
name: "id",
settings: null,
field_ref: [
"field",
2392,
null
],
effective_type: "type/Text",
id: 2392,
visibility_type: "normal",
display_name: "ID",
fingerprint: null,
base_type: "type/Text"
},
{
description: null,
semantic_type: "type/Category",
coercion_strategy: null,
name: "type",
settings: null,
field_ref: [
"field",
2430,
null
],
effective_type: "type/Text",
id: 2430,
visibility_type: "normal",
display_name: "Type",
fingerprint: {
global: {
distinct-count: 4,
nil%: 0
},
type: {
type/Text: {
percent-json: 0,
percent-url: 0,
percent-email: 0,
percent-state: 0,
average-length: 5.951650943396227
}
}
},
base_type: "type/Text"
}
],
creator: {
last_login: "2023-01-04T09:51:13.005383Z",
is_qbnewb: false,
is_superuser: true,
id: 20,
date_joined: "2022-09-02T08:41:55.064013Z",
},
can_write: true,
database_id: 3,
enable_embedding: false,
collection_id: 42,
query_type: "query",
name: "Test2 - Bug Always Inner Join",
last_query_start: "2023-01-05T17:13:28.894792Z",
dashboard_count: 0,
average_query_time: 720.3333333333334,
creator_id: 20,
moderation_reviews: [ ],
updated_at: "2023-01-05T17:13:29.72876Z",
made_public_by_id: null,
embedding_params: null,
cache_ttl: null,
dataset_query: {
database: 3,
query: {
source-table: 146,
filter: [
"time-interval",
[
"field",
2414,
null
],
-1,
"month",
{
include-current: false
}
],
fields: [
[
"field",
2392,
null
],
[
"field",
2430,
null
]
]
},
type: "query"
},
id: 544,
parameter_mappings: [ ],
display: "table",
entity_id: "c635knCZoYYfVRgIMkXSF",
collection_preview: true,
last-edit-info: {
id: 20,
timestamp: "2023-01-05T17:10:00.276301Z"
},
visualization_settings: {
table.pivot_column: "type",
table.cell_column: "id_2"
},
is_write: false,
collection: {
authority_level: null,
description: "For purposes of metabase feature testing",
archived: false,
slug: "testing",
color: "#509EE3",
name: "Testing",
personal_owner_id: null,
id: 42,
entity_id: "uSrIy12_ffpiqLRkfsOyw",
location: "/37/",
namespace: null,
created_at: "2022-10-20T13:11:43.713669Z"
},
parameters: [ ],
dataset: false,
created_at: "2023-01-05T17:09:30.278738Z",
public_uuid: null
}
```

**Comment by flamber** [comment] 2023-01-06 11:20
@carstenkadmos I cannot reproduce. Please include the full (do not redact) SQL generated by going to "Test1 - Bug Always Inner Join".

**Comment by carstenkadmos** [comment] 2023-01-06 15:17
Here it is 

`SELECT `datamart.completed_payouts`.`id` AS `id`, `datamart.completed_payouts`.`type` AS `type`, `Payments`.`id` AS `Payments__id`
FROM `datamart.completed_payouts`
LEFT JOIN `datalake.payments` `Payments` ON `datamart.completed_payouts`.`payment_id` = `Payments`.`id`
WHERE (`datamart.completed_payouts`.`dt` >= date_trunc(date_add(current_date(), INTERVAL -1 month), month)
   AND `datamart.completed_payouts`.`dt` < date_trunc(current_date(), month) AND `Payments`.`dt` >= date_trunc(date_add(current_date(), INTERVAL -1 month), month) AND `Payments`.`dt` < date_trunc(current_date(), month))
LIMIT 1048575`

**Comment by flamber** [comment] 2023-01-06 15:22
@carstenkadmos So there's no nested query going on here, which is the same as I'm seeing.
So what exactly is the problem? Please provide a SQL query that you would expect Metabase to generate.

**Comment by carstenkadmos** [comment] 2023-01-06 15:26
True, my argument is that no left join is possible when wanting to filter the the right hand table. Basically when filtering on a left join you could also just switch to an inner join. When filtering on the right side sth like this would actually do what I would expect. 

`SELECT `datamart.completed_payouts`.`id` AS `id`, `datamart.completed_payouts`.`type` AS `type`, `Payments`.`id` AS `Payments__id`
FROM `datamart.completed_payouts`
LEFT JOIN `datalake.payments` `Payments` ON `datamart.completed_payouts`.`payment_id` = `Payments`.`id` AND `Payments`.`dt` >= date_trunc(date_add(current_date(), INTERVAL -1 month), month) AND `Payments`.`dt` < date_trunc(current_date(), month))
WHERE (`datamart.completed_payouts`.`dt` >= date_trunc(date_add(current_date(), INTERVAL -1 month), month)
   AND `datamart.completed_payouts`.`dt` < date_trunc(current_date(), month) 
LIMIT 1048575`

**Comment by flamber** [comment] 2023-01-06 15:44
@carstenkadmos Okay, so this is not a bug report, but a feature request?
You are basically looking for something like this (which will be possible from v46, when `now` function is introduced)
![image](https://user-images.githubusercontent.com/1447303/211045924-0ec48e65-ac46-4125-bba3-52129a7bd9d6.png)

I'm going to close this issue, since it has been quite confusing. You're welcome to open a new issue, but please provide very clear reproduction steps (that everyone will be able to follow) and with expected behavior (include SQL when needed etc)

**Closed by flamber** 2023-01-06 15:44 UTC
Labels: Type:Bug, .Needs Triage

**Comment by flamber** [comment] 2023-01-06 15:54
@carstenkadmos Sounds like you are likely looking for #11869
