### ISSUE TITLE
Pivot table in night time mode is unreadable

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#24117] opened 2022-07-19 18:31 UTC
**Describe the bug**
Night time mod + pivot tables is not a fancy combination :(

**Logs**
NA

**To Reproduce**
1) New->question->Orders -> sum of total, sum of tax, sum of quantity by source
2) use the pivot table viz
3) add to a dashboard
4) put the dashboard in full screen mode
5) click on night time

**Expected behavior**
See the contents of the pivot table

**Screenshots**
![image](https://user-images.githubusercontent.com/1711649/179822959-58b5a343-e45f-4e78-b008-e219931a3c33.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop 22.04
- Metabase version: 1.43.4, tested in master as well
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
Can't use pivots in night time, so I would say P2

**Additional context**
NA

**Comment by flamber** [comment] 2022-07-21 09:47
Duplicate of #23072

**Closed by flamber** 2022-07-21 09:47 UTC
Labels: Type:Bug, Priority:P2, .Frontend, Visualization/Tables
