### ISSUE TITLE
Date shown is over 24 hours in data table view (visual bug)

### ISSUE THREAD

**Issue by JustasJan** [metabase/metabase#13138] opened 2020-08-19 08:36 UTC
Date can be over 24 hours when viewing table data.
Changing view from simple to SQL fixes it.

<br>

Data view right after entering data table:
![simple view](https://user-images.githubusercontent.com/12074445/90610791-9c6c8a80-e20e-11ea-8fe4-09f8f191ecd7.png)

Data view after converting to SQL:
![sql view](https://user-images.githubusercontent.com/12074445/90610907-c0c86700-e20e-11ea-8cc8-b18b9693bb7f.png)

Postgres data:
![postgres](https://user-images.githubusercontent.com/12074445/90610956-cde55600-e20e-11ea-984a-bed735d717bb.png)

**System info:**
```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.18.0-193.6.3.el8_2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**
Seems to be visual bug only, doesn't affect data but looks weird.

**Comment by flamber** [comment] 2020-08-19 09:47
Duplicate of #9538

**Closed by flamber** 2020-08-19 09:47 UTC
Labels: .Needs Triage, Type:Bug
