### ISSUE TITLE
UI - data model - foreign key selector

### ISSUE THREAD

**Issue by dfx413** [metabase/metabase#13806] opened 2020-11-16 14:57 UTC
version: 145b575 docker

Hi,
1. In Data model I open the dropdown with available tables
2. I start typing the table name into autosuggest
3. Table not found 

Table is present in the list so I can select it manually but the autosuggest is not able to filter the name correctly. 

![Kapture 2020-11-16 at 15 50 19](https://user-images.githubusercontent.com/1764151/99267315-13bcb500-2824-11eb-8b62-08f0caa80ecf.gif)

**Comment by flamber** [comment] 2020-11-16 15:15
Duplicate of #13025

**Closed by flamber** 2020-11-16 15:15 UTC
Labels: .Needs Triage, Type:Bug
