### ISSUE TITLE
Default values are not respected for pinned questions in collections in v48

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#37831] opened 2024-01-17 21:52 UTC
### Describe the bug

When you add default values to the filters (normal or field filters) on a native questions, those are not taken into account in v48

### To Reproduce

1) new question -> select * from people where {{something}}
2) something is a field filter mapped to the state field, it's of type "location is"
3) add a default value, like NY
4) select a state, run the question, it will run
5) now remove the state from the filter (not from the default value). Run the question, see it failing

### Expected behavior

It should run with the default filter

### Logs

NA

### Information about your Metabase installation

```JSON
v48.x
```

### Severity

P2

### Additional context

Pretty sure this worked in v47

**Comment by notz** [comment] 2024-01-18 20:39
@paoliniluis May this bug also cause the problem that pinned sql queries with default values can't be rendered on the folder overview? 

Saw that problem on 48.0, but never tried a newer version after rollback to 47.

**Comment by prigal** [comment] 2024-01-24 08:41
Same problem here after migrating from 0.47.X to 0.48.3, we had to rollback to 0.47.12.

**Comment by paoliniluis** [comment] 2024-01-30 03:14
@prigal can you check if this has been fixed?

**Comment by paoliniluis** [comment] 2024-01-30 03:17
fixed

**Comment by notz** [comment] 2024-01-31 22:53
@paoliniluis it's not fixed with 0.48.4 for me. Same behaviour than before. In folder view for pinned sql queries with default date filter values.

Left one has required set on the date filter and the right one hasn't required set (renders but without default date filter)

![image](https://github.com/metabase/metabase/assets/697251/d2544333-46d6-40ce-a4b1-8cac0c258ab9)

Have to rollback again.

**Comment by darksciencebase** [comment] 2024-02-01 09:29
Following the steps to reproduce I can't see the issue anymore — the question works as expected.
@notz maybe in your case it's a different problem after all. Can you reproduce it with a new question on the Sample Database?

**Comment by paoliniluis** [comment] 2024-02-02 15:50
cc @bshepherdson

**Comment by bshepherdson** [comment] 2024-02-02 16:07
I don't have any real insight.

In my testing for #38012 I remember that the FE was passing the default values to the BE when a value was not set. So my guess is that the FE isn't sending them for pinned cards, and to check the network request.

(Not assigning myself; I'm working on something else today.)

**Comment by paoliniluis** [comment] 2024-02-02 16:55
you're absolutely right @bshepherdson , that's the exact cause

**Comment by calherries** [comment] 2024-02-06 17:05
Just reading the description, I suspect this is the cause [Allow native questions with filters with default values to be cleared](https://github.com/metabase/metabase/pull/31891)

**Comment by paoliniluis** [comment] 2024-02-12 15:19
@calherries if the PR wasn't backported, this will be broken till 49 right?

**Comment by calherries** [comment] 2024-02-12 16:34
for reference, Luiggi and I discussed on slack and Luiggi was mistaken in the previous comment. There is no fix yet

**Closed** 2024-02-26 19:43 UTC
Labels: Type:Bug, Priority:P2, Querying/Parameters & Variables, Querying/Native, .Frontend, .Regression, .Escalation, .Team/DashViz
