### ISSUE TITLE
Hidden fields are still shown as the result of an SQL query

### ISSUE THREAD

**Issue by caske33** [metabase/metabase#2302] opened 2016-04-04 20:19 UTC
I'm guessing this is known and very hard to fix but I thought I would report it anyway:

Hidden fields are still shown in the table view if you use `table.*` in a raw SQL query. Maybe metabase should try to filter the hidden columns out?

For example:

`SELECT * FROM user WHERE id = 3` will report the password field of the user, even if the password field is marked als hidden.

**Comment by camsaul** [comment] 2016-04-04 20:21
Duplicate of #1689 .

**Closed by camsaul** 2016-04-04 20:21 UTC
Labels: Duplicate

**Comment by caske33** [comment] 2016-04-05 10:06
Oops, I tried searching for a duplicate but couldn't find it. Sorry
