### ISSUE TITLE
Add support for group-based static filters

### ISSUE THREAD

**Issue by PiMaker** [metabase/metabase#9258] opened 2019-01-14 12:54 UTC
Hi everyone!

Our team is currently planning to integrate Metabase into our own, internal reporting platform as an analysis tool. Since our system is (sadly) built on a lot of legacy code at the moment, our DB table structure is not very optimized for table-based user roles yet.

Our current solution includes a column containing a value regarding which organizational area a row belongs to. E.g.:

| ID | Data | More Data | Area         |
|----|------|-----------|--------------|
| 0  | ...  | ...       | 'workgroup1' |
| 1  | ...  | ...       | 'workgroup1' |
| 2  | ...  | ...       | 'workgroup2' |

The system we are trying to replace would then basically append a `WHERE Area='current user group'` into every request.

We currently don't see a way to implement this type of access control in Metabase (if there is, let us know please; we couldn't find anything) - the finest granularity seems to be table-based. A feature to support such structures would allow us to use a single instance of Metabase targeting our main internal reporting database, while still having granular user access control, even on legacy tables.

Our idea so far:

To model this behaviour in Metabase, a fixed ("static") filter based on groups would be a simple and useful solution. According to this, it would be possible to add one or more filters to user groups, that only admins can change. Every question asked through Metabase would then be filtered by all filters set by the current user's group before being further filtered/grouped via the question entered in the user interface.
This could be shown to the user as an "unchangeable" filter in the question builder.

This definitely opens up some questions as to how this would work with Dashboards and the like, but since this is currently not a business need for our use case we have (as of yet) not done any exploration into that region.

Alternatively, this type of access control could definitely be implemented on the database layer itself (SQL views?), although the cleaner solution (in our opinion anyway) would be to have it integrated into the Metabase interface itself.

We are happy to hear any feedback from the Metabase team, if this could be a viable addition to Metabase itself or not.

**Comment by flamber** [comment] 2019-01-14 18:22
Hi @PiMaker 
This sounds similar to #2824.
Like you state, SQL Views would be a fix for this. It would mean that you had to create a View and database connection for each user group, and setup data model for each connection.
It would be great if Metabase could accommodate any type of database structure, but that would also be difficult, compared to creating Views to fix bad structures in legacy systems.

**Comment by salsakran** [comment] 2019-01-22 15:42
closing as a dupe of 2824

**Closed by salsakran** 2019-01-22 15:42 UTC
