### ISSUE TITLE
DateFilter - Between doesn't work properly

### ISSUE THREAD

**Issue by jescorotero** [metabase/metabase#7035] opened 2018-02-28 11:07 UTC
Hi
We are experience some issues when using a DateFilter variable with between mode.

As you can see in the video, after you choose the start date, if you wanna to change the month for End Date, you only can go over one step more after it crashes and date picker shakes.

Using Windows 10 + Chrome + Metabase v0.28.1 + Database=Mysql

https://share.vidyard.com/watch/Tju6HFvTvjeuJaCbg7J6pE

Reproduce:

1.  Create a new variable, and choose a Field Filter type, then DateFilter as widget type
![image](https://user-images.githubusercontent.com/1407874/36784205-eda711ca-1c7e-11e8-9419-d1da517cb94e.png)

1. Using the filter, change to "Between" mode.
![image](https://user-images.githubusercontent.com/1407874/36784316-3f702244-1c7f-11e8-8b34-02dfbe7b8d4c.png)

1. Try to select October 1st 2017 to February, 25th 2018.  Start Date = 2017-10-01 and then click to next month arrow until 2018-February
![image](https://user-images.githubusercontent.com/1407874/36784482-d50219a2-1c7f-11e8-8127-1e1bc41ee511.png)

Then you cannnot do that, because after two months the date picker shakes

**Comment by bugo99iot** [comment] 2018-02-28 16:09
Hi Jescorotero, could you share your SQL code? Or just the WHERE statement will be enough.
What's the MySQL type of your 'Fecha Boda' column?
Probably I won't be able to help you I'm just trying to investigate a similar issue I have.

**Comment by jescorotero** [comment] 2018-03-01 08:20
fecha_alta and fecha_boda are date type fields
```
select fecha_alta, fecha_boda, id_user 
from PB_COM_USERS
where true 
 AND [[{{vFilterDate}}]]
 AND [[{{vfilterDate2}}]]
limit 100
```

**Comment by salsakran** [comment] 2018-03-02 00:14
pretty sure this is a dupe of #6952

**Closed** 2018-03-31 00:30 UTC
Labels: Bug, Priority/P1, Query Builder/Native
