### ISSUE TITLE
Pivot tables do not show custom column titles for value columns

### ISSUE THREAD

**Issue by janfrederik** [metabase/metabase#19071] opened 2021-11-23 12:10 UTC
**Describe the bug**
Pivot tables don't honor the custom "Column title" set in the formatting options for the table values.

In the normal table view, the custom column title is shown.

**To Reproduce**
1. Create aggregated question (with a "Sum of..." aggregation) and choose "Pivot Table" as visualization
2. In the visualization settings, put all category-fields in the "rows", so the "columns" is empty
3. Set a custom "Column title" for the "Sum of ..."
4. The pivot table keeps on showing the default column title "Sum of ..." for the value column.

**Expected behavior**
The custom "column title" should be show as column header in the pivot table

**Screenshots**
Definition of aggregated question:
![image](https://user-images.githubusercontent.com/18148910/143020872-7e94a9cd-9d54-4730-8bcc-935ad9e3edee.png)

Pivot table config:
![image](https://user-images.githubusercontent.com/18148910/143021062-8d43cce1-da1e-4915-94a8-6ad689aefd96.png)

Setting the custom column name:
![image](https://user-images.githubusercontent.com/18148910/143021090-d1daaff9-8160-4515-92ad-7833b4d8bf13.png)
![image](https://user-images.githubusercontent.com/18148910/143021161-737b5b38-3773-4f0a-9213-0a081a744b3e.png)

Result: pivot table still shows "Sum of Hours" as column title instead of "Hours". Even after saving, refreshing browser and opening.
![image](https://user-images.githubusercontent.com/18148910/143021022-0c73d5d8-ca36-4ba9-af29-64a26daa866c.png)

In the normal table view, the custom column title is shown:
![image](https://user-images.githubusercontent.com/18148910/143021297-1a0aac67-5746-4cfc-b245-d6882f112c06.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "5.4.0-1046-azure",
    "user.language": "en",
    "user.timezone": "Europe/Brussels"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-11-09",
      "tag": "v0.41.2",
      "branch": "release-x.41.x",
      "hash": "ad599fd"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Annoying

**Comment by flamber** [comment] 2021-11-23 12:16
Duplicate of #15353

**Closed by flamber** 2021-11-23 12:16 UTC
Labels: Type:Bug, .Needs Triage
