### ISSUE TITLE
Open *.xslx file grouped by date (month) leads to error

### ISSUE THREAD

**Issue by rogerzwingli** [metabase/metabase#24334] opened 2022-07-27 06:39 UTC
Opening a xlsx-file with grouped by date (month) will show following error: “Excel cannot open the file 'abc123.xlsx" because the file format or file extension is not valid. Verify that the file has not been corrupted and that the file extension matches the format of the file.”

All other groupings work (for example day, minutes, etc)

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.4.188+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.16"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-31",
      "tag": "v1.43.2",
      "branch": "release-x.43.x",
      "hash": "433d533"
    },

**Comment by flamber** [comment] 2022-07-27 07:22
Duplicate of #23980

**Closed by flamber** 2022-07-27 07:22 UTC
