### ISSUE TITLE
Performance regression in nested queries

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#32149] opened 2023-07-05 16:47 UTC
### Describe the bug

Let's compare these 3 scenarios:
1) scenario 1
- create a question: count of people where source = 'Google', save it as a number
- add it 30 times to a dashboard, save it
- refresh
![fast](https://github.com/metabase/metabase/assets/1711649/2487f46f-1757-450e-a54b-74c683834fa3)

2) scenario 2
- create a question: select all from people, save it as people_1
- create a question out of people_1: select all from people_1 where source = 'Google', save it as people_2
- create a question out of people_2: count, save it as a number as people_3
- add it 30 times to a dashboard, save it
- refresh
![slow](https://github.com/metabase/metabase/assets/1711649/9403ffd7-64c8-4c0f-9114-15cae8373bfe)

3) scenario 3
- let's grab people_3, turn it to a SQL question and save it as people_3_with_sql
- create a new dashboard and add it 30 times, save it, refresh
![fast_sql](https://github.com/metabase/metabase/assets/1711649/a95c8c7a-a032-41e1-8415-f68a2c75a7d4)

### To Reproduce

Above

### Expected behavior

If queries are the same, you should get the responses with the same speed

### Information about your Metabase installation

```JSON
v47, but this is hitting a few 46 customers
```

### Severity

P1

### Additional context

Why does the frontend render them 1 by one?

**Comment by snoe** [comment] 2023-07-06 19:15
Discussion from https://metaboat.slack.com/archives/C052ZBWRG3W/p1688575840459759:

So, we also do mlv2 conversion without gating in https://github.com/metabase/metabase/pull/29583

This added about ~1.8s / 100 queries, this change would be very difficult to back out, likely what we'd want to do is push forward on mlv2 in the query processor if necessary.

However, I am unable to reproduce the ~10s query times shown in this issue and I'm not convinced the conversion is the cause of what we're seeing here. It's feeling very similar to https://github.com/metabase/metabase/issues/31373 where I believe @NevRA was still seeing similar slow requests after the revert.


Some test code I used to narrow down these commits

```clojure
  (dotimes [_ 4]
    (driver/with-driver :postgres
      (mt/dataset
       sample-dataset
        (mt/with-temp*
          [Card [people-0 {:dataset_query (mt/mbql-query people
                                            {:filter [:= [:field $source nil] "Google"]
                                             :aggregation [[:count]]})}]
           Card [people-1 {:dataset_query (mt/mbql-query people {})}]
           Card [people-2 {:dataset_query (mt/mbql-query
                                           people
                                            {:source-table (str "card__" (:id people-1))
                                             :filter      [:= [:field $source nil] "Google"]})}]

           Card [people-3 {:dataset_query (mt/mbql-query
                                           people
                                            {:source-table (str "card__" (:id people-2))
                                             :aggregation [[:count]]})}]]
          (let [num-times 100]
            (let [now (java-time/instant)
                  in (a/to-chan (range 0 num-times))
                  out (a/chan 1)]
              (a/pipeline-blocking
                100
                out
                (map
                  (fn [_] (mt/user-http-request :crowberto :post 202 (format "card/%d/query"
                                                                             (:id people-0)))))
                in)
              (a/<!! (a/into [] out))
              (let [fast-time (java-time/time-between :millis now (java-time/instant))
                    now (java-time/instant)
                    in (a/to-chan (range 0 num-times))
                    out (a/chan 1)]
                (a/pipeline-blocking
                  100
                  out
                  (map
                    (fn [_] (mt/user-http-request :crowberto :post 202 (format "card/%d/query"
                                                                               (:id people-3)))))
                  in)
                (a/<!! (a/into [] out))
                (tap> [[:fast fast-time] [:slow (java-time/time-between :millis now (java-time/instant))]]))))))))
```

**Comment by john-metabase** [comment] 2023-07-10 15:48
Thanks for the test @snoe. I'm running this through a profiler first, but if that fails to highlight the biggest performance problems, then some judicious debugging should do it. As pointed out, it looks like it's going to be too complicated to unwind the changes involved here, and it may be easier to figure out how to make it faster.

**Comment by john-metabase** [comment] 2023-07-10 18:58
I haven't succeeded in profiling this yet, but sampling yielded some interesting results. Right now it looks like a significant chunk of time is spent multimethod dispatch functions, and particularly in `metabase.mbql.util.match.impl/match-in-collection`, but this isn't strictly new to v47. I'm working on a more detailed performance comparison between versions.

**Comment by camsaul** [comment] 2023-07-17 23:03
Should be resolved in x.47 by https://github.com/metabase/metabase/pull/32418

**Comment by paoliniluis** [comment] 2023-07-26 18:17
I just built the latest 47 release to check if this was fixed, please consider that I test this with docker limiting the CPU and RAM I give to the container to mimic a cloud deployment. My results on a 2 core, 2GB of RAM (JAVA_OPTS=-Xmx1536m -Xms512m) are the following:
GUI questions (~ 4 seconds):
![image](https://github.com/metabase/metabase/assets/1711649/de46de50-a70b-424d-916e-28658e410939)

SQL questions (~800ms):
![image](https://github.com/metabase/metabase/assets/1711649/7f8efa48-028b-4899-a9b3-369627366f38)

Hash: ff9613a

**Comment by paoliniluis** [comment] 2023-07-26 18:23
Interesting thing is that if you build a GUI query without using nested questions then the query takes ~ 1 second:
![image](https://github.com/metabase/metabase/assets/1711649/bf299e8c-a4dd-4a39-8ce1-001d9e63481a)

**Comment by camsaul** [comment] 2023-07-27 03:51
Adapted case's code slightly to use Criterium for profiling

```clj
(defn x []
  (driver/with-driver :postgres
    (mt/dataset sample-dataset
      (t2.with-temp/with-temp [Card people-0 {:dataset_query (mt/mbql-query people
                                                               {:filter      [:= [:field $source nil] "Google"]
                                                                :aggregation [[:count]]})}
                               Card people-1 {:dataset_query (mt/mbql-query people {})}
                               Card people-2 {:dataset_query (mt/mbql-query
                                                                 people
                                                                 {:source-table (str "card__" (:id people-1))
                                                                  :filter       [:= [:field $source nil] "Google"]})}

                               Card people-3 {:dataset_query (mt/mbql-query
                                                                 people
                                                                 {:source-table (str "card__" (:id people-2))
                                                                  :aggregation  [[:count]]})}]
        (letfn [(query-people-0 []
                  (mt/user-http-request :crowberto :post 202 (format "card/%d/query" (:id people-0))))
                (query-people-3 []
                  (mt/user-http-request :crowberto :post 202 (format "card/%d/query" (:id people-3))))]
          (query-people-0)
          (mt/set-ns-log-level! 'metabase.server.middleware.log :trace)
          (println "Query without nesting:")
          (query-people-0)
          (Thread/sleep 100)
          (println "Query with nesting:")
          (query-people-3)
          (Thread/sleep 100)
          (mt/set-ns-log-level! 'metabase.server.middleware.log :info)
          (println "Query without nesting:")
          (criterium.core/quick-bench (query-people-0))
          (println "Query with nesting:")
          (criterium.core/quick-bench (query-people-3)))))))
```

I got the following results:

### x.46.x

```
Query without nesting:

Evaluation count : 42 in 6 samples of 7 calls.
             Execution time mean : 14.150742 ms
    Execution time std-deviation : 389.133635 µs
   Execution time lower quantile : 13.463083 ms ( 2.5%)
   Execution time upper quantile : 14.529334 ms (97.5%)
                   Overhead used : 1.494505 ns

Found 1 outliers in 6 samples (16.6667 %)
 low-severe   1 (16.6667 %)
 Variance from outliers : 13.8889 % Variance is moderately inflated by outliers

Query with nesting:

Evaluation count : 18 in 6 samples of 3 calls.
             Execution time mean : 50.372110 ms
    Execution time std-deviation : 978.754017 µs
   Execution time lower quantile : 49.624156 ms ( 2.5%)
   Execution time upper quantile : 51.548643 ms (97.5%)
                   Overhead used : 1.494505 ns
```

### x.47.x

```
Query without nesting:

Evaluation count : 24 in 6 samples of 4 calls.
             Execution time mean : 32.779426 ms
    Execution time std-deviation : 1.707003 ms
   Execution time lower quantile : 31.120539 ms ( 2.5%)
   Execution time upper quantile : 34.601335 ms (97.5%)
                   Overhead used : 1.507438 ns

Query with nesting:

Evaluation count : 12 in 6 samples of 2 calls.
             Execution time mean : 60.937148 ms
    Execution time std-deviation : 1.976646 ms
   Execution time lower quantile : 58.725040 ms ( 2.5%)
   Execution time upper quantile : 63.855758 ms (97.5%)
                   Overhead used : 1.507438 ns

Found 1 outliers in 6 samples (16.6667 %)
	low-severe	 1 (16.6667 %)
 Variance from outliers : 13.8889 % Variance is moderately inflated by outliers
```

### `master`

```
Query without nesting:

Evaluation count : 24 in 6 samples of 4 calls.
             Execution time mean : 32.653396 ms
    Execution time std-deviation : 460.888324 µs
   Execution time lower quantile : 32.179981 ms ( 2.5%)
   Execution time upper quantile : 33.255000 ms (97.5%)
                   Overhead used : 1.486978 ns

Query with nesting:

Evaluation count : 6 in 6 samples of 1 calls.
             Execution time mean : 99.877331 ms
    Execution time std-deviation : 1.505706 ms
   Execution time lower quantile : 98.872747 ms ( 2.5%)
   Execution time upper quantile : 102.430359 ms (97.5%)
                   Overhead used : 1.486978 ns

Found 1 outliers in 6 samples (16.6667 %)
 low-severe   1 (16.6667 %)
 Variance from outliers : 13.8889 % Variance is moderately inflated by outliers
```

So there does seem to be a performance hit between 46 and 47, but I don't think nested queries are the problem. Nested queries had a extra overhead of ~30ms in x.46, and that still true in x.47. But non-nested queries are significantly slower in x.47

**Comment by camsaul** [comment] 2023-07-27 03:58
Hitting the QP directly with

```clj
(qp/process-query (:dataset_query people-0))
```

gives me

### 0.46.x

```
Query without nesting:
Evaluation count : 120 in 6 samples of 20 calls.
             Execution time mean : 5.422597 ms
    Execution time std-deviation : 201.665011 µs
   Execution time lower quantile : 5.127553 ms ( 2.5%)
   Execution time upper quantile : 5.601460 ms (97.5%)
                   Overhead used : 1.569040 ns
Query with nesting:
Evaluation count : 24 in 6 samples of 4 calls.
             Execution time mean : 34.161294 ms
    Execution time std-deviation : 3.391948 ms
   Execution time lower quantile : 31.542309 ms ( 2.5%)
   Execution time upper quantile : 38.654077 ms (97.5%)
                   Overhead used : 1.569040 ns
```

### 0.47.x

```
Query without nesting:
Evaluation count : 36 in 6 samples of 6 calls.
             Execution time mean : 17.889620 ms
    Execution time std-deviation : 512.505163 µs
   Execution time lower quantile : 17.312173 ms ( 2.5%)
   Execution time upper quantile : 18.419043 ms (97.5%)
                   Overhead used : 1.507438 ns
Query with nesting:
Evaluation count : 18 in 6 samples of 3 calls.
             Execution time mean : 36.792426 ms
    Execution time std-deviation : 553.643227 µs
   Execution time lower quantile : 35.989483 ms ( 2.5%)
   Execution time upper quantile : 37.334127 ms (97.5%)
                   Overhead used : 1.507438 ns
```

46 is definitely faster but nested queries surprisingly work out to about the same.

**Comment by camsaul** [comment] 2023-07-27 22:11
As case mentioned, this might actually be an async issue, maybe we're tying up our `core.async` threads or something like that

**Comment by paoliniluis** [comment] 2023-07-28 01:21
Can you compare 45 and 46 which is where I see the most difference? also, It would be awesome if we all can only use 4 cores and JAVA_TOOL_OPTIONS: -Xmx1488m -Xms500m, as that's what we run on the cloud

**Closed** 2023-08-22 15:00 UTC
Labels: Type:Bug, Priority:P1, Reporting/Dashboards, Querying/Nested Queries, .Team/QueryProcessor :hammer_and_wrench:, .Escalation
