### ISSUE TITLE
Exporting from lat/long filtered results on pin map exports everything

### ISSUE THREAD

**Issue by reed-tom** [metabase/metabase#11432] opened 2019-12-03 17:03 UTC
When you "draw a box" to filter on a pin map then go to data view and attempt to export the results it will export everything instead of the filtered results.

**Comment by flamber** [comment] 2019-12-03 17:14
Hi @reed-tom 
I cannot reproduce on `master` (upcoming 0.34), but you're not giving details on how to reproduce.
What do you mean by "data view"?
When you say "export" - do you mean "download"?

**Comment by reed-tom** [comment] 2019-12-03 19:42
Sorry, should have been more specific.  Below is the diagnostic info and more detailed description.
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_201-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_201",
    "java.vm.name": "Java HotSpot(TM) Client VM",
    "java.vm.version": "25.201-b09",
    "os.name": "Windows Server 2016",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.6",
      "date": "2019-11-19",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": "Canada/Eastern"
    }
  }
}

===========================================
On a map with multiple pins I'm clickin on the "Draw a box to filter" control on the map
![draw a box to filter](https://user-images.githubusercontent.com/58078313/70083536-90865d00-15da-11ea-928a-e13be4f54d32.png)

This appears to apply a lat/long filter.  Then I'm clicking on the data or list view (switch in the bottom center of the page)
![image](https://user-images.githubusercontent.com/58078313/70083677-e0652400-15da-11ea-871d-50d95400b3d3.png)

Then click the download button in the bottom right corner of the data view.
![image](https://user-images.githubusercontent.com/58078313/70083728-f96dd500-15da-11ea-8dfa-51921899d904.png)

I've tried with all the download formats with the same result.  The download contains all records instead of the filtered records.

**Comment by flamber** [comment] 2019-12-03 23:45
@reed-tom 
Looking at your map, it looks like there's around 50 points. Same in your Raw Data ("data view").
So are you saying that the download returns more than 50 points?
I have tried multiple version of Metabase on different browsers, but it always returns the amount of filtered points. Can you add the Sample Dataset (Admin > Databases) and try to do the test on the People table, since it's easier to reproduce issues with the same data.

But one thing I noticed was the zoom level of the map sometimes zoomed in a bit too far, so some pins were only visible outside of the viewport, but they were still included in Raw Data and download. There's an issue open about that #5211 - upvote by clicking :+1: on the first post.

**Comment by reed-tom** [comment] 2019-12-04 14:16
Found a workaround.  If I click on the filter that "Draw box to filter" produces and click "Update Filter" the resulting download only contains the filtered records.
![image](https://user-images.githubusercontent.com/58078313/70149432-160b1b00-1676-11ea-8384-7cea74b2621f.png)

It looks like "Draw box to filter" zooms to the area and writes in a filter but doesn't actually apply it until you click "Update Filter"

**Comment by mazameli** [comment] 2020-01-16 22:57
@reed-tom Are you still experiencing this on 0.34.1? I can't reproduce this on 0.34.1.

**Comment by reed-tom** [comment] 2020-01-17 16:51
> @reed-tom Are you still experiencing this on 0.34.1? I can't reproduce this on 0.34.1.

No, the issue persists.

**Comment by flamber** [comment] 2020-05-20 10:37
Closing in favor of #11557

**Closed by flamber** 2020-05-20 10:37 UTC
Labels: .Unable to Reproduce, Priority:P3, Reporting/Export, Type:Bug, Visualization/Maps
