### ISSUE TITLE
multiple value bar chart tooltips when over can be display only one value when hovered ?

### ISSUE THREAD

**Issue by eaotnc** [metabase/metabase#17084] opened 2021-07-16 03:19 UTC
I need  to custom tooltips for my chart to display only value that been hovered. Can it be ?
for example like this
![image](https://user-images.githubusercontent.com/23261505/125886422-0ffcee7c-851a-4045-b4fa-11233315cc94.png)
![image](https://user-images.githubusercontent.com/23261505/125886516-14d1b0b6-c043-41f1-939c-49a041073d10.png)

**Comment by paoliniluis** [comment] 2021-07-16 18:30
Hi, I'm closing this one as it is a duplicate of this https://github.com/metabase/metabase/issues/5176, please post the questions in the forum, thanks!

**Closed by paoliniluis** 2021-07-16 18:30 UTC
Labels: .Needs Triage, Type:Question

**Comment by eaotnc** [comment] 2021-07-16 18:58
> Hi, I'm closing this one as it is a duplicate of this #5176, please post the questions in the forum, thanks!

thank you

**Comment by ni-ndose** [comment] 2022-09-23 13:51
I disagree that this is a duplicate of #5176.

Tho it depends on how #5176 is ultimately implemented, that ticket is really leaning towards trimming down a large list of tooltips into a smaller one (e.g. so it fits on the screen).

This one here is about just showing the value (tooltip) for the one single item you're hovering over. This is common in graphing software, e.g.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/99418758/191973514-505458a2-96fa-4c91-b7f9-934e69172fbc.png">


Also, UI-design-wise it also feels a bit funny to disclose information about items you're _not_ interacting with. For lack of time, this isn't an ideal example but should highlight what the general pattern is: if I mouseover on a ticket number like #5176 or #17084 here on github, I get information about that one ticket I am interacting with and not the ones next to it.
