### ISSUE TITLE
Not user-friendly table formatting in pulses

### ISSUE THREAD

**Issue by catabram** [metabase/metabase#8699] opened 2018-10-16 09:38 UTC
Table formatting in pulses is not easily readable, e.g.:
![image](https://user-images.githubusercontent.com/15132002/47006729-45dc2400-d13f-11e8-9d6e-1f8d886ce2d5.png)
![image](https://user-images.githubusercontent.com/15132002/47007286-8e481180-d140-11e8-86ca-5b1526e3a517.png)

Previous versions (for example 0.29.3) had more readable design:
![image](https://user-images.githubusercontent.com/15132002/47007088-1f6ab880-d140-11e8-8150-d2fbf13e9bbb.png)

- Chrome 69.0.3497.100 (64)
- Windows NT 10.0
- Postgres
- Metabase version: 0.30.3

**Comment by jornh** [comment] 2018-10-16 20:18
Looks like a (variation or) duplicate of #8446 

If you agree please close and add your vote over there.

**Closed** 2018-10-17 11:35 UTC
