### ISSUE TITLE
Dropdown suggestions in a dashboard filter not working for nested SQL question

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#17214] opened 2021-07-26 23:36 UTC
**Describe the bug**
When one sets Text or Category dashboard filter and chooses "Dropdown", there is no actual dropdown with the suggestions for a nested SQL filter. It works as expected for regular and nested QB questions.

**Logs**
```
[backend] 2021-07-27 01:33:34,588 WARN middleware.log :: GET /api/field/field%2CTITLE%2C%5Bobject%20Object%5D 404 176.4 µs (0 DB calls)
[backend] "API endpoint does not exist."
```

**To Reproduce**
1. Native question > `SELECT * FROM PRODUCTS;` > Save as "SQL Products"
2. After the question is saved, you will see "Explore results" in the upper right corner > Click on it
3. It will open a QB "Products" table > Save it as "SQL Products Nested"
4. Add it to a new dashboard
5. Add filter "Text or Category", choose "Dropdown"
6. Connect it to the `TITLE` column (see the error in the "Logs" section)
**NOTE that there is no `CATEGORY` column listed!** - @flamber do we have an issue for that already?
7. Save the dashboard
8. Click on the filter widget and start typing "Br"
9. Note that there is no dropdown with the list of the matching titles

**Expected behavior**
Dropdown should work in the same manner as it does for the regular and nested QB questions.

**Screenshots**
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/ApuzZAEN/b8d262e5-dfcb-46ad-b6e4-3b042ee679ee.gif?source=viewer&v=a5a04426c30d2315207ca3a95329fe5e)

**Information about your Metabase Installation:**
local dev, H2, `master`, 1211ded01df20807883ed7dc6e2a0b8f342edd9c

**Severity**
P2?

**Additional context**
Strongly related to or even a duplicate of a #12985 (scenario 1).

**Comment by flamber** [comment] 2021-07-27 10:37
Step 6 is a duplicate of #13186. And the rest just feels like a duplicate of #12985. Should we just close in favor of those?

**Closed** 2021-08-05 14:25 UTC
Labels: .Needs Triage, Type:Bug
