### ISSUE TITLE
SQL based question shows incorrect dates on X axis of Line/ Bar Charts

### ISSUE THREAD

**Issue by joebi3** [metabase/metabase#10789] opened 2019-09-03 15:28 UTC
**Describe the bug**
When running an SQL question as a bar or bar+ line chart, the dates displayed on the x axis are being shown incorrectly. If the date range passed into the query is the 24th -30th  Aug, the chart displays dates from the 25th -31st Aug, but the label over the data point displays the correct date, see screenshot below:
![image](https://user-images.githubusercontent.com/29917166/64186492-d5c5b200-ce66-11e9-8734-02ef75bb5b4d.png)

**Logs**
The server logs don't indicate any issue:
Sep 03 15:21:26 DEBUG metabase.middleware.log :: GET /api/session/properties 200 4 ms (1 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (82 total active threads) Queries in flight: 0
Sep 03 15:21:26 DEBUG metabase.middleware.log :: GET /api/setting 200 774 µs (0 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (85 total active threads) Queries in flight: 0
Sep 03 15:21:26 DEBUG metabase.middleware.log :: GET /api/setup/admin_checklist 200 11 ms (11 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (85 total active threads) Queries in flight: 0
Sep 03 15:21:28 DEBUG metabase.middleware.log :: GET /api/task 200 7 ms (2 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (85 total active threads) Queries in flight: 0
Sep 03 15:21:58 DEBUG metabase.middleware.log :: GET /api/database 200 5 ms (3 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (85 total active threads) Queries in flight: 0
Sep 03 15:21:58 DEBUG metabase.middleware.log :: GET /api/automagic-dashboards/database/3/candidates 200 92 ms (7 DB calls) Jetty threads: 5/50 (1 idle, 0 queued) (85 total active threads) Queries in flight: 0
Sep 03 15:22:01 DEBUG metabase.middleware.log :: GET /api/card/24 200 7 ms (5 DB calls) Jetty threads: 5/50 (1 idle, 0 queued) (85 total active threads) Queries in flight: 0
Sep 03 15:22:01 DEBUG metabase.middleware.log :: GET /api/alert/question/24 200 2 ms (1 DB calls) Jetty threads: 5/50 (1 idle, 0 queued) (85 total active threads) Queries in flight: 0
Sep 03 15:22:04 DEBUG metabase.middleware.log :: POST /api/card/24/query 200 [ASYNC: completed] 3 s (14 DB calls) Jetty threads: 4/50 (1 idle, 0 queued) (85 total active threads) Queries in flight: 0
Sep 03 15:22:04 INFO metabase.middleware.exceptions :: Request canceled before finishing.
Sep 03 15:22:04 DEBUG metabase.middleware.log :: GET /api/user/current 200 4 ms (3 DB calls) Jetty threads: 6/50 (2 idle, 0 queued) (86 total active threads) Queries in flight: 0
Sep 03 15:22:04 DEBUG metabase.middleware.log :: GET /api/session/properties 200 5 ms (1 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (86 total active threads) Queries in flight: 0
Sep 03 15:22:04 DEBUG metabase.middleware.log :: GET /api/database 200 5 ms (3 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (86 total active threads) Queries in flight: 0
Sep 03 15:22:04 DEBUG metabase.middleware.log :: GET /api/setting 200 706 µs (0 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (86 total active threads) Queries in flight: 0

**To Reproduce**
Create a question in SQL, utilising a parameter to set a date range, and a parameter to set a category. 
Set the question type to be Bar+Line (or just Bar), and map the data points so that the date is on the x axis. 
Hover over any of the data points and see that the date on the x axis doesnt match the date in the pop up. 

**Expected behavior**
The two dates should match 

**Screenshots**

**Information about your Metabase Installation:**
- Chrome Version 76.0.3809.132 (Official Build) (64-bit)
- Win 10 
- Your databases: mysql
- Metabase version:0.32.10
- Metabase hosting environment: Docker image on Ubuntu 
- Metabase internal database: postgres

**Severity**
High - it is providing end users with inaccurate data that they believe is accurate. 

**Additional context**
This occurs whether you view the question, or view it in a dashboard or an embedded dashboard. It doesn't appear to be related to any specific date ranges.

**Comment by flamber** [comment] 2019-09-03 17:27
Hi @joebi3 
This is duplicate of #8413, which probably is rooted in #5246
There's work being done currently, to try to squash some of those timezone inconsistencies.

**Comment by mbvictoria** [comment] 2019-09-04 17:15
Going to go ahead and close this, since it's a previously reported issue.

**Closed by mbvictoria** 2019-09-04 17:15 UTC
Labels: Type:Bug
