### ISSUE TITLE
Filters available on custom question but not available in dashboard to be linked

### ISSUE THREAD

**Issue by omkar-work** [metabase/metabase#18944] opened 2021-11-11 05:01 UTC
**Describe the bug**
I  have a custom question. I can apply filters to each column of the question.
I created one more question which is an aggregation of the 1st question and I still can apply filter on all the columns.
But when I add both these custom questions to a dashboard and add a field filter. All the columns are not available to link with the filter.

**To Reproduce**
1. Question with native query - Raw Data
      This question shows 5 columns - a, b, c, d, e
2. Create a custom question with base as Raw Data - Aggregate Data
      summarize - count of rows group by b, c and apply a filter on c
      * On Aggregate Data question, I can apply filter on all 5 columns - a,b,c,d,e
3. Add Raw Data and Aggregate Data to a dashboard. 
     Add a field filter to the dashboard
     For linking this filter to Raw Data and Aggregate Data: 
            none of a,b,c,d,e columns are shown in the drop down for both the cards

**Expected behavior**
All of a,b,c,d,e should be available to be linked with dashboard filters for both the cards

**Screenshots**
Raw Data: 
<img width="1773" alt="image" src="https://user-images.githubusercontent.com/86356654/141239974-27b5af32-c2a8-41cd-9fa1-98c978656cbf.png">
Aggregate Table:
<img width="1768" alt="image" src="https://user-images.githubusercontent.com/86356654/141239999-c255065c-a382-4cfa-9900-0f982834deec.png">
Dashboard:
<img width="1756" alt="image" src="https://user-images.githubusercontent.com/86356654/141240047-a9b422d7-42e6-4695-85c5-e2debfee63aa.png">

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-IN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_265-b01",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_265",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.265-b01",
    "os.name": "Linux",
    "os.version": "4.14.104-95.84.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "athena",
      "mysql",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.12"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.40.3.1",
      "date": "2021-08-26",
      "branch": "release-x.40.x",
      "hash": "0550b86"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

**Comment by flamber** [comment] 2021-11-11 09:19
Duplicate of #6449 / #13186

**Closed by flamber** 2021-11-11 09:19 UTC

**Comment by omkar-work** [comment] 2021-11-12 07:24
It's exactly similar to those issues. I am unable to link any column in a custom question to a field filter in a dashboard.

**Comment by flamber** [comment] 2021-11-12 09:51
@omkar-work Upgrade to the latest release, and try with a database, which is not a third-party driver.
