### ISSUE TITLE
List of values for filter not shown in dashboard with multiple datasources

### ISSUE THREAD

**Issue by petit-pois** [metabase/metabase#9052] opened 2018-11-29 14:22 UTC
After a refresh, the list of values for filter is not shown in dashboard with multiple datasources

Settings:
- Safari 12.0.1
- macOS Sierra 10.12.6
- Druid 0.12.3
- Metabase version: 0.29.3
- Metabase hosting environment: Docker
- Metabase internal database: MySQL MariaDB 5.5.26

Repeatable steps to reproduce the issue:
- Create a dashboard containing 2 cards from 2 different datasources having a common categorical field
- Add a categorical filter to each card with the common categorical field
- Save the dashboard, the filter widget (dropdown menu) does show the list of possible values
- Refresh the dashboard, the filter widget became a text box, no filter value is proposed

![image](https://user-images.githubusercontent.com/17743430/49227867-678d2400-f3ea-11e8-8f41-b7ed25ebc24d.png)

After refresh
<img width="720" alt="image" src="https://user-images.githubusercontent.com/17743430/49227913-812e6b80-f3ea-11e8-829b-3f995209ec1b.png">

**Comment by notrom** [comment] 2019-01-14 21:36
I see the same issue on v0.31.3.

Interestingly, if I use the public link the same dashboard I do get the list of values in the filter.

**Comment by jasongi-actu** [comment] 2019-01-15 01:49
Yep this is the same issue as #8698. Can confirm I'm getting this on 0.31.1
My work around for the moment:

> I have discovered a work around to this, where if you create a second filter that only filters on one of the questions then it magically makes the first filter (filtering on both) appear with a dropdown again. I've had to name these filters IGNORE ME which isn't a great look for our users.

**Comment by flamber** [comment] 2019-02-25 19:27
This looks like a duplicate of #7168 - go and upvote by clicking :+1:

**Comment by jasongi-actu** [comment] 2019-02-25 23:11
> This looks like a duplicate of #7168 - go and upvote by clicking 👍

#7168 is a proposal to include both columns in the list, this is a bug where neither columns appear in the list.

**Comment by flamber** [comment] 2019-02-26 00:38
@jasongi-actu You're right. Duplicate of #8698

**Comment by mazameli** [comment] 2019-11-06 22:31
Closing as duplicate of #8698

**Closed by mazameli** 2019-11-06 22:31 UTC
Labels: Priority:P2, Querying/Parameters & Variables, Reporting/Dashboards, Type:Bug
