### ISSUE TITLE
`Between` filter errors out with min > max 

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16745] opened 2021-06-23 18:54 UTC
**Describe the bug**
Before #16728 it wasn't possible to use `between` filter for longitude/latitude at all. This is already a huge improvement. However, I've run into a few situations that result in an error. Still trying to find the root cause.

**Logs**
`not,Integer greater than zero, X` where `X` is some negative number

**To Reproduce**
1. Open "People" table
2. Click "Summarize" (will open a right sidebar)
3. Open popover with binning options for "Longitude"
4. Choose "Bin every 10 degrees" (or any other specific value)
5. Visualization should render _bars_
6. Click on any of the bars, choose "Zoom in" (to drill through)
7. You should see granularity change to 1 degree and the filter saying `Longitude -100 -90`
8. Click on that filter. You should see this
![image](https://user-images.githubusercontent.com/31325167/123151849-2d7e4480-d464-11eb-82ad-ac891cee0a77.png)
9. Replace -100 (W) with positive value 100 (E)
![image](https://user-images.githubusercontent.com/31325167/123151958-5272b780-d464-11eb-9bd1-779e3206e75b.png)
10. Click "Update filter"
11. Observe an error
![image](https://user-images.githubusercontent.com/31325167/123152073-78985780-d464-11eb-8e38-1d8795eb12a3.png)

console error
```
VisualizationError.jsx:45 error (2) ["not", Array(2)]0: "not"1: (2) ["Integer greater than zero", -190]length: 2__proto__: Array(0)
```

**Expected behavior**
Between filter should work regardless of the range.

**Information about your Metabase Installation:**
local dev, `master`, f3847cb8fd9025f20f39822a073a8c9bf7db3373

**Severity**
?

**Additional context**
I couldn't reproduce it by using filter initially. It _seems_ to only happens after binning, but the weird part is that if you try to use regular filter after that, it will fail as well.

**Comment by flamber** [comment] 2021-06-23 19:19
You get similar error by doing something like this:
![image](https://user-images.githubusercontent.com/1447303/123154508-3d4b5800-d467-11eb-828f-b4873c4ba6b5.png)

<details><summary>Full stacktrace</summary>

```
2021-06-23 21:16:10,056 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 4,
 :started_at #t "2021-06-23T21:16:09.466708+02:00[Europe/Copenhagen]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Output of calculate-num-bins does not match schema: \n\n\t   (not (\"Integer greater than zero\" 0))  \n\n",
   :stacktrace
   ["--> query_processor.middleware.binning$update_binning_strategy_in_inner_query$replace_45722__45723.invoke(binning.clj:209)"
    "mbql.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:47)"
    "mbql.util.match.impl$replace_in_collection.invoke(impl.cljc:38)"
    "query_processor.middleware.binning$update_binning_strategy_in_inner_query$replace_45722__45723.invoke(binning.clj:209)"
    "mbql.util.match.impl$replace_in_collection$iter__17982__17986$fn__17987.invoke(impl.cljc:44)"
    "mbql.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:43)"
    "mbql.util.match.impl$replace_in_collection.invoke(impl.cljc:38)"
    "query_processor.middleware.binning$update_binning_strategy_in_inner_query$replace_45722__45723.invoke(binning.clj:209)"
    "query_processor.middleware.binning$update_binning_strategy_in_inner_query.invokeStatic(binning.clj:209)"
    "query_processor.middleware.binning$update_binning_strategy_in_inner_query.invoke(binning.clj:205)"
    "query_processor.middleware.binning$update_binning_strategy_STAR_.invokeStatic(binning.clj:219)"
    "query_processor.middleware.binning$update_binning_strategy_STAR_.invoke(binning.clj:216)"
    "query_processor.middleware.binning$update_binning_strategy$fn__45736.invoke(binning.clj:227)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__46453.invoke(resolve_fields.clj:34)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__44574.invoke(add_dimension_projections.clj:314)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__44803.invoke(add_implicit_clauses.clj:147)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__49789.invoke(upgrade_field_literals.clj:40)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__45088.invoke(add_source_metadata.clj:123)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__48942.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45296.invoke(auto_bucket_datetimes.clj:147)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46500.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__48750.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46552.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__47301.invoke(expand_macros.clj:184)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__45097.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49742.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48953$fn__48957.invoke(resolve_database_and_driver.clj:31)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48953.invoke(resolve_database_and_driver.clj:25)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47541.invoke(fetch_source_query.clj:274)"
    "query_processor.middleware.store$initialize_store$fn__49751$fn__49752.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__49751.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__49796.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__47677.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44943.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49727.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__46794.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__48839.invoke(process_userland_query.clj:135)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46734.invoke(catch_exceptions.clj:173)"
    "query_processor.reducible$async_qp$qp_STAR___38051$thunk__38052.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___38051.invoke(reducible.clj:109)"
    "query_processor.reducible$sync_qp$qp_STAR___38060$fn__38063.invoke(reducible.clj:135)"
    "query_processor.reducible$sync_qp$qp_STAR___38060.invoke(reducible.clj:134)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:241)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:237)"
    "query_processor$fn__49886$process_query_and_save_execution_BANG___49895$fn__49898.invoke(query_processor.clj:253)"
    "query_processor$fn__49886$process_query_and_save_execution_BANG___49895.invoke(query_processor.clj:245)"
    "query_processor$fn__49930$process_query_and_save_with_max_results_constraints_BANG___49939$fn__49942.invoke(query_processor.clj:265)"
    "query_processor$fn__49930$process_query_and_save_with_max_results_constraints_BANG___49939.invoke(query_processor.clj:258)"
    "api.dataset$run_query_async$fn__56143.invoke(dataset.clj:56)"
    "query_processor.streaming$streaming_response_STAR_$fn__56122$fn__56123.invoke(streaming.clj:72)"
    "query_processor.streaming$streaming_response_STAR_$fn__56122.invoke(streaming.clj:71)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$fn__16071.invoke(streaming_response.clj:84)"],
   :ex-data {:clause [:field 94 {:binning {:strategy :default}}]}}],
 :error_type :invalid-query,
 :json_query
 {:database 4,
  :query
  {:source-table 12,
   :filter ["between" ["field" 94 nil] 2 1],
   :aggregation [["count"]],
   :breakout [["field" 94 {:binning {:strategy "default"}}]]},
  :type "query",
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native nil,
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> query_processor.middleware.binning$fn__45515$calculate_num_bins__45520.invoke(binning.clj:64)"
  "query_processor.middleware.binning$fn__45540$resolve_default_strategy__45545$fn__45546.invoke(binning.clj:78)"
  "query_processor.middleware.binning$fn__45540$resolve_default_strategy__45545.invoke(binning.clj:70)"
  "query_processor.middleware.binning$resolve_options.invokeStatic(binning.clj:160)"
  "query_processor.middleware.binning$resolve_options.invoke(binning.clj:147)"
  "query_processor.middleware.binning$fn__45680$update_binned_field__45685$fn__45698.invoke(binning.clj:195)"
  "query_processor.middleware.binning$fn__45680$update_binned_field__45685.invoke(binning.clj:184)"
  "query_processor.middleware.binning$update_binning_strategy_in_inner_query$replace_45722__45723.invoke(binning.clj:209)"
  "mbql.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:47)"
  "mbql.util.match.impl$replace_in_collection.invoke(impl.cljc:38)"
  "query_processor.middleware.binning$update_binning_strategy_in_inner_query$replace_45722__45723.invoke(binning.clj:209)"
  "mbql.util.match.impl$replace_in_collection$iter__17982__17986$fn__17987.invoke(impl.cljc:44)"
  "mbql.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:43)"
  "mbql.util.match.impl$replace_in_collection.invoke(impl.cljc:38)"
  "query_processor.middleware.binning$update_binning_strategy_in_inner_query$replace_45722__45723.invoke(binning.clj:209)"
  "query_processor.middleware.binning$update_binning_strategy_in_inner_query.invokeStatic(binning.clj:209)"
  "query_processor.middleware.binning$update_binning_strategy_in_inner_query.invoke(binning.clj:205)"
  "query_processor.middleware.binning$update_binning_strategy_STAR_.invokeStatic(binning.clj:219)"
  "query_processor.middleware.binning$update_binning_strategy_STAR_.invoke(binning.clj:216)"
  "query_processor.middleware.binning$update_binning_strategy$fn__45736.invoke(binning.clj:227)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__46453.invoke(resolve_fields.clj:34)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__44574.invoke(add_dimension_projections.clj:314)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__44803.invoke(add_implicit_clauses.clj:147)"
  "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__49789.invoke(upgrade_field_literals.clj:40)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__45088.invoke(add_source_metadata.clj:123)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__48942.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45296.invoke(auto_bucket_datetimes.clj:147)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46500.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48750.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46552.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__47301.invoke(expand_macros.clj:184)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__45097.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49742.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48953$fn__48957.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48953.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47541.invoke(fetch_source_query.clj:274)"
  "query_processor.middleware.store$initialize_store$fn__49751$fn__49752.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__49751.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__49796.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__47677.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44943.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49727.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__46794.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__48839.invoke(process_userland_query.clj:135)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46734.invoke(catch_exceptions.clj:173)"
  "query_processor.reducible$async_qp$qp_STAR___38051$thunk__38052.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___38051.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___38060$fn__38063.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___38060.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:241)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:237)"
  "query_processor$fn__49886$process_query_and_save_execution_BANG___49895$fn__49898.invoke(query_processor.clj:253)"
  "query_processor$fn__49886$process_query_and_save_execution_BANG___49895.invoke(query_processor.clj:245)"
  "query_processor$fn__49930$process_query_and_save_with_max_results_constraints_BANG___49939$fn__49942.invoke(query_processor.clj:265)"
  "query_processor$fn__49930$process_query_and_save_with_max_results_constraints_BANG___49939.invoke(query_processor.clj:258)"
  "api.dataset$run_query_async$fn__56143.invoke(dataset.clj:56)"
  "query_processor.streaming$streaming_response_STAR_$fn__56122$fn__56123.invoke(streaming.clj:72)"
  "query_processor.streaming$streaming_response_STAR_$fn__56122.invoke(streaming.clj:71)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$fn__16071.invoke(streaming_response.clj:84)"],
 :context :ad-hoc,
 :error (not ("Integer greater than zero" 0)),
 :row_count 0,
 :running_time 0,
 :preprocessed nil,
 :ex-data {:type :schema.core/error, :value 0, :error (not ("Integer greater than zero" 0))},
 :data {:rows [], :cols []}}
```

</details>

It's because there's some logic in the (location only?) binning, which does a `max - min`, and that is not expected to be below 0.
Likely the same root cause as #13914.

**Comment by camsaul** [comment] 2022-03-12 01:16
I don't know what behavior you guys expect to happen here... 

```sql
SELECT * FROM table WHERE lon BETWEEN 100 and -90
``` 

is going to return nothing because nothing is `> 100` AND `<= -90`. 

Unless you think we should have some special logic in here to change 

```sql
WHERE lon BETWEEN 100 and -90
``` 

to 

```sql
WHERE (lon BETWEEN 100 AND 180) OR (log BETWEEN -90 AND -180)
```

Is that what you meant? Or do you just want me to fix the error here?

SQL `BETWEEN` is `BETWEEN <min> AND <max>`, and there's an explicit expectation there and in MBQL `:between` that `min <= max`... maybe we just need to generate an error here.

**Comment by camsaul** [comment] 2022-03-12 02:01
Here's a failing backend test:

```clj
(deftest bin-negative-ranges-test
  (testing "#16745"
    (mt/dataset sample-dataset
      (let [query (mt/mbql-query people
                    {:breakout    [[:field %longitude {:binning {:strategy :bin-width, :bin-width 1}}]]
                     :aggregation [[:count]]
                     :filter      [:between $longitude 100 -90]})]
        (mt/with-native-query-testing-context query
          (is (= :wow
                 (qp/process-query query))))))))
```

Not sure what the actual expected behavior is here (discussion in https://metaboat.slack.com/archives/C01LQQ2UW03/p1647049527602029) so I need to wait for that to get sorted out before I can proceed further

**Comment by flamber** [comment] 2022-03-12 09:18
We should probably just change this to FE issue and show a nice FE message preventing bad input.

**Comment by kulyk** [comment] 2023-11-08 12:28
This doesn't result in errors anymore (tried out #34851), but it would be nice to either validate that the left value is greater than the right value or maybe flip the values.

**Comment by ranquild** [comment] 2023-11-08 13:25
Should we disable the button to add a filter in this case?

**Comment by ranquild** [comment] 2023-11-13 11:33
Fixed by https://github.com/metabase/metabase/pull/35609

**Closed by ranquild** 2023-11-13 11:33 UTC
Labels: Type:Bug, Priority:P3, Querying/Parameters & Variables, .Frontend, Querying/GUI, .Team/QueryProcessor, .Wanted: MLv2, .Team/Query
