### ISSUE TITLE
Removed users can't automatically re-register with LDAP credentials

### ISSUE THREAD

**Issue by lr-sc** [metabase/metabase#5766] opened 2017-08-17 15:03 UTC
User removed through 'People' UI can't login using LDAP credentials anymore, and gets redirected to login form with no noticeable error instead. This is due to the fact that entry for them still exists in `core_user`, but with `is_active` set to 0 - which makes sense when interpreted as disabled user, but is not consistent with the UI. Re-registration works fine if entry is manually removed from DB.

An example of consistent behavior would be to have both disable and remove actions, where for 'disable' the user would still appear, grayed out, in 'People' tab (and shouldn't be able to log in) - while 'remove' would actually remove the user while allowing them to log in (and re-register). Moreover, some feedback for disabled user during login attempt would be useful.

Present in Metabase 0.25.1 and 0.25.2.

**Comment by wwwiiilll** [comment] 2017-08-30 15:07
This is covered by #4936

**Comment by salsakran** [comment] 2017-09-06 22:04
dupe of #4936

**Closed by salsakran** 2017-09-06 22:04 UTC
