### ISSUE TITLE
Dashboards broken if you click "edit dashboard" and then navigate away

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#12516] opened 2020-05-13 02:05 UTC
On `master` (0.36.0-snapshot) I guess the "edit dashboard" page isn't cleaning up the state when it unmounts/you navigate away. When you go back, it fails with the error

```
Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
```

![image](https://user-images.githubusercontent.com/1455846/81763082-34760d80-9483-11ea-80b6-5ce57a1c263b.png)

Steps to repro:

1.  Create a dashboard with a datetime filter
2.  Go to the collection view that contains that dashboard e.g. http://localhost:3000/collection/root?type=dashboard
3.  Navigate to dashboard
4.  Click "edit dashboard"
5.  Click "Edit" on Date Filter. URL changes to http://localhost:3000/dashboard/925?date_filter=thisyear
6.  Click the back button on your browser
7.  Navigate to the dashboard again as in Step 3
8.  Broken! URL is still http://localhost:3000/dashboard/925?date_filter=thisyear

The only way I was able to fix this was by manually editing the URL and taking `?date_filter=thisyear` out.

**Comment by kulyk** [comment] 2021-06-18 13:49
Hi @camsaul @flamber,

Looks like I can't reproduce the issue. When I switch to editing mode and click the filter, I can't see any new URL params in the address bar and it works fine. However, if I e.g. set a default value for a date-time filter, a URL param appears, but I can still navigate here and there without any issues. Attaching the demo below. Please LMK if you can still reproduce the problem

https://user-images.githubusercontent.com/17258145/122570617-9294fd00-d054-11eb-84ab-e5a21726aeec.mov

**Comment by flamber** [comment] 2021-06-18 14:00
I cannot reproduce either - couldn't reproduce initially on the the same `master`.

**Comment by kulyk** [comment] 2021-06-18 14:16
@flamber thank you for double-checking 🙏 Should we then close the issue?

**Comment by flamber** [comment] 2021-06-18 14:58
@kulyk Yeah, let's do that, since there has been so many changes to dashboards now that it might generate a different error anyway, so we wouldn't be able to correlate it anyways.

**Closed by flamber** 2021-06-18 14:58 UTC
Labels: .Frontend, Priority:P2, Reporting/Dashboards, Type:Bug
