### ISSUE TITLE
Redshift queries failing with "Invalid protocol sequence 'P' while in PortalSuspended state."

### ISSUE THREAD

**Issue by peloyeje** [metabase/metabase#29680] opened 2023-03-30 12:25 UTC
**Describe the bug**

Queries that return large number of rows (> 100k) fail with the following error message : "Invalid protocol sequence 'P' while in PortalSuspended state."

Same query runs ok in local IDE (IntelliJ Ultimate with Redshift JDBC driver 2.1.0.1)

A working workaround consists in adding `LIMIT 1000` to the end of the query

**Logs**

Diagnostic info
```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.4.209-116.363.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "athena",
      "postgres",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-03-28",
      "tag": "v0.46.0",
      "branch": "release-x.46.x",
      "hash": "0ca7df3"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

JS logs when the query failed:
```
{
    "database_id":2,
    "started_at":"2023-03-30T12:19:15.037888Z",
    "state":"XX000",
    "json_query":{
        "constraints":{
            "max-results":10000,
            "max-results-bare-rows":2000
        },
        "type":"native",
        "middleware":{
            "js-int-to-string?":true,
            "ignore-cached-results?":false,
            "process-viz-settings?":false
        },
        "native":{
            "query":"<redacted>",
            "template-tags":{
                "business_date":{
                    "id":"8b7005cc-c794-6cba-228b-9796d5b5ae02",
                    "name":"business_date",
                    "display-name":"Business date range",
                    "type":"dimension",
                    "dimension":[
                        "field",
                        601453,
                        null
                    ],
                    "widget-type":"date/range",
                    "default":"2023-03-19~2023-03-23",
                    "required":true
                },
                "user_type":{
                    "id":"5aafc135-1528-bae9-6734-0e307082075f",
                    "name":"user_type",
                    "display-name":"User type (pro/private)",
                    "type":"text"
                },
                "organisation":{
                    "id":"d1418d01-41de-1ab0-567b-7c100cb73de4",
                    "name":"organisation",
                    "display-name":"Organisation",
                    "type":"dimension",
                    "dimension":[
                        "field",
                        298,
                        null
                    ],
                    "widget-type":"string/=",
                    "default":null
                }
            }
        },
        "database":2,
        "parameters":[
            {
                "id":"8b7005cc-c794-6cba-228b-9796d5b5ae02",
                "type":"date/range",
                "value":"2023-03-19~2023-03-23",
                "target":[
                    "dimension",
                    [
                        "template-tag",
                        "business_date"
                    ]
                ]
            }
        ],
        "async?":true,
        "cache-ttl":null
    },
    "status":"failed",
    "class":"class com.amazon.redshift.util.RedshiftException",
    "stacktrace":[
        "com.amazon.redshift.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2607)",
        "com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2275)",
        "com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1880)",
        "com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1872)",
        "com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)",
        "com.amazon.redshift.jdbc.RedshiftStatementImpl.executeInternal(RedshiftStatementImpl.java:514)",
        "com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:435)",
        "com.amazon.redshift.jdbc.RedshiftPreparedStatement.executeWithFlags(RedshiftPreparedStatement.java:200)",
        "com.amazon.redshift.jdbc.TypeInfoCache.getRSType(TypeInfoCache.java:494)",
        "com.amazon.redshift.jdbc.RedshiftResultSetMetaDataImpl.getRSType(RedshiftResultSetMetaDataImpl.java:443)",
        "com.amazon.redshift.jdbc.RedshiftResultSetMetaDataImpl.getColumnTypeName(RedshiftResultSetMetaDataImpl.java:357)",
        "--> driver.sql_jdbc.execute$fn__71772$fn__71773.invoke(execute.clj:467)",
        "driver.sql_jdbc.execute$fn__71772.invokeStatic(execute.clj:464)",
        "driver.sql_jdbc.execute$fn__71772.invoke(execute.clj:462)",
        "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:512)",
        "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:489)",
        "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:497)",
        "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:489)",
        "driver.sql_jdbc$fn__105074.invokeStatic(sql_jdbc.clj:63)",
        "driver.sql_jdbc$fn__105074.invoke(sql_jdbc.clj:61)",
        "query_processor.context$executef.invokeStatic(context.clj:60)",
        "query_processor.context$executef.invoke(context.clj:49)",
        "query_processor.context.default$default_runf.invokeStatic(default.clj:68)",
        "query_processor.context.default$default_runf.invoke(default.clj:66)",
        "query_processor.context$runf.invokeStatic(context.clj:46)",
        "query_processor.context$runf.invoke(context.clj:40)",
        "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:15)",
        "query_processor.reducible$identity_qp.invoke(reducible.clj:12)",
        "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___69168.invoke(cache.clj:224)",
        "query_processor.middleware.permissions$check_query_permissions$fn__64640.invoke(permissions.clj:126)",
        "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__68059.invoke(mbql_to_native.clj:24)",
        "query_processor$fn__70687$combined_post_process__70692$combined_post_process_STAR___70693.invoke(query_processor.clj:243)",
        "query_processor$fn__70687$combined_pre_process__70688$combined_pre_process_STAR___70689.invoke(query_processor.clj:240)",
        "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__69079$fn__69084.invoke(resolve_database_and_driver.clj:36)",
        "driver$do_with_driver.invokeStatic(driver.clj:90)",
        "driver$do_with_driver.invoke(driver.clj:86)",
        "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__69079.invoke(resolve_database_and_driver.clj:35)",
        "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__64949.invoke(fetch_source_query.clj:310)",
        "query_processor.middleware.store$initialize_store$fn__65127$fn__65128.invoke(store.clj:12)",
        "query_processor.store$do_with_store.invokeStatic(store.clj:47)",
        "query_processor.store$do_with_store.invoke(store.clj:41)",
        "query_processor.middleware.store$initialize_store$fn__65127.invoke(store.clj:11)",
        "query_processor.middleware.normalize_query$normalize$fn__69368.invoke(normalize_query.clj:25)",
        "query_processor.middleware.constraints$add_default_userland_constraints$fn__66305.invoke(constraints.clj:54)",
        "query_processor.middleware.process_userland_query$process_userland_query$fn__69304.invoke(process_userland_query.clj:150)",
        "query_processor.middleware.catch_exceptions$catch_exceptions$fn__69681.invoke(catch_exceptions.clj:171)",
        "query_processor.reducible$async_qp$qp_STAR___59455$thunk__59457.invoke(reducible.clj:103)",
        "query_processor.reducible$async_qp$qp_STAR___59455$fn__59459.invoke(reducible.clj:108)"
    ],
    "card_id":274,
    "context":"question",
    "error":"ERROR: Invalid protocol sequence 'P' while in PortalSuspended state.",
    "row_count":0,
    "running_time":0,
    "data":{
        "rows":[
            
        ],
        "cols":[
            
        ]
    }
}
```

Redshift version: PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.48004

**To Reproduce**

Not sure, I guess queries that return a large number of rows should trigger this behavior

**Expected behavior**
Query runs successfully and first x result rows are displayed

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?

High because users can't load the full result set

**Comment by paoliniluis** [comment] 2023-03-30 13:52
Hi, I'm not able to reproduce this, as Metabase will always return either 2000 rows on table views or 10000 on aggregated charts. Is there any way you're triggering this?

**Comment by peloyeje** [comment] 2023-03-31 07:47
Hi @paoliniluis,
After some testing it seems that this error is triggered when I'm using the following field filter inside a CTE:
- linked field: "date" field inside a dim table
- filter widget type: date range

The resulting compiled query snippet:
```sql
  WHERE
    "dim_table"."date_field" BETWEEN $ 1
    AND $ 2
```

**Comment by paoliniluis** [comment] 2024-03-11 13:27
@peloyeje coming back to this, is this still valid in v48?

**Comment by paoliniluis** [comment] 2024-04-24 17:07
@peloyeje is this still relevant in v49? otherwise I'll close it

**Closed** 2024-05-16 01:32 UTC
Labels: Database/Redshift, .Needs Triage
