### ISSUE TITLE
Sending a test email can result in a 403 page redirect

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1644] opened 2015-12-05 02:28 UTC
Jeff tried to send himself a 3 question pulse and got a 403 page.

Tried to repo with my account (an admin account) and it sent correctly. Repro'd with a normal user account and got a 403 screen.

**Comment by agilliland** [comment] 2015-12-05 18:02
closing as a dupe of #1637

**Closed by agilliland** 2015-12-05 18:02 UTC
Labels: bug
