### ISSUE TITLE
Issues sorting ascending/descending rows

### ISSUE THREAD

**Issue by stxyzth** [metabase/metabase#10030] opened 2019-05-23 15:42 UTC
I am encountering an issue where sorting (Ascending & Descending) are not working properly. Picture has been attached of the rows being sorted by ascending for the "state" column.

![Hd7l7NSA](https://user-images.githubusercontent.com/8493287/58266104-50b80080-7d81-11e9-9ee7-7b153afca996.png)

This is just one example column I want to sort, eventually I'll want to sort rows of single columns on 300+ column schema but any column I try to sort just isn't sorting correctly.

Details:
- Your browser and the version: Chrome 74.0.3729.131
- Your operating system: MacOS Mojave 10.14.2
- Your databases: Druid
- Metabase version: 0.32.4
- Metabase hosting environment: Amazon Linux 2
- Metabase internal database: MySQL

**Comment by flamber** [comment] 2019-05-23 16:31
Hi @stxyzth 
I think there's an issue with sorting on Druid - it was reported in #9273

**Comment by stxyzth** [comment] 2019-05-23 16:37
Thanks @flamber - read over that prior but wasn't entirely sure if the bug got captured fully given that the end conversation was around column name sorting instead. I'll wait to see if someone from metbase will close and keep as a reference

**Comment by stxyzth** [comment] 2019-05-23 16:45
The PR stating the potential fix was merged to `master` 30th Jan: https://github.com/metabase/metabase/pull/9343

My current metabase version was released 10th April so based on that I doubt the row sorting issue was fixed, this can likely be closed and just merge with #9273 to confirm that the bug has indeed not been fixed.

**Comment by salsakran** [comment] 2019-06-05 01:22
dupe of #9273

**Closed by salsakran** 2019-06-05 01:22 UTC
