### ISSUE TITLE
[Actions] - Add option to use HTTP requests

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#39450] opened 2024-03-01 14:38 UTC
**Describe the solution you'd like**
Since we already support Actions, which right now consist of simple SQL Insert, Update or Delete. The ask here is to enhance the Action functionality to support simple HTTP requests like GET/PUT

**Describe alternatives you've considered**
None

**Additional context**
Nothing major, just a nice to have

**Comment by dahyeik** [comment] 2024-04-05 17:56
Duplicate of https://github.com/metabase/metabase/issues/35195

**Closed** 2024-04-05 20:54 UTC
Labels: Priority:P3, Type:New Feature, Querying/Actions
