### ISSUE TITLE
Axis off by one error in months

### ISSUE THREAD

**Issue by zekenie** [metabase/metabase#11165] opened 2019-10-17 18:42 UTC
**Describe the bug**
When we make a report grouped by a time field, we sometimes get a month duplicated in axis space, but not chart space. See below. On the axis, march appears twice, but when you hover over the data, its only there once.

![image](https://user-images.githubusercontent.com/962281/67037718-b1a2f500-f0e3-11e9-8225-b871cec7719c.png)
![image](https://user-images.githubusercontent.com/962281/67037768-c7b0b580-f0e3-11e9-9691-4f99a4e0fcf2.png)
![image](https://user-images.githubusercontent.com/962281/67037784-cd0e0000-f0e3-11e9-8b2d-9021901015bf.png)

We are on version 0.33.3

**Comment by mazameli** [comment] 2019-10-17 19:04
I believe this is a duplicate of #5916, which we are working on fixing along with various other timezone issues. Let me know if you think this is a different issue than that @zekenie.

**Closed by mazameli** 2019-10-17 19:04 UTC
Labels: .Duplicate, Type:Bug
