### ISSUE TITLE
Permission error on saved

### ISSUE THREAD

**Issue by GabKlein** [metabase/metabase#6739] opened 2018-01-22 12:28 UTC
As I was updating permissions by going back and forth in all different permission subcategories, I selected limited access to "Saved questions".

When I tried to save, I've got an error and the section "Saved questions" was not present anymore in the "Permissions databases list"

Version: 0.27.2
Backend: Postgresql
Logs: 

```
Jan 22 11:28:43 ERROR metabase.middleware :: PUT /api/permissions/graph 500 (1 ms) (0 DB calls)
{:type :schema.core/error,
:schema
[{:schema
{:revision Int,
:groups
{(constrained Int "Integer greater than zero")
{(constrained Int "Integer greater than zero")
(constrained
{(optional-key :native) (enum :read :write :none),
(optional-key :schemas) (cond-pre (enum :all :none) {Str (cond-pre (enum :all :none) {(constrained Int "Integer greater than zero") (enum :all :none)})})}
"DB permissions with a valid combination of values for :native and :schemas")}}},
:optional? false,
:name new-graph}],
:value
[{:revision 14,
:groups
{1 {2 {:native :none, :schemas :none}, 3 {:native :none, :schemas :none}, 4 {:native :none, :schemas :none}, 5 {:native :none, :schemas :none}},
2 {2 {:native :write, :schemas :all}, 3 {:native :write, :schemas :all}, 4 {:native :write, :schemas :all}, 5 {:native :write, :schemas :all}},
3 {2 {:native :write, :schemas :all}, 3 {:native :write, :schemas :all}, 4 {:native :write, :schemas :all}, 5 {:native :write, :schemas :all}},
4 {2 {:native :read, :schemas :all}, 3 {:native :read, :schemas :all}, 4 {:native :read, :schemas :all}, 5 {:native :read, :schemas :all}, -1337 {:native :read, :schemas :all}},
5 {2 {:native :read, :schemas :all}, 3 {:native :read, :schemas :all}, 4 {:native :read, :schemas :all}, 5 {:native :read, :schemas :all}, -1337 {:native :read, :schemas :all}},
6 {2 {:native :read, :schemas :all}, 3 {:native :read, :schemas :all}, 4 {:native :read, :schemas :all}, 5 {:native :read, :schemas :all}, -1337 {:native :read, :schemas :all}},
7 {2 {:native :read, :schemas :all}, 3 {:native :read, :schemas :all}, 4 {:native :read, :schemas :all}, 5 {:native :read, :schemas :all}, -1337 {:native :read, :schemas :all}}}}],
:error
[(named {:groups {4 {(not ("Integer greater than zero" -1337)) invalid-key}, 5 {(not ("Integer greater than zero" -1337)) invalid-key}, 6 {(not ("Integer greater than zero" -1337)) invalid-key}, 7 {(not ("Integer greater than zero" -1337)) invalid-key}}} new-graph)],
:message
"Input to update-graph! does not match schema: \n\n\t [(named {:groups {4 {(not (\"Integer greater than zero\" -1337)) invalid-key}, 5 {(not (\"Integer greater than zero\" -1337)) invalid-key}, 6 {(not (\"Integer greater than zero\" -1337)) invalid-key}, 7 {(not (\"Integer greater than zero\" -1337)) invalid-key}}} new-graph)] \n\n",
:stacktrace
["models.permissions$fn__21775$update_graph_BANG___21784.invoke(permissions.clj:485)"
"api.permissions$fn__42676$fn__42678.invoke(permissions.clj:73)"
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:248)"
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:243)"
"api.permissions$fn__42676.invokeStatic(permissions.clj:61)"
"api.permissions$fn__42676.invoke(permissions.clj:61)"
"middleware$enforce_authentication$fn__31785.invoke(middleware.clj:122)"
"api.routes$fn__45016.invokeStatic(routes.clj:76)"
"api.routes$fn__45016.invoke(routes.clj:76)"
"routes$fn__45721$fn__45722.doInvoke(routes.clj:101)"
"routes$fn__45721.invokeStatic(routes.clj:97)"
"routes$fn__45721.invoke(routes.clj:97)"
"middleware$log_api_call$fn__31884$fn__31886.invoke(middleware.clj:330)"
"middleware$log_api_call$fn__31884.invoke(middleware.clj:329)"
"middleware$add_security_headers$fn__31834.invoke(middleware.clj:245)"
"middleware$bind_current_user$fn__31789.invoke(middleware.clj:142)"
"middleware$maybe_set_site_url$fn__31838.invoke(middleware.clj:268)"]}

Jan 22 11:28:48 ERROR metabase.middleware :: PUT /api/permissions/graph 500 (957 µs) (0 DB calls)
{:type :schema.core/error,
:schema
[{:schema
{:revision Int,
:groups
{(constrained Int "Integer greater than zero")
{(constrained Int "Integer greater than zero")
(constrained
{(optional-key :native) (enum :read :write :none),
(optional-key :schemas) (cond-pre (enum :all :none) {Str (cond-pre (enum :all :none) {(constrained Int "Integer greater than zero") (enum :all :none)})})}
"DB permissions with a valid combination of values for :native and :schemas")}}},
:optional? false,
:name new-graph}],
:value
[{:revision 14,
:groups
{1 {2 {:native :none, :schemas :none}, 3 {:native :none, :schemas :none}, 4 {:native :none, :schemas :none}, 5 {:native :none, :schemas :none}},
2 {2 {:native :write, :schemas :all}, 3 {:native :write, :schemas :all}, 4 {:native :write, :schemas :all}, 5 {:native :write, :schemas :all}},
3 {2 {:native :write, :schemas :all}, 3 {:native :write, :schemas :all}, 4 {:native :write, :schemas :all}, 5 {:native :write, :schemas :all}},
4 {2 {:native :read, :schemas :all}, 3 {:native :read, :schemas :all}, 4 {:native :read, :schemas :all}, 5 {:native :read, :schemas :all}, -1337 {:native :read, :schemas :all}},
5 {2 {:native :read, :schemas :all}, 3 {:native :read, :schemas :all}, 4 {:native :read, :schemas :all}, 5 {:native :read, :schemas :all}, -1337 {:native :read, :schemas :all}},
6 {2 {:native :read, :schemas :all}, 3 {:native :read, :schemas :all}, 4 {:native :read, :schemas :all}, 5 {:native :read, :schemas :all}, -1337 {:native :read, :schemas :all}},
7 {2 {:native :read, :schemas :all}, 3 {:native :read, :schemas :all}, 4 {:native :read, :schemas :all}, 5 {:native :read, :schemas :all}, -1337 {:native :read, :schemas :all}}}}],
:error
[(named {:groups {4 {(not ("Integer greater than zero" -1337)) invalid-key}, 5 {(not ("Integer greater than zero" -1337)) invalid-key}, 6 {(not ("Integer greater than zero" -1337)) invalid-key}, 7 {(not ("Integer greater than zero" -1337)) invalid-key}}} new-graph)],
:message
"Input to update-graph! does not match schema: \n\n\t [(named {:groups {4 {(not (\"Integer greater than zero\" -1337)) invalid-key}, 5 {(not (\"Integer greater than zero\" -1337)) invalid-key}, 6 {(not (\"Integer greater than zero\" -1337)) invalid-key}, 7 {(not (\"Integer greater than zero\" -1337)) invalid-key}}} new-graph)] \n\n",
:stacktrace
["models.permissions$fn__21775$update_graph_BANG___21784.invoke(permissions.clj:485)"
"api.permissions$fn__42676$fn__42678.invoke(permissions.clj:73)"
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:248)"
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:243)"
"api.permissions$fn__42676.invokeStatic(permissions.clj:61)"
"api.permissions$fn__42676.invoke(permissions.clj:61)"
"middleware$enforce_authentication$fn__31785.invoke(middleware.clj:122)"
"api.routes$fn__45016.invokeStatic(routes.clj:76)"
"api.routes$fn__45016.invoke(routes.clj:76)"
"routes$fn__45721$fn__45722.doInvoke(routes.clj:101)"
"routes$fn__45721.invokeStatic(routes.clj:97)"
"routes$fn__45721.invoke(routes.clj:97)"
"middleware$log_api_call$fn__31884$fn__31886.invoke(middleware.clj:330)"
"middleware$log_api_call$fn__31884.invoke(middleware.clj:329)"
"middleware$add_security_headers$fn__31834.invoke(middleware.clj:245)"
"middleware$bind_current_user$fn__31789.invoke(middleware.clj:142)"
"middleware$maybe_set_site_url$fn__31838.invoke(middleware.clj:268)"]}

Jan 22 11:28:57 ERROR metabase.middleware :: PUT /api/permissions/graph 500 (952 µs) (0 DB calls)
{:type :schema.core/error,
:schema
[{:schema
{:revision Int,
:groups
{(constrained Int "Integer greater than zero")
{(constrained Int "Integer greater than zero")
(constrained
{(optional-key :native) (enum :read :write :none),
(optional-key :schemas) (cond-pre (enum :all :none) {Str (cond-pre (enum :all :none) {(constrained Int "Integer greater than zero") (enum :all :none)})})}
"DB permissions with a valid combination of values for :native and :schemas")}}},
:optional? false,
:name new-graph}],
:value
[{:revision 14,
:groups
{1 {2 {:native :none, :schemas :none}, 3 {:native :none, :schemas :none}, 4 {:native :none, :schemas :none}, 5 {:native :none, :schemas :none}},
2 {2 {:native :write, :schemas :all}, 3 {:native :write, :schemas :all}, 4 {:native :write, :schemas :all}, 5 {:native :write, :schemas :all}},
3 {2 {:native :write, :schemas :all}, 3 {:native :write, :schemas :all}, 4 {:native :write, :schemas :all}, 5 {:native :write, :schemas :all}},
4 {2 {:native :read, :schemas :all}, 3 {:native :read, :schemas :all}, 4 {:native :read, :schemas :all}, 5 {:native :read, :schemas :all}, -1337 {:native :read, :schemas :all}},
5 {2 {:native :read, :schemas :all}, 3 {:native :read, :schemas :all}, 4 {:native :read, :schemas :all}, 5 {:native :read, :schemas :all}, -1337 {:native :read, :schemas :all}},
6 {2 {:native :read, :schemas :all}, 3 {:native :read, :schemas :all}, 4 {:native :read, :schemas :all}, 5 {:native :read, :schemas :all}, -1337 {:native :read, :schemas :all}},
7 {2 {:native :read, :schemas :all}, 3 {:native :read, :schemas :all}, 4 {:native :read, :schemas :all}, 5 {:native :read, :schemas :all}, -1337 {:native :read, :schemas :all}}}}],
:error
[(named {:groups {4 {(not ("Integer greater than zero" -1337)) invalid-key}, 5 {(not ("Integer greater than zero" -1337)) invalid-key}, 6 {(not ("Integer greater than zero" -1337)) invalid-key}, 7 {(not ("Integer greater than zero" -1337)) invalid-key}}} new-graph)],
:message
"Input to update-graph! does not match schema: \n\n\t [(named {:groups {4 {(not (\"Integer greater than zero\" -1337)) invalid-key}, 5 {(not (\"Integer greater than zero\" -1337)) invalid-key}, 6 {(not (\"Integer greater than zero\" -1337)) invalid-key}, 7 {(not (\"Integer greater than zero\" -1337)) invalid-key}}} new-graph)] \n\n",
:stacktrace
["models.permissions$fn__21775$update_graph_BANG___21784.invoke(permissions.clj:485)"
"api.permissions$fn__42676$fn__42678.invoke(permissions.clj:73)"
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:248)"
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:243)"
"api.permissions$fn__42676.invokeStatic(permissions.clj:61)"
"api.permissions$fn__42676.invoke(permissions.clj:61)"
"middleware$enforce_authentication$fn__31785.invoke(middleware.clj:122)"
"api.routes$fn__45016.invokeStatic(routes.clj:76)"
"api.routes$fn__45016.invoke(routes.clj:76)"
"routes$fn__45721$fn__45722.doInvoke(routes.clj:101)"
"routes$fn__45721.invokeStatic(routes.clj:97)"
"routes$fn__45721.invoke(routes.clj:97)"
"middleware$log_api_call$fn__31884$fn__31886.invoke(middleware.clj:330)"
"middleware$log_api_call$fn__31884.invoke(middleware.clj:329)"
"middleware$add_security_headers$fn__31834.invoke(middleware.clj:245)"
"middleware$bind_current_user$fn__31789.invoke(middleware.clj:142)"
"middleware$maybe_set_site_url$fn__31838.invoke(middleware.clj:268)"]}
```

**Comment by camsaul** [comment] 2018-04-09 22:31
This is a duplicate of #5617. @GabKlein, the Saved Questions "database" was never supposed to show up in the Edit Permissions page in the first place, which is why it disappeared after the page was reloaded. We have an open issue, #5610, to add some way for you to edit permissions for Saved Questions

**Closed by camsaul** 2018-04-09 22:31 UTC
Labels: Bug, Permissions, Priority/P2
