### ISSUE TITLE
Column not recognized if strftime() is part of VIEW (SQLite tested only)

### ISSUE THREAD

**Issue by kezyr** [metabase/metabase#12191] opened 2020-03-25 14:37 UTC
I have SQLite database, table "cmd". I create VIEW in sqlite3 shell by this commands:
```
sqlite> create view v_src as select id, strftime('%s', filetime) from src;
sqlite> select strftime('%s','2020-03-01 12:20:35');
1583065235
sqlite> select * from v_src;
1|1581775594
```

This kind of VIEW Metabase will not recognize (I see no columns in Data Model). And if this view is part of database then it will not recognize also other views (created later) even they dont use strftime() function inside.

This is in from log after "Sync-database schema now".

```
[a76ff707-0d97-46ff-9320-90fbd480b4d5] 2020-03-25T15:30:54+01:00 INFO metabase.sync.util STARTING: step 'sync-fields' for sqlite Database 39 'db3'
[a76ff707-0d97-46ff-9320-90fbd480b4d5] 2020-03-25T15:30:54+01:00 WARN metabase.driver.sql-jdbc.sync Don't know how to map column type '' to a Field base_type, falling back to :type/*.
[a76ff707-0d97-46ff-9320-90fbd480b4d5] 2020-03-25T15:30:54+01:00 ERROR metabase.sync.util Error syncing Fields for Table 'Table 99 'v_src'': Output of table-metadata does not match schema:

{:fields #{{:database-type (not ("Non-blank string" ""))}}}
```

Tables and views without using strftime() inside works well.

```
{
  "browser-info": {
    "language": "cs-CZ",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_241-b07",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_241",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.241-b07",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "cs",
    "user.timezone": "Europe/Prague"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlite"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.3",
      "date": "2020-02-25",
      "branch": "release-0.34.x",
      "hash": "1a83edb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2020-03-27 12:23
I'm fairly sure this would be fixed by PR #11358.

**Comment by camsaul** [comment] 2020-07-16 17:24
This is fundamentally the same issue as #12191, merging into that one
 
Duplicate of #12191

**Comment by camsaul** [comment] 2020-07-16 17:24
Duplicate of #12547

**Closed by camsaul** 2020-07-16 17:24 UTC
Labels: Administration/Metadata & Sync, Database/SQLite, Type:Bug
