### ISSUE TITLE
Pass filter values not the same in the destination dashboard

### ISSUE THREAD

**Issue by sleanodlh** [metabase/metabase#19139] opened 2021-11-30 16:51 UTC
**Describe the bug**
I assigned multiple values to a filter passed the values to linked dashboard.
The values are not the same.

**To Reproduce**
1. Create a temporary table
CREATE TABLE tmp (
FiscalYear VARCHAR(4),
Mon VARCHAR(50),
Quantity INT (11)
);

2. Add values to the table
INSERT INTO tmp VALUES ('2021','January',100);
INSERT INTO tmp VALUES ('2021','January',150);
INSERT INTO tmp VALUES ('2021','February',200);
INSERT INTO tmp VALUES ('2021','March',150);
INSERT INTO tmp VALUES ('2020','January',300);
INSERT INTO tmp VALUES ('2020','February',200);
INSERT INTO tmp VALUES ('2020','March',100);
INSERT INTO tmp VALUES ('2020','March',300);

3. Create a question out of the table (Question1)
3.1 Make it a graph

4. Add Dashboard 1 (DB1)
4.1 Add the Question to DB1
4.2 Add Filters
4.2.1 Fiscal Year assign to Fiscal Year
4.2.2 Month assign to Mon

5. Create Dashboard 2 (DB2)
5.1 Add the Question to DB2
5.2 Add Filters
5.2.1 Fiscal Year assign to Fiscal Year
5.2.2 Month assign to Mon

6. Edit "Click Behavior" of the question
   6.1 Select Go to a customer destination
      6.1.1 Link to Dashboard
      6.1.2 Select DB2
  6.2 "Pass values to this dashboard's filters (optional)
     FiscalYear to FiscalYear
     Month to Month

7.  Test Filters
7.1 Add 2021 and 2022 in the Fiscal Year Filter (2 selections)
7.2 Add May June July and August (4 selections)
7.3 Click the graph to be directed to another dashboard

**Expected behavior**
The same value(s) shall be forwarded to the destination dashboard

**Screenshots**

Case 1 when passing Month (values are passed as a single parameter):
Main Dashboard
![image](https://user-images.githubusercontent.com/95237076/144073539-8b867109-e9a7-4a8e-ad0c-037a35512580.png)

Value Forwarded to another dashboard
![image](https://user-images.githubusercontent.com/95237076/144073698-f3407f24-f175-4066-9c67-5cd1337c0e92.png)

Case 2 when passing fiscal year (only 1 value was passed)
Main Dashsboard
![image](https://user-images.githubusercontent.com/95237076/144089600-9bab2e2f-8d3d-4a58-ae8a-4e40e0ff820f.png)

Value Forwarded to another dashboard
![image](https://user-images.githubusercontent.com/95237076/144089711-f83c0dda-ea7d-4f69-8f1b-d799742d2e1e.png)
![image](https://user-images.githubusercontent.com/95237076/144089765-3f11b894-db12-40ab-ab72-ec8df11162b8.png)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "13.0.1+9",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.1",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "13.0.1+9",
    "os.name": "Linux",
    "os.version": "3.10.0-1062.1.2.el7.x86_64",
    "user.language": "en",
    "user.timezone": "America/Chicago"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.4.8-MariaDB-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-11-09",
      "tag": "v0.41.2",
      "branch": "release-x.41.x",
      "hash": "ad599fd"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
I can't proceed with my plan of re-using filters and provide my end-users minimum data entry on filters when navigating from one dashboard to another.

**Comment by flamber** [comment] 2021-11-30 18:39
Duplicate of #17160

**Closed by flamber** 2021-11-30 18:39 UTC
Labels: Type:Bug, .Needs Triage

**Comment by sleanodlh** [comment] 2021-11-30 18:56
I did the workaround stated on other issues but it's still the same 

Click Behavior: 
![image](https://user-images.githubusercontent.com/95237076/144109489-0da06764-95cc-4294-a0cf-a715835a4bbe.png)
Source Dashboard
![image](https://user-images.githubusercontent.com/95237076/144109280-7da9681d-b972-4dba-91ef-760365ac6ff6.png)

New Dashboard
![image](https://user-images.githubusercontent.com/95237076/144109561-f208620a-cc3f-452f-aa55-8a9443a9e83a.png)

**Comment by flamber** [comment] 2021-11-30 19:00
@sleanodlh There's no workaround for that issue - well, not an easy workaround.
