### ISSUE TITLE
Pivot Table: show totals should be configurable so that they could be shown collapsed

### ISSUE THREAD

**Issue by jereh16** [metabase/metabase#16393] opened 2021-06-07 14:57 UTC
If using totals it should be configurable if the rows should be shown collapsed by default.

**Current behaviour:**

![image](https://user-images.githubusercontent.com/489879/121039256-3a870c80-c7b1-11eb-94e7-7da768fd868f.png)

**The table should be shown like this:**

![image](https://user-images.githubusercontent.com/489879/121038946-f5fb7100-c7b0-11eb-96a3-b2a9b9cb5ade.png)

**Comment by flamber** [comment] 2021-06-07 15:01
Duplicate of #15211

**Closed by flamber** 2021-06-07 15:01 UTC
Labels: .Needs Triage, Type:New Feature
