### ISSUE TITLE
Locked parameters in embed dashboards not working

### ISSUE THREAD

**Issue by dgrijuela** [metabase/metabase#20489] opened 2022-02-14 11:06 UTC
The previous Metabase v0.41.6 does not have this bug.

**Describe the bug**

"Embed this dashboard in an application" page not opening for previously created dashboards with locked parameters.

It opens for new dashboards but breaks when changing parameters from "Disabled" to "Locked".

**Logs**

Browser's console logs:

```
TypeError: Cannot read properties of undefined (reading 'some')
    at new i (fields.js:2:27)
    at xo (react-dom.production.min.js:134:171)
    at Ba (react-dom.production.min.js:176:149)
    at xs (react-dom.production.min.js:263:490)
    at yl (react-dom.production.min.js:246:265)
    at ml (react-dom.production.min.js:246:194)
    at ll (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Vi (react-dom.production.min.js:122:325)
```

This function throws the error:
```
export function hasFieldValues(parameter) {
  return parameter.fields.some(field => field.hasFieldValues());
}
```

**To Reproduce**
1. Create a dashboard with one filter
2. Go to Sharing and Embedding
3. Click on Embed this dashboard in an application
4. Change parameter from "Disabled" to "Locked"
5. It will throw take you to the previous page

**Expected behavior**
Parameter gets locked status

**Screenshots**
![bug gif](https://im7.ezgif.com/tmp/ezgif-7-abfce9654c.gif)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "es-ES",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "5.11.0-1022-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.1 (Debian 14.1-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-08",
      "tag": "v0.42.0",
      "branch": "release-x.42.x",
      "hash": "de1264e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
All my usage is with embedded dashboards and locked parameters so this blocks me completely.

**Comment by flamber** [comment] 2022-02-14 11:08
Duplicate of #20357

**Closed by flamber** 2022-02-14 11:08 UTC
Labels: Type:Bug, .Needs Triage
