### ISSUE TITLE
as  today() or  istoday(date) in  function available in custom expression 

### ISSUE THREAD

**Issue by allan-simon** [metabase/metabase#23135] opened 2022-06-03 09:39 UTC
**Is your feature request related to a problem? Please describe.**

People in our team use metabase to track some operational errors  and often the request come "I want to do a custom expression where i can say 'not today(column)' or even better ' < TODAY()'

**Describe the solution you'd like**
To have a function in the custom expression that expose  CURRENT_DATE  or something equivalent

**Describe alternatives you've considered**

We can create a fake question "today" that is a SQL section that does this, a one column one row table , and then to do a full outer join on it, but it's really hackish...

**How important is this feature to you?**

It's not life changing, but it will save people time (currently they use some tricks with "last N days not include today" ) )

**Comment by flamber** [comment] 2022-06-03 09:48
Duplicate of #16870/#19274

**Closed by flamber** 2022-06-03 09:48 UTC
Labels: Type:New Feature, .Needs Triage

**Comment by allan-simon** [comment] 2022-06-03 09:49
https://github.com/metabase/metabase/issues/16870  is about  an operator between 2 columns  same for #19274

**Comment by allan-simon** [comment] 2022-06-03 09:50
both can be implemtend without fixing this issue,  which is to have acces to a value that does not from a column, but from the server itself "current_date"

**Comment by allan-simon** [comment] 2022-06-03 09:51
@flamber  so i think you went a bit fast on closing this one

**Comment by flamber** [comment] 2022-06-03 09:57
@allan-simon The Custom Expressions are Metabase functions, not the same as whatever your database does. We are working on implementing something similar to `current_date`, which is required for the two issues I linked.

**Comment by allan-simon** [comment] 2022-06-03 10:25
@flamber I understand that custom expressions is an abstraction layer, but I didn't know , as it was not stated in the linked ticket, that an underlying requirement would be to implement a "current_date" function into the custom expressions layer

thank for taking the time to explain me :)

**Comment by allan-simon** [comment] 2022-06-03 10:25
at first I opened it , because i found the linked issue and it was specifically written 

> Note: If you want a different function, then create a separate feature request for that. This issue is only about date difference
