### ISSUE TITLE
Raw queries with "ON" datefilter are broken for Druid [Regression]

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#6290] opened 2017-10-28 11:21 UTC
Hi,

Since metabase 0.26.2, there is an issue with raw queries that have a filter set to ON specific date or time. When filter "on XX/xx/2017" is added only 1 record (i guess first) is shown in the "details"/"1 record" format instead of a table with all records.
This does not happen if filter is changed to past X days for example or current day.

Database: druid

**Comment by moumny** [comment] 2017-11-09 16:55
Just need to set the timestamp as not entity key but "no special type".
I guess we should make the driver not make the timestamp as primary eky

**Comment by Digma** [comment] 2017-11-14 15:09
I noticed that setting the timestamp as key has the effect of showing it first when showing "Raw data" in metabase. A solution that would keep timestamp as the first row in the table would be nice

**Comment by senior** [comment] 2017-11-15 16:38
@metabase/core-developers  I was able to reproduce this issue. I think it's a visualization bug. I setup an "ON" filter like described on a timestamp that had two results. The resultset coming from the backend included both results, but it looks like the visualization had `isObjectDetail` set to true, which prevents showing the table view. and instead is zoomed in on one row with the object detail view.

**Comment by tlrobinson** [comment] 2018-01-15 15:36
I see. The frontend assumes any time you do a `=` filter on a field marked as a `PK` you would get a single record because, well, you filtered on a primary key. However, we do an implicit `day` bucketing on `=` filters for time fields, so that's not necessarily true.

Possible solutions:
1. check the number of rows, however, currently the code that detects the "mode" does so purely based on the question definition, not the results
2. exclude date fields that happen to PKs from the object detail mode criteria

**Comment by tlrobinson** [comment] 2018-01-19 08:25
Ok, so as I understand it Druid doesn't really have primary keys, even though we're marking `timestamp` as one, since it's normally the closest thing we have to a PK (although our sample Druid dataset does have an `id` column, but I'm guessing that's not common in Druid schemas?). It's entirely possible you could have more than one event with the same timestamp (which is only millisecond resolution).

Where's what I propose:

1. if you manually add an "On" filter we should use `["=", ["datetime-field", ["field-id", id], "day"], value]`. This **should not** be detected as "object detail", nor should `["=", ["field-id", id], value]` if the field is a date/time, since it's implicitly bucketed by day in most (all?) of our databases.
2. If you drill down using the "View details" and the column also happens to be a date we should use `["=", ["datetime-field", ["field-id", id], "default"], value]`, since as mentioned above `["=", ["field-id", id], value]` implicitly buckets by day.

That **should** be detected as "object detail" if the field is marked as a PK, **unless** the query results also happen to have more than one row. As a result, it may be impossible to view "object detail" for certain records in Druid (or other dbs that try to use non-unique timestamps as PKs), but that's better than silently showing the first of more than one, which may not actually be the one you clicked.

Or we could just stop marking `timestamp` as a PK?

**Comment by Digma** [comment] 2018-01-19 08:30
@tlrobinson Thanks for having a look. Indeed with druid there are no such thing as a unique kay (or a unique key would be the concatenation of all "dimensions" including timestamp)

> Or we could just stop marking timestamp as a PK?

That is what we did on our side. We removed the classification of timestamp as a PK. It has worked pretty well so far and we did not notice other issues. One small thing our user complained about was that the timestamp was not anymore the first field showing up in the "Raw data" view (so they had to change the order of the raw data table manually everytime which was a bit painful). Given Druid is really time-series oriented, I think having the timestamp showing up first is a good practice. Is there a way to keep / reorder column to have timestamp a the first one automatically?

**Comment by tlrobinson** [comment] 2018-01-22 07:12
By the way, the original issue can be reproduced on any database, not just Druid, by marking a DateTime field as "Entity Key" (i.e. PK)

**Comment by senior** [comment] 2018-01-30 16:01
Sounds like the real fix for this isn't on the frontend as I originally thought, but something we should change on the backend. Quote from @salsakran on #6726 

> imo this entire PR can be replaced by removing that assignment in the druid driver (?) and forcing a re-classification in the next version.

I'll take a look at the backend fix for this.

**Closed** 2020-05-19 19:32 UTC
Labels: .Backend, Database/Druid, Priority:P1, Type:Bug
