### ISSUE TITLE
Week start on Metabase

### ISSUE THREAD

**Issue by mnahta** [metabase/metabase#16287] opened 2021-05-31 01:16 UTC
**Describe the bug**
Week start is always 7 despite changing it on admin > settings >localization to Monday (week start =1 ) and on snowflake.

I am using Metabase cloud.

**Expected behavior**
Week start should be 1 (or Monday)

**Information about your Metabase Installation:**
Metabase cloud. Chrome.

**Comment by flamber** [comment] 2021-05-31 09:35
Hi @mnahta 
Please include "Diagnostic Info" from Admin > Troubleshooting.
I'm seeing a correct change based on "First day of the week", when using the GUI.
Can you include more details or an example of how it looks with Sunday and Monday set?
Sounds like a duplicate of #16114

**Comment by mnahta** [comment] 2021-05-31 16:27
Sure. This is a sample chart:

![image](https://user-images.githubusercontent.com/12686965/120220851-40e61900-c1f2-11eb-9b42-c579792a217b.png)

You can see that week start (May 30) is a Sunday. 

We've put Monday as week start in admin > settings. 
![image](https://user-images.githubusercontent.com/12686965/120220874-50656200-c1f2-11eb-9012-3a53e3aa0b5d.png)

Diagnostic information

`{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.14.219-164.354.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-17",
      "tag": "v1.39.2",
      "branch": "release-x.39.x",
      "hash": "b0d9436"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

**Comment by flamber** [comment] 2021-05-31 16:45
@mnahta Is the question build in the GUI or is it based on SQL?
Have you tried setting the Report Timezone to GMT? See #8804 for more details.

**Comment by flamber** [comment] 2021-06-11 09:32
Closing in favor of #16114/#8804, since it sounds like that's the problem and haven't received more information on how to reproduce.

**Closed by flamber** 2021-06-11 09:32 UTC
Labels: .Needs Triage, Type:Bug
