### ISSUE TITLE
Public dashboards and questions visible to all

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#7505] opened 2018-05-01 05:31 UTC
- Your databases: BigQuery
- Metabase version: 0.26.6
- Metabase internal database: MySQL

Even after migration process correctly assigned `read_permissions` on all the rows in `report_card` table, there are certain questions and dashboards which are still visible to all.

I am trying to figure out what's common between those questions and dashboards but is there any reason for this on the code side?

@camsaul @salsakran 

Steps to recreate:
- Login as user1/group1
- Create a question (with BQ as source table) and add it to a dashboard
- Make dashboard public and try accessing it with user2/group2 who does not have access to that table via permissions (it shows dashboard and questions while it shouldn't)
- Disable public dashboards from admin settings and try accessing from user2/group2 and it will work properly

**Comment by VikramTiwari** [comment] 2018-05-01 06:37
It's happening on all the dashboards which have a public link, their questions are also visible to any user. Strangely enough, it starts following all the permissions as soon as I disable public dashboards from admin settings. Note that I am not disabling an individual dashboard but updating the toggle in admin settings. This makes me think that the value of toggle is causing issues somewhere during permissions check.

**Comment by VikramTiwari** [comment] 2018-05-01 16:14
Will make sure to follow responsible disclosure practices. Might be useful to add a sentence about that in the issue template.

Regarding the issue itself:
Public links are public because of the link that's been generated. It's as secure as the UUID that refers to it. Also, since the UUID can be reset, it's fairly secure. But to say that since there's a link generated, that's why it should be visible to all on the team makes its anonymity kinda useless.

A use case:
- HR puts up a dashboard about employee's performance and creates a public link for execs. The link is shared only with execs and the only HR has access to that table/database.
- Making this dashboard internally public is incorrect

This would totally work if there was another toggle int the public dashboards settings which asked if it's okay to share these dashboards and questions internally.

**Comment by salsakran** [comment] 2018-05-01 23:26
We're going to be completely changing how dashboard visibility works in 0.30 as well. Will close this once that merges/ships.

**Comment by jornh** [comment] 2018-09-20 19:33
@VikramTiwari would be good if you are able to verify if this is fixed in 0.30.x as for you as well. 

See #7974 for recent positive verification findings on a similar report.

**Comment by kdoh** [comment] 2018-10-31 03:34
@salsakran / @VikramTiwari Are we feeling good about closing this due to 0.30 per the previous comments? (thanks as always for the follow up @jornh, you rock).

**Comment by mbvictoria** [comment] 2019-07-01 20:36
Closing - was intended to be closed post 0.30 release.

**Closed by mbvictoria** 2019-07-01 20:36 UTC
Labels: Bug, Permissions, Priority/P1
