### ISSUE TITLE
Revision not inserted after dashboard created

### ISSUE THREAD

**Issue by vinceall** [metabase/metabase#12429] opened 2020-04-30 08:44 UTC
Metabase v0.34.2

**Describe the bug**
Revision not inserted after dashboard created.

**To Reproduce**
1. Create a new dashboard
2. Add a Card to the dashboard
3. Check the revisions
4. Sometimes the popup will be loading forever

**Expected behavior**
Revisions should be seen in the popup

**Screenshots**
![image](https://user-images.githubusercontent.com/7637311/80689721-4f9a6200-8b00-11ea-9d2f-ca01ef29db8e.png)

**Reason**
1. After dashboard is created, a `:dashboard-create` event will be published
2. The `push-revision!` function in metabase.models.revision checks whether the dashboard exists
3. However, the `:dashboard-create` event is published inside a db transaction in `m.api.dashboard`
![image](https://user-images.githubusercontent.com/7637311/80690082-e36c2e00-8b00-11ea-8c83-f1832d0ce95f.png)
4. Unfortunately, if transaction has not been submitted yet, the existence check in step 3 will fail

I'm afraid that there are other similar occasions, we should go through the code and fix them, for now, I fixed it like this and I'm still testing if it works well:
![image](https://user-images.githubusercontent.com/7637311/80690769-def44500-8b01-11ea-89b2-6b0df227f570.png)

**Comment by flamber** [comment] 2020-04-30 08:53
Hi @vinceall 
Which version of Metabase? Please post "Diagnostic Info" from Admin > Troubleshooting.
When you see the loading spinner, are there any errors in the browser console or Metabase log?
Just for reference:
https://github.com/metabase/metabase/blob/edf87bdfd8c2130ab1211d569d2468236b6b36ea/src/metabase/api/dashboard.clj#L77-L84

**Comment by vinceall** [comment] 2020-04-30 09:07
> Hi @vinceall
> Which version of Metabase? Please post "Diagnostic Info" from Admin > Troubleshooting.
> When you see the loading spinner, are there any errors in the browser console or Metabase log?
> Just for reference:
> https://github.com/metabase/metabase/blob/edf87bdfd8c2130ab1211d569d2468236b6b36ea/src/metabase/api/dashboard.clj#L77-L84
Diagnostic info:
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_241-b07",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_241",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.241-b07",
    "os.name": "Linux",
    "os.version": "3.10.0-1062.9.1.el7.x86_64",
    "user.language": "zh",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "impala"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.28-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.2",
      "date": "2020-04-30",
      "branch": "HEAD",
      "hash": "eed8f75"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

Errors in console:
![image](https://user-images.githubusercontent.com/7637311/80692895-d8b39800-8b04-11ea-8f89-b0bfe4ed551e.png)

**Comment by flamber** [comment] 2020-04-30 09:20
@vinceall 
Do you see the same behavior in the latest official release 0.35.3?
Please paste text, since images cannot be searched:
`TypeError: Cannot read property 'common_name' of undefined`

**Comment by vinceall** [comment] 2020-04-30 09:53
> @vinceall
> Do you see the same behavior in the latest official release 0.35.3?
> Please paste text, since images cannot be searched:
> `TypeError: Cannot read property 'common_name' of undefined`

My work is based on v0.34.2 so I didn't try the latest release. Error text is not available due to some reasons, sorry

**Comment by flamber** [comment] 2020-06-18 21:23
Closing, since I have not been able to reproduce on official release.

**Closed by flamber** 2020-06-18 21:23 UTC
Labels: .Unable to Reproduce, Type:Bug
