### ISSUE TITLE
Chart Funnel cutting number on dashboard

### ISSUE THREAD

**Issue by rudaruda** [metabase/metabase#15036] opened 2021-03-02 21:43 UTC
**Describe the bug**
Chart Funnel is cutting number on Dashboard

**Logs**
Not apply

**To Reproduce**
1. Make Funnel question
2. Insert on one dashboard
3. See the dashboard with Funnel
4. See cut numbers

**Expected behavior**
See all numbers on Funnel.

**Screenshots**
![image](https://user-images.githubusercontent.com/9773420/109718472-2619ef00-7b86-11eb-98dc-6533e71109cd.png)

**Information about your Metabase Installation:**
- Your browser and the version: Firefox 86.0 (64-bit)
- Your operating system: Windows 10.1809
- Your databases: Postgres, MongoDB
- Metabase version: v0.38.0
- Metabase hosting environment: (e.x. Jar-file on Windows)
- Metabase internal database: Postgres

**Severity**
Low/Average, because, I cannot present the number correctly or clearly.

**Comment by flamber** [comment] 2021-03-02 22:06
Duplicate of #12042

**Closed by flamber** 2021-03-02 22:06 UTC
Labels: .Needs Triage, Type:Bug

**Comment by rudaruda** [comment] 2021-03-03 14:09
I will try to submit the CSS correction myself:
[](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/components/FunnelNormal.css)
Will I make it? rs
