### ISSUE TITLE
Proposal: Multiple visualizations for each query

### ISSUE THREAD

**Issue by nicosuave** [metabase/metabase#27642] opened 2023-01-12 09:13 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am forced to create duplicate queries if I want different visualizations.

**Describe the solution you'd like**
Multiple visualizations attached to the same query

**How important is this feature to you?**
Very— otherwise our Metabase organization becomes a mess with tons of duplicate queries. We can't use the visual editor sadly, as our data source is not compatible with the functions used by the mysql connector, so SQL it is. Metabase would generally benefit from embracing SQL more.

**Comment by paoliniluis** [comment] 2023-01-12 14:54
Hi @nicosuave, this is a duplicate of https://github.com/metabase/metabase/issues/1824

**Closed by paoliniluis** 2023-01-12 14:54 UTC
Labels: Type:New Feature, .Needs Triage

**Comment by nicosuave** [comment] 2023-01-12 16:58
Thanks @paoliniluis. Good seeing you here!
