### ISSUE TITLE
Breadcrumb incorrect when exploring saved sql question

### ISSUE THREAD

**Issue by rcronin** [metabase/metabase#17894] opened 2021-09-15 01:50 UTC
**Describe the bug**
When moving from a Question to Explore Results, then clicking the parent folder, it just returns not found.

**To Reproduce**
1. Create Collection
2. Create question based off SQL and store in above Collection
3. Open question and click Explore Results
4. Clicking Parent Folder goes to schema that doesn't exist 

**Expected behavior**
Clicking parent folder of explored SQL question navigates back to original question, collection it is saved in, or browsing of original database connection

**Screenshots**
![fba1a0f0-6132-4161-bba8-47020f4d9f74](https://user-images.githubusercontent.com/11710708/133356863-3eff7afa-ad47-4442-b3ce-da770df7d361.png)
![d10f1cb5-a7bd-47e2-a9dd-9bd896d43c8f](https://user-images.githubusercontent.com/11710708/133356862-a9e3d06a-a8bb-4676-91cc-336557655186.png)
![Screenshot 2021-09-14 214623](https://user-images.githubusercontent.com/11710708/133356951-47b20fd8-b890-468f-9ae4-b3a0bed123b8.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome/93.0.4577.63
- Your operating system: Ubuntu 18.04
- Your databases: Postgresql, SQL Server, DB2
- Metabase version: v1.40.4
- Metabase hosting environment: Jar-file on Ubuntu
- Metabase internal database: Postgres

**Severity**
Not overly severe, just some polish we'd like for our end users navigating the interface.

**Comment by flamber** [comment] 2021-09-15 08:11
Duplicate of #12616

**Closed by flamber** 2021-09-15 08:11 UTC
Labels: Type:Bug, .Needs Triage
