### ISSUE TITLE
OOM errors during Mongo DB sync-fields

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#46119] opened 2024-07-25 09:14 UTC
### Describe the bug

Some customers have OOM errors while inferring the schema of a MongoDB table during the sync-fields step. This issue is just to track its investigation and the fix.

### To Reproduce

NA

### Information about your Metabase installation

```JSON
master
```

### Severity

high, blocking

**Comment by qnkhuat** [comment] 2024-08-02 02:57
it's OOM during fetching sample documents for mongo, so this is a duplicate of https://github.com/metabase/metabase/issues/46277

**Closed by qnkhuat** 2024-08-02 02:57 UTC
Labels: Type:Bug, Priority:P1, Administration/Metadata & Sync, .Team/BackendComponents
