### ISSUE TITLE
Switching between tabs reruns queries even if filters keep unmodified

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#39863] opened 2024-03-08 18:14 UTC
### Describe the bug

Queries are being rerun when switching between tabs in 48.x, even though this is not the intended behavior (see [thread](https://metaboat.slack.com/archives/C01LQQ2UW03/p1709760884184699))

https://github.com/metabase/metabase/assets/132273646/b48c0c75-9518-44ba-b0bf-d81e19bc2005

### To Reproduce

1. Dave a dashboard with “Tab A” and “Tab B”, both tabs have questions and common filters.
2. Open “Tab A”, set some filter values and wait until things load
3. Go to “Tab B”, wait until things load
4. Go back to “Tab A”

Metabase reruns queries even though filters were not changed. This should not be happening as per [this](https://github.com/metabase/metabase/blob/2e5a99b3b03e3cad7a413507627281e776869e5e/frontend/src/metabase/dashboard/actions/data-fetching.js#L332) 

### Expected behavior

Shouldn't rerun the query if things keep unmodified

### Information about your Metabase installation

```JSON
- V1.48.8
```

### Severity

P2

### Additional context

Happens in 48 and 47, doesn't happen in Master (49)

**Comment by ignacio-mb** [comment] 2024-03-18 13:28
Couldn't reproduce in 49, so closing this.

**Comment by kulyk** [comment] 2024-03-29 13:57
Update: the issue can be reproduced in 49 as well. #35465 fixed this on `master` but it wasn't backported to 49 (and most likely shouldn't)

**Comment by kulyk** [comment] 2024-03-30 11:34
Fixed in #40783

**Closed by kulyk** 2024-03-30 11:34 UTC
Labels: Type:Bug, Priority:P2, Reporting/Dashboards, support/Repro, .Regression, .Team/DashViz

**Comment by mayanala-coxauto** [comment] 2024-04-04 02:16
It seems like if I have more than 8 Dashboard filters then it goes back to re-running the queries switching tabs.

**Comment by kulyk** [comment] 2024-04-04 17:50
@mayanala-coxauto, after some investigation, I think the issue is related to pivot tables, and dashboard filters are not involved AFAICT. The pivot table issue is now tracked at https://github.com/metabase/metabase/issues/41043

**Comment by mayanala-coxauto** [comment] 2024-04-04 18:51
@kulyk I'm not certain if it's just with pivot tables. I'm able to reproduce the issue with Sample DB.

Steps to Reproduce:
1)	Create Native Sql question with field filters and normal table visualization which default. Make created_at field as required field.
SELECT
  "PUBLIC"."PEOPLE"."ID" AS "ID",
  "PUBLIC"."PEOPLE"."ADDRESS" AS "ADDRESS",
  "PUBLIC"."PEOPLE"."EMAIL" AS "EMAIL",
  "PUBLIC"."PEOPLE"."PASSWORD" AS "PASSWORD",
  "PUBLIC"."PEOPLE"."NAME" AS "NAME",
  "PUBLIC"."PEOPLE"."CITY" AS "CITY",
  "PUBLIC"."PEOPLE"."LONGITUDE" AS "LONGITUDE",
  "PUBLIC"."PEOPLE"."STATE" AS "STATE",
  "PUBLIC"."PEOPLE"."SOURCE" AS "SOURCE",
  "PUBLIC"."PEOPLE"."BIRTH_DATE" AS "BIRTH_DATE",
  "PUBLIC"."PEOPLE"."ZIP" AS "ZIP",
  "PUBLIC"."PEOPLE"."LATITUDE" AS "LATITUDE",
  "PUBLIC"."PEOPLE"."CREATED_AT" AS "CREATED_AT"
FROM
  "PUBLIC"."PEOPLE"
  where true
  [[and {{v_id}}]]
  [[ and {{v_name}}]]
  [[ and {{v_city}}]]
  [[ and {{v_state}}]]
  [[ and {{v_source}}]]
  [[ and {{v_zip}}]]
  [[ and {{v_email}}]]
  [[ and {{v_password}}]]
  [[ and {{v_created_at}}]]
LIMIT
  1048575

Native Sql Question with 9 filters looks as follows

 
2)	Create a Dashboard with 8 filters(in my case, I left the password field) and  2 tabs for same question created from step 1. 
 

3)	Switch between tabs and notice messages from /var/log/messages. Since queries complete so fast, I had to look at /var/log/messages. In our environment, we check on Athena recent queries. Notice that re-run doesn’t happen.
4)	Add 9th filter, and repeat 3). Notice that re-run of the queries happen.

**Comment by mayanala-coxauto** [comment] 2024-04-04 18:55
Question 
![image](https://github.com/metabase/metabase/assets/49332534/8a501e31-d547-48b5-98e0-fc4fe01e6193)

Dashboard 
![image](https://github.com/metabase/metabase/assets/49332534/15d0f858-d9ae-4dfa-a0f7-ebe032c31e84)

**Comment by kulyk** [comment] 2024-04-04 18:59
Thank you for sharing such thorough repro steps, @mayanala-coxauto 🙏 I'll investigate

**Comment by JesseSDevaney** [comment] 2024-04-23 21:26
The fix for more than 8 filters causing queries to be re-run has been merged here and will be added in 49.8:
- https://github.com/metabase/metabase/pull/41739

**Comment by mayanala-coxauto** [comment] 2024-05-21 14:12
But we do not have any pivot tables in our Dashboards. Just tables and map visualizations.

**Comment by ignacio-mb** [comment] 2024-05-21 14:43
Hi @mayanala-coxauto, for that I've opened a feature request here: https://github.com/metabase/metabase/issues/42956
