### ISSUE TITLE
Object Detail connected to sidebar sometimes never loads first reference

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13165] opened 2020-08-25 18:10 UTC
**Describe the bug**
When viewing Object Details of a PK, then sometimes it never loads the first FK reference, but just shows a spinner.

**To Reproduce**
1. Simple question > Sample Dataset > Products
2. Click first rows ID column (`1`) to go to Object Details
![image](https://user-images.githubusercontent.com/1447303/91210614-cee61e00-e70d-11ea-8495-2cf63e00107c.png)
3. The result for "Orders" will never finish. Looking at the requests, there's two identical requests to `/api/dataset` with the same query (for "Reviews" both of them):
```
{"database":1,"type":"query","query":{"source-table":2,"aggregation":["count"],"filter":["and",["=",8,1]]}}
```
4. Click the left/right Object Detail arrows will load the results. Doing a browser refresh will cause the loading spinner again.

**Information about your Metabase Installation:**
Metabase 0.36.4 and `master`

**Additional context**
I can consistently reproduce on stats with Sample Dataset's Products. I can reproduce with a few other databases locally on 0.36.4, but not Sample Dataset.

**Comment by alxnddr** [comment] 2021-09-24 19:59
@flamber are you still able to reproduce it? Two dataset queries are needed to show counts of both Orders and Reviews. Maybe there was a race condition or something because I cannot reproduce it now:
<video src="https://user-images.githubusercontent.com/14301985/134732816-5686a282-c92a-47be-b112-26e65b39e269.mov" />

**Comment by flamber** [comment] 2021-09-24 20:10
@alxnddr I can swear that I just saw this the other day on master, but I cannot reproduce anymore. Can still reproduce on 0.40.5

**Comment by flamber** [comment] 2021-11-09 21:40
@alxnddr I'm still seeing this on 0.41.2 - but it's less often than before. Doing a uncached browser refresh seems to trigger it every time, and sometimes I even had a couple of them spinning (though, haven't figured out how to trigger that).
![image](https://user-images.githubusercontent.com/1447303/141009377-5a992243-cb83-4ad2-8f9a-d83d2da03970.png)

**Comment by djmaze** [comment] 2022-01-11 13:34
Exactly the same problem here with 0.41.5. Cannot reproduce with Sample Dataset, but with our own database. Also seeing two requests for the same field in the network inspector.

**Comment by marek-klima** [comment] 2022-02-11 15:18
I can also easily reproduce this locally using the JAR download today from [download page](https://metabase.com/start/jar.html) and connecting to my own database (Postgres running inside a Docker). What is specific about the schema of my database is that we have a JSON column in this affected table (this table that's displayed as a permanent spinner).

I checked the logs and if I understand this correctly, I should see something similar to this for each connected table:
```
2022-02-11 16:02:16,974 DEBUG sql.query-processor ::
HoneySQL Form: 🍯
{:from ((metabase.util.honeysql-extensions/identifier :table "schema_name" "table_name")),
```
But this log entry is not visible for the affected table.

This is why potentially this issue is incorrectly marked as `.Frontend`.

If that would be helpful, I could try to replicate this with H2 table and share it with you.

**Comment by kdoh** [comment] 2023-12-12 15:41
Wasn't able to reproduce this in the newer object detail modal as of `0.48.1` `f5d6697`. The entire connection sidebar does POP in in a somewhat undesirable way, but I tested against a postgres schema and viewed a detail for a table who's PK is present in a table with a JSON field (set to show everywhere) and couldn't get any infinite spinners on either side of it.

**Closed by kdoh** 2023-12-12 15:41 UTC
Labels: Type:Bug, Priority:P3, .Frontend, Visualization/Detail

**Comment by paoliniluis** [comment] 2023-12-22 21:23
yup, works 

![Image](https://github.com/metabase/metabase/assets/1711649/1c167ebb-47d2-4e2b-8bb5-4ec954780f46)
