### ISSUE TITLE
Adding Series Misalligns the X-Axis Marks for Bar Graphs

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#13847] opened 2020-11-19 18:29 UTC
![layover](https://user-images.githubusercontent.com/15974735/99707665-9d04ff00-2a51-11eb-935a-f717ef2020bc.png)

**To Reproduce**
Use the sample sataset to create two bar graphs > Add to dashboard > Add one to the other using "Add series" button

Metabase v0.37.2 (not sure if this working ok in the previous versions)

**Comment by mazameli** [comment] 2020-11-19 18:40
This is working as intended. Your example is just a little funny because you have two series that don't both have values for any given x-axis value, so the visualization is leaving room for the other bar at each x-axis value, but that bar's value just happens to be nothing.

If you try it with two series that both have values for a corresponding x-axis value, you'll see what I mean, as shown below.

<img width="1527" alt="image" src="https://user-images.githubusercontent.com/2223916/99708927-5dd7ad80-2a53-11eb-8dab-f48edd9e24fb.png">

I think a workaround though is you could open up the visualization settings at turn on Stacking:

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/2223916/99709046-83fd4d80-2a53-11eb-834b-6ca1446f46b9.png">

Closing this as working-as-intended.

**Closed by mazameli** 2020-11-19 18:40 UTC
Labels: .Already Fixed
