### ISSUE TITLE
Fix world map showing country code instead of country name

### ISSUE THREAD

**Issue by atranel** [metabase/metabase#9138] opened 2018-12-15 14:16 UTC
Please fix a bug instroduced in 0.31.x. When I plot World map with number of sites or patients per country and I mouse-hover over it, I see only country 2-letter ISO code (like DZ, UA, RO, ...), but in version 0.30.4 it was country name (Algeria, Ukraine, Romania, ...). Can you please fix it? People watching our maps should see country names and not too google up, what every 2-letter country code means. 
![screenshot_2](https://user-images.githubusercontent.com/42370527/50043890-454b0580-007c-11e9-8697-125d13aa56af.png)

**Comment by flamber** [comment] 2018-12-16 02:06
Duplicate of #8986.

**Comment by salsakran** [comment] 2018-12-28 01:59
closing as a dupe of #8986

**Closed by salsakran** 2018-12-28 01:59 UTC
