### ISSUE TITLE
Custom columns not appearing in result set when selecting subset of fields

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#20229] opened 2022-02-03 18:58 UTC
Create a question on the sample dataset on Orders, and create a custom column called "adjective" who's formula is `case([Total] > 100, "expensive", "cheap")`

The custom column appears in the results when all fields on Orders are selected, but does not appear when only a subset of fields are selected:

NOTE: most important is `release-x.42.x` It is possible this bug does not manifest in `master`. Will need a e2e test when we have narrowed and identified.

![image](https://user-images.githubusercontent.com/6377293/152410070-0b44f00f-135b-49e6-9015-329f9c9cc7fb.png)
![image](https://user-images.githubusercontent.com/6377293/152410083-a521f5aa-fab0-4a68-8e8a-0f68bb2477ae.png)
![image](https://user-images.githubusercontent.com/6377293/152410096-2bc4d033-e3e3-46e5-a567-bcc9aed046ee.png)
![image](https://user-images.githubusercontent.com/6377293/152410111-6f6259e3-5ac1-4a82-b2af-04c7399f500d.png)

**Comment by dpsutton** [comment] 2022-02-03 20:09
I think this is a FE bug. The query when selecting all fields is:

```clojure
;; selecting all fields omits a fields entry
{:database 1
 :query {:source-table 2
         :expressions {:adjective ["case"
                                   [[[">"
                                      ["field" 7 nil]
                                      100]
                                     "expensive"]]
                                   {:default "cheap"}]}}
 :type "query"
 :parameters []}
```
Since there are no fields, the fields it computes all of the fields involved in the query. However, the query sent over from the FE when you select only a subset of fields:

```clojure
;; selecting a subset includes only the fields from the orders table and not the custom expression
{:database 1
 :query {:source-table 2
         :expressions {:adjective ["case"
                                   [[[">"
                                      ["field" 7 nil]
                                      100]
                                     "expensive"]]
                                   {:default "cheap"}]}
         :fields [["field" 9 nil]
                  ["field" 7 nil]
                  ["field" 4 nil]]}
 :type "query"
 :parameters []}
```

Note the lack of the custom column in the fields to select. As far as I can tell the backend is behaving correctly and not returning the custom column.

the correct query that should be sent from the FE is the following query. Note there is no possible way for the backend to anticipate which fields should be selected once you send a subset of them. You must include all fields you want to select.

```clojure
;; the correct query when you add the custom column to the query after selecting the subset of columns
{:database 1
 :query {:source-table 2
         :fields [[:field 9 nil]
                  [:field 7 nil]
                  [:field 2 nil]
                  [:expression "adjective"]]
         :expressions {:adjective ["case"
                                   [[[:> [:field 7 nil] 100]
                                     "expensive"]]
                                   {:default "cheap"}]}}
 :type :query}
```

If you instead select a subset of fields and then add the custom column, the FE constructs the correct query. So the bug is the transition.

Scenarios:
- don't specify fields, add custom field, then select subset of fields -> Busted. This is because there is no fields list to keep track of in the `select *` case, and when it introduces the fields to keep track of it doesn't account for the custom field
- specify subset of fields, then add custom field. In this code path it is aware of a fields list and adds the custom field to that list and the correct query is created.

**Comment by flamber** [comment] 2022-02-04 09:48
Duplicate of #12395

**Closed by flamber** 2022-02-04 09:48 UTC
Labels: Type:Bug, Priority:P1, .Frontend, .Reproduced
