### ISSUE TITLE
Duplicate tables in filter modal when summarizing by a foreign key column 

### ISSUE THREAD

**Issue by alexyarosh** [metabase/metabase#46357] opened 2024-08-01 00:14 UTC
### Describe the bug

When summarizing by a foreign key column, the filter modal shows the joined table twice. 

[See slack thread](https://metaboat.slack.com/archives/C01LQQ2UW03/p1722451325908009)

![image](https://github.com/user-attachments/assets/89f0c09d-b7aa-4120-9baa-144d81fc292a)

For comparison, when summarizing by the same column but picked from the auto-joined table instead, the joined table is only shown once.

### To Reproduce

1. Create a GUI question in the sample database: Count` of Orders` by Product ID. Use the `Product ID` column or Orders. (not `Product->ID `column from Products)
3. In the table view, open the filter modal
4. Products table will appear in the modal twice

_Note: if summarizing by `Product->ID` instead, the Products table will only appear in the modal once_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "6.6.12-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.1 (Debian 16.1-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2024-07-30",
      "tag": "v1.50.18",
      "hash": "c323ffc"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Confusing

### Additional context

https://github.com/user-attachments/assets/8c3ad5fd-998b-42bb-89df-9f401c6479ca

**Comment by nemanjaglumac** [comment] 2024-08-08 19:15
The list of columns is coming straight from the backend. The duplication should be fixed there.
The FE is simply displaying them.

https://github.com/metabase/metabase/blob/master/frontend/src/metabase/querying/components/FilterModal/utils/filters.ts#L24

**Comment by ranquild** [comment] 2024-08-21 19:00
Duplicate of https://github.com/metabase/metabase/issues/46845

**Closed by ranquild** 2024-08-21 19:00 UTC
Labels: Type:Bug, Priority:P3, .Backend, Querying/GUI, .Team/Querying
