### ISSUE TITLE
GET /api/database/tables 404 After migrating from H2 to Postgres

### ISSUE THREAD

**Issue by hamin** [metabase/metabase#1912] opened 2016-02-10 17:23 UTC
I had an older instance of Metabase running (I forget what version) that was using a local H2 database. I upgraded metabase and migrated the db like so:

```
export MB_DB_AUTOMIGRATE=false
java -jar metabase.jar migrate up
```

And then did the postgres migration like so:

```
java -jar metabase.jar load-from-h2
```

Now my met abase instance is running `0.14.1`. Any new questions I'm creating are fine but links to old questions in activity contain are resulting tin the mentioned 404 error on `api/database/tables`. Is there another migration command i'm supposed to run? Is this task related to my issue: https://github.com/metabase/metabase/blob/fc015c600fefced3407ca1474c6b0e641e43a982/src/metabase/db/migrations.clj#L58

**Comment by hamin** [comment] 2016-02-10 17:24
I wanted to add a note that the link in the acitivyt contains a `?clone` url param. If I copy the link for saved  question and remove the url param I'm actually getting the result of the saved question

**Comment by agilliland** [comment] 2016-02-10 19:15
Hi @hamin I believe I see a possible explanation for what you're seeing.

Since you ran the manual schema migration command first, and then immediately ran the `load-from-h2` command to migrate the data, it looks like you might have missed executing some of the data migrations on your database which would have happened when the app was started up.

Probably the easiest/safest way to resolve this is to launch Metabase using your original H2 file so that the data migrations are executed, then shut it down and rerun the `load-from-h2` command to copy your data into the postgres instance.  Note that you'd have to clear out the data from your postgres database to do this.

If that's a problem then you can try the slightly more dangerous route which is to manually remove entries in the Metabase `data_migrations` table and then restart Metabase, this would cause the data migrations to run again.  The risk in this case is that I'm not clear exactly what migrations you would have already run so you might execute them again, but this should be safe.

**Comment by hamin** [comment] 2016-02-10 19:37
@agilliland so the problem was that in order to run `load-from-h2` properly form our original H2 file, we had to run data migrations since the `Dependency` table was missing. So I had to run `migrate up` in order to run the `load-from-h2` command.

I tested your second suggestion of deleting the `data_migrations` records and restarting Metabase. The `data_migrations` table got updated but I'm still getting the same 404 errors. Any thoughts?

**Comment by hamin** [comment] 2016-02-10 20:04
@agilliland actually i tried your first method and it worked locally. Going to try it on production now :) and will report back

**Comment by hamin** [comment] 2016-02-11 15:51
This didn't work for me locally to actually. I forgot i had the H2 database which got picked up. I think i'm gonna have to migrate this manually on a new metabase instance.

**Comment by agilliland** [comment] 2016-03-28 02:40
Closing this as the explanation for the problem was caused by the attempt to migrate and upgrade at the same time.  The solution is to upgrade to the latest version first, then migrate as a separate step.

**Closed by agilliland** 2016-03-28 02:40 UTC
Labels: Error

**Comment by kul** [comment] 2016-04-13 12:01
I had the following exact upgrades
0.13.0 -> 0.13.1 -> 0.14.1 -> 0.15 -> 0.16.1 -> load-from-h2
Migrations runs just fine, post that

* Database connection details are lost.
* On viewing any old question I get `ERROR: duplicate key value violates unique constraint "pk_view_log"`. Most probably the view_log counter is reset from 0 again. So i truncate view_log to workaround this. But it still fails with `GET /api/database/tables is not yet implemented`.
* On clicking pulse i get 
```
java.lang.ClassCastException: java.lang.Integer cannot be cast to clojure.lang.IPersistentMap
        at clojure.lang.RT.dissoc(RT.java:848)
        at clojure.core$dissoc.invokeStatic(core.clj:1462)
        at clojure.core$dissoc.invoke(core.clj:1455)
        at medley.core$dissoc_in.invokeStatic(core.cljc:22)
        at medley.core$dissoc_in.invoke(core.cljc:11)
        at medley.core$dissoc_in.invokeStatic(core.cljc:18)
        at medley.core$dissoc_in.invoke(core.cljc:11)
        at metabase.models.pulse_channel$fn__15654.invokeStatic(pulse_channel.clj:251)
        at metabase.models.pulse_channel$fn__15654.invoke(pulse_channel.clj:250)
```
* Dashboards are also broken.

**Comment by agilliland** [comment] 2016-04-13 15:29
So before you ran the load-from-h2 command were you able to run Metabase v0.16.1 against the H2 database without any issues?  I'm assuming you are able to do that right now?

**Comment by kul** [comment] 2016-04-14 04:14
Yes, migration to 0.16.1 on H2 db itself has absolutely no issues afaict from playing around with cards, dashboards, pulse and settings.

**Comment by kul** [comment] 2016-05-04 07:04
This is reproducible on 0.17.0 too.
We started using metabase experimentally but have a fair amount of user data like questions, pulses and dashboards in it.  Is there a way out of the H2 db without losing all the work?

**Comment by agilliland** [comment] 2016-06-10 15:51
We made some improvements to the h2 migration process, so when v0.18.0 comes out give it another shot and everything should work.

#2712

**Comment by kul** [comment] 2016-06-11 02:40
Thanks @agilliland :100:  *  :+1: 
Will definitely try it out and let you know the results.
