### ISSUE TITLE
[Accessibility] Contrast in calendar weekdays

### ISSUE THREAD

**Issue by tmaso-tiqueteo** [metabase/metabase#17013] opened 2021-07-13 14:25 UTC
From 0.38 version and newer versions, the contrast for the weekday sections in date picker are quite white and it is not easy for the users to view the weekday.

![image](https://user-images.githubusercontent.com/47613774/125469217-a3116fe7-7f73-42e0-8ee4-091d43a265e8.png)

**Comment by flamber** [comment] 2021-07-13 14:44
Duplicate of #14602

**Closed by flamber** 2021-07-13 14:44 UTC
Labels: .Needs Triage, Type:New Feature
