### ISSUE TITLE
Button for testing LDAP-connection

### ISSUE THREAD

**Issue by shakudu** [metabase/metabase#13359] opened 2020-10-05 06:01 UTC
**Is your feature request related to a problem? Please describe.**
When setting up LDAP it isn't clear if the configuration is successful or not.

**Describe the solution you'd like**
It would be nice to have a button for testing the connection, like the one where you configure SMTP.

**Describe alternatives you've considered**
Right now the only way i see is to log out and do a test-login.

**How important is this feature to you?**
This will more than likely be a one time configuration that you rarely revisit once you've got it working. For me, i need it right now but i'll probably get over it. For future users it might prove useful and add to the quality of the software.

**Additional context**

**Comment by flamber** [comment] 2020-10-05 09:03
Duplicate of #11446

**Closed by flamber** 2020-10-05 09:03 UTC
Labels: .Needs Triage, Type:New Feature
