### ISSUE TITLE
Timestamps for the hour of 12AM, show like "24:" and not "00:"

### ISSUE THREAD

**Issue by anastasiapapa** [metabase/metabase#14954] opened 2021-02-24 16:59 UTC
**Describe the bug**
When looking at a card with raw data that contains some timestamps, we noticed that values in the first hour of the day (from 00:00:00 to 00:59:59) look like `February 6, 2021, 24:01` for example, focusing on the **24** in comparison to **00** that we would expect to see there. 
The exact value in the Postgres table that this card has as its source, shows `2021-02-06 00:01:32`.
Did you intend for this to show like this? I think it's globally accepted that `12:00AM = 00:00` and not `24:00`.

**Expected behavior**
We would expect to see `00:` for the 12AM and not `24:`.

**Information about your Metabase Installation:**
Our Metabase version is v0.37.4

**Comment by flamber** [comment] 2021-02-24 17:27
Duplicate of #9538

**Closed by flamber** 2021-02-24 17:27 UTC
Labels: .Needs Triage, Type:Bug
