### ISSUE TITLE
metabase 0.31 can't delete card in dashboard 

### ISSUE THREAD

**Issue by mengrayan** [metabase/metabase#8933] opened 2018-11-13 02:48 UTC
I click the delete button but no response

**Comment by mengrayan** [comment] 2018-11-13 02:54
![](https://blog-rayan-cc-1252204459.cos.ap-shanghai.myqcloud.com/20181113105240.png)
Firefox is OK,chrome have no response.

**Comment by mazameli** [comment] 2018-11-15 19:45
@mengrayan Assuming you are also using Windows, this is indeed a duplicate of #2187. Closing as such.

**Closed by mazameli** 2018-11-15 19:45 UTC
Labels: Duplicate
