### ISSUE TITLE
Download options of Charts as PNG or JPEG format

### ISSUE THREAD

**Issue by ardatasci** [metabase/metabase#6438] opened 2017-11-21 12:43 UTC
The generated charts in questions pane shall include export options in jpeg/png format (as in csv and xlsx). Export functionality for questions may include the following options:
- Transparent background (for png)
- Resolution options
- Include a link showing the URL of question below the chart as reference
- Export time, and the email of person who exports the chart
- Night mode / normal mode

**Comment by camsaul** [comment] 2017-11-22 16:12
Hi @ardatasc, those sound like some good options to add. If you have some basic familiarity with Clojure and JavaScript, we'd love to have you as a contributor and would welcome a PR to support them 👍

**Comment by flamber** [comment] 2020-05-24 20:54
Duplicate of #4701

**Closed by flamber** 2020-05-24 20:54 UTC
Labels: .Proposal, Querying/Processor, Reporting/Pulses, Type:New Feature, Visualization/Chart Settings
