### ISSUE TITLE
Make it clear that a databse sync is running

### ISSUE THREAD

**Issue by MrMauricioLeite** [metabase/metabase#2194] opened 2016-03-21 01:24 UTC
Here goes another suggestion.
Some users get confused when starting to point metabase at a DB and questions still confusing (cause a sync with in-deph analysis is running) and when trying to edit data model some tbale have empty models. They go like "Where the heck are my columns?! Whats going on?!"

So my suggestion is to create som sort of notification fo users that this datamase is under sync process or even that the sync is at 80%. That kind of feedback would help a lot for new users.

My sugestion is that on the question screen, where you get to pick a database we place a blue badge saying: "in sync" that on hover have a tooltip with "Sync progress: xx% (We don't recommend asking questions on databases that are syncing.)"

What do you guys think @kdoh, @agilliland and @camsaul??

**Comment by salsakran** [comment] 2016-03-21 05:26
Great idea! But closing this issue as a dupe of #649

**Closed by salsakran** 2016-03-21 05:26 UTC
