### ISSUE TITLE
How to change database easily for different questions?

### ISSUE THREAD

**Issue by gclsoft** [metabase/metabase#8962] opened 2018-11-18 03:34 UTC
Our system has many same databases in different areas, each stores different data, but the structure of database is the same. How to change database easily for different questions?
For example, database `New York` and database `Beijing`, they have same tables, I don't need to write the same questions for them.
![image](https://user-images.githubusercontent.com/1269898/48668339-e0a49580-eb25-11e8-9990-8c8181d8452d.png)

**Comment by flamber** [comment] 2019-02-24 05:58
Hi @gclsoft 
This is a duplicate of #6496, but will very difficult to implement, since each field in the question has an underlying ID, which is connected to it's table's ID, which is connected to it's database's ID.

**Closed** 2020-05-29 21:12 UTC
Labels: .Proposal
