### ISSUE TITLE
Migrate to the new Google Identity Services library

### ISSUE THREAD

**Issue by doniyor2109** [metabase/metabase#21412] opened 2022-04-01 06:48 UTC
We have received email from Google Developers with subject "[Action Required] Migrate to the new Google Identity Services library as soon as possible"

Google announced plan for for Google SignIn JavaScript platform will no longer be supported after March 31, 2023.

I wanted to notify about these announcement and wanted to know if there is plans for migration to new Google Identity Services library?

See more details https://developers.googleblog.com/2022/03/gis-jsweb-authz-migration.html

**Comment by flamber** [comment] 2022-04-01 06:50
Duplicate of #17429

**Closed by flamber** 2022-04-01 06:50 UTC
Labels: Type:Question, .Needs Triage
