### ISSUE TITLE
Autoupdate and nighttime mode for shared dashboards

### ISSUE THREAD

**Issue by vkovalskiy** [metabase/metabase#4794] opened 2017-04-15 06:48 UTC
Shared dashboards are a great feature but we need to have nighttime mode + autoupdate configured (i.e. for TV screen). Moreover it would even better if we could configure the target mode using url params so there would be no need to click anything on a tv screen which is a pain!

**Comment by salsakran** [comment] 2017-04-17 18:20
dupe of #4612

**Closed by salsakran** 2017-04-17 18:20 UTC
Labels: Dashboards, Embedding
