### ISSUE TITLE
Variable Values For Named Fields (AS) Can not be used as Field Filters in Custom Query Builder

### ISSUE THREAD

**Issue by tuaris** [metabase/metabase#9391] opened 2019-02-08 01:16 UTC
- MariaDB
- Metabase version: 0.31.2
- Metabase hosting environment: Linux/Ubuntu 12
- Metabase internal database:  MariaDB

Scenario 1

It's not possible to have the `myfield_value` variable as a Field Filter.

```
SELECT `table`.`column` AS `myfield` FROM `table` WHERE `myfield` = {{myfield_value}}
```

Scenario 2

It's not possible to use `date_range` as a Field Filter

```
SELECT * FROM
(
	SELECT 
		CURDATE() - INTERVAL `sequence`.`seq` DAY AS `date`
	FROM
		(SELECT `seq` FROM `seq_0_to_2000`) AS `sequence`
) AS `datelist`

WHERE {{date_range}}
```

**Comment by flamber** [comment] 2019-02-08 01:55
Hi @tuaris 
Correct, aliases are not supported, when using Field Filters. This is a duplicate of #3324 - give it a :+1:

**Comment by lindsay-stevens** [comment] 2019-02-08 05:17
For scenario 1 you can use a subquery for the filter then alias the column in the outer query:

```sql
SELECT subq.column AS myfield
FROM (
  SELECT *
  FROM table
  WHERE {{myfield_value}}
) AS subq
```

Because it'll render like this (where `1, 2, 3` are selected values in the filter widget):

```sql
SELECT subq.column AS myfield
FROM (
  SELECT *
  FROM table
  WHERE table.column IN (1, 2, 3)
) AS subq
```

For scenario 2, the way Field Filters are designed is that they're hooked up to a specific database column, but in the example SQL it seems to be an unrelated / arbitrary table. Probably for that case you'd need the Date variable type to have an option for Date Range, rather than it being a problem with Field Filters as such.

The main point is that Field Filters take a token like this:

```sql
WHERE {{my_field}}
```

And inject a SQL snippet like this:

```sql
WHERE "selected_map_table"."selected_map_column" IN ('value 1', 'value 2, 'etc')
```

**Comment by salsakran** [comment] 2019-04-10 04:56
closing as a dupe.

**Closed by salsakran** 2019-04-10 04:56 UTC
