### ISSUE TITLE
Allow users to cancel a query execution at the database

### ISSUE THREAD

**Issue by infomofo** [metabase/metabase#2399] opened 2016-04-21 20:24 UTC
Mentioned by @agilliland in this [ticket](https://github.com/metabase/metabase/issues/2181) as a candidate for being split into a different feature request.

I was running a long running query. I realized after I hit run query that I forgot to filter the data. I then had to wait for it to complete. 

I wanted a cancel button.  Obviously I can just refresh the page to get this effect but a cancel button seems better/safer.

⬇️  Please click the 👍 reaction instead of leaving a `+1` or 👍  comment

**Comment by salsakran** [comment] 2016-04-21 20:38
does your data warehouse support cancelling the query? ;)

This is a bit of a leading question, but I'll throw out that not all data warehouses allow you to do this, so we'll need to have some sensible UX treatment if we go down this route.

**Comment by infomofo** [comment] 2016-04-21 20:43
no it doesn't - but my browser does effectively- I can hit Cmd-R and then reconfigure my query as I see fit.

I get your point, that there is a risk here because the original query isn't cancelled, but I don't think that the presence of a UI affordance to cancel the query changes the actual options available to an end user of metabase, it just makes the experience less frustrating.

**Comment by salsakran** [comment] 2016-04-21 21:01
Yeah, I think it's something we need to look into. It's just semantically tricky, as in many cases, we *dont* want users to hit Cmd-R a bunch of times on a big beefy query on Redshift, say.

**Comment by agilliland** [comment] 2016-04-22 22:00
One other consideration here is that typically to cancel a query you need special db permissions and given that Metabase is often run on credentials with limited and read-only permissions it's often not possible to cancel the queries.

That problem not withstanding, I'm not opposed to providing a way for users to continue their work on the frontend and resubmit a query before the last one has finished.

**Comment by CzechJiri** [comment] 2016-04-25 21:51
Most databases accept the query cancellation via` Statement.cancel()` and try to cancel the query. I am saying try because the cancellation can be long operation depending on what else is going on with underlying data. The only datasource I am aware which does not support cancel() for the query is HIVE.

The other (sort of workaround) could be setting timeout e.g. when I am creating new question, I can pick 60sec/120sec/... timeout. This could be almost like a "screatchpad before I finalize the question" This works via `Statement.setQueryTimeout(seconds)`

**Comment by MrMauricioLeite** [comment] 2016-04-26 01:24
Taking as example the Bigquery web interface we can abandon a query but it let you know that the query will keep running on background and you'll pay for the query anyway, in case bigquery can't cancel them.

I think that metabase can try to cancel the query but let the user know that some databases may let the query running on background until it ends. Geting the interface back to the question for edit.

**Comment by CzechJiri** [comment] 2016-04-26 02:25
we should probably take this to forum... BigQuery can cancel queries/jobs 

https://cloud.google.com/bigquery/docs/reference/v2/jobs/cancel

**Comment by agilliland** [comment] 2016-04-26 21:23
I think the title here may be a little misleading because really the original request was more about not having to wait for a query to complete its execution before being allowed to submit a new query.  That's fairly different from actively canceling a query running on a data warehouse.

While canceling a query may be related, I think the more pressing question is whether or not the UI should block until a query is completed, or if the user should be allowed to continue modifying the query and then execute it again before the previous query returns.

**Comment by CzechJiri** [comment] 2016-04-26 21:33
the way I read @infomofo and his ticket titled "I want to be able to cancel a query", it seems he wants to cancel the query because he made a mistake

> I was running a long running query. I realized after I hit run query that I forgot to filter the data. I then had to wait for it to complete.
I wanted a cancel button. Obviously I can just refresh the page to get this effect but a cancel button seems better/safer.

I would love this feature as well

**Comment by kfarr** [comment] 2016-04-27 23:10
+1 we have been using metabase for a week and already are encountering this issue with end-users who make a mistake with a long-running query and have to wait a long time before being able to adjust their filtering settings

**Comment by tlrobinson** [comment] 2016-05-02 19:14
Related to #2181

**Comment by tlrobinson** [comment] 2016-05-02 19:28
- How should the client signal to the server that the query should be canceled?
  - currently the /api/dataset endpoint is synchronous so we should be able to just close the connection on the client and detect that on the backend
    - no changes needed on the backend to prevent the backend from pulling data from the db cursors, but may need to issue db-specific commands to actually cancel an in-progress query?
  - if we wanted to change the /api/dataset endpoint to be asynchronous we could have it return a query id that we could pass to another endpoint to cancel it, but that would be more complicated

**Comment by agilliland** [comment] 2016-05-06 18:52
I'm going to make it clear this issue is focused specifically on actively canceling queries at the database level.

The issue of freeing up the query UI so that a query can be edited/re-run before it finishes executing will be tackled by https://github.com/metabase/metabase/issues/2181

**Comment by salsakran** [comment] 2016-05-13 22:55
An open question;
If the attempt to cancel a query fails, should we inform the user somehow? the admin? does it just limp along in the background?

I'm assuming we should do the last, baring some kind of site wide notification system as the chances are good the user will have moved on.

**Comment by camsaul** [comment] 2016-05-13 22:56
a lot of times cancelling a query on a DB is a best-effort so you don't know whether it failed or succeeded

**Comment by salsakran** [comment] 2016-09-27 21:37
a +1 for this from #3404

**Comment by salsakran** [comment] 2016-10-06 16:51
+1 for this from http://discourse.metabase.com/t/prevent-automatic-running-of-queries-after-saving-and-allow-for-termination-of-queries/741

This is getting silly. We need to be able to do what we can to cancel queries. Sometimes people are running us on DBs that take 10+ minutes to run a query.

@camsaul can you do a bit of research and see which of our supported DBs support cancelling queries?

**Comment by thearthur** [comment] 2017-04-28 21:28
Some thinking on this one:
* Part 1 Make the Cancel Button Work:
  * Add the ability to cancel requests to the Drivers that support it.
  * include a cancellation token in the request that starts a query
  * add a cancel API endpoint that cancels the request with that same DB and token.
* Part 2  Automatically Cancel Abandoned Requests
  * finish https://github.com/metabase/metabase/pull/1158 to make detecting when the browser has left reasonable.
  * catch the connection closed exception, and then cancel the request
* Part 3
  * Store the queries status (running, abandoned, cancel-pending, cancel-started, cancel-confirmed) in the db.
  * make the drivers pull this from the DB to reduce the dependence on running MB on a single host
  * add add query management admin options to allow cleaning up runaway queries.
* Part 4
  * Make queries asynchronous, managed etc.

**Comment by txomon** [comment] 2017-07-19 10:50
Just in case, this is severely affecting our setup. We have expensive queries that with filters are quite way cheaper and feasible, and because metabase executes them automatically, when the user runs it again, we have the expensive one running forever, actually overloading the database.

**Comment by salsakran** [comment] 2018-02-23 01:28
closed via #6848

**Closed by salsakran** 2018-02-23 01:28 UTC
Labels: Proposal/Being Discussed, Query Builder

**Comment by davehowell** [comment] 2019-08-21 01:06
> Yeah, I think it's something we need to look into. It's just semantically tricky, as in many cases, we _dont_ want users to hit Cmd-R a bunch of times on a big beefy query on Redshift, say.

As warned by @salsakran ,  we now have this exact issue, people hit cancel, it doesn't cancel the query, and users fill up the concurrency slots and then everyone complains that Redshift is slow. I know however, that Redshift does support canceling queries. It works in other query tools.
