### ISSUE TITLE
When sync finds a new table, you must refresh your browser.

### ISSUE THREAD

**Issue by robdaemon** [metabase/metabase#12825] opened 2020-07-01 22:48 UTC
**Describe the bug**
If an administrator adds a new table to their database and forces a sync in the admin interface, the new table isn't visible in the data model view after sync is complete until the user refreshes their browser.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Add a new database table to an existing database
2. Go to Admin, Databases and choose the database you added the table to
3. Click "Sync database schema now"
4. Watch the logs for the sync to complete
5. Go to Admin, Data Model, and select the database
6. Note the missing new table. Hit Refresh in your browser, and that table will appear.

**Expected behavior**
A refresh of your browser should not be necessary when the database schema is updated.

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10-post-Ubuntu-3ubuntu1",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10-post-Ubuntu-3ubuntu1",
    "os.name": "Linux",
    "os.version": "5.4.0-39-generic",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "oracle"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "dev",
    "version": {
      "tag": "v0.36.0-snapshot",
      "hash": "8c6d854",
      "branch": "oracle-enums",
      "date": "2020-06-30"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Probably a P3 - more of an annoyance.

**Additional context**
Was testing this with an Oracle database, but that doesn't seem to matter.

**Comment by flamber** [comment] 2020-07-02 08:07
Duplicate of https://github.com/metabase/metabase/issues/10330#issuecomment-610900593 or one of the related ones

**Closed by flamber** 2020-07-02 08:07 UTC
Labels: .Needs Triage, Administration/Metadata & Sync, Type:Bug
