### ISSUE TITLE
Series settings (for multiple metrics) lost when upgrading from 0.31 to 0.32

### ISSUE THREAD

**Issue by vi-vsn** [metabase/metabase#9785] opened 2019-04-15 13:24 UTC
After upgrading I noticed that some of my charts appearance has changed - I had to go to fix the interpolate missing  values (it wasn't "don't show" any longer, which is what it was supposed to be). Sorry if I am misremembering the actual names of things, let me know if  this isn't clear.

**Comment by flamber** [comment] 2019-04-15 18:55
Hi @vi-vsn 
Which version did you upgrade from and to?
Can you give more details - like providing a screenshot?
So your line charts used to "Replace missing values with" set to "Nothing", but that changed on upgrade? What was is changed to?

**Comment by vi-vsn** [comment] 2019-04-15 18:59
It was changed to replace with zero.

I upgraded from  0.31.2 to 0.32.2.

I have since downgraded back to 0.31.2 due to another critical bug that I
reported, so I can't conduct any further tests at the moment, until I am
ready to try the upgrade again.

Just wanted to let you know in case it was something easy to diagnose and
fix.
 0.31.2

**Comment by flamber** [comment] 2019-04-15 19:14
@vi-vsn Okay, understandable. Do you have a backup of the old 0.31.2 database, since now the upgrade might have changed something, so it will be difficult to reproduce.
You should have a look in the table `report_card` and the column `visualization_settings`
If you can pull information from there, then I would like to try to reproduce it.

**Comment by vi-vsn** [comment] 2019-04-15 19:25
Two examples of the charts that changed:

{"graph.y_axis.title_text":"","table.columns":[{"name":"day","enabled":true},{"name":"order_date","enabled":false},{"name":"partition","enabled":false},{"name":"this_period_total","enabled":false},{"name":"this_period_running_total","enabled":true},{"name":"this_period_count","enabled":false},{"name":"this_period_running_count","enabled":false},{"name":"same_period_last_month_total","enabled":false},{"name":"same_period_last_month_running_total","enabled":false},{"name":"same_period_last_month_count","enabled":false},{"name":"same_period_last_month_running_count","enabled":false},{"name":"same_period_1_year_ago_total","enabled":false},{"name":"same_period_1_year_ago_running_total","enabled":true},{"name":"same_period_1_year_ago_count","enabled":false},{"name":"same_period_1_year_ago_running_count","enabled":true},{"name":"same_period_2_years_ago_total","enabled":false},{"name":"same_period_2_years_ago_running_total","enabled":true},{"name":"same_period_2_years_ago_count","enabled":false},{"name":"same_period_2_years_ago_running_count","enabled":false}],"graph.x_axis.title_text":"","graph.y_axis.auto_split":false,"graph.metrics":["this_period_running_total","goal_running_total","same_period_1_year_ago_running_total","same_period_2_years_ago_running_total"],"graph.y_axis.axis_enabled":true,"series_settings":{"This Period":{"color":"#7172AD","display":"line","line.missing":"none","line.marker_enabled":true,"line.interpolate":"cardinal","axis":"left"},"Current Product Cost":{"line.interpolate":"linear","display":"area","color":"#509EE3"},"Same Period Last Month":{"line.missing":"interpolate","color":"#509EE3"},"Same Period 2 Years Ago":{"color":"#98D9D9","display":"line","line.marker_enabled":true,"line.interpolate":"cardinal"},"Same Period 2 Years Ago Counts":{"display":"bar","color":"#98D9D9"},"Same Period 1 Year Ago":{"color":"#509EE3","display":"line","line.marker_enabled":true,"line.interpolate":"cardinal"},"Same Period 2 Years Ago Running Total":{"line.missing":"none","color":"#98D9D9","line.marker_enabled":true},"Same Period Last Year":{"color":"#98D9D9","display":"area"},"Goal Running Total":{"color":"#EF8C8C","line.marker_enabled":true,"line.interpolate":"cardinal"},"This Period Running Total":{"line.missing":"none","color":"#7172AD","line.marker_enabled":true},"Same Period 1 Year Ago Counts":{"display":"bar","color":"#509EE3"},"This Period Counts":{"color":"#7172AD","display":"bar"},"Previous Product Cost":{"line.interpolate":"cardinal","display":"area","color":"#98D9D9"},"Same Period 1 Year Ago Running Total":{"line.missing":"none","color":"#509EE3","line.marker_enabled":true}},"graph.dimensions":["day"],"stackable.stack_type":null}

----------------------------------------------------------------------------------------

{"graph.y_axis.title_text":"","table.columns":[{"name":"day","enabled":true},{"name":"order_date","enabled":false},{"name":"partition","enabled":false},{"name":"this_period_total","enabled":false},{"name":"this_period_running_total","enabled":true},{"name":"this_period_count","enabled":false},{"name":"this_period_running_count","enabled":false},{"name":"same_period_last_month_total","enabled":false},{"name":"same_period_last_month_running_total","enabled":false},{"name":"same_period_last_month_count","enabled":false},{"name":"same_period_last_month_running_count","enabled":false},{"name":"same_period_1_year_ago_total","enabled":false},{"name":"same_period_1_year_ago_running_total","enabled":true},{"name":"same_period_1_year_ago_count","enabled":false},{"name":"same_period_1_year_ago_running_count","enabled":true},{"name":"same_period_2_years_ago_total","enabled":false},{"name":"same_period_2_years_ago_running_total","enabled":true},{"name":"same_period_2_years_ago_count","enabled":false},{"name":"same_period_2_years_ago_running_count","enabled":false}],"graph.x_axis.labels_enabled":false,"graph.x_axis.axis_enabled":true,"graph.x_axis.title_text":"Month","graph.y_axis.auto_split":false,"graph.metrics":["this_period_running_total","same_period_1_year_ago_running_total","same_period_2_years_ago_running_total","goal_running_total_ytd"],"graph.y_axis.axis_enabled":true,"series_settings":{"This Period":{"color":"#7172AD","display":"line","line.missing":"none","line.marker_enabled":true,"line.interpolate":"cardinal","axis":"left"},"Current Product Cost":{"line.interpolate":"linear","display":"area","color":"#509EE3"},"Same Period Last Month":{"line.missing":"interpolate","color":"#509EE3"},"Same Period 2 Years Ago":{"color":"#98D9D9","display":"line","line.marker_enabled":true,"line.interpolate":"cardinal"},"Same Period 2 Years Ago Counts":{"display":"bar","color":"#98D9D9"},"Same Period 1 Year Ago":{"color":"#509EE3","display":"line","line.marker_enabled":true,"line.interpolate":"cardinal"},"Same Period 2 Years Ago Running Total":{"line.missing":"none","color":"#98D9D9","line.marker_enabled":true},"Same Period Last Year":{"color":"#98D9D9","display":"area"},"Goal Running Total Ytd":{"color":"#EF8C8C"},"This Period Running Total":{"line.missing":"none","color":"#7172AD","line.marker_enabled":true,"display":"line"},"Same Period 1 Year Ago Counts":{"display":"bar","color":"#509EE3"},"This Period Counts":{"color":"#7172AD","display":"bar"},"Previous Product Cost":{"line.interpolate":"cardinal","display":"area","color":"#98D9D9"},"Same Period 1 Year Ago Running Total":{"line.missing":"none","color":"#509EE3","line.marker_enabled":true}},"graph.dimensions":["day"],"stackable.stack_type":null}

**Comment by vi-vsn** [comment] 2019-04-15 19:26
This is the data prior to the upgrade. When I rolled back the upgrade - I also restored the database from the backup.

**Comment by vi-vsn** [comment] 2019-04-15 19:28
It might help to know that specifically, the series titled "This Month" is the one that changed in appearance following the upgrade.

**Comment by camsaul** [comment] 2019-04-15 19:34
I diffed these two JSON blobs so it's possible to see at a glance what changed.

### BEFORE

```json
{
  "series_settings": {
    "Goal Running Total": {
      "color": "#EF8C8C",
      "line.marker_enabled": true,
      "line.interpolate": "cardinal"
    }
  },
  "graph.x_axis.title_text": "",
  "graph.metrics": [
    null,
    "goal_running_total",
    "same_period_1_year_ago_running_total",
    "same_period_2_years_ago_running_total"
  ]
}
```

### AFTER

```json
{
  "series_settings": {
    "Goal Running Total Ytd": {
      "color": "#EF8C8C"
    },
    "This Period Running Total": {
      "display": "line"
    }
  },
  "graph.x_axis.title_text": "Month",
  "graph.metrics": [
    null,
    "same_period_1_year_ago_running_total",
    "same_period_2_years_ago_running_total",
    "goal_running_total_ytd"
  ],
  "graph.x_axis.axis_enabled": true,
  "graph.x_axis.labels_enabled": false
}
```

(Taken from before/after JSON before @vi-vsn removed after JSON in an edit (why?))

@tlrobinson any ideas about this?

**Comment by vi-vsn** [comment] 2019-04-15 19:36
Sorry for the confusion - I removed the second example because it wasn't a before/after, but simply two examples of "before". I though a single example will reduce the chances of confusion.

**Comment by tlrobinson** [comment] 2019-04-15 20:03
This is likely due to the fix for #9189 which changed the "key" we used to identify each series in the series settings (which includes the `line.missing` setting).

Unfortunately it's difficult to fix issues like that and not break existing saved questions. We probably need some sort of migration system for visualization settings.

**Comment by tuaris** [comment] 2019-05-10 20:10
This 'less' broken in 0.32.7.  I've come across some questions that have randomly changed series color and/or lost the custom label for the series.

**Comment by flamber** [comment] 2021-11-11 19:45
We're working on migration cleanup and while we would like to have included this, it is deemed too dangerous to try to fix this now and it seems like relatively few people experienced this issue, so closing issue.
In the future, if we make similar changes to visualization_settings, then we will do migrations to avoid problems like this.

**Closed by flamber** 2021-11-11 19:45 UTC
Labels: Visualization/Chart Settings, Operation/Database Migrations
