### ISSUE TITLE
Add setting to replace Help link destination for Pro/EE white-labeled Metabase

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#34806] opened 2023-10-18 18:46 UTC
**Is your feature request related to a problem? Please describe.**
- Customers who are white-labeling Metabase and rebranding it are not able to change the destination of the Help link
- This means that clicking Help takes them to Metabase branded help which may defeat their white-labeling goals and circumvent their branding

![image](https://github.com/metabase/metabase/assets/8808703/7871dd00-ffc2-4d55-ae98-a4b1ed30a0ba)

**Describe the solution you'd like**
- Create a setting and environment variable available to admins in Pro/EE Metabase to setup a custom destination for the Help link

**Describe alternatives you've considered**
- None for Cloud customers
- Reverse proxy to inject replacement code/link/css for self-hosted customers
- Custom build of Metabase for self-hosted customers
- https://github.com/metabase/metabase/issues/14994

**How important is this feature to you?**
- Deal-breaker for some Pro/EE customers who have strict brand requirements.

**Comment by paoliniluis** [comment] 2023-10-18 20:08
dupe of https://github.com/metabase/metabase/issues/14994?

**Comment by likeshumidity** [comment] 2023-10-19 22:51
Not quite a dupe, but solves same problem. This one is much less effort (doesn't require rebranding docs).

**Comment by albertoperdomo** [comment] 2023-11-24 12:29
Addressed via https://github.com/metabase/metabase/issues/35915

**Comment by albertoperdomo** [comment] 2024-03-19 10:41
Closed. [Shipped in version 49](https://www.metabase.com/docs/latest/configuring-metabase/appearance#help-link-in-the-settings-menu).

**Closed by albertoperdomo** 2024-03-19 10:41 UTC
Labels: Type:New Feature, .Frontend, .Backend, Administration/Whitelabel, .Team/Embedding
