### ISSUE TITLE
App refreshes back to homepage every time I load the dashboard

### ISSUE THREAD

**Issue by andytsoi** [metabase/metabase#4554] opened 2017-03-21 01:55 UTC
I am having trouble with Metabase not loading the dashboard. I am using an early 2015 13" MacBook pro on OS version 10.12.1, running SQL Server (windows 2008), and Metabase app version v0.22.2.

------
Before filing an issue we'd appreciate it if you could take a moment to ensure
there isn't already an open issue or pull-request.
-----

### Database support
If there's an exisiting issue, please add a +1 in the comments as we
prioritize drivers by the level of support. Otherwise, please include the name
of the database and the version.

### Feature requests and proposals
We're excited to hear how we can make Metabase better. Please add as much detail
as you can on your use case.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

- *Repeatable steps to reproduce the issue*

Thanks for being part of the Metabase project!
-------

**Comment by tlrobinson** [comment] 2017-03-21 20:24
Duplicate of #3950

**Closed by tlrobinson** 2017-03-21 20:24 UTC
