### ISSUE TITLE
Visualization: Bar chart not showing 0 values unlike line and area chart

### ISSUE THREAD

**Issue by jrca025** [metabase/metabase#22442] opened 2022-05-05 01:33 UTC
This is the only option when choosing bar chart.

![image](https://user-images.githubusercontent.com/89201548/166851632-d9984cda-6a5d-4bdb-b005-1cf6ef62c071.png)

Whilst below images are for Line and Area chart.

![image](https://user-images.githubusercontent.com/89201548/166851844-25758bbf-747e-4ed3-82d5-4ad8d6e310f1.png)
![image](https://user-images.githubusercontent.com/89201548/166851864-6aeac443-d7b5-49b6-948b-b5950783d3fd.png)

This is the same as for previous metabase version that I was on around v0.3+

However, there was a workaround (just switch to line/area chart then select **"Replace missing values" with Zero** then revert to bar chart, missing values would then be replaced with 0 value) that I did back then that is now not working on my current version.

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10-Ubuntu-0ubuntu0.18.04.1",
    "java.vendor": "Private Build",
    "java.vendor.url": "Unknown",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10-Ubuntu-0ubuntu0.18.04.1",
    "os.name": "Linux",
    "os.version": "5.4.0-1077-azure",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "mongo",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-04-07",
      "tag": "v0.42.4",
      "branch": "release-x.42.x",
      "hash": "7c3ce2d"
    },
    "settings": {
      "report-timezone": "Asia/Hong_Kong"
    }
  }
}

**Comment by flamber** [comment] 2022-05-05 09:36
Duplicate of #20290

**Comment by jrca025** [comment] 2022-05-05 09:48
@flamber I think this is not a duplicate, similar but not a duplicate. The problem in #20290 is when the area is small for the values. From what I stated here missing numbers are not showing as 0 when bar chart is selected. Because even if I maximize the chart size. Those data with missing number are not showing as 0 as seen on the attached screenshots.

Here is a sample data based on the screenshot below:

![image](https://user-images.githubusercontent.com/89201548/166899479-c374f5a3-c6b2-4d44-b554-1757b629803d.png)

Date,invested
2022-05-05,50
2022-05-04,60
2022-05-03,0
2022-05-02,31
2022-05-01,0
2022-04-30,0
2022-04-29,23

Now when I choose bar chart, there is no option to replace missing values as 0.

**Closed** 2022-07-16 00:01 UTC
Labels: Type:Bug, Priority:P3, .Frontend, Visualization/Charts
