### ISSUE TITLE
Redshift Late Binding views don't fetch the column information for type/text columns

### ISSUE THREAD

**Issue by startoz** [metabase/metabase#13622] opened 2020-10-29 10:31 UTC
In Redshift, views are bound by default to the tables that they represent, unless they are created with `WITH NO SCHEMA BINDING` (in this case, they are called "Late Binding" views).
Metabase doesn't seem to be able to fetch the column info for "text" columns in views created this way. The data type is displayed as `type/*` instead of `type/text`
This means that the columns cannot be properly used in filters and/or used in "group by" clauses.
![metabase](https://user-images.githubusercontent.com/2110582/97556865-4ec48900-19da-11eb-9089-3ca3bb6e2c7b.PNG)

Sounds very similar to #6505  

### Diagnostic Info:
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "4.14.171-136.231.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-08-04",
      "tag": "v0.36.3",
      "branch": "release-0.36.x",
      "hash": "a792f14"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Log

```
2020-10-29T11:00:01+01:00 INFO metabase.sync.sync-metadata.tables Updating description for tables: ([...])
2020-10-29T11:00:01+01:00 DEBUG metabase.middleware.log GET /api/card/302 200 7.1 ms (6 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (14 idle, 0 queued) (190 total active threads) Queries in flight: 0 (0 queued)
2020-10-29T11:00:01+01:00 DEBUG metabase.middleware.log POST /api/dataset 202 [ASYNC: completed] 49.7 ms (10 DB calls) App DB connections: 1/15 Jetty threads: 3/50 (14 idle, 0 queued) (190 total active threads) Queries in flight: 1 (0 queued)
2020-10-29T11:00:03+01:00 DEBUG metabase.middleware.log POST /api/dataset 202 [ASYNC: completed] 51.9 ms (10 DB calls) App DB connections: 1/15 Jetty threads: 3/50 (16 idle, 0 queued) (170 total active threads) Queries in flight: 0 (0 queued)
2020-10-29T11:00:04+01:00 WARN metabase.driver.sql-jdbc.sync Don't know how to map column type 'character varying(40)' to a Field base_type, falling back to :type/*.
2020-10-29T11:00:04+01:00 WARN metabase.driver.sql-jdbc.sync Don't know how to map column type 'character varying(60)' to a Field base_type, falling back to :type/*.
2020-10-29T11:00:04+01:00 WARN metabase.driver.sql-jdbc.sync Don't know how to map column type 'character varying(20)' to a Field base_type, falling back to :type/*.
2020-10-29T11:00:04+01:00 WARN metabase.driver.sql-jdbc.sync Don't know how to map column type 'character varying(256)' to a Field base_type, falling back to :type/*.
2020-10-29T11:00:04+01:00 WARN metabase.driver.sql-jdbc.sync Don't know how to map column type 'character varying(40)' to a Field base_type, falling back to :type/*.
2020-10-29T11:00:04+01:00 WARN metabase.driver.sql-jdbc.sync Don't know how to map column type 'character varying(256)' to a Field base_type, falling back to :type/*.
2020-10-29T11:00:04+01:00 WARN metabase.driver.sql-jdbc.sync Don't know how to map column type 'character varying(3)' to a Field base_type, falling back to :type/*.
```

### Steps to reproduce

1. Create a `TEST_VIEW` view in Redshift with `WITH NO SCHEMA BINDING` and point it to a table that includes text fields
2. Sync schema in Metabase
3. Inspect the `TEST_VIEW` table's schema in Metabase and notice the incorrect data type for the text fields

**Comment by flamber** [comment] 2020-10-29 10:54
Hi @startoz 
Please fill out all the requested information, when opening an issue. At a minimum "Diagnostic Info" from Admin > Troubleshooting, but it would be very helpful with steps to reproduce with sample view query and logs from sync.
Sounds like a duplicate of #13141

**Comment by startoz** [comment] 2020-10-29 11:14
Hi @flamber , thank you. I've updated the original post

**Comment by startoz** [comment] 2020-10-29 11:18
It sounds like it might be the same issue, but #13141 doesn't specify that it happens for Redshift's Late Binding views

**Comment by camsaul** [comment] 2021-01-30 02:47
Fixed by #14496

**Closed by camsaul** 2021-01-30 02:47 UTC
Labels: Administration/Metadata & Sync, Database/Redshift, Type:Bug

**Comment by rarup1** [comment] 2022-03-23 18:30
Has anyone else found that there is still a related issue syncing fields from a Late Binding View on Redshift using Metabase version 0.42.0? It always errors on: 
`WARN metabase.sync.util Error syncing Fields for Table 'Table 1,970 'models_core.rpt_xml_aif_0002''
com.amazon.redshift.util.RedshiftException: ERROR: invalid input syntax for integer: "" `

We are experiencing an issue where any field that contains NULLs and is of the type CHARACTER VARYING or NUMERIC in the pg_get_late_binding_view_cols() causes this error which results in the table not being functional. To overcome this we have had to CAST all fields that could possibly be NULL to a varchar(XX). This is very much a workaround until we understand why this is happening in Metabase.

It is is a similar issue to what people are experiencing in tableau here: https://kb.tableau.com/articles/issue/Error-Amazon-Amazon-Redshift-30-Error-Occurred-While-Trying-To-Execute-A-Query-Sqlstate-22P02-Error-Invalid-Input-Syntax-For-Integer-When-Refreshing-Extracts-Workbooks-Or-Running-Subscription?lang=de-de

@camsaul  Do you think this is related to the above and should I open a separate issue?

**Comment by flamber** [comment] 2022-03-23 18:35
@rarup1 Please upgrade to latest release: https://github.com/metabase/metabase/releases/latest
If that doesn't help, then create a new issue with steps-to-reproduce, so we have something to work with.
