### ISSUE TITLE
Version 0.33.4 not working behind NGINX reverse proxy anymore.

### ISSUE THREAD

**Issue by floushee** [metabase/metabase#11148] opened 2019-10-16 06:22 UTC
We have configured our NGINX to redirect from /metabase to our Metabase installation. This worked for versions between 0.31.xx and 0.33.3. When we upgraded to Metabase version 0.33.4 this redirect was suddenly broken because Metabase is loading its sources from a different path:

Before version 0.33.4 -> /metabase/app/dist/..
Since version 0.33.4 -> /app/dist/...

Our NGINX configuration looks like this:
`location /metabase/ {
    proxy_pass http://<metabase-host>:3000/;
}
`

Now we are not sure if you did change this on purpose or if its a bug.

**Comment by floushee** [comment] 2019-10-16 06:24
The issue might be related to this one: https://github.com/metabase/metabase/issues/11139

**Comment by flamber** [comment] 2019-10-16 06:47
Hi @floushee 
Just to make sure, your Admin > Settings > General > Site URL is something like `https://example.com/metabase` ?
I haven't tested yet, but I guess it's caused by PR 10963 (not linking, since I'm unsure).
Until #11139 gives more information - like if this is sub-directory reverse proxy like you - then I don't know if they're related, but timing would make me think so too.

**Comment by floushee** [comment] 2019-10-16 07:06
I tried that and it did not resolve the issue

**Comment by paulrosenzweig** [comment] 2019-10-21 20:04
Fixed in #11174

**Closed by paulrosenzweig** 2019-10-21 20:04 UTC
Labels: .Duplicate, Type:Bug
