### ISSUE TITLE
"File download" not working in Chrome browser.

### ISSUE THREAD

**Issue by jina9716** [metabase/metabase#24804] opened 2022-08-16 06:37 UTC
**Describe the bug**
"File download" not working in Chrome browser.

console message
```
Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details.
```

**To Reproduce**
1. Click on 'Download full results' button
2. See error

**Severity**
critical

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "ko-KR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8",
    "os.name": "Linux",
    "os.version": "5.4.0-1029-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "athena",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-08-04",
      "tag": "v0.44.0",
      "branch": "release-x.44.x",
      "hash": "d3700f5"
    },
    "settings": {
      "report-timezone": "Asia/Seoul"
    }
  }
}
```

**Comment by flamber** [comment] 2022-08-16 07:34
Hi @jina9716 
I cannot reproduce, but the error indicates you are not just using Metabase regularly, but have done some type of embedding or using sandboxed iframe. You'll need to provide enough information with steps-to-reproduce.

**Comment by jina9716** [comment] 2022-08-16 08:23
To download the excel file, I pressed the button in my query.
but it's not working.
![스크린샷 2022-08-16 오후 5 17 47](https://user-images.githubusercontent.com/17245615/184832269-4fe20a8e-2c34-4cf3-b628-8be23cc5b5c7.png)

**Comment by flamber** [comment] 2022-08-16 08:31
@jina9716 You need to provide a full HAR export from your browser developer Network-tab, so it is possible to understand how you are using Metabase, since you are running Metabase in a non-standard way.
Closing until there's enough details provided to be able to reproduce.

**Closed by flamber** 2022-08-16 08:31 UTC
Labels: Type:Bug, .Needs Triage
