### ISSUE TITLE
Question cannot be saved when results are empty

### ISSUE THREAD

**Issue by brunob712** [metabase/metabase#9390] opened 2019-02-07 19:50 UTC
Trying to save custom SQL questions that don't bring any results sometimes produce the following error message:
`value may be nil, or if non-nil, value must be an array of valid results column metadata maps.`

Sometimes, it is desirable to save a question that momentarily does not show any results, but _could_ yield results at some point in the future (which is usually the case with Pulse-associated questions).

**Comment by flamber** [comment] 2019-02-07 20:23
Would guess that this is a duplicate of #9286 - even though yours is for SQL.

**Comment by salsakran** [comment] 2019-04-10 04:56
dupe of #9286

**Closed by salsakran** 2019-04-10 04:56 UTC
