### ISSUE TITLE
[feature] Display the SQL being run

### ISSUE THREAD

**Issue by that0n3guy** [metabase/metabase#2518] opened 2016-05-03 14:16 UTC
I just realized it would be very nice to see the actual SQL that is being run.  

There are countless times I have a "question" in metabase and want to tweak it just slightly w/ some additional SQL.  I then have to re-write the query that metabase is doing and then do the tweak.   

It would save me soooo much time if I could just copy the sql, then start hacking on it.

**Comment by agilliland** [comment] 2016-05-03 15:44
This is a dupe of this issue #607 , can you go and add your vote for it there?

**Closed by agilliland** 2016-05-03 15:44 UTC
Labels: Duplicate
