### ISSUE TITLE
'Date Range' filter couldn't be applied on Native Queries

### ISSUE THREAD

**Issue by AmirTKashi** [metabase/metabase#13076] opened 2020-08-06 09:59 UTC
**Describe the bug**
When a Query is made in Native Query (or converted from Custom Question to SQL), the 'Date Range' filter couldn't be applied to the query.

**To Reproduce**
1. Create a 'Custom Question' with the sample data as shown in this image:
(Data:'Orders', Summarize: 'Sum of Subtotal' grouped by 'Product ID')

![1](https://user-images.githubusercontent.com/40166454/89511368-ba2b0000-d7c9-11ea-8aa7-2737564867ea.png)

Then visualise it with bars:

![image](https://user-images.githubusercontent.com/40166454/89511578-070ed680-d7ca-11ea-9dea-d163dd1182d1.png)

and save it as *Orders, Sum of Subtotal, Grouped by User*

2. Convert the Question to SQL, and save it as *Orders, Sum of Subtotal, Grouped by User - SQL*. You'll have a new question like this:

![2](https://user-images.githubusercontent.com/40166454/89515341-e1380080-d7ce-11ea-9e67-d1020301c7cc.png)

Where the query is:
```sql
SELECT "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID", sum("PUBLIC"."ORDERS"."SUBTOTAL") AS "sum"
FROM "PUBLIC"."ORDERS"
GROUP BY "PUBLIC"."ORDERS"."PRODUCT_ID"
ORDER BY "PUBLIC"."ORDERS"."PRODUCT_ID" ASC
```

3. Put both questions in a dashboard, and add a 'Date Range' filter to the dashboard. You'll have a dashboard like this:

![3](https://user-images.githubusercontent.com/40166454/89515831-8ce15080-d7cf-11ea-9f6a-2b47598ad195.png)

4. Edit the filter, and you'll see that it can be applied on the question made by custom question (left question in my dashboard), but not on the question made by the native query (right question in my dashboard):

![4](https://user-images.githubusercontent.com/40166454/89516240-16911e00-d7d0-11ea-953f-723c3102e8ca.png)

**What else I tried**
I have also seen this [discussion](https://discourse.metabase.com/t/a-sql-question-with-a-date-range-filter/811) on the Metabase forum and modified my query to:
```sql
SELECT "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID", sum("PUBLIC"."ORDERS"."SUBTOTAL") AS "sum"
FROM "PUBLIC"."ORDERS"
WHERE {{date}}
GROUP BY "PUBLIC"."ORDERS"."PRODUCT_ID"
ORDER BY "PUBLIC"."ORDERS"."PRODUCT_ID" ASC
```
but, it throws this error:
```text
Data conversion error converting "2018-07-12"; SQL statement: -- Metabase:: userID: 1 queryType: native queryHash: ce36a91f3aa06f0ab5e351d08b93dd59e4ed0246cdeaf1c416a8536b64f08ff3 SELECT "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID", sum("PUBLIC"."ORDERS"."SUBTOTAL") AS "sum" FROM "PUBLIC"."ORDERS" WHERE ? GROUP BY "PUBLIC"."ORDERS"."PRODUCT_ID" ORDER BY "PUBLIC"."ORDERS"."PRODUCT_ID" ASC [22018-197]
```

*Hint*
I can apply a single date filter on this query:

```sql
SELECT "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID", sum("PUBLIC"."ORDERS"."SUBTOTAL") AS "sum"
FROM "PUBLIC"."ORDERS"
WHERE [["PUBLIC"."ORDERS"."CREATED_AT"<{{date}}]]
GROUP BY "PUBLIC"."ORDERS"."PRODUCT_ID"
ORDER BY "PUBLIC"."ORDERS"."PRODUCT_ID" ASC
```
But I wanted to have a 'Date Range' filter.

**Information about your Metabase Installation:**
I am using Metabase  0.36.2 on a Fedora VM.

**Severity**
This issue is restricting my usage of Metabase and it forces me not to use native queries (and instead, I have to create materialised views on my database so I can make my questions in the 'Custom Question')

**Comment by flamber** [comment] 2020-08-06 10:08
Hi @AmirTKashi 
When you are using Native queries, then you need to define variables, so Metabase knows where it can input a filter.
And you need to create a Field Filter, but it looks like you are only using a Date filter, which you are then trying to link to a dashboard filter, which is Date Range.
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#the-field-filter-variable-type
Duplicate of #5781
Related to #4509/#3156

**Closed by flamber** 2020-08-06 10:08 UTC
Labels: .Needs Triage, Type:Bug

**Comment by AmirTKashi** [comment] 2020-08-06 10:59
Thank you,
That solved one of my big problems!
