### ISSUE TITLE
Activity feed telling me "You Joined!" but i've been on our metabase for several months now...

### ISSUE THREAD

**Issue by infomofo** [metabase/metabase#2667] opened 2016-05-25 15:07 UTC
If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is Mac OS.
*  I'm running Metabase ____. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is PSQL.
*  My Metabase version is 0.17.0-snapshot.

![image](https://cloud.githubusercontent.com/assets/539599/15544976/b448234a-2268-11e6-8a2c-64a866d01246.png)

**Comment by agilliland** [comment] 2016-05-25 15:59
This is a duplicate of #2448 which was resolved in #2452 and I suspect that what you are seeing there is just an old symptom of the issue which occurred before you upgraded to the version with the fix applied.

**Closed by agilliland** 2016-05-25 15:59 UTC
Labels: Duplicate
