### ISSUE TITLE
Dashboard filters are only commited on enter, not blur

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#4335] opened 2017-02-08 23:30 UTC
If I create a SQL query with two params, enter a value for the first, and hit `Tab` (which takes you to the next box) or click on the next box (or anywhere for that matter), the value in the first box is cleared. 

![out](https://cloud.githubusercontent.com/assets/1455846/22762177/e4e8a6ac-ee12-11e6-83ad-0d7db2026477.gif)

This is a somewhat-serious bug because it's basically impossible to use a SQL Question with more than one parameter 💔 

This is on the `public-embedding` branch (`0.23.0-SNAPSHOT`) with an unsaved Question.

**Comment by tlrobinson** [comment] 2017-02-08 23:32
IIRC it was an intention decision to require you hit "enter" to commit the filter. It also happens with a single param, as well as on dashboards.

We can certainly revisit whether we should commit-on-blur though.

**Comment by camsaul** [comment] 2017-02-08 23:34
The same thing happens if you just have one param and try to click to run the query:

![out](https://cloud.githubusercontent.com/assets/1455846/22762404/fec89a72-ee13-11e6-8de9-18c88a116cae.gif)

**Comment by camsaul** [comment] 2017-02-08 23:35
this behavior is pretty confusing, I think if a Metabase *developer* gets tripped up by it it's definitely going to trip up our users...

It's not indicated anywhere that you're supposed to press enter to "commit" a param. And if that's what's expected, should we allow people to tab between boxes?

**Comment by mazameli** [comment] 2017-02-08 23:46
Yeah, I'm having a hard time remembering why we went with having to hit enter to commit the filter. I think I advocated for that, but it definitely looks weird in practice. Commit on blur _or_ enter seems right, yeah?

**Comment by sldorman** [comment] 2017-11-14 16:27
I find that the biggest issue is related to bringing back large amounts of data.  If I have 2 filters to reduce the results and I have to hit enter after only entering 1 value (because it will disappear once I leave the field), then it may take longer than I want to retrieve the results.  Would be better if I could enter both values, then enter (or whatever) to get the results.

**Comment by flamber** [comment] 2019-02-17 04:38
Hi @camsaul 
I cannot reproduce this on 0.31.2 with Firefox 65 in Native Query, but I can reproduce in Dashboard.
So what to do, rename the issue again? :smirk: 
Commit on blur would be nice. I've seen multiple users inputting text and then clicking on the next filter, just to see their previous input disappearing.
- Native Query: Saves on blur
![screencast 2019-02-16 22 16 30](https://user-images.githubusercontent.com/1447303/52908390-cec4b280-323a-11e9-82df-e14cd09d5b10.gif)
- Dashboard: Reverts on blur
![screencast 2019-02-16 22 25 11](https://user-images.githubusercontent.com/1447303/52908391-d1270c80-323a-11e9-89bb-44f4bcc09f96.gif)

**Comment by ranquild** [comment] 2022-07-28 14:36
@flamber @mazameli I'm not sure if this issue is relevant anymore. While we don't save on `blur`, the UI has changed and now there is a button to add the filter. And pressing `tab` in the input will move focus to this button and not reset the value:

<img width="1230" alt="Screenshot 2022-07-28 at 17 34 54" src="https://user-images.githubusercontent.com/8542534/181555374-b4b45847-e669-4182-8b72-34edb806a38a.png">

**Comment by ranquild** [comment] 2022-08-04 07:53
Unassigning since the UI has changed and it's not clear what the correct behavior would be.

**Comment by uladzimirdev** [comment] 2023-07-25 10:41
@kdoh @mazameli I need your input. In terms of UI we have two types of inputs for parameters in QB: inline and with popup.

Inline saves value on enter and on tab
popup is more complicated, but it also saves value on enter
<img width="824" alt="image" src="https://github.com/metabase/metabase/assets/125459446/a3ffcce6-d6c0-45bf-b234-4478513bd42d">

The only problem I see atm is date picker, but it's completely unusable from keyboard, so you have to click "update date" anyway to save the data

Do you experience any issue with query parameters? Original issue is created for old version of metabase

**Comment by uladzimirdev** [comment] 2023-07-25 10:51
@mazameli @kdoh even if the issue name is about dashboard, examples here are about query builder params.

So for query builder we have two types of inputs: inline and with popup (multiple values).

- inline save value on change, so both blur and enter work fine
- with popup - enter only commits the value inside input, but to save and apply it you have to hit a button with mouse
- datepicker is completely unusable from keyboard, so it can be used only with mouse

As for dashboard filters, we have "popup" like inputs, where both enter and tab commit the value (puts it inside inbox), but blur (click on another filter) will remove the committed value. 
And I see it as the only wrong behaviour here. Could you please confirm and suggest some good UI pattern? 

https://www.loom.com/share/4b7a9b6748394491b299391a65f94f9c

**Comment by uladzimirdev** [comment] 2023-07-26 09:13
Original issue

> If I create a SQL query with two params, enter a value for the first, and hit Tab (which takes you to the next box) or click on the next box (or anywhere for that matter), the value in the first box is cleared.

It was addressed in previous version of the product, currently value is saved 

https://www.loom.com/share/d56e3b4dcf624258951f9297f7b3d38e

As @flamber [mentioned](https://github.com/metabase/metabase/issues/4335#issuecomment-464416428), problematic may be only editing filter values on some mobile devices, but we do not encourage working with dashboards on mobile (we even decided to hide edit button for small screens).

created an issue for date filter https://github.com/metabase/metabase/issues/32661

Regarding the lost value for the parameter with popup (without hitting enter), I didn't find any related issue, so current behaviour seems to be fine

**Closed by uladzimirdev** 2023-07-26 09:13 UTC
Labels: Type:Bug, Priority:P3, Reporting/Dashboards, Client:Mobile Web, Querying/Parameters & Variables, .Frontend, .Team/42 :milky_way:, .BugScope42
