### ISSUE TITLE
Dashboard or question migration 

### ISSUE THREAD

**Issue by Siddarth434** [metabase/metabase#8529] opened 2018-09-15 13:12 UTC
Hi

I want a way to migrate all dashboard or question from one instance to other. I use H2 database.

We first work on local environment, once Tested we move it to production which is a different instance. Please let me know a easy way of migration.

**Comment by jornh** [comment] 2018-09-16 07:36
Duplicate of https://github.com/metabase/metabase/issues/6485

**Comment by salsakran** [comment] 2018-12-28 03:50
we're working on this in #8845

**Comment by flamber** [comment] 2020-05-26 15:14
Closing in favor of #6485. The [Enterprise Edition](https://www.metabase.com/enterprise/) has [Serialization](https://www.metabase.com/docs/latest/enterprise-guide/serialization.html), which can do a lot of migration.

**Closed by flamber** 2020-05-26 15:14 UTC
Labels: Operation/
