### ISSUE TITLE
Cannot create field filter after upgrading to 0.39.0

### ISSUE THREAD

**Issue by nbrustein** [metabase/metabase#15730] opened 2021-04-21 21:25 UTC
**Describe the bug**

When I try to create field filters on text columns I get the message "There aren't any filter widgets for this type of field yet. Learn more".  

Other field types I've tried (timestamp, uuid) work as expected.

Field filters in reports that I created on text columns before the upgrade to 0.39.0 still work as expected.  I was able to create field filters recently. I believe it stopped working when we updated to 0.39.0, but I'm not 100% sure of that.

**Logs**
There are no errors in the browser console.

**To Reproduce**
1. Create a new native query
2. Add the following sql: `select * from my_table where {{my_filter}}`
3. Under "Variable Type", select "Field Filter"
4. Under "Field to map to", select "my_table", and then "my_col", where my_col is a text column.
5. See the message "There aren't any filter widgets for this type of field yet. Learn more".  Note that the filter has not appeared above the text editor as expected.

**Expected behavior**
I should be able to select text columns when creating field filters.

**Screenshots**

This is what it looks like when I try to create the filter:

<img width="711" alt="Screen Shot 2021-04-21 at 5 17 40 PM" src="https://user-images.githubusercontent.com/82556/115622273-a0810880-a2c5-11eb-98a5-f64de82f8942.png">

This shows the schema that's being used in the above screenshot.

<img width="986" alt="Screen Shot 2021-04-21 at 5 20 01 PM" src="https://user-images.githubusercontent.com/82556/115622620-184f3300-a2c6-11eb-92ca-58804b35450d.png">

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "4.14.225-168.357.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-19",
      "tag": "v0.39.0",
      "branch": "release-x.39.x",
      "hash": "5e40366"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
I can live without field filters, but they're convenient.  The longer it is before I can add them again, the more queries I'll have to go back and update from simple text filters to field filters.

**Comment by flamber** [comment] 2021-04-21 21:27
Duplicate of #15700 - upgrade to 0.39.0.1 - https://github.com/metabase/metabase/releases/tag/v0.39.0.1

**Closed by flamber** 2021-04-21 21:27 UTC
Labels: .Needs Triage, Type:Bug

**Comment by nbrustein** [comment] 2021-04-21 21:33
Oops. Sorry. I guess I only searched open tickets before filing the issue.  Thanks for the quick response.
