### ISSUE TITLE
Fail to generate sql with multiple group by condition

### ISSUE THREAD

**Issue by link89** [metabase/metabase#9179] opened 2018-12-28 03:00 UTC
Fail to generate sql with multiple group by condition

- Your browser and the version: chrome 71
- Your operating system: osx
- Your databases:Postgres
- Metabase version: 0.31.1
- Metabase hosting environment: Docker
- Metabase internal database:  H2 
- Reproduce steps: create a question with two condition in group by, and click get answer

**Comment by salsakran** [comment] 2018-12-28 03:38
Can't reproduce this.

Can you share the question you're trying to create, the schema of the table and any errors in the JS and Server logs?

**Comment by camsaul** [comment] 2019-01-03 01:39
Can't reproduce this either. @link89 ?

**Comment by mbvictoria** [comment] 2019-06-22 00:00
Closing - have been unable to reproduce and has needed for info for 6 months.

**Closed by mbvictoria** 2019-06-22 00:00 UTC
Labels: Need More Info, Unable to Reproduce
