### ISSUE TITLE
Failed to send email : java.lang.NullPointerException

### ISSUE THREAD

**Issue by vabhishek6** [metabase/metabase#9968] opened 2019-05-14 08:51 UTC
**Bug description**
Metabase logs report of a `java.lang.NullPointerException` post a `WARN metabase.email :: Failed to send email` warning.

**Technical details:**
- Metabase version: v0.32.7
- Operating System : Ubuntu 16.04.6 LTS 
- Metabase hosting environment: Ubuntu 16 VM
- Metabase internal database: Postgres
- Databases: MySQL, Postgres
- Command used to start : java -Xmx8g -jar /home/qa/Metabase/metabase.jar &
- Browser: Chromium Version 73.0.3683.86 (Official Build)

- *Repeatable steps to reproduce the issue*
Start metabase by running and observe the startup logs.

**Metabase Logs**
5-14 09:20:53 WARN metabase.email :: Failed to send email
java.lang.NullPointerException
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1204)
	at postal.smtp$smtp_send_STAR_.invokeStatic(smtp.clj:36)
	at postal.smtp$smtp_send_STAR_.invoke(smtp.clj:29)
	at postal.smtp$smtp_send.invokeStatic(smtp.clj:58)
	at postal.smtp$smtp_send.doInvoke(smtp.clj:39)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at postal.core$send_message.invokeStatic(core.clj:36)
	at postal.core$send_message.invoke(core.clj:29)
	at metabase.email$fn__26381$send_message_or_throw_BANG___26386$fn__26390.invoke(email.clj:93)
	at metabase.email$fn__26381$send_message_or_throw_BANG___26386.invoke(email.clj:84)
	at metabase.email$send_message_BANG_.invokeStatic(email.clj:118)
	at metabase.email$send_message_BANG_.doInvoke(email.clj:103)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at metabase.pulse$fn__57425.invokeStatic(pulse.clj:210)
	at metabase.pulse$fn__57425.invoke(pulse.clj:208)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at metabase.pulse$send_notifications_BANG_$fn__57432.invoke(pulse.clj:221)
	at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:220)
	at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:216)
	at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:249)
	at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:240)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at metabase.task.send_pulses$send_pulses_BANG_$fn__63311$fn__63312.invoke(send_pulses.clj:47)
	at metabase.models.task_history$fn__37607$do_with_task_history__37612$fn__37613.invoke(task_history.clj:77)
	at metabase.models.task_history$fn__37607$do_with_task_history__37612.invoke(task_history.clj:72)
	at metabase.task.send_pulses$send_pulses_BANG_$fn__63311.invoke(send_pulses.clj:44)
	at metabase.task.send_pulses$send_pulses_BANG_.invokeStatic(send_pulses.clj:43)
	at metabase.task.send_pulses$send_pulses_BANG_.invoke(send_pulses.clj:26)
	at metabase.task.send_pulses$send_pulses_BANG_.invokeStatic(send_pulses.clj:33)
	at metabase.task.send_pulses$send_pulses_BANG_.invoke(send_pulses.clj:26)
	at metabase.task.send_pulses.SendPulses$fn__63331.invoke(send_pulses.clj:88)
	at metabase.models.task_history$fn__37607$do_with_task_history__37612$fn__37613.invoke(task_history.clj:77)
	at metabase.models.task_history$fn__37607$do_with_task_history__37612.invoke(task_history.clj:72)
	at metabase.task.send_pulses.SendPulses.execute(send_pulses.clj:74)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property speak-punctuation.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property azimuth.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property speech-rate.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property pitch.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property richness.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property page-break.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property pause.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property cue-before.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property volume.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property cue.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property pause-after.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property speak-numeral.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property cue-after.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property pause-before.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property play-during.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property voice-family.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property speak.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property elevation.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property stress.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property speak-header.
05-14 09:20:54 WARN domassign.DeclarationTransformer :: Unable to find method for property pitch-range.
05-14 09:20:59 ERROR task.send-pulses :: Error sending Pulse 132
<eval>:4306 TypeError: formatter is not a function
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.runtime.Undefined.lookup(Undefined.java:102)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:106)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:98)
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
	at jdk.nashorn.internal.scripts.Script$Recompilation$344$131978AAA$\^eval\_.L:10#L:4262#makeCellBackgroundGetter#L:4301(<eval>:4306)
	at jdk.nashorn.internal.scripts.Script$Recompilation$343$129273AAA$\^eval\_.L:10#L:4187#L:4190#makeCellBackgroundGetter#L:4210(<eval>:4211)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:643)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117)
	at metabase.pulse.color$get_background_color.invokeStatic(color.clj:60)
	at metabase.pulse.color$get_background_color.invoke(color.clj:56)
	at metabase.pulse.render$render_table$fn__26682$fn__26684.invoke(render.clj:373)
	at clojure.core$map_indexed$mapi__8533$fn__8534.invoke(core.clj:7310)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$map$fn__5851.invoke(core.clj:2746)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:709)
	at clojure.core$next__5371.invokeStatic(core.clj:64)
	at clojure.core$str$fn__5451.invoke(core.clj:557)
	at clojure.core$str.invokeStatic(core.clj:555)
	at clojure.core$str.doInvoke(core.clj:544)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at hiccup.compiler$fn__25958.invokeStatic(compiler.clj:88)
	at hiccup.compiler$fn__25958.invoke(compiler.clj:82)
	at hiccup.compiler$fn__25941$G__25936__25946.invoke(compiler.clj:68)
	at clojure.core$map$fn__5851.invoke(core.clj:2753)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$apply.invokeStatic(core.clj:660)
	at clojure.core$apply.invoke(core.clj:660)
	at hiccup.compiler$fn__25958.invokeStatic(compiler.clj:88)
	at hiccup.compiler$fn__25958.invoke(compiler.clj:82)
	at hiccup.compiler$fn__25941$G__25936__25946.invoke(compiler.clj:68)
	at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
	at hiccup.compiler$render_element.invoke(compiler.clj:72)
	at hiccup.compiler$fn__25956.invokeStatic(compiler.clj:85)
	at hiccup.compiler$fn__25956.invoke(compiler.clj:82)
	at hiccup.compiler$fn__25941$G__25936__25946.invoke(compiler.clj:68)
	at clojure.core$map$fn__5851.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$apply.invokeStatic(core.clj:660)
	at clojure.core$apply.invoke(core.clj:660)
	at hiccup.compiler$fn__25958.invokeStatic(compiler.clj:88)
	at hiccup.compiler$fn__25958.invoke(compiler.clj:82)
	at hiccup.compiler$fn__25941$G__25936__25946.invoke(compiler.clj:68)
	at clojure.core$map$fn__5851.invoke(core.clj:2753)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$apply.invokeStatic(core.clj:660)
	at clojure.core$apply.invoke(core.clj:660)
	at hiccup.compiler$fn__25958.invokeStatic(compiler.clj:88)
	at hiccup.compiler$fn__25958.invoke(compiler.clj:82)
	at hiccup.compiler$fn__25941$G__25936__25946.invoke(compiler.clj:68)
	at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
	at hiccup.compiler$render_element.invoke(compiler.clj:72)
	at hiccup.compiler$fn__25956.invokeStatic(compiler.clj:85)
	at hiccup.compiler$fn__25956.invoke(compiler.clj:82)
	at hiccup.compiler$fn__25941$G__25936__25946.invoke(compiler.clj:68)
	at clojure.core$map$fn__5851.invoke(core.clj:2753)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$apply.invokeStatic(core.clj:660)
	at clojure.core$apply.invoke(core.clj:660)
	at hiccup.compiler$fn__25958.invokeStatic(compiler.clj:88)
	at hiccup.compiler$fn__25958.invoke(compiler.clj:82)
	at hiccup.compiler$fn__25941$G__25936__25946.invoke(compiler.clj:68)
	at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
	at hiccup.compiler$render_element.invoke(compiler.clj:72)
	at hiccup.compiler$fn__25956.invokeStatic(compiler.clj:85)
	at hiccup.compiler$fn__25956.invoke(compiler.clj:82)
	at hiccup.compiler$fn__25941$G__25936__25946.invoke(compiler.clj:68)
	at clojure.core$map$fn__5851.invoke(core.clj:2753)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$apply.invokeStatic(core.clj:660)
	at clojure.core$apply.invoke(core.clj:660)
	at hiccup.compiler$fn__25958.invokeStatic(compiler.clj:88)
	at hiccup.compiler$fn__25958.invoke(compiler.clj:82)
	at hiccup.compiler$fn__25941$G__25936__25946.invoke(compiler.clj:68)
	at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
	at hiccup.compiler$render_element.invoke(compiler.clj:72)
	at hiccup.compiler$fn__25956.invokeStatic(compiler.clj:85)
	at hiccup.compiler$fn__25956.invoke(compiler.clj:82)
	at hiccup.compiler$fn__25941$G__25936__25946.invoke(compiler.clj:68)
	at clojure.core$map$fn__5851.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1788)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at hiccup.compiler$fn__25958.invokeStatic(compiler.clj:88)
	at hiccup.compiler$fn__25958.invoke(compiler.clj:82)
	at hiccup.compiler$fn__25941$G__25936__25946.invoke(compiler.clj:68)
	at clojure.core$map$fn__5851.invoke(core.clj:2753)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$apply.invokeStatic(core.clj:660)
	at clojure.core$apply.invoke(core.clj:660)
	at hiccup.compiler$fn__25958.invokeStatic(compiler.clj:88)
	at hiccup.compiler$fn__25958.invoke(compiler.clj:82)
	at hiccup.compiler$fn__25941$G__25936__25946.invoke(compiler.clj:68)
	at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
	at hiccup.compiler$render_element.invoke(compiler.clj:72)
	at hiccup.compiler$fn__25956.invokeStatic(compiler.clj:85)
	at hiccup.compiler$fn__25956.invoke(compiler.clj:82)
	at hiccup.compiler$fn__25941$G__25936__25946.invoke(compiler.clj:68)
	at clojure.core$map$fn__5851.invoke(core.clj:2753)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$apply.invokeStatic(core.clj:660)
	at clojure.core$apply.invoke(core.clj:660)
	at hiccup.compiler$fn__25958.invokeStatic(compiler.clj:88)
	at hiccup.compiler$fn__25958.invoke(compiler.clj:82)
	at hiccup.compiler$fn__25941$G__25936__25946.invoke(compiler.clj:68)
	at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
	at hiccup.compiler$render_element.invoke(compiler.clj:72)
	at hiccup.compiler$fn__25956.invokeStatic(compiler.clj:85)
	at hiccup.compiler$fn__25956.invoke(compiler.clj:82)
	at hiccup.compiler$fn__25941$G__25936__25946.invoke(compiler.clj:68)
	at clojure.core$map$fn__5851.invoke(core.clj:2753)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$apply.invokeStatic(core.clj:660)
	at clojure.core$apply.invoke(core.clj:660)
	at hiccup.compiler$fn__25958.invokeStatic(compiler.clj:88)
	at hiccup.compiler$fn__25958.invoke(compiler.clj:82)
	at hiccup.compiler$fn__25941$G__25936__25946.invoke(compiler.clj:68)
	at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
	at hiccup.compiler$render_element.invoke(compiler.clj:72)
	at hiccup.compiler$fn__25956.invokeStatic(compiler.clj:85)
	at hiccup.compiler$fn__25956.invoke(compiler.clj:82)
	at hiccup.compiler$fn__25941$G__25936__25946.invoke(compiler.clj:68)
	at clojure.lang.Var.invoke(Var.java:384)
	at metabase.email.messages$render_message_body.invokeStatic(messages.clj:246)
	at metabase.email.messages$render_message_body.invoke(messages.clj:242)
	at metabase.email.messages$render_alert_email.invokeStatic(messages.clj:302)
	at metabase.email.messages$render_alert_email.invoke(messages.clj:298)
	at metabase.pulse$fn__57397.invokeStatic(pulse.clj:184)
	at metabase.pulse$fn__57397.invoke(pulse.clj:171)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.pulse$pulse__GT_notifications$iter__57459__57463$fn__57464$fn__57465.invoke(pulse.clj:238)
	at metabase.pulse$pulse__GT_notifications$iter__57459__57463$fn__57464.invoke(pulse.clj:236)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$seq__5387.invoke(core.clj:137)
	at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:217)
	at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:216)
	at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:249)
	at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:240)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at metabase.task.send_pulses$send_pulses_BANG_$fn__63311$fn__63312.invoke(send_pulses.clj:47)
	at metabase.models.task_history$fn__37607$do_with_task_history__37612$fn__37613.invoke(task_history.clj:77)
	at metabase.models.task_history$fn__37607$do_with_task_history__37612.invoke(task_history.clj:72)
	at metabase.task.send_pulses$send_pulses_BANG_$fn__63311.invoke(send_pulses.clj:44)
	at metabase.task.send_pulses$send_pulses_BANG_.invokeStatic(send_pulses.clj:43)
	at metabase.task.send_pulses$send_pulses_BANG_.invoke(send_pulses.clj:26)
	at metabase.task.send_pulses$send_pulses_BANG_.invokeStatic(send_pulses.clj:33)
	at metabase.task.send_pulses$send_pulses_BANG_.invoke(send_pulses.clj:26)
	at metabase.task.send_pulses.SendPulses$fn__63331.invoke(send_pulses.clj:88)
	at metabase.models.task_history$fn__37607$do_with_task_history__37612$fn__37613.invoke(task_history.clj:77)
	at metabase.models.task_history$fn__37607$do_with_task_history__37612.invoke(task_history.clj:72)
	at metabase.task.send_pulses.SendPulses.execute(send_pulses.clj:74)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)

**Comment by flamber** [comment] 2019-05-14 19:32
Hi @vabhishek6 Do you see anything in your mail server log?

**Comment by vabhishek6** [comment] 2019-05-15 08:15
@flamber nope the mail server logs dont point at anything that looks like an outlier.

**Comment by flamber** [comment] 2019-05-16 02:34
But do you even see a connection on the mail server from Metabase?
The error message is too general to figure out what's going on.

**Comment by flamber** [comment] 2019-07-12 19:08
Related to (probably duplicate of) #9891

**Comment by flamber** [comment] 2020-03-30 10:10
Closing because no response.

**Closed by flamber** 2020-03-30 10:10 UTC
Labels: .Need More Info, Reporting/Pulses
