### ISSUE TITLE
Adding new DB objects (schemas, tables, fields) and re-syncing also requires a hard browser refresh for them to appear

### ISSUE THREAD

**Issue by ryrobes** [metabase/metabase#10330] opened 2019-07-11 06:08 UTC
Basically title. ;)

Adding new database objects and triggering a re-sync has never repopulated the screen for me.

Again, I don't mean magically while I'm on the screen -  I mean when I leave admin and go back some time later (cached) they will never appear until I do a manual refresh on the Data Model selection page.

Trivial - but could lead to much frustration "waiting".

[Win 10, Chrome 64-bit Version 75.0.3770.100 (Official Build)]

**Comment by paulrosenzweig** [comment] 2019-08-29 21:30
I think this is because the front end doesn't know when to pull down the new database metadata. The `sync_schema` endpoint returns immediately and asynchronously does the sync. Is there some endpoint the front end could poll?

Or, if the sync is typically fast (<30 seconds?), could the sync endpoint do the work synchronously with some timeout? If the sync completes quickly, the endpoint returns a 200. If it's slow, the endpoint could return a 202 after the timeout elapsed and the front end would know to poll.

**Comment by mazameli** [comment] 2020-01-16 23:38
To add a related scenario, if you mark a table as "Hidden" in the Data Model, then exit the admin panel and go the Browse Data, the hidden table is still visible until you hard refresh the browser (see https://github.com/metabase/metabase/issues/11383). It feels like a sync should get triggered a few seconds after changes like these are made in the data model.

**Comment by flamber** [comment] 2020-04-08 11:20
Looks like a duplicate of #5129. Related to #11383, #10330, #9027, #5796

**Comment by ranquild** [comment] 2024-05-21 14:19
The issue should disappear when we move more stuff to RTK query

**Comment by ranquild** [comment] 2024-07-13 20:03
Duplicate of https://github.com/metabase/metabase/issues/10330

**Closed by ranquild** 2024-07-13 20:03 UTC
Labels: Type:Bug, Priority:P2, Difficulty:Hard, .Frontend, Querying/GUI, .Team/QueryingComponents
