### ISSUE TITLE
Characters after "," are deleted after applying 'Contains', 'Does not contain', 'Starts/Ends with' filter

### ISSUE THREAD

**Issue by mvrabel** [metabase/metabase#5542] opened 2017-07-21 12:49 UTC
- Your browser and the version: 59.0.3071.115 (64bit)
- Your operating system: Win10 (64bit)
- Your databases: Postgres 9.6
- Metabase version: 0.24.2
- Metabase hosting environment: CentOS Linux 7 (Core)
- Metabase internal database: H2 (default)

- **Repeatable steps to reproduce the issue**
1. Open question
2. Add filter for string column
3. Select Contains OR Does not contain OR Starts with OR Ends with filter
4. Type "Does, not, contain" into the search field

**Aftermath**
It will remove ", not, contain" string and will only filter out rows that contain 'Does'.

Is there a way to filter out fields like:

```
SELECT *
FROM <TABLE>
WHERE <TABLE>.<COLUMN> LIKE '%ASD%'
  OR <TABLE>.<COLUMN> LIKE '%JKL%'
```

**Comment by salsakran** [comment] 2017-07-25 02:36
@maz + @tlrobinson I remember we were talking about enters vs commas for multi-value fields. What was the expected behaviour here? I'm assuming we shouldn't _always_ be splitting on ",".

**Comment by flamber** [comment] 2019-02-16 04:57
Hi @mvrabel 
I cannot reproduce this issue on 0.31.2 - can you verify that it has been fixed since the version you used?
![image](https://user-images.githubusercontent.com/1447303/52894749-0832ea80-3175-11e9-983f-b6af46f3a117.png)
The first option of the auto-complete is selected, when pressing comma, which makes it tricky to input a string with commas, but that's a different issue.

**Comment by camsaul** [comment] 2019-09-28 01:53
Closing as already fixed. Thanks @flamber

**Closed by camsaul** 2019-09-28 01:53 UTC
Labels: Priority:P3, Query Builder, Type:Bug
