### ISSUE TITLE
Metabasev0.34.0：Android WeChat Browser Stuck on Pie Chart

### ISSUE THREAD

**Issue by iiAt-ch** [metabase/metabase#11591] opened 2019-12-26 02:19 UTC
Metabasev0.34.0：**Android WeChat Browser** Stuck on **Pie Chart**。Other charts open without problems。

**Comment by iiAt-ch** [comment] 2019-12-26 02:28
Tested v0.31.2 version without this problems

**Comment by iiAt-ch** [comment] 2019-12-26 03:40
![Record the screen](https://user-images.githubusercontent.com/28256364/71456482-84a24b00-27d4-11ea-8cf2-9e9e186cbd2f.gif)

**Comment by flamber** [comment] 2020-01-02 15:46
Hi @iiAt-ch 
Does it work with mobile versions of Chrome or Firefox (or other browsers)?
Does WeChat provide a way to see the browser console for errors, could you provide those?

**Comment by flamber** [comment] 2021-11-11 11:17
Closing, since I cannot reproduce, but Pie chart has been updated several times in the past couple of years.
If anyone is still experiencing this issue, please include a screenshot, and "Diagnostic Info" from Admin > Troubleshooting, and any other information that can be helpful in reproducing the problem.

**Closed by flamber** 2021-11-11 11:17 UTC
Labels: Type:Bug, Priority:P3, Client:Mobile Web
