### ISSUE TITLE
Date selection widget jumping up and down depending on number of weeks

### ISSUE THREAD

**Issue by gvwilson** [metabase/metabase#16015] opened 2021-05-12 15:39 UTC
**Describe the bug**
The prev/next arrow controls in the calendar widget move up and down depending on the number of weeks in the month, which makes date selection difficult.

**To Reproduce**

1. Add a filter widget to a dashboard.
2. Select 'Date' as type.
3. Try to specify early end of date range.

![May-12-2021 11-33-41](https://user-images.githubusercontent.com/911566/118003143-4d273680-b316-11eb-8e4d-b519f7793659.gif)

**Expected behavior**

The prev/next controls should stay put so that I can easily back up a couple of years rather than accidentally selecting the wrong date. (Explicit textual date entry, as other datetime widgets allow, would be a workaround.)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_291-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_291",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.291-b10",
    "os.name": "Mac OS X",
    "os.version": "10.16",
    "user.language": "en",
    "user.timezone": "America/Toronto"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "vUNKNOWN",
      "date": "2021-04-30",
      "branch": "master",
      "hash": "8df9d95"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

- Chrome Version 90.0.4430.93 (Official Build) (arm64)
- MacOS 11.2.3 (Big Sur) on M1

**Severity**

Annoyance.

**Comment by flamber** [comment] 2021-05-13 11:14
Duplicate of #14546

**Closed by flamber** 2021-05-13 11:14 UTC
Labels: .Needs Triage, Type:Bug
