### ISSUE TITLE
Confusing guide to running metabase on elastic beanstalk

### ISSUE THREAD

**Issue by harrybiddle** [metabase/metabase#15391] opened 2021-03-30 09:29 UTC
**Describe the bug**
The "Running Metabase on Elastic Beanstalk" is either broken or just confusing

**To Reproduce**
1. Visit https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html
2. Where it says "Download the Metabase Docker image to upload to Elastic Beanstalk" click on the link
3. You are redirected to the [AWS Console](https://console.aws.amazon.com/elasticbeanstalk/home?region=us-east-1#/newApplication?applicationName=Metabase&tierName=WebServer&platform=Docker&environmentType=LoadBalancing&sourceBundleUrl=https:%2F%2Fdownloads.metabase.com%2Fv0.38.2%2Fmetabase-aws-eb.zip&instanceType=t3a.small)
4. Later on   in the guide you are invited to "upload the file you dowloaded at the very beginning of this guide (metabase-aws-eb.zip)", but you have no such file

**Expected behavior**

I would expect that I am taken to a link where I can download the file.

**Hypothesis**

From the URL it looks like the guide is trying to be clever and auto-fill in the "source bundle URL". However, it is not filled in: it's just defaulting still to "Sample Application":

<img width="591" alt="image" src="https://user-images.githubusercontent.com/5887227/112966887-f17c6180-914a-11eb-8a90-8d046b15a7bb.png">

I presume this used to work and then AWS went and changed their frontend? 

Furthermore, if that is what it is trying to do, then the guide shouldn't be indicating that you should download a docker file, but rather it should get you to check that you are using the right source URL.

Possibly related to #14273 by @paoliniluis?

**Severity**

No severe, just annoying and confusing!

**Comment by flamber** [comment] 2021-03-30 09:35
Duplicate of #15205 fixed by #15206 - will be part of 0.38.3

**Comment by harrybiddle** [comment] 2021-03-30 09:36
Oh great, thanks! I had a search but I missed that issue

**Closed by flamber** 2021-03-30 09:35 UTC
Labels: .Needs Triage, Type:Bug
