### ISSUE TITLE
Can't edit question inside dashboard

### ISSUE THREAD

**Issue by kvosha** [metabase/metabase#8169] opened 2018-07-30 14:01 UTC
### Bug
- Browser and the version: Chrome 68.0.3440.75
- OS: Windows 10
- Postgres
- Metabase version: 0.29.3
- Metabase hosting environment:Docker
- Metabase internal database: default

How to reproduce:
- Create Native SQL Question with Progress bar
- Add it to dasboard
- Open dashboard
- Edit dashboard
- Click edit question
- .. nothing happens

Thanks

**Comment by jornh** [comment] 2018-08-03 18:24
Duplicate of https://github.com/metabase/metabase/issues/7246?

 If you agree then please close this issue and add 👍 and more info over there if you have.

Note https://github.com/metabase/metabase/issues/7246#issuecomment-391287318 - maybe you can confirm you experience the same?

**Comment by mazameli** [comment] 2018-08-03 18:46
Yep, a pretty clear duplicate of #7246.

**Closed by mazameli** 2018-08-03 18:46 UTC
Labels: Duplicate
