### ISSUE TITLE
Multiple values in dashboard category filters

### ISSUE THREAD

**Issue by luissancho** [metabase/metabase#4739] opened 2017-04-10 08:52 UTC
Now that we have complete date filters in dashboards (similar to questions date filters), it would be very useful if we could do the same with category filters, letting us select multiple options in dashboard filters (see image attached).

<img width="301" alt="multiple_option_dashboard_filters" src="https://cloud.githubusercontent.com/assets/12734676/24853499/8f886b04-1ddb-11e7-909f-98ec7633fc7c.png">

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by LukeAbell** [comment] 2017-04-19 21:19
Would LOVE this. I know, thumb it, don't comment. Just wanted to let you know how much we need this. Love you guys ❤️.

**Comment by Akilesh1989** [comment] 2017-07-11 14:54
+1

**Comment by camsaul** [comment] 2017-07-11 17:10
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by davesgonechina** [comment] 2017-09-11 17:19
This is very similar to https://github.com/metabase/metabase/issues/3736

**Comment by BenjaminRietpietsch** [comment] 2018-01-16 07:38
👍

**Comment by jornh** [comment] 2018-02-13 16:38
With #3736 implemented by #6563 and shipped as part of version 0.28: 

https://metabase.com/blog/Metabase-0.28/index.html#multi-select-dashboard-filters

can this be closed (as a duplicate) - or do anyone see anything more actionable here?

**Comment by mazameli** [comment] 2018-02-13 18:02
Good eye, @jornh. Yes, closing as a duplicate of #3736, which was implemented by #6563. This feature shipped with Metabase version 0.28.0. I hope it's working well for everyone!

**Closed by mazameli** 2018-02-13 18:02 UTC
Labels: Parameters/Variables, Proposal
