### ISSUE TITLE
Dashboard subscription rendering for MS Outlook in v0.41+ is not as clean as in Gmail

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#18925] opened 2021-11-09 23:18 UTC
**Is your feature request related to a problem? Please describe.**
We use Outlook 2019 for all our desktop email. We want to use the dashboard subscription functionality of Metabase, but the rendering of then emails by Outlook makes these look less than ideal.

The work done in v0.41 is great and definitely heading in the right direction, I think it looks pretty good in Gmail via browser and app. But in Outlook it doesn't give the same clean view. I'm aware that a lot of this is in the hands of the Outlook renderer, but thought it was worth raising in case there are some things you can tweak.

Here's an example from Gmail in the browser:
![image](https://user-images.githubusercontent.com/4504437/141018587-5da4b025-1ee3-44fe-a9a5-27a520828fd4.png)

And the same subscription in Outlook (I've had to zoom Outlook out to get the table visible):
![image](https://user-images.githubusercontent.com/4504437/141018608-35eb22a7-0709-4c65-b7ab-35cb011ef437.png)

Things that jump out at me in the Outlook version:
- the grey background covering most of the blank space
- the chart image is quite large. When not zoomed out it takes up the whole screen
- The table column widths are inconsistent, it's wrapping the long content quite aggressively, to me it's much easier to read on the Gmail version
- Overall table width doesn't match the chart width, feels like quite a bit of empty space on the right of the table

**Describe the solution you'd like**
I'd love if the emails could be rendered in Outlook the same way they render in Gmail.

**Describe alternatives you've considered**
None, we will use subscriptions as they are. We're stuck with Outlook for the time being.

**How important is this feature to you?**
Relatively important. I'm reluctant to really push the use of email subscriptions as the feedback I get from users is that they don't think the emails look very good when compared with the actual dashboards in Metabase. It's a user acceptance/perception thing really.

**Additional context**
Well aware of the limitations of Outlook, but still holding out hope that there's something you guys can do. The direction you guys are going with dashboard subscriptions looks really good, would be great if us Outlook users could get the most out of them too.

**Comment by paoliniluis** [comment] 2021-11-10 00:00
I have a feeling that the issue is a duplicate of https://github.com/metabase/metabase/issues/6874, so if you can complete that one it would be great

**Closed by paoliniluis** 2021-11-10 00:00 UTC
Labels: Type:New Feature, .Needs Triage
