### ISSUE TITLE
Filters unstable

### ISSUE THREAD

**Issue by mvanderb** [metabase/metabase#8354] opened 2018-08-17 18:49 UTC
When adding new filters in 0.30, the filters are not acting consistently.  There are 2 issues:

- If the type of a filter is changed, it jumps around.  If it's not at the top, it jumps there, if it is it jumps elsewhere.

Steps to reproduce:
1. Have more than 1 filter for a question.
2. Change the variable type of filter for the top filter.
Observe how it jumps from the top to the bottom of the list.
3. Now change the same filter's variable type again.
Observe how it jumps back up to the top of the list again.

- If there is a filter already set to variable type with a selected field in a table for it's 'Field to map to', changing another filter's variable type will inherit the same settings from the 1st filter.  Also, until the 2nd filter's data is changed it will reflect at least the "Field to map to" until the user changes the field.
Steps to reproduce:
1. Start a new question
2. Pick Native query
3. Write a simple query with a where clause of "where {{f1}} and {{f2}}
4. Select a variable type of 'Field Filter' for f1
5. Pick a table/column for f1
6. Select a variable type of 'Field Filter' for f2
Observe how it suddenly is populated with the same info as f1.
7. Change the column for f1 again.
Observe how the column in f2 also changed.

Verified that this happens in both Chrome and Internet Explorer on Win 10 for a Oracle database on 0.30 of Metabase.

**Comment by mazameli** [comment] 2018-08-17 18:50
Closing as duplicate of https://github.com/metabase/metabase/issues/8261

**Closed by mazameli** 2018-08-17 18:50 UTC
Labels: Duplicate
