### ISSUE TITLE
filters error when i use presto table

### ISSUE THREAD

**Issue by aCrazyOnion** [metabase/metabase#25129] opened 2022-08-31 09:14 UTC
I created a dashboard filter,then i found it's query faild.My datasource is presto.
Here is the log:

{:query
  "SELECT date(CAST(\"source\".\"dd\" AS date)) AS \"dd\", sum(CASE WHEN \"source\".\"is_history_new_good\" = 1 THEN \"source\".\"uv\" ELSE 0.0 END) AS \"历史新品uv\", sum(CASE WHEN \"source\".\"is_history_new_good\" = 1 THEN \"source\".\"trd_pay_ord_amt_1d_pct\" ELSE 0.0 END) AS \"历史新品支付金额\" FROM (SELECT \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"good_sn\" AS \"good_sn\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"pipeline_code\" AS \"pipeline_code\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"channel_code\" AS \"channel_code\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"platform_code\" AS \"platform_code\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"platform_name\" AS \"platform_name\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"goods_spu\" AS \"goods_spu\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"spu_title\" AS \"spu_title\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"leveli_category_name\" AS \"leveli_category_name\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"levelii_category_name\" AS \"levelii_category_name\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"leveliii_category_name\" AS \"leveliii_category_name\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"business_group\" AS \"business_group\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"business_division\" AS \"business_division\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"goods_cn_name\" AS \"goods_cn_name\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"main_image_url\" AS \"main_image_url\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"keyword\" AS \"keyword\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"lifecycle\" AS \"lifecycle\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"lifecycle_ch\" AS \"lifecycle_ch\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"market_price\" AS \"market_price\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"shop_price\" AS \"shop_price\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"rate\" AS \"rate\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"first_up_time\" AS \"first_up_time\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"currency_code\" AS \"currency_code\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"status\" AS \"status\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"status_ch\" AS \"status_ch\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"is_new_good\" AS \"is_new_good\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"is_inventory\" AS \"is_inventory\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"leveli_category_name_lang\" AS \"leveli_category_name_lang\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"levelii_category_name_lang\" AS \"levelii_category_name_lang\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"leveliii_category_name_lang\" AS \"leveliii_category_name_lang\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"is_history_new_good\" AS \"is_history_new_good\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"leveliii_category_pc_url\" AS \"leveliii_category_pc_url\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"leveliii_category_m_url\" AS \"leveliii_category_m_url\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"m_week_th\" AS \"m_week_th\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"pv\" AS \"pv\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"pv_hb\" AS \"pv_hb\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"uv\" AS \"uv\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"uv_hb\" AS \"uv_hb\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_user_cnt_1d_pct\" AS \"trd_pay_user_cnt_1d_pct\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_user_cnt_1d_pct_hb\" AS \"trd_pay_user_cnt_1d_pct_hb\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_ord_cnt_1d_pct\" AS \"trd_pay_ord_cnt_1d_pct\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_ord_qty_1d_pct\" AS \"trd_pay_ord_qty_1d_pct\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_ord_qty_1d_pct_hb\" AS \"trd_pay_ord_qty_1d_pct_hb\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_ord_amt_1d_pct\" AS \"trd_pay_ord_amt_1d_pct\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_ord_amt_1d_pct_hb\" AS \"trd_pay_ord_amt_1d_pct_hb\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_cur_ord_amt_1d_pct\" AS \"trd_pay_cur_ord_amt_1d_pct\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_ord_amt_1d_pctandscp\" AS \"trd_pay_ord_amt_1d_pctandscp\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_ord_qty_1d_pctandnet\" AS \"trd_pay_ord_qty_1d_pctandnet\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_ord_amt_1d_pctandnet\" AS \"trd_pay_ord_amt_1d_pctandnet\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_ctr_ord_cnt_1d\" AS \"trd_ctr_ord_cnt_1d\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_ctr_ord_user_cnt_1d\" AS \"trd_ctr_ord_user_cnt_1d\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_crt_ord_amt_1d\" AS \"trd_crt_ord_amt_1d\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"sale_stk_qty_1d_qc\" AS \"sale_stk_qty_1d_qc\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"days_30d_hvstk\" AS \"days_30d_hvstk\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"sale_qty_net30d\" AS \"sale_qty_net30d\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"sale_loss_qty_net30d\" AS \"sale_loss_qty_net30d\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"sale_loss_amt_net30d\" AS \"sale_loss_amt_net30d\", CAST(\"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"dd\" AS date) AS \"dd\", CAST(\"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"dd_sku\" AS date) AS \"dd_sku\", CAST(\"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"ds\" AS date) AS \"ds\", concat(\"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"pipeline_code\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"good_sn\") AS \"站点独立SKU编码\" FROM \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\" WHERE (CAST(\"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"ds\" AS date) >= date(now() AT TIME ZONE 'Asia/Shanghai') AND CAST(\"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"ds\" AS date) < date(date_add('day', 1, now())))) \"source\" WHERE \"source\".\"pipeline_code\" = ? GROUP BY date(CAST(\"source\".\"dd\" AS date)) ORDER BY date(CAST(\"source\".\"dd\" AS date)) ASC",
  :params ("US")},
 :status :failed,
 :class java.lang.RuntimeException,
 :stacktrace
 ["com.facebook.presto.jdbc.internal.client.StatementClientV1.requestFailedException(StatementClientV1.java:497)"
  "com.facebook.presto.jdbc.internal.client.StatementClientV1.advance(StatementClientV1.java:420)"
  "com.facebook.presto.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:1743)"
  "com.facebook.presto.jdbc.PrestoResultSet.<init>(PrestoResultSet.java:121)"
  "com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:272)"
  "com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:230)"
  "com.facebook.presto.jdbc.PrestoPreparedStatement.<init>(PrestoPreparedStatement.java:84)"
  "com.facebook.presto.jdbc.PrestoConnection.prepareStatement(PrestoConnection.java:142)"
  "com.facebook.presto.jdbc.PrestoConnection.prepareStatement(PrestoConnection.java:329)"
  "com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:385)"
  "--> driver.presto_jdbc$fn__89961.invokeStatic(presto_jdbc.clj:361)"
  "driver.presto_jdbc$fn__89961.invoke(presto_jdbc.clj:357)"
  "driver.sql_jdbc.execute$prepared_statement_STAR_.invokeStatic(execute.clj:335)"
  "driver.sql_jdbc.execute$prepared_statement_STAR_.invoke(execute.clj:332)"
  "driver.sql_jdbc.execute$statement_or_prepared_statement.invokeStatic(execute.clj:359)"
  "driver.sql_jdbc.execute$statement_or_prepared_statement.invoke(execute.clj:356)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:498)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:494)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
  "driver.sql_jdbc$fn__83581.invokeStatic(sql_jdbc.clj:54)"
  "driver.sql_jdbc$fn__83581.invoke(sql_jdbc.clj:52)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
  "query_processor.context.default$default_runf.invoke(default.clj:65)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
  "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___51447.invoke(cache.clj:220)"
  "query_processor.middleware.permissions$check_query_permissions$fn__47230.invoke(permissions.clj:109)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__50388.invoke(mbql_to_native.clj:23)"
  "query_processor$fn__52921$combined_post_process__52926$combined_post_process_STAR___52927.invoke(query_processor.clj:207)"
  "query_processor$fn__52921$combined_pre_process__52922$combined_pre_process_STAR___52923.invoke(query_processor.clj:204)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51368$fn__51373.invoke(resolve_database_and_driver.clj:35)"
  "driver$do_with_driver.invokeStatic(driver.clj:75)"
  "driver$do_with_driver.invoke(driver.clj:71)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51368.invoke(resolve_database_and_driver.clj:34)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47473.invoke(fetch_source_query.clj:277)"
  "query_processor.middleware.store$initialize_store$fn__47661$fn__47662.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__47661.invoke(store.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__51640.invoke(normalize_query.clj:22)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__48730.invoke(constraints.clj:53)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__51579.invoke(process_userland_query.clj:145)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51951.invoke(catch_exceptions.clj:168)"
  "query_processor.reducible$async_qp$qp_STAR___44200$thunk__44202.invoke(reducible.clj:100)"
  "query_processor.reducible$async_qp$qp_STAR___44200.invoke(reducible.clj:106)"
  "query_processor.reducible$async_qp$qp_STAR___44200.invoke(reducible.clj:91)"
  "query_processor.reducible$sync_qp$qp_STAR___44211.doInvoke(reducible.clj:126)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:326)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:322)"
  "query_processor$fn__52968$process_query_and_save_execution_BANG___52977$fn__52980.invoke(query_processor.clj:337)"
  "query_processor$fn__52968$process_query_and_save_execution_BANG___52977.invoke(query_processor.clj:330)"
  "query_processor$fn__53012$process_query_and_save_with_max_results_constraints_BANG___53021$fn__53024.invoke(query_processor.clj:349)"
  "query_processor$fn__53012$process_query_and_save_with_max_results_constraints_BANG___53021.invoke(query_processor.clj:342)"
  "api.dataset$run_query_async$fn__66704.invoke(dataset.clj:68)"
  "query_processor.streaming$streaming_response_STAR_$fn__39322$fn__39323.invoke(streaming.clj:162)"
  "query_processor.streaming$streaming_response_STAR_$fn__39322.invoke(streaming.clj:161)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$task__18948.invoke(streaming_response.clj:84)"],
 :card_id 386,
 :context :ad-hoc,
 :error "Error executing query",
 :row_count 0,
 :running_time 0,
 :preprocessed

**Comment by aCrazyOnion** [comment] 2022-09-01 01:49
> Post "Diagnostic Info" from Admin > Troubleshooting. And your PrestoDB version.

here is the version:
metabase v0.43.4
presto-server-0.275
i will post the "Diagnostic Info" later,now i'm not familiar with it.

**Comment by aCrazyOnion** [comment] 2022-09-01 08:30
> Post "Diagnostic Info" from Admin > Troubleshooting. And your PrestoDB version.

and i found i can't use "" in quering presto sql,here is the example("US" is the parameter sent by metabase front end):
select
    *
from hive.ads.ads_sap_pipe_goods_plat_channel_analysis_df
where pipeline_code = "US"
;

**Comment by flamber** [comment] 2022-09-01 09:23
@aCrazyOnion 
Please include the full stacktrace. And try with the latest release 0.44.2: https://github.com/metabase/metabase/releases/latest

Metabase does not send double-quotes, it's a parameter sent to the driver.
If you use SQL, then you would use single-quotes, since you control the entire SQL query.

I cannot reproduce based on the information you have provided.

**Comment by aCrazyOnion** [comment] 2022-09-01 09:31
> @aCrazyOnion Please include the full stacktrace. And try with the latest release 0.44.2: https://github.com/metabase/metabase/releases/latest
> 
> Metabase does not send double-quotes, it's a parameter sent to the driver. If you use SQL, then you would use single-quotes, since you control the entire SQL query.
> 
> I cannot reproduce based on the information you have provided.
"full stacktrace" ,u mean Admin > Troubleshooting > Logs?

**Comment by flamber** [comment] 2022-09-01 09:36
@aCrazyOnion I mean the full stacktrace. You are missing the entire end of the stacktrace. It's only half.
And provide steps-to-reproduce, otherwise it will be impossible to know what is going on.

**Comment by aCrazyOnion** [comment] 2022-09-01 09:45
> @aCrazyOnion I mean the full stacktrace. You are missing the entire end of the stacktrace. It's only half. And provide steps-to-reproduce, otherwise it will be impossible to know what is going on.

{:database_id 2,
 :started_at #t "2022-09-01T09:31:45.181078Z[GMT]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "执行查询时出错。null",
   :stacktrace
   ["--> driver.bigquery_cloud_sdk$throw_invalid_query.invokeStatic(bigquery_cloud_sdk.clj:173)"
    "driver.bigquery_cloud_sdk$throw_invalid_query.invoke(bigquery_cloud_sdk.clj:172)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:215)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:177)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:219)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:217)"
    "driver.bigquery_cloud_sdk$process_native_STAR_$thunk__81161.invoke(bigquery_cloud_sdk.clj:279)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:287)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invoke(bigquery_cloud_sdk.clj:271)"
    "driver.bigquery_cloud_sdk$fn__81167.invokeStatic(bigquery_cloud_sdk.clj:307)"
    "driver.bigquery_cloud_sdk$fn__81167.invoke(bigquery_cloud_sdk.clj:299)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
    "query_processor.context.default$default_runf.invoke(default.clj:65)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
    "query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:193)"
    "query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:178)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___51447.invoke(cache.clj:219)"
    "query_processor.middleware.permissions$check_query_permissions$fn__47230.invoke(permissions.clj:109)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__50388.invoke(mbql_to_native.clj:23)"
    "query_processor$fn__52921$combined_post_process__52926$combined_post_process_STAR___52927.invoke(query_processor.clj:207)"
    "query_processor$fn__52921$combined_pre_process__52922$combined_pre_process_STAR___52923.invoke(query_processor.clj:204)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51368$fn__51373.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:75)"
    "driver$do_with_driver.invoke(driver.clj:71)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51368.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47473.invoke(fetch_source_query.clj:277)"
    "query_processor.middleware.store$initialize_store$fn__47661$fn__47662.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__47661.invoke(store.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__51640.invoke(normalize_query.clj:22)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__48730.invoke(constraints.clj:53)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__51579.invoke(process_userland_query.clj:145)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51951.invoke(catch_exceptions.clj:168)"
    "query_processor.reducible$async_qp$qp_STAR___44200$thunk__44202.invoke(reducible.clj:100)"
    "query_processor.reducible$async_qp$qp_STAR___44200$fn__44204.invoke(reducible.clj:105)"],
   :error_type :invalid-query,
   :ex-data
   {:type :invalid-query,
    :sql
    "SELECT datetime_trunc(CAST(`source`.`dd` AS datetime), day) AS `dd`, `source`.`pipeline_code` AS `pipeline_code`, (CAST(count(distinct `source`.`__sku___2`) AS float64) / CASE WHEN count(distinct `source`.`good_sn`) = 0 THEN NULL ELSE count(distinct `source`.`good_sn`) END) AS `___` FROM (SELECT `source`.`good_sn` AS `good_sn`, `source`.`pipeline_code` AS `pipeline_code`, `source`.`dd` AS `dd`, `source`.`status` AS `status`, `source`.`sale_stk_qty_1d_qc` AS `sale_stk_qty_1d_qc`, `source`.`sale_stk_qty_1d_qm` AS `sale_stk_qty_1d_qm`, `source`.`business_division` AS `business_division`, `source`.`business_group` AS `business_group`, `source`.`status_ch` AS `status_ch`, `source`.`lifecycle_ch` AS `lifecycle_ch`, CASE WHEN `source`.`status` = 1 THEN `source`.`good_sn` END AS `__sku__`, CASE WHEN `source`.`sale_stk_qty_1d_qc` = 0 THEN `source`.`good_sn` END AS `__sku___2` FROM (with query1 as (\n   select \n      pipeline_code,\n      good_sn,\n      stock_goods_cnt_1d_nostk, \n      sale_stk_qty_1d_qc, \n      sale_stk_qty_1d_qm, \n      dd \n   from \n      dws.dws_stock_in_1d_di\n   where dd >= '2022-06-01'\n)\n,query2 as (\n   select \n      pipeline_code,\n      good_sn,\n      dd,\n      status  \n   from \n      dim.dim_item_pipe_goods_relation_df\n   where dd >= '2022-06-01'\n   group by \n      pipeline_code,\n      good_sn,\n      dd,\n      status \n   )\n,query3 as (\n   select \n      good_sn,\n      business_group,\n      business_division\n   from \n      dim.dim_item_goods_info_df\n   where dd = date_sub(CURRENT_DATE(), INTERVAL 1 day)\n)\n,query4 as (\n   select \n      pipeline_code,\n      good_sn,\n      status_ch, \n      lifecycle_ch \n   from \n      dim.dim_item_pipe_goods_relation_df\n   where dd = date_sub(CURRENT_DATE(), INTERVAL 1 day)\n)\nselect \n   coalesce(query1.good_sn, query2.good_sn) as good_sn, \n   coalesce(query1.pipeline_code, query2.pipeline_code) as pipeline_code, \n   coalesce(query1.dd, query2.dd) as dd, \n   coalesce(query2.status, 9999) as status, \n   coalesce(query1.sale_stk_qty_1d_qc, 0) as sale_stk_qty_1d_qc, \n   coalesce(query1.sale_stk_qty_1d_qm, 0) as sale_stk_qty_1d_qm, \n   query3.business_division,    \n   query3.business_group, \n   query4.status_ch, \n   query4.lifecycle_ch \nfrom \n   query1\nfull join \n   query2\non query1.pipeline_code = query2.pipeline_code and query1.good_sn = query2.good_sn\nleft join \n   query3\non coalesce(query1.good_sn, query2.good_sn) = query3.good_sn\nleft join\n   query4\non coalesce(query1.good_sn, query2.good_sn) = query4.good_sn and coalesce(query1.pipeline_code, query2.pipeline_code) = query4.pipeline_code) `source`) `source` WHERE (`source`.`dd` >= date_trunc(date_add(current_date(), INTERVAL -30 day), day) AND `source`.`dd` < date_trunc(current_date(), day) AND `source`.`pipeline_code` = ?) GROUP BY `dd`, `pipeline_code` ORDER BY `dd` ASC, `pipeline_code` ASC",
    :parameters ("US")}}],
 :error_type :invalid-query,
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true, :ignore-cached-results? false},
  :database 2,
  :query
  {:aggregation
   [[:aggregation-options
     [:/ [:distinct [:expression "断货sku编码"]] [:distinct [:field "good_sn" {:base-type :type/Text}]]]
     {:display-name "断货率", :name "断货率"}]],
   :breakout
   [[:field "dd" {:base-type :type/Date, :temporal-unit :day}] [:field "pipeline_code" {:base-type :type/Text}]],
   :expressions
   {"在线sku编码"
    [:case [[[:= [:field "status" {:base-type :type/Integer}] 1] [:field "good_sn" {:base-type :type/Text}]]]],
    "断货sku编码"
    [:case
     [[[:= [:field "sale_stk_qty_1d_qc" {:base-type :type/Integer}] 0] [:field "good_sn" {:base-type :type/Text}]]]]},
   :source-table "card__167",
   :filter [:time-interval [:field "dd" {:base-type :type/Date}] -30 :day {:include-current false}]},
  :parameters
  [{:type :string/=,
    :value ["US"],
    :target [:dimension [:field "pipeline_code" {:base-type :type/Text}]],
    :id "2e270a6e"}],
  :async? true,
  :cache-ttl 7184},
 :native nil,
 :status :failed,
 :class java.util.concurrent.CancellationException,
 :stacktrace
 ["java.base/java.util.concurrent.FutureTask.report(Unknown Source)"
  "java.base/java.util.concurrent.FutureTask.get(Unknown Source)"
  "clojure.core$deref_future.invokeStatic(core.clj:2304)"
  "clojure.core$future_call$reify__8477.deref(core.clj:6976)"
  "clojure.core$deref.invokeStatic(core.clj:2324)"
  "clojure.core$deref.invoke(core.clj:2310)"
  "--> driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:181)"
  "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:177)"
  "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:219)"
  "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:217)"
  "driver.bigquery_cloud_sdk$process_native_STAR_$thunk__81161.invoke(bigquery_cloud_sdk.clj:279)"
  "driver.bigquery_cloud_sdk$process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:287)"
  "driver.bigquery_cloud_sdk$process_native_STAR_.invoke(bigquery_cloud_sdk.clj:271)"
  "driver.bigquery_cloud_sdk$fn__81167.invokeStatic(bigquery_cloud_sdk.clj:307)"
  "driver.bigquery_cloud_sdk$fn__81167.invoke(bigquery_cloud_sdk.clj:299)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
  "query_processor.context.default$default_runf.invoke(default.clj:65)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
  "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
  "query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:193)"
  "query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:178)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___51447.invoke(cache.clj:219)"
  "query_processor.middleware.permissions$check_query_permissions$fn__47230.invoke(permissions.clj:109)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__50388.invoke(mbql_to_native.clj:23)"
  "query_processor$fn__52921$combined_post_process__52926$combined_post_process_STAR___52927.invoke(query_processor.clj:207)"
  "query_processor$fn__52921$combined_pre_process__52922$combined_pre_process_STAR___52923.invoke(query_processor.clj:204)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51368$fn__51373.invoke(resolve_database_and_driver.clj:35)"
  "driver$do_with_driver.invokeStatic(driver.clj:75)"
  "driver$do_with_driver.invoke(driver.clj:71)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51368.invoke(resolve_database_and_driver.clj:34)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47473.invoke(fetch_source_query.clj:277)"
  "query_processor.middleware.store$initialize_store$fn__47661$fn__47662.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__47661.invoke(store.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__51640.invoke(normalize_query.clj:22)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__48730.invoke(constraints.clj:53)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__51579.invoke(process_userland_query.clj:145)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51951.invoke(catch_exceptions.clj:168)"
  "query_processor.reducible$async_qp$qp_STAR___44200$thunk__44202.invoke(reducible.clj:100)"
  "query_processor.reducible$async_qp$qp_STAR___44200$fn__44204.invoke(reducible.clj:105)"],
 :card_id 326,
 :context :dashboard,
 :error nil,
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true, :ignore-cached-results? false},
  :user-parameters
  [{:type :string/=,
    :value ["US"],
    :target [:dimension [:field "pipeline_code" {:base-type :type/Text}]],
    :id "2e270a6e"}],
  :info {:executed-by 75, :context :dashboard, :card-id 326, :card-name "断货趋势折线图", :dashboard-id 119},
  :database 2,

**Comment by flamber** [comment] 2022-09-01 09:56
@aCrazyOnion Now you are including a stacktrace from BigQuery. This is getting very difficult to help with.
I would advise you create a new issue and provide all the requested details, but most importantly clear steps-to-reproduce.
Make sure you have upgraded to 0.44.2 first.
I'm going to close this issue, since we cannot fix issues without understanding how to reproduce.

**Closed by flamber** 2022-09-01 09:56 UTC
Labels: Type:Bug, .Needs Triage

**Comment by aCrazyOnion** [comment] 2022-09-01 10:08
> @aCrazyOnion Now you are including a stacktrace from BigQuery. This is getting very difficult to help with. I would advise you create a new issue and provide all the requested details, but most importantly clear steps-to-reproduce. Make sure you have upgraded to 0.44.2 first. I'm going to close this issue, since we cannot fix issues without understanding how to reproduce.

ok,thank you for your help!
