### ISSUE TITLE
Google Analytics - Filter by Prior [X] Months Breaks "Last Month"

### ISSUE THREAD

**Issue by chucksense** [metabase/metabase#10701] opened 2019-08-23 19:58 UTC
**Describe the bug**
When creating a question based on Google Analytics and using the date filter of "Previous [X] Months" (with this month unchecked), the Last Month data is not pulled in correctly.  It only pulls the data from the first day of last month.

**To Reproduce**
Pre-requisite, link with a Google Analytics account.

1. Create a new question
2. Select Google Analytics Profile
3. Filter by Date -> Previous 4 Months, leave "Include **this month**" as unchecked.
4. Select View -> Users
5. Select Grouped by -> Date: Day

**Expected behavior**
Would include all data through the last day of the prior month.

**Actual behavior**
Includes only data through the first day of the prior month.

**Information about your Metabase Installation:**
- Metabase version:  0.32.9
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

**Severity**
Blocking a dashboard metric that is requested.

**Comment by salsakran** [comment] 2019-10-06 22:15
Bumping priority to match other GA timezone bugs. Think it's all one root cause.

**Comment by camsaul** [comment] 2019-11-25 20:08
@mazameli reported he was still seeing this on November 21st 2019, need to verify whether it is actually fixed yet or not

**Comment by camsaul** [comment] 2019-12-10 01:52
This is confirmed fixed on `master`

![Screen Shot 2019-12-09 at 5 50 38 PM](https://user-images.githubusercontent.com/1455846/70488140-971a4600-1aac-11ea-896c-60340c671c38.png)

**Closed by camsaul** 2019-12-10 01:52 UTC
Labels: Database/Google Analytics, Misc/Timezones, Priority:P1, Type:Bug
