### ISSUE TITLE
Problem trying to add a text box

### ISSUE THREAD

**Issue by kip-13** [metabase/metabase#7551] opened 2018-05-04 17:36 UTC
Info
---

**OS**
```CentOS release 6.9 (Final)```
**Metabase**
```Metabase version v0.29.0```
**Metabase hosting**
```Docker version 1.7.1, build 786b29d/1.7.1```
**DB**
```MySQL Community Server (GPL) 5.7.20```

----

Hi, I have a problem when I try to add a "text box" in all dashboards, this is the error:

```javascript
{
   "message":"Column 'card_id' cannot be null",
   "type":"class com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException",
   "stacktrace":[
      "models.dashboard_card$fn__35931$create_dashboard_card_BANG___35936$fn__35937$fn__35939.invoke(dashboard_card.clj:151)",
      "models.dashboard_card$fn__35931$create_dashboard_card_BANG___35936$fn__35937.invoke(dashboard_card.clj:150)",
      "models.dashboard_card$fn__35931$create_dashboard_card_BANG___35936.invoke(dashboard_card.clj:144)",
      "models.dashboard$add_dashcard_BANG_.invokeStatic(dashboard.clj:215)",
      "models.dashboard$add_dashcard_BANG_.doInvoke(dashboard.clj:202)",
      "api.dashboard$fn__41383$fn__41386.invoke(dashboard.clj:256)",
      "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:254)",
      "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)",
      "api.dashboard$fn__41383.invokeStatic(dashboard.clj:248)",
      "api.dashboard$fn__41383.invoke(dashboard.clj:248)",
      "middleware$enforce_authentication$fn__38506.invoke(middleware.clj:118)",
      "api.routes$fn__49378.invokeStatic(routes.clj:66)",
      "api.routes$fn__49378.invoke(routes.clj:66)",
      "routes$fn__49469$fn__49470.doInvoke(routes.clj:108)",
      "routes$fn__49469.invokeStatic(routes.clj:103)",
      "routes$fn__49469.invoke(routes.clj:103)",
      "middleware$log_api_call$fn__38605$fn__38607.invoke(middleware.clj:349)",
      "middleware$log_api_call$fn__38605.invoke(middleware.clj:348)",
      "middleware$add_security_headers$fn__38555.invoke(middleware.clj:251)",
      "core$wrap_streamed_json_response$fn__54821.invoke(core.clj:67)",
      "middleware$bind_current_user$fn__38510.invoke(middleware.clj:139)",
      "middleware$maybe_set_site_url$fn__38559.invoke(middleware.clj:275)"
   ],
   "sql-exception-chain":[
      "MySQLIntegrityConstraintViolationException:",
      "Message: Column 'card_id' cannot be null",
      "SQLState: 23000",
      "Error Code: 1048"
   ]
}
```

I figured out how solve this problem, the column `card_id` in `report_dashboardcard` have a `NOT NULL` property and if I change this property to false, the text box is added without problems.

**Why ?**
I think is because this text box is not a question and is not created in `report_card` and its value is saved in `visualization_settings` a column of `report_dashboardcard`.

I dont know if this is a bug....

**Comment by mazameli** [comment] 2018-05-04 17:45
You mention this is happening in "in some dashboards," so are you able to create them in other cases? Are there any other steps to reliably reproduce this error?

**Comment by kip-13** [comment] 2018-05-04 18:44
@mazameli sorry, in all dashboards, I dont know why I writed 'some', sorry again.

Simply add a text box to some dashboard and when you try to save, the button show `SAVE FAILED` and in the console you get the error that I mentioned above, see:

![](http://g.recordit.co/Kd1BPfhnVO.gif)

**Comment by jornh** [comment] 2018-05-05 05:37
@kip-13 good clear bug report with well thought through analysis 😄👍 

The `NOT NULL` constraint was removed [in changeset 71](https://github.com/metabase/metabase/blob/c1ab5aedb2cec270402537722296731f0bdb05fe/resources/migrations/000_migrations.yaml#L3995) in the database migration file. Seems it was done specifically to allow for text cards. So the database change you made manually seems right. 

Is your install a fresh one or has it been migrated? It seems this migration was somehow missed. It would be good to nail if it’s something specific to your install or if it can go generally wrong with MySQL with a way to reproduce the problem.

**Comment by kip-13** [comment] 2018-05-06 00:10
@jornh the install has been migrated.

I created antoher container linked with antoher database(empty) in the same MySQL environment to try get this "bug" but when I added the text box, the dashboard was saved without any problems !

I think that the migration does not set the constraint correctly....

**Comment by mazameli** [comment] 2018-05-07 16:15
Hmm, interesting. Do you remember which version of Metabase you were running before the upgrade+migration?

**Comment by kip-13** [comment] 2018-05-07 17:03
The first instance that we run was ` v0.25.2` and after this all was migrations I supossed, no ?

The migration exist in the database:

Name         |Value                                                                   |
-------------|------------------------------------------------------------------------|
ID           |71                                                                      |
AUTHOR       |camsaul                                                                 |
FILENAME     |migrations/000_migrations.yaml                                          |
DATEEXECUTED |2018-02-28 15:29:58                                                     |
ORDEREXECUTED|69                                                                      |
EXECTYPE     |EXECUTED                                                                |
MD5SUM       |7:c538632c79c29ec8a18d34b27615c5ee                                      |
DESCRIPTION  |dropNotNullConstraint columnName=card_id, tableName=report_dashboardcard|
COMMENTS     |Added 0.28.0                                                            |
TAG          |                                                                        |
LIQUIBASE    |3.5.3                                                                   |
CONTEXTS     |                                                                        |
LABELS       |                                                                        |
DEPLOYMENT_ID|9831761790                                                              |

**Comment by flamber** [comment] 2020-05-23 18:20
Closing this, since it hasn't been reported by others. Not sure how the constraint changed between the migration script and the manual modification. Please comment if this is still a problem.

**Closed by flamber** 2020-05-23 18:20 UTC
Labels: Priority:P2, Reporting/Dashboards, Type:Bug
