### ISSUE TITLE
Time filter/granularity dropdowns not appearing if time is second breakout

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5175] opened 2017-05-23 18:05 UTC
They appear as expected here, when time breakout is first:

<img width="898" alt="screen shot 2017-05-23 at 11 03 18 am" src="https://cloud.githubusercontent.com/assets/2223916/26368781/89998e38-3fa7-11e7-9d0f-cdc5a396dd55.png">

But they don't appear if the breakout order is swapped:

<img width="884" alt="screen shot 2017-05-23 at 11 03 10 am" src="https://cloud.githubusercontent.com/assets/2223916/26368827/a22c4fe4-3fa7-11e7-8b5a-9a9681a19c20.png">

**Comment by tlrobinson** [comment] 2017-05-23 18:12
That's not a bug according to how the "modes" were originally defined. At least according to my understanding.

**Comment by tlrobinson** [comment] 2017-05-23 18:13
(Though I agree it seems kind of weird)

**Comment by mazameli** [comment] 2017-05-23 18:19
Gotcha. I think it feels particularly weird since the order of the breakouts doesn't seem to affect the resultant visualization (or underlying pivot table) in any way. I.e., if the shape of the resultant data is the same, shouldn't this be an equivalent "mode?"

**Comment by tlrobinson** [comment] 2017-05-23 18:23
Probably, yeah. I don't know if @salsakran had a reason for specifying the first breakout had to be time.

**Comment by salsakran** [comment] 2017-06-03 03:13
eh. it made sense at the time =)

**Comment by attekei** [comment] 2017-07-18 00:28
I think that in order to support timeseries mode when we have time as n:th breakout where n≠1 we have to modify time filter/granularity dropdowns and possibly drill-through actions too so that they look for the first time breakout and use that.

Changing the condition itself whether to have the mode active or not should be trivial.

**Comment by flamber** [comment] 2020-05-25 19:34
Closing, since granularity went missing in 0.33 - #11183

**Closed by flamber** 2020-05-25 19:34 UTC
Labels: Priority:P3, Type:Bug, Type:UX
