### ISSUE TITLE
Query Builder Questions using dashboard date filters broken on 0.31.2

### ISSUE THREAD

**Issue by bcbob** [metabase/metabase#9090] opened 2018-12-09 08:09 UTC
Dashboard date filters on single dates do not work for question builder questions.

For example, using the sample dataset create a simple GUI raw data question on the ORDERS table.
Then add it to a dashboard and setup a single date filter.

Try filtering for orders on 11 Feb 2019.
No results will appear unless you filter for orders BETWEEN 11 Feb 2019 and 11 Feb 2019.

This is the simplest example of an issue that has broken many of the dashboards we use. 

Does anyone else have broken dashboards using single date filters on question builder questions? I ask because it would seem this simple issue has been missed since 0.31.0, when it first cropped up. Up until that point, our dashboards worked fine.

<img width="661" alt="screen shot 2018-11-25 at 4 22 54 pm" src="https://user-images.githubusercontent.com/30799811/48980179-8039c900-f0ce-11e8-8347-3402bad14a26.png">

<img width="872" alt="screen shot 2018-11-25 at 4 27 16 pm" src="https://user-images.githubusercontent.com/30799811/48980246-24237480-f0cf-11e8-87c2-805ebaa6fd60.png">

<img width="1309" alt="screen shot 2018-11-25 at 4 27 57 pm" src="https://user-images.githubusercontent.com/30799811/48980252-2c7baf80-f0cf-11e8-8271-350e39218ede.png">

_Originally posted by @bcbob in https://github.com/metabase/metabase/issues/8932#issuecomment-441444648_

**Comment by lukecarazzo** [comment] 2018-12-13 14:18
@bcbob I am also still having the same issues. I am still on Version 0.30.4 where the date filters work fine. I have had to test each version that has been released and had to revert back to 0.30.4 as each release has the bug.

**Comment by lukecarazzo** [comment] 2018-12-13 14:19
I really hope that this issue gets resolved in the new release so that I can get all the upgrades in the newer versions.

**Comment by bcbob** [comment] 2018-12-13 14:30
@lukecarazzo I'm pleased to know I'm not the only one. It almost seems that way 😐 I expected date filters on dashboards to be a core feature and that almost all users would be affected by this? But you and I seem to be all alone in the user base...?

**Comment by anandabudi** [comment] 2018-12-14 09:09
Guys, you're not alone.. I also have the same problem with date filters + Google BigQuery with the latest Metabase 😐

**Comment by bcbob** [comment] 2018-12-14 10:40
Please give the overall issue a thumbs up to bump it up the dev team priority list if you also have broken dashboards! They have a lot on their plates ... this is kind of mission critical for everyone with existing dashboards in use wanting to upgrade to 0.31.x!

**Comment by mazameli** [comment] 2018-12-14 18:19
Okay, I've reproduced the issue with Single Date filters on dashboards using the sample dataset's Orders table. If you choose a date that should produce results for a card on the dashboard, it instead displays an error on screen, and the logs show the below error. I'm also seeing this error when using the "All Options" widget, but only when using the `On` operator (i.e. a specific single date).

These errors appear to be limited to dashboard filters only; query builder single date filters appear to work just fine. 

I was also able to reproduce this with a BigQuery question on a dashboard with the Single Date filter and the All Options filter widget when using the `On` operator. 

**For the others who have run into issues, are your issues with _all_ dashboard Time filters, or only the Single Date and `On` operator of the All Options filter widget?**

```
Dec 14 18:08:30 WARN metabase.query-processor :: Query failure: Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-null, :not-null, :time-interval, :segment
("clojure.core$ex_info.invokeStatic(core.clj:4739)"
"clojure.core$ex_info.invoke(core.clj:4739)"
"--> query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:285)"
"query_processor$assert_query_status_successful.invoke(query_processor.clj:277)"
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:323)"
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:316)"
"query_processor$fn__38063$process_query_and_save_execution_BANG___38068$fn__38069.invoke(query_processor.clj:354)"
"query_processor$fn__38063$process_query_and_save_execution_BANG___38068.invoke(query_processor.clj:340)"
"api.card$run_query_for_card.invokeStatic(card.clj:580)"
"api.card$run_query_for_card.doInvoke(card.clj:566)"
"api.card$fn__42772$fn__42775.invoke(card.clj:587)"
"api.card$fn__42772.invokeStatic(card.clj:586)"
"api.card$fn__42772.invoke(card.clj:582)"
"middleware$enforce_authentication$fn__55960.invoke(middleware.clj:113)"
"api.routes$fn__56106.invokeStatic(routes.clj:62)"
"api.routes$fn__56106.invoke(routes.clj:62)"
"routes$fn__56195$fn__56196.doInvoke(routes.clj:108)"
"routes$fn__56195.invokeStatic(routes.clj:103)"
"routes$fn__56195.invoke(routes.clj:103)"
"middleware$catch_api_exceptions$fn__56095.invoke(middleware.clj:436)"
"middleware$log_api_call$fn__56073$fn__56075.invoke(middleware.clj:364)"
"middleware$log_api_call$fn__56073.invoke(middleware.clj:363)"
"middleware$add_security_headers$fn__56015.invoke(middleware.clj:252)"
"core$wrap_streamed_json_response$fn__56896.invoke(core.clj:67)"
"middleware$bind_current_user$fn__55965.invoke(middleware.clj:137)"
"middleware$maybe_set_site_url$fn__56025.invoke(middleware.clj:290)"
"middleware$add_content_type$fn__56018.invoke(middleware.clj:262)")
```

**Comment by lukecarazzo** [comment] 2018-12-18 13:22
@mazameli 

I am having the issues on all date filters on my dashboards. Any type of date filter doesn't work and gives an error. I am having issues for single date, between dates month/year an so forth. if I roll back to 0.30.4 then all date filters on dashboards work just fine.

**Comment by bcbob** [comment] 2018-12-18 14:10
@mazameli
I've noticed the error only for single date filters (ON a specific date).
Clicking through to the underlying question works, and the correct results are displayed.
Using BETWEEN on a single date fixes the problem (but i have other native query cards on my dashboards that require single date input).

**Comment by mazameli** [comment] 2018-12-18 18:05
Okay, interesting. Both of you are querying against mysql if I'm not mistaken, but @lukecarazzo is running it on Windows Server. And to reiterate, all these problems appear to be specific to dashboard Date/time filters.

@camsaul Any ideas on this?

**Comment by bcbob** [comment] 2019-01-05 19:03
Yes, I'm querying mysql, and yes it's specific to DASHBOARD date/time filters. Clicking through from the dashboard to the underlying question builder question works fine - the dashboard parameter is passed to the question and it runs properly.
I just have a bunch of semi functional dashboards ... and am surprised more other users don't too?
I was assuming this was a very small bug somehow introduced into the 0.31.x update...

**Comment by jlisyc** [comment] 2019-01-15 16:59
Also bu in 0.31.2 https://github.com/metabase/metabase/issues/9267

**Comment by vincentsjtu** [comment] 2019-01-25 04:50
same problem. we i added single day filter to my dashboard, all related questions broke out with"There was a problem displaying this chart."

**Comment by bcbob** [comment] 2019-04-01 16:40
Have installed 0.32.1 and problem is still there.
Finally going to re-do all our dashboards.
Still very confused why this bug doesn't seem to affect anyone else and persists?
The way we use metabase it is absolutely fundamental!

**Comment by lukecarazzo** [comment] 2019-04-01 17:51
@bcbob

I am also waiting for a fix. I've got many questions and dashboards that are affected. I thought that they were on this issue but it seems that nothing has come from it.

**Comment by flamber** [comment] 2019-04-01 17:58
@salsakran I think you added the wrong milestone - it should be 0.33.0 or a new 0.32.2

**Comment by camsaul** [comment] 2019-04-02 21:55
Sameer this isn't a 0.32.x regression -- this was first an issue in 0.31.0. Not saying it shouldn't be fixed, but is there a specific reason you added it to 0.32.2?

**Comment by salsakran** [comment] 2019-04-02 22:01
@camsaul mainly because it is a super common use case that impacts a large fraction of our install base.

Date filters on dashboards are extremely common, and for them to be broken for GUI cards is a problem. If it's all GUI cards, I'd say this is a P0, if it's only a small subset it's P2.

**Comment by camsaul** [comment] 2019-04-02 22:09
Related (fixed in 0.32.0): #9127

**Closed** 2019-04-03 23:40 UTC
Labels: Bug, Dashboards, Parameters/Variables, Priority/P1

**Comment by bcbob** [comment] 2019-04-09 17:44
Thank you very much for resolving this issue 🌈🏆❤️✅0.32.3

**Comment by lukecarazzo** [comment] 2019-04-09 17:47
Oh Yay!!!!
