### ISSUE TITLE
Builder columns sorting in matrix view doesn't match SQL mode sorting

### ISSUE THREAD

**Issue by M4zD4i** [metabase/metabase#6235] opened 2017-10-23 11:24 UTC
- Your browser and the version: Safari 11.0 (12604.1.38.1.7)
- Your operating system: MacOS Sierra 10.12.6
- Your databases: Apache Impala
- Metabase version: fork from 0.26.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

Steps to reproduce:
1. Create a query in Builder using count(*) for results and grouping them by 2 parameters
2. Results are viewed as matrix and both dimensions are sorted ASC
3. Click "View as SQL" button
4. Sorting for dimensions in SQL query are different:
![question metabase 2017-10-23 14-16-37](https://user-images.githubusercontent.com/1096609/31886644-e4b9b51c-b7fd-11e7-984b-5306a15c0415.png)

**Comment by salsakran** [comment] 2017-12-04 21:55
We automatically pivot 2-d breakouts. We should probably maintain the order of these =)

**Comment by flamber** [comment] 2019-02-17 23:05
Hi @M4zD4i 
I cannot reproduce your issue on 0.31.2 - now both breakouts are `ASC` - not sure when this was fixed.
![image](https://user-images.githubusercontent.com/1447303/52920771-0af92100-32d6-11e9-9d78-2dd25483404e.png)

**Comment by flamber** [comment] 2020-03-02 19:44
Closing since I cannot reproduce on 0.34.3 and the pivot function has been updated since 0.26.1

**Closed by flamber** 2020-03-02 19:44 UTC
Labels: Priority:P2, Type:Bug, Type:UX, Visualization/Chart Settings
