### ISSUE TITLE
Column order resets when adding/removing columns in question settings

### ISSUE THREAD

**Issue by cwilby** [metabase/metabase#16565] opened 2021-06-13 18:50 UTC
**Describe the bug**
Column order is being reset after adding/removing columns in question settings.

**Logs**
No logs in JS console, no relevant logs on server, all `INFO sync.*` calls.

**To Reproduce**
Create a question, join at least one table, and create a query with a mix of columns from the root table and joined tables.  Then, add/delete any column.

**Expected behavior**
The joined table columns should remain at their configured indices.

**Actual behavior**
The joined table columns move to the end of the column set.

**Screenshots**

https://user-images.githubusercontent.com/13686317/121818706-a2b87100-cc3d-11eb-8c89-c271bcea1950.mp4

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "5.4.0-1048-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.7 (Debian 12.7-1.pgdg100+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-27",
      "tag": "v0.39.3",
      "branch": "release-x.39.x",
      "hash": "598a112"
    },
    "settings": {
      "report-timezone": "America/Los_Angeles"
    }
  }
}
```

**Severity**
Not business-ending, just kind of annoying when we're building reports.

**Comment by flamber** [comment] 2021-06-13 18:57
Duplicate of #13455

**Closed by flamber** 2021-06-13 18:57 UTC
Labels: .Needs Triage, Type:Bug
