### ISSUE TITLE
Cant change redshift's password in Metabase

### ISSUE THREAD

**Issue by mrdeds** [metabase/metabase#8374] opened 2018-08-21 21:03 UTC
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Browser and the version: Chrome Versión 68.0.3440.106 (Build oficial) (64 bits)
- Operating system: OS X 10.13.5
- Databases: Redshift
- Metabase version:  0.30.1
- Metabase hosting environment: 5 Kubernets pods with 2 GB CPUs and 2 GB memory each
- Metabase internal database: Postgres

- *Repeatable steps to reproduce the issue*
need to have a _Redshift_ database already configured
go to admin--->databases--->select redshift database--->try changing the password

**Comment by senior** [comment] 2018-08-21 22:45
I was able to change the password on Redshift database with 0.30.1. Do you get an error when you try to save the new password? It will refuse to save the password if it's not able to connect using the new credentials.

**Comment by mrdeds** [comment] 2018-08-21 22:49
i can't put passwords on a new connection. (I'm using v 0.30, that may dissapear in 0.30.1). Here's a screenshot:
<img width="1440" alt="captura de pantalla 2018-08-21 a la s 17 48 04" src="https://user-images.githubusercontent.com/9302082/44433120-959cd580-a56a-11e8-8f1b-464297ba9c45.png">

**Comment by jornh** [comment] 2018-08-22 04:15
@mrdeds are you seeing this with 0.30.0 or 0.30.1? 

This was reported in https://github.com/metabase/metabase/issues/8267 (and other places) so the error is present in 0.30.0. But the PR supposed to fix it in https://github.com/metabase/metabase/pull/8268 *is* part of 
https://github.com/metabase/metabase/commits/v0.30.1

**Comment by mrdeds** [comment] 2018-08-22 05:43
Correct, it seems to be the same issue as #8267

**Comment by jornh** [comment] 2018-08-22 14:01
Are you seeing this with version 0.30.1?

**Comment by mrdeds** [comment] 2018-08-22 14:13
No, I’m still in version 0.30

**Comment by senior** [comment] 2018-08-22 14:46
@mrdeds I'm going to go ahead and close this as a duplicate of https://github.com/metabase/metabase/issues/8267. It's been fixed and included in v0.30.1, so upgrading should fix the issue for you.

**Closed by senior** 2018-08-22 14:46 UTC
