### ISSUE TITLE
ERROR: table name "xxxx" specified more than once”

### ISSUE THREAD

**Issue by LukeAbell** [metabase/metabase#5841] opened 2017-08-30 02:44 UTC
I’m seeing this issue if I reference the same table using two foreign keys in a question:
Customer ID -> Users
Recipient ID -> Users

“ERROR: table name "lrt_user_meta_pivot_prepared__" specified more than once”

Created a new issue per @camsaul - Ref #5578

Metabase 0.25.2

**Comment by LukeAbell** [comment] 2017-10-06 16:22
@camsaul Any movement on this?

**Comment by camsaul** [comment] 2017-10-06 17:52
@LukeAbell not yet. Unfortunately we're a pretty small team so we can't fix every bug as fast as we'd like. But if you have an idea for a fix we'd love a PR

**Comment by LukeAbell** [comment] 2019-03-05 22:58
@camsaul @salsakran We are still running into this issue a bunch. It looks like the issue is that the foreign key join alias is based on the table name, and so when it's specified more than once, SQL throws an error. Any chance metabase could just prefix the alias name with the field name that's making the foreign key? That would make it unique and make the query work. We took the SQL generated from the error log and verified that things work if the aliases are prefixed.

If you point me in the right direction I may be able to fix and submit a pull request.

Thanks!!

**Comment by flamber** [comment] 2021-11-09 13:23
I cannot reproduce on 0.41.1, so closing.
If you're still experiencing this issue, then please provide "Diagnostic Info" from Admin > Troubleshooting, and more complete steps-to-reproduce and the failing query generated.

**Closed by flamber** 2021-11-09 13:23 UTC
Labels: Type:Bug, Priority:P2, Querying/MBQL
