### ISSUE TITLE
Metabase multi series charting frequently crashing browser when trying to display questions.

### ISSUE THREAD

**Issue by rodolphogarrido** [metabase/metabase#14576] opened 2021-01-28 23:51 UTC
**Describe the bug**
Metabase **multi series charting** frequently crashing browser when trying to display questions.

**To Reproduce**
1. Metabase must have several questions (we have ~5000)
2. Use the [multi-series-charting](https://www.metabase.com/docs/latest/users-guide/09-multi-series-charting.html) feature to combine two saved questions.
3. Metabase frequently gets stuck on the loading screen and eventually crashes the browser.

**Expected behavior**
Multi series charting question selection display showing without cashing the browser.

**Screenshots**
Before crashing the browser:
![Screenshot from 2021-01-28 19-49-35](https://user-images.githubusercontent.com/47122489/106212424-5e09cd00-61a9-11eb-97d8-4f3e2424c0e9.png)

Some time when it doesn't crash it takes a long time (4min) "freezed" and then show the available queries.

**Severity**
This is breaking several dashboards.

**Additional context**
Metabase database (PostgreSQL) is operating normally, the host machine has more than enough memory and cpu available (when this issue happens it doesn't even increase memory/cpu usage). This issue happens on firefox and chrome for every user.  Connection between Metabase and users is working fine.

The same doesn't happen when running a "test" Metabase with a few questions.

No error log is reported from Metabase.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "5.4.72-flatcar",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "presto",
      "postgres",
      "druid",
      "h2",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-12-03",
      "tag": "v0.37.3",
      "branch": "release-x.37.x",
      "hash": "2f1e783"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Comment by flamber** [comment] 2021-01-29 13:34
Duplicate of #13100

**Closed by flamber** 2021-01-29 13:34 UTC

**Comment by rodolphogarrido** [comment] 2021-01-29 13:35
Sorry I didn't saw that issue, my bad.
