### ISSUE TITLE
Add interactive control elements to charts and dashboard

### ISSUE THREAD

**Issue by x670** [metabase/metabase#10268] opened 2019-06-27 16:14 UTC
Sometimes there is need to update table data or act according to decision, made from analyzed data. 

# Example:
Question is `SELECT name, fruit, count FROM table;` 
In dashboard we can see this table

 | name | fruit | count|
 | --- | --- | --- |
 |Sara | apple | 7 |
|Johny | potato | 2 |
 |Alice | banana | 4 |

 On clicking `Johny` metabase shall query
```
UPDATE "table" 
SET fruit='apple', count={{count}} 
WHERE name={{name}}
```
or launch preconfigured in chart options application or script from shell
`~/metabase/activities/exchange_potatoes_for_apples.py --name {{name}} --fruit {{fruit}} --count {{count}}`
And after refreshing dashboard we'll get

 | name | fruit | count|
 | --- | --- | --- |
 |Sara | apple | 7 |
|Johny | apple | 2 |
 |Alice | banana | 4 |

# Another example:
Here we see whole dashboard where we can fire celebration with button
![image](https://user-images.githubusercontent.com/29977642/60282294-47392f80-990f-11e9-8301-4587e06c6fa1.png)

-----
Also it may be check boxes, toggles, sliders and etc. But at least running sql query or custom shell script with parameters from table or button with parameters from dashboard will be enough.

This feature will not replace specialized CRM's or administration tools, but may significantly increase convenience and simplicity of using BI in a daily workflow

As an alternative now we can generate link and use special server for doing actions, but it is not very convinient

**Comment by flamber** [comment] 2019-06-27 16:30
Hi @x670 
Sounds like a duplicate of Action Buttons #3737 (or #2882)
With the newly added PR #10211, then you could send an URL to a client-side application.

**Comment by x670** [comment] 2019-07-01 10:25
Hi
Idea of control elements is to run server-side code without creating additional public-available server apps.
You're right, it is pretty similar to #3737. But it seems, this idea goes against metabase dev-team vision

**Closed** 2019-07-01 10:29 UTC
Labels: New Feature
