### ISSUE TITLE
SQL snippets within models with database switching capability

### ISSUE THREAD

**Issue by vipera7** [metabase/metabase#35446] opened 2023-11-07 10:21 UTC
**Is your feature request related to a problem? Please describe.**
I have an application that operates in a primary environment, and I have set up two distinct Metabase installations, each connecting to the corresponding database of the application based on its environment. Despite sharing the same set of reports, these two Metabase instances are deployed in separate environments.

My goal is to synchronize the databases between `Metabase A` and `Metabase B`. This process involves the adjustment of database configurations for each report, as both instances already have the correct database connections established. Furthermore, I need to modify the schema for each report and model. For example, in the first database, there's a view named `view_789 `, while in the second, there's `view_456 `. I require the capability to easily modify and switch between these views across different environments.

The following schema might make it easier to understand:

<img width="481" alt="Capture2" src="https://github.com/metabase/metabase/assets/18635706/0782054d-0f65-4828-a5e6-1a749dd4d299">

So far, I've created a SQL snippets, storing `789 `for the first environment and changing it to `456 `for the second environment. However, I'm facing difficulties when trying to integrate these snippets into the Metabase model. To interface with the Metabase database, I've been utilizing the following SQL query:

```
UPDATE report_card SET dataset_query = JSON_SET(dataset_query, "$.database", 6) WHERE json_extract(dataset_query, '$.database') = 3;
UPDATE report_card SET database_id = 6 WHERE database_id = 3;

/*
Switch database caching
*/
UPDATE metabase_database SET options = '{"persist-models-enabled":true}' WHERE id = 6;
UPDATE metabase_database SET options = '{"persist-models-enabled":false}' WHERE id = 3;

/*
Update Current view ID snippet
*/
UPDATE native_query_snippet SET content = '456' WHERE id = 9;
```

**Describe the solution you'd like**
I wish to have the capability to seamlessly incorporate the SQL snippet into the model. This way, I can simply modify the view ID within the SQL snippet, eliminating the need to recreate each model individually and edit every report that relies on it. Additionally, I'd like the flexibility to change the database associated with the model.

**Describe alternatives you've considered**
An alternative approach would involve initiating an SQL request to update the reports, all the while ensuring the integrity of the Metabase database remains intact.

**How important is this feature to you?**
This holds significance for me as I require a backup of all my reports and the ability to link them with to the backup application.

**Comment by paoliniluis** [comment] 2024-05-28 00:26
this is a duplicate of https://github.com/metabase/metabase/issues/29781

**Closed by paoliniluis** 2024-05-28 00:26 UTC
Labels: Type:New Feature, Querying/Parameters & Variables, Querying/Native, Querying/, Querying/Models, Administration/Databases, Querying/Snippets
