### ISSUE TITLE
Synchronization breaks the configuration of fields to be used in joins.

### ISSUE THREAD

**Issue by apierard** [metabase/metabase#4737] opened 2017-04-10 07:43 UTC
In the definition of the data model, I specify the fields to be used to perform the join.

The problem is that with each automatic synchronization of Metabase with the database (MySQL in my case), this configuration is lost.

This synchronization breaks the dataviz and dashboard that use the fields on which I specified a join field to apply. I am therefore obliged to redo the configuration at each synchronization.

**Comment by camsaul** [comment] 2017-04-10 21:43
Duplicate of #3464

**Closed by camsaul** 2017-04-10 21:43 UTC
Labels: Bug, Duplicate, Metadata/Sync, Priority/P1

**Comment by salsakran** [comment] 2017-04-10 21:46
@apierard what kind of key are you specifying? Specifically, is it a compound key?

**Comment by apierard** [comment] 2017-04-11 06:05
Hello,

You will find in the attachment the screenshot of the configuration that I must reapply after every automatic synchronization of the database.

<img width="1356" alt="capture d ecran 2017-04-11 a 08 02 28" src="https://cloud.githubusercontent.com/assets/15813735/24894889/88d5a40e-1e8d-11e7-9bdc-dd90b27de860.png">
