### ISSUE TITLE
Cannot use Chinese in expressions

### ISSUE THREAD

**Issue by 8debug** [metabase/metabase#15314] opened 2021-03-24 01:54 UTC
Version: v0.38.2

step1:  create a "Simple question"
step2:  open "Filter" and input content in "Custom Expression"
step3:  try input chinese

Whether it is the Chinese input method that comes with Microsoft or a third-party Chinese input method

https://user-images.githubusercontent.com/3394927/112242163-44a36f80-8c86-11eb-9df4-f2a698c9a228.mp4

**Comment by flamber** [comment] 2021-03-24 12:52
I'm not able to reproduce this, since I don't know enough about how Chinese inputs are made - and don't have Windows.

It seems like the third-party input that you use in the second try actually inputs something - have you checked if it is just a display problem or if the inputs are actually blank?

**Comment by 8debug** [comment] 2021-03-25 00:28
> I'm not able to reproduce this, since I don't know enough about how Chinese inputs are made - and don't have Windows.
> 
> It seems like the third-party input that you use in the second try actually inputs something - have you checked if it is just a display problem or if the inputs are actually blank?

You can try other languages, such as Japanese or Korean

**Comment by ariya** [comment] 2022-04-20 06:47
This is fixed with the use of Ace as the basis for the custom expression editor (PR #19129).

**Closed by ariya** 2022-04-20 06:47 UTC
Labels: Type:Bug, Priority:P2, Customization/i18n, Querying/Notebook/Custom Expression
