### ISSUE TITLE
Database connection exceptions should be caught and translated to a human readable message

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6628] opened 2018-01-02 02:51 UTC
For commonly expected errors (like a file name not being found as in #6627), we shouldn't be leaking cryptic errors like `java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V` into user-land.

**Comment by camsaul** [comment] 2018-01-02 21:44
In general we already do translate common error messages; see https://github.com/metabase/metabase/blob/master/src/metabase/driver/postgres.clj#L162 for example. The problem here is `java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V` isn't supposed to be a commonly expected error.

**Comment by camsaul** [comment] 2018-01-02 23:38
Duplicate of #881

**Comment by camsaul** [comment] 2018-08-08 02:03
Duplicate of #881

**Closed by camsaul** 2018-08-08 02:03 UTC
Labels: Already Fixed, Database/SQLite, UX
