### ISSUE TITLE
Snowflake start of week is incorrect for date fields

### ISSUE THREAD

**Issue by soltanianalytics** [metabase/metabase#22773] opened 2022-05-17 14:03 UTC
**Describe the bug**
When aggregating over a table on the week of a date, the start of the week consistently deviates from the setting in Metabase's admin panel by one day (if the setting is Sunday, then the query's start of the week will be Monday etc.).

Example Admin: Set to Thursday
![image](https://user-images.githubusercontent.com/46958547/168828249-91dc808b-3af7-4354-bdf5-fbc9238f0aaa.png)

Example Question: Aggregating on the week of a date
![image](https://user-images.githubusercontent.com/46958547/168828367-90e24a0d-b152-4371-a22b-ed0440c89eca.png)

Example Result: `Mar 25, 2022` is a Friday
![image](https://user-images.githubusercontent.com/46958547/168828665-45fd584b-eb09-4816-ae56-215d8a0d7a91.png)

Example Question's Query:
```SQL
/* Comment by author
You'll see that the auto-generated query subtracts and re-adds 4 days. This seems to be how Metabase implements the start of week setting. This seems to assume a session setting for week_start, which is 1 in our case (week starts on Monday), but is assumed to be 0 or 7 (Sunday).
*/
SELECT dateadd(day, 4, CAST(date_trunc("week", CAST(dateadd(day, -4, CAST("DIM_DATES__via__DAY"."DATE" AS timestamp)) AS timestamp)) AS timestamp)) AS "DIM_DATES__via__DAY__DATE", sum("REPORTING"."REPORTING_DAILY_KPIS"."NET_SALES") AS "sum"
FROM "ANALYTICS"."REPORTING"."REPORTING_DAILY_KPIS"
LEFT JOIN "ANALYTICS"."STAR"."DIM_DATES" "DIM_DATES__via__DAY" ON "REPORTING"."REPORTING_DAILY_KPIS"."DAY" = "DIM_DATES__via__DAY"."DATE"
WHERE ("REPORTING"."REPORTING_DAILY_KPIS"."DAY" >= dateadd(day, 4, CAST(date_trunc("week", CAST(dateadd(day, -4, CAST(dateadd(week, -7, CAST(current_timestamp() AS timestamp)) AS timestamp)) AS timestamp)) AS timestamp))
   AND "REPORTING"."REPORTING_DAILY_KPIS"."DAY" < dateadd(day, 4, CAST(date_trunc("week", CAST(dateadd(day, -4, CAST(dateadd(week, 1, CAST(current_timestamp() AS timestamp)) AS timestamp)) AS timestamp)) AS timestamp)))
GROUP BY dateadd(day, 4, CAST(date_trunc("week", CAST(dateadd(day, -4, CAST("DIM_DATES__via__DAY"."DATE" AS timestamp)) AS timestamp)) AS timestamp))
ORDER BY dateadd(day, 4, CAST(date_trunc("week", CAST(dateadd(day, -4, CAST("DIM_DATES__via__DAY"."DATE" AS timestamp)) AS timestamp)) AS timestamp)) ASC
```

Example Session Parameter: You see it is set to 1 - it is always the same whatever the setting in the admin panel, despite the admin panel explicitly saying something different.
![image](https://user-images.githubusercontent.com/46958547/168829301-055f305d-c34c-49bc-80bc-a4e925296907.png)

**To Reproduce**
1. Connect a Snowflake instance with Monday as start of week
2. Have a table on date granularity
3. Summarize the table by week of that date

**Expected behavior**
Consistent start of week with the setting in the admin panel.

**Screenshots**
See above

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "4.14.275-207.503.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-03-23",
      "tag": "v0.42.3",
      "branch": "release-x.42.x",
      "hash": "33fb268"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

**Severity**
Very annoying. We're going to set the admin panel setting of week start of Sunday even though we want it to be Monday.

**Comment by flamber** [comment] 2022-05-17 14:05
Duplicate of #20999

**Closed by flamber** 2022-05-17 14:05 UTC
Labels: Type:Bug, .Needs Triage
