### ISSUE TITLE
Drilldown on multi series dashboard charts does not work, gives error

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#13109] opened 2020-08-13 04:15 UTC
**Describe the bug**
When there are multiple series on a dashboard chart (i.e. added using the "Add data" button) the drilldowns on the second series do not work as expected and produce an error.

The "View these XXX" drilldown shows the table used for the **first** table regardless of if they are the same. This probably points to the root of the remaining issues.

Clicking any of the drill down options ("Zoom in", "View these ...", "Caterory", "Location") on the second series produces an error. It appears to be trying to query the table of the first series.

Note that I got the same errors even when the series' were from the same base table.

**Logs**
Javascript console shows no relevant errors. The error presented in the browser is
```
Error: Table 4 is not present in the Query Processor Store.
```

Server logs
```
[62368698-4017-46ba-953c-9a31c973c932] 2020-08-13T15:59:15+12:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: null
{:database_id 1,
:started_at #t "2020-08-13T15:59:15.162720100+12:00[Pacific/Auckland]",
:json_query
{:type "query",
:query {:source-table 2, :filter ["and" ["=" ["datetime-field" ["field-id" 35] "month"] "2018-11-01T00:00:00+13:00"]]},
:database 1,
:parameters [],
:middleware {:add-default-userland-constraints? true}},
:native nil,
:status :failed,
:class java.lang.Exception,
:stacktrace
["--> query_processor.store$fn__38285$table__38290$fn__38291.invoke(store.clj:232)"
"query_processor.store$fn__38285$table__38290.invoke(store.clj:228)"
"driver.sql.query_processor$fn__64217.invokeStatic(query_processor.clj:243)"
"driver.sql.query_processor$fn__64217.invoke(query_processor.clj:238)"
"driver.sql.query_processor$fn__64222.invokeStatic(query_processor.clj:250)"
"driver.sql.query_processor$fn__64222.invoke(query_processor.clj:248)"
"driver.sql.query_processor$fn__64240.invokeStatic(query_processor.clj:279)"
"driver.sql.query_processor$fn__64240.invoke(query_processor.clj:277)"
"driver.sql.query_processor$fn__64725.invokeStatic(query_processor.clj:599)"
"driver.sql.query_processor$fn__64725.invoke(query_processor.clj:597)"
"driver.sql.query_processor$fn__64749.invokeStatic(query_processor.clj:615)"
"driver.sql.query_processor$fn__64749.invoke(query_processor.clj:613)"
"driver.sql.query_processor$fn__64767.invokeStatic(query_processor.clj:627)"
"driver.sql.query_processor$fn__64767.invoke(query_processor.clj:625)"
"driver.sql.query_processor$apply_top_level_clauses$fn__64873.invoke(query_processor.clj:788)"
"driver.sql.query_processor$apply_top_level_clauses.invokeStatic(query_processor.clj:786)"
"driver.sql.query_processor$apply_top_level_clauses.invoke(query_processor.clj:782)"
"driver.sql.query_processor$apply_clauses.invokeStatic(query_processor.clj:863)"
"driver.sql.query_processor$apply_clauses.invoke(query_processor.clj:848)"
"driver.sql.query_processor$fn__64950$build_honeysql_form__64955$fn__64959.invoke(query_processor.clj:868)"
"driver.sql.query_processor$fn__64950$build_honeysql_form__64955.invoke(query_processor.clj:865)"
"driver.sql.query_processor$mbql__GT_honeysql.invokeStatic(query_processor.clj:879)"
"driver.sql.query_processor$mbql__GT_honeysql.invoke(query_processor.clj:877)"
"driver.sql.query_processor$mbql__GT_native.invokeStatic(query_processor.clj:885)"
"driver.sql.query_processor$mbql__GT_native.invoke(query_processor.clj:881)"
"driver.sql$fn__73821.invokeStatic(sql.clj:40)"
"driver.sql$fn__73821.invoke(sql.clj:38)"
"query_processor.middleware.mbql_to_native$query__GT_native_form.invokeStatic(mbql_to_native.clj:15)"
"query_processor.middleware.mbql_to_native$query__GT_native_form.invoke(mbql_to_native.clj:10)"
"query_processor.middleware.mbql_to_native$mbql__GT_native$fn__45532.invoke(mbql_to_native.clj:23)"
"query_processor.middleware.check_features$check_features$fn__44834.invoke(check_features.clj:42)"
"query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__45697.invoke(optimize_datetime_filters.clj:133)"
"query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47225.invoke(wrap_value_literals.clj:137)"
"query_processor.middleware.annotate$add_column_info$fn__43455.invoke(annotate.clj:574)"
"query_processor.middleware.permissions$check_query_permissions$fn__44709.invoke(permissions.clj:64)"
"query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__46215.invoke(pre_alias_aggregations.clj:40)"
"query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__44907.invoke(cumulative_aggregations.clj:61)"
"query_processor.middleware.resolve_joins$resolve_joins$fn__46747.invoke(resolve_joins.clj:183)"
"query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39185.invoke(add_implicit_joins.clj:245)"
"query_processor.middleware.limit$limit$fn__45518.invoke(limit.clj:38)"
"query_processor.middleware.format_rows$format_rows$fn__45499.invoke(format_rows.clj:81)"
"query_processor.middleware.desugar$desugar$fn__44973.invoke(desugar.clj:22)"
"query_processor.middleware.binning$update_binning_strategy$fn__43999.invoke(binning.clj:229)"
"query_processor.middleware.resolve_fields$resolve_fields$fn__44515.invoke(resolve_fields.clj:24)"
"query_processor.middleware.add_dimension_projections$add_remapping$fn__38734.invoke(add_dimension_projections.clj:272)"
"query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__38941.invoke(add_implicit_clauses.clj:141)"
"query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39334.invoke(add_source_metadata.clj:105)"
"query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__46412.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
"query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__43640.invoke(auto_bucket_datetimes.clj:125)"
"query_processor.middleware.resolve_source_table$resolve_source_tables$fn__44562.invoke(resolve_source_table.clj:46)"
"query_processor.middleware.parameters$substitute_parameters$fn__46197.invoke(parameters.clj:114)"
"query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__44614.invoke(resolve_referenced.clj:80)"
"query_processor.middleware.expand_macros$expand_macros$fn__45229.invoke(expand_macros.clj:158)"
"query_processor.middleware.add_timezone_info$add_timezone_info$fn__39365.invoke(add_timezone_info.clj:15)"
"query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47109.invoke(splice_params_in_response.clj:32)"
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46423$fn__46427.invoke(resolve_database_and_driver.clj:33)"
"driver$do_with_driver.invokeStatic(driver.clj:61)"
"driver$do_with_driver.invoke(driver.clj:57)"
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46423.invoke(resolve_database_and_driver.clj:27)"
"query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45447.invoke(fetch_source_query.clj:267)"
"query_processor.middleware.store$initialize_store$fn__47118$fn__47119.invoke(store.clj:11)"
"query_processor.store$do_with_store.invokeStatic(store.clj:46)"
"query_processor.store$do_with_store.invoke(store.clj:40)"
"query_processor.middleware.store$initialize_store$fn__47118.invoke(store.clj:10)"
"query_processor.middleware.cache$maybe_return_cached_results$fn__44491.invoke(cache.clj:209)"
"query_processor.middleware.validate$validate_query$fn__47127.invoke(validate.clj:10)"
"query_processor.middleware.normalize_query$normalize$fn__45545.invoke(normalize_query.clj:22)"
"query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39203.invoke(add_rows_truncated.clj:36)"
"query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47094.invoke(results_metadata.clj:147)"
"query_processor.middleware.constraints$add_default_userland_constraints$fn__44850.invoke(constraints.clj:42)"
"query_processor.middleware.process_userland_query$process_userland_query$fn__46286.invoke(process_userland_query.clj:136)"
"query_processor.middleware.catch_exceptions$catch_exceptions$fn__44793.invoke(catch_exceptions.clj:174)"
"query_processor.reducible$async_qp$qp_STAR___38013$thunk__38014.invoke(reducible.clj:101)"
"query_processor.reducible$async_qp$qp_STAR___38013.invoke(reducible.clj:107)"
"query_processor.reducible$sync_qp$qp_STAR___38022$fn__38025.invoke(reducible.clj:133)"
"query_processor.reducible$sync_qp$qp_STAR___38022.invoke(reducible.clj:132)"
"query_processor$process_userland_query.invokeStatic(query_processor.clj:213)"
"query_processor$process_userland_query.doInvoke(query_processor.clj:209)"
"query_processor$fn__47269$process_query_and_save_execution_BANG___47278$fn__47281.invoke(query_processor.clj:225)"
"query_processor$fn__47269$process_query_and_save_execution_BANG___47278.invoke(query_processor.clj:217)"
"query_processor$fn__47313$process_query_and_save_with_max_results_constraints_BANG___47322$fn__47325.invoke(query_processor.clj:237)"
"query_processor$fn__47313$process_query_and_save_with_max_results_constraints_BANG___47322.invoke(query_processor.clj:230)"
"api.dataset$fn__50604$fn__50607.invoke(dataset.clj:54)"
"query_processor.streaming$streaming_response_STAR_$fn__35435$fn__35436.invoke(streaming.clj:73)"
"query_processor.streaming$streaming_response_STAR_$fn__35435.invoke(streaming.clj:72)"
"async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
"async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
"async.streaming_response$do_f_async$fn__23249.invoke(streaming_response.clj:85)"],
:context :ad-hoc,
:error "Error: Table 4 is not present in the Query Processor Store.",
:row_count 0,
:running_time 0,
:preprocessed
{:type :query,
:query
{:source-table 2,
:filter
[:and
[:>= [:datetime-field [:field-id 35] :default] [:absolute-datetime #t "2018-11-01T00:00+13:00" :default]]
[:< [:datetime-field [:field-id 35] :default] [:absolute-datetime #t "2018-12-01T00:00+13:00" :default]]],
:fields [[:datetime-field [:field-id 15] :default] [:field-id 10] [:field-id 12] [:field-id 11] [:field-id 14] [:field-id 13] [:field-id 16] [:field-id 17] [:field-id 9]],
:limit 2000},
:database 1,
:middleware {:add-default-userland-constraints? true},
:info
{:executed-by 1,
:context :ad-hoc,
:nested? false,
:query-hash [123, -90, -103, 108, 122, -91, -92, -55, 61, 83, -12, -11, -120, -88, 59, -107, -118, 105, 60, 98, 117, 43, -30, 117, 22, -78, -98, 117, 69, -32, 4, 123]},
:constraints {:max-results 10000, :max-results-bare-rows 2000}},
:data {:rows [], :cols []}}
```

**To Reproduce**
1. Sample dataset, question count orders by month, save
2. Sample dataset, question count reviews by month, save
3. New dashboard, add first question (Orders)
4. "Add data" button on chart widget, add second question (Reviews)
5. Save the dashboard
6. Click a point on the second series (Reviews), note that the "View these Orders" which is incorrect
7. Click the "View these Orders", Error is displayed. Note that the table seems to be looking Orders not Reviews where we started from.
8. Same error with the other drill down options.

**Expected behavior**
Drill throughs should work when there are multiple series on a dashboard chart.

**Screenshots**
![image](https://user-images.githubusercontent.com/4504437/90093293-5ed7af80-dd7f-11ea-99f5-80768361a88c.png)
![image](https://user-images.githubusercontent.com/4504437/90093387-92b2d500-dd7f-11ea-8e08-fa1593ab0d5e.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "13.0.2+8",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-07-31",
      "tag": "v0.36.2",
      "branch": "release-0.36.x",
      "hash": "13f0225"
    },
    "settings": {
      "report-timezone": "Pacific/Auckland"
    }
  }
}
```

**Severity**
Frustration, found a few little quirks with the multiple series charts on dashboards. They are really really useful, but I'm not having a great time with them.

**Comment by flamber** [comment] 2020-08-13 08:58
Hi @notrom 
Sounds like a duplicate of #11442 ?

**Comment by notrom** [comment] 2020-08-13 23:37
@flamber I'd say very highly related, could well be the same root cause. I'm getting an error out of the UI rather than getting the wrong filters applied which to be honest I prefer. My issue is more like what you're seeing in your comment to that ticket than the OPs description.

**Closed** 2021-06-16 16:57 UTC
Labels: Priority:P2, Querying/, Querying/Parameters & Variables, Reporting/Dashboards, Type:Bug
