### ISSUE TITLE
Elastic Beanstalk upgrade documentation link broken

### ISSUE THREAD

**Issue by sherbondy** [metabase/metabase#4182] opened 2017-01-17 21:30 UTC
Hey there,

Trying to update an Elastic Beanstalk deployed Metabase instance to the latest and greatest (v0.22). Noticed that [the link from the Operations Guide](http://www.metabase.com/docs/latest/operations-guide/start.html#upgrading-metabase) is currently busted on the website:

[Upgrading AWS Elastic Beanstalk deployments](http://www.metabase.com/docs/master/operations-guide/running-metabase-on-elastic-beanstalk#deploying-new-versions-of-metabase)

Note that it points to `master` instead of `latest`.

When I manually change the URL to `latest`, the corresponding documentation page appears:
[Deploying New Versions of Metabase](http://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk#deploying-new-versions-of-metabase), but it seems to be out of date?

It contains the download link for v0.20:
`http://downloads.metabase.com/v0.20.0/metabase-aws-eb.zip`

I tried manually modifying the download link to `v0.22`, I'm just a little worried that the zip file I'm getting may not be ready/tested for deployment?

Let me know. Happy to have a go at updating the relevant documentation in the repo if it is within scope for outside/rando contributors.

**Comment by camsaul** [comment] 2017-01-17 22:55
It looks like that link should be http://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk#deploying-new-versions-of-metabase

(`latest` instead of `master`)

**Comment by camsaul** [comment] 2017-01-17 22:58
Looks like the same thing is happening on the link below as well:

[Upgrading Heroku deployments](http://www.metabase.com/docs/master/operations-guide/running-metabase-on-heroku#deploying-new-versions-of-metabase)

**Comment by camsaul** [comment] 2017-01-17 23:03
So in the source Markdown file links like

```markdown
[Running on Heroku](running-metabase-on-heroku.md)
```

work in the documentation:

```html
<a href="running-metabase-on-heroku.html">Running on Heroku</a>
```

But ones containing bookmarks *do not*:

```markdown
[Upgrading Heroku deployments](running-metabase-on-heroku.md#deploying-new-versions-of-metabase)
```

```html
<a href="http://www.metabase.com/docs/master/operations-guide/running-metabase-on-heroku#deploying-new-versions-of-metabase">
  Upgrading Heroku deployments
</a>
```

@salsakran, it sounds to me like this might be a bug in our documentation generation script.

**Comment by salsakran** [comment] 2017-01-18 00:25
@camsaul yeah, that's the root cause. Long story short, I entered the wrong label for our "version", and `master` crept in instead of `latest`. I did a search+replace but seem to have missed a few spots.

@sherbondy thanks for the heads up. It should be fixed now.

**Closed by salsakran** 2017-01-18 00:25 UTC
Labels: Bug, Documentation
