### ISSUE TITLE
Cannot fix the order of parameters

### ISSUE THREAD

**Issue by xqwbx163** [metabase/metabase#9607] opened 2019-03-22 12:59 UTC
metabase version：0.31
database : mysql 5.7
OS:centos 7.2

 i writing a question by  Sql, set 5 parameter  variables such as  aa, bb, cc, dd, ee.  they will be arranged in order. 
so i save this question,, the order of the parameters is changed. the order change to 
ee aa dd bb cc, 
it looks very unattractive, 
however  I tried to modify many times , can't adjust the order, what should I do?

![image](https://user-images.githubusercontent.com/20455410/54824084-d3bacd00-4ce4-11e9-9ad6-34190e7ab108.png)

![image](https://user-images.githubusercontent.com/20455410/54823871-23e55f80-4ce4-11e9-8d8c-6de83903d94a.png)

**Comment by flamber** [comment] 2019-03-22 14:25
Hi @xqwbx163 
I cannot reproduce your issue on 0.31.2 - when I create this query and set Variable Type, then the parameters gets created in the same order. And it's still in order after I save and browser refresh.
```SQL
SELECT * FROM ORDERS WHERE 1=1
AND {{aa}} AND {{bb}} AND {{cc}} AND {{dd}} AND {{ee}}
```
There's a bug about reordering - #9357
And there's a bug, where order gets mixed if there's more than 8 parameters - #5136

**Comment by xqwbx163** [comment] 2019-03-23 01:45
@flamber 
That's right, I tried it again. If the parameters are less than 8, the parameters can be sorted in order, but more than 8 will change. Is there any good solution for the order of 10 or more parameters?
My case, there are many parameters exceed 8 or even 15, 
![image](https://user-images.githubusercontent.com/20455410/54860104-2aa9bc00-4d50-11e9-948b-e43d1d87727e.png)
![image](https://user-images.githubusercontent.com/20455410/54860106-2f6e7000-4d50-11e9-9b7b-961428784375.png)

**Comment by flamber** [comment] 2019-03-23 01:51
@xqwbx163 Okay, then you can close this issue and upvote the two issues by clicking the :+1:

**Closed** 2019-03-23 05:41 UTC
