### ISSUE TITLE
Feature requests and proposals

### ISSUE THREAD

**Issue by kilonzi** [metabase/metabase#7182] opened 2018-03-22 15:54 UTC
Ability to join 2 tables in some field. Similar to Inner, Left, Right,Outer Join in MySQL

**Comment by jornh** [comment] 2018-03-22 19:12
It’s already possible - with two different options:
* either through some admin config 
* or the more flexible/geeky native SQL
for the basics see this discourse thread about [Data Modelling](http://discourse.metabase.com/t/data-modeling/3162)

**Comment by salsakran** [comment] 2018-03-31 00:59
dupe of #1173 which we've decided is best handled via nested queries https://www.metabase.com/blog/Nested-Queries/index.html

**Closed by salsakran** 2018-03-31 00:59 UTC
