### ISSUE TITLE
Transparent background only on static embed

### ISSUE THREAD

**Issue by Wattos** [metabase/metabase#35008] opened 2023-10-24 12:18 UTC
**Is your feature request related to a problem? Please describe.**
Enable transparent embed. Currently none of the theme options allow for the embed to have a transparent background. The transparent theme is not usable, as it also makes the cards transparent.

**Describe the solution you'd like**
An ability for the static embed to come with a transparent window, but keep the cards / widgets with a background color. 

**Describe alternatives you've considered**
I tried to the transparent version, but it does meet my needs. I am also unable to inject a custom css to resolve the issue.

**How important is this feature to you?**
It is important enough for me to create a PR. See PR https://github.com/metabase/metabase/pull/34938

**Comment by Wattos** [comment] 2023-11-10 13:01
@albertoperdomo currently this is implemented as a new theme, but maybe this should just be a checkbox, similar to the frame option and otherwise?

**Comment by dahyeik** [comment] 2023-12-12 23:30
Duplicate of https://github.com/metabase/metabase/issues/9856

**Closed** 2023-12-12 23:30 UTC
Labels: Type:New Feature, Embedding/Signed, .Product Input Needed, .Team/Embedding

**Comment by albertoperdomo** [comment] 2024-05-29 09:20
@Wattos We are working on redesigning this. There will be a light and dark theme, with the ability to make the iframe background transparent as an option. The background of cards will be solid, depending on the theme used (light or dark). Does this address your needs?

**Comment by Wattos** [comment] 2024-05-29 10:04
@albertoperdomo yes, that works. The current theme works for me, but its just the background that needs to be removed.

In the long term, I would really love to customize the widget look (e.g. change box shape, corners, radius, margins between widgets) to make it look more "native" to our own UI, but having the transparent background is already a big win!

**Comment by albertoperdomo** [comment] 2024-10-09 18:51
Hey @Wattos and others!

In upcoming version 51, we deprecate the transparent theme. Instead we introduce the option to choose between the light and dark themes and optionally toggle background transparency.

If you want to have a sneak peek, here's the download link for 51 Beta: https://downloads.metabase.com/enterprise/beta/metabase.jar
I hope this addresses everyone's issues. If not, please let us know!
