### ISSUE TITLE
Support multilingual Data in Meta base ?

### ISSUE THREAD

**Issue by hireninnodel** [metabase/metabase#14461] opened 2021-01-20 05:58 UTC
Dear Team,

We have multilingual data in our database (MongoDB OR CSV).

Data Store in different language's English,Hindi,Gujarati etc.

is the support  multilingual data in meta base for display in charts ?

we have facing some issue in display multilingual data in metabase. so kindly guide as.

Thanks & Regards
Hiren

**Comment by flamber** [comment] 2021-01-20 09:14
Hi @hireninnodel 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Possibly a duplicate of #9508

**Closed by flamber** 2021-01-20 09:14 UTC
Labels: .Needs Triage, Type:Question
