### ISSUE TITLE
Roles and Permissions

### ISSUE THREAD

**Issue by federicokeen** [metabase/metabase#3200] opened 2016-08-15 23:24 UTC
Ability to create Roles and Permissions. Allow the creation of roles and allow to assign permissions to them. Then associate those roles to users.
The admin role is good, the user role also is good, but you might want to grant access to some users that can only look at some specific dashboards or questions but prevent them from creating dashboards or questions or looking at dashboards and questions they have not been granted access.

**Comment by mazameli** [comment] 2016-08-15 23:30
This is a duplicate of #2682, and related to #3087 and #1175.

Hopefully you'll be glad to know that we're actively working on implementing basic, customizable user groups with data-level permissions (i.e. on the database/schema/table level). In the future, we'll be looking at dashboard/question/pulse-level permissions and possibly column/row-level permissions.

**Comment by camsaul** [comment] 2016-08-15 23:31
Hi @federicokeen, we're currently working on implementing roles. It will ship as part of our next release.

Duplicate of #3087

**Closed by mazameli** 2016-08-15 23:30 UTC

**Comment by federicokeen** [comment] 2016-08-15 23:32
Wow guys, this is amazing! Thanks so much! I actually checked the other "features" I was looking into opening tickets and couldn't find this one. Sorry for opening a duplicate and amazing response time!

**Comment by mazameli** [comment] 2016-08-15 23:34
No worries! We know people are really eager for this set of features. 👍

**Comment by davejlsherwood** [comment] 2016-08-29 15:35
@camsaul @mazameli when is the net release due roughly? Really looking forward to this!!

**Comment by camsaul** [comment] 2016-08-29 18:14
@davejlsherwood probably in the next few weeks 📆

**Comment by cagiraudo** [comment] 2016-08-31 20:39
Nice guys!! i am looking foward for this!!!

**Comment by neeagl** [comment] 2016-09-09 13:06
we are waiting for this too..

**Comment by cepix** [comment] 2017-10-25 13:01
Hi , any news about roles feature?

**Comment by camsaul** [comment] 2017-10-25 18:58
Hi @cepix, good news! We shipped this feature as part of our 0.20.0 release, so it's been available for a year or so. See PR #3087
