### ISSUE TITLE
Attempting to Select "Custom Expression" After using a  Linked Table view Locks-up Webpage

### ISSUE THREAD

**Issue by Go2ClassPoorYorick** [metabase/metabase#9356] opened 2019-01-31 16:15 UTC
Your browser and the version: Chromium Version 71.0.3578.98 (Official Build) snap (64-bit)
Your operating system: Ubuntu 18.04
Your databases: Sql Server
Metabase version: v0.31.2
Metabase hosting environment: Docker
Metabase internal database: H2 (default)

-To reproduce, attempt to use query builder to select the number of distinct values of a Linked table.
-The query will work, but if you attempt to view the "Custom Expression" option the page will lock up.
-Console should log "Uncaught Error: Unknown Expression"
-Attempting to click off the page will log "Cannot read property 'valueTracker' of null"
-Attempting to click the view box will log "Cannot read property 'firstChild' of null"
-Selecting other boxes will allow input, but the view dropdown will stay locked and console will start logging many errors.
![screenshot from 2019-01-31 11-03-27](https://user-images.githubusercontent.com/33301123/52067337-64c4c180-2548-11e9-9d89-2ff4597924f2.png)

-------

**Comment by Go2ClassPoorYorick** [comment] 2019-01-31 16:16
Not browser specific, same issue occurs in firefox

**Comment by flamber** [comment] 2019-01-31 17:06
Seeing the same thing, but it doesn't matter if you use Distinct, as long as you selected a linked table.
```
Error: Unknown expression ["avg",["fk->",["field-id",6342],["field-id",6334]]]
```

**Comment by Go2ClassPoorYorick** [comment] 2019-01-31 17:21
> Seeing the same thing, but it doesn't matter if you use Distinct, as long as you selected a linked table.
> 
> ```
> Error: Unknown expression ["avg",["fk->",["field-id",6342],["field-id",6334]]]
> ```

Updated title to reflect. Maybe this'll be my first bug report that wasn't from my own misuse.

**Comment by rylonian** [comment] 2019-02-22 20:19
This is confirmed for me as well.

**Comment by flamber** [comment] 2019-02-22 20:38
Another way to break it, is by going into a sub of View, return and then try to enter "Custom Expression".
It will throw this error `Error: Unknown expression ["sum",null]` (where `sum` depends on the option)
![screencast](https://user-images.githubusercontent.com/1447303/53269764-5bde9000-36af-11e9-916f-25c638cf40a7.gif)

**Comment by mazameli** [comment] 2019-10-09 23:33
I'm not able to reproduce this in the the Custom query builder, so I'm going to close this, but please let me know if you're experiencing it in version 0.33.

**Closed by mazameli** 2019-10-09 23:33 UTC
Labels: Priority:P2, Query Builder, Type:Bug
