### ISSUE TITLE
BigQuery authentication error for federated tables (Google Sheets)

### ISSUE THREAD

**Issue by remydavid** [metabase/metabase#4179] opened 2017-01-17 11:47 UTC
- Your browser and the version: Chrome 55
- Your operating system: Windows 7
- Your databases: Big Query
- Metabase version: 21.1
- Metabase hosting environment: App Engine
- Metabase internal database: Google SQL

Metabase cannot request federated tables in BigQuery.

To reproduce : 
- create a Google Sheet document in Google Drive
- add it as a table in Big Query
- create a request on this table 
Error :
`Access Denied: BigQuery BigQuery: Permission denied while globbing file pattern.`

Other (non federated) tables from the same project / dataset work fine.

I think the scope for Google Drive needs to be added to Big Query API requests issued by Metabase.
For more, see 
http://stackoverflow.com/questions/40731823/encountered-an-error-while-globbing-file-pattern-error-when-using-bigquery-api

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by tlrobinson** [comment] 2017-01-17 16:29
Confirmed adding `https://www.googleapis.com/auth/drive` to the scopes works. I'm not sure we want to include it by default though. Maybe a toggle for "Include Google Drive permissions".

In the meantime you can just manually add `%20https://www.googleapis.com/auth/drive` after `scope=https://www.googleapis.com/auth/bigquery` in the `Click here to get an auth code` URL.

**Comment by remydavid** [comment] 2017-01-17 16:57
I thought the scope was send per request, if we can add it to the auth code, that's perfect.
A toggle would be nice.

**Comment by bhanna** [comment] 2017-02-21 22:40
This also solved my permissions problem. Seems to be a needed toggle.

**Comment by VikramTiwari** [comment] 2017-06-22 19:21
I am getting read timeouts on this. Is there something I might be missing?

**Comment by mito** [comment] 2017-07-08 18:48
Same here, getting read timeouts when trying to make new question

**Comment by mito** [comment] 2017-07-10 16:07
you have to enable Google Drive API in project (5 days trying :(

**Comment by damon09273** [comment] 2017-07-11 02:44
i get timeouts too.

**Comment by VikramTiwari** [comment] 2017-07-14 21:42
@mito Did it solve for you after enabling Google Drives API. I did so and generated a new auth token yet the same result.

**Comment by mazameli** [comment] 2018-10-22 17:11
Got a report from a user that querying Google Drive federated tables _was_ working for them in version 0.30.3, but as of upgrading to 0.30.4 it has stopped working.

**Comment by ernoaapa** [comment] 2019-07-30 12:02
Any updates on this?

**Comment by hassan-koho** [comment] 2021-05-10 14:59
Any plans to fix this?

**Comment by paoliniluis** [comment] 2021-11-23 22:46
The error now is "Permission denied while getting Drive credentials". No matter if you grant the service account an owner role, it will fail

**Comment by ekaram** [comment] 2022-01-14 19:21
i get the same error.  

i am using oauth and have included drive scope.  
i have granted my service account edit permission on the google sheet.   

"Access Denied: BigQuery BigQuery: Permission denied while getting Drive credentials."

**Comment by camsaul** [comment] 2022-01-25 02:22
Fixed by #19629

**Closed by camsaul** 2022-01-25 02:22 UTC
Labels: Type:Bug, .Limitation, Database/BigQuery
