### ISSUE TITLE
v039.1 is not displaying number of records correctly in pt-BR

### ISSUE THREAD

**Issue by tatusis** [metabase/metabase#16061] opened 2021-05-14 14:13 UTC
**Describe the bug**

v039.1 is not displaying number of records correctly

The translation for Showing 10 rows is incorrect: Mostrando {0} linhas

The marker {0} is not being replaced by the number of rows

**To Reproduce**

1. Go to any question on a server configured as pt-BR
2. See the footer text that displays the number of lines
4. Translation is incorrect

**Expected behavior**

The translation for Showing 10 rows should be Mostrando 10 linhas instead of Mostrando {0} linhas

**Screenshots**

![image](https://user-images.githubusercontent.com/55719904/118283000-411daf00-b4a5-11eb-8bb6-020ec75dc657.png)

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "America/Sao_Paulo"
  },
  "metabase-info": {
    "databases": [
      "oracle",
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.14"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-27",
      "tag": "v0.39.1",
      "branch": "release-x.39.x",
      "hash": "6beba48"
    },
    "settings": {
      "report-timezone": "Etc/GMT-3"
    }
  }
}

**Severity**

Users are unable to know how many rows were returned

**Comment by flamber** [comment] 2021-05-14 14:18
Duplicate of #15694

**Closed by flamber** 2021-05-14 14:18 UTC
Labels: .Needs Triage, Type:Bug
