### ISSUE TITLE
Different chart rendered in pulse from question

### ISSUE THREAD

**Issue by weenpeace** [metabase/metabase#5493] opened 2017-07-17 21:29 UTC
when adding this question (http://mb.spot.com/public/question/c7b0affd-e236-4c37-b7be-90a5b76b3f98) to an email pulse, the rendered card is a table despite the question being saved as a chart. 

documentation does not contain guidance on how to change to one of the approved data visualizations for an email pulse, but only contains the current options/limitations for data visualization.  

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment] 2017-07-26 20:50
Hmm, I'm not sure why this particular chart is being displayed as a table. Single metric time series should be displayed as line charts. Besides that issue, you've hit on a few things:

1. The documentation around what happens to each chart type when added to a Pulse is not exhaustive
2. Multi-metric time series charts are getting converted to tables. I can't honestly recall if this was ever intentional, but it's pretty goofy. This is exacerbated by #1 above.
3. At a higher level, I think we need to revisit our overall philosophy around chart transformation in Pulses. Aspects of our current philosophy are confusing/frustrating lots of users.

**Comment by mazameli** [comment] 2017-07-26 22:15
I did a quick inventory of each of our chart types and how they get transformed when added to a Pulse.

The simple summary is that all charts that we allow get mapped to one of the following:
- single line time series
- row chart (metric broken out by a dimension other than time)
- 3 column, 10 row basic table (i.e., up to 2 dimensions, one metric)

**Raw data, pin map, scatter plot**
Can't be shown

**Aggregated tables**
![aggregated table](https://user-images.githubusercontent.com/2223916/28645659-45dfc722-7213-11e7-8f87-07a3546a2576.png)

**Pivot table**
![pivot table](https://user-images.githubusercontent.com/2223916/28645993-55404d08-7214-11e7-99ae-852677412ef5.png)

**Single line chart**
![line - one metric](https://user-images.githubusercontent.com/2223916/28645765-a44abb28-7213-11e7-9f1e-89746890ae27.png)

**Basic bar chart**
![bar chart](https://user-images.githubusercontent.com/2223916/28645851-d8b36c7a-7213-11e7-82c6-c7860d8ddb26.png)

**Horizontal bar**
![screen shot 2017-07-26 at 2 50 48 pm](https://user-images.githubusercontent.com/2223916/28645781-b1b3522a-7213-11e7-8117-81521eae91e5.png)

**Time series, broken out by category**
![screen shot 2017-07-26 at 2 51 12 pm](https://user-images.githubusercontent.com/2223916/28645902-fe8e361e-7213-11e7-8aa8-5c065abbe4a2.png)

**Bar chart over time broken out by category**
![multi-bar](https://user-images.githubusercontent.com/2223916/28646083-ba354150-7214-11e7-9b44-7239ec21d685.png)

**Stacked bar (same thing as above basically)**
![stacked bar](https://user-images.githubusercontent.com/2223916/28646100-cfbc4906-7214-11e7-8533-96f7dcf7c473.png)

**Region map**
![region map](https://user-images.githubusercontent.com/2223916/28645946-207203a0-7214-11e7-9595-c2ce59b0ea1b.png)

**Pie chart**
![screen shot 2017-07-26 at 2 51 44 pm](https://user-images.githubusercontent.com/2223916/28646030-80b751e8-7214-11e7-9965-e2a3c4027fbe.png)

**Funnel**
![screen shot 2017-07-26 at 2 50 57 pm](https://user-images.githubusercontent.com/2223916/28645799-c1653940-7213-11e7-89db-f88acee1e141.png)

**Comment by josiaranda** [comment] 2018-02-02 11:21
I think it would better if questions are sent just as it intended to be shown. So the pulse receiver don't need to open link to see the visualization.

**Comment by irinawetransfer** [comment] 2018-10-15 11:31
is there any progress on this? I have the opposite issue, I'd love to see a table and my questions is saved as a table, but when added to a pulse it is visualized as a line plot...

**Comment by nick-giudici** [comment] 2019-08-09 17:59
I would love to have the option to send the chart as an image. This could work by rendering the chart using a headless browser, taking a screen cap, then embedding that into the email.

Frequently, my clients want to read these reports when they are not in the office and can't access the metabase front end.

**Comment by shanealynn** [comment] 2019-10-21 17:10
This feature is a brilliant part of Metabase - the ability to send pulses and visualisations. Having the visualisations render as intended would improve this massively - at the moment the emails are unpredictable, and any sort of complex diagram is lost.

**Comment by ricardoekm** [comment] 2020-02-28 19:45
It would be great to have the option to send pulses as images.

**Comment by ricardoekm** [comment] 2020-03-12 14:47
While this issue is not implemented I've open-sourced the project we're using here to send pulses. It uses puppeteer and nodemailer: [metabase-pulses](https://github.com/Calindra/metabase-pulses)

**Comment by idkw** [comment] 2020-08-26 21:06
I tried the pulse feature but almost all my beautiful questions charts get transformed to an ungly table.
Nobody wants to read a complicated table in an email or slack, so for me the feature is currently broken.
Couldn't this be implemented with chrome-headless to just make a screenshot of the chart ?

**Comment by sudipbhandari126** [comment] 2021-03-25 06:42
> is there any progress on this? I have the opposite issue, I'd love to see a table and my questions is saved as a table, but when added to a pulse it is visualized as a line plot...

This often happens when you have 2 columns (which pulse email visualizes as line plot).. one workaround that has worked for me is by adding a literal in select statement just to avoid line plot

eg:

select day, amount from ..... -> visualizes as line plot
select day, amount, 'something' as somecolumn from .... -> doesn't visualize

**Comment by saisundarr** [comment] 2021-11-23 06:20
Is there any update on this? The bar graph visualisation is getting sent as a table for me too via dashboard subscriptions.

**Comment by Deepanshu418** [comment] 2022-06-29 11:57
Any Update on this ?

**Comment by mblasius-notarize** [comment] 2022-10-26 18:23
I'm having this issue as well. Many of my charts look great in the Metabase UI but are rendering as tables when sent via Dashboard Subscriptions.

**Comment by resilience** [comment] 2023-01-23 16:14
Trying to ping for an update here as well

**Comment by paoliniluis** [comment] 2023-01-23 17:14
@resilience we're working on every release to make the subscription charts as similar as the ones you see on the frontend

**Comment by laurenbetz** [comment] 2023-04-19 21:18
@paoliniluis has there been any progress here? 

I am having difficulty still with map views and pivoted tables with conditional formatting. With the subscription they all come through as tables despite the saved formatting. It would be great to know where this is at or whether I have missed some existing workaround.

**Comment by paoliniluis** [comment] 2023-04-19 22:09
we made more changes in 46, and we'll be closing this issue soon to start creating atomic issues rather than a general one like this one

**Comment by laurenbetz** [comment] 2023-04-20 01:33
so just to confirm it will not be possible to have map views and pivot tables render in email subscriptions on 44? And if we upgrade to 46 they will be available?

**Comment by paoliniluis** [comment] 2023-04-20 02:28
In 46 maps and pivot tables are not yet available in subscriptions
dashboard
![image](https://user-images.githubusercontent.com/1711649/233241944-1c14d25c-422d-46b0-9f81-cc2ed957fb2d.png)

email
![image](https://user-images.githubusercontent.com/1711649/233241926-a0cba543-09fd-4e66-a68a-66bacb29ca97.png)

we're adding new visualizations as we can, but focusing mainly on the ones that are used most by customers

**Comment by caramkarter** [comment] 2023-06-23 16:00
Is there existing documentation for how different visualizations are transformed from dashboard to dashboard subscriptions? I had to do quite a bit of trial and error and would like to avoid that in the future when building out a dashboard intended to be shared as an email report.

**Comment by ojjj13** [comment] 2023-12-13 01:10
Since we are subscribed from the dashboard, why don't render the card in the same way they rendered in dashboard?

**Comment by markbastian** [comment] 2024-01-09 17:40
@cdeweyx I think we need to convert this to an Epic and start with:
* A list of all chart types and how they currently render when sent as a pulse (This may already exist, and @mazameli summarized this well above)
* Create issues for each gap where a dashboard chart does not match the expected pulse chart

We should work off of the Epic and associated tickets as that gives us a concrete set of gaps and a definition of done. Thoughts?

**Comment by cdeweyx** [comment] 2024-05-23 14:07
Addressed for Line / Area / Bar / Combo / Scatter / Waterfall charts in 50

**Comment by cdeweyx** [comment] 2024-05-23 14:16
Closing 🎉 We'll open up new viz-specific issues as needed for outstanding chart types

**Closed by cdeweyx** 2024-05-23 14:16 UTC
Labels: Type:Bug, Priority:P2, Reporting/Pulses, .Completeness, Visualization/Static, .Team/DashViz, .LongTerm

**Comment by JurenaMat** [comment] 2024-10-08 09:15
@cdeweyx , we crucially need pulses to support visualizing pivot tables. Should I create a new task for that as this one has been closed, even though it is resolved only partially?

**Comment by paoliniluis** [comment] 2024-10-08 09:24
@JurenaMat it's https://github.com/metabase/metabase/issues/43638
