### ISSUE TITLE
After upgrading to v0.39.0.1:: ERROR MESSAGES java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel

### ISSUE THREAD

**Issue by mglaredo** [metabase/metabase#15806] opened 2021-04-26 11:34 UTC
**Describe the bug**
After upgrading to v0.39.0.1, error messages about "Error determining whether HTTP request was canceled" and 
"java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel"

**Logs**
<details><summary>SERVER/LOG ERRORS</summary>

```
2021-04-26 12:42:14,212 ERROR async.streaming-response :: Error al determinar si se canceló la solicitud HTTP
java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:139)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:130)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__16190$state_machine__8591__auto____16197$fn__16199$inst_16139__16214.invoke(streaming_response.clj:165)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308$fn__13309.invoke(util.clj:53)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308.invoke(util.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-26 12:42:14,486 ERROR async.streaming-response :: Error al determinar si se canceló la solicitud HTTP
java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:139)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:130)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__16190$state_machine__8591__auto____16197$fn__16199$inst_16139__16214.invoke(streaming_response.clj:165)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308$fn__13309.invoke(util.clj:53)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308.invoke(util.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-26 12:42:14,762 ERROR async.streaming-response :: Error al determinar si se canceló la solicitud HTTP
java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:139)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:130)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__16190$state_machine__8591__auto____16197$fn__16199$inst_16139__16214.invoke(streaming_response.clj:165)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308$fn__13309.invoke(util.clj:53)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308.invoke(util.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-26 12:42:15,214 ERROR async.streaming-response :: Error al determinar si se canceló la solicitud HTTP
java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:139)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:130)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__16190$state_machine__8591__auto____16197$fn__16199$inst_16139__16214.invoke(streaming_response.clj:165)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308$fn__13309.invoke(util.clj:53)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308.invoke(util.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-26 12:42:15,489 ERROR async.streaming-response :: Error al determinar si se canceló la solicitud HTTP
java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:139)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:130)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__16190$state_machine__8591__auto____16197$fn__16199$inst_16139__16214.invoke(streaming_response.clj:165)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308$fn__13309.invoke(util.clj:53)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308.invoke(util.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-26 12:42:15,764 ERROR async.streaming-response :: Error al determinar si se canceló la solicitud HTTP
java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:139)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:130)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__16190$state_machine__8591__auto____16197$fn__16199$inst_16139__16214.invoke(streaming_response.clj:165)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308$fn__13309.invoke(util.clj:53)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308.invoke(util.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-26 12:42:16,217 ERROR async.streaming-response :: Error al determinar si se canceló la solicitud HTTP
java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:139)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:130)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__16190$state_machine__8591__auto____16197$fn__16199$inst_16139__16214.invoke(streaming_response.clj:165)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308$fn__13309.invoke(util.clj:53)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308.invoke(util.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-26 12:42:16,491 ERROR async.streaming-response :: Error al determinar si se canceló la solicitud HTTP
java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:139)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:130)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__16190$state_machine__8591__auto____16197$fn__16199$inst_16139__16214.invoke(streaming_response.clj:165)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308$fn__13309.invoke(util.clj:53)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308.invoke(util.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-26 12:42:16,769 ERROR async.streaming-response :: Error al determinar si se canceló la solicitud HTTP
java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:139)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:130)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__16190$state_machine__8591__auto____16197$fn__16199$inst_16139__16214.invoke(streaming_response.clj:165)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308$fn__13309.invoke(util.clj:53)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308.invoke(util.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-26 12:42:17,223 ERROR async.streaming-response :: Error al determinar si se canceló la solicitud HTTP
java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:139)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:130)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__16190$state_machine__8591__auto____16197$fn__16199$inst_16139__16214.invoke(streaming_response.clj:165)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308$fn__13309.invoke(util.clj:53)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308.invoke(util.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-26 12:42:17,494 ERROR async.streaming-response :: Error al determinar si se canceló la solicitud HTTP
java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:139)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:130)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__16190$state_machine__8591__auto____16197$fn__16199$inst_16139__16214.invoke(streaming_response.clj:165)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308$fn__13309.invoke(util.clj:53)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308.invoke(util.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-26 12:42:17,771 ERROR async.streaming-response :: Error al determinar si se canceló la solicitud HTTP
java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:139)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:130)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__16190$state_machine__8591__auto____16197$fn__16199$inst_16139__16214.invoke(streaming_response.clj:165)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308$fn__13309.invoke(util.clj:53)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308.invoke(util.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-26 12:42:18,225 ERROR async.streaming-response :: Error al determinar si se canceló la solicitud HTTP
java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:139)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:130)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__16190$state_machine__8591__auto____16197$fn__16199$inst_16139__16214.invoke(streaming_response.clj:165)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308$fn__13309.invoke(util.clj:53)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308.invoke(util.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-26 12:42:18,497 ERROR async.streaming-response :: Error al determinar si se canceló la solicitud HTTP
java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:139)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:130)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__16190$state_machine__8591__auto____16197$fn__16199$inst_16139__16214.invoke(streaming_response.clj:165)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308$fn__13309.invoke(util.clj:53)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308.invoke(util.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-26 12:42:18,690 INFO middleware.cache :: La consulta tardó 11,1 s en ejecutarse; el mínimo para la elegibilidad de caché es 60,0 s
2021-04-26 12:42:18,719 DEBUG middleware.log :: POST /api/card/70/query 202 [ASYNC: completed] 11,3 s (10 llamadas a la BBDD) Conexiones BBDD: 1/7 Hilos Jetty: 4/50 (6 esperando, 0 en cola) (99 hilos totales activos) Consultas en ejecución: 2 (0 en cola)
2021-04-26 12:42:18,728 INFO middleware.cache :: La consulta tardó 11,8 s en ejecutarse; el mínimo para la elegibilidad de caché es 60,0 s
2021-04-26 12:42:18,783 ERROR async.streaming-response :: Error al determinar si se canceló la solicitud HTTP
java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:139)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:130)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__16190$state_machine__8591__auto____16197$fn__16199$inst_16139__16214.invoke(streaming_response.clj:165)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308$fn__13309.invoke(util.clj:53)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308.invoke(util.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-26 12:42:18,807 DEBUG middleware.log :: POST /api/card/68/query 202 [ASYNC: completed] 12,1 s (10 llamadas a la BBDD) Conexiones BBDD: 1/7 Hilos Jetty: 4/50 (6 esperando, 0 en cola) (99 hilos totales activos) Consultas en ejecución: 1 (0 en cola)
2021-04-26 12:42:19,228 ERROR async.streaming-response :: Error al determinar si se canceló la solicitud HTTP
java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:139)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:130)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__16190$state_machine__8591__auto____16197$fn__16199$inst_16139__16214.invoke(streaming_response.clj:165)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308$fn__13309.invoke(util.clj:53)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308.invoke(util.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-26 12:42:20,231 ERROR async.streaming-response :: Error al determinar si se canceló la solicitud HTTP
java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:139)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:130)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__16190$state_machine__8591__auto____16197$fn__16199$inst_16139__16214.invoke(streaming_response.clj:165)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308$fn__13309.invoke(util.clj:53)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308.invoke(util.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-26 12:42:21,235 ERROR async.streaming-response :: Error al determinar si se canceló la solicitud HTTP
java.lang.ClassCastException: org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to java.nio.channels.SocketChannel
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:139)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:130)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__16190$state_machine__8591__auto____16197$fn__16199$inst_16139__16214.invoke(streaming_response.clj:165)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308$fn__13309.invoke(util.clj:53)
	at metabase.async.util$cancelable_thread_call$f_STAR___13308.invoke(util.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

**To Reproduce**
1. Upgrade from v0.38.1 to v0.39.0.1
2. Navigate to dashboard on HTTPS server
3. While loading questions (graphs and tables), those errors occured
4. See errors on LOGs and Firefox console (debug)

**Expected behavior**
I expected a newer version improved my metabase server without any new errors

**Severity**
These messages are annoying but not blocking the usage of Metabase so far.

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_272-b10",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "1.8.0_272",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.272-b10",
    "os.name": "Linux",
    "os.version": "4.18.0-193.6.3.el8_2.x86_64",
    "user.language": "es",
    "user.timezone": "Europe/Madrid"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.3.17-MariaDB"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.39.0.1",
      "date": "2021-04-20",
      "branch": "release-x.39.x",
      "hash": "47bb5f2"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by mglaredo** [comment] 2021-04-26 11:37
I had found some older issues related to this one, but not helping me:

- https://discourse.metabase.com/t/error-determining-whether-http-request-was-canceled/12227
- https://github.com/metabase/metabase/issues/12335
- https://discourse.metabase.com/t/continuous-errors-until-complete-query-execution/10202

**Comment by flamber** [comment] 2021-04-26 11:45
Hi @mglaredo 
How are you hosting Metabase, and how have you configured https and which reverse-proxy are you using?

**Comment by mglaredo** [comment] 2021-04-26 15:40
Hi @flamber. 

- We host Metabase from our own: starting JAR on Linux Server.
- HTTPS: I setup MB_JETTY_SSL, MB_JETTY_SSL_KEYSTORE, MB_JETTY_SSL_KEYSTORE_PASSWORD and MB_JETTY_SSL_PORT before launching JAR.
- Sorry but I am not aware of using reverse-proxy, but could ask to System or Network Administrators.

Let me know how could I deep into more information for help your investigation.
So thanks in advance!

**Comment by flamber** [comment] 2021-04-26 17:18
@mglaredo Okay, I have no idea why you haven't seen this in the logs in previous versions, since it's been around since 0.35 or something like that. But it doesn't cause any problems, though it's annoying in the logs.
If you want to get rid of those errors, then terminate HTTPS in a reverse-proxy instead of Jetty - it's also easier to maintain certificates outside of Jetty.
Closing as duplicate of #13771

**Closed by flamber** 2021-04-26 17:18 UTC
Labels: .Needs Triage, Type:Bug
