### ISSUE TITLE
MongoDB No fields found for table "levels".

### ISSUE THREAD

**Issue by k2xl** [metabase/metabase#24039] opened 2022-07-17 15:27 UTC
Tried today with latest dockerfile deploy. Connected to MongoDB via connection string - yet I'm seeing this error pop up that it can't find fields. The table names do show up however.

**Comment by paoliniluis** [comment] 2022-07-17 15:34
I'm guessing this is a duplicate of https://github.com/metabase/metabase/issues/10343

**Closed by paoliniluis** 2022-07-17 15:34 UTC
Labels: Type:Bug, .Needs Triage

**Comment by k2xl** [comment] 2022-07-17 15:38
Aye most likely it is that. Thanks
