### ISSUE TITLE
Support InfluxDB

### ISSUE THREAD

**Issue by proffalken** [metabase/metabase#13174] opened 2020-08-27 11:32 UTC
**Is your feature request related to a problem? Please describe.**

This platform looks amazing, however 90% of our data (and that of our customers!) is stored in InfluxDB.

It would be great to be able to pull that data out of Influx and analyse it alongside our other solutions.

**Describe the solution you'd like**

A new database connector that supports influxdb

**Describe alternatives you've considered**

None, the data that we process is best suited to a time series database and Influx is our TSDB of choice

**How important is this feature to you?**

It determines whether we adopt metabase as a solution or not.

**Additional context**
N/A

**Comment by flamber** [comment] 2020-08-27 12:18
Duplicate of #2561

**Closed by flamber** 2020-08-27 12:18 UTC
Labels: .Needs Triage, Type:New Feature

**Comment by proffalken** [comment] 2020-08-28 11:34
Thanks @flamber  - I completely missed that one some how!

**Comment by MasiGit** [comment] 2021-02-04 20:06
Any progress here?

**Comment by proffalken** [comment] 2021-02-04 20:27
@MasiGit this moved to issue #2561 - you can follow the conversation there.
