### ISSUE TITLE
Weekday only option for Pulse/Dashboard Subscriptions

### ISSUE THREAD

**Issue by magazinexperts** [metabase/metabase#20355] opened 2022-02-08 23:18 UTC
**Is your feature request related to a problem? Please describe.**
We would like the ability to only send pulses/Dashboard Subscriptions on weekdays.

**Describe the solution you'd like**
We'd like to see either an option for weekdays only (M-F) or a multi-select option for the daily report where you can select multiple days.

**Describe alternatives you've considered**
The majority of the working world works 5 days a week, but actual implementation of a 5 day work-week could vary and alternative configurations could easily allow for be more advanced configurations such as a 4 day workweek or multiple times a week, such as M-W-F

**How important is this feature to you?**
Preventing pulses from firing on weekends would save two annoying emails a week that will never get used. Customizing so it can be easily sent on any combination of weekdays might be more useful to more users.

**Additional context**
The work around is to make 5 pulses, one for each day of the week. But with several of them or frequency changes, that can be quite annoying and there doesn't seem to be a clone pulse option.

**Comment by paoliniluis** [comment] 2022-02-09 00:11
Hi. This might be a duplicate of https://github.com/metabase/metabase/issues/3846

**Closed by paoliniluis** 2022-02-09 00:11 UTC
Labels: Type:New Feature, .Needs Triage
