### ISSUE TITLE
v0.35.3 Can't save Questions with Empty Results Again

### ISSUE THREAD

**Issue by Alxander64** [metabase/metabase#12584] opened 2020-05-25 15:23 UTC
**Describe the bug**
Saw a similar issue on this before, although I still can't seem to save table questions with empty results from a Postgres database. I believe comments in #9286 said to clear browser cache, which I tried and still no luck.

**Logs**
```
[3988efb5-2679-4c47-a3ed-9b447eba9320] 2020-05-25T11:16:27-04:00 DEBUG metabase.middleware.log POST /api/card 400 1.1 ms (0 DB calls)
{:errors {:result_metadata "value may be nil, or if non-nil, value must be an array of valid results column metadata maps."}}
```

**To Reproduce**
1. v0.35.3 with Postgres database connection
2. Custom SQL query with empty table result
3. Try to save question

**Expected behavior**
Question is saved as normal.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chromium Version 83.0.4103.61 (Official Build) snap (64-bit)
- Your operating system: Ubuntu 20.04
- Your databases: Postgres
- Metabase version: v0.35.3
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Comment by flamber** [comment] 2020-05-25 15:27
Duplicate of #11256

**Closed by flamber** 2020-05-25 15:27 UTC
Labels: .Needs Triage, Type:Bug
