### ISSUE TITLE
Manual y-axis range doesn't display as expected with logarithmic scale

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11190] opened 2019-10-23 00:19 UTC
If you set a manual maximum range for a y-axis when using the logarithmic scale, the y-axis tick marks don't match your input. In this case, I've input `100,000` for the max of my y-axis, but `59,874.14` is displayed instead:

![image](https://user-images.githubusercontent.com/2223916/67345322-76dbfb00-f4ef-11e9-944e-90ae3e7eee8b.png)

**Comment by flamber** [comment] 2019-10-23 00:30
@mazameli Probably caused by PR #10396 - not sure if this is a duplicate of issue #10434, since this involves log scale, but it has all the same characteristics.

**Comment by JesseSDevaney** [comment] 2024-05-17 19:26
Could not reproduce:


https://github.com/metabase/metabase/assets/22608765/f08e4cee-7a3a-4699-bac9-42655fe79235

**Closed** 2024-05-27 08:23 UTC
Labels: Type:Bug, Priority:P2, Visualization/Chart Settings, .Frontend, .echarts-scope, .Team/DashViz
