### ISSUE TITLE
Legend labels on pie charts on dashboards where the legend is below the pie and the percentage is on the wedge have an extraneous dash 

### ISSUE THREAD

**Issue by cbalusek** [metabase/metabase#46213] opened 2024-07-26 21:20 UTC
### Describe the bug

If you make a pie chart really long on a dashboard so the legend is below the pie, and you set the percentages to show on the pie chart, the legend will have an extraneous dash like, "Pie - "

<img width="376" alt="image" src="https://github.com/user-attachments/assets/e62f60ec-f56c-4584-8ab5-d19dc72c81f6">

### To Reproduce

1.  Create a pie chart
2. Put it on a dash
3. Make the pie chart card really long so the legend is below piet
4. Marvel at the legend being below the pie
5. Set the pie chart display settings to have the percentage on the chart

### Expected behavior

There should not be a dash

### Information about your Metabase installation

```JSON
Built on 2024-07-26

Hash: f27d115
```

### Severity

It doesn't look great, but it works

### Additional context

See example at https://stats.metabase.com/dashboard/2546

**Comment by EmmadUsmani** [comment] 2024-07-26 22:00
Related to / duplicate of https://github.com/metabase/metabase/issues/29597

**Closed** 2024-11-18 20:04 UTC
Labels: Type:Bug, Priority:P3, Visualization/Maps, Visualization/Charts/Pie, .Team/DashViz
