### ISSUE TITLE
Change "Getting set up" labels item to collections

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#4303] opened 2017-02-03 18:21 UTC
As show in the screenshot in #4295 we're still showing a "Getting set up" item asking you to create labels, which are now pretty much deprecated (it's very difficult to create new labels). We should replace that with one for collections.

![image](https://cloud.githubusercontent.com/assets/18193/22602983/53da0956-e9fa-11e6-8119-f6c52c03a8a0.png)

**Comment by tlrobinson** [comment] 2017-02-03 18:22
This should be an easy one: https://github.com/metabase/metabase/blob/121500bd2099eb5564c7fe72fbe3a93e407ffea1/src/metabase/api/setup.clj#L143-L148

**Comment by kdoh** [comment] 2017-02-03 20:01
Duplicate of #4260

**Closed by kdoh** 2017-02-03 20:01 UTC
Labels: Help Wanted, Proposal, UX
