### ISSUE TITLE
Display indicator always

### ISSUE THREAD

**Issue by kinbod** [metabase/metabase#11417] opened 2019-12-01 01:09 UTC
How can I setup it always show on top of picture like below.
![image](https://user-images.githubusercontent.com/8268021/69907921-42c2f680-141a-11ea-8a36-6fc3564a6fa0.png)

**Comment by flamber** [comment] 2019-12-01 07:27
Hi @kinbod 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Duplicate of #4788. Please close this issue and upvote #4788 by clicking :+1: on the first post.

**Closed** 2019-12-03 22:39 UTC
Labels: .Duplicate
