### ISSUE TITLE
Allow disabling of group removal using LDAP

### ISSUE THREAD

**Issue by adjenks** [metabase/metabase#11886] opened 2020-02-11 17:28 UTC
**Is your feature request related to a problem? Please describe.**
We only want to add users via LDAP, not remove them from groups. Manually set groups are being unset.

**Describe the solution you'd like**
The ability to disable automatic group removal.

**Describe alternatives you've considered**
Edit LDAP with one-off permissions. Disabling LDAP and doing everything manually. Neither is ideal.

**How important is this feature to you?**
Very. Group removal isn't intuitive because you can initially add someone to a group and then they will disappear over night. I've had one person ask me 3 times why they can't access their dashboards and now I look like a fool. On the third time I realized I needed to look into the LDAP configuration. I wasn't the person to originally configure the LDAP settings so I was unaware of the fact that it will "remove users" from groups. At the very least, it should raise a warning when you add a user to a group that will later be removed when synced. Or disable the manual group assignment altogether and just say *YOU CANNOT EDIT GROUPS WHILE LDAP IS ENABLED*.
It should also maybe warn you that all custom group assignments will be destroyed when enabling LDAP, instead of a harmless looking little switch.

**Additional context**
Fool me twice, shame on me?

**Comment by flamber** [comment] 2020-02-11 20:22
Hi @adjenks 
I'm going to close this as duplicate of #7571 - if I misunderstood your request, then please comment back with more details and I'll reopen.

**Closed by flamber** 2020-02-11 20:22 UTC
Labels: .Needs Triage, Type:New Feature

**Comment by adjenks** [comment] 2020-02-11 21:10
@flamber Thank you. It looks the same. I did search for the problem before posting this, but I guess I didn't use the right terms. Thank you again.
