### ISSUE TITLE
Allow Admin To Display "Browse Data" Screen in ERD Format.

### ISSUE THREAD

**Issue by MrChadMWood** [metabase/metabase#39478] opened 2024-03-01 20:57 UTC
**Is your feature request related to a problem? Please describe.**
Not related to a problem, but I'd like to help my users understand the concept of data modelling better. 
They interact with the data via Metabase, it would be nice if they could browse the data in a way that indicated the underlying model of the data.

**Describe the solution you'd like**
Id like the "Browse Data" screen to be an ERD. Users can see relationships between tables via this screen. They could also (still) click a tile to open it up and view the data.

**Additional context**
If multiple schemas are present, this may get complicated if relationships are across schemas?

**Comment by paoliniluis** [comment] 2024-03-01 21:34
maybe duplicate of https://github.com/metabase/metabase/issues/25956?

**Closed** 2024-05-10 15:24 UTC
Labels: Type:New Feature, .Needs Triage
