### ISSUE TITLE
In "OUR DATA" is showing all tables, even if tables are Hidden or even Dropped

### ISSUE THREAD

**Issue by jlisyc** [metabase/metabase#8822] opened 2018-10-30 10:53 UTC
## In "OUR DATA" is showing all tables, even if tables are Hidden or even Dropped.

-------
Your browser and the version: (Firefox 63.0)
Your operating system: (ubuntu 16.04)
Your databases: (Postgres)
Metabase version: (0.30.4)
Metabase hosting environment: (Linux/Ubuntu)
Metabase internal database: (Postgres)

-------
After login on Metabase, in OUR DATA section,
is showing all tables, even if tables are Hidden or even Dropped.
Seems it is not recognising the hidden value , neither false value.

It should work like when you are creating a new question. Creating a question , you are watching only not hidden tables (even for administrators).

Steps to reproduce
- Create a table
- Hide table
You will see in OUR DATA that table.

- dropped table.
You will see in OUR DATA that table.

-------

THANKS!

**Comment by jlisyc** [comment] 2018-10-30 11:35
Related: Even private schemas remain visible to all users
https://github.com/metabase/metabase/issues/8045

**Comment by kdoh** [comment] 2018-10-30 16:31
Thanks for reporting this. I've been able to reproduce the hidden tables / schemas still being visible when looking at the database in the browsing part of the app. I haven't been able to repro the deleted db still showing up in the list part of the issue though, at least so far.

**Comment by jlisyc** [comment] 2018-10-30 17:29
Hi Kyle, 
In case it help for deleted table in db,
 I show you the row at metadata "metabase_table" showing a table dropped from database.
![image](https://user-images.githubusercontent.com/33416503/47737385-1bc34f80-dc71-11e8-87ce-9ba08631ca46.png)


... and in browsing metabase we can see it
![image](https://user-images.githubusercontent.com/33416503/47737566-7e1c5000-dc71-11e8-9e87-9fc6cc6ad4ad.png)

Thanks !

**Comment by kdoh** [comment] 2018-10-30 17:30
Ah got it. I misread table deletion as DB deletion.

**Comment by jlisyc** [comment] 2018-10-30 17:44
sorry. I'll change the issue with word "dropped" instead of "deleted"

**Comment by kdoh** [comment] 2018-10-30 18:43
#8831 should solve the tables marked hidden still showing up in the browse app issue. 

As far as dropped tables go those changes in your db should be getting reflected in Metabase the next time the backend sync process runs for that database. By default it runs every hour but you can do a manual trigger of that if you're doing some DB pruning and want those changes reflected immediately. Would you mind checking if that manual trigger reflects the dropped table changes for you so we can ensure everything there is working as intended?

**Comment by kdoh** [comment] 2018-10-30 18:58
Hrm, after some digging it looks like this isn't the first time the dropped table / schema issue has come up. https://github.com/metabase/metabase/issues/8363. Ping @camsaul / @senior

**Comment by kdoh** [comment] 2018-10-31 17:31
Whoops the PR for the table hiding closed this. Reopening until we figure out whats up on the dropped table side of things.

**Closed** 2018-10-31 19:16 UTC
Labels: Bug, Data Browsing, Priority/P1
