### ISSUE TITLE
Chained filter endpoints fail without data permissions

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#13537] opened 2020-10-20 17:26 UTC
The chained filter endpoints 403 when the user doesn't have data permissions. Access to these endpoints should match access to the dashboard itself.

Repro steps:
1. Create a dashboard with a filter.
2. Create a user with collection perms but no data perms.
2. Accessing that dashboard as that user will show a 200 for `GET /api/dashboard/:id` but 403 on `GET /api/dashboard/:id/params/:id/values` when you click on the filter.

**Comment by camsaul** [comment] 2020-10-20 17:59
That's the same behavior from the old field values endpoints... you have to have read perms for the underlying Field to be able to fetch values from it. Otherwise we'd be letting people bypass locked down perms and open the door to bad security situations. Maybe that behavior should be revisited, but it's been existing/intended behavior for years now so I don't think we should rush out a sudden change to it before shipping 37

**Comment by camsaul** [comment] 2020-10-20 18:00
The old endpoint does the same thing:

https://github.com/metabase/metabase/blob/master/src/metabase/api/field.clj#L171-L175

**Comment by paulrosenzweig** [comment] 2020-10-20 18:04
I think that behavior made sense on the old endpoint since there was no "parent" collection permission to grant you access to the field data. Here, I think we should take access to the dashboard as access to fully use the filters.

But yeah, I'm fine with waiting until 0.37.x to ship this. Rushing out permissions changes is scary.

**Comment by camsaul** [comment] 2020-10-20 18:17
I'm still not convinced we want to ship this anyway -- it just doesn't make sense when things like sandboxing are in play. See https://github.com/metabase/metabase-enterprise/issues/411

Basically what this issue is asking for is to treat any Users with no Field read perms whatsoever as if they had full unsandboxed read perms for that Field. So if you had sandboxed read perms you'd actually end up seeing less possible values than if the admin configured you to have no access whatsoever. It's a security behavior that is really confusing and really dangerous IMO.

Security implications WRT sandboxing aside, this isn't a trivial change. The value of Dashboard `:parameters` was really a frontend-only thing prior to 0.37.0. The backend didn't didn't read/validate this column at all -- if you have write perms for a Dashboard you could change it, and if you had read perms you could see it, but it was really just a column where the FE could store whatever metadata it wanted related to parameters.

So a bad actor could of course have put parameters entries in there that reference arbitrary Field IDs. The backend permissions checks happen around the Field IDs themselves, so that sort of stuff wouldn't matter -- the FE could try to fetch info/values for the Fields referenced by those parameters, but if the current user didn't have read perms for the Field(s), the request would return a 403.

Bypassing Field perms checks in the parameters endpoints would only be something we should be comfortable doing if we're confident that the `:parameters` saved in a Dashboard were validated, which they're not. `:parameters` is still essentially treated as untrusted input by the backend.

So to fix this (assuming we wanted to) I think we'd need to rename `parameters` to `legacy_untrusted_parameters` or something like that and create a new trusted `parameters` column that we'll use for all new Dashboards or when you re-save existing ones. And only for the new trusted `parameters` could we even consider bypassing normal Field permissions checks

**Comment by paulrosenzweig** [comment] 2020-10-20 19:35
To complicate things further: I think we want the same behavior to apply to native question field filters. i.e. if you have collection perms on a question, you should be able to use its filters. Those haven't been converted to chained filter endpoints, but I think they should be (#13480).

I see your point that adding this functionality requires validating referenced field ids in a way we haven't before. The migration path you spelled out sounds super annoying, but I can't think of anything better.

I do think the ideal behavior is that questions/dashboards contain permissions to use all their referenced resources. It feels consistent that GUI questions grant access to the tables they reference and dashboards or native questions grant access to their field filters' values. In both cases, I think it's clear to the creator what's visible to the viewer.

For sandboxing, I agree it's weird that with no data perms you'd see a full list, but with sandboxed perms you'd see a subset. I think that's right though. Unless I'm misunderstanding, it matches how viewing a GUI question works, right?

**Comment by nemanjaglumac** [comment] 2021-01-28 21:13
If you check attached screenshots in https://github.com/metabase/metabase/pull/14557, this behavior is clearly visible in that repro.

Should I extract just the XHR part and make a separate repro for this issue? We should at least have a cross-reference between the issues.

**Comment by paulrosenzweig** [comment] 2021-01-29 16:27
@nemanjaglumac I'm not sure what you mean by "extract just the XHR part". I think the ideal repro for this issue would not assert on the 403 itself but instead look for the values that should appear in the popover. The same question/dashboard setup from the other repro might be the same here though if that's what you mean.

---

As a side note, I think these issues appear similar but have different causes. It looks like #12720 is due to us trying to modify a question and run a query adhoc rather than using the question's parameters. This issue is due to us not having a good way to grant specific metadata access to dashboard viewers.

**Comment by nemanjaglumac** [comment] 2021-01-29 17:18
@paulrosenzweig sorry, I meant - write the repro up to the point where we hit the XHR and assert on its `status` and/or any part of its response.

**Comment by camsaul** [comment] 2021-05-05 00:49
This is basically the same issue as #12654 or #15119

**Comment by camsaul** [comment] 2022-04-20 20:24
I think bare minimum we need to check that the parameter (Field) you're trying to fetch values for belongs to a Card+Dashboard you have permissions to run queries for, and then we need to be careful that we're still applying any sandboxing to the query we run. This is kind of a tricky situation because maybe the Card you have permissions to run has some built in filter like `[:not= [:field "status" ...] "secret"]` which means you'd never normally be able to see the secret rows with only Card permissions; returning the values for a Field from those rows seems like a big no-no. So maybe if you don't have full data perms we actually need to be splicing in additional `WHERE` clauses from the Card(s) in question as well when doing the chain filter query. That's complicated. 😢

**Comment by noahmoss** [comment] 2023-03-09 20:37
Closed by #28581

**Closed by noahmoss** 2023-03-09 20:37 UTC
Labels: Type:Bug, Priority:P2, Querying/Parameters & Variables
