### ISSUE TITLE
CSV export of table with 2 groupings has wrong format

### ISSUE THREAD

**Issue by MarkVillacampa** [metabase/metabase#3075] opened 2016-07-29 02:02 UTC
In the Table view of a query with two gropings, each grouping acts as value for the first row and the first column. However when exported to CSV, the formatting is not kept.

Attached pictures for reference:

![screen_shot_2016-07-29_at_3_58_15_am](https://cloud.githubusercontent.com/assets/1014118/17235430/4b9af1ae-5541-11e6-9ac4-366c4870b4b1.png)
![screen_shot_2016-07-29_at_3_58_31_am](https://cloud.githubusercontent.com/assets/1014118/17235431/4bd53b8e-5541-11e6-8683-dc642995e462.png)

**Comment by camsaul** [comment] 2016-07-29 02:20
Duplicate of #2473

**Closed** 2016-07-29 02:21 UTC
Labels: Duplicate
