### ISSUE TITLE
Freezing issue while embedding dashboard from metabase to other applications

### ISSUE THREAD

**Issue by kunalmanuanant** [metabase/metabase#6572] opened 2017-12-13 07:37 UTC
@tlrobinson  @camsaul  @kdoh  @salsakran @mazameli I am new to Metabase and embedded the dashboard in my java application but i am facing freezing problem(click on the circle of line graph and it tool tip freeze) . I think whenever i click on the graph it try to fetch more data from the database and in metabase log it show this error "ORA-01000: maximum open cursors exceeded". Is there any way to restrict embedded applications sync only to view mode?
![metabase](https://user-images.githubusercontent.com/34364608/33927168-3be9c990-e007-11e7-887a-f63e2f23a77e.png)

**Comment by salsakran** [comment] 2017-12-13 20:28
probable dupe of #6467

**Comment by tbrockhouse** [comment] 2018-01-17 11:48
I am also experiencing this issue, tool tip freezes after clicking on an embedded chart (Version 0.27.2).
I get the following error in the Chrome console when viewing the question in embed preview. 

![image](https://user-images.githubusercontent.com/24715699/35041198-d0a81d18-fb7b-11e7-89a6-989c168ca881.png)

**Comment by StraylightSky** [comment] 2018-02-28 18:01
Also running into this issue in v0.28.1. I get the same error as @tbrockhouse in Chrome's console. I get a different error in Firefox:

![image](https://user-images.githubusercontent.com/1560034/36803420-53fc7f9a-1c6c-11e8-9351-343d8c778914.png)

This was the closest related issue I could find that had a resolution: https://github.com/metabase/metabase/issues/4671 but the suggestion to not self-close the `<iframe>` tag does not fix the problem for me.

Most likely related, but unknown if they are embedding their dashboard: https://github.com/metabase/metabase/issues/6711

**Comment by kelsen** [comment] 2019-08-16 18:50
I'm having this issue also with embeded dashboard, I believe that setting iframe width=100% combined with @StraylightSky's "self-close" `<iframe>` tag solution has worked, at least untill now.

**Comment by flamber** [comment] 2020-05-25 08:21
Closing, since original issue was likely fixed by one of the PRs for #6467.
I cannot reproduce on 0.35.3, but the "sticky" tooltip on touch/mobile devices is #6711.
Please comment with version info and code to reproduce if you're still experiencing this.

**Closed by flamber** 2020-05-25 08:21 UTC
Labels: Database/Oracle, Priority:P2, Type:Bug

**Comment by theharisshah** [comment] 2020-09-18 17:53
I am facing this issue on version  0.34.1, the embedded dashboards work fine when opened on phone, or on mac (chrome) but when opening on windows 10 (almost every browser) the page becomes unresponsive and shows loading animation.
I am using php here is my code
```
$signer = new Sha256();
$token = (new Builder())
            ->set('resource', ['dashboard' => 1])
            ->set('params', ['param' => ''])
            ->sign($signer, env('METABASE_SECRET_KEY'))
            ->getToken();
 $metabaseSiteUrl = env('METABASE_URL');
return "$metabaseSiteUrl/embed/dashboard/$token#bordered=false&titled=true";
```
Please not I am also getting these console errors irrespective of the platform 
```
vendor.bundle.js?8902e0cb00fa4456f7bb:1 Uncaught Invariant Violation: Minified React error 44; 
````

**Comment by flamber** [comment] 2020-09-18 18:04
@theharisshah Try upgrading to latest release, 0.36.4, remember to backup first.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
