### ISSUE TITLE
Paginate results or allow next page to retrieve next 2000 rows when limit is reached in first page of results

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#29464] opened 2023-03-22 23:08 UTC
**Is your feature request related to a problem? Please describe.**
Users are unable to see the next set of 2000 rows when they hit the maximum:
![image](https://user-images.githubusercontent.com/8808703/227058188-f69983df-30e3-4758-9988-4d54f89a54b4.png)

**Describe the solution you'd like**
When result datasets are greater than the limits (currently 2k rows unaggregated and 10k aggregated rows), allow users to paginate through results, to allow load of next 2k results or next 10k results.

**Describe alternatives you've considered**
- Group by some categorical column, and try to view filtering by each category one at a time as long as the category contains less than 2k results each. This is challenging and if more than a few categories or no categories with less than 2k members is not workable.

**How important is this feature to you?**
- Limits query results and affects sorting of results with no workaround for large data sets

**Additional context**
Relating to:
- https://github.com/metabase/metabase/issues/4564
- https://github.com/metabase/metabase/issues/8622

**Comment by paoliniluis** [comment] 2024-10-11 10:11
Duplicate of https://github.com/metabase/metabase/issues/8322

**Closed by paoliniluis** 2024-10-11 10:11 UTC
Labels: Type:New Feature, Visualization/Tables, scaling
