### ISSUE TITLE
allow data caching a.k.a. TTL

### ISSUE THREAD

**Issue by CzechJiri** [metabase/metabase#2597] opened 2016-05-12 21:21 UTC
This should be optional for question.

Some questions take longer time to execute, it would be idea if the resultset could be cached for certain period e.g. 1 hour - this way the first user would wait longer and data result would get cached, but all subsequent users would get snappy quick result

you could potentially extend it and auto-execute the query after TTL of the cache expires

**Comment by tlrobinson** [comment] 2016-05-12 21:24
Duplicate of #1666

**Closed by tlrobinson** 2016-05-12 21:24 UTC
Labels: Duplicate
