### ISSUE TITLE
Generate inmmutable canonical URL's for questions or dashboards

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#29901] opened 2023-04-07 23:06 UTC
**Is your feature request related to a problem? Please describe.**
There's an interesting use case where customers might want to pin down a URL no matter the question ID (e.g. the question underneath might change the ID or name, but you want the URL to be always the same). This is useful for customers that want to embed something and don't want to switch the URL but rather they can keep the URL static and then switch internally in Metabase the associated dashboard or question

**Describe the solution you'd like**
Be able to change in Metabase the URL of a question or dashboard

**Describe alternatives you've considered**
Use a reverse proxy on top, and add redirect rules

**How important is this feature to you?**
Requested by a customer

**Additional context**
NA

**Comment by luizarakaki** [comment] 2023-04-24 16:56
@paoliniluis They want a fixed URL and change the underlying question? Like today this URL points to question 123 but now we created a new one and we want it to point to 456?

**Comment by paoliniluis** [comment] 2023-11-13 12:03
@luizarakaki I just saw your comment, they want a fixed url so they can change the question, yes

**Comment by ignacio-mb** [comment] 2023-11-13 12:07
dupe of https://github.com/metabase/metabase/issues/9441?

**Comment by paoliniluis** [comment] 2023-11-13 12:23
yes

**Closed** 2023-11-13 12:23 UTC
Labels: Reporting/Dashboards, Type:New Feature, Organization/Saved Questions, Embedding/, .Team/Embedding
