### ISSUE TITLE
Custom mapped field stop showing values in GUI after syncing database scheme (BigQuery)

### ISSUE THREAD

**Issue by shafy** [metabase/metabase#11265] opened 2019-11-05 08:47 UTC
After re-syncing the database scheme manually, the GUI stops showing values for the custom mapped fields and the filter also don't work. It works again after going into the field settings and clicking save.

Metabase v0.33.4 with BigQuery on Heroku.

**Comment by HKFiliatix** [comment] 2020-02-28 14:59
For mysql re-syncing the database scheme just remove saved mapping values at all

**Comment by flamber** [comment] 2020-02-28 20:07
Unless I'm misunderstanding this, is it a duplicate of #9115?

**Comment by flamber** [comment] 2020-07-01 09:17
Closing in favor of #9115

**Closed by flamber** 2020-07-01 09:17 UTC
Labels: Administration/Data Model, Database/BigQuery, Priority:P2, Type:Bug
