### ISSUE TITLE
Metabase config management

### ISSUE THREAD

**Issue by timrcoulson** [metabase/metabase#12352] opened 2020-04-20 06:08 UTC
**Is your feature request related to a problem? Please describe.**
Our infrastructure provisioning is completely automated minus a few steps - we almost never manually pass around DB connection details. Metabase is one of those exceptions where we have to manually pass in our Redshift credentials to get querying.

**Describe the solution you'd like**
I'm wondering if you think there's an appetite in the community for a Terraform provider to:

- Provision data sources
- Configure authorisation
- Configure anything relevant in "admin/settings"

An alternative solution for our use case could be configuration via Kubernetes ConfigMaps/Secrets.

**How important is this feature to you?**
This is a nice-to-have, but I'm keen to contribute since I love the project.

**Comment by flamber** [comment] 2020-04-20 08:52
Hi @timrcoulson 
It sounds like a duplicate of #2052. If you agree, then please close this and upvote the other issue :+1:

**Closed** 2020-04-20 08:55 UTC
Labels: .Needs Triage, Type:New Feature
