### ISSUE TITLE
Filter by joined value

### ISSUE THREAD

**Issue by simopaasisalo** [metabase/metabase#2652] opened 2016-05-24 09:02 UTC
Hi,

Would be nice to be able to filter by joined data. 
Example:
Warehouse-contains fields TemperatureMin, TemperatureMax
Temperature-contains fields Value and WarehouseId
I would like to filter Temperatures that are within the Warehouse's limits. 
Sample SQL: ...WHERE temperature.value > warehouse.temperatureMax

**Comment by camsaul** [comment] 2016-05-24 17:00
@simopaasisalo you can actually already filter by values in a joined table if there is foreign key relationship to that table (either detected automatically or marked as such in the admin metadata page). Unfortunately you can't filter using two fields; Metabase currently only supports filtering a single field against a literal value.

Filtering with 2 fields is already open in #1834, so I'm going to close this as a duplicate of that.

**Closed by camsaul** 2016-05-24 17:00 UTC
Labels: Duplicate

**Comment by simopaasisalo** [comment] 2016-05-25 05:35
@camsaul Thanks for the response. I can't seem to get it working though; in the filter options I select "temperature.value" and it tells me to enter desired number. I can't input any kind of text in that field, nor does Metabase autofill anything when I try to input "Warehouse.temperatureMax". Am I missing something here?

**Comment by camsaul** [comment] 2016-05-25 05:38
@simopaasisalo you can't currently use 2 different fields in the same filter clause, so until #1834 is implemented there is no way to filter `temperature.value > warehouse.temperatureMax`.

**Comment by simopaasisalo** [comment] 2016-05-25 05:40
@camsaul Oh okay, I misunderstood your first response. Thanks for the response!
