### ISSUE TITLE
Bug when filtering on large amount of values

### ISSUE THREAD

**Issue by yanivgold** [metabase/metabase#7200] opened 2018-03-26 10:28 UTC
![metabase error](https://user-images.githubusercontent.com/34236853/37901321-0d42571e-311b-11e8-92db-9144d7800f94.PNG)
We are finding Metabase as a great platform for non tech users to create their own reports and dashboards, responses are truly great! we did run into what seems to be a bug, when copy pasting a large number of values to filter on. The query breaks both on the 'elegant' UI and the query editor, while running the same query in an external query editor returns an answer with no problem.
The number of values trying to filter on is ~34k
Details needed:
Browser- Chrome 64.0.3282.186 (64 bit)
OS- Windows 10 Enterprise
Database- Vertica
Metabase version- v0.28.2
Hosting environment- CentOS Linux release 7.4.1708
Internal database- PostgreSQL

**Comment by jornh** [comment] 2018-03-26 13:49
Just another Metabase user here. 

The error message indicates that it is the Vertica JDBC driver that is returning the error message, see: https://www.google.com/search?q=%2Bvertica+the+query+contains+an+expression+that+is+too+complex+to+analyze

A few points to maybe explore:
* Is the other external query editor you are using also talking through JDBC? 
* Could there be differences in the Vertica JDBC driver version, see https://github.com/metabase/metabase/blob/master/docs/administration-guide/databases/vertica.md
* Can you grab the exact outgoing query either in the Metabase logs - or preferably incoming in Vertica (I'm not familiar with it) and compare that ... then use that for comparison?

**Comment by yanivgold** [comment] 2018-03-27 08:08
@jornh , thanks for this.
It seems the query generated by metabase in this case is a big 'or' statement, whereas I would expect it to be an 'in' statement. The mentioned causes the statement to be a very long one that could not be executed (it has 30k different 'or' values). Can anything be done to resolve this?
Thanks!

**Comment by camsaul** [comment] 2024-07-02 20:38
Same underlying issue as #23101; when #23101 gets fixed this will be fixed too.

Since #23101 has had more activity I'm going to close this as a duplicate of that one 

Duplicate of #23101

**Closed by camsaul** 2024-07-02 20:38 UTC
Labels: Type:Bug, Priority:P3, .Performance, Querying/Processor, Database/Vertica, .Backend, .Team/QueryProcessor
