### ISSUE TITLE
iPad: Question page goes blank

### ISSUE THREAD

**Issue by o2genum** [metabase/metabase#22537] opened 2022-05-09 15:53 UTC
**Describe the bug**
On iPad, when the query result has loaded, the question page goes blank.

Works well on Mac (Safari Version 15.4 (17613.1.17.1.13)).

**Logs**
Safari Web Inspector log:
<img width="1002" alt="Screen Shot 2022-05-09 at 18 49 56" src="https://user-images.githubusercontent.com/658230/167448282-bcccb56b-e3d2-48fe-aade-369bc5e7ee18.png">
Full exported log: 
[Console.txt](https://github.com/metabase/metabase/files/8653253/Console.txt)

Metabase version: v0.43.0

OS version: iPadOS 15.4.1

No content blockers/extensions in Safari.

**To Reproduce**
1. Go to any question
2. Wait for it to load.
3. When the query result is ready, the page goes blank.

**Severity**
No casually going through questions on iPad, pretty annoying.

**Comment by flamber** [comment] 2022-05-09 15:56
Duplicate of #22172

**Closed by flamber** 2022-05-09 15:56 UTC
Labels: Type:Bug, .Needs Triage
