### ISSUE TITLE
Filter / Grouping by Month / Quarter doesn't work

### ISSUE THREAD

**Issue by ccasado-asac** [metabase/metabase#9355] opened 2019-01-31 09:29 UTC
I tried on several browsers and systems, here is the data:
--------------------------------------------------
- Your browser and the version: Chrome 71.0.3578.98 / Opera 57.0.3098.106 / Firefox 65.0
- Your operating system: Windows 7 / Windows 10 / Windows Server 2008R2
- Your databases: SQL Server 2008
- Metabase version: 0.31.2
- Metabase hosting environment: Windows 7 / Windows Server 2008R2
- Metabase internal database: H2
--------------------------------------------------

When I try to filter or group by months (quarter, last months, etc...) on questions and dashboard filters, they don't work. Shows the next error message:

> com.microsoft.sqlserver.jdbc.SQLServerException: 'format' no es un nombre de función integrada reconocido.

Translate in english:

> com.microsoft.sqlserver.jdbc.SQLServerException: 'format' isn't a recognized integrated function.

I had the suspicion that this is happening because the SQLServer version (2008R2).
How can I solve this issue?

**Comment by flamber** [comment] 2019-01-31 14:43
Duplicate of #2330 - which is sadly a `Won't Fix`.
The only solutions right now is to create Native Questions (SQL) or build your own version where you merge PR #7181

**Comment by ccasado-asac** [comment] 2019-02-01 09:11
Wow! I thought my search skills were better. I search for an issue like this but didn't find anything.
Thanks for pointing me out in the right direction. Pretty sad that is a won't fix when the solution is aplicable for full SQLServer support :/

**Comment by salsakran** [comment] 2019-04-10 05:13
We don't (fully) support SQL Server 2008. We don't intentionally break things but we don't do any automated testing for that version or commit to all features working on it. 

For context, mainstream support for SQLServer 2008 ended over 4 years ago, and we can't support old versions of every databases indefinitely.

**Closed by salsakran** 2019-04-10 05:13 UTC
