### ISSUE TITLE
Clearing filter causes page to close.

### ISSUE THREAD

**Issue by MelUniSA** [metabase/metabase#46949] opened 2024-08-18 23:55 UTC
### Describe the bug

Filter clear attempts to close the webpage.

### To Reproduce

1. Go to native sql query with field filters
2. Click on field filter and select a value
3. Generate the filtered report
4. Click to clear filter
5. See error - "This page is asking you to confirm that you want to leave — information you’ve entered may not be saved."
6. Need to click stay on page in order to clear the filter.

### Expected behavior

Filter would clear.

### Logs

![image](https://github.com/user-attachments/assets/f7c149a7-3713-4be2-ae36-b0b0602b922d)

[f11f6183-f5c3-469d-80e8-a570e7616e38] 2024-08-19T09:22:05+09:30 DEBUG metabase.server.middleware.log GET /api/collection/tree 200 30.6 ms (6 DB calls) App DB connections: 4/13 Jetty threads: 9/50 (1 idle, 0 queued) (121 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[f11f6183-f5c3-469d-80e8-a570e7616e38] 2024-08-19T09:22:05+09:30 DEBUG metabase.server.middleware.log GET /api/setting 200 60.5 ms (16 DB calls) App DB connections: 3/13 Jetty threads: 9/50 (1 idle, 0 queued) (123 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[f11f6183-f5c3-469d-80e8-a570e7616e38] 2024-08-19T09:22:05+09:30 DEBUG metabase.server.middleware.log GET /api/search 200 111.8 ms (5 DB calls) App DB connections: 2/13 Jetty threads: 9/50 (1 idle, 0 queued) (123 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[f11f6183-f5c3-469d-80e8-a570e7616e38] 2024-08-19T09:22:05+09:30 DEBUG metabase.server.middleware.log GET /api/session/properties 200 73.7 ms (12 DB calls) App DB connections: 1/13 Jetty threads: 7/50 (1 idle, 0 queued) (125 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[f11f6183-f5c3-469d-80e8-a570e7616e38] 2024-08-19T09:22:05+09:30 DEBUG metabase.server.middleware.log GET /api/session/properties 200 51.4 ms (12 DB calls) App DB connections: 0/13 Jetty threads: 7/50 (1 idle, 0 queued) (125 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[f11f6183-f5c3-469d-80e8-a570e7616e38] 2024-08-19T09:22:05+09:30 DEBUG metabase.server.middleware.log GET /api/setup/admin_checklist 200 42.3 ms (10 DB calls) App DB connections: 0/13 Jetty threads: 4/50 (3 idle, 0 queued) (127 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[f11f6183-f5c3-469d-80e8-a570e7616e38] 2024-08-19T09:22:05+09:30 INFO metabase.server.middleware.exceptions Request canceled before finishing.
[f11f6183-f5c3-469d-80e8-a570e7616e38] 2024-08-19T09:22:07+09:30 DEBUG metabase.server.middleware.log GET /api/util/bug_report_details 200 10.6 ms (1 DB calls) App DB connections: 0/13 Jetty threads: 4/50 (4 idle, 0 queued) (127 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.15.158.2-1.cm2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.19"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-08-06",
      "tag": "v0.50.19",
      "hash": "0b97bf8"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Annoying

### Additional context

![image](https://github.com/user-attachments/assets/543a2db3-55b7-438e-beb8-1b95d423f91b)

**Comment by kamilmielnik** [comment] 2024-08-19 07:45
It's been fixed in 0.50.20.
Duplicate of #46570.
Closing.

**Closed by kamilmielnik** 2024-08-19 07:45 UTC
Labels: Type:Bug, Priority:P1, .Frontend, .Team/DashViz
