### ISSUE TITLE
Can't download results on mobile viewports

### ISSUE THREAD

**Issue by ZayManor** [metabase/metabase#37532] opened 2024-01-10 19:32 UTC
### Describe the bug

When viewing an embedded dashboard on a desktop device, one can hover the ellipsis to download the results. However, when viewing an embedded dashboard on a mobile device, hovering over the ellipsis does not happen which prevents one from downloading results.``

### To Reproduce

On a mobile device...
1. Go to an embedded dashboard
2. Navigate to the far right side of the dashboard
3. Try to hover the far right side (where the ellipsis is on Desktop)
4. See no ellipsis appear

### Expected behavior

An ellipsis should appear, once clicked the "Download Results" should appear

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.15.98-fly",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-12-01",
      "tag": "v0.47.9",
      "branch": "?",
      "hash": "d05b06e"
    },
    "settings": {
      "report-timezone": "America/New_York"
    }
  }
}
```

### Severity

Blocking some users

**Comment by EmmadUsmani** [comment] 2024-07-18 22:39
Confirmed that this only happens on embedded dashboards, not in app, so perhaps this should be assigned to the embedding team.

![Image](https://github.com/user-attachments/assets/d1178edb-f4be-4f42-a2a5-53dcfb6498f7)

**Comment by npretto** [comment] 2024-07-19 15:47
@ZayManor what os/browser are you using on your phone?
Can you confirm you're talking about the "Download results" on cards inside a *static embedded* dashboard? (Public embeds don't have that functionality yet)

I just tried to reproduce this on v0.47.9 with an iphone but it was working

https://github.com/user-attachments/assets/e8bd06c4-c88d-479f-a662-9052eabf455d

**Comment by albertoperdomo** [comment] 2024-10-20 10:11
Closing as we were are unable to reproduce and OP didn't respond.

**Closed by albertoperdomo** 2024-10-20 10:11 UTC
Labels: Type:Bug, Priority:P2, .Unable to Reproduce, Client:Mobile Web, Reporting/Export, .Frontend, .Team/Embedding
