### ISSUE TITLE
Allow setting login background and navigation colors

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#23323] opened 2022-06-13 23:11 UTC
**Describe the bug**
1) <43 we used the primary color as the background color in the login screen, now in >43 we don't do it anymore
2) <43 we had a navbar color, now we don't have it anymore

**Logs**
NA

**To Reproduce**
1) set up 1.42.4, configure a different primary color AND also a logo (if you don't use a logo, this won't trigger)
2) go to the login screen, see the color
3) now upgrade the instance to 43, you don't see the color anymore

**Expected behavior**
If this is a regression and not an actual decision, see the background color in 43 :)

**Screenshots**
>43
![image](https://user-images.githubusercontent.com/1711649/173462017-533e4a9a-abcd-48f6-b301-7081242199c4.png)

<43
![image](https://user-images.githubusercontent.com/1711649/173462153-923645db-cd06-405b-b3f3-3c482620613f.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop 22.04
- Your databases: Postgres 14.2
- Metabase version: 1.43.3
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14.2

**Severity**
Cosmetic

**Additional context**
NA

**Comment by paoliniluis** [comment] 2022-06-14 02:23
Leaving https://github.com/metabase/metabase/issues/15712 as reference. It seems that we went ahead and left the white color as default no matter what. Maybe it's not a regression but just something that we need to decide how to go forward. If we're not going back we need to change some screenshots

**Comment by Tony-metabase** [comment] 2023-07-11 19:27
Increasing priority since it's a bit problematic when your logo is simply white-background ... Since it get's pretty annoying for people who has that type of logo

<img width="1258" alt="image" src="https://github.com/metabase/metabase/assets/110378427/c43f66e0-7111-4a36-beaa-ddf4f7cd7674">

**Comment by cdeweyx** [comment] 2023-07-24 18:42
On expected behavior:
- +1 we should offer a new "User interface color" for the nav bar. That feels like the problematic thing here, bordering on regression territory.
- I'm not quite as concerned about the login screen. We intentionally removed that in the aforementioned PR here: https://github.com/metabase/metabase/issues/15712

**Comment by Tony-metabase** [comment] 2023-07-25 07:21
I am inclined to agree with you @cdeweyx should i open a separate issue for that? Instead of an additional comment

**Comment by mazameli** [comment] 2023-09-25 18:47
I don't see the need to do anything here. Every brand identity should have a version of the logo to be used on a white background and on a black/dark background — this is exceedingly common. Adding a user interface color setting for the navbar just to address the white logo problem seems really backwards to me.

Strong bias to close as "won't fix."

**Comment by Tony-metabase** [comment] 2023-09-26 06:43
We can recommend customers to have a black and white version of their logo.  

But what we are indirectly saying is that you will have to use a version that only works with white background. So the very least we should make that clear

**Comment by albertoperdomo** [comment] 2023-10-30 15:46
Based on this discussion, I don't think this issue is a P2. Perhaps it should be closed as won't fix, as @mazameli is suggesting.

**Comment by albertoperdomo** [comment] 2023-10-30 15:47
Does anyone feel the strong need to let customers change the nav bar color? It seems there is a strong bias towards treating the login screen as a non-issue.

**Comment by Tony-metabase** [comment] 2023-10-30 18:25
Fine by me. We will not support this and push users that if need be one should have a version of the logo to be used on a white background and on a black/dark background

**Closed by Tony-metabase** 2023-10-30 18:25 UTC
Labels: Priority:P3, Type:New Feature, Administration/Whitelabel
