### ISSUE TITLE
Timestamp granularity together with JSON unfolded grouping causes incorrect results because of bad aliasing of timestamp

### ISSUE THREAD

**Issue by tony-maynard** [metabase/metabase#22831] opened 2022-05-19 08:33 UTC
**Describe the bug**
Using the Question UI with several fields and grouping by date (weekly basis) doesn't seem to work we get outputs like the below 
<img width="731" alt="Screenshot 2022-05-19 at 09 16 56" src="https://user-images.githubusercontent.com/85884885/169246763-71895de1-e043-4651-a61e-07fc1d80b776.png">

The SQL generated from metabase looks like this:

```
SELECT (CAST(date_trunc('week', ("foo"."created_at" + (INTERVAL '1 day'))) AS timestamp) + (INTERVAL '-1 day')) AS "created_at", ("foo"."json" #>> '{url}'::text[])::text  AS "raw_analytics → url", sum(("foo"."json" #>> '{time}'::text[])::double precision ) AS "sum"
FROM "foo"
GROUP BY "created_at", "raw_analytics → url"
ORDER BY (CAST(date_trunc('week', ("foo"."created_at" + (INTERVAL '1 day'))) AS timestamp) + (INTERVAL '-1 day')) ASC, "raw_analytics → url" ASC
```

To get the required outcome I have to change the SQL to include the `(CAST(date_trunc('week', ("foo"."created_at" + (INTERVAL '1 day'))) AS timestamp) + (INTERVAL '-1 day')) ` in the GROUP BY clause instead of the alias. 
<img width="941" alt="Screenshot 2022-05-19 at 09 24 37" src="https://user-images.githubusercontent.com/85884885/169248170-abb23dd7-bc0e-43b0-9e54-670ade383eee.png">

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Using the Question UI select a data source with a **creation timestamp** type
2. summarise with a sum of values
3. group by creation date(week) and a few fields
4. Notice it doesn't group by week

**Expected behavior**
Groups by week and various other fields 

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: 101.0.4951.64 
- Your operating system: OS X 12.3.1 
- Your databases: Postgres
- Metabase version: 0.43.1
- Metabase hosting environment: jar-file
- Metabase internal database: H2

**Severity**
Not severe as we can use the SQL builder

**Comment by flamber** [comment] 2022-05-19 08:47
Hi @tony-maynard 
I'm not sure I understand what is going on. I think you have redacted too much. It looks like `"foo"` is both a timestamp and json column at the same time.

**Comment by tony-maynard** [comment] 2022-05-19 08:50
@flamber Apologies, have updated

**Comment by howonlee** [comment] 2022-08-02 02:40
Hey, we have repeatedly failed to replicate this, first with our own group bys and then trying to replicate the given complex group by - can you still replicate on 44?

**Comment by flamber** [comment] 2022-08-02 14:26
@howonlee 
Reproduce
1. Create table in Postgres
```
CREATE TABLE x_json_issue22831 (
	ts timestamp NULL,
	val int4 NULL,
	str varchar NULL,
	jsoncol json NULL
);
INSERT INTO x_json_issue22831 (ts, val, str, jsoncol) VALUES('2022-08-01 00:00:00.000', 1, '/', '{"jsonstr":"/"}'::json);
INSERT INTO x_json_issue22831 (ts, val, str, jsoncol) VALUES('2022-08-02 00:00:00.000', 2, '/', '{"jsonstr":"/"}'::json);
INSERT INTO x_json_issue22831 (ts, val, str, jsoncol) VALUES('2022-08-03 00:00:00.000', 3, '/', '{"jsonstr":"/"}'::json);
```
2. Question > Postgres > x_json_issue22831
3. Summarize Count and Sum of "val" grouped by "ts":**Month** and **"jsoncol->jsonstr"**
![image](https://user-images.githubusercontent.com/1447303/182398485-3348dbb7-546c-4ec7-a713-f16df059e9ac.png)
4. If you group by regular "str" (non-JSON) instead of "jsoncol->jsonstr", then you get the expected results
![image](https://user-images.githubusercontent.com/1447303/182398770-983989ee-e4af-42ea-a810-28b945471505.png)

**Comment by rlotun** [comment] 2022-08-04 17:17
closed by https://github.com/metabase/metabase/pull/24545

**Closed by rlotun** 2022-08-04 17:17 UTC
Labels: Type:Bug, Priority:P1, Database/Postgres, .Correctness, .Backend, .Regression
