### ISSUE TITLE
Performance problem on postgresql's partitioned tables when using field filter

### ISSUE THREAD

**Issue by onesvat** [metabase/metabase#8275] opened 2018-08-09 20:03 UTC
Partitioned tables are essential for huge tables on postgresql. Timescale uses them too. When using metabase's field filter query planning takes too much, because PostgreSQL query planner cannot evaluate functions and values in where clauses.

It will be nice if metabase put directly dates into sql: `WHERE created_at > '2018-08-09 00:00:00'` not using `date_trunc` and `current_timestamp`

Please check further information: https://dba.stackexchange.com/questions/171057/postgresql-partitioned-table-timestamptz-constraint-problem

**Comment by flamber** [comment] 2019-02-22 07:57
Hi @onesvat 
This looks like a duplicate of #4043

**Comment by camsaul** [comment] 2021-02-15 20:05
Duplicate of #4043, fixed by #10980

**Closed by camsaul** 2021-02-15 20:05 UTC
Labels: .Proposal, Database/Postgres, Type:Performance
