### ISSUE TITLE
`displayInfo` returns unexpected result for a column group

### ISSUE THREAD

**Issue by uladzimirdev** [metabase/metabase#37067] opened 2023-12-22 11:41 UTC
**Context**

To repro the bug:
1. [Go to this question](https://stats.metabase.com/model/15002-active-metabase-user-stats)
2. Click on the filter button

```
return groups.map((group, groupIndex) => {
      const groupInfo = Lib.displayInfo(query, stageIndex, group);
      ....
```

groupInfo is incorrect for a [question from stats](https://stats.metabase.com/model/15002-active-metabase-user-stats)

FE expects the next interface:

```
name: string;
displayName: string;
isSourceTable: boolean;
isFromJoin: boolean;
isImplicitlyJoinable: boolean;
fkReferenceName?: string;
```

And the returned value is different:

<img width="353" alt="image" src="https://github.com/metabase/metabase/assets/125459446/594de213-06d4-4bf9-8859-f694e463dfab">

**Comment by bshepherdson** [comment] 2023-12-22 17:07
The columns returned from the server have `fk_field_id: "customer_id"` even though that should always be a numeric ID.

So this is really a QP bug, but we can work around its immediate consequences by looking up that column by name and using the ID.

PR incoming.

**Comment by bshepherdson** [comment] 2023-12-22 18:21
Once #37079 is in Stats, we should try the problem query again.

**Comment by darksciencebase** [comment] 2023-12-27 07:20
#37079 is on stats, and clicking the Filter button still leads to the “Something's gone wrong” page. `react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'toLowerCase')` and whatnot

**Comment by uladzimirdev** [comment] 2023-12-27 07:54
Confirm what @darksciencebase explored, same problem as it was before 
<img width="549" alt="image" src="https://github.com/metabase/metabase/assets/125459446/6243c0ec-612c-45ae-ab59-a680a02f7adb">

**Comment by bshepherdson** [comment] 2024-01-08 17:41
I can't reproduce this locally, and debugging on stats is hard without CLJS source maps.

I looked into enabling CLJS source maps. There was a shadow-cljs bug [fixed by thheller here](https://github.com/thheller/shadow-cljs/commit/45b017da78f5565f397b4bc7715d80d986b3dd08) and in `2.26.3`.

There was also a bug in the JS libraries for processing input source maps used by the webpack plugins. I've fixed that as well, but it's currently in an [open PR](https://github.com/7rulnik/source-map-js/pull/17) against that library. If that lands we can use it directly, maybe with a `resolutions` override since we depend on `source-map-loader` which depends on `source-map-js`. If there's a delay in landing the patch I'll see about pointing at a fork, or maybe a tiny local webpack plugin to preprocess the CLJS source maps so they don't trigger the issue.

For the sake of this P1, I'm going to timebox perhaps 2h this afternoon to do a mix of debugging somewhat blindly in stats, and eyeballing the `lib.column-groups` code with these inputs to see if I can spot the problem.

**Closed** 2024-01-15 21:41 UTC
Labels: Type:Bug, Priority:P1, .Regression/master, .metabase-lib, .Team/QueryProcessor
