### ISSUE TITLE
Time conversion is not consistent

### ISSUE THREAD

**Issue by watollop** [metabase/metabase#15958] opened 2021-05-07 11:10 UTC
**Describe the bug**
When using a SQL question and converting to time(), sometimes the conversion is OK, others are one hour less.

As you can see in the screenshot,  both dates are 2021-05-07TXXXXXXXXX

Row 2 "04:41:55.72475+01:00" is converted to 4:41 which's OK. 
Row 3 "04:42:23.977445+01:00" is converted to 3:42 which is not ok.

**Logs**
` ["19:12:31.482685+01:00", "customer_order_routed", "2021-05-06T21:12:31.482+02:00", 8294096, "18",…]
1: ["04:40:14.805926+01:00", "picking_operation_finished", "2021-05-07T06:40:14.805+02:00", 8294096, null,…]
2: ["04:41:55.72475+01:00", "picking_operation_finished", "2021-05-07T06:41:55.724+02:00", 8294096, null,…]
3: ["04:42:23.977445+01:00", "picking_operation_finished", "2021-05-07T06:42:23.977+02:00", 8294096, null,…]
4: ["04:43:16.062405+01:00", "picking_operation_finished", "2021-05-07T06:43:16.062+02:00", 8294096, null,…]
`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to wright custom SQL from bigquery
2. Convert timestamp to Time

**Expected behaviour**
All conversion hours are converted properly

**Screenshots**
<img width="1771" alt="Captura de pantalla 2021-05-07 a las 12 57 45" src="https://user-images.githubusercontent.com/10385633/117440517-6f930b80-af34-11eb-87aa-e4cb560ce85c.png">

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "es-ES",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.19.112+",
    "user.language": "en",
    "user.timezone": "Europe/Madrid"
  },
  "metabase-info": {
    "databases": [
      "oracle",
      "postgres",
      "bigquery",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.21"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-27",
      "tag": "v0.39.1",
      "branch": "release-x.39.x",
      "hash": "6beba48"
    },
    "settings": {
      "report-timezone": "Europe/Madrid"
    }
  }
}
```

**Severity**
High, we had reverted to 37.2 our previous version, as reports are not consistent.

**Additional context**

**Comment by flamber** [comment] 2021-05-07 11:34
Duplicate of #15876

**Closed by flamber** 2021-05-07 11:34 UTC
Labels: .Needs Triage, Type:Bug
