### ISSUE TITLE
Tooltips and axis labels should always show the DISPLAY label

### ISSUE THREAD

**Issue by Sire** [metabase/metabase#14862] opened 2021-02-17 10:18 UTC
**Describe the bug**
Tooltips don't always show the display label, often it's changed to the database column name.  
The problem with this is that the database column names are often abbreviated, use technical terms or is otherwise not named with the end-user in mind.
The correct display label is shown when hovering over that exact line, but never for the other data points. The fact that tooltip labels change depending on where you hover only add to the confusion.

See image below. The display label is "Sales", the DB column is "TOTAL".
What is shown in the tooltip: "Sum of TOTAL" (the DB column name).
What I expected in the tooltip: "Sales" (or possibly "Sum of Sales" if you feel it's important to show the aggregation).
Same with axis labels. I set it to "Date", but it's still showing up as "CREATED_AT". 

![image](https://user-images.githubusercontent.com/205954/108189364-edebc880-7110-11eb-905f-b906f1f63494.png)

**To Reproduce**
1. Summarize the ORDERS table on Sum of TOTAL and Sum of QUANTITY, group by CREATED_AT
2. Set display names.
2. See tooltips.

**Information about your Metabase Installation:**

Metabase version: 0.37.9
(I see 0.38.0 was just released but the changelog doesn't mention tooltips)

**Severity**

It's very confusing for users to understand the tooltips currently. We would like to turn them off until this is resolved.

Possibly related to #9407.

Thanks for an otherwise FANTASTIC software 😃

**Comment by flamber** [comment] 2021-02-17 10:55
Looks like a duplicate of #11395
The axis labes can be changed separately from the anything else in visualization Settings > Labels.

**Closed by flamber** 2021-02-17 10:55 UTC
Labels: .Needs Triage, Type:Bug
