### ISSUE TITLE
Question save issue

### ISSUE THREAD

**Issue by TLazarevic** [metabase/metabase#34480] opened 2023-10-09 07:15 UTC
### Describe the bug

'Save question' modal for saving questions after editing has an issue on 'Save' click.

### To Reproduce

1. Go to a native question
2. Edit the question SQL
3. Click on the 'Save' button in the upper right corner of the editor
4. Modal pops up
5. Click 'Save'
6. See error directly on modal

### Expected behavior

Question gets saved, modal closes

### Logs

<img width="633" alt="Screenshot 2023-10-09 at 09 05 53" src="https://github.com/metabase/metabase/assets/18078190/d85e9625-bcb7-4645-b52b-8580a92b08be">

Brave browsers' issues view:
<img width="1149" alt="Screenshot 2023-10-09 at 09 06 12" src="https://github.com/metabase/metabase/assets/18078190/edec7d8e-24e6-4852-b9c9-1001fdf9434b">
<img width="1423" alt="Screenshot 2023-10-09 at 09 13 59" src="https://github.com/metabase/metabase/assets/18078190/c7a4c88a-8c05-4c8d-94cd-8ab21b9ff213">

### Information about your Metabase installation

```JSON
- Metabase version v0.47.3
- Brave browser version 1.58.127 Chromium: 117.0.5938.88 (Official Build) (arm64)
```

### Severity

Not sure

**Comment by paoliniluis** [comment] 2023-10-09 17:37
Are you running Metabase behind a CDN?

**Comment by TLazarevic** [comment] 2023-10-09 22:09
> Are you running Metabase behind a CDN?

No

**Comment by uladzimirdev** [comment] 2023-10-10 15:08
@TLazarevic we need more details as I can't reproduce the issue on 0.47.3.

https://www.loom.com/share/9f290bacfcc04bf88988ab002b7b0954?sid=dc2440a3-b7dc-4c6b-8287-5b6cf2668bab

**Comment by TLazarevic** [comment] 2023-10-17 20:35
@uladzimirdev 

For more info:
I had a native query question with a Pie visualization, I added an additional condition to a CTE in the query, and when I tried replacing the question the issue occurred. It only happens on occasion, I barely managed to reproduce it with multiple failed attempts. 

More console logs:

Uncaught TypeError: Cannot read properties of null (reading 'offsetHeight')
    at s.value (NativeQueryEditor.jsx:451:29)
    at s.value (NativeQueryEditor.jsx:466:12)
    at c (debounce.js:17:37)


Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at react-dom.production.min.js:50:151
    at it (react-dom.production.min.js:50:217)
    at t.findDOMNode (react-dom.production.min.js:289:336)
    at m.value (ExplicitSize.jsx:45:25)
    at ExplicitSize.jsx:133:30
    at h (index.js:160:19)
    at v (index.js:207:14)
    at y (index.js:195:14)
    
 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'ordered_cards')
    at data-fetching.js:499:47
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:293:22)
    at Generator.next (runtime.js:118:21)
    at ln (metadata.js:35:12)
    at a (metadata.js:35:12)
    at metadata.js:35:12
    at new Promise (<anonymous>)
    at metadata.js:35:12
    at data-fetching.js:498:3
    
Warning: can't clean query without metadata!
value @ StructuredQuery.ts:368

It also seems that the question is still saved even with the error.

Can I assist more somehow?

**Comment by uladzimirdev** [comment] 2023-10-18 12:59
@TLazarevic thanks, actually we have a fix for this issue already. As a workaround, after saving the dashboard, please, reload the page before editing questions.

**Comment by uladzimirdev** [comment] 2023-10-18 13:00
duplication of https://github.com/metabase/metabase/issues/31766

**Closed by uladzimirdev** 2023-10-18 13:00 UTC
Labels: Type:Bug, .Team/42, .FixScope42
