### ISSUE TITLE
Multiple sum aggregations for Druid

### ISSUE THREAD

**Issue by RuslanTaran** [metabase/metabase#7195] opened 2018-03-24 11:39 UTC
### Description
Adding multiple sum aggregators with Druid backend leads to query failure.
It seems that this is an issue with the Druid query builder.

### The setup

- Client browser and the version: Chrome 65.0.3325.146 (Official Build) (64-bit)
- Client operating system: macOS Sierra 10.12.6 (12G1212)
- Database: Druid v0.10.0: https://github.com/druid-io/druid/tree/druid-0.10.0
- Metabase version: 0.28.2
- Metabase hosting environment: Docker
- Metabase internal database: MariaDB 5.5.52 for Linux (x86_64)

### Reproduce the issue as follows:

-  First metric:
<img width="698" alt="screen shot 2018-03-24 at 12 23 21" src="https://user-images.githubusercontent.com/2749783/37863518-77fb9cae-2f5f-11e8-927a-ee6017709dd5.png">

- Second metric:
<img width="671" alt="screen shot 2018-03-24 at 12 23 40" src="https://user-images.githubusercontent.com/2749783/37863517-77dd8eb2-2f5f-11e8-97f5-f7d252f3d73d.png">

- Both metrics:
<img width="743" alt="screen shot 2018-03-24 at 12 24 25" src="https://user-images.githubusercontent.com/2749783/37863516-77bbc64c-2f5f-11e8-8ce8-1d8b3ea3a484.png">
- Checking the metabase query log we can see that the following query has failed:

```
{:type "query",
:query {:source_table 111, :aggregation [["sum" ["field-id" 1092]] ["sum" ["field-id" 1094]]]},
:parameters [],
:constraints {:max-results 10000, :max-results-bare-rows 2000},
:info
{:executed-by 83,
:context :ad-hoc,
:card-id nil,
:nested? false,
:query-hash [13, -73, -47, 98, -104, -96, 80, 81, -35, -28, 85, 115, -11, -126, -23, -20, -113, -39, 33, 119, 102, -114, 48, 11, 113, -119, -99, 32, 121, -8, 71, 112],
:query-type "MBQL"}}
```

- It seems that there is a collision in the aggregated fields as both are called "sum".

**Comment by camsaul** [comment] 2018-11-20 21:39
Duplicate of #4166

**Closed by camsaul** 2018-11-20 21:39 UTC
Labels: Bug, Database/Druid, Priority/P2, Query Builder
