### ISSUE TITLE
'View these x' action doesn't work for questions with joined data 

### ISSUE THREAD

**Issue by jona-sc** [metabase/metabase#11015] opened 2019-09-30 06:56 UTC
**Describe the bug**

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.x. OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by flamber** [comment] 2019-09-30 15:22
Hi @jona-sc 
When creating an issue, please fill out the template, so we can better help you.
It sounds like you're seeing issue #10871 - if you agree, then please close this issue.

**Comment by mazameli** [comment] 2019-09-30 17:38
Closing as duplicate of #10871

**Closed by mazameli** 2019-09-30 17:38 UTC
Labels: Duplicate, Type:Bug

**Comment by jona-sc** [comment] 2019-10-01 01:26
@flamber strange, I had written a full description but it was somehow reset to the original template. Yes that appears to be duplicate. Thanks.
