### ISSUE TITLE
Invalid download in safari browser

### ISSUE THREAD

**Issue by MeiJunNa** [metabase/metabase#9536] opened 2019-03-11 02:29 UTC
![image](https://user-images.githubusercontent.com/30679487/54096777-40ca8a80-43e8-11e9-9e68-419aa47b6380.png)
The chrome browser can download normally, but it does not work in safari. I do not know why.

**Comment by flamber** [comment] 2019-03-11 02:43
Hi @MeiJunNa 
Please fill in all the requested information (Metabase and OS/browser version) and do you see anything in browser console (if Safari even has such thing)?

**Comment by MeiJunNa** [comment] 2019-03-11 02:59
> Hi @MeiJunNa
> Please fill in all the requested information (Metabase and OS/browser version) and do you see anything in browser console (if Safari even has such thing)?
Thank you very much for your reply
safari version is 12.0.3,Metabase on version v0.31.2
Sandbox access violation: Blocked a frame at "https://dash.siren8.com" from accessing a frame at Click File Download and the console will report the following error:
The frame being accessed is sandboxed and lacks the "allow-same-origin" flag.
in a frame because it set 'X-Frame-Options' to 'DENY'.

**Comment by MeiJunNa** [comment] 2019-03-11 03:02
Hi @flamber 
Thank you very much for your reply
safari version is 12.0.3,Metabase on version v0.31.2
console will report the following error:
1.The frame being accessed is sandboxed and lacks the "allow-same-origin" flag.
2.in a frame because it set 'X-Frame-Options' to 'DENY'.

**Comment by flamber** [comment] 2019-03-11 03:10
@MeiJunNa 
Okay, then it sounds like you're using embedded or maybe just using an iframe?
You should see the same errors in Chrome and Firefox.
Can you provide exact steps to reproduce this - including if you're embedding/iframing, etc. ?

**Comment by MeiJunNa** [comment] 2019-03-11 03:21
Hi@flamber 
The code, as shown below:
![image](https://user-images.githubusercontent.com/30679487/54098433-95253880-43ef-11e9-9ac4-f244fa86e432.png)
![image](https://user-images.githubusercontent.com/30679487/54098446-9e160a00-43ef-11e9-81a3-a13284cf056c.png)

**Comment by flamber** [comment] 2019-03-11 03:26
@MeiJunNa 
I don''t know what that means - that's your internal code.
If you're having problems with some headers, because you're implementing Metabase via iframe, then just remove or change the headers with a reverse proxy.

**Comment by MeiJunNa** [comment] 2019-03-11 03:29
Hi @flamber 
Ok, thank you very much for your reply.

**Comment by salsakran** [comment] 2019-04-10 04:25
Closing since anything you do with a reverse proxy is outside of the scope of Metabase itself.

**Closed by salsakran** 2019-04-10 04:25 UTC

**Comment by liran-co** [comment] 2019-09-03 16:30
I'm actually getting this same issue, using the basic embedding feature in Metabase (https://www.metabase.com/docs/latest/administration-guide/13-embedding.html). When clicking the download button on any card in Safari, it returns an error in the console that the 'X-Frame-Options' is set to 'DENY'. Chrome works fine.

**Comment by flamber** [comment] 2019-09-03 17:41
@liran-co 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Which version of Metabase?
Are you using a reverse-proxy? If not, then that might be your solution, since you can modify the headers, so it works with your setup.

**Comment by liran-co** [comment] 2019-09-03 18:09
I'm on v0.33.0. Just thought maybe it was a bug considering the download buttons are shown by default when embedding, so they should work if we're following the guide? If this does require a reverse-proxy to work, maybe there should be a note added to the guide or a switch we can flip to disable downloads?

**Comment by flamber** [comment] 2019-09-03 18:15
@liran-co 
Metabase doesn't require a reverse-proxy, but if your setup is advanced, then it might help you changing some headers to make it fit into your setup.
I would guess it has something to do with your (sub)domains and which domain Metabase is configured to.
But if Safari is the only browser failing, then perhaps the issue is with that browser?
Can you provide steps to reproduce the issue?

**Comment by devstein** [comment] 2020-09-07 23:27
@liran-co @flamber What was the solution here? We are facing the same issue on Safari because Metabase is returning the following CSP 

```
Content-Security-Policy: default-src 'none'; script-src 'self' 'unsafe-eval' https://maps.google.com https://apis.google.com https://www.google-analytics.com https://*.googleapis.com *.gstatic.com 'sha256-lMAh4yjVuDkQ9NqkK4H+YHUga+anpFs5JAuj/uZh0Rs=' 'sha256-sMNbXyc1lLzhHbH/CKs11HIQMnMkZAN2eA99WhJeEC0=' 'sha256-JJa56hyDfUbgNfq+0nq6Qs866JKgZ/+qCq2pkDJED8k='; child-src 'self' https://accounts.google.com; style-src 'self' 'unsafe-inline'; font-src 'self' ; img-src * 'self' data:; connect-src 'self' metabase.us10.list-manage.com ; manifest-src 'self'; frame-ancestors 'none';
```

Note the `frame-ancestors 'none'`.

The error in Safari's console is

```
Refused to load https://metabase.our.internal.domain/api/embed/dashboard/*/dashcard/85/card/52/xlsx because it does not appear in the frame-ancestors directive of the Content Security Policy.
```

**Comment by flamber** [comment] 2020-09-08 09:43
@devstein Metabase doesn't set `frame-ancestors 'none'`, so that must be your proxy that does this.
