### ISSUE TITLE
Adding an additional table to the Permissions for a Group doesn't work

### ISSUE THREAD

**Issue by MathiasDL** [metabase/metabase#4000] opened 2016-12-26 12:53 UTC
I discovered an issue with the permissions. It seems that you cannot change table permissions for a group, *if* that group already has access to at least one table.

Workaround: remove all table permissions for that group, save, and add all permissions you want to add in 1 action.

- Browser and the version: Chrome 55
- Operating system: OS X
- Databases: MySQL
- Metabase version: 0.21.1
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

Steps to reproduce:
1. Create a new group (e.g. Test Group)
2. Go to Permissions
3. Give the Test Group limited Data Access
4. Assign at least one table to the Test Group
5. Save - this works
6. Go back to the Test Group, try to add another table
7. Save again. This time, the save button stays in place, and nothing is saved

**Comment by tlrobinson** [comment] 2016-12-28 20:35
I'm not able to reproduce this on v0.21.1. I did the following:

1. Created a new group, "New Group"
2. Went to /admin/permissions/databases. New group had no access to any databases.
3. Set "Data Access" for the "Sample Dataset" database to "Limit access" for "New Group"
4. It took me to the "Sample Dataset" tables permissions page, /admin/permissions/databases/1/schemas/PUBLIC/tables
5. Set "Data Access" for the "Orders" table and "New Group" group to "Grant unrestricted access"
6. Hit "Save changes" and "Yes" in the confirmation modal
7. Set "Data Access" for the "People" table and "New Group" group to "Grant unrestricted access"
8. Hit "Save changes" and "Yes" in the confirmation modal
9. Refreshed the page. It correctly shows "New Group" has access to "Orders" and "People" but not "Products" and "Reviews"

Did you do anything differently?

**Comment by camsaul** [comment] 2017-01-05 01:53
@MathiasDL ?

**Comment by camsaul** [comment] 2017-01-09 17:41
@MathiasDL ?

**Comment by MathiasDL** [comment] 2017-01-25 11:33
I did the same tests as you describe. I also upgrade to 0.22.0, and tested on that version.

I installed it on my Mac and it works fine for both H2 and MySQL databases. 

On our server, it still doesn't work, I tested with Chrome and Safari, and on a MySQL database, as well as the H2 test database.

I hit the error already at step 6. The log is below.

```
Jan 25 11:29:28 DEBUG metabase.models.permissions :: Changing permissions: 🔏
FROM:
{8 {3 {:schemas :none}}, 5 {2 {:schemas {nil {7 :none, 13 :all, 6 :none, 12 :all, 11 :none, 9 :none, 5 :none, 10 :none, 8 :none}}}}}

TO:
{8 {3 {:schemas {"PUBLIC" {14 :all, 15 :none, 16 :none, 17 :none}}}}, 5 {2 {:schemas {"" {7 :none, 13 :all, 6 :none, 12 :all, 11 :none, 9 :none, 5 :none, 10 :none, 8 :none}}}}}


Jan 25 11:29:28 DEBUG metabase.models.permissions :: Granting permissions for group 8: /db/3/schema/PUBLIC/table/14/
Jan 25 11:29:28 DEBUG metabase.models.permissions :: Granting permissions for group 8: /db/3/schema/PUBLIC/table/14/
Jan 25 11:29:28 DEBUG metabase.models.permissions :: Granting permissions for group 5: /db/2/schema//table/13/
Jan 25 11:29:28 DEBUG metabase.models.permissions :: Granting permissions for group 5: /db/2/schema//table/13/
Jan 25 11:29:28 ERROR metabase.models.permissions :: Failed to grant permissions: ERROR: duplicate key value violates unique constraint "permissions_group_id_object_key"
Detail: Key (group_id, object)=(5, /db/2/schema//table/13/) already exists.
Jan 25 11:29:28 ERROR metabase.middleware :: PUT /api/permissions/graph 500 (105 ms) (10 DB calls)
{:message "ERROR: current transaction is aborted, commands ignored until end of transaction block",
:stacktrace
["db$query.invokeStatic(db.clj:525)"
"db$query.doInvoke(db.clj:521)"
"db$simple_select.invokeStatic(db.clj:575)"
"db$simple_select.invoke(db.clj:567)"
"db$select.invokeStatic(db.clj:819)"
"db$select.doInvoke(db.clj:813)"
"db$select_field.invokeStatic(db.clj:830)"
"db$select_field.doInvoke(db.clj:823)"
"models.permissions$delete_related_permissions_BANG_.invokeStatic(permissions.clj:323)"
"models.permissions$delete_related_permissions_BANG_.doInvoke(permissions.clj:310)"
"models.permissions$revoke_permissions_BANG_.invokeStatic(permissions.clj:330)"
"models.permissions$revoke_permissions_BANG_.doInvoke(permissions.clj:327)"
"models.permissions$fn__15770$update_table_perms_BANG___15775$fn__15776.invoke(permissions.clj:405)"
"models.permissions$fn__15770$update_table_perms_BANG___15775.invoke(permissions.clj:402)"
"models.permissions$fn__15797$update_schema_perms_BANG___15802$fn__15803.invoke(permissions.clj:413)"
"models.permissions$fn__15797$update_schema_perms_BANG___15802.invoke(permissions.clj:407)"
"models.permissions$fn__15856$update_db_permissions_BANG___15861$fn__15862.invoke(permissions.clj:438)"
"models.permissions$fn__15856$update_db_permissions_BANG___15861.invoke(permissions.clj:429)"
"models.permissions$fn__15888$update_group_permissions_BANG___15893$fn__15894.invoke(permissions.clj:442)"
"models.permissions$fn__15888$update_group_permissions_BANG___15893.invoke(permissions.clj:440)"
"models.permissions$fn__15928$update_graph_BANG___15937$fn__15938$fn__15940.invoke(permissions.clj:486)"
"db$do_in_transaction$fn__7763.invoke(db.clj:301)"
"db$do_in_transaction.invokeStatic(db.clj:299)"
"db$do_in_transaction.invoke(db.clj:296)"
"models.permissions$fn__15928$update_graph_BANG___15937$fn__15938.invoke(permissions.clj:484)"
"models.permissions$fn__15928$update_graph_BANG___15937.invoke(permissions.clj:473)"
"api.permissions$fn__30671$fn__30673.invoke(permissions.clj:72)"
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:222)"
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:219)"
"api.permissions$fn__30671.invokeStatic(permissions.clj:60)"
"api.permissions$fn__30671.invoke(permissions.clj:60)"
"middleware$enforce_authentication$fn__31489.invoke(middleware.clj:84)"
"api.routes$fn__31615.invokeStatic(routes.clj:56)"
"api.routes$fn__31615.invoke(routes.clj:56)"
"routes$fn__32587.invokeStatic(routes.clj:24)"
"routes$fn__32587.invoke(routes.clj:24)"
"middleware$log_api_call$fn__31577$fn__31579.invoke(middleware.clj:275)"
"db$_do_with_call_counting.invokeStatic(db.clj:461)"
"db$_do_with_call_counting.invoke(db.clj:455)"
"middleware$log_api_call$fn__31577.invoke(middleware.clj:274)"
"middleware$add_security_headers$fn__31536.invoke(middleware.clj:209)"
"middleware$bind_current_user$fn__31493.invoke(middleware.clj:104)"],
:sql-exception-chain ["PSQLException:" "Message: ERROR: current transaction is aborted, commands ignored until end of transaction block" "SQLState: 25P02" "Error Code: 0"]}

```

**Comment by MathiasDL** [comment] 2017-01-31 14:38
Do you need additional information?

This bug is starting to be very annoying as I add more groups and users. I am unable to give a group access to a subset of the tables, without first disabling the access of all other groups that have access to a subset of the tables. So as I add more groups, I need to set the permissions again and again in a single operation.

Other than that, looking great! The permissions on Collections are a nice addition to keep things organized.

**Comment by mazameli** [comment] 2017-01-31 19:01
I _was_ able to reproduce this on 0.22.2

With just the Sample Dataset as the only DB:
1. Create a test group.
2. Create a test user and assign it to the test group (and only that group)
3. Revoke all data access from the All Users group.
4. Set the test group's access to Limited
5. Revoke access to all tables within the sample dataset except for one for the Test Group.
6. Save changes.
7. Navigate way from Permissions and then go back to it.
8. Click on View Tables and grant the Test Group access to another table.
9. Attempt to save changes and observe that the changes are not saved or committed.

**Comment by camsaul** [comment] 2017-01-31 19:03
@mazameli thanks I'll get started on a fix

**Comment by tlrobinson** [comment] 2017-01-31 19:06
In addition to the backend issue, we also aren't surfacing API errors on the frontend, which we should do.

**Comment by camsaul** [comment] 2017-02-01 00:51
@mazameli I just followed those steps exactly and didn't run into any issues :/

**Comment by camsaul** [comment] 2017-02-01 00:51
![screen shot 2017-01-31 at 4 51 29 pm](https://cloud.githubusercontent.com/assets/1455846/22491027/8964a4f4-e7d5-11e6-9797-309654642aba.png)

here's my two tables :D

**Comment by camsaul** [comment] 2017-02-01 00:53
@mazameli can you include the server logs from when you went through those steps?

**Comment by camsaul** [comment] 2017-02-01 00:54
e.g. my logs were

```
01-31 16:50:00 DEBUG models.permissions :: Changing permissions: 🔏
FROM:
{127 {1 {:schemas :none}}, 1 {1 {:schemas :all, :native :write}}}

TO:
{127 {1 {:schemas {"PUBLIC" {1 :all, 2 :none, 3 :none, 4 :none}}}}, 1 {1 {:schemas :none, :native :none}}}
```

and 

```
01-31 16:50:30 DEBUG models.permissions :: Changing permissions: 🔏
FROM:
{127 {1 {:schemas {"PUBLIC" {2 :none}}}}}

TO:
{127 {1 {:schemas {"PUBLIC" {2 :all}}}}}
```

**Comment by camsaul** [comment] 2017-02-01 01:19
Actually I think I see what the issue might be here.

```
DEBUG metabase.models.permissions :: Changing permissions: 🔏
FROM:
{5 {2 {:schemas {nil {7 :none, 13 :all, 6 :none, 12 :all, ...}}}}}

TO:
{5 {2 {:schemas {"" {7 :none, 13 :all, 6 :none, 12 :all, ...}}}}}
```

At some point the schema is getting changed from `nil` to an empty string

**Comment by camsaul** [comment] 2017-02-01 01:22
Ok, I was able to repro this 😬

**Closed** 2017-02-01 01:52 UTC
Labels: API, Bug, Permissions
