### ISSUE TITLE
On a dashboard with multiple tabs, allow filters for just the specific tab

### ISSUE THREAD

**Issue by aarthi-subramanian** [metabase/metabase#42809] opened 2024-05-17 00:44 UTC
**Is your feature request related to a problem? Please describe.**
Me and my team are high users of the metabase dashboard with tabs. However, one big problem is that when we add a dashboard-level filter, we only want this filter to apply to ONE tab. It apples to all tabs :(

**Describe the solution you'd like**
If you add a dashboard-level filter to a dash with multiple tabs, have an option to apply this filter to ALL tabs or just the one tab.

**Describe alternatives you've considered**
I can add individual filters for the charts but this isnt helpful here

**How important is this feature to you?**
Very important for usability, self-service for stakeholders

**Additional context**

**Comment by paoliniluis** [comment] 2024-05-17 16:22
If you don't connect the filter to any card on the tab, then the filter will dissapear from there, have you checked this?

**Comment by aarthi-subramanian** [comment] 2024-05-17 18:51
Ya. I want different filters for different tabs. E.g. `transaction_count_threshold` filter where default is 1000 for tab1, default is 100 for tab 2, default is 100000 for tab3

**Comment by aarthi-subramanian** [comment] 2024-05-21 18:06
Oh wow yes that's what i want! Sorry how can i see which version im on?

**Comment by aarthi-subramanian** [comment] 2024-05-21 20:07
Ah this is my version. Ill ask my data eng team if we can upgrade to 49 🙏 
<img width="487" alt="image" src="https://github.com/metabase/metabase/assets/47357846/7ab55250-c6da-4349-9ad7-9a0a65ed87b6">

**Comment by ignacio-mb** [comment] 2024-06-04 14:55
Closing as this is possible from version 49, and dupe of https://github.com/metabase/metabase/issues/31621

**Closed** 2024-06-04 14:55 UTC
Labels: Type:New Feature, .Needs Triage
