### ISSUE TITLE
Mac "Check for updates..." error

### ISSUE THREAD

**Issue by maximepvrt** [metabase/metabase#13057] opened 2020-08-03 14:08 UTC
I did the last update, but it's not the new installed version is not the last

![Capture d’écran 2020-08-03 à 16 04 36](https://user-images.githubusercontent.com/1840026/89191662-8b334500-d5a3-11ea-81f0-9d4162daf593.png)

**Comment by flamber** [comment] 2020-08-03 14:14
Duplicate of #11336

**Closed by flamber** 2020-08-03 14:14 UTC
Labels: .Needs Triage, Type:Bug
