### ISSUE TITLE
Filter in embedding does not work properly

### ISSUE THREAD

**Issue by nakazavva** [metabase/metabase#4832] opened 2017-04-21 07:49 UTC
* Metabase version: 0.23.1
* Metabase hosting environment: Docker
* Metabase internal database: H2

When remove filter which is set, embed application seems to call the api wrongly. Look at the attachment below. I think the last api call should be ```/38```, not ```/38?category= ```

![screencast 2017-04-21 16-35-17](https://cloud.githubusercontent.com/assets/15145442/25267921/b3f08150-26b1-11e7-853f-5a3dda8dd116.gif)

**Comment by salsakran** [comment] 2017-04-24 18:16
think this is a dupe of #4653

**Comment by salsakran** [comment] 2017-04-24 18:37
if this is a dupe, #4715 should fix this as well.

**Comment by nakazavva** [comment] 2017-04-25 01:53
Not sure if this is same.

Embed application calls ```http://{host}/api/embed/dashboard/{JWT}/dashcard/70/card/38?category=```
then the server logs says:

```
Apr 25 01:43:32 WARN metabase.query-processor :: {:status :failed,
:class clojure.lang.ExceptionInfo,
:error "Valid value (must be nil, boolean, number, string, or a relative-datetime form)",
:stacktrace
["query_processor.expand$fn__21998$value__22003.invoke(expand.clj:88)"
"query_processor.expand$fn__22022$field_or_value__22027$fn__22028.invoke(expand.clj:101)"
"query_processor.expand$fn__22022$field_or_value__22027.invoke(expand.clj:95)"
"query_processor.expand$fn__22347$equality_filter__22356$fn__22357.invoke(expand.clj:219)"
"query_processor.expand$fn__22347$equality_filter__22356.invoke(expand.clj:217)"
"query_processor.expand$fn__22792$expand_ql_sexpr__22797$fn__22801.invoke(expand.clj:460)"
"query_processor.expand$fn__22792$expand_ql_sexpr__22797.invoke(expand.clj:452)"
"query_processor.expand$walk_expand_ql_sexprs.invokeStatic(expand.clj:468)"
"query_processor.expand$walk_expand_ql_sexprs.invoke(expand.clj:463)"
"query_processor.expand$walk_expand_ql_sexprs.invokeStatic(expand.clj:468)"
"query_processor.expand$walk_expand_ql_sexprs.invoke(expand.clj:463)"
"query_processor.expand$fn__22837$expand_inner__22842$fn__22843.invoke(expand.clj:476)"
"query_processor.expand$fn__22837$expand_inner__22842.invoke(expand.clj:472)"
"query_processor.expand$expand.invokeStatic(expand.clj:501)"
"query_processor.expand$expand.invoke(expand.clj:487)"
"query_processor.middleware.expand_resolve$expand_resolve_STAR_.invokeStatic(expand_resolve.clj:21)"
"query_processor.middleware.expand_resolve$expand_resolve_STAR_.invoke(expand_resolve.clj:16)"
"query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__21475.invoke(add_row_count_and_status.clj:14)"
"query_processor.middleware.driver_specific$process_query_in_context$fn__22980.invoke(driver_specific.clj:12)"
"query_processor.middleware.resolve_driver$resolve_driver$fn__24066.invoke(resolve_driver.clj:14)"
"query_processor.middleware.catch_exceptions$catch_exceptions$fn__22902.invoke(catch_exceptions.clj:51)"
"query_processor$process_query.invokeStatic(query_processor.clj:64)"
"query_processor$process_query.invoke(query_processor.clj:59)"
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:180)"
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:175)"
"query_processor$fn__24097$dataset_query__24102$fn__24103.invoke(query_processor.clj:212)"
"query_processor$fn__24097$dataset_query__24102.invoke(query_processor.clj:199)"
"api.card$run_query_for_card.invokeStatic(card.clj:373)"
"api.card$run_query_for_card.doInvoke(card.clj:357)"
"api.public$run_query_for_card_with_id$fn__26711.invoke(public.clj:59)"
"api.public$run_query_for_card_with_id.invokeStatic(public.clj:57)"
"api.public$run_query_for_card_with_id.doInvoke(public.clj:53)"
"api.public$public_dashcard_results.invokeStatic(public.clj:181)"
"api.public$public_dashcard_results.doInvoke(public.clj:169)"
"api.embed$dashcard_results.invokeStatic(embed.clj:220)"
"api.embed$dashcard_results.doInvoke(embed.clj:213)"
"api.embed$fn__27061$fn__27062.invoke(embed.clj:317)"
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:228)"
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:224)"
"api.embed$fn__27061.invokeStatic(embed.clj:304)"
"api.embed$fn__27061.invoke(embed.clj:304)"
"middleware$message_only_exceptions$fn__34693.invoke(middleware.clj:356)"
"api.routes$fn__34712.invokeStatic(routes.clj:59)"
"api.routes$fn__34712.invoke(routes.clj:59)"
"routes$fn__35781$fn__35782.doInvoke(routes.clj:53)"
"routes$fn__35781.invokeStatic(routes.clj:49)"
"routes$fn__35781.invoke(routes.clj:49)"
"middleware$log_api_call$fn__34681$fn__34683.invoke(middleware.clj:331)"
"middleware$log_api_call$fn__34681.invoke(middleware.clj:330)"
"middleware$add_security_headers$fn__34631.invoke(middleware.clj:245)"
"middleware$bind_current_user$fn__34586.invoke(middleware.clj:138)"
"middleware$maybe_set_site_url$fn__34635.invoke(middleware.clj:268)"],
:query
{:type "query",
:query
{:source_table 83,
:aggregation [["sum" ["field-id" 784]]],
:filter ["AND" ["SEGMENT" 8] ["time-interval" ["field-id" 1073] -36 "month"]],
:breakout [["datetime-field" ["field-id" 1073] "as" "month"]]},
:parameters ({:type "category", :target ["dimension" ["field-id" 1078]], :value ""}),
:constraints {:max-results 10000, :max-results-bare-rows 2000},
:info
{:executed-by 1,
:context :embedded-dashboard,
:card-id 38,
:dashboard-id 4,
:query-hash [-39, 23, 18, 81, 38, 83, 5, 22, 80, -36, -70, -16, -30, 10, 80, 127, 23, 55, -59, 4, -119, -22, 55, 127, -50, 123, 114, -102, 36, -101, 3, 65],
:query-type "MBQL"}},
:expanded-query nil,
:ex-data
{:type :schema.core/error,
:schema metabase.query_processor.interface.ValuePlaceholder,
:value {:field-placeholder {:field-id 1078, :fk-field-id nil, :datetime-unit nil}, :value ""},
:error {:value (named (not ("Non-blank string" "")) "Valid value (must be nil, boolean, number, string, or a relative-datetime form)")}}}

Apr 25 01:43:32 WARN metabase.query-processor :: Query failure: Valid value (must be nil, boolean, number, string, or a relative-datetime form)
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:149)"
"query_processor$assert_query_status_successful.invoke(query_processor.clj:142)"
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:181)"
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:175)"
"query_processor$fn__24097$dataset_query__24102$fn__24103.invoke(query_processor.clj:212)"
"query_processor$fn__24097$dataset_query__24102.invoke(query_processor.clj:199)"
"api.card$run_query_for_card.invokeStatic(card.clj:373)"
"api.card$run_query_for_card.doInvoke(card.clj:357)"
"api.public$run_query_for_card_with_id$fn__26711.invoke(public.clj:59)"
"api.public$run_query_for_card_with_id.invokeStatic(public.clj:57)"
"api.public$run_query_for_card_with_id.doInvoke(public.clj:53)"
"api.public$public_dashcard_results.invokeStatic(public.clj:181)"
"api.public$public_dashcard_results.doInvoke(public.clj:169)"
"api.embed$dashcard_results.invokeStatic(embed.clj:220)"
"api.embed$dashcard_results.doInvoke(embed.clj:213)"
"api.embed$fn__27061$fn__27062.invoke(embed.clj:317)"
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:228)"
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:224)"
"api.embed$fn__27061.invokeStatic(embed.clj:304)"
"api.embed$fn__27061.invoke(embed.clj:304)"
"middleware$message_only_exceptions$fn__34693.invoke(middleware.clj:356)"
"api.routes$fn__34712.invokeStatic(routes.clj:59)"
"api.routes$fn__34712.invoke(routes.clj:59)"
"routes$fn__35781$fn__35782.doInvoke(routes.clj:53)"
"routes$fn__35781.invokeStatic(routes.clj:49)"
"routes$fn__35781.invoke(routes.clj:49)"
"middleware$log_api_call$fn__34681$fn__34683.invoke(middleware.clj:331)"
"middleware$log_api_call$fn__34681.invoke(middleware.clj:330)"
"middleware$add_security_headers$fn__34631.invoke(middleware.clj:245)"
"middleware$bind_current_user$fn__34586.invoke(middleware.clj:138)"
"middleware$maybe_set_site_url$fn__34635.invoke(middleware.clj:268)"]

Apr 25 01:43:32 DEBUG metabase.middleware :: GET /api/embed/dashboard/{JWT}/dashcard/70/card/38 400 (286 ms) (9 DB calls)
"An error occurred while running the query."

**Comment by attekei** [comment] 2017-05-10 17:52
I'm unable to reproduce in 0.24. The `category` query string is in the query url only if the category filter is active so it seems that this issue has been fixed.

![screen shot 2017-05-10 at 10 44 22](https://cloud.githubusercontent.com/assets/6034928/25913066/51464c80-356e-11e7-8a39-e87d0f43a595.png)

**Closed by attekei** 2017-05-10 17:52 UTC
Labels: Bug, Embedding, Parameters/Variables, Priority/P2
