### ISSUE TITLE
Pulse image got stretched out after 33.0 upgrade

### ISSUE THREAD

**Issue by giovannibonetti** [metabase/metabase#10781] opened 2019-09-02 15:42 UTC
**Describe the bug**
After upgrading from 32.x to 33.0 the pulse images on Slack got stretched up. It seems like it changed from landscape to portrait orientation. Please see the screenshot below for more details. Is this an intentional change or is it a bug? Or is it a feature? 🤔 

**Logs**
I don't think it is relevant in this case.

**To Reproduce**
1. Create/view a pulse with a chart;
2. Trigger a Slack notification with it;
3. Look at the pulse image/chart on Slack.

**Expected behavior**
I expected the pulse image after the upgrade to look like it used to before the upgrade.

**Screenshots**
On August 30th we were using Metabase 32.x (can't recall the exact version, but the previous update was about 2-3 months earlier). After upgrading to 33.0 (with docker pull) we noticed the pulse images on Slack got way larger.

![Screenshot 2019-09-02 12 23 52](https://user-images.githubusercontent.com/3451581/64124782-5957a400-cd7e-11e9-9df5-3627347168a5.png)

**Information about your Metabase Installation:**
- Your browser and the version: Slack "native" client
- Your operating system: Mac OS Mojave
- Your databases: Postgres
- Metabase version: 33.0
- Metabase hosting environment: Docker container on Google Compute Engine
- Metabase internal database: also Postgres

**Severity**
Slightly annoying.

**Additional context**

**Comment by mazameli** [comment] 2019-09-02 17:26
Hmm, @walterl, do you think any of the recent pulse fixes might've changed the way these visualizations render in Slack?

**Comment by walterl** [comment] 2019-09-02 19:38
@mazameli The fix in #10650 _could_ have the side effect of previously ignored styles now being applied.

If that is what caused the height difference, the 0.32 pulse's PNG would've been rendered from generated HTML containing invalid CSS (one or more attributes without values).

**Comment by walterl** [comment] 2019-09-03 00:16
I tested on 0.32.10 (the last 0.32.x version), and it rendered a simple line graph into a square (540x540) PNG. So I haven't found anything promising so far.

@giovannibonetti Do you know which exact 0.32.x version of Metabase it was that produced the flat example?

**Comment by giovannibonetti** [comment] 2019-09-03 02:17
Hi, @walterl! Thanks for the response!
The previous docker image we run had the digest `sha256:f2279a60ce1d680cd1a345ba57238b2107e2a5ecadf507dbc25643a090e0b539`. Following [this procedure](https://stackoverflow.com/questions/41808763/how-to-determine-the-docker-image-id-for-a-tag-via-docker-hub-api#answer-41830007) we found out that it belongs to v32.8. So that's the previous version we were running here.

**Comment by sharedphysics** [comment] 2019-11-12 20:15
I have this same problem, running on 33.2 on AWS. Was not on issue on 32.x

**Comment by tsmacdonald** [comment] 2020-10-13 19:27
The issue is in [this refactoring commit](https://github.com/metabase/metabase/commit/71bbe9ce8e35be15d1fa1d450bc4d205d72aa3a5) (PR #10263), which changed the image dimensions from  524×130 to 524×524 (presumably that was just a transcription error).

It's unclear if this is bad behavior though. The way sparklines work is all of the values for an axis are normalized to a number between 0 and 1 (e.g., `normalized_x = (min_x + x) / (max_x - min_x)`) and then those points are plotted and connected by lines. Since the normalized range of both the x and y axes is now 1, it sort of makes sense to have a square chart.

Here are some examples; all of which are of the same data.

Square pulse:

![image](https://user-images.githubusercontent.com/784417/95906451-bf737080-0d5f-11eb-9982-e0f867bf75e5.png)


Rectangular pulse:

![image](https://user-images.githubusercontent.com/784417/95906474-c8644200-0d5f-11eb-894c-d7580992358b.png)


Question visualization:

![order-chart](https://user-images.githubusercontent.com/784417/95906597-f0ec3c00-0d5f-11eb-9093-bca44ce538b0.png)

In Google Sheets:

![ys vs  xs](https://user-images.githubusercontent.com/784417/95906687-124d2800-0d60-11eb-9f00-23cf50c90c5c.png)



@mazameli @kdoh Which aspect ratio do you prefer; square or rectangular?

**Comment by kdoh** [comment] 2020-10-13 22:07
Given that the original intention of the way we do those stripped down pulse charts was to make them easier to parse in a mobile context like an email I think square is probably fine until we do a more wholesale rework to modernize them and get more viz parity into what we send out.

**Comment by tsmacdonald** [comment] 2020-10-14 14:43
Thanks @kdoh! Should we close this issue?

**Closed** 2020-10-14 16:36 UTC
Labels: Priority:P3, Reporting/Pulses, Type:Bug
