### ISSUE TITLE
The BigInt field cannot be displayed normally, and the end will become 0

### ISSUE THREAD

**Issue by cyhhao** [metabase/metabase#11447] opened 2019-12-05 07:15 UTC
**Describe the bug**
The BigInt field cannot be displayed normally, and the end will become 0.Even if I set it manually as a string in the administrator's data model.
And also cannot enter BigInt numbers to filter from the table.

**Logs**
None.
Refer to the screenshot below.

**To Reproduce**
Query any table containing a field of BigInt
or
Enter BigInt numbers to filter from the table.

**Expected behavior**
Can view and filter bigint fields normally

**Screenshots**

metabase show :
![image](https://user-images.githubusercontent.com/5381613/70211533-5058e300-1770-11ea-80ea-ffdec3acd838.png)

metabase's console :
![image](https://user-images.githubusercontent.com/5381613/70211556-61a1ef80-1770-11ea-97eb-5466fe6cceb7.png)

Correct data is：
![image](https://user-images.githubusercontent.com/5381613/70211713-bba2b500-1770-11ea-9de2-dd813e229574.png)

Failed to enter the correct number, it will become the number ending with 0 :
![image](https://user-images.githubusercontent.com/5381613/70211914-3c61b100-1771-11ea-892c-54f162ddb5e0.png)

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "zh-CN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_222-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_222",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.222-b10",
    "os.name": "Linux",
    "os.version": "3.10.0-957.27.2.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.6",
      "date": "2019-11-19",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by flamber** [comment] 2019-12-05 13:57
Hi @cyhhao 
Looks like a duplicate of #5816. If you agree, then please close this and upvote the other issue :+1:

**Closed** 2019-12-05 22:43 UTC
Labels: .Duplicate
