### ISSUE TITLE
Need multiple databases while adding a mysql databases

### ISSUE THREAD

**Issue by sajiljosephs** [metabase/metabase#25747] opened 2022-10-03 07:52 UTC
**Is your feature request related to a problem? Please describe.**
Need multiple databases while adding a mysql databases

**Describe the solution you'd like**
Need multiple databases while adding a mysql databases

**Describe alternatives you've considered**
t have many connections configured is a mess. I have more than 1000 databases and I cannot configure 1000 connections

**How important is this feature to you?**
This is needed as soon as possible. This is very much required by most of the users. I will have to stop using it, if we dont have this feature

**Comment by flamber** [comment] 2022-10-03 07:57
Duplicate of #5887

**Closed by flamber** 2022-10-03 07:57 UTC
Labels: Type:New Feature, .Needs Triage
