### ISSUE TITLE
New collection saved inside "My personal collection" doesn't appear in "New collection" modal

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#14757] opened 2021-02-10 20:58 UTC
I created a collection called X and then started to create a new collection (Y). X should appear in the "Collection it's saved in" option but does not. Can be fixed with a refresh.

**Repro steps:**
- Create a new collection ("X")
- Save it inside "My personal collection"
- Create one more new collection ("Y")
- Click on a select menu to choose a collection to save it in
- Notice that "My personal collection" doesn't have "arrow right" icon - it's not possible to look inside and to choose "X" collection

![unnamed](https://user-images.githubusercontent.com/784417/107571238-43bfee00-6bb0-11eb-9af2-a5eb7ffd1b3e.png)

**Comment by flamber** [comment] 2021-02-10 21:01
Very related to referenced issues in https://github.com/metabase/metabase/issues/10330#issuecomment-610900593

**Comment by nemanjaglumac** [comment] 2021-02-19 17:57
I can't seem to get it fixed even with a (hard) refresh.

**Comment by nemanjaglumac** [comment] 2021-02-19 18:40
Also, it's important to note that this happens only for "My personal collection".

- If I create a new collection inside "Our analytics", I can see it in the "New collection" modal immediately. 
- If I create a new collection inside some collection that ALREADY has children, I can see it on a subsequent attempt in a "New collection" modal

**Comment by tsmacdonald** [comment] 2021-02-19 19:07
> I can't seem to get it fixed even with a (hard) refresh.

You're right, I can't repro this either. Sorry for the false alarm!

And yes, in my case it had to be within my personal collection, not as a top-level collection

**Comment by flamber** [comment] 2021-02-19 19:27
Isn't this a duplicate of #14122 ?

**Comment by nemanjaglumac** [comment] 2021-02-19 19:55
> Isn't this a duplicate of #14122 ?

Oopsy! It is but we didn't notice it on time. Additionally, I think the reason why is because repro for #14122 includes ONLY the steps for "Move collection" modal.

We can do two things now:
1. Leave this as it is and let this issue cover the step when you attempt to save new collection and let 14122 deal with moving it or
2. I can close this issue as a duplicate, revert the repro for it and update repro for 14122?

Your call @flamber

**Comment by flamber** [comment] 2021-02-19 19:57
@nemanjaglumac Simplify would be my preference - hence 2.

**Closed** 2021-02-19 20:03 UTC
Labels: .Reproduced, Organization/Collections, Priority:P3, Type:Bug
