### ISSUE TITLE
v0.51.0-beta Multiple groupings by same date field, labels are confusing

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#48591] opened 2024-10-10 20:54 UTC
### Describe the bug

Love this feature, I've been working around this for ages.

When I create a question with a summary by different granularity of the same datetime, the chart, and some settings, don't distinguish between these meaning you've got to guess which one is which.

### To Reproduce

1. New question on sample data > Orders
2. Count by "Create At: Hour of day" and "Created At: Day of week"
![Image](https://github.com/user-attachments/assets/a117734e-af7a-42eb-a5e4-b0c652aa7fe7)
3. Visulise > scatter chart
4. Open settings
5. Both date groupings are called "Created At" so you've got guess which is which
6. Both x and y axis on the chart are labelled "Created At"
![Image](https://github.com/user-attachments/assets/f0cdbc60-8371-459a-af4e-e8aa08e0fe2b)

### Expected behavior

I should be able to distinguish the different groupings both in the chart settings and the visualisation itself.

### Logs

NA

### Information about your Metabase installation

{
  "browser-info": {
    "language": "en-NZ",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-10-08",
      "tag": "v0.51.0-beta",
      "hash": "f69afc2"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    }
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.2+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.2+8",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  }
}

### Severity

Annoying, have to guess and manually relabel

### Additional context

This seems to apply across different visualisation types.

**Comment by mngr** [comment] 2024-10-16 14:36
Related to https://github.com/metabase/metabase/issues/47579 and https://github.com/metabase/metabase/issues/47576

**Comment by ranquild** [comment] 2024-10-18 01:11
Duplicate of https://github.com/metabase/metabase/issues/47579

**Closed by ranquild** 2024-10-18 01:11 UTC
Labels: Type:Bug, Priority:P2, Querying/Processor, .Backend, .Team/Querying, Bug:v51
