### ISSUE TITLE
Schema sync isn't updating field order

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#27310] opened 2022-12-16 22:10 UTC
**Describe the bug**
After moving fields and adding a new field, schema sync is only picking up the new field but field order remains the same -- even though field order is set to be based on database order. 

**Logs**
n/a

**To Reproduce**
1. Add a new field. Move some fields from beginning to end of list. 
2. Trigger schema sync
3. Browse to table. Only new field is added. Moved fields are still in the same old order. 

To fix the order, you would need to go to admin, change field order to alphabetical and then change back to database order. 

**Expected behavior**
After schema sync, it should update the database order of fields as well. 

**Screenshots**
n/a

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome
- Your operating system:  OS X
- Your databases: Postgres
- Metabase version: master
- Metabase hosting environment: Metabase Cloud
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
It's just annoying having to work around it by changing field order and then change back to database order. 

**Additional context**

**Comment by flamber** [comment] 2022-12-17 09:08
Duplicate of #13024/#19096

**Closed by flamber** 2022-12-17 09:08 UTC
Labels: Type:Bug, .Needs Triage
