### ISSUE TITLE
Issues with displaying CJK character in pulses over Slack

### ISSUE THREAD

**Issue by hden** [metabase/metabase#6395] opened 2017-11-15 01:46 UTC
Metabase version: 0.26.1 

Any tables with CJK character are currently being displayed as **tofu**.

<img width="375" alt="screen shot 2017-11-15 at 10 39 54" src="https://user-images.githubusercontent.com/1910549/32814306-d4c29cd6-c9f1-11e7-8311-98021ce75185.png">

Possible solution: change the rendering font to something that cares about i18n, e.g. [Google noto](https://www.google.com/get/noto/).

**Comment by camsaul** [comment] 2017-11-15 02:09
Duplicate of #2342

**Closed by camsaul** 2017-11-15 02:09 UTC
