### ISSUE TITLE
Unable to migrate from h2 to Postgres

### ISSUE THREAD

**Issue by roemhildtg** [metabase/metabase#9790] opened 2019-04-16 17:54 UTC
Running into this error:

![image](https://user-images.githubusercontent.com/5471079/56232431-574aae00-6046-11e9-9c19-9837d70879a7.png)

```
set MB_DB_TYPE=postgres
set MB_DB_DBNAME=metabase
set MB_DB_PORT=5432
set MB_DB_USER=postgres
set MB_DB_PASS=secret
set MB_DB_HOST=localhost
java -Xms1G -Xmx1G  -jar metabase.jar load-from-h2 ./metabase.db
```

- Your operating system: Windows Server 2016 x64
- Your databases: Postgres 11.2.2
- Metabase version: 0.32.4
- Metabase hosting environment: Java jar
- Metabase internal database: H2 -> Postgres

- *Repeatable steps to reproduce the issue*

Thanks for being part of the Metabase project!
-------

**Comment by flamber** [comment] 2019-04-16 19:34
Hi @roemhildtg This is most likely a duplicate of #9756

**Comment by camsaul** [comment] 2019-04-17 00:53
Duplicate of #9756

**Closed by camsaul** 2019-04-17 00:53 UTC
