### ISSUE TITLE
Be able to populate Databases list by conf

### ISSUE THREAD

**Issue by mmaryo** [metabase/metabase#21380] opened 2022-03-31 12:02 UTC
Hello 

I would like to be able to populate Database list `/admin/databases` by configuration file 

I could be loaded at startup, for example with Docker : 

`-e databases.configfile=/home/dbs-conf.yaml`

 And the conf could be 

- databases
    - name: users
      type: postgresql
      host: ...
      port: ...
   - name: products
      type: postgresql
      host: ...
      port: ...

The same for users will be nice 

I deploy Metabase with Terrform to ECS

**Comment by flamber** [comment] 2022-03-31 12:14
Duplicate of #17059
Already possible with Serialization: https://www.metabase.com/docs/latest/enterprise-guide/serialization.html

**Closed by flamber** 2022-03-31 12:14 UTC
Labels: Type:New Feature, .Needs Triage
