### ISSUE TITLE
Error on Sorting in Custom Questions: column "named" does not exist

### ISSUE THREAD

**Issue by PauloHFM** [metabase/metabase#10205] opened 2019-06-18 02:29 UTC
ERROR: column "named" does not exist Position: X

This happens to me EVERY time I try to order a "View" column (that I named in Custom Expression) in Custom Questions. 

Anyone knows?

![image](https://user-images.githubusercontent.com/38223133/59458373-b0d61b80-8df0-11e9-8111-30c4dc5ec755.png)

 ![image](https://user-images.githubusercontent.com/38223133/59458478-e418aa80-8df0-11e9-8ad0-b777f9e06451.png)

This issue is in all versions I've tried so far, currently using v0.32.8. 

Commented in 
https://github.com/metabase/metabase/issues/8621#issuecomment-501829587_

**Comment by flamber** [comment] 2019-06-18 02:51
Hi @PauloHFM 
Looks like you're seeing issue #6239, if you agree, then please close this issue :+1:

**Comment by mazameli** [comment] 2019-06-18 19:04
Closing as duplicate of #6239.

**Closed by mazameli** 2019-06-18 19:04 UTC
Labels: Duplicate
