### ISSUE TITLE
Field names to retain full path from nested NoSQL data structures

### ISSUE THREAD

**Issue by gabriel-r** [metabase/metabase#17983] opened 2021-09-21 09:18 UTC
When importing from a NoSQL DB, MongoDB in my case, the field names are flattened, keeping only the final "local" name.

This results in duplicate and incomprehensible field names. E.g. from this document:

```
{ 
    "_id" : ObjectId("593967424703e21546aad528"), 
    "name" : "vogue", 
    "user" : {
        "id" : "915493236", 
        "name" : "Madonna"
    }, 
    "createdAt" : ISODate("2016-11-25T12:26:16.177+0200"), 
    "updatedAt" : ISODate("2016-11-25T12:26:16.177+0200"), 
    "platform" : "universal", 
    "extension" : {
        "id" : "915493236", 
        "name" : "APIv2.1"
    }, 
    "external" : {
        "url" : "https://twitter.com/parentful",
        "id" : "915493236", 
    }
}

```

The resulting structure is not usable:
```
createdAt
id
id
id
id
name
name
platform
updatedAt
name
url
```

**When importing from NoSQL DBs, keep the document path in the fields names.**

```
id
name
user.id
user.name
createdAt
updatedAt
platform
extension.id
extension.name
external.url
external.id
```

Alternatively, add the path in the description of each field. Less useful right away, but at least one can clean things up manually in the Admin interface. 

Without this, NoSQL is a lot more difficult than it should be. To me, it's unusable.

**Comment by flamber** [comment] 2021-09-21 10:24
Duplicate of #9684

**Closed by flamber** 2021-09-21 10:24 UTC
Labels: Type:New Feature, .Needs Triage
