### ISSUE TITLE
Metabase v0.37.2 - Resyncing schemas w/ Redshift database fails

### ISSUE THREAD

**Issue by cgddrd** [metabase/metabase#13845] opened 2020-11-19 12:22 UTC
**Describe the bug**

Since upgrading to v0.37.2 from v0.36.8, attempts to resync table schemas with Redshift fail and result in the following error: `org.postgresql.util.PSQLException: ERROR: type "e" does not exist`. 

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

```
[ed6d494a-d9e7-4210-9d63-db1895eaf820] 2020-11-19T10:52:38+00:00 DEBUG metabase.middleware.log POST /api/database/8/sync_schema 200 1.9 ms (1 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (124 total active threads) Queries in flight: 0 (0 queued)
[ed6d494a-d9e7-4210-9d63-db1895eaf820] 2020-11-19T10:52:38+00:00 INFO metabase.sync.util STARTING: Sync metadata for redshift Database 8 'Redshift'
[ed6d494a-d9e7-4210-9d63-db1895eaf820] 2020-11-19T10:52:38+00:00 INFO metabase.sync.util STARTING: step 'sync-timezone' for redshift Database 8 'Redshift'
[ed6d494a-d9e7-4210-9d63-db1895eaf820] 2020-11-19T10:52:38+00:00 INFO metabase.sync.util FINISHED: step 'sync-timezone' for redshift Database 8 'Redshift' (23.1 ms)
[ed6d494a-d9e7-4210-9d63-db1895eaf820] 2020-11-19T10:52:38+00:00 INFO metabase.sync.util STARTING: step 'sync-tables' for redshift Database 8 'Redshift'
[ed6d494a-d9e7-4210-9d63-db1895eaf820] 2020-11-19T10:52:38+00:00 ERROR metabase.sync.util Error running sync step
org.postgresql.util.PSQLException: ERROR: type "e" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:311)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:297)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:274)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at org.postgresql.jdbc.PgDatabaseMetaData.getTables(PgDatabaseMetaData.java:1317)
	at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getTables(NewProxyDatabaseMetaData.java:3010)
	at metabase.driver.sql_jdbc.sync.describe_database$db_tables$fn__76737.invoke(describe_database.clj:74)
	at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__76712.reduce(common.clj:34)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$cat$fn__8761.invoke(core.clj:7625)
	at clojure.core$map$fn__5862$fn__5863.invoke(core.clj:2742)
	at clojure.core$completing$fn__8440.invoke(core.clj:6868)
	at clojure.core$filter$fn__5889$fn__5890.invoke(core.clj:2806)
	at clojure.core$take_while$fn__5913$fn__5914.invoke(core.clj:2901)
	at clojure.core.protocols$fn__8159.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8159.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8114$G__8109__8123.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8146.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$reduce.invoke(core.clj:6810)
	at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__76712.reduce(common.clj:35)
	at clojure.core$transduce.invokeStatic(core.clj:6883)
	at clojure.core.Eduction.reduce(core.clj:7682)
	at clojure.core$transduce.invokeStatic(core.clj:6883)
	at clojure.core.Eduction.reduce(core.clj:7682)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$into.invokeStatic(core.clj:6895)
	at clojure.core$into.invoke(core.clj:6887)
	at metabase.driver.sql_jdbc.sync.describe_database$describe_database$fn__76769.invoke(describe_database.clj:124)
	at metabase.driver.sql_jdbc.sync.describe_database$describe_database.invokeStatic(describe_database.clj:119)
	at metabase.driver.sql_jdbc.sync.describe_database$describe_database.invoke(describe_database.clj:116)
	at metabase.driver.sql_jdbc$fn__78130.invokeStatic(sql_jdbc.clj:57)
	at metabase.driver.sql_jdbc$fn__78130.invoke(sql_jdbc.clj:55)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.sync.fetch_metadata$fn__58073$db_metadata__58078$fn__58079.invoke(fetch_metadata.clj:13)
	at metabase.sync.fetch_metadata$fn__58073$db_metadata__58078.invoke(fetch_metadata.clj:10)
	at metabase.sync.sync_metadata.tables$fn__59499$db_metadata__59504$fn__59505.invoke(tables.clj:146)
	at metabase.sync.sync_metadata.tables$fn__59499$db_metadata__59504.invoke(tables.clj:143)
	at metabase.sync.sync_metadata.tables$fn__59560$sync_tables_BANG___59565$fn__59566.invoke(tables.clj:163)
	at metabase.sync.sync_metadata.tables$fn__59560$sync_tables_BANG___59565.invoke(tables.clj:158)
	at metabase.sync.util$fn__44054$run_step_with_metadata__44059$fn__44063$fn__44065.invoke(util.clj:345)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:119)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:116)
	at metabase.sync.util$fn__44054$run_step_with_metadata__44059$fn__44063.invoke(util.clj:342)
	at metabase.sync.util$fn__44054$run_step_with_metadata__44059.invoke(util.clj:337)
	at metabase.sync.util$fn__44246$run_sync_operation__44251$fn__44252$fn__44253.invoke(util.clj:430)
	at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$mapv.invokeStatic(core.clj:6903)
	at clojure.core$mapv.invoke(core.clj:6903)
	at metabase.sync.util$fn__44246$run_sync_operation__44251$fn__44252.invoke(util.clj:430)
	at metabase.sync.util$fn__44246$run_sync_operation__44251.invoke(util.clj:424)
	at metabase.sync.sync_metadata$fn__59613$sync_db_metadata_BANG___59618$fn__59619$fn__59620.invoke(sync_metadata.clj:51)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:145)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
	at clojure.core$partial$fn__5839.invoke(core.clj:2623)
	at metabase.driver$fn__22483.invokeStatic(driver.clj:550)
	at metabase.driver$fn__22483.invoke(driver.clj:550)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__43966.invoke(util.clj:138)
	at metabase.sync.util$with_db_logging_disabled$fn__43963.invoke(util.clj:129)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
	at metabase.sync.util$with_start_and_finish_logging$fn__43952.invoke(util.clj:114)
	at metabase.sync.util$with_sync_events$fn__43947.invoke(util.clj:88)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__43938.invoke(util.clj:67)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:164)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:161)
	at metabase.sync.sync_metadata$fn__59613$sync_db_metadata_BANG___59618$fn__59619.invoke(sync_metadata.clj:50)
	at metabase.sync.sync_metadata$fn__59613$sync_db_metadata_BANG___59618.invoke(sync_metadata.clj:47)
	at metabase.api.database$fn__60358$fn__60360.invoke(database.clj:634)
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[ed6d494a-d9e7-4210-9d63-db1895eaf820] 2020-11-19T10:52:38+00:00 INFO metabase.sync.util FINISHED: Sync metadata for redshift Database 8 'Redshift' (44.9 ms)
[ed6d494a-d9e7-4210-9d63-db1895eaf820] 2020-11-19T10:52:38+00:00 INFO metabase.sync.util STARTING: Analyze data for redshift Database 8 'Redshift'
[ed6d494a-d9e7-4210-9d63-db1895eaf820] 2020-11-19T10:52:38+00:00 INFO metabase.sync.util STARTING: step 'fingerprint-fields' for redshift Database 8 'Redshift'
```

**To Reproduce**
1. Go to Admin console -> 'Databases' 
2. Select Redshift database.
3. Select 'Sync database schema now'

**Expected behavior**

When a resync of a Redshift database is triggered in Metabase, it should complete successfully, with new schemas made accessible via the UI.

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.186-110.268.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "mysql"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.8"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-11-16",
      "tag": "v0.37.2",
      "branch": "release-x.37.x",
      "hash": "25e5f70"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

High severity, whilst existing schemas are still accessible via Metabase, it isn't possible to make available new tables that we need to add, or remove old schemas that are no longer required from the GUI, thus making it much harder for standard (non-SQL) users to access our datasets.

**Additional context**

**Comment by flamber** [comment] 2020-11-19 12:48
Hi @cgddrd 
While it looks like your database is saved as "Database type"="Redshift", can you just validate that it's not saved as "PostgreSQL"?
Looks like #9844, but that should have been fixed a long time ago.

**Comment by cgddrd** [comment] 2020-11-19 12:49
Hey @flamber, thanks for the super quick response. 

I think it's saved as a RS database, here's what the UI says:

**Comment by cgddrd** [comment] 2020-11-19 12:52
Just took a look at #9844 - just to confirm, we've never attempted to change from the Redshift to PgSql driver before.

**Comment by flamber** [comment] 2020-11-19 12:58
One of the driver developers needs to look at this later today. They might ask for extra information.
But it would help a lot if you could try adding the following environment variable, since it will provide much more details on sync:
`JAVA_OPTS="-Dlog4j.configurationFile=https://log4j.us/v2/templates/metabase?trace=metabase.sync"`

**Comment by cgddrd** [comment] 2020-11-19 13:29
@flamber - so, this is a bit weird, but after adding the env. variables you suggested above and restarting the EB environent/app server, I attempted the sync again so I could send the detailed logs through, and things are now working again?! 

I've confirmed that the tables I was expecting to see appear (that weren't before) are now there, and as far as I can see, the sync has completed successfully as expected. 

I don't really understand why this has happened now, as we would have had to restart the app servers following the upgrade procedure on EB.

**Comment by cgddrd** [comment] 2020-11-19 13:30
I can send the logs I've got now if that's of interest, but I believe (for now at least) we can close this ticket?

**Comment by flamber** [comment] 2020-11-19 13:40
It sounds a little like, when #9844 needed a restart to fix the problem. I'm wondering if you have the logs from before you restarted with the envvar - have a feeling that there might have been some indication there (earlier than the sync error) that something was not completely right.
I'm okay with closing this, but if this happens again, then we probably need to figure out the root cause with much more logs.

**Closed by flamber** 2020-11-19 13:40 UTC
Labels: .Regression, Administration/Metadata & Sync, Database/Redshift, Priority:P1, Type:Bug

**Comment by cgddrd** [comment] 2020-11-19 17:33
Hi @dpsutton - to the best of my knowledge, no this database has never been marked as Postgres. If there's a way to check for sure, I'm happy to try to do this.

**Comment by dpsutton** [comment] 2020-11-19 17:40
I think that's sufficient. Don't go out of your way. It seems very unlikely that the db type of this database was changed. That seemed to have been at least one underlying cause in the linked issue but i think this points that there is something else more subtle going on as well.
