### ISSUE TITLE
Toggling filter availability across multiple tabs in a dashboard

### ISSUE THREAD

**Issue by tocwneise** [metabase/metabase#36755] opened 2023-12-13 15:21 UTC
**Is your feature request related to a problem? Please describe.**
This is not related to any specific problem but would help end user visibility.  For example, tab1 could show questions in relation to date1 while tab2 could show the same questions in relation to date2.  If I include filters for each of these dates, the end user may get confused when they apply a filter to date1 and tab2 does not change and vice versa while other categorical filters will change both tabs.

**Describe the solution you'd like**
Either build in a selector for each filter showing which tab it would be visible in and apply to or, automatically gray out or remove the filter for the end user if all of the questions on that tab do not have an attribute selected in the dropdown for that filter.

**Describe alternatives you've considered**
Tried to create a combined column of Date1 and Date2, but there is no way to link each to a tab.  I've also added a note, but this still creates confusion with the end user.

**How important is this feature to you?**
This is of moderate importance as I am only applying this to 1 dashboard at the moment.  In the future I may have to create multitab dashboards using the same questions, just shifting the reference based on some categorical attribute that in itself can contain sub categories that would require filters based on the selected tab.

**Comment by paoliniluis** [comment] 2023-12-13 22:23
so the request is filters that apply for specific tabs?

**Comment by gasp37** [comment] 2023-12-22 19:09
> so the request is filters that apply for specific tabs?

Kinda. This is a really good request. The idea is that a filter is only *shown* on specific tabs.

So let's say you have a dashboard regarding your company's sales, in one tab you want to analyze the sales by location, while in the other tab, you want to analyze the sales by product.

In the sales by location tab you might want to show filters such as: Date; Country; City
While in the sales by product you'd use the filters: Date; Segment; Product

As it is now, both pages would show all filters: Date, Country, City, Segment, Product. And in some cases, this can get messy. So if we could choose in which tab a filter would be shown that would be amazing and would really improve the end-user experience.

Made sense?

**Comment by udit-001** [comment] 2024-01-24 07:05
It would be a helpful feature to have filters that apply for specific tabs only! 🙌

**Comment by alexandroabalo** [comment] 2024-02-09 10:18
I would love to have it! It's really weird to see filters that didn't work in some tabs

**Comment by ignacio-mb** [comment] 2024-03-25 18:25
Hi @alexandroabalo @udit-001 @gasp37, are you referring to this https://github.com/metabase/metabase/issues/31621? We shipped it in v49.

**Comment by Tony-metabase** [comment] 2024-04-15 12:56
Closing as duplicate of https://github.com/metabase/metabase/issues/31621

**Closed by Tony-metabase** 2024-04-15 12:56 UTC
Labels: Type:New Feature, .Needs Triage
