### ISSUE TITLE
To-dos for finishing Permissions v1

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3435] opened 2016-10-03 17:37 UTC
@kdoh 

* [x] Grid columns should take up as much space as is avaliable
* [x] Change blue edit header to 80% tint of gray of admin panel bg color
* [x] Cancel confirm modal missing some padding (fix in `Confirm` component?)
* [x] All references to "raw queries" should be changed to "SQL queries"
* [x] Bump up width allotted to Databases/Schemas/Tables column to maybe 180px
* [x] Remove "real" database names below database labels in the permissions chart

@tlrobinson

* [x] In the SQL editor's `Database` dropdown, I should only see databases for which I have `write raw queries` permissions ~~(needs endpoint update from @camsaul)~~
* [x] In dashboard, a dashcard for which I don't have permission shouldn't display its title (this is the "List of people to be fired" example case) ~~(needs endpoint update from @camsaul)~~
* [x] Clear dashcard data cache when navigating away from dashboard

@camsaul 

* [x] Do not return card titles (and query definitions?) in dashcards' `card` and `series` cards if the user doesn't have permission to view the card.
* [x] Add a native read/write/none permissions flag in database metadata endpoints to facilitate hiding in SQL editor
* [x] `Illegal clause (no matching fn found): :segment` and `Illegal clause (no matching fn found): :metric` errors, currently manifesting in:
  * [x] Fix: on the Stats instance, some of the saved questions filters (like Favorites and Saved by Me) are returning `An error occurred`
  * [x] Fix: on Stats, the `Dashboards` menu isn’t opening
  * [x] Fix: on Stats, the `Add to Dashboard` action from question details isn’t rendering correctly

**Comment by camsaul** [comment] 2016-10-03 22:43
RE

> All references to "raw queries" should be changed to "SQL queries"

Keep in mind that not all databases use SQL (Mongo, Druid)

**Comment by salsakran** [comment] 2016-10-03 22:45
@camsaul yeah ... the problem is that so far nothing else seems even remotely clear. Suggestions for alternative text welcome =)

**Comment by camsaul** [comment] 2016-10-05 18:58
are these all done?

**Comment by kdoh** [comment] 2016-10-05 18:58
I'm still wrapping up a couple assigned to me, should be done shortly though.

**Comment by camsaul** [comment] 2016-10-07 23:09
This is all done right?

**Comment by salsakran** [comment] 2016-10-07 23:09
pretty sure @kdoh is still working on his issues

**Comment by kdoh** [comment] 2016-10-10 15:38
My stuff should be g2g minus one bug I found while stress testing the grid with a ton of groups that I might need a bit of assistance from @tlrobinson on.

**Closed** 2016-10-10 23:23 UTC
Labels: Permissions
