### ISSUE TITLE
Pivot Table column width should be adjust to widget size or should be changeable manually

### ISSUE THREAD

**Issue by jereh16** [metabase/metabase#16391] opened 2021-06-07 14:46 UTC
The size of the columns of the pivot table should be adjustable. Either automatically to the size of the widget (like the other tables) or manually by being able to adjust the column width.

![image](https://user-images.githubusercontent.com/489879/121037136-81740280-c7af-11eb-9369-0a628ca65091.png)

Currently using Metabse v0.39.3

**Comment by flamber** [comment] 2021-06-07 14:55
Duplicate of #14350

**Closed by flamber** 2021-06-07 14:55 UTC
Labels: .Epic
