### ISSUE TITLE
Metabase model field description is copying from last field

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#27966] opened 2023-01-30 23:29 UTC
**Describe the bug**
In a Metabase model that has no field descriptions, when editing the metadata, the field description is being copied to other fields on first edit. 

**Logs**
n/a

**To Reproduce**
1. Edit a Metabase model that has no field descriptions
2. Go to Metadata tab
3. Add description for 1 field
4. Click on another field with no descriptions and the field's description is populated with the previous field's description. 

**Expected behavior**
A field without description should show blank description

**Screenshots**
n/a

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome
- Your operating system: OS X
- Your databases:  Postgres
- Metabase version:  master
- Metabase hosting environment: Cloud Dev
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
It seems to be cosmetic so won't be saved but confusing. 

**Additional context**
n/a

**Comment by paoliniluis** [comment] 2023-01-31 12:45
dupe of https://github.com/metabase/metabase/issues/25884

**Closed by paoliniluis** 2023-01-31 12:45 UTC
Labels: Type:Bug, .Needs Triage
