### ISSUE TITLE
Column settings not accessible when column name is long

### ISSUE THREAD

**Issue by gajus** [metabase/metabase#10345] opened 2019-07-13 15:56 UTC
**Describe the bug**

<img width="420" alt="Screenshot 2019-07-13 at 16 54 48" src="https://user-images.githubusercontent.com/973543/61173718-1869bd00-a58f-11e9-92d0-7b74fec1bb42.png">

**Comment by flamber** [comment] 2019-07-13 16:26
Duplicate of #10286

**Closed** 2019-07-13 16:33 UTC
Labels: Bug
