### ISSUE TITLE
Row Chart with Limit: Wrong number of results

### ISSUE THREAD

**Issue by zaiddabaeen** [metabase/metabase#5477] opened 2017-07-14 08:47 UTC
Metabase row chart does not show the right number of results. If using limit 5, and using the table view, there are 5 results. When switching to row chart, there are only 4 results. If using limit 10, and using the table view, there are 10 results. When switching to row chart, there are 7 results.

My SQL is as such:

```sql
SELECT p2.name as "Param2", (this_week.count-last_week.count)/last_week.count * 100 as `Change`
FROM
(
    SELECT p1.p2_id as `p2_id`, count(p1.id) as `count`
    FROM filtered_p1 p1
    WHERE str_to_date(concat(yearweek(`p1`.`created`), ' Sunday'), '%X%V %W') = str_to_date(concat(yearweek(date_add(now(), INTERVAL -2 week)), ' Sunday'), '%X%V %W')
    GROUP BY p1.p2_id
) as last_week
INNER JOIN
(
    SELECT p1.p2_id as `p2_id`, count(p1.id) as `count`
    FROM filtered_p1 p1
    WHERE str_to_date(concat(yearweek(`p1`.`created`), ' Sunday'), '%X%V %W') = str_to_date(concat(yearweek(date_add(now(), INTERVAL -1 week)), ' Sunday'), '%X%V %W')
    GROUP BY p1.p2_id
) as this_week
ON last_week.p2_id = this_week.p2_id
LEFT JOIN p2s p2 ON v.id = this_week.p2_id
GROUP BY this_week.p2_id
HAVING `Change` < 0
ORDER BY `Change` ASC
LIMIT 10;
```

- Your browser and the version: Chrome 59.0.3071.115
- Your operating system: Mac Sierra 10.12.5
- Your databases: MySQL
- Metabase version: 0.24.2
- Metabase hosting environment: JAR on EC2
- Metabase internal database: H2

I do have the reverse of this same SQL using 

```sql
HAVING `Change` > 0
ORDER BY `Change` DESC
```
that shows the right number of results.

**Comment by salsakran** [comment] 2017-07-17 21:39
Can't reproduce this. Can you construct a query that results in this behaviour using the sample dataset? I've tried a couple variants of order bys and selects, but eg 

```
select id, total from orders
order by id desc
limit 10
```
results in 10 bars in both row and table views

**Comment by zaiddabaeen** [comment] 2017-07-18 09:35
Here you go:

```
SELECT p.ID, (p.PRICE-1000) as `price`
FROM `orders` o 
LEFT JOIN `products` p ON p.id = o.product_id
ORDER BY `price` DESC
LIMIT 10;
```

The error in action (Sadly github doesn't support video upload):
https://vid.me/HlTuF
This is a fresh metabase.jar installation.

**Comment by camsaul** [comment] 2017-12-07 03:15
@zaiddabaeen are you still seeing this issue?

**Comment by snarfed** [comment] 2018-03-13 18:59
i think i'm seeing this same bug, particularly with the "other" consolidation. i get a decent row chart for a result dataset with 25 rows, but with 100 rows, i just get one row and "other":

<img width="1168" alt="untitled" src="https://user-images.githubusercontent.com/778068/37363720-dda48852-26b5-11e8-8cad-ecb9ee5239db.png">

full 100 row dataset:

```csv
x,count
a,623077
b,622913
c,622832
d,622832
e,622828
f,622751
g,622695
h,622675
i,432212
j,255755
k,241886
l,220698
m,215706
n,213590
o,213282
p,208654
q,168880
r,168436
s,123662
t,119042
u,116190
v,116158
w,102431
x,78662
y,72661
z,71928
a,71928
b,71928
c,71928
d,71928
e,71928
f,71928
g,71928
h,71928
i,71928
j,71928
k,71928
l,71928
m,71928
n,71928
o,71928
p,71928
q,66105
r,55750
s,55750
t,55750
u,54301
v,49566
w,49529
x,49394
y,49361
z,49257
a,47606
b,47530
c,47467
d,47456
e,47048
f,46726
g,45900
h,39441
i,39411
j,39400
k,39394
l,39297
m,38874
n,38514
o,38459
p,38130
q,38092
r,38015
s,37841
t,37685
u,37639
v,37396
w,37393
x,32955
y,32941
z,32881
a,32850
b,32823
c,32822
d,28112
e,26421
f,26013
g,26013
h,22758
i,18944
j,16206
k,12852
l,12456
m,12315
n,11523
o,11521
p,11520
q,10787
r,7864
s,7844
t,7777
u,6795
v,5238
```

**Comment by flamber** [comment] 2020-05-23 15:56
Closing, since the video is not available anymore and the query example returns 10 rows with the same data. Don't think this has anything to do with `LIMIT`.
As for too many rows being consolidated in "Others", there's a specific issue for that #7544

**Closed by flamber** 2020-05-23 15:56 UTC
Labels: .Unable to Reproduce, Priority:P3, Type:Bug
