### ISSUE TITLE
Unable to Load Dashboard, Javascript Error - "Cannot read properties of undefined (reading 'type')"

### ISSUE THREAD

**Issue by joshymantou11** [metabase/metabase#22123] opened 2022-04-27 03:02 UTC
**Describe the bug**
Some team members are unable to load a shared dashboard and encounter the javascript error "Cannot read properties of undefined (reading 'type')", while some other team members are able to load it. 

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

<img width="2560" alt="Javascript log" src="https://user-images.githubusercontent.com/103890489/165430806-448d16bf-e425-43de-a8c9-e03ef65740ec.png">

**To Reproduce**
1. No specific steps except for clicking on the dashboard.

**Expected behavior**
The dashboard should load.

**Screenshots**
<img width="1012" alt="Metabase js Error" src="https://user-images.githubusercontent.com/103890489/165430994-db2c0848-d410-4163-b168-c43728399d83.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox version 99.0.1 (64-bit)
- Your operating system: OS X 12.0.1
- Your databases: Postgres
- Metabase version: v0.42.0
- Metabase hosting environment: Self hosted via AWS EC2
- Metabase internal database: Postgres

**Severity**
High severity - blocking access for key internal stakeholders in the team. 
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by flamber** [comment] 2022-04-27 07:37
Duplicate of #20656

**Closed by flamber** 2022-04-27 07:37 UTC
Labels: Type:Bug, .Needs Triage
