### ISSUE TITLE
admin can not manage user's private collections

### ISSUE THREAD

**Issue by szsuyuji** [metabase/metabase#19505] opened 2021-12-31 03:55 UTC
**Describe the bug**

admin cant not see user's private collection fold ,i want move the collection to other collection

**Comment by flamber** [comment] 2021-12-31 08:07
Hi @szsuyuji 
You currently cannot move, change or disable Personal Collections.
Duplicate of #15339

**Closed by flamber** 2021-12-31 08:07 UTC
Labels: Type:Bug, .Needs Triage
