### ISSUE TITLE
long integer will lost precision

### ISSUE THREAD

**Issue by ckmbks** [metabase/metabase#13205] opened 2020-09-04 06:57 UTC
metabase v0.36.3
Mysql5.7
when query long integer data,the result will lost precision.
for examlpe,data is 483018443327537201,query result will be 483018443327537200.
please fix this bug,thanks every much!

**Comment by flamber** [comment] 2020-09-04 09:36
Duplicate of #5816

**Closed by flamber** 2020-09-04 09:36 UTC
Labels: .Needs Triage, Type:Bug
