### ISSUE TITLE
Bug - Query failing when using more than one segment

### ISSUE THREAD

**Issue by mvrabel** [metabase/metabase#5706] opened 2017-08-08 08:33 UTC
Your browser and the version: 60.0.3112.90 
Your operating system: Win 10
Your databases: Postgresql 9.6
Metabase version: 0.25.0
Metabase hosting environment: CentOS7
Metabase internal database: H2 (default)

- Repeatable steps to reproduce the issue
1. new question
2. add 2 segments as filters
3. `There was a problem with your question`

`Show error details
Here's the full error message
Input to compound-filter does not match schema: [0;33m [nil (named (named (not (matches-some-precondition? nil)) "Valid filter clause") subclause) (named (not (matches-some-precondition? nil)) "Valid filter clause")] [0m`

**Comment by mvrabel** [comment] 2017-08-09 06:44
Workaround: F5 - reload page

**Comment by mazameli** [comment] 2017-08-10 17:59
Repro-ed. This also happens with a single segment + an additional normal filter, like this:

<img width="857" alt="screen shot 2017-08-10 at 10 58 44 am" src="https://user-images.githubusercontent.com/2223916/29184404-e8f2e964-7dba-11e7-96f4-ec6254e28387.png">

**Comment by jpulec** [comment] 2017-08-10 18:58
I believe #5530 is the same issue, or at least caused by the same issue.

**Comment by mattdoran** [comment] 2017-08-23 00:00
This is a serious issue for us as we use segments in basically every query.   Is it possible to get a bug fix for this one?

**Closed** 2017-08-23 03:51 UTC
Labels: Bug, Metrics & Segments, Priority/P2

**Comment by mazameli** [comment] 2017-09-27 20:25
Hey everyone. Just a heads up that [we've just shipped version 0.26](http://www.metabase.com/blog/Metabase-0.26) which fixes this issue.
