### ISSUE TITLE
Error downloading results from in cvs, xlsx, json

### ISSUE THREAD

**Issue by gustavosobol** [metabase/metabase#33450] opened 2023-08-23 20:37 UTC
**Describe the bug**

It does not allow downloading in csv, excel, or json format, the same thing happens from the question or control panel.

And attached screenshot of other errors

**Expected behaviour**
How it worked in the previous version

**Screenshots**
Results CSV
![Captura de pantalla_área-de-selección_20230823155340](https://github.com/metabase/metabase/assets/11079334/b282469e-3176-4435-8215-3d59e5f918ed)

Results excel

![Captura de pantalla_área-de-selección_20230823155448](https://github.com/metabase/metabase/assets/11079334/7c893ed6-5d7b-4f3b-86b8-4e4aa905bd9f)

**Severity**
Several clients depend on these types of downloads

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "es-ES",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8",
    "os.name": "Linux",
    "os.version": "5.15.0-78-generic",
    "user.language": "en",
    "user.timezone": "America/Argentina/Ushuaia"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-08-16",
      "tag": "v0.47.0",
      "branch": "release-x.47.x",
      "hash": "682ec2d"
    },
    "settings": {
      "report-timezone": "America/Argentina/Ushuaia"
    }
  }
}
```

**Comment by paoliniluis** [comment] 2023-08-23 23:00
do you use a reverse proxy on top of Metabase?

**Comment by gustavosobol** [comment] 2023-08-23 23:14
If I am using a reverse proxy and I also redirect it to a subfolder... did anything change in this version? Because it's the first time this has happened to me and I've had it configured like this for a long time... I share the nginx configuration
```
  location /subfolder/ {
         default_type application/json;
         proxy_hide_header Content-Location;
         add_header Content-Location /api/$upstream_http_content_location;
         proxy_set_header Connection "";
         proxy_http_version 1.1;
         proxy_pass http://ip:port/;
       }
```

**Comment by asimumba** [comment] 2023-08-24 12:47
This is the same problem I have. Mine started when I upgraded to 0.47.0. For all the other lower versions, this has always worked.

**Comment by paoliniluis** [comment] 2023-08-24 12:49
duplicate of https://github.com/metabase/metabase/issues/33244. I'll keep the investigation on that issue

**Closed by paoliniluis** 2023-08-24 12:49 UTC
