### ISSUE TITLE
Cannot use "String is" or "String is not" on field filters for fields with no semantic type

### ISSUE THREAD

**Issue by araujo-filipe** [metabase/metabase#21653] opened 2022-04-13 17:15 UTC
**Describe the bug**
When creating a field filter linked to a text field, if that field does not have a semantic type defined one can't pick the options "String is" or "String is not".

**To Reproduce**
1. Create a new question on the sample database with `select * from people [[where {{address}}]]`
2. Make {{address}} a field filter and link it to people.address
3. Try to pick field filter type
4. See not all options show up

Optionally
5. In Admin->Data Model make people.address a "Category" semantic type
6. Retry previous steps and notice that you can see "String" and "String is not" on the options

**Expected behavior**
I should be able to see the option to use this filter as an exact match and not partial match only.

**Screenshots**
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/59164598/163233831-b3d5e9f2-4218-470c-baec-d738410ca5e7.png">

**Severity**
Not super severe as we can just set the semantic type when this happens.
Could be a bit sensitive because setting a field as "Category" will show values on the dropdown as you write on the filter, which could be sensitive data.

**Additional context**
Not all semantic types work here. "Category" and "Title" work for example but "Description" and "Comment" don't.
One other thing, when the options do show up they show as "String" and "String is not". I believe the first one should be "String is".

Information about your Metabase Installation:
tested on v0.42.4

**Comment by flamber** [comment] 2022-04-13 17:28
Likely a duplicate of #11274 + #20048 combined.
History https://github.com/metabase/metabase/issues/20643#issuecomment-1045992726

**Comment by araujo-filipe** [comment] 2022-04-13 17:40
Well, after going through [the documentation](https://www.metabase.com/docs/v0.42/users-guide/13-sql-parameters.html#the-field-filter-variable-type) a bit deeper I see this expected behaviour, so maybe this is more of a feature request than a bug?

**Comment by flamber** [comment] 2022-04-13 17:42
If you read the issues I've linked, then you'll see that it's a common problem and has just gotten worse in 42.

**Closed** 2022-04-22 17:20 UTC
Labels: Type:Bug, Priority:P2, Querying/Parameters & Variables, Querying/Native, .Frontend, Querying/GUI
