### ISSUE TITLE
Export To Google Spreadsheet

### ISSUE THREAD

**Issue by jpulec** [metabase/metabase#3772] opened 2016-11-16 21:56 UTC
One of the great features of Heroku's dataclip platform is that it allows easily exporting dataclips to google spreadsheets. It does this by using google spreadsheets `importData` command which just expects to receive a url that contains a CSV file. You don't need to be logged in or have any permissions to access these urls. Heroku does this by just using UUIDs for it's csv urls.

Is this something to consider supporting in metabase?

**Comment by salsakran** [comment] 2016-11-16 21:57
yup! #3680 + tacking a '/csv` will get this working for you. 

Closing this as a dupe of that issue. We'll be working on that in the near term!

**Closed by salsakran** 2016-11-16 21:57 UTC

**Comment by codingjoe** [comment] 2020-01-17 07:26
Just for reference, it's `.csv` now, not `/csv`.
Anyhow, I'd wish there is a field where I can just copy the correct URL. I don't want to explain my CEO, that he needs to go to spreadsheets, type `=IMPORTDATA()` then share the metabase report, copy the public URL and paste it while amending `.csv`.
It's just too complicated for your average Joe.
