### ISSUE TITLE
Flexible permissions

### ISSUE THREAD

**Issue by eudj1n** [metabase/metabase#1450] opened 2015-11-05 05:50 UTC
Good day! 

After using metabase, I have some ideas to improve permissions:

* Allow guest to view dashboads and saved queries
* Allow administrator to provide access for registered users with predefined databases list

**Comment by tlrobinson** [comment] 2015-11-05 19:00
Related to (duplicate of?) #1175

**Comment by salsakran** [comment] 2015-11-05 19:03
Yes.

@eudj1n Thanks for the feedback! We're primarily focusing on making Metabase useful for small groups without a lot of permission/auth functionality for the near future. We'd love it if you could give us any concrete use cases you have for permissions as it'll help us fully spec out a potential future system. Permissions systems are tricky to setup without making them horribly complicated and we're going to be moving carefully here.

**Comment by styts** [comment] 2015-11-12 14:28
We would also be interested in some permissions functionality.
In our case we would like to have one metabase instance for the company and limit certain users(teams?) to certain databases and dashboards.

**Comment by camsaul** [comment] 2016-01-21 00:57
Closing as duplicate of #1175

**Closed by camsaul** 2016-01-21 00:57 UTC
Labels: Duplicate
