### ISSUE TITLE
How to rename the schame name show in /browse/2 ?

### ISSUE THREAD

**Issue by zhxjdwh** [metabase/metabase#17346] opened 2021-08-06 01:38 UTC
How to rename the schame name show in /browse/{id} ?
![image](https://user-images.githubusercontent.com/9401765/128442814-e8b7050c-0fc9-4eba-855c-f875bb06b077.png)

**Comment by flamber** [comment] 2021-08-06 09:01
Duplicate of #6619
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Closed by flamber** 2021-08-06 09:01 UTC
Labels: Type:Question, .Needs Triage
