### ISSUE TITLE
Newly added MySQL DB tables not showing up, but old ones do show up

### ISSUE THREAD

**Issue by jfang** [metabase/metabase#38499] opened 2024-02-07 05:28 UTC
**Describe the bug**
After the upgrade to Metabase v0.48.4, I am not able to see any newly added MySQL DB tables even after I have clicked on the "Sync database schema now" and "Re-scan field values now" buttons. The old tables that were created before the upgrade is showing up. Updating to v0.48.5 does not seem to resolve this issue.

When I go to "+ New" and click on "SQL Query", I am able to pull up the data from my newly added table. However, when I go to "+New" and click on "Question", the newly added table does not show up in the "Pick your starting data" section. Only the old tables are there.

It seems like the **"Sync database schema now" functionality** is not working correctly.

**Logs**
Feb 06 20:34:372024-02-07 04:34:37,037 DEBUG middleware.log :: GET /api/database/2/schemas 200 34.6 ms (4 DB calls) App DB connections: 1/4 Jetty threads: 4/50 (3 idle, 0 queued) (48 total active threads) Queries in flight: 0 (0 queued)
Feb 06 20:34:372024-02-07 04:34:37,149 DEBUG middleware.log :: GET /api/database/2/schema/ 200 56.8 ms (6 DB calls) App DB connections: 2/4 Jetty threads: 4/50 (3 idle, 0 queued) (48 total active threads) Queries in flight: 0 (0 queued)
Feb 06 20:34:372024-02-07 04:34:37,191 DEBUG middleware.log :: GET /api/database 200 170.7 ms (8 DB calls) App DB connections: 1/4 Jetty threads: 3/50 (3 idle, 0 queued) (49 total active threads) Queries in flight: 0 (0 queued)
Feb 06 20:35:332024-02-07 04:35:33,570 DEBUG middleware.log :: GET /api/database/2 200 25.0 ms (3 DB calls) App DB connections: 1/4 Jetty threads: 3/50 (4 idle, 0 queued) (49 total active threads) Queries in flight: 0 (0 queued)
Feb 06 20:35:352024-02-07 04:35:35,524 INFO metabase.events :: Loading events namespace: metabase.events.audit-log 👂
Feb 06 20:35:352024-02-07 04:35:35,602 INFO metabase.events :: Loading events namespace: metabase.events.driver-notifications 👂
Feb 06 20:35:352024-02-07 04:35:35,632 INFO metabase.events :: Loading events namespace: metabase.events.last-login 👂
Feb 06 20:35:352024-02-07 04:35:35,643 INFO metabase.events :: Loading events namespace: metabase.events.persisted-info 👂
Feb 06 20:35:352024-02-07 04:35:35,670 INFO metabase.events :: Loading events namespace: metabase.events.recent-views 👂
Feb 06 20:35:352024-02-07 04:35:35,687 INFO metabase.events :: Loading events namespace: metabase.events.revision 👂
Feb 06 20:35:352024-02-07 04:35:35,737 INFO metabase.events :: Loading events namespace: metabase.events.schema 👂
Feb 06 20:35:352024-02-07 04:35:35,738 INFO metabase.events :: Loading events namespace: metabase.events.sync-database 👂
Feb 06 20:35:352024-02-07 04:35:35,756 INFO metabase.events :: Loading events namespace: metabase.events.view-log 👂
Feb 06 20:35:352024-02-07 04:35:35,909 DEBUG middleware.log :: POST /api/database/2/sync_schema 200 409.2 ms (3 DB calls) App DB connections: 1/4 Jetty threads: 3/50 (4 idle, 0 queued) (49 total active threads) Queries in flight: 0 (0 queued)
Feb 06 20:35:362024-02-07 04:35:36,681 DEBUG middleware.log :: POST /api/database/2/rescan_values 200 55.8 ms (3 DB calls) App DB connections: 1/4 Jetty threads: 3/50 (4 idle, 0 queued) (50 total active threads) Queries in flight: 0 (0 queued)
Feb 06 20:35:362024-02-07 04:35:36,685 INFO sync.util :: STARTING: Cache field values in mysql Database 2 'Twrl Inventory'
Feb 06 20:35:362024-02-07 04:35:36,731 INFO sync.util :: STARTING: step 'delete-expired-advanced-field-values' for mysql Database 2 'Twrl Inventory'
Feb 06 20:35:372024-02-07 04:35:37,447 INFO sync.util :: FINISHED: step 'delete-expired-advanced-field-values' for mysql Database 2 'Twrl Inventory' (715.1 ms)
Feb 06 20:35:372024-02-07 04:35:37,448 INFO sync.util :: STARTING: step 'update-field-values' for mysql Database 2 'Twrl Inventory'
Feb 06 20:35:392024-02-07 04:35:39,511 INFO sync.util :: FINISHED: step 'update-field-values' for mysql Database 2 'Twrl Inventory' (2.1 s)
Feb 06 20:35:392024-02-07 04:35:39,539 INFO sync.util :: FINISHED: Cache field values in mysql Database 2 'Twrl Inventory' (2.9 s)
Feb 06 20:39:002024-02-07 04:39:00,042 INFO task.sync-databases :: Starting sync task for Database 2.
Feb 06 20:39:002024-02-07 04:39:00,121 ERROR core.JobRunShell :: Job DEFAULT.metabase.task.sync-and-analyze.job threw an unhandled Exception:
Feb 06 20:39:00java.lang.IllegalArgumentException: No matching clause: REVOKE INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON "metrics_user_telegraf".* FROM "doadmin"@"%"
Feb 06 20:39:00at metabase.driver.mysql$parse_grant.invokeStatic(mysql.clj:788)
Feb 06 20:39:00at metabase.driver.mysql$parse_grant.invoke(mysql.clj:766)
Feb 06 20:39:00at clojure.core$map$fn__5935.invoke(core.clj:2770)
Feb 06 20:39:00at clojure.lang.LazySeq.sval(LazySeq.java:42)
Feb 06 20:39:00at clojure.lang.LazySeq.seq(LazySeq.java:51)
Feb 06 20:39:00at clojure.lang.RT.seq(RT.java:535)
Feb 06 20:39:00at clojure.core$seq__5467.invokeStatic(core.clj:139)
Feb 06 20:39:00at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
Feb 06 20:39:00at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
Feb 06 20:39:00at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
Feb 06 20:39:00at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
Feb 06 20:39:00at clojure.core$reduce.invokeStatic(core.clj:6886)
Feb 06 20:39:00at clojure.core$group_by.invokeStatic(core.clj:7214)
Feb 06 20:39:00at clojure.core$group_by.invoke(core.clj:7214)
Feb 06 20:39:00at metabase.driver.mysql$privilege_grants_for_user.invokeStatic(mysql.clj:836)
Feb 06 20:39:00at metabase.driver.mysql$privilege_grants_for_user.invoke(mysql.clj:825)
Feb 06 20:39:00at metabase.driver.mysql$fn__104935.invokeStatic(mysql.clj:884)
Feb 06 20:39:00at metabase.driver.mysql$fn__104935.invoke(mysql.clj:872)
Feb 06 20:39:00at clojure.lang.MultiFn.invoke(MultiFn.java:234)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$schema_PLUS_table_with_select_privileges.invokeStatic(describe_database.clj:125)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$schema_PLUS_table_with_select_privileges.invoke(describe_database.clj:123)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$have_select_privilege_fn.invokeStatic(describe_database.clj:143)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$have_select_privilege_fn.invoke(describe_database.clj:131)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$post_filtered_active_tables.invokeStatic(describe_database.clj:186)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$post_filtered_active_tables.doInvoke(describe_database.clj:181)
Feb 06 20:39:00at clojure.lang.RestFn.applyTo(RestFn.java:142)
Feb 06 20:39:00at clojure.core$apply.invokeStatic(core.clj:667)
Feb 06 20:39:00at clojure.core$apply.invoke(core.clj:662)
Feb 06 20:39:00at metabase.driver.mysql$fn__104819.invokeStatic(mysql.clj:535)
Feb 06 20:39:00at metabase.driver.mysql$fn__104819.doInvoke(mysql.clj:533)
Feb 06 20:39:00at clojure.lang.RestFn.invoke(RestFn.java:457)
Feb 06 20:39:00at clojure.lang.MultiFn.invoke(MultiFn.java:244)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$fn__81027$_AMPERSAND_f__81028$fn__81029$default_active_tbl_fn__81030.invoke(describe_database.clj:221)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$fn__81027$_AMPERSAND_f__81028$fn__81029.invoke(describe_database.clj:233)
Feb 06 20:39:00at metabase.driver.sql_jdbc.execute$fn__78811$fn__78812.invoke(execute.clj:388)
Feb 06 20:39:00at metabase.driver.sql_jdbc.execute$fn__78776$_AMPERSAND_f__78777.invoke(execute.clj:334)
Feb 06 20:39:00at metabase.driver.sql_jdbc.execute$fn__78776$fn__78780.invoke(execute.clj:317)
Feb 06 20:39:00at metabase.driver.sql_jdbc.execute$fn__78811.invokeStatic(execute.clj:382)
Feb 06 20:39:00at metabase.driver.sql_jdbc.execute$fn__78811.invoke(execute.clj:380)
Feb 06 20:39:00at clojure.lang.MultiFn.invoke(MultiFn.java:244)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$fn__81027$_AMPERSAND_f__81028.invoke(describe_database.clj:213)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$fn__81027$fn__81037.invoke(describe_database.clj:208)
Feb 06 20:39:00at metabase.driver.sql_jdbc$fn__107582.invokeStatic(sql_jdbc.clj:94)
Feb 06 20:39:00at metabase.driver.sql_jdbc$fn__107582.invoke(sql_jdbc.clj:92)
Feb 06 20:39:00at clojure.lang.MultiFn.invoke(MultiFn.java:234)
Feb 06 20:39:00at metabase.sync.fetch_metadata$db_metadata.invokeStatic(fetch_metadata.clj:15)
Feb 06 20:39:00at metabase.sync.fetch_metadata$db_metadata.invoke(fetch_metadata.clj:12)
Feb 06 20:39:00at metabase.sync.sync_metadata$sync_db_metadata_BANG_.invokeStatic(sync_metadata.clj:61)
Feb 06 20:39:00at metabase.sync.sync_metadata$sync_db_metadata_BANG_.invoke(sync_metadata.clj:58)
Feb 06 20:39:00at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invokeStatic(sync_databases.clj:94)
Feb 06 20:39:00at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invoke(sync_databases.clj:77)
Feb 06 20:39:00at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:113)
Feb 06 20:39:00at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:101)
Feb 06 20:39:00at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:118)
Feb 06 20:39:00at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
Feb 06 20:39:00at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Feb 06 20:39:002024-02-07 04:39:00,137 ERROR core.ErrorLogger :: Job (DEFAULT.metabase.task.sync-and-analyze.job threw an exception.
Feb 06 20:39:00org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.IllegalArgumentException: No matching clause: REVOKE INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON "metrics_user_telegraf".* FROM "doadmin"@"%"]
Feb 06 20:39:00at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
Feb 06 20:39:00at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Feb 06 20:39:00Caused by: java.lang.IllegalArgumentException: No matching clause: REVOKE INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON "metrics_user_telegraf".* FROM "doadmin"@"%"
Feb 06 20:39:00at metabase.driver.mysql$parse_grant.invokeStatic(mysql.clj:788)
Feb 06 20:39:00at metabase.driver.mysql$parse_grant.invoke(mysql.clj:766)
Feb 06 20:39:00at clojure.core$map$fn__5935.invoke(core.clj:2770)
Feb 06 20:39:00at clojure.lang.LazySeq.sval(LazySeq.java:42)
Feb 06 20:39:00at clojure.lang.LazySeq.seq(LazySeq.java:51)
Feb 06 20:39:00at clojure.lang.RT.seq(RT.java:535)
Feb 06 20:39:00at clojure.core$seq__5467.invokeStatic(core.clj:139)
Feb 06 20:39:00at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
Feb 06 20:39:00at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
Feb 06 20:39:00at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
Feb 06 20:39:00at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
Feb 06 20:39:00at clojure.core$reduce.invokeStatic(core.clj:6886)
Feb 06 20:39:00at clojure.core$group_by.invokeStatic(core.clj:7214)
Feb 06 20:39:00at clojure.core$group_by.invoke(core.clj:7214)
Feb 06 20:39:00at metabase.driver.mysql$privilege_grants_for_user.invokeStatic(mysql.clj:836)
Feb 06 20:39:00at metabase.driver.mysql$privilege_grants_for_user.invoke(mysql.clj:825)
Feb 06 20:39:00at metabase.driver.mysql$fn__104935.invokeStatic(mysql.clj:884)
Feb 06 20:39:00at metabase.driver.mysql$fn__104935.invoke(mysql.clj:872)
Feb 06 20:39:00at clojure.lang.MultiFn.invoke(MultiFn.java:234)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$schema_PLUS_table_with_select_privileges.invokeStatic(describe_database.clj:125)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$schema_PLUS_table_with_select_privileges.invoke(describe_database.clj:123)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$have_select_privilege_fn.invokeStatic(describe_database.clj:143)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$have_select_privilege_fn.invoke(describe_database.clj:131)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$post_filtered_active_tables.invokeStatic(describe_database.clj:186)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$post_filtered_active_tables.doInvoke(describe_database.clj:181)
Feb 06 20:39:00at clojure.lang.RestFn.applyTo(RestFn.java:142)
Feb 06 20:39:00at clojure.core$apply.invokeStatic(core.clj:667)
Feb 06 20:39:00at clojure.core$apply.invoke(core.clj:662)
Feb 06 20:39:00at metabase.driver.mysql$fn__104819.invokeStatic(mysql.clj:535)
Feb 06 20:39:00at metabase.driver.mysql$fn__104819.doInvoke(mysql.clj:533)
Feb 06 20:39:00at clojure.lang.RestFn.invoke(RestFn.java:457)
Feb 06 20:39:00at clojure.lang.MultiFn.invoke(MultiFn.java:244)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$fn__81027$_AMPERSAND_f__81028$fn__81029$default_active_tbl_fn__81030.invoke(describe_database.clj:221)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$fn__81027$_AMPERSAND_f__81028$fn__81029.invoke(describe_database.clj:233)
Feb 06 20:39:00at metabase.driver.sql_jdbc.execute$fn__78811$fn__78812.invoke(execute.clj:388)
Feb 06 20:39:00at metabase.driver.sql_jdbc.execute$fn__78776$_AMPERSAND_f__78777.invoke(execute.clj:334)
Feb 06 20:39:00at metabase.driver.sql_jdbc.execute$fn__78776$fn__78780.invoke(execute.clj:317)
Feb 06 20:39:00at metabase.driver.sql_jdbc.execute$fn__78811.invokeStatic(execute.clj:382)
Feb 06 20:39:00at metabase.driver.sql_jdbc.execute$fn__78811.invoke(execute.clj:380)
Feb 06 20:39:00at clojure.lang.MultiFn.invoke(MultiFn.java:244)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$fn__81027$_AMPERSAND_f__81028.invoke(describe_database.clj:213)
Feb 06 20:39:00at metabase.driver.sql_jdbc.sync.describe_database$fn__81027$fn__81037.invoke(describe_database.clj:208)
Feb 06 20:39:00at metabase.driver.sql_jdbc$fn__107582.invokeStatic(sql_jdbc.clj:94)
Feb 06 20:39:00at metabase.driver.sql_jdbc$fn__107582.invoke(sql_jdbc.clj:92)
Feb 06 20:39:00at clojure.lang.MultiFn.invoke(MultiFn.java:234)
Feb 06 20:39:00at metabase.sync.fetch_metadata$db_metadata.invokeStatic(fetch_metadata.clj:15)
Feb 06 20:39:00at metabase.sync.fetch_metadata$db_metadata.invoke(fetch_metadata.clj:12)
Feb 06 20:39:00at metabase.sync.sync_metadata$sync_db_metadata_BANG_.invokeStatic(sync_metadata.clj:61)
Feb 06 20:39:00at metabase.sync.sync_metadata$sync_db_metadata_BANG_.invoke(sync_metadata.clj:58)
Feb 06 20:39:00at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invokeStatic(sync_databases.clj:94)
Feb 06 20:39:00at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invoke(sync_databases.clj:77)
Feb 06 20:39:00at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:113)
Feb 06 20:39:00at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:101)
Feb 06 20:39:00at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:118)
Feb 06 20:39:00at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
Feb 06 20:39:00... 1 more
Feb 06 20:54:002024-02-07 04:54:00,036 INFO task.refresh-slack-channel-user-cache :: Slack is not configured, not refreshing slack user/channel cache.
Feb 06 21:00:002024-02-07 05:00:00,047 INFO task.send-pulses :: Sending scheduled pulses...

**To Reproduce**
1. Use Metabase v0.48.4 or v0.48.5 and connect to DigitalOcean managed MySQL 8.
2. Create a new table in MySQL.
3. Click on "Sync database schema now" and newly created table does not show up. Also, if ti's a newly added database, the Syncing tables just continues to spin without stopping.

**Expected behavior**
I am expecting to create new DB tables and have it show up in Metabase after I've clicked on "Sync database schema now" and "Re-scan field values now"

**Screenshots**
New DB table (woh_distribution_center) shows up in SQL query
![image](https://github.com/metabase/metabase/assets/5340486/da1eca49-0cbf-4794-b333-7b138a217a74)

But it (Woh Distribution Center) does not show up here
![image](https://github.com/metabase/metabase/assets/5340486/1c6d436a-f6ae-430e-a388-8b70c3be707b)

nor here
![image](https://github.com/metabase/metabase/assets/5340486/14508a35-43a8-40db-9036-d8d5cd5f0f3f)

**Severity**
This is a very severe issue as it is preventing me from completing new deliverables for my clients. It also creates doubts in my client's minds about the continued usage of Metabase.

**Additional context**
I am using Cloudron service hosted with DigitalOcean and using their managed MySQL Database version 8.0. When I tried using a locally hosted version (via Docker) of Metabase v0.48.4 with the DigitalOcean Managed MySQL Datbase, the Syncing tables notification just keeps going... I have to remove the database to stop the syncing.
![image](https://github.com/metabase/metabase/assets/5340486/7cfa3314-5b72-45b3-91d4-16114c8aa352)

When I tried to connect Metabase v0.48.4 from DigitalOcean to my local MariaDB (10.11.2-MariaDB-1:10.11.2+maria~ubu2204 - mariadb.org binary distribution), I do not have the same issue. It works fine.

Others are having similar issues:
https://discourse.metabase.com/t/this-database-doesnt-have-any-tables-mysql/73848
https://discourse.metabase.com/t/v0-48-4-bug/74410

**Metabase Diagnostic Info**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9-post-Ubuntu-0ubuntu122.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9-post-Ubuntu-0ubuntu122.04",
    "os.name": "Linux",
    "os.version": "5.15.0-92-generic",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-02-06",
      "tag": "v0.48.5",
      "hash": "dab12cf"
    },
    "settings": {
      "report-timezone": "America/Los_Angeles"
    }
  }
}
```

**Comment by paoliniluis** [comment] 2024-02-07 13:08
what's metrics_user_telegraf? a table? a view? a schema?
Are you completely sure that it's a MySQL 8 and not a fork or anything like that?

**Comment by paoliniluis** [comment] 2024-02-07 15:33
Can you run 
```
SHOW GRANTS FOR CURRENT_USER()
```
in your DB?

**Comment by jfang** [comment] 2024-02-07 16:27
Hi Luis,



Grants for doadmin@%

| GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CR... |
| GRANT REPLICATION_APPLIER,ROLE_ADMIN ON *.* TO "doadmin"@"%" WITH GRANT OPTION |
| REVOKE INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON "metrics_user_telegraf".* FROM "doadmin"@"%" |
| REVOKE INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON "mysql".* FROM "doadmin"@"%" |
| REVOKE INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON "sys".* FROM "doadmin"@"%" |


Thanks,
Jeff
    On Wednesday, February 7, 2024 at 07:33:37 AM PST, Luis Paolini ***@***.***> wrote:  
 
 


Can you run
SHOW GRANTS FOR CURRENT_USER()

in your DB?

**Comment by jfang** [comment] 2024-02-07 16:28
Hi Luis,
I'm not sure what metrics_user_telegraf is.
Your MySQL connection id is 87861Server version: 8.0.30 Source distribution



    On Wednesday, February 7, 2024 at 05:08:55 AM PST, Luis Paolini ***@***.***> wrote:  
 
 


what's metrics_user_telegraf? a table? a view? a schema?
Are you completely sure that it's a MySQL 8 and not a fork or anything like that?

**Comment by paoliniluis** [comment] 2024-02-07 18:18
I'm not able to reproduce what you're seeing. If you see one of the responses of the grants, you'll see a line of the error you post above
REVOKE INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON "metrics_user_telegraf".* FROM "doadmin"@"%"

**Comment by jfang** [comment] 2024-02-07 23:30
Thanks again for looking into this. I just installed a Docker instance of Metabase v0.48.3 on my local system and connected to DigitalOcean's managed MySQL 8 database. I did not have any issues connecting to the existing database tables and I was able to create new tables and Sync without issues. The Syncing tables took a few seconds to complete.

Screenshot from v.0.48.3
![image](https://github.com/metabase/metabase/assets/5340486/9c78c8d7-e97b-4150-b7c5-6318a80247e0)

I also installed the Docker instances of v0.48.4 and v0.48.5 on my local system and connected to DigitalOcean's managed MySQL database. For these two instances, when I click on Browse data and select my "Test" database, it is not able to see any tables  The Syncing... notification shows Syncing tables... and continues to spin. See below. Something changed between v0.48.3 to v0.48.4.

Screenshot from v0.48.4
![image](https://github.com/metabase/metabase/assets/5340486/f2d12944-3517-4545-bb08-4ec65e4dd277)

Screenshot from v0.48.5
![image](https://github.com/metabase/metabase/assets/5340486/7ad8b6aa-e656-42e0-a9b8-3dacdf420016)

I tried "+ New" > "SQL query" with a SELECT statement (for both v0.48.4 and v0.48.5) and was able to see the data in the table "sales_orders", eventhough it is still trying to sync.
![image](https://github.com/metabase/metabase/assets/5340486/786a1b85-84ff-4242-8a6b-a57e2163645b)

I did not change any settings in MySQL 8 on DigitalOcean or updates to the MySQL user permissions.

**Comment by crisptrutski** [comment] 2024-02-12 14:11
This issue should be fixed in the upcoming 0.48.6 release

**Comment by jfang** [comment] 2024-02-12 15:12
Thank you!

**Comment by lbrdnk** [comment] 2024-02-13 09:05
Fixed by #38552.

**Closed by lbrdnk** 2024-02-13 09:05 UTC
