### ISSUE TITLE
Unexpected character ('g' (code 103)) in Map

### ISSUE THREAD

**Issue by bestpika** [metabase/metabase#12993] opened 2020-07-24 08:49 UTC
**Describe the bug**

I loaded some geojson files in a previous version. But in the new version there is an error and I can't do anything (including delete) when it happens.

**Logs**

```
{:via
[{:type java.lang.Exception, :message "無法將對應資源轉換為JSON格式：`http://localhost/share/LE3-AREA1.geojson`", :at [metabase.api.geojson$valid_json_url_string_QMARK_ invokeStatic "geojson.clj" 73]}
{:type com.fasterxml.jackson.core.JsonParseException,
:message "Unexpected character ('g' (code 103)): was expecting comma to separate Object entries\n at [Source: (BufferedReader); line: 7, column: 260]",
:at [com.fasterxml.jackson.core.JsonParser _constructError "JsonParser.java" 1804]}],
:trace
[[com.fasterxml.jackson.core.JsonParser _constructError "JsonParser.java" 1804]
[com.fasterxml.jackson.core.base.ParserMinimalBase _reportError "ParserMinimalBase.java" 669]
[com.fasterxml.jackson.core.base.ParserMinimalBase _reportUnexpectedChar "ParserMinimalBase.java" 567]
[com.fasterxml.jackson.core.json.ReaderBasedJsonParser _skipComma "ReaderBasedJsonParser.java" 2271]
[com.fasterxml.jackson.core.json.ReaderBasedJsonParser nextToken "ReaderBasedJsonParser.java" 664]
[cheshire.parse$parse_STAR_ invokeStatic "parse.clj" 63]
[cheshire.parse$parse_STAR_ invoke "parse.clj" 61]
[cheshire.parse$parse_STAR_ invokeStatic "parse.clj" 63]
[cheshire.parse$parse_STAR_ invoke "parse.clj" 61]
[cheshire.parse$parse_STAR_ invokeStatic "parse.clj" 64]
[cheshire.parse$parse_STAR_ invoke "parse.clj" 61]
[cheshire.parse$parse_STAR_ invokeStatic "parse.clj" 63]
[cheshire.parse$parse_STAR_ invoke "parse.clj" 61]
[cheshire.parse$parse invokeStatic "parse.clj" 98]
[cheshire.parse$parse invoke "parse.clj" 86]
[cheshire.core$parse_stream invokeStatic "core.clj" 250]
[cheshire.core$parse_stream invoke "core.clj" 232]
[cheshire.core$parse_stream invokeStatic "core.clj" 246]
[cheshire.core$parse_stream invoke "core.clj" 232]
[metabase.api.geojson$valid_json_QMARK_$fn__56822$fn__56823 invoke "geojson.clj" 31]
[metabase.util$do_with_timeout$fn__10195 invoke "util.clj" 310]
[clojure.core$binding_conveyor_fn$fn__5754 invoke "core.clj" 2030]
[clojure.lang.AFn call "AFn.java" 18]
[java.util.concurrent.FutureTask run nil -1]
[java.util.concurrent.ThreadPoolExecutor runWorker nil -1]
[java.util.concurrent.ThreadPoolExecutor$Worker run nil -1]
[java.lang.Thread run nil -1]],
:cause "Unexpected character ('g' (code 103)): was expecting comma to separate Object entries\n at [Source: (BufferedReader); line: 7, column: 260]",
:message "無法將對應資源轉換為JSON格式：`http://localhost/share/LE3-AREA1.geojson`",
:type java.lang.Exception}
```

**To Reproduce**

1. Go to 'admin/settings/maps'
1. Click on any item
1. See error

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/5698157/88374663-b318f080-cdcc-11ea-863e-800b7570d70d.png)

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "zh-TW",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_261-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_261",
    "java.vm.name": "Java HotSpot(TM) Client VM",
    "java.vm.version": "25.261-b12",
    "os.name": "Windows Server 2016",
    "os.version": "10.0",
    "user.language": "zh",
    "user.timezone": "Asia/Taipei"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.36.0",
      "date": "2020-07-21",
      "branch": "release-0.36.x",
      "hash": "b31049f"
    },
    "settings": {
      "report-timezone": "Asia/Taipei"
    }
  }
}
```

**Severity**

This is a critical error, I can't delete any problematic map data while this error is occurring.

**Additional context**

[LE3-AREA1.zip](https://github.com/metabase/metabase/files/4970983/LE3-AREA1.zip)

**Comment by flamber** [comment] 2020-07-24 09:40
Hi @bestpika 
The file is invalid - check with http://geojson.io
Duplicate of #12599

**Closed by flamber** 2020-07-24 09:40 UTC
Labels: .Needs Triage, Type:Bug
