### ISSUE TITLE
Several joins on the same table

### ISSUE THREAD

**Issue by Philippe-M** [metabase/metabase#18005] opened 2021-09-22 12:41 UTC
Hello,

Is it possible with the query editor to create joins on the same table. For example :

```
SELECT * FROM sorder s
INNER JOIN sorderq s1 ON s1.sohnum = s.sohnum
INNER JOIN sorderp s2 ON s2.sohnum = s1.sohnum AND s2.itmref = s1.itmref AND s2.soplin = s1.soplin AND s2.soqseq = s1.soqseq
```

For the moment when I go through the query editor I have as much inner join as I have join.

**Comment by flamber** [comment] 2021-09-22 13:08
Duplicate of #11375

**Closed by flamber** 2021-09-22 13:08 UTC
Labels: Type:Question, .Needs Triage
