### ISSUE TITLE
Feature Request: SQL formatter

### ISSUE THREAD

**Issue by mickeyreiss** [metabase/metabase#15479] opened 2021-04-04 19:19 UTC
This is a feature request for the `Write SQL` feature. It would be great if there was a way to auto-format my SQL input.

It would be nice if this had a button as well as a keyboard shortcut (for example, BigQuery uses Cmd+Shift+F).

For this to be useful, it would need to be aware of SQL dialects and variations in code style.

It seems likely to me that many implementations of automatic code formatting would also give inline syntax errors and fix-its as well, which might be nice to have too.

**Comment by flamber** [comment] 2021-04-04 19:31
Duplicate of #9142

**Closed by flamber** 2021-04-04 19:31 UTC
Labels: .Needs Triage, Type:New Feature
