### ISSUE TITLE
How to disable access to some of the large tables

### ISSUE THREAD

**Issue by kandadaboggu** [metabase/metabase#3006] opened 2016-07-22 15:50 UTC
Yesterday, I provided access to our follower PostgreSQL database to a MetaBase instance. I have few extremely large tables in the database. I had made sure I didn't add any questions that accesses these large tables.
Few hours later, our  DBA's noticed that several long running queries on the database. They were trying to access the large tables.

Does Metabase access all the tables even when there are no questions on the tables? How do I stop this from happening?

*  I am using the Chrome browser.
*  My computer's OS is MacOSX.
*  I'm running Metabase on Herkou / etc.] and it is using the Postgres database.
*  My data is in a Postgres database. 
*  My Metabase version is v0.18.1.

**Comment by salsakran** [comment] 2016-07-22 16:58
We scan your tables to build an internal model of your data. We currently only offer DB wide controls on this via the toggle at the bottom of a database connection detail view eg

![screen shot 2016-07-22 at 9 59 35 am](https://cloud.githubusercontent.com/assets/107439/17064680/a0612cde-4ff2-11e6-9378-c3a4701a1ac2.png)

It's definitely something we need to get smarter about. We use the scans to do things like populate lists of filterable values for fields, try to guess semantic types, etc. A lot of the Metabase "magic" depends on it, but it's obviously hard to do on larger tables.

**Comment by kandadaboggu** [comment] 2016-07-22 17:12
I had changed the visibility on the large tables. I was expecting the in-depth analysis to be skipped for them. May be it is better to honor the visibility rules while performing the analysis.

Also, what type of content gets stored in the MetaBase DB while performing analysis? Do I need to increase the size of the database to match the production database size?

**Comment by salsakran** [comment] 2016-07-22 17:16
Relatively little is stored. We run through a sample of your rows, try go guess things based on the distributions, etc. We'll store the field values for low cardinality rows (which we use to populate dropdowns for filters). 

The main thing that uses up space in the application database is our activity and query execution logs (which still fairly). 

We've got an issue re: respecting visibility settings during sync's, #2127 and I'll close this as a dupe of that one.

**Closed by salsakran** 2016-07-22 17:16 UTC

**Comment by kandadaboggu** [comment] 2016-07-22 21:54
I disabled the In-depth analysis. But I still see these messages in the logs.

```
2016-07-22T21:50:01.306630+00:00 app[web.1]: 07-22 21:50:01 INFO sync-database.introspect :: [*******************·······························] 😐   38% Synced table 'public.table1'.
2016-07-22T21:50:01.333574+00:00 app[web.1]: 07-22 21:50:01 INFO sync-database.introspect :: [*******************·······························] 😐   40% Synced table 'public.table2'.
2016-07-22T21:50:01.369212+00:00 app[web.1]: 07-22 21:50:01 INFO sync-database.introspect :: [********************······························] 😐   41% Synced table 'public.table3'.
2016-07-22T21:50:01.375509+00:00 app[web.1]: 07-22 21:50:01 WARN driver.generic-sql :: Don't know how to map column type '_text' to a Field base_type, falling back to :UnknownField.
2016-07-22T21:50:01.375692+00:00 app[web.1]: 07-22 21:50:01 WARN driver.generic-sql :: Don't know how to map column type '_text' to a Field base_type, falling back to :UnknownField.
2016-07-22T21:50:01.376029+00:00 app[web.1]: 07-22 21:50:01 WARN driver.generic-sql :: Don't know how to map column type 'hstore' to a Field base_type, falling back to :UnknownField.
2016-07-22T21:50:01.423698+00:00 app[web.1]: 07-22 21:50:01 INFO sync-database.introspect :: [*********************·····························] 😐   43% Synced table 'public.table4'.
2016-07-22T21:50:01.453933+00:00 app[web.1]: 07-22 21:50:01 INFO sync-database.introspect :: [**********************····························] 😐   44% Synced table 'public.table5'.
2016-07-22T21:50:01.490238+00:00 app[web.1]: 07-22 21:50:01 INFO sync-database.introspect :: [**********************····························] 😐   46% Synced table 'public.table6'.
2016-07-22T21:50:01.545198+00:00 app[web.1]: 07-22 21:50:01 INFO sync-database.introspect :: [***********************···························] 😬   47% Synced table 'public.table7'.
2016-07-22T21:50:01.550715+00:00 app[web.1]: 07-22 21:50:01 WARN driver.generic-sql :: Don't know how to map column type '_int4' to a Field base_type, falling back to :UnknownField.
2016-07-22T21:50:01.551537+00:00 app[web.1]: 07-22 21:50:01 WARN driver.generic-sql :: Don't know how to map column type 'hstore' to a Field base_type, falling back to :UnknownField.
2016-07-22T21:50:03.225982+00:00 app[web.1]: 07-22 21:50:03 DEBUG sync-database.introspect :: Marking foreign key 'public.table1.table2_id' -> 'public.table2.id'.
```
Is this supposed to happen?

**Comment by camsaul** [comment] 2016-07-22 21:56
@kandadaboggu we have an open issue for that: #2127

**Comment by kandadaboggu** [comment] 2016-07-22 22:42
@camsaul So the analysis happens even if I disable In-Depth analysis?

**Comment by camsaul** [comment] 2016-07-22 22:42
yes @kandadaboggu, #2127 is to address that.

**Comment by camsaul** [comment] 2016-07-22 22:43
in-depth analysis won't happen if you disable it but basic analysis still happens
