### ISSUE TITLE
Download results (.csv, .json, .xlsx) request does not include subpath when deploying on subpath

### ISSUE THREAD

**Issue by mmovahedi** [metabase/metabase#33244] opened 2023-08-16 17:51 UTC
### Describe the bug

We have deployed Metabase on subpath behind nginx for example domain:
`https://example.com/metabase/`.

When we want to download results of a question or table of database, requests are sent to
`https://example.com` 
instead of 
`https://example.com/metabase/`.

I have set `MB_SITE_URL`.

Request full url:
`https://sub.example.com/api/card/1/query/csv`
Expected request url:
`https://sub.example.com/subpath/api/card/1/query/csv`

### To Reproduce

1. Deploy Metabase on subpath
2. Create a question
3. Click "Download full result" Icon
4. Get a 404 error.

### Information about your Metabase installation

```
- Chrome updated
- Ubuntu 22.04
- Postgres
- Metabase: latest version
- Docker community edition self-hosted
- Internal database: Postgres
```

### Severity

Blocking my usage

**Comment by nierob** [comment] 2023-08-18 09:35
It seems like  a regression introduced between v0.46.7 and  v0.47.0

**Comment by paoliniluis** [comment] 2023-08-24 12:52
So there seems to be a way in which everyone is using a reverse proxy and that might be wrong. Can you all post your reverse proxy configs? I'm using the one here and it does not fail https://github.com/paoliniluis/metabase-subpath

**Comment by nierob** [comment] 2023-08-25 06:26
We used to have:
```
traefik.http.middlewares.metabase-stripprefix.stripPrefix.prefixes=/metabase
traefik.http.routers.metabase.middlewares=default@file,metabase-stripprefix@consulcatalog
traefik.http.routers.metabase.rule=Path(`/{path:metabase(/.*)?}`)
```

and now we have a workaround for this bug using referer

```
traefik.http.middlewares.metabase-stripprefix.stripPrefix.prefixes=/metabase
traefik.http.routers.metabase.middlewares=default@file,metabase-stripprefix@consulcatalog
traefik.http.routers.metabase.rule=Path(`/{path:metabase(/.*)?}`) || HeadersRegexp(`Referer`, `^https:\\/\\/URL_BASE]]\\/metabase(/.*)?$`)
```

**Comment by mmovahedi** [comment] 2023-08-25 07:16
Nginx configuration we use:
```
listen 443 ssl http2;
listen [::]:443 ssl http2;

server_name example.com;

ssl_certificate /configs/ssl/fullchain.pem;
ssl_certificate_key /configs/ssl/privkey.pem;

server_tokens off;

gzip on;
gzip_proxied any;
gzip_comp_level 4;
gzip_types text/css application/javascript image/svg+xml;

location = /favicon.ico { access_log off; log_not_found off; }

location /metabase/ {
    proxy_pass http://127.0.0.1:8003/; # metabase local port
    
    proxy_buffers 32 4k;
    proxy_connect_timeout 240;
    proxy_headers_hash_bucket_size 128;
    proxy_headers_hash_max_size 1024;
    proxy_http_version 1.1;
    proxy_read_timeout 240;
    proxy_redirect  http://  $scheme://;
    proxy_send_timeout 240;
    
    proxy_set_header Early-Data $ssl_early_data;
    proxy_set_header Host $host;
    proxy_set_header Proxy "";
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_set_header X-Real-IP $remote_addr;
}
```

**Comment by paoliniluis** [comment] 2023-08-25 15:42
@mmovahedi please check https://github.com/paoliniluis/metabase-subpath which is the correct way of using a sub path. Your configuration will not rewrite the second part of the URL. Be aware that Metabase will be never aware it's running on a sub path unless we ship https://github.com/metabase/metabase/issues/30895

**Comment by mmovahedi** [comment] 2023-08-26 15:04
@paoliniluis I checked configs in [ https://github.com/paoliniluis/metabase-subpath](https://github.com/paoliniluis/metabase-subpath) 
In above configuration uses `last` which cause to redirect to `/` path (We have an other service served at root) and routing fails. So I used `break`. 
With `break` also problem still exist.
Our final nginx config:
```
location /mb/ {
    rewrite ^/mb(/.*)$ $1 break;
    proxy_pass http://127.0.0.1:8003/; # metabase local port
}
```

I do not think it is gateway problem as request generated by metabase does not include subpath. It isn't routing problem.

**Comment by mmovahedi** [comment] 2023-08-26 16:09
Something new I found about nginx [about proxy_pass](https://serverfault.com/a/725433):
The trailing `/` at end of proxy_pass will rewrite the location part. so it seems our first configs also do the write.

**Comment by gustavosobol** [comment] 2023-08-26 19:43
I agree that the solution that the configurations in https://github.com/paoliniluis/metabase-subpath do **not solve the problem** because, like @mmovahedi, we have another service served in the root... On the other hand, in versions prior to the 0.47.0 worked correctly... Today the export of data is working only through mail shipments... It would be very important to find a solution to this problem since I have clients that depend on these types of downloads

**Comment by nierob** [comment] 2023-08-28 06:31
Maybe it is about respecting `MB_SITE_URL` we set it to `https://example.com/metabase`?

**Comment by asimumba** [comment] 2023-08-28 06:59
Like everyone has mentioned. We too have a landing page served on the root of the subdomain. This issue arose after an upgrade to 0.47.0.

**Comment by ouquoi** [comment] 2023-08-31 07:52
Hello,
We experience the same issue after migrating from 0.46 to 0.47.
Thanks

**Comment by netanellusky** [comment] 2023-08-31 13:17
Hi,
I have same issue

**Comment by doublesea** [comment] 2023-09-01 03:16
same issue， v0.47

**Comment by TimMurnaghan** [comment] 2023-09-06 07:14
Yep me too. v0.47 This is a very severe regression. 
Are we going to have to re-host on a new dns name if site urls aren't supported?

**Comment by udit-001** [comment] 2023-09-06 14:25
Experiencing the same issue, unable to export data, the exported file says "not found"

**Comment by paoliniluis** [comment] 2023-09-06 14:40
We’re working on it

**Comment by gustavosobol** [comment] 2023-09-06 23:09
I wanted to share that when the question is shared it works correctly as well as when sending emails... the only way that doesn't work is the one we all mentioned... it's really tedious to have to change the urls due to this error.. Could it be that they are going to correct this problem? (Personally, it would be ideal if they made a correction).... How can I know that so I know which path I can take with my clients since I have daily queries about this problem... 
thank you very much

**Comment by paoliniluis** [comment] 2023-09-07 10:54
@TimMurnaghan Metabase was never designed to work on sub paths, we'll fix this issue but please consider moving Metabase to a subdomain rather than a subpath till https://github.com/metabase/metabase/issues/30895 is fixed. This will keep happening in the future as we don't have test coverage on this

**Comment by nierob** [comment] 2023-09-07 10:57
The documentation suggests that it is supported: [MB_SITE_URL](https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_site_url) explicitly mentions version with subpath.

**Comment by paoliniluis** [comment] 2023-09-07 11:31
We need to change that section of the documentation as currently subpaths is a hack rather than a supported deployment model

**Comment by paoliniluis** [comment] 2023-09-07 13:54
@TimMurnaghan the documentation is just cosmetics, Metabase was not designed from the beginning to run on sub paths and the results speak for themselves: we broke a thing we didn’t even know it existed because we don’t even have test coverage for this. We will fix this issue but you shouldn’t expect zero bugs from this in the future till we make it a supported feature.

**Comment by TimMurnaghan** [comment] 2023-09-08 17:13
>  We will fix this issue but you shouldn’t expect zero bugs from this in the future till we make it a supported feature.

I guess that makes it "reluctantly supported".
Any idea of when the fix might be? 
I see that's its labelled as P3 which is quite low for something which is also a Bug and a Regression. It's much higher for us in our use case - but given that you don't really want to do it I suppose that's not a surprise.

**Comment by paoliniluis** [comment] 2023-09-08 20:53
We’re currently working on it, our devs had to even set up an entire new dev env just to reproduce this since this was never on our scope, that’s why it’s taking this long

**Comment by ouquoi** [comment] 2023-09-09 12:27
We will switch as you suggest to migrate to subdomain.

**Comment by paoliniluis** [comment] 2023-09-11 15:35
I just checked the PR and it works, I would suggest every person in this thread to pull paoliniluis/metabase-subpath and test @ouquoi @TimMurnaghan @nierob @gustavosobol @udit-001 @doublesea @netanellusky @asimumba @danielmittelman @mmovahedi

**Comment by TimMurnaghan** [comment] 2023-09-12 15:46
I'd be happy to do some testing - but not quite sure how that JWT example would play with the rest of our config.
Is there a branch of metabase itself that I can pull?

**Comment by mmovahedi** [comment] 2023-09-12 21:53
I tested this branch and it is working:
https://github.com/metabase/metabase/tree/33244/download-results-subpath

Thanks for fix @paoliniluis @uladzimirdev

**Comment by paoliniluis** [comment] 2023-09-13 06:48
@TimMurnaghan please see my previous post

**Comment by TimMurnaghan** [comment] 2023-09-13 10:51
OK - got it thanks. Yes that works for us too.

**Comment by netanellusky** [comment] 2023-09-13 13:50
Now its working, thanks.

**Comment by gustavosobol** [comment] 2023-09-13 13:53
It works for us too.... thank you very much

**Comment by asimumba** [comment] 2023-09-15 13:05
@paoliniluis when can we expect the solution to be released as a patch fix?

**Comment by paoliniluis** [comment] 2023-09-15 15:20
next week

**Closed** 2023-09-18 15:05 UTC
Labels: Type:Bug, Priority:P3, Reporting/Export, .Regression, .Team/42 :milky_way:

**Comment by doublesea** [comment] 2023-09-19 01:41
tested in v0.47.2. it works well. 
Thanks very nuch

**Comment by nierob** [comment] 2023-09-19 07:53
Thank you for handling it in so nice way!

**Comment by gustavosobol** [comment] 2023-09-19 19:30
Geniuses!!! Thank you very much, the 47.2 update worked for us... many grateful users

**Comment by pphanwang** [comment] 2023-09-20 01:49
![image](https://github.com/metabase/metabase/assets/22736308/563d937e-5215-4290-909b-66d28a90b036)
 将http  改成https  解决问题

**Comment by ahnaf-tahmid-chowdhury** [comment] 2023-10-01 13:36
This is how I have solved my issue

```c
    location /metabase/ {
        proxy_pass http://localhost:3000/; 
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;  
        proxy_set_header   X-Forwarded-Host $host;
        proxy_redirect     ~^/(.*)$ /metabase/$1; 
    }
 ```
