### ISSUE TITLE
X-axis is hidden on histogram, when there's less than 7 results and x-axis is numeric

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13257] opened 2020-09-16 20:08 UTC
**Describe the bug**
When there's less than 7 results and the x-axis value type is numeric, then the x-axis is hidden. Setting the "Show x-axis line and marks" to "Compact" will make it show the x-axis again.

**To Reproduce**
1. Simple question > Sample Dataset > Orders
2. Summarize Count by Quantity:Unbinned - and Filter "Quantity" between `1` and `6` - and visualize as Line/Bar/Area/Scatter:
![image](https://user-images.githubusercontent.com/1447303/93385865-1e2ff200-f867-11ea-97aa-d50f3207e13a.png)
3. Changing visualization Settings > Axes > "Show x-axis line and marks" to "Compact" will show the axis:
![image](https://user-images.githubusercontent.com/1447303/93385938-3d2e8400-f867-11ea-9093-34ea29d615b4.png)

**Information about your Metabase Installation:**
Metabase 0.31.2, 0.35.4, 0.36.6

**Additional context**
Related to #7058 and #7310
https://discourse.metabase.com/t/column-names-disappear-when-the-number-of-columns-changes-v0-36-6/11623

**Comment by alxnddr** [comment] 2021-04-02 22:46
@flamber not sure if it is relevant anymore, I could not reproduce it on v0.38.3

**Comment by flamber** [comment] 2021-04-03 07:28
I can still reproduce on 0.38.3 and master:
![image](https://user-images.githubusercontent.com/1447303/113471754-d9645500-945e-11eb-8f04-49a8df09862e.png)

Changing to 7 results will show the axis:
![image](https://user-images.githubusercontent.com/1447303/113471760-e5e8ad80-945e-11eb-8216-d3a25bba88c6.png)

**Comment by alxnddr** [comment] 2021-04-16 20:20
Fixed by https://github.com/metabase/metabase/pull/15661

**Closed** 2021-04-16 20:20 UTC
Labels: Browser:Firefox, Priority:P3, Type:Bug, Visualization/Charts
