### ISSUE TITLE
Request for Internationalization of Email and Notification Templates in Metabase

### ISSUE THREAD

**Issue by Sulecio** [metabase/metabase#38420] opened 2024-02-03 05:28 UTC
Dear Metabase Development Team,

I hope this message finds you well. I am reaching out to you as an enthusiastic user of Metabase to express a suggestion that I believe would significantly enhance the user experience worldwide: the internationalization of email and notification templates.

Currently, I have noticed that these templates, such as "new_user_invite.mustache" and others, are exclusively in English. This limitation poses a barrier for those users who prefer or need to interact with Metabase in other languages. As part of a global community of users, I firmly believe that including internationalization in these templates would be a major step forward in making Metabase truly accessible and adaptable to diverse linguistic and cultural needs.

I understand that this development may require additional resources, but I believe the resulting benefits in terms of user satisfaction and expansion of the user base fully justify the investment. Full internationalization of Metabase not only in the user interface but also in automated communications would be a significant advancement that would enhance the overall user experience and strengthen Metabase's position as a leading data analytics solution.

Therefore, I kindly urge you to consider this request and include the internationalization of email and notification templates in your future development roadmap. I am confident that many users, like myself, would greatly appreciate this effort on your team's part.

I am available to provide any further clarification you may need. I sincerely appreciate your attention to this matter and look forward to seeing how Metabase continues to evolve to meet the needs of its diverse user base.

Best regards
Joel Sulecio

**Comment by paoliniluis** [comment] 2024-02-06 14:34
Duplicate of https://github.com/metabase/metabase/issues/7535

**Closed by paoliniluis** 2024-02-06 14:34 UTC
Labels: Type:New Feature, .Needs Triage
