### ISSUE TITLE
Joining Model in question editor loses Model Name and defaults to Question Number when trying to filter

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#27795] opened 2023-01-20 14:07 UTC
**Describe the bug**
When you join to a model in the UI, then try to filter / aggregate etc., the model's name changes to the format of Question 1234 rather than the original model name.

**To Reproduce**
1. Go to New -> Question -> Sample Database -> Products -> Save -> Turn to a model
2. Go to New -> Question -> Sample Database -> Orders -> Join Model Products on Orders.Product_ID = Model.ID 
3. Try to setup a filter and notice that the Model Name is now Question 1234

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/110378427/213714399-aa259fa1-b384-462e-a649-15426a35611d.png">

5. Doesn't happen if you join a Data source with a Model:

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/110378427/213713834-f7b1f556-74be-4282-9047-97bc9517b70a.png">

**Expected behavior**
Keep the Model name so it doesn't confuse customers

**Information about your Metabase Installation:**

Able to replicate on both Master and 45.2

**Comment by sketchings** [comment] 2023-05-22 23:47
<img width="84" alt="Screenshot 2023-05-22 at 4 46 22 PM" src="https://github.com/metabase/metabase/assets/1067121/c96f73a7-73a8-40e7-a503-ccffdf44532f">

<img width="704" alt="Screenshot 2023-05-22 at 4 45 36 PM" src="https://github.com/metabase/metabase/assets/1067121/e5ceefb7-a126-41e9-8f5e-4803e7f6f6ca">

We are running into this same issue, it also shows numbers in the filter and summarize sections.

This makes Models almost useless seeing as there are supposed to "Simplify your schema" but actually make it more confusing because they show a useless number instead of a name

**Comment by sketchings** [comment] 2023-05-24 22:54
It seems to behave better if the Model is based off SQL instead of a "Questions". 

You can:

1. "Turn back to saved question"
2. "View the SQL"
3. "Convert this Question to SQL"
4. *OPTIONAL* simplify the SQL if desired
5. "Turn into a model" again

This seems to keep the same model number, so it should keep the "Used by" questions. However, you may need to refresh or redo those questions

**Comment by iethree** [comment] 2023-10-17 21:11
duplicate of https://github.com/metabase/metabase/issues/21646

**Comment by camsaul** [comment] 2023-10-19 02:48
Duplicate of #21646

**Closed by camsaul** 2023-10-19 02:48 UTC
Labels: Type:Bug, Priority:P2, Querying/Notebook, Querying/Models, .Team/QueryProcessor, .Wanted: MLv2
