### ISSUE TITLE
Don't round values on data points in some cases

### ISSUE THREAD

**Issue by dacort** [metabase/metabase#11686] opened 2020-01-10 22:12 UTC
**Is your feature request related to a problem? Please describe.**
When using the "show values on data points" feature in 0.34, there's some automatic rounding that happens that can sometimes lead to a confusing visual.

**Describe the solution you'd like**
Allow me to disable rounding, or have the "minimum number of decimal places" be reflected in the data point values.

**Describe alternatives you've considered**
Tried setting minimum number of decimal places, but it had no effect.

**How important is this feature to you?**
n/a

**Additional context**
Here's a sample query that reproduces this:

```sql
SELECT 'a' as x, 3.2 as anumber
UNION ALL
SELECT 'b', 3.4 
```

If I run that query and make a line chart, you can see that even though the slope is increasing, both numbers are shown as "3".

![image](https://user-images.githubusercontent.com/1512/72189839-c5908700-33b2-11ea-9949-0e70fc6b4652.png)

If I change the Y axis to show a minimum number of 1 decimal points, the axis labels update but the data point labels do not.

![image](https://user-images.githubusercontent.com/1512/72189890-eb1d9080-33b2-11ea-81f7-d2b1708ddfd6.png)

Originally reported in [Discourse](https://discourse.metabase.com/t/rounding-values-incorrectly/8612).

**Comment by paulrosenzweig** [comment] 2020-01-10 22:14
I think this is a dupe of #11565

**Comment by dacort** [comment] 2020-01-10 22:20
Oh yep, you're right. Will close this in favor of that one.

**Closed** 2020-01-10 22:20 UTC
Labels: .Duplicate, .Enhancement, Priority:P2, Type:Completeness, Type:New Feature, Visualization/Charts
