### ISSUE TITLE
Variables appearing like {0} on the UI

### ISSUE THREAD

**Issue by adventuresnick** [metabase/metabase#17717] opened 2021-09-01 14:55 UTC
**Describe the bug**
Some variables on the UI appear like {0} instead of the actual value of them.

**Logs**
I got some logs from the Chrome console:
[dados.gsoul.com.br-1630505316092.log](https://github.com/metabase/metabase/files/7091705/dados.gsoul.com.br-1630505316092.log)

**To Reproduce**
To be honest, in my case, just go to any board or page on the UI that have some variables concatenated on the text

**Expected behavior**
To the values to appear correctly.

**Screenshots**
Yes, it is in Portuguese, Brasil.
![image](https://user-images.githubusercontent.com/84153574/131687423-336f3269-78f3-411a-b8d7-23d00203a0de.png)
![image](https://user-images.githubusercontent.com/84153574/131687453-58d019ba-7eb7-47ca-998c-40e09f7886d5.png)
![image](https://user-images.githubusercontent.com/84153574/131689580-f76b1d84-1ead-47ff-9413-9d28d76ac01a.png)

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 92.0.4515.159
- Your operating system: Ubuntu 20.04
- Your databases: BigQuery
- Metabase version: v0.40.2
- Metabase hosting environment: Compute Engine - GCP
- Metabase internal database: PostgreSQL

Here is the JSON that contains the troubleshooting data.
[data.txt](https://github.com/metabase/metabase/files/7091875/data.txt)

**Severity**
The problem affects the final usability of Metabase, and as you guys can see on the screenshots, important information is not delivered to our final user, causing confusion and frustration. 

**Additional context**
I've checked in other browsers and the problem appears there too.

**Comment by flamber** [comment] 2021-09-01 15:24
Duplicate of #16690 - see details for workaround.

**Closed by flamber** 2021-09-01 15:24 UTC
Labels: Type:Bug, .Needs Triage

**Comment by adventuresnick** [comment] 2021-09-01 16:40
Thanks @flamber !
