### ISSUE TITLE
Dashboard list filter doesn't display values.  

### ISSUE THREAD

**Issue by ElVidrah** [metabase/metabase#12644] opened 2020-06-03 12:56 UTC
**Describe the bug**
When creating dashboards filters with more than 100 entries, the filter doesn't display any values. 
![image](https://user-images.githubusercontent.com/8224517/83637969-b5b75080-a5a8-11ea-9236-05594a69df0c.png)
the filter should be full of values, but is empty instead. 
By default metabase changes the filter type to search type filter but you can override the change in the data model . 
For reference my column has 564 unique entries I want to filter them by using a list of all values filter. 
This happens regardless if the chart is made with SQL or simple question builder. 
**Logs**
I get the following JS error repeated multiple times:
![image](https://user-images.githubusercontent.com/8224517/83638291-3d9d5a80-a5a9-11ea-859f-9ed4b830974a.png)

**To Reproduce**
1. Create a table with a column that has more than 100 unique entries. 
2. Put it on a dashboard, create a filter and bind the column and filter together.
3. Go to the data model for and change filtering on this field to: A list of all values
4. Discard cached field values and re-scan this field. (to ensure you start from clean slate)
5. Go to dashboard: You should see a empty search the list filter without ability to search. *picture above

**Expected behavior**
A list filter with values you can click/search like this:
 
![image](https://user-images.githubusercontent.com/8224517/83638885-2317b100-a5aa-11ea-8b39-cd13e5a9133e.png)

**Severity**
It's annoying but not severe. people will have to use a search-box type filter.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10-post-Debian-3deb10u1",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10-post-Debian-3deb10u1",
    "os.name": "Linux",
    "os.version": "4.19.0-9-amd64",
    "user.language": "en",
    "user.timezone": "Europe/Ljubljana"
  },
  "metabase-info": {
    "databases": [
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.20"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-21",
      "tag": "v0.35.3",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": "Europe/Athens"
    }
  }
}
```

**Comment by flamber** [comment] 2020-06-03 13:03
Hi @ElVidrah 
There's a limit of 300 (if I remember correctly), then a List is converted into a Search instead.
Duplicate of #7603 - upvote by clicking :+1: on the first post

**Closed by flamber** 2020-06-03 13:03 UTC

**Comment by ElVidrah** [comment] 2020-06-03 13:16
Hi @flamber 
Thanks for the quick reply! 
I also tried to create a table with 200 entries using this SQL statement:
```
 SELECT TOP 200 dbo.Accounts.AccountName
FROM dbo.Accounts
WHERE {{AccountName}}
```
And got the same result …

**Comment by flamber** [comment] 2020-06-03 13:33
@ElVidrah But that's not a limit of the entries in the dropdown - that's a limit of your results of that question. Metabase does a scan of unique values and stores them in the Metabase application database (MySQL in your case) in the table `metabase_fieldvalues`, which is used for the dropdown and search. It all gets fairly technical and nitty gritty at that level. But we do have a bug in the conversion from dropdown to search, it doesn't behave like regular search does. That's #7603
Just for reference: https://www.metabase.com/docs/latest/administration-guide/01-managing-databases.html#database-sync-and-analysis
