### ISSUE TITLE
Language Issue on Filters Commands

### ISSUE THREAD

**Issue by JoaoCioffi** [metabase/metabase#38568] opened 2024-02-08 17:54 UTC
### Describe the bug

Metabase has language setup and it works at some features. By the way while selecting some data entries for example the language remains in English (default). I changed for Portuguese-BR and some words changed at translation, but other features remain showing the English version as the print below:

![Screenshot from 2024-02-08 14-41-15](https://github.com/metabase/metabase/assets/60454486/75e98a7e-1758-4164-9dde-cc41b270ea69)

Here the default value needs to be "Passados 30 dias", but stead of this it displays "Previous 7 dias" -> It combines the 2 languages in a single text.

Further info:

![image](https://github.com/metabase/metabase/assets/60454486/1b1c647f-54b9-4857-801f-84f37038eb7e)

The error/bug happens also at settings button as shown above

### To Reproduce

1. Change the default language at Admin Settings or User Settings to a different language than English (e.g Portuguese-BR)
1. Go to any data filter (it needs to be available on all options, e.g specific dates, relative dates, etc)
2. Click on "Últimos 7 dias" (stands for "previous 7 days")
3. Scroll to the filter box

### Expected behavior

Displays the entire text in an unique language (the selected one)

### Information about your Metabase installation

```JSON
- running at Brave Browser Version 1.62.156 Chromium: 121.0.6167.139 (Official Build) (64-bit)
- OS: Ubuntu 22.04.3 LTS x86_64
- DB: Postgres
- Metabase v1.48.3
```

### Severity

Urgent / High

**Comment by paoliniluis** [comment] 2024-02-09 13:49
duplicate of https://github.com/metabase/metabase/issues/13188

are you using Metabase Pro/enterprise? if that's the case please contact support so we can identify the user and tag it

**Closed by paoliniluis** 2024-02-09 13:49 UTC
Labels: Type:Bug, .Needs Triage

**Comment by JoaoCioffi** [comment] 2024-02-09 14:24
Thanks for the comment @paoliniluis, yes I'm using Metabase Pro.
