### ISSUE TITLE
Going to some old question hashes on `master` fails with a blank screen

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15372] opened 2021-03-29 14:00 UTC
**Describe the bug**
If you have bookmarked unsaved question hash links (`/question#eyJkYX...`), which are created in pre-0.39 and then try to open one of those URLs on 0.39 (master), then the UI navbar flashes for a split second and then the page goes completely blank.

**To Reproduce**
(IDs will be different for other instances, so adjust throughout accordingly)
1. Custom question > Sample Dataset > Create a question like this (without saving)
![image](https://user-images.githubusercontent.com/1447303/112841046-52029480-90a0-11eb-8fd5-a08cd72b3b3c.png)
2. On 0.38.2 it will generate a question hash like this (bookmark this URL):
```
eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoxLCJxdWVyeSI6eyJzb3VyY2UtcXVlcnkiOnsic291cmNlLXRhYmxlIjoxLCJhZ2dyZWdhdGlvbiI6W1siY291bnQiXV0sImJyZWFrb3V0IjpbWyJmaWVsZC1pZCIsNl1dfSwiYWdncmVnYXRpb24iOltbImF2ZyIsWyJmaWVsZC1saXRlcmFsIiwiY291bnQiLCJ0eXBlL0ludGVnZXIiXV1dfSwidHlwZSI6InF1ZXJ5In0sImRpc3BsYXkiOiJzY2FsYXIiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=

Decoded:
{"dataset_query":{"database":1,"query":{"source-query":{"source-table":1,"aggregation":[["count"]],"breakout":[["field-id",6]]},"aggregation":[["avg",["field-literal","count","type/Integer"]]]},"type":"query"},"display":"scalar","visualization_settings":{}}
```
3. On `master` it will generate a question hash like this:
```
eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoxLCJxdWVyeSI6eyJzb3VyY2UtcXVlcnkiOnsic291cmNlLXRhYmxlIjoxLCJhZ2dyZWdhdGlvbiI6W1siY291bnQiXV0sImJyZWFrb3V0IjpbWyJmaWVsZCIsNixudWxsXV19LCJhZ2dyZWdhdGlvbiI6W1siYXZnIixbImZpZWxkIiwiY291bnQiLHsiYmFzZS10eXBlIjoidHlwZS9JbnRlZ2VyIn1dXV19LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InNjYWxhciIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==

Decoded:
{"dataset_query":{"database":1,"query":{"source-query":{"source-table":1,"aggregation":[["count"]],"breakout":[["field",6,null]]},"aggregation":[["avg",["field","count",{"base-type":"type/Integer"}]]]},"type":"query"},"display":"scalar","visualization_settings":{}}
```
4. Notice that `"breakout"` and second `"aggregation"` is different between step 2 on 0.38.2 and step 3 on `master`
5. On `master`, when visiting the bookmarked URL from step 2 (0.38.2), then the UI navigation bar quickly flashes and the page goes blank:
![Screencast-2021-03-29_15 43 58](https://user-images.githubusercontent.com/1447303/112846033-dc99c280-90a5-11eb-90e0-3e9282cc858e.gif)
The browser console errors with:
```
Uncaught (in promise) TypeError: Cannot read property 'columnName' of null
    at app-main.bundle.js?f5d8c3a4e37630fba187:5
    at Array.map (<anonymous>)
    at t.value (app-main.bundle.js?f5d8c3a4e37630fba187:5)
    at app-main.bundle.js?f5d8c3a4e37630fba187:5
    at i (app-main.bundle.js?f5d8c3a4e37630fba187:5)
    at t.n.value (app-main.bundle.js?f5d8c3a4e37630fba187:5)
    at t.value (app-main.bundle.js?f5d8c3a4e37630fba187:5)
    at t.value (app-main.bundle.js?f5d8c3a4e37630fba187:5)
    at app-main.bundle.js?f5d8c3a4e37630fba187:5
    at i (app-main.bundle.js?f5d8c3a4e37630fba187:5)
```
I also got this error at one point, but forgot how I ended up with that:
```
Uncaught (in promise) Error: Unknown MBQL clause ["field-literal","count","type/Integer"]
    at s (app-main.bundle.js?f5d8c3a4e37630fba187:5)
    at app-main.bundle.js?f5d8c3a4e37630fba187:5
    at Array.map (<anonymous>)
    at app-main.bundle.js?f5d8c3a4e37630fba187:5
    at s (app-main.bundle.js?f5d8c3a4e37630fba187:5)
    at t.value (app-main.bundle.js?f5d8c3a4e37630fba187:5)
    at Array.value (app-main.bundle.js?f5d8c3a4e37630fba187:5)
    at app-main.bundle.js?f5d8c3a4e37630fba187:5
    at Array.map (<anonymous>)
    at t.default (app-main.bundle.js?f5d8c3a4e37630fba187:5)
```

**Expected behavior**
Don't explode - show the question with broken fields, so I can manually fix it, if it cannot be done automatically.
And at least don't go blank - ever.

**Information about your Metabase Installation:**
`master` commit `d6765a1`

**Severity**
I'm not sure if this can happen for anything besides the steps I've added - if yes, then it's a definite P1

**Comment by paulrosenzweig** [comment] 2021-04-05 15:40
This is caused by #15079. It's probably a dupe but this title is more likely to be found by a user, so maybe it's good to keep it open.

**Comment by alxnddr** [comment] 2021-04-07 16:25
Closed by https://github.com/metabase/metabase/pull/15497

**Closed by alxnddr** 2021-04-07 16:25 UTC
Labels: .Frontend, .Regression, .Reproduced, Priority:P2, Querying/GUI, Type:Bug
