### ISSUE TITLE
[P1] Pages take a long time to be considered loaded, even if empty

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26730] opened 2022-11-24 12:07 UTC
When loading a page, the title shows "X/Y loaded" and the timer for way longer than necessary. Sometimes the "wanna be notified when this loads?" toast even shows up.

To repro, just create a page and just view it, with nothing on it.

**Comment by iethree** [comment] 2023-02-27 16:32
duplicate of https://github.com/metabase/metabase/issues/24402

**Closed by iethree** 2023-02-27 16:32 UTC
Labels: Type:Bug, Priority:P3, Organization/Apps
