### ISSUE TITLE
Native query autocomplete should suggest ON for JOIN from foreign keys

### ISSUE THREAD

**Issue by bitwisecook** [metabase/metabase#13623] opened 2020-10-29 13:10 UTC
I'm frustrated when editing native queries that the JOINs don't get autocomplete suggestions based on the foreign keys present in the database.

When creating a query for this schema (postgresql):
```sql
CREATE TABLE a (
    id INT
    name TEXT
);
CREATE TABLE b (
   id INT
   thing TEXT
   a INT REFERENCES a(id)
);
```

I would like for a query like
```sql
SELECT * from b JOIN a ON ...
```

to automatically suggest
```
b.a = a.id
```

for completion.
   
This feature makes writing queries in larger schemas much more pleasant, saving significant time when considering the JOINs to be made.

This is present in Jetbrains IDEs:
<img width="859" alt="image" src="https://user-images.githubusercontent.com/2267430/97577966-0a3fea00-19e8-11eb-9c73-81efb872975f.png">

**Comment by flamber** [comment] 2020-10-29 13:15
Duplicate of #3885

**Closed by flamber** 2020-10-29 13:15 UTC
Labels: .Needs Triage, Type:New Feature
