### ISSUE TITLE
Allow relative dates (specifically "today") for default values of SQL parameters

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4606] opened 2017-03-23 22:27 UTC
Right now default values have to be absolute days. 

This seems much much less common a desired default than "yesterday" or "today" or "tomorrow"

**Comment by tlrobinson** [comment] 2017-03-23 22:40
This is only regarding SQL "field filter" template tags, right? On dashboards you can use whichever date widget you picked.

This would be resolved by adding the "full" date filter widget. I had to pick one of the existing filter widgets for date "field filters". The choice of "single date" widget was somewhat arbitrary.

**Comment by salsakran** [comment] 2017-03-23 22:41
Yes, updated the title to reflect that.

**Comment by mazameli** [comment] 2017-03-23 22:57
Related to or dupe of #4509

**Closed** 2017-03-23 22:58 UTC
Labels: Enhancement, Parameters/Variables
