### ISSUE TITLE
Render HTML tags in table view.

### ISSUE THREAD

**Issue by renatofritola** [metabase/metabase#12925] opened 2020-07-16 14:22 UTC
Several times it is necessary to include a link in table view to take the user to another application page. It turns out that the metabase does not support the inclusion of an HTML tag that would make the view cleaner.

I would like the possibility of including a link with `html <a href=""> COLUMN VALUE </a>`  to be included and for the metabase to interpret this leaving the column value as a link.

The interpretation should look like this according to github for example: <a href=""> VALUE OF COLUMN </a>

Currently in REDASH this is possible and very useful.

**Comment by flamber** [comment] 2020-07-16 14:27
The is already possible [Enterprise Edition](https://www.metabase.com/enterprise/) with [Custom Drill-through](https://www.metabase.com/docs/latest/enterprise-guide/customizing-drill-through.html)
Duplicate of #8461.

**Closed by flamber** 2020-07-16 14:27 UTC
Labels: .Needs Triage, Type:New Feature
