### ISSUE TITLE
Adding filters causes bugs on dashboard

### ISSUE THREAD

**Issue by sarahjane1987** [metabase/metabase#11948] opened 2020-02-20 20:54 UTC
**Describe the bug**
Adding a filter causes a bug on the dashboard that causes drag and drop to not work. You also can't actually apply to filter to any of the cards. The drag and drop aspect is similar to other bugs I have run into (https://github.com/metabase/metabase/issues/11931 and https://github.com/metabase/metabase/issues/11163)

**Logs**
![Untitled](https://user-images.githubusercontent.com/60162592/74977130-1fe02700-53f8-11ea-862d-616eb18a6d85.png)

There is a TON of data in the metabase logs for today because I've done a lot of work, but I don't see any red other than a separate issue due to changing a field name in the back end database.

**To Reproduce**
1. Add a filter on this specific dashboard and try to make it apply to any of the visualizations
2. Hit "done"
3. Try to drag and drop

**Screenshots**
Notice how it says "select the field..." but you can't actually select anything on the cards the way you should be:
![Untitled1](https://user-images.githubusercontent.com/60162592/74977509-d512df00-53f8-11ea-9138-c399753ab6d4.png)

This is with the drag and drop issue activated. Notice how the usual squares in the background go away that show you where you can drop... that always happens with this bug. I haven't tried hitting "save" for fear of bugging the whole dashboard and having to start over again (which I've already had to do once due to bugs), but I'm willing to bet it would tell me "Save Failed"
![Untitled2](https://user-images.githubusercontent.com/60162592/74977691-32a72b80-53f9-11ea-8233-6c3e14828864.png)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.14.97-74.72.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-02-04",
      "tag": "v0.34.2",
      "branch": "release-0.34.x",
      "hash": "dab738c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Blocks the use of any filters, which are crucial for this dashboard.

**Additional context**

**Comment by flamber** [comment] 2020-02-20 21:04
Duplicate of #11927

**Closed by flamber** 2020-02-20 21:04 UTC
Labels: .Needs Triage, Type:Bug
