### ISSUE TITLE
Card alert won't render on master

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#33382] opened 2023-08-21 17:34 UTC
### Describe the bug

We have a regression where table card won't render in a slack alert

Card 12874, channel "Cancellation Survey Responses for Alert"

### To Reproduce

See above

### Expected behavior

alerts should render correctly

### Logs

NA

### Information about your Metabase installation

```JSON
master
```

### Severity

P2

**Comment by darksciencebase** [comment] 2023-08-23 15:45
Duplicate of https://github.com/metabase/metabase/issues/33279

**Closed by darksciencebase** 2023-08-23 15:45 UTC
Labels: Type:Bug, Priority:P2, Reporting/Alerts, .Regression/master

**Comment by paoliniluis** [comment] 2023-08-23 23:01
thank you!
