### ISSUE TITLE
Automatic switching between dashboards (carousel)

### ISSUE THREAD

**Issue by josteinaj** [metabase/metabase#5314] opened 2017-06-12 15:41 UTC
I would like it if there was a way to set up multiple dashboards to be displayed in a carousel-like manner.

**Comment by alee792** [comment] 2017-08-14 19:47
Would also love this feature. I created a quick and dirty static web page to cycle through embedded iframes of dashboards/questions, but would love this as a native feature.

**Comment by jornh** [comment] 2018-05-04 15:45
Sounds like a duplicate of https://github.com/metabase/metabase/issues/4468 to me.

**Comment by josteinaj** [comment] 2018-05-08 08:51
Yes, it's a duplicate. Didn't see that issue when I created this one.

**Closed** 2020-05-28 19:47 UTC
Labels: .Proposal, Reporting/Dashboards
