### ISSUE TITLE
`<h1>Bad Message 400</h1><pre>reason: Illegal character SPACE=' '</pre>` when trying to display models

### ISSUE THREAD

**Issue by astrojuanlu** [metabase/metabase#22752] opened 2022-05-16 17:09 UTC
**Describe the bug**
When I try to display the list of models, I observe an error in the menu and no data.

There seems to be a `GET /api/database/-1337/datasets/Everything%20else` coming from the frontend that originates this `400 BAD REQUEST` error.

**Logs**
There seems to be a `GET /api/database/-1337/datasets/Everything%20else` coming from the frontend that originates this `400 BAD REQUEST` error.

**To Reproduce**
1. Create a model
2. Create new question
3. On the "Pick your starting data" dropdown, pick "Models"
4. Observe error

**Expected behavior**
I see a list of models and no errors.

**Screenshots**
![Screenshot from 2022-05-16 19-03-09](https://user-images.githubusercontent.com/316517/168645589-37b81da2-a006-4202-b643-e5330fecbe87.png)

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.13.0-1022-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-02",
      "tag": "v0.43.0",
      "branch": "release-x.43.x",
      "hash": "ee686fc"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
It is not very severe because I can still use the search box to locate my model, but I have to remember the name.

**Comment by flamber** [comment] 2022-05-16 17:25
Hi @astrojuanlu 
There should be a full stacktrace error in Admin > Troubleshooting > Logs - please include that.

It sounds like Metabase is making a request to `/api/database/-1337/datasets/Everything else` (with a space instead of encoded), but I'm not sure how this can occur, since we're sending the encoded `%20`.
It worries me that the error is coming directly from Jetty instead of via Metabase as it should.

I'm not able to reproduce this. Is this a new setup or existing which was upgraded to 43.0? And is it a new problem on 0.43?
If you do a full browser refresh, are you still have to trigger this error?

**Comment by astrojuanlu** [comment] 2022-05-16 17:51
Hi @flamber , interestingly the `400` request does not appear in the logs. Here is what I have:

```
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:00+02:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 55.8 ms (4 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (3 idle, 0 queued) (101 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:00+02:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 124.8 ms (9 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (102 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:01+02:00 DEBUG metabase.server.middleware.log GET /api/bookmark 200 15.8 ms (1 DB calls) App DB connections: 6/15 Jetty threads: 9/50 (1 idle, 0 queued) (105 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:01+02:00 DEBUG metabase.server.middleware.log GET /api/collection/root 200 25.9 ms (2 DB calls) App DB connections: 6/15 Jetty threads: 8/50 (2 idle, 0 queued) (105 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:01+02:00 DEBUG metabase.server.middleware.log GET /api/database 200 59.8 ms (3 DB calls) App DB connections: 3/15 Jetty threads: 6/50 (4 idle, 0 queued) (105 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:01+02:00 DEBUG metabase.server.middleware.log GET /api/activity/recent_views 200 88.6 ms (6 DB calls) App DB connections: 3/15 Jetty threads: 5/50 (5 idle, 0 queued) (105 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:01+02:00 DEBUG metabase.server.middleware.log GET /api/collection/tree 200 123.5 ms (8 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (6 idle, 0 queued) (105 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:01+02:00 DEBUG metabase.server.middleware.log GET /api/activity/popular_items 200 112.8 ms (8 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (7 idle, 0 queued) (105 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:30+02:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 54.7 ms (4 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (6 idle, 0 queued) (105 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:31+02:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 106.2 ms (9 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (7 idle, 0 queued) (105 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:31+02:00 DEBUG metabase.server.middleware.log GET /api/collection/root 200 24.5 ms (2 DB calls) App DB connections: 5/15 Jetty threads: 9/50 (1 idle, 0 queued) (105 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:31+02:00 DEBUG metabase.server.middleware.log GET /api/bookmark 200 16.3 ms (1 DB calls) App DB connections: 4/15 Jetty threads: 7/50 (4 idle, 0 queued) (106 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:31+02:00 DEBUG metabase.server.middleware.log GET /api/database 200 45.0 ms (3 DB calls) App DB connections: 3/15 Jetty threads: 6/50 (5 idle, 0 queued) (106 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:31+02:00 DEBUG metabase.server.middleware.log GET /api/activity/recent_views 200 86.8 ms (6 DB calls) App DB connections: 2/15 Jetty threads: 5/50 (6 idle, 0 queued) (106 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:31+02:00 DEBUG metabase.server.middleware.log GET /api/collection/tree 200 105.3 ms (8 DB calls) App DB connections: 2/15 Jetty threads: 5/50 (6 idle, 0 queued) (106 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:31+02:00 DEBUG metabase.server.middleware.log GET /api/activity/popular_items 200 106.6 ms (8 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (7 idle, 0 queued) (108 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:36+02:00 DEBUG metabase.server.middleware.log GET /api/timeline 200 36.7 ms (3 DB calls) App DB connections: 2/15 Jetty threads: 5/50 (6 idle, 0 queued) (108 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:36+02:00 DEBUG metabase.server.middleware.log GET /api/search 200 42.2 ms (3 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (7 idle, 0 queued) (108 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:36+02:00 DEBUG metabase.server.middleware.log GET /api/database 200 89.5 ms (7 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (7 idle, 0 queued) (108 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:43+02:00 DEBUG metabase.server.middleware.log GET /api/setting 200 46.4 ms (3 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (7 idle, 0 queued) (108 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:43+02:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 54.7 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (7 idle, 0 queued) (108 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:43+02:00 DEBUG metabase.server.middleware.log GET /api/setup/admin_checklist 200 132.0 ms (11 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (8 idle, 0 queued) (108 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:44:47+02:00 DEBUG metabase.server.middleware.log GET /api/util/bug_report_details 200 14.5 ms (1 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (8 idle, 0 queued) (108 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:45:29+02:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 58.8 ms (4 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (7 idle, 0 queued) (108 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:45:29+02:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 107.4 ms (9 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (8 idle, 0 queued) (108 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:45:29+02:00 DEBUG metabase.server.middleware.log GET /api/database 200 38.6 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (8 idle, 0 queued) (108 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:45:59+02:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 53.5 ms (4 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (6 idle, 0 queued) (105 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:45:59+02:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 107.8 ms (9 DB calls) App DB connections: 1/15 Jetty threads: 3/50 (7 idle, 0 queued) (105 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:45:59+02:00 DEBUG metabase.server.middleware.log GET /api/collection/root 200 24.5 ms (2 DB calls) App DB connections: 2/15 Jetty threads: 6/50 (4 idle, 0 queued) (105 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:45:59+02:00 DEBUG metabase.server.middleware.log GET /api/bookmark 200 14.1 ms (1 DB calls) App DB connections: 3/15 Jetty threads: 5/50 (5 idle, 0 queued) (105 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:45:59+02:00 DEBUG metabase.server.middleware.log GET /api/database 200 39.0 ms (3 DB calls) App DB connections: 2/15 Jetty threads: 6/50 (4 idle, 0 queued) (105 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:45:59+02:00 DEBUG metabase.server.middleware.log GET /api/collection/tree 200 98.7 ms (8 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (5 idle, 0 queued) (105 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:45:59+02:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 60.6 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (5 idle, 0 queued) (105 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:45:59+02:00 DEBUG metabase.server.middleware.log GET /api/setting 200 53.8 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (5 idle, 0 queued) (105 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:45:59+02:00 DEBUG metabase.server.middleware.log GET /api/setup/admin_checklist 200 145.0 ms (11 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (7 idle, 0 queued) (107 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:46:00+02:00 DEBUG metabase.server.middleware.log GET /api/activity/recent_views 200 149.3 ms (6 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (6 idle, 0 queued) (107 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:46:00+02:00 DEBUG metabase.server.middleware.log GET /api/activity/popular_items 200 161.4 ms (8 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (6 idle, 0 queued) (107 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:46:03+02:00 DEBUG metabase.server.middleware.log GET /api/timeline 200 35.5 ms (3 DB calls) App DB connections: 2/15 Jetty threads: 6/50 (4 idle, 0 queued) (107 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:46:03+02:00 DEBUG metabase.server.middleware.log GET /api/search 200 38.0 ms (3 DB calls) App DB connections: 1/15 Jetty threads: 5/50 (5 idle, 0 queued) (107 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:46:03+02:00 DEBUG metabase.server.middleware.log GET /api/database 200 85.7 ms (7 DB calls) App DB connections: 1/15 Jetty threads: 5/50 (5 idle, 0 queued) (107 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:46:14+02:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 54.2 ms (4 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (6 idle, 0 queued) (109 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:46:14+02:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 106.8 ms (9 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (7 idle, 0 queued) (109 total active threads) Queries in flight: 0 (0 queued)
[b35361e7-82e5-4fa8-921d-a81b6fb7893f] 2022-05-16T19:46:14+02:00 DEBUG metabase.server.middleware.log GET /api/database 200 37.5 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (7 idle, 0 queued) (109 total active threads) Queries in flight: 0 (0 queued)
```

Doing a `Ctrl+F` for `/api/database/-1337` yields nothing from the logs.

This setup was upgraded to 43.0 from 42.0 but in the previous version it was happening too. A full browser refresh doesn't help, tested with Firefox and Chromium.

**Comment by flamber** [comment] 2022-05-16 18:00
@astrojuanlu Are you sure that you don't have a reverse-proxy, which causes problems during encoding of URLs?
https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html

**Comment by astrojuanlu** [comment] 2022-05-16 18:11
@flamber It's very likely, since this is an instance running as an https://github.com/orchest/orchest/ service. Pinging @fruttasecca

**Comment by flamber** [comment] 2022-05-17 19:52
@astrojuanlu The problem is definitely being caused by a reverse-proxy somewhere, since there should be a request in Metabase's log if it was hitting Metabase. Since you've had this problem in 0.42.x too, and I've not heard of anyone else hitting this problem, then it must be something fairly unique to your setup. Closing.

**Closed by flamber** 2022-05-17 19:52 UTC
Labels: Type:Bug, .Needs Triage
