### ISSUE TITLE
Select permission level for All users when adding a new data source

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#27252] opened 2022-12-15 00:01 UTC
**Is your feature request related to a problem? Please describe.**
It would be good if we could ask the admin who will add a new data source the permissions they want to give to "All Users" when they add it. Right now it's "unrestricted" but that might be a little too much for some contexts

**Describe the solution you'd like**
An option in the Add DB form to select the permission level an admin wants to give "All users". The default can be Unrestricted

**Describe alternatives you've considered**
Adding the DB and right after that an API call blocking :D

**How important is this feature to you?**
Requested by a customer

**Additional context**
NA

**Comment by flamber** [comment] 2022-12-15 10:07
Duplicate of #6735

**Closed by flamber** 2022-12-15 10:07 UTC
Labels: Type:New Feature, Administration/Permissions
