### ISSUE TITLE
Metabase Initialization FAILED on latest build

### ISSUE THREAD

**Issue by Shra25** [metabase/metabase#9751] opened 2019-04-10 06:37 UTC
Metabase version - 0.32.4
Ubuntu 16.04
database - h2

Error Log

04-10 12:04:56 INFO metabase.db :: Verifying h2 Database Connection ...
04-10 12:04:56 INFO metabase.driver :: Initializing driver :sql...
04-10 12:04:56 INFO metabase.driver :: Initializing driver :sql-jdbc...
04-10 12:04:56 INFO metabase.driver :: Initializing driver :h2...
04-10 12:05:01 ERROR metabase.core :: Metabase Initialization FAILED
java.lang.Exception: Timed out after 5,000 milliseconds.
        at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:34)
        at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:18)
        at clojure.lang.RestFn.invoke(RestFn.java:442)
        at clojure.lang.Var.invoke(Var.java:393)
        at metabase.db$verify_db_connection$fn__14460.invoke(db.clj:403)
        at metabase.db$verify_db_connection.invokeStatic(db.clj:401)
        at metabase.db$verify_db_connection.invoke(db.clj:394)
        at metabase.db$verify_db_connection.invokeStatic(db.clj:397)
        at metabase.db$verify_db_connection.invoke(db.clj:394)
        at metabase.db$setup_db_BANG_$fn__14477.invoke(db.clj:467)
        at metabase.util$do_with_us_locale.invokeStatic(util.clj:683)
        at metabase.util$do_with_us_locale.invoke(util.clj:669)
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:466)
        at metabase.db$setup_db_BANG_.doInvoke(db.clj:460)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at metabase.core$init_BANG_.invokeStatic(core.clj:72)
        at metabase.core$init_BANG_.invoke(core.clj:51)
        at metabase.core$start_normally.invokeStatic(core.clj:118)
        at metabase.core$start_normally.invoke(core.clj:112)
        at metabase.core$_main.invokeStatic(core.clj:138)
        at metabase.core$_main.doInvoke(core.clj:133)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
Caused by: java.util.concurrent.TimeoutException: Timed out after 5,000 milliseconds.
        at metabase.util$deref_with_timeout.invokeStatic(util.clj:329)
        at metabase.util$deref_with_timeout.invoke(util.clj:323)
        at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:29)
        ... 24 more
04-10 12:05:01 INFO metabase.core :: Metabase Shutting Down ...
04-10 12:05:01 INFO metabase.core :: Metabase Shutdown COMPLETE

**Comment by flamber** [comment] 2019-04-10 08:11
@Shra25 
Did you upgrade? If yes, from which version? What if you downgrade, do you still get the error?

**Comment by Shra25** [comment] 2019-04-10 08:13
Upgraded it from V0.31.2

**Comment by camsaul** [comment] 2019-04-10 17:18
If it can’t connect to your H2 DB that usually means another process has it open. Did you stop the old Metabase server first?

**Comment by x670** [comment] 2019-04-12 13:46
I have the same issue. 
Before that I run metabase **v0.31.2** docker version with h2 db
I killed container with previous build, removed it with `docker container rm`, then forced to remove image and reinstalled docker image to latest version **v0.32.4**
And now there it is

**Comment by flamber** [comment] 2019-04-12 14:40
Hi @x670 

There has been work done, so it should now do some cleanup, when Metabase is stopping (#9411), because that process cannot be done while Metabase is using the database.

It is not recommended to use H2 in production - use Postgres or MariaDB/MySQL:
https://metabase.com/docs/latest/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres

You can manually run cleanup on H2 - have a look in this thread:
https://discourse.metabase.com/t/metabase-db-cleanup/5079?u=flamber

**Comment by jianbowan** [comment] 2019-06-29 10:14
Metabase version - 0.32.9
Centos 7
database - spark sql

Mine too, when I try to connect to the hive database, I get the following error:
Timed out after 5,000 milliseconds.

**Comment by flamber** [comment] 2019-06-29 14:10
Hi @jianbowan 
This issue is about Metabase not starting, because of problems with a corrupted H2 database.
Your problem is unrelated. It sounds like firewall issues - or just the wrong hostname/port. Have a look at the log for more detailed errors.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by jianbowan** [comment] 2019-07-02 01:28
> 嗨@jianbowan
> 这个问题是关于Metabase没有启动，因为H2数据库被锁定/损坏的问题。
> 你的问题是无关紧要的。这听起来像防火墙问题 - 或者只是错误的主机名/端口。查看日志以获取更详细的错误。
> 请使用论坛查询问题和排除故障：[https](https://discourse.metabase.com/)：[//discourse.metabase.com/](https://discourse.metabase.com/)

The ip, port, and firewall are all fine. In the old version of metabase, the layer successfully created the spark connection.
Now you can use this connection directly to get the number, but you can't save an existing connection or create a new one.

I tested it locally. I can't connect to spark after running jar in Windows 10. When I replace sparksql.metabase-driver.jar with metabase-sparksql-deps-1.2.1.spark2-standalone.jar, everything is fine. .
However, I tried to delete sparksql.metabase-driver.jar under metabase/plugins on centos7 and leave metabase-sparksql-deps-1.2.1.spark2-standalone.jar. Every time I start metabase, the system will generate sparksql.metabase-driver.jar again under plugins.

Now I have nothing to do, please help me, thank you very much!

**Comment by flamber** [comment] 2019-07-02 01:42
@jianbowan 
Okay, but that's a completely different problem than what this issue is describing.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And check the Metabase log to make sure that it actually loads built-in Spark driver. Or rename the older driver to `sparksql.metabase-driver.jar`, so Metabase doesn't try to extract the built-in driver.

**Comment by mathop** [comment] 2020-03-03 19:11
Metabase Version: 0.34.3
Environment: Docker
Database: MySQL

I have the same issue while migrating from 0.34.2 to v.034.3:

```
03-03 01:36:30 INFO metabase.core :: Starting Metabase version v0.34.3 (1a83edb release-0.34.x) ...
...
03-03 01:44:54 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
03-03 01:44:55 INFO metabase.db :: Verifying mysql Database Connection ...
03-03 01:44:55 INFO driver.impl :: Initializing driver :sql...
03-03 01:44:55 INFO driver.impl :: Initializing driver :sql-jdbc...
03-03 01:44:55 INFO driver.impl :: Initializing driver :mysql...
03-03 01:45:01 ERROR driver.util :: Database connection error
java.util.concurrent.TimeoutException: Timed out after 5.0 s
at metabase.util$deref_with_timeout.invokeStatic(util.clj:292)
at metabase.util$deref_with_timeout.invoke(util.clj:284)
at metabase.util$do_with_timeout.invokeStatic(util.clj:298)
at metabase.util$do_with_timeout.invoke(util.clj:295)
at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:31)
at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:20)
at clojure.lang.RestFn.invoke(RestFn.java:442)
at clojure.lang.Var.invoke(Var.java:393)
at metabase.db$fn__21258$verify_db_connection__21267$fn__21270$fn__21271.invoke(db.clj:275)
at metabase.db$fn__21258$verify_db_connection__21267$fn__21270.invoke(db.clj:274)
at metabase.db$fn__21258$verify_db_connection__21267.invoke(db.clj:266)
at metabase.db$fn__21258$verify_db_connection__21267$fn__21268.invoke(db.clj:269)
at metabase.db$fn__21258$verify_db_connection__21267.invoke(db.clj:266)
at metabase.db$setup_db_BANG__STAR_$fn__21310.invoke(db.clj:328)
at metabase.util$do_with_us_locale.invokeStatic(util.clj:656)
at metabase.util$do_with_us_locale.invoke(util.clj:642)
at metabase.db$setup_db_BANG__STAR_.invokeStatic(db.clj:327)
at metabase.db$setup_db_BANG__STAR_.invoke(db.clj:322)
at metabase.db$setup_db_from_env_BANG__STAR_.invokeStatic(db.clj:337)
at metabase.db$setup_db_from_env_BANG__STAR_.invoke(db.clj:334)
at metabase.db$setup_db_BANG_$fn__21321.invoke(db.clj:351)
at metabase.db$setup_db_BANG_.invokeStatic(db.clj:349)
at metabase.db$setup_db_BANG_.invoke(db.clj:344)
at metabase.core$init_BANG_.invokeStatic(core.clj:76)
at metabase.core$init_BANG_.invoke(core.clj:55)
at metabase.core$start_normally.invokeStatic(core.clj:122)
at metabase.core$start_normally.invoke(core.clj:116)
at metabase.core$_main.invokeStatic(core.clj:142)
at metabase.core$_main.doInvoke(core.clj:137)
at clojure.lang.RestFn.invoke(RestFn.java:397)
at clojure.lang.AFn.applyToHelper(AFn.java:152)
at clojure.lang.RestFn.applyTo(RestFn.java:132)
at metabase.core.main(Unknown Source)
03-03 01:45:01 ERROR metabase.core :: Metabase Initialization FAILED
java.lang.Exception: Timed out after 5.0 s
at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:37)
at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:20)
at clojure.lang.RestFn.invoke(RestFn.java:442)
at clojure.lang.Var.invoke(Var.java:393)
at metabase.db$fn__21258$verify_db_connection__21267$fn__21270$fn__21271.invoke(db.clj:275)
at metabase.db$fn__21258$verify_db_connection__21267$fn__21270.invoke(db.clj:274)
at metabase.db$fn__21258$verify_db_connection__21267.invoke(db.clj:266)
at metabase.db$fn__21258$verify_db_connection__21267$fn__21268.invoke(db.clj:269)
at metabase.db$fn__21258$verify_db_connection__21267.invoke(db.clj:266)
at metabase.db$setup_db_BANG__STAR_$fn__21310.invoke(db.clj:328)
at metabase.util$do_with_us_locale.invokeStatic(util.clj:656)
at metabase.util$do_with_us_locale.invoke(util.clj:642)
at metabase.db$setup_db_BANG__STAR_.invokeStatic(db.clj:327)
at metabase.db$setup_db_BANG__STAR_.invoke(db.clj:322)
at metabase.db$setup_db_from_env_BANG__STAR_.invokeStatic(db.clj:337)
at metabase.db$setup_db_from_env_BANG__STAR_.invoke(db.clj:334)
at metabase.db$setup_db_BANG_$fn__21321.invoke(db.clj:351)
at metabase.db$setup_db_BANG_.invokeStatic(db.clj:349)
at metabase.db$setup_db_BANG_.invoke(db.clj:344)
at metabase.core$init_BANG_.invokeStatic(core.clj:76)
at metabase.core$init_BANG_.invoke(core.clj:55)
at metabase.core$start_normally.invokeStatic(core.clj:122)
at metabase.core$start_normally.invoke(core.clj:116)
at metabase.core$_main.invokeStatic(core.clj:142)
at metabase.core$_main.doInvoke(core.clj:137)
at clojure.lang.RestFn.invoke(RestFn.java:397)
at clojure.lang.AFn.applyToHelper(AFn.java:152)
at clojure.lang.RestFn.applyTo(RestFn.java:132)
at metabase.core.main(Unknown Source)
Caused by: java.util.concurrent.TimeoutException: Timed out after 5.0 s
at metabase.util$deref_with_timeout.invokeStatic(util.clj:292)
at metabase.util$deref_with_timeout.invoke(util.clj:284)
at metabase.util$do_with_timeout.invokeStatic(util.clj:298)
at metabase.util$do_with_timeout.invoke(util.clj:295)
at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:31)
```

The version 0.34.2 can successfully connect to MySQL during the startup process:

```
03-03 18:21:41 INFO metabase.core :: Starting Metabase version v0.34.2 (dab738c release-0.34.x) ...
...
03-03 18:22:01 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
03-03 18:22:01 INFO metabase.db :: Verifying mysql Database Connection ...
03-03 18:22:01 INFO driver.impl :: Initializing driver :sql...
03-03 18:22:01 INFO driver.impl :: Initializing driver :sql-jdbc...
03-03 18:22:01 INFO driver.impl :: Initializing driver :mysql...
03-03 18:22:02 INFO metabase.db :: Successfully verified MySQL 5.7.12 application database connection. ✅
```

**Comment by flamber** [comment] 2020-03-03 20:24
Hi @mathop 

There hasn't been any changes to the query or connection layers between 0.34.2 and 0.34.3
So it's quite puzzling that it has problems with the connection between those versions.

This issue was about Metabase not starting with H2 as the application database, but you're using MySQL, so you're having a different problem.
Most likely the connection to your MySQL database was not working, while Metabase was starting.
Given the 17 hours difference between the startups, could that maybe be the cause?

Please head over to the forum to try troubleshooting the problem: https://discourse.metabase.com/

--
Closing this issue, since using H2 for production is not recommended - please migrate away:
https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html

**Closed by flamber** 2020-03-03 20:24 UTC
Labels: Operation/, Priority:P3, Type:Bug

**Comment by mathop** [comment] 2020-03-03 21:54
@flamber Thanks for answering me! I tried to run a Metabase instance in another Docker environment and it worked with no issues. I went back to the faulty environment and realized the server load was too high, and probably causing the delay to connect to the MySQL server.
