### ISSUE TITLE
Field filter links not working in SQL

### ISSUE THREAD

**Issue by Maragues** [metabase/metabase#3615] opened 2016-10-18 11:20 UTC
I'm trying to create a field filter in a SQL question, but it's never offered in dashboard filters. See gif, sorry it's a bit long. You may need to open it in a new tab to see what's going on
1. I choose "Variable Type: text", which works fine and I can link from a dashboard
2. I choose "Variable Type: field filter", which I'm not able to link to from a dashboard

![metabase_filters_speed_up](https://cloud.githubusercontent.com/assets/655970/19475558/12c241c8-9535-11e6-9ac0-34bba8ed3d9e.gif)

The field I'm trying to work with is "TEXT", but I've also tried with VARCHAR

I've also tried Date columns without success

```
AND date between {{start}} and {{end}}
```

If I flag them as Date varaible type, I can use them for dashboard filtering. If I try to flag them as Field Filter, they are not offered when adding a dashboard filter.

Metabase version is 20.0.0
database is MySQL

Related
- https://github.com/metabase/metabase/pull/2795
- https://github.com/metabase/metabase/issues/3120

**Comment by tlrobinson** [comment] 2016-10-18 14:57
This should have been fixed in 0.20.0. I just tried this with the Sample dataset and it worked fine, e.x. `select count(*) from products where {{category}}` with `category` set to be a Field Filter for the "Products: Category" column. Could you try that and see if it works?

What is the type of the `Communities: Name` field?

BTW, this shouldn't matter, but Field Filter variables don't need the optional `[[ ]]` brackets (since we can insert a nop clause like `1=1`)

**Comment by Maragues** [comment] 2016-10-19 08:06
Your query works for me with the sample dataset, but this one doesn't

```
select count(*) from people where {{email}}
```

![image](https://cloud.githubusercontent.com/assets/655970/19509924/546fa672-95e1-11e6-83f7-82fbdc448bc8.png)

![image](https://cloud.githubusercontent.com/assets/655970/19509933/5feb7a44-95e1-11e6-82ed-8e54fac2a512.png)

![image](https://cloud.githubusercontent.com/assets/655970/19509952/73dbf128-95e1-11e6-83c4-dad3ee576640.png)

If I query "*show columns from products/orders*", both fields are VARCHAR(255). But if I go through metabase's table viewer, the *datatype* is the same (*type/text*) while the *Field type* is *Category* for *category* and *No field type* for *email*. I don't know where this information comes from.

**Comment by kigen** [comment] 2017-01-05 11:07
I have the same issue. 
Field filters for SQL builder based queries doesn't generate the UI widget. 
Field Types: String & UUID 
Database: PostgreSQL
Metabase version: 0.21.1
Setup: Jar File.

**Comment by camsaul** [comment] 2017-01-09 18:01
@Maragues what kind of database are you using?

@kigen you have to have the Card in a Dashboard to see the field filter widget, it doesn't show up in the SQL editor view (that's correct, right, @metabase/core-developers?)

**Comment by Maragues** [comment] 2017-01-10 13:25
MySQL 

I no longer have access to that project, so I won't be able to help beyond what's already posted, sorry

**Comment by camsaul** [comment] 2017-01-10 17:10
Since neither @tlrobinson or I were able to reproduce this I think it might have been fixed since 0.20.0 so I'm going to go ahead and close this. @Maragues feel free to open a new issue if you have problems again in the future.

**Comment by tlrobinson** [comment] 2017-01-10 20:59
It looks like for the "category" widget we're only showing fields that are.... categories. Specifically `isCategory` which currently includes `TYPE.Boolean`, `TYPE.Category`, and `TYPE.Address`, which feels a little arbitrary.

@metabase/core-developers Is the "Category" widget actually supposed to be restricted to fields we consider a Category in other places, or should we just allow any `TYPE.Text` or `TYPE.Number`?

**Comment by abtinf** [comment] 2017-02-21 09:23
I too am experiencing this issue. I'm using a sqlite data source with text columns.

**Comment by salsakran** [comment] 2017-02-21 23:36
@tlrobinson the intention was that "category" would be used for things that were low ordinality and could effectively be drop-downs.

The initial set of widgets was not meant to be comprehensive, and we should probably add others that are better suited to eg, names, emails, etc.

**Comment by salsakran** [comment] 2017-02-21 23:38
@abtinf , @Maragues and @kigen can you please elaborate on what you're trying to filter? It's our intention to create a bunch of specialized filter widgets vs just putting `input` fields on the dashboard and letting users fend for themselves

**Comment by Maragues** [comment] 2017-02-22 08:06
In my case you can check the .gif I attached. I tried to filter the table by column name (TEXT).

Anyway, I'm working at another company and I no longer use metabase, so I can't be of much help.

**Comment by wvengen** [comment] 2017-03-13 10:54
I'm seeing this too with PostgreSQL. Setting _Variable type_ to _Text_ shows a filter input above the query, setting it to _Field Filter_ does not result in any filter input above the query.
Using [master](https://github.com/metabase/metabase/commit/1125050524a72246f1ed55c8db0d3715db08fcf3) on Chromium and Firefox.

**Comment by wvengen** [comment] 2017-03-13 10:57
Could this be related to #3586?

**Comment by jlgoldman** [comment] 2017-03-24 22:15
I have the same issue a @wvengen, trying to create a Field Filter on string/text column input does precisely nothing.

The use case is essentially: SELECT count(*) FROM table1 WHERE {{code}};

The column "code" is a foreign key reference to table2 where "code" is the primary key and has just 50 values. I just need a dropdown of those 50 values.

**Comment by nickcarenza** [comment] 2017-05-08 16:56
I have this issue as well.

**Comment by federico-fiorini** [comment] 2017-09-14 02:03
Same issue here as well

**Comment by hky404** [comment] 2017-10-16 20:22
same issue

**Comment by mazameli** [comment] 2017-10-16 21:27
@nickcarenza, @federico-fiorini, and @hky404 — which version of Metabase are you using, and what kind of database?

**Comment by nickcarenza** [comment] 2017-10-16 21:35
You're on version v0.23.1 with mysql

**Comment by mazameli** [comment] 2017-10-16 21:50
@nickcarenza thanks for the quick reply. For what it's worth, v0.23 was released 7 months ago, so it's very possible that [a simple upgrade](https://metabase.com/docs/latest/operations-guide/start.html#upgrading-metabase) would solve your problems (not to mention all the cool additional features you'd get 😉 ).

**Comment by nickcarenza** [comment] 2017-10-16 22:03
@mazameli Yea, we really should upgrade. I actually don't remember what issue exactly I was having at the time but in another new metabase installation I have what seems to be the same problem as what is discussed here and it seems to be strictly related to the number of distinct values for the column. Is there some sort of internal limit for using a category filter?

**Comment by hky404** [comment] 2017-10-16 22:12
@mazameli I am using
v0.26.1
Built on 2017-09-26

**Comment by mazameli** [comment] 2017-10-16 22:27
@hky404 thanks for the info. Can you try the following:

- go to the Admin Panel, and in the Data Model section, go to the table that has the field you're trying to use with your filter, and set that field to the `Category` type.
- click on the gear icon to the right of the Type dropdown, and click the `Re-scan this field` button at the bottom of the page you're taken to. This will force a re-caching of the values in that field.
- go back to your saved SQL query and refresh it

If your field has fewer than 300 unique values, you should get a dropdown-with-search filter widget at the top of your query. If the field has more than 300 unique values, the filter widget will just be an input box. (Hopefully that also answers your last question, @nickcarenza)

**Comment by hky404** [comment] 2017-10-16 22:34
@mazameli thanks for the detailed response. But still the same, may be I am doing something wrong in the query?! Here is my question that I posted on discourse with no response over there as usual - 
https://discourse.metabase.com/t/how-to-apply-filter-at-dashboard-level/2236

**Comment by hky404** [comment] 2017-10-17 18:47
@mazameli it worked. I changed the date field to the type 'category' in the admin panel and made some changes to my query and everything worked fine as far as date is concerned. Now to the next question, how can I make a field drop-down?! But that's not for this thread as it is not related to bug fixes. I just wish Metabase documentation was slightly better, but it's all good.

**Comment by HayatBJJ** [comment] 2018-04-11 14:33
I have the same issue,but I'm using MongoDB, so I need the query equivalent of:
 " select count(*) from products where {{category}} ".
I tried this one :
{
    "$group":{"_id":{"stage":"$stage","project":"$projectName"},
        "count":{"$sum":1}
    }
},{"$unwind":"$_id"},{ "$project" : {
   "_id":0, "stage":"$_id.stage","project":"$_id.project","count":1
         }},{"$match":{"project":"$$category"}}
But it doesn't work.

**Comment by vsusnova** [comment] 2018-08-22 10:42
I am experiencing the same issue as well. 
Metabase version 0.30.0
Database postgres

**Comment by xaviershay** [comment] 2018-10-22 22:47
I think I was having this same issue. I had a field filter in native SQL on a column "quest_id", but I wasn't able to link it to a dashboard filter.

To "fix", I went into the data model section of admin and explicitly set the column to a Foreign Key type. That allowed me to choose a "filter widget type" in the variable configuration, which was previously not showing up, and to also link in dashboards.

**Comment by flamber** [comment] 2020-05-08 11:06
Since version 0.33.4 "Filter widget type" is always shown, but might only have the option "None", including the help text "There aren't any filter widgets for this type of field yet" and a documentation link:
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#the-field-filter-variable-type

**Closed by flamber** 2020-05-08 11:06 UTC
Labels: Priority:P3, Querying/Parameters & Variables, Type:Bug
