### ISSUE TITLE
Dashboard filters - should stay at the top when scrolling

### ISSUE THREAD

**Issue by samiyabroudi** [metabase/metabase#3511] opened 2016-10-11 19:33 UTC
Hello!

Would it be possible to keep filters frozen at the top of the dashboard while scrolling down (in regular mode and both edit modes). It would be super helpful. An example similar to this is freezing rows and columns in a spreadsheet.

Thanks!

**Comment by flamber** [comment] 2020-02-22 20:14
Even though this is the OG, I'm closing it as duplicate of #11187, since this has fewer upvotes.

**Closed by flamber** 2020-02-22 20:14 UTC
Labels: .Proposal, Reporting/Dashboards

**Comment by samiyabroudi** [comment] 2020-02-23 17:03
Oh nooooo!!!!

**Comment by flamber** [comment] 2020-02-23 19:25
Sorry @samiyabroudi 
No one found the other issue, when it was created. That doesn't mean that it will go to the back of the queue. I'm just trying to cleanup the duplicates, so it's easier to overview the 2k+ open issues.
