### ISSUE TITLE
Translate interface

### ISSUE THREAD

**Issue by Philippe-M** [metabase/metabase#6652] opened 2018-01-05 07:29 UTC
In a future version, is there a possibility to translate the interface?

**Comment by jornh** [comment] 2018-01-05 14:53
Sounds like a duplicate of *"Localization"* - See https://github.com/metabase/metabase/issues/1451#issuecomment-323420922

Please close this issue if that resolves what you were asking for 😄 or explain further ...

**Comment by salsakran** [comment] 2018-01-05 17:24
yup, this is a dupe of #1451 which is in progress!

**Closed by salsakran** 2018-01-05 17:24 UTC
