### ISSUE TITLE
Can't use regex flags with query parameters

### ISSUE THREAD

**Issue by rashad** [metabase/metabase#12176] opened 2020-03-23 15:22 UTC
Hello there 👋 

**Describe the bug**
Part of my query includes a parametrized search in a string as per
```
SELECT array_length(regexp_extract_all(gl.lyrics,  r'(?i)'|| {{search}} )) AS search_match
```
If I replace the content of `search` in the bigquery console no issue but when it comes from metabase i get a **weird parameter injection in the query** (example with word `nwar`)

```
SELECT array_length(regexp_extract_all(gl.lyrics,  r'('nwar'i)'? )) AS search_match
```

**Expected behavior**
I expected the query to run as it does on the console and to replace the `{{search}}` part instead of the `?` 

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.
It's blocking me from completing this query which I rely on for very often (multiple times per week) look for info in a text corpus. So very severe bug on my side :(

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.15.0-45-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "bigquery",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-02-25",
      "tag": "v0.34.3",
      "branch": "release-0.34.x",
      "hash": "1a83edb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

Cheers from France 👋 🇫🇷

**Comment by flamber** [comment] 2020-03-23 15:45
Closing a duplicate of #10257

**Closed by flamber** 2020-03-23 15:45 UTC
Labels: .Duplicate

**Comment by rashad** [comment] 2020-03-23 23:13
Sorry I looked and missed it. My Bad 🙏 Thanks for the redirection
