### ISSUE TITLE
Browser Language changes chart format

### ISSUE THREAD

**Issue by o-rayer** [metabase/metabase#10230] opened 2019-06-20 14:22 UTC
Hi,

With my browser in EN (US), I have a chart displaying a bar chart and a line. When I change my browser language to FR-FR (in Chrome advanced parameters), the same chart changes to two lines in different colors.

It is the same whether I'm in the Question or in the Dashboard. It happens on several charts (time series).

In EN (US) :
<img width="674" alt="Capture d’écran 2019-06-20 à 16 10 54" src="https://user-images.githubusercontent.com/36108313/59856099-821eee80-9376-11e9-9128-c13a866462a8.png">

In FR (FR):
<img width="662" alt="Capture d’écran 2019-06-20 à 16 10 23" src="https://user-images.githubusercontent.com/36108313/59856104-864b0c00-9376-11e9-8a52-828187d8d5db.png">

- Your browser and the version: Chrome Version 75.0.3770.100
- Your operating system: OS X Mojave 10.14.2
- Your databases: Postgres
- Metabase version: 0.31.1
- Metabase hosting environment: AWS
- Metabase internal database: Postgres

I hope these info are complete enough,

Thanks !

**Comment by flamber** [comment] 2019-06-20 18:10
Hi @o-rayer 
Duplicate of #9376.
I think it was fixed by PR #9350. I cannot reproduce on 0.32.9

**Closed** 2019-06-20 18:23 UTC
Labels: Bug, Duplicate
