### ISSUE TITLE
Dashboard  Subscriptions do not respect number multiplication

### ISSUE THREAD

**Issue by thomasrehm** [metabase/metabase#21312] opened 2022-03-29 08:20 UTC
**Describe the bug**
When preparing data to view on dashboards, I've set up price fields in our database to be multiplied by 0.01 in the formatting settings, as the values are handled in cents for our tool. For the dashboards the value will be correctly multiplied and displayed as Euro.

When sending dashboard subscriptions, data is returned as non transformed value which is ugly and not really useful (except for full data downloads maybe).

Dashboard:
<img width="1192" alt="Bildschirmfoto 2022-03-29 um 10 24 00" src="https://user-images.githubusercontent.com/4144107/160567478-93d77736-7be6-496d-8421-c2832793d73b.png">

Subscription sent via mail 
<img width="515" alt="Bildschirmfoto 2022-03-29 um 10 24 07" src="https://user-images.githubusercontent.com/4144107/160567517-35e61ae7-f5e7-4e3d-99dc-8e040da2cd8d.png">

Same applies for Slack based subscriptions:
<img width="411" alt="Bildschirmfoto 2022-03-29 um 10 25 06" src="https://user-images.githubusercontent.com/4144107/160567607-bc0739b9-0463-4f5e-b047-c495ccf4a988.png">

**Expected behavior**
Values are transformed and handled the same way for subscriptions as they are for dashboards.

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "de-DE",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14+9",
    "os.name": "Linux",
    "os.version": "5.4.0",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-08",
      "tag": "v0.42.0",
      "branch": "release-x.42.x",
      "hash": "de1264e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
- Metabase version: v0.42.0
- Metabase hosting environment: Docker on VPS
- Metabase internal database: H2

**Severity**
Annoying. Makes Subscriptions not useable for us.

**Comment by flamber** [comment] 2022-03-29 08:27
Hi @thomasrehm 
Create a custom column instead, so the returned results are multiplied.
Duplicate of #3735
Latest release is 0.42.3: https://github.com/metabase/metabase/releases/latest
You should migrate away from H2 if you are using Metabase in production: https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html

**Closed by flamber** 2022-03-29 08:27 UTC
Labels: Type:Bug, .Needs Triage

**Comment by flamber** [comment] 2022-03-29 14:01
@thomasrehm Use Models https://www.metabase.com/docs/latest/users-guide/models.html or creating a view on the database.
