### ISSUE TITLE
when editing dashboard, dragging questions doesn't scroll browser

### ISSUE THREAD

**Issue by snarfed** [metabase/metabase#5333] opened 2017-06-14 16:50 UTC
hi all! when i'm moving questions/graphs around a dashboard in edit mode, the browser window doesn't scroll if i drag them up to the top or bottom and hold, so there's no easy way to move them more than a screen length up or down.

annoyingly this seems _somewhat_ browser specific. on mac os x 10.11.6, it happens in both firefox (53) and chrome (58), but _not_ safari (10.1.1). safari isn't great either though: while dragging a question and scrolling the browser, the question often "falls off" the mouse cursor.

metabase 0.24.2 on heroku (postgres), data in bigquery. minor, obviously. hope you all are good!

**Comment by mnzt** [comment] 2017-07-21 08:54
Confirmed on Chrome 58, Arch Linux, Metabase 0.24.2

**Comment by sarahmamy** [comment] 2018-06-15 08:51
Top 1 friction I'm experiencing so far 😄   Chrome Version 66.  MacOs High Sierra Version 10.13.4

**Comment by GrandathePanda** [comment] 2019-10-02 16:26
Very annoying.

**Comment by flamber** [comment] 2019-10-02 19:26
I just tried updating the package `react-draggable` to `^3.3.2` and then it scrolls on Firefox 69, but it still doesn't work Chromium 76. Not sure what the behavior is on Safari, Edge/IE or mobile.
Looks like it was fixed in https://github.com/mzabriskie/react-draggable/pull/261

**Comment by mazameli** [comment] 2019-12-17 00:12
Fixed by https://github.com/metabase/metabase/pull/11468

**Closed by mazameli** 2019-12-17 00:12 UTC
Labels: Reporting/Dashboards, Type:UX
