### ISSUE TITLE
Failed to save changes to the existing report/SQL query after latest version updation

### ISSUE THREAD

**Issue by Ravi9535** [metabase/metabase#40769] opened 2024-03-29 06:42 UTC
### Describe the bug

We have updated the Metabase to it's latest version currently 0.49.2 as on Mar-29-2024 now when we do some changes to the reports which are already saved in metabase we can't save changes to report once again.

### To Reproduce

1. Go to 'metabase'
2. Click on 'NEW - > SQL QUERY -> Select Database and write a query, run and save'
3. Now after save, do some changes to the same query and try to save the same query once again
4. It will show failed when you click on save (replace original question)

![about metabase](https://github.com/metabase/metabase/assets/66297271/15588594-3b2b-48f0-a740-725d697f1948)
![failed](https://github.com/metabase/metabase/assets/66297271/47dea86a-bb64-4409-9004-12723f1d9668)

### Expected behavior

It should allow us to edit and save as many times as earlier

### Information about your Metabase installation

```JSON
- METABASE 0.49.2
- CHROME Version 122.0.6261.111 (Official Build) (64-bit)
```

### Severity

Since this is last month of financial year we need some of the import information using reports

**Comment by ranquild** [comment] 2024-03-29 06:48
@Ravi9535 could you provide the logs? there should be an error when saving the question failed

**Comment by Ravi9535** [comment] 2024-03-29 07:30
Since many users are using the saved reports the log is too much and it is running. So what exactly should I share regarding that log

**Comment by paoliniluis** [comment] 2024-03-29 08:12
@Ravi9535 we need to see what happens in the server and in your browser when you click on save

**Comment by Ravi9535** [comment] 2024-03-29 09:44
Here is the Log
[log.log](https://github.com/metabase/metabase/files/14802373/log.log)

**Comment by paoliniluis** [comment] 2024-03-29 11:22
Are you using MySQL as the application database? Which version?

**Comment by Ravi9535** [comment] 2024-03-29 11:48
Yes,
mysql  Ver 14.14 Distrib 5.7.42, for Linux (x86_64) using  EditLine wrapper

**Comment by ssshreyans26** [comment] 2024-05-09 05:01
@ranquild Is this issue resolved in the latest version of metabase community? If not is there a temporary patch/fix that we can apply or do we need to revert to previous version?

**Comment by Ninx96** [comment] 2024-05-09 05:46
hi guys,
having same issue while trying to replace the existing query, did anyone find any solution for this ?, when will this issue be fixed ????

**Comment by Ninx96** [comment] 2024-06-05 06:04
hi @nemanjaglumac 

you can reproduce the issue by following the steps:

1. try to run & save a native query to any connected sql database (can be as simple as "select 1")
2. Once it is saved try to edit the same saved question (for example "select 2")
3. when the save Question popup opens up select "Replace original question" and try to save it 
4. it will get failed 


logs saying:

[9344d828-2654-460a-9612-26e7477ea086] 2024-06-05T11:22:41+05:30 DEBUG metabase.server.middleware.log PUT /api/card/1005 400 2.7 ms (0 DB calls) 
{:errors {:collection_preview "nullable boolean"},
 :specific-errors {:collection_preview ["should be a boolean, received: 1"]}}

**Comment by nemanjaglumac** [comment] 2024-06-05 14:48
This error is completely different from the original one that @Ravi9535 attached.

@Ninx96 are all these steps on the same version (if yes - which one?)? Or do you save an original question in one version (which one?) and then upgrade to some other version (which one?)?

**Comment by nemanjaglumac** [comment] 2024-06-05 15:53
Both @Ravi9535 and @Ninx96 - a really important missing piece of information - from which version you upgraded to v49?

**Comment by Tony-metabase** [comment] 2024-06-06 18:07
Are you sure that the upgrade went well? Do you have the logs when you performed the update cause it could be something went wrong there and that would point us to the issue.

Also same question what application DB are you using? If MYSLQ the minimum recommended version is 8.0.17

**Comment by nemanjaglumac** [comment] 2024-06-06 18:09
I spent A LOT of time trying to debug this. No matter what I do I cannot reproduce it.

For example:
Spun up v43 (43.4) and created two SQL questions.

```
select 1
```

and 

```

SELECT
  count(*)
FROM
  products
WHERE
  category = {{category}}
```

Saved both, and then upgraded to v49 (49.5)

I was able to modify both questions and to save them (both to override them and to save as new).
On top of that, I was able to create a new SQL in the version 49 and to then update it and override it.

There needs to be something very specific about your questions or your environments that is causing this error.
@Tony-metabase raised a good question about the MySQL version.

This is why we ask for the diagnostic info.

**Comment by johnswanson** [comment] 2024-06-06 19:42
This looks to be a duplicate of this issue: https://github.com/metabase/metabase/issues/40600

**Comment by nemanjaglumac** [comment] 2024-06-06 19:46
I'm closing this issue for the lack of the information, AND because it's most likely a duplicate.
Once #43296 gets merged to `master` and backported to `49` @Ravi9535 and @Ninx96 please check if that fixes an issue for you.

**Closed by nemanjaglumac** 2024-06-06 19:46 UTC
Labels: Type:Bug, Priority:P2, .Unable to Reproduce, Querying/GUI, .Needs Clarification

**Comment by GizzmoAsus** [comment] 2024-10-18 07:40
@Ravi9535 I had this same issue against `v0.49.11` but upgrading to `v0.50.29` has resolved it.

@paoliniluis for reference the issue I was seeing in the logs/api response was as follows:

```
PUT /api/card/58 400 1.9 ms (0 DB calls)
{:errors {:collection_preview "nullable boolean"},
 :specific-errors {:collection_preview ["should be a boolean, received: 1"]}}
```

I thought it was because the query was a standalone one at the top level and not part of a collection but editing collection queries suffered the same issue but the latest version is working fine for me :)
