### ISSUE TITLE
Pulses don't honor column order

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#11936] opened 2020-02-18 23:22 UTC
**Describe the bug**
In table visualisation mode, I set column in specific order, but this setting is ignored in the pulse.

**Logs**
None.

**To Reproduce**
1. Create a simple question.
2. Reorder columns in table visualisation mode.
3. Create a pulse.
4. Observe the columns are in the order of the underlying table instead of table visualisation.

**Expected behavior**
Columns should be listed in the order set in table visualisation.

**Information about your Metabase Installation:**

`{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1; Windows for Workgroups 3.11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.15.0-66-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.29"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-02-04",
      "tag": "v0.34.2",
      "branch": "release-0.34.x",
      "hash": "dab738c"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}`

**Severity**
A nuisance, as I have to recreate the question from scratch.

**Additional context**
The columns actually come from joined saved SQL questions, if that matters.

**Comment by gazzer82** [comment] 2020-03-21 12:24
Just a quick, me too here, I have a daily pulse and am missing some essential columns due to the column limit, and it not honouring the custom column order set in the question.

**Comment by flamber** [comment] 2020-03-22 10:03
Very likely a duplicate of #3735, since formatting (visualization settings) isn't applied to pulses overall.

**Comment by markbastian** [comment] 2023-12-21 15:14
I believe this is fixed with the latest work on exports. See https://github.com/metabase/metabase/pull/36067 for reference. @adam-james-v

**Closed** 2023-12-21 15:56 UTC
Labels: Type:Bug, Priority:P3, Reporting/Pulses, Visualization/Chart Settings, Visualization/Static
