### ISSUE TITLE
Interactive dashboards with custom destination and  nginx for reverse proxy fail!

### ISSUE THREAD

**Issue by happydentist** [metabase/metabase#18928] opened 2021-11-10 03:32 UTC
Metabase version 0.41.0
    java -DMB_JETTY_PORT=3000 -DMB_SITE_URL=http://localhost:3000/mb/ -jar metabase.jar

nginx for reverse proxy
server {
  server_name             domain.com;

  location /mb/ {
    proxy_pass            http://localhost:3000/;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forward-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $http_x_forwarded_proto;
  }
}

I can use url http://domain.com/mb and watch the dashboard.

But I design Interactive dashboards with customizing click behavior on the question of dashboards, go to a custom destination over column, then save.
When I click the column that I design click behavior, it fail.
I look at the url and find the url ---> http://domain.com/dashboard/...    or http://dentsb-nuc.ddns.net/question#..................
I change the url by hand to        ---> http://domain.com/mb/dashboard/...   or http://dentsb-nuc.ddns.net/mb/question#.................. , it works.
How can resolve the problem?
I wonder the custom destination don't take the MB_SITE_URL for reference from metabase configure setting (metabase.db.mv.db)?

**Comment by flamber** [comment] 2021-11-10 08:34
Duplicate of #13602
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Closed by flamber** 2021-11-10 08:34 UTC
Labels: Type:Question, .Needs Triage
