### ISSUE TITLE
Timeline strange behavior when two x-axis displaying

### ISSUE THREAD

**Issue by shihyuuuuuuu** [metabase/metabase#27562] opened 2023-01-07 04:27 UTC
**Describe the bug**
The range of the timeline changes when I change the `scale` of the x-axis ( between `Timeseries` and `Ordinal`)

**To Reproduce**
1. I set the `JAVA_TIMEZONE` to `UTC` and the `Report Timezone` to `Asia/Taipei` (See `Metabase Diagnostic Info` below for details)
2. Create a chart with 2 x-axis and one of it is related to datetime
3. Swtich the `scale` setting of x-axis between `Timeseries` and `Ordinal`, and the range of the x-axis changed.
4. (See the screencast below for detail operations)

**Expected behavior**
The range of the x-axis should be the same even if I change the `scale`. I think the `scale` parameter should only change the display but not the value.

**Screenshots**
- When I use `Ordinal`, the time on the hover is the same as the axis shown below
- But when I use `Timeseries`, the hover time remains the same but is different from the axis value (the axis value is subtracted by 8 hours)

https://user-images.githubusercontent.com/17334269/211131386-1bad57ab-6988-4fc5-8479-772c1c8c9a5a.webm

**Severity**
Not that serious but increase confusion about the timezone settings

**Additional context**
In another situation, I just changed the number of x-axis shown, and the axis value changed.

[Screencast from 01-07-2023 12:26:14 PM.webm](https://user-images.githubusercontent.com/17334269/211130920-4a52e243-cd8c-4b7a-9df6-01ac2d888325.webm)

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "zh-TW",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.17+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.17",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.17+8",
    "os.name": "Linux",
    "os.version": "5.15.0-1025-gcp",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "bigquery-cloud-sdk",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.39-google-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-12-07",
      "tag": "v0.45.1",
      "branch": "release-x.45.x",
      "hash": "019d31c"
    },
    "settings": {
      "report-timezone": "Asia/Taipei"
    }
  }
}
```

**Comment by paoliniluis** [comment] 2023-02-23 15:22
@darksciencebase can you reproduce this with the sample dataset? I don't get how you can "Create a chart with 2 x-axis and one of it is related to datetime". You mean add 2 series?

**Comment by darksciencebase** [comment] 2023-02-23 15:43
@paoliniluis I think you wanted to tag @shihyuuuuuuu here

**Comment by zbodi74** [comment] 2024-04-29 09:39
@shihyuuuuuuu - closing this as I could not reproduce the above in v1.49. Please add instructions to reproduce and feel free to reopen if you're still seeing this behavior.

**Closed by zbodi74** 2024-04-29 09:39 UTC
Labels: Misc/Timezones, Reporting/
