### ISSUE TITLE
Y-axis range Max force cut-off

### ISSUE THREAD

**Issue by JadAbdallah** [metabase/metabase#16115] opened 2021-05-17 18:26 UTC
**Is your feature request related to a problem? Please describe.**
Visualization options with axes don't let you hard-code a cut-off point for the Y-axis. If there are data points above given value, it will automatically set the Y-axis Max at the largest value. This makes hiding outlier values impossible.  

**Describe the solution you'd like**
Possibility to set Max y-axis range regardless of range of a values in data set. 

**How important is this feature to you?**
Nice to have. Analyses with many outliers become distracting because of the noise.  

**Additional context**
Same feature with min would be nice. Essentially, the custom Y-axis range is only customizable to the range of the data set itself. It would be nice to be able to cut off any points that are not relevant to the visualization.

**Comment by flamber** [comment] 2021-05-17 18:42
Duplicate of #10434

**Closed by flamber** 2021-05-17 18:42 UTC
Labels: .Needs Triage, Type:New Feature
