### ISSUE TITLE
mysql table can not using date column index

### ISSUE THREAD

**Issue by xqwbx163** [metabase/metabase#9139] opened 2018-12-17 01:50 UTC
create new question-->custom--->select mysql table  ,
selecting the date through the time control, and get the result.
then Sql for this question,
you will find the time column  is converted that was  added with the date type conversion, 
if you take this sql into database ,which causes the MYSQL table to fail to obtain data quickly through the index, and only the full table scan can be performed.
This is a very serious problem.

![image](https://user-images.githubusercontent.com/20455410/50062244-17330600-01e1-11e9-816d-70b6c00f11c2.png)

**Comment by flamber** [comment] 2018-12-17 19:33
Hi @xqwbx163 
Which version of Metabase and MySQL are you using? What type is the column that is being converted to DATE()?
This might be related to issue #4043, but I'm not sure, since I don't understand your problem fully.

**Comment by flamber** [comment] 2018-12-22 04:37
If you read the comments in #4043, then multiple of them references other databases too, like Redshift, CrateDB, so I think it's a general bug on how Metabase handles the queries.

**Comment by heyuanh** [comment] 2018-12-22 04:57
Is it possible to modify this mysql driver file to fix this performance issue:
https://github.com/metabase/metabase/blob/1899ad3e864f3cc38c83774114346b0d42f2de93/src/metabase/driver/mysql.clj 

Basically, remove those functions: str_to_date(), date_format(), and date(), which operated on date-typed data connected from MySQL db, thereby queries on time-related columns can utilize  original indexing  provided by MySQL, so to improve query performance.

**Comment by nikita2206** [comment] 2019-05-03 16:46
Hey, I've made a relatively dirty fix for this (dirty in the sense of code quality/architecture, not that it breaks anything). If you need these optimizations you can use my branch from #9860 PR to build your own Docker image with them included. Hopefully I'll come up with something that we will be okay to merge later during the month.

**Comment by denis-troyan** [comment] 2019-08-27 07:21
Hey @nikita2206, could you clarify if the fix is coming in the public release any time soon?

**Comment by nikita2206** [comment] 2019-08-27 13:26
@denis-troyan no idea, my PRs have been there ignored for almost two months, maybe Metabase team are preparing a different implementation of their own though

**Comment by nikita2206** [comment] 2019-08-29 10:40
No problem, we're using a fixed fork at our company for now. Thanks for the update!

**Comment by camsaul** [comment] 2019-10-17 02:04
Implemented by #10980

**Closed by camsaul** 2019-10-17 02:04 UTC
Labels: Database/MySQL, Querying/Processor, Type:Performance

**Comment by flamber** [comment] 2020-01-02 19:58
@mazameli This was added to 0.33.4, but at least with MySQL it seems like it's not fixed #11502
When testing on 0.33.4 (and `master`) with MariaDB 10.4, I'm seeing date-columns wrapped in `date()`:
```
SELECT count(*) AS `count`
FROM `PEOPLE`
WHERE date(`PEOPLE`.`BIRTH_DATE`) BETWEEN date(date_add(now(), INTERVAL -10000 day))
   AND date(date_add(now(), INTERVAL -1 day))
```
POST /api/dataset :
```
{"database_id":4,"started_at":"2020-01-02T19:48:41.339Z","json_query":{"database":4,"type":"query","query":{"source-table":17,"filter":["and",["time-interval",["field-id",89],-10000,"day",{}]],"aggregation":[["count"]]},"parameters":[],"async?":true,"middleware":{"add-default-userland-constraints?":true,"userland-query?":true},"constraints":{"max-results":10000,"max-results-bare-rows":2000}},"average_execution_time":null,"status":"completed","context":"ad-hoc","row_count":1,"running_time":39,"data":{"rows":[[459]],"native_form":{"query":"SELECT count(*) AS `count` FROM `PEOPLE` WHERE date(`PEOPLE`.`BIRTH_DATE`) BETWEEN date(date_add(now(), INTERVAL -10000 day)) AND date(date_add(now(), INTERVAL -1 day))","params":null},"cols":[{"base_type":"type/Integer","special_type":"type/Number","name":"count","display_name":"Count","source":"aggregation","field_ref":["aggregation",0]}],"results_metadata":{"checksum":"YTIwS7d9TDP0SGr9cZq1zQ==","columns":[{"name":"count","display_name":"Count","base_type":"type/Integer","special_type":"type/Quantity","fingerprint":{"global":{"distinct-count":1,"nil%":0.0},"type":{"type/Number":{"min":459.0,"max":459.0,"avg":459.0,"sd":null,"q1":459.0,"q3":459.0}}}}]},"insights":null}}
```
GET /api/field/:id :
```
{"description":null,"database_type":"DATE","table_id":17,"table":{"description":null,"entity_type":"entity/UserTable","schema":null,"db":{"description":null,"features":["basic-aggregations","standard-deviation-aggregations","expression-aggregations","foreign-keys","right-join","left-join","native-parameters","nested-queries","expressions","set-timezone","binning","inner-join"],"cache_field_values_schedule":"0 50 0 * * ? *","timezone":"UTC","auto_run_queries":true,"metadata_sync_schedule":"0 50 * * * ? *","name":"mariadb-10.4","caveats":null,"is_full_sync":true,"updated_at":"2019-11-26T23:03:31.919Z","details":{...redacted...},"is_sample":false,"id":4,"is_on_demand":false,"options":null,"engine":"mysql","created_at":"2019-11-26T23:03:31.632Z","points_of_interest":null},"show_in_getting_started":false,"name":"PEOPLE","caveats":null,"fields_hash":"dnd7wWgZExKuKBEnHC9qvA==","rows":null,"updated_at":"2019-11-26T23:03:38.391Z","entity_name":null,"active":true,"id":17,"db_id":4,"visibility_type":null,"display_name":"People","created_at":"2019-11-26T23:03:32.089Z","points_of_interest":null},"special_type":"type/Birthdate","name":"BIRTH_DATE","fingerprint_version":4,"has_field_values":"none","settings":null,"caveats":null,"fk_target_field_id":null,"dimensions":[],"updated_at":"2020-01-02T19:47:54.993Z","active":true,"parent_id":null,"id":89,"last_analyzed":"2019-11-26T23:03:38.425Z","position":0,"visibility_type":"normal","preview_display":true,"display_name":"Birth Date","name_field":null,"fingerprint":{"global":{"distinct-count":2308,"nil%":0.0},"type":{"type/DateTime":{"earliest":"1958-04-26T06:00:00.000Z","latest":"2000-04-03T06:00:00.000Z"}}},"created_at":"2019-11-26T23:03:32.325Z","base_type":"type/Date","points_of_interest":null}
```

**Comment by amigold** [comment] 2020-05-07 16:49
Indeed this is still not fixed for MySQL

**Comment by flamber** [comment] 2020-05-07 16:56
@amigold Upvote #11502 by clicking :+1: on the first post

**Comment by shetaksroc** [comment] 2020-06-06 08:20
> Indeed this is still not fixed for MySQL

Yes

**Comment by ghomem** [comment] 2020-12-23 02:39
Reproducible with:

* v0.37.0-snapshot
* Maria DB 10.1

The date() function makes it impossible to using the existing timestamp index.

**Comment by flamber** [comment] 2020-12-23 10:51
@ghomem Upvote #11502 by clicking :+1: on the first post

**Comment by ghomem** [comment] 2020-12-23 10:57
Hi @flamber I already upvoted. Any idea where in the code this could be tweaked, while the official fix is not available? I have an example query that goes from 6 minutes (unusable!) to 18 seconds (slow but acceptable) with this change (tested the queries directly on the MariaDB client).

**Comment by flamber** [comment] 2020-12-23 11:12
@ghomem Check the code here: #13081

**Comment by ghomem** [comment] 2020-12-23 11:17
thank you @flamber

**Comment by ghomem** [comment] 2020-12-23 23:52
There is an additional note. 

Using expressions such this:

date(date_add(now(), INTERVAL -1 day))

instead of pre calculating the values prevents also the use of the database query cache. Only constant queries (ex: literal date instead of a function) appear to be cached by MariaDB.

And see that date() is being applied even when the filter field is a Date instead of DateTime.

**Comment by ghomem** [comment] 2021-01-05 03:49
We did a custom build with the code from #13081 and this is the result in regards to the generated queries.

With stock metabase:

```
SELECT `MYTABLE`.`logon` AS `logon`, sum(`MYTABLE`.`a_value`) AS `sum`
FROM `MYTABLE`
WHERE date(`MYTABLE`.`timestp`) BETWEEN date(date_add(now(), INTERVAL -30 day))
   AND date(date_add(now(), INTERVAL -1 day))
GROUP BY `MYTABLE`.`logon`
ORDER BY `sum` DESC, `MYTABLE`.`logon` ASC
LIMIT 50
```

With custom build

```
SELECT `MYTABLE`.`logon` AS `logon`, sum(`MYTABLE`.`a_value`) AS `sum`
FROM `MYTABLE`
WHERE (`MYTABLE`.`timestp_date` >= date(date_add(now(6), INTERVAL -30 day))
   AND `MYTABLE`.`timestp_date` < date(now(6)))
GROUP BY `MYTABLE`.`logon`
ORDER BY `sum` DESC, `MYTABLE`.`logon` ASC
LIMIT 50
```

We went from several minutes of wait on the stock build to 8-10 seconds on the custom build. I note, however, that with the custom build indexes are being used but the cache in *not* being used. If expressions  such as

```
date(date_add(now(6), INTERVAL -30 day))
```
were converted to constants, the query would return in miliseconds due to the MariaDB cache.
