### ISSUE TITLE
Permissions for saved questions cannot be updated, logs show error

### ISSUE THREAD

**Issue by Overbryd** [metabase/metabase#5605] opened 2017-07-27 13:26 UTC
I consider this a bug.

* Metabase version: 0.25.0
* Hosting environment: Running the metabase.jar CentOS 6 with Java 8
* Metabase internal database: MySQL

This is a screenshot from the operation I am trying to perform:

<img width="1440" alt="screen shot 2017-07-27 at 15 24 58" src="https://user-images.githubusercontent.com/21111/28672345-cceb7b90-72df-11e7-9a34-6b4b919cc011.png">

<img width="1439" alt="screen shot 2017-07-27 at 15 25 08" src="https://user-images.githubusercontent.com/21111/28672350-d1054bb6-72df-11e7-922e-272d6ea9a9d9.png">

This is the log output from updating the permissions:

```
2017-07-27T13:20:39.00662 07-27 13:20:39 ERROR metabase.middleware :: PUT /api/permissions/graph 500 (793 ?s) (0 DB calls)
2017-07-27T13:20:39.00665 {:type :schema.core/error,
2017-07-27T13:20:39.00666  :schema
2017-07-27T13:20:39.00666  [{:schema
2017-07-27T13:20:39.00666    {:revision Int,
2017-07-27T13:20:39.00666     :groups
2017-07-27T13:20:39.00666     {(constrained Int "Integer greater than zero")
2017-07-27T13:20:39.00667      {(constrained Int "Integer greater than zero")
2017-07-27T13:20:39.00667       (constrained
2017-07-27T13:20:39.00667        {(optional-key :native) (enum :read :write :none),
2017-07-27T13:20:39.00667         (optional-key :schemas) (cond-pre (enum :all :none) {Str (cond-pre (enum :all :none) {(constrained Int "Integer greater than zero") (enum :all :none)})})}
2017-07-27T13:20:39.00668        "DB permissions with a valid combination of values for :native and :schemas")}}},
2017-07-27T13:20:39.00668    :optional? false,
2017-07-27T13:20:39.00668    :name new-graph}],
2017-07-27T13:20:39.00668  :value
2017-07-27T13:20:39.00668  [{:revision 0,
2017-07-27T13:20:39.00669    :groups
2017-07-27T13:20:39.00669    {1 {2 {:native :write, :schemas :all}, 3 {:native :write, :schemas :all}, -1337 {:native :read, :schemas :all}},
2017-07-27T13:20:39.00669     2 {2 {:native :write, :schemas :all}, 3 {:native :write, :schemas :all}},
2017-07-27T13:20:39.00669     3 {2 {:native :write, :schemas :all}, 3 {:native :write, :schemas :all}}}}],
2017-07-27T13:20:39.00669  :error [(named {:groups {1 {(not ("Integer greater than zero" -1337)) invalid-key}}} new-graph)],
2017-07-27T13:20:39.00670  :message "Input to update-graph! does not match schema: \n\n\t   [(named {:groups {1 {(not (\"Integer greater than zero\" -1337)) invalid-key}}} new-graph)]  \n\n",
2017-07-27T13:20:39.00670  :stacktrace
2017-07-27T13:20:39.00671  ["models.permissions$fn__20079$update_graph_BANG___20088.invoke(permissions.clj:476)"
2017-07-27T13:20:39.00671   "api.permissions$fn__39242$fn__39244.invoke(permissions.clj:73)"
2017-07-27T13:20:39.00671   "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:227)"
2017-07-27T13:20:39.00671   "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:222)"
2017-07-27T13:20:39.00672   "api.permissions$fn__39242.invokeStatic(permissions.clj:61)"
2017-07-27T13:20:39.00672   "api.permissions$fn__39242.invoke(permissions.clj:61)"
2017-07-27T13:20:39.00673   "middleware$enforce_authentication$fn__28960.invoke(middleware.clj:122)"
2017-07-27T13:20:39.00673   "api.routes$fn__40160.invokeStatic(routes.clj:70)"
2017-07-27T13:20:39.00674   "api.routes$fn__40160.invoke(routes.clj:70)"
2017-07-27T13:20:39.00674   "routes$fn__40781$fn__40782.doInvoke(routes.clj:75)"
2017-07-27T13:20:39.00674   "routes$fn__40781.invokeStatic(routes.clj:71)"
2017-07-27T13:20:39.00674   "routes$fn__40781.invoke(routes.clj:71)"
2017-07-27T13:20:39.00674   "middleware$log_api_call$fn__29059$fn__29061.invoke(middleware.clj:331)"
2017-07-27T13:20:39.00675   "middleware$log_api_call$fn__29059.invoke(middleware.clj:330)"
2017-07-27T13:20:39.00675   "middleware$add_security_headers$fn__29009.invoke(middleware.clj:245)"
2017-07-27T13:20:39.00675   "middleware$bind_current_user$fn__28964.invoke(middleware.clj:142)"
2017-07-27T13:20:39.00675   "middleware$maybe_set_site_url$fn__29013.invoke(middleware.clj:268)"]}
2017-07-27T13:20:39.00676 
```

**Comment by joeymiller** [comment] 2017-07-27 13:44
Was just about to report the exact same issue.

**Comment by caique-lima** [comment] 2017-07-27 18:45
Same here with Postgres Database

**Comment by camsaul** [comment] 2017-07-27 18:47
Duplicate of #5617.

The Saved Permissions DB isn't supposed to show up in the Permissions page since the permissions for using a query as a subquery is just based on the permissions of the original question.

We're talking about making permissions separately configurable in the future in #5610.

**Closed by camsaul** 2017-07-27 18:47 UTC

**Comment by salsakran** [comment] 2017-07-27 18:56
@joeymiller @caique-lima @Overbryd 
Are you trying to restrict access to nested queries or turn them off entirely?

**Comment by Overbryd** [comment] 2017-07-28 07:03
I am trying to give normal users access to saved questions in general.

At the moment this is not possible. And if a user (of group All Users)
tries to access a saved question from another account, he is denied.

The current workaround is to give this user admin rights. But that cannot
be longterm solution, and it cannot be applied to all users who would need
access to saved questions.

Sameer Al-Sakran <notifications@github.com> schrieb am Do. 27. Juli 2017 um
20:56:

**Comment by caique-lima** [comment] 2017-07-28 12:03
Exactly the same here. And give admin rights isn't an option. Just adding
more info I've tried to give access to an new user, and group, the
questions are created before the user and group.

**Comment by Overbryd** [comment] 2017-07-28 15:21
For me upgrading to **0.25.1** solved the issue. Thanks.
