### ISSUE TITLE
Category Filter on Native Query cannot recognize enum 

### ISSUE THREAD

**Issue by imfaridz** [metabase/metabase#7092] opened 2018-03-08 08:55 UTC
I found an error like this
![screenshot from 2018-03-08 15-51-21](https://user-images.githubusercontent.com/32382632/37141742-9b000bc8-22e8-11e8-9047-3f971b62301c.png)
```
ERROR: operator does not exist: "enum_orderItem_type" = character varying
Hint: No operator matches the given name and argument type(s).
You might need to add explicit type casts. Position: 787
```

But when I use custom query builder, the filter works just fine.
Any solution to this ?

Thanks.

=================================================================================
- Your browser and the version: Firefox 58.0.2
- Your operating system: Ubuntu
- Your databases:  Postgres,
- Metabase version: v0.28.1
- Metabase hosting environment: Docker, Linux/Coreos
- Metabase internal database:  Postgres

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by Gaabe** [comment] 2020-03-04 16:19
This makes filtering based on enum columns really hard, since it only works using a text field filter and casting it manually, so the person using the dashboard has to know all the possible values of the enum beforehand.

Any updates on this? it has been open for almost 2 years already.

**Comment by alexpusch** [comment] 2020-07-30 11:43
Still an issue on latest version

**Comment by matthieu-foucault** [comment] 2020-10-20 21:57
Ran into this on v0.36.6. The workaround from https://github.com/metabase/metabase/issues/1623#issuecomment-438376086 works as far as I can tell, but that involves editing the `metabase_field` data directly, which is always a bit scary:

```sql
update metabase_field set base_type='type/PostgresEnum', database_type = 'your_schema.your_enum_type' where id=42;
```

**Comment by jankatins** [comment] 2021-02-23 23:23
Adding an `=` OPERATOR also makes the field filters on ENUMs work:

form https://stackoverflow.com/a/43748427/1380673

```SQL
CREATE TYPE os_dim.job_type AS ENUM ('X','Y');

CREATE FUNCTION os_dim.cmp_job_type__text(_a os_dim.job_type, _b text)
    RETURNS boolean AS
    $func$
        SELECT _a = _b::os_dim.job_type;
    $func$
    LANGUAGE SQL IMMUTABLE STRICT;

CREATE OPERATOR = (
    leftarg = os_dim.job_type,
    rightarg = text,
    procedure = os_dim.cmp_job_type__text,
    COMMUTATOR = =,
    NEGATOR = !=,
    HASHES, MERGES
);
```

If you want to add that to all enums in a schema: 

```
CREATE OR REPLACE FUNCTION util.add_enum_comparison_operators(schema_name TEXT)
  RETURNS VOID AS
$func$
DECLARE
  r         RECORD;
  code_     TEXT;
  enum_name TEXT;
  cmp_func  TEXT;
BEGIN
  FOR r IN (
    SELECT DISTINCT
      n.nspname AS schema,
      t.typname AS name
    FROM pg_type t
    JOIN pg_enum e ON t.oid = e.enumtypid
    JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = schema_name
  )
    LOOP
      enum_name := r.schema || $$.$$ || r.name;
      cmp_func := r.schema || $$._cmp_$$ || r.name || $$__text$$;
      code_ := $$
    CREATE OR REPLACE FUNCTION $$ || cmp_func || $$(_a $$ || enum_name || $$, _b text)
    RETURNS boolean AS
    $f$
        SELECT _a = _b::$$ || enum_name || $$;
    $f$
    LANGUAGE SQL IMMUTABLE STRICT;

  -- no replace, so drop and recreate
  DROP OPERATOR IF EXISTS = ($$ || enum_name || $$, text);

  CREATE OPERATOR = (
    leftarg = $$ || enum_name || $$,
    rightarg = text,
    procedure = $$ || cmp_func || $$,
    COMMUTATOR = =,
    NEGATOR = !=,
    HASHES, MERGES
);$$;
      RAISE NOTICE 'Executing: %', code_;
      EXECUTE code_;
    END LOOP;
END
$func$ LANGUAGE 'plpgsql';

-- And call with 
SELECT util.add_enum_comparison_operators('public');
```

**Comment by thomasrehm** [comment] 2022-05-20 10:54
any update on this topic?

**Comment by metamben** [comment] 2022-06-27 20:29
I couldn't reproduce the issue. I tried field filter by an enum column in the native query editor and in a dashboard, both worked. A more exact description of the steps might help me reproduce the problem.

**Comment by clyfish** [comment] 2022-06-28 03:24
> I couldn't reproduce the issue. I tried field filter by an enum column in the native query editor and in a dashboard, both worked. A more exact description of the steps might help me reproduce the problem.

@metamben 

1. Browse a table with an enum column
2. Click `Filter by this column`
3. Check a value and click `Update filter`

Error message:
There was a problem with your question
Most of the time this is caused by an invalid selection or bad input value. Double check your inputs and retry your query.

Hide error details
Here's the full error message
ERROR: operator does not exist: ***.*** = character varying Hint: No operator matches the given name and argument types. You might need to add explicit type casts. Position: 491

**Comment by metamben** [comment] 2022-06-28 13:25
Closing this because it's not a problem with newer versions.

**Comment by clyfish** [comment] 2022-06-28 14:01
@metamben @flamber
I can reproduce the issue with latest metabase version.
My metabase version: v0.43.3
My postgresql version: 14.2
DDL of my table:
```sql
CREATE SCHEMA api;
CREATE TYPE api.contest_status AS ENUM ('pending', 'fetched', 'rejudged', 'manual', 'scored');
CREATE TABLE api.contest (
  id SERIAL PRIMARY KEY,
  title_slug VARCHAR(32) UNIQUE NOT NULL,
  url VARCHAR(256),
  title VARCHAR(32) NOT NULL,
  start_time TIMESTAMPTZ NOT NULL,
  duration INTEGER NOT NULL CHECK (duration > 0),
  status api.contest_status NOT NULL DEFAULT 'pending',
  attendance INTEGER
);

CREATE INDEX ON api.contest (status);
```

**Comment by metamben** [comment] 2022-06-28 17:49
I could reproduce the problem with Postgres 14 with [the exact steps](https://github.com/metabase/metabase/issues/7092#issuecomment-1168767202). I suspect the problem is caused by the schema other than `public`. For the `status` field above I have `type/*` and for the enum field I created I have `type/PostgresEnum`. It is the type `type/PostgresEnum` that triggers the cast which is missing here.

**Closed** 2022-06-30 18:07 UTC
Labels: Type:Bug, Priority:P2, Database/Postgres, Querying/Parameters & Variables, Querying/Native, Drainable:Yes
