### ISSUE TITLE
Allow users to mark entire schema as hidden

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4628] opened 2017-03-28 00:17 UTC
It would be useful to be able to mark entire schema as hidden, as we do for tables.

http://discourse.metabase.com/t/toggle-data-model-visibility-for-entire-database-schemas-at-once-instead-of-table-by-table/1307

**Comment by mazameli** [comment] 2017-03-28 00:21
I agree(ed). ;)
Dupe of #2086.

**Closed by mazameli** 2017-03-28 00:21 UTC
Labels: Admin Panel & Setup, Duplicate
