### ISSUE TITLE
Multi Series Charting - Combined Question broke after update to 0.32.1

### ISSUE THREAD

**Issue by tuaris** [metabase/metabase#9669] opened 2019-04-02 23:31 UTC
- Your browser and the version: Firefox 66.0
- Your operating system: FreeBSD 12.0-RELEASE
- Your databases: MariaDB
- Metabase version: 0.32.1
- Metabase hosting environment: Linux Debian
- Metabase internal database: Postgres

After updating to 0.32.1, dashboard with multi-series charts (specifically the ones made up from combined questions) "broke".  The charts show the same question for each of the series, but the data points appear to be correct.  

These screenshots describe the issue best.

**Before Update**:
![Before Update Screenshot](http://venus.morante.net/downloads/unibia/screenshots/Firefox_Screenshot_2019-04-02T23-29-48.023Z.png)

**After Update**:
![After Update Screenshot](http://venus.morante.net/downloads/unibia/screenshots/Firefox_Screenshot_2019-04-02T23-15-58.939Z.png)

This one changed more dramatically, and appears to have added in a trend line?.

**Before Update**:
![Before Update Screenshot](http://venus.morante.net/downloads/unibia/screenshots/Firefox_Screenshot_2019-04-02T23-32-24.273Z.png)

**After Update**:
![After Update Screenshot](http://venus.morante.net/downloads/unibia/screenshots/Firefox_Screenshot_2019-04-02T23-32-56.219Z.png)

**Comment by flamber** [comment] 2019-04-02 23:33
Duplicate of #9636

**Comment by tuaris** [comment] 2019-04-02 23:35
Ah okay.  Those didn't come up in my search.  Thanks.

**Comment by tlrobinson** [comment] 2019-04-03 05:19
Closing as duplicate of #9636

**Closed by tlrobinson** 2019-04-03 05:19 UTC
