### ISSUE TITLE
Snowflake TIME datatype does not give correct results in UI

### ISSUE THREAD

**Issue by TusharShrivastava** [metabase/metabase#20933] opened 2022-03-10 08:02 UTC
**Describe the bug**
I am using metabase locally and trying to run the below query selecting snowflake as a database.

```
select 
      '2021-06-19 04:45:00.000 +0000'::timestamp_tz as foo --expect to see June 19, 2021 4:45AM
     ,foo::Date --expect to see June 19, 2021 (if it says 12:00AM, that's fine)
     ,foo::time --expect to see 4:45AM
     ,foo::timestamp_ntz --expect to see June 19, 2021 4:45AM
```

Notice that in the UI in 3rd column foo::time shows 11:15 PM, however in the downloaded json it shows the expected result which is 4:45 AM. Currently the report timezone is set as database/default and Monday is selected as the Week start day in the admin settings.

On Metabase v0.42.0 go to `new -> sql query`
Select `snowflake` as a database
Run this query 
```
select 
      '2021-06-19 04:45:00.000 +0000'::timestamp_tz as foo --expect to see June 19, 2021 4:45AM
     ,foo::Date --expect to see June 19, 2021 (if it says 12:00AM, that's fine)
     ,foo::time --expect to see 4:45AM
     ,foo::timestamp_ntz --expect to see June 19, 2021 4:45AM
```
Observe the result on UI for `3rd column `and download the results as `json or xsl `to see the difference.

**Expected behavior**
Query should return the similar results in UI and in the downloaded reports for consistency

**Screenshots**

<img width="1374" alt="Screenshot 2022-03-10 at 12 13 29 PM" src="https://user-images.githubusercontent.com/79984925/157613585-145b759f-b3c1-4769-90eb-565ca8576be6.png">

Downloaded JSON:

[
  {
    "FOO": "2021-06-19T04:45:00Z",
    "FOO::DATE": "2021-06-19",
    "FOO::TIME": "04:45:00",
    "FOO::TIMESTAMP_NTZ": "2021-06-19T04:45:00"
  }
]

**Information about your Metabase Installation:**
- Your browser and the version: Chrome
- Your operating system: Mac os catalina 10.15.7
- Metabase version: v0.42.0

**Comment by flamber** [comment] 2022-03-10 08:42
Duplicate of #15876

**Closed by flamber** 2022-03-10 08:42 UTC
Labels: Type:Bug, .Needs Triage
