### ISSUE TITLE
Metabase in a sub directory still try to access "/app/assets/img/*" which causes many 404 errors

### ISSUE THREAD

**Issue by wxiaoguang** [metabase/metabase#11774] opened 2020-01-22 05:56 UTC
**Describe the bug**

Metabase in a sub directory (eg: http://site/metabase/ ) still try to access "/app/assets/img/*" in HTML head, which causes many 404 errors in browser's console:

```
<link rel="apple-touch-icon" sizes="180x180" href="/app/assets/img/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/app/assets/img/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/app/assets/img/favicon-16x16.png">
<link rel="manifest" href="/app/assets/img/site.webmanifest">
<link rel="mask-icon" href="/app/assets/img/safari-pinned-tab.svg" color="#62a8e6">
<link rel="shortcut icon" href="/app/assets/img/favicon.ico">
<meta name="msapplication-TileColor" content="#2d89ef">
<meta name="msapplication-config" content="/app/assets/img/browserconfig.xml">
<meta name="theme-color" content="#ffffff">
<meta name="apple-mobile-web-app-status-bar-style" content="default" />
<meta name="base-href" content="/metabase/" />
```

**Expected behavior**

No 404 errors

**Information about your Metabase Installation:**

metabase-0.34.1

**Comment by dacort** [comment] 2020-01-24 23:04
Duplicate of #10743 - feel free to upvote that issue by adding a 👍 to the first comment!

**Closed by dacort** 2020-01-24 23:04 UTC
Labels: .Needs Triage, Type:Bug
