### ISSUE TITLE
[FRONT] Relative path vs absolute path

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#11900] opened 2020-02-13 00:25 UTC
**Describe the bug**
When using Metabase in a subpath deploy, the app works well but some features did not work, cuz uses an absolute path.

**Screenshots**
The React works well in `href="app/`:

![Screenshot from 2020-02-12 21-19-24](https://user-images.githubusercontent.com/6808348/74389653-a89a0a00-4ddd-11ea-82a6-1341648821e8.png)

But, some HTML metadata don't, cuz use an absolute path, like `href="/app/`:
![Screenshot from 2020-02-12 21-18-49](https://user-images.githubusercontent.com/6808348/74389696-c9faf600-4ddd-11ea-9aa2-138d4ad2a0f5.png)

**Severity**
Low, impact only in speed on redirects.

**Comment by flamber** [comment] 2020-02-13 21:35
Duplicate of #10743 (mostly, besides `site.webmanifest`) - upvote by clicking :+1: on the first post.

**Closed by flamber** 2020-02-13 21:35 UTC
Labels: .Duplicate, Type:Bug
