### ISSUE TITLE
Better syntax error reporting in the native query editor 

### ISSUE THREAD

**Issue by jfo8001** [metabase/metabase#30599] opened 2023-05-07 01:09 UTC
**Is your feature request related to a problem? Please describe.**
When I have a SQL syntax error, it tells me the number of the character in which the SQL query failed

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/106567118/236652496-96c9d2f5-fdfa-4a90-ace3-89ef1827e40e.png)
![image](https://user-images.githubusercontent.com/106567118/236652558-1c0dea51-ab1a-475a-a418-5284755db2b4.png)

I would like for the error screen to show exactly where character 7 is and/or highlight the error in the native code editor.
![image](https://user-images.githubusercontent.com/106567118/236652651-1cc1119f-5b50-4a3a-8a7e-9c4480bfb6c0.png)

Often times the native SQL help gives terrible advice to fix up SQL problems - saying the casing of my columns is incorrect, etc.  It would be more helpful to point out the place in the string where the SQL query failed.

**Describe alternatives you've considered**
A SQL linter would be nice to have https://github.com/sqlfluff/sqlfluff

**How important is this feature to you?**
I am having to open the javascript console and do this to get the actual error and it's slowing the team down. 

```
`select * from badSqlQuery`.substring(7)
```

**Comment by brunobergher** [comment] 2023-05-08 11:15
Closing this as a duplicate of #625. We're working on it right now though: #27468.

**Closed by brunobergher** 2023-05-08 11:15 UTC
Labels: Type:New Feature, .Needs Triage
