### ISSUE TITLE
Custom metrics: Ratio of 2 integers always returns 0

### ISSUE THREAD

**Issue by EBoisseauSierra** [metabase/metabase#10905] opened 2019-09-17 17:41 UTC
**Describe the bug**
My custom metrics always returns 0 when calculating the ratio of 2 (SQL) `integer`s — however, it works when the given metrics are `numeric(4,0)` (see comment).

**To Reproduce**
I think I'm a medium. For that, a few times a day, I toss a coin, predict whether it's head or tail, and compare the result. Here is the log of the past 3 months:
```sql
CREATE TABLE demo
(
    date date NOT NULL,
    successes integer NOT NULL,
    attempts integer NOT NULL,
    CONSTRAINT demo_pkey PRIMARY KEY (date)
);
```
```sql
INSERT INTO demo(date, successes, attempts)
    VALUES
    ('2019-6-1',8,27),
    ('2019-6-2',2,3),
    ('2019-6-3',19,20),
    ('2019-6-4',7,27),
    ('2019-6-5',5,14),
    ('2019-6-6',4,7),
    ('2019-6-7',8,10),
    ('2019-6-8',2,3),
    ('2019-6-9',4,10),
    ('2019-6-10',16,28),
    ('2019-6-11',2,28),
    ('2019-6-12',14,19),
    ('2019-6-13',12,30),
    ('2019-6-14',18,23),
    ('2019-6-15',4,4),
    ('2019-6-16',1,16),
    ('2019-6-17',1,2),
    ('2019-6-18',8,26),
    ('2019-6-19',12,27),
    ('2019-6-20',15,19),
    ('2019-6-21',15,27),
    ('2019-6-22',10,17),
    ('2019-6-23',5,5),
    ('2019-6-24',15,23),
    ('2019-6-25',3,5),
    ('2019-6-26',4,25),
    ('2019-6-27',14,15),
    ('2019-6-28',7,16),
    ('2019-6-29',9,18),
    ('2019-6-30',1,1),
    ('2019-7-1',0,3),
    ('2019-7-2',19,27),
    ('2019-7-3',13,21),
    ('2019-7-4',5,15),
    ('2019-7-5',1,1),
    ('2019-7-6',0,2),
    ('2019-7-7',2,4),
    ('2019-7-8',16,29),
    ('2019-7-9',2,6),
    ('2019-7-10',6,10),
    ('2019-7-11',5,8),
    ('2019-7-12',3,17),
    ('2019-7-13',2,3),
    ('2019-7-14',14,27),
    ('2019-7-15',20,29),
    ('2019-7-16',17,27),
    ('2019-7-17',3,10),
    ('2019-7-18',15,19),
    ('2019-7-19',2,20),
    ('2019-7-20',1,1),
    ('2019-7-21',15,16),
    ('2019-7-22',23,25),
    ('2019-7-23',6,20),
    ('2019-7-24',13,30),
    ('2019-7-25',20,25),
    ('2019-7-26',20,28),
    ('2019-7-27',7,9),
    ('2019-7-28',1,2),
    ('2019-7-29',1,10),
    ('2019-7-30',4,14),
    ('2019-7-31',5,13),
    ('2019-8-1',4,4),
    ('2019-8-2',22,25),
    ('2019-8-3',2,3),
    ('2019-8-4',3,20),
    ('2019-8-5',3,22),
    ('2019-8-6',16,19),
    ('2019-8-7',1,1),
    ('2019-8-8',8,20),
    ('2019-8-9',7,20),
    ('2019-8-10',9,20),
    ('2019-8-11',20,24),
    ('2019-8-12',0,5),
    ('2019-8-13',1,1),
    ('2019-8-14',7,29),
    ('2019-8-15',13,28),
    ('2019-8-16',11,12),
    ('2019-8-17',15,18),
    ('2019-8-18',12,15),
    ('2019-8-19',2,10),
    ('2019-8-20',2,2),
    ('2019-8-21',13,25),
    ('2019-8-22',9,10),
    ('2019-8-23',23,30),
    ('2019-8-24',0,9),
    ('2019-8-25',4,9),
    ('2019-8-26',2,22),
    ('2019-8-27',21,27),
    ('2019-8-28',16,17),
    ('2019-8-29',28,28),
    ('2019-8-30',15,28),
    ('2019-8-31',3,3);
```

I want Metabase to compute my daily success rate. For that, I start a question and create the relevant variable:

![success_rate](https://user-images.githubusercontent.com/37387755/65065028-8ceb1e80-d979-11e9-9e13-8bc00fbece12.png)

I then click on visualizing the results… and the success rate is always 0.

![not_working](https://user-images.githubusercontent.com/37387755/65065163-cfacf680-d979-11e9-859e-a6456aa315b9.png)

**Expected behavior**
I guess it should be something like:
```csv
"Date","Success","Trials","Success rate"
01/06/19,8,22,36.36%
02/06/19,13,25,52.00%
03/06/19,9,14,64.29%
04/06/19,11,11,100.00%
05/06/19,2,10,20.00%
06/06/19,9,15,60.00%
07/06/19,8,14,57.14%
08/06/19,10,20,50.00%
09/06/19,5,25,20.00%
10/06/19,1,13,7.69%
11/06/19,0,2,0.00%
12/06/19,6,8,75.00%
13/06/19,5,16,31.25%
14/06/19,11,25,44.00%
15/06/19,24,25,96.00%
16/06/19,3,9,33.33%
17/06/19,9,22,40.91%
18/06/19,10,26,38.46%
19/06/19,12,12,100.00%
20/06/19,7,22,31.82%
21/06/19,1,3,33.33%
22/06/19,9,10,90.00%
23/06/19,15,19,78.95%
24/06/19,3,7,42.86%
25/06/19,9,21,42.86%
26/06/19,5,10,50.00%
27/06/19,3,5,60.00%
28/06/19,14,25,56.00%
29/06/19,5,9,55.56%
30/06/19,4,28,14.29%
01/07/19,7,24,29.17%
02/07/19,1,2,50.00%
03/07/19,3,11,27.27%
04/07/19,2,8,25.00%
05/07/19,3,7,42.86%
06/07/19,19,27,70.37%
07/07/19,1,2,50.00%
08/07/19,11,21,52.38%
09/07/19,7,30,23.33%
10/07/19,1,2,50.00%
11/07/19,1,16,6.25%
12/07/19,4,15,26.67%
13/07/19,3,5,60.00%
14/07/19,0,5,0.00%
15/07/19,2,24,8.33%
16/07/19,5,22,22.73%
17/07/19,13,24,54.17%
18/07/19,7,23,30.43%
19/07/19,1,5,20.00%
20/07/19,6,14,42.86%
21/07/19,1,6,16.67%
22/07/19,25,30,83.33%
23/07/19,6,18,33.33%
24/07/19,10,13,76.92%
25/07/19,16,19,84.21%
26/07/19,6,8,75.00%
27/07/19,4,6,66.67%
28/07/19,1,19,5.26%
29/07/19,8,18,44.44%
30/07/19,7,16,43.75%
31/07/19,3,4,75.00%
01/08/19,5,7,71.43%
02/08/19,12,12,100.00%
03/08/19,3,28,10.71%
04/08/19,11,22,50.00%
05/08/19,17,27,62.96%
06/08/19,1,2,50.00%
07/08/19,14,15,93.33%
08/08/19,0,10,0.00%
09/08/19,1,12,8.33%
10/08/19,14,24,58.33%
11/08/19,1,2,50.00%
12/08/19,11,22,50.00%
13/08/19,9,19,47.37%
14/08/19,1,5,20.00%
15/08/19,9,16,56.25%
16/08/19,4,4,100.00%
17/08/19,12,25,48.00%
18/08/19,19,22,86.36%
19/08/19,17,29,58.62%
20/08/19,3,19,15.79%
21/08/19,3,21,14.29%
22/08/19,8,23,34.78%
23/08/19,22,23,95.65%
24/08/19,5,7,71.43%
25/08/19,2,3,66.67%
26/08/19,12,21,57.14%
27/08/19,20,28,71.43%
28/08/19,6,22,27.27%
29/08/19,9,16,56.25%
30/08/19,12,20,60.00%
31/08/19,5,25,20.00%
```

**Information about your Metabase Installation:**
- Your browser and the version: Firefox Developer Edition 70.0b6
- Your operating system: Fedora 30
- Your databases: Postgres
- Metabase version: 33.2
- Metabase hosting environment: Jar-file
- Metabase internal database: Postgres

**How severe an issue is this bug to you?**
~~It's quite annoying, because it makes the "Custom column" unreliable.~~
Minor, now that I know I can change my SQL data type for it to work. However, this might not be the case for other people.

**Additional context**
I guess given the results, I guess I'm not such a great medium, after all.

**Comment by EBoisseauSierra** [comment] 2019-09-17 17:48
Ok, I've narrowed down the issue:
**It doesn't work** with:
```sql
CREATE TABLE demo
(
    date date NOT NULL,
    successes integer NOT NULL,
    attempts integer NOT NULL,
    CONSTRAINT demo_pkey PRIMARY KEY (date)
);
```

but it **does work** with

```sql
CREATE TABLE demo
(
    date date NOT NULL,
    successes numeric(4,0) NOT NULL,
    attempts numeric(4,0) NOT NULL,
    CONSTRAINT demo_pkey PRIMARY KEY (date)
);
```

**Comment by sbelak** [comment] 2019-09-17 18:59
Dupe of #8783

**Closed by sbelak** 2019-09-17 18:59 UTC
Labels: Type:Bug
