### ISSUE TITLE
Unable to delete reference to Mongo DB database

### ISSUE THREAD

**Issue by cwbeck** [metabase/metabase#3259] opened 2016-08-23 11:05 UTC
*  I am using the Chrome browser.
*  My computer's OS is Mac.
*  I'm running Metabase on Docker (AWS) and it is using the _______ [Postgres / MySQL / H2 (default)] database.
*  My data is in a Mongo and BigQuery databases. 
*  My Metabase version is "You're running Metabase 0.19.3 which is the latest and greatest!."

When we go to remove the reference for MongoDB, we type "DELETE" and then the page just hangs forever. Encounter this each time. What is DELETE actually doing here?

![screen shot 2016-08-23 at 12 01 20](https://cloud.githubusercontent.com/assets/425262/17889762/cfa0c360-6929-11e6-8b62-b75829915685.png)

**Comment by salsakran** [comment] 2016-08-23 17:55
can you check the javascript console and the server logs for errors?

**Comment by cwbeck** [comment] 2016-08-24 09:02
@salsakran it took 24 hours, but it has now been deleted. I'm unable to check without re-adding and removing again.

**Comment by camsaul** [comment] 2016-09-01 01:37
@cwbeck if you get a chance, could you add your database again under a different name and then delete it and post the logs? It would be super helpful to our trying to diagnose this issue 👍

**Comment by camsaul** [comment] 2016-09-10 02:33
This sounds like a duplicate of #2655 (Page hangs when deleting database / takes forever to delete). Since we have console logs on that issue I'm going to close this as a duplicate.

**Closed by camsaul** 2016-09-10 02:33 UTC
Labels: Admin Panel & Setup, Bug, Duplicate, Need More Info
