### ISSUE TITLE
Value label settings messed up when having 3 or more y-axis

### ISSUE THREAD

**Issue by wfjsw** [metabase/metabase#13766] opened 2020-11-12 16:58 UTC
**Describe the bug**
When an chart have more than 3 y-axis, the following glitches would happen:
 - The value label of the first y-axis gone 0 without affecting other things.

Additionally, this always happen, regardless of how many y-axis are there:
 - The settings of first y-axis got applied to all of y's, including prefix, suffix, and multiplier etc.

**Logs**
Javascript logs:
```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://maps.google.com https://apis.google.com https://www.google-analytics.com https://*.googleapis.com *.gstatic.com  'sha256-lMAh4yjVuDkQ9NqkK4H+YHUga+anpFs5JAuj/uZh0Rs=' 'sha256-sMNbXyc1lLzhHbH/CKs11HIQMnMkZAN2eA99WhJeEC0=' 'sha256-JJa56hyDfUbgNfq+0nq6Qs866JKgZ/+qCq2pkDJED8k='". Either the 'unsafe-inline' keyword, a hash ('sha256-R8Vj/r6kkoQoKea75sN+pJH2skhDQEeMN3QX7Lv8cT4='), or a nonce ('nonce-...') is required to enable inline execution.

26:61 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://maps.google.com https://apis.google.com https://www.google-analytics.com https://*.googleapis.com *.gstatic.com  'sha256-lMAh4yjVuDkQ9NqkK4H+YHUga+anpFs5JAuj/uZh0Rs=' 'sha256-sMNbXyc1lLzhHbH/CKs11HIQMnMkZAN2eA99WhJeEC0=' 'sha256-JJa56hyDfUbgNfq+0nq6Qs866JKgZ/+qCq2pkDJED8k='". Either the 'unsafe-inline' keyword, a hash ('sha256-zDn3LxPTzpqF09uYqnbbDSlUHJituzczzuI+umLfDDc='), or a nonce ('nonce-...') is required to enable inline execution.

26:64 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://maps.google.com https://apis.google.com https://www.google-analytics.com https://*.googleapis.com *.gstatic.com  'sha256-lMAh4yjVuDkQ9NqkK4H+YHUga+anpFs5JAuj/uZh0Rs=' 'sha256-sMNbXyc1lLzhHbH/CKs11HIQMnMkZAN2eA99WhJeEC0=' 'sha256-JJa56hyDfUbgNfq+0nq6Qs866JKgZ/+qCq2pkDJED8k='". Either the 'unsafe-inline' keyword, a hash ('sha256-rk7lLvgs1PCWBsshqaE5rbDeyUqYl4GPEsGQahVLIg8='), or a nonce ('nonce-...') is required to enable inline execution.

26:1 
```

**To Reproduce**
1. Create a new question based on a 3 x n table
2. Set up 2 y-axis and 1 x-axis
3. Add 1 more y-axis

**Expected behavior**
Accurate data label represention

**Screenshots**
Before: 

![image](https://user-images.githubusercontent.com/2220320/98969767-27c59580-254a-11eb-9fc3-5ddd6f5f099c.png)

After: 

![image](https://user-images.githubusercontent.com/2220320/98969834-36ac4800-254a-11eb-99c0-d8220d7736c5.png)

Issues are marked with red rectangle.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome/86.0.4240.198
- Your operating system: Windows 10 20H2
- Your databases: MySQL
- Metabase version: v0.37.0.2
- Metabase hosting environment: Jar-file on Debian Buster
- Metabase internal database: PostgreSQL

**Severity**
As this misrepresents data it is a pretty critical issue.

**Comment by flamber** [comment] 2020-11-12 17:04
Duplicate of #13095

**Closed by flamber** 2020-11-12 17:04 UTC
Labels: .Needs Triage, Type:Bug
