### ISSUE TITLE
Filter type does not work with table aliasses

### ISSUE THREAD

**Issue by Tux** [metabase/metabase#38466] opened 2024-02-06 13:49 UTC
### Describe the bug

ERROR: invalid reference to FROM-clause entry for table "cte_issue_doof" Hint: Perhaps you meant to reference the table alias "d". Position: 306

### To Reproduce

Create three tables in your selection database. Probably also fails with two, but this mimics best what I found
```
psql> create table cte_issue_zoof (c integer, s varchar);
psql> create table cte_issue_woof (c integer, s varchar);
psql> create table cte_issue_doof (c integer, d date);
```
Create a new SQL query
```
with
  z as (
    select * from cte_issue_zoof
    )
select    dt, z.s
from      cte_issue_doof d
left join z                on z.c = d.c
left join cte_issue_woof w on w.c = d.c
[[  and   {{filter}}]]
;
```
In the right, the variable filter springs into existence. I just have access to a Dutch version as added in the screen-dump
![20240206142648](https://github.com/metabase/metabase/assets/2492/e0263715-27d4-43f2-bfef-f35f88634dbe)

The selection of the field does not offer me to choose from any of the table aliasses, so I need to choose a real table field (why it is capitalized that way puzzles me, but I can live with that). The query works when the optional filter has no value, but causes an error
```
ERROR: invalid reference to FROM-clause entry for table "cte_issue_doof" Hint: Perhaps you meant to reference the table alias "d". Position: 306
```
when the dropdown on to is used to select a period. As selection does not offer or understand table aliasses, this causes a deadlock. The filter field can select the required field on the right and the left cannot be written to use the filter (unless table aliasses are not used at all)

Besides that, it would make more sense to be able to have those filters available on the selected columns rather than what is in the original tables

### Expected behavior

The dropdown on the right should support the table aliasses d and z from the example or the field shoul be entered manually, like `d.dt`

### Information about your Metabase installation

```JSON
- Metabase v0.48.4 in docker (updated after I hit this issue in v0.46.6.4)
- PostgreSQL 13.7 .. 16.1
- Reproduced on openSUSE Leap 15.5 with Opera One 108.0.5047.0
```

### Severity

very annoying

### Additional context

Queries are written and tested outside of the Metabase ecosystem. When they work as expected, the SQL is copied into Metabase and filers are added where wanted. This means that the people that write the selection write it in a readable and maintainable way where overly long schema.table names are aliassed to something logical to the query, e.g. `males as (select * from person where gender = 'M')`. Having to expand all those aliasses in queries of sometimes over 100 lines just to be able to use this kind of filter is extremely annoying

**Comment by paoliniluis** [comment] 2024-02-06 14:09
duplicate of https://github.com/metabase/metabase/issues/3324

**Closed by paoliniluis** 2024-02-06 14:09 UTC
Labels: Type:Bug, .Needs Triage
