### ISSUE TITLE
FieldValues not getting deleted if field cardinality becomes > low-cardinality-threshold

### ISSUE THREAD

**Issue by nigeljyng** [metabase/metabase#3215] opened 2016-08-17 10:10 UTC
The column in my table has 128 unique values, but it's only showing the top 40 by alphabetical order. I think #2848 mentions this issue:

> It will only show up as a category picker if the underlying fields that are mapped to that parameter have less than 40 distinct values.

The behaviour is somewhat different for me. It shows up as a category picker, but only displays 40 values. Is there ay way we can display all values?
-  I'm running Metabase on AWS in Docker.
-  My data is in a SQLite db.
-  My Metabase version is v0.19.3

**Comment by salsakran** [comment] 2016-08-18 00:10
Yeah, our support for FieldValues is a big hokey. 

As a straw poll, do you think 128 values would make sense in a drop down?

**Comment by camsaul** [comment] 2016-08-18 01:01
@salsakran I don't think it makes sense to label this as a bug. The limit to the number of values in FieldValues is intentional behavior.

**Comment by salsakran** [comment] 2016-08-18 01:13
The reason I'm thinking it's a bug is:
If something has > 40 values, then we should skip it.
The fact that something went from <40 to above 40 and kept the old field values is a bug. 

Eg. there's now no way to filter by the newly added values.

**Comment by camsaul** [comment] 2016-08-18 01:15
Ok, in that case this sounds like a regression of #1499

**Comment by salsakran** [comment] 2016-08-18 01:23
either that or the analyze logic, as I don't know how else a column w/ a cardinality of 128 only has 40 field values stored.

**Comment by nigeljyng** [comment] 2016-08-18 08:50
I agree that it shouldn't be a dropdown if it has >40 values, wasn't sure if that was a bug or intended behaviour.

**Comment by ralf-rf** [comment] 2016-10-12 10:40
Could it become a search-suggest if there are more than 40 values? In our situation we have a client base with over 40 clients; and we would really like to find-select them by name. Is this a posibility? Or is there a way to change the threshold for capping the dropdown result?

**Comment by skwasha** [comment] 2017-01-13 21:32
Any updates on how this issue should/will be addressed? Thanks!

**Comment by camsaul** [comment] 2017-04-03 20:47
Fixed by #4677

**Closed** 2017-04-03 20:47 UTC
Labels: Bug, Metadata/Sync, Priority/P1
