### ISSUE TITLE
Category Filter with Optional Clauses for MS SQL Server not generating correct query 

### ISSUE THREAD

**Issue by probaner** [metabase/metabase#7368] opened 2018-04-18 10:07 UTC
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Ans: Firefox 59.0.2(64 bit)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
Ans: Windows 10
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Ans: MS SQL Server
- Metabase version: (e.x. 0.19.3)
Ans: V0.28.1
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Ans: metabase jar
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
Ans: H2

What works:
![image](https://user-images.githubusercontent.com/8830097/38925828-5a01e244-431e-11e8-8cee-b31bec05c87d.png)

What does not work : 
![image](https://user-images.githubusercontent.com/8830097/38925362-055f9d7c-431d-11e8-9bb4-b47eda969326.png)
The SQL generated when I use Category filter with Optional Clauses is not correct. Please refer to screen shot.

This is what I gent in console:

04-18 15:30:11 [1mERROR generic-sql.query-processor[0m :: nil
04-18 15:30:11 [1mWARN metabase.query-processor[0m :: {:status :failed,
 :class java.lang.Exception,
 :error "Incorrect syntax near the keyword 'IN'.",
 :stacktrace
 ["driver.generic_sql.query_processor$do_with_try_catch.invokeStatic(query_processor.clj:452)"
  "driver.generic_sql.query_processor$do_with_try_catch.invoke(query_processor.clj:448)"
  "driver.generic_sql.query_processor$execute_query.invokeStatic(query_processor.clj:502)"
  "driver.generic_sql.query_processor$execute_query.invoke(query_processor.clj:498)"
  "driver$fn__25552$G__25381__25559.invoke(driver.clj:51)"
  "query_processor$execute_query.invokeStatic(query_processor.clj:51)"
  "query_processor$execute_query.invoke(query_processor.clj:45)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__29796.invoke(mbql_to_native.clj:30)"
  "query_processor.middleware.annotate_and_sort$annotate_and_sort$fn__28210.invoke(annotate_and_sort.clj:41)"
  "query_processor.middleware.limit$limit$fn__29751.invoke(limit.clj:15)"
  "query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__29609.invoke(cumulative_aggregations.clj:58)"
  "query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__29609.invoke(cumulative_aggregations.clj:58)"
  "query_processor.middleware.format_rows$format_rows$fn__29741.invoke(format_rows.clj:26)"
  "query_processor.middleware.binning$update_binning_strategy$fn__28289.invoke(binning.clj:172)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__31145.invoke(results_metadata.clj:89)"
  "query_processor.middleware.resolve$resolve_middleware$fn__27818.invoke(resolve.clj:424)"
  "query_processor.middleware.expand$expand_middleware$fn__29498.invoke(expand.clj:569)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__27902.invoke(add_row_count_and_status.clj:14)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__29629.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__31156.invoke(resolve_driver.clj:15)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__28370.invoke(cache.clj:146)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__29546.invoke(catch_exceptions.clj:58)"
  "query_processor$process_query.invokeStatic(query_processor.clj:130)"
  "query_processor$process_query.invoke(query_processor.clj:126)"
  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:241)"
  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:235)"
  "query_processor$fn__31190$process_query_and_save_execution_BANG___31195$fn__31196.invoke(query_processor.clj:281)"
  "query_processor$fn__31190$process_query_and_save_execution_BANG___31195.invoke(query_processor.clj:267)"
  "api.dataset$fn__33291$fn__33294.invoke(dataset.clj:62)"
  "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:254)"
  "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)"
  "api.dataset$fn__33291.invokeStatic(dataset.clj:53)"
  "api.dataset$fn__33291.invoke(dataset.clj:53)"
  "middleware$enforce_authentication$fn__33152.invoke(middleware.clj:123)"
  "api.routes$fn__46098.invokeStatic(routes.clj:66)"
  "api.routes$fn__46098.invoke(routes.clj:66)"
  "routes$fn__46856$fn__46857.doInvoke(routes.clj:106)"
  "routes$fn__46856.invokeStatic(routes.clj:101)"
  "routes$fn__46856.invoke(routes.clj:101)"
  "middleware$log_api_call$fn__33251$fn__33253.invoke(middleware.clj:342)"
  "middleware$log_api_call$fn__33251.invoke(middleware.clj:341)"
  "middleware$add_security_headers$fn__33201.invoke(middleware.clj:255)"
  "core$wrap_streamed_json_response$fn__47651.invoke(core.clj:66)"
  "middleware$bind_current_user$fn__33156.invoke(middleware.clj:144)"
  "middleware$maybe_set_site_url$fn__33205.invoke(middleware.clj:279)"],
 :query
 {:type "native",
  :native
  {:query "SELECT [BRN_CODE]\n      ,[BRN_NAME]\n      ,[BRN_CLUSTER_ID]\n      ,[BRN_CLUSTER_NAME]\n  FROM [dbo].[T_BND_BRANCH_MASTER]\n  [[WHERE  BRN_ZONE_NAME = {{BRN_ZONE_NAME}}]]",
   :collection "CUSTOMER_GROUP_TEST1",
   :template_tags
   {:BRN_ZONE_NAME
    {:id "9b15ac4b-0a4b-bf02-b433-c1c8a7706ec2", :name "BRN_ZONE_NAME", :display_name "Brn zone name", :type "dimension", :dimension ["field-id" 486], :widget_type "category", :default nil}}},
  :parameters [{:type "category", :target ["dimension" ["template-tag" "BRN_ZONE_NAME"]], :value ["Mumbai"]}],
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :card-id nil,
   :nested? false,
   :query-hash [-33, -86, -107, -119, 107, 38, -120, -83, 15, 48, -102, -117, 70, -50, -20, -45, -115, 104, 84, -91, -94, -73, 87, 31, 75, 36, -39, 94, 8, 76, 15, -30],
   :query-type "native"}},
 :expanded-query nil}

04-18 15:30:11 [1mWARN metabase.query-processor[0m :: Query failure: Incorrect syntax near the keyword 'IN'.
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:209)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:202)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:242)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:235)"
 "query_processor$fn__31190$process_query_and_save_execution_BANG___31195$fn__31196.invoke(query_processor.clj:281)"
 "query_processor$fn__31190$process_query_and_save_execution_BANG___31195.invoke(query_processor.clj:267)"
 "api.dataset$fn__33291$fn__33294.invoke(dataset.clj:62)"
 "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:254)"
 "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)"
 "api.dataset$fn__33291.invokeStatic(dataset.clj:53)"
 "api.dataset$fn__33291.invoke(dataset.clj:53)"
 "middleware$enforce_authentication$fn__33152.invoke(middleware.clj:123)"
 "api.routes$fn__46098.invokeStatic(routes.clj:66)"
 "api.routes$fn__46098.invoke(routes.clj:66)"
 "routes$fn__46856$fn__46857.doInvoke(routes.clj:106)"
 "routes$fn__46856.invokeStatic(routes.clj:101)"
 "routes$fn__46856.invoke(routes.clj:101)"
 "middleware$log_api_call$fn__33251$fn__33253.invoke(middleware.clj:342)"
 "middleware$log_api_call$fn__33251.invoke(middleware.clj:341)"
 "middleware$add_security_headers$fn__33201.invoke(middleware.clj:255)"
 "core$wrap_streamed_json_response$fn__47651.invoke(core.clj:66)"
 "middleware$bind_current_user$fn__33156.invoke(middleware.clj:144)"
 "middleware$maybe_set_site_url$fn__33205.invoke(middleware.clj:279)"]

04-18 15:30:11 [1mDEBUG metabase.middleware[0m :: POST /api/dataset 200 (268 ms) (9 DB calls)

**Comment by flamber** [comment] 2019-02-19 22:57
Hi @probaner 
I hope you already found the solution, but in any case, here's the answer.
When using Field Filters, you should not include the column reference and operator, but only the variable.
Following your example, change your query to this:
```SQL
SELECT [BRN_CODE], [BRN_NAME], [BRN_CLUSTER_ID], [BRN_CLUSTER_NAME]
FROM [dbo].[T_BND_BRANCH_MASTER]
WHERE 1=1 [[AND {{BRN_ZONE_NAME}}]]
```
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#the-field-filter-variable-type

**Comment by camsaul** [comment] 2019-09-20 22:55
Closing this as an answered question (thanks @flamber) – not a bug

**Closed by camsaul** 2019-09-20 22:55 UTC
Labels: Priority:P2, Query Builder/Native, Type:Bug
