### ISSUE TITLE
Slow dashboard timing calls on a public dashboard trigger auth check

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4620] opened 2017-03-27 17:51 UTC
http://discourse.metabase.com/t/public-dashboard-jumps-to-auth-login-after-20-seconds-of-loading/1300

Seems like the call to get timing info on slow dashboard cards is calling a protected API endpoint.

**Comment by tlrobinson** [comment] 2017-03-27 17:56
Duplicate of #4557

**Closed by tlrobinson** 2017-03-27 17:56 UTC
Labels: Bug, Dashboards, Priority/P2
