### ISSUE TITLE
Static visualization for simple stacked lines fails

### ISSUE THREAD

**Issue by astrojuanlu** [metabase/metabase#26174] opened 2022-10-31 12:24 UTC
**Describe the bug**
Static visualization (tested with Slack) for a simple stacked lines plot fails with "An error occurred while displaying this card".

**Logs**

Server logs:

<details>

```
[5229d3a9-beb9-41b7-b71d-b4f86cf185ab] 2022-10-31T13:16:53+01:00 DEBUG metabase.server.middleware.log POST /api/pulse/test 200 1.3 s (29 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued); h2 DB 1 connections: 0/2 (0 threads blocked)
[5229d3a9-beb9-41b7-b71d-b4f86cf185ab] 2022-10-31T13:19:37+01:00 ERROR metabase.pulse.render Pulse card render error
TypeError: Cannot read property '1' of undefined
	at <js> ks(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:2111480-2111483)
	at <js> I(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:2139958-2139973)
	at <js> :anonymous(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:2139311-2140021)
	at <js> G(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:2139284-2140063)
	at <js> af(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:2139265-2140067)
	at <js> n(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:691758-691771)
	at <js> K(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:692776-692781)
	at <js> K.render(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:691107-692827)
	at org.graalvm.polyglot.Value.execute(Value.java:841)
	at metabase.pulse.render.js_engine$execute_fn_name.invokeStatic(js_engine.clj:48)
	at metabase.pulse.render.js_engine$execute_fn_name.doInvoke(js_engine.clj:42)
	at clojure.lang.RestFn.invoke(RestFn.java:490)
	at metabase.pulse.render.js_svg$combo_chart.invokeStatic(js_svg.clj:138)
	at metabase.pulse.render.js_svg$combo_chart.invoke(js_svg.clj:129)
	at metabase.pulse.render.body$lab_image_bundle.invokeStatic(body.clj:691)
	at metabase.pulse.render.body$lab_image_bundle.invoke(body.clj:665)
	at metabase.pulse.render.body$fn__58335$render__58324__58340$fn__58341.invoke(body.clj:699)
	at metabase.pulse.render.body$fn__58335$render__58324__58340.invoke(body.clj:697)
	at clojure.lang.MultiFn.invoke(MultiFn.java:261)
	at metabase.pulse.render$fn__58887$render_pulse_card_body__58892$fn__58896.invoke(render.clj:128)
	at metabase.pulse.render$fn__58887$render_pulse_card_body__58892.invoke(render.clj:118)
	at metabase.pulse.render$fn__58926$render_pulse_card__58931$fn__58932.invoke(render.clj:154)
	at metabase.pulse.render$fn__58926$render_pulse_card__58931.invoke(render.clj:142)
	at metabase.pulse$create_slack_attachment_data$iter__79774__79778$fn__79779.invoke(pulse.clj:140)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$filter$fn__5962.invoke(core.clj:2826)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$seq__5467.invoke(core.clj:139)
	at clojure.core$tree_seq$walk__6455$fn__6456.invoke(core.clj:4970)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:58)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$concat$cat__5560$fn__5561.invoke(core.clj:736)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$filter$fn__5962.invoke(core.clj:2826)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$filter$fn__5962.invoke(core.clj:2826)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:713)
	at clojure.core$next__5451.invokeStatic(core.clj:64)
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:169)
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_.invokeStatic(pulse.clj:211)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_.invoke(pulse.clj:202)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_.invokeStatic(pulse.clj:208)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_.invoke(pulse.clj:202)
	at metabase.pulse$fn__79934.invokeStatic(pulse.clj:391)
	at metabase.pulse$fn__79934.invoke(pulse.clj:389)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.util.retry$decorate$fn$reify__77154.call(retry.clj:42)
	at io.github.resilience4j.retry.Retry.lambda$decorateCallable$5(Retry.java:306)
	at metabase.util.retry$decorate$fn__77153.doInvoke(retry.clj:43)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.pulse$send_notification_retrying_BANG_.invokeStatic(pulse.clj:478)
	at metabase.pulse$send_notification_retrying_BANG_.doInvoke(pulse.clj:472)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at metabase.pulse$send_notifications_BANG_$fn__79974.invoke(pulse.clj:485)
	at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:484)
	at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:480)
	at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:508)
	at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:489)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.api.pulse$fn__81106.invokeStatic(pulse.clj:244)
	at metabase.api.pulse$fn__81106.invoke(pulse.clj:230)
	at compojure.core$wrap_response$fn__29289.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__29273.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__29278.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__29282.invoke(core.clj:151)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__29282.invoke(core.clj:153)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__29282.invoke(core.clj:153)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__29282.invoke(core.clj:153)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__29282.invoke(core.clj:152)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__70051.invoke(auth.clj:14)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301.invoke(core.clj:200)
	at compojure.core$make_context$handler__29329.invoke(core.clj:289)
	at compojure.core$make_context$fn__29333.invoke(core.clj:299)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$make_context$fn__29333.invoke(core.clj:300)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at metabase.api.routes$fn__81630$fn__81633.invoke(routes.clj:64)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__81793$fn__81794.doInvoke(routes.clj:67)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301.invoke(core.clj:200)
	at compojure.core$make_context$handler__29329.invoke(core.clj:289)
	at compojure.core$make_context$fn__29333.invoke(core.clj:299)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__29282.invoke(core.clj:153)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__29282.invoke(core.clj:153)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__29282.invoke(core.clj:153)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301$f__29302$respond_SINGLEQUOTE___29303.invoke(core.clj:197)
	at metabase.server.routes$fn__81779$fn__81781.invoke(routes.clj:45)
	at compojure.core$routes$fn__29301$f__29302.invoke(core.clj:198)
	at compojure.core$routes$fn__29301.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__78186.invoke(exceptions.clj:98)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__78183.invoke(exceptions.clj:86)
	at metabase.server.middleware.log$log_api_call$fn__83205$fn__83206$fn__83207.invoke(log.clj:211)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
	at metabase.server.middleware.log$log_api_call$fn__83205$fn__83206.invoke(log.clj:203)
	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:236)
	at toucan.db$_do_with_call_counting.invoke(db.clj:229)
	at metabase.server.middleware.log$log_api_call$fn__83205.invoke(log.clj:202)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__86311.invoke(browser_cookie.clj:38)
	at metabase.server.middleware.security$add_security_headers$fn__63426.invoke(security.clj:149)
	at metabase.server.middleware.json$wrap_json_body$fn__85263.invoke(json.clj:63)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__85281.invoke(json.clj:99)
	at metabase.server.middleware.offset_paging$handle_paging$fn__63450.invoke(offset_paging.clj:42)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__86578.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__86597.invoke(params.clj:77)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__36494.invoke(misc.clj:59)
	at metabase.server.middleware.session$reset_session_timeout$fn__48028.invoke(session.clj:394)
	at metabase.server.middleware.session$bind_current_user$fn__48011$fn__48012.invoke(session.clj:331)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:310)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:299)
	at metabase.server.middleware.session$bind_current_user$fn__48011.invoke(session.clj:330)
	at metabase.server.middleware.session$wrap_current_user_info$fn__47993.invoke(session.clj:280)
	at metabase.server.middleware.session$wrap_session_id$fn__47977.invoke(session.clj:213)
	at metabase.server.middleware.auth$wrap_api_key$fn__70059.invoke(auth.clj:27)
	at ring.middleware.cookies$wrap_cookies$fn__86498.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__36477.invoke(misc.clj:27)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__36502.invoke(misc.clj:76)
	at ring.middleware.gzip$wrap_gzip$fn__86540.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__36505.invoke(misc.clj:93)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__86327.invoke(ssl.clj:38)
	at metabase.server$async_proxy_handler$fn__82001.invoke(server.clj:73)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
```
</details>

**To Reproduce**
1. Create a new SQL query from the sample database with these contents:

```sql
SELECT
  TO_CHAR(CREATED_AT, 'yyyy-mm') AS created_at_month,
  PRODUCT_ID,
  SUM(QUANTITY) as sum_quantity
FROM ORDERS
GROUP BY
  TO_CHAR(CREATED_AT, 'yyyy-mm'),
  PRODUCT_ID
ORDER BY
  created_at_month ASC,
  PRODUCT_ID ASC
LIMIT 10
```

2. Plot it with stacked lines as follows:

![image](https://user-images.githubusercontent.com/316517/199006680-dff02598-e32f-447c-be58-d63af897c485.png)

3. Add it to a dashboard
4. Try sending the dashboard to Slack
5. See this in Slack:

![image](https://user-images.githubusercontent.com/316517/199006758-9f31126d-e34f-4166-8d1f-83c449b10a8f.png)

**Expected behavior**
The plot renders as I see it on Metabase.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox
- Your operating system: Linux Mint
- Your databases: PostgreSQL
- Metabase version: 0.44 and 0.45-RC1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
I don't see a workaround and I can't make it to work, so it's somewhat severe.

**Additional context**
Potentially related to gh-20752 and possibly others like gh-19525.

**Comment by flamber** [comment] 2022-10-31 12:31
Duplicate of #20752
You have "gaps" in data - if you add `WHERE PRODUCT_ID!=34` then it'll work.
![image](https://user-images.githubusercontent.com/1447303/199008084-a69c58f1-8a68-4ea6-b44d-8b68af22120a.png)

**Closed by flamber** 2022-10-31 12:31 UTC
Labels: Type:Bug, .Needs Triage

**Comment by astrojuanlu** [comment] 2022-11-21 09:19
Progress, the plot appears in 0.45.0-RC2 👍🏽 

But it's kind of cursed:

![image](https://user-images.githubusercontent.com/316517/203012394-bcdcc1b3-a57c-466a-b360-5a771e1b57a1.png)

Original:

![image](https://user-images.githubusercontent.com/316517/203012480-37895dfd-0cfa-4795-bf2f-a5d19044a0b6.png)

@flamber Could this be reopened?

**Comment by flamber** [comment] 2022-11-21 09:36
@astrojuanlu Let's create new issues for new problems.
