### ISSUE TITLE
Scrollbars appear on chart settings when language not English

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#21405] opened 2022-03-31 23:51 UTC
**Describe the bug**
When the language is not english, we tend to enlarge the container where the chart settings are and scrollbars appear.

**Logs**
NA

**To Reproduce**
1) Set up the instance with a different language than english (spanish can be)
2) make a question (e.g.: average of price per vendor per month)
3) go to settings of the chart, see the scrollbars

**Expected behavior**
No scrollbars please 🙏🏻

**Screenshots**
![image](https://user-images.githubusercontent.com/1711649/161167674-53f41b32-fd5c-4aa0-b18f-5360d5839465.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 20.04
- Your databases: H2
- Metabase version: 42.3
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Cosmetic

**Additional context**
NA

**Comment by flamber** [comment] 2022-04-22 14:32
Duplicate of #11241

**Closed by flamber** 2022-04-22 14:32 UTC
Labels: Type:Bug, Priority:P3, Visualization/Chart Settings, Customization/i18n, .Frontend
