### ISSUE TITLE
Can't view nested saved questions without data access permissions

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11028] opened 2019-10-01 18:54 UTC
Originally reported by @flamber. I'm calling this a P2 initially because I'm unsure how prevalent this use case is (user group with no data permissions attempting to view a nested question).

To reproduce:
- As an admin, create a nested saved question (it can use a GUI or SQL question; doesn't matter)
- Put the source saved question and the nested saved question into collections that a user group has View access to. It can be the same collection.
- For your test user group, revoke data access permissions to the database that the saved questions are based on.
- Log in with a user that's a member of that locked-down group, then navigate to the collection that has the nested question and click on it.
- The question will never finish loading.
- However, if that user clicks on the _source_ saved question, it loads just fine.

What's interesting is that if you give that user group data access to just one table in the database that the source saved question is based on, even if it's not the table that question is based on, the nested question loads just fine.

There don't appear to be any server log errors, but the JS console has a few:

```
Warning: Unknown props `collectionId`, `dispatch`, `fetchList`, `fetch`, `create`, `update`, `setArchived`, `setCollection`, `fetched`, `loading`, `error`, `reload`, `object`, `remove` on <a> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in a (created by Link)
    in Link (created by BaseLink)
    in BaseLink (created by Link)
    in Link (created by MaybeLink)
    in MaybeLink (created by Badge)
    in Badge (created by CollectionBadge)
    in CollectionBadge (created by EntityObjectLoader)
    in EntityObjectLoader (created by Connect(EntityObjectLoader))
    in Connect(EntityObjectLoader) (created by EntityType)
    in EntityType (created by EntityObjectLoader)
    in EntityObjectLoader (created by CollectionBadge)
    in CollectionBadge (created by ViewTitleHeader)
    in div (created by ViewSubHeading)
    in ViewSubHeading (created by ViewTitleHeader)
    in div (created by ViewTitleHeader)
    in div
    in Clean.div (created by Flex)
    in Flex (created by ViewSection)
    in ViewSection (created by ViewTitleHeader)
    in ViewTitleHeader (created by Unknown)
    in div (created by Unknown)
    in Unknown (created by View)
    in div (created by View)
    in div (created by View)
    in View (created by QueryBuilder)
    in QueryBuilder (created by FitViewport)
    in FitViewport (created by Title[FitViewport])
    in Title[FitViewport] (created by QueryBuilder)
    in QueryBuilder (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider
```

```
Error loading metadata for card TypeError: Cannot read property 'schemaNames' of null
    at Table.hasSchema (Table.js:39)
    at getDataSourceParts (QuestionDataSource.jsx:49)
    at Function.webpackJsonp../query_builder/components/view/QuestionDataSource.jsx.QuestionDataSource.shouldRender (QuestionDataSource.jsx:23)
    at ViewTitleHeader.render (ViewHeader.jsx:134)
    at ViewTitleHeader.<anonymous> (makeAssimilatePrototype.js:15)
    at ReactCompositeComponent.js:793
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:792)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:819)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:743)
```

```
Uncaught (in promise) TypeError: Cannot read property 'schemaNames' of null
    at Table.hasSchema (Table.js:39)
    at getDataSourceParts (QuestionDataSource.jsx:49)
    at Function.webpackJsonp../query_builder/components/view/QuestionDataSource.jsx.QuestionDataSource.shouldRender (QuestionDataSource.jsx:23)
    at ViewTitleHeader.render (ViewHeader.jsx:134)
    at ViewTitleHeader.<anonymous> (makeAssimilatePrototype.js:15)
    at ReactCompositeComponent.js:793
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:792)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:819)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:743)
```

```
Uncaught TypeError: Cannot read property 'schemaNames' of null
    at Table.hasSchema (Table.js:39)
    at getDataSourceParts (QuestionDataSource.jsx:49)
    at Function.webpackJsonp../query_builder/components/view/QuestionDataSource.jsx.QuestionDataSource.shouldRender (QuestionDataSource.jsx:23)
    at ViewTitleHeader.render (ViewHeader.jsx:134)
    at ViewTitleHeader.<anonymous> (makeAssimilatePrototype.js:15)
    at ReactCompositeComponent.js:793
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:792)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:819)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:743)
```

```
Table.js:39 Uncaught (in promise) TypeError: Cannot read property 'schemaNames' of null
    at Table.hasSchema (Table.js:39)
    at getDataSourceParts (QuestionDataSource.jsx:49)
    at Function.webpackJsonp../query_builder/components/view/QuestionDataSource.jsx.QuestionDataSource.shouldRender (QuestionDataSource.jsx:23)
    at ViewTitleHeader.render (ViewHeader.jsx:134)
    at ViewTitleHeader.<anonymous> (makeAssimilatePrototype.js:15)
    at ReactCompositeComponent.js:793
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:792)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:819)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:743)
```

@flamber also reported seeing these errors:
```
TypeError: prevComponentInstance is null
TypeError: this._query.table(...) is null
```

**Comment by ferarnoled** [comment] 2019-10-07 14:37
Same thing for me. Also I don't know if this is related to only this bug or to all bugs in general. After I got the JS error you mentioned I can't sign out, I have to reload the page. This goes to an unexpected state so not sure if that would qualify as another bug.

**Comment by flamber** [comment] 2019-10-07 18:47
@ferarnoled The uncaught type errors can do that, but it doesn't qualify for as another bug, since this is the root cause.

**Comment by stephanvd** [comment] 2019-11-06 08:09
We're dealing with something similar to this. A group with no permissions to the database, but has it's own sub-collection. One source question which pre-filters some data for their company only. A sub-question showing a graph on that data. They can view the source question, but not the sub question.

**Comment by camsaul** [comment] 2019-11-15 01:30
Is this the same issues as #11297 ?

**Comment by flamber** [comment] 2019-11-15 01:53
@camsaul 
No, because I stumbled upon this in mid-September (before 0.33.4). It sounds very similar though, but this is Saved Questions (both Custom and SQL). It breaks the UI and need refresh to recover.
I did a test on 0.32.10, 0.33.0, 0.33.2 and 0.33.3, and they all failed. Check your mail for test db.

**Comment by flamber** [comment] 2019-11-20 21:13
On 0.33.6 I'm now able to view a nested question without filters.
But cannot view a nested question with filters - it generates errors like this:
`Error loading metadata for card TypeError: "this.db is null"`
`TypeError: this._query.table(...) is null`
`TypeError: this.db is null`
`TypeError: n is null`
And that breaks the interface, so needs a browser refresh to recover.

**Comment by flamber** [comment] 2020-05-04 17:03
This was likely fixed completely by #11579, but there's no specific test for it (afaik), so not closing.

**Comment by camsaul** [comment] 2020-06-15 20:27
@flamber this sounds sort of similar to #12354, which was fixed in the last few weeks. @dacort added a test for that in #12525. Do you think those cover this issue as well?

**Comment by flamber** [comment] 2020-06-15 22:14
@camsaul This doesn't error in the log like #12354, just broke the frontend completely.
Just re-tested (didn't test May 4th), and it seems like it stopped working again in 0.34.2 thru 0.35.4
It does work on `master` - should it get a dedicated test, since this is Saved Question, not Sub-Query?

**Closed** 2020-06-16 10:53 UTC
Labels: Administration/Permissions, Priority:P2, Querying/Nested Queries, Type:Bug
