### ISSUE TITLE
Can't add 12'th column

### ISSUE THREAD

**Issue by steelunicorn** [metabase/metabase#10208] opened 2019-06-18 12:54 UTC
Strange issue here. I can't add 12+'th column into table. 
Added custom expression which is just "= sum(income)", but it doesn't added to table columns, and I can't add it manually in table options. 
But the query works without errors, and shows 11 columns that was added first.
Moreover, the query results in json have this column and data for it.

![image](https://user-images.githubusercontent.com/20414473/59682489-06d70480-91df-11e9-990f-716adf9fb0ce.png)
![image](https://user-images.githubusercontent.com/20414473/59683588-1b1c0100-91e1-11e9-8540-6c66f9c17b50.png)

Metabase v0.32.9 jar file, hosted on Win 8.1 Pro

**Comment by flamber** [comment] 2019-06-18 13:53
Hi @steelunicorn 
If you cannot select `income` directly from "Sum of ...", then it's probably an incorrect Field Type:
Admin > Data Model > (database) > (table) > (column) :gear:
Or it might be something at the database level, what is the actual column type?

**Comment by steelunicorn** [comment] 2019-06-18 14:27
I can select it directly with same result actually. The reason that I'm using custom expression is that so I can set custom name for column instead of just another "Sum".
Actual column type of this column in databse is numeric. 

The problem btw is not with particular column, a can't add any column with any possible aggregation.

**Comment by flamber** [comment] 2019-06-18 14:36
Okay, I cannot reproduce this issue.
Do you see any warnings/errors in the browser console?

**Comment by steelunicorn** [comment] 2019-06-18 14:54
Quick update.
Just tried to zoom into one row, and got missing columns to show. 
After zooming out those fields became visible for entire table. 
No errors in log. 
Zooming resulted this warning in console: 
![image](https://user-images.githubusercontent.com/20414473/59694875-f5e3be80-91f1-11e9-88b3-31e2d949d726.png)

**Comment by flamber** [comment] 2019-06-18 15:34
Okay, it sounds you might be  seeing a combination of #6670 and/or #9144

**Comment by mazameli** [comment] 2019-10-10 20:22
This should be fixed in any version of Metabase after 0.32.10. Are you still experiencing this @steelunicorn?

**Comment by flamber** [comment] 2020-03-04 13:06
Closing since this was most likely fixed in 0.32.10.
If you're still experiencing problems, then please comment.

**Closed by flamber** 2020-03-04 13:06 UTC
Labels: Priority:P2, Querying/GUI, Type:Bug
