### ISSUE TITLE
Sorting does not work

### ISSUE THREAD

**Issue by maksim2042** [metabase/metabase#2880] opened 2016-07-05 03:50 UTC
If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is MacOS ; server is Ubuntu 14.
*  I'm running Metabase on a DigitalOcean Ubuntu instance. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is Postgres 9.3.
*  My Metabase version is ___________. ((( latest Jar -- installed yesterday )))

Sequence of events:
* Create a question
* add a GroupBy
* try to add an Order By -- the entire page crashes; system needs to be reloaded. 

JavaScript Console is clean; system log is clean.

**Comment by tomkanjam** [comment] 2016-07-05 14:55
Duplicate of https://github.com/metabase/metabase/issues/2859

**Closed** 2016-07-05 17:58 UTC
