### ISSUE TITLE
After upgrading from 0.47 to 0.48.3 some dashboards does not open. Rollback was not possible to 0.47 without recreating internal Postgres database!!

### ISSUE THREAD

**Issue by Drconstantino** [metabase/metabase#37689] opened 2024-01-15 12:02 UTC
### Describe the bug

Hi,
I've made the upgrade of my test metabase instance from 0.47.9 to 0.48.3 in order to test this migration before implementing in production. However, some dashboards don't load.
I've attached the log,console export and the har file. Please help

### To Reproduce

Update from 0.47.9 to 0.48.3

### Information about your Metabase installation

```JSON
chrome 117.0.5938.132
```

### Severity

Blocking

**Comment by Drconstantino** [comment] 2024-01-15 12:07
also included log after rollback to 0.47.9. Metabase does not start
[output_afterrollback.zip](https://github.com/metabase/metabase/files/13938693/output_afterrollback.zip)

**Comment by paoliniluis** [comment] 2024-01-15 12:08
did you restore a database backup? or you just switched the image?

either way, I would strongly suggest you stay in v48 and try to recreate the dashboards, as the APIs do return data, there has to be something on the frontend

**Comment by paoliniluis** [comment] 2024-01-15 12:10
By the way, the first zip file has a lot of personal data uploaded, like your house floorplan, your couple's name,etc. Any bad actor can impersonate you and even find where you live. I would strongly suggest you remove that file and even ask Github to remove all traces of it, as it really compromises your security

**Comment by Drconstantino** [comment] 2024-01-15 14:23
Thank you! I already removed the file. 
In regards with the upgrade, I upgraded the JAR and the dashboards were returning:
"2024-01-15 11:56:09,723 WARN malli.fn :: Invalid input - Please report this as an issue on Github: ["invalid type"] {:type :metabase.util.malli.fn/invalid-input, :error {:schema :map, :value nil, :errors ({:path [], :in [], :schema :map, :value nil, :type :malli.core/invalid-type})}, :humanized [invalid type], :schema :map, :value nil, :fn-name query-hash}
"
I have multiple dashboards that are not working, so I cannot aford to recreate all of them.
After not being able to view the dashboards, I restore the jar with the old version and the instance does not start with the error:
"2024-01-15 12:05:21,187 ERROR metabase.core :: Metabase Initialization FAILED
clojure.lang.ExceptionInfo: ERROR: relation "data_migrations" does not exist
  Position: 15 {:toucan2/context-trace [["execute SQL with class com.mchange.v2.c3p0.impl.NewProxyConnection" {:toucan2.jdbc.query/sql-args ["SELECT * FROM \"data_migrations\""]}] ["resolve connection" {:toucan2.connection/connectable metabase.db.connection.ApplicationDB}] ["resolve connection" {:toucan2.connection/connectable :default}] ["resolve connection" {:toucan2.connection/connectable nil}] {:toucan2.pipeline/rf #object[clojure.core$map$fn__5931$fn__5932 0x55986125 "clojure.core$map$fn__5931$fn__5932@55986125"]} ["with compiled query" {:toucan2.pipeline/compiled-query ["SELECT * FROM \"data_migrations\""]}] ["with built query" {:toucan2.pipeline/built-query {:select [:*], :from [[:data_migrations]]}}] ["with resolved query" {:toucan2.pipeline/resolved-query {}}] ["with parsed args" {:toucan2.pipeline/query-type :toucan.query-type/select.instances.fns, :toucan2.pipeline/parsed-args {:queryable {}}}] ["with model" {:toucan2.pipeline/model :model/DataMigrations}] ["with unparsed args" {:toucan2.pipeline/query-type :toucan.query-type/select.instances.fns, :toucan2.pipeline/unparsed-args (:model/DataMigrations)}]]}
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:67)
	at toucan2.jdbc.query$reduce_jdbc_query.invokeStatic(query.clj:40)"

After this, the only option was to restore the postgres database from production copy with pg_dump/pg_restore and the old v0.47.9 started working on TST env again.

**Comment by calherries** [comment] 2024-01-15 15:30
The logs from the instance you started after restoring the jar with the old version suggests you didn't rollback the database successfully. See the docs: https://www.metabase.com/docs/latest/installation-and-operation/upgrading-metabase
You need to run the migrate down command `java -jar metabase.jar migrate down` _before_ restoring the old jar and starting the instance again with the old version.

**Comment by Drconstantino** [comment] 2024-01-15 17:37
Thanks, the main goal here is to understand why my dashboards are not working/loading with the new version..

**Comment by paoliniluis** [comment] 2024-01-15 18:32
we need the logs with the new version to check

**Comment by Drconstantino** [comment] 2024-01-16 12:14
[output.zip](https://github.com/metabase/metabase/files/13949710/output.zip)

**Comment by paoliniluis** [comment] 2024-01-16 12:24
Thanks, now send me the result of yourmetabaseurl/api/dashboard/223 and post the JSON here

**Comment by Drconstantino** [comment] 2024-01-16 12:51
dashboards 223 works, I've sent the json of dashboard 225 which doesn't work and returns the error.
[dashboard_225.json](https://github.com/metabase/metabase/files/13950078/dashboard_225.json)

**Comment by paoliniluis** [comment] 2024-01-17 01:27
I think that the issue is a duplicate of https://github.com/metabase/metabase/issues/37345, we'll fix it soon so please upgrade to the version where the fix is and let us know if it works from there on

**Closed by paoliniluis** 2024-01-17 01:27 UTC
Labels: Type:Bug, .Needs Triage

**Comment by Drconstantino** [comment] 2024-01-17 09:14
many thanks @paoliniluis
