### ISSUE TITLE
Overlapping x-axis labels

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#6762] opened 2018-01-24 18:38 UTC
If a card on the dashboard is too small, labels overlap. In the row example (where presumably the x-axis is numeric) we should probably just skip some.
<img width="433" alt="screenshot 2018-01-23 14 57 42" src="https://user-images.githubusercontent.com/178038/35350308-5f98f2ec-00f2-11e8-8897-43f58c26a03a.png">
<img width="404" alt="screenshot 2018-01-23 15 08 13" src="https://user-images.githubusercontent.com/178038/35350313-63f6fc58-00f2-11e8-951d-e0a54ad9ee39.png">

Related issue: the current strategy of omitting some labels for categorical dimensions is questionable as it gives the wrong impression of importance:
<img width="437" alt="screenshot 2018-01-23 15 07 51" src="https://user-images.githubusercontent.com/178038/35351486-e4c97286-00f5-11e8-98a6-cc625deace4c.png">
It's also inconsistent, as for example here we do the more correct thing:
<img width="415" alt="screenshot 2018-01-24 11 02 35" src="https://user-images.githubusercontent.com/178038/35351595-2a0b989c-00f6-11e8-827d-97f2289b5157.png">

**Comment by salsakran** [comment] 2018-02-02 01:43
dupe of #2935

**Closed by salsakran** 2018-02-02 01:43 UTC
Labels: Bug, Visualization
