### ISSUE TITLE
Cannot delete Question from Dashboard.

### ISSUE THREAD

**Issue by rodjager** [metabase/metabase#2187] opened 2016-03-18 05:47 UTC
If this is a bug report, please fill in the blanks:
-  I am using the Safari browser.
-  My computer's OS is OS X El Capitan (10.11.3).
-  I'm running Metabase OS X Client. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
-  My database is mySQL.
-  My Metabase version is 0.15.1

I am running the OS X Client (0.15.1) in on El Capitan (10.11.3).

I am unable to delete a Question from a Dashboard. I can click the trash can icon but the Question remains.

For reference I am experiencing an issue with the Edit Data menu in questions not appearing in dashboards but will document that separately.

[Metabase Console Log.log.zip](https://github.com/metabase/metabase/files/179121/Metabase.Console.Log.log.zip)

**Comment by salsakran** [comment] 2016-08-16 23:01
@rodjager is this a problem in v0.19.3 (or later)?

**Comment by camsaul** [comment] 2016-08-31 22:30
@rodjager ?

**Comment by rodjager** [comment] 2016-09-05 12:54
Thanks for the follow up @camsaul.

I upgraded within the app to the latest release and now I am getting an issue with the app constantly crashing.  I tried cleaning up the profile files as per the Metabase website but this has not corrected the error for me.

At this stage I can't give you an update as to whether this issue has been resolved.

**Comment by camsaul** [comment] 2017-01-04 23:43
Hey @rodjager, are you still having this problem?

**Comment by kdoh** [comment] 2017-07-05 22:01
Given that this issue has been open for over a year and we can't seem to reproduce it I'm going to close this. Happy to re-open if more details come to light.

**Comment by BenWoodford** [comment] 2017-07-12 12:46
If the original issue is anything like mine, it's a UI thing. The drag handling is overriding clicking the gear or trash bin while in edit mode so it tries to drag rather than edit/delete.

**Comment by UnacceptableUse** [comment] 2017-07-19 23:46
I'm also getting this issue in Chrome 59.0.3071.115 on Windows 10, with the latest version

**Comment by notrom** [comment] 2017-10-26 20:55
I'm seeing this to, Chrome 62.0.3202.75 on Windows 7, Metabase v0.26.1

I can use the selector @BenWoodford described to delete a question, but that's not going to work for my end users. Would love to move forward with Meatbase but user self service is right up there on our requirements so this is a sticking point

**Comment by notrom** [comment] 2017-10-26 22:06
I just upgraded to v0.26.2 and for me this has resolved my issue. Thanks!

**Comment by kdoh** [comment] 2017-10-27 00:08
Glad to hear it @notrom. Thanks for letting us know.

**Comment by nicwells** [comment] 2017-11-08 12:03
Still not working for me in Chrome 61.0.3163.100 (Official Build) (64-bit) (cohort: Stable) on Windows 7, Metabase v0.26.2

When editing a dashboard, all I can do is resize cards. I cannot edit cards in any other way including deleting them, nothing appears to happen.

**Comment by sowmyaaguptaa** [comment] 2017-11-30 11:43
I am facing the same issue as @nicwells with the latest Metabase built (v0.27.1) and also with  v0.26.1.
I am working on Chrome 62.0.3202.94 (Official Build) (64-bit) and Windows 7.

I am running it using the jar file and no errors are appearing in the Chrome console as well as on the cmd when I click the edit, settings and delete button on the cards.

**Comment by notrom** [comment] 2018-04-19 01:01
I've just come back to using Metabase after some time away and this is still an issue for me. It does seem to be a bit intermittent, sometimes I can delete, sometimes not. 

Chrome Version 65.0.3325.181 (64-bit)
Windows 7
Metabase v0.28.4 (jar file)

**Comment by tlrobinson** [comment] 2018-05-16 18:01
It seems like everyone who is still experiencing this is on Chrome + Windows. Is that correct?

**Comment by UnacceptableUse** [comment] 2018-05-16 18:06
Chrome, windows 10 and NOT experiencing it. If that helps.

**Comment by notrom** [comment] 2018-06-08 03:36
Chrome and Windows 7 is seeing the issue for me. It's strange though because yesterday this wasn't an issue (again), now it's an issue. Same browser, same Metabase, same databases.

Firefox and Windows is working for me.

**Comment by notrom** [comment] 2018-09-19 00:11
I'm still seeing this on and off after upgrading to v0.30.3

Your browser and the version: Version 69.0.3497.81 (Official Build) (64-bit)
Your operating system: Windows 7
Your databases: SQL Server 2014
Metabase version: 0.30.3
Metabase hosting environment: On Prem Windows Server 2012
Metabase internal database: Postgres

**Comment by MarkRx** [comment] 2018-09-19 14:58
This has been driving me nuts. I've seen it sporadically but now it seems to be happening to me all the time. If I use firefox it works.

Chrome 69.0.3497.100 on Windows 7

**Comment by ashishnirvana** [comment] 2019-01-31 11:33
I am also facing this issue. 

To me it seems that the drag feature is overriding the click.

**Comment by jstell** [comment] 2019-02-15 21:44
Still an issue metabase v0.31.2, Chrome 72.0.3626.96 on Linux

**Comment by emiletf** [comment] 2019-03-28 18:56
Any resolution on this problem? @ashishnirvana seems to be correct. The drag features seems to be above the X to delete or gear to configure.

**Comment by lindsay-stevens** [comment] 2019-05-08 09:55
Also affects Metabase v0.28.6, Windows 10, Chrome 74.0.3729.131. 

Works as expected with Firefox 66.0.5.

**Comment by CloudCray** [comment] 2019-06-02 21:06
Still happening on Metabase v0.32.8, Windows 10, Chromium 74.0.3729.169

React Dev Tools shows the card's drag event is firing instead of the click event for Settings ⚙️ or Remove ❌ buttons while in Edit mode

`Dash--dragging` className is added to GridLayout and its first child, and `dragging` class is added to a descendant of DraggableCore 

![2019-06-02_16-57-40](https://user-images.githubusercontent.com/2027640/58767351-ea3c9a80-8557-11e9-87ea-f2c9541d6c4a.png)

**Comment by slickrock22** [comment] 2019-06-14 11:21
Just encountered this with a client using Metabase.  Their reaction was "really, this might be a bug.  Its a Dashboard tool and you cant remove a question?!".  Seems like table stakes if you are going to place an remove button on a dashboard solution, that the remove button needs to work flawlessly.

**Comment by camsaul** [comment] 2019-06-17 23:31
> React Dev Tools shows the card's drag event is firing instead of the click event for Settings ⚙️ or Remove ❌ buttons while in Edit mode

Hopefully this won't be too hard to fix if it's just a simple matter of changing the event ?

React experts: PRs are welcome!

**Comment by mazameli** [comment] 2019-09-30 21:08
This should be fixed by #10206 in version 0.32.10 or later (current latest is v0.33.3), so I'm going to close this, but please let us know if you're still experiencing it.

**Closed by mazameli** 2019-09-30 21:08 UTC
Labels: .Help Wanted, Browser:Chrome, Priority:P2, Reporting/Dashboards, Type:Bug

**Comment by davideanastasia** [comment] 2020-03-10 10:33
This is still happening to me: I am running the latest version (0.32.3). One tile in my dashboard doesn't show the top-right set of icons, hence I cannot remove or edit that tile. General behaviour in the dashboard is weird, as I have the "save failed" message and all the tiles cannot be resized or moved as expected.

It's impossible for me to say whether the bug wasn't really solved or it is was reintroduced.

**Comment by flamber** [comment] 2020-03-10 10:36
@davideanastasia 
The latest version is 0.34.3 - and I'm quite sure you're seeing #11163, which will be fixed on 0.35.0

**Comment by davideanastasia** [comment] 2020-03-10 10:43
@flamber Yep, sorry, corrected the mistake: I am indeed running 0.34.3. The linked issue seems to be exactly the problem I am experiencing: thanks for pointing it out.
