### ISSUE TITLE
Dashboard subscription fails for a specific valid dashboard

### ISSUE THREAD

**Issue by fernandobrito** [metabase/metabase#16888] opened 2021-07-05 16:34 UTC
**Describe the bug**
Dashboard subscriptions work fine for almost all the dashboards but fail with an obscure error for a particular dashboard.

**Details**
I have a particular dashboard that when I try to create a Dashboard Subscription and press "Send email now", the sending fails:

<img src="https://user-images.githubusercontent.com/196840/124497518-3c95b880-ddbb-11eb-83f0-2506639eec20.png" width="100">

Creating a Dashboard Subscription in any other dashboard works fine, so the issue doesn't seem to be related to our server or installation, but to this particular dashboard.

The dashboard has only one question, which works fine otherwise and looks like that:

![image](https://user-images.githubusercontent.com/196840/124497791-b463e300-ddbb-11eb-86a6-68b47dc99e53.png)

Given that all other dashboards are working, I started to simplify the query by removing some of the filters and summarized fields in the hope of isolating the issue.

I reached a point where this will NOT work:
![image](https://user-images.githubusercontent.com/196840/124498432-9ba7fd00-ddbc-11eb-8272-bce56cafced9.png)

But if I remove the summarize clause inside the red rectangle, it works. If I just change from "Week of Year" to "Day of Year", that will not fix the issue and the test email will still fail. Also, if I convert the version on the screenshot above (that fails) to a native SQL question, it starts to work again.

**Logs**
When it fails, I get a 500 response back from the `/api/pulse/test` HTTP request.

![image](https://user-images.githubusercontent.com/196840/124498734-1ec95300-ddbd-11eb-9b4f-d43204623a38.png)

And the body of the response is:

```{"via":[{"type":"java.lang.ClassCastException"}],"trace":[],"message":null}```

The logs show more or less the same:

![image](https://user-images.githubusercontent.com/196840/124499504-6a303100-ddbe-11eb-8556-c9612d416939.png)

**To Reproduce**
1. Go to my particular dashboard
2. Click on the "Sharing" button
3. Try to create an email subscription
4. Press "Send email now" to test the subscription

**Expected behavior**
The test email should be sent. Instead, I get a failure.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome/91.0.4472.77
- Your operating system: (I'm using the official Docker image file. Not sure what it uses)
- Your databases: Snowflake
- Metabase version: 0.39.4
- Metabase hosting environment: Docker image on Kubernetes
- Metabase internal database: Postgres

**Additional context**
The Metabase user that reported this to me mentioned that the Pulse/alert that he has directly on the question is also not working and that it used to work before a recent upgrade that we did (from 0.38.1 to 0.39.4), but I was not able to verify that.

**Comment by flamber** [comment] 2021-07-05 17:21
Hi @fernandobrito 
Try creating a Pulse instead, which should fail (loading spinner) in the preview - before even trying to send it - and hopefully it includes a full stacktrace, since there's not a lot to work on with the tiny error you got from `/api/pulse/test`.

Without logs or steps to reproduce, which doesn't involve "Go to my particular dashboard", then it's really tricky to figure out what is going wrong.

**Comment by fernandobrito** [comment] 2021-07-06 07:32
Thanks for the quick response, @flamber 😄 .

When I try creating a Pulse in the same question, I get the same error.
HTTP 500 on GET `.../api/pulse/preview_card_info/4330`, response body `{"via":[{"type":"java.lang.ClassCastException"}],"trace":[],"message":null}` and logs

```
GET /api/pulse/preview_card_info/4330 500 1.7 s (13 DB calls) 
{:via [{:type java.lang.ClassCastException}], :trace [], :message nil}
```

I can think of 2 ways to help me narrow down the issue even further:
1) Recreate the exact same faulty question on a table with mock data to rule out that the issue is not somehow caused by the data itself;
2) Try to reproduce it starting from the other direction. First I went to the faulty question and started removing filters and summary clauses. Now I will try creating a new blank question and add the filters one by one.

Not sure if I will have time for it today, but I will keep this thread updated.

**Comment by flamber** [comment] 2021-07-07 11:37
@fernandobrito Found the problem. Not sure why your system isn't showing the full stacktrace, but I guess you have changed something on Log4j - anyways, closing in favor of #16918

**Closed by flamber** 2021-07-07 11:37 UTC
Labels: .Needs Triage, Type:Bug

**Comment by fernandobrito** [comment] 2021-07-08 08:51
Amazing, thanks!
