### ISSUE TITLE
Question From a Saved Question not working on a dashboard with filters in 0.32.5 version

### ISSUE THREAD

**Issue by agoud1993** [metabase/metabase#9848] opened 2019-04-24 18:32 UTC
Hi, I've upgraded my metabase from 0.31.2 version to latest and greatest version 0.32.5 in order to solve some of my issues like "asking a question from a saved question and saving that question and using it on a dashboard".
I've dashboard and from that dashboard I want to ask a question and save it and use that saved question on a dashboard. 
I'm able to save the question but I'm not able to view the data from the question which is saved previously on a dashboard.
The dashboard has a date filter.
Before when I was using 0.31.2 i wasn't able to even save the dashboard, but now when I've upgraded to 0.32.5 I'm able to save a question on dashboard but there's no data after using a date filter.
"Target 4w Production with Goal" is a question which is asked from a saved question which you can see the bar chart. But, I want to view the same in a different visualization. But I failed with this error
Please view the image below
![saved question from a question](https://user-images.githubusercontent.com/45699622/56678022-bdab7e00-668f-11e9-952d-cb67c2d848c5.PNG)

the same question which is not displaying the data on the dashboard is displaying in the data in question level
![saved question level](https://user-images.githubusercontent.com/45699622/56683482-a4103380-669b-11e9-89fc-efb111263581.PNG)
- Browser (e.x.  Firefox 60.5,)
- Your databases:  Postgres
- Metabase version: 0.32.5

**Comment by flamber** [comment] 2019-04-24 18:41
@agoud1993 I think you're seeing #9802, since I can see you're using Nested Question on the one failing.

**Comment by vabhishek6** [comment] 2019-04-30 09:07
I have hit on a similar such issue were I see that the admin user doesn't have permissions in the saved questions module.
![Screenshot from 2019-04-30 09-52-33](https://user-images.githubusercontent.com/10140218/56951412-b2dd6700-6b2f-11e9-90c8-55c9e8de8bd8.png)

**Comment by flamber** [comment] 2019-04-30 13:54
Hi @vabhishek6 That's a different issue. Just ignore "Saved Questions" on the Permissions page.
Read more here #5610

@agoud1993 If you agree that it's a duplicate of #9802, then please close this issue.

**Comment by mazameli** [comment] 2019-10-18 22:08
Closing as duplicate of #9802

**Closed by mazameli** 2019-10-18 22:08 UTC
Labels: .Duplicate, Priority:P3, Querying/Nested Queries, Type:Bug
