### ISSUE TITLE
Exporting date values to Excel transforms them from "1/25/2021" to "1/24/2021 22:00:00"

### ISSUE THREAD

**Issue by atanas0** [metabase/metabase#14507] opened 2021-01-25 11:48 UTC
**Describe the bug**
Date values are stored as timestamps in the Excel export in the format 1/24/2021 22:00:00 instead of 1/25/2021. The Day value in the file is lower by 1 than the displayed value.

**To Reproduce**
1. Create a question with a date column and the following settings for the date (Screenshot 1)
2. Export the result as Excel
3. Open Excel and see date values "1/24/2021 22:00:00" instead of "1/25/2021" (Screenshot 2)

**Expected behavior**
Display date values as: 1/25/2021

**Screenshots**
Screenshot 1:
![Screen Shot 2021-01-25 at 16 06 42](https://user-images.githubusercontent.com/13204176/105716426-766ab500-5f27-11eb-8af8-067d8b94fe7f.png)

Screenshot 2:
![Screen Shot 2021-01-25 at 13 36 24](https://user-images.githubusercontent.com/13204176/105701197-9f347f80-5f12-11eb-902e-eedd43d1695a.png)

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.158-129.185.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-01-20",
      "tag": "v0.37.7",
      "branch": "release-x.37.x",
      "hash": "2b034aa"
    },
    "settings": {
      "report-timezone": "Europe/Athens"
    }
  }
}

**Severity**
It's blocking some of our not sophisticated users who are not able to open up a CSV file with their Excel and successfully go through the process of setting delimiters etc.

**Additional context**
Issue is not observed for CSV exports

**Comment by flamber** [comment] 2021-01-25 12:10
Hi @atanas0 
Can you provide a more detailed steps-to-reproduce, since I don't understand step 1, and I don't understand how step 3 is relevant?

**Comment by atanas0** [comment] 2021-01-25 14:09
Hi @flamber 
I edited the description. I hope it makes more sense now.

**Comment by flamber** [comment] 2021-01-25 21:42
@atanas0 
Metabase does not support formatting on exports - there's an issue open about that: #10879

It seems like we have a problem with Postgres exports, which is using the UTC timezone.
I'm reopening the original issue #13677 and closing this.

**Closed by flamber** 2021-01-25 21:42 UTC
Labels: .Needs Triage, Type:Bug
