### ISSUE TITLE
Region map: k-means choropleth coloring breaks with small number of rows

### ISSUE THREAD

**Issue by FadhelC** [metabase/metabase#9078] opened 2018-12-06 11:24 UTC
Metabase 0.31.1

If the number of rows is less than the number of colors (5), the k-means library throws this error:

Uncaught Error: Cannot generate more classes than there are data values

might be the same as #4684

**Comment by paulrosenzweig** [comment] 2019-07-24 22:21
Looks like it was a duplicate of #4684 as mentioned. That one is fixed on master.

**Closed by paulrosenzweig** 2019-07-24 22:21 UTC
Labels: Priority:P2, Type:Bug, Visualization/
