### ISSUE TITLE
Metabase unable to fetch vertica schema v0.39.3

### ISSUE THREAD

**Issue by ivalexa** [metabase/metabase#16352] opened 2021-06-04 07:36 UTC
**Describe the bug**
When using the latest Metabase version v0.39.3, and adding vertical database, Vertica connector is broken and unable to fetch Vertica database schema, I tested different version and after v0.35.3 schema, fetch is broken and doesn't work  

**Logs**
[vertica_logs.log](https://github.com/metabase/metabase/files/6596571/vertica_logs.log)

**To Reproduce**
1. Setup Metabase
2. Add Vertica database type successfully
3. Metabase unable to fetch the schema

**Expected behavior**
Metabase should be able to fetch Vertica schema

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.19.121-linuxkit",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "vertica"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-27",
      "tag": "v0.39.3",
      "branch": "release-x.39.x",
      "hash": "598a112"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
This is blocking usage of Metabase entirely since even in the old v0.35.3 version, which is able to fetch schema, there are other issues like it's unable to select * from table, it seems that Vertica integration is completely broken which prevent me from using this great tool, however when using tools such datagrip everything works perfectly

**Additional context**
Other information about the setup:
Tables: 901
Views: 190
Vertica Driver: vertica-jdbc-10.0.1-0.jar (I tried different version with no luck)

**Screenshots:**
<img width="1500" alt="Screen Shot 2021-06-04 at 10 31 06" src="https://user-images.githubusercontent.com/1618071/120763867-50ca6980-c520-11eb-9d18-4ace1af796a2.png">
<img width="1500" alt="Screen Shot 2021-06-04 at 10 30 49" src="https://user-images.githubusercontent.com/1618071/120763896-588a0e00-c520-11eb-9770-aceced818d96.png">
<img width="1500" alt="Screen Shot 2021-06-04 at 10 30 35" src="https://user-images.githubusercontent.com/1618071/120763915-5cb62b80-c520-11eb-8653-15eb832b89fe.png">
<img width="1500" alt="Screen Shot 2021-06-04 at 10 26 33" src="https://user-images.githubusercontent.com/1618071/120763946-663f9380-c520-11eb-9e3b-066ffa711a9f.png">

**Comment by flamber** [comment] 2021-06-04 10:41
Hi @ivalexa 

This sounds similar to #13628, but it was fixed in 0.37.1

Which version of Vertica DB are you using? The JDBC driver has to match as closely as possible. Just for reference:
https://www.metabase.com/docs/latest/administration-guide/databases/vertica.html

Have you checked the query log on Vertica DB to see what Metabase is querying and what Vertica returns?

I can only see it starting the sync, but not finishing or any other details:
`INFO metabase.sync.util STARTING: step 'sync-tables' for vertica Database 2 'Vertica DEV'`

Looks like you're using Docker, so try running the container with this to get much more logging during sync:
... `-e JAVA_OPTS="-Dlog4j.configurationFile=https://log4j.us/v2/templates/metabase?trace=metabase.sync"` ...

Are you able to manually run a query like this in Metabase > Native query > `select * from YOUR_TABLE` ?

Which privileges does Metabase have to Vertica? Have you tried giving all privileges, and if that works, then slowly make it more restricted. Several times when Metabase cannot connect, or cannot find schemas/tables, then it might because of too restrictive privileges.

**Comment by ivalexa** [comment] 2021-06-06 08:43
It's strange, but after setting time zone, and clicking re-sync Metabase was able to fetch the schema, so currently it does work for me , i will do additional investigation to ensure it's not coincidence (eg just taking a lot of time to fetch schema)

**Comment by flamber** [comment] 2021-06-11 12:20
@ivalexa Closing, since it looks like you got it working. But please comment back if you still have problems. And it would be extremely helpful if you could provide steps-to-reproduce or query logs from the database, which can be correlated to the Metabase logs.

**Closed by flamber** 2021-06-11 12:20 UTC
Labels: .Needs Triage, Type:Bug
