### ISSUE TITLE
The chart draws Zero value for NULL instead of hiding the value

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4122] opened 2017-01-11 14:08 UTC
![image](https://cloud.githubusercontent.com/assets/1708680/21851551/90b3a530-d820-11e6-8f21-0a68827b0885.png)

(Clarification: `SELECT NULL::int` return `NULL` in Vertica. In case if you think that `NULL::int` is `0` value)

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by tlrobinson** [comment] 2017-01-11 19:53
I believe this isn't a regression, Metabase has always treated NULL as 0.

It does treat actual missing values (when it can detect the interval) differently. We have a "missing values" setting to change the behavior of that, but it looks like it doesn't apply to in this case.

@salsakran What's the expected behavior here?

**Comment by salsakran** [comment] 2017-01-11 19:56
For time series, we treat a null value as a 0.

The reason for this is that if you do a group by, empty buckets are returned as nulls and not 0.

I see linear interpolation on timeseries with nulls being the exceptional case, and something that imo is incorrect when rendering timeseries with aggregate metrics as the value.

**Comment by salsakran** [comment] 2017-01-11 19:57
i.e. this is absolutely expected behaviour.

**Comment by salsakran** [comment] 2017-01-11 19:57
closing unless we want to add interpolation controls on normal timeseries.

**Comment by tlrobinson** [comment] 2017-01-11 20:12
@salsakran 

> The reason for this is that if you do a group by, empty buckets are returned as nulls and not 0.

The backend doesn't return a row at all for empty buckets. I believe we have/had a ticket open for a long time for that issue but we might have closed it when we added the `Replace missing values with` setting on the frontend, though the default is `LInear Interpolated` (I believe we didn't want to break existing behavior)

This is the default:

![screenshot 2017-01-11 12 06 07](https://cloud.githubusercontent.com/assets/18193/21864430/9bf42566-d7f6-11e6-91a6-20d43871e9cb.png)

This is what I think you're expecting the default is:

![screenshot 2017-01-11 12 09 07](https://cloud.githubusercontent.com/assets/18193/21864461/c54797c2-d7f6-11e6-8c92-7be61fcf4bcd.png)

I think ideally we should filter `NULL` rows (so the behavior is more consistent and the `missing value` setting works for NULLS) and default to `Zero` in more (all?) cases.

**Comment by salsakran** [comment] 2017-01-11 20:13
Ahhh, I see. I was probably too quick to the draw.

**Comment by salsakran** [comment] 2017-01-11 20:14
can anyone think of any situations where there's a semantic difference between a null and a missing value?

**Comment by tlrobinson** [comment] 2017-01-11 20:16
The issue I was talking about was #896

I wonder how many cards we would break vs. make "more correct" if we changed the default from "Linear Interpolated"  to "Zero"?

**Comment by camsaul** [comment] 2017-01-11 20:17
I would think zero should be the default e.g. if we have a query that returns number of sales per month you don't want to interpolate months where you had no sales

**Comment by salsakran** [comment] 2017-01-11 20:17
Ugh. 

Regardless, I think I'm on board with nulls being treated as missing values for the sake of the interpolation setting you mentioned, @tlrobinson

**Comment by anki-code** [comment] 2017-01-11 21:04
@camsaul 
> if we have a query that returns number of sales per month you don't want to interpolate months where you had no sales

`SELECT date, sum(NULL) FROM table GROUP BY 1` returns `0` value. This is no problem.

**Comment by anki-code** [comment] 2017-01-11 21:21
When you write `WHERE val != 1` on sql it really returns rows where "val != 1 AND val is not null". It's standard behavior - NULL is "no value".

**Comment by camsaul** [comment] 2017-01-11 21:26
@anki-code we know 😉

**Comment by anki-code** [comment] 2017-02-01 21:28
Any next steps on this issue? )

**Comment by anki-code** [comment] 2017-02-27 19:07
It's really annoying when NULL values are propagating to all area chart.

On chart below you can see the release of new version of app. But the "new version area" hasn't started in the release date point. It has NULL value from first date.

![image](https://cloud.githubusercontent.com/assets/1708680/23375321/f82769ee-fd38-11e6-8eb5-19ae5fc7886d.png)

**Comment by tlrobinson** [comment] 2017-02-27 19:19
@anki-code I'll take a look at this.

@salsakran I think we decided nulls should basically be treated the same as "missing" values?

**Comment by anki-code** [comment] 2017-02-27 19:26
Could be a solution is to add an option here:

![image](https://cloud.githubusercontent.com/assets/1708680/23376054/c988a4a6-fd3b-11e6-8b44-b8bcf4138893.png)

**Comment by anki-code** [comment] 2017-03-17 09:21
> @anki-code I'll take a look at this.

Hi @tlrobinson! Did you have time to look? Do this issue have a chance to be in 0.23?

**Comment by anki-code** [comment] 2017-04-20 08:51
Take a look please. Could it be easy to do.

**Comment by rthouvenin** [comment] 2017-10-12 09:13
Any chance that this issue is looked at soon? If not enough support from the community, can someone point me to the relevant places in the code so I can give a try?

**Comment by anki-code** [comment] 2017-12-07 20:41
Still actual in 0.27.1

**Comment by jornh** [comment] 2017-12-09 19:11
@rthouvenin looks like the interpolation setting mentioned above in https://github.com/metabase/metabase/issues/4122#issuecomment-282824678 is applied in https://github.com/metabase/metabase/blob/v0.27.1/frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js#L300 so that’s one starting point if you are still up for this.

**Comment by bfelbo** [comment] 2020-07-03 18:32
How do we hide NULLs on the latest version of Metabase?

For the line visualization, I don't see the "Replace missing values with" option mentioned in https://github.com/metabase/metabase/issues/4122#issuecomment-271980423.

**Comment by flamber** [comment] 2020-07-04 10:30
@bfelbo Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
![image](https://user-images.githubusercontent.com/1447303/86510671-1b8a3880-bdf2-11ea-8543-b1a8521d23ae.png)

**Closed** 2021-06-24 18:29 UTC
Labels: Priority:P2, Type:Bug, Visualization/Charts
