### ISSUE TITLE
Feature Request to have Dashboards as a group

### ISSUE THREAD

**Issue by sandeepbathina** [metabase/metabase#7240] opened 2018-03-30 02:04 UTC
Hi,

We started using metabase and it looks great for us. Currently we are having multiple dashboards and its becoming difficult for us to identify a particular dashboard of a group. It would be nice if you could provide dashboards as a group option similar to one we have for questions.

**Comment by jornh** [comment] 2018-03-30 06:30
Duplicate of #6509 ... which in turn I think is a duplicate of #6081.

**Comment by salsakran** [comment] 2018-03-31 00:34
closing this in favor of 6509 which has the most upvotes.

**Closed by salsakran** 2018-03-31 00:34 UTC
