### ISSUE TITLE
Long error messages are truncated in the UI

### ISSUE THREAD

**Issue by orenmazor** [metabase/metabase#13938] opened 2020-12-02 18:26 UTC
**Describe the bug**
When you run a query that results in an error message, that error message often includes the query itself. if the query is very large, the error view in metabase only shows the bottom of the entire error, which is taken up by the query. You need to inspect source to find the actual error.

I would suggest an alternative where this view has the ability to scroll to the top of the error

**Logs**
no applicable logs

**To Reproduce**
1. Go to run a question
2. enter a long question that will result in SOME kind of error. in my case, if I run an athena ddl query that will not return a result set (e.g. something that will generate a "[Simba][JDBC](11300) A ResultSet was expected but not generated from query" error)

**Expected behavior**
at the top of the result view I'd want to see "[Simba][JDBC](11300) A ResultSet was expected but not generated from query", but instead I see just a bottom chunk of the lengthy query and not the actual error.

**Screenshots**
this makes sense because the query is short:

![Screen Shot 2020-12-02 at 1 21 45 PM](https://user-images.githubusercontent.com/384279/100914649-55469480-34a1-11eb-982f-ec4a102f3f1e.png)

not as great. my query pushed the error off screen
![Screen Shot 2020-12-02 at 1 25 35 PM](https://user-images.githubusercontent.com/384279/100915050-e0278f00-34a1-11eb-8564-76f3c6325b90.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: firefox latest update as of today (2020-12-02)
- Your operating system: big sur
- Your databases: athena
- Metabase version: 0.37.2
- Metabase hosting environment: jar in ec2
- Metabase internal database: pg

**Severity**
annoying mostly. confusing to some of my users who dont understand how they got there. ends up as an ops issue "metabase is broken" instead of a user-end query debug

**Comment by flamber** [comment] 2020-12-02 18:34
Duplicate of #11885

**Closed by flamber** 2020-12-02 18:34 UTC
Labels: Priority:P3, Querying/Native, Type:Bug
