### ISSUE TITLE
"Cannot decrypt encrypted string" each time I try to set site_url

### ISSUE THREAD

**Issue by muscovitebob** [metabase/metabase#20159] opened 2022-02-02 10:09 UTC
**Describe the bug**
Each time I try and set the site_url with an `MB_ENCRYPTION_SECRET_KEY` configured I get an error saying it cannot decrypt the database value. The effect is that the site_url is not persisted to the metabase application database and upon each Metabase pod restart site_url is reset to default. Because the default is an http URL this breaks my SAML, configured to redirect to HTTPS.

**Logs**
```
2022-02-02 09:50:15,155 WARN util.encryption :: Cannot decrypt encrypted string. Have you changed or forgot to set MB_ENCRYPTION_SECRET_KEY? Message seems corrupt or manipulated. ["buddy.core.crypto$fn__6869.invokeStatic(crypto.clj:485)"
 "buddy.core.crypto$fn__6869.invoke(crypto.clj:474)"
 "clojure.lang.MultiFn.invoke(MultiFn.java:229)"
 "buddy.core.crypto$decrypt.invokeStatic(crypto.clj:568)"
 "buddy.core.crypto$decrypt.invoke(crypto.clj:555)"
 "--> util.encryption$decrypt.invokeStatic(encryption.clj:69)"
 "util.encryption$decrypt.invoke(encryption.clj:61)"
 "util.encryption$maybe_decrypt.invokeStatic(encryption.clj:113)"
 "util.encryption$maybe_decrypt.doInvoke(encryption.clj:101)"
 "models.setting.cache$restore_cache_BANG_.invokeStatic(cache.clj:122)"
 "models.setting.cache$restore_cache_BANG_.invoke(cache.clj:118)"
 "models.setting$fn__21542$set_string_BANG___21547$fn__21548.invoke(setting.clj:416)"
 "models.setting$fn__21542$set_string_BANG___21547.invoke(setting.clj:400)"
 "models.setting$set_boolean_BANG_.invokeStatic(setting.clj:448)"
 "models.setting$set_boolean_BANG_.invoke(setting.clj:444)"
 "public_settings$fn__31605$fn__31606.invoke(public_settings.clj:401)"
 "models.setting$set_BANG_.invokeStatic(setting.clj:529)"
 "models.setting$set_BANG_.invoke(setting.clj:514)"
 "api.setting$fn__77886.invokeStatic(setting.clj:34)"
 "api.setting$fn__77886.invoke(setting.clj:28)"
 "server.middleware.auth$enforce_authentication$fn__70969.invoke(auth.clj:14)"
 "api.routes$fn__80444$fn__80445.invoke(routes.clj:54)"
 "server.routes$fn__80589$fn__80590.doInvoke(routes.clj:57)"
 "server.middleware.exceptions$catch_uncaught_exceptions$fn__78051.invoke(exceptions.clj:98)"
 "server.middleware.exceptions$catch_api_exceptions$fn__78048.invoke(exceptions.clj:86)"
 "server.middleware.log$log_api_call$fn__82642$fn__82643$fn__82644.invoke(log.clj:209)"
 "driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)"
 "driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)"
 "server.middleware.log$log_api_call$fn__82642$fn__82643.invoke(log.clj:201)"
 "server.middleware.log$log_api_call$fn__82642.invoke(log.clj:200)"
 "server.middleware.browser_cookie$ensure_browser_id_cookie$fn__87883.invoke(browser_cookie.clj:30)"
 "server.middleware.security$add_security_headers$fn__59920.invoke(security.clj:144)"
 "server.middleware.json$wrap_json_body$fn__85184.invoke(json.clj:62)"
 "server.middleware.json$wrap_streamed_json_response$fn__85202.invoke(json.clj:98)"
 "server.middleware.offset_paging$handle_paging$fn__59944.invoke(offset_paging.clj:42)"
 "server.middleware.misc$maybe_set_site_url$fn__33925.invoke(misc.clj:59)"
 "server.middleware.session$bind_current_user$fn__45955$fn__45956.invoke(session.clj:257)"
 "server.middleware.session$do_with_current_user.invokeStatic(session.clj:238)"
 "server.middleware.session$do_with_current_user.invoke(session.clj:230)"
 "server.middleware.session$bind_current_user$fn__45955.invoke(session.clj:256)"
 "server.middleware.session$wrap_current_user_info$fn__45942.invoke(session.clj:216)"
 "server.middleware.session$wrap_session_id$fn__45928.invoke(session.clj:162)"
 "server.middleware.auth$wrap_api_key$fn__70977.invoke(auth.clj:27)"
 "server.middleware.misc$add_content_type$fn__33908.invoke(misc.clj:27)"
 "server.middleware.misc$disable_streaming_buffering$fn__33933.invoke(misc.clj:76)"
 "server.middleware.misc$bind_request$fn__33936.invoke(misc.clj:93)"
 "server.middleware.ssl$redirect_to_https_middleware$fn__87899.invoke(ssl.clj:48)"
 "server$async_proxy_handler$fn__82415.invoke(server.clj:71)"
 "server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)"]
```

**To Reproduce**

* In the admin panel of an instance with SAML and the encryption secret key configured, go to the General panel and set the site_url and redirect to HTTPS. Observe the error being emitted in the logs. Verify SAML works by logging in and out.
* Now restart the Metabase process (or pod in my case).
* Verify SAML login is not functional due to wrong callback URL. Login with email, go to the admin panel General panel and see that the site_url has been reset to default.

**Expected behavior**
site_url should be persisted in the database.

**Information about your Metabase Installation:**

The app database is a PG13 CloudSQL instance.
```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "5.4.144+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-11-05",
      "tag": "v1.41.1-SNAPSHOT",
      "branch": "forky-mc-forkface",
      "hash": "6f4e355"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
Notice I run a fork you can find in 18422.

**Severity**
Rather severe as since I run Metabase using a helm chart in Kubernetes, pods do get replaced and lose the setting. breaking SAML for users.

**Comment by muscovitebob** [comment] 2022-02-02 10:11
It is not just the `site_url` that fails, but it is the most visible to me. On startup I get the following decryption errors as well:
[full_log_since_start.txt](https://github.com/metabase/metabase/files/7985431/full_log_since_start.txt)

**Comment by muscovitebob** [comment] 2022-02-02 10:23
For the moment I will try working around this by setting `MB_SITE_URL` and `MB_REDIRECT_ALL_REQUESTS_TO_HTTPS` to what these values need to always be.

**Comment by flamber** [comment] 2022-02-02 10:24
You should immediately upgrade to a newer release: https://github.com/metabase/metabase/releases/latest
Duplicate of #19487

**Closed by flamber** 2022-02-02 10:24 UTC
Labels: Type:Bug, .Needs Triage
