### ISSUE TITLE
Make date range filter available to multiple fields

### ISSUE THREAD

**Issue by nickcarenza** [metabase/metabase#13180] opened 2020-08-28 17:05 UTC
The date range filter is awesome but it is limited to field filters. I regularly wish I was able to have a date range filter apply to multiple different fields without having to have multiple filters or using 2 regular date filters for start and end dates.

What if we could define multiple field filters but link them into a single UI component?

```
{{ created_a }} => select column "A" in ui
{{ created_b }} => select column "B" in ui and link to "created_a" filter
```

What if we had parameters in the variable definition that allowed us to specify the field to filter on per-instance?

```sql
select * from d.table_a where {{ created "d.table_a" }}
union
select * from d.table_b where {{ created "d.table_b" }}
```

If we end up adding that sort of parameterization of the query variables I think it would be awesome to take it a step further to make the UI unnecessary for variable configuration.

```sql
select * from d.table_a where {{ created type="date-range" field="d.table_a" )}}
union
select * from d.table_b where {{ created  type="date-range" field="d.table_b" }}
```

One problem with this approach would be syncing the in-query representation of the filter and whatever options were chosen via the UI.

Any other implementation ideas?

**Comment by flamber** [comment] 2020-08-28 17:33
Hi @nickcarenza Sounds like a duplicate of #3324 and/or #4509

**Closed by flamber** 2020-08-28 17:33 UTC
Labels: .Needs Triage, Type:New Feature
