### ISSUE TITLE
"Too much recursion" in Firefox

### ISSUE THREAD

**Issue by MaxSavenkov** [metabase/metabase#5262] opened 2017-06-03 08:42 UTC
Browser and OS: Firefox 53.0.1 (32bit), Windows 7 64bit, 
DB: Postgres 9.6
Metabase version: 0.24.1
Metabase hosting: Docker
Metabase internal DB: H2

A "too much recursion" error appeared after I have added several filters to a dashboard (before that, the dashboard was working fine). Now, most of the time I can't even open the dashboard to edit it (sometimes it opens and manages to load default results for one question before giving up). The dashboard includes 4 quite complex custom SQL questions and about 5 filters for them.

However, this seem to be a Firefox-only bug, as Chrome and even IE11 can work with this dashboard without any problems.

Call stack:

-------------------------
InternalError: too much recursion

[object Object]  app-main.bundle.js:159:6060
	e/< app-main.bundle.js:159:6060
	i app-main.bundle.js:7:17450
	c/< app-main.bundle.js:7:18548
	l/</e[t] app-main.bundle.js:7:17626
	r app-main.bundle.js:159:3095
	r/< app-main.bundle.js:159:3224
	o app-main.bundle.js:6:14575
	M/< app-main.bundle.js:6:14697
	u app-main.bundle.js:6:18820
-------------------------

If needed, I think I can provide read-only access to out Metabase installation for diagnostic and debugging purposes.

**Comment by Varunram** [comment] 2017-06-05 06:34
Um, ok. Could you post the SQL query you used (with field names changed for privacy) so that I may try to reproduce the issue? Thanks!

**Comment by MaxSavenkov** [comment] 2017-06-05 08:42
The problem disappeared after I upgraded my PC to a much more powerful one and move on to Windows 10. So maybe it only happens on slower machines, or is Firefox+Win7-specific?

I'm not sure if posting a query here would help much, but here goes:

The dashboard uses 4 queries, all of which extract data from a big table with a JSONB field and cross-reference it with a few other tables.

The tables are:
```
CREATE TABLE "statistic_events" (
	"id" SERIAL,
	"type" VARCHAR(16) NOT NULL,
	"data" JSONB,
	"time" TIMESTAMP,
	PRIMARY KEY ("id"),
	INDEX "" ("type")
);

CREATE TABLE "original_cards" (
	"id" SERIAL,
	"ref_name" VARCHAR(255) NULL DEFAULT NULL,
	"clan_id" INTEGER NULL DEFAULT NULL,
	PRIMARY KEY ("id"),
	INDEX "" ("clan_id"),
);

CREATE TABLE "clans" (
	"id" SERIAL,
	"name" VARCHAR(255),
	PRIMARY KEY ("id")
);
```

The queries are all fairly similar, with only a few different details changed between each one, so I'll reproduce only one here:
```
WITH 
cards_in_battles AS (SELECT bid, unnest(cards) AS card_id, result FROM
	(
		SELECT 
			data->'battle_id' AS bid, 
			type AS result,
		    ARRAY( SELECT (card_id->>0)::integer FROM jsonb_array_elements(data->'all_cards') AS card_id ORDER BY card_id) as cards
        FROM statistic_events
        WHERE ((statistic_events.type)::text = ANY ((ARRAY['combat_won'::character varying, 'combat_lost'::character varying, 'combat_drawn'::character varying])::text[]))
        AND {{interval}}
        AND (data->>'user_level')::integer >= {{min_user_level}}
        AND (data->>'opponent_level')::integer >= {{min_user_level}}
        AND (data->>'user_level')::integer <= {{max_user_level}}
        AND (data->>'opponent_level')::integer <= {{max_user_level}}        
        AND data->>'mode_type' IN (SELECT id FROM game_modes WHERE {{rooms}})   	
    ) AS a
),

cards_wins_combats AS (SELECT card_id, COUNT(DISTINCT(bid)) AS combats,
sum(
    CASE
        WHEN result = 'combat_won'::text THEN 1
        ELSE 0
    END) AS wins
 FROM cards_in_battles
 GROUP BY card_id
)

SELECT 
ref_name AS name,
combats, 
wins, 
((wins::float/combats)*100)::integer AS win_percent,
'https://klanz.ru/card/'::text||card_id::text AS card_url
FROM cards_wins_combats JOIN original_cards ON original_cards.id=card_id
WHERE wins>={{min_wins}}
AND combats>={{min_combats}}
ORDER BY win_percent DESC;
```

An example of data from statistic_events table:

```
INSERT INTO "statistic_events" VALUES (1188, E'combat_won', E'{"clans": [1, 2, 5, 6, 7, 8, 10, 11, 17, 21, 27], "turns": 5, "mode_id": "brawl", "user_id": 863970, "battle_id": "fdcf083c-a236-4bf3-bebc-515405c40055", "mode_type": "brawl"}', E'2017-04-27 11:41:45.437676');
```

**Comment by Varunram** [comment] 2017-06-06 05:50
@MaxSavenkov Hm the queries and stuff look normal, so I don't think there'll be a problem with that. It maybe an issue with less powerful machines as you mentioned. I'm sure the other devs would have a better opinion regarding this.

**Comment by astathis** [comment] 2017-06-07 14:32
I had the same problem with metabase 0.24.1 & Firefox 53.0.3 (32-bit) on Windows 8.1 64-bit. I gave up to 4GB memory (e.g.  java -Xms3g -Xmx4g -jar metabase.jar). Now, I am working with chrome :)

**Comment by dgleba** [comment] 2018-01-09 21:26
I have 'too much recursion' in Firefox and 'Maximum call stack size exceeded' in Chrome. Sad Face.

**Comment by tomfbush** [comment] 2019-09-06 08:08
Not sure if it's too late to add to this!

I was getting these 2 errors whether using Chrome or Firefox when loading a very simple dashboard (just a count of a categorical variable in a ~1k Postgres table). Sometimes it got a bit further, rendering the frame for the charts to go into but remained blank.

I found 2 unsatisfactory ways round this:

1) The dashboard has a single question in it. I tried that separately and it loaded instantly in both browsers.

2) I created an identical dashboard and that works fine in both browsers.

Obviously neither of these resolve the root cause but I wonder if there is some mechanism under the hood that is caching parts of the dashboard (over my head I'm afraid).

Also FWIW this was absolutely fine previously and I've not changed Metabase version or anything, however I did restart Metabase between it working and not working -- although I just tested that on the duplicate dashboard I made in 2) and that doesn't seem to have broken this time round.

Tried in incognito mode of both browsers so doesn't look like a browser cache issue or anything.

I'm on "v0.32.10, built on 2019-07-30" currently testing on an EC2 with Postgres server on same instance.

Happy to try and help diagnose this as this could be a show-stopper as far as using Metabase in production :)

**Comment by retypepassword** [comment] 2019-09-19 15:32
I encountered the same issue on two different machines in both Firefox and Chrome. In both cases, oddly enough, the issue disappeared after resizing the viewport.

**Comment by rthouvenin** [comment] 2019-10-30 08:38
I noticed the same problem with Metabase 0.33.0, and upgrading to 0.33.4 didn't solve it. Making a duplicate dashboard led to the same issue. I always get the problem, and Firefox tells me that the page is slowing down the browser and asks me whether I want to wait or stop the execution. If I say wait, it will either show an error "too much recursion" or manage to display the frame of the single question of the dashboard but not more than that. 
And it does make the issue disappear if I resize the browser window to a smaller one o_0

The dashboard is made of a single native SQL question with one variable, and one filter linked to the question variable. The visualization of the question is a funnel.

**Comment by rthouvenin** [comment] 2019-11-29 15:58
The problem stops as soon as the dashboard questions cover the whole width of the dashboard: I then don't need to resize the window to view the dashboard.

**Comment by flamber** [comment] 2019-11-29 17:14
There has been a fix (#11393) for several issues that froze dashboards in specific cases.
It will be part of next release 0.34.0 (hopefully in early December).
I think on Chrome the error is `Maximum call stack size exceeded` instead of `too much recursion`

**Comment by cemsbr** [comment] 2020-01-02 14:28
With 0.34.0, I'm still getting "too much recursion2 vendor.bundle.js:1:1372526" in Firefox and "vendor.bundle.js?f4999ff7ddee79f5a90a:1" in Chrome.

**Comment by flamber** [comment] 2020-01-02 14:46
@cemsbr This issue (and the fix) is specific to dashboards. You're likely seeing #11343.

**Comment by flamber** [comment] 2020-06-03 18:46
Closing, since there hasn't been any reports about problems in Firefox since 0.34
Please comment with details if you're still experiencing this on Firefox.
There's two other issues, which seems to be specific to Chrome-based browsers #6701 #10127

**Comment by ctSkennerton** [comment] 2021-05-14 18:43
I also get this error.
MacOS 11
Firefox 88.0
Metabase 0.38.4

The behaviour is basically the same as described above. The dashboard will be unresponsive and give the message "too much recursion" but recreating the question does not produce an error. The dashboard has a single question and a single date filter. The SQL of the question is equivalent to:  

```sql
select guid, isExpected, sum(proportion) as sumprop from tab group by guid, isExpected having sum(proportion) is not null
```

And the full table has about 10,000 rows.

Switching to chrome did not give an error.

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "4.15.0-1039-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-08",
      "tag": "v0.38.4",
      "branch": "release-x.38.x",
      "hash": "057b6bb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by spacecowboy** [comment] 2021-05-16 18:23
Also seeing this error for a dashboard I created in Firefox 88.0.1

Seemed to trigger once I had added "too many" questions to the dashboard I thought. With too many being around 7.

**Comment by flamber** [comment] 2021-06-03 18:11
@ctSkennerton @spacecowboy
We have not been able to reproduce this issue nor #10127/#6701, and both issues seems to be extremely specific to OS, resolution, zoom levels, and browser viewport (width/height of the browser's content window without the chrome).
I don't think we'll be able to resolve these issues until a frontend developer can consistently reproduce the problem on their system.

**Closed** 2024-01-19 01:47 UTC
Labels: Type:Bug, Priority:P2, Reporting/Dashboards, .Unable to Reproduce, Browser:Firefox, Difficulty:Hard, .Frontend, .Team/DashViz
