### ISSUE TITLE
[Feature] Highlight cards which will be affected by the filter

### ISSUE THREAD

**Issue by tmdoit** [metabase/metabase#14152] opened 2020-12-21 22:27 UTC
**Is your feature request related to a problem? Please describe.**
I don't know which cards will be affected by the filter

**Describe the solution you'd like**
Highlight cards which will be affected by the filter

**Comment by flamber** [comment] 2020-12-22 09:33
Duplicate of #13207

**Closed by flamber** 2020-12-22 09:33 UTC
Labels: .Needs Triage, Type:New Feature
