### ISSUE TITLE
Large integers are rounded on the new question UI

### ISSUE THREAD

**Issue by DandrewsDev** [metabase/metabase#33975] opened 2023-09-19 21:02 UTC
### Describe the bug

When constructing a filter for a new question. I select a integer field and enter in a number to filter too. However this is replaced with a rounded number and as such I cant set my filter to equal the number I'm trying to filter to.

The field I am trying to filter to is for 64 bit steam ids, which are 17 digit numbers. When entering an id like, 76561198275305775 it rounds it to 76561198275305780, which is a different user entirely. 

### Expected behavior

These 17 digit numerical IDs should not be rounded.

### Information about your Metabase installation

```JSON
- Firefox 117.0.1 (64-bit) and Chrome Version 117.0.5938.88
- macOS 13.4.1 
- MongoDB 7.0.0 Community
- Metabase 0.47.2 
- Metabase standalone docker container
- Metabase DB: Postgres
```

### Severity

Annoying: Prevents some wanted filters 

### Additional context

<img width="435" alt="Screenshot 2023-09-19 at 4 44 28 PM" src="https://github.com/metabase/metabase/assets/3299799/d08f1493-23cd-44ca-8fca-ee80f9b65d66">
Pasted value: 76561198275305775
Filtered to value: 76561198275305780

**Comment by paoliniluis** [comment] 2023-09-20 06:57
Dupe of https://github.com/metabase/metabase/issues/5816

**Closed by paoliniluis** 2023-09-20 06:57 UTC
Labels: Type:Bug, .Needs Triage
