### ISSUE TITLE
 Time filter in native SQL query throws 'cannot cast' error

### ISSUE THREAD

**Issue by bugo99iot** [metabase/metabase#7020] opened 2018-02-26 15:04 UTC
Hi, I’m writing a Postgres native SQL query and I am adding filters manually.

> SELECT count(*) AS “count”, (date_trunc(‘week’, CAST((CAST(to_timestamp(“public”.“my_database”.“time”) AS timestamp) + INTERVAL ‘1 day’) AS timestamp)) - INTERVAL ‘1 day’) AS “time”
> 
> FROM “public”.“my_database”
> 
> WHERE {{City}} AND {{Shape}} AND {{Times}}
> 
> etc…

‘City’ and ‘Shape’ filters work well, whereas the ‘Time’ filter once selected for throws the error:

> ERROR: cannot cast type integer to date Position: 417

Once i since the database, I get this other error:

> Error generating fingerprint for Field 312 'time': java.lang.String cannot be cast to java.lang.Number

Wonder what could cause this and how I could fix it. I have selected the time column as a UNIX timestamp in Data Model.

Thanks.

Additional information

- Firefox 48.0
- Ubuntu 16.04
- PostgreSQL hosted on Azure
- Metabase latest release

**Comment by salsakran** [comment] 2018-03-02 00:20
what are the types of the `city`, `shape` and `times` parameters? If they are "field filters", what is the type of the field you are pointing them to?

**Comment by flamber** [comment] 2020-06-02 12:19
Closing, since not enough information to understand the root cause. Please try latest release 0.35.4

**Closed by flamber** 2020-06-02 12:19 UTC
Labels: .Need More Info, Querying/Native, Querying/Parameters & Variables
