### ISSUE TITLE
Calcite Driver (or a Generic JDBC one ?)

### ISSUE THREAD

**Issue by fetanchaud** [metabase/metabase#6920] opened 2018-02-09 12:11 UTC
------
Before filing an issue we'd appreciate it if you could take a moment to ensure
there isn't already an open issue or pull-request.
-----

Hi all (again),

To easily enable data federation in Metabase,
Do you plan to add a driver for Calcite ?

That way Metabase could also help reporting on a directory of CSV files,
with schema self discovery...

Thank you,
Fabrice

**Comment by jornh** [comment] 2018-02-09 17:46
Duplicate of #6230 and #3014

**Comment by salsakran** [comment] 2018-02-15 21:50
as @jornh mentioned, this is a dupe. We have over 1000 open issues. Pretty please search for obvious keywords before opening a new issue.

**Closed by salsakran** 2018-02-15 21:50 UTC
