### ISSUE TITLE
SQL Queries Using References Queries Cannot Filter on String Types

### ISSUE THREAD

**Issue by chipach** [metabase/metabase#16764] opened 2021-06-24 21:57 UTC
**Describe the bug**

There is a saved, non-SQL question (ID #1571 below) with a string filter (e.g. First Name is Chip).  When queried as a referenced card via SQL, an error is returned from the DB (either Snowflake or Postgres) that a bind variable is not set.  When queried from a non-SQL question against the same card, there is no problem.  Further, when a numeric or boolean type is used (e.g. "User ID is 14684") in the original question, both the SQL and non-SQL question that refers to it work.   That is true for equality ("is") and other operations (e.g. greater and less than).

This problem exists for multiple databases (types) and multiple tables.

Modifying the data type for the filtered column to category vs. no semantic type seemed to have no impact.  It seems to be related to the fact that it is a string.  (In fact, changing a column from no semantic type -- which seems to assume string -- to be a number then allowed us to use "is" against that field successfully.)

Converting the original question to SQL (thus statically binding the variable) works.

**Logs**

Will attach file with longer logs, but the relevant piece for the failure is:

```
{:sql
    "-- Metabase:: userID: 16 queryType: native queryHash: 3353be6840670dbf7cd81f509a0b8f4b07c0ba1c50478cabd122efb200f4e215\nselect * from ((SELECT ...  FROM \"ANALYTICS\".\"CORE\".\"USERS\" WHERE \"ANALYTICS\".\"CORE\".\"USERS\".\"FIRST_NAME\" = ? LIMIT 1048575))",
    :params nil,
    :type :invalid-query}}],
 :state "42601",
 :error_type :invalid-query,
 :json_query
 {:type "native",
  :native
  {:query "select * from ({{ #1571 }})",
   :template-tags
   {:#1571
    {:id "837bf6d3-9985-c91e-93ab-aef0d4674980", :name "#1571", :display-name "#1571", :type "card", :card-id 1571}}},
```

Note that it is using nil params into the database, hence the error due to lack of a bind value; the database error makes sense given what is being sent.

[metabase_filter_logs.txt](https://github.com/metabase/metabase/files/6712304/metabase_filter_logs.txt)

**To Reproduce**
1. Create a new Simple question.
2. Select a table and add a static filter against a string field.
3. Save, noting question ID.
4. Create a new Native Query.
5. Do a basic SQL query, such as select * from {{ #questionID }}.
6. Note error that a bind variable cannot be found.  This error comes from the native DB, so does vary slightly with Postgres vs. Snowflake.

**Expected behavior**
Able to use a string filter in a saved table and refer to it from a SQL query.

**Screenshots**

In the screenshots, the saved query is on the left.  The middle is the Native SQL Query.  The right is the GUI "Simple" question with the result below it.

Broken behavior (string filter):
<img width="2547" alt="String Filter Not Working" src="https://user-images.githubusercontent.com/1738637/123336497-f0718b00-d513-11eb-915d-7a76e9354473.png">

Working behavior (numeric filter):
<img width="2550" alt="Numeric Filter Working" src="https://user-images.githubusercontent.com/1738637/123336506-f5363f00-d513-11eb-92fd-5b5b10e6a8a5.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Seen in Safari 14.1.1  and Chrome 91.
- Your operating system: OS X for client.  Server is a Docker (metabase/metabase:v0.39.4)
- Your databases:   Postgres and Snowflake
- Metabase version: 0.39.4 (and 0.39.3)
- Metabase hosting environment: Docker Container
- Metabase internal database: Postgres

**Severity**

This is blocking us from having the source question be something that non-SQL users can manipulate.  We have a workaround by converting the source questions to SQL, but it is blocking us from a workflow where we can have users who don't know SQL manipulate these.  (We're using SQL for the final thing because of some more complicated logic that unions a few of these together.)

**Additional context**

Happy to try additional permutations of this.

**Comment by chipach** [comment] 2021-06-24 22:04
This may the same general problem as https://github.com/metabase/metabase/pull/16724, fixed with https://github.com/metabase/metabase/pull/16724, but I'm not sure!

**Comment by flamber** [comment] 2021-06-25 08:54
Yes, it's a duplicate of #12236

**Closed by flamber** 2021-06-25 08:54 UTC
Labels: .Needs Triage, Type:Bug
