### ISSUE TITLE
Data Model is blank after changing underlying table name

### ISSUE THREAD

**Issue by nickhamlin** [metabase/metabase#9492] opened 2019-02-26 14:51 UTC
- Your browser and the version: Version 70.0.3538.110 (Official Build) (64-bit)
- Your operating system: OSX 10.14.1
- Your databases: MySQL
- Metabase version: 0.31.2
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

If I change the name of an underlying table in MySQL, then sync databases in metabase and update field values, I can no longer see the data model for that corresponding database in the admin console. The page loads, but shows 0 tables. There's no errors either in the metabase logs or in the JS console. If I go change the name back to what it was originally and resync everything again, the data model shows up again just fine.

It looks like there are some similar-sounding issues, like https://github.com/metabase/metabase/issues/6155,  https://github.com/metabase/metabase/issues/6146, and https://github.com/metabase/metabase/issues/6702, but I haven't seen one yet that specifically deals with issues in the data model. Many thanks and please let me know if there's more info I can provide!

UPDATE: The same thing happens if a table is dropped entirely from the underlying database

**Comment by flamber** [comment] 2020-05-30 14:16
I cannot reproduce on 0.35.4 - very likely fixed in 0.32.1
But requires browser refresh to update Data Model - #10330

**Closed by flamber** 2020-05-30 14:16 UTC
Labels: Administration/Data Model, Priority:P3, Type:Bug
