### ISSUE TITLE
Exported CSV/XLSX column names use `name` instead of `display_name`

### ISSUE THREAD

**Issue by sodium238** [metabase/metabase#7902] opened 2018-06-19 12:47 UTC
Even though, I have renamed columns of a table in admin panel.
![capture](https://user-images.githubusercontent.com/33920755/41598014-1096c0b4-73e0-11e8-84bd-7b0bc0ee4cc8.JPG)

Whilst exporting to csv or xlsx, it is taking the names defined in the database table.
![image](https://user-images.githubusercontent.com/33920755/41598119-59738934-73e0-11e8-9323-ff2d6b7978ef.png)

**Comment by tlrobinson** [comment] 2018-06-19 16:52
Related to #3992 and #2473

**Comment by flamber** [comment] 2020-02-19 12:21
If I remember correctly, this was fixed in 0.33.0 - I cannot reproduce on 0.34.2
There's an issue about formatting not being applied to exports: #10879 - upvote by clicking :+1:

**Closed by flamber** 2020-02-19 12:21 UTC
Labels: Reporting/Export

**Comment by semen-ksv** [comment] 2021-08-03 11:52
@flamber Hello!
Have the same problem in version  0.40.1 
CSV/XLSX downloaded files have column names that don't the same as in the Metabase, and also were changed columns position.
![image](https://user-images.githubusercontent.com/56713869/128010047-b1f307ce-dd57-4233-9168-088178b6f624.png)
![image](https://user-images.githubusercontent.com/56713869/128010235-fb5446db-925b-4711-8fbd-410a75c65c65.png)

**Comment by flamber** [comment] 2021-08-03 12:14
@semen-ksv Column title and position done in formatting sidebar is not applied - that's issue #10879 - upvote by clicking :+1:
