### ISSUE TITLE
field mapping bug or just function misunderstanding

### ISSUE THREAD

**Issue by BembelGmbH** [metabase/metabase#5727] opened 2017-08-11 12:14 UTC
(Re)mapping values to each column is a great function! It realizes a 1-step Join afaik. 
I've encounted a situation where it fails or may be it is just not meant to work this way:
Lets say, we have following configuration (regardless whether it makes sense or not :) ):
![untitled-1](https://user-images.githubusercontent.com/20416429/29212321-436db8b8-7e9e-11e7-86d4-f5475ecba19f.png)
Here the `_id` columns are foreign keys for corresponding tables.
On the `Order-Table`, if I am requesting `Raw Data`, instead of the user_id I get the user name. 
So far so good. 
Now lets do the same on `Items-Table`. Here I am requesting `Raw Data` and grouping by `user_id`from the `Order-Table`. As result I get a list of user IDs - but not their names, as I have expected.
Technically this would mean 2-step Join - that's why I am not sure whether this is a bug or not.

**Comment by mazameli** [comment] 2017-08-11 23:19
Yeah, this is unfortunately something that's tripped up a few users already. I think this is effectively a duplicate of https://github.com/metabase/metabase/issues/5600, and was also reported in https://github.com/metabase/metabase/issues/5671.

**Comment by BembelGmbH** [comment] 2017-08-12 06:42
@mazameli  Thank you - it is a bit hard to search for, since everyone gives this feature a different name :) 
These 2 issues seem to be about the same - may be I just drilled down a bit more. Would be better to make one issue out of 3?

**Comment by upccjesse** [comment] 2018-05-16 04:57
I would like to offer some additional insight on this issue from a user's perspective. I will present two configurations below- one with custom mappings that works as expected and one with default foreign key mappings that doesn't (but my expectation is that it should).

## Relevant Database schema  
  * `PC Owner` table contains information about a customer and his device. Of note, this includes a foreign key to the `mainassettypeid` of the `mainassettypes` database.
  * The `mainassettypes` database contains a `mainassetname` field, which is what I want to appear in all questions in place of the `mainassettypeid`. So, instead of ID 1, it would show "Computer", etc.

## Example A: Foreign key to foreign name field mapping  
The intention is to let Metabase handle the mapping. For all `mainassettypeid`s in the `PC Owner` table, all views (raw, bar, scatter, etc) should show the mapped name for that `mainassettypeid` instead of the id. As mentioned by @BembelGmbH, this works as expected in the "Raw Data" view. In the Raw Data view, the `mainassettypeid` is replaced by its representative name as defined in the Admin settings.

However, applying any type of view (like count, average, etc), grouping, or changing the display type (to bar graph, for example) results in the `mainassettypeid` value showing instead of the expected `mainassetname` field it should be mapped to.

### Example A1: Configuration 
![a3](https://user-images.githubusercontent.com/31744530/40097146-83483038-58a2-11e8-830c-8f56ef6267da.PNG)

### Example A2: Raw Data view working as expected
![a1](https://user-images.githubusercontent.com/31744530/40097171-a55bdff8-58a2-11e8-88b5-e73f63a89607.PNG)

### Example A3: Raw Data view with grouping applied- not working as expected
![a2](https://user-images.githubusercontent.com/31744530/40097215-e068f194-58a2-11e8-974c-1e82d14d34db.PNG)

## Example B: Foreign key to custom mapping
The intent is the same but instead of letting Metabase map the keys, I map them manually. This works as expected.

### Example B1: Configuration
![b3](https://user-images.githubusercontent.com/31744530/40097261-2880b8ae-58a3-11e8-9c00-eeb7d337ce65.PNG)

### Example B2: Raw Data view working as expected
![b1](https://user-images.githubusercontent.com/31744530/40097266-32079a00-58a3-11e8-9301-6de178373456.PNG)

### Example B3: Raw Data view with grouping, view applied- working as expected
![b2](https://user-images.githubusercontent.com/31744530/40097278-3cbf8d18-58a3-11e8-8499-859b596ca705.PNG)

## Conclusion

So since the custom mapping works as expected to allow a foreign key to be mapped to a more user-friendly name, I would assume that Foreign Key => Foreign Field mapping should behave the same way. Since it does not, I'm guessing this is a bug?

**Comment by tlrobinson** [comment] 2019-06-14 22:54
Duplicate of #5600

**Closed by tlrobinson** 2019-06-14 22:54 UTC
Labels: UX
