### ISSUE TITLE
DATETIME and TIMESTAMP mix-ups with BigQuery rendering date filter unusable

### ISSUE THREAD

**Issue by shafy** [metabase/metabase#11639] opened 2020-01-06 15:39 UTC
**Describe the bug**

**Case 1**:  TIMESTAMP in BigQuery
If you select something with year in the Date and Time filter (e.g. previous 1 year), it returns the error:

`TIMESTAMP_ADD does not support the YEAR date part`

This is because there is no date part `year` (or `month` for that matter) in the `TIMESTAMP_ADD()` method.

**Case 2**:  DATETIME in BigQuery
So I converted all TIMESTAMPS to DATETIME in my BigQury database, but it still treats the DATETIME field as TIMESTAMP in the metabase filter. E.g. this part of the query:

```
WHERE datetime_trunc(`simplified_prod.locations`.`created_at`, year) =
timestamp_trunc(timestamp_add(current_timestamp(), INTERVAL -1 year), year)
```

The first part is correct, but the GUI filter comes with TIMESTAMP. In the data model is recognized correctly as DATETIME, and I deleted the cached data, re-scanned the fields and the database, tried different browsers etc.

I'm on Metabase v0.34 with BigQury as the database. This error seems to be introduced with 0.34 (didn't have it before).

This is a pretty severe regression, as it makes 0.34 unusable with BigQury as backend.

Probably somehow related to the fixing of #11222

**Comment by lukeman** [comment] 2020-01-06 16:54
This also manifests with DATE fields. When you apply a "prior X weeks" filter on a DATE column, values get casted to TIMESTAMP before the filter is applied and you get the same errors.

This has some dangerous implications as you can't assume date is expressed in any particular timezone and you often get off by one day issues when filtering by UTC.

**Comment by camsaul** [comment] 2020-01-06 18:43
Duplicate of #11578

**Closed by camsaul** 2020-01-06 18:43 UTC
Labels: .Needs Triage, Type:Bug

**Comment by shafy** [comment] 2020-01-06 21:11
Thanks, didn't see that once while searching.
