### ISSUE TITLE
"Not found" when using locked date range filter with embedded dashboards

### ISSUE THREAD

**Issue by philippks** [metabase/metabase#6334] opened 2017-11-06 13:54 UTC
Hello everybody

I can't use dashboard filter parameters with the type "Date Range", when embedding a dashboard. It simply returns "Not Found":
![image](https://user-images.githubusercontent.com/8806985/32443706-40653230-c300-11e7-9cb9-8a17a2a09dde.png)

I reproduced this issue on a clean installation (version 2.26.2), started with docker
```
docker run -d -p 3000:3000 --name metabase metabase/metabase
```

Afterwards I created a question, e.g. the a count on the orders table. This question is added to a dashboard, where I add a "Date Range" filter, which is connected to e.g. the "Created At" date of the orders table:
![image](https://user-images.githubusercontent.com/8806985/32443895-ecbd9108-c300-11e7-915c-03b720b5c585.png)

When embedding, I set the created filter to "Locked" and set a preview value. This leads to the "Not Found".

The resulting code to embed the dashboard looks like this:
```
// you will need to install via 'npm install jsonwebtoken' or in your package.json

var jwt = require("jsonwebtoken");

var METABASE_SITE_URL = "http://localhost:3000";
var METABASE_SECRET_KEY = "...";

var payload = {
  resource: { dashboard: 1 },
  params: {
    "date_range": "2017-11-01~2017-11-30"
  }
};
var token = jwt.sign(payload, METABASE_SECRET_KEY);

var iframeUrl = METABASE_SITE_URL + "/embed/dashboard/" + token + "#bordered=true&titled=true";
```

When I change the filter from "Locked" to "Editable" and set a value in the preview, everything works as expected.

Am I missing something or is this a bug? Thanks for your feedback.

**Comment by zongwenquan** [comment] 2017-11-07 07:16
**me too！**
but i do not think this case  is caused by "Locked" or "Editable", as i‘ve tried both of them;

**My case is：**
I m a Chinese guy, so i edit the filter with "Chinese language";
when i input "炎", **it works**;    "Locked" and "Editable" all worked;
when i input "菌", it shows "**Not found**", I debug the browser, it shows "the iframe url 404!"
and i've checked my mysql language, it’s right.
![Uploading 1.png…]()
![Uploading 2.png…]()
![Uploading 3.png…]()
![Uploading 4.png…]()

**Comment by salsakran** [comment] 2017-12-04 20:27
what version is this @philippks ?

**Comment by philippks** [comment] 2017-12-05 07:51
@salsakran version 2.26.2.

PR #6470 sounds promising, even tough I suspected the tilde and not the dashes (just a guess)

**Comment by salsakran** [comment] 2017-12-05 16:15
Apologies, this was auto-closed by the PR being merged. Re-opening unless it actually did fix the issue.

**Comment by flamber** [comment] 2020-05-24 22:11
I cannot reproduce on 0.35.3

**Closed by flamber** 2020-05-24 22:11 UTC
Labels: Embedding/, Priority:P2, Querying/Parameters & Variables, Type:Bug
