### ISSUE TITLE
Clicking on cancel edit dashboard without any changes removes the dashboard filter

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#17139] opened 2021-07-20 20:23 UTC
**Describe the bug**
On a dashboard that already has some filter set, entering edit mode and then either hitting the "Cancel" button or the "Save" button without making any change will reset whatever filter was already set before.

**Logs**

**To Reproduce**
1. Go to any dashboard that already has the dashboard filter connected to any of the fields
2. Set the filter value if it already wasn't set
3. Note that the url changes and it now includes the filter and its value (correct behavior)
4. Click on the pencil icon to enter Dashboard edit mode
5. Click on "Cancel" button (clicking the "Save" button produces the same behavior but it shouldn't even be possible to click it if there were no changes)
6. The filter is now empty and the url loses all info about the filter.

**Expected behavior**
If there were not any changes made, previously defined filter should be intact.

**Screenshots**
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/12u4nRYO/1ff31bb3-5ce8-4a9a-99c0-0aa20f552a61.gif?source=viewer&v=1b43365bc88a08e4002af862dce3c4cc)

**Information about your Metabase Installation:**
local dev, `master`, x.40.1-SNAPSHOT, 28aab0f

**Severity**
Seems pretty unpredictable. I'd say P2.

**Additional context**
Tested as back as x.38.4 and it was broken all along.

**Comment by nemanjaglumac** [comment] 2021-07-20 20:28
This also resets multiple filters at once.

**Comment by flamber** [comment] 2021-07-22 10:08
Duplicate of #5332

**Closed by flamber** 2021-07-22 10:08 UTC
Labels: .Reproduced, Priority:P3, Querying/Parameters & Variables, Reporting/Dashboards, Type:Bug
