### ISSUE TITLE
Iframe is not downsizing using iframe-resizer

### ISSUE THREAD

**Issue by thiagog3** [metabase/metabase#10132] opened 2019-06-11 14:34 UTC
I'm using iframe-resizer like you recomend to embbed a dashboard but I found a css issue on iframe content that prevents iframe to be downsizing. I found a possible solution when I read iframe-resizer Troubleshooting docs.

Basically we need to remove "height: 100%" from html and body tags. You can read the sugestion here: https://github.com/davidjbradshaw/iframe-resizer/blob/2387294ba16f9d4828960da16518d540ed68a2c8/docs/troubleshooting.md#iframe-not-downsizing

If it's ok for everyone I can provide a PR for this issue.

**Comment by flamber** [comment] 2019-06-11 20:23
Hi @thiagog3 
If you've found an issue and can create a PR, then please do :+1: 
You might need to update the library too, since Metabase's version is 3.5.11 and latest is 4.1.1

**Comment by petrusgomes** [comment] 2019-07-11 21:55
Hi @thiagog3. Were you able to fix this?
We are having similar issues here when alternating between dashboards of different sizes.

**Comment by exzizt** [comment] 2020-02-09 05:32
Is there a fix for this issue yet?

**Comment by flamber** [comment] 2021-11-12 19:41
The embedding was updated in 0.41. I cannot reproduce this issue on 0.41.2

**Closed by flamber** 2021-11-12 19:41 UTC
Labels: Type:Bug, Embedding/

**Comment by jakefurler-hm** [comment] 2023-01-19 03:57
I'm still experiencing this issue on v1.44.6 (cloud). The `body` tag inside the iframe still has its height set to "100%", which means the iframe doesn't downsize. You can reproduce by embedding a dashboard with a few items, resizing the entire window to make it very narrow (the iframe height will correctly resize to be taller to fit the content), and then resizing the window back to its original width. The iframe will not resize to be its original height.

**Comment by juan-maldonado-kenility** [comment] 2024-02-02 14:40
> The embedding was updated in 0.41. I cannot reproduce this issue on 0.41.2

this is still happening to me
