### ISSUE TITLE
Greeting text changes when creating new dashboard

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#14408] opened 2021-01-14 22:21 UTC
**To Reproduce**
Steps to reproduce the behavior
1. Go to the root page
2. Click on the `+` and then "New dashboard"
3. Start typing a dashboard title in the resulting modal
4. Notice that the greeting in the top left of the main page changes.

**Screenshots**
![image](https://user-images.githubusercontent.com/784417/104656140-70054f00-5684-11eb-81b5-cc056e71256c.png)
![image](https://user-images.githubusercontent.com/784417/104656168-77c4f380-5684-11eb-99bd-5a851094e18b.png)
![image](https://user-images.githubusercontent.com/784417/104656187-7eec0180-5684-11eb-9132-106df0ba2d73.png)

**Comment by flamber** [comment] 2021-01-15 09:17
Duplicate of #11952

**Closed by flamber** 2021-01-15 09:17 UTC
Labels: .Frontend, .Needs Triage, Type:Bug
