### ISSUE TITLE
Drilling down by a Region Map assigns the wrong value to the filter

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14650] opened 2021-02-04 01:08 UTC
- Start off with a GUI question where you break out Count of Orders or Count of People by People.State
- Visualize it as a map (should happen automatically)
- Click on a state like Texas and select "View these Orders"
- The filter is incorrectly set to `State is Texas` instead of `State is TX`, so you won't see results
- If you manually change the filter value to `TX`, you'll see results.

I noticed that relatively recently we merged a change that made the tooltips for these maps "smarter" by replacing "TX" in the tooltip with "Texas," and I suspect that change is the cause of or at least related to this bug: you'll notice that if you visualize the same query as e.g. a bar chart instead, and try drilling down the same way, you won't encounter this bug.

![wrong-state-value](https://user-images.githubusercontent.com/2223916/106830049-27690200-6642-11eb-87e8-14c93e5a6a12.gif)

**Comment by flamber** [comment] 2021-02-04 11:05
The smarter tooltip was 0.34.0 #11436 :wink: But this is a regression since 0.37.0
It also happens if you take the exact same query, but change to World map instead.
The problem is that we're sending region_name instead of region_key.

**Comment by paulrosenzweig** [comment] 2021-02-08 20:37
Fixed in #14688

**Closed by paulrosenzweig** 2021-02-08 20:37 UTC
Labels: .Regression, .Reproduced, Priority:P2, Querying/GUI, Type:Bug, Visualization/Maps
