### ISSUE TITLE
Incorrect string value when Migrating from H2 to MySQL

### ISSUE THREAD

**Issue by Microsheep** [metabase/metabase#9741] opened 2019-04-10 01:53 UTC
Currently, I am trying to Migrate from H2 to MySQL.
And is stuck with `Incorrect string value: '\xF0...` error when migrating.

I thought it was due to utf8 and utf8mb4 problem in MySQL
So I drop&recreate the database then change the character set and collate to utf8mb4 by the following
```
ALTER DATABASE metabase_live CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
```
After running the load-from-h2 again, I still get the same error

====================================

Metabase Version: 0.31.2
MySQL Version: 5.7

```
MB_DB_TYPE=mysql
MB_DB_DBNAME=metabase_live
MB_DB_PORT=3306
MB_DB_USER=XXX
MB_DB_PASS=XXX
MB_DB_HOST=XXX
java -jar metabase.jar load-from-h2 /XXX/metabase.db
```

```
Transfering 2228 instances of FieldValues.......BatchUpdateException:
 Message: Incorrect string value: '\xF0\x9F\xA6\x88\xE5\xB0...' for column 'values' at row 1
 SQLState: HY000
 Error Code: 1366
java.sql.BatchUpdateException: Incorrect string value: '\xF0\x9F\xA6\x88\xE5\xB0...' for column 'values' at row 1
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163)
        at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1778)
        at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1262)
        at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
        at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:539)
        at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:532)
        at clojure.java.jdbc$db_do_execute_prepared_statement$fn__4693.invoke(jdbc.clj:969)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:790)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:717)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:730)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:717)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:968)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:954)
        at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:992)
        at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:972)
        at clojure.java.jdbc$insert_cols_BANG_.invokeStatic(jdbc.clj:1498)
        at clojure.java.jdbc$insert_cols_BANG_.invoke(jdbc.clj:1489)
        at clojure.java.jdbc$insert_multi_BANG_.invokeStatic(jdbc.clj:1548)
        at clojure.java.jdbc$insert_multi_BANG_.invoke(jdbc.clj:1523)
        at metabase.cmd.load_from_h2$insert_entity_BANG_$fn__43968.invoke(load_from_h2.clj:129)
        at metabase.cmd.load_from_h2$insert_entity_BANG_.invokeStatic(load_from_h2.clj:128)
        at metabase.cmd.load_from_h2$insert_entity_BANG_.invoke(load_from_h2.clj:108)
        at metabase.cmd.load_from_h2$load_data_BANG_.invokeStatic(load_from_h2.clj:144)
        at metabase.cmd.load_from_h2$load_data_BANG_.invoke(load_from_h2.clj:138)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__44049.invoke(load_from_h2.clj:219)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:747)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:717)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:717)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:730)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:717)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:216)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:209)
        at clojure.lang.Var.invoke(Var.java:381)
        at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:37)
        at metabase.cmd$load_from_h2.invoke(cmd.clj:30)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:657)
        at clojure.core$apply.invoke(core.clj:652)
        at metabase.cmd$run_cmd$fn__44225.invoke(cmd.clj:133)
        at metabase.cmd$run_cmd.invokeStatic(cmd.clj:133)
        at metabase.cmd$run_cmd.invoke(cmd.clj:129)
        at clojure.lang.Var.invoke(Var.java:385)
        at metabase.core$run_cmd.invokeStatic(core.clj:256)
        at metabase.core$run_cmd.invoke(core.clj:254)
        at metabase.core$_main.invokeStatic(core.clj:265)
        at metabase.core$_main.doInvoke(core.clj:261)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at metabase.core.main(Unknown Source)
Caused by: java.sql.SQLException: Incorrect string value: '\xF0\x9F\xA6\x88\xE5\xB0...' for column 'values' at row 1
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
        at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1756)
        ... 48 more
Command failed with exception: Incorrect string value: '\xF0\x9F\xA6\x88\xE5\xB0...' for column 'values' at row 1
```

**Comment by flamber** [comment] 2019-04-10 02:24
Hi @Microsheep 
Changing collation for the database, doesn't change collation for all the tables/columns, so make sure they're all using `utf8mb_...` - here's a guide:
https://confluence.atlassian.com/jirakb/how-to-change-all-columns-and-tables-collation-to-utf8_bin-in-mysql-601456761.html
It's been a while, since I migrated, but I think it creates the structure and then fails on import, and then you can modify the structure and just re-run the migration again.

**Comment by Microsheep** [comment] 2019-04-10 03:06
Hi @flamber~
Thanks for the reply!

I had tested the following and all these SQL return empty rows
```
SELECT * FROM information_schema.SCHEMATA WHERE schema_name = 'metabase_live' AND DEFAULT_COLLATION_NAME != 'utf8mb4_unicode_ci';
SELECT * FROM information_schema.SCHEMATA WHERE schema_name = 'metabase_live' AND DEFAULT_CHARACTER_SET_NAME != 'utf8mb4';
```
```
SELECT * FROM information_schema.TABLES WHERE table_schema = 'metabase_live' AND table_collation != 'utf8mb4_unicode_ci';
```
```
SELECT * FROM information_schema.COLUMNS WHERE table_schema = 'metabase_live' AND collation_name != 'utf8mb4_unicode_ci';
SELECT * FROM information_schema.COLUMNS WHERE table_schema = 'metabase_live' AND CHARACTER_SET_NAME != 'utf8mb4';
```

**Comment by flamber** [comment] 2019-04-10 04:15
@Microsheep 
So does that mean it worked or not?
The entire structure has been created and you've changed charset/collation, but it still fails when you run the migration again?

**Comment by Microsheep** [comment] 2019-04-10 07:55
@flamber Yeah, It still fails...
I can confirm that all those SQL return empty rows, which means all of them shall be already utf8mb4

**Comment by Microsheep** [comment] 2019-04-10 08:02
@camsaul in #9748 you mention about fixing some code related to this functionality
Is it possible that this issue can be solved if I first upgrade metabase then use the upgraded H2 DB to load into MySQL?

**Comment by flamber** [comment] 2019-04-10 08:23
@Microsheep 
Make a backup for the H2 file, then try to upgrade to 0.32.4 and verify that everything is working as it did before, and then you can try migrating again. You cannot upgrade+migrate at the same time.
I did a migration a few months ago to MariaDB 10.2 with Metabase 0.30

**Comment by AntonTsaberyaby** [comment] 2019-05-30 08:24
Looks like a duplicate of #9786

**Comment by camsaul** [comment] 2020-01-16 22:34
Combining this issue into #10691

**Closed by camsaul** 2020-01-16 22:34 UTC
Labels: Operation/, Priority:P3
