### ISSUE TITLE
Feature Request: Option to show percentages multiplied by hundred

### ISSUE THREAD

**Issue by Serfenia** [metabase/metabase#4926] opened 2017-05-02 07:10 UTC
Hello,

I'd like to request a feature to choose when using stacked visualizations;
Currently the y-axis shows 10% to 100% correctly, but when I hover over the point markers it shows the percentage in values between 0 and 1, and my request is to choose to display the values between 0 and 100 so we get a value that has 2 numbers behind the delimiter, instead of a rounded percentage value behind the delimiter.

Can be a part of #4267 as extra enhancement options for visualizations.

Regards,
Serfenia

**Comment by flamber** [comment] 2019-02-14 20:08
Hi @Serfenia 
I'm trying to reproduce your issue without success on 0.31.2, but given all the new formatting options added since 0.31, maybe your issue is resolved (or maybe I'm misunderstanding your request)
![image](https://user-images.githubusercontent.com/1447303/52814513-f57bc100-3061-11e9-8eb3-cb71039b1a0d.png)

**Comment by flamber** [comment] 2020-03-24 10:25
Closing, since it was likely fixed in 0.31. I cannot reproduce on 0.34.3

**Closed by flamber** 2020-03-24 10:25 UTC
Labels: .Proposal, Visualization/Chart Settings
