### ISSUE TITLE
How to make metabase export csv with utf-8 with bom

### ISSUE THREAD

**Issue by archer2012** [metabase/metabase#17466] opened 2021-08-16 08:35 UTC
For help with installation and setup, information on how specific features work, or general questions about Metabase, please use our discussion forum:

https://discourse.metabase.com

The Github issue tracker is intended to collect bug reports and feature requests.
Any issues open for help requests will be closed to keep from clogging up the issue tracker.

**Comment by flamber** [comment] 2021-08-16 08:36
Duplicate of #3271

**Closed by flamber** 2021-08-16 08:36 UTC
Labels: Type:Question, .Needs Triage
