### ISSUE TITLE
How to avoid the filter widget with the dropdown menu from changing to the search box?

### ISSUE THREAD

**Issue by Josh01B** [metabase/metabase#16283] opened 2021-05-28 18:27 UTC
I have encountered an issue trying to use the filter widget with a dropdown menu. It's related to display several categories and click on the selected ones to filter rows.
I have tested it with many categories, and it works fine. But when I enter all categories that I have, the dropdown menu doesn't show the list of values.

On this Metabase site, "https://www.metabase.com/learn/building-analytics/sql-templates/field-filters#distinguishing-field-filters-from-simple-text-number-and-date-variables" says "Note that Metabase will automatically use a Search box if the number of distinct values in the column is greater than 300, even if you select the dropdown option, A list of all values."

I tested it and found there could be even one single category that's not displayed if it's around 10,000 characters long. And I need to hold 16,397 chars.

What could I do to deal with this? (for avoiding the filter widget with the dropdown menu from changing to search box search to displaying all values in the dropdown menu) I've been navigating the code but haven't identified it.

(I attach test cases' pictures.)
1-Dropdown menu with some values, as it should work:
![image9](https://user-images.githubusercontent.com/37640012/120023210-b6f83f00-bfaa-11eb-8809-57001a67a1e5.png)

2-The dropdown menu still works with these values:
a) Categories -> total characters are 9,694 (1,200 categories)
![image](https://user-images.githubusercontent.com/37640012/120023572-3554e100-bfab-11eb-844d-2853d4004611.png)

b) Single category 9,999 characters long
![image](https://user-images.githubusercontent.com/37640012/120023633-4dc4fb80-bfab-11eb-9413-efc7e9810eff.png)

3-But when surpassing 10,000 characters, the dropdown menu changes to the search box:
a) Categories total chars are 10,062
![image](https://user-images.githubusercontent.com/37640012/120024487-844f4600-bfac-11eb-95b6-a7804ead7321.png)

b) Single category 10,010 characters long
![image](https://user-images.githubusercontent.com/37640012/120026753-caf26f80-bfaf-11eb-913b-96c2afc05771.png)

**Comment by flamber** [comment] 2021-05-28 18:35
@Josh01B 
1. Post "Diagnostic Info" from Admin > Troubleshooting
2. And any related errors from Admin > Troubleshooting > Logs.
3. I don't understand what you're doing in 2b or 3a+b

**Comment by Josh01B** [comment] 2021-05-31 07:49
@flamber 
I'm going to post each answer in separate comments.

**Comment by Josh01B** [comment] 2021-05-31 07:52
1. Here is the requested Diagnostic Info of the Metabase platform run in a Docker container. (I put text in case you need to copy-paste something). And after it, there is information about the running Docker version, if it's helpful too.

{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.9.1+1",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.9.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.9.1+1",
    "os.name": "Linux",
    "os.version": "5.8.0-53-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-01-21",
      "tag": "v0.39.0-SNAPSHOT",
      "branch": "master",
      "hash": "fcd8c79"
    },
    "settings": {
      "report-timezone": "America/Costa_Rica"
    }
  }
}

Docker Version
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by Josh01B** [comment] 2021-05-31 07:56
2. I re-ran the queries and interacted with the dropdown menu (the Docker container's time was around "Mon May 31 07:00:22 UTC 2021"), here they are.
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:00:00-06:00 INFO metabase.task.send-pulses Enviando pulsos programados...
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:00-06:00 INFO metabase.task.sync-databases Iniciando tarea de sincronización para la base de datos 4.
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:00-06:00 INFO metabase.sync.util STARTING: Sync metadata for postgres Base de Datos 4 'reporteria'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:00-06:00 INFO metabase.sync.util STARTING: paso 'sync-timezone' para postgres Base de Datos 4 'reporteria'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:00-06:00 INFO metabase.sync.util FINISHED: paso 'sync-timezone' para postgres Base de Datos 4 'reporteria' (8.0 ms)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:00-06:00 INFO metabase.sync.util STARTING: paso 'sync-tables' para postgres Base de Datos 4 'reporteria'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:00-06:00 INFO metabase.sync.util FINISHED: paso 'sync-tables' para postgres Base de Datos 4 'reporteria' (322.9 ms)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:00-06:00 INFO metabase.sync.util STARTING: paso 'sync-fields' para postgres Base de Datos 4 'reporteria'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:08-06:00 WARN metabase.driver.sql-jdbc.sync.describe-table Don't know how to map column type '_varchar' to a Field base_type, falling back to :type/*.
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:08-06:00 INFO metabase.sync.util FINISHED: paso 'sync-fields' para postgres Base de Datos 4 'reporteria' (8.5 s)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:08-06:00 INFO metabase.sync.util STARTING: paso 'sync-fks' para postgres Base de Datos 4 'reporteria'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:16-06:00 INFO metabase.sync.util FINISHED: paso 'sync-fks' para postgres Base de Datos 4 'reporteria' (7.5 s)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:16-06:00 INFO metabase.sync.util STARTING: paso 'sync-metabase-metadata' para postgres Base de Datos 4 'reporteria'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:16-06:00 INFO metabase.sync.util FINISHED: paso 'sync-metabase-metadata' para postgres Base de Datos 4 'reporteria' (253.3 ms)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:16-06:00 INFO metabase.sync.util FINISHED: Sync metadata for postgres Base de Datos 4 'reporteria' (16.6 s)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:16-06:00 INFO metabase.sync.util STARTING: Analyze data for postgres Base de Datos 4 'reporteria'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:16-06:00 INFO metabase.sync.util STARTING: paso 'fingerprint-fields' para postgres Base de Datos 4 'reporteria'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:18-06:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [*****·············································] 😢   10% Tabla 1.450 'proxy_schema_1.mdl_events_queue_handlers'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:20-06:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [**********········································] 😞   20% Tabla 1.603 'proxy_schema_1.mdl_course_format_options'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:21-06:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [***************···································] 😕   30% Tabla 1.756 'proxy_schema_1.mdl_stats_weekly'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:21-06:00 INFO metabase.sync.util FINISHED: paso 'fingerprint-fields' para postgres Base de Datos 4 'reporteria' (5.1 s)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:21-06:00 INFO metabase.sync.util STARTING: paso 'classify-fields' para postgres Base de Datos 4 'reporteria'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:21-06:00 INFO metabase.sync.analyze classify-fields Analyzed [********************······························] 😐   40% Tabla 1.400 'proxy_schema_1.mdl_questionnaire_fb_sections'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:21-06:00 INFO metabase.sync.analyze classify-fields Analyzed [*************************·························] 😬   50% Tabla 1.553 'proxy_schema_1.mdl_plagiarism_turnitin_files'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:21-06:00 INFO metabase.sync.analyze classify-fields Analyzed [******************************····················] 😌   60% Tabla 1.706 'proxy_schema_1.mdl_scorm_scoes'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:21-06:00 INFO metabase.sync.util FINISHED: paso 'classify-fields' para postgres Base de Datos 4 'reporteria' (229.2 ms)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:21-06:00 INFO metabase.sync.util STARTING: paso 'classify-tables' para postgres Base de Datos 4 'reporteria'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:21-06:00 INFO metabase.sync.analyze classify-tables Analyzed [***********************************···············] 😏   70% Tabla 1.350 'proxy_schema_1.mdl_wiki_pages'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:22-06:00 INFO metabase.sync.analyze classify-tables Analyzed [****************************************··········] 😊   80% Tabla 1.503 'proxy_schema_1.mdl_forum_discussion_subs'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:22-06:00 INFO metabase.sync.analyze classify-tables Analyzed [*********************************************·····] 😍   90% Tabla 1.656 'proxy_schema_1.mdl_grade_grades_history'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:22-06:00 INFO metabase.sync.util FINISHED: paso 'classify-tables' para postgres Base de Datos 4 'reporteria' (486.0 ms)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:04:22-06:00 INFO metabase.sync.util FINISHED: Analyze data for postgres Base de Datos 4 'reporteria' (5.8 s)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:00-06:00 INFO metabase.task.sync-databases Iniciando tarea de sincronización para la base de datos 3.
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:00-06:00 INFO metabase.sync.util STARTING: Sync metadata for postgres Base de Datos 3 'moodle_mv_test'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:00-06:00 INFO metabase.sync.util STARTING: paso 'sync-timezone' para postgres Base de Datos 3 'moodle_mv_test'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:00-06:00 INFO metabase.sync.util FINISHED: paso 'sync-timezone' para postgres Base de Datos 3 'moodle_mv_test' (13.9 ms)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:00-06:00 INFO metabase.sync.util STARTING: paso 'sync-tables' para postgres Base de Datos 3 'moodle_mv_test'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:00-06:00 INFO metabase.sync.util FINISHED: paso 'sync-tables' para postgres Base de Datos 3 'moodle_mv_test' (503.7 ms)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:00-06:00 INFO metabase.sync.util STARTING: paso 'sync-fields' para postgres Base de Datos 3 'moodle_mv_test'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:16-06:00 INFO metabase.sync.util FINISHED: paso 'sync-fields' para postgres Base de Datos 3 'moodle_mv_test' (16.3 s)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:16-06:00 INFO metabase.sync.util STARTING: paso 'sync-fks' para postgres Base de Datos 3 'moodle_mv_test'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:22-06:00 INFO metabase.sync.util FINISHED: paso 'sync-fks' para postgres Base de Datos 3 'moodle_mv_test' (5.8 s)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:22-06:00 INFO metabase.sync.util STARTING: paso 'sync-metabase-metadata' para postgres Base de Datos 3 'moodle_mv_test'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:23-06:00 INFO metabase.sync.util FINISHED: paso 'sync-metabase-metadata' para postgres Base de Datos 3 'moodle_mv_test' (876.2 ms)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:23-06:00 INFO metabase.sync.util FINISHED: Sync metadata for postgres Base de Datos 3 'moodle_mv_test' (23.5 s)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:23-06:00 INFO metabase.sync.util STARTING: Analyze data for postgres Base de Datos 3 'moodle_mv_test'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:23-06:00 INFO metabase.sync.util STARTING: paso 'fingerprint-fields' para postgres Base de Datos 3 'moodle_mv_test'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:26-06:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [*****·············································] 😢   10% Tabla 957 'public.mdl_oauth2_user_field_mapping'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:27-06:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [**********········································] 😞   20% Tabla 1.103 'public.mdl_format_grid_icon'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:30-06:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [***************···································] 😕   30% Tabla 1.249 'public.mdl_auth_oauth2_linked_login'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:31-06:00 INFO metabase.sync.util FINISHED: paso 'fingerprint-fields' para postgres Base de Datos 3 'moodle_mv_test' (7.6 s)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:31-06:00 INFO metabase.sync.util STARTING: paso 'classify-fields' para postgres Base de Datos 3 'moodle_mv_test'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:31-06:00 INFO metabase.sync.analyze classify-fields Analyzed [********************······························] 😐   40% Tabla 909 'public.mdl_book_chapters'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:31-06:00 INFO metabase.sync.analyze classify-fields Analyzed [*************************·························] 😬   50% Tabla 1.055 'public.mdl_stats_monthly'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:31-06:00 INFO metabase.sync.analyze classify-fields Analyzed [******************************····················] 😌   60% Tabla 1.201 'public.mdl_question_numerical_options'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:31-06:00 INFO metabase.sync.util FINISHED: paso 'classify-fields' para postgres Base de Datos 3 'moodle_mv_test' (278.6 ms)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:31-06:00 INFO metabase.sync.util STARTING: paso 'classify-tables' para postgres Base de Datos 3 'moodle_mv_test'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:31-06:00 INFO metabase.sync.analyze classify-tables Analyzed [***********************************···············] 😏   70% Tabla 861 'public.mdl_role_assignments'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:31-06:00 INFO metabase.sync.analyze classify-tables Analyzed [****************************************··········] 😊   80% Tabla 1.007 'public.mdl_gradingform_rubric_levels'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:31-06:00 INFO metabase.sync.analyze classify-tables Analyzed [*********************************************·····] 😍   90% Tabla 1.153 'public.mdl_game_bookquiz'
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:31-06:00 INFO metabase.sync.util FINISHED: paso 'classify-tables' para postgres Base de Datos 3 'moodle_mv_test' (376.3 ms)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:09:31-06:00 INFO metabase.sync.util FINISHED: Analyze data for postgres Base de Datos 3 'moodle_mv_test' (8.3 s)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:16:29-06:00 INFO metabase.server.middleware.exceptions Solicitud cancelada antes de terminar.
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:20:07-06:00 INFO metabase.server.middleware.exceptions Solicitud cancelada antes de terminar.
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:20:07-06:00 INFO metabase.server.middleware.exceptions Solicitud cancelada antes de terminar.
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:20:07-06:00 INFO metabase.server.middleware.exceptions Solicitud cancelada antes de terminar.
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:22:21-06:00 INFO metabase.api.card Los metadatos de resultados de tarjetas pasados a API son VÁLIDOS. ¡Gracias!
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:23:32-06:00 INFO metabase.api.card Los metadatos de resultados de tarjetas pasados a API son VÁLIDOS. ¡Gracias!
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:25:01-06:00 INFO metabase.api.card Los metadatos de resultados de tarjetas pasados a API son VÁLIDOS. ¡Gracias!
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:26:36-06:00 INFO metabase.api.card Los metadatos de resultados de tarjetas pasados a API son VÁLIDOS. ¡Gracias!
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:27:26-06:00 INFO metabase.api.card Los metadatos de resultados de tarjetas pasados a API son VÁLIDOS. ¡Gracias!
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:27:35-06:00 INFO metabase.server.middleware.exceptions Solicitud cancelada antes de terminar.
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:38:47-06:00 INFO metabase.api.card FALTAN los metadatos de resultados de la tarjeta en el API. Ejecutando la consulta para obtener los metadatos correctos.
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:38:47-06:00 INFO metabase.models.card Card references Fields in params: (16270)
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:43:50-06:00 INFO metabase.models.dashboard Referenced Fields in Dashboard params have changed: Was: #{16137 16261 16250 16152 16253 16267 16255 16146 16264 16258} Is Now: #{16137 16261 16250 16152 16253 16267 16255 16146 16270 16264 16258} Newly Added: #{16270}
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:47:34-06:00 INFO metabase.api.card Los metadatos de resultados de tarjetas pasados a API son VÁLIDOS. ¡Gracias!
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:47:51-06:00 INFO metabase.api.card Los metadatos de resultados de tarjetas pasados a API son VÁLIDOS. ¡Gracias!
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:49:18-06:00 INFO metabase.api.card Los metadatos de resultados de tarjetas pasados a API son VÁLIDOS. ¡Gracias!
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T00:49:33-06:00 INFO metabase.api.card Los metadatos de resultados de tarjetas pasados a API son VÁLIDOS. ¡Gracias!
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T01:11:30-06:00 INFO metabase.api.card FALTAN los metadatos de resultados de la tarjeta en el API. Ejecutando la consulta para obtener los metadatos correctos.
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T01:16:24-06:00 INFO metabase.api.card Los metadatos de resultados de tarjetas pasados a API son VÁLIDOS. ¡Gracias!
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T01:16:31-06:00 INFO metabase.api.card FALTAN los metadatos de resultados de la tarjeta en el API. Ejecutando la consulta para obtener los metadatos correctos.
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T01:16:47-06:00 INFO metabase.api.card FALTAN los metadatos de resultados de la tarjeta en el API. Ejecutando la consulta para obtener los metadatos correctos.
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T01:17:15-06:00 INFO metabase.api.card Los metadatos de resultados de tarjetas pasados a API son VÁLIDOS. ¡Gracias!
[410b76cd-20a3-48e9-8dc5-4543af0e1772] 2021-05-31T01:21:15-06:00 INFO metabase.api.card Los metadatos de resultados de tarjetas pasados a API son VÁLIDOS. ¡Gracias!

**Comment by Josh01B** [comment] 2021-05-31 07:58
3. Regarding the pictures:
Picture 2a shows the dropdown menu can hold 1,200 categories.
I wondered how to determine the menu’s limit. Then I tested with different amounts of category names and noticed the longer the categories’ strings are, the fewer categories the menu can hold.
Picture 2b shows it can hold 9,999 characters. And picture 3b shows the category stops displaying the dropdown menu when the amount of characters in the category is 10,010.
Picture 3a is for showing that having multiple categories or a single one doesn’t seem to be the problem, but the number of characters the dropdown menu can hold. It supports around 10,000 chars, and I need to hold 16,397 chars.

**Comment by flamber** [comment] 2021-05-31 12:21
@Josh01B I would recommend that you try one of the releases and not a development branch, which is also 4 months old.
There are several issues open about filter dropdowns - this being a duplicate of one or several of those, so closing in favor of those:
https://github.com/metabase/metabase/issues?q=is%3Aissue+is%3Aopen+author%3Aflamber+dropdown+created%3A2021-05-17

**Closed by flamber** 2021-05-31 12:21 UTC
Labels: .Needs Triage, Type:Bug

**Comment by Josh01B** [comment] 2021-05-31 19:22
@flamber I'll clone the last release branch and check out the other issues you showed me, thanks for your recommendations.
![image](https://user-images.githubusercontent.com/37640012/120233215-8581ac80-c212-11eb-820e-6fd821503986.png)
