### ISSUE TITLE
Columns are marked as entity key if they're part of complex index

### ISSUE THREAD

**Issue by vitos555** [metabase/metabase#5633] opened 2017-07-28 18:46 UTC
We have several tables with complex indices (i.e. something like `unique key key_name(col1, col2)`) and for those tables filtration by any column of the index shows a single card as result, not a list of rows (even though there are several rows satisfying filtration conditions).

**Comment by camsaul** [comment] 2017-07-28 18:58
Hi @vitos555, Metabase doesn't currently fully support composite primary keys for things like click-thru filtering. It's something we're looking at addressing in the future. We have an open issue for tracking it, so I'm going to go ahead and close this as a duplicate of #3475

**Closed by camsaul** 2017-07-28 18:58 UTC
