### ISSUE TITLE
Metabase 0.34.0 Changing timezone does not change timestamps

### ISSUE THREAD

**Issue by anshulk** [metabase/metabase#11623] opened 2020-01-03 07:15 UTC
Earlier version (0.33.6) had a specific timezone set in admin settings
and times were shown in that timezone.

On updating all times are shown in the default db timezone (UTC) instead.

**Comment by flamber** [comment] 2020-01-03 07:35
Hi @anshulk 
It would be really helpful with more details, like Diagnostic Info from Admin > Troubleshooting, and which database+version which had a different behavior.

**Comment by camsaul** [comment] 2020-01-10 23:00
@anshulk in 0.34.0 we made tweaks so that databases that do not support setting session timezones show their data in their actual timezone the data is in. Report Time Zone is only supported for databases that support session time zones, as mentioned [in the documentation](https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html).

Either way, we don't have enough information to help debug this issue further – please fill out the bug questionnaire from the new issue template.

**Comment by davidllorente** [comment] 2020-01-31 13:46
I'm having the same issue, my Database is Druid (which supports Report Time Zone) but the native query always has "UTC" as the timezone, regardless of my config in the Admin settings. This behaviour also started with 0.34.0

**Comment by dacort** [comment] 2020-01-31 17:52
@davidllorente Are you able to provide more details of your Metabase instance, for example the "Diagnostic Info" from the troubleshooting page? I'd have to check how the Druid driver is implemented, but I know on the Postgres side we set the session timezone instead of converting the queries themselves.

**Comment by davidllorente** [comment] 2020-01-31 19:06
@dacort here it is:
`{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "3.10.0-693.21.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "druid"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "date": "2020-01-13",
      "tag": "v0.34.1",
      "branch": "release-0.34.x",
      "hash": "265695c"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}`

**Comment by davidllorente** [comment] 2020-04-14 10:48
Any follow-up on this? I've just tried updating to 0.35.2 and I'm still having the same issue (all queries to Druid are setting UTC as the timezone in their native query).

Weirdly enough, the X-axis timeseries shows up in the correct timezone but all visualizations (line, table, etc.) show the timestamps in UTC:

![Screenshot 2020-04-14 at 12 47 28](https://user-images.githubusercontent.com/14162118/79216852-2a45fc80-7e4e-11ea-820c-ed9b9fb49d2f.png)

**Comment by davidllorente** [comment] 2020-05-18 11:17
@dacort could you take a look at this issue? I would create another one with more detailed info of my exact case but it would be a duplicate of this one in essence.

@camsaul I've taken a look at the documentation and for the [latest version](https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html) it is stated that Druid is supported for Report Time Zone, but in the [github wiki](https://github.com/metabase/metabase/wiki/Understanding-Timezones-in-Metabase#database-support) it says that it is **not** supported! The wiki was updated on October 2019. Could be that the docs are outdated and Report Time Zone has been removed for Druid and currently only supports MySQL and PostgreSQL?

**Comment by leonardonunespuc** [comment] 2020-08-08 06:50
I'm having the same problem with Druid.
My Report Timezone is set to 'America/Sao_Paulo' but when I build a question the timezone in the native query is set to 'UTC'. 

<img src="https://github.com/leonardonunespuc/images/blob/master/Screen%20Shot%202020-08-08%20at%2003.31.16.png?raw=true" />


On the graph, the date and time on the X-axis are correct, but the ones on the tooltip are not on my timezone.

<img src="https://github.com/leonardonunespuc/images/blob/master/Screen%20Shot%202020-08-08%20at%2003.30.15.png?raw=true" />



<img src="https://github.com/leonardonunespuc/images/blob/master/Screen%20Shot%202020-08-08%20at%2003.32.03.png?raw=true" />


**Diagnostic Info**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "3.10.0-1062.1.2.el7.x86_64",
    "user.language": "en",
    "user.timezone": "America/Sao_Paulo"
  },
  "metabase-info": {
    "databases": [
      "druid",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.8"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-21",
      "tag": "v0.35.3",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": "America/Sao_Paulo"
    }
  }
}
```

**Comment by flamber** [comment] 2020-08-08 09:22
For Druid, it sounds like you're seeing #6289. I'm going to close this issue, since it doesn't contain enough specific information.

**Closed by flamber** 2020-08-08 09:22 UTC
Labels: .Need More Info, Misc/Timezones, Type:Bug
