### ISSUE TITLE
Binning/granularity menu is out of the screen after reopening

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#15534] opened 2021-04-09 01:25 UTC
**Describe the bug**
Binning/granularity menu is out of the screen after reopening. The situation gets worse when there only a few columns so that the scroll is not shown because triggering scroll repositioning of the menu.

**To Reproduce**
1. Go to Simple Question page
2. Select sample dataset, orders table
3. Click summarize, find "Created At" and click multiple times on its Binning/granularity menu

**Screenshot**
<img width="360" alt="Screen Shot 2021-04-09 at 04 13 13" src="https://user-images.githubusercontent.com/14301985/114115510-9df8d900-98eb-11eb-9ec9-3416041cf0f8.png">

**Comment by flamber** [comment] 2021-04-09 08:23
Likely the same problem as #15502 and #15277

**Comment by nemanjaglumac** [comment] 2021-04-09 15:39
@howonlee since you're working on this set of issues, can you please take a look at this one as well? Thanks

**Comment by howonlee** [comment] 2021-04-09 17:12
I think this is exactly the same issue, we just haven't landed the fix yet

**Comment by flamber** [comment] 2021-04-20 14:39
I cannot reproduce on 0.39.0

**Closed by flamber** 2021-04-20 14:39 UTC
Labels: Priority:P1, Querying/GUI, Type:Bug
