### ISSUE TITLE
User Level Timezone

### ISSUE THREAD

**Issue by teotia-bizSystems-curefit** [metabase/metabase#11696] opened 2020-01-13 06:39 UTC
**Is your feature request related to a problem? Please describe.**
We want our users to be able to work in whichever timezone they prefer rather than restricting it to system level. Kindly help if this can be done using existing features or guide what is the optimal way to make these changes in codebase for our use case.

**Describe the solution you'd like**
We want to add an timezone field at user level (`edit_current`) which should be used to render timezone for that particular user.

**How important is this feature to you?**
This is an important feature to us since our users access metabase from different timezones and we don't want to host different applications for different timezones.

**Comment by mazameli** [comment] 2020-01-15 01:19
Duplicate of https://github.com/metabase/metabase/issues/4284

**Closed by mazameli** 2020-01-15 01:19 UTC
Labels: .Duplicate, Type:New Feature
