### ISSUE TITLE
Dashboard variables

### ISSUE THREAD

**Issue by vesteinn** [metabase/metabase#1941] opened 2016-02-15 11:45 UTC
As question and dashboard configurations are time consuming yet hard coded, setting and use of global variables could enable swift reconfiguration with minimum cost.

This would allow for a single dashboard/question-set configuration to serve multiple views.

**Comment by camsaul** [comment] 2016-02-26 04:25
Duplicate of #1543

**Closed by camsaul** 2016-02-26 04:25 UTC
Labels: Dashboards, Proposal
