### ISSUE TITLE
Add option to display data values on charts

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4788] opened 2017-04-14 19:03 UTC
This is mentioned in #4267, but I don't believe it has its own issue, and I think it warrants one. This would require us to figure out how to do this for each visualization type, but there are plenty of examples we can reference, like these from Highcharts:

- [Bars with values on top](http://www.highcharts.com/demo/column-drilldown)
- [Bars with rotated values inside](http://www.highcharts.com/demo/column-rotated-labels)
- [Horizontal bars with values at the end](http://www.highcharts.com/demo/bar-basic)
- [Lines with values on top of each tick](http://www.highcharts.com/demo/line-labels)
- [Stacked bar with values inside](http://www.highcharts.com/demo/column-stacked)
- [Bubble chart with breakout dimension value rather than metric inside](http://www.highcharts.com/demo/bubble)

**Some open questions:**
- For which charts can we do this?
- Is there more than one option per visualization type?
- What happens if a value is super long and doesn't fit? Do we change the size, ellipsify, etc.?

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by alee792** [comment] 2017-08-14 19:44
Hey Maz, a really cool feature I've seen in other viz platforms is a "fill-in" bar on a table. The following is Superset's implementation of this feature. 

![image](https://user-images.githubusercontent.com/6137401/29288628-6c10c452-8107-11e7-93bf-96a951864b44.png)

**Comment by EvaSchreyer** [comment] 2017-08-16 09:36
Hi there, I was wondering if there are any news on data labels for charts - that would be very helpful. 
Cheers, Eva

**Comment by HelenMertes** [comment] 2017-11-22 16:59
Hi,
I have noticed the new display of all series' values when hovering over the lowest series in a stacked bar chart in the latest release v0.27.0.RC1. 

However, I find this rather irritating and not very easy to view and digest, also as it covers and blocks a large part of the chart (several Metabase users in my team have expressed a similar opinion). 

What would be really useful instead is an option to display the total sum of stacked bars' values!

Thanks, Helen

**Comment by aniamin** [comment] 2018-03-01 05:16
Any Update on this?

**Comment by alexflom2** [comment] 2018-05-28 10:30
Hey, 
Any update on Add option to display data values on charts ? 

Its a must feature. 

Thank you very much

**Comment by mickdelaney** [comment] 2018-06-18 20:05
Is this likely to happen ? Our clients want to print embedded charts but without the data values it doesn’t really achieve what they want.

**Comment by liransmartlighthouse** [comment] 2018-08-30 22:04
Hi there,

I'm also a big supporter for this new feature.

**Comment by jornh** [comment] 2018-08-31 02:38
Hey everyone, one way the core team prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍 comments, please just upvote by adding a reaction to the issue description.

**Comment by lutvdh** [comment] 2018-11-28 10:04
@camsaul , do you know if the metabase team have a response on this topic?   Really a great suggestion and would like to understand if its on the roadmap.

**Comment by mazameli** [comment] 2018-11-28 18:37
@lutvdh This is definitely something we want to add, so I'd say yes it's on our roadmap, but I can't say for certain if it will be in the very next major release vs. the one after that quite yet.

**Comment by lutvdh** [comment] 2018-11-28 19:52
Thank you @mazameli , that is awesome news!!  Will monitor your roadmaps allocations closely.

**Comment by jmilan** [comment] 2019-01-08 18:49
This functionality will help me a lot, please request the prioritization

**Comment by MarcGJA** [comment] 2019-03-29 04:03
Happy to make it upvote #99!  Apparently some users just can't wait any longer and are will to hire out to get this feature custom built for them! https://discourse.metabase.com/t/software-development-wanted/5791
Other items that will benefit a great many users are <a href="https://github.com/metabase/metabase/issues/8219">search widgets</a>, <a href="https://github.com/metabase/metabase/issues/9591">item ordering</a>, <a href="https://github.com/metabase/metabase/issues/5540">dependent filters</a>, <a href="https://github.com/metabase/metabase/issues/9208">binning & formatting</a>, <a href="https://discourse.metabase.com/t/embedded-geojson-maps-not-resolving/5145">embed maps</a>.
Perhaps the new modularization of <a href="https://github.com/metabase/metabase/releases/tag/v0.32.0-RC1">Metabase 0.32 - RC1</a> will help.

**Comment by MarcGJA** [comment] 2019-03-29 04:08
Happy to make it upvote number 99!  Apparently some users are just can't wait and are taking matters into their own hands! https://discourse.metabase.com/t/software-development-wanted/5791
Among other items that will benefit a great many users are improvements in <a href="https://github.com/metabase/metabase/issues/8219">search widgets</a>, <a href="https://github.com/metabase/metabase/issues/9591">item ordering</a>, <a href="https://github.com/metabase/metabase/issues/5540">dependent filters</a>, <a href="https://github.com/metabase/metabase/issues/9208">binning & formatting</a>, and <a href="https://discourse.metabase.com/t/embedded-geojson-maps-not-resolving/5145">embed maps</a>.
Perhaps the new modularization of <a href="https://github.com/metabase/metabase/releases/tag/v0.32.0-RC1">Metabase 0.32 - RC1</a> will help.

**Comment by MarcGJA** [comment] 2019-03-29 04:09
Happy to make it upvote number 99!  Apparently some users just can't wait and are taking matters into their own hands! https://discourse.metabase.com/t/software-development-wanted/5791
Among other items that will benefit a great many users are improvements in <a href="https://github.com/metabase/metabase/issues/8219">search widgets</a>, <a href="https://github.com/metabase/metabase/issues/9591">item ordering</a>, <a href="https://github.com/metabase/metabase/issues/5540">dependent filters</a>, <a href="https://github.com/metabase/metabase/issues/9208">binning & formatting</a>, and <a href="https://discourse.metabase.com/t/embedded-geojson-maps-not-resolving/5145">embed maps</a>.
Perhaps the new modularization of <a href="https://github.com/metabase/metabase/releases/tag/v0.32.0-RC1">Metabase 0.32 - RC1</a> will help.

**Comment by exabrial** [comment] 2019-04-12 17:19
Hey Guys! Is anyone interested in pooling resources to pay for an implementation on this? Anything from $5 to $5000?

**Comment by hrpitta** [comment] 2019-04-15 12:10
> Hey Guys! Is anyone interested in pooling resources to pay for an implementation on this? Anything from $5 to $5000?

For sure!

**Comment by exabrial** [comment] 2019-04-15 15:15
We have a clojure developer step forward who may be interested! Let me talk with him and get an estimate of time.

**Comment by megrahamdutton** [comment] 2019-04-23 13:36
This would be really good for my wallboards

**Comment by fabiohvp** [comment] 2019-05-05 14:16
I also think this is an important feature, especially if you want to print the charts or if you are using the charts in mobile web apps

**Comment by exabrial** [comment] 2019-05-06 14:09
Great news everyone, the devs got back to me and showed me a quick prototype. If you are willing to contribute to the cause, I think I'm going to try get a gofundme or something together.

![metabase-piechart](https://user-images.githubusercontent.com/1392297/57230613-5a4e1400-6fde-11e9-94d3-d6d69c6964dd.png)

My biggest fear is we get across the finish line but can't get it merged into master. @mazameli @tlrobinson or @camsaul If you have an opinion about this, please let us know. I'd hate to spend the development effort and not have that happen! Thank you!

**Comment by exabrial** [comment] 2019-05-20 20:15
@mazameli @tlrobinson or @camsaul I'd love to hear your thoughts, thank you!

**Comment by dannyeuu** [comment] 2019-05-24 21:54
@mazameli maybe something like this, and show the values:
![Screenshot from 2019-05-24 18-42-24](https://user-images.githubusercontent.com/6808348/58358429-3cddce80-7e55-11e9-9224-147a22d8ca0f.png)

**Comment by caasebo** [comment] 2019-05-27 19:33
When is this coming? This is a MUST have feature, so you can see the numbers on big screens.

**Comment by mazameli** [comment] 2019-12-03 22:40
Just an update to everyone that work is in progress on this, and it's planned for the next version, 0.34. :)

**Closed** 2019-12-05 23:17 UTC
Labels: Priority:P1, Type:Completeness, Visualization/Chart Settings

**Comment by ycaruso** [comment] 2019-12-06 14:06
@mazameli ty, great work, we look forward to seeing how it will look.

**Comment by pragyan003** [comment] 2020-06-11 11:31
is the issue resolved yet?
i'm using the metabase version -  v0.35.2
and i'm still not able to show data labels on the bar chart

**Comment by flamber** [comment] 2020-06-11 12:00
@pragyan003 Yes, it has been available since 0.34.0, but limited to single-series. Work is being done to try to add it to multi-series in 0.36.0. Latest release is 0.35.4
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
