### ISSUE TITLE
Date time field for Midnight shows 24: instead of 0:

### ISSUE THREAD

**Issue by tatusis** [metabase/metabase#12486] opened 2020-05-08 23:53 UTC
**Describe the bug**
Date time field for Midnight shows 24: instead of 0:
Is there any way to modify this behavior?

**Expected behavior**
Field date time to Midnight should show 0:00 until 00:59 in the first hour of the day and not 24:00 until 24:59.

**Screenshots**
Configuration:
![image](https://user-images.githubusercontent.com/55719904/81457768-d5a45180-916d-11ea-9d5a-4de390adb246.png)
Problem:
![image](https://user-images.githubusercontent.com/55719904/81457494-af31e680-916c-11ea-9a72-7e361d9a30cc.png)

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_241-b07",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_241",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.241-b07",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "America/Sao_Paulo"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "oracle",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.14"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.3",
      "date": "2020-04-21",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
We are culturally accustomed to the first hour of the day being represented: 0:00 until 00:59, and not: 24:00 until 24:59.

**Comment by flamber** [comment] 2020-05-09 08:36
Duplicate of #9538

**Closed by flamber** 2020-05-09 08:36 UTC
Labels: .Duplicate, Type:Bug
