### ISSUE TITLE
TAB in Chrom freezes upon clicking on SORT settings in a question

### ISSUE THREAD

**Issue by kandadaboggu** [metabase/metabase#3003] opened 2016-07-22 08:53 UTC
When I click on the `SORT` button, the TAB freezes and becomes unresponsive. 
![image](https://cloud.githubusercontent.com/assets/185035/17051698/da1b9520-4fae-11e6-99cd-70093409a675.png)

I see the following error in the console.
```javascript
invariant.js:35 Uncaught (in promise) Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.(…)r 
@ invariant.js:35unmountComponentAtNode 
@ ReactMount.js:609value 
@ Tooltip.jsx:47notifyAll 
@ CallbackQueue.js:65close 
@ ReactReconcileTransaction.js:81closeAll 
@ Transaction.js:202perform 
@ Transaction.js:149perform 
@ Transaction.js:136perform 
@ ReactUpdates.js:86x 
@ ReactUpdates.js:147closeAll 
@ Transaction.js:202perform 
@ Transaction.js:149batchedUpdates 
@ ReactDefaultBatchingStrategy.js:62l 
@ ReactUpdates.js:176r 
@ ReactUpdateQueue.js:24enqueueSetState 
@ ReactUpdateQueue.js:190r.setState 
@ ReactComponent.js:65u.handleChange 
@ connect.js:301c 
@ createStore.js:186(anonymous function) 
@ index.js:28(anonymous function)
@ index.js:14dispatch 
@ applyMiddleware.js:45(anonymous function) 
@ redux.js:70r 
@ runtime.js:61(anonymous function) 
@ runtime.js:329e.(anonymous function) 
@ runtime.js:94r 
@ app.bundle.js:1976(anonymous function) 
@ app.bundle.js:1976
invariant.js:35 Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
```

*  I am using the Chrome browser.
*  My computer's OS is MacOSX.
*  I'm running Metabase on Herkou / etc.] and it is using the Postgres database.
*  My data is in a Postgres database. 
*  My Metabase version is v0.18.1.

**Comment by tlrobinson** [comment] 2016-07-22 10:09
Duplicate of #2859

**Closed by tlrobinson** 2016-07-22 10:09 UTC
