### ISSUE TITLE
[Regression] "Nth not support on this type: SQLException" when you type in bad sql

### ISSUE THREAD

**Issue by exabrial** [metabase/metabase#9946] opened 2019-05-10 15:20 UTC
> Before filing an issue we'd appreciate it if you could take a moment to ensure there isn't already an open issue or pull-request

_I took a look, I didn't see any, apologies if I missed it_

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Chrome Latest
- Your operating system: (e.x. OS X 10, Windows XP, etc)
OSX Latest
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Percona Mysql 8.0 latests
- Metabase version: (e.x. 0.19.3)
0.32.6, 0.32.4
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Ubuntu 18.04 on Adoptopenjdk8 latest
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
Percona Mysql 8

During an error, Metabase displays the following rather than the database message:
![image](https://user-images.githubusercontent.com/1392297/57537697-774f5380-730c-11e9-9d4e-de5a842b1919.png)

I confirmed on 0.32.6, 0.32.4, (didn't check 0.32.5, 0.32.3), but the problem does not exist on 0.32.2:

![Screen Shot 2019-05-10 at 10 18 53 AM](https://user-images.githubusercontent.com/1392297/57538084-3f94db80-730d-11e9-8704-6daa2b603537.png)

**Comment by flamber** [comment] 2019-05-10 15:31
I think it might be related to #9942

**Comment by exabrial** [comment] 2019-05-10 15:35
Agree, sounds like the same, but he reports it's fine on 0.32.4, and I just checked that version and saw the issue.

**Comment by flamber** [comment] 2019-05-10 15:39
Does it work in any 0.32.x release? Otherwise it might be an issue with the new MariaDB driver in 0.32.x

**Comment by exabrial** [comment] 2019-05-10 15:49
yes, the second screenshot is running on 0.32.2:

![Screen Shot 2019-05-10 at 10 49 22 AM](https://user-images.githubusercontent.com/1392297/57539985-4b829c80-7311-11e9-8df6-20b311ad2b24.png)

**Comment by camsaul** [comment] 2019-05-11 14:48
Duplicate of #9942

**Closed** 2019-05-11 14:48 UTC
