### ISSUE TITLE
zoom breaks UI on multigroup by with time

### ISSUE THREAD

**Issue by camerondavison** [metabase/metabase#11475] opened 2019-12-09 18:27 UTC
**Describe the bug**
Zooming in on a date timeframe while asking a question breaks the UI, and requires a refresh of the page.

**To Reproduce**
1. boot 0.33.6 docker image with example data
2. ask a question of "reviews" summarize by count and "rating: auto binned, by month"
![Screen Shot 2019-12-09 at 12 23 29 PM](https://user-images.githubusercontent.com/165381/70461725-f19cad80-1a7e-11ea-85e3-5a07bf06748d.png)
3. click visualize
4. try and zoom in by some time frame
Error saying field is not aggregated 
![Screen Shot 2019-12-09 at 12 25 46 PM](https://user-images.githubusercontent.com/165381/70461797-13963000-1a7f-11ea-8427-af00c8c50a9b.png)
5. refresh page (everything looks as expected)

**Expected behavior**
Should zoom in correctly, and should not require refreshing the page

**Information about your Metabase Installation:**
```
You're on version v0.33.6
Built on 2019-11-19
```

**Severity**
Annoying

**Comment by mazameli** [comment] 2019-12-09 18:34
I've reproduced this on our stats instance:

![image](https://user-images.githubusercontent.com/2223916/70462202-3fa9b500-1a6f-11ea-9294-c74b5196cde6.png)

The underlying data actually looks correct though:

![image](https://user-images.githubusercontent.com/2223916/70462214-4afce080-1a6f-11ea-97b0-dd2e00a08871.png)

Refreshing the page seems to get the visualization to correctly recognize the updated bins for `Rating`:

![image](https://user-images.githubusercontent.com/2223916/70462266-6667eb80-1a6f-11ea-8c19-0ced33c090c6.png)

But the underlying data hasn't changed after the refresh:

![image](https://user-images.githubusercontent.com/2223916/70462283-71228080-1a6f-11ea-9ef0-1b2c60e4dc9b.png)

**Comment by flamber** [comment] 2020-06-03 18:00
I cannot reproduce on 0.35.4 - think it was fixed in 0.34

**Closed by flamber** 2020-06-03 18:00 UTC
Labels: Priority:P2, Querying/GUI, Type:Bug, Visualization/Charts
