### ISSUE TITLE
SQL stored in version controlled github repo.

### ISSUE THREAD

**Issue by alexkroeger** [metabase/metabase#12194] opened 2020-03-25 17:46 UTC
Is it possible for metabase to link up with a github repo for version controlled SQL?

This would enable collaboration via git and track changes to queries over time. If not possible, this would be an awesome feature.

**Comment by flamber** [comment] 2020-03-27 12:12
Duplicate of #9389 - upvote by clicking :+1: on the first post

**Closed by flamber** 2020-03-27 12:12 UTC
Labels: .Duplicate, Type:New Feature
