### ISSUE TITLE
Custom mappings are broken

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#29347] opened 2023-03-19 19:45 UTC
**Describe the bug**
We seem to have broken custom field remappings in 45. They worked in 44.6 but now 46-RC3 does not display the mappings:
Values are there, the filters simply don't show them
![image](https://user-images.githubusercontent.com/1711649/226204929-b676e4c4-179b-4883-a778-2448603d807d.png)

**Logs**
NA

**To Reproduce**
1) go to settings->data model->orders-> change the data type to category and click on the gear on "quantity" field
2) remap a few quantities to words
3) create a new question with the orders table, add it to a dashboard
4) create a dropdown filter and connect it to quantity field
5) Click on the filter, you won't see the remappings

**Expected behavior**
Remappings should be there

**Screenshots/videos**
Above

**Information about your Metabase Installation:**
- Metabase version: 1.46.0-RC3

**Severity**
P1

**Additional context**
NA

**Comment by qnkhuat** [comment] 2023-03-20 06:38
![Screenshot 2023-03-20 at 13 37 19](https://user-images.githubusercontent.com/25661381/226264877-4e0f39ac-3d98-4baf-9820-c91ed02fce74.png)
BE is returning the remapped values, so essentially this is a FE bug.

also we should add e2e tests for this while fixing it.

**Comment by ranquild** [comment] 2023-03-20 13:33
The root cause is that the backend doesn't return `param_values` in the response for fields used in parameters in the dashboard in `GET /api/dashboard/:id`. It used to do it in 0.43 and it worked correctly. 
<img width="646" alt="Screenshot 2023-03-20 at 14 32 43" src="https://user-images.githubusercontent.com/8542534/226355422-8c805d27-4a9f-49a4-a334-a3abb8cb478c.png">

**Comment by qnkhuat** [comment] 2023-03-20 14:35
Related bug for embedding and public dashboard: https://github.com/metabase/metabase/issues/29346. Probably the same cause.

**Comment by dpsutton** [comment] 2023-03-20 15:22
@ranquild I'm not sure I follow. Do we have to enumerate all values for dropdowns when sending over dashboard information?

**Comment by qnkhuat** [comment] 2023-03-20 15:24
@dpsutton yes. slack [thread](https://metaboat.slack.com/archives/C04DAKFDTCZ/p1679319123616409?thread_ts=1679312270.315959&cid=C04DAKFDTCZ)

**Comment by paoliniluis** [comment] 2023-05-29 16:08
Just tested and the issue is still there. Filters show the original values

**Comment by qnkhuat** [comment] 2023-05-30 03:05
@paoliniluis I just tested on both master and release 46 and it works. could you try again?

**Comment by paoliniluis** [comment] 2023-05-30 17:39
@qnkhuat I just tested 46.4:
did a remap of "rating" in the review table, this is the filter values in the question:
![image](https://github.com/metabase/metabase/assets/1711649/f167d3d4-e04c-43ba-9d16-2d6c1c0e4dda)

this is what appears in the dashboard:
(does not appear as a category):
![image](https://github.com/metabase/metabase/assets/1711649/9ba34a47-f98f-46ea-bfba-d7791080db7c)

it will appear only as a number:
![image](https://github.com/metabase/metabase/assets/1711649/7cbbe46e-fb6e-4c75-a16e-2b772caca62e)
![image](https://github.com/metabase/metabase/assets/1711649/d6a571aa-6dee-4469-bd2d-17c669c08ac5)

**Comment by paoliniluis** [comment] 2023-05-30 18:07
wait wait wait... seems like something happened after some time and it's now working, maybe a refresh? maybe some async process in the dB?

**Comment by qnkhuat** [comment] 2023-05-31 02:42
it shouldn't be  :/ there is no syncing I believe, but if you find it recurring let's create an issue for that. 

otoh, can we close this now?

**Closed** 2023-05-31 08:56 UTC
Labels: Type:Bug, Priority:P1, Querying/Parameters & Variables, Administration/Data Model, .Backend, .Reproduced, .Regression, .Team/42 :milky_way:
