### ISSUE TITLE
Bar color plot following table conditional formatting

### ISSUE THREAD

**Issue by viniciusparede** [metabase/metabase#21303] opened 2022-03-28 22:54 UTC
**Is your feature request related to a problem? Please describe.**
When I open the conditional formatting option on a specific table and add a coloring rule to the table the bar chart does not follow the created template.
![image](https://user-images.githubusercontent.com/37218996/160499510-9b43fa16-ba93-4269-b114-27c2f0fc6b1f.png)
![image](https://user-images.githubusercontent.com/37218996/160499595-b1aad937-7272-4ceb-92c9-ab3c048ef04a.png)

**Describe the solution you'd like**
It would be great if the bar chart followed the same color condition in the created rules.

Like that:
![image](https://user-images.githubusercontent.com/37218996/160500066-904bfd2d-bcd1-4f9b-9c9d-7cac895bb92a.png)

**How important is this feature to you?**
Not relevant.

**Comment by flamber** [comment] 2022-03-29 08:11
Duplicate of #11461

**Closed by flamber** 2022-03-29 08:11 UTC
Labels: Type:New Feature, .Needs Triage
