### ISSUE TITLE
Binning Double Counting

### ISSUE THREAD

**Issue by flarco** [metabase/metabase#24906] opened 2022-08-19 19:17 UTC
**Describe the bug**
We've verified that Metabase can double count rows in bins when the value falls exactly at the bound, when clicking on the bars to view the records.

**To Reproduce**
1. Bin an integer column with values at the bound of the bin and visualize with bars
2. Click on the bar, and click on `View These ...`
3. The number of returned rows should are different than what was shown in the bar.

**Expected behavior**
When clicking `View These ...`, it should be the same number of records

**Screenshots**
We see below that the chart bin is correct, with the 2 records.
<img src="https://user-images.githubusercontent.com/7671010/185690268-9faf4f50-7d39-47db-93e4-8e206ac6e985.png" width="250">

But when I click the bar, and click `View These ...`, I get 3 records
<img src="https://user-images.githubusercontent.com/7671010/185690116-ad32c9d5-6719-4b19-a1c8-bd9a6042503c.png" width="250">

**Additional context**
When graphing with the bars, it uses the bucketing/filtering logic: `GROUP BY ((floor((({my_column} - 0.0) / 5)) * 5) + 0.0)`
When viewing records via tabular, it uses the filtering logic: `{my_column} BETWEEN 0 AND 5` which is *inclusive*. 
Should use `{my_column} >= 0 AND {my_column} < 5` instead. In my case, we are querying Postgres.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8",
    "os.name": "Linux",
    "os.version": "5.4.196-108.356.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-07-29",
      "tag": "v1.43.4.2",
      "branch": "release-x.43.x",
      "hash": "7809f82"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2022-08-19 19:30
Duplicate of #15324

**Closed by flamber** 2022-08-19 19:30 UTC
