### ISSUE TITLE
Sign in with Google with several domains support

### ISSUE THREAD

**Issue by luosprz** [metabase/metabase#11300] opened 2019-11-12 16:06 UTC
I was trying to configure my own Metabase enabling the option for Authentication with Google Sign-in.

Could be possible to support it with more than one domain name? 

Now it is only possible to filter by one domain name in:
```Allow users to sign up on their own if their Google account email address is from:```

Thanks

**Comment by flamber** [comment] 2019-11-12 16:52
Hi @luosprz 
Sounds like a duplicate of #5218 - if you agree, then please close this and upvote the other issue.

**Closed** 2019-11-12 17:14 UTC
Labels: .Needs Triage, Type:New Feature
