### ISSUE TITLE
Druid cannot sort columns

### ISSUE THREAD

**Issue by xqwbx163** [metabase/metabase#9273] opened 2019-01-16 07:06 UTC
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (Chrome 70)
- Your operating system: ( Windows 10)
- Your databases: (druid)
- Metabase version: (0.31.2)
- Metabase hosting environment: (windows 10)
- Metabase internal database: (H2 (default))

issue:
![image](https://user-images.githubusercontent.com/20455410/51231900-09b79a00-19a0-11e9-87b9-547e98d1285a.png)

when i load druid table ,and list the table result.

The column and the corresponding field value do not match, there is a wrong line, the A field corresponds to the value of B, and the B field corresponds to the value of C.
And timestamp not the correct value .

Could you help me ?

**Comment by xqwbx163** [comment] 2019-01-16 07:10
add one:
why druid column can not sort by Ascending or Descending ?

**Comment by salsakran** [comment] 2019-01-22 15:35
can you share the raw response back from the api? (open network inspector and there should be an api call to "dataset_query").

**Comment by flamber** [comment] 2019-01-22 20:56
Would this be fixed by #9304 ? At least the column match - not sure if the sorting is a different issue.

**Comment by lostduck** [comment] 2019-02-28 12:09
![image](https://user-images.githubusercontent.com/21040254/53565461-298bd180-3b8c-11e9-97ac-215975bc07b8.png)
the data and the column not match, any idea to solve it? or it has been fixed?

**Comment by flamber** [comment] 2019-02-28 17:13
@lostduck 
By default, Metabase orders columns in alphabetical order (except the Entity Key). You can change the column order by clicking the :gear: icon:
https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html#tables

**Comment by lostduck** [comment] 2019-03-01 03:01
@flamber yeah i know about the Metabase orders, but i mean the value and the name of column is not match, this condition seem like the @xqwbx163 's report, any idea to solve it?

**Comment by flamber** [comment] 2019-03-01 03:06
@lostduck Okay, if you try the current nightly (either docker head or build from master), then you can test if #9343 fixed your issue.

**Comment by salsakran** [comment] 2019-06-05 01:23
bumping priority since it's been reported again

**Comment by uladzimirdev** [comment] 2023-10-20 12:54
If I understood the problem correctly, sorting of the columns was broken if you have a timestamp column in the table.

https://www.loom.com/share/50c2b17ad63946d1922032b89c7820cd

Indeed in the version 0.33.0 it was broken and in the version 0.33.7.3 it seems was addressed already as with the same parameters sorting works well.

probably https://github.com/metabase/metabase/pull/9343 could fix the issue. Fill free to create a new issue if the problem still exists at some configuration

**Closed by uladzimirdev** 2023-10-20 12:54 UTC
Labels: Type:Bug, Priority:P2, .Limitation, Database/Druid, Querying/GUI, .Team/42, .FixMBQLScope42

**Comment by uladzimirdev** [comment] 2023-10-20 12:59
@xqwbx163 if there is a chance you're still working with metabase, could you please verify if the issue is fixed in the more recent versions?
