### ISSUE TITLE
Allow downloading results before output on interface

### ISSUE THREAD

**Issue by rafaelveloso** [metabase/metabase#9358] opened 2019-01-31 19:35 UTC
When running heavy and slow questions, I would find it extremely helpful to be able to immediately download results export on the first query run. As it is now, we have to first run the query and only then the button to download will show - this will make the user wait twice the time to download.

**Comment by flamber** [comment] 2019-02-14 18:31
Duplicate of #4820

**Closed** 2019-02-14 18:37 UTC
