### ISSUE TITLE
Wonkiness when editing column name in Admin > Data Model

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#20143] opened 2022-02-01 22:58 UTC
It rerenders the screen several times with both the old text and new text while you are in the process of typing:

![bye](https://user-images.githubusercontent.com/1455846/152065597-a9f92dc3-9b1d-4e35-956a-d8c481550df1.gif)

**Comment by flamber** [comment] 2022-02-02 09:29
Duplicate of #10462

**Closed by flamber** 2022-02-02 09:29 UTC
Labels: Type:Bug, .Needs Triage
