### ISSUE TITLE
America/Los_Angeles not recognized as a valid timezone

### ISSUE THREAD

**Issue by cwilby** [metabase/metabase#16564] opened 2021-06-13 18:45 UTC
**Describe the bug**
I have configured my local timezone in Admin > Settings > Localization to be "America/Los_Angeles"

Expected:  Dates show in the local timezone
Actual:  Dates show in the database timezone

**Logs**
```
metabase-app_1  | 2021-06-13 18:35:39,010 ERROR sql-jdbc.execute :: Failed to set timezone 'America/Los_Angeles' for :mysql database
metabase-app_1  | java.sql.SQLTransientConnectionException: (conn=3118513) Unknown or incorrect time zone: 'America/Los_Angeles'
metabase-app_1  | 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:79)
metabase-app_1  | 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
metabase-app_1  | 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274)
metabase-app_1  | 	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:363)
metabase-app_1  | 	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:501)
metabase-app_1  | 	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
metabase-app_1  | 	at metabase.driver.sql_jdbc.execute$set_time_zone_if_supported_BANG_.invokeStatic(execute.clj:151)
metabase-app_1  | 	at metabase.driver.sql_jdbc.execute$set_time_zone_if_supported_BANG_.invoke(execute.clj:136)
metabase-app_1  | 	at metabase.driver.sql_jdbc.execute$fn__79472.invokeStatic(execute.clj:183)
metabase-app_1  | 	at metabase.driver.sql_jdbc.execute$fn__79472.invoke(execute.clj:178)
metabase-app_1  | 	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
metabase-app_1  | 	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:465)
metabase-app_1  | 	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:453)
metabase-app_1  | 	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:462)
metabase-app_1  | 	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:453)
metabase-app_1  | 	at metabase.driver.sql_jdbc$fn__81184.invokeStatic(sql_jdbc.clj:54)
metabase-app_1  | 	at metabase.driver.sql_jdbc$fn__81184.invoke(sql_jdbc.clj:52)
metabase-app_1  | 	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
metabase-app_1  | 	at metabase.query_processor.context$executef.invokeStatic(context.clj:59)
metabase-app_1  | 	at metabase.query_processor.context$executef.invoke(context.clj:48)
metabase-app_1  | 	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:68)
metabase-app_1  | 	at metabase.query_processor.context.default$default_runf.invoke(default.clj:66)
metabase-app_1  | 	at metabase.query_processor.context$runf.invokeStatic(context.clj:45)
metabase-app_1  | 	at metabase.query_processor.context$runf.invoke(context.clj:39)
metabase-app_1  | 	at metabase.query_processor.reducible$pivot.invokeStatic(reducible.clj:34)
metabase-app_1  | 	at metabase.query_processor.reducible$pivot.invoke(reducible.clj:31)
metabase-app_1  | 	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47511.invoke(mbql_to_native.clj:25)
metabase-app_1  | 	at metabase.query_processor.middleware.check_features$check_features$fn__46625.invoke(check_features.clj:39)
metabase-app_1  | 	at metabase.query_processor.middleware.limit$limit$fn__47497.invoke(limit.clj:37)
metabase-app_1  | 	at metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__46077.invoke(cache.clj:211)
metabase-app_1  | 	at metabase.query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__47757.invoke(optimize_temporal_filters.clj:204)
metabase-app_1  | 	at metabase.query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__49687.invoke(validate_temporal_bucketing.clj:50)
metabase-app_1  | 	at metabase.query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__45196.invoke(auto_parse_filter_values.clj:43)
metabase-app_1  | 	at metabase.query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__41497.invoke(wrap_value_literals.clj:161)
metabase-app_1  | 	at metabase.query_processor.middleware.annotate$add_column_info$fn__41372.invoke(annotate.clj:605)
metabase-app_1  | 	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__46497.invoke(permissions.clj:81)
metabase-app_1  | 	at metabase.query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__48615.invoke(pre_alias_aggregations.clj:40)
metabase-app_1  | 	at metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46698.invoke(cumulative_aggregations.clj:60)
metabase-app_1  | 	at metabase.query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__48914.invoke(resolve_joined_fields.clj:102)
metabase-app_1  | 	at metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__49227.invoke(resolve_joins.clj:171)
metabase-app_1  | 	at metabase.query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44772.invoke(add_implicit_joins.clj:190)
metabase-app_1  | 	at metabase.query_processor.middleware.large_int_id$convert_id_to_string$fn__47461.invoke(large_int_id.clj:59)
metabase-app_1  | 	at metabase.query_processor.middleware.format_rows$format_rows$fn__47442.invoke(format_rows.clj:74)
metabase-app_1  | 	at metabase.query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__44066.invoke(add_default_temporal_unit.clj:23)
metabase-app_1  | 	at metabase.query_processor.middleware.desugar$desugar$fn__46764.invoke(desugar.clj:21)
metabase-app_1  | 	at metabase.query_processor.middleware.binning$update_binning_strategy$fn__45583.invoke(binning.clj:227)
metabase-app_1  | 	at metabase.query_processor.middleware.resolve_fields$resolve_fields$fn__46300.invoke(resolve_fields.clj:34)
metabase-app_1  | 	at metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__44421.invoke(add_dimension_projections.clj:314)
metabase-app_1  | 	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__44650.invoke(add_implicit_clauses.clj:147)
metabase-app_1  | 	at metabase.query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__49636.invoke(upgrade_field_literals.clj:40)
metabase-app_1  | 	at metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44935.invoke(add_source_metadata.clj:123)
metabase-app_1  | 	at metabase.query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__48789.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)
metabase-app_1  | 	at metabase.query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45143.invoke(auto_bucket_datetimes.clj:147)
metabase-app_1  | 	at metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46347.invoke(resolve_source_table.clj:45)
metabase-app_1  | 	at metabase.query_processor.middleware.parameters$substitute_parameters$fn__48597.invoke(parameters.clj:111)
metabase-app_1  | 	at metabase.query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46399.invoke(resolve_referenced.clj:79)
metabase-app_1  | 	at metabase.query_processor.middleware.expand_macros$expand_macros$fn__47148.invoke(expand_macros.clj:184)
metabase-app_1  | 	at metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__44944.invoke(add_timezone_info.clj:15)
metabase-app_1  | 	at metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49589.invoke(splice_params_in_response.clj:32)
metabase-app_1  | 	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48800$fn__48804.invoke(resolve_database_and_driver.clj:31)
metabase-app_1  | 	at metabase.driver$do_with_driver.invokeStatic(driver.clj:60)
metabase-app_1  | 	at metabase.driver$do_with_driver.invoke(driver.clj:56)
metabase-app_1  | 	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48800.invoke(resolve_database_and_driver.clj:25)
metabase-app_1  | 	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47388.invoke(fetch_source_query.clj:274)
metabase-app_1  | 	at metabase.query_processor.middleware.store$initialize_store$fn__49598$fn__49599.invoke(store.clj:11)
metabase-app_1  | 	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:44)
metabase-app_1  | 	at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
metabase-app_1  | 	at metabase.query_processor.middleware.store$initialize_store$fn__49598.invoke(store.clj:10)
metabase-app_1  | 	at metabase.query_processor.middleware.validate$validate_query$fn__49643.invoke(validate.clj:10)
metabase-app_1  | 	at metabase.query_processor.middleware.normalize_query$normalize$fn__47524.invoke(normalize_query.clj:22)
metabase-app_1  | 	at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44790.invoke(add_rows_truncated.clj:35)
metabase-app_1  | 	at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49574.invoke(results_metadata.clj:147)
metabase-app_1  | 	at metabase.query_processor.middleware.constraints$add_default_userland_constraints$fn__46641.invoke(constraints.clj:42)
metabase-app_1  | 	at metabase.query_processor.middleware.process_userland_query$process_userland_query$fn__48686.invoke(process_userland_query.clj:135)
metabase-app_1  | 	at metabase.query_processor.middleware.catch_exceptions$catch_exceptions$fn__46581.invoke(catch_exceptions.clj:173)
metabase-app_1  | 	at metabase.query_processor.reducible$async_qp$qp_STAR___38051$thunk__38052.invoke(reducible.clj:103)
metabase-app_1  | 	at metabase.query_processor.reducible$async_qp$qp_STAR___38051.invoke(reducible.clj:109)
metabase-app_1  | 	at metabase.query_processor.reducible$sync_qp$qp_STAR___38060$fn__38063.invoke(reducible.clj:135)
metabase-app_1  | 	at metabase.query_processor.reducible$sync_qp$qp_STAR___38060.invoke(reducible.clj:134)
metabase-app_1  | 	at clojure.lang.AFn.applyToHelper(AFn.java:156)
metabase-app_1  | 	at clojure.lang.AFn.applyTo(AFn.java:144)
metabase-app_1  | 	at clojure.core$apply.invokeStatic(core.clj:667)
metabase-app_1  | 	at clojure.core$apply.invoke(core.clj:660)
metabase-app_1  | 	at metabase.query_processor$process_userland_query.invokeStatic(query_processor.clj:241)
metabase-app_1  | 	at metabase.query_processor$process_userland_query.doInvoke(query_processor.clj:237)
metabase-app_1  | 	at clojure.lang.RestFn.invoke(RestFn.java:423)
metabase-app_1  | 	at metabase.query_processor$fn__49733$process_query_and_save_execution_BANG___49742$fn__49745.invoke(query_processor.clj:253)
metabase-app_1  | 	at metabase.query_processor$fn__49733$process_query_and_save_execution_BANG___49742.invoke(query_processor.clj:245)
metabase-app_1  | 	at metabase.query_processor$fn__49777$process_query_and_save_with_max_results_constraints_BANG___49786$fn__49789.invoke(query_processor.clj:265)
metabase-app_1  | 	at metabase.query_processor$fn__49777$process_query_and_save_with_max_results_constraints_BANG___49786.invoke(query_processor.clj:258)
metabase-app_1  | 	at metabase.api.dataset$run_query_async$fn__55990.invoke(dataset.clj:56)
metabase-app_1  | 	at metabase.query_processor.streaming$streaming_response_STAR_$fn__55969$fn__55970.invoke(streaming.clj:72)
metabase-app_1  | 	at metabase.query_processor.streaming$streaming_response_STAR_$fn__55969.invoke(streaming.clj:71)
metabase-app_1  | 	at metabase.async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)
metabase-app_1  | 	at metabase.async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)
metabase-app_1  | 	at metabase.async.streaming_response$do_f_async$fn__16071.invoke(streaming_response.clj:84)
metabase-app_1  | 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
metabase-app_1  | 	at clojure.lang.AFn.applyTo(AFn.java:144)
metabase-app_1  | 	at clojure.core$apply.invokeStatic(core.clj:665)
metabase-app_1  | 	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
metabase-app_1  | 	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
metabase-app_1  | 	at clojure.lang.RestFn.invoke(RestFn.java:425)
metabase-app_1  | 	at clojure.lang.AFn.applyToHelper(AFn.java:156)
metabase-app_1  | 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
metabase-app_1  | 	at clojure.core$apply.invokeStatic(core.clj:669)
metabase-app_1  | 	at clojure.core$bound_fn_STAR_$fn__5749.doInvoke(core.clj:2003)
metabase-app_1  | 	at clojure.lang.RestFn.invoke(RestFn.java:397)
metabase-app_1  | 	at clojure.lang.AFn.run(AFn.java:22)
metabase-app_1  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
metabase-app_1  | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
metabase-app_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
metabase-app_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
metabase-app_1  | 	at java.base/java.lang.Thread.run(Unknown Source)
metabase-app_1  | Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Unknown or incorrect time zone: 'America/Los_Angeles'
metabase-app_1  | 	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
metabase-app_1  | 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194)
metabase-app_1  | 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:262)
metabase-app_1  | 	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:357)
metabase-app_1  | 	... 109 more
metabase-app_1  | Caused by: java.sql.SQLException: Unknown or incorrect time zone: 'America/Los_Angeles'
metabase-app_1  | 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1688)
metabase-app_1  | 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1550)
metabase-app_1  | 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1513)
metabase-app_1  | 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:256)
metabase-app_1  | 	... 110 more
```

**To Reproduce**
1.  Configure a new Metabase instance in Docker with an example database
2. Set the dropdown in Settings > Admin > Localization > Timezone to "America/Los_Angeles"
3. Open metabase logs `docker-compose logs -f`

**Expected behavior**
Dates should appear in the local timezone and the exception should not appear in the logs.

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "5.4.0-1048-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.7 (Debian 12.7-1.pgdg100+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-27",
      "tag": "v0.39.3",
      "branch": "release-x.39.x",
      "hash": "598a112"
    },
    "settings": {
      "report-timezone": "America/Los_Angeles"
    }
  }
}
```
**Severity**
It's not critical, but it would be nice to see dates in local timezones - it isn't causing confusion now as it's just a couple of people in one timezone.  I'd rate it "Please, may I have a bug fix?" out of "We've declared bankruptcy due to technical issues".

**Additional context**
None

**Comment by flamber** [comment] 2021-06-13 18:52
Hi @cwilby 
Metabase gets the timezones available from Java, but you are having problems with MySQL, which is likely caused by your MySQL either doesn't have `tzinfo` (it does not have this by default for some reason) or it's not up-to-date.
https://dev.mysql.com/doc/refman/8.0/en/mysql-tzinfo-to-sql.html
Closing in favor of #10365

**Closed by flamber** 2021-06-13 18:52 UTC
Labels: .Needs Triage, Type:Bug

**Comment by cwilby** [comment] 2021-06-13 19:46
Thanks @flamber 👍
