### ISSUE TITLE
Deploy with AWS ElasticBeanstalk failed on verion v0.40 above in regions not support AWS inspect (like cn-north-1 or ap-southeast-1)

### ISSUE THREAD

**Issue by yexingok** [metabase/metabase#17249] opened 2021-07-29 10:36 UTC
**Describe the bug**
When deploy Metabase version 0.40.1 with ElasticBenastalk quicklaunch from: https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html to regions not support AWS inspect, the deploy process will fail

Example regions not support AWS inspect:

* Singapore (ap-southeast-1)
* China region (cn-north-1)

Affect version is from Metabase version >= 0.40 (after PR (https://github.com/metabase/metabase/pull/14718 ))
No matter you update from a previous version to this version,
Or do a new installation, you will run into this bug.

**Logs**
Please found in reproduce sections

**To Reproduce**

Steps to reproduce the behaviour:

1. Deploy with Elastic Beanstalk with quick start guide to ap-southeast-1 or cn-north-1, when do deploy, enable push logs to cloudwatch, otherwise you can not see debug log,
2. From cloudwatch log group: /aws/elasticbeanstalk/{your-env-name}/var/log/eb-engine.log ; search for "error":

```
An error occurred during execution of command [app-deploy] - [PostBuildEbExtension]. Stop running the command. Error: Container commands build failed. Please refer to /var/log/cfn-init.log for more details. 
```

From cfn-init.log you can find:

```
2021-07-29 08:24:01,409 [ERROR] Command 06-install_inspector (bash -x install -u false) failed2021-07-29 08:24:01,410 [ERROR] Error encountered during build of postbuild_0_test_metabase: Command 06-install_inspector failed
Traceback (most recent call last):
```

you will see an error message in ElasticBeanstalk interface about deploy failed; 

It is likely caused by adding the aws inspector logic in this PR (https://github.com/metabase/metabase/pull/14718 )

The issue is likely caused by the code below in  the .ebextensions\01_metabase.config:

```
06-install_inspector:
        command: bash -x install -u false
        cwd: /tmp/
```

Which required the step to finish in the deploy progress, but it failed when launch to a region not support AWS inspect, 

It seems this bug will prevent users to deploy to regions **outside** the below region:

```
us-east-1 us-west-1 us-west-2 ap-northeast-1 eu-west-1 eu-west-2 ap-northeast-2 ap-southeast-2 ap-south-1 eu-central-1 eu-north-1 us-east-2 us-gov-west-1 us-gov-east-1
```

**Expected behavior**
Run through Metabase install without error. 

**Screenshots**
Will post later.

**Information about your Metabase Installation:**

Metabase version >= v0.40 (after the PR https://github.com/metabase/metabase/pull/14718)

**Severity**
This bug will block users to launch Metabase install, if the users are not in below AWS regions:

```
us-east-1 us-west-1 us-west-2 ap-northeast-1 eu-west-1 eu-west-2 ap-northeast-2 ap-southeast-2 ap-south-1 eu-central-1 eu-north-1 us-east-2 us-gov-west-1 us-gov-east-1
```

**To mitigate before patch ready**

To share with anyone whom may run into the issue, I am able to mitigate the issue by do the following:

1. Revert the changes manually in 01_metabase.config to previous version. (ie: 0.39.4).  
2. Re-deploy, Metabase launch succ.

Please let me know if you need any info, thanks.

**Comment by flamber** [comment] 2021-07-29 10:39
Duplicate of #17143

**Closed by flamber** 2021-07-29 10:39 UTC
Labels: .Needs Triage, Type:Bug
