### ISSUE TITLE
Languages mixed into a filter of a dashboard

### ISSUE THREAD

**Issue by Pierre-PSUD** [metabase/metabase#38112] opened 2024-01-24 21:12 UTC
### Describe the bug

My metabase version is in french.
When I want to apply a filter on a dashboard like : "All the stuffs *of the previous year*", it appears ```Previous année``` (```Année``` being the french word for ```year```).
It could be perfect to have ```Année précédente``` instead.

### To Reproduce

1. Configure your metabase in french version
2. Go to a dashboard with a filter which have a 'date' type
3. Click on it and filter to have all the result whose date is part of the ```Previous year```
4. ```Previous Année``` is written

### Expected behavior

Année précédente

### Logs

No response

### Information about your Metabase installation

French version of Metabase

### Severity

P3

### Additional context

No response

**Comment by paoliniluis** [comment] 2024-02-27 01:36
this happens in all languages

**Comment by paoliniluis** [comment] 2024-02-27 01:37
https://github.com/metabase/metabase/issues/24624

**Comment by ranquild** [comment] 2024-07-18 23:13
Duplicate of https://github.com/metabase/metabase/issues/24624

**Closed by ranquild** 2024-07-18 23:13 UTC
Labels: Type:Bug, Priority:P3, Querying/Parameters & Variables, Customization/i18n, .Completeness, .Frontend, .Team/QueryingComponents
