### ISSUE TITLE
Json operator `?` incorrectly escaped

### ISSUE THREAD

**Issue by whisust** [metabase/metabase#15453] opened 2021-04-02 09:28 UTC
**Describe the bug**
```sql
SELECT '{"a": 1}'::JSONB ? 'a'
``` 

should return `true`, instead it raises an error `No value specified for parameter 1.`

This should be due to an incorrect parsing and string being directly sent as is to the JDBC Driver, interpreting the `?` as an argument parameter.

I am using metabase self hosted v0.38.3

**Screenshots**
<img width="1569" alt="Screenshot 2021-04-02 at 11 20 00" src="https://user-images.githubusercontent.com/22323709/113403208-90e96080-93a6-11eb-9153-160c42ba2106.png">

**Comment by flamber** [comment] 2021-04-02 10:46
Duplicate of #10257

**Closed by flamber** 2021-04-02 10:46 UTC
Labels: .Needs Triage, Type:Bug
