### ISSUE TITLE
Google Sign-in migration

### ISSUE THREAD

**Issue by zxpower** [metabase/metabase#17465] opened 2021-08-16 05:33 UTC
Recently Google upgraded their Google Sign-In Javascript library and the old way (used by Metabase) is deprecated and will not be supported after March 31, 2023.

By this time it's necessary to upgrade the way Metabase uses Google Sign-in according to this [document](https://developers.google.com/identity/gsi/web/guides/migration) from Google.

**Comment by flamber** [comment] 2021-08-16 08:17
Duplicate of #17429

**Closed by flamber** 2021-08-16 08:17 UTC
Labels: Type:Bug, .Needs Triage
