### ISSUE TITLE
Confirmation modal when removing a card or a text card says "Remove this card?"

### ISSUE THREAD

**Issue by MatheusBeniniF** [metabase/metabase#24304] opened 2022-07-26 12:15 UTC
**Describe the bug**
there are two types of cards, so 2 types of titles are needed.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Create new dashboard
2. Add a text card and a question
3. Click to delete both cards
4. See it's the same message

**Expected behavior**

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.g., Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.g., OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.g, MySQL, Postgres, MongoDB, …)
- Metabase version: (e.g., 0.19.3)
- Metabase hosting environment: (e.g., Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.g., H2 (default), Postgres or MySQL)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by flamber** [comment] 2022-07-26 12:28
Hi @MatheusBeniniF 
Both questions and textboxes are cards on the dashboard. Duplicate of #23841

**Closed by flamber** 2022-07-26 12:28 UTC
Labels: Type:Bug, .Needs Triage
