### ISSUE TITLE
Please add box plot in chart type. It is very useful for distribution visualization.

### ISSUE THREAD

**Issue by yunjiaxu** [metabase/metabase#12054] opened 2020-03-05 00:39 UTC
Please use the issue chooser, when creating a new issue:

https://github.com/metabase/metabase/issues/new/choose

**Comment by flamber** [comment] 2020-03-05 18:25
Duplicate of #10783

**Closed by flamber** 2020-03-05 18:25 UTC

**Comment by albertocasash** [comment] 2020-08-05 13:37
yes, i agreed, we need a boxpplot on Metabase.
