### ISSUE TITLE
X Days Ago Time Filter

### ISSUE THREAD

**Issue by jbrooksuk** [metabase/metabase#7336] opened 2018-04-12 13:16 UTC
I may have missed a trick here, but I need to generate reports for `x days ago`, not after or before x days, but I need to look at exactly 4 days from today.

Without writing this as an SQL query, is this achievable?

**Comment by petar777** [comment] 2018-04-16 11:41
I think you can only do it with an SQL query:

`SELECT *`
`FROM sampe_table`
`WHERE cast(sample_date as date) = cast(now()1 + interval '-5 days' as date)`

**Comment by jbrooksuk** [comment] 2018-04-16 19:49
You can, but it feels like it should be something Metabase supports as part of the question builder.

**Comment by flamber** [comment] 2019-02-19 04:42
Hi @jbrooksuk 
Sounds like you're looking for what is described in #4083 - go and upvote by clicking the :+1:

**Comment by jbrooksuk** [comment] 2019-02-19 08:49
Done!

**Comment by mazameli** [comment] 2019-10-11 00:04
Closing as duplicate of #4083

**Closed by mazameli** 2019-10-11 00:04 UTC
Labels: .Duplicate, .Proposal, Query Builder
