### ISSUE TITLE
Comments not working on SQL native query

### ISSUE THREAD

**Issue by AndreLuizRego** [metabase/metabase#11787] opened 2020-01-23 20:39 UTC
Using "#" to comment a line returns error on a query. See images attached.
![Screen02](https://user-images.githubusercontent.com/56892990/73021670-c095f380-3e06-11ea-90cc-a0f0fb39388c.PNG)
![Screen01](https://user-images.githubusercontent.com/56892990/73021671-c095f380-3e06-11ea-88be-c56b544b38cf.PNG)

Metabase 0.33.4
MYSQL Database
Chrome 79.0.3945.117 (64 bits)

**Comment by mazameli** [comment] 2020-01-23 21:30
Hmm, I was unable to reproduce this in 0.34.1 using a MySQL DB; see screenshot. Are you able to reproduce this error with a simpler query? Does this happen for you on version 0.34?

![image](https://user-images.githubusercontent.com/2223916/73025389-5d936500-3de4-11ea-8b4b-464fb51313d9.png)

**Comment by AndreLuizRego** [comment] 2020-01-24 11:27
Hello Maz Ameli,

I made a simple query similar to the one you wrote and the error did not happen. I also noted another odd behavior (please see attached pictures): When I added a coment line just before a group statement the result changed from a previous 95 records to 1 record.

Regards,

                   André Rêgo
![Screen_Comment](https://user-images.githubusercontent.com/56892990/73065779-2aec7980-3e83-11ea-93ca-914f64799f0f.PNG)
![Screen_No_Comment](https://user-images.githubusercontent.com/56892990/73065780-2aec7980-3e83-11ea-932f-3190ef2e84fa.PNG)

**Comment by flamber** [comment] 2020-02-05 17:18
Are you seeing the same problem on 0.34.1?
Are you using Windows? Which browser are you using?
I have a feeling this has something to do with newline endings - Windows uses CR+LF (Return Newline) and all other systems just uses LF (Newline). The editor was updated in 0.34.0, so perhaps that could have fixed your problem.
Also, check the Admin > Troubleshooting > Logs for a more detailed error message. You might also see the full error (and query) on your MySQL if you have enabled error logging there.

**Comment by AndreLuizRego** [comment] 2020-02-06 15:25
Hello!

Here is the log:


#metabase.models.user.UserInstance{:id 6, :password_salt 08243dba-b14b-43de-9ff7-5c70cd49076d, :password $2a$10$zskjwAfMRfl4vdbknzJBpuIkHqoPGAu1ceTpBTWgv2YzVWCMMH/sC, :last_login #inst "2020-02-06T13:56:48.000000000-00:00"}
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:05:12-03:00 DEBUG metabase.middleware.log POST /api/session 200 5,0 ms (2 DB calls) Jetty threads: 3/50 (3 idle, 0 queued) (97 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:05:12-03:00 DEBUG metabase.middleware.log GET /api/setting 200 466,2 µs (0 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (97 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:05:12-03:00 DEBUG metabase.middleware.log GET /api/user/current 200 1,9 ms (3 DB calls) Jetty threads: 3/50 (3 idle, 0 queued) (97 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:05:12-03:00 DEBUG metabase.middleware.log GET /api/collection/root/items 200 6,3 ms (7 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (97 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:05:12-03:00 DEBUG metabase.middleware.log GET /api/collection/root 200 1,7 ms (2 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (97 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:05:15-03:00 DEBUG metabase.middleware.log GET /api/database/4/schemas 200 3,0 ms (4 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (97 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:05:15-03:00 DEBUG metabase.middleware.log GET /api/database/4/metadata 200 37,3 ms (7 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (97 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:05:19-03:00 DEBUG metabase.middleware.log GET /api/database 200 27,1 ms (5 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (97 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:05:19-03:00 DEBUG metabase.middleware.log GET /api/table/178/query_metadata 200 6,6 ms (8 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (97 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:05:19-03:00 DEBUG metabase.middleware.log GET /api/table/178/fks 200 8,9 ms (5 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (97 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:05:19-03:00 DEBUG metabase.middleware.log POST /api/dataset 200 [ASYNC: completed] 29,4 ms (15 DB calls) Jetty threads: 2/50 (4 idle, 0 queued) (97 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:19:06-03:00 DEBUG metabase.middleware.log GET /api/user/current 200 2,1 ms (3 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (94 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:19:06-03:00 DEBUG metabase.middleware.log GET /api/session/properties 200 2,2 ms (1 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:19:06-03:00 DEBUG metabase.middleware.log GET /api/database 200 6,7 ms (4 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:19:06-03:00 INFO metabase.api.session 3@metabase.wefor.com.br
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:19:06-03:00 INFO metabase.api.session 6abe296abe61771dcd221f62d42b08d6
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:19:06-03:00 INFO metabase.api.session calc-hash => string-param: 3@metabase.wefor.com.br
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:19:06-03:00 INFO metabase.api.session calculated-token:
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:19:06-03:00 INFO metabase.api.session token-login
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:19:06-03:00 INFO metabase.api.session Create session: user=> #metabase.models.user.UserInstance{:id 8, :password_salt 6e42eeef-d244-4134-8560-a01d0ee79167, :password $2a$10$hurDUVngfZXBLSs4YQTKf.K6GtsX3Vda/AAKXeryKlYK5fbvTPgBy, :last_login #inst "2020-02-06T14:14:36.000000000-00:00"}
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:19:06-03:00 DEBUG metabase.middleware.log POST /api/session 200 7,3 ms (2 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:19:06-03:00 DEBUG metabase.middleware.log GET /api/setting 200 424,3 µs (0 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:19:06-03:00 DEBUG metabase.middleware.log GET /api/user/current 200 1,8 ms (3 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:19:06-03:00 DEBUG metabase.middleware.log GET /api/collection/root/items 200 6,2 ms (7 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:19:06-03:00 DEBUG metabase.middleware.log GET /api/collection/root 200 1,8 ms (2 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:19:10-03:00 DEBUG metabase.middleware.log GET /api/collection/root 200 1,7 ms (2 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:20:37-03:00 DEBUG metabase.middleware.log GET /api/database 200 30,5 ms (5 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (93 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:20:38-03:00 DEBUG metabase.middleware.log GET /api/card/26 200 3,7 ms (5 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:20:38-03:00 DEBUG metabase.middleware.log GET /api/alert/question/26 200 1,3 ms (1 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:20:38-03:00 DEBUG metabase.middleware.log POST /api/card/26/query 200 [ASYNC: completed] 68,3 ms (11 DB calls) Jetty threads: 2/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:20:56-03:00 DEBUG metabase.middleware.log POST /api/dataset 200 [ASYNC: completed] 39,4 ms (9 DB calls) Jetty threads: 2/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:20:59-03:00 DEBUG metabase.middleware.log POST /api/dataset 200 [ASYNC: completed] 65,2 ms (8 DB calls) Jetty threads: 2/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:21:05-03:00 DEBUG metabase.middleware.log GET /api/database/2/autocomplete_suggestions 200 14,3 ms (6 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:21:07-03:00 DEBUG metabase.middleware.log POST /api/dataset 200 [ASYNC: completed] 48,8 ms (9 DB calls) Jetty threads: 2/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:21:14-03:00 DEBUG metabase.middleware.log POST /api/dataset 200 [ASYNC: completed] 56,9 ms (8 DB calls) Jetty threads: 2/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:21:40-03:00 DEBUG metabase.middleware.log GET /api/database/2/autocomplete_suggestions 200 13,2 ms (6 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:21:43-03:00 DEBUG metabase.middleware.log POST /api/dataset 200 [ASYNC: completed] 40,8 ms (8 DB calls) Jetty threads: 2/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:22:03-03:00 DEBUG metabase.middleware.log GET /api/session/properties 200 2,4 ms (1 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:22:03-03:00 DEBUG metabase.middleware.log GET /api/setup/admin_checklist 200 5,4 ms (11 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:22:03-03:00 DEBUG metabase.middleware.log GET /api/setting 200 398,7 µs (0 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0
[04cd97c3-640e-470a-a83e-2cf81f1869d9] 2020-02-06T12:22:05-03:00 DEBUG metabase.middleware.log GET /api/util/bug_report_details 200 1,7 ms (1 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (95 total active threads) Queries in flight: 0

**Comment by AndreLuizRego** [comment] 2020-02-06 15:28
And here is about my Metabase Diagnostic Info:

{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_201-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_201",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.201-b09",
    "os.name": "Linux",
    "os.version": "3.10.0-693.17.1.el7.x86_64",
    "user.language": "pt",
    "user.timezone": "America/Argentina/Buenos_Aires"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.0-snapshot",
      "date": "2019-09-22",
      "branch": "simple-sso",
      "hash": "60d2905"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by flamber** [comment] 2020-02-06 15:55
@AndreLuizRego As I said in the other issue too, you're using a third party version of Metabase, so you need to get support from the people who created that version. Or use an official release: https://www.metabase.com/start/
I'm going to close this issue, since we cannot provide support for third party versions.

**Closed by flamber** 2020-02-06 15:55 UTC
Labels: .Unable to Reproduce, Priority:P2, Querying/Native, Type:Bug
