### ISSUE TITLE
Two same type mertic can‘t be used in one question

### ISSUE THREAD

**Issue by MrPortra** [metabase/metabase#7595] opened 2018-05-09 05:44 UTC
I added two sum or count distinct metrics in one tables. Like sum(real_amount) and sum(sale_amount) group by day. And get error like this:

`There was a problem with your question
Most of the time this is caused by an invalid selection or bad input value. Double check your inputs and retry your query.`

But when  I make new question on the table,use only one mertic,it works fine. I test Number of distinct mertics it seems like have same problem

*browser and the version:   Chrome 66.0
operating system:  OS X 10.11.16
databases:  Druid
Metabase version: 0.28.1
Metabase hosting environment:   Linux/Ubuntu 
Metabase internal database:  MySQL*

**Comment by MrPortra** [comment] 2018-05-09 07:34
This problem appears on Druid. Other databases work well

**Comment by salsakran** [comment] 2018-05-09 20:46
possibly related to (or a dupe of #5393)

**Comment by emetselaar** [comment] 2018-05-18 14:50
If you make them both Custom Expressions and give them their own alias (name) then it works OK. 

However, there are indeed issues with how queries are build for Druid.

I am tried to figure out what the exact issue is.

My conclusion now is: Any Custom Expression that contains any arithmetic operator like / + * etc. will be the only metric shown.

When you do a SUM(metric1) AS M1 and a Custom Expression like SUM(metric2)/2 AS M2 then only M2 is being calculated and shown. I can actually can see in the raw query that the metric1 is not even part of the query anymore. This is specific for Druid it seems and does not happen with my SQL like databases.

**Comment by aerendil** [comment] 2018-05-24 08:49
@emetselaar Indeed it seems the issue is that the query builder do actually name the aggregation by a default name which is "sum" if it's not a custom expression instead of building a name like "sum_metric1", for example.

I made a little patch that works for me  that I posted there : #4166 . If you have the possibility of using it, let me know if it works :)

**Comment by aerendil** [comment] 2018-06-04 15:57
Actually, the patch isn't a good solution at all - I found multiple issues with it so I removed it for now - I'll make sure to keep you updated when I manage to fix it and will join a step by step method to apply it!

**Comment by camsaul** [comment] 2018-11-20 21:38
Duplicate of #7195

**Closed by camsaul** 2018-11-20 21:38 UTC
Labels: Bug, Database/Druid, Priority/P2, Query Builder
