### ISSUE TITLE
Dropdown not showing for publicly shared dashboard

### ISSUE THREAD

**Issue by ElishaKay** [metabase/metabase#7658] opened 2018-05-17 13:11 UTC
![image](https://user-images.githubusercontent.com/16700452/40179273-9a0a4964-59ec-11e8-986e-119b23e36939.png)

I have a filter to set a MySQL Column as a "Category" filter. The question is added to a dashboard that has filters. When I view the dashboard as a logged-in metabase user, I see the values.

But, when I share the dashboard, the user has a textbox for the same filter (instead of the dropdown with the ENUM values)

------
Before filing an issue we'd appreciate it if you could take a moment to ensure
there isn't already an open issue or pull-request.
-----

If there's an existing issue, please add a :+1: reaction to the description of
the issue. One way we prioritize issues is by the number of :+1: reactions on
their descriptions. Please DO NOT add `+1` or :+1: comments.

### Database support

For requests for new database drivers, please include the name
of the database and the version. Additionally, giving us a sense of how and what
you use it for, and other high-level details about the database, can help us get
a better picture of what would need to done to support it.

### Feature requests and proposals
We're excited to hear how we can make Metabase better. Please add as much detail
as you can on your use case.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

- *Repeatable steps to reproduce the issue*

Thanks for being part of the Metabase project!
-------

**Comment by mazameli** [comment] 2018-05-17 16:58
It appears you're on an older version of Metabase. [I believe this was the fix](https://github.com/metabase/metabase/pull/7248), which was included in Metabase version 0.28.5 (latest version is 0.29.3).

Can you verify which version of Metabase you're using?

**Comment by flamber** [comment] 2020-04-02 13:02
Closing, cannot reproduce on 0.35.0

**Closed by flamber** 2020-04-02 13:02 UTC
Labels: .Need More Info
