### ISSUE TITLE
On Safari mobile, dashboards (auto) refresh every 5 seconds

### ISSUE THREAD

**Issue by thibault-yellowstones** [metabase/metabase#22516] opened 2022-05-07 10:04 UTC
**Describe the bug**
Dashboards refresh every 5 seconds on Safari mobile. 
It is the whole page that refreshes, not the content of the dashboard, which makes dashboards impossible to use on mobile.

**Logs**
No time to get logs as refresh happens too fast.

**To Reproduce**
1. Go to a dashboard on Safari mobile.
2. Wait 2 seconds, the page refreshes. 

**Expected behavior**
The dashboard page should not refresh at all.

**Screenshots**

https://user-images.githubusercontent.com/39294553/167249431-59b3e125-a730-46c5-a507-6f119667b2e7.mp4

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Safari Mobile
- Your operating system: IOS 15.0.2
- Your databases: Postgres
- Metabase version: = 0.43.0 (no problem with previous versions)
- Metabase hosting environment: ECS (Docker container, official metabase image)
- Metabase internal database: H2 (default)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
It makes it impossible to visualise dashboards on mobile and it is a regression, so very severe.

**Comment by flamber** [comment] 2022-05-07 10:11
Duplicate of #22172

**Closed by flamber** 2022-05-07 10:11 UTC
Labels: Type:Bug, .Needs Triage
