### ISSUE TITLE
Snowflake sync fails with "Missing user name"

### ISSUE THREAD

**Issue by john-metabase** [metabase/metabase#31475] opened 2023-06-09 16:11 UTC
### Describe the bug

Sync fails with a "Missing user name" error for Snowflake connections using an uploaded private key, username but no password, and a role name. Other combinations haven't been tested. I suspect this is related to no password combined with a role.

### To Reproduce

1. Save a new Snowflake connection with no password, uploaded private key, and a role name
2. Observe sync failure after a period of time

### Expected behavior

Sync should complete successfully

### Logs

```
2023-06-09 11:52:24,832 ERROR events.sync-database :: Error syncing Database 2
java.sql.SQLException: Connections could not be acquired from the underlying database!
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:692)
        at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:372)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:343)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
        at metabase.driver.snowflake$eval124373$fn__124374$fn__124375.invoke(snowflake.clj:397)
        at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:47)
        at metabase.query_processor.store$do_with_store.invoke(store.clj:41)
)       at metabase.driver.snowflake$eval124373$fn__124374.invoke(snowflake.clj:390
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at metabase.sync.fetch_metadata$eval100838$db_metadata__100843$fn__100844.invoke(fetch_metadata.clj:15)
        at metabase.sync.fetch_metadata$eval100838$db_metadata__100843.invoke(fetch_metadata.clj:12)
        at metabase.sync.sync_metadata$eval102678$sync_db_metadata_BANG___102683$fn__102684.invoke(sync_metadata.clj:58)
        at metabase.sync.sync_metadata$eval102678$sync_db_metadata_BANG___102683.invoke(sync_metadata.clj:55)
        at metabase.events.sync_database$process_sync_database_event$fn__122600.invoke(sync_database.clj:40)
        at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
        at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1507)
        at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
        at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
        ... 21 more
Caused by: net.snowflake.client.jdbc.SnowflakeSQLLoggedException: Missing user name.
        at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initialize(DefaultSFConnectionHandler.java:109)
        at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initializeConnection(DefaultSFConnectionHandler.java:79)
tionV1.initConnectionWithImpl(SnowflakeConnectionV1.java:116)
        at net.snowflake.client.jdbc.SnowflakeConnectionV1.<init>(SnowflakeConnectionV1.java:96)
        at net.snowflake.client.jdbc.SnowflakeDriver.connect(SnowflakeDriver.java:180)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
        at metabase.connection_pool$proxy_data_source$reify__45642.getConnection(connection_pool.clj:29)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:161)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:147)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:202)
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
ntPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)eAndDecreme
        at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
        at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
        at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
```

### Information about your Metabase installation

```JSON
v1.46.2
```

### Severity

blocks anyone trying to use this configuration

**Comment by paoliniluis** [comment] 2023-06-09 17:04
duplicate of https://github.com/metabase/metabase/issues/30376

**Closed by paoliniluis** 2023-06-09 17:04 UTC
Labels: Type:Bug, .Needs Triage
