### ISSUE TITLE
Export the query response directly to google sheets.

### ISSUE THREAD

**Issue by sarth886** [metabase/metabase#31754] opened 2023-06-21 08:37 UTC
Whenever I need the data for analysis I need to download data in csv and export that to sheets ....Instead of that it would be great if I could export to sheets directly from metabase.

Let me know if there is any way we can do that currently.

**Comment by paoliniluis** [comment] 2023-06-23 12:53
dupe of https://github.com/metabase/metabase/issues/9810

**Closed by paoliniluis** 2023-06-23 12:53 UTC
Labels: Type:New Feature, .Needs Triage
