### ISSUE TITLE
Details page is a "little lost" when browsing Postgres data and clicking on first primary key (Entity Key)

### ISSUE THREAD

**Issue by PierreKerschgens** [metabase/metabase#25326] opened 2022-09-09 11:21 UTC
**Describe the bug**
When I'm in the browse data section of a Postgres connection and try to get the details page of the very first row (by clicking on the primary key link) I get "We're a little lost...". No matter how the table is ordered, the very first item leads to this error message.

**Logs**
I didn't find logs related to that issue neither in "admin/troubleshooting/logs" nor in host container logs.

**To Reproduce**
1. Go to 'Browse data'
2. Click on a  Postgres database connection
3. Click on a table
4. Click on the primary key (Entity Key in table details) hyperlink of the very first table row
5. See error

**Expected behavior**
I'd like to see the details page of the clicked row.

**Screenshots**
![Screenshot 2022-09-09 at 13 11 24](https://user-images.githubusercontent.com/33054479/189337537-20216abf-394f-4858-835f-7e386ab6ae72.png)

Not much to see sorry but it shows the table on top and the error page (that should be the details page) at the bottom.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox 104.0.1 (64-bit)
- Your operating system: macOS 12.3
- Your databases: Postgres, Athena, MySQL
- Metabase version: v0.43.1
- Metabase hosting environment: Docker container running as AWS Fargate ECS task
- Metabase internal database: Postgres

**Severity**
Issue is annoying because you can - if you know - sort differently and view the details page of a specific row. Could block some users that aren't aware of the workaround.

**Additional context**
We use Metabase v0.43.1 because we need [this Athena driver](https://github.com/dacort/metabase-athena-driver). The latest tested Metabase version of that driver is v0.43.1.

**Comment by flamber** [comment] 2022-09-09 11:25
Duplicate of #22768
Just because the driver wasn't tested with a newer version doesn't mean it doesn't work, it just means that v1.4.0 of the driver was only tested with Metabase 0.43.1 (since that was the newest version at the time of driver release, and to note that the driver wasn't tested with previous versions of Metabase).

**Closed by flamber** 2022-09-09 11:25 UTC
Labels: Type:Bug, .Needs Triage
