### ISSUE TITLE
"Today" filter broken

### ISSUE THREAD

**Issue by crazydog115** [metabase/metabase#2703] opened 2016-06-06 17:02 UTC
* Chrome Version 51.0.2704.79 (64-bit)
* OS X 10.11.5
* Metabase 0.17.1 on Heroku
* DB is Postgres 9.5.3

When selecting "Today" as a date filter, after choosing "Add Filter", the following JS error occurs, and the filter does not get added:
```
Uncaught TypeError: Cannot read property 'toLowerCase' of null
capitalize	@	inflection.js:846
l	        @	query_time.js:88
s	        @	query_time.js:118
(anonymous function)	@	query_time.js:70
u	        @  	query_time.js:70
```

After this, if any other filter, or view selection, etc. is selected, it does not work, and the following JS error occurs.
```
Uncaught TypeError: Cannot read property '_currentElement' of null
_updateRenderedComponent	@	ReactCompositeComponent.js:559
```

The only workaround is a full page refresh.

**Comment by tlrobinson** [comment] 2016-06-06 17:16
Duplicate of #2703, it's fixed in master and will be released in v0.18.0

**Closed by tlrobinson** 2016-06-06 17:16 UTC
