### ISSUE TITLE
can disable tooltips only one chart

### ISSUE THREAD

**Issue by eaotnc** [metabase/metabase#17083] opened 2021-07-16 03:11 UTC
I need to disable tooltips on some chart can it be disable?

**Comment by paoliniluis** [comment] 2021-07-16 16:03
Hi, closing this as it's a duplicate of https://github.com/metabase/metabase/issues/17084.

Also, please post your questions in the forum if possible :) . Thanks!

**Closed by paoliniluis** 2021-07-16 16:03 UTC
Labels: .Needs Triage, Type:Question
