### ISSUE TITLE
On our stats instance, the Slack icon is missing from the dashboard subscriptions sidebar

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14493] opened 2021-01-22 16:41 UTC
I'm not seeing this when running master locally, but on our stats instance, the icon is missing here. Stats is currently on `e68a39a`.

<img width="394" alt="Screen Shot 2021-01-22 at 8 38 38 AM" src="https://user-images.githubusercontent.com/2223916/105518673-69cb3000-5c8d-11eb-991c-4c015b5ecca6.png">

**Comment by nemanjaglumac** [comment] 2021-01-22 23:05
I can see it now. Can you please check again.

**Comment by tsmacdonald** [comment] 2021-01-26 17:24
I'm also seeing it

![image](https://user-images.githubusercontent.com/784417/105880407-f432cd00-5fc8-11eb-8e11-c4fff6f44375.png)


![image](https://user-images.githubusercontent.com/784417/105880446-fe54cb80-5fc8-11eb-8266-112f2d5f4d76.png)


I'm going to close this for now

**Closed by tsmacdonald** 2021-01-26 17:24 UTC
Labels: Priority:P2, Reporting/Dashboards, Type:Bug

**Comment by tsmacdonald** [comment] 2021-01-26 21:08
We did have [this issue with the sharing icon](https://github.com/metabase/metabase/pull/14289), but I just confirmed that the [retina Slack image exists](https://stats.metabase.com/app/assets/img/slack@2x.png)

I was a little surprised the image `src` is `app/assets/img/slack.png` instead of `/app/assets/img/slack.png` (leading slash), but like I said it seems to be working now.
