### ISSUE TITLE
Date columns are filtered by timestamp with timezone

### ISSUE THREAD

**Issue by TraviJohnny** [metabase/metabase#27458] opened 2022-12-29 10:15 UTC
**Describe the bug**
Date columns are filtered by timestamp with timezone depending on the timezone given in the admin/settings/localization -> REPORT TIMEZONE. 
Our date is stored as a German Date in the Database. When filtering as presented in the Screenshot below we get the wrong result. 
When REPORT TIMEZONE is set to Europe/Berlin as sql is transformed into
```
WHERE ("metabase"."marketing_metatable"."reference_date" < timestamp with time zone '2022-11-28 00:00:00.000+01:00'
   AND "metabase"."marketing_metatable"."reference_date" >= timestamp with time zone '2022-11-27 00:00:00.000+01:00')
```
Result date would be the the 26th of November, but 27th would be expected according to the filter in the screenshot.
So we have to use UTC as  REPORT TIMEZONE
```
WHERE ("metabase"."payment_metatable"."receipt_datetime" < timestamp with time zone '2022-11-28 00:00:00.000Z'
   AND "metabase"."payment_metatable"."receipt_datetime" >= timestamp with time zone '2022-11-27 00:00:00.000Z')
```
This would yield the expected date 27th of November. But which then causes issues with other columns stored as timestamp with timezone Europe/Berlin and the email scheduling time. 

**Logs**
not applicable

**To Reproduce**
Just looking at the SQL Statement when filtering any date column

**Expected behavior**
Wouldn't it make more sense to have date columns filtered i.e. like this when defined as a date?
WHERE ("metabase"."marketing_metatable"."reference_date" < '2022-11-28'
   AND "metabase"."marketing_metatable"."reference_date" > '2022-11-26')

**Screenshots**
![image](https://user-images.githubusercontent.com/121111871/209936149-d0b1b7c4-959b-4b71-9c16-422a67de0125.png)

**Information about your Metabase Installation:**
we are using Redshift as a reporting db, so Date can only be stored as UTC
```
{
  "browser-info": {
    "language": "de-DE",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.17+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.17",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.17+8",
    "os.name": "Linux",
    "os.version": "5.10.147-133.644.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.26"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-12-07",
      "tag": "v0.45.1",
      "branch": "release-x.45.x",
      "hash": "019d31c"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}

```

**Comment by flamber** [comment] 2022-12-29 10:54
Duplicate of #19910

**Closed by flamber** 2022-12-29 10:54 UTC
Labels: Type:Bug, .Needs Triage
