### ISSUE TITLE
Dashboards: "add questions" sidebar overlaps other sidebars

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#17691] opened 2021-08-31 15:56 UTC
**Describe the bug**
While editing a dashboard, if I open the "add questions" sidebar and then want to change a card's click behavior or edit a dashboard filter, I can't see the corresponding sidebars as they're overlapped by the "add questions" sidebar.

**To Reproduce**

1. Go to a dashboard > "Edit dashboard" ✏️  > "Add questions" ➕ 
2. Hover any card and click "Click behaviour"
3. Click behavior sidebar is invisible.
4. Click the gear icon on any dashboard filter
5. Filter options sidebar is invisible.

WORKAROUND: close the "Add questions" sidebar, and then you'll see the expected sidebar.

**Expected behavior**
The click behavior and dashboard filter sidebar should be visible on the right side. The "Add questions" popup has to be either closed or overlapped by the most recent one.

**Video**

https://user-images.githubusercontent.com/17258145/131535864-5c856e02-c157-4510-875c-d481f4c04e39.mov

**Information about your Metabase Installation:**

Metabase v0.41.0-SNAPSHOT

**Comment by flamber** [comment] 2021-08-31 16:01
Duplicate of #16783

**Closed by flamber** 2021-08-31 16:01 UTC
Labels: Type:Bug, Type:UX, .Needs Triage
