### ISSUE TITLE
Dashboard Error 500

### ISSUE THREAD

**Issue by Linuxfabrik** [metabase/metabase#10853] opened 2019-09-10 11:46 UTC
**Describe the bug**
If you create a Dashboard and add any question against your first table (first = the first one from `metabase_table`, not necessarily with ID 1), the Dashboard crashes with Error 500. If you just use questions that fetch their data from any other table, the Dashboard works as expected.

**Logs**
`java[7364]: 09-10 13:38:18 ERROR middleware.log :: GET /api/dashboard/8 500 17.6 ms (11 DB calls)
java[7364]: [189B blob data]
java[7364]: :type java.sql.SQLSyntaxErrorException,
java[7364]: :stacktrace
java[7364]: ("org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:236)"
java[7364]: "org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)"
java[7364]: "org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)"
java[7364]: "org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:232)"
java[7364]: "org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)"
java[7364]: "org.mariadb.jdbc.MariaDbPreparedStatementClient.executeQuery(MariaDbPreparedStatementClient.java:174)"
java[7364]: "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)"
java[7364]: "clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1072)"
java[7364]: "clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1066)"
java[7364]: "clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1095)"
java[7364]: "clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)"
java[7364]: "clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)"
java[7364]: "clojure.java.jdbc$query.invoke(jdbc.clj:1126)"
java[7364]: "toucan.db$query.invokeStatic(db.clj:285)"
java[7364]: "toucan.db$query.doInvoke(db.clj:281)"
java[7364]: "clojure.lang.RestFn.invoke(RestFn.java:410)"
java[7364]: "toucan.db$simple_select.invokeStatic(db.clj:391)"
java[7364]: "toucan.db$simple_select.invoke(db.clj:380)"
java[7364]: "toucan.db$select.invokeStatic(db.clj:659)"
java[7364]: "toucan.db$select.doInvoke(db.clj:653)"
java[7364]: "clojure.lang.RestFn.applyTo(RestFn.java:139)"
java[7364]: "clojure.core$apply.invokeStatic(core.clj:667)"
java[7364]: "clojure.core$apply.invoke(core.clj:660)"
java[7364]: "toucan.db$select_field__GT_field.invokeStatic(db.clj:701)"
java[7364]: "toucan.db$select_field__GT_field.doInvoke(db.clj:694)"
java[7364]: "clojure.lang.RestFn.invoke(RestFn.java:494)"
java[7364]: "--> api.dashboard$hashes__GT_hash_vec__GT_avg_time.invokeStatic(dashboard.clj:162)"
java[7364]: "api.dashboard$hashes__GT_hash_vec__GT_avg_time.invoke(dashboard.clj:156)"
java[7364]: "api.dashboard$add_query_average_duration_to_dashcards.invokeStatic(dashboard.clj:176)"
java[7364]: "api.dashboard$add_query_average_duration_to_dashcards.invoke(dashboard.clj:173)"
java[7364]: "api.dashboard$add_query_average_durations.invokeStatic(dashboard.clj:188)"
java[7364]: "api.dashboard$add_query_average_durations.invoke(dashboard.clj:185)"
java[7364]: "api.dashboard$get_dashboard.invokeStatic(dashboard.clj:194)"
java[7364]: "api.dashboard$get_dashboard.invoke(dashboard.clj:191)"
java[7364]: "api.dashboard$fn__48680.invokeStatic(dashboard.clj:236)"
java[7364]: "api.dashboard$fn__48680.invoke(dashboard.clj:233)"
java[7364]: "middleware.auth$enforce_authentication$fn__64059.invoke(auth.clj:14)"
java[7364]: "routes$fn__65209$fn__65210.doInvoke(routes.clj:56)"
java[7364]: "middleware.exceptions$catch_uncaught_exceptions$fn__64158.invoke(exceptions.clj:104)"
java[7364]: "middleware.exceptions$catch_api_exceptions$fn__64155.invoke(exceptions.clj:92)"
java[7364]: "middleware.log$log_api_call$fn__65583$fn__65584.invoke(log.clj:170)"
java[7364]: "middleware.log$log_api_call$fn__65583.invoke(log.clj:164)"
java[7364]: "middleware.security$add_security_headers$fn__64121.invoke(security.clj:128)"
java[7364]: "middleware.json$wrap_json_body$fn__65288.invoke(json.clj:61)"
java[7364]: "middleware.json$wrap_streamed_json_response$fn__65306.invoke(json.clj:97)"
java[7364]: "middleware.session$bind_current_user$fn__62021$fn__62022.invoke(session.clj:193)"
java[7364]: "middleware.session$do_with_current_user.invokeStatic(session.clj:176)"
java[7364]: "middleware.session$do_with_current_user.invoke(session.clj:170)"
java[7364]: "middleware.session$bind_current_user$fn__62021.invoke(session.clj:192)"
java[7364]: "middleware.session$wrap_current_user_id$fn__62010.invoke(session.clj:161)"
java[7364]: "middleware.session$wrap_session_id$fn__61995.invoke(session.clj:123)"
java[7364]: "middleware.auth$wrap_api_key$fn__64067.invoke(auth.clj:27)"
java[7364]: "middleware.misc$maybe_set_site_url$fn__65610.invoke(misc.clj:56)"
java[7364]: "middleware.misc$bind_user_locale$fn__65613.invoke(misc.clj:72)"
java[7364]: "middleware.misc$add_content_type$fn__65598.invoke(misc.clj:28)"
java[7364]: "middleware.misc$disable_streaming_buffering$fn__65621.invoke(misc.clj:87)"),
java[7364]: :sql-exception-chain
java[7364]: ["SQLSyntaxErrorException:"
java[7364]: [187B blob data]
java[7364]: "SQLState: 42000"
java[7364]: "Error Code: 1064"]}
`

**To Reproduce**
1. Create some questions that fetch their data from any but your first table.
2. Create a Dashboard and attach those questions to it.
3. Create a question that get its data from your first table.
4. Add this question to the Dashboard from 2.
5. You'll get `<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>500 Server Error</title> </head><body> <h1>Server Error</h1> <p>The server encountered an internal error or misconfiguration and was unable to complete your request.</p> <p>Please contact the server administrator at ... to inform them of the time this error occurred, and the actions you performed just before this error.</p> <p>More information about this error may be available in the server error log.</p> </body></html> `

You could test this directly in the metabase database in `report_dashboardcard.card_id` (for example to heal your Dashboard).

**Expected behavior**
The Dashboard should work as expected, regardless of where the questions fetch their data from.

**Information about your Metabase Installation:**
- Your operating system: CentOS 3.10.0-957.27.2.el7.x86_64
- Your databases: MariaDB ColumnStore
- Metabase version: 0.33.2
- Metabase hosting environment: jar-File, systemd
- Metabase internal database: MariaDB

**Severity**
Blocker for all Users, annoying for the Admin.

**Comment by salsakran** [comment] 2019-10-06 00:02
what is the name of this table?

The error being thrown is a SQL syntax error, which shouldn't have anything to do with an id of 1.

**Comment by salsakran** [comment] 2020-02-22 03:19
closing since it was only hit by one person, seems to be caused by sql syntax and no further information to help reproduce it has been provided for 5 months.

**Closed by salsakran** 2020-02-22 03:19 UTC
Labels: Database/MySQL, Priority:P2, Querying/, Querying/Processor, Type:Bug
