### ISSUE TITLE
Failed to connect to database: org.postgresql.util.PSQLException

### ISSUE THREAD

**Issue by astathis** [metabase/metabase#4864] opened 2017-04-25 07:44 UTC
- Windows 8.1. Pro
- PostgreSQL 9.6
- Metabase version: (v0.23.1)

 I have installed a fresh metabase version (see above) and everything was fine. After a restart I couldn't start metabase with usual command (java -jar metabse.jar) with error that it could not connect H2 (java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.). Then I run the command 
java -jar metabase.jar migrate release-locks but it was failing again. Because my 1st project was created on postgres, I decided to move there. So, I run 👍 
```
set MB_DB_TYPE=postgres
set MB_DB_DBNAME=metabase
set MB_DB_PORT=5432
set MB_DB_USER=<username>
set MB_DB_PASS=<pwd>
set MB_DB_HOST=127.0.0.1

java -jar metabase.jar
```

but I get the error : _ERROR metabase.driver←[0m :: Failed to connect to database: org.postgresql.util.PSQLException: FATAL: database "metabase" does not exist_

 How can I start metabase even with clean DB or what can I do to recover the from this situation?

**Comment by salsakran** [comment] 2017-04-26 19:18
sounds like the database server MB connected to doesn't have a database named `metabase` on it. did you do a `createdb`?

Closing this as it's not a bug report, and relates to your specific setup. Our discussion forum is a better place to get this kind of help if the above doesn't get you sorted.

**Closed by salsakran** 2017-04-26 19:18 UTC
