### ISSUE TITLE
Missing database types in the Admin -> Add database screen

### ISSUE THREAD

**Issue by mherle** [metabase/metabase#5415] opened 2017-06-30 04:57 UTC
- Your browser and the version: Chrome 59.0.3071.86
- Your operating system: Ubuntu 16.04.2 LTS
- Your databases: NA
- Metabase version: v0.24.2
- Metabase hosting environment: OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
- Metabase internal database: H2

- 
I'm only seeing few database types (in the dropdown for adding a database). One issue could be that these are the ones that we already have database of.
Have control over the hosting environment and can give more logs/infos if needed.

![metabase_issue](https://user-images.githubusercontent.com/1589535/27721542-8d6be732-5d7e-11e7-8d04-79d4204e6e55.png)

-------

**Comment by salsakran** [comment] 2017-07-10 04:31
are there any javascript console errors?

**Comment by mherle** [comment] 2017-07-11 13:56
Some errors of font not loading:

`Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAIw4ABEAAAABQcAAAQABAAAAAAAAAAAAAAAAAAAAA…hgZiCKVViwAiVhsAFFYyNisAIjRLMJCgMCK7MLEAMCK7MRFgMCK1myBCgGRVJEswsQBAIrAA==' because it violates the following Content Security Policy directive: "font-src 'self' fonts.gstatic.com themes.googleusercontent.com ".`

However, 
`/api/session/properties
`
is returning only entries: "h2", "mysql", "postgres", "redshift" and "mongo"
{ engines : { "h2": {...}, "mysql": {}... etc }

Does this help ?

**Comment by camsaul** [comment] 2017-07-14 19:23
Closing as duplicate of #2881.

**Closed by camsaul** 2017-07-14 19:23 UTC
Labels: Admin Panel & Setup, Bug, Priority/P2

**Comment by camsaul** [comment] 2017-07-14 19:26
@mherle this seems to be an issue with the OpenJDK 9 Beta and not with Metabase itself. We recommend you use OpenJDK 8 until OpenJDK 9 reaches a more stable state.

**Comment by mherle** [comment] 2017-07-17 13:53
Thanks for the update.
