### ISSUE TITLE
Getting stuck in setup wizard after entering an invalid email

### ISSUE THREAD

**Issue by attekei** [metabase/metabase#5057] opened 2017-05-10 18:34 UTC
Initially, the setup wizard accepts my email address which contains Scandinavian characters `ä` and `ö`, and lets me add a database. In the last step, clicking `Next` fails silently and the server returns a validation error.

<img width="1435" alt="screen shot 2017-05-10 at 11 29 40" src="https://cloud.githubusercontent.com/assets/6034928/25914873/8445c95c-3574-11e7-91a3-8da1437b7fce.png">

Seems that the frontend and backend have different criteria for validating the email address.

**Comment by attekei** [comment] 2017-05-10 18:37
I just learned that I'm able to go back to first step by clicking the "Hi, Username. Nice to meet you!" , but that is hard to discover because the cursor doesn't change to pointer when you hover on the text/container.

**Comment by mazameli** [comment] 2019-10-11 22:46
I just reproduced this in 0.33.4 and I'm setting it to a P1 since it has to do with setup and a silent error. Let me know if I'm over-escalating this.

The server error I'm getting is `10-11 15:44:49 DEBUG middleware.log :: POST /api/setup 400 1.4 ms (0 DB calls) 
{:errors {:email "value must be a valid email address."}}`

To repro, on a fresh install put in an email address like `MäZöMELI@metabase.com` and try to complete the entire setup flow. Clicking the Next button on the `Usage data preferences` step will result in that server error, but no user-facing error, and nothing happens.

**Comment by camsaul** [comment] 2020-01-13 19:29
This sounds like the same issue as #10926, which was fixed by @paulrosenzweig for 0.34.0

**Comment by camsaul** [comment] 2020-01-13 19:29
Fixed by #11042

**Closed by camsaul** 2020-01-13 19:29 UTC
Labels: First Experience/Setup, Priority:P1, Type:Bug
