### ISSUE TITLE
Can't remove cards from dashboard

### ISSUE THREAD

**Issue by mattxbart** [metabase/metabase#8785] opened 2018-10-26 15:43 UTC
Hi,
I can only reproduce this issue in Chrome (I recently upgraded). If you create a dashboard and add a question you cannot remove the cards from the dashboard. Clicking the "X" on the card does not fire any event. It works as expected in Firefox and Edge.

![error](https://user-images.githubusercontent.com/5711411/47576837-4ec8b480-d8fa-11e8-9eea-6e129b4ad27a.png)

After clicking the following messages are printed to the console:
Popover.jsx:177
[Violation] 'click' handler took 196ms
[Violation] Forced reflow while executing JavaScript took 37ms

Browser: Chrome Version 70.0.3538.77
OS: Windows 10
Database: Postgres 9.5

Metabase version:  0.30.4
Metabase hosting environment: Linux
Metabase internal database: Postgres

**Comment by mazameli** [comment] 2018-10-26 17:48
Couldn't reproduce this with Chrome v. 70.0.3538.77 on the master branch of Metabase, but I'm on macOS High Sierra. Maybe this is a Windows-specific bug.

**Comment by MarkRx** [comment] 2018-10-29 21:30
This happens to me all the time. The 'X' button doesn't work and I have to resort to Firefox to remove cards from a dashboard. It doesn't happen to a coworker who is running with chrome on Windows 10.

Your browser and the version: 69.0.3497.100 (Official Build) (64-bit)
Your operating system: Windows 7
Your databases: Oracle 12.2
Metabase version: 0.30.3
Metabase hosting environment: RHEL 7
Metabase internal database: MySQL

**Comment by kdoh** [comment] 2018-10-31 02:40
Going to close this since it seems to be a duplicate of #2187. I'm aware its a bummer this is still a thing so I don't want to overlook that but it does help having 1 open issue per specific problem. I'm not really much of a windows user and it does seem like its been sporadic but I'll see if I can spin up a VM and poke around. I'll also elevate the priority of that original issue since its kinda nutty it's been reported over such a long period.

**Closed by kdoh** 2018-10-31 02:40 UTC
Labels: Browser/Chrome, OS/Windows, Unable to Reproduce
