### ISSUE TITLE
Override of data model field (FK->category) is periodically reset

### ISSUE THREAD

**Issue by caseyching** [metabase/metabase#7088] opened 2018-03-07 19:24 UTC
The use case is that I want to use a foreign key field as a variable in a query along with a dropdown which lists all available FK values. This is somewhat possible to do now by editing the data model and changing field which is detected as an FK to a category type. This works great immediately but the next day the data model resets itself back to an FK field. I suspect something about the background schema discovery/refresh is resetting the field. Is there some  way to permanently change the field type?

Alternatively is there a way to force an FK to be shown  in the query UI as a dropdown widget? Currently the widget is a text input with no auto-complete.

- Your browser and the version: Chrome 
- Your operating system: OS X 
- Your databases: Postgres
- Metabase version: 0.27.1
- Metabase hosting environment: Linux 
- Metabase internal database: Postgres

- *Repeatable steps to reproduce the issue*
    1. Create db schema that contains an FK 
    1. Scan the schema
    1. Manually edit the populated schema using the admin data model editor. Change the FK to category.
    1. Wait for the next schema refresh
    1. The manual edit to the data model is now lost

**Comment by flamber** [comment] 2020-06-11 10:46
I've reproduce this on 0.35.4, but it might actually be a duplicate of #3464

**Comment by sbelak** [comment] 2020-06-11 11:02
Also covered by #12574

**Closed** 2020-07-02 15:36 UTC
Labels: Administration/Metadata & Sync, Priority:P2, Type:Bug
