### ISSUE TITLE
Switching dataset corrupts question

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#10831] opened 2019-09-06 23:18 UTC
Reported by a user on EE v1.0.6- 

Recently, we had a case where we need to switch the BigQuery dataset/table for a dozen questions. The user selected the new dataset but didn't select the table as the table name is the same (thinking that it would be an easy swap without having to redo the filters/groups/visualization) and saved the question.

Even though no table was selected after selecting the dataset, it saved successfully, however the question becomes corrupted. Any attempt to view the question (after refreshing browser) will result in a bank page. 

The following error is displayed in the browser console: ncaught (in promise) TypeError: Cannot read property 'source-table' of undefined

If you look at what's stored in the database, the dataset_query is set to {"database":21,"type":"query"}, which is missing the source-table. 

To fix this, I had to manually restore the dataset_query for a dozen questions. 

Aside from the obvious of preventing the saving of corrupted questions, two suggestions for improving the experience on changing table sources:
1) Remove the chart (when it removes the filters/groups) so it is obvious the chart no longer applies to the current state of the question. This would prevent users from thinking everything is still working when nothing is.
2) Currently, the filters/groups are removed when changing dataset/table. This makes it hard to change the chart to use a different table source that has the same fields. It would be better if it would do that after the user selects the table and checks that fields used by the chart have changed. If there are no changes to any fields, then the chart/filter/group should be retained. Right now, it's hard to do migrations when a dataset or table needs to be renamed.

**Comment by ranquild** [comment] 2023-11-08 11:29
Repro steps:
- Add PG sample database
- New -> Question -> Sample DB (H2) -> Orders -> Save
- Notebook -> Click on the data source -> PG -> Orders
- Click Visualize

The issue is that we don't change the database when selecting a new table in `DataStep`

<img width="932" alt="Screenshot 2023-11-08 at 12 53 07" src="https://github.com/metabase/metabase/assets/8542534/f724a09a-ad1b-4202-9173-598f3cd96b35">

**Comment by ranquild** [comment] 2023-11-08 13:57
Discussed - this is a BE (CLJS) issue https://github.com/metabase/metabase/issues/35245

**Comment by darksciencebase** [comment] 2023-12-27 12:06
closing in favor of #35245 then

**Closed by darksciencebase** 2023-12-27 12:06 UTC
Labels: Type:Bug, Priority:P2, Querying/MBQL, .Backend, .Team/QueryProcessor, .Wanted: MLv2
