### ISSUE TITLE
Custom Column fixed to type/Float Field since 0.39.0.1

### ISSUE THREAD

**Issue by MarcSamD** [metabase/metabase#15710] opened 2021-04-21 09:12 UTC
**Describe the bug**
Custom Column are always set as a type Float (number).
In version 0.38.3, text fields where identified with the right type and so could be filtered.
This is not possible anymore in version 0.39.0.1

**To Reproduce**
In sample dataset "Products", create a Custom Column "= [Category]" and Visualize the result.

**Expected behavior**
We should be able to filter Custom Column as text strings

**Screenshots**
![image](https://user-images.githubusercontent.com/70358310/115526580-c0fb9380-a2c2-11eb-965c-0b167c4bdcc8.png)
![image](https://user-images.githubusercontent.com/70358310/115526487-aaedd300-a2c2-11eb-853a-525a64f7344c.png)

**Severity**
Annoying

**Bonus bug**
Also the columns of "Products" must be all selected with "Select All" checkbox or else the Custom Column will not be displayed (not sure if this bug is new or not)

**Comment by flamber** [comment] 2021-04-21 15:18
Hi @MarcSamD 
I'm seeing the same behavior on 0.38.3 (and 0.35.4 for that matter). It has never worked. Duplicate of #13751/#13122.
Could it be that you were summarizing and then trying to filter that aggregation, since that will behave slightly different?
And the bonus sounds like #12395.

**Closed by flamber** 2021-04-21 15:18 UTC
Labels: .Needs Triage, Type:Bug

**Comment by MarcSamD** [comment] 2021-04-22 02:46
@flamber Indeed it seems very similar to the other tickets you mentionned.

There is a "count of row" summarize in my request but I'm not sure what it could have changed.
![image](https://user-images.githubusercontent.com/70358310/115647115-d66dcd80-a355-11eb-806c-34f6ca4e394e.png)

As you can see on the screenshot, I was able in 0.38.3 to filter using the string "Pro" (the filter could be "Is not" then) but now the query fails and the notebook editor will even not allow me to input anything except a number.

Not sure if this help, and anyway no problem to close this ticket as solving  #13751/#13122 will also include my special case.

**Comment by flamber** [comment] 2021-04-22 08:28
@MarcSamD I'm not able to reproduce. I have tried several different ways and database. I would need to see all the metadata in the requests from 0.38.3 and 0.39.0, so I could compare it.
There's a little workaround. When you start filtering, then instead of choosing the Custom Column `Editions (grouped)`, select one of the text columns (eg. `Name` in your case), input the string and click the `< Name` to return to the column list, and then select the `Editions (grouped)`. Now it will have the input you just created, but you will be limited by the operator options, since it won't work for "Starts with" and other string-based operators.
