### ISSUE TITLE
Reduce the use of driver specific tests

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#26316] opened 2022-11-09 15:29 UTC
When writing tests for drivers, we sometimes hardcode the drivers we want to run tests on.

One example that we write tests specifically for mongo https://github.com/metabase/metabase/blob/e193d00f059cf0511b96a408dc863a2adda16865/test/metabase/query_processor_test/alternative_date_test.clj#L234-L240

We should stop doing this and instead abstract these under `driver/supports` with feature flags, there are 2 benefits of doing this:
1. Tests will run for third-party drivers that implement the feature flags
2. FE could use the supports information to enable/disable features based on DB-engine

For more context: https://github.com/metabase/metabase/pull/22313#pullrequestreview-1172544707

**Comment by camsaul** [comment] 2023-03-13 17:33
Closing in favor of #26807

Duplicate of #26807

**Closed by camsaul** 2023-03-13 17:33 UTC
Labels: Type:Tech Debt, .Backend
