### ISSUE TITLE
Option to customize which dashboard tabs are sent in dashboard subscription 

### ISSUE THREAD

**Issue by J-Reichardt** [metabase/metabase#47550] opened 2024-09-03 08:58 UTC
**Is your feature request related to a problem? Please describe.**
Some users are only interested in some tabs in a dashboard, while others are interested in all of them. 

**Describe the solution you'd like**
It would be nice to select which dashboard tabs are to be sent in a subscription mail. Also only filters linked to the chosen tabs would need to be selected.

**Describe alternatives you've considered**
The current working alternative is to create multiple redundant dashboards for each different subscription. This results in a high number of dashboards which all have to be maintained.

**Comment by paoliniluis** [comment] 2024-09-13 22:59
I think this is a dupe of https://github.com/metabase/metabase/issues/36366

**Closed by paoliniluis** 2024-09-13 22:59 UTC
Labels: Reporting/Dashboards, Reporting/Pulses, Type:New Feature

**Comment by MfMark** [comment] 2025-01-28 11:59
We also need this feature of setting subscriptions on specific tabs
