### ISSUE TITLE
Duplicate columns in viz settings additional columns in `master`

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#33562] opened 2023-08-28 18:37 UTC
I'm having trouble reproducing this consistently, but these were the steps I took to trigger it in the first place.

1. New Question > Raw Data > Sample Database > Orders
2. Run query
3. Save as Question "Orders"
4. New Question > Saved Questions > Orders
5. Click little ⚙️ icon
6. Observe duplicate columns:

<img width="326" alt="image" src="https://github.com/metabase/metabase/assets/1455846/88b4b224-cacc-4396-9f07-fff2af18a7c5">

I can't consistently reproduce this, so I'm guessing it has something to do with bad metadata for the saved question that we inadvertently fixed as part of MLv2, or perhaps metadata not being loaded yet (a race condition).

I think once the MLv2 viz settings stuff lands we can close this out if we can no longer repo it. I'm mostly opening it so we can track that there was broken behavior on `master` that MLv2 is fixing.

**Comment by oisincoveney** [comment] 2023-11-08 12:40
Tried to reproduce this error on `0.47.5`, `master`, and #34851 . I can't seem to reproduce it either.

**Comment by npretto** [comment] 2023-11-08 14:59
I also couldn't reproduce it, but isn't there another problem in the screenshot? Shouldn't the first section ("Columns") be populated instead of saying "Add fields.."?

**Comment by uladzimirdev** [comment] 2024-01-24 14:40
I can't reproduce neither on 46.0, nor on master 4c79e00260

**Comment by lbrdnk** [comment] 2024-02-15 13:33
I'm unable to reproduce on master master [d419e9a](https://github.com/metabase/metabase/commit/d419e9acc4109c59878f4b6fc51a86e23f7dc051) and 47.2.

**Comment by perivamsi** [comment] 2024-02-15 14:42
@camsaul are you comfortable closing this now?

**Closed** 2024-05-28 03:30 UTC
Labels: Type:Bug, Priority:P2, .Backend, Querying/GUI, .Wanted: MLv2
