### ISSUE TITLE
Dashboard Cards does not display question names

### ISSUE THREAD

**Issue by vkovalskiy** [metabase/metabase#3187] opened 2016-08-14 15:00 UTC
If this is a bug report, please fill in the blanks:

*  I am using the Chrome Latest browser.
*  My computer's OS is MacBook Air.
*  I'm running Metabase 0.19 on AWS and it is using the Postgres database.
*  My data is in a Postgres database.
*  My Metabase version is 0.19.

Starting from Metabase 0.19 our cards have stopped to show titles (question names), which are vital for understanding the dashboard. Instead they just display Count as a Title.

![metabase](https://cloud.githubusercontent.com/assets/564016/17649939/f1c2037e-6248-11e6-8b08-9ce0bbb7d201.png)

**Comment by salsakran** [comment] 2016-08-14 19:49
dupe of #3169 
Fixed in the latest 0.19.3 patch release.

**Comment by salsakran** [comment] 2016-08-14 19:49
it should go away if you upgrade your instance.

**Closed by salsakran** 2016-08-14 19:49 UTC
