### ISSUE TITLE
Filter values in dropdown are not getting populated in SQL question based dashboard

### ISSUE THREAD

**Issue by vaijayanthisundaram** [metabase/metabase#35852] opened 2023-11-16 10:57 UTC
### Describe the bug

Field filter is showing the values in dropdown in the native SQL query. But when the SQL question is built on top of this (by summarising gender in this example) and then placed on dashboard the dashboard filter does not show the values in the dropdown , only a search box . The SQL question was also converted into a model but still the dropdown does not show up on the dashboard.
Version v0.42.3

Dashboard filter :
<img width="516" alt="Dashboard dropdown filter" src="https://github.com/metabase/metabase/assets/142204309/14fddd29-4cb5-4917-b13e-a93ab9a9a9e1">

The filter showing the dropdown in the underlying sQL query :
<img width="302" alt="SQL question filter" src="https://github.com/metabase/metabase/assets/142204309/5699caec-3c6d-410d-8d72-113d4d26dca5">

### To Reproduce

1. Create a SQL query with a field filter that can show  dropdown values.
2. Build a SQL question on top of 1 by summarizing a categorical value.
3. Place 2 on a dashboard
4. Create a dropdown dashboard filter and link to SQL question

### Expected behavior

Dashboard filter should show a dropdown of values.

### Information about your Metabase installation

```JSON
-Safari 16.4
-Mac OS Ventura 13.3
```

### Severity

Blocking some users

**Comment by paoliniluis** [comment] 2023-11-16 11:06
Please upgrade to the latest version

**Comment by ranquild** [comment] 2024-06-21 02:32
This is expected behavior for SQL queries. Please confirm with product and close.

**Comment by uladzimirdev** [comment] 2024-06-28 19:55
@vaijayanthisundaram I'm closing this issue, feel free to create a new issue if you still have troubles with dashboard filter values populating.

it's a correct behavior, if you want your filter to be populated with a values, please try the following way:

1. create a native (sql) model, edit its metadata so the column is mapped to the corresponding DB column
2. create a question based on your model (model is intended to be a data source)
3. map your question to a dashboard filter - values will be populated

I added a cypress test, which verifies this behavior in https://github.com/metabase/metabase/pull/44927

**Closed** 2024-06-28 21:11 UTC
Labels: Type:Bug, Priority:P2, Querying/Parameters & Variables, .Frontend, .Product Input Needed, .Team/QueryingComponents
