### ISSUE TITLE
ERR_CONNECTION_CLOSED - MB_JETTY_SSL_Port / HTTPS

### ISSUE THREAD

**Issue by nconder** [metabase/metabase#8803] opened 2018-10-29 14:18 UTC
Running this setup on Windows. It seems as if everything is loading/starting up just fine including the cert keystore. Metabase responds fine on port 3000 but when launching HTTPS on 8443 nothing is logged on the console and the browser returns ERR_CONNECTION_CLOSED. 

The only thing that I could think of is that I'm using a wildcard certs is that OK?

Running latest jar on windows

Config:
set MB_JETTY_HOST=revenue.****.com
set MB_JETTY_SSL=true
set MB_JETTY_SSL_Port=8443
set MB_JETTY_SSL_Keystore=C:\keystore.jks
set MB_JETTY_SSL_Keystore_Password=*****
set MB_PASSWORD_COMPLEXITY=normal
java.exe -jar metabase.jar

Console:
 C:\Program Files\Metabase>set MB_JETTY_HOST=revenue.****.com
C:\Program Files\Metabase>set MB_JETTY_SSL=true
C:\Program Files\Metabase>set MB_JETTY_SSL_Port=8443
C:\Program Files\Metabase>set MB_JETTY_SSL_Keystore=C:\keystore.jks
C:\Program Files\Metabase>set MB_JETTY_SSL_Keystore_Password=****
C:\Program Files\Metabase>set MB_PASSWORD_COMPLEXITY=normal
C:\Program Files\Metabase>java.exe -jar metabase.jar

10-29 20:39:30 ←[1mINFO metabase.util←[0m :: Loading Metabase...
10-29 20:39:34 ←[1mINFO util.encryption←[0m :: Saved credentials encryption is D
ISABLED for this Metabase instance.
For more information, see https://www.metabase.com/docs/latest/operations-guide/
start.html#encrypting-your-database-connection-details-at-rest
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (fil
e:/C:/Program%20Files/Metabase/metabase.jar) to constructor java.nio.DirectByteB
uffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.inte
rnal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflect
ive access operations
WARNING: All illegal access operations will be denied in a future release
10-29 20:39:45 ←[1mINFO metabase.core←[0m :: Starting Metabase in STANDALONE mod
e
10-29 20:39:45 ←[1mINFO metabase.core←[0m :: Launching Embedded Jetty Webserver
with config:
 {:port 3000, :host "revenue.****.com", :ssl? true, :ssl-port 8443, :keysto
re "C:\\keystore.jks"}

10-29 20:39:45 ←[1mINFO metabase.core←[0m :: Starting Metabase version v0.30.4 (
8bf182f release-0.30.4) ...
10-29 20:39:45 ←[1mINFO metabase.core←[0m :: System timezone is 'Asia/Bangkok' .
..
WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collec
tion, being replaced by: #'monger.collection/any?
10-29 20:39:48 ←[1mINFO metabase.core←[0m :: Setting up and migrating Metabase D
B. Please sit tight, this may take a minute...
10-29 20:39:48 ←[1mINFO metabase.db←[0m :: Verifying h2 Database Connection ...
10-29 20:39:49 ←[1mINFO metabase.db←[0m :: Verify Database Connection ...
10-29 20:39:49 ←[1mINFO metabase.db←[0m :: Running Database Migrations...
10-29 20:39:49 ←[1mINFO metabase.db←[0m :: Setting up Liquibase...
10-29 20:39:49 ←[1mINFO metabase.db←[0m :: Liquibase is ready.
10-29 20:39:50 ←[1mINFO metabase.db←[0m :: Checking if Database has unrun migrat
ions...
10-29 20:39:54 ←[1mINFO metabase.db←[0m :: Database Migrations Current ...
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration fi
le for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be
found. Skipping.", exception -> null]
10-29 20:39:55 ←[1mINFO db.migrations←[0m :: Running all necessary data migratio
ns, this may take a minute.
10-29 20:39:56 ←[1mINFO db.migrations←[0m :: Finished running data migrations.
10-29 20:39:56 ←[1mINFO metabase.events←[0m :: Starting events listener: metabas
e.events.notifications
10-29 20:39:56 ←[1mINFO metabase.events←[0m :: Starting events listener: metabas
e.events.metabot-lifecycle
10-29 20:39:56 ←[1mINFO metabase.events←[0m :: Starting events listener: metabas
e.events.dependencies
10-29 20:39:56 ←[1mINFO metabase.events←[0m :: Starting events listener: metabas
e.events.activity-feed
10-29 20:39:56 ←[1mINFO metabase.events←[0m :: Starting events listener: metabas
e.events.last-login
10-29 20:39:56 ←[1mINFO metabase.events←[0m :: Starting events listener: metabas
e.events.revision
10-29 20:39:56 ←[1mINFO metabase.events←[0m :: Starting events listener: metabas
e.events.sync-database
10-29 20:39:56 ←[1mINFO metabase.events←[0m :: Starting events listener: metabas
e.events.view-log
10-29 20:39:56 ←[1mINFO metabase.events←[0m :: Starting events listener: metabas
e.events.driver-notifications
10-29 20:39:56 ←[1mINFO metabase.task←[0m :: Loading tasks namespace: metabase.t
ask.send-anonymous-stats
10-29 20:39:57 ←[1mINFO metabase.task←[0m :: Job already exists: metabase.task.a
nonymous-stats.job
10-29 20:39:57 ←[1mINFO metabase.task←[0m :: Loading tasks namespace: metabase.t
ask.sync-databases
10-29 20:39:57 ←[1mINFO metabase.task←[0m :: Loading tasks namespace: metabase.t
ask.upgrade-checks
10-29 20:39:57 ←[1mINFO metabase.task←[0m :: Job already exists: metabase.task.u
pgrade-checks.job
10-29 20:39:57 ←[1mINFO metabase.task←[0m :: Loading tasks namespace: metabase.t
ask.follow-up-emails
10-29 20:39:57 ←[1mINFO metabase.task←[0m :: Job already exists: metabase.task.f
ollow-up-emails.job
10-29 20:39:57 ←[1mINFO metabase.task←[0m :: Job already exists: metabase.task.a
bandonment-emails.job
10-29 20:39:57 ←[1mINFO metabase.task←[0m :: Loading tasks namespace: metabase.t
ask.DynamicClassLoadHelper
10-29 20:39:58 ←[1mINFO metabase.task←[0m :: Loading tasks namespace: metabase.t
ask.send-pulses
10-29 20:39:58 ←[1mINFO metabase.task←[0m :: Job already exists: metabase.task.s
end-pulses.job
10-29 20:39:58 ←[1mINFO metabase.core←[0m :: Metabase Initialization COMPLETE
10-29 20:39:58 ←[1mINFO metabase.metabot←[0m :: Starting MetaBot threads...
10-29 20:39:58 ←[1mINFO metabase.metabot←[0m :: This instance will now handle Me
taBot duties.

**Comment by salsakran** [comment] 2018-10-31 00:58
@nconder it's hard to really do much in the way of helping here as we don't all the details of how your server is configured. I'd suggest moving this discussion over to http://discourse.metabase.com unless you think there's a specific bug. It's more likely someone there is also running on windows and can help you with HTTPS termination.

**Comment by nconder** [comment] 2018-10-31 01:34
@salsakran this is not running on IIS it is all using the default/built-in metabase web server JETTY.?.?. This seems like a bug as the web server is not logging any responses to the HTTPS request via terminal but works fine for HTTP.  
This is the only thing I've configured beside the certificate that is valid. 
Config:
set MB_JETTY_HOST=revenue.****.com
set MB_JETTY_SSL=true
set MB_JETTY_SSL_Port=8443
set MB_JETTY_SSL_Keystore=C:\keystore.jks
set MB_JETTY_SSL_Keystore_Password=*****
set MB_PASSWORD_COMPLEXITY=normal
java.exe -jar metabase.jar

I will carry on to discourse if you think that is where I need to be.

**Comment by camsaul** [comment] 2019-01-03 01:53
```
10-29 20:39:45 ←[1mINFO metabase.core←[0m :: Launching Embedded Jetty Webserver
with config:
{:port 3000, :host "revenue.****.com", :ssl? true, :ssl-port 8443, :keysto
re "C:\keystore.jks"}
```

It looks like `MB_JETTY_SSL_KEYSTORE_PASSWORD` isn't being passed as part of the config.

**Comment by nconder** [comment] 2019-01-13 20:20
@camsaul yes, I'm sure it is being passed if the password is wrong or nothing is passed I receive a password validation error and metabase fails to start.

**Comment by flamber** [comment] 2021-11-11 16:55
A lot has changed since this issue was created. I'm not able to reproduce with 0.41.2

**Closed by flamber** 2021-11-11 16:55 UTC
Labels: OS:Windows, Operation/
