### ISSUE TITLE
Add row numbers to SQL query results

### ISSUE THREAD

**Issue by meagancojocar** [metabase/metabase#25375] opened 2022-09-13 04:03 UTC
**Is your feature request related to a problem? Please describe.**
I'm used to Datagrip and, though minor, Metabase not having row numbers on query results makes a difference for me. I end up having to write in row numbers via a partition which slows down my productivity. (Can't believe this issue doesn't exist already, but yet couldn't find it)

**Describe the solution you'd like**
When you run a SQL query on Metabase it returns the results with row numbers. I.e. If I query the top 100 customers there is a row number from 1-100 so I can easily see which is 20, etc. 

**Describe alternatives you've considered**
None, this seems standard with other tools. 

**How important is this feature to you?**
There is a workaround its just annoying.

**Additional context**
<img width="1417" alt="Screen Shot 2022-09-12 at 9 03 02 PM" src="https://user-images.githubusercontent.com/50200557/189804814-e8f81bfc-8c4c-41bb-9d8c-ce0c6f229f29.png">

**Comment by flamber** [comment] 2022-09-13 07:51
Duplicate of #12551

**Closed by flamber** 2022-09-13 07:51 UTC
Labels: Type:New Feature, .Needs Triage
