### ISSUE TITLE
Display weekly charts in a more intelligible manner

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3449] opened 2016-10-05 03:09 UTC
EG from http://discourse.metabase.com/t/count-by-week-line-graph-x-axes-labels-wrong/731

For most people seeing a metric by week, it's more useful to see month ticks on the x-axis rather than things like "week 40"

**Comment by tlrobinson** [comment] 2016-10-15 00:28
Related to / duplicate of #1665

What do we actually want to do here?

Some options are:

* `23rd - 2015`
* `Week 23 - 2015`
* `23rd week of 2015`
* `Week of Jan 1, 2015`
* `Week of January 1, 2015`
* `January 1 - 8, 2015`
* `December 31, 2015 - January 7 2016` if it spans months/years
* etc

We can also show different things in axis tick labels, tooltips, table cells, etc. Tick labels should be relatively short.

**Comment by salsakran** [comment] 2016-10-15 02:35
Bar charts are the clearest for me, where the x-axis should just be in days with the months labelled, with each bar covering the appropriate days for that week.

I think line charts are a bit weirder, as I'm not sure where the "dot" should be. 

I definitely think that `week 23` isn't super useful as I don't have any anchor for it.

**Comment by tlrobinson** [comment] 2016-10-18 20:24
#2517 is related to this. To summarize, it seems like people tend to expect week numbers to follow the ISO-8601 week number standard (first day of week is Monday and the first week of the year contains January 4th), which is at odds with the US standard of Sunday as the first day of the week.

**Comment by tlrobinson** [comment] 2016-10-18 20:29
Not formatting `week` groupings with week numbers would alleviate that issue, and I don't think the precise first day of week / first week of year matters as much for `week-of-year` groupings (does it?)

Also related, "Allow organizations to determine the start of their week" #1779

**Comment by mazameli** [comment] 2016-10-19 17:11
For the _tooltips_, I _strongly_ want the format, `January 1 – 8, 2015` or `December 31, 2015 – January 7, 2016` if it spans months/years. The important part IMO is showing the exact dates; I'm not hung up on the particulars of the formatting. (E.g., I think it's just as good to write `1/1/2016 – 1/8/2016`, though this does call out the need to allow admins to localize their time/date formats.)

**Comment by c2h5oh** [comment] 2016-11-25 16:58
My $0.02:

1. For week of the year I would stick to ISO-8601 (weeks start on Monday, the first week of the year is the week that contains that year's first Thursday), because this is what any database built-in function is likely to return and what is most likely to be accepted by external apps

2. For week it would be nice to have it configurable, but that can happen with timezone and locale support

3. Labels could use `Jan 25 - Feb 1, 2016`: it's concise, it follows how users are going to be looking at the data most of the time and US population that insists on writing their dates wrong (ref: https://xkcd.com/1179/ ) will not complain. 

4. Tooltips: same as labels, possibly with full months until locale support is done

**Comment by mazameli** [comment] 2017-02-01 00:39
Can we reach a decision on what to do here and implement this change? This continues to drive me nuts.

**Comment by mazameli** [comment] 2017-04-06 19:14
I spent a while looking at how other products handle this, especially GA. Like Sameer said, with bars, the x-axis is in day units, and the width of each bar covers its week's range of days. In GA, the labels are month+year, and as best as I can tell, each tick mark is left-aligned with the position of the first day of that month on the x-axis. Like this:

![bars](https://cloud.githubusercontent.com/assets/2223916/24771169/62f4d702-1ac1-11e7-9bcb-27f306196a41.png)

![bars hover](https://cloud.githubusercontent.com/assets/2223916/24771368/41846faa-1ac2-11e7-9244-2923bbd6d125.png)


For lines, the dots are positioned at the center of the week range (i.e. in the middle of the bar if it were a bar chart):

![larger range](https://cloud.githubusercontent.com/assets/2223916/24771234/a6185d56-1ac1-11e7-9cca-71cbb99ab5f3.png)

I haven't entirely reverse-engineered the logic they're employing for this next example, but one nice thing GA also does is if you're looking at a smaller range of days that span around 3 months, instead of month+year, the x-axis labels are the first day of the week in every-week or every-other-week increments. In this scenario, the x-axis labels are center-aligned with the corresponding dot/bar. Here's an every-other week example:

![small range](https://cloud.githubusercontent.com/assets/2223916/24771354/3264d2c6-1ac2-11e7-8e4c-302bf504d696.png)

**Comment by mazameli** [comment] 2017-04-13 18:13
@salsakran @tlrobinson this might be my #1 pick for a UX issue to add to 0.24 if we have bandwidth, and if the solution I've outlined above seems good to you both.

**Comment by salsakran** [comment] 2017-04-13 18:14
that solution works for me

**Comment by tlrobinson** [comment] 2017-05-03 18:15
@mazameli @salsakran That makes sense for tooltips and axis. What about everything else? (tables, legends, etc)

**Comment by salsakran** [comment] 2017-05-03 18:17
imo for axis, keep it as the start day of the week. For tables. ... ugh.

**Comment by mazameli** [comment] 2017-05-03 21:42
Right now tables display something like `44th - 2016` so I think almost anything would be an improvement, though obviously the problem is keeping the text from being too long. How about `Week of Feb 19, 2017`?. Alternatively `Feb 28 – Mar 6, 2017` (which would be ideally reduced down to `Feb 19–25, 2017` if not crossing months), but could be long, like `Dec 31, 2016 – Jan 6, 2017`.

I'm trying to avoid patterns like `Week of 2/19/2017` because we don't yet have the ability to let users change their preference for displaying dates.

**Closed** 2017-05-05 19:55 UTC
Labels: Enhancement, Timezones/Calendars, UX, Visualization

**Comment by alberthkcheng** [comment] 2018-12-04 08:36
The week format looks ok in question page, but when i add it into a dashboard, I still see this:
```
45th - 2018
46th - 2018
```
