### ISSUE TITLE
Visualizations only showing date and not time in the tooltips

### ISSUE THREAD

**Issue by Tadimsky** [metabase/metabase#12370] opened 2020-04-21 20:46 UTC
**Describe the bug**

I have a timeseries area and line chart that uses this to get the time:

```sql
SELECT TO_TIMESTAMP_NTZ(CONVERT_TIMEZONE('America/Los_Angeles', run_time)) AS run_time,
```

However, the chart does not show any time information, only the date:
![image](https://user-images.githubusercontent.com/1149244/79911518-58d75080-83d5-11ea-8533-ab50a655be77.png)

I have the setting on the X axis to show the time:
![image](https://user-images.githubusercontent.com/1149244/79911563-6987c680-83d5-11ea-8c42-8863d83aa8cc.png)

If I change my time to do a date_trunc to the minute, then I do see the time on the chart:

```sql
SELECT date_trunc('minute', TO_TIMESTAMP_NTZ(CONVERT_TIMEZONE('America/Los_Angeles', run_time))) AS run_time,
```
![image](https://user-images.githubusercontent.com/1149244/79911650-8c19df80-83d5-11ea-8a03-e9155b242c92.png)

However, that's not accurate enough for me and if I go down to the second, then I go back to the previous error:

```sql
SELECT date_trunc('seconds', TO_TIMESTAMP_NTZ(CONVERT_TIMEZONE('America/Los_Angeles', run_time))) AS run_time,
```
![image](https://user-images.githubusercontent.com/1149244/79911717-a653bd80-83d5-11ea-917a-46c9f7965fb0.png)

So I'm not quite sure why I cannot see the correct date information.

If I render it as a Table, then I see the current times.

It looks like the data passed into the Visualization contains the correct dates:
![image](https://user-images.githubusercontent.com/1149244/79912021-36920280-83d6-11ea-8ffe-20521f19a6cf.png)

**To Reproduce**
Plot a line chart with timestamps that have millisecond times.

**Expected behavior**
See the actual times (including the desired display format of the time) on the tooltip.

**Screenshots**
See above.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 80
- Your operating system: OSx
- Your databases: Snowflake
- Metabase version: 0.34.3
- Metabase hosting environment: Docker

**Comment by flamber** [comment] 2020-04-21 20:51
Duplicate of #11435 - upvote by clicking :+1: on the first post

**Closed by flamber** 2020-04-21 20:51 UTC
Labels: .Duplicate

**Comment by Tadimsky** [comment] 2020-04-21 20:54
Looks like it's this code here that is setting the minimum resolution to minutes. https://github.com/metabase/metabase/blob/1d9368c2826d12f2c9ece335c4e10861acc8cec9/frontend/src/metabase/visualizations/lib/timeseries.js#L80
