### ISSUE TITLE
Forward project a trend line in a metabase graph

### ISSUE THREAD

**Issue by mjcam** [metabase/metabase#12898] opened 2020-07-11 10:39 UTC
We use metabase to track income levels throughout the month or quarter by recording the daily value of all scheduled monthly payments. We can add a trend line but only for those values already recorded. We want to be able to extend the trendily to the end of the month to give us a projection based on daily growth.

Currently, we extract the data and plot it in excel which then allows us to forward project the trend line but it would b great to see this info on the dashboard in metabase

This feature is important to us as we use projections a lot in the business and want to base it on a trend rather than a guess.

**Comment by flamber** [comment] 2020-07-11 11:02
Duplicate of #5889
Related to #9170

**Closed by flamber** 2020-07-11 11:02 UTC
Labels: .Needs Triage, Type:New Feature
