### ISSUE TITLE
Filter box in table has horizontal scroll

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#31339] opened 2023-06-05 20:35 UTC
### Describe the bug

When filtering a field that has long strings, the filter box creates an unnecessary horizontal scroll.

### To Reproduce

1. Sample database -> People
2. Password (long strings field): filter by this column
3. Is: "8bee" or any known value (dont copy and paste)
4. Horizontal scroll

<img width="544" alt="Screenshot 2023-06-07 at 5 43 39 PM" src="https://github.com/metabase/metabase/assets/132273646/6ef8a49a-b8b6-45f8-bdfa-14b700d5a90d">

### Expected behavior

No horizontal scroll

### Information about your Metabase installation

```JSON
v1.46.4
```

### Severity

Minor

**Comment by kamilmielnik** [comment] 2023-07-04 11:50
I can't reproduce this particular issue anymore.
The filter box auto-resizes itself based on its content ([screenshot](https://github.com/metabase/metabase/assets/6830683/d2f2977e-6837-4b83-8ee5-02aa54e289d9)). I tried many resolutions.

The worst I get sometimes is horizontal scrollbar being there when it should not: [screenshot](https://github.com/metabase/metabase/assets/6830683/e4449846-2981-49f8-9bc2-89252ecb7ad3). This is a P4 though.

**Comment by kamilmielnik** [comment] 2023-07-04 12:09
Almost entirely fixed by #30778 (epic PR: #30273): https://github.com/metabase/metabase/pull/30778/files#diff-89a7618bee1f2fef73cc32c099003ae01e40091305fb1980199340f6a6551a86R158.

I'll submit a PR for the redundant scrollbar, although it is different scrollbar than originally reported: [screenshot](https://github.com/metabase/metabase/assets/6830683/cc237127-9cf6-478c-8f88-b1f45e9f34e9).

**Closed** 2023-07-05 07:43 UTC
Labels: Type:Bug, Priority:P3, Querying/Parameters & Variables, .Frontend, Visualization/Tables, .Team/42 :milky_way:
