### ISSUE TITLE
Table conditional formatting allowing to format a column based on a condition applied to another column

### ISSUE THREAD

**Issue by nick-holaemi** [metabase/metabase#16774] opened 2021-06-25 16:03 UTC
Currently, the conditional formatting on tables only allows conditions based on the column on which the format will be applied. However, it would be super helpful to be able to apply format to a column based on a condition applied on another column.

Eg: format the order column green if the column named order_weekly_variation is greater than 20%.

This would help introduce contextual data using the format instead of including it directly into a table as separate values.

**Comment by flamber** [comment] 2021-06-25 16:09
Duplicate of #15523

**Closed by flamber** 2021-06-25 16:09 UTC
Labels: .Needs Triage, Type:New Feature
