### ISSUE TITLE
Return to dashboard button on questions

### ISSUE THREAD

**Issue by Dynnammo** [metabase/metabase#17876] opened 2021-09-14 09:47 UTC
**Is your feature request related to a problem? Please describe.**
When I'm on a dashboard, and I want to correct a specific question, I click on it and correct it, but it's troublesome to then come back to the dashboard it belongs to.

**Describe the solution you'd like**
Having a "Return to dashboard" button near the collection and database icon, like this
![metabase](https://user-images.githubusercontent.com/33259633/133235166-5c2063bc-5739-4bea-be89-8bbcba448b54.png)
(please note that this button should be a dropdown to come back at the right dashboard if many dashboards include that question)

**Describe alternatives you've considered**
None.

**How important is this feature to you?**
Not so important, but can save tremendous time when fine-tuning dashboards.

**Additional context**
Please put a :+1: instead of `+1` comments or `updates?`

**Comment by flamber** [comment] 2021-09-14 10:06
Duplicate of #15624

**Closed by flamber** 2021-09-14 10:06 UTC
Labels: Type:New Feature, .Needs Triage
