### ISSUE TITLE
Issue displaying charts with date interval in SQL

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#5422] opened 2017-07-05 07:29 UTC
There is an issue with charts (bar, line, area) being suddenly displayed with dates up to e.g. December 2017 on the x-axis and wrong data points, when changing the time interval (SQL contains this: "WHERE orderedAt > cast(date_trunc((DATE_SUB(CURRENT_DATE, INTERVAL 24 week)), week) as timestamp"). 
The query result is displayed correctly if changed to table format, but is randomly messed up in any graph, while it used to work well before (see examples attached).
![screenshot](https://user-images.githubusercontent.com/24734846/27824696-986ec65e-60ad-11e7-8914-fa09efa2c3f1.jpg)

I cannot figure what it is that is messing it up, it still works for example with an interval of 30 or 12 weeks, but not with 24 weeks. No pattern that is obvious to me and the same happens if the interval is changed to month or year, it works for some values and not for others, a rather bizarre behaviour.
Not very convenient for showing it on Dashboards!

Thanks in advance for looking into this!

Your browser and the version: Chrome Version 58.0.3029.110 (64-bit)
Your operating system: Windows 10
Your databases: BigQuery
Metabase version: 24.2
Metabase hosting environment: Heroku

**Comment by flamber** [comment] 2019-02-22 18:00
This looks related to or possibly duplicate of #3842

**Comment by flamber** [comment] 2020-05-29 20:49
Closing in favor of #3842

**Closed by flamber** 2020-05-29 20:49 UTC
Labels: Database/BigQuery, Priority:P2, Query Builder, Type:Bug, Visualization/
