### ISSUE TITLE
Enable to change what is in columns to rows and rows to columns for every visualization

### ISSUE THREAD

**Issue by MrMauricioLeite** [metabase/metabase#2371] opened 2016-04-18 22:50 UTC
Very often I find myself trying to replicate some analysis that we have today out of metabase and can't find how (if there is any way) to switch rows with columns.

That would be useful has it often affects how the data is graphed and how it's displayed on table mode. Also there is something that the pulse should not mess with, I think.

What do you guys think about it?

**Comment by tlrobinson** [comment] 2016-04-18 22:51
Duplicate of #2338?

**Comment by agilliland** [comment] 2016-04-18 23:27
Lets keep this as a separate issue and track it more like an RFE.  #2338 will be addressed separately.

**Comment by salsakran** [comment] 2017-04-17 18:48
closed via the data tab of the new visualization settings panel.

**Closed by salsakran** 2017-04-17 18:48 UTC
Labels: Proposal/Being Discussed, Visualization/Chart Settings
