### ISSUE TITLE
Reports in metabase not matching downloaded version

### ISSUE THREAD

**Issue by GeorgeVragalev** [metabase/metabase#36028] opened 2023-11-22 11:38 UTC
### Describe the bug

Reports are not matching in metabase when using custom naming and visualization settings with the reports that download in CSV format.
On latest instance which has the problem with custom filtering
I checked using docker the latest image
the downloaded report doesn’t match the one that is being shown in metabase 
![reports](https://github.com/metabase/metabase/assets/78079918/4cf504cb-d452-4451-80fe-21fd8e831d72)

So we are using custom columns and custom column names
We are changing the name of the column and saving, but it doesn't reflect on the downloaded csv.

### To Reproduce

1. Go to 
Metabase any 
2. Change column name
![image](https://github.com/metabase/metabase/assets/78079918/226b82e2-844d-43e4-8fc1-fbf9636b60d4)

3. Save and Download the csv

4. The column name doesn't match

Also creating custom column names with Questions and not SQL will have the same affect

### Expected behavior

Column names should match

### Information about your Metabase installation

```JSON
latest image
 Postgres and MSQL server for metabase
```

### Severity

Client is complaining about this issue

**Comment by paoliniluis** [comment] 2023-11-22 22:16
duplicate of https://github.com/metabase/metabase/issues/17753

**Closed by paoliniluis** 2023-11-22 22:16 UTC
Labels: Type:Bug, .Needs Triage

**Comment by attaxia** [comment] 2023-11-23 10:17
@paoliniluis I'm not sure it's correct to close this one. We noticed this as a regression here as well. 
We have some processes with scripts that import the CSV files downloaded from certain questions, which get data based on the column names. These used to match what's on screen. This was last used a month ago, so I can't pinpoint the exact version with the regression, but now this process broke because the column names in the CSV no longer match what's on screen.
