### ISSUE TITLE
Hide password extension on query editor 

### ISSUE THREAD

**Issue by maximepvrt** [metabase/metabase#19223] opened 2021-12-06 15:57 UTC
**Describe the bug**
If an password extension is activated on browser, every inputs on the editor load password extension.

![Capture d’écran 2021-12-06 à 16 54 20](https://user-images.githubusercontent.com/1840026/144878397-851b378e-0e2f-40b1-b4f6-1cb82cc83da1.png)

Can you add `autocomplete="off"` (https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#values) ont inputs ?

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 96 + 1Password extension
- Your operating system: Mac OS 
- Metabase version: v0.41.2

**Comment by flamber** [comment] 2021-12-06 16:15
Seems like a bug in 1Password rather than Metabase. I'm sure there's a setting somewhere in 1Password, so you can disable it.

**Comment by dpsutton** [comment] 2021-12-06 16:20
> Can you add autocomplete="off" (https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#values) ont inputs ?

From that link (emphasis added):

>  In most modern browsers, setting autocomplete to "off" will **not** prevent a password manager from asking the user if they would like to save username and password information, or from automatically filling in those values in a site's login form. See the autocomplete attribute and login fields.

That suggestion will not accomplish what we want according to that link.

**Comment by maximepvrt** [comment] 2021-12-10 11:32
Password managers still use `autocomplete="off"` for some cases https://1password.community/discussion/comment/621899#Comment_621899

**Comment by iethree** [comment] 2022-04-20 20:19
can't seem to reproduce on current chrome release + 1password extension

**Comment by flamber** [comment] 2022-04-20 20:22
Let's close this, since it's likely fixed by the extension at some point.
If someone is still having problems, then provide the OS, browser, browser version and extension version - and a screenshot of where the password manager interferes with Metabase.

**Closed by flamber** 2022-04-20 20:22 UTC
Labels: Type:Bug, Priority:P3, .Frontend
