### ISSUE TITLE
Audit on who Inserted/Edited Data via Actions

### ISSUE THREAD

**Issue by cons-barathan** [metabase/metabase#35734] opened 2023-11-15 05:35 UTC
**Is your feature request related to a problem? Please describe.**
The new Metabase feature enable access for Users to edit the backend data. But we have no knowledge on Who edited the data. I believe it is crucial to track who edited what data as a Audit

**Describe the solution you'd like**
Whenever user perform any edit via Action button, it should be Audited, on what action used, what is before and after change, who edited the data. For every record

**Describe alternatives you've considered**
I tried to check the Metabase Logs if somewhere it is being logged but I am not able to find anything. The logs "Action" and "Query Action" just gives the list of action created but no knowledge on when it is used, who used, what change has been done to data.

**How important is this feature to you?**
Audit is feature is crucial for any data edit application. So I beleive this is not only crucial for us. But for whoever uses the Data edit feature

**Additional context**
It would be greate if the Data Audit feature is provded soon. Atleast log on who executed the Action, What was before and After would be really grateful

**Comment by paoliniluis** [comment] 2023-11-15 13:51
duplicate of https://github.com/metabase/metabase/issues/29027

**Closed by paoliniluis** 2023-11-15 13:51 UTC
Labels: Type:New Feature, .Needs Triage
