### ISSUE TITLE
Pulses sent to Slack no longer show the preview / image

### ISSUE THREAD

**Issue by kristian-elder** [metabase/metabase#17350] opened 2021-08-06 10:37 UTC
**Describe the bug**
As of yesterday evening (~7 PM GMT, 5 August), Slack pulses appear to be missing the image/preview that would normally be attached, and instead only shows the link to the pulse/question. This is with no change to Metabase, the pulses in question or (other than auto updates) to Slack.

**Logs**
There's no indication in the logs that anything is different from normal. Pulses still appear in Slack, but without the preview.

**To Reproduce**
1. Setup a slack pulse in Metbase
2. Trigger the pulse / wait for it to appear i Slack
3. Observe that pulse no longer has the preview image

**Expected behavior**
The preview image showing the content of the query behind the pulse is displayed in Slack.

**Information about your Metabase Installation:**

Metabase v0.38.0.1, self hosted under Docker / Kubernets

**Severity**
Currently slowing down company workflows where action is taken based on pulses (and their content)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2021-08-06 10:45
Slack not showing images from Subscriptions/Pulses since 2021-08-06 00:00:00 UTC

Only a link to the question is included:
![image](https://user-images.githubusercontent.com/1447303/128498477-52179579-b7b8-4ad1-843f-ad602c12f4ab.png)

Currently unknown why. There's no errors logged, and Slack does not report any problems.
If it is caused by [workspace deprecation](https://api.slack.com/changelog/2021-03-workspace-apps-to-retire-in-august-2021), then someone at Slack was prematurely removing functionality.

Might be time to looking into migrating to App instead of Bot - #12383

**Comment by dendolder** [comment] 2021-08-06 11:10
Yes, we have the same issue. Slack Bots are also deprecated now.

<img width="1038" alt="Screenshot 2021-08-06 at 13 09 53" src="https://user-images.githubusercontent.com/30436389/128501889-347475cf-61df-409a-a6fd-5ae677682b14.png">

**Comment by flamber** [comment] 2021-08-06 11:19
@dendolder Bots have been outdated for some time, but that doesn't explain why images stopped showing now. See #12383

**Comment by RomantsovArtur** [comment] 2021-08-06 11:43
The same for us. We can see images in the metabase_files channel, but they are not attached to the messages
![image](https://user-images.githubusercontent.com/40241717/128505537-48400e42-21d1-49b3-8a83-2643eaf67115.png)

Timing is the same.

Could slack has changed the expected response and that's why Metabase can't attach the image.

**Comment by flamber** [comment] 2021-08-06 11:46
@RomantsovArtur It's definitely something at Slack that isn't working or have changed, but there's no indication of what/why: https://github.com/metabase/metabase/issues/17350#issuecomment-894174284

**Comment by abdidarmawan007** [comment] 2021-08-06 14:09
its serious issue dude, i have metabase with version 0.36.x, 5 august bot error can't send pulse alert with images, alredy try install new metabase 0.40.2 still same
Has the Metabase team communicated with Slack Team for fix this issue ?

**Comment by evans-mike** [comment] 2021-08-06 15:25
I assumed it was an issue so I upgraded to the latest version of Metabase this morning, and then reset and added a new Slack Token. No fix.

**Comment by azundo** [comment] 2021-08-06 18:23
Just an observation that when this issue first appeared we were not getting any new file uploads in our #metabase_files channel at all, but as of earlier today files are being uploaded again. The image preview is still not appearing in the pulse but hopefully this means that slack is aware of an issue and working on a fix.

**Comment by stringbeans** [comment] 2021-08-06 19:28
yeah we noticed this start to happen just a few days ago as well. as a workaround for now we are letting our team members know to just join the #metabase_files channel to correspond the image with each pulse :+1:

**Comment by alexhocksween** [comment] 2021-08-07 05:43
I sent a support request to Slack. They're
> aware of an issue where attachments-based message payloads are sent with a Slack file image link and don't unfurl

It appears Metabase uses this approach:
```
POST https://slack.com/api/chat.postMessage?token=[REDACTED]
channel:     #metabase_files
username:    MetaBot
icon_url:    http://static.metabase.com/metabot_slack_avatar_whitebg.png
text:        Pulse: test
attachments: [{"title":"People, Filtered by ID","title_link":"http://localhost:3000/question/1","fallback":"People, Filtered by ID","image_url":"https://files.slack.com/files-pri/T0M9D81RR-F02AHDP0XEX/image.png"}]
```

I've asked if they're planning a fix and will update here.

**Comment by safvanplp** [comment] 2021-08-08 10:18
I found this thread luckily today and I also facing the issue for the last two days.
@alexhocksween  Are we lucky to get some more updates from Slack?

**Comment by abdidarmawan007** [comment] 2021-08-09 02:50
@safvanplp im already contact slack support but their response is very slow, already 3 day no updates from them

**Comment by safvanplp** [comment] 2021-08-09 03:33
@abdidarmawan007 do we have a public topic or ticket open with Slack so that all the interested parties can refer to it for the latest updates.

**Comment by abdidarmawan007** [comment] 2021-08-09 03:37
@safvanplp sorry im delete my post

im create ticket with admin account Slack Pro Plan, and ticket not public

**Comment by alexhocksween** [comment] 2021-08-09 06:29
Slack support responded (for the record, they responded very quickly - delay has been on my side).

> I'm afraid that don't have an answer as to whether the team will fix the issue. For context, I know that they had discussed deprecating certain attachments-based messaging features due to the push towards using the new block kit messaging format instead, but this particular feature wasn't specifically mentioned. Additionally, this internal Slack file link unfurling capability isn't available with the new block kit messaging format. I'm still waiting to hear back on their decision.


They proposed an alternate solution:
> send the Slack message permalink for the uploaded image file, into the payload's root text field, that would unfurl the entire contents of the message, including the image

This would involve:
1. From the current `files.upload` response, getting `files.channels[0]` and `files.shares.public.(channel_id)[0].ts`, and sending that to `https://slack.com/api/chat.getPermalink?channel=(channel_id)&(message_ts)`. That will return a permalink.
2. Included the permalink from (1) in the `text` part of the payload to `chat.PostMessages` and including `unfurl_media` and `unfurl_links`, e.g.:
```
{
    "channel": "(detination channel)",
    "text": "Pulse: Test\n Image 1 \n <https://(slack_url).slack.com/archives/C02AHDAU0N7/p1628487076000400|1> \n Image 2 \n <https://(slack_url).slack.com/files/U02AAER7ATG/F02AKGMR3U3/image.png|2>",
    "unfurl_media": true,
    "unfurl_links": true
}
```

This is definitely not as nice as the current approach as it would unfurl the media below all the messages. Titles will no longer display above the corresponding image, so it would probably be preferable to send lots of messages, this is what it would look like:
<img width="480" alt="metabase" src="https://user-images.githubusercontent.com/481637/128667413-a61b2646-8b25-49f6-a2b3-2d82c75e1342.png">


I'm going to respond to support and let them know the workaround is not an ideal one. Will update when I hear back.

**Comment by ampoonia-dc** [comment] 2021-08-09 07:03
I'm facing the same issue here, slack images just stopped working.

**Comment by imjustd** [comment] 2021-08-09 08:03
Same here, as I understand it's a Slack API deprecation, but still Metabase needs to adjust and use a newer approach for uploading files, correct?

**Comment by niteeshhegde** [comment] 2021-08-09 17:48
Looks like Slack has reverted its changes. Images are back now

**Comment by camsaul** [comment] 2021-08-09 18:11
Hi everyone, sorry about the issues with Metabase rendering images on Slack -- before Slack fixed the issue upstream, we were discussing a plan to issue a hotfix to address the issue later today. Now that the issue is fixed upstream, we will continue to monitor the situation and will issue a hotfix if the issue pops up again.

We have some planned work for the upcoming 0.41.0 release to migrate to the latest Slack APIs, and from a legacy Slack Bot to a Slack App. IIRC Bots and Apps require different setup/authentication tokens, so it's not possible to automatically switch our integration from a Bot to an App without requiring reauthentication with Slack. We're working on a way to make the transition as seamless as possible for everyone.

**Comment by flamber** [comment] 2021-08-16 18:15
Closing this, since Slack has fixed their unannounced change and there hasn't been any reports since.
Work on the conversion of Bot to App can be tracked in #12383

**Closed by flamber** 2021-08-16 18:15 UTC
Labels: Type:Bug, Priority:P1, Reporting/MetaBot
