### ISSUE TITLE
0.44.3: Model's fields are duplicated

### ISSUE THREAD

**Issue by a-meledin** [metabase/metabase#25696] opened 2022-09-29 08:51 UTC
Query:
![image](https://user-images.githubusercontent.com/98175818/192984975-88639a96-2ed3-459b-8160-6e26259f10bc.png)
When saved and metadata is assigned from tables referenced in the query:
1. there is duplicate of columns in setting:
![image](https://user-images.githubusercontent.com/98175818/192985395-557c059d-3584-4788-8d79-82771d5d7eee.png)
2. also there is an error message in logs:
![image](https://user-images.githubusercontent.com/98175818/192985679-d9d69812-3021-4edb-bd9e-eeb09755fdad.png)
3. after that column metadata is changed to refer, IMHO, duplicated model field instead of tare_number_registery.tare_number as was set inititally:
![image](https://user-images.githubusercontent.com/98175818/192986017-891aa8d1-77de-4aea-89c1-0f9ab8d1c3cb.png)
4. Diagnostic info
{
  "browser-info": {
    "language": "ru-RU",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "3.10.0-957.12.2.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Europe/Moscow"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.4.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-09-02",
      "tag": "v0.44.3",
      "branch": "release-x.44.x",
      "hash": "7d50282"
    },
    "settings": {
      "report-timezone": "Europe/Moscow"
    }
  }
}

**Comment by flamber** [comment] 2022-09-29 08:54
Duplicate of #23018

**Closed by flamber** 2022-09-29 08:54 UTC
Labels: Type:Bug, .Needs Triage
