### ISSUE TITLE
Cant create Pulse

### ISSUE THREAD

**Issue by sraveh** [metabase/metabase#12602] opened 2020-05-28 07:05 UTC
**Describe the bug**
When creating a new Pulse, or updating exsiting one, I cant select question. 
<img width="721" alt="Screen Shot 2020-05-28 at 12 02 18 AM" src="https://user-images.githubusercontent.com/620609/83109627-8d929380-a076-11ea-91cd-b6acc1eb32f5.png">

**Logs**
05-28 06:50:44 [1mERROR middleware.log[0m :: [31mGET /api/pulse/preview_card_info/220 500 1.9 s (13 DB calls) 
{:message "temporal",
 :type java.lang.NullPointerException,
 :stacktrace
 ["java.util.Objects.requireNonNull(Objects.java:228)"
  "java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1741)"
  "java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)"
  "java_time.format$format.invokeStatic(format.clj:50)"
  "java_time.format$format.invoke(format.clj:43)"
  "--> pulse.render.datetime$reformat_temporal_str.invokeStatic(datetime.clj:14)"
  "pulse.render.datetime$reformat_temporal_str.invoke(datetime.clj:13)"
  "pulse.render.datetime$format_temporal_str.invokeStatic(datetime.clj:33)"
  "pulse.render.datetime$format_temporal_str.invoke(datetime.clj:16)"
  "pulse.render.body$fn__32579$format_cell__32584$fn__32585.invoke(body.clj:48)"
  "pulse.render.body$fn__32579$format_cell__32584.invoke(body.clj:45)"
  "pulse.render.body$fn__32659$query_results__GT_row_seq__32664$fn__32665$iter__32666__32670$fn__32671$iter__32704__32708$fn__32709.invoke(body.clj:110)"
  "pulse.render.table$render_table_body$iter__32493__32497$fn__32498$iter__32531__32535$fn__32536.invoke(table.clj:75)"
  "api.pulse$fn__64069.invokeStatic(pulse.clj:166)"
  "api.pulse$fn__64069.invoke(pulse.clj:159)"
  "middleware.auth$enforce_authentication$fn__66808.invoke(auth.clj:14)"
  "routes$fn__68332$fn__68333.doInvoke(routes.clj:56)"
  "middleware.exceptions$catch_uncaught_exceptions$fn__66907.invoke(exceptions.clj:97)"
  "middleware.exceptions$catch_api_exceptions$fn__66904.invoke(exceptions.clj:85)"
  "middleware.log$log_api_call$fn__68710$fn__68711.invoke(log.clj:197)"
  "middleware.log$log_api_call$fn__68710.invoke(log.clj:191)"
  "middleware.security$add_security_headers$fn__66870.invoke(security.clj:121)"
  "middleware.json$wrap_json_body$fn__68413.invoke(json.clj:64)"
  "middleware.json$wrap_streamed_json_response$fn__68431.invoke(json.clj:100)"
  "middleware.misc$maybe_set_site_url$fn__68740.invoke(misc.clj:59)"
  "middleware.session$bind_current_user$fn__63397$fn__63398.invoke(session.clj:209)"
  "middleware.session$do_with_current_user.invokeStatic(session.clj:184)"
  "middleware.session$do_with_current_user.invoke(session.clj:177)"
  "middleware.session$bind_current_user$fn__63397.invoke(session.clj:208)"
  "middleware.session$wrap_current_user_id$fn__63382.invoke(session.clj:161)"
  "middleware.session$wrap_session_id$fn__63326.invoke(session.clj:125)"
  "middleware.auth$wrap_api_key$fn__66816.invoke(auth.clj:27)"
  "middleware.misc$bind_user_locale$fn__68745.invoke(misc.clj:78)"
  "middleware.misc$add_content_type$fn__68726.invoke(misc.clj:29)"
  "middleware.misc$disable_streaming_buffering$fn__68754.invoke(misc.clj:94)"
  "server$async_proxy_handler$fn__68488.invoke(server.clj:70)"
  "server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)"]}
[0m
05-28 06:51:05 [1mERROR middleware.log[0m :: [31mGET /api/pulse/preview_card_info/220 500 2.3 s (13 DB calls) 
{:message "temporal",
 :type java.lang.NullPointerException,
 :stacktrace
 ["java.util.Objects.requireNonNull(Objects.java:228)"
  "java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1741)"
  "java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)"
  "java_time.format$format.invokeStatic(format.clj:50)"
  "java_time.format$format.invoke(format.clj:43)"
  "--> pulse.render.datetime$reformat_temporal_str.invokeStatic(datetime.clj:14)"
  "pulse.render.datetime$reformat_temporal_str.invoke(datetime.clj:13)"
  "pulse.render.datetime$format_temporal_str.invokeStatic(datetime.clj:33)"
  "pulse.render.datetime$format_temporal_str.invoke(datetime.clj:16)"
  "pulse.render.body$fn__32579$format_cell__32584$fn__32585.invoke(body.clj:48)"
  "pulse.render.body$fn__32579$format_cell__32584.invoke(body.clj:45)"
  "pulse.render.body$fn__32659$query_results__GT_row_seq__32664$fn__32665$iter__32666__32670$fn__32671$iter__32704__32708$fn__32709.invoke(body.clj:110)"
  "pulse.render.table$render_table_body$iter__32493__32497$fn__32498$iter__32531__32535$fn__32536.invoke(table.clj:75)"
  "api.pulse$fn__64069.invokeStatic(pulse.clj:166)"
  "api.pulse$fn__64069.invoke(pulse.clj:159)"
  "middleware.auth$enforce_authentication$fn__66808.invoke(auth.clj:14)"
  "routes$fn__68332$fn__68333.doInvoke(routes.clj:56)"
  "middleware.exceptions$catch_uncaught_exceptions$fn__66907.invoke(exceptions.clj:97)"
  "middleware.exceptions$catch_api_exceptions$fn__66904.invoke(exceptions.clj:85)"
  "middleware.log$log_api_call$fn__68710$fn__68711.invoke(log.clj:197)"
  "middleware.log$log_api_call$fn__68710.invoke(log.clj:191)"
  "middleware.security$add_security_headers$fn__66870.invoke(security.clj:121)"
  "middleware.json$wrap_json_body$fn__68413.invoke(json.clj:64)"
  "middleware.json$wrap_streamed_json_response$fn__68431.invoke(json.clj:100)"
  "middleware.misc$maybe_set_site_url$fn__68740.invoke(misc.clj:59)"
  "middleware.session$bind_current_user$fn__63397$fn__63398.invoke(session.clj:209)"
  "middleware.session$do_with_current_user.invokeStatic(session.clj:184)"
  "middleware.session$do_with_current_user.invoke(session.clj:177)"
  "middleware.session$bind_current_user$fn__63397.invoke(session.clj:208)"
  "middleware.session$wrap_current_user_id$fn__63382.invoke(session.clj:161)"
  "middleware.session$wrap_session_id$fn__63326.invoke(session.clj:125)"
  "middleware.auth$wrap_api_key$fn__66816.invoke(auth.clj:27)"
  "middleware.misc$bind_user_locale$fn__68745.invoke(misc.clj:78)"
  "middleware.misc$add_content_type$fn__68726.invoke(misc.clj:29)"
  "middleware.misc$disable_streaming_buffering$fn__68754.invoke(misc.clj:94)"
  "server$async_proxy_handler$fn__68488.invoke(server.clj:70)"
  "server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)"]}

**Comment by flamber** [comment] 2020-05-28 09:27
Duplicate of #11665

**Closed by flamber** 2020-05-28 09:27 UTC
Labels: .Needs Triage, Type:Bug
