### ISSUE TITLE
unable to remove description of a question

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#4752] opened 2017-04-11 01:22 UTC
Should be reproducible everywhere.

- Save a question with any description
- remove the description and try to save

Gives following error:
![screen shot 2017-04-10 at 5 49 30 pm](https://cloud.githubusercontent.com/assets/1330677/24888780/8ab2ff88-1e1a-11e7-9c57-56fa0374adf3.jpg)

**Comment by adrian17** [comment] 2017-04-11 17:40
(duplicate of https://github.com/metabase/metabase/issues/4738)

**Closed** 2017-04-11 17:55 UTC
Labels: Duplicate
