### ISSUE TITLE
Dates in tooltips off by 1

### ISSUE THREAD

**Issue by dudleycarr** [metabase/metabase#2091] opened 2016-03-05 14:32 UTC
If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is MacOS X Yosemite.
*  My database is Postgresql.
*  My Metabase version is 0.15.

Bar chart with grouping on a timestamp field at a monthly interval shows the wrong month on hover. The count is correct but the date shown is for the previous month.

**Comment by tlrobinson** [comment] 2016-03-05 20:53
Likely a duplicate of #1635 but I'll leave it to remind us to check tooltips once it's fixed.

**Closed** 2016-03-15 16:12 UTC
Labels: Bug, Correctness
