### ISSUE TITLE
Pin map not showing any pin when reach 1000 or more rows of data

### ISSUE THREAD

**Issue by imfaridz** [metabase/metabase#7560] opened 2018-05-07 04:15 UTC
### Bugs
 *Repeatable steps to reproduce the issue*
when I set the data limited to 999 row,
![image](https://user-images.githubusercontent.com/32382632/39684576-1f48c15e-51e7-11e8-81f7-f54b6b70fc48.png)
![image](https://user-images.githubusercontent.com/32382632/39684585-33677806-51e7-11e8-9e2a-98ab07f9eaa2.png)

but the problem occur when I limit the data to 1000 row,
![image](https://user-images.githubusercontent.com/32382632/39684619-67cff7bc-51e7-11e8-9769-d9dcb03b5524.png)
![image](https://user-images.githubusercontent.com/32382632/39684635-7cae917a-51e7-11e8-94ae-c6661d15d9f5.png)

- Your browser and the version: Google Chrome 65.0.3325.181 
- Your operating system: Ubuntu
- Your databases: Postgres
- Metabase version: v0.28.1
- Metabase hosting environment: Docker, Linux/Coreos
- Metabase internal database: Postgres

**Comment by ceyhunkerti** [comment] 2018-10-01 15:50
Any progress for this issue ?

**Comment by emrahgumus** [comment] 2018-10-01 16:12
What is the solution to this bug?

**Comment by emrahgumus** [comment] 2018-10-01 16:13
What is the solution for this bug?

**Comment by pjatx** [comment] 2019-01-17 22:16
Also experiencing this bug : /

**Comment by mazameli** [comment] 2019-01-17 22:38
This appears to be a problem specifically with SQL/native queries. I'm able to create a pin map with a GUI-based question with 2,000 rows. I did reproduced this bug with SQL on master though.

![screen shot 2019-01-17 at 2 38 08 pm](https://user-images.githubusercontent.com/2223916/51353454-8bbdc680-1a65-11e9-8ede-422c315697c0.png)

**Comment by mazameli** [comment] 2019-01-17 22:41
Also, I'm seeing a bunch of server errors like this when trying to use a SQL query with a pin map with more than 999 rows:

```
01-17 14:39:23 DEBUG metabase.middleware :: GET /api/tiles/3/2/2/undefined/undefined/7/8/ 404 (133 µs) (0 DB calls).
"API endpoint does not exist."
```

**Comment by flamber** [comment] 2019-02-11 19:08
I think this is a duplicate of #4394

**Comment by tlrobinson** [comment] 2019-02-14 17:02
Closing as duplicate of #4394

**Closed by tlrobinson** 2019-02-14 17:02 UTC
Labels: Bug, Priority/P2, Query Builder/Native, Visualization
