### ISSUE TITLE
Notify endpoint will always return 200 even if the tables don't exist

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#25627] opened 2022-09-26 14:35 UTC
**Describe the bug**
If you call the notify endpoint with id's or names that don't exist in the payload, the endpoint will return 200 and {"success": true}.
We should be consistent with the error codes and the responses

**Logs**
NA

**To Reproduce**
1) Call the notify endpoint with non-existent id's or names, see it responding ok all the time. It won't do anything

**Expected behavior**
If the table does not exist, we should respond a 500 and the corresponding error message in the payload

**Screenshots**
NA

**Information about your Metabase Installation:**
- Metabase version: 1.44.3
- Metabase hosting environment: Docker

**Severity**
NA

**Additional context**
NA

**Comment by tsmacdonald** [comment] 2022-09-29 09:20
Hey @paoliniluis , I can't reproduce this (on `master`). With a numerical ID that doesn't exist I get `404 Not found` (which seems more correct than a 500), and with a non-numerical ID I get `404 API endpoint does not exist`.

Valid ID:
![image](https://user-images.githubusercontent.com/784417/192993033-58409e38-798b-45a3-8c61-d2a1454230ca.png)

Missing ID:
![image](https://user-images.githubusercontent.com/784417/192993135-a6ab5f33-4257-4127-8da3-7bb0eaf922ce.png)


Non-numerical "ID":
![image](https://user-images.githubusercontent.com/784417/192993250-f842a8ae-5df5-4f8c-af5e-7c56528a3330.png)


And there's [an existing unit test](https://github.com/metabase/metabase/blob/master/test/metabase/api/notify_test.clj#L22) for it.

**Comment by flamber** [comment] 2022-09-29 09:23
@tsmacdonald It's not about the db id, it's the `table_id` or `table_name`.

**Comment by tsmacdonald** [comment] 2022-09-29 14:09
Ack, sorry flamber, thanks for the clarification. Should be fixed in #25703 .

**Closed** 2022-09-30 10:47 UTC
Labels: Type:Bug, Misc/API, .Backend
