### ISSUE TITLE
Email show black cells instead gradient colors

### ISSUE THREAD

**Issue by lpadula** [metabase/metabase#25178] opened 2022-09-01 16:19 UTC
**Describe the bug**
Email reports show black cells instead gradient colors on tables.

**Logs**
Not needed.

**To Reproduce**
1. Create a  new Dashboard.
2. Add a 'question' with table format (at least on column with conditional formatting).
3. Send an email with the report.

**Expected behavior**
Something like this:
![image](https://user-images.githubusercontent.com/1341504/187962478-b478d6e4-32a1-4002-bba8-3e18936287dc.png)

Instead of it:

![image](https://user-images.githubusercontent.com/1341504/187962050-a74761b4-0ad0-4366-9fe6-491e0e629a80.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Mozilla/5.0 (X11; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0
- Your operating system: Manjaro Gnome
- Your databases: MySQL
- Metabase version: v0.44.2
- Metabase hosting environment: Docker
- Metabase internal database: PostgreSQL 14.5

**Severity**
Low?

**Additional context**
No needed.

**Comment by flamber** [comment] 2022-09-02 08:23
Duplicate of #13892

**Closed by flamber** 2022-09-02 08:23 UTC
Labels: Type:Bug, .Needs Triage
