### ISSUE TITLE
[Bug] Horizontal Scaling, turning off Metabase application level cache

### ISSUE THREAD

**Issue by mihirk** [metabase/metabase#6891] opened 2018-02-07 15:43 UTC
I am running Metabase jar on 3 t2.micro instances fronted by an ELB, using RDS Postgres for Metabase's database. I am seeing some erratic behavior across different requests especially along caching of fields, triggering sync of database fields. I believe Metabase maintains an internal application level cache of fields, which is specific to that instance of servlet making it difficult to horizontally scale by just running multiple instances of Metabase on small machines fronted by a load balancer. 

Anyone else notice this issue?

Am I right about it maintaining an application level cache, and is it possible to turn it off?

**Comment by jornh** [comment] 2018-02-07 16:18
> Am I right about it maintaining an application level cache, and is it possible to turn it off?

You're right, and I believe currently the answer is no.

I think this issue is basically a duplicate of the existing feature request in #2754

**Comment by salsakran** [comment] 2018-02-15 21:04
this is a dupe of #2754 

Metabase isn't intended to be horizontally scaled at this point.

**Closed by salsakran** 2018-02-15 21:04 UTC

**Comment by amanmalkar** [comment] 2018-05-02 20:31
@mihirk Hi Mihir could you tell me how are you running multi-instance setup of metabase? Is it via booting the s3 images on BeanStalk and Auto load balancing or did u manually configure the load balancer ?

**Comment by mihirk** [comment] 2018-05-03 05:54
I am running it on t2.micro EC2 Instances. Not using Beanstalk. I use the jar to run it. It is fronted by an ELB.

**Comment by amanmalkar** [comment] 2018-05-03 13:56
@mihirk Thanks a lot for responding.

Are u running it on java7 or java8? I always run into intermittent crashing while running on t2.micro and I was thinking its because t2.micro has weak resources.
