### ISSUE TITLE
Date and time issues v29.3 

### ISSUE THREAD

**Issue by Trashtravis** [metabase/metabase#7890] opened 2018-06-15 09:36 UTC
```

Browser: Firefox 52.7.3 (64-bit)
Metabase: v29.3  (running on Jar application)
DB: MySQL 5.7

Metabase Timezone: default database
MySQL Timezone: System (default system)

My OS: CentOS 7
Metabase Hosting OS: CentOS 7

```
When I select now(), curdate() ;  from metabase
![image](https://user-images.githubusercontent.com/5169793/41460910-6ab04f3e-708e-11e8-8b65-d3a36c2472fe.png)

Directly on the server
![image](https://user-images.githubusercontent.com/5169793/41461071-e011206e-708e-11e8-92ef-231d41cf006b.png)

My queries on metabase show the date time wrong it seems metabase is adding one hour and some cases 2 hours to the actual time when running same query on mysql.

My table is created using timestamp data type in mysql. 

To reproduce that run metabase v29.3 on mysql and compare the select now() and curdate(); with the one in mysql. Also create any table using timestamp data type and with a few rows on it with any date time and compare the results.

Is there any workaround for that? 

I saw many date and time related issues but none of them had a solution was always miscofing between timezones but I am not using any timezone it's all system default. It seems Metabase changes some types of date and time can't figure out what is really going on.

**Comment by mvrabel** [comment] 2018-06-15 14:03
@Trashtravis Is the timezone on your Metabase instance the same as your database timezone ?

**Comment by senior** [comment] 2018-06-15 14:04
I think I know what's going on here. To be sure though, what is your report timezone setting for your Metabase instance? You can find this in the General settings in the admin panel. Also, what is the timezone of the JVM that is running Metabase. This can be overridden via a parameter, but by default will be the system (or container's) timezone.

I think the fix for you will be to specify a report timezone, but you'll hit a bug in 0.29.3 using a native query like the one you used in this original issue. The bug has been fixed in master https://github.com/metabase/metabase/commit/8b6d0cca2c7a05958fb0e5615b05a2a429425199 and will be included in the next release (v0.30.0).

**Comment by Trashtravis** [comment] 2018-06-18 07:08
@senior I am not using any timezone on Metabase is set to database default as the screenshot shows.

![image](https://user-images.githubusercontent.com/5169793/41522291-96679576-72d5-11e8-9641-2deb2e4531a5.png)

When I specify a timezone the date difference adds up even more hours. 

Java is using default system timezone same as MySQL.

I just want to get the raw date time from the database without any interference but it seems Metabase does modify the datetime and timestamp date type when returning a result set.

**Comment by Trashtravis** [comment] 2018-06-18 10:10
I was playing around with timezones on Metabase report timezones what it fix for me was to set timezone to 'UTC' even though I am in 'CEST' on CentOS. 

Curiously on the logs I got this error message:
![image](https://user-images.githubusercontent.com/5169793/41530429-8301af74-72f0-11e8-9fd0-ef0e94047583.png)

**Comment by xjzhou** [comment] 2018-06-28 09:23
when I customized the timezone, I got the erros too.
 [image](https://user-images.githubusercontent.com/1255410/42025664-b60c2386-7af7-11e8-9a77-dd1f628dc639.png)

**Comment by salsakran** [comment] 2018-07-06 04:54
tacking this as a p3 because I believe it's fixed in master, but contains symptoms that might need to be revisited on that version.

**Comment by flamber** [comment] 2021-04-10 14:15
I cannot reproduce this on latest release - 0.38.3 - quite sure this was fixed long ago.
If you are still experiencing this, then please post "Diagnostic Info" from Admin > Troubleshooting, and the timezone information from MySQL server.

**Closed by flamber** 2021-04-10 14:15 UTC
Labels: Misc/Timezones, Priority:P3, Type:Bug
