### ISSUE TITLE
Know how users use metabase？

### ISSUE THREAD

**Issue by annisun2020** [metabase/metabase#14237] opened 2021-01-04 09:27 UTC
Metabase provides some data tables for users to analyze,But we don’t know how users analyze and use metabase.

Is it possible to connect with Google Analytics(GA) to store user behavior data in the database to help administrators provide users with a better analysis experience?

**Comment by flamber** [comment] 2021-01-04 10:54
Hi @annisun2020 
The Enterprise Edition has auditing functionality, which provides more insight: https://www.metabase.com/docs/latest/enterprise-guide/audit.html
Duplicate of #2470/#5462/#7320

**Closed by flamber** 2021-01-04 10:54 UTC
Labels: .Needs Triage, Type:New Feature
