### ISSUE TITLE
After Upgrading to 0.33.6 Existing Charts are broken

### ISSUE THREAD

**Issue by willhurley004** [metabase/metabase#11374] opened 2019-11-22 21:59 UTC
**Describe the bug**
After upgrading from 0.32.7 to 0.33.6 there were a number of errors in existing charts.  Seemed like it was looking back 20 years into the past for the x axis of a time series.  We were able to work around it by switching to ordinal from time series, but this is less than ideal from a UX and developer experience standpoint.  Additionally, now in ordinal mode, the charts display dates at the beginning of unix time when a date is null.   Based on the release notes, my colleague thinks the issue may be related to the fix for #5916 .

**Logs**
No errors or warnings present in either

**To Reproduce**
1. Create a chart which overlays a few questions on a time series on 0.32.x.  
2. Upgrade to 0.33.6.  
3. Have broken charts

**Expected behavior**
Upgrades should not break existing charts.

**Screenshots**
### Broken
<img width="270" alt="Screen Shot 2019-11-22 at 4 48 39 PM" src="https://user-images.githubusercontent.com/10673246/69462802-fad00f80-0d47-11ea-82b1-0ce59f67a6bc.png">
<img width="314" alt="Screen Shot 2019-11-22 at 4 48 20 PM" src="https://user-images.githubusercontent.com/10673246/69462887-379c0680-0d48-11ea-9130-9b3a7bd6ef46.png">
### After workaround
<img width="96" alt="Screen Shot 2019-11-22 at 4 57 24 PM" src="https://user-images.githubusercontent.com/10673246/69463287-34ede100-0d49-11ea-9a41-a0982c2c598b.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36",
    "vendor": "Google Inc."
  }
}
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)
Postgres
**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.
As I said above, we have worked around this issue for the moment, but it is annoying for the data people at my company.  

**Additional context**
Metabase is running in docker/k8s.  It was deployed using helm.

**Comment by paulrosenzweig** [comment] 2019-11-25 20:37
@willhurley004 Thanks for reporting this.

Does the same bug appear when you recreate an identical question on 0.33.6? Also, are the questions querying the same database?

**Comment by willhurley004** [comment] 2019-11-26 21:49
@paulrosenzweig All the questions query a single postgres database with many schemas.  I did not walk back the versions to investigate if this was a recently introduced problem.  I will try and do so during some off hours and let you know the results.

**Comment by paulrosenzweig** [comment] 2019-11-26 22:22
> I did not walk back the versions to investigate if this was a recently introduced problem.

Sorry that's not what I meant. I'm curious whether the issue is specific to the charts you have or caused by the upgrade path. 

If you (while still using 0.33.6) take one of the broken questions and copy the SQL into a new question, does that work? If it's a GUI question rather than a SQL one, I'd try to recreate it with the GUI.

**Comment by paulrosenzweig** [comment] 2019-12-19 14:51
@willhurley004 is this issue still occurring for you?

**Comment by paulrosenzweig** [comment] 2020-01-08 00:36
@willhurley004 I'm going to close this issue since I can't reproduce it. If it's still an issue for you on please reopen.

**Closed by paulrosenzweig** 2020-01-08 00:36 UTC
Labels: Priority:P1, Type:Bug, Visualization/Chart Settings
