### ISSUE TITLE
In Simple Question, making a filter over a PK field only shows the first record

### ISSUE THREAD

**Issue by AMorenoStratio** [metabase/metabase#13959] opened 2020-12-04 13:27 UTC
**Describe the bug**
When I show a table and try to make a filter on a field that is PK, only the first result is shown even if the filter has to return several records. Version is v0.33.2

**To Reproduce**

1. Go to Simple Question
2. Choose the relevant table in our postgresql db
3. Filter by multiples ID (Example: between 1 and 100)
4. See Detail of only one record

**Expected behavior**
See table with only filter records

**Screenshots**
1. Records
![imagen](https://user-images.githubusercontent.com/60425524/101168892-6e377d00-363c-11eb-85cc-0139a9f6fac4.png)

2. Filter (Start with E)
![imagen](https://user-images.githubusercontent.com/60425524/101168954-8b6c4b80-363c-11eb-9c4a-55b1cf06cdc0.png)

3. Result
![imagen](https://user-images.githubusercontent.com/60425524/101169030-a50d9300-363c-11eb-9ead-da950b4cd42b.png)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "es-ES",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_131-b11",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_131",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.131-b11",
    "os.name": "Linux",
    "os.version": "3.10.0-1062.1.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "crossdata",
      "stratiopostgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.2",
      "date": "2020-09-23",
      "branch": "branch-0.39",
      "hash": "f6c1d05"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
- Your browser and the version: Firefox
- Your databases: Postgresql
- Metabase version: 0.33.2

**Comment by flamber** [comment] 2020-12-04 13:37
Duplicate of #13717. Latest release is 0.37.3

**Closed by flamber** 2020-12-04 13:37 UTC
Labels: .Needs Triage, Type:Bug
