### ISSUE TITLE
Bad plot bar clipping when using manual Y range

### ISSUE THREAD

**Issue by adrian17** [metabase/metabase#7747] opened 2018-05-29 14:29 UTC
Example on the screenshot. Visible when I set the min Y value above 0.
The bars overlap with the X axis and labels.

![zrzut ekranu z 2018-05-29 16-29-02](https://user-images.githubusercontent.com/4729533/40665406-6fe3aee4-635d-11e8-91f8-7324294f3b02.png)

Tested on FF 60, Metabase 0.29.3.

**Comment by flamber** [comment] 2019-02-21 21:15
Hi @adrian17 
This is looks like a duplicate of #6547
It seems to be the same problem for line, area, bar, line+bar, when "Auto y-axis range" is off and "Minimum" value is set higher than the minimum values of the data. Tested on 0.31.2

**Closed** 2020-05-29 18:45 UTC
Labels: .CSS, Priority:P3, Type:Bug
