### ISSUE TITLE
Sorting Popover Broken

### ISSUE THREAD

**Issue by fragglebob** [metabase/metabase#4498] opened 2017-03-08 13:48 UTC
The sorting popover seems like it is trying to show the rows that being aggregated, but is failing as you can see the in the screenshot. Then using the broken item seems to do nothing.

However sorting via the table seems to apply a filter that works, but displays an invalid name.

![screenshot from 2017-03-08 13-28-29](https://cloud.githubusercontent.com/assets/551150/23705978/2cfbc63e-0404-11e7-944c-993ec2170bce.png)

The console is also throwing warnings:

Unknown field type:  ["aggregation", 0] query.js:411

- Your browser and the version: Chrome 56
- Your operating system: Ubuntu 16.04
- Your databases: BigQuery
- Metabase version: 0.22.2
- Metabase hosting environment: Ubuntu 16.04
- Metabase internal database: MySQL

**Comment by kdoh** [comment] 2017-03-08 16:55
Thanks for reporting this @fragglebob. Looks like its a duplicate of #3939.

**Closed by kdoh** 2017-03-08 16:55 UTC

**Comment by fragglebob** [comment] 2017-03-08 17:06
Sorry about that, i did try and look to see if someone else had noticed it. Seems I didn't look hard enough.

**Comment by kdoh** [comment] 2017-03-08 17:17
@fragglebob No worries. Lots of issues in there, thanks for trying.
