### ISSUE TITLE
Manually specify JOIN value for polymorphic relationships

### ISSUE THREAD

**Issue by nitsujri** [metabase/metabase#20250] opened 2022-02-04 10:55 UTC
**Is your feature request related to a problem? Please describe.**
https://github.com/metabase/metabase/pull/17633 did a lot of work in bringing in the ability to have multiple JOIN specifications which is absolutely fantastic, but we still cannot write in a manual value which is needed to satisfy polymorphic joins

**Describe the solution you'd like**
Like this https://github.com/metabase/metabase/issues/14061 states an example query is

```sql
SELECT users.*, sum(orders.amount) as total_order_value FROM users
  LEFT OUTER JOIN orders ON orders.orderer_id = users.id AND orders.orderer_type = `User`
  GROUP BY users.id
```

In the example above, Orders can come from users or partners who are different objects/tables in the DB, but we want to list all the users and see their total order value even if it's zero.

**How important is this feature to you?**
Pretty big, a lot of what we do has polymorphic relationships so we write a lot of custom queries instead of using built in expressions/functions. 

The multiple conditions PR was so close to what we were hoping for.

Thanks so much for this fantastic piece of software!

**Comment by flamber** [comment] 2022-02-04 11:16
Duplicate of #1708

**Closed by flamber** 2022-02-04 11:16 UTC
Labels: Type:New Feature, .Needs Triage
