### ISSUE TITLE
Query builder - custom column from substring is treated as a number

### ISSUE THREAD

**Issue by piotrb5e3** [metabase/metabase#14376] opened 2021-01-13 13:57 UTC
**Describe the bug**
When filtering by a custom column that's defined using `substring`, it can not be filtered properly afterwards.
I can see that `concat` has the same problem.

**Logs**
N/A

**To Reproduce**
1. Create new question
2. Add custom column defined as a substring of an exisiting text column
3. Try filtering by value of the custom column
4. It's impossible to specify an exact string value to filter by, the input only allows numbers

**Expected behavior**
I'd like to be able to specify a filter in the same way as it's specified on text columns.

**Screenshots**
![custom_column_def](https://user-images.githubusercontent.com/2026520/104459810-8e4c4b80-55ad-11eb-948e-a8cb9687ba60.png)
![filtering_def](https://user-images.githubusercontent.com/2026520/104459819-92786900-55ad-11eb-89c2-5439cd034265.png)

**Information about your Metabase Installation:**
This was reproduced on a fresh `v0.37.5` docker image.
<details>
<summary>Diagnostic info</summary>

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "5.8.0-36-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-01-05",
      "tag": "v0.37.5",
      "branch": "release-x.37.x",
      "hash": "be537ee"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
</details>

We've originally seen this on our production metabase deployment (v0.37.5) connected with a Postgres instance.

**Severity**
It's blocking one of our core uses for metabase. We'd gladly accept a fix or a workaround.
We're interested in substrings from the middle of a longer value, so _contains_, _starts with_, _ends with_ are not acceptable substitutes.

**Comment by flamber** [comment] 2021-01-13 14:07
Duplicate of #13751 - also see some of the related issues in that.

**Closed by flamber** 2021-01-13 14:07 UTC
Labels: .Needs Triage, Type:Bug
