### ISSUE TITLE
column names of same, multiple times joined tables in query builder override each other

### ISSUE THREAD

**Issue by mokra** [metabase/metabase#19707] opened 2022-01-15 12:23 UTC
**Describe the bug**
In the Query Builder, if you add the same table multiple times for JOINs and choose the same column for both tables, then in the results view, both columns will have the same name. 
![grafik](https://user-images.githubusercontent.com/1849512/149621476-1ffbee42-6bf1-4a50-8dfd-03c3d2ec46af.png)

If you try to change the name of one column - it will override the name of the other column:

![grafik](https://user-images.githubusercontent.com/1849512/149621513-212e86a7-fab3-4aec-9d2f-4639a58547ae.png)

![grafik](https://user-images.githubusercontent.com/1849512/149621528-1418c2d8-bebe-4a2b-bfcf-45f2ab1c2c44.png)

**To Reproduce**
1. Open the  query builder and choose any table
2. Add join for a table_1 on any column and for the select chooses column_1
3. Add join for a table_1 again on any column and for the select chooses column_1
4. Try to change column names in the result table-view 

**Expected behavior**
Column names should be different

**Information about your Metabase Installation:**
Windows 10, FF: 89
- Metabase version: 0.41.6

**Comment by flamber** [comment] 2022-01-15 12:42
Duplicate of #12685

**Closed by flamber** 2022-01-15 12:42 UTC
Labels: Type:Bug, .Needs Triage
