### ISSUE TITLE
[PIVOT TABLES] Front-end bug that scrolling bar end but has the row totals not showing

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#40787] opened 2024-03-29 15:03 UTC
### Describe the bug

When the pivot table has lots of rows, scrolling down to the end of table not shows the totals, one of the main use of pivot tables
![Screenshot from 2024-03-29 11-56-41](https://github.com/metabase/metabase/assets/6808348/32cd8669-b927-4125-85af-7e61d5baf9b6)

### To Reproduce

1. Create a pivot table lots of rows that need scrolling bar
2. Scroll to the end of the table

### Expected behavior

Show the entire table

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "19+36",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "19+36",
    "os.name": "Linux",
    "os.version": "5.10.0-26-cloud-amd64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "clickhouse",
      "mysql",
      "postgres",
      "cubejs",
      "sqlserver",
      "googleanalytics",
      "athena",
      "bigquery-cloud-sdk",
      "mongo",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-02-22",
      "tag": "v0.48.7",
      "hash": "c192db1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

annoying

**Comment by linucksrox** [comment] 2024-06-15 21:52
Every time I update I hope this has been fixed, but so far no dice. My workaround is toggling table view on and then back off (the button in the bottom center) and then it works as expected, just not on a fresh page load.

**Comment by EmmadUsmani** [comment] 2024-07-18 22:20
@dannyeuu @linucksrox This was likely fixed by https://github.com/metabase/metabase/pull/44514, as I'm no longer able to reproduce it in master, see the comparison below. You should no longer experience this issue after upgrading to the latest v50 minor release.

**48.2**

https://github.com/user-attachments/assets/a2a3885d-fc96-49ae-9472-a87871be5322

**master (commit df2d409)**

https://github.com/user-attachments/assets/2afa9eb8-1667-4a77-81be-f037e78a51e8

**Closed by EmmadUsmani** 2024-07-18 22:20 UTC
Labels: Type:Bug, Priority:P2, .Frontend, Visualization/Tables, .Already Fixed, .Team/DashViz

**Comment by dannyeuu** [comment] 2024-07-18 23:26
Great! Thanks!

**Comment by linucksrox** [comment] 2024-07-18 23:53
Thanks! Looks like it's fixed for me on the latest version.
