### ISSUE TITLE
Data display on dashboard

### ISSUE THREAD

**Issue by 100n0m3** [metabase/metabase#3817] opened 2016-11-26 13:08 UTC
Data show on dash, example i want to click on a bar and see the raw data on a new table or window with the content of the bar.
![sem titulo](https://cloud.githubusercontent.com/assets/13314118/20640548/27ec73be-b3c8-11e6-927f-f25be82bb40d.png)
this already exist?
there is a way to implement?

**Comment by machupichu** [comment] 2016-11-28 10:32
This would make a huge difference in ters of UX imo. Would make the charts way more user friendly for non techy end userss! +1

**Comment by mazameli** [comment] 2016-11-28 18:14
I think this is either related to or is a duplicate of #1884.

**Comment by 100n0m3** [comment] 2016-11-28 18:30
Exactly!

**Comment by lanner22** [comment] 2016-11-29 18:29
Actually, I think that what  @100n0m3 needs is something like a report of the clicked element.

For [example](http://www.highcharts.com/demo/column-drilldown), when clicking on the 'Chrome' bar, instead of showing another bar graph with the versions, it must appear the list of users who used Chrome, with various information, etc.

Correct me if i am wrong.

**Comment by mazameli** [comment] 2016-11-29 22:53
Yeah, if you read some of salsakran's comments in #1884, the challenge is that either of those behaviors (zooming in on a more granular bar graph vs. displaying the table of the underlying data for a specific bar) are legitimate expectations a user could have for what should happen when they click. So our current approach is to try and automatically come up with a sensible set of "next questions" for cases like this. You can see the progress of this approach in #3079.

**Comment by camsaul** [comment] 2016-12-13 02:34
@mazameli so... is this a dupe of #1884?

**Comment by flamber** [comment] 2020-02-22 20:51
Duplicate of #1884

**Closed by flamber** 2020-02-22 20:51 UTC
Labels: .Proposal, Reporting/Dashboards
