### ISSUE TITLE
When visualizing timestamp data and group it by month, March appears twice

### ISSUE THREAD

**Issue by fbonawiede** [metabase/metabase#10777] opened 2019-09-01 20:39 UTC
**Describe the bug**
When visualizing timestamp data and group it by month, March appears twice. And October is sometimes not visible.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. open a table with timestamp data
2. Create a graph and group by month
3. See error

**Screenshots**
<img width="1624" alt="Screenshot 2019-09-01 at 22 29 14" src="https://user-images.githubusercontent.com/691791/64081947-1f4bbb00-cd08-11e9-8a3d-1d22a0a3bcaa.png">
And its corresponding table
<img width="232" alt="Screenshot 2019-09-01 at 22 27 04" src="https://user-images.githubusercontent.com/691791/64081948-21ae1500-cd08-11e9-93b7-e91f4c7fbb41.png">

Another example
<img width="1620" alt="Screenshot 2019-09-01 at 22 38 06" src="https://user-images.githubusercontent.com/691791/64082023-36d77380-cd09-11e9-97b9-9bcf66b0cf86.png">
And its corresponding table
<img width="571" alt="Screenshot 2019-09-01 at 22 38 16" src="https://user-images.githubusercontent.com/691791/64082024-38a13700-cd09-11e9-92b1-c16730c240fa.png">

**Information about your Metabase Installation:**
- Your browser and the version: Chrome Version 76.0.3809.132 (Official Build) (64-bit)
- Your operating system: OS Mojave, v 10.14.6
- Your databases: Postgres
- Metabase version: v0.33.0
- Metabase hosting environment: Docker
- Metabase internal database: H2 (default)

**Severity**
How severe an issue is this bug to you? Annoying

**Comment by flamber** [comment] 2019-09-02 01:13
Hi @fbonawiede 
Looks like a duplicate of #5916 - if you agree, then upvote by clicking :+1: and close this issue.

**Closed** 2019-09-02 04:10 UTC
Labels: Type:Bug
