### ISSUE TITLE
Modifying pivot chart breaks it and the query cant be used

### ISSUE THREAD

**Issue by Filip-Djokovic** [metabase/metabase#32429] opened 2023-07-17 10:10 UTC
### Describe the bug

We were using sql query editor. With the data set we created a pivot chart. It works fine, but when you modify the chart in any way (we added a new field to the rows or change the order of the fields) everything breaks, we cant use the data anymore, cant query it or revert the changes. Then, I created a new query (that is exactly the same as before) and it works, but again, if you change the pivot chart in any way, it breaks and we cant use that sql query but have to recreate it.
I suspect it has something to do with metadata. 

### To Reproduce

1. Create any query in sql editor (could also be the case with questions, but in this case we couldnt do it in questions)
2. Create a pivot chart, it should work at first
3. do any modification, we first added a new field, second time we changed the order of fields
4. Pivot chart should be broken now, and when you inspect the page it says metadata issue. 

### Expected behavior

it shouldnt break after modifying pivot in a chart

### Information about your Metabase installation

```JSON
- chrome Version 114.0.5735.198 
- macos 13.2.1 (22D68)
- redshift
```

### Severity

it is an inconvenience, it probably has deeper issues that we didnt encounter.

**Comment by paoliniluis** [comment] 2023-07-17 11:48
I'm not able to reproduce your issue by following the instructions. I created the following SQL question:
```
SELECT
  "People - User"."SOURCE" AS "People - User__SOURCE",
  "PRODUCTS__via__PRODUCT_ID"."CATEGORY" AS "PRODUCTS__via__PRODUCT_ID__CATEGORY",
  SUM("PUBLIC"."ORDERS"."TAX") AS "sum",
  SUM("PUBLIC"."ORDERS"."TOTAL") AS "sum_2",
  SUM("PUBLIC"."ORDERS"."DISCOUNT") AS "sum_3"
FROM
  "PUBLIC"."ORDERS"
 
LEFT JOIN "PUBLIC"."PEOPLE" AS "People - User" ON "PUBLIC"."ORDERS"."USER_ID" = "People - User"."ID"
  LEFT JOIN "PUBLIC"."PRODUCTS" AS "PRODUCTS__via__PRODUCT_ID" ON "PUBLIC"."ORDERS"."PRODUCT_ID" = "PRODUCTS__via__PRODUCT_ID"."ID"
GROUP BY
  "People - User"."SOURCE",
  "PRODUCTS__via__PRODUCT_ID"."CATEGORY"
ORDER BY
  "People - User"."SOURCE" ASC,
  "PRODUCTS__via__PRODUCT_ID"."CATEGORY" ASC
```

but I can't turn that into a pivot table viz, as I need to create a GUI question first

can you post the exact reproduction steps? Otherwise I'll have to close the issue

**Closed** 2023-08-01 12:54 UTC
Labels: Type:Bug, .Needs Triage
