### ISSUE TITLE
add support for marking a Field as 'monetary' so that we can format it accordingly

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#650] opened 2015-07-12 20:18 UTC
as a user I often have columns and output where I am displaying money values such as revenue and cost.  it would be nice if I could simply identify when a column/Field is monetary and then all the output is automatically treated appropriately.

**Comment by camsaul** [comment] 2016-01-20 20:35
Closing as a duplicate of #1522. This is an older issue but that one has a lot more activity on it

**Closed by camsaul** 2016-01-20 20:35 UTC
Labels: duplicate, proposal
