### ISSUE TITLE
Data Model column type sort

### ISSUE THREAD

**Issue by enqueue** [metabase/metabase#9768] opened 2019-04-12 06:48 UTC
The sorting of the special column types in a table's data model maintenance is not intuitive to me. Perhaps there is some scheme, but I fail to see it. Unless a more structured approach is taken, e.g. by explicitly grouping column types semantically, I would suggest to sort the types alphabetically.

![Screenshot_20190412_083852](https://user-images.githubusercontent.com/5407006/56017458-98b62300-5cff-11e9-9f5f-9403d997252e.png)

**Comment by mazameli** [comment] 2019-05-13 20:58
Agreed. I'm going to call this a duplicate of https://github.com/metabase/metabase/issues/7586 though.

**Closed by mazameli** 2019-05-13 20:58 UTC
