### ISSUE TITLE
It is difficult to tell what is today's date from the query date picker

### ISSUE THREAD

**Issue by gvohra** [metabase/metabase#10115] opened 2019-06-08 22:48 UTC
1. Open the date picker on a query or dashboard
2. Try to determine what *today's* date is

Expected: It is easy
Actual: It is hard

![image](https://user-images.githubusercontent.com/11955301/59153007-e485ff80-8a04-11e9-9489-e9083b435adf.png)

This could be a very simple design tweak to improve

**Comment by mazameli** [comment] 2019-06-10 16:33
Thanks for pointing this out! The `expected` and `actual` gave me a good chuckle, too. :D

**Comment by mazameli** [comment] 2019-06-10 16:38
Actually, @gvohra, I'm not able to reproduce your screenshot with the latest version of Metabase. Here's what I'm seeing. Which version are you on?

![image](https://user-images.githubusercontent.com/2223916/59210785-3fce0400-8b63-11e9-9e4e-a8edfe495507.png)

![image](https://user-images.githubusercontent.com/2223916/59210819-4f4d4d00-8b63-11e9-824b-7c28f92b01d0.png)

**Comment by flamber** [comment] 2019-06-10 18:02
@mazameli I think this is specific to the Single Date selector in Native Query. Either filter with simple Date or Field Filter with Single Date:
![image](https://user-images.githubusercontent.com/1447303/59215845-8ded0280-8b77-11e9-97fb-54fee3554fd9.png)

**Comment by mazameli** [comment] 2019-06-11 00:14
Ahhh, thanks, Flamber!

**Comment by paulrosenzweig** [comment] 2019-08-28 23:36
Resolved by #10137. A fix for this will be in 0.33.1.

**Closed by paulrosenzweig** 2019-08-28 23:36 UTC
Labels: CSS, Query Builder/Native, Type:UX
