### ISSUE TITLE
Stacked bar graph is rendered as unstacked bar graph in e-mail/slack subscription 

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#30315] opened 2023-04-24 12:55 UTC
### Describe the bug

Stacked bar graph gets rendered as a grouped bar graph instead

### To Reproduce

1. Go to New -> Question -> Orders -> Count -> Grouped by created_at: month and Product -> Category -> Visualize as Stacked Bar chart

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/110378427/234001836-677a060a-01ee-46fe-a910-ab534f78e6b3.png">

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/110378427/234001990-da9ed010-61be-4554-bef1-7ff621da9e98.png">

2. Add it to a Dashboard -> Subscriptions -> Send test e-mail .. Notice how the bar chart gets unstacked

<img width="670" alt="image" src="https://user-images.githubusercontent.com/110378427/234002210-8acc03d2-58bd-4bc6-80da-75c603917526.png">

### Expected behavior

Stacked bar graph gets rendered correctly

### Information about your Metabase installation

```JSON
Replicate on both 1.46.1 and master
```

### Severity

 .

**Comment by luizarakaki** [comment] 2023-05-24 17:54
Moving this to the backlog. This issue is important and we need to fix it. But we are reconsidering our static viz strategy. So it is better to understand the future of the feature before working on this particular instance.

**Comment by accesstechnology-mike** [comment] 2023-09-18 11:28
Hello, I can confirm this behaviour and am seeking a fix.

Chart in Metabase:

![image](https://github.com/metabase/metabase/assets/55278705/a62d279d-37a4-43b1-9568-3bdf6374ac04)

Result in Slack report:

![image](https://github.com/metabase/metabase/assets/55278705/b9d97ffe-6388-4983-9dbf-aab890974c02)

**Closed** 2024-05-13 14:07 UTC
Labels: Type:Bug, Priority:P3, Visualization/Charts, Visualization/Static, .echarts-scope, .Team/DashViz

**Comment by OdinTallBeard** [comment] 2024-05-29 10:16
This is still a massive problem.

My organization is debating terminating our metabase and finding a different platform with this as the biggest reason why.

I have weekly reports that go out where the chart in my metabase dashboard can have a max value of 7% and the chart looks fine but in the email for whatever reason the max is 12% and its just a bunch of empty space making it a poor looking chart.

This is such an unbelievably important feature and since its been over a year I think you guys need to prioritize fixing this as it makes all the hard work we do in the dashboards in metabase less impressive with these poor reports.

Please fix this or find a better solution.

I don't think Metabase is scaleable based soley on this issue of reports in slack / email not being authentic to the dashboard I created.

**Comment by Tony-metabase** [comment] 2024-05-29 10:19
Hi @OdinTallBeard most of those visualization issues when you compare email vs metabase should be ironed out with Release 50. Test out release 50 which should be out soon in a couple of weeks and if you still have an issue we can open this or something similar if its a different viz issue
