### ISSUE TITLE
i18n for "Previous" is not working

### ISSUE THREAD

**Issue by renatocron** [metabase/metabase#15330] opened 2021-03-25 03:40 UTC
Word "Previous" is not working for pt.po

![image](https://user-images.githubusercontent.com/1919076/112415182-27ac8200-8d02-11eb-8bb7-e57ab2cdc532.png)

But this i18n is included 5 months ago

https://github.com/metabase/metabase/blob/master/locales/pt.po#L5551
 

I'm running version v0.38.2 Built on 2021-03-17, via docker

**Comment by flamber** [comment] 2021-03-25 09:06
Duplicate of #8964 - it's a regression since 0.37.0

**Closed by flamber** 2021-03-25 09:06 UTC
Labels: .Needs Triage, Type:Bug
