### ISSUE TITLE
CSV/Excel attached file in Pulses is truncating to 2000 rows.

### ISSUE THREAD

**Issue by prashuchaudhary** [metabase/metabase#7622] opened 2018-05-11 08:03 UTC
Support CSV/XLSX attachments in Pulses/Subscriptions with more than 2,000 rows (unaggregated, or 10,000 rows if aggregated).

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by prashuchaudhary** [comment] 2018-05-11 08:04
@senior please check this. A change was made in 0.28.6 release regarding pulse table column limits

**Comment by senior** [comment] 2018-05-11 14:03
I think you're referring to this PR https://github.com/metabase/metabase/pull/7074. That dealt specifically with the columns and rows that are displayed in the Pulse email, not the CSV attachment. As far as I know, we have had a limit of 10,000 rows and that didn't change. I'm not aware of that value being 20,000 for CSV attachments.

When you run the query via the UI on version 0.28.1 and 0.29.0, do you get the same results? I'm wondering if maybe there was another change that caused your query results to be different.

**Comment by prashuchaudhary** [comment] 2018-05-14 05:32
@senior i checked for CSV attachments, I was able to send CSV attachment with number of rows upto 20K (19982 to be precise)

**Comment by prashuchaudhary** [comment] 2018-05-15 04:13
@senior any update on this ??

**Comment by senior** [comment] 2018-05-15 14:47
I haven't had time to try and reproduce the issue. It would be helpful to get more troubleshooting information, such as what we asked in the original issue template that you removed. Specifically what database you're querying against would be helpful. Are you able to get 20k rows from other databases? Does the query return more than 20k and we're truncating it at 20k (or 19982)?

All of these things will help me try and narrow where the change occurred.

**Comment by prashuchaudhary** [comment] 2018-05-15 15:25
I am querying **Redshift** to extract data and send it in attachment form. I had previously deployed Metabase version **0.28.1**. And **0.29.0** is the currently deployed version. The query is returning more than 20K rows in the previous version. Only in the currently deployed version (0.29.0) it is truncating it at 10k. I did not query other databases.

**Comment by senior** [comment] 2018-05-25 14:15
The 10,000 row change happened in https://github.com/metabase/metabase/pull/7022/files. One of the commits I had this in the commit message:

    This commit also limits all queries to 2000 rows, similar to how queries
    issued via the UI are constrained. Users wanting more than 2000 rows
    use the existing export functionality.

I think the reason we made the change was that it made pulses more consistent with the rest of the application (using the same defaults). In testing with @maz we found it easy to hit attachment size limits with our mail provider (maybe Amazon SES) with a row limit so high. Since those files were pretty large, we thought exporting was a better solution to that problem.

**Comment by mazameli** [comment] 2018-05-25 16:48
@prashuchaudhary Just confirming what @senior said about email testing: we chose the trade off of decreasing the limit of rows in a csv so that emails would be less likely to fail. We're sensitive to keeping users from accidentally sending enormous emails.

Could you explain your use case in more detail to me? Are you for example trying to send a very large list of data to external customers or stakeholders who don't have the ability to log in to your Metabase instance to see the full results?

**Comment by prashuchaudhary** [comment] 2018-05-26 04:36
@senoir thanks a lot. I checked the entire code myself and found out the case. For now, we sending the Pulse mail with 10k rows, and anyone who wants to entire data  can download it.

**Comment by prashuchaudhary** [comment] 2018-05-26 04:40
@mazameli Only our internal business and marketing teams are using Metabase. They all have access to Metabase. It's just that before upgrading to Metabase 0.29, we were able to send 20K rows in Pulse and after upgrade it got limited to 10k. So I raised the issue to know the reason behind this change.  
After reading the proposal for adding CSV/Excel attachments to Pulse mail, i finally understood the reason.

Thanks a lot

**Comment by mazameli** [comment] 2018-05-29 16:12
@prashuchaudhary Got it. Thanks for the additional info!

**Comment by ccadenel** [comment] 2018-06-02 08:13
It could be nice to have the information that file (xlsx, csv) is truncated in the body of the pulse email.  

A result can have 9900 lines one day and 10 100 the day after. The user receveiving the pulse have to know that result is truncated.

Depending on need, it would be nice to have an option to choose by pulse, the maximum number of rows to include.

**Comment by Tim-The-Third** [comment] 2018-07-03 11:48
Also an issue for our usecase, at least the ability to set a limit from the admin side would be a nice middle ground (truncate at 30k rows etc.) at least then I could test before setting it up (e.g this report times out at 25K rows so this should be a weekly report)

**Comment by nskalis** [comment] 2018-07-04 07:29
indeed, sane defaults with the ability to override (per use-case / pulse) would be a nice to have

**Comment by minhdaltix** [comment] 2019-06-14 11:06
Right now the attachment files (both csv and xls) are capped at 2000 rows, which is definitely not enough for us. This would force the recipient to click on the direct link to metabase question, and only then be able to download the whole dataset. Would it be possible to increase this cap? Even if we'd have to pay for it?

**Comment by tsadauskas** [comment] 2019-06-19 08:20
Would you consider including this into the project if someone would implement and PR this feature?
Basically the general idea would be to keep the 2K default, but add a configuration option in the UI.

**Comment by mialitman** [comment] 2019-07-22 17:34
I also second the notion of wanting more rows in the pulse. I created a Google app script to push this data into a google spreadsheet. I use the data along with other excel formulas/joins, but need all of the data to be sent.

**Comment by Tim-The-Third** [comment] 2019-08-23 12:37
Its a shame this hasn't gotten more traction, for auto dispatched reports we are definitely going to have to move away from metabase 😞 .

**Comment by kevinconroy** [comment] 2019-09-19 00:09
Given the changes since 0.32.x which applied the 2k limit from the UI to the Excel file exports, I think there should be increased emphasis placed on either (a) allowing for customized/override size parameters for pulses or (b) letting people modify the limits in the admin console.

In prior versions, Pulses allowed more rows. Recent changes to apply the max limit more consistently makes sense from a tech point of view, but NOT from the end user's view. A file that you get emailed to you shouldn't be different from a file that you can download. I appreciate the technical differences, but our end users don't care about that. The 2,000 limit on the view has FORCED them to use CSV and Excel files as workarounds to the UI limitations. Applying the UI limitations to the file exports just frustrates teams who want to access their full data sets.

**Comment by TheCondorman** [comment] 2020-02-11 22:37
Any plans on allowing this? Currently people are moving to sending screenshots of dashboards with files attached manually to get a better experience.

**Comment by darkhelmet** [comment] 2020-02-26 21:11
I've hit this too and had to jump through some hoops because of the 2K limit in email alert exports.

**Comment by maurociancio** [comment] 2020-03-06 13:52
I also want a custom option to allow sending more that 2K in attachments.

**Comment by remis87** [comment] 2020-04-14 06:42
This limitation should be removed, It is kind of disappointing that this is arbitrarily enforced.

**Comment by catabram** [comment] 2020-05-04 19:27
Hi, 

please add an ability to send more than 2k rows

**Comment by davidburke** [comment] 2020-05-11 16:09
This is an excellent feature but we also cannot use it due to the 2k row limitation. Perhaps for pulses run monthly or less, the limit could be much higher?

**Comment by notrom** [comment] 2021-06-02 23:03
@flamber this limitation of 2000 rows in attachments has flowed through to Dashboard subscriptions, there's a little info icon that says this when you're setting it up, but nothing in either the email or the CSV file attached.

I'd prefer either a much higher limit (same as normal CSV export) or a configurable limit on each subscription.

2000 feels arbitrary and low. Today I hit a wall where my data is around 2050 rows, limit of 2000 leads to misleading results when 2000 is within the "expected" row count.

**Comment by kumarjoshi** [comment] 2021-11-02 17:38
Will the 2000 rows limit be removed anytime soon?

**Comment by kevinconroy** [comment] 2021-11-02 20:09
If anyone else is experiencing limitations from this, we had to fork Metabase and make a patch for pulses to expand the total rows. We've still got hard-coded limits, but this patch file (attached) allows you to set any arbitrary limit just for pulse attachments, keeping your web interface quick and snappy.

We have not yet successfully ported this to dashboard subscriptions, so welcome any tips or input on how to adapt this approach for that.

Of course, I'm still in favor of making this a feature, but if anyone else can benefit from the patch in the short term, it's attached. (Note: There are a few Eclipse project files that are added by the patch. You can ignore those if you aren't using Eclipse)

[patch.diff.zip](https://github.com/metabase/metabase/files/7463729/patch.diff.zip)

**Comment by rohetoric** [comment] 2021-11-09 15:18
@flamber this seems quite a recurring issue with everyone.
Truncating at 2k rows doesn't carry the whole dataset in cases where rows exceed 2k.

It would be great if we could manually set the limit in Pulse settings.

**Comment by paoliniluis** [comment] 2022-05-31 21:07
Hi @M1n3lysp, please contact us to the support email so we can help you

**Comment by JadAbdallah** [comment] 2022-11-14 17:14
@flamber  Hello! Reading through this thread and not seeing any solution/resolution. Was this voted against? This is a requirement for us as well.

**Comment by paoliniluis** [comment] 2023-06-22 02:15
If someone needs to change this, you need to tweak https://github.com/metabase/metabase/blob/c9e67486044f02c0196acdf1bb43f36b1eb4f625/src/metabase/query_processor/middleware/constraints.clj#L8

This will also tweak the number of rows that any question returns as default

**Comment by paoliniluis** [comment] 2023-06-22 19:50
@darkhelmet just increase or decrese that number and build :)

**Comment by aashishjain09** [comment] 2023-07-17 06:38
@paoliniluis Thanks for the solution! Could you help in locating the file where the suggested change should be implemented?

**Comment by darkhelmet** [comment] 2023-07-24 16:34
@paoliniluis Connecting to the DB and setting this value in the appropriate table was much easier than rebuilding an image and having to maintain that, so I went that route. Does require restarting the server after you change it, but that's fine.

**Comment by paoliniluis** [comment] 2023-07-26 19:02
@darkhelmet can you post the solution here?

**Comment by darkhelmet** [comment] 2023-08-02 15:41
@paoliniluis Well never mind. Turns out that if you set that setting, it will ALSO limit the number of rows when you want to download the XLSX. Have to delete that setting.

(The following isn't directed at you @paoliniluis, I'm just ranting in the same comment)

I don't understand how this is still a thing after 5 years. Why does an analytics tool actively provide incorrect data, with no warning? I'm actively looking for a replacement for Metabase because of this problem. Right now I have people get emailed a report and don't clue in that it's only 2000 rows and then make decisions based on incorrect/incomplete data, or invoice customers based on incomplete data. I have to run around and make sure everybody writing reports and reading reports KNOWS to watch out for the 2000-row limit problem.

**Comment by paoliniluis** [comment] 2024-01-31 21:10
... aaaaand yes, here it is, finally: https://github.com/metabase/metabase/pull/37716

coming to a Metabase near you in 48.5

**Closed by paoliniluis** 2024-01-31 21:10 UTC
Labels: Reporting/Pulses, Type:New Feature, Reporting/Export

**Comment by neilrobert** [comment] 2025-05-26 23:49
I looked at Guthib - seemed to indicate was resolved in 48.5 ?? - but Im not clear how it was resolved ?? We send emails to client every day for their BI purposes - with now  1500 to 1800 rows - so approaching the 2000 limit
