### ISSUE TITLE
Relative date filter with time works in Field Filters different for SQL variables than for GUI

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#38037] opened 2024-01-23 12:49 UTC
### Describe the bug

GUI filters give correct results; the issue comes when filtering with variables in SQL to datetime fields. The results given in each query differ, even though the data, tables, filter configuration, etc are the same.

### To Reproduce (EDIT: Below are easier repro steps)

1. Create a table in a MySQL database with a datetime field. Example SQL below the steps
2. Create a GUI query that shows all the fields, and use the table view to filter the Datetime Field. Select "Specific dates" as the filter type, and select "Add a time". 
3. To filter, select "Between" January 19th 2024 and January 19th 2024, and select an inclusive time for the fields you want (for example, 12:30pm to 5pm). See that the filter works correctly.
4. Now create a SQL question `select * from mytable where {{my_date_filter}}`
5. In the variables menu, select Field Filter as variable type, map it to datetime_field, and select Date filter as the Filter widget type. 
6. Now, filter by the _same_ dates and times that you used in the GUI, Jan 19th, between 12:30 pm and 5pm (inclusive).
7. See that there are no results.

**SQL for step 1**
```
CREATE DATABASE IF NOT EXISTS example_db;
USE example_db;

CREATE TABLE test_table (
    id INT AUTO_INCREMENT PRIMARY KEY,
    datetime_field DATETIME
);

INSERT INTO test_table (datetime_field) VALUES 
('2024-01-19 15:55:00'),
('2024-01-19 16:00:00');
```

This is the SQL generated by the GUI query:
```
SELECT
  `test_table`.`id` AS `id`,
  `test_table`.`datetime_field` AS `datetime_field`
FROM
  `test_table`
WHERE
  (
    `test_table`.`datetime_field` >= convert_tz(
      '2024-01-19 12:30:00.000',
      'America/Argentina/Buenos_Aires',
      @@session.time_zone
    )
  )
 
   AND (
    `test_table`.`datetime_field` < convert_tz(
      '2024-01-19 17:01:00.000',
      'America/Argentina/Buenos_Aires',
      @@session.time_zone
    )
  )
LIMIT
  1048575
```

And this is the query preview for the SQL query:
```
select * from test_table where DATE(`test_table`.`datetime_field`) BETWEEN timestamp '2024-01-19 13:30:00.000'
   AND timestamp '2024-01-19 12:30:00.000'
```

### Expected behavior

Results should be the same?

### Information about your Metabase installation

```JSON
- Metabase 48.3
- MySQL 8.1.0
```

### Severity

P2

### Additional context

Related: https://github.com/metabase/metabase/issues/4284

**Comment by ignacio-mb** [comment] 2024-01-23 18:41
I'm just realizing this has been already reported in https://github.com/metabase/metabase/issues/33492 🤦

**Comment by bshepherdson** [comment] 2024-01-25 14:32
Sorry for the noise. This seemed like it might be a duplicate of #38012 but now I'm not sure. If that bug were behind this, I'd expect the SQL query to show all results, rather than none.

**Comment by ignacio-mb** [comment] 2024-02-07 12:50
@bshepherdson Here are easier reproduction steps with Sample Database (reproduced with Postgres, MySQL and H2, in 48.4):

**To check that it works in GUI**
- Create a GUI question, all from Orders. Filter by the Created AT table, using "Specific Dates" and selecting June 26th and 9-10pm time filter inclusion. You should see 1 result (correct)
![Screenshot 2024-02-07 at 9 43 36 AM](https://github.com/metabase/metabase/assets/132273646/09e66142-cb18-4586-9ca9-d5911328f17b)

**To check that it doesn't works in SQL field filters**
- Now create a SQL `select * from orders where {{field_filter_test}}`, and select Field Filter, map to Created At from Orders, select Date Filter, and select Specific Dates
- Now filter by the same: June 26th and 9-10 pm time filter, you will see 0 results.
![Screenshot 2024-02-07 at 9 49 50 AM](https://github.com/metabase/metabase/assets/132273646/aec4b687-2470-4b95-b49e-ca72a9d8d11b)

**Comment by Tony-metabase** [comment] 2024-02-07 13:45
Also notice the query that is being sent. both in the examples Ignacio shared and the below:

<img width="1160" alt="image" src="https://github.com/metabase/metabase/assets/110378427/29085f5a-ac72-4220-907c-129ba21cced8">

The DATE conversation is stripping the column time information

**Closed** 2024-02-15 17:10 UTC
Labels: Type:Bug, Database/MySQL, Misc/Timezones, Querying/Parameters & Variables
