### ISSUE TITLE
Google Analytics - Viewing Multiple Metrics, Sorting by Metrics

### ISSUE THREAD

**Issue by sharedphysics** [metabase/metabase#5756] opened 2017-08-15 21:21 UTC
1. I'm trying to view multiple metrics at the same time in Google Analytics and I'm running into errors. I tried in query builder and it allows me to add multiple metrics but only displays the first one in results. I checked the SQL query and it confirms that it only loads the first one. I tried editing the SQL query directly, but no results.  Goal was to see pages vs. bounce rate vs. total bounces vs. total pageviews.

![image](https://user-images.githubusercontent.com/5796884/29337090-13c640ba-81de-11e7-8d3c-716579a9564d.png)

Here's what I tried:

(This only shows me the first metric)
```
{
  "ids": "ga:----------",
  "start-date": "90daysAgo",
  "end-date": "yesterday",
  "metrics": "ga:bounces",
  "metrics": "ga:bouncerate",
  "metrics": "ga:pageviews",
  "dimensions": "ga:pagePath",
  "sort": "ga:pagePath",
  "include-empty-rows": false,
  "max-results": 2000
}
```
also

This gives me an error:
```
{
  "ids": "ga:----------",
  "start-date": "90daysAgo",
  "end-date": "yesterday",
  "metrics": "ga:bounces", "ga:pageviews", "ga:bouncerate",
  "dimensions": "ga:pagePath",
  "sort": "ga:pagePath",
  "include-empty-rows": false,
  "max-results": 2000
}
```

Error:
`Unexpected character (',' (code 44)): was expecting a colon to separate field name and value at [Source: java.io.StringReader@7fe0d458; line: 5, column: 43]`

2. I also tried to filter google analytics results to show only results that had `X` number of views but the native query builder is not giving me the option to sort by `at least`, only by queries related to language (i.e., `contains`, `does not contain`). I was able to get the answer I wanted in the SQL builder, but why can't I do it in the native question builder?

Code to sort by sessions #:
`  "filters": "ga:sessions>X",`
Where `X` is the number.

**Comment by mazameli** [comment] 2017-08-15 21:33
Your first issue is a known bug: https://github.com/metabase/metabase/issues/4894

I think number two is a known limitation of the current implementation of the GA driver, but I'm not 100% sure.

**Comment by tlrobinson** [comment] 2018-01-30 11:04
@sharedphysics in your native query example this line isn't valid JSON: `"metrics": "ga:bounces", "ga:pageviews", "ga:bouncerate",`

You want them all as one string joined by commas: `"metrics": "ga:bounces,ga:pageviews,ga:bouncerate",`

I've also implemented a fix for the first part of your issue in #6822.

The second part is a limitation of Metabase's query editor and MBQL in general, we can't filter by aggregation (it's technically possible with nested queries for drivers that support it, but GA isn't one of them)

**Comment by sharedphysics** [comment] 2018-01-30 16:47
Brilliant, thank you! I look forward to the first part being part of the question builder in the future, will use sql queries for now.

**Comment by mazameli** [comment] 2019-06-13 18:52
Closing this because the first item has been fixed, and the second item is a duplicate of https://github.com/metabase/metabase/issues/1207.

**Closed by mazameli** 2019-06-13 18:52 UTC
Labels: Database/Google Analytics
