### ISSUE TITLE
Impossible to reorder columns when some columns are hidden

### ISSUE THREAD

**Issue by alexandre-butynski** [metabase/metabase#33947] opened 2023-09-19 09:48 UTC
**Describe the bug**

Impossible to reorder columns _on a table view_ when some columns are hidden.

**Logs**

No error logs.

**To Reproduce**

1. Create a new question with aggregation or not
2. Hide one column
3. Try to reorder an other column
4. The reorder is not taken into account

**Expected behavior**

We should be able to reorder columns

**Screenshots**

https://github.com/metabase/metabase/assets/671662/c52d972b-f3ad-41e3-8c5b-f0154822924c

**Severity**

Impossible to create usable table when we have a lot of columns.

If it's based on aggregation question, we have to remove all the aggregated columns and then recreate them in the right order. It can double the time to create a single table. 

**Additional context**

We use Metabase Cloud.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8",
    "os.name": "Linux",
    "os.version": "5.10.184-175.731.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-08-15",
      "tag": "v1.46.8",
      "branch": "release-x.46.x",
      "hash": "27a9ec6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by darksciencebase** [comment] 2023-09-25 15:42
Looks like a duplicate of https://github.com/metabase/metabase/issues/29287 which was shipped in 47, and I can't reproduce on `master`. Once the cloud switches to 47, this should work! If it doesn't, please reopen the issue. Have a nice day

**Closed by darksciencebase** 2023-09-25 15:42 UTC
Labels: Type:Bug, Priority:P2, .Team/PixelPolice :police_officer:
