### ISSUE TITLE
"date string" not translated on the horizontal axis

### ISSUE THREAD

**Issue by placaze** [metabase/metabase#13334] opened 2020-10-01 10:13 UTC
**Describe the bug**
The "date strings" are not translated in the horizontal axis of a graph. We can "janvier" in French in the tooltip, but there is "january" in English on the horizontal axis.

![Metabase langue abscisse](https://user-images.githubusercontent.com/57751243/94795620-df10ad80-03dd-11eb-8f0f-2af0192780bf.png)

**Logs**
_Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)_
Not needed in that case?

**To Reproduce**
1. Use a different locale than English
2. Create a SQL question with data like '2019-11', '2019-12', '2020-01', '2020-02', etc.
3. Use "time series" on the horizontal axis
4. Show the histogram

**Expected behavior**
The locale must be applied on the horizontal axis, like the content in the tooltip.

**Screenshots**
_If applicable, add screenshots to help explain your problem._
Pasted above.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox 81
- Your operating system: Windows 10
- Your databases: PostgreSQL 11.9
- Metabase version: v0.36.6
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
_How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely? Note: the more honest and specific you are here the more we will take you seriously._
It's just annoying for the readers. 😄 

**Additional context**
_Add any other context about the problem here._

**Comment by flamber** [comment] 2020-10-01 10:21
Duplicate of #11319

**Closed by flamber** 2020-10-01 10:21 UTC
Labels: .Needs Triage, Type:Bug
