### ISSUE TITLE
Could not save question after moving one column.

### ISSUE THREAD

**Issue by armetiz** [metabase/metabase#23499] opened 2022-06-23 09:23 UTC
**Describe the bug**
I could not save question after moving one column.

**Logs**
```
Form submission error: TypeError: Cannot read properties of undefined (reading 'collection')
    at reducer (schemas.js:76:62)
    at redux.js:163:12
    at combineReducers.js:120:29
    at combineReducers.js:120:29
    at k (<anonymous>:2235:16)
    at D (<anonymous>:2251:13)
    at <anonymous>:2464:20
    at Object.d [as dispatch] (createStore.js:165:22)
    at e (<anonymous>:2494:20)
    at middleware.js:22:18
```

**To Reproduce**
1. Go to any question, I've tested with a simple Question (metabase IDE), one `Data` source, no filter, no custom columns ...
2. Move any column to any position.
3. Click on save "Replace the original question"
4. See error "Sorry, you don’t have permission to see that."

3.bis. Click on save "Save as new question"
4.bis. See error "Cannot read properties of undefined (reading 'id')"

**Expected behavior**
Modification must be saved.

**Screenshots**
![metabase_replace_original_question](https://user-images.githubusercontent.com/1119250/175264571-4647b4e9-f0ff-4cd5-ac47-5f1590dec442.png)

![metabase_save_as_new_question](https://user-images.githubusercontent.com/1119250/175264584-75a544b2-9f00-4c3e-838b-885ab6f1be1b.png)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36   ",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.10.93-87.444.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.27"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.5"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-06-13",
      "tag": "v0.43.3",
      "branch": "release-x.43.x",
      "hash": "c9c7ef0"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
}
```
You can get this information by going to Admin -> Troubleshooting.

- Metabase hosting environment: Docker
- Metabase internal database: MySQL

**Severity**
Annoying some users, because complexe question could not be rearranged to fit our business needs.

**Comment by armetiz** [comment] 2022-06-23 09:35
**Extra information**
I'm not sure this is related, but on a question with about 6 Data source and 1 Custom column, I have an error when trying to "duplicate this question" : `Cannot read properties of undefined (reading 'id')`.

**Comment by flamber** [comment] 2022-06-23 11:03
Duplicate of #22727

**Closed by flamber** 2022-06-23 11:03 UTC
Labels: Type:Bug, .Needs Triage

**Comment by armetiz** [comment] 2022-06-23 12:18
@flamber are you sure about related issue?
I have the problem as administrator. Note that screenshot is showing "Thomas Tourlourat's personal collection" => I am "Thomas Tourlourat".

**Comment by armetiz** [comment] 2022-06-23 12:41
Ok ! you're awesome helping people, good job ;)

AWS WAF has been configured. Thank you.
