### ISSUE TITLE
Odd UX with default parameter values on SQL questions

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4840] opened 2017-04-21 18:43 UTC
If I add a field filter widget on a SQL question by doing something like `[[WHERE {{time}}]]` I'm able to set a default value on that widget and save my question. This is super handy and ends up feeling a lot like using the query builder. 

However if I add that saved SQL question as a card on a dashboard, that default value isn't carried over. More confusingly, if I click on that card, I'm then going to see a different result than I did on the dashboard, because now my default filter _is_ applied.

Forgetting default values for a moment, it also feels a little strange that applying a filter on a SQL question using a filter widget doesn't count as changing the question, meaning that the `save` button doesn't appear, which means a user who's unfamiliar with SQL (or who doesn't have access to the editor) can't fork an existing SQL question filtered down to say a different date and use the new result on their own dashboard.

**Comment by flamber** [comment] 2019-02-14 19:21
Hi @mazameli 
Maybe I'm misunderstanding this, but I cannot reproduce on 0.31.2.
I'm using this SQL, where Field Filter is `CREATED_AT` with a default of `Past 2 Weeks`. Result is `282`.
```SQL
SELECT count(*) AS "count" FROM ORDERS WHERE {{time}}
```
Then I add the card to a dashboard. Result is `282`.
Then I add a filter on the dashboard and change period, gives different results, as expected. Remove filter, result is `282`, as expected.

As for the second part:
I would tend to agree with you, but then the widgets should change the default value - just like it does in QB. Currently SQL and QB are inconsistent.
This test question is defaulted to `Past 2 Weeks`, but when changing via the widget, doesn't change the default value nor gives the `Save` option:
![image](https://user-images.githubusercontent.com/1447303/52811556-05dc6d80-305b-11e9-871d-c9b273254beb.png)
This test question was grouped by Day, then I changed the bottom widget to Hour and it changes the question too and gives me the `Save` option:
![image](https://user-images.githubusercontent.com/1447303/52811282-50111f00-305a-11e9-880e-c707b8df1a6a.png)

**Comment by flamber** [comment] 2020-05-27 11:11
Closing, since most of this is either fixed in 0.35.3 or has different behavior now because of collections

**Closed by flamber** 2020-05-27 11:11 UTC
Labels: Querying/Parameters & Variables, Type:UX
