### ISSUE TITLE
Summarize table action menu spacing is weird

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5043] opened 2017-05-10 00:03 UTC
<img width="379" alt="spacing" src="https://cloud.githubusercontent.com/assets/2223916/25877604/56cef21e-34d9-11e7-9c1e-691f738aa4e2.png">

**Comment by kdoh** [comment] 2017-05-10 00:03
Duplicate of #5021

**Closed by kdoh** 2017-05-10 00:03 UTC
