### ISSUE TITLE
You shouldn't be able to set alerts on models

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#37893] opened 2024-01-18 21:41 UTC
## Context
Models are data sources. You wouldn't set up an alert on a table. That doesn’t make much sense, right? You’d want to set an alert on criteria for existing or new rows on that table, aka a query. Allowing this results in bugs like https://github.com/metabase/metabase/issues/35091.

[More context](https://metaboat.slack.com/archives/C064QMXEV9N/p1705439180887609).

**Comment by yangmingtao** [comment] 2024-01-19 03:30
![image](https://github.com/metabase/metabase/assets/8136462/e52655bf-4ef1-4fbf-b0c4-0ea1f674a260)

**Comment by nemanjaglumac** [comment] 2024-07-16 17:14
The frontend portion of this has been fixed in https://github.com/metabase/metabase/pull/45611.
Re-assigned the issue to the backend team.

**Comment by ignacio-mb** [comment] 2024-10-14 21:11
Can't reproduce this in master. Should we close this?

**Closed** 2024-10-15 15:55 UTC
Labels: Type:Bug, Priority:P2, Reporting/Alerts, .Backend, .Reproduced, Querying/Models, .Team/DashViz

**Comment by nemanjaglumac** [comment] 2024-10-16 07:11
@ignacio-mb @cdeweyx have you seen this comment?
https://github.com/metabase/metabase/issues/37893#issuecomment-2231429159

Have you double checked with the backend team(s) that the proper solution has been implemented?
The reason you can't reproduce it on `master` is because I removed the UI option. But I think we didn't solve the problem on the backend.
