### ISSUE TITLE
Cannot display column with same name when summarize by and custom column is used in the question

### ISSUE THREAD

**Issue by Xlagrap** [metabase/metabase#12198] opened 2020-03-26 22:12 UTC
**Describe the bug**
When creating a question with Summarize By option and a custom column, it's not possible to display two column with the same name.
The preview before the custom column works

**Logs**
Erreur de la requête {:status :failed,
:class java.sql.SQLSyntaxErrorException,
:error "(conn=13158) Duplicate column name 'id'",
:stacktrace
("org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:243)"
"org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)"
"org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)"
"org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:225)"
"org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:145)"
"org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:159)"
"com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)"
"clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1072)"
"clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1066)"
"clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1081)"
"clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)"
"clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)"
"clojure.java.jdbc$query.invoke(jdbc.clj:1126)"
"--> driver.sql_jdbc.execute$cancelable_run_query.invokeStatic(execute.clj:209)"
"driver.sql_jdbc.execute$cancelable_run_query.invoke(execute.clj:198)"
"driver.sql_jdbc.execute$run_query.invokeStatic(execute.clj:223)"
"driver.sql_jdbc.execute$run_query.invoke(execute.clj:219)"
"driver.sql_jdbc.execute$do_with_auto_commit_disabled.invokeStatic(execute.clj:272)"
"driver.sql_jdbc.execute$do_with_auto_commit_disabled.invoke(execute.clj:260)"
"driver.sql_jdbc.execute$do_in_transaction$fn__69387.invoke(execute.clj:277)"
"driver.sql_jdbc.execute$do_in_transaction.invokeStatic(execute.clj:276)"
"driver.sql_jdbc.execute$do_in_transaction.invoke(execute.clj:275)"
"driver.sql_jdbc.execute$run_query_without_timezone.invokeStatic(execute.clj:300)"
"driver.sql_jdbc.execute$run_query_without_timezone.invoke(execute.clj:299)"
"driver.sql_jdbc.execute$execute_query$fn__69410.invoke(execute.clj:338)"
"driver.sql_jdbc.execute$do_with_try_catch.invokeStatic(execute.clj:252)"
"driver.sql_jdbc.execute$do_with_try_catch.invoke(execute.clj:246)"
"driver.sql_jdbc.execute$execute_query.invokeStatic(execute.clj:332)"
"driver.sql_jdbc.execute$execute_query.invoke(execute.clj:325)"
"driver.sql_jdbc$fn__71316.invokeStatic(sql_jdbc.clj:49)"
"driver.sql_jdbc$fn__71316.invoke(sql_jdbc.clj:47)"
"query_processor$fn__46335$execute_query__46340$fn__46341.invoke(query_processor.clj:69)"
"query_processor$fn__46335$execute_query__46340.invoke(query_processor.clj:64)"
"query_processor.middleware.mbql_to_native$mbql__GT_native$fn__37455.invoke(mbql_to_native.clj:40)"
"query_processor.middleware.annotate$result_rows_maps__GT_vectors$fn__40562.invoke(annotate.clj:541)"
"query_processor.middleware.annotate$add_column_info$fn__40468.invoke(annotate.clj:485)"
"query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__41503.invoke(cumulative_aggregations.clj:57)"
"query_processor.middleware.resolve_joins$resolve_joins$fn__43430.invoke(resolve_joins.clj:184)"
"query_processor.middleware.limit$limit$fn__42138.invoke(limit.clj:19)"
"query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__46195.invoke(results_metadata.clj:87)"
"query_processor.middleware.format_rows$format_rows$fn__42126.invoke(format_rows.clj:76)"
"query_processor.middleware.add_dimension_projections$add_remapping$fn__38215.invoke(add_dimension_projections.clj:234)"
"query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__38866.invoke(add_source_metadata.clj:107)"
"query_processor.middleware.resolve_source_table$resolve_source_tables$fn__43480.invoke(resolve_source_table.clj:46)"
"query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__38703.invoke(add_row_count_and_status.clj:16)"
"query_processor.middleware.driver_specific$process_query_in_context$fn__41578.invoke(driver_specific.clj:12)"
"query_processor.middleware.resolve_driver$resolve_driver$fn__43094.invoke(resolve_driver.clj:22)"
"query_processor.middleware.store$initialize_store$fn__46220$fn__46221.invoke(store.clj:11)"
"query_processor.store$do_with_store.invokeStatic(store.clj:46)"
"query_processor.store$do_with_store.invoke(store.clj:40)"
"query_processor.middleware.store$initialize_store$fn__46220.invoke(store.clj:10)"
"query_processor.middleware.async$async__GT_sync$fn__37366.invoke(async.clj:23)"
"query_processor.middleware.async_wait$runnable$fn__40619.invoke(async_wait.clj:89)"),
:query
{:query
{:source-query
{:source-table 287,
:joins
[{:fields [["joined-field" "glpi_plugin_credit_tickets" ["field-id" 578]]],
:source-table 59,
:condition ["=" ["field-id" 2781] ["joined-field" "glpi_plugin_credit_tickets" ["field-id" 575]]],
:alias "glpi_plugin_credit_tickets"}],
:aggregation [["count"]],
:breakout [["field-id" 2781] ["joined-field" "glpi_plugin_credit_tickets" ["field-id" 578]]]},
:expressions {:tst ["field-literal" "count" "type/Integer"]}},
:type "query",
:parameters [],
:async? true,
:middleware {:add-default-userland-constraints? true, :userland-query? true},
:info
{:executed-by 1,
:context :ad-hoc,
:card-id nil,
:nested? false,
:query-hash [95, 26, -38, -89, -93, -123, 15, 27, 37, 54, 62, -118, 57, -11, -12, 80, -77, 54, 50, 25, -95, 78, 104, -21, -96, 123, -68, -26, 107, 30, -110, -50]},
:constraints {:max-results 10000, :max-results-bare-rows 2000}},
:preprocessed
{:constraints {:max-results 10000, :max-results-bare-rows 2000},
:type :query,
:middleware {:add-default-userland-constraints? true, :userland-query? true},
:info
{:executed-by 1,
:context :ad-hoc,
:nested? false,
:query-hash [95, 26, -38, -89, -93, -123, 15, 27, 37, 54, 62, -118, 57, -11, -12, 80, -77, 54, 50, 25, -95, 78, 104, -21, -96, 123, -68, -26, 107, 30, -110, -50]},
:preprocessing-level 1,
:database 2,
:query
{:source-query
{:source-table 287,
:joins [{:strategy :left-join, :source-table 59, :condition [:= [:field-id 2781] [:joined-field "glpi_plugin_credit_tickets" [:field-id 575]]], :alias "glpi_plugin_credit_tickets"}],
:aggregation [[:aggregation-options [:count] {:name "count"}]],
:breakout [[:field-id 2781] [:joined-field "glpi_plugin_credit_tickets" [:field-id 578]]],
:order-by [[:asc [:field-id 2781]] [:asc [:joined-field "glpi_plugin_credit_tickets" [:field-id 578]]]]},
:expressions {:tst [:field-literal "count" :type/Integer]},
:source-metadata
[{:name "id", :id 2781, :table_id 287, :display_name "id", :base_type :type/Integer, :special_type :type/PK, :fingerprint nil, :settings nil}
{:name "id_2", :id 578, :table_id 59, :display_name "glpi_plugin_credit_tickets → id", :base_type :type/Integer, :special_type :type/PK, :fingerprint nil, :settings nil}
{:name "count", :display_name "Nombre de lignes", :base_type :type/Integer, :special_type :type/Number}],
:fields [[:field-literal "id" :type/Integer] [:field-literal "id_2" :type/Integer] [:field-literal "count" :type/Integer] [:expression "tst"]],
:limit 2000}},
:native
{:query
"SELECT `source`.`id` AS `id`, `source`.`id_2` AS `id_2`, `source`.`count` AS `count`, `source`.`count` AS `tst` FROM (SELECT `glpi_plugin_credit_entities`.`id` AS `id`, `glpi_plugin_credit_tickets`.`id` AS `id`, count(*) AS `count` FROM `glpi_plugin_credit_entities` LEFT JOIN `glpi_plugin_credit_tickets` `glpi_plugin_credit_tickets` ON `glpi_plugin_credit_entities`.`id` = `glpi_plugin_credit_tickets`.`plugin_credit_entities_id` GROUP BY `glpi_plugin_credit_entities`.`id`, `glpi_plugin_credit_tickets`.`id` ORDER BY `glpi_plugin_credit_entities`.`id` ASC, `glpi_plugin_credit_tickets`.`id` ASC) `source` LIMIT 2000",
:params nil},
:cause {:class java.sql.SQLException, :error "Duplicate column name 'id'"}}

**To Reproduce**
![image](https://user-images.githubusercontent.com/19491368/77701424-8c7db100-6fb6-11ea-9d04-682656606b09.png)

**Expected behavior**
The query should be displayed with the column I choose.

**Screenshots**
(conn=13696) Duplicate column name 'id'

**Information about your Metabase Installation:**
- Your browser and the version: Chrome/80.0.3987.132
- Your databases: mysql
- Metabase version: v0.34.3. I have tried with 0.35 RC2 same problem
- Metabase hosting environment: Jar-file on Debian
- Metabase internal database: Mysql

**Comment by flamber** [comment] 2020-03-27 17:51
Hi @Xlagrap 
I'm fairly sure this is a duplicate of #10511, which happens after you've added the post-aggregate `tst` Custom Column.

**Closed by flamber** 2020-03-27 17:51 UTC
