### ISSUE TITLE
Altered column in a database to be reflected in Metabase

### ISSUE THREAD

**Issue by FilmonK** [metabase/metabase#35543] opened 2023-11-09 16:09 UTC
**Is your feature request related to a problem? Please describe.**
In the scenario where a user changes the name of a column in their database, eventually does a sync with Metabase, that column is brought in as a new record in the ‘metabase_field’ table.
The questions will still reference the id of the old field until manually updated by the user because there is no historical correlation during a sync. You can't adjust the field in the question, but need to remove it completely and add in the new field.

**Describe the solution you'd like**
The request is to be able to have an option to associate this name change to an existing field.

**Describe alternatives you've considered**

**How important is this feature to you?**
This becomes a time consuming task in the event there are several questions that may be affected by this change.

**Additional context**
<img width="737" alt="Screenshot 2023-11-09 at 10 02 08 AM" src="https://github.com/metabase/metabase/assets/17398657/f0e05440-d6ae-4f22-8239-d45a1193a1ea">

**Comment by pvanderlinden** [comment] 2023-11-13 12:33
This is also a bug: as the interface will partially not work while this field is selected:
- You can't remove the field
- You can't replace the field
- You can't add a field
- You can only remove the whole Summarize section

**Comment by FilmonK** [comment] 2023-11-13 16:22
I’m using postgres as the backend for reproducing this issue, along with a basic question created based off this table.
<br>

<img width="667" alt="Screenshot 2023-11-13 at 10 06 56 AM" src="https://github.com/metabase/metabase/assets/17398657/c21289bd-1e19-433e-b777-2e300d90d7a8">

<img width="981" alt="Screenshot 2023-11-13 at 10 05 36 AM" src="https://github.com/metabase/metabase/assets/17398657/a5e3c6ab-780d-4544-8064-41f679ccf83c">

<br>
<br>

Now change **product_name** to something different like **product_class** within the database.
Sync the database schema.
Make note that the Table Metadata in Admin Settings has been updated and only **product_class** is listed.

Now the question will reference the id of the original field (**product_name**).

<img width="974" alt="Screenshot 2023-11-13 at 10 10 42 AM" src="https://github.com/metabase/metabase/assets/17398657/859649be-37f1-451e-a3fa-912054d8e4b9">

<br>
<br>

You are not able to click on the field and select any other option from the dropdown. You have to remove the entire Summarize section before you're able to use the new field(**product_class**).

**Comment by camsaul** [comment] 2024-06-26 03:34
Duplicate of #10371 (for errors editing the question when the Field disappears) and #12721 (we are considering adding tools to let you automatically replace columns across all of your Saved Questions)

**Closed by camsaul** 2024-06-26 03:34 UTC
Labels: Type:Bug, Priority:P3, Administration/Metadata & Sync, .Product Input Needed, .Team/QueryProcessor
