### ISSUE TITLE
Allow multiple email domains in Google OAuth SSO

### ISSUE THREAD

**Issue by advincze** [metabase/metabase#11625] opened 2020-01-03 14:17 UTC
**Is your feature request related to a problem? Please describe.**
We are using the google oauth login, but our company has two google apps domains 
e.g. user1@foo.com, user2@bar.com

currently i can only sepcify one domain in the google oauth settings (foo.com)

so we have to use email/password authenticaton for our second domain. 
This does not allow offboarding users by removing their google accouts.

**Describe the solution you'd like**
I'd like to be able to specify multiple domains. e.g. comma separated "foo.com,bar.com"

**Describe alternatives you've considered**
our workaround is to use an oauth reverse proxy in front of metabase that supports multiple domains which is not a nice user experience and confusing to half of our users who have to use two different auth mechanisms.

**How important is this feature to you?**
it would simplify our infrastructure a lot and improve the userr experience,

**Additional context**
relevant code:
https://github.com/metabase/metabase/blob/f332b611c464a90027f9960be0b8a1d565ee60ae/src/metabase/api/session.clj#L278

**Comment by flamber** [comment] 2020-01-03 16:21
Hi @advincze 
Sounds like a duplicate of #5218. And there's a PR that never got finished in #7559, so you're welcome to look at the comments and create a new PR.
Please close this issue :+1:

**Comment by walterl** [comment] 2020-01-09 14:22
Duplicate of #5218 (thanks @flamber).

**Closed by walterl** 2020-01-09 14:22 UTC
Labels: .Needs Triage, Type:New Feature
