### ISSUE TITLE
For a new Custom column, I can set Style to "Currency", but cannot choose the Unit of Currency

### ISSUE THREAD

**Issue by EBoisseauSierra** [metabase/metabase#11233] opened 2019-10-30 15:42 UTC
## Bug description
Say I create the _Custom column_ as  `Total Price = Quantity × Unit Price`.

<img src="https://user-images.githubusercontent.com/37387755/67872600-1f124500-fb2a-11e9-9102-c8610c503cef.png" width=400 />

The created metric is a unit-less float.
I want to assign it a (currency). So in table option, I select the column `Total Price` and choose the style _Currency_.

<img src="https://user-images.githubusercontent.com/37387755/67872975-a790e580-fb2a-11e9-8801-2ede3fc95570.png" width=300 />

That all good… except that **I cannot choose which currency to use** (the default is USD, whatever the global default currency chosen in `Admin/Settings/Formatting/Currency/Unit of currency`).

## Expected behavior

I want to be able to chose which currency to use, just like it is possible for columns that have been casted as "Currency" in the Data Model:
<img src="https://user-images.githubusercontent.com/37387755/67873495-706f0400-fb2b-11e9-9471-68d15be12d3c.png" width=300 />

## Metabase Installation:

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_191-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_191",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.191-b12",
    "os.name": "Linux",
    "os.version": "4.13.9-300.fc27.x86_64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.4",
      "date": "2019-10-07",
      "branch": "release-0.33.x",
      "hash": "9559406"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

## Severity
Annoying

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2019-11-07 23:15
Looks like a duplicate of #10787, but the title is probably a little confusing.

**Comment by flamber** [comment] 2019-11-08 13:51
@EBoisseauSierra I did not mean that your title was confusing - it was issue #10787's title :wink: 
But if you agree that this is a duplicate of #10787, then please close this issue.

**Comment by EBoisseauSierra** [comment] 2019-11-08 14:05
Well, to be honest, this issue's title wasn't super clear neither!

Anyway, it seems related, yet do not totally overlap IMHO, as they are focusing on General settings not being applied globally, whereas this issue focus on Custom column and the lack of "Unit of Currency" selector (and not the default value thereof).

So I'd personally keep it open, but I'm happy for you to close it if/when you see fit to do so.

**Comment by EvaSchreyer** [comment] 2020-09-07 12:24
Hi, this problem still exists in v0.35.4, and with my SQL database I can´t even get the currency settings in the visualisation settings when the field is set to currency in the data model.

**Comment by EvaSchreyer** [comment] 2020-09-17 06:32
still an issue in 0.36.6, I am now able to set the data model field settings to currency EUR, but even then I can´t choose the currency in the visualisation settings and the only available currency is $.

**Comment by edgarvonk** [comment] 2021-02-12 15:10
We seem to have the same issue still in v0.37.9. I can change the global currency to EUR but it is not applied to any of our questions and I also cannot select it in the visualisation settings of any question. The only choice remains USD/$.

**Comment by rlotun** [comment] 2021-04-04 06:02
closed by https://github.com/metabase/metabase/pull/15457

**Closed by rlotun** 2021-04-04 06:02 UTC
Labels: .Regression, Customization/Formatting, Priority:P2, Type:Bug
