### ISSUE TITLE
Presto driver reports an error when using variables and there's a question mark (?) in query comments

### ISSUE THREAD

**Issue by OrenLederman** [metabase/metabase#13787] opened 2020-11-13 19:49 UTC
**Describe the bug**
Presto reports the following error when using a variable and there's a question mark (?) in a comment
`line 2:1: Incorrect number of parameters: expected 1 but found 0`

Looking at the code, it appears that the Presto driver attempts to convert prepared statements to a native query (is that what `unprepare` does?). I am guessing that it identifies the question mark in the comment as a parameter and fails to find a suitable value.

**Logs**
```
11-13 19:40:44 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 7,
 :started_at #t "2020-11-13T19:40:44.573Z[Etc/UTC]",
 :json_query
 {:type "native",
  :native
  {:query "select * from public.robot \n-- why?\nwhere name = {{somename}}",
   :template-tags {:somename {:id "a126b442-8500-5a31-efb2-f01deef6bc37", :name "somename", :display-name "Somename", :type "text"}}},
  :database 7,
  :parameters [{:type "category", :target ["variable" ["template-tag" "somename"]], :value "Nova-16-0054"}],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> driver.presto$fetch_next_page.invokeStatic(presto.clj:116)" "driver.presto$fetch_next_page.invoke(presto.clj:112)" "driver.presto$fetch_results_async$fn__500.invoke(presto.clj:154)"],
 :context :ad-hoc,
 :error "line 2:1: Incorrect number of parameters: expected 1 but found 0",
 :row_count 0,
 :running_time 0,
 :ex-data
 {:message "line 2:1: Incorrect number of parameters: expected 1 but found 0",
  :errorCode 80,
  :errorName "INVALID_PARAMETER_USAGE",
  :errorType "USER_ERROR",
  :errorLocation {:lineNumber 2, :columnNumber 1},
  :failureInfo
  {:type "io.prestosql.spi.PrestoException",
   :message "line 2:1: Incorrect number of parameters: expected 1 but found 0",
   :suppressed [],
   :stack
   ["io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)"
    "io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)"
    "io.prestosql.execution.QueryPreparer.validateParameters(QueryPreparer.java:88)"
    "io.prestosql.execution.QueryPreparer.prepareQuery(QueryPreparer.java:80)"
    "io.prestosql.execution.QueryPreparer.prepareQuery(QueryPreparer.java:56)"
    "io.prestosql.dispatcher.DispatchManager.createQueryInternal(DispatchManager.java:179)"
    "io.prestosql.dispatcher.DispatchManager.lambda$createQuery$0(DispatchManager.java:148)"
    "io.prestosql.$gen.Presto_344_e____20201113_061512_2.run(Unknown Source)"
    "java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)"
    "java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)"
    "java.base/java.lang.Thread.run(Thread.java:834)"],
   :errorLocation {:lineNumber 2, :columnNumber 1}}},
 :data {:rows [], :cols []}}
```

**To Reproduce**
1. Create a native query on a Presto database
2. Use the following query (or with any table and catalog):
```
select * from public.robot
-- why?
where name = {{somename}}
```
3. Fill in a value for the variable
4. Run query

Note - I am guessing that you can re-create the error with any database driver that converts prepared statements into native queries 

**Expected behavior**
No error should appear

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_272-8u272-b10-0+deb9u1-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_272",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.272-b10",
    "os.name": "Linux",
    "os.version": "4.19.112+",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "presto",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.19"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.36.6",
      "date": "2020-09-15",
      "branch": "release-0.36.x",
      "hash": "cb258fb"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

**Severity**
Low. This is annoying for users because the cause is not clear, but can be easily fixed by removing question marks for queries

**Comment by flamber** [comment] 2020-11-13 20:02
Duplicate of #10257

**Closed by flamber** 2020-11-13 20:02 UTC
Labels: .Needs Triage, Type:Bug
