### ISSUE TITLE
Group by max date

### ISSUE THREAD

**Issue by daveresbk** [metabase/metabase#13680] opened 2020-11-04 15:12 UTC
**Describe the bug**
When try to use the max function to aggregate, the date fields can't be selected

**Logs**

**To Reproduce**
1. Go to Browse Data
2. Select a Postgres' table
3. Click on Summarize
4. Summarize by Max

Table schema:
COLUMN | DATA TYPE | ADDITIONAL INFO
-- | -- | --
id | type/Integer |  
name | type/Text |  
rate_type | type/Integer |  
rate_price_type | type/Integer |  
payment_type | type/Integer |  
pricing | type/Integer |  
currency | type/Integer |  
rate_allotment | type/Integer |  
rate_allotment_priority | type/Boolean |  
common_allotment_access | type/Boolean |  
allow_shared_allotment | type/Boolean |  
min_stay_for_enty_date | type/Boolean |  
package_only | type/Boolean |  
entry_days | type/Integer |  
out_days | type/Integer |  
week_days | type/Integer |  
ini_date | type/Date |  
end_date | type/Date |  
min_stay | type/Integer |  
priority | type/Integer |  
base_board | type/Integer |  
baby_age | type/Integer |  
first_child_age | type/Integer |  
second_child_age | type/Integer |  
active | type/Boolean |  
binding_price | type/Boolean |  
deleted | type/Boolean |  
added_value | type/Float |  
percentage | type/Decimal |  
market_inclusion | type/Boolean |  
last_update_date | type/DateTimeWithLocalTZ |  
accommodation | type/Integer |  
creation_date | type/DateTimeWithLocalTZ |  
free_sale | type/Boolean |  
delete_date | type/DateTimeWithLocalTZ |  
ini_booking_period | type/Date |  
end_booking_period | type/Date |  
skipped_board_prices | type/Boolean |  
ini_booking_hour | type/Time |  
end_booking_hour | type/Time |  
time_zone | type/Integer |  
release | type/Integer |  
external_id | type/Text |  
channel_manager | type/Integer

**Expected behavior**
Group by Max date field (we only see integer type)

**Screenshots**
![image](https://user-images.githubusercontent.com/32431931/98128548-58595f80-1eb8-11eb-9c0d-a2d23ece1b5e.png)

**Information about your Metabase Installation:**

- Your databases: Postgres
- Metabase version: 0.37.2
- Metabase hosting environment: Ubuntu (on premise)
- Metabase internal database: Postgres

**Severity**
Annoying for not technical users (workaround: make a SQL statement)

**Additional context**

**Comment by flamber** [comment] 2020-11-04 15:25
Duplicate of #4482

**Closed by flamber** 2020-11-04 15:25 UTC
Labels: .Needs Triage, Type:Bug
