### ISSUE TITLE
"Is empty" option filters out only NULL String. Misleading name -- maps to MBQL :is-null -- consider adding :is-empty filter clause

### ISSUE THREAD

**Issue by mvrabel** [metabase/metabase#5299] opened 2017-06-08 09:07 UTC
I have empty strings in my database but when I try to filter out the empty strings with the **"is empty"** option I get **no results**.

When I create pie chart with data from this column I get this:

![empty](https://user-images.githubusercontent.com/12628893/26919587-98aef138-4c36-11e7-9be8-dd342daa7259.PNG)
But when I click "View these XY" I get an error message that says that there was a problem with my question: 
![view_these](https://user-images.githubusercontent.com/12628893/26920497-7e9b94c4-4c39-11e7-970b-10af51376599.PNG)

![filter_empty](https://user-images.githubusercontent.com/12628893/26920651-eceb384e-4c39-11e7-935b-70c6a4895ede.PNG)

```
Jun 08 10:27:54 WARN metabase.query-processor :: Query failure: Valid value (must be nil, boolean, number, string, or a relative-datetime form)
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:159)"
"query_processor$assert_query_status_successful.invoke(query_processor.clj:152)"
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:191)"
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:185)"
"query_processor$fn__26961$dataset_query__26966$fn__26967.invoke(query_processor.clj:223)"
"query_processor$fn__26961$dataset_query__26966.invoke(query_processor.clj:209)"
"api.dataset$fn__28474$fn__28477.invoke(dataset.clj:39)"
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:229)"
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:224)"
"api.dataset$fn__28474.invokeStatic(dataset.clj:33)"
"api.dataset$fn__28474.invoke(dataset.clj:33)"
"middleware$enforce_authentication$fn__38784.invoke(middleware.clj:120)"
"api.routes$fn__38910.invokeStatic(routes.clj:59)"
"api.routes$fn__38910.invoke(routes.clj:59)"
"routes$fn__39540$fn__39541.doInvoke(routes.clj:64)"
"routes$fn__39540.invokeStatic(routes.clj:60)"
"routes$fn__39540.invoke(routes.clj:60)"
"middleware$log_api_call$fn__38883$fn__38885.invoke(middleware.clj:329)"
"middleware$log_api_call$fn__38883.invoke(middleware.clj:328)"
"middleware$add_security_headers$fn__38833.invoke(middleware.clj:243)"
"middleware$bind_current_user$fn__38788.invoke(middleware.clj:140)"
"middleware$maybe_set_site_url$fn__38837.invoke(middleware.clj:266)"]
```

**The Problem is that "Is empty" filter filters only null strings and it can't select "" (empty) strings**.
This is what I get when I click on the "View the SQL" button: 
![view_sql](https://user-images.githubusercontent.com/12628893/26920236-a6ecfaf4-4c38-11e7-81c8-3a7553a80268.PNG)

Is empty: 
`
....
....
WHERE "XX"."YY"."ZZ" IS NULL LIMIT 2000`

Also I get the same error message as above when I try to filter out the rows like this: 
![empty_dropdown](https://user-images.githubusercontent.com/12628893/26920370-1ddbd842-4c39-11e7-8b91-9dbbf5620f8e.PNG)

- *Repeatable steps to reproduce the issue*
Create a table with a column that has "" (empty) string.
Try to filter out that row that has this "" (empty) string.

browser and the version: 58.0.3029.110 (64-bit)
operating system: Win 10
databases: Postgressql 9.6
Metabase version: v0.24.2 Built on 2017-06-01
Metabase hosting environment: CentOS 7
Metabase internal database: I think H2 (default), I only downloaded the jar and conected to the database.

Thanks,
Martin

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by attekei** [comment] 2017-07-27 22:36
I talked about this with @mazameli and we found four distinct issues:
1. QB user interface doesn't have any filter that supports empty strings

2. Query processor shows no sympathy towards empty strings in equality/inequality operators like
`["=", ["field-id", 8696], ""]`; those queries fail to execute

3. Drill-through lets you filter by empty strings although because of (2) the resulting question fails to execute and because of (1) the filter UI of query builder is in a confused state

4. Field value analysis process recognizes nulls but it doesn't recognize empty strings at all (this is relevant only if field's type is Category)

Possible solutions for each of these:
1. "Is Empty" and "Not Empty" filters currently map to `is-null` MBQL operator. For strings, we could  have a new `is-empty` operator which would additionally check if the value is a string with zero length. Other options is to do the same thing in frontend, but from perspective of development bandwidth I think that having a new operator would make more sense.

2. Just fix the query processor =)

3. After (1) and (2) have been done, drill-through should ideally treat empty strings and nulls as `isEmpty` filters but I don't know if that is a stretch

4. Just fix the analysis process =)

**Comment by attekei** [comment] 2017-07-27 22:41
I'm interested to hear thoughts about (1), (2) and (4) from @camsaul

**Comment by camsaul** [comment] 2017-07-27 22:45
1. Adding a new `is-empty` operator isn't needed. Just do `[:= [:field-id <field>] ""]`

2. That can be fixed

4. Not sure empty strings are the sort of things we want to put in categories. Picking a blank value from a filter drop-down sounds weird to me

**Comment by attekei** [comment] 2017-07-27 22:50
@camsaul in (1) the question is more about whether it's 10x faster to implement a new operator to backend (which checks that value is null OR value is an empty string) vs. complicating the filter parsing logic in the frontend

About (3) I agree

**Comment by camsaul** [comment] 2017-07-27 23:13
Ok, it sounds like you want something that is basically

```clojure
[:or [:= [:field-id <field>] ""]
     [:= [:field-id <field>] nil]]
```

Luckily the [`=` filter already has syntactic sugar for doing that](https://github.com/metabase/metabase/wiki/Query-Language-'98#equals-filter) so all you need to do is

```clojure
[:= [:field-id <field>] "" nil]
```

**Comment by mvrabel** [comment] 2017-10-06 14:16
Hi @camsaul @attekei,
Is there any update on this issue ? :)

**Comment by M4zD4i** [comment] 2017-10-19 13:37
Reproduced this issue, in additional I have an error when trying to set filter "Is"->"Empty":
![question metabase 2017-10-19 16-35-50](https://user-images.githubusercontent.com/1096609/31773572-d98a0fd0-b4eb-11e7-92ad-9bc56e0e5180.png)

**Comment by camsaul** [comment] 2017-11-06 02:16
@salsakran "Is Empty" in the Query Builder creates a query with an `:is-null` clause, and the resulting query does in fact filter against values that are not null. So there's a mismatch between what the label says and the query it results in. We either need to change the label to match what it does or change what happens under the hood and produce queries in line with what it suggests it will do

**Comment by mvrabel** [comment] 2017-11-06 08:04
@camsaul Could you add new field in to dropdown menu "is null" ?

**Comment by bcbob** [comment] 2018-01-25 20:48
Has this been resolved?

**Comment by mvrabel** [comment] 2018-01-26 11:59
@bcbob sadly, no  :(

**Comment by epapak02** [comment] 2018-03-07 10:07
Is this been resolved guys ?

**Comment by mvrabel** [comment] 2018-03-07 11:48
@epapak02 Meabase 0.28.1, No :(

**Comment by amit** [comment] 2018-04-05 04:21
0.28.5, not yet :-(

**Comment by probaner** [comment] 2018-04-16 12:15
Me too stuck up in this basic step. need to filter out empty strings.

**Comment by leonardoaranda** [comment] 2018-08-01 13:17
+1

**Comment by bcbob** [comment] 2018-08-09 10:11
Fixing this will be very helpful!

**Comment by mvrabel** [comment] 2018-08-14 12:02
Metabase team ranks issues on number of "👍 " on the first comment. If you want to increase the priority, please, click the "👍 " on the first comment. Thanks 👍 :)

**Comment by Tonkonozhenko** [comment] 2018-08-14 15:27
Hi @mvrabel 
I'd like to contribute on fixing this issue and found that the issue is here:
https://github.com/metabase/metabase/blob/4ffed3bfe38b95550c62e981c8ad0203d045e5c5/src/metabase/query_processor/interface.clj#L325
What about changing it to 
```
(s/named (s/maybe (s/cond-pre s/Bool su/AllowedBlankString OrderableValueLiteral))
```
and adding schema something like
```
(def AllowedBlankString
  "Schema for a string."
  (s/named (s/cond-pre s/Str) (tru "String")))
```
?

**Comment by mvrabel** [comment] 2018-08-14 15:59
Hi @Tonkonozhenko,
Create a pull request for this fix.
I'm not metabase dev, nor contributor. I just read regulary what happens here.

P.S. Thanks for finding this ! I was too lazy to search for it.

**Comment by mvrabel** [comment] 2018-11-16 14:10
@camsaul Hi, is there any update on this ? 

> Ok, it sounds like you want something that is basically
> 
> ```clojure
> [:or [:= [:field-id <field>] ""]
>      [:= [:field-id <field>] nil]]
> ```
> 
> Luckily the [`=` filter already has syntactic sugar for doing that](https://github.com/metabase/metabase/wiki/Query-Language-'98#equals-filter) so all you need to do is
> 
> ```clojure
> [:= [:field-id <field>] "" nil]
> ```

@Tonkonozhenko even create a PR for this.

Thanks,
Martin

**Comment by tlrobinson** [comment] 2019-02-14 20:28
The backend issue with empty strings appears to be resolved in `master`.

If the field shows a list of values including the empty string you can select it and it works correctly:

<img width="936" alt="screenshot 2019-02-14 12 15 09" src="https://user-images.githubusercontent.com/18193/52814940-32d85280-3052-11e9-989e-1fa32d484a38.png">

(we should clean up the UI a bit for empty strings)

However, if you don't have field values we don't have a way to enter an empty string:

<img width="902" alt="screenshot 2019-02-14 12 16 39" src="https://user-images.githubusercontent.com/18193/52815008-674c0e80-3052-11e9-82a7-155c82c5e48d.png">

Additionally I think it would be nice to have "Is Empty" be shorthand for "null or empty string" (for string fields) rather than just null. I think we were trying to be too cute by referring to `is-null` as "Is Empty".

We could also have "Is Null", but with the "Is not" variants the list of operators would be pretty long. Are there cases where you want to filter out "null" but not empty string?


@camsaul We have `is-null` sugar for `[:= [:field-id <field>] nil]`, why not have `is-empty` be sugar for `[:= [:field-id <field>] nil ""]`? It would make implementation on the frontend easier, since currently the operator list maps directly to the MBQL operator (though we do have something more complex for date/time filters, so we could switch to something like that, but it's a fair amount more work)

**Comment by montanaflynn** [comment] 2019-09-02 10:50
I think is empty should be "" and there should be a separate is null.

**Comment by camsaul** [comment] 2020-07-16 19:27
To summarize the state of this issue:

There is some confusion in how things work because the MBQL `:is-null` filter is referred to as `"is Empty"` in the frontend code. If you want a filter for `nil` or *empty* strings you can do something like

```clojure
[:= [:field-id <id>] nil ""]
```

Tom suggested adding a `:is-empty` filter that is syntactic sugar the same way `:is-null` is, and then having the frontend call `:is-null` "Is Null" and add a separate "Is Empty" option to fix the confusion. (We may want to add a `:not-empty` filter for `"Is Not Empty" support).

**Comment by camsaul** [comment] 2020-07-16 19:42
@robdaemon to tackle this issue all you should need to do is:

1.  Add the new filter clauses to the MBQL schema in `metabase.mbql.schema`
2.  Tweak `metabase.mbql.util/desugar-filter-clause` so it converts the new filter clauses to the appropriate not-sugary clauses
3.  Rename `is-null` to `Is null` in the frontend code -- it looks like this is mostly in `frontend/src/metabase/lib/schema_metadata.js`
4.  Add `is-empty` and `is-not-empty` to frontend. I would just grep `frontend` for `is-null` to see where it would need to go (looks like maybe 5 or 6 files need to be edited)

The backend stuff only really requires editing 2 files, but there seems to be a lot of duplication in the FE stuff, especially in `schema_metadata.js`. Maybe that can be refactored a bit?

**Closed** 2020-07-21 22:50 UTC
Labels: .Correctness, Priority:P2, Query Builder, Type:Bug, Type:Completeness

**Comment by flamber** [comment] 2020-07-30 19:27
This was fixed in 0.36.1, so now filtering is done like this:
"Is empty" generates `(column IS NULL OR column = '')`
"Not empty" generates `(column IS NOT NULL AND column <> '')`

And old filters from before 0.36.1 are changed to "Is empty" => "Is null", and "Not empty" => "Not null"

**Comment by vangelova09** [comment] 2021-02-02 18:16
Quite disappointing to see a lot of basics are missing from the tool, including this which seems to be still unresolved.

How I went around it is with a custom field and then used that as an extra filter
`case(field = " ", 0, 1)`

**Comment by paoliniluis** [comment] 2021-02-02 18:21
Hi @vangelova09, if you are having issues please post them in Discourse so we can help you better. If there is an issue, we invite you to create a new issue or ask to open again a closed one if the issue still occurs. Thanks!
