### ISSUE TITLE
Cannot create/edit pulses due to issue with selecting delivery mechanisms in UI. 

### ISSUE THREAD

**Issue by cgddrd** [metabase/metabase#13094] opened 2020-08-11 10:12 UTC
**Describe the bug**

When attempting to create a new pulse, I am unable to select/enable either the email or Slack delivery mechanisms (the toggle switches do not respond). Looking at the developer tools console I find the following errors:

When first loading the pulse editor page:
```
Cannot read property 'email' of undefined
    at t.getDefaultChannel (app-main.bundle.js?ada954fc8b32cc88efab:5)
    at app-main.bundle.js?ada954fc8b32cc88efab:5
    at u (vendor.bundle.js?ada954fc8b32cc88efab:1)
    at Generator.g._invoke (vendor.bundle.js?ada954fc8b32cc88efab:1)
    at Generator.e.<computed> [as next] (vendor.bundle.js?ada954fc8b32cc88efab:1)
    at r (app-main.bundle.js?ada954fc8b32cc88efab:5)
    at app-main.bundle.js?ada954fc8b32cc88efab:5
```

When attempting to select either the Slack or email toggle switches:

```
Cannot read property 'slack' of undefined
    at t.value (app-main.bundle.js?ada954fc8b32cc88efab:5)
    at t.value (app-main.bundle.js?ada954fc8b32cc88efab:5)
    at r.handleClick (app-main.bundle.js?ada954fc8b32cc88efab:5)
    at Object.i (vendor.bundle.js?ada954fc8b32cc88efab:1)
    at s (vendor.bundle.js?ada954fc8b32cc88efab:1)
    at Object.executeDispatchesInOrder (vendor.bundle.js?ada954fc8b32cc88efab:1)
    at d (vendor.bundle.js?ada954fc8b32cc88efab:1)
    at f (vendor.bundle.js?ada954fc8b32cc88efab:1)
    at Array.forEach (<anonymous>)
    at e.exports (vendor.bundle.js?ada954fc8b32cc88efab:1)

Uncaught TypeError: Cannot read property 'email' of undefined
    at t.value (app-main.bundle.js?ada954fc8b32cc88efab:5)
    at t.value (app-main.bundle.js?ada954fc8b32cc88efab:5)
    at r.handleClick (app-main.bundle.js?ada954fc8b32cc88efab:5)
    at Object.i (vendor.bundle.js?ada954fc8b32cc88efab:1)
    at s (vendor.bundle.js?ada954fc8b32cc88efab:1)
    at Object.executeDispatchesInOrder (vendor.bundle.js?ada954fc8b32cc88efab:1)
    at d (vendor.bundle.js?ada954fc8b32cc88efab:1)
    at f (vendor.bundle.js?ada954fc8b32cc88efab:1)
    at Array.forEach (<anonymous>)
    at e.exports (vendor.bundle.js?ada954fc8b32cc88efab:1)
```
I am also unable to save the pulse as I cannot enable at least one delivery mechanism. 

**I can confirm that both the email and Slack credentials are setup via the Admin panel, and appear to be validating correctly.**

This used to work a few versions ago, but I'm unsure as to exactly which version this issue was introduced.

**Logs**

There appear to be no server log entries related to this issue. 

**To Reproduce**
1. Click 'New' -> 'Pulse' via top nav bar. 
2. Attempt to click on the toggle switches for either the email or Slack delivery mechanisms (either before or after selecting questions to include in the pulse).
3. Note that the toggles fail to switch on and you cannot edit the delivery settings for email or Slack.

**Expected behavior**

When I click on the toggle switches for either the email or Slack delivery mechanisms, then these should enable correctly in the UI and I should be able to configure/test the email/Slack options and save the pulse.

**Screenshots**

![Screenshot 2020-08-11 at 11 07 25](https://user-images.githubusercontent.com/2536819/89885464-0360c280-dbc3-11ea-8899-e5e2901bd445.png)

**On one occasion, I was able to open the Slack settings, and got this error (it only happened a single time and I wasn't able to reproduce).**

![Screenshot 2020-08-11 at 10 58 57](https://user-images.githubusercontent.com/2536819/89885384-e2986d00-dbc2-11ea-84b0-cd46352c79d7.png)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "4.14.186-110.268.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "mysql"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-08-04",
      "tag": "v0.36.3",
      "branch": "release-0.36.x",
      "hash": "a792f14"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**

High - No new pulses can be created or existing ones modified where you need to change the delivery settings. However, existing pulses that do not require changes continue to work.

**Additional context**

I've tested on Chrome and Safari on macOS 10.15.6 and Chrome on Windows 10. This issue occurs in all cases.

**Comment by flamber** [comment] 2020-08-11 10:19
Hi @cgddrd 
Please post the error from the log, when you see `clj-http: status 429` - Admin > Troubleshooting > Logs.

**Comment by cgddrd** [comment] 2020-08-11 10:28
Hi @flamber, 

This is the only reference I can find - 

```
[fa1b6d7a-7d22-4516-9ef2-09ee9c64ef49] 2020-08-11T09:00:00+01:00 INFO metabase.task.send-pulses Sending scheduled pulses...
[fa1b6d7a-7d22-4516-9ef2-09ee9c64ef49] 2020-08-11T09:00:03+01:00 ERROR metabase.integrations.slack Slack channel named `metabase_files` is missing! Please create the channel in order to complete the Slack integration. The channel is used for storing graphs that are included in Pulses and MetaBot answers.
[fa1b6d7a-7d22-4516-9ef2-09ee9c64ef49] 2020-08-11T09:00:03+01:00 ERROR metabase.task.send-pulses Error sending Pulse 1
```

I'm trying to ascertain if there's an issue with our Slack config that would be preventing this working. Wondering if this is actually related to #12978?

**Comment by flamber** [comment] 2020-08-11 10:40
Yes, it's a duplicate of #12978

**Closed by flamber** 2020-08-11 10:40 UTC
Labels: .Needs Triage, Type:Bug

**Comment by cgddrd** [comment] 2020-08-11 12:10
@flamber - just confirming that these JS issues don't need to be raised as an issue in their own right?

**Comment by flamber** [comment] 2020-08-11 12:18
@cgddrd The JS errors are side-effect of the backend not working as expected.
