### ISSUE TITLE
Unable to connect to IBM Databases for Mongo

### ISSUE THREAD

**Issue by ayukidawe** [metabase/metabase#11850] opened 2020-02-04 05:20 UTC
**Describe the bug**
I keep getting Connection error when trying to connect to a IBM cloud hosted - "Databases for Mongodb"

**Logs**

"Timed out after 3000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=ae03869f-a4a9-4810-8d33-cf3e08879595-0.blrrvkdw0thh68l98t20.databases.appdomain.cloud:32182, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}]", :message "Timed out after 3000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=ae03869f-a4a9-4810-8d33-cf3e08879595-0.blrrvkdw0thh68l98t20.databases.appdomain.cloud:32182, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}]"}

If I directly edited a row in the Metabase DB and then try to "sync" as given in one of the forums I Get a PKIX error - 

Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**To Reproduce**
1. Create a new service - IBM hosted - "Databases for Mongodb"
2. Metabase -> Databases -> Add a new Database
3. Enter all fields - host, port, username, password, options - "ssl = true"
4. Import the IBM certifcate in the Java Key store as pointed out in forums

**Expected behavior**
Database should be added without any error

**Screenshots**

**Information about your Metabase Installation:**
0.34.1 - private hosted , Elasticbean stalk both giving same error

You can get this information by going to Admin -> Troubleshooting.

- Browser: Chrome
- Your operating system: Linux
- Your databases: MongoDB - IBM Databases for mongoldb
- Metabase version: 0.34.1
- Metabase hosting environment: Mac ( Metabase.jar) ,   Elastic Beanstalk / Docker, Jar-file on Ubuntu, …)
- Metabase internal database: H2 / Postgres

**Severity**
This is severe, this is blocking our internal teams after migrating from privately hosted mongodb to IBM databases for mongoldb

**Additional context**
Followed the following forums to resolve the issue - 

https://www.metabase.com/docs/latest/administration-guide/databases/mongodb (edited) 

http://mongodb.github.io/mongo-java-driver/3.0/driver/reference/connecting/ssl/

https://github.com/metabase/metabase/issues/3877 (edited)

**Comment by flamber** [comment] 2020-03-10 12:03
Hi @ayukidawe 
Unless I'm misunderstanding, this is a duplicate of #3877. By solving that, would also solve this, right?
Have you tried to build a Docker image as a workaround, like the example in https://github.com/metabase/metabase/issues/3877#issuecomment-559000257, but just with the IBM certificate instead?

**Comment by flamber** [comment] 2020-06-06 13:34
Closing in favor of #3877. And 0.36.0 will allow specifying certificate.

**Closed by flamber** 2020-06-06 13:34 UTC
Labels: .Need More Info, Type:Bug
