### ISSUE TITLE
The difference between not empty and not null [0.29.3]

### ISSUE THREAD

**Issue by weisongbai** [metabase/metabase#8499] opened 2018-09-11 09:12 UTC
when I set  "a is not empty" in FILTERED BY, but the converted sql is "a is not NULL"

**Comment by mvrabel** [comment] 2018-09-11 10:10
Duplicate of https://github.com/metabase/metabase/issues/5299

**Comment by salsakran** [comment] 2018-12-28 04:00
closing as a dupe

**Closed by salsakran** 2018-12-28 04:00 UTC
