### ISSUE TITLE
some Formatting is lost in the pulse emails

### ISSUE THREAD

**Issue by kkalyan** [metabase/metabase#9216] opened 2019-01-04 15:26 UTC
Column Ordering (metrics are displayed as first column) and `multiplied by a number` are lost in the pulse emails. Using Druid Native query here. 

## Question Format
![image](https://user-images.githubusercontent.com/391567/50695442-8be3ae00-0ff1-11e9-8a61-7746b047914f.png)

## Email Format

![image](https://user-images.githubusercontent.com/391567/50695508-be8da680-0ff1-11e9-9953-ecbd50685f87.png)

## Setup 
- Browser Version: Chrome 71.0.3578.98 
- OS Version: Mac OS X 10.4.2  
- Database: Druid 0.12.3
- Metabase version: v0.31.2
- Metabase hosting environment: RHEL6 
- Metabase internal database: H2 (default)

**Comment by flamber** [comment] 2019-02-24 22:37
Hi @kkalyan 
This looks like a duplicate of #3735, since currently no formatting is added to pulses (multiply, decimal, prefix, suffix, separator, title). Related to #5493. Go and upvote :+1:

**Closed** 2020-03-03 15:52 UTC
Labels: Priority:P3, Reporting/Pulses, Type:Bug, Visualization/Chart Settings
