### ISSUE TITLE
After adding columns to a view, field filter shows columns not in correct order

### ISSUE THREAD

**Issue by janfrederik** [metabase/metabase#19096] opened 2021-11-25 10:42 UTC
**Describe the bug**
After adding columns to a view in the database and resyncing the database schema, the field filter shows the columns not in the right order.

**To Reproduce**
1. Create a view in the database
2. Create a simple or custom question on this view
3. Click on "Filter", which lists all fields in the view. They are shown in the order that the columns are defined in the DB. So far so good.
4. Edit the definition of the view: add some (more than 1) columns in the middle.
5. Resync the database schema. Wait for this operation to be completed (you can see the progress in the log output)
6. Create a new simple or custom question on this view
7. Click on "Filter", which lists all fields in the view. The newly added columns are in the list, but not in the correct place.
8. In the Data model, with "Column order: Database", they are shown in the correct order.
9. In the Data model, with "Column order: Custom", they are shown in yet another (random?) order, even though I never touched anything about this view yet and the order seems just random.

**Expected behavior**
The field list should show the columns in the exact order that they are defined in the DB.

**Screenshots**
The newly added columns are in red. They were added all at the same time and in the view definition, all together between "BudgetedAmount" and "ProjectStartDate".

Field list in the filter.
![image](https://user-images.githubusercontent.com/18148910/143425522-8907c28a-ce99-4c9b-a965-022069fc84a6.png)
(rest of columns at the bottom not shown)

Field list in Data model, with "Show original schema"
![image](https://user-images.githubusercontent.com/18148910/143425854-5f5648f6-bfe1-4fe0-97ef-635ef46fb98f.png)
(rest of columns at the bottom not shown)

Field list in Data model, with "Column order: Database"
![image](https://user-images.githubusercontent.com/18148910/143426433-154d13fc-0e0e-40a9-9f6f-16bf0f2303f7.png)
![image](https://user-images.githubusercontent.com/18148910/143426239-a21eb814-31d2-4c9d-931a-2f75d3ab8f42.png)
(rest of columns at the bottom not shown)

Field list in Data model, with "Column order: Custom"
![image](https://user-images.githubusercontent.com/18148910/143426659-ab63e259-911c-41f8-94b9-e8e791ee7a8a.png)
![image](https://user-images.githubusercontent.com/18148910/143426796-eecfa9b5-4112-4b11-a9a7-e54dc7155ee9.png)
(rest of columns at the bottom not shown)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "5.4.0-1046-azure",
    "user.language": "en",
    "user.timezone": "Europe/Brussels"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-11-09",
      "tag": "v0.41.2",
      "branch": "release-x.41.x",
      "hash": "ad599fd"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Annoying

**Comment by flamber** [comment] 2021-11-25 11:00
This is basically a duplicate of #13024.
Workaround is to change column order to "Alphabetic" and then back to "Database".

**Comment by janfrederik** [comment] 2021-11-25 15:32
The cause is the same, indeed.
Thanks for sharing the workaround!

**Comment by calherries** [comment] 2023-11-07 12:13
Closed by https://github.com/metabase/metabase/issues/13024

**Closed by calherries** 2023-11-07 12:13 UTC
Labels: Type:Bug, Priority:P3, Administration/Metadata & Sync, Administration/Table Metadata, .Backend, .Wanted: MLv2

**Comment by snoe** [comment] 2023-11-08 22:31
Not MLv2 but tested as part of https://github.com/metabase/metabase/pull/30446
