### ISSUE TITLE
Unchecking "Remember me" box has no effect -- close the browser and reopen, then go back to your MB instance and you're still logged in

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15223] opened 2021-03-18 19:04 UTC
This is on Edge (Chromium) but I don't think it's browser-specific.

1. Be logged out
1. Go to http://localhost:3000/auth/login 
2. Uncheck the "remember me" box
3. log in
4. close your browser
5. Go back to http://localhost:3000
6. You are still logged in. I'd expect to have to log in again

I'm assuming the "remember me" box is meant to tell Metabase to generate a session cookie that gets wiped when you close the browser, similar to way cookies usually work for sensitive stuff like banks. 

We create the same cookies on the backend regardless of whether that box is checked or not. I'm not sure if that checkbox corresponds to a flag passed to the auth API endpoints or not, but the backend definitely is not looking for it or doing anything different if it is there. I wrote the most recent iteration of our session cookie code on the backend, and I wasn't even aware that checkbox was there before today.

Either way, it should be easy to get this working:

1. Figure out what flag the FE client is passing in if that box is checked
2. Look for this flag and create a session cookie on the backend if it is present

**Comment by flamber** [comment] 2021-05-10 20:27
@noahmoss I can reproduce on Linux. When it's unchecked, then the sessions should not be remembered, when the browser closes - currently the checkbox has no effect and always remembers across browser closes, so people have to remember to sign out before closing the browser.

**Comment by noahmoss** [comment] 2021-05-10 20:59
Thanks @flamber, I think my mental model of session cookies was a bit off in my previous comment. I digged a bit more and it seems that they can already be enabled with the `MB_SESSION_COOKIES` env variable, documented here: https://www.metabase.com/docs/latest/operations-guide/changing-session-expiration.html

Currently, if `MB_SESSION_COOKIES` is set, all logins use session cookies, which are automatically cleared when the browser is closed: https://github.com/metabase/metabase/blob/5bd6dd30e990f405a8e0e23b9039559fca3371b0/src/metabase/server/middleware/session.clj#L73-L78

The question now is, how should the "remember me" checkbox and this `MB_SESSION_COOKIES` interact if they contradict each other?
* If `MB_SESSION_COOKIES` is unset (the current default) and "remember me" is checked, should we use session cookies?
* If `MB_SESSION_COOKIES` is set and "remember me" is unchecked, should we use session cookies? Alternatively should we hide or gray-out the checkbox in this case, and have the env variable take precedence since it's a system-level setting?

**Comment by flamber** [comment] 2021-05-10 21:33
@noahmoss 
> If MB_SESSION_COOKIES is unset (the current default) and "remember me" is checked, should we use session cookies?

The other way around, right? When not defined, then "remember me"=checked should preserve across browser-close, but when "remember me"=unchecked, then it should forget on browse-close.

> If MB_SESSION_COOKIES is set and "remember me" is unchecked, should we use session cookies? Alternatively should we hide or gray-out the checkbox in this case, and have the env variable take precedence since it's a system-level setting?

I think that it makes most sense to hide "remember me", when `MB_SESSION_COOKIES` is set, since the user should not be able to control instance defined security settings.

**Closed** 2021-05-24 17:05 UTC
Labels: Administration/Auth, Good Backend Starter Issue, Priority:P2, Type:Bug
