### ISSUE TITLE
Feature Request: Show full data / rows for Pulse Email

### ISSUE THREAD

**Issue by naxIO** [metabase/metabase#4669] opened 2017-04-03 10:23 UTC
Right now the rows are capped in the Pulse Email report. This limits the use of this feature.

It should show an entire row (with line breaking) or if the data is too much sacrifice the responsiveness of the template (people can zoom in then) to enable full email data reports.

**Comment by mazameli** [comment] 2017-04-03 16:35
Closing as a duplicate of #3894. Please feel free to add your support to that issue via a 👍  reaction.

**Closed by mazameli** 2017-04-03 16:35 UTC
Labels: Duplicate
