### ISSUE TITLE
0.30.1 Collections 2.0 Permissions Inherit

### ISSUE THREAD

**Issue by tomonetml** [metabase/metabase#8432] opened 2018-08-31 07:45 UTC
Hi,

-Running Metabase 0.30.1 on Ubuntu 14 LTS as Service-

We recentrly migrated from 0.29.3 to 0.30.1 to receive new collections benefits.
As obvious, our Questions Pulses and Dashboards gone to 'Migrated' "group".

Our goal is now to create Collections with visibility only to some specific user groups we are creating ex novo, ensuring our sensible datas keep secure.
From administration guide and through testing we understood that only 'items' that are created directly in that collection get visible to those groups.

No visibility for Questions Moved there nor Dashboards.
Then we tried to edit a question and make 'save as' from there and saved to the collection but still no luck, permissions doesn't get inherited.

The real only way we find is to ask a new question and save to that specific collection.

So, assuming we want migrated questions and dashboards to be now visible in new collection system should we recreate them from the beginning? (re-designign existing dashboards is a slow [boring] process)

Maybe it could become possible to inherit permissions while moving items within collections (asking user about it) ?

Hope at least 'save as' question function will get to inherit permissions from collection it's saved in.

Sorry for being so long
if something is unclear let me know
ty
Matteo

**Comment by mazameli** [comment] 2018-08-31 16:36
If I'm understanding you correctly, this sounds like a bug that I will try to reproduce.

Are you saying that when you move an existing dashboard, question, or pulse from a collection that a group did not have access to, to another collection that the group _does_ have access to, that members of that group are not able to see the moved item in the new collection? Are they able to see other items in the collection? If a user in that group goes to that collection and refreshes the page in the browser, do the items appear then?

Lastly, could you let me know what web browser you and/or your users are using?

**Comment by mazameli** [comment] 2018-08-31 16:57
In a few tests that I just ran on master, I couldn't reproduce the behavior that I thought you were describing: I moved a dashboard and a question from the "migrated" collections to a new collection that my "Marketing" group has access to. When I logged in with a non-admin account that is a member of the Marketing group, I was able to see the moved dashboard and question without a problem.

I think the inheritance that you're referring to in the docs is specifically about new _collections_, not new items: when you create a new _collection_, by default it inherits the permissions of the collection it was created inside. But when you move a collection, its permissions do _not_ change. Administrators can change a collection's permissions either by clicking the lock in the top-right of the collection's page, or they can alter all collection permissions from within the Admin Panel's Permissions section, under the Collection Permissions tab.

**Comment by tomonetml** [comment] 2018-09-01 06:45
Hi @mazameli,

Yes, you understand our problem corrextly in your first reply.

We run Firefox 61.0.2 (64 bit)

I have created a test user in a group that has full data access to a specific db and no sql permissions on that db (mysql). All users group permissions are none on that db but specific user group wins on this as normal.
We created a new collection and moved there things from migrated collection. 
To test this i'm giving view permission to the collection

![permission](https://user-images.githubusercontent.com/34745293/44943149-e1008080-adc1-11e8-8601-6a7d25ce1ebe.PNG)

and yes, user test can see collection when refreshing.

We have then a migrated dashboard pinned in this collection.

![test01](https://user-images.githubusercontent.com/34745293/44943163-23c25880-adc2-11e8-8112-b13bbf4cd362.PNG)

but when user access the 'controllo di gestione' dashboard gets this error

![test02](https://user-images.githubusercontent.com/34745293/44943169-3fc5fa00-adc2-11e8-9e22-29641e1853da.PNG)

Note that on screen nr2 there's a dashboard named 'prova'
that dashboard was directly created in that collection and user can access it.

![test03](https://user-images.githubusercontent.com/34745293/44943200-8b78a380-adc2-11e8-9b9d-03656c1223ab.PNG)

hope this can help you.
Next week i'm away and can't test new things
have a nice day
Matteo

**Comment by tomonetml** [comment] 2018-09-11 08:02
Hi,

Understood the problem.

All questions that are added to a dashboard in a collection needs to be in that collection too or you get 'datasetQuery is undefined' error.

**Comment by salsakran** [comment] 2018-12-28 04:13
at the very least, this needs a better error message.

**Comment by flamber** [comment] 2019-11-29 16:43
If I understand this correctly, it's likely the same issue as #10247. Fixed by #10653 in 0.33.1

**Closed** 2020-06-03 15:48 UTC
Labels: Administration/Permissions, Organization/Collections, Priority:P2, Type:Bug
