### ISSUE TITLE
UI Bug with "Combo" visualization, can't display normal and percent on one plot

### ISSUE THREAD

**Issue by grkhr** [metabase/metabase#15745] opened 2021-04-22 10:46 UTC
**Describe the bug**
When I try to do a Combo visualization, where bar should be numbers and line should be percent, Metabase displays only percents, or only numbers. Bug apears both in Custom Question and Native Query.

**To Reproduce**
1. Make question with columns of normal and column of percents, grouped by date.
2. Сhoose percent columns type as percent. 
3. Make Combo visualization, percent-columns line, number-columns bar.
4. Enable "Show values on data points" in visualization settings
5. See error

**Expected behavior**
Percents as percents, numbers as numbers.

**Screenshots**
![tg_image_1151027207](https://user-images.githubusercontent.com/40689054/115701069-0de97380-a370-11eb-97ee-7832f71f57fe.jpeg)
![tg_image_3801773125](https://user-images.githubusercontent.com/40689054/115701088-1477eb00-a370-11eb-8249-93497e1ac294.jpeg)

And also the video how to reproduce related bug with all percent displaying.
https://user-images.githubusercontent.com/40689054/115701718-bdbee100-a370-11eb-99c4-bfd92f57d4c9.mov

**Severity**
Severe. I figured out this bug half-year ago, hoped for fix in new versions, but there wasn't. Really annoying bug

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-gb",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "5.4.0-58-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "vertica"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.2 (Debian 11.2-1.pgdg90+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-20",
      "tag": "v0.39.0.1",
      "branch": "release-x.39.x",
      "hash": "47bb5f2"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2021-04-22 10:59
Duplicate of #13095

**Closed by flamber** 2021-04-22 10:59 UTC
