### ISSUE TITLE
Link URL replaced with ASCII characters

### ISSUE THREAD

**Issue by MarcSamD** [metabase/metabase#18594] opened 2021-10-21 10:26 UTC
**Describe the bug**
The "Link URL" field replace special characters by ASCII characters causing the link to be invalid (not working).

**To Reproduce**
1. Create a table "Resource" with a column "ResPath", with values like "/folder1/folder2/filename.pdf" and "/folder2/folder1/english-and-中文.pdf"
2. Go to "Data Model", table "Resource", "ResPath" field settings
3. Setup "Field Type" as URL
4. Go to Formatting
5. Setup View as "Link", "Link text" as "https://mydomain.com{{ResPath}}" and "Link URL" as "https://mydomain.com{{ResPath}}"

=> The field is displayed as "https://mydomain.com/folder1/folder2/filename.pdf" but the link is "https://mydomain.com%2Ffolder1%2Ffolder2%2Ffilename.pdf" which is not valid.

**Expected behavior**
The link should be "https://mydomain.com/folder1/folder2/filename.pdf" (which is already working for the text displayed)

**Information about your Metabase Installation:**
- Your browser and the version: tested on several browsers, all same issue
- Your operating system: Windows 10
- Your databases: MSSQL
- Metabase version: 0.40.4
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

**Severity**
blocking some users

**Additional context**
May be related to my table's values including chinese characters. But the %2F also appears for paths with only english characters. Also possibly related to #15454

**Comment by flamber** [comment] 2021-10-21 10:29
Duplicate of #14846

**Closed by flamber** 2021-10-21 10:29 UTC
Labels: Type:Bug, .Needs Triage

**Comment by flamber** [comment] 2021-10-21 10:44
@MarcSamD It's because I (sadly) can remember almost all our issues :robot: :wink:
