### ISSUE TITLE
Reported time zone incorrect

### ISSUE THREAD

**Issue by joevandyk** [metabase/metabase#5676] opened 2017-08-03 19:14 UTC
I live in the US/Pacific time zone. I'm connected to a postgresql database and am querying against a table with timestamptz columns.

I've got my timezone set to US/Pacific in Metabase's admin panel.

I'm noticing the dates reported in Metabase are incorrect: http://take.ms/McBV4
The query in the screenshot is the same query Metabase says it runs.

Any ideas?

**Comment by joevandyk** [comment] 2017-08-03 19:18
I converted the question to sql and I'm getting stranger results: http://take.ms/V3ryl

**Comment by salsakran** [comment] 2017-08-03 19:18
this is a dupe of #5324

we're aware of it and we're working on it currently.

**Closed by salsakran** 2017-08-03 19:18 UTC
Labels: Bug, Priority/P1, Timezones/Calendars

**Comment by salsakran** [comment] 2017-08-03 19:20
There's some wacky implicit conversion happening in the server/jdbc driver interface. It shows up in odd places. 

The easiest way to work around this bug is if you have control over the server timezone, setting it, the database timezone and your reporting timezone all to the same timezone should fix it.

**Comment by joevandyk** [comment] 2017-08-03 19:45
I created a new Metabase user and set the time zone for that user to us/pacific, then set the Metabase time zone to use the database's default time zone. that seemed to do the trick, thanks!
