### ISSUE TITLE
Cannot Upload Specific Custom Maps

### ISSUE THREAD

**Issue by golfmachine13** [metabase/metabase#41596] opened 2024-04-18 16:50 UTC
### Describe the bug

I have been using this data to great effect in uploading maps: https://github.com/faeldon/philippines-json-maps/tree/master/2023/geojson

I had no issues uploading geojson files from the folders 2023/country, 2023/provdists, 2023/regions. However, attempting to upload any geojson from 2023/municipalities folder will result in "something's gone wrong" error in Metabase

### To Reproduce

Add a new map and input as url a raw geojson url from the 2023/municipalities folder. Sample: https://raw.githubusercontent.com/faeldon/philippines-json-maps/master/2023/geojson/municities/lowres/bgysubmuns-municity-1381300000.0.001.json
![image](https://github.com/metabase/metabase/assets/76050054/4c808b87-d800-477c-9795-98c8d634d87a)
3. Click on '....'
"Load"
6. See error
![image](https://github.com/metabase/metabase/assets/76050054/3f386e33-367f-4a8b-856d-6aa4dd702dc6)

### Expected behavior

Should be able to upload a map. Again, other geojson from the source found in 2023/country, 2023/provdists, 2023/regions all work. Just the ones under municipalities folder seem problematic. Note also that the files under municipalities can be loaded in https://geojson.io/ so I am not sure why uploading in Metabase is problematic for these files specifically. File size also does not seem to be too big.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "6.5.0-1017-azure",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.36"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-01-05",
      "tag": "v0.48.2",
      "hash": "e66c075"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Annoying

**Comment by paoliniluis** [comment] 2024-04-22 07:46
duplicate of https://github.com/metabase/metabase/issues/37715

**Closed by paoliniluis** 2024-04-22 07:46 UTC
Labels: Type:Bug, .Needs Triage

**Comment by golfmachine13** [comment] 2024-04-23 03:58
Yes, it was indeed similar to another issue. The geojson had a NULL. Thank
you!

Michael Fong, MD
Physician Informaticist
MedProjects Inc.
www.medprojects.com
