### ISSUE TITLE
Axis labels and tooltips are mis-aligned

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#1391] opened 2015-10-28 19:03 UTC
<img width="544" alt="screen shot 2015-10-28 at 12 01 25 pm" src="https://cloud.githubusercontent.com/assets/5248953/10799758/bdd300b2-7d6b-11e5-8f19-cc2f0e9c2603.png">

My expectation would be that the tooltip and point on the line would be on the same x-axis point as the label.

**Comment by tlrobinson** [comment] 2015-10-28 21:12
I believe this is a timezone mismatch issue.

**Comment by tlrobinson** [comment] 2015-10-28 23:56
Also I think this is a duplicate of #582, but since this has a screenshot not in Asana maybe we should close the other one.

**Comment by agilliland** [comment] 2016-02-22 20:27
latest charting code removes those guidelines and prefers using the tooltip, so this is no longer relevant.

**Closed by agilliland** 2016-02-22 20:27 UTC
Labels: Visualization, Won't Fix
