### ISSUE TITLE
When adding a db, immediately updating `database-enable-actions` prevents the db from finishing initial sync

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#27877] opened 2023-01-25 20:43 UTC
I discovered this while setting up automated testing for actions DBs, If we update the DB immediately after adding it, before the initial sync had finished, the DB would always report that the initial sync was "incomplete"

This was an easy workaround in our e2e test setup: wait for the initial sync to complete before enabling actions, but I fear that real customers with large DBs that take minutes to sync initially could get stuck.

**Comment by tsmacdonald** [comment] 2023-02-01 14:51
@iethree I can't reproduce this. Steps I took:

1. Load up the very large mouse genome data into a local postgres DB
2. Add the DB to Metabase
3. While it was syncing, go to `http://localhost:3000/admin/databases/:id` in another window, toggle the actions, and save.
4. Confirm that it was still syncing.
5. After the sync finished, check the status.

You can see in the screenshot the sync status for `Mouse Genome` while the sync was running and then after it finished.
![image](https://user-images.githubusercontent.com/784417/216075887-2426390d-0710-47bf-875c-d4b09d88a5ec.png)

And, indeed, the settings updated correctly:

```
# select id, name, initial_sync_status, settings from metabase_database where id = 320;
 id  |     name     | initial_sync_status |             settings             
-----+--------------+---------------------+----------------------------------
 320 | Mouse Genome | complete            | {"database-enable-actions":true}
(1 row)
```

**Comment by iethree** [comment] 2023-02-01 15:43
I've added a cypress test on this branch that reproduces the issue: `repro-27877`

![Screen Shot 2023-02-01 at 8 36 22 AM](https://user-images.githubusercontent.com/30528226/216089562-ee49dbf1-ab28-465e-aac7-93a5a3fd4ba5.png)

if you have docker engine running, this branch includes a handly little helper that will spin up the appropriate containers for you that will link up to the test: `yarn test-qa-dbs:up`

Otherwise, you can edit the DB credentials in the spec file: `frontend/test/metabase/scenarios/admin/databases/repro-27877.cy.spec.js`

**Comment by dpsutton** [comment] 2023-02-13 16:55
I can't recreate this either. But I don't think your repro is valid. Sync is an asynchronous process that takes some time. Your test asserts that `initial_sync_status` is "complete" immediately after updating the settings. 

```clojure
race=> (let [{id :id} (create-db {:engine "postgres"
                                  :name "foo6"
                                  :details {:dbname "sample-dataset"
                                            :user "dan"}})
             status! (fn [id] (db/select-one-field :initial_sync_status 'Database :id id))]
         (update-db id {:settings {:database-enable-actions true}}) ;; update the settings

         {:immediately (status! id)     ;; sync status right away
          :two-second-pause  (do (Thread/sleep 2000) (status! id))}) ;; wait 2 seconds, get sync status
{:immediately "incomplete", :two-second-pause "complete"}
```

I did this in a loop 8 times:

```clojure
race=> (let [create-and-update (fn [index]
                                 (let [{id :id} (create-db {:engine "postgres"
                                                            :name (str "check_" index)
                                                            :details {:dbname "sample-dataset"
                                                                      :user "dan"}})]
                                   (update-db id {:settings {:database-enable-actions true}})
                                   ))]
         (dotimes [index 8]
           (create-and-update index)))
nil
```

and query the database (after a suitable amount of time. with so many syncs have to wait about 10 seconds until the console output slows down)

```sql
clean=# select id, name, description, initial_sync_status from metabase_database;
 id |      name       |                                      description                                      | initial_sync_status
----+-----------------+---------------------------------------------------------------------------------------+---------------------
  8 | check_6         | [null]                                                                                | complete
  9 | check_7         | [null]                                                                                | complete
  3 | check_1         | [null]                                                                                | complete
  1 | Sample Database | Some example data for you to play around with as you embark on your Metabase journey. | complete
  4 | check_2         | [null]                                                                                | complete
  2 | check_0         | [null]                                                                                | complete
  5 | check_3         | [null]                                                                                | complete
  6 | check_4         | [null]                                                                                | complete
  7 | check_5         | [null]                                                                                | complete
```

If i create 20 or so they start stepping on toes but i think this is due to load and not anything fundamental to updating a database right away.

**Comment by dpsutton** [comment] 2023-02-13 17:02
based on the above, @iethree, can you run two experiments?

1. does your test pass if you remove the update to the settings? Does it see it as complete?
2. if you add a timeout of two seconds and then check the status, is it seen as complete?

**Comment by iethree** [comment] 2023-02-13 20:03
> based on the above, @iethree, can you run two experiments?
> 
> 1. does your test pass if you remove the update to the settings? Does it see it as complete?
> 2. if you add a timeout of two seconds and then check the status, is it seen as complete?

1. yes. yes.
2. yes.

the server throws this error:
```
2023-02-13 12:03:00,817 clojure-agent-send-off-pool-8 ERROR An exception occurred processing Appender metabase-appender java.lang.IllegalArgumentException: No implementation of method: :explain of protocol: #'schema.core/Schema found for class: clojure.lang.Var$Unbound
```

**Comment by iethree** [comment] 2023-02-13 20:10
> 2\. if you add a timeout of two seconds and then check the status, is it seen as complete?

I think I may have misunderstood this question.
- if you wait 2 seconds BEFORE updating the database, the test passes
- if you wait 2 (or 100) seconds AFTER updating the database, it still never reports as having completed the sync.

> but I don't think your repro is valid. Sync is an asynchronous process that takes some time. Your test asserts that initial_sync_status is "complete" immediately after updating the settings.

I have updated the repro to wait 2 seconds after updating the DB to demonstrate. As you can see, it still fails every time.

**Comment by qnkhuat** [comment] 2023-03-02 15:29
I finally able to reproduce this with the dev server.

The error is from and it's failing to get the connection:
https://github.com/metabase/metabase/blob/e896c3ddfc21d358e29d2ca31530253eb718bf70/src/metabase/driver/sql_jdbc/sync/describe_database.clj#L148

Error: ` java.sql.SQLException: An SQLException was provoked by the following failure: java.lang.InterruptedException`

<details>
<summary>stacktrace </summary>

```

 java.sql.SQLException: An SQLException was provoked by the following failure: java.lang.InterruptedException
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:74)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:694)
        at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:372)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:343)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
        at metabase.driver.sql_jdbc.sync.describe_database$describe_database.invokeStatic(describe_database.clj:153)
        at metabase.driver.sql_jdbc.sync.describe_database$describe_database.invoke(describe_database.clj:148)
        at metabase.driver.sql_jdbc$eval109547$fn__109548.invoke(sql_jdbc.clj:71)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at metabase.sync.fetch_metadata$eval113283$db_metadata__113288$fn__113289.invoke(fetch_metadata.clj:15)
        at metabase.sync.fetch_metadata$eval113283$db_metadata__113288.invoke(fetch_metadata.clj:12)
        at metabase.sync.sync_metadata$eval115103$sync_db_metadata_BANG___115108$fn__115109.invoke(sync_metadata.clj:58)
        at metabase.sync.sync_metadata$eval115103$sync_db_metadata_BANG___115108.invoke(sync_metadata.clj:55)
        at metabase.sync$eval115162$sync_database_BANG___115171$fn__115177$fn__115179$fn__115181.invoke(sync.clj:47)
        at clojure.core$mapv$fn__8535.invoke(core.clj:6979)
        at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
        at clojure.core.protocols$fn__8244.invokeStatic(protocols.clj:136)
        at clojure.core.protocols$fn__8244.invoke(protocols.clj:124)
        at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6886)
        at clojure.core$mapv.invokeStatic(core.clj:6970)
        at clojure.core$mapv.invoke(core.clj:6970)
        at metabase.sync$eval115162$sync_database_BANG___115171$fn__115177$fn__115179.invoke(sync.clj:47)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:159)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:152)
        at clojure.core$partial$fn__5910.invoke(core.clj:2647)
        at metabase.driver$eval72920$fn__72921.invoke(driver.clj:662)
        at clojure.lang.MultiFn.invoke(MultiFn.java:239)
        at metabase.sync.util$sync_in_context$fn__82603.invoke(util.clj:137)
        at metabase.sync.util$with_db_logging_disabled$fn__82600.invoke(util.clj:128)
        at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:101)
        at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:95)
        at metabase.sync.util$with_start_and_finish_logging$fn__82589.invoke(util.clj:113)
        at metabase.sync.util$with_sync_events$fn__82584.invoke(util.clj:87)
        at metabase.sync.util$with_duplicate_ops_prevented$fn__82575.invoke(util.clj:66)
        at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:180)
        at metabase.sync.util$do_sync_operation.invoke(util.clj:177)
        at metabase.sync$eval115162$sync_database_BANG___115171$fn__115177.invoke(sync.clj:46)
        at metabase.sync$eval115162$sync_database_BANG___115171.invoke(sync.clj:32)
        at metabase.sync$eval115162$sync_database_BANG___115171$fn__115172.invoke(sync.clj:42)
        at metabase.sync$eval115162$sync_database_BANG___115171.invoke(sync.clj:32)
        at metabase.events.sync_database$process_sync_database_event$fn__144799.invoke(sync_database.clj:39)
        at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.InterruptedException
        at java.base/java.lang.Object.wait(Native Method)
        at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1503)
        at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
        at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
        ... 52 more

```
</details>


I can *sometimes* reproduce with this script. I think it is a race condition problem

```clojure
(let [do-n-times (fn [n sleep thunk]
                   (doseq [_ (range n)]
                     (thunk)
                     (Thread/sleep sleep)))
      db (metabase.test/user-http-request :crowberto :post 200 "/database"
                                          {:is_on_demand false
                                           :is_full_sync true
                                           :is_sample false
                                           :cache_ttl nil
                                           :refingerprint false
                                           :auto_run_queries true
                                           :schedules {}
                                           :details {:host "localhost"
                                                     :port 5404
                                                     :dbname "sample"
                                                     :user "metabase"
                                                     :password "metasample123"
                                                     :schema-filters-type :all
                                                     :ssl false
                                                     :tunnel-enabled false
                                                     :advanced-options false}
                                           :name   "test sync"
                                           :engine "postgres"})]
   (metabase.test/user-http-request :crowberto :put 200 (format "/database/%d" (:id db))
                                    {:settings {"database-enable-actions" true}})
   (do-n-times 3 1000 (fn [] (println (:initial_sync_status (metabase.test/user-http-request :crowberto :get 200 (format "/database/%d" (:id db))))))))
```

**Comment by darksciencebase** [comment] 2023-08-14 17:36
This is really hard to hit as a user. Still, there might be an underlying cause for the race condition that we might like to fix. But this is not adjacent to anything this team is doing, and relatively low priority, so we won't be picking this up soon.

**Comment by iethree** [comment] 2023-11-09 15:14
Did some more digging into this as part of #35489, and this happens even without enabling actions on the DB. just sometimes the DB finishes syncing, but the database endpoint continues to report sync status as incomplete.

see: https://metaboat.slack.com/archives/C5XHN8GLW/p1699476789618349?thread_ts=1697714338.212399&cid=C5XHN8GLW

> Some interesting learnings:
Enabling actions is not the problem
The actions database isn’t even the problem
I enabled backend logs. And the failure is usually failing to connect to the non-writable MySQL. The backend logs show that the sync is complete, but it never reports a complete   sync status via the API
[Failed Job](https://github.com/metabase/metabase/actions/runs/6802527104/job/18496201350?pr=35498#step:12:7646), [Another Failed Job](https://github.com/metabase/metabase/actions/runs/6802527104/job/18496202501?pr=35498#step:12:7130)
[Successful Job](https://github.com/metabase/metabase/actions/runs/6802527104/job/18496202730?pr=35498#step:12:7512)
I really think this is some race condition under the hood

**Comment by calherries** [comment] 2023-11-14 14:10
I can reproduce pretty reliably with a modified version of Ngoc's script above:

```clojure
(map (fn [_x]
         (let [db (metabase.test/user-http-request :crowberto :post 200 "/database"
                                                   {:is_on_demand false
                                                    :is_full_sync true
                                                    :is_sample false
                                                    :cache_ttl nil
                                                    :refingerprint false
                                                    :auto_run_queries true
                                                    :schedules {}
                                                    :details {:host "localhost"
                                                              :port 5432
                                                              :dbname "<db name>"
                                                              :user "<user name>"
                                                              :password ""
                                                              :schema-filters-type :all
                                                              :ssl false
                                                              :tunnel-enabled false
                                                              :advanced-options false}
                                                    :name   "test sync"
                                                    :engine "postgres"})
               _ (metabase.test/user-http-request :crowberto :put 200 (format "/database/%d" (:id db))
                                                  {:settings {"database-enable-actions" true}})
               get-sync-status (fn [] (:initial_sync_status (metabase.test/user-http-request :crowberto :get 200 (format "/database/%d" (:id db)))))]
           (reduce (fn [results i]
                     (let [status (get-sync-status)
                           results (conj results status)]
                       (if (= status "complete")
                         (reduced results)
                         (do (Thread/sleep 1000)
                             results))))
                   []
                   (range 10))))
       (range 3))
```

The reason this happens is because the POST request that updates `database-enable-actions` closes any open connections that are being used for database sync.

It does so through this pseudo-call graph:
```
1. In the PUT "/api/database/:id" handler
2. (events/publish-event! :event/dashboard-update ...)
3. driver/notify-database-updated
4. sql-jdbc.conn/notify-database-updated
5. invalidate-pool-for-db!
```

In the specific instance of setting `database-enable-actions`, closing the connections isn't even necessary because it should not change any property of a connection that our code depends on.

However, this is a more general problem when syncing a database: if you update it during sync, at least a step is likely to fail when the connection closes.

One solution to this specific problem is to avoid calling `driver/notify-database-updated` in the `events/publish-event!` event handler if the update to the database entity shouldn't change a property of a connection that our code depends on.

**Closed** 2023-11-15 13:46 UTC
Labels: Type:Bug, Priority:P2, Administration/Metadata & Sync, .Team/BackendComponents
