### ISSUE TITLE
Be a bit smarter about last-edit of dashboards

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#16559] opened 2021-06-11 18:09 UTC
From https://github.com/metabase/metabase/pull/16510#issuecomment-859746262

Background:

We base last edits on revisions, which are essentially copies of an entity (card, dashboard, pulse, snippet) along with who edited them. These are created from events fired in certain APIs and happen asynchronously due to this. So when editing a dashboard or a card, you want include that it was _just now_ edited, but you cannot rely on the fact that there is a revision yet since it happens asynchronously. The shortcut of this was to construct a last-edit information based on the current api interaction. IE, the user who posted obviously was the editor, and the time was now.

The problem is that not all posts trigger a revision, so need to be smarter about when we fake a last-revision based on the current user versus when we just grab the latest revision because the current interaction will not create a revision.

the line is here: https://github.com/metabase/metabase/blob/master/src/metabase/api/dashboard.clj#L304

This needs to know if the change was sufficient to trigger a revision (then construct the last-edit-info) otherwise just look for the current existing last-edit info since this change will not add a new revision entry.

**Comment by kulyk** [comment] 2021-06-11 18:16
Thank you for creating an issue. Could the same thing repro with questions too?

**Comment by dpsutton** [comment] 2021-06-11 18:28
Actually, I may have spoken too soon. I think the backend will save a revision, it's just that revisions are only loaded once so those are the old revisions. I am not seeing any conditional checks in the code that might or might not create a revision. So in the instance, if maz were to refresh he would (presumably) see the new revision there.

The bug here is stale revisions in the UI, not that the revision should not have been created.

**Comment by WiNloSt** [comment] 2023-08-03 10:46
I believed this is fixed by https://github.com/metabase/metabase/pull/17887 since I can't reproduce the bug anymore

**Comment by WiNloSt** [comment] 2023-08-03 11:29
@dpsutton I know this is an old issue, but could you confirm that this has been fixed? I haven't been able to reproduce this issue anymore. One thing that's different from the original issue now is that the revision has been moved to the dashboard sidebar.

I believed this issue has been fixed by https://github.com/metabase/metabase/pull/17887.

**Closed** 2023-08-04 10:31 UTC
Labels: Type:Bug, Priority:P3, Reporting/Dashboards, .Frontend, Organization/Activity Log, .Team/42 :milky_way:, .FixScope42
