### ISSUE TITLE
Syncs from Redshift failing since version 0.47.7

### ISSUE THREAD

**Issue by MattKWill** [metabase/metabase#36040] opened 2023-11-22 14:55 UTC
**Describe the bug**
Syncs to our Redshift database failed after upgrading to 0.47.7. After downgrading to 0.47.6 they are working again. This appears to be related to changes to autocommit settings.

**Logs**
`org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: com.amazon.redshift.util.RedshiftException: Cannot rollback when autoCommit is enabled.]`

**To Reproduce**
1. Go to 'Admin - Databases'
2. Select a Redshift database
3. Click on 'Sync database schema now'
4. Nothing happens - new columns and tables are not added.

Same applies with scheduled updates. 

**Expected behavior**
Syncs complete and add new tables and columns.

**Screenshots**
Not applicable

**Severity**
Everything is running fine on 0.47.6 for now, but we are blocked from future updates until this is resolved. We don't have any immediate issues.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.10.198-187.748.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk",
      "redshift",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-10-26",
      "tag": "v0.47.6",
      "branch": "?",
      "hash": "3a7ed7a"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Comment by MattKWill** [comment] 2023-11-22 15:00
Likely related to this issue, however we have no issues querying data, it is only syncs which are affected https://github.com/metabase/metabase/issues/35653

**Comment by metamben** [comment] 2023-11-22 18:01
In issue https://github.com/metabase/metabase/issues/35653 the problem is that auto commit is disabled. Here the problem appears to be that auto commit is enabled.

**Comment by metamben** [comment] 2023-11-22 18:16
@MattKWill the attached diagnostic info seems to come from version `0.47.6`, can you update it? Also a full stack trace including that of the nested `RedshiftException` would be very usefu.

**Comment by paoliniluis** [comment] 2023-11-22 20:20
Hi @MattKWill can you reboot your Redshift cluster and try again?

**Comment by metamben** [comment] 2023-11-22 20:33
I have just added a fix for a bug that I think is causing this. To check my assumption, I need the stack trace.

**Comment by paoliniluis** [comment] 2023-11-22 21:38
@metamben

```
[227200c5-dffd-4f80-b5f9-1eb6d714c168] 2023-11-16T16:26:02+01:00 ERROR org.quartz.core.JobRunShell Job DEFAULT.metabase.task.sync-and-analyze.job threw an unhandled Exception: 
com.amazon.redshift.util.RedshiftException: Cannot rollback when autoCommit is enabled.
	at com.amazon.redshift.jdbc.RedshiftConnectionImpl.rollback(RedshiftConnectionImpl.java:1115)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.rollback(NewProxyConnection.java:1033)
	at metabase.driver.sql_jdbc.sync.describe_database$fn__86499.invokeStatic(describe_database.clj:96)
	at metabase.driver.sql_jdbc.sync.describe_database$fn__86499.invoke(describe_database.clj:80)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.driver.sql_jdbc.sync.describe_database$fast_active_tables$fn__86517.invoke(describe_database.clj:128)
	at clojure.core$filter$fn__5958$fn__5959.invoke(core.clj:2822)
	at clojure.core$preserving_reduced$fn__8848.invoke(core.clj:7682)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$cat$fn__8851.invoke(core.clj:7693)
	at clojure.core$map$fn__5931$fn__5932.invoke(core.clj:2759)
	at clojure.core$completing$fn__8528.invoke(core.clj:6931)
	at clojure.core$filter$fn__5958$fn__5959.invoke(core.clj:2823)
	at clojure.core$completing$fn__8528.invoke(core.clj:6931)
	at clojure.core$filter$fn__5958$fn__5959.invoke(core.clj:2823)
	at clojure.core$filter$fn__5958$fn__5959.invoke(core.clj:2823)
	at clojure.core$filter$fn__5958$fn__5959.invoke(core.clj:2823)
	at clojure.core$take_while$fn__5982$fn__5983.invoke(core.clj:2918)
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__85709.reduce(common.clj:39)
	at clojure.core$transduce.invokeStatic(core.clj:6946)
	at clojure.core.Eduction.reduce(core.clj:7750)
	at clojure.core$transduce.invokeStatic(core.clj:6946)
	at clojure.core.Eduction.reduce(core.clj:7750)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$reduce.invoke(core.clj:6868)
	at metabase.driver.redshift$reducible_schemas_with_usage_permissions$reify__126878.reduce(redshift.clj:340)
	at clojure.core$transduce.invokeStatic(core.clj:6946)
	at clojure.core.Eduction.reduce(core.clj:7750)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$into.invokeStatic(core.clj:6958)
	at clojure.core$into.invoke(core.clj:6950)
	at metabase.driver.sql_jdbc.sync.describe_database$fn__86536$describe_database__86537$fn__86538.invoke(describe_database.clj:178)
	at metabase.driver.redshift$fn__126791$fn__126793.invoke(redshift.clj:149)
	at metabase.driver.sql_jdbc.execute$fn__80825$do_with_resolved_connection__80826.invoke(execute.clj:333)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at malli.core$_instrument$fn__13258.doInvoke(core.cljc:2526)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at metabase.driver.redshift$fn__126791.invokeStatic(redshift.clj:137)
	at metabase.driver.redshift$fn__126791.invoke(redshift.clj:135)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.driver.sql_jdbc.sync.describe_database$fn__86536$describe_database__86537.invoke(describe_database.clj:164)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at malli.core$_instrument$fn__13258.doInvoke(core.cljc:2526)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.driver.sql_jdbc$fn__122674.invokeStatic(sql_jdbc.clj:84)
	at metabase.driver.sql_jdbc$fn__122674.invoke(sql_jdbc.clj:82)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.sync.fetch_metadata$fn__98002$db_metadata__98007$fn__98008.invoke(fetch_metadata.clj:15)
	at metabase.sync.fetch_metadata$fn__98002$db_metadata__98007.invoke(fetch_metadata.clj:12)
	at metabase.sync.sync_metadata$fn__100421$sync_db_metadata_BANG___100426$fn__100427.invoke(sync_metadata.clj:58)
	at metabase.sync.sync_metadata$fn__100421$sync_db_metadata_BANG___100426.invoke(sync_metadata.clj:55)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:75)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:66)
	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:85)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[227200c5-dffd-4f80-b5f9-1eb6d714c168] 2023-11-16T16:26:02+01:00 ERROR org.quartz.core.ErrorLogger Job (DEFAULT.metabase.task.sync-and-analyze.job threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: com.amazon.redshift.util.RedshiftException: Cannot rollback when autoCommit is enabled.]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: com.amazon.redshift.util.RedshiftException: Cannot rollback when autoCommit is enabled.
	at com.amazon.redshift.jdbc.RedshiftConnectionImpl.rollback(RedshiftConnectionImpl.java:1115)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.rollback(NewProxyConnection.java:1033)
	at metabase.driver.sql_jdbc.sync.describe_database$fn__86499.invokeStatic(describe_database.clj:96)
	at metabase.driver.sql_jdbc.sync.describe_database$fn__86499.invoke(describe_database.clj:80)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.driver.sql_jdbc.sync.describe_database$fast_active_tables$fn__86517.invoke(describe_database.clj:128)
	at clojure.core$filter$fn__5958$fn__5959.invoke(core.clj:2822)
	at clojure.core$preserving_reduced$fn__8848.invoke(core.clj:7682)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$cat$fn__8851.invoke(core.clj:7693)
	at clojure.core$map$fn__5931$fn__5932.invoke(core.clj:2759)
	at clojure.core$completing$fn__8528.invoke(core.clj:6931)
	at clojure.core$filter$fn__5958$fn__5959.invoke(core.clj:2823)
	at clojure.core$completing$fn__8528.invoke(core.clj:6931)
	at clojure.core$filter$fn__5958$fn__5959.invoke(core.clj:2823)
	at clojure.core$filter$fn__5958$fn__5959.invoke(core.clj:2823)
	at clojure.core$filter$fn__5958$fn__5959.invoke(core.clj:2823)
	at clojure.core$take_while$fn__5982$fn__5983.invoke(core.clj:2918)
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__85709.reduce(common.clj:39)
	at clojure.core$transduce.invokeStatic(core.clj:6946)
	at clojure.core.Eduction.reduce(core.clj:7750)
	at clojure.core$transduce.invokeStatic(core.clj:6946)
	at clojure.core.Eduction.reduce(core.clj:7750)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$reduce.invoke(core.clj:6868)
	at metabase.driver.redshift$reducible_schemas_with_usage_permissions$reify__126878.reduce(redshift.clj:340)
	at clojure.core$transduce.invokeStatic(core.clj:6946)
	at clojure.core.Eduction.reduce(core.clj:7750)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$into.invokeStatic(core.clj:6958)
	at clojure.core$into.invoke(core.clj:6950)
	at metabase.driver.sql_jdbc.sync.describe_database$fn__86536$describe_database__86537$fn__86538.invoke(describe_database.clj:178)
	at metabase.driver.redshift$fn__126791$fn__126793.invoke(redshift.clj:149)
	at metabase.driver.sql_jdbc.execute$fn__80825$do_with_resolved_connection__80826.invoke(execute.clj:333)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at malli.core$_instrument$fn__13258.doInvoke(core.cljc:2526)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at metabase.driver.redshift$fn__126791.invokeStatic(redshift.clj:137)
	at metabase.driver.redshift$fn__126791.invoke(redshift.clj:135)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.driver.sql_jdbc.sync.describe_database$fn__86536$describe_database__86537.invoke(describe_database.clj:164)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at malli.core$_instrument$fn__13258.doInvoke(core.cljc:2526)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.driver.sql_jdbc$fn__122674.invokeStatic(sql_jdbc.clj:84)
	at metabase.driver.sql_jdbc$fn__122674.invoke(sql_jdbc.clj:82)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.sync.fetch_metadata$fn__98002$db_metadata__98007$fn__98008.invoke(fetch_metadata.clj:15)
	at metabase.sync.fetch_metadata$fn__98002$db_metadata__98007.invoke(fetch_metadata.clj:12)
	at metabase.sync.sync_metadata$fn__100421$sync_db_metadata_BANG___100426$fn__100427.invoke(sync_metadata.clj:58)
	at metabase.sync.sync_metadata$fn__100421$sync_db_metadata_BANG___100426.invoke(sync_metadata.clj:55)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:75)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:66)
	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:85)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more
```

**Comment by metamben** [comment] 2023-11-22 22:59
Thanks, @paoliniluis, that confirms my assumption.

**Comment by JCWahoo** [comment] 2023-11-29 22:02
Does rolling back to 47.6 resolve this or do we need to wait for 47.9?

**Comment by MattKWill** [comment] 2023-12-01 15:32
> > Does rolling back to 47.6 resolve this or do we need to wait for 47.9?
> 
> Sorry appears rolling back didnt work unless I'm doing something wrong

Rolling back to 0.46.6 worked in my case.

**Comment by JCWahoo** [comment] 2023-12-04 13:43
Yep - Metabase still has access to everything, just won't scan or show up in schemas. I gave metabase user SUPERUSER perms so it shouldn't be anything permission-related

**Comment by JCWahoo** [comment] 2023-12-04 13:44
Looks like changing to "Some Schemas" has gotten them to show back up

**Comment by metamben** [comment] 2023-12-04 15:40
@JCWahoo can you give a new description of the problem? I have the feeling that you are experiencing an issue different from what ticket is about.

**Comment by paoliniluis** [comment] 2023-12-04 16:01
@JCWahoo what about memory, do you see the instance getting dying?

also, does the sync finishes?

**Comment by JCWahoo** [comment] 2023-12-04 16:04
No issues with the instance. I've only seen a scheduled sync finish, but not a manual one. The sync isnt reported at all in the logs which is odd.

Just tried another manual sync and will monitor.

**Comment by JCWahoo** [comment] 2023-12-04 16:05
It does appear the sync is now running, although there is no sync started message - Logs have these, which is expected as I have lots of SUPER columns so I know its doing something

[5c303d59-8a00-4a5b-a0fa-4389cb7c06e2] 2023-12-04T11:04:50-05:00 WARN metabase.driver.sql-jdbc.sync.describe-table Don't know how to map column type 'super' to a Field base_type, falling back to :type/*.

**Comment by darksciencebase** [comment] 2023-12-04 17:53
adding the milestone back since we got reports of the fix working for other people

**Comment by darksciencebase** [comment] 2023-12-08 14:44
Looks like the original issue has been fixed (we got more reports about it working), so I will close this now. @JCWahoo if the problem you're seeing persists, please open another bug about that specific problem.

**Closed by darksciencebase** 2023-12-08 14:44 UTC
Labels: Type:Bug, Priority:P1, Administration/Metadata & Sync, .Backend, .Regression, .Team/QueryProcessor
