### ISSUE TITLE
Cannot uncheck all table columns

### ISSUE THREAD

**Issue by ansidev** [metabase/metabase#19486] opened 2021-12-27 08:58 UTC
**Describe the bug**
Some table has too many columns, but I want to select some of them.
By default, there is no uncheck all options.
I uncheck manually and because Metabase UI has bugs so I can't do it.

**To Reproduce**
See the recorded clip:

https://user-images.githubusercontent.com/6688235/147453894-3e02e3ad-73d0-48d1-88c9-f62d8641e2a9.mov

**Expected behaviour**
I can uncheck all columns by unchecking the checkbox `Select all`.

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 96.0.4664.110
- Your operating system: macOS Monterey 12.1
- Your databases: MariaDB
- Metabase version: 0.41.5
- Metabase hosting environment: Docker on Ubuntu 20.04
- Metabase internal database: PostgresSQL

**Severity**
Blocking usage.

**Comment by flamber** [comment] 2021-12-27 09:19
Duplicate of #10460

**Closed by flamber** 2021-12-27 09:19 UTC
Labels: Type:Bug, .Needs Triage
