### ISSUE TITLE
[Privacy] Metabase loads google analytics on self-hosted dashboards, even if you opt-out of usage tracking

### ISSUE THREAD

**Issue by exabrial** [metabase/metabase#9699] opened 2019-04-05 17:37 UTC
* metabase version: 0.32.2
* JDK: 1.8 AdoptOpenJDK

Hey guys,

One of the reasons we have to self-host Metabase is because we're in finance. We have to be extraordinarily careful of what information is sent to the outside world. We noticed on the dashboard pages, Google analytics is still being loaded even if anonymous tracking is disabled.

It looks like there's an attempt to prevent tracking in place, thank you for that.

But, the script still loads on page load, sending information to Google. It would be best if the script wasn't allowed to load at all if anonymous tracking is disabled.

Thank you for a great product and giving us the option to control our privacy.

Excerpt from dashboard page:

```
<script type="text/javascript">
--
  | (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]\|\|function(){
  | (i[r].q=i[r].q\|\|[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  | m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  | })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  |  
  | // if we are not doing tracking then go ahead and disable GA now so we never even track the initial pageview
  | const tracking = window.MetabaseBootstrap.anon_tracking_enabled;
  | const ga_code = window.MetabaseBootstrap.ga_code;
  | if (!tracking) {
  | window['ga-disable-'+ga_code] = true;
  | }
  |  
  | ga('create', ga_code, 'auto');
  | </script>
```

Setting is disabled:
![Screen Shot 2019-04-05 at 12 34 02 PM](https://user-images.githubusercontent.com/1392297/55645899-68223680-579f-11e9-9ee1-d86791148538.png)

Load still happens, sending our IP and other information to Google:
![Screen Shot 2019-04-05 at 12 36 42 PM](https://user-images.githubusercontent.com/1392297/55645969-97d13e80-579f-11e9-8e20-7287132e4ad0.png)

**Comment by flamber** [comment] 2019-04-05 18:08
Duplicate of #9464 - go and upvote by clicking :+1: - for workaround see https://github.com/metabase/metabase/issues/2677#issuecomment-458654023

**Comment by camsaul** [comment] 2019-04-05 18:25
Thanks @flamber 

Closing as duplicate of #9464

**Closed by camsaul** 2019-04-05 18:25 UTC
