### ISSUE TITLE
Field Filters tied to a field that contains a period break the query

### ISSUE THREAD

**Issue by ProteanHub** [metabase/metabase#19884] opened 2022-01-24 18:14 UTC
**Describe the bug**
When using a field filter variable in a custom SQL question, a field name with a period in it causes the query to fail.

**Logs**
No need, but I do have a screenshot of the specific issue attached.

**To Reproduce**
Create a custom SQL question. Use a variable such as {{DATE1}} and then in the options tie it to a field that contains a period in the name of the field.

**Expected behavior**
Fields tied to custom variables need to have backticks so they are not interpreted as part of the db/table/field delineation. Example: database_name.table_name.field_name : if the field is "something.01", that translates to database_name.table_name.something.01 which breaks the query. It should be database_name.table_name.`something.01`

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Safari 15.2
- Your operating system: Ubuntu 20.04
- Your databases: MySQL
- Metabase version: 0.41.6
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

**Severity**
Completely breaking question with no acceptable workaround.
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

<img width="1780" alt="Screen Shot 2022-01-24 at 1 01 12 PM" src="https://user-images.githubusercontent.com/1413491/150840344-bc21bddd-f315-42db-9180-9295c3bb72aa.png">

**Comment by flamber** [comment] 2022-01-24 19:17
Duplicate of #13932 - fixed in the upcoming 0.42

**Closed by flamber** 2022-01-24 19:17 UTC
Labels: Type:Bug, .Needs Triage

**Comment by ProteanHub** [comment] 2022-01-24 19:23
Sorry I missed the duplicate. Did a search for "period" but not "dot". Thanks for the quick update.
