### ISSUE TITLE
Missing timezone when query date field by time-interval

### ISSUE THREAD

**Issue by shixiaobao17145** [metabase/metabase#19339] opened 2021-12-13 02:16 UTC
**Describe the bug**
When query date field by "Previous","Next","Current", the timezone is missing in server to calculate the $match condition. While the other query types like "Before","After","On", "Between" works fine. 

> The datasource is in Mongo

**To Reproduce**
1. Set metabase JAVA_HOME timezone to be 'Asia/Shanghai'
2. Connect to Mongo database source
3. Filter date type column with "Previous","Next" or "Current"
4. See the result will always missing the data before 8:00 AM

### **Screenshots**
**filter by 'time-interval'(unexpected):**

![image](https://user-images.githubusercontent.com/1640561/145744996-43bfd52b-cab5-4d13-a38a-1d14e61bb028.png)
![image](https://user-images.githubusercontent.com/1640561/145745214-d1ef12f0-fdc1-4cd2-879f-a660cd0d9ade.png)
![image](https://user-images.githubusercontent.com/1640561/145745299-fed111e0-5266-42c5-afe3-81a0a7cdae5b.png)

**filter by 'on'(expected):**

![image](https://user-images.githubusercontent.com/1640561/145746000-bc972198-ee16-4711-a69b-a30b288f9d43.png)
![image](https://user-images.githubusercontent.com/1640561/145746103-d4e95d56-a03a-437f-a74e-06dd0796a9c4.png)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36 Edg/96.0.1054.53",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "5.10.47-linuxkit",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.14 (Debian 11.14-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-12-10",
      "tag": "v0.41.4",
      "branch": "release-x.41.4",
      "hash": "471cfb9"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by flamber** [comment] 2021-12-13 10:16
Duplicate of #14233

**Closed by flamber** 2021-12-13 10:16 UTC
Labels: Type:Bug, .Needs Triage
