### ISSUE TITLE
Segment tips not show

### ISSUE THREAD

**Issue by gaodazhu** [metabase/metabase#7455] opened 2018-04-26 02:37 UTC
When I choose the filter and hover the segments info icon at the end , the error show on console, and no description tip show!

Could not find "store" in either the context or props of "Connect(Remapped[RemappedValueContent])". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Remapped[RemappedValueContent])"

- browser and the version: (Chrome 65)
- operating system: (Win 10)
- databases: (Postgres)
- Metabase version: (0.29)
- Metabase hosting environment: (redhat)
- Metabase internal database: (Postgres)

**Comment by flamber** [comment] 2019-02-20 04:05
Hi @gaodazhu 
I cannot reproduce your issue on 0.31.2 with Firefox 65 or Chromium 71. Could you try the newer version of Metabase and see if the problem is fixed?
![screenshot_00003](https://user-images.githubusercontent.com/1447303/53065673-5f490000-3492-11e9-9cbc-2598ba6aa478.png)

**Comment by mazameli** [comment] 2019-10-10 23:47
This specific bug is from an old version and it doesn't seem reproducible, so I'm closing this.

However, the tooltip for segments in 0.33.4 isn't showing up at all now, which I think is an omission rather than a bug. I'll search for an existing issue or create a new one for that.

**Closed by mazameli** 2019-10-10 23:47 UTC
Labels: Priority:P3, Query Builder, Type:Bug
