### ISSUE TITLE
Uncaught exception when fingerprinting fails

### ISSUE THREAD

**Issue by joekohlsdorf** [metabase/metabase#12652] opened 2020-06-05 15:50 UTC
**Describe the bug**

When the Metabase user doesn't have permissions to access a table, fingerprinting fails with an uncaught exception logging a stack trace.
This started occurring after updating from v0.35.2 to v0.35.4 and was most likely introduced in https://github.com/metabase/metabase/pull/12575.

**Logs**

```
06-05 15:17:41 ERROR sync.util :: Error fingerprinting Table 3,017 'redacted.redacted'
org.postgresql.util.PSQLException: ERROR: permission denied for schema redacted
  Position: 7044
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)
	at metabase.driver.sql_jdbc.execute$fn__70879.invokeStatic(execute.clj:267)
	at metabase.driver.sql_jdbc.execute$fn__70879.invoke(execute.clj:265)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:389)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)
	at metabase.driver.sql_jdbc$fn__73052.invokeStatic(sql_jdbc.clj:49)
	at metabase.driver.sql_jdbc$fn__73052.invoke(sql_jdbc.clj:47)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.query_processor.context$executef.invokeStatic(context.clj:59)
	at metabase.query_processor.context$executef.invoke(context.clj:48)
	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:69)
	at metabase.query_processor.context.default$default_runf.invoke(default.clj:67)
	at metabase.query_processor.context$runf.invokeStatic(context.clj:45)
	at metabase.query_processor.context$runf.invoke(context.clj:39)
	at metabase.query_processor.reducible$pivot.invokeStatic(reducible.clj:34)
	at metabase.query_processor.reducible$pivot.invoke(reducible.clj:31)
	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__43149.invoke(mbql_to_native.clj:26)
	at metabase.query_processor.middleware.check_features$check_features$fn__42463.invoke(check_features.clj:42)
	at metabase.query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__43314.invoke(optimize_datetime_filters.clj:133)
	at metabase.query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47282.invoke(wrap_value_literals.clj:137)
	at metabase.query_processor.middleware.annotate$add_column_info$fn__41084.invoke(annotate.clj:577)
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__42338.invoke(permissions.clj:64)
	at metabase.query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__43813.invoke(pre_alias_aggregations.clj:40)
	at metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__42536.invoke(cumulative_aggregations.clj:61)
	at metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__44345.invoke(resolve_joins.clj:183)
	at metabase.query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39271.invoke(add_implicit_joins.clj:245)
	at metabase.query_processor.middleware.limit$limit$fn__43135.invoke(limit.clj:38)
	at metabase.query_processor.middleware.format_rows$format_rows$fn__43116.invoke(format_rows.clj:81)
	at metabase.query_processor.middleware.desugar$desugar$fn__42602.invoke(desugar.clj:22)
	at metabase.query_processor.middleware.binning$update_binning_strategy$fn__41628.invoke(binning.clj:229)
	at metabase.query_processor.middleware.resolve_fields$resolve_fields$fn__42144.invoke(resolve_fields.clj:24)
	at metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__38807.invoke(add_dimension_projections.clj:272)
	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39027.invoke(add_implicit_clauses.clj:147)
	at metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39420.invoke(add_source_metadata.clj:105)
	at metabase.query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__44010.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)
	at metabase.query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__41269.invoke(auto_bucket_datetimes.clj:125)
	at metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__42191.invoke(resolve_source_table.clj:46)
	at metabase.query_processor.middleware.parameters$substitute_parameters$fn__43795.invoke(parameters.clj:97)
	at metabase.query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__42243.invoke(resolve_referenced.clj:80)
	at metabase.query_processor.middleware.expand_macros$expand_macros$fn__42858.invoke(expand_macros.clj:158)
	at metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__39451.invoke(add_timezone_info.clj:15)
	at metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47166.invoke(splice_params_in_response.clj:32)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__44021$fn__44025.invoke(resolve_database_and_driver.clj:33)
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:61)
	at metabase.driver$do_with_driver.invoke(driver.clj:57)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__44021.invoke(resolve_database_and_driver.clj:27)
	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__43064.invoke(fetch_source_query.clj:243)
	at metabase.query_processor.middleware.store$initialize_store$fn__47175$fn__47176.invoke(store.clj:11)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:44)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:40)
	at metabase.query_processor.middleware.store$initialize_store$fn__47175.invoke(store.clj:10)
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__42120.invoke(cache.clj:209)
	at metabase.query_processor.middleware.validate$validate_query$fn__47184.invoke(validate.clj:10)
	at metabase.query_processor.middleware.normalize_query$normalize$fn__43162.invoke(normalize_query.clj:22)
	at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39289.invoke(add_rows_truncated.clj:36)
	at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47151.invoke(results_metadata.clj:124)
	at metabase.query_processor.reducible$async_qp$qp_STAR___38090$thunk__38091.invoke(reducible.clj:101)
	at metabase.query_processor.reducible$async_qp$qp_STAR___38090.invoke(reducible.clj:107)
	at metabase.query_processor.reducible$async_qp$qp_STAR___38090.invoke(reducible.clj:94)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___38099$fn__38100.invoke(reducible.clj:129)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___38099.invoke(reducible.clj:128)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.query_processor$process_query.invokeStatic(query_processor.clj:124)
	at metabase.query_processor$process_query.doInvoke(query_processor.clj:118)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.Var.invoke(Var.java:384)
	at metabase.db.metadata_queries$fn__51972$table_rows_sample__51977$fn__51978.invoke(metadata_queries.clj:104)
	at metabase.db.metadata_queries$fn__51972$table_rows_sample__51977.invoke(metadata_queries.clj:100)
	at metabase.sync.analyze.fingerprint$fn__52038$fingerprint_table_BANG___52043$fn__52044.invoke(fingerprint.clj:63)
	at metabase.sync.analyze.fingerprint$fn__52038$fingerprint_table_BANG___52043.invoke(fingerprint.clj:43)
	at metabase.sync.analyze.fingerprint$fn__52211$fingerprint_fields_BANG___52216$fn__52217$fn__52218.invoke(fingerprint.clj:166)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
	at metabase.sync.analyze.fingerprint$fn__52211$fingerprint_fields_BANG___52216$fn__52217.invoke(fingerprint.clj:164)
	at metabase.sync.analyze.fingerprint$fn__52211$fingerprint_fields_BANG___52216.invoke(fingerprint.clj:160)
	at metabase.sync.analyze.fingerprint$fn__52239$fingerprint_fields_for_db_BANG___52244$fn__52245$fn__52246$iter__52247__52251$fn__52252$fn__52253.invoke(fingerprint.clj:184)
	at metabase.sync.analyze.fingerprint$fn__52239$fingerprint_fields_for_db_BANG___52244$fn__52245$fn__52246$iter__52247__52251$fn__52252.invoke(fingerprint.clj:181)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:59)
	at clojure.core$chunk_next.invokeStatic(core.clj:708)
	at clojure.core$reduce1.invokeStatic(core.clj:942)
	at clojure.core$reduce1.invokeStatic(core.clj:934)
	at clojure.core$merge_with.invokeStatic(core.clj:3059)
	at clojure.core$merge_with.doInvoke(core.clj:3051)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.sync.analyze.fingerprint$fn__52239$fingerprint_fields_for_db_BANG___52244$fn__52245$fn__52246.invoke(fingerprint.clj:181)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:46)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:40)
	at metabase.sync.analyze.fingerprint$fn__52239$fingerprint_fields_for_db_BANG___52244$fn__52245.invoke(fingerprint.clj:178)
	at metabase.sync.analyze.fingerprint$fn__52239$fingerprint_fields_for_db_BANG___52244.invoke(fingerprint.clj:172)
	at metabase.sync.analyze$make_analyze_steps$fn__52385.invoke(analyze.clj:108)
	at metabase.sync.util$fn__44568$run_step_with_metadata__44573$fn__44577$fn__44579.invoke(util.clj:345)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:119)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:116)
	at metabase.sync.util$fn__44568$run_step_with_metadata__44573$fn__44577.invoke(util.clj:342)
	at metabase.sync.util$fn__44568$run_step_with_metadata__44573.invoke(util.clj:337)
	at metabase.sync.util$fn__44760$run_sync_operation__44765$fn__44766$fn__44767.invoke(util.clj:430)
	at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$mapv.invokeStatic(core.clj:6903)
	at clojure.core$mapv.invoke(core.clj:6903)
	at metabase.sync.util$fn__44760$run_sync_operation__44765$fn__44766.invoke(util.clj:430)
	at metabase.sync.util$fn__44760$run_sync_operation__44765.invoke(util.clj:424)
	at metabase.sync.analyze$fn__52397$analyze_db_BANG___52402$fn__52403$fn__52404.invoke(analyze.clj:125)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:145)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
	at clojure.core$partial$fn__5839.invoke(core.clj:2623)
	at metabase.driver$fn__22363.invokeStatic(driver.clj:537)
	at metabase.driver$fn__22363.invoke(driver.clj:537)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__44480.invoke(util.clj:138)
	at metabase.sync.util$with_db_logging_disabled$fn__44477.invoke(util.clj:129)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
	at metabase.sync.util$with_start_and_finish_logging$fn__44466.invoke(util.clj:114)
	at metabase.sync.util$with_sync_events$fn__44461.invoke(util.clj:88)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__44452.invoke(util.clj:67)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:164)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:161)
	at metabase.sync.analyze$fn__52397$analyze_db_BANG___52402$fn__52403.invoke(analyze.clj:122)
	at metabase.sync.analyze$fn__52397$analyze_db_BANG___52402.invoke(analyze.clj:117)
	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:42)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
```

**To Reproduce**

Revoke permissions for the Metabase user on a table and try to fingerprint it.

**Expected behavior**

The exception gets caught and a proper error message is shown, without logging a stack trace.

**Information about your Metabase Installation:**

- Your browser and the version: irrelevant
- Your operating system: irrelevant
- Your databases: Postgres
- Metabase version: v0.35.4
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**

Low

**Comment by flamber** [comment] 2020-06-05 16:41
Hi @joekohlsdorf 
Thanks for digging around. So I think you're right that it's caused by the GA fix (#12575), but that actually solved a problem, where fingerprinting process could crash completely, which is why you probably never saw the errors about failed fingerprints before, since they were not scanned.
This sounds like a duplicate of #10139, which will be fixed by #10892 - do you agree?

**Comment by joekohlsdorf** [comment] 2020-06-05 17:05
While these two issues would solve the problem I reported, my opinion is that a full stack trace is not useful to the user. The error the database adapter returns is sufficient to see what the problem is and the rest is unrelated noise.
I propose to catch the exception and to log just the error message.

**Comment by landreville** [comment] 2020-08-05 19:24
Thanks for the info.

I'm poking around in the internal database to see if I can fix it.

So far I've found that metabase_field rows with active = false are displayed in the foreign key target drop downs. It also appears that some metabase_fields have been changed to have visibility type "sensitive" during the upgrade and these do not appear in the target drop downs or on the data model pages.

I've deleted the inactive fields and changed all records from visibility_type sensitive to normal. This at least lets me manually choose the correct targets.

**Comment by camsaul** [comment] 2020-09-30 21:05
It looks like this error *is* caught, which is why we're logging it. 

If we try to fingerprint something and can't for some reason it's expected behavior to log the error and move on. 

Since sync happens asynchronously we don't really have a place to show those sorts of sync errors to the user outside of the logs at this point.

**Comment by camsaul** [comment] 2020-09-30 21:06
The actual cause of the error that gets logged is #10139, so I'm going to close this as a duplicate.

**Closed by camsaul** 2020-09-30 21:06 UTC
Labels: Administration/Metadata & Sync, Administration/Troubleshooting, Priority:P3, Type:UX

**Comment by dpsutton** [comment] 2020-10-14 20:36
@rlotun i'm unassigning myself as this error is logged and the linked ticket (https://github.com/metabase/metabase/issues/10139) is closed. I think there's nothing to do here unless @joekohlsdorf (issue reporter) has any objection.
