### ISSUE TITLE
Date format in pivot table incorrect (DD.MM.YYYY)

### ISSUE THREAD

**Issue by AdrianM** [metabase/metabase#23625] opened 2022-06-30 07:05 UTC
In our Metabase (v1.41.5), the pivot table with a date column shows the date incorrect for the sum line if we choose the date format '(day, month, year)'. The date is then shown as 'MM.DD.YYYY' instead of 'DD.MM.YYYY' (screenshot 1). As soon as we change the format to 'DD Month YYYY', it is working properly (screenshot 2).

<img width="536" alt="screenshot1" src="https://user-images.githubusercontent.com/8291/176613401-53b7a28e-1427-4a78-9009-ac4e2a5513e3.png">

<img width="536" alt="screenshot2" src="https://user-images.githubusercontent.com/8291/176613431-5e08703d-f97d-4375-9257-6213cd4f053a.png">

Just as a hint: the feature with conditional formatting in pivot tables would be extremely helpful for our business cases (https://github.com/metabase/metabase/issues/15693)

Thanks and regards,
Adrian

**Comment by flamber** [comment] 2022-06-30 07:33
Duplicate of #23076

**Closed by flamber** 2022-06-30 07:33 UTC
Labels: Type:Bug, .Needs Triage
