### ISSUE TITLE
cassandra database?

### ISSUE THREAD

**Issue by xujingzhou** [metabase/metabase#11402] opened 2019-11-28 06:43 UTC
Hi, 
 metabase can support cassandra?

**Comment by flamber** [comment] 2019-11-28 06:49
Hi @xujingzhou 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Have you tried to search? Duplicate of #2049 - upvote by clicking :+1: on the first post.
And please close this issue.

**Closed** 2019-12-01 11:24 UTC
Labels: .Needs Triage, Type:Question
