### ISSUE TITLE
[0.31.0] Unable to get tables name in a custom query

### ISSUE THREAD

**Issue by knightmano** [metabase/metabase#8914] opened 2018-11-09 18:50 UTC
Hello,

First, thanks for your amazing product. We recently updated our Metabase to version 0.31 (from 0.30) and encountered a server error while trying to get table names for a custom query.

A hard refresh on our browser or rescan of our databases' tables didn't help us.

Please find here our configuration:

- Your browser and the version:  Google Chrome, version 70.0.3538.77 (64 bits)
- Your operating system: Ubuntu 18.04
- Your databases: Redshift and MariaDB
- Metabase version: 0.31.0 (stable release)
- Metabase hosting environment: Docker on Ubuntu
- Metabase internal database: MariaDB 10.2.12

JS errors:

![image](https://user-images.githubusercontent.com/44907099/48282121-0ad8c200-e459-11e8-8d4f-267b3b8aa33b.png)

Metabase Logs: 

> Nov 09 19:48:51 ERROR metabase.middleware :: GET /api/database 500 (886 ms) (5 DB calls).
{:value [nil],
:error [(named (named (not (matches-some-precondition? nil)) "Keyword or string") token)],
:message "Input to normalize-token does not match schema: \n\n\t [(named (named (not (matches-some-precondition? nil)) \"Keyword or string\") token)] \n\n",
:type clojure.lang.ExceptionInfo,
:stacktrace
("--> mbql.util$fn__18719$normalize_token__18724.invoke(util.clj:14)"
"mbql.normalize$normalize_template_tags$iter__19397__19401$fn__19402.invoke(normalize.clj:201)"
"mbql.normalize$normalize_template_tags.invokeStatic(normalize.clj:198)"
"mbql.normalize$normalize_template_tags.invoke(normalize.clj:194)"
"mbql.normalize$normalize_tokens.invokeStatic(normalize.clj:253)"
"mbql.normalize$normalize_tokens.doInvoke(normalize.clj:235)"
"mbql.normalize$normalize_tokens$iter__19441__19445$fn__19446.invoke(normalize.clj:265)"
"mbql.normalize$normalize_tokens.invokeStatic(normalize.clj:263)"
"mbql.normalize$normalize_tokens.doInvoke(normalize.clj:235)"
"mbql.normalize$normalize_tokens$iter__19441__19445$fn__19446.invoke(normalize.clj:265)"
"mbql.normalize$normalize_tokens.invokeStatic(normalize.clj:263)"
"mbql.normalize$normalize_tokens.doInvoke(normalize.clj:235)"
"models.interface$maybe_normalize.invokeStatic(interface.clj:62)"
"models.interface$maybe_normalize.invoke(interface.clj:61)"
"api.database$source_query_cards.invokeStatic(database.clj:105)"
"api.database$source_query_cards.invoke(database.clj:102)"
"api.database$cards_virtual_tables.invokeStatic(database.clj:118)"
"api.database$cards_virtual_tables.doInvoke(database.clj:113)"
"api.database$saved_cards_virtual_db_metadata.invokeStatic(database.clj:123)"
"api.database$saved_cards_virtual_db_metadata.doInvoke(database.clj:121)"
"api.database$add_virtual_tables_for_saved_cards.invokeStatic(database.clj:132)"
"api.database$add_virtual_tables_for_saved_cards.invoke(database.clj:131)"
"api.database$dbs_list.invokeStatic(database.clj:139)"
"api.database$dbs_list.invoke(database.clj:137)"
"api.database$fn__45154.invokeStatic(database.clj:150)"
"api.database$fn__45154.invoke(database.clj:143)"
"middleware$enforce_authentication$fn__55497.invoke(middleware.clj:113)"
"api.routes$fn__55649.invokeStatic(routes.clj:65)"
"api.routes$fn__55649.invoke(routes.clj:65)"
"routes$fn__56385$fn__56386.doInvoke(routes.clj:108)"
"routes$fn__56385.invokeStatic(routes.clj:103)"
"routes$fn__56385.invoke(routes.clj:103)"
"middleware$catch_api_exceptions$fn__55632.invoke(middleware.clj:436)"
"middleware$log_api_call$fn__55610$fn__55612.invoke(middleware.clj:364)"
"middleware$log_api_call$fn__55610.invoke(middleware.clj:363)"
"middleware$add_security_headers$fn__55552.invoke(middleware.clj:252)"
"core$wrap_streamed_json_response$fn__57236.invoke(core.clj:67)"
"middleware$bind_current_user$fn__55502.invoke(middleware.clj:137)"
"middleware$maybe_set_site_url$fn__55562.invoke(middleware.clj:290)"
"middleware$add_content_type$fn__55555.invoke(middleware.clj:262)")}

If you need further information, do not hesitate!

Best regards,

**Comment by camsaul** [comment] 2018-11-09 20:13
Hi @knightmano can you add the full response from that API call? It would be helpful for debugging it

**Comment by knightmano** [comment] 2018-11-09 20:32
Hi @camsaul,

Is this log file suitable for your investigations?

[metabase_issue_8914_stacktrace.txt](https://github.com/metabase/metabase/files/2567428/metabase_issue_8914_stacktrace.txt)

Good luck!

**Comment by jonathanstidwillvf** [comment] 2018-11-10 17:46
I get a similar error after upgrading to 0.31. When I'm editing a question, and try to add it to a dashboard, I get: "Input to normalize-token does not match schema: [0;33m [(named (named (not (matches-some-precondition? nil)) "Keyword or string") token)] [0m".

It also fails, when I try to add a question to a dashboard directly, but with a different error:
vendor.bundle.js?78e15b587bf48274efb7:96 
Uncaught TypeError: Cannot read property 'id' of undefined
    at app-main.bundle.js?78e15b587bf48274efb7:5
    at app-main.bundle.js?78e15b587bf48274efb7:5
    at Object.addCardToDashboard (vendor.bundle.js?78e15b587bf48274efb7:145)
    at r.onAdd (app-main.bundle.js?78e15b587bf48274efb7:5)
    at onChange (app-main.bundle.js?78e15b587bf48274efb7:5)
    at S.u.default.createElement.onClick (app-main.bundle.js?78e15b587bf48274efb7:5)
    at Object.i (vendor.bundle.js?78e15b587bf48274efb7:96)
    at s (vendor.bundle.js?78e15b587bf48274efb7:96)
    at Object.executeDispatchesInOrder (vendor.bundle.js?78e15b587bf48274efb7:96)
    at h (vendor.bundle.js?78e15b587bf48274efb7:94)

**Comment by rredhatt** [comment] 2018-11-13 05:04
Same error here when trying to add a newly created question to a dashboard.

ERROR - Input to normalize-token does not match schema: [0;33m [(named (named (not (matches-some-precondition? nil)) "Keyword or string") token)] [0m

**Comment by khalidsalomao** [comment] 2018-11-16 20:03
Yes, after upgrade from `0.30.1` to `0.31.0` it is no longer possible to update a dashboard by adding a question. The same error happens on a newly created dashboard and trying to add a question.

![image](https://user-images.githubusercontent.com/1336766/48644467-ceade000-e9c9-11e8-84ea-05c34a070c0a.png)

**Comment by camsaul** [comment] 2018-11-20 01:15
So this is an issue where it's trying to parse the parameters passed into a query and they're not what it expects.

@knightmano @khalidsalomao @rredhatt @jonathanstidwillvf @CyrilVinot @Charles-Go @jamesbloomer @freelancerlucas @ehulsbosch @rkaram @shimoju could you give me a little more details? What sort of parameters do the failing questions/dashboards have? Does anyone know how to repro this (preferably with the Sample Dataset?) Could someone post the entire failing API response?

I will fix this tonight but I need to figure out how to repro it first.

**Comment by camsaul** [comment] 2018-11-20 02:39
Ok, @tlrobinson or I can't really figure out how it was possible to generate queries with invalid parameter info in the first place. Since older versions of Metabase didn't validate queries and parameters before saving some invalid Questions or Dashboards must have snuck in along the way, causing this error now when we can't figure out how to parse it. Either way, as far as I can tell it's impossible to save new Questions and Dashboards in a way that could cause this error since we validate using the same checks before saving. Of course, new Questions in old dashboards might still see this issue.

I made some tweaks to fail gracefully if a Question/parameter is invalid instead of letting the entire API call fail. It logs additional information about the unparseable property as well which might make it easier to figure out how things got in a bad state in the first place, in which case I might be able to come up with fixes that correct the invalid properties rather than ignoring it entirely. 

Fixed by #8914

**Closed** 2018-11-20 02:40 UTC
Labels: Bug, Query Processor

**Comment by jonathanstidwillvf** [comment] 2018-11-21 14:49
The new version uploaded to Docker hub (v0.31.1) resolved the problem for me. Try that.

**Comment by adjenks** [comment] 2019-09-10 22:54
I got this error on the latest version:
`Input to normalize-token does not match schema`

**Comment by flamber** [comment] 2019-09-10 23:07
@adjenks 0.33.2? Which database are you querying? Do you have steps-to-reproduce? I think you're probably seeing a separate issue, the error is not unique, so maybe it's better to create a new issue.
