### ISSUE TITLE
Error when try to search a question to add in a dashboard

### ISSUE THREAD

**Issue by fer-batista** [metabase/metabase#49169] opened 2024-10-25 14:35 UTC
### Describe the bug

Search bar used to find a question and add them to a dashboard is not working.
Unexpected character ('2' (code 50)): was expecting comma to separate Object entries at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 179]

![Image](https://github.com/user-attachments/assets/adb77ad8-1794-43e4-810e-f08ca5f7946a)

### To Reproduce

1. Go to a dashboard
2. Click on add questions
3. Use the search box

### Information about your Metabase installation

{
  "browser-info": {
    "language": "pt-BR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql",
      "bigquery-cloud-sdk"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-self-hosted-yearly",
    "version": {
      "date": "2024-10-23",
      "tag": "v1.51.1",
      "hash": "b8178a8"
    },
    "settings": {
      "report-timezone": "America/Sao_Paulo"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "6.1.90+",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}

### Severity

P3

**Comment by dpsutton** [comment] 2024-10-25 14:48
@fer-batista can you provide the logs that appear in the backend when this error happens?

**Comment by fer-batista** [comment] 2024-10-25 14:58
https://github.com/user-attachments/assets/ca8ea256-46f2-4a3a-b2c3-0ca7df04d8ec

**Comment by fer-batista** [comment] 2024-10-25 15:01
https://github.com/user-attachments/assets/3798a338-cb71-49c0-889d-911aec8d3ed7

**Comment by dpsutton** [comment] 2024-10-25 15:56
Weird. That is erroring out because there is invalid json for one of the card's queries.
https://github.com/metabase/metabase/blob/master/src/metabase/search/impl.clj#L177

```clojure
        (update :dataset_query (fn [dataset-query]
                                 (when-let [query (some-> dataset-query json/parse-string)] ;; <--- error is happening here
                                   (if (get query "type")
                                     (mbql.normalize/normalize query)
                                     (not-empty (lib/normalize query))))))
```

This should be impossible. Have you perhaps done any edits to the application database?

I'm trying to think of the easiest way to see which questions have invalid queries

**Comment by dpsutton** [comment] 2024-10-25 20:54
Sure. This is the `report_card` table. It has a text column `dataset_query` which should always be valid json. You have a row (or multiple) which match your search term which have invalid json.

**Comment by fer-batista** [comment] 2024-10-26 13:03
Nothing found when I query the table.

![Image](https://github.com/user-attachments/assets/fc4645fd-a950-48c6-b721-7c464f60521d)

**Comment by fer-batista** [comment] 2024-10-26 13:57
@dpsutton Hey! Thank you for the hint.
I got all the dataset_query and used BigQuery to SAFE.PARSE_JSON.
This returned all the queries with parsed JSON and I filtered only on error and then deleted it from the application database.
Now the search box is working!
![Image](https://github.com/user-attachments/assets/dae5739f-0c2c-4394-9cd6-cb390720cc20)

**Comment by paoliniluis** [comment] 2024-10-26 18:52
@fer-batista can you send the wrong json so we can try to reproduce?

**Comment by dpsutton** [comment] 2024-10-30 12:22
I'm going to close this as it seems it arose due to you changing data in the application database. If this is not correct, we want to work on it with the highest priority. We should never have invalid json in that table. If that was our fault, please let us know. But it seems we didn't cause it so nothing left to do.

**Closed by dpsutton** 2024-10-30 12:22 UTC
Labels: Type:Bug, .Needs Triage
