### ISSUE TITLE
Filters look misaligned when there's no value

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2211] opened 2016-03-22 22:45 UTC
![screen shot 2016-03-22 at 3 45 19 pm](https://cloud.githubusercontent.com/assets/18193/13970297/1c0c507e-f045-11e5-8d43-775fc1b028e8.png)

**Comment by kdoh** [comment] 2017-06-28 04:33
Looks like #3531 was a duplicate of this and #4118 fixed this.

**Closed by kdoh** 2017-06-28 04:33 UTC
Labels: Query Builder, UX
