### ISSUE TITLE
Relative date widget yields wrong date range for past 30 days

### ISSUE THREAD

**Issue by Overbryd** [metabase/metabase#6554] opened 2017-12-11 13:07 UTC
### Bug

Running Metabase `0.27.1` on the target database (MySQL).
On both, the "Report Timezone" is set to "Europe/Berlin".

The Metabase version `0.27.1` seems to yield the wrong date range when selecting "Past 30 Days".
I am querying a dataset on a `DATETIME` field for the past 30 days. **Today is `Mon, 11. Dec`**, so I expect to have `Sun, 10. Dec` included in the daterange.

The log output, and the results, state otherwise. Metabase seems to exclude `Sun, 10. Dec` and starts the past 30 days range with `Sat, 09. Dec`.

Here is a screenshot of what I am trying to achieve in the UI.

<img width="831" alt="screen shot 2017-12-11 at 14 01 46" src="https://user-images.githubusercontent.com/21111/33832430-6c26a6f0-de7c-11e7-8e0c-803a33a723eb.png">

Here is the snip from the log captured output:

```console
(#inst "2017-11-10T23:00:00.000000000-00:00" #inst "2017-12-09T23:00:00.000000000-00:00")
```

**Comment by jornh** [comment] 2017-12-11 18:53
https://metabase.com/docs/latest/troubleshooting-guide/timezones.html contains suggestions for debugging timezone related problems.

In your case I suspect “SQL queries are not respecting the Reporting Time Zone setting” might be the problem biting you.

**Comment by Overbryd** [comment] 2017-12-11 20:25
It must be a problem that was introduced between `0.25` and `0.27` somehow.
We have a `0.25` installation running, and the exact same questions yield the same results.

This problem currently hinders us from upgrading to `0.27`.

**Comment by senior** [comment] 2018-01-05 22:33
I've done some digging on this issue and I think it's related to a bug in the MySQL driver. On the Metabase side, I think https://github.com/metabase/metabase/pull/5729 broke it for MySQL. That PR uses the JDBC standard way of specifying a timezone for a date/timestmap query parameter. Unfortunately due to [this bug](https://bugs.mysql.com/bug.php?id=80201) in the MySQL driver, the date/timestamp query parameters are adjusted incorrectly.

We just merged a work-around for this bug with https://github.com/metabase/metabase/pull/6643 that I think will fix the issue. For MySQL we're attaching the parameter as an ISO formatted date/timestamp string and using MySQL's `convert_tz` function to put the timestamp in the correct timezone, which avoids the code that has the conversion bug.

@Overbryd The fix is currently in master and will be included in our next release (probably 0.28.0 RC1). Could you verify that the issue is fixed for you?

**Comment by Overbryd** [comment] 2018-03-20 09:12
Ok, I am picking this up now, and will let you know where we stand.
We are now running on 0.28 can therefore do another test.

Thank you for digging into it, highly appreciated.

Ryan Senior <notifications@github.com> schrieb am Fr. 5. Jan. 2018 um 23:34:

**Comment by senior** [comment] 2018-05-11 15:49
@Overbryd I don't think this problem will be fixed for you. The fix I mentioned applied to queries built via the query builder, but not a native query like you have in your original issue description. I should have been able to reproduce this issue in a unit test though and will be working on a fix soon. That work will happen in https://github.com/metabase/metabase/pull/7520

**Closed** 2018-05-22 02:53 UTC
Labels: Bug, Priority/P1, Timezones/Calendars
