### ISSUE TITLE
Question Title Loads before Custom Title on Dashboard Card

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#41843] opened 2024-04-25 18:46 UTC
### Describe the bug

If you set a custom name for a dashboard card on the dashboard, when you first load (or reload) the dashboard the Question title will display before the dashboard custom title takes it's place

### To Reproduce

1. Create a dashboard
2. Toss a few dashboard cards on it
3. On one of the card go into 'Visualization Options" and change the title on the card
4. Save
5. Refresh and watch the card title

### Expected behavior

When you load a Dashboard that has a custom title on the dashboard card only show the custom title.

### Information about your Metabase installation

```JSON
https://www.loom.com/share/572275acd8dd45dca25831adbda1c79b
```

### Severity

annoying

### Additional context

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.15.133.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2",
      "bigquery-cloud-sdk",
      "mysql",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.22 (Debian 11.22-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-04-11",
      "tag": "v1.49.5",
      "hash": "31c4887"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by paoliniluis** [comment] 2024-04-25 18:48
This has always been like that since we first load what comes from the BE and then we write the titles on the FE. It's a simple change in the FE but it might introduce lag

**Comment by ojjj13** [comment] 2024-04-26 00:53
A suggestion would be load the card first, then redering the title as needed.

**Comment by alxnddr** [comment] 2024-12-20 19:51
Duplicate of https://github.com/metabase/metabase/issues/50044

**Closed** 2024-12-20 20:25 UTC
Labels: Type:Bug, Priority:P3, Reporting/Dashboards, .Frontend, .Team/DashViz
