### ISSUE TITLE
"Type" dropdown in Data Model settings jumps to top jarringly 

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#16200] opened 2021-05-23 22:02 UTC
**Describe the bug**
When setting the type of a column, if you scroll down to the bottom of the dropdown and then scroll up a tiny bit, it jumps back to the top of the dropdown.

**To Reproduce**
1. Go to Admin -> Data Model
2. Select a DB and table
3. Click on a dropdown under the "Type" column
4. Scroll to the bottom of the options
5. Scroll up slight
6. Observe the UI jump back up to the top of the options

**Screenshots**

https://user-images.githubusercontent.com/32746338/119278037-bdb43a00-bbd7-11eb-8926-364faade48ad.mov

**Information about your Metabase Installation:**
 v0.39.1 on Firefox 88.0.1

**Comment by flamber** [comment] 2021-05-24 09:31
Duplicate of #13805

**Closed by flamber** 2021-05-24 09:31 UTC
Labels: .Needs Triage, Type:Bug
