### ISSUE TITLE
Filter by date on dashboard - bug

### ISSUE THREAD

**Issue by Crusader4Christ** [metabase/metabase#12245] opened 2020-04-02 09:05 UTC
**Describe the bug**
Added 'question from question' on the dashboard with filter by date field does not work

**Logs**
```
[372310be-a897-44ff-af6e-df5fc4de5b93] 2020-04-02T11:07:49+03:00 WARN metabase.query-processor.middleware.process-userland-query Query failure {:status :failed,
:class clojure.lang.ExceptionInfo,
:error (not (integer? "deposited_date")),
:stacktrace
("--> models.params$fn__29604$field_form__GT_id__29609.invoke(params.clj:21)"
"query_processor.middleware.parameters.mbql$fn__42649$build_filter_clause__42654$fn__42664.invoke(mbql.clj:50)"
"query_processor.middleware.parameters.mbql$fn__42649$build_filter_clause__42654.invoke(mbql.clj:39)"
"query_processor.middleware.parameters.mbql$expand.invokeStatic(mbql.clj:78)"
"query_processor.middleware.parameters.mbql$expand.invoke(mbql.clj:65)"
"query_processor.middleware.parameters$expand_mbql_params.invokeStatic(parameters.clj:37)"
"query_processor.middleware.parameters$expand_mbql_params.invoke(parameters.clj:33)"
"query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:49)"
"query_processor.middleware.parameters$expand_one.invoke(parameters.clj:41)"
"query_processor.middleware.parameters$expand_all$replace_42749__42750.invoke(parameters.clj:59)"
"mbql.util.match$replace_in_collection$iter__24076__24080$fn__24081.invoke(match.clj:132)"
"mbql.util.match$replace_in_collection.invokeStatic(match.clj:131)"
"mbql.util.match$replace_in_collection.invoke(match.clj:126)"
"query_processor.middleware.parameters$expand_all$replace_42749__42750.invoke(parameters.clj:59)"
"query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:59)"
"query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)"
"query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:56)"
"query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)"
"query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:77)"
"query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:73)"
"query_processor.middleware.parameters$fn__42765$substitute_parameters_STAR___42770$fn__42771.invoke(parameters.clj:82)"
"query_processor.middleware.parameters$fn__42765$substitute_parameters_STAR___42770.invoke(parameters.clj:79)"
"query_processor.middleware.driver_specific$process_query_in_context$fn__41578.invoke(driver_specific.clj:12)"
"query_processor.middleware.resolve_driver$resolve_driver$fn__43094.invoke(resolve_driver.clj:22)"
"query_processor.middleware.store$initialize_store$fn__46220$fn__46221.invoke(store.clj:11)"
"query_processor.store$do_with_store.invokeStatic(store.clj:46)"
"query_processor.store$do_with_store.invoke(store.clj:40)"
"query_processor.middleware.store$initialize_store$fn__46220.invoke(store.clj:10)"
"query_processor.middleware.async$async__GT_sync$fn__37366.invoke(async.clj:23)"
"query_processor.middleware.async_wait$runnable$fn__40619.invoke(async_wait.clj:89)"),
:query
{:constraints {:max-results 10000, :max-results-bare-rows 2000},
:type :query,
:middleware {:userland-query? true},
:info
{:executed-by 9,
:context :question,
:card-id 176,
:dashboard-id nil,
:query-hash [88, -45, 4, 13, -75, 127, -92, 117, -25, 105, -38, -75, 65, 96, -91, 43, -4, 100, 16, -106, 127, -26, 63, -44, -31, -53, -41, -9, 66, -88, -4, 34]},
:query {:source-table "card__181", :aggregation [[:count]], :breakout [[:field-literal "Affiliate" :type/Text]], :order-by [[:desc [:aggregation 0]]]},
:parameters [{:type "date/all-options", :target ["dimension" ["field-literal" "deposited_date" "type/Date"]], :value "thisday"}],
:async? true,
:cache-ttl 10},
:preprocessed nil,
:native nil,
:ex-data {:type :schema.core/error, :value "deposited_date", :error (not (integer? "deposited_date"))}}
```

**To Reproduce**
1. Create a sql question 'SELECT date(timestampColumn) as column_date FROM table'
2. Create new chart from this question (choose saved question as source)
3. Add it to dashboard.
4. Add date filter by the date field

**Information about your Metabase Installation:**
- Your databases: MySQL 5.7
- Metabase version: v0.34.3
- Metabase hosting environment: Docker
- Metabase internal database: PostgreSQL v9.6.17

**Severity**
blocking some users

**Additional context**
When loading the dashboard with this question get error in console:
Request URL: https://metabase--3000.megasource.io/api/field/field-literal%2Ccolumn_date%2Ctype%2FDate
response "API endpoint does not exist."

**Comment by flamber** [comment] 2020-04-02 10:15
Hi @Crusader4Christ 
It's still not possible to link filters to a Saved Question, but there's now (since 0.34.x) a visual bug, which allows you to link a filter if you went directly from a question to adding it to a dashboard. If you go to a dashboard and try to add the question, then you're not allowed to link the filter.
Closing a duplicate of #9802.

**Closed by flamber** 2020-04-02 10:15 UTC
Labels: .Needs Triage, Type:Bug
