### ISSUE TITLE
CSV download limited to 10,000 rows

### ISSUE THREAD

**Issue by raphal** [metabase/metabase#3967] opened 2016-12-16 06:26 UTC
Using the download as CSV feature in a card returns files of up to 10,000 rows, regardless of the LIMIT statement. I would expect this to return the full data set (or perhaps max 1048576 records to match Excel's limit).

Test case:
- run this SQL to create a table raph_test:  [demo.sql.zip](https://github.com/metabase/metabase/files/656520/demo.sql.zip)
- create a new question and use SQL editor to enter the query `SELECT mb_no FROM raph_test`
- the display in the web interface is limited to 10,000 rows (that's fine)
- download the CSV file: the file contains 10,002 lines, with 10,000 rows of data (I believe that's NOT okay, should be 10,578 rows, i.e. the whole table)

![image](https://cloud.githubusercontent.com/assets/8253399/21253645/9089d854-c3a3-11e6-8456-c33446de292a.png)

Downloaded file with the problem:
[query_result_2016-12-16T06-22-42.994Z.csv.zip](https://github.com/metabase/metabase/files/656507/query_result_2016-12-16T06-22-42.994Z.csv.zip)

I am using:
- Browser: Chrome 54.0.2840.98 (64-bit) on Mac OS X 10.12.1
- Database: MariaDB 10.0.17 (an AWS RDS instance)
- Metabase version: 0.21.1 hosted as Elastic Beanstalk application
- Metabase internal DB: PostgreSQL 9.5.4 (also an AWS RDS instance)

Please note this issue did NOT occur in Metabase 0.20.0 with otherwise the same setup (10578 rows of data):
[query_result_2016-12-16T06-25-14.782Z.csv.zip](https://github.com/metabase/metabase/files/656510/query_result_2016-12-16T06-25-14.782Z.csv.zip)

**Comment by aagarwal-gtr** [comment] 2016-12-16 09:41
@raphal this is a dupe of #3936 which is a dupe of #3810

**Closed** 2016-12-16 17:57 UTC
Labels: Duplicate
