### ISSUE TITLE
Druid HyperUnique queries broken between versions v0.30.4 and v0.33.3

### ISSUE THREAD

**Issue by thelgis** [metabase/metabase#10984] opened 2019-09-25 09:21 UTC
Druid HyperUnique queries seem to be generated incorrectly by Metabase on version v0.33.3. This functionality was working correctly in v0.30.4. 

The issue seems to be that the generated Druid query when using a HyperUnique column used to be generated with **type=hyperUnique**, whereas in the latest version it gets generated with **type=cardinality**. 

This is clear in the attached screenshots where the same exact query has been run on the same data source but on different versions of Metabase. You'll notice that the generated native Druid queries are different. 

The expected behavior is the one that existed in v0.30.4 where such queries had hyperUnique type. This issue is blocking users to use Metabase for metrics with HyperUnique columns on Druid. 

![v0 30 4](https://user-images.githubusercontent.com/4777478/65587722-fc22cd00-df8e-11e9-8182-b1b812656360.png)
![v0 33 3](https://user-images.githubusercontent.com/4777478/65587725-fe852700-df8e-11e9-9189-5d71a0004cb9.png)

**Comment by arruzk** [comment] 2019-09-30 11:46
@sbelak Hi, is it a duplicate of https://github.com/metabase/metabase/issues/10221 ?

**Comment by sbelak** [comment] 2019-09-30 17:38
It is. Closing in favour of that, thanks.

**Closed by sbelak** 2019-09-30 17:38 UTC
Labels: Database/Druid, Type:Bug
