### ISSUE TITLE
Model metadata not overriding question column settings

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20624] opened 2022-02-18 12:13 UTC
**Describe the bug**
Model metadata not overriding question column settings. Unsure if this might have wider effects.

**To Reproduce**
1. Native > Sample > `select * from PRODUCTS limit 2`
2. Rename TITLE to something different
![image](https://user-images.githubusercontent.com/1447303/154679981-f6d2939b-636d-48ea-9d26-2d099d1d0054.png)
3. Save question and convert to Model (notice the column title is still showing)
![image](https://user-images.githubusercontent.com/1447303/154680122-208ffbe2-99a4-41c5-9858-a4e307de5de9.png)
4. Change metadata for TITLE, which says Display name is the actual underlying column name instead of the step 2.
![image](https://user-images.githubusercontent.com/1447303/154680364-c32bb2c0-ffe0-4b93-b6c0-f7bd9d99f2b4.png)
![image](https://user-images.githubusercontent.com/1447303/154680459-82ac0fec-fb55-4aeb-a393-4b4ffeb37e3b.png)
5. The metadata change does not take effect
![image](https://user-images.githubusercontent.com/1447303/154680564-c09bb2e5-8e2f-435d-b251-be3325b0e0f7.png)

**Expected behavior**
Model metadata should overrule column titles defined on source question.

**Information about your Metabase Installation:**
Tested 0.42.1 thru 0.44.6

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by WiNloSt** [comment] 2022-03-17 11:19
@flamber  I think I already solved half of the problem. Given your example, from the repro @nemanjaglumac created, it expects to see `TITLE - RENAMED` in the metadata editor, not `TITLE`.
https://github.com/metabase/metabase/blob/b8635fafc096346a4787102aebcd042e25affff0/frontend/test/metabase/scenarios/models/reproductions/20624-model-metadata-should-override-column-settings.cy.spec.js#L30

So, the repro steps in this issue aren't exactly what we have in the Cypress test.

I just want to confirm if both the table view and the metadata editor view should show the same column name (like the repro @nemanjaglumac created). Currently;
- On the table view it shows `TITLE - RENAMED`
- On the metadata editor view it shows `TITLE`

#### Table view
![image](https://user-images.githubusercontent.com/1937582/158798158-7b210b93-5c13-4be4-a488-2c8133d62008.png)

#### Metadata editor view
![image](https://user-images.githubusercontent.com/1937582/158798210-c4457ed7-ff64-44bb-8ea4-219c9d4b51b2.png)

**Comment by WiNloSt** [comment] 2022-03-17 12:13
I tried making both metadata editor and table view show the same column name, but I still find it weird that the metadata view will display the value from `metadata` while the column name displays a different name (the same name as the table view)

![image](https://user-images.githubusercontent.com/1937582/158805863-f70c668c-c783-4921-8feb-ce072c23b09f.png)

I think it might be fine to let the metadata view show the column name from the metadata itself (`TITLE` not `TITLE - RENAMED`) in this case. Otherwise, it will still look confusing anyway and the change looks hacky already in my opinion.

**Comment by WiNloSt** [comment] 2022-03-18 07:46
@flamber I'm not sure if this is even viable.
https://www.loom.com/share/98f6d9e32ad1419aae867a5b45880436

[My assumption](https://github.com/metabase/metabase/pull/21054#discussion_r829057969) (check if `name` and `display_name` are different) breaks lots of tests.

**Comment by flamber** [comment] 2022-03-18 08:44
Perhaps we need to drop or convert the visualization settings to metadata, when converting from question to Model.
Guess this might involve backend. Sounds like it's not an easy issue to fix.

**Comment by snarfed** [comment] 2022-05-07 18:50
I came here from https://discourse.metabase.com/t/metadata-is-reset-when-editing-a-model-sql-query/18845, which I'm not sure is the same bug, but I trust you all!

I edited a model's query just now, added a custom column, saved the query, and discovered that all the metadata I'd customized was gone. All columns reverted to their original names, types, and visibility settings. Definitely a disappointing surprise, since I'd spent some time on that metadata.

Is this the right issue to follow? Thanks in advance!

**Comment by flamber** [comment] 2022-05-08 09:34
@snarfed I've created a separate issue for metadata being dropped when changing the columns on a Model #22517

**Comment by dpsutton** [comment] 2023-02-02 17:07
I'm not entirely sure this is a bug. This boils down to the fact that we have two different ways to indicate what a column's name should be: from the display name of the column, or the viz settings of the question. We have the following scenario:

```clojure
{:result_metadata        ({:display_name "model-renamed-title",
                           :name         "TITLE"})
 :name                   "model rename",
 :visualization_settings {:column_settings {"[\"name\",\"TITLE\"]"
                                            {:column_title "renamed-title"}}}}
```
There are two renames vying for the same column. I think the current behavior is intentional and correct.

For a question, setting a column's display name in the viz settings should override the display name for a column. The viz setting is an intentional and deliberate overriding of "system settings" in that sense. This display name is only in effect for the individual question. Any questions that query from the saved question (or model) would see the metadata display_name property.

So I think the only work to be done here is to perhaps remove a bit of the surprise. I think what we could do is when a question becomes a model, we can strip any viz settings column renames and add them to the metadata display_name.

It might be worth preventing using viz settings on models from renaming columns because it can be a bit confusing, but fundamentally there's nothing wrong with it. It's a way to add custom names to columns when viewing this particular question. And thus the state you get into with both metadata display_name and viz_settings column_title is not really illegal or wrong.

**Comment by WiNloSt** [comment] 2023-02-02 18:32
I don't have a ton of context to give much useful opinion, but your comment makes sense to me. They sound all reasonable, but I like 2 or 3 the most, just stop using viz settings altogether in models since we can edit some of that in metadata instead. Also, models are made to feel like a data source, so 1 sounds a bit counterintuitive.

I think when editing any visualization settings and we're forced to create a new question, that should be the behavior that we keep.

**Comment by dpsutton** [comment] 2023-02-06 15:54
Ok I think I've got a way forward for this. 
To recap, we have two different customizations fighting for the display name of the column:
- viz settings (which wins). Says to call the column X when viewing this question. Note this does not flow through queries based on the model
- metadata. Editing the display_name is the intended behavior. But its results are never really seen because of the local modification to viz settings. However, other questions based on the model will use this display_name

We now have a way forward to do Clojure-land migrations run from liquibase. This would be an ideal case. The solution is to grab all models which have a viz setting column rename. For each of these, for each non-blank viz setting column name, find it's matching column in the result_metadata. If the display name of the column is equal to `(humanization/name->human-readable-name name)` (ie, it's the default name and not changed by a human), replace the display_name in the metadata with the viz setting name. Update the model with the new metadata and the viz settings with the column renames removed.

### Explanation of parts:

#### How to match columns to viz settings
Check out `metabase.pulse.render.body/column-name`. This gets the column name for displaying in static viz. This must check display_name in the metadata as well as the viz setting.

#### How to find models matching this scenario:
a rough first approximation is 

```clojure
  (db/select 'Card
             :dataset true
             :visualization_settings [:like "%column_title%"])
```
Viz settings are text and we can look for column_title in the json string.

The relevant parts of the card are the following

```clojure
  [{:id 777,
    :visualization_settings {:table.pivot_column "ID",
                             :table.cell_column "TITLE",
                             :column_settings {"[\"name\",\"TITLE\"]" {:column_title "viz settings title rename"}}}, ;; viz setting rename
    :result_metadata ({:name "ID",
                       :display_name "ID",
                       :field_ref [:field
                                   "ID"
                                   {:base-type :type/BigInteger}]}
                      {:name "TITLE",
                       :display_name "model metadata rename", ;; human edited metadata column rename
                       :field_ref [:field
                                   "TITLE"
                                   {:base-type :type/Text}]})}
   {:id 774,
    :visualization_settings {:table.pivot_column "ID",
                             :table.cell_column "PRICE",
                             :column_settings {"[\"name\",\"TITLE\"]" {:column_title "renamed-title"}}}, ;; viz setting rename
    :result_metadata [{:name "TITLE",
                       :display_name "model-renamed-title", ;; human edited metadata column rename
                       :field_ref [:field
                                   "TITLE"
                                   {:base-type :type/Text}]}]}]
;; note (humanization/name->human-readable-name "TITLE") = "Title" so we know these are human edited
```

#### How to create a clojureland migration

Liquibase allows for `customChange` as the change type. It's single property is `class`, a fully qualified class name that will do the migration

```yaml
  - changeSet:
      id: v46.00-080
      author: dpsutton
      comment: custom change class
      customChange:
        class: "metabase.db.custom_migrations.ModelsVizSettingsRemoveNames"
```

And a namespace `custom-migrations` that creates a class of the appropriate name:

```clojure
(ns metabase.db.custom-migrations
  (:require [clojure.tools.logging :as log]
            [metabase.models.humanization :as humanization]
            [toucan.db :as db])
  (:import [liquibase.change.custom CustomTaskChange CustomTaskRollback]
           liquibase.exception.ValidationErrors))

(defrecord ModelsVizSettingsRemoveNames []
  CustomTaskChange
  (execute [_ _database]
;; example migration making all dashboards have uppercase names
    (log/warn "Setting dashboard titles to uppercase")
    (db/execute! {:update :report_dashboard
                  :set    {:name :%upper.name}})
    (log/warn "Dashboard titles set to uppercase successfully"))
  (getConfirmationMessage [_]
    "said hello")  ;; investigate
  (setUp [_])
  (validate [_ _database]
    (ValidationErrors.))
  (setFileOpener [_ _resourceAccessor])

  CustomTaskRollback
  (rollback [_ _database]
    (println "Goodbye")))  ;; investigate
```

And at startup:

```
2023-02-03 16:29:06,422 INFO db.liquibase :: Checking if Database has unrun migrations...
2023-02-03 16:29:08,187 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
2023-02-03 16:29:08,345 INFO db.liquibase :: Migration lock is cleared. Running migrations...
2023-02-03 16:29:08,581 WARN db.custom-migrations :: Setting dashboard titles to uppercase
2023-02-03 16:29:08,664 WARN db.custom-migrations :: Dashboard titles set to uppercase successfully
2023-02-03 16:29:08,753 INFO db.setup :: Database Migrations Current ...  ✅
```

Since this will be our first Clojure-land migration interleaved into the regular liquibase migrations, we want to make sure things work correctly.

Particularly, we need to know what liquibase does with transactions and errors. Test this out and have your migration throw an error. Does it continue, etc. I expect things to be pretty sane here but we have to make sure.

**Comment by markbastian** [comment] 2023-02-06 19:10
To summarize the course of action and resultant behavior:

- For **existing** models, we have 4 situations (all with respect to column name conflicts) we will handle via migration:
  - There are no metadata or viz settings overrides. We do nothing.
  - There are only metadata overrides (no viz settings). We do nothing.
  - There are viz settings but no metadata. We promote `visualization_settings.column_title` to `results_metadata.display_name` and remove the visualization_settings.
    - Reverting from a model to question will drop the column name override.
  - Both `visualization_settings.column_title` and `results_metadata.display_name` exist.
    - Currently we show the `visualization_settings.column_title` in the model's table view, this is a bug.
    - In the migration, we retain `results_metadata.display_name` and drop `visualization_settings.column_title`.
    - Reverting from a model to question will drop the column name override.
- For **new** models, we will perform the same action as above as if there were no metadata settings.
  - Promote `visualization_settings.column_title` (if any) to `results_metadata.display_name` and remove the visualization_settings.
  - Reverting from a model to question will drop the column name override.

**Comment by dpsutton** [comment] 2023-02-06 20:04
@WiNloSt as an alternative to a migration, is it possible for the frontend to ignore viz settings column names on models?

**Comment by markbastian** [comment] 2023-02-06 20:14
For reference, here is a [convo](https://metaboat.slack.com/archives/C04DAKKDMFT/p1675710702443849) on this topic from slack as well as a screen capture of the behavior in question.

![rename](https://user-images.githubusercontent.com/8381441/217075395-977ea565-2907-47c4-a62a-9fbe766c0a37.gif)

**Comment by WiNloSt** [comment] 2023-02-22 14:26
@dpsutton sorry I missed your comment. I've made a small PR https://github.com/metabase/metabase/pull/28530 which implements your suggestion. It passes the reproduced test locally.

**Comment by camsaul** [comment] 2023-03-06 17:18
This should probably be something that gets fixed by Metabase lib v2

**Comment by WiNloSt** [comment] 2023-11-08 11:05
Reproducible on 1.42 and master (e0ebd085cc168d75692c4ec584bb71994011dc83)

![image](https://github.com/metabase/metabase/assets/1937582/4c3db638-de9b-4eb8-bd1f-5404ed36555e)
![image](https://github.com/metabase/metabase/assets/1937582/7ceb3dc6-a071-4cbc-bf0a-1b64e008a02a)

**Comment by kamilmielnik** [comment] 2024-04-04 13:19
Reproducible on `master` at c059d8d585.

**Comment by metamben** [comment] 2024-07-08 21:14
@camsaul said

> This should probably be something that gets fixed by Metabase lib v2

and he meant that this is issue is best addressed when viz-settings support (at least for columns) in MLv2 gets implemented.

**Comment by ranquild** [comment] 2024-07-15 01:34
This has nothing to do with MBQL lib or model metadata. What happens is the following:
- There is a question with viz settings (`column_settings)` with custom `column_title`
- This question gets converted to a model -> the viz settings are preserved
- There are some metadata edits that overwrite `display_name` in `result_metadata`
- All ad-hoc questions created from the model inherit viz settings with custom `column_title`, which override any query metadata

What we can do:
1. Reset all viz settings when turning a question to a model
2. Reset only `column_settings`, e.g. column formatting settings but not column order (`table.columns`)
3. Reset only `column_title` in `column_settings`

**Comment by metamben** [comment] 2024-07-15 15:01
I was assuming we planned to do 4 (plus overwriting the `result_metadata` with the new `column_title` when converting back), but it gets simpler if there is no conversion between cards and models.

**Closed** 2024-10-21 18:39 UTC
Labels: Type:Bug, Priority:P2, Difficulty:Medium, .Frontend, .Reproduced, .Regression, Querying/Models, .Team/Querying, Frequency:Rare
