### ISSUE TITLE
Extra day and alignment is off on bar chart with multiple series

### ISSUE THREAD

**Issue by alvaroc1** [metabase/metabase#6857] opened 2018-02-03 17:35 UTC
This is a report showing 7 days from Jan 4 to Jan 10. The bars look correct, but the labels are showing an extra day at the beggining: Jan 3 which is not included in the data. 

<img width="1033" alt="screenshot 2018-02-03 10 25 13" src="https://user-images.githubusercontent.com/107395/35769727-addbaecc-08cc-11e8-8185-4ad76d5ba4af.png">

When rendering the same question as a table, you can see that Jan 3 is not part of the data:
<img width="770" alt="screenshot 2018-02-03 10 34 10" src="https://user-images.githubusercontent.com/107395/35769796-d6335388-08cd-11e8-9b6d-5649c3174b66.png">

- Your browser and the version: Chrome 63
- Your operating system: OSX
- Your databases: Redshift
- Metabase version: v0.28.0.RC1
- Metabase hosting environment: EC2 with jarfile
- Metabase internal database: Mysql

**Comment by alvaroc1** [comment] 2018-03-21 17:55
Easy reproduction:
<img width="640" alt="screenshot 2018-03-21 11 54 03" src="https://user-images.githubusercontent.com/107395/37727969-abd723c6-2cfe-11e8-866d-aeb2b1d3ec06.png">

**Comment by alvaroc1** [comment] 2018-03-21 19:00
Upgrading dc-js to v2.1.10 and explicitly casting the strings to dates somewhat improves the situation:
<img width="688" alt="screenshot 2018-03-21 12 55 01" src="https://user-images.githubusercontent.com/107395/37731273-41dd8538-2d07-11e8-8eba-d88b30648a5b.png">

Now the labels align, but only because it's adding an extra not only at the start but also at the end. 
Without the explicit casts, the code seems to do the same thing it was doing before. With no casts, the code clearly is figuring out that my strings are really dates, but for some reason it's arriving at a slightly different results (timezone issue?) than with the explicit casts.

**Comment by alvaroc1** [comment] 2018-04-16 15:21
Workaround: Format into a string within SQL. This can break client-side sorting on the Table visualization.

**Comment by flamber** [comment] 2020-04-22 21:06
This was fixed in 0.32.9 I think. I cannot reproduce on 0.35.3:
![image](https://user-images.githubusercontent.com/1447303/80033932-d5f5e900-84ed-11ea-89ab-5a6c1a882ec2.png)

**Closed by flamber** 2020-04-22 21:06 UTC
Labels: Priority:P3, Type:Bug, Visualization/
