### ISSUE TITLE
BIGINT UNSIGNED value

### ISSUE THREAD

**Issue by ajatau** [metabase/metabase#30382] opened 2023-04-26 09:52 UTC
### Describe the bug

Had a question which always worked but after the recent update I keep getting an error 
```
BIGINT UNSIGNED value is out of range in 
```
when trying to perform summations and subtractions on columns

### To Reproduce

1. Go to use MySQL 5.6
2. try an operation like 

```
(`amount`- (`interest` + `vat_charge`))

``` 
3. See error 
BIGINT UNSIGNED value is out of range in 
<img width="568" alt="Screenshot 2023-04-26 at 10 50 33" src="https://user-images.githubusercontent.com/9402003/234539208-ffe3e43e-a811-4fa7-a3d2-d8b8bf04bb01.png">

### Expected behavior

It should perform operation as expected

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "4.14.309-231.529.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.28"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-04-05",
      "tag": "v0.46.1",
      "branch": "release-x.46.x",
      "hash": "12a6e1d"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

### Severity

very severe!

**Comment by mweisshaupt1988** [comment] 2023-04-26 15:16
I had a similar problem with calling functions in PostgreSQL. I have some functions which accept integers as parameters which are inserted on dashboards.

Example function:
`CREATE OR REPLACE FUNCTION report.myfunction(myparameter INTEGER)`

This has worked until recently:
`SELECT * FROM myschema.myfunction({{parameter}})`

But now this no longer works because now instead of an integer it will pass a bigint to the function. This fixed it for me:
`SELECT * FROM myschema.myfunction({{parameter}}::int)`

In your case you need to cast it howewer that is done in mysql.

**Comment by paoliniluis** [comment] 2023-04-26 23:46
@ajatau can you post reproduction steps with the sample dataset?

**Comment by paoliniluis** [comment] 2023-07-07 02:24
Closing, this is a version of MySQL we don't support

**Closed by paoliniluis** 2023-07-07 02:24 UTC
Labels: Type:Bug, .Needs Triage
