### ISSUE TITLE
Public dashboard fails with "An error occurred"

### ISSUE THREAD

**Issue by drorm** [metabase/metabase#4644] opened 2017-03-30 06:26 UTC
- Your browser and the version:Chrome and Firefox
- Your operating system: Ubuntu 16.04
- Your databases: H2
- Metabase version: v0.23.0
- Metabase hosting environment: Docker on LInux
- Metabase internal database: H2

- *Repeatable steps to reproduce the issue*
Go to: https://mb.wrdr.io/public/dashboard/2a175069-5177-4df2-a7ce-287fb29ac4d9
You'll get "not found" or "An error occurred" rather than a dashboard though sometimes it does work.

Logs show:
metabase.middleware :: GET /api/user/current 401 (93 µs) (0 DB calls)
"Unauthenticated"

So there's some dangling authentication that probably shouldn't happen. I suspect that it's related to the queries taking a while. If I leave just a single card it seems  to work fine.

**Comment by salsakran** [comment] 2017-04-03 17:40
I'm not seeing the error from my end. Tried Chrome + Safari on OS X.

**Comment by salsakran** [comment] 2017-04-03 17:40
was there any pattern to when you got the error and when the dashboard rendered?

**Comment by drorm** [comment] 2017-04-03 22:33
This is strange. It fails on Chrome but not on Firefox anymore for me, but works in Virtualbox and for other people.  It also works if I have the console open in Chrome. It's on plugin issue because it fails in incognito mode. The attached file shows how it's failing. Feel free to close this ticket since you can't reproduce it.

[err.zip](https://github.com/metabase/metabase/files/891615/err.zip)

**Comment by camsaul** [comment] 2017-04-11 18:54
@drorm I'm able to load that dashboard from that link you posted just fine

are you still seeing the issue?

**Comment by drorm** [comment] 2017-04-12 04:22
I'm still seeing it on Chrome but not Firefox on Linux. Works fine on Windows, and OSX. On Chrome it works if the console is open. My inclination is to close this for now and try again on 0.24.

**Comment by tlrobinson** [comment] 2017-04-12 22:51
@drorm Does the error occur exactly 15 seconds after the dashboard starts loading? If so this is a duplicate of #4557

If not I'll reopen it.

**Closed by tlrobinson** 2017-04-12 22:51 UTC
Labels: Bug, Embedding, Unable to Reproduce

**Comment by drorm** [comment] 2017-04-17 01:25
No, it does not happen after 15 seconds.

Also, when I open the console, after it fails, I see:

> Refused to load the script 'data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJLy8gaHR0cHM6Ly9kZXZl…07Cgl9OwoJZ2EucmVtb3ZlID0gbm9vcGZuOwoJd2luZG93W2dhTmFtZV0gPSBnYTsKfSkoKTs=' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline' 'unsafe-eval' 'self' https://maps.google.com https://apis.google.com https://www.google-analytics.com https://*.googleapis.com *.gstatic.com js.intercomcdn.com *.intercom.io ".

> textareas.js:30 findTextAreas: running over 1
> textareas.js:30 findTextAreas: running over 1
> /api/user/current Failed to load resource: the server responded with a status of 401 (Unauthorized)

Let's keep this closed for now. I'll see if 0.24 fixes this issue.

**Comment by ysim** [comment] 2017-07-03 18:51
I'm getting this same error, along with another one on Firefox, for a map visualization:

> Content Security Policy: The page’s settings blocked the loading of a resource at data:application/javascript;base64,KGZ1b... (“script-src 'unsafe-inline' 'unsafe-eval' https://our-metabase-instance.com https://maps.google.com https://apis.google.com https://www.google-analytics.com https://*.googleapis.com https://*.gstatic.com https://js.intercomcdn.com https://*.intercom.io”).
> The resource from “https://our-metabase-instance.com/card/snippets/text.js” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).

I'm running v0.23.1 on AWS EC2 Container Service/RDS.

**Comment by thucnc** [comment] 2017-10-09 10:14
I got the same error on V0.26.0

**Comment by jordantaylorjolly** [comment] 2021-04-29 21:53
I had this issue (using Chrome on a Pixelbook...) - somehow it got into a weird state where I was being seen as unauthenticated.

The only thing that fixed this was restarting my Chromebook!
