### ISSUE TITLE
Not all values listed in filters - cannot select value not listed.

### ISSUE THREAD

**Issue by funktopus** [metabase/metabase#5128] opened 2017-05-17 07:36 UTC
When I am using a filter (in questions or dashboards), there is a new drop down menu with all the values. However not all of them are listed (it ends with letter G in my case) and I cannot select a value that I want, because they are not listed. This is a catch-22 style work blocker :-(

**Comment by salsakran** [comment] 2017-05-19 23:25
This is an issue with FieldValues not being properly picked up. 

Related to #4991 and #5046

**Comment by camsaul** [comment] 2017-08-03 23:09
Basically the same underlying issue as #5323. This was resolved by #5510.

**Comment by camsaul** [comment] 2017-08-30 19:44
Duplicate of #5323

**Closed by camsaul** 2017-08-30 19:44 UTC
Labels: Bug, Metadata/Sync, Priority/P1

**Comment by mazameli** [comment] 2017-09-27 19:06
Hey everyone. Just a heads up that [we've shipped version 0.26](http://www.metabase.com/blog/Metabase-0.26) which fixes this issue.
