### ISSUE TITLE
Comma Separate Numbers filter not working as it previously did

### ISSUE THREAD

**Issue by brianschillaci** [metabase/metabase#21160] opened 2022-03-22 17:37 UTC
**Describe the bug**

For a number filter that is a comma separated list of numbers, it throws an error that looks like:

ERROR: column "infinity" does not exist Position: 488

This only happens when the list of numbers is longer than 2 numbers in the comma separated list.

**To Reproduce**
1. Setup a query with a number filter, passing in a comma separated list of numbers (more than like 5 numbers)
2. Run the query
3. See the error column infinity doesn't exist

**Expected behavior**
I expected the comma separated list to be parsed properly and filter the data.

**Information about your Metabase Installation:**

We recently upgraded from 0.41.6 to 0.42.2

- Firefox 98.0.1 
- MacOS Big Sur
- Aurora Postgres
- Metabase version: 0.42.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
This is blocking filtering ability on several critical reports for us.

**Additional context**
It seems like instead of parsing the comma separated numbers properly, it is concatenating them all into 1 number. Which is why it 
returns an 'infinity' error.

**Comment by flamber** [comment] 2022-03-22 18:11
It's also causing incorrect results, when there's few values. Regression since 0.42.0

Reproduce:
1. Question > SQL > Sample - change variable type to Number
`select count(*) from orders where user_id in ({{number_comma}})`
2. Input `1,2,3` in the widget - run, result is 0, while 0.41.6 would return 21 (correct):
![image](https://user-images.githubusercontent.com/1447303/159546241-96f0aa95-31d1-4dfb-926a-fac609f90496.png)
3. Input `123,456,789,321` in the widget - run, query fails `Numeric value out of range: "123456789321" in column`, while 0.41.6 would return 18 (correct):
<details><summary>Full stacktrace</summary>

```
2022-03-22 19:06:57,753 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 4,
 :started_at #t "2022-03-22T19:06:56.958071+01:00[Europe/Copenhagen]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error executing query: Numeric value out of range: \"123456789321\" in column ; SQL statement:\n-- Metabase:: userID: 1 queryType: native queryHash: dbcd794a617c71fe70c0152090faeda3912795cf999ca61d74194b15264989d9\nselect count(*) from orders where user_id in (123456789321) [22004-197]",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__53274.invoke(execute.clj:504)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:501)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:487)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:496)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:487)"
    "driver.sql_jdbc$fn__81915.invokeStatic(sql_jdbc.clj:54)"
    "driver.sql_jdbc$fn__81915.invoke(sql_jdbc.clj:52)"
    "driver.h2$fn__79065.invokeStatic(h2.clj:90)"
    "driver.h2$fn__79065.invoke(h2.clj:87)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49659.invoke(mbql_to_native.clj:25)"
    "query_processor.middleware.check_features$check_features$fn__50405.invoke(check_features.clj:42)"
    "query_processor.middleware.limit$limit$fn__48032.invoke(limit.clj:37)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__50788.invoke(cache.clj:204)"
    "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__51821.invoke(optimize_temporal_filters.clj:204)"
    "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__51865.invoke(validate_temporal_bucketing.clj:50)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__49716.invoke(auto_parse_filter_values.clj:43)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__39821.invoke(wrap_value_literals.clj:161)"
    "query_processor.middleware.annotate$add_column_info$fn__44587.invoke(annotate.clj:659)"
    "query_processor.middleware.permissions$check_query_permissions$fn__46329.invoke(permissions.clj:108)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__51010.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46725.invoke(cumulative_aggregations.clj:60)"
    "query_processor.middleware.visualization_settings$update_viz_settings$fn__46663.invoke(visualization_settings.clj:63)"
    "query_processor.middleware.fix_bad_references$fix_bad_references_middleware$fn__50975.invoke(fix_bad_references.clj:91)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47610.invoke(resolve_joined_fields.clj:111)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__51591.invoke(resolve_joins.clj:176)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__51133.invoke(add_implicit_joins.clj:202)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__47629.invoke(large_int_id.clj:59)"
    "query_processor.middleware.format_rows$format_rows$fn__51185.invoke(format_rows.clj:74)"
    "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__46997.invoke(add_default_temporal_unit.clj:23)"
    "query_processor.middleware.desugar$desugar$fn__46636.invoke(desugar.clj:21)"
    "query_processor.middleware.binning$update_binning_strategy$fn__39550.invoke(binning.clj:229)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__45971.invoke(resolve_fields.clj:34)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__50342.invoke(add_dimension_projections.clj:487)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__50636.invoke(add_implicit_clauses.clj:164)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__48017.invoke(upgrade_field_literals.clj:117)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__47374.invoke(add_source_metadata.clj:125)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__50887.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__48974.invoke(auto_bucket_datetimes.clj:147)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45952.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__48628.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46025.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__52249.invoke(expand_macros.clj:184)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__48407.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__51200.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50647$fn__50652.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50647.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46571.invoke(fetch_source_query.clj:286)"
    "query_processor.middleware.store$initialize_store$fn__46762$fn__46763.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__46762.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__50982.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__50989.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__48353.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49645.invoke(results_metadata.clj:82)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__48371.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__50923.invoke(process_userland_query.clj:146)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51280.invoke(catch_exceptions.clj:169)"
    "query_processor.reducible$async_qp$qp_STAR___43323$thunk__43324.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___43323.invoke(reducible.clj:109)"
    "query_processor.reducible$sync_qp$qp_STAR___43332$fn__43335.invoke(reducible.clj:135)"
    "query_processor.reducible$sync_qp$qp_STAR___43332.invoke(reducible.clj:134)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:245)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:241)"
    "query_processor$fn__52297$process_query_and_save_execution_BANG___52306$fn__52309.invoke(query_processor.clj:256)"
    "query_processor$fn__52297$process_query_and_save_execution_BANG___52306.invoke(query_processor.clj:249)"
    "query_processor$fn__52341$process_query_and_save_with_max_results_constraints_BANG___52350$fn__52353.invoke(query_processor.clj:268)"
    "query_processor$fn__52341$process_query_and_save_with_max_results_constraints_BANG___52350.invoke(query_processor.clj:261)"
    "api.dataset$run_query_async$fn__65276.invoke(dataset.clj:69)"
    "query_processor.streaming$streaming_response_STAR_$fn__38459$fn__38460.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__38459.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__26889.invoke(streaming_response.clj:84)"],
   :error_type :invalid-query,
   :ex-data
   {:sql
    "-- Metabase:: userID: 1 queryType: native queryHash: dbcd794a617c71fe70c0152090faeda3912795cf999ca61d74194b15264989d9\nselect count(*) from orders where user_id in (123456789321)",
    :params [],
    :type :invalid-query}}],
 :state "22004",
 :error_type :invalid-query,
 :json_query
 {:type "native",
  :native
  {:template-tags
   {:number_comma
    {:id "2f06dcf1-5211-fac0-10e7-4aa722ed03cf",
     :name "number_comma",
     :display-name "Number comma",
     :type "number",
     :default nil}},
   :query "select count(*) from orders where user_id in ({{number_comma}})"},
  :database 4,
  :parameters
  [{:type "number/=",
    :value ["123,456,789,321"],
    :target ["variable" ["template-tag" "number_comma"]],
    :id "2f06dcf1-5211-fac0-10e7-4aa722ed03cf"}],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :status :failed,
 :class org.h2.jdbc.JdbcSQLException,
 :stacktrace
 ["org.h2.message.DbException.getJdbcSQLException(DbException.java:357)"
  "org.h2.message.DbException.get(DbException.java:179)"
  "org.h2.value.Value.convertToInt(Value.java:1214)"
  "org.h2.value.Value.convertTo(Value.java:723)"
  "org.h2.value.Value.convertTo(Value.java:617)"
  "org.h2.value.Value.convertTo(Value.java:592)"
  "org.h2.mvstore.db.MVSecondaryIndex.convertToKey(MVSecondaryIndex.java:326)"
  "org.h2.mvstore.db.MVSecondaryIndex.find(MVSecondaryIndex.java:262)"
  "org.h2.mvstore.db.MVSecondaryIndex.find(MVSecondaryIndex.java:258)"
  "org.h2.index.BaseIndex.find(BaseIndex.java:130)"
  "org.h2.index.IndexCursor.find(IndexCursor.java:176)"
  "org.h2.table.TableFilter.next(TableFilter.java:471)"
  "org.h2.command.dml.Select.queryGroup(Select.java:323)"
  "org.h2.command.dml.Select.queryWithoutCache(Select.java:628)"
  "org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:114)"
  "org.h2.command.dml.Query.query(Query.java:371)"
  "org.h2.command.dml.Query.query(Query.java:333)"
  "org.h2.command.CommandContainer.query(CommandContainer.java:114)"
  "org.h2.command.Command.executeQuery(Command.java:202)"
  "org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:227)"
  "org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)"
  "com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)"
  "--> driver.sql_jdbc.execute$fn__53194.invokeStatic(execute.clj:368)"
  "driver.sql_jdbc.execute$fn__53194.invoke(execute.clj:366)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:376)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:373)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__53274.invoke(execute.clj:502)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:501)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:487)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:496)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:487)"
  "driver.sql_jdbc$fn__81915.invokeStatic(sql_jdbc.clj:54)"
  "driver.sql_jdbc$fn__81915.invoke(sql_jdbc.clj:52)"
  "driver.h2$fn__79065.invokeStatic(h2.clj:90)"
  "driver.h2$fn__79065.invoke(h2.clj:87)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
  "query_processor.context.default$default_runf.invoke(default.clj:66)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49659.invoke(mbql_to_native.clj:25)"
  "query_processor.middleware.check_features$check_features$fn__50405.invoke(check_features.clj:42)"
  "query_processor.middleware.limit$limit$fn__48032.invoke(limit.clj:37)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__50788.invoke(cache.clj:204)"
  "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__51821.invoke(optimize_temporal_filters.clj:204)"
  "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__51865.invoke(validate_temporal_bucketing.clj:50)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__49716.invoke(auto_parse_filter_values.clj:43)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__39821.invoke(wrap_value_literals.clj:161)"
  "query_processor.middleware.annotate$add_column_info$fn__44587.invoke(annotate.clj:659)"
  "query_processor.middleware.permissions$check_query_permissions$fn__46329.invoke(permissions.clj:108)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__51010.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46725.invoke(cumulative_aggregations.clj:60)"
  "query_processor.middleware.visualization_settings$update_viz_settings$fn__46663.invoke(visualization_settings.clj:63)"
  "query_processor.middleware.fix_bad_references$fix_bad_references_middleware$fn__50975.invoke(fix_bad_references.clj:91)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47610.invoke(resolve_joined_fields.clj:111)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__51591.invoke(resolve_joins.clj:176)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__51133.invoke(add_implicit_joins.clj:202)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__47629.invoke(large_int_id.clj:59)"
  "query_processor.middleware.format_rows$format_rows$fn__51185.invoke(format_rows.clj:74)"
  "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__46997.invoke(add_default_temporal_unit.clj:23)"
  "query_processor.middleware.desugar$desugar$fn__46636.invoke(desugar.clj:21)"
  "query_processor.middleware.binning$update_binning_strategy$fn__39550.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__45971.invoke(resolve_fields.clj:34)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__50342.invoke(add_dimension_projections.clj:487)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__50636.invoke(add_implicit_clauses.clj:164)"
  "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__48017.invoke(upgrade_field_literals.clj:117)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__47374.invoke(add_source_metadata.clj:125)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__50887.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__48974.invoke(auto_bucket_datetimes.clj:147)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45952.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48628.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46025.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__52249.invoke(expand_macros.clj:184)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__48407.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__51200.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50647$fn__50652.invoke(resolve_database_and_driver.clj:35)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50647.invoke(resolve_database_and_driver.clj:34)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46571.invoke(fetch_source_query.clj:286)"
  "query_processor.middleware.store$initialize_store$fn__46762$fn__46763.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__46762.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__50982.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__50989.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__48353.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49645.invoke(results_metadata.clj:82)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__48371.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__50923.invoke(process_userland_query.clj:146)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51280.invoke(catch_exceptions.clj:169)"
  "query_processor.reducible$async_qp$qp_STAR___43323$thunk__43324.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___43323.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___43332$fn__43335.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___43332.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:245)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:241)"
  "query_processor$fn__52297$process_query_and_save_execution_BANG___52306$fn__52309.invoke(query_processor.clj:256)"
  "query_processor$fn__52297$process_query_and_save_execution_BANG___52306.invoke(query_processor.clj:249)"
  "query_processor$fn__52341$process_query_and_save_with_max_results_constraints_BANG___52350$fn__52353.invoke(query_processor.clj:268)"
  "query_processor$fn__52341$process_query_and_save_with_max_results_constraints_BANG___52350.invoke(query_processor.clj:261)"
  "api.dataset$run_query_async$fn__65276.invoke(dataset.clj:69)"
  "query_processor.streaming$streaming_response_STAR_$fn__38459$fn__38460.invoke(streaming.clj:162)"
  "query_processor.streaming$streaming_response_STAR_$fn__38459.invoke(streaming.clj:161)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$task__26889.invoke(streaming_response.clj:84)"],
 :card_id nil,
 :context :ad-hoc,
 :error
 "Numeric value out of range: \"123456789321\" in column ; SQL statement:\n-- Metabase:: userID: 1 queryType: native queryHash: dbcd794a617c71fe70c0152090faeda3912795cf999ca61d74194b15264989d9\nselect count(*) from orders where user_id in (123456789321) [22004-197]",
 :row_count 0,
 :running_time 0,
 :data {:rows [], :cols []}}

2022-03-22 19:06:57,763 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 816.1 ms (4 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (3 idle, 0 queued) (56 total active threads) Queries in flight: 0 (0 queued); h2 DB 4 connections: 0/1 (0 threads blocked)
```

</details>

**Comment by flamber** [comment] 2022-03-22 18:32
@brianschillaci So this is actually fixed in 0.42.3, and I'm guessing it's the change from `map` to `mapv`, but I don't know Clojure
https://github.com/metabase/metabase/pull/20908/files#diff-4795dfe1b125880654e2a4620fc9f8310fc06d0173f3de8b15d14534e9c270c3R219

Closing, so it gets on the release notes.

Though, I really think we need more tests for this, since it's not the first time we've broken it. @camsaul

**Closed by flamber** 2022-03-22 18:32 UTC
Labels: Type:Bug, Priority:P2, .Correctness, Querying/Parameters & Variables, Querying/Native, .Regression

**Comment by brianschillaci** [comment] 2022-03-22 19:12
@flamber Thanks! Do you know when 0.42.3 will be released?

**Comment by camsaul** [comment] 2022-03-22 19:15
Yeah we definitely need more tests around it.
@brianschillaci we're planning on releasing 42.3 either today or tomorrow

**Comment by brianschillaci** [comment] 2022-03-22 19:17
Thanks very much @camsaul !

**Comment by arvindzuddl** [comment] 2022-09-13 13:11
Comma Separate text filter not working. any idea ? @nemanjaglumac

**Comment by flamber** [comment] 2022-09-13 13:13
@arvindzuddl Whatever your problem is, is unrelated to this issue. This issue is specifically about Number filter with comma-separated values. Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
