### ISSUE TITLE
Import of CSV fails with error (integer out of range)

### ISSUE THREAD

**Issue by attaxia** [metabase/metabase#34425] opened 2023-10-06 10:00 UTC
### Describe the bug

![Screenshot 2023-10-06 at 11 57 18](https://github.com/metabase/metabase/assets/4743303/8e1dca3b-de23-4d50-aef1-f9fc6269f59e)

### To Reproduce

Upload a CSV file (in this case an exported contact list from Hubspot) with a column that contains numbers
Have a number be larger than the range of integers. 

The upload fails

### Expected behavior

Upload should succeed

### Information about your Metabase installation

```JSON
Metabase 0.47.3
Postgres 13.10
```

### Severity

Blocking some users

**Comment by tsmacdonald** [comment] 2023-10-06 11:34
Duplicate of #34080; fixed by #34118.

**Closed by tsmacdonald** 2023-10-06 11:34 UTC
Labels: Type:Bug, .Needs Triage
