### ISSUE TITLE
Select specific fields of a table in Question

### ISSUE THREAD

**Issue by nielsonsantana** [metabase/metabase#2322] opened 2016-04-06 16:29 UTC
When I try make a question, I can't specify the fields that I want on report.
How can I do it?

If this is a bug report, please fill in the blanks:
*  I am using the Firefo browser.
*  My computer's OS is Ubuntu
*  I'm running Metabase Heroku. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is Postgres.
*  My Metabase version is v0.16.1

**Comment by tlrobinson** [comment] 2016-04-06 17:08
Duplicate of #1445

**Closed by tlrobinson** 2016-04-06 17:08 UTC
