### ISSUE TITLE
Add Special Type "Time"

### ISSUE THREAD

**Issue by mvrabel** [metabase/metabase#5319] opened 2017-06-13 08:24 UTC
I have a "time" column in my Postgresql 9.6 database. When I view the table in metabase it's represented as a timestamp "Thursday, January 1,${time}".

![last_modified_time](https://user-images.githubusercontent.com/12628893/27072582-1b08c440-5021-11e7-80cb-61f4a696762a.PNG)

Postgresql time vs timestamp https://www.postgresql.org/docs/9.6/static/datatype-datetime.html

- browser: Chrome  59.0.3071.86 
- operating system: Win 10
- databases: Postgressql 9.6
- Metabase version: v0.24.2 Built on 2017-06-01
- Metabase hosting environment: CentOS 7
- Metabase internal database: I think H2 (default), I only downloaded the jar and conected to the database.

**Comment by camsaul** [comment] 2017-08-03 23:12
We already have a `:type/Time` base type. This is something that should be a "base type" rather than a special type.

Either way `:type/Time` doesn't work properly. @senior, this is what you were working on the other day, right? Not sure whether you have a separate issue for that

**Comment by senior** [comment] 2017-08-08 15:41
@camsaul  @mvrabel I was looking at this in the context of #5563. The issue is the JDBC driver is returning a java.sql.Time object. java.sql.Time is a subclass of java.util.Date, but it zeros out the year/month/day to epoch. Our code currently doesn't handle the Time fields separately, so it just treats it like a regular date object (which gives surprising results like what's above).

I will be working on a fix for this soon.

**Comment by senior** [comment] 2018-06-25 15:52
Support for Time fields was added in 0.28.0. See https://github.com/metabase/metabase/pull/6109 for more information.

**Closed by senior** 2018-06-25 15:52 UTC
Labels: Metadata/Sync, Proposal
