### ISSUE TITLE
Dashboard shows a loading notification while all cards are loaded

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#24402] opened 2022-07-28 14:07 UTC
**Describe the bug**
A timer and a notification about dashboard loading are displayed despite all dashboards cards being loaded.

**To Reproduce**
1. Go to a saved dashboard with questions and filters
2. Change a filter value and reset it
3. Click on `Edit` and then `Save` without changes
4. Change a filter value again and reset it
5. Hover over a card
6. After 10-20 seconds you will see a timer and a notification, but all cards are already loaded

Loom https://www.loom.com/share/73d4147c9ea140ae961024f1b6bbdc20

**Expected behavior**
No timer and notification since all cards are loaded

**Screenshots**
<img width="578" alt="Screenshot 2022-07-28 at 17 01 29" src="https://user-images.githubusercontent.com/8542534/181525110-6ff6fc60-f873-4c04-a644-e662cb2aeb22.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 103
- Your operating system: OS X 12.1
- Metabase version: 0.44-rc2, commit `f867e114f8c4d1f24d9670e32e557af37d9fa7cc`
- Metabase internal database: H2 (default)

**Severity**
It doesn't block me from using the dashboard but pretty annoying.

**Comment by jjromary** [comment] 2022-07-29 17:27
I'll work on this problem, okay?

**Comment by jjromary** [comment] 2022-07-29 19:11
Hi, @ranquild. I reproduced the same steps and the warning shown to you was not shown to me. I noticed that in the video the filter is not associated with a column. Is this right?

Loom video: https://www.loom.com/share/ca0218912e6445cf8618b5edabdb7129

**Comment by EmmadUsmani** [comment] 2023-02-27 22:14
I also wasn't able to reproduce this issue. @ranquild Do you know if it was already fixed (perhaps inadvertently)?

**Comment by uladzimirdev** [comment] 2023-07-31 11:45
I wasn't able to reproduce the issue

**Comment by nemanjaglumac** [comment] 2023-08-01 09:53
@uladzimirdev @ranquild whatever I tried, I couldn't reproduce it on the latest `master` f75f2866140903df66ea0f98587c947a84bba66b

**Comment by uladzimirdev** [comment] 2023-08-01 20:58
@ranquild I'm closing this, feel free to reopen if you're able to reproduce it

**Closed by uladzimirdev** 2023-08-01 20:58 UTC
Labels: Type:Bug, Priority:P3, Reporting/Dashboards, .Unable to Reproduce, .Frontend, .Regression, .Team/42 :milky_way:, .FixScope42
