### ISSUE TITLE
Improve UX of selecting included columns in joins/data steps

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10460] opened 2019-08-01 18:12 UTC
The current column picker could use a bit of improving. At minimum, it should:
- should allow you to deselect all columns on the initial Data step
- have a max-height and be scrollable

![image](https://user-images.githubusercontent.com/2223916/62316632-c5c44800-b44c-11e9-9e7d-715e300a17d5.png)

**Stretch/future follow-up:**

If we wanted to enhance it, it could:
- be in a modal so that tables with lots of columns would feel nicer
- have input boxes for the columns so you could edit their names inline
- display the underlying name of the column in the DB to increase clarity
- include the column description to make it easier to know what you're including/excluding

![pick-columns](https://user-images.githubusercontent.com/2223916/62316521-7e3dbc00-b44c-11e9-9236-b43ec56b496d.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by tlrobinson** [comment] 2019-08-21 21:33
FWIW the main reason I didn't allow "deselect all" is if you deselect all the columns we default back to including all columns.

@camsaul maybe an empty list for `fields` should actually mean no columns instead of defaulting to all columns now that we have joins which may also add columns?

**Comment by SetSails** [comment] 2019-08-23 16:10
> FWIW the main reason I didn't allow "deselect all" is if you deselect all the columns we default back to including all columns.
> 
> @camsaul maybe an empty list for `fields` should actually mean no columns instead of defaulting to all columns now that we have joins which may also add columns?

absolutely agree with @tlrobinson . With joins it's really cumbersome to uncheck each and every box one by one.

**Comment by BenjaminGK** [comment] 2019-09-02 03:35
@mazameli Do you have any estimates one when you plan to have this fixed and released along with some of the other issues reported?
We are currently being prevented from upgrading to version 0.33.0 because of these issues

**Comment by mazameli** [comment] 2019-09-02 17:06
@BenjaminGK It won't be in 0.33.1, so it'll either be 0.33.2 or 0.34.0.

Just to clarify, the `Select none` _does_ work when selecting columns for the _joined_ data. It just doesn't work for the initial data step yet as described above.

![image](https://user-images.githubusercontent.com/2223916/64128053-5605ed80-cd69-11e9-98df-7edc9abfcc80.png)

**Comment by tlrobinson** [comment] 2019-09-23 19:43
@camsaul I think the behavior of top-level `fields` should match `joins`'s `fields`, with the exception of the default (undefined/null) being `:all` instead of `:none`. Ideally `[]` would be equivalent to `:none` like it is in `joins`. It's possible that could break some existing queries, but I'd have to check to see if the frontend was even able to generate `fields: []`, it might have normalized it by removing `fields: []`.

At least adding `:all`/`:none` to top-level `:fields` would unblock this issue though.

**Comment by krainboltgreene** [comment] 2020-01-13 23:38
I'm not sure if this is the right ticket, but I would love to copy the UI for column name here to the general join ui. For example, how does the user know which table the [ID] and [Person ID] come from?

<img width="1684" alt="Screen Shot 2020-01-13 at 3 34 52 PM" src="https://user-images.githubusercontent.com/334809/72301144-bb70c180-361a-11ea-9c56-39907b7725dd.png">

**Comment by ldelaporte** [comment] 2020-02-25 20:22
Is there a fix / roadmap to look for? As the last two commenters mentioned the issue is only with the first table, "deselect all" works perfectly for joined tables. As of now, I basically can't use the interface if I want to start with a table with lots of columns and write SQL instead :)

**Comment by maxschloegl** [comment] 2020-03-04 14:45
When do you plan to fix that?

**Comment by ajcoll5** [comment] 2020-04-24 18:56
Heck I'd even settle for it not jumping you back to the top of the page when selecting or deselecting a column. :/

**Comment by pastullo** [comment] 2020-05-27 13:43
Any update on when this will be prioritized? I personally stumble upon this problem multiple times a week.
The additional bug reported by @ajcoll5 above makes it even more annoying actually.

**Comment by lajcf** [comment] 2020-06-02 11:58
+1 for this incredibly useful feature :D

**Comment by tonxxd** [comment] 2020-06-10 11:57
I think this is very important especially when using Bigquery data source. With more than 40 columns, not being able to easily deselect all columns, means Metabase performs a full table scan which is not cost-effective.

**Comment by TomFanella4** [comment] 2021-06-30 18:18
Is this still on the roadmap? Many of our tables have 10s of columns so being able to deselect all would be fantastic!

**Comment by pastullo** [comment] 2021-07-14 13:53
Yeah this is still something needed!
Funny enough it is already implemented when doing a join, but not on the
base table.

**Comment by pastullo** [comment] 2021-08-30 16:15
Any news on this? Seems like a quick fix that would improve the UX!

**Comment by krainboltgreene** [comment] 2021-08-30 18:03
I see that it's been noted as "P1", I assume that means high priority, is there anyway I can assist with this ticket?

**Comment by ofirnn** [comment] 2021-11-02 08:17
Any updates on this? we're on a very old version of Metabase due to the issue, since we have hundreds of fields on each table.

**Comment by akimchrome** [comment] 2021-11-22 23:00
Any updates?

**Comment by alxnddr** [comment] 2021-12-09 17:56
@flamber should we make it P2–P3 now?

**Comment by flamber** [comment] 2021-12-09 18:01
It will be possible to unselect the base-table (expect a minimum of 1 column) from the upcoming version 0.42 (January). #19186
This issue will remain open until a better experience is provided for managing larger tables.

**Comment by pastullo** [comment] 2021-12-09 18:29
Yessss! that's all we need

**Comment by mazameli** [comment] 2022-01-12 19:15
@pastullo and everyone else — here's what you'll be able to do in version 0.42/1.42:

![deselect-cols](https://user-images.githubusercontent.com/2223916/149206503-8468c652-e39b-4682-ba3f-1534924669c0.gif)

**Comment by krainboltgreene** [comment] 2022-01-12 20:09
Absolutely fucking beautiful.

**Comment by pastullo** [comment] 2022-01-12 22:18
Just forwarded this to the entire company! LEGENDARY

**Comment by ravindra887** [comment] 2023-06-15 19:00
For older versions of metabase.
If you have too many properties to uncheck, execute this script in your browser console after clicking on the table properties. This should uncheck all properties except the first one, had to use `requestIdleCallback` because unchecking many buttons at once causes page to crash.
```
function uncheckButtonsWithIdleCallback(buttons) {
  let index = 2;

  function processBatch(deadline) {
    while (index < buttons.length && deadline.timeRemaining() > 0) {
      const button = buttons[index];
      if (button.checked === true) {
        button.click();
      }
      index++;
    }

    if (index < buttons.length) {
      requestIdleCallback(processBatch);
    }
  }

  requestIdleCallback(processBatch);
}

const buttons = document.querySelectorAll(
  ".CheckBoxstyled__Input-rzkbqg-3.krmPTr"
); //validate the classname of the buttons
uncheckButtonsWithIdleCallback(buttons);
```

**Comment by mngr** [comment] 2024-03-27 22:01
@mazameli shouldn't we close this as we've implemented showing metadata already?

**Closed** 2024-04-02 23:15 UTC
Labels: Type:UX, Priority:P2, Difficulty:Medium, .Frontend, .Backend, Querying/Notebook
