### ISSUE TITLE
Select All Fields -> Unselect all fields

### ISSUE THREAD

**Issue by FinnFrotscher** [metabase/metabase#20582] opened 2022-02-17 12:09 UTC
In the view where i select fields, its weird that i cant unselect all. 

<img width="251" alt="image" src="https://user-images.githubusercontent.com/11148454/154478875-93f7fc7f-0591-4ac1-80c6-7e01197ff88c.png">

**Comment by flamber** [comment] 2022-02-17 12:50
Duplicate of https://github.com/metabase/metabase/issues/10460#issuecomment-1011369806

**Closed by flamber** 2022-02-17 12:50 UTC
Labels: Type:New Feature, .Needs Triage
