### ISSUE TITLE
Custom Column after aggregation causes dashboard filtering to be very limited

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#19744] opened 2022-01-18 15:44 UTC
**Describe the bug**
When adding a Custom Column after aggregation, then dashboard filters cannot be connected to fields before the aggregation.

Close P1, since it makes creating more complex questions difficult to use with dashboard filters.

**To Reproduce**
1. Custom question > Sample Dataset > Products
2. Summarize Count, Sum of Price, Sum of Rating - grouped by Category - add Custom Column `1 + 1`
![image](https://user-images.githubusercontent.com/1447303/149966747-458a3393-753e-4351-927b-14fa9e5943e1.png)
3. Add to dashboard, add Time filter and try to connect to card - it will say `No valid fields` on the card.
![image](https://user-images.githubusercontent.com/1447303/149969592-f25b0991-aa7b-4c60-acb8-b2a8afe8c94a.png)

**Expected behavior**
Even when added a Custom Column after the aggregation, then I should still be able to filter with fields from before the aggregation.
![image](https://user-images.githubusercontent.com/1447303/149969787-b31af8b7-3f8e-496e-9e50-db04aa06a21d.png)

**Information about your Metabase Installation:**
Tested 0.37.8 thru 0.41.6

**Additional context**
Creating a separate issue, so it doesn't get overlooked when fixing #12985, which is likely the underlying root causes.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment] 2022-01-18 22:34
Fixed by #19384

**Comment by ranquild** [comment] 2023-01-23 16:37
For anyone reading this, the workaround is to have your custom columns **before** filters and aggregations, like this: 

<img width="1289" alt="Screenshot 2023-01-23 at 18 35 32" src="https://user-images.githubusercontent.com/8542534/214096522-0d5a7e91-819e-4400-ade4-29d3a5282646.png">

**Comment by cdeweyx** [comment] 2023-04-12 00:57
I agree with @ranquild's comment above re expected behavior here. De-prioritizing for now.

**Comment by rognstad** [comment] 2023-04-12 02:23
I think the buggy behavior here is that if you have any custom columns after aggregation, then *no* fields are available for filtering.

I ran into this once when trying to concat a summed field with a localized unit of measure, e.g. total distance for races someone ran.

**Comment by paoliniluis** [comment] 2023-05-05 20:40
@cdeweyx @ranquild just had a meeting with the customer where they need to pass a dashboard filter to an intermediate stage. Their use case is pretty straightforward: it's an aggregation of an aggregation, and they can't pass that filter at the last stage of the query :(

**Comment by ranquild** [comment] 2023-05-29 11:17
This is a limitation in the query process, more details here https://metaboat.slack.com/archives/C052ZBWRG3W/p1683320074594969

**Comment by bshepherdson** [comment] 2024-02-16 18:10
From @luizarakaki:
- this is closer to a feature request than a bug
- the best place to be filtering the query is _the earliest stage with an aggregation_ in 99% of cases.
- it's possible that one might want to filter based on a custom column in a later stage which is itself aggregated, but that's quite rare.

This probably calls for a new MLv2 function to encode that logic. It's more general than `filterable-columns`, since it doesn't examine a specific `stage-number`. Maybe `(lib/parameter-mappable-columns query)`? (That name could be a lot better; I'm open to ideas.)

**Comment by paoliniluis** [comment] 2024-02-16 19:17
@bshepherdson customers that are waiting for this need to connect a filter to any stage of the query, is that possible?

**Comment by luizarakaki** [comment] 2024-02-16 20:45
It is, but then we would need to iterate on the UI to assign fields to params. We would need to represent different stages when selecting the field

**Comment by bshepherdson** [comment] 2024-06-21 15:48
The difference in these queries is that the post-aggregation `negative` expression adds a second stage.

So this example illustrates what Arakaki said (and I repeated [here](https://github.com/metabase/metabase/issues/19744#issuecomment-1949020580)): that the best default for attaching dashboard filters is _the earliest stage with an aggregation_, ie. the first stage here. Then we should get the same filter options and query results as the left query.

I'll look at implementing this with a new function like I mentioned above.

**Comment by perivamsi** [comment] 2024-07-16 13:39
Closed the other one, will track the work here https://github.com/metabase/metabase/issues/26244

**Comment by mngr** [comment] 2024-07-16 17:41
I also think this is not a bug but a feature request. Currently we have all this logic about query stages but it is not visible to the users hence they keep frustrating about why some columns are shown in the dashboard filters and others are not.
So we are going to tackle this from 2 directions: 1) allow filtering by columns from multiple stages 2) better explain or modify the logic of the query builder.

**Closed** 2024-11-22 22:49 UTC
Labels: Type:Bug, Type:UX, Priority:P1, Reporting/Dashboards, Querying/Parameters & Variables, .Completeness, Difficulty:Hard, .Frontend, .Backend, .Reproduced, .Wanted: MLv2, .Team/Querying
