### ISSUE TITLE
UUID filter not work for click behavior

### ISSUE THREAD

**Issue by shumkovdenis** [metabase/metabase#15516] opened 2021-04-07 15:40 UTC
**Describe the bug**
Dashboard click behavior not work for UUID type filed.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
I have two postgresql tables:

_Games_

- id (UUID)
- title (Text)

_Rooms_

- id (UUID)
- title (Text)
- game_id (UUID) FK for Games.id

Add dashboard _Main_ with question Games (table view)
Add dashboard _Game_ with question Rooms (table view) and add ID filter for game_id.

1. Go to 'Main dashboard.'
2. Click on 'Edit dashboard'
3. Open 'Click behavior'
4. Select 'title' field'
5. Select 'Go to a custom destination'
6. Select 'Link to 'Dashboard''
7. Select _Game_ dashboard
8. In 'Available filters' no ID filter from  _Game_ dashboard. Erorr?

**Expected behavior**
I expected ID filter from  _Game_ dashboard in 'Available filters' list.

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "ru-RU",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "5.4.95-42.163.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.1 (Debian 13.1-1.pgdg100+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-01",
      "tag": "v0.38.3",
      "branch": "release-x.38.x",
      "hash": "8332830"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
This problem makes it very difficult to configure the analytics system.

**Comment by flamber** [comment] 2021-04-07 16:20
Duplicate of #15170

**Closed by flamber** 2021-04-07 16:20 UTC
Labels: .Needs Triage, Type:Bug

**Comment by shumkovdenis** [comment] 2021-04-07 18:30
Thanks!
