### ISSUE TITLE
Filter dropdown too large on mobile

### ISSUE THREAD

**Issue by Sire** [metabase/metabase#12768] opened 2020-06-24 13:35 UTC
The filter dropdown is locked to a minimum width of 400 pixels. This might look good on desktop, but clips on most mobiles, with just 1rem padding. Looks like this:

![metabase popover mobile screenshot](https://user-images.githubusercontent.com/205954/85564932-f5fd7200-b62e-11ea-9fac-b2f556178295.png)

I'm running Metabase embedded in an iframe. Worked fine for months until I added a filter.

The reason is this PopOver html code, that for some reason is using style attributes instead of css:

![metabase popover mobile](https://user-images.githubusercontent.com/205954/85565351-58ef0900-b62f-11ea-9227-88da2fcb5e5e.png)

The fix is simple: Use `min-width: 200px; max-width: 400px;`  
instead of 400px. Still looks good on desktop, and will scale up to 400 px as before.
You might also consider changing the max-width to 370px which makes it look fine even at max size on mobile.

Metabase: 0.35.4 (latest)
Browser: Chrome on Pixel 2, Chrome on Windows with responsive mode and Pixel 2 width.

**Comment by flamber** [comment] 2020-06-24 13:44
Duplicate of #12440

**Closed by flamber** 2020-06-24 13:44 UTC
Labels: .Needs Triage, Type:Bug
