### ISSUE TITLE
Stop translating error log messages

### ISSUE THREAD

**Issue by darksciencebase** [metabase/metabase#33340] opened 2023-08-18 15:30 UTC
In the scope of this task is just to stop translating the error messages that go into the log. The translations complicate debugging for us and limit the ability of our users to figure out what's going on.

**Comment by paoliniluis** [comment] 2023-08-21 12:48
Dupe of https://github.com/metabase/metabase/issues/10764

**Comment by darksciencebase** [comment] 2023-08-23 15:40
Less of a dupe and more of breaking it down into two tasks so that we can do one thing without necessarily going all the way down the road with the second just yet.

**Comment by darksciencebase** [comment] 2024-04-08 05:54
closed by https://github.com/metabase/metabase/pull/41067

**Closed** 2024-04-08 05:54 UTC
Labels: Type:Tech Debt, Administration/Troubleshooting, .Task, :broom:
