### ISSUE TITLE
Admin Panel : Database form not loading properly

### ISSUE THREAD

**Issue by hugocar** [metabase/metabase#3603] opened 2016-10-17 16:07 UTC
> ### Bugs
> If you're filing an issue about a bug please include as much information
> as you can including the following.

- Metabase version: 0.20

When switching from a database form to an other the form inputs are not reloaded.

This is very very tricky ! Trying to update a database password, I ended up giving it the config of an other base. getting the two databases referenced under the same name and causing questions to malfunction. (Especially tricky in my case, because the two databases share the same structure with different data !)

**Comment by mazameli** [comment] 2016-10-17 16:18
Can confirm this behavior. When switching DBs, it displays the last DB you looked at rather than the one you've just selected. This is a must-fix.

**Comment by salsakran** [comment] 2016-10-17 16:55
I'm pretty sure this has the same underlying cause as  #3359

**Comment by tlrobinson** [comment] 2016-10-17 17:33
This sounds like a duplicate of #3359. I've marked that one as P1.

**Closed by tlrobinson** 2016-10-17 17:33 UTC
Labels: Bug, Priority/P1
