### ISSUE TITLE
Do not offer "Explore results" if the question has parameters

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#29404] opened 2023-03-21 17:27 UTC
**Describe the bug**
If we know that the question has template tags, we shouldn't show the button, as it will end up as a broken question :(

**Logs**
NA

**To Reproduce**
1) create a sql question like "select * from people" where state = {{state}}"
2) save it
3) click explore

**Expected behavior**
We shouldn't show the button if it's a sql question with template tags as it won't work

**Screenshots/videos**
NA

**Information about your Metabase Installation:**
- Metabase version: 1.45.3 (it's been there since the button was created)

**Severity**
P3

**Additional context**
NA

**Comment by oleggromov** [comment] 2023-12-27 11:31
This is a duplicate of https://github.com/metabase/metabase/issues/35476, which was fixed by https://github.com/metabase/metabase/pull/36105. The fix still works on the current `master`.

**Closed by oleggromov** 2023-12-27 11:31 UTC
Labels: Type:Bug, Priority:P3, Querying/Native
