### ISSUE TITLE
Metabase model using removed fields

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#27087] opened 2022-12-08 19:32 UTC
**Describe the bug**
I have a Metabase model that selects all fields from a raw table. After renaming a field in the raw table to a new name, the Metabase model is broken as it can't find the old field. 

**Logs**
N/a

**To Reproduce**

Create a new model that selects all fields and then rename a field in the raw table. The model will be broken (as expected? Since it's select all, I would imagine it should just update with the new field name automatically -- and breaking downstream consumers). 

When you try to update the model definition:
1.  While the old field isn't listed, it still tries to query it. 
2. When de-select all fields, it works by showing the id only. 
3. When I select all fields, another error about bad field id. 
4. To make it work, I had to de-select all fields, save (this is the key), and then re-edit and re-select all fields. 

In the process, I also duplicated the broken model, and strangely, it fixed itself when I try to view it later. So there seems to be some sort of process that updates the fields used in a model?  Maybe it fixes after duplicating but just doesn't work until you re-open it later? 

**Expected behavior**
For select all models, it should update automatically with any field name changes. 
Otherwise, when editing the model, it should pull in the new fields automatically and allow you to save. 
At the minimal, deselect all and then re-select all fields should fix the problem -- though that might not be intuitive for most users. 

**Screenshots**
n/a
**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome
- Your operating system:  OS X
- Your databases: Postgres
- Metabase version: master
- Metabase hosting environment: Metabase Cloud?
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?

It makes updating raw tables more cumbersome as it requires an edit dance for the Metabase model. 

**Additional context**
n/a

**Comment by flamber** [comment] 2022-12-09 12:18
Seems very related to #7884, #12721 and #10371

**Comment by ranquild** [comment] 2023-11-08 10:12
I can still reproduce using latest `master`. The steps:

- Create a new table in the DB (could be sample DB). `CREATE TABLE TEST(ID INT, TITLE TEXT)`
- Sync the database schema
- Create a new GUI model based on the table. Don't select any fields - all fields are selected by default.
- Create a new question based on this model.
- Now rename `TITLE` to `NAME` in the DB and re-sync the schema. 
- Make sure the schema is updated in Admin -> Table Metadata.
- Open the model. It would be broken - the query cannot be executed.
- Try to `Edit metadata`. There would be an error.
- The only workaround would be to go to the `Query` tab, change "Fields", save the model, then select all fields and save the model again.

<img width="1499" alt="Screenshot 2023-11-08 at 12 08 56" src="https://github.com/metabase/metabase/assets/8542534/baeb9db8-ef39-4e0b-ac5a-8a98964cca9f">
<img width="1728" alt="Screenshot 2023-11-08 at 12 09 09" src="https://github.com/metabase/metabase/assets/8542534/e3400467-df5b-4cae-abf5-154d3bfcb2b9">

**Comment by camsaul** [comment] 2024-06-26 03:24
Closing as duplicate of #12721

This is not specific to models, any sort of Saved Question that has a column removed stops working. We have some planned ways to work around this in the future, see #12721 and #39008 for more information.

Duplicate of #12721

**Closed by camsaul** 2024-06-26 03:24 UTC
Labels: Type:Bug, Priority:P2, .Backend, Querying/Models, .Team/QueryProcessor, .Wanted: MLv2
