### ISSUE TITLE
Date type variable Problem

### ISSUE THREAD

**Issue by iamkyu** [metabase/metabase#6402] opened 2017-11-15 23:29 UTC
In this configuration,

- Settings> General> Report Timezone to Asia / Seoul
- MySQL database time zone setting is Asia / Seoul

When I use Date type Variable in Query, subtracted 9 hours. 
Is this the intended function?

![2017-11-15 4 48 04](https://user-images.githubusercontent.com/13076271/32865783-020da99a-caa8-11e7-8668-ac3f52cd3773.png)

More Information
- Chrome 64.0.3268.0 canary (64bit)
- macOS High Sierra 10.13.1
- Metabase version: 0.26.2
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: MySQL

**Comment by camsaul** [comment] 2017-11-16 00:24
@iamkyu what happens if you just do `SELECT {{date}}`?

**Comment by iamkyu** [comment] 2017-11-16 01:14
<img width="1378" alt="2017-11-16 10 11 25" src="https://user-images.githubusercontent.com/13076271/32868683-a793e632-cab6-11e7-93a0-f54d090e296d.png">

@camsaul same.

**Comment by davidRichards39** [comment] 2018-03-07 17:11
I'm seeing a similar issue with Postgres.
Reporting timezone is configured as US/Eastern, however the resolved date appears to be the start of the previous day (rather than the start of the specified date).

![mbissue](https://user-images.githubusercontent.com/17985578/37106641-5638600a-2200-11e8-97ef-7fdf82405524.png)

- Chrome 64.0.3282.140 (Official Build) (64-bit)
- Ubuntu 17.10
- Metabase version: v0.28.1
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

**Comment by senior** [comment] 2018-04-26 21:14
@iamkyu I've done some investigation into your issue and I think Metabase is working as intended. When you issue a query like the query above, a date parameter is included in the query and we're adjusting it according the report timezone setting. Our dates always get converted to timestamps, so the 12:00 AM timestamp gets adjusting to the report timezone that was configured. Depending on how the query is written, that date can be a string or a date:
```
select {{date}} -> "2018-04-18 04:00:00"
```
If I'm explicit about the date: 
```
select cast({{date}} as date) -> "2018-04-18T04:00:00.000-00:00"
```
The second result is a date object as well, whereas the first result just includes a string.

**Comment by senior** [comment] 2018-04-26 21:16
@davidRichards39 I'm thinking your issue might be different. I tried to recreate it but wasn't able to. Can you provide some additional details? Are you querying against a PostgreSQL instance or is that just what your Metabase internal database is using? What timezone is that instance in?

**Comment by davidRichards39** [comment] 2018-04-27 21:16
@senior I'll try to provide as much as I can!
Elastic Beanstalk is telling me that the Metabase internal database is PostgreSQL (in addition to querying against a PostgreSQL database). Metabase is configured to use use US/Eastern as the report timezone. I can confirm that this issue is still present in 0.28.5

**Comment by senior** [comment] 2018-05-08 13:43
@davidRichards39 @iamkyu I've figured out the issue. Metabase was incorrectly parsing the dates in the JVM timezone, rather than in the report timezone that was configured. I have fix for it in https://github.com/metabase/metabase/pull/7520. It still needs some work, but should be merged soon

**Closed** 2018-05-22 02:53 UTC
Labels: Bug, Priority/P1, Timezones/Calendars
