### ISSUE TITLE
Can't update DB after column rename/delete

### ISSUE THREAD

**Issue by eladeyal-intel** [metabase/metabase#6155] opened 2017-10-12 09:37 UTC
- browser : Chrome 61 on Windows 10
- BS: MariaDB
- Metabase version: 0.26.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

may be the same as #6146, #6108

Create a MariaDB View or a table TTTT  (I've seen the problem with both, I think, see below. I caould not narrow this down.)
TTTT has multiple fields, among them a field FFFF. FFFF is an INT, foreign key to another table.

Admin -> Data model shows that FFFF is a foreign key. Set "Display value" for FFFF to "Use foreign key"

Open a new question to show the offending table in "raw data". alterantively, go to "Learn About Your Data", select TTTT and select "Show the raw data".

# Problem 1: You get the message "Unknown column 'TTTT.FFFF' in 'field list'" and the table is not displayed. 

Oct 12 08:29:58 WARN metabase.query-processor :: {:status :failed,
:class java.lang.Exception,
:error "Unknown column 'TTTT.FFFF' in 'field list'",
:stacktrace
["driver.generic_sql.query_processor$do_with_try_catch.invokeStatic(query_processor.clj:444)"
"driver.generic_sql.query_processor$do_with_try_catch.invoke(query_processor.clj:440)"
"driver.generic_sql.query_processor$execute_query.invokeStatic(query_processor.clj:491)"
"driver.generic_sql.query_processor$execute_query.invoke(query_processor.clj:487)"
"driver$fn__22726$G__22719__22733.invoke(driver.clj:34)"
"query_processor$execute_query.invokeStatic(query_processor.clj:50)"
"query_processor$execute_query.invoke(query_processor.clj:44)"
"query_processor.middleware.mbql_to_native$mbql__GT_native$fn__26974.invoke(mbql_to_native.clj:30)"
"query_processor.middleware.annotate_and_sort$annotate_and_sort$fn__25402.invoke(annotate_and_sort.clj:41)"
"query_processor.middleware.limit$limit$fn__26929.invoke(limit.clj:14)"
"query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__26791.invoke(cumulative_aggregations.clj:46)"
"query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__26791.invoke(cumulative_aggregations.clj:46)"
"query_processor.middleware.format_rows$format_rows$fn__26919.invoke(format_rows.clj:21)"
"query_processor.middleware.binning$update_binning_strategy$fn__25481.invoke(binning.clj:172)"
"query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__28198.invoke(results_metadata.clj:89)"
"query_processor.middleware.resolve$resolve_middleware$fn__25009.invoke(resolve.clj:359)"
"query_processor.middleware.expand$expand_middleware$fn__26685.invoke(expand.clj:550)"
"query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__25093.invoke(add_row_count_and_status.clj:14)"
"query_processor.middleware.driver_specific$process_query_in_context$fn__26811.invoke(driver_specific.clj:12)"
"query_processor.middleware.resolve_driver$resolve_driver$fn__28209.invoke(resolve_driver.clj:14)"
"query_processor.middleware.cache$maybe_return_cached_results$fn__25562.invoke(cache.clj:146)"
"query_processor.middleware.catch_exceptions$catch_exceptions$fn__26733.invoke(catch_exceptions.clj:58)"
"query_processor$process_query.invokeStatic(query_processor.clj:126)"
"query_processor$process_query.invoke(query_processor.clj:122)"
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:234)"
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:229)"
"query_processor$fn__28243$process_query_and_save_execution_BANG___28248$fn__28249.invoke(query_processor.clj:272)"
"query_processor$fn__28243$process_query_and_save_execution_BANG___28248.invoke(query_processor.clj:258)"
"api.dataset$fn__30133$fn__30136.invoke(dataset.clj:63)"
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:248)"
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:243)"
"api.dataset$fn__30133.invokeStatic(dataset.clj:54)"
"api.dataset$fn__30133.invoke(dataset.clj:54)"
"middleware$enforce_authentication$fn__29522.invoke(middleware.clj:122)"
"api.routes$fn__43823.invokeStatic(routes.clj:61)"
"api.routes$fn__43823.invoke(routes.clj:61)"
"routes$fn__44402$fn__44403.doInvoke(routes.clj:75)"
"routes$fn__44402.invokeStatic(routes.clj:71)"
"routes$fn__44402.invoke(routes.clj:71)"
"middleware$log_api_call$fn__29621$fn__29623.invoke(middleware.clj:330)"
"middleware$log_api_call$fn__29621.invoke(middleware.clj:329)"
"middleware$add_security_headers$fn__29571.invoke(middleware.clj:245)"
"middleware$bind_current_user$fn__29526.invoke(middleware.clj:142)"
"middleware$maybe_set_site_url$fn__29575.invoke(middleware.clj:268)"],
:query
{:type "query",
:query {:source_table 13},
:parameters [],
:constraints {:max-results 10000, :max-results-bare-rows 2000},
:info
{:executed-by 4,
:context :ad-hoc,
:card-id nil,
:nested? false,
:query-hash [-121, -20, 5, 108, 11, 38, -5, -81, 45, -93, 46, -111, 113, -22, 114, -64, 62, -103, 41, 61, 36, 1, -104, 29, -51, 4, 11, 98, 63, 4, 109, 67],
:query-type "MBQL"}},
:expanded-query nil}

Oct 12 08:29:58 WARN metabase.query-processor :: Query failure: Unknown column 'TTTT.FFFF' in 'field list'
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:203)"
"query_processor$assert_query_status_successful.invoke(query_processor.clj:196)"
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:235)"
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:229)"
"query_processor$fn__28243$process_query_and_save_execution_BANG___28248$fn__28249.invoke(query_processor.clj:272)"
"query_processor$fn__28243$process_query_and_save_execution_BANG___28248.invoke(query_processor.clj:258)"
"api.dataset$fn__30133$fn__30136.invoke(dataset.clj:63)"
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:248)"
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:243)"
"api.dataset$fn__30133.invokeStatic(dataset.clj:54)"
"api.dataset$fn__30133.invoke(dataset.clj:54)"
"middleware$enforce_authentication$fn__29522.invoke(middleware.clj:122)"
"api.routes$fn__43823.invokeStatic(routes.clj:61)"
"api.routes$fn__43823.invoke(routes.clj:61)"
"routes$fn__44402$fn__44403.doInvoke(routes.clj:75)"
"routes$fn__44402.invokeStatic(routes.clj:71)"
"routes$fn__44402.invoke(routes.clj:71)"
"middleware$log_api_call$fn__29621$fn__29623.invoke(middleware.clj:330)"
"middleware$log_api_call$fn__29621.invoke(middleware.clj:329)"
"middleware$add_security_headers$fn__29571.invoke(middleware.clj:245)"
"middleware$bind_current_user$fn__29526.invoke(middleware.clj:142)"
"middleware$maybe_set_site_url$fn__29575.invoke(middleware.clj:268)"]

# Problem 2: Database -> DB name -> Sync fails

What I think is hapenning, is that the enine finds a problem with one field and then aborts the rest of the sync.

Oct 12 08:39:02 INFO metabase.sync.util :: STARTING: Sync metadata for mysql Database 2 'Data'
Oct 12 08:39:03 ERROR metabase.sync.util :: Error syncing FKs for Table 29 'TTTT': SHOW VIEW command denied to user 'XXXXX'@'XXXXX' for table 'TTTT'
("driver.generic_sql$describe_table_fks.invokeStatic(generic_sql.clj:351)"
"driver.generic_sql$describe_table_fks.invoke(generic_sql.clj:349)"
"driver$fn__22808$G__22715__22817.invoke(driver.clj:34)"
"sync.fetch_metadata$fn__32476$fk_metadata__32481$fn__32482.invoke(fetch_metadata.clj:25)"
"sync.fetch_metadata$fn__32476$fk_metadata__32481.invoke(fetch_metadata.clj:20)"
"sync.sync_metadata.fks$fn__33046$sync_fks_for_table_BANG___33055$fn__33058$fn__33059.invoke(fks.clj:67)"
"sync.util$do_with_error_handling.invokeStatic(util.clj:115)"
"sync.util$do_with_error_handling.invoke(util.clj:110)"
"sync.sync_metadata.fks$fn__33046$sync_fks_for_table_BANG___33055$fn__33058.invoke(fks.clj:66)"
"sync.sync_metadata.fks$fn__33046$sync_fks_for_table_BANG___33055.invoke(fks.clj:61)"
"sync.sync_metadata.fks$fn__33090$sync_fks_BANG___33095$fn__33096.invoke(fks.clj:75)"
"sync.sync_metadata.fks$fn__33090$sync_fks_BANG___33095.invoke(fks.clj:70)"
"sync.sync_metadata$fn__33520$sync_db_metadata_BANG___33525$fn__33526$fn__33527.invoke(sync_metadata.clj:30)"
"sync.util$do_with_error_handling.invokeStatic(util.clj:115)"
"sync.util$do_with_error_handling.invoke(util.clj:110)"
"sync.util$do_with_error_handling.invokeStatic(util.clj:113)"
"sync.util$do_with_error_handling.invoke(util.clj:110)"
"driver$fn__22940.invokeStatic(driver.clj:209)"
"driver$fn__22940.invoke(driver.clj:209)"
"driver$fn__22914$G__22695__22923.invoke(driver.clj:34)"
"sync.util$sync_in_context$fn__30912.invoke(util.clj:106)"
"sync.util$with_db_logging_disabled$fn__30909.invoke(util.clj:98)"
"sync.util$with_start_and_finish_logging$fn__30904.invoke(util.clj:87)"
"sync.util$with_sync_events$fn__30901.invoke(util.clj:70)"
"sync.util$with_duplicate_ops_prevented$fn__30892.invoke(util.clj:49)"
"sync.util$do_sync_operation.invokeStatic(util.clj:133)"
"sync.util$do_sync_operation.invoke(util.clj:130)"
"sync.sync_metadata$fn__33520$sync_db_metadata_BANG___33525$fn__33526.invoke(sync_metadata.clj:23)"
"sync.sync_metadata$fn__33520$sync_db_metadata_BANG___33525.invoke(sync_metadata.clj:20)"
"api.database$fn__34163$fn__34164$fn__34165.invoke(database.clj:495)")

Oct 12 08:39:03 ERROR metabase.sync.util :: Error syncing FKs for Table 38 'TTTT': SHOW VIEW command denied to user 'XXXX'@'XXXX' for table 'TTTTTTT'
("driver.generic_sql$describe_table_fks.invokeStatic(generic_sql.clj:351)"
"driver.generic_sql$describe_table_fks.invoke(generic_sql.clj:349)"
"driver$fn__22808$G__22715__22817.invoke(driver.clj:34)"
"sync.fetch_metadata$fn__32476$fk_metadata__32481$fn__32482.invoke(fetch_metadata.clj:25)"
"sync.fetch_metadata$fn__32476$fk_metadata__32481.invoke(fetch_metadata.clj:20)"
"sync.sync_metadata.fks$fn__33046$sync_fks_for_table_BANG___33055$fn__33058$fn__33059.invoke(fks.clj:67)"
"sync.util$do_with_error_handling.invokeStatic(util.clj:115)"
"sync.util$do_with_error_handling.invoke(util.clj:110)"
"sync.sync_metadata.fks$fn__33046$sync_fks_for_table_BANG___33055$fn__33058.invoke(fks.clj:66)"
"sync.sync_metadata.fks$fn__33046$sync_fks_for_table_BANG___33055.invoke(fks.clj:61)"
"sync.sync_metadata.fks$fn__33090$sync_fks_BANG___33095$fn__33096.invoke(fks.clj:75)"
"sync.sync_metadata.fks$fn__33090$sync_fks_BANG___33095.invoke(fks.clj:70)"
"sync.sync_metadata$fn__33520$sync_db_metadata_BANG___33525$fn__33526$fn__33527.invoke(sync_metadata.clj:30)"
"sync.util$do_with_error_handling.invokeStatic(util.clj:115)"
"sync.util$do_with_error_handling.invoke(util.clj:110)"
"sync.util$do_with_error_handling.invokeStatic(util.clj:113)"
"sync.util$do_with_error_handling.invoke(util.clj:110)"
"driver$fn__22940.invokeStatic(driver.clj:209)"
"driver$fn__22940.invoke(driver.clj:209)"
"driver$fn__22914$G__22695__22923.invoke(driver.clj:34)"
"sync.util$sync_in_context$fn__30912.invoke(util.clj:106)"
"sync.util$with_db_logging_disabled$fn__30909.invoke(util.clj:98)"
"sync.util$with_start_and_finish_logging$fn__30904.invoke(util.clj:87)"
"sync.util$with_sync_events$fn__30901.invoke(util.clj:70)"
"sync.util$with_duplicate_ops_prevented$fn__30892.invoke(util.clj:49)"
"sync.util$do_sync_operation.invokeStatic(util.clj:133)"
"sync.util$do_sync_operation.invoke(util.clj:130)"
"sync.sync_metadata$fn__33520$sync_db_metadata_BANG___33525$fn__33526.invoke(sync_metadata.clj:23)"
"sync.sync_metadata$fn__33520$sync_db_metadata_BANG___33525.invoke(sync_metadata.clj:20)"
"api.database$fn__34163$fn__34164$fn__34165.invoke(database.clj:495)")

Here I expected to see the same error reported for other tables, becuase I have a few of them. But I only see a message twice for same table. 

Oct 12 08:39:03 INFO metabase.sync.util :: FINISHED: Sync metadata for mysql Database 2 'Data' (1 s)

Another relevant log message. When I try "Admin -> Data model -> TTTT -> FFFF -> Rescan this field" the log show

Oct 12 08:45:20 ERROR metabase.driver.generic-sql.query-processor :: nil

# things I tried for solving

(1) While the log message say "denied to user", i'm quite positive there's no permission issue there in the DB. If I could know the SQL command which is being attempted I can verify this.

(2) change the Data Model to treat FFFF as "Other data" and  not foreign key. did not help

(3) look for offending questions. Change them to SQL and change the SQL query to :  `select "temp";` . Did not help.

(4) Admin -> Data base -> danger zone -> discard and then resync. did not help.

(5) Admin -> Data model -> change offending fields visibility to "Hidden". This solves the problem of "Raw data not displayed", but the database will not update.

**Comment by monitaure** [comment] 2017-10-12 12:33
:+1: just found that I've got the same problem, with the same errors after a rename of column. 

@eladeyal-intel thanks for the _"Hidden"_ visibility, I can get the raw data too.

**Comment by eladeyal-intel** [comment] 2017-10-15 15:53
I tried to enable all debugging vie log4j.properties but does not get a lot of more information:

10-15 18:49:12 ←[1mINFO sync.util←[0m :: STARTING: Sync metadata for mysql Database 2 'Data'
10-15 18:49:20 ←[1mERROR sync.util←[0m :: Error syncing FKs for Table 29 'VVVVVV': SHOW VIEW command denied to user 'XXXXX'@'YYYYYY' for table 'VVVVVV'
("driver.generic_sql$describe_table_fks.invokeStatic(generic_sql.clj:351)"
 "driver.generic_sql$describe_table_fks.invoke(generic_sql.clj:349)"
 "driver$fn__22808$G__22715__22817.invoke(driver.clj:34)"
 "sync.fetch_metadata$fn__32476$fk_metadata__32481$fn__32482.invoke(fetch_metadata.clj:25)"
 "sync.fetch_metadata$fn__32476$fk_metadata__32481.invoke(fetch_metadata.clj:20)"
 "sync.sync_metadata.fks$fn__33046$sync_fks_for_table_BANG___33055$fn__33058$fn__33059.invoke(fks.clj:67)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:115)"
 "sync.util$do_with_error_handling.invoke(util.clj:110)"
 "sync.sync_metadata.fks$fn__33046$sync_fks_for_table_BANG___33055$fn__33058.invoke(fks.clj:66)"
 "sync.sync_metadata.fks$fn__33046$sync_fks_for_table_BANG___33055.invoke(fks.clj:61)"
 "sync.sync_metadata.fks$fn__33090$sync_fks_BANG___33095$fn__33096.invoke(fks.clj:75)"
 "sync.sync_metadata.fks$fn__33090$sync_fks_BANG___33095.invoke(fks.clj:70)"

**Comment by camsaul** [comment] 2017-12-07 02:53
> Error syncing FKs for Table 29 'VVVVVV': SHOW VIEW command denied to user 'XXXXX'@'YYYYYY' for table 'VVVVVV'

@eladeyal-intel it sounds like the user you are using to connect to the MySQL database doesn't have sufficient permissions.

**Comment by LionelBino** [comment] 2017-12-15 13:43
I have the same issue when try a connect with a MySQL database.

**Comment by camsaul** [comment] 2017-12-20 00:07
This (or parts of this) are likely a duplicate of #6146

**Closed** 2017-12-20 20:18 UTC
Labels: Bug, Metadata/Sync, Priority/P2

**Comment by salsakran** [comment] 2017-12-20 20:27
@eladeyal-intel we believe that #6601 fixed your first issue.

The second issue seems to be due to user permissions on views and not an actual bug. If you discover we're incorrect on either #6601 fixing the first problem or that it's an actual bug in scenario #2, please reopen this issue.
