### ISSUE TITLE
Error adding question to dashboard

### ISSUE THREAD

**Issue by bplmp** [metabase/metabase#11724] opened 2020-01-15 14:16 UTC
**Describe the bug**
When I try to add a question to a dashboard, after I click on the question name in the modal, nothing happens. But, if I leave the dashboard open for a long time in my browser (5+ minutes), strangely, I can then add a question successfully.

**Logs**
Javascript console logs:

    vendor.bundle.js?fd220da862d7458722d7:1 Uncaught TypeError: Cannot read property 'id' of undefined
        at app-main.bundle.js?fd220da862d7458722d7:5
        at app-main.bundle.js?fd220da862d7458722d7:5
        at Object.addCardToDashboard (vendor.bundle.js?fd220da862d7458722d7:1)
        at r.onAdd (app-main.bundle.js?fd220da862d7458722d7:5)
        at onChange (app-main.bundle.js?fd220da862d7458722d7:5)
        at S.u.default.createElement.onClick (app-main.bundle.js?fd220da862d7458722d7:5)
        at Object.i (vendor.bundle.js?fd220da862d7458722d7:1)
        at s (vendor.bundle.js?fd220da862d7458722d7:1)
        at Object.executeDispatchesInOrder (vendor.bundle.js?fd220da862d7458722d7:1)
        at h (vendor.bundle.js?fd220da862d7458722d7:1)

**To Reproduce**
1. Go to a dashboard
2. Click the plus sign to add a question to it
3. Click a question name to add it to the dashboard

**Expected behavior**
The question gets added to the dashboard.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

    {
      "browser-info": {
        "language": "en-US",
        "platform": "Linux x86_64",
        "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
        "vendor": "Google Inc."
      },
      "system-info": {
        "java.runtime.name": "OpenJDK Runtime Environment",
        "java.runtime.version": "11.0.4+11",
        "java.vendor": "AdoptOpenJDK",
        "java.vendor.url": "https://adoptopenjdk.net/",
        "java.version": "11.0.4",
        "java.vm.name": "OpenJDK 64-Bit Server VM",
        "java.vm.version": "11.0.4+11",
        "os.name": "Linux",
        "os.version": "4.19.86-coreos",
        "user.language": "en",
        "user.timezone": "GMT"
      },
      "metabase-info": {
        "databases": [
          "h2",
          "mongo",
          "mysql",
          "redshift",
          "postgres",
          "athena"
        ],
        "hosting-env": "unknown",
        "application-database": "mysql",
        "run-mode": "prod",
        "version": {
          "date": "2019-09-20",
          "tag": "v0.33.3",
          "branch": "release-0.33.x",
          "hash": "86d32bf"
        },
        "settings": {
          "report-timezone": null
        }
      }
    }

**Severity**
Practically blocking the usage of dashboards.

**Comment by mazameli** [comment] 2020-01-16 00:53
I'm unable to reproduce this in a quick test on 0.34.1. Is this happening for you on all dashboards? Or only new dashboards or only existing dashboards? If you can back up your app db and try upgrading to the latest version to see if the issue is still there, that would be helpful.

**Comment by bplmp** [comment] 2020-01-16 17:45
@mazameli Yes, on all dashboards, including new ones. I can't upgrade my instance, it's running in production and I don't have the permission to do it. I can ask for it but it might take a while.

We have many dbs and tables plugged into our Metabase instance, and because I can add questions after waiting for a few minutes, I am thinking this is related to something loading in the background.

I've investigated the network tab in my console and found out that this request was still loading in the background: `GET https://metabase.ourdomain.com/api/card?f=all`. It ended up loading 10 mb of data, and once that request was done I could then add the question successfully.

So maybe this is not technically a bug but a problem with the performance of our Metabase instance. Maybe if there was a way to paginate or optimize `GET https://metabase.ourdomain.com/api/card?f=all` the wait time would be reduced, or maybe it would be good to have a loading spinner here.

**Comment by flamber** [comment] 2020-02-04 19:17
Duplicate of #11316
I'm going to close this as a duplicate, which has been given Priority 1 and I know there's work being done on it currently.

**Closed by flamber** 2020-02-04 19:17 UTC
Labels: .Duplicate, Reporting/Dashboards, Type:Bug
