### ISSUE TITLE
MongoDB Delegated Authentication

### ISSUE THREAD

**Issue by iiSeymour** [metabase/metabase#1375] opened 2015-10-27 13:47 UTC
A common setup with MongoDB is to manage all users in the admin database and use delegated authentication when connecting to other databases. For example a typical connection string might be: 

    mongodb://user:pass@mongohost/sales?authSource=admin

Where we want to query the sales database but authenticate against the admin database.

It would be great if metabase supported delegated authentication.

**Comment by tlrobinson** [comment] 2015-10-27 17:57
Duplicate of #1113

**Closed by tlrobinson** 2015-10-27 17:57 UTC
