### ISSUE TITLE
Associated column value not showed 

### ISSUE THREAD

**Issue by Crusader4Christ** [metabase/metabase#9573] opened 2019-03-18 12:59 UTC
- Your browser and the version: Chromium Version 70.0.3538.77 (Official Build) 
- Your operating system:  Ubuntu 16.04 (64-bit)
- Your databases: MySQL
- Metabase version: v0.30.3 Built on 2018-09-13
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

Main table has two FK to one table (`user`).
Every FK column is setted to show the user name. However first column (affiliate) still show only ID: Here is request/response 
```
request - POST api/dataset
body: {"database":2,"type":"query","query":{"source-table":49},"parameters":[]}
response:
{
  "database_id": 2,
  "started_at": "2019-03-18T10:18:06.833Z",
  "json_query": {
    "database": 2,
    "type": "query",
    "query": {
      "source-table": 49
    },
    "parameters": [],
    "constraints": {
      "max-results": 10000,
      "max-results-bare-rows": 2000
    }
  },
  "average_execution_time": null,
  "status": "completed",
  "context": "ad-hoc",
  "row_count": 2000,
  "running_time": 132,
  "data": {
    "columns": ["download_id", "affiliate_id", "brand_id", "name", "name_2"],
    "native_form": {
      "query": "SELECT `download`.`download_id` AS `download_id`, `download`.`affiliate_id` AS `affiliate_id`, `download`.`brand_id` AS `brand_id`, `user__via__affiliate_id`.`name` AS `name`, `user__via__brand_id`.`name` AS `name` FROM `download` LEFT JOIN `user` `user__via__affiliate_id` ON `download`.`affiliate_id` = `user__via__affiliate_id`.`user_id` LEFT JOIN `user` `user__via__brand_id` ON `download`.`brand_id` = `user__via__brand_id`.`user_id` LIMIT 2000",
      "params": null
    },
    "cols": [{
      "description": null,
      "table_id": 49,
      "special_type": "type/PK",
      "name": "download_id",
      "settings": null,
      "source": "fields",
      "parent_id": null,
      "id": 245,
      "visibility_type": "normal",
      "display_name": "Download ID",
      "fingerprint": null,
      "base_type": "type/Integer"
    }, {
      "description": null,
      "table_id": 49,
      "special_type": "type/FK",
      "name": "affiliate_id",
      "settings": null,
      "source": "fields",
      "remapped_to": "name_2",
      "parent_id": null,
      "id": 251,
      "visibility_type": "normal",
      "display_name": "Affiliate",
      "fingerprint": {
        "global": {
          "distinct-count": 33
        }
      },
      "base_type": "type/Integer"
    }, {
      "description": null,
      "table_id": 49,
      "special_type": "type/FK",
      "name": "brand_id",
      "settings": null,
      "source": "fields",
      "remapped_to": "name_2",
      "parent_id": null,
      "id": 225,
      "visibility_type": "normal",
      "display_name": "Brand",
      "fingerprint": {
        "global": {
          "distinct-count": 10
        }
      },
      "base_type": "type/Integer"
    }, {
      "description": null,
      "table_id": 53,
      "special_type": "type/Name",
      "name": "name",
      "settings": null,
      "source": "fields",
      "remapped_from": "brand_id",
      "fk_field_id": 251,
      "parent_id": null,
      "id": 185,
      "visibility_type": "normal",
      "display_name": "Brand ID",
      "fingerprint": {
        "global": {
          "distinct-count": 89
        },
        "type": {
          "type/Text": {
            "percent-json": 0.0,
            "percent-url": 0.0,
            "percent-email": 0.0,
            "average-length": 9.247619047619047
          }
        }
      },
      "base_type": "type/Text"
    }, {
      "description": null,
      "table_id": 53,
      "special_type": "type/Name",
      "name": "name_2",
      "settings": null,
      "source": "fields",
      "remapped_from": "brand_id",
      "fk_field_id": 225,
      "parent_id": null,
      "id": 185,
      "visibility_type": "normal",
      "display_name": "Brand ID",
      "fingerprint": {
        "global": {
          "distinct-count": 89
        },
        "type": {
          "type/Text": {
            "percent-json": 0.0,
            "percent-url": 0.0,
            "percent-email": 0.0,
            "average-length": 9.247619047619047
          }
        }
      },
      "base_type": "type/Text"
    }],
    "results_metadata": {
      "checksum": "jbJPv2gC4ZdEMYGm0xjDru4kpiNS6bzmWZrhu0izpBKYAvjv4noiQAEWYzYjJIge/Ckt4ArjSo15YefDMjp7LmqW9OxEpWKhnXp9O1U5/PI=",
      "columns": [{
        "name": "download_id",
        "display_name": "Download ID",
        "base_type": "type/Integer",
        "special_type": "type/PK",
        "fingerprint": null
      }, {
        "name": "affiliate_id",
        "display_name": "Affiliate",
        "base_type": "type/Integer",
        "special_type": "type/FK",
        "fingerprint": {
          "global": {
            "distinct-count": 33
          }
        }
      }, {
        "name": "brand_id",
        "display_name": "Brand",
        "base_type": "type/Integer",
        "special_type": "type/FK",
        "fingerprint": {
          "global": {
            "distinct-count": 10
          }
        }
      }, {
        "name": "name",
        "display_name": "Name",
        "base_type": "type/Text",
        "special_type": "type/Name",
        "fingerprint": {
          "global": {
            "distinct-count": 89
          },
          "type": {
            "type/Text": {
              "percent-json": 0.0,
              "percent-url": 0.0,
              "percent-email": 0.0,
              "average-length": 9.247619047619047
            }
          }
        }
      }, {
        "name": "name_2",
        "display_name": "Name",
        "base_type": "type/Text",
        "special_type": "type/Name",
        "fingerprint": {
          "global": {
            "distinct-count": 89
          },
          "type": {
            "type/Text": {
              "percent-json": 0.0,
              "percent-url": 0.0,
              "percent-email": 0.0,
              "average-length": 9.247619047619047
            }
          }
        }
      }]
    },
    "insights": null,
    "rows_truncated": 2000
  }
}
```

**Comment by flamber** [comment] 2019-03-18 14:21
Hi @Crusader4Christ 
Sounds like a duplicate of #9236

**Comment by salsakran** [comment] 2019-04-10 04:11
closing as a dupe

**Closed by salsakran** 2019-04-10 04:11 UTC
