### ISSUE TITLE
Date colums are treated as datetime

### ISSUE THREAD

**Issue by WhyNotHugo** [metabase/metabase#12784] opened 2020-06-26 00:09 UTC
**Describe the bug**

I've a few column of type `date` (not `datetime`), and the CSV for reports on them are of type datetime, e.g.: `2020-06-01T00:00:00-03:00`.

**Logs**

```
Column type:
      Column       |     Type      | Collation | Nullable |                 Default                  | Storage | Stats target | Description
-------------------+---------------+-----------+----------+------------------------------------------+---------+--------------+-------------
 issued_date       | date          |           | not null |                                          | plain   |              |
```

**To Reproduce**
1. Create a table with a column of type `date`.
2. `select mydate from mytable;`
3. Export a CSV

(Note: for in-dashboard tables this can be overridden, [but not for exports](https://www.metabase.com/docs/latest/api-documentation.html#post-apicardcard-idqueryexport-format)).

**Expected behaviour**

The data in the CSV should match the one in the source database.

**Actual behaviour**

A time is added to the dates.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your databases: Postgres
- Metabase version: Metabase 0.35.4
- Metabase internal database: also Postgres

**Severity**
It's mostly annoying. ~~It also requires custom scripts to be written for every CSV report with a date in it.~~ Can be worked around with `TO_CHAR(afip_receipt.issued_date :: DATE, 'yyyy-mm-dd')`. Upside is that it's also an easy way to get a human-readable date (e.g.: ISO-8601).

Leaving it as is causes confusion ("Hey, what does this time mean on the per-day billing report?")

**Comment by flamber** [comment] 2020-06-26 08:27
Duplicate of #5859 and/or #10879 - related to #10803

**Closed by flamber** 2020-06-26 08:27 UTC
Labels: .Needs Triage, Type:Bug

**Comment by WhyNotHugo** [comment] 2020-06-26 09:18
It is, thanks!

We used such different keywords I'd didn't come up in my search. 😅
