### ISSUE TITLE
type/BigInteger lost precision on frontend

### ISSUE THREAD

**Issue by xu20160924** [metabase/metabase#15142] opened 2021-03-12 08:59 UTC
**Describe the bug**
There has ‘BIGINT’ of the field in my table when I look at the data of my table. The number of BigInteger will be lost precision. And I have seen the response of data, it's ok at the response tab in debug mode, and if I see it at preview tab that will be lost precision same to shown at query result. I have tried this at master and tag/v1.38.1, BigInteger both didn't work. So anyone has noted this problem？
**Logs**

**To Reproduce**
1. create a table that contains a field which type is BigInteger and add it to MetaBase.
2. Just check the data of the created table.

**Expected behavior**
Correct number

**Screenshots**
![image](https://user-images.githubusercontent.com/22407827/110916135-71d15300-8353-11eb-8620-6d939cdc03b9.png)
![image](https://user-images.githubusercontent.com/22407827/110916305-9d543d80-8353-11eb-96af-42aba8891444.png)
![image](https://user-images.githubusercontent.com/22407827/110916348-a93fff80-8353-11eb-8de5-a124f60c2b45.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome
- Your operating system: OS X
- Your databases: MySQL
- Metabase version: master、tag/v1.38.1
- Metabase hosting environment: 
- Metabase internal database: MySQL
**Severity**

**Additional context**

**Comment by flamber** [comment] 2021-03-12 09:55
Duplicate of #5816

**Closed by flamber** 2021-03-12 09:55 UTC
Labels: .Needs Triage, Type:Bug
