### ISSUE TITLE
"Is not" filter breaking BigQuery on second+ joined tables in v0.37.0-rc3

### ISSUE THREAD

**Issue by grkhr** [metabase/metabase#13569] opened 2020-10-22 11:15 UTC
**Describe the bug**
Looks like something wrong with generated SQL query in **v0.37.0-rc3**. When I join second table and want to use category filter `is not` on second table, I see `Unrecognized name" error`. On last version **v0.36.7** it was fine. 

When I tried to debug generated SQL, I found that it generate `OR IS NULL` statement that doesn't use table alias.

Generated query:
```
SELECT count(*) AS `count`
FROM `analytics.meals`
LEFT JOIN `analytics.meals_available` `meals_available` ON `analytics.meals`.`id` = `meals_available`.`id`
WHERE (`meals_available`.`placeRef` <> 'kmn'
    OR `analytics.meals_available`.`placeRef` IS NULL) -- here the bug
```

Should be (without `analytics` in last statement, works fine):
```
SELECT count(*) AS `count`
FROM `analytics.meals`
LEFT JOIN `analytics.meals_available` `meals_available` ON `analytics.meals`.`id` = `meals_available`.`id`
WHERE (`meals_available`.`placeRef` <> 'kmn'
    OR `meals_available`.`placeRef` IS NULL) -- here the fix
```

**To Reproduce**
1. Go to custom question
2. Choose table
3. Join second
4. Try to filter category filter on second table with "Is not" option
5. See error `Unrecognized name: `analytics.meals_available` at [2:1212]`

**Expected behavior**
It should work ;)

**Screenshots**
![image](https://user-images.githubusercontent.com/40689054/96863828-2552ad00-1470-11eb-930e-7548d1638572.png)
![image](https://user-images.githubusercontent.com/40689054/96863850-2d125180-1470-11eb-946c-c8ac465e3cd5.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_252-8u252-b09-1~deb9u1-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_252",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.252-b09",
    "os.name": "Linux",
    "os.version": "4.19.112+",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "bigquery",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.9"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.37.0-rc3",
      "date": "2020-10-19",
      "branch": "new-release-build-script",
      "hash": "51209f3"
    },
    "settings": {
      "report-timezone": "Europe/Moscow"
    }
  }
}
```
**Severity**
Really annoying. This broke a lot of question and blocks businness-users job.

**Comment by flamber** [comment] 2020-10-22 14:01
Duplicate of #13534
You should really not use a release candidate in production.

**Closed by flamber** 2020-10-22 14:01 UTC
Labels: .Needs Triage, Type:Bug
