### ISSUE TITLE
Alerts email delivery toggle not working correctly

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6571] opened 2017-12-12 23:25 UTC
Toggling off the email delivery setting doesn't seem to be doing anything. The only way to prevent email delivery seems to be to manually remove all recipients. 

![alert-email-settings](https://user-images.githubusercontent.com/2223916/33913897-8ad757c8-df50-11e7-87d4-83fbb753cca5.gif)

**Comment by salsakran** [comment] 2017-12-13 01:01
does it still send the email? I.e. is this a presentational or behavioral bug?

**Comment by mazameli** [comment] 2017-12-13 01:05
I’ll have to check if the alert email still sends, but if you remove recipients later it still sends them “you’ve been unsubscribed” notification emails.

**Comment by mazameli** [comment] 2017-12-13 03:40
@salsakran I just confirmed that, yes, the emails are still sending.

**Comment by senior** [comment] 2018-01-09 19:06
It looks like the data isn't getting updated properly before being PUT to the backend. If you click the email slider, then click the save button, it still includes the recipients in the alert data that is posted.

@mazameli Should the recipients be cleared when selecting the email slider? I'm specifically thinking about someone clicking it twice (before hitting save). Would you expect the recipients to still be there?

**Comment by mazameli** [comment] 2018-01-09 19:10
Yes, I'd expect the recipients to still be there, at least until I'd saved changes. I.e., if I turn the email slider off and the save changes, and then at some later point I open up the settings again and turn email back _on_, I don't think I'd expect to see the recipients that were previously there.

**Comment by senior** [comment] 2018-01-09 19:45
Ok, I know what the issue is. @tlrobinson or @attekei: do one of you have some time to help talk me through a fix for this?

**Closed** 2018-01-11 16:48 UTC
Labels: Alerts, Bug, Priority/P2
