### ISSUE TITLE
Not able to connect to google analytics using the instructions in the UI

### ISSUE THREAD

**Issue by jhackett1** [metabase/metabase#14928] opened 2021-02-22 18:09 UTC
Hello,

I'm trying to connect my metabase app to google analytics, but I am failing at the auth code step, because Google doesn't think my oauth client is the right kind for the redirect URI metabase is giving.

The instructions say to use an "other" client but this isn't an option any more - experimenting found that "TVs and limited input devices" did the trick.

I also kept losing what I'd typed since when I clicked to generate an auth code, I had to hit the back button in my browser to get back to the metabase form.

**I think the fix here is just having the "click here" links open in new tabs and updating old references to "other".**

**Describe the bug**
I can't connect to google analytics following the oauth client id instructions in the UI. I have to experiment and manually open things in new tabs to succeed.

**Expected behavior**
I can authenticate through google and grant access to google analytics.

**Comment by flamber** [comment] 2021-02-22 19:45
Yeah, Google made a change and it was difficult to figure out if it was permanent, since they were A/B testing, but it seems like they're sticking to it now.
Duplicate of #12491

**Closed by flamber** 2021-02-22 19:45 UTC
Labels: .Needs Triage, Type:Bug
