### ISSUE TITLE
Trying to filter on a custom string column incorrectly shows numeric operators

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#15637] opened 2021-04-15 18:39 UTC
This is on `release-x.39.x`

## Here's a custom string column I've added via concat
<img width="1180" alt="Screen Shot 2021-04-15 at 11 14 58 AM" src="https://user-images.githubusercontent.com/2223916/114920483-576d1800-9dde-11eb-811f-6ba28d62589d.png">

## When I try to filter on the custom column, it gives me numeric operators instead of string operators as expected
<img width="1153" alt="Screen Shot 2021-04-15 at 11 15 29 AM" src="https://user-images.githubusercontent.com/2223916/114920476-54722780-9dde-11eb-846d-a941409826f8.png">

**Comment by ariya** [comment] 2021-04-15 19:05
Likely related to #13122 (due to the [hard-coded numeric type](https://github.com/metabase/metabase/issues/13122#issuecomment-779441374)).

**Comment by flamber** [comment] 2021-04-15 20:04
Duplicate of #13217 (which is likely a dupe of #13122)

**Closed by flamber** 2021-04-15 20:04 UTC
Labels: Priority:P2, Querying/Notebook, Type:Bug
