### ISSUE TITLE
Tables too dim to read in fullscreen mode

### ISSUE THREAD

**Issue by TheSeanBrady** [metabase/metabase#4875] opened 2017-04-26 20:37 UTC
### Bug
Fullscreen mode tables are "dimmed" out, too dim to read unless sized small enough initially. In other words, if I have a table that is long, more than 24 rows, fullscreen mode displays it too dimly to see. If I resize the box to make it much smaller, it displays in fullscreen properly, although it truncates the bottom of the table. Note that this is on a 27" Apple Cinema Display.

- Your browser and the version: Safari 10.0.1, Chrome 57.0.2987.133
- Your operating system: Mac 10.12.1
- Your databases: Postgres and MSSQL
- Metabase version: 0.23.1 
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

- *Repeatable steps to reproduce the issue*
1. Create a dashboard with a table in it
2. Extended it downward to fit, beyond 24 rows.
3. Put metabase in fullscreen mode

**Comment by mazameli** [comment] 2017-04-26 20:51
I was able to reproduce this.

![screen shot 2017-04-26 at 1 50 42 pm](https://cloud.githubusercontent.com/assets/2223916/25456325/6a77e390-2a87-11e7-8ee1-6fd7860be1a8.png)

**Comment by kdoh** [comment] 2017-04-26 20:52
I think this is due to the below the fold logic that dims an item that isn't fully in the viewport.

**Comment by mazameli** [comment] 2017-04-26 20:54
Ah, I forgot about that, or I thought we had decided to rip it out. I still really don't like that behavior, but I think @tlrobinson was an advocate?

**Comment by mazameli** [comment] 2017-04-26 20:56
Actually, is this really a dupe of https://github.com/metabase/metabase/issues/2258?

**Closed** 2017-04-26 20:58 UTC
Labels: CSS, Dashboards, Duplicate, UX
