### ISSUE TITLE
"You do not have permissions to run this query." Error for SQL-Questions for non-SQL users.

### ISSUE THREAD

**Issue by carstenkadmos** [metabase/metabase#33041] opened 2023-08-09 12:09 UTC
### Describe the bug

The general scenario of the bug is the following:

1. User 1 (User with SQL rights) creates a SQL question and saves it in a collection that can be viewed by every user.
2. User 2 (No-SQL rights) builds a question and joins this SQL question to any other data and then wants to run the query. The user get the error: "You do not have permissions to run this query." 

It really is confusing because it works if you take the SQL question and left join any other table. It does not if you take any other data and left join the SQL question.

### To Reproduce

1. As a User with SQL privileges, go to new SQL question and create a SQL query. For simplicity I reproduced it with this:
```
SELECT 
    id,
    country,
    customer_name
FROM 
datamart.users
limit 100
```
2. Save this query in a folder that can be viewed by a non-SQL user.
3. As the Self-Service or non-SQL User create a question based on any data and then use the SQL questions created before as a join.
4. Click visualize and try to run the query.
5. See error

### Expected behavior

User 2 should be able to use the SQL question as a basis for anything

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "ANSI_X3.4-1968",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10-post-Debian-1deb10u1",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10-post-Debian-1deb10u1",
    "os.name": "Linux",
    "os.version": "5.15.107+",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-07-28",
      "tag": "v0.46.6.4",
      "branch": "release-x.46.6.x",
      "hash": "7c60aca"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

High. A lot of work has been already put in to circumvent this issue and it is quite unpredictable. It basically makes a lot of SQL questions unusable for any non-SQL user.

### Additional context

If you need any other information, let me know. This bug is really eating up a lot of my time, which is why invested so much time to reproduce it.

**Comment by paoliniluis** [comment] 2023-08-09 14:33
99% probably it's a duplicate of https://github.com/metabase/metabase/issues/30077, can you confirm?

**Closed by paoliniluis** 2023-08-09 14:33 UTC
Labels: Type:Bug, .Needs Triage

**Comment by carstenkadmos** [comment] 2023-08-09 15:33
@paoliniluis it looks like they are related but #30077 looks like an oddly specific variation of the problem. This is blocking me on a daily basis with users not being able to query things.
