### ISSUE TITLE
上传csv文件报错

### ISSUE THREAD

**Issue by Memory5210** [metabase/metabase#40831] opened 2024-04-01 01:24 UTC
在执行写入查询时出错。(conn=4749) Identifier name '%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD_%EF%BF%BD%EF%BF%BD%C5%80' is too long

**Comment by paoliniluis** [comment] 2024-04-01 09:55
Change the name of the CSV file to something shorter and try again. I think this is due to the encodings. Can you share the name of your CSV file?

**Comment by Memory5210** [comment] 2024-04-02 00:56
> Change the name of the CSV file to something shorter and try again. I think this is due to the encodings. Can you share the name of your CSV file?

The file names are ces.csv and ce.csv, just for testing functionality.I also think it's a encoding issue, but I don't know where to set it up.

**Comment by Memory5210** [comment] 2024-04-02 00:59
The downloaded CSV file in Chinese is also garbled due to the encoding format, but I don't know how to modify its default settings

**Comment by paoliniluis** [comment] 2024-09-06 15:37
duplicate of https://github.com/metabase/metabase/issues/45689

**Closed by paoliniluis** 2024-09-06 15:37 UTC
Labels: Priority:P2, Visualization/Download, .Team/BackendComponents, Organization/Uploads
