### ISSUE TITLE
Request: Ability for alerts to check more granular than hourly

### ISSUE THREAD

**Issue by k2xl** [metabase/metabase#7072] opened 2018-03-05 15:12 UTC
Currently the minimum interval in metabase for Pulse or alerts is hourly. Would be great if we could have it run more often.

Perhaps:

Every minute
Every 10 minutes
Every 30 minutes

**Comment by mazameli** [comment] 2018-03-05 20:32
Closing as a duplicate of https://github.com/metabase/metabase/issues/3846

**Closed by mazameli** 2018-03-05 20:32 UTC
Labels: Duplicate
