### ISSUE TITLE
Click on the "Limit Access" button in permission page didn't redirect me to the table page.

### ISSUE THREAD

**Issue by bryanyang0528** [metabase/metabase#12333] opened 2020-04-16 09:55 UTC
**Describe the bug**
I would like to change the permission of a group from "no access" to "limit access" status. When I click on the 'Limit access' button, it does not redirect me to the "table page" but an invalid Url like `https://mydomain/admin/permissions/databases/10/schemas/null/tables` 

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to 'admin page'
2. Click on the 'Permission' tab
3. Click on a "No access" button
4. Click on a "Limit access"

**Expected behavior**
This action should redirect me to the table page of this data source. But nothing happened.

**Screenshots**
<img width="248" alt="Screen Shot 2020-04-16 at 17 41 22" src="https://user-images.githubusercontent.com/5171607/79442154-c0bf1d00-800a-11ea-9af6-3e3b50cf1016.png">
<img width="526" alt="Screen Shot 2020-04-16 at 17 41 33" src="https://user-images.githubusercontent.com/5171607/79442163-c3ba0d80-800a-11ea-9597-07b9f0cb245d.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Version 80.0.3987.163 (Official Build) (64-bit)
- Your operating system: OS X 10.14.6
- Your databases: AWS Aurora serverless (MySQL 5.6)
- Metabase version: 0.35.2
- Metabase hosting environment: Docker on k8s
- Metabase internal database: AWS Aurora serverless (MySQL 5.6)

**Severity**
I cannot control the access permission on a single or part table in a data source. 

**Additional context**

**Comment by flamber** [comment] 2020-04-16 09:57
Duplicate of #12269

**Closed by flamber** 2020-04-16 09:57 UTC
Labels: .Needs Triage, Type:Bug
