### ISSUE TITLE
"No results" when setting config in Postgres

### ISSUE THREAD

**Issue by mausch** [metabase/metabase#15052] opened 2021-03-03 18:04 UTC
**Describe the bug**
When I add a `SET` statement to my query Metabase claims there are no results.
e.g.
```
set local max_parallel_workers_per_gather = 8;
select * from companies.canonical_companies limit 10;
```

Other clients e.g. DBeaver have no issues with this and return results as expected.

**Logs**

Server log:

```
03-03 17:52:57 ERROR sql-jdbc.execute :: nil
03-03 17:52:57 WARN middleware.process-userland-query :: Query failure {:status :failed,
 :class org.postgresql.util.PSQLException,
 :error "No results were returned by the query.",
 :stacktrace
 ("org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:109)"
  "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)"
  "clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1072)"
  "clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1066)"
  "clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1081)"
  "clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)"
  "clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)"
  "clojure.java.jdbc$query.invoke(jdbc.clj:1126)"
  "--> driver.sql_jdbc.execute$cancelable_run_query.invokeStatic(execute.clj:209)"
  "driver.sql_jdbc.execute$cancelable_run_query.invoke(execute.clj:198)"
  "driver.sql_jdbc.execute$run_query.invokeStatic(execute.clj:223)"
  "driver.sql_jdbc.execute$run_query.invoke(execute.clj:219)"
  "driver.sql_jdbc.execute$do_with_auto_commit_disabled.invokeStatic(execute.clj:272)"
  "driver.sql_jdbc.execute$do_with_auto_commit_disabled.invoke(execute.clj:260)"
  "driver.sql_jdbc.execute$do_in_transaction$fn__69387.invoke(execute.clj:277)"
  "driver.sql_jdbc.execute$do_in_transaction.invokeStatic(execute.clj:276)"
  "driver.sql_jdbc.execute$do_in_transaction.invoke(execute.clj:275)"
  "driver.sql_jdbc.execute$run_query_without_timezone.invokeStatic(execute.clj:300)"
  "driver.sql_jdbc.execute$run_query_without_timezone.invoke(execute.clj:299)"
  "driver.sql_jdbc.execute$execute_query$fn__69410.invoke(execute.clj:338)"
  "driver.sql_jdbc.execute$do_with_try_catch.invokeStatic(execute.clj:252)"
  "driver.sql_jdbc.execute$do_with_try_catch.invoke(execute.clj:246)"
  "driver.sql_jdbc.execute$execute_query.invokeStatic(execute.clj:332)"
  "driver.sql_jdbc.execute$execute_query.invoke(execute.clj:325)"
  "driver.sql_jdbc$fn__71316.invokeStatic(sql_jdbc.clj:49)"
  "driver.sql_jdbc$fn__71316.invoke(sql_jdbc.clj:47)"
  "query_processor$fn__46335$execute_query__46340$fn__46341.invoke(query_processor.clj:69)"
  "query_processor$fn__46335$execute_query__46340.invoke(query_processor.clj:64)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__37455.invoke(mbql_to_native.clj:40)"
  "query_processor.middleware.annotate$result_rows_maps__GT_vectors$fn__40562.invoke(annotate.clj:541)"
  "query_processor.middleware.annotate$add_column_info$fn__40468.invoke(annotate.clj:485)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__41503.invoke(cumulative_aggregations.clj:57)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__43430.invoke(resolve_joins.clj:184)"
  "query_processor.middleware.limit$limit$fn__42138.invoke(limit.clj:19)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__46195.invoke(results_metadata.clj:87)"
  "query_processor.middleware.format_rows$format_rows$fn__42126.invoke(format_rows.clj:76)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__38215.invoke(add_dimension_projections.clj:232)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__38866.invoke(add_source_metadata.clj:107)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__43480.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__38703.invoke(add_row_count_and_status.clj:16)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__41578.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__43094.invoke(resolve_driver.clj:22)"
  "query_processor.middleware.store$initialize_store$fn__46220$fn__46221.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__46220.invoke(store.clj:10)"
  "query_processor.middleware.async$async__GT_sync$fn__37366.invoke(async.clj:23)"
  "query_processor.middleware.async_wait$runnable$fn__40619.invoke(async_wait.clj:89)"),
 :query
 {:type "native",
  :native {:query "set local max_parallel_workers_per_gather = 8;\nselect * from companies.canonical_companies limit 10;", :template-tags {}},
  :parameters [],
  :async? true,
  :middleware {:add-default-userland-constraints? true, :userland-query? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :card-id nil,
   :nested? false,
   :query-hash [45, -27, -7, 74, 34, -75, 125, 122, 38, -37, 109, 76, -27, 101, -75, 5, 71, -19, 99, -69, 30, 126, 31, -32, -126, 107, 60, 48, 22, 79, 50, -115]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}}}
```

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.9.0-9-amd64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-02-25",
      "tag": "v0.34.3",
      "branch": "release-0.34.x",
      "hash": "1a83edb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
This issue means some of my queries cannot run on Metabase because they require specific settings to help the Postgres query planner. Otherwise the query times out.

**Comment by flamber** [comment] 2021-03-03 18:12
Hi @mausch Sounds like a duplicate of #4050 - by the way, latest release is 0.38.0.1

**Closed by flamber** 2021-03-03 18:12 UTC
Labels: .Needs Triage, Type:Bug
