### ISSUE TITLE
pivot table - missing row

### ISSUE THREAD

**Issue by dfx413** [metabase/metabase#16666] opened 2021-06-18 08:15 UTC
Metabase version: 89d1b96 docker

Hi,
when displaying data in Pivot table it sometimes happens that there is a missing row in the results. 
totals for  2021-06-22 = 3 but only 2 rows are displayed (see below):
![Snímek obrazovky 2021-06-18 v 10 10 36](https://user-images.githubusercontent.com/1764151/122529497-d8829e80-d01d-11eb-95b7-7baaf4a205c3.png)

Here is the same data displayed using a standard table component:
![Snímek obrazovky 2021-06-18 v 10 10 09](https://user-images.githubusercontent.com/1764151/122529708-0e278780-d01e-11eb-8f30-c57b9589a89e.png)

**Comment by flamber** [comment] 2021-06-18 08:25
@dfx413 You need to provide all the details, when opening a bug and a way to reproduce.

**Comment by dfx413** [comment] 2021-06-18 18:32
@flamber 
Hi, sorry, I forgot to add Metabase version. 
I have looked into the data returned by the API and the relevant row is there. It just does not get rendered.
Then I found out that when I toggle "show totals" for the column "jméno" the row suddenly reappears.
See below:

![Kapture 2021-06-18 at 20 31 35](https://user-images.githubusercontent.com/1764151/122603219-5376a400-d074-11eb-9b15-245de6a6b2a7.gif)

**Comment by flamber** [comment] 2021-06-18 18:46
@dfx413 You are not providing much information.
1. Post "Diagnostic Info" from Admin > Troubleshooting
2. Is this a new problem? If yes, since which version?
3. Can you provide a way to reproduce? Either with Sample Dataset or SQL examples.

**Comment by dfx413** [comment] 2021-06-22 06:01
@flamber 
Hi, 
sorry, posting more info:

1)
```
{
  "browser-info": {
    "language": "cs-CZ",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "5.8.0-33-generic",
    "user.language": "en",
    "user.timezone": "Europe/Prague"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.7 (Ubuntu 11.7-0ubuntu0.19.10.1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-06-16",
      "tag": "v0.40.0-SNAPSHOT",
      "branch": "master",
      "hash": "89d1b96"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

I am using MSSQL 

2) I don't really know but I have noticed it in version `89d1b96` and it persists in `b92ad6c`


3) I have tried to extract the relevant data into a separate table to send you, but I am not able to replicate with the derived dataset. I have found a temporary way around the problem, will contact you when I stumble upon another instance of it.
Thanks.

**Comment by flamber** [comment] 2021-06-22 09:05
@dfx413 
Okay, please try latest release 0.39.4.
And if you cannot reproduce with any other table or database, then it seems like it must be something specific to that question or table/columns. You would have to check the API responses.
But how are we going to fix something if there's no way of reproducing the problem?

**Comment by flamber** [comment] 2021-06-29 15:58
Closing this, since I have no way of reproducing and not enough details to understand the problem, and don't know if the problem has occurred while several versions of `master`

**Closed by flamber** 2021-06-29 15:58 UTC
Labels: .Needs Triage, Type:Bug
