### ISSUE TITLE
When you do drill through on a question created from a model, the drill through does not respect the column order of the model

### ISSUE THREAD

**Issue by cbalusek** [metabase/metabase#48015] opened 2024-09-18 22:35 UTC
### Describe the bug

When you create a question from a model and drill through on that question, the detail view does not show the correct column order of the model.  It will hide any hidden columns, but it does not respect column order.

### To Reproduce

1. Create a model
2. Rearrange the columns
3. Create a question from the model with segments
4. Drill into a segment
5. See how the column order is different

Or see:  https://stats.metabase.com/question/19772-question-to-drill-in-and-see-how-the-model-column-order-isnt-respected

### Expected behavior

If I create a question from a model and drill through, the drill through should show the detail records as designed in the model.   It does this currently for some behavior (hidden columns) but not the column order

### Information about your Metabase installation

```JSON
Tested on:
Build from 2024-09-18
1.48.8
1.50.25.2
v1.49.8
```

### Severity

It's disappointing.  I would have sworn this worked, which is why I tested it on so many versions.  It also is a reason not to use Models.

### Additional context

Reported by a customer

**Comment by ranquild** [comment] 2024-09-18 23:08
The order of the columns in models is currently implemented (incorrectly) as a viz setting. It doesn't affect anything outside of the model query itself.

**Comment by TanTan412** [comment] 2024-09-23 19:54
is this in the works in the future?

**Comment by paoliniluis** [comment] 2024-10-09 13:19
@TanTan412 yes

**Comment by ranquild** [comment] 2024-10-21 14:53
Duplicate of https://github.com/metabase/metabase/issues/38523

**Closed by ranquild** 2024-10-21 14:53 UTC
Labels: Type:Bug, Priority:P2, Difficulty:Hard, .Frontend, Querying/Models, .Team/Querying
