### ISSUE TITLE
charts are not rendered when there is a series with null values

### ISSUE THREAD

**Issue by SrancsikAtBitrise** [metabase/metabase#10840] opened 2019-09-09 10:06 UTC
**Describe the bug**
Bar charts are not rendered when one of the series includes only nulls.

**To Reproduce**
Query any data where one of the series contain only nulls. Table view is populated, Line chart is okay but bar chart is not rendered.

**Expected behavior**
Bar charts are rendered without the series which is null.

**Information about your Metabase Installation:**
- Your browser and the version: 76.0.3809.132 (Official Build) (64-bit)
- Your operating system: OS X 10.14.6 (18G87)
- Your databases: PostgreSQL
- Metabase version: 0.33.2
- Metabase hosting environment: Heroku
- Metabase internal database: PostgreSQL

**Severity**
Users cannot see existing reports. They can, however, switch to table view but it is not trivial that the data is actually there.

**Comment by paulrosenzweig** [comment] 2019-09-09 20:56
@SrancsikAtBitrise I want to confirm that I can reproduce exactly what you're seeing.

As an example, take this simple dataset without any nulls. 

![image](https://user-images.githubusercontent.com/691495/64565478-d73d2180-d321-11e9-9312-516869c95e6f.png)

Here's what it looks like if series `c` contains only nulls for `y`. That looks like what I'd expect.

![image](https://user-images.githubusercontent.com/691495/64565603-1cf9ea00-d322-11e9-84d1-d4584b2abe4d.png)

Here's the graph with only nulls for `x` in series `c`. This is broken, but should be fixed by another pending PR, so I want to make sure you're not seeing something else.

![image](https://user-images.githubusercontent.com/691495/64565782-84b03500-d322-11e9-8949-da46e83b1546.png)

**Comment by SrancsikAtBitrise** [comment] 2019-09-10 10:49
It looks different here but yes, it is broken.

![Screenshot 2019-09-09 at 11 56 59](https://user-images.githubusercontent.com/39155393/64607663-3ace5a00-d3c9-11e9-90a9-cf595aa1416d.png)

where data table looks like this:
![Screenshot 2019-09-09 at 11 56 49](https://user-images.githubusercontent.com/39155393/64607673-40c43b00-d3c9-11e9-94ea-2952a3a5107b.png)

**Comment by paulrosenzweig** [comment] 2019-09-10 19:42
@SrancsikAtBitrise, I think I was able to reproduce the issue with your data, but I don't think it is related to the nulls. If I'm seeing the same bug, the issue is that you have two columns that could be used on the x axis and three that could be used on the y. In that scenario we fail to pick default columns for you, but you should be able to select them yourself in the visualization settings.

I just opened a PR to fix that issue, but let me know if you think you're seeing something else and the nulls are part of the problem.

**Comment by SrancsikAtBitrise** [comment] 2019-09-11 09:43
I must say this is two different issues. I experienced the issue of picking no columns for X and Y when changing the chart type.

But my issue is rendering no chart at all: the chart which is not rendered used to work before updating to 0.33.1 and then 0.33.2.

This is the same chart with updated data. Now there are records under `aborted` thus the chart is back to normal. Mapping of columns to X and Y never changed.

![Screenshot 2019-09-11 at 11 30 42](https://user-images.githubusercontent.com/39155393/64685917-14232880-d488-11e9-89ab-713fe1b181b5.png)

**Comment by SrancsikAtBitrise** [comment] 2019-09-11 10:17
Finally, I caught it. So, @paulrosenzweig both of us are right.
**The mapping is not correct when one of the series contains only nulls.**

This chart presents the latest state of data (let's disregard our old friend, the mismatch between the date on X-axis and the tooltip).
![Screenshot 2019-09-11 at 11 30 31](https://user-images.githubusercontent.com/39155393/64688744-48e5ae80-d48d-11e9-930c-07223431e0f2.png)

Dating back to a period where `aborted` is missing, the chart is not rendered because mapping is missing:
![Screenshot 2019-09-11 at 12 12 34](https://user-images.githubusercontent.com/39155393/64689128-04a6de00-d48e-11e9-9dc0-170459334e80.png)

**Comment by paulrosenzweig** [comment] 2019-09-11 19:54
@SrancsikAtBitrise ah that makes sense! When the column only contains nulls we lose type information and can't decide whether this column should be on the x or y axis. When we make the wrong choice and try to put `aborted` on the x axis, we hit the bug that #10858 addresses. 

I just looked into adding a special case around columns that only have nulls to avoid slotting them into the x axis. It would be straightforward, but I worry that it introduces a new issue for columns that *should* be on the x axis. For now I think it makes sense to leave out that special case.

**Comment by paulrosenzweig** [comment] 2019-09-13 15:20
The code that has issues with too many columns on the x axis looks like it was new as of v0.33.0. Without that issue the nulls shouldn't break anything.

Makes sense that this affects all charts since that x/y splitting code. I just updated the title to reflect that.

**Comment by alxnddr** [comment] 2021-06-16 20:12
It looks like we fixed it with https://github.com/metabase/metabase/pull/15554
@flamber could you please take a look?

**Comment by flamber** [comment] 2021-06-17 12:06
@alxnddr I cannot reproduce on 0.39.4, but I also cannot figure out how to reproduce and there's at least three other problems in the comments, which are handled in other issues, so closing this.

**Closed by flamber** 2021-06-17 12:06 UTC
Labels: Priority:P2, Type:Bug, Visualization/Chart Settings
