### ISSUE TITLE
Combing charts not showing all questions

### ISSUE THREAD

**Issue by JBrame** [metabase/metabase#8519] opened 2018-09-14 09:38 UTC
When trying to combine questions into the same chart I'm not able to find all the questions.
![image](https://user-images.githubusercontent.com/6168847/45542588-431da480-b80a-11e8-83ce-6b8ad7a807af.png)
![image](https://user-images.githubusercontent.com/6168847/45542608-4fa1fd00-b80a-11e8-8e30-a6f65d8e91c6.png)
---
- Chrome Version 69.0.3497.92 (Official Build) (64-bit)
- Windows 10
- MySQL
- Metabase version: 03.03
- Jar
- Metabase internal database: H2 (default)

**Comment by flamber** [comment] 2021-11-11 15:17
Duplicate of #4201

**Closed by flamber** 2021-11-11 15:17 UTC
Labels: Type:Bug, Priority:P3, Reporting/Dashboards
