### ISSUE TITLE
Invalid Axle label translation of graph/visualisation

### ISSUE THREAD

**Issue by DustHoff** [metabase/metabase#13226] opened 2020-09-10 07:17 UTC
**Describe the bug**
Visualizations of data are not fully translated which results in a inconsistency of the UI translation.

**Logs**
No logs required as it is a normal startup without plugins.

**To Reproduce**
1. Go to 'start the initial installation and select as language german.'
2. Click on 'select "Ein blick auf die Orders Tabelle'
3. Scroll down to graph 'Verkäufe nach Quelle'
4. the axle labels are in English (January) but with mouse hover a datapoint the month is translated to "Januar"

**Expected behavior**
Axel and datapoint should use the same translation

**Screenshots**
![image](https://user-images.githubusercontent.com/14981295/92692406-666d8280-f344-11ea-86d7-0115aeac56e3.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

{
  "browser-info": {
    "language": "de-DE",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "ANSI_X3.4-1968",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.2+9",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "11.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.2+9",
    "os.name": "Linux",
    "os.version": "4.19.76-linuxkit",
    "user.language": "de_DE",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-08-17",
      "tag": "v0.36.4",
      "branch": "release-0.36.x",
      "hash": "196c1f6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
This issue is not blocking us fully to use Metabase

**Comment by flamber** [comment] 2020-09-10 09:25
Duplicate of #11319

**Closed by flamber** 2020-09-10 09:25 UTC
Labels: .Needs Triage, Type:Bug
