### ISSUE TITLE
Request: Enable Metabase Update within Settings

### ISSUE THREAD

**Issue by naxIO** [metabase/metabase#5111] opened 2017-05-15 17:25 UTC
Would be neat to have an "Update" button in the Metabase settings which actually update/upgrades Metabase to the latest or newest Version (replacing the jar etc under the hood.)

**Comment by tlrobinson** [comment] 2017-05-15 17:34
Duplicate of #711

This would be awesome, it's just difficult to do in certain environments, in particular filesystems without persistence. But maybe it's ok to just download the jar on every boot? Or only support it on persistent filesystems?

**Comment by naxIO** [comment] 2017-05-15 17:53
Well, if it works for 90% of the installations in a persistent environment that would already be cool. It has a lot of things to consider obviously (permissions etc). 

I think the most awesome but also most difficult way would be to update the content within the hull (jar) but not the entire jar itself. This way this issue could be addressed .

**Closed** 2017-05-15 18:14 UTC
