### ISSUE TITLE
Error getting setting table.pivot_column TypeError: Cannot read property 'cols' of undefined

### ISSUE THREAD

**Issue by OptimusOS** [metabase/metabase#12838] opened 2020-07-03 12:42 UTC
**Describe the bug**

The query in the preview version does not work
when I publish it.

**Logs**
`[84fad6bc-4673-4baa-8239-93bf8c22414b] 2020-07-03T14:41:43+02:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: null
{:database_id 7,
:started_at (t/zoned-date-time "2020-07-03T12:41:39.681810Z[Etc/UTC]"),
:via
[{:status :failed,
:class clojure.lang.ExceptionInfo,
:error "Fehler beim Reduzieren der Ergebniszeilen.",
:stacktrace
["--> query_processor.context.default$default_reducef$fn__38004.invoke(default.clj:61)"
"query_processor.context.default$default_reducef.invokeStatic(default.clj:58)"
"query_processor.context.default$default_reducef.invoke(default.clj:49)"
"query_processor.context$reducef.invokeStatic(context.clj:69)"
"query_processor.context$reducef.invoke(context.clj:62)"
"query_processor.context.default$default_runf$respond_STAR___38008.invoke(default.clj:70)"
"driver.bigquery$post_process_native$fn__1380.invoke(bigquery.clj:182)"
"driver.bigquery$do_with_finished_response.invokeStatic(bigquery.clj:141)"
"driver.bigquery$do_with_finished_response.invoke(bigquery.clj:132)"
"driver.bigquery$post_process_native.invokeStatic(bigquery.clj:166)"
"driver.bigquery$post_process_native.invoke(bigquery.clj:163)"
"driver.bigquery$process_native_STAR_$thunk__1474.invoke(bigquery.clj:212)"
"driver.bigquery$process_native_STAR_.invokeStatic(bigquery.clj:214)"
"driver.bigquery$process_native_STAR_.invoke(bigquery.clj:207)"
"driver.bigquery$eval1478$fn__1480.invoke(bigquery.clj:231)"
"query_processor.context$executef.invokeStatic(context.clj:59)"
"query_processor.context$executef.invoke(context.clj:48)"
"query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
"query_processor.context.default$default_runf.invoke(default.clj:67)"
"query_processor.context$runf.invokeStatic(context.clj:45)"
"query_processor.context$runf.invoke(context.clj:39)"
"query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
"query_processor.reducible$pivot.invoke(reducible.clj:31)"
"query_processor.middleware.mbql_to_native$mbql__GT_native$fn__43149.invoke(mbql_to_native.clj:26)"
"query_processor.middleware.check_features$check_features$fn__42463.invoke(check_features.clj:42)"
"query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__43314.invoke(optimize_datetime_filters.clj:133)"
"query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47282.invoke(wrap_value_literals.clj:137)"
"query_processor.middleware.annotate$add_column_info$fn__41084.invoke(annotate.clj:577)"
"query_processor.middleware.permissions$check_query_permissions$fn__42338.invoke(permissions.clj:64)"
"query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__43813.invoke(pre_alias_aggregations.clj:40)"
"query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__42536.invoke(cumulative_aggregations.clj:70)"
"query_processor.middleware.resolve_joins$resolve_joins$fn__44345.invoke(resolve_joins.clj:183)"
"query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39271.invoke(add_implicit_joins.clj:245)"
"query_processor.middleware.limit$limit$fn__43135.invoke(limit.clj:38)"
"query_processor.middleware.format_rows$format_rows$fn__43116.invoke(format_rows.clj:81)"
"query_processor.middleware.desugar$desugar$fn__42602.invoke(desugar.clj:22)"
"query_processor.middleware.binning$update_binning_strategy$fn__41628.invoke(binning.clj:229)"
"query_processor.middleware.resolve_fields$resolve_fields$fn__42144.invoke(resolve_fields.clj:24)"
"query_processor.middleware.add_dimension_projections$add_remapping$fn__38807.invoke(add_dimension_projections.clj:272)"
"query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39027.invoke(add_implicit_clauses.clj:147)"
"query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39420.invoke(add_source_metadata.clj:105)"
"query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__44010.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
"query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__41269.invoke(auto_bucket_datetimes.clj:125)"
"query_processor.middleware.resolve_source_table$resolve_source_tables$fn__42191.invoke(resolve_source_table.clj:46)"
"query_processor.middleware.parameters$substitute_parameters$fn__43795.invoke(parameters.clj:97)"
"query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__42243.invoke(resolve_referenced.clj:80)"
"query_processor.middleware.expand_macros$expand_macros$fn__42858.invoke(expand_macros.clj:158)"
"query_processor.middleware.add_timezone_info$add_timezone_info$fn__39451.invoke(add_timezone_info.clj:15)"
"query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47166.invoke(splice_params_in_response.clj:32)"
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__44021$fn__44025.invoke(resolve_database_and_driver.clj:33)"
"driver$do_with_driver.invokeStatic(driver.clj:61)"
"driver$do_with_driver.invoke(driver.clj:57)"
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__44021.invoke(resolve_database_and_driver.clj:27)"
"query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__43064.invoke(fetch_source_query.clj:243)"
"query_processor.middleware.store$initialize_store$fn__47175$fn__47176.invoke(store.clj:11)"
"query_processor.store$do_with_store.invokeStatic(store.clj:46)"
"query_processor.store$do_with_store.invoke(store.clj:40)"
"query_processor.middleware.store$initialize_store$fn__47175.invoke(store.clj:10)"
"query_processor.middleware.cache$maybe_return_cached_results$fn__42120.invoke(cache.clj:209)"
"query_processor.middleware.validate$validate_query$fn__47184.invoke(validate.clj:10)"
"query_processor.middleware.normalize_query$normalize$fn__43162.invoke(normalize_query.clj:22)"
"query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39289.invoke(add_rows_truncated.clj:36)"
"query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47151.invoke(results_metadata.clj:128)"
"query_processor.middleware.constraints$add_default_userland_constraints$fn__42479.invoke(constraints.clj:42)"
"query_processor.middleware.process_userland_query$process_userland_query$fn__43884.invoke(process_userland_query.clj:136)"
"query_processor.middleware.catch_exceptions$catch_exceptions$fn__42422.invoke(catch_exceptions.clj:174)"
"query_processor.reducible$async_qp$qp_STAR___38090$thunk__38091.invoke(reducible.clj:101)"
"query_processor.reducible$async_qp$qp_STAR___38090.invoke(reducible.clj:107)"
"query_processor.reducible$sync_qp$qp_STAR___38099$fn__38102.invoke(reducible.clj:133)"
"query_processor.reducible$sync_qp$qp_STAR___38099.invoke(reducible.clj:132)"
"query_processor$process_userland_query.invokeStatic(query_processor.clj:218)"
"query_processor$process_userland_query.doInvoke(query_processor.clj:214)"
"query_processor$fn__47350$process_query_and_save_execution_BANG___47359$fn__47362.invoke(query_processor.clj:233)"
"query_processor$fn__47350$process_query_and_save_execution_BANG___47359.invoke(query_processor.clj:225)"
"query_processor$fn__47394$process_query_and_save_with_max_results_constraints_BANG___47403$fn__47406.invoke(query_processor.clj:245)"
"query_processor$fn__47394$process_query_and_save_with_max_results_constraints_BANG___47403.invoke(query_processor.clj:238)"
"api.dataset$fn__50692$fn__50695.invoke(dataset.clj:52)"
"query_processor.streaming$streaming_response_STAR_$fn__34128$fn__34129.invoke(streaming.clj:73)"
"query_processor.streaming$streaming_response_STAR_$fn__34128.invoke(streaming.clj:72)"
"async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
"async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
"async.streaming_response$do_f_async$fn__23118.invoke(streaming_response.clj:85)"],
:error_type :qp,
:ex-data {:type :qp}}],
:error_type :qp,
:json_query
{:database 7,
:query
{:source-table 37,
:aggregation
[["aggregation-options" ["/" ["sum" ["field-id" 478]] ["count"]] {:display-name "avg_consumption"}]
["aggregation-options" ["/" ["cum-sum" ["field-id" 478]] ["count"]] {:display-name "avg_cum_consumption"}]],
:breakout [["field-id" 477]]},
:type "query",
:parameters [],
:middleware {:add-default-userland-constraints? true}},
:native
{:query
"SELECT `metabase_prod_mgmt.consumption_rate_overall`.`month` AS `month`, (CAST(sum(`metabase_prod_mgmt.consumption_rate_overall`.`historical_consumption`) AS float64) / CASE WHEN count(*) = 0 THEN NULL ELSE count(*) END) AS `expression`, (CAST(sum(`metabase_prod_mgmt.consumption_rate_overall`.`historical_consumption`) AS float64) / CASE WHEN count(*) = 0 THEN NULL ELSE count(*) END) AS `expression_2` FROM `metabase_prod_mgmt.consumption_rate_overall` GROUP BY `month` ORDER BY `month` ASC",
:params nil,
:table-name "consumption_rate_overall",
:mbql? true},
:status :failed,
:class java.lang.NullPointerException,
:stacktrace [nil],
:context :ad-hoc,
:error nil,
:row_count 0,
:running_time 0,
:preprocessed
{:database 7,
:query
{:source-table 37,
:aggregation
[[:aggregation-options [:/ [:sum [:field-id 478]] [:count]] {:display-name "avg_consumption", :name "expression"}]
[:aggregation-options [:/ [:sum [:field-id 478]] [:count]] {:display-name "avg_cum_consumption", :name "expression_2"}]],
:breakout [[:field-id 477]],
:order-by [[:asc [:field-id 477]]]},
:type :query,
:middleware {:add-default-userland-constraints? true},
:info
{:executed-by 1,
:context :ad-hoc,
:nested? false,
:query-hash [-33, 62, 107, 26, 32, 16, -126, -123, 15, -45, -75, -95, 23, -40, -97, 116, -68, 27, 31, 102, -49, 113, -32, 20, -24, -23, -41, 50, 94, 97, 18, -125]},
:constraints {:max-results 10000, :max-results-bare-rows 2000}},
:data {:rows [], :cols []}}

[84fad6bc-4673-4baa-8239-93bf8c22414b] 2020-07-03T14:41:43+02:00 DEBUG metabase.middleware.log POST /api/dataset 202 [ASYNC: completed] 4.0 s (10 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (3 idle, 0 queued) (99 total active threads) Queries in flight: 1 (0 queued)`

**To Reproduce**
see gif-file

**Screenshots**
[MetabaseError als gif](https://drive.google.com/file/d/1KXEWLNGO1gRkQNAOA-cFvOumJu74Ogc0/view?usp=sharing)

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 83.0.4103.116
- Your operating system: Windows 10 
- Your databases: Bigquerry SQL
- Metabase version: (e.x. 0.35.4)
- Metabase hosting environment: Jar-file on Ubuntu Server 
- Metabase internal database: default

*Severity**
blocking some users

**Additional context**
In the Version v0.32.8 it worked

**Comment by flamber** [comment] 2020-07-03 12:59
Duplicate of #12585, which is fixed in upcoming 0.36.0 - no release date yes, but probably a few weeks

**Closed by flamber** 2020-07-03 12:59 UTC
Labels: .Needs Triage, Type:Bug
