### ISSUE TITLE
Boolean variables in SQL queries

### ISSUE THREAD

**Issue by josteinbf** [metabase/metabase#21082] opened 2022-03-18 09:52 UTC
**Is your feature request related to a problem? Please describe.**
I wish to write SQL queries/questions that optionally return some rows. For example, consider a table where no entries are ever deleted. The newest row for each ID represents the current value, while the rest of the rows form an audit trail. In those cases, I wish to give the viewer of the question result/dashboard viewer the option to show/hide the rows forming the audit trail. That leads to SQL like this:

```sql
SELECT variable_name, variable_value, created_at
FROM mytable
WHERE {{all_rows}} OR superseded_by is null
```

In this table, the `superseded_by` field points to the `id` of the row that replaced it. For each value of `variable_name` there will be exactly one row with `superseded_by = null`. I'm sure many other use cases for boolean variables, though.

**Describe the solution you'd like**
Boolean to be a variable type available (along with Text, Number etc). The filters in dashboards etc could e.g. be on/off switches.

**Describe alternatives you've considered**

For now, I'm working around this by using a Number variable and putting `WHERE CAST({{all_rows}} as bool)` in the code. From a code point of view this is only a minor inconvenience, but the filter widgets generated are suboptimal -- I need to instruct the users that `0` means "No" and `1` means "Yes".

**How important is this feature to you?**

It won't stop me from using Metabase (which I like, thanks!). But it would certainly make those who view the dashboards and questions that don't have programming experience less confused.

**Additional context**
None

**Comment by flamber** [comment] 2022-03-18 10:09
Duplicate of #20230

**Closed by flamber** 2022-03-18 10:09 UTC
Labels: Type:New Feature, .Needs Triage
