### ISSUE TITLE
Dashboard. Bug Visualization 0.31.2. Edit Filters not showing column information when column table comes from foreign key, and not saving default values for filters.

### ISSUE THREAD

**Issue by jlisyc** [metabase/metabase#9267] opened 2019-01-15 16:49 UTC
###

- Your browser and the version: (Firefox 60.0.1,)
- Your operating system: (ubuntu 16.04)
- Your databases: (Postgres)
- Metabase version: (0.31.2) (in 0.30.4 works ok)
- Metabase hosting environment: (Linux/Ubuntu)
- Metabase internal database: (Postgres)

## Steps to reproduce
1. Database. 
Table "test_a" as: 
![image](https://user-images.githubusercontent.com/33416503/51193315-dfef6c00-18e8-11e9-922d-05cb9ca2ca01.png)
Table "test_b" as (with foreign key to test_a):  
![image](https://user-images.githubusercontent.com/33416503/51195332-21821600-18ed-11e9-908b-4d388c94b7f2.png)

2. Create dashboard based in both question (A TEST 1 from table test_a , and  A TEST 2 from table test_b).
![image](https://user-images.githubusercontent.com/33416503/51195388-3f4f7b00-18ed-11e9-8281-2af88473d9f9.png)

3. Add filter definition
![image](https://user-images.githubusercontent.com/33416503/51195019-8a1cc300-18ec-11e9-80d3-bcc48dbb1250.png)

4. Bug. IN 0.31.2 , If we open again , we can not see filters definitions in the second question (the one we apply filter of foreign key) , And also , it is not saving default values for filters.

It still works, but it is not possible to visualize 
![image](https://user-images.githubusercontent.com/33416503/51195594-b08f2e00-18ed-11e9-8afd-c51cf8b762c6.png)

-------------------
-------------------

Still persist the problem in 0.32.4
![image](https://user-images.githubusercontent.com/33416503/56113813-4a06c400-5f5f-11e9-95fb-2d3881121fd9.png)

-------------------
Thanks for Metabase project!
-------

**Comment by jlisyc** [comment] 2019-01-17 07:32
Hello @salsakran. Could you take a look at this issue? I think is an important issue in 0.31.2
The problem is , after defining the filter (to a foreign column) for a question in a dashboard and we save it; Then, **_when we open again the dashboard_** and edit filters again, we can not see which column was selected 
![image](https://user-images.githubusercontent.com/33416503/51302334-50ee6b00-1a32-11e9-9f6b-80bf4e068ec9.png)

**Comment by jlisyc** [comment] 2019-01-18 07:52
Related http://discourse.metabase.com/t/dashboard-edit-filters-not-showing-column-information-when-column-table-comes-from-foreign-key/5221/7

**Comment by jlisyc** [comment] 2019-01-22 15:58
Yes. He can execute the question and see data from borh tables. He select exactly the same column, but in the case of "foreign key" can not see the info. (in 0.30.4 works well)
![image](https://user-images.githubusercontent.com/33416503/51547431-93ff7280-1e66-11e9-8352-0ecd33120bf7.png)

**Comment by jlisyc** [comment] 2019-02-13 18:14
it shows this error also when tried to change the filter field
![image](https://user-images.githubusercontent.com/33416503/52733666-86e82600-2fc3-11e9-889b-d63ce208d0ca.png)

**Comment by flamber** [comment] 2019-02-14 03:03
It took me a little time to understand this issue, but I've reproduced with Sample on 0.31.2 (Firefox 65)

1. Create QB with SampleData, from `ORDERS`, group by `ORDERS.ID` and `PRODUCTS.TITLE` (linked table), since I just want two columns, and add to dashboard.
2. Edit dashboard and add two filters. FilterA connects to `ORDERS.ID`, FilterB connects to `PRODUCTS.TITLE`, save the dashboard.
3. Edit the dashboard again. Edit FilterA and it shows as connected to `ORDERS.ID`. Edit FilterB and it shows as unconnected "Select..."

I cannot reproduce the JS error. And from what I can tell, everything is working as it should, so this is just a visual problem, where linked table columns doesn't get listed in the filter connected selector.

**Comment by jlisyc** [comment] 2019-02-14 08:05
Thanks Flamber, that's right. It's a visual issue, It still works, but it is not possible to visualize the connected filter.

**Comment by flamber** [comment] 2019-02-25 02:13
This is a duplicate of #9267 - normally I would reference the oldest issue, but @MarkRx has made a very detailed description.

**Comment by MarkRx** [comment] 2019-02-25 16:31
@flamber I think you mean #9364

**Comment by flamber** [comment] 2019-02-25 16:38
@MarkRx I was tired I guess after going through so many bugs, so my copy/paste-fu was off :smile:

**Comment by jlisyc** [comment] 2019-04-15 07:17
Hi All
Still persist the probnlem in 0.32.4
![image](https://user-images.githubusercontent.com/33416503/56113787-34919a00-5f5f-11e9-9324-14d065e37b0d.png)

**Comment by jlisyc** [comment] 2019-04-24 07:34
Hi @salsakran , @flamber ,
Don´t you think this is an important issue to be solved in 0.32.6?  
Thanks anyway.

**Comment by jlisyc** [comment] 2019-05-08 15:59
Hi,
Have you got a release decided to fix this issue?

**Comment by flamber** [comment] 2019-05-08 16:05
@jlisyc 
As I earlier pointed out, this issue should be closed and you should :+1: and Subscribe to #9364, which has been marked as Priority 1. That doesn't mean it will be fixed in next release, but indicates priority.

**Comment by jlisyc** [comment] 2019-06-07 05:59
Closed because of it is managing in #9364

**Comment by jlisyc** [comment] 2019-06-07 06:00
Closed because of it is managing in #9364

**Closed** 2019-06-07 05:59 UTC
Labels: Bug, Dashboards, Parameters/Variables, Priority/P2
