### ISSUE TITLE
Filtering on date columns by relative dates returning wrong results

### ISSUE THREAD

**Issue by albertoperdomo** [metabase/metabase#42291] opened 2024-05-06 18:27 UTC
### Describe the bug

We have recently started seeing duplicate records in our weekly alerts. This started around 2-3 weeks ago.

### To Reproduce

1. Go to https://stats.metabase.com/question/4859
2. Change filter on created at from past week 16 weeks ago, to past week from 17 weeks ago 
3. Realize there are some results that show up in both when they should not

### Expected behavior

There seems to be something wrong with this filter. This was reliable up until a few weeks ago and now we consistently have the duplicates every week.

### Information about your Metabase installation

```JSON
- Hash 649de4f 2024-05-06
```

### Severity

P2

### Additional context

Discussion in Slack w/ Loom: https://metaboat.slack.com/archives/C01LQQ2UW03/p1714409208479349

**Comment by camsaul** [comment] 2024-05-07 02:10
Is this bug present in 49?

**Comment by camsaul** [comment] 2024-05-07 03:58
Duplicate of #34573

**Comment by camsaul** [comment] 2024-05-07 04:26
Ok while this is extremely similar to #34573 I actually have a way to work around this on the BE

**Comment by camsaul** [comment] 2024-05-30 20:33
@albertoperdomo is reporting this is still not working as expected here https://metaboat.slack.com/archives/C01LQQ2UW03/p1716799511920049?thread_ts=1714409208.479349&cid=C01LQQ2UW03

**Comment by albertoperdomo** [comment] 2024-06-20 15:01
Upgraded to P1: Correctness of results on a common feature

**Closed** 2024-06-24 20:18 UTC
Labels: Type:Bug, Priority:P1, Querying/MBQL, .Team/QueryProcessor
