### ISSUE TITLE
Allow Visualization Plugins too.

### ISSUE THREAD

**Issue by aadrian** [metabase/metabase#22103] opened 2022-04-26 18:27 UTC
Please allow Visualization Plugins/Extensions, in a similar way Superset allows it https://superset.apache.org/docs/contributing/creating-viz-plugins/, ( besides the currently supported driver extension mechanism https://github.com/metabase/metabase/blob/master/docs/developers-guide/drivers/start.md )

This would allow the community to quickly contribute many new visualization types (since this is an area where Metabase is missing allot of chart types ,e.g.: Force Directed Graph Chart , Circular Graph Chart, Tree Chart, Tree Map, Chord, Sankey, Sunburst, HeatMap, BoxPlots, etc ) 

Thank you.

**Comment by flamber** [comment] 2022-04-26 18:31
Duplicate of #2318

**Closed by flamber** 2022-04-26 18:31 UTC
Labels: Type:New Feature, .Needs Triage
