### ISSUE TITLE
Repetetion of label name on questions

### ISSUE THREAD

**Issue by antonio-mendes** [metabase/metabase#9762] opened 2019-04-11 15:10 UTC
Hey hey,

So basically we've noticed after some users reported that labels on question when there's more than 2 grouping just keep repeating the name and color of the 2nd grouping even though the values are actually correct. Something like this:
![image](https://user-images.githubusercontent.com/29656081/55968591-98287880-5c7c-11e9-9bff-f5821a8f9ee8.png)

As you can see there's 2 sessions. The values however in the chart are correct, just the color and label are not. If there's X variables all of them from the 2nd onwards will be Red and Sessions.

Additional info:
- Happening on the latest Chrome and Firefox 66.0.2 at least, got some reports from dashboard users using Safari too
- MacOS and Linux (Manjaro)
- Postgres
- Metabase version: 0.31.2
- Metabase hosting environment: Linux (Gentoo)
- Metabase internal database: H2

I couldn't find any other similar report. Thank in advance for the help!

**Comment by mazameli** [comment] 2019-04-11 17:23
Pretty sure this is a duplicate of https://github.com/metabase/metabase/issues/9636 which was fixed in version 0.32.2 (latest is 0.32.4).

**Closed by mazameli** 2019-04-11 17:23 UTC
Labels: Duplicate
