### ISSUE TITLE
Unable to change Dashboard Filter Default Value

### ISSUE THREAD

**Issue by jonchua-habu** [metabase/metabase#27924] opened 2023-01-27 19:23 UTC
**Describe the bug**
Changing the default value for a dashboard filter is reflected in the edit screens, but not in the dashboard view

**To Reproduce**
1. Create a Dashboard
2. Add a filter, connect to reports
3. Set a default value
(Our example had the default value set for 3-4 weeks)
4. Change the default value
5. Observe whether it's reflected in the dashboard
(Note: We were able to fix this by making a new filter that used the same Field)

**Expected behavior**
New default filter value reflected in the Dashboard

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Blocking users and our ability to make the tool self-service

**Additional context**
This inconsistently happens. The location where this occurred was a very complex use case. The Dashboard was behind several links and had 100Ms of data. Very odd that re-creating the filter from scratch fixed the problem.

**Comment by paoliniluis** [comment] 2023-01-27 20:25
@jonchua-habu can you post diagnostic info? we don't know the version you're running to start debugging

**Comment by jonchua-habu** [comment] 2023-01-27 20:53
Here you go! FYI, this issue was found by a customer success resource
but the diagnostics were pulled by one of our engineers that manages
our enterprise instance.

{

  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2
Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.17+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.17",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.17+8",
    "os.name": "Linux",
    "os.version": "5.4.219-126.411.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "snowflake",
      "athena",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.17"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-12-07",
      "tag": "v1.45.1",
      "branch": "release-x.45.x",
      "hash": "019d31c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}



--

*Jon Chua*

Senior Product Manager

+1 847.651.0180

habu.com
[image: Habu] <https://habu.com/>

**Comment by paoliniluis** [comment] 2023-03-06 00:32
If you could capture the API call (browser dev tols-network tab) when you do the change, it would be awesome, as we can't reproduce and I believe this is an issue in the backend. Closing for now till we have those logs, feel free to reopen it if you can capture the logs

**Closed by paoliniluis** 2023-03-06 00:32 UTC
Labels: Type:Bug, .Needs Triage
