### ISSUE TITLE
Table sort order issue when grouping by datetime hour of day and any other field, hour of day order changes to alphabetical

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#8543] opened 2018-09-17 22:19 UTC
Hi guys, recently updated to v0.30.3, and migrated from H2 to PostgreSQL, both the processes went great and I'm loving the improved performance.

I've got a small issue when grouping by datetimes. What I'm really trying to do is build a type of heatmap (or similar) that shows events by hour of day and day of week in the same chart/table. Tried using a scatter chart but struck limitations, so figured I'd use the nice new table formatting features of v0.30.

### Environment
- Your browser and the version: Version 69.0.3497.81 (Official Build) (64-bit)
- Your operating system: Windows 7
- Your databases: SQL Server 2014
- Metabase version: 0.30.3 (but also existed in 0.29)
- Metabase hosting environment: Windows Server 2012
- Metabase internal database: Postgres

### Repro steps
- New question on a table that has a datetime field
- Table visualisation
- Count, group by datetime field "hour of day"
- Output table is sorted by the hour of day, numerically. All good here.
- Add a second group by field, could be any category I think.
- **BUG** Output table is now sorted by hour of day alphabetically, which is not really what I expected.

### Example Image
![image](https://user-images.githubusercontent.com/4504437/45652281-3bbb0b80-bb28-11e8-895d-981ab2474e11.png)

It doesn't seem to matter if the table puts the hour of day on rows or columns, it will order them alphabetically, not numerically.

I know I could update my data source (a SQL view) to split out the hour of day as a number, but as "hour of day" is an option I'd strongly prefer to use that.

Thanks

**Comment by flamber** [comment] 2019-02-22 23:31
Duplicate of #8053 - fixed in 0.31

**Comment by mazameli** [comment] 2019-10-10 23:21
Closing as duplicate as flamber mentioned. Fixed in 0.31.

**Closed by mazameli** 2019-10-10 23:21 UTC
Labels: .Duplicate, Query Builder, Type:Bug
