### ISSUE TITLE
Selecting column Y while trying to unselect X

### ISSUE THREAD

**Issue by qloridant** [metabase/metabase#10838] opened 2019-09-09 08:07 UTC
**Describe the bug**
While creating a query, I want to unselect columns. But after unselecting a few columns (also creating a feature request for an unselect all option), when I click to unselect the 19th column, it selects a column that I already unselected, the 14th one (or sometimes the 10th).

**Logs**
This bug does not create a log entry

**To Reproduce**
1. Go to 'Ask a new question' (you need a data base with at least 20 columns)
2. Click on 'Custom query'
3. Click on 'columns'
4. Try to unselect all the columns, starting from the 1st one

**Screenshots**
![bug](https://user-images.githubusercontent.com/14170613/64513651-4e09f880-d2e9-11e9-9a81-b82d2142638f.png)

**Information about your Metabase Installation:**
- Your browser and the version:  Firefox 68.0.2
- Your operating system:  Ubuntu 16.04
- Your databases: Postgres
- Metabase version: v0.33.2
- Metabase hosting environment:  Jar-file on Ubuntu
- Metabase internal database:  Postgres

**Severity**
Blocking users that do not want to write SQL and want to choose specific columns

**Comment by flamber** [comment] 2019-09-09 15:56
Hi @qloridant 
I remember this issue on the 0.33-preview releases, but I cannot reproduce on 0.33.2 with Firefox 69.
As for deselecting all columns and a better interface, when having a lot of columns, then you should check out #10460 - upvote by clicking :+1: on the first post.

**Comment by qloridant** [comment] 2019-09-10 08:20
Upvote done. 
I Will try to improve the 'Steps to reproduce' section then.
Thank you for your answer

**Comment by bglaplante** [comment] 2019-09-13 17:15
I had definitely seen this issue on 0.33 initial release (not preview).  But I just tried to reproduce it on 33.2 using Firefox 69.0 - and couldn't.  I also tried Chrome 76.0 and again the bug seems to have vanished for me.

Not to say I like the interface jumping to the top of the list every time I click - requires me to scroll back down.  I think that's new.

**Comment by flamber** [comment] 2020-06-01 17:22
Closing, since I haven't been able to reproduce on any browsers and no other reports about Y X.
Jumping is #11202, but it will be fixed when #10460 is fixed - upvote by clicking :+1: on the issue

**Closed by flamber** 2020-06-01 17:22 UTC
Labels: Priority:P3, Querying/Notebook, Type:Bug, Type:UX
