### ISSUE TITLE
Support ClickHouse as one of the database connections in Metabase

### ISSUE THREAD

**Issue by manojfim** [metabase/metabase#13826] opened 2020-11-18 01:52 UTC
**Is your feature request related to a problem? Please describe.**
ClickHouse is a great DW which is an open-source columnar. The queries run fast. It would be great to join clickhouse and Metabase to query and visualize data.

**Describe the solution you'd like**
Adding support for connecting ClickHouse as one of the databases in the supported list

**How important is this feature to you?**
This would be a game-changing feature. The duo Metabase + ClickHouse can compete with industry self-service analytics leaders like Looker.

**Comment by salsakran** [comment] 2020-11-18 01:56
this is a duplicate of #3332

Please upvote that if you wish to nudge it up.

**Closed by salsakran** 2020-11-18 01:56 UTC
Labels: .Needs Triage, Type:New Feature
