### ISSUE TITLE
Sub-collection in Personal Collections shows in sidebar hierarchy even after they are archived

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#15343] opened 2021-03-25 20:26 UTC
**Describe the bug**
It is not possible to get rid of (sub) collections that live inside users' personal collections after they are archived. At first I thought it's just a UI glitch that requires a page reload. Nope - it simply won't go away. That creates a bunch of new issues because it is possible to edit such (archived) collection, add questions/dashboards/new collections to it, etc.

The weirdest possible thing is that if you look inside the archive, it lives there as well 👽

**Logs**
Examining `GET /api/collection/:id` (when loading UI) will show that such collection has archived attribute already set.
`archived: true`

**To Reproduce**
1. Go to your own personal collection
2. Add new collection to it (call it "Foo")
3. Navigate inside newly created (sub) collection
4. Click pencil icon
5. Choose "Archive this collection" (confirm by clicking "Archive" button in the modal)
6. You will see that "Foo" is still visible in the sidebar
7. Refresh the page - "Foo" collection is still there
    - if you examine the GET request like I described above, you'll see that this collection has `archived: true`
8. Click on "View archive" in bottom left corner (Go to archive)
9. You will see that "Foo" collection shows inside archive

**Expected behavior**
Archived collection should immediately vanish from the UI and should live in "Archive" only!

**Screenshots**
N/A

**Information about your Metabase Installation:**
- Metabase version: v0.38.3-SNAPSHOT
- Metabase hosting environment: local dev, release-x.38.x
- Metabase internal database: H2 (default), sample dataset

**Severity**
I'd say P2. This shouldn't happen at all.

**Additional context**
N

**Comment by flamber** [comment] 2021-03-26 19:12
Slightly similar to #14907, but this is only in PC, so only giving P3. It's a regression since 0.38.0

**Comment by kulyk** [comment] 2021-04-20 10:22
Fixed by #15674

**Closed by kulyk** 2021-04-20 10:22 UTC
Labels: .Regression, .Reproduced, Organization/Collections, Priority:P3, Type:Bug
