### ISSUE TITLE
Filter variable not working when only executing part of the sql code

### ISSUE THREAD

**Issue by EvaSchreyer** [metabase/metabase#17411] opened 2021-08-11 14:08 UTC
**Describe the bug**

I have a BigQuery database and metabase version 0.40.0. 

When I use common table expressions ("with" statements) and run only a part of the code that I have marked, the used text/number filter variables don´t work (there is no error, they just don´t filter).
When I run the whole sql syntax with the blue button they work. 

**To Reproduce**
Create a functioning sql query with text/number filter variables and then mark some of the code that itself is able to run that includes the filter. Then run this marked code snippet. The text/number filter does does not filter anything.

**Comment by flamber** [comment] 2021-08-11 14:10
Duplicate of #16584

**Closed by flamber** 2021-08-11 14:10 UTC
Labels: Type:Bug, .Needs Triage
