### ISSUE TITLE
Pin map fails when there is a null latitude or longitude, error "e is null" displayed

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#11818] opened 2020-01-29 02:02 UTC
**Describe the bug**
When using the Pin Map visualisation if there are any records with a null latitude or longitude the entire map will not display and the error "e is null" is displayed.
There's also no simple way to filter these records out in the question builder, for a latitude or longitude field you can only filter by "Is", "Is not", and "Inside", there is not "Is empty" option.

**Logs**
```
TypeError: "e is null"
    project http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    latLngToPoint http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    project http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    latLngToLayerPoint http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    update http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    setLatLng http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    value http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    value http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    notifyAll http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    close http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    closeAll http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    perform http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    perform http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    perform http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    M http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    closeAll http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    perform http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    batchedUpdates http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    e http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    a http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    enqueueSetState http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    setState http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    onStateChange http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    notify http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    notifyNestedSubs http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    onStateChange http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    g http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    default http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    default http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    thunkWithDispatchAction http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    dispatch http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    action http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    n http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    M http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    _invoke http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    t http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    r http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    q http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    q http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    queryCompleted http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    thunkWithDispatchAction http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    dispatch http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    e http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
app-main.bundle.js:5:1240589
    value http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    value http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    notifyAll http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    close http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    closeAll http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    perform http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    perform http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    perform http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    M http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    closeAll http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    perform http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    batchedUpdates http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    e http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    a http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    enqueueSetState http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    setState http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    onStateChange http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    notify http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    notifyNestedSubs http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    onStateChange http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    g http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    default http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    default http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    thunkWithDispatchAction http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    dispatch http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    action http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    n http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    M http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    _invoke http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    t http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    r http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    q http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    q http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    queryCompleted http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    thunkWithDispatchAction http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    dispatch http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    e http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
```
```
e is null app-main.bundle.js:5:324251
    onRenderError http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    value http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    value http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    notifyAll http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    close http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    closeAll http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    perform http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    perform http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    perform http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    M http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    closeAll http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    perform http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    batchedUpdates http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    e http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    a http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    enqueueSetState http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    setState http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    onStateChange http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    notify http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    notifyNestedSubs http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    onStateChange http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    g http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    default http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    default http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    thunkWithDispatchAction http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    dispatch http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    action http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    n http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    M http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    _invoke http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    t http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    r http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    q http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    q http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    queryCompleted http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    thunkWithDispatchAction http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    dispatch http://localhost:3000/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    e http://localhost:3000/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
```

**To Reproduce**
(I couldn't find quick way to reproduce in the Sample Dataset as all the records have a lat/long populated)
1. Ask a question on a table with lat/long field where some are null
2. Set row limit to 999 otherwise not pins rendered anyway
3. Order the dataset such that some of the record have null lat/long values (bit hand wavy I know, sorry)
4. Change the visualisation to a Pin map
5. Error displayed on screen "e is null"

**Expected behavior**
I'd expect it to display all the valid lat/longs on the map, and hopefully say how many couldn't be displayed because they were invalid or null.

**Screenshots**
Query as a table, these blank lat/long are nulls
![image](https://user-images.githubusercontent.com/4504437/73319997-ec9bf380-42a2-11ea-9a7f-d8ba28c5e40f.png)

After changing to map:
![image](https://user-images.githubusercontent.com/4504437/73320012-f9204c00-42a2-11ea-8b51-b34519245c1f.png)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_101-b13",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_101",
    "java.vm.name": "Java HotSpot(TM) Client VM",
    "java.vm.version": "25.101-b13",
    "os.name": "Windows 7",
    "os.version": "6.1",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.1",
      "date": "2020-01-13",
      "branch": "release-0.34.x",
      "hash": "265695c"
    },
    "settings": {
      "report-timezone": "Pacific/Auckland"
    }
  }
}

**Severity**
Annoyance and adds complexity. In order to use maps I've had to create a "Has lat long" field for each location (i.e. lat and long are not null) which I can use to filter the dataset before changing to a map. This is easy to forget and forces me to put that logic somewhere to create it (views, ETL step etc). Daily users often forget this step and simply give up trying to use the Metabase maps.

**Comment by paulrosenzweig** [comment] 2020-01-29 14:36
Duplicate of #7361, which has PR #11779 open to fix it.

**Closed by paulrosenzweig** 2020-01-29 14:36 UTC
Labels: .Needs Triage, Type:Bug
