### ISSUE TITLE
The return of thin bar charts

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3842] opened 2016-11-30 23:55 UTC
A user in Discourse is reporting that they're getting thin bar charts in 0.20.3:
http://discourse.metabase.com/t/my-bar-charts-are-all-thin/129/7?u=maz

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment] 2017-02-10 18:08
Was anyone able to reproduce this?

**Comment by mazameli** [comment] 2017-02-10 19:23
Coincidentally, [another Discourse user just wrote this](http://discourse.metabase.com/t/my-bar-charts-are-all-thin/129/8?u=maz) a minute ago:

> I've seen the same issue with the thin bar charts. What I found was that when I had a linear x-axis that contained buckets, like yours does, then the bar char was actually leaving space for the numbers in between, which is why the bars were so thin. For example, in your case, it has a bucket for 4 and 9, but the bars are thin because it has a 0 value for 5, 6, 7, & 8. You can fix this by changing the x-axis to be ordinal instead of linear, which will cause metabase to not fill in 0 values for the "missing" data.

**Comment by tlrobinson** [comment] 2017-02-10 20:27
I think these are two different (but related) issues:

1. Sometimes we don't compute the correct interval size of the data, which causes the bars to be narrow. This is definitely a bug.
2. Sometimes we compute the "correct" interval size, but your data is sparse and you probably want to view it using an ordinal X axis, rather than the default linear axis. This is more of a limitation. We could potentially detect sparse data and default to ordinal.

In the case of bucketing, if you're sure every bucket will have a result then it's safe to just use the ordinal axis.

Otherwise, you'll need to make sure your buckets are regularly spaced so that we compute the correct interval size.

However, we may be able to improve the interval size computation. e.x. currently we correctly compute the interval size of `[0, 5, 10, 15]` as `5`, but `[1, 6, 11, 16]` as `1`. Is that correct, or should it be `5`?

But then what happens when the data is sparse? e.x. `[1, 6, 16]`

Or slightly irregularly spaced, like `[4, 9, 15, 21]` in louloizides's example.

Or both...?

I'm sure we could come up with some heuristics, or maybe we should just allow you to override the interval size?

@salsakran Do you have any opinions on this?

**Comment by gilhs** [comment] 2017-06-01 12:52
Any plans to resolve?

Just to add a my 2 cents - the issue is enhanced in part by the automatic enriching of a date format; notice how switching to ordinal transforms the 'week' value from a date string ('2017-05-01') into a more robust date item which includes day of week, time, etc.)

![image](https://cloud.githubusercontent.com/assets/22723398/26680487/4d067980-46e2-11e7-9d8b-64999d417cca.png)

![image](https://cloud.githubusercontent.com/assets/22723398/26680494/52eb691e-46e2-11e7-9c20-dd89541162bf.png)

**Comment by sabino** [comment] 2017-10-19 19:13
We just had this problem. I have no idea what caused.
Version 0.25.2

**Comment by ali-izzo** [comment] 2018-04-11 04:43
I have the exact same problem with the latest version of metabase and it's giving our manager a really bad impression. On one side I can't change the timezone (as our reports would no longer make sense), on the other the charts are unreadable. Please fix this soon.

**Comment by zuk** [comment] 2019-01-16 15:37
Ran into the same issue today with a timeseries x-axis.

.One bit worth noting is that the bar chart looks fine when it's done using the query builder, but as soon as I convert it to native SQL using "Convert this question to SQL", the bars become thin:

<img width="739" alt="image" src="https://user-images.githubusercontent.com/35702/51259558-6dc76780-197a-11e9-8dca-ed901dc78956.png">
<img width="222" alt="image" src="https://user-images.githubusercontent.com/35702/51259586-7c158380-197a-11e9-8205-140d6d3ed439.png">
<img width="738" alt="image" src="https://user-images.githubusercontent.com/35702/51259611-83d52800-197a-11e9-8b64-17d756b83bc8.png">

This leads me to believe that Metabase is using some other hinting to determine how to handle the x-axis interval. I've looked through the `report_card` table to see if there are any clues in the `dataset_query` or `visualization_settings` JSON, but no luck so far.

**Comment by VirgilRealityDev** [comment] 2020-10-06 05:23
This bug seems to have returned in the latest version.

You're on version v0.36.6
Built on 2020-09-15

**Comment by flamber** [comment] 2020-10-06 08:51
@VirgilRealityDev The issue is still open, so it hasn't returned in 0.36.6. You can get more appropriate spacing, when your data spread over multiple periods, if you change visualization Settings > Axes > X-axis scale = Ordinal

**Comment by paulrosenzweig** [comment] 2021-02-09 14:27
The weekly case was fixed in #14706. If you see a related problem, please open another issue.

**Closed by paulrosenzweig** 2021-02-09 14:27 UTC
Labels: Priority:P3, Type:Bug, Visualization/
