### ISSUE TITLE
Converting question to raw SQL broken for grouped by questions using latitude or longitude 

### ISSUE THREAD

**Issue by gdippolito** [metabase/metabase#10894] opened 2019-09-15 18:15 UTC
When converting a question to raw SQL a pop up appear displaying the raw SQL for the question metabase is about to convert in raw SQL. This function does not appear to work properly for questions that are grouped by a latitude or longitude field. Metabase convert the question in raw SQL but the question does not produce any more the expected results. 

**Logs:**
There are not evident logs in the console when the issue happen.

**Reproduce the bug:**
1. Using the sample dataset create a question using the People table. 
2. Group the question by latitude or longitude.
3. Transform the query in raw sql.
4. The query does not produce the expected result. 

**Expected behavior**
I expected the same behaviour performing the query throug the query builder and via raw SQL.

**Screenshots**

**Information about your Metabase Installation:**
- Your browser and the version: Firefox 68.02
- Your operating system: Fedora 30
- Your databases: Postgres
- Metabase version: 0.33.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
Medium

**Additional context**

**Comment by flamber** [comment] 2019-09-15 18:35
Hi @gdippolito 
What do you mean by "The query does not produce the expected result" ?
Are you binning the latitude/longitude by Auto, None, ...?

**Comment by gdippolito** [comment] 2019-09-15 20:14
Hi @flamber,

The binning is left as auto. What I meant is that result of the query is not displayed. 

After converting the query to raw SQL and pressing the play icon the graph is not displayed but only a grey shadow is visible. 
See the attached image as reference:
![image](https://user-images.githubusercontent.com/18577894/64927040-86379c80-d7fd-11e9-8aea-981bda7d16ad.png)

**Comment by flamber** [comment] 2019-09-15 20:30
Okay, so it's not specific to latitude/longitude, but binning on any non-date field.
Try Orders - Count of rows by Total:Auto.
I'm quite sure this is a duplicate of #10840, which will be fixed by @paulrosenzweig in #10858.
Work-around: Go to visualization :gear: Settings > Data and set the columns manually.

**Comment by gdippolito** [comment] 2019-09-15 21:08
Thanks for the reply. 
Yes, I think is the same bug.
I have try to follow your suggestion but I think I have faced a possibly different one. 
If I group by latitude and longitude a query (e.g People table) and bin to 0.1 degree I will be able to select as visualization a grid map which is displayed as expected. If I then transform this query to a raw SQL the map broke with the following error: 
![image](https://user-images.githubusercontent.com/18577894/64927620-0f060680-d805-11e9-98b3-165075a11a95.png)
Is this a separate bug? If so do you want me to create a separate bug report for it?

**Comment by flamber** [comment] 2019-09-15 21:12
The error `Grid map requires binned longitude/latitude.` is covered in #8362.

**Comment by gdippolito** [comment] 2019-09-15 22:07
Thanks for your response. I guess we can close this issue and mark as duplicate of the two issues you have mentioned above. Have a great day.

**Closed** 2019-09-15 22:08 UTC
Labels: Type:Bug
