### ISSUE TITLE
we seem to be creating lots of no-change revisions for dashboards

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#15953] opened 2021-05-06 20:11 UTC
<img width="645" alt="image" src="https://user-images.githubusercontent.com/6377293/117359255-c1785a80-ae7c-11eb-8ccf-c4b807050461.png">

Dashboards seem to end up with lots of diffs that have no diffs in them.

```clojure
;; in models.revision
(comment
  (pprint
   (map metabase.test/derecordize
    (revisions+details metabase.models.dashboard/Dashboard 9))))

(
{:description nil,
 :is_creation false,
 :id 395,
 :is_reversion false,
 :timestamp #t "2021-05-06T15:01:55.297356Z",
 :user {:id 1, :first_name "dan", :last_name "sutton", :common_name "dan sutton"},
 :message nil,
 :diff {:before nil, :after nil}}
...)
```

There's a [PR to suppress these](https://github.com/metabase/metabase/pull/15942) but we should probably identify why we are getting so many.

## Reproduction
Create a dashboard, edit and add a card, save, edit and resize the card.
<img width="641" alt="image" src="https://user-images.githubusercontent.com/6377293/117359665-53806300-ae7d-11eb-907c-b0c6f796549d.png">

**Comment by flamber** [comment] 2021-05-06 20:56
This is caused by how the frontend saves, which is a 3 step process, when e.g. adding a new card to an empty dashboard.

1. Request an `cardid` to be used in step 2 via `POST /api/dashboard/:id/cards`
2. Insert the card details and position via `PUT /api/dashboard/:id/cards`
3. Update the dashboard, which contains most of the information from step 1+2 too via `PUT /api/dashboard/:id`

Editing a dashboard and just clicking Save without making any changes will leave an empty diff because of step 3.

In my point of view, it doesn't make sense to have these as three different revisions, since it should not possible to revert to somewhere in between these revisions - that just causes some interesting corruption #6884.

And it doesn't make much sense to show a revision for each added card, when adding multiple cards, since it's not possible to know which one you're reverting back to - and also causes corruption.
![image](https://user-images.githubusercontent.com/1447303/117363222-93b30600-aebc-11eb-9c14-9e2c1a6b0bdb.png)

There should just be a single revision for each time there's a Save. The description should then tell what has happened. Example:
![image](https://user-images.githubusercontent.com/1447303/117363909-88140f00-aebd-11eb-9a90-5b10d27a6c51.png)
Would likely need a slight UI makeover to make the description less ugly - perhaps elements from the new timeline can be used.

**Comment by gusaiani** [comment] 2021-05-06 22:54
@flamber @dpsutton, also may be worth noting cases that are not composite changes in one diff.

One I noticed:

1. Create a new Dashboard
2. Click pencil icon (top, right-hand) to edit
3. Click **Aa** button to insert text box
4. Click Save
5. Click pencil icon (top, right-hand) to edit
6. Add any text to text box
7. Click **Save**

In other words, just editing a textbox inside a Dashboard generates a diff with no description.

**Comment by gusaiani** [comment] 2021-05-06 22:56
Also, creating an empty textbox and saving generates two discrete diffs with descriptions:

1. "added a card"
2. "cards rearranged"

So, as far as I understand, "cards rearranged" should not exist.

**Comment by flamber** [comment] 2021-05-07 07:46
@gusaiani The empty description is caused by step 3 in my comment. And "cards rearranged" is caused by step 2 in my comment, since we're likely not checking if previous position was null, where it should think of it as a new card instead of rearranged.

**Comment by pawit-metabase** [comment] 2021-09-15 10:01
If you're playing around and you're wondering why the revert button sometimes fail or nothing happens, see the following issue/PR:

#15237
#17899

**Comment by qnkhuat** [comment] 2023-09-28 10:31
Fixed by https://github.com/metabase/metabase/pull/30285

**Closed by qnkhuat** 2023-09-28 10:31 UTC
Labels: Type:Tech Debt, Organization/Activity Log
