### ISSUE TITLE
[P1D] Make it apparent, if not obvious, how to edit the model for a view

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26439] opened 2022-11-11 22:12 UTC

**Comment by kulyk** [comment] 2022-11-21 17:19
We were thinking about putting the query builder in a modal for this, but we'd need to refactor how QB manages its own URL to make it happen. Another approach is to ditch an explicit "editing" mode for pages/dashboards

**Comment by kulyk** [comment] 2022-11-21 17:29
Isn't this a duplicate of #26362?

**Closed** 2022-11-22 11:20 UTC
