### ISSUE TITLE
Changing a parameter on a native SQL query starts a new question

### ISSUE THREAD

**Issue by Nikos410** [metabase/metabase#11964] opened 2020-02-24 13:09 UTC
**Describe the bug**
Changing a parameter value in a native SQL query sometimes starts a new question:
https://streamable.com/x2ohl

Executing the query after setting a parameter works one time and then metabase starts a new question, which means that you can't run the query again because of missing permissions (Our users can run SQL questions but can't write their own ones).

I'm not 100% sure what causes this, but this is a huge query where we are creating and dropping temporary tables, I'll try to narrow down what exactly causes this to happen.

**Logs**
Loading the query and running it without parameters:
```
Feb 24 13:48:04 kevdev48 java[1812]: 02-24 13:48:04 DEBUG middleware.log :: GET /api/user/current 200 2,7 ms (3 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (196 total active threads) Queries in flight: 0
Feb 24 13:48:04 kevdev48 java[1812]: 02-24 13:48:04 DEBUG middleware.log :: GET /api/session/properties 200 2,9 ms (1 DB calls) Jetty threads: 3/50 (3 idle, 0 queued) (196 total active threads) Queries in flight: 0
Feb 24 13:48:04 kevdev48 java[1812]: 02-24 13:48:04 DEBUG middleware.log :: GET /api/database 200 5,5 ms (3 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (196 total active threads) Queries in flight: 0
Feb 24 13:48:04 kevdev48 java[1812]: 02-24 13:48:04 DEBUG middleware.log :: GET /api/card/240 200 4,6 ms (6 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (196 total active threads) Queries in flight: 0
Feb 24 13:48:05 kevdev48 java[1812]: 02-24 13:48:05 DEBUG middleware.log :: GET /api/database 200 115,4 ms (20 DB calls) Jetty threads: 3/50 (3 idle, 0 queued) (196 total active threads) Queries in flight: 0
Feb 24 13:48:05 kevdev48 java[1812]: 02-24 13:48:05 DEBUG middleware.log :: GET /api/alert/question/240 200 702,3 µs (1 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (196 total active threads) Queries in flight: 0
Feb 24 13:48:05 kevdev48 java[1812]: 02-24 13:48:05 DEBUG middleware.log :: GET /api/collection/118 200 2,7 ms (4 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (196 total active threads) Queries in flight: 0
Feb 24 13:48:07 kevdev48 java[1812]: 02-24 13:48:07 DEBUG middleware.log :: POST /api/card/240/query 202 [ASYNC: completed] 2,0 s (10 DB calls) Jetty threads: 2/50 (4 idle, 0 queued) (196 total active threads) Queries in flight: 0
```

Setting parameter and running it again:
```
Feb 24 13:49:46 kevdev48 java[1812]: 02-24 13:49:46 DEBUG middleware.log :: POST /api/card/240/query 202 [ASYNC: completed] 1,2 s (11 DB calls) Jetty threads: 2/50 (4 idle, 0 queued) (193 total active threads) Queries in flight: 0
```
After the query has run with the parameter, Metabase switches to "New question"

Trying to run the "new question" again:
```
Feb 24 13:51:53 kevdev48 java[1812]: 02-24 13:51:53 WARN middleware.process-userland-query :: Abfrage fehlgeschlagen {:status :failed,
Feb 24 13:51:53 kevdev48 java[1812]:  :class clojure.lang.ExceptionInfo,
Feb 24 13:51:53 kevdev48 java[1812]:  :error "Du hast keine Berechtigungen, um diese Abfrage auszuführen.",
Feb 24 13:51:53 kevdev48 java[1812]:  :stacktrace
Feb 24 13:51:53 kevdev48 java[1812]:  ("--> query_processor.middleware.permissions$perms_exception.invokeStatic(permissions.clj:23)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.permissions$perms_exception.invoke(permissions.clj:22)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.permissions$fn__42821$check_ad_hoc_query_perms__42826$fn__42827.invoke(permissions.clj:32)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.permissions$fn__42821$check_ad_hoc_query_perms__42826.invoke(permissions.clj:28)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.permissions$fn__42844$check_query_permissions_STAR___42849$fn__42855.invoke(permissions.clj:40)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.permissions$fn__42844$check_query_permissions_STAR___42849.invoke(permissions.clj:34)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__41503.invoke(cumulative_aggregations.clj:57)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.resolve_joins$resolve_joins$fn__43430.invoke(resolve_joins.clj:184)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.limit$limit$fn__42138.invoke(limit.clj:19)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__46195.invoke(results_metadata.clj:87)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.format_rows$format_rows$fn__42126.invoke(format_rows.clj:76)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.add_dimension_projections$add_remapping$fn__38215.invoke(add_dimension_projections.clj:232)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__38866.invoke(add_source_metadata.clj:107)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__43480.invoke(resolve_source_table.clj:46)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__38703.invoke(add_row_count_and_status.clj:16)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.driver_specific$process_query_in_context$fn__41578.invoke(driver_specific.clj:12)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.resolve_driver$resolve_driver$fn__43094.invoke(resolve_driver.clj:22)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.store$initialize_store$fn__46220$fn__46221.invoke(store.clj:11)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.store$do_with_store.invoke(store.clj:40)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.store$initialize_store$fn__46220.invoke(store.clj:10)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.async$async__GT_sync$fn__37366.invoke(async.clj:23)"
Feb 24 13:51:53 kevdev48 java[1812]:   "query_processor.middleware.async_wait$runnable$fn__40619.invoke(async_wait.clj:89)"),
Feb 24 13:51:53 kevdev48 java[1812]:  :query
Feb 24 13:51:53 kevdev48 java[1812]:  {:type "native",
Feb 24 13:51:53 kevdev48 java[1812]:   :native
Feb 24 13:51:53 kevdev48 java[1812]:   {:query
[...]
Feb 24 13:51:53 kevdev48 java[1812]:    :template-tags
Feb 24 13:51:53 kevdev48 java[1812]:    {:dateFrom {:id "6c50bd3d-ec82-88ea-81b8-eb6c259761d0", :name "dateFrom", :display-name "Datum von", :type "date", :default "2018-10-01", :required true},
Feb 24 13:51:53 kevdev48 java[1812]:     :dateTo {:id "16e2c97d-beca-e5e8-ae99-e0d116fd3f4a", :name "dateTo", :display-name "Datum  bis", :type "date", :default "2019-12-31", :required true},
Feb 24 13:51:53 kevdev48 java[1812]:     :gutschriftVorhanden {:id "c8f0b55a-0278-a7ae-df3b-2e56fa39f78e", :name "gutschriftVorhanden", :display-name "Gutschrift zu Retoure vorhanden (Ja/Nein)", :type "text"},
Feb 24 13:51:53 kevdev48 java[1812]:     :quantityBalanced {:id "ff645f67-e499-0b4c-b165-5b05a17d4935", :name "quantityBalanced", :display-name "Anzahl Teile ausgeglichen (Ja/Nein)", :type "text"},
Feb 24 13:51:53 kevdev48 java[1812]:     :netsumBalanced {:id "b4ef0b0c-8f20-79da-5158-484ee8505021", :name "netsumBalanced", :display-name "Wert ausgeglichen (Ja/Nein)", :type "text"},
Feb 24 13:51:53 kevdev48 java[1812]:     :treshold {:id "976ca134-94a7-9c11-fc5d-c88967a75a02", :name "treshold", :display-name "Toleranz für Wertausgleich", :type "number"}}},
Feb 24 13:51:53 kevdev48 java[1812]:   :parameters
Feb 24 13:51:53 kevdev48 java[1812]:   [{:type "date/single", :target ["variable" ["template-tag" "dateFrom"]], :value "2018-10-01"}
Feb 24 13:51:53 kevdev48 java[1812]:    {:type "date/single", :target ["variable" ["template-tag" "dateTo"]], :value "2019-12-31"}
Feb 24 13:51:53 kevdev48 java[1812]:    {:type "category", :target ["variable" ["template-tag" "quantityBalanced"]], :value "Ja"}],
Feb 24 13:51:53 kevdev48 java[1812]:   :async? true,
Feb 24 13:51:53 kevdev48 java[1812]:   :middleware {:add-default-userland-constraints? true, :userland-query? true},
Feb 24 13:51:53 kevdev48 java[1812]:   :info
Feb 24 13:51:53 kevdev48 java[1812]:   {:executed-by 21,
Feb 24 13:51:53 kevdev48 java[1812]:    :context :ad-hoc,
Feb 24 13:51:53 kevdev48 java[1812]:    :card-id nil,
Feb 24 13:51:53 kevdev48 java[1812]:    :nested? false,
Feb 24 13:51:53 kevdev48 java[1812]:    :query-hash [83, 48, 77, -51, -118, -105, -54, 113, 59, -12, 83, 86, 17, 53, 84, 11, 68, -23, 76, 108, 28, 104, 32, -18, -34, 94, -47, 16, 112, -122, -126, -98]},
Feb 24 13:51:53 kevdev48 java[1812]:   :constraints {:max-results 10000, :max-results-bare-rows 2000}},
Feb 24 13:51:53 kevdev48 java[1812]:  :ex-data
Feb 24 13:51:53 kevdev48 java[1812]:  {:required-permissions #{"/db/12/native/"},
Feb 24 13:51:53 kevdev48 java[1812]:   :actual-permissions
Feb 24 13:51:53 kevdev48 java[1812]:   #{"/db/18/" "/collection/63/read/" "/collection/55/read/" "/collection/56/read/" "/db/14/schema//table/1286/" "/collection/118/read/" "/collection/root/read/" "/collection/82/read/"
Feb 24 13:51:53 kevdev48 java[1812]:     "/db/12/schema/" "/collection/62/read/" "/collection/33/" "/collection/51/read/" "/collection/73/read/" "/collection/84/read/" "/collection/105/read/" "/collection/52/read/"
Feb 24 13:51:53 kevdev48 java[1812]:     "/db/14/schema//table/1291/" "/db/14/schema//table/1314/" "/collection/100/read/" "/collection/69/read/" "/collection/68/read/" "/collection/114/read/" "/db/16/schema//" "/collection/67/read/"},
Feb 24 13:51:53 kevdev48 java[1812]:   :permissions-error? true}}
Feb 24 13:51:53 kevdev48 java[1812]:
Feb 24 13:51:53 kevdev48 java[1812]: 02-24 13:51:53 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 198,6 ms (9 DB calls) Jetty threads: 2/50 (5 idle, 0 queued) (192 total active threads) Queries in flight: 0
```
It fails because it is a new native SQL question, which only admins can create.

**To Reproduce**
1. Create a native SQL query
2. Run it
3. Change a parameter
4. Execute the query again
5. A new Question is created

**Expected behavior**
The parameter gets used in the existing question

**Screenshots**
https://streamable.com/x2ohl

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_201-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_201",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.201-b09",
    "os.name": "Linux",
    "os.version": "4.12.14-lp150.12.19-default",
    "user.language": "de",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres",
      "firebird",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.2.14"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.2",
      "date": "2020-02-04",
      "branch": "release-0.34.x",
      "hash": "dab738c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

- Your browser and the version: Chrome 79.0.3945.130 / Firefox 73.0
- Your operating system: Ubuntu 18.04.4 LTS / Windows Server 2008 R2 Datacenter
- Your databases: MS SQL
- Metabase version: 0.34.2
- Metabase hosting environment: .jar file on OpenSuse Linux
- Metabase internal database:Postgres

**Severity**
Our users can't use parameters for one query

**Additional context**
Like I said in the description we are using a lot of fancy MSSQL specific syntax stuff like temp tables, I will try to narrow down the cause of this.

**Comment by Nikos410** [comment] 2020-02-24 13:11
This might be a duplicate of #11225

**Comment by flamber** [comment] 2020-02-24 14:37
Hi @Nikos410 
Yes, it looks like a duplicate of #11225, but I still cannot reproduce this. I can see the problem in the video, so something is definitely wrong, but it helps to be able to reproduce when fixing the issue.
Can you explain your permission setup of the user? Admin > Permissions
And if possible, can you give steps to reproduce with Sample Dataset?
Referencing the error in English: `You do not have permissions to run this query`

**Comment by Nikos410** [comment] 2020-02-24 22:05
Hi @flamber , I don't think this is a permissions problem. The error "You do not have permissions to run this query" just occurs because our users can only run premade native queries that are in specific collections, and the "new question" is, well, new and not in any collection.

The problem that a new question is sometimes created happens using my admin user as well, and I think I might have found a few hints what might be the cause of this. 

I've taken a few looks at what exactly the api call to /query returns and after breaking down the query to a single selected column I've noticed that the column doesn't always have the same base type:

request A:
```JSON
{
	[...]
	"data": {
		[...]
		"cols": [{
				"name": "someId",
				"display_name": "someId",
				"base_type": "type/Integer",
				"source": "native",
				"field_ref": ["field-literal", "someId", "type/Integer"]
			}
		],
		"results_metadata": {
			"checksum": "SbSlowsxn+XkAH8OhEajsQ==",
			"columns": [{
					"name": "someId",
					"display_name": "someId",
					"base_type": "type/Integer",
					"special_type": null,
					"fingerprint": {
						"global": {
							"distinct-count": 81,
							"nil%": 0.9185
						},
						"type": {
							"type/Number": {
								"min": 308081.0,
								"max": 322500.0,
								"avg": 314896.245398773,
								"sd": 4504.659283506749,
								"q1": 309381.1606741985,
								"q3": 317683.4375
							}
						}
					}
				}
			]
		},
		"insights": null,
		"rows_truncated": 2000,
		"results_timezone": "Europe/Berlin"
	}
}
```

request B (with different parameter values):
```JSON
{
	[...]
	"data": {
		[...]
		"cols": [{
				"name": "someId",
				"display_name": "someId",
				"base_type": "type/*",
				"source": "native",
				"field_ref": ["field-literal", "someId", "type/*"]
			}
		],
		"results_metadata": {
			"checksum": "pQKurOWnOO//g+pZYJgdfw==",
			"columns": [{
					"name": "someId",
					"display_name": "someId",
					"base_type": "type/*",
					"special_type": null,
					"fingerprint": {
						"global": {
							"distinct-count": 22,
							"nil%": 0.9561717352415027
						}
					}
				}
			]
		},
		"insights": null,
		"results_timezone": "Europe/Berlin"
	}
}
```

I don't have the slightest clue why that changes, but it seems like metabase starts a new question as soon as the `base_type` of any column changes.  I've uploaded the full query downloads for both queries here: http://gist.github.com/Nikos410/4078ca7948dd3abe05f09e169e3228f0 maybe that helps. If you have any questions, feel free to ask!

**Comment by urkle** [comment] 2020-02-25 16:04
The behavior I am seeing is I have the SQL query configured to visualize as a pivot table. And when you switch from the pivot view to the raw view it switches to an adhoc new question.

**Comment by Nikos410** [comment] 2020-02-26 10:24
@flamber Alright, I was finally able to reliably reproduce this issue with the sample dataset:

Native SQL question:
```SQL
select 
    discount
from orders
where {{onlyNulls}} not like 'y'
    or discount is null
```

Variable configuration:
![Screenshot from 2020-02-26 11-21-41](https://user-images.githubusercontent.com/20876882/75335663-1e947b80-588a-11ea-8076-09539f474ac0.png)

1.  Save the question somewhere and run it using the parameter value 'y' 
2. Run it again using the parameter value 'n'
3. A new question gets created

**Comment by Nikos410** [comment] 2020-02-26 10:47
Taking a look at what `/query` returns again (limited to the first 4 values):

With parameter y:
```
{
	"database_id": 1,
	"started_at": "%now",
	"json_query": {
		"constraints": {
			"max-results": 10000,
			"max-results-bare-rows": 2000
		},
		"type": "native",
		"middleware": {
			"userland-query?": true
		},
		"native": {
			"template-tags": {
				"onlyNulls": {
					"id": "bb402e8e-f9cb-22af-6bdc-020517522993",
					"name": "onlyNulls",
					"display-name": "onlyNulls (y/n)",
					"type": "text",
					"required": true,
					"default": "y"
				}
			},
			"query": "select \n    top 4 discount\nfrom orders\nwhere {{onlyNulls}} not like 'y'\n    or discount is null"
		},
		"database": 1,
		"parameters": [{
				"type": "category",
				"target": ["variable", ["template-tag", "onlyNulls"]],
				"value": "y"
			}
		],
		"async?": true,
		"cache-ttl": null
	},
	"average_execution_time": null,
	"status": "completed",
	"context": "question",
	"row_count": 4,
	"running_time": 14,
	"data": {
		"rows": [[null], [null], [null], [null]],
		"native_form": {
			"query": "select \n    top 4 discount\nfrom orders\nwhere 'y' not like 'y'\n    or discount is null",
			"params": null
		},
		"cols": [{
				"name": "DISCOUNT",
				"display_name": "DISCOUNT",
				"base_type": "type/*",
				"source": "native",
				"field_ref": ["field-literal", "DISCOUNT", "type/*"]
			}
		],
		"results_metadata": {
			"checksum": "Mm/neNCFR+9/YJp3fZocDw==",
			"columns": [{
					"name": "DISCOUNT",
					"display_name": "DISCOUNT",
					"base_type": "type/*",
					"special_type": null,
					"fingerprint": {
						"global": {
							"distinct-count": 1,
							"nil%": 1.0
						}
					}
				}
			]
		},
		"insights": null,
		"results_timezone": "Europe/Berlin"
	}
}
```

With parameter n:
```
{
	"database_id": 1,
	"started_at": "%now",
	"json_query": {
		"constraints": {
			"max-results": 10000,
			"max-results-bare-rows": 2000
		},
		"type": "native",
		"middleware": {
			"userland-query?": true
		},
		"native": {
			"template-tags": {
				"onlyNulls": {
					"id": "bb402e8e-f9cb-22af-6bdc-020517522993",
					"name": "onlyNulls",
					"display-name": "onlyNulls (y/n)",
					"type": "text",
					"required": true,
					"default": "y"
				}
			},
			"query": "select \n    top 4 discount\nfrom orders\nwhere {{onlyNulls}} not like 'y'\n    or discount is null"
		},
		"database": 1,
		"parameters": [{
				"type": "category",
				"target": ["variable", ["template-tag", "onlyNulls"]],
				"value": "n"
			}
		],
		"async?": true,
		"cache-ttl": null
	},
	"average_execution_time": null,
	"status": "completed",
	"context": "question",
	"row_count": 4,
	"running_time": 14,
	"data": {
		"rows": [[null], [null], [6.416679208849759], [null]],
		"native_form": {
			"query": "select \n    top 4 discount\nfrom orders\nwhere 'n' not like 'y'\n    or discount is null",
			"params": null
		},
		"cols": [{
				"name": "DISCOUNT",
				"display_name": "DISCOUNT",
				"base_type": "type/Float",
				"source": "native",
				"field_ref": ["field-literal", "DISCOUNT", "type/Float"]
			}
		],
		"results_metadata": {
			"checksum": "/wQRFxJ5rlhyN6OAL5DUqQ==",
			"columns": [{
					"name": "DISCOUNT",
					"display_name": "DISCOUNT",
					"base_type": "type/Float",
					"special_type": "type/Discount",
					"fingerprint": {
						"global": {
							"distinct-count": 2,
							"nil%": 0.75
						},
						"type": {
							"type/Number": {
								"min": 6.416679208849759,
								"max": 6.416679208849759,
								"avg": 6.416679208849759,
								"sd": null,
								"q1": 6.416679208849759,
								"q3": 6.416679208849759
							}
						}
					}
				}
			]
		},
		"insights": null,
		"results_timezone": "Europe/Berlin"
	}
}
```

The only difference I can spot is the type of the discount column. It seems like metabase cannot determine the type if only nulls are returned. Why would that cause metabase to start a new question?

**Comment by flamber** [comment] 2020-02-26 11:54
@Nikos410 Excellent information! And with step to reproduce in Sample Dataset :tada: 
I have a feeling I've seen this before, but I need to search a bit more. For now I'm just tagging.

@urkle Not the same issue. I've created one for you - #11994 - upvote by clicking :+1: on the first post

**Comment by Nikos410** [comment] 2020-03-06 08:35
@walterl Yes, it looks like the issue is fixed! 

I tried the simple sample dataset question as well as the huge SQLServer one we first discovered this issue on, both seem to work correctly now.

Thanks for the great work!

**Comment by walterl** [comment] 2020-03-06 13:30
Thanks for confirming, @Nikos410 :slightly_smiling_face:

**Closed by walterl** 2020-03-06 13:30 UTC
Labels: .Already Fixed, Administration/Permissions, Priority:P3, Querying/Native, Querying/Parameters & Variables, Type:Bug
