### ISSUE TITLE
[New Question] Database dropdown won't show list after 13th elements

### ISSUE THREAD

**Issue by ans-4175** [metabase/metabase#8770] opened 2018-10-25 03:23 UTC
### Bugs
I found bug regarding database listing on New Question UI.
I have 15 databases, but only 13 listed out in database dropdown.
Is there something an issue I should called?

<img width="1231" alt="screen shot 2018-10-25 at 10 20 55" src="https://user-images.githubusercontent.com/3961872/47474136-d56c8b80-d83f-11e8-80a5-e57a16faf590.png">
These are 6 last database out of 15.
But only 4 last listed out
<img width="523" alt="screen shot 2018-10-25 at 10 21 26" src="https://user-images.githubusercontent.com/3961872/47474157-e917f200-d83f-11e8-979f-533a6d931acb.png">

- Chrome Version 70.0.3538.67 (Official Build) (64-bit)
- OSX Mojave
- BigQuery Database
- Metabase version: 0.30.4
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

-------

**Comment by kdoh** [comment] 2018-10-25 15:59
I think this looks like a duplicate of #8370 so I'm going to close it to consolidate conversation over there. I'm going to take a look at why this is happening this morning.

**Closed by kdoh** 2018-10-25 15:59 UTC
