### ISSUE TITLE
Pulse cannot retain pivoted result set of a question

### ISSUE THREAD

**Issue by phani538** [metabase/metabase#11641] opened 2020-01-06 19:38 UTC
Hi Team,
I have created a question in metabase using native sql. I ran the query and pivoted the result set and saved the question. When I again open the question its showing the pivoted result set which is good. but, when I referenced the same question in pulse to send the result set , it does not retain the pivoted result set, it simply shows or send the original result set instead of pivoted.

Is there any way to achieve this?. Please help.

**Comment by dacort** [comment] 2020-01-10 17:09
Hi @phani538 - this is likely related to #5493 that mentions all charts get mapped to a few different types. Feel free to upvote that issue - I'll close this as a dupe for now.

**Comment by camsaul** [comment] 2020-01-10 22:52
@dacort if an issue is a duplicate feel free to close it 

Closing as duplicate of #5493

**Closed by camsaul** 2020-01-10 22:52 UTC
Labels: .Duplicate, Type:Bug
