### ISSUE TITLE
Enhancement: Organizations

### ISSUE THREAD

**Issue by tomkanjam** [metabase/metabase#1399] opened 2015-10-29 12:53 UTC
I would like to create organizations, to which users can be added, in order to manage access to databases, queries, dashboards and so on.

**Comment by mazameli** [comment] 2016-03-14 21:58
This seems like a completely reasonable request, though not an insignificant amount of effort. I think we'll want to revisit this later this year. Any thoughts, @salsakran?

**Comment by salsakran** [comment] 2016-08-05 22:48
this is being done in #3087

**Comment by camsaul** [comment] 2016-09-22 02:23
I'm going to go ahead and close this as a duplicate of #3362. @tomkanjam we're working on shipping a permissions framework with groups/roles for our upcoming release.

**Closed by camsaul** 2016-09-22 02:23 UTC
Labels: Duplicate, Proposal
