### ISSUE TITLE
Native Query in metabase 2000 row limitation

### ISSUE THREAD

**Issue by mgarv** [metabase/metabase#14454] opened 2021-01-19 19:42 UTC
Row limitation truncated to 2000 rows for native query in metabase.  Are there any work arounds for this. 

I wrote a native query to make a timeseries line graph for the past 30 days, by hour for each client.  X axis is hours, and Y axis is Total and legend is clientname.  However the x axis is truncated, it will only show up to 2000 records.  

Is there a work around in the setup of metabase or environment settings to increase this limit?

Thank you.

**Comment by flamber** [comment] 2021-01-19 20:04
Duplicate of #12729 and currently no workaround for hardcoded limits #4564

**Closed by flamber** 2021-01-19 20:04 UTC
Labels: .Needs Triage, Type:Question
