### ISSUE TITLE
Columns in the order by list must be unique

### ISSUE THREAD

**Issue by ansutung** [metabase/metabase#44722] opened 2024-06-26 02:54 UTC
### Describe the bug

When using "Summarize" and "Sort", there is an error that generates a field twice, causing a conflict.
Error: "A column has been specified more than once in the order by list. Columns in the order by list must be unique."

![image](https://github.com/metabase/metabase/assets/26163387/aeaee6d0-1cfa-41c3-9b0f-be6210dcbee2)

### Information about your Metabase installation

```JSON
Metabase version: v0.50.7
```

### Severity

For the time being, I need to go back and edit the Questions, removing the Sort section.

**Comment by lbrdnk** [comment] 2024-06-26 08:33
Thanks for the report. This issue is a potential duplicate of https://github.com/metabase/metabase/issues/44653. I'll verify that when I'll be closing the linked issue.

**Comment by lbrdnk** [comment] 2024-06-27 19:22
As mentioned before, it seems that scenario here is same as in https://github.com/metabase/metabase/issues/44653, ie. attempt to sort by breakout field of a question that has model as a source. That's been fixed by https://github.com/metabase/metabase/pull/44740 -- closing.

**Closed by lbrdnk** 2024-06-27 19:22 UTC
Labels: Type:Bug, Priority:P1, Querying/Processor, .Team/QueryProcessor
