### ISSUE TITLE
Support for reading datasets from other projects in BQ

### ISSUE THREAD

**Issue by farmdawgnation** [metabase/metabase#13120] opened 2020-08-14 20:56 UTC
**Is your feature request related to a problem? Please describe.**

When using BigQuery, it's possible for a service account to originate from one project, but have access to BigQuery datasets from another. For example, projects can read from the `bigquery-public-data` project, but don't always have permissions there. (E.g. can't create jobs in that project.) Currently, the Dataset ID prevents you from prefixing the Dataset name with a project identifier, making it impossible to use these.

**Describe the solution you'd like**

The Dataset Identifier should permit using a project id prefix.

**Describe alternatives you've considered**

N/A

**How important is this feature to you?**

I'm using this to do analysis of COVID-19 Data in BigQuery. In all honesty, I can find another solution other than Metabase to do this, but I'd rather not. So being unable to read the public datasets is a bit of a dealbreaker for me.

**Additional context**

N/A

**Comment by flamber** [comment] 2020-08-14 21:07
Hi @farmdawgnation Sounds like a duplicate of #2273 - upvote by clicking :+1: on the first post. Perhaps it will be possible to get around that limitation now with the new Service Accounts.

**Closed by flamber** 2020-08-14 21:07 UTC
Labels: .Needs Triage, Type:New Feature
