### ISSUE TITLE
[Click Behavior] cannot use hidden columns for column mappings

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#14417] opened 2021-01-15 02:38 UTC
Assume I have a table like below in a dashboard.
```
col1   col2  col3(hidden)
a1     b1     c1
a2     b2     c2
a3     b3     c3
```
I want to setup click behavior for col2 to take me to a saved question, but in addition to col2 I want to use col3 (which is hidden) in the mappings as well. Currently only visible columns can be used in the column mappings.

Since we can assign dashboard filters to hidden columns of cards, I think it should be possible to use hidden columns in column mapping of click behavior as well.

v .37.5

**Comment by flamber** [comment] 2021-01-15 09:31
Duplicate of #13927

**Closed by flamber** 2021-01-15 09:31 UTC
Labels: .Needs Triage, Type:Bug
