### ISSUE TITLE
Public Dashboards do not display on IE11 if there are too many cards vertically.

### ISSUE THREAD

**Issue by cetra3** [metabase/metabase#5434] opened 2017-07-06 07:31 UTC
This is a weird one.  If you have a public dashboard, and that dashboard has questions that are below a certain row size then it fails to render in Internet Explorer 11 and is blank.

- Browser: IE11 (Using [Modern.ie](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/))
- Metabase version: `0.24.2`

### Steps to Replicate

* As an Admin, enable Public Sharing
* Create a Question, any Question 
* Add that Question to a dashboard
* Streeeeetch that question so it occupies at least 11 rows.  But keep going if you are feeling adventurous.  You can also move the question card down to the end, and it will do the same
* Publicly Share the dashboard
* Navigate to the URL in IE11
* Notice that is is blank

Note: You can sometimes trick it into showing if you resize the window.  It's a bit temperamental though, so go easy on the poor thing.

#### What you should see:

![dashboard-working](https://user-images.githubusercontent.com/6415435/27900094-09e06a30-626c-11e7-9baa-a163bd721be7.png)

#### What you do see:

![dashboard-broken](https://user-images.githubusercontent.com/6415435/27900227-a4a5443c-626c-11e7-9677-9ac14b80e943.png)

**Comment by eneroth** [comment] 2017-07-20 10:29
Over here, the issue seems to be remain regardless whether public sharing is turned on or off.

**Comment by lexnat187** [comment] 2017-07-20 10:39
The problem is not limited to publicly shared dashboards, it also occurs with embedded dashboards using the secret key signing method.

I have confirmed that once you hit 11 rows on an embedded dashboard it stops rendering in IE 11

**Comment by mtucker** [comment] 2017-09-25 15:38
Experiencing the same issue, more detail here: https://github.com/metabase/metabase/issues/5965

Although, I have not found reducing the number of row in the dashboard has any effect.

**Comment by mtucker** [comment] 2017-09-25 18:43
Check that, I am seeing the behavior where the height of the dashboard affects rendering.

It seems that if the dashboard's height exceeds the available height of the window or iFrame, the dashboard is not being rendered in IE11. Same behavior on embed and public link.

**Comment by mtucker** [comment] 2017-09-25 22:43
More info and a possible workaround here: https://github.com/metabase/metabase/issues/5965

**Comment by jornh** [comment] 2018-08-19 20:10
@cetra3 and @lexnat187 the fix mentioned above got released as part of v0.30.0. Would be good to know if that fixes the issue for you!

A good starting point for planning to go to v0.30 - as it contains quite some UI changes etc. is 
https://metabase.com/blog/before-upgrading-to-0.30/index.html#before-you-upgrade

**Comment by jlisyc** [comment] 2018-11-28 11:44
related https://github.com/metabase/metabase/issues/9038

**Comment by flamber** [comment] 2021-11-08 18:23
Closing, since Metabase dropped support for IE11 in version 0.40
https://www.metabase.com/blog/Metabase-0.40/index.html#upgrade-now

**Closed by flamber** 2021-11-08 18:23 UTC
Labels: Type:Bug, .Won't Fix, Priority:P3, Reporting/Dashboards, Browser:IE
