### ISSUE TITLE
"Deselect All" instead of/in addition to "Select All" in notebook

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#10668] opened 2019-08-21 21:17 UTC
In Notebooks by default all columns are selected:
![Untitled](https://user-images.githubusercontent.com/15974735/63469002-0563cb80-c41e-11e9-888f-fa487222622f.png)

So having a "Deselect all" option is more needed than the current "Select All" option.

**Comment by flamber** [comment] 2019-08-21 21:20
Hi @vvaezian Looks like a duplicate of #10460

**Closed** 2019-08-21 21:33 UTC
Labels: Duplicate, Type:New Feature
