### ISSUE TITLE
Error with overriding default date filter for csv report download

### ISSUE THREAD

**Issue by pdiniz13** [metabase/metabase#3704] opened 2016-10-31 22:04 UTC
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: Chrome Firefox
- Your operating system: OSX, Windows 10
- Your databases: MySQL
- Metabase version: (e.x. 0.20.3)
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

- *Repeatable steps to reproduce the issue*
Create a card with a default date range. One the card is saved change the date range and press refresh, try downloading the csv. The csv is being downloaded with the default date range and not with the date range selected by the user.

**Comment by ethier** [comment] 2016-11-03 19:14
We're experiencing the same issue.

Bugs

If you're filing an issue about a bug please include as much information
as you can including the following.

Your browser and the version: Chrome Firefox

Your operating system: OSX, Windows 10

Your databases: PostgreSQL

Metabase version: (e.x. 0.20.3)

Metabase hosting environment: ElasticBeanstalk

Metabase internal database: Postgres

Repeatable steps to reproduce the issue
Create a card with a default date range. One the card is saved change the date range and press refresh, try downloading the csv. The csv is being downloaded with the default date range and not with the date range selected by the user.

**Comment by salsakran** [comment] 2016-11-07 19:11
dupe of  #3695 

Noting you there.

**Comment by salsakran** [comment] 2016-11-07 19:23
Oops. disregard.

**Comment by tlrobinson** [comment] 2016-11-17 21:04
Duplicate of #3695

**Closed by tlrobinson** 2016-11-17 21:04 UTC
Labels: Bug, Parameters/Variables
