### ISSUE TITLE
Permissions graph edit page trying to save invalid combo of native read + no data access

### ISSUE THREAD

**Issue by freakinruben** [metabase/metabase#4280] opened 2017-02-01 09:15 UTC
### Summary

I can't seem to change the permissions of a group when I try to revoke the groups permission on some of the tables. On screen nothing happens, the inspector shows the server gave a 500 response though.

### Info

- Browser: Chrome 55
- OS: Mac OS X 10.11.6
- DB: Postgres 9.6
- Metabase Version: 0.22.1
- Metabase hosting: Docker/GCE
- Metabase int. db: postgres

### Details

Error: `Input to update-graph! does not match schema: [(named {:groups {3 {2 (not (\"DB permissions with a valid combination of values for :native and :schemas\" a-clojure.lang.PersistentArrayMap))}}} new-graph)]`

It's PUTting to: https://mymetabase.com/api/permissions/graph
Request payload: 
```json
{ "groups" : { "1" : { "2" : { "native" : "none",
              "schemas" : "none"
            } },
      "2" : { "2" : { "native" : "write",
              "schemas" : "all"
            } },
      "3" : { "2" : { "native" : "read",
              "schemas" : "none"
            } },
      "5" : { "2" : { "native" : "read",
              "schemas" : { "public" : { "10" : "all",
                      "11" : "all",
                      "12" : "all",
                      "13" : "all",
                      "14" : "all",
                      "15" : "none",
                      "16" : "all",
                      "5" : "all",
                      "6" : "all",
                      "7" : "all",
                      "8" : "none",
                      "9" : "none"
                    } }
            } }
    },
  "revision" : 13
}
```

Response:
```json
{ "error" : [ "schema.utils.NamedError@16adfbd5" ],
  "message" : "Input to update-graph! does not match schema: [(named {:groups {3 {2 (not (\"DB permissions with a valid combination of values for :native and :schemas\" a-clojure.lang.PersistentArrayMap))}}} new-graph)]",
  "schema" : [ { "name" : "new-graph",
        "optional?" : false,
        "schema" : { "groups" : { "schema.core.Constrained@c32121e4" : { "schema.core.Constrained@c32121e4" : { "post-name" : "DB permissions with a valid combination of values for :native and :schemas",
                        "postcondition" : "metabase.models.permissions$check_native_and_schemas_permissions_allowed_together@ddaa850",
                        "schema" : { "schema.core.OptionalKey@80fab393" : { "vs" : [ "read",
                                    "write",
                                    "none"
                                  ] },
                            "schema.core.OptionalKey@e0ca6a71" : { "schemas" : [ { "vs" : [ "all",
                                          "none"
                                        ] },
                                    { "schema.core.Maybe@53dddfc9" : { "schemas" : [ { "vs" : [ "all",
                                                    "none"
                                                  ] },
                                              { "schema.core.Constrained@c32121e4" : { "vs" : [ "all",
                                                        "none"
                                                      ] } }
                                            ] } }
                                  ] }
                          }
                      } } },
            "revision" : { "p?" : "clojure.core$integer_QMARK_@67693e21",
                "pred-name" : "integer?"
              }
          }
      } ],
  "stacktrace" : [ "models.permissions$fn__17968$update_graph_BANG___17977.invoke(permissions.clj:473)",
      "api.permissions$fn__32152$fn__32154.invoke(permissions.clj:72)",
      "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:222)",
      "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:219)",
      "api.permissions$fn__32152.invokeStatic(permissions.clj:60)",
      "api.permissions$fn__32152.invoke(permissions.clj:60)",
      "middleware$enforce_authentication$fn__30864.invoke(middleware.clj:84)",
      "api.routes$fn__32815.invokeStatic(routes.clj:56)",
      "api.routes$fn__32815.invoke(routes.clj:56)",
      "routes$fn__32851.invokeStatic(routes.clj:24)",
      "routes$fn__32851.invoke(routes.clj:24)",
      "middleware$log_api_call$fn__30952$fn__30954.invoke(middleware.clj:275)",
      "db$_do_with_call_counting.invokeStatic(db.clj:406)",
      "db$_do_with_call_counting.invoke(db.clj:400)",
      "middleware$log_api_call$fn__30952.invoke(middleware.clj:274)",
      "middleware$add_security_headers$fn__30911.invoke(middleware.clj:209)",
      "middleware$bind_current_user$fn__30868.invoke(middleware.clj:104)"
    ],
  "type" : "schema.core/error",
  "value" : [ { "groups" : { "1" : { "2" : { "native" : "none",
                    "schemas" : "none"
                  } },
            "2" : { "2" : { "native" : "write",
                    "schemas" : "all"
                  } },
            "3" : { "2" : { "native" : "read",
                    "schemas" : "none"
                  } },
            "5" : { "2" : { "native" : "read",
                    "schemas" : { "public" : { "10" : "all",
                            "11" : "all",
                            "12" : "all",
                            "13" : "all",
                            "14" : "all",
                            "15" : "none",
                            "16" : "all",
                            "5" : "all",
                            "6" : "all",
                            "7" : "all",
                            "8" : "none",
                            "9" : "none"
                          } }
                  } }
          },
        "revision" : 13
      } ]
}
```

Server logs output:
```
02-01 08:59:58 WARN models.permissions :: Invalid DB permissions: if you have readonly native query access, you must also have data access.
02-01 08:59:59 ERROR metabase.middleware :: PUT /api/permissions/graph 500 (2 ms) (0 DB calls)
{:type :schema.core/error,
.... etc, same as above
```

**Comment by camsaul** [comment] 2017-03-01 22:58
Sounds like the UI is trying to let you do something invalid, hence the error message:

> if you have readonly native query access, you must also have data access.

(That error message is an intentional validation error, and I've already fixed the error handling issue here so this now returns a 400 instead of a 500).

I don't know exactly where we decided upon the rule but if you have read access for SQL queries you have to also have to have data access .

**Comment by freakinruben** [comment] 2017-03-20 13:25
The rule sounds ok to me. Right now it's mostly frustrating that I get the `500` error for each change that I want to make to the permissions, resulting in just adding all users to the adminstrators group..
In which version should the changes that you mention be released?

**Comment by mazameli** [comment] 2017-04-03 20:43
I tried this on a Postgres DB on the master branch. I'm not seeing 500 errors (since evidently @camsaul fixed those), or those server log lines @freakinruben mentioned, but I am able to get the permissions table into the weird state outlined in #4273.

Steps:
- Set a group's SQL queries access to `view`
- Set their data access to that same DB to `limited`
- Drill into that DB and set that group's access for each table in the DB to `no access`
- Save changes
- Changes should save, but a weird blue-gray state should be present in the `SQL queries` cell

**Comment by attekei** [comment] 2017-04-25 00:35
I just confirmed that after following the steps @mazameli described (both in the comment above and in #4273), and trying to change permissions after that, results to a similar error.

I'm trying to fix this #4847 but I'm still concerned that it maybe doesn't cover all scenarios. I would be very interested see what kind of situation has caused this for others. For example a screenshot of the whole permissions page before trying to unsuccessfully change permissions would be super helpful.

**Comment by AdamLandis** [comment] 2017-04-25 17:17
coming from: https://github.com/metabase/metabase/issues/4807#issuecomment-296841101

I'm getting something similar. But I couldn't seem to manage any new permission changes to be saved so I was totally stuck.

In hindsight I think I somehow got the All Users table into an invalid situation (no tables deleted) and only by deleting the table with the "Grey Tile" then re-adding databases was I able to re-enable saving changes.

While I'm on this thread, I think adding a new table shouldn't by default add full permissions to "all Users." 

`:error
[(named {:groups {1 {14 (not ("DB permissions with a valid combination of values for :native and :schemas" a-clojure.lang.PersistentArrayMap))}, 3 {14 (not ("DB permissions with a valid combination of values for :native and :schemas" a-clojure.lang.PersistentArrayMap))}}} new-graph)],
:message
"Input to update-graph! does not match schema: [(named {:groups {1 {14 (not (\"DB permissions with a valid combination of values for :native and :schemas\" a-clojure.lang.PersistentArrayMap))}, 3 {14 (not (\"DB permissions with a valid combination of values for :native and :schemas\" a-clojure.lang.PersistentArrayMap))}}} new-graph)]",
:stacktrace
["models.permissions$fn__17135$update_graph_BANG___17144.invoke(permissions.clj:474)"
"api.permissions$fn__33619$fn__33621.invoke(permissions.clj:72)"
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:229)"
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:224)"
"api.permissions$fn__33619.invokeStatic(permissions.clj:60)"
"api.permissions$fn__33619.invoke(permissions.clj:60)"
"middleware$enforce_authentication$fn__34582.invoke(middleware.clj:118)"
"api.routes$fn__34726.invokeStatic(routes.clj:66)"
"api.routes$fn__34726.invoke(routes.clj:66)"
"routes$fn__35781$fn__35782.doInvoke(routes.clj:53)"
"routes$fn__35781.invokeStatic(routes.clj:49)"
"routes$fn__35781.invoke(routes.clj:49)"
"middleware$log_api_call$fn__34681$fn__34683.invoke(middleware.clj:331)"
"middleware$log_api_call$fn__34681.invoke(middleware.clj:330)"
"middleware$add_security_headers$fn__34631.invoke(middleware.clj:245)"
"middleware$bind_current_user$fn__34586.invoke(middleware.clj:138)"
"middleware$maybe_set_site_url$fn__34635.invoke(middleware.clj:268)"]}`

**Comment by attekei** [comment] 2017-05-10 21:25
https://github.com/metabase/metabase/pull/4847 added an extra consistency check to the permissions page UI which hopefully prevents the permissions tree from getting to an invalid state. It is included in the new 0.24 release.

I will close this issue for now, but please report if you're still encountering odd issues with permissions page after updating to 0.24.

**Closed by attekei** 2017-05-10 21:25 UTC
Labels: Admin Panel & Setup, Bug, Permissions, Priority/P1

**Comment by fenichelar** [comment] 2017-05-20 04:04
@attekei I just downloaded Metabase to test it out. I made some permissions changes and now I am unable to set table specific permissions. Using 0.24.

**Comment by attekei** [comment] 2018-01-22 11:51
@GabKlein I'm a little lazy so I'll just copy-paste what I replied to https://github.com/metabase/metabase/issues/5158#issuecomment-303922553: Theoretically you could manually edit the contents of `permissions` table in application database, but the hierarchical nature of permissions settings makes it tricky to do so.

Which version are you using? Others haven't reported similar problems recently.

**Comment by GabKlein** [comment] 2018-01-22 11:56
@attekei Thank you for you reply, I'm using the version 0.27.2. 
Indeed it looks a bit tricky, I have access to the Metabase application tables using PgAdmin. 
Any advise ?

**Comment by attekei** [comment] 2018-01-22 11:58
@GabKlein If possible, could you create a new issue describing how you ended up in that weird state where you aren't able to change the db permissions anymore (and if the permissions UI is behaving in a weird way atm)?

**Comment by GabKlein** [comment] 2018-01-22 12:02
Of course, it is very similar to the others with a 500 in Metabase logs.

In the mean time, can you provide me with a sql statement to truncate + update the permission table? I'm ok to redo all of them.

**Comment by attekei** [comment] 2018-01-22 12:09
@GabKlein Not completely sure, at least you have to keep the root level permission (`object` is `/`) in place. You can wipe some of those more detailed permissions (like `/db/6/schema/`) pretty safely. Better to try to remove a small bit at once (and, of course, have a backup of the current state of the table).

**Comment by GabKlein** [comment] 2018-01-22 12:30
@attekei I've opened a new issue https://github.com/metabase/metabase/issues/6739. 
Basically the section "Saved question" is not presented in the Database list.

**Comment by attekei** [comment] 2018-01-22 13:44
Thanks @GabKlein! 🙂 I'll take a look at it when I have a chance.
