### ISSUE TITLE
Enable Metabot toggle not working in admin slack settings

### ISSUE THREAD

**Issue by jasonmadrid** [metabase/metabase#3112] opened 2016-08-03 17:16 UTC
*  I am using the Chrome browser Version 51.0.2704.103 (64-bit)
*  My computer's OS is Mac OS 10.11.6.
*  I'm running Metabase in Docker and it is using the H2 database.
*  My data is in a mysql database.
*  My Metabase version is 0.19.

We're trying to enable the Slack integration and metabot. I've tried with both a slack test key and with setting up a bot in Slack. Pulses work great, so we know the integration is working to that extent.

However, we can't enable metabot. In the Slack settings panel, the switch is set to 'Disabled' and grayed out. We can't click the slider to enable it.

![cant_enable](https://cloud.githubusercontent.com/assets/2541528/17374778/6c684872-596b-11e6-8b79-984c49201f51.png)

**Comment by jasonmadrid** [comment] 2016-08-04 15:54
In case it helps, we're getting this spammed in our metabase logs:

08-04 15:53:38 ERROR metabase.metabot :: Error connecting websocket: clj-http: status 429
08-04 15:53:39 ERROR metabase.metabot :: Error connecting websocket: clj-http: status 429
08-04 15:53:39 ERROR metabase.metabot :: Error connecting websocket: clj-http: status 429
08-04 15:53:40 ERROR metabase.metabot :: Error connecting websocket: clj-http: status 429
08-04 15:53:41 ERROR metabase.metabot :: Error connecting websocket: clj-http: status 429
08-04 15:53:42 ERROR metabase.metabot :: Error connecting websocket: clj-http: status 429
08-04 15:53:43 ERROR metabase.metabot :: Error connecting websocket: clj-http: status 429
08-04 15:53:44 ERROR metabase.metabot :: Error connecting websocket: clj-http: status 429
08-04 15:53:44 ERROR metabase.metabot :: Error connecting websocket: clj-http: status 429
08-04 15:53:45 ERROR metabase.metabot :: Error connecting websocket: clj-http: status 429
08-04 15:53:46 ERROR metabase.metabot :: Error connecting websocket: clj-http: status 429
08-04 15:53:46 ERROR metabase.metabot :: Error connecting websocket: clj-http: status 429
08-04 15:53:47 ERROR metabase.metabot :: Error connecting websocket: clj-http: status 429

**Comment by jasonmadrid** [comment] 2016-08-04 16:54
I created a new token in Slack and added it to metabase, which stopped the error above.  Upon save I see in the logs:

08-04 16:52:23 INFO metabase.metabot :: Starting MetaBot WebSocket monitor thread...
08-04 16:52:23 DEBUG metabase.middleware :: PUT /api/slack/settings 200 (464 ms) (4 DB calls)
08-04 16:52:23 DEBUG metabase.middleware :: GET /api/session/properties 200 (467 µs) (1 DB calls)
08-04 16:52:23 DEBUG metabase.middleware :: GET /api/setting 200 (242 µs) (1 DB calls)

However, still can't enable metabot in settings.

**Comment by camsaul** [comment] 2016-08-04 19:18
@jasonmadrid 

If you're seeing this line in the logs:

```

**Comment by camsaul** [comment] 2016-08-04 19:20
Actually @metabase/core-developers I'm able to reproduce this on stats. Looks like the Metabase enable/disable switch isn't toggling

**Comment by MrMauricioLeite** [comment] 2016-08-04 20:05
Same is happening here with version 0.19.0


[]'s,

Mauricio R. Leite
(11) 9 4141  2201

2016-08-04 16:20 GMT-03:00 Cam Saül <notifications@github.com>:

**Comment by camsaul** [comment] 2016-08-04 20:18
Seeing a lot of React errors on this page when I run it locally

![screen shot 2016-08-04 at 1 17 00 pm](https://cloud.githubusercontent.com/assets/1455846/17416984/cbe4a2d4-5a45-11e6-8527-32dd1b587691.png)


Also it looks like the toggle in question doesn't have `onChange`/`onClick` handlers

![screen shot 2016-08-04 at 1 16 33 pm](https://cloud.githubusercontent.com/assets/1455846/17416985/cbedf0be-5a45-11e6-9722-a7acf687a214.png)

**Comment by salsakran** [comment] 2016-08-04 21:50
fixed via #3126

**Closed by salsakran** 2016-08-04 21:50 UTC
Labels: Admin Panel & Setup, Bug, Metabot
