### ISSUE TITLE
Area chart visualization bleeds over x axis in chart when axis limit is selected.

### ISSUE THREAD

**Issue by dvanrijswijk** [metabase/metabase#7131] opened 2018-03-15 20:17 UTC
Browser and the version: Firefox Quantum 59.0 (64-bit)
Operating system: Windows 7
Databases: Postgres, 
Metabase version: 0.28.1
Metabase hosting environment: Linux/Ubuntu 16.04
Metabase internal database: Postgres

Steps to reproduce:
Create an area chart, set axis limit to lower bound.
Area chart bleeds over lower bound.

![image](https://user-images.githubusercontent.com/10403194/37488912-5ec50346-286c-11e8-848c-c52cce8a8cb0.png)

**Comment by flamber** [comment] 2020-05-23 16:23
Duplicate of #6547
Fixed by #10396 in 0.32.10
Related #10434

**Closed by flamber** 2020-05-23 16:23 UTC
Labels: Priority:P3, Type:Bug, Visualization/
