### ISSUE TITLE
World map is not on-hover showing names of countries but only 2-letter codes

### ISSUE THREAD

**Issue by atranel** [metabase/metabase#8986] opened 2018-11-20 20:52 UTC
When I visualize world map, it no longer shows names of countries but only 2-letter codes. In version 0.30.4 it was working.
![screenshot_11](https://user-images.githubusercontent.com/42370527/48802229-e4474080-ed0e-11e8-8158-1928dbaf5d4c.png)

**Comment by mariomka** [comment] 2018-11-22 12:03
I have the same issue with a custom region map. Seems like name property does not work.

**Comment by atranel** [comment] 2019-02-20 08:05
Did someone find a way to fix it already? I can do the change and recompile. Customers are complaining about codes :(

**Comment by atranel** [comment] 2019-03-05 09:30
There is a workaround by changing your map and query to use region/country name instead of key/2-letter code etc. I had to use custom World map.
![obrazek](https://user-images.githubusercontent.com/42370527/53795185-b4c0ea80-3f31-11e9-9733-aebe30d9f41d.png)

**Comment by lp-lima** [comment] 2019-03-26 13:54
For me, nothing will work at all. I can't get the hovering functionality working anyhow.

**Comment by flamber** [comment] 2019-03-26 15:13
@lp-lima Sounds like a different issue. Check browser console for errors. Try to make it using Sample Data, might just be an issue with your data. Use the forum for questions and troubleshooting :-)

**Comment by lp-lima** [comment] 2019-03-26 15:37
I filed a different issue, and it was closed in favor of this one: [](https://github.com/metabase/metabase/issues/9125)

I already used the forum, and got no answers on this matter:
https://discourse.metabase.com/t/custom-geojson-map-issues-on-0-31/5042/2


I'm pretty sure my data is alright, since it was working on 0.29...

**Comment by flamber** [comment] 2019-03-26 19:19
@lp-lima 
I cannot reproduce your issue on 0.31.2 - I get the hover.
![Screenshot_00000](https://user-images.githubusercontent.com/1447303/55026982-c3973c00-4fc9-11e9-9236-4c93aa6206fa.png)
But in your issue (#9125), your example of just a single result actually causes an error, which is an existing issue that causes an error on maps, when there's less than 5 results - see #4684
Again, check your browser console and Metabase logs.

**Comment by lp-lima** [comment] 2019-03-28 15:50
Did some checks here. Very odd, I can now get the hover working. Maybe I needed some hard refreshes on my browser. My mistake - I'm sorry.

**Comment by paulrosenzweig** [comment] 2019-08-12 15:21
Fixed in #10065

**Closed by paulrosenzweig** 2019-08-12 15:21 UTC
Labels: Priority:P1, Type:Bug, Visualization/
