### ISSUE TITLE
Filter widget breaks page when typing a value

### ISSUE THREAD

**Issue by Somtom** [metabase/metabase#37492] opened 2024-01-10 09:18 UTC
### Describe the bug

I was trying to filter for a specific ID in a model in the filter widget and then the page crashed.

This seems to be related to a GET `/api/field/:id/search/:id` endpoint returns HTTP 204 no content instead of an empty array.

There is a workaround to just filter on the normal column dropdown in the model table view.

### To Reproduce

I couldn't reproduce it for other models than the one where it broke but here is what I did (more context in the video in our [Slack](https://metaboat.slack.com/archives/C01LQQ2UW03/p1704872831507539))

1. Go to a model page
2. Click on the "Filter" button on the top 
<img width="220" alt="image" src="https://github.com/metabase/metabase/assets/29712801/33308fd0-17a4-476e-9c13-4514d42878cd">

3. Scroll down to the entity id field and start typing 
<img width="813" alt="image" src="https://github.com/metabase/metabase/assets/29712801/5a6acda6-79c9-47ca-8466-b50964edede4">

<img width="656" alt="image" src="https://github.com/metabase/metabase/assets/29712801/2965f023-f86c-49b8-a77f-393ba93600e8">

### Logs

Some logs from the console:
```
TypeError: e.map is not a function or its return value is not iterable
    at Q (utils.ts:33:22)
    at SearchValuePicker.tsx:40:11
    at Object.ig [as useMemo] (react-dom.production.min.js:162:119)
    at t.useMemo (react.production.min.js:25:113)
    at J (SearchValuePicker.tsx:39:19)
    at o6 (react-dom.production.min.js:153:146)
    at iF (react-dom.production.min.js:175:309)
    at l (react-dom.production.min.js:263:406)
    at aH (react-dom.production.min.js:246:265)
    at react-dom.production.min.js:246:194
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.10.201-191.748.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "druid",
      "mysql",
      "postgres",
      "redshift",
      "bigquery-cloud-sdk",
      "mongo",
      "h2",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-01-09",
      "tag": "vUNKNOWN",
      "hash": "30fff3b"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

### Severity

annoying

**Comment by ranquild** [comment] 2024-01-10 12:34
Not enough details in the ticket but one of two things should happen:
- The shouldn't be marked as searchable
- The BE should return an empty array when there are no search results as it does normally

**Comment by piranha** [comment] 2024-01-19 15:43
So the issue here is that the field is of the type uuid, and trying to search on such a field causes an exception internally - since for UUID fields value is mapped to a db type. Casting `%asd%` to an UUID obviously does not make sense and so it fails.

Just returning `[]` in that case is easy, but it solves nothing — the db will never be searched. So I see two ways of proceeding with this: either switching on the front-end to a dropdown with client-side filtering, or actually making search work for UUID fields on the backend. I'm not sure if latter makes a lot of sense with an id field?

@luizarakaki any thoughts?

**Comment by luizarakaki** [comment] 2024-01-25 18:19
For content viewers UUIDs are just long strings and they should be searchable.

Is it possible to "cast" for search purposes? If it is ok, I'd follow this route

**Comment by calherries** [comment] 2024-02-14 12:10
Thomas ran into this again and created another loom: https://www.loom.com/share/63242a2bb5d44c088b2d3643d3d32be0

**Comment by calherries** [comment] 2024-02-14 12:24
I'm not 100% sure this is the same exact bug, but I could recreate the observed behaviour (i.e. the filter widget breaking) with a UUID column in postgres:

```
CREATE TABLE uuid_table (
    uuid_column UUID PRIMARY KEY DEFAULT uuid_generate_v4()
);
INSERT INTO uuid_table (uuid_column)
SELECT uuid_generate_v4()
FROM generate_series(1, 2000);
```

If you sync this table and try to filter on it, the search query reaches an error [here](https://github.com/metabase/metabase/blob/b98fa2b4bb16c10e561a29c8e29d5bcc9dd168ca/src/metabase/driver/postgres.clj#L356-L357), where `value` is `%whateveryousearched%`.

The stack trace looks like this:
```
; Execution error (IllegalArgumentException) at java.util.UUID/fromString1 (UUID.java:280).
; Invalid UUID string: %whateveryousearched%
clj꞉dev.nocommit.scratch꞉> 
java.util.UUID/fromString1 (UUID.java:280)
java.util.UUID/fromString (UUID.java:258)
metabase.driver.postgres/eval170497 (NO_SOURCE_FILE:358)
... (many omitted fn calls)
metabase.driver.sql.query-processor/mbql->native (query_processor.clj:1467)
```

Maybe the solution is to change `[search-values-query](https://github.com/metabase/metabase/blob/b98fa2b4bb16c10e561a29c8e29d5bcc9dd168ca/src/metabase/api/field.clj#L380)` to cast the UUID to a text column before applying the `:contains` expression.

The thing I don't understand about this is, the accounts ID column in postgres has type `:type/Text`, not `:type/UUID`. So this might not be the same bug I'm seeing.

**Comment by calherries** [comment] 2024-02-14 12:29
Thomas made another thread in slack on this issue [here](https://metaboat.slack.com/archives/C05MPF0TM3L/p1707822061007859)

**Comment by piranha** [comment] 2024-02-15 15:36
The problem in question is not that `ID` is an `uuid` field in database - it is a `text` field in fact, but it's because our code tries to convert input to an UUID string (`java.util.UUID/fromString`) and that fails.

**Comment by calherries** [comment] 2024-02-15 16:59
Did you reproduce the problem? If so please leave instructions for the next guy

**Comment by aryaag** [comment] 2024-04-01 06:33
I seem to have found a workaround for whoever is getting this error with UUID fields. 
1. Go to Metabase Admin
2. Go to table metadata 
3. Find the columns of UUID type and click the gear icon next to those columns/fields
4. Under `Filtering on this field`, select `Plain input box`
5. This should prevent metabase from trying to cast it into a UUID.
<img width="1302" alt="Screenshot 2024-04-01 at 12 03 09 PM" src="https://github.com/metabase/metabase/assets/11738285/8ab856da-6eb1-4b6c-89ae-010fcc8a04c0">

**Closed** 2024-07-18 01:13 UTC
Labels: Type:Bug, Priority:P1, Querying/MBQL, .Backend, Querying/Models, .Team/QueryProcessor
