### ISSUE TITLE
Auto-connect all dashboard cards' filter fields from first card

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#15251] opened 2021-03-19 15:19 UTC
**Is your feature request related to a problem? Please describe.**
With a lot of similar cards on a dashboard (e.g. all querying the same table), when one adds a dashboard filter, one has to connect it manually to every card. This is time-consuming and error-prone.

**Describe the solution you'd like**
After connecting the first card's filter, I would like to be prompted to auto-connect the filter on all other cards to the same field (if available). Or have the possibility to connect to all cards in one go from the filter edit pane on the right.

**Describe alternatives you've considered**
Connect all cards manually.

**How important is this feature to you?**
A nice-to-have.

**Additional context**
Often a dashboard has a lot (20+) of cards querying the same or similar table.

**Comment by flamber** [comment] 2021-03-19 15:37
Duplicate of #4767

**Closed by flamber** 2021-03-19 15:37 UTC
Labels: .Needs Triage, Type:New Feature
