### ISSUE TITLE
Wrong psition number in error message during sql execution

### ISSUE THREAD

**Issue by dariusdev** [metabase/metabase#13206] opened 2020-09-04 08:44 UTC
**Describe the bug**
Currently in error message if i make syntax error i receive error position number not the same as line number in editor. It confuses and make error message useless. 

**To Reproduce**
1. Write sql query with some misstype
2. Look at error message position number

**Expected behavior**
Line number in error message should meet edditors line number

**Screenshots**

![image](https://user-images.githubusercontent.com/6444878/92219625-806e1780-eea3-11ea-859f-dc84cce94b0d.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.x. Chrome 52.)
- Your operating system: (e.x. OS X 10.10)
- Your databases: (e.x.  Postgres, )
- Metabase version: (v0.35.4)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking query testing

**Comment by flamber** [comment] 2020-09-04 09:41
Duplicate of #625

**Closed by flamber** 2020-09-04 09:41 UTC
Labels: .Needs Triage, Type:Bug
