### ISSUE TITLE
Search results show the incorrect collection for questions not saved in Our Analytics

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10438] opened 2019-07-31 17:31 UTC
Search result collection badge:

![image](https://user-images.githubusercontent.com/2223916/62233747-0bfea600-b37e-11e9-8205-d5b63dea642f.png)

Actual correct collection indicated on the question detail:

![image](https://user-images.githubusercontent.com/2223916/62233757-115bf080-b37e-11e9-8f4f-23ff2ee95b5e.png)

**Comment by tlrobinson** [comment] 2019-08-08 23:15
@mazameli I'm unable to reproduce this on the latest branch, are you?

**Comment by flamber** [comment] 2019-08-08 23:38
It's working correctly now. I think it was fixed by Cam's large PR #10517

**Comment by tlrobinson** [comment] 2019-08-08 23:47
👍

**Closed by tlrobinson** 2019-08-08 23:47 UTC
Labels: Difficulty:Easy, Organization/Search, Priority:P2, Type:Bug
