### ISSUE TITLE
Displayed table path is not consistent

### ISSUE THREAD

**Issue by Timelessprod** [metabase/metabase#44389] opened 2024-06-19 09:01 UTC
### Describe the bug

When I browse a table from the "Browse" page, then click on the database I want to navigate to, then navigate folders and finally click on a table to view it, the correct path is shown on the top left corner:

<img width="241" alt="Screenshot 2024-06-19 at 10 47 24" src="https://github.com/metabase/metabase/assets/69579602/e3a5b7e4-084f-4842-911a-8ca1714e1a0f">

However if I use the new search box popup to look for the same table, the path shown on the corner is missing the folder(s) name(s) in which the table is located:

<img width="221" alt="Screenshot 2024-06-19 at 10 48 33" src="https://github.com/metabase/metabase/assets/69579602/1c2eee89-9d07-456d-8e0c-3bbd57ff7e0a">

This creates inconsistency and in the case we have a database in which different folders have tables with same names, it's ambiguous to know which table is which.

### To Reproduce

1. Go to Metabase
2. Click on the search box or press Command/Ctrl + K
3. Type the name of table which is in a folder inside a database (not at the root of the database)
4. Click on the result to open the table
5. See the missing folder(s) name(s) on the top left corner

### Expected behavior

I should see the full path of the table just as when I access it via the Browse page.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.11+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.11+9",
    "os.name": "Linux",
    "os.version": "6.1.58+",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-15",
      "tag": "v0.50.5",
      "hash": "48f6978"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Annoying

**Comment by luizarakaki** [comment] 2024-08-12 20:06
@Timelessprod I'm not able to reproduce this. Can you check if this is still happening on the latest release?

**Comment by Timelessprod** [comment] 2024-08-13 07:15
I will check once we will update yes

**Comment by Timelessprod** [comment] 2024-08-19 10:13
@luizarakaki It's still happening on v0.50.20 on my side.

Everytime I have tables pairs like:
- `Database_1/Folder_1/Table_1`
- `Database_1/Folder_2/Table_1`
- ...
- `Database_1/Folder_n/Table_1`

and I start a search from the searchbox, Metabase will list all n tables with just their name (so I can't tell which table is from which folder cf. my feature request https://github.com/metabase/metabase/issues/44388). When I open any of these results from the search popup, Metabase will show the table name as "Database_1 / Table_1" on the top left corner, so I don't know if it's from folder 1 or 2 or 3 ... or n. This means I don't know what data I'm looking at and have to go to browse section and manually find it myself in the end, thus time consuming.

**Comment by rafpaf** [comment] 2024-10-22 15:19
Thanks @Timelessprod for your patience. I'm also struggling to reproduce this issue. I'm using a postgres db with multiple schemas (I'm assuming what you call folders are schemas). The names of the schemas appear next to the table names in the Command Palette (the new search box). When I click a table name in the Command Palette, I next see a page that contains the name of the table, along with the name of its schema. If you're able to share a little more about how your database is configured, I can take a second look.

For now I'm closing this issue, but I'll gladly re-open it later if you can show me more about how this bug arose for you.

**Closed by rafpaf** 2024-10-22 15:19 UTC
Labels: Type:Bug, Priority:P2, .Frontend, .Team/AdminWebapp, Organization/Browse Data

**Comment by Timelessprod** [comment] 2024-10-22 15:34
@rafpaf FYI I am using BigQuery thus the folders are folders not schemas.

Indeed now the search pop up is showing the folder name which helps a lot but I still notice the inconsistency bug on the table name when going via the search pop up or via the browse tab.
