### ISSUE TITLE
Time series charts are off by one day due to timezone differences

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1635] opened 2015-12-04 18:24 UTC
Behold:

When viewing this query as a table, note the values and the dates:
![screen shot 2015-12-04 at 10 20 43 am](https://cloud.githubusercontent.com/assets/2223916/11597498/0127233a-9a71-11e5-8530-cf69da8c7fcc.png)

But when changing the visualization to a time series, the values remain the same, but the dates are shifted over by one:
![screen shot 2015-12-04 at 10 21 06 am](https://cloud.githubusercontent.com/assets/2223916/11597510/109b8572-9a71-11e5-8c87-4f35b98fb3d6.png)

![screen shot 2015-12-04 at 10 23 51 am](https://cloud.githubusercontent.com/assets/2223916/11597524/2670324e-9a71-11e5-99e8-121772d1cb45.png)

Here's the query:
![screen shot 2015-12-04 at 10 21 56 am](https://cloud.githubusercontent.com/assets/2223916/11597538/3a5a19d2-9a71-11e5-9921-7236748e4937.png)

**Comment by agilliland** [comment] 2015-12-04 19:13
Just to add a little clarity, but this is almost certainly related to timezone handling.  We should dig into it a bit more to be sure, but I believe that the sense of time in the charts is not fully aligned with the sense of time in the data.  Small deltas of even just an hour can end up causing this particular issue.

**Comment by robinfrick** [comment] 2016-01-07 16:53
I experience something similar, possibly related.

For me the last day in bar-charts of time series is missing. If I switch to another chart type all days are displayed correctly.

![image](https://cloud.githubusercontent.com/assets/8144392/12176318/472f69b2-b567-11e5-8231-7304bc991f5c.png)
![image](https://cloud.githubusercontent.com/assets/8144392/12176341/61d85936-b567-11e5-8f97-6929aeebb695.png)

**Comment by MartinArens** [comment] 2016-01-21 15:33
+1

**Comment by GSeva** [comment] 2016-01-22 20:08
Something alike is happening with "past 30 days". Received data does not include today, and bar chart visualization is 3 days off. I.e., i'm making this query at 22 of January, largest date in the received dataset is 21 and the last bar in the chart is for 19.

**Comment by camsaul** [comment] 2016-01-22 20:12
FWIW "past 30 days" isn't supposed to include the current day

**Comment by GSeva** [comment] 2016-01-22 20:19
yeah, i assumed it wasn't bug, i commented mainly because of visualization.

**Comment by salsakran** [comment] 2016-01-22 20:21
In general, at day N, `past 30 days` should be date range from N-31 to N-1 inclusive

**Comment by tlrobinson** [comment] 2016-01-31 07:13
I looked into this a little more closely, and I think there are actually 2 issues (excluding the bar chart being cut off, and the fact that we don't communicate precisely what `past 30 days` means)

1. The frontend does not yet use the "report timezone" setting at all, therefore if your local machine/browser has a different timezone than the "report timezone" things will almost certainly be off. 
2. The backend always returns timestamps with the UTC "Z" designator (which the browser correctly parses as UTC), however it returns the incorrect timestamps for groupings other than "hour". e.x. assuming the report timezone and browser are PST (UTC -8), when grouping by day the row for January 30, 2016 is returned as `2016-01-30T00:00:00.000Z` (*even if the report timezone is not UTC!*) which gets parsed by the browser as `Fri Jan 29 2016 16:00:00 GMT-0800 (PST)` then displayed as January 29, 2016. Note that fixing 1 alone won't fix this.

Possible solutions:

1. Format all date/times in the frontend according to the "report timezone"? (note: what if "database default" is selected?) I think it makes sense for all dates/times appearing on a page to be in the same timezone, namely date filters and results should match up. It might also be nice to have a footnote containing the report timezone (always, or only if the report timezone and browser timezone don't match?)
2. I think it would be best for `/api/dataset` to always return date/times in the report timezone, but either way it should be consistent about returning the beginning of the grouping period *in the report timezone*, whether it's represented in the report timezone or UTC. e.x. for the case above (January 30, 2016 with report timezone set to PST) either `2016-01-30T00:00:00.000-08:00` (report timezone, my preference) or `2016-01-30T08:00:00.000Z` (UTC)

**Comment by agilliland** [comment] 2016-01-31 19:04
I agree, those are both issues.  I think it's best if we separate 2. into its own issue and link it back to this one.  We need to resolve both of these though.

I agree that using the reporting timezone consistently throughout all date/time representations in the app makes the most sense.  Its worth thinking that through in a bit more detail, but in general that makes sense to me.  And for "database default" we probably either need to tweak that to use the system default for the Metabase instance or actually grab the default timezone from the database (which is realistically less reliable since some databases don't support timezones).

**Comment by mchung** [comment] 2016-02-07 20:53
Another example of the off-by-one-day bug in the wild (on v0.14.1).

<img width="868" alt="screen_shot_2016-02-07_at_12_27_31_pm" src="https://cloud.githubusercontent.com/assets/2609/12875095/7f78b538-cd97-11e5-9bb5-2f2e737d5c37.png">

**Comment by agilliland** [comment] 2016-02-25 21:50
@tlrobinson After looking at this a little bit more I think the first thing we should do is completely remove the browser timezone from the equation.  I think that will make a big difference.  There is realistically no reason (that i can think of) for the browser timezone to be having any impact on the values that are returned from queries.  

So I'm thinking that wherever we are parsing the values that come back from queries we should be taking care not to do anything that would impact the timezone representation and if the value is represented in UTC then we should keep it in UTC.

I still agree that there is work to be done on the backend to more accurately represent the datetime values that are returned as you describe above.  I'm going to go ahead and create a separate ticket for that issue.

**Comment by agilliland** [comment] 2016-02-26 17:43
This impacts multiple places in the visualizations, but here's a clearly reproduceable test case using tables.

To reproduce: Set the report timezone to `Asia/Tokyo` and run this query (on postgres) `select * from (values (timestamp with time zone '1999-01-08 11:05:06 -8:00', (timestamp with time zone '1999-01-08 11:05:06 -8:00'::date))) v`.  on my system which is in US/Pacific the output is ...
<img width="459" alt="screen shot 2016-02-26 at 9 37 45 am" src="https://cloud.githubusercontent.com/assets/1987787/13360155/a21f1c2e-dc6c-11e5-923c-a3e79f4b3fbb.png">

The expected output is `Saturday, January 9, 1999 04:05am` which is what the above timestamp represents in the selected Asia/Tokyo timezone.  

The reason for the inaccuracy is because currently the frontend visualizations are parsing the timestamps that come back from query results into javascript Date objects and then reformatting them for various scenarios on charts, tables, etc.  When reformatting them the code is using the local browser timezone instead of more ideally just leaving them in whatever timezone they start in which is probably ideal so the frontend never needs to make any decisions about timezones, or at the very least formatting them explicitly in the report timezone value set by the user.

**Comment by tlrobinson** [comment] 2016-02-29 06:12
@agilliland are #2034 and #2035 the issues you created for the two problems I identified in my previous comment? Should we just use this issue to track the overall problem, and only close it when both are resolved?

**Comment by tlrobinson** [comment] 2016-02-29 06:26
Nevermind, I think those are both backend issues?

Taking about it a little more, I'm not sure the frontend should be using the global "report timezone" to format date/times since some databases don't support it (also is it possible for SQL queries to override the report timezone?). I think ideally the backend would always return timestamps including the timezone the query was run using, which the frontend could use in formatting.

**Comment by agilliland** [comment] 2016-02-29 15:53
Yep, that's what I think we should be doing as well.  I would prefer to not have the frontend do any timezone conversion work at all.  #2034 is tracking the main fix for that which would update the backend to ensure all query results format their timestamps with the appropriate timezone.

#2035 is related to timezone handling, but it's not particularly related to this issue.  that issue is more specifically about how to handle cases where the database itself returns data that is missing timezone information.

**Comment by salsakran** [comment] 2016-03-12 00:21
Lots of people seem to be hitting this. Do we have a proposed solution? Can we get this into 0.16?

**Comment by agilliland** [comment] 2016-03-14 15:34
Yes, this is something that we can address for the next release.  The proposed solution is to remove any timezone changing when the frontend does date reformatting.

**Closed** 2016-03-15 16:12 UTC
Labels: Bug, Correctness, Query Processor, Visualization

**Comment by morrow95** [comment] 2018-05-30 04:02
What is the status on this?
