### ISSUE TITLE
Support for Trino

### ISSUE THREAD

**Issue by rubenssoto** [metabase/metabase#17532] opened 2021-08-20 18:55 UTC
Hello,

After support for PrestoDB JDBC is it easier to add support for TrinoDB JDBC too?

Trino has a bigger community, I think it would be very good for metabase users.

Thank you

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by bitsondatadev** [comment] 2021-08-21 03:50
Context: https://trino.io/blog/2020/12/27/announcing-trino.html
How to migrate: https://trino.io/blog/2021/01/04/migrating-from-prestosql-to-trino.html

**Comment by rubenssoto** [comment] 2021-08-21 13:48
@flamber 

Do you know if there is any chance of this driver being developed soon? 

Thank you so much

**Comment by flamber** [comment] 2021-08-21 14:52
@rubenssoto Taking on an extra included driver in the product is a lot more work than people think. It is definitely on our radar.

**Comment by rubenssoto** [comment] 2021-08-21 15:10
@flamber thank you so much!

**Comment by bitsondatadev** [comment] 2021-08-21 17:09
> @rubenssoto Taking on an extra included driver in the product is a lot more work than people think. It is definitely on our radar.

@flamber will you take community contributions from the Trino side?

**Comment by flamber** [comment] 2021-08-21 17:21
@bitsondatadev I would recommend that you create a community driver first, then it's easier to see what it would take to make it part of the product: https://www.metabase.com/docs/latest/developers-guide-drivers.html

**Comment by bitsondatadev** [comment] 2021-08-21 19:37
Thanks @flamber, is the Presto driver code available to view? I imagine it's a small code change if we have that to base from.

**Comment by rubenssoto** [comment] 2021-08-21 19:53
@bitsondatadev 
I think, that is the one:
https://github.com/metabase/metabase/tree/master/modules/drivers/presto-jdbc

@flamber only to be sure, is it right?

thank you

**Comment by kadekbyan** [comment] 2021-09-30 01:10
@dacort or anyone, do we need a specific trino driver other than JDBC driver ? After this, jdbc driver will come to Metabase 0.41.

**Comment by rubenssoto** [comment] 2021-09-30 01:53
I didn't understand @kadekbyan, the presto jdbc driver that will come with metabase 0.41 doesn't support new versions of trino.

**Comment by jeff303** [comment] 2021-09-30 02:05
The new Presto driver coming in x.41 does use JDBC.  However, it only works with prestodb.  Trino still does need its own separate driver.  Fortunately, it should be almost identical to the prestodb one we added in 41, and the work done by @dacort confirms that.

**Comment by kadekbyan** [comment] 2021-10-16 05:24
@jeff303 will this issue resolved by downgrade the trino version to 350 with metabase version 0.40 ? because I think the problem is trino start to differ it's path since the beginning of 2021 and there still a lot of works from community to expand the trino driver.

**Comment by flamber** [comment] 2021-10-16 08:52
@kadekbyan Until Trino starts to divert enough, then we'll look into integrating the driver in Metabase, but as already pointed out, it is a lot more work and maintenance to have drivers integrated.

The workaround is to use the legacy header, which works fine with the old and new Presto driver:
```
# Add the following line to the file /etc/trino/config.properties
protocol.v1.alternate-header-name=Presto
```
If you cannot use the workaround for some reason, then you can use the community driver https://github.com/metabase/metabase/issues/17532#issuecomment-923353091
Or you can downgrade to Trino 350, where it still announces itself as Presto, so both the old and new driver will work.

**Comment by mosabua** [comment] 2021-10-21 17:09
The Trino JDBC driver supports Oauth and is getting constantly improved and updated with new features. While this workaround is possible for now it also is limited to clusters that set the legacy header.. most clients work with the new headers so it is becoming less and less likely that a cluster is held back at the legacy header just for one BI tool. I strongly recommend that someone takes the presto driver, and rejigs it to Trino.

**Comment by luizarakaki** [comment] 2021-11-19 14:08
Hello, I'm Luiz, product manager here at Metabase. I'm exploring supporting Trino.

I prepared this [quick survey](https://forms.gle/VSSFWLQiDfw5RtdD7) to gather more info about Trino usage. Could you please respond to the survey? It will help us be more confident to prioritize and develop this feature.

**Comment by bitsondatadev** [comment] 2021-11-20 03:44
> Hello, I'm Luiz, product manager here at Metabase. I'm exploring supporting Trino.
> 
> 
> 
> I prepared this [quick survey](https://forms.gle/VSSFWLQiDfw5RtdD7) to gather more info about Trino usage. Could you please respond to the survey? It will help us be more confident to prioritize and develop this feature.

@luizarakaki, I'm sharing this around the Trino Community to get a little more reach.

**Comment by irisywy6201** [comment] 2021-11-27 15:04
> Hello, I'm Luiz, product manager here at Metabase. I'm exploring supporting Trino.
> 
> I prepared this [quick survey](https://forms.gle/VSSFWLQiDfw5RtdD7) to gather more info about Trino usage. Could you please respond to the survey? It will help us be more confident to prioritize and develop this feature.

@luizarakaki, Hi, I wonder if you have an estimate of when this feature will be completed? Thanks.

**Comment by luizarakaki** [comment] 2021-11-29 18:41
> > Hello, I'm Luiz, product manager here at Metabase. I'm exploring supporting Trino.
> > I prepared this [quick survey](https://forms.gle/VSSFWLQiDfw5RtdD7) to gather more info about Trino usage. Could you please respond to the survey? It will help us be more confident to prioritize and develop this feature.
> 
> @luizarakaki, Hi, I wonder if you have an estimate of when this feature will be completed? Thanks.

We don't have an estimate. We are evaluating how/why users connect to Trino and talking to people that may contribute. There are good conversations, though. We will keep this issue updated.

**Comment by alexpusch** [comment] 2021-12-26 09:08
Trino headers workaround `protocol.v1.alternate-header-name=Presto` stoped working for us when using the "new Presto driver" we got after upgrading to the latest Metabase version. For now we can keep working with the old driver, but I guess it's a matter of time until it's gone.

@luizarakaki any hope for official support for Trino?

**Comment by flamber** [comment] 2021-12-26 10:07
@alexpusch It's still working with both the old and the new driver with the header workaround.

**Comment by alexpusch** [comment] 2021-12-26 11:05
@flamber When using the new Persto driver, the same query that worked on the old driver throws the following error:
```
class: "class com.facebook.presto.jdbc.internal.jackson.databind.exc.ValueInstantiationException"
error: "Cannot construct instance of `com.facebook.presto.jdbc.internal.client.QueryResults`, problem: Illegal base64 character 2d\n at [Source: (String)\"{\"id\":\"...\",\"infoUri\":\"http://***/ui/query.html?...\",\"partialCancelUri\":\"http://***/v1/statement/executing/partialCancel/...",\"nextUri\":\"http://***/v1/statement/executing/...\",\"columns\":[{\"name\":\"id\",\"type\":\"uuid\",\"typeSignature\":{\"rawType\":\"uuid\",\"arguments\":[]}},{\"na\"[truncated 5147 chars]; line: 1, column: 5646]"

```

**Comment by flamber** [comment] 2021-12-26 11:13
@alexpusch Okay, that's a different problem. Try just doing `select 1` - if that works, then it has nothing to do with the header.
It would require a lot more information to understand what the problem is. "Diagnostic Info", versions, the query, etc.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by rubenssoto** [comment] 2022-02-07 15:34
Do you have any updates on this?

thank you

**Comment by rubenssoto** [comment] 2022-04-06 12:55
Hey Guys,

Any updates on this issue?

Thank you

**Comment by luizarakaki** [comment] 2022-06-08 13:20
The first version of the Starburst/Trino driver is ready. The Starburst team developed it in partnership with Metabase.

https://github.com/starburstdata/metabase-driver

Although it was tested and verified by our team, we expect to find adjustments in the next few weeks. Feedback is very welcome!

**Closed** 2022-06-15 17:19 UTC
Labels: Database/, Type:New Feature

**Comment by mingfang** [comment] 2022-09-04 12:19
Why was this closed?
I just tried the latest version of Metabase and I still do not see an option to connect to Trino.
Please open this issue.

**Comment by flamber** [comment] 2022-09-04 15:20
@mingfang As mentioned just above https://github.com/metabase/metabase/issues/17532#issuecomment-1149906975, it's a driver module which can be downloaded. Partner drivers are included in Metabase Cloud.
