### ISSUE TITLE
Increasing the number of rows to show is not working

### ISSUE THREAD

**Issue by diogormendes** [metabase/metabase#22245] opened 2022-04-29 12:11 UTC
**Describe the bug**
When trying to increase the number of rows to show above 2000, is not working.

**Logs**

https://user-images.githubusercontent.com/17742979/165941343-6588df17-cb33-408f-a167-4992d9d741d2.mov

**To Reproduce**
1. Go to 'Sample Database'
2. Click on 'Orders'
3. Click on `Showing first 2,000 rows`
4. Change the limit to something higher than 2000 and run the query.
6. See error

**Expected behavior**
Should filter the required rows

**Information about your Metabase Installation:**

<details>
<summary>Version</summary>
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_322-b06",
    "java.vendor": "Azul Systems, Inc.",
    "java.vendor.url": "http://www.azul.com/",
    "java.version": "1.8.0_322",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.322-b06",
    "os.name": "Mac OS X",
    "os.version": "12.3.1",
    "user.language": "en",
    "user.timezone": "America/Sao_Paulo"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v1.43.0-rc2",
      "date": "2022-04-28",
      "branch": "release-x.43.x",
      "hash": "04a3896"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
</details>

x.43.RC2

**Comment by nemanjaglumac** [comment] 2022-04-29 14:05
Ok, I wasn't able to reproduce originally because I was going for the smaller number and it works. After watching your video, I tried with the larger number and indeed it doesn't work.

So maybe alter the title and description to make it explicit.

**Comment by flamber** [comment] 2022-05-01 14:36
There's a hardcoded max limit of 2000. Similar to #12188, closing in favor of #1546.

**Closed by flamber** 2022-05-01 14:36 UTC
Labels: Type:Bug, .Needs Triage, .bugbash
