### ISSUE TITLE
Mongo Max/Min of datetime field

### ISSUE THREAD

**Issue by ujjwal-gupta** [metabase/metabase#5200] opened 2017-05-26 09:32 UTC
While grouping, in the view section, the user should be able to specify datetime field in the "Maximum of", "Minimum of" options.

**Comment by tanzoniteblack** [comment] 2017-05-26 21:05
👍  for this to be not just for mongo, but also available for other engines (recently needed this on both postgres and mysql)

**Comment by c-schmitz** [comment] 2017-12-20 11:22
Duplicate of #4482

**Closed** 2020-03-08 01:34 UTC
Labels: .Proposal, .Query Language (MBQL)
