### ISSUE TITLE
"Number" visualization showing wrong value when resized

### ISSUE THREAD

**Issue by aviggiano** [metabase/metabase#7100] opened 2018-03-09 16:20 UTC
I found an issue when resizing a "Number" card on a dashboard.

Here's the card when there is enough space to see the whole number

![screenshot-2018-03-09-13-11-30](https://user-images.githubusercontent.com/3029017/37217226-bdec0ad4-239b-11e8-9c47-8b673b2c46c0.png)

Here's the resized card, showing a wrong value

![screenshot-2018-03-09-13-11-34](https://user-images.githubusercontent.com/3029017/37217275-e1c7f490-239b-11e8-9769-697caf40fca0.png)

Apparently the card is not taking into consideration the multiplier defined in the card configuration

![screenshot-2018-03-09-13-17-05](https://user-images.githubusercontent.com/3029017/37217427-3c99e392-239c-11e8-912b-96ac233ba8cb.png)

Additional information:

- Your browser and the version: Chrome 64.0.3282.167 (Official Build) (64-bit)
- Your operating system: Linux/Ubuntu 16.04.1
- Your databases: MongoDB
- Metabase version: 0.28.1
- Metabase hosting environment: Elastic Beanstalk/Docker (launched using the button on [this URL](https://metabase.com/start/aws.html))
- Metabase internal database: Postgres on AWS/RDS

*Repeatable steps to reproduce the issue*

1. Create a "Number" card with a multiplier
2. Resize it

**Comment by mazameli** [comment] 2018-03-09 17:32
Duplicate of https://github.com/metabase/metabase/issues/5778

**Closed by mazameli** 2018-03-09 17:32 UTC
Labels: Duplicate
