### ISSUE TITLE
Preview embed FE tries to call `GET /api/dashboard/:jwt-token/params/:param-id/values` which does not exist

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#20511] opened 2022-02-14 23:57 UTC
This API endpoint does not exist:

<img width="1448" alt="image" src="https://user-images.githubusercontent.com/1455846/153966603-cdd23120-d419-488b-bd66-012ef34db2df.png">

We have `GET /api/dashboard/:id/params/:param-id/values` and `GET /api/embed/dashboard/:jwt-token/params/:param-id/values` but you can't call a `GET /api/dashboard/` endpoint with an embedding JWT.

To repro:

1. Enable embedding in the admin panel
2. Create a Dashboard with a Category parameter
3. Go to sharing > Embedding for the Dashboard and select "Embed in another application"
4. Enable the parameter for embedding
5. Attempt to enter a parameter e
6. In Network Console there is a 404

**Comment by flamber** [comment] 2022-02-15 09:41
Duplicate of #14309

**Closed by flamber** 2022-02-15 09:41 UTC
Labels: Type:Bug, .Needs Triage
