### ISSUE TITLE
Cannot Start when language set to Turkish

### ISSUE THREAD

**Issue by ahmetsah** [metabase/metabase#9073] opened 2018-12-05 15:03 UTC
PS C:\Users\MIKRODEV\Desktop\mnm> java -jar metabase.jar
12-05 16:12:42 [1mINFO metabase.util[0m :: Metataban² y³kleniyor ...
12-05 16:12:42 [1mINFO metabase.util[0m :: Maximum memory available to JVM: 884,0 MB
12-05 16:12:46 [1mINFO util.encryption[0m :: Kay²tl² kimlik bilgileri ■ifreleme, bu Metataban² ÷rne­i iin DEVRE DIÌI.
 For more information, see https://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
12-05 16:12:53 [1mINFO metabase.core[0m :: STANDALONE modunda Metataban²n² ba■latma
12-05 16:12:53 [1mINFO metabase.core[0m :: Config ile Embedded Jetty Web sunucusu ba■lat²l²yor:
 {:port 3000}

12-05 16:12:53 [1mINFO metabase.core[0m :: Metataban² s³r³m³ v0.31.1 (04829a7 release-0.31.1) ba■lat²l²yor ...
12-05 16:12:53 [1mINFO metabase.core[0m :: Sistem saat dilimi ' Asia/Istanbul ' ...
WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collection, being replaced by: #'monger.collection/any?
12-05 16:12:55 [1mINFO metabase.core[0m :: Metataban² DByi kurma ve ta■²ma. L³tfen bekleyin, Bu bir dakika s³rebilir ..
12-05 16:12:55 [1mINFO metabase.db[0m :: h2 Veritaban² Ba­lant²s² Do­rulan²yor ...
12-05 16:12:55 [1mINFO metabase.db[0m :: Veritaban² Ba­lant²s²n² Do­rulay²n.
12-05 16:12:55 [1mINFO metabase.db[0m :: Veritaban² Gei■lerini Ãal²■t²rma ...
12-05 16:12:55 [1mINFO metabase.db[0m :: Liquibase kurulumu ...
12-05 16:12:55 [1mINFO metabase.db[0m :: Liquibase haz²rd²r.
12-05 16:12:55 [1mINFO metabase.db[0m :: Veritaban²n²n gei■leri kald²r²l²p kald²r²lmad²­²n² kontrol etme ...
12-05 16:12:57 [1mINFO metabase.db[0m :: Veritaban²nda ta■²nma yok. Ta■²ma kilidinin silinmesini bekliyor ...
12-05 16:12:57 [1mINFO metabase.db[0m :: G÷ kilidi temizlendi. G÷ler yay²nlan²yor ...
12-05 16:12:59 [1mINFO metabase.db[0m :: Veritaban² Gei■leri
12-05 16:12:59 [1mINFO db.migrations[0m :: Running all necessary data migrations, this may take a minute.
12-05 16:13:00 [1mINFO db.migrations[0m :: Running data migration 'add-users-to-default-permissions-groups'...
12-05 16:13:00 [1mINFO models.permissions-group[0m :: Olu■turulan b³y³ izin grubu ' All Users ' (ID = null)
12-05 16:13:00 [1mINFO models.permissions-group[0m :: Olu■turulan b³y³ izin grubu ' Administrators ' (ID = null)
12-05 16:13:00 [1mINFO db.migrations[0m :: Running data migration 'add-admin-group-root-entry'...
12-05 16:13:00 [1mINFO db.migrations[0m :: Running data migration 'add-databases-to-magic-permissions-groups'...
12-05 16:13:00 [1mINFO models.permissions-group[0m :: Olu■turulan b³y³ izin grubu ' MetaBot ' (ID = null)
12-05 16:13:00 [1mINFO db.migrations[0m :: Running data migration 'migrate-field-types'...
12-05 16:13:00 [1mINFO db.migrations[0m :: Running data migration 'fix-invalid-field-types'...
12-05 16:13:00 [1mINFO db.migrations[0m :: Running data migration 'copy-site-url-setting-and-remove-trailing-slashes'...
12-05 16:13:00 [1mINFO db.migrations[0m :: Running data migration 'drop-old-query-execution-table'...
12-05 16:13:00 [1mINFO db.migrations[0m :: Running data migration 'ensure-protocol-specified-in-site-url'...
12-05 16:13:00 [1mINFO db.migrations[0m :: Running data migration 'populate-card-database-id'...
12-05 16:13:00 [1mINFO db.migrations[0m :: Running data migration 'migrate-humanization-setting'...
12-05 16:13:00 [1mINFO db.migrations[0m :: Running data migration 'mark-category-fields-as-list'...
12-05 16:13:00 [1mINFO db.migrations[0m :: Running data migration 'add-legacy-sql-directive-to-bigquery-sql-cards'...
12-05 16:13:00 [1mINFO db.migrations[0m :: Running data migration 'clear-ldap-user-local-passwords'...
12-05 16:13:00 [1mINFO db.migrations[0m :: Running data migration 'add-migrated-collections'...
12-05 16:13:00 [1mERROR metabase.core[0m :: Metataban² Ba■latma Ba■ar²s²z
java.lang.Exception: Not something with an ID:
        at metabase.util$get_id.invokeStatic(util.clj:460)
        at metabase.util$get_id.invoke(util.clj:451)
        at metabase.db.migrations$add_migrated_collections.invokeStatic(migrations.clj:333)
        at metabase.db.migrations$add_migrated_collections.invoke(migrations.clj:332)
        at metabase.db.migrations$run_migration_if_needed_BANG_.invokeStatic(migrations.clj:52)
        at metabase.db.migrations$run_migration_if_needed_BANG_.invoke(migrations.clj:43)
        at metabase.db.migrations$run_all_BANG_.invokeStatic(migrations.clj:72)
        at metabase.db.migrations$run_all_BANG_.invoke(migrations.clj:66)
        at clojure.lang.Var.invoke(Var.java:377)
        at metabase.db$run_data_migrations_BANG_.invokeStatic(db.clj:445)
        at metabase.db$run_data_migrations_BANG_.invoke(db.clj:440)
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:456)
        at metabase.db$setup_db_BANG_.doInvoke(db.clj:447)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at metabase.core$init_BANG_.invokeStatic(core.clj:162)
        at metabase.core$init_BANG_.invoke(core.clj:139)
        at metabase.core$start_normally.invokeStatic(core.clj:246)
        at metabase.core$start_normally.invoke(core.clj:240)
        at metabase.core$_main.invokeStatic(core.clj:266)
        at metabase.core$_main.doInvoke(core.clj:261)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
12-05 16:13:00 [1mINFO metabase.core[0m :: Metataban² Kapan²yor ...
12-05 16:13:00 [1mINFO metabase.core[0m :: Metataban² Kapatma TAMAMLANDI
PS C:\Users\MIKRODEV\Desktop\mnm>

how can i solve this problem

w10，turkish

**Comment by tlrobinson** [comment] 2018-12-05 19:21
Related to / duplicate of #9011

**Closed** 2019-02-09 04:06 UTC
Labels: Bug, Priority/P1, i18n
