### ISSUE TITLE
Set default width for columns in query results

### ISSUE THREAD

**Issue by reza-keshavarz** [metabase/metabase#13976] opened 2020-12-07 11:22 UTC
**Is your feature request related to a problem? Please describe.**
Every once in a while we encounter a column which values are uncommonly long. For instance, when there is a hash stored in that filed, or a long URL, or something else. 
This makes navigating hard when for instance, seeing a whole table in Metabase. These long fields make horizontal scrolling annoying. 

**Describe the solution you'd like**
It would be great if we could set a default width for a column in the results. For instance, for any field with values wider that 40 characters, the dashboard would show a fixed-length filed ending with "..." indicating that this value is not shown completely.

**Describe alternatives you've considered**
For now, every time I open a view a table, I either uncheck the field in the query editor, or collapse the column with the mouse. They both are of course boring and productivity killers.

**How important is this feature to you?**
On the scale of 1 to 10 with 10 being the most important, I would give this feature a 6.

**Additional context**

**Comment by flamber** [comment] 2020-12-07 19:04
Duplicate of #10372

**Closed by flamber** 2020-12-07 19:04 UTC
Labels: .Needs Triage, Type:New Feature
