### ISSUE TITLE
New dashboard not appearing in list without hard refresh if created via save question flow

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3874] opened 2016-12-06 00:18 UTC
In 0.21.0-rc2, in Chrome, if you have 0 dashboards, save a new question, and try to add it to a dashboard, MB prompts you to create a new dashboard. If you do that through this flow and save the dashboard, the dashboard won't appear in your dashboard dropdown until you hard refresh Metabase.

![screen shot 2016-12-05 at 4 14 17 pm](https://cloud.githubusercontent.com/assets/2223916/20907982/61a52f48-bb06-11e6-8ff9-12de6b7e7fd7.png)

**Comment by tlrobinson** [comment] 2016-12-06 01:33
Duplicate of #2871

**Closed by tlrobinson** 2016-12-06 01:33 UTC
Labels: Bug

**Comment by mazameli** [comment] 2016-12-06 17:57
I beg to differ. In 0.21.0-rc2, if I create a dashboard using the "create your first dashboard" button from the dropdown, I _do_ see the dashboard in the dropdown. It's only specifically if I create one via the save question flow that I don't end up seeing it in the dropdown until I refresh.
