### ISSUE TITLE
Translation string interpolation on browser tab Title broken in master shows "e=>e?E.t" while loading

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#40875] opened 2024-04-01 21:24 UTC
### Describe the bug

String interpolation issue with translations that shows briefly in title bar of browser tab after changing and rerunning a question.

### To Reproduce

1. Create an ad-hoc question
2. Add a filter
3. Watch the browser tab title, it briefly shows "e=>e?E.t`Waiting ..." while loading instead of the translation of "Waiting ..."

![image](https://github.com/metabase/metabase/assets/8808703/ce9ab9ac-29a3-428e-b796-7fd194b8c2f2)

### Expected behavior

- expect to see translation

### Logs

n/a

### Information about your Metabase installation

```JSON
- `master` as of `80e6905`
```

### Severity

P2: standard bug

**Comment by uladzimirdev** [comment] 2024-04-01 21:38
Probably duplicate of https://github.com/metabase/metabase/issues/40051

**Closed** 2024-04-02 06:38 UTC
Labels: Type:Bug, Priority:P2, .Frontend, .Needs Triage, .Regression/master
