### ISSUE TITLE
Google SSO User Error "Unauthenticated" When Using Identity Only Domain

### ISSUE THREAD

**Issue by jspisakcpr** [metabase/metabase#17789] opened 2021-09-07 18:43 UTC
**Description**<img width="1254" alt="Screen Shot 2021-09-07 at 11 35 48 AM" src="https://user-images.githubusercontent.com/74877628/132395169-e01e49b3-ce43-4c93-83f8-d047b483d0cf.png">We have been using Google SSO successfully for a while. We added a free Google Identity only domain to our Google Workspace, but users on that "Identity Only" domain cannot login to Metabase. The Oauth2 popup completes successfully, but the are left at the login page and the error log shows them a "Unauthenticated" even though their Google Account shows the application "Metabase" as successfully authenticated. We removed them from all Groups, same behavior.

**Logs**
[72621d30-bcf7-4e21-8b8b-34e0695d075d] 2021-09-07T06:04:39-07:00 DEBUG metabase.server.middleware.log GET /api/user/current 401 398.1 µs (0 DB calls) 
"Unauthenticated"

**To Reproduce**
1. Create a Free Google Cloud Identity account for a domain.
2. Register the domain with your current Google Workspace as a "Secondary Domain"
3. Create an "Identity Only" user (format will be username@secondarydomain.net)
4. Try to login to Metabase as the "Identity Only" User using "Login with Google"
5. The login screen prompts for Oauth Login, and completes, but the user is never granted access to Metabase and remains at the login screen.

**Expected behavior**
User should be allowed in if Oauth completes and shows as "Authenticated" in their Google Account.

**Screenshots**

<img width="1254" alt="Screen Shot 2021-09-07 at 11 35 48 AM" src="https://user-images.githubusercontent.com/74877628/132395169-e01e49b3-ce43-4c93-83f8-d047b483d0cf.png">**Severity**
Secondary Domain users cannot use Google with 2 factor protection, only Metabase simple password security.

**Additional context**
Strangely, we can see in the Google Oauth audit logs that the Metabase Oauth session completes and is granted a token.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9-Ubuntu-0ubuntu2.20.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9-Ubuntu-0ubuntu2.20.04",
    "os.name": "Linux",
    "os.version": "5.8.0-1038-gcp",
    "user.language": "en",
    "user.timezone": "America/Phoenix"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.26-0ubuntu0.20.04.2"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-07-14",
      "tag": "v0.40.1",
      "branch": "release-x.40.x",
      "hash": "ed8f9c8"
    },
    "settings": {
      "report-timezone": "US/Arizona"
    }
  }
}
```

**Comment by flamber** [comment] 2021-09-07 19:26
Basically a duplicate of #5218, which allows multiple domains since 1.40.0 (the Enterprise Edition).

**Closed by flamber** 2021-09-07 19:26 UTC
Labels: Type:Bug, .Needs Triage
