### ISSUE TITLE
Weekly grouping with inconsistent data

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#6153] opened 2017-10-12 02:30 UTC
Metabase version: 0.26.1, On all platforms

When you make a query with weekly grouping, the result is shown with date ranges for the week. But as soon as you put it on a dashboard, it changes to week number.

Preferred: Show date ranges for the week on dashboards as well.

![screen shot 2017-10-11 at 19 26 35](https://user-images.githubusercontent.com/1330677/31476267-75028c54-aeba-11e7-8d01-cf89e0fd1092.png)
![screen shot 2017-10-11 at 19 26 46](https://user-images.githubusercontent.com/1330677/31476268-75256d0a-aeba-11e7-9da0-38b5c15f9bf1.png)

**Comment by flamber** [comment] 2019-02-17 02:00
Hi @VikramTiwari 
I cannot reproduce your issue on 0.31.2 - I'm not sure when this was changed.
![image](https://user-images.githubusercontent.com/1447303/52907303-c2cdf600-3224-11e9-9ead-22502d379d39.png)
![image](https://user-images.githubusercontent.com/1447303/52907320-248e6000-3225-11e9-833b-6e1d28590a7a.png)

**Comment by flamber** [comment] 2020-03-02 18:49
Closing issue because of no reply and I cannot reproduce on 0.34.3

**Closed by flamber** 2020-03-02 18:49 UTC
Labels: Reporting/Dashboards, Type:UX, Visualization/
