### ISSUE TITLE
Email option can't be enabled when creating a pulse

### ISSUE THREAD

**Issue by jobevers** [metabase/metabase#3016] opened 2016-07-25 18:35 UTC
When attempting to create a pulse, I can't get it to enable the email option:

![image](https://cloud.githubusercontent.com/assets/2380127/17112619/636dea66-526c-11e6-8004-0797b1549191.png)

Email is configured and it works - I am able to invite people to view the dashboard.

---

If this is a bug report, please fill in the blanks:
-  I am using the Chrome browser.
-  My computer's OS is OSX.
-  I'm running Metabase AWS EBS  and it is using the Postgres database.
-  My data is in a Postgres database. 
-  My Metabase version is 0.18.1.

**Comment by camsaul** [comment] 2016-07-26 23:39
@jobevers I can't reproduce this issue either on 0.18.1 or 0.19.0-SNAPSHOT. Are you still seeing this error? If so, do you see anything in your browser logs?

**Comment by camsaul** [comment] 2016-08-04 20:03
Fixed by #3124, credit: @mavimo

**Comment by camsaul** [comment] 2016-08-04 20:03
Oops wrong tab on my browser. Please disregard previous comment

**Comment by jobevers** [comment] 2016-08-10 11:50
Sorry for the late response:

![image](https://cloud.githubusercontent.com/assets/2380127/17552643/b7aade34-5ec6-11e6-8b97-096d835f4f3f.png)

**Comment by camsaul** [comment] 2016-09-10 02:28
Looks like it might be an issue with `GET /api/pulse/form_input` returning a 500... not sure why; it's working fine for me locally. Maybe this was something that was accidentally fixed.

@jobevers Are you still seeing this on the latest version of Metabase (0.19.3)?

**Comment by ragb-rg** [comment] 2016-11-14 08:09
Unable to enable email and slack options in metabase. 

Screenshot attached. 
V0.20.3 , chrome, Ubuntu, AWS

![metabase_pulse](https://cloud.githubusercontent.com/assets/23306999/20257443/9f837452-aa6f-11e6-9798-6e8a0058088b.png)

**Comment by sanandnarayan** [comment] 2017-01-23 16:41
I recently upgraded metabase by downloading the jar, and I am facing the same issue.

**Comment by sanandnarayan** [comment] 2017-01-23 16:47
The issue was slack token was revoked. You can fix this by deleting your old slack token

**Comment by camsaul** [comment] 2017-03-01 23:07
@jobevers @ragb-rg did you get a chance to try @sanandnarayan's suggestion

**Closed** 2017-03-23 23:43 UTC
Labels: Bug, Priority/P1, Pulses
