### ISSUE TITLE
Metabase Integration barrier(X-Frame-Options:Deny) with other Open Source Platform.

### ISSUE THREAD

**Issue by navdeepghai1** [metabase/metabase#7506] opened 2018-05-01 06:50 UTC
> ### Database support
>> MariaDB

### Feature requests and proposals
If metabase header Allow X-Frame-Options set to  wildcard URL. It's will be easy for the developer to integrate the Metabase with other open source platforms.

> ### Browser:
>> ALL

If It's issue with ClickJacking then we can use environment variable which allow user to set the 
option for   **X-Frame-Options** .

**Comment by salsakran** [comment] 2018-05-01 23:25
dupe of #2721 and given the security footprint it opens up, it's not something we're planning on doing.

**Closed by salsakran** 2018-05-01 23:25 UTC
