### ISSUE TITLE
Pulse by Slack does not support UTF8

### ISSUE THREAD

**Issue by aogilvie** [metabase/metabase#11425] opened 2019-12-03 01:11 UTC
**Describe the bug**
Pulse by email works fine as embedded HTML however the image conversion used to post to Slack shows squares where Japanese text should be:

**To Reproduce**
1. Setup a mongodb database with a Japanese text entry
2. Create and save a question
3. Setup slack bot connection with API key
4. Create pulse to send question result to Slack

**Expected behavior**
Should see text not "mojibake"

**Screenshots**
![69695284-1e67d100-111f-11ea-88aa-69c05f1601be](https://user-images.githubusercontent.com/970364/70007725-be58ab00-15b4-11ea-8219-138c8566de51.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

metabase 0.33.0 in docker on Google Cloud VM (CentOS 7), mongoDB

**Severity**
Makes Slack notifications unreadable - low severity

**Comment by flamber** [comment] 2019-12-03 03:26
Hi @aogilvie 
Looks like a duplicate of #2342. If you agree, then please close this and upvote the other issue :+1:
By the way, latest release is 0.33.6

**Closed** 2019-12-14 00:10 UTC
Labels: .Duplicate

**Comment by aogilvie** [comment] 2020-02-03 03:59
yes. thanks.
