### ISSUE TITLE
Very Large performance difference for regular users vs Admins

### ISSUE THREAD

**Issue by apostoltego** [metabase/metabase#47276] opened 2024-08-27 06:46 UTC
### Describe the bug

Regular users of metabase have been reporting that their dashboards are loading super slowly. This isn't the case for users with admin privileges indicating permissions related slowdowns.

This was initially flagged [here](https://github.com/metabase/metabase/issues/44359#issuecomment-2304769175) where the conclusion was to open a separate issue. Relevant information from there:

```
select count(*) from data_permissions -> 113,541

select count(*), active from metabase_table group by active
count | active
15,388 | false
1,287 | true

```

### To Reproduce

Assuming that to reproduce this there's a need to a decently large amount of data permissions.

### Expected behavior

Dashboards should load fast for all users regardless of permissions

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "clickhouse",
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-08-21",
      "tag": "v0.50.21",
      "hash": "ec9f5d7"
    },
    "settings": {
      "report-timezone": "UTC"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.10 (Ubuntu 13.10-1.pgdg22.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.10.219-208.866.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}
```

### Severity

High, preventing metabase usage by end users.

**Comment by perivamsi** [comment] 2024-08-27 09:57
How much time is the dashboard taking for regular user and how much time is it taking for an admin? Are you able to look at the `/api/dashboard/:id` and the `/api/dashboard/:id/query_metadata` endpoints in browser tools and see the response time?

**Comment by apostoltego** [comment] 2024-08-27 11:10
As an admin:
- query_metadata 2s
- dashboard 1s

Non-Admin about ~5s each. 

These are with admin priveleges:
![Screenshot 2024-08-27 at 12 05 06](https://github.com/user-attachments/assets/4187eab4-cdbf-4ae7-a16c-aafe0dc659cf)
![Screenshot 2024-08-27 at 12 05 12](https://github.com/user-attachments/assets/51ea5107-f0fa-453c-ae56-cf61823b5ac4)


Regular permissions:

![Screenshot 2024-08-27 at 12 07 47](https://github.com/user-attachments/assets/e9597929-2ab9-4b5a-aab1-4e87b4acea81)
![Screenshot 2024-08-27 at 12 07 53](https://github.com/user-attachments/assets/cd03933c-5686-4f1d-85b6-fe980a4d1fa2)

**Comment by bshepherdson** [comment] 2024-08-27 13:30
This might be caused by #46181.

**Comment by noahmoss** [comment] 2024-08-27 18:58
@apostoltego How many databases do you have, and what is the distribution of tables across the databases? The output of this would be helpful to see:
```
select count(*), db_id from metabase_table group by db_id;
```

I have a solution in mind involving finer-grained caching but this would help me verify that this will work for your use case.

**Comment by apostoltego** [comment] 2024-08-27 20:01
<img width="277" alt="Screenshot 2024-08-27 at 21 56 17" src="https://github.com/user-attachments/assets/5888c184-e228-4e1f-9769-0080f47e4769">
I've added the active flag as well as tons of the table listed aren't active. 
There's loads of reasons but primarily older stuff that was present during the years and potentially metabase schema scans conflicting with dbt runs. Another big reason are Airbyte runs and schemas that were being scanned in the past that aren't now.

Furthermore, of all the databases there, only 2 of them are used by non-admins.

**Comment by FilmonK** [comment] 2024-08-30 22:44
Hey Team
Have a cloud customer on 1.50.23 running into something similar with admin and non-admin/sandboxed users.
I have a couple of their dashboards I can reference but we've been primarily looking at one.

<br>

General stats
Tables - 4,046 | 1,261-active | 2,785 - not active
Collections - 419

<br>

Admin user - 5 seconds
![admin_user](https://github.com/user-attachments/assets/33bc85f9-f702-405d-bae7-85cf07261d4b)

<br>

Non-admin user - 58 seconds
![non-admin_user](https://github.com/user-attachments/assets/9eee5b07-8477-40dc-9065-d9b23e424a38)

**Comment by noahmoss** [comment] 2024-09-03 18:57
Closing in favor of https://github.com/metabase/metabase/issues/47582 for the issue reported above

**Closed by noahmoss** 2024-09-03 18:57 UTC
Labels: Type:Bug, Priority:P2, .Performance, .Backend, .Team/Querying

**Comment by csp33** [comment] 2024-10-16 11:31
hi, this is still happening
https://github.com/metabase/metabase/issues/36442#issuecomment-2416530002

**Comment by paoliniluis** [comment] 2024-10-16 16:16
@csp33 please send us version and a reproduction so we can track this down

**Comment by csp33** [comment] 2024-10-17 07:14
Hi @paoliniluis

Metabase v0.50.29
Steps to reproduce:
1. Create this collections structure
  ![Image](https://github.com/user-attachments/assets/721a04cd-5aad-4574-ac71-6e717920cda7)

2. Create the following groups: `private collection viewers`, `public collection viewers`, `sub-private collection viewers` and `sub-public collection viewers`.
3. Apply the following permissions structure:
![Image](https://github.com/user-attachments/assets/e4ff19a3-087e-4ed1-a216-743e05646187)
![Image](https://github.com/user-attachments/assets/a3da3369-f4dd-48b6-a851-ba09cf77fe70)
![Image](https://github.com/user-attachments/assets/5e129e30-cb77-41a0-9160-7a58dd66dd66)
![Image](https://github.com/user-attachments/assets/74e9aa56-1ed0-4260-a424-c48f619021bd)
![Image](https://github.com/user-attachments/assets/49d56a0c-7f1b-4ccb-8594-a26bb7d60432)
![Image](https://github.com/user-attachments/assets/72abaf0d-3c11-43cc-9751-7bb37f2c45d4)

4. Give these groups to the viewer user 
    ![Image](https://github.com/user-attachments/assets/6e41afe6-78a1-4e3b-b54f-4feb0ec9e29f)
5. Login with the viewer user and check the `tree` endpoint load time
  ![Image](https://github.com/user-attachments/assets/3b25645e-bf5d-4843-b2ae-bdd062a2ce03)

6. Give `All Users` permission to view `Our analytics`. Login again with the viewer user and check the response time.
![Image](https://github.com/user-attachments/assets/b59d1a31-b5e4-48cf-b61d-f21a04428168)

  ![Image](https://github.com/user-attachments/assets/83718b65-1656-4434-b4c2-9a38f969f64b)


I know the difference is not significative here, but when the number of dashboards, users and groups increases, this difference grows exponentially.

Thanks for your time!
