### ISSUE TITLE
Static viz does not respect original chart colors

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#21506] opened 2022-04-07 01:55 UTC
**Describe the bug**
Subscriptions won't respect the original chart colors, which might confuse the users. This happens in line charts, bar charts, combo charts, area charts, pie chart

**Logs**
NA

**To Reproduce**
1) Build a question like Orders->Sum of quantity per created_at (month), you should get a green line
2) Add the question to a dashboard, and then do a subscription with it, send a test email.
3) see the line/area now in blue, or the pie chart with different colors

**Expected behavior**
Respect the original chart colors that were used in the chart in Metabase in the subscription

**Screenshots**
This is the chart in Metabase
![image](https://user-images.githubusercontent.com/1711649/162100902-a2296426-5f6e-4862-9c30-0da4ffe91672.png)

This is the chart in the subscription
![image](https://user-images.githubusercontent.com/1711649/162100927-0977d043-f92e-4ed9-a68d-b5aef40f5c70.png)

Happens the same with other viz's

EDIT: if you add another series to the line chart (let's say "Distinct value of Product ID"), it will invert the colors
Dashboard
![image](https://user-images.githubusercontent.com/1711649/162104990-ec879bab-aa2b-4f95-86a0-58ba65800017.png)

Subscription
![image](https://user-images.githubusercontent.com/1711649/162105016-3278265c-32cc-46d5-826a-189e4de6577c.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 20.04.4
- Your databases: Postgres 14
- Metabase version: 1.42.3
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14

**Severity**
Cosmetic

**Additional context**
NA

**Comment by WiNloSt** [comment] 2022-11-11 10:02
Note that https://github.com/metabase/metabase/pull/26211 address all charts' colors not matching except the pie chart.

**Comment by gusaiani** [comment] 2023-01-05 21:34
@paoliniluis I've been checking here, looks like this issue has been solved already.

Can you confirm, please?

**Comment by gusaiani** [comment] 2023-01-05 22:26
@paoliniluis, I've been experimenting and could not reproduce a case missing the color connection in static viz.

As written above, Kelvin implemented a chunk of this and mentions pie charts.
Even pie charts seem ok in my tests.

Can you confirm, please?

**Comment by paoliniluis** [comment] 2023-01-06 14:04
@gusaiani seems like @WiNloSt fixed it, I'll create a new one with the pie chart

**Comment by flamber** [comment] 2023-01-06 14:51
Closing in favor of #27547

**Closed by flamber** 2023-01-06 14:51 UTC
Labels: Type:Bug, Priority:P3, Visualization/Static
