### ISSUE TITLE
Select two/multiple fields for a foreign key display value

### ISSUE THREAD

**Issue by jabbett** [metabase/metabase#17080] opened 2021-07-15 18:46 UTC
**Is your feature request related to a problem? Please describe.**

Our database has a `people` table which doesn't have a single `name` field like most of our other tables. People have first, middle, and last names, and we generally concatenate those fields to display a person's full name. Foreign key relationships to the `people` table are many & numerous.

Metabase only allows us to choose a single field as a foreign key display value:

![image](https://user-images.githubusercontent.com/923971/125840309-98a6441a-1c5b-493f-a74a-42638d702b1e.png)

**Describe the solution you'd like**

I'd love to have the ability to choose First Name + Last Name as the display value — it would make so many of our Metabase questions/dashboards easier to read.

**Describe alternatives you've considered**

* I can fall back on the SQL editor to concatenate these fields manually, but we usually just avoid person-related queries because it's onerous. This, however, is not a solution for our non-SQL-savvy Metabase users.
* If I had full control of the database, I suppose could add a computed column that concatenates these name columns. But I only have read access.

**How important is this feature to you?**

Our database has 150 tables, and most tables have FK relationships to `people` at least once, and often several times (creator, updater, owner, etc.). Given how often we encounter this problem, it's pretty important.

**Comment by paoliniluis** [comment] 2021-07-15 20:37
Why can't you do a view at the DB and expose that view instead of the raw table?

**Comment by flamber** [comment] 2021-07-22 09:22
Duplicate of #9236

**Closed by flamber** 2021-07-22 09:22 UTC
Labels: .Needs Triage, Type:New Feature
