### ISSUE TITLE
Custom Logo Prevents Access to Hamburger Menu for left Nav

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#40337] opened 2024-03-20 00:05 UTC
### Describe the bug

When a custom logo is added to Metabase in v49 the hamburger menu may become unusable in some browsers. 

- The behavior seems to be specific to SVG files where the viewBox attribute isn't being utilized
- SVG files without the viewBox attribute set expand over the top of the menu

This issue did not present in Firefox for me but it's observable in current versions of Chrome and Edge browsers.

### To Reproduce

1. Launch Metabase Version 49 in Chrome or Edge
2. Upload custom SVG logo without viewBox attribute set (attached my test files)
3. Exit Admin
4. Try to collapse left hand nav

[
![test_logo_with_viewbox](https://github.com/metabase/metabase/assets/13661163/bd7fcf83-5292-4bab-af31-247cfaad8fac)
![test_logo_no_viewbox](https://github.com/metabase/metabase/assets/13661163/3629e607-0efd-4181-abf0-dfd67383d42f)
](url)

### Expected behavior

The hamburger menu should be accessible

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.15.133.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.22 (Debian 11.22-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-14",
      "tag": "v1.49.0",
      "hash": "46c668b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Severe - if someone upgrades with a logo file that creates this nav issue it could be really impactful

**Comment by paoliniluis** [comment] 2024-03-20 00:11
Duplicate of https://github.com/metabase/metabase/issues/40153

**Comment by paoliniluis** [comment] 2024-03-20 14:51
fixed

**Closed by paoliniluis** 2024-03-20 14:51 UTC
Labels: Type:Bug, Priority:P1, Browser:Chrome, .Frontend, .Needs Triage, .Escalation
