### ISSUE TITLE
Ability to apply group labels to columns in the UI

### ISSUE THREAD

**Issue by jack-cook-repo** [metabase/metabase#26098] opened 2022-10-25 16:46 UTC
Currently if you have a table with lots of columns it's not easy to scroll through to get what you're looking for - it'd be great to be able to put columns into logical groups to make it easier to navigate.

**Describe the solution you'd like**

This would be quite similar to Looker's [group labels](https://cloud.google.com/looker/docs/reference/param-field-group-label)

**Comment by flamber** [comment] 2022-10-26 11:56
Duplicate of #3216

**Closed by flamber** 2022-10-26 11:56 UTC
Labels: Type:New Feature, .Needs Triage
