### ISSUE TITLE
Error: duplicate column name. Found at custom question that uses as source a question with joins

### ISSUE THREAD

**Issue by filipetoyoshima** [metabase/metabase#12731] opened 2020-06-17 16:21 UTC
**Describe the bug**

I created a question that joins tables. The result has some columns with the same name. Creating a new custom question with the prior question as source throws an error "duplicate column name". May be related with #7959

**Logs**

I believe that it won't be necessary. The problem seems to be related to the SQL generation (more details at the Screenshots section).

I may edit it and include the logs if the staff judges it necessary.

**To Reproduce**

1. Create a question. This question must join tables and select different columns with the same name.
2. Create a new question, using the prior question as a source.
3. Try to visualize the results (raw, just after selecting the source).
4. See the message "duplicate column name"

**Expected behavior**

As I did nothing but select the source of my question, I'd expect to see the same results that I had on the original question.

**Screenshots**

This is the SQL generated from the original question "Lista de Clientes". Note that the statement `AS 'name'` is duplicated, it references both `'source'.'name'` and `'Office'.'name'`. As said on #7959, this is no problem to the question itself.

![image](https://user-images.githubusercontent.com/29482983/84920446-8bca5780-b099-11ea-91e6-160409b1f863.png)

----------------------

But when using this question as a source to a new custom question, this is what I get:

![image](https://user-images.githubusercontent.com/29482983/84918306-d0a0bf00-b096-11ea-8837-be59a3ac9a82.png)

<details>
  <summary><b>Information about your Metabase Installation:</b></summary>

- Your browser and the version: Chrome 83.0.4103.61 (Official Build) (64-bit)
- Your operating system: Ubuntu 18.04
- Your databases: MySQL
- Metabase version: 0.35.4
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

More details:

```json
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.173-137.229.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": "America/Sao_Paulo"
    }
  }
}
```

</details>

**Severity**

Since I've found a workaround, it's annoying. But very annoying. And makes the expansion of my dashboards a lot harder.

**Additional context**

The original question "Lista de Clientes" uses another question as a source, which is built with native SQL. But it just a simple `select *, function(params) from table`. (because I didn't find anything about using SQL function at Metabase)

**Workaround**

Since this is a SQL problem, converting the question to a SQL question and manually changing one of the `AS 'name'` statements solves the problem. It's very annoying because it becomes necessary to declare every dashboard filter you may use. And, also, it may block dashboard filters on any custom question that use this one as a source.

Something like that:

![image](https://user-images.githubusercontent.com/29482983/84922697-9cc89800-b09c-11ea-8d8a-cd946ab599a4.png)

**Comment by sbelak** [comment] 2020-06-17 17:30
This looks like a duplicate of #10511

**Comment by filipetoyoshima** [comment] 2020-06-17 18:02
Yeah, I think it really is.

**Closed** 2020-06-17 18:15 UTC
Labels: .Needs Triage, Type:Bug
