### ISSUE TITLE
Subscription fails, when there's specific characters that causes Markdown failure

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20993] opened 2022-03-14 16:48 UTC
**Describe the bug**
Subscription fails, when there's specific characters that causes Markdown failure.
Regression since 0.42.0

**To Reproduce**
1. Dashboard > add Textbox
```
- test (1;1)
- test2 (2 2)
- test3 [3;3]
- test4 [4 4] - the problematic one
```
2. Add some random question, so Subscription is allowed
3. Trying to send the subscription will fail with "Sending failed" - log says `Illegal character in path at index 1: 4 4`

<details><summary>Full stacktrace</summary>

```
2022-03-14 17:45:53,271 ERROR middleware.log :: POST /api/pulse/test 500 62.8 ms (26 DB calls) 
{:via
 [{:type java.lang.IllegalArgumentException,
   :message "Illegal character in path at index 1: 4 4",
   :at [java.net.URI create "URI.java" 883]}
  {:type java.net.URISyntaxException,
   :message "Illegal character in path at index 1: 4 4",
   :at [java.net.URI$Parser fail "URI.java" 2913]}],
 :trace
 [[java.net.URI$Parser fail "URI.java" 2913]
  [java.net.URI$Parser checkChars "URI.java" 3084]
  [java.net.URI$Parser parseHierarchical "URI.java" 3166]
  [java.net.URI$Parser parse "URI.java" 3125]
  [java.net.URI <init> "URI.java" 600]
  [java.net.URI create "URI.java" 881]
  [java.net.URI resolve "URI.java" 1066]
  [metabase.pulse.markdown$resolve_uri invokeStatic "markdown.clj" 200]
  [metabase.pulse.markdown$resolve_uri invoke "markdown.clj" 191]
  [metabase.pulse.markdown$fn$reify$reify__57939 resolveLink "markdown.clj" 318]
  [com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer resolveLink "HtmlRenderer.java" 599]
  [com.vladsch.flexmark.html.renderer.CoreNodeRenderer render "CoreNodeRenderer.java" 757]
  [com.vladsch.flexmark.html.renderer.NodeRenderingHandler render "NodeRenderingHandler.java" 16]
  [com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer renderNode "HtmlRenderer.java" 779]
  [com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer renderChildrenNode "HtmlRenderer.java" 798]
  [com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer renderChildren "HtmlRenderer.java" 790]
  [com.vladsch.flexmark.html.renderer.CoreNodeRenderer renderTextBlockParagraphLines "CoreNodeRenderer.java" 256]
  [com.vladsch.flexmark.html.renderer.CoreNodeRenderer render "CoreNodeRenderer.java" 317]
  [com.vladsch.flexmark.html.renderer.NodeRenderingHandler render "NodeRenderingHandler.java" 16]
  [com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer renderNode "HtmlRenderer.java" 779]
  [com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer renderChildrenNode "HtmlRenderer.java" 798]
  [com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer renderChildren "HtmlRenderer.java" 790]
  [com.vladsch.flexmark.html.renderer.CoreNodeRenderer lambda$renderListItem$5 "CoreNodeRenderer.java" 226]
  [com.vladsch.flexmark.util.html.HtmlAppendableBase tag "HtmlAppendableBase.java" 349]
  [com.vladsch.flexmark.util.html.HtmlAppendableBase tagLine "HtmlAppendableBase.java" 398]
  [com.vladsch.flexmark.html.renderer.CoreNodeRenderer renderListItem "CoreNodeRenderer.java" 224]
  [com.vladsch.flexmark.html.renderer.CoreNodeRenderer render "CoreNodeRenderer.java" 215]
  [com.vladsch.flexmark.html.renderer.NodeRenderingHandler render "NodeRenderingHandler.java" 16]
  [com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer renderNode "HtmlRenderer.java" 779]
  [com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer renderChildrenNode "HtmlRenderer.java" 798]
  [com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer renderChildren "HtmlRenderer.java" 790]
  [com.vladsch.flexmark.html.renderer.CoreNodeRenderer lambda$render$3 "CoreNodeRenderer.java" 205]
  [com.vladsch.flexmark.util.html.HtmlAppendableBase tag "HtmlAppendableBase.java" 349]
  [com.vladsch.flexmark.util.html.HtmlAppendableBase tagIndent "HtmlAppendableBase.java" 405]
  [com.vladsch.flexmark.html.renderer.CoreNodeRenderer render "CoreNodeRenderer.java" 205]
  [com.vladsch.flexmark.html.renderer.NodeRenderingHandler render "NodeRenderingHandler.java" 16]
  [com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer renderNode "HtmlRenderer.java" 779]
  [com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer renderChildrenNode "HtmlRenderer.java" 798]
  [com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer renderChildren "HtmlRenderer.java" 790]
  [com.vladsch.flexmark.html.renderer.CoreNodeRenderer render "CoreNodeRenderer.java" 113]
  [com.vladsch.flexmark.html.renderer.NodeRenderingHandler render "NodeRenderingHandler.java" 16]
  [com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer renderNode "HtmlRenderer.java" 761]
  [com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer render "HtmlRenderer.java" 683]
  [com.vladsch.flexmark.html.HtmlRenderer render "HtmlRenderer.java" 213]
  [com.vladsch.flexmark.html.HtmlRenderer render "HtmlRenderer.java" 197]
  [com.vladsch.flexmark.html.HtmlRenderer render "HtmlRenderer.java" 230]
  [metabase.pulse.markdown$fn__57954 invokeStatic "markdown.clj" 340]
  [metabase.pulse.markdown$fn__57954 invoke "markdown.clj" 337]
  [clojure.lang.MultiFn invoke "MultiFn.java" 234]
  [metabase.email.messages$render_result_card invokeStatic "messages.clj" 412]
  [metabase.email.messages$render_result_card invoke "messages.clj" 408]
  [metabase.email.messages$render_message_body$fn__58979$fn__58980 invoke "messages.clj" 459]
  [clojure.core$mapv$fn__8468 invoke "core.clj" 6914]
  [clojure.core.protocols$fn__8181 invokeStatic "protocols.clj" 168]
  [clojure.core.protocols$fn__8181 invoke "protocols.clj" 124]
  [clojure.core.protocols$fn__8136$G__8131__8145 invoke "protocols.clj" 19]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
  [clojure.core.protocols$fn__8168 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8168 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8110$G__8105__8123 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6830]
  [clojure.core$mapv invokeStatic "core.clj" 6905]
  [clojure.core$mapv invoke "core.clj" 6905]
  [metabase.email.messages$render_message_body$fn__58979 invoke "messages.clj" 459]
  [metabase.email.messages$render_message_body invokeStatic "messages.clj" 458]
  [metabase.email.messages$render_message_body invoke "messages.clj" 456]
  [metabase.email.messages$render_pulse_email invokeStatic "messages.clj" 485]
  [metabase.email.messages$render_pulse_email invoke "messages.clj" 482]
  [metabase.pulse$fn__74941 invokeStatic "pulse.clj" 293]
  [metabase.pulse$fn__74941 invoke "pulse.clj" 282]
  [clojure.lang.MultiFn invoke "MultiFn.java" 239]
  [metabase.pulse$results__GT_notifications$iter__74971__74975$fn__74976 invoke "pulse.clj" 345]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5419 invokeStatic "core.clj" 139]
  [clojure.core$seq__5419 invoke "core.clj" 139]
  [metabase.pulse$send_notifications_BANG_ invokeStatic "pulse.clj" 387]
  [metabase.pulse$send_notifications_BANG_ invoke "pulse.clj" 386]
  [metabase.pulse$send_pulse_BANG_ invokeStatic "pulse.clj" 415]
  [metabase.pulse$send_pulse_BANG_ doInvoke "pulse.clj" 395]
  [clojure.lang.RestFn invoke "RestFn.java" 410]
  [metabase.api.pulse$fn__75935 invokeStatic "pulse.clj" 211]
  [metabase.api.pulse$fn__75935 invoke "pulse.clj" 197]
  [compojure.core$wrap_response$fn__32273 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__32257 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__32262 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__32266 invoke "core.clj" 151]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32266 invoke "core.clj" 153]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32266 invoke "core.clj" 153]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32266 invoke "core.clj" 153]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32266 invoke "core.clj" 152]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__65369 invoke "auth.clj" 14]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285 invoke "core.clj" 200]
  [compojure.core$make_context$handler__32313 invoke "core.clj" 289]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 299]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [metabase.api.routes$fn__76493$fn__76496 invoke "routes.clj" 56]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__76638$fn__76639 doInvoke "routes.clj" 57]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285 invoke "core.clj" 200]
  [compojure.core$make_context$handler__32313 invoke "core.clj" 289]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 299]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32266 invoke "core.clj" 153]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32266 invoke "core.clj" 153]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32266 invoke "core.clj" 153]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [metabase.server.routes$fn__76626$fn__76628 invoke "routes.clj" 41]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__73621 invoke "exceptions.clj" 98]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__73618 invoke "exceptions.clj" 86]
  [metabase.server.middleware.log$log_api_call$fn__77104$fn__77105$fn__77106 invoke "log.clj" 209]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 15]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 9]
  [metabase.server.middleware.log$log_api_call$fn__77104$fn__77105 invoke "log.clj" 201]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.server.middleware.log$log_api_call$fn__77104 invoke "log.clj" 200]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__80457 invoke "browser_cookie.clj" 38]
  [metabase.server.middleware.security$add_security_headers$fn__55229 invoke "security.clj" 148]
  [metabase.server.middleware.json$wrap_json_body$fn__79612 invoke "json.clj" 62]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__79630 invoke "json.clj" 98]
  [metabase.server.middleware.offset_paging$handle_paging$fn__55253 invoke "offset_paging.clj" 42]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__80724 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__80740 invoke "params.clj" 69]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__34379 invoke "misc.clj" 59]
  [metabase.server.middleware.session$bind_current_user$fn__45722$fn__45723 invoke "session.clj" 262]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 243]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 235]
  [metabase.server.middleware.session$bind_current_user$fn__45722 invoke "session.clj" 261]
  [metabase.server.middleware.session$wrap_current_user_info$fn__45709 invoke "session.clj" 221]
  [metabase.server.middleware.session$wrap_session_id$fn__45695 invoke "session.clj" 167]
  [metabase.server.middleware.auth$wrap_api_key$fn__65377 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__80644 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__34362 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__34387 invoke "misc.clj" 76]
  [ring.middleware.gzip$wrap_gzip$fn__80686 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__34390 invoke "misc.clj" 93]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__80473 invoke "ssl.clj" 38]
  [metabase.server$async_proxy_handler$fn__76877 invoke "server.clj" 73]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 388]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 633]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 380]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 277]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 338]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 315]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 173]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 131]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 386]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 883]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1034]
  [java.lang.Thread run "Thread.java" 829]],
 :cause "Illegal character in path at index 1: 4 4",
 :message "Illegal character in path at index 1: 4 4"}
```

</details>

**Information about your Metabase Installation:**
Tested 0.41.6 thru 0.42.2 - regression since 0.42.0

**Comment by noahmoss** [comment] 2022-03-14 19:42
The exception only seems to be thrown for email subscriptions. Slack subscriptions don't fail, but the bracket characters are missing.

This appears to be a bug in [flexmark-java](https://github.com/vsch/flexmark-java) which is the library we use for Markdown parsing on the backend. It interprets a standalone set of square brackets as part of a [link reference](https://spec.commonmark.org/0.30/#link-reference-definition) with a null reference, but this is not the expected behavior according to the CommonMark spec.

I just asked about this on [this closed issue](https://github.com/vsch/flexmark-java/issues/460) in the flexmark-java repo. If this can't be fixed in flexmark-java I think we can figure out a hacky fix in Metabase, but in the meantime, the workaround is to escape both brackets with a backslash, like so: `\[4 4\]`

**Closed** 2022-03-17 17:57 UTC
Labels: Type:Bug, Priority:P2, .Backend, .Regression, Visualization/Static
