### ISSUE TITLE
Wrong data labels in line chart

### ISSUE THREAD

**Issue by Hennisa** [metabase/metabase#3669] opened 2016-10-25 12:57 UTC
- Browser and the version: Chrome 53.0.2785.143 (64-bit)
- Operating system: OS X 10.11.6
- DB: Redshift
- Metabase internal database: Postgres
- Metabase version 0.20.1
- Metabase hosting environment: Elastic Beanstalk

I'm summing data in custom SQL for multiple series:
sum(x1) AS "Test_1",
sum(x2) AS "Test_2",
sum(x3) AS "Test_3"

When I visualize this in a line chart I get wrong datapoint labels. They all have label Test_1 even though my series should have individual names:

<img width="433" alt="screen shot 2016-10-25 at 14 47 21" src="https://cloud.githubusercontent.com/assets/14327271/19686634/5614b48c-9ac2-11e6-97b6-7829c41260f3.png">

<img width="377" alt="screen shot 2016-10-25 at 14 47 36" src="https://cloud.githubusercontent.com/assets/14327271/19686815/322b2410-9ac3-11e6-901a-0874aa8f31ed.png">

<img width="403" alt="screen shot 2016-10-25 at 14 47 43" src="https://cloud.githubusercontent.com/assets/14327271/19686818/35c38aea-9ac3-11e6-80d1-6444d63b5c35.png">

**Comment by vlopez** [comment] 2016-10-28 17:35
I am experienced the same behaviour, our select expression looks something like this:

`count(case when bank_code = 000 then 1 end) as 'Bank1',`

**Comment by lachesis** [comment] 2016-11-07 23:28
I'm also experiencing this. Is there anything I can do to make this easier to debug?

**Comment by andreialbu** [comment] 2016-12-12 08:40
Isn't this the duplicate of https://github.com/metabase/metabase/issues/3599 ? I thought I saw it coming for v0.21, but somehow it didn't make it there.

**Comment by salsakran** [comment] 2016-12-14 23:18
fixed by #3848

**Closed by salsakran** 2016-12-14 23:18 UTC
Labels: Bug, Visualization
