### ISSUE TITLE
Sync fails constantly for BigQuery tables that has required partition filter

### ISSUE THREAD

**Issue by shay-rf** [metabase/metabase#22723] opened 2022-05-13 22:53 UTC
**Describe the bug**
For all BigQuery tables that have a required partition filter - for example date field, the sync/fingerprint process constantly fails and issue an exception.

We have many of those and logs is filled with those exceptions

**Logs**

WARN metabase.sync.util Error fingerprinting Table

at metabase.driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:224)

Caused by: clojure.lang.ExceptionInfo: Cannot query over table 'foo' without a filter over column(s) 'date' that can be used for partition elimination {"code" 400, "errors" [{"domain" "global", "location" "q", "locationType" "parameter", "message" "Cannot query over table 'foo' without a filter over column(s) 'date' that can be used for partition elimination", "reason" "invalidQuery"}], "message" "Cannot query over table 'foo' without a filter over column(s) 'date' that can be used for partition elimination", "status" "INVALID_ARGUMENT"}

**To Reproduce**
Just have a BigQuery table with required partition-filter field and check the logs.

**Expected behavior**
Not sure what should be the correct way to handle this - maybe provide some way to express what should be the default value of this field to allow syncing this table.

**Comment by flamber** [comment] 2022-05-14 07:32
Duplicate of #14490

**Closed by flamber** 2022-05-14 07:32 UTC
Labels: Type:Bug, .Needs Triage
