### ISSUE TITLE
Card number with big numbers does not scale well on mobiles/portrait

### ISSUE THREAD

**Issue by brailateo** [metabase/metabase#23394] opened 2022-06-16 18:05 UTC
**Describe the bug**
Card number with big numbers such as 110,753,373 does not scale well on mobiles/portrait, I can't see the last three digits

**Logs**
not available

**To Reproduce**
1. make a dashboard with a big card number (110,753,373)
2. check it on a mobile phone in portrait mode
3. the number is truncated

**Expected behavior**
To see the whole number as it looks on desktop version

**Screenshots**
2 files attached

**Information about your Metabase Installation:**
- Metabase version 0.43.3
- Google Chrome 102.0.5005.125 on Android 11 (or Brave)

**Severity**
 blocking some users
![desktop](https://user-images.githubusercontent.com/602966/174136644-52f1e2f5-be86-4f4e-af24-ca3a34f60d7c.jpg)
![mobile](https://user-images.githubusercontent.com/602966/174136646-236d904a-a89a-4db5-bbe6-6f25e19b1f95.jpg)

**Additional context**

**Comment by flamber** [comment] 2022-06-17 10:06
Duplicate of #23093

**Closed by flamber** 2022-06-17 10:06 UTC
Labels: Type:Bug, .Needs Triage
