### ISSUE TITLE
CSV download should not be limited to 10,000

### ISSUE THREAD

**Issue by luqmansyauqi** [metabase/metabase#3936] opened 2016-12-13 07:37 UTC
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Chrome 53.0.2785.143
- OSX 10.10
- Postgres, MySQL
- Metabase version v0.21.0
- Metabase hosting environment: Ubuntu16.04
- Metabase internal database: Postgres 9.5

- *Repeatable steps to reproduce the issue*
Based on this pull request: **Loosen CSV download limits** https://github.com/metabase/metabase/pull/1496 , there should be no limit on downloading the CSV file (based on this, the limit should be like 1 million rows), however we found out that the limit is still 10,000 rows with some steps below to reproduce the issue:

**1. Create a new question (which is resulting more than 10,000 record)**
To make it simple, we can create the question with **Sample Dataset** using table **"PUBLIC"."ORDERS"**, let's check the number of records first:
<img width="1226" alt="screen shot 2016-12-13 at 2 31 37 pm" src="https://cloud.githubusercontent.com/assets/13912558/21131422/2c743abc-c141-11e6-88e2-c2846c480eaa.png">
Just to make sure that the number of records is more than 10,000, then we can create below question:
<img width="1203" alt="screen shot 2016-12-13 at 2 35 06 pm" src="https://cloud.githubusercontent.com/assets/13912558/21131461/62268dd6-c141-11e6-9a3b-e8846a1c732b.png">

**2. Download the result**
And yes the result in CSV only contains 10,000 records
<img width="786" alt="screen shot 2016-12-13 at 2 36 06 pm" src="https://cloud.githubusercontent.com/assets/13912558/21131497/916d0fb6-c141-11e6-9109-f0b283a50ea3.png">

So, this is bug right? Or is there any config to set up the hard limit of CSV download? Please advise.

Thanks for being part of the Metabase project!
-------

**Comment by camsaul** [comment] 2016-12-13 19:44
Hi @luqmansyauqi, this isn't a bug, but rather intended behavior. We already have an open issue to remove or otherwise address this limit: #3810.

Closing as duplicate.

**Closed by camsaul** 2016-12-13 19:44 UTC
Labels: Duplicate
