### ISSUE TITLE
Need Minutes and Seconds while configuring an alert

### ISSUE THREAD

**Issue by sajiljosephs** [metabase/metabase#25746] opened 2022-10-03 07:49 UTC
**Is your feature request related to a problem? Please describe.**
Need Minutes and Seconds while configuring an alert

**Describe the solution you'd like**
Need Minutes and Seconds while configuring an alert

**How important is this feature to you?**
Verymuch required

**Comment by flamber** [comment] 2022-10-03 07:55
Duplicate of #6648

**Closed by flamber** 2022-10-03 07:55 UTC
Labels: Type:New Feature, .Needs Triage
