### ISSUE TITLE
[bug] Not all filters visible on questions.

### ISSUE THREAD

**Issue by that0n3guy** [metabase/metabase#6161] opened 2017-10-12 20:00 UTC
Description:
Filters are hidden from view (can not be seen, but still work) on question with more than 2 filters.

### Bug
- Your browser and the version: Chrome 61.0.3163.100 (Official Build) (64-bit)
- Your operating system: Windows 10
- Your databases: Mysql
- Metabase version: v0.26.1
- Metabase hosting environment: Docker
- Metabase internal database: Mysql

*Repeatable steps to reproduce the issue*

- Create a question
- filter by a date between 2 dates
- Add 2 more filters

Only 2 filters will show the 3rd will be hidden behind the "view" section.

See this image: 
![image](https://user-images.githubusercontent.com/113870/31516301-b9780b18-af5d-11e7-8c08-319473a5bc8d.png)

More proof there is a filter there, its just hidden:
![image](https://user-images.githubusercontent.com/113870/31516589-ae75e86a-af5e-11e7-8e5a-6a4b718bd49f.png)

Notes:
I can't find another issue like this one, even though there has to be one b/c this is so easily duplicated.

Its not a small screen issue, I have a 27" screen.

**Comment by mazameli** [comment] 2017-10-12 20:06
Yeah, dupe of https://github.com/metabase/metabase/issues/5470

**Closed by mazameli** 2017-10-12 20:06 UTC
Labels: Duplicate
