### ISSUE TITLE
Audit visualizations does not show correct information, when there's more than 1000 aggregated dates

### ISSUE THREAD

**Issue by ukritw** [metabase/metabase#17820] opened 2021-09-09 08:27 UTC
**Describe the bug**
Audit log not showing active users since Oct 2019.

**Active users is incorrect**
1. Admin > Audit
2. The overview doesn't show number of active users after Oct 2019.
_see stats for details_

**Comment by ukritw** [comment] 2021-09-09 08:28
@flamber this bug happens in our stats instance, now running on EE.

**Comment by flamber** [comment] 2021-09-09 09:52
The no active users. I don't understand why it's not working. But the numbers are completely wrong.
Perhaps it's hitting a query limit, or a dropping something, when it's mapping the two results.
https://github.com/metabase/metabase/blob/master/enterprise/backend/src/metabase_enterprise/audit/pages/users.clj#L29-L55
Feels like a possible P1 correctness, since I don't think this is specific to our data.

The missing members is caused by stats not having `core_user.sso_source`
Seems like it has been manually removed, since [migration 90](https://github.com/metabase/metabase/blob/master/resources/migrations/000_migrations.yaml#L5168-L5184) was correctly executed.
This is an internal ops problem.

I can also see that we send requests twice for all charts, so there's also a P2 performance issue.

**Comment by camsaul** [comment] 2021-09-29 18:16
Investigating this. It works for me locally...

actual SQL that gets executed is 

```sql
WITH "last_query" AS (
  SELECT
    "executor_id" AS "id",
    max("started_at") AS "started_at"
  FROM
    "query_execution"
  GROUP BY
    "executor_id"
),
"groups" AS (
  SELECT
    "u"."id" AS "id",
    string_agg("pg"."name", ', ') AS "groups"
  FROM
    "core_user" "u"
    LEFT JOIN "permissions_group_membership" "pgm" ON "u"."id" = "pgm"."user_id"
    LEFT JOIN "permissions_group" "pg" ON "pgm"."group_id" = "pg"."id"
  GROUP BY
    "u"."id"
),
"questions_saved" AS (
  SELECT
    "u"."id" AS "id",
    count(*) AS "count"
  FROM
    "report_card" "c"
    LEFT JOIN "core_user" "u" ON "u"."id" = "c"."creator_id"
  GROUP BY
    "u"."id"
),
"dashboards_saved" AS (
  SELECT
    "u"."id" AS "id",
    count(*) AS "count"
  FROM
    "report_dashboard" "d"
    LEFT JOIN "core_user" "u" ON "u"."id" = "d"."creator_id"
  GROUP BY
    "u"."id"
),
"pulses_saved" AS (
  SELECT
    "u"."id" AS "id",
    count(*) AS "count"
  FROM
    "pulse" "p"
    LEFT JOIN "core_user" "u" ON "u"."id" = "p"."creator_id"
  GROUP BY
    "u"."id"
),
"users" AS (
  SELECT
    concat("u"."first_name", ' ', "u"."last_name") AS "name",
    CASE
      WHEN "u"."is_superuser" = TRUE THEN 'Admin'
      ELSE 'User'
    END AS "role",
    "id",
    "date_joined",
    CASE
      WHEN "u"."sso_source" IS NULL THEN 'Email'
      ELSE "u"."sso_source"
    END AS "signup_method",
    "last_name",
    "first_name"
  FROM
    "core_user" "u"
)
SELECT
  "u"."id" AS "user_id",
  "u"."name",
  "u"."role",
  "groups"."groups",
  "u"."date_joined",
  "last_query"."started_at" AS "last_active",
  "u"."signup_method",
  "questions_saved"."count" AS "questions_saved",
  "dashboards_saved"."count" AS "dashboards_saved",
  "pulses_saved"."count" AS "pulses_saved"
FROM
  "users" "u"
  LEFT JOIN "groups" ON "u"."id" = "groups"."id"
  LEFT JOIN "last_query" ON "u"."id" = "last_query"."id"
  LEFT JOIN "questions_saved" ON "u"."id" = "questions_saved"."id"
  LEFT JOIN "dashboards_saved" ON "u"."id" = "dashboards_saved"."id"
  LEFT JOIN "pulses_saved" ON "u"."id" = "pulses_saved"."id"
ORDER BY
  lower("u"."last_name") ASC,
  lower("u"."first_name") ASC
LIMIT
  1000 OFFSET 0
```

**Comment by camsaul** [comment] 2021-09-29 18:29
So, the query itself is fine -- the root issue is that the `:sso_source` column in the Users table somehow went missing (???) -- I think we should consider closing this issue out and investigating where `:sso_source` went separately.

I also opened #18124 so we can make sure the error messages are displayed in the FE when something like this happens

**Comment by flamber** [comment] 2021-09-30 08:35
@camsaul There's two issues here.
1. P1, the "Active members and new members per day" (first graph on stats > Admin > Audit) is incorrect. And this is very likely caused by the amount of activity/users stats has. Everything looks fine on my local instances too.
2. core_user.sso_source missing on stats for some obscure reason. That's also a P1, but it's an internal ops problem.
3. (And then I noticed all requests are sent twice, which is a P2 performance issue, but I'll create an issue for that.)

**Comment by rlotun** [comment] 2021-09-30 17:59
Can we close this and open two other issues - a metaboat issue for the internal ops problem, and a P2 perf bug we can investigate separately? thanks!

**Comment by flamber** [comment] 2021-09-30 18:02
@rlotun And what about the P1, which is the main reason for this issue?
> 1. P1, the "Active members and new members per day" (first graph on stats > Admin > Audit) is incorrect. And this is very likely caused by the amount of activity/users stats has. Everything looks fine on my local instances too.

**Comment by rlotun** [comment] 2021-10-01 16:44
Oh I missed that - I thought it was due to the ops issue. Are you suggesting the graph is incorrect for another reason - something to do with a certain scale of users or activities?

**Comment by flamber** [comment] 2021-10-01 17:01
@rlotun Yes, please go to stats > Admin > Audit > first graph (Active members and new members per day), and tell me how many active members you think there has been since October 2019. My guess is more than zero, which is what it is showing.

I'm quite sure this is not something specific to our data, but simply just the amount of data, which causes this.
It could perhaps be fixed by only showing the past 2 years, or changing granularity. But probably worth checking the code to find what the reason is.

**Comment by paoliniluis** [comment] 2021-10-05 21:34
Just received this from a trialer. Check ticket 6673

**Comment by paoliniluis** [comment] 2021-10-05 23:18
"Query views and speed per day" is also broken, showing till 2019

**Comment by rlotun** [comment] 2021-11-02 06:04
After https://github.com/metabase/metabase/pull/18583 has gone in i checked the questions, databases, and dashboards overview in audit and they seem to now be returning data, but it would be great if @ukritw and @flamber can confirm things are looking correct now. Thank you.

**Comment by flamber** [comment] 2021-11-02 08:49
@rlotun Yes, it looks correct. I'm guessing #18583 should be backported?

**Comment by ukritw** [comment] 2021-11-02 09:05
What's the definition of active users in this case? 
In https://stats.metabase.com/admin/people, I see that we have 56 active accounts but I guess we define this as someone who's actually using Metabase.

Also, the **All members** tab seems to be broken.
<img width="1676" alt="Screen Shot 2021-11-02 at 4 03 05 PM" src="https://user-images.githubusercontent.com/2685753/139817055-b6e380d4-623c-491c-847b-5a217cc7ca34.png">

**Comment by flamber** [comment] 2021-11-02 09:12
@ukritw That's an internal ops problem, not a general problem. https://github.com/metabase/metabase-ops/issues/352

**Comment by rlotun** [comment] 2021-11-04 15:54
> @rlotun Yes, it looks correct. I'm guessing #18583 should be backported?

Yeah that PR was just merged. Thanks I'll close this.

**Closed by rlotun** 2021-11-04 15:54 UTC
Labels: Type:Bug, Priority:P1, .Correctness, Administration/Audit
