### ISSUE TITLE
Row Bar Chart collapses when there is value 0 in the last record

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#14285] opened 2021-01-06 18:51 UTC
```sql
with temp as (
    select 'a' col1, 25 col2
    union all 
    select 'b', 10
    union all 
    select 'c', 15
    union all 
    select 'd', 0
    union all
    select 'e', 30
    union all 
    select 'f', 35
)
select * from temp
--order by 2 desc
```
In the first image  the `order by` clause is commented out. In the second image the `order by` clause is being evaluated (therefore the record with the value 0 in its second column is placed in the last row).  
This is in addition to the issue #13769 which is apparent in the images.

![raw](https://user-images.githubusercontent.com/15974735/103808163-62a8ee80-500c-11eb-8281-1cd5631ba378.png)

![raw2](https://user-images.githubusercontent.com/15974735/103808167-63da1b80-500c-11eb-877f-ce62e9440d34.png)

v .37.2

**Comment by flamber** [comment] 2021-01-06 19:09
Hi @vvaezian 
I would almost say it's a duplicate of #7544, since it only happens on Firefox, but leaving this because it's a different trigger.

**Closed** 2021-06-25 19:01 UTC
Labels: .Reproduced, Browser:Firefox, Priority:P2, Type:Bug, Visualization/Charts
