### ISSUE TITLE
GUI time period selector can cause blank screen under some circumstances

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#26265] opened 2022-11-07 10:48 UTC
**Describe the bug**
GUI time period selector can cause blank screen (crashes frontend) under some circumstances, requiring a browser refresh to recover.

**To Reproduce**
There's likely [other ways of reproducing](https://discourse.metabase.com/t/data-visualization-display-exception/22588), but they are causing the same TypeErrrors
1. Question > Sample > Products
2. Filter CreatedAt relative previous 30 days starting from 7 days ago
3. Summarize Count by CreatedAt:Month
![image](https://user-images.githubusercontent.com/1447303/200288892-9da121d2-82e7-41bd-9ef3-9dc7936b33fc.png)
4. Shows "No results" as expected, click the bottom time period selector and just click Apply - ends in blank screen
![image](https://user-images.githubusercontent.com/1447303/200290596-03f17660-0999-464a-a31d-09d9ad74fc51.png)

Browser console errors:
```
TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at Join.ts:710:50
    at i (Join.ts:710:50)
    at new o (MBQLClause.ts:13:5)
    at y.<anonymous> (Aggregation.ts:17:42)
    at new y (Filter.ts:36:22)
    at StructuredQuery.ts:858:26
    at Array.map (<anonymous>)
    at n.value (StructuredQuery.ts:857:39)
    at memoizeClass.ts:54:58
    at c (memoizeClass.ts:11:19)
oa @ react-dom.production.min.js:209
Ma.o.componentDidCatch.n.callback @ react-dom.production.min.js:227
vo @ react-dom.production.min.js:131
ua @ react-dom.production.min.js:212
Ml @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
wl @ react-dom.production.min.js:248
ll @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
N @ react-dom.production.min.js:287
Zt @ react-dom.production.min.js:68

TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at Join.ts:710:50
    at i (Join.ts:710:50)
    at new o (MBQLClause.ts:13:5)
    at y.<anonymous> (Aggregation.ts:17:42)
    at new y (Filter.ts:36:22)
    at StructuredQuery.ts:858:26
    at Array.map (<anonymous>)
    at n.value (StructuredQuery.ts:857:39)
    at memoizeClass.ts:54:58
    at c (memoizeClass.ts:11:19)
oa @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
vo @ react-dom.production.min.js:131
ua @ react-dom.production.min.js:212
Ml @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
wl @ react-dom.production.min.js:248
ll @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
N @ react-dom.production.min.js:287
Zt @ react-dom.production.min.js:68

Uncaught TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at Join.ts:710:50
    at i (Join.ts:710:50)
    at new o (MBQLClause.ts:13:5)
    at y.<anonymous> (Aggregation.ts:17:42)
    at new y (Filter.ts:36:22)
    at StructuredQuery.ts:858:26
    at Array.map (<anonymous>)
    at n.value (StructuredQuery.ts:857:39)
    at memoizeClass.ts:54:58
    at c (memoizeClass.ts:11:19)
```

**Information about your Metabase Installation:**
Tested 0.44.6

**Comment by nemanjaglumac** [comment] 2024-06-24 18:33
The error looks like MLv1. Most likely fixed by the changes in MLv2.

I'm closing this issue without adding an explicit reproduction for it because we already have multiple tests that have this query structure.

**Closed by nemanjaglumac** 2024-06-24 18:33 UTC
Labels: Type:Bug, Priority:P2, .Backend, Querying/Notebook, .Team/QueryingComponents
