### ISSUE TITLE
Dashboard Date range filter to google Analytics data not working

### ISSUE THREAD

**Issue by sashankQ** [metabase/metabase#6272] opened 2017-10-26 01:02 UTC
When we create a question with date filter of previous 6 months and try adding it to the dashboard with date filter the chart shows "There was a problem displaying this chart". 
I have mapped the filter to  ga:Date variable

**Comment by flamber** [comment] 2020-05-24 20:51
Duplicate of #4766

**Closed by flamber** 2020-05-24 20:51 UTC
Labels: Database/Google Analytics, Priority:P2, Type:Bug
