### ISSUE TITLE
Can't change column order in table when 1 or more columns hidden on questions

### ISSUE THREAD

**Issue by eanndale** [metabase/metabase#29287] opened 2023-03-16 17:46 UTC
Description
When attempting to change the order of columns in a table some columns will not allow a user to select and drag them to a new location. Note: This only happens when one or more columns are hidden (i.e. moved to the "More columns" section)

Reproduction steps
1. Go to any question with data and select "Settings"
2. Hide 1 or more of the given columns (Note: There are no issues when only hiding columns at the end of the list of columns)
3. Attempt to change the location of a column in the "Columns" section
4. Some will be able to move while other will not (have not been able to determine any kind of pattern for this)

Expected behavior
Any of the columns can be moved even with hidden columns.

Version Information
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.83.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.21"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-02-19",
      "tag": "v0.45.3",
      "branch": "release-x.45.x",
      "hash": "070f57b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
Severity
This is a minor UI bug. While it is rather annoying, I wouldn't consider it to be a major issue or risk.

EDIT, repro steps:
- create a SQL question ("select * from people"), save it, run it
- go to the viz settings, hide "created_at", 
- move "latitude" to the top"
- unhide "created_at"
- hide "latitude"
- try moving "created_at"

... you hit the issue, columns will enter a weird state where they'll move anywhere they want

I still don't know why this doesn't happen in GUI questions

**Comment by paoliniluis** [comment] 2023-03-16 18:29
I think this will be fixed in v46, but I'll leave this open till you can test it

**Comment by FredBl79** [comment] 2023-03-22 08:23
Hi,

Same impact for me, even if it is a minor, it has an impact when you have queries with many columns and you would hide some of them.
You have to unhide all in order to rearrange.

Regards
Fred

**Comment by FredBl79** [comment] 2023-03-28 14:42
> I think this will be fixed in v46, but I'll leave this open till you can test it

Just deployed 0.46, the issue remains, we can rearrange table columns.

**Comment by paoliniluis** [comment] 2023-03-28 15:18
I'm using 46 here and can't reproduce the error 
![image](https://user-images.githubusercontent.com/1711649/228285813-fe831b4e-5543-4fa7-853a-e06d68ddc871.png)
![reorder](https://user-images.githubusercontent.com/1711649/228285896-a484442b-bc5c-48fc-868e-ab701570b012.gif)

**Comment by FredBl79** [comment] 2023-03-28 15:37
I have the issue on a SQL query, not on a table view

0.46 installed


![metabase_dragdrop](https://user-images.githubusercontent.com/100215218/228291342-a3649a26-836a-47d2-8a8f-72d15659f200.gif)

**Comment by gorbunovav** [comment] 2023-03-28 17:02
Still happens for me too (with SQL queries).

**Comment by gorbunovav** [comment] 2023-04-04 21:51
@paoliniluis ping

**Comment by paoliniluis** [comment] 2023-04-05 11:59
Please post exact reproduction steps with the sample database or this will never be taken by our devs, we can’t fix something we don’t see

**Comment by gorbunovav** [comment] 2023-04-05 13:42
@paoliniluis steps in the initial bug description are very precise. The only additional detail which I can add is that for me it happens with SQL queries only. On your recording with attempt to reproduce it, you are trying to do it with just a general table view it seems.

**Closed** 2023-06-24 02:50 UTC
Labels: Type:Bug, Priority:P2, .Frontend, Visualization/Tables, .Team/PixelPolice :police_officer:

**Comment by jonniepeller** [comment] 2023-07-19 00:37
I'd argue that this isn't a minor bug, as the order of the columns matter—the eyes (for latin etc based languages) are drawn to the left first, so the most important information needs to go there.

If the re-ordering doesn't work, I'd rather not have the ability to re-oder them at all, so I can do so in my query.
