### ISSUE TITLE
Ability to cut off time period from this year, this month etc.

### ISSUE THREAD

**Issue by elenif** [metabase/metabase#15931] opened 2021-05-05 15:54 UTC
**Is your feature request related to a problem? Please describe.**
When filtering for time, e.g. this year, we would like to have the ability to not show the data from the ongoing month (see screenshot 1). 

**Describe the solution you'd like**
The ideal solution would be to be able to select between beginning of the year - last month in the filtering menu (see screenshot 2).

**How important is this feature to you?**
We would highly appreciate this feature as we use our dashboards for client communication. Naturally, it does not look good if the ongoing month shows a decline (even when not finished yet). 

**Additional context**
![1](https://user-images.githubusercontent.com/44734526/117170561-a690e200-adb9-11eb-83b8-ab44d4ce88a7.PNG)
![2](https://user-images.githubusercontent.com/44734526/117170908-efe13180-adb9-11eb-871f-e6b4420fdfc9.PNG)

**Comment by flamber** [comment] 2021-05-05 16:05
Hi @elenif 
Duplicate of #4083
Add another filter, which cut off at a specific date:
![image](https://user-images.githubusercontent.com/1447303/117172334-04c6c080-adcc-11eb-8e5e-21daf684601a.png)

**Closed by flamber** 2021-05-05 16:05 UTC
Labels: .Needs Triage, Type:New Feature

**Comment by elenif** [comment] 2021-05-05 16:28
@flamber 
Hi, thanks for the quick response. Maybe I described the problem not clear enough. We'd like to select a date like "this month","last month" that dynamically changes over the year, so that we do not have to select the respective date over and over again.

**Comment by flamber** [comment] 2021-05-05 16:31
@elenif And that's already possible, but there's currently no relative selection available for before/after/etc, which is #4083
![image](https://user-images.githubusercontent.com/1447303/117176343-14480880-add0-11eb-94c8-ff8b98ec40a7.png)

**Comment by camsaul** [comment] 2021-05-13 02:04
Duplicate of #4083
