### ISSUE TITLE
Unable to Group By multiple parts of date field in master

### ISSUE THREAD

**Issue by atharvai** [metabase/metabase#5103] opened 2017-05-13 12:40 UTC
I'm running master branch locally and testing out simple question. "Count of rows grouped by Week of Year and Year" However I am unable to select two groups based on same date field. `Created At` field here:
![image](https://cloud.githubusercontent.com/assets/14027470/25993697/c4f9cfb8-3702-11e7-822a-ba601c7ed528.png)

However in version 0.23.1 (built on 2017-03-30) it is possible. `Timestamp` field here:
![image](https://cloud.githubusercontent.com/assets/14027470/25993865/78697c38-3703-11e7-967e-12255bfdfb11.png)

I tried searching in issues and PRs here but didn't see any related changes. I noticed this with both a PostgresQL and Redshift database.

Can you give me any pointers?

**Comment by atharvai** [comment] 2017-05-18 09:29
Has anyone been able to reproduce and confirm? Or found this to be an issue?

**Comment by salsakran** [comment] 2017-05-19 23:43
repro'd.

**Comment by tlrobinson** [comment] 2017-05-20 00:13
Duplicate of #4726

**Closed by tlrobinson** 2017-05-20 00:13 UTC
Labels: Bug, Priority/P2, Query Builder
