### ISSUE TITLE
java.sql.SQLTransientConnectionException: (conn=182956) Unknown or incorrect time zone: 'Asia/Shanghai'

### ISSUE THREAD

**Issue by 1renwuruiming** [metabase/metabase#24625] opened 2022-08-05 01:42 UTC
when I execute queries,I find this information in the metabase.log，how should I do to resolve the question

**Comment by flamber** [comment] 2022-08-05 06:52
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Duplicate of #10365

**Closed by flamber** 2022-08-05 06:52 UTC
Labels: Type:Question, .Needs Triage
