### ISSUE TITLE
iframeResizer makes IE11 unresponsive, browser does not stop freezing!

### ISSUE THREAD

**Issue by w92** [metabase/metabase#11152] opened 2019-10-16 12:01 UTC
**Describe the bug**
Hello,
We noticed that the iframeResizer script that metabase uses to make the dashboard embedd iframe be displayed at its content height makes IE11 extremely slow, on an 8core i7 with 8GB memory IE stops responding, I waited for 5minutes but IE didn't stop freezing, the website became unresponsive!

As soon as we disable this iframeResizer script (remove onLoad property) the website loads almost fast (~2 seconds) and doesn't freeze in IE, but this is not someting we want to do, we need it with dynamic size.

```
 <iframe
            height="3000px" width="100%"
            src="{{ url }}"
            frameborder="0"
            allowtransparency
            onload="iFrameResize({}, this)"  <!--- We removed this line -->
 ></iframe>
```

**Logs**
[ie11log_mb_freeze.txt](https://github.com/metabase/metabase/files/3734101/ie11log_mb_freeze.txt)

**To Reproduce**
1. Crate a new question, create a simple dashboard eg table widget, share it with iframe
2. Open the page with the iframe in IE11
3. It will freeze

**Expected behavior**
No freeze

**Screenshots**
![ie11_freeze](https://user-images.githubusercontent.com/56636676/66916532-b00dfa00-f01b-11e9-9028-660eadbf1661.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

{
  "browser-info": {
    "language": "de-AT",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.4+11",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.4",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.4+11",
    "os.name": "Linux",
    "os.version": "4.15.0-65-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-10-07",
      "tag": "v0.33.4",
      "branch": "release-0.33.x",
      "hash": "9559406"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}

**Severity**
I would say a big issue, many people use IE11 nowadays.

**Additional context**

**Comment by w92** [comment] 2019-10-17 07:22
@flamber :

Thanks, yes, your comment about corporate environments is true.
Some people have other browsers e.g. FF installed by their system admins but they used IE for years so they still tend to favour using IE.

In general Metabase works in IE11 it seems, just the iframeResizer maybe needs some tuning so it doesn't make the app freeze.

Please run an tracing / profiler session with IE, this gives insight maybe? I don't know how to do myself.

Yes, please upgrade to a newer version of iframeResizer and we can run our test again wenn a new metebase release is out to see if this fixes the issue?

**Comment by w92** [comment] 2019-11-07 10:11
hello @flamber any news on this issue?

can you please update the iframeresizer so we can test again if the new version fixes it?

**Comment by flamber** [comment] 2019-11-08 01:13
@w92 There's more than 2000 issues open, so please allow some time to solve them. There's now a dedicated issue for updating the library #11166.
If you need it fixed now, then you can try [changing](https://github.com/metabase/metabase/blob/master/package.json#L29) the version line and building your own Metabase.

While we're talking about people continued use of Internet Explorer - besides the poor security and speed - many platforms are dropping support:
https://css-tricks.com/a-business-case-for-dropping-internet-explorer/

**Comment by w92** [comment] 2019-11-08 08:18
hello @flamber thanks for your reply, 

sadly i can't do the change you mentioned myself so i will wait for you guys to do it.

some clients that use the metabase instance where i had the mentioned issue use internet explorer, not everyone can simply install a new browser, some companies get set up with IE and thats it so i have to do my best to support it.

**Comment by paulrosenzweig** [comment] 2019-11-08 19:09
After some hiccups getting this set up in my windows VM, it looks like the performance problem isn't happening for me. Does it happened consistently on every ie11 user's computer?

> sadly i can't do the change you mentioned myself so i will wait for you guys to do it.

@w92, it looks like the change you indicated is outside our codebase. Do you control the page embedding Metabase? If so, you can change the reference to iFrameResizer to a newer version that what was bundled with Metabase. That would help us make sure the new version fixes the issue.

**Comment by w92** [comment] 2019-11-11 08:11
@paulrosenzweig : 

thanks for your reply.
i tried including a newer version of iframeResizer by referencing it in the embedd code but the issue was there still.

2 ideas:

1) did you install all updates in the VM for windows including optional ones? please try this, maybe it works in your old version but new one not.

2) please add multiple graphs and tables with each about 30 rows / data sets like on the screenshot above, maybe it freezes only with enough data.

**Comment by flamber** [comment] 2019-11-11 16:29
I think this might be a duplicate of #9181, since it's only a problem with a lot of questions embedded.

**Comment by rlotun** [comment] 2021-07-12 16:36
closed as part of https://github.com/metabase/metabase/pull/16952

**Closed by rlotun** 2021-07-12 16:36 UTC
Labels: Browser:IE, Embedding/Public, Embedding/Signed, Type:Performance
