### ISSUE TITLE
Unable to access H2 database while setting up metabase

### ISSUE THREAD

**Issue by veerfl** [metabase/metabase#3861] opened 2016-12-04 14:22 UTC
### Bugs

```
12-04 19:36:19 ERROR metabase.driver :: Failed to connect to database: org.h2.jdbc.JdbcSQLException: Error while creating file "/Downloads" [90062-192]
java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
	at metabase.db$verify_db_connection.invokeStatic(db.clj:336)
	at metabase.db$verify_db_connection.invoke(db.clj:331)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:357)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:349)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:112)
	at metabase.core$init_BANG_.invoke(core.clj:92)
	at metabase.core$start_normally.invokeStatic(core.clj:195)
	at metabase.core$start_normally.invoke(core.clj:189)
	at metabase.core$_main.invokeStatic(core.clj:280)
	at metabase.core$_main.doInvoke(core.clj:275)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
12-04 19:36:19 ERROR metabase.core :: Metabase Initialization FAILED:  Assert failed: Unable to connect to Metabase h2 DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
12-04 19:36:19 INFO metabase.core :: Metabase Shutting Down ...
12-04 19:36:19 INFO metabase.core :: Metabase Shutdown COMPLETE
```

-  browser and the version: Firefox 48.0
-  operating system: ubuntu
-  databases: MySQL
- Metabase version: e.x. 0.20.0
- Metabase hosting environment:  Linux/Ubuntu 12
- Metabase internal database:  MySQL

-------

**Comment by veerfl** [comment] 2016-12-04 14:50
MB_DB_FILE=/Downloads/metabase.db java -jar metabase.jar
i am using this command

**Comment by salsakran** [comment] 2016-12-05 22:24
does your user account have write permission to /Downloads/?

**Comment by salsakran** [comment] 2016-12-07 01:57
If you're able to, can you try compiling the most recent version of master?

There were some bugs in our H2 lib that were fixed and we've upgraded (#3881). They were hitting us when using the bare jar under OS X Sierra, but they might have been the root cause here.

**Comment by camsaul** [comment] 2016-12-13 03:39
@veerfl any luck?

**Comment by camsaul** [comment] 2017-11-22 17:14
This sounds like the same issue as #5249/#1871. Going to go ahead and close it as a duplicate since we fixed it back in #5396 (0.25.0)

@veerfl please let us know if you're still seeing this issue on a newer version of Metabase.

**Closed by camsaul** 2017-11-22 17:14 UTC
Labels: Need More Info, Running Metabase/H2

**Comment by veerfl** [comment] 2017-11-22 17:26
Hi Cam Saul,

The issue is solved, upgrading to newer version helped.

**Comment by camsaul** [comment] 2017-11-22 17:29
Great! Glad to hear it @veerfl
