### ISSUE TITLE
Upgrade to 0.23 fails with "DB is not setup..."

### ISSUE THREAD

**Issue by calmyournerves** [metabase/metabase#4611] opened 2017-03-24 15:49 UTC
Hey there!

I just tried to update our Metabase installation (on Docker) to 0.23. When starting it, it throws a `java.lang.Exception: DB is not setup. Make sure to bind call set-default-db-connection! or bind *db-connection*.` and exits afterwards. Setting it back to 0.22.2 makes it work again.

Here's the startup log output:

```03-24 15:41:40 INFO metabase.util :: Loading Metabase...
03-24 15:41:41 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓
03-24 15:41:50 INFO metabase.core :: Starting Metabase in STANDALONE mode
03-24 15:41:50 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000, :host "metabase-18-vjgjb"}

03-24 15:41:50 INFO metabase.core :: Starting Metabase version v0.23.0 (2f5faf1 release-0.23.0) ...
03-24 15:41:50 INFO metabase.core :: System timezone is 'GMT' ...
03-24 15:41:51 DEBUG metabase.driver :: Registered driver :bigquery 🚚
03-24 15:41:51 DEBUG metabase.driver :: Registered driver :crate 🚚
03-24 15:41:51 DEBUG metabase.driver :: Registered driver :druid 🚚
03-24 15:41:51 DEBUG metabase.driver :: Registered driver :googleanalytics 🚚
03-24 15:41:51 DEBUG metabase.driver :: Registered driver :h2 🚚
03-24 15:41:51 DEBUG metabase.driver :: Registered driver :mongo 🚚
03-24 15:41:51 DEBUG metabase.driver :: Registered driver :mysql 🚚
03-24 15:41:51 DEBUG metabase.driver :: Registered driver :postgres 🚚
03-24 15:41:51 DEBUG metabase.driver :: Registered driver :redshift 🚚
03-24 15:41:51 DEBUG metabase.driver :: Registered driver :sqlite 🚚
03-24 15:41:51 DEBUG metabase.driver :: Registered driver :sqlserver 🚚
03-24 15:41:51 INFO metabase.db :: Verifying postgres Database Connection ...
03-24 15:41:51 INFO metabase.db :: Verify Database Connection ...  ✅
03-24 15:41:51 INFO metabase.db :: Running Database Migrations...
03-24 15:41:51 INFO metabase.db :: Setting up Liquibase...
03-24 15:41:51 INFO metabase.db :: Liquibase is ready.
03-24 15:41:51 INFO metabase.db :: Checking if Database has unrun migrations...
03-24 15:41:56 WARN server.HttpChannel :: /
java.lang.Exception: DB is not setup. Make sure to bind call set-default-db-connection! or bind *db-connection*.
	at toucan.db$connection.invokeStatic(db.clj:91)
	at toucan.db$connection.invoke(db.clj:84)
	at toucan.db$query.invokeStatic(db.clj:237)
	at toucan.db$query.doInvoke(db.clj:233)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at toucan.db$simple_select.invokeStatic(db.clj:301)
	at toucan.db$simple_select.invoke(db.clj:290)
	at toucan.db$select.invokeStatic(db.clj:538)
	at toucan.db$select.doInvoke(db.clj:532)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at toucan.db$select_field__GT_field.invokeStatic(db.clj:568)
	at toucan.db$select_field__GT_field.doInvoke(db.clj:561)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at metabase.models.setting$restore_cache_if_needed_BANG_.invokeStatic(setting.clj:89)
	at metabase.models.setting$restore_cache_if_needed_BANG_.invoke(setting.clj:87)
	at metabase.models.setting$db_value.invokeStatic(setting.clj:117)
	at metabase.models.setting$db_value.invoke(setting.clj:114)
	at metabase.models.setting$get_string.invokeStatic(setting.clj:131)
	at metabase.models.setting$get_string.invoke(setting.clj:121)
	at clojure.core$partial$fn__4759.invoke(core.clj:2514)
	at metabase.models.setting$get.invokeStatic(setting.clj:168)
	at metabase.models.setting$get.invoke(setting.clj:164)
	at metabase.models.setting$setting_fn$fn__15391.invoke(setting.clj:282)
	at metabase.middleware$maybe_set_site_url$fn__34609.invoke(middleware.clj:264)
	at ring.middleware.cookies$wrap_cookies$fn__35456.invoke(cookies.clj:161)
	at ring.middleware.session$wrap_session$fn__35705.invoke(session.clj:103)
	at ring.middleware.gzip$wrap_gzip$fn__35485.invoke(gzip.clj:65)
	at ring.adapter.jetty$proxy_handler$fn__35329.invoke(jetty.clj:24)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

Would be cool if you could look into it. Thank you!

**Comment by mazameli** [comment] 2017-03-24 16:58
I think you're experiencing [this same issue](https://github.com/metabase/metabase/issues/4570).

As Sameer [mentioned elsewhere](http://discourse.metabase.com/t/how-do-i-update-metabase-running-on-elastic-beanstalk/53/16?u=maz): that's unfortunately what we currently display when you run a health check before the instance is fully set up. If you wait a minute or two, the upgrade should go through.

Marking as dupe of #4570.

**Closed by mazameli** 2017-03-24 16:58 UTC

**Comment by tclift** [comment] 2017-03-25 14:38
The "DB is not setup" message might be a red herring. Just had an issue starting up 0.23.0 here, previously working on 0.22.2. Downgraded, came straight up. Also using Docker image, on Kubernetes. Perhaps relevant logs:

```
03-26 01:14:04 INFO metabase.util :: Loading Metabase...
***snip***
03-26 01:14:17 INFO metabase.core :: Starting Metabase version v0.23.0 (2f5faf1 release-0.23.0) ...
***snip***
03-26 01:14:44 WARN server.HttpChannel :: /api/health
java.lang.Exception: DB is not setup. Make sure to bind call set-default-db-connection! or bind *db-connection*.
***snip***
03-26 01:14:54 INFO metabase.db :: Database Migrations Current ...  ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
03-26 01:14:54 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
03-26 01:14:56 INFO db.migrations :: Running data migration 'migrate-query-executions'...
Metabase is not initialized yet!
Metabase is not initialized!
Metabase is not initialized yet!
Metabase is not initialized yet!
Metabase is not initialized yet!
***snip***
```

The "not initialized" lines repeat in both forms. I waited about 20 minutes before restarting 0.23.0 again, same result. Restarted with 0.22.2, came straight up:

```
03-26 01:22:40 INFO metabase.util :: Loading Metabase...
***snip***
03-26 01:22:52 INFO metabase.core :: Starting Metabase version v0.22.2 (e318fee release-0.22.2) ...
***snip***
03-26 01:23:23 INFO metabase.db :: Database Migrations Current ...  ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
03-26 01:23:25 INFO db.migrations :: Finished running data migrations.
03-26 01:23:25 INFO metabase.events :: Starting events listener: metabase.events.activity-feed 👂
***success from here on***
```

**Comment by salsakran** [comment] 2017-03-27 00:52
@tclift we migrated the query_queryexecutions table in this release. If you have a ton of entries and a very slow application DB (on the I/O side), it could take a while to finish that.

Can you poke around and see how large that table is?

**Comment by calmyournerves** [comment] 2017-03-27 06:50
Raising the health check wait time indeed solved the issue for me, thanks @mazameli!

**Comment by tclift** [comment] 2017-03-29 03:24
@salsakran `query_queryexecution` is ~10k rows, ~5.5 MiB. Not so big, I guess? While waiting for startup, the system wasn't memory constrained, and CPU usage was low. There were a few open DB connections, but I didn't look into what they were doing.

`DATABASECHANGELOG` indicates migration 051 has executed.

**Comment by tclift** [comment] 2017-04-17 08:14
Tried again, upgrade succeeded after 32 minutes.
