### ISSUE TITLE
Sync problems after upgrading to 0.32.5

### ISSUE THREAD

**Issue by marthursson** [metabase/metabase#9903] opened 2019-05-07 10:36 UTC
Recently upgraded to 0.32.5, and it appears that the DB migration did not go exactly as it should.

After migration I could not get sync to work properly. E.g. in one particular table with lots of columns, only a small subset would show up under data model. Any number of explicit sync requests would not make any difference.

Looking more closely in the internal metabase database, I noticed that the missing columns appeared to have a weird state in the metabase_field table: all the missing columns had active = 'true' and visibility_type='retired'.

Explicitly changing visibility_type to 'normal' for these fields fixed the problem (for this particular table).

I'm just guessing here, but maybe something is missing in a DB migration executed on upgrade to 0.32.5?

**Comment by flamber** [comment] 2019-05-07 16:14
Hi @marthursson 
Which version did you upgrade from? Do you still have old metadata database, so you could reproduce the migration or do you have logs from the migration showing the changes? If not, then it's going to be extremely difficult to reproduce.

**Comment by sbelak** [comment] 2019-09-17 11:32
If you look in the logs are there any errors during sync?

**Comment by flamber** [comment] 2020-05-28 12:36
Closing, since without logs or the old metabase, it's very hard to figure out what went wrong.

**Closed by flamber** 2020-05-28 12:36 UTC
Labels: Administration/Metadata & Sync, Priority:P3, Type:Bug
