### ISSUE TITLE
Dimension not counted in a pivot table

### ISSUE THREAD

**Issue by Philippe-M** [metabase/metabase#21311] opened 2022-03-29 07:29 UTC
Hello,

**Describe the bug**
In a pivot table when a dimension has no total then it is not visible if the detail is collapsed.

For example : 
![image](https://user-images.githubusercontent.com/4558101/160548790-afd36ed1-84ea-4047-b90e-4d0d35b1c193.png)

![image](https://user-images.githubusercontent.com/4558101/160548862-5ecc499e-dfd8-4370-9fd8-fcd7ae69bb61.png)

Where is dimension C02? And 40 + 52 != 96

```
{
  "browser-info": {
    "language": "fr",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1-LTS",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1-LTS",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.25.1.el7.x86_64",
    "user.language": "fr",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.5.10-MariaDB-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.5"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-03-23",
      "tag": "v0.42.3",
      "branch": "release-x.42.x",
      "hash": "33fb268"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
}
```

**Comment by flamber** [comment] 2022-03-29 07:46
Without any information on how to reproduce, then it's impossible to figure out what is happening, but I'm guessing it is a duplicate of #19373.

**Closed by flamber** 2022-03-29 07:46 UTC
Labels: Type:Bug, .Needs Triage
