### ISSUE TITLE
Funny dashboard permission UX with public links

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4576] opened 2017-03-21 22:59 UTC
With the new public links feature, if an admin sets a dashboard to be sharable, but it contains a card(s) for which a user doesn't have access, if that user views the public link to that dashboard in the same browser/session, they won't be able to see that card. However, if they view the link in a different browser, or clear their MB session, they can see the card. 

We discussed this, and it seems the core problem is that we don't currently have dashboard-level permissions; if we did, we could make it so that any user with permission to view a dashboard would just be able to see the cards it contains. Without implementing dashboard-level permissions, a temporary fix could be that a non-admin user should only be able to view a dashboard's sharing icon if she has at least view access for _all_ of that dashboard's cards.

**User viewing the dashboard within their MB instance**
 
![screen shot 2017-03-21 at 3 51 52 pm](https://cloud.githubusercontent.com/assets/2223916/24174631/e3fb7ca4-0e4e-11e7-8edd-e4f9543c9b5b.png)

**Viewing the public link in the same browser. Notice the error message is different:**

![screen shot 2017-03-21 at 3 51 45 pm](https://cloud.githubusercontent.com/assets/2223916/24174636/ed52c672-0e4e-11e7-9719-c2573237a00d.png)

**Viewing the public link in a different browser**

![screen shot 2017-03-21 at 3 52 00 pm](https://cloud.githubusercontent.com/assets/2223916/24174652/fffb5ac8-0e4e-11e7-9fa0-2ae99b66a040.png)

**Comment by flamber** [comment] 2020-05-26 13:27
I cannot reproduce on 0.35.3 - think this was fixed in 0.30 with Collection permissions.

**Closed by flamber** 2020-05-26 13:27 UTC
Labels: Administration/Permissions, Type:UX
