### ISSUE TITLE
CSV/JSON Download icon does not appear on the question page after upgrade to 0.24.1

### ISSUE THREAD

**Issue by feronera** [metabase/metabase#5215] opened 2017-05-29 04:25 UTC
### Bugs
CSV/JSON Download icon does not appear after upgrade to 0.24.1

- Browser and the version: Chrome 8.0.3029.110 & Safari
- OS: OS X 10
- Databases: MariaDB
- Metabase version: 0.24.1
- Metabase hosting environment: Elastic Beanstalk with Docker
- Metabase internal database: MariaDB

STEP:
1. Go to each old question page.
2. Waiting for the first run answer.
3. After answer appear. Icon download arrow did not appear.
4. Next, try to copy SQL query and create the new question. Download icon appears as normally.But after save question. Download Icon immediately disappeared.

**Comment by rafaelveloso** [comment] 2017-05-29 12:00
For me, this only happens for questions with one or more parameters where there's not a default value defined. If any parameter is empty, the download button isn't showing.

**Comment by leomelzer** [comment] 2017-05-30 05:45
We face the same issue, but this has been fixed in master and will be in 0.24.2 - see https://github.com/metabase/metabase/issues/5047

**Comment by mazameli** [comment] 2017-05-30 20:41
Yep, as leomelzer pointed out, this issue is a duplicate of https://github.com/metabase/metabase/issues/5047, and was fixed by https://github.com/metabase/metabase/pull/5099.

**Closed by mazameli** 2017-05-30 20:41 UTC
