### ISSUE TITLE
Unclear error message when attempting to edit user email to an email that already exists in Metabase

### ISSUE THREAD

**Issue by alexyarosh** [metabase/metabase#46938] opened 2024-08-16 16:39 UTC
### Describe the bug

If you try to edit a user and put an email that belongs to someone who is already a user in Metabase, the error message that Metabase gives you is very unclear (`n.user is undefined`):
![image](https://github.com/user-attachments/assets/2912e2cf-7111-4a29-bf68-08841582c94e)
I imagine in orgs with hundreds of users, it'll be difficult to figure out what the actual error is.

### To Reproduce

1. Add at least two users by email 
2. Edit one of the users to have the same email as an already existing user
3. Click update

### Expected behavior

A clear error message, like the one you get when _adding_ (instead of updating) a user with an already existing email:
![image](https://github.com/user-attachments/assets/c0b84416-589b-400b-8d31-d219d24cf703)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "6.6.12-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.1 (Debian 16.1-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2024-08-13",
      "tag": "v1.50.20",
      "hash": "df82d58"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P3

### Additional context

https://github.com/user-attachments/assets/19e55718-f54c-4e59-8b2a-426829583c14

**Comment by kamilmielnik** [comment] 2024-08-19 07:40
Duplicate of #46449, closing.

**Closed by kamilmielnik** 2024-08-19 07:40 UTC
Labels: Type:Bug, Priority:P2, .Frontend, Administration/People, .Team/AdminWebapp
