### ISSUE TITLE
Edit table values with Metabase

### ISSUE THREAD

**Issue by collector-ynh** [metabase/metabase#22309] opened 2022-05-01 11:44 UTC
I can't seem to change the values on the databases with Metabase, because the application only allows me to view and search the values but not to modify them.

Is it possible to modify directly from tables with Metabase? 
(As will DBeaver, phpMyAdmin...)

**Comment by flamber** [comment] 2022-05-01 11:57
Duplicate of #2882

**Closed by flamber** 2022-05-01 11:57 UTC
Labels: Type:Question, .Needs Triage
