### ISSUE TITLE
Mathmatical Conditional Formatting

### ISSUE THREAD

**Issue by OdinTallBeard** [metabase/metabase#37476] opened 2024-01-09 20:32 UTC
Allow you to compare fields based on mathematical components (if column A is greater than Column B, highlight column A red...)

Can be used for better, more accurate data visualization.

**Comment by paoliniluis** [comment] 2024-01-10 00:01
duplicate of https://github.com/metabase/metabase/issues/37249

**Closed by paoliniluis** 2024-01-10 00:01 UTC
Labels: Type:New Feature, .Needs Triage
