### ISSUE TITLE
BigQuery INT64 values are not displayed correctly

### ISSUE THREAD

**Issue by urish** [metabase/metabase#29467] opened 2023-03-23 07:19 UTC
**Describe the bug**
When displaying query results (e.g. in a table, or as numbers), int64 values are sometimes incorrectly displayed. This seems to be due to loss of precision - I imagine these values are internally represented as float64, which starts to lose precision when the numbers are larger than (2⁵³ – 1).

**Logs**
Looking at the browser's network tab, the values seem to be correct. So it is probably a client side problem. Here's what I see when I send the query `SELECT CAST("356206305582642177" as INT64) as value`:

```json
{"data":{"rows":[
[356206305582642177]
],
"cols":[{"display_name":"value","source":"native","field_ref":["field","value",{"base-type":"type/Integer"}],"name":"value","base_type":"type/Integer","effective_type":"type/Integer"}],"native_form":{"query":"SELECT CAST(\"356206305582642177\" as INT64) as value","params":null},"results_timezone":"GMT","results_metadata":{"columns":[{"display_name":"value","field_ref":["field","value",{"base-type":"type/Integer"}],"name":"value","base_type":"type/Integer","effective_type":"type/Integer","semantic_type":null,"fingerprint":{"global":{"distinct-count":1,"nil%":0.0},"type":{"type/Number":{"min":3.5620630558264218E17,"q1":3.5620630558264218E17,"q3":3.5620630558264218E17,"max":3.5620630558264218E17,"sd":null,"avg":3.5620630558264218E17}}}}]},"insights":null},
"database_id":3,"started_at":"2023-03-23T07:17:34.017052Z","json_query":{"database":3,"native":{"query":"SELECT CAST(\"356206305582642177\" as INT64) as value","template-tags":{}},"type":"native","middleware":{"js-int-to-string?":true,"add-default-userland-constraints?":true}},"average_execution_time":null,"status":"completed","context":"ad-hoc","row_count":1,"running_time":545}
```

**To Reproduce**
1. Create a new SQL question and run the following query: `SELECT CAST("356206305582642177" as INT64) as value`
2. Observed that the displayed value is 356206305582642200

**Expected behavior**
The value 356206305582642177 should be displayed instead

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/892318/227130202-2da06688-a7cd-46ef-a728-d3eab283752a.png)

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 111.0.5563.65 (64 bit)
- Your operating system: Windows 11.1413
- Your databases: BigQuery
- Metabase version: 0.45.3
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.12.2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-02-19",
      "tag": "v0.45.3",
      "branch": "release-x.45.x",
      "hash": "070f57b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
It's definitely annoying as we have some int64 fields, and we can't easily see their values and sometimes also can't filter them correctly, but not a blocker. We just have to be aware that sometimes that values we are seeing are incorrect and look at the network tab to find the correct value.

**Comment by abhishek-superk** [comment] 2023-03-28 11:59
Tried this, just for reference: this isn't an issue with just `INT64`, but also breaks for `FLOAT64`. 

On BigQuery UI, `INT64` gives the input value as expected, and `FLOAT64` gives `3.5620630558264218e+17`

**Comment by paoliniluis** [comment] 2023-04-16 00:01
Thanks for the report, I have a feeling this is a duplicate of https://github.com/metabase/metabase/issues/5816

**Closed by paoliniluis** 2023-04-16 00:01 UTC
Labels: Type:Bug, .Needs Triage
