### ISSUE TITLE
Choosing a binning option for a date breakout on a joined column should work without additional clicks

### ISSUE THREAD

**Issue by jeff303** [metabase/metabase#15446] opened 2021-04-01 18:43 UTC
**Describe the bug**
In the question editor, when choosing a date breakdown on a joined column, the joined column isn't selected when choosing the binning option, which creates a poor user experience.

**Logs**
N/A

**To Reproduce**
1. Edit a question for the sample Orders table
2. Add a join to the sample People table
3. Add an aggregation
4. For the aggregation breakout, expand People - User (i.e. the joined table), and scroll down to its Created At column (i.e. the date the user who placed that order was created)
5. Click "by" to select a binning option (ex: hour of day), then click that option
6. The query editor is shown with a column that isn't valid, unless you first click Created At, then navigate back into the breakout selection, then click the "by" option

**Expected behavior**

**Screenshots**

About to select the breakout (before step 3 above):
<img width="1157" alt="breakout_selection_joined_column_1" src="https://user-images.githubusercontent.com/3521562/113339142-a94a7400-92ef-11eb-8b11-cfd7aa919c65.png">

Selecting the binning option for the Users/Created At column (step 4):
<img width="1211" alt="breakout_selection_joined_column_2" src="https://user-images.githubusercontent.com/3521562/113339218-c97a3300-92ef-11eb-8259-f19647de67a9.png">

After selecting "Hour of Day" (notice that the column shown here is not valid; it does not include `People - User ->` and the query can't be previewed):
<img width="1172" alt="breakout_selection_joined_column_3" src="https://user-images.githubusercontent.com/3521562/113339293-e3b41100-92ef-11eb-891f-de99c0e6f5c9.png">

Going back into the breakout selection again to rectify the problem:
<img width="1133" alt="breakout_selection_joined_column_4" src="https://user-images.githubusercontent.com/3521562/113339416-09411a80-92f0-11eb-811f-a0c9c86c2e2a.png">

Choosing "Hour of day" again:
<img width="1227" alt="breakout_selection_joined_column_5" src="https://user-images.githubusercontent.com/3521562/113339431-0f36fb80-92f0-11eb-81e9-ba2f6a71f137.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 89
- Your operating system: OS X 11
- Your databases: SQL Server
- Metabase version: 0.39
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Minor

**Additional context**
N/A

**Comment by flamber** [comment] 2021-04-01 20:43
This is more problematic than just minor. The binning selector is showing the list of options two times, once for the original table and once for the joined table. And depending on which you options (the upper or lower) you select, it will reference the original table or the joined table.

master - I had to zoom out to clearly show it, since #15445 causes the option popout to become very tiny
![image](https://user-images.githubusercontent.com/1447303/113351607-66ae8900-933b-11eb-80fd-ee45722fb904.png)

0.38.2 for reference
![image](https://user-images.githubusercontent.com/1447303/113350855-5649de80-933a-11eb-9d1d-62e7adfcb34a.png)

**Comment by jeff303** [comment] 2021-04-05 18:15
@nemanjaglumac confirmed on the planning call that binning options are being rendered twice, once for the base table, and once for the joined table.  So the "real issue" is the duplicate options.  Presumably, if only the correct binning options are rendered for the joined table, then this problem would go away?

**Comment by nemanjaglumac** [comment] 2021-04-05 18:49
According to the repro I was making, it should. Yes.
![image](https://user-images.githubusercontent.com/31325167/113612594-56a2ec00-9650-11eb-90ca-8259be45c7c4.png)

Basically, that's what @flamber said here:
> depending on which you options (the upper or lower) you select, it will reference the original table or the joined table.

**Comment by ariya** [comment] 2021-04-05 20:26
By bisecting the git history, I discovered that this was a regression introduced for the first time in commit 6bdd5e09, associated with PR #14897 (MBQL Refactor: Combine various Field clauses into one new clause).

I'll continue to dig further, but if anyone (@camsaul? @paulrosenzweig?) more familiar with the said Field refactoring has some ideas or spot something obvious, I'll be all ears!

**Comment by ariya** [comment] 2021-04-06 02:13
Here is the comparison of what the DimensionList component receives and subsequently renders.

**Before** commit 6bdd5e0 (note the `_parent` pointing to some object of `JoinedDimension` type):

![image](https://user-images.githubusercontent.com/7288/113649011-81864380-9642-11eb-8f65-4b09a55edb01.png)


**After** commit 6bdd5e0 (`_parent` is now `null`):

![image](https://user-images.githubusercontent.com/7288/113649039-982c9a80-9642-11eb-8596-dfdf48febf71.png)

**Comment by flamber** [comment] 2021-04-12 17:25
Closing as fixed by #15530 - but it's not completely fix - see #15574

**Closed by flamber** 2021-04-12 17:25 UTC
Labels: .Regression, .Reproduced, Priority:P2, Querying/GUI, Type:Bug
