### ISSUE TITLE
Feature Request: Variable filters from nested queries accessible in Query Builder

### ISSUE THREAD

**Issue by chucksense** [metabase/metabase#10220] opened 2019-06-19 15:05 UTC
**Is your feature request related to a problem? Please describe.**
I have a SQL Question that includes variables configured as Field Filter.

In using that Question in a Nested Query, I would like to be able to utilize the filters in the new Question using Query Builder.

**Describe the solution you'd like**
Ideally, those would simply appear as filterable items in the Filter drop down.

**How important is this feature to you?**
Note: this would be very useful for me as I create a lot of Questions using custom SQL then reference them in query builder in order to centralize a set of logic, then build a suite of other questions off of that logic.  But this is due to the fact that I don't have access to modify the schema directly.  Anybody that can modify their own schema to create summary/aggregation tables or views probably doesn't need this.

Also note, this is slightly different than #6449 as I'm not talking about Dashboard filters, but filters in Query Builder instead.

**Comment by flamber** [comment] 2019-06-19 19:09
Hi @chucksense 
I think it relates to the same core issue. The filters are not available from the original question, when using Saved Question - no matter if used in QB or dashboard.
Would you say that this might be a duplicate of #7089?

**Comment by chucksense** [comment] 2019-06-20 18:47
Yes, that appears to be the same issue! Thanks!

**Closed** 2019-06-20 18:47 UTC
Labels: New Feature
