### ISSUE TITLE
Determine column type for mongoDB ($date)

### ISSUE THREAD

**Issue by ujjwal-gupta** [metabase/metabase#5162] opened 2017-05-22 06:25 UTC
I have 3 datetime fields in MongoDB with values set as either $date BSON Mongo type or null. Metabase does great at determining the type of 2 but not the third. This leads to obvious problem for the third (filtering, grouping, how it looks in a table). The only difference between this column Vs. the other two I can think of it that this one probably has more records set as null than the others. 

What is type determination based on? Random sampling? Majority values? Why is this field not being recognised as a date?

I'd also be okay with being able to specify date type in the data Model on admin view to resolve this.

![selection_001](https://cloud.githubusercontent.com/assets/4945922/26295037/78bf660e-3ee5-11e7-8041-89c6a4e8fa33.png)

Sample raw mongo entries:
{
    "expired_datetime": ISODate("2017-03-01T13:28:33.651Z"),
    "cancelled_datetime": ISODate("2017-03-01T13:28:33.449Z"),
    "demand_created_datetime": ISODate("2017-03-01T09:57:19.294Z")
},
{
    "expired_datetime": ISODate("2017-03-01T02:36:56.713Z"),
    "cancelled_datetime": null,
    "demand_created_datetime": ISODate("2017-03-01T02:36:56.713Z")
}

Observed on:

Chrome Version 58.0.3029.81 (64-bit)
Ubuntu 16.04
MongoDB
Metabase version: 0.24.1
Hosted on Elastic Beanstalk 
Metabase internal database: MySQL

**Comment by salsakran** [comment] 2017-06-03 03:33
What is it marked as in the admin panel? 

For databases with direct schema information we pull out the underlying type of the field and use that as the "base_type". 

We also take a sample of the first 10k values and use them to infer special types, valid values, etc. It's fairly imperfect but has been working reasonably so far. We're looking into smarter ways of sampling as well, but that has been the simplest performant way we found initially.

**Comment by ujjwal-gupta** [comment] 2017-06-05 03:35
Neither of the three shows up as anything in the admin panel (data model). They just show the default "Select a special type" message. Date is not even present as a special type, in the options.

Using 10K samples seems reasonable but IMO random 10K would be better that first. Specifically, in Mongo, a "distinct" query could also be useful though neither of them is a performant way.

That being said, it's clear that datetime is already a special data type in metabase and is recognised as such most of the time. If that type is added as a selectable type in the admin panel, I could mark this field as such and solve my problem.

**Comment by ujjwal-gupta** [comment] 2017-07-24 10:45
It seems like the "datetime" type can also be set in MySQL by specifying a column as UNIX timestamp (seconds/milliseconds). A similar "$date" BSON type for Mongo seems like the right choice with respect to design consistency.

**Comment by v-six** [comment] 2018-09-18 13:14
Any update about this issue? I'm running metabase v0.30.3 and I've exactly the same problem.
- mongoDB field is typed as "ISODate"
- metabase recognize this field as a "type/DateTime" in the original schema of my collection
- metabase type dropdown does not show any "Date" or "Timestamp" type for this field

When trying to create a new question based on this field I have this error =>
```
Command failed with error 16006: 'can't convert from BSON type object to Date' on server xx.xx.xx.xx:xxxx. The full response is { "ok" : 0.0, "errmsg" : "can't convert from BSON type object to Date", "code" : 16006, "codeName" : "Location16006" }
```

This problem does not appear with Timestamps, cause the dropdown in metadata shows the type "UNIX Timestamp" in that case.

So a workaround for now could be an ISODate to Timestamp conversion in the MongoDB database.

**Comment by camsaul** [comment] 2020-05-13 01:44
Related: #2947

**Comment by camsaul** [comment] 2022-12-14 21:06
So it sounds like there are a few different issues being discussed here:
- Metabase is not detecting date columns correctly. This sounds like the problem @ujjwal-gupta is having.
   - This is basically the same issue as #4946, if we're not detecting the column correctly during sync. #27045, which is currently in progress, will hopefully help alleviate this problem a bit.
- Metabase is not detecting `object` columns as dates. This sounds like the issue @thedavidprice is running in to.
   - I'm not really sure how we are supposed to be able to guess this programmatically. Addressing #10484 would at least give people an escape hatch to fix these sorts of things themselves. @thedavidprice, we don't currently let people set the actual database type of a column in the data model page -- just "semantic type" about what the _meaning_ of the column is. I think removing that restriction would probably be part of the work in #10484
- Metabase is detecting the date columns directly, but we're doing the wrong thing with them. This sounds like the problem @v-six ran in to.
   - Maybe we just need to do some sort of `cast()` or something here to fix the `can't convert from BSON type object to Date`. 

Since the first two problems are covered by other existing issue, let's focus this issue on just the 

```
can't convert from BSON type object to Date
```

problem going forward. Once that's fixed, let's close this out and track the other two in the aforementioned open issues.

**Comment by metamben** [comment] 2023-01-13 22:24
@v-six Can you reproduce the problem with a recent version of Metabase? If yes, could you provide the data you use? I'm asking, because fields of type `ISODate` seem to get the base type `type/Instant` and not as `type/DateTime`.

**Comment by metamben** [comment] 2023-01-20 19:14
The MongoDB version of our test data (e.g., `sample-dataset`, `test-data`) uses `ISODate` fields to represent dates. In the application DB these have `:database_type "java.time.Instant"`, `:effective_type :type/Instant`, and `:base_type :type/Instant`. The tests pass, the UI works as expected,  so I close this ticket. A new ticket should be opened if problems surface.

**Closed by metamben** 2023-01-20 19:14 UTC
Labels: Type:Bug, Database/Mongo, Administration/Metadata & Sync
