### ISSUE TITLE
Example from the official documentation on SQL parameters not working

### ISSUE THREAD

**Issue by vins31** [metabase/metabase#5638] opened 2017-07-30 14:27 UTC
### Environment
- Browser: Chrome 59.0.3071.115 
- OS X 10.11.6
- Database: Sample dataset
- Metabase version: 0.25.1
- Metabase hosting environment: Docker
- Metabase internal database: default

### Repeatable steps to reproduce the issue

I followed the sample about sql parameters from the documentation [http://www.metabase.com/docs/v0.25.1/users-guide/13-sql-parameters.html
](http://www.metabase.com/docs/v0.25.1/users-guide/13-sql-parameters.html)

#### Request 1

```
select count(*) from PRODUCTS
[[where category = {{cat}}]]
```
But this requests returns the following error

> Data conversion error converting "Gizmo"

[Log](https://pastebin.com/E1TsFrrF)

----

#### Request 2

According to #4545 we should now cast the variables for security purpose (which is not mentioned in the documentation)

This requests returns 0 (no error) which is an incorrect answer:
```
select count(*) from PRODUCTS
[[where category = cast ({{cat}} as text)]]
```
[Log](https://pastebin.com/9hDVGeg0)
Note: with Metabase 0.24.2 the previous request returned an error.

----

#### Request 3

This request returns me 43:
```
select count(*) from PRODUCTS
where category = 'Gadget'
```

Using Text variable instead of a Field Filter variable works.

I do not know whether the problems comes from the documentation or the code.

**Comment by salsakran** [comment] 2017-08-07 22:05
Ugh. Repro'd. 

Thank you for pointing this out!

**Comment by attekei** [comment] 2017-08-30 18:41
The second screenshot http://www.metabase.com/docs/v0.25.1/users-guide/13-sql-parameters.html is just plain wrong because it suggests that you could use field filter inside that kind of query. 

To clarify, this query works as intended with a field filter:
```
select count(*) from PRODUCTS where {{cat}}
```

but this doesn't: 
```
select count(*) from PRODUCTS
[[where category = {{cat}}]]
```

When I started using Metabase last autumn it took me some time to figure out that you can never use Field Filter template tag in the same ways as Text, Number or Date template tags. So in addition to fixing the screenshot in documentation I'd suggest either
- Being really explicit in the documentation about how field filters are different compared to all other template tags
- Adding a description text in frontend about the usage of field filters after you have selected that the Field Filter template tag type
- Returning a more helpful error message than `Data conversion error converting X` from the backend that would help the user in the right direction

**Comment by vins31** [comment] 2017-08-31 16:52
You are right, thank you a lot @attekei!

**Comment by mazameli** [comment] 2017-09-20 19:41
FYI, I had already slightly updated the docs about field filters, which will be reflected once we push version 0.26: https://github.com/metabase/metabase/blob/release-0.26.0/docs/users-guide/13-sql-parameters.md

Also just merged https://github.com/metabase/metabase/pull/6018 to update the screenshot as @attekei mentioned.

**Comment by salsakran** [comment] 2017-09-25 23:02
closing this as @atte is correct that this is highlights a difference in field filters.

**Closed by salsakran** 2017-09-25 23:02 UTC
Labels: Bug, Parameters/Variables, Priority/P1
