### ISSUE TITLE
stacked area charts plots 0 for missing values

### ISSUE THREAD

**Issue by CzechJiri** [metabase/metabase#2771] opened 2016-06-15 22:06 UTC
This is not an error per say, but more an formatting question/discussion

lets assume I have chart (sample below) and one of the categories is missing, then suddenly shows up (see green), it shows zero value for the whole history, I would assume this category would be missing and would show from the time it actually exists.

![image](https://cloud.githubusercontent.com/assets/6222611/16098918/481503d4-330a-11e6-9c41-cf8a166c7424.png)

**Comment by tlrobinson** [comment] 2016-06-15 22:07
Duplicate of #896?

**Comment by agilliland** [comment] 2016-06-15 22:08
This looks more like nulls being treated as 0's?

**Comment by tlrobinson** [comment] 2016-06-15 22:08
Err yeah, actually "related to", not "duplicate of"

**Closed** 2016-09-15 22:14 UTC
Labels: Visualization
