### ISSUE TITLE
BigQuery: Joins in the query builder generate invalid table aliases

### ISSUE THREAD

**Issue by JGrubb** [metabase/metabase#14982] opened 2021-02-26 15:23 UTC
**Describe the bug**

Since 0.38.0 explicitly joining tables via the query builder results in the generated table alias using the human readable name of the table, eg "Accounts: Users".  BigQuery errors with `Invalid field name "Accounts: Users - Owner__user_id". Fields must contain only letters, numbers, and underscores, start with a letter or underscore, and be at most 128 characters long.`

```
... -- generated SQL
LEFT JOIN `staging.accounts_users` `Accounts: Users - Owner` ON `staging.accounts_projects`.`owner_id` = `Accounts: Users - Owner`.`user_id`
...
```

This only affects queries that explicitly join tables in the UI.  If tables are filtered on columns in related tables (via the FK connections in the data model) the generated table name is valid - 

```
...
LEFT JOIN `staging.accounts_users` `accounts_users__via__owner_id` ON `staging.accounts_projects`.`owner_id` = `accounts_users__via__owner_id`.`user_id`
...
```

**Logs**
N/A

**To Reproduce**
1. Go to any dataset backed by BigQuery, pick any table with a related table.
2. Click on the visual query editor
3. Join a table into the query and "visualize".  The query will appear to hang because of [#14918](https://github.com/metabase/metabase/issues/14918)
4. See error in BQ console

**Expected behavior**
Expected behavior is for Metabase to generate a valid table alias for the joined table.  If I go into the Data Model section and change the name of the table to a valid bigQuery alias the query will work.

**Information about your Metabase Installation:**

- Your browser and the version: N/A because not a UI bug.
- Your operating system: N/A because not a UI bug.
- Your databases: BigQuery
- Metabase version: 0.38.0
- Metabase hosting environment: Self hosted on [Platform.sh](https://platform.sh/)
- Metabase internal database: Postgres 9.6

**Severity**
Well, it seems pretty severe to be honest.  From what I can tell, no queries built with the query builder involving joins will succeed unless the table has a valid name in the Data Model section, ie no spaces or special chars other than `_`.  I'm really mystified that I don't see this bug opened in the ticket queue yet.

**Additional context**

**Comment by flamber** [comment] 2021-02-26 15:37
Duplicate of #14933

**Closed by flamber** 2021-02-26 15:37 UTC
Labels: .Needs Triage, Type:Bug
