### ISSUE TITLE
Pivot Table Fails to Render

### ISSUE THREAD

**Issue by chucksense** [metabase/metabase#10025] opened 2019-05-22 21:49 UTC
## Issue
Pivot tables are failing to render when driven by custom data.

The data the SQL produces looks like this, unpivoted:
![Question · Metabase 2019-05-22 17-46-28](https://user-images.githubusercontent.com/199588/58211314-914c4700-7cb9-11e9-94d0-34ec94487b1a.jpg)

([Full exported data set](https://github.com/metabase/metabase/files/3209442/query_result_2019-05-22T21_45_41.389Z.zip))

When applying a pivot on "Dimension" the preview pivot looks like this:
![Question · Metabase 2019-05-22 17-48-51](https://user-images.githubusercontent.com/199588/58211424-e38d6800-7cb9-11e9-89f5-9b31e37b5202.jpg)

And the final rendered pivot looks like this:
![Question · Metabase 2019-05-22 17-49-28](https://user-images.githubusercontent.com/199588/58211462-f6a03800-7cb9-11e9-9ea7-7dd97484ab14.jpg)

How can I get this to export correctly?

## Bug Details
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
  - Issue occurs in both Safari 12.1 and Chrome 74.0.*
- Your operating system: (e.x. OS X 10, Windows XP, etc)
  - macOS 10.14.4 and macOS 10.14.5
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
  - Postgres
- Metabase version: (e.x. 0.19.3)
  -  0.32.5
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
  - Unsure, but if I had to guess, Beanstalk.
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
  - Again unsure, but if I had to guess, Postgres

**Comment by flamber** [comment] 2019-05-22 22:02
Hi @chucksense 
This looks like a duplicate of #8926
Currently (as of 0.32.8) Pivot needs one numeric and two grouping columns - [docs](https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html#pivoted-tables).
So the following Sample Dataset should work via QB:
![image](https://user-images.githubusercontent.com/1447303/58211937-7faf7300-7caa-11e9-8ea2-79d93e43718b.png)
And via SQL:
![image](https://user-images.githubusercontent.com/1447303/58212045-c7ce9580-7caa-11e9-941b-2efd9fa5fef9.png)

**Comment by chucksense** [comment] 2019-05-23 21:02
@flamber my dataset above has one numeric and two grouping columns, right?  So why wouldn't it work here?

**Comment by flamber** [comment] 2019-05-23 21:14
I cannot see your query, so I don't know if you're grouping `Week` and `Dimension`.
You can check the query and more details by looking in the browser developer console's Network-tab, click the POST request to show details and then look in the Response-tab.

**Comment by chucksense** [comment] 2019-05-28 20:33
@flamber Yes, I'm grouping by both `Week` and `Dimension`.  The table view comes back perfectly, it's just when I attempt to pivot it the UI breaks.  The POST's request and response data looks identical when unpivoted vs when pivoted.

This is not an issue with the query, this is an issue with the pivot UI breaking on this dataset for some reason.

**Comment by flamber** [comment] 2019-05-28 20:44
@chucksense 
Can you reproduce your issue with Sample Dataset database?
The request doesn't change depending on what visualization you're using. Can you post the response?

**Comment by HelenMertes** [comment] 2019-06-03 14:02
I have the same issue (v0.32.6, BigQuery). Grouping sum(x) by date and a dimension in standard SQL, results are fine as table but if I want to display it as Pivot, it is empty. 
Would be great if you can fix it soon!

**Comment by flamber** [comment] 2020-05-21 12:29
I cannot reproduce on 0.35.3 with dataset given:
<details>

```
SELECT 'April     22, 2019' AS "Week", 'Data 7' AS "Dimension", 1 AS "Count" UNION ALL
SELECT 'April     22, 2019' AS "Week", 'Data 4' AS "Dimension", 3 AS "Count" UNION ALL
SELECT 'April     22, 2019' AS "Week", 'Data 1' AS "Dimension", 7 AS "Count" UNION ALL
SELECT 'April     22, 2019' AS "Week", 'Data 11' AS "Dimension", 10 AS "Count" UNION ALL
SELECT 'April     22, 2019' AS "Week", 'Data 2' AS "Dimension", 55 AS "Count" UNION ALL
SELECT 'April     22, 2019' AS "Week", 'Data 8' AS "Dimension", 57 AS "Count" UNION ALL
SELECT 'April     22, 2019' AS "Week", 'Data 3' AS "Dimension", 83 AS "Count" UNION ALL
SELECT 'April     22, 2019' AS "Week", 'Data 9' AS "Dimension", 142 AS "Count" UNION ALL
SELECT 'April     22, 2019' AS "Week", 'Data 5' AS "Dimension", 164 AS "Count" UNION ALL
SELECT 'April     22, 2019' AS "Week", 'Data 10' AS "Dimension", 565 AS "Count" UNION ALL
SELECT 'April     29, 2019' AS "Week", 'Data 1' AS "Dimension", 7 AS "Count" UNION ALL
SELECT 'April     29, 2019' AS "Week", 'Data 3' AS "Dimension", 34 AS "Count" UNION ALL
SELECT 'April     29, 2019' AS "Week", 'Data 2' AS "Dimension", 38 AS "Count" UNION ALL
SELECT 'April     29, 2019' AS "Week", 'Data 8' AS "Dimension", 58 AS "Count" UNION ALL
SELECT 'April     29, 2019' AS "Week", 'Data 5' AS "Dimension", 123 AS "Count" UNION ALL
SELECT 'April     29, 2019' AS "Week", 'Data 9' AS "Dimension", 136 AS "Count" UNION ALL
SELECT 'April     29, 2019' AS "Week", 'Data 10' AS "Dimension", 278 AS "Count" UNION ALL
SELECT 'May       06, 2019' AS "Week", 'Data 2' AS "Dimension", 6 AS "Count" UNION ALL
SELECT 'May       06, 2019' AS "Week", 'Data 3' AS "Dimension", 37 AS "Count" UNION ALL
SELECT 'May       06, 2019' AS "Week", 'Data 8' AS "Dimension", 70 AS "Count" UNION ALL
SELECT 'May       06, 2019' AS "Week", 'Data 5' AS "Dimension", 144 AS "Count" UNION ALL
SELECT 'May       06, 2019' AS "Week", 'Data 9' AS "Dimension", 160 AS "Count" UNION ALL
SELECT 'May       06, 2019' AS "Week", 'Data 10' AS "Dimension", 283 AS "Count" UNION ALL
SELECT 'May       13, 2019' AS "Week", 'Data 1' AS "Dimension", 1 AS "Count" UNION ALL
SELECT 'May       13, 2019' AS "Week", 'Data 4' AS "Dimension", 3 AS "Count" UNION ALL
SELECT 'May       13, 2019' AS "Week", 'Data 2' AS "Dimension", 8 AS "Count" UNION ALL
SELECT 'May       13, 2019' AS "Week", 'Data 3' AS "Dimension", 31 AS "Count" UNION ALL
SELECT 'May       13, 2019' AS "Week", 'Data 5' AS "Dimension", 48 AS "Count" UNION ALL
SELECT 'May       13, 2019' AS "Week", 'Data 8' AS "Dimension", 81 AS "Count" UNION ALL
SELECT 'May       13, 2019' AS "Week", 'Data 9' AS "Dimension", 99 AS "Count" UNION ALL
SELECT 'May       13, 2019' AS "Week", 'Data 6' AS "Dimension", 103 AS "Count" UNION ALL
SELECT 'May       13, 2019' AS "Week", 'Data 10' AS "Dimension", 226 AS "Count" UNION ALL
SELECT 'May       20, 2019' AS "Week", 'Data 5' AS "Dimension", 5 AS "Count" UNION ALL
SELECT 'May       20, 2019' AS "Week", 'Data 3' AS "Dimension", 9 AS "Count" UNION ALL
SELECT 'May       20, 2019' AS "Week", 'Data 2' AS "Dimension", 15 AS "Count" UNION ALL
SELECT 'May       20, 2019' AS "Week", 'Data 8' AS "Dimension", 27 AS "Count" UNION ALL
SELECT 'May       20, 2019' AS "Week", 'Data 9' AS "Dimension", 52 AS "Count" UNION ALL
SELECT 'May       20, 2019' AS "Week", 'Data 6' AS "Dimension", 72 AS "Count" UNION ALL
SELECT 'May       20, 2019' AS "Week", 'Data 10' AS "Dimension", 95 AS "Count"
```

</details>

![image](https://user-images.githubusercontent.com/1447303/82559142-60724c80-9b6f-11ea-94fa-3696a203f5cf.png)

**Closed by flamber** 2020-05-21 12:29 UTC
Labels: Priority:P2, Querying/Native, Type:Bug, Visualization/
