### ISSUE TITLE
Dashboard filter applied to Cards from different Datasources cause Dashboards to break for users without permission to view all Cards in a Dashboard

### ISSUE THREAD

**Issue by hagen** [metabase/metabase#7633] opened 2018-05-13 21:04 UTC
The source of the problem appears to be the result of creating Dashboard filters for more than one data source where the viewer of the Dashboard does not have access to both Datasources.
Typically, were I to view a Dashboard that contained Questions I *did* and *didn't* have access to, the Cards that I cannot see due to permissions would say 'Sorry, you don't have permissions to see that". Perfect.

However, if the creator of the dashboard (who has access to all Datasources) creates a filter (say a date filter) for a common field in both Questions from different Datasources, anyone that views the Dashboard that doesn't have access to all Questions the Filter is wired to, will get an error:
`Cannot read property 'type' of undefined`

This error is thrown in Parameter.js, function `getParameterTargetFieldId`.
```js
/** Returns the field ID that this parameter target points to, or null if it's not a dimension target. */
function getParameterTargetFieldId(target, datasetQuery) {
  if (target && target[0] === "dimension") {
    var dimension = target[1];
    if (Array.isArray(dimension) && (0, _util.mbqlEq)(dimension[0], "template-tag")) {
      if (datasetQuery.type === "native") {
        var templateTag = datasetQuery.native.template_tags[String(dimension[1])];
        if (templateTag && templateTag.type === "dimension") {
          return _query2.default.getFieldTargetId(templateTag.dimension);
        }
      }
    } else {
      return _query2.default.getFieldTargetId(dimension);
    }
  }
  return null;
}
```

- Your browser and the version: Chrome 67
- Your operating system: Windows 10
- Your DB: Aurora (MySQL)
- Metabase version: 0.29.0
- Metabase hosting environment: EB
- Metabase internal database: PG

# Steps to repeat
* Create two data sources, D1 and D2 (both point to the same database, but with differing credentials). The table you use from the datasources should contain at least a timestamp field and a category field that is common.
* Create two Groups, G1 and G2. Give G1 full access to D1. Give G2 full access to G2. Also give G1 full access to D2 (this allows G1 to access both D1 and D2, but G2 is restricted to D2). 
* Create two Users, U1 and U2. Assign U1 to G1, and U2 to G2. U1 is kind of the _owner_ of both datasources. U2 is not.
* Logged in as U1, create two Questions - one for each of D1 and D2. The questions should be identical in their nature. The need to be filterable by date and category (I used a table called `invoices`, which has an `isssue_date` and `code`).
* Add the two questions to a Dashboard (Card 1 - C1; Card 2 - C2), and add two Filters - one for the date in both Cards (F1), and one for the Category in both Cards (F2).
* Log out and back in as U2.
* The dashboard _should be_ visible to U2 (but of course we know that only one of the Cards in the Dashboard will load).
* Open the Dashboard. The error `Cannot read property 'type' of undefined` is displayed:
![image](https://user-images.githubusercontent.com/5161952/39971732-abf41bf6-5743-11e8-9f51-b81cce62c9cd.png)
Here's the console error:
```js
Uncaught TypeError: Cannot read property 'type' of undefined
    at getParameterTargetFieldId (app-main.bundle.js:16403)
    at app-main.bundle.js:25216
    at vendor.bundle.js:34377
    at vendor.bundle.js:34337
    at vendor.bundle.js:34391
    at vendor.bundle.js:34337
    at vendor.bundle.js:34387
    at vendor.bundle.js:34337
    at Function.mapStateToProps [as mapToProps] (app-main.bundle.js:94766)
    at mapToPropsProxy (vendor.bundle.js:88211)
```
* If you then delete the Dashboard filter, and reload, the Dashboard loads correctly, with a message that U2 does not have permission to view C1.

It seems that for U2, when this function is called on the Card attached to D1 (which they have no access to), the datasetQuery parameter is `undefined`. That would make sense, because they have no access. But that shouldn't prevent U2 from filtering data in the Card attached to D2.

**Comment by snarfed** [comment] 2019-04-19 19:38
still happening in 0.32.4. user-visible error message is now `t is undefined`, new stack trace below. it's a pretty painful failure mode since it's basically a crash, the whole dashboard dies and doesn't render at all.

```
TypeError: "t is undefined"
    getParameterTargetFieldId https://health.color.com/app/dist/app-main.bundle.js?6e1007b711bcfd53042c:5
    getMappingsByParameter https://health.color.com/app/dist/app-main.bundle.js?6e1007b711bcfd53042c:5
    c https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:12
    i https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:12
    l https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:12
    i https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:12
    l https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:12
    i https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:12
    O https://health.color.com/app/dist/app-main.bundle.js?6e1007b711bcfd53042c:5
    i https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:139
    p https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    p https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    i https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    run https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:139
    componentWillReceiveProps https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:139
    updateComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    receiveComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    receiveComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:83
    _updateRenderedComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    _performComponentUpdate https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    updateComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    receiveComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    receiveComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:83
    _updateRenderedComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    _performComponentUpdate https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    updateComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    receiveComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    receiveComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:83
    _updateRenderedComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    _performComponentUpdate https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    updateComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    receiveComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    receiveComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:83
    _updateRenderedComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    _performComponentUpdate https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    updateComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    receiveComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    receiveComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:83
    _updateRenderedComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    _performComponentUpdate https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    updateComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    receiveComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    receiveComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:83
    _updateRenderedComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    _performComponentUpdate https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    updateComponent https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    performUpdateIfNecessary https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    performUpdateIfNecessary https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:83
    b https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:83
    perform https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:94
    perform https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:94
    perform https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:83
    w https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:83
    closeAll https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:94
    perform https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:94
    batchedUpdates https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    t https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:83
    a https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:110
    enqueueSetState https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:110
    setState https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:96
    onStateChange https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:139
    notify https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    notifyNestedSubs https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    onStateChange https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:139
    m https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:139
    default https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    default https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:110
    f https://health.color.com/app/dist/app-main.bundle.js?6e1007b711bcfd53042c:5
    dispatch https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    t https://health.color.com/app/dist/app-main.bundle.js?6e1007b711bcfd53042c:5
    w https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    _invoke https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    e https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    r https://health.color.com/app/dist/app-main.bundle.js?6e1007b711bcfd53042c:5
    r https://health.color.com/app/dist/app-main.bundle.js?6e1007b711bcfd53042c:5
    a https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    L https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:145
    c https://health.color.com/app/dist/vendor.bundle.js?6e1007b711bcfd53042c:94
```

**Comment by salsakran** [comment] 2019-04-19 20:05
@snarfed reprioritized to p1, we'll look at it now

**Comment by snarfed** [comment] 2019-04-19 20:30
thanks @salsakran! fyi i tried out https://github.com/griddynamics/metabase/commit/32d879714d3921cc82667b269db883825fae6729 just now (after resolving a minor conflict) and it indeed fixes this.

**Comment by salsakran** [comment] 2019-08-19 21:17
@walterl mind pulling in the fix snarfed references and maybe adding a test somewhere?

**Comment by walterl** [comment] 2019-08-19 21:27
@salsakran :+1:

**Comment by walterl** [comment] 2019-08-21 22:40
Following @hagen's very good steps to reproduce, I can't seem to reproduce this issue on version 0.33. Could someone affected by this please confirm that this issue still exists in 0.33? @snarfed ?

**Comment by snarfed** [comment] 2019-08-21 22:58
very possible! I'm vacationing without a computer for the next week or so, but I can look after that.

**Comment by walterl** [comment] 2019-08-21 23:07
@snarfed Thanks, and enjoy your vacation! :palm_tree:

**Comment by walterl** [comment] 2019-09-25 14:23
@snarfed Have you had a chance to see if you can reproduce this?

**Comment by snarfed** [comment] 2019-09-25 18:28
thanks for the nudge, @walterl, and sorry for the delay! i looked into this on our side just now, and our setup has changed pretty significantly, so it's not easy for me to try to reproduce any more.

thanks for merging the fix! i trust you all, feel free to close this issue.

**Comment by walterl** [comment] 2019-09-25 18:43
Thanks, @snarfed.

I'm closing this, since it cannot be reproduced. Please re-open if it pops up again for anyone.

**Closed by walterl** 2019-09-25 18:43 UTC
Labels: .Frontend, Parameters/Variables, Priority:P1, Reporting/Dashboards, Type:Bug
