### ISSUE TITLE
queries using set search_path = schema_name do not seem to work in metabase?

### ISSUE THREAD

**Issue by whitemark** [metabase/metabase#6293] opened 2017-10-30 09:01 UTC
Hello All

I'm using metabase to query a greenplum cluster, all works well, metabase is absolutely fantastic, just a problem, I have numerous schemas and it seems I cannot make the schema_path to work

I'm trying to setup the path to a schema, my query is :

set search_path = data;
SELECT "data"."test"."column1" AS "column1"
FROM "data"."test"
LIMIT 2000

Metabase returns the message "No results were returned by the query" (the table has data in it of course) It looks like metabase is only running the first statement, rather than the whole query

I also tried to setup the path in the database configuration, using set search_path = myschema in the additional JDBC connection string options, but again no luck

I'm running metabase v0.26.2 
The database is Greenplum 4.3x
metabase is running on windows 2012 server, internal db H2
java ver SE 1.8.0.144

Any idea how to make it work or it is a bug or lack of functionality?

Thanks all
Mark

**Comment by lindsay-stevens** [comment] 2017-11-01 04:31
Probably since SET is a separate command the driver considers it to be the "result" rather than the subsequent SELECT command. Here's a couple of options:

- Use [ALTER ROLE](http://gpdb.docs.pivotal.io/510/ref_guide/sql_commands/ALTER_ROLE.html) to set the search path configuration parameter as a default for the role you're connecting with, which means it'd be the default for all questions using that database / connection - though if you were looking at doing it in the database configuration then this might be desirable. 
- [Create a table-returning function](http://gpdb.docs.pivotal.io/510/ref_guide/sql_commands/CREATE_FUNCTION.html), and inside of that set the parameter as needed (or indeed make the parameter value a function parameter). While more flexible it'd require creating functions separately to using them in Metabase. Using it could look like `SELECT * FROM function_name()`

On a more academic point (and assuming Greenplum is like Postgres on this front) if you're already specifying the schema name `FROM "data"."test"` then setting the search path shouldn't be necessary. Setting this parameter would just give the option of saying `FROM "test"` and having that being taken to mean `FROM "data"."test"`.

**Comment by whitemark** [comment] 2017-11-02 22:53
Hello 
Thanks, the alter role works, it is not ideal but it works if you have just one schema per user, if you have more than one schema per user it becomes tricky 

We are using some very large and complex queries (heaps of them) and they are the same for all the users, to rewrite the lot to include database.schema.table in each statement would take ages and be prone to errors, being able to have the schema set at the beginning of the query is the standard way, it works without problems in Redash so I was surprised that Metabase could not handle separate commands

It would be great if that could be addressed

Thanks for the help!
Mark

**Comment by jlisyc** [comment] 2017-11-10 12:36
Hi,
could be interesting to pass in "Metabase admin panel --> Databases --> Additional JDBC connection string options", the option "currentSchema=myschema" to see just one schema. I tried out but it seems not working.
Thanks!

**Comment by camsaul** [comment] 2017-11-10 18:45
Duplicate of #1498

**Closed by camsaul** 2017-11-10 18:45 UTC
