### ISSUE TITLE
Query fails on "Error reducing result rows"

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#12251] opened 2020-04-02 22:04 UTC
I found more information about the problem um the api response.
The data for questions is returned bu the error I mentioned, `Error reducing result rows`, is returned together. In the returned stack trace an 

Error on Api Response:
```
class clojure.lang.ExceptionInfo","error":"Error reducing result rows","stacktrace":["--> query_processor.context.default$default_reducef$fn__37780.invoke(default.clj:61)","query_processor.context.default$default_reducef.invokeStatic(default.clj:58)","query_processor.context.default$default_reducef.invoke(default.clj:49)","query_processor.context$reducef.invokeStatic(context.clj:69)"
``` 

Error on the result query status:
```
class java.lang.StackOverflowError","stacktrace":["clojure.lang.Numbers.isZero(Numbers.java:117)","--> sync.analyze.fingerprint.insights$change.invokeStatic(insights.clj:29)","sync.analyze.fingerprint.insights$change.invoke(insights.clj:26)","sync.analyze.fingerprint.insights$change.invokeStatic(insights.clj:35)","sync.analyze.fingerprint.insights$change.invoke(insights.clj:26)"
```

_Originally posted by @rjansen in https://github.com/metabase/metabase/issues/12228#issuecomment-608113217_

**Comment by rjansen** [comment] 2020-04-02 22:07
Thanks @paulrosenzweig, I will post the test case for the bug later.
For now, I solved the issue returning Metabase to version 0.34.2.

**Comment by rjansen** [comment] 2020-04-02 22:51
Hi, @paulrosenzweig I understood the problem.
It seems to happen on results that have only negative values and one of these records has a column with value equals 0.
I executed the questions successfully adding a restriction to remove values with 0, something like `value != 0`.

The results look like:

Date                                               | Value    |
:------------------------------ | -------: |
2019-02-10 00:00:00.000000 |   -9.25   |
2019-02-09 00:00:00.000000 | -19.53   |
2019-02-08 00:00:00.000000 | -33.33  |
2019-02-05 00:00:00.000000 |    0.00   |
2019-02-04 00:00:00.000000 |    0.00   |

I will try to reproduce the issue on the sample data set and post the instructions.

**Comment by flamber** [comment] 2020-04-06 12:56
@rjansen Have you been able to reproduce this with static SQL or using Sample Dataset? I've tried a few different ways, but I cannot reproduce this issue.

**Comment by flamber** [comment] 2020-04-06 21:02
@patrickvenetz 
Which database are you querying?
Can you give any help on how to reproduce this error?

**Comment by sbelak** [comment] 2020-04-06 21:34
At least @paulrosenzweig's error is caused by a bug in `metabase.sync.analyze.fingerprint.insights/change`. This bug has been here since the code has been written, but with the new QP we seem to have lost some of the hardening.

**Comment by patrickvenetz** [comment] 2020-04-06 22:01
@flamber Using PostgreSQL 10.12

I can reproduce it somewhat reliably.

__Steps to reproduce__

1. Create table

```sql
CREATE TABLE "sampleData" (
    a timestamp with time zone PRIMARY KEY,
    b real,
    c real,
    d real,
    e real,
    f real
);
```

2. Populate table

```sql
INSERT INTO "sampleData"("a","b","c","d","e","f")
VALUES
(E'2018-01-31 23:59:59+00',1241,0,1241,0,1241),
(E'2018-02-28 23:59:59+00',378,-265,113,9.10556e+18,1354),
(E'2018-03-31 23:59:59+00',266,-176,90,6.646972e+17,1444),
(E'2018-04-30 23:59:59+00',401,-215,186,1.2880886e+18,1630),
(E'2018-05-31 23:59:59+00',454,-208,246,1.5092024e+19,1876),
(E'2018-06-30 23:59:59+00',134,-242,-108,-5.7569296e+18,1768),
(E'2018-07-31 23:59:59+00',140,-199,-59,-3.337104e+18,1709),
(E'2018-08-31 23:59:59+00',141,-204,-63,-3.6863662e+18,1646),
(E'2018-09-30 23:59:59+00',163,-165,-2,-1.2150669e+17,1644),
(E'2018-10-31 23:59:59+00',231,-155,76,4.622871e+18,1720),
(E'2018-11-30 23:59:59+00',256,-167,89,5.1744185e+17,1809),
(E'2018-12-31 23:59:59+00',205,-164,41,2.2664456e+18,1850),
(E'2019-01-31 23:59:59+00',388,-255,133,7.189189e+18,1983),
(E'2019-02-28 23:59:59+00',107,-235,-128,-6.4548666e+18,1855),
(E'2019-03-31 23:59:59+00',169,-164,5,2.6954178e+16,1860),
(E'2019-04-30 23:59:59+00',107,-166,-59,-3.172043e+18,1801),
(E'2019-05-31 23:59:59+00',95,-148,-53,-2.9428096e+16,1748),
(E'2019-06-30 23:59:59+00',117,-128,-11,-6.2929064e+17,1737),
(E'2019-07-31 23:59:59+00',132,-115,17,9.7869894e+17,1754),
(E'2019-08-31 23:59:59+00',119,-131,-12,-6.841505e+16,1742),
(E'2019-09-30 23:59:59+00',81,-112,-31,-1.7795637e+18,1711),
(E'2019-10-31 23:59:59+00',136,-111,25,1.4611338e+17,1736),
(E'2019-11-30 23:59:59+00',99,-104,-5,-2.8801844e+15,1731),
(E'2019-12-31 23:59:59+00',325,-135,190,1.0976314e+18,1921),
(E'2020-01-31 23:59:59+00',184,-163,21,1.09318064e+18,1942),
(E'2020-02-29 23:59:59+00',282,-134,148,7.621009e+18,2090),
(E'2020-03-31 23:59:59+00',1396,-134,1262,6.0382776e+18,3352),
(E'2020-04-30 23:59:59+00',185,-84,101,3.0131264e+18,3453);
```

3. Query data in Metabase as question, native query:

```sql
SELECT * FROM "sampleData" ;
```

UI looks like it's fetching data forever.

Inspecting network, `/api/dataset` is queried, response body is not parseable (invalid JSON, `.data.rows[]`  interrupted by error mentioned in https://github.com/metabase/metabase/issues/12251#issuecomment-610022100).

**Comment by patrickvenetz** [comment] 2020-04-06 22:09
Addendum. Ordering sample data seems to have an impact. 

__Works__

```sql
SELECT * FROM "sampleData" ORDER BY a ASC ;
```

__Won't work__

```sql
SELECT * FROM "sampleData" ORDER BY a DESC ;
```

**Comment by sbelak** [comment] 2020-04-06 22:15
Simpler repo:
`select parsedatetime('2019', 'yyyy') as t, -1 as x
union all
select parsedatetime('2020', 'yyyy') as t, 0 as x`

There's a bug in `metabase.sync.analyze.fingerprint.insights/change` causing infinite recursion. But since this is fingerprinting/insights code the bigger bug is that this stops the whole QP.

**Comment by sbelak** [comment] 2020-04-08 13:11
Fixed both the root cause (#12282) and hardened the QP (#12289)

**Comment by rjansen** [comment] 2020-04-08 19:58
Thanks, @patrickvenetz!
Great job. 🎉

**Comment by rjansen** [comment] 2020-04-08 20:02
Hi, @sbelak. Thanks for the help. Do you have the fix docker image?

**Comment by rjansen** [comment] 2020-04-08 20:03
Would be `metabase/metabase-head:fix-12251`?

**Comment by sbelak** [comment] 2020-04-08 20:04
We'll release a patch release in a few days.

**Comment by flamber** [comment] 2020-04-10 23:07
This didn't make it into 0.35.2, but it will be part of 0.35.3

**Comment by dacort** [comment] 2020-04-13 15:53
PR to merge into `release-0.35.x` branch is at https://github.com/metabase/metabase/pull/12315

**Comment by flamber** [comment] 2020-04-14 19:10
This was merged now, so it will be part of 0.35.3

**Closed by flamber** 2020-04-14 19:10 UTC
Labels: Administration/Metadata & Sync, Priority:P1, Type:Bug

**Comment by parsaap** [comment] 2020-04-16 18:05
Is there a rough release date for 0.35.3? We are also disrupted by this bug

**Comment by flamber** [comment] 2020-04-16 18:08
@parsaap Today - or maybe tomorrow. Don't hang me up on it.
