### ISSUE TITLE
Incorrect join on date column

### ISSUE THREAD

**Issue by dubravcik** [metabase/metabase#16130] opened 2021-05-18 12:34 UTC
**Describe the bug**
When I join a table on another table using date column it generates incorrect ON statement (see screenshot).

I would expect that it generates simply the date columns on both sides:

```
ON "F_Kontent_SubscriptionMetric"."DATE Effective" = "D_Date"."Date"
```

but instead it generates this (date of week on left side and date of month on right side):

```
ON CAST(dateadd(day, (1 - datepart(weekday, "kontent"."F_Kontent_SubscriptionMetric"."DATE Effective") - -1), "kontent"."F_Kontent_SubscriptionMetric"."DATE Effective") AS datetime) = DateFromParts(year("D_Date"."Date"), month("D_Date"."Date"), 1)
```

**To Reproduce**
1. Go to question editor
2. join another table on a Date column (I tested Date dimension and also randomly picked table with date column and bot had the bug)

**Expected behavior**
I would expect that the table are joined row by row without any column transformation in the join.

**Screenshots**
![image](https://user-images.githubusercontent.com/2481962/118649514-dee5e680-b7e3-11eb-8b99-c64f1234d479.png)

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_262-b10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_262",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.262-b10",
    "os.name": "Windows Server 2019",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Europe/Prague"
  },
  "metabase-info": {
    "databases": [
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.39.1",
      "date": "2021-04-27",
      "branch": "release-x.39.x",
      "hash": "6beba48"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
It is confusing as it joins few rows (when week=month). Moreover we cannot use any custom field from Date dimension.
In situations when you need to join two question on Date column it makes impossible to use the editor, and we would have to write custom SQL.

**Additional context**
FYI I use SQL Server database, and I don't know if it is problem for other dbs as well.

**Comment by flamber** [comment] 2021-05-18 12:41
Duplicate of #10924

**Closed by flamber** 2021-05-18 12:41 UTC
Labels: .Needs Triage, Type:Bug
