### ISSUE TITLE
Dropping Column from Underlying Table Breaks GUI Editor

### ISSUE THREAD

**Issue by sambradbury** [metabase/metabase#38538] opened 2024-02-08 01:01 UTC
### Describe the bug

When a question created using the GUI editor (not the native sql editor) is trying to select a column that has been been dropped from the underlying table the question breaks (this part makes sense) but the `Show editor` also breaks. Ideally one could click into the `Show editor` button so as to remove the now missing column thus fixing the query. 

### To Reproduce

1. Create a question using the custom/GUI editor which selects column A from table B
2. Drop column A from table B 
3. <img width="729" alt="Screenshot 2024-02-07 at 17 56 39" src="https://github.com/metabase/metabase/assets/31943456/c783f55d-655d-4972-8d75-7b5871812df2">
4. Click the show editor button on the question
<img width="659" alt="Screenshot 2024-02-07 at 17 56 44" src="https://github.com/metabase/metabase/assets/31943456/e5643a4e-ae02-4201-969f-f340deefd14e">

### Information about your Metabase installation

```JSON
- Browser: Version 1.57.57 Chromium: 116.0.5845.163 (Official Build) (x86_64)
- Metabase Version: You're on version v1.48.3
```

### Severity

Medium

**Comment by ignacio-mb** [comment] 2024-02-21 16:19
Hi @sambradbury I couldn't reproduce. My steps were:

1. Have a table in Postgres called Countries with fields: Id, Country
2. Make a GUI query basic all from Countries.
3. Save the question
4. Go to the database, run `ALTER TABLE countries DROP COLUMN Country;`
5. Go to the question, see the error 
> column countries.country does not exist
6. Click Editor button, I can access the query editor. 

What am I missing?

**Comment by ignacio-mb** [comment] 2024-02-21 16:19
related to https://github.com/metabase/metabase/issues/12721

**Comment by kamilmielnik** [comment] 2024-05-20 08:17
> What am I missing?

Database schema needs to be resynced in Admin > Databases after dropping the column.
With this I can reproduce the issue.

The notebook editor does not crash anymore but it's not possible to fix the query manually because the missing column isn't shown.

----

Automatically fixing such cases would not always be possible due to edge cases (e.g. the only column from a query has been dropped) so it feels ok to leave it to the users to fix them.

From technical perspective we'd need to change MLv2 behavior a bit, so that functions like `Lib.visibleColumns` would return query columns that aren't present in the metadata (so all `Lib.*Columns` functions). We wouldn't be able to display names of those columns in UI though (since they're not in metadata anymore) but I think it's ok if we displayed them as "Unknown column" or something like that - just enough to let users fix the query.

This definitely needs QP changes (and possibly QC changes depending on what QP changes would look like) so I'm sending this issue that way.

**Comment by camsaul** [comment] 2024-06-26 03:13
Duplicate of #38532

**Closed by camsaul** 2024-06-26 03:13 UTC
Labels: Type:Bug, Priority:P2, Querying/Processor, Querying/MBQL, .Backend, .Team/QueryProcessor
