### ISSUE TITLE
Column selection by a variable value

### ISSUE THREAD

**Issue by pavelbukhtik** [metabase/metabase#12143] opened 2020-03-17 08:27 UTC
**Is your feature request related to a problem?**
I ran into this problem when migrating sql queries from Redash to Metabase. In Redash, I could use parameters not only to specify conditions in the "where" expression, but also to specify a specific column to select. To be honest, I don't know if this tricky substitution has any name, so I'm going to share an example. 

Redash:
<img width="377" alt="Screenshot 2020-03-17 at 10 21 46" src="https://user-images.githubusercontent.com/26227765/76832712-efdf4480-683a-11ea-83f2-4ead6d6a5f0e.png">

As you can see in the picture above, I specified the column name as an argument to the parameter to select. The "first_column" at the bottom of the image indicates that the column was successfully selected.

Metabase:
<img width="373" alt="Screenshot 2020-03-17 at 10 23 21" src="https://user-images.githubusercontent.com/26227765/76832870-4482bf80-683b-11ea-82f5-6aade0dffb15.png">

If I try to do the same in Metabase, it selects a string value instead of a column.

**Describe the solution you'd like**
It would be great to be able to make such selections of columns in Metabase as in Redash. If there is any alternative solution, I will be glad to know about it.

**Describe alternatives you've considered**
Since the string value is substituted, I tried to somehow ignore the quotation marks - to no avail.

**How important is this feature to you?**
The company I currently work for is looking for a more user-friendly visualisation tool, so anyone in the company can analyze data without the knowledge of SQL. The metabase is perfect for us, and we would like to thank you for what you do. Unfortunately, we have a ton of queries for dashboards that use the dynamic queries described above and we don’t yet know any alternatives for writing such queries.

**Comment by flamber** [comment] 2020-03-17 10:03
Hi @pavelbukhtik 
Variables are currently specific to the WHERE clause:
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html
Duplicate of #4639.

**Closed by flamber** 2020-03-17 10:03 UTC
Labels: .Duplicate
