### ISSUE TITLE
Jetty temporary errors

### ISSUE THREAD

**Issue by ihackalot** [metabase/metabase#4301] opened 2017-02-02 20:06 UTC
I have a metabase installation behind haproxy and pretty often I receive server errors that just disappear as soon as I refresh the browser. Errors like this:

```html
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1" />
    <title>Error 500</title>
</head>

<body>
    <h2>HTTP ERROR: 500</h2> 
    <p>
        Problem accessing /api/activity. 
        Reason: <pre> Communications link failure The last packet successfully received from the server was 7,196,566 milliseconds ago. The last packet sent successfully to the server was 1 milliseconds ago.</pre>
    </p>
    <hr /><i><small>Powered by Jetty://</small></i> 
</body>

</html>
```
Apart from that metabase works pretty well so far.

**Comment by salsakran** [comment] 2017-02-02 21:41
That's strange. I don't think I've ever seen that before. Are there haproxy or metabase server logs around this timeframe?

**Comment by ihackalot** [comment] 2017-02-02 22:23
Haproxy didn't compain at all, its error log is empty, but I could grab this while `docker log -f metabase`: https://cl.ly/0Z0E0G3A381Q

**Comment by camsaul** [comment] 2017-02-02 22:34
looks like most of the errors there are related to issues connecting to your MySQL DB

**Comment by ihackalot** [comment] 2017-02-02 22:52
I see, although the connected mariadb container is doing well without errors, and metabase does indeed work, if not for those server errors that may happen only when I first connect. Then I refresh, and as long as I work everything is just fine. If I stop hitting the server for a couple of minutes it might (or might not) happen again.

**Comment by camsaul** [comment] 2017-02-02 23:05
do any of the servers spin down / sleep if not being used (e.g. like in a free Heroku instance)?

**Comment by ihackalot** [comment] 2017-02-02 23:13
Metabase containers are monitored by a rancher server, which does indeed run healthchecks, and in case of "unhealthy" containers recreates them, but as far as I can tell this was not the case (i had the rancher stack open in a tab next to metabase and streaming logs to output, so I can tell). Anyhow downtime is the only thing I can think of myself.
I'm running a vanilla mariadb container, do you suggest any particular .cnf file maybe?

**Comment by ihackalot** [comment] 2017-02-22 21:28
Found [this thread](http://stackoverflow.com/questions/2983248/com-mysql-jdbc-exceptions-jdbc4-communicationsexception-communications-link-fai) which might explain the issue. My setup has docker env variable `MB_JETTY_PORT` set to `3200` although `MB_DB_PORT` is set to the standard `3306`. I can ping db from metabase and viceversa no problem and everything still working fine, but this... _lazyness_.

**Comment by salsakran** [comment] 2017-02-22 22:40
@ihackalot this sounds like an issue with your networking configuration, and not a bug (or even issue with Metabase). 

Given our lack of visibility into your specific setup, and that there's not a whole lot we can do to help. 

I'm closing this issue, but feel free to re-open it if you find something wrong going on w/ Metabase itself.

**Closed by salsakran** 2017-02-22 22:40 UTC
Labels: Running Metabase

**Comment by ihackalot** [comment] 2017-02-24 09:55
Yep, it definitely hasn't to do with metabase itself, but Haproxy in front of it. Still, It's really weird and I don't understand why it triggers this error and then upon refresh everything is just fine.
If you do have suggestions I would really appreciate that! 🙃

**Comment by ihackalot** [comment] 2017-02-24 23:14
Actually I found it to be related to [#4077](https://github.com/metabase/metabase/issues/4077) and as of now, the best haproxy config to front metabase that I found is the following:

```
default
    timeout connect 1000
    timeout check 1000
    timeout client 10000
    timeout server 10000
```
