### ISSUE TITLE
Metabot Slack Post Doesnt Support UTF-8 Non-English Characters

### ISSUE THREAD

**Issue by cavemancoder999** [metabase/metabase#7679] opened 2018-05-22 06:00 UTC
### Bug
Metabot Slack Post Doesnt Support UTF-8 Non-English Characters

- Browser: Firefox 60.0.1
- OS: Windows 10
- Database: Postgresql
- Metabase version: 0.29.3
- Metabase hosting environment: Java, local machine
- Metabase internal database: 

- *Repeatable steps to reproduce the issue*
Have database with utf-8 encoding, non-english characters (ie: asian languages)
Have question in Metabase setup
Have Slack Metabot setup
Use Metabot in slack eg: Metabot Product By Name
Notice that Metabot posted image contains incorrect charcters (ie: white square)
where non-english characters should appear.

**Comment by camsaul** [comment] 2018-07-17 20:19
Duplicate of #2342

**Closed by camsaul** 2018-07-17 20:19 UTC
Labels: Type:Bug, Priority:P2, Reporting/MetaBot
