### ISSUE TITLE
Zero-padded days and months in dates

### ISSUE THREAD

**Issue by shakudu** [metabase/metabase#13360] opened 2020-10-05 06:17 UTC
**Is your feature request related to a problem? Please describe.**
The current date format is hard to read.

**Describe the solution you'd like**
I would like dates to be zero-padded. Instead of 2018-1-7 you get the more standard 2018-01-07.
You could provide an "advanced" option where you get to supply your own date format like "yyyy-MM-dd". One could even do the same for time formatting.

**Describe alternatives you've considered**
I'm sure there's a hack somewhere to get it the way i want but i haven't explored any.

**How important is this feature to you?**
My users tend to prefer tables instead of nice graphs. Dates like that in a table makes it difficult to find the right information.
And date columns that are not of equal lenght is not aesthetically pleasing to look at.

**Additional context**

**Comment by flamber** [comment] 2020-10-05 09:02
Duplicate of #9191

**Closed by flamber** 2020-10-05 09:02 UTC
Labels: .Needs Triage, Type:New Feature
