### ISSUE TITLE
Please add Subscription - quarterly ( send option )

### ISSUE THREAD

**Issue by ubreathtaking** [metabase/metabase#34952] opened 2023-10-23 10:40 UTC
Good day. 
Can you please add a subscription option - to send report quarterly.
As of now, the options are : Hourly/Weekly/Daily/monthly. 

Thank you in advanced.

**Comment by likeshumidity** [comment] 2023-10-25 21:41
Closing as duplicate of https://github.com/metabase/metabase/issues/3846

**Closed** 2023-10-25 21:46 UTC
Labels: Type:New Feature, .Needs Triage
