### ISSUE TITLE
Native queries don't have "Unit of currency" formatting setting

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#15455] opened 2021-04-02 13:25 UTC
GUI questions have a "Unit of currency" setting to change the currency from the instance default.

![image](https://user-images.githubusercontent.com/691495/113419273-1a903280-9395-11eb-887e-dccdfec2c676.png)

Native questions can be set to display a currency, but you cannot pick which currency:

![image](https://user-images.githubusercontent.com/691495/113419336-41e6ff80-9395-11eb-8809-cecc86cdb7ab.png)

**Comment by paoliniluis** [comment] 2021-04-02 13:32
Workaround is to go to Settings->Admin->Data Model, change the field to a currency field type and select the currency that you want to use

**Comment by paulrosenzweig** [comment] 2021-04-02 13:34
@paoliniluis I don't think that will work. With native queries, we don't know what fields from the data model were used. It's possible the returned values don't even correspond to any fields in the database.

**Comment by paoliniluis** [comment] 2021-04-02 13:41
yup @paulrosenzweig, I'm still sleepy, just deleted my previous comment

**Comment by paoliniluis** [comment] 2021-04-02 13:44
Related to https://github.com/metabase/metabase/issues/10787 and https://github.com/metabase/metabase/issues/11233

**Comment by flamber** [comment] 2021-04-02 14:00
Duplicate of #10787/#11233

**Closed by flamber** 2021-04-02 14:00 UTC
Labels: Priority:P3, Type:Bug, Type:Completeness
