### ISSUE TITLE
 Include possibility of icons (font-awesome) in columns

### ISSUE THREAD

**Issue by renatofritola** [metabase/metabase#12759] opened 2020-06-23 11:50 UTC
As well as having several colors, icons in consultations can help a lot in monitoring screens indicating a status, category etc ...

This facilitates the identification of the data and action on it.

**Comment by flamber** [comment] 2020-06-23 12:20
Hi @renatofritola 
I don't understand what you're looking for, but it sounds like a duplicate of #1903.
You can already apply colors: https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html#conditional-table-formatting

**Closed by flamber** 2020-06-23 12:20 UTC
Labels: .Needs Triage, Type:New Feature

**Comment by renatofritola** [comment] 2020-07-16 14:16
> Hi @renatofritola
> I don't understand what you're looking for, but it sounds like a duplicate of #1903.
> You can already apply colors: https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html#conditional-table-formatting

Colors are limited, only 6 options.
It should be possible for me to inform the color I want (Hexadeciaml, RGB) so I can give you a richer visualization to improve decisions.
