### ISSUE TITLE
Stacked bar chart fails to display x-axis label for single bar

### ISSUE THREAD

**Issue by danishpatelcex** [metabase/metabase#9446] opened 2019-02-19 10:13 UTC
Please find the attachment, where bar chart with x-axis label, shows customer names  in case of multiple customers, but fails in case of single customer.

Please find the details below:

* Your browser and the version: Chrome 71.0.3578.80 (Official Build) (64-bit)
* Your operating system: Windows 10
* Your databases: MySQL
* Metabase version: v0.32.0
* Metabase hosting environment: Linux/Ubuntu
* Metabase internal database: MySQL

![single-bar-chart-issue](https://user-images.githubusercontent.com/13693154/53007224-d368b100-345c-11e9-8dd9-ad0abf510d28.png)

**Comment by flamber** [comment] 2019-02-19 19:04
Hi @danishpatelcex 
This looks like a duplicate of #8540 - if yes, then please close this issue and :+1: the other issue.

**Closed** 2019-02-22 19:06 UTC
Labels: Duplicate
