### ISSUE TITLE
Zoom In / Out buttons in Region Map

### ISSUE THREAD

**Issue by talenodigital** [metabase/metabase#40659] opened 2024-03-27 05:32 UTC
Requesting for a Zoom  In / Out buttons for Region Map as well.

Reference: https://github.com/metabase/metabase/issues/33928

**Comment by ignacio-mb** [comment] 2024-03-27 12:13
Dupe of https://github.com/metabase/metabase/issues/33928

**Closed by ignacio-mb** 2024-03-27 12:13 UTC
Labels: Type:New Feature, .Needs Triage
