### ISSUE TITLE
Click Behavior for filters with multiple options selected - Category filters

### ISSUE THREAD

**Issue by rlhez** [metabase/metabase#22698] opened 2022-05-13 09:47 UTC
**Describe the bug**
I have a dashboard set up that includes A category filter with multiple options selected.

In the Dashboard, I have a SQL defined question where the click behavior is enabled and redirects to a detail question where the Dashboard filter is mapped to a variable (variable set up as Field filter) in this detail question.

If I click on the SQL question that appears in the dashboard, the detail question appears to be empty, the Dashboard's filter has not been properly passed to the question.

This happens to be the case since [our upgrade to 0.42](https://www.metabase.com/blog/Metabase-0.42/index.html). That includes changes to category filters :

> We’ve improved the filtering experience, including allowing the use of string and numerical operators in dashboard filters, as well as an improved interface for category selection. Dashboard filter performance has also been quite improved.

**Logs**

**To Reproduce**
1. Define a SQL question nb 1
2. Add it to a dashboard
3. Set up a category filter on the dashboard
4. Define a SQL question nb 2 with a variable taking using the same field you used for the dashboard filter
5. Set up a click behavior (of type go to question) on SQL question nb 1 mapping the dashboard filter to the varibale created on SQL question nb2
6. Save
7. Select several options in your dashboard filter
8. Click on SQL question nb 1

**Expected behavior**
![filter_result_2](https://user-images.githubusercontent.com/4458804/168256471-fe12ecbf-4ac2-4e1c-a8f6-2b305c4c3d98.png)
Instead of
![filter_result_1](https://user-images.githubusercontent.com/4458804/168256512-6725a37c-faf5-4806-8eb7-0ea1e2b2ac33.png)

**Screenshots**
![category_filter](https://user-images.githubusercontent.com/4458804/168256394-37b9d786-6ba4-4399-b084-417e0ad8802c.png)

**Severity**
Partially Blocking users. Temporary work around communicated : manually change filters on the detail questions

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "5.4.176-91.338.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-04-07",
      "tag": "v0.42.4",
      "branch": "release-x.42.x",
      "hash": "7c3ce2d"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

**Comment by flamber** [comment] 2022-05-13 10:00
Duplicate of #17160 - this is not new in 42, it's always been like that, but only for dashboard filters. If you make the Click Behavior directly to the question, then it should work as expected.

**Closed by flamber** 2022-05-13 10:00 UTC

**Comment by rlhez** [comment] 2022-05-13 10:11
@flamber thanks for the quick reply 

I noticed this problem before this problem if the Click Behavior links to a url.

Here, if you look at the screenshot, it is set up to go directly to a question.

![category_filter](https://user-images.githubusercontent.com/4458804/168256394-37b9d786-6ba4-4399-b084-417e0ad8802c.png)

**Comment by flamber** [comment] 2022-05-13 10:40
That's a regression. I've updated #17160
