### ISSUE TITLE
Pivot table dissapears when going to the notebook editor and return to the viz

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#43129] opened 2024-05-24 16:15 UTC
### Describe the bug

The FE will clean the rendering when going to the notebook editor and return to the viz

### To Reproduce

1) make a question like
![image](https://github.com/metabase/metabase/assets/1711649/ae98ebb4-f626-46af-bcaf-824791fdbd59)

2) use a pivot table to visualize it
3) then go to the notebook editor again
4) then click again on the same place to go back to the viz

the table is empty

### Expected behavior

It should show you the viz

### Logs

NA

### Information about your Metabase installation

```JSON
v50
brave
```

### Severity

P2

### Additional context

![Peek 2024-05-24 13-13](https://github.com/metabase/metabase/assets/1711649/da557b36-d1c7-41a6-bcaf-47d0855fd3e8)

**Comment by nemanjaglumac** [comment] 2024-07-03 13:32
Duplicate of #39504

**Closed by nemanjaglumac** 2024-07-03 13:32 UTC
Labels: Type:Bug, Priority:P2, .Frontend, Visualization/Tables, .Regression, .Team/DashViz
