### ISSUE TITLE
Since v0.42.2 can't add a new MySQL database

### ISSUE THREAD

**Issue by lpadula** [metabase/metabase#20827] opened 2022-03-03 16:33 UTC
**Describe the bug**
Since v0.42.2 can't add a new MySQL database with SSH tunnel option enabled.

**To Reproduce**
1. Go to Admin -> Databases -> Add Database.
2. Select MySQL database and complete SSH tunnel fields.
3. Save.

**Expected behavior**
New database added or a connection error detail show on screen. Instead the page is reloaded with empty fields and the database is never added.

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.56",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "5.4.0-100-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.2 (Debian 14.2-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-28",
      "tag": "v0.42.2",
      "branch": "release-x.42.x",
      "hash": "d6ff494"
    },
    "settings": {
      "report-timezone": "America/Argentina/Buenos_Aires"
    }
  }
}

**Severity**
Blocking some users.

**Comment by flamber** [comment] 2022-03-03 17:05
Hi @lpadula 
Sounds like a duplicate of #20756, but you are not providing any information.
It works fine when I test and several different setups and MySQL databases through SSH.
So which version were you using before, since I doubt it's something specific to 0.42.2?

**Closed by flamber** 2022-03-03 17:05 UTC
Labels: Type:Bug, .Needs Triage
