### ISSUE TITLE
Delete database modal should confirm the name of the database

### ISSUE THREAD

**Issue by xPaw** [metabase/metabase#13473] opened 2020-10-14 16:46 UTC
Link: https://github.com/metabase/metabase/blob/5e8ff50d5ed3f0d569ce4e196fcd272d594eabb7/frontend/src/metabase/admin/databases/components/DeleteDatabaseModal.jsx

Right now, when deleting a database, modal asks "Delete this database?" and to confirm you have to type "DELETE", but nowhere in this modal does it actually say the name of the database you are about to delete.

A common thing to do with confirmations like that, is asking the user to type the name of the database, instead of "DELETE" in the confirmation input.

**Comment by flamber** [comment] 2020-10-14 16:56
Duplicate of #12883

**Closed by flamber** 2020-10-14 16:56 UTC
