### ISSUE TITLE
Missed columns title in resulting matrix view

### ISSUE THREAD

**Issue by M4zD4i** [metabase/metabase#6234] opened 2017-10-23 10:47 UTC
- Your browser and the version: Safari 11.0 (12604.1.38.1.7)
- Your operating system: MacOS Sierra 10.12.6
- Your databases: Apache Impala
- Metabase version: fork from 0.26.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

Steps to reproduce:
1. Create a query in Builder using count(*) for results and grouping them by 2 parameters
2. Matrix view will be resulting but there are no title for columns, for rows only:
![question metabase 2017-10-23 13-41-58](https://user-images.githubusercontent.com/1096609/31885115-1776f1aa-b7f8-11e7-8970-d0a0d6e11833.png)

**Comment by flamber** [comment] 2019-02-17 23:13
Hi @M4zD4i 
When an initial result returns 3 columns, then the table is automatically set to `Pivot`, which can be changed under the visualization settings (:gear:).
Pivot enabled:
![image](https://user-images.githubusercontent.com/1447303/52920891-1c8ef880-32d7-11e9-95f3-4b0709254a3b.png)
Pivot disabled:
![image](https://user-images.githubusercontent.com/1447303/52920913-506a1e00-32d7-11e9-83d0-d0ebb12ef3d3.png)

**Comment by flamber** [comment] 2020-06-03 13:26
Closing, since this is expected behavior of Pivot. Please comment with more details if you disagree.

**Closed by flamber** 2020-06-03 13:26 UTC
Labels: Priority:P3, Type:UX, Visualization/Tables
