### ISSUE TITLE
Export button missing when using optional clause

### ISSUE THREAD

**Issue by hugocar** [metabase/metabase#5137] opened 2017-05-18 09:16 UTC
The export button is absent in the cases described below.

```
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: Firefox up-to-date, Safari 9.1.2

- Metabase version: 0.24.1
- Metabase hosting environment: .jar on linux
- Metabase internal database: MYSQL
```
- *Repeatable steps to reproduce the issue*

## Simple request without variables : export button is present
<img width="1214" alt="capture d ecran 2017-05-18 a 11 04 53 am" src="https://cloud.githubusercontent.com/assets/19691106/26195051/c267338c-3bba-11e7-8353-1dc3c24d9227.png">

## Same request with a variable : export button is **absent**
<img width="1214" alt="capture d ecran 2017-05-18 a 11 04 17 am" src="https://cloud.githubusercontent.com/assets/19691106/26195050/c266def0-3bba-11e7-8df3-d32e6702bd8e.png">

## Same request with a variable  and a value: export button is present
<img width="1228" alt="capture d ecran 2017-05-18 a 11 03 50 am" src="https://cloud.githubusercontent.com/assets/19691106/26195052/c26cbfb4-3bba-11e7-9ac7-95bb06e57fa8.png">

**Comment by mazameli** [comment] 2017-05-18 16:35
Duplicate of https://github.com/metabase/metabase/issues/5047 and fixed by #5099. Sorry for the inconvenience!

**Closed by mazameli** 2017-05-18 16:35 UTC
