### ISSUE TITLE
Add person/user doesn't works

### ISSUE THREAD

**Issue by jommgoncalves** [metabase/metabase#1738] opened 2016-01-15 15:05 UTC
Hi,

I'm trying to add a new person/user in "Admin Panel" but doesn't works. I'm using a docker image at this moment and this error isn't registered in log.

Below, a screenshot with a error (my browser is Google Chrome):
![error](https://cloud.githubusercontent.com/assets/5732101/12356128/d3586fce-bb98-11e5-99bc-61d7e3e12042.png)

Thanks a lot,

**Comment by agilliland** [comment] 2016-01-15 16:38
What version of Metabase are you using (available by clicking `About Metabase` from the dropdown in the upper right corner)?

**Comment by jommgoncalves** [comment] 2016-01-15 16:41
This is my version:

`You're on version v0.13.2
built on 2015-12-14`

How can I help you?

**Comment by agilliland** [comment] 2016-01-15 16:54
The main thing I need is clear steps to reproduce the problem.  I've just tried this a few times and I'm not running into any issues with it.

Anything else you can tell me about your environment would be helpful.  What kind of OS is docker running on?  What docker version?  What OS/version is your browser running on?  Have you made any other configuration choices when starting Metabase?

**Comment by jommgoncalves** [comment] 2016-01-15 17:16
Hum... I tryed in another browser (Firefox) and this problem not occurs. I think that the problem is the browser.

BTW, the version of the browser is `Version 49.0.2621.0 canary (64-bit)`. It can be canary version.

**Comment by agilliland** [comment] 2016-01-15 17:40
Yeah, looks like that's most likely the issue.  This is likely not something we are going to spend time on considering you're using a non-production build of Chrome.

**Comment by agilliland** [comment] 2016-01-18 18:30
I'm going to close this as "Won't Fix" due to the fact that it stems from usage of a non-production browser version.

**Closed by agilliland** 2016-01-18 18:30 UTC
Labels: wontfix

**Comment by jommgoncalves** [comment] 2016-01-21 18:04
Sorry my late answer, but this problem occurs in version `Version 47.0.2526.111 (64-bit)` too. Only in Firefox works fine.
