### ISSUE TITLE
ERROR metabase.sync.util Error fingerprinting table 60 'public.pg_buffercache'

### ISSUE THREAD

**Issue by etoulas** [metabase/metabase#15143] opened 2021-03-12 09:22 UTC
**Describe the bug**

While it looks like this is caused by missing permissions, I would like to understand the following:
- Does Metabase schema(?) sync rely on fingerprinting `pg_buffercache` in order to function correctly?
- If not, why is it trying to fingerprint this table?

**Logs**

```
ERROR metabase.sync.util Error fingerprinting table 60 'public.pg_buffercache'
org.postgresql.util.PSQLException: ERROR: permission denied for function pg_buffercache_pages
```

**Information about your Metabase Installation:**

- Your operating system: Debian
- Your databases: PostgreSQL 11.10
- Metabase version: 0.38.0.1
- Metabase hosting environment: Jar-file
- Metabase internal database: PostgreSQL 11.7

**Severity**
At the moment it looks like things still work as expected.

**Additional context**
We do have some sync issues with two tables that cannot be correctly fingerprinted because of a non-existing field (I filed a separate bug report #15144). I would like ant to understand if these issues are related to pg_buffercache.

EDIT: added potentially related bug report.

**Comment by flamber** [comment] 2021-03-12 10:04
Hi @etoulas 

I would guess that you have setup the database in Metabase with credentials, which has select privileges to `public.pg_buffercache` at some point, which means Metabase has synced the table, so that it is included in the scan and fingerprint processes.

If you run a manual sync again, then Metabase should set the table to `active=false`, which means it should not be included in scan or fingerprint anymore - Admin > Databases > (your postgres) > Sync database schema now.
And check the log for any errors during sync - Admin > Troubleshooting > Logs.

You might need to enable debug logging - JAR example:
`java -Dlog4j.configurationFile="https://log4j.us/v2/templates/metabase?trace=metabase.sync" -jar metabase.jar`

**Comment by etoulas** [comment] 2021-03-12 14:22
Hi @flamber,

I triggered the schema sync manually as you suggested. For the debug logging I will only be able to enable that on Monday.

The log shows that the sync finished, but raising exceptions for the tables in this and the other task.

I've attached the log from start to finish (other tables that are not the 3 with problems have been obfuscated).
[manual-db-schema-sync.log](https://github.com/metabase/metabase/files/6130255/manual-db-schema-sync.log)

I'm cannot judge if the issue you mentioned will solve the same problem.

**Comment by flamber** [comment] 2021-03-13 13:28
@etoulas I'm not quite sure what's going on in the log (very helpful by the way!), but it is not marking the column and table as `active=false`, which is definitely should do during the sync - and then they should not be included, when it does fingerprinting.
Hopefully the debug log could perhaps give more insights into what is going on.

Just want to make sure that you manually redacted the table names to just `public.table` like the following - otherwise that might indicate another problem:
`2021-03-12T14:00:34+01:00 INFO metabase.sync.sync-metadata.tables Aktualisiere Beschreibung für Tabellen: (Tabelle  'public.table' Tabelle  'public.table' Tabelle  'public.table' Tabelle  'public.table')`

And you (or someone else) haven't manually edited the Metabase metadata at any time - right? Just want to make sure, since I have not seen something like this before.

There should be something like this during the sync, which then means the fingerprint and scan would skip those:
`INFO sync-metadata.tables :: Marking tables as inactive: (Table  'public.pg_buffercache')`
`INFO fields.sync-instances :: Marking Field 'Table 337 'public.product_group' Field 'product_id'' as inactive.`
`INFO fields.sync-instances :: Marking Field 'Table 85 'public.product_service' Field 'product_service_id'' as inactive.`

Currently the only fix I can think of would be to manually mark the columns/tables, which shouldn't exist with `active=false`, but please do so after getting debug log - and make sure you have backups before changing the application database.

**Comment by dpsutton** [comment] 2021-06-10 16:41
Some investigation I've done:

In a native query on a pg instance i run `CREATE EXTENSION pg_buffercache;` and then i can execute 

```sql
SELECT n.nspname, c.relname, count(*) AS buffers
             FROM pg_buffercache b JOIN pg_class c
             ON b.relfilenode = pg_relation_filenode(c.oid) AND
                b.reldatabase IN (0, (SELECT oid FROM pg_database
                                      WHERE datname = current_database()))
             JOIN pg_namespace n ON n.oid = c.relnamespace
             GROUP BY n.nspname, c.relname
             ORDER BY 3 DESC
             LIMIT 10;
```

This causes the `describe-database` function to report the the view `pg_buffercache`

```clojure
(pprint (db-metadata (metabase.models.database/Database 6)))

#{{:name "pg_buffercache", :schema "public", :description nil}
  {:name "events", :schema "public", :description nil}
  {:name "wut2", :schema "public", :description nil}
  {:name "wut", :schema "public", :description nil}}
```

Syncing postgres again gives me logs:

```
sync-metadata.tables :: Found new tables: (Table  'public.pg_buffercache')
sync-metadata.tables :: Updating description for tables: (Table  'public.pg_buffercache')
```

This view seems to be synced just fine:
<img width="1524" alt="image" src="https://user-images.githubusercontent.com/6377293/121041704-98e3c900-c778-11eb-9390-9cb5c4abae08.png">

I execute `DROP EXTENSION pg_buffercache;` in the native query and resync seeing the following in the logs:

```
INFO sync-metadata.tables :: Marking tables as inactive: (Table  'public.pg_buffercache')
```

### NOTE
I am not advocating your drop the extension on your instance, I'm only recreating the view and then removing the view, and finding that the `pg_buffercache` view is no longer reported as an active table.

And the pg_buffercache view is no longer visible in the data model section of the Admin section of metabase.

## Your logs
I see
```
2021-03-12T14:00:32+01:00 INFO metabase.sync.util STARTING: Schritt 'sync-tables' für postgres Datenbank 2 'database2'
```
In your logs and nothing around that, so your database is still reporting that the view pg_buffercache exists

So this seems to be another instance of sync not seeing changes. I don't believe there is anything special about pg_buffercache other than metabase saw it once so it thinks its just another view. The mystery why sync is not marking it as no longer present is confusing.

**Comment by mazameli** [comment] 2022-05-06 19:17
@dpsutton should we mark this as `Couldn't Reproduce`?

**Comment by etoulas** [comment] 2023-12-12 09:40
@dpsutton I originally reported this issue. I don't have anymore access to the particular Metabase instance where I observed this issue. I suggest to close it as it got no upvotes whatsoever.

**Closed** 2024-02-13 08:07 UTC
Labels: Type:Bug, Priority:P2, Administration/Metadata & Sync, .Unable to Reproduce
