### ISSUE TITLE
Can't zoom in on custom expression rows

### ISSUE THREAD

**Issue by joevandyk** [metabase/metabase#6193] opened 2017-10-18 00:33 UTC
I have an aggregation using a custom expression called "Net Revenue $". When I zoom in using that expression, I see this error: http://take.ms/liahI ("No expression named 'Net Revenue $'")

**Comment by attekei** [comment] 2018-01-22 13:43
I couldn't reproduce the error on my own; @joevandyk does the problem still persist and could you provide step-by-step instructions for reproducing it?

What I saw is that you can try to sort by a custom expression in the table visualization (by clicking the custom expression header) although you're not supposed to be able to do that but that's not directly related to the error you were describing.

**Comment by mazameli** [comment] 2019-10-09 19:32
Can't reproduce this on master, so I'm closing this as fixed since it was opened two years ago and no one else seems to have run into it.

**Closed by mazameli** 2019-10-09 19:32 UTC
Labels: .Unable to Reproduce, Priority:P2, Querying/Simple, Type:Bug
