### ISSUE TITLE
Trend visualization does not show comparison for SQL questions with arbitrary date range

### ISSUE THREAD

**Issue by rthouvenin** [metabase/metabase#23385] opened 2022-06-16 14:13 UTC
**Describe the bug**
When a SQL question returns 2 dates that are not 7 days part or 1 month apart or 1 year apart, the trend visualization displays "Nothing to compare for the previous .":

![image](https://user-images.githubusercontent.com/7570541/174085745-8c94c2be-66ba-4086-9042-c55754fa131a.png)

**To Reproduce**
1. Create a SQL, with a query such as:
   ```
   SELECT CAST(created_at AS date) AS creation_date, SUM(total)
   FROM orders
   WHERE CAST(created_at AS date) IN ('2020-03-01', '2020-03-10')
   GROUP BY creation_date
   ```
3. Select Trend visualization

**Expected behavior**
Even if the elapsed time does not translate well as an English phrase, it should be possible to see the previous value and the percentage difference. For example "↓ 78% • was 992,59 previously"

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your databases: reproduced on MySQL and H2
- Metabase version: 0.42.3
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

**Severity**
Our reporting dashboard lets users enter any date range, and there a couple of questions that displays a Trend viz of a metric from beginning of date range to end of date range. Users cannot see the comparison unless they pick 2 dates that are 7 days apart or 1 month apart or 1 year apart.

**Comment by flamber** [comment] 2022-06-17 11:56
Quite sure it's a limitation of how the Trend code is implemented. Very related to #11200 and probably also #8919 and #13284.

Reproduce:
1. Native > Sample
```
select '2020-03-01'::date as "d", 992.59 as "v"
union all select '2020-03-10'::date, 1249.76
```
![image](https://user-images.githubusercontent.com/1447303/174292950-fca76113-7399-447e-9e4a-b26d94114186.png)
2. Saving and using Explore results, with Sum of V and grouped by D::Day will display `Nothing to compare for the previous day.`
![image](https://user-images.githubusercontent.com/1447303/174293199-6a83d0b7-2b04-48d2-9dea-d44a81075893.png)

**Comment by MartinCura** [comment] 2022-09-20 13:06
Hi, same problem here. 😞

After seeing UI editor only let me aggregate by very limited "day", "week" (which is from start of week to start of week), "month", etc., spent several hours making a custom query that transforms the date range filter into period delimiters (can share SQL if needed)... only to find that the question won't render any comparison if it doesn't fall into the same boxes. Also, even when selecting a week, if the data is not sorted by date ASC then it will show the wrong numbers.

Desired behaviour: just compare the last two numbers, and as label show "against previous period" or anything like that.


![image](https://user-images.githubusercontent.com/14017665/191265647-27d6cb97-39e5-456f-9d73-641479eb907c.png)

![image](https://user-images.githubusercontent.com/14017665/191265499-2df0f227-90ef-40ad-b8a5-27d45c43803d.png)

**Comment by prigal** [comment] 2022-10-24 14:16
Same problem here (v0.44.5)

Working : (month to date vs month -1) 
![image](https://user-images.githubusercontent.com/895267/197547281-28f45569-4ccd-419e-88d4-09d7f7c14f02.png)

Not workging (month to date vs month -2)
![image](https://user-images.githubusercontent.com/895267/197547504-b7f84feb-ce07-42af-bb18-08306acc369d.png)

_I'm not 100% sure but I think it was working few month ago with previous versions._

**Comment by yrostovskaya** [comment] 2023-05-18 13:31
Seems I found a solution.
You need to change the order of the columns.
<img width="1022" alt="Снимок экрана 2023-05-18 в 16 25 38" src="https://github.com/metabase/metabase/assets/90113422/b7ce8514-d3eb-48a7-a0de-cf7817b1c3f4">
<img width="960" alt="Снимок экрана 2023-05-18 в 16 26 27" src="https://github.com/metabase/metabase/assets/90113422/9d9cf01f-b41e-42c2-b3b8-4d3384220f70">

**Comment by Nortaniaan** [comment] 2023-07-20 16:56
The date column should have a specific pattern such as daily, weekly and so on. For example: if you have two dates - 19/07/2023 and 18/07/2023 then it gives you "X%. was Y last day " and if it was out of pattern, example 19/07/2023 and 17/07/2023 - it gives you "Nothing to compare for the previous"

**Comment by markbastian** [comment] 2024-01-22 20:19
@cdeweyx, I think this may be fixed. Attached are images from master using both @flamber's repro and a variant of the original. Attachments show both the dashboard and the emailed image -- which are consistent. Looks like now when the delta isn't a known unit, it just shows "vs. [Previous Date]".

<img width="531" alt="image" src="https://github.com/metabase/metabase/assets/8381441/46705cd6-bb98-47aa-92af-7095ea36d01b">

<img width="1026" alt="image" src="https://github.com/metabase/metabase/assets/8381441/1e0516e6-b51f-4c11-8a3d-86d102a5aa46">

Finally, I've attached an image from stats.
<img width="1026" alt="image" src="https://github.com/metabase/metabase/assets/8381441/ac4b3787-60b8-402c-90e8-2f8b92d6a8d0">

LMK if you think we're good to close as fixed.

**Comment by cdeweyx** [comment] 2024-01-23 00:09
> @cdeweyx, I think this may be fixed. Attached are images from master using both @flamber's repro and a variant of the original. Attachments show both the dashboard and the emailed image -- which are consistent. Looks like now when the delta isn't a known unit, it just shows "vs. [Previous Date]".
> 
> <img alt="image" width="531" src="https://private-user-images.githubusercontent.com/8381441/298710867-46705cd6-bb98-47aa-92af-7095ea36d01b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5Njg4NTUsIm5iZiI6MTcwNTk2ODU1NSwicGF0aCI6Ii84MzgxNDQxLzI5ODcxMDg2Ny00NjcwNWNkNi1iYjk4LTQ3YWEtOTJhZi03MDk1ZWEzNmQwMWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMDAwOTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGZkMTYxZDZkYTM3MTRmOWEwNGQ3Zjc5MWI3OTIyMzM4NmJiZGRmMmQ4NmFhNDJiZDE4NGNkZDI4ZDI4ZGU2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BMfsxSuyoz4XuUFI_X_HmiWFOWMnRgriY880LeBgdNc"> <img alt="image" width="1026" src="https://private-user-images.githubusercontent.com/8381441/298710914-1e0516e6-b51f-4c11-8a3d-86d102a5aa46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5Njg4NTUsIm5iZiI6MTcwNTk2ODU1NSwicGF0aCI6Ii84MzgxNDQxLzI5ODcxMDkxNC0xZTA1MTZlNi1iNTFmLTRjMTEtOGEzZC04NmQxMDJhNWFhNDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMDAwOTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzZlMmFmOWE1ZmI3MjBiNjg2YWRkZjIyYzZmOGRlNWExZTcwNTIxYTNiMGE4MmVhZTBkNzc4ZDBjNTVmN2EyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OiyaUbKVFHExTdyUDnZZ4Dm6mt99pLofWmVLVo5VqDw">
> Finally, I've attached an image from stats. <img alt="image" width="1026" src="https://private-user-images.githubusercontent.com/8381441/298711165-ac4b3787-60b8-402c-90e8-2f8b92d6a8d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5Njg4NTUsIm5iZiI6MTcwNTk2ODU1NSwicGF0aCI6Ii84MzgxNDQxLzI5ODcxMTE2NS1hYzRiMzc4Ny02MGI4LTQwMmMtOTBlOC0yZjhiOTJkNmE4ZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMDAwOTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmU0OTUzZTAzZWEyY2Q0MDgwMjA2ODYxNTM1ZDA1NGIwNzY5YjUwZjAzNDU1NTVjNzE4MWY4ZTUzNjRmZWQwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DJ9Mp5fZuHL0dR6qgFLNApAlhqymjUQOkSFEbM0Wpy4">
> 
> LMK if you think we're good to close as fixed.

Yep that's right — Closing as fixed.

**Closed** 2024-01-23 00:10 UTC
Labels: Type:Bug, Priority:P2, Querying/Native, Visualization/Scalars, .Team/DashViz
