### ISSUE TITLE
Preselect filter values for questions on dashboards

### ISSUE THREAD

**Issue by nickcarenza** [metabase/metabase#11077] opened 2019-10-07 20:11 UTC
I would like to be able to use a question multiple times on the same dashboard but with different pre-selected filter values. When I add a question to a dashboard I would like to have the option to choose values for any filters declared in the question.

Currently, I either have to create copies of the question with hardcoded values instead of filters or create duplicate filters on the dashboard that link to different copies of the question. Having copies of questions with different hardcoded values is not ideal because then maintenance becomes too difficult. Having multiple filters on the dashboard is not ideal because they aren't really meant to be changed once set.

Thanks Metabase team!

**Comment by nickcarenza** [comment] 2019-10-07 20:17
Another reasonable solution would be to have filters physically placed anywhere on the dashboard so it's clear which questions they link to. This would enable dynamic comparisons of

**Comment by flamber** [comment] 2019-10-07 20:42
Hi @nickcarenza 
It sounds like a duplicate of #3575 - if you agree, then please close this issue :+1:

**Closed** 2019-10-08 23:09 UTC
Labels: Type:New Feature
