### ISSUE TITLE
Question filter abnormally changed (v 0.44.0)

### ISSUE THREAD

**Issue by duongnt18** [metabase/metabase#24802] opened 2022-08-16 02:30 UTC
**Describe the bug**
In the question have more than 2 filter, when the filter are changed their value, another filter are changed the same.

**To Reproduce**
1. This error was run in chrome.
2. Create the question with 2 tables and with more than 2 filter 
3. Change value of 1 filter

https://user-images.githubusercontent.com/19161026/184785494-d83197ac-782c-4316-aaa1-160269d6cb3e.mp4

Thanks team,
Duong Nguyen

**Comment by flamber** [comment] 2022-08-16 07:41
Duplicate of #24664

**Closed by flamber** 2022-08-16 07:41 UTC
Labels: Type:Bug, .Needs Triage
