### ISSUE TITLE
Bind date range edges to exact date filters of questions on dashboards

### ISSUE THREAD

**Issue by AndrewDryga** [metabase/metabase#20457] opened 2022-02-11 18:39 UTC
I feel like this would be a great addition for Metabase which will simplify a lot of more complex use cases.

Eg. we have a question that exposes two variables: `{{start_date}}` and `{{end_date}}` (field filter won't work because queries are more complex and filter is reused on different fields at the same time). Then by having a Date Range filter with relative value "This Month" we can bind its beginning of range to `{{start_date}}` and end of it to `{{end_date}}`.

So on the dashboard default value would be relative, SQL queries don't care if the date is relative, pulses work just perfect and there is no filters pollution on the dashboard (no need to re-expose `{{start_date}}` and `{{end_date}}` separately and then link them to prevent date overlaps).

This also partially solves the requested feature of having a relative date on a date field.

**Comment by flamber** [comment] 2022-02-11 18:52
Duplicate of #4509/#4083

**Closed by flamber** 2022-02-11 18:52 UTC
Labels: .Epic
