### ISSUE TITLE
In lastest version 0.35.4, The datetime format in Japanese cannot show in the chart correctly.

### ISSUE THREAD

**Issue by SwiftTT18** [metabase/metabase#12704] opened 2020-06-15 12:45 UTC
**Describe the bug**
In lastest version 0.35.4,
The datetime format in Japanese cannot show in the chart correctly.
It still show in the english way even though you choose the Japanese datetime format.

**Logs**

metabase log:
[2e2c6a78-40aa-4627-a094-000824e7e509] 2020-06-15T21:02:02+09:00 DEBUG metabase.middleware.log POST /api/dataset 202 [ASYNC: completed] 84.9 ms (9 DB calls) App DB connections: 1/10 Jetty threads: 2/50 (4 idle, 0 queued) (118 total active threads) Queries in flight: 0 (0 queued)

javascript console:
Uncaught TypeError: Cannot read property 'card' of undefined
    at P (app-main.bundle.js?31778b9e3b01ff7193ac:5)
    at Object.series (app-main.bundle.js?31778b9e3b01ff7193ac:5)
    at y (app-main.bundle.js?31778b9e3b01ff7193ac:5)
    at SVGPathElement.<anonymous> (app-main.bundle.js?31778b9e3b01ff7193ac:5)
    at SVGPathElement.__onmousemove (vendor.bundle.js?31778b9e3b01ff7193ac:1)
4vendor.bundle.js?31778b9e3b01ff7193ac:1 Uncaught Invariant Violation: Minified React error #44; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=44 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at e.exports (http://ec2-52-196-86-120.ap-northeast-1.compute.amazonaws.com/app/dist/vendor.bundle.js?31778b9e3b01ff7193ac:1:291123)
    at Object.e.exports [as findDOMNode] (http://ec2-52-196-86-120.ap-northeast-1.compute.amazonaws.com/app/dist/vendor.bundle.js?31778b9e3b01ff7193ac:1:2525765)
    at d.value (http://ec2-52-196-86-120.ap-northeast-1.compute.amazonaws.com/app/dist/app-main.bundle.js?31778b9e3b01ff7193ac:5:215521)
    at n._updateSize (http://ec2-52-196-86-120.ap-northeast-1.compute.amazonaws.com/app/dist/app-main.bundle.js?31778b9e3b01ff7193ac:5:214948)

**To Reproduce**

1. Open a dashboard
2. Click the '設定'(option?) bottom 
3. Click the 'データ'(data) tag
4. Click the option icon on the right of 'X軸' (x-axis)
5. Choose the '1月7, 2018' in the '日付の形式' 's list
6. The chart's X-axis still show in 'May 24, 2020'. It cannot show in the correct japanese format

**Expected behavior**
the chart X-axis can show in the correct japanese datetime format

**Screenshots**
![image-2020-06-08-10-54-14-654](https://user-images.githubusercontent.com/49319903/84658844-764a1600-af51-11ea-9553-462ba7ed9f48.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 83.0.4103.97 (Official Build)
- Your operating system: OS X 10.15.5
- Your databases: Amazon Redshift
- Metabase version: 0.35.4
- Metabase hosting environment: docker image

**Severity**
Some of our clients and manager level staff don't understand english. It is annoying and even a little bit rude (due to the Japanese business culture)  when we show boss the chart in english.

We know that is just a small issue, but still sincerely hope that the Metabase team could fix it.

For using Metabase for a quite long time, we really appreciate it that you guys create a fantastic BI software for the world.

**Comment by flamber** [comment] 2020-06-15 12:47
Duplicate of #11319

**Closed by flamber** 2020-06-15 12:47 UTC
Labels: .Needs Triage, Type:Bug
