### ISSUE TITLE
Onclick behaviour on Pivot Table visualization

### ISSUE THREAD

**Issue by omkar1610** [metabase/metabase#18888] opened 2021-11-08 07:53 UTC
**Describe the bug**
I want to add on click behaviour to cells of a pivot table. When I am accessing the column name and row name of a corresponding cell it's not getting the correct value

**Example Table**
| r1 | c1 | 1 |
|----|----|---|
| r1 | c2 | 2 |
| r2 | c1 | 4 |
| r2 | c2 | 5 |

**Visualization on  dashboard**
|    | c1 | c2 |  
|----|----|----|
| r1 | 1  | 2  |   | 
| r2 | 4  | 5  | 

**What is happening currently on click pivot table**
1 and 2 both gets 1st row in table i.e r1,c1,1
4 and 5 both gets 2nd row i.e r1, c2, 2

**Expected behaviour**
1 should get r1,c1,1
2 should get r1,c2,2
4 should get r2,c1,4
5 should get r2,c2,5

**Comment by flamber** [comment] 2021-11-08 08:38
Duplicate of #17920

**Closed by flamber** 2021-11-08 08:38 UTC
Labels: Type:Bug, .Needs Triage

**Comment by omkar-work** [comment] 2021-11-08 11:53
@flamber It's not a duplicate. I am taking about the pivot table option inside table visualisation.
You have merged it with custom question pivot table
![image](https://user-images.githubusercontent.com/86356654/140737491-10b3cc9d-5703-4233-8554-9e94ae36c103.png)

**Comment by flamber** [comment] 2021-11-08 11:57
@omkar-work 
Yes, it's a duplicate of that issue, which is specific about the old "Pivot the table" in Table, not Pivot Table visualization.
But post "Diagnostic Info" from Admin > Troubleshooting, as requested when opening an issue. If you are not using the latest release, then upgrade: https://github.com/metabase/metabase/releases/latest
