### ISSUE TITLE
Why are underscores replaced with spaces even when Friendly Table and Field Names is disabled?

### ISSUE THREAD

**Issue by aagarwal-gtr** [metabase/metabase#3948] opened 2016-12-14 08:39 UTC
I disabled 'friendly tables and field names' from the admin panel but i am still not getting them in the actual raw format.
eg: the field name is total_notxxxx and now its showing up as 'Total Notxxxx' i want it to show up as it is.
is this intentional? why?

from the logs i can see a whole bunch of these:
`Dec 14 08:01:35 INFO metabase.models.humanization :: Updating display name for Field 'total_notxxxx': 'Total Not Xxxx' -> 'Total Notxxxx'`

Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Chrome Version 54.0.2840.71 (64-bit)
Your operating system: (e.x. OS X 10, Windows XP, etc)
Ubuntu 15.04
Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Postgres
Metabase version: (e.x. 0.19.3)
v0.20.3
Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Docker
Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
H2

**Comment by camsaul** [comment] 2017-01-09 17:46
@salsakran @aagarwal-gtr this isn't a bug, this intentional behavior.

If you enable "Friendly Table and Field Names" it attempts to break them out into different words. If you disable it it falls back to our old behavior which is just replacing underscores with spaces.

@aagarwal-gtr what is the reason you *wouldn't* want `total_notxxxx` to show up as `Total Notxxxx`?

**Comment by aagarwal-gtr** [comment] 2017-01-10 04:26
@camsaul because it screws up with my own chosen accepted naming conventions. camelCase becomes CamelCase. i want to be able to default to actuals. also if i download the csv the column names will show up as post metabase processed not actuals so if i need to reuse the raw data externally it causes confusion because of unstandardization.

**Comment by orware** [comment] 2017-02-11 00:23
This is annoying to me as well.

For our Oracle database the table naming convention is pretty well set so the rewriting that's occurring here for us is making the product almost unusable because it throws people off from what they're used to seeing in Oracle's tools.

We are expecting a consistent casing scheme (for Oracle, this is generally all uppercase letters for the tables and field names and no spaces or mixed cases, that's just weird for us, though I wouldn't mind having it be all lowercase either).

The table searching is a bit weird too because there should be a table for example named "GOBTPAC" but I was only able to find it with some other prefix "GV_GOBTPAC" yet in our database metadata, while I'm able to query both (meaning perhaps there's an alias out there with this other name), the actual table name should still be GOBTPAC. Plus seeing the field name "Gobtpac Usage Accept Ind" is quite a bit different than the original "GOBTPAC_USAGE_ACCEPT_IND". A feature to strip out the table name from the beginning of the field names might be a potentially useful feature (to save some space when displaying data in tabular format) but that would probably be all that would be needed for the types of tables that we see.

Also, in our database there are quite a few comment descriptions for tables present in this Oracle system table which might be useful to automatically bring in for tables that have them:
select * from all_tab_comments where comments is not null;

The table above has a comment for it like this: "Third Party Access Table" that might be useful to include in the metadata information collected by the software.

Also, when turning the Friendly Table Names off, it kicks off the process immediately and kind of hangs the UI if there are a lot of tables to process (which is the case for us) so it might be nice to allow for the setting to get toggled off and a notification get shown that says the process is being run in the background (similar to what's being done for the Sync step).

I also had to increase our Java memory size to about 4 GB to allow for the initial sync from our database to complete successfully (the Ellucian Banner SIS program used by colleges/universities has a lot of tables...I think it was close to 7000 when I was doing some digging into the metadata the other week).

**Comment by camsaul** [comment] 2017-02-11 00:32
@orware we have an open issue to use table and column remarks as descriptions where applicable: #3089

**Comment by camsaul** [comment] 2017-02-11 00:34
@orware, are you prefixing all of your fields with the name of the table they're in? e.g. you have a table named `GOBTPAC` and it has a field named `GOBTPAC_USAGE_ACCEPT_IND`?

**Comment by camsaul** [comment] 2017-02-11 00:37
That is a good point RE: setting toggling the value of Friendlier Table Names. @tlrobinson sounds like we should be making that API call asynchronously instead of synchronously. That's what we should do in most cases I think. People might be on a high-latency spotty wifi connection or something like that. IDK, maybe I am just scarred from my dark past as former mobile developer

**Comment by camsaul** [comment] 2017-02-11 00:42
Or I guess maybe I could just tackle all the renaming on a background thread. That might make more sense, but either way we should try to never block the UI waiting for an API request to complete because network connections are finicky. Especially if we want to further develop the plot of our mobile story (?) because mobile connects are hashtag finicky

**Comment by orware** [comment] 2017-02-11 00:44
@camsaul Ellucian seems to have prefixed most field names by the table name, though that's not 100% consistent in every single location, but it's a general enough rule that if it was an option to be turned on it could be implemented simply by having a visual filter to just replace the "#TABLENAME#_" prefix in field names with nothing when detected.

**Comment by orware** [comment] 2017-02-11 00:51
Also, when trying to create a question, I'm having a difficult time finding table names (which is partly due to the issues described above with the naming), but also because most of the tables are within different Oracle Database Schemas. In Oracle, there's a Database Instance and within it are multiple schemas with the tables inside of them. But also in Oracle, every Database User gets their own schema so there's a lot of noise at this initial sublevel and one would have to know which schema to go into in order to try and even find a table. It would be nice if the search at this level would allow searching by table name as well and either help you filter the list of schemas to the one containing the table name or simply take you straight to where the table is located might be nice. Also, including a count of tables in a schema right there when creating a question could potentially be a useful visual cue (generally most of our queries are going to be against the schemas with the larger amounts of tables).

If helpful, I can provide a copy of the metabase MySQL database tables somewhere which might be helpful for testing since you guys might not have a similar dataset already available?

**Comment by orware** [comment] 2017-02-11 00:58
@camsaul I'm not sure if the whole database would be needed, but I can likely provide the raw_column / raw_table tables to you guys securely if that would be helpful at all for testing purposes.

Our raw_column count is a little over 143,000 and our raw_table count is a little over 8,000 at the moment for reference.

**Comment by orware** [comment] 2017-02-11 01:04
To play on this a little more, I just did some additional checking within our Metabase database and it seems here I was looking into the wrong schema and when I switched to the more "correct" one I was able to reference things a little more easily by the table names I was used to (I guess the "BANINST1" schema in our database has that GV_GOBTPAC table, which seemed to have the same contents of the "GENERAL" schema's GOBTPAC table...why I'm not really sure but there's lot of hidden nooks and crannies in our database just waiting to be discovered and understood better).

**Comment by tlrobinson** [comment] 2017-02-12 17:28
@camsaul The frontend only uses async requests. The saving indicator will spin until the request returns but it shouldn't actually block any additional UI actions. @orware what aspect of the UI hangs?

**Comment by orware** [comment] 2017-02-12 21:12
@tlrobinson What I observed from the web UI was that when I toggled the Friendly Names option in the Settings area and the toggle didn't seem to do anything.

However, since I had been noticing that the command line prompt where I had started the metabase.jar file from seemed to be capturing quite of bit of log activity (which had given me an indication of where the database sync was when I had initially synced up our campus database to metabase earlier in the day) I switched back over to the server to see if something was going on, and I could see a bunch of log output showing that tables were getting renamed in the background, however from the web UI it wasn't hanging per se, but the Friendly Names toggle didn't switch to "off" the way I expected it to, and that may have been because while it kicked off the async request, the web UI was still waiting for the result of that request before the toggle could be switched off.

It took several minutes though before that renaming process completed so my main suggestion there was that having something more like the "sync" option for databases might be more appropriate in this case since the web UI gave a clear indicator that, "Hey, this might take a while so it's happening in the background" while it didn't do that for the Friendly Names toggle option.

Also, while I was checking out the Admin UI I was wondering if there was any way to see a log of recent activity in the system and that didn't seem to be available (so for example the output I was seeing from the command line didn't seem to be visible anywhere in the web UI, which might be useful for administrators of the software to see more easily...particularly once I try and set this up as a service on the Windows Server I spun up in our local environment, I'm not really going to be able to easily see that log output anymore). And other activity such as user logins and stuff like that might also be useful for admins to be able to check out if needed :-).

**Comment by burdiyan** [comment] 2017-02-20 10:03
It would be really great to be able to see raw table and field names!

**Comment by justin-yan** [comment] 2017-04-21 17:13
Just to chime in - there is definitely some confusion for our internal users in understanding the metabase renaming pattern (for example, starting in the data explorer, and then switching to the SQL view - why are the names different?).  In general, for us, it's not exactly a major problem (people get it after a bit), but we largely don't perceive the "prettification" to be worth the (admittedly minor) confusion that results from not having identical names.

Don't expect it to be default, but it would be nice to have a toggle to be able to disable this behavior.

**Comment by elburro1887** [comment] 2017-05-03 09:05
I must also agree that this is not helpful at all, in spite of the effort.

 For my database, the friendly names result in a confusing splitting up of the names (see screenshots) and I wasn't sure at first what was going on here. BTW, my table names are in German, so maybe that's the reason, but to be honest, this feature confuses users more than helps them.

In my opinion, the names should be left as they are by default, and only enabled upon asking and warning the user.

Also, the option to disable/enable this feature should be much more visible and not buried in the last row of the "General" settings. Maybe add a "Database" settings category?

![metabase1](https://cloud.githubusercontent.com/assets/13376225/25654033/da38f620-2fef-11e7-8f42-33808f26dddf.png)

**Comment by doodlebro** [comment] 2017-05-12 16:46
Is there a planned resolution for this issue? The discussion above tells me that this feature needs polishing.

**Comment by doodlebro** [comment] 2017-05-15 20:10
@camsaul: Nuked my metabase instance and reconnected to our database with the option disabled. It would appear that metabase uses friendly table and field names regardless of what the admins have chosen for this option.

Anything I can do so that actual table/field names are being used?

**Comment by camsaul** [comment] 2017-05-15 20:18
@doodlebro if you disable friendly table & field names it still replaces underscores with spaces but doesn't attempt to break words apart based on an English dictionary

**Comment by doodlebro** [comment] 2017-05-15 20:37
@camsaul Probably should update the description string for this setting then?

Currently it reads: "Metabase can attempt to transform your table and field names into more sensible, human-readable versions, e.g. "somehorriblename" becomes "Some Horrible Name". This doesn’t work all that well if the names are in a language other than English, however. Do you want us to take a guess?"

It is not obvious that replacing underscores with spaces is "intended behavior." Quite confusing at the moment.

**Comment by doodlebro** [comment] 2017-05-15 20:38
Moreover... Why not allow the admins an _option_ to decide whether they want underscores replaced?

**Comment by jackolicious** [comment] 2017-10-12 00:40
Please please please... turning off friendly field names should turn off friendly field names. End of story. If I want to make them friendly, I can turn that on or manually configure the display names in the data model configs.

It makes query writing a huge pain.
It makes understanding tables a huge pain. 
It makes our internal data seem inconsistent.

**Comment by adjenks** [comment] 2017-11-02 21:46
@jackolicious Amen!

**Comment by zikegcwk** [comment] 2017-11-03 23:21
Is there anyone looking at this? It seems to be a huge pain.

**Comment by zikegcwk** [comment] 2017-11-03 23:47
just solved this - you can just get connected to the metabase metadata db, and then set all the metabase_table.display_name = metabase_table.name. Do the same for field and you should be all good.

**Comment by gbard** [comment] 2018-01-10 01:26
@zikegcwk can you provide more details? I connected to metabase H2 database but can't find anything like what you are mentioning...

**Comment by doodlebro** [comment] 2018-01-10 20:29
@gbard: You will want to run this SQL in order to update the display names to be based on the actual table name:

UPDATE metabase_table SET display_name = name;

This statement effectively fixes the bug.

**Comment by charlesread** [comment] 2019-05-22 19:54
> This is annoying to me as well.
> 
> For our Oracle database the table naming convention is pretty well set so the rewriting that's occurring here for us is making the product almost unusable because it throws people off from what they're used to seeing in Oracle's tools.
> 
> We are expecting a consistent casing scheme (for Oracle, this is generally all uppercase letters for the tables and field names and no spaces or mixed cases, that's just weird for us, though I wouldn't mind having it be all lowercase either).
> 
> The table searching is a bit weird too because there should be a table for example named "GOBTPAC" but I was only able to find it with some other prefix "GV_GOBTPAC" yet in our database metadata, while I'm able to query both (meaning perhaps there's an alias out there with this other name), the actual table name should still be GOBTPAC. Plus seeing the field name "Gobtpac Usage Accept Ind" is quite a bit different than the original "GOBTPAC_USAGE_ACCEPT_IND". A feature to strip out the table name from the beginning of the field names might be a potentially useful feature (to save some space when displaying data in tabular format) but that would probably be all that would be needed for the types of tables that we see.
> 
> Also, in our database there are quite a few comment descriptions for tables present in this Oracle system table which might be useful to automatically bring in for tables that have them:
> select * from all_tab_comments where comments is not null;
> 
> The table above has a comment for it like this: "Third Party Access Table" that might be useful to include in the metadata information collected by the software.
> 
> Also, when turning the Friendly Table Names off, it kicks off the process immediately and kind of hangs the UI if there are a lot of tables to process (which is the case for us) so it might be nice to allow for the setting to get toggled off and a notification get shown that says the process is being run in the background (similar to what's being done for the Sync step).
> 
> I also had to increase our Java memory size to about 4 GB to allow for the initial sync from our database to complete successfully (the Ellucian Banner SIS program used by colleges/universities has a lot of tables...I think it was close to 7000 when I was doing some digging into the metadata the other week).

Hooking up to Banner, eh?  Me too ;)

**Comment by orware** [comment] 2019-05-22 20:09
@charlesread That's right :-)! Actually didn't realize something had been merged regarding this already going to have to try it out (I had been using the manual updates to the DB suggested above though once I learned about that option).

**Comment by mazameli** [comment] 2019-09-24 21:22
Fixed over a year ago by https://github.com/metabase/metabase/pull/6708

**Closed by mazameli** 2019-09-24 21:22 UTC
Labels: Metadata/Sync, Type:Question
