### ISSUE TITLE
No formatting setting visible for a sum of values of float8 type

### ISSUE THREAD

**Issue by papermechanics** [metabase/metabase#33430] opened 2023-08-23 09:04 UTC
### Describe the bug

![image](https://github.com/metabase/metabase/assets/47104789/dce7f23d-e0d2-4b77-8bbf-ca6c61073cc4)
The settings menu is not visible for the sum of the amount (float8 type, Postgres). None of the values in the table have more than 2 decimal places, even so, it sums them up to extended precision and does not let me truncate or format decimal point in any kind of way.points

### To Reproduce

1. Make a question that calculates the sum of values of a column of float8 type.
2.  Click on the settings icon to enter formating settings.
formatting

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8",
    "os.name": "Linux",
    "os.version": "5.19.0-1025-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-08-16",
      "tag": "v0.47.0",
      "branch": "release-x.47.x",
      "hash": "682ec2d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Urgent

**Comment by paoliniluis** [comment] 2023-08-23 10:06
What’s the semantic type in Metabase? Go to settings-> admin-> metadata

**Comment by papermechanics** [comment] 2023-08-23 10:12
Semantic Type is Currency in Indian Rupees.

**Comment by papermechanics** [comment] 2023-09-27 06:46
Any updates on this issue?

**Comment by papermechanics** [comment] 2023-11-27 05:31
Any updates on the issue??

**Comment by adam-james-v** [comment] 2023-12-21 17:09
I am unable to reproduce this bug. These are the steps I've taken:

In Posgres, I first created a table with a float8 column:

```sql
CREATE TABLE my_table (A float8);
```

And then created some random entries, all of which have only 2 decimal places:

```sql
INSERT INTO my_table (A)
SELECT trunc(random() * 100000) / 1000
FROM generate_series(1, 50000);
```

Creating a question that sums this Column gives me:

<img width="702" alt="image" src="https://github.com/metabase/metabase/assets/21064735/3a08a187-556d-4c79-acfe-64fe96388a02">

**Comment by markbastian** [comment] 2023-12-21 17:41
Here is a similar attempt. Formatting results seem to apply correctly both in the app and to the downloads.
![33430](https://github.com/metabase/metabase/assets/8381441/5f0e3262-c525-42ba-9829-024a1ec4ba38)

**Comment by paoliniluis** [comment] 2023-12-22 21:22
same, I created 

![Image](https://github.com/metabase/metabase/assets/1711649/35443a1b-decd-448f-9e18-51ec3a2cdd9b)

and can't see the issue in v48. Closing

**Closed by paoliniluis** 2023-12-22 21:22 UTC
Labels: Type:Bug, Priority:P2, Visualization/Chart Settings, .Team/PixelPolice (DEPRECATED)
