### ISSUE TITLE
[BUG] Column order in saved question resets after a column(s) is removed from database table

### ISSUE THREAD

**Issue by mvrabel** [metabase/metabase#7884] opened 2018-06-14 16:49 UTC
If a column is deleted from a table then the **ORDER OF ALL COLUMNS IN ALL QUESTIONS created from this table will reset** to default alphabetic order.

Example/Reproducible steps:

1. Create table:

```
CREATE TABLE test_7884 ( 
	id                   int   NOT NULL,
	col_a                text  NOT NULL,
	col_b                text  NOT NULL,
	col_c                text  NOT NULL,
	CONSTRAINT pk_test_table_id PRIMARY KEY ( id )
 );
```
![test_table](https://user-images.githubusercontent.com/12628893/41425804-149d8fc6-7002-11e8-8b2f-c73dcc171450.PNG)

2. Insert some Data 

`INSERT INTO test_7884 ( col_a, col_b, col_c) VALUES ( 1, 'A', 'B', 'C' );`

3. Reorder data in Metabase. (By default the columns will be sorted alphabetically with the single exception of PK column i.e. the default order is Id, col_a, col_b, col_c )
![metabase_test_table](https://user-images.githubusercontent.com/12628893/41425837-275b14a8-7002-11e8-9227-d603d865316c.PNG)

4. Remove column col_c (or any column) from the table
`ALTER TABLE test_7884 DROP COLUMN col_c;`
![metabase_test_table_c_not_exists](https://user-images.githubusercontent.com/12628893/41425844-2b63cb8a-7002-11e8-9cd2-9ce50ee68beb.PNG)

5. Sync database in admin menu and view the question. 
![metabase_test_table_reordered](https://user-images.githubusercontent.com/12628893/41425847-2e83fca4-7002-11e8-82cc-a5a91aefcd37.PNG)

You can see that the order is now Id, col_a, col_b **instead of the expected** Id, col_a, col_b.
This is a big problem when you have dozens of reports created from one table. (As we do).

Nonetheless thanks for the awesome work Metabase team! 👍 ,
Martin

- Browser: Chrome 67.0.3396.79 (64bit)
- Operating system: Windows 10
- Database: Postgres 9.6
- Metabase version: 0.29.3
- Metabase hosting environment: CentOS7
- Metabase internal database: H2 (default)

Thanks for being part of the Metabase project!
-------

**Comment by flamber** [comment] 2019-02-22 01:00
Hi @mvrabel 
I can reproduce until step 5, because after removing and sync'ing, then step 5 still throws the error.
I'm not quite sure it's related, but the behavior is similar to #8185

**Comment by mvrabel** [comment] 2019-02-25 08:32
@flamber thanks for looking into this.
Maybe this was resolved in in never version. I'm no longer on the project where we used metabase :)
I'll ask my colleague to leave a comment

**Comment by sbelak** [comment] 2020-07-02 08:29
Closing since as of #12559 we have a robust mechanism for ordering fields both in results and data model.

**Comment by flamber** [comment] 2020-07-02 09:11
This is not a Data Model issue, but how question metadata is stored. I can reproduce on `master` and get this error in step 4:
`Unknown column 'test_7884.col_c' in 'field list'`
![image](https://user-images.githubusercontent.com/1447303/86339265-aaad1a00-bc53-11ea-8f04-2d69e6f5e5cd.png)

And then to recover the question to a working condition, I have to go to Notebook editor and click the table Columns, where the "Select All" is only half-checked:
![image](https://user-images.githubusercontent.com/1447303/86338983-51dd8180-bc53-11ea-8408-1965e915c2c2.png)

And click "Select All" to make it fully checked and Visualize:
![image](https://user-images.githubusercontent.com/1447303/86339115-80f3f300-bc53-11ea-9029-41ac8c252a73.png)
![image](https://user-images.githubusercontent.com/1447303/86339374-cdd7c980-bc53-11ea-933a-42aed2255076.png)

Related to #7612

**Comment by npretto** [comment] 2023-11-08 13:54
Couldn't get a version from 2018 to run, but I reproduced this on master.

@npfitz is it possible that this is caused by `isInvalid` triggering `getDefault` in vis settings?

**Comment by bshepherdson** [comment] 2024-02-09 16:01
## On topic

Typically the BE does not migrate existing questions or cards proactively on any change, since it typically requires loading every question and rewriting some of them (or none). On the other hand, there are several kinds of normalization or cleanup it performs on loading things, eg. modernizing aging MBQL into the latest form. These are applied dynamically on loading an entity and not written back unless eg. the question is saved again.

I think it would be straightforward for the BE to determine on loading a card that its `table.columns` contains a reference that is no longer valid and simply to drop it, so the FE receives a plausible viz-settings. That solves this bug, I think.


## Rant

I think it's worth mentioning that this touches on a real gnarly can of worms, without good solutions for many of the issues.

As one example: field `name`s are unique on a query. If there are several names that overlap, we use either join aliases (`Reviews__ID`) or arbitrary numbering (`ID_2`) to make the `name`s unique. But since both of those renamings are based on something arbitrary (user-defined join aliases, or column order), it's possible to make two columns "swap labels", so they get each others' viz settings: change the aliases of two joins so one gets the other's alias, or reorder two join clauses inside a model so that the `ID_2` and `ID_3` are applied to different columns.

Of course those edits are a bit contrived. But since all we see in practice is two sets of column names without any context for what has changed in user schema, query, or both, we're reduced to guessing how to map the existing viz settings to the changed query.

**Comment by bshepherdson** [comment] 2024-02-09 18:23
I'm looking into how the BE works with this data.

[`metabase.query-processor.streaming/validate-table-columns`](https://github.com/metabase/metabase/blob/master/src/metabase/query_processor/streaming.clj#L41) does this validation in the QP, checking that all the specified `table.columns` are found on the query. If they're not, it scraps the entire `table.columns` list and synthesizes a new one. That new one is based on the order of columns in the generated SQL I think.

I don't know whether this order (which I think determines the order of `data.cols` in the network response) is what the FE uses, or if it does its own reordering based on the card's `visualization_settings`.

**Comment by darksciencebase** [comment] 2024-06-26 07:58
@ranquild if this is a frontend issue, should it be `.Team/QueryingComponents`?

**Comment by calherries** [comment] 2024-07-12 00:44
@ranquild is right, this is FE and definitely not related to sync.

**Closed** 2024-07-12 22:21 UTC
Labels: Type:Bug, Priority:P2, Visualization/Chart Settings, .Frontend, Querying/GUI, .Team/QueryingComponents
