### ISSUE TITLE
Custom geojson map issues on 0.31

### ISSUE THREAD

**Issue by lp-lima** [metabase/metabase#9125] opened 2018-12-13 19:47 UTC
Hi there, guys! My custom maps region names are not being show properly on 0.31 - they were fine at 0.29. 

Check images below:

![image](https://user-images.githubusercontent.com/22321989/49963142-54a44480-fefe-11e8-9090-5323a61f6e59.png)

The field name is displaying correctly, so, the geojson has a field name set.

This is the preview of the question, when I choose which fields is Metabase supposed to associate with the saved map:

![image](https://user-images.githubusercontent.com/22321989/49963160-61289d00-fefe-11e8-930f-46b41d5b2d36.png)

When I save the question, though, not even the ID is being displayed when I hover the mouse over:
![image](https://user-images.githubusercontent.com/22321989/49963181-6ab20500-fefe-11e8-82cc-a3f87e9c6cf5.png)

It was working so well previously, but now I can barely get some information out of the map without having to click on some region and dive into it (leaving the map page as a consequence).

I’m on Chrome, Windows 10, and my Metabase instance is running on a Debian on Amazon EC2.
The GeoJSON file: https://raw.githubusercontent.com/tbrugz/geodata-br/master/geojson/geojs-35-mun.json 1

Steps to reproduce:
1 - configure the GeoJson map from the source above on your metabase instance, and set fields accordingly (id and name);
2 - Run a question with this query in any MySQL database (or a similar query in any other), just to generate the question and show the map. You will see that hovering the mouse over the map, in the question results screen, has no effect on it:

“SELECT 1100015 as id, 13 as count”

I created a [post ](https://discourse.metabase.com/t/custom-geojson-map-issues-on-0-31/5042) a few days ago, but got no reply so far, so I found proper to file an issue here.

-  Browser: 71.0.3578.80 (Official version) 64 bits
- OS: Windows 10
- Databases: MySQL
- Metabase version: 0.31.0
- Metabase hosting environment: Amazon EC2, running via jar file
- Metabase internal database: H2 (default)

**Comment by salsakran** [comment] 2018-12-28 02:01
dupe of #8986 (which is marked as a P1, so not closing this because we don't care :)

**Closed by salsakran** 2018-12-28 02:01 UTC

**Comment by lp-lima** [comment] 2018-12-28 05:40
> dupe of #8986 (which is marked as a P1, so not closing this because we don't care :)

I hope that is the same, because, in his case, he can see something when hovering the mouse over. For me, not even that... although, solving one issue will fit both, most likely
