### ISSUE TITLE
Dashboards Permissions for specific User

### ISSUE THREAD

**Issue by MixMe** [metabase/metabase#4169] opened 2017-01-16 15:18 UTC
Future request ;)

**Comment by camsaul** [comment] 2017-01-16 17:54
I think #3363 covers this.

**Comment by camsaul** [comment] 2017-01-16 21:19
@MixMe you can just put all the Cards in the Dashboard in a Collection.

**Comment by salsakran** [comment] 2017-01-16 21:30
yes, this is a dupe of #3363 

closing in favor of that.

**Closed by salsakran** 2017-01-16 21:30 UTC
