### ISSUE TITLE
Impossible to save a query returning no results

### ISSUE THREAD

**Issue by Thierry-Godfroid** [metabase/metabase#12413] opened 2020-04-28 08:55 UTC
**Describe the bug**
When adding a new question or updating an existing one that returns **no row** (for a pulse), it's impossible to save it once the query has been run.

**Logs**
The save request `POST /api/card` returns `400` with payload
```
{
  "errors": {
    "result_metadata":"value may be nil, or if non-nil, value must be an array of valid results column metadata maps."
  }
}
```
The same message is returned on update when using `PUT /api/card/<id>`

**To Reproduce**

Assuming `select field, count(id) from table group by 1 having count(id) > 1` returns no row.

1. Add a question, 
2. choose the db
3. add the query,
4. **run the query**
5. click `Save` -> it fails with the `400` shown above 

**Expected behavior**
I expect the query to be saved without error. If you don't do step 4, it _will_ save.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_242-heroku-b08",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_242-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.242-b08",
    "os.name": "Linux",
    "os.version": "4.4.0-1062-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift",
      "h2"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.16"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.3",
      "date": "2020-04-21",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**
It's _really_ annoying: if you want to change it, the workaround is to change the query to return something, run it, change everything back, make the additional changes you want WITHOUT running the query, then save and test, and repeat.

**Additional context**

**Comment by flamber** [comment] 2020-04-28 09:41
Duplicate of #11256

**Closed by flamber** 2020-04-28 09:41 UTC
Labels: .Duplicate
