### ISSUE TITLE
After updating to 0.33, the default formatting settings are not applied.

### ISSUE THREAD

**Issue by johanjvrens** [metabase/metabase#10787] opened 2019-09-03 09:59 UTC
**Describe the bug**
After updating to 0.33, the default formatting settings set under Admin do now pull through on the settings option at the bottom of a question. This means I can't change a column to type currency as this will default to Dollars, same with date, time and all of the other data.

I did upgrade from 0.32.2 to the newest 0.33 and I'm using the docker container on AWS.

**To Reproduce**
1. Go to https://metabase.you-url.com/admin/settings/formatting
2. Click on formatting on the left menu and change the currency to South African Rand.
3. Go to a question that has a number and format it to currency using the new settings button on the bottom of the screen. 
4. The currency will ZAR is not applied or available to select for the question.

**Expected behavior**
I expected to see the symbol R when I select Currency.

**Screenshots**
After updating to 0.33, the default formatting settings set under Admin like shown below
![Screenshot 2019-09-03 at 09 50 27](https://user-images.githubusercontent.com/8234230/64162362-730cf000-ce3f-11e9-9ffe-c2265d5a0024.png)
![Screenshot 2019-09-03 at 09 50 15](https://user-images.githubusercontent.com/8234230/64162551-d26b0000-ce3f-11e9-8d71-46081fb2bb89.png)
do not propagate to the questions new settings pane as shown in the image below 
![Screenshot 2019-09-03 at 09 48 20](https://user-images.githubusercontent.com/8234230/64162519-c5e6a780-ce3f-11e9-90ef-62b1966feb1a.png)

**Information about my Metabase Installation:**
- Your browser and the version: (Google Chrome Version 76.0.3809.132 (64-bit))
- Your operating system: (OS X 10.10)
- Your databases: (Postgres)
- Metabase version: (0.33.0)
- Metabase hosting environment: (Docker)
- Metabase internal database: (Postgres)

**Severity**
There is no way for me to change from $ to R in all my tables.

**Additional context**
I'm from South Africa and we work in Currency (Rand), symbol (R), currency code (ZAR)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment] 2019-09-03 20:20
I believe this is effectively the same issue as https://github.com/metabase/metabase/issues/10703, which was fixed by https://github.com/metabase/metabase/pull/10704. The next dot release, 0.33.1, will include the fix for this, and will be coming out very shortly.

I can't reproduce this on the latest `release-0.33.x` release branch, so I'm going to close this since like I said I'm pretty sure it got fixed by that same PR.

**Comment by flamber** [comment] 2019-09-03 20:39
@mazameli 
Change of currency format is a different issue, not fixed by the PR.
To reproduce:
```SQL
SELECT SUM(TOTAL) FROM ORDERS
```
Then change Style to Currency, you can only change Label not Unit - I have global Unit set to Euro.
Also reported in the forum: https://discourse.metabase.com/t/column-styles-broken-by-0-33/7131/7
![image](https://user-images.githubusercontent.com/1447303/64206469-ab202d00-ce57-11e9-82b4-5c2f5fa0ebc9.png)

**Comment by mazameli** [comment] 2019-09-03 20:46
Ah, yep, I see. I misunderstood the issue: I think this is specifically for native/sql queries. Seems to be working correctly for GUI ones with `Currency` columns:

![image](https://user-images.githubusercontent.com/2223916/64207241-17e3f900-ce51-11e9-9d36-c68de97a610a.png)

![image](https://user-images.githubusercontent.com/2223916/64207294-31854080-ce51-11e9-9478-2a5f28e3227b.png)

**Comment by mallchin** [comment] 2019-09-09 11:11
This is not limited to native/SQL queries.  I cannot set the currency for a simple question in 0.33.2:

![Question_·_Metabase](https://user-images.githubusercontent.com/1703980/64526281-c5945380-d2fa-11e9-9e04-556facf5f415.png)

**Comment by steinmann321** [comment] 2019-09-09 16:50
Bug still present in 0.33.2

**Comment by kevin-kemok** [comment] 2020-02-20 16:51
Bug stil present in 0.34.2

**Comment by prigal** [comment] 2020-02-21 11:20
I can confirm too, still present in 0.34.2

**Comment by nsangwan** [comment] 2020-03-27 08:17
Bug stil present in 0.34.3

**Comment by flamber** [comment] 2020-03-27 09:44
Instead of leaving comments, please just upvote the first post by clicking :+1:

**Comment by EvaSchreyer** [comment] 2020-09-07 12:25
Bug still present in 0.35.4

**Comment by marcospls** [comment] 2020-10-05 23:47
unable to upgrade Metabase version (from 0.32.10 - last OK), by this recurrent or old issue.

**Comment by EvaSchreyer** [comment] 2021-05-03 14:48
hi, I can change now the currency in my query settings in 0.39. Thanks for fixing this :)

**Comment by daltojohnso** [comment] 2021-06-17 00:02
This seems to be fixed. I'm unable to repro based on what the previous comment showed. I will close this issue.

<img width="912" alt="Screen Shot 2021-06-16 at 5 00 17 PM" src="https://user-images.githubusercontent.com/13057258/122310098-719da200-cec4-11eb-8c13-f194f5071469.png">

**Comment by flamber** [comment] 2021-06-17 11:01
Reopening, since we're not applying the Global defaults, when selecting Currency for a field where this isn't applied through Data Model (example SQL). But lowering to P3, since it's now possible to set the Currency since 0.38.4.

Reproduce:
1. Admin > Settings > Localization > change Numbers and Currency to anything other than the defaults
![image](https://user-images.githubusercontent.com/1447303/122384372-ed9ef500-cf6b-11eb-9616-823d229448ff.png)
2. Simple question > Sample Dataset > Orders - set Currency for one of the fields that doesn't have this enabled in the Data Model (ex. Quantity)
It applies system-defaults instead of Global defaults for Currency, but it does correctly apply Global default for Separator
![image](https://user-images.githubusercontent.com/1447303/122384181-baf4fc80-cf6b-11eb-9842-ceeeb81cadae.png)
3. Same thing for a Native query
![image](https://user-images.githubusercontent.com/1447303/122384246-cc3e0900-cf6b-11eb-8671-89a488dd4781.png)

For more context about the different levels of formatting see the description in #11394

**Closed** 2021-09-23 11:27 UTC
Labels: Type:Bug, Priority:P3, Visualization/Chart Settings, Customization/Formatting, .Frontend, .Regression
