### ISSUE TITLE
[Bug] Group by day breaks Line & Area visualizations

### ISSUE THREAD

**Issue by davidllorente** [metabase/metabase#9690] opened 2019-04-04 09:56 UTC
This issue started happening on v0.30.0 (or at least v0.29.0 doesn't have this bug) and is still happening with the latest release v0.32.2.

Just select a sum of anything, or a count of anything, and grouping by day makes the Line and Area visualizations show empty. All other timestamp groupings work fine (minute, hour, week, even day of year). My current workaround is either grouping by day of year to have a Line visualization, or group by day and use the Table visualization.

**Comment by flamber** [comment] 2019-04-04 15:17
Hi @davidllorente 
WIthout more information, it is difficult to debug.
Can you reproduce this issue with Sample Dataset? Or a screenshot?
It might have something to do with Timeseries and Ordinal, which can be selected in the visualization options :gear: - and that usually is a problem if there's skips in the dates.

**Comment by davidllorente** [comment] 2019-04-04 15:50
Hi @flamber thanks for answering.
I thought about adding more detail when creating this issue but the screenshot really doesn't add more info:
![Screen Shot 2019-04-04 at 17 28 42](https://user-images.githubusercontent.com/14162118/55568084-4b362680-56ff-11e9-9bc3-1229411874dd.png)

I've tried reproducing the issue with the Sample Dataset and it does not occur. Back to my Dataset I've tried changing axes scales to Ordinal to no avail.
I don't know why this bug is happening to me, but I've not changed anything about my Druid database nor the data I sent to it (my timestamp column has always been like "2019-02-15 22:00:00 UTC") and it only stopped working when I upgraded to a newer version (I've tried launching v0.29.0 pointing to my production dataset and this bug does not happen)

**Comment by flamber** [comment] 2019-04-04 16:58
Do you see any errors in the browser developer console?
Can you download the results as CSV and attach here? Click the arrow-down to the right.

Make sure that your Field Types are set to something fairly correct (or not set at all) in Settings > Admin > Data Model > (database) > (table) > (column) :gear: 

Without any errors or ways to reproduce this issue, it's difficult to know what's going on. The only issue that, I know of. which has some of the same problems is #9235

**Comment by davidllorente** [comment] 2019-04-04 17:21
I've found the following error in the browser developer console:
`Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2019-03-28+01:00, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (http://localhost:3000/app/dist/vendor.bundle.js?7d6d729f0c3014d9a886:1:23741)
    at Mt (http://localhost:3000/app/dist/vendor.bundle.js?7d6d729f0c3014d9a886:1:41462)
    at Ct (http://localhost:3000/app/dist/vendor.bundle.js?7d6d729f0c3014d9a886:1:42173)
    at Tt (http://localhost:3000/app/dist/vendor.bundle.js?7d6d729f0c3014d9a886:1:42255)
    at Function.i.parseZone (http://localhost:3000/app/dist/vendor.bundle.js?7d6d729f0c3014d9a886:1:70441)
    at t.parseTimestamp (http://localhost:3000/app/dist/app-main.bundle.js?7d6d729f0c3014d9a886:5:274067)
    at t.HACK_parseTimestamp (http://localhost:3000/app/dist/app-main.bundle.js?7d6d729f0c3014d9a886:5:406992)
    at http://localhost:3000/app/dist/app-main.bundle.js?7d6d729f0c3014d9a886:5:400423
    at Array.map (<anonymous>)
    at http://localhost:3000/app/dist/app-main.bundle.js?7d6d729f0c3014d9a886:5:400318`

It only shows up when grouping by day (all other timestamp groupings don't throw this exception) which makes me think that this is the cause of the bug. The exception shows up as soon as I execute the query, regardless of which visualization (Table, Line...) I have selected.

I've checked the Field Type of my timestamp and is set to Entity Key (which should be correct because all other queries/groupings work). Also I've attached a CSV of an example query that reproduces the bug for me:
[query_result_2019-04-04T17_07_04.975Z.csv.zip](https://github.com/metabase/metabase/files/3044700/query_result_2019-04-04T17_07_04.975Z.csv.zip)

**Comment by mazameli** [comment] 2019-04-04 17:28
Yeah, I'm almost certain this is a duplicate of https://github.com/metabase/metabase/issues/9235 as @flamber said, especially since this is happening with Druid specifically for you. I'm going to close this as such, but please let me know if you think this is a separate issue, @davidllorente.

**Closed by mazameli** 2019-04-04 17:28 UTC
Labels: Duplicate

**Comment by davidllorente** [comment] 2019-04-04 17:34
It may be a duplicate, but please take a look at the stacktrace I've just posted. That seems to be the direct cause of the bug (and #9235 does not provide this evidence in the browser dev console).
