### ISSUE TITLE
Dynamic time for Email on Dashboard Subscription

### ISSUE THREAD

**Issue by jrca025** [metabase/metabase#34238] opened 2023-09-29 07:54 UTC
Please add a feature wherein we can manually input an exact time when the subscription be emailed. The current setup is too restricting in my opinion
![image](https://github.com/metabase/metabase/assets/89201548/86fb88b9-20cc-4c3e-b9c4-186d3a588b4a)

**Comment by paoliniluis** [comment] 2023-10-04 17:15
duplicate of https://github.com/metabase/metabase/issues/3135

**Closed by paoliniluis** 2023-10-04 17:15 UTC
Labels: Type:New Feature, .Needs Triage
