### ISSUE TITLE
Add a dashboard filter for numeric fields

### ISSUE THREAD

**Issue by excieve** [metabase/metabase#4796] opened 2017-04-17 14:49 UTC
Please consider implementing a dashboard widget, which would enable a "between" filter for numeric fields. This could be done as a double-sided slider for instance, with leftmost one defining a lower bound and the rightmost — the upper bound. The absolute bounds should be min and max values of the field.

This is very useful to provide public users with an ability to only see the graphs for a specific segment of certain numeric values (e.g. income, price, etc.) without making different dashboard with predefined segments.

**Comment by mazameli** [comment] 2017-09-05 21:23
Dupe of https://github.com/metabase/metabase/issues/3035 I think? I agree that this would be a welcome feature.

**Comment by stelio** [comment] 2017-11-06 14:43
@mazameli yes, agreed a dupe. How do we move this passed proposal?

**Comment by mazameli** [comment] 2017-11-06 22:10
Closing this as a duplicate of #3035

@stelio there are a number of dashboard widgets like this one that we on the core Metabase team are intending to add. We'll be looking at all of our priorities and seeing where this proposal fits in.

**Closed by mazameli** 2017-11-06 22:10 UTC
Labels: Dashboards, Duplicate, Parameters/Variables, Proposal
