### ISSUE TITLE
Click behavior for updating dashboard filter with visualization options > hidden fields

### ISSUE THREAD

**Issue by cnp0** [metabase/metabase#16927] opened 2021-07-07 19:14 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to create links out of fields that update filters based on hidden fields through the dashboard editing process. This saves space on simpler cards/visualizations (niche use). Could be a user problem. Will update if that's the case.

So a field where I can shorten the length of the data to save space on dashboard's card would have two forms

column_shortened, column_long
"12345...", 123456789

column_long would be used to update a filter on the dashboard after clicking on column_shortened.

Example

![image](https://user-images.githubusercontent.com/14341145/124816279-50195e80-df36-11eb-8bd2-a6670655b78f.png)

Hidden using 

![image](https://user-images.githubusercontent.com/14341145/124815701-90c4a800-df35-11eb-9da0-b68d379b4815.png)

and then

![image](https://user-images.githubusercontent.com/14341145/124815838-bce02900-df35-11eb-9479-08eac1e9c85f.png)

**Describe alternatives you've considered**
I've tried looking for similar issues submitted. I might have missed them but I haven't found any yet. Haven't tried anything else.

**How important is this feature to you?**
5/10 important - I would find this useful for interactive summarized reporting

**Comment by flamber** [comment] 2021-07-08 15:51
Duplicate of #13927

**Closed by flamber** 2021-07-08 15:51 UTC
Labels: .Needs Triage, Type:New Feature

**Comment by cnp0** [comment] 2021-07-10 14:37
If I'm following, this is in 0.40.0?

**Comment by flamber** [comment] 2021-07-10 16:38
@cnp0 Yes, the issues are tagged with milestones.
