### ISSUE TITLE
Views jus show two columns and cannot connect via SSH

### ISSUE THREAD

**Issue by jesusrtc** [metabase/metabase#3393] opened 2016-09-25 19:57 UTC
### Database support
+1 It would be nice if you allow people to connect via ssh

### Feature requests and proposals
In the views while creating a question I just can add two columns. That make sense if I'm going to plot a chart but not if I'm just going to get data.

### Congratulations
I became very excited when I found metabase cause it is amazing. I think you guys have thought in everything, I think your project is much much better even than most of paid tools.

**Comment by tlrobinson** [comment] 2016-09-25 23:22
Thank you for the feedback.

I believe this is a duplicate of #1403 and #1445. Please comment on those with any additional information/ideas you have, or open separate issues for each feature request.

**Closed by tlrobinson** 2016-09-25 23:22 UTC
