### ISSUE TITLE
Can't edit segment

### ISSUE THREAD

**Issue by shafy** [metabase/metabase#11343] opened 2019-11-18 22:26 UTC
After creating a Segment in the Admin panel, editing it is not possible. E.g. changing filter doesn't take effect, or trying to edit the name doesn't work. It seems like a front-end problem, because it doesn't let me delete the name or enter a reason for change.

I'm on Metabase v0.33.4 and tried with Firefox and Chrome on Mac.

**Comment by flamber** [comment] 2019-11-18 22:41
Confirmed on 0.33.5.1
Seeing `too much recursion` in the browser console.
Looks like `state` is setting original value `onchange`, so it's not possible to change value.

**Comment by cemsbr** [comment] 2020-01-02 14:30
While editing segments with 0.34.0, I'm still getting "too much recursion2 vendor.bundle.js:1:1372526" in Firefox and "vendor.bundle.js?f4999ff7ddee79f5a90a:1" in Chrome.

**Comment by mallchin** [comment] 2020-01-08 16:30
This affects me also.

Is there and ETA on a fix?

Has anyone got a workaround?

**Comment by paulrosenzweig** [comment] 2020-01-13 14:23
Fixed by #11670

**Closed by paulrosenzweig** 2020-01-13 14:23 UTC
Labels: .Frontend, Administration/Metrics & Segments, Priority:P1, Type:Bug
