### ISSUE TITLE
The detailed row view gets replaced with a warning triangle after about a second

### ISSUE THREAD

**Issue by aucampia** [metabase/metabase#33669] opened 2023-09-01 07:41 UTC
### Describe the bug

When clicking on a row identifier of some tables, the detailed view of the row shows only for about a second before disappearing and being replaced by a gray warning triangle (:warning:). 

No network errors occur, but the following error shows up in the console:

```
react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'table')
    at schema_metadata.js:10:41
    at Array.map (<anonymous>)
    at i (schema_metadata.js:9:6)
    at jT (ObjectRelationships.tsx:34:27)
    at ta (react-dom.production.min.js:153:146)
    at xs (react-dom.production.min.js:261:496)
    at Sc (react-dom.production.min.js:246:265)
    at _c (react-dom.production.min.js:246:194)
    at gc (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
```

### To Reproduce

1. Go to a table for which this occurs
2. Click on the primary key for a row
![cap_simplescreenrecorder-2023-09-01_08 40 59_00:00:23 133_02](https://github.com/metabase/metabase/assets/4481387/f909ef25-3ea0-46b0-8849-b613dbebcb51)
![cap_simplescreenrecorder-2023-09-01_08 40 59_00:00:26 833_03](https://github.com/metabase/metabase/assets/4481387/73b4a579-bc97-4d68-a652-324252562ad9)

3. See the detailed view for the row appear
![cap_simplescreenrecorder-2023-09-01_08 40 59_00:00:27 633_04](https://github.com/metabase/metabase/assets/4481387/ccb462dd-ef0d-464e-bd3b-e9b084d7fa44)

4. Notice how about a second later it dissapears and gets replaced with a gray warning triangle
![cap_simplescreenrecorder-2023-09-01_08 40 59_00:00:29 400_05](https://github.com/metabase/metabase/assets/4481387/1f43ad15-ed16-481d-b2ec-2b26d98ca6e6)
![cap_simplescreenrecorder-2023-09-01_08 40 59_00:00:29 967_06](https://github.com/metabase/metabase/assets/4481387/b69edbb5-7647-4bce-b1e9-d3ab5d4a6bec)
![cap_simplescreenrecorder-2023-09-01_08 40 59_00:00:30 967_07](https://github.com/metabase/metabase/assets/4481387/6db06a65-7a27-4611-9a3f-4ba15224a5e0)

### Expected behavior

The detailed row view should not disappear

### Logs

```
StructuredQuery.ts:368 Warning: can't clean query without metadata!
value @ StructuredQuery.ts:368
StructuredQuery.ts:368 Warning: can't clean query without metadata!
value @ StructuredQuery.ts:368
react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'table')
    at schema_metadata.js:10:41
    at Array.map (<anonymous>)
    at i (schema_metadata.js:9:6)
    at jT (ObjectRelationships.tsx:34:27)
    at ta (react-dom.production.min.js:153:146)
    at xs (react-dom.production.min.js:261:496)
    at Sc (react-dom.production.min.js:246:265)
    at _c (react-dom.production.min.js:246:194)
    at gc (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
cs @ react-dom.production.min.js:209
n.payload @ react-dom.production.min.js:227
mo @ react-dom.production.min.js:129
Ua @ react-dom.production.min.js:179
xs @ react-dom.production.min.js:263
Sc @ react-dom.production.min.js:246
_c @ react-dom.production.min.js:246
gc @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Zi @ react-dom.production.min.js:122
mc @ react-dom.production.min.js:240
notify @ Subscription.js:16
notifyNestedSubs @ Subscription.js:88
i @ Subscription.js:93
g @ redux.js:296
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ index.js:20
dispatch @ redux.js:691
(anonymous) @ utils.js:200
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
m @ promise.ts:61
a @ promise.ts:61
Promise.then (async)
m @ promise.ts:61
a @ promise.ts:61
(anonymous) @ promise.ts:61
(anonymous) @ promise.ts:61
(anonymous) @ utils.js:196
(anonymous) @ index.js:16
fetchTableFks @ ObjectDetail.tsx:106
(anonymous) @ ObjectDetail.tsx:182
(anonymous) @ useMount.js:4
ds @ react-dom.production.min.js:211
Bc @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Cc @ react-dom.production.min.js:257
gc @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Zi @ react-dom.production.min.js:122
T @ react-dom.production.min.js:287
Kt @ react-dom.production.min.js:68
```

### Information about your Metabase installation

```
- Browser: Google Chrome 116.0.5845.110 (Official Build) (64-bit) 
- Operating System: Fedora Linux 38 (Xfce)
- Database: PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
- Metabase version: v0.47.0 (`docker.io/metabase/metabase:v0.47.0@sha256:c8639a60e458adf72a2b06688ab7c805af1ab284f9bc129a231714d31611a331`)
- Metabase hosting environment: Docker
- Metabase internal database: Postgres
```

### Severity

Annoying

**Comment by WiNloSt** [comment] 2023-09-01 08:05
I believe this is a duplicate of https://github.com/metabase/metabase/issues/32654

**Comment by aucampia** [comment] 2023-09-01 08:33
> I believe this is a duplicate of #32654

Seems very similar, but I will leave the final choice up to whoever does the triage.

**Comment by WiNloSt** [comment] 2023-09-01 08:50
Closing as it's a duplicate of https://github.com/metabase/metabase/issues/32654

**Closed by WiNloSt** 2023-09-01 08:50 UTC
Labels: Type:Bug, Priority:P2, .Frontend, Visualization/Tables, Visualization/Detail
