### ISSUE TITLE
All bar and line chart visualizations have messed up

### ISSUE THREAD

**Issue by ssharma15** [metabase/metabase#10852] opened 2019-09-10 10:25 UTC
The Qualitative variables used in x-axis have somehow been distorted and the final visualization just shows a number scale on the x-axis.

Please see the tabular representation of data:
![image](https://user-images.githubusercontent.com/55136659/64605663-31052080-d3e2-11e9-952f-ae8c3e823b46.png)
 and the line chart for same data gives the following results
![image](https://user-images.githubusercontent.com/55136659/64605690-3ebaa600-d3e2-11e9-840e-b3bd88c8ebba.png)

The same issue is there with many other queries with bar charts, line charts, and combo charts
Information about your Metabase Installation:
- Chrome Version 72.0.3626.109 (Official Build) (64-bit)
- Windows 10.
- Databases MongoDB
- Metabase version: (e.x. 0.33.2)

It is blocking my usage of Metabase entirely as most of my visualizations in the dashboards are showing messed up data

**Comment by citizen-seven** [comment] 2019-09-10 13:30
Same for me. 
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/14357228/64618028-29487a80-d3e8-11e9-96aa-36644a03c203.png">

Fails on SQL based visualisations, when there is extra column left without usage. If I remove the column from the query, visualisation works correctly

**Comment by paulrosenzweig** [comment] 2019-09-10 13:45
Closing this as a duplicate of #10818 

A PR is open with a fix. It should go out with 0.33.3.

**Closed by paulrosenzweig** 2019-09-10 13:45 UTC
Labels: Type:Bug
