### ISSUE TITLE
Poor performance with "current" timestamp filters

### ISSUE THREAD

**Issue by James-REANNZ** [metabase/metabase#15275] opened 2021-03-21 22:26 UTC
While #10980 seemingly made timestamp queries better, it seems like it doesn't apply when using the "current" filters ("Current Day", "Current Week", etc.). This causes the query to use casts and prevents the use of the index.

For example, when I use "Current Day" I get this SQL (edited for clarity):

```SQL
SELECT <fields>
FROM "table"
WHERE CAST("timestamp" AS date) = CAST(now() AS date)
```

and I expect to get something more like:

```SQL
SELECT <fields>
FROM "table"
WHERE "timestamp" >= CAST(now() AS date) AND "timestamp" < CAST(now() AS date) + INTERVAL '1' day
```

On my PostgreSQL database, the difference is massive. The first query takes 3 minutes to execute, the second query takes 1 second (timed on the database server itself).

I am using version 0.38.2 of Metabase and version 11.11 of  PostgreSQL.

**Comment by flamber** [comment] 2021-03-22 08:45
Duplicate of #11837 - fixed by #14835 - will be part of 0.39.0

**Closed by flamber** 2021-03-22 08:45 UTC
Labels: .Needs Triage, Type:Bug
