### ISSUE TITLE
Notebook Editor becomes very slow (or freezes browser), when there is a lot of fields/sections

### ISSUE THREAD

**Issue by bricemaurin** [metabase/metabase#12378] opened 2020-04-22 17:02 UTC
**Describe the bug**
When opening the editor, the panel slides weirdly and verrrrry slowly.

**To Reproduce**
1. Go to any saved question
2. Click to open it
3. Click to show the editor

**Expected behavior**
well...the panel should just slide down, right? 

**Screenshots**

https://user-images.githubusercontent.com/1447303/131403586-0cae1a36-03c0-41ac-9beb-10446f5f4f1f.mp4

**Information about your Metabase Installation:**
```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko)",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+9-202002041938",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+9-202002041938",
    "os.name": "Mac OS X",
    "os.version": "10.15.2",
    "user.language": "en",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "osx",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-21",
      "tag": "v0.35.3",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2020-04-22 17:38
Hi @bricemaurin 
That looks pretty cool actually - we should implement this as the standard :wink:
Dang it, just noticed you're using the Mac App, which means it's Safari rendering, so you cannot even test with other browsers, and I'm not sure if there's a developer console (like regular browsers), where potential errors would be listed.

**Comment by bricemaurin** [comment] 2020-04-22 19:38
;)

I just tried opening local on chrome, and this solved my problem. Thanks @flamber !
is it possible to switch to chromium inside the app ?

**Comment by flamber** [comment] 2020-04-22 19:45
Let's leave this open, since it might be an issue on all Mac Apps.
I don't know the restrictions of Apple, so I don't know what's possible.

**Comment by aleixdorca** [comment] 2021-05-20 15:56
This happens to me as well. I have version 0.39.2 running.

This behavior affects both mac computers with Safari, Firefox or Chrome as well as GNU/Linux running Chrome.

It is most severe when the editor contains a significant number of joins, filters and summarize rules.

**Comment by flamber** [comment] 2021-05-20 16:12
@aleixdorca I can reproduce - the more joins+metrics+groups, the slower the UI gets - specially the enter/exit Notebook.
This is just zoomed out to show I did to reproduce.
![image](https://user-images.githubusercontent.com/1447303/119012960-ccf87500-b996-11eb-8c3a-f31bfbe2b855.png)

**Comment by kulyk** [comment] 2021-08-31 16:50
Did some investigation here a few days ago. I guess I found two major reasons affecting the performance here:

1. For each notebook section (join, custom column, filter, summarize, sort, etc. sections) we [generate a reverted query on every render](https://github.com/metabase/metabase/blob/ab75c941e57520195d62612a3d397899e06e042f/frontend/src/metabase/query_builder/components/notebook/NotebookStep.jsx#L142). A reverted query is a query without a particular part of it. Let's say we have a query with a join and a filter. A query with a reverted filter will only contain the join. We do that to check if it's okay to remove that section (and to display the "remove" icon). You can see the reverted query is created, then we check if the reverted query is valid and if it is, we show the "remove" icon. I just removed that piece of code locally and the performance improved heavily.
2. Every [notebook step component](https://github.com/metabase/metabase/tree/master/frontend/src/metabase/query_builder/components/notebook/steps) does a lot of stuff on every render. The more steps we have, the more the performance drops. I replaced a few of them with divs and the performance improved (even with the reverted query thing running)

As an idea, we can try to memoize the reverted query thing + wrap notebook steps with `React.memo`

Sorry, I had to share those after I did some experiments, so now it's better to double-check everything I wrote here

**Comment by kulyk** [comment] 2021-09-02 11:05
Update: it looks to me that reason two is not really the case and it's more about the `Triggerable` and `Popover` components. Almost every cell in the notebook is wrapped with `Triggerable` and `Popover`. Once I removed them and removed step 1 (reverted query generation), the performance improved heavily (and all the step components were still spawning callbacks and stuff on every render). So it looks to me we'd need to optimize `Triggerable` and `Popover`

Step 1 is going to be solved by #17727 if there are no issues there

**Comment by francisyan123** [comment] 2021-09-22 08:07
@kulyk Hi,I find #17727 was merged 8 days ago,but version 0.40.5 not yet applied.How long can we use in metabase?

**Comment by flamber** [comment] 2021-09-22 08:08
@francisyan123 That is not part of 0.40.5. It will be included in 0.41.0

**Comment by flamber** [comment] 2021-10-09 16:57
@aleixdorca This issue has not been fixed. Only parts of it was fixed in #17727. When this issue is closed, then it will get a milestone, so you can see which version it is fixed from.

**Comment by gggdomi** [comment] 2021-11-16 16:41
I have no strict evidence, but here is my experience if it helps : I just upgraded from 0.39 to 0.41.1. I had barely noticed these slowdown before. Since the update I see them daily. Sometimes it takes 1min+ to unfold the notebook. (Chrome on MacOS, same config for 2+ years)
So there may be a regression. That could explain why new issues on the matter are opened these days.

**Comment by flamber** [comment] 2021-11-16 17:06
@gggdomi There's a lot more complexity and functionality added to newer releases, which is part of the reason for the (regression) slowdown. It has been quite difficult to fix this, but it is on our radar.
I can definitely see that it's also something to do with the amount of fields (many tables with many columns).

**Comment by ariya** [comment] 2021-11-18 21:54
> This is just zoomed out to show what I did to reproduce.

While the presence of animation noticeably makes things worse, the likely cause of this performance issue is the expensive construction (or re-rendering) of the notebook component itself. Take a look at the following `Performance` capture of Chrome DevTools, where the notebook initial render (right after clicking on the Hide/Show Editor) takes 1.25 seconds (and I'm on a beefy machine, 16 cores with 32 GB RAM).

![image](https://user-images.githubusercontent.com/7288/142502671-5c4228f2-e16d-486a-bea6-c3711f200a80.png)

When drilling down further, I even discovered a GC process blocking the thread for quite some time.

The long-term fix is to significantly reduce the time it takes for the notebook component to render. However, in the mean time, I'm looking for a few shortcuts which get use noticeable quick wins.

**Comment by nshcylindo** [comment] 2021-11-19 13:18
It is possible to disable this animation?

**Comment by timuric** [comment] 2021-11-24 11:20
This bug have been there for years, and makes authoring questions unbearable. To be honest if you write questions everyday these animations are very annoying and time consuming. Most professional software avoid such heavy animations (excel, tableau, any IDE, etc). I am begging you to consider to remove this effect!

**Comment by flamber** [comment] 2021-11-24 11:31
@timuric I would recommend that you enable reduced-motion in your browser. We have made it so all animations are removed if that is activated (some already available in 0.41, while everywhere is included in 0.42).
For context: https://github.com/metabase/metabase/issues/17726 https://github.com/metabase/metabase/issues/18169

**Comment by timuric** [comment] 2021-11-24 12:45
@flamber Reduce motion doesn't work on mac, but also not really solving a problem since we can't force all organization users to use reduced motion settings system wide. Since this option is already implemented, can it be added as an option in the admin panel?

**Comment by flamber** [comment] 2021-11-24 12:47
@timuric It's not an option, it's a browser accessibility settings that is being detected, but you are welcome to open a new issue, since it's not really specific to this issue, which is a performance issue that is caused by many different things.

**Comment by flixx** [comment] 2021-12-02 10:50
@flamber Seems to be included in v42. As far as I understand, it might be slightly faster then. Great!


Is there maybe some workaround for disabling those animations without waiting for v42 already?
Maybe some code-snippets that we could past into the console?

**Comment by flamber** [comment] 2021-12-02 10:57
@flixx There are some fixes coming in the next 41.x release (#19131), which should make it a lot less problematic for most. But this issue will not be closed until we have fixed all the problems.
There's no simply workaround - this is not a simple issue, and we've spend many hours on it already, but it's very complicated.

**Comment by flixx** [comment] 2021-12-03 09:55
@flamber 
I can confirm that the situation improved drastically in 1.41.3.1.

Thanks! 🙏

**Closed** 2023-09-13 11:04 UTC
Labels: Type:Bug, Priority:P1, .Performance, Difficulty:Hard, .Frontend, Querying/Notebook, .Team/42 :milky_way:

**Comment by Stepease1** [comment] 2023-09-21 02:25
good job everyone

**Comment by renatodossantosleal** [comment] 2023-12-08 21:43
Hi! We're still suffering with this issue as the UI becomes really slow after adding 2 simple custom columns and 10+ summarized fields at the visual builder.

Every new aggregation/summarization makes the UI painfully slower, that happens specially after clicking the done.
Trace below:
[Trace-20231208T181503.zip](https://github.com/metabase/metabase/files/13621168/Trace-20231208T181503.zip)

**Comment by Stepease1** [comment] 2025-06-14 06:51
What is this
