### ISSUE TITLE
Exports of Pivot Table contains `pivot-grouping` when question is unsaved

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15034] opened 2021-03-02 21:07 UTC
**Describe the bug**
When using the visualization Pivot Table and the question is not saved (in "dirty" state), then exports include the column `pivot-grouping`.

**To Reproduce**
1. Custom question > Sample Dataset > Products - summarize Count by Category and CreatedAt:Year:
![image](https://user-images.githubusercontent.com/1447303/109714409-abab9800-7ba2-11eb-98ec-c50cd00560ab.png)
2. Change visualization to Pivot Table
![image](https://user-images.githubusercontent.com/1447303/109715139-92efb200-7ba3-11eb-87bc-d3882f2f57ba.png)
3. Export as CSV (XLSX or JSON) - the download includes the column `pivot-grouping`
```
Category,Created At,pivot-grouping,Count
Doohickey,2016-01-01,0,13
...
```
4. Saving the question and exporting again, now it only includes the columns as expected:
```
Category,Created At,Count
Doohickey,2016-01-01,13
...
```

**Expected behavior**
Never expose system data like `pivot-grouping` to users.

**Information about your Metabase Installation:**
Tested `44ce694` (almost 0.38.1)

**Additional context**
This will likely get fixed when #15008 is addressed.
Found during testing of #15019

**Comment by cdeweyx** [comment] 2024-08-22 14:28
Closing as dupe of https://github.com/metabase/metabase/issues/46561 which is more recent and applies outside of just unsaved questions.

**Closed by cdeweyx** 2024-08-22 14:28 UTC
Labels: Type:Bug, Priority:P3, Reporting/Export, .Backend, Visualization/Tables, .Team/DashViz
