### ISSUE TITLE
Bad performance when typing in forms on the Collections page

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#19297] opened 2021-12-09 19:32 UTC
**Describe the bug**
Typing the name of a new collection on the `/collection/root` route is quite slow. On every key press it seems like the entire page is re-rendering.

**To Reproduce**
1. Navigate to the Collections page (`/collection/root`)
2. Click the plus icon to open the "new collection" form modal
3. Start typing and observe slowness. The more dashboards/questions you have on the page, the slower it is.

**Expected behavior**
Form inputs shouldn't feel sluggish.

**Screenshots**
Here's a screenshot of some long scripting times caused by keypress events:

![Screen Shot 2021-12-09 at 11 23 50 AM](https://user-images.githubusercontent.com/13057258/145462934-7dfce4f3-07be-4ca7-b4de-bc0ce9d5fcb2.png)

Here's a recording with react component re-renders highlighted:

https://user-images.githubusercontent.com/13057258/145462945-8ee37b98-fd5d-4ac4-a89b-a009a5057c7c.mov

**Information about your Metabase Installation:**
This is on `master`.

**Severity**
The performance hit here is fairly severe.  I'm seeing keypress events on my local instance block the main thread for upwards of 200 to 300ms. I think we ought to fix this before the release, ideally. P2?

**Additional context**
Wrapping components on the page in `React.memo` will hopefully take us a decent ways toward fixing this because this is clearly the result of unnecessary component re-renders.

**Comment by flamber** [comment] 2021-12-09 19:42
Looks like a duplicate of #14601, but it might have gotten worse again in master.

**Closed** 2022-04-18 10:27 UTC
Labels: Type:Bug, Priority:P2, .Performance, Organization/Collections, .Frontend, .Regression
