### ISSUE TITLE
Filter dashboards by year

### ISSUE THREAD

**Issue by to-schi** [metabase/metabase#26943] opened 2022-12-04 13:02 UTC
I want to filter a dashboard by year by clicking on "year"-filter and then one of the available year-numbers, like 2021, 2022.
At the moment you can set a time filter for "quarter and year" and "month and year", but not a whole year.

This is important for almost every BI-dashboard I build.

**Comment by flamber** [comment] 2022-12-04 13:28
Duplicate of #10477

**Closed by flamber** 2022-12-04 13:28 UTC
Labels: Type:New Feature, .Needs Triage
