### ISSUE TITLE
V 0.37.0.2 Linked Filters will not work in embedded applications

### ISSUE THREAD

**Issue by shieleven** [metabase/metabase#13639] opened 2020-10-30 02:24 UTC
The Linked Filters feature is not available in the dashboard of the embedded application in version 0.37.0.2. The filter returns a blank value, and entering any data does not matter. This is a great feature, and if you can use it in an embedded application, it will be perfect!

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by lutvdh** [comment] 2020-11-07 11:17
i just picked this up as well and have been trying to figure out what im doing wrong but it appears that its a bug in the system or not considered as part of the embedded dashboard feature.  @mazameli , can you confirm if this works in the embedded dashboard feature of metabase?

**Comment by shieleven** [comment] 2020-11-09 06:37
The question is generated by SQL

**Comment by lutvdh** [comment] 2020-11-11 14:37
The linked filters don't work when you use the public sharing link as well.

**Comment by mdz0r** [comment] 2020-11-23 17:33
Could it be related to #13858 ?

**Comment by lutvdh** [comment] 2020-11-30 08:57
@camsaul , hope that you are well.  Have you been able to able to spend any time on this ticket to confirm if its a bug?

**Comment by mazameli** [comment] 2020-12-07 17:25
@camsaul Let me know if you need additional details on this bug — we have a contact who's offered to provide whatever info you need.

**Comment by lutvdh** [comment] 2020-12-17 08:49
> @camsaul Let me know if you need additional details on this bug — we have a contact who's offered to provide whatever info you need.

Hi @mazameli & @camsaul, hope you guys are well.  Please advise if this was resolved in v0.37.3 the release notes say that this was fixed but i still get the same behavior when trying to access the linked filters via either public shared link or embedding option.

**Comment by shieleven** [comment] 2020-12-23 07:07
V0.37.3 It's not fixed

**Comment by lutvdh** [comment] 2020-12-23 13:56
> V0.37.3 It's not fixed

:-(

**Comment by camsaul** [comment] 2021-01-07 03:28
This is the same issue https://github.com/metabase/metabase/issues/13858. We shipped a fix for it with 0.37.5 yesterday. 

Duplicate of #13858

**Closed by camsaul** 2021-01-07 03:28 UTC
Labels: Embedding/Signed, Priority:P1, Reporting/Dashboards, Type:Bug

**Comment by SG2019** [comment] 2021-01-07 05:02
Hi @mazameli 
 The issue has been fixed for public link in v0.37.5 but not working for embedded applications.

**Comment by beko1997** [comment] 2021-01-14 09:12
@mazameli @camsaul @SG2019 I can indeed confirm this issue still exists with embeding dashboards. I've tested both v0.37.3 and v0.37.5. The filterlist stays empty on the embedded version, while it does get filled in MetaBase self.

The issue is a 400 response on the following request:

GET api/embed/dashboard/xxxxxxx/params/b2234673/values
````
Output of chain-filter-merged-params does not match schema: 

	 [0;33m  {(not (instance? java.lang.String nil)) invalid-key} [0m 
````

Any ideas on how to fix this one?

**Comment by marcoruggine** [comment] 2021-04-22 14:21
Hi, any plan on solving this for embedded dashboards? I'm running 0.39.0.1 and it's still not working. Thanks

**Comment by flamber** [comment] 2021-04-22 14:28
@marcoruggine It has been fixed, but you're likely seeing a different issue.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And include logs from Admin > Troubleshooting > Logs, and browser console errors.
And if you can reproduce with Sample Dataset, then please include an example of that.
