### ISSUE TITLE
Ability to Change the Row-Limit for Visualizing Data

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#12005] opened 2020-02-27 19:34 UTC
Currently there is a 2000-row limit when visualizing data. 
It would be nice to have an option to change this in the Settings. 
Even better if we can set different limits for different DB's (in the Data Model, which overwrites the global value in the Settings).

**Comment by flamber** [comment] 2020-02-27 19:46
Hi @vvaezian 
Sounds a lot like #4564 - can we close this as a duplicate of that?

**Closed** 2020-02-27 20:21 UTC
Labels: .Needs Triage, Type:New Feature
