### ISSUE TITLE
Non-Query Card-Types

### ISSUE THREAD

**Issue by taker93** [metabase/metabase#4836] opened 2017-04-21 10:16 UTC
There should be an option to add cards to the dashboard which can be filled via an text/html-editor.

⬇️  Please click the 👍 reaction instead of leaving a `+1` or 👍  comment

**Comment by tlrobinson** [comment] 2017-04-21 16:00
@taker93 could you describe your use cases for this?

Would a simple "label" card be sufficient? If not, what about basic rich text (or markdown?) Or do you need raw HTML for some reason?

(FYI you can currently fake this with a `SELECT 'text'` question but thats obviously not ideal)

**Comment by camsaul** [comment] 2017-04-21 17:39
Similar to #3635

**Comment by taker93** [comment] 2017-04-21 17:54
I guess that some dashboards could also contain static data like descriptions of what you're seeing, a logo of the company, i even saw dashboards with a clock or calendar.

Or you could have "special" data you want to present in another than the provided ways. (e.g. TO-DO-List) Then you would need to be able to create individual cards (and create a binding to your query-results). (i guess this would be off-topic in this issue)

My special use case that made me think of that idea:
Because I'm not able to describe x-axis-values in my favoured way. I'm displaying the numbers which are retrieved by the query and would like to describe their relevance via text. (i could map it in the sql, right)
That was when I wanted to display an additional legend on a card at the side of my diagramm.

**Comment by gilhs** [comment] 2017-04-23 06:48
We would also very much like to have this feature.  Sometimes you want to add things like launch dates, short descriptions (company mission), explanations, etc.

**Comment by alee792** [comment] 2017-08-14 19:46
A markdown card would be great! We are setting up large displays in a warehouse and would love to include short announcements or images.

**Comment by tedpower** [comment] 2017-09-29 20:39
Would love this. We create an OKR dashboard, and it'd be nice to group the metrics under the 'Objective' heading.

**Comment by jornh** [comment] 2018-01-09 21:32
Implemented by #6436 (I'd say this is a dupe of #3221)

**Comment by camsaul** [comment] 2018-01-09 21:33
Yeah looks like a duplicate.

**Closed by camsaul** 2018-01-09 21:33 UTC
Labels: Dashboards, Proposal
