### ISSUE TITLE
Clicking "Reset to defaults" in a dashcard viz removes all viz settings

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#26945] opened 2022-12-05 01:58 UTC
**Describe the bug**
When overwriting visualization options in a dash card, clicking the "reset to defaults" button near the bottom of the modal will remove all viz settings, rather than bring you back to whatever viz settings were originally saved with the card.

**To Reproduce**
1. Click New -> Question -> Orders
2. Metric: Count, Group By Quarter
3. Change the labels (or any other viz settings)
4. Save and add to a dashboard
5. Click visualization options on the dashcard
6. At the bottom of the modal, click reset to defaults
7. Notice that any custom settings such as renamed labels are reset back to their original values. If you click on save, nothing will happen

**Expected behavior**
I would expect reset defaults to only undo settings made to the Dashcard, not the original card itself.

**Screenshots**
![image](https://user-images.githubusercontent.com/1328979/205532581-c0b0f906-a8f9-4206-a315-89c1239652d0.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1-Ubuntu-0ubuntu1.20.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1-Ubuntu-0ubuntu1.20.04",
    "os.name": "Linux",
    "os.version": "5.10.16.3-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "America/Halifax"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2022-11-24",
      "src_hash": "4fdb72203d7b38cadc6da948624f6f03b9f129b8",
      "tag": "v1.45.1-SNAPSHOT",
      "branch": "Viz-Settings-Update-Eye-Icons",
      "hash": "94d9e4a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Likely not severe, though if we don't fix it would should remove the button.

**Comment by flamber** [comment] 2022-12-05 09:41
Clicking "Done" will show settings from the card, it's just temporary glitch. We should definitely not remove "Reset to defaults" button.
Duplicate of #13248

**Closed by flamber** 2022-12-05 09:41 UTC
Labels: Type:Bug, .Needs Triage
