### ISSUE TITLE
Allow 'Select None' when picking columns on single table

### ISSUE THREAD

**Issue by ryshi** [metabase/metabase#19982] opened 2022-01-27 12:18 UTC
I added a table with more than 100 columns to my metabase, and it will show all columns by default when browsing data.
Is it possible to allow 'Select None' like what join data does?

![image](https://user-images.githubusercontent.com/1818419/151357371-aab3b7fc-2e8d-447b-9141-d8d3920b1a3e.png)

**Comment by flamber** [comment] 2022-01-27 12:20
Duplicate of #10460 - It will be possible in 0.42

**Closed by flamber** 2022-01-27 12:20 UTC
Labels: Type:New Feature, .Needs Triage
