### ISSUE TITLE
Labels / Legenda not shown correctly

### ISSUE THREAD

**Issue by RS514227** [metabase/metabase#13901] opened 2020-11-26 21:06 UTC
<img width="1435" alt="Schermafbeelding 2020-11-26 om 21 28 27" src="https://user-images.githubusercontent.com/75096673/100390922-3aec6100-3032-11eb-8484-08e1f8fd6e0c.png">

Hi there, I'm new to this forum, run metabase for a couple of days and already love it. I run the dutch version and I'm not sure if the translation is 100% and I also don't know if the bug is only in the Dutch version showing.

The example consists of database fields and custum fields like SUM and AVG. I renamed the fields and the legenda (left upper corner) is showing the correct names. The labels on the hover field show a mix of original names and remained field. I even can state that only 1 field is shown correctly and the others are shown in their original name.

I'm running version 0.37.2.0 on Ubuntu Server 20.04 connected to MySQL 8.0

Details from metabase itself.
{
  "browser-info": {
    "language": "nl-nl",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.9.1+1-Ubuntu-0ubuntu1.20.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.9.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.9.1+1-Ubuntu-0ubuntu1.20.04",
    "os.name": "Linux",
    "os.version": "5.4.0-54-generic",
    "user.language": "en",
    "user.timezone": "Europe/Amsterdam"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-11-16",
      "tag": "v0.37.2",
      "branch": "release-x.37.x",
      "hash": "25e5f70"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}

**Comment by flamber** [comment] 2020-11-27 11:52
Duplicate of #11395

**Closed by flamber** 2020-11-27 11:52 UTC
Labels: .Needs Triage, Type:Bug

**Comment by RS514227** [comment] 2020-11-27 12:03
Hi Flamber,

I agree seems like the same problem. Please advise why both are closed? I run the latest release and it is still occurring. 

Kind regards,
Ralf

Verstuurd vanaf mijn iPhone

**Comment by flamber** [comment] 2020-11-27 12:08
@RS514227 #11395 is not closed.

**Comment by RS514227** [comment] 2020-11-27 12:14
Hi Flamber,

New to GitHub, you’re right again. Thanks for the update. 

Verstuurd vanaf mijn iPhone
