### ISSUE TITLE
sum of numerical values with null in the data

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#4985] opened 2017-05-05 20:59 UTC
Case:
- My analytics storage DB contains `null` values in a numeric column
- If I try to do `sum` on that column, result varies based on the backend engine but is mostly wrong for SQL-based databases
- Even if ^ was correct, as soon as I group the data by any other column, the values end up being `null`

More details:
- Tested on BigQuery and MySQL DBs
- On 0.23.1

Possible fix:
- For any SQL like DB (even BQ): add `IFNULL(sum(column_name), 0)` when making queries from GUI query builder

@camsaul Thoughts?

**Comment by salsakran** [comment] 2017-05-05 22:00
Labeling this a bug, even though it's underlying idiocy in the DB since if I select `sum` from the QB I expect to see sum and not have nulls leaking in

**Comment by flamber** [comment] 2021-11-08 12:58
Closing, since I cannot reproduce on 0.41.1 - there's a known issue #12394, which has reproducible steps.

**Closed by flamber** 2021-11-08 12:58 UTC
Labels: Type:Bug, Priority:P2, Querying/Processor
