### ISSUE TITLE
Don't ask for addition to dashboard if existing question is edited

### ISSUE THREAD

**Issue by c-schmitz** [metabase/metabase#6605] opened 2017-12-20 13:05 UTC
When editing an existing question and the question already exists on any dashboard the question 'Do you want to add this question to a dashboard' becomes really annoying after some time.

Instead if would be better if the software offered to jump to the particular dashboard instead, like:

"The question was updated . Do you want to check out the related dashboard  <Dasboardname'>'.
If the question is used on several dashboards probably don't ask at all.

**Comment by samweber** [comment] 2017-12-20 16:42
See #6541

**Comment by mazameli** [comment] 2017-12-20 17:24
Yeah, closing as a duplicate of #6541. This was resolved by #6580

**Closed by mazameli** 2017-12-20 17:24 UTC
Labels: Duplicate

**Comment by c-schmitz** [comment] 2017-12-20 19:07
Okay, thank you!
