### ISSUE TITLE
Column Display Names for Same Foreign Key are Tied Together

### ISSUE THREAD

**Issue by jbarnesdafg** [metabase/metabase#19512] opened 2022-01-03 14:53 UTC
**Describe the bug**
When joining a foreign key onto the same table multiple times but to different fields, the column display names are tied together and show the same name. Any attempt to rename one to differentiate them will change the others to match. To be clear the data is correct, just the display names for the columns are the issue.

**To Reproduce**
See screen shots for the query structure.

**Expected behavior**
Columns should be capable of being named differently when the right table has been joined to separate fields in the left table.

**Screenshots**
![image](https://user-images.githubusercontent.com/95362507/147941841-18533980-340a-4829-9763-c6a84ff3fb47.png)
![image](https://user-images.githubusercontent.com/95362507/147941895-6968410e-1abd-4906-9ad1-e24ee99e9d1e.png)
![image](https://user-images.githubusercontent.com/95362507/147941976-4432948e-de85-47b9-8854-efe675fa627b.png)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_252-8u252-b09-1~16.04-b09",
    "java.vendor": "Private Build",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_252",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.252-b09",
    "os.name": "Linux",
    "os.version": "4.4.0-101-generic",
    "user.language": "en",
    "user.timezone": "SystemV/EST5"
  },
  "metabase-info": {
    "databases": [
      "db2",
      "sqlserver",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.5.21"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v1.41.5",
      "date": "2021-12-16",
      "branch": "release-x.41.x",
      "hash": "fbfffc6"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}

This was a postgres query.

**Severity**
Users will not be able to tell the different columns apart from each other. This makes reports very difficult to use, if not impossible.

**Comment by flamber** [comment] 2022-01-03 15:13
Duplicate of #12685

**Closed by flamber** 2022-01-03 15:13 UTC
Labels: Type:Bug, .Needs Triage
