### ISSUE TITLE
Y-axis range not adjusting in 0.33.5.1

### ISSUE THREAD

**Issue by DannyK85** [metabase/metabase#11367] opened 2019-11-21 14:50 UTC
When enabling the min/max for a custom Y-axis range the range doesn't seem to be updated.
![Screenshot 2019-11-21 at 15 45 23](https://user-images.githubusercontent.com/5367750/69348325-46b28400-0c76-11ea-8b69-75ec2016b15e.png)

Metabase version 0.33.5.1
For custom questions & native sql questions.

**Comment by flamber** [comment] 2019-11-21 14:54
Hi @DannyK85 
Sounds like a duplicate of #10434. If you agree, then please close this and upvote the other issue :+1:

**Closed** 2019-11-21 14:56 UTC
Labels: .Needs Triage, Type:Bug
