### ISSUE TITLE
Dashboard filter dropdowns cut off on small cards

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4719] opened 2017-04-07 16:29 UTC
This is a tricky one because there's just too much content to fit, especially in a multi-series card like the example below. One option would be to hide the note/warning when a card is this size, and then stack the dropdowns vertically. Another option would be to stack everything vertically and add internal vertical scrolling to the card, which sounds gross.

![screen shot 2017-03-20 at 1 55 31 pm](https://cloud.githubusercontent.com/assets/2223916/24809404/447ca3be-1b74-11e7-8261-3a0b97ce0313.png)

Related to #4648 and #3979.

**Comment by flamber** [comment] 2020-06-04 13:46
I cannot reproduce on 0.35.4 - now it looks like this - closing, since #4648 should handle long titles
![image](https://user-images.githubusercontent.com/1447303/83764595-693c4580-a67a-11ea-9a99-f8f1eb135c6d.png)

**Closed by flamber** 2020-06-04 13:46 UTC
Labels: Reporting/Dashboards, Type:UX
