### ISSUE TITLE
Not able to migrate to metabase 0.31

### ISSUE THREAD

**Issue by mohit091** [metabase/metabase#8928] opened 2018-11-12 15:06 UTC
while migrating to metabase 0.31 getting the issue 

com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-agilliland-migrations/000_migrations.yaml' for key 'idx_databasechangelog_id_author_filename'

**Comment by camsaul** [comment] 2018-11-12 19:58
Hi @mohit091 I'm taking a look at this issue and hope to have a fix later today. 

Duplicate of #8909

**Closed by camsaul** 2018-11-12 19:58 UTC
