### ISSUE TITLE
Unable to change timezone to IST on Metabase using Redshift tables

### ISSUE THREAD

**Issue by gvaibhavraj2** [metabase/metabase#16099] opened 2021-05-16 15:04 UTC
**Describe the bug**
We're currently using Metabase on top of Redshift tables. Redshift date data is in UTC. 
We want to render our dashboards in IST on Metabase. The report timezone setting doesn't work on metabase. Also, after setting redshift timezone to IST for our user, it still doesn't reflect.

Our setup in on Elastic Beanstalk with Metabase deployment. Please help with ways to fix this.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your databases: (Redshift)
- Metabase version: (0.39.1)
- Metabase hosting environment: (Elastic Beanstalk, Docker)
- Metabase internal database: ( Postgres )

**Severity**
Prod release blocker

**Comment by flamber** [comment] 2021-05-16 16:04
Hi @gvaibhavraj2 
Post "Diagnostic Info" from Admin > Troubleshooting, and which database column type you are having issues with.

**Comment by gvaibhavraj2** [comment] 2021-05-16 16:10
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.14.225-169.362.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Kolkata"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "h2"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-27",
      "tag": "v0.39.1",
      "branch": "release-x.39.x",
      "hash": "6beba48"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by flamber** [comment] 2021-05-16 16:21
@gvaibhavraj2 Please provide the DDL for one of your table. I need to know exactly which column type it is.

**Comment by gvaibhavraj2** [comment] 2021-05-16 16:28
@flamber Attaching schema and value for your ref
**Check createdat field**
<img width="551" alt="Screenshot 2021-05-16 at 9 57 23 PM" src="https://user-images.githubusercontent.com/7159037/118404749-c9f93e00-b691-11eb-848e-3324145acb75.png">

<img width="139" alt="Screenshot 2021-05-16 at 9 57 05 PM" src="https://user-images.githubusercontent.com/7159037/118404743-c6fe4d80-b691-11eb-80cc-20d3b2f38f0a.png">

**Comment by flamber** [comment] 2021-05-16 16:38
@gvaibhavraj2 I'm guessing this is a column without timezone `timestamp without time zone`. Metabase currently doesn't handle conversion of such columns. You would need to either change it to `timestamptz` or create a view, where you do the conversion.
Duplicate of #13400

**Closed by flamber** 2021-05-16 16:38 UTC
Labels: .Needs Triage, Type:Bug

**Comment by gvaibhavraj2** [comment] 2021-05-16 16:54
@flamber Our use case is to ingest data through a third party integration service. It wouldn't allow to configure the column type directly.
Also, adding on views would mean changing it every time we don anything on Metabase? Is there a middleware/wrapper which can help convert our `timestamp` columns to `timestampz`?

**Comment by flamber** [comment] 2021-05-16 17:08
@gvaibhavraj2 Creating a view would be the "middleware". You would create a view for every table, so Metabase would just use those views instead of the original tables.
There's work being done to try adding such modelling to Metabase in the future, but no timeline for when it might come.
