### ISSUE TITLE
New version 0.33.4 stopped working behind HTTPS apache2 reverse proxy

### ISSUE THREAD

**Issue by atranel** [metabase/metabase#11139] opened 2019-10-15 08:18 UTC
I was using 0.33.2 without issues, but new version 0.33.4 is showing only blank screen when used via https proxied address. When I use public IP like http://10.34.1.203:3000 it works as expected.

**Comment by flamber** [comment] 2019-10-15 15:32
Hi @atranel 
Please post your Apache config (redact where needed).
Have you configured the correct Site URL in Admin > Settings > General?
What errors do you see in the browser console, when it displays the blank page?

**Comment by atranel** [comment] 2019-10-17 06:56
@flamber I have it set correctly all the time. It just stopped to work after upgrade. I get blank white page and this in console:
![image](https://user-images.githubusercontent.com/42370527/66984912-f7e45e00-f0bb-11e9-9732-921685b3acef.png)

**Comment by flamber** [comment] 2019-10-17 07:07
@atranel Okay, so you're using sub-directory like #11148. Haven't tracked down the root cause yet, but I'm guessing it's caused by PR 10963. Until it's fixed, downgrade to 0.33.3.

**Comment by paulrosenzweig** [comment] 2019-10-21 20:03
Fixed in #11174

**Closed by paulrosenzweig** 2019-10-21 20:03 UTC
Labels: .Duplicate, Type:Bug
