### ISSUE TITLE
[BUG] Conflict on multiple aggregations of the same type

### ISSUE THREAD

**Issue by icosamuel** [metabase/metabase#8983] opened 2018-11-20 15:34 UTC
## Bug
Both Averages work well on their own, but when viewed together one of them gets overwritten by the other.

Average on `Data.P1Thrown`
![image](https://user-images.githubusercontent.com/5400332/48783825-56883880-ecaf-11e8-81bd-5306ec161b61.png)

Average on `Data.P1Hit`
![image](https://user-images.githubusercontent.com/5400332/48783891-791a5180-ecaf-11e8-8004-92f5ab5f15d0.png)

Conflict when both are viewed
![image](https://user-images.githubusercontent.com/5400332/48783932-8a635e00-ecaf-11e8-87ca-9b16cb9cb19a.png)

## Environment
- Browser: Firefox 63.0.1
- OS: Arch
- Database: MongoDB 4.1.5
- Hosted on Docker (metabase/metabase:latest)

## Reproduction steps
- Create a new question with a grouping on date (day)
- Add multiple Averages on different fields

**Comment by tlrobinson** [comment] 2018-11-20 17:50
Duplicate of #5393

**Closed by tlrobinson** 2018-11-20 17:50 UTC

**Comment by icosamuel** [comment] 2018-11-20 18:09
in his example the sum is not shown, which is different than overwriting a sibling. But maybe both problems will be fixed by the same PR...
