### ISSUE TITLE
Variable Filter Label No Longer Auto-populates

### ISSUE THREAD

**Issue by adriank-convoy** [metabase/metabase#9081] opened 2018-12-06 23:14 UTC
Description: The 'Filter label' box for variables in a raw SQL previously auto-populated based on the variable name. When we upgraded from 0.30.1 to 0.31.1 that no longer happens.

- Your browser and the version:  Chrome 70.0.3538.77
- Your operating system:  OS X 10
- Your databases: Redshift
- Metabase version:  0.31.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

1. Create a new raw SQL question
2. In the SQL, add a {{address_city}} variable
3. Expect the 'Filter label' box for the variable to be populated with AddressCity, but instead see 

![image](https://user-images.githubusercontent.com/40185566/49617482-9450b680-f969-11e8-8f63-8e683e4e8496.png)

Thanks for being part of the Metabase project!
-------

**Comment by walterl** [comment] 2020-03-11 18:55
Cannot reproduce. Closing this issue, since it was probably fixed through some other work, considering the time since this issue was opened.

**Closed by walterl** 2020-03-11 18:55 UTC
Labels: Priority:P3, Querying/Native, Querying/Parameters & Variables, Type:Bug
