### ISSUE TITLE
Permission on dashboard issue

### ISSUE THREAD

**Issue by OnFormLimited** [metabase/metabase#19044] opened 2021-11-19 12:37 UTC
**US**
Parity Recruitment
s.moore@parity.net

**The bug**
A dashboard has been moved from one collection (Management) to another (Our Analytics)- and now prevents a user (i.brown@parity.net) from accessing it entirely. The dashboard opens briefly, all components show the spinning circle then it goes straight to "Sorry, you don’t have permission to see that". Permissions have been tweaked and changed to no avail. The dashboard has been duplicated both back to it's original location and also to her personal collection. Both of these are inaccessible with the same message.

**Logs**
[metabaselog.txt](https://github.com/metabase/metabase/files/7570215/metabaselog.txt)

**To Reproduce**
Steps to reproduce the behaviour:
1. Logon
2. Click on 'Weekly Flash' shown at top (Our Analytics)
3. See error

**Expected behaviour**
The dashboard should open and all component questions display their relevant parts.

**Screenshots**
[](![image](https://user-images.githubusercontent.com/87531080/142622952-4731197f-6fa6-407d-850f-6d65c07c68cd.png))

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.53",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.12+7",
    "java.vendor": "Eclipse Foundation",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.12",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.12+7",
    "os.name": "Linux",
    "os.version": "4.14.219-164.354.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.9"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-10-21",
      "tag": "v1.41.1",
      "branch": "release-x.41.x",
      "hash": "68c0017"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Questions are still visible to the user, so not a show stopper - but **definitely** a major setback in time lost

**Comment by flamber** [comment] 2021-11-19 12:41
Duplicate of #15368

**Closed by flamber** 2021-11-19 12:41 UTC
Labels: Type:Bug, .Needs Triage

**Comment by OnFormLimited** [comment] 2021-11-19 12:46
Hi - why is this closed? I've looked at issue '15368 and it is different. Although this dashboard has a click behaviour addition (leading somewhere else) - it is **this** dashboard that just won't open (not the one being called)

Are you saying this is still the same issue? It looks as though '15368 is closed as well!

Please respond

**Comment by flamber** [comment] 2021-11-19 12:49
@OnFormLimited #15368 is closed because it's fixed and will be part of 1.41.3
Until then, remove all click behaviors referencing other dashboards/questions, which the user trying to view cannot access. Or give access, so the user can access all the referenced dashboards/questions.

**Comment by OnFormLimited** [comment] 2021-11-19 12:53
As explained: It is NOT the dashboard being called that is the issue.

It is the first dashboard that HAS the click behaviour on it that does not open at all.

Are you saying that any dashboard that has click behaviour on it will not open?? Because I though it was only those dashboards being CALLED by the click behaviour were the ones that would not open.

**Comment by flamber** [comment] 2021-11-19 12:55
@OnFormLimited Please re-read the description in #15368. It is the first dashboard.

**Comment by OnFormLimited** [comment] 2021-11-19 12:56
Hi - damn you're right. 
I removed the click behaviour off one of the duplicates and it works. Fair enough! Look forward to the update!
