### ISSUE TITLE
The time zone problem

### ISSUE THREAD

**Issue by futureio** [metabase/metabase#5902] opened 2017-09-06 03:20 UTC
I am back again.
The time zone problem seems to be a big problem plaguing me, In every part of the metabase.
For example I set up a mail to send it late for 8 hours (China),
And I found it the same thing with my filter, when I chose the September 5(day), the log shows the parameters of the September 4 16:00, etc.

I would like to know where to set up or change to fix these problems?

**Comment by futureio** [comment] 2017-09-06 03:50
For the first question, I found in the settings "REPORT TIMEZONE" (Maybe the default setting does not take effect)
Seems to be able to change the time I received the message when I chose Asia/Hong_Kong (from CST to HKT) (why did not there be Asia/Beijing or Asia/Shanghai?)
But this option still does not solve another problem

**Comment by sabino** [comment] 2017-09-06 10:02
Hey @futureio
Not sure if this can solve your problems but I had to change the timezone inside the Docker container.

Added this line to the Dockerfile

```
# change timezone
RUN sed -i 's/ZONE=.*/ZONE=Brazil\/East/g' /etc/localtime && \
    ln -sf /usr/share/zoneinfo/Brazil/East /etc/localtime
```

That way I could leave the default option within Metabase

**Comment by camsaul** [comment] 2017-09-06 23:02
@senior is this a duplicate of any of the other timezone bugs?

**Comment by senior** [comment] 2017-09-07 16:11
@futureio We have had a lot of timezone problems. The good news is I think I have either already fixed the problems you found or there are pull requests in-flight for fixing them. Either way, they are targeted for our next release, 0.26.0 and we have an RC release available [here](https://github.com/metabase/metabase/releases) with some of the fixes already. 

With regard to the report timezone. This is not configured by default, but if the databases you are using support setting their timezone, this is the best and easies way to get consistent timezone behavior. I wrote up some of that advice [here](https://github.com/metabase/metabase/blob/release-0.26.0/docs/troubleshooting-guide/timezones.md). Once 0.26.0 is released, that will go up on the website.

Emailing - You were seeing the confusing times here I'm guessing because you didn't have a report timezone set. The system would then use the JVM's timezone. I just verified in the code, if you specify a report timezone, it will use that to determine when to send a message. If you still find an issue after you set that report timezone, it's a bug.

Filters - There was probably a similar problem happening here that was happening with the email timezone. When no report timezone is specified, it uses the JVM timezone. What should happen, is if you specify a report timezone, it should use that for your filters. This wasn't working correctly before, but I fixed it in #5729. This has been release in 0.26.0 RC1 and can be tested out now.

Timezone ID - Currently we have a [list of timezones](https://github.com/metabase/metabase/blob/master/src/metabase/models/common.clj) we support in the code. Looking at the timezones IDs the JVM supports, I see Asia/Shanghai, but not Asia/Beijing. Have you used Beijing in configuring other software? It looks like all three cities are in the same timezone, i.e. UTC+08:00. Is the issue just that you had a hard time finding the right city for your timezone?

**Comment by futureio** [comment] 2017-09-13 06:56
@sabino  Configuring the Docker container is a bit more complicated, and my metabase is started in a real server. -,-

**Comment by futureio** [comment] 2017-09-14 06:28
@senior Thank you very much, I believe that the issue of time zone will be greatly improved through your changes.

I tried to do some code merge work (0.26.0 RC1 version && my local internationalized revision) and found some questions about the expired fields that could cause the problem to be unavailable without prompting. I decided to solve those questions first and then verify that the time zone is in effect. Look forward to the official version

The e-mail problem is mainly due to the default settings are not valid. 
Is jvm time zone configuration read from the `/etc/sysconfig/clock` file?
```bash
$ cat /etc/sysconfig/clock
ZONE = "Asia / Shanghai" # My default setting
```
Perhaps because it is not in the list, so it does not take effect.

Hope that the metabase is getting better and better.

**Comment by senior** [comment] 2017-09-14 14:02
Referencing `/etc/sysconfig/clock` leads me to think you're on CentOS? I think that's the right file, but your timezone seems off. My guess is it should be "Asia/Shanghai" with no spaces. By default the JVM will inherit the system timezone which could come from there. Another option is to add `-Duser.timezone=Asia/Shanghai` to your Metabase launch script, something like `java -Duser.timezone=Asia/Shanghai -jar metabase.jar`. By using -Duser.timezone, it will always use the one you specify and not whatever the system has configured.

**Comment by senior** [comment] 2017-10-02 16:25
@futureio are you still having issues? If not, could you close this issue?

**Closed** 2017-10-18 08:33 UTC
Labels: Timezones/Calendars
