### ISSUE TITLE
Unable to deploy metabase to the specified postgres schema

### ISSUE THREAD

**Issue by yinxulai** [metabase/metabase#48457] opened 2024-10-08 14:00 UTC
# Problem
I want to deploy the metabase to a specific schema, but it fails. I found this [code](https://github.com/metabase/metabase/blob/2ec9fdb1783d6028d64d87609c25c33e2ff14d7d/resources/migrations/initialization/metabase_postgres.sql#L5), which seems to be the main reason why the metabase cannot be deployed to the specified schema.

**Comment by paoliniluis** [comment] 2024-10-08 14:13
duplicate of https://github.com/metabase/metabase/issues/37836

**Closed by paoliniluis** 2024-10-08 14:13 UTC
