### ISSUE TITLE
upgrading container from 0.37 to 0.40 fails with Incorrect datetime value, I'm in Europe/Rome tz

### ISSUE THREAD

**Issue by dada216** [metabase/metabase#17488] opened 2021-08-17 13:08 UTC
**Describe the bug**
updating the metabase container from 0.37 to 0.40 fails with the following logs, which I believe are related to the [closed issue 12981](https://github.com/metabase/metabase/issues/12981
) .

what's my best course of action to avoid the error? I have a copy of the metabase db from before the upgrade and I've already tried to set the mysql (mariadb 10.5.8) timezone to '+00:00' but I get the same error.
for other reasons I would prefer NOT to set the server timezone to UTC or even worse America/Los_Angeles, I would actually prefer to even leave the mysql tz to SYSTEM if possible.

this is running in Centos8, under podman v 1.6.4, mariadb 10.5.8 hosted on the same machine, the server timezone is Europe/Rome.

**Logs**
full logs (db migration section): [metabase_upgrade_fail.txt](https://github.com/metabase/metabase/files/7000134/metabase_upgrade_fail.txt)

extract:
2021-08-17 12:50:05,141 ERROR changelog.ChangeSet :: Change Set migrations/000_migrations.yaml::282::camsaul failed.  Error: (conn=227) Incorrect datetime value: '2021-03-28 02:00:00' for column `metabase_app_040`.`task_history`.`started_at` at row 33466 [Failed SQL: ALTER TABLE task_history
MODIFY started_at timestamp(6) DEFAULT current_timestamp(6) NOT NULL]
2021-08-17 12:50:05,148 WARN metabase.util :: auto-retry metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__35464@160bb46b: Migration failed for change set migrations/000_migrations.yaml::282::camsaul:
     Reason: liquibase.exception.DatabaseException: (conn=227) Incorrect datetime value: '2021-03-28 02:00:00' for column `metabase_app_040`.`task_history`.`started_at` at row 33466 [Failed SQL: ALTER TABLE task_history
MODIFY started_at timestamp(6) DEFAULT current_timestamp(6) NOT NULL]

**Comment by flamber** [comment] 2021-08-17 13:26
Hi @dada216 

Go and remove the row 33466 from task_history before upgrading, then it should work.

It's going to be difficult to figure out which timezone setup you're using everywhere with so little information, but since this is the first time anyone is encountering this problem, then we will not create a fix for it (just like with #12981), since it would be many hours of development for something that can be fixed by removing one row in a non-essential table.

**Closed** 2021-08-17 13:32 UTC
Labels: Type:Bug, .Won't Fix

**Comment by dada216** [comment] 2021-08-17 13:51
I can't search by row number in mariadb 10.5.8 and that table does not allow for an easy way to determine what row that row number actually refers to.

I have a bunch of rows in task_history with started_at value corresponding to "2021-03-28 02:00:00", which is mentioned in the error, can I safely delete all of these?

**Comment by flamber** [comment] 2021-08-17 13:57
I would guess that the row references the ID column, but yes, getting rid of those tasks at `2021-03-28 02:00:00` would fix it.
The problem is that the started_at/ended_at columns were changed to include the timezone, but for some reason your setup had created some values, which basically doesn't exists, since they fall in between the DST.

**Comment by flamber** [comment] 2021-08-17 14:03
No, it's safe to truncate task_history. Just means there's no history to look back on in case you needed to debug something. It will fill up task_history with new data going forward.

**Comment by dada216** [comment] 2021-08-17 14:16
> No, it's safe to truncate task_history. Just means there's no history to look back on in case you needed to debug something. It will fill up task_history with new data going forward.

thought so, thanks for the confirmation.
btw amazing software.

**Comment by AikedeJongste** [comment] 2021-12-14 13:28
A query like this should fix it::

`delete from task_history where started_at >= '2021-03-28 02:00:00' AND started_at < '2021-03-28 03:00:00';`
