### ISSUE TITLE
ORA-01839: the date is not valid for the month indicated

### ISSUE THREAD

**Issue by Philippe-M** [metabase/metabase#16288] opened 2021-05-31 06:48 UTC
**Logs**
ORA-01839: le quantième n'est pas valide pour le mois indiqué 

**To Reproduce**
1. Create new question
![image](https://user-images.githubusercontent.com/4558101/120151256-57897180-c1ec-11eb-8d2a-5feaff4f1031.png)

SQL Version
```
SELECT *
FROM (SELECT "SDELIVERY"."SDHNUM_0" AS "SDHNUM_0", "SDELIVERY"."CREDAT_0" AS "CREDAT_0" FROM "SDELIVERY"
WHERE ("SDELIVERY"."CREDAT_0" >= trunc(SYSDATE, 'month')
   AND "SDELIVERY"."CREDAT_0" < trunc((CAST(SYSDATE AS timestamp) + numtoyminterval(1, 'month')), 'month'))) WHERE rownum <= 1048575
```

the CREDAT field is of type type/Date

**Information about your Metabase Installation:**
- Your browser and the version:  Firefox/88.0
- Your operating system: Linux
- Your databases: Oracle
- Metabase version: 0.39.3
- Metabase hosting environment: Jar-file
- Metabase internal database: Mysql

**Comment by flamber** [comment] 2021-05-31 09:29
Duplicate of #10072

**Closed by flamber** 2021-05-31 09:29 UTC
Labels: .Needs Triage, Type:Bug
