### ISSUE TITLE
Pulse reports getting half an hour delayed

### ISSUE THREAD

**Issue by dsmegha** [metabase/metabase#4398] opened 2017-02-17 03:47 UTC
I have set up a metabase pulse set up at 11.00 pm IST. I consistently get the pulse emails with a half an hour delay at (11.30 PM). This is the same scenario with all my pulses (I have about 15 set up). What could be causing this?

My browser : Chrome Version 55.0.2883.95 (64-bit)
OS : maxOS 10.12.2
Database : MySQL 5.7
Metabase version: 22.2
Metabase hosting environment: Elastic Beanstalk
Metabase internal database : MySQL

**Comment by tlrobinson** [comment] 2017-02-17 03:59
I'm guessing this has something to do with IST being 5:30 ahead of UTC.

You can set the server timezone by settings the `JAVA_TIMEZONE` environment variable on Elastic Beanstalk (maybe to [`Asia/Kolkata`](https://en.wikipedia.org/wiki/Asia/Kolkata)?)

**Comment by mazameli** [comment] 2017-03-27 17:01
If others are experiencing this issue, @tlrobinson's suggestion [seemed to work for at least one of our users](http://discourse.metabase.com/t/issue-with-metabase-urgent/1297).

**Comment by flamber** [comment] 2021-11-07 18:14
Closing, since without more details, then it's not possible to know what the problem is.
At a minimum "Diagnostic Info" from Admin > Troubleshooting.

**Closed by flamber** 2021-11-07 18:14 UTC
Labels: Type:Bug, Reporting/Pulses, Misc/Timezones
