### ISSUE TITLE
sorting broken if result contains null values

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#7176] opened 2018-03-21 20:56 UTC
- Your browser and the version: Chrome latest
- Your operating system: OSX latest
- Your databases: BigQuery
- Metabase version: 0.28.2
- Metabase internal database: MySQL

- *Repeatable steps to reproduce the issue*
If your result contains null values the sorting breaks with a null pointer exception. Tested with numerical columns.

**Comment by VikramTiwari** [comment] 2018-03-22 17:20
Related: https://github.com/metabase/metabase/issues/6615

**Comment by camsaul** [comment] 2018-04-10 00:11
@VikramTiwari if I understand correctly BigQuery itself throws a NullPointerException if you try to sort on a numeric column that contains `NULL` values. Any thoughts on the best way to write a SQL query that works around this?

**Comment by VikramTiwari** [comment] 2018-04-10 05:42
The way I normally approach `NULL` values is by `COALESCE`.

So if the query was `SUM(table.numerical_column)` it becomes `SUM(COALESCE(FLOAT(table.numerical_column), 0))`.

Of course, type inferencing (float/int/string) and then apply proper functions on top will help.

Also, this works for my use case since most of my values are numerical and representing `NULL` as `0` is fine since they both mean the same thing. But there might be a case where `NULL` is different than just `0`.

**Comment by camsaul** [comment] 2020-05-06 21:28
Duplicate of #6615

**Closed by camsaul** 2020-05-06 21:28 UTC
Labels: Database/BigQuery, Priority:P3, Type:Bug
