### ISSUE TITLE
Revision History Label

### ISSUE THREAD

**Issue by PetrSebik** [metabase/metabase#20614] opened 2022-02-18 07:06 UTC
**Describe the bug**
Inside the app, the labels on the dashboard and question which says "Edited x hours ago by you" do not take into account the timezones. I usually work in the UTC timezone, but right now I am in UTC+4 (and so is my OS) and every time I edit and save something it says "Edited 4 hours ago"

**To Reproduce**
I guess try to set a timezone in your OS to UTC+x and save something in the app

**Expected behavior**
it should say "Edited a few seconds ago by you"

**Screenshots**
![image](https://user-images.githubusercontent.com/50589449/154634108-f7b5c8ba-9d93-4392-ad2a-b226b807719c.png).

**Severity**
Minor

**Comment by flamber** [comment] 2022-02-18 08:12
Duplicate of #17829

**Closed by flamber** 2022-02-18 08:12 UTC
Labels: Type:Bug, .Needs Triage
