### ISSUE TITLE
Feature request: Better export filenames

### ISSUE THREAD

**Issue by nfm** [metabase/metabase#13346] opened 2020-10-02 00:51 UTC
**Is your feature request related to a problem? Please describe.**

When I export data from saved questions in Metabase, the filenames are not helpful. They're formatted like this: `query_result_2020-10-02T00 42 46.445Z.csv`.

If I export data from multiple questions within a short timespan, there's no way to differentiate between the files apart from opening them to figure out which is which. I end up with a series of files like this:

- `query_result_2020-10-02T00 42 46.445Z.csv`
- `query_result_2020-10-02T00 42 47.413Z.csv`
- `query_result_2020-10-02T00 43 01.313Z.csv`

Then I need to figure out which export is associated with which question by looking at them in all succession until I find the one I need next.

**Describe the solution you'd like**

For saved questions, using the question name as the export filename would be a better default. For example, if I have a saved question named "Accounts on discontinued plans", the export filename could be `Accounts on discontinued plans.csv`. or `Accounts on discontinued plans 2020-10-02T00 43 01.313Z.csv`.

There might be some need to normalize the question name to remove eg. spaces.

Unsaved questions would still need to be exported just using a timestamp as there'd be no additional information to include in the filename.

**Describe alternatives you've considered**

The only other option I can think of would be to prompt for the filename when exporting, but that doesn't seem necessary - the question name would be sufficient and a much better default than adding an additional step to the process.

**How important is this feature to you?**

Nice to have, but would reduce friction every time I export data from Metabase.

**Additional context**
nil

**Comment by flamber** [comment] 2020-10-02 08:32
Duplicate of #8280

**Closed by flamber** 2020-10-02 08:32 UTC
Labels: .Needs Triage, Type:New Feature
