### ISSUE TITLE
Custom question can not filter on complex custom expression

### ISSUE THREAD

**Issue by duc-ctm-jacobins-digital** [metabase/metabase#14046] opened 2020-12-11 03:52 UTC
**Describe the bug**
When I filter on custom expression, Metabase show error: `ERROR: column source.custom expression does not exist Position: 465`.
Note that this bug won't show up if the expression is `Sum([Tax])`, but will happen with `Sum([Tax]) + Sum([Subtotal])`.

**To Reproduce**
1. Go to `Custom question` > `Sample database` > `Orders`
2. Click on `Summarize` > `Custom expression` > `Sum([Tax]) + Sum([Subtotal])`, name = 'custom expression`
3. Summarize by `Product ID`
4. Click on icon Filter > `custom expression` > `greater than` > `100`
4. Click on `Visualize` > See error

**Expected behavior**
It should filter by the custom expression

**Screenshots**
![image](https://user-images.githubusercontent.com/70874681/101859377-32ea0080-3b9e-11eb-8643-f8740cf218a4.png)
![image](https://user-images.githubusercontent.com/70874681/101859393-3d0bff00-3b9e-11eb-933e-08024a5e6f83.png)

**Severity**
This bug is annoying. On dashboard I need to show reports like "Top 10 Product by growth", and if I can not filter on expression, user might see product with negative growth.

**Metabase Diagnostic Info**
I see same error on Metabase 0.37.3

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.19.0-12-amd64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.4 (Debian 12.4-1.pgdg100+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-10-26",
      "tag": "v0.37.0.2",
      "branch": "release-x.37.x",
      "hash": "ba7be09"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment] 2020-12-11 11:03
Duplicate of #12839

**Closed by flamber** 2020-12-11 11:03 UTC
Labels: .Needs Triage, Type:Bug
