### ISSUE TITLE
DbT Cloud Semantic Layer support

### ISSUE THREAD

**Issue by Guilherme-B** [metabase/metabase#48106] opened 2024-09-25 10:08 UTC
**Is your feature request related to a problem? Please describe.**
Currently Metabase supports Cube.dev. Whilst this is a great product, another popular Headless BI solution is the DbT Cloud Semantic Layer (former MetricFlow). Not supporting this solution forces a the usage of other tools only to support the Headless BI solution from DbT.

**Describe the solution you'd like**
Integration of the DbT Cloud Semantic Layer.

**Describe alternatives you've considered**
Using other products.

**How important is this feature to you?**
Highly important as this would allow unifying the Data Stack.

**Comment by ignacio-mb** [comment] 2024-10-18 20:03
Dupe of https://github.com/metabase/metabase/issues/48106

**Closed by ignacio-mb** 2024-10-18 20:03 UTC
Labels: Type:New Feature, .Needs Triage
