### ISSUE TITLE
Users created incorrectly from config.yml during an import into an uninitialized instance

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#44739] opened 2024-06-26 10:57 UTC
### Describe the bug

Users are not created correctly when config.yml is specificed, and an `import` command is run on an uninitialized instance.

### To Reproduce

1. Create an instance, add some contents, export it via the CLI
2. Create a config.yml with a user
3. Import the exported resources into a new instance with an uninitialized database, and also use `config.yml` to add new users in the same step. Something like:
`MB_CONFIG_FILE_PATH=config_with_user.yml java -jar metabase.jar import export_dir`

4.(!) The import runs, but the users are created incorrectly.
* the internal user is created with the incorrect id: 1 (seen this only on 1.49.18, not in 1.49.7)
* first_name and last_name are null
* is_superuser set to false (was true in the import)

5.(!) Start the instance, and see that the password of the imported user doesn't work

### Expected behavior

config.yml should be processed correctly even during the import phase

### Information about your Metabase installation

```JSON
Recent versions of 49 and 50 (1.49.18 and 1.50.7).
```

### Severity

Reported by a customer on v49

### Additional context

config.yml
```
version: 1
config:
  users:
    - first_name: a
      last_name: b
      password: some_password
      email: a@b.com
      is_superuser: true
```

Records in core_user after the import:
```
# [
#   {
#     "id": 1,
#     "email": "internal@metabase.com",
#     "first_name": null,
#     "last_name": null,
#     "password": "$2a$10$CP.liWQ6YXD5GEOLCWPQ1.b6DB0a3cibQMancy9Y/ArQ3crwKvDuS",
#     "password_salt": "b817b8c5-becc-4b01-92f9-99b2590dc623",
#     "date_joined": "2024-06-26 09:10:48.828406 +00:00",
#     "last_login": null,
#     "is_superuser": false,
#     "is_active": true,
#     "reset_token": null,
#     "reset_triggered": null,
#     "is_qbnewb": true,
#     "login_attributes": null,
#     "updated_at": "2024-06-26 09:10:48.828406 +00:00",
#     "sso_source": null,
#     "locale": null,
#     "is_datasetnewb": true,
#     "settings": "{\"last-acknowledged-version\":\"v1.49.18\"}",
#     "type": "personal"
#   },
#   {
#     "id": 2,
#     "email": "a@b.com",
#     "first_name": null,
#     "last_name": null,
#     "password": "$2a$10$WVAobp0p807JoNuJhQkFvOvXDOW.yoCpKFTdAtEKiYoYqGnXXKw/y",
#     "password_salt": "c16f7294-8db6-40d2-9797-f333f7e68bb1",
#     "date_joined": "2024-06-26 09:10:48.828406 +00:00",
#     "last_login": null,
#     "is_superuser": false,
#     "is_active": true,
#     "reset_token": null,
#     "reset_triggered": null,
#     "is_qbnewb": true,
#     "login_attributes": null,
#     "updated_at": "2024-06-26 09:10:48.828406 +00:00",
#     "sso_source": null,
#     "locale": null,
#     "is_datasetnewb": true,
#     "settings": "{\"last-acknowledged-version\":\"v1.49.18\"}",
#     "type": "personal"
#   }
# ]
```

**Comment by johnswanson** [comment] 2024-06-27 19:59
@zbodi74 I merged a PR to fix this, but wanted to elaborate a bit on the problem and its solution.

Fundamentally I think the problem is more that running `import` on a brand new Metabase App DB is broken. This is true even if you don't use a config file - the export contains the internal user, the new app DB doesn't, so we create the internal user in a broken state.

My fix doesn't actually change this - it just tells the user that they're trying to do something we don't support, and what to do instead. In this case, you could run `MB_CONFIG_FILE_PATH=config_with_user.yml java -jar metabase.jar` to launch Metabase and get everything initialized. Then, once the user has been created by *that* process, exit and run `java -jar metabase.jar import export_dir` to do the import before restarting Metabase.

**Comment by luizarakaki** [comment] 2024-07-05 18:16
@zbodi74 unfortunately, this isn't a supported use case. If this works, it was a fluke and we don't want to add a new way of starting a Metabase instance. There are other ways to achieve the same result, including simply creating an instance as usual and using the API to import content.

**Closed by luizarakaki** 2024-07-05 18:16 UTC
Labels: Type:Bug, Priority:P1, Operation/, Administration/People, .Team/AdminWebapp

**Comment by johnswanson** [comment] 2024-07-12 14:41
@zbodi74 I ended up making `import` [do the normal initialization procedure](https://github.com/metabase/metabase/pull/45390). Once that goes out you should now be able to run something like `MB_CONFIG_FILE=... java -jar metabase.jar import /path/to/export` to initialize the instance again. Sorry for the confusion here!
