### ISSUE TITLE
Filtering of BigQuery tables in a dataset

### ISSUE THREAD

**Issue by paulbes** [metabase/metabase#49277] opened 2024-10-29 09:52 UTC
**Is your feature request related to a problem? Please describe.**
The way we integrate BigQuery datasets with Metabase is through service accounts. Where those service accounts frequently only have access to some of the tables in the dataset. As a result, the logs are frequently being spammed with warnings about not having access, approximately 50% of all invocations from Metabase to BigQuery fail on this scenario.

We do not think it is realistic to ask our users to tailor all tables in a dataset for use with Metabase, e.g., they should all be accessible; they might want to use those tables in different contexts.  Furthermore, when we started building our solution we did not recommend that our users make all tables in a dataset accessible for the service account. So, if we were to move to this pattern now, where all tables in a dataset should be open, we would need to ask our users to rebuild all their questions and dashboards, since there is no easy way to change the data source.

**Describe the solution you'd like**
We would like to be able to provide a filter or list of which tables in a BigQuery dataset Metabase tries to search and index

**Describe alternatives you've considered**
Just continue as is, with a lot of warnings or errors in the logs that are expected, and that might impact performance. As noted in the previous description, we have also considered asking our users to make all tables in a dataset accessible, but do not really think this is a good recommendation. 

**How important is this feature to you?**
Hard to set a level of importance on this, as it might only have a small performance impact, and the logs can always be filtered. However, in the latter case of filtering, we might be concealing real errors. Overall, it seems reasonable that the BigQuery driver should support this type of filtering of tables, and that it is more correct behavior.

**Comment by paoliniluis** [comment] 2024-10-29 12:58
I believe this is a duplicate of https://github.com/metabase/metabase/issues/5500

**Closed by paoliniluis** 2024-10-29 12:58 UTC
Labels: Type:New Feature, .Needs Triage
