### ISSUE TITLE
Serialization fails when there's a question on a personal collection using a metric or segment

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#20755] opened 2022-02-25 22:01 UTC
**Describe the bug**
When a question in a personal collection uses a metric or a segment the serialization process will fail as the dependency.yml includes these objects, but as things in personal collections aren't moved, then the process cannot find them.

**Logs**
<details>
2022-02-25 21:53:07,648 WARN serialization.names :: #error {
 :cause Value does not match schema: {:card (not (integer? nil))}
 :data {:type :schema.core/error, :value {:collection nil, :card nil}, :error {:card (not (integer? nil))}}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message Can't resolve collection, card in fully qualified name /collections/root/collections/a b%27s Personal Collection/cards/Products%2C Filtered by blabla
   :data {:fully-qualified-name /collections/root/collections/a b%27s Personal Collection/cards/Products%2C Filtered by blabla, :resolve-name-failed? true, :context {:collection nil, :card nil}}
   :at [metabase_enterprise.serialization.names$fully_qualified_name__GT_context invokeStatic names.clj 325]}
  {:type clojure.lang.ExceptionInfo
   :message Value does not match schema: {:card (not (integer? nil))}
   :data {:type :schema.core/error, :value {:collection nil, :card nil}, :error {:card (not (integer? nil))}}
   :at [metabase.util.schema$schema_core_validator$fn__18071 invoke schema.clj 29]}]
 :trace
 [[metabase.util.schema$schema_core_validator$fn__18071 invoke schema.clj 29]
  [schema.core$validate invokeStatic core.clj 164]
  [schema.core$validate invoke core.clj 159]
  [metabase_enterprise.serialization.names$fully_qualified_name__GT_context invokeStatic names.clj 321]
  [metabase_enterprise.serialization.names$fully_qualified_name__GT_context invoke names.clj 299]
  [clojure.core$comp$fn__5825 invoke core.clj 2573]
  [metabase_enterprise.serialization.load$load_dependencies$iter__83026__83030$fn__83031$fn__83032 invoke load.clj 786]
  [metabase_enterprise.serialization.load$load_dependencies$iter__83026__83030$fn__83031 invoke load.clj 785]
  [clojure.lang.LazySeq sval LazySeq.java 42]
  [clojure.lang.LazySeq seq LazySeq.java 51]
  [clojure.lang.RT seq RT.java 535]
  [clojure.core$seq__5419 invokeStatic core.clj 139]
  [clojure.core$map_indexed$mapi__8571$fn__8572 invoke core.clj 7303]
  [clojure.lang.LazySeq sval LazySeq.java 42]
  [clojure.lang.LazySeq seq LazySeq.java 51]
  [clojure.lang.RT seq RT.java 535]
  [clojure.core$seq__5419 invokeStatic core.clj 139]
  [clojure.core.protocols$seq_reduce invokeStatic protocols.clj 24]
  [clojure.core.protocols$fn__8168 invokeStatic protocols.clj 75]
  [clojure.core.protocols$fn__8168 invoke protocols.clj 75]
  [clojure.core.protocols$fn__8110$G__8105__8123 invoke protocols.clj 13]
  [clojure.core$reduce invokeStatic core.clj 6830]
  [clojure.core$group_by invokeStatic core.clj 7148]
  [clojure.core$group_by invoke core.clj 7148]
  [metabase_enterprise.serialization.upsert$group_by_action invokeStatic upsert.clj 109]
  [metabase_enterprise.serialization.upsert$group_by_action invoke upsert.clj 100]
  [metabase_enterprise.serialization.upsert$maybe_upsert_many_BANG_ invokeStatic upsert.clj 133]
  [metabase_enterprise.serialization.upsert$maybe_upsert_many_BANG_ invoke upsert.clj 119]
  [metabase_enterprise.serialization.load$load_dependencies invokeStatic load.clj 784]
  [metabase_enterprise.serialization.load$load_dependencies invoke load.clj 776]
  [metabase_enterprise.serialization.cmd$fn__86713$load__86718$fn__86719 invoke cmd.clj 56]
  [metabase_enterprise.serialization.cmd$fn__86713$load__86718 invoke cmd.clj 39]
  [clojure.lang.Var invoke Var.java 388]
  [metabase.cmd$load invokeStatic cmd.clj 149]
  [metabase.cmd$load doInvoke cmd.clj 140]
  [clojure.lang.RestFn invoke RestFn.java 423]
  [metabase.cmd$load invokeStatic cmd.clj 144]
  [metabase.cmd$load invoke cmd.clj 140]
  [clojure.lang.AFn applyToHelper AFn.java 154]
  [clojure.lang.RestFn applyTo RestFn.java 132]
  [clojure.core$apply invokeStatic core.clj 667]
  [clojure.core$apply invoke core.clj 662]
  [metabase.cmd$run_cmd$fn__83228 invoke cmd.clj 190]
  [metabase.cmd$run_cmd invokeStatic cmd.clj 190]
  [metabase.cmd$run_cmd invoke cmd.clj 186]
  [clojure.lang.Var invoke Var.java 388]
  [metabase.core$run_cmd invokeStatic core.clj 141]
  [metabase.core$run_cmd invoke core.clj 139]
  [metabase.core$_main invokeStatic core.clj 163]
  [metabase.core$_main doInvoke core.clj 158]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [metabase.core main nil -1]]}
2022-02-25 21:53:07,653 ERROR serialization.load :: Error loading dependencies: reference to an unknown entity /collections/root/collections/a b%27s Personal Collection/cards/Products%2C Filtered by blabla
</details>

**To Reproduce**
1) Create a metric or a segment
2) Add this metric or segment into a question and save the question in a personal collection
3) dump and load, see the error

**Expected behavior**
Make the process to finish correctly

**Screenshots**
NA

**Information about your Metabase Installation:**
- Your operating system: Ubuntu 21.10
- Your databases: H2
- Metabase version: 1.41.2
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
P1'ish

**Additional context**
🙏🏻 we have to make the process more robust, with flags (like include/not things in personal collections, etc)

**Comment by flamber** [comment] 2022-02-28 10:35
It is definitely not a P1, and I cannot reproduce on 1.42.1

**Comment by paoliniluis** [comment] 2022-02-28 14:06
Please try again, I was able to reproduce once again this error:
- Set up source and destination instances
- on the source, create a metric or segment on any table in the H2 database
- create a question that uses the metric or segment and save the question on the personal collection
- dump and load (in fact you will be able to see the error in the dependency.yaml which is generated with a question in the personal collection)

### A sample segment
![image](https://user-images.githubusercontent.com/1711649/155995868-17ef40e6-e454-4263-8e9b-85a767a8966a.png)

### Serialization and a `cat` of the dependencies.yaml
![image](https://user-images.githubusercontent.com/1711649/155996215-29c0fa55-557d-49f2-85c6-b3a41a54b921.png)

### Load
<details>
2022-02-28 14:04:31,724 INFO serialization.cmd :: BEGIN LOAD from /target/ with context {:mode :skip, :on-error :continue}
2022-02-28 14:04:31,771 INFO serialization.upsert :: Database "Sample Database" (ID 1) already exists -- skipping
2022-02-28 14:04:31,801 INFO serialization.upsert :: Table "PEOPLE" (ID 3) already exists -- skipping
2022-02-28 14:04:31,802 INFO serialization.upsert :: Table "REVIEWS" (ID 4) already exists -- skipping
2022-02-28 14:04:31,803 INFO serialization.upsert :: Table "PRODUCTS" (ID 1) already exists -- skipping
2022-02-28 14:04:31,804 INFO serialization.upsert :: Table "ORDERS" (ID 2) already exists -- skipping
2022-02-28 14:04:31,909 INFO serialization.upsert :: Field "LONGITUDE" (ID 12) already exists -- skipping
2022-02-28 14:04:31,909 INFO serialization.upsert :: Field "CITY" (ID 21) already exists -- skipping
2022-02-28 14:04:31,910 INFO serialization.upsert :: Field "PASSWORD" (ID 11) already exists -- skipping
2022-02-28 14:04:31,911 INFO serialization.upsert :: Field "BIRTH_DATE" (ID 16) already exists -- skipping
2022-02-28 14:04:31,912 INFO serialization.upsert :: Field "STATE" (ID 17) already exists -- skipping
2022-02-28 14:04:31,912 INFO serialization.upsert :: Field "EMAIL" (ID 15) already exists -- skipping
2022-02-28 14:04:31,913 INFO serialization.upsert :: Field "ZIP" (ID 20) already exists -- skipping
2022-02-28 14:04:31,914 INFO serialization.upsert :: Field "CREATED_AT" (ID 10) already exists -- skipping
2022-02-28 14:04:31,916 INFO serialization.upsert :: Field "ADDRESS" (ID 13) already exists -- skipping
2022-02-28 14:04:31,916 INFO serialization.upsert :: Field "NAME" (ID 14) already exists -- skipping
2022-02-28 14:04:31,917 INFO serialization.upsert :: Field "LATITUDE" (ID 19) already exists -- skipping
2022-02-28 14:04:31,917 INFO serialization.upsert :: Field "SOURCE" (ID 18) already exists -- skipping
2022-02-28 14:04:31,918 INFO serialization.upsert :: Field "ID" (ID 22) already exists -- skipping
2022-02-28 14:04:31,953 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:31,954 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:31,954 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:31,955 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:31,956 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:31,956 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:31,957 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:31,957 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:31,958 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:31,958 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:31,959 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:31,960 INFO serialization.upsert :: FieldValues 3 already exists -- skipping
2022-02-28 14:04:31,960 INFO serialization.upsert :: FieldValues 2 already exists -- skipping
2022-02-28 14:04:31,962 INFO driver.impl :: Initializing driver :sql...
2022-02-28 14:04:31,963 INFO driver.impl :: Initializing driver :sql-jdbc...
2022-02-28 14:04:31,963 INFO driver.impl :: Initializing driver :postgres...
2022-02-28 14:04:32,035 INFO serialization.upsert :: Field "RATING" (ID 31) already exists -- skipping
2022-02-28 14:04:32,036 INFO serialization.upsert :: Field "CREATED_AT" (ID 34) already exists -- skipping
2022-02-28 14:04:32,037 INFO serialization.upsert :: Field "REVIEWER" (ID 35) already exists -- skipping
2022-02-28 14:04:32,037 INFO serialization.upsert :: Field "ID" (ID 36) already exists -- skipping
2022-02-28 14:04:32,038 INFO serialization.upsert :: Field "BODY" (ID 32) already exists -- skipping
2022-02-28 14:04:32,051 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,052 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,052 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,053 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,054 INFO serialization.upsert :: FieldValues 5 already exists -- skipping
2022-02-28 14:04:32,109 INFO serialization.upsert :: Field "RATING" (ID 28) already exists -- skipping
2022-02-28 14:04:32,109 INFO serialization.upsert :: Field "PRICE" (ID 23) already exists -- skipping
2022-02-28 14:04:32,110 INFO serialization.upsert :: Field "VENDOR" (ID 25) already exists -- skipping
2022-02-28 14:04:32,111 INFO serialization.upsert :: Field "CATEGORY" (ID 26) already exists -- skipping
2022-02-28 14:04:32,112 INFO serialization.upsert :: Field "CREATED_AT" (ID 29) already exists -- skipping
2022-02-28 14:04:32,113 INFO serialization.upsert :: Field "EAN" (ID 24) already exists -- skipping
2022-02-28 14:04:32,114 INFO serialization.upsert :: Field "TITLE" (ID 27) already exists -- skipping
2022-02-28 14:04:32,115 INFO serialization.upsert :: Field "ID" (ID 30) already exists -- skipping
2022-02-28 14:04:32,133 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,134 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,135 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,135 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,136 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,137 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,137 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,138 INFO serialization.upsert :: FieldValues 4 already exists -- skipping
2022-02-28 14:04:32,192 INFO serialization.upsert :: Field "TOTAL" (ID 7) already exists -- skipping
2022-02-28 14:04:32,192 INFO serialization.upsert :: Field "DISCOUNT" (ID 1) already exists -- skipping
2022-02-28 14:04:32,194 INFO serialization.upsert :: Field "QUANTITY" (ID 2) already exists -- skipping
2022-02-28 14:04:32,195 INFO serialization.upsert :: Field "SUBTOTAL" (ID 6) already exists -- skipping
2022-02-28 14:04:32,195 INFO serialization.upsert :: Field "TAX" (ID 8) already exists -- skipping
2022-02-28 14:04:32,196 INFO serialization.upsert :: Field "CREATED_AT" (ID 4) already exists -- skipping
2022-02-28 14:04:32,196 INFO serialization.upsert :: Field "ID" (ID 9) already exists -- skipping
2022-02-28 14:04:32,209 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,210 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,211 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,211 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,212 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,213 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,213 INFO serialization.upsert :: FieldValues 1 already exists -- skipping
2022-02-28 14:04:32,262 INFO serialization.upsert :: Inserting Segment "Only_people_from_CA"
2022-02-28 14:04:32,292 INFO serialization.upsert :: Field "PRODUCT_ID" (ID 33) already exists -- skipping
2022-02-28 14:04:32,295 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,320 INFO serialization.upsert :: Field "USER_ID" (ID 3) already exists -- skipping
2022-02-28 14:04:32,320 INFO serialization.upsert :: Field "PRODUCT_ID" (ID 5) already exists -- skipping
2022-02-28 14:04:32,324 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:32,324 INFO serialization.upsert :: Inserting FieldValues
2022-02-28 14:04:33,806 WARN serialization.names :: #error {
 :cause Value does not match schema: {:card (not (integer? nil))}
 :data {:type :schema.core/error, :value {:collection 1, :card nil}, :error {:card (not (integer? nil))}}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message Can't resolve collection, card in fully qualified name /collections/root/collections/a b%27s Personal Collection/cards/People%2C Filtered by Only_people_from_CA
   :data {:fully-qualified-name /collections/root/collections/a b%27s Personal Collection/cards/People%2C Filtered by Only_people_from_CA, :resolve-name-failed? true, :context {:collection 1, :card nil}}
   :at [metabase_enterprise.serialization.names$fully_qualified_name__GT_context invokeStatic names.clj 325]}
  {:type clojure.lang.ExceptionInfo
   :message Value does not match schema: {:card (not (integer? nil))}
   :data {:type :schema.core/error, :value {:collection 1, :card nil}, :error {:card (not (integer? nil))}}
   :at [metabase.util.schema$schema_core_validator$fn__18071 invoke schema.clj 29]}]
 :trace
 [[metabase.util.schema$schema_core_validator$fn__18071 invoke schema.clj 29]
  [schema.core$validate invokeStatic core.clj 164]
  [schema.core$validate invoke core.clj 159]
  [metabase_enterprise.serialization.names$fully_qualified_name__GT_context invokeStatic names.clj 321]
  [metabase_enterprise.serialization.names$fully_qualified_name__GT_context invoke names.clj 299]
  [clojure.core$comp$fn__5825 invoke core.clj 2573]
  [metabase_enterprise.serialization.load$load_dependencies$iter__83026__83030$fn__83031$fn__83032 invoke load.clj 786]
  [metabase_enterprise.serialization.load$load_dependencies$iter__83026__83030$fn__83031 invoke load.clj 785]
  [clojure.lang.LazySeq sval LazySeq.java 42]
  [clojure.lang.LazySeq seq LazySeq.java 51]
  [clojure.lang.RT seq RT.java 535]
  [clojure.core$seq__5419 invokeStatic core.clj 139]
  [clojure.core$map_indexed$mapi__8571$fn__8572 invoke core.clj 7303]
  [clojure.lang.LazySeq sval LazySeq.java 42]
  [clojure.lang.LazySeq seq LazySeq.java 51]
  [clojure.lang.RT seq RT.java 535]
  [clojure.core$seq__5419 invokeStatic core.clj 139]
  [clojure.core.protocols$seq_reduce invokeStatic protocols.clj 24]
  [clojure.core.protocols$fn__8168 invokeStatic protocols.clj 75]
  [clojure.core.protocols$fn__8168 invoke protocols.clj 75]
  [clojure.core.protocols$fn__8110$G__8105__8123 invoke protocols.clj 13]
  [clojure.core$reduce invokeStatic core.clj 6830]
  [clojure.core$group_by invokeStatic core.clj 7148]
  [clojure.core$group_by invoke core.clj 7148]
  [metabase_enterprise.serialization.upsert$group_by_action invokeStatic upsert.clj 109]
  [metabase_enterprise.serialization.upsert$group_by_action invoke upsert.clj 100]
  [metabase_enterprise.serialization.upsert$maybe_upsert_many_BANG_ invokeStatic upsert.clj 133]
  [metabase_enterprise.serialization.upsert$maybe_upsert_many_BANG_ invoke upsert.clj 119]
  [metabase_enterprise.serialization.load$load_dependencies invokeStatic load.clj 784]
  [metabase_enterprise.serialization.load$load_dependencies invoke load.clj 776]
  [metabase_enterprise.serialization.cmd$fn__86713$load__86718$fn__86719 invoke cmd.clj 56]
  [metabase_enterprise.serialization.cmd$fn__86713$load__86718 invoke cmd.clj 39]
  [clojure.lang.Var invoke Var.java 388]
  [metabase.cmd$load invokeStatic cmd.clj 149]
  [metabase.cmd$load doInvoke cmd.clj 140]
  [clojure.lang.RestFn invoke RestFn.java 423]
  [metabase.cmd$load invokeStatic cmd.clj 144]
  [metabase.cmd$load invoke cmd.clj 140]
  [clojure.lang.AFn applyToHelper AFn.java 154]
  [clojure.lang.RestFn applyTo RestFn.java 132]
  [clojure.core$apply invokeStatic core.clj 667]
  [clojure.core$apply invoke core.clj 662]
  [metabase.cmd$run_cmd$fn__83228 invoke cmd.clj 190]
  [metabase.cmd$run_cmd invokeStatic cmd.clj 190]
  [metabase.cmd$run_cmd invoke cmd.clj 186]
  [clojure.lang.Var invoke Var.java 388]
  [metabase.core$run_cmd invokeStatic core.clj 141]
  [metabase.core$run_cmd invoke core.clj 139]
  [metabase.core$_main invokeStatic core.clj 163]
  [metabase.core$_main doInvoke core.clj 158]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [metabase.core main nil -1]]}
2022-02-28 14:04:33,819 ERROR serialization.load :: Error loading dependencies: reference to an unknown entity /collections/root/collections/a b%27s Personal Collection/cards/People%2C Filtered by Only_people_from_CA
2022-02-28 14:04:33,824 INFO serialization.upsert :: Inserting Dependency
2022-02-28 14:04:33,835 ERROR serialization.upsert :: Error inserting metabase.models.dependency.DependencyInstance@8b4c8e8e: Assert failed: (map? row-map)
java.lang.AssertionError: Assert failed: (map? row-map)
	at toucan.db$insert_BANG_.invokeStatic(db.clj:597)
	at toucan.db$insert_BANG_.invoke(db.clj:597)
	at metabase_enterprise.serialization.upsert$insert_many_individually_BANG_$iter__54070__54074$fn__54075$fn__54076$fn__54077.invoke(upsert.clj:85)
	at metabase_enterprise.serialization.upsert$insert_many_individually_BANG_$iter__54070__54074$fn__54075$fn__54076.invoke(upsert.clj:83)
	at metabase_enterprise.serialization.upsert$insert_many_individually_BANG_$iter__54070__54074$fn__54075.invoke(upsert.clj:80)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5419.invokeStatic(core.clj:139)
	at clojure.core$map$fn__5884.invoke(core.clj:2750)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5419.invokeStatic(core.clj:139)
	at clojure.core$map$fn__5888.invoke(core.clj:2761)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:58)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5419.invokeStatic(core.clj:139)
	at clojure.core$concat$cat__5512$fn__5513.invoke(core.clj:736)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5419.invokeStatic(core.clj:139)
	at clojure.core$sort.invokeStatic(core.clj:3101)
	at clojure.core$sort_by.invokeStatic(core.clj:3107)
	at clojure.core$sort_by.invokeStatic(core.clj:3107)
	at clojure.core$sort_by.invoke(core.clj:3107)
	at metabase_enterprise.serialization.upsert$maybe_upsert_many_BANG_.invokeStatic(upsert.clj:156)
	at metabase_enterprise.serialization.upsert$maybe_upsert_many_BANG_.invoke(upsert.clj:119)
	at metabase_enterprise.serialization.load$load_dependencies.invokeStatic(load.clj:784)
	at metabase_enterprise.serialization.load$load_dependencies.invoke(load.clj:776)
	at metabase_enterprise.serialization.cmd$fn__86713$load__86718$fn__86719.invoke(cmd.clj:56)
	at metabase_enterprise.serialization.cmd$fn__86713$load__86718.invoke(cmd.clj:39)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.cmd$load.invokeStatic(cmd.clj:149)
	at metabase.cmd$load.doInvoke(cmd.clj:140)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at metabase.cmd$load.invokeStatic(cmd.clj:144)
	at metabase.cmd$load.invoke(cmd.clj:140)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.cmd$run_cmd$fn__83228.invoke(cmd.clj:190)
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:190)
	at metabase.cmd$run_cmd.invoke(cmd.clj:186)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.core$run_cmd.invokeStatic(core.clj:141)
	at metabase.core$run_cmd.invoke(core.clj:139)
	at metabase.core$_main.invokeStatic(core.clj:163)
	at metabase.core$_main.doInvoke(core.clj:158)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.core.main(Unknown Source)
2022-02-28 14:04:33,843 INFO serialization.cmd :: END LOAD from /target/ with context {:mode :skip, :on-error :continue}
</details>

**Comment by flamber** [comment] 2022-03-01 13:59
Yes, it's creating a reference in `dependencies.yaml` on dump, which can be easily removed before load.

I can only make it fail if the segment/metric is only used by a card, which is not included (e.g. Personal Collection).
If I have another card somewhere that also uses the segment/metric, then it will not fail.

**Comment by flamber** [comment] 2022-07-27 07:47
Is likely irrelevant since #24283.

**Comment by camsaul** [comment] 2023-03-06 17:50
This sounds like it's related to SerDes v1, so once we move to SerDes v2 completely we can close this either way

**Comment by camsaul** [comment] 2023-03-06 17:50
After looking into this more this is indeed resolved by #24283

**Closed by camsaul** 2023-03-06 17:50 UTC
Labels: Type:Bug, Priority:P3, Administration/Metrics & Segments, .Backend, .Cannot Cypress Test, Operation/Serialization
