### ISSUE TITLE
Metabase alerts frequency

### ISSUE THREAD

**Issue by satishvarmadandu** [metabase/metabase#8732] opened 2018-10-19 14:17 UTC
Creating a new issue on alerts frequency as couldn't able to find any open issue.

Started using Metabase and so far its great. One of the big blocker is Alerts frequency. At best, we could able to set only hourly alerts. Is there any way to trigger alerts every "few mins" like 5 mins. This is a major blocker because hourly alerts frequency is too long. Or is there any work around ?

**Comment by jornh** [comment] 2018-10-19 19:10
Duplicate of #6648 

Found through this search: 
https://github.com/metabase/metabase/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+alerts

If you agree please 👍 that other issue and close this one.

**Comment by satishvarmadandu** [comment] 2018-10-19 23:20
Done. Is this in the roadmoa ?

**Closed** 2018-10-19 23:21 UTC

**Comment by jornh** [comment] 2018-10-20 02:33
For my understanding of how to judge priorities see https://github.com/metabase/metabase/issues/1173#issuecomment-413793410

I hope that helps in doing your own estimates from there.
