### ISSUE TITLE
Map editing problem

### ISSUE THREAD

**Issue by ggentili** [metabase/metabase#12390] opened 2020-04-24 17:54 UTC
**Describe the bug**
We have a problem in editing of dashboard with maps. Several times when you resize a map, the map remain attached to the pointer and you are stuck and you can't save the modified dashboard.

**To Reproduce**
See the video here:  https://youtu.be/d5ldvSY28c8  at  0:50

**Expected behavior**
The map resized.

**Screenshots**
See the video

**Information about your Metabase Installation:**
- Your browser : Chrome
- Your operating system: OS X  e Windows 10
- Your databases: Postgres
- Metabase version: v0.35.2

**Severity**
blocking the use of maps

**Comment by flamber** [comment] 2020-04-24 17:59
Hi @ggentili 
Duplicate of #12249 - fixed by #12307 - upgrade to 0.35.3

**Closed by flamber** 2020-04-24 17:59 UTC
Labels: .Duplicate
