### ISSUE TITLE
Hope to increase the database grouping function

### ISSUE THREAD

**Issue by annisun** [metabase/metabase#11472] opened 2019-12-09 08:32 UTC
it would be better if you could add a grouping function to the position where the database is displayed,
so that different business groupings can be displayed more clearly, business personnel can quickly locate the business groupings.
![DeepinScrot-3059](https://user-images.githubusercontent.com/26518100/70419950-887a6180-1aa1-11ea-93dd-d5e7c87048d6.png)

**Comment by flamber** [comment] 2019-12-09 16:33
Hi @annisun 
Sounds like a duplicate of #9518/#1615. If you agree, then please close this and upvote the other :+1:

**Comment by mazameli** [comment] 2019-12-09 17:31
Closing as duplicate of #9518 or #1615

**Closed by mazameli** 2019-12-09 17:31 UTC
Labels: .Duplicate
