### ISSUE TITLE
Custom column disappears from select list after non-custom column is appended to select list

### ISSUE THREAD

**Issue by nefremov** [metabase/metabase#15716] opened 2021-04-21 16:43 UTC
**Describe the bug**
Custom column disappears from select list after not-custom column is appended to select list

**Logs**
no events in console

**To Reproduce**
1. Create custom question, add one table as data source
2. Select some columns from the table
3. Create custom column (e.g. =length[some text column])
4. Visualize the question as table. Custom column exist in table
5. Switch to edit mode
6. Add any additional column from the table column list (or remove)
7. Visualize the question. Custom column disappears from the view.

**Expected behavior**
Custom column continue to be visible

**Screenshots**

**Information about your Metabase Installation:**
You're on version v1.39.0.1
Built on 2021-04-20
Branch: release-x.39.x
Hash: 47bb5f2

- Your browser and the version: Chrome 90.0.4430.72 (Official Build) (64-bit)
- Your operating system:
Edition	Windows 10 Pro
Version	20H2
Installed on	‎24.‎07.‎2020
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0

- Your databases: Postgres
- Metabase version: v1.39.0.1
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: Postgres

**Comment by flamber** [comment] 2021-04-21 16:53
Duplicate of #12395

**Closed by flamber** 2021-04-21 16:53 UTC
Labels: .Needs Triage, Type:Bug
