### ISSUE TITLE
Code runs in phpMyAdmin but not in Metabase

### ISSUE THREAD

**Issue by petar777** [metabase/metabase#7378] opened 2018-04-19 09:24 UTC
Hey there guys!

I am experiencing a problem that I cannot solve for a really long time. I have a MySQL database running on a MySQL 5.0.95 server. This database is attached both to phpMyAdmin and Metabase. The problem is the following- I have cyrilic symbols in some of the columns and they are represented in a wrong way which makes pretty much no sense. For example the query returns 'Ð’Ð¸Ð²Ð°ÐºÐ¾Ð¼' but it should look like 'Виваком'. (You can paste it here https://2cyr.com/decode/ and you will see that it turns it to 'Виваком'). The collation of the database is utf8_general_ci. When I run the following code in phpMyAdmin:
`SET character_set_results = 'latin1';`
`select * from sample_table`
I change the character set and the resulting query returns everything as I want it. However, I cannot run the above mentioned line in Metabase. It returns the following error once I run it:
`com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select * from sample_table' at line 3`
Can anyone please help me on that issue because I have tried numerous ways to avoid this problem but none of them help and it is of key importance to my project. I suppose that I might be missing something so I would really appreciate every suggestion. All I want is to convert the column to the proper encoding no matter how I do it.

**Comment by salsakran** [comment] 2018-04-20 03:43
dupe of #4050

**Comment by salsakran** [comment] 2018-04-20 03:43
@petar777 we don't support multi-statements in the native query editor for now.

**Closed by salsakran** 2018-04-20 03:43 UTC
