### ISSUE TITLE
Slow loading in custom query

### ISSUE THREAD

**Issue by iwaffles** [metabase/metabase#3407] opened 2016-09-27 19:45 UTC
**Browser:** Chrome Version 53.0.2785.116 (64-bit)
**Metabase:** version: 0.19.3
**My OS:** OS X 10.11.6
**Database:** Postgres
**Hosting:** AWS Elastic Beanstalk (t2.micro)
**Internal DB:** Postgres
### Issue
1. Creating a new question and running the query. Seeing it load fairly slow.
2. Add a variable, set the variable and re-run the question. Loads much slower and sometimes indefinitely. Clicking cancel will cause it to wait a second, then stop. All data is loaded below after cancelling. 

It seems that there might be a client side issue (just a guess). Below is a screenshot of what I've found in the console in Chrome:
![image](https://cloud.githubusercontent.com/assets/7333/18888669/2980bada-84ae-11e6-8bcd-f9770d86aed0.png)
### Expected Behavior

Expect the query to load quickly and without requiring the user to click on "cancel" when a query is running. The query is written in SQL (not using the visual select options tool) and has one variable. It also has one join.
### Query:

```
select * from A
join B on B.a_id = a.id
where a.state = 1
and a.show_id={{show_id}};
```
### Additional Screenshots

![image](https://cloud.githubusercontent.com/assets/7333/18889529/3b0d74ce-84b2-11e6-9f0a-df9e44368b62.png)
![image](https://cloud.githubusercontent.com/assets/7333/18889539/4310ebce-84b2-11e6-866f-f3e79cae2974.png)
![image](https://cloud.githubusercontent.com/assets/7333/18889560/4f9816e2-84b2-11e6-849e-e06ff0834ef4.png)

**Comment by hugocar** [comment] 2016-09-27 21:30
I've been using custom queries with variables without performances issues.

Does the query run faster on another tool or the command line console ?
If not, maybe a solution would be to check the indexes on the tables A and B. 
You could run EXPLAIN on the query to make the indexes are used.

**Comment by iwaffles** [comment] 2016-09-27 21:33
I don't believe that it's necessarily the query that's taking a long time, but perhaps something in the browser. When I click cancel on the request, it seems to load almost immediately.

**Comment by hugocar** [comment] 2016-09-27 21:40
Someone of the metabase team could confirm this : I am speculating that when you hit "cancel" the data shown might be partial. If the results were streamed, you received a portion of the results and hitting "cancel" shows that portion. Which should be considered a bug.

**Comment by iwaffles** [comment] 2016-10-03 18:48
Not entirely sure if this is related, and the query doesn't seem to take a long time when run directly against the db. However, when the quantity of columns doesn't extend the frame displaying content (the width, visually), it seems to run significantly faster. 

While the speed increase could be attributed to to pulling less columns, it could also potentially be worth considering something in the client side that may be causing the issue, especially considering the errors in the console.

**Comment by iwaffles** [comment] 2016-10-03 19:45
After chatting with @tlrobinson it seems (to me at least) that this might be client side.

The query does fully execute the endpoint and possibly hanging on the client side. After clicking cancel I see the full dataset every time (compared with running the query natively against the DB – outside of Metabase). 

Some of my notes/observations:

- When columns are limited in scope to a smaller number (7 in my case), this is not an issue.
- When columns are unlimited and range around 25, this is an issue.
- /dataset returns in a quick amount of time (less than 500ms) for large queries with multiple columns.
- Running the query causes the javascript error from the console as noted (screenshot) above. `invalid array with`
- Clicking cancel causes the javascript error seen above. `invalid array with`
- Canceling a few times causes the full dataset to appear. Confirmed by testing against a query that was run outside of Metabase against the db.

**Comment by HugoCornu** [comment] 2016-10-14 08:46
@tlrobinson 
This issue should be labeled as a bug 


MySQL 5.5
Firefox up to date
Metabase 0.20 from jar file (same on Metabase 0.19.3

simple query (just a SELECT with LIMIT 1) is instantaneous on SQLWorkbench or console
"DOING SCIENCE" for ever on Metabase
Clicking cancel once does nothing
Clicking cancel a second time show the results

**Comment by alexcohaniuc** [comment] 2016-11-01 12:06
any update on this?
I have the same issue with when queering a table with a lot of columns

**Comment by tlrobinson** [comment] 2016-11-16 23:04
@iwaffles @HugoCornu @alexcohaniuc @hugocar We believe this has been fixed in `master`. If possible could you try it out and confirm.

You can build from `master`, use the `metabase/metabase-head:latest` Docker image, or this jar: https://9000-30203935-gh.circle-artifacts.com/6/home/ubuntu/metabase/target/uberjar/metabase.jar

**Comment by tlrobinson** [comment] 2016-11-17 01:45
This is a duplicate of #3205. Please comment there if you can confirm this is or isn't fixed.

**Closed by tlrobinson** 2016-11-17 01:45 UTC
Labels: Bug, Query Builder/Native
