### ISSUE TITLE
Filtering on "count" throws error

### ISSUE THREAD

**Issue by shafy** [metabase/metabase#11648] opened 2020-01-07 16:02 UTC
**Describe the bug**

Filtering on the "Count of rows" property throws this error:
```
No matching signature for operator > for argument types: INT64, STRING.
Supported signatures: ANY > ANY at [2:318]
```

Here's the relevant part of the generated SQL:
```
ORDER BY `location_id` ASC) `source` WHERE `source`.`count` > '30'
```

30 shouldn't be a string.

Metabase 0.34 and BigQuery. It was working before updating to 0.34.

This is pretty severe as filtering on count is done often.

**Comment by flyingmachine** [comment] 2020-01-08 14:38
@shafy could you provide more details?

* When you say "count of rows property", what are you referring to? I can't tell if it's a column in your database, a virtual column on a `GROUP BY` query, or something else
* Can you share more about the context in which this query is being generated?
* If possible, could you share the entire query with all confidential / sensitive data and identifiers removed?

Thanks!

**Comment by sbelak** [comment] 2020-01-08 15:11
Likely a dupe or related to #10552

**Comment by shafy** [comment] 2020-01-08 15:30
Thanks @sbelak, it's a duplicate of that issue.

@flyingmachine it's better explained here #10552 but I mean the pre-defined "Count of rows" metric that you can choose in "Summarize" from the GUI. Here's the entire query:

```
SELECT `source`.`location_id` AS `location_id`, `source`.`count` AS `count`
FROM (SELECT `simplified_prod.rentals`.`location_id` AS `location_id`, count(*) AS `count` FROM `simplified_prod.rentals`
WHERE (`simplified_prod.rentals`.`status` = 0
   AND `simplified_prod.rentals`.`rental_type` = 0)
GROUP BY `location_id`
ORDER BY `location_id` ASC) `source` WHERE `source`.`count` > '30'
LIMIT 1048576
```

**Comment by mazameli** [comment] 2020-01-08 18:24
Closing as dupe of #10552

**Closed by mazameli** 2020-01-08 18:24 UTC
Labels: .Duplicate, .Need More Info, .Needs Triage, Type:Bug
