### ISSUE TITLE
User with no data access to a question can create subscription, but it fails to send

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#20892] opened 2022-03-08 16:51 UTC
**Describe the bug**
I have access to a dashboard, but I don't have access to all questions. I don't have data access to 7 cards.
I can create a subscription, but when I send the email now, it fails.

**Logs**
```
[eecd016d-5646-4019-9fe1-03cda7dd7925] 2022-03-07T09:20:12-05:00 DEBUG metabase.server.middleware.log POST /api/pulse/test 400 4.4 ms (0 DB calls) 
{:errors
 {:cards
  "value must be an array. Each value must satisfy one of the following requirements: 1) value must be a map with the following keys `(collection_id, description, display, id, include_csv, include_xls, name, dashboard_id, parameter_mappings)` 2) value must be a map with the keys `id`, `include_csv`, `include_xls`, and `dashboard_card_id`. The array cannot be empty."}}
```

**To Reproduce**
1. As a non-admin user in stats, go to https://stats.metabase.com/dashboard/166-customer-revenue. There are 7 cards that don't show any data because of data permissions.
2. Sharing > Dashboard and Subscriptions > Email > Yourself > Send email now
3. The button turns to "Sending failed"

**Expected behavior**
The user should receive the email with the data they have access to.

**Screenshots**
![image](https://user-images.githubusercontent.com/32561114/157285308-1a93f592-6901-4c2d-a789-20a1e1e4a66e.png)

**Information about your Metabase Installation:**
Built on 2022-03-08
Branch: master
Hash: 3a257c2

**Severity**
Low

**Additional context**
Related to [18009](https://github.com/metabase/metabase/issues/18009), but it doesn't even send the email.

As an Admin, Noah managed to send the report to himself.
He also created a user, blocked access to one DB, and still managed to receive the report as expected (questions with blocked data weren't displayed while questions that the user had access were displayed normally).

The dashboard never finishes loading, although all cards are loaded/blocked.
![image](https://user-images.githubusercontent.com/32561114/157285864-3dfdeff1-9bca-4cb7-a962-a95e205f7991.png)

**Comment by flamber** [comment] 2022-03-09 13:15
Duplicate of #18154, since it has nothing to do with no-data permissions, but collection permissions.

**Closed by flamber** 2022-03-09 13:15 UTC
Labels: Type:Bug, Priority:P2, Reporting/Dashboards, Reporting/Pulses, Administration/Permissions
