### ISSUE TITLE
Generating fingerprint for Field 312 ‘time’: java.lang.String cannot be cast to java.lang.Number

### ISSUE THREAD

**Issue by bugo99iot** [metabase/metabase#7034] opened 2018-02-28 09:37 UTC
Hi,

I'm a Metabase Postgres user and when I Sync my database I get the error below:

> Generating fingerprint for Field 312 ‘time’: java.lang.String cannot be cast to java.lang.Number

Being a SQL column the field 'time' stores integers and nan only.

Is this a known issue?

Thank you.

**Comment by senior** [comment] 2018-04-26 16:08
I'm going to need some more information on this. The column name is `time` and it stores integers and NaN only. What datatype is that field? Looking at the docs for the PostgreSQL Time datatype, it is a string not a number, so not sure what kind of column we're failing to fingerprint.

**Comment by viluon** [comment] 2019-03-06 13:00
Similar issue here:
```
03-06 13:57:46 INFO sync.analyze :: fingerprint-fields Analyzed [***************···································] 😕   30% Table 1,196 'prediction_curve'
03-06 13:57:46 ERROR sync.util :: Error generating fingerprint for Field 23,318 'year_display': java.sql.Date cannot be cast to java.lang.Number
("clojure.lang.RT.doubleCast(RT.java:1348)"
 "bigml.histogram.core$when_double.invokeStatic(core.clj:104)"
 "bigml.histogram.core$when_double.invoke(core.clj:103)"
 "bigml.histogram.core$insert_simple_BANG_.invokeStatic(core.clj:109)"
 "bigml.histogram.core$insert_simple_BANG_.invoke(core.clj:106)"
 "--> sync.analyze.fingerprint.fingerprinters$histogram.invokeStatic(fingerprinters.clj:179)"
 "sync.analyze.fingerprint.fingerprinters$histogram.invoke(fingerprinters.clj:175)"
 "sync.analyze.fingerprint.fingerprinters$with_error_handling$fn__37235$fn__37240.invoke(fingerprinters.clj:117)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:148)"
 "sync.util$do_with_error_handling.invoke(util.clj:143)"
 "sync.analyze.fingerprint.fingerprinters$with_error_handling$fn__37235.invoke(fingerprinters.clj:117)"
 "sync.analyze.fingerprint.fingerprinters$col_wise$fn__37198$fn__37203.invoke(fingerprinters.clj:32)"
 "sync.analyze.fingerprint.fingerprinters$col_wise$fn__37198.invoke(fingerprinters.clj:29)"
 "sync.analyze.fingerprint$fn__43086$fingerprint_table_BANG___43091$fn__43092.invoke(fingerprint.clj:41)"
...
```

**Comment by sbelak** [comment] 2019-03-07 16:36
@viluon could you show me what /api/field/23318 returns

**Comment by flamber** [comment] 2020-06-02 12:20
Closing, since not enough information to understand the root cause. Please try latest release 0.35.4

**Closed by flamber** 2020-06-02 12:20 UTC
Labels: .Need More Info, Administration/Metadata & Sync, Priority:P3, Type:Bug
