### ISSUE TITLE
Can Metabase expand horizontally?

### ISSUE THREAD

**Issue by futureio** [metabase/metabase#6038] opened 2017-09-25 07:19 UTC
I recently found some problems with my metabase usability, and horizontal expansion might be a good idea. Does the metabase support horizontal extension? How?

**Comment by mazameli** [comment] 2017-09-25 16:41
I believe this is a duplicate of https://github.com/metabase/metabase/issues/2754.

**Closed by mazameli** 2017-09-25 16:41 UTC
Labels: Duplicate
