### ISSUE TITLE
Multiple joins against a single table and field filters in SQL questions

### ISSUE THREAD

**Issue by dtheodor** [metabase/metabase#4478] opened 2017-03-02 16:54 UTC
I have an SQL question where my main table joins with a dimension table twice (let's say I have a 'date modified' and 'date accessed', which are both foreign keys to a single date table). I want to create a dashboard filter on both of these columns, but I can't! When creating the field filters in the chart itself, I only get a single choice, the target date table,  when in fact there should be two choices, since the target table is joined twice. In these scenarios the target table needs to be aliased, exactly how it has to be done in SQL itself when you have to join the same table twice in order to resolve the ambiguity.

When I do wireup my chart with a dashboard filter this way, the actual filtering is performed only on one of the two table aliases. Not sure how metabase chooses which one to filter.

This is not an issue for non-SQL questions, where if you create a dashboard filter, you get to explicitly pick the field out of a list of all tables, which are duplicated in case the same table is joined twice.

**Comment by salsakran** [comment] 2017-03-02 23:46
I'm having a bit of trouble following. Can you share the SQL you're trying to templatize? 

In general, you should be able to have two different template variables point to the same field, and refer to them in the SQL template and wire up dashboard filter separately.

**Comment by dtheodor** [comment] 2017-03-03 09:30
```sql
select sum(cost)
from items
join location as location_manufactured ON items.location_manufactured_id = location.id
join location as location_sold ON items.location_sold_id = location.id
[[WHERE {{region_manufactured}}]]
[[AND {{region_sold}}]]
```
The raw SQL I want to be generated when filters are applied is

```sql
select sum(cost)
from items
join location as location_manufactured ON items.location_manufactured_id = location.id
join location as location_sold ON items.location_sold_id = location.id
WHERE location_manufactured.region = 'a region'
AND location_sold.region = 'another region'
```

So, I want my dashboard to provide two filters on location, one to filter the region where manufacturing took place and the other to filter where it's sold.

When I create the two field filters in the question, the filter field allows only 1 selection, the field 'region' from table 'location'. So I have 2 filters, both on the same table field. When I go to the dashboard and create a filter, I see a dropdown with two options, both named 'Location Region'. Selecting either of them results in fitlering the location manufactured.

**Comment by salsakran** [comment] 2017-03-04 02:11
Ah, ok. I get it now.

**Comment by JoeSham** [comment] 2017-10-16 12:01
Any update on this issue? @salsakran

**Comment by JoeSham** [comment] 2018-04-27 13:25
Any update here? @salsakran @camsaul @senior

**Comment by flamber** [comment] 2019-07-10 21:45
This is a duplicate of #3324, since table aliases are currently not supported for Field Filters.

**Comment by flamber** [comment] 2020-05-30 11:36
Closing in favor of #3324

**Closed by flamber** 2020-05-30 11:36 UTC
Labels: Querying/Native, Querying/Parameters & Variables, Type:New Feature
