### ISSUE TITLE
Friendly Table and Field Names should be disabled by default in non-english languages

### ISSUE THREAD

**Issue by TjrGithub** [metabase/metabase#13047] opened 2020-07-31 13:59 UTC
**Describe the bug**
If you use Metabase in German, names get mangled out-of-the-box, by "Friendly Table and Field Names". This setting is know not to work well except in English. It should be disabled by default.

**Logs**
see #13046 

**To Reproduce**
see #13046

**Expected behavior**
If language is not english and all settings are default, then please disable friendly names.

**Screenshots**
see #13046

**Information about your Metabase Installation:**
see #13046

**Severity**
Bad. It took me an hour of bug reporting to find out about this. What else is hidden in Metabase? Can I show this to my client, if there are more "surprises"?

**Additional context**
see #13046

**Comment by flamber** [comment] 2020-07-31 14:00
Duplicate of #5878

**Closed by flamber** 2020-07-31 14:00 UTC
Labels: .Needs Triage, Type:Bug
