### ISSUE TITLE
Box plots (and/or violin plots)

### ISSUE THREAD

**Issue by h3kker** [metabase/metabase#15595] opened 2021-04-13 14:56 UTC
**Is your feature request related to a problem? Please describe.**
Box plots are a nice way to analyze and compare distributions of data points. Especially when you plot categories on x and the values on y, it would be nice to see where the median and quartiles are. 

**Describe the solution you'd like**
Show boxplots (or violin plots for continuous distributions). See attached file. See also https://discourse.metabase.com/t/does-metabase-currently-support-box-plot/7076/4

<img width="194" alt="Screenshot 2021-04-13 at 16 52 50" src="https://user-images.githubusercontent.com/1489014/114573804-fd9f0d80-9c78-11eb-9846-bfecacd6aacf.png">

**Describe alternatives you've considered**
Scatterplots are nice, but a) truncate the table and b) don't let me immediately compare medians and quartiles.
<img width="328" alt="Screenshot 2021-04-13 at 16 55 35" src="https://user-images.githubusercontent.com/1489014/114573932-1dcecc80-9c79-11eb-9fb5-c8244664c75a.png">
(note: not the same data)

**How important is this feature to you?**
We need this quite often to compare different categories. All our R reports contain at least one ;-)

**Additional context**

**Comment by Rhinogradentia** [comment] 2021-04-13 15:04
Yeah - that would be a really needed feature
+1

**Comment by flamber** [comment] 2021-04-13 15:23
Duplicate of #10783

**Closed by flamber** 2021-04-13 15:23 UTC
Labels: .Needs Triage, Type:New Feature
