### ISSUE TITLE
Tooltips in line chart show wrong values

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#6806] opened 2018-01-29 10:28 UTC
Hi,
I have built a line chart based on a SQL question with 3 fields grouped by month, and am displaying one field as a line. While the value per month for the line is correctly displayed, the tooltip shows the values of the two additional series (which are not shown in the chart) for the next month, which is wrong. 
So basically, the line shows the January value but the tooltip shows February values for the hidden fields, and so on. 
Switching to a bar chart, the tooltip values are showing correctly, so this seems like a bug related to a line chart.

Your browser and the version: Chrome Version 63.0.3239.132 (64-Bit)
Your operating system: Windows 10
Your databases: BigQuery
Metabase version: v0.27.1
Metabase hosting environment: Heroku

**Comment by jornh** [comment] 2018-02-02 03:28
Skynde like a duplicate of #6401 

Would be good if you could take 0.28.0-RC2 e.g. in the form of http://downloads.metabase.com/v0.28.0-RC2/metabase.jar for a test-drive to see if it fixes your issue

**Comment by jornh** [comment] 2018-02-11 19:52
@HelenMertes with Metabase v0.28.1 now available can you confirm if my assumption about #6404 was right and this got fixed?

**Comment by HelenMertes** [comment] 2018-02-12 08:38
Yes, it is correct now in the line chart. However, in the bar chart the values of the series not shown in the chart have disappeared altogether,

**Comment by jornh** [comment] 2018-02-12 10:33
Great & not so great 😬 
is the bar chart issue similar to #6842?

Guess it’s easier to keep on top of thinks if you close this issue and either add to #6842 if appropriate or open a new

**Comment by tuaris** [comment] 2019-04-22 18:18
In bar charts the value is displayed, but one of the series is incorrect when using the **Stack - 100%** option:

![Stacked Barchart](http://venus.morante.net/downloads/unibia/screenshots/barchart-wrong-percenta.png)

**Comment by paulrosenzweig** [comment] 2019-05-08 16:22
@tuaris, can you elaborate on the error? Are those percents way off the source data?  Or, is the issue that the 99.52% is rounded to 100%?

**Comment by tuaris** [comment] 2019-05-08 16:27
@paulrosenzweig yes, it's the 99.52% being rounded off to 100%.

**Comment by paulrosenzweig** [comment] 2019-05-08 16:44
Closing this as the original issue was resolved. I've opened a new one to document this rounding issue.

**Closed by paulrosenzweig** 2019-05-08 16:44 UTC
Labels: Bug, Priority/P1, Timezones/Calendars, Visualization
