### ISSUE TITLE
SQL syntax error when use nested query with filter

### ISSUE THREAD

**Issue by Splinter37** [metabase/metabase#14284] opened 2021-01-06 18:46 UTC
**Describe the bug**

**To Reproduce**
1. Write query select * from any_table left join {{#2}} as nested_table on any_table.first_column = nested_table.second_column where {{column}} 
2. {{column}} is setup as field filter on any_table.first_column
3. When filter si empty all is right
4. When setup filter on any value, return syntax error
5. When delete left join on {{#2}} all is right
6. Nested query is corect

I trying many alternative select, but still is problem where use any nested_table with any filter 

_**This problem occurred after updating the application to version 0.37.4**_

**Expected behavior**
Select is writen corectly. I expected return corectly data

**Screenshots**
![4](https://user-images.githubusercontent.com/77072483/103808119-c278b700-5057-11eb-99db-1e8293c78915.png)
![3](https://user-images.githubusercontent.com/77072483/103808125-c3a9e400-5057-11eb-8a64-bb9d8fa93c71.png)
![1](https://user-images.githubusercontent.com/77072483/103808128-c4427a80-5057-11eb-8aea-0de307e7e495.png)
![2](https://user-images.githubusercontent.com/77072483/103808166-d3292d00-5057-11eb-9219-d0c1fabd1e70.png)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "sk",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.4.0-112-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.7 (Ubuntu 11.7-2.pgdg16.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-12-17",
      "tag": "v0.37.4",
      "branch": "release-x.37.x",
      "hash": "e0d5287"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}

**Severity**
Some existing select´s don´t work

**Logs**
[Metabase.log](https://github.com/metabase/metabase/files/5777577/Metabase.log)

**Comment by flamber** [comment] 2021-01-06 21:54
Hi @Splinter37 
Which version were you using before?
I cannot reproduce on H2, MySQL or MariaDB with Metabase 0.37.5.
Can you check the MySQL log to see the full query that fails or any debug details that the database log can provide?

**Comment by Splinter37** [comment] 2021-01-07 09:18
Hi, 
I trying update to newest version 0.37.5, but problem it still lasts :-/

I not have permit to DB for looking to LOG, DB is managed by an external vendor. 

I wrote to them, but they say they don't see it anywhere, that the query really went to DB: - /

**Comment by Splinter37** [comment] 2021-01-07 12:09
After downgrade to 0.35.2. is all right ... 

![image](https://user-images.githubusercontent.com/77072483/103891097-82621480-50e9-11eb-87d9-63c8d6d7d237.png)

**Comment by flamber** [comment] 2021-01-07 12:22
@Splinter37 Okay, but it doesn't help with figuring out what the problem was. The query is sent to the database, otherwise you wouldn't get an error like that - that error message comes from the database.
Which version of MySQL are you using?

**Comment by Splinter37** [comment] 2021-01-08 10:40
Version MySQL is MySQL 5.7.31

I think it will be some BUG in the metabase, which in such a composition will send a syntactically incorrect query to the DB (some extra comma is possible).

Unfortunately I don't have more info, for now it will work with version 0.35 and in time there may be someone to whom it also happens and provide more information

**Comment by flamber** [comment] 2021-01-29 18:27
Until we have a log from the database, which clearly describes what the problem is, then it's going to be very difficult to figure out.
Closing this, but please comment back when you have more details.

**Closed by flamber** 2021-01-29 18:27 UTC
Labels: .Needs Triage, Type:Bug
