### ISSUE TITLE
I can create a collection/sub-collection while saving a question

### ISSUE THREAD

**Issue by shyrahnama** [metabase/metabase#25459] opened 2022-09-16 14:57 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm saving a question and choosing the collection it should go in because I often need to create a new sub-collection, but need to stop the process of saving the question, go into a new tab to create the collection, and then come back and re-save the original question. On occasion I've gotten distracted and forgotten to save the question, and lost it.

<img width="755" alt="image" src="https://user-images.githubusercontent.com/2866012/190668591-bb965ff0-3da2-4ed8-9a7e-42bcc0576565.png">

**Describe the solution you'd like**
The ability to create a collection as I'm saving

**Describe alternatives you've considered**
None

**How important is this feature to you?**
I probably hit this issue 12 times a day, and it makes it really hard for me to get my team to stay organized.

**Additional context**

**Comment by flamber** [comment] 2022-09-16 15:11
Duplicate of #4020

**Closed by flamber** 2022-09-16 15:11 UTC
Labels: Type:New Feature, .Needs Triage
