### ISSUE TITLE
BUG: Snippet Results vs SQL Results are different

### ISSUE THREAD

**Issue by henricksone** [metabase/metabase#23139] opened 2022-06-03 12:52 UTC
**Describe the bug**
Saved Metabase snippet is returning the wrong data. If I copy the Snippet Code and run it on it's own (Not as snippet), I get correct data. In fact I have determined that the snippet returns the data of a different snippet. 

**Logs**
api/user/current:1          Failed to load resource: the server responded with a status of 401 ()
NativeQueryEditor.jsx:336 Uncaught TypeError: Cannot read properties of null (reading 'offsetHeight')
    at i.value (NativeQueryEditor.jsx:336:29)
    at i.value (NativeQueryEditor.jsx:351:12)
    at o (debounce.js:13:29)
    at delay.js:7:17
react-dom.production.min.js:49 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at react-dom.production.min.js:49:67
    at it (react-dom.production.min.js:50:217)
    at t.findDOMNode (react-dom.production.min.js:289:336)
    at h.value (ExplicitSize.jsx:47:23)
    at ExplicitSize.jsx:121:28
    at c (throttle.js:32:21)
react-dom.production.min.js:49 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at react-dom.production.min.js:49:67
    at it (react-dom.production.min.js:50:217)
    at t.findDOMNode (react-dom.production.min.js:289:336)
    at h.value (ExplicitSize.jsx:47:23)
    at ExplicitSize.jsx:121:28
    at c (throttle.js:32:21)
react-dom.production.min.js:49 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at react-dom.production.min.js:49:67
    at it (react-dom.production.min.js:50:217)
    at t.findDOMNode (react-dom.production.min.js:289:336)
    at h.value (ExplicitSize.jsx:47:23)
    at ExplicitSize.jsx:121:28
    at c (throttle.js:32:21)
react-dom.production.min.js:49 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at react-dom.production.min.js:49:67
    at it (react-dom.production.min.js:50:217)
    at t.findDOMNode (react-dom.production.min.js:289:336)
    at h.value (ExplicitSize.jsx:47:23)
    at ExplicitSize.jsx:121:28
    at c (throttle.js:32:21)

**To Reproduce**
1. Go to  a new SQL report in Metabase.  Site Name: Operation Mobilization
2. Run these 2 separately 
SELECT * FROM ({{snippet: Last_Gift_Support}}) AS LGS ORDER BY 1
SELECT * FROM ({{snippet: Last_Gift_Project}}) AS LGP ORDER BY 1
3. Last_Gift_Support is actually returning the same data as Last_Gift_Project.
4. If I copy the SQL code from the Last_Gfit_Support snippet and run it then I get correct data. Somehow the call to the snippet is pulling from the wrong snippet. 

**Expected behavior**
I expect Last_Gift_Support to return correct data and not the data from the other snippet. 

**Screenshots**
not applicable

**Severity**
Our reports heavily use snippets.  We can't trust any reports until this is fixed. 
 
**Additional context**
Doubt it is relevant but we use Virtuous CRM, but I use Metabase to write the SQL and snippets. But the reports are displayed in Virtuous CRM. 

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "4.14.273-207.502.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-16",
      "tag": "v1.43.1",
      "branch": "release-x.43.x",
      "hash": "7f1a1c4"
    },
    "settings": {
      "report-timezone": "US/East-Indiana"
    }
  }
}
```

**Comment by flamber** [comment] 2022-06-03 13:03
Duplicate of #15387 - instead of editing part of the snippet variable name, then remove it and add the new via the sidebar.

**Closed by flamber** 2022-06-03 13:03 UTC
