### ISSUE TITLE
Create the “super-user” role, halfway between admin and regular users 

### ISSUE THREAD

**Issue by EBoisseauSierra** [metabase/metabase#13091] opened 2020-08-10 15:45 UTC
## Issue

In our current usage of Metabase, we have 3 levels of users:

* instance/site users (many),
* instance/site “master” users (a couple),
* cross-instances sysadmins (a few).

Sysadmins would love to grant some “mundane” privileges (e.g. creating segment and metrics, managing collection rights) to master users, yet promoting them as Admins is sometimes seen as “too dangerous” as they'd have then the power to screw things quite a lot.

## Feature request

We would love to **have a new _super-user_ type of user, halfway between _admin_ and _regular users_**. 
Such user group would have access to some of the admin privileges only. 

In our scenario, they'd have access to “Data model” and “Permissions” setting tabs. I'd imagine that others might have different needs, so Admins might be able to toggle privilege for: Settings (unlikely), People, Data Model, Databases, Permissions, and Troubleshooting — or finer subdivisions thereof.

## Alternative solutions

Well, I can't think of any, as with Admins it's “all or nothing”.

## Feature importance

It would be a very nice to have.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment] 2020-08-10 15:52
Duplicate of #6799/#9853 ?

**Comment by EBoisseauSierra** [comment] 2020-08-10 16:05
Definitively, indeed. I'd say the scope of this feature request is a bit more generic (and the [things I'd like the new user level to be able to do](https://github.com/metabase/metabase/issues/9853#issuecomment-491989602) is slightly different than in these US), but I'm happy for you to close it if you think it's better that way.

**Comment by flamber** [comment] 2020-08-10 16:37
Different roles to this extend likely belongs in the Enterprise Edition, but it's more generic than #9853, so let's leave it open.

**Comment by camsaul** [comment] 2021-01-07 22:54
Related: #2682

**Comment by Will-Angel** [comment] 2021-09-29 17:33
This enhancement would be helpful in our compliance heavy space where the ability to add new users must be controlled more tightly than the ability to add new databases or update the data model.

**Comment by luizarakaki** [comment] 2022-08-31 17:45
The permissions improvements on 43 accomplished most of what was demanded here.
Available on Pro/EE plans
https://www.metabase.com/releases/2022-05-02-Metabase-0.43

**Closed by luizarakaki** 2022-08-31 17:45 UTC
Labels: Type:New Feature, Administration/Permissions, Administration/
